### ISSUE TITLE
support anonymous issues

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1014]
it would be nice to be have some form to enable users to report bugs without creating a github account. since this is a public repo we could just have a dummy account that doesn't even need access to the wesnoth repo to let a script create issues with it. One of the problems with suhc a solution that is that i am unuse whethe rit also alows user to respons in existent issues

**Comment by CelticMinstrel** [comment]
There is an online service that enables anonymous issue submission to github. It's called [Git Reports](https://gitreports.com/). I don't know if it's good, but it could be worth investigating.

**Comment by matthiaskrgr** [comment]
Hm, out of curiosity, does it provide a way to prevent spam/ads?

**Comment by pydsigner** [comment]
What I think could kill two birds with one stone is to have an email address, say bugs@wesnoth.org, where anonymous or sensitive bug reports could be directed.

**Comment by CelticMinstrel** [comment]
So is anyone opposed to using Git Reports to allow anonymous submissions? I don't see anything on its website about spam/ad prevention, unfortunately. The email method that @pydsigner suggests could also be a valid substitute for Git Reports, though it would lock out anyone who doesn't have an email (not sure if that's likely enough to matter).

**Comment by GregoryLundberg** [comment]
How about someone create a web form on wesnoth.org which submits the issue using a robot name. Require a Wesnoth account and then handle abuse/spam in out normal manner?

**Comment by CelticMinstrel** [comment]
If we accept anonymous bugs, they could be posted to github by the @wesnoth-bugs account.

**Comment by Vultraz** [comment]
No one pursued this further (either Git Reports or some other method), and honestly it hasn't really been an issue as we anticipated at the time. At this point, I feel it would just add an additional administrative component to maintain, so I'm closing this.
