### ISSUE TITLE
Import GNA issues

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#1015]
We need to import all the issues from GNA, especially those that are still open.

**Comment by CelticMinstrel** [comment]
Looks like a python (or similar) script to import them should be relatively simple to write using the GitHub web API. I exported all open issues as of... an hour or two ago? I also exported all closed issues separately, in case someone's interested in those, but there's nearly 7k of them (compared to just 648 open ones), so we probably shouldn't import those.

**Comment by CelticMinstrel** [comment]
(API documentation [here](https://developer.github.com/v3/issues/#create-an-issue).)

**Comment by CelticMinstrel** [comment]
I now have a working script for importing the issues. Basically it just needs to be run, though I could also add downloading and reposting of attachments first.

**Comment by CelticMinstrel** [comment]
A sample import has been completed at [CelticMinstrel/wesnoth](https://github.com/CelticMinstrel/wesnoth/issues). Since then I've made a few more small changes to the script which include adding severity, priority, os, and release to the opening post. I could transfer release to milestone, but I'm not sure that would really be useful (some of the bugs have the release set to pretty old values), so I probably won't.

Are there any preferences on how to handle attachments? There are 197 attachments in total, and the web API doesn't support uploading them, so I'd have to either do it manually or find a different way of adding them (for example, text or saved game attachments could be converted to gists, image attachments could be uploaded to an image hosting site, etc).

There's also the question of which account should post them. Broadly, there are three options:

* Use my own account (or, send the script to someone else and have them use their account).
* Use a new account specifically dedicated for posting the GNA bugs. (It could be called something like "wesnoth-gna".)
* Use an account called something like "wesnoth-anon" which would then also be used if #1014 is implemented.

@vultraz said that he would think about these options.

**Comment by jyrkive** [comment]
Out of the account options, "wesnoth-anon" sounds like the best option to me.

**Comment by CelticMinstrel** [comment]
For the record, @vultraz seems to prefer "wesnoth-bugs" (but otherwise the same idea).

**Comment by CelticMinstrel** [comment]
The import is completed. Fixing up issues with the import is covered separately in #1676.
