### ISSUE TITLE
ingame help command help misleading

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#1018]
![help](https://cloud.githubusercontent.com/assets/476013/25608486/4f4f491c-2f1b-11e7-82ea-01b6ddefabde.png)

**Comment by matthiaskrgr** [comment]
Ok, I figured out the ":" refers to opening the console... >.<

Anyway is there a way we could make this more clear?

**Comment by Wedge009** [comment]
Would it be better to just say 'try help for a list of available commands'?

**Comment by matthiaskrgr** [comment]
Yeah, probably.
Or even make the console check, if there is an unknown command that starts with a ":", print a different error to try without ":".

**Comment by GregoryLundberg** [comment]
```
:help
Unknown command, did you mean: help?
```

```
:plugh
Unknown command.
```

**Comment by CelticMinstrel** [comment]
Yeah, comparing an unknown command to known ones in order to generate suggestions would be great!
