### ISSUE TITLE
Named locations not included in editor location palette

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#1023]
While adding a new named location does add the name to the list, existing named locations are not added when the map is loaded. This would make it difficult to alter existing locations.

**Comment by CelticMinstrel** [comment]
Addendum: The locations list also doesn't update if you open a new map, meaning you'll still see all the locations from the old map (assuming they were added in the current session).

**Comment by gfgtdf** [comment]
yes the locations seems top be completeley unrelated to the actual map and onyl related to the 'session'. i think th first one (existing named locations are not added when the map is loaded) it more annyoing than the second one (meaning you'll still see all the locations from the old map )

**Comment by CelticMinstrel** [comment]
Yes, it is indeed more annoying, but I have a feeling the fix for both would prove to be the same.
