### ISSUE TITLE
Reimplement tiling options in the storyscreen

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#1027]
The old storyscreen supported a number of tiling options. The GUI2 version does not. This needs fixing.

**Comment by kallaballa** [comment]
I'd like to look into this bug, but from your description i have no idea what the problem is. Could you please elaborate?

**Comment by CelticMinstrel** [comment]
See [the wiki](https://wiki.wesnoth.org/IntroWML) for reference. There are several keys described there (under `[background_layer]`) that specify scaling and tiling options. These no longer function as advertised.

**Comment by AI0867** [comment]
Partially re-implemented in 4f79fed84d059f43eef5ac44da3fc009facfd226, but unless someone wants to modify the widgets, the WML interface should probably be changed.

**Comment by CelticMinstrel** [comment]
So that's partial because it only supports the case where horizontal and vertical are set to the same value, I guess? Full support would require alteration of the GUI2 canvas WML as well.

**Comment by Vultraz** [comment]
Where the hell even is that commit? I can't find it.

**Comment by Vultraz** [comment]
Anyway, fully implemented above.

**Comment by CelticMinstrel** [comment]
Nice! Does that finally cover everything, then? It'd be nice to expand the test added by @AI0867 so that it covers more cases, too.

I'm kinda surprised (and slightly suspicious) that this seems to have been done without touching the GUI2 canvas code at all...

**Comment by AI0867** [comment]
As that commit was on a branch on my own fork, it was not actually 'added'. I've now added the testcase in 39c3f21b9b13fb19175ceead5910713d7fef37f6.

**Comment by CelticMinstrel** [comment]
Ah, okay. I guess that explains why vultraz couldn't find it... >_>
