### ISSUE TITLE
Starting Battle For Wesnoth adds EN-US keyboard layout

### ISSUE THREAD

**Issue by Hontaro** [wesnoth/wesnoth#1029]
When starting Wesnoth, the Keyboard Layout `English (United States) - US` is added to the available Keyboards (Language Bar). The Keyboard Layout persists upon closing the game and only disappears when restarting the PC.

Steps to reproduce:
* Make sure the English keyboard layout is not listed in the language bar as available keyboard layout.
* Start Battle for Wesnoth.

The version of the game is Windows 1.12.6 running on Windows 7.

**Comment by CelticMinstrel** [comment]
Does this occur on 1.13.7?

**Comment by Hontaro** [comment]
I do get an initial error on startup with 1.13.7, I assume it's because I still have 1.12.6 installed:

```
Error validating data core.

Details:

    Core ID: default
    The ID is already in use.
    Skipping the core.
```
It still starts up and the bug does not occur. Should I uninstall 1.12.6 first and try again?

**Comment by CelticMinstrel** [comment]
There should normally be no conflict between 1.12.6 and 1.13.7, unless your gamedata directories are different from the default. Normally they'd be in "My Documents\My Games\Wesnoth1.12" and "My Documents\My Games\Wesnoth1.13", I think. (The latter is correct, at least; I don't have 1.12 installed on Windows.)

**Comment by grz0** [comment]
> Does this occur on 1.13.7?
I checked on 1.13.11, it is fixed.
