### ISSUE TITLE
Set up a new set of mailing lists

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#1030]
With GNA going down, the mailing lists will be disappearing too. If I'm not mistaken, some contributors (particularly translators) rely heavily on them, so we need to find a replacement fast.

There are two broad options:

1. Find a website that provides a free mailing list service. For example, @ln-zookeeper discovered [Librelist](http://librelist.com), which is a very simple service and easy to use, though it has no real administrative functions for the mailing lists (but I don't know if those are needed). It may also be notable that none of the lists hosted by it have seen activity in the past two years.

2. Set up a mailing list on the Wesnoth servers, or on the servers of some other contributor (for example, the Jenkins server?). There is a variety of different mailing list software to choose from in this case. [GNU Mailman](https://www.gnu.org/software/mailman/) is, I believe, the software that GNA used and thus might be more familiar to some members. [Mlmmj](http://mlmmj.org/) looks relatively lightweight and easy-to-use, though it hasn't been updated in two years. Other promising-looking possibilities include [Sympa](http://www.sympa.org/) and [Dada Mail](http://www.dadamailproject.com/).

**Comment by AI0867** [comment]
There is an VM on the server dedicated to exim4 and mailman. Currently its only use is for a commits list (github sends an email to commits@wesnoth.org and the list forwards it).

**Comment by Vultraz** [comment]
@AI0867 was that for the old commits ml list? If so, I propose we drop it. In fact, I propose we drop all MLs except for the translators one, since that seems to be used. Though I suggest recommending they come and request a language-specific channel on the Discord server if desired, so we can phase out the MLs.

**Comment by CelticMinstrel** [comment]
As usual, you come in and completely miss the point.

**Comment by CelticMinstrel** [comment]
I believe this has been done. Can someone confirm?

**Comment by CelticMinstrel** [comment]
I believe this has been done. Can someone confirm? Maybe @soliton- knows?

**Comment by soliton-** [comment]
I think so. The mailing lists are listed here: http://mailman.wesnoth.org

If there's anything still missing someone comment.
