### ISSUE TITLE
Consider adding a "try  to reconnect" button to the "player disconnected" dialog (GNA #3386)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1034]
**[Original submission](https://gna.org/bugs/index.php?3386)** by anonymous on 2004-05-13

(Reproduced on GNU Linux)
Release: 0.7.7-CVS
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-09-21**

**ott wrote:**

> See https://savannah.nongnu.org/bugs/index.php?func=detailitem&amp;item_id=8948 for Savannah history.

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-09-23**

**anonymous wrote:**

> Just thought I'd make a note here that I've discussed a potential solution with yogibear. The solution involves giving the host on a disconnect / player left message the option to set control state for the slot to &quot;NONE&quot; or &quot;wait&quot;, which is equivalent to not assigning control for that side yet. The side's control can later be assigned with :control.
> 
> 
> 
> The state &quot;NONE&quot;/&quot;wait&quot; would probably allow even this to be fulfilled:
> 
> 19:57 &lt;Soliton&gt; a nice feature (inspired by this bug [green games in the lobby]) would be to mark games special that are in need for a (replacement) player.

**Comment by Pentarctagon** [comment]
Closing in favor of #1261
