### ISSUE TITLE
Provide useful object/weapon displays (GNA #4120)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1040]
**[Original submission](https://gna.org/bugs/index.php?4120)** by anonymous on 2005-05-10

In 0.9.1, the unit display on the side panel tries to list non-weapon [object]s beside the unit's traits, with the result that they get truncated if they have long names or if there are several with short names.

Moreover, when I filed bug #13036 I was told that even *that* much display was an accident, and had been removed from 0.9.1+ CVS.

AFAICT, that leaves us without any way to see objects at all, except for units on the recall list.  So please provide us with something on the unit display. Preferably a vertical listing, with line wraps on the individual objects, so that we can see everything if there are several or if any have long names.

The weapon display is better, but it truncates longish names and will only show four or five weapons, so it would be nice if you could let this (and the objects) take up as much vertical space as needed, and scroll if they need more space than the screen resolution provides.

Thanks.

(Reproduced on Linux)
Release: 0.9.1
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-10**

**ott wrote:**

> See https://savannah.nongnu.org/bugs/index.php?func=detailitem&amp;item_id=13047 for Savannah history.

**Comment by CelticMinstrel** [comment]
I'm not sure I agree with @sigurdfdragon on this being pointless; while it's true that `[object]`s are not shown to the user in current master (unless an addon adds them to the theme), there's still an issue with weapons being cut off when the window is small.

Then again, maybe that should be a separate issue?

**Comment by gfgtdf** [comment]
I mostly agree with @sigurdfdragon here, i think it's likeley that back then (0.9.1!) [object]s were exclusiveley use for simple pickupable items as seen in some mainline campaigns. Nowdays [object]s are used more generally so i don't think a standard way to show then is possible/makes sense.

Also the issue mentioned by @CelticMinstrel is a different issue and should have a seperate report.
