### ISSUE TITLE
Display gold in the Load Game dialog (GNA #4180)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1043]
**[Original submission](https://gna.org/bugs/index.php?4180)** by anonymous on 2005-06-22

As suggested in the Idea forum (http://www.wesnoth.org/forum/viewtopic.php?t=6110):

When playing a campaign it's not unusual (understatement...) that it starts to go bad - gold gets low, favorite units are killed, etc - at and beyond some scenario. You play on, but later you realize that you have to go back a number of scenarios and start over from there and change tactics.

Now, to actually find a scenario among the saved games where you can make a reasonable restart is difficult if you don't remember when it started to go bad; you have to load one scenario after another until you find [the] one where you finished with a reasonable amount of gold and/or nice units.

Therefore, I suggest a change/addition to the Load Game dialog: the savegame summary to the left of the savegame list should also contain the "current" amount of gold.

To make this lenghty post even longer, the savegame summary could also contain some information on the recall list, for instance the number of troups and perhaps (more interesting?) the total level of the troups. But this is secondary to the amount of gold being shown.

(Reproduced on All)
Release: 0.9.2+
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-10**

**ott wrote:**

> See https://savannah.nongnu.org/bugs/index.php?func=detailitem&amp;item_id=13511 for Savannah history.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-07-22**

**hajo wrote:**

> Now wesnoth is at v1.3.6, and the displayed info about savegames
> 
> still does not include gold, number of units etc.
> 
> 
> 
> I think showing these infos would be a good idea.

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-19**

**mordante changed status:** None -> Postponed

**mordante wrote:**

> I think the gold makes some sense, the other info is easily obtained by loading the game so I think it has no bug advantage.
> 
> 
> 
> I'll implement this after the feature freeze.

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-02-16**

**mordante wrote:**

> Hope to find time for it post 1.6.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**shadowmaster changed status:** Postponed -> None

**Comment by CelticMinstrel** [comment]
Implemented in 99693041b129.
