### ISSUE TITLE
ability to continue with another map in multiplayer (GNA #4201)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1044]
**[Original submission](https://gna.org/bugs/index.php?4201)** by anonymous on 2005-07-02

This is a very simple proposal that would make the mystery campaign unnecessary. 

It'd be good if, at the end of a multiplayer map, it gave you the option to "play another map". This would bring up the multiplayer game dialogue again, defaulting to the play mode you had previously (ai vs. human, online, etc.) but with the option of having your previous units available for recall and your gold reserves available. 

This would make multiplayer far more enjoyable, since half the fun of the game is in preserving and using high level units, and would avoid the problem of randomness in the mystery campaign, which quickly gets boring. You could choose how hard to make your enemies each time, rather than having the game try and calculate an even match.

For more see this forum thread:
http://www.wesnoth.org/forum/viewtopic.php?p=87775

(Reproduced on any)
Release: 0.9.3
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-10**

**ott wrote:**

> See https://savannah.nongnu.org/bugs/index.php?func=detailitem&amp;item_id=13614 for Savannah history.

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-02-14**

**soliton wrote:**

> Seems like a good idea as a first step towards multiplayer campaigns as well.

**soliton changed priority:** 5 - Normal -> 7 - High

**soliton changed OS:** GNU/Linux -> any

**soliton changed title:** Play another map in multiplayer -> ability to continue with another map in multiplayer

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-07-27**

**anonymous wrote:**

> The commit is for bug #4210, not this bug.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-09-09**

**soliton changed severity:** 3 - Normal -> 1 - Wish

**soliton changed priority:** 7 - High -> 5 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-19**

**mordante changed status:** None -> Need Info

**mordante wrote:**

> Does this idea still have merit since it's possible to create multiplayer campaigns now?

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-21**

**soliton wrote:**

> I think it's still a nice idea since it'd be more flexible for the user than mp campaigns. If it's somewhat easy to enable we could test it out sometime..
> 
> 
> 
> I suppose a good interface for this needs a bit thought though.

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-24**

**mordante changed status:** Need Info -> None

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-07-13**

**anonymous wrote:**

> Note that mp campaigns already work (more or less) in latest wesnoth versions.
> 
> 
> 
> Also implementing this is not trivial, specially becasue currently in campaigns it is defined by wml which sides unit carries over to which side of the next scenario. Specially its currently unrelated to which user conrolls which side. This may seem like a technical limitation but actually its very related to problems like: 'If player A controlls side 1 in the first scenario And controlls sides 2 and 3 of the next scenario which side (of the next scenario) should get the carryover units?' In usual (mp and sp) campaigns this is defined by wml.

**Comment by ProditorMagnus** [comment]
It should be implemented as custom campaign already.

**Comment by gfgtdf** [comment]
yes i think we cam mark this as fixed

**Comment by CelticMinstrel** [comment]
Does this "custom campaign" actually satisfy this issue?

**Comment by gfgtdf** [comment]
in https://github.com/wesnoth/wesnoth/issues/1676 the author said this is the case.

**Comment by CelticMinstrel** [comment]
As far as I can see, you're referring to the comment from @sigurdfdragon about Custom Campaign? Rather than the author of this issue (though we have no idea who that is anyway).

Can Custom Campaign let you choose the scenarios as you go or is it selected all up-front at the start?

**Comment by gfgtdf** [comment]
by 'author' i meant the author of 'Custom Campaign' which is afaik @sigurdfdragon

**Comment by CelticMinstrel** [comment]
Yeah, that's what I thought, but I don't know how Custom Campaign works so I can't tell if it actually implements this request.

**Comment by sigurdfdragon** [comment]
The short version is that Custom Campaign is an mp mod that will save all the units you have on victory at the end of arbitrary mp maps and allows using the saved units on a new mp map.
It doesn't allow you to select the next map during the end of the current one. Instead, maps are chosen and set up via the standard mp game config interface, like a normal game. One just needs to have the mod enabled when creating the game.

**Comment by CelticMinstrel** [comment]
Ah, so you _do_ choose the next map after you've finished the previous one, then. So I guess it does technically satisfy this. (Does it also have a "discard units and start a new campaign" option...)

**Comment by sigurdfdragon** [comment]
> (Does it also have a "discard units and start a new campaign" option...)
yes
