### ISSUE TITLE
Campaign overview should show the campaigns' version (GNA #4337)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1049]
**[Original submission](https://gna.org/bugs/index.php?4337)** by anonymous on 2005-08-25

Campaign overview should show the campaigns' version so that one knows whether a new one should be downloaded.

(Reproduced on all)
Release: 0.9.5
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-10**

**ott wrote:**

> See https://savannah.nongnu.org/bugs/index.php?func=detailitem&amp;item_id=14287 for Savannah history.

**ott changed OS:** Gentoo Linux/ Any -> all

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-07-11**

**hajo wrote:**

> The link in the previous comment leads to &quot;Error:Project not found&quot;
> 
> 
> 
> This makes it rather hard to see why this old bug is still open...

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-07-11**

**anonymous wrote:**

> For your information, Savannah was the old bug tracker for Wesnoth, before the project (and the bug reports) moved to Gna! The old bug tracker there has since vanished, unattended, so that is why the links are not valid anymore.
> 
> 
> 
> Most bugs and feature requests, thankfully, have enough information without the Savannah history. Like this one: the original submission (original feature request) is very clear, in my opinion.
> 
> 
> 
> Of course, a simple indication (however it gets implemented), that a new version of a campaign you have has become available, should be enough to grant this wish.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-08-03**

**boucman wrote:**

> assigning all campaignserver bugs to mordante...
> 
> 
> 
> mordante can you sort/duplicate/close ?

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-02-16**

**mordante wrote:**

> Hope to find time for it post 1.6.

**Comment by Wedge009** [comment]
I'm guessing this original request was in relation to add-on campaigns. The current (1.14) add-on interface shows which add-ons have newer versions available, so I think this old issue can be closed.
