### ISSUE TITLE
provide hotkey for switching focus (eg. TAB) (GNA #4340)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1050]
**[Original submission](https://gna.org/bugs/index.php?4340)** by anonymous on 2005-08-28

Currently the MP lobby (devsrv) behaves like this:

- If you click on the selected game (that has the red bar), or probably on any game present, you can not input data, unless you return focus on the text by clicking again on the text input row at the bottom of the screen.

- Clicking on an inactive area of the games' list has no effect.

- Have not tested, whether clicking on players' list has any effect.

- This behaviour has not, to my knowledge, been present before, and it restricts the usability of the lobby.

An additional note:

- I have not tested, whether the same behaviour is currently present on the MP game creation lobby - may be.

(Reproduced on Linux)
Release: 0.9.6+cvs
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-10**

**ott wrote:**

> See https://savannah.nongnu.org/bugs/index.php?func=detailitem&amp;item_id=14306 for Savannah history.

**Comment by Wedge009** [comment]
#1239 also talks about changing focus via tab but for the general case, not just MP lobby. Closing this one in favour of the later issue since that one has more discussion there.
