### ISSUE TITLE
Having a way to watch chats in the lobby while playing a game would be useful (GNA #4342)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1051]
**[Original submission](https://gna.org/bugs/index.php?4342)** by anonymous on 2005-08-28

I have noticed a lot of people keep open two games while playing

in order to talk in the lobby while playing a game. It would

be nice if there was a way for people to talk in the lobby while

playing a game.

One possible way this might work is to have lobby chats go down

the right side of the screen and to use a different talk command

than for in game chats. Whether or not the lobby messages show

up should probably be a preference. Talking to the lobby should

turn that preference on but not change the saved setting.

(Reproduced on all)
Release: 0.9.6+cvs
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-10**

**ott wrote:**

> See https://savannah.nongnu.org/bugs/index.php?func=detailitem&amp;item_id=14308 for Savannah history.

**ott changed OS:** Windows/Linux -> all

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-10-17**

**anonymous wrote:**

> I don't think this is really worth the trouble.
> 
> 
> 
> As mentioned already in the original request, keeping open two clients works fine, if you really want to distract yourself from the game you're playing.
> 
> 
> 
> Mark as Won't Fix and close?

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-10-17**

**anonymous wrote:**

> Plus, providing for this kind of gizmos that distract from playing the game is hardly the essence of what Wesnoth wants to do. If people want to use multi-tabbed chat browsers, they can do so outside the game.

**Comment by Wedge009** [comment]
Closing in favour of #3866

**Comment by jostephd** [comment]
I don't think #3866 and this issue are duplicates. #3866 is about being able to see the lobby while in the mp_staging screen (where one configures sides/teams), while this issue is about being able to see the lobby in-game. I think I'm agreeing with the last two anonymous comments, though.

**Comment by Wedge009** [comment]
Ah, I misunderstood 'hosting a game' as playing it, but if it's a matter of checking the lobby while still during set-up, then yes it's different. Leaving it closed since you agree with last two comments.
