### ISSUE TITLE
Game summary dialog (GNA #4459)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1055]
**[Original submission](https://gna.org/bugs/index.php?4459)** by hogne on 2005-10-02

Dialog to replace the current Scenario dialog which isn\'t very appropriate for MP or single scenario games. The mock-up was made with MP games in mind, but could also be used for single player games.

See attached mock-up for proposed layout.

The crown is used to indicate that the leader has survived, a skull that the leader has died.

Winning team is colored green, loosing theme red.

Hogne

(Reproduced on any)
Release: svn trunk
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-02**

**hogne added attachment:** [mp_summary2.png](http://gna.org/bugs/download.php?file_id=191)

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-02**

**hogne added attachment:** [mp_summary2.png](http://gna.org/bugs/download.php?file_id=185)

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-02**

**hogne added attachment:** [mp_summary2.png](http://gna.org/bugs/download.php?file_id=185)

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-02**

**hogne added attachment:** [mp_summary2.png](http://gna.org/bugs/download.php?file_id=185)

**Comment by wesnoth-bugs** [comment]
**Modified on 2005-10-02**

**hogne wrote:**

> Skull icon. I can this and the crown bigger if that is desirable.
> 
> 
> 
> Hogne

**hogne added attachment:** [skull.png](http://gna.org/bugs/download.php?file_id=187)

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-01**

**ivanovic wrote:**

> Changing reports assigned to people that are probably inactive to 'none'.

**Comment by Pentarctagon** [comment]
Closing since the UI being referenced here is wildly out of date from what currently exists.

**Comment by CelticMinstrel** [comment]
What _is_ the UI being referenced? I can't tell from the description.

**Comment by Pentarctagon** [comment]
It looks like a very old proposal for showing some additional information for saved games that have been fully played.

**Comment by CelticMinstrel** [comment]
So is it referencing the statistics dialog? Or the end-of-scenario summary? Or something else? The image isn't useful in determining this because it's just a mock-up.

**Comment by Pentarctagon** [comment]
I doubt there's any way we'll be able to know for sure at this point, to be honest.

**Comment by soliton-** [comment]
It's a mock-up. The important part is what info it shows not what the UI design looks like.
