### ISSUE TITLE
replace the verbal multiplayer color selector with attached icons (GNA #5199)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1061]
**[Original submission](https://gna.org/bugs/index.php?5199)** by eleazar on 2006-02-04

Here's an GUI improvement Ivanovich came up with:

Instead of having colored text that of the name of the team color, it would be more useful to have a icon showing what the color is.

Thus the color would be easier to identify and save the translators trouble naming tricky colors.

"color-bulb" is meant to be used in the list, and the other 3 PNGs are a standard buttons.  

The TColor parts of the button icons are completely greyscale, equal parts RGB of the following values:

125 medium

255 brightest

15 darkest

240

225

190

175

165

149

145

130

115

95

80

55

35

25

(Reproduced on any)
Release: trunk
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-02-04**

**eleazar added attachment:** [color-bulb.zip](http://gna.org/bugs/download.php?file_id=604)

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-08-03**

**boucman wrote:**

> interesting new widget to add: dropdown menu with images...
> 
> 
> 
> don't know how doablee this is, though..

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-08-05**

**sapient wrote:**

> Interesting idea. I'm not sure if I'll like the looks of it, but I'm willing to give it a try. At least it should save some space on the screen.

**Comment by Vultraz** [comment]
I implemented this in 1.13. The color dropdown in MP staging is accompanied by an appropriately-colored orb.
