### ISSUE TITLE
Sorting of unofficial campaigns by language (GNA #5327)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1063]
**[Original submission](https://gna.org/bugs/index.php?5327)** by gwain on 2006-02-17

it should be allowed to sort the campaigns by language, checking if there is a translation for the language selected in the options menu, or by the default menu

(Reproduced on All)
Release: 1.0.2+
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by gfgtdf** [comment]
I assume this is a request about the addon manager and not the campaign selection screen?

**Comment by jostephd** [comment]
This should be pretty straightforward. The addon manager is implemented in src/gui/dialogs/addon/manager.cpp and src/gui/dialogs/addon/manager.cpp; it already shows the list of translations, all that's needed is to add some UI to match against them.

**Comment by CelticMinstrel** [comment]
Probably in the filter UI?

**Comment by jostephd** [comment]
Yeah, the value of the search textbox could be matched against the text in the "Translations" label. Or maybe a dropdown could be added. A dropdown would have the advantage that a player could filter for several languages at once ("Campaigns with either Danish or Swedish translation").

**Comment by CelticMinstrel** [comment]
Yeah, filtering for multiple languages is probably a good idea, and even if you didn't want to support that, I think a dropdown is better. Actually... maybe this is a place where a combobox would be the best choice - basically a cross between a text field and a combobox, so they can either pick a language from the menu or type in a language code in the text field.

**Comment by Kingofd** [comment]
Hello,
I am interested in adding this feature. 
I am thinking of adding a dropdown, similar to the "Type"-dropdown. 

"None"-translations will default to English translation.

As I am new could you give me some pointers as to where stuff is added to the UI?

**Comment by soliton-** [comment]
Did you take a look at `src/gui/dialogs/addon/manager.cpp` as mentioned by jostephd above? Anything specific you're missing? The related config is in `data/gui/window/addon_manager.cfg` in case you haven't found it.

**Comment by Kingofd** [comment]
@soliton- Thx, addon_manager.cfg was what I was missing

So the feature is done, however I need to iron out some bugs and unwanted behaviour:

Firstly: When I select multiple languages, it can happen, that the list, where the addons are shown does not expand to fit the newly selected addons that fit the language filter and it throws the following error:
`20220831 15:14:04 error gui/layout: grid [] place: Failed to place a grid, we have (1031,59) space but we need (1920,59) space. This happened at a grid with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui25panelE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui27dialogs13addon_managerE' with the id 'addon_manager'.
`
Did I miss some additional `update_gui()` function to update the `addon_list`. From what I see it should be done by `apply_filters()`?

Secondly:
I scrape the addon.locales information vector for all available translations. The function `langcode_to_string()` that is used to show which translations are available in the dedicated addon window does not give a readable language string for all languages, only langcodes (see picture). Should I only display those, for which `langcode_to_string()` gives valid results or show everything that is indeed listed in the respective addon descriptions?
![BfW-LangUI](https://user-images.githubusercontent.com/26515148/187693244-340a9cb5-db84-4948-b3b4-fcefd690deed.png)
