### ISSUE TITLE
Moving unit_height_adjust from [terrain] to [tile] (GNA #5821)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1065]
**[Original submission](https://gna.org/bugs/index.php?5821)** by zookeeper on 2006-04-19

Currently the unit height adjustment on a terrain has to be the same on every hex that's of the same terrain. This makes for example the height adjustment on keeps difficult, since normal castle keeps need to have much higher height than encampment keeps - but both are of the same terrain, so either one is bound to look silly. Since the amount of height adjustment should obviously be determined by the graphics on a hex, not the terrain itself, it would be logical to move the 'unit_height_adjust' key from [terrain] to [tile]. Actually, the 'submerge' key should get the same treatment, for the same reasons.

So, this is how it should work:

If a [tile] has the 'unit_height_adjust' key present, that value will be added to the value given in the [terrain] tag, but of course just for the one hex that the [tile] refers to. The same for the 'submerge' key. So both keys should still be accepted inside [terrain], both for simplicity and in case the terrain is "uniform" in height and needs either none or only few / small tile-specific adjustments.

I have the WML means to apply the different adjustments for the different keep types if this is implemented, and for example for mountains, too, if such a thing is desired.

(Reproduced on all)
Release: trunk
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-01-05**

**mordante wrote:**

> Since my terrain branch has a letter for each keep, the most important reason for this FR no longer exists. I just discussed it with Zookeeper on IRC, but it will also be a wish to have after the merge of my terrain branch.

**Comment by stevecotton** [comment]
Closing:
* was logged before 1.3.2 (the release that changed from single-character terrain codes)
* no response to the previous question about closing it
* there's lots of `unit_height_adjust` values in data/core/terrain.cfg.
