### ISSUE TITLE
WML configurable village income / upkeep (GNA #6301)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1071]
**[Original submission](https://gna.org/bugs/index.php?6301)** by anonymous on 2006-07-06

I'm going to record a feature request, about which ott wrote on wesnoth-dev mailing lists:

"Talking theory is interesting, but tends to go round in circles.

Let's talk practice instead.

This whole thread [simplifying income/upkeep, balancing campaigns] would stop cropping up again and again if:

1.  all relevant parts were scriptable in WML, and

2.  there were some campaigns making a compelling case for anything changing.

Issue 1 was partially addressed a while back, but clearly things like the upkeep cost calculation parameters could be moved into WML too. Why not allow each village to generate 2gp per turn, or 1gp and 1 unit upkeep, or 2 units, and then see how they stack up?"

This would allow campaign authors more flexibility in income balancing their scenarios.

(Reproduced on all)
Release: 1.3.
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-04-14**

**gabba added attachment:** [village_support.diff](http://gna.org/bugs/download.php?file_id=5626)

**gabba wrote:**

> This is quite an old feature request, but it was still on the EasyCoding page. Since there's already a village_gold WML [side] attribute that controls how much gold each village yields, I decided to add a new [side] attribute called village_support, that defines how many unit levels each village can support for upkeep purposes. I tested it by adding the attribute to several campaign scenarios, and it works fine.
> 
> However there are probably still some loose ends to tie:
> 
> - not tested in multiplayer
> 
> - I know there's a kind of WML validator, so I don't know if it's gonna like my new attribute
> 
> 
> 
> If this patch is accepted, http://www.wesnoth.org/wiki/SideWML would need to be updated to add the new village_support attribute. I can do it, just let me know...
> 
> (file #5626)

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-04-14**

**gabba wrote:**

> I've attached my patch via the proper mechanism, but it's exactly the same file as attached here.
> 
> 
> 
> Forgot to mention by eventual plans: I'd like to add attributes to [village] so you can configure income and support/upkeep per-village. Could be a nice feature for scenario designers.

**Comment by gfgtdf** [comment]
Now that village_support support is implemented we can close this. I might create a new bugreport for even further upkeep/support modification for example in [village].
