### ISSUE TITLE
Check for music changes after a [story] or [part] skip by the user (GNA #6406)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1074]
**[Original submission](https://gna.org/bugs/index.php?6406)** by zookeeper on 2006-07-21

Sometimes you want to start playing the scenario music already in the story screen, not wait until the scenario actually starts. For this, you'd use the music= key in a [part] (or a [music] tag, I guess that would work just as well). The problem is when the user skips the story screen by using the "skip" button (or just clicking "next" rather quickly) - which causes the scenario music to never start. When skipping the intro, the [part]s should still be scanned for music changes so that you get the correct playlist when the scenario starts, even if you skip the intro (or just make skip go through every [part] and process everything in them otherwise normally, but really, really quickly).

(Reproduced on win)
Release: 1.3+svn
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-08-05**

**rusty wrote:**

> This is true, but you can work around it by repeating the music list in the scenario itself.  Music changes are only forced when the current playing music is not in the new playlist.
> 
> 
> 
> But you're right, it'd be nice to fix.

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-01**

**ivanovic wrote:**

> Changing reports assigned to people that are probably inactive to 'none'.

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-11**

**esr changed category:** Bug -> Feature Request

**esr changed title:** [story] [part] music changes skipped by the &quot;skip&quot; button -> Check for music changes after a [story] or [part] skip by the user

**Comment by nemaara** [comment]
This no longer happens as of 1.14.6.
