### ISSUE TITLE
Allow subfolders and organising of .cfg's and txt-file maps in MP create screen (GNA #6860)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1076]
**[Original submission](https://gna.org/bugs/index.php?6860)** by anonymous on 2006-09-03

This way you could separate your "Serious gameplay" maps, "Epic maps", "Special scenarios with complex WML", etc., according to your liking, and more easily find what you are looking for.

(See also f.r. / bug #4150 that concerns subfolders.)

(Reproduced on all)
Release: 1.3-svn
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-09-04**

**anonymous wrote:**

> Related to f.r. / bug #6864. And please reduce severity to 2 - Minor.

**Comment by ProditorMagnus** [comment]
Partially implemented, local maps are displayed as separate list.

**Comment by CelticMinstrel** [comment]
I'm assuming this refers to editor-created maps?

**Comment by gfgtdf** [comment]
> I'm assuming this refers to editor-created maps?

quite unclar, the title explicitly says .cfg files (note that it was 2006 so the 'scenario editor' did not exist at that point) and txt-file maps (whever that is)

as it unlikely that we will ever get claryfying feedback on this one, i do support closing this one and waiting for a new clearer feature request.

**Comment by CelticMinstrel** [comment]
My interpretation was that the game should parse subdirectories in the editor map directories and build those up as a tree view when selecting a random map, or at least use them as categories.

**Comment by Pentarctagon** [comment]
Going ahead and closing at this point given the lack of clarity.
