### ISSUE TITLE
Request for map editor to be able to load a map from a savegame (GNA #6893)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1077]
**[Original submission](https://gna.org/bugs/index.php?6893)** by anonymous on 2006-09-07

In case zipios support is enabled, preferably also from a compressed savegame.

If the savegame contains several map_data tags, providing a way to choose which one to load would be nice. If you want to be fancy, you can make the selection list be shown with minimap-previews.

For saving maps from the editor, please see feature request / bug #4348.

(Reproduced on all)
Release: 1.3-svn
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-09-07**

**edb wrote:**

> partialy done in patch #594

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-09-08**

**anonymous wrote:**

> Do I understand you correctly - also loading from a savegame, not only loading from a scenario .cfg -file?

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-09-08**

**edb wrote:**

> in fact all file that contain a map_data tag. But data are save in the file where they come from. so not really what want i guess

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-03**

**shadowmaster wrote:**

> Deassigning bugs from inactive developers.

**Comment by stevecotton** [comment]
With 1.14, it's possible to do "File", "Save Map" during a game or a replay. I think this old feature request should be closed as done.

**Comment by cooljeanius** [comment]
> With 1.14, it's possible to do "File", "Save Map" during a game or a replay. I think this old feature request should be closed as done.

yeah I've done this for an add-on and can confirm it works
