### ISSUE TITLE
Only final statistics are shown in replay mode (GNA #6931)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1079]
**[Original submission](https://gna.org/bugs/index.php?6931)** by anonymous on 2006-09-10

Not their development along the game's events.

(Reproduced on all)
Release: 1.3-svn
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-09-10**

**anonymous wrote:**

> Oh, I just noticed that the above _only_ applies for watching real replays, not watching a savegame as replay.
> 
> 
> 
> I can't believe the number of things in Wesnoth where a replay and a savegame are treated so differently...

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-09-11**

**soliton wrote:**

> No, the difference is that in a replay the statistics *start* with the normally final values. The development while replaying works as usual AFAICT.

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-09-30**

**anonymous wrote:**

> Hmm. This looks like another case where replays and savegames differ. Please see bug #7245 for what happens with savegames. The cause for the misinitialised stat values may be the same, though. In the case of replays, these don't get changed during the viewing, however.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-02-11**

**anonymous wrote:**

> In 1.2.1, up-to-date statistics seem to work at least with a save/replay that satisfies the following conditions:
> 
> - is a mp replay (not tested with a savegame, also not possible to test in 1.2.1 because of bug #8389),
> 
> - is saved by the winning player.
> 
> 
> 
> Other combinations not tested for the moment.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-02-12**

**anonymous wrote:**

> 1.2.1 also works with the following:
> 
> - is a campaign replay,
> 
> - is saved by the winning player.

**Comment by jostephd** [comment]
This has been fixed for a while. https://github.com/wesnoth/wesnoth/commit/2a7188ea10401247bda25d4efefe27e11fa639d0 (part of #3997) explains how it works in 1.14.6.
