### ISSUE TITLE
Request to be able to choose one team's view in replay mode (GNA #6946)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1080]
**[Original submission](https://gna.org/bugs/index.php?6946)** by anonymous on 2006-09-11

This would allow observing from one team's viewpoint, without being able to know more about the moves than the team's players did during the game.

User interface suggestion follows.

The current "Fog" -checkbox [and probably the same for shroud] could be changed to a drop-down list with the following options:

- No fog [shroud]

- Rotating fog [shroud] (i.e. the current option)

- Fog [Shroud] for team {North, 1}

- Fog [Shroud] for team {South, 2}

...

- Fog [Shroud] for team N

(Reproduced on all)
Release: 1.3-svn
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-07-03**

**tuukkah wrote:**

> This is now partly implemented by https://gna.org/patch/?757

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-07-08**

**anonymous wrote:**

> Very cool, thanks! And good luck in extending the support, if you intend to.

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-10-24**

**anonymous wrote:**

> Compare and contrast with bug #9591.

**Comment by sevu** [comment]
This seems to be implemented.
