### ISSUE TITLE
Whispers not available in the chatlog (GNA #7230)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1083]
**[Original submission](https://gna.org/bugs/index.php?7230)** by anonymous on 2006-09-28

Would be nice to be able to catch the whispers in the chatlog, if you miss them otherwise.

Then again, getting them in the savegame wouldn't be nice.

(Reproduced on all)
Release: 1.1.10
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-09-28**

**anonymous wrote:**

> Sorry, this was supposed to be a feature request.
> 
> 
> 
> For a related issue, see bug #6923.

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-09-28**

**soliton changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-05-06**

**anonymous wrote:**

> Actually, considering that you don't want whispers in your savegame, where all other chat ends up, it probably makes more sense to cache the whispers in a separate whisper-log. I hope something like this is possible.

**Comment by Pentarctagon** [comment]
Closing since whispers are intentionally not stored anywhere.
