### ISSUE TITLE
Observers don't see time running out (GNA #7313)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1084]
**[Original submission](https://gna.org/bugs/index.php?7313)** by anonymous on 2006-10-04

(Reproduced on all)
Release: 1.1.10
Priority: 3 - Low
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-11-16**

**esr changed status:** None -> Wont Fix

**esr wrote:**

> Ancient, anonymous poster, no plans for a 1.2.x.
> 
> We'll revive if it shows up in a dev version.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-11-17**

**soliton wrote:**

> The problem is that we don't transmit timer information. If we would send the remaining time on end turn or so to synchronize, it should not be difficult to implement.
> 
> 
> 
> Related is that we do not show timer information about the active player when it's not our turn either. Would be valuable information IMO.

**soliton changed title:** Observers don't see time running out in the top row -> Observers don't see time running out

**soliton changed category:** Bug -> Feature Request

**soliton changed severity:** 2 - Minor -> 1 - Wish

**soliton changed priority:** 5 - Normal -> 3 - Low

**soliton changed status:** Wont Fix -> None

**Comment by Pentarctagon** [comment]
Given observers aren't playing, they also don't need to see the turn timer in the first place.
