### ISSUE TITLE
MP chat font - small request (GNA #7470)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1087]
**[Original submission](https://gna.org/bugs/index.php?7470)** by anonymous on 2006-10-19

It is hard to distinquish between . and , and likewise : and ; because the commas aren't too easily readable. I don't know if anything can easily be done to this.

If not, please feel free to close this immediately as a "Won't fix".

(Reproduced on all)
Release: 1.3-svn
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2006-10-30**

**anonymous wrote:**

> Interestingly enough, in the lobby the differences show clearly, just not in the in-game chat.

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-05-16**

**kthakore wrote:**

> I am working on this now

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-02-28**

**boucman wrote:**

> last comment from 2008, this FR is up for grabbing if anybody wants...

**Comment by Wedge009** [comment]
There was a font change to Lato not so long ago (early 2018?), plus I had a look at the punctuation concerned - commas, full stops, colons, and semi-colons - in MP Lobby and in-game chat for 1.14.7 and they look okay to me. Feel free to re-open if anyone thinks this is still worth keeping.
