### ISSUE TITLE
get add-ons: remember sort order and direction (GNA #8097)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1090]
**[Original submission](https://gna.org/bugs/index.php?8097)** by wwp on 2006-12-26

What about remembering the sort column and direction in the "get add-ons" submenu?

(Reproduced on all)
Release: 1.2
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-09-22**

**hajo wrote:**

> As an option in the preferences,
> 
> or just between calls to the add-on -
> 
> manager during one run of the program ?

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-09-22**

**anonymous wrote:**

> As something in-between the two options you suggest?
> 
> 
> 
> In other words, sort in the add-on manager, but store (in the preferences _file,_ of course) and remember this sorting not only during one run, but across the runs.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-09-29**

**wwp wrote:**

> Hajo:
> 
> sorry for my late reply (was offline for a while).
> 
> Yes, it's about remembering the sorting across the runs (when re-entering the add-ons manager, sort the data like they were sorted in the previous 'session'). I don't think that this needs an option, IMO remembering sorting column and direction is enough common in applications to make it trivial and welcome.

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-02-16**

**mordante wrote:**

> Hope to find time for it post 1.6.

**Comment by CelticMinstrel** [comment]
I currently have no plans to work on this, so unassigning myself.
