### ISSUE TITLE
Streamlining game loading (start position, scrolling) (GNA #8152)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1092]
**[Original submission](https://gna.org/bugs/index.php?8152)** by anonymous on 2007-01-03

Hello.

Picked up from http://www.wesnoth.org/forum/viewtopic.php?t=14616 :

4. After loading a game, it shows player's initial position on the map, then scrolls to position game was saved in. This is excess.

In fact, it often/always shows player 1's position (in MP games) and then scrolls to the relevant position on whatever turn the game was saved on. (It can also scroll to a saved multi-turn move and start to do that.)

This scrolling could conceivably be hidden from the user, as stated in the original message.

(Reproduced on all)
Release: 1.3-svn
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-10-24**

**anonymous wrote:**

> Compare with bug #12788. Current status of this?

**Comment by gfgtdf** [comment]
this was changed iirc
