### ISSUE TITLE
Graphic display of Resistances for sidebar (GNA #8473)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1096]
**[Original submission](https://gna.org/bugs/index.php?8473)** by anonymous on 2007-02-11

Resistances are important, but aren't currently displayed in the sidebar.

I've modified Jetryl's icons here:

http://www.wesnoth.org/forum/download.php?id=12483

to be able to display resistance by displaying all six icons in a row on the sidebar.

The intensity of the color, (red or green) indicates the magnitude of the resistance.

A tooltip would display the actual resistance numbers.

See here and my following post for more explanation:

http://www.wesnoth.org/forum/viewtopic.php?p=195245#195245

(Reproduced on all)
Release: trunk
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-08-03**

**boucman wrote:**

> linked to themes, 
> 
> 
> 
> DF, would that be doable ?

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-01**

**ivanovic wrote:**

> Changing reports assigned to people that are probably inactive to 'none'.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-15**

**gfgtdf wrote:**

> You can see th3e resistances in the hps tooltip already, so can the be marked as fixed?

**Comment by nemaara** [comment]
Resistances are already visible in the hp tooltip as gfgtdf said. Closing.

**Comment by CelticMinstrel** [comment]
It'd still be cool to make them easier to see though...

**Comment by jostephd** [comment]
Agreed. For example, https://raw.githubusercontent.com/wesnoth/wesnoth/1.14/images/icons/icons-resistances.png could be shown in the sidebar, the font for that is in https://raw.githubusercontent.com/wesnoth/wesnoth/1.14/images/icons/icons-numbers.png. It would need some thought however about how to handle custom damage types (like "electrical" in the test scenario).

Reopening to continue discussion.

**Comment by Pentarctagon** [comment]
Closing given no discussion happened.
