### ISSUE TITLE
Better display of MP/Def table (GNA #8481)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1097]
**[Original submission](https://gna.org/bugs/index.php?8481)** by eleazar on 2007-02-12

Currently the display of MP/Def on terrains that a unit cannot enter is not ideal, and a bit cluttered and confusing.

It would be easier to read if dashed "&mdash;" where shown instead of "99" or a defense percentage for a terrain that cannot be entered, like so:

Chasm           &mdash;      &mdash; 

Cave            1     50%  

Mushroom Grove  1     40% 

Deep Water      &mdash;      &mdash; 

Shallow Water   3     20% 

Swamp           3     20% 

Sand            1     30%  

Grassland       1     30% 

Forest          1     30% 

Tundra          2     30% 

Hills           1     60% 

Mountains       1     70% 

Village         1     50%  

Castle          1     60%

I'd also like to see the order of terrains listed changed to the above.  Currently the list is somewhat jumbled.  This list puts similar terrains together, in a general low to high order.

(Reproduced on all)
Release: Trunk
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-02-13**

**anonymous wrote:**

> Looks lika a good idea, special-casing the value 99 (or whichever is wanted) of movement cost.
> 
> 
> 
> Might I make a couple suggestions, though:
> 
> - _Cave wall_, chasm, _lava_, cave.
> 
> - By the amount of vegetation and general defense percentages (low to high), tundra/snow could be a bit higher. Sand, _snow_, grassland.
> 
> - Ordering of forests, hills and mountains is a bit tricky. Elves can have 70% in forests, dwarves have 70% on mountains. However, _most_ units have it better (or as good as) on mountains than forests. So -&gt; forest, hills, mountains?
> 
> - Ordering of castle vs. village? No real justification for either order, but considering that villages give healing they're generally &quot;better&quot; for the unit, so maybe keeping with the low to high order have villages last?
> 
> 
> 
> So, all together:
> 
> (Shroud)
> 
> (Impassable mountains)
> 
> 
> 
> Cave wall (some can walk there)
> 
> Chasm
> 
> Lava (some can walk here, even)
> 
> Cave
> 
> Mushroom grove
> 
> 
> 
> Deep water
> 
> Shallow water
> 
> Swamp
> 
> 
> 
> Sand
> 
> Snow
> 
> Grassland
> 
> Forest (for some aesthetic reason I'd group this here... also, some units like dwarves, horses and Kalifa have a bad defense in forests)
> 
> 
> 
> Hills
> 
> Mountains
> 
> 
> 
> Castle
> 
> Village
> 
> 
> 
> Does this sound organised?

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-02-13**

**anonymous wrote:**

> Isn't Impassible Mountains an alias for cave wall?

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-02-13**

**eleazar wrote:**

> Anonymous #2: &quot;Isn't Impassible Mountains an alias for cave wall?&quot;
> 
> 
> 
> Yes, and neither should be listed because no mainline unit can move through them.  That's where the term &quot;impassable&quot; comes from.
> 
> 
> 
> Also lava and chasm are the same terrain: &quot;Unwalkable&quot; impassable to all but flying units.
> 
> 
> 
> Anonymous #1, why are you making suggesting about something you are apparently unfamiliar with?
> 
> 
> 
> Clarification: my first reference of &quot;low to high&quot; referred to elevation.  It's senseless to try to order the list according to defense rate, since there it varies wildly between units and races.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-02-26**

**anonymous wrote:**

> Eleazar: &quot;apparently unfamiliar&quot; ... a bit harsh. I may not be a terrain artist like you, but... Let's just say that I simply made a suggestion that followed a different logic than yours. Did my suggestion completely not make sense to you, or could you see any logic in it? (Or did you even look at the slightly modified order I suggested?)
> 
> 
> 
> Mostly I took issue with your placing of tundra after forest, since in Wesnoth gameplay standard &quot;snow&quot;/&quot;ice&quot; doesn't have the altitude characteristic of real-world tundra. (Wesnoth uses snow-covered hills/mountains for that purpose.)
> 
> 
> 
> Also: &quot;neither should be listed&quot; ... how do you then propose to deal with campaign units that can walk there (Cave wall)? (Wall guards, the one silly creature that had 99% defense there, some others someone might want to create?)
> 
> 
> 
> (About lava vs. chasm: I had in mind the special case of lava from UtBS.)

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-03-04**

**anonymous wrote:**

> (PS: Whether or not lava is an alias of chasm is largely irrelevant here, as this feature request isn't aimed at the 1.2 branch, and trunk already has a new terrain engine that allows lava and chasm to be defined separately. (...which would make sense, in my opinion, but if you don't agree, fine, let's not argue about that here.))

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-03-12**

**johnnyw wrote:**

> &quot;Chasm � � 
> 
> Cave 1 50% 
> 
> Mushroom Grove 1 40% 
> 
> Deep Water � � 
> 
> Shallow Water 3 20% 
> 
> Swamp 3 20% 
> 
> Sand 1 30% 
> 
> Grassland 1 30% 
> 
> Forest 1 30% 
> 
> Tundra 2 30% 
> 
> Hills 1 60% 
> 
> Mountains 1 70% 
> 
> Village 1 50% 
> 
> Castle 1 60% &quot;
> 
> 
> 
> I think this is a good order, but do you feel Tundra would fit better directly after Sand?  They seem more similar IMHO than Tundra/Forest Tundra/Hills.  If the purpose is to make it easy to determine values for Snowy Hills/Forest, then I ask why not put Shalow Water and Grassland together for Bridges/Riverford?
> 
> 
> 
> Also, this may be a personal preference, but it seems to me that Villages are a special and more important terrain than Castle; as such I think they should be listed last so that the values are more easily seen.
> 
> 
> 
> I good idea for sure though IMO.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-03-13**

**anonymous wrote:**

> johnnyw: That's the reason I (anonymous) suggested putting villages last. (And I'd put snow=tundra between sand and grassland.)
> 
> 
> 
> Anyhow, it's the devs' decision, whatever they choose.

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-19**

**mordante wrote:**

> I'll assign it for now, not sure whether I'll work on it however. We're in a feature freeze atm so it will be postponed.

**mordante changed status:** None -> Postponed

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-02-16**

**mordante wrote:**

> Hope to find time for it post 1.6.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**shadowmaster changed status:** Postponed -> None

**Comment by CelticMinstrel** [comment]
Checked both in the help and in-game (the tooltip when hovering move points). Both use the dash for impassable terrains, so I guess this was implemented at some point,
