### ISSUE TITLE
Allow .pbl file to contain image data for add-ons server display. (GNA #8625)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1098]
**[Original submission](https://gna.org/bugs/index.php?8625)** by johnnyw on 2007-02-28

Right now usermade content must be displayed on the add-ons server by images currently located in the user's wesnoth directories.  Sapient has informed me that although this is normally confines the standard image sets, usermade images will be seen by those who have already downloaded the content.

I would like to see it possible for image data to be implanted directly into the .pbl file to be interpreted and shown on the add-ons server.  This would allow any user to customize their display icon to advertise their content to a greater degree to those who have not downloaded the add-on previously.

(Reproduced on Windows)
Release: 1.3.1
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-03-20**

**mordante changed item group:**  -> None of the others

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-05-10**

**anonymous wrote:**

> Makes sense... I just had these errors (in stderr) about apparently non-existent images from viewing the add-on server:
> 
> 
> 
> error display: could not open image 'adept-ranged-7.png'
> 
> error display: could not open image '../data/campaigns/Imperial_Era/images/units/lavinian/centurion.png'
> 
> error display: could not open image 'wraith.png'
> 
> error display: could not open image 'warden.png'
> 
> error display: could not open image 'low-elvish-high-lord.png'
> 
> error display: could not open image 'units/druid-type2-4.PNG'
> 
> error display: could not open image '../images/units/human-loyalists/General.png'
> 
> error display: could not open image 'items/flaming_swordsman.png'
> 
> error display: could not open image 'units/terran/scout.png'
> 
> error display: could not open image '~campaigns/Giyan_art_maps/giyan.png'
> 
> error display: could not open image ''
> 
> error display: could not open image 'units/elvish-lord.png'
> 
> error display: could not open image 'units/human-magi/great-mage+female '
> 
> error display: could not open image 'enchantress-magic.png'
> 
> error display: could not open image 'units/human-magi/great-mage+female'

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-07-29**

**anonymous wrote:**

> i think this is a great idea!

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-02-16**

**mordante changed status:** None -> Postponed

**mordante wrote:**

> Hope to find time for it post 1.6.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**shadowmaster changed status:** Postponed -> None

**Comment by CelticMinstrel** [comment]
I currently have no plans to work on this, so unassigning myself.

**Comment by AI0867** [comment]
This is now possible, through #2544, though this should also be documented.

**Comment by CelticMinstrel** [comment]
Would it be worth making the client automatically generate a data URI from any non-core images referenced by the pbl on upload?

If not, then how do we expect addon devs to convert an arbitrary image to a data URI for the pbl?

**Comment by AI0867** [comment]
As stated on discord, googling for "data URI generator" gives you pages of random websites doing just that, but a built-in converter could be useful, as would a detector for whether an add-on icon is part of core or not when uploading.

**Comment by soliton-** [comment]
I think a separate syntax for local images that should be converted would be fine as well.

**Comment by AI0867** [comment]
The fact that data URIs are now supported has been documented in PblWML and the format now has its own page.

A built-in converter will have to wait a bit longer.

**Comment by sevu** [comment]
Closing, because functionality is now provided, converter if any would be a separate task.
