### ISSUE TITLE
support for HTTP proxy servers (GNA #8713)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1099]
**[Original submission](https://gna.org/bugs/index.php?8713)** by anonymous on 2007-03-11

I am currently studying abroad. The university's firewall only allows outgoing traffic through the HTTP proxy on port 8080. Would it be possible to add support for HTTP proxies so that I (and other people in the dormitory) can download add-ons and play games over the Internet?

(Reproduced on Mac OS X/Linux)
Release: 1.2.2
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-03-11**

**soliton changed severity:** 4 - Important -> 1 - Wish

**soliton changed category:**  -> Feature Request

**Comment by Vultraz** [comment]
*11 years later*. Closing. No one is going to put effort into someone requested over a decade ago involving something that's not even widely used anymore.

**Comment by CelticMinstrel** [comment]
That said, if someone _did_ put the effort into this, it wouldn't be rejected out of hand. (That doesn't mean it would be accepted either, though.)

**Comment by GregoryLundberg** [comment]
Fulfilling the OP request is dumb. I question that the OP actually knew how things work. I'd have simply rejected it, back then.

But, today, I read it as a request to replace the proprietary add-on protocol with a web-based, probably RESTful, interface. I'd mark that as a 2.0 feature request but it's possible we could offer it in parallel with the crufty old protocol for backwards compatibility with older clients.

**Comment by soliton-** [comment]
Wesnothd has a proxy feature. If there is demand we can consider running a proxy server on port 8080 on wesnoth.org...

**Comment by GregoryLundberg** [comment]
8080 is typically HTTP. We might as well run it on port 80.

Any properly configured proxy across a firewall would filter for HTTP and close down the conversation on 8080. The OP was depending upon the fact that 10 or 15 years ago most networks using proxies across firewalls were so mismanaged they're not check.

If we're going to offer services on a well-known port, we really should offer them using the expected protocol.
