### ISSUE TITLE
Update add-on download dialogue caption during unpacking stage (GNA #8777)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1101]
**[Original submission](https://gna.org/bugs/index.php?8777)** by anonymous on 2007-03-22

The current behavior is that the progress bar fills to 100 or 99% and then you have to wait for unpacking the addon with progress bar stuck at the end. A change as simple as adding new caption text "installing" after the file is downloaded would provide user with much better information on what's going on.

(Reproduced on Windows XP)
Release: 1.2.3
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-09-22**

**hajo wrote:**

> Would be nice, as I have seen the unpacking 
> 
> takes longer then the download.

**Comment by Wedge009** [comment]
I noticed this behaviour still occurring in 1.14/1.15, while I was testing the add-on download dialogue.
