### ISSUE TITLE
Darkening of user stats in the head line (GNA #9058)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1106]
**[Original submission](https://gna.org/bugs/index.php?9058)** by anonymous on 2007-05-01

If it's not the players turn the stats in the head line (number of villages, income, ...) are darkened in version 1.3.2. In multiplayer games you often need to think about and discuss strategy during the turn of you opponents and the darkened stats are very hard to read at this time.

Is there really a need to darken these stats? There is a clear indicator (the flag, even with the players name as a tooltip) to see which players turn is it.

Please revert this darkening of the stats or make the stats well readable again on every players turn.

(Reproduced on Linux)
Release: 1.3.2
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-05-01**

**alink wrote:**

> Indeed, I don't really know why we darken these stats (they seems updated during opponent turn), but even if there is a reason, I suppose that we can use a more readable color.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-05-01**

**alink changed status:** None -> In Progress

**alink wrote:**

> Soliton remember me that it's for making clear that the stats don't apply to the currently playing side.
> 
> 
> 
> I will try to find a readable dark color which keep this clear.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-05-01**

**anonymous wrote:**

> Yes, this was done after bug #3413, but the solution is not ideal. Comment #6 in that report gives a suggestion to gray out the icons, not the numbers.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-05-07**

**alink wrote:**

> Mmmmh graying the icons seems like a good idea. I did some quick test, it seems a bit &quot;sad&quot; but it's effectively looks disabled. I'm planning to work on themes and icons of the status bar, so I will also give it a try.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-05-17**

**anonymous wrote:**

> I changed the color for GRAY_TEXT to 888888. It's a bit better now, but still not good. I also would prefer to gray the icons and change the numbers back to white.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-07-19**

**esr wrote:**

> Fade Manley (one of my user test group members) has also complained about the text darkening.  So this is not just coming from &quot;Anonymous&quot;.
> 
> 
> 
> I think graying the icons but not the text is a reasonable idea.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-09-06**

**alink changed status:** In Progress -> None

**alink wrote:**

> I remove myself of the &quot;assigned to&quot;. A lot of work and decisions to make for this one. And the theme code is not easy and is far from my usual areas.
> 
> 
> 
> Here is some thoughts
> 
> - the theme engine is very flexible, any implementation of this  must try to keep its power
> 
> - the icons are currently purely decorative, we must find a way to associate them to the related data
> 
> - need new theme keys for having &quot;enabled/disabled&quot; images
> 
> - we need some trigger system to activate the switch
> 
> - and probably other details/problems to solve

**Comment by sevu** [comment]
Learned sth. new today, never noticed the graying out.

From reading the above, it seems some changes were done, and farther

**Comment by soliton-** [comment]
Not sure how you read that. It seems more like everyone agreed that only graying the icons would be preferable. Alink didn't get to it but provided a list of what would be needed to properly implement it.

Regardless of the implementation details the issue remains.

**Comment by sevu** [comment]
I read it like that the original change was mitigated by changing the color, and that the proposed changes won't be implemented because of time and technical reasons.

But might as well be reopenend. I also payed attention ingame, and I agree that it may be easier to keep focus if the color doesn't change.

**Comment by jostephd** [comment]
I don't see the issue. On my machine the text is grayed out but it's still readable.

**Comment by sevu** [comment]
Issue is too strong of a word.

**Comment by jostephd** [comment]
Well, whatever the right word for it is, the original bug report was that the darkened stats are hard to read, and my contribution to the discussion is that I find the grayed out text readable in current 1.14.

**Comment by sevu** [comment]
Alright
