### ISSUE TITLE
Incorrect behavior in Mac OS X contextual menus (GNA #9151)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1108]
**[Original submission](https://gna.org/bugs/index.php?9151)** by anonymous on 2007-05-17

In standard Mac programs, a right-click brings up a contextual menu and either button can be used to select items from it. This allows for the simple behavior of using the right button for both menu opening and item selection.

In Wesnoth, selecting an item from any contextual menu using the right mouse button closes the menu and brings up a new menu at the point the mouse was clicked. This behavior is non-standard and runs against Mac interface conventions.

The current Wesnoth behavior of closing the menu and opening a new one at the point of the mouse click should only be used if right-clicking *outside* the menu.

(Reproduced on Mac OS X)
Release: 1.3.2
Priority: 1 - Later
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-05-20**

**ivanovic wrote:**

> Since we don't have any active Mac Coder this will take quite some time to be established. It is not really a bug, but more a feature request to change the interface behaviour for the macversion.

**ivanovic changed priority:** 5 - Normal -> 1 - Later

**ivanovic changed category:** Bug -> Feature Request

**ivanovic changed severity:** 3 - Normal -> 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-08**

**ancestral wrote:**

> It seems this has been partially resolved; right-clicking on an item in the menu does not close the menu. However, right-clicking on another hex off the menu does not create a new menu as it should.
> 
> 
> 
> As this behavior is consistent with Windows machines as well, I�ll create a new bug report specifically for this; the immediate issue however is resolved.

**Comment by sevu** [comment]
... and due to that, this can be closed
