### ISSUE TITLE
Dialog position should be themable (GNA #9381)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1110]
**[Original submission](https://gna.org/bugs/index.php?9381)** by esr on 2007-06-23

Dialog position should be themable, so that (for example) people using dual-headed monitoes will be able to use themse that move the normal dialog location off the screen join.

(Reproduced on Any)
Release: trunk
Priority: 3 - Low
Severity: 1 - Wish

**Comment by Pentarctagon** [comment]
Closing since a use case for this seems non-existent.
