### ISSUE TITLE
Please provide a keyboard way to access the Details -subdialogs of the Statistics -dialog (GNA #9551)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1112]
**[Original submission](https://gna.org/bugs/index.php?9551)** by anonymous on 2007-07-20

In other words, please re-allow keyboard navigating the Statistics dialog and its subdialogs.

The ENTER/RETURN key used to bring you the details of the selected option. Using the common UI design principle that "ENTER/RETURN selects the highlighted option", I would expect it to. (ENTER enters, ESC escapes. Simple, is it not?)

I don't really see the reasons why this shouldn't be so - from an UI point of view. The reason that _is_ valid is that _I'm_ not doing the coding. ;-)

Anyhow, _if_ that is a complete no-no, please provide another hotkey, be it 'd' or anything else, that allows keyboard access to the statistics subdialogs. (I'd expect ESC to continue working though.)

(Arrow key navigation � la MC would work fine too, unless the arrow keys are used in another context. That is, left goes further down to details, right acts as ESC, and exits one level of dialogs at a time.)

--

I reported this as part of bug #9309, which just got closed since part of it was fixed. Sapient disagreed with this part of the request, but indicated that there could be an other solution, so I'm re-filing this issue. Please see the discussion there if you need the details.

(Reproduced on all)
Release: trunk
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by Pentarctagon** [comment]
Closing since the statistics dialog doesn't have sub-dialogs anymore.
