### ISSUE TITLE
Ability to cancel or disable automatic movement in a turn (GNA #9906)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1113]
**[Original submission](https://gna.org/bugs/index.php?9906)** by karsten on 2007-08-31

You can assign units orders to move automatically by targeting a spot which takes them more than one round to reach. In the following turns, they will follow the shortest path to reach that destination. In case an enemy unit blocks the path, they will stop. But they will still advance towards enemy units, even if they stop directly in front of the enemy. Obviously, this might not be what a player wants if he sends a fragile unit and approaches a powerful enemy unit.

I'd like to have some hotkey and/or a config option to interrupt or turn off automatic movement so that players can react to such an occasion without having to change the orders in the previous turn. Since this automatic movement happens at the beginning of the turn, after you load the save game, a config option would be enough.

Attached is a save game of a situation where such an option would have been useful. The Dragoon is ordered to move automatically, too, but to where the Ghoul is standing now, and he stops. The Elf Shaman approaches the Ghoul and stops right in front of him.

P.S.: It might be that units stop with the usual "Enemy units sighted, press t to continue" in case an enemy is sighted for the first time. But at least the units that are moving afterwards automatically won't stop but charge towards that enemy instead.

(Reproduced on Any)
Release: Any
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-08-31**

**karsten added attachment:** [Choice_in_the_Fog-Auto-Save26](http://gna.org/bugs/download.php?file_id=2881)

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-09-01**

**anonymous wrote:**

> Thank you for the report.
> 
> 
> 
> It used to be possible to double-click on the unit with pre-given orders to cancel the order at any time (at least in campaign play).
> 
> 
> 
> However, at least in multiplayer, this seems to not work every time, but I haven't bothered researching when it works and when not.
> 
> 
> 
> Please try if being able to cancel single pre-given orders (e.g. during the AI turn) is sufficient for you, or if you'd still want an &quot;emergency stop&quot; / &quot;stop the world&quot; hotkey for this purpose.
> 
> 
> 
> For me, being able to cancel individual orders anytime (if it consistently works) I feel would be sufficient.

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-09-02**

**karsten wrote:**

> I am talking about single player here, although it would be of a lot more interest in multi player environments where you can't just load an old save game and redo the turn, I guess.
> 
> 
> 
> You can cancel the order by doubleclicking, yes, but you have to do it before hosting the turn, i.e. on the previous turn. I think you would be able to change those automatic orders for a turn before they are executed, if you are *really* fast, but I didn't manage to do that. Try it with the provided savegame: Can you prevent them?

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-04-05**

**ilor wrote:**

> patch #1024 (in trunk) offers a solution for single player via a &quot;cancel orders&quot; option in the load game dialog. However, it would be nice to rework how the auto moves are handled so that would not be necessary.

**Comment by jostephd** [comment]
It's possible to cancel moves during one's own turn (with two single clicks, or with the menu item added by the Advanced Order Canceling add-on), and the "Cancel orders" option mentioned in the last comment addresses the issue for SP. What's left? Being able to cancel orders in MP games during other players' turns?

**Comment by Wedge009** [comment]
I don't think there is much to do either - might be another case of features that aren't immediately visible to players otherwise unaware of their existence.

Occasionally I have a unit continue a movement that unintentionally carries across multiple turns (I normally only move units as far as they can go in a single turn). I don't recall it being a problem, but I suppose it could be a nuisance in scenarios with shroud/fog that would then block undoing of this kind of move (and yes, I'm aware of the ability to delay shroud/fog updates, but I don't normally have that enabled).

**Comment by Pentarctagon** [comment]
Can this be closed then?

**Comment by gfgtdf** [comment]
I'd say yes
