### ISSUE TITLE
A way to show MP map credits that parallels campaign credits (GNA #9921)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1114]
**[Original submission](https://gna.org/bugs/index.php?9921)** by anonymous on 2007-09-02

Prompted by r20012 and bug #9913, I wish to suggest the following.

As has been argued by Doc Paterson, providing channels for feedback considering multiplayer maps is essential to their development. I completely agree with this desire, and I feel having access to this information (the credits) will be valuable for the maps' development. As a parallel, also campaigns give credit accordingly to their creators, artists, and current maintainers.

--

Revision 20012 adds these credits for multiplayer maps. These were added in the _Scenario Objectives._ This means, in other words, that the credits will be shown at the _start_ of _each game_ to each player.

_I consider this to be somewhat too obtrusive._ As a parallel, for campaigns, the credits are shown when you complete (finish) the campaign. If we consider that the creator of the game, Dave, doesn't have his name thrust, as it were, on the users' face continually, I don't think it is either _appropriate_ or _necessary_ to do this in the case of multiplayer maps and the names behind them, either.

If you'll allow the pun, the "objective" of the scenario is not to show who made it, the objective is to "Defeat Enemy Leaders". :-) Mixing these two goals is mixing reality and gameworld, and detracts from the immersion aspect in the game (for those who care about it). (As a parallel, showing campaign credits after finishing the campaign does not in the same way create a mixed situation.)

In short, I believe putting the information in the "objectives" was probably _a convenient short-term solution,_ but I sincerely hope that this solution will _not_ be _permanent._

--

So, how to show the credits? (I will include a mock-up of possible _contents_ of the credits at the end.)

I see at least two possible approaches.

1)

- Treat "Multiplayer" as the equivalent of "One Campaign", and provide common credits for all the MP _maps_ in a general dialog.

- This dialog should also include the MP (unit) balancing developers' credits.

- This dialog could, for example, be accessible through a button in the MP map selection screen, mp lobby, or from in-game. I'm sure something could be thought for this. Come to think of it, perhaps the best solution could be to include the credits as the _last option_ in the menu after pressing the "Start an MP game" button in the main screen.

2)

- Treat each "Multiplayer map" as a separate entity, and give each separate credits.

- MP (unit) balancing developers won't get credited separately, so their credits remain in the general "about".

- This could be done by adding to scenarios a "credits=" key or "[credits]" tag, in which the credits would be shown.

--

I would favour option 1.

If we chose option 2, _when_ to show this dialog? In my opinion, _not_ at _each_ game's start. The possible options could be:

- Add a menu entry in-game, with "Show map credits". I believe this would be the best solution, even if (unlike campaign credits) these wouldn't be shown automatically. However, even campaign credits are shown automatically very rarely, only when you finish the campaign, so I think this option would be acceptable.

- Add a possibility for map makers to show these credits (as map labels, as chat text, probably not as a popup as esr's been trying to reduce those) in linger mode. (I'm not sure this is a good idea.)

- Add the credits as pop-up accessible through a context menu present on each village of the map (or some other solution that creatively uses the game's features).

--

Mock-up of the MP map credits:

*-----Multiplayer Map Credits-----*

*Bitter Creek*

Original map design: pg (Charge)

Current map design and balance: Doc Paterson (Bitter Creek)

Special credits for the map's name go to: bert1"

*Triple Blitz*

Original map concept: pg (Blitz)

Map adaptation: olof (Blitz 3p)

Current map design and balance: Doc Paterson (Triple Blitz)

*Castle Hopping*

Original map design: pg

Map revised by: Becephalus

Current map design and balance: Doc Paterson (please excuse me if I misattributed something here)

(Reproduced on all)
Release: trunk
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-09-02**

**zookeeper wrote:**

> We could also just add an in-game menu option (right-click or in the main menu) for showing &quot;scenario information&quot;, where things like map designer(s), default settings, backstory or whatever else could be written to.

**Comment by Pentarctagon** [comment]
Closing because this kind of information would be better in the description, if desired by the scenario author, as well as the first feedback we'd get from this is people asking for a way to disable showing the same credits every time they finish a scenario because having to click through the credits every time they finish a scenario would get old real quick.  All the other ideas are already able to be implemented by the UMC author if they decide they want to.
