### ISSUE TITLE
desperately need side setting lock for village_gold (GNA #10244)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1116]
**[Original submission](https://gna.org/bugs/index.php?10244)** by rhuvaen on 2007-11-01

The WML settings income_lock, gold_lock etc are very valuable.

However, one of the most important settings is gold per village, or village_gold. This side parameter doesn't have a lock yet.

Having a lock for village_gold would be necessary to control the flow of a scenario to any degree.

(Reproduced on debian)
Release: 1.3.9+svn
Priority: 6
Severity: 3 - Normal

**Comment by sevu** [comment]
This is not really a missing feature:
Gold and income can be changed for individual sides in the MP Staging view (the 2nd screen for creating an MP game), and to hinder that are these lock settings, same for color, faction, leader, team and controller.

Village income can be set at MP Create (the first screen for creating a game) for _all_ sides. These ones can be locked by force_lock_settings.

**Comment by gfgtdf** [comment]
I actually think we did fix this somehow, the values in [side] should now overwrite what the user says and to give a default for the 'global' values the mp_village_gold in [multiplayer should be used.
