### ISSUE TITLE
Download and install several AddOn's at one time - without reconnect (GNA #10380)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1117]
**[Original submission](https://gna.org/bugs/index.php?10380)** by erendir on 2007-11-23

Itll be nice to have the possibility to choose several addons to download - without reconnecting all the time.

 Possible with a Ctrl+Click or somethin else.

(Reproduced on WinXP)
Release: 1.3.10
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2007-11-24**

**mordante changed status:** None -> Postponed

**mordante wrote:**

> I want to rewrite the entire addon management in Wesnoth [1][2]. I won't be able to do the finish it before the 1.4 feature freeze [3] which will take place pretty soon. So the request will be postponed.
> 
> 
> 
> 
> 
> [1] http://www.wesnoth.org/forum/viewtopic.php?t=15664&amp;postdays=0&amp;postorder=asc&amp;start=15
> 
> [2] http://www.wesnoth.org/wiki/User:SkeletonCrew#Addon_server
> 
> [3] https://mail.gna.org/public/wesnoth-dev/2007-10/msg00002.html

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-02-16**

**mordante wrote:**

> Hope to find time for it post 1.6.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**shadowmaster changed status:** Postponed -> None

**Comment by CelticMinstrel** [comment]
I currently have no plans to work on this, so unassigning myself.

**Comment by nemaara** [comment]
The addon manager now has this behavior so this issue can be closed.
