### ISSUE TITLE
Players should stay in their team in linger mode (GNA #10431)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1119]
**[Original submission](https://gna.org/bugs/index.php?10431)** by uso on 2007-12-02

In linger mode all players should stay in their original team (and not switch all to the same team), so that you can use team chat further on.

(Reproduced on Linux)
Release: 1.3.12+svn
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-08**

**soliton wrote:**

> I think this should only be done for players that actually have alive team members (ie they can actually see something and have something to (secretly) chat about).

**Comment by Pentarctagon** [comment]
Closing since this doesn't seem to have a use case:
* If this isn't an MP campaign, then the single scenario is over and there's nothing that would need to be kept secret anymore.
* If this is an MP campaign, then the players can effectively already do this by moving to the next scenario.
