### ISSUE TITLE
Adding support to ingame unit and image loading (GNA #10656)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1121]
**[Original submission](https://gna.org/bugs/index.php?10656)** by suokko on 2008-01-03

Adding tag to load customs units and images for them in scenario WML.

This would give MP scenarios access to special units in campaigns like RotW.

```
[units]

    [binary_path]

        path=<some_path>

    [/binary_path]

    [unit]

....

    [/unit]

[/units]
```

After scenario wesnoth will clean all custom units and images from game data so next scenario will be unaffected.

(Reproduced on any)
Release: trunk
Priority: 1 - Later
Severity: 3 - Normal

**Comment by jostephd** [comment]
Fixed by #3414. (Reopen if you disagree)
