### ISSUE TITLE
use name instead of tag for abilities in damage calc screen (GNA #10887)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1123]
**summary:**

The request is for the damage calculations screen to say `Inspires bonus:` instead of `Leadership bonus:` when a unit is affected by a `[leadership] name=_ "inspires"` ability.

**[Original submission](https://gna.org/bugs/index.php?10887)** by bob_the_mighty on 2008-01-26

Custom abillities that use the leadership tag (for instance) are shown in damage calculations as 'leadership' rather than the name of the custom ability. 

If different abilities are culmative and use the same tag, it could be confusing to work out what is doing what. Could it use the id instead perhaps?

(Reproduced on Windows XP)
Release: 1.3.13
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-27**

**zookeeper wrote:**

> Note: it shouldn't use the id, but the name of the ability.

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-01-27**

**noyga wrote:**

> I think zookeper meant the name (the translatable key) that is inside the ability, not the name of the tag itself.

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-09-29**

**silene changed status:** None -> Fixed

**sileneclosed the issue**

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-05-25**

**bob_the_mighty wrote:**

> This is marked as fixed, but on 1.8.1 I am still seeing 'leadership' stated in the battle calculations - when it should be the name of a custom ability.
> 
> 
> 
> Whatsmore, when an ability uses a negative value inside the leadership tag the plus and minus sign are both displayed.
> 
> 
> 
> For instance, Bob's RPG Era has a ability called Scare which deducts 10% damage from the enemy's attack (much like the old terror ability from EE). For this, the calculation screen shows: +-10%.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-05-25**

**silene changed status:** Fixed -> None

**silene reopened the issue**

**silene wrote:**

> Strange, this bug report doesn't ring a bell at all. And none of my commits are mentioned in the comments. And it isn't assigned to me either. So I have absolutely no idea why I would have closed it. I will just assume that the gna database is corrupted and I will reopen it.

**Comment by jostephd** [comment]
> For instance, Bob's RPG Era has a ability called Scare which deducts 10% damage from the enemy's attack (much like the old terror ability from EE). For this, the calculation screen shows: +-10%.

This doesn't happen in 1.15.

> Custom abillities that use the leadership tag (for instance) are shown in damage calculations as 'leadership' rather than the name of the custom ability.

Sadly this is not trivial, for two reasons.

1. The line shows the cumulative effect of all leadership-like abilities. If a unit is affected by _two_ `[leadership]` specials, the "Leadership bonus" line will show the combined (net) effect of both specials.

2. Localization. It's difficult to translate `"%s bonus:"` where `%s` is replaced by a word not known in advance (such as `leadership` or `inspires` or any word UMC authors may use at this point) because in some languages the translation would depend on, say, the gender of the substituted word.

**Comment by CelticMinstrel** [comment]
Having a _general_ way to substitute words based on gender _would_ be useful, indeed... it's a pity gettext doesn't help out with that.

**Comment by CelticMinstrel** [comment]
(Though even if there _was_ a generic way, I guess it wouldn't help _for this specific case_ since we're talking about grammatical gender..._

**Comment by stevecotton** [comment]
> Sadly this is not trivial, for two reasons. ... If a unit is affected by _two_ `[leadership]` specials, the "Leadership bonus" line will show the combined (net) effect of both specials.

I think this issue can be closed as implemented by #6462, which makes the abilities easy to see in the tooltip. Given @jostephd's point about units being affected by multiple `[leadership]` specials, I think #6462's solution is a good general answer that copes with that.

![tooltip_taught](https://user-images.githubusercontent.com/31768074/168082502-8711f654-d26e-4421-881f-5d57081d2f8c.png)
[More screenshots](https://github.com/wesnoth/wesnoth/pull/6462#issuecomment-1124978969)

**Comment by Pentarctagon** [comment]
I agree.
