### ISSUE TITLE
random map selector (GNA #10904)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1124]
**[Original submission](https://gna.org/bugs/index.php?10904)** by ukognos on 2008-01-28

a new entry at the mapselection in multiplayer games which says: 2p_random or so.

if you start a game with this entry selected, the computer will choose one out of the standart 1v1 maps (all 2p maps except wesbowl and dark forecast)

i think this would be a nice feature

(Reproduced on All)
Release: 1.3.15
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-11-16**

**gfgtdf changed title:** random map generator -> random map selector

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-01-11**

**gfgtdf wrote:**

> There are already addons that do exactly that (rushed by yetis, Sandbox, ..). So i'm not sure whether this is still needed.

**Comment by jostephd** [comment]
Closing for the reason @gfgtdf gave. The `Ladder Era` addon basically implements this for the mainline maps.
