### ISSUE TITLE
Trackpad Scrolling almost useless (GNA #11172)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1125]
**[Original submission](https://gna.org/bugs/index.php?11172)** by fugalh on 2008-02-27

I have a macbook, which has a trackbook that supports two-finger scrolling. I drag two fingers in any directon and it generates vertical and horizontal scroll events. 

Wesnoth is apparently designed to be clever about scrolling and converts scroll events to scroll along the axis to which the mouse is closest. This is no doubt very useful for people with scroll mice that have only one scrolling axis.

Unfortunately, when scrolling with a trackpad there is no way to keep from emitting horizontal scroll events. Since horizontal scroll events are treated the same as vertical scroll events, total chaos ensues. This can be worked around by going diagonally, from bottom right to top left, so that the events are at least in the same direction, but this is not at all obvious unless one understands what the problem is. Certainly it's not the best behavior.

I think ideally wesnoth would have an option to disable smart scrolling and just obey vertical (and horizontal) scroll events. This would make scrolling work well on trackpads as well as mice with both horizontal and vertical scrolling wheels.

(Reproduced on all)
Release: 1.3.19
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-02-27**

**fugalh wrote:**

> &quot;Trackbook&quot;... I'm quite sure I meant trackpad.

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-02-27**

**esr wrote:**

> I'm changing this to a feature request.  It can certainly wait until 1.5 forks.

**esr changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-05-24**

**wumpus wrote:**

> I observed this in the official build of 1.4.2 as well - thanks for the tip about working around it :-)
> 
> 
> 
> However, when I built it from source + &quot;Mac Compile stuff&quot; in order to investigate bug #11707 (see comment #9 of that bug for more details on my compile process), the scrolling suddenly worked as describe in &quot;bug&quot; #11611 - IE, scrolling vertically with the touchpad worked without issue (and without needing the workaround described here), horizontally not at all.
> 
> 
> 
> This is...  strange.  Have I missed something about the mac build process which is leading to my build behaving substantially differently to the official one?!  It makes it obviously a little difficult to improve this behaviour if my build doesn't behave like the official one ,p

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-08**

**ancestral wrote:**

> https://gna.org/bugs/?11611 may have been a duplicate of this bug.
> 
> 
> 
> Horizontal scrolling on the Mac is not a supported feature as a part of SDL 1.2, but supposedly it is included in SDL 1.3
> 
> 
> 
> http://lists.libsdl.org/pipermail/svn-libsdl.org/2007-July/000215.html
> 
> 
> 
> http://www.nabble.com/Mighty-mouse-horizontal-scroll-wheel-events--td21158099.html
> 
> 
> 
> option+scroll will perform horizontal scrolling. (I think shift-scroll is probably the OS X system default, so slightly different than what some people may be used to.)

**Comment by Wedge009** [comment]
I tested 1.14 on a Linux laptop and enabled two-finger scrolling. I'm not really familiar with it, and maybe I don't know how to use it properly, but I was able to scroll in both horizontal and vertical directions with two fingers. It may simply be a product of moving to SDL 2.0, I don't know.

Closing, but re-open if necessary.
