### ISSUE TITLE
configure option to build only specific translations (GNA #11252)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1126]
**[Original submission](https://gna.org/bugs/index.php?11252)** by megane on 2008-03-13

Since a noticeable fraction of the build time is spent building the various translations, but most players only use one, might it be possible to add a command line option to only build the one(s) you want? i.e. ./configure --enable-translations=en_US,de

IIRC someone noted on the forums that you could edit the relevant line in your Makefile to achieve this, but an option would be easier.

(Reproduced on Ubuntu 7.10)
Release: 1.4
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by sevu** [comment]
I think there is no need for that

**Comment by jostephd** [comment]
For reference, something like `echo de > po/LINGUAS` before building ought to do it.
