### ISSUE TITLE
Allow grouping/disabling of unit entries in campaign help (GNA #11314)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1127]
**[Original submission](https://gna.org/bugs/index.php?11314)** by ronnystandtke on 2008-03-18

I was just trying out the "Descent into Darkness" campaign. I took a look at the unit description of Darken Volk, clicked on the "Advances to: Necromancer" link and was surprised that in the Necromancer help there are two entries for the "Advances from" field. Both are labelled "Dark Sorcerer" but one has a question mark (see attached screenshot). Either the unit "Dark Sorcerer" is known or unknown. It can not be both at the same time.

(Reproduced on Linux)
Release: 1.4
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-03-18**

**ronnystandtke added attachment:** [wesnoth.jpg](http://gna.org/bugs/download.php?file_id=3986)

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-03-18**

**cycholka changed title:** Inconsistent &quot;Advances from&quot; entries in Necromancer help -> Allow grouping/disabling of unit entries in campaign help

**cycholka changed severity:** 3 - Normal -> 1 - Wish

**cycholka wrote:**

> Want to see nineteen such entries per unit? ;) Look at Desert Elves in UtBS.
> 
> 
> 
> And seriously it's an engine limitatoin. Both Dark Sorcerers probably exist in the campaign and they differ by few atributes, that's the reason for separate entries.
> 
> 
> 
> Changing to feature request.

**cycholka changed category:** Bug -> Feature Request

**Comment by Wedge009** [comment]
Testing 1.14, I note that Darken Volk's custom Necromancer unit type doesn't have this issue any more. I also observe the UtBS' Quenoth elves also appear to not have this issue any more. Closing, but if I'm wrong feel free to re-open.
