### ISSUE TITLE
Slow should stay in effect until it's slower's turn again, but does not (GNA #11393)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1129]
**[Original submission](https://gna.org/bugs/index.php?11393)** by anonymous on 2008-03-28

In 2on2 MP games the "slow" effect is removed once the slowed unit's side ends its turn. Instead, it should stay in effect until it is the slower's turn again.

Example:

Assume players p1 to p4 with team1 being p1,p4 and team2 being p2,p3. Now p3 slows a unit of p1 on its turn. Slow stays effective during p4's turn and during p1's turn now. But once p1 has ended its turn, slow is already removed, leaving p2 without the possibility to take advantage of the team effort. Currently, the "slow" effect can only be used by the other team players if they move after the slower's side.

However it would make more sense to me if turn order would not matter here.

The attachment is a replay showing the problem. In turn2, Green has slowed a red Gryphon. But when Blue is about to move (turn3), slow is already gone.

(Reproduced on Linux)
Release: 1.4 stable
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by gfgtdf** [comment]
> In 2on2 MP games the "slow" effect is removed once the slowed unit's side ends its turn. Instead, it should stay in effect until it is the slower's turn again.

Yes this is the same behvaiour as in sp, changing this woudl make the game more complicated since the game and the players would have to remmber who slowed the unit. I don't think this will be changed.

**Comment by ProditorMagnus** [comment]
Implemented as https://forums.wesnoth.org/viewtopic.php?t=42668

**Comment by gfgtdf** [comment]
Anyone with an opinion on this should we just reject this?

**Comment by Pentarctagon** [comment]
IMO the duration of the slows effect should be consistent regardless of who did the slowing.  Having it be dependent on which side did the slowing feels like an unnecessary complexity, and also it's not game logic that's as obvious to the player due to the current inconsistency.

@Hejnewar - any opinion?  This would effectively be a sort of buff to slows, though since this would only affect maps with 3+ players my assumption is it wouldn't be too much of an impact.

**Comment by gfgtdf** [comment]
> IMO the duration of the slows effect should be consistent regardless of who did the slowing. Having it be dependent on which side did the slowing feels like an unnecessary complexity, and also it's not game logic that's as obvious to the player due to the current inconsistency.

Im not quite sure what you mean here you first  talk about complexity, and then about the current sitatuion, so are you trying to say that the _current_ way is more complex?

**Comment by Pentarctagon** [comment]
I meant that I could see new players being confused about why the slows duration isn't consistent.

**Comment by gfgtdf** [comment]
and which behavior do you think is more  "consistent" ?

**Comment by Pentarctagon** [comment]
The one described in this issue - it always lasts until the start of the slower's turn.

**Comment by Pentarctagon** [comment]
That said, I don't feel particularly strongly about it, so I'm fine with just closing the issue as well.

**Comment by Wedge009** [comment]
I don't have a strong opinion either, as I only play SP games. If I understand the proposal correctly, the request is to have the slow status last until it's back to the turn of whoever cast the slow. This means it's only potentially a difference for games with three or more players: eg Player 1 slows a unit belonging to Player 2, Player 2 has their turn, and then (currently) that's the end of the slow effect.

If the slow effect continues until it's Player 1 again then that means Player 3 (or more) can also benefit from the slow status against Player 2, in a free-for-all situation, or if Player 3+ is allied with Player 1. I don't know how significant this could affect MP games - nor if it would be viewed as a positive or negative change, but given the forum post reference, perhaps the community is interested in this change as a positive? In which case they already have that as an add-on (though not sure if all players would need to have this add-on installed or just the host).

If the add-on is a satisfactory work-around, I think it's reasonable to close this.
