### ISSUE TITLE
Re-add "variable speed on land" feature (GNA #11525)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1130]
**[Original submission](https://gna.org/bugs/index.php?11525)** by ai0867 on 2008-04-20

In 1.2, a unit's sliding speed was inversely proportional to the movement cost. This feature was removed somewhere in 1.3.

Request re-adding.

http://www.wesnoth.org/forum/viewtopic.php?p=294193#p294193

(Reproduced on Any)
Release: 1.4.1
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-04-20**

**boucman changed category:**  -> Bug

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-08-28**

**esr changed category:** Bug -> Feature Request

**Comment by Wedge009** [comment]
I only started playing around 1.4, so I'm not sure how I've ever seen it in action. Is it something that's still missed by players?

**Comment by CelticMinstrel** [comment]
I only started playing at 1.10 so presumably I've never seen it either, but... it does seem like a nice idea to me.

**Comment by Wedge009** [comment]
Hmm... unit movement animation speed is constant... sounds like it used to be units with many moves (such as cavalry) would slide really quickly and slower units (like heavy infantry) would slide really slowly. Possibly such that a cavalry unit would complete its movement across 8 or so hexes in less time than a heavy infantry would move across 3 (or whatever). I'd have to see it in action but just thinking about that I'm not sure I'd like it.

**Comment by CelticMinstrel** [comment]
That sounds different from what the opening post was describing, which seems to imply the sliding speed will vary as the unit moves, depending on which terrain it's crossing. So for example, crossing a mountain would be slower.

**Comment by Wedge009** [comment]
Ohhh, movement cost of the terrain. That makes more sense. So slower in terrain where it costs more than 1MP per hex.  Again, would be interesting to see.

**Comment by boucman** [comment]
yeah, it was fun, but IIRC it was removed because it slowed the gameplay too much...

I would advise looking for the commit that removed it and check the commit message for the actual reason... I can't really remember why, it was such a long time ago...

**Comment by Pentarctagon** [comment]
Closing since something that's been mentioned a fair number of times by players is that they already today increase the default speed of animations (which I myself also tend to find myself doing) since they slow down gameplay quite a bit, so adding something else that would further slow down gameplay wouldn't be good.  This would also end up looking somewhat odd when applied to units that have actual movement animations rather than just sliding around.

**Comment by Wedge009** [comment]
Sounds like a reasonable judgement to me.
