### ISSUE TITLE
Support for multidirectional scrolling devices (GNA #11611)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1131]
**[Original submission](https://gna.org/bugs/index.php?11611)** by apismenny on 2008-05-01

Apple Mighty Mouse (default mouse for a desctop Mac) has a scrolling ball and MacBooks have touchpads that support scrolling in both directions. This works in most of the Mac OS X programs, but not in BfW. In windowed mode you can only scroll vertically with the ball/touchpad and only sideways using borders.

(Reproduced on Mac OS X)
Release: 1.4.1
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2008-05-01**

**alink wrote:**

> Copied ftom my reply from the forum thread, because it add few technical details for the fixer:
> 
> http://www.wesnoth.org/forum/viewtopic.php?t=21173
> 
> 
> 
> 
> 
> Wesnoth normally support horizontal mousewheel (with a horizontal scrolling). At least is was working the last time I checked in linux+Xorg.
> 
> 
> 
> You can also use Alt + vertical mouselwheel to do horizontal scrolling.
> 
> 
> 
> We currently lack Mac developer for really coding+testing things like that. If you know a little about SDL (or want to learn SDL, which is not a big thing), feel free to post a patch. The only problem is that this part is not very documented in SDL, so probably need to do some googling or experiment by scanning what type of events SDL detect when you use your mouse.
> 
> 
> 
> In code search about SDL_BUTTON_WHEELLEFT (it's in src/mouse_events.cpp, and src/sdl_utils.hpp)
> 
> and maybe add a &quot;#ifdef __APPLE__&quot; if the change is mac-specific.

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-02-25**

**ancestral wrote:**

> Did some research on this.
> 
> 
> 
> http://lists.libsdl.org/pipermail/svn-libsdl.org/2007-July/000215.html
> 
> 
> 
> Looks like they left it out of SDL 1.2. I have yet to try building, but apparently SDL 1.3 finally adds support for this.
> 
> 
> 
> http://www.nabble.com/Mighty-mouse-horizontal-scroll-wheel-events--td21158099.html

**Comment by dhardy** [comment]
Has this not been implemented? At least, I've been scrolling (horizontally and vertically) on recent Linux versions. Which brings me to #2218.

**Comment by CelticMinstrel** [comment]
I think it supports four-way scrolling but not free scrolling (like the Apple Magic Mouse). Not entirely sure though.

**Comment by gfgtdf** [comment]
i just tried to play wesnoth 1.14.0 on my laptop (windows 10) and im also effected by this. Horizontal scrolling does not work (it works in other programms such as firefox)

**Comment by Wedge009** [comment]
Seems related to #1125.

**Comment by Wedge009** [comment]
@gfgtdf Still an issue in 1.14.7? Reading the older comments here and in #1125 I thought it had the impression this is SDL-related, but we've been on SDL 2.0 since 1.14, haven't we?

**Comment by Pentarctagon** [comment]
Can this be closed then?

**Comment by Wedge009** [comment]
No response since August 2019 - more than four years ago as at time of writing. I'd say so, but can re-open if really necessary.

On the topic of touch-pads, there seems to be horizontal scrolling on at least some devices otherwise there wouldn't be issues like #3362 and #7404.
