### ISSUE TITLE
Add detailed info to unit advancing dialogue (GNA #11626)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1132]
**[Original submission](https://gna.org/bugs/index.php?11626)** by mcshark on 2008-05-03

If you put the cursor over unit attributes like loyal etc. in main screen you get detailed info.

It would be nice to have this feature in unit advancing dialogue, too.

(Reproduced on WinXP home)
Release: 1.5.0+svn
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by gfgtdf** [comment]
This was implemented shortly after we ported that dialog to gui2.
