### ISSUE TITLE
[Preferences] Include map position in saved games (GNA #12788)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1142]
**[Original submission](https://gna.org/bugs/index.php?12788)** by anonymous on 2008-12-26

Currently, when users load previously saved games, the scenario always starts in a map position where the protagonist is. It would be nice if the preferences (Ctrl-P) would have an option that allows users to change this behavior. When loading scenario's the alternative setting would start those in the map position where the game was saved.

Example: While playing Elves' Last Stand from Legend of Wesmere, users could choose to keep leader Kalenz on the keep while his forces are near the keep of Urug-Pir fighting bad guys. Users who save their game now and then may prefer Wesnoth to load the saved games in the map position where they saved them. In this case, showing the keep of Urug-Pir instead of where Kalenz is hanging out.

(Reproduced on GNU/Linux)
Release: 1.5.6
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-10-24**

**anonymous wrote:**

> Compare with bug #8152.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-03**

**shadowmaster wrote:**

> Deassigning bugs from inactive developers.

**Comment by gfgtdf** [comment]
using the position of the saved gameis now default behviour
