### ISSUE TITLE
Please use fontconfig for system fonts (GNA #12810)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1143]
**[Original submission](https://gna.org/bugs/index.php?12810)** by limburgher on 2009-01-02

To avoid having to include fonts that are likely already available to users, please use fontconfig.  Currently, distributions are faced with either wasting space on duplicated font files or symlinking, which will result in either breakage or extra maintenance.

Thank you!

(Reproduced on Linux)
Release: 1.4.7
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-01-03**

**esr changed category:** Bug -> Feature Request

**Comment by Wedge009** [comment]
Will this request help in issues like #1549? Although, that one seems to be Windows-specific and AFAIK fontconfig is mainly for *NIX systems.

**Comment by Pentarctagon** [comment]
Given it was said
> on macos and linux we use fontconfig which will attempt to figure out and use a fallback font at all costs

this would seem to be resolved, therefore closing.
