### ISSUE TITLE
Glitch when a submerged unit stands on an [item] (GNA #13041)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1146]
**[Original submission](https://gna.org/bugs/index.php?13041)** by zookeeper on 2009-02-21

When a unit stands in for example water and there's an [item] on that hex, the item image will show through the half-transparent submerged part of the unit. Instead, the item should obviously always remain behind the unit regardless of submersion.

Easy to test in Bay of Pearls in HttT: just take a mermen to the storm trident and don't pick it up.

(Reproduced on All)
Release: trunk
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-12-28**

**boucman wrote:**

> this one is very very tricky to fix
> 
> 
> 
> the problem is that units in water are "half transparent", so we need a way to tell the item how much of itself should be transparent, which breaks the current design badly
> 
> 
> 
> no idea how to fix that one...

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-08-08**

**wedge009 wrote:**

> I confirm this issue is still around in 1.13.1+dev, but honestly I don't think it's that bad. Even when I first started playing Wesnoth back in 1.4.x and was playing Heir to the Throne, this glitch didn't stick out in my mind at all. True, it might be ideal to have the item hidden behind the unit in question... but on the other hand, I find it's probably useful to have the item still visible on the off chance one chooses not to pick up the item with the first unit that contacts it.
> 
> 
> 
> Given the technical effort it would take to resolve this, I think this one can be left alone. Would be nice to fix, but not really essential.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-07**

**wedge009 changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-07**

**wedge009 changed OS:** win xp -> All

**Comment by knyghtmare** [comment]
Seems to be resolved with https://github.com/wesnoth/wesnoth/pull/6855.

**Comment by Wedge009** [comment]
Hmm, does this still count as 'showing through'?
![item](https://user-images.githubusercontent.com/13679322/178650331-d6729fc9-1055-4265-83db-b2e68098ee52.png)

**Comment by knyghtmare** [comment]
Seems item by item basis bug. I tested with "rock-submerged" in Dead Water.
![image](https://user-images.githubusercontent.com/5283677/178651353-2cd224a2-3777-40ad-849c-2b52fc29ce32.png)

**Comment by knyghtmare** [comment]
The whirlpool one is visually correct...rest seem to exhibit the bug.

Apparently _Dead Water_ got around this by _submerging_ the items which got placed over deep/shallow water

![image](https://user-images.githubusercontent.com/5283677/178651699-eb31d85e-ac83-41c7-992b-f4793091d70e.png)

**Comment by mesilliac** [comment]
I'm not really sure what should happen in the case of the trident. If the trident is floating on the water... how does it work if there is also a unit there?

**Comment by mesilliac** [comment]
Either the trident is stabbing the unit, or the trident is behind the unit in which case the trident itself should be submerged. In that case, submerging the item like with the rock here would be the correct solution.

**Comment by knyghtmare** [comment]
> Either the trident is stabbing the unit, or the trident is behind the unit in which case the trident itself should be submerged. In that case, submerging the item like with the rock here would be the correct solution.

Seems there should be some set of submerged items, which makes this bug issue a feature request

**Comment by knyghtmare** [comment]
I think so too. It does look a lot better for submerged items.
