### ISSUE TITLE
Campaign server should allow lists of icons (GNA #13146)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1148]
**[Original submission](https://gna.org/bugs/index.php?13146)** by turin on 2009-03-09

So, for all my Imperial Era campaigns, I like to use units from the IE for the campaign icon (for obvious reasons). But this makes it so that people who don't have the IE downloaded get error messages about not being able to open the images. So to avoid that I have to either leave the icon blank, or use something that doesn't actually represent the campaign (because the only images that do represent the campaign are found in the Imperial Era). For obvious reasons, I don't find either of these satisfactory.

Obviously this can't be fixed for 1.6, but it'd be nice if I could do something like this in the pbl file:

icon="units/human-marauders/warrior.png~RC(magenta>blue)","items/brazier-lit4.png"

Where it would load warrior.png if it could find it, but if it couldn't it would go on to brazier-lit4.png *without giving an error message*. It would only give an error message if none of the images could be found.

(Reproduced on all)
Release: 1.5.12+svn
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-02-07**

**noyga wrote:**

> would :
> 
> 
> 
> icon="units/human-marauders/warrior.png~RC(magenta>blue)"
> 
> icon_alt="items/brazier-lit4.png" 
> 
> 
> 
> be sufficient ?
> 
> It can be implemented trivially this way, without even breaking the string freeze.
> 
> (feel free to suggest a better name for "icon_alt")

**Comment by gfgtdf** [comment]
closing this as one can now put base64 image data into that

**Comment by CelticMinstrel** [comment]
base64 doesn't satisfy this request at all.

**Comment by ln-zookeeper** [comment]
The original request was for a workaround for a problem (use an alt icon when the icon you really want can't be found), and the DataURI feature lets you avoid the problem altogether (you can always use the icon you really want), so surely the request is either satisfied or made obsolete.

**Comment by CelticMinstrel** [comment]
Yeah, I see what you mean. I still think there could be room for this feature (since DataURIs can get quite large), but maybe it's obsolete now.
