### ISSUE TITLE
Add difficulty scale for A New Land MP scenario (GNA #13154)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1149]
**[Original submission](https://gna.org/bugs/index.php?13154)** by bob_the_mighty on 2009-03-09

After playing 'A New Land' a few times on the new version it seems 100g makes for a very easy game. I suggest setting the starting gold to 75g per side.

I still managed to complete it with less gold, but it was much more challenging. As governor said after our last game, it was 'teetering on impossibility'. This is how a survival should be.

(Reproduced on Windows XP)
Release: 1.5.12-1.6rc1
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-01-10**

**gfgtdf wrote:**

> > it was 'teetering on impossibility'. This is how a survival should be.
> 
> 
> 
> I doubt everyone would agrees with this. I think the best solution would be to have different difficulcy levels for that scenario similar to campaigns.

**Comment by sevu** [comment]
I'm leaning towards closing this, because there are people first time playing this, so it should not be insanely hard.

**Comment by gfgtdf** [comment]
As I said, one could add multiple difficulty levels to serve both types of players

**Comment by sevu** [comment]
Dark forecast has a difficulty slider, but from what the OP wrote that's actually the gold setting (basically the only setting which is not locked... despite the leader selection)

I had the idea in mind to make the guards loyal (because otherwise you are punished for killing a guard), maybe as a side effect enemy income could be increased slightly.

**Comment by Wedge009** [comment]
I think it's pretty clear what bob was asking. I'd agree with closing this too - one is free to choose whatever starting gold the players should have and the 100 is only a recommendation.

**Comment by jostephd** [comment]
@Wedge009 I think the `Campaign` label is correct here, this is an issue about a specific map, not about the MP engine in general.

**Comment by sevu** [comment]
The most realistic to happen, would be to change wording of https://github.com/wesnoth/wesnoth/blob/master/data/multiplayer/scenarios/4p_A_New_Land.cfg#L6.

How about:
> This 4p survival scenario allows you to construct buildings and terraform the land.\n
\n
~The recommended starting gold is 75 for experienced players.~
For experienced players, it’s recommended to lower the starting gold to 75.

```
