### ISSUE TITLE
Treat objects as maps (like JavaScript does) in FormulaAI (GNA #13157)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1150]
**[Original submission](https://gna.org/bugs/index.php?13157)** by seahen on 2009-03-10

In FormulaAI, the only difference I can see between the dump of an object and the dump of a map is that the former has curly brackets and the latter has square.

Why not change the curly brackets to square and treat objects as maps, the way JavaScript does? This would make it possible to:

* perform runtime duck typing.

* copy an object and add new custom properties to the copy.

* create dummy units, hexes, moves etc. that would have some or all of the properties of real ones.

FAI already has weak dynamic typing, so let's take advantage of all the features that weak dynamic typing offers.

(Reproduced on all)
Release: 1.5.10+svn (32849)
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by CelticMinstrel** [comment]
Oh! I did this without even knowing there was an issue for it!
