### ISSUE TITLE
Provide FormulaAI console mode (GNA #13158)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1151]
**[Original submission](https://gna.org/bugs/index.php?13158)** by seahen on 2009-03-10

It would be useful if Wesnoth had a command-line option, which I shall give the working name --formula, which would allow FormulaAI to interface with the console.

If --formula was combined with -m, it would implicitly set --nogui, and on each local human player's turn, that player could enter input to FormulaAI (as though they were in the GUI and had pressed f), and the output would be printed to console.

If --formula was used without -m, *only* the FormulaAI console would load. Game-specific variables and functions would not exist, but formulas that didn't depend on them could still be tested.

Not only would this be useful for AI development, but because it would provide a complete console interface to the game, it would make alternative front-ends possible.

(Reproduced on all)
Release: 1.5.10+svn (32849)
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by mattsc** [comment]
Uses of Formula AI have been removed from mainline at this time, and FAI as a whole will be deprecated in 1.17.  Suggest marking this as "won't do" and closing it.

**Comment by mattsc** [comment]
Right.  I am aware of the distinction between FAI and WFL and the existence of the in-game formula console.  I am suggesting closing this specifically because it is about FAI, not WFL, and because of the existence of the in-game console.

**Comment by CelticMinstrel** [comment]
Yeah, that seems reasonable. It sounds like the in-game console already existed when this was posted, but without FormulaAI there's less of a rationale for this.

That said… a similar thing could apply to Lua AI, providing a REPL-like console where you can enter in AI commands and basically play a game without the UI. Still pretty niche though…
