### ISSUE TITLE
Give the "full map" hotkey a better name to state that it is replay only (GNA #13191)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1152]
**[Original submission](https://gna.org/bugs/index.php?13191)** by beetlenaut on 2009-03-13

If you set a hotkey for showing the full map, the key has no effect.

(Reproduced on Linux)
Release: 1.5.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Wedge009** [comment]
Even looking at a replay I'm not sure what the Full Map Point of View is supposed to do...

**Comment by CelticMinstrel** [comment]
I think it's supposed to ignore fog and shroud?

**Comment by Wedge009** [comment]
Ah, I was testing a replay that didn't have either, no wonder I didn't notice any difference. All the more reason to try to work out something equally brief yet more descriptive than just 'full map'.

**Comment by gfgtdf** [comment]
i think the original issue can still be considered fixes since the hotkey windows now shows in which context a hotkey is available. Mayve it's be better to rename it to 'full map view' though? But it's quire possibel that it'd then alos appear as 'full map view' in the replay vision menu button which woudl be a a biut redundant there.

**Comment by Wedge009** [comment]
I'm not quite sure, with all those typos, if you're referring to the hot-key preferences window. I only saw it was in the context of 'editor' (only other options are 'game' and 'title'), rather than replay, though I suppose there aren't enough options for replay to have its own category.

**Comment by gfgtdf** [comment]
oh sry yes i was just confused, forget what i said.

**Comment by Wedge009** [comment]
I can't think of a good way to describe this function succinctly, but I'm wondering if it's worth having optional tool-tips on individual hot-key actions - this way when hovering over Full Map a description could be given to say that this is for removing fog and/or shroud during replays.

**Comment by jostephd** [comment]
> I can't think of a good way to describe this function succinctly

`Viewpoint: Full Map (replays only)`

and rename the hotkeys for "Human Team" and "Each Team" in the same way.

This will also group them in the list, which makes sense in its own right.

**Comment by CelticMinstrel** [comment]
Maybe adding the word "View" or "Viewpoint" would also help to clarify?

**Comment by Wedge009** [comment]
Quoting myself from 25 August
> I only saw it was in the context of 'editor' (only other options are 'game' and 'title'), rather than replay, though I suppose there aren't enough options for replay to have its own category.

I realise now that Replay hot-keys are under 'game' - but with the scroll bars necessary for the window (even in English, since I have some custom hot-keys) the green dots indicating 'game' got pushed to the right so that I mistakenly read them as 'editor'.

**Comment by Wedge009** [comment]
Changing the names in the hot-key menu also change the text in the replay menu itself. But I think it's not too bad.

**Comment by jostephd** [comment]
> I realise now that Replay hot-keys are under 'game' - but with the scroll bars necessary for the window (even in English, since I have some custom hot-keys) the green dots indicating 'game' got pushed to the right so that I mistakenly read them as 'editor'.

So let's change the green dots to `"hotkeys preferences screen^G"` for the Game column, and E and T for the other two columns, at least until someone fixes the column widths in the table header row?
