### ISSUE TITLE
split forest graphics iinto two layers in order to handle some edge cases better (GNA #13242)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1153]
**[Original submission](https://gna.org/bugs/index.php?13242)** by anonymous on 2009-03-22

After the scout was slowed by an elven shaman, his face was obscured behind a forest tile. Screen shot provided shows the end result. The artifact cleared up as soon as the scout moved.

(Reproduced on Ubuntu)
Release: 1.6
Priority: 3 - Low
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-03-22**

**alink wrote:**

> No screenshot attached :-/

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-03-24**

**ai0867 wrote:**

> The shield of the right dwarf fighter shows what is probably the same thing. Whether this is a bug or not I don't know.
> 
> 
> 
> http://wesnoth.org/start/1.6/images/start-4-full.jpg

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-04-10**

**boucman wrote:**

> hmm
> 
> 
> 
> this "works as designed" I'm not sure if/how to fix that
> 
> 
> 
> basically, to convey a feeling of "depth" some tiles are drawn in front of others (think of the elven tree for example) 
> 
> 
> 
> in that case the overlay of the bordering tile overspill a bit too far, but the tile is considered in front of the uni and its overlay is thus drawn in front.
> 
> 
> 
> this is an artistic bug, but I'm not sure it's worth fixing. I will forward to zookeeper for the time being, but he will probably mark as "won't fix"

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-04-14**

**zookeeper changed status:** None -> Postponed

**zookeeper wrote:**

> It would be possible to fix these glitches for terrains such as forests. However, it'd require splitting off all the forest graphics into at least two parts so that the top and bottom parts of the tile could layer differently and thus for example the offending little tree in this case would get drawn behind the unit.
> 
> 
> 
> However, it'd be a pretty big task for relatively little gain, so as a workaround I'd suggest just moving any trees which are far away from the hex (such as that one little tree) a bit closer to their hex to prevent them from overlapping with adjacent units in such a noticeable manner.
> 
> 
> 
> I'll mark this as postponed, since we might actually implement the proper fixes one day.

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-10-29**

**esr changed status:** Postponed -> None

**esr wrote:**

> This was "graphics bug with shaman/forest/orc scout".  Reclassifying as a low-priority FR and retitling to reflect what's actually needed

**esr changed priority:** 5 - Normal -> 3 - Low

**esr changed title:** graphics bug with shaman/forest/orc scout -> split forest graphics iinto two layers in order to handle some edge cases better

**esr changed category:** Bug -> Feature Request

**esr changed severity:** 3 - Normal -> 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-01**

**mattsc added attachment:** [small_tree_in_front_of_wolf.png](http://gna.org/bugs/download.php?file_id=20451)

**mattsc wrote:**

> Reviving this since almost 5 years later it is still unchanged.  See attached screen grab.  No new information though.
> 
> (file #20451)

**Comment by Pentarctagon** [comment]
Can confirm this still happens on 1.15.15.

**Comment by Pentarctagon** [comment]
@doofus-01 would this be something you'd be able to look into?

**Comment by doofus-01** [comment]
Sure, I'll look into it.  No guarantees at this point, but we'll see.

**Comment by doofus-01** [comment]
I think this is fixed, but someone else should confirm (1.16, not master)

**Comment by Pentarctagon** [comment]
Looks good to me.

**Comment by doofus-01** [comment]
Thanks.  I'll close this then.
