### ISSUE TITLE
Zoomable portraits in help (GNA #13361)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1156]
**[Original submission](https://gna.org/bugs/index.php?13361)** by beetlenaut on 2009-04-12

It would be nice if the small portraits on the help screens were links. Clicking on the link would show a blank help window with the large-size portrait in it. That would let you see all the details on the beautiful portraits we have now, and make the artists' work more prominent. The "back" button would take you back to the regular unit page.

(Reproduced on Linux)
Release: 1.6a
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-04-12**

**esr changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-06-24**

**anonymous wrote:**

> Maybe display them bigger when hovered with the mouse pointer?

**Comment by cooljeanius** [comment]
there's zooming code elsewhere in the game; would it be possible to reuse it for this?

**Comment by Wedge009** [comment]
Loosely related, I remember @Vultraz recently remarking how the interpolation used for the sprites in Help's unit pages are different to the interpolation used in the actual game screen.

I think the state of the Help in 1.14.17, even if still limited by GUI1, is likely better than its implementation back in 2009 - or at least the portraits available now are very large (relative to the window) and easily visible. In which case, is it still required to have this open? Looks like @beetlenaut made the original request.

**Comment by beetlenaut** [comment]
When I made this request, the help screen used half-sized portraits. It uses full-size ones now, so it's not an issue. This can be closed far as I'm concerned. It can even be marked "fixed" if you want.

**Comment by Wedge009** [comment]
Thanks for the feedback.
