### ISSUE TITLE
"The Chief Must Die" needs redesign (GNA #13511)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1159]
**[Original submission](https://gna.org/bugs/index.php?13511)** by cathyr19355 on 2009-05-11

I'm playing Legend of Wesmere on "normal" difficulty and I've reached the "Chief Must Die" scenario where they have to kill the Orc Sovereign while invisible and escape.  The unit descriptions claim that no unit is supposed to initiate an attack on you while you're invisible, except for wolf units because they can smell you.

The problem is that the wolf units start approaching you if you're anywhere within their movement range (9 or 10 hexes, depending on the level of wolf).  When they reach you, they attack you.  If you kill them, all the nearby non-wolf units start piling on you and attack.  So I'm having to stay *outside* every wolf unit's range (and I have to make sure the area is clear of units in general before I kill a wolf that happens upon me).

I'm convinced that this situation makes the scenario unplayable.  Even if I'm wrong and it is still winnable, it's no longer fun.  

I've attached a save file from my game--it shouldn't take more than a few turns for you to see what I mean.

(Reproduced on Ubuntu)
Release: 1.7.0 svn35547
Priority: 3 - Low
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-05-11**

**cathyr19355 added attachment:** [LOW-The_Chief_must_die-Auto-Save23.gz](http://gna.org/bugs/download.php?file_id=5774)

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-05-13**

**ivanovic changed item group:**  -> None of the others

**ivanovic changed severity:** 5 - Blocker -> 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-05-13**

**ivanovic wrote:**

> Yesterday esr already said that he has no real idea how this is supposed to work (and zookeeper does not know it either). So assigning it to you in the hope that you find a nice solution for 1.7.0 which is due for Sunday...

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-05-18**

**esr wrote:**

> It appears from the code that the wolf guards use formula AI and are supposed to have a guard radius of 3.  That would make the scenario playable.

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-05-18**

**crab wrote:**

> They have the guard radius of 3. but, detection triggers when wolf is at 3 squares from elf during the movement, not only before the movement and after the movement
> 
> I've got a proposal:
> 
> 
> 
> --
> 
> 18:53 <Crab_> fendrin: ok, I see. well, the map is definitely beatable, but to do it one the 1st try and without reloading, the player will need to 1) know the guard radius (as zookeeper has said) 
> 
> 18:53 <Crab_>  2) sit for first 7 turns doing nothing but calculating the riders' waypoints (as the player cannot set labels on the map on enemy turn, he'll need to use a pencil-and-paper approach to write their movements, and set labels later). and then, after patrol routes are known,  the player will need to calculate the 'safe path' and stick to it.
> 
> 18:55 <Crab_> the wolves are too fast - so it's very hard to 'predict' their movements, and to 'predict' safe zones (without labeling them beforehand) , so trying to beat the map rush-style will lead to many reloads.
> 
> 18:56 <Crab_> I've got a suggestion: spare the player from that hard work of labeling patrol routes (or remembering them in some other way), (at least on easy/normal difficulties) - place the labels "Wolf X was here on turn Y" when the wolves move each turn.
> 
> 18:57 <Crab_> then, any player who's patient enough will have the routes after those 7 turns (7 is longest patrol route), will still have a puzzle to solve "how to get to that chief?"
> 
> 18:58 <Crab_> and no save\reloads will be required.
> 
> 18:59 <Soliton> maybe you can make the routes fairly obvious via map design?
> 
> 18:59 <Crab_> Soliton: hard, since each wolf uses his own route, and they're chaotic enough
> 
> 19:00 <Crab_> from the story perspective, incremental 'labeling of patrol routes' this will simulate the fact that Kalenz is smart enough (and is patient enough) to remember all those wolves movements :)
> 
> 19:03 <Crab_> 12 wolves, each with ~9 moves, are too fast for 38x30 map :)
> 
> 19:04 <Crab_> and note that the wolf hasn't got to 'end a move' within 3 squares of the elf - he can detect on 'passing by' and attack instead
> 
> 19:06 <Crab_> (ok, I go now, will return later today)
> 
> 19:06 -!- Crab_ [n=Crab_@wesnoth/developer/crab] has quit ["Leaving."]
> 
> 19:07 <Soliton> placing labels seems a bit out of character to me but with dialog from Kalenz that sounds good.
> 
> --

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-07-08**

**fendrin changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-08-21**

**fendrin changed status:** Confirmed -> In Progress

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-10-29**

**fendrin changed item group:** None of the others -> Campaign

**fendrin changed priority:** 5 - Normal -> 1 - Later

**fendrin changed category:** Bug -> Feature Request

**fendrin changed severity:** 3 - Normal -> 2 - Minor

**fendrin changed release:** 1.7.0 svn35547 -> 1.7.7+

**fendrin changed title:** LOW--orcs find the heroes too readily in &quot;The Chief Must Die&quot; -> "The Chief Must Die" needs redesign

**fendrin wrote:**

> The scenario is still not designed well but no longer broken.
> 
> So I change this to a feature request so it is out of the way for 1.8.
> 
> 
> 
> I plan to redesign the scenario to an underground/indoor exploration one that is event driven like UtBS 08.

**fendrin changed status:** In Progress -> Postponed

**fendrin changed OS:** Ubuntu -> All

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-10-29**

**fendrin changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-10-29**

**fendrin changed status:** In Progress -> Postponed

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**shadowmaster changed status:** Postponed -> None

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-27**

**fendrin changed priority:** 5 - Normal -> 3 - Low

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-12-29**

**fendrin changed status:** None -> Postponed

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-07-23**

**gfgtdf changed status:** Postponed -> None

**Comment by Wedge009** [comment]
I could be wrong, but I recall seeing a _bug_ report of this issue where it was determined that the ideal approach to the keep was from the opposite side of where Kalenz and Landar start from. It may be lost in the old gna.org system...

**Comment by CelticMinstrel** [comment]
I do have the closed GNA bugs still, I think… I could look that up in then.

**Comment by soliton-** [comment]
You can find the old bug reports in: https://files.wesnoth.org/gna_bug_export_02052017.xml.gz

**Comment by Wedge009** [comment]
Two references to the difficulty of The Chief Must Die are Gna reports #13511 (migrated as this issue) and #25411. I was thinking of the latter one as I'm a participant in that conversation and @mattsc gave a demonstration of how the scenario is supposed to be played, approaching from the south-east. That report was a later submission than this one - maybe the scenario could be redesigned to make the intended approach a bit more obvious, but it seems we agreed to close #25411 so perhaps this one can be closed too?

**Comment by nemaara** [comment]
I just tried playing this as well, there are many approaches you could take to get to the great chieftain since you can kill guards without fear of retaliation. Northwest is one, southeast is another. Unless there are other comments, I'll close this soon.
