### ISSUE TITLE
Publish wesnoth server using Avahi/Zeroconf (GNA #13703)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1162]
**[Original submission](https://gna.org/bugs/index.php?13703)** by anonymous on 2009-06-15

Currently, joining a multiplayer scenario requires entering the IP address of the wesnoth server, even if the server is on the local network. Setting up multiplayer games could be made much easier if wesnothd would publish its service using Avahi/Zeroconf/Bonjour. That way, the client could discover available wesnoth servers on the local network and display them to the user.

(Reproduced on Linux)
Release: 1.6
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-12-31**

**keb wrote:**

> This sounds like a cool feature, but please dont make avahi/zeroconf/bonjour mandatory prerequisites to build or install the game.

**Comment by Pentarctagon** [comment]
Closing given how old this is, as well as the amount of effort likely involved in implementing a rarely used feature.
