### ISSUE TITLE
Show registered players with bold in game creation screen as well (GNA #13830)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1164]
**[Original submission](https://gna.org/bugs/index.php?13830)** by grzywacz on 2009-06-30

Currently it's difficult to tell if players joining the game have their nick registered. This makes it more difficult to remove repeating offenders.

(Reproduced on Any)
Release: 1.7.x
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-03**

**shadowmaster wrote:**

> Deassigning bugs from inactive developers.

**Comment by jostephd** [comment]
Closing since the official servers require registration. (If someone needs this for their own private server we can reopen.)

**Comment by ProditorMagnus** [comment]
It needs to be closed more specifically because the bold names were removed from lobby.
