### ISSUE TITLE
defending statistics view (GNA #13960)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1168]
**[Original submission](https://gna.org/bugs/index.php?13960)** by freem on 2009-07-15

I have find that it is not ever impossible to see combat statistics for the best attack of an enemy unit. For example, if I attack with an adept an elvish warrior, I can't see statistics for when he fight, at his turn with his corporal attack because I have no corporal attack.

(Reproduced on all)
Release: 1.6.4
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-07-17**

**soliton wrote:**

> How should the interface look like?

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-10-24**

**anonymous wrote:**

> Reported earlier at least in bug #6292, recently marked fixed.

**Comment by jostephd** [comment]
It's possible to view the statistics by doing a mouseover over the words "melee-blade" in the sidebar when the Elvish Fighter is selected. See also #3956.

**Comment by Wedge009** [comment]
As with #1091 it sounds like another case of the feature being available, just not obviously so. Should we keep such issues open?
