### ISSUE TITLE
regression: show setup screen when observing (GNA #14310)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1171]
**[Original submission](https://gna.org/bugs/index.php?14310)** by mystic_x on 2009-09-13

Before the loading proggress bar was introducted, when a player went to observe a game, it would show the setup screen while the game was loading. The observer could look at what players are in which slots, their leaders and any changed settings. This helped to kill time waiting for the game to load, very unlike the loading screen. There is a workaround of starting the game with -s argument, but that's not quite it. The feature would be disabling the loading screen or somohow merging it with the setup screen, when observing a game.

(Reproduced on .)
Release: 1.7.5
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-05**

**ivanovic changed item group:** User Interface -> Multiplayer Lobby

**Comment by Pentarctagon** [comment]
@Vultraz is this something that you think would be worth implementing?

**Comment by soliton-** [comment]
Definitely an unfortunate regression but probably not useful to keep this open.
