### ISSUE TITLE
Team name in tooltip is not translated (GNA #14654)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1175]
**[Original submission](https://gna.org/bugs/index.php?14654)** by stikonas on 2009-10-31

Team name in tooltip is not translated.

Hoover mouse on the team flag at the top of the screen. Tooltip shows untranslated name.

(Reproduced on GNU/Linux)
Release: 1.7.7+svn
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-11-01**

**silene wrote:**

> It is not translated, because it is not the team name. It is the save id, which cannot be translated (otherwise savegames would be lost when changing languages).
> 
> 
> 
> I could replace it with the real team name (which then would be translated), but it would cause the player names to no longer appear in multiplayer games. So I'm a bit reluctant to do this change.

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-12-26**

**silene wrote:**

> The leader name in the turn-start message is taken from the same place and therefore suffers from the same issue (bug #14984).

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-08-11**

**anonymissimus wrote:**

> also reported here: bug #18490

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-05**

**wedge009 wrote:**

> Possibly also related: #19660

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-06**

**gfgtdf wrote:**

> I dont know which tooltip you mean exactly but there were somc changes regarding save_index/current_player etc. so im marking this as ready to test.

**gfgtdf changed status:** None -> Ready For Test

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-06**

**wedge009 wrote:**

> Hovering over the icons at the top of the game screen shows some tool-tips, eg gold, villages, units, etc. I haven't looked at this for a while, but I think the complaint relates to the coloured flag on the top-left.
> 
> 
> 
> Hovering over it in 1.12 produces a team name tool-tip, which is not translated. Current 1.13 doesn't appear to show anything... which isn't necessarily a bad thing. I don't know the specifics of those changes to save_index/current_player.

**Comment by Wedge009** [comment]
Still not sure what's going on in this one. At time of writing, SP and MP seem to use leader name (which may be save ID, I don't know). Interestingly, the tool-tip still shows as Konrad when picking Li'sar in the Tutorial.

**Comment by gfgtdf** [comment]
so is this fixed then?

**Comment by CelticMinstrel** [comment]
I don't know. The commit addresses the comment from @Wedge009 above, and the preceding commit _may_ address the issue itself, but I'm not sure. Someone needs to test in a language other than English.

**Comment by CelticMinstrel** [comment]
Oh, it's also possible that the actual issue here was fixed much earlier, for example when the `side_name` attribute was introduced.

**Comment by Wedge009** [comment]
Thanks for that. Prince is Prince for both French and English, so I never saw a difference.

Using German, I confirm hovering over the flag shows Prince Haldric for 1.12 branch and Prinz Haldric for master. On this basis I think we can close this.
