### ISSUE TITLE
[if] tag has 2 different syntaxes (GNA #14670)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1176]
**[Original submission](https://gna.org/bugs/index.php?14670)** by fendrin on 2009-11-02

The if wml tag has currently 2 totally different syntaxes depending on the context which can be animation or action wml.

animation wml syntax:

http://wiki.wesnoth.org/AnimationWML

action wml syntax:

http://wiki.wesnoth.org/ConditionalActionsWML#.5Bif.5D

I suggest to rename one of the different uses or to unify the syntax somehow.

(Reproduced on All)
Release: 1.9
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**shadowmaster changed status:** Postponed -> None

**Comment by Pentarctagon** [comment]
Closing since, while I suppose it's potentially confusing, I don't think it's so confusing that it's worth breaking a bunch of currently working code.

**Comment by CelticMinstrel** [comment]
I think it's worth leaving this open. It's _extremely_ low priority, but it would be nice to address it some day.
