### ISSUE TITLE
Localized Lobby for Different Languages (GNA #14755)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1178]
**[Original submission](https://gna.org/bugs/index.php?14755)** by aethaeryn on 2009-11-13

Basically, instead of just joining Lobby on connect, a user should also join a room that is based on the language they're using for Wesnoth. For instance, if they're using German, they would automatically join a room called "de" or "Lobby-de" when they joined the MP server. This would allow them to see who is using their language and make it easier for them to form games.

(Reproduced on Fedora 11)
Release: 1.7.8
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-11-14**

**soliton wrote:**

> Instead of a default join of dubious value it'd be better to have a user configurable list of rooms to autojoin.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-05**

**ivanovic changed item group:** Multiplayer -> Multiplayer Lobby

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-03**

**shadowmaster wrote:**

> Deassigning bugs from inactive developers.

**Comment by Pentarctagon** [comment]
Closing since rooms no longer exist.
