### ISSUE TITLE
UtBS: add female variation for Desert Fighter and Desert Scout Lines (GNA #14924)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1181]
**[Original submission](https://gna.org/bugs/index.php?14924)** by fkhodkov on 2009-12-11

Quenoth Elves have fighters and scouts (and their advanced companions) of both genders; for example, in the first scenario (The Morning After) we have female fighter Lrea and female scout Nisa.

But there aren't any female variations (i. e. no strings and no sprites) for that unit types.  In Russian, male and female unit names should be translated differently; in some other languages too.  It would be nice either to add female variations for those units (Fighter, Hero, Champion, Captain, Marshal, Scout, Horseman, Rider and Outrider), or to make them male-only, like "regular" elves.

(Reproduced on All)
Release: 1.8
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-12-15**

**esr changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-09-18**

**espreon wrote:**

> This will be handled as part of the desert elf redesign.
> 
> 
> 
> There will be a female version for the scouts, but not one for the melee units.

**Comment by nemaara** [comment]
This is out of date, since the quenoth remake occurred and female fighters/scouts were changed to male ones.
