### ISSUE TITLE
Battle for Wesnoth: OST (GNA #14962)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1182]
**[Original submission](https://gna.org/bugs/index.php?14962)** by antro on 2009-12-17

Why not? Why don't add and .m3u file with a list of all the music in a suitable "musiclist" format? Here attached my BfW.m3u, for example...

It must be placed in the main directory, and maybe could be nice to add a link in the menu creation, something like "Play BfW OST", or an icon on the Linux desktop... whatever...

In this way you can listen BfW OST in your favorite Player...

The .ogg are quite detailed and in my foobar 0.9.6.8 the plain list attached is quite nicely displayed....

Ciao

Antonio

(Reproduced on all)
Release: 1.7.10
Priority: 1 - Later
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2009-12-17**

**antro added attachment:** [BfW.m3u](http://gna.org/bugs/download.php?file_id=7518)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-03**

**shadowmaster changed priority:** 5 - Normal -> 1 - Later

**Comment by Wedge009** [comment]
I do this myself, for my own listening. But I don't see what extra functionality this adds to the game itself. Also the question of what would be a suitable 'official' order.

**Comment by Wedge009** [comment]
@Pentarctagon I'm inclined to close this one as it doesn't add any value to the game. Haven't seen anyone else's thoughts on this, though.

**Comment by Pentarctagon** [comment]
I'm not especially clear on the benefit in general to be honest - I assume it'd work just as well to go into the music directory and play the music files?

**Comment by Wedge009** [comment]
Same here - it sounds more like just a wish to make the music files 'officially' available somehow. Presented nicely or whatever.

**Comment by CelticMinstrel** [comment]
The only thing this adds is giving a "recommended" playing order. Whether that's an advantage or something worthwhile, I have no idea.

(Album art might be nice too, though.)

**Comment by Wedge009** [comment]
Yeah, and how to even establish that order was one of the early questions I had. And unless we take existing assets - such as the Eldaric vs Troll picture used as the background in the Steam library page, for example - album art would require artistic effort too.

**Comment by cooljeanius** [comment]
There are plenty of tools out there to convert ogg to mp3; I used one of them (Audacity or VLC or Tunesify; I forget which) to import the Wesnoth soundtrack to my iTunes library. I remember a lot of the metadata being missing from the imported songs, though, so it would be useful to make sure all the metadata fields on the files are filled out properly. For album art I just used the Wesnoth logo (the shield with 2 crossed swords behind it). The order the songs got put in for the album was just alphabetical order, so yeah some track numbers would be useful. Also Mattias Westlund sells an album of his contributions to Wesnoth music on the iTunes store that people can purchase if they'd like to support him; it comes with album art and metadata: https://music.apple.com/us/album/the-wesnoth-years/1494704618 (It's mostly the same as the soundtrack that's shipped with the game; I'm attaching a screenshot of my review of differences between the two)
<img width="735" alt="Screen Shot 2021-09-13 at 20 51 18" src="https://user-images.githubusercontent.com/1388660/133176087-4934be38-c2a0-45a4-b345-3e6d909e2a06.png">

**Comment by Wedge009** [comment]
I don't think the request is about format conversion - personally I wouldn't want to perform a lossy conversion anyway. It's the value of doing this for the game project itself - and I don't see any. I think those who like to listen to Wesnoth music, including myself, can just make similar arrangements as you describe for their own music collections.

However, if (only now) people want to express interest in this and do something about it, by all means re-open, but only if you're going to work on it.

**Comment by CelticMinstrel** [comment]
> And unless we take existing assets - such as the Eldaric vs Troll picture used as the background in the Steam library page, for example - album art would require artistic effort too.

Absolutely, if we _were_ to do this, the album art would probably have to be something entirely new.

> There are plenty of tools out there to convert ogg to mp3

It's pretty easy to convert them with ffmpeg or one of its many GUI wrappers. I wouldn't choose mp3 as the target format though.

> (It's mostly the same as the soundtrack that's shipped with the game; I'm attaching a screenshot of my review of differences between the two)

I'm kind of curious about these two tracks that apparently aren't actually in the game… does anyone know anything about them? Were they ever in the game?

---

In any case, I think a Wesnoth OST would be best as an _entirely separate_ download from the main game, simply because you can't release it in ogg format (because Apple hates ogg) and it's silly to include two copies of every track just so that people can have a playlist. Plus, some tracks might need to be edited a little to work in a playlist format. (That would be true of most games, at least; I'm not sure if it's true of Wesnoth specifically.)

**Comment by Wedge009** [comment]
See, that's where things quickly become complicated. My impression from the original request was that such an OST project would just use assets as provided in the game itself. Akin to a 'game rip' perhaps. Re-using the source oggs is fine - most media players on PC would or should handle this.

On the other hand, if we're talking about making this a full-blown publication, I don't think we - as software developers - should necessarily be the ones to do this. It sounds to me like the artists who have contributed to Wesnoth could get together to collate - and if they felt it necessary - re-arrange their pieces and publish their works with at least some common lossless options like FLAC, and ALAC for Mac users, (personally I prefer Wavpack, but that doesn't appear to be very common and transcoding between lossless formats is, well, lossless anyway). This way they could even charge a modest sum for such a publication (or if they're feeling generous, make it a voluntary contribution as I've seen some artists do), and be appropriately compensated for their efforts.

(On the topic of tracks in a play-list, I think they work fine as-is - Wesnoth music doesn't have per-track looping as many games do.)

**Comment by cooljeanius** [comment]
> > (It's mostly the same as the soundtrack that's shipped with the game; I'm attaching a screenshot of my review of differences between the two)
> 
> I'm kind of curious about these two tracks that apparently aren't actually in the game… does anyone know anything about them? Were they ever in the game?
> 

"Ambuscade" at least is used in a lot of UMC; it's in "Akladian Music" (used by ANO), "IftU Music", and "UMC Music Book 07"; I don't know about "Victory's Price" though...

> (because Apple hates ogg)

Speaking of which I'd really appreciate it if someone could help me get the qlvorbis QuickLook plugin working: https://github.com/clemmece/qlvorbis/issues/4
