### ISSUE TITLE
Units can talk in their own die events (GNA #15113)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1183]
**[Original submission](https://gna.org/bugs/index.php?15113)** by beetlenaut on 2010-01-12

A die event fires after the unit's death animation plays, and the unit disappears. However, in the following code, the unit that triggered the event can be the one who talks. Also, the ghost won't appear in the right place:

```

[event]

    name=die



    [filter]

        side=2

    [/filter]



    [message]

        side=2

        message= _ "You killed one of us!"

    [/message]



    [unit]

        type=Ghost

        x=$unit.x

        y=$unit.y

    [/unit]

[/event]

```

As a workaround, you can add a [kill] tag to the die event:

```

[kill]

    id=$unit.id

[/kill]

```

But that isn't obvious, and if it's necessary, it should happen internally.

(Reproduced on Linux)
Release: 1.7.11
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-14**

**ai0867 changed status:** None -> Confirmed

**ai0867 wrote:**

> A unit isn't erased yet at that point because the die event can be used to revive the unit.
> 
> This can also be done from the last breath event however and probably only exists for backwards compatibility reasons.
> 
> 
> 
> I'm not sure if it's a good idea to change it this late in 1.7 though.

**ai0867 changed priority:** 5 - Normal -> 3 - Low

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-14**

**ai0867 changed status:** Confirmed -> Postponed

**ai0867 wrote:**

> My previous guess was incorrect. The current method of firing events requires that the unit still exists in order for it to be filtered on.
> 
> 
> 
> I'll see if this can be changed, but this will almost certainly have to wait for 1.9, so I'm marking this bug postponed for now.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-15**

**beetlenaut wrote:**

> It sounds like this may be more trouble than its worth to change. Since the behavior seems counterintuitive, I added a note to the wiki.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-16**

**esr wrote:**

> ai0867, you can go ahead and fix this before 1.8 without worrying about compatibility.  wmllint has a test for units speaking in their die events and I have already used it to verify that mainline no longer has any of these cases in it.  (I fixed several myself.)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-17**

**silene wrote:**

> The filtering part can't be changed easily. However, the fact that unit cannot be created in the proper location may be a bug introduced by Crab_ when he rewrote the way units are created for 1.7.11.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-19**

**crab wrote:**

> yes, silene is right, 'the fact that unit cannot be created in the proper location' is a consequence of my change. but, IMO, it's not a bug, it's a feature - a consequence of the fact that the original unit is still not dead ('A unit isn't erased yet') at this time, so it's square is occupied, so the ghost is spawned at nearest free square.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-20**

**silene changed status:** Postponed -> None

**silene changed severity:** 3 - Normal -> 5 - Blocker

**silene wrote:**

> No, it isn't a feature, it's a bug; you are changing the behavior of a WML tag very late in the development cycle. And it isn't just an obscure behavior: designers do use the [unit] tag to overwrite units in events without killing them first (and nothing in the documentation says they shouldn't). Please revert this part of your patch.

**silene changed priority:** 3 - Low -> 5 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-20**

**crab wrote:**

> Making sure that [unit] spawns only on vacant hexes fully prevents 'accidential' overwrites such as https://gna.org/bugs/index.php?14384  , which are annoying bugs and are far more harder to spot than mis-placings and duplications. I would prefer [unit] to work this way, requiring explicit authorization before replacing the unit with another. 
> 
> 
> 
> However, I agree with 'you are changing the behavior of a WML tag very late in the development cycle.' part and, therefore, propose  'I revert that part now, document, and reapply in 1.9' solution.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-25**

**crab wrote:**

> Got some negative feedack on aforementioned kind of solution on forum [ http://forums.wesnoth.org/viewtopic.php?f#21&t28616 ], and asked zookeeper about "what should be the default behavior of [unit]x,y=1,1[/unit] when 1,1 is occupied by other unit"
> 
>  
> 
> --
> 
> (11:31:43 PM) zookeeper: Crab_, i'd say the default should be not overwrite but to put on nearest vacant
> 
> (11:32:15 PM) zookeeper: that's the "safe" default...if someone wants to potentially erase existing units then they ought to specify it
> 
> --

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-25**

**crab wrote:**

> also,
> 
> --
> 
> shadowmaster: and, what do you think about "what should be the default behavior of [unit]x,y=1,1[/unit] when 1,1 is occupied by other unit" ? should it, by default, overwrite or find nearby vacant tile ? ( https://gna.org/bugs/?15113 ). 
> 
> (11:51:09 PM) shadowmaster: find nearby vacant tile
> 
> (11:51:17 PM) Crab_: ok, thanks
> 
> (11:51:52 PM) shadowmaster: that has been the behavior since as far as I can recall (1.0)
> 
> ...
> 
> (11:58:10 PM) shadowmaster: Crab_: confirmed that "find nearby vacant tile" was the normal behavior in 1.0 already with a [event]name=start in the test scenario spawning an Orcish Warrior and an Elvish Shaman at 10,10
> 
> (11:58:38 PM) shadowmaster: the shaman was spawned second and at 10,9
> 
> (01/26/2010 12:00:04 AM) shadowmaster: same behavior in 1.6's test scenario with the same sequence but in a prestart event

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-01-28**

**crab changed status:** None -> Postponed

**crab changed severity:** 5 - Blocker -> 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**shadowmaster changed status:** Postponed -> None

**Comment by Pentarctagon** [comment]
Closing given the age, and that there are already ways to accomplish the original issues (add a filter for the dead unit's location in the [message] and use `overwrite=yes` when placing the unit).
