### ISSUE TITLE
Hotkeys should ignore caps-lock (GNA #15486)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1190]
**[Original submission](https://gna.org/bugs/index.php?15486)** by teaser on 2010-02-25

For as long as I can remember the hotkeys in wesnoth are inconsistent with how I expect them to work.

That is: the systems reads for the character typed and not the keys pressed. Afaik this only affects the user if it has the caps-lock (or equivalent) set.

If I press the 'm' key I expect the chat-box to show regardless if I typed 'm' or 'M'.

/tsr

(Reproduced on G/L Ubu9.10)
Release: 1.7.13
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-02-27**

**soliton wrote:**

> If you propose replacements for all the shortcuts you break with this change (for example n # next unit and N  previous unit) we could think about it...

**soliton changed category:** Bug -> Feature Request

**soliton changed severity:** 2 - Minor -> 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-02-27**

**teaser wrote:**

> Well, reading how the hotkeys are defined I don't think it breaks anything if you map commands to actually pressed keys.
> 
> 
> 
> That is:
> 
> pressing 'n' (regardless if it would write 'n' or 'N') results in 'cycle'
> 
> pressing 'shift'+'n' (regardless if it would write 'N' or 'n') results in 'cycleback'
> 
> 
> 
> So if the hotkey-reader reads the keys pressed and not the resulting character it will work.
> 
> 
> 
> Ofc, I have no idea how it is implemented but I think this proposal makes it more consistent with how it works in user-OS'es.
> 
> 
> 
> /tsr

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-01**

**mordante wrote:**

> I agree that it should work as stated in comment #2.
> 
> I want to implement that once I get around it for gui2,
> 
> I'll leave it unassigned in case somebody wants to fix
> 
> it in gui1 before I get around it.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-02**

**soliton wrote:**

> Well, then we'd be back to impossible shortcuts for certain keyboard layouts like the infamous shift + ; (to get ':')...

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-07**

**mordante wrote:**

> Good point, maybe only do the case insensitive evaluation for normal letter [a-z] and not for other keys.

**Comment by grz0** [comment]
this issue is fixed in 1.13.X
