### ISSUE TITLE
error messages about PANGO on Mac console (GNA #15625)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1193]
**[Original submission](https://gna.org/bugs/index.php?15625)** by wesnoth_user on 2010-03-14

I am getting a lot of error messages like the following on my console while playing Battle for Wesnoth 1.7.14 - 1.8-beta7. I don't know what they mean or if they are important. There are dozens of them, all saying the same thing.

The game itself (HttT, The Siege of Elensefar, on Hard) seems fine with no noticeable problems.

3/14/10 10:08:00 PM [0x0-0x42042].org.wesnoth.Wesnoth[754] (process:754): Pango-CRITICAL **: _pango_engine_shape_covers: assertion `PANGO_IS_FONT (font)' failed 

3/14/10 10:08:00 PM [0x0-0x42042].org.wesnoth.Wesnoth[754] (process:754): Pango-CRITICAL **: _pango_engine_shape_covers: assertion `PANGO_IS_FONT (font)' failed 

3/14/10 10:08:00 PM [0x0-0x42042].org.wesnoth.Wesnoth[754] (process:754): Pango-CRITICAL **: _pango_engine_shape_covers: assertion `PANGO_IS_FONT (font)' failed 

3/14/10 10:08:00 PM [0x0-0x42042].org.wesnoth.Wesnoth[754] (process:754): Pango-CRITICAL **: _pango_engine_shape_covers: assertion `PANGO_IS_FONT (font)' failed

(Reproduced on Mac 10.5.8)
Release: 1.7.14
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-17**

**esr changed item group:**  -> None of the others

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-20**

**mordante wrote:**

> Does it give any problems while running Wesnoth or only these messages?
> 
> 
> 
> Where in the game do they occur and how to reproduce?
> 
> 
> 
> I assume it's a Mac specific problem since I haven't seen them ever (on Debian).

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-22**

**wesnoth_user wrote:**

> It seems to have no effect on the game at all, there were no problems.  
> 
> 
> 
> It occurred sometime during the Siege of Elensefar.  
> 
> 
> 
> I will install the new version (RC1) and try to figure out exactly when it occurs and reproduce the error. Unfortunately I didn't notice the error before I finished the scenario so all the automatic save-games were erased.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-24**

**ancestral wrote:**

> I get these same errors; I think crimson_penguin could elaborate further. I think it�s an issue with Pango, Cairo, or something related.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-28**

**wesnoth_user added attachment:** [4p_-_Loris_River_Turn_12.gz](http://gna.org/bugs/download.php?file_id=8726)

**wesnoth_user wrote:**

> I just tired RC1 and a multiplayer game and I get the same errors. 
> 
> 
> 
> 3/28/10 9:16:01 PM [0x0-0x3a03a].org.wesnoth.Wesnoth[754] (process:754): Pango-CRITICAL **: _pango_engine_shape_covers: assertion `PANGO_IS_FONT (font)' failed 
> 
> 
> 
> the same message was generated 4000 times in the course of a one hour game. I will attach a save game but I think any scenario would do it.
> 
> (file #8726)

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-09-07**

**alarantalara wrote:**

> The version of Pango currently used by the Mac OS X package appears to be 14 releases older than the current requirements. This may have something to do with the error messages.

**Comment by Vultraz** [comment]
10.5 is no longer supported, our current macOS people haven't seen such messages, and as alarantalara wrote (on GNA) it was likely an old packages thing.
