### ISSUE TITLE
retain lobby message history during games (GNA #15650)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1194]
**[Original submission](https://gna.org/bugs/index.php?15650)** by mystic_x on 2010-03-18

mp lobby room chat log, and all whisper room logs get erased whenever the user leaves the main lobby (so enters a game as observer/player, a game lobby or create game dialog).

(Reproduced on any)
Release: 1.7.15
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-25**

**ilor changed priority:** 5 - Normal -> 3 - Low

**ilor wrote:**

> While this is a regression from the old lobby, the "old" behavior wasn't perfect anyway so this will probably wait till the more major lobby issues are sorted out.

**ilor changed status:** None -> Postponed

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-05**

**ivanovic changed item group:** User Interface -> Multiplayer Lobby

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-08**

**ilor changed severity:** 3 - Normal -> 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**shadowmaster changed status:** Postponed -> None

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-03**

**shadowmaster wrote:**

> Deassigning bugs from inactive developers.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-19**

**laundry wrote:**

> I will work on this. Hopefully I can fix it.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-19**

**laundry wrote:**

> As I understand the "bug" is that when you leave the multiplayer lobby by :Entering a game, create a game, or going back to the title screen the lobby chat becomes erased. I do not think this is a bug because this is supposed to be how it works. 
> 
> 
> 
>     As you can see in the pictures I attached I said "Hi I am Austin DeLauney". I then quit and go to the title screen, then re-enter the multiplayer lobby and my chat is gone. I believe that is how it is supposed to work for the main lobby.
> 
> 
> 
> The Whisper chats are getting erased from transitions, which shouldn't happen (As those are private and should be kept) I still haven't investigated Whisper chats but to my understanding that is what they're supposed to do.
> 
> (file #21095, file #21096)

**laundry added attachment:** [Multiplayer Lobby Chat.png](http://gna.org/bugs/download.php?file_id=21095)

**laundry added attachment:** [Multiplayer Lobby Chat after.png](http://gna.org/bugs/download.php?file_id=21096)

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-19**

**laundry wrote:**

> *NOTE* This is not a bug, this is just how the chat works. It looks like if we want to fix this we'd have to revamp the whole chat system *NOTE*

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-20**

**soliton changed OS:** . -> any

**soliton changed category:** Bug -> Feature Request

**soliton changed title:** lobby messages keep getting deleted -> retain lobby message history during games

**Comment by ProditorMagnus** [comment]
Works for 1.12, broken for 1.13.

**Comment by jyrkive** [comment]
Implemented in commit 8a0027691363c05fa06657f8c4e466054a530fda.
