### ISSUE TITLE
/emote or /me command doesn't work properly. (GNA #15651)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1195]
**[Original submission](https://gna.org/bugs/index.php?15651)** by spookymagician on 2010-03-19

I attempted to use the /emote and /me command in the lobby but it does not print out correctly. if you use /emote it shows:

/me <message>

same thing for /me too... this should be fixed...

(Reproduced on Windows)
Release: 1.7.15
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-25**

**ilor changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-01**

**ancestral wrote:**

> If you create a game, in the creation screen it�s working. However in the lobby it isn�t.
> 
> 
> 
> My guess is these are different widgets they�re using?
> 
> 
> 
> Using 1.8.0 and Mac OS X 10.6.3
> 
> (file #8771)

**ancestral added attachment:** [Screen shot 2010-04-01 at 4.56.21 PM.png](http://gna.org/bugs/download.php?file_id=8771)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-05**

**ivanovic changed item group:** Multiplayer -> Multiplayer Lobby

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-29**

**spookymagician wrote:**

> Does this still not work for 1.9? I forgot to test this. Although, I cannot because it seems that the server is down at the moment. Whenever someone has a chance, please test this. (make sure it's in the new lobby and not within making a game.)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-29**

**spookymagician added attachment:** [emote_w_184_fail.png](http://gna.org/bugs/download.php?file_id=10083)

**spookymagician wrote:**

> hm, I did a quick test in 1.8.4 (with using that version of the new lobby and it didn't work still.)
> 
> 
> 
> It seems I didn't upload a image... Let me go ahead and show you just so you see what I see...
> 
> (file #10083)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-03**

**shadowmaster wrote:**

> Deassigning bugs from inactive developers.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-04**

**ancestral wrote:**

> Issue appears resolved, likely with change to the new lobby.
> 
> 
> 
> Verified working in 1.10.3 on Mac OS X. If someone wants to test in Windows maybe we can close this bug.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-04**

**shadowmaster wrote:**

> You mean it's solved by switching to the old (pre-1.8) lobby, or by switching to the new (broken and non-default) lobby?

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-04**

**ancestral wrote:**

> Bah. My mistake.
> 
> 
> 
> Works on the old lobby, not the new one. So the issue is still there.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-08-08**

**wedge009 wrote:**

> Not sure what is old or new, but using Multiplayer option and then typing /emote [message] or /me [message] in the chat window results in: <[username] [message]>
> 
> 
> 
> This is correct isn't it? I'm using 1.13.1+dev on Windows. If this is correct, we can close this.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-07**

**wedge009 wrote:**

> Confirmed this is in the 'experimental lobby', presumably part of an attempt to move to the GUI2 model.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-29**

**wedge009 wrote:**

> /me is rendered correctly in the 'old' lobby regardless of what interface the sender is using. /me is rendered as-is in the 'experimental' lobby, again, regardless of what interface the sender is using.

**Comment by Wedge009** [comment]
@Vultraz This work-around seems to do the job for now.

**Comment by GregoryLundberg** [comment]
Discussion on Discord asked about emote being used to mimic server messages or other users.

Indeed, back in the day, this was a huge problem.

The solution was simple: make it obvious it was an emote.  Discord, for example, shows the user's handle, as normal, and the emote text, in italic font, on the next line.

It's been ages, but IIRC, we fixed it in Amylaar by putting a > before the emote. `/me smiles` --> `> Tad Carlucci smiles`. Many site administrators tried disallowing certain critical names. While that usually worked for `/me` (although when it came to player names it was often a game of Whack-A-Mole) it didn't help with `/emote Server will shut down in 5 minutes.` --> `Server will shut down in 5 minutes.` Still, even with the leading > we would have problems with new players panicking.
