### ISSUE TITLE
Rapid screen movement during AI turns (GNA #15718)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1198]
**[Original submission](https://gna.org/bugs/index.php?15718)** by cathyr19355 on 2010-03-27

I'm playing "Legend of Wesmere" on "hard" difficulty.  During  combat on the AI's turns, the screen jerks rapidly either up and down or side to side, as though it is attempting to follow rapid unit movements for units the player can't see.  The result is to make the screen unviewable--it's bad enough almost to induce motion sickness.  I've attached some saves where you can see this happening.

(Reproduced on Ubuntu)
Release: 1.7.13 (41392)
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-27**

**cathyr19355 added attachment:** [LOW-Human_Alliance_Turn_7.gz](http://gna.org/bugs/download.php?file_id=8697)

**cathyr19355 added attachment:** [LOW-The_Elvish_Treasury_Turn_7a.gz](http://gna.org/bugs/download.php?file_id=8696)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-28**

**esr changed status:** None -> Confirmed

**esr wrote:**

> Confirmed, I've seen this repeatedly on Cathy's display.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-28**

**esr wrote:**

> We have this characterized no.  To invoke it, the track unit scrolling option must be on, the skip ai moves option must be on, and scroll speed must be set high.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-03-28**

**boucman changed category:** Bug -> Feature Request

**boucman wrote:**

> ok, after some analysis, this is a problem of using a too fast scrolling speed
> 
> 
> 
> above a certain speed scrolling should warp instead of scroll
> 
> 
> 
> assigning to fendrin

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-25**

**fendrin changed status:** Confirmed -> Postponed

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**shadowmaster changed status:** Postponed -> None

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-27**

**fendrin changed status:** None -> Confirmed

**fendrin changed priority:** 5 - Normal -> 3 - Low

**fendrin changed severity:** 3 - Normal -> 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-05-07**

**fendrin changed status:** Confirmed -> Postponed

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-07-23**

**gfgtdf changed status:** Postponed -> None

**Comment by Wedge009** [comment]
Couldn't load such an old game in 1.14.7. Anyone know if this is still happening? I don't recall anything matching what's being described here...

**Comment by Wedge009** [comment]
Skipping AI moves doesn't scroll. Also I can't find any track unit scrolling option (only in older version?). I think this may no longer be required - please re-open if you think otherwise.

**Comment by soliton-** [comment]
I think they might mean "Follow unit actions" under advanced preferences.

Yep, there it is https://github.com/wesnoth/wesnoth/commit/bc82c3b

**Comment by Wedge009** [comment]
Okay, Follow unit actions is enabled by default, so that doesn't make a difference to my earlier testing. Skipping AI moves still cancels the unit tracking/following. Unless someone else confirms this is still issue I think we can leave it closed.

Thanks for the info.
