### ISSUE TITLE
remove drop boxes for player list in mp lobby (GNA #15770)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1200]
**[Original submission](https://gna.org/bugs/index.php?15770)** by jbx on 2010-04-02

There are currently 3 drop boxes for the player list in the 1.8 mp lobby.  (Selected Game, Lobby, Other Games)

The drop boxes are not needed.  They add extra clicks for the user, and make finding players more difficult.  

The previous color coded system and sorting behavior from 1.6 was much smoother.

(Reproduced on vista)
Release: 1.8
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-05**

**ivanovic changed item group:** Multiplayer -> Multiplayer Lobby

**Comment by ProditorMagnus** [comment]
I think this issue is relevant for 1.13 again.

**Comment by Vultraz** [comment]
Closing this since their presentation has been improved. Other Rooms is no longer shown, Other Games has been relegated to last place and starts collapsed, and Selected Game and Lobby start off expanded.
