### ISSUE TITLE
See the damage of the enemy if he attack you (GNA #15784)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1202]
**[Original submission](https://gna.org/bugs/index.php?15784)** by el_caballero on 2010-04-04

I think that it need a way to calculate the damage that the enemy can do to yours units if he attack them. Now, i only can see the damage if i attack. I think that it function will help so much to the tactics to play.

I think that it can so similar to the function to calculate the damage of your attack (The windows), but... it can be with another color, else the player can confuse.

I propose to see the enemy damage if he attack you, to click over the enemy unit and after click over your unit. There will appear a windows with the table damage calculations.

(Reproduced on Linux &amp; Windows)
Release: 1.8
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Wedge009** [comment]
Very similar to #1252. Closing this one if only because the later issue has a bit more detail and is also linked to #3956.
