### ISSUE TITLE
Meta tags for maps (GNA #15803)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1203]
**[Original submission](https://gna.org/bugs/index.php?15803)** by ancestral on 2010-04-06

Maps in Wesnoth have no information, such as author, title, description, and version in them like scenarios have. These could be particularly useful and also give credit where it's due.

I suggest one of the three:

* Add more meta tags to the map file format

* Use a small amount of WML in the file for this information

* Simply put comments in the map with this information

Although map add-ons can already have this from the .pbl file I'm mostly referring to maps distributed in the game, and certainly with add-ons that feature many maps it might be nice to even make some of this information available when a user chooses a map to play with.

http://www.wesnoth.org/forum/viewtopic.php?f#15&t29465

(Reproduced on Any)
Release: Any
Priority: 1 - Later
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-03-26**

**anonymissimus wrote:**

> TBH, this feature request doesn't make much sense to me. There is no "map file", every map doesn't work without a scenario and gets just embedded into it. Thus there is the spot where such info can be put.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-03-26**

**anonymissimus wrote:**

> In my previous post I'm actually responding to http://forums.wesnoth.org/viewtopic.php?f#10&t36323&p=524716#p524716
> 
> Didn't quite realize the two have probably different meaning.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-03-26**

**ancestral wrote:**

> I�m not sure what doesn�t make sense here. There are map files, and they do work with and without scenarios. Meta tags could be very useful for displaying a variety of different information, including:
> 
> 
> 
> * Type (Campaign, Singleplayer, Multiplayer, MP Survival, MP Conquest, etc.)
> 
> * Number of players
> 
> * Author
> 
> * Date
> 
> * Version
> 
> * Description
> 
> 
> 
> This information would show up during the create game dialog.
> 
> 
> 
> This would be extremely handy not only to give credit where its due (people make our maps just like they make our artwork!) but also with potentially organizing maps down the road (imagine being able to create a game and by filtering only skirmish maps, or multiplayer maps for 4 players or more). Really this isn�t a whole lot different than metadata for add-ons.
> 
> 
> 
> In some cases the metadata will be the same as the add-on, but in others, especially where multiplayer add-ons have multiple maps you�re going to have different info.
> 
> 
> 
> This is currently an active post over at the forums that fabi (Fendrin?) has also been spilling ideas into, though its probably beyond the scope of the intention of this FR: http://r.wesnoth.org/t36323

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-27**

**fendrin changed priority:** 5 - Normal -> 1 - Later

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-12-06**

**fendrin changed status:** None -> Postponed

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-07-23**

**gfgtdf wrote:**

> iirc we just removed the border_size#<int> and typemark/map metadata from maps, since it was considered useless, so i doubt this will be implemented.
> 
> 
> 
> In any case, removign postponed status

**gfgtdf changed status:** Postponed -> None

**Comment by Pentarctagon** [comment]
Closing for the above comment, and also this seems duplicative for a user creating an add-on with the described information provided in the _server.pbl if they are bothered about it.

**Comment by CelticMinstrel** [comment]
Although the border_size and type parameters were removed as gfgtdf says, I'm pretty sure the embedded WML header in the map format is still there – it's just empty in most maps. So if someone _wanted_ to add random metadata to their maps, they could just do it (though obviously Wesnoth would ignore it currently).
