### ISSUE TITLE
persistent memory of lobby tab state (GNA #15826)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1204]
**[Original submission](https://gna.org/bugs/index.php?15826)** by wintermute on 2010-04-08

lobby tabs in 1.8.0 currently reset to default behavior after joining/leaving a game or logging on/off.

Ideal behavior would be for the tabs to remember the last settings, so that players who prefer to see all players (selected games, lobby, and other games), for example, can do so without having to reset the tabs each time they return to the lobby from a game.

(Reproduced on all)
Release: 1.8.0
Priority: 3 - Low
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-03**

**shadowmaster wrote:**

> Deassigning bugs from inactive developers.

**Comment by gfgtdf** [comment]
> 20180505 20:11:35< Ravana_> I think https://github.com/wesnoth/wesnoth/issues/1204 is implemented and can be closed
