### ISSUE TITLE
Flag modified MP scenarios [was: MP cheat, units and gold added to player, no OOS] (GNA #15883)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1205]
**[Original submission](https://gna.org/bugs/index.php?15883)** by neofutur on 2010-04-14

hi all,

 i was playing a multiplayer game on the official MP server

 After seeing a unit appearing from nowhere I checked the replay and could confirm there is a MP cheat, allowing my opponent to add 2 lancers and gold to his side

 see the cheated replay at http://xena.ww7.be/4p_-_Isar_s_Cross_repeticion.gz

        [event]

                name="turn 10"

                [unit]

                        ai_special="guardian"

                        generate_name="yes"

                        random_traits="no"

                        role="guardian"

                        side="1"

                        type="Lancer"

                        x="12"

                        y="22"

                [/unit]

                [unit]

                        ai_special="guardian"

                        generate_name="yes"

                        random_traits="no"

                        role="guardian"

                        side="1"

                        type="Lancer"

                        x="11"

                        y="21"

                [/unit]

and many 

        [event]

                name="turn 10"

                [gold]

                        amount="20"

                        side="1"

                [/gold]

        [/event]

        [event]

                name="turn 14"

                [gold]

                        amount="20"

                        side="1"

                [/gold]

        [/event]

 my opponent also said :

                [speak]

                        id="DarkKnight"

                        message="he is right. there are 2 lancer appera outside of the castle"

                        side="1"

                [/speak]

 probably it was not him who cheated, but the game creator ( side 1 )

(Reproduced on linux)
Release: 1.6
Priority: 5 - Normal
Severity: 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-14**

**neofutur added attachment:** [4p_-_Isar_s_Cross_repeticion.gz](http://gna.org/bugs/download.php?file_id=8975)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-15**

**silene wrote:**

> Yes, it is due to the game creator. You are not getting any OOS because the modifications to the scenario were there right from the start, so your clients knew that, on certain turns, gold would be added and units would appear. Since the modifications were not added on the fly, this is not a MP cheat.
> 
> 
> 
> Ideally, there should have been a notification at scenario start indicating that the WML was not identical to the one stored locally, so that the scenario behavior would be less of a surprise. Changing to a feature request.

**silene changed title:** MP cheat, units and gold added to player, no OOS -> Flag modified MP scenarios [was: MP cheat, units and gold added to player, no OOS]

**silene changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-22**

**soliton wrote:**

> At least in the old lobby it says "Remote Scenario" in the game description if the WML doesn't match our own (or we don't have it at all).

**Comment by Pentarctagon** [comment]
Closing since games are flagged when they have been locally modified, but generally speaking Wesnoth doesn't have the ability to determine whether something is a cheat or not.

**Comment by CelticMinstrel** [comment]
Although I believe it _can_ recognize the built-in debug cheats since they're included in the replay.

**Comment by Pentarctagon** [comment]
That isn't what's being referenced as a cheat here though.

**Comment by CelticMinstrel** [comment]
Fair enough.
