### ISSUE TITLE
(new) MP Lobby - Text no longer selectable. (GNA #15894)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1206]
**[Original submission](https://gna.org/bugs/index.php?15894)** by grickit on 2010-04-17

You can no longer select text in the lobby. This would be needed for copying and pasting.

I realize there are lobby logs for this, but they don't cover rooms and whispers. Also the feature was available in the old lobby.

(Reproduced on All)
Release: 1.8
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-24**

**anonymissimus changed title:** MP Lobby - Text no longer selectable. -> (new) MP Lobby - Text no longer selectable.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-08-08**

**wedge009 wrote:**

> I can select and copy text from the chat window as of 1.13.1+dev. Does this mean this can be closed?

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-07**

**wedge009 wrote:**

> Found the 'new lobby' as 'experimental lobby', appears to be incomplete transition to GUI2, so confirmed: cannot select text in the chat box.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-07**

**wedge009 changed status:** None -> Confirmed

**wedge009 wrote:**

> Noting it is still yet to be resolved in 1.13.6+dev.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-20**

**wedge009 wrote:**

> Redesigned MP lobby in 1.13.7+dev carries this over.

**wedge009 changed OS:** Windows -> All

**Comment by ProditorMagnus** [comment]
Still broken with 1.13.11.

**Comment by Wedge009** [comment]
1.14.7

**Comment by Wedge009** [comment]
Seems to be present still for master (1.17.0+dev) and 1.16 branch.

**Comment by Wedge009** [comment]
1.18.0 release

**Comment by CelticMinstrel** [comment]
This is easily done ever since @babaissarkar made a proper multiline textbox.

**Comment by babaissarkar** [comment]
Needs some details, does it really need to be multiline or a copy-able single line textbox will do?

Screenshot from 1.6 shows that it was single line, but copy-able.
![Screenshot from 2024-08-11 09-34-49](https://github.com/user-attachments/assets/f0f67907-ad56-4ba5-9443-bb3eb2f027d4)

**Comment by Wedge009** [comment]
I think the chat area, yes. The original report referred to what was then called the 'new' lobby, which was made the default in 1.14. Hence my remark (in another issue) about avoiding calling something 'new'/'modern'/etc.

**Comment by babaissarkar** [comment]
Run into quite a few interesting bugs.
1. Scroll text doesn't support markup ATM
2. Pango attributes and Pango markup don't work together. Using pango markup stops the attributes from working. (This isn't a pango problem but rather a text renderer bug.)

**Comment by CelticMinstrel** [comment]
Pretty sure the point is to be able to copy chat logs, yes. The chat input box already supports copying
