### ISSUE TITLE
UMC translations not working? (GNA #15962)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1209]
**[Original submission](https://gna.org/bugs/index.php?15962)** by anonymous on 2010-04-28

Translation statistics indicate there are translations of an UMC add-on, and some the .po files at berlios have non-empty msgstr entries (specifically, hu.po for Bad Moon Rising), but the add-on does not appear to have anything in the "translations" folder.  Add-on was downloaded from http://addons.wesnoth.org.

I asked about this on the forum and got this response:

http://forum.wesnoth.org/viewtopic.php?p=425006#p425006

I think that there may be a problem, or the wiki needs to to be updated.  

Thanks.

doofus-01

(Reproduced on Linux)
Release: 1.8
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-04-29**

**anonymous wrote:**

> I should have mentioned that the add-on was uploaded with the wesnoth_addon_manager script, not BfW itself.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-05-01**

**ai0867 wrote:**

> The process shadowmaster and me use is to manually merge back the .mo files from wescamp into our add-ons, and then upload those to the add-on server.
> 
> I'm not sure if wescamp is supposed to be automagic, but it isn't.

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-05-01**

**mordante wrote:**

> IIRC it used to work, will look at it later.

**mordante changed status:** None -> In Progress

**Comment by CelticMinstrel** [comment]
Wesnoth should be able to load the po files directly now, as long as the path is correctly specified by the `[textdomain]` tag. So maybe this can be closed?

**Comment by CelticMinstrel** [comment]
Oh, looks like the original poster was @doofus-01, so I should ping him on this.

**Comment by doofus-01** [comment]
I got your ping, @CelticMinstrel , I will try to test this and let you know.  (I have so little memory of this, it will take time to test.)

**Comment by Vultraz** [comment]
If I understand the original issue correctly, there were some problems with Wescamp and translations management. However, Wescamp has been defunct for years now, and there is no longer (as of 1.13) any need to handle .mo files. The game can read .po files placed in the appropriate translations folder, so it's now easy for UMC authors to provide translations without hassle. Closing.
