### ISSUE TITLE
Remove strange frame-based duration= from [print] and [message] (GNA #16026)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1212]
**[Original submission](https://gna.org/bugs/index.php?16026)** by zookeeper on 2010-05-15

According to http://wiki.wesnoth.org/InterfaceActionsWML , duration# in both [print] and [message] works based on "frames". It's very unintuitive and apparently not even accurate, so I propose the duration key be deprecated in favour of a new time= key, which would take the length of time in milliseconds.

(Reproduced on all)
Release: trunk
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by ProditorMagnus** [comment]
Seems to be removed from [message].

**Comment by CelticMinstrel** [comment]
I think it was removed from [message] because it had ceased to function.

**Comment by stevecotton** [comment]
`[print]` was changed to milliseconds in a9d9e48c72e70fd41ae9759e3894752eb9708596, for details see the comments in 264f90eed47ae7574efb739a875bea3cecc4234c.
