### ISSUE TITLE
player disconnect causes change of leader name (GNA #16061)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1214]
**[Original submission](https://gna.org/bugs/index.php?16061)** by aceman on 2010-05-23

I noticed this situation:

1. player 1 controlling side 1 has a leader with customized name (using rename unit in menu).

2. player 1 disconnects from the server.

3. other player 2 takes over his side (1).

4. game is saved.

5. new game is created using this save game.

6. player 2 takes his side 2 fine.

7. side 1 is marked reserved and expects human1 as a player.

8. player 1 joins the game and is manually set to control side 1.

9. after the game starts, player 1 finds out hid leader is named Human1, not the name he set in step 1.

(Reproduced on Linux)
Release: 1.8.1
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-12-11**

**soliton changed category:** Bug -> Feature Request

**soliton wrote:**

> Leader renaming on side dropping is intended, though maybe not too useful.

**Comment by Pentarctagon** [comment]
Closing as this was already stated to be intended functionality.
