### ISSUE TITLE
Clear labels menu item should ask for confirmation (GNA #16077)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1215]
**[Original submission](https://gna.org/bugs/index.php?16077)** by aceman on 2010-05-25

I wish I would get a confirmation dialog after clicking Clear labels item from the context menu. I think it is too easy to hit because Set label is just next to it.

(Reproduced on Linux)
Release: 1.8.1
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Vultraz** [comment]
Same request as #2371, which was fixed in 40706a8.
