### ISSUE TITLE
tooltip on leader icon with its side's color name (GNA #16116)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1217]
**[Original submission](https://gna.org/bugs/index.php?16116)** by anonymous on 2010-06-04

A tooltip on the leader icon that shows its side's color name would be useful for color blind folks who can't tell the difference between black and purple (and other colors). In on-line multiplayer games, people frequently address each other by their colors (e.g. "purple, go caves").

(Reproduced on GNU/Linux)
Release: 1.8.2
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Wedge009** [comment]
Not sure why I kept selecting Campaign label by mistake. Also I know this isn't specific to MP but it's more relevant for that mode.

**Comment by Wedge009** [comment]
Looks good. Is there a problem with leaving it on permanently?

**Comment by jostephd** [comment]
It's redundant for the majority of players.

**Comment by Wedge009** [comment]
Hmm, but tool-tips don't show unless the cursor is hovered over the item. Yes, it might be unnecessary but I don't think it's a huge deal. But I suppose it's nicer to have the option to switch them off.

**Comment by ProditorMagnus** [comment]
People who need this might not notice this preference. I think showing it always in that tooltip is good enough. Most people just have no need to regularly use that tooltip.

**Comment by ProditorMagnus** [comment]
> name: A translatable name for the color. This may be ignored for non-core colors?

Documentation can be updated then.

**Comment by Wedge009** [comment]
> "Options are bad" means there is always a trade-off to consider when adding an option since it causes an implementation and maintenance burden. If the benefit of the option is big enough it can still be implemented.

I understand that, it just sounds like a blanket statement to say you should 'never' add options.

**Comment by Wedge009** [comment]
I just noticed this enhancement could benefit #2682. While I can still see the difference between blue and purple there, clearly it's difficult for some to distinguish them even if they would not normally consider themselves colour-blind.

**Comment by jostephd** [comment]
> Documentation can be updated then.

Honestly, I fail to see how "may be ignored for non-colors" could possibly be true. It's not like there's a boolean field in the parsed config object that says whether the color range had been parsed from data/core or from ~add-ons, after all...

So, yeah, the plan is:

1. Use the name of the color_range, if available, else id
2. Add it to the sidebar, top bar, and game status dialogs
3. No new preference

**Comment by jostephd** [comment]
> Use the name of the color_range, if available, else id

Translated color names are stored in game_config::team_rgb_name.

**Comment by Wedge009** [comment]
Thanks. I know I said I'd revisit this by Tuesday but I don't think I'll have time this week - though I do plan to come back to it (and a number of other issues I've marked for myself to look into) at some point (this year I mean).

**Comment by jostephd** [comment]
Thanks for the info. I might beat you to it, then. We'll see.

**Comment by jostephd** [comment]
PR: 4366
