### ISSUE TITLE
Assertion failed: !wml_triggered (GNA #16148)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1218]
**[Original submission](https://gna.org/bugs/index.php?16148)** by anonymous on 2010-06-11

I'm getting an "Assertion failed" error with Wesnoth 1.8.2.

It is occurring in "The Founding of Borstep".  Note that this is not a mainline campaign, but I've been told that this is a "shouldn't happen" bug so it ought to be reported in the Wesnoth bug tracker:

http://forums.wesnoth.org/viewtopic.php?p=434121#p434121

The error occurs at the end of "Dwarf City", after Krag-Ubor says, "We'll go look at it, but if it's such a good spot, why did the dragon come down here?"

Assertion failed!

Program: ...ram Files\Battle for Wesnoth 1.8.2\wesnoth.exe

File: src\actions.cpp

Line: 467

Expression: !wml_triggered

(Reproduced on Windows XP)
Release: 1.8.2
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-06-11**

**anonymous added attachment:** [TFoB-Dwarf_City-Auto-Save21.gz](http://gna.org/bugs/download.php?file_id=9297)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-06-12**

**beetlenaut wrote:**

> This bug does not always occur. I was unable to create a save file that causes it, but the one uploaded by gnombat does.
> 
> 
> 
> (In case it saves you some time: the bug is triggered by a [recall] tag at line 657 in the attached cfg file.)
> 
> (file #9314)

**beetlenaut added attachment:** [09_Dwarf_City.cfg](http://gna.org/bugs/download.php?file_id=9314)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-06-12**

**anonymous added attachment:** [TFoB-Dwarf_City.gz](http://gna.org/bugs/download.php?file_id=9317)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-06-12**

**anonymous wrote:**

> Note: this bug occurs only in The Founding of Borstep version 0.9.0.  Version 0.9.1 has since been released with a workaround to avoid triggering this bug.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-20**

**anonymissimus wrote:**

> Other related (seemingly the same) reports are bug #18803, bug #18791.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-11-11**

**anonymissimus wrote:**

> I'm unassigning this from mordante. It was assigned to him since apparently silene thought it should be, mordante has no idea why however.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-03-08**

**jamit added attachment:** [01_Assert_Failure.cfg](http://gna.org/bugs/download.php?file_id=15352)

**jamit wrote:**

> I believe I have been able to reproduce this crash in a simpler case by putting a [recall] within a "die" or "last_breath" event, and having that event result from combat. I've attached a short scenario demonstrating this. (Just kill the walking corpse. You have an ancient lich. Should be easy.) There are probably other factors involved (since beetlenaut had trouble reproducing the bug), but this simple case reliably causes the assertion failure for me (using BfW 1.10.0).
> 
> (file #15352)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-04-10**

**anonymous wrote:**

> Another similar bug report here:
> 
> 
> 
> http://forums.wesnoth.org/viewtopic.php?f#8&t35356&start=15#p526061

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-05-06**

**natewr wrote:**

> As requested on the forums, I've put together a stripped down example to reproduce this error.
> 
> 
> 
> http://forums.wesnoth.org/viewtopic.php?f#21&t38775
> 
> 
> 
> I am using the PUT_TO_RECALL_LIST macro and then trying to immediately recall a unit. This causes the error. This is placed into a die event. I tried a similar approach storing and unstoring the units myself (without the macro) and received the same error.
> 
> 
> 
> To reproduce:
> 
> 
> 
> 1. Unpack wml_triggered_reproduction.zip and put the addon into your addons folder.
> 
> 
> 
> 2. Load local multiplayer game.
> 
> 
> 
> 3. Select wml_triggered reproduction case scenario and ensure use map settings is checked.
> 
> 
> 
> 4. Kill the goblin.
> 
> (file #17904)

**natewr added attachment:** [wml_triggered_reproduction.zip](http://gna.org/bugs/download.php?file_id=17904)

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-05-06**

**anonymissimus wrote:**

> Both jamit's and natewr's test cases are good and reproduce for me using 1.11.2-263-g931e1f9
> 
> I think that they cover the same bug. The attack code taking place before the last breath/die event adds "random results" in random.cpp; probably for storing in the replay. These are queried for from actions::place_recruit, the code there thinks they should be present only if itself is triggered (I think) by player-recruit or recall. (IIRC the wml_triggered parameter in place_recruit is false when triggered by a replay, an apparent unrelated bug prevented me from checking it.)
> 
> There is an easy workaround using [unit] instead of [recall], since [unit] has recall-or-create semantics. Probably only sensible for a single unit and when referencing it by id. This workaround works, since the [unit]-recalling doesn't use the same code as [recall], for probably no good reason, and doesn't check those random results.
> 
> The [recall] tag doesn't need to be in that die/last breath event, it also reproduces when another wml event in the same turn where the fight happened tries to recall. The results probably get removed at turn change then, recalling in the next turn is fine. wml mostly uses [recall] in prestart, start or turn 1 events only when no fight happened yet, so this crash doesn't happen more frequently.
> 
> The unit doesn't need to die.
> 
> I suppose this random check is made in case of player-recruit where trait randomization is done. However, recalling doesn't need any randomization. Also, [unit]-creation already doesn't do it anyway. A quick fix which seems to work is disabling the call to recruit_checksums in actions::place_recruit in case of a recall. From what the code looks like I assume recruit_checksums was written with new units in mind only.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-14**

**gfgtdf wrote:**

> The assertion in questions was removed, note sure if the underlying bug was fixed, marking as 'ready for test'

**gfgtdf changed status:** None -> Ready For Test

**Comment by sigurdfdragon** [comment]
I ran the wml_triggered_reproduction.zip on latest master
There is no assertion failure, however, I have no idea what the underlying bug is/was supposed to be.

**Comment by CelticMinstrel** [comment]
Wow, 1.8. I guess if you don't get an assertion failure from that, this was probably fixed at some point, probably in one of the last two stable releases.

**Comment by gfgtdf** [comment]
Yes assuming to be fixed then
