### ISSUE TITLE
Image in [item] are not animated (GNA #16161)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1219]
**[Original submission](https://gna.org/bugs/index.php?16161)** by alink on 2010-06-13

I just commented off a not-working fire animation in scenario-test (because of the error spam). But Espreon told me that it was a reminder. So, I post this instead.

http://svn.gna.org/viewcvs/wesnoth?rev#43408&viewrev

(Reproduced on all)
Release: trunk
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Wedge009** [comment]
For reference, this appears to be https://github.com/wesnoth/wesnoth/blob/c8976432af207e1442d316abf854e316767e3cb9/data/scenario-test.cfg#L2456, still an issue for 1.14/master.

**Comment by mesilliac** [comment]
Fixed by #5163

**Comment by Wedge009** [comment]
I'm confused. I just checked 1.16 and hex (11,1), which uses `halo=` already worked. Hex (9,1), which uses `image=` remains static. So this was a non-issue to begin with? If animations are required to use `halo=`...

**Comment by CelticMinstrel** [comment]
The linked pull request does not make images animatable, but I think we can still keep this closed as "won't fix". The important thing is that there _is_ a way to animate in `[item]`, not that it works specifically with the `image` key… unless of course someone comes up with something that would work in `image` but not in `halo`, I suppose.

**Comment by mesilliac** [comment]
Right... as i understand it `halo=` is the correct way to animate, while `image=` is for loading static images, and it not intended to be animatable in any context. The linked PR fixes `halo=` animations not working, like is used for the other campfires

**Comment by mesilliac** [comment]
previously the `halo=` animations did work... but only if there was something else on screen that was also animating

**Comment by mesilliac** [comment]
So after looking into it some more, with the current state of things yes this issue should be closed and the comment in the file removed as this is unsupported behaviour. If this behaviour is desired for some reason (like having an item animation that plays under units in stead of above it), then it should be a new feature request.
