### ISSUE TITLE
Several requests for object/effect (GNA #16172)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1220]
**[Original submission](https://gna.org/bugs/index.php?16172)** by pentarctagon on 2010-06-16

The bug: when you use make a unit loyal through object/effect, the unit will get 0 upkeep, but the trait is not visually added to the list of traits that the unit has.

A couple feature requests:

1. Add set_damage# and set_attacks keys for when apply_to=attack

2. Add a set# key for when apply_tomax_experience/hitpoints

3. Let apply_to be able to add the fearless trait

I'm making these requests based the wiki, if any of these have already been implemented then could a) someone update the wiki or b) tell me so that I can update the wiki?

(Reproduced on Windows 7)
Release: 1.8.2
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-07-22**

**silene wrote:**

> This is not a bug. Unless you add a [trait], there is no reason for the unit to have a trait. The engine can't guess that your object is supposed to give a trait (which one?).

**silene changed title:** Several requests and a bug for object/effect -> Several requests for object/effect

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-11-16**

**gfgtdf wrote:**

> 3) has been implemented, just like for loyal it sill only five you the effect not the trait.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-11-16**

**gfgtdf wrote:**

> s/sill only five/only gives

**Comment by gfgtdf** [comment]
all of these exists now (no sure since when)
