### ISSUE TITLE
Use normal transitions to fix the edges of the Grid. (GNA #16205)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1221]
**[Original submission](https://gna.org/bugs/index.php?16205)** by eleazar on 2010-06-27

Here's a little thing that's been bugging me.

The grid doesn't draw well on the edges.

If the terrain was snow rather than sand, the hexes marked with an X would have no visible grid. (see attachment)

There were files for grid-top, and grid-bottom which apparently aren't actually used, and wouldn't have solved the problem for non-square maps anyway.  I deleted them.

The solution is simple- the grid needs the 6 basic transitions. Then all hexes will get a light and dark line on all sides, so at least one is visible no matter the terrain.

These files are in trunk, but don't currently do anything, i guess the code needs to be tweaked.

(Reproduced on ANY)
Release: SVN
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-06-27**

**eleazar added attachment:** [Grid.jpg](http://gna.org/bugs/download.php?file_id=9380)

**Comment by Wedge009** [comment]
Not sure if this is exactly what eleazar was describing but it seems okay in 1.14.7.

![grid_1147](https://user-images.githubusercontent.com/13679322/64319895-c0848b00-d000-11e9-9b45-491f2fcc4314.jpg)

Please re-open if it is not.
