### ISSUE TITLE
don't give "Filter" keyboard focus when a match is clicked (GNA #16286)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1223]
**[Original submission](https://gna.org/bugs/index.php?16286)** by anonymous on 2010-07-19

see summary

(Reproduced on GNU/Linux)
Release: 1.8.1
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Vultraz** [comment]
Selecting a match in the lobby does remove focus from the filter textbox.
