### ISSUE TITLE
Lag when beginning animations if animations have lots of frames (GNA #16363)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1226]
**[Original submission](https://gna.org/bugs/index.php?16363)** by elvish_pillager on 2010-08-05

I've been using WML to create units with 80+ separate animations, which are understandably laggy. What seems unusual is that when I increase the number of *frames* in each of those animations by a lot, without increasing the number of animations, there's still a significant increase in the lag when starting animations (an increase over the situation with 80 simple animations, that is.)

There doesn't seem to be an unusual amount of lag in the actual animations - only before an animation begins.

The attached savefile illustrates such a situation: attack the wolf with the wraith to observe the lag.

(Reproduced on Ubuntu)
Release: 1.8.3
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-05**

**elvish_pillager added attachment:** [animation_lag_example_save.gz](http://gna.org/bugs/download.php?file_id=9702)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-05**

**silene added attachment:** [animation-trace.png](http://gna.org/bugs/download.php?file_id=9705)

**silene wrote:**

> I have attached the callgraph obtained while the animation is playing. There is an obvious path, assuming the graph is correct:
> 
> - 90% spent in Lua scripts (luaW_pcall),
> 
> - 66% spent in creating units (unit::unit),
> 
> - 63% spent in adding animations to these units (unit_animation::add_anims),
> 
> - 42% spent in building config objects (config::append).
> 
> (file #9705)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-06**

**silene wrote:**

> Here is an updated callgraph after applying the 4 patches. The total time has been halved, but it is still way too long for the game to be usable. The bottleneck is now:
> 
> - 80% spent in Lua/WML,
> 
> - 50% in creating units from Lua,
> 
> - 25% in adding animations to a unit,
> 
> - 15% in creating particles.
> 
> (file #9718)

**silene added attachment:** [animation-trace5.png](http://gna.org/bugs/download.php?file_id=9718)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-06**

**silene wrote:**

> Updated callgraph. From an animation point of view, the biggest offenders are the 33% of unit_animation::add_anims (of which 20% are from particule::particule). On the Lua side, there are 30% spent on getting data from/to WML and engine. The remaining 35% of the profile do not show anything obvious.
> 
> (file #9722)

**silene added attachment:** [animation-trace10.png](http://gna.org/bugs/download.php?file_id=9722)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-29**

**boucman wrote:**

> ok, we are adding custom animations, so my first idea of factoring into the type to parse them only once won't work.
> 
> 
> 
> basically what takes time is that we are reading the WML and filling in the structures describing the actual animations.
> 
> 
> 
> a complicated method would be to have a "load_animation" wml action that could be added to prestart events That would load the animation WML and attach it to an id, and then be able to attach it to a unit through the add_animation action.
> 
> 
> 
> Would this be fine with you ?

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-29**

**boucman wrote:**

> note to self : ok, here is the plan...
> 
> 
> 
> each animation can have an id to avoid loading.
> 
> 
> 
> we keep some sort of global std::set which matches id to unit_animation structures (multiple du to conditional expansions)
> 
> 
> 
> when an animation is added to a unit, we look for the id in that set
> 
> 
> 
> * if it is in, we add a copy to the unit, as we do for animations that come from the unit_type
> 
> * if it is not call a lua function that will return the cfg to be parsed, and parse it the old way. 
> 
> 
> 
> ask silene for implementation details.
> 
> 
> 
> still need to figure out where to store the set so it has the proper lifecycle

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-29**

**boucman wrote:**

> Ok, the cache has been added, but unfortunately the fix can't ve tested with the savegame.
> 
> 
> 
> Elvish Pillager, could you do the following ?
> 
> 
> 
> in the "new_animation" block where you add the animation could you add an id=<something> flag, where "something" is any string that is different for each new_animation block ?
> 
> 
> 
> this should reduce most of what's left of the blocking time.
> 
> 
> 
> if that's not enough, could youpost a new save after that feature was enabled so we can look into it some more ? thx

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-07**

**wedge009 wrote:**

> Is this related to bug #17865?

**Comment by Wedge009** [comment]
New link: #1253

**Comment by Pentarctagon** [comment]
Closing given the age as well as #2915 being possible without this issue happening apparently.
