### ISSUE TITLE
Show Enemy Moves not updated after recruitment (GNA #16402)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1227]
**[Original submission](https://gna.org/bugs/index.php?16402)** by maiklas3000 on 2010-08-11

When you Show Enemy Moves and then do a recruitment, the Show Enemy Moves display is not updated. This can lead to an inconsistent and confusing display. This could be fixed simply by updating the Show Enemy Display (if already active) after a recruitment.

For discussion, see the thread:

http://forums.wesnoth.org/viewtopic.php?p=448511

(Reproduced on All? W7 64-bit)
Release: 1.8.3 and earlier
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-11**

**maiklas3000 added attachment:** [wesnoth, show enemy moves buggy during recruitment.jpg](http://gna.org/bugs/download.php?file_id=9788)

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-08-12**

**anonymissimus changed category:** Bug -> Feature Request

**Comment by Wedge009** [comment]
Seems to be working properly when I checked 1.14.7. Please re-open if it is not.
