### ISSUE TITLE
Being able to customize recall cost based on unit characteristics criteria. (GNA #16538)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1229]
**[Original submission](https://gna.org/bugs/index.php?16538)** by stevenaus on 2010-08-25

The ability to customize recall cost - to be able to set criteria for a particular gold recall cost.  So any comparison operator/s (on any of the particular unit's characteristics) on each line, such as #, >, <=, <>, *and*, and in the case of traits *contains*, and *does not contain* (be able to test for particular individual traits, or trait combinations - *and* could be used with *contains* and *does not contain* statements too).   They would be evaluated starting from the top, the first line that has its criteria satisfied is the one the cost would be associated with and shown in the recall dialog (so if you had multiple possibilities for a custom recall cost, the one that is matched first is the one that would be used and shown in the recall dialog).  If a particular unit does not satisfy any line's criteria, it would use the default recall cost (either the global default, or whatever the default recall cost is defined for that "side" in that scenario's WML).

What do you think?

Best regards,

Steven.

(Reproduced on Any Supported)
Release: 1.9 series
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-25**

**stevenaus wrote:**

> (in the case of non-number characteristics, such as Unit Type, "<>"   means *does not equal*)

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-08-29**

**zookeeper wrote:**

> Frankly I can't even figure out what you're trying to describe.
> 
> 
> 
> Support for customizable recall costs should be as simple as having a recall_cost=<number> key available both in unit types and single units.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-23**

**gfgtdf wrote:**

> You can already set the recall costs for indivudal unit and the rest can be done with lua/wml code.

**gfgtdf changed status:** None -> Fixed

**Comment by CelticMinstrel** [comment]
If this is fixed, shouldn't it be closed? Though, from the comments, it seems that invalid is more accurate than fixed.
