### ISSUE TITLE
Implement sorting bans by criteria other than IP (GNA #16541)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1232]
**[Original submission](https://gna.org/bugs/index.php?16541)** by mystic_x on 2010-08-25

Add a way to sort the server bans currently shown with '/query bans' and sorted by IP also by the other attributes of the ban (start date, end date etc.)

(Reproduced on any)
Release: 1.9.0
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Wedge009** [comment]
Hmm, is it only possible to query bans as an admin/moderator?

**Comment by soliton-** [comment]
Yes, see http://wiki.wesnoth.org/ServerAdministration

With wesnothd now respecting forum bans this is probably less useful anyway.

**Comment by Wedge009** [comment]
Thanks. That probably means I can't really try #1246 and #1247 either then.

**Comment by Pentarctagon** [comment]
Is this useful to keep open at this point?  How many wesnothd bans exist at the moment?

**Comment by Pentarctagon** [comment]
Soliton checked just now and 1.14's MP server has no wesnothd bans to sort, so given that I'll close this.
