### ISSUE TITLE
Support for [movement_costs] in [filter_radius] (GNA #16688)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1235]
**[Original submission](https://gna.org/bugs/index.php?16688)** by zookeeper on 2010-09-12

While SLF's can already do almost anything, tasks like reliably finding out the exact movement/vision range of a unit or how many movement points are needed to reach a given location are still practically impossible. However, if [filter_radius] could take a [movement_costs] tag which would specify how many "points" it takes for the radius to expand to a given hex, these would become doable.

For example, this would store the farthest away locations that side 1 can reach (to attack):

```

[store_unit]

    [filter]

        side=1

    [/filter]

    

    kill=no

    variable=units

[/store_unit]



{FOREACH units i}

    [store_locations]

        find_in=locs

        

        [or]

            [and]

                x,y=$units[$i].x,$units[$i].y

                radius="$($units[$i].moves + 1)"

                

                [filter_radius]

                    [insert_tag]

                        name=movement_costs

                        variable=units[$i].movement_costs

                    [/insert_tag]

                [/filter_radius]

            [/and]

            

            [not]

                x,y=$units[$i].x,$units[$i].y

                radius=$units[$i].moves

                

                [filter_radius]

                    [insert_tag]

                        name=movement_costs

                        variable=units[$i].movement_costs

                    [/insert_tag]

                [/filter_radius]

            [/not]

        [/or]

        

        variable=locs

    [/store_locations]

{NEXT i}

```

As a simpler example, this SLF could be used to store the locations onto which overflowing lava should expand to, if you'd want it to expand twice as fast onto cave floor than onto rockbound cave:

```

    terrain=Ql*

    radius=2

    

    [filter_radius]

        [movement_costs]

            flat=1

            cave=1

            hills=2

        [/movement_costs]

    [/filter_radius]

```

Of course, the tag could be named [radius_costs] too. I'm assigning to Sapient since this is your area of expertise; feel free to unassign if you're not interested.

(Reproduced on all)
Release: trunk
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by stevecotton** [comment]
@ln-zookeeper, please would you review whether there's anything left to do in this ticket?

In the time since this was originally written, `[store_reachable_locations]` and `[find_path]` have been added, and both are in 1.14. The lava example wouldn't be supported by that, but the other examples would be.

**Comment by ln-zookeeper** [comment]
Yes, I think those tags fulfill this FR reasonably well, so I'll just close this. I'm pretty sure the main purpose of the FR was to get **some** method of calculating reach, and there are good ways now, so I don't think we should keep this open merely because the current solutions look different than what was requested here.
