### ISSUE TITLE
A new font for Vietnamese (GNA #17074)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1240]
**[Original submission](https://gna.org/bugs/index.php?17074)** by anonymous on 2010-11-11

''This is hhyloc, current translation maintainer of Vietnamese, I couldn't used my account to post this because my ip was black listed (don't khow why) so I had to post this anonymously (with my ip changed)''

Currently, the best font to display Vietnamese is DejaVuSans, but even this font is not so good at displaying Vietnamese, as can be seen in the images[1]...

Problems:

"?" looks like "?"

"?" looks like "?"

"?" looks like "�"

"?" looks like "?"

"." in words like "v?","ch?","th?" displayed at the wrong position.

And others.

Solution: I found a font named Arev, it displayed Vietnamese perfectly, fixed all the problems DajaVuSans had. So I suggest adding this font to help Vietnamese can enjoy the game more.

For copyright concerns of the font: http://tavmjong.free.fr/FONTS/ArevCopyright.txt (If I understand it correctly, the font is free to use, copy, merge, publish, distribute, and/or sell..v.v.)

I also attached the font, the po file (vi.po) for "wesnoth" package which I modified these translation strings (not original strings):

DejaVuSans.ttf,Andagii.ttf,wqy-zenhei.ttc

DejaVu Sans,Andagii,WenQuanYi Zen Hei 

into this:

Arev.ttf,DejaVuSans.ttf,Andagii.ttf,wqy-zenhei.ttc

Arev,DejaVu Sans,Andagii,WenQuanYi Zen Hei 

If something is wrong, please contact me at nightgaunt13@gmail.com

[1]

DejaVuSans font: http://i284.photobucket.com/albums/ll10/hHyLoc/DejaVuSansfont.jpg

Arev font: http://i284.photobucket.com/albums/ll10/hHyLoc/Arevfont.jpg

P.S: Sorry for my bad English.

(Reproduced on Windows XP)
Release: 1.9.2
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-11-11**

**anonymous added attachment:** [vi.po](http://gna.org/bugs/download.php?file_id=11191)

**anonymous added attachment:** [Arev.ttf](http://gna.org/bugs/download.php?file_id=11190)

**Comment by Wedge009** [comment]
Does anyone know if the switch to Lato has mitigated any of the issues with Vietnamese?

**Comment by CelticMinstrel** [comment]
Also, I wonder what all the ?'s in the initial post were.

**Comment by Wedge009** [comment]
Possibly characters that weren't converted properly in the transfer from Gna...

**Comment by CelticMinstrel** [comment]
Right, that's what I assumed too, but it doesn't actually answer the real question. :P

**Comment by Wedge009** [comment]
Unfortunately, Gna has since died. Fortunately, archive.org archived it in [February this year](https://web.archive.org/web/20170204102906/gna.org/bugs/index.php?17074).

> "ễ" looks like "ẽ"
> "ữ" looks like "ũ"
> "ẫ" looks like "ã"
> "ầ" looks like "ẩ"
> "." in words like "vị","chị","thị" displayed at the wrong position.

**Comment by Wedge009** [comment]
I tested this in 1.14.7 MP lobby and all the characters above seem to be okay. I don't have easy access to pre-Lato builds but I assume this is okay for Vietnamese now.

(Looks like Vietnamese translation doesn't meet the 80% threshold so I couldn't check that.)

**Comment by soliton-** [comment]
You can call wesnoth with the option `--all-translations`. Still need to find a translated string though.
