### ISSUE TITLE
Wish menu to pop up when there is animation going on (GNA #17219)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1241]
**[Original submission](https://gna.org/bugs/index.php?17219)** by porcho on 2010-12-04

When an unit is moving(in animation), and you click on an empty slot of the castle to recruit another unit, a menu with "Unit Description", "Clear Labels", "Toggle planing mode", "Next Unit" pops up instead of the normal menu. It would be very nice, to be able to open the menu with the "Recruit" option, while an unit is moving.

(Reproduced on Windows XP)
Release: 1.9.2
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2010-12-04**

**soliton changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-02-20**

**jamit wrote:**

> There is a timing issue involved with this. Suppose you were able to select the "Recruit" option while a unit is moving. What is supposed to happen if an event fires when that unit is done moving? (For example, moving the unit might cause some monsters to appear. Or perhaps it might cause the player to lose all gold -- including what had just been spent on the new recruit.)
> 
> 
> 
> The game engine is largely written on the assumption that only one action can be performed at a time.
> 
> 
> 
> (If you are impatient, you can accelerate the animations so you don't have to wait so long.)

**Comment by Wedge009** [comment]
I'd even be inclined to close this. As jamit suggested one can just accelerate the animations.

**Comment by jostephd** [comment]
Similar: #1064 

I wouldn't be opposed to merging the two issues.

**Comment by gfgtdf** [comment]
Yes this seems to be beasicially a special case of #1064
