### ISSUE TITLE
It would be nice if the game resolution in fullscreen would be the current desktop resolution (GNA #17245)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1243]
**[Original submission](https://gna.org/bugs/index.php?17245)** by laurion on 2010-12-06

It would be nice if the game resolution in fullscreen would be the current desktop resolution.

As a matter of fact, I use the 1366 x 768 resolution and because i didn't notice the "Change resolution" button in the Preferences menu so I had to use the default resolution.

(Reproduced on Windows Seven)
Release: 1.9.2
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-12-29**

**ancestral wrote:**

> May be a duplicate of #20193.
> 
> 
> 
> May also have been fixed with SDL2.

**Comment by Vultraz** [comment]
This is the case in 1.13 post-SDL2 transition, since we use `SDL_WINDOW_FULLSCREEN_DESKTOP`. There's been some controversy about this, though (#1545) but since the behavior asked for here has been implemented, closing.
