### ISSUE TITLE
Allow vertical scrolling when there is too much text in [story] blocks (GNA #17492)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1250]
**[Original submission](https://gna.org/bugs/index.php?17492)** by ivanovic on 2011-01-15

Currently there is no way to display more text than there is space available right on the screen. Any text that is "too much" is simply cut off. Usually you don't notice that when using a resolution of >=1024x768. But in smaller resolutions like 800x600 (or even 800x480) it might happen that text has to be cut off. This is currently (r48273) the case in some scenarios of Two Brothers with the lengthy diary entries and is even more problematic for translations that need more space than the English language (like eg German). The commit r48247 already significantly improved things by basically removing the "unused" border and filling it with text instead of whitespace.

For the moment I have to add a workaround to those story screens and split them in two. Since it is likely that translators are not aware of those problems I would propose adding vertical scrolling to the [story] screens if there is too much text to display it.

(Reproduced on Any)
Release: 1.9.3+svn (r48273)
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-01-15**

**ivanovic wrote:**

> Added a workaround for the problem in Two Brothers in r48279:
> 
> http://svn.gna.org/viewcvs/wesnoth?rev#48279&viewrev

**Comment by Vultraz** [comment]
This is probably fixed by the transition of the storyscreen to GUI2. Could @Wedge009 confirm?

**Comment by Wedge009** [comment]
I read through the Tale of Two Brothers introduction in the current minimum resolution, 800x600, and note that the text section expands to fit the text. I would not know what might happen should there be more text than can fit in the entire window at once (scroll? truncate? crash?), but I think Tale of Two Brothers has the lengthiest story text per page at the moment.

Could be closed, unless some wants to try testing a stupidly large block of text for the story screen.

**Comment by CelticMinstrel** [comment]
Hmm, expanding to fit the text may actually be less than ideal, as it means the image will be more covered on smaller screens... I wonder if a max height should be set...

**Comment by Vultraz** [comment]
Closing this. I tested with a ridiculously large block of text, and found the text area will expand until it fills the screen, and then grants a scrollbar. Perhaps a max height should be set, yes, but that's not that simple, and besides, UMC authors can just manually split the story parts.
