### ISSUE TITLE
lag when firing animation (GNA #17865)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1253]
**[Original submission](https://gna.org/bugs/index.php?17865)** by anonymous on 2011-03-08

There is often, though not always, a lag between when a unit is placed on a map and when a subsequent animation is fired, so that the base frame appears for a fraction of a second before the intended animation.  See http://forum.wesnoth.org/viewtopic.php?p=481386#p481386

(Reproduced on linux)
Release: 1.9.4
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-07**

**wedge009 wrote:**

> Is this related to #16363?

**Comment by Wedge009** [comment]
New link: #1226

**Comment by Pentarctagon** [comment]
Closing given the age as well as #2915 being possible without this issue happening apparently.
