### ISSUE TITLE
portaits scaled badly in dialogue (GNA #17961)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1254]
**[Original submission](https://gna.org/bugs/index.php?17961)** by anonymous on 2011-03-28

Starting in 1.9.3, the portraits got scaled down severely, at least for some screen sizes.  In 1.9.5, the scaling method degrades the images more than it did in 1.9.3 and 1.9.4.  But they should not get scaled at all?  Please see forum post:

https://r.wesnoth.org/p483567

(Reproduced on linux)
Release: 1.9.5
Priority: 5 - Normal
Severity: 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-03-28**

**shadowmaster changed severity:** 3 - Normal -> 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-03-31**

**mordante wrote:**

> There have been changes in the size of the scaling between 1.9.3 and 1.9.4, which can cause the size reduction.
> 
> 
> 
> The quality reduction might be caused by [1]. When looking at an image in 1.9.3 and 1.9.5. scaled down to the same size does the quality then also degrade?
> 
> 
> 
> 
> 
> [1] http://forum.wesnoth.org/viewtopic.php?f#5&t3284&start=15#p481831

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-03-31**

**anonymous wrote:**

> There must be a typo in your link, mordante, it leads to a 2004 post about ghosts.  I didn't notice much of a difference between 1.9.3 and 1.9.4, but I will check.  What I did notice was:
> 
>  1.9.2 vs 1.9.3, images got scaled down
> 
>  1.9.4 vs 1.9.5, image quality decreased
> 
> 
> 
> - doofus-01

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-03-31**

**shadowmaster wrote:**

> I think he meant http://forums.wesnoth.org/viewtopic.php?p=481831#p481831 .

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-04-01**

**anonymous wrote:**

> OK, I think I understand:
> 
> 
> 
> A.  Dec. 10th -> 1.9.3
> 
> 
> 
> B.  Dec. 19th -> r47967
> 
> 
> 
> C.  Jan. 17th -> 1.9.4 -> Did r47967 make the portraits smoother in 1.9.4 than they were in 1.9.3?
> 
> 
> 
> D.  March 12th -> r47967 is undone, hard edges restored for editor 
> 
> 
> 
> E.  March 27th -> 1.9.5 -> Did action "D" make 1.9.5 have same portraits as 1.9.3?
> 
> 
> 
> I'll have to re-install 1.9.3, so I don't yet know.  But AI (in my forum link below) said the portraits should not be getting scaled at all for normal screen sizes, so isn't the real problem older than 1.9.3?

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-04-02**

**anonymous wrote:**

> OK, mordante was right, that's what it was.  See:
> 
> http://forum.wesnoth.org/viewtopic.php?p=484231#p484231

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-04-03**

**ai0867 wrote:**

> There are two issues here:
> 
> 1. Portraits are scaled when there is no need to do so. This was probably introduced along with extremely tall portraits (> 500 px, like the wose) as a temporary fix. Wanted behavior:
> 
> -Scale down to 500px wide if wider.
> 
> -Crop down to screen height if (still) too tall.
> 
> 
> 
> 2. The scaling algorithm messes up the minimap by sampling from pixels not in the hex. The scaling algorithm was then re-broken to fix this, which re-worsened any scaling for portraits and such.
> 
> 
> 
> 
> 
> So, fixes that are needed:
> 
> 1. Change GUI2 to make portraits work as wanted.
> 
> 2. Specialize the scaling algorithm to work for the minimap, then re-enable the proper sampling.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-04-05**

**ai0867 wrote:**

> Reading a commit shadowmaster linked to [1], it appears the max width is now screen_width/3. Which may be more reasonable than 500px, but is probably what causes the scaling at smaller resolutions. (1024px wide -> scales everything wider than 341px, which is just about everything)
> 
> 
> 
> 
> 
> [1] http://svn.gna.org/viewcvs/wesnoth?view#rev&rev47766

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-11-09**

**ai0867 wrote:**

> Bumping up to blocker as we do not want to release 1.10 with portraits looking like this.

**ai0867 changed severity:** 4 - Important -> 5 - Blocker

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-12-10**

**mordante changed status:** None -> Ready For Test

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-12-11**

**ai0867 wrote:**

> Portraits are still scaled on 1024 pixel-wide screens, but I guess there's not much that can be done about that.
> 
> 
> 
> On <700 pixel tall screens that are wide enough for 500 pixel wide portraits, rithrandil is still scaled though. The idea was that everything above 500px that doesn't fit is allowed to be cropped.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-12-11**

**mordante wrote:**

> I designed the dialog to only scale and not to crop, so the fact that rithrandil is scaled on several screens is by design.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-12-11**

**ai0867 wrote:**

> That may be true, but rithrandil was designed against the spec I described, which was an idea to make huge units look that way without noticeable cropping. (if the screen is tall, you can show the whole portrait. If it's short you can crop anything above 500px)
> 
> It's not very important for 1.10, but it was a spec that the artists rather liked.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-12-17**

**mordante wrote:**

> I talked with Jetrel regarding the wishes of the portraits before coding. In
> 
> the original specification, there was only the wish to scale portraits, not to
> 
> crop them. So I designed the engine according to these specifications.
> 
> 
> 
> So at the moment it needs quite a bit of work to change how it works. Since
> 
> there are a lot of other GUI2 things to be done, this has a low priority for
> 
> me. Also I don't consider it a bug.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-22**

**ivanovic changed status:** Ready For Test -> Duplicate

**ivanovic wrote:**

> Sounds like a duplicate of bug #18686.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-22**

**ivanovic changed severity:** 5 - Blocker -> 4 - Important

**ivanovic changed status:** Duplicate -> Postponed

**ivanovic wrote:**

> Espreaon just mentioned that it is not a dupe, so marking it as postponed till past 1.10 is branched off...

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-27**

**shadowmaster added attachment:** [map-scaling-wesnoth.jpg](http://gna.org/bugs/download.php?file_id=14840)

**shadowmaster wrote:**

> I just realized that the scaling algorithm also makes the titlescreen background look terrible with jagged text edges on 800x600 (I normally use 1280x800, which displays a completely unrelated problem).
> 
> 
> 
> Attached a screenshot of the titlescreen on 800x600, and a version of the titlescreen background scaled using the GIMP's Linear scaling method.
> 
> (file #14840, file #14841)

**shadowmaster added attachment:** [map-scaling-gimp-linear.jpg](http://gna.org/bugs/download.php?file_id=14841)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-27**

**shadowmaster wrote:**

> Also attaching a 1.8 screenshot for reference.
> 
> (file #14842)

**shadowmaster added attachment:** [map-scaling-wesnoth-1.8.jpg](http://gna.org/bugs/download.php?file_id=14842)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**mordante wrote:**

> Shadowmaster as said on IRC I consider the image scaling algorithm problem not as part of this bug, but see it as a separate issue.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**shadowmaster changed status:** Postponed -> None

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-29**

**ai0867 wrote:**

> There are 4 scaling-related bugs:
> 
> * Portraits get scaled when they don't need to be.
> 
> ** Fixed in r52205.
> 
> * Portraits get scaled rather than cropped above 500px when there's no room.
> 
> ** No other bug filed.
> 
> * Too-large portraits occasionally crash the game.
> 
> ** Bug #18686.
> 
> * Misuse of scaling algorithms.
> 
> ** Minimap should not use interpolation, main menu background, story art and portraits should. (main menu is broken, not sure about the rest)
> 
> ** No other bug filed.

**Comment by CelticMinstrel** [comment]
Is this still an issue in [c][message][/c]?

**Comment by CelticMinstrel** [comment]
@ln-zookeeper Does that commit fix this?

**Comment by AI0867** [comment]
It's related to the selection of scaling algorithms, which has to do with some parts of this issue.

The main thing this issue is about though, is this:
> Portraits get scaled rather than cropped above 500px when there's no room.

**Comment by Wedge009** [comment]
The title here seems specific to scaling of portraits in (I assume) game story dialogue. Is there anything still outstanding in relation to that for 1.15/1.16? If there are other things this issue brings up that aren't yet resolved, perhaps the title needs to be changed?

**Comment by Wedge009** [comment]
Scaling and rendering has changed dramatically (eg #7741, #8275) since the original report, plus the lack of activity says to me this is not relevant. I think it's perhaps better to start a new issue rather than re-open this one if there's anything still outstanding.
