### ISSUE TITLE
Remove/increase character limit on lobby PMs (GNA #18008)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1255]
**[Original submission](https://gna.org/bugs/index.php?18008)** by insinuator on 2011-04-07

I would like the the Private Message character limited increased.  Currently, when you double-click on another player's nickname and send a PM, there is a 17 character limit.  This is very annoying and allows for little communication.

Now, I know you're going to tell me to type out the /msg - playername - whatever, but that is a more cumbersome approach.  The GUI PM is a kernel of a good idea.  It just needs some more flexibility.  Let's make it pop!

(Reproduced on Windows 7)
Release: 1.8.5
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-03**

**shadowmaster wrote:**

> The source code for the mp_cmd_wrapper GUI2 dialog (more spec. the gui2::tmp_cmd_wrapper::pre_show() method) imposes an 18 characters limit when compiling for Windows and Mac OS X, which is rather odd:
> 
> 
> 
> ```
> 
> #if defined(_WIN32) || defined(__APPLE__)
> 
> 	ttext_box* message =
> 
> 			find_widget<ttext_box>(&window, "message", false, false);
> 
> 	if(message) {
> 
> 		/**
> 
> 		 * @todo For some reason the text wrapping fails on Windows and Mac,
> 
> 		 * this causes an exception to be thrown, which brings the user back
> 
> 		 * to the main menu. So avoid that problem by imposing a maximum
> 
> 		 * length (the number of letters W that fit).
> 
> 		 */
> 
> 		message->set_maximum_length(18);
> 
> 	}
> 
> #endif
> 
> ```
> 
> 
> 
> (This is the situation as of trunk r55227, some time after 1.11.0.)
> 
> 
> 
> I'm assigning this to mordante in the hope that he might know what to do about this before 1.12.

**Comment by Vultraz** [comment]
Fixed in 1.13 with the Lobby redesign. The limit is no longer necessary since we handle PMs directly in the chatbox.
