### ISSUE TITLE
FR: Allow multiple #ifdef symbols (GNA #18069)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1256]
**[Original submission](https://gna.org/bugs/index.php?18069)** by spookymagician on 2011-04-25

I was frustrated to learn that you cannot use multiple #ifdef symbols either...

Example:
```
#ifdef NORMAL,HARD

  # do stuff here...

#endif
```

I would find it somewhat useful at times. Maybe not very often but, I am sure it could have it's uses...

(Reproduced on ALL?)
Release: 1.9+
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-04-25**

**spookymagician wrote:**

> I forgot to mention that it should check if both symbols or either symbols is/are defined. (If allowed.)
> 
> 
> 
> The example below should read: if normal or hard (or) normal and hard (technically this doesn't make sense but, other custom symbols could make sense.), do stuff, end if...
> 
> 
> 
> Mostly just to remove redundancies of only checking for 1 symbol at a time. It could have it's uses.
> 
> 
> 
> ~ SpoOkyMagician

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-15**

**gfgtdf wrote:**

> I think wit this proposes syntax its quite unclear whether its 'and' or 'or' behaviour, https://gna.org/bugs/?22969 seems to be a better option to me.

**Comment by Pentarctagon** [comment]
Closing in favor of #1425
