### ISSUE TITLE
[interface] Cancelling order of unit if ennemi appears (GNA #18070)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1257]
**[Original submission](https://gna.org/bugs/index.php?18070)** by paul_kauphart on 2011-04-25

The idea is to cancel the orders carried to the next turn if a ennemy unit appear while its not your turn, or if your unit is zocced or attacked, or at least having a "press t to continue" like warning before executing the order.

Already discussed here in the forum :

http://forums.wesnoth.org/viewtopic.php?f#12&t30425

(Reproduced on Any)
Release: 1.8.5
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Wedge009** [comment]
Closing as duplicate - or at least very similar to - #1113.
