### ISSUE TITLE
A couple minor requests (GNA #18171)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1262]
**[Original submission](https://gna.org/bugs/index.php?18171)** by velensk on 2011-05-30

The first request I have, is that the hills/tropical forest terrain be made a joint hill/forest terrain for gameplay rather than being an alias of forest alone. This one is a coherency/gameplay improvement that seems like common sense to me.

The second request I have, is that the map editor have a 'load recent' option so that when one is making maps for UMC one does not have to browse out of the editor folder into the add-ons folder and to the map they were just working on. This is a convenience feature.

(Reproduced on OSX 10.5.8)
Release: 1.9.6
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-06-13**

**shadowmaster wrote:**

> This is both a bug and a feature request. It'd be appreciated if you posted separate issues in the tracker instead of piling them up into a single one.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-06-14**

**velensk wrote:**

> Alright, consider this the thread for the second one, which would be the feature.

**Comment by Vultraz** [comment]
Load Recent has been a thing since (IIRC) 1.12 now.

As for the other thing, I actually think that might be the case now? @ln-zookeeper is it so?

**Comment by nemaara** [comment]
Yes, the hills/tropical forest acts as any other joint terrain, so this can be closed.
