### ISSUE TITLE
Option to tune map auto-scrolling at the beginning of a new turn (GNA #18255)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1264]
**[Original submission](https://gna.org/bugs/index.php?18255)** by anonymous on 2011-06-21

Currently wesnoth autoscrolls the map to the main hero at the beginning of a new turn.

I'd like a setting that would allow to change this behavior to scrolling to the position in which "End Turn" was pressed.

Reason: I'm using to make the last moves before the end of the turn in the most important place of the map. This helps remembering the plan when a new turn starts.

I'm noticing that autoscroll to the main hero also happens when a game is loaded from a save file. The autoscroll setting should take effect here too. It's even more important, since loading a game after a long break for real life in the same screen position it was saved helps remembering the main plan even more.

(Reproduced on Slackware Linux)
Release: 1.8.6
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Pentarctagon** [comment]
Is this something that's worth having a setting for?

**Comment by Wedge009** [comment]
I'm not sure how useful this is either, and we can't identify the requester.

Sometimes I notice that loading a game scrolls to a completely different position than my leader, eg in a scenario like The Chase in Two Brothers, where the player's team starts at the south end and needs to work their way north, a load game will have the screen position set at the north end. So I'm not sure how reliable the initial 'scroll to leader' feature is anyway.

**Comment by Wedge009** [comment]
If it turns out to be really that useful to someone, this can be re-opened.
