### ISSUE TITLE
Textdomain bindings not being on the first line of a file can cause translations not to show up sometimes (GNA #18378)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1265]
**[Original submission](https://gna.org/bugs/index.php?18378)** by espreon on 2011-07-18

Sometimes, if the textdomain binding isn't on the first line of a file, the translations for the strings in that file won't show up. In an observed situation, a big macro is defined right before the textdomain binding. If the macro definition is removed, the translations will show up.

I shall attach a test campaign and instructions shortly.

(Reproduced on Sabayon Linux)
Release: 1.9.7+svn (50337)
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-07-18**

**espreon changed title:** Textdomain bindings not being on the first line of the file can cause translations not to show up sometimes -> Textdomain bindings not being on the first line of a file can cause translations not to show up sometimes

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-07-18**

**espreon wrote:**

> svn co: https://wesnoth-umc-dev.svn.sourceforge.net/svnroot/wesnoth-umc-dev/branches/testing/trunk/Bug18378
> 
> 
> 
> Tarball: http://wesnoth-umc-dev.svn.sourceforge.net/viewvc/wesnoth-umc-dev/branches/testing/trunk/Bug18378/?view=tar
> 
> 
> 
> After putting the test campaign in the proper location, do the following:
> 
> 
> 
> 1. Switch to the Japanese translation
> 
> 
> 
> 2. Start the test campaign
> 
> 
> 
> 3. Put the cursor over the Spearman
> 
> 
> 
> 4. Look at the sidebar; you should see "Kureijii" instead of ???????

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-07-18**

**espreon wrote:**

> And for those who can't find the option for the Japanese translation, choose "??? (Nihongo)".

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-07-24**

**espreon wrote:**

> As Ivanovic suggested on IRC, I checked in the po file. So, just run svn up to get it or go here: http://wesnoth-umc-dev.svn.sourceforge.net/viewvc/wesnoth-umc-dev/branches/testing/trunk/Bug18378/ja.po?view=log

**Comment by Pentarctagon** [comment]
This seems more like a coding bug?  I feel like the correct solution here isn't to have Wesnoth try to handle people putting textdomain declarations in random places, but rather to just say "textdomain declarations must always come first".

**Comment by CelticMinstrel** [comment]
I don't think it's at all complicated to handle textdomains everywhere, and it needs to work _anyway_ since you can switch textdomains halfway through (eg, to reuse mainline strings).

But given the age of this bug, it's probably referring to the Perl wmlxgettext tool, which is no longer in use.

**Comment by Pentarctagon** [comment]
Alright, closing in that case.
