### ISSUE TITLE
[ai] blocks are ignored (GNA #18679)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1271]
**[Original submission](https://gna.org/bugs/index.php?18679)** by beetlenaut on 2011-09-17

If there is more than one [ai] block in a side tag, all of them are ignored. (This is true at least with [avoid]. Most other ai keys and tags have less obvious effects, so it's hard to tell.)

(Reproduced on Linux)
Release: 1.9.9
Priority: 5 - Normal
Severity: 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-25**

**anonymissimus wrote:**

> Crab, I guess you don't mind; I can't reproduce this in r51637. I used a side definition like so
> 
> +```+
> 
> 	[side]
> 
> 		side=2
> 
> 		type=Troll
> 
> 		controller=ai
> 
> 		recruit="Troll Whelp"
> 
> 		team_name=team
> 
> 		[ai]
> 
> 			[avoid]
> 
> 				x=9-44
> 
> 			[/avoid]
> 
> 		[/ai]
> 
> # 		[ai]
> 
> # 			[avoid]
> 
> # 				x=7-44
> 
> # 			[/avoid]
> 
> # 		[/ai]
> 
> 	[/side]
> 
> -```-
> 
> The difference in ai behavior was obvious (grabbing a village in the affected column/not grabbing it).
> 
> Marking works for me.
> 
> It also worked with ai_algorithm=

**anonymissimus changed status:** None -> Works For Me

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-25**

**beetlenaut added attachment:** [01_Rooting_Out_a_Mage.cfg](http://gna.org/bugs/download.php?file_id=14263)

**beetlenaut wrote:**

> Hmm. It still *doesn't* work for me in r51650. Could you replace the original cfg (in AToTB) with the attached file, and see what happens? When I play, the ai units, which should be restricted to the castle march right for the player unless you remove the second [avoid].
> 
> (file #14263)

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-26**

**anonymissimus wrote:**

> Reproduced with both test cases.
> 
> My former setup seems to be somehow flawed in that the areas to avoid overlap...

**anonymissimus changed status:** Works For Me -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-19**

**celticminstrel changed status:** Confirmed -> Invalid

**celticminstrel wrote:**

> The problem here is that only one of each aspect can be specified in the side's AI - in other words, you can have only one [avoid]. If you want to avoid multiple areas, you need to merge them into a single [avoid] tag. It doesn't matter how many [ai] tags you use - with a few minor exceptions, multiple [ai] tags are equivalent to stuffing everything into a single [ai] tag.
> 
> 
> 
> That's not to say that multiple [avoid] tags are useless, mind you. Each [avoid] tag stacks on a new facet, so if you want the AI to avoid one area, but halfway through the scenario they stop that and start to avoid a different area, you could use two [avoid] tags. The second tag would come into effect immediately; you could then use a [modify_ai] halfway through the scenario to remove it (with a path of aspect[avoid].facet[0] if I recall correctly), at which point the first [avoid] tag would be in effect.
> 
> 
> 
> In any case, this is not a bug but rather an misunderstanding of how the AI system works, so I'm marking this invalid.

**Comment by Wedge009** [comment]
Closing as it's marked invalid.
