### ISSUE TITLE
Debug mode can be used in Network multiplayer (GNA #18693)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1273]
**[Original submission](https://gna.org/bugs/index.php?18693)** by mkaysi on 2011-09-19

Debug mode can be used in Network multiplayer (Create units, change their sides, add gold and so on...).This causes the other side to get out of sync.

Steps to reproduce:

1. Open terminal.

2. run "wesnoth-1.9 --debug"

3. Go to official server and multiplayer.

4. In game right-click something and you can create units and change their sides and so on.

(Reproduced on Debian Sid)
Release: Battle for Wesnoth v1.9.9
Priority: 5 - Normal
Severity: 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-09-19**

**anonymissimus closed the issue**

**anonymissimus changed status:** None -> Wont Fix

**anonymissimus wrote:**

> Won't fix, since this is intended.
> 
> reasons:
> 
> -Debug mode in networked multiplayer is extremely useful for resolving OOS errors in multiplayer wml.
> 
> -Generally, people who know how to use this don't cheat.
> 
> -Most actions, mainly the most useful ones, which can be done in debug mode, cause OOS anyway.
> 
> -It is not possible to prevent cheating anyway, since people can modify and recompile the source.
> 
> -It is even easier to open a second BfW instance and load a savegame from the game one is currently playing to inspect the opponent's units, resources etc.
> 
> 
> 
> Also note that the :debug command doesn't work.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-09-20**

**sapient wrote:**

> For what it's work, I think this is a bad idea.
> 
> 
> 
> 1. Majority of players do not know how to modify and recompile the source or are using a platform where it requires extra effort (i.e. Windows)
> 
> 
> 
> 2. Although some cheat because they think they are clever, others cheat because they are just lazy. The "lazy" cheaters are unlikely to expend the effort to open a second BfW instance and load a savegame every turn, though they might try it on occasion.
> 
> 
> 
> Personally, I think connecting to any official multiplayer server with debug mode enabled should be considered a bannable offense.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-09-20**

**grickit wrote:**

> Even if we put the cheating aside for a second, there's still the matter of that this option breaks the game.
> 
> 
> 
> We should not have any official "features" or in-game-options that cause OOS. Only errors and bad WML should do that.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-09-20**

**anonymissimus wrote:**

> "We should not have any official "features" or in-game-options that cause OOS. Only errors and bad WML should do that.":
> 
> One may even desire to intentionally get OOS to test something, or need an OOS to "equalize" an already existing one.
> 
> Since I'm tired of repeating here's my arguments from the irc log:
> 
> 
> 
> 20110919 22:01:21< anonymissimus> Gambit_: no, I am 100% opposed to you here
> 
> 20110919 22:02:34< anonymissimus> error reports and savegames are much more complicated and work
> 
> 20110919 22:02:41< anonymissimus> and insufficient
> 
> 20110919 22:44:16< anonymissimus> Gambit: https://gna.org/bugs/index.php?18693
> 
> 20110919 22:44:47< anonymissimus> for active debug mode cheating, just say "we have OOS, so I can't trust my opponents in thsi game"
> 
> 20110919 22:44:59< anonymissimus> and an OOS game is screwed anyway
> 
> 20110919 22:45:18< anonymissimus> since all active debug mode cheating causes OOS
> 
> 20110919 22:46:08< anonymissimus> and for "passive" cheating it is probably more obvious to load a savegame locally from teh game I'm playing and look there
> 
> 20110919 22:46:20< anonymissimus> rather than :inspect etc
> 
> 20110919 22:47:01< anonymissimus> so, since it is that easy to cheat anyway, it doesnt make much sense to attempt to prevent it here
> 
> 20110919 22:57:09< anonymissimus> hm obs can use all debug mode functionalities
> 
> 20110919 23:08:23< anonymissimus> here's the discussion I has with silene btw: https://gna.org/bugs/?17412

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-09-21**

**mkaysi wrote:**

> But why to not setup own servers for debug tests? My logs:
> 
> 
> 
> 
> 
> 
> 
> 21:21:47        Mkaysi | I have an suggestion about this debug thing which helps both sides, players and developers.                                                                          
> 
> 21:22:14        Mkaysi | Add configuration variable for allowing of debug mode to Wesnoth server config.                                                                                      
> 
> 21:22:46       Gambit_ | Yes that would have been the right way to do this.                                                                                                                   
> 
> 21:22:52       Gambit_ | Make it so that it doesn't break the game.                                                                                                                           
> 
> 21:22:54        Mkaysi | If developers need to test their multiplayer screnarios/capmpaings/eras, they could just quickly setup their own server for debug tests.                             
> 
> 21:22:56       Gambit_ | And make it ask the server if it's okay.                                                                                                                             
> 
> 21:23:02       Gambit_ | And then our official server should say no.                                                                                                                          
> 
> 21:24:09        Mkaysi | And enabling debug could be done with :debug, why to allow one way if one way is blocked?                                                                            
> 
> 21:25:32  shadowmaster | --debug is dead easy to add to a launcher/shortcut; changing the engine behavior at the source code level is not

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-09-21**

**anonymissimus wrote:**

> Well, I don't want to be the only badass here and keep bothered with it. There should be an easy and quick way to have debug mode in networked mp imho.
> 
> A precondition for the wesnothd solution is for instance that it also works on windows and with the MSVC debugger. A first trial doesn't work.

**anonymissimus changed status:** Wont Fix -> None

**anonymissimus changed severity:** 4 - Important -> 2 - Minor

**anonymissimus reopened the issue**

**anonymissimus changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-09-21**

**anonymissimus changed severity:** 2 - Minor -> 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-18**

**grickit wrote:**

> The server should announce to everyone that one player has debug mode enabled.
> 
> 
> 
> Cheating doesn't have to be (and really can't be with this game) prevented, but you can let players know that it might be going on.
> 
> 
> 
> It can also help to explain to others why the game suddenly OOSes � because BillyBob had debug mode on and decided to make a yeti.

**grickit changed severity:** 1 - Wish -> 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-27**

**shadowmaster changed category:** Feature Request -> Bug

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-27**

**shadowmaster changed severity:** 2 - Minor -> 4 - Important

**shadowmaster changed title:** Debug mode can be used in Network multiplayer. -> Debug mode can be used in Network multiplayer

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-12-16**

**anonymissimus wrote:**

> fun fact: It is already possible to use debug mode on the official 1.8 mp server with the official 1.8 source. Just activate the new MP lobby in the preferences; this bypasses the game_config::debug = false setting the old lobby does, and you have debug mode in networked multiplayer. ;)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-03-19**

**slowthinker wrote:**

> grickit wrote:
> 
> > the game suddenly OOSes � because BillyBob had debug mode on and decided to make a yeti.
> 
> > ...
> 
> > We should not have any official "features" or in-game-options that cause OOS. Only errors and bad WML should do that.
> 
> 
> 
> Such OOS is not a problem of the debug mode: The yeti creation should not cause OOS, it should be rather distributed to other clients, like any other player's action.
> 
> But I fully agree the server should announce if someone uses the debug mode.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-07**

**gfgtdf changed status:** None -> Fixed

**gfgtdf wrote:**

> Fixed in https://github.com/wesnoth/wesnoth/commit/c605f07a36af185cc070bed661e806c674adfeaf and other commits in 1.13.1+dev
> 
> 
> 
> Debug commands liek :unit or :lua are now synced and dont casue OOS. Also the game now announces if a debug command is used.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-08**

**slowthinker wrote:**

> also it should warn that a player joins a game with debug set to on.
> 
> {With 'debug on' a detailed info about enemy sides (gold ...) is accessible.)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-08**

**anonymous wrote:**

> Hmm maybe that could be useful but note that there are other more easy ways to cheat. The most known is to save the game and then to open it in a seperate wesnoth client.
> 
> 
> 
> Another thing you could do is a use a mp modification to detect clients that use debug mode.
> 
> Untested code:
> 
> ```
> 
> [modification]
> 
> 	id = detect_debug
> 
> 	name = _ "Detect Debug"
> 
> 	description = _ "Adds a menu item to check which players have debug mode active"
> 
> 	[event]
> 
> 		name = "prestart"
> 
> 		[set_menu_item]
> 
> 			id = "detect_debug"
> 
> 			description = "Detect Debug"
> 
> 			[command]
> 
> 				[lua]
> 
> 				code = <<
> 
> 					wesnoth.set_variable("debug_active", value)
> 
> 					wesnoth.wml_actions.set_global_variable {
> 
> 						namespace = "detect_debug",
> 
> 						to_global = "debug_active",
> 
> 						from_local = "debug_active",
> 
> 						side = "global",
> 
> 						immediate = true,
> 
> 					}
> 
> 					wesnoth.set_variable("debug_active")
> 
> 					local text = ""
> 
> 					for k, side in ipairs(wesnoth.sides) do
> 
> 						if side.controller ~= "null" then
> 
> 							wesnoth.wml_actions.get_global_variable {
> 
> 								namespace = "detect_debug",
> 
> 								to_global = "debug_active",
> 
> 								from_local = "debug_active",
> 
> 								side = side.side,
> 
> 								immediate = true,
> 
> 							}
> 
> 							text = text .. "Side " .. side.side .. " has debug mode on: " .. wesnoth.get_variable("debug_active") .. "\n"
> 
> 							wesnoth.set_variable("debug_active")
> 
> 						end
> 
> 					end
> 
> 					wesnoth.message(text)
> 
> 				>>
> 
> 				[/lua]
> 
> 			[/command]
> 
> 		[/set_menu_item]
> 
> 	[/event]
> 
> [/modification]
> 
> 
> 
> ```

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-08**

**anonymous wrote:**

> ofc the line
> 
> 
> 
> wesnoth.set_variable("debug_active", value)
> 
> 
> 
> should become
> 
> 
> 
> wesnoth.set_variable("debug_active", wesnoth.game_config.debug)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-29**

**shadowmaster wrote:**

> gfgtdf: Please don't forget about making the warnings stick around for longer.

**shadowmaster changed status:** Fixed -> In Progress

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-23**

**gfgtdf wrote:**

> you mean just inclising the time they are shown?

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/commit/92cd7fee255ac4bf0d08f24ab46ad1bdd5914898 made the marking stck around longer.
