### ISSUE TITLE
Bridge to Castle over Chasm transitions are off (GNA #18873)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1274]
**[Original submission](https://gna.org/bugs/index.php?18873)** by sigurdthedragon on 2011-10-27

Attached is a jpg showing the occurances over a variety of types of bridges, chasms, and keeps. They occur in the / and \ directions.

(Reproduced on Win 7 x64)
Release: r51685
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-27**

**sigurdthedragon added attachment:** [Bridge-Castle-Chasam_Transitions.jpg](http://gna.org/bugs/download.php?file_id=14298)

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-27**

**alarantalara changed status:** None -> In Progress

**alarantalara wrote:**

> Dwarven castles rely on a different macro that does not allow for the layering to appear properly. Further, since the associated images are bound to the walls, the dwarven castle requires redrawing (image cutting) to fix. Expect it to take rather longer.

**Comment by Wedge009** [comment]
I note the dwarf castle to bridge transition is still off as of 1.14.0

**Comment by sevu** [comment]
![mainline](https://user-images.githubusercontent.com/21158813/39945373-88f21872-556a-11e8-9eb9-fc68cba6b0ac.png)
Wit the redesigned map for Northern Rebirth we have this in mainline. (Scenario 2)

**Comment by Wedge009** [comment]
Well-spotted - it's somewhat mitigated by the shroud in this level, I didn't notice this in my play-through of the new level designs.

**Comment by Wedge009** [comment]
I happen to be replaying Northern Rebirth S02 at the moment (1.14.17), the above issue is no longer present but only because it appears the castle tiles were removed. I'm looking at hex 35,5 specifically - the bridge seems to look better than with the castle tiles but the transition still looks a bit abrupt.

**Comment by Wedge009** [comment]
Wesnoth 1.16.8 release:
![image](https://user-images.githubusercontent.com/13679322/222995173-8ccb28d5-2a3a-467e-879b-dc9ebdd50e1c.png)

Not sure if it makes sense to make a bridge up to the walls of a castle, but I think this looks reasonable especially compared with the transitions in older versions. Of course, feel free to re-open if there are still jarringly bad transitions.
