### ISSUE TITLE
Help markup breaks in stuff where Pango markup is enabled (GNA #18730)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1276]
**[Original submission](https://gna.org/bugs/index.php?18730)** by espreon on 2011-09-24

Help markup breaks in stuff where Pango markup is enabled(example: sidebar tooltips). And yes, help markup used to function fine in those areas.

I'll whip up a nice testcase soon.

(Reproduced on Sabayon Linux)
Release: 1.9.9+svn (51283)
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-09-24**

**espreon wrote:**

> OK, I made that testcase.
> 
> 
> 
> Tarball: http://wesnoth-umc-dev.svn.sourceforge.net/viewvc/wesnoth-umc-dev/branches/testing/trunk/Bug18730/?view=tar
> 
> 
> 
> svn: https://wesnoth-umc-dev.svn.sf.net/svnroot/wesnoth-umc-dev/branches/testing/trunk/Bug18730
> 
> 
> 
> Just start the scenario, select the Blessed One, hover the cursor over his unit type name in the sidebar, and behold.

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-11-01**

**mordante wrote:**

> Somebody decided it was a good idea to convert the reporting area to pango, which causes this issue. Fixing it properly will probably some work and I won't have time to fix it soon. The other option is to revert the whole stuff, but that will probably also be a lot of work.
> 
> 
> 
> Since I don't have time, nor interested in cleaning up this mess I leave the bug unassigned for now.

**mordante changed status:** None -> Confirmed

**Comment by Wedge009** [comment]
I'm not sure what is meant by this. Does anyone have an example of where this 'help mark-up' is broken 'where pango mark-up is enabled'?

**Comment by CelticMinstrel** [comment]
I don't have an example of somewhere this actually occurs, but it sounds like this person used to use help markup in the text for tooltips on the sidebar, such as in traits descriptions. If traits use the same description both in the sidebar and in the help, I can certainly see how that could happen.

If it's truly an issue, there's a function on the help branch that converts help markup to Pango, so that could be imported to master and used in such places.

**Comment by Wedge009** [comment]
Hmm, sounds like this one needs to be kept around for a bit longer then, until we're sure we've resolved this mixed mark-up issue.

**Comment by gfgtdf** [comment]
> Hmm, sounds like this one needs to be kept around for a bit longer then

i don't think so,from looking at the first post the help markup in sidebar tooltips worked last in 1.8 and i don't see a point in adding a backwards compbality path for that.

**Comment by Wedge009** [comment]
Oh, so we're just using pango mark-up now?

Happy to take your judgement on that!

**Comment by CelticMinstrel** [comment]
The only reason to add a compatibility path would be if the same string is used both for help and tooltips... which I think might not be the case? Don't traits for example have separate descriptions for help and tooltips?
