### ISSUE TITLE
Team colors on unit names in messages? (GNA #18800)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1277]
**[Original submission](https://gna.org/bugs/index.php?18800)** by coffee on 2011-10-09

I noticed that it can be difficult to determine which team is talking in scenarios with many sides and even with few sides for new scenarios to the player.

My idea is to color the name of the unit in messages with the team color to help differentiate this. I am referring to messages via the standard [message] WML tag.

(Reproduced on Any)
Release: 1.9.9
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-10**

**anonymissimus changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-13**

**shadowmaster wrote:**

> I somehow doubt that will work very well with the darker TC colors, especially black. Was there any forum discussion about this before?

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-11-25**

**simon_smith wrote:**

> Perhaps use the team flag as a side indicator?

**Comment by jostephd** [comment]
For the record: campaign authors can get around this easily by doing [select_unit] before [message] so the speaker's details, including side flag, appear in the sidebar.

**Comment by CelticMinstrel** [comment]
Isn't `[message]` supposed to do that automatically?

**Comment by jostephd** [comment]
Yeah, I was confused because I remembered 12d0d65e955d63530735ebeb2f3106309f97a077.
