### ISSUE TITLE
on-map units disappear when loading a save from linger mode (GNA #18827)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1279]
**[Original submission](https://gna.org/bugs/index.php?18827)** by anonymissimus on 2011-10-20

Introduced in r41649, due to removed saving of on-map units in play_controller::to_config(). All units are on the recall list instead which somehow leads to them not getting lost when proceeding to the next scenario (was fix for bug #15545).

Other bugs in the series are bug #15545, bug #16111 and possibly bug #15226.

(Reproduced on win xp)
Release: trunk r51547
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-10-20**

**anonymissimus wrote:**

> also bug #18828

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-15**

**gfgtdf wrote:**

> THere were some changes related to this, merking as ready to test

**gfgtdf changed status:** None -> Ready For Test

**Comment by Vultraz** [comment]
Just tested loading a linger mode save, all units are present.
