### ISSUE TITLE
allow whiteboard to be enabled per side (GNA #19140)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1284]
**[Original submission](https://gna.org/bugs/index.php?19140)** by anonymissimus on 2011-12-08

Played Isar's cross with 2 allied sides per client. A client controlling 2 sides can't independently activate/deactivate wb for his sides (this is possible with DSU).

(Reproduced on any)
Release: trunk r52196
Priority: 3 - Low
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2011-12-09**

**soliton changed category:** Bug -> Feature Request

**soliton changed OS:** win xp -> any

**soliton changed title:** wb active option in right click menu shared between sides -> allow whiteboard to be enabled per side

**soliton changed severity:** 3 - Normal -> 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-01-06**

**gabba wrote:**

> Thanks for the suggestion, please assign whiteboard stuff to me though.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-04-22**

**gabba changed priority:** 5 - Normal -> 3 - Low

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-04-22**

**gabba changed status:** None -> Confirmed

**Comment by Pentarctagon** [comment]
Maybe I'm missing something, but this doesn't seem to make any sense.  What is the use case for enabling whiteboard for only one side of a two-side team where you control both allied sides?

**Comment by CelticMinstrel** [comment]
@anonymissimus seems to be the original submitter.

**Comment by Wedge009** [comment]
I'm also puzzled by this one. I thought it's pretty straightforward to toggle planning mode via default hot-key 'p'.
