### ISSUE TITLE
terrain graphics ambiguity (GNA #19238)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1286]
**[Original submission](https://gna.org/bugs/index.php?19238)** by slowthinker on 2012-01-03

I believe that terrain with different movecost/defense should be very clearly distinguished, without a need to concentrace on the graphics, and even in a fog.

With 1.9 these new problems arose:

* deep water, shallow water and ford are too similar

next terrains were much better distinguished in 1.8. True, people could edit their maps and replace 'Rd' and 'Re' by other flat terrain, but that would be a somewhat painful solution:

* sand terrains are similar to 'Rd' (Dry Dirt)

* cave terrains are similar to 'Re' (Regular Dirt)

Next ambiguities are inherited from 1.8:

* Impassable Mountains are similar to Mountains (maybe the fog in these hexes should be dark, so that all impassable terrains use a lot of black)

* the village 'Uu^Vud' is hard to find in caves 

** (a sidenote: maybe all villages should have a common graphical point: when I was a noob I considered a Mill to be a village)

* 'Uu' and 'Uh' are similar sometimes (it looks there are two graphical types of 'Uh', and the one with less points is similar to 'Uu')

* 'Ur' should be slightly better distinguished form other cave terrains. ('Ur' could be replaced by another flat terrain in maps, but it would affect the atmosphere in caves)

(Reproduced on any)
Release: 1.9.3
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by nemaara** [comment]
With updated graphics, this should no longer be the case.
