### ISSUE TITLE
Chat log should show latest messages, not oldest (GNA #19320)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1290]
**[Original submission](https://gna.org/bugs/index.php?19320)** by ancestral on 2012-01-23

When opening the chat log it always displays the oldest messages. This is very inconvenient.

Better would be to show the newest messages, by having the chat box scrolled all the way down before showing the chat log.

(Reproduced on any)
Release: trunk
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-12-06**

**fit1 wrote:**

> Hey guys.. I am trying to fix this bug for a college project. Any leads on where to begin or which '.cpp' will have the username.
> 
> 
> 
> I tried to fix it by changing few lines. But didn't work. WOuld love some help.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-10-24**

**vultraz wrote:**

> Should finally be fixed here: https://github.com/wesnoth/wesnoth/commit/b89731c7ac48ead261217aa7f532e37d8870d113 Wasn't able to test since one would need to play an mp game.

**vultraz changed status:** None -> Ready For Test

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-10-24**

**vultraz changed status:** Ready For Test -> In Progress

**vultraz wrote:**

> Ok, that did not fully fix it. I improved the situation here: https://github.com/wesnoth/wesnoth/commit/d8027de68fe645ac394d29ad6f579c5f31675da2 but that doesn't fix the scrollbar position on first run... will have to investigate further.
> 
> 
> 
> The invalidate_layout calls were in order to recalculate size if the initial page was less than max height. However, they also reset the scrollbar position to the top. Now that I've made the dialog fixed-size as well, these calls are redundant. Dropping them fixes the scroll-to-bottom behavior for paging and filtering, just not the initial run.

**Comment by Wedge009** [comment]
No update in 3 years, guessing it's not actively in progress right now...

**Comment by Wedge009** [comment]
Is 'chat log' supposed to be recent messages in the MP lobby chat window? In 1.14.x I don't see anything in the chat log other than the initial server messages - my assumption is that anything that might have been said previously is not shown upon entering. Was it shown in previous iterations of the lobby? (I think 1.12 and earlier.)

**Comment by Wedge009** [comment]
Closing in favour of #9211.

**Comment by Wedge009** [comment]
That's my understanding.
