### ISSUE TITLE
Hex tile with active unit is not highlighted anymore (GNA #19416)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1292]
**[Original submission](https://gna.org/bugs/index.php?19416)** by anonymous on 2012-02-05

When you have a lot of units on adjacent hex tiles (and cannot follow the footsteps to the unit easily) it's hard to locate the active unit. That already was hard enough in older versions of wesnoth when the tile was highlighted. In 1.10 the tile with the active unit is not highlighted anymore. That makes it much more difficult to locate the unit in such a case.

(Reproduced on linux)
Release: 1.10
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-17**

**shadowmaster wrote:**

> If you can see the golden frame, then this is working as intended.
> 
> 
> 
> See also: http://forums.wesnoth.org/viewtopic.php?p=441417#p441417
> 
> 
> 
> If you have a better proposal, you might want to post it in the Ideas forum so it can be discussed with the art people.

**shadowmaster changed status:** None -> Invalid

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-19**

**anonymous added attachment:** [s.png](http://gna.org/bugs/download.php?file_id=15168)

**anonymous wrote:**

> Unfortunately the solution which is shown at the end of the referenced thread has not been implemented (or does not work like it's proposed there). The golden frame does not mark the position of the active unit. In version 1.10 it marks the position of the mouse cursor. If the golden frame actually would mark the active unit the problem would be solved.
> 
> The image http://forums.wesnoth.org/download/file.php?id#42933&modeview in the referenced thread perfectly shows the regression. On the left side (the picture from version 1.8.x) you can see which unit is active. But in the middle picture (which looks like it is from version 1.10) you hardly can see which unit is active.
> 
> Also look at the attached screenshot. The selected unit really should be easier to spot.
> 
> (file #15168)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-19**

**anonymous wrote:**

> As a proposal for a better solution:
> 
> - highlight the hex with the active unit
> 
>   (as it was done in version 1.8)
> 
> - use the golden frame to mark the active unit,
> 
>   i.e. draw it around the hex with the active unit
> 
>   (and keep it there, don't move it with the cursor)
> 
> - the golden frame is not needed to find your cursor,
> 
>   that's what your cursor arrow is for, highlighting
> 
>   the target hex under the cursor (as it was done in
> 
>   previous versions) is completely enough

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-19**

**shadowmaster changed category:** Bug -> Feature Request

**shadowmaster changed status:** Invalid -> None

**Comment by CelticMinstrel** [comment]
Looking at the screenshot, I think this bug is addressed? Not 100% sure, though.

**Comment by Wedge009** [comment]
I think the original requester wants a highlight on the tile the active unit is positioned. The best 1.8 screenshot I could find to describe this is https://www.wesnoth.org/images/sshots/wesnoth1.8-4.jpg.

For 1.10 the tile highlight was replaced with a unit highlight (reference: https://www.wesnoth.org/images/sshots/wesnoth-1.10-4.jpg) - while I'm not bothered by the change I suppose it could be difficult for people to distinguish the active unit (there are 'high contrast UI themes' for a reason, I suppose).

So is this issue addressed? I'd say no. Is this a change we want to make? Personally I'm not so sure - and given we don't know the original requester I'm wondering if this should be closed.

**Comment by jostephd** [comment]
Nowadays one can identify the active unit by turning ellipses off (Ctrl+E), as that turns off all ellipses except the selected unit's. I guess this can be closed (if someone finds the current situation unsatisfactory we can always reopen).

**Comment by Wedge009** [comment]
I never really tried that before because I never had this problem. But I notice that when moving a unit the active unit tile is 'highlighted' by virtue of every other tile being shaded anyway. But you're right, disabling ellipses means only the active unit ever has an ellipse, making it really easy to see which is the active unit.

Closing unless someone really insists on this still being an issue.
