### ISSUE TITLE
Feature request: In the recall window, sorting by XP should sort by percentage (GNA #19431)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1294]
**[Original submission](https://gna.org/bugs/index.php?19431)** by laza on 2012-02-07

Playing "The South Guard", 2nd mission:

First i drilled some new units for first strike, than i began to draft units from the first mission:

- I sort descending after "EP" but misleadingly a peasant (Bauer) with 2/23 EP, Level 0 is first in order, followed by a Spearman/Spearthrower (Speerträger) with 8/34 EP, Level 1.

- sortation ascending leads to:

1st Watermanhunter (Wassermannjäger) Level 1, 0/35 EP

2nd Bowman (Bogenschütze) Level 1, 4/39 EP

3rd Seaservant (Seeknecht) Level 1, 0/29 EP

4rd Spearthrower (Speerträger) Level 1, 7/34 EP

It is completly mixed up and anusable!

I added the relevant savegames.

(Reproduced on Windows 7 SP1)
Release: 1.10.0
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-07**

**laza added attachment:** [DS-Die_Pr�fung_des_Schwertes-Autospeichern4.gz](http://gna.org/bugs/download.php?file_id=15031)

**laza added attachment:** [preferences](http://gna.org/bugs/download.php?file_id=15032)

**laza added attachment:** [DS-Die_Pr�fung_des_Schwertes.gz](http://gna.org/bugs/download.php?file_id=15029)

**laza added attachment:** [DS-Die_Pr�fung_des_Schwe..._Runde_4_-_Bug.gz](http://gna.org/bugs/download.php?file_id=15030)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-07**

**max2008 wrote:**

> see here:
> 
> https://gna.org/bugs/?func#detailitem&item_id14486

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-08**

**max2008 wrote:**

> i guess adding tooltips here would be nice

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-08**

**laza wrote:**

> It is not exactly the same like #14486.
> 
> 
> 
> For me it should sorted by the ratio between X and Y in X/Y (IMHO) or give the % till the unit reaches the next level.
> 
> It doesn't matter which level the unit is!

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-08**

**max2008 wrote:**

> just tried your save game. it's exactly as described in #14486. the units get sorted by experience needed to level up.
> 
> 
> 
> > - sortation ascending leads to:
> 
> > 1st Watermanhunter (Wassermannj�ger) Level 1, 0/35 EP
> 
> > 2nd Bowman (Bogensch�tze) Level 1, 4/39 EP           
> 
> > 3rd Seaservant (Seeknecht) Level 1, 0/29 EP
> 
> > 4rd Spearthrower (Speertr�ger) Level 1, 7/34 EP
> 
> 
> 
> 1: needs 35 xp
> 
> 2: needs 35 xp
> 
> 3: needs 29 xp
> 
> 4: needs 27 xp
> 
> 
> 
> (there are two more units in you recall list. nr 5 needs 26 xp, nr 6 21 xp).
> 
> 
> 
> yes, it's confusing - but imo it's better than sorting it by %. at least if you're looking for units that are fast to level up (a lvl 2 unit that needs 20% takes much longer to level up than a lvl 1 unit with 40%).

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-08**

**laza wrote:**

> Thanks for your explanation, Max!
> 
> 
> 
> But for me, it is much more helpful they are sorted by %.
> 
> I think about the units i would need and then start with:
> 
> - recalled units with low XP who will level up in the mission (prossibly)
> 
> - recalled units with high level to kill on the first/second strike, who will survive many attacks
> 
> - recalled units, which will maybe fall but have the chance to level up after two/three rounds and are completely healed
> 
> 
> 
> I prefer the third possibility, which i want to suggest.
> 
> 
> 
> The difference to the next level is shown by the color of the XP from blue to white (or is this not in the recall window?)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-23**

**anonymissimus changed category:** Bug -> Feature Request

**anonymissimus wrote:**

> Well, changing into feature request then. Max, pls complain if something else here needs to be done.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-02-23**

**anonymissimus changed priority:** 5 - Normal -> 3 - Low

**Comment by jostephd** [comment]
**Summary:** This is a feature request to make the recall window when sorted by XP sort by percentage, for example, a unit with 20/40XP and a unit with 30/60XP should sort equal. Currently it's sorted by experience to advance (`max_experience - experience`).

**Comment by soliton-** [comment]
IMO it's fine as is. I think it's more important to find units that need a specific amount of XP to level, i.e. how many (level 1) kills it needs to level, no matter what level the unit itself is.

If there is a simple way to support both that'd be fine but otherwise I'd leave this as it now is.

**Comment by GregoryLundberg** [comment]
I've never really been happy with how it sorts "By XP" but I've also never come up with how I'd rather have it sort.

Generally, I start my recall phase by purging any level 1 units which are not __very__ close to level 2. For many units, it's not worth the coin to recall them if they have no (or very little) XP; it's cheaper to simply recruit a new unit. So I purge them to avoid making a mistake.

One thing I don't want is sorting solely on XP. a 30/60 L1 should not sort above a 20/40 L2 unit. Maybe that's what I couldn't remember.

**Comment by jostephd** [comment]
Come to think about this, why is it useful at all to sort by "XP percentage"? Isn't that basically [the sunk cost fallacy](https://en.wikipedia.org/wiki/Sunk_cost#Loss_aversion_and_the_sunk_cost_fallacy)? There is no a practical difference between a Red Mage with 90/100XP and one with 990/1000XP (assuming they have the same traits and will have the same XP requirement when they advance to lvl3), so they should sort equal. That is exactly how it works now:

https://github.com/wesnoth/wesnoth/blob/0379e2e8329b62dce6d4a7723641cba673c66740/src/gui/dialogs/unit_recall.cpp#L237-L240

What I think might work is to add the unit's `max_experience` as a tie breaker between units that have equal `experience_to_advance()`. This way, if you have, say, a Mage with 43/53XP and an Orcish Assassin with 24/34XP, the Mage will sort higher, which is probably sensible since units with higher XP requirements tend to advance into more powerful forms.

**Comment by AI0867** [comment]
Well, a 40/80 XP unit that costs 16 gold might be worthwhile to recall, but a 0/40 XP unit that costs < 20 gold is useless, unless you really need that combination of traits.

At the same time, any unit that costs >= 20 gold is worth keeping around.

So it's not just the "but this unit already has this much XP", but the "an equivalent unit would be this amount of XP behind".

There are various considerations here that we should formalize if we want the best possible sorting system.

**Comment by jostephd** [comment]
> There are various considerations here that we should formalize if we want the best possible sorting system.

I'm not trying to come up with the best possible sorting system. I'm just trying to come up with an improvement over the current system. In your 40/80XP and 0/40XP example, adding `max_experience` as a tiebreaker (`std::make_tuple(u.level(), -static_cast<int>(u.experience_to_advance()), u.max_experience())`) would sort the 40/80XP unit higher, which would be an improvement, I think? Maybe there's an even better solution that takes recall cost, recruit cost, and recruit list into account, but that might be more complicated, and I don't want the best to be the enemy of the good... and in the end, it's not like having two units of equal level and equal experience_to_advance() is very common.

**Comment by Wedge009** [comment]
I also prefer sorting by XP-to-next-level rather than by percentage. If possible I would think it would also be nice to group those assortments by level, but that's beyond the scope of this particular request, I think.

**Comment by jostephd** [comment]
> If possible I would think it would also be nice to group those assortments by level,

It's possible and that's how it works currently, isn't it? Units are sort first by level and second by experience to advance (= max_experience minus experience).

**Comment by Wedge009** [comment]
Hmm, possibly. I might not have played 'seriously' since 1.12 so I don't have any suitable save files on hand to check but I remember being frustrated by the XP sorting back then. It might have improved by now.

Regardless the question is what to do with this, given it sounds like we prefer to keep things as they are, ie _not_ using percentage to sort XP.

**Comment by jostephd** [comment]
> Hmm, possibly. I might not have played 'seriously' since 1.12 so I don't have any suitable save files on hand to check but I remember being frustrated by the XP sorting back then. It might have improved by now.

I didn't have savefiles either, so I opened the Lua console and did `wesnoth.create_unit({type='Mage', experience='44'}):to_recall()` a few times, and dismissed the intelligent mages afterwards.

> Regardless the question is what to do with this, given it sounds like we prefer to keep things as they are, ie _not_ using percentage to sort XP.

Yeah. There seems to be consensus that it's fine as it is now. I don't think @AI0867 disagreed with that (do correct me if I'm wrong), so let's close.
