### ISSUE TITLE
Remove [item] image size limitation (GNA #19502)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1295]
**[Original submission](https://gna.org/bugs/index.php?19502)** by anonymous on 2012-02-27

Situation: 

- Currently, size of regular item images are limited within the hex mask. 

Suggestion: 

- Release this limitation as was similarly seen with unit image and halos. 

This idea has been briefly discussed with shadowmaster before ticket submission.

Thanks,

Battlestar

(Reproduced on Windows)
Release: 1.11.x or later
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Wedge009** [comment]
Closing in favour of #6118.
