### ISSUE TITLE
Restore window properties (GNA #19514)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1296]
**[Original submission](https://gna.org/bugs/index.php?19514)** by fphoenix on 2012-02-29

I think, it will be better, if game memorise it's window state when switching to full screen and restore it when switching back.

(Reproduced on WinXP)
Release: 1.10.1
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Vultraz** [comment]
This is currently the behavior.
