### ISSUE TITLE
Giant Scorpion has Mudcrawler resists (GNA #19596)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1299]
**[Original submission](https://gna.org/bugs/index.php?19596)** by anonymous on 2012-03-28

I just noticed that this known bug doesn't seem to exist in the tracking system. The Giant Scorpion has the same movetype as the Mudcrawler, which makes some sense, but consequently has the same resistances, which doesn't.

See the first few posts in this thread for developer agreement that this is a bug: http://forums.wesnoth.org/viewtopic.php?f=15&t=20564

The consensus seems to be that the resistances should be the same as the giant spider (currently 20% to arcane, 0% other). There is also some discussion of whether the giant spider resistances should be tweaked, but the major discrepancy at present are the scorpion's resistances (resists impact more than skeletons resist arrows, and -100% fire resistance compared to the standard biggest vulnerabilities of -50% of Woses to fire or Drakes to cold).

(Reproduced on Windows 7)
Release: 1.10
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-03-29**

**anonymissimus wrote:**

> Scorpions are widely used as some "unusual monsters to bother the player and hold him off for a while" in various campaigns so changing something here may unbalance quite some scenarios.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-03-29**

**anonymous wrote:**

> You're right. This means that there is a transition cost to changing the resistances, as some campaigns may need to rebalance slightly (but campaign balance is normally not very precise to begin with).
> 
> 
> 
> If Wesnoth were only going to be around in the short term, I think that would be enough of a reason not to change the resistances. I think the game is likely to have a long and healthy future, though, and that it's better to get this change in earlier. Almost all resistances in the game make some sense. The giant scorpion's make almost no sense whatsoever (which hasn't stopped people occasionally trying to give post-hoc justifications for them), and this breaks suspension of disbelief.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-03-29**

**anonymissimus changed category:** Bug -> Feature Request

**Comment by nemaara** [comment]
Scorpions are indeed used in many campaigns and altering their resists may change balance, so I'm thinking of handling this for 1.15.0 by changing the resists to be the same as a standard mundane unit (20% arcane, 0 otherwise). Putting it in the dev cycle should give people time to rebalance while porting their campaigns, and for us to modify mainline campaigns if necessary.

**Comment by doofus-01** [comment]
If the resistances matter a lot, we can make a variation with small base-frame alterations, a "Mud Scorpion" or something.  It will make it easier to port older UMC to 1.15 and diversity in the Wesnoth bestiary isn't a bad thing anyways.

**Comment by CelticMinstrel** [comment]
I seem to recall thinking a fire vulnerability makes a lot of sense for them though...

**Comment by jostephd** [comment]
@CelticMinstrel For what kind of reason, lore or balance?

**Comment by nemaara** [comment]
> If the resistances matter a lot, we can make a variation with small base-frame alterations, a "Mud Scorpion" or something. It will make it easier to port older UMC to 1.15 and diversity in the Wesnoth bestiary isn't a bad thing anyways.

I was thinking something like a "sand scuttler". I can tweak the frames a little bit to make it if necessary as well.

**Comment by CelticMinstrel** [comment]
You should generally assume that any suggestions from me come from a position of lore, not balance.

I don't guarantee that my thoughts on this matter were properly justified though.

**Comment by nemaara** [comment]
See #4015.
