### ISSUE TITLE
Modal dialog causes a side's control is problematic (GNA #19625)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1301]
**[Original submission](https://gna.org/bugs/index.php?19625)** by slowthinker on 2012-04-08

In a MP game that runs on a MP server, a modal dialog may cause errors if it is open when host passes side's control to another player.

How to reproduce:

1. Start a 2p game on a MP server, side1: player1 (host), side2: player2.

2. During side1's turn player2 pauses his client by opening a dialog

3. Player1 ends his turn

4. Player1 takes control of side2: ':control 2 player1'. 

He gets a message "it is now player1's turn" 

5. Player2 closes the dialog. 

He gets a message "it is now player2's turn"

Both players get a message '<server> Removing illegal command 'init_side' from: player2. Current player is: player1.'

In the case above the game may continue probably,

but I encountered also cases where player2 was able to end turn of side2 and to continue to play. Then error messages continued with any action (like 'Removing illegal command 'end_turn' ') .

(Reproduced on Win XP Pro)
Release: 1.10.1
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by gfgtdf** [comment]
Yes this is a known issue, if the host takes control from a player that is likeley to casue OOS for that player, it's reccomended that that player leaves and reenters the game to prevent that OOS.

**Comment by gfgtdf** [comment]
this is s dublicate of #1586
