### ISSUE TITLE
Untranslateable sides in campaigns (GNA #19660)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1302]
**[Original submission](https://gna.org/bugs/index.php?19660)** by fphoenix on 2012-04-25

The side names in all or most of campaigns can't be translated. Even if side have same name as it's leader, his name will be translated, but not side.

[Attached examples from "Liberty"]

(Reproduced on WinXP)
Release: 1.10.2
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-04-25**

**fphoenix added attachment:** [sides-hint.jp2](http://gna.org/bugs/download.php?file_id=15622)

**fphoenix added attachment:** [sides-status-table.jp2](http://gna.org/bugs/download.php?file_id=15621)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-04-26**

**fphoenix wrote:**

> By the way, as seen in the first picture, the translated dialog tabs vary in width. Maybe it would be better to change this behavior by setting the maximum needed width to both of them?

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-02**

**jamit wrote:**

> Marked bug #21740 as a duplicate of this.

**jamit changed category:** Feature Request -> Bug

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-08**

**wedge009 wrote:**

> I had a look at leader_scroll_dialog.cpp and it seems the team (or side) name is not translated. For at least the reason described in bug #14654 (which this is arguably related to). So any reasons for bug #14654 to be left alone also applies to this one.

**Comment by Wedge009** [comment]
Link to #1175

**Comment by Wedge009** [comment]
Same as for #1175, testing in Russian shows the side name is translated.
