### ISSUE TITLE
Screenshot indexer bug on Windows (and translation of its filenames) (GNA #19665)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1303]
**[Original submission](https://gna.org/bugs/index.php?19665)** by fphoenix on 2012-04-26

There was bug with incorrect encoding until 1.10.2 version (#19425). In 1.10.2 encoding was normalized, but now game can't set normal index to Cyrillic filenames and always overwrite zero-screenshot (000). Only under Windows, and only when using translation.

By the way, it's too bad that string "Screenshot" is shared in translation, i.e. used for both - hotkey list and part of filename:

|| WESNOTH-LIB.POT

|| #: src/hotkeys.cpp:67 src/hotkeys.cpp:1179

|| msgid "Screenshot"

|| msgstr ""

In Russian language it's normally translating with 2 words (like "screen shot"; we use an Anglicism too, but it's just a jargon), but translators can't choice a splitting character between this words and index, and summary name seems like "screen shot_000.bmp".

So I think, it will be much better, if you change this lines in hotkeys.cpp (for example):

|| std::string name = map_screenshot ? _("Map-Screenshot") : _("Screenshot");

|| std::string filename = get_screenshot_dir() + "/" + name + "_";

to

|| std::string name = map_screenshot ? _("Map-Screenshot_") : _("Screenshot_");

|| std::string filename = get_screenshot_dir() + "/" + name;

(Reproduced on Windows XP)
Release: 1.10.2
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-04-26**

**fphoenix wrote:**

> i.e. to
> 
> ```
> 
> std::string name = map_screenshot ? ("Map-Screenshot_") : ("Screenshot_"); 
> 
> std::string filename = get_screenshot_dir() + "/" + name;
> 
> ```

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-04-26**

**shadowmaster wrote:**

> The second part of this report should really have been a feature request in a new tracker issue instead; regardless, I'll address it here for now.
> 
> 
> 
> What you suggest is that we let translators choose an appropriate filename component separator for their language? Because it seems to me like a better approach would be for them to be able to translate a proper format string like the following:
> 
> 
> 
> "Screenshot_$number"
> 
> "Map-Screenshot_$number"
> 
> 
> 
> This way they could also choose whether $number (which is replaced at runtime by the actual screenshot number) should go in front or at the end of the label.
> 
> 
> 
> By the way, when citing source code it's better that you don't change it in the post. For example, ("Foo") (a non-translatable string) is not the same as _("Foo") (a translatable string).

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-04-26**

**fphoenix wrote:**

> I agree about variable, but just decided to post the easiest variant as example, that i see how to do.
> 
> 
> 
> And yes, bad citing - just I didn't know about tags on this tracker, and it turned underline characters to italic formatting. I don't see preview and edit buttons here, so it's not easy for me to make good post from first attempt :)
> 
> 
> 
> *hotkeys.cpp*
> 
> Current code:
> 
> ```
> 
> std::string name = map_screenshot ? _("Map-Screenshot") : _("Screenshot");
> 
> std::string filename = get_screenshot_dir() + "/" + name + "_";
> 
> ```
> 
> Proposed code:
> 
> ```
> 
> std::string name = map_screenshot ? _("Map-Screenshot_") : _("Screenshot_");
> 
> std::string filename = get_screenshot_dir() + "/" + name;
> 
> ```

**Comment by Pentarctagon** [comment]
Is this still occurring?

**Comment by Wedge009** [comment]
I'm not sure if I've ever used the internal screen capture feature before, nor do I normally have non-ASCII characters in my file names (although a few campaign scenario names have such characters such as 'Talking to Tyegëa' from Dead Water). fphoenix doesn't appear to be a member here and looks like @irydacea was the only one to respond to them on Gna.

**Comment by irydacea** [comment]
@kabachuha or @loonycyborg might be able to check since they use Russian, especially the former since he's the translation maintainer  right now.

**Comment by kabachuha** [comment]
It works fine both with single or multiple localized (Cyrillic) words on 1.14.
<details>

![изображение](https://user-images.githubusercontent.com/14872007/133069948-d311f408-e2d6-48c5-a7e1-df93234578f6.png)

</details>
