### ISSUE TITLE
Doubled confirmation window (GNA #19674)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1304]
**[Original submission](https://gna.org/bugs/index.php?19674)** by fphoenix on 2012-04-29

When I tried to connect official server under a nickname, that already in game, first time I see the simple confirmation dialog  (screenshot 1), without any fields to change the nick - only Ok and Cancel buttons (and it's also untranslatable). If i press Ok, then I simply enter server, but if I press Cancel, the second dialog (screenshot 2) with login options is shown.

And I think, it will better without first of this windows.

(Reproduced on WinXP)
Release: 1.10.2
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-04-29**

**fphoenix added attachment:** [double-connect-en-2.jp2](http://gna.org/bugs/download.php?file_id=15639)

**fphoenix added attachment:** [double-connect-en-1.jp2](http://gna.org/bugs/download.php?file_id=15638)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-02**

**max2008 wrote:**

> could you use jpg/png instead of jpg2000 files? there's no browser/os with native support (without installing plugins/viewers)...

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-02**

**fphoenix added attachment:** [double-connect-en-2.jpg](http://gna.org/bugs/download.php?file_id=15658)

**fphoenix wrote:**

> Ok
> 
> (file #15657, file #15658)

**fphoenix added attachment:** [double-connect-en-1.jpg](http://gna.org/bugs/download.php?file_id=15657)

**Comment by Wedge009** [comment]
The first dialogue is there to give you an option of taking over the log-in (and thus kicking out the previous log-in), cancelling that dialogue returns you to the log-in dialogue with the option of trying another user name.

I would argue this is perfectly valid and sensible, and removing the first dialogue would not make sense. Thus, closing - if anyone objects you can re-open it.
