### ISSUE TITLE
Request for a [detect] ability (GNA #19685)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1308]
**[Original submission](https://gna.org/bugs/index.php?19685)** by the_other on 2012-05-01

Following a forum discussion [url](http://forums.wesnoth.org/viewtopic.php?f#21&t36547&p=527349#p527339)[/url], this is a request for the addition of a [detect] function within [abilities].

The purpose of this would be to allow units with this ability to locate hidden units, without moving adjacent to them, while making them visible ONLY to the player who controls the detecting unit.  This is a bit long, I'm hoping [ section ] tags will work properly here...

[section#"An ideal solution"]An ability that can take [filter]s for the location and condition of both the detecting unit, and the unit to be detected, and a radius key.  Example:

```
[detect]
  id=example_detect
  name= _ "Detection Example"
  description= _ "During daylight, this unit can detect hidden units in forests within a radius of 6 hexes around itself"
  radius=6
  [filter_self]
    time_of_day=lawful
  [/filter_self]
  [filter_second]
    terrain=aliases of all forest terrains
  [/filter_second]
[/detect]
```

Ideally, the radius= key could also take a value of 'vision', setting it to equal the unit's normal vision range, or be omitted or left blank (in which case it would default to unlimited radius, covering the entire map)[/section]

I see that there could be an issue here if a unit has multiple or multi-faceted [hides] abilities in effect at the same time (the example ability above would reveal units with Ambush, even if they were also being hidden by Nightstalk).  How and if this can be solved is dependent on how the game engine processes [hides] abilities - one way to avoid it is by processing in the following sequence:

[section="This information is also in the forum thread referenced above"]1.  All units meeting filters for terrain-based [hides] abilities are flagged as "invisible"

2.  All units currently flagged as "invisible" are checked to see if they satisfy the filters in any [detect] ability.  If so, the "invisible" flag is removed.

3.  Same as step 1, but for time-of-day-related [hides] abilities

4.  Repeat step 2

5.  Same as step 1 and 3, but for other types of filtering eg. status-based [hides] abilities

6.  Repeat step 2.

...insert any other possible filtering types here...

7.  Flag as "invisible" all units with unfiltered [hides] abilities (ie, constant invisibility)

8.  Repeat step 2.

9.  Any units that still have an "invisible" flag become hidden.

Thus, the problem of multiple [hides] abilities is solved (in the example case above, the unit is hidden by Ambush, revealed, but then hidden AGAIN by Nightstalk).  Hopefully that made sense...[/section]

If this is not possible or practical, a second option would be for the [detect] ability to take keys for radius# and detected, with the latter being the ID of the specific [hides] ability which is countered (potentially a comma-separated list, or a blank key which would default to "all forms of [hides] ability"

Finally, I see that vision range is now being made separate from max_moves.  In this case, perhaps detection_range could also be added within [unit_type], describing the radius within which hidden units are automatically detected (defaulting to 1 if omitted) - a far simpler solution from a player/UMC-maker's perspective, if it is practical to implement.

Thanks!

(Reproduced on Any)
Release: Any
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-01**

**brilliand wrote:**

> You want this ability to be able to suppress certain "hides" abilities, while leaving others active?  I think this result might be more easily obtained by adding a StandardSideFilter to the [hides] tag that determines which sides the unit is hidden from.  That filter could then filter out sides with suppressing units in the vicinity, as needed.  It makes the WML more complicated, but it also makes it more flexible.
> 
> 
> 
> You'd think, though, that players would want their allies to see the units they've managed to detect.  I suppose that would be a part of shared vision.  That could be covered by the WML as well, though it would probably require a macro to keep everything straight.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-01**

**the_other wrote:**

> I see BBCode doesn't work here...never mind...
> 
> 
> 
> For me personally, discriminating between different [hides] abilities is not a concern.  But just about every ability imaginable, seems to be wanted by SOMEONE, so it seems to me to make sense that the discriminatory function be included (somebody WILL want it at some point!).  It isn't strictly necessary to what I have in mind, though.
> 
> The reasoning for adding a new [detect] ability, rather than adding new functions to [hides], is that it is far simpler for novice and intermediate WMLers (myself included) to understand. I'm aware of at least one way to accomplish the same thing currently, in pure WML and with no change to the game engine.  The problem, basically, is that it's a pain in the arse to do it that way.  See the forum thread where this suggestion originated - I won't repeat it here, as it's not directly helpful and currently contains no actual code.
> 
> Suffice it to say that the reason for (hypothetically) adding this function as an ability, is to make it accessible in the simplest and most comprehensible way for non-WML-literate users, requiring the least amount of code - and research! - in order to make new abilities of this type.

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-02**

**boucman wrote:**

> As a rule of thumb, we try to avoid "counter-abilities" in wesnoth.
> 
> 
> 
> i.e we try to avoid abilities that specifically target another ability, like an "anti-poison aura" they make the game less interesting
> 
> 
> 
> (we also avoid "oposite abilities" like an aura of darkness, but that's not relevent here)
> 
> 
> 
> 
> 
> brilliand : I am assigning this FR to zookeeper, since he is the one with the most vision about the big picture WRT wml in general.
> 
> 
> 
> if he doesn't react and you are interested in implementing this, ping him for comments
> 
> 
> 
> Boucman

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-09-11**

**zookeeper wrote:**

> I don't really see any problem with an ability like that. I might be more inclined to propose adding an extra [filter_radius] filter however, to allow better control of the detection "paths".
> 
> 
> 
> I'd keep it simple and make it so that the detect ability always reveals any units which match the given filters within the given radius, regardless of how many and what kind of hides abilities they have.
> 
> 
> 
> One remaining question I think hasn't been addressed so far is whether the owner of the detected unit would see their unit as having been detected; in other words, does the ability prevent the hides ability from working at all, or does it only allow the detecting side (and them only) to see through the hides ability? It has quite some gameplay implications especially when fog is used, or when there's multiple teams.

**Comment by Pentarctagon** [comment]
Closing since this is essentially FPI#29, should be mostly implementable via WML now without needing to add a specific [detect] ability, and the details of how this would work were never decided.
