### ISSUE TITLE
addon manager has low transfer rate at connection and download (GNA #19701)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1309]
**[Original submission](https://gna.org/bugs/index.php?19701)** by j_daniel on 2012-05-02

Downloading an addon with firefox I get 1 MB/s

Downloading an addon with addon-manager I get 1MB/min

(Reproduced on Linux amd64)
Release: 1.11.0-svn
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-02**

**j_daniel wrote:**

> happens with 1.8.6 SDL_net code and 1.11.0-svn asio code

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-05**

**shadowmaster changed severity:** 3 - Normal -> 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-08**

**max2008 wrote:**

> what's your cpu load while downloading?
> 
> 
> 
> mine is (1.10.1 on windows) is quite high for such a simple task (takes half a core). maybe it's caused by the ui (progressbar seems to be updated quite frequently).

**Comment by Wedge009** [comment]
Too many factors and no responses on this one for so many years, I don't think this is worth keeping. eg When testing #4244 I noted that the slow downloading was possibly due to the add-on server's limited bandwidth rather than - or at least in addition to - my slow Internet service generally.
