### ISSUE TITLE
Translated help topics alpabetically sorting (GNA #19707)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1310]
**[Original submission](https://gna.org/bugs/index.php?19707)** by fphoenix on 2012-05-03

English help topics are sorted ok, but not translated topics. I don't now, how it works, but it either doesn't inherits the original strings order.

At the screenshot I marked an order difference with arrows and placed numbers for correct Russian order.

(Reproduced on WinXP)
Release: 1.10.2
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-05-03**

**fphoenix added attachment:** [help-sorting-compare.jpg](http://gna.org/bugs/download.php?file_id=15663)

**Comment by Wedge009** [comment]
I note that this appears to be in place now - testing 1.14. eg Undead is Morts-vivants in French and is located in the correct order relative to everything else in the units list.
