### ISSUE TITLE
Display of the current speed (GNA #19755)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1311]
**[Original submission](https://gna.org/bugs/index.php?19755)** by anonymous on 2012-05-22

Since many times during enemy turn one is supposed to use the CTRL+A shortcut to temporarily switch to accelerated speed, it would be nice to show the current speed in the user interface during the game, since there is no way to intefere it without moving a unit.

I mean something really small like a label with "SPEED # 1x" or "SPEED  2x" written in the right panel or on the upper status bar.

(Reproduced on WinXP)
Release: 1.10.2
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-10-05**

**spixi wrote:**

> I tried to implement it, but it didn't work ...
> 
> 
> 
> --- /src/hotkeys.cpp	2012-09-23 15:37:45.276327119 +0200
> 
> +++ /src/hotkeys.cpp	2012-09-23 15:36:42.579069752 +0200
> 
> @@ -1197,6 +1198,7 @@
> 
>  			break;
> 
>  		case HOTKEY_ACCELERATED:
> 
>  			preferences::set_turbo(!preferences::turbo());
> 
> +			gui2::show_message(disp.video(), _("Speed: "), preferences::get("turbo_speed") );
> 
>  			break;
> 
>  		case HOTKEY_MUTE:
> 
>  			{
> 
> 
> 
> 
> 
> Maybe I did something wrong ...

**Comment by Wedge009** [comment]
The root of this request - having the acceleration speed permanently on display somewhere (side-bar or menu bar, I assume) - is covered by #1188.
