### ISSUE TITLE
Serious performance issues (GNA #19914)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1312]
**[Original submission](https://gna.org/bugs/index.php?19914)** by anonymous on 2012-07-09

Greets,

I have some serious performance issues when playing BfW. When scrolling the map and/or moving units, FPS falls to 2-5.

Wesnoth Version: 1.10.3

PC Info: P4-2800/512M RAM/GeForce 6600 128Mb AGP/100Mbit broadband conenction

Latest GPU drivers are installed.

(Reproduced on Windows XP)
Release: 1.10.3
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-02-10**

**mordante changed status:** None -> Need Info

**mordante wrote:**

> Can you post a sample savegame where this occurs? What screen resolution do you use?

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-02-10**

**anonymous wrote:**

> 1024*768 is used.
> 
> 
> 
> This trouble occurs every now and then. In every, EVERY game.

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-02-10**

**mordante wrote:**

> What do you mean with `every now and then'; does it happen every time you scroll or only sometimes?

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-02-12**

**anonymous wrote:**

> Every time when scrolling.

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-02-16**

**mordante wrote:**

> Did you run older versions of Wesnoth on this system and if so were they also as slow or faster?

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-02-18**

**anonymous wrote:**

> Such kind of issues have been spotted since approx. 1.6.

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-02-23**

**mordante changed status:** Need Info -> None

**mordante wrote:**

> Ok thanks for the info.

**Comment by nemaara** [comment]
No longer relevant since 1.10 isn't supported any longer (and we already know about performance problems for 1.14, but that is a different issue).
