### ISSUE TITLE
Segfault when an unit with a planned action is killed. (GNA #20071)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1314]
**[Original submission](https://gna.org/bugs/index.php?20071)** by ejls on 2012-08-16

- Move an unit with 1 hp next to an enemy.

- Plan a move for the next turn.

- End turn.

- When the unit is killed, the game segfault.

With my next commit, the game segfault only on the next use of the highlighter or whatever use action::get_unit before a mapbuilding.

The problem is that the move is not removed from the side_actions.

(Reproduced on All)
Release: r54960
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Wedge009** [comment]
@CelticMinstrel This report didn't get all the conversation from http://gna.org/bugs/index.php?20071 for some reason. I don't know yet if this is an isolated case or if other imports have this issue.

**Comment by Wedge009** [comment]
Quoting myself from 2015-09-23:

> I've managed to reproduce what I think is the original problem:
> 
> * Player 1 has a low-health unit. In planning mode, Player 1 plans a move that takes more than one turn to complete (thus, leaving the low-health unit with planned moves after the current turn).
> * Player 2 attacks the low-health unit, killing it.
> * Back to Player 1's turn, the killed unit still has unfinished planned moves, causing an assertion failure in debug mode, or a terminal crash in normal release compilation.
> 
> The crash happens because highlighter::last_action_redraw() attempts to access now-dead unit. I've worked around this by checking first that the unit is valid before attempting to access its data. I am still working on whether its possible (within my limited knowledge of the code) to remove the unfinished planned move highlighting which lingers behind (it ought to be deleted if the unit is no longer alive).

**Comment by Wedge009** [comment]
Quoting myself from 2015-12-09:

> To test the issue with the attached [2p_—_Cynsaun_Battlefield-Sauvegarde_automatique8.gz](https://github.com/wesnoth/wesnoth/files/988054/2p_._Cynsaun_Battlefield-Sauvegarde_automatique8.gz)
> * Deoddyn at 25,22 is low health.
> * I plan a move to 25,29 so that when I end the turn, he is occupying 26,27.
> * It is then easy for any nearby drake to use their ranged attacks to kill him.
> * After ending the turn, the dead unit's plans are displayed again. Before the PR, the game will crash. Afterwards, the game will not, though it does require a mouse-over the plans to remove it from display (see PR #496 for more explanation on this).

**Comment by CelticMinstrel** [comment]
That's strange. I hope this is indeed an islolated issue... if I recall correctly, the transfer did crash once or twice, so it's possible that that was after posting this issue but before posting its comments?
