### ISSUE TITLE
Event-based abilities (GNA #20188)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1318]
**[Original submission](https://gna.org/bugs/index.php?20188)** by mrdarkunknown on 2012-09-20

I would be pleased if it was allowed to place [event]s into the subtags of [abilities] and [specials] and [set_specials], like [leadership], [slows], or [damage] (or [dummy]). These events would have the same effect as if they were in [unit_type]. Too many UMC coders fail to understand the [+tag] use syntax, suggest dumb things on the forums, claim that it is not possible to add things like feeding with [object]s... it is generally hard to understand it, and the whole usage of event based abilities/weapon specials is very clumsy (other macros needed when it's added with advancements, other when added with objects (and the event is not passed on into next scenarios)).

I mean something like this:

    [dummy]

        id=feeding

        name= _ "feeding"

        female_name= _ "female^feeding"

        description=_ "Feeding:

This unit gains 1 hitpoint added to its maximum whenever it kills a living unit."

	 [event]

	    id#ability_feeding_die #Preferably, id and first_time_onlyno should be added automatically, id according to the id of the ability

	    name=die

	    first_time_only=no

	    [filter]

		[not]

		    [filter_wml]

		        [status]

		            not_living="yes"

		        [/status]

		    [/filter_wml]

		[/not]

	    [/filter]

	    [filter_second]

		ability=feeding

	    [/filter_second]

	    [unstore_unit]

		variable=second_unit

		{COLOR_HEAL}

		text= _ "+1 max HP"

		find_vacant=no

	    [/unstore_unit]

	    [object]

		silent=yes

		duration=forever

		[filter]

		    x,y=$x2,$y2

		[/filter]

		[effect]

		    apply_to=hitpoints

		    increase_total=1

		    increase=1

		[/effect]

	    [/object]

	[/event]

    [/dummy]

(Reproduced on Linux)
Release: 1.11
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-15**

**gfgtdf wrote:**

> I don't like this idea, it seems to me like it'd just result in the whole [event] code beeing stored in every single unit that uses that ability. 
> 
> 
> 
> 
> 
> Also note that we recently changed the feeding ability code so that it no longer uses the [+tag] syntax.

**Comment by stevecotton** [comment]
Can we close this FR, as IIUC WML has improved with other ways to do it (as in, more places where the `[event]` tag is supported)?

**Comment by gfgtdf** [comment]
Yes i'd say so, also ftr 'mrdarkunknown' is @Dugy if I remember correctly.

**Comment by Dugy** [comment]
> Yes i'd say so, also ftr 'mrdarkunknown' is @Dugy if I remember correctly.

Yes, both Dugi and Dugy were taken, so I had to improvise when registering. I apologise for the confusion I caused.
