### ISSUE TITLE
Unable to add new event handler in Wesnoth 1.11.0 (GNA #20280)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1320]
**[Original submission](https://gna.org/bugs/index.php?20280)** by seattledad on 2012-11-02

The attached file, which seeks to add an event handler as per the instructions in http://forums.wesnoth.org/viewtopic.php?f#58&t34045 (see Event Registration-->With Wesnoth) works fine in Wesnoth 1.10.4 but generates a Bus Error 10 in Wesnoth 1.11.0.

Note that this file runs fine in Wesnoth 1.11.0 under the following circumstances:

--When run in nogui mode

--When both sides are controlled by the AI

It exhibits the error when run with the following:

/Applications/Wesnoth1.11.0.official.app/Contents/MacOS/Wesnoth  --multiplayer --controller 2:ai   --ai-config 2:~ai/dev/display_event_error.cfg

(Reproduced on OS X)
Release: 1.11.0
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-11-02**

**seattledad added attachment:** [display_event_error.cfg](http://gna.org/bugs/download.php?file_id=16737)

**Comment by gfgtdf** [comment]
The link in the first post gives "The requested topic does not exist."
The link in the second post gives "<Error><Code>SignatureDoesNotMatch ..."
It's generally unclear what type of "Event" is meant here


So i'm closing this

**Comment by GregoryLundberg** [comment]
https://forums.wesnoth.org/viewtopic.php?t=34045
