### ISSUE TITLE
WML configuration of hex field size not working (GNA #20327)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1322]
**[Original submission](https://gna.org/bugs/index.php?20327)** by jamit on 2012-11-25

I added the line

```

    tile_size=36

```

to game_config.cfg and saw no results other than messing up the z-order in some cases (e.g. units disappearing under some villages and mountains). I also tried setting tile_size to 144. Still nothing.

I was expecting that the grid would resize based on tile_size, with the probable result that the default graphics would look bad because they were either overlapping (for tile_size#36) or not covering everything (for tile_size144). However, I saw no such resizing. From what I can see, this half of r55268 is not functioning.

I mentioned this in IRC back in September (early on the 17th by log time) and thought I should put it in the bug tracker so it is not forgotten.

(Reproduced on Linux)
Release: 1.11.0+svn
Priority: 4
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-12-12**

**fendrin changed priority:** 5 - Normal -> 4

**fendrin changed status:** None -> Confirmed

**fendrin changed severity:** 3 - Normal -> 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-06**

**fendrin changed status:** Confirmed -> Postponed

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-07-23**

**gfgtdf changed status:** Postponed -> None

**Comment by Wedge009** [comment]
Just wondering what the purpose of setting `tile_size` would be. Trying to manually set the zoom level perhaps? jostephd's comment in #4423 seemed to be an interpretation that this issue was an expectation this was something that should available, yet I see no mention of this in the [wiki documentation](https://wiki.wesnoth.org/WesnothGameConfigure).

Wesnoth now saves the zoom level between application sessions, so I'm inclined to think that covers this issue. If not, it can always be re-opened.

**Comment by CelticMinstrel** [comment]
Though as you say it's not particularly clear, my suspicion would be that this is something related to custom cores, intended as a way to make a core that has a different base terrain hex size. And looking in game_config.cpp, I indeed see it's an undocumented key in the `[game_config]` tag, which seems to support my suspicion.

I did a quick look, and it appears the game_config constant is indeed used everywhere this matters, so it would seem weird to me that setting it to a different value doesn't do anything. Of course, I'm probably missing something…

By the way, the page you linked is _very_ obsolete. The current version of that documentation (which still doesn't mention that key) is [here](https://wiki.wesnoth.org/GameConfigWML).

**Comment by Wedge009** [comment]
`tile_size` is present, but from what I recall, is only ever used in code - haven't seen it in WML.

Regarding the documentation, I'm not familiar with the structure, I found the obsolete page via Internet search. Perhaps it should be deleted or merged with the current page?

**Comment by CelticMinstrel** [comment]
Yeah, I agree, so I asked for that on IRC/Discord and @Pentarctagon has already deleted it.

> haven't seen it in WML.

Yeah, it appears to be supported in `[game_config]`, but core doesn't actually set it, letting the C++ hard-coded default value come into play.
