### ISSUE TITLE
"Castle overlay" does not disable "keep" functionality of a keep... (GNA #20343)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1323]
**[Original submission](https://gna.org/bugs/index.php?20343)** by tobefree on 2012-12-01

...but even the field description which is shown in the upper-right corner when someone hovers the mouse over it does not say something about it.

(Reproduced on every OS)
Release: 1.10.4
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-12-02**

**jamit wrote:**

> Why should someone think that adding castle functionality (via a castle overlay) somehow removes fully-compatible functionality (that of a keep)?

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-12-03**

**tobefree wrote:**

> Simply because the castle overlay would be useless for such a field otherwise. I want to be able to use the keep tiles as castle tiles and since the castle overlay has no effect on a keep at the moment anyway, it would be nice to be able to do that.
> 
> 
> 
> And, as I said, the tile description does not mention the "keep" feature if such an overlay has been placed on a keep. Either fix this or (my idea) allow keep functionality to be disabled that way. I assumed it would work like that. ;-)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-12-03**

**jamit changed severity:** 3 - Normal -> 1 - Wish

**jamit wrote:**

> Correct, a castle overlay is useless on a keep (also useless on a castle). Which, when combined with Wesnoth's "keep it simple" philosophy, makes for a strong case against adding special processing to change the tile description when someone does this, since that someone has no reason to do this.
> 
> 
> 
> Changing this one particular overlay in this one particular case so that it removes something (when all other overlays only add) might be more confusing overall. And it would require special-case handling, which again goes against a KISS philosophy. I wouldn't be surprised if this eventually gets filed under "won't fix". (In the meantime, I'm going to change this from a bug report to a feature request for an overlay that can remove something from the underlying terrain.)
> 
> 
> 
> To get the effect you want, you might have to define a new terrain type. (Since all the images are already made, it should not be too difficult.) Something like the following might work:
> 
> ```
> 
> [terrain_type]
> 
>     symbol_image=castle/encampment/regular-keep-tile
> 
>     id=encampment_castle         # Changed this
> 
>     name= _ "Encampment Castle"  # Changed this
> 
>     string=Kez                   # Changed this
> 
>     aliasof=Ch
> 
>     unit_height_adjust=0
> 
>     recruit_from=false           # Changed this
> 
>     recruit_onto=true
> 
>     editor_group=castle
> 
> [/terrain_type]
> 
> ```
> 
> 
> 
> The "changed this" notes mean the lines were changed from the definition of terrain code Ke. The id# and string lines were changed to keep them unique. The string= line begins still begins with a 'K' (instead of changing it to a 'C') in case that helps the macros that control the transitions between terrains.

**jamit changed category:** Bug -> Feature Request

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-12-05**

**tobefree wrote:**

> Okay, thank you for the code example; I'll probably use that instead. I would still suggest to change the tile description of a keep+castleoverlay tile because it is confusing imho. ;)

**Comment by wesnoth-bugs** [comment]
**Modified on 2012-12-06**

**alarantalara wrote:**

> The tile description is also effectively unchangeable. Overlay descriptions are supposed to override descriptions for the base terrain and it makes sense to do so in every case but this (forests, mushroom groves, the castle overlay on all other terrains, the keep overlay, the impassable overlay, etc.).
> 
> 
> 
> There isn't actually any UI clue other than trying to recruit and that description to indicate the presence of a keep however, and as you have pointed out, the description is not reliable. This is actually a problem with the heals, castle, and keep status for terrains.

**Comment by Wedge009** [comment]
The conversation here seems to suggest this may not be a valid request. Worth keeping (especially considering its age)?

**Comment by gfgtdf** [comment]
yes i agree

**Comment by Wedge009** [comment]
...agree it's invalid or agree to keep it?

**Comment by gfgtdf** [comment]
that its invalid.

**Comment by Wedge009** [comment]
Thanks.
