### ISSUE TITLE
Separate attack-icon frame from the attack-icon proper (GNA #20387)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1327]
**[Original submission](https://gna.org/bugs/index.php?20387)** by anonymous on 2012-12-26

Feature request: separate the attack-icon frame from the attack-icon proper.

Right now, the attack-icons are 60x60 px images. The part that varies between attack-icons is in the center, 50x50 px; the "frame around them is redundant (if the frame does vary on some attack-icon, then it varies due to an error). Attack-icons would be better off rendered in 2 layers: first the 60x60 px frame, then the 50x50 px attack-icon proper in the center of it.

1) it would remove redundancy

2) it would simplify the spec of an attack-icon image into "close-up weapon on black background"

3) it would save from file size

4) at some point, the frame could be made to vary separately, eg to denote damage type (red for fire, blue for cold, etc)

(Reproduced on N/A)
Release: N/A
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Pentarctagon** [comment]
I don't really follow what this is suggesting.  @doofus-01 does this make any sense to you?

**Comment by doofus-01** [comment]
I think the request is to separate the icon border from the actual image, then essentially ~BLIT() it on as needed.  Point 4 does make sense: if you want to make a quick variation, you can color-shift the image without also color-shifting what looks like a part of the UI.

This is already possible by BLIT()-ing an image onto `attacks/blank-attack.png`.  I guess this would be more of a convention than an engine feature, though it could be made part of the engine if there is some performance benefit (I have no idea if there is).

**Comment by Pentarctagon** [comment]
Do you think this is something that'd be worth doing to all the existing icons, or more something to do as needed on a case by case basis?

**Comment by doofus-01** [comment]
Case by case.  There's nothing currently stopping anyone from constructing a composite icon image with IPFs if they need to.  Converting the existing icons just seems like busywork.  It might be worth doing if the border becomes something placed by the GUI dialog, but not until then.

**Comment by Pentarctagon** [comment]
Alright, closing then.
