### ISSUE TITLE
[color_palette]s do not get refreshed after F5 is used (GNA #20423)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1329]
**[Original submission](https://gna.org/bugs/index.php?20423)** by espreon on 2013-01-11

As the title implies, [color_palette]s do not get refreshed after F5 is used.

To see this bug in action, do the following:

1. Download this: http://wesnoth-umc-dev.svn.sourceforge.net/viewvc/wesnoth-umc-dev/branches/testing/trunk/Color_Palette_Refresh_Test/?view=tar ... and install it.

2. Go to its entry in the campaign description menu

3. Follow the directions (you can also read them by going here: http://wesnoth-umc-dev.svn.sourceforge.net/viewvc/wesnoth-umc-dev/branches/testing/trunk/Color_Palette_Refresh_Test/_main.cfg?revision#16811&content-typetext%2Fplain)

(Reproduced on *)
Release: 1.11.x
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Wedge009** [comment]
Can we do anything about this given the links don't appear to be valid any more? I also wonder in what context F5 was being used.

**Comment by Wedge009** [comment]
Oh I see. F5 is used in the editor?

**Comment by CelticMinstrel** [comment]
I found a valid link to this:

https://sourceforge.net/p/wesnoth-umc-dev/code/HEAD/tree/branches/testing/trunk/Color_Palette_Refresh_Test/_main.cfg

**Comment by jostephd** [comment]
No need for links... here's the full contents of that file, there are no other files in its directory either:

```
[campaign]
    id=color_palette_refresh_test
    define=COLOR_PALETTE_REFRESH_TEST
    name="Color Palette Refresh Test"
    first_scenario=null
    icon=data/core/images/units/human-magi/red-mage.png~RC(magenta>blue)
    image=data/core/images/units/human-magi/red-mage.png~RC(magenta>blue)
    description="A testcase for developers...

Do the following:

1. Look at this campaign's menu icon
2. Open team-color.cfg in core
3. Remove all but the first of the color codes from the 'magenta' palette and save
4. Exit the campaign selection menu and hit F5
5. Open the campaign selection menu and look at this campaign's icon again
6. Behold... it has not changed!"
[/campaign]
```

**Comment by soliton-** [comment]
Works for me. Removed the `magenta` entry from `[color_palette]`, pressed F5 on the title screen and opened the campaign menu and all icons are now magenta and you get `Invalid color in palette: magenta` in the log.
