### ISSUE TITLE
A few keys in [side] stopped working (GNA #20562)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1330]
**[Original submission](https://gna.org/bugs/index.php?20562)** by anonymous on 2013-02-26

The gender, type, and faction keys no longer lock in the player to that choice or even do anything at all.

(Reproduced on windows 7)
Release: 1.11.1+svn
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-07-21**

**jamit changed item group:** None of the others -> Multiplayer Lobby

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-11**

**thunderstruck wrote:**

> "The gender, type, and faction keys no longer lock in the player to that choice or even do anything at all."
> 
> This claim isn't exactly true, because keys do work, but not all the time. faction and gender keys didn't do nothing if force_lock_settings wasn't set to yes, while type key seemed to work just fine.
> 
> 
> 
> I've fixed this with https://github.com/wesnoth/wesnoth/commit/cec331c11b4d85f7f37b127d0373e14a76b6d475
> 
> 
> 
> I made it so that faction and gender attributes provide default values for relevant combos even if force_lock_settings is not set to yes.
> 
> 
> 
> To fully fix this one, I think we should add such attributes as faction_lock to provide individual locks for factions, leaders and genders.
> 
> 
> 
> I'm lowering priority of this one, because the problem has been already mostly addressed.

**thunderstruck changed severity:** 3 - Normal -> 2 - Minor

**thunderstruck changed priority:** 5 - Normal -> 3 - Low

**Comment by gfgtdf** [comment]
given that we have a `leader_lock` attribute i assume that this is fixed
