### ISSUE TITLE
RFE: Request to rename "cutter" and "exploder" (GNA #20615)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1331]
**[Original submission](https://gna.org/bugs/index.php?20615)** by mschwendt on 2013-03-13

Hello everyone! This is a hard one. I hope you won't be annoyed by this question.

Would you be willing to rename the tools "cutter" and "exploder" to something less generic, so they don't bear a high risk of conflicting with other programs that use the same names?

For example, there are two programs "cutter" which name their executables "cutter": A unit-testing project "cutter" ( http://cutter.sourceforge.net/ ) which exists for many years (but not as long as BfW), and a second one, a firewall/networking related "cutter" ( http://www.digitage.co.uk/digitage/software/cutter ).

Would it be considered too inconvenient, if the command-line tools "cutter" and "exploder" were named "wesnoth-cutter" and "wesnoth-exploder"? I understand the tools are not specific to BfW, so perhaps there would be an even more specific name?

(Reproduced on Linux)
Release: 1.10.5
Priority: 3 - Low
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-07-21**

**jamit changed priority:** 5 - Normal -> 3 - Low

**jamit changed category:** Bug -> Feature Request

**Comment by Vultraz** [comment]
Both cutter and exploder were removed in b991c320a48fd29735d15dbc2729a4df27242a56.
