### ISSUE TITLE
Invalid Markup Text Message (GNA #20617)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1332]
**[Original submission](https://gna.org/bugs/index.php?20617)** by woodruff on 2013-03-13

My Operating System: Windows XP Pro, Version 2002, Service Pack 3

Version of Wesnoth: 1.10.5 now (just updated from 1.10.3 when I started noticing this problem)

Language Used: English

Here was my original synopsis of the problem, as stated in the Wesnoth Forums: Many of the campaigns, and including the Tutorial, give me the error message "The text contains invalid markup" for the Scenario Objectives when I first start the campaign (after I select the level of difficulty). I also notice that in those campaigns which have this problem (including the Tutorial), all of the "character text boxes" are either blank or have a similar error message.

At first, I simply thought this was an isolated problem with an occasional campaign, but I have come across it more and more. And the real key for me was when I tried the Tutorial, just to see what was up.

I updated to 1.10.5 just now, hoping that had some sort of a fix for it, but the problem remains.

I've been playing Wesnoth since before 1.10, so it's not a newbie thing. And I have successfully run many of these campaigns, including the Tutorial, previously. So I suspect it may be a setting I have going on, but I can't seem to figure it out.

However, as follow-on experimentation occurred from discussion in the Wesnoth Forums, I realized that this appears to be caused by the number of add-ons I have, or perhaps the total size of those add-ons.  It was suggested to me that it was being caused by an add-on, so I copied all of my add-ons into a backup directory, leaving my add-on directory empty.  I then checked the Tutorial, and it was intact without the text markup message.

So then, one-by-one, I copied each add-on back into the add-on directory and then tested the Tutorial to see if the problem started back up.  At the point where I copied the 264th add-on into the add-on directory, the problem re-emerged, exactly as it was before.

So my next step was to see if it was that particular add-on, by removing it and trying a different one.  The problem re-emerged.  I did this with five different directories, all resulting in the problem noted.

Now, I'm not sure if this is being caused by the total number of add-on sub-directories or the total amount of space being taken up by the aggregate of those directories.

I recognize that I don't NEED to have 264 different add-ons.  However, the primary thing I like about Battle For Wesnoth is that I can play so many different campaigns.  Essentially what I do is when I sit down to play, I roll some dice to see what campaign I will play.  This keeps the game fresh and interesting for me, as I find myself playing all different kinds of campaigns and never knowing in advance what it will be.  So it actually is pretty important to my enjoyment of Battle of Wesnoth.

Please let me know if you need any further information.  Thanks.

(Reproduced on Windows XP)
Release: 1.10.5
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-03-24**

**mordante wrote:**

> Can you provide a link to the forum thread?

**mordante changed status:** None -> Need Info

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-03-24**

**woodruff wrote:**

> Here is the link to the forum thread:
> 
> 
> 
> [url]http://forums.wesnoth.org/viewtopic.php?f#4&t38461[/url]
> 
> 
> 
> Let me know if you need anything else.  Thanks!

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-01-05**

**woodruff wrote:**

> Why is this item still marked as "need info"?  I provided a link to the forum thread, as requested, and have seen no other requests for information.  I realize that development fixes can be slow, but that was in March of last year...which should have been plenty of time to at least update the status of this item, shouldn't it?

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-06**

**shadowmaster changed status:** Need Info -> None

**Comment by jostephd** [comment]
I think that could be the bug I fixed recently in a1bbe66acb45a6cfa8cb9f1501f9f6207d1bc192 after @Konrad22 independently discovered it. The key in that bug was having more than 128 different textdomains, so that would mean more than half of the OP's addons didn't have translations.

In the circumstances I'll close this, but please reopen if you can reproduce it in current 1.14.

**Comment by Konrad22** [comment]
I have to say it does sounds uncannily similar to the bug I had discovered, so I can only concur with the above assessment.
