### ISSUE TITLE
mouse and menu options are out of sync (GNA #20746)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1334]
**[Original submission](https://gna.org/bugs/index.php?20746)** by eltito on 2013-04-19

PLease Ignore if already open

version1.11.1

mac OSX  10.6.8

Problem-when wesnoth is run windowed, the menu items are highlighted only when the mouse cursor is slightly to the lower right of the option in question (1280*800 resolution). If the resolution is lowered and then returned to 1280*800 it behaves normally. However whenever wesnoth is newly opened in windowed format at 1280*800, the mouse cursor highlights the various menu options only when to the lower right of the menue options.

mercy. This is my first bug report.

(Reproduced on OSX)
Release: 1.11.1
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-05-24**

**lubod wrote:**

> This same bug (or one very similar to it) affects Wesnoth version 1.10.6 on Mac OS X 10.5.8 just as badly, if not worse.
> 
> 
> 
> With a screen resolution of 1024x768 (stretched) on a MacBookPro, I have to move the mouse an inch below the various buttons on the main screen (like Preferences) before they highlight! This is in windowed mode, they act ok in full screen mode, but I do not wish to give up multitasking and run it like some retarded DOS clone only capable of showing one program at a time. Please fix windowed mode. It worked well as recently as version 1.10.3 or so, so some of the 'bug fixes' seem to be regressions or new bugs, not fixes.

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-05-24**

**lubod added attachment:** [Error.jpg](http://gna.org/bugs/download.php?file_id=18007)

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-07-07**

**ancestral wrote:**

> This is a duplicate of #20332.
> 
> 
> 
> Resizing the window or clicking the zoom button will fix this immediately.
> 
> 
> 
> A fix has been merged into 1.12 and 1.13 that will prevent the problem for users �out-of-the-box.�

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-07-10**

**involution changed status:** None -> Postponed

**involution wrote:**

> I'm marking this bug "postponed".
> 
> 
> 
> IIUC the problem is that the Mac OS X window manager behaves differently from standard windows and linux managers, and sometimes gives the application a differently sized window than it requests, or silently rescales the window from what it tells the application it has, and SDL does not currently handle the messages that it sends about this. (Retina is also not well supported by SDL.)
> 
> 
> 
> ancestral's bug fix will make the default preference settings better so that the bug is avoided on OS X. However, if you bungle your preference settings then the bug will reappear. This is likely the best we can do until SDL gets along with OS X better, or until we switch to use a different system.

**Comment by hrubymar10** [comment]
Can't reproduce with 1.13.11+dev in macOS 10.13.4 Beta.

**Comment by Vultraz** [comment]
@ancestral confirms fixed.

**Comment by CelticMinstrel** [comment]
I recall experiencing this at some point, I think in 1.12 or 1.13? I can't remember any details though... but it wasn't consistent and only happened in some particular situation that messed it up until restarting, so maybe the underlying cause wasn't quite the same.

**Comment by hrubymar10** [comment]
Weren't Wesnoth transferred to SDL2 during 1.13? if so than it was possible resolved by this transition, if not and problem existed after SDL2 than idk, there are no steps to reproduce it and personally I have never had this problem.

**Comment by CelticMinstrel** [comment]
I don't recall whether it was before or after SDL2 that I experienced it.

**Comment by hrubymar10** [comment]
I believe that this problem disappeared after SDL2 transition. I recall that I had this issue but it was in 1.12? or smt around it so before SDL2.
