### ISSUE TITLE
Make disconnected user aware of his situation (GNA #20810)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1336]
**[Original submission](https://gna.org/bugs/index.php?20810)** by anonymous on 2013-05-12

Currently, disconnected (due to network failure) user is left guessing about what's going on: if he is out or if other player is away/lagging/whatever. Game should be able to notify when you are disconnected, at least in probabilistic way. I have no idea how often communication with server is done, but if there are no signs of life in X seconds, game would be right to suspect connection has died.

In general, it feels like Wesnoth client is disconnected far too often. Maybe there could be a way for client to automatically establish a new connection and request server to resend last packages (e.g. referring to the latest client received)?

(Reproduced on -)
Release: 1.10.4
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-07-10**

**involution wrote:**

> Just a comment: There is a command ":ping" which you can issue to your client which will cause it to send a small packet to the server. I believe the intention is to use it to check if you are disconnected, (although I'm not totally sure of this).

**Comment by Pentarctagon** [comment]
@soliton- @loonycyborg or @Vultraz Does the client *not* show an alert when a disconnect happens?  I could've sworn I remembered it doing that, and if nothing else there's the notorious "semaphore timeout" error.

**Comment by soliton-** [comment]
The server enables a keepalive feature so will notice disconnects.

I think the client doesn't so it's probably possible to not notice a disconnect in a situation where no network message is sent. You should get a timeout or whatever error if you trigger sending data over the network. (For example with the ping command.)

There used to be a custom ping implementation that you could optionally activate on the client side as well. Not anymore though.

The client side should just enable the keepalive feature as well.

**Comment by Pentarctagon** [comment]
I'll probably take a look at this in the near future if nobody else gets to it first. My understanding from discussing this recently on Discord is that this can more or less take the server-side keepalive logic as-is and then add the windows-specific way of handling it (since the server currently only supports keepalive when running on linux or macos).
