### ISSUE TITLE
Mouse problems in xmonad after resizing (GNA #20833)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1337]
**[Original submission](https://gna.org/bugs/index.php?20833)** by saati on 2013-05-20

When the xmonad window manager resizes wesnoth to the master tile  the mouse behaves like it's the old small size and it's only possible to click in the upper left parts of the window.

Steps to reprodce:

1. Start xmonad and a few programs, with the default (Tall) layout

2. Start wesnoth

3. Move another program to the master tile

4. Move wesnoth back to the master tile

(Reproduced on Debian Sid)
Release: Battle for Wesnoth 1.10.6
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-07-10**

**involution wrote:**

> Wesnoth does not contain special code to interact with window managers on windows, mac, or linux, we rely on SDL to manage our windows for us.
> 
> 
> 
> Does this bug affect all SDL games / applications for you, or just Wesnoth? If it affects only Wesnoth then we can likely fix it, but if it affects all of them then it's most likely an upstream problem. Note that we plan to upgrade SDL, either to SDL 2 or an alternative, in the near future.

**Comment by Pentarctagon** [comment]
Closing due to lack of response/further information if this is actually a Wesnoth bug.
