### ISSUE TITLE
save_index gets clobbered when Load Game is brought up for the first time in a given session (GNA #20850)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1338]
**[Original submission](https://gna.org/bugs/index.php?20850)** by espreon on 2013-05-27

Upon bringing up the Load Game dialog for the first time in a given session, the save_index is completely erased, with the exception of the first save on the list � the one that happens to be selected when the dialog is brought up.

(Reproduced on *)
Release: 1.11.x
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Vultraz** [comment]
Not been an issue for a while.
