### ISSUE TITLE
Add possibility to customize poison. (GNA #20919)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1339]
**[Original submission](https://gna.org/bugs/index.php?20919)** by ravana on 2013-06-18

Summarized at http://forums.wesnoth.org/viewtopic.php?f#21&t38907#p555485

Damage each turn (1 to 12) standard 8

Kills at the end (Yes or No) standard No

Lasts how many rounds (1 to indefinite) standard indefinite

(Reproduced on All)
Release: All so far
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-08**

**ravana wrote:**

> Best end result would be support for that kind of keys in [poison].

**Comment by Wedge009** [comment]
Superseded by #8126.
