### ISSUE TITLE
Alternate direction for "stones with sand drifts" (GNA #21018)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1345]
**[Original submission](https://gna.org/bugs/index.php?21018)** by tekelili on 2013-08-11

I have found several times that embellisment "stones with sand drifts" is not always looking cool due to "face". Currently only west-east sand drifts are alllowed, a north-south variation would be helpfull :)

(Reproduced on windows)
Release: 1.10.6
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Wedge009** [comment]
Not sure what is meant by 'face' here...

**Comment by AI0867** [comment]
The facing of the tile, as it's directional. It sounds like this particular terrain would benefit from /\| variations.

**Comment by Wedge009** [comment]
Ah, so there's only limited options for the orientation of the tile.

**Comment by doofus-01** [comment]
Even if there are complaints about the new images, the situation is changed enough (in 1.17.3+) that this can be closed.
