### ISSUE TITLE
Nested #define's (GNA #21343)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1352]
**[Original submission](https://gna.org/bugs/index.php?21343)** by laerne on 2013-12-13

This code :

#define F Y Z

  #define G A B

  {H Y A B}

  #enddef

    {K G {Z}}

  #undef G

#enddef

fails with "Macro/file 'Z' is missing at a/_main.cfg:10", the macro parameters seems to have been undefined with the first #enddef

At least one of the following behavior should happen :

* Define should be nestable.

* inside a #define, lines beginning by #define are comments.

I'm not hiding that I truly prefer the former solution, because it allows simulate lambda function for callback macros (As show in the first example where K is a macro taking the name of a macro).

(Reproduced on Any)
Release: 1.10.6
Priority: 3 - Low
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-12-13**

**laerne added attachment:** [_main.cfg](http://gna.org/bugs/download.php?file_id=19465)

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-12-14**

**jamit wrote:**

> Just observing: if we were to take your example code, and apply the rule "inside a #define, lines beginning by #define are comments", then stripping out that comment line would leave
> 
> 
> 
> #define F Y Z
> 
> {H Y A B}
> 
> #enddef
> 
> {K G {Z}}
> 
> #undef G
> 
> #enddef
> 
> 
> 
> This looks like it would fail with "Macro/file 'Z' is missing at a/_main.cfg:9". Not exactly an improvement in the end behavior.

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-12-16**

**jamit wrote:**

> I looked at the source and ran a few tests, and I think the second solution is already in place: inside a #define, lines beginning with "#define" *are* comments. So I guess that means this issue is already resolved? (I mean, one of the proposed solutions is in place, so what else would be needed to close this?)

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-12-16**

**laerne wrote:**

> I believe this should converted into a feature request for the first solution and not a bug.
> 
> 
> 
> What I mean with the second solution, is that the full block within beginning with #define (and not only the lines...) are comment.  But I realize this is not easier than the first solution, so it is better to have the first as a feature request, I think.

**Comment by wesnoth-bugs** [comment]
**Modified on 2013-12-16**

**jamit changed priority:** 5 - Normal -> 3 - Low

**jamit changed category:** Bug -> Feature Request

**jamit changed severity:** 3 - Normal -> 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-13**

**involution wrote:**

> I don't think this feature would be a very good idea.
> 
> 
> 
> The preprocessor would ideally be made simpler, faster, and easier to debug / get debugging output from. This change would be a change in the opposite direction, and for apparently little gain. I think there's a reason that, for instance, the C preprocessor doesn't allow you to do this. 
> 
> 
> 
> Can you give any use case that wouldn't be covered by using lua instead?
> 
> 
> 
> If not I would like to close this.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-13**

**laerne wrote:**

> This can be useful in every case where a closure can be useful, because this is basically it.  I lost the perticuliar case I wrote this in the first place, as I worked around it some times ago.
> 
> 
> 
> The idea as far as I remembered is there is no easy way to pass a bunch of values to macros, and macros are usefull to avoid copy-and-paste code, especially outside ActionWML, (like the inability to loop to emit the choice options of a [message] tag, but my issue was different).  But macro closure is probably not an elegant solution either.
> 
> 
> 
> Feel free to close it.

**Comment by ProditorMagnus** [comment]
I believe 1.14 does not allow nested defines, so this should be retested.

**Comment by jostephd** [comment]
In 1.14 it fails with

```
Macro/file 'Z' is missing
at scenario-test.cfg:4083
    included from _main.cfg:57
```

and I think that's expected because the macro definition is terminated by the first `#enddef`. No compelling use-case has been given for the so-called "closure" semantics (instead of having G use Y you could just have F pass Y to G as an additional argument, instead of having G as a "lambda function" you'd just have to use a longer name). Closing.
