### ISSUE TITLE
Count of units that can move to a hex is useless (GNA #21465)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1355]
**[Original submission](https://gna.org/bugs/index.php?21465)** by alarantalara on 2014-01-09

The count shows the total number of units, both mine and those of other sides that can reach a hex when it is selected based on the number of moves currently left for the unit. Of what value is knowing that an enemy unit did not use its full movement the previous turn and why should it complicate the information presented?

(Reproduced on OS X)
Release: 1.11.8+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-01-09**

**alarantalara added attachment:** [Screen shot 2014-01-09 at 3.39.29 PM.png](http://gna.org/bugs/download.php?file_id=19715)

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-06**

**fendrin wrote:**

> Future versions will splitt the numbers between enemy, own and ally.
> 
> 
> 
> The amount of enemy/ally units shown should be those able to reach the field in question during their next turn.
> 
> 
> 
> I will take care about it after 1.12 because fixing it properly involves some more features to be implemented.

**fendrin changed status:** None -> Postponed

**Comment by jostephd** [comment]
I can't reproducer the original issue. Close as fixed?

**Comment by stevecotton** [comment]
> I can't reproduce the original issue. Close as fixed?

No answer for 1 year, so...
