### ISSUE TITLE
Does not launch in maximized window (GNA #21503)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1356]
**[Original submission](https://gna.org/bugs/index.php?21503)** by anonymous on 2014-01-17

When "run maximized" selected in desktop shortcut, program opens in normal window partly off the screen edge. Need to move window and manually maximize every time.

(Reproduced on Windows XP &amp; 7)
Release: all
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-01-19**

**jamit wrote:**

> A more accurate description, as far as I can tell:
> 
> 
> 
> The game ignores Windows' "Run:" setting, which has the options "Normal window", "Minimized", and "Maximized". This setting can be found (in Windows XP) by right-clicking the shortcut and selecting "Properties". (It's in the "Shortcut" tab, but that seems to be the default tab as well.)
> 
> 
> 
> The symptom reported in the original submission is likely a result of the game remembering its previous resolution when running in a window (enough to fill a maximized window), yet starting as a normal window whose upper-left corner is not at the upper-left corner of the screen.
> 
> 
> 
> 
> 
> By the way (directed at the original submitter), you do not have to move the window. Click the Wesnoth icon at the left side of the window's title bar, then select "Maximize". (And, of course, there is the full-screen option, which I personally would use instead of a maximized window.)

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-03-05**

**wedge009 wrote:**

> With SDL2, a windowed game will start in the centre of the screen now, instead of the possibility of an edge hanging off screen. It will still ignore Windows' 'run maximised' shortcut property, though. I suspect this is just the way SDL works - I'm not sure if such a feature exists in other OSs either.
> 
> 
> 
> If you wish to start the game maximised, what difference is it to use full-screen mode instead?

**Comment by Wedge009** [comment]
There was another bug report that discussed Wesnoth being actual full-screen or borderless windowed in Linux, as I recall. Given that Wesnoth is the latter, I think this can be closed.

**Comment by Wedge009** [comment]
Closing due to lack of further comments.
