### ISSUE TITLE
overlapping announce-messages when toggling accelerated speed (GNA #21634)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1363]
**[Original submission](https://gna.org/bugs/index.php?21634)** by anonymous on 2014-02-10

By pressing Ctrl + A twice, you once obtain:

Accelerated speed enabled!

and

(press ctrl + A to disable)

Unfortunately, these are displayed at the same place.

The easiest fix might be to merge the messages in play_controller.cpp line 1471:

gui_->announce(_("Accelerated speed enabled!"), font::NORMAL_COLOR);

gui_->announce("\n" + vgettext("(press $hk to disable)", symbols), font::NORMAL_COLOR);

This would become

gui_->announce(_("Accelerated speed enabled!\n") + vgettext("(press $hk to disable)", symbols), font::NORMAL_COLOR);

(Reproduced on All)
Release: 1.11.9
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-02-13**

**shadowmaster wrote:**

> It's probably worth noting that this is a Windows-specific bug.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-02-13**

**mattsc wrote:**

> It's present on OS X as well.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-02-13**

**shadowmaster wrote:**

> In that case I probably should be more specific:
> 
> 
> 
> I can reproduce it on Windows, but not on Linux (Debian jessie amd64, clang 3.3, cairo 1.12.16, pango 1.36.0, freetype 2.5.2).

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-02-22**

**jamit wrote:**

> The "\n" is supposed to put the messages on separate lines.
> 
> 
> 
> If you're not seeing these messages on two lines, then you probably would also see "(press 'T' to keep moving)" on top of the "units sighted" message when unit movement removes fog and/or shroud from an enemy unit. (There are some other variations on that, but that is the simplest to describe.)
> 
> 
> 
> So fixing announce() to respect the newline character would be a much more desirable fix than hacking each announcement individually. Or maybe enhance announce() so that consecutive messages are automatically shifted down so they do not overlap? (That would also help with "Accelerated speed enabled!" being written on top of "Accelerated speed disabled!", which is another oddity you'd see by pressing Ctrl-A twice in rapid succession.)

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-08-15**

**anonymous wrote:**

> why do we actualy show the message?
> 
> Is it only for people who pressed the keyboard shortcut accidently?

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-17**

**wedge009 wrote:**

> Any sort of announcement appears to trigger this behaviour, for example, quickly switching planning mode (default 'p') on and off reproduces this as well.
> 
> 
> 
> I'm not sure what changed from shadowm's build, but (for me) this doesn't just happen in Windows but in Linux as well. (Cairo 1.14.2, Pango 1.36.8)
> 
> 
> 
> I'm not sure if the new-line character is necessarily a problem. Within each message it appears to function correctly - these announcements, on activation, usually have something like '\n(press $hk to deactivate)', which displays correctly.
> 
> 
> 
> A suitable fix, I think, is to either shift overlapping messages somehow, or perhaps remove the previous message if it has not yet disappeared of its own accord by the time a new message needs to be displayed.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-09-02**

**wedge009 changed OS:** Windows 7 -> All

**wedge009 changed status:** None -> Confirmed

**wedge009 wrote:**

> As noted in bug #24983, this happens with debug messages as well.
> 
> 
> 
> Affected OSs seem to include Windows, Linux and OSX, too. If shadowm can confirm this is still not an issue in Linux, we need to find out how/why.

**Comment by Wedge009** [comment]
Resolved with PR #999
