### ISSUE TITLE
[lock_view] does not prevent scrolling via minimap (GNA #21719)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1368]
**[Original submission](https://gna.org/bugs/index.php?21719)** by vultraz on 2014-02-24

Even if [lock_view] is set, the player can still move the viewport by clicking on the minimap.

(Reproduced on Any)
Release: 1.11.10+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by stevecotton** [comment]
Seems fixed in 1.13.12, although it's reproducible on 1.12.6.

**Comment by Wedge009** [comment]
Does this mean it's resolved on 1.14 and should probably be closed now?

**Comment by stevecotton** [comment]
Fixed in 1.14
