### ISSUE TITLE
test_gui2 unit tests fail (GNA #21747)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1369]
**[Original submission](https://gna.org/bugs/index.php?21747)** by fendrin on 2014-03-03

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'campaign_difficulty' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'campaign_difficulty' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'campaign_difficulty' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'campaign_difficulty' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'campaign_difficulty' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'campaign_selection' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'campaign_selection' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'campaign_selection' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'campaign_selection' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'campaign_selection' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'data_manage' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'data_manage' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'data_manage' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'data_manage' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'data_manage' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'editor_set_starting_position' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'editor_set_starting_position' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'editor_set_starting_position' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'editor_set_starting_position' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'editor_set_starting_position' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'game_load' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'game_load' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'game_load' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'game_load' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'game_load' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'gamestate_inspector' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'gamestate_inspector' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'gamestate_inspector' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'gamestate_inspector' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'gamestate_inspector' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'language_selection' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'language_selection' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'language_selection' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'language_selection' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'language_selection' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'simple_item_selector' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'simple_item_selector' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'simple_item_selector' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'simple_item_selector' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'simple_item_selector' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_change_control' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_change_control' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_change_control' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_change_control' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_change_control' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

warning gui/draw: Text: text is too wide for the canvas and will be clipped.

warning gui/draw: Text: text is too wide for the canvas and will be clipped.

warning gui/draw: Text: text is too wide for the canvas and will be clipped.

warning gui/draw: Text: text is too wide for the canvas and will be clipped.

warning gui/draw: Text: text is too wide for the canvas and will be clipped.

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_create_game' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_create_game' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_create_game' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_create_game' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_create_game' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_method_selection' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_method_selection' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_method_selection' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_method_selection' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_method_selection' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_server_list' Failed

new widgets # 1 resolution  800x480

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_server_list' Failed

new widgets # 1 resolution  800x600

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_server_list' Failed

new widgets # 1 resolution  1024x768

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_server_list' Failed

new widgets # 1 resolution  1280x1024

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

src/tests/gui/test_gui2.cpp(173): error in "test_gui2": Test for 'mp_server_list' Failed

new widgets # 1 resolution  1680x1050

Exception caught: Condition '!must_exist || result' failed at src/gui/auxiliary/find_widget.tpp:75 in function 'find_widget'..

(Reproduced on All)
Release: 1.11.11+
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-05**

**ai0867 wrote:**

> I've 'fixed' this by disabling the run of the tests with new_widgets set to true.

**Comment by Vultraz** [comment]
GUI2's `new_widgets` mode hasn't been maintained in years (outside one or two small fixes). The tests failing would be the least of the problems with them.

**Comment by CelticMinstrel** [comment]
Given its lack of maintenance, I wonder if it's even worth keeping that old code around... >_>
