### ISSUE TITLE
mp_connect unit tests fail (GNA #21748)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1370]
**[Original submission](https://gna.org/bugs/index.php?21748)** by fendrin on 2014-03-03

src/tests/test_mp_connect.cpp(141): error in "flg_map_settings": check side_engine->flg().choosable_factions().size() # 1 failed [7 != 1]

src/tests/test_mp_connect.cpp(142): error in "flg_map_settings": check side_engine->flg().current_faction()["id"] # "Custom" failed [Random != Custom]

src/tests/test_mp_connect.cpp(149): error in "flg_map_settings": check side_engine->flg().choosable_factions().size() # 1 failed [8 != 1]

src/tests/test_mp_connect.cpp(157): error in "flg_map_settings": check side_engine->flg().choosable_factions().size() # 1 failed [7 != 1]

src/tests/test_mp_connect.cpp(164): error in "flg_map_settings": check side_engine->flg().choosable_factions().size() # 1 failed [7 != 1]

src/tests/test_mp_connect.cpp(165): error in "flg_map_settings": check side_engine->flg().current_faction()["id"] # "Rebels" failed [Random != Rebels]

src/tests/test_mp_connect.cpp(179): error in "flg_map_settings": check side_engine->flg().choosable_factions().size() # 1 failed [7 != 1]

src/tests/test_mp_connect.cpp(180): error in "flg_map_settings": check side_engine->flg().current_faction()["id"] # "Custom" failed [Random != Custom]

src/tests/test_mp_connect.cpp(187): error in "flg_map_settings": check side_engine->flg().choosable_factions().size() # 1 failed [8 != 1]

src/tests/test_mp_connect.cpp(225): error in "flg_map_settings": check side_engine->flg().choosable_leaders().size() > 1 failed

src/tests/test_mp_connect.cpp(226): error in "flg_map_settings": check side_engine->flg().current_leader() # "random" failed [null != random]

src/tests/test_mp_connect.cpp(271): error in "flg_map_settings": check side_engine->flg().choosable_genders().size() # 1 failed [3 != 1]

src/tests/test_mp_connect.cpp(272): error in "flg_map_settings": check side_engine->flg().current_gender() # "female" failed [random != female]

src/tests/test_mp_connect.cpp(287): error in "flg_map_settings": check side_engine->flg().choosable_genders().size() # 1 failed [3 != 1]

src/tests/test_mp_connect.cpp(328): error in "flg_map_settings": check side_engine->flg().current_gender() # "male" failed [female != male]

src/tests/test_mp_connect.cpp(353): error in "flg_no_map_settings": check side_engine->flg().current_faction()["id"] # "Custom" failed [Random != Custom]

(Reproduced on All)
Release: 1.11.11+
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Vultraz** [comment]
Long since stopped happening.
