### ISSUE TITLE
MP campaign leader random gender change (GNA #21753)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1371]
**[Original submission](https://gna.org/bugs/index.php?21753)** by sigurdfdragon on 2014-03-04

In the campaign section under Multiplayer:

If you choose a unit for your leader that has more than one gender option, in subsequent scenarios, the gender (as shown by the unit's image and language name) can change, though the portrait will remain the correct one.

This is shown through the 3 attached pictures. It seems likely that the display of 'Random' for the gender in step_2_glitch.jpg is part of the issue.

This occurs 1/2 of the time when selecting a unit that has two gender options.

(Reproduced on Win 7 x64)
Release: 1.11.11+dev
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-04**

**sigurdfdragon added attachment:** [step_2_glitch.jpg](http://gna.org/bugs/download.php?file_id=20255)

**sigurdfdragon added attachment:** [step_1_choice.jpg](http://gna.org/bugs/download.php?file_id=20254)

**sigurdfdragon added attachment:** [step_3_result.jpg](http://gna.org/bugs/download.php?file_id=20256)

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-26**

**sigurdfdragon wrote:**

> Perhaps this should be considered a minor bug, my own usage decided that [side] locks to prevent the behavior.
> 
> 
> 
> However, this would still be relevant in an mp campaign where the author wanted to allow the player the option of changing faction/leader between each scenarios. In such a case, if the player wanted to keep his leader selection, and it had two gender options, he would have to keep specifying the gender each time, otherwise he could get the bug occurring.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-11**

**thunderstruck changed severity:** 3 - Normal -> 2 - Minor

**thunderstruck wrote:**

> This should be partially fixed in https://github.com/wesnoth/wesnoth/commit/cec331c11b4d85f7f37b127d0373e14a76b6d475.
> 
> 
> 
> I made it so that if 'gender' attribute exists, leader would be assigned to that gender by default.
> 
> 
> 
> To fully fix this one, we should reload portrait information so that switching between genders would not cause such problems.
> 
> 
> 
> I'm lowering priority of this since due to recent changes.

**thunderstruck changed priority:** 5 - Normal -> 3 - Low

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-14**

**anonymous wrote:**

> > However, this would still be relevant in an mp campaign where the author wanted to allow the player the option of changing faction/leader between each scenarios
> 
> 
> 
> I actualy don't know of any such campaign, do you?

**Comment by cooljeanius** [comment]
@sigurdfdragon

**Comment by sigurdfdragon** [comment]
No.
Tested in Windows 10 / Steam BfW 1.17.22
