### ISSUE TITLE
make chat history a smart (drag-selectable and copyable) text box (GNA #21755)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1372]
**[Original submission](https://gna.org/bugs/index.php?21755)** by involution on 2014-03-05

Actually in my view the main purpose of this would be to allow players to chat hyperlinks to eachother. As a possibly easier alternative, perhaps <link> http://... </link> could be rendered as a hyperlink?

(Reproduced on N/A)
Release: 1.11
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-05**

**shadowmaster wrote:**

> For the feature suggested in the subject we first need a GUI2 multiline textbox widget, which doesn't exist yet.
> 
> 
> 
> For the feature suggested in the OP we need link-aware GUI2 labels, which I am not sure how it'd work given that Pango doesn't have a link tag or concept AFAIK.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-07**

**involution wrote:**

> For the feature in the subject:
> 
> 
> 
> If implemented, it would be great if the :inspect dialog were also copyable, that would be quite handy in my opinion.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-21**

**shadowmaster wrote:**

> I have added a copy button to gui2::tchat_log (on [9b065fd9a0dd066418c4b0b1c1aa304f7889a015 master] and [1.12](s://github.com/wesnoth/wesnoth/commit/799e09d94a4774854ddd29fbb9bd1362105da9cd)) and gui2::tgamestate_inspector ([master](s://github.com/wesnoth/wesnoth/commit/eab3e6fb646fda8cc6101a3e568c86c2b17b707f) and [1.12](s://github.com/wesnoth/wesnoth/commit/6a56da5f0f60558f0c15206a92b91a612a4dc5da)) as a convenience while this gets implemented. It'd be nice if future entries for this issue were focused on the former, though; you can file a separate FR for gui2::tgamestate_inspector.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-11-19**

**involution wrote:**

> Just an update: I did figure out how to automatically detect and render hyperlinks in gui2 labels, and make them clickable.

**Comment by Wedge009** [comment]
As a work-around, one can use Alt-C and get hyperlinks rendered as hyperlinks that way. As for the MP chat system as a whole, it sounds like that's covered by the (quite big, I would say) request of #1179.
