### ISSUE TITLE
when reloading a game, mp_connect could display chosen faction rather than custom (GNA #21764)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1373]
**[Original submission](https://gna.org/bugs/index.php?21764)** by involution on 2014-03-06

I find that it always detects a custom faction even when I use default era... Not sure what code is relevant here or what it is supposed to do but it seems to be bugged.

(Reproduced on linux)
Release: 1.11.11
Priority: 2
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-06**

**involution changed priority:** 5 - Normal -> 3 - Low

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-08**

**thunderstruck wrote:**

> Custom faction should be chosen if side has 'recruit' set to something.
> 
> 
> 
> Please provide a test case if you really think this is broken.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-08**

**involution wrote:**

> I see, I think I just didn't understand the intended behavior. It makes sense to me now. With this logic it should always display "custom" in a reloaded game I guess.
> 
> 
> 
> I'm changing this to a feature request to display the chosen faction from the given era if possible, rather than "custom", for reloaded games.

**involution changed title:** faction detection when reloading in mp_create dialog seems broken -> when reloading a game, mp_connect could display chosen faction rather than custom

**involution changed category:** Bug -> Feature Request

**involution changed priority:** 3 - Low -> 2

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-08**

**gfgtdf wrote:**

> Deassigning bugs from inactive developers.

**Comment by Vultraz** [comment]
This no longer appears to be an issue. I tested with an MP save from a few months ago and the faction was set to Custom, but recent saves (past few days) properly display the faction name in MP Staging... can someone else confirm this? @Wedge009 ?

**Comment by Wedge009** [comment]
I'm not sure if I'm testing it correctly or I might have closed this already. But it seems okay to me (loading MP game from MP lobby - then again loading from the main menu takes you straight to the game).

I didn't get any indication of a custom faction in Dark Forecast either.

**Comment by Vultraz** [comment]
You probably have debug mode off, so don't see the AI sides. Still, this seems fixed. Closing.

**Comment by Wedge009** [comment]
Oh right, I missed the bit about AI sides. Agree with closing anyway.
