### ISSUE TITLE
unexpected death animation (GNA #21804)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1379]
**[Original submission](https://gna.org/bugs/index.php?21804)** by anonymissimus on 2014-03-16

insert the following code into mp scenario 2p_Hamlets.cfg:

+```+

	[event]

		name=turn 1

		{UNIT 2 Troll 10 5 (hitpoints,id=0,kill_me)}

		[set_menu_item]

			id=kill

			description=_"kill"

			[command]

				[kill]

					id=kill_me

					fire_event=yes

					animate=yes

				[/kill]

			[/command]

		[/set_menu_item]

	[/event]

	[event]

		name=last breath

		[filter]

			id=kill_me

		[/filter]

		[kill]

			id=$unit.id

			animate=yes

		[/kill]

		{UNIT 1 Troll $x1 $y1 (id=should_live)}

		[message]

			id=should_live

			message=_"I should live!"

		[/message]

	[/event]

-```-

Start a game and click the right-click menu added above. This first kills kill_me and plays according animation, but also plays the animation a second time for should_live. should_live is still alive although not visible afterwards (present in the unit_map as shown by :inspect), he's just not displayed until clicking his location.

Note that it doesn't happen if kill_me is killed by an attack of the near leader.

(Reproduced on any)
Release: 1.11.11+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-17**

**involution wrote:**

> I wonder if it has anything to do with failure of some of the unit tests of the unit_map object:
> 
> 
> 
> chris@chris-KLR650 ~/wesnoth-src/clone/wesnoth-old $ ./test
> 
> ...
> 
> src/tests/test_unit_map.cpp(236): error in "track_real_unit_by_iterator": Iterator should be invalid after extraction and reinsertion.
> 
> src/tests/test_unit_map.cpp(272): error in "track_fake_unit_by_iterator": Iterator should be invalid after extraction and reinsertion.
> 
> ...
> 
> 
> 
> There have been a lot of bugs noticed with animations / animation pointers lately: 
> 
> 
> 
> - mattsc notices animation segfault caused by "double kill" (rapidly hitting ctrl+k in debug mode on a unit)
> 
> at this line:
> 
> 
> 
> https://github.com/wesnoth/wesnoth-old/blob/30c3a9c287a0e3420c918181a6de6b79e01c2b2f/src/unit_animation.cpp#L1428
> 
> 
> 
> - EP: segfaults with animations of lua units, if i understand correclty... https://gna.org/bugs/?21765
> 
> 
> 
> 
> 
> 
> 
> Basically all of these are caused because animations are only tied by a weak (naked) pointer to the unit. When the unit is removed the animation doesn't have any way to know.
> 
> 
> 
> I wonder if the lack of safe pointers is causing that the animation doesn't get removed from the list of pending animations before the second unit takes the place of the first unit, with the result that the animation plays through for both. (This might make sense if some of the animation status data is stored with the unit, for example.)

**Comment by stevecotton** [comment]
Can't reproduce on 1.15.6+dev, nor on 1.14.14+dev (b85c5dc8adbc7c2ece48be3f1441aac8a67e6894)
