### ISSUE TITLE
Map editor does not preserve unknown properties (GNA #21859)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1380]
**[Original submission](https://gna.org/bugs/index.php?21859)** by dindoz on 2014-03-23

_ Made a map_scenario.cfg with the editor for being able to use all cool new option 

_ generate map and add some unit and side

_ save the map_scenario

_ open the map_scenario.cfg with Kwrite for exemple.

_ add some capacity to some units or side that cant be added by the editor.

_ save the file, open it with the editor and save the map_scenario.cfg.

: All capacity manually added are gone...

(Reproduced on ubuntu 13.10)
Release: 1.11.11
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-03-24**

**dindoz added attachment:** [aaa.cfg](http://gna.org/bugs/download.php?file_id=20427)

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-05**

**fendrin changed status:** None -> Postponed

**Comment by Wedge009** [comment]
I don't profess to know much about how the internal editor is used, but I would expect that if one is doing some manual work on a map file that the editor doesn't handle, then of course re-saving that file within the editor would discard all the manual work.

I'm inclined to treat this as invalid - what sort of things do folks need to do that can't be applied with the internal editor?

**Comment by gfgtdf** [comment]
> what sort of things do folks need to do that can't be applied with the internal editor?

well there is some stuff like unit variables or modifications/objects, but all thouse things can also be added via [modify_unit] in events i think.

The real problem here is how poorly the editor is documented, you are not supposed to modify the editor generatd file, instead  it is iirc supposed  to used is to include the editor file in the real scenario like
```
[scenario]
  ## edito generated scenario file
  {~/add-ons/my_addon/maps/scenario1.cfg}
  [event]
    ## do stuff
  [/event]
[/scenario]
```

**Comment by jostephd** [comment]
> The real problem here is how poorly the editor is documented, you are not supposed to modify the editor generatd file, instead it is iirc supposed to used is to include the editor file in the real scenario like

In this case, let's:

1. Make the cfg files generated by the editor start with a hard-to-miss comment saying `Do not edit this file manually. Changes will be lost. Do this instead: (here put the code @gfgtdf posted)`

2. Let's make the editor error out if the file it loaded has a key or tag that the editor doesn't know how to generate.

(I mean, personally I would have expected the editor to leave unmodified any tag, attribute, or comment it doesn't know about, but if we don't have that, let's at least not lose data.)

**Comment by gfgtdf** [comment]
> Make the cfg files generated by the editor start with a hard-to-miss comment saying

This is s good idea I think.


>  I mean, personally I would have expected the editor to leave unmodified any tag, attribute, or comment it doesn't know about, but if we don't have that, let's at least not lose data

Iirc we partly tried to implement this, and it does apply to come cases, but some things like comments are really impossible to keep since the config ovjevtbdies not keep them.

**Comment by vgaming** [comment]
Indeed, adding a comment that the file should never be edited manually would be a possible solution.

I was thinking of preserving the properties, but it seems to be non-trivial upon further consideration.

The solution of adding such comment (or maybe also adding read-only filesystem flag?) is easy to do, right?

**Comment by jostephd** [comment]
Adding a comment should be easy.

I'm not sure about marking read-only in the filesystem. That would mean the editor would have to automatically ignore read-onliness of files, and it probably shouldn't do that.

**Comment by stevecotton** [comment]
> Make the cfg files generated by the editor start with a hard-to-miss comment saying

Created PR #5001 for this, which could be backported to 1.14 too.
