### ISSUE TITLE
Units with many [advancement] tags cause graphic slowdowns (GNA #21884)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1381]
**[Original submission](https://gna.org/bugs/index.php?21884)** by anonymous on 2014-04-01

Units with too many [advancement] tags cause irrational slowdowns. In the save file I provided, they cause quite a huge CPU usage. Sometimes, it goes even to FPS drops. It seems that the [advancement]s are somehow processed every time a frame is rendered.

(Reproduced on All)
Release: 1.10
Priority: 2
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-01**

**anonymous added attachment:** [Slowdowns.gz](http://gna.org/bugs/download.php?file_id=20452)

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-03**

**anonymous wrote:**

> I investigated it deeper and found out that it didn't use more CPU cycles than other units with the same number of animations. I am very sure that I have seen a single unit with a standing animations eating like 70% CPU on a 2.21 GHz processor in the past, but I believe proper experiments more than witnesses, even if I am the witness. The cause must have been elsewhere.
> 
> 
> 
> Please delete this.
> 
> 
> 
> The original poster

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-22**

**involution wrote:**

> Marking invalid at OP's request (apparently).

**involution changed status:** None -> Invalid

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-22**

**shadowmaster closed the issue**

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-26**

**gfgtdf changed status:** Invalid -> None

**gfgtdf wrote:**

> i can reproduce this issue.
> 
> 
> 
> The reason is that we want to know whether a unit can advance to decide for the color of the xpbar. To do this we check for all possible advancements whther we have already [advancemnt]s with that id.
> 
> 
> 
> Stacktrace:
> 
> 1) controller_base::play_slice(bool)
> 
> 2) display::draw(bool,bool)
> 
> 3) game_display::draw_invalidated(void)
> 
> 4) display::draw_invalidated(void)
> 
> 5) unit_drawer::redraw_unit(class unit const &)const
> 
> 6) unit::can_advance(void)const
> 
> 7) unit::get_modification_advances(void)const
> 
> 8) unit::modification_count(class std::string const &,class std::string const &)const
> 
> 
> 
> AND
> 
> 
> 
> 6) unit::xp_color(void)const
> 
> 7) unit::get_modification_advances(void)const
> 
> 8) unit::modification_count(class std::string const &,class std::string const &)const

**gfgtdf reopened the issue**

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-27**

**gfgtdf changed priority:** 5 - Normal -> 2

**gfgtdf wrote:**

> Ok i think https://github.com/wesnoth/wesnoth/pull/226 caused a lot of speedup in this case.
> 
> 
> 
> Also it seems like the slowdown by many advancements is O('number of [advance]' * 'number of [advancement]') or similar, since there are known workarounds against having very much [advancement]s in a unit i'm decreasing this bugs priority.

**gfgtdf changed severity:** 3 - Normal -> 2 - Minor

**Comment by Wedge009** [comment]
Marking @gfgtdf as a commenter on this issue.

**Comment by Wedge009** [comment]
I was never able to replicate this one, but could it possibly be closed with the merging of #6855?

**Comment by soliton-** [comment]
Since the slowdown seems to be in going through all the advancements I doubt a graphics code change is able to fix it.

Since the slowdown is apparently not that big anymore and it seems required to go through the advancements anyway I'd say this is at most an enhancement/optimization request now. Probably better to close this. If it's an actual issue for someone still then it can be reopened or a new issue filed.
