### ISSUE TITLE
sound and music lags/screech sometimes if a lot of sound acitivity is produced (GNA #21937)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1384]
**[Original submission](https://gna.org/bugs/index.php?21937)** by laza on 2014-04-19

i play in an VM with Windows 8.1 Update 1, 4 GB RAM, 2 CPU cores, 2D and 3D video acceleration, 196 MB GPU

to reproduce this bug, change the resolution to maximum my LCD can handle: 1920x1200

- play a bit

- if an unit attacks three times, the attacking sound lags and is only two times created(?)

- if a lot of units heal/cure the sound screechs and seldom the music breaks

- sometimes the music breaks

maybe this is a problem of the VM and not for BfW, but i tested a bit and if i change the game speed to 0,5 the sound and is correct and no abnormal behavior.

also the resolution has an impact cause it got much worse if i change the resolution to the maximum.

Host: Xubuntu 14.04

VirtualBox 4.3.10

Guest: Windows 8.1 Update 1

(Reproduced on Windows 8.1)
Release: 1.11.12
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-20**

**coffee wrote:**

> What happens if you increase the length of the sound buffer to say 4096 in the advanced are of sound preferences?

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-21**

**laza wrote:**

> I is 4096 - but i can't remember, that i changed it.
> 
> Is this the new standard?
> 
> 
> 
> I made a new VM to test/verify this bug and did not touch anything but the resolution and sound + music volume.
> 
> --> now, i changed GPU to 256 MB max.
> 
> maybe i have today a bit time to do some more tests...
> 
> 
> 
> If i can do something to hunt this bug down let me know.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-05-25**

**laza wrote:**

> Okay, to verify the bug, i created a new VM:
> 
> 
> 
> VirtualBox 4.3.12 (repo in Trusty 64 bit)
> 
> Windows 8.1 Update 1 - 32 Bit (straight installed and updated)
> 
> BfW 1.11.13
> 
> 
> 
> The lag at a attack is as worse as described, just about a second, so the first attack is soundless, the second gets the sound from the first and so on... at least there is an attack sound even it is finished.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-15**

**shadowmaster wrote:**

> Since I tend to get noise and lag (under 0.3 seconds) in sounds played by any application running under a Windows guest in VirtualBox, and you mentioned that the guest display resolution has an impact, I'm more inclined to suspect this is a problem with VirtualBox itself and not Wesnoth.
> 
> 
> 
> Nevertheless, if it isn't much trouble for you (i.e. if you don't mind the big download), is there any chance you could try Wesnoth 1.11.11 and compare the results? There was a minor change to our mixer setup in 1.11.12:
> 
> 
> 
> ```
> 
>    * Increased the sound mixer channel allocation from 16 to 32, thereby
> 
>      raising the limit for simultaneous sound effects from 5 to 21.
> 
> -verbatim

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-21**

**laza wrote:**

> Okay, i could solve this problem thanks to the ubuntuusers forum:
> 
> 
> 
> Changing the Audio - Audio Driver from PulseAudio to ALSA the lag is gone and works smooth with music and all!
> 
> 
> 
> Tested with 1.11.15

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-17**

**wedge009 wrote:**

> Glad to know this seems to be resolved by switching to ALSA. It begs the question whether this is still an issue with the current state of PulseAudio, though.
> 
> 
> 
> Also, any particular reason you're playing in a Win8 VM and not your Xubuntu host itself?

**Comment by Wedge009** [comment]
Issue is with regards to playing in a VM. Unconfirmed and no further input. Closing.
