### ISSUE TITLE
Cannot switch between desktops or use Mission Control, while in Full-Screen mode (GNA #21943)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1385]
**[Original submission](https://gna.org/bugs/index.php?21943)** by generous on 2014-04-20

When I launch Battle for Wesnoth in full screen mode, it is impossible to switch between applications.

I cannot swipe between desktops using trackpad, and F3 button - "mission control" - is not working.

Command+H shortcut, instead of hiding the application's window, just turns it into the black screen!

I find it unacceptable that this severe bug is still not fixed, despite so many updates have passed.

There is no such problem at Windows version: you can hide BfW window easily, by pressing "Win" key

(Reproduced on Mac OS X)
Release: 1.11.12 (1.12 beta 3)
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-21**

**yaiyan wrote:**

> I posted this on the forums, but I figured I could copy it here too.
> 
> 
> 
> Nice fullscreen on OS X seems to be a bit of a pain.
> 
> 
> 
> https://developer.apple.com/library/mac/documentation/graphicsimaging/Conceptual/QuartzDisplayServicesConceptual/Articles/DisplayCapture.html
> 
> 
> 
> Going fullscreen captures the display which gives your application exclusive usage, which obviously isn't very good if you want to allow other apps a chance to be used as well (ie, by swiping left/right).
> 
> 
> 
> Apples solution appears to be to make a borderless window the size of the display. SDL also seems to have some flags for this (SDL_WINDOW_FULLSCREEN_DESKTOP), but from what I've read just blindly using this flag minimises the window when focus is lost, but there are other flags to disable this.
> 
> 
> 
> I can't test this out though, haven't got SDL set up for development on my laptop, and my computer's running Linux, but hopefully this helps as a headstart to anyone wanting to fix this.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-04-22**

**involution wrote:**

> I am downgrading the severity, although not the priority, of this bug and a similar one (https://gna.org/bugs/?21956) to "2 - minor". 
> 
> 
> 
> Reasons: 
> 
> The bug does not make the game unplayable or unusable in some circumstance, which would make it "5 - blocker".
> 
> The bug only occurs in select circumstances, e.g. when using / toggling fullscreen window status.
> 
> The consequences of the bug are purely cosmetic and don't damage the game state.
> 
> The bug is easily worked around.
> 
> 
> 
> Please note that this is not a statement that we don't care about the bug or that it isn't a priority to
> 
> fix it, just that it doesn't compare in terms of severity with other bugs with a 3 or 4 severity rating. 
> 
> 
> 
> I'm also including a link to some helpful comments yaiyan made on the forum about how to fix it (there were some comments about SDL 1.2 vs 2.0 not appearing below). http://forums.wesnoth.org/viewtopic.php?f#5&t40217&start=15#p569617

**involution changed severity:** 4 - Important -> 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-29**

**shadowmaster changed status:** None -> Upstream Problem

**Comment by singalen** [comment]
Just tested 1.14.0 (in MacPorts build, though), most of it didn't reproduce.

* Swipes work. F3 is no longer "mission control" shortcut; Ctrl-Up works. 3-swipe-Up "mission control" works. 3-swipe-aside to switch between screens works.

* Cmd-H is disabled in fullscreen; needs to be tested in XCode build. Will update this comment.

**Comment by Wedge009** [comment]
1.14 introduced SDL 2 so I was wondering if this is still a valid issue. Please advise if it needs to be kept open.

**Comment by hrubymar10** [comment]
I'll assign myself. AFAIK the default fullscreen doesn't work, but if you will use windowed mode instead and use macOS' ability to create fullscreen window than everything works just fine. I am wondering if we can change wesnoth's fullscreen to this macOS' fulscreen window...

**Comment by Wedge009** [comment]
Given the age of the original report and matt's confirmation of expected functionality in current builds, I agree. hrubymar can always re-open if it's still an issue.
