### ISSUE TITLE
mp server has trouble with "local player" option in campaigns (GNA #21965)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1387]
**[Original submission](https://gna.org/bugs/index.php?21965)** by involution on 2014-04-23

gfgtdf pointed out that the mp server reports errors with controller types when transitioning scenarios, if the host has some sides controlled by a "local" player. (Note that the bug only affects the use of "local" sides when in a networked context.)

This can be reproduced easily using LoW inserting at Chapter 3. When finishing the level, the server reports "Side 7 had no controller! ..." on making the transition.

AFAICT the problem is that game:update_sides_data() doesn't have any special handling for these sides, nor any obvious way to create it. (We could specially handle player name "Anonymous local player", but not if this is internationalized...)

We discussed on irc, and it was agreed to postpone this. Some reasons are

- The fix is most likely server side and could happen after 1.12.0

- This probably didn't work properly in 1.10 and no one seems to have complained.

- Most likely that's because there are workarounds, like using two clients, or assigning the "local" sides to the host's control.

See top of: http://www.wesnoth.org/irclogs/2014/04/%23wesnoth-dev.2014-04-24.log

(Reproduced on Linux Mint 16)
Release: 1.11.13
Priority: 3 - Low
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-07-23**

**gfgtdf wrote:**

> might be fixed in 1.13 some time ago, in any case removing postponed since 1.13 came out some time ago

**gfgtdf changed status:** Postponed -> Ready For Test

**Comment by Vultraz** [comment]
I tested this with Oath of Allegiance, with me controlling one side and the other set to Local player. I didn't see any issues.

**Comment by Vultraz** [comment]
Ok, just for the record, I did noticed a few odd inconsistencies, but they may be intentional.
* When proceeding to the next scenario scenario, the previously local sides are again available for network players to join. This seems reasonable.
* When reloading a save where one player was local, the side is assigned to you. Ie, when I had one side assigned to "vultraz" and the other "Local player", both were assigned to "vultraz" on reload.

Tagging @gfgtdf for thoughts.

**Comment by gfgtdf** [comment]
hmm this still sounds like bugs to me, i mean it's not that bad but i see little reason to give people the option to assign 'local player' in the networked game to a side in the first place.

There is a related featurerequest #1041 that might require having somethign like this though but i don'T think it'll be implemented soon.

**Comment by Vultraz** [comment]
@gfgtdf I suppose in some very rare situations two people might be playing a MP game on the same computer... or more common someone might be playing two sides maybe? I dunno. I can probably disable Local Player in MP mode if you think I should.
