### ISSUE TITLE
Village count incorrect after map resize (GNA #22090)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1390]
**[Original submission](https://gna.org/bugs/index.php?22090)** by beetlenaut on 2014-05-26

When you resize the map in the editor, the village count at the top of the screen is not updated. If villages were lost in the resize, the count will be incorrect.

(Reproduced on Linux)
Release: 1.11.15
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-03**

**involution wrote:**

> Does this also affect wml resize / overlay events?

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-21**

**shadowmaster wrote:**

> From a quick test with the "map change N" [replace_map] test cases in the test scenario, this doesn't appear to affect [replace_map]. I'd suspect that this is an editor-specific issue and thus it probably doesn't affect [terrain_mask] either.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-20**

**wedge009 wrote:**

> This is a tricky one, and I think requires someone who has actual working knowledge of the editor.
> 
> 
> 
> I had a go at removing villages from the gamemap::villages_ vector, since gamemap::on_board() will already let you know if a given map_location is within the resized board or not. This worked okay but I couldn't get the villages count at the top of the screen to update at the appropriate time.
> 
> 
> 
> Then there's the additional complication of villages that stay on the map after shrinking, but are right on the border and so can still be present if extending the map afterwards. I thought about forcing villages on the map border to become background terrain to force their deletion, but couldn't work out the various functions and event handlers. Even the interoperation between the tiles_ t_map and tdata_ tdata_cache isn't clear... not that they are very helpful member names either - it isn't clear that t_ in this context refers to terrain (I think).
> 
> 
> 
> So I'm giving up on this for now. I've stared at it all day hoping to get a breakthrough... but have nothing to show for it. ):

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-19**

**wedge009 changed status:** None -> Confirmed

**Comment by Wedge009** [comment]
This is a blast from the past. I'm glad @Vultraz was able fix the village count on map reduction. But the converse is still a problem, either:

- Adding a village at the very edge (outside the counted map area) and then extending the map, or
- Reducing the map such that one or more villages fall on the very edge (outside the counted map area) and then re-extending the map.

Both of these cases will still produce incorrect village counts. Granted, it's a boundary (ha ha) condition, but it's still a potential problem. At least the count being wrong doesn't appear to cause any crashes (eg the count doesn't go negative if you remove the villages while the count < actual).

**Comment by CelticMinstrel** [comment]
It seems appropriate to reopen this, then.
