### ISSUE TITLE
allow [end_turn] to say what side number has the next turn (GNA #22163)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1392]
**[Original submission](https://gna.org/bugs/index.php?22163)** by involution on 2014-06-08

Idea is that [end_turn] should have an attribute "next_side" which determines what the next value of "current_side" in the engine will be, so that you can easily transfer control to whatever team is desired.

Currently you can also do this by putting [end_turn] in "side turn" events for the teams who you don't want to have the next turn, but its cumbersome, may have other bad side effects, and is slow in networked mp because afaict you have to wait for all the clients to respond for each side that you want to skip...

(Reproduced on Linux Mint 16)
Release: 1.14.0
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by Vultraz** [comment]
Any updates on this?

**Comment by gfgtdf** [comment]
well the pr above is still open and it's not much left to do, but i currently have neigher time nor motivation to work on this, so it probably won't make it into 1.14
