### ISSUE TITLE
animation and right-click (GNA #22177)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1393]
**[Original submission](https://gna.org/bugs/index.php?22177)** by vanagandr on 2014-06-11

Right clicking seems to speed up animation. I encountered this first when using [animate_unit] in a right-click menu. I attached a test scenario for this (it prints the times it takes to play the animations, the total time of the animation is 350ms). You can animate the spearman via right-click menu (animation takes around 20 ms, far too quick) and via the hotkey a (animation takes around 350ms, so this is correct). 

This also works with attack animations: If you time your right-click to coinced with the start of an attack animation, the animation seems to be cancelled (but probably just plays so fast you can't see it) and the other unit plays its animation. That timing is harder to do than the right-click menu though.

(Reproduced on Windows 8)
Release: 1.11.15
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-11**

**vanagandr added attachment:** [animate_test.zip](http://gna.org/bugs/download.php?file_id=20980)

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-06-21**

**coffee wrote:**

> I believe the right click will pause the game to the observer by bringing up a menu, but the animation timer continues in the background. The animation then appears to fill in quickly to catch up with the timer. Seems like desired behaviour to me so that animations do the right thing (e.g. for multiplayer).

**Comment by Pentarctagon** [comment]
Closing since this was stated to be desired behavior.
