### ISSUE TITLE
number formatting errors in wml cache manager (GNA #22261)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1396]
**[Original submission](https://gna.org/bugs/index.php?22261)** by involution on 2014-07-02

Go to preferences -> general -> cache

to launch the WML cache manager dialog.

I get strange numbers displayed here for the size of the cache:

-2.5e+33 yiB

I had to look up what "yiB" stands for but apparently this means I have -2 * 10^30 * 2^80 bytes of storage used, or something like -10^60 bytes in my cache?

:p

I didn't test on 1.12 but I assume it's similar.

(Reproduced on Linux Mint 16)
Release: 1.13.0-dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-12-23**

**shadowmaster wrote:**

> Assigning to AI0867, since he wrote utils::si_string(). The underlying cause probably is a call with the following parameters:
> 
> 
> 
> ```
> 
>     utils::si_string(-1, true, _("unit_byte^B"));
> 
> ```
> 
> 
> 
> Here, this yields "-1.21e+24 yiB" somehow, which is equivalent to -1.21 B. I don't know why the numbers were different for iceiceice, seeing as how the parameter is actually a call to filesystem::dir_size(), which only returns one possible negative value (-1) to signify an error condition in the Boost.filesystem-based implementation.
> 
> 
> 
> I'm going to change the utils::si_string() caller (gui2::tgame_cache_options::update_cache_size_display()) to handle this border case correctly, so do not rely on it to reproduce the bug.

**Comment by jostephd** [comment]
@sevu Reopening since si_string() is still broken in exactly the way @shikadiqueen described.
