### ISSUE TITLE
extra keyboard sound volume keys don't work (GNA #22338)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1398]
**[Original submission](https://gna.org/bugs/index.php?22338)** by laza on 2014-07-14

Hardware:

Lenovo ThinkPad R61 - Type 8933

Software:

Edubuntu 14.04

Battle for Wesnoth installed via ppa:rhonda/wesnoth-devel

The ThinkPad has three extra keys for the sound volume (Mute, Volume down, Volume up) and these work(ed) with Edubuntu 12.04 and now 14.04 flawlessly (also with the installed Rhythmbox).

But in BfW the keys do nothing and it is real annoying to leave the game and set the volume and start the game again...

(Reproduced on Linux/Ubuntu)
Release: 1.11.15
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-06**

**wedge009 wrote:**

> This seems hardware or OS specific to me. If the OS has muted the volume, then no application - Wesnoth or otherwise - should have its audio go to the speakers (or whatever output you're using).
> 
> 
> 
> Volume buttons on my own laptops affect OS volume, which in turn should have an effect on Wesnoth's volume too.

**Comment by Wedge009** [comment]
Closing as hardware-specific and no further input.

**Comment by CelticMinstrel** [comment]
It would be cool though if the volume keys actually worked in Wesnoth. Mind you, on my computer, they control system volume, so there's no need for Wesnoth to care about them.

**Comment by Wedge009** [comment]
That's my point. The buttons go to the OS and any fault with their function would be with the OS handling of those buttons.
