### ISSUE TITLE
Village flag graphic displayed behind [item] images (GNA #22373)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1400]
**[Original submission](https://gna.org/bugs/index.php?22373)** by tekelili on 2014-07-21

This behavior is different from BfW 1.10 and it causes that custom village images used in a vllage overlay tile look bad because flag is displayed "behind" village.

I dont know cause, but it looks like village flag or [item] images changed their layer.

(Reproduced on Windows)
Release: 1.11.6
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-11**

**shadowmaster changed status:** None -> Confirmed

**Comment by Vultraz** [comment]
Fixed in accelerated_rendering.

**Comment by CelticMinstrel** [comment]
@ln-zookeeper  - To auto-close the issue you can't have any extra words between "fixes" and the issue number.
