### ISSUE TITLE
mousemove event. (GNA #22635)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1409]
**[Original submission](https://gna.org/bugs/index.php?22635)** by gfgtdf on 2014-09-14

i think a mousemove (wml or lua) event that triggers whenever the mouse enters a new hex would be useful.

(Reproduced on all)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by ProditorMagnus** [comment]
re #1268

**Comment by ProditorMagnus** [comment]
https://github.com/wesnoth/wesnoth/commit/b017a2b6b2d6c862af6fdec62c7be4d4f42a29e8

**Comment by CelticMinstrel** [comment]
The linked commit implements this.

**Comment by ProditorMagnus** [comment]
I hope it will be documented eventually. Currently I have no need for this functionality so wont be trying how it works myself.
