### ISSUE TITLE
Negative damage taken - miscalculated statistics (GNA #22726)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1410]
**[Original submission](https://gna.org/bugs/index.php?22726)** by anonymous on 2014-09-29

When a Ghost attacked a unit and received -1 damage (draining) instead of the expected 0, the statistics read +1150% damage taken.

The value seems odd, but more important less damage taken than expected should always be a negative number.

(Reproduced on Windows 7)
Release: 1.10.7
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-09-29**

**anonymous added attachment:** [bfw-statss-sm.jpg](http://gna.org/bugs/download.php?file_id=22441)

**Comment by Pentarctagon** [comment]
Closing since this no longer seems to happen with the redesigned statistics dialog.
