### ISSUE TITLE
mp-replay not loadable in mp-mode (GNA #22813)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1414]
**[Original submission](https://gna.org/bugs/index.php?22813)** by anonymous on 2014-10-15

When trying to load a multiplayer replay in multiplayer mode it fails; error message: 'The scenario is invalid because it has no id.' Same behavior whether 'Show replay' is checked or not.

The mp-replay will load in singleplayer mode (prompting the disclaimer).

Attached is the mp-replay I encountered this.

nuorc

(Reproduced on Windows 7)
Release: 1.11.17
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-15**

**anonymous added attachment:** [9p_�_Merkwuerdigliebe_replay-n1rfx.gz](http://gna.org/bugs/download.php?file_id=22644)

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-15**

**anonymous wrote:**

> we cannot add a "watch replays together with other players via network" before 1.12 .
> 
> I suggest detecting replays in mp loadgame and then changing the errormessage to something that exaplins the you have to watch replays via the sp loadgame dialog.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-18**

**anonymous wrote:**

> edit: ofc i meant "you cannot do it currently and we won't implement it in 1.12"

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-21**

**anonymous wrote:**

> If the 'Load' button has no functionality in mp-mode and won't have in 1.12 I think it should go. And the button in sp-mode shouldn't give an error warning.
> 
> nuorc

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-22**

**anonymous wrote:**

> sure it has functionality, you can still reload a game. You can just not watch a replay.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-22**

**anonymous wrote:**

> See how confusing this is? ;)
> 
> 
> 
> Anyway, I think the current state is not good; in sp-mode you get the message to use mp-mode, in mp-mode it's not working although there is even a check box for replays. Not really sure how it's intended to be. nuorc

**Comment by gfgtdf** [comment]
In 1.13 you don't get the 'use mp mode' message anymore, also in mp mode they checkbox for replay is disabled
