### ISSUE TITLE
[generator] failing in create a castle make BfW crash (GNA #22828)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1415]
**[Original submission](https://gna.org/bugs/index.php?22828)** by tekelili on 2014-10-18

If conditions inside [castle] make [generator] unable to create all of them, BfW will stop running and become closed.

(Reproduced on Windows)
Release: 1.11.17
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-18**

**anonymous wrote:**

> which generator do you use?
> 
> what is teh content of the stderr.txt=

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-18**

**tekelili wrote:**

> I used default [generator]. Never looked stderr.txt before, but it looked to me like all lines have date from a week ago (I think date is when I downloaded and instaled BfW 1.11.17)
> 
> 
> 
> To reproduce bug, looks enougth with give restrictive values inside [castle] keys
> 
>     valid_terrain=#some not very comon terrain on map generated
> 
>     min_distance=#some big number

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-18**

**tekelili wrote:**

> I forgot a little detail, to reproduce bug you also need a "big enougth" value in key players
> 
> 
> 
> players=#I was using 6

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-18**

**tekelili wrote:**

> Forgive me, I finally found the "true" stderr.txt. it says:
> 
> "20141019 02:16:47 error engine: No castle location found, aborting."

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-18**

**involution wrote:**

> Can you post scenario files for reproductions?

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-18**

**involution wrote:**

> tekelili: The line that makes that message is here:
> 
> 
> 
> https://github.com/wesnoth/wesnoth/blob/master/src/generators/map_generator.cpp#L1016
> 
> 
> 
> There's supposed to be some more parts to the message:
> 
> 
> 
> "No valid castle location found. Too many or too few mountain hexes? (please check the 'max hill size' parameter)"
> 
> 
> 
> So it might be intended that it won't make a map in this case, but it is wrong if wesnoth is closing... I guess it means that the code that calls the generator doesn't catch game::error? Not sure.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-10-19**

**tekelili added attachment:** [World_Conquest_II_for_bug_reproduction.rar](http://gna.org/bugs/download.php?file_id=22656)

**tekelili wrote:**

> Sorry for no attach files before, my scenario is quite complex and macromized and can not supply a reduced enveiroment. I attach my add on tweaked to reproduce bug:
> 
> 1- Host game 3p-World Conquest II
> 
> 2- Use debug in scenario 1
> 
> 3- use "n" for next scenario and BfW will crash
> 
> 
> 
> It looks like bug only happens for scenarios beyond 1 (I got error message with no crash for scenario1)
> 
> 
> 
> Files relevant for bug are:
> 
>  utils/maps/generator_provinces.cfg
> 
>  scenarios/3p/WC_II_3p_2D_Provinces.cfg
> 
> (file #22656)

**Comment by gfgtdf** [comment]
Is this still an issue?

**Comment by Wedge009** [comment]
I don't think I ever worked out how to try to replicate it. It sounded like tekelili was using some heavily customised stuff which somehow prevented the creation of the castle. Normal random map generation is pretty stable, isn't it?

**Comment by gfgtdf** [comment]
> Normal random map generation is pretty stable, isn't it?

Well yes but that's not the point, wesnoth should not crash unless you do something really crazy.

But I think it's quite unlikely that this is still an issue, so if you want you can close it.

**Comment by Wedge009** [comment]
Oh I fully understand there shouldn't be a crash but without knowing how to replicate the original issue it's pretty hard to resolve, isn't it? By stable I meant that it's not going to run into the situation where the castle isn't created, at least under normal circumstances.

**Comment by gfgtdf** [comment]
> without knowing how to replicate the original issue it's pretty hard to resolve, isn't it?

well it actually rather easy: use the standard map generator, go to settings maximum number of players, minimum size, maximum hill size should do it.

**Comment by Wedge009** [comment]
Tried what you suggested in 1.14.7 editor. Instead of crash I have the following message:
> Map creation failed.
> No valid castle location found. Too many or too fie mountain hexes? (please check the 'max hill size' parameter)

So at least we don't crash any more.
