### ISSUE TITLE
Wish: add dummy overlay (GNA #22907)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1417]
**[Original submission](https://gna.org/bugs/index.php?22907)** by tekelili on 2014-11-04

When I want fire some effects on a set of given locations, I can currently store locations, and using find_in and [clear_variable] build an appropiate filter...

...but given how filters work in WML, it would be much comfortable if I could place tiles with a "dummy" overlay with no effect, that allowed me use a simple location filter with no need of junky store location and etc :)

(Reproduced on any)
Release: 1.11
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-11-04**

**tekelili wrote:**

> Note, that I could do it myself, but I am asking to be added for multiplayer compatibility reasons.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-11-04**

**tekelili wrote:**

> Sorry for triple post... just also note that a dummy overlay would be also a very useful tool for [generator]

**Comment by stevecotton** [comment]
Triaging and closing this old wishlist item, as
* it's partially done, (see changelog for 1.15.3)
* choosing a better name for it is #2932
* getting it properly implemented and documented is part of #5070

Changelog for 1.15.3:
   * `[time_area]` can now be used without specifying a custom time schedule, this can in particular be used in the scenario editor if one just wants to mark an area to use in as `[event]`
