### ISSUE TITLE
Legend of Wesmere - Chapter 3 - Olurf's loyal units do not have icon (GNA #22940)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1421]
**[Original submission](https://gna.org/bugs/index.php?22940)** by anonymous on 2014-11-10

Olurf's loyal units do not have the icon which indicates they are loyal.

(Reproduced on Windows)
Release: 1.11.19
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-18**

**inky wrote:**

> In addition, the two Elvish scouts on Galtrid's side at the beginning of scenario 3 Kalian Under Attack have the loyal overlay, but are not loyal.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-24**

**wedge009 wrote:**

> In 1.13.1+dev, Kalian Under Attack, Galtrid now only has one scout and neither it nor any other of his units have the loyal icon overlay nor the loyal trait.
> 
> 
> 
> For Olurf in chapter 3, I could not find where Olurf picks up loyal units. Does he still have loyal units without the loyal icon overlay? If he does, can you provide a save file?

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-24**

**wedge009 wrote:**

> Thanks for your confirmation.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-12-18**

**inky wrote:**

> Now in 1.12.5 and 1.13.2 Galtrid's two scouts both have the overlay but only one has the loyal trait.
> 
> 
> 
> Also (I think in both 1.12 and 1.13) Olurf's loyal units (defined in the utils/characters cfg file) have the loyal trait but not the overlay.

**Comment by stevecotton** [comment]
There's still a bug with the scouts, and I'll add the fix to PR #2556.

Scenario 3, Kalian Under Attack: there are two scouts with loyal overlays, on 22,21 and 24,21. In MP mode, both are loyal (with correct overlays), and the players get one each. In SP mode, only one is loyal, but both still get the overlays.
