### ISSUE TITLE
No longer possible to deselect unit with left click (GNA #22952)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1422]
**[Original submission](https://gna.org/bugs/index.php?22952)** by ravana on 2014-11-13

Previously (1.10) clicking out of reachable map during own turn and clicking out of unit during other turns would deselect unit. This is most relevant for touchpad, as rightclick is more difficult to send there.

Another reason why this is problem is that esc can not be set to deselect unit.

Same problem for 1.13-dev.

(Reproduced on Windows 7)
Release: 1.11.19
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by ProditorMagnus** [comment]
Yes, I have got used to 1.12 way by now.

**Comment by CelticMinstrel** [comment]
@ProditorMagnus Since you're the original submitter (right?), I'll take that as a request to close this. Feel free to complain if I misunderstood.
