### ISSUE TITLE
a whispered text is not always in the blue color (GNA #22986)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1426]
**[Original submission](https://gna.org/bugs/index.php?22986)** by slowthinker on 2014-11-23

First time I received a whisper after the installation of BfW 1.12.0, the text

_<whisper: XYZ> text_

was white only.

Though I don't know how to recreate the bug: even after a restart of BfW any received whisper was blue.

(Reproduced on Win XP)
Release: 1.12.0
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-11-24**

**slowthinker added attachment:** [wesnoth chat.png](http://gna.org/bugs/download.php?file_id=22962)

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-11-24**

**slowthinker wrote:**

> the bug happens quite often: see the attached file as an example

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-05-30**

**shadowmaster wrote:**

> This can be reproduced more easily if you whisper yourself and then resize the window. Any changes to a GUI1 textbox's layout result in the text colors being reset because textboxes don't keep track of the colors of individual lines, so when the text is rendered again for the new layout it just uses the default color.
> 
> 
> 
> It is possible to fix this, but it's relatively non-trivial.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-20**

**wedge009 changed status:** None -> Fixed

**wedge009 wrote:**

> I think this is resolved with the new gui2-based MP lobby in 1.13.7. I checked the window resizing too. Do we want to keep this open for 1.12.x? Otherwise I was going to close it.

**Comment by Wedge009** [comment]
Why not fixed? Is it because it's still valid for 1.12.x?

**Comment by Vultraz** [comment]
Not valid anymore in 1.13.x. The chat UI has been totally redesigned.
