### ISSUE TITLE
modifying units stats by lua (GNA #23004)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1430]
**[Original submission](https://gna.org/bugs/index.php?23004)** by anonymous on 2014-11-30

currecntly lua is only able to set/get the easiest unit stats, that is more or less the [unit] attributes but not the child tags.

The result is, that when you want to modify for example the units attacks or abilities, then you have to store/unstore the unit in wml. This is often not very efffective, for example unstoring a unit from a wmltable results in all [effect]s from objects/advancements/traits beeing applied first and then the units stats beeing overwritten by what is given in the wml table.

This is also the main reason why we currently cannot have custom [effect]s implemented in lua: Currently for more complicated unit modification we need to unstore the unit which would then result in infinite recursion if it's done inside a [effect].

(Reproduced on )
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-29**

**anonymous wrote:**

> partly implemented in https://github.com/wesnoth/wesnoth/commit/43c10ec0ccc88c6deeed85c96646a9c0782502df. attacks can now be changes and inspected, it is still not possible to remove or to add new attacks.

**Comment by Vultraz** [comment]
@CelticMinstrel allowed adding, removing, and replacing attacks via the Lua interface in 31f783b86dd6d4e5134b6046ccb261f5b95e0b4b.

As far as I can tell, we still don't have an interface to manage abilities...

**Comment by CelticMinstrel** [comment]
Not with direct access to the unit userdata, no; you can of course use `add_modification` though.

**Comment by Pentarctagon** [comment]
@CelticMinstrel is this issue still valid?

**Comment by CelticMinstrel** [comment]
I kind of doubt it. There may be a few things that can't be edited in Lua, but if such are found a separate issue can be opened.
