### ISSUE TITLE
Custom Mod/Core GUI2 theme and font support (GNA #23025)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1433]
**[Original submission](https://gna.org/bugs/index.php?23025)** by ancestral on 2014-12-04

I cannot change the size of the in-game character dialog (the text at the bottom of the screen) through a mod or a core, likely because theme files in data/gui cannot be overridden or replaced.

Also, I am not able to reference or replace a custom font (probably due to: hardwired/fonts.cfg).

See the forum thread starting [here](://r.wesnoth.org/p578682) for more details.

(Reproduced on Any)
Release: 1.12+
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-29**

**ancestral wrote:**

> Possible duplicate of #21948 (Allow addons to add fonts).

**Comment by Wedge009** [comment]
Duplicate link is #1386

**Comment by CelticMinstrel** [comment]
Core GUI themes _are_ supported now, but currently you would need to edit _data/gui/\_main.cfg_ to load the theme if I recall correctly. So it could still use a little more work.

**Comment by Wedge009** [comment]
Original report was by @ancestral.

**Comment by CelticMinstrel** [comment]
I'm closing this since GUI2 theme support was completed in 1.13.7. New issues can be opened specifically for font support or for improvements to the GUI2 theme interface.
