### ISSUE TITLE
force_lock_settings=yes in campaigns (GNA #23037)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1435]
**[Original submission](https://gna.org/bugs/index.php?23037)** by anonymous on 2014-12-07

actually this of more a "feature removal" request.

Currently in mp campaigns you can by default change several settings: 

1) Use Fog
2) Use Shroud
3) Random Start Time
4) Turn Limit
5) XP Modifer
6) Village Support
7) Village Income

I think all those settings are designed for normal 'blanced' mp maps, and i really cannot imagine any situation where the scenario designer of a campaign wants them to be modifyable. Even worse, in mp campaigns some of those those can be side specific (1,2,6,7), and allowing to overwrite them would mess the content of the wml up.

Also it often likeley that "Turn Limit" is assumed to not beeing changed, for example if there are "turn X" events or messages like "we have to hurry only one day left". Same is also true for "Random Start Time".

So the only thing that could make sense to be changed in a mp campaign is "XP Modifer".

I propose to eigher never allow to change them in mp campaigns, or at least to make force_lock_settings=yes the default for [scenario] but not for [multiplayer].

(Reproduced on all)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-12-24**

**ai0867 wrote:**

> Partly done by gfgtdf in [213c8293ba7](s://github.com/gfgtdf/wesnoth-old/commit/213c8293ba78f9d156756616b413bb2c9cf4ceed).

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-26**

**gfgtdf wrote:**

> a possible plan to fix the issue of overwriting side specific values might be to allow multiplayer scenarios to specify 1,2,6 and 7 directly in [multiplayer] which is then used as the default for sides if sides dont spcify them.
> 
> Then the mp configure dialog could simply change that value instead of changing the sides values.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-28**

**sigurdfdragon wrote:**

> I'm not sure what the best way to deal with this would be.

**Comment by Wedge009** [comment]
Checking MP Campaign menu in 1.14.7, I note that 'map settings' is locked and these settings include all 7 of those mentioned above. These settings are not locked for normal MP scenarios or random map generation. As best as I can tell this has been resolved but please re-open if I'm wrong.
