### ISSUE TITLE
variable substitution in abilities (GNA #23063)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1436]
**[Original submission](https://gna.org/bugs/index.php?23063)** by anonymous on 2014-12-12

It woudl be coold if we there was variable substitution when abilities or weapon specials are applied. Then it would be for example possible to add weapon specials like this:

```

[damage]

add = "$($other_unit.level - $unit.level)"

[/damage]

```

(Reproduced on all)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by gfgtdf** [comment]
closing this since you can now use formulas there. I decded against implementing support for variable subsutution since this is known to makew things more complicated, specially when the abilitites are applied via [object]

**Comment by CelticMinstrel** [comment]
The equivalent of the given example with the implemented syntax would be:

```
[damage]
    add = "(other.level - level)"
[/damage]
```

The enclosing parentheses signal that this is a WFL formula.
