### ISSUE TITLE
[music] unable to replace playlist without interrupting current track (GNA #23065)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1437]
**[Original submission](https://gna.org/bugs/index.php?23065)** by zookeeper on 2014-12-12

It should be possible to change the playlist without interrupting the current track by using immediate,append=no,no. Currently, doing so does cause an immediate switch to the new playlist.

Here, the playlist switch upon the first move should allow elf-land to finish playing first, but currently doesn't (instead, the switch happens as if immediate=yes was used):

```

    [event]

        name=start



        [music]

            name=elf-land.ogg

            immediate=yes

            append=no

        [/music]

    [/event]

    [event]

        name=moveto



        [music]

            name=defeat.ogg

            immediate=no

            append=no

        [/music]

    [/event]

```

(Reproduced on All)
Release: 1.12.0
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-12-12**

**fendrin changed OS:** win7 -> All

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-12-12**

**fendrin changed status:** None -> Ready For Test

**fendrin wrote:**

> Fix attempt in commit http://git.io/wzJ2rg
> 
> (Master only so far)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-03**

**zookeeper wrote:**

> It seems that this broke one thing: the simple scenario-level [music] tags (that is, ones with only a name= supplied) used for example by macros such as INTRO_AND_SCENARIO_MUSIC. Previously, the track would immediately start playing in the story screen, but now it first waits for the current track to finish (which, if starting a campaign, will be main_menu.ogg).
> 
> 
> 
> This should be reproducible in the first story screen of most campaigns; for example AOI, LoW, EI.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-25**

**shadowmaster changed status:** Ready For Test -> In Progress

**shadowmaster wrote:**

> The original fix for 1.12 was reverted prior to releasing 1.12.1, by zookeeper's request (see comment #2).

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-02-01**

**zookeeper wrote:**

> To clarify, the fix is fine in master.
> 
> 
> 
> In 1.12, the previously mentioned change to behavior of scenario-level [music] tags causes a slight compatibility break so it should be addressed somehow; if it's possible to re-port to 1.12 with an added check for whether the [music] tag is scenario-level or not, that'd do.
> 
> 
> 
> In other words, in 1.12, a plain scenario-level [music] tag should default to immediate=yes.

**Comment by CelticMinstrel** [comment]
Well, master goes to great lengths to ensure the current track always finishes, so I'm closing this.
