### ISSUE TITLE
Addon manager incorrectly applies addon states to certain labels (GNA #23080)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1438]
**[Original submission](https://gna.org/bugs/index.php?23080)** by vultraz on 2014-12-15

The addon manage appears to incorrectly apply variable labels to certain messages.

For example, the install successful popup should say '[addon] was successfully updated' if the relevant addon was in an Upgradable state, however it only does if you had a filter for Upgradable addons present in the manage before you began downloading.

I suspect this applies to certain other label states as well, but I haven't confirmed.

An additional suggestion would be updating the value of the OK button to say Update if the addon is a candidate for such.

(Reproduced on Windows 8)
Release: 1.12.0
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-26**

**vultraz wrote:**

> Assigning this to me since the old GUI1 manager has been removed. Still need to decide how much of this is an issue.

**Comment by Wedge009** [comment]
I haven't noticed anything like the issues mentioned above since the new interface was implemented and given its age I think it can be closed. Please re-open if this assessment is incorrect.
