### ISSUE TITLE
Addon manager does not properly show file upload progress (GNA #23083)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1439]
**[Original submission](https://gna.org/bugs/index.php?23083)** by vultraz on 2014-12-15

When uploading an addon, the upload progress bar will display at full immediately, along with the total size, but with no indication any uploading is going on.

(Reproduced on Windows 8.1)
Release: 1.12.0
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-21**

**loonycyborg wrote:**

> I looked into this issue. It's caused by the way networking code is tracking progress. It relies on completion handlers from asio's async_write/async_read, but in case of windows asio calls completion handler only once per write operation. Read operation on windows work in the same way as on linux so completion handlers still work to track download progress. I didn't see any  guarantees on when completion handler is called in asio's documentation so the safe way to fix it is to manually split write and read operations into small chunks, but it'll make code more complex and duplicate something asio should be doing itself IMO.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-21**

**loonycyborg wrote:**

> Also, I expected that completion handler is called each time underlying low level operation completes, so it could be a bug in asio or quirk of windows network stack.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-21**

**shadowmaster changed item group:** User Interface -> Networking

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-06-16**

**vultraz wrote:**

> Is this fixed with the move to boost Asio?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-06-16**

**loonycyborg wrote:**

> No. It's Asio bug, duh.

**Comment by Vultraz** [comment]
I just tested this again, and it seems the issue is now the opposite. The progress bar never fills, and the current progress remains at 0.
