### ISSUE TITLE
[unstore_unit] with check_passability=yes does not place the unit if there is no suitable place (GNA #23103)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1440]
**[Original submission](https://gna.org/bugs/index.php?23103)** by anonymous on 2014-12-23

If [unstore_unit] with check_passability=yes is used on a unit that has has all terrain types set as unreachable, it doesn't do anything, the unit isn't placed and can possibly break the scenario by not being on the map if it's supposed to be there.

If this happens, this is written into the log:

error engine: Trying to add  - (insert unit id here) at an invalid location; Discarding.

(Reproduced on All)
Release: 1.12
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-12-23**

**involution wrote:**

> That sounds like the expected behavior, check passability is supposed to guarantee that a unit won't be placed somewhere it's not normally supposed to be allowed to stand. If that breaks your scenario, try using check passability = no?
> 
> 
> 
> What exactly do you think is supposed to happen in this case?

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-12-24**

**zookeeper wrote:**

> It indeed seems like a corner case that the WML author should take into consideration.
> 
> 
> 
> However, it *could* be smarter and simply ignore check_passability if there aren't (or can't be) *any* passable locations on the whole map and just place the unit where it was told to (still respecting find_vacant, of course) and write a note about it to the log.

**Comment by wesnoth-bugs** [comment]
**Modified on 2014-12-27**

**involution wrote:**

> IMO that behavior would be surprising, if you think it's desirably I think it should be on an optional flag or something.
> 
> 
> 
> To me the most practical solution would be, if you need to do some kind of complicated error handling in your scenario "try to do X, but if it doesn't work / gives an error, then try to do it differently, if it still doesn't work..." just use lua. lua was  designed to make that kind of thing very easy, and the author will be able to tweak it to get it just right.

**Comment by CelticMinstrel** [comment]
This is clearly invalid — it's obvious that `check_passability=yes` would never find a valid hex for a unit that views all terrain type as impassable.
