### ISSUE TITLE
Crash when Music Change and/or Playing Sound of Attack (GNA #23203)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1446]
**[Original submission](https://gna.org/bugs/index.php?23203)** by carian on 2015-01-20

Hello,

Crash Occurs in the Two Brothers Campaign.

Scenario 1 : If Music enabled : At the end of Starting Dialog, just before displaying Objectives, Sounds plays in infinite loop, depending of the buffer size.

To workaround it, I have disabled Sound and music.

After displaying Ojectives, I have re-enabled Sound and music.

Music are Ok. At the first attack of my Cavalry, Same bug : Sound of attack playing in infinite loop, and game Crash.

Game crash Occurs in libvorbis-0.dll

It seems to be a memory leak also, because Virtual Memory has been increased drasticaly.

Can reproduce the bug a each time.

I have tested the main campaign. Same Bug

File Joined :

- SaveGame.

I'm available for all test you want, if you can not reproduce the bug.

(Reproduced on Win XP SP3)
Release: 1.12.00
Priority: 5 - Normal
Severity: 5 - Blocker

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-20**

**carian added attachment:** [HdDF-La_Destruction_d'un_mage-Sauvegarde_automatique3.gz](http://gna.org/bugs/download.php?file_id=23561)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-20**

**carian wrote:**

> More information :
> 
> - This is the Windows genuine build of BoW. No modification, no customization.
> 
> 
> 
> - Abstract from CrashDump :
> 
> AppName: wesnoth.exe	 AppVer: 0.0.0.0	 ModName: libvorbis-0.dll
> 
> ModVer: 0.0.0.0	 Offset: 0001a009
> 
> 
> 
> - SoundDriver :
> 
> SoundMAX Integrated Digital Audio
> 
> Version : 5.12.1.3524

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-21**

**anonymous wrote:**

> there have been similar reports already:
> 
> https://gna.org/bugs/?23026
> 
> and
> 
> http://boards.openpandora.org/topic/15312-crashes-when-using-sdlmixer-and-vorbisfile/

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-21**

**carian wrote:**

> I have done a build of 1.13.0-dev on my Win Xp Sp3 System with CodeBlocks, using the today's Git Zip and the last CodeBlocksWinSDK supplied.
> 
> 
> 
> Sound problem does not occurs. It seems fixed.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-21**

**anonymous wrote:**

> Did you use the same dlls for your custom build as for the downloaded build?

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-22**

**carian wrote:**

> No, no version number was provided on libvorbis-0.dll, only release date.
> 
> 
> 
> My custom build use CodeBlocksWinSDK_28_11_2014 dlls, with a 20/07/2007 21:43:06 build date for libvorbis-0.dll
> 
> 
> 
> The official build wich have the problem is the 1.12.0 build wich use a 11/05/2014 15:55 dated version of libvorbis-0.dll.
> 
> (Note : datetime provided are french formatted :) )
> 
> 
> 
> If i can get the same CodeBlocksWinSDK used for the official build, i can do a build of 1.13.0-dev version to ensure if the bug is fixed in 1.13.0-dev or not.
> 
> 
> 
> I have the time to do many test, so, you're welcome !

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-22**

**anonymous wrote:**

> maybe you could do a 1.12 build the same way you did the 1.13 build and check whether the bug appears to you there?

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-01-22**

**carian wrote:**

> Already done :)
> 
> 
> 
> Building 1.12.0+dev with the Today's Git Zip with the CodeBlocksWinSDK_28_11_2014 ddl settings, using CodeBlocks 12.13
> 
> 
> 
> It'ok. Bug does not occurs. It seems only pb of libvorbis dll version used.
> 
> 
> 
> Case seems solved.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-07-14**

**vultraz changed status:** None -> Fixed

**vultraz closed the issue**

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-07-14**

**shadowmaster reopened the issue**

**shadowmaster changed status:** Fixed -> None

**shadowmaster wrote:**

> @vultraz: This has not been fixed, so please don't mark it as such.
> 
> 
> 
> https://forums.wesnoth.org/viewtopic.php?f#4&t43631

**Comment by Wedge009** [comment]
Similar report: #1434

**Comment by gfgtdf** [comment]
the last link by @shikadilord doesn't work anymore it gives me 'The requested topic does not exist'

**Comment by shikadilord** [comment]
https://forums.wesnoth.org/viewtopic.php?f=4&t=43631

**Comment by sevu** [comment]
I wonder if this and #1434 can be closed / no being a blocker anymore:
- windows xp is not oficially supported anymore in 1.13
- though @shikadilord mentioned an variation of the issue with debian8 and returning to (the old?) MP lobby in the other report.

**Comment by Wedge009** [comment]
I never observed either, so I couldn't investigate them. It might well be not-a-blocker as Vista onwards only really did audio processing in software (not quite sure what the state is with 10). carian doesn't appear to be on GitHub either.

**Comment by Vultraz** [comment]
Since there's been no evidence this issue or #1434 affected any Windows version other than XP, I'm closing this and #1434. We indeed don't officially support XP anymore in 1.13.
