### ISSUE TITLE
{TRAIT_... mistakes in addon affect a gameplay outside this addon (GNA #23291)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1450]
**[Original submission](https://gna.org/bugs/index.php?23291)** by anonymous on 2015-02-17

My era - Default Complete Era - is based on default era, and has inherited a lot of wesnoth core files with small changes - including units.cfg

Inside this file, under "# subfolders for units" block listing various folders, there was a code:

        #traits that are common to all races and units

        {TRAIT_STRONG}

        {TRAIT_QUICK}

        {TRAIT_INTELLIGENT}

        {TRAIT_RESILIENT}

Because these lines were not only in data/core/units.cfg , but also in units.cfg of my addon, I had two serious problems:

1) Double unit traits, while playing in eras from my add-on ("quick,quick", "strong,strong", etc)

2) Even when I played in default era with other people, there were a lot of OOS (out-of-sync) errors between me and other players.

These errors were caused by different traits of units in their "picture of game" and mine; probably because those traits from my addon got added to a common traits pool,

despite I haven't been using my add-on at this time!

After I removed these "{TRAIT_...}" lines from units.cfg of my addon, these two problems have disappeared

"1)" - is not a Wesnoth bug, its my problem

However, "2)" - mistakes in addon should not affect a gameplay outside this addon - so there is a bug here

(Reproduced on OS X 10.10.1)
Release: 1.12.1
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-02-17**

**generous wrote:**

> I believe its a bug because it ruined a gameplay outside addon. Files of addon should not affect Wesnoth gameplay without addon

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-02-17**

**anonymous wrote:**

> there is currently nothing to prevent add ons from changing gameplay if they are not activated.
> 
> 
> 
> Campaigns (and in 1.13 also mp eras and mp scenarios) are able to hide their content in a #ifdef that is then only loaded when the addon is active.
> 
> But this is more about reducing loading time than about disabling content. I you put your content in a #ifdef loading goes faster if the content in it is not used but it might require another reload of the game config as soon as that content is used (for example if you start a campaign). Thats why for very small content (like most mainline multiplayer mp maps in 1.13) this feature it not used.

**Comment by Pentarctagon** [comment]
@gfgtdf is this still a valid issue?

**Comment by gfgtdf** [comment]
I think this should be fixed but i didn't test it.

**Comment by soliton-** [comment]
Not loading all addons anymore was pretty much exactly done to fix this kind of issue.
