### ISSUE TITLE
overwrite unit advancements in campaigns (GNA #23298)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1451]
**[Original submission](https://gna.org/bugs/index.php?23298)** by anonymous on 2015-02-20

currrently it is possible to disale/enable certain unit advancements with extra_defines#DISABLE_GRAND_MARSHAL or extra_definesENABLE_ANCIENT_LICH.

This approach has multiple disadvantages:

1) it makes the core wml content dependent on macos and thus requires reloading the whole wml core content when starting a campaign or mp (this is the one that really annoys me).

2) It only allows to change the advancements of some unit types.

It would be better to have a tag [overwrite_unit_advancements] in [campaign] that could be used like this:

```

[campaign]

...

  [overwrite_unit_advancements]

    Lich=Ancient_Lich

    General=Grand_Marshal

  [/overwrite_unit_advancements]

[/campaign]

```

(Reproduced on )
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-02-22**

**anonymous wrote:**

> also currently if you want to copy & change one unit by using  [base_unit] (why is [base_unit] a tag and not just a base_unit= attribute ?) you usually have to do that for the whole unit advancement tree becasue the other units still advance to the old type, with this new feature you wouldn't need to do that.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-02-25**

**involution wrote:**

> re (1):
> 
> 
> 
> That reloading is pretty much unavoidable. All core wml content is in general dependent on macros, and even if it isn't each campaign has its own campaign define symbol, and mp lives in its own macro space as well. I think it would be very difficult and undesirable to change this.
> 
> 
> 
> 
> 
> 
> 
> re [overwrite_unit_advancements]: 
> 
> 
> 
> I wonder if you couldn't just write some lua script that scans all the unit types and makes substitutes for your campaign with the appropriate unit advancements? It might be useful as a utility.
> 
> 
> 
> If you like I think you could then go on to make a wml tag defined using the lua utility.
> 
> 
> 
> I think that would be what we the devs would do also most likely, rather than implement it in C++.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-12-25**

**gfgtdf wrote:**

> > re (1):
> 
> > That reloading is pretty much unavoidable. All core wml content is in general dependent on macros, and even if it isn't each campaign has its own campaign define symbol, and mp lives in its own macro space as well. I think it would be very difficult and undesirable to change this.
> 
> 
> 
> The wesnothdir/data/core wml currently basically only depends on those unit advancement macros, {EDITOR}, and some macros whose values can only be set at programmstart, if it werent for them it would sureley be easier to cache those part of the wml tree better and load them faster.
> 
> 
> 
> what was not mentioned in the first post is that the current [advancefrom] + ifdef has other disadvatages:
> 
> 3) [advancefrom] is unusable in mp since it will also add those units with the era that adds this units isnt currently played.
> 
> 4) It cannot remove advancements from units.
> 
> 
> 
> Currently there are only 2 ways a wml developer can to fix this
> 
> 1) copy the whole unit type tree with basetypes, overwrite the advancements and dont use the original unit types in your scenarios/era.
> 
> 2) changing the advance_to dynamically with lua/wml
> 
> 
> 
> Both approaches have disadvantages, a problem that they both share is that the help system can no longer show correct and clean information, in the first case each unit will appear twice in the help while with (2) the help wont show the new advncement options at all.
> 
> 
> 
> Thus i think we need a way to change units or at least units advancements on [campaign] level, and not durng wml loading.
> 
> 
> 
> I am not convinced about the proposed syntax though. Mostly becasue currently unit type ids can use characters that are not usable as attribute names in wml tables.
> 
> 
> 
> > re [overwrite_unit_advancements]:
> 
> >
> 
> > I wonder if you couldn't just write some lua script that scans all the unit types and makes substitutes for your campaign with the appropriate unit advancements? It might be useful as a utility.
> 
> > If you like I think you could then go on to make a wml tag defined using the lua utility.
> 
> >
> 
> > I think that would be what we the devs would do also most likely, rather than implement it in C++.
> 
> 
> 
> Sry but i am unusre about what you mean here, sure it is possible to write a lua (or and other language) script helps you creating .cfg files for copied unit types. But i dont see how a wml tag could use such a code.

**Comment by gfgtdf** [comment]
I still think this is a good idea but i'm unsure on how eactly to implement it, since there are multiple options:

1. We could simply let users overwrite arbitary unit attributes this would fix (1) (2) and (4) but not (3). But it would give people even more options.

2. we could have a [overwrite_unit_advancements] tag as proposed in the first post, whose effect is staticially. This would fix all (1) (2) (3) and (4)

3. we could have a [overwrite_unit_advancements] action tag similar to what was proposed in the first post, this woudl allow the author of an addon to make an advancement optional (for example via an [options] checbox)

I currently favour option 3 since it's just more flexible then option 2 It probably also harder to implement.

**Comment by CelticMinstrel** [comment]
Option 3 is a pretty fundamental change. Currently, unit types are _immutable_ at runtime (ie in ActionWML). You're proposing to change that. This could have all sorts of unforeseen consequences. As such, I'd be pretty hesitant to go with this possibility.

I think the immutability of unit types would also interfere with an implementation of `[overwrite_unit_advancements]`, making it harder to implement than it might seem at first glance, though at least this probably wouldn't have as many unforeseen consequences if the overwriting only occurs once. In fact, it would probably be possible to wire it into the unit type building process, just like `[advancefrom]` is.

There is also literally no reason why `[advancefrom]` plus defines should not work over multiplayer. When starting a campaign, all clients should know which extra defines are required and load the WML data with those defines, meaning that they should all get the appropriate `[advancefrom]`s. That this is not currently the case is a flaw somewhere in the multiplayer negotiation.

**Comment by gfgtdf** [comment]
> And by the way, with regards to issue point 3....

This is not about campaigns, and even for in 1.13 it's only possible to for eras / mods to have one define each.

**Comment by CelticMinstrel** [comment]
> This is not about campaigns

The opening post begs to differ, but... well, what I said should be true of individual scenarios, too.

> even for in 1.13 it's only possible to for eras / mods to have one define each.

Why? This seems like a potential bug.
