### ISSUE TITLE
victory event not fired for observers (GNA #23329)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1454]
**[Original submission](https://gna.org/bugs/index.php?23329)** by anonymous on 2015-02-27

On the observers client victory and defeat events are not fired.

This makes sense for multiplayer matches where one side wins and another side loses but not for cooperative campaigns like LoW.

(Reproduced on any)
Release: 1.12
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-01**

**gfgtdf wrote:**

> fixed in master in https://github.com/wesnoth/wesnoth/commit/7111e9bbfdf8faa469b980ac54d17297f1c97855

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-05-30**

**gfgtdf wrote:**

> actually I am not sure whether the new code fires the defeat or the victory event for observer, and i think i should maybe revert it.
> 
> 
> 
> Note that in 1.13 we have an endlevel event that is fired regardless of victory/defeat and also for observers.

**Comment by CelticMinstrel** [comment]
@gfgtdf — this is no longer the case in 1.13.x, right?

**Comment by gfgtdf** [comment]
ye it was
