### ISSUE TITLE
Use git or similar in the addon server (GNA #23360)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1458]
**[Original submission](https://gna.org/bugs/index.php?23360)** by anonymous on 2015-03-06

Players that know wml sometimes want to know what has changed when they download a new version of their add ons. And the changelog that the umc authour wrote often misses entries.

Also some umc devs use git internally to organize the developenent of their add ons.

My idea was to make the add on server a git server which allows to use git to push to the addon server and will create commits for every upload from people that do not use git.

This would also make it easier to see the diffrences of add on versions from people that do not use git.

(Reproduced on every OS)
Release: 1.14
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-09**

**involution wrote:**

> I think it would be pretty complicated for us to figure out how to make the add-on server talk directly to git.
> 
> 
> 
> I once suggested something along these lines, what I suggested was that if you like, you can put your add-on on github and put a link in the pbl file, and tell the server to update from github.
> 
> 
> 
> But now I think this is not so different from what we currently have. Many add-ons are already on github. You can just use the existing system to upload from your local clone, and in wesnoth 1.13 the add-on server will support clickable hyperlinks in the description, so you can just put a link to your github page from there.

**Comment by Pentarctagon** [comment]
This doesn't seem to provide a significant benefit, especially given we now able to download previous add-on versions and incremental updates.

**Comment by cooljeanius** [comment]
> This doesn't seem to provide a significant benefit, especially given we now able to download previous add-on versions and incremental updates.

Potential benefits:
- Fork add-ons directly from within the add-on manager
- Collaborate in-game (e.g. submit pull requests)
- Reduce duplication between git commits and add-on server uploads
- Switch not just between versions, but also between branches

**Comment by Pentarctagon** [comment]
It still begs the question of why Wesnoth would need to try and have a UI frontend for git.  The large majority of add-ons won't benefit from it, and the ones that actively want these features implemented through git likely already know how to use git.
