### ISSUE TITLE
mp testing core (GNA #23368)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1459]
**[Original submission](https://gna.org/bugs/index.php?23368)** by anonymous on 2015-03-08

It would be nice to have a "testing core" that is a core (see http://gna.org/bugs/index.php?8832) that is optimized for testing and fast loading. It could for example only contain like 3 units, 5 terrains and 2 mp scenarios.

(Reproduced on any)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Pentarctagon** [comment]
Closing since running tests on a different Core would generally invalidate the test being run.
