### ISSUE TITLE
[delayed_massage] tag (GNA #23378)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1460]
**[Original submission](https://gna.org/bugs/index.php?23378)** by anonymous on 2015-03-11

Sometimes you want to show a message to a specific side, but in hotseat games it is possible that that side is not the currently viewing side. So i propose to add a [delayed_message] tags that works similar to normal [message] but has a side= attribute and shows as soon as that side is the currently viewing side.

(Reproduced on all)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-12**

**tekelili wrote:**

> I think you can already do that with:
> 
> 
> 
> [event]
> 
>     name= side turn X
> 
>     [message]
> 
>     [/message]
> 
> [/event]

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-12**

**anonymous wrote:**

> No it is not that easy, if i do it like that then: 
> 
> 1) The message will also show for other sides than side X.
> 
> 2) If it is already side X turn the message will show in the next turn and not in this one.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-08**

**vultraz wrote:**

> [message] side_for already exists.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-10**

**anonymous wrote:**

> @Charles Dang <vultraz>:
> 
> Yes but that is something very different from what i described in the first post.

**Comment by CelticMinstrel** [comment]
So can this already be done, or not?

**Comment by AI0867** [comment]
It would appear the proposed syntax

    [delayed_message]
        side=X
    [/delayed_message]

is equivalent to:

    [event]
        name=side X turn
        [message]
            side_for=X
        [/message]
    [/event]

**Comment by gfgtdf** [comment]
this is not 100% the same, 
1) if it is already the turn of side x it your code would show the message in the next turn.
2) since the proposed syntax said 'as soon as that side is the currently viewing side' which means 'immidiateley' for normal mp games but at 'side x turn' for hotseat games, i guess it's good enough though.

**Comment by CelticMinstrel** [comment]
Well, for #1 you could easily add a conditional based on the current turn/side to show the message immediately if that turn is already reached, right?
