### ISSUE TITLE
Change ford terrain code to Wf (GNA #23386)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1461]
**[Original submission](https://gna.org/bugs/index.php?23386)** by tekelili on 2015-03-13

While working heavyly with terrain filters, I have noticed terrain codes are designed nicely to make filters easy to build. However, there is one code often disrupts this propose: Wwf

In resume, I often have to use filters like

[terrain]

[and]

terrain=Ww,Wwt,Wwg,Wwr*

[/and]

[/terrain]

Because I often want to filter shallow water and reefs without consider fords. A code like Wf would allow easier filtering in any case.

Not as important, but for similar causes, would be also helpfull change reefs code to Wr,Wrt,Wrg

This would break backward compatibility, but I think it would be easy to manage keeping old code as deprecated for one version.

(Reproduced on any)
Release: 1.13
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-13**

**tekelili wrote:**

> As side note, my proposal would complicate current filter
> 
> terrain=Ww*
> 
> 
> 
> ...it would become
> 
> terrain=Ww*,Wf,Wr*
> 
> 
> 
> But in my experience, I almost never wanted use such filter.

**Comment by nemaara** [comment]
This one will cause a lot more problems than it'd fix. Every map would need to be fixed to use the new terrain codes, and existing filters would need to be checked to produce the correct behavior. It also doesn't make sense, because fords are still considered water, which is relevant to units like mermen and nagas.

**Comment by CelticMinstrel** [comment]
Also, if you specifically want to avoid fords, you can always use something like `W*,!,Wwf` as your filter.
