### ISSUE TITLE
Drakes have 40% defense over unwalkable (GNA #23409)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1462]
**[Original submission](https://gna.org/bugs/index.php?23409)** by cannonfodder on 2015-03-24

Maybe it is intentional, however for me it feels like a bug.

So Drake units have 40% defense over unwalkable terrain (which they can fly over). This feels odd since the same units (Drake Burner line and Drake Fighter line of units) have only 20% defense over water. Maybe applies to other units, too, I just observed this with Drakes (particularly in the "A Song of Fire" user made campaign, "The Sky Dragon Descends" scenario, where the city which the player should defend is surrounded with a chasm, where it felt very odd that the attacking Drakes don't lose defense: not even the huge Fire Dragon monster).

This can be reproduced easiest by starting an Auction X local multiplayer game (which has chasms) with a Drake player. I verified this exist in 1.12.0 and 1.10.7, on Debian Linux.

(Reproduced on Linux)
Release: 1.12.0
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-24**

**anonymous wrote:**

> to me it makes sense that flying unit have more defense in chasm than over water because they can move down if they are attacked.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-30**

**cannonfodder wrote:**

> Normally yes, however for me these drake units feel like needing solid ground to defend themselves: unlike other flyers, they are portrayed as preferring sitting and acting on the ground, and contrary to those, their usual defenses reflect this (while usual flyers such as gryphons, bats or the drake glider tree have uniform defense over most terrains, including over water). Unwalkable is (typically) a chasm, so if they need to land, they are even below their opponent. The "move down" might feel OK when they are defending, however when they are the attacker, it makes much less sense (also note that 40% is the highest defense rating these units can get).
> 
> 
> 
> Maybe someone should clear this up, whether it was an intentional feature: part of the design of the drakes. It is just odd.

**Comment by nemaara** [comment]
It looks intentional to me, the line of code in the movetype specifically states unwalkable=60, different from the defenses for water, reef, or swamp. You can justify it by thinking about Drake defenses being about maneuverability. The "move down" to dodge an attack is not possible above water because the drake will then make contact with the water, which they most likely very much dislike. In chasm, they can maneuver however they like, and so can dodge attacks more easily. Some chasms are also lava hexes, so it makes sense that drakes would do fairly well in their natural habitat (mountains, volcanoes, hills, lava and such). So, I think the 40% defense over chasm is reasonable.

If there are no other complaints, I'll close this issue.

**Comment by CelticMinstrel** [comment]
Note that non-chasm lava is also unwalkable, so the "can move down" justification doesn't always work.

**Comment by nemaara** [comment]
I'm okay with leaving one case where that justification doesn't strictly work. Changing this to 20% ruins a lot of balancing in drake campaigns where chasms are important (see Ashen Hearts, for example), and I think it makes sense that drakes have decent defenses over lava.

**Comment by Ja-MiT** [comment]
Maybe the heat from the lava makes it easier to dodge by  moving up?

**Comment by CelticMinstrel** [comment]
...okay, you have a point there.

**Comment by nemaara** [comment]
Drakes probably also do better in hot places as reptilian creatures, whereas large bodies of water tends to cool the air and works to their detriment. Either way, drakes have bad enough defenses on almost every type of terrain (especially given their cost), so I don't think this change is desirable from a gameplay perspective either.

**Comment by CelticMinstrel** [comment]
Yeah, my arguments were against the justification only, so I think this can indeed be closed.
