### ISSUE TITLE
Do no ask user to enable forced modification (GNA #23410)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1463]
**[Original submission](https://gna.org/bugs/index.php?23410)** by tekelili on 2015-03-24

[modification] is a great tool to load pack of events or variables used in diferent scenarios, it reduces user memory consumed.

As example, I want to use [modification] to load lot of repeated stuff written in 1p, 2p, 3p scenarios of my add on. However this would be incovenient for user, as would add an extra click requirement when selecting one of my scenarios.

I think...

[scenario]

force_modification=

...should enable such modification automaticaly without user input.

There is already a feature request for hidden [modification] that I support and would be better than this request. I am suggesting it as a possible quick-easy fix for nest 1.12.X version.

(Reproduced on any)
Release: 1.12
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-25**

**lipk wrote:**

> I'm not strictly opposed to the idea, but I'd like to point out that the current behavior is a result of a conscious design decision to give the user a clear view on the effects of their choices.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-26**

**tekelili wrote:**

> I dont think user should be punished with a useless extra click just to make debug easir.
> 
> 
> 
> If I use force_modification, I am saying that is a core part of scenario and wont work without it. I dont see how user can profit from be asked about load core code, or not play scenario at all...

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-26**

**tekelili wrote:**

> Just to say it with other works, if you wont ask user: "do you agree in load code inside [scenario][/scenario] in order to play?"
> 
> 
> 
> then why you ask about...
> 
> [scenario]
> 
> force_modificatio=
> 
> [/scenario]
> 
> 
> 
> From my point of view, force_modification code is equivalent to whatever other code is written

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-27**

**involution wrote:**

> tekelili: I see what you are saying and where you are coming from. I think it's reasonable to have a prompt, and a no prompt mode.
> 
> 
> 
> It's not just about debug for scenario maker.
> 
> 
> 
> If I'm a user and I'm trying to make a game, if I specifically pick some era, then I pick some scenario or modification and the game immediately changes it back for no reason that I could see, I could get extremely frustrated very quickly. Especially if there is a bug that add-on maker made with the dependencies, or if I just misunderstand the dependencies... it's definitely not universally a good thing to just undo what the user does without explanation.
> 
> 
> 
> If you release a bug in your add-on that messes up the dependencies in some way, you want the users to be able to turn on some mode so that they can explain what has happened, and not just get reports "it was a game of whackamole, I did not solve it."
> 
> 
> 
> It's like "use map settings". Usually you as the scenario maker will want the user to play exactly as you intended. But we don't force them to do that, we let them configure it differently if they want. There is also plans to allow the user to force a "broken" configuration of add-on eras and modifications, one that ignores your force_modification code, if they want, for the same reasons.
> 
> 
> 
> It's not the same as "please don't load core code", or "please crash to desktop", that's a misleading comparison. We want to make it easiest for the user to play the scenario as you intended, but we also want to allow them to try to set it up differently if they want.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-03-28**

**tekelili wrote:**

> @Chris: Use force_mofication will not remove era chosen by user unless [modification] uses disallow_era, in wich case user would be warned as I am not asking to remove that "question".

**Comment by gfgtdf** [comment]
1.14 has [resource] which can be used for such things. In particular as i am currently the maintiner of world conquest II (the addon for which he needed this in the first post) i know that it fixed his usecase.
