### ISSUE TITLE
�Instruct ally� context menu indirectly reveals number of enemy teams which have not been discovered yet (GNA #23432)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1464]
**[Original submission](https://gna.org/bugs/index.php?23432)** by wuzzy on 2015-03-30

Singleplayer mode:

If there are enemy teams hidden in the black fog and the player has not discovered any of them, using the �Instruct ally� context menu allows one to at least reveal the number of enemy teams.

Here is one way how to reproduce this:

Start the mission �The Grey Woods� in the campaign �Freedom�. In the first turn, rightclick one of your allies, then select �Instruct ally� in the context menu.

Now tell them that they shoud attack some team.

Here it gets interesting: Instead of a list of leaders/teams, the list shows three teams, but without names. It just shows �Team 3�, �Team 4� and �Team 5� without their leader's name and picture. There is also an equals sign for some reason.

Also, this mission has the �black fog� and all three enemy leaders are hidden at the beginning.

I think it should not be possible to select these enemy teams at all as long they have not been spotted yet. Certainly this list of teams looks wrong to me.

(Reproduced on GNU/Linux)
Release: 1.12.1
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by CelticMinstrel** [comment]
This has been deprecated for removal, so there's no longer a need to fix bugs in it.

If at some point a new instructable AI is added and the same bug resurfaces, a new issue can be opened for it at that time.
