### ISSUE TITLE
Remove deprecated command line options (GNA #23463)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1466]
**[Original submission](https://gna.org/bugs/index.php?23463)** by vultraz on 2015-04-09

--config-dir# and --config--path are deprecated and should be removed.  --userconfig-path# and --userdata-path are supposed to replace them, respectively.

(Reproduced on All)
Release: 1.13.0-dev
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-10**

**gfgtdf wrote:**

> all our official windows releases use --config-dir. If this request results in those needing to pass 2 commandline arguments to wesnoth which need to be changed to reset the userdata directory then im against it.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-10**

**shadowmaster wrote:**

> I actually intended to rename --config-dir to something less ambiguous for that reason, and the fact that it's very convenient for things like the utils/wesnoth-defaults script.

**Comment by Wedge009** [comment]
@gfgtdf How does Windows use this command-line option? Or does it still use it? (Your comment was from 2015.)

**Comment by Wedge009** [comment]
As best as I can tell, these lines would spit out some sort of error message instead of copying them to the new user- options.

https://github.com/wesnoth/wesnoth/blob/2d16a3b4101b66e068c98411345e02401cab4e29/src/commandline_options.cpp#L345-L348

Also noting this is @Vultraz's report.

**Comment by gfgtdf** [comment]
> @gfgtdf How does the Windows build use this command-line option? Or does it still use it? (Your comment was from 2015.)

Iirc the installer has (or at least had in 2015) an option to store the userdata in the installer directory which was implemented using config-dir

**Comment by Wedge009** [comment]
@loonycyborg Is it an issue for Windows installer to remove these options?

**Comment by gfgtdf** [comment]
> @loonycyborg Is it an issue for Windows installer to remove these options?

Whether the options are there or not, you wanting to remove the `--config-dir` option is clearly not enough of a reason to remove them. Why do you want to remove it in the first place?

**Comment by Wedge009** [comment]
Not *me*. See the original requester.

Screw it, I don't know why I bother.

**Comment by Vultraz** [comment]
We don't need a committee hearing just to remove a command line option! I seem to recall there were some complications that prevented shadowm from ever removing these, and maybe those still need to be addressed, but going into a "well why do you want to remove this" debate is ridiculous!

**Comment by jostephd** [comment]
Agreed. Let's please not make this personal.

This issue is about removing two command-line options that have a replacement. Personally, I support closing this issue as won't fix since I [don't see a need](https://github.com/wesnoth/wesnoth/pull/4386#discussion_r328156365) to remove them at all. Just keeping them for backward compatibility is fine by me. If anyone disagrees, or thinks there's something else that needs to be done, just say so.
