### ISSUE TITLE
slider disregards "min" value as offset when it is not a multiple of "step" (GNA #23466)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1467]
**[Original submission](https://gna.org/bugs/index.php?23466)** by anonymous on 2015-04-10

To reproduce, create the following slider in a [modification]:

[slider]

   id=broken_slider

   default=4

   min=1

   max=13

   step=3

   name=_"slider from 1 to 13"

   description=_"goes from 0 to 12"

[/slider]

It seems that allowed positions for the slider are only multiples of "step", even if the "min" value is meant as an offset for that.

(Reproduced on linux ubuntu)
Release: v1.12.1
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-23**

**gfgtdf changed status:** None -> Fixed

**gfgtdf wrote:**

> Seems like this was fixed when porting that dialog to gui2.

**Comment by Wedge009** [comment]
Closing with 1.14 release.
