### ISSUE TITLE
Make profile accessible via lua proxy units. (GNA #23467)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1468]
**[Original submission](https://gna.org/bugs/index.php?23467)** by anonymous on 2015-04-11

Not all of the keys in a unit (WML) are directly available in "LuaWML Units", though there is a workaround  

For example see 

http://forums.wesnoth.org/viewtopic.php?p=583220#p583220

(Reproduced on Linux)
Release: 1.12.1
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-07-14**

**gfgtdf changed title:** (lua) wesnoth.get_recall_units doesn\'t support all keys -> Make profile accessible via lua proxy units.

**gfgtdf wrote:**

> profile= beeing not accesible from lua is unrelated to whether it is recall unit or not

**gfgtdf changed category:** Bug -> Feature Request

**Comment by Vultraz** [comment]
Ok, bit of a correction here. I misread this report as requesting `profile` access in `unit_type`, not `unit`. However, you can access a unit's portrait/profile via `unit.portrait`, so this is still resolved.

@doofus-01

**Comment by CelticMinstrel** [comment]
Might want to consider adding things to the unit type that aren't currently present there but are present in the unit.

**Comment by doofus-01** [comment]
Using the same names would be great.  My confusion was that what was accessed with Lua was not the same as what was visible in written WML or `:inspect`.  (At least I think that was the issue, it was years ago...)
