### ISSUE TITLE
documentate executing order of [event] (GNA #23475)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1469]
**[Original submission](https://gna.org/bugs/index.php?23475)** by tekelili on 2015-04-13

I have not found in wiki any explanation about if [event] inside [era] has any preference for be written inside scenario over one writed inside [modification]

It is also not clear in wich order events will be written if user enables several [modification]

It looks intuitive that events directly written inside [scenario] go first, but wouldnt harm explain it. In case other tags write events after execution of name=preload written inside [scenario], it would be also good have it explained.

(Reproduced on any)
Release: 1.12.2
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-13**

**tekelili wrote:**

> Oh, also is not clear... ```[side]
> 
>     [unit]
> 
>         [event]
> 
>         [/event]
> 
>     [/unit]
> 
> [/side]```
> 
> ...in wich moment will be writed

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-13**

**tekelili wrote:**

> edit of previous post
> 
> 
> 
> It is also not clear...
> 
> ```
> 
> [side]
> 
>     [unit]
> 
>         [event]
> 
>         [/event]
> 
>     [/unit]
> 
> [/side]
> 
> ```
> 
> ...in wich moment will be writed

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-13**

**anonymous wrote:**

> There is no guaranteed order in which different [modification]s are loaded into scenario. Even if you observe in 1.12 that for example modifications are loaded in order in which they are loaded into the game config (just an example! i don't say it is like this), it might for example be changed in 1.13 that modification are loaded in the order in which the user selectes them.
> 
> 
> 
> For 1.13 the best you can do is to make feature request about an order= attribute for [modification]s or even for [event]s which specifies in which order [modification]s are loaded or where events are insertd into the list.
> 
> 
> 
> For 1.12 the best you can do is to figure out yourself in which order those are loaded.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-13**

**anonymous wrote:**

> If it's really crucial in what order they happen, I think you could force the order? If you had two events, and one of them needs to fire first, you could make it set a variable when it does fire. If the other one runs and sees that that variable is not set it could stop itself from running and set a different variable, which asks the first to call it by name when the first does run.
> 
> 
> 
> Its a bit tedious I agree but maybe you could make a macro for the whole system? Idk how it would work if you had many order-specific events.
> 
> 
> 
> I think in 1.12 it is probably deterministic but I don't know what the order is. It may depend on what other add-ons you have installed, or in what order they were clicked in the menu or something. I don't think it is alphabetic.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-13**

**tekelili wrote:**

> I think would be usefull [modification] were written by key "id=" order, like [set_menu_item] does. That way a coder could have some control about its own modifications coordination. Anyway I dont need such uber control rightnow, what it is more important for me is that if there are some known rules as: "events inside era are written first than modification ones", I would like wiki mention it, so it becomes expected behavior and I can be sure this wont change in future BfW versions.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-14**

**anonymous wrote:**

> > if there are some known rules as: "events inside era are written first than modification ones", I would like wiki mention it, so it becomes expected behavior and I can be sure this wont change in future BfW versions.
> 
> In fact it did already change (not intentionally though) in future wesnoth vrsions: in 1.13 currently events from modification are added before events from [era]. Sure it would be easy to chnage that back

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-17**

**tekelili wrote:**

> I am right now relaying for 1.12 in [era] events being fired before [modification] ones. It looks both intuitive and usefull behavior. That is why I asked for documentate it, as long there is none "expected behavior", I can not ask for a bug fix if this changes in future.

**Comment by Wedge009** [comment]
It sounds like it's not possible - at least for 1.12 - to determine the order of [event], so is it possible to document this? If not, can we close this?

**Comment by Wedge009** [comment]
Please re-open if it's deemed to be valid after all.
