### ISSUE TITLE
Automatic updater (GNA #23481)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1470]
**[Original submission](https://gna.org/bugs/index.php?23481)** by anonymous on 2015-04-14

It would be cool if wesnoth had an automatic updater, there is already a forum thread http://forums.wesnoth.org/viewtopic.php?f#12&t41861 so i made a feature request, Having an automatic updater would make updating the game easier and faster.

Since i do not know how other operating system handle programfiles (with package managers and similar) i made this report only for windows for now.

The Updater could work in the following way: We have an http server which hosts archive(zip) files which contains only those files which are changed since the previous version, Then at start the programchecks whether there are new files on the server, unpacks then if so and restarts itself if necessary.

There are some smaller technical problems with this approach but i think they can be solved:

1) On windows you cannot change an exe or dll file that is currently executed, this can usuallybe worked around by simply renaming the exe/dll file.

2) If people install wesnoth in "C:\program files" directory, wesnoth usually cannot write to that files, in order to run wesnoth as administrator wesnoth has restart itself (so 2 restarts in total, one for admin privileges, and another one to make the new changes have an effect).

(Reproduced on windows)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Vultraz** [comment]
Since we're going on Steam, where apps can be automatically updated, I don't think it's worth trying to hand-roll something like that for the desktop version. Closing.

**Comment by GregoryLundberg** [comment]
I don't care either way because it's unlikely auto-updating is ever going to work for the myriad Linux package managers.
