### ISSUE TITLE
Loading global variable that doesn't exist breaks :inspect (GNA #23489)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1471]
**[Original submission](https://gna.org/bugs/index.php?23489)** by pentarctag0n on 2015-04-15

If wesnoth tries to load the global variable that doesn't exist, the :inspect window won't display the values of any variables:

https://i.imgur.com/MPO5TCp.jpg

Reloaded when the variable exists:

https://i.imgur.com/c81c2ot.png

(Reproduced on Windows 7)
Release: 1.13+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-15**

**anonymous wrote:**

> possibly a buplicate of http://gna.org/bugs/?22263

**Comment by gfgtdf** [comment]
Since #22263 isn't on this tracker, thi migth be fixed

**Comment by CelticMinstrel** [comment]
Test it, verify, and close? :)

**Comment by Wedge009** [comment]
How can I go about testing this?

**Comment by CelticMinstrel** [comment]
Probably add a `[get_global_variable]` ActionWML tag somewhere? (Documented [here](https://wiki.wesnoth.org/PersistenceWML).) Or ask @Pentarctagon maybe.

**Comment by Pentarctagon** [comment]
This seems to have been fixed at some point, as I can't reproduce it anymore.

**Comment by Wedge009** [comment]
Beat me to it. Thanks.
