### ISSUE TITLE
remove [item]s by id (GNA #23500)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1472]
**[Original submission](https://gna.org/bugs/index.php?23500)** by anonymous on 2015-04-18

currently [remove_item] x,y#2,2 image"image1.png" [/remove_item] removes all items that on (2,2) with the image 'image1.png' even if it was previously added twice via [item].

This is often not what you want. For example if there are 2 pickupable gold items on hex (2,2) one for side1 and one for side2 placed via [item] it is not possible to only remove side1 s item if side 1 picked up that item.

It would be useful if you could give item ids that could the be used to remove that item for example in this case i could then give the first item the id gold1 and the second item the id gold2 and when side 1 steps on that hex i could only remove the [item] with the id gold1,

(Reproduced on all)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-19**

**tekelili wrote:**

> Currently you have a work around for this rare issue using IPF.
> 
> 
> 
> Lets say you have a copy of misc/blank.png on your add on called "my_blank.png"
> 
> 
> 
> Then you can place images with "id" like this
> 
> ```
> 
> [item]
> 
>     image=id1.png~MASK(my_blank.png)~BLIT(gold-bars.png)
> 
> [/item]
> 
> [item]
> 
>     image=id2.png~MASK(my_blank.png)~BLIT(gold-bars.png)
> 
> [/item]
> 
> ```
> 
> Image visible is the same, but they are removed with different names

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-19**

**anonymous wrote:**

> thx, but i guees i'l get spams of 'unfound image id1.png'... warnings with this?

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-19**

**tekelili wrote:**

> I didnt test exactly it, but I am using a similar technique in add on World Conquest II for different proposes and it works.
> 
> 
> 
> If my advice give errors, then try by using a valid image as first one (I mean, BLIT ir in images/misc/blanck.png). I can asure you I have image path functions working without error messages when only some of the images are missing.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-19**

**tekelili wrote:**

> In fact I realized you can probably just BLIT the false id image after your one and will work; wich is more simple than my first proposal.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-19**

**anonymous wrote:**

> most likeley https://github.com/wesnoth/wesnoth/commit/38ffe014163371f9bc80d053c6de097c97b304b5 is the bad commit

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-19**

**anonymous wrote:**

> sry the comment below was for bug 23460

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-19**

**anonymous wrote:**

> > In fact I realized you can probably just BLIT the false id image after your one and will work; wich is more simple than my first proposal.
> 
> I just tested your solution an i got an error in stderr.txt:
> 
> ```
> 
> 20150419 20:50:55 error display: ~BLIT(): image not found: 'id1'
> 
> ```
> 
> my code:
> 
> ```
> 
> [item]
> 
> 	x = 10
> 
> 	y = 10
> 
> 	image = items/armor.png~BLIT(id1)
> 
> [/item]
> 
> ```

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-19**

**tekelili wrote:**

> Well... if just is in stderr.txt but not in game screen, then I guess I am getting the same. It is that a relevant problem? I am living probably with it and didnt notice anything wrong.

**Comment by nemaara** [comment]
This is possible now, although the id= key is actually name=.
