### ISSUE TITLE
cannot step on hexes where movecots > max_movement (GNA #23505)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1473]
**[Original submission](https://gna.org/bugs/index.php?23505)** by anonymous on 2015-04-19

If a unit has currently 5 movepoints but only 1 max movepoint, i cannot move it over terrain where it needs 2 movepoints.

I do not know whether this bug is present on 1.12

(Reproduced on windows)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-12-10**

**gfgtdf changed status:** None -> Fixed

**gfgtdf wrote:**

> This was fixes in 1.13. (the pr was merged)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-12-10**

**gfgtdf wrote:**

> Wrong bug

**gfgtdf changed status:** Fixed -> None

**Comment by CelticMinstrel** [comment]
Is this still present in master?

**Comment by gfgtdf** [comment]
> Is this still present in master?

I'd say yes, at i reemmber no related commit sine this bug was filed.

**Comment by gfgtdf** [comment]
i looked into this a bit and this line https://github.com/wesnoth/wesnoth/blob/1.13.8/src/pathfind/pathfind.cpp#L712 seems to be the problematic one. Not sure why it's there in the first place that why i don't knwo WHTHER I CAN DELETE IT:

**Comment by CelticMinstrel** [comment]
That check should probably use the current move points, not max, right?

**Comment by gfgtdf** [comment]
no that function also chalculated multi-turn moves so even if it currnetly hasn'T enough movpoints it coudl reach tht hex on a later turn. I coudl probably change it to `total_movement_ < terrain_cost && movement_left_ < terrain_cost` though.

**Comment by gfgtdf** [comment]
ok i made a pr for this
