### ISSUE TITLE
Game at idle using 100% CPU (GNA #23536)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1474]
**[Original submission](https://gna.org/bugs/index.php?23536)** by petevine on 2015-04-25

After starting a scenario the game is consuming close to 100% cpu (athlon xp 3200) when it's completely idle (20% wesnoth, remainder Xorg)

I've been able to compare two wesnoth releases (1.8.6 vs 1.12.2) on the same hardware but on different linux systems. The old one had kernel 2.4 and xorg 6.8.2 and the recent one kernel 3.14 and xorg 1.14, both using the same version of nvidia binary drivers. The old one is using close to 0% CPU in that same scenario.

I'm attaching output from gdb from those two systems for comparison.

(Reproduced on Linux)
Release: 1.12.2
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-25**

**petevine added attachment:** [comparison.txt](http://gna.org/bugs/download.php?file_id=24349)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-04-26**

**petevine wrote:**

> It's getting more interesting.
> 
> I can see there's a difference between MP and mainline campaign scenarios in the latest version of wesnoth (but not the old one).
> 
> In 6p team survival it's about 85%, in Nosmo's 3p around 50% and in a normal campaign scenario between 6-30%.
> 
> In the latter case backtrace looks almost exactly like the old one (which still was using close to nothing)
> 
> Has there been some serious regression esp. in MP?

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-05-06**

**shadowmaster wrote:**

> Are you building 1.12.x from source with OpenMP support enabled? If so, what happens if you run a build with it disabled?

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-05-07**

**petevine wrote:**

> It was already built without OpenMP (like the old one probably)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-05-18**

**petevine wrote:**

> I've run the old 1.8.6 binary on the new system and the results are fully consistent which means the problem doesn't come from broken Xorg/SDL, etc.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-05-18**

**shadowmaster wrote:**

> So, did you build 1.12.x yourself from source? Did you use cmake? If so, did you make sure to select the Release build type (cmake <path> -DCMAKE_BUILD_TYPE=Release)? This is an important detail that's very easy to miss (see bug #23445) because Wesnoth is heavily CPU-bound, and drawing operations in particular are expensive. The default CMake build type is better suited to debugging purposes and it doesn't have any compiler optimizations enabled at all, unlike the Release type which uses -O3.
> 
> 
> 
> Since you say there is a difference between MP and single-player, I thought it might be related to the chat log overlay on the top left corner of the game view. In single-player it's not shown unless you play a scenario that prints messages to chat or mess with command mode, but in multiplayer you are more likely to receive chat messages from the server or other players.
> 
> 
> 
> Also, just to clarify the original post, did you try Wesnoth 1.12.x on *both* operating systems on the same hardware, or you just separately tried 1.8.x on the older OS and 1.12.x on the newer?

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-05-19**

**petevine wrote:**

> I'm pretty sure I built the release version (at first I was using scons and it was exactly the same). 
> 
> As for the MP part it's a local game, completely offline even.
> 
> I had to copy libboost and libicu binaries from the old system to run 1.8.6 so it's possible the problem could be narrowed down to the newer boost.
> 
> I won't be able to do the inverse test as 1.12 won't build on the old system.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-05-21**

**petevine wrote:**

> I'm attaching callgrind analysis from both versions.
> 
> (file #24526, file #24527)

**petevine added attachment:** [1.12.2](http://gna.org/bugs/download.php?file_id=24526)

**petevine added attachment:** [1.8.6](http://gna.org/bugs/download.php?file_id=24527)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-10-28**

**petevine wrote:**

> I've tried again with the latest 1.12.4 and there's no difference.
> 
> 
> 
> A pity.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-06**

**wedge009 wrote:**

> Just as a comment, CPU usage also varies dependent on what's in the display. Other reports have indicated that maps predominantly made of water (eg Dead Water scenarios), with animations switched on, soak up a lot of CPU power.
> 
> 
> 
> Presumably you're using the same scenario for your testing across machines/OSs, though. The long-term plan is for hardware acceleration to be enabled so hopefully that will alleviate performance issues in the future.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-06**

**wedge009 wrote:**

> Also, the Athlon XP 3200 is a rather old CPU now (more than a decade old, even at the time of the original report). Not a slight against it - it was great for its time and I've used it myself plenty of times.
> 
> 
> 
> Granted, one would expect that a 2D game like Wesnoth wouldn't take up that much in processing power, though.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-06**

**petevine wrote:**

> It's either between BfW 1.8 and 1.12, each and every tested map (especially the MP ones) went from 0% at idle to those high numbers due to some new scripting going on or there's lots of needless polling/redrawing.
> 
> 
> 
> Either way it's a regression of some sort. No need to bring absolute CPU power into this. 
> 
> 
> 
> Lastly, binaries from slackonly.com also behave this way so a local build problem can be ruled out.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-06**

**wedge009 wrote:**

> Any idea how 1.10.x performs? I don't think anyone really knows of that 'single change' which seems to have killed the performance in the most recent release branch.

**Comment by Wedge009** [comment]
No response for several years. Re-open if still needed.
