### ISSUE TITLE
new add-on type "developer-resource/tool" (GNA #23566)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1478]
**[Original submission](https://gna.org/bugs/index.php?23566)** by anonymous on 2015-05-03

I propose to add a new add-on type "developer-resource/tool" for add-ons that are only interresting for developers. These add-ons could contain wml/lua samples or tools that help devepoing add ons (like debugging tools or the 'Image loading tester').

(Reproduced on all)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-05-05**

**shadowmaster wrote:**

> There already is a Resource category.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-05-06**

**anonymous wrote:**

> the description for "Resource" (in http://add-ons.wesnoth.org/1.12/) says: "Usually a (perhaps optional) dependency of another add-on." which is different from this proposal.

**Comment by Wedge009** [comment]
Current add-on types (1.14.7) are:
- Campaigns
- Scenarios
- SP/MP Campaigns
- MP Campaigns
- MP Scenarios
- MP Map Packs
- MP Eras
- MP Factions
- Modifications
- Cores
- Resources
- Other
- Unknown

Hmm, wonder what's the difference between Campaigns, SP/MP Campaigns, and MP Campaigns? I suppose the first is SP only and the second can be used for both SP and MP?

I also wonder what's the difference between a scenario and a map pack. Although I suppose a map pack might be a series of scenarios that aren't related like they would be for a campaign. Still, I wonder if the two types could be consolidated.

Back to the topic, I notice @sigurdfdragon's GUI Debug Tools are currently classed under Other. It would be suitable for a new developer category, I suppose.

**Comment by soliton-** [comment]
From a map pack I'd expect just a bunch of maps not necessarily with accompanying scenario files at all or just very basic ones. Scenario would be more elaborate with story and such. Basically like a campaign but just a single scenario. (Still can be multiple independent scenarios in one addon.)

To decide if a new category is needed perhaps we should look at everything in the "other" category and see if anything sticks out. In the end it depends how people use the categories since nothing is enforced. You can put whatever you like in an addon.

**Comment by Wedge009** [comment]
Oh I see, scenario = map + story and other features.

**Comment by Wedge009** [comment]
Current 1.14 add-on list for Other is quite brief. @doofus-01's Archaic packs could probably go under Resources. There's a few modifications that should probably go under Modifications. That just leaves:
- @jostephd's Combat Information Theme
- @ln-zookeeper's Generic Animations
- @sigurdfdragon's GUI Debug Tools
- Move Units Between Campaigns
- @ancestral's Simple Hot Keys
- UMC_Terrain_Pack_Old
- War of the Gods 2 (campaign?)

So not much there to make another type worth it, perhaps.

**Comment by jostephd** [comment]
Combat Info Theme, Simple Hot Keys, and Move Units Between Campaigns wouldn't belong in "developer-resource/tool". The first two are UI tweaks, the third is basically a mod that uses persistent state.

I think we can close this issue. We can always reopen it if we find there are many addons in "Other".

**Comment by Wedge009** [comment]
Sounds good.
