### ISSUE TITLE
A New Land no longer allows you to recruit peasants (GNA #23593)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1479]
**[Original submission](https://gna.org/bugs/index.php?23593)** by legrande on 2015-05-13

I just upgraded to 1.12 from Jessie-backports. When I started to play a local game of A New Land from the Multiplayer scenarios, I discovered that the Loyalists can not recruit peasants anymore. Peasants are an important part of A New Land, so not having the ability to recruit them severely hampers gameplay.

(Reproduced on Debian Jessie)
Release: 1.12
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-12**

**shadowmaster wrote:**

> It seems [side] faction_from_recruit doesn't have the effect it had on 1.10 (or doesn't have the intended effect for this scenario in particular?), resulting in this.
> 
> 
> 
> Note that it is possible to leave the default "Custom" faction selected for all sides to get the correct recruit lists.

**shadowmaster changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-12**

**shadowmaster wrote:**

> Committed a [work-around](://git.io/vI5va) for 1.12.3 that has the side-effect of allowing any leader to be selected with Use Map Settings on, unlike 1.10 which would limit the faction selection to Loyalists (again, faction_from_recruit doesn't seem to work as intended). I figured we'd rather have that (and the potential gameplay implications with faster or slower leaders, etc.) than a broken scenario.
> 
> 
> 
> (Also, an errata for the commit message: Use Map Settings being on or off is unrelated. It's just that if you specifically choose Loyalists you'll get the ANL recruit list instead of the faction's.)

**Comment by CelticMinstrel** [comment]
So it sounds like this is fixed then?

@shikadilord

**Comment by shikadilord** [comment]
I don't know and I don't remember what was the intended behavior.

**Comment by CelticMinstrel** [comment]
Maybe @gfgtdf would know? I seem to recall him doing something on ANL more recently.

**Comment by gfgtdf** [comment]
the last comment said that in 1.10 you could only choose your leaders form the loyalists faction leaders while in 1.13 you can choose a leader from any faction. I don't think the old bahviour is really better than the new beahviour though, so i think we can call this fixed.

**Comment by gfgtdf** [comment]
> Maybe @gfgtdf would know? I seem to recall him doing something on ANL more recently.

i didn't work on ANL recently, maybe yo0u rememberd my work on dark forcast mp scenario?

**Comment by CelticMinstrel** [comment]
That could be what I was remembering, yeah.

**Comment by pydsigner** [comment]
As it stands, there's use of faction lock somehow giving access to all leader units in whatever era you choose, with the Peasant and Mage recruits set in the side descriptions. If you disable use_map_settings when you set up the game, all that breaks. I'd like to see this improved by using [set_recruit] in an event.

**Comment by gfgtdf** [comment]
with https://github.com/wesnoth/wesnoth/commit/0c92fbd10ba627c05edf401532dc5e9005192ff8 this shouldn't be a problem anymore.

**Comment by sevu** [comment]
Apparently no issue anymore.
