### ISSUE TITLE
Clicking cancel when waiting for players to join steps back to second game creation screen (GNA #23638)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1481]
**[Original submission](https://gna.org/bugs/index.php?23638)** by anonymissimus on 2015-06-08

In 1.10, when waiting for players to join a mp game, clicking cancel takes me back to the game creation screen, of which there is only one.

In 1.12, the button is still named cancel, but it takes me back to the second game creation screen, then I need to click back and again cancel to be able to see the current games. Thus that action I want to do most of the time requires 3 clicks instead of just 1.

The current button should be named "back" and there should be an additional cancel button at the old position performing the action as in 1.10, on the second creation screen as well probably.

(Reproduced on Lubuntu trusty)
Release: 1.12.2+dev@85ef902960270779b798add026c8b
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-08**

**anonymissimus changed item group:** None of the others -> Multiplayer

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-11**

**shadowmaster changed category:** Bug -> Feature Request

**Comment by Wedge009** [comment]
Local MP cancel goes back to the main menu. In networked MP, cancelling a game goes back to the main lobby. So I'm guessing the 'three clicks' report for 1.12 was for the older MP lobby, when the current one was still called 'experimental'.

Tested on official 1.14.7 release.
