### ISSUE TITLE
Mini-map settings persist in MP lobby and load game preview (GNA #23647)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1484]
**[Original submission](https://gna.org/bugs/index.php?23647)** by anonymous on 2015-06-15

In the mp lobby the game uses the same settings for drawing minimap as during the game. This is problematic if you turned 'Draw Terrain' off (so that only the units are visible on the minimap) because then maps will not be shown in there are 2 solutions to fix this problem:

1) Ignore the 'Draw Terrain' setting in the mp lobby

2) Add buttons or other widgets in the mp lobby to change minimap preferences.

(Reproduced on windows)
Release: 1.12.2
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Wedge009** [comment]
Not sure how I missed testing this previously. But I don't see this issue in master, only in 1.12 branch. Presumably due to the gui2 MP lobby.

What to do with this? It's a big change to 'back-port' to 1.12.

**Comment by Wedge009** [comment]
The MP lobby might not be an issue in master but I just notice that the mini-map preview in the load game dialogue has this issue - it follows whatever settings you have put on the mini-map in the main game as well.

**Comment by CelticMinstrel** [comment]
I'm guessing that if it happens in Load Game it's fairly likely that it also happens in MP Lobby and MP Create...

**Comment by Wedge009** [comment]
Okay, I confirm it's an issue for MP lobby in master still. The trick is that the mini-map settings seem to be read once on application start and it retains those settings throughout the application session. I replicated with this:

1. Assuming default mini-map settings, load/start any game, disable the Draw Terrain (hexagon icon second from left) and exit the whole application.
2. Restart application, and observe missing terrain in mini-map on load game dialogue and MP lobby.

**Comment by Wedge009** [comment]
Confirmed, the lobby and load game mini-maps appear to be independent of the in-game mini-map now. Thanks.
