### ISSUE TITLE
bugs in Legend of Wesmere with shuffle sides active (GNA #23650)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1485]
**[Original submission](https://gna.org/bugs/index.php?23650)** by anonymous on 2015-06-18

When you activate 'shuffle sides' when playing LoW bugs will appear.

Proposed solution:

It should not be possible to activate 'shuffle sides' in Legend of Wesmere.

(Reproduced on windows)
Release: 1.12.2, 1.13.0
Priority: 5 - Normal
Severity: 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-06-25**

**shadowmaster changed severity:** 3 - Normal -> 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-20**

**wedge009 wrote:**

> Somewhat related: bug #25604

**Comment by Wedge009** [comment]
Somewhat related: #1638

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/570e1b2d2f0d0d1da150dfbc1987937fcc0262e2 fixes this.
