### ISSUE TITLE
[unit_type] in [scenario] (GNA #23654)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1487]
**[Original submission](https://gna.org/bugs/index.php?23654)** by anonymous on 2015-06-20

It would be useful if [unit_type] would be read from [scenario]. The intention is, to make it possible for the host to transfer [unit_type]s over network to other players. if [unit_type] were read form [scenario]/[multiplayer] you could just put your unittypes there and they would automaticly transfered to other players among everything else inside [scenario].

(Reproduced on all of them)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by gfgtdf** [comment]
Iirc i was the one who suggsted this and in particular with the automatic download of addons, i don't think there is a reason for that anymore
