### ISSUE TITLE
wesnothd does not save replays when advancing to the next scenario (GNA #23675)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1492]
**[Original submission](https://gna.org/bugs/index.php?23675)** by tekelili on 2015-07-03

When players beat a scenario of a multiplayer campaign, replay is not stored in Wesnoth Index of Replays. Replays are stored when players quit or they are defeated.

(Reproduced on any)
Release: 1.12.4
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-07-04**

**anonymous wrote:**

> Also the server ignores the replay_save# value inside [endlevel] (even if resultdefeat)

**Comment by jostephd** [comment]
I cannot reproduce this with the last scenario of HttT on 1.14.3: when I kill Asheviere, a replay is created and saved.

**Comment by gfgtdf** [comment]
the is a an issue about multiplayer games and the replays on replays.wesnoth.org

**Comment by jostephd** [comment]
I launched HttT as an MP game, but I thought this issue was about the local saves/ dir. Thanks for the correction.

**Comment by soliton-** [comment]
The replay is saved.

https://github.com/wesnoth/wesnoth/blob/b14a4b1bb355da1f076ed57a9d54aeddaa75a58b/src/server/server.cpp#L1542

Need to figureout if/why the games do not end up in the replay archive.

**Comment by gfgtdf** [comment]
from lloking at the code:

the `update_game` here 
https://github.com/wesnoth/wesnoth/blob/7ce90285eaf01435436adeb86f59412869aa591b/src/game_initialization/connect_engine.cpp#L795

sets `game::started_` to false which is checked by `game::save_replay`

**Comment by gfgtdf** [comment]
maybe this is broken in https://github.com/wesnoth/wesnoth/commit/8c4e11700e51cb9e30dbde971f8b7427d831b915 ? in any case i think we can just delete that `update_game` there and i needed copy the logic to the store_next_scenario handler

**Comment by soliton-** [comment]
Yes, thanks for tracking that down. I agree that the update_game message seems useless and the same can just be done with store_next_scenario.

**Comment by gfgtdf** [comment]
pushed a commit, untested yet though,

@soliton- can you soon restart the 1.15 mp server please so that i can test it?

**Comment by soliton-** [comment]
Sure. Why set started_ to false at all though?

**Comment by gfgtdf** [comment]
> Sure. Why set started_ to false at all though?

Not really sure, but some of the functions like for example game::take_side check for started_, so i didnt want to break anything. I assume the reason for this might be the cases where the mp connect screen is shown between scenarios (for example becasue teh new scenairo has more play slots than the old one)

**Comment by soliton-** [comment]
Well, started_ was true before https://github.com/wesnoth/wesnoth/commit/8c4e11700e51cb9e30dbde971f8b7427d831b915 and I‘ve recently added logic back that got lost that‘s based on started_ being true for games that advance to the next scenario. This could be done differently of course.

Restarted dev server anyway.

**Comment by soliton-** [comment]
Please backport to 1.14 once tested.

**Comment by gfgtdf** [comment]
> Restarted dev server anyway.

whcih server is this i just 'connect to official server' tried on my 1.15.1+dev buidl and /q version still tells me 1.15.0+dev

**Comment by soliton-** [comment]
If you connect with a +dev version you don’t get redirected then you need to connect explicitly to port 14997.
