### ISSUE TITLE
Warning that add-on updated failed not displayed (GNA #23687)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1493]
**[Original submission](https://gna.org/bugs/index.php?23687)** by pentarctag0n on 2015-07-11

When updating an add-on from the server that has a .pbl file that would be over-written, if the update fails the UI still shows the message that is succeeded.  There is a warning/error in the stderr.txt stating that the updated failed.

(Reproduced on Windows 7)
Release: 1.13.1+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Wedge009** [comment]
Can anyone replicate this?

**Comment by soliton-** [comment]
Perhaps @Pentarctagon can.

**Comment by Pentarctagon** [comment]
I don't remember what I did, so unfortunately not.
