### ISSUE TITLE
exit_hex event preventing any movement (GNA #23704)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1496]
**[Original submission](https://gna.org/bugs/index.php?23704)** by ravana on 2015-07-21

[event]

	name=exit_hex

	first_time_only=no

[/event]

Having this in scenario, no matter if event has any actions or not, will prevent all player and ai movement.

Attacking without moving is still possible.

For ai movement attempts it shows up in stderr as

20150721 21:56:49 error ai/actions: Error #2007 (E_NOT_REACHED_DESTINATION) in full move by side 1 from location 6,19 to location 12,16

20150721 21:56:49 warning ai/ca/testing_move_to_targets: unexpected outcome of move

Effectively this makes all exit_hex events unusable currently.

(Reproduced on any)
Release: 1.12.4, 1.13.1
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-07-21**

**ravana wrote:**

> Seems I formed the report incorrectly, the part I deemed most important was actually intended.
> 
> 
> 
> The original case that players reported was exit_hex with [filter_condition] that would fire only for first try of moving.
> 
> And that stopped all ai attacks of that turn.
> 
> 
> 
> So first all ai units that would normally attack move to attack, but do not attack. then all ai units with nothing in range move towards player, and then ai ends turn.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-23**

**gfgtdf wrote:**

> See also this related issue https://gna.org/bugs/?22988

**Comment by gfgtdf** [comment]
@ProditorMagnus this was changed in https://github.com/wesnoth/wesnoth/commit/821e27c34f222c72d1cb02100370e0f7df2a75c2 . In 1.13.9 enter/exit hex event no longer interrupt movement/atacks, you now need to explcitly use [cancel_action] to interrupt the moevment
