### ISSUE TITLE
Illuminates not working as advertised (GNA #23749)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1498]
**[Original submission](https://gna.org/bugs/index.php?23749)** by bob_the_mighty on 2015-08-03

Some of the keys in the illuminates ability seem to be broken. I have an ability which is meant to change the TOD for the unit with the ability and no one else. Both affect_allies=no and affect_enemies=no do not produce the desired effect. Nor does putting in a impassable filter. All adjacent units are affected. Here's my code.

```
#define ABILITY_BRIGHTENS
[illuminates]
	id=brightens
	value=10
	max_value=25
	cumulative=no
	name= _ "brightens"
	female_name= _ "female^brightens"
	description= _ "If this unit is lawful it will fight with a +10% damage bonus at dusk and dawn, and a only -15% penalty at night. Units on adjacent hexes are not affected."
	affect_self=yes
	affect_allies=no
	affect_enemies=no
	[affect_adjacent]
		[filter]
			ability=this_is_to_stop_anyone_else_being_affected
		[/filter]
	[/affect_adjacent]
[/illuminates]
#enddef
```

(Reproduced on Windows 7)
Release: 1.12
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-09**

**sigurdfdragon wrote:**

> Confirmed that the wml below doesn't work.
> 
> 
> 
> However when read the wiki entry and searched the c++ code in /src for "illuminates", I got the impression that the intent of the illuminates tag was not to use most of the common keys and tags for abilities. So it seems the wiki might have it incorrect or need clarifying. Though my statements need to be confirmed.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-09**

**gfgtdf wrote:**

> I think the reson might be tha [illuminates], unlike [leadership], doesnt change units but the terrain (or rather the tod of that terrain) that's why tags like thinkgs like [filter_adjacent] unit filters have no effect.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-09**

**gfgtdf wrote:**

> You can for exampel see that when you hover over a tile next to a unit that its tod is illuminated, even if there is no unit on it.

**Comment by sevu** [comment]
added it to the wiki
