### ISSUE TITLE
gui2 listboxes header not working correctly (GNA #23752)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1499]
**[Original submission](https://gna.org/bugs/index.php?23752)** by anonymous on 2015-08-04

the headers of gui2 listboxes (which are defined inside [header]) should, like gui1 listboxes headers, be outside the scroll area so that they are always on top of the list unrelatd to where the scrollbar grip is.

(Reproduced on )
Release: 1.13
Priority: 5 - Normal
Severity: 5 - Blocker

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-08-06**

**gfgtdf wrote:**

> I investigated this problem, and its harder than it seems at first:
> 
> 
> 
> Assume we have a normal vertical listbox which is very big so that we need vertical and horizontal scrollbars. In this case its not that trivial as moving the header out of the scroll area becasue we want the header to be effected by horizontal scrolling but not by vertical scrolling.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-03**

**gfgtdf changed item group:** None of the others -> User Interface

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-13**

**shadowmaster changed severity:** 3 - Normal -> 5 - Blocker

**shadowmaster wrote:**

> Promoted to blocker since this now visibly affects the Load Game and Create Unit dialogs after they were ported by GUI2/enabled.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-14**

**vultraz wrote:**

> There is a workaround for this: keep the header in a separate row above the listbox in a per-dialog basis.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-15**

**gfgtdf wrote:**

> This is definiteeley not a perfect workaround becasue it wont be effected be horizontal scrolling so you have to know that this lisxox never has horizontal scorlling. Also you have to account for the pace taken by the vertical_scollbar, so you have to know whether a vertical scrollbar exists or not.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-29**

**vultraz wrote:**

> I committed a similar workaround to what I had suggested before: https://github.com/wesnoth/wesnoth/commit/12ba9bd5c78919621718434591d511c66c10d774
> 
> 
> 
> Instead of doing it on a per-dialog basis, doing this in the widget definition means dialogs don't have to worry about vertical scrollbar presence.
> 
> 
> 
> This isn't a perfect solution, since as gfgtdf mentioned, this renders horizontal scrollbars on listboxes with header useless (hopefully a rare occurrence - I can't think of any mainline cases, even) but it will do for now.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-03-04**

**vultraz changed status:** None -> In Progress

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-01-19**

**celticminstrel wrote:**

> When you say no mainline listboxes need horizontal scrollbars, I sure hope that means on 800x600 resolution...

**Comment by Vultraz** [comment]
Demoting from blocker since this really isn't a blocker. The case I described above still remains, but that's very much an edge case.

**Comment by Wedge009** [comment]
Where does this remain in 1.14.7? (Does it?) I find the hot-key preferences menu has a horizontal scroll with some translations, but I haven't seen it as a bad enough problem such that I lose the header. Headers are correctly excluded from vertical scroll.

**Comment by gfgtdf** [comment]
> Where does this remain in 1.14.7? 

Probably not, but that does not.mean it can be closed so nice it can still effect dialogs in umc.

**Comment by Wedge009** [comment]
Nice?

**Comment by gfgtdf** [comment]
> Nice?

corrected it

**Comment by Wedge009** [comment]
Actually, I encountered this issue while looking at the Game/Editor/Title heading of the hot-keys list for #1152 .

**Comment by Wedge009** [comment]
Aforementioned issue was likely in 1.14.x. 1.15.17+dev seems to mitigate this by allowing the width of the preferences dialogue to expand.

I'm not aware of other places to check for this issue. I don't really look at UMC.

**Comment by Wedge009** [comment]
Closing due to lack of further information.
