### ISSUE TITLE
a [make_tag] tag to create custom wml tags. (GNA #23841)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1503]
**[Original submission](https://gna.org/bugs/index.php?23841)** by anonymous on 2015-09-01

I don't know any usecases for it but i tought it was a funny idea:

One could add a [make_tag] tag which creates custom wml tags:

```

-- A tag to create new wml tags

wesnoth.wml_actions.make_tag = function(cfg)

	local tagname = cfg.tagname

	local command = helper.get_child(cfg, "command")

	wesnoth.wml_actions[tagname] = function(args)

		local old_args = wesnoth.get_variable("args")

		wesnoth.set_variable("args", args)

		wesnoth.wml_actions.command(command)

		wesnoth.set_variable("args", old_args)

	end

	-- TODO: Use wesnoth.game_events.on_load/save to make those tags persistent.

end

```

This could then be used for example like this:

```

[make_tag]

##	triggers an advancement for the given unit (which shows an advancement dialog)

	name = "advance_unit"

	[command]

		[store_unit]

			[filter]

				x = "$args.x"

				y = "$args.y"

			[/filter]

			## args variable will be cleared automatically

			variable = "args.unit"

		[/store_unit]

		[set_variable]

			name = "args.unit.experience"

			add = "args.unit.max_experience"

		[/set_variable]

		[unstore_unit]

			variable = "args.unit"

			fire_event = yes

		[/unstore_unit]

	[/command]

[/make_tag]

[advance_unit]

	x,y = 7,4

[/advance_unit]

[advance_unit]

	x,y = 8,4

[/advance_unit]

[advance_unit]

	x,y = 9,4

[/advance_unit]

```

(Reproduced on any)
Release: 1.13
Priority: 5 - Normal
Severity: 1 - Wish

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-01**

**tekelili wrote:**

> It you any doubt about its usefullness I can tell you I have dreamed with something like this beign implemented for years :)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-01**

**anonymous wrote:**

> Ok i made a new (tested) version that makes the custom wml tags also persistent (so that they won't be lost when reloading):
> 
> 
> 
> Lua code:
> 
> 
> 
> ```
> 
> local helper = wesnoth.require("lua/helper.lua")
> 
> local _ = wesnoth.textdomain 'wesnoth'
> 
> local T = helper.set_wml_tag_metatable {}
> 
> 
> 
> -- a map string -> vconfig
> 
> local wml_defined_tags = {}
> 
> 
> 
> local add_new_wml_tag = function(tagname, command)
> 
> 	if type(command) # "table" then
> 
> 		command = wesnoth.tovconfig(command)
> 
> 	end
> 
> 	wml_defined_tags[tagname] = command
> 
> 	wesnoth.wml_actions[tagname] = function(args)
> 
> 		local old_args = wesnoth.get_variable("a")
> 
> 		wesnoth.set_variable("a", args)
> 
> 		wesnoth.wml_actions.command(command)
> 
> 		wesnoth.set_variable("a", old_args)
> 
> 	end
> 
> 	
> 
> end
> 
> 
> 
> local old_on_save = wesnoth.game_events.on_save
> 
> wesnoth.game_events.on_save = function()
> 
> 	local cfg = old_on_save()
> 
> 	for k,v in pairs(wml_defined_tags) do
> 
> 		table.insert(cfg, T.wml_defined_tag {
> 
> 			tagname = k,
> 
> 			T.command(helper.literal(v)),
> 
> 		})
> 
> 	end
> 
> 	return cfg
> 
> end
> 
> 
> 
> local old_on_load = wesnoth.game_events.on_load
> 
> wesnoth.game_events.on_load = function(cfg)
> 
> 	for i = #cfg,1,-1 do
> 
> 		local v = cfg[i]
> 
> 		if v[1] # "wml_defined_tag" then
> 
> 			local v2 = v[2]
> 
> 			add_new_wml_tag(v2.tagname, helper.get_child(v2, "command") )
> 
> 			table.remove(cfg, i)
> 
> 		end
> 
> 	end
> 
> 	old_on_load(cfg)
> 
> end
> 
> 
> 
> wesnoth.wml_actions.make_tag = function(cfg)
> 
> 	local tagname # cfg.tagname or helper.wml_error "[make_tag] missing required tagname attribute."
> 
> 	local command # helper.get_child(cfg, "command") or helper.wml_error "[make_tag] missing required command child."
> 
> 	add_new_wml_tag(tagname, command)
> 
> end
> 
> 
> 
> 
> 
> ```
> 
> 
> 
> How to use:
> 
> 
> 
> ```
> 
> [make_tag]
> 
> ##	triggers an advancement for the given unit (which shows an advancement dialog)
> 
> 	tagname = "advance_unit"
> 
> 	[command]
> 
> 		[store_unit]
> 
> 			[filter]
> 
> 				x = "$a.x"
> 
> 				y = "$a.y"
> 
> 			[/filter]
> 
> 			## a variable will be cleared automatically
> 
> 			variable = "a.unit"
> 
> 		[/store_unit]
> 
> 		[set_variable]
> 
> 			name = "a.unit.experience"
> 
> 			add = "$a.unit.max_experience"
> 
> 		[/set_variable]
> 
> 		[unstore_unit]
> 
> 			variable = "a.unit"
> 
> 			fire_event = yes
> 
> 		[/unstore_unit]
> 
> 	[/command]
> 
> [/make_tag]
> 
> 
> 
> [advance_unit]
> 
> 	x,y = 16,17
> 
> [/advance_unit]
> 
> ```
> 
> 
> 
> i also renamed 'args' to 'a', first becasue that is easier to type, but also because short variable names are usually faster than long ones in execution.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-01**

**anonymous wrote:**

> This code will also work in 1.12.x, just put it in a toplevel [lua] tag in your campaign.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-01**

**anonymous wrote:**

> I think it could benefit from a slightly more standardized approach to return values, and maybe a different name, but overall I think it seems good. Also, maybe it should support delayed_variable_substitution=no.
> 
> 
> 
> My only concern is that, as written, it's kind of dangerous. You can use it to blindly overwrite any WML tag with a new definition, including [make_tag] itself. I think the ability to overwrite tags is beneficial, but either it should be explicitly enabled behaviour (ie something like overwrite=yes) or preset WML tags should be protected from being overwritten somehow, so that only tags defined by [make_tag] can be overwritten by [make_tag].
> 
> 
> 
> Also, a delete form (in analogy to [event]delete=yes) could make sense.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-01**

**anonymous wrote:**

> Oh, one other thing (I'm the same person who posted the previous comment #4) - if the ability to overwrite the preset tags is retained, then there should be a way to restore the default behaviour of a preset tag.
> 
> 
> 
> ~~CelticMinstrel

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-04**

**anonymous wrote:**

> > ... You can use it to blindly overwrite any WML tag with a new definition ...
> 
> 
> 
> A check for wesnoth.wml_actions[tagname] # nil should be easy to implement, but also i think the chances that someone really does that accidently are rather small, also it mostlikeley will only effect your addon anyway.
> 
> 
> 
> In any case feel free to use that code in your addons.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-12**

**vultraz wrote:**

> wesnoth.wml_actions.tagname can already be used to overwrite an existing tag, and in fact, is done in some cases. This tag doing the same thing should not be a problem.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-01-19**

**celticminstrel wrote:**

> Normally when you overwrite an existing tag, it's to extend it; the original implementation is saved first, and then called from the new implementation. It's not a problem to be able to overwrite an existing tag, but it's not good to be able to _accidentally_ overwrite an existing tag.

**Comment by Vultraz** [comment]
Closing since I already rejected the FR. I still don't think this is a good design choice.
