### ISSUE TITLE
SDL 2 focus loss on default doesn't work well with strategy games. (GNA #23857)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1504]
**[Original submission](https://gna.org/bugs/index.php?23857)** by aethaeryn on 2015-09-06

By default, SDL 2 minimizes a fullscreen window on loss of focus. This default behavior doesn't work well with slow-playing strategy games. It is common behavior to multitask when it's not one's turn in multiplayer and on a computer that has multi-monitor or a large monitor it is really annoying to have this constant, unnecessary minimizing and unminimizing.

https://wiki.libsdl.org/SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS

(Reproduced on All)
Release: 1.13.2
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-09-08**

**aginor changed release:** 1.13 -> 1.13.2

**Comment by Wedge009** [comment]
I never recall this happening and does this even happen currently? I can lose focus and leave the window as-is, at least in Windows.

**Comment by GregoryLundberg** [comment]
Linux too. I'd suggest we mark this Invalid and close it. My guess is it was a config problem for the OP

**Comment by Wedge009** [comment]
Thanks.

**Comment by jyrkive** [comment]
No, this bug report is just a duplicate of #1606 that I fixed in August.
