### ISSUE TITLE
attempt to add an [event] with empty id=, ignoring (GNA #23893)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1507]
**[Original submission](https://gna.org/bugs/index.php?23893)** by anonymous on 2015-09-20

I sometimes get a message 'attempt to add an [event] with empty id=, ignoring' in stderr.txt

I think this is a bug because the id= attribute is not necessary accoring to the wiki.

(Reproduced on windows)
Release: 1.12.4
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-11-04**

**anonymissimus changed status:** None -> Invalid

**anonymissimus wrote:**

> You seem to have at least one [unit_type][event] without an id#. For such [event]s id is mandatory according to the wiki. Once such a unit is created in a scenario that message is emitted.
> 
> Marking invalid.
> 
> (It is mandatory as there has to be only one [unit_type][event] per unit_type, not several per each [unit] of that type.)

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-12-16**

**shadowmaster closed the issue**

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-06-23**

**gfgtdf changed status:** Invalid -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-06-23**

**gfgtdf wrote:**

> This just happend to me in 1.12.5, and like said in the original message, the error message printed by wesnoth is quiet confusing since it doesn't mention that the [event] was in a [unit_type]
> 
> 
> 
> Reopeining this.

**gfgtdf reopened the issue**

**Comment by stevecotton** [comment]
The log doesn't seem to be for a `[unit_type]`, but for a single unit created with `[unit]` that has events specific to that individual unit. I'm unsure of the uses of that feature, but believe they might now be done more easily with `[load_resource]`.

I self-assigned this intending to improve the logging, but it seems a reasonable log message would require adding an extra parameter to multiple functions just to pass debugging info from `game_events::wml_func_unit`. That doesn't seem worthwhile.

**Comment by Pentarctagon** [comment]
Should this be closed then?
