### ISSUE TITLE
default zoom level bar in preferences (GNA #24034)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1518]
**[Original submission](https://gna.org/bugs/index.php?24034)** by neverenough on 2015-11-05

When game starts zoom level must always get adjusted on some laptop screens to give the fair sight of the game. Would be nice if this could be tuned on settings with an adjustable bar

(Reproduced on any)
Release: any
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-11-06**

**neverenough wrote:**

> i just noticed an old related issue
> 
> https://gna.org/bugs/?13190

**Comment by Wedge009** [comment]
If I understand this correctly, this is asking for a default zoom option to be included in the preferences, to be the first zoom level displayed when going to a game.

**Comment by jostephd** [comment]
That's my understanding too. It doesn't need an explicit preference; we can just remember the last used zoom in a hidden preference (like #1090).
