### ISSUE TITLE
Add a countdown before starting MP game (GNA #24040)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1519]
**[Original submission](https://gna.org/bugs/index.php?24040)** by neverenough on 2015-11-07

I think the game really lacks possibility for players to pick race/leader while in game lobby. While it would be an overall nice upgrade to game, there are also some RPG maps (Bob's Era) where ur choice is strictly related to other players, usually after some chat about strats and tastes.

Also, related to bug #20394:

In some commercial games it is normal to start a short countdown when host clicks "start". During the count others clients screens get darker and buttons aren't clickable anymore, they see just the count rollin down. This behaviour freezes any player setting mentioned above, and avoids the bug #20394 to happen.

What do you think?

(Reproduced on any)
Release: any
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-11-23**

**gfgtdf wrote:**

> I think it would be useful to be able to change leaders/factions not only when joining teh game.
> 
> 
> 
> I dont see how a counddown timer would fix #20394. Also i don't know why you posed this proposal about #20394 here and not in the tread of #20394.

**Comment by wesnoth-bugs** [comment]
**Modified on 2015-12-03**

**neverenough wrote:**

> Selectable items after join looks like a new features to me. I pointed _here_ it could help with an other bug. I'm doing it wrong?

**Comment by Wedge009** [comment]
1.14.7 allows for change of leader/faction upon joining a game, so that just leaves the 'change freeze' period before a game starts.

GNA #20394 is now #1328.

**Comment by jostephd** [comment]
A countdown isn't going to make #1328 impossible. A player could easily disconnect just as the countdown finishes, leading to the same problem. (Even if you disable the Leave button people will close the entire BfW app/window)

I'm going to go ahead and close this. If someone disagrees, or has some _other_ reason for wanting a countdown, do reopen.
