### ISSUE TITLE
assertion failure when quitting (GNA #24119)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1523]
**[Original submission](https://gna.org/bugs/index.php?24119)** by gfgtdf on 2015-11-23

I just quitted the game while observing a mp game (some WC2 game it was i think (not sure)), and i got this assertion failue:

File: boost/unordered/detail/table.hpp

Line: 559

Expression !size_

This is teh first time i got this error so i don't think i can reprodce it easily.

(Reproduced on windows)
Release: 1.12.5
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-06**

**wedge009 wrote:**

> Any further clues on this one? I've had random crashes on occasion as well (not necessarily related to this one), but if I can't reproduce it I don't think to report it.

**Comment by Wedge009** [comment]
@gfgtdf seems to agree this can be closed.
