### ISSUE TITLE
X BadValue when maximising and then windowing a window in Ubuntu running in Docker (GNA #24137)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1524]
**[Original submission](https://gna.org/bugs/index.php?24137)** by aginor on 2015-12-04

This is copied from https://github.com/wesnoth/wesnoth/pull/555#issuecomment-161603713

I was going to raise this on gna, but my setup is pretty bizarre and I don't really know if you want to spend time trying to fix this edge case - my host machine is Ubuntu 12.04, but Wesnoth is running in a Ubuntu 14.04 Docker container with audio and video forwarded to the host.

I'm therefore just noting the issue here in case other people intermittently see it and you potentially want to talk to someone who can reliably reproduce.

When using this branch I'm able to reliably reproduce a near-identical error to https://gna.org/bugs/?2970 after starting up Wesnoth for the first time within a container - the steps to repro the crash only work once in a particular container.

The issue happens like this:

```

/work $ ./wesnoth/wesnoth-debug 

Battle for Wesnoth v1.13.1+dev (f709b8e-Clean)

Started on Thu Dec  3 01:31:53 2015



Automatically found a possible data directory at /work/wesnoth

process 357: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory

See the manual page for dbus-uuidgen to correct this issue.

libGL error: failed to open drm device: Permission denied

libGL error: failed to load driver: i965



Data directory:               /work/wesnoth

User configuration directory: /myhome/.config/wesnoth

User data directory:          /myhome/.local/share/wesnoth/1.13

Cache directory:              /myhome/.cache/wesnoth



Checking video mode: 1024x768x24...

Setting mode to 1024x768x24

Checking lua scripts... ok

[...PRESS MAXIMIZE...]

[...PRESS WINDOWED...]

X Error of failed request:  BadValue (integer parameter out of range for operation)

  Major opcode of failed request:  130 (MIT-SHM)

  Minor opcode of failed request:  3 (X_ShmPutImage)

  Value in failed request:  0x400

  Serial number of failed request:  3377

  Current serial number in output stream:  3378

```

And it dies. No backtrace is available when using GDB. Note that the libGL and dbus complaints are also new as of SDL2.

```





Sorry, I should've emphasised these lines:



[...PRESS MAXIMIZE...]

[...PRESS WINDOWED...]





```

(Reproduced on Ubuntu (Docker))
Release: dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-23**

**vultraz wrote:**

> Could we confirm if this is still an issue? Might have been fixed with my refactor of window handling.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-06**

**wedge009 wrote:**

> Close this if it's no longer an issue? (:

**Comment by Wedge009** [comment]
No further input.
