### ISSUE TITLE
Drawing and sheathing animations lack ellipses (GNA #24314)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1527]
**[Original submission](https://gna.org/bugs/index.php?24314)** by zookeeper on 2016-01-15

Unit ellipses are drawn during all other combat animations, but not during draw_weapon and sheath_weapon animations.

Sky Drake, Hurricane Drake and Merman Hunter are easy core testcases.

(Reproduced on win)
Release: 1.13.2+dev
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-03-07**

**zookeeper wrote:**

> Same also applies to healing, healed and poisoned animations. While not combat animations, I see no reason why ellipses should turn off during them.

**Comment by Wedge009** [comment]
Still seems to be present in 1.14.7. I noticed ellipses are not drawn during unit movements - I assume that's intentional and expected behaviour, it's only a problem with combat animations.

**Comment by jostephd** [comment]
> Unit ellipses are drawn during all other combat animations, but not during draw_weapon and sheath_weapon animations.

Fixed: d26c2a2290a8f4e06f296043c11076d7db51ab51

> Same also applies to healing, healed and poisoned animations. While not combat animations, I see no reason why ellipses should turn off during them.

@ln-zookeeper Ellipses and health/XP bars are enabled and disabled together. The animations do look better without bars IMO, so maybe for this case we could disable the bars but keep the ellipses.

https://github.com/wesnoth/wesnoth/blob/d26c2a2290a8f4e06f296043c11076d7db51ab51/src/units/udisplay.cpp#L799-L819

**Comment by Wedge009** [comment]
What's still outstanding here? I see ellipses are active now for drawing/sheathing animations. If it's a question about healing, etc, I wonder if that should be a separate issue? I just did a quick check and the ellipses and HP/XP bars are removed for healing for all units, not just the drakes/mermen mentioned here.

**Comment by Wedge009** [comment]
I saw this in the release notes for 1.14.11, so closing. If there's a minor part still outstanding please re-open.
