### ISSUE TITLE
image cache shared beteen different campaigns. (GNA #24365)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1529]
**[Original submission](https://gna.org/bugs/index.php?24365)** by gfgtdf on 2016-01-30

if 2 campaigns use the same image filename like in [item] image = "halo/a.png" [/item], but with differnt contents. the image of the first campaign will be used in the second campaign if the second campaign was started after the first campaign.

(Reproduced on windows 7)
Release: 1.13.3+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-01-30**

**shadowmaster wrote:**

> Sounds like bug #22866.

**Comment by Wedge009** [comment]
https://gna.org/bugs/?22866 is closed.
