### ISSUE TITLE
Water maps slow on 1.13.2+dev (GNA #24366)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1530]
**[Original submission](https://gna.org/bugs/index.php?24366)** by gfgtdf on 2016-01-30

wesnoth 1.13.2+dev perofrms bad on maps with a lot of water. Tested on last scenario of dead water campaign:

after some scrolling on the map, wesnoth reached 1GB or memory usage (on 1.12.5 it is 250mb) and just form looking (no scrolling, no other animations) at a mappart with a lot of water it has 25% CPU usage (that is one core on a quadcore cpu) (1.12.5 had 20% cpu usage in this case which isn't that much less i admit). When looking at a mappart without water is has 11% cpu usage (same on 1.12.5).

I don't know which of this is caused by the new water images, and which is caused by the SDL2 movement.

I really think his is annoying, specially the 1GB memory part, becasue this means that cannot play wesnoth on water maps anymore while using other meory heavy applications at the same time (like browser with many tabs)

(Reproduced on windows 7)
Release: 1.13.2+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-01-30**

**gfgtdf changed severity:** 4 - Important -> 3 - Normal

**gfgtdf wrote:**

> Decreasing priority after noticing that there is an o�tion to disable terrain animations.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-01**

**pentarctag0n wrote:**

> This also occurs when running on Mint.  Tested in the map editor on a 200x200 map entirely of Gray Deep Water.
> 
> 
> 
> Memory usage peaks at ~770MBs
> 
> At default zoom it keeps a single CPU at ~50%, 100% at minimum zoom.
> 
> 
> 
> The bigger issue, to me at least, is the input lag it can cause.  Moving the mouse around the grid would entirely freeze the game for a bit.
> 
> 
> 
> The animations themselves are also somewhat jerky even when nothing else is happening and even if there's only a few water tiles.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-04**

**zookeeper wrote:**

> Peaking at >700MB on a single-terrain 200x200 map like that sounds weird, since I only see <300MB in that case (even after scrolling around everywhere). You sure that wasn't affected by other maps you had open(ed)?
> 
> 
> 
> Anyway, the biggest problem is the transitions. I'll do some optimization there and see how much that helps. In the meantime, it wouldn't hurt to hear what your performance and memory use are like if you disable all the water transitions by removing these lines:
> 
> 
> 
> https://github.com/wesnoth/wesnoth/blob/master/data/core/terrain-graphics.cfg#L844-L858
> 
> 
> 
> For what it's worth, I'm still on SDL1.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-04**

**pentarctag0n wrote:**

> Also probably should have mentioned, I'm using SDL2.
> 
> 
> 
> What seems to have happened I think was I had opened an MP map before opening the editor; opening just the editor from the title screen tops out at ~310 MBs.
> 
> 
> 
> Commenting out those lines reduces memory usage by a couple tens of MBs, but that's about it.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-02-16**

**zookeeper changed status:** None -> In Progress

**zookeeper wrote:**

> [df9cecd5](s://github.com/wesnoth/wesnoth/commit/df9cecd558f834f390553a6a11c42ed4dd89374c) should decrease memory use back to acceptable levels, although it might slightly increase CPU use (which is something that needs to be mitigated in other ways).

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-03-29**

**zookeeper wrote:**

> I've now done pretty much all I can regarding optimization of the water-related terrain graphics rules, so further performance improvements will have to come from the engine side.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-29**

**aginor changed status:** In Progress -> None

**Comment by Vultraz** [comment]
Closing this since @jyrkive has significantly improved performance in 1.13.8+dev.
