### ISSUE TITLE
Animation image offsets not scaled when zooming (GNA #24487)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1536]
**[Original submission](https://gna.org/bugs/index.php?24487)** by defender1031 on 2016-03-02

Per-pixel offsets in animation frames are not scaled properly when zooming. For example, if either x or directional_x is set to 100, and the zoom level is at 50%, the image will still be offset by 100 pixels, rather than by 50. Note that this is not the case with a halo, which does seem to properly account for zoom.

The following test cases attempt to place a magical halo at the tip of a mage's wand to illustrate the issue. Both should be viewed at a zoom level other than 100%:

Failure test case:

```
[extra_anim]
  flag=animation_test
  [frame]
    image="units/human-magi/mage-attack-magic[1,2,1].png:[200,1500,200]"
  [/frame]
  
  [halo_frame]
    image="halo/mage-preparation-halo[1~7].png:100,halo/mage-halo[1~5].png:100,halo/mage-preparation-halo[7~1].png:100"
    x=15:200,11:1500,15:200
    y=-16:200,-21:1500,-16:200
  [/halo_frame]
[/extra_anim]
```

Expected behavior: Halo remains at the tip of the mage's wand even when viewing the map at an alternate zoom level

Actual behavior: Halo only lines up correctly when using the normal zoom level

Successful test case (using halo= rather than image=):

```
[extra_anim]
  flag=animation_test
  [frame]
    image="units/human-magi/mage-attack-magic[1,2,1].png:[200,1500,200]"
  [/frame]
  
  [halo_frame]
    halo="halo/mage-preparation-halo[1~7].png:100,halo/mage-halo[1~5].png:100,halo/mage-preparation-halo[7~1].png:100"
    halo_x=15:200,11:1500,15:200
    halo_y=-16:200,-21:1500,-16:200
  [/halo_frame]
[/extra_anim]
```

Why not to just use "halo=" if you need the positioning to be correct: halo is missing features, such as blend, alpha, autoflip, etc. which can't be easily replicated.

(Reproduced on Debian/Linux)
Release: 1.12
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by CelticMinstrel** [comment]
Is this present in 1.13.x?
