### ISSUE TITLE
Become has_weapon= key into a subtag of [filter] (GNA #24554)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1541]
**[Original submission](https://gna.org/bugs/index.php?24554)** by tekelili on 2016-04-06

I really would like do things like

[filter]

    [has_weapon]

        range=ranged

    [/has_weapon]

[/filter]

(Reproduced on any)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by CelticMinstrel** [comment]
Implemented in 0f072f34 as `[has_attack]`.
