### ISSUE TITLE
implement optional command-line history feature without GNU readline/history dependency (GNA #24569)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1542]
**[Original submission](https://gna.org/bugs/index.php?24569)** by gfgtdf on 2016-04-07

readline/history has limited support on windows:

1) It doesnt support utf8 filepaths on windows

2) The examples from their webpage make the programm crash if compiled with msvc.

3) It imposstible to extract the offical download files on windows becasue of invalid filename.

(1) is the main problem here becasue it means that we won't be able to write history to disk on some windows sytems. ( (2) and (3) are just to show that readline is clearly not meant as a platform independent libary)

In a plattform indenpendent software like wesnoth, libraries like readline should never be used.

Ideally we woudl just improve gui2's own histpry implementation and use that then too in the lua console.

(Reproduced on windows)
Release: 1.13+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-07**

**shadowmaster wrote:**

> Has anyone tried contacting upstream about these issues? (2) and (3) might just be oversights due to lack of testing and/or coders on that platform, not intentional. It wasn't too long ago that the same could be said about Wesnoth and OS X.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-08**

**gfgtdf wrote:**

> > Has anyone tried contacting upstream about these issues?
> 
> 
> 
> Not that i know of. The point problem here is that you cannot archieve good windows compaility by just using standard c libarires like fopen. you have to eigher use the wchar_t api or use another libarires that does this conversion for you.
> 
> 
> 
> 
> 
> >  It wasn't too long ago that the same could be said about Wesnoth and OS X.
> 
> 
> 
> You mean point (2) and (3) in paticular or is this jsut about generally bad macosx compability.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-14**

**involution changed status:** None -> Invalid

**involution wrote:**

> Some of the technical claims made in this bug report are incorrect.
> 
> 
> 
> > readline/history has limited support on windows:
> 
> > 
> 
> > 1) It doesnt support utf8 filepaths on windows
> 
> > 2) The examples from their webpage make the programm crash if compiled with msvc.
> 
> > 3) It imposstible to extract the offical download files on windows becasue of invalid filename. 
> 
> 
> 
> GNU readline is one of the most well-known and widely used cross-platform C libraries provided by GNU. Bindings have been written for python, ruby, lua, and many other languages, precisely because it is a high-quality, cross-platform library.
> 
> 
> 
> If "doesn't support utf8 filepaths on windows" is disqualifying for a C library, then also SDL and the SDL extension libraries are disqualified and we should remove those dependencies also, I suppose. Are you sure that there is no extra mechanism to use user-provided filesystem functions or a fallback to load command history data directly? There is no evidence that you checked.
> 
> 
> 
> Issue (2) sounds like a problem with your system or the way you are compiling the code, and not problems with the library, neither does this have any obvious connection to wesnoth. Similarly, (3) sounds like something wrong with your method, and again, has nothing to do with wesnoth.
> 
> 
> 
> > In a plattform indenpendent software like wesnoth, libraries like readline should never be used.
> 
> 
> 
> Again, this is frankly ridiculous. Even technologies like lua have an optional dependency on readline, in order to support their REPL. If readline is not platform independent software, you may be the first developer in the world to realize the problem.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-14**

**gfgtdf changed status:** Invalid -> None

**gfgtdf wrote:**

> > then also SDL and the SDL extension libraries are disqualified and we should remove those dependencies also, 
> 
> 
> 
> This is wrong, SDL usually does support utf8 names on windows becasue it uses the winapi functions on windows internally (OpenFile etc.) the reason why we had to work around things with our custom rw ops are bugs in sdl_mixer which are likeley to be fixed in sdl2. And even if it didn't supportutf8 filesnems ina direct way, it'd still suport reading utf8 filenames via the SDL_RWops
> 
> 
> 
> > Are you sure that there is no extra mechanism to use user-provided filesystem functions or a fallback to load command history data directly? There is no evidence that you checked.
> 
> 
> 
> Yes i did check (on this page https://cnswww.cns.cwru.edu/php/chet/readline/history.html#SEC9)
> 
> 
> 
> > Issue (2) sounds like a problem with your system or the way you are compiling the code, and not problems with the library, neither does this have any obvious connection to wesnoth. Similarly,
> 
> 
> 
> When you see at the examples on how to use the history libary (for example on the page i liked above) its quite clear that they won't work if compiled with msvc, in this case this is becasue it used free() to free a piece of emeprty that was allocated by an external libary (readline/history).
> 
> 
> 
> the relation on wesnoth here is again that readline/history is not a plattforn independent libarry and thus wesnoth shouldn't rely it to implement a feature that should be plattform independent.
> 
> 
> 
> > (3) sounds like something wrong with your method, and again, has nothing to do with wesnoth. 
> 
> 
> 
> I think i explained quite clearly what the issue was, some of the the filenames of the files in the .tar.gz file downloaded from the readline git are invalid on windows filesystems.
> 
> 
> 
> > Bindings have been written for python, ruby, lua, and many other languages, precisely because it is a high-quality, cross-platform library. 
> 
> 
> 
> > Again, this is frankly ridiculous. Even technologies like lua have an optional dependency on readline, in order to support their REPL
> 
> 
> 
> That there are binding to readline doesn't imply that readline itself is a cross-plattform libary, lua defines LUA_USE_READLINE only on linux and macosx. Python also doesn't ship with redline on windows and instead had a python-written readline implementation (pyreadline) instead which it recomends to use on windows.
> 
> Ruby has similar issues and there is also again a readline implementation in ruby (https://github.com/ConnorAtherton/rb-readline) to adress this.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-14**

**gfgtdf wrote:**

> correction of the link: https://cnswww.cns.cwru.edu/php/chet/readline/history.html

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-14**

**involution changed title:** remove readline/history dependency -> implement optional command-line history feature without GNU readline/history dependency

**involution changed category:** Bug -> Feature Request

**involution wrote:**

> The GnuWin32 project has been shipping readline / history, with msvc compatibility files, since 2005 according to their news archive: http://gnuwin32.sourceforge.net/oldnews.html
> 
> 
> 
> In 2008 they fixed a bug where some msvc files weren't generated correctly. So it seems clear that msvc is actively supported.
> 
> 
> 
> Regardless of what you think you understand from the documentation, I suggest that you message them with the problem you are having and see what they suggest. As shadowm suggested, try contacting upstream before you jump to conclusions like
> 
> 
> 
> > readline is clearly not meant as a platform independent libar
> 
> 
> 
> and 
> 
> 
> 
> > In a plattform indenpendent software like wesnoth, libraries like readline should never be used. 
> 
> 
> 
> Again, if readline is "not platform independent", then you seem to know something that no one else does, and certainly no one at the GnuWin32 project.
> 
> 
> 
> Finally, let me point out that readline/history is not in fact a dependency, it is an optional dependency for an optional feature. One which I created. I did it this way for several reasons. One of which was to save time rather than reinvent the wheel, which it certainly did. Second, I was predisposed to use GNU libraries since wesnoth is GPL anyways, and using other GPL libraries helps to promote free software.
> 
> 
> 
> If you want to create an alternate pathway to implement command line history, and test it and maintain it indefinitely, by all means, go ahead, as I originally suggested. In my original email some years ago I wrote "there is plenty of space between the #else and #endif".
> 
> 
> 
> I do not appreciate your classifying an optional dependency for an optional feature that I made as a bug, or the unsupported claims that the library is not cross-platform, and that it was a mistake for me to have picked it. I did not test the feature on windows because I do not use windows, but I did even test it in mingw / wine, and it worked there. Most wesnoth developers historically do not test platforms besides their own. Anyways I would be shocked if the minor issues you raise regarding readline, if they even matter for wesnoth, cannot be easily worked around.
> 
> 
> 
> I have reclassified your report as a feature request, and rewritten the title.
> 
> 
> 
> Please do not "remove readline/history dependency" unless you actually reimplement and test the features that are supported by it, which I use myself when I develop addons for the game, having taken the time to implement the feature myself to much fanfare from the other developers. Otherwise I will consider your patch to be a bug in return. A compilation option like this does not harm you at all, so please try to be reasonable.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-14**

**gfgtdf wrote:**

> hmm it seem like this bugtracker cannot handle the www inside that link. You can see the correct link in the mail archieve about this that post: https://www.mail-archive.com/wesnoth-bugs@gna.org/msg25860.html
> 
> 
> 
> > In 2008 they fixed a bug where some msvc files weren't generated correctly. So it seems clear that msvc is actively supported. 
> 
> 
> 
> Well it actuall looks that this project had no changes since 2010.
> 
> 
> 
> > try contacting upstream before you jump to conclusions like 
> 
> 
> 
> These bugs cannot be fixed by GnuWin32, at least not in a way that would allow code that would work on both linux and windows without ifdefs. In order to fix the crash, readline must change its interface and export its 'free' function like SDL does with SDL_free. This is 4 lines of code on the readline side. But readline doesn't do it. At least i didn't find anything in the readlines header files or in the documentation. Similary the best fix for the utf8 issue is to have custom read/write objects like sdl does with SDL_RWops.
> 
> 
> 
> I did file a bugreport on readline. But i don't think that this can fix this issue, even if it gets fixed by readline the downloadable version on gnuwin32 will mostlikeley not be updated, note that their latest version is version 5.0 which is from 2004 while the latest readline version is 6.3 from 2014.
> 
> 
> 
> > Again, if readline is "not platform independent", then you seem to know something that no one else does, and certainly no one at the GnuWin32 project.
> 
> 
> 
> Well, like i said before, many known programms like ruby or python ship with readline only on linux and do rather reimplement it in their own language than to build the original readline on windows. So im sureley not the first one who noticed the lack of support for windows in readline.
> 
> 
> 
> > Finally, let me point out that readline/history is not in fact a dependency, it is an optional dependency for an optional feature. One which I created. I did it this way for several reasons. One of which was to save time rather than reinvent the wheel, which it certainly did. Second, I was predisposed to use GNU libraries since wesnoth is GPL anyways, and using other GPL libraries helps to promote free software.
> 
> > If you want to create an alternate pathway to implement command line history, and test it and maintain it indefinitely, by all means, go ahead, as I originally suggested. In my original email some years ago I wrote "there is plenty of space between the #else and #endif".
> 
> > I do not appreciate your classifying an optional dependency for an optional feature that I made as a bug
> 
> 
> 
> We have a feature, it doesn't work with msvc at all, and it also works not perfectly when compiled with mingw. I'd call that a bug. With your argumentation you could declare any feature that doesnt work on all plattforms as an optional feautre and mark related bugreports as feature request.  
> 
> 
> 
> 
> 
> > but I did even test it in mingw / wine, and it worked there.
> 
> 
> 
> This is because the crash issue only happen with msvc, and the utf8 issue only when your username contains non-ascii chracters.
> 
> 
> 
> > Most wesnoth developers historically do not test platforms besides their own. Anyways I would be shocked if the minor issues you raise regarding readline, if they even matter for wesnoth, cannot be easily worked around.
> 
> 
> 
> Well, when i try to compile with readline for example with the files provided by gnuwin i get crashes whenever i try histoy expansion (for the reason is explained in my last post). I wouldn't call that a minor. Do you have an idea how to work around it?
> 
> 
> 
> > unless you actually reimplement and test the features that are supported by it, which I use myself when I develop addons for the game
> 
> 
> 
> You mean the substutution syntax like in "!!:s/aa1/aa2/" ?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-15**

**involution wrote:**

> > I did file a bugreport on readline.
> 
> 
> 
> Can you please post a link to your bugreport in their bug tracker? I could search for it, but there are several possible bug trackers you could have used, and I can't know for sure which person submitted which report.
> 
> 
> 
> > Well it actuall looks that this project had no changes since 2010. 
> 
> 
> 
> GNU Readline is a 27 year old library, probably it was written before you were born. If it was not changed in the last five years, that is more likely to indicate that it is extremely stable and in maintenance mode, than that it is inherently fundamentally broken as you claim.
> 
> 
> 
> > These bugs cannot be fixed by GnuWin32, at least not in a way that would allow code that would work on both linux and windows without ifdefs. In order to fix the crash, readline must change its interface and export its 'free' function like SDL does with SDL_free.
> 
> 
> 
> You keep repeating this technical argument about malloc / free under different compilers, which we both discussed years ago when this feature was originally added.
> 
> 
> 
> I know that you think you understand this very well, and you doubt for whatever reason that there is a workaround, and don't want to do the work yourself of looking into it.
> 
> 
> 
> But if you look at the big picture, your argument here is that
> 
> 
> 
> (1) Readline is inherently flawed and unusable on msvc, because of design flaws in the library.
> 
> (2) Rather than state this upfront in their documentation, you think that the developers have indicated this to you by posting an example code snippet which you are simply sure cannot work in msvc. Regardless of other options / configuration which might not be visible in the simple code snippet, it is just an example after all.
> 
> (3) It's not clear what you imagine is going on in the mind of the readline developers. Do you think that, they think it works on msvc, but they are just wrong and have been wrong for 20+ years, with no one to point out the problem?
> 
> (4) If readline does not work on msvc, and they are aware of the problem, why is this not stated up front in the docs "msvc is not supported"? Do you imagine that they are aware, but for whatever reason they choose to obscure this "fact" and leave it to the user to discover on their own? Why would they do that?
> 
> (5) These rewrites of the readline interface don't prove anything like what you are saying. People have rewritten readline many times, for instance in the BSD editline library, and their motivation for this was to free themselves of the GNU GPL. You claim that really they did this because there are known major problems that make readline unusable on windows, but you don't actually link to anyone authoritative saying that. You claim "Python also doesn't ship with redline on windows and instead had a python-written readline implementation (pyreadline) instead which it recomends to use on windows. " but you don't link to an authoritative person saying this. Even if your claim is true, there could be any number of reasons that they would recommend to use something different on windows. Maybe they make something that integrates with windows shell more naturally and doesn't behave like bash -- this is just an example I'm making up. The point is that what you write here doesn't support at all your idea that readline is fundamentally incompatible with msvc. You are just jumping to conclusions without doing a real investigation.
> 
> 
> 
> If readline doesn't work on msvc, then YOU should be able to point to a page with the original developers saying something directly to that effect. "We do not support msvc for the following reasons, and the following features are unusable there: ...". If you can't do that, then YOU should give some kind of explanation for why they don't say that. Either that they just don't know and didn't figure it out in 20+ years (which basically means that they are idiots), or that they do know but choose to pretend to be cross-platform anyways, which means that you think they have some motivation to mislead their users.
> 
> 
> 
> Either way, obviously it demands some kind of explanation. And this should be completely obvious to you. It's amazing that I have to state something like this explicitly, but that just speaks to the direction in which you've steered this argument.
> 
> 
> 
> While you are at it, you might want to update the wikipedia page for GNU readine, since it claims that it is a cross-platform library and obviously you have figured out that that's not true. You could see if the wikipedia editors consider your change to be vandalism and revert it or not. My expectation is that they would. https://en.wikipedia.org/wiki/GNU_Readline
> 
> 
> 
> > We have a feature, it doesn't work with msvc at all, and it also works not perfectly when compiled with mingw. I'd call that a bug. With your argumentation you could declare any feature that doesnt work on all plattforms as an optional feautre and mark related bugreports as feature request.
> 
> >
> 
> > Well, when i try to compile with readline for example with the files provided by gnuwin i get crashes whenever i try histoy expansion (for the reason is explained in my last post). I wouldn't call that a minor. Do you have an idea how to work around it? 
> 
> 
> 
> I'm getting increasingly tired of your argumentation. This is the same old intransigent crap that just gets so very boring... You don't like the way something works, you think it should be done differently.
> 
> You show up with these ridiculous claims that something is poor quality / not cross-platform / whatever other value judgment. When asked to support your claims, you try to turn around and say the burden of proof is on me, and not you. You basically just repeat this one problem you had with some example code ad nauseum, with blinders on in regards to the big picture. There's no honest effort to understand the issue, there's no real effort to quality software engineering. You just keep repeating tired old claims from a few years ago, make the argument entirely political, and just be as lazy as possible.
> 
> 
> 
> I think based on the exchange we've had, it's pretty clear that you don't really know what you are talking about and aren't interested to learn, so I doubt that we will be able to resolve this amicably. I'm not really happy either about having my time wasted.
> 
> 
> 
> I don't know why your little code example from a few years ago segfaults when you compile it, and frankly, it's not my job to figure it out. If you can't figure it out yourself, then ask someone else for help. Please have the decency to blame yourself before the tools, rather than show up with trumped-up claims that everything else is inescapably defective, and that the GNU developers don't know what they are doing or prefer to conceal problems in their code, when it's obvious to everyone else that it's much more likely that you are doing it wrong.
> 
> 
> 
> The first rule of development is, do no harm. If you can't figure out for yourself what's a useful feature and what's a bug, then ask others for guidance. If it still doesn't work out, then please don't make any more commits.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-15**

**gfgtdf wrote:**

> > I did file a bugreport on readline. 
> 
> 
> 
> http://lists.gnu.org/archive/html/bug-readline/2016-04/msg00025.html
> 
> 
> 
> > GNU Readline is a 27 year old library, probably it was written before you were born. If it was not changed in the last five years, that is more likely to indicate that it is extremely stable and in maintenance mode, than that it is inherently fundamentally broken as you claim.
> 
> 
> 
> My comment was obviously about the gnuwin32 project (see announcements in http://gnuwin32.sourceforge.net/), not about the readline project, as is said in my previous post, the latest readline version is from 2014.
> 
> 
> 
> The result from the bugreport was that the crash issue was actually fixed in readline 6 which is from 2008, unfortunateley still too new for the gnuwin32 project. They told me however about a readline5 workaround using a function that is neigher in the headers nor in the docuementation (see the bugreport answers for details).
> 
> 
> 
> > These rewrites of the readline interface don't prove anything like what you are saying
> 
> 
> 
> The motivation sction of the ruby readline poject i linked below begins with the words "First, building the GNU readline library on MS Windows with Visual C++ is almost impossible".
> 
> 
> 
> > I don't know why your little code example from a few years ago segfaults when you compile it and frankly, it's not my job to figure it out
> 
> 
> 
> First, it's not just that little example, it's every code that used readline versions lower then 5 including the code in wesnoth. Second, i explained multiple times already why it crashed.
> 
> 
> 
> > When asked to support your claims, you try to turn around and say the burden of proof is on me
> 
> 
> 
> All my claims 1-3 are eigher trivial to understand or i explained them enough and also why 1 and 3 cannot easily worked around. If you say they can be easily worked around you should show how to do it.

**Comment by cooljeanius** [comment]
I was just wishing for readline-like functionality for CommandMode myself today; is it really necessary to reimplement it entirely these days, or has upstream readline improved enough to the point where we can just use it as-is?

**Comment by AI0867** [comment]
Looks like readline is at version 8.1 nowadays, which is 2 major versions higher than an 2017. However, gnuwin32 hasn't been updated in over a decade, so the windows-related issues probably remain, unless those 2 major versions have included a windows compatibility effort.

I haven't looked at libedit, replxx or linenoise, but maybe one of them fits our needs?

**Comment by CelticMinstrel** [comment]
I don't think it's correct for this to be closed by #5538? My understanding is that this is more about the history functionality missing on Windows than it is about the in-game command console not having history.
