### ISSUE TITLE
Cocoa notifications not showing as supported (GNA #24578)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1543]
**[Original submission](https://gna.org/bugs/index.php?24578)** by ancestral on 2016-04-10

In the main menu, when clicking on the 'i' which shows version numbers, under the Features tab, Cocoa notifications show as not supported even though it is in fact working.

```

ShikadiLord: ancestral: I think I know why Cocoa notifications are considered unavailable by the version UI.

ShikadiLord: The file that carries the required information, src/build_info.cpp, checks whether HAVE_NS_USER_NOTIFICATION has been defined. It most certainly has not, there.

ShikadiLord: The reason is that when it's defined, it is defined _only_ in the context of src/desktop/apple_notification.mm.

ShikadiLord: Either it used to be defined everywhere, or I misinterpreted something when I wrote that bit in build_info.cpp.

ShikadiLord: Feel free to fix it however you see fit.

```

(Reproduced on OS X)
Release: 1.13.x
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by Wedge009** [comment]
This is Cocoa, so definitely seems OSX-specific to me.

**Comment by CelticMinstrel** [comment]
Bleh, clearly I should've been a little more carefuly before deleting the "os:os x" label...

I had a WIP related to fixing this somewhere, but it's pretty difficult for me to test when I'm on 10.7 and Cocoa Notifications were introduced on 10.8.

**Comment by CelticMinstrel** [comment]
Since I'm not sure I'll get a chance to work on this again, here's my WIP patch to address it:

[osx_notifications.patch](https://github.com/wesnoth/wesnoth/files/1017308/osx_notifications.patch.txt)

It needs to be tested on OSX 10.7 in particular (unless we plan to drop support for it, but in that case I wonder if we even need Growl support?), as well as 10.8+.

**Comment by ancestral** [comment]
I applied the patch and it appears to have solved the issue. Thanks CelticMinstrel!

I have merged the changes into master.
