### ISSUE TITLE
game state becomes corrupted when changing control of players (GNA #24591)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1546]
**[Original submission](https://gna.org/bugs/index.php?24591)** by iceiceice on 2016-04-14

When playing a default (no custom add-ons) ladder match in the stable 1.12 multiplayer server, the game became corrupted after a player disconnected and control of his side was changed several times when he reconnected.

The order was, first to idle, then to player when he returns, then to observer when he disconnects again, then to host, then droid after the game is over.

(I droided both sides after he did not return and effectively conceded.)

Something very strange happened after droiding.

Both sides got the leader of the *other* side seemingly on their recall lists, or perhaps just at the starting position of the map? The game was orcish vs loyalists. Sometime after droiding, both sides got an additional leader of the other type, so loyalists had a troll rock lobber, and orcs had a loyalist pikeman unit.

This was a vanilla, default game, there were no custom addons or eras. It was initially started with the "Sandbox" map picker mod, but that does not affect the recall lists, nor do I believe that it is meaningfully connected to the bug. If you agree about that, then it was effectively just a default game on the mainline "Cave of the Basilisks" map.

Replay is attached.

(Reproduced on Ubuntu 15.10)
Release: 1.12.5
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-04-14**

**iceiceice added attachment:** [2p_-_Caves_of_the_Basilisk_replay_BUG_when_controllers_are_changed.gz](http://gna.org/bugs/download.php?file_id=27111)

**Comment by CelticMinstrel** [comment]
Is this still present in 1.13.x?
