### ISSUE TITLE
Resizing doesn't work (GNA #24604)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1548]
**[Original submission](https://gna.org/bugs/index.php?24604)** by pak on 2016-04-23

I'm using the stable Mac download. When I resize the window, the contents are plain white for a few seconds, and then it shows the interface, but with the cursor not aligning with whatever is highlighted/selected.

(Reproduced on OS X)
Release: 1.12.5
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Wedge009** [comment]
Haven't seen this with Windows or Linux, and pak is reporting this is on OSX.

**Comment by CelticMinstrel** [comment]
Looks like it originally was labelled Mac, but in a format the transfer didn't recognize.

I don't think I remember seeing this when I last ran Wesnoth on OSX, so I suspect it's probably fixed, but we should probably get @mattsc or @ancestral to verify it.

**Comment by Vultraz** [comment]
@ancestral confirms fixed.

**Comment by ancestral** [comment]
Issue appears resolved with some combination of newer macOS software, newer libraries, or more code modernized.
