### ISSUE TITLE
Units moving after in game help exit (GNA #24644)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1551]
**[Original submission](https://gna.org/bugs/index.php?24644)** by ravana on 2016-05-06

Selecting unit, clicking on ability name on sidebar, clicking any unit in the appearing list, and using esc(or exit button), makes the selected unit move somewhere.

(Reproduced on All)
Release: 1.13.4
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-05-06**

**zookeeper wrote:**

> It's enough to just select a unit, open the help by clicking on a trait/ability/race/type/alignment in the sidebar, and then close the help (whether via the button or esc).

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-06-01**

**wedge009 wrote:**

> It took me a while to replicate this, but I can confirm this as well. Without knowing all the technical details, I have a guess that this is something to do with the interaction between a gui2 window and registering/processing mouse position/clicks as the unit moves in the direction of where the mouse was upon closing the help window.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-20**

**wedge009 changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-05-01**

**wedge009 wrote:**

> PR #1002 seems to resolve this - can mark as fixed when it's merged.

**wedge009 changed OS:** windows -> All

**wedge009 changed status:** Confirmed -> In Progress

**Comment by Wedge009** [comment]
Resolved with PR #1002
