### ISSUE TITLE
Hovering on [option] causes a strange border to appear (GNA #24667)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1553]
**[Original submission](https://gna.org/bugs/index.php?24667)** by pentarctag0n on 2016-05-13

Hovering over an image causes a change in its transparency, and for a border to appear:

http://cubeupload.com/im/RRZkEU.png

(Reproduced on Linux Mint)
Release: 1.13.4+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-05-13**

**pentarctag0n wrote:**

> *Hovering over an >option<

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-05-16**

**vultraz wrote:**

> Temporarily redisabled blurring pending further debugging. Some of this might be fixed in the renderpath-redo branch.
> 
> 
> 
> https://github.com/wesnoth/wesnoth/commit/f5fbb3872a4d58e85029ad703ad733f93b652947

**vultraz changed status:** None -> Postponed

**Comment by Pentarctagon** [comment]
@Vultraz was this fixed?

**Comment by Vultraz** [comment]
I don't remember. I *think* I can recall what the issue was, but without the screenshot I can't be sure.

**Comment by Pentarctagon** [comment]
Well, I can't seem to reproduce it anymore, so closing.
