### ISSUE TITLE
Timer settings not remembered on Configure Game screen (GNA #24700)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1556]
**[Original submission](https://gna.org/bugs/index.php?24700)** by sigurdfdragon on 2016-05-25

Every other setting on the Configure Game screen will remember what the user selected between sessions, except for the four timer settings of Init. limit, Turn bonus, Reservoir, & Action bonus.

(Reproduced on Win 7 x64)
Release: 1.12, 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-06-01**

**sigurdfdragon wrote:**

> I took a look at doing a pr for this and found that this behavior was originally put in place in 2006 by https://github.com/wesnoth/wesnoth/commit/adb4f15cc14cf30158a732577abd2230b63d2ce5 and it also provided a key to add to preferences (remember_timer_settings=yes) if someone wants their timer settings to have memory.
> 
> 
> 
> I guess there must have been reasons, though ever since I've started playing mp vs computer with a timer (maybe two years ago?), I've found the reset annoying.
> 
> 
> 
> I'm at least glad that I found there's a key to enable the behavior.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-06-02**

**gfgtdf wrote:**

> > I guess there must have been reasons, though ever since I've started playing mp vs computer with a timer (maybe two years ago?), I've found the reset annoying. 
> 
> 
> 
> 
> 
> Im surpised to hear this, do you think it'd also make sense to allow timers in sp?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-06-02**

**sigurdfdragon wrote:**

> I've been using the ladder timer settings with 1v1 mp maps, as part of getting better at playing Wesnoth.
> 
> 
> 
> I think a lot of players would get into trouble enabling a timer on SP, especially if they try and use the ladder settings of 300/300/300/0.
> 
> 
> 
> SP campaigns scenarios can be quite varied, so what would be a good timer setting? One would have to be provided if the feature was easily available for all upon game installation.
> 
> 
> 
> Furthermore, due to scenario variety, it seems like you'd need to allow the player to adjust the timer between scenarios. I think such complexity is best kept away from players.
> 
> 
> 
> If players want to try the timer in sp, they can currently access it by launching wesnoth in debug mode which enables the sp campaigns to appear in the mp framework.
> 
> 
> 
> TL,DR - I think allowing a timer for all in sp would allow a good number of players to cause themselves problems.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-06-02**

**sigurdfdragon wrote:**

> As far as the reported bug, since Sapient made the original commit and he's been around lately, we should hear from him about this.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-21**

**sigurdfdragon wrote:**

> I think the best way to resolve the issue in the OP would be to give the timer settings memory like other Game Settings entries and have a 'Defaults' button for the timer group to reset it, like there is for Custom Options under GUI2.

**Comment by Wedge009** [comment]
Hmm, I just had a look at the commit that @sigurdfdragon mentioned and it's odd that the timer settings explicitly forgotten by default - and that `remember_timer_settings` is used nowhere else, as best as I can tell.

The relevant code is now residing in `preferences/game.cpp`:
https://github.com/wesnoth/wesnoth/blob/b593e82cd268a380a8f14a1bb31debf1f1325477/src/preferences/game.cpp#L85-L89

Is it worth making the `remember_timer_settings` a toggle via Advanced Preferences?

**Comment by jostephd** [comment]
> Is it worth making the `remember_timer_settings` a toggle via Advanced Preferences?

I don't think so. Preferences are best avoided when possible. In this case, I think the solution @sigurdfdragon outlined in https://github.com/wesnoth/wesnoth/issues/1556#issuecomment-299843914 would be satisfactory, and it doesn't require a preference. Is there any reason why that solution _wouldn't_ be desirable behavior?

Unrelated: Referencing #4448.

**Comment by Wedge009** [comment]
I was only asking because I wondered why the `remember_timer_settings` preference (which isn't currently used or generated) was explicitly put there. I expect just removing this erase block should allow the settings to be remembered again.

**Comment by jostephd** [comment]
Probably because someone wanted to keep the behavior unchanged by default but add an outlet to those who wanted to have the behavior changed anyway. Undocumented hidden preferences are just not very discoverable :(

**Comment by Wedge009** [comment]
Indeed!

Turns out this 'feature' was introduced by @sapientN3T in adb4f15c/69fdee80 (in 2006!). I'm not sure if he's still around to comment on why this was introduced or even remembers this. Either way, I reckon we could disable this and introduce a manual default as you pointed to above.

**Comment by sapientN3T** [comment]
Hi, yeah there was a motivation behind it to nudge players towards using the default settings, while prroviding a hidden toggle for those who complained.

But more than that there was very limited space on that screen at that time, so this was a compromise to avoid squeezing in a Reset Timer Defaults button.

Ideally it should be handled via a restore defaults button. And the hidden setting can go away.

**Comment by Wedge009** [comment]
Cool, thanks for the quick response and confirming the approach discussed here.
