### ISSUE TITLE
Alignment not being translated in unit sidebar (GNA #24887)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1562]
**[Original submission](https://gna.org/bugs/index.php?24887)** by sigurdfdragon on 2016-07-28

When playing under another language, the unit sidebar alignment translation is not working, and displays the English name instead.

Doing a mouse-over the ToD graphic does show translations though.

Compare with 1.12.6 where it is working.

I checked in both German and Russian.

See attached pic showing Russian.

(Reproduced on Win 7 x64)
Release: 1.13.4+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-07-28**

**sigurdfdragon added attachment:** [alignment not translated.png](http://gna.org/bugs/download.php?file_id=28035)

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-07-30**

**lipk wrote:**

> I'm not familiar enough with the inner workings of the translation system to draw a definitive conclusion but I suspect that this bug relates to the N_ macro being used in header files. Those instances probably won't be collected as translatable strings. Actually, it would make sense not to collect them.
> 
> 
> 
> Indeed, this bug only affects male units, while female variants of the alignment string, which are placed in unit/types.cpp, are translated correctly.
> 
> 
> 
> Another example of N_ in a header file is the RANDOM_FACTION_MODE enum in mp_game_settings.hpp, and those strings aren't translated either.

**lipk changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-07-30**

**wedge009 wrote:**

> I had a look through the history (back when unit/types.* was still unit_types.*, and Chris Beck switched unit_type::alignment from the standard enum used in 1.12.x to the MAKE_ENUM macro on 26th May 2014 (684d1c35c64e9317e331f3860aeb0fb98088ac28). I don't know what this macro does or what its advantages might be.
> 
> 
> 
> On 27th December 2014 (2aca986bcb79b64a0befcc9266b96b9396328a79) Chris Beck moved the female MAKE_ENUM from the header to the cpp file. I don't know why the alignment for female units is translated okay but the male/standard units aren't, but this seems to be where the distinction happens. The N_ macro does appear to disable translations (gettext_noop).
> 
> 
> 
> I wasn't able to test those or other revisions to try to find out how long this issue has been happening in 1.13.x, but I suspect those two would be good places to start. 2014 does feel like quite a long time ago, though. According to the old news posts, 1.12.0 was released in November 2014 and 1.13.0 wasn't released until April 2015.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-11**

**gfgtdf wrote:**

> The N_ means that the gettext parser should add these (for the po files) but theat the actual c++ code doesnt translate them yet becasue they are translated later, here in https://github.com/wesnoth/wesnoth/blob/1.13.5/src/units/types.cpp#L843

**Comment by CelticMinstrel** [comment]
Is this still an issue?

**Comment by Vultraz** [comment]
Confirmed fixed by @hrubymar10.
