### ISSUE TITLE
Mage of Light illuminates halo issue (GNA #24914)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1563]
**[Original submission](https://gna.org/bugs/index.php?24914)** by inky on 2016-08-05

Moving one mage of light past another will cause graphical issues (flashing) with the illuminates halo.

(Reproduced on windows 10)
Release: 1.13.5
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-05**

**wedge009 wrote:**

> I didn't notice any flashing, but there are some graphical interactions between the translucent haloes. So I suppose this is confirmed for 1.13.x, but it's fine on 1.12.x.
> 
> 
> 
> I don't know if this is related to, or a side-effect of, resolving bug #23712.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-11**

**wedge009 wrote:**

> A good place to test this is the opening scenario of Delfador's Memoirs, where a Mages of Light crosses over another.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-20**

**wedge009 wrote:**

> Reconfirming on 1.13.7+dev.

**wedge009 changed status:** None -> Confirmed

**Comment by Wedge009** [comment]
Linking to related #1350. They are different issues, but possibly related.

**Comment by Vultraz** [comment]
Fixed on accelerated_rendering

**Comment by Wedge009** [comment]
> Fixed on accelerated_rendering

Great! I'll try to remember to check it out when I return home by the
weekend.

**Comment by Wedge009** [comment]
Confirm this is resolved in AR branch. However, @Vultraz, I have severe rendering issues in other areas (like overlapping text and images and crashes on using the command console). Are you aware of these? Do they need to be reported separately?

**Comment by Wedge009** [comment]
@Vultraz One example:
![ar](https://user-images.githubusercontent.com/13679322/27759049-f0b61c56-5e67-11e7-86bd-558db13eed45.jpg)

**Comment by CelticMinstrel** [comment]
Should this be reopened?

**Comment by Wedge009** [comment]
Replaying the opening story for Delfador's Memoirs seems okay to me (Mages of Light crossing paths).  What's the reason for re-opening this?

**Comment by jyrkive** [comment]
Ah, you're right. Sorry for reopening this one. I went through celmin's "should this be reopened?" comments for issues which had been tagged "fixed in AR branch", and after confirming that the first of them hadn't been fixed in any other way, proceeded to reopen them all. I missed that this one had been fixed separately (heck, *I* am the one who fixed it).

Closing again.

**Comment by Wedge009** [comment]
No worries, I'm just not sure what's going on with the AR branch.

> (heck, _I_ am the one who fixed it).

Heh, that's funny.
