### ISSUE TITLE
hotkey issue with 'b' and 'volume up/f9' (GNA #24918)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1564]
**[Original submission](https://gna.org/bugs/index.php?24918)** by inky on 2016-08-05

When I assign an action to the 'b' hotkey, then pressing the volume up/f9 key will also perform that action.

I'm not sure if it's an issue on my end, however it works fine for me in 1.12.

(Reproduced on windows 10)
Release: 1.13.5
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-05**

**wedge009 wrote:**

> I wasn't able to replicate this issue. What keyboard layout are you using? The SDL2 key scanning should adapt to different layouts but best to minimise variables.
> 
> 
> 
> Also, what's the contents of the hot-key section of your preferences file?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-05**

**inky wrote:**

> I'm using the QWERTY keyboard layout.
> 
> I guess this is the relevant section of the preferences file:
> 
> [hotkey]
> 
> 	alt=no
> 
> 	cmd=no
> 
> 	command="bestenemymoves"
> 
> 	ctrl=no
> 
> 	disabled=no
> 
> 	key="B"
> 
> 	shift=no
> 
> [/hotkey]
> 
> 
> 
> It happens with other actions too, e.g. if I add the 'b' shortcut to recruit, then pressing the volume up key will open the recruit window.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-06**

**wedge009 wrote:**

> I'm sorry, but I still can't replicate this issue. Is this the only hot-key entry in your preferences file?
> 
> 
> 
> Given that it happens with other functions to which 'b' is assigned, I wonder if it's specific to your keyboard. I don't have a dedicated volume up on my keyboard, although I have the same function using a Function+F11 combination on my specific model.
> 
> 
> 
> If possible, can you confirm if the same issue happens with a different keyboard? Or even the same keyboard on a different computer?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-06**

**inky wrote:**

> I should've mentioned it's a DELL laptop keyboard, with multimedia keys like volume control, play/pause etc. across the top (and you hold Fn to get the Function keys). After some experimentation it seems to happen with other multimedia keys as well (volume down/f8 activates the 'c' hotkey and Next/f12 activates 'p') so it seems to be an issue specific to this type of laptop keyboard.
> 
> 
> 
> Unfortunately I don't have another computer to test with. This hotkey interference doesn't seem to happen with other programs including Wesnoth 1.12 though.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-06**

**wedge009 wrote:**

> It sounds as though this might be related to your specific hardware, then. I'm not sure what we can do to test/debug this issue in this case.
> 
> 
> 
> 1.12 uses SDL1 while 1.13 uses SDL2. So the different hot-key handling is why you don't observe this behaviour in 1.12.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-06**

**inky wrote:**

> It's no problem, I'll just avoid assigning the b hotkey. I guess this report can be closed then.
> 
> 
> 
> Anyway, thank you for taking the time to look into it.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-06**

**wedge009 wrote:**

> I think we'll leave it open as a record of the issue - on the off chance someone else has the same problem.
> 
> 
> 
> Thanks for taking the time to report!

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-09**

**aginor wrote:**

> Which model of Dell laptop is it? It sounds like it's a scancode issue but we may be able to filter on the function key if we can figure out the appropriate things.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-09**

**inky wrote:**

> It's an Inspiron N5010.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-10-16**

**inky wrote:**

> I got a new laptop, an HP Pavilion notebook, and have the same hotkey issue (pressing volume down/f7 activates the 'c' hotkey, volume up/f8 activates the 'b' hotkey, etc.)
> 
> The keyboard layout is almost exactly the same as the other laptop, though volume up is f8 instead of f9, etc.

**Comment by inky17** [comment]
Happy to report that this issue is gone with version 1.13.10!
