### ISSUE TITLE
GUI2 canvas text looks bad when rendered on a semi-transparent bg (GNA #24959)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1568]
**[Original submission](https://gna.org/bugs/index.php?24959)** by vultraz on 2016-08-10

gui2::tcontrol widgets like tlabel seems to call font::ttext directly, while gui2 canvas operations call gui2::ttext (which then calls font::ttext). The output of the latter seems to be worse than the output of the former.

The latter also doesn't seem to handle newline characters correctly.

Needs investigation.

(Reproduced on Windows 10)
Release: All
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-11**

**wedge009 wrote:**

> Is there a good example of a dialogue I should be looking at to check this?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-11**

**vultraz wrote:**

> Compare, for example, the text in the headings of the status dialog to the text in the list. The former looks markedly worse, IMO.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-12**

**wedge009 wrote:**

> It's not an obvious difference to me. Perhaps the font size difference may also be making an impact? Do you think it's another Windows-specific text rendering issue? Any difference that's there is even harder to see in Linux. If I had to pick one, overall I'd say the Linux rendering looks nicer.
> 
> 
> 
> I had a look at the ttext references, to see if maybe I could experiment with using one over the other, but I find it all so scattered and hard to read. ):
> 
> (file #28272, file #28273)

**wedge009 added attachment:** [linux.png](http://gna.org/bugs/download.php?file_id=28273)

**wedge009 added attachment:** [windows.png](http://gna.org/bugs/download.php?file_id=28272)

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-18**

**vultraz wrote:**

> Hmmm. Could you compare at any text you can type in text boxes, such as the username field in mp connect?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-19**

**wedge009 added attachment:** [mp_linux.png](http://gna.org/bugs/download.php?file_id=28414)

**wedge009 wrote:**

> Some interesting differences, and not just in the input box. I know you did a change not so long ago relating to the Cairo anti-aliasing and dropping the special case for Windows. While I think what we have now is an improvement over how it was back then, it does look like there is still some inferior rendering going on in Windows.
> 
> 
> 
> On the other hand, there's some interesting interactions between the horizontal line of the t and the dot of the i in the 'multi-player' and 'log-in' text at the top of the Linux image.
> 
> (file #28414, file #28415)

**wedge009 added attachment:** [mp_windows.png](http://gna.org/bugs/download.php?file_id=28415)

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-29**

**vultraz wrote:**

> Removing the background from the text box makes the text look better. Hmmmmm.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-29**

**vultraz wrote:**

> Ok, it seems that somehow blitting the text surface directly onto semi-transparent canvas causes issues. I dunno why this isn't a problem for label widgets... something must happen to the canvas when constructing a dialog that doesn't happen if you draw text directly to the canvas.

**Comment by Wedge009** [comment]
Re-adding the windows label as the conversation with @Vultraz suggests it's mainly a Windows problem.

**Comment by Vultraz** [comment]
To clarify this, the problem occurs when you have something like this:

```
[rectangle]
	x = 0
	y = 0
	w = "(width)"
	h = "(height)"
	fill_color = "0, 0, 0, 150"
[/rectangle]
```

with non-opaque alpha followed either directly or indirectly by a [text] shape in the same canvas (different widgets all have their own canvas - sometimes multiple ones). Something about surface blitting, especially on Windows, causes the result to be sub-optimal.

Do note text rendering uses our custom `blit_surface` function by necessity.

**Comment by mesilliac** [comment]
This probably fixed, but needs confirmation.

**Comment by Wedge009** [comment]
@Vultraz is better able to judge the differences than I am.

**Comment by Wedge009** [comment]
Closing due to lack of feedback. There are other, more obvious, issues with the new hardware-accelerated rendering (though the benefits still outweigh the problems, I think).
