### ISSUE TITLE
[HELP] Portrait gets not shown properly anymore (GNA #25004)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1570]
**[Original submission](https://gna.org/bugs/index.php?25004)** by shiki on 2016-08-21

Something changed since 1.13.4, and this image get's shown buggy. (On image itself or the wml nothing changed.)

(Reproduced on Archlinux)
Release: 1.13.5
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-21**

**shiki added attachment:** [1_13_4-working.jpg](http://gna.org/bugs/download.php?file_id=28472)

**shiki added attachment:** [the_image.png](http://gna.org/bugs/download.php?file_id=28474)

**shiki added attachment:** [1_13_5+dev-broken.jpg](http://gna.org/bugs/download.php?file_id=28473)

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-22**

**wedge009 wrote:**

> Do you have this issue with any of the standard units? Or let me know which add-on has these Elementals, please.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-22**

**vultraz wrote:**

> We implemented scaling of the portraits in help, and that's a known issue that happens with various portraits, including the Mage of Light.

**vultraz changed title:** Portrait gets not shown properly anymore -> [HELP] Portrait gets not shown properly anymore

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-22**

**wedge009 wrote:**

> Oh, I see it now. I wonder if it's a case of the alpha layer not being scaled with rest of the image properly.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-22**

**shiki wrote:**

> This is from Rise of the Elementalists, they appear in the 2nd scenario. If you stark the game in debug mode you can choose the scenario directly.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-28**

**wedge009 wrote:**

> Just wondering: where's the bit of code that does the portrait resizing?

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-08-29**

**wedge009 wrote:**

> vultraz mentioned sdl/utils.cpp:446.
> 
> 
> 
> Could this be related to bug #17961? That one is rather old, so I don't know if the issues it mentions are still valid.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**vultraz wrote:**

> Looks like something similar happens to the ellipses when you zoom in >_> 
> 
> (file #29879)

**vultraz added attachment:** [what happens to the ellipses.JPG](http://gna.org/bugs/download.php?file_id=29879)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**vultraz wrote:**

> Ah, but only if the Linear scaling option is selected...

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**vultraz wrote:**

> Looks like this bug is in the scale_surface (linear scaling) function in sdl/utils:265.

**Comment by Wedge009** [comment]
The portraits in help seem to be okay now. Thanks.
