### ISSUE TITLE
HP loss when changing 'movement cost' for a turn with an object (GNA #25043)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1573]
**[Original submission](https://gna.org/bugs/index.php?25043)** by skeptical_troll on 2016-09-07

the following  code causes units that picked the item to lose few HP when the effect wears off. Other strange effects occurs, like AMLAed units getting fully healed regardless of their started HP. Tested in wesnoth 1.12.2

[code]

      {PICKUPPABLE_ITEM test_ring 10 7  race=khalifate items/ring-red.png

      ( _ "This ring gives improved movement in caves to the bearer" )

      ( _ "Cave agility ring^Take it")

      ( _ "Cave agility ring^Leave it")

      ( _ "This is one of those rings that improves movement in caves. We dwarves are already agile enough on caves. This is definitely better for clumsy humans.")(

      [object]

   image=items/ring-red.png

   name= _ "Cave agility ring"

   description= _ "This ring gives improved movement in caves."

   duration=turn

   [effect]

     apply_to=movement_costs 

     replace=yes

     [movement_costs]

       cave=1

     [/movement_costs]

   [/effect]   

      [/object]

      )} 

[/code]

(Reproduced on Ubuntu 14.04)
Release: 1.12.2
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-09-10**

**vultraz wrote:**

> Can you confirm if this is still an issue in the latest 1.13 version (1.13.5)? We've done some refactoring of the handling of units and unit effects, so this could be fixed.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-09-10**

**skeptical_troll wrote:**

> I downloaded and tried on 1.13.5, and the bugs still holds. Differently than what I previously wrote on the forum, this doesn't seem to actually affect UtbS, I removed my post (apologies for the confusion).

**Comment by gfgtdf** [comment]
fixed by https://github.com/wesnoth/wesnoth/commit/e047564acdfac459a620951d2349d14458a6d2ed (some time ago actually)
