### ISSUE TITLE
Unit image bugged on cave bridge (GNA #25064)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1574]
**[Original submission](https://gna.org/bugs/index.php?25064)** by tekelili on 2016-09-15

I have not tested all transitions, but there is at least one case where I can see (Sorceress) image bugged

(Reproduced on any)
Release: 1.12
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-09-15**

**tekelili added attachment:** [bug_image.png](http://gna.org/bugs/download.php?file_id=28625)

**Comment by CelticMinstrel** [comment]
Is this still an issue?

**Comment by ln-zookeeper** [comment]
Yeah, still an issue. Doesn't even require the bridge really, in this case it just makes the problem apparent by shifting the unit upwards enough to clip into the transition.

I know what the problem is, I just need to figure out how to fix it without breaking something else.

**Comment by Wedge009** [comment]
Did that commit fix this? Was it only for 1.12?
