### ISSUE TITLE
New credits won't display if too many entries are present (GNA #25065)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1575]
**[Original submission](https://gna.org/bugs/index.php?25065)** by vultraz on 2016-09-16

This affects the new GUI2 credits dialogs.

Rather a corner case, since it works fine with mainline credits and mainline campaigns' credits, but if one has too many addon campaigns (with credits, of course) installed, the text will not show.

This is possibly due to the surface becoming too large. However, no tests seem to indicate that fact, including a read of SDL_GetError() when the text surface is created and any intermediate validation steps in the GUI2 canvas as it makes it way to render.

I have also tested whether this is due to some cropping calculation due to the scrollbar positioner becoming too small, but that does not seem to be the case either.

For all intents and purposes, the text is placed (and can even be queried with .label()), but just doesn't show. This can also be triggered if you have "enough" addon campaigns with credits installed and change the label definition to "default_large".

Again, a possibility is the surface being too large, but someone more knowledgeable than I in SDL_Surface's internals will have to look into this.

(Reproduced on Windows 10)
Release: 1.13.5+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-28**

**vultraz changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-26**

**jyrkive wrote:**

> Debugging shows that Pango gives us an empty surface buffer. It looks like a Pango bug at this point.
> 
> 
> 
> I investigated a bit what happens inside Pango, but everything looked normal.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-30**

**jyrkive wrote:**

> All right. It turned out that if I call cairo_status() after attempting to render the text, it returns CAIRO_STATUS_INVALID_SIZE.
> 
> 
> 
> I believe that we exceed the maximum allowed height for Cairo surfaces. The height limit appears to be 32 768 pixels (2^15).

**Comment by jyrkive** [comment]
Fixed by merging #1028.
