### ISSUE TITLE
game create screen not shown when window not big enough (GNA #25101)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1581]
**[Original submission](https://gna.org/bugs/index.php?25101)** by matthiaskrgr on 2016-09-21

window size is 812x861

When trying setting up a multiplayer game and hitting "Create game", there is an error

20160921 22:23:10 error gui/layout: tgrid [] place: Failed to place a grid, we have 821,540 space but we need 831,78 space. This happened at a grid with the id '' in a 'N4gui28tlistboxE' with the id 'side_list' in a 'N4gui25tgridE' with the id '' in a 'N4gui210tgeneratorINS_6policy17minimum_selection5tnoneENS1_17maximum_selection9tinfiniteENS1_9placement12tindependentENS1_13select_action5tshowEEE' with the id '_content_grid' in a 'N4gui25tgridE' with the id '' in a 'N4gui215tstacked_widgetE' with the id '' in a 'N4gui25tgridE' with the id '' in a 'N4gui25tgridE' with the id '' in a 'N4gui25tgridE' with the id '_window_content_grid' in a 'N4gui25tgridE' with the id '_content_grid' in a 'N4gui216tscrollbar_panelE' with the id '' in a 'N4gui25tgridE' with the id '' in a 'N4gui27twindowE' with the id 'mp_staging'.

and the ui where you can assign slots to players is missing.

The ui elements appear when I increase size to around 1100x800 px (but they stay when I make the window smaller again after that, strange).

Battle for Wesnoth v1.13.5+dev (c1ca0e3-Clean)

(Reproduced on linux)
Release: 1.13.5+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-09-23**

**wedge009 wrote:**

> I understand there's been a lot of development recently in the MP Create Game dialogue, so you may have just got it in an unstable state. Can you try again and see if it's still causing you problems?
> 
> 
> 
> Also, this looks like the same situation as bug #25087, just with a different issue on a too-small resolution window.

**wedge009 changed release:** git -> 1.13.5+dev

**Comment by Wedge009** [comment]
Pinging @matthiaskrgr about this one, since he wouldn't be notified of changes to this issue with the move to GitHub.

**Comment by matthiaskrgr** [comment]
Looks good here, it survived 725x573 screen :)

**Comment by Wedge009** [comment]
Thanks, and wow that's a tiny available window (at least by today's standards).
