### ISSUE TITLE
unit moves on impassible terrain (GNA #25217)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1590]
**[Original submission](https://gna.org/bugs/index.php?25217)** by matthiaskrgr on 2016-10-23

in last turn, see attached replay.

(Reproduced on linux)
Release: git
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-10-23**

**matthiaskrgr added attachment:** [2p_�_Dark_Forecast_(Survival)_replay.gz](http://gna.org/bugs/download.php?file_id=29108)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-23**

**zookeeper wrote:**

> For some reason, the spawns are given some altered movement costs, which specifically includes impassable=3. It seems to have always been that way, although I don't know the exact reasoning, as it can certainly lead to unpredictable weirdness like that and the back mountains/wall are the only impassable terrains anyway.
> 
> 
> 
> So, while it's not a technical bug, I don't think it'd be inappropriate to call it a bug in the scenario design... even if it's intentional.

**Comment by Pentarctagon** [comment]
This is still happening: https://i.imgur.com/PBpltAp.png

**Comment by stevecotton** [comment]
Duplicated by #3891. Better to close this one, the other one has more discussion about the bug.
