### ISSUE TITLE
MP slot selection becomes black (GNA #25221)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1591]
**[Original submission](https://gna.org/bugs/index.php?25221)** by matthiaskrgr on 2016-10-23

Multiplayer

Local game

create game

=> hover cursor between team color selector and background of the widget(?)

the background will become darker every time until text is completely unreadable

(Reproduced on linux)
Release: 1.13.5+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-10-23**

**wedge009 wrote:**

> At first I thought this might be related to bug #25107, but it doesn't look like it. I'm playing around with the colour selection in both Windows and Linux and I can't see what you're describing.
> 
> 
> 
> I wonder if it's something to do with your SDL version or maybe graphics drivers.

**wedge009 changed release:** git -> 1.13.5+dev

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-25**

**gfgtdf wrote:**

> This is related to the semi-translarent background of that treeview ([panel] definition = "box_display_no_blur_no_border" ...). It onyl happens if the panels child widget (the treeview) doesnt wully fit on the window (e.g when a scrollbar appears at the bottom of the window and that scrollbar is set so that the treeview is not fully visible).
> 
> 
> 
> The same issue can be observed at the mp create game screen if you use a bad resultion and the name/password bos is onyl partly visible in the window.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-25**

**gfgtdf wrote:**

> s/wully/fully

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-25**

**wedge009 wrote:**

> 'doesn't fully fit on the window' sounds more related to my bug #25107.

**Comment by Wedge009** [comment]
Possibly related: #1583

**Comment by CelticMinstrel** [comment]
I think this should be largely fixed by my relayout of the MP Staging dialog for low resolutions. I can't be certain it won't ever happen still, but it should at least happen less frequently.

**Comment by CelticMinstrel** [comment]
Note that it probably only ever happened on lower resolutions - it occurred only when the window had a scrollbar along the bottom.

**Comment by matthiaskrgr** [comment]
Oooh yes, you are right.. It still happens :(

**Comment by CelticMinstrel** [comment]
Can you give any details of a game in which it still happens? Or even a screenshot from _before_ the blackness overwhelms it (it only starts going black when the mouse hovers over the main staging area) or from after resizing the window to avoid it. And are you viewing at 1024x768 or something less?

**Comment by matthiaskrgr** [comment]
wesnoth 61ec2d0
Game resolution:
````
  Width: 780
  Height: 861
````
Multiplayer
Local Game
Create Game
Hover mouse onto and off the player/local/player/ai selection thing
=>
sometimes when moving it off, the darkening is not reset.
![scr](https://cloud.githubusercontent.com/assets/476013/25936950/14807962-362a-11e7-9189-6d682d1cfaa5.png)

**Comment by CelticMinstrel** [comment]
So Elensefar Courtyard. Alright, I'll see if I can reproduce.

**Comment by matthiaskrgr** [comment]
Hmm, additional note: you have to move the cursor rather fast, when I move it slowly, the issue does not seem to occur. It might be easier to reproduce on my sys because I build with -O0 and sanitizers which introduces a huge slowdown on code execution.

**Comment by Wedge009** [comment]
Ah, a picture is worth many words - I can confirm this is the same as #1583. If the list of players is big enough relative to the window to require a scroll bar, you'll get the blackening effect.

**Comment by CelticMinstrel** [comment]
Right. I reduced the chance that the list of players will get that big, but did not address the actual issue.

**Comment by CelticMinstrel** [comment]
Oh, I wonder if tweaking the resolution at which the more compact layout is used would be sufficient? See data/gui/window/mp_staging.cfg, lines 556 and 557.

Also, I wonder if this problem exists for guests as well as hosts? If I recall correctly, the guest side is implemented as a separate dialog, so it might not be an issue...
