### ISSUE TITLE
Game room player list shows host multiple times for guest (GNA #25271)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1598]
**[Original submission](https://gna.org/bugs/index.php?25271)** by wedge009 on 2016-11-07

I tested with a Windows instance and a Linux instance, happens when either is the guest. See attached image for an example, the host name appears multiple times.

I was using the official server, current master build for both instances, b739bdde.

(Reproduced on All)
Release: 1.13.6+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-07**

**wedge009 added attachment:** [repeated-host.png](http://gna.org/bugs/download.php?file_id=29320)

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-07**

**vultraz wrote:**

> I can't repro this :/

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-07**

**wedge009 wrote:**

> Would appreciate testing from others on this. I just retested on current master (6faef63b) on the following scenarios:
> 
> 
> 
> * Windows 7 and Linux instances connecting to the official server.
> 
> * Two Windows 7 instances connecting to the official server.
> 
> * Windows 7 and Linux instances connecting to a local wesnothd instance on the Windows 7 PC.
> 
> * Windows 7 and Linux instances connecting to a local wesnothd instance on the Linux PC.
> 
> 
> 
> In all cases, the guest instance (ie the player not hosting the game) lists the host multiple times in the chat window's list of players. I was using Legend of Wesmere campaign.
> 
> 
> 
> I find it hard to believe that something in Windows 10 would prevent this from happening.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**vultraz wrote:**

> Can you still repro this?

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**wedge009 wrote:**

> I just tested against 15f8ac3c and unfortunately, yes, this still occurs. Tested with Windows and Linux clients connecting to the official server, both clients show multiple player entries (as in the original screenshot) when they are the guest.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**vultraz wrote:**

> And I *still* can't get this to happen myself :(

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**wedge009 wrote:**

> It's okay. If it's any consolation, it's not a game-crippling bug, just a cosmetic oddity.
> 
> 
> 
> Out of curiosity, how long are your player names? I doubt it would make a difference, but it's something to consider.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**vultraz wrote:**

> "vultraz" and "vultraz2"

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**wedge009 wrote:**

> I tried vultraz2 and vultraz3 on official server with Legend of Wesmere campaign and French, English GB, and English US languages, all having the issue on the guest's Connected Players list.
> 
> 
> 
> Would be nice to have at least one other test this, regardless of whether or not he/she can reproduce it.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-20**

**wedge009 wrote:**

> Uh, I just realised I may be confusing you. By 'lobby' I meant the player list for the game room the host and client have joined. Not referring to the global lobby that everyone has access to when they first enter MP.
> 
> 
> 
> Renaming the report to clarify this.

**wedge009 changed title:** Lobby shows host multiple times for guest -> Game room player list shows host multiple times for guest

**Comment by Wedge009** [comment]
Commenting so as reported I'm subscribed to this, plus still waiting for someone besides myself and @Vultraz to test this so we can see if it's something specific to my or his builds.

**Comment by Vultraz** [comment]
@Wedge009 please confirm the above

**Comment by Wedge009** [comment]
Seems good to me. Thanks!
