### ISSUE TITLE
assertion failure: future move + shroud + planning mode (GNA #25277)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1599]
**[Original submission](https://gna.org/bugs/index.php?25277)** by matthiaskrgr on 2016-11-09

have map with shroud

make sure shroud updates are delayed

move unit to farthest edge of shroud it can reach in 2 turns

start planning mode

=>

wesnoth: /home/matthias/vcs/github/wesnoth/src/actions/undo.cpp:488: bool actions::undo_list::apply_shroud_changes() const: Assertion `synced_context::is_synced()' failed.

(Reproduced on linux)
Release: v1.13.6+dev (bf0f1b4-Clean)
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-10**

**gfgtdf wrote:**

> please give a stacktrace of this asertion failure.

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-10**

**matthiaskrgr added attachment:** [assert_failure_shroud.log](http://gna.org/bugs/download.php?file_id=29356)

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-10**

**gfgtdf wrote:**

> thx for this stacktrace, form looking at the code it seems like the whiteboard is generally incompatible with the normal undo system. Meaning that when you 'execute' a planned move, you cannot undo it, even if the map uses nigher fog or shroud is this correct?

**Comment by gfgtdf** [comment]
the assert_failure_shroud.log file cannot be seen anyore.

**Comment by Wedge009** [comment]
I can still access the log file just now.

**Comment by gfgtdf** [comment]
ye celmin fixed that link

**Comment by gfgtdf** [comment]
fixed in https://github.com/wesnoth/wesnoth/commit/5412a24b05a9f8b89db0a2734ab77a46a7e19f66
