### ISSUE TITLE
Crash if wesnoth resolution is higher than desktop resolution. (GNA #25288)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1602]
**[Original submission](https://gna.org/bugs/index.php?25288)** by shiki on 2016-11-12

When the desktop resolution is lower then the resolution used the last time in wesnoth, it segfaults on startup.

https://bpaste.net/show/c77216cb59be

(Reproduced on Archlinux)
Release: 1.13.6+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-12**

**gfgtdf wrote:**

> this coudl be relatd to caused by https://gna.org/bugs/index.php?25290

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-13**

**shiki wrote:**

> I suppose so.
> 
> 
> 
> I remember that there comes usually an error message saying something about Xorg and exits then.
> 
> 
> 
> This could be changed to =)

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-13**

**wedge009 wrote:**

> I find this issue seems specific to Linux - Windows is fine. I recall we had issues with this in SDL1 but I thought it was resolved with the move to SDL2.
> 
> 
> 
> Regardless, this seems related to your own bug #24984.

**Comment by Wedge009** [comment]
Linking mention of #1603 from @gfgtdf.

**Comment by Wedge009** [comment]
Testing 1.14.0 in Linux, I found that manually setting the preferences file to use much higher resolution than is available in the desktop doesn't appear to cause any issue - the game just reverts to the highest available resolution on start-up.

If @sevu or @gfgtdf still find this is a problem they can re-open.
