### ISSUE TITLE
Image Not Found for minimap icons when using large font size (GNA #25293)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1604]
**[Original submission](https://gna.org/bugs/index.php?25293)** by inky on 2016-11-13

Very large (120% or greater) font sizes will cause some of the icons for the minimap to show up as "image not found."

I'm using 1280x720 resolution if that's relevant.

(Reproduced on All)
Release: 1.13.6
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-13**

**wedge009 changed OS:** Windows 10 -> All

**wedge009 changed status:** None -> Confirmed

**wedge009 wrote:**

> For me, happens in both Windows and Linux at 115% or higher.

**Comment by jostephd** [comment]
`location().h == 26` here:

https://github.com/wesnoth/wesnoth/blob/9fd59ebcda48ce905dd65afc9e5df7a79a1c82d9/src/widgets/button.cpp#L87-L99

That causes the images to be looked up under the wrong name, `minimap-draw-terrain.png` rather than `minimap-draw-terrain_25.png`, so they're not found.

**Comment by Wedge009** [comment]
Hmm... so there are hard-coded variants of images... and which variant is loaded is dependent on the height of the location...? And this height value is presumably affected by the font scaling feature. So need to use a non-scaled value instead...

**Comment by CelticMinstrel** [comment]
> So need to use a non-scaled value instead...

Rather than using a non-scaled value, probably round to the nearest valid size.

**Comment by Wedge009** [comment]
Has font scaling been removed again? I can't find it in 1.17.0+dev nor 1.15.17+dev.

**Comment by Wedge009** [comment]
Apparently scaling is done automatically now - is the issue with the missing buttons still present?

**Comment by CelticMinstrel** [comment]
I guess we'd have to ask someone with a high-DPI screen, right?

**Comment by Wedge009** [comment]
Aye. I don't even know what would be the threshold for what would be considered a high-DPI screen. Is this something @Vultraz would know about?

**Comment by Wedge009** [comment]
I'm guessing this was covered by work related to #2219. Please re-open if it turns out it's still a problem.
