### ISSUE TITLE
workspace switching in fullscreen mode (GNA #25303)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1606]
**[Original submission](https://gna.org/bugs/index.php?25303)** by shiki on 2016-11-15

One of the good things from the sdl2 movement is that it's now possible to switch workspaces while you use fullscreen mode. For wesnoth that's in particular good, since you have to wait between the rounds, and games often take hours.

However, there are some bugs which should be fixed before 1.14:

When using fullscreen mode, by switching to another workspace and back, wesnoth gets often, but not in every case, minimized.

E.g try this:

Use key combinations for workspace switching, possibly ctrl+alt+(up/down)/(left/right) or ctrl+F1/F2/F3/F4

Start wesnoth on the second workspace.

Switching to the third and back is fine.

Switching to the first and back minimizes wesnoth.

(or the other way around)

Another possibility of switching workspaces are kind of overview modes.

In gnome 3, that's what you get with the [win] key.

In kde 5 exist many similar such modes (grid, cube, zylinder, ball, and more), one of them is availaible with ctrl+F11, two others with ctrl+F9/F10. *

Windows 10 has as well sth. like this.

The problem is the same here. But what do these overview modes show when the window got minimized (due to switching the workspace forth and back in overview mode)?

 => see picture 1 & 2. When choosing the wesnoth windows again, everything is fine.

When the wesnoth window is not minimized, then the wesnoth window looks normal in the pverview, without broken map.

With much workspace switching something like that can happen too:

 => in gnome: see picture 3

 If I click away the message, all works fine.

 In kde I didn't happen to get such a message, maybe kde is more tollerant there.

 In windows 10 I managed somehow to get a similar message (tough windows doesn't allow me to click away the message and continue the game), but I can't reproduce it. The key combination to switch workspaces in windows 10 is ctrl+win+(right/left).

 ----

* "Allow Applications to block compositing" must be disabled in the system settings -> hardware -> display -> compositor

(Reproduced on Archlinux Win10)
Release: 1.13.6+dev
Priority: 5 - Normal
Severity: 4 - Important

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-11-15**

**shiki added attachment:** [picture_1(gnome).jpg](http://gna.org/bugs/download.php?file_id=29396)

**shiki added attachment:** [picture_3.jpg](http://gna.org/bugs/download.php?file_id=29398)

**shiki added attachment:** [picture_2(kde).jpg](http://gna.org/bugs/download.php?file_id=29397)

**Comment by CelticMinstrel** [comment]
I assume this is still an issue, @sevu?

**Comment by sevu** [comment]
Yes.

**Comment by jyrkive** [comment]
I can reproduce this issue myself. Latest Git master, siduction GNU/Linux, KDE Plasma 5.8.7, SDL 2.0.5.

I'll try to figure something out.
