### ISSUE TITLE
recruit window: unit scaling method (GNA #25347)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1609]
**[Original submission](https://gna.org/bugs/index.php?25347)** by shiki on 2016-11-30

I have the impression that the SCALE_SHARP method mentioned here is getting used for scaling.

https://wiki.wesnoth.org/ImagePathFunctionWML#SCALE:_Image-scaling_function

I suppose that it looks better with the SCALE or XBRZ method.

(Reproduced on Archlinux)
Release: 1.13.6+dev
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**vultraz wrote:**

> SHARP scaling is indeed used. This is deliberate. Simple ~SCALE doesn't look great, and while I'd like to use XBRZ, I have to deal with sprites that are over 72x72.
> 
> 
> 
> I do have an idea, however...

**Comment by Vultraz** [comment]
Honestly, can't remember what the idea for using xBRZ was anymore, and I think SCALE_SHARP works just fine. Closing.

**Comment by grz0** [comment]
> Honestly, can't remember what the idea for using xBRZ was anymore, and I think SCALE_SHARP works just fine. Closing.

@Vultraz Could you reopen this issue? xBRZ scaling looks much better

![b](https://user-images.githubusercontent.com/3605541/37435384-69f40002-27e3-11e8-886a-0cd2dce8ef3d.png)

> Simple ~SCALE doesn't look great, and while I'd like to use XBRZ, I have to deal with sprites that are over 72x72.

~XBRZ(2)~SCALE(144,144) works for all sprites
160 x 200 sprites:

![a](https://user-images.githubusercontent.com/3605541/37435374-60331ddc-27e3-11e8-8fe2-a9b2cfd591cb.png)

**Comment by Vultraz** [comment]
Hmmm.. I hadn't thought to use both IPFs in conjuncture...
