### ISSUE TITLE
`wesnoth` fails to start with SDLApplication clash (GNA #25357)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1610]
**[Original submission](https://gna.org/bugs/index.php?25357)** by adunn on 2016-12-03

I compiled 1.13.6 from source, and when I try to run `wesnoth` from the command-line it prints this message then hangs:

```

$ wesnoth

objc[37013]: Class SDLApplication is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x108aabd70)and /usr/local/bin/wesnoth (0x1081408c8). One of the two will be used. Which one is undefined.

```

Full build logs: https://gist.github.com/dunn/8e8cc251a17a08edb1041b91a23489b2#file-01-scons-L1

(Reproduced on macOS 10.12.1)
Release: 1.13.6
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-12-04**

**adunn wrote:**

> Still occurs on HEAD, as of 707c9d7:
> 
> 
> 
> ```
> 
> objc[55868]: Class SDLApplication is implemented in both /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (0x10d968d70)and /usr/local/bin/wesnoth (0x10cf8a868). One of the two will be used. Which one is undefined.
> 
> ```

**Comment by singalen** [comment]
Close this.
`/usr/local/opt/` means a MacPorts compilation, not officially supported.

If someone ever wants to build on MacPorts, with `libsdl2main`, go to `wesnoth.cpp` and replace 

```
#ifdef __APPLE__
extern "C" int wesnoth_main(int argc, char** argv);
```
with
```
#ifdef __CHUPACABRA__
extern "C" int wesnoth_main(int argc, char** argv);
```

**Comment by singalen** [comment]
For those who come here later: after adding `SDLMain.mm` to `CMakeLists.txt`, it stopped building with MacPorts, because SDLMain.mm refers to `wesnoth_main()`.
If one removes `SDLMain.mm`, it still builds with MacPorts.
It won't have the main menu, though.
