### ISSUE TITLE
SDL2 support broken on ARM (GNA #25377)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1614]
**[Original submission](https://gna.org/bugs/index.php?25377)** by petevine on 2016-12-10

I've just built the new, SDL2-based wesnoth on ARM Linux and it's definitely broken. 

Using a GLES-only SDL2 library leads to a game with non-working keyboard and a functioning mouse pointer (no clicks). The choice of the rendering backend seems to be important here. (another issue about SDL2/OpenGL coming next)

I might try a debug build later, but for now here's what I'm seeing on the console:

$ ./wesnoth

Battle for Wesnoth v1.13.6+dev (66494fc-Clean)

Started on Sat Dec 10 22:17:59 2016

Automatically found a possible data directory at /home/odroid/wesnoth-master/build-boost154/..

Data directory:               /home/odroid/wesnoth-master/build-boost154/..

User configuration directory: /home/odroid/.config/wesnoth

User data directory:          /home/odroid/.local/share/wesnoth/1.13

Cache directory:              /home/odroid/.cache/wesnoth

Setting mode to 1280x1024

Checking lua scripts... ok

20161210 22:18:05 error general: Unknown key: +

20161210 22:18:05 error general: Unknown key: page up

20161210 22:18:05 error general: Unknown key: page down

20161210 22:18:05 error general: Unknown key: :

(Reproduced on Linux)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2016-12-12**

**petevine wrote:**

> Forgot to mention there was no sound either. (unlike in #25378)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-01-06**

**petevine wrote:**

> Just finished building @cb7ea10 and input/sound problems are gone. The game still crashes though which leaves #25377 as the main issue.

**Comment by Vultraz** [comment]
Closing this one since there have been no further reports.
