### ISSUE TITLE
Animations immediately following a message get truncated (GNA #25397)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1617]
**[Original submission](https://gna.org/bugs/index.php?25397)** by zookeeper on 2016-12-20

If a [message] is shown right prior to an animation, then the animation gets skipped or truncated somehow. It doesn't seem to matter whether the animation is one triggered by [animate_unit] or for example a regular combat animation. I'm also not entirely sure whether other things besides animations suffer from the same problem.

One can workaround the problem by inserting a delay after the message (for example even [delay] time=0 [/delay] works). So, one possible fix was to add wesnoth.delay(1) to the [message] implementation, but vultraz didn't want that because it'd cause a brief flicker between successive messages.

A simple test case:

```

    [event]

        name=attacker hits,attacker misses,defender hits,defender misses

        first_time_only=no



        {DEBUG_MSG "As long as this message is here, the following combat animations won't play correctly"}

    [/event]

```

(Reproduced on win 7)
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by CelticMinstrel** [comment]
Hold on, if even a delay of 0 works, then what about adding `wesnoth.delay(0)` to the `[message]` implementation?

**Comment by ln-zookeeper** [comment]
That doesn't seem to work. [delay]time=0 works, wesnoth.delay(0) doesn't. Probably something in the internals of one or the other checks it for >=1 or something.

**Comment by gfgtdf** [comment]
> That doesn't seem to work. [delay]time=0 works, wesnoth.delay(0) doesn't.

this is extremeley unlikeley, since [delay] in implemented in lua by calling wesnoth.delay

**Comment by ln-zookeeper** [comment]
> this is extremeley unlikeley, since [delay] in implemented in lua by calling wesnoth.delay

Right, looks like I was inserting the wesnoth.delay(0) in the wrong place.

Regardless, even a delay of 0 after a message causes a redraw between successive messages, causing flicker.

**Comment by Vultraz** [comment]
DeFender seemed to indicate this was fixed on accelerated_rendering.

**Comment by Vultraz** [comment]
Should have closed this a long time ago since accelerated_rendering was merged into master months ago and the fix for this along with it.
