### ISSUE TITLE
OOS when redoing certain action that use synced choices (GNA #25473)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1623]
**[Original submission](https://gna.org/bugs/index.php?25473)** by gfgtdf on 2017-01-29

This code:

```



	[event]

		name="recall"

		first_time_only=no

		[message]

			mesage = "mesage"

			[option]

				message = "option 1"

				[command]

				[/command]

			[/option]

			[option]

				message = "option 2"

				[command]

				[/command]

			[/option]

		[/message]

		[allow_undo]

		[/allow_undo]

	[/event]

```

causes OOS if the actions is first undne and then redone, you will also see that the engine shos the message with options again when redoing the actions while it actualyl shouldn't (it shoudl just use the stored answer from when this action was executed the first time)

(Reproduced on )
Release: 1.13.6
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-23**

**gfgtdf changed status:** None -> Invalid

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-23**

**gfgtdf wrote:**

> After looking at this again i think this code is not meant to be OOS safe. Its actually the same code that is meantioned as an oos-causing example at https://wiki.wesnoth.org/DirectActionsWML#.5Ballow_undo.5D. Makrin as invlid

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-23**

**gfgtdf wrote:**

> My bad i didnt see the first_time_only=no in my exampel code bloew, marking as 'none'

**gfgtdf changed status:** Invalid -> None

**Comment by gfgtdf** [comment]
probably fixed by https://github.com/wesnoth/wesnoth/commit/26d80bdb54e5bbce702dc4e842f2ed65ac973e29

**Comment by CelticMinstrel** [comment]
Why the 1.13.7 milestone?

**Comment by gfgtdf** [comment]
because .13.7 is the first release that had this commit in it
