### ISSUE TITLE
addon manger is slow (GNA #25523)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1627]
**[Original submission](https://gna.org/bugs/index.php?25523)** by gfgtdf on 2017-02-19

The addon manager is currently quite slow when selecting new list entries. This doesn't happen on all entries though, i suspect that is somehow related to the feedback url textbox since is seems not to happen if the feedback url of the next addon is the same as the feedbackurl of the previous addon. I further suspect that someting is calling window->invalidate_layout() i couldn't firgue out how exactly though.

(Reproduced on windows)
Release: 1.13.6+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-19**

**vultraz wrote:**

> Just throwing a out guess that it's the various scroll labels, esp Author, Version, and Description.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-19**

**gfgtdf wrote:**

> > Just throwing a out guess that it's the various scroll labels, esp Author, Version, and Description.
> 
> 
> 
> Hmm but this slowness does not happen when i just switch selection between addons that don't specify a feedback url. It only happens if i switch selection bettwen two addons that have a differnet feeback url
> 
> 
> 
> If i could debug here i would just put a brakpount in window::invalidate_layout and look at the callstack.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-21**

**gfgtdf wrote:**

> Hmm i think you are right, when i tested it now again it wasn't as related to the feedback rl as it seemed when i tested it the first time.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-24**

**wedge009 wrote:**

> It's hard to quantify slowness because everyone's system is different. But even on my system there seems to be a slight delay in bringing up a newly-clicked list entry.
> 
> 
> 
> At the menu screen CPU usage is negligible. When I go to the add-on screen it jumps to 50-75% of a single core. So it looks like there's something funny going on there. Reminds me of the issue with the ocean animation filling up the majority of the grid (like in the mermen campaign) but there's no animation here...

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-02-25**

**vultraz wrote:**

> Really good way to repro is just use the arrow keys to scroll quickly through the list. Certain entries take longer to come up than others, though the difference on my system is pretty negligible.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-21**

**jyrkive wrote:**

> https://github.com/wesnoth/wesnoth/pull/963

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-22**

**jyrkive changed status:** None -> Fixed

**jyrkive wrote:**

> Fixed. Vultraz merged the pull request. (Thanks!)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-22**

**wedge009 wrote:**

> Before I had a chance to test it! Okay, I'll have a look in my next rebuild.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-22**

**wedge009 wrote:**

> Seems okay to me, thanks!

**Comment by jyrkive** [comment]
Closing as per the new bug protocol.
