### ISSUE TITLE
List in the hotkey preference dialog becomes bigger (GNA #25553)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1629]
**[Original submission](https://gna.org/bugs/index.php?25553)** by ratarmy on 2017-03-01

Hotkey list becomes bigger and hide toggle buttons.

To replicate the bug:

1. Open preference dialog.

2. Click hotkey tab.

3. Click other tab.

4. Repeat 2-3.

(Reproduced on Linux)
Release: 1.13.6+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-02**

**vultraz wrote:**

> Cannot repro. Could you provide a screenshot?

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-03**

**wedge009 wrote:**

> I also didn't find this issue. I tested against b1ea099d on both Windows and Linux. I also wondered if font scaling might have been a factor but that doesn't seem to cause what you describe either. Sorry.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-03**

**ratarmy added attachment:** [Screenshot_20170303_201346.png](http://gna.org/bugs/download.php?file_id=29861)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-03**

**ratarmy wrote:**

> I attached a screenshot(file #29861) in version 1.13.6+dev (b1ea099-Clean).
> 
> 
> 
> Maybe my explanation causes misunderstanding.
> 
> The "tab" which I called don't mean a bar on the hotkey list, but also buttons on the left bar(ex. General, Hotkeys, Display,...etc).
> 
> 
> 
> So, to reproduce this bug, just repeat switching "General" and "Hotkeys" button.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-03**

**wedge009 wrote:**

> Uh, that's what I was doing, switching between the 'tabs' in the preferences dialogue. Also, it's not clear what's the issue in the picture - is it that the hot-key groups have gone?
> 
> 
> 
> Do you still have the problem with a clean build?

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-03**

**ratarmy wrote:**

> I did clean build(rm&mk build-dir, cmake, make).
> 
> 
> 
> > is it that the hot-key groups have gone?
> 
> Yes, it is the problem.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-04**

**ratarmy wrote:**

> I doubt that this bug is environment-dependent.
> 
> 
> 
> I asked people in the Japanese translation team to check this bug in latest wesnoth, and this bug is caused too in their system.
> 
> 
> 
> But, the condition is different for each people...
> 
> Some people says that this bug is caused when font scale is more than 110%, but other people says that font scaling is not related.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-04**

**wedge009 wrote:**

> Looks like we really need help in reproducing this issue because it sounds like none of the regulars here are able to do so. I tried switching to Japanese language as well as experimenting with the font scaling but still can't replicate the issue.
> 
> 
> 
> Perhaps if you could share your preferences file? Or maybe check with those in the translation team to see what's common in their preferences. There must be something happening in there to cause the issue and if we can find out what that is, at least that will be a start to resolving it.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-04**

**vultraz wrote:**

> TBH, the only really odd thing in your screenshot is that the hotkey category list is missing. Maybe that's what you're referring to?

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-04**

**wedge009 wrote:**

> I believe so (see ratarmy's comment on 3rd March 13:00 UTC).

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-04**

**vultraz wrote:**

> Still, I can't make it go away myself :/

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-04**

**wedge009 wrote:**

> Nor I. :/

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-04**

**ratarmy added attachment:** [hotkey_2click.png](http://gna.org/bugs/download.php?file_id=29865)

**ratarmy wrote:**

> I notice that this bug is caused by not only switch tab, but also click "Hotkeys" button repeatedly.
> 
> 
> 
> 1click: 
> 
> 
> 
> My preference file
> 
> ```
> 
> UI_sound=yes
> 
> UI_volume=""
> 
> allow_observers=yes
> 
> ally_orb_color="lightblue"
> 
> ally_sighted_interrupts=yes
> 
> animate_map=yes
> 
> animate_water=yes
> 
> ask_delete=""
> 
> auto_save_max=3
> 
> bell_volume=""
> 
> blindfold_replay=no
> 
> campaign_server="add-ons.wesnoth.org"
> 
> chat_lines=6
> 
> chat_message_aging=""
> 
> chat_timestamp=no
> 
> color_cursors=no
> 
> completed_campaigns=""
> 
> compress_saves="gzip"
> 
> confirm_end_turn=""
> 
> confirm_load_save_from_different_version=""
> 
> core="default"
> 
> damage_prediction_allow_monte_carlo_simulation=no
> 
> delete_saves=no
> 
> disable_auto_moves=no
> 
> disable_notifications=""
> 
> editor_auto_update_transitions=""
> 
> editor_b=""
> 
> editor_default_dir=""
> 
> editor_draw_hex_coordinates=""
> 
> editor_draw_terrain_codes=no
> 
> editor_g=""
> 
> editor_max_recent_files=""
> 
> editor_r=""
> 
> enable_planning_mode_on_start=no
> 
> encountered_terrain_list=""
> 
> encountered_units=""
> 
> enemy_orb_color="black"
> 
> fi_friends_in_game=""
> 
> fi_invert=no
> 
> fi_text=""
> 
> fi_vacant_slots=no
> 
> filter_lobby=yes
> 
> flip_time=""
> 
> floating_labels=yes
> 
> font_scale=100
> 
> friend_message_lobby=no
> 
> friend_message_notif=no
> 
> friend_message_sound=no
> 
> fullscreen=no
> 
> game_has_begun_lobby=no
> 
> game_has_begun_notif=no
> 
> game_has_begun_sound=yes
> 
> grid=no
> 
> hide_whiteboard=no
> 
> host="server2.wesnoth.org:15000"
> 
> iconize_list=yes
> 
> idle_anim=yes
> 
> idle_anim_rate=0
> 
> joystick_cursor_deadzone=""
> 
> joystick_cursor_threshold=""
> 
> joystick_cursor_xaxis_num=""
> 
> joystick_cursor_yaxis_num=""
> 
> joystick_num_cursor_xaxis=""
> 
> joystick_num_cursor_yaxis=""
> 
> joystick_support_enabled=""
> 
> lobby_auto_open_whisper_windows=""
> 
> lobby_joins="friends"
> 
> lobby_playerlist_group_players=""
> 
> lobby_playerlist_sort_name=yes
> 
> lobby_playerlist_sort_relation=yes
> 
> lobby_sounds=""
> 
> lobby_whisper_friends_only=no
> 
> local_tod_lighting=""
> 
> locale="en_US"
> 
> login="@RatArmy@"
> 
> login_is_wrapped=yes
> 
> maximized=yes
> 
> message_bell=""
> 
> middle_click_scrolls=""
> 
> minimap_draw_terrain=yes
> 
> minimap_draw_units=yes
> 
> minimap_draw_villages=no
> 
> minimap_movement_coding=yes
> 
> minimap_terrain_coding=yes
> 
> modifications=""
> 
> mouse_scrolling=""
> 
> moved_orb_color="red"
> 
> mp_countdown=no
> 
> mp_era="era_khalifate"
> 
> mp_fog=yes
> 
> mp_level="multiplayer_Ruphus_Isle"
> 
> mp_level_type=0
> 
> mp_modifications=""
> 
> mp_random_start_time=no
> 
> mp_shroud=no
> 
> mp_turns=100
> 
> mp_use_map_settings=yes
> 
> mp_village_gold=2
> 
> mp_village_support=1
> 
> mp_xp_modifier=70
> 
> music=yes
> 
> music_volume=""
> 
> new_lobby=no
> 
> partial_orb_color="brightorange"
> 
> password=""
> 
> ping_timeout=""
> 
> player_joins_lobby=no
> 
> player_joins_notif=no
> 
> player_joins_sound=yes
> 
> player_leaves_lobby=no
> 
> player_leaves_notif=no
> 
> player_leaves_sound=yes
> 
> private_message_lobby=yes
> 
> private_message_notif=no
> 
> private_message_sound=yes
> 
> public_message_lobby=no
> 
> public_message_notif=no
> 
> public_message_sound=no
> 
> random_faction_mode="Independent"
> 
> ready_for_start_lobby=no
> 
> ready_for_start_notif=no
> 
> ready_for_start_sound=yes
> 
> registered_users_only=no
> 
> remember_password=no
> 
> remember_timer_settings=""
> 
> sample_rate=""
> 
> save_replays=yes
> 
> scale_hex="linear"
> 
> scale_zoom="linear"
> 
> scroll=50
> 
> scroll_threshold=10
> 
> scroll_to_action=yes
> 
> scroll_when_mouse_outside=""
> 
> server_message_lobby=yes
> 
> server_message_notif=no
> 
> server_message_sound=yes
> 
> show_ai_moves=yes
> 
> show_all_units_in_help=no
> 
> show_ally_orb=yes
> 
> show_combat=""
> 
> show_enemy_orb=yes
> 
> show_haloes=yes
> 
> show_moved_orb=yes
> 
> show_partial_orb=yes
> 
> show_side_colors=yes
> 
> show_unmoved_orb=yes
> 
> shuffle_sides=no
> 
> skip_ai_moves=no
> 
> skip_mp_replay=no
> 
> sort_list=yes
> 
> sound=yes
> 
> sound_buffer_size=""
> 
> sound_volume=""
> 
> sp_modifications=""
> 
> startup_effect=""
> 
> stop_music_in_background=no
> 
> theme="Default"
> 
> turbo=yes
> 
> turbo_speed=1.75
> 
> turn_bell=yes
> 
> turn_changed_lobby=no
> 
> turn_changed_notif=no
> 
> turn_changed_sound=yes
> 
> turn_dialog=yes
> 
> unit_standing_animations=yes
> 
> unmoved_orb_color="brightgreen"
> 
> use_twelve_hour_clock_format=""
> 
> xresolution=1920
> 
> xwindowsize=1920
> 
> yresolution=1017
> 
> ywindowsize=1017
> 
> [dir_bookmarks]
> 
> [/dir_bookmarks]
> 
> [options]
> 
> [/options]
> 
> [completed_campaigns]
> 
> [/completed_campaigns]
> 
> [history]
> 
> [/history]
> 
> 
> 
> ```
> 
> (file #29863, file #29864, file #29865)

**ratarmy added attachment:** [hotkey_1click.png](http://gna.org/bugs/download.php?file_id=29864)

**ratarmy added attachment:** [hotkey_initial.png](http://gna.org/bugs/download.php?file_id=29863)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-04**

**ratarmy added attachment:** [hotkey_3click.png](http://gna.org/bugs/download.php?file_id=29866)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-04**

**ratarmy wrote:**

> I sent #12 on the way.
> 
> 
> 
> Here are new screenshots for different number of click times.
> 
> before click: file #29863
> 
> 1click: file #29864
> 
> 2click: file #29865
> 
> 3click: file #29866
> 
> 
> 
> The more I click the "Hotkeys", the bigger hotkeys list become.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-04**

**wedge009 wrote:**

> I didn't notice anything immediately obvious in the preferences, but something is clearly wrong. There is way too much padding in your initial dialogue image. I always see an image somewhere in between your 1 and 2 click images - there are three rows of hot-key group buttons, with the top of the hot-key list flush against the bottom row. This does not change no matter how many clicks I try.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-07**

**vultraz changed status:** None -> Works For Me

**Comment by Wedge009** [comment]
This 'works' for @Vultraz and myself, but clearly it's an issue for @fujimo-t. I wonder if we can get anyone else to try to confirm this.

**Comment by CelticMinstrel** [comment]
I'm guessing this was an effect of the grid listbox. Since Vultraz switched that out for a multimenu button, I imagine the issue won't occur anymore.

**Comment by Wedge009** [comment]
Duh, I forgot about that again. Well, we still need confirmation from @fujimo-t before we can close this one, I think, since only he had this issue.

**Comment by fujimo-t** [comment]
The issue doesn't occur now in my environment. Thank you.
