### ISSUE TITLE
map scaling + shroud/fog (GNA #25590)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1635]
**[Original submission](https://gna.org/bugs/index.php?25590)** by shiki on 2017-03-13

It's possible to scale the map with the "+" key - or the key which is on that place where the english layout has the "+" key.

On maps with shroud are such artefacts. Many are related to the animated water, but not all. moving the mouse over the border tiles creates in some places more of these artefacts (like in the nord and west borders)

(I'm using xBRZ + NN as scaling method.)

(Reproduced on Archlinux)
Release: 1.13.6+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-13**

**shiki added attachment:** [borders.jpg](http://gna.org/bugs/download.php?file_id=29880)

**Comment by jostephd** [comment]
@sevu @Wedge009 How to reproduce? I enabled water animation, set xBRZ+NN, pressed `0` to zoom out to 50%, moved the mouse around and saw no problem. I tested in HttT 19c, I manually enabled shroud. What scenario do you test in? Does the problem happen in master today?

**Comment by Wedge009** [comment]
Perhaps not as big of a problem with fog, but I notice it with shroud. The key difference, I think, is to zoom in rather than out. I just reconfirmed on 1.14.9 release. I think it's possibly an artefact of the nature of xBRZ + NN.

**Comment by jostephd** [comment]
I still can't reproduce it. Could you state for the record what scenario you see this in?

**Comment by Wedge009** [comment]
The same one you said before: HttT 19c, with xBRZ+NN. I switched to shroud instead of fog and zoomed in instead of out. Artefacts appear in between the black shroud hexes nearest to the visible area, similar to the original image posted above.

**Comment by jostephd** [comment]
Still can't reproduce (I tested master). :thinking:

**Comment by Wedge009** [comment]
Reconfirmed for Linux master...

**Comment by Wedge009** [comment]
Given the conversation in #318 and the commits mentioned there, master (1.15.2+dev) no longer allows for xBRZ scaling and therefore this issue no longer occurs.
