### ISSUE TITLE
Translation mark _ in text key breaks event with [animate_unit] (GNA #25625)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1639]
**[Original submission](https://gna.org/bugs/index.php?25625)** by zepko on 2017-03-24

A translatable text into the [animate_unit] tag breaks the event which includes [animate_unit].

How to reproduce:

Insert the following code in the middle of any event

```
[animate_unit]
    flag=attack
    [filter]
        id=your_unit
    [/filter]
    hits=yes
    text= _"Some text"
[/animate_unit]
```

When the event reaches this point, the following error is generated, the text is not displayed, and the next commands inside the event are skipped.

error scripting/lua: lua/wml/animate_unit.lua:94: bad argument #-2 to 'add' (string expected, got userdata)

stack traceback:

	[C]: in method 'add'
	lua/wml/animate_unit.lua:94: in upvalue 'add_animation'
	lua/wml/animate_unit.lua:112: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>

No error if the translation mark _ is removed, that is

text= "Some text"

(Reproduced on Linux)
Release: 1.13.7
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-26**

**celticminstrel changed status:** None -> Ready For Test

**Comment by CelticMinstrel** [comment]
Can anyone confirm this is fixed?

**Comment by CelticMinstrel** [comment]
Both myself and @Vultraz confirmed the fix.
