### ISSUE TITLE
Minimap reveals shroud prematurely when vision points are less than MP (GNA #25622)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1645]
**[Original submission](https://gna.org/bugs/index.php?25622)** by shiki on 2017-03-23

(Reproduced on Archlinux)
Release: 1.12 / 1.13.7+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-23**

**shiki wrote:**

> When a unit has more movement points than vision points, it is showing the shrouded area on the minimap too.
> 
> 
> 
> I think it is good that it's not revealing the shroud, but the minimap shouldn't do so either.
> 
> 
> 
> 
> 
> 
> 
> I submitted this to early, can someone adjust change the title?
> 
> (file #29900)

**shiki added attachment:** [minimap.png](http://gna.org/bugs/download.php?file_id=29900)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-23**

**shiki wrote:**

> Note: The unit has to be selected for this.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-23**

**wedge009 wrote:**

> How does a unit see more than it can move? I thought that is a standard game-play rule. Is this from a custom unit? The only time I can think that movement would be impaired is if an enemy is in your way, but the vision should be impaired too.
> 
> 
> 
> I did a quick check of the above scenario and found the mini-map followed the main map in its shroud-revealing behaviour.

**wedge009 changed title:** Minimap -> Minimap reveals shroud prematurely

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-24**

**shiki wrote:**

> It's the other way around, she can move more than she can see.
> 
> For the unit_type exists the movement key and the vision key. By default that is the same, I doubt that really somebody is using the vision key. In this case I gave her more moves with debug mode.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-24**

**wedge009 wrote:**

> Ah, debug mode thing. That's why I couldn't test it.
> 
> 
> 
> But yes, standard rule is movement # vision.

**Comment by sevu** [comment]
I just saw that this doesn't happen in 1.12

**Comment by CelticMinstrel** [comment]
We should try to get this fixed for 1.14.

**Comment by jostephd** [comment]
Submitted #2150

**Comment by jostephd** [comment]
An easy way to test this is by running 'wesnoth -t' and clicking on the Elvish Rider at (8,11).
