### ISSUE TITLE
Redraw issue when switching from/to fullscreen (GNA #25623)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1646]
**[Original submission](https://gna.org/bugs/index.php?25623)** by shiki on 2017-03-23

When switching from/to fullscreen my screen looks like this.

What is not visible on my screen - my mouse is on that checkbox. 

As soon as I move the mouse away from the "Full Screen" label, the screen is redrawn.

(Reproduced on All)
Release: 1.13.7+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-23**

**shiki added attachment:** [switching_fullscreen.png](http://gna.org/bugs/download.php?file_id=29901)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-24**

**wedge009 wrote:**

> Seems to be the way the dialogues are redrawn between switching screen modes via the preferences dialogue. Still a lot better with SDL2 than what we had in SDL1.
> 
> 
> 
> I usually use the Ctrl+F default hot-key for switching between window and full screen, so I never saw this minor artefact. Is it the same for you?

**wedge009 changed status:** None -> Confirmed

**wedge009 changed OS:** Archlinux KDE5 -> All

**wedge009 changed title:** switching from/to fullscreen -> Redraw issue when switching from/to fullscreen

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-24**

**shiki wrote:**

> With ctrl+F everything works fine, never used this before.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-03-24**

**wedge009 wrote:**

> At least we can say it's specific to the preferences dialogue, then.

**Comment by sevu** [comment]
While it looks strange for a moment when switching, the window is repainted afterwards. -> fixed

**Comment by Wedge009** [comment]
Agreed, testing on 1.14.0 (this was probably resolved ages ago), this artefact is briefly visible but at least there's an auto-redraw after the resizing now.
