### ISSUE TITLE
remove ai.synced_command(GNA #25633)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1649]
**[Original submission](https://gna.org/bugs/index.php?25633)** by gfgtdf on 2017-04-06

ai.synced_command is quite unsafe and can easily be used for cheating, we should remove it with some more resitricive function that only allows calling functions there were previously registered to all clients and not arbitary lua code.

(Reproduced on )
Release: 1.13
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by CelticMinstrel** [comment]
I've been wondering about this function. Does it do anything that wesnoth.synchronize_choice doesn't? I'm pretty unclear on how the two differ, but I suspect they're not quite the same somehow.

Pinging @mattsc since this is also related to AI.

**Comment by CelticMinstrel** [comment]
Looking through the list of synced command, I see `lua_ai` (the one that `ai.synced_command` sends and `debug_lua` which are essentially the same. Is the former really more dangerous than the latter for cheating? The only difference I can see is that it's silent, but the announcement sent by `debug_lua` doesn't exactly prevent the action from occurring, so...

**Comment by gfgtdf** [comment]
> but the announcement sent by `debug_lua` doesn't exactly prevent the action from occurring, so...

well but you know that your opponene thcates, just liek for :unit :gold etc commands.

>  think it needs a replacement of equivalent power before it can be replaced. What about exposing the synced command handlers to Lua so that Lua code can install additional ones?

Yes that's also what i had in mind, but i' unusre about where exactly these should be registered, (inside [ai] or in [scenario] or somehere else). I think that having to modify the [scenario] in order to make your ai work woudl be annyiing so we need some type of place that is somehow inside the ai code but still sycned/(sended over network)

**Comment by CelticMinstrel** [comment]
I don't think additional synced commands would be useful _only_ for AI. They could also be used within the `[do_command]` ActionWML, right? So, I had been assuming you'd register them with a `[lua]` tag at toplevel or in the `[scenario]`. Probably the latter, without calling dofile or require, in order to avoid breaking the distributability of replays.

**Comment by gfgtdf** [comment]
> I don't think additional synced commands would be useful _only_ for AI. They could also be used within the `[do_command]` ActionWML, right?

yes they could, but we coudl also support them in multiple aoruces like inside ai but also in scenario, one of the reasony why i'd want it to be supported independently form the scnario configs, is that one might want to choose the ai independently from the scenario in the mp staging  dialog.


Another idea i has was to ahev jut a [actionwml] command, that excuted its content (a single tag), and then the sycned code wodul need to whitelist all tag save that tey want to use later that way.

**Comment by CelticMinstrel** [comment]
Well, an "action_wml" synced command pretty much has the same problem as the "lua_ai" command which is that someone malicious could send it to achieve anything they want.

**Comment by gfgtdf** [comment]
> Well, an "action_wml" synced command pretty much has the same problem as the "lua_ai" command which is that someone malicious could send it to achieve anything they want.

well that's why i said 

> and then the sycned code would need to whitelist all tag that are mp save that they want to use later that way.

but i've changes my min i don't think we need additional sycned commands, just use [fire_event] ad support paremters ( queued_event::data ) in [fire_event].

**Comment by gfgtdf** [comment]
accdently closed this.

**Comment by CelticMinstrel** [comment]
Hmm, but that doesn't really do anything about keeping it independent from a scenario, since the events that are to be fired then need to be registered in a synced way as well.

**Comment by gfgtdf** [comment]
> Hmm, but that doesn't really do anything about keeping it independent from a scenario, since the events that are to be fired then need to be registered in a synced way as well.

we coudl mayb add some way for ai code to register (copy then in the scenario) events .

**Comment by CelticMinstrel** [comment]
Well, I did have the idea of accepting `[event]` inside `[ai]` (which could be used when making a custom AI available in MP Staging). I'd also expect such events to default to `first_time_only=no`. That wouldn't help for Micro AIs though; but Micro AIs are registered through a synced event anyway (often start or prestart), so I guess they could register their needed events through the Lua interface. It also wouldn't help for extra candidate actions.

**Comment by CelticMinstrel** [comment]
Reopening this as a reminder that the implementation is neither finished nor finalized.

It can also be assigned to me. Don't think I can do that from my phone.

**Comment by CelticMinstrel** [comment]
(To clarify, I intend to work on it this weekend. Probably even tonight.)

**Comment by Vultraz** [comment]
Eh? Not finished or finalized?

**Comment by CelticMinstrel** [comment]
At the very least we need to fix the rabbits MicroAI; I might want to do some other tweaks too.

**Comment by gfgtdf** [comment]
@CelticMinstrel please close this when you consider it finished.
