### ISSUE TITLE
[remove_object] heals units with amla (GNA #25639)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1651]
**[Original submission](https://gna.org/bugs/index.php?25639)** by gfgtdf on 2017-04-08

to reprocue:

1) Let unit1 be a unit with id=unit1,x=1,y=1,hitpoints=1 and it has already got one default amla.

2) add a dummy object (:lua wesnoth.get_unit(1,1):add_modification("object", {id = "a"}))

3) remove the object (:lua lua wesnoth.wml_actions.remove_object { object_id = "a"})

observed behaviour: the unit was fully healed

expected behviour: the unit shoudl still have one hp.

The reason why it fully heals is that the default amla has a heal_full=yes in it, and remove_object reapplies all modifications.

Proposed solution: the engine shodul somehow know that we are just reapplying the effect and skip the healing then.

(Reproduced on )
Release: 1.13.7
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-08**

**celticminstrel wrote:**

> I doubt this is a bug with [remove_object]. If the situation is as you suggest, it should also affect objects with an expiry, such as the "stun" weapon special. I don't know of any good way to fix this.

**Comment by CelticMinstrel** [comment]
I guess some key could be added to `[remove_object]` that makes it save certain quantities and restore them after the object was removed? Would have to decide exactly which quantities to save though. And that wouldn't help with the "stun" special, which presumably also shouldn't heal someone when it wears off.

Should we add a flag in `add_modification` to indicate that it's a rebuild and thus should only apply the non-transient changes? I'm not even sure that would be sufficient though — what if its hitpoints were 15/20 before removing the object, but the base unit has max hitpoints 12 and one of the modifications is what increased it to 20?

**Comment by CelticMinstrel** [comment]
Fixed by #2029 

I'm wondering though if there are other cases where a similar problem could arise. Consider for example a modification that changes the type of the unit. That unit then levels up. What happens in that case?
