### ISSUE TITLE
OOS when oberving a mp game (GNA #25640)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1652]
**[Original submission](https://gna.org/bugs/index.php?25640)** by gfgtdf on 2017-04-09

when you join a running mp game to observe you get OOS in >50% of cases, it seems like the initial [replay] (which contains all the moves that were done before you joined the game) is somhow skipped/forgotten. Whihc obiously reults in later moves not making any sense -> OOS.

(Reproduced on windows)
Release: 1.13.7
Priority: 5 - Normal
Severity: 5 - Blocker

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-16**

**gfgtdf wrote:**

> i just tested at 4f50559 and it now happens to me every time (not every other time like when i tested at 1.13.7)

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/commit/7db2b7c31e56dfb52f7e6139336b0d5088ed2b50
