### ISSUE TITLE
Turning on/off standing animations doesn't work correctly (GNA #25641)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1653]
**[Original submission](https://gna.org/bugs/index.php?25641)** by beetlenaut on 2017-04-10

Go to display preferences, and deselect "Show unit standing animations." When you return to the game, the animations continue playing. They don't actually stop until the unit is animated again. That means you can stop them by just selecting a unit, but you would still have to click on each unit to have the effect you wanted. Turning the option back on works the same way.

(Reproduced on All)
Release: 1.12.6+dev
Priority: 5 - Normal
Severity: 2 - Minor

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-12**

**wedge009 changed status:** None -> Confirmed

**wedge009 changed OS:** Linux -> All

**wedge009 wrote:**

> Reverse is also true - re-enable animations and the units won't move until clicked or reloading.
> 
> 
> 
> Noting that this is an issue in current release branch as well. Have not checked how far back it goes. Maybe most people don't use this feature and so it hasn't been reported till now.

**wedge009 changed release:** 1.13.7+dev -> 1.12.6+dev

**Comment by universecoder** [comment]
I am trying to solve this.
