### ISSUE TITLE
larger window for paths listing (GNA #25643)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1655]
**[Original submission](https://gna.org/bugs/index.php?25643)** by shiki on 2017-04-10

The window which appears when clicking the [i] on the titlescreen could be a bit wider. With the current length I assume that most paths won't be displayed fully.

A path length like this should be displayed without shortening:

/home/username/.local/share/wesnoth/1.13/data/add-ons/

Shortening the paths for the standard locations doesn't make sense, this windows exists to make things easier, not complicated.

(Reproduced on Linux)
Release: 1.13.7+dev
Priority: 5 - Normal
Severity: 4 - Important

**Comment by Wedge009** [comment]
Agreed - and as with #1665 I see a lot of difficult to navigate scroll-bars with non-English translations.

**Comment by Wedge009** [comment]
#8803 makes the dialogue for the paths substantially wider, although there will still be some truncation of the text. I think it's okay to close but if @sevu or others think there should still be more room for the paths, then feel free to re-open.

**Comment by babaissarkar** [comment]
> #8803 makes the dialogue for the paths substantially wider, although there will still be some truncation of the text. I think it's okay to close but if @sevu or others think there should still be more room for the paths, then feel free to re-open.

Note that the text boxes are now _uneditable_ instead of inactive, so you can click on them and a cursor will appear, which allows to move around the text.

**Comment by Wedge009** [comment]
I noticed that too, though I didn't know that wasn't possible for the previous iteration in 1.18. So that's another improvement point!

**Comment by babaissarkar** [comment]
> I noticed that too, though I didn't know that wasn't possible for the previous iteration in 1.18. So that's another improvement point!

It was listed as a TODO in [the NotSoEasyCoding page in the wiki](https://wiki.wesnoth.org/index.php?title=NotSoEasyCoding&oldid=70761#Multi-line_textbox.2C_single-line_textbox_improvements).
