### ISSUE TITLE
MP starting gold slider doesn't work properly with arrow keys (GNA #25644)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1656]
**[Original submission](https://gna.org/bugs/index.php?25644)** by jesse597 on 2017-04-10

To replicate, start a local multiplayer game, click OK, and click Create Game. A few different cases happen on the gold slider for both players:

-If the value of the slider is greater than 625 and any key is pressed, the slider will move to 75

-If the slider is between 75 and 625 inclusive and any key is pressed, the slider will move to 50

-If the slider is set to 50, pressing left or down sets the slider to 25, but pressing right or up does nothing

Additionally, a mouse click on the slider is treated as a right or up keystroke

(Reproduced on Windows 10)
Release: 1.13.6+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-10**

**jesse597 wrote:**

> Fixed by changing the starting gold slider's step size to 1.
> 
> https://github.com/swe-TeamRed/wesnoth/commit/0b93dc82f2ceadf531c4f3fe2e9841fc38cf24a2

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-10**

**gfgtdf wrote:**

> > Fixed by changing the starting gold slider's step size to 1. 
> 
> 
> 
> hm ye but it doesnt fix the underlying bug, since other slider which have a step differnt than one are still broken.
> 
> 
> 
> 
> 
> this is actuall a known bug and the actual problem here lies in https://github.com/wesnoth/wesnoth/blob/master/src/gui/widgets/scrollbar.cpp . this class has 2 different teams of step sides
> 
> 
> 
> 1) the 'step size' as its used here 
> 
> 2) the size in pixes beween 2 steps
> 
> 
> 
> and it rather hard to track which paremters are actual taken in 'steps' 'pixels' or 'values' so moslikely somehere there a function that passes a value to another function expects use diffetnt units as a parermter. To make it more colicated it also supposts some concept of 'visible items' (since it was originally written for scorllbars) and it unclear how that should behave if step_size is not 1.

**Comment by gfgtdf** [comment]
assigning to me to remmber it, doesnt mean i am curently working on it.
