### ISSUE TITLE
memleak when broken addon is installed (GNA #25650)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1657]
**[Original submission](https://gna.org/bugs/index.php?25650)** by matthiaskrgr on 2017-04-12

If there is an addon installed that causes an error on game start and the error-notification pops up there seems to be a memleak caused by this.

(Reproduced on linux)
Release: git
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by Vultraz** [comment]
@matthiaskrgr any way you could verify if this is still the case? I've since done refactoring to the preprocessor and everything should be using smart pointers now.

**Comment by matthiaskrgr** [comment]
Ok I manually broke one of the addons and I no longer could reproduce any leak. :)

**Comment by Vultraz** [comment]
Yay!
