### ISSUE TITLE
[animate_unit] add error (GNA #25657)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1659]
**[Original submission](https://gna.org/bugs/index.php?25657)** by sigurdfdragon on 2017-04-13

The following occurs with the add-on Ashen Hearts in S8

It does not occur with the same version of the add-on in 1.12.6

20170413 21:05:27 error scripting/lua: lua/wml/animate_unit.lua:95: bad argument #-2 to 'add' (target must be adjacent to the animated unit)

stack traceback:

	[C]: in method 'add'

	lua/wml/animate_unit.lua:95: in upvalue 'add_animation'

	lua/wml/animate_unit.lua:113: in local 'cmd'

	lua/wml-utils.lua:145: in field 'handle_event_commands'

	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>

The error is triggered by line 844 in 08_Ilrandh.cfg

To reproduce, load the prepared save file and move the unit Khazern to the side 2 leader at the top of the map.

(Reproduced on Win 7 x64)
Release: 1.13.7+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-13**

**sigurdfdragon added attachment:** [AH-Ilrandh_Turn_1_Animate_Unit_Bug.gz](http://gna.org/bugs/download.php?file_id=29930)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-13**

**sigurdfdragon wrote:**

> version 1.6.0 of Ashen Hearts on the add-on server

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-17**

**vultraz wrote:**

> https://github.com/wesnoth/wesnoth/commit/2b58109133f35701ce8f3a0dd4f9a31ec8cac0a9

**vultraz changed status:** None -> Ready For Test

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-17**

**sigurdfdragon wrote:**

> The very first animation in the sequence fires now, and I think the bug is fixed.
> 
> 
> 
> It still throws the same error on the next one on line 875, but I think this is due to faulty wml here, (the animated unit & facing have the same x,y) which was exposed by the animate lua conversion making the animate add more strict. (the code worked in 1.12) I'm not sure if this is something that should be fixed.
> 
> 
> 
> 20170417 16:25:27 error scripting/lua: lua/wml/animate_unit.lua:95: bad argument #-2 to 'add' (target must be adjacent to the animated unit)
> 
> stack traceback:
> 
> 	[C]: in method 'add'
> 
> 	lua/wml/animate_unit.lua:95: in upvalue 'add_animation'
> 
> 	lua/wml/animate_unit.lua:113: in local 'cmd'
> 
> 	lua/wml-utils.lua:145: in field 'handle_event_commands'
> 
> 	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
> 
> 
> 
> 
> 
> This one looks to be triggered by

**Comment by CelticMinstrel** [comment]
@sigurdfdragon Is this still an issue?

**Comment by sigurdfdragon** [comment]
Only if we think stricter wml is a problem. I'm going with 'no' here.

**Comment by CelticMinstrel** [comment]
What's the WML that triggers the error, then?

**Comment by sigurdfdragon** [comment]
The WML is below.
The filtered unit (id of Menor IV) location is the same as the coordinates being input in [facing].
This worked in 1.12, but now throws:
error scripting/lua: lua/wml/animate_unit.lua:95: bad argument #-2 to 'add' (target must be adjacent to the animated unit)
which I think is legit, and thus indicating incorrect wml in the add-on


		[animate_unit]
			flag=attack
			[filter]
				id=Menor IV
			[/filter]
			hits=yes
			
			[primary_attack]
				range=ranged
			[/primary_attack]
			
			[facing]
				x,y=$menor.x,$menor.y
			[/facing]
		[/animate_unit]

**Comment by CelticMinstrel** [comment]
Ah, I see. Yes, as I understand, `[facing]` is supposed to match a hex other than the one the unit is currently standing on.

**Comment by Vultraz** [comment]
I agree, this stricter WML is a good thing. Closing.

**Comment by CelticMinstrel** [comment]
I also added a more accurate error message for this specific case in e2ebfa3.
