### ISSUE TITLE
Webpage - checksum and link checksum file (GNA #25658)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1660]
**[Original submission](https://gna.org/bugs/index.php?25658)** by damark on 2017-04-14

The SHA256 checksum on the website for the Version 1.13.7 for macOS 10.7 or later is not identical with the checksum computed on my Mac. I am using OS 10.11.6 and the command /usr/bin/shasum

My checksum is "254045c20944ffa88b589565e4eb1bd2da8f2b62  Wesnoth_1.13.7.dmg"

The *.dmg file can be opened. So I assume the download is correct. 

The link to download the checksum file for Version 1.13.7 for macOS 10.7 or later is broken. The browser reports:

"The requested URL /releases/Wesnoth_1.13.7.dmg.sha256 was not found on this server."

(Reproduced on macOS)
Release: 1.13.7
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-15**

**vultraz changed status:** None -> Confirmed

**vultraz wrote:**

> The checksum issue is know. Despite us doing a thorough comparison of the package before upload and the one provided by SourceForge and finding them identical, the hashes still don't match for some reason.
> 
> 
> 
> As for the broken checksum files, we'll fix the links. Thanks for pointing that out :)

**Comment by Vultraz** [comment]
1.13.7 is no longer the current release, and no checksum issues have been reported for later ones.
