### ISSUE TITLE
Mixed factions and Mac and PC cannot play together (GNA #25659)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1661]
**[Original submission](https://gna.org/bugs/index.php?25659)** by damark on 2017-04-15

These problems may be related to the same problem.

Starting a local multiplayer game (for example "4p - Hamlets") everything can be mixed up. In this example I am in Team North but my leader is in the castel together with the first leader of team south. My leader is an ork and I recruit dwarfs. My opponent in the south is a dwarf and recruits khalifate figures.

Starting earlier and also a problem in 1.12.6 is that a local multiplayer game does not work if you play with Mac and PC. The problem seems to be on the Mac side because PC and Linux is no problem.

The problem is similar. While the fractions are consistent the player on the Mac side owns another castle compared to the PC side and the figures move different on the two platforms. After some turns the games on the platform differ too much and it is not possible to make the next turn.

I add some screenshots to show the problem with the local multiplayer game.

(Reproduced on OS X, 10.11.6)
Release: 1.13.7
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-15**

**damark added attachment:** [mp-bug1.jpg](http://gna.org/bugs/download.php?file_id=29931)

**damark added attachment:** [mp-bug2.jpg](http://gna.org/bugs/download.php?file_id=29932)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-15**

**damark wrote:**

> One screenshot was missing ...
> 
> (file #29934)

**damark added attachment:** [mp-bug3.jpg](http://gna.org/bugs/download.php?file_id=29934)

**Comment by Wedge009** [comment]
This surprises me as I wouldn't think that OS should cause problems in MP. Is it still the case that macOS players can't play properly with other Wesnoth players? I don't use macs so I can't test for myself.

**Comment by soliton-** [comment]
Might actually be an intermittent issue with the shuffle sides feature.

**Comment by gfgtdf** [comment]
> Might actually be an intermittent issue with the shuffle sides feature.

Didn't we fix that? So can this be closed?

**Comment by Wedge009** [comment]
Two years since last discussion. I'll close this and see if it prompts any response from concerned parties. (:
