### ISSUE TITLE
linear scaling option - artefacts for red ellipses, while blue ones are fine (GNA #25660)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1662]
**[Original submission](https://gna.org/bugs/index.php?25660)** by shiki on 2017-04-15

Have a look at the picture. The game is scaled up with, it think it was ctrl + ´.

While the blue ellipses are looking fine, there are strange pixels appearing on the red ones.

Same for xbrz+linear option.

Disabling ellipses doesn't show the pixels anymore.

The strange thing is, it only happens for the red ellipses, not the blue.

(Reproduced on Archlinux)
Release: 1.13.7+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-15**

**shiki added attachment:** [red_circles.png](http://gna.org/bugs/download.php?file_id=29933)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-15**

**vultraz wrote:**

> Yeah, this is a bug with linear scaling, same one as https://gna.org/bugs/index.php?25004. It doesn't happen with xBRZ + NN, so I recommend using that instead (and it's the recommended setting).

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-17**

**shiki wrote:**

> Oh, now I understand what the comments there meant.
> 
> 
> 
> Maybe it's time to fix that one, I heard a few times of bugs which could be or are related to that one.
> 
> 
> 
> Personally I liked the xbrz+linear option more. (or was it just linear)

**Comment by Wedge009** [comment]
Related #1570

**Comment by sevu** [comment]
Looks good now.

**Comment by Wedge009** [comment]
While the Help portraits from #1570 seem okay now, I'm not sure if the ellipses are. I took this with linear scaling and maximum zoom - note the Mage of Light's halo also has artefacts.

![linear](https://user-images.githubusercontent.com/13679322/30506347-87686ce8-9abe-11e7-81ec-8043982aebbb.png)

@sevu How does it look for you?

**Comment by sevu** [comment]
My bad, I didn't use linear scaling.
Looks like in your case.

**Comment by Vultraz** [comment]
Honestly, I'm just marking this won't fix. It's not worth the effort, given that we're switching to accelerated rendering for 1.15 and will most likely remove linear scaling.

**Comment by CelticMinstrel** [comment]
I wonder if it could even be a bug in the linear scaling implementation... meaning that merely switching to OpenGL's built-in linear scaling could be enough to fix it...
