### ISSUE TITLE
Petrified leader does not lose the game and thus becomes invincible. Possible on official map! (GNA #25672)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1666]
**[Original submission](https://gna.org/bugs/index.php?25672)** by tobefree on 2017-04-22

This issue can be reproduced on an official map, "Silverhead Crossing", with default settings in the default era.

Said map has a hidden surprise tentacle in the upper left corner with 500 HP and a devastating 100-1 petrifying arcane ranged attack. Surviving the attack, which is possible with a strong enough leader, makes the attacker end up with a petrified, INVINCIBLE leader.

To try it, I used an Inferno Drake leader at day, when the attack is reduced to 75-1 (96-1 because of arcane vulnerability). I levelled it up until it had 100 HP and was able to survive the attack, then attacked the hidden tentacle and had a petrified king.

Petrified units can not be attacked. The petrified leader is suddenly invincible. If the petrified leader can recruit units, it might become even more weird.

Of course, this is probably more likely to happen in campaigns and third party maps, but my idea came from an official map and it works there.

The best solution is to make the player lose the game instantly when the king is petrified. Or, if you don't like that, make the player lose the game when all his units are petrified.

(Reproduced on any)
Release: 1.12.6
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-22**

**tobefree added attachment:** [wesnoth-leader-petrification-small.mp4](http://gna.org/bugs/download.php?file_id=29940)

**tobefree added attachment:** [14500moves_2S_�_Die_Furt_am_Silberkopf_Aufzeichnung_abspielen.bz2](http://gna.org/bugs/download.php?file_id=29939)

**tobefree added attachment:** [wesnoth-petrification-bug-tobefree-lowquality.jpg](http://gna.org/bugs/download.php?file_id=29941)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-22**

**tobefree wrote:**

> Detailled bug description video with text:
> 
> 
> 
> https://www.youtube.com/watch?v=Y9JccDwAjdw

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-22**

**gfgtdf wrote:**

> hmm i think we should just remove that Petrified weapon sepcial there in that scenario.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-22**

**tobefree wrote:**

> That would quickly solve the issue for official maps, but it might still be nice to properly fix this for user-created scenarios and campaigns.

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-23**

**gfgtdf wrote:**

> one problem is that it's just not that easy: petrification is mainly used in campaigns in and often the players are often given some option to unpetryfy their units, and in that case your proposal would make the player loose even if he could still win this.
> 
> 
> 
> Also even with your proposal it doesn't fix all problams casues by pertyfying: For example you can use petryfyaing to eternally block the path betwen two teams (specially easy to do on dungeon scnearios) if threre is no way to undo the pretyfying. Also the enemy could petrify other units that are not your leader but necessary to meed a custom scenario objective.
> 
> 
> 
> 
> 
> So i really think it better to let the sceanrio designer hande this in their scenario wml on a case-by-case basus

**Comment by ToBeFree** [comment]
![wesnoth-petrification-bug-tobefree-lowquality](https://cloud.githubusercontent.com/assets/1029811/25829361/d0657d2a-3455-11e7-8773-59964fbfe6e0.jpg)

**Comment by CelticMinstrel** [comment]
@ToBeFree Is that a repost of the image linked as an attachment on GNA, or is it a new screenshot?

**Comment by CelticMinstrel** [comment]
Just for the record, I have confirmed that it is indeed a repost and updated the link in the first comment to point to it.

**Comment by ToBeFree** [comment]
Oh, yes, you're right. I originally wanted to re-upload all the attachments, but uploading these didn't seem to work for me. Now all the files seem to be uploaded to GitHub, I guess a developer (you?) did that. Thanks! :)

**Comment by CelticMinstrel** [comment]
Yes, I re-uploaded them all. I had to convert some from jp2->jpg or bz1->gz, but they're at least all on GitHub now.

**Comment by sigurdfdragon** [comment]
Fixed in https://github.com/wesnoth/wesnoth/commit/3e9515c1d4a1b68d355959f3159442e0ed05003c
