### ISSUE TITLE
Walking corpse bat sometimes shows humanoid animation (GNA #25673)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1667]
**[Original submission](https://gna.org/bugs/index.php?25673)** by gnombat on 2017-04-23

See the attached screenshot (from the first scenario of Secrets of the Ancients).  It's actually a walking corpse bat, but it sometimes turns into a humanoid while attacking.

(Reproduced on All)
Release: 1.13.7
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-23**

**gnombat added attachment:** [bat.png](http://gna.org/bugs/download.php?file_id=29943)

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-23**

**sigurdfdragon wrote:**

> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-25**

**vultraz wrote:**

> Cannot confirm :/

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-28**

**sigurdfdragon wrote:**

> This was caused by the bat variant only having two attack_anim, but inheriting three from the base unit. Thus, the third tag wasn't overwritten and still active.
> 
> 
> 
> I submitted a fix at 
> 
> https://github.com/wesnoth/wesnoth/pull/1004

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-28**

**sigurdfdragon wrote:**

> Also note the bug was only visible if you attacked in a direction other than n or s, and also was slightly intermittent

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-28**

**wedge009 wrote:**

> Confirmed on master (e7cf8730) on both Windows and Linux.
> 
> 
> 
> Looking through the images and config files, I don't see anything immediately obviously wrong. But I do note zookeeper added doofus' walking corpse images in 18f866e on 18th April, just a couple of weeks ago. Maybe something changed there that shouldn't have? I can't see what, though. ):

**wedge009 changed OS:** Windows -> All

**wedge009 changed status:** None -> Confirmed

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-28**

**wedge009 wrote:**

> Bah, I didn't see the updates. That sounds reasonable to me. I don't know if the PR is the right way to go about fixing it.

**Comment by CelticMinstrel** [comment]
Fixed in #1004
