### ISSUE TITLE
-t parameter for wesnoth executable (GNA #25679)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1670]
**[Original submission](https://gna.org/bugs/index.php?25679)** by shiki on 2017-04-27

While I wanted to add a manpage entry for -tmicro_ai_test I realized it's actually only making use of the -t option. But either -t is not documented correctly or not implemented correctly.

Small extract from the manpage:

-t, --test [scenario_id]

runs  the game in a small test scenario. The scenario should be one defined with a [test] WML tag. The default is "test". Implies --nogui.

```

So, wesnoth -t starts the default test scenario.

wesnoth -t test should be the same, but actually it's wesnoth -ttest

Long option mode isn't working either way, only without arguments.

```

Since usually there is a space between the option and the argument and long option mode isn't working with arguments I'd argue to change rather that than the documentation.

(Reproduced on Linux)
Release: 1.13.7+dev
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by CelticMinstrel** [comment]
I think this is related to the fact that positional arguments are interpreted as the userdata directory. For long options you need `--test=test`.

**Comment by luther9** [comment]
The problem seems to be that the option takes an optional argument, which makes it ambiguous whether the next arg in the command line is a stand-alone argument or an argument to the option. Maybe we could change the man page to make it more clear how such options should be invoked?
