### ISSUE TITLE
Hotkey preferences give incorrect feedback when updating hotkeys (GNA #25683)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1672]
**[Original submission](https://gna.org/bugs/index.php?25683)** by aginor on 2017-04-29

The hotkey preferences dialog gives wrong feedback when binding a previously unbound hotkey.

It also displays incorrect feedback on occasion when assigning multiple hotkeys in a row, especially if it's reassigning existing hotkeys.

(Reproduced on Any)
Release: 1.13.7
Priority: 5 - Normal
Severity: 3 - Normal

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-04-30**

**vultraz wrote:**

> https://github.com/wesnoth/wesnoth/commit/7e1caca082dca2930a55deebe4e2a89349ff06af
> 
> 
> 
> Attempted to fix here, and it removes the "bound to unrecognized command" prompt if re-assigning multiple times, but I'm not sure it's the right fix.
> 
> 
> 
> That's probably the second issue you described. Not sure what you meant by "when binding a previously unbound hotkey". I saw no errors there.
> 
> 
> 
> Let me know if this is the wrong method.

**vultraz changed status:** None -> Ready For Test

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-05-01**

**sigurdfdragon wrote:**

> I'm still getting a form of incorrect feedback after
> 
> https://github.com/wesnoth/wesnoth/commit/7e1caca082dca2930a55deebe4e2a89349ff06af
> 
> 
> 
> After a quit and relaunch cycle, the hotkey asignment indicates a something like:
> 
>  ,'
> 
> 
> 
> when I try to reassign ' to a command
> 
> 
> 
> see also https://gna.org/bugs/index.php?25683

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-05-01**

**sigurdfdragon wrote:**

> correct link: https://gna.org/bugs/?25687

**Comment by Vultraz** [comment]
Just checking, was that before or after #1016 ?

**Comment by Vultraz** [comment]
@sigurdfdragon that is, I'm pretty sure this was also fixed by #1016 - is that correct?

**Comment by sigurdfdragon** [comment]
yes, it was fixed with https://github.com/wesnoth/wesnoth/issues/1016
