### ISSUE TITLE
ingame chat doesn't work (GNA #25686)

### ISSUE THREAD

**Issue by wesnoth-bugs** [wesnoth/wesnoth#1675]
**[Original submission](https://gna.org/bugs/index.php?25686)** by gfgtdf on 2017-05-01

chat messages asend by the host do not arrive at other sides.

(Reproduced on windows)
Release: 1.13.7
Priority: 7 - High
Severity: 5 - Blocker

**Comment by wesnoth-bugs** [comment]
**Modified on 2017-05-01**

**gfgtdf changed title:** chat doesn\'t work -> ingame chat doesn't work

**Comment by gfgtdf** [comment]
I tested with vultraz and it is a bug on receiving side that seems to be resolved in master.
