### ISSUE TITLE
Editor auto-saves all maps when reloading (with F5)

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#1677]
This is dangerously surprising behaviour and can result in loss of data.

**Comment by gfgtdf** [comment]
as seen here it does explicitly does that https://github.com/wesnoth/wesnoth/blob/1.13.8/src/editor/controller/editor_controller.cpp#L732. Probably becasue it restarts the editor which then reloads the map from disk

**Comment by CelticMinstrel** [comment]
Yes, I know it explicitly does that, but it shouldn't. It should do one of the following:

1) Treat it as a normal editor quit, by putting up a confirmation dialog for any unsaved maps.
2) Store the maps at a higher scope so that the editor can be reloaded without destroying the maps.

**Comment by gfgtdf** [comment]
I guess it could also just store them under a different name or some temp folder

**Comment by CelticMinstrel** [comment]
Currently the autosave file becomes the primary file (for unsaved maps), which basically means that it would save to that file if you later click save, and also that it shows in the editor as having been saved. If you can change it so that a map can have both an autosave file and an official location, then yeah, that would work too.

**Comment by Vultraz** [comment]
This is an issue, but not a blocker. Removing the label.

**Comment by Vultraz** [comment]
Moving to 1.14.1 since new strings are required.

**Comment by gfgtdf** [comment]
> since new strings are required.

why that?

**Comment by CelticMinstrel** [comment]
Whether new strings are required depends on the implementation. In particular, the _ideal_ implementation does _not_ require any new strings.

**Comment by Wedge009** [comment]
Work-around should be straightforward. Re-implementing the reload... probably not.

**Comment by CelticMinstrel** [comment]
This behaviour was removed in #8903.
