### ISSUE TITLE
test scenario: lua error (silly dance)

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#1678]
Wesnoth 45c1dec

````wesnoth -t````
Move unit on "The silly dance" label (14,9)
=>

````
20170510 00:00:45 error scripting/lua: lua/wml/animate_unit.lua:89: bad argument #2 to 'add' (string expected, got nil)
stack traceback:
	[C]: in method 'add'
	lua/wml/animate_unit.lua:89: in upvalue 'add_animation'
	lua/wml/animate_unit.lua:107: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
````

**Comment by Vultraz** [comment]
The `[animate_unit]` tag in question is empty, so this is to be expected, I think.

**Comment by CelticMinstrel** [comment]
It should yield a WML error instead of a Lua error, though. In other words, the `[animate_unit]` implementation should check for this.

**Comment by Vultraz** [comment]
Could you add that, then?

**Comment by Vultraz** [comment]
Though TBH I'm wondering what in hell that code was supposed to do in the first place.. was it a placeholder? Supposed to fire a default anim?

**Comment by CelticMinstrel** [comment]
I haven't looked at the code, so I don't know.

**Comment by Vultraz** [comment]
It's literally this:

```    [event]
        name="moveto"
        first_time_only=no
        [filter]
            x,y=14,9
        [/filter]
        [animate_unit]
        [/animate_unit]
        [allow_undo]
        [/allow_undo]
    [/event]```

**Comment by CelticMinstrel** [comment]
Seems like it must be intentional. Maybe @ln-zookeeper would have some idea? Or we could use blame to find who added that and try to ask them.
