### ISSUE TITLE
[kill] doesn't seem to handle being launched in an event

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#1683]
As of: https://github.com/wesnoth/wesnoth/commit/e2ebfa31f6b20eef25c7f45adc40444ceb25b31e ,

[kill] throws an error, when launched from an event in some cases. Seems likely it was introduced in the  port of [kill] to lua

Two ways to reproduce:
1. Launch THoT, switch to 09_Forbidden_Forest, Have a mage pick up staff at 22,16 and have mage get killed by an enemy.
error is:
20170510 01:13:02 error scripting/lua: lua/wml/kill.lua:30: attempt to index a nil value (field 'event')
stack traceback:
	lua/wml/kill.lua:30: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>

2. Use add-on GUI Debug Tools -> Side Debug -> Kill Units
error is:
20170510 00:57:48 error scripting/lua: lua/wml/kill.lua:30: attempt to index a nil value (field 'event')
stack traceback:
	lua/wml/kill.lua:30: in field 'kill'
	~add-ons/Gui_Debug_Tools/lua/side_utils.lua:37: in field 'kill_units'
	~add-ons/Gui_Debug_Tools/lua/side_debug.lua:795: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>

**Comment by CelticMinstrel** [comment]
Hmm, so `wesnoth.current.event` is nil, but as far as I know that shouldn't happen during an event firing...

**Comment by Vultraz** [comment]
Accidentally closed with that commit, though I'm pretty sure it's the right one.

**Comment by sigurdfdragon** [comment]
confirmed, both cases above are working now. thanks
