### ISSUE TITLE
test scenario: "load and exec lua code" broken

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#1690]
wesnoth 41d0a6b

wesnoth -t
right click on map and select "Reload and execute Lua code"
=>
````
20170513 00:39:52 error scripting/lua: [string " wesnoth.dofile("lua/code.lua").main() "]:1: bad argument #-1 to 'dofile' (file not found)
stack traceback:
	[C]: in field 'dofile'
	[string " wesnoth.dofile("lua/code.lua").main() "]:1: in local 'bytecode'
	lua/wml-tags.lua:265: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
````

**Comment by CelticMinstrel** [comment]
I think this is intended, actually. Based on the comments in the scenario config, it seems like you're supposed to create the code.lua file before running this.

Mind you, there's likely a better way to handle it...

**Comment by Wedge009** [comment]
Closing this since CelMin marked it as invalid, and a helpful error message has since been merged.
