### ISSUE TITLE
domain forum.wesnoth.org is not secure (problem with TLS certificate)

### ISSUE THREAD

**Issue by PSLLSP** [wesnoth/wesnoth#1700]
My WWW browser, that is Chromium (58.0.3029.96, running on Ubuntu 16.04) report that https://forum.wesnoth.org, is not secure. I see only two TLS certificates in the chain of trust.
ERROR is NET::ERR_CERT_COMMON_NAME_INVALID (Certificate name mismatch) 

On the other side, https://www.wesnoth.org is secure, it has three TLS certificates in the chain of trust.

You can verify it here:

<https://www.ssllabs.com/ssltest/analyze.html?d=forum.wesnoth.org>
<https://www.ssllabs.com/ssltest/analyze.html?d=www.wesnoth.org>

**Comment by jyrkive** [comment]
https://forums.wesnoth.org/ (with an S) works fine. Why do you try to access forum.wesnoth.org?

**Comment by PSLLSP** [comment]
I followed a link from Google... I asked for "wesnoth sound usb"

**Comment by jyrkive** [comment]
Huh. Indeed, Google links to such a subdomain.

**Comment by shikadilord** [comment]
forums.wesnoth.org is the canonical domain name. forum.wesnoth.org may be floating around from obsolete or mistyped links but it's not canonical, hence it wasn't included in the certificate. Not sure if it's really worth keeping it.

**Comment by rhonda** [comment]
forum.wesnoth.org has been added to the certificate.
