### ISSUE TITLE
No audio to my USB speakers (Ubuntu)

### ISSUE THREAD

**Issue by PSLLSP** [wesnoth/wesnoth#1701]
Ubuntu 16.04 i386, Wesnoth distributed with Ubuntu (1.12).

I have USB speakers and I use PulseAudio.

Generally, my USB speakers work good but Wesnoth doesn't work with this configuration, there are no sounds, no music in Wesnoth. Could you check why your design is limited to internal sound card?

I guess the same problem could be with USB headphones, Bluetooth headphones, etc.

**Comment by pydsigner** [comment]
We need more information about your setup. Wesnoth does not select a sound
card itself, and I've used Wesnoth with a number of different pulseaudio
configurations successfully​ myself. Have you checked that sound is enabled
in Wesnoth? Does Wesnoth appear in the pulseaudio program list? Is it muted
or set specifically to an incorrect output?

**Comment by Wedge009** [comment]
Might be a stupid question but nothing can be assumed - does sound work on the USB speakers for other programs besides Wesnoth? What is selected as the default or highest priority output device in your OS?

Labelling this Linux if only because this one seems related to PulseAudio.

**Comment by PSLLSP** [comment]
This can be closed. Pulse audio routed Wesnoth music to internal sound card. Once I discovered this switch in PulseAudio control panel, I changed that and , I finally hear nice Wesnoth music from my USB speakers. The only problem was with my PulseAudio configuration.

**Comment by Wedge009** [comment]
No worries, thanks for confirming it's resolved.
