### ISSUE TITLE
SotA S21: Lengthy delay when new enemies appear

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#1706]
As of Master 96ea0eb6b97cc558d7a20d6feef30a513e538944

In SotA S21, new enemies appear mid-scenario on turns 4, 12, & 13
This is handled quickly in 1.12.6, but is significantly slower in 1.13

Reported here in section 21_Against_the_World:
https://forums.wesnoth.org/viewtopic.php?f=31&t=43116&start=15#p609866

When I tested the slow down, the following error occurs in my log 12,469 times:
"error engine: failed to auto-store $unit at (-999,-999)"

I have an improvement to the scenario code here: https://github.com/wesnoth/wesnoth/pull/1705

Which lowers the lag time, and error log occurrence to 2,169 times, but it's only a partial solution, and wasn't necessary in 1.12.6 for speed.

The error is triggered due to something between lines 245-266 in 21_Against_the_World.cfg

**Comment by gfgtdf** [comment]
> error engine: failed to auto-store $unit at (-999,-999)

this is likeley because that code uses a variable named 'unit' i'd suggest to just rename that variabl

**Comment by sigurdfdragon** [comment]
@gfgtdf That was it, thanks
