### ISSUE TITLE
Can't build translations without second gettext on macOS

### ISSUE THREAD

**Issue by ancestral** [wesnoth/wesnoth#1707]
When attempting to build translations, I get:

`scons: *** Do not know how to make File target 'translations' (/Users/user/wesnoth/translations).  Stop.`

It has something to do with the version of `gettext` included in MacOS, and that what Wesnoth likes. 

Is there a reason the pre-installed `gettext` is insufficient? Having two versions of the same library can cause problems if not careful.

Currently, to build translations, one must install `gettext` (say, via Homebrew), export it into your path, and then build.

**Comment by loonycyborg** [comment]
This message suggests that translation targets were disabled. They're auto-disabled if "msgfmt" program isn't found in $PATH

**Comment by hrubymar10** [comment]
I guess that macOS' gettext just doesn't provide required things.

for example `msgfmt` :

```
MacBook-Pro:~ user$ sudo su                                                                   #Became root user using this "hack"
sh-3.2# cd /                                                                                                 #cd to root
sh-3.2# find . -name "msgfmt"                                                                  #Try find all files named 'msgfmt'
./usr/local/bin/msgfmt                                                                                 #This is symlink to Homebrew's gettext
./usr/local/Cellar/gettext/0.19.8.1/bin/msgfmt                                           #Homebrew Gettext
```

As you can see, there doesn't exist macOS' `msgfmt`

Conclusion? In my opinion it can't be fixed because macOS just doesn't provide it. Can someone other confirm it?

**Comment by singalen** [comment]
My proposal:
* add `msgfmt` as a Mac build requirement. No matter where you get it. We could provide a statically linked binary to those who need it.
* make a more clear diagnostic message in SConscript and maybe CMakeLists, like `"msgfmt" not found in $PATH", translations disabled`.

**Comment by ryandesign** [comment]
> It has something to do with the version of `gettext` included in MacOS

macOS has never included any version of gettext.

**Comment by ancestral** [comment]
> macOS has never included any version of gettext.

This is from long ago. Looks like I misunderstood the cause.

This might just be an upstream issue. It looks like with Homebrew you have to some extra stuff as it’s keg-only. Past that, I don’t know, as I don’t want to research this. I haven’t needed to build or run translations lately as I am no longer involved with that portion of the project.

I’m fine if you want to close this ticket.

**Comment by Pentarctagon** [comment]
Closing then - translations build on travis and hrubymar hasn't reported any issues with this when making the macOS package.

**Comment by hrubymar10** [comment]
Translations for packages are generated using Homebrew's gettext as described in Xcode's README.md .

macOS does include `libintl` library but doesn't provide binaries like `msgfmt` IIRC.

I believe that only valid/fixable point of this issue is singalen's comment:
> * make a more clear diagnostic message in SConscript and maybe CMakeLists, like "msgfmt" not found in $PATH", translations disabled.
