### ISSUE TITLE
some string won't work in lua console

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1708]
puting `wesnoth.wml_actions.message { speaker="narrator", message="Hello World!" }` will give a `event not found` error, i think this is becasue the history library treats the '!' at the end as a special character to invoke cutom commands. In any case this is undocumented and unexpected bahviour.

**Comment by CelticMinstrel** [comment]
In my opinion we should stop using the history library and implement our own. The text field has an interface for this already, maybe that could be used?

**Comment by gfgtdf** [comment]
> In my opinion we should stop using the history library and implement our own. The text field has an interface for this already, maybe that could be used?

I fully agree here, this would also remove another dependency from wesnoth.

**Comment by CelticMinstrel** [comment]
Note that the existing text field history isn't as useful though, so it would probably need some work if we wanted to use it in the Lua console.

**Comment by Arcanister** [comment]
This behavior can be disabled in bash at least. Maybe it should simply be disabled by default in Wesnoth too?

**Comment by CelticMinstrel** [comment]
Yeah, it's using readline for history. If anyone knows how to disable that behaviour in readline, go ahead and do that for the Lua console, though I would still prefer moving away from readline.

**Comment by GregoryLundberg** [comment]
Moving away from breadline means either eliminating the features or reimplementing them. Both seem like poor choices.

**Comment by Arcanister** [comment]
I cannot reproduce this issue on GNU/Linux, even though lua console completion is set to "yes". If I input something like !hrs then I get event not found error.

However this patch, or setting correspondent value in inputrc should solve the problem.
```
diff --git a/src/gui/dialogs/lua_interpreter.cpp b/src/gui/dialogs/lua_interpreter.cpp
index edc02fe..4b3fce8 100644
--- a/src/gui/dialogs/lua_interpreter.cpp
+++ b/src/gui/dialogs/lua_interpreter.cpp
@@ -49,6 +49,7 @@
 #ifdef HAVE_HISTORY
 #include "filesystem.hpp"
 #include <readline/history.h>
+char history_expansion_char = 0;
 #endif
 
 static lg::log_domain log_lua_int("lua/interpreter");
```

**Comment by CelticMinstrel** [comment]
@gfgtdf - Does that patch fix it for you?

**Comment by gfgtdf** [comment]
since my local msvc build, if ihad one wouldn't build with history enables anyway, the onl way to test this would be pushing it to master and testign with a jenkins build.

**Comment by CelticMinstrel** [comment]
Then we should get someone else who gets the error to test it. I may be able to do it myself, actually.

**Comment by Arcanister** [comment]
It could be gfgtdf using old version of readline. Perhaps updating readline would also fix the problem.

**Comment by gfgtdf** [comment]
> It could be gfgtdf using old version of readline

I used the 1.13.8 windows release when i tested that.

**Comment by Arcanister** [comment]
Wesnoth for windows comes with ancient GNU Readline 5.0 (from 2005), while you need 6.3 or later.

**Comment by loonycyborg** [comment]
I've updated Readline to version 7.0 in 1.13.10 windows release. I tested it and found that `message="Hello World!"` in a command doesn't trigger `event not found` with this library version.

**Comment by Arcanister** [comment]
So, if history expansion still bothers you (it will still happen with `!` in front of non-space and non-quote character, unless `!` is escaped, you can apply my patch from above.

Perhaps it should be configuration option in wesnoth preferences?

**Comment by soliton-** [comment]
This seems resolved. If someone wants to change the default for history expansion or so please file a new issue.
