### ISSUE TITLE
[set_menu_item] no longer works.

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#1710]
[set_menu_item] no longer does anything, as of the latest revision.  The code:
```
[event]
  name="start"
  [set_menu_item]
    id="menu"
    description="a menu"
    [command]
      [message]
        message="hi"
      [/message]
    [/command]
  [/set_menu_item]
[/event]
```
does not cause a message to be displayed.  It does show in the right-click menu.  No errors appear in the log.

**Comment by CelticMinstrel** [comment]
Presumably related to Vultraz's recent `wmi_container` refactor.
