### ISSUE TITLE
Hard coded number in multimenu^$first and 1 other

### ISSUE THREAD

**Issue by gunchleoc** [wesnoth/wesnoth#1721]
src/gui/widgets/multimenu_button.cpp:187 src/gui/widgets/multimenu_button.cpp:207

    multimenu^$first and 1 other
    multimenu^$first and $excess others

The first plural rule in my language matches both 1 and 11, so this is untranslatable. Never, ever hard-code numbers in plural statements ;)

I'm hesitant to just use $excess in my translation anyway, because it will probably cause a crash.

**Comment by CelticMinstrel** [comment]
That's the singular statement that's hard-coded. It's easy to not hard-code it, of course, but I'd have thought that you can just add the placeholder to the translated string? Something like `msgstr[0] "$first and $excess other"`.

Anyway, if no-one else gets to it, I'll fix it this evening.

**Comment by gunchleoc** [comment]
I have have bad experiences with program crashes when sprintf placeholders don't match, so without analysing the code, I won't risk it.

**Comment by CelticMinstrel** [comment]
1. This is exactly Wesnoth's variable substitution syntax (even to the point that `$()` would be expanded if you included it in a string). This means missing placeholders are just empty and excess placeholders are ignored.

2. The singular and plural form of the strings have the same available variables when passed to the formatting function; in this specific case, for English, the `$excess` variable is available byt just goes unused when the singular string is selected.

Certainly `sprintf` would cause crashes if the placeholders don't match. It's well-known that `sprintf` and related functions are not particularly safe. But Wesnoth doesn't use `sprintf` or anything like it.

**Comment by CelticMinstrel** [comment]
(As you can see from the commit, that string no longer includes `$first`.)

**Comment by gunchleoc** [comment]
Thanks for the explanation and the fix :)
