### ISSUE TITLE
Changing volume with [volume] doesn't affect preferences sliders

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#1727]
When the music (and sound, I am assuming) volume is changed via the [volume] tag, the slider value in Preferences > Sound is not updated.  For example, if I set the Music slider to max volume, then use [volume] to set the music volume to 0, when I go to the Preferences, the Music slider is still at max volume.

**Comment by CelticMinstrel** [comment]
If I recall correctly, the volume set by `[volume]` is in fact relative to the volume set in Preferences, rather than replacing it. So, it's correct that it doesn't show in preferences.

**Comment by Pentarctagon** [comment]
Oh, so it is.  Well, never mind then.
