### ISSUE TITLE
help: support for forward/backward mouse buttons

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1729]
Some mouses have buttons for forwards and backwards in browsers etc.
We could use them for the forwards/backwards in the help.

**Comment by CelticMinstrel** [comment]
I'm not sure if that's possible to detect in a generic manner; as far as I know, they'd appear to SDL as just button 4 and button 5. The problem with this is that button 4 and button 5 could just as easily be some other extra mouse buttons with completely different meaning.

**Comment by sevu** [comment]
Maybe it's some kind of default that these buttons are every time button 4 and 5.
I can't test though, I have no mouse with more than 5 buttons.

**Comment by CelticMinstrel** [comment]
Well, I don't know if there's a guarantee that mice with more than three buttons actually have forward/back buttons, either.

**Comment by sevu** [comment]
I think right now everything >3 is unused, it would still be an improvement.

**Comment by sevu** [comment]
Happy to see this has been implemented
