### ISSUE TITLE
'Illegal tile in map' flood

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#1733]
When loading a save-game where the map has some custom terrain, the console is flooded with these errors, I assume it's because of the minimap.  Even if there are multiple custom terrain codes, a single error on the first unknown code encountered should be enough to get the point across as to why the minimap is not being displayed.  As far as debugging WML, I don't see how this error is helpful, so I can't think of a reason to have the error show more than once.
> 20170527 19:27:16 error config: Error while loading the map: Illegal tile in map: (Mhyc^Mfyc) 'Mhyc^Mfyc'
20170527 19:27:16 error config: Error while loading the map: Illegal tile in map: (Mhyc^Mfyc) 'Mhyc^Mfyc'
... yadda-yadda-yadda ...

I'm not sure when this started, but it has been going on for a while, it's not a 1.13.8 thing.

**Comment by GregoryLundberg** [comment]
I ran into this message last year. IIRC at the time the mini map was loading, the custom tiles were not yet loaded. So the actual map looks fine, but the mini-map for the save is messed up. You're probably seeing one message per tile.

Snubbing after the first message is probably too draconian. It should be possible to build a mapping recording the illegal tile values so you only see one message per value.

**Comment by doofus-01** [comment]
I'm not sure if multiple tiles cause multiple errors, but the overall number of errors generated has to do with how long you sit in the load-game dialog.  So, it's some sort of loop, or it gives an error on each refresh, or something like that.  It's not giving one error per tile.

**Comment by Vultraz** [comment]
Fixed on accelerated_rendering. Might backport a version of the fix to master.

**Comment by Vultraz** [comment]
FTR, the message spam was due to an error every draw cycle.

Anyway, dunno when, but this is fixed on master. The error only appears once when selecting the affected save and doesn't continue to spam the console. I don't recall backporting by fix, nor can I find mention of it in the logs... My best guess is this was inadvertently fixed along with some drawing refactors. Perhaps when @jyrkive made windows stop redrawing 50 times a second?

Anyway, closing.

**Comment by CelticMinstrel** [comment]
Should this be reopened?

**Comment by Wedge009** [comment]
I don't think I was able to see this issue but it's worth re-testing now that #6855 is merged.

**Comment by doofus-01** [comment]
The flood doesn't happen even in 1.16.2 (that's just what I had compiled, I don't think that version is a dividing line).  The mini-map doesn't load, but there is just one error printed.

(I don't know what goes on in recent 1.17 yet.)

**Comment by mesilliac** [comment]
If this is fixed in 1.16 it should remain so in 1.17. Everything should be drawing only as-necessary, so even if there's still an error it should only appear once.

Closing as resolved, but reopen if for some reason it reoccurs.
