### ISSUE TITLE
[chat] side filter is ignored

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#1735]
When designing patch for https://forums.wesnoth.org/viewtopic.php?f=12&t=46029, I noticed that 1.13.8 shows 
[chat]
message=_"message"
side=1
[/chat]
also to client, that does not control side 1. 

This seems to be from the fact that with 1.13.8, side.controller shows human for networked sides too.

Therefore https://github.com/wesnoth/wesnoth/blob/553f7c3c8baac9fcc062fa1fe0b0ac6cdca14a07/data/lua/wml-tags.lua#L78 check passes, if there is any side, that should see the message.

**Comment by ProditorMagnus** [comment]
I intend to open pull request for this soon. However, new version relies on side.is_local, which does not seem to be documented.

**Comment by CelticMinstrel** [comment]
`side.is_local` just tests whether the side is controlled by a local client.
