### ISSUE TITLE
Title screen hotkeys not working

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#1737]
Hotkeys such as m, a have no effect on title screen with 1.13.8. Works as expected with 1.13.7. Only F1 and F5 seem to work currently.

**Comment by ProditorMagnus** [comment]
Ctrl+F and Alt+F4 work as expected.

**Comment by Wedge009** [comment]
Interesting. None of the single-letter hot-keys appear to work on the main menu but I can get combinations like ctrl-p for Preferences just fine.

This is testing with default hot-keys, of course.

**Comment by CelticMinstrel** [comment]
My guess is that it affects any hotkey that would produce text input, but I haven't verified this. (So for example shift-p probably wouldn't work either.)

**Comment by Wedge009** [comment]
This seems to have resolved most of the issues in the title screen, thanks. One I found that still seems to be an issue is the credits, whose default hot-key is space. I wonder if there is an issue with the use of space at the moment, as it also seems to be a problem in #1769.

**Comment by CelticMinstrel** [comment]
Maybe we could add space to the list of uncomposable keys in key.cpp? I removed backquote since it turned out that that didn't really address the true issue, but for space I suppose it's not so weird for it to be included...

**Comment by Wedge009** [comment]
Funny how that helped. Let me know if I didn't fix it correctly (2de925e4).
