### ISSUE TITLE
sorting by level + remaining XP in recall dialog is broken

### ISSUE THREAD

**Issue by ePaul** [wesnoth/wesnoth#1738]
In 1.12, the default sorting in the recall dialog was a combination of level (3 before 2 before 1) and "remaining XP until next level".

In 1.13.8 (the first 1.13 version I tried), you can choose to order by level or by XP (beyond some others), but none of them give the sort order which we had before.

Sorting by level gives a total mix of XP (or remaining XP):
![recall-strange-sort](https://cloud.githubusercontent.com/assets/645859/26529212/42e48948-43bc-11e7-8e5b-f20fe3d99813.png)

Sorting by XP doesn't take "remaining XP" into account, and neither the level:
![recall-strange-sort-xp](https://cloud.githubusercontent.com/assets/645859/26529211/42e31d2e-43bc-11e7-86ec-8a6cf6f1004b.png)

Could we have the old sort order back, please?

**Comment by CelticMinstrel** [comment]
This should be fixable by using a stable sort in the listbox.

**Comment by gfgtdf** [comment]
afaik it does use a stable sort, but the point here is that sort by level should always use remaining xp as second criteria (which is also different from current exp)

**Comment by CelticMinstrel** [comment]
Oh? If that's the case then it should be even easier to fix, just by tweaking the functors that this dialog uses for sorting.

**Comment by Vultraz** [comment]
So, I think both Level and XP should basically sort by the same criteria (level and xp needed), then?

**Comment by ePaul** [comment]
My idea would be:

* Sort by level: First by level (decreasing), second by remaining XP (increasing).
* Sort by XP: First by XP needed (increasing), second by level (decreasing).

(Of course, increasing/decreasing can be swapped by clicking again.)

**Comment by CelticMinstrel** [comment]
The second half of that is probably unnecessary, as long as it uses a stable sort - simply clicking the Level header and then the XP header would produce that result, and that would allow people to sort second by some other criterion if they prefer by clicking, for example, Trait and then XP.

@Vultraz is also totally wrong about the intent here, I believe. The Level and XP sorting criterions shouldn't be the same. Level should simply use the XP remaining to level-up as a secondary criterion when the levels are the same. Sorting by XP should probably just sort by XP (and not sure if it should be current XP or XP needed to level).

**Comment by CelticMinstrel** [comment]
Actually, if sorting by XP already sorts by the XP needed, then the criterions may not need changing at all - you'd just need to set up the _default_ view to sort first by XP, then by level. (This might sound like the opposite of what you want, but actually does give the result you want. Think of it like this: first you sort them by XP needed. Then you sort the result by level. This gives the effect of level being the primary sort criterion while XP is the secondary criterion.)

That said, I noticed one odd thing about this that might render my "unnecessary" comments a little moot - the two sorts are _in opposite directions_. That is, level decreasing, followed by XP increasing. I'm not sure if you can get this effect by simply clicking on the headers in the right order. _Maybe_ it would work to click the XP header until XP is sorted increasing, then click the Level header twice? Can someone try it? (I don't have time right now, but I might try it later.) It seems to me that it's important to check if the desired result is obtainable in this way. If it is, then all that needs to be done is setting the defaults to that desired result.

**Comment by universecoder** [comment]
Hello, I want to contribute to Wesnoth.
Can I try taking up this issue?

**Comment by jyrkive** [comment]
@Vultraz : @universecoder is asking your permission in particular, as you have assigned the issue to yourself.

**Comment by Vultraz** [comment]
@universecoder  sure, go ahead :) I hadn't really had a solution for this yet anyway.

**Comment by universecoder** [comment]
I think that they should be sorted by level first. Then we have (Actual XP/XP_to_upgrade). After this they should be sorted by (XP_to_upgrade-Actual XP). 
This way, we have units sorted by level, and the units that are likely to upgrade the fastest are at the top.
Is this ok?

**Comment by jyrkive** [comment]
What you propose is exactly what I'd prefer.

**Comment by ePaul** [comment]
@universecoder Sounds good ... I guess the quotient step in between is new, but I think it won't hurt to have the half-leveled mages with the half-leveled spearmen instead at the end (because even half-leveled mages have more XP needed than totally fresh spearmen).

**Comment by universecoder** [comment]
@ePaul 
Quotient step? I just mean to sort them by their experience_to_advance.

**Comment by ePaul** [comment]
@universecoder Sorry, I might have misunderstood your previous comment.

**Comment by jyrkive** [comment]
Implemented in #1760 .
