### ISSUE TITLE
Text rendering output bad when copied with alpha blending

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#1744]
During my work on the accelerated rendering branch, I've once again run into the issue that plagued me when I attempted to use textures for text in the GUI2 canvas along with a surface renderer: **text looks like crap if it's copied with alpha blending**:

![this text looks like shit](https://cloud.githubusercontent.com/assets/3558659/26613141/0aa2f902-4605-11e7-9959-ec972deb1603.JPG)

For some reason, the text looks fine on buttons (and only buttons - in other tests before I managed to generally restrict the effect to semi-transparent surfaces).

This doesn't occur when copying the text directly to the screen renderer (`SDL_RenderCopy`) or copying the pixel data verbatim to a texture (`SDL_UpdateTexture`). However, the former conflicts with my design of having draw results cached to a texture, and the latter is impossible to use since having no blending at all cases the fully transparent area of the surface to overwrite whatever data is underneath them. The same thing occurs when disabling alpha blending (`SDL_BLENDMODE_NONE`) on either the text surface or a texture created from that surface.

This is related to #1568. The underlying cause is probably the same. This issue isn't by any means new; it's likely the reason we have the custom `blit_surface` function. I'm guessing #1568 simply covers cases it wasn't able to cover.

I'm really not sure how to solve this. A stopgap measure is to call `pango_cairo_show_layout` twice, but I'm not sure that's really what we want to do.

And for the record, no, this isn't a premultipled vs postmultipled alpha problem (at least, not entirely). Our rendering code already does a pre-to-post multiplied alpha conversion on the cairo text output.

**Comment by Wedge009** [comment]
Upon seeing the bug title, I also thought it might be related to #1568. I don't think we want to call show layout twice - I remember you already removed that kind of thing on Windows for the last Cairo text rendering issue.

Speaking of which, is this only on Windows or does it happen on other OSs?

**Comment by Vultraz** [comment]
Not sure, but given that `blit_surface` is used on all platforms I'd say it's probably not Windows-specific.

**Comment by Wedge009** [comment]
Comparing (by eye) between Linux and Windows (MSVC), I don't see this issue. Windows looks closer to what is shown in #5618 (after change applied), so assuming that PR has resolved this issue.
