### ISSUE TITLE
HttT void armor (19b) non-functional in 1.13.8

### ISSUE THREAD

**Issue by TuggyNE** [wesnoth/wesnoth#1746]
The void armor in Swamp of Dread, scenario 19b, does nothing but report its presence when a unit wears it. It does not affect displayed or actual resistance anywhere.

STR:
1. Get to 19b somehow or other, probably through judicious use of `:next_level`.
1. Enter debug mode.
2. Kill each of the four death knights (<kbd>Shift</kbd>+<kbd>K</kbd> when hovering, or right-click and choose Kill unit).
3. Send some fighting unit (e.g. Kalenz) to pick up the armor.
4. Enter combat with the lich's skeletons or bats.

Expected:
50% blade resistance (Skeleton does 4-3 at dawn/dusk) and 50% shown when hovering over HP.
Actual:
With Kalenz, 0% blade resistance (Skeleton does 7-3 at dawn/dusk) and same shown in HP tooltip.

Bug is the same on BfW 1.13.7 and 1.13.8 pre-packaged Windows builds on Windows 10 x64.

Initial investigation into WML showed no obvious problems: an `[object]` with two `[effect]`s and some message eventing (which *does* work) and a display-only trait.

**Comment by ln-zookeeper** [comment]
Thanks, should now be fixed by 24eb4bcd.
