### ISSUE TITLE
Add-on Manager Interface - sort by last updated

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#1747]
It would be useful to be able to sort add-ons in the in-game add-on manager by the time they were last updated.  Partially I think this would just be useful functionality to to have in and of itself, and also partially because being able to sort by last updated would make it easier to start actually enforcing the add-on server rules.  The web UI at addons.wesnoth.org does allow sorting by last updated, but having this functionality in the game would be much more convenient.

**Comment by pydsigner** [comment]
Is this not possible in 1.13? I know it is in 1.12.

**Comment by CelticMinstrel** [comment]
If it's a regression, then fixing this must be a priority.

**Comment by Pentarctagon** [comment]
@CelticMinstrel I have Wesnoth open on a 1920x1080 monitor, so I can't imagine it's auto-hiding any columns.

**Comment by CelticMinstrel** [comment]
Yeah, pretty sure the smallest width that auto-hides any columns is 1280.

**Comment by jostephd** [comment]
Idea: I mainly use "Sort by updated date" to look through newly-uploaded add-ons.  That use case would be served equally well by letting the user mark a particular add-on as "I've seen this", and then allow filtering the list for add-ons that don't have the "has been seen" marker.

The "I've seen this" marker would be cached locally (in ~/.local/share/ or wherever).  It could be either per-add-on or per-add-on-version; the distinction is whether new versions of the marked add-on would be matched by the "Not marked as seen" filter.

**Comment by Vultraz** [comment]
I've been working on reimplementing the original first uploaded/last updated sorting options, but it's implementation has proven a lot more difficult than I expected.

**Comment by jostephd** [comment]
@Pentarctagon Filed that as #1904.

**Comment by Pentarctagon** [comment]
@Vultraz Having this functionality also is also particularly important from my perspective, as I was planning to start actually enforcing the add-on server rules once 1.14 comes out.

It doesn't need to be a blocker for 1.13.9 though, if it comes down to it.
