### ISSUE TITLE
Event triggers multiple times (HttT Plunging into the Darkness)

### ISSUE THREAD

**Issue by fluffbeast** [wesnoth/wesnoth#1749]
In scenario 14 of HttT, the sighted event triggers multiple times.  I suspect that this happens because units are moved during the event, causing new sightings to happen before the original event completes. It eventually finishes after triggering about 8 or 9 times.

This problem is reproducible; I attached a save file that triggers the problem as soon as Konrad is moved north. (Note that get_gryphons=1)

This was observed on the latest clean build, e188379cd2b3055d7c344b4316953a3d1e41b17f

[HttT-Plunging_into_the_Darkness-Auto-Save7.gz](https://github.com/wesnoth/wesnoth/files/1049611/HttT-Plunging_into_the_Darkness-Auto-Save7.gz)

**Comment by GregoryLundberg** [comment]
Also note on-screen Lua message:
<Lua> Repeated [endlevel] execution, ignoring

**Comment by gfgtdf** [comment]
please test with c0bd6253c1d8aad6b33d9a8723dfef1ad562b218

**Comment by fluffbeast** [comment]
This seems to fix the problem, thanks!
