### ISSUE TITLE
Preferences dialog error

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#1750]
On current master, opening the preferences dialog from the main menu results in the following:

> Setting mode to 1920x1054
> Checking lua scripts... ok
> 20170603 13:34:50 error gui/layout: grid [] place: Failed to place a grid, we have 560,418 space but we need 593,55 space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'list_hotkeys' in a 'N4gui24gridE' with the id '' in a 'N4gui29generatorINS_6policy17minimum_selection7no_itemENS1_17maximum_selection10many_itemsENS1_9placement11independentENS1_13select_action4showEEE' with the id '_content_grid' in a 'N4gui24gridE' with the id '' in a 'N4gui214stacked_widgetE' with the id 'pager' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'preferences_dialog'.

OS is Linux Mint 18.1.

**Comment by CelticMinstrel** [comment]
Does the hotkeys panel still work?

**Comment by Pentarctagon** [comment]
It shows up, but is completely blank:
https://i.imgur.com/mtFCt8D.png

**Comment by gfgtdf** [comment]
does this happen on all languages?

**Comment by Pentarctagon** [comment]
I didn't try on _all_ languages, but I tried a couple others, and it did give the same error:

> 20170604 02:30:13 warning general: setlocale() failed for 'af_ZA'.
> 20170604 02:30:13 warning general: setlocale() failed for 'af_ZA'.
> 20170604 02:30:18 error gui/layout: grid [] place: Failed to place a grid, we have 560,418 space but we need 593,55 space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'list_hotkeys' in a 'N4gui24gridE' with the id '' in a 'N4gui29generatorINS_6policy17minimum_selection7no_itemENS1_17maximum_selection10many_itemsENS1_9placement11independentENS1_13select_action4showEEE' with the id '_content_grid' in a 'N4gui24gridE' with the id '' in a 'N4gui214stacked_widgetE' with the id 'pager' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'preferences_dialog'.
> 20170604 02:30:35 warning general: setlocale() failed for 'da_DK'.
> 20170604 02:30:35 warning general: setlocale() failed for 'da_DK'.
> 20170604 02:30:37 error gui/layout: grid [] place: Failed to place a grid, we have 560,418 space but we need 593,55 space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'list_hotkeys' in a 'N4gui24gridE' with the id '' in a 'N4gui29generatorINS_6policy17minimum_selection7no_itemENS1_17maximum_selection10many_itemsENS1_9placement11independentENS1_13select_action4showEEE' with the id '_content_grid' in a 'N4gui24gridE' with the id '' in a 'N4gui214stacked_widgetE' with the id 'pager' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'preferences_dialog'.
> 20170604 02:31:30 error gui/layout: grid [] place: Failed to place a grid, we have 560,418 space but we need 593,55 space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'list_hotkeys' in a 'N4gui24gridE' with the id '' in a 'N4gui29generatorINS_6policy17minimum_selection7no_itemENS1_17maximum_selection10many_itemsENS1_9placement11independentENS1_13select_action4showEEE' with the id '_content_grid' in a 'N4gui24gridE' with the id '' in a 'N4gui214stacked_widgetE' with the id 'pager' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'preferences_dialog'.
> 20170604 02:32:15 warning general: setlocale() failed for 'ca_ES'.
> 20170604 02:32:15 warning general: setlocale() failed for 'ca_ES'.
> 20170604 02:32:18 error gui/layout: grid [] place: Failed to place a grid, we have 550,418 space but we need 593,55 space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'list_hotkeys' in a 'N4gui24gridE' with the id '' in a 'N4gui29generatorINS_6policy17minimum_selection7no_itemENS1_17maximum_selection10many_itemsENS1_9placement11independentENS1_13select_action4showEEE' with the id '_content_grid' in a 'N4gui24gridE' with the id '' in a 'N4gui214stacked_widgetE' with the id 'pager' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'preferences_dialog'.
> 20170604 02:32:24 warning general: setlocale() failed for 'et_EE'.
> 20170604 02:32:24 warning general: setlocale() failed for 'et_EE'.
> 20170604 02:32:26 error gui/layout: grid [] place: Failed to place a grid, we have 496,418 space but we need 593,55 space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'list_hotkeys' in a 'N4gui24gridE' with the id '' in a 'N4gui29generatorINS_6policy17minimum_selection7no_itemENS1_17maximum_selection10many_itemsENS1_9placement11independentENS1_13select_action4showEEE' with the id '_content_grid' in a 'N4gui24gridE' with the id '' in a 'N4gui214stacked_widgetE' with the id 'pager' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'preferences_dialog'.

**Comment by gfgtdf** [comment]
i couldn't reproduce this one

**Comment by Pentarctagon** [comment]
Not sure what else to say - it's still happening for me with latest master.

**Comment by Pentarctagon** [comment]
So, apparently it was somehow related to my preferences file, since I deleted it for another reason and now I can access the hotkeys tab again and don't get this error.  Therefore, I am closing this.

**Comment by CelticMinstrel** [comment]
If it's related to your preferences file, I wonder if that could meant that it depends on what you've customized your hotkeys too. Maybe try changing some hotkeys and see if you get it again? Probably consider hotkeys with multiple modifiers, and possibly multiple hotkeys for the same command.

**Comment by Pentarctagon** [comment]
I hadn't set other hotkeys, except for a hotkey of 0 for the [set_menu_item] in my add-on.  I do have backups though, so I could upload the preferences file if you want.

**Comment by CelticMinstrel** [comment]
Sure, might as well.

**Comment by CelticMinstrel** [comment]
(Also, what's your addon?)

**Comment by Pentarctagon** [comment]
My preferences: https://pastebin.com/1T5PpZp9

My add-on used to be Music, but now on the 1.13 server at least is renamed to Wesnoth Music Player.
