### ISSUE TITLE
[part]s won't be shown if [story] doesn't have [part] as a child

### ISSUE THREAD

**Issue by tamanegi-jp** [wesnoth/wesnoth#1765]
(This is different from the issue I recently posted at the forum)
If [story] does not have [part] as a direct child like the following example, no story text will be shown. (If another [part] is added outside the [if] block, either one of pre-existing [part] in addition to the newly added one will be shown.)

```
[story]
  [if]
    ...
    [then]
       [part]...[/part]
    [/then]
    [else]
       [part]...[/part]
    [/else]
  [/if]
[/story]
```

It seems WML evaluation is skipped if there are no direct child [part] tags.

Attached file below is a sample _main.cfg file of a campaign I used for confirmation. No storytxt will be shown. (Checked on v1.13.8+dev (2aefb78ab7-Clean))
[wml.txt](https://github.com/wesnoth/wesnoth/files/1064034/wml.txt)

**Comment by Vultraz** [comment]
Sounds like we need to move the validation post-parse.

**Comment by tamanegi-jp** [comment]
Fixed. Thank you very much :)
