### ISSUE TITLE
Immediate sound change

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1766]
Would it be possible to have sound preferences have an immediate effect?

Right now there is no "cancel" or "OK" button, which hints that changes I mage should be applied immediately. When it doesn't, it feels a bit like a bug. Also, the volume slider becomes less effective as you need to make a lot of clicks in order to see how a chosen volue level "feels".

**Comment by vn971** [comment]
Possibly related to https://github.com/wesnoth/wesnoth/issues/1809

**Comment by vgaming** [comment]
@Vultraz thanks for the fix, awesome!
