### ISSUE TITLE
game preferences: sliders are not click-able

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1767]
Steps to reproduce:
* start wesnoth-1.13.8 (development version)
* start creating a game
* go to last screen that allows selecting "Gold" and "Income"
* try to click on the right part of the "Gold" slider to set it to maximum

Expected:
* the Gold value should be set to a higher value

Actually:
* It decreases from a value of 100 to the value of 50. And doesn't change after subsequent clicks. The value of 50 seems to be a kind of default value. Whatever you set previosly, clicking on a Gold slider resets it to 50.

// If fixing the sliders is not convenient then at least it would be good to set the default value to 100 instead of 50.

Thanks

**Comment by Wedge009** [comment]
I've observed similar behaviour before and seems related to #1656 and other slider-related issues.

**Comment by gfgtdf** [comment]
fixed in https://github.com/wesnoth/wesnoth/commit/e9c6dff56ad8283d19e539e27fde5ada6c73059c
