### ISSUE TITLE
misaligned hover pop-up

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1768]
See the screenshot:

![screenshot](https://camo.githubusercontent.com/713b13ac9d532c7c799d7f79097d1fd5f3b5480a/68747470733a2f2f706f696e747367616d652e6e65742f766e3937312f74656d702f323031372e30362e30395f31373a33323a31395f653139346432662e706e67)

Before taking the screenshot, mouse was hovered above the "Gender: []" image. I would expect the pop-up to be somewhere close to the mouse, but it's actually far to the right.

Not an important bug, obviosly.

**Comment by Vultraz** [comment]
I fixed this in d707f94830bced93. Forgot to close this report.

**Comment by vn971** [comment]
@Vultraz cool, thank you! BTW, if you include text like "fix GH-1768" or "fix #1768" in commit message, github will auto-link those facts and close the issue (at the moment the commit gets merged to master).
