### ISSUE TITLE
"skip turn" missing in 1.13.8+dev

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1769]
The development version 1.13.8 doesn't seem to have a "skip turn" action.

In 1.12.x, it was keyboard "Space" button. When you press it, you mark one of your units as "finished moving/attacking for this turn", so that this unit will no longer occur in the "Next unit" list.

This action by itself is very convenient. You separate units for which you want to return later from units that you are sure will not play anymore in this turn.

**Comment by CelticMinstrel** [comment]
For the record, I believe this action is called "hold" rather than "skip turn". (Might help someone trying to locate it in the source.)

**Comment by CelticMinstrel** [comment]
(Unless I'm confusing it with a slightly different action?)

**Comment by Wedge009** [comment]
There's a end unit turn (default space) and hold position (default shift+space). Both are present in 1.12 and 1.13, though 1.13 has issues with some combination hot-keys at the moment.

The end unit turn still seems to work in 1.13 for me.

**Comment by vn971** [comment]
@Wedge009 "end turn" works for me, but "hold" (end _unit_ turn) doesn't. Compiled from master branch 2 days ago (at the time of raising the issue).

**Comment by Wedge009** [comment]
End unit turn and hold position are different. But looking at it again, it seems the _default_ hot-keys are not working in 1.13. Assigning your own hot-key to either of them still works. So it looks like it's another issue with the hot-key system itself, not the triggering of the end unit turn or the hold position functions.

**Comment by CelticMinstrel** [comment]
For the record, I was wrong in my initial comment. The "hold" action is even stronger than what you described - it means the unit won't show up in the cycle order ever again in any future turn, until such time as you specifically find it and move it (which undoes the "hold").

**Comment by Wedge009** [comment]
As @CelticMinstrel suggested, adding space to the list of 'uncomposable' keys seems to get hot-keys involving space working again (2de925e4). Please try for yourself and let me know if it's still not working for you.

**Comment by vn971** [comment]
@Wedge009 all correct, the bug is fixed now.
Thanks!
