### ISSUE TITLE
Help browser uses translatable name as unique id

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#1774]
When there are multiple weapon specials with same name, and different id, then when opening in game help by clicking on special name in sidebar, it opens at wrong topic.

![](https://vgy.me/fRCDqs.png) Expected

![](https://vgy.me/83vYRY.png) Actual

https://forums.wesnoth.org/viewtopic.php?p=613776#p613776

Broken both for 1.12 and 1.13.

**Comment by ProditorMagnus** [comment]
Ids used were AE_agl_knockback and AE_efm_trample, so it is possible that alphabetically first is always used.

**Comment by Vultraz** [comment]
Looks like a problem with the fact that `unit_type::abilities()` are ability names... what the *hell*.

**Comment by CelticMinstrel** [comment]
There's probably a reason for that though, so don't blindly change it.
