### ISSUE TITLE
Trait mouseover: number missing for XP 

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1776]
![Trait Overlay](https://user-images.githubusercontent.com/21158813/27007150-44f6db2c-4e49-11e7-8a4e-95d13b09e868.png)
In reality it needs 12% more XP to advance.

**Comment by CelticMinstrel** [comment]
Did you check if it happens with US English too? Because I imagine that this could in theory be a translator error.

**Comment by sevu** [comment]
Happens with en_US too.

**Comment by sevu** [comment]
It only affects XP, for example getting -12% HP is displayed correctly.
