### ISSUE TITLE
let level= in suf accept multiple values

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1778]
It would be nice to have Standard Unit Filters like this one:
```
[filter]
    [not]
        level=0,1,2
    [/not]
[/filter]
```

**Comment by sevu** [comment]
It's already used in mainline:
https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg#L210
It takes only the first value into account.

**Comment by CelticMinstrel** [comment]
This would be extremely easy to do.

**Comment by sevu** [comment]
Would be great to have. We talked in an old bug report about it too, a question remaining was if there are other keys where you would assume they accept such syntax but the don't do it (yet)
