### ISSUE TITLE
upkeep key in unit types broken

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1779]
In 1.12 you can use the upkeep key in unit types to change upkeep costs, like
```
...
level=2
upkeep=1
```
Doesn't work anymore.

**Comment by gfgtdf** [comment]
the wiki page https://wiki.wesnoth.org/UnitTypeWML doesn't mention upkeep= as an accepted parameter of [unit_type]. So i always thought it's one of those thing that onyla plpy to single units (like current hitpoints or status)

**Comment by Vultraz** [comment]
@sevu are you *sure* this was a thing?

**Comment by ProditorMagnus** [comment]
It was in unit types too.

**Comment by Vultraz** [comment]
There is no mention of upkeep in https://github.com/wesnoth/wesnoth/blob/1.12/src/unit_types.cpp. I suspect if it were ever a feature it must have been an unintentional one.

**Comment by ProditorMagnus** [comment]
Will try it again then.

**Comment by Vultraz** [comment]
To be clear, I can add this if you think it's a worthwhile feature to have.

**Comment by ProditorMagnus** [comment]
I see it indeed is not supported in 1.12 either. Still, all of Era of Magic, Era of Myths and Ageless Era attempt to use it, so I believe it would be good to support.

**Comment by ProditorMagnus** [comment]
My test was invalid, I edited source but did not preprocess it again after changes. It works in 1.12.

**Comment by sevu** [comment]
With the workaround I got Errors from the AI's logdomain that the upkeep wasn't what it would expect, so I think it has some advantage to have it in unit type.
But at the same time I would discourage people to use this, because there is no other way to see the upkeep ingame than the unit's level. The "abilities" which use this currently are kind of a hack, since they implement it in the unit_type and are just an ability to have a text for the players. Nevertheless, it isn't bad.

**Comment by gfgtdf** [comment]
making unit apply it's types upkeep on advance_to would also fix a likeley bug where remove_object would not properly remove objects that use a `apply_to=loyal` effect. So currently i support such a change.
