### ISSUE TITLE
mp lobby crashes on rezising.

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1781]
Observed on 1.13.8 release 

to reproduce:

1) Start wesnoth
2) Switch to 838x978  resolution (vertical split screen)
3) Connect to mp server
4) Maximize the window while in the mp lobby (then it has a 1680x987 resulution here)
5) wesnoth will crash and errorlog will just give 'caught std::exception'

**Comment by gfgtdf** [comment]
I cannopt reproduce this at bed7303361441170f71713daaef2efa41c3d3939 appveyor build anymore. It's possibel that this was fixed since 1.13.8 but it's also possible that this just doesn't happen in msvc builds.

**Comment by Wedge009** [comment]
I don't have this exception in either Windows or Linux. Since you can't get it to happen any more either, is it worth closing?

**Comment by gfgtdf** [comment]
I'd rather try with a mingw build first, (eigher 1.13.9 release or jenkins build)

**Comment by sevu** [comment]
Seems to be fixed.

**Comment by Wedge009** [comment]
Thanks.
