### ISSUE TITLE
preferences window looks bad on german translation

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1782]
Observed in 1.13.8

Here a screenshot, as you can it adds 2 ugly scrollbars. The vertical scrollbar on the left is probably a consequence of less vertical space due to the horizontal scorllbar.

![grafik](https://user-images.githubusercontent.com/4893136/27053035-29054308-4fbc-11e7-825b-45b954686650.png)

**Comment by Wedge009** [comment]
Not just German, but already reported in #1665.
