### ISSUE TITLE
wmlxgettext aborts after first error

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1786]
The python wmlxgettext script doesn't tolerate errors.
I don't know if this is a good or a bad thing. I think one can argue that it is better.
It has the side-effect that it tells only about one error (the first encountered) each time.

**Comment by gfgtdf** [comment]
I don't know about wmlxgettext. but i have the same problem with travis builds ( they stop after finding an error ina  file instead of trying to compile the other files). So i can tell how annoying this can be.

**Comment by CelticMinstrel** [comment]
I'd prefer if it at least had an option to try and recover from errors when possible...
