### ISSUE TITLE
UI bug for addon settings?: slider always enabled (1.13.8+dev)

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1788]
I think the UI "enabled" status might be broken in 1.13.8+dev.

Steps to reproduce:
1. install "Switch Leader" add-on.
2. Start creating new game
3. in "Custom Options" see the add-on settings
4. enable checkbox "No Limit".
5. At this moment, the bottom slider of setting the limit should be disabled. But in fact it's enabled.

I think it worked correctly in 1.12.*

**Comment by ProditorMagnus** [comment]
Checkbox cannot change state of different option. So, possible feature request, to allow options interact, but not bug.

**Comment by vn971** [comment]
@ProditorMagnus OK, I must be wrong remembering the state for 1.12.* then. Closing.

**Comment by CelticMinstrel** [comment]
You don't want to leave it open as a feature request?

**Comment by vn971** [comment]
@CelticMinstrel I guess that's not very important since it's a feature request rather than bug. I don't mind re-opening it as a feature request if developers think it's important enough.

**Comment by CelticMinstrel** [comment]
Well, it's your issue, so it's really up to you. Feature requests don't necessarily need to be important though. They might be just "nice to have"/

**Comment by vn971** [comment]
@CelticMinstrel would you be interested in this issue to be open? I would resurrect if that's the case.

**Comment by CelticMinstrel** [comment]
I don't really have an opinion one way or another.
