### ISSUE TITLE
XP Modification is broken (1.13.8+dev)

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1789]
Steps to reproduce:
1. install Xp Mod (add-on)
2. start a game, create a unit with 20 XP
3. spend that XP for unit hitpoints

Expected: unit gets more hitpoints, has XP=`14`

Actually: unit gets more hitpoints, XP is set to `-6` (negative value).

**Comment by ProditorMagnus** [comment]
This is not problem with core game, addon should not rely on $MODIFY_UNIT_store and $MODIFY_UNIT_i.

Open for https://github.com/ProditorMagnus/XP_Modification instead.

**Comment by gfgtdf** [comment]
Assuming that ProditorMagnus  is correct and it's not a problem in the core game, considering that that code already uses lua below, i reccomend just to change the expereince with lua (unlike the wiki said, unit.expereince can be set from lua)

**Comment by gfgtdf** [comment]
I took a look at your code and decided to port it all to lua, here is the code in case you want to use it, it has the disadvantage of beeing untested and not working in 1.12 though
```
--in [lua] in prestart, untested code
function wesnoth.wml_actions.xp_mod(cfg)

	local event_context = wesnoth.current.event_context
	local unit = wesnoth.get_unit(event_context.x1, event_context.y1)

	wesnoth.play_sound("fanfare-short.wav")

	unit:add_modification("object", {
		T.effect (helper.get_child(cfg, "effect"))
	})
	unit.experience = unit.experience - cfg.cost

	local speaker = string.format("%s the %s", tostring(unit.name),  tostring(wesnoth.unit_types[unit.type].name))
	local message = string.format("I spent %s xp for %s!", cfg.cost,  tostring(cfg.desc))
	wesnoth.message(speaker, message)

	local floating_message = string.format("<span color='#BCB088'>%s</span>",  tostring(cfg.desc))
	wesnoth.float_label(unit.x, unit.y, floating_message)
end


...


#define XP_MOD_MENU AMOUNT COST APPLICATION ADJUSTMENT FILTER DESC
	[show_if]
		[have_unit]
			x,y=$x1,$y1
			side=$side_number
			formula="experience >= {COST}"
			[and]
				{FILTER}
			[/and]
		[/have_unit]
	[/show_if]
	[command]
		[xp_mod]
			cost = {COST}
			desc = {DESC}
			[effect]
				apply_to={APPLICATION}
				{ADJUSTMENT}={AMOUNT}
			[/effect]
		[/xp_mod]
	[command]
#enddef

....


	[set_menu_item]
		id=xp_mod_a
		description=_ "+$Rav_XP_hp_amount hp: $Rav_XP_hp_cost xp"
		{XP_MOD_MENU $Rav_XP_hp_amount $Rav_XP_hp_cost hitpoints increase_total {XP_MOD_NOT_DRAIN} "+$Rav_XP_hp_amount hp"}
	[/set_menu_item]
	[set_menu_item]
		id=xp_mod_b
		description=_ "+$Rav_XP_hp_amount hp: $Rav_XP_hp_cost_drainer xp"
		{XP_MOD_MENU $Rav_XP_hp_amount $Rav_XP_hp_cost_drainer hitpoints increase_total {XP_MOD_DRAIN} "+$Rav_XP_hp_amount hp"}
	[/set_menu_item]
...

```

**Comment by ProditorMagnus** [comment]
Appreciated, I will try it out this weekend.

**Comment by Wedge009** [comment]
Is there any relation to #1796 (that one seems to be the core game, though, no add-on)?

**Comment by ProditorMagnus** [comment]
No, here is just addon relying on internal implementation of WML tags/macros.

**Comment by ProditorMagnus** [comment]
Been changed since https://github.com/wesnoth/wesnoth/commit/8544320b586f0b8decf56c3194ff186bf48ac010#diff-1e93e89c53ec41539fb840b29836f7de

**Comment by ProditorMagnus** [comment]
Fixed with https://github.com/ProditorMagnus/XP_Modification/commit/fef58f24234fabcbc5fb212213d0a13923d693f9

**Comment by CelticMinstrel** [comment]
So it's not actually a Wesnoth issue, then. Okay.
