### ISSUE TITLE
XP trait effects are not calculated correctly (18-2=17) when playing with XP modifier 

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1796]
![maths](https://user-images.githubusercontent.com/21158813/27207030-d0ae2e2c-523b-11e7-95e5-7f6394f3cd43.png)

the effect for this trait was -2 xp
using -5% xp instead - which means per 20xp 1 point less - didn't reduce xp  - I would expect to take some rounding taking place, and reduce xp by 1, if the max_xp are >=10)

This happens in a game with 70% xp modifier, the unit has normally 26 xp (26*0.7 = 18,2)
In a game with 100% xp modifier and the unit having 18 xp it is really reduced by 2, and by 1 if using -5%.

Must be an old bug, present in 1.12 too.

**Comment by gfgtdf** [comment]
this is probably due to the way how expereince_modifer is currently applied: I think it calculates: (26 -2) *0.7 = 16.8 -> rounded to 17


Note however that this depend on how the unit got that trait, if the trait is applied ba an event a different rule might apply.

**Comment by gfgtdf** [comment]
I personally have  no objections againt changign that code so that xp_modifer will just effect the unit_types base max_experience and nothing else though.

**Comment by Lanternglow** [comment]
Code for modifying max experience by a percentage: `max_experience_ = lexical_cast_default<int>(set)*max_experience_/100;`
I think this is due to floating point truncation. Which isn't what is expected. In real number math, the calculation would be correct, but not when dealing with discrete values.
What would be more expected is to calculate the experience change and truncate that. Then adjust the max experience by that.

**Comment by gfgtdf** [comment]
> Code for modifying max experience by a percentage: `max_experience_ = lexical_cast_default<int>(set)*max_experience_/100;`

I think you are looking at the wrong code there, the more comon way to modify a unit expierience by percentage is by doing things like `increase=20%` not `set=120%`, also the code in in the first post does no midify the exierirnce by percentage, it jus says `+2` not `+2%`

**Comment by sevu** [comment]
Any chance for this still going into 1.14 ?
