### ISSUE TITLE
Addons list is redownloaded after every operation

### ISSUE THREAD

**Issue by Polsaker** [wesnoth/wesnoth#1800]
Currently, the addon list is redownloaded after every operation, this is pretty annoying when you have a slow connection and have to install a bunch of addons.

A possible solution would be to store the addon list locally and use Etags to check whether it should be redownloaded.

Another option to solve this would be to add bulk installing for addons.

**Comment by CelticMinstrel** [comment]
What's "Etags"?

**Comment by GregoryLundberg** [comment]
A way for web browsers to detect that a file on the server has changed. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

Since the server is on Linux, you could use the inode and last-mod date/time to simulate an HTTP ETag header

**Comment by Polsaker** [comment]
> Since the server is on Linux, you could use the inode and last-mod date/time to simulate an HTTP ETag header

From what I've seen, the addon server is already including ETags with every request.

**Comment by CelticMinstrel** [comment]
If you mean when visiting the web page in the browser, that's not relevant here, as the addons client does not download over HTTP.

**Comment by donovanamitchell** [comment]
Would downloading the addon list once upon opening the addon manager be an acceptable solution?

**Comment by Polsaker** [comment]
Yes
