### ISSUE TITLE
Add new --log-fps launch option

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#1801]
Largely related to [this](https://forums.wesnoth.org/viewtopic.php?f=6&t=46442) thread, it would write the value displayed by the --fps option to a file at some interval.

**Comment by Wedge009** [comment]
Just for clarity, where is this feature in current code? I'm not that interested in it myself, but I note this issue is 'closed as completed'.

**Comment by Pentarctagon** [comment]
It ended up getting rolled into the `--fps` option rather than as a separate flag. It gets written to `<userdata dir>/fps_log.csv`:
https://github.com/wesnoth/wesnoth/blob/870bd715219e319c174ee124af6005c795dc9189/src/display.cpp#L1347

**Comment by Wedge009** [comment]
Nice. You implemented your own enhancement request. (:
