### ISSUE TITLE
Under burning Suns bug

### ISSUE THREAD

**Issue by DPJulien** [wesnoth/wesnoth#1804]
There is a lua, WML problem. I can't continue the campaign. This is the sixth scenario I think.

Thanks,
Julien

[SlSB-Dans_les_tunnels_trolls_Tour_1.gz](https://github.com/wesnoth/wesnoth/files/1085400/SlSB-Dans_les_tunnels_trolls_Tour_1.gz)

**Comment by ln-zookeeper** [comment]
This has already been fixed, please see https://forums.wesnoth.org/viewtopic.php?p=614446#p614446 for instructions of how to fix the problem locally before the next Wesnoth release.
