### ISSUE TITLE
game crash attack_prediction.cpp:1734

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1808]
wesnoth crashes with the following message in the logs:
```
wesnoth: src/attack_prediction.cpp:1734: double {anonymous}::calculate_probability_of_debuff(double, bool, double, double, bool, double): Assertion `prob_kill >= 0.0 && prob_kill <= 1.0' failed.
```

Savegame: https://pointsgame.net/vn971/temp/2017.06.21_17:47:12_f5d47a0.bz2
The crash happens at AI turn, after you press "end turn" (immediately after loading the game).
It's not deterministic. I had to do about 5 "reload ->end turn" cycles before it crashed last time.

**Comment by vn971** [comment]
UPD: it happens in 0.5 seconds after **red** player gets his turn.

**Comment by jyrkive** [comment]
Regression from commit 93be1487fac79406c30c71e5b2a79e43ca722770. I'll investigate ASAP.

**Comment by vn971** [comment]
In this savegame, crash occurs after "end turn" almost each time: https://pointsgame.net/vn971/temp/2017.06.21_19:56:10_74fecb1.bz2
