### ISSUE TITLE
save preferences instantly

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1809]
Clicking the "Close" button on Preferences window doesn't save preferences to disk. (It only applies them locally).
If wesnoth is somehow killed (or crashed, or stopped in development, or whatever), altered settings are lost. It would be great to write them down instantly.

Thanks

UPD: this was the default behavior in wesnoth-1.12

**Comment by CelticMinstrel** [comment]
Note that not all preferences are set by the preferences dialog. Many things in the preferences file are set by other actions, such as what you select in the MP Create dialog. As such, saving on clicking "Close" would not prevent all instances of data loss in the event of a crash.

On the Mac, the application's preferences file (which must be a plist) is automatically saved in the background. I wonder if this would be easy to implement in Wesnoth?

**Comment by vn971** [comment]
@CelticMinstrel also note that this used to work already, so unless it was heavily refactored, it shouldn't generally be hard to bring something back. Also, settings were actually applied the instant you changed them. So, for example, when you disable/enable Sound, it starts/stops playing immediately.

**Comment by CelticMinstrel** [comment]
If it's "save on dialog close", then I guess that should be easy to bring back, yeah.

**Comment by vgaming** [comment]
@Vultraz thanks a lot!
That was really important in some cases.
