### ISSUE TITLE
failed assertion attack_prediction.cpp:1627

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#1810]
Finishing this turn https://pointsgame.net/vn971/temp/2017.06.21_19:56:10_74fecb1.bz2  causes wesnoth to fail on assertion:

```
wesnoth: src/attack_prediction.cpp:1627: static void {anonymous}::monte_carlo_combat_matrix::scale_probabilities(const std::vector<double>&, std::vector<double>&, double, unsigned int): Assertion `std::abs(std::accumulate(target.begin(), target.end(), 0.0) - 1.0) < 0.001' failed.
```

wesnoth version is 1.13.8+dev (2de925e4e6-Clean).

**Comment by vn971** [comment]
@CelticMinstrel it's not UI though, it's underlying game mechanics (and math).

**Comment by vn971** [comment]
Maybe it can be called AI because it affects it the most.

**Comment by CelticMinstrel** [comment]
Yeah, I wasn't sure which purple label to give it. We probably need a few more purple labels. I was thinking "Game" might be the most appropriate, but apparently that doesn't exist.

**Comment by vn971** [comment]
@CelticMinstrel I'm personally not very familiar with wesnoth codebase, so I don't really know. Probably no bug or `AI` would do in this case. But I guess it doesn't matter much for a closed ticket anyway.

**Comment by jyrkive** [comment]
AI is definitely a more suitable label IMO.
