### ISSUE TITLE
Use Map Settings sets incorrect village gold

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#1814]
1.13.8+dev

When loading an mp map in a local game, such as Hamlets, if you have Use Map Settings checked, it displays a village gold of 2 in game configuration. But when you launch the map, there is a village gold of 1.

When Use Map Settings is unchecked, the correct gold value is used.

**Comment by CelticMinstrel** [comment]
This sounds like a basic flipped conditional somewhere...

**Comment by Vultraz** [comment]
Confirmed this is fixed. Should have closed this a long time ago...
