### ISSUE TITLE
Force Modification key & dialog not working correctly

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#1815]
1.13.8+dev

The scenario '1p - Custom Campaign', that comes with the Custom Campaign add-on, uses the force_modification=yes key. When the scenario is selected without the Custom Campaign modification, a dialog is triggered that asks if you would like to activate the modification. This dialog does not appear to be working correctly.

To reproduce:
Install add-on Custom Campaign.
Go to mp game setup
Select scenario '1p - Custom Campaign'
The dialog says it requires the custom campaign modification, would you like to apply the changes?
Click 'yes'
At this point, the modification's box is not checked. The player still has to go and check it, to get it to work.

**Comment by Vultraz** [comment]
Ah, I wondered when this would finally bite me in the ass...

**Comment by gfgtdf** [comment]
iirc i did some related fixes recently

**Comment by sigurdfdragon** [comment]
confirmed fixed, thanks
