### ISSUE TITLE
mp lobby on small resolution

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1825]
On low resolution you get behaviour like this:
I happens not every time, bit moving the gold slider triggers it every time.
One can back to normal if one hovers with the mouse over one of the popup textes (not really a popup... maybe floating text fit's it better)
No issue on normal resolution, this is 800x600.
![low_resolution](https://user-images.githubusercontent.com/21158813/27641562-8af3d18a-5c1c-11e7-9bef-80618545e04f.png)

**Comment by Wedge009** [comment]
Are you referring to the issue of everything fading to black? This isn't limited to Linux and sounds very much the same as #1583. Let me know if it is not.

**Comment by sevu** [comment]
It's a duplicate of it.

**Comment by Wedge009** [comment]
Thanks.
