### ISSUE TITLE
help on low resolution 

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1826]
The table view doesn't work on 800x600 

![bildschirmfoto von 2017-06-28 20-05-40](https://user-images.githubusercontent.com/21158813/27652889-a0a52864-5c3d-11e7-8886-c8b3d396f543.png)

**Comment by Wedge009** [comment]
I understand Help is being converted to gui2 soon.

**Comment by sevu** [comment]
Ok. Maybe in that rush some other help related bugs can be fixed too.
I will post some feedback when this happens.

**Comment by CelticMinstrel** [comment]
The presence of the GUI2 help branch is the reason why I've been considering most help-related bugs to be "postponed" until after its completion. I can't say whether we'll be able to finish it in time for 1.14, but I kind of hope we can.

**Comment by pydsigner** [comment]
If (not "since") we're waiting for accelerated rendering, I don't see why
we wouldn't put the updated help in too.

**Comment by CelticMinstrel** [comment]
If we were waiting for accelerated rendering, then yeah, the GUI2 help would probably get in too, but I was pretty sure we weren't waiting for accelerated rendering. I know vultraz has put a lot of work into it, but it's quite likely that the rendering performance issues can be solved more simply in order to get a timely 1.14 release out.

**Comment by Wedge009** [comment]
Reconfirmed for 1.14.9. Noting postponed until Help is on gui2.

**Comment by Wedge009** [comment]
#3653 is merged. However, it's not yet in a good state especially for low-resolution display.
![image](https://github.com/user-attachments/assets/1992d8cc-2ddb-4b86-92fe-b18f6e263aff)

**Comment by CelticMinstrel** [comment]
I think @babaissarkar's idea of making the menu be completely collapsed by default and you click on it to expand it would work really well for lower resolutions.

**Comment by Wedge009** [comment]
I'm not sure what you mean. From what I saw, the menu is completely fixed and takes up the majority of the display.

**Comment by CelticMinstrel** [comment]
I'm talking about a suggestion that was made before. Basically, the sidebar menu wouldn't be visible at all, and you'd click a button or something to make it pop up, kinda like a menu, and it would overlap (possibly even entirely replace on smaller resolutions) the topic area. It's a bit hard to describe in words though…

**Comment by Wedge009** [comment]
Oh right, suggestion for improvement, not a description of the current state.

**Comment by CelticMinstrel** [comment]
Right.

**Comment by babaissarkar** [comment]
https://www.youtube.com/watch?v=S9OiWe5iBYo

A video that explains the concept.
