### ISSUE TITLE
X server Ubuntu bug

### ISSUE THREAD

**Issue by cipiricus** [wesnoth/wesnoth#1828]
When the game is full screen I can't use Fn+Vol Up/Down or Mute from my laptop, must make game in window mode to can use Fn. Version 1.12.6

**Comment by CelticMinstrel** [comment]
Could you test if you get the same issue in 1.13.8?

**Comment by Wedge009** [comment]
I recall another issue with laptop buttons, albeit in Windows, in #1564. Probably not related, though.

It does seem interesting that full-screen would block out volume button operation. Maybe that mode some how blocks those keys being passed on to the OS?

**Comment by cipiricus** [comment]
CelticMinstrel, I'll try as soon possible, first I have to finish with exams at my college

**Comment by sevu** [comment]
That's not the case any more in 1.13 since the switch to sdl2.
You couldn't tab out of the game or adjust brightness either previously.

**Comment by soliton-** [comment]
Any news on this? Is this fixed in 1.13?

**Comment by sevu** [comment]
It is.
