### ISSUE TITLE
Installing or uninstalling an add-on un-applies search filter

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#1829]
Installing or uninstalling an add-on results in the full list of add-ons being displayed again, but the search filter text is not cleared([link](https://i.imgur.com/M0Ni2HZ.png)).

**Comment by Pentarctagon** [comment]
Why was this given the `MP Lobby` label?

**Comment by CelticMinstrel** [comment]
I wonder if the addons manager is important enough to get its own label...
