### ISSUE TITLE
Why isnt Wesnoth in GNOME Software?

### ISSUE THREAD

**Issue by retiform** [wesnoth/wesnoth#1831]
All that it needs is an appdata file to show up, and to be in their respitory, so is there any reason that it is not or is that on the GNOME devs?  Since GNOME Software is the most popular software center for linux, it would be nice if Wesnoth was on there.

**Comment by GregoryLundberg** [comment]
https://forums.opensuse.org/showthread.php/504777-How-to-add-manually-installed-software-to-gnome-software

gnome-software in a specific application program. The assertion that it's "most popular" is debatable, at best.

This is an issue for the package maintainer, and you don't specify which package you used.

I just tested on Arch using LXQt. The appdata file was installed and BfW shows in my Games menu.

**Comment by Pentarctagon** [comment]
It seems like this is sort of like why Wesnoth isn't available on XYZ service or store.  Really, it'd probably be best to get around to getting Wesnoth on Steam, see how that goes, then try to expand from there.

**Comment by CelticMinstrel** [comment]
Seems silly for it to be labelled invalid when it was actually addressed...
