### ISSUE TITLE
storing + unstoring might readd abiltites to units.

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1837]
Assume there is a normal elvish shaman at (7,7) and 

Code1
```
[store_unit]
  variable="a"
  [filter]
    x=7
    y=7
  [/filter]
[/store_unit]
[clear_variable]
  name = "a.abilities.heals[0]"
[/clear_variable]
[unstore_unit]
  variable = "a"
[/unstore_unit]
[clear_variable]
  name = "a"
[/clear_variable]
```

Code2
```
[store_unit]
  variable="a"
  [filter]
    x=7
    y=7
  [/filter]
[/store_unit]
[unstore_unit]
  variable = "a"
[/unstore_unit]
[clear_variable]
  name = "a"
[/clear_variable]
```

If you now execute Code1 the shaman will loose its healing ability (as it should). If you then execute code2 whihc does noting bug storing+unstoring the unit the shaman will regain it's healing ability (unexpected).

**Comment by ln-zookeeper** [comment]
I don't think it's entirely unexpected; if you unstore a unit that's missing some property, then it is supposed to get re-created based on the unit type. For example if you have made direct modifications to unit.max_moves, you can restore the original natural value by clearing unit.max_moves and unstoring.

I suppose the question of which keys/tags it should apply to is a bit fuzzy. But if you make a direct modification that completely removes a key/tag that the unit should have according to its type, then it doesn't strike me as obviously a bug if it gets recreated upon unstoring.

**Comment by gfgtdf** [comment]
> But if you make a direct modification that completely removes a key/tag that the unit should have according to its type, then it doesn't strike me as obviously a bug if it gets recreated upon unstoring.

The point is that i don't delete the [abilitites] tag, that's also why the [unstore_unit] in Code1 will not automatically readd the [heals] ability. This only happens if you use Code2 after that.

**Comment by CelticMinstrel** [comment]
Maybe we should just revert 72e9dee. How much difference does it even make to save file size? Probably not that much, right? And I seem to recall it was causing other problems, too.

**Comment by gfgtdf** [comment]
> How much difference does it even make to save file size? 

Uncompressed, a single (normal without any modification) unit is about 300byte/150lines in the cfg file. an empty tag about 30bytes/2lines. In the best (and unlikeley) case that commits saves 5 empty tags per unit.


> Maybe we should just revert 72e9dee

Yes i also think we should (at least partly) revert it. Mabye we could  keep it for [filter_recall] or other tags that are very rareley used. Not sure though.

**Comment by CelticMinstrel** [comment]
So if there are 100 units (total for all sides), and your numbers are accurate, the uncompressed savings are about 100 lines, or 15,000 bytes, or 15kb, or 14.6kib. That doesn't seem all that significant; and I imagine the compression would narrow that down quite a bit, since compression is usually good with patterns.

**Comment by gfgtdf** [comment]
there was a type on my laste message it should ofc be 3000bytes for the 150lines not 300 (which would be only 1 chracter per line...)

**Comment by CelticMinstrel** [comment]
Well, that makes the savings even less significant.

**Comment by doofus-01** [comment]
For what it's worth, I found that "savings" commit to be quite inconvenient.  I eventually fixed all the places it broke things in my UMCs (at least I think I did) by writing dummy keys to keep the tags from being deleted.  I don't know how representative my case is of other UMCs, but I'd guess that you'll spare at least some authors a bit of frustration if you revert it.

**Comment by gfgtdf** [comment]
since this a rather easy thing to do we should do it before 1.13.9, @Vultraz any opinions on reverting 72e9dee40d2616986d1f52447a1633f7e11a64e4 ?

**Comment by Vultraz** [comment]
Perhaps you could explain why exactly that results in abilities being re-added in the first place.

**Comment by gfgtdf** [comment]
> Perhaps you could explain why exactly that results in abilities being re-added in the first place.

that'w what i did in the first post

**Comment by gfgtdf** [comment]
if it's really the visuals in the unit stus window that bothers people we could maybe just push the empty tags to the bottom of the unitwml, any opinions ?

**Comment by Vultraz** [comment]
Well configs are sorted alphabetically so it would have to be in the Inspector itself but still, that's acceptable.

**Comment by CelticMinstrel** [comment]
I don't think it's a great idea, but I suppose it'll work as long as it doesn't affect `[variables]`.

**Comment by gfgtdf** [comment]
> Well configs are sorted alphabetically 

This applies only to attributes, not to child configs.

> I don't think it's a great idea, but I suppose it'll work as long as it doesn't affect `[variables]`.

The thouht was also about [varaibles] tag (not the content of the variables though, onyl te empty [varaibels] tag itself will be pushed to the bottom)

**Comment by CelticMinstrel** [comment]
Yeah, that's what I was talking about - don't sort the contents of `[variables]` and it should be fine. More generally, don't sort _anything_ where it's expected that someone may want to directly access it via Lua, because the order of the children is actually significant in that context, and it would be bad for the inspector window to not reflect the true order (and even worse for the order to be disrupted by opening the inspector window).

**Comment by Vultraz** [comment]
Why the hell does order of tags matter in Lua? That seems like design very prone to breakage.

**Comment by CelticMinstrel** [comment]
It has nothing to do with Lua and everything to do with the WML format. The only reason the order _doesn't_ matter when working in WML is that the WML variable syntax offers no way to say "fetch me the child at index n regardless of its tag name".

**Comment by gfgtdf** [comment]
Obviously the order also matters in wml, just think about actionwml in events where the actionwml tags are processed in order and not in alphabetical order.

**Comment by CelticMinstrel** [comment]
Yes, but it _doesn't_ matter (except between tags with the same name) when accessing WML variables, which is the case that is really relevant here.

**Comment by Vultraz** [comment]
I don't follow.

**Comment by CelticMinstrel** [comment]
WML consists of an ordered list of tags, so if you change the order, the configs are no longer equal. WML variables ignore the relative ordering of differently-named tags, but in Lua and in C++, you can ask either for the nth tag with a particular name, or the nth tag overall.
