### ISSUE TITLE
Cannot debug scenario from command line without 'allow_new_game=yes'

### ISSUE THREAD

**Issue by Coffee--** [wesnoth/wesnoth#1843]
Since commit 5f40636fa9041f7da1b7da6157788f743e1d8d74 you can't enter a scenario from the command line parameter "--scenario=ID" without setting "allow_new_game=yes".

A minor thing, but for debugging this would be good to work regardless when starting Wesnoth from the command line with the --scenario switch.

**Comment by gfgtdf** [comment]
just to be sure: You want to use --scenario switch to enter a specific scenario in a multiplayer [campaign]?

**Comment by Coffee--** [comment]
Yeah, I want to start a multiplayer scenario. I would think that others might want to start from a specific scenario in a campaign from the command line as well.

**Comment by gfgtdf** [comment]
> Yeah, I want to start a multiplayer scenario

that is part of a [campaign] ?

**Comment by Coffee--** [comment]
Looks like it is now working for me as expected.

Apologies if I got the command wrong or whatever made me think this was an issue.
