### ISSUE TITLE
Mouse not interacting with main game window

### ISSUE THREAD

**Issue by sapientN3T** [wesnoth/wesnoth#1844]
As [reported](https://forums.wesnoth.org/viewtopic.php?f=5&t=46094&start=60#p613491) by Eagle_11 on the forums (1.13.8, Windows 10):

> Encountered strangeness: Cant perform any action ingame. Only menu buttons work. Cant select an unit, cant rightclick on a hex, hovering the mouse over an hex doesnt acquisition it at all. Mouse not interacting with main game window, somehow. 
> This on Win10 if it helps. Infact, im almost sure if tried on win7 would work so im baffled on what is missing on win10.
> edit1: Managed to recruit an unit through dropdown Actions menu. Still cant select anything.
The texts in options menu got cutoff despite 1920x1080 resolution.
> edit2: at 3. restart, everything magically functions as intended.

This issue was also seen previously with version 1.13.7 for Windows 7. Restarting Wesnoth did not resolve the problem in that case. It was thought to be fixed in 1.13.8, so the bug was closed at gna.org.

There has now been [another report](https://forums.wesnoth.org/viewtopic.php?f=4&t=46582#p615487) on the forums for version 1.13.7 with Windows 10 by forum user Bluedragon13

**Comment by gfgtdf** [comment]
Do you know whether the menu bars still work? If yes it could be the same as https://github.com/wesnoth/wesnoth/issues/1622 (also reported by you)

**Comment by sapientN3T** [comment]
@gfgtdf Wow, how did I miss that. Yeah I'm pretty sure this is a duplicate. Sorry I searched but missed that one.
