### ISSUE TITLE
MacBook Pro 2017 13' resolution problem. Retina Support?

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#1848]
I compiled latest dev version of wesnoth from origin:master e1e336a and I have problem with screen resolution.

I have new 2017 MacBook Pro 13inch with screen resolution 2560x1600. I am ofc able to start game but I can't select higher resolution than 1440x900 (I simply don't have higher options).

I already created topic on Wesnoth's forum: https://forums.wesnoth.org/viewtopic.php?f=4&t=46576&p=615459#p615459

My question was simply: "Where is the problem?"
Now I have some new knowledge.

**What I tried and know so far:**
- I already tried pass SDL_WINDOW_ALLOW_HIGHDPI flag to SDL's window.
- I have 'High Resolution Capable' bool in _Info.plist_ (manifest).
- I think that problem is located in file _src/video.cpp_ . I tried debug and change some functions in that file but effect was not really related to this problem.
- I found that very old version of Wesnoth (1.11.15) works good but doesn't have scaling. I can select my resolution in fullscreen. I get window which fits in my screen but texts are very small. I need them about 250% bigger. Not only them, actually all elements like buttons.

**What I'll do now?**
- I'll continue with debugging and researching around this issue.
- I'll try to find when does it start. (As I said, it somehow worked in 1.11.15 . I want to know from which version is it broken. So far I know that it was already broken in version 1.13.5)

**My build environment:**
OS: macOS High Sierra 10.13 Beta 3 (17A306f)
GPU: Intel Iris Plus Graphics 650 1536 MB
Display: 13,3-inch (2560 x 1600)
Language: Czech, English US

Wesnoth: Battle for Wesnoth v1.13.8+dev (e1e336a46c-Modified)
How/Where: I built it myself from origin:master branch using xcode. I am not using provided mac compile stuff. I am using own libraries built from source using Homebrew.
Wesnoth's game and build infos:
```
The Battle for Wesnoth version 1.13.8+dev (e1e336a46c-Modified)
Running on Apple OS X 10.13

Game paths
==========

Data dir:        /Users/user/xcode/wesnoth/projectfiles/Xcode/build/Products/Debug/Wesnoth.app/Contents/Resources
User config dir: /Users/user/Library/Application Support/Wesnoth_1.13
User data dir:   /Users/user/Library/Application Support/Wesnoth_1.13
Saves dir:       /Users/user/Library/Application Support/Wesnoth_1.13/saves
Add-ons dir:     /Users/user/Library/Application Support/Wesnoth_1.13/data/add-ons
Cache dir:       /Users/user/Library/Application Support/Wesnoth_1.13/cache

Libraries
=========

Boost:             1.64
OpenSSL/libcrypto: 1.0.2l  (runtime 1.0.2l)
Cairo:             1.14.10 (runtime 1.14.10)
Pango:             1.40.7  (runtime 1.40.7)
SDL:               2.0.5   (runtime 2.0.5)
SDL_image:         2.0.1   (runtime 2.0.1)
SDL_mixer:         2.0.1   (runtime 2.0.1)
SDL_ttf:           2.0.14  (runtime 2.0.14)
libpng:            1.6.30  (runtime 1.6.30)

Features
========

Experimental OpenMP support:    no
PNG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: no
Cocoa notifications back end:   yes
Growl notifications back end:   no
```

**Comment by Thunderforge** [comment]
I have the same model of MacBook Pro and version 1.12.6 gives me the options to select resolutions up to 2880x1800 (including 2560x1600 that you mention).

**Comment by hrubymar10** [comment]
Well @Thunderforge ,
Please post your Wesnoth version. Follow these instructions https://forums.wesnoth.org/viewtopic.php?t=25660 .

Also are you using built in retina display of your macbook or external minitor?

**Comment by Thunderforge** [comment]
@hrubymar10 It looks like those instructions only work for 1.13.2 and above. As I said, I'm running 1.12.6, the latest version that I can download from wesnoth.org. Here is a screenshot of the version number in both the bottom left corner and the title bar.

![wesnoth 1 12 6](https://user-images.githubusercontent.com/6200170/35713075-0d1aa5d4-078b-11e8-8813-d82270b07470.png)

I am using the built-in Retina display; no external monitor. I'm on macOS 10.13.3.

**Comment by sevu** [comment]
When you scroll down on wesnoth.org you can choose between the stable and development version, maybe you can try that.

**Comment by Thunderforge** [comment]
I can reproduce this error with 1.13.10b. The highest resolution that is available on my MacBook Pro's built-in retina display is 1440x900.

<img width="1552" alt="wesnoth 1 13 10b" src="https://user-images.githubusercontent.com/6200170/35717161-1635aade-07a3-11e8-8fad-94c1cfd2f2cb.png">

**Comment by hrubymar10** [comment]
Well, I can remember now. We already know this.

Version 1.12.6 in window mode have 2560x1600 resolution but wesnoth can't scale so if you apply this resolution on 2x HDPi monitor than you will got this:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2218817/35725949-7c89ce68-0803-11e8-9856-4a4fe8737477.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2218817/35725973-8f721ada-0803-11e8-8f8c-71ad76a27db6.png">


And when you try apply it inside fullscreen mode than it works of course but game isn't scaled so everything became very small:
![image](https://user-images.githubusercontent.com/2218817/35726080-e0a9cd08-0803-11e8-8666-a3fb1076f597.png)
![image](https://user-images.githubusercontent.com/2218817/35726102-f9eb9102-0803-11e8-98a7-f5a1a4bd1435.png)

Wesnoth 1.12.6 doesn't have font scaling which should help.

And one off topic, Wesnoth 1.12.6 downloaded from wesnoth.org looks like 32-bit binary so on 1.13.4 beta and higher (including next stable release) you will get this message about future removing 32-Bit slice support from macOS https://developer.apple.com/news/?id=12012017a

<img width="532" alt="image" src="https://user-images.githubusercontent.com/2218817/35726269-97a62c72-0804-11e8-8a14-e1f743cf2947.png">

**Comment by hrubymar10** [comment]
Another facts:

1.12.6 doesn't have 'Open in Low Resolution' option

![2018-02-02 at 10 35](https://user-images.githubusercontent.com/2218817/35726374-fd6d867c-0804-11e8-8c5d-419f3950399f.png)

but 1.13.10 has this option:

![2018-02-02 at 10 37](https://user-images.githubusercontent.com/2218817/35726453-3e9b71d6-0805-11e8-9d35-052bcd6a0b17.png)

Diference is for example in title bar:
1.12.6
<img width="182" alt="image" src="https://user-images.githubusercontent.com/2218817/35726488-5f431682-0805-11e8-86aa-4618f69a6a78.png">

1.13.10
<img width="360" alt="image" src="https://user-images.githubusercontent.com/2218817/35726507-6c6d732a-0805-11e8-9910-5e519c5150fb.png">


This is because of SDL.

1.12.6 uses SDL 1.2.14
1.13.10 uses SDL 2.0.7

**Comment by Thunderforge** [comment]
@hrubymar10 I've spun off the 32-bit app warning #2427. Thanks for spotting that!

**Comment by singalen** [comment]
What remains is, I believe, a HiDPI support issue, i.e. a duplicate of #2219.

This is the responsible line: https://github.com/wesnoth/wesnoth/blob/master/src/video.cpp#L393
and this is the reason: [`SDL_GetDisplayBounds` is returning screen size in "points" on HiDPI displays](https://discourse.libsdl.org/t/hidpi-support-on-mac-os-x/20020).

**Comment by hrubymar10** [comment]
It was discussed many times already. HiDPi/Retina support is not so simple thing. Mainly because of current WMLtheme.

I have working 1.5x Scalling on iPhone 5S with iOS version of Wesnoth but it uses many workarounds and one is hardcoded into SDL so not ideal way how to do that.

**Comment by singalen** [comment]
I remember a very different conclusion from the last discussion with Vultraz. To me, HiDPI seems more or less simple, just not thought through yet.

Anyway, this one is a duplicate and can probably be closed.

**Comment by hrubymar10** [comment]
I'll close this issue as it is very old now.

Current 1.15.x and also 1.14.x doesn't support HiDPI scaling but at least on macOS it is fully playable with downscaled resolution. IIRC before was everything blurry now it isn't. Sure I can see pixels of font, but it is sharp now so I it doesn't feel unplayable an my eyes doesn't hurt anymore.

HiDPI issue is opened here: #2219 

This macOS only issue is solved.

Closing
