### ISSUE TITLE
Game crashes with EXC_BAD_ACCESS while saving generated map in map editor.

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#1849]
Tittle say it all, I'll post here only some useful informations like how to reproduce it.

**How to reproduce it:**
1. Build game through Xcode (I built DEBUG target).
2. Start game.
3. When game starts click 'Map Editor' button.
4. Click 'Map' button in upper menu and select 'Generate Map'
5. Generate random map
6. When your map is generated, click 'File' button in upper menu and select 'Save Map'
BOOM, game will crash

**What I know so far:**
- Game crash with message: 
> Thread 1: EXC_BAD_ACCESS (code=2, address=0x7fffd3fde058)
- And Xcode (as debuger) shows me file '_collator.h_' in path _/usr/local/Cellar/boost/1.64.0_1/include/boost/locale/collator.hpp_ on line 120

**My build environment:**
OS: macOS High Sierra 10.13 Beta 3 (17A306f)
GPU: Intel Iris Plus Graphics 650 1536 MB
Display: 13,3-inch (2560 x 1600)
Language: Czech, English US

Wesnoth: Battle for Wesnoth v1.13.8+dev (e1e336a46c-Modified)
How/Where: I built it myself from origin:master branch using xcode. I am not using provided mac compile stuff. I am using own libraries built from source using Homebrew.
Wesnoth's game and build infos:
```
The Battle for Wesnoth version 1.13.8+dev (e1e336a46c-Modified)
Running on Apple OS X 10.13

Game paths
==========

Data dir:        /Users/user/xcode/wesnoth/projectfiles/Xcode/build/Products/Debug/Wesnoth.app/Contents/Resources
User config dir: /Users/user/Library/Application Support/Wesnoth_1.13
User data dir:   /Users/user/Library/Application Support/Wesnoth_1.13
Saves dir:       /Users/user/Library/Application Support/Wesnoth_1.13/saves
Add-ons dir:     /Users/user/Library/Application Support/Wesnoth_1.13/data/add-ons
Cache dir:       /Users/user/Library/Application Support/Wesnoth_1.13/cache

Libraries
=========

Boost:             1.64
OpenSSL/libcrypto: 1.0.2l  (runtime 1.0.2l)
Cairo:             1.14.10 (runtime 1.14.10)
Pango:             1.40.7  (runtime 1.40.7)
SDL:               2.0.5   (runtime 2.0.5)
SDL_image:         2.0.1   (runtime 2.0.1)
SDL_mixer:         2.0.1   (runtime 2.0.1)
SDL_ttf:           2.0.14  (runtime 2.0.14)
libpng:            1.6.30  (runtime 1.6.30)

Features
========

Experimental OpenMP support:    no
PNG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: no
Cocoa notifications back end:   yes
Growl notifications back end:   no
```

**Comment by GregoryLundberg** [comment]
I cannot this issue reproduce using Linux.

Can you re-test using a stable, released version of your operating system? High Sierra is in early Beta and may be the cause of the failure you're seeing when trying to save a file.

**Comment by CelticMinstrel** [comment]
This sounds like the same locale-related crash that has been reported before. If so, you should get the crash also by just entering the editor and clicking Load Map.

There has been quite some discussion as to the cause of the crash, and we concluded that it's likely some kind of binary compatibility between the dependencies (I think we concluded it was most likely Boost and either ICU or iconv).

**Comment by hrubymar10** [comment]
Yes, @CelticMinstrel exactly described the problem. At this case it happend because of boost. I don't have access to stable OS right now. I'll let you know when I'll have access and do some tests.

**Comment by CelticMinstrel** [comment]
Whoops, apparently I said "binary compatibility" when I really meant "binary *in*compatibility'.

**Comment by hrubymar10** [comment]
So today I tried it on stable macOS and yes @GregoryLundberg , bug also exists here. I can reproduce it.
Builded from newest origin:master 1b7bc55

```
The Battle for Wesnoth version 1.13.8+dev (1b7bc55f19-Modified)
Running on Apple OS X 10.12.6

Game paths
==========

Data dir:        /Applications/Wesnoth.app/Contents/Resources
User config dir: /Users/user/Library/Application Support/Wesnoth_1.13
User data dir:   /Users/user/Library/Application Support/Wesnoth_1.13
Saves dir:       /Users/user/Library/Application Support/Wesnoth_1.13/saves
Add-ons dir:     /Users/user/Library/Application Support/Wesnoth_1.13/data/add-ons
Cache dir:       /Users/user/Library/Application Support/Wesnoth_1.13/cache

Libraries
=========

Boost:             1.65
OpenSSL/libcrypto: 1.0.2l  (runtime 1.0.2l)
Cairo:             1.14.10 (runtime 1.14.10)
Pango:             1.40.11 (runtime 1.40.11)
SDL:               2.0.5   (runtime 2.0.5)
SDL_image:         2.0.1   (runtime 2.0.1)
SDL_mixer:         2.0.1   (runtime 2.0.1)
SDL_ttf:           2.0.14  (runtime 2.0.14)
libpng:            1.6.31  (runtime 1.6.31)

Features
========

Experimental OpenMP support:    no
PNG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: no
Cocoa notifications back end:   yes
Growl notifications back end:   no
```

**Comment by singalen** [comment]
This locale-related crash? #2094

**Comment by hrubymar10** [comment]
So it should be workarounded already? I’ll try reproduce it asap.

**Comment by singalen** [comment]
Yes, should have been already worked around in e16e4baf791c006352a7032cab4ce85b083d02bb somewhere in editor.

**Comment by hrubymar10** [comment]
It looks like that it is fixed. I can't reproduce it now.

Closing as fixed
