### ISSUE TITLE
chat doesn't work during [delay]

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1856]
as said in the title, during a [delay] the players should be able to send & receive chat messages but they can't

**Comment by CelticMinstrel** [comment]
Does delay use something like `SDL_Delay`? The proper implementation would be to lock out player controls and just run a game loop until the delay is expired... there's a function called somewhere from the AI that should have that effect.

**Comment by gfgtdf** [comment]
delay doesn't freeze the game, you can still open the chatbox, you also see the chat that you just entered at the left-upper corner of the window. It just that you don't receive chat form other and/or the chatmessages  are not immidiatley send to others.

**Comment by CelticMinstrel** [comment]
Ah, so it probably is implemented (mostly?) correctly then.

**Comment by gfgtdf** [comment]
yes the only problem is that the chat isn't sended (or received by, not sure here) to other players until after the [delay] (or probably the whole user action?) has finished. I perosnally think this is still an important issue.

The problem with trying to read chat from the network during [delay] is that one might find other user commands, (recruit/recall etc.) that cannpt be processed during a delay and the network thing (playturn_network_adapter.cpp) doesn't have a 'push_front()' function to push those unhandled netorkpackages back for later.

**Comment by gfgtdf** [comment]
it'd be nice if this could go into 1.14 or 1.14.1 . No gurantee though: since i dont know yet how involved such a fix would be i cannot say right now whether it'd be good for 1.14
