### ISSUE TITLE
attempting to chat during [delay] in a start event blocks the game

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1857]
i just tested with an addon that does 
```
	[event]
		name=start
		[lua]
		code = <<
				wesnoth.delay(10000)
		>>
		[/lua]
	[/event]
```

when you now enter a chat message from player 1 during thay [delay] the follwing happens:
1) The chat message immidiatley appears at the client 1s screen
2) After 10 second the chat message immidiatley appears at the client 2s screen
3) The 'new turn' dialogs never shows and it seems like the game never reaches 'turn 1' on client 1: The 'end turn' button stas greyed out and you cnnnot recruit/move units.

**Comment by gfgtdf** [comment]
Ok i investigated this issue, and it seem like when you chat the chatmessage is put on the replay so that then at https://github.com/wesnoth/wesnoth/blob/1.13.8/src/play_controller.cpp#L412 the condition replay_->at_end() is false so that the side is never initiated.

**Comment by gfgtdf** [comment]
ok while 75cc7e62f6 somwhow fixes the client getting stuck it now gives an assertion error (replay.cpp assert(at_end())). So this is not fully solved yet. Fixing #1856 would probably fix this one aswell and might actually not be much harder so i'm considering fixing that one first.

**Comment by gfgtdf** [comment]
since this still quite the corner case, i'll set this for 1.14 (meanign it doesn't block 1.13.9)

**Comment by gfgtdf** [comment]
This is probably fixed by d08f402ef1677a8389c9cdd0040d1c18a085d9f1, still have to test it

**Comment by gfgtdf** [comment]
ok tested that this is fixed

**Comment by CelticMinstrel** [comment]
Is #1856 fixed too, then?

**Comment by gfgtdf** [comment]
it isn't
