### ISSUE TITLE
New scroll hotkey may cause endless scrolling

### ISSUE THREAD

**Issue by DisherProject** [wesnoth/wesnoth#1864]
I'm running Wesnoth 1.13.8+dev on Windows 7 Home Premium.

To reproduce:
1. Start any scenario
2. Go to Preferences->Hotkeys panel
3. Choose any "Scroll" Action
4. Add any hotkey different from the default one
5. Press it

The map should start scrolling endlessly in the chosen direction. In this case, clearing the hotkey won't have the map stopped.

**Comment by CelticMinstrel** [comment]
Textual hotkeys cause this, but other keys (such as end) work fine, so it must be something about these keys not correctly handling the key-up event.

**Comment by GregoryLundberg** [comment]
Well, we just made a change in that area.

**Comment by CelticMinstrel** [comment]
What change are you referring to?

**Comment by GregoryLundberg** [comment]
that thing about unsigned vs signed char from a week or two ago

**Comment by CelticMinstrel** [comment]
Oh, that. I don't think it's likely to be caused by that, though...

**Comment by gfgtdf** [comment]
the code (last time i checked) handled 'normal' keys only via meaning ignores keyup/down events, those are onyl used for eigehr non-text keys for for keys that are used in combination with odifers.

**Comment by CelticMinstrel** [comment]
The problem here can be summed up by saying that text-like hotkeys never send keyup events (only keydown); while not exactly accurate, it does give a good idea of the problem. Basically, I think I need to find a way to _simulate_ the keyup event. The only other option I can think of is reverting Aginor's key handling which distinguishes between regular and "text-like" hotkeys... and reverting something should be a last resort in my opinion.

**Comment by aginor** [comment]
You can also make the scroll-events special and still rely on key up/down. The logic for that would be easy to add into hotkey_item.cpp.

An argument in favour of doing that is that scrolling, unlike other hotkeys, expects to treat the keyboard like a large gamepad, where the duration of a keypress has significance. Other hotkeys don't care about it (although you might also get key-repeat).

**Comment by aginor** [comment]
Another workaround is obviously to stop allowing people to rebind the scroll hotkeys :)

**Comment by CelticMinstrel** [comment]
So my idea for fixing this is to make the scroll events never bind to a TEXTINPUT. Basically, when binding a scroll event, it'll ignore TEXTINPUT and instead register the key event. I don't know whether I'll have time to do this in the next week though (which basically gives me tomorrow only, unless I can find time in the evening).
