### ISSUE TITLE
player information wrong in mp_join_game

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1867]
the right side player information in the gui2 mp_join_game dialog makes just one entry for each side found in the scenario.

This is obvious wrong because:
1) players that are assigned to multiple sides appear multiple times
2) players&observers that don't have a side assigned to them (yet) are missing in that list
3) It also list ai sides to that the host (which controls ai sides) appears multiuple times for scenarios with ai sides.
4) it generates empty lines in the playerlist for empty sides.

**Comment by Vultraz** [comment]
Is this problem also in mp_staging or just mp_join_game?

**Comment by Vultraz** [comment]
Also I'm not sure how there are duplicates considering a set is used.

**Comment by gfgtdf** [comment]
> Is this problem also in mp_staging or just mp_join_game?

I only tested mp_join_game and i have currently no reason to believe it applies to mp_staging  aswell.

> Also I'm not sure how there are duplicates considering a set is used.

There is no set used in that code

**Comment by Vultraz** [comment]
Yeah, the set is in mp_staging. Mo_join_game just uses the [side] tags. Any idea where I can get the player info?

**Comment by gfgtdf** [comment]
> Yeah, the set is in mp_staging. Mo_join_game just uses the [side] tags. Any idea where I can get the player info?

I am not even sure whther mp_join_game tracks this data, i mena the server does send things like observerjoins, ( https://github.com/wesnoth/wesnoth/blob/1.13.8/src/server/game.cpp#L1194 ) or plyerlist https://github.com/wesnoth/wesnoth/blob/1.13.8/src/server/game.cpp#L1320 but i cannot see the mp join game code readng any of this data ( https://github.com/wesnoth/wesnoth/blob/1.13.8/src/gui/dialogs/multiplayer/mp_join_game.cpp#L441 ). (I coudl be missing something though). So probably currently just ignores those
