### ISSUE TITLE
bad file names in cache directory

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1871]
the names of the cache directory are currently generated by the utils::sha1 function which also uses characters like `.` or `/` in the encode_hash function, this may easily result in filenames like "asf/../../sfsfg" or worse beeing generated.

**Comment by gfgtdf** [comment]
assuigning to celmin since it likeley casued by https://github.com/wesnoth/wesnoth/commit/c9191c98122d97310eddae041a9fd3496cd5b894whihc made sha use a Base64 encoding.

**Comment by pydsigner** [comment]
You're right, it's https://github.com/wesnoth/wesnoth/commit/c9191c98122d97310eddae041a9fd3496cd5b894#diff-46ec93803811240fe7b2b9e83eac7ba2L23 that's to blame. We can fix this by removing the `./` from the beginning, or by using an actual hexdigest conversion.

**Comment by CelticMinstrel** [comment]
Does removing the `./` from the beginning break forum logins on the MP server, though?

**Comment by gfgtdf** [comment]
> Does removing the `./` from the beginning break forum logins on the MP server, though?

Qiute possible, so i'd reccomend just to use the old hexadecimal encoding. alterntiveley we can just run a strgn replace at config_cache.cpp to use other chracters there.

**Comment by CelticMinstrel** [comment]
The latter sounds simplest. Only `/` would need replacing really, so you could just use something like `boost::replace_all(hash, "/", "-")`.

**Comment by gfgtdf** [comment]
I'd still reccomend replacing `.` aswell, even though only `..` and `.` really have special meanings in filesystems its likeley that it random `.` asppearing in filenames confuse some programs.

**Comment by gfgtdf** [comment]
Oh another thing i noticed: this algorithm uses uppercase and lowercase letters, but windows filesystems are case independent so the names might clash. Going back to a hexadecimal encoding seems ot be the only option after all.
