### ISSUE TITLE
Edit ui looks cut off

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1884]
![grafik](https://user-images.githubusercontent.com/4893136/29026813-fd42b4ce-7b7d-11e7-8a0e-3a8370a15347.png)
 In the screnshow above you can for example see:
1) the golden border around the map is only present at the up and left side. (this is unrelated to the scorlling posistion of the map)
2) the right-side panel looks cut-off at the downer side.

The editor also has issues with rezsing,  which results in black bars in the tooblar area at the right.

**Comment by Wedge009** [comment]
As indicated in the commit gold border is removed now. Is the concern about the side-bar only because the box around the terrain icons looks open-ended (deliberately so, I imagine)?

**Comment by jostephd** [comment]
Yes, it's deliberate:

https://github.com/wesnoth/wesnoth/blob/1f4e1854813039f71886d2dd864c5bd966dc6884/data/themes/editor.cfg#L766-L781

**Comment by Wedge009** [comment]
1. As mentioned previously, has been resolved by the commit.
2. Seems to be covered in #2618. I notice it's dependent on one's window size - maximised the editor icons happened to fit nicely such that the last row sits very close to the bottom. Only at certain window dimensions it can potentially leave a large gap in the interests of not rendering an incomplete row where the full height of the icons can't be seen.

**Comment by AI0867** [comment]
> 2. Seems to be covered in [Editor palette background renders incorrectly #2618](https://github.com/wesnoth/wesnoth/issues/2618). I notice it's dependent on one's window size - maximised the editor icons happened to fit nicely such that the last row sits very close to the bottom. Only at certain window dimensions it can potentially leave a large gap in the interests of not rendering an incomplete row where the full height of the icons can't be seen.

I think rendering an incomplete row would actually be better UX: it visually shows that more rows are available, while empty space would imply there's no more.

While I've certainly used software where the next row 'pops in' the moment enough room is available, I believe that's mainly for technical reasons.
