### ISSUE TITLE
cmake uninstall takes very long

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1890]
I only compiled the server daemon.
Cmake uninstall takes way longer than installing, I think longer than compiling.
That's not a problem, but maybe it can be enhanced?

**Comment by Vultraz** [comment]
@GregoryLundberg

**Comment by GregoryLundberg** [comment]
Huh? Never did CMake install much less uninstall. But I should have some time later today so I'll see what I can see.

**Comment by Vultraz** [comment]
@GregoryLundberg I figured you would know what to do with it.

**Comment by GregoryLundberg** [comment]
Well, I don't. My CMake run compiles Debug using clang for campaignd wesnothd wesnoth and test. I sync'd to current master (atm) and get a clean build on all targets.

I ran 'sudo make install' and watched the filenames scroll past at Mach speed. I then ran 'sudo make uninstall' and watched them scroll by just as fast. Took about a minute to install and about the same to uninstall.

**Comment by Vultraz** [comment]
Well, then perhaps... @CelticMinstrel knows?

**Comment by GregoryLundberg** [comment]
Well, he said he compiles just the server. Perhaps it's that 'make install' and/or 'make uninstall' is expecting both wesnoth and wesnothd and all the translations and he skipped some and that's causing the slowdown.

**Comment by sevu** [comment]
Compiled today everything, it's unrelated.

**Comment by CelticMinstrel** [comment]
I'm not sure why I'd know... I'd expect "uninstall" to be deleting the entire data directory from somewhere, though, would you expect that to be slow? Then again, maybe I don't really understand what (un)install are supposed to do.

**Comment by GregoryLundberg** [comment]
Install copies the executables, creates the data directories and copies the files.

Uninstall reverses each step.

On my Arch Linux it takes a bit oversaw minutes each and the names scroll too quickly to read.

**Comment by CelticMinstrel** [comment]
Okay, so that's exactly what I though it would do. I dunno if it makes sense for it to take a long time to delete a large directory tree, though.

**Comment by GregoryLundberg** [comment]
It knows what it did and reverses it. (cp -> rm) (mkdir -> rmdir) .. doing it file-by-file avoids accidentally deleting a user-created file or, worse yet, the implications of (rm -fR) going awry.

I'm wondering if the issue might be a file-system problem. I could see rm taking a long time if it's from a protected area and each rm hits a privilege-escalation break.

So ..

OP .. what is the OS? If it's a Linux system, what is the file-system? Are you running any unexpected hardware? A SSD? A Raid array? Networked storage?

Can anyone duplicate the issue of 'make uninstall' taking noticeably longer than 'make install'?

**Comment by sevu** [comment]
I'm running arch linux as well (have it up to date), nothing special about the hardware, a T450s with a SSD, i think it's an samsung 850 evo with 500gb, also running the default kernel.
The root file system is ext4 with the options rw,relatime,discard,errors=remount-ro,data=ordered, and home, where the git repo lies, has additionally nosuid,nodev.
Both file systems are often very full.

I get the following results with time make install:
real	0m13,712s
user	0m5,409s
sys	0m6,173s

and time make uninstall:
real	2m47,472s
user	1m43,409s
sys	1m5,699s

I wonder what it could be that it is different in your case.

**Comment by sevu** [comment]
So, just for the record - was anyone else seeing a difference here?

**Comment by sevu** [comment]
Closing this, before this remains here for ages.
