### ISSUE TITLE
Bug with possibly movements backlight

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#1891]
Windows 7 Pro x32
Wesnoth 1.12.6

When moving mouse cursor over any unit there is no possibly reach distance backlight, but all hexes are backlighted! Like unit could move to any hex at map (unit really could not, it is only broken backlight).
Very dissapointing thing - could not play properly at all.

Game started as usuall, but at some turn bug occured.

Also I remeber that sometime ago on another computer and Wesnoth version this bug occured to me.

On this screenshot mouse cursor is over drake corpse:
![screen](https://user-images.githubusercontent.com/10855248/29106325-1e8b9172-7cdd-11e7-9504-e48dfc36d1b4.png)

Save game:
[2p_—_Sablestone_Delta_BUGGY.gz](https://github.com/wesnoth/wesnoth/files/1210423/2p_._Sablestone_Delta_BUGGY.gz)

**Comment by ln-zookeeper** [comment]
Holding down number keys changes how many turn's worth of movement the highlighting shows, and that can get stuck if Wesnoth loses focus when you have one of those keys pressed down. That's probably what's happened, in which case simply using the number keys ought to reset it.

**Comment by amokmen** [comment]
Never used number keys. And for change focus pressed Alt+Tab.
