### ISSUE TITLE
Timer sometimes occasionally is decreasing in multiplayer

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#1892]
Windows 7 Pro x64
Wesnoth 1.12.6

Sometimes (I can't notice exactly when and at what circumstances) timer is going to descrease time to play turn. Different Wesnoth versions. And it does not matter: I am host or just joining player.

Usually, game starts normally. After a few turns timer became shorter. For example, last time I hosted game with these settings: 300/300/300/0 seconds. So, 5 minutes for each turn. But screenshot below shows, that at turn 10, my timer became 1 minute and 9 seconds from start! I don't remember exactly, but probably later timer became again 5 minutes after a few turns more.

This bug not rare for me. What is this? Wrong netcode? Accumulated error? Problems with FPS?

![5 minutes](https://user-images.githubusercontent.com/10855248/29169159-3e16cb0c-7ddb-11e7-91e1-794222de3fc5.jpg)

**Comment by amokmen** [comment]
replay is [here](https://replays.wesnoth.org/1.14/20181114/2p__Caves_of_the_Basilisk_Turn_25_(26301).bz2)

**Comment by soliton-** [comment]
In that game the timer was 240/60/300/0.

**Comment by amokmen** [comment]
Yeap, but one turn there was 60+26=86 seconds **from start**, other turn different time. You could see chat, where I asking about it. Also both players sometimes could not properly do their all moves with all units...

**Comment by jostephd** [comment]
Your screenshot shows that red's turn 10 started with a short clock. How much time remained on the clock at the end of red's turn 9 and at the end of blue's turn 9?

**Comment by amokmen** [comment]
@jostephd Are you going to tell me that it was 'by design' behaviour?

I don't remember how much time was at my (red's) turn 9, of course. And I definitely don't know timer numbers for blue.

P. S. By the way, could someone give me a link where exactly describes all these '300/300/300/0'? I've searched once w/o any result.

**Comment by jostephd** [comment]
No, I'm not going to say that. I was just trying to rule out a possible cause of the bug. If you'd said that blue turn 9 ended with 85 seconds remaining and then red turn 10 started with 84 seconds, that'd have been unlikely to be a coincidence, you see.

The MP Create Game describes these settings in a sentence each, I don't know where they're described more fully.

**Comment by amokmen** [comment]
It's almost impossibly to get that information from another player. Of course I could try :)

**Comment by soliton-** [comment]
"timer is mad" is really not a clear description at all unfortunately. That a turn starts with 60+26 seconds when the turn bonus is 60 seems perfectly normal. As well as that different turns start with different remaining times if the turn bonus is less than the reservoir time.

It's awesome that you report issues and I'm not saying there is no issue here but we need to figure out what exactly the problem is before anyone has a chance to fix it.

There is unfortunately no more detailed description of the timer on the wiki (but it'd certainly be nice to have one). You can probably find a post or two on the forum by Sapient about the timer design.

What the game displays and how fast is not going to affect the timer but of course it might make it harder for you to make quick moves.

**Comment by amokmen** [comment]
0. I could not record video of all my games, but it would be wonderful (half-wonderful without recording from other side) bug report! :)
1. I've just load last replay and pressed "play side turn" every time watching timer number. It's interesting, you should also try.
2. If you missed my first report, where I was host and there 100% was 300/300/300/0 settings. I am very accurate person, I always double check numbers. So, how you would explain this situation?

**Comment by soliton-** [comment]
1. Replays contain no timing information.
2. I didn't miss your initial report but there's not much to go by here. If you happen to still have the replay it'd be possible to double check the timer values at least.

I'd like to repeat that I'm not saying there is no issue here but unfortunately there is little to go by so far.

**Comment by amokmen** [comment]
2. Unfortunately there is no replay locally. I tried to find it in replays.wesnoth.org with no result also.

**Comment by amokmen** [comment]
let's close it.
