### ISSUE TITLE
Problem of [set_menu_item]

### ISSUE THREAD

**Issue by Kinako-Ohagi** [wesnoth/wesnoth#1895]
If "use_hotkey" of [set_menu_item] is set to "no", "description" is not displayed.

**Comment by gfgtdf** [comment]
This looks like it was likeley broken by 7d2d100cf88f7bd675ad02ca5180ec1ccce5e0c3 . The problem here is that wml_menu_item::menu_text() eigher retursn the hotkey id or the descrption the code that handled the 'returns description' cae was somehow lost.

**Comment by Vultraz** [comment]
What do you mean? The code is still there:

```	std::string menu_text() const
	{
		// The space is to prevent accidental hotkey binding.
		return use_hotkey_ ? hotkey_id_ : description_.str() + ' ';
	}
```

**Comment by gfgtdf** [comment]
hmm ye mabe i was a little unclear, i meant the code thean processed the return value later seems to now assume that it's a hotkey id and doesn't fallback to using the string itself as the display string.
