### ISSUE TITLE
Remove add-on downloader because of licensing issues

### ISSUE THREAD

**Issue by stas730** [wesnoth/wesnoth#1897]
It looks like it's now allowed to use any CC license for add-ons.
Some CC licenses are non-free (NC and ND).
Game should be fully free, so there must be no non-free add-on downloader (hiding non-free add-ons with a checkbox is not good).

**Comment by Vultraz** [comment]
Fuck off.

**Comment by stas730** [comment]
Will be removed from GNU FSDG distros. Bye.

**Comment by JohnMHarrisJr** [comment]
I can't believe this kind of non-issue is something that's actually coming up.

**Comment by sapientN3T** [comment]
@stas730  There was a really long discussion about this in the forums from October of last year. Here is a link to the relevant post:

https://forums.wesnoth.org/viewtopic.php?f=6&t=44771

After that discussion, the "Statement on UMC content licensing changes" was posted on May of this year:

https://forums.wesnoth.org/viewtopic.php?f=6&t=46093

In short, I am sorry if it causes any inconvenience for GNU FSDG distros, but it's already been decided and you missed your chance by a longshot to try to alter that decision.

**Comment by GregoryLundberg** [comment]
I trust the bistros will also remove all web browsers since they too can download non free objects.

No? Well I always assumed the gnu purists were hypocritical

**Comment by realsobek** [comment]
For what it is worth:
https://www.mail-archive.com/gnu-linux-libre@nongnu.org/msg02359.html
https://www.mail-archive.com/gnu-linux-libre@nongnu.org/msg02390.html

**Comment by GregoryLundberg** [comment]
Quoting from that mailing list archive (message 02390):

> > It looks like we have lost this fight...
>
> No, we lost support for our community from another because a troll was
> allowed to speak for it unchallenged and attack developers that are on
> our side over a non-issue. This demonstrates an abject failure on our
> part to project a good image of who we are and, most importantly, prove
> that we are not a raving collection of lunatics. This is not the first
> time, and it will not be the last.
> 
> If any Wesnoth fans are on this list, please, respond to that forum
> post. Denounce stasXXX's behavior, and explain that what he said about
> GNU FSDG was pure bullshit and not even remotely in line with GNU FSDG,
> neither the letter nor the spirit. They need to be reassured that some
> of their fans are in fact libre software community members, who do not
> approve of stas's actions, and that stas does not speak for all of us.
> 

So, as we expected, this entire Issue was prompted by a troll. I'm locking further comments, we've wasted enough bandwidth on this non-issue.
