### ISSUE TITLE
lua error when starting the tutorial

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1898]
When starting the Tutorial it may be that you get this message:

20170813 16:40:13 error scripting/lua: lua/wml-tags.lua:291: Error: Attempted to access an invalid music track.

stack traceback:
	[C]: in metamethod '__newindex'
	lua/wml-tags.lua:291: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>

**Comment by CelticMinstrel** [comment]
This may not be specifically related to the tutorial... it's likely a duplicate of #1861.

**Comment by sevu** [comment]
I think you fixed this - at least I didn't see this message anymore
