### ISSUE TITLE
Can no longer to type "Space" to mark a unit wouldn't move

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#1903]
Steps to reproduce:

0. Start "A Tale of Two Brothers"
1. Click on a unit that has a green orb
2. Press "Space" (End Unit Turn)
3. In 1.12.6, that unit's orb turns to black and then pressing "N" repeatedly does not visit that unit.

    In 1.13.8, pressing "Space" does nothing, and subsequently pressing "N" does visit the unit.  I tried the "Shift+Space" (Hold Position) key combination too, but it had no effect.

This feels like a UI regression: I don't see how to mark a unit as needing no further attention this turn.  Was this change intentional?

(I use the debian packages. I didn't find any previous bug reports.)

Thanks,

**Comment by Pentarctagon** [comment]
Possible duplicate of #1893 ?

**Comment by jostephd** [comment]
The "N" key still works here, which seems to rule that out.

**Comment by Wedge009** [comment]
I think this is a closed issue for master - I vaguely recall this in an earlier report and I confirm that as of 44207559 End Unit Turn (space by default) is working properly in Windows and Linux.

Are you able to try compiling the latest code yourself and see if you still get the issue? Otherwise you can wait till the next release.

**Comment by jostephd** [comment]
Thanks for the quick answer.  I'll try latest master over the weekend.

**Comment by jostephd** [comment]
With b2e9cd3:

- "c" at the title screen: works
- "space" in-game: works
- "n" in-game: nothing happens
- "u" in-game: nothing happens

With 1.13.8 debian package:

- "c" at the title screen: nothing happens
- "space" in-game: nothing happens
- "n" in-game: works

So the issue with space is indeed fixed.  The remaining issue with "n" is probably #1893.  Let's close this issue then.
