### ISSUE TITLE
Right-click-to-dismiss causes Context Menu popup

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#1908]
Sorry I don't know when this first showed up (it's been a couple weeks or more), but as of 11edc7afe5, there is a problem with mouse clicks (I use "left-click/right-click", I know that's imprecise, but I don't know the internals and this is what I observe on a standard mouse.)
1.  Select a unit to move with left-click (screen is fuzzed-out, except for the reachable hexes, and that unit's defense is displayed, cursor is a pair of pointy metal boots).
2.  Decide that isn't the unit you need to move, dismiss with right-click (left-click would execute the move you don't want).  Move is dismissed, but <b>context menu is opened.</b>

**Comment by Wedge009** [comment]
I understand what you mean. You want to cancel the move so you use right-click to dismiss the move options but it seems that step is being missed and it goes straight to the standard right-click action which is to bring up the context menu.

**Comment by Vultraz** [comment]
I haven't tested, but this might have been a side effect of c5dc04c90001b...

**Comment by Wedge009** [comment]
@Vultraz I confirm reverting c5dc04c9 resolves the change in right-click behaviour. Looks like it's an unintended side-effect of the refactoring, but I'm not sure what it is that's doing it.

**Comment by Vultraz** [comment]
Well, then, the cause is very simple. The right down click dismisses the reach map, and then the right *up* click triggers the context menu.

**Comment by Wedge009** [comment]
Huh, should have read the comment on your commit message. The right-click-to-dismiss-movement is something specific to Wesnoth, I imagine. If your goal is to make things more consistent with general application behaviour (I'll grant that generally you expect actions to occur on mouse-click-release - even recall some bug/wish reports on this), could we insert a check on whether there is something special displayed on the game map (like the movement highlighting) before going to the right-click menu?

**Comment by Vultraz** [comment]
There is such a check, but some stuff needs to be reworked to accommodate the new behavior, I think.

**Comment by CelticMinstrel** [comment]
Why not just make the reach map be dismissed on mouse up instead of mouse down? Wouldn't that solve the problem?

**Comment by Vultraz** [comment]
Maybe, but the code is messy and it's not clear where that happens.

**Comment by gfgtdf** [comment]
> Maybe, but the code is messy and it's not clear where that happens.

If it works as it should, this happens via hotkey (since 1.12 you can change the selecct_hex hotkey form right mouse buttom to somethign else)

**Comment by Wedge009** [comment]
Looking through the hot-key calls brought me to [mouse_handler::select_hex()](https://github.com/wesnoth/wesnoth/blob/master/src/mouse_events.cpp#L679). Looks like @gfgtdf already tried to tidy some things here last week.

**Comment by gfgtdf** [comment]
> Looks like @gfgtdf already tried to tidy some things here last week.

I only fixed some bugs in the lua mouseliick callback reported by elidupee last week on irc.
