### ISSUE TITLE
loss of command modes

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#1909]
I believe this happened within the last ten days or so, though not completely sure, but as of 11edc7afe5, the command line doesn't seem to work anymore.  I know the magic key changes, but ";" and ":" don't seem to do anything (english-US QWERTY keyboard).  

Following the Help->Commands->Debug Commands text, I get nowhere.  I couldn't open the chat-line either, but I never use that, so I have no idea if that is new or related.
EDIT:  Actually, this may be part of https://github.com/wesnoth/wesnoth/issues/1893

**Comment by Wedge009** [comment]
I think it might be the same as #1893, if you're using Linux. It's not an issue on Windows.

**Comment by doofus-01** [comment]
Yeah, I'm using Linux.
