### ISSUE TITLE
Multiplayer lobby: big leader sprites get cropped before and uncropped after minimazing and maximizing the BfW window

### ISSUE THREAD

**Issue by Kwandulin** [wesnoth/wesnoth#1932]
In the multiplayer lobby, when picking a leader that has a big unit sprite, the unit sprite is cropped (starting at 0,0). After minimizing BfW and maximizing (full screen) it again, the leader's sprite is not cropped anymore. I attached an image that shows the lobby before (top image) and after minimizing and maximizing the window.

I think the lobby should directly show the uncropped version.

Happens on Windows 10, BfW 1.13.8.

![minimize](https://user-images.githubusercontent.com/19636085/29997432-4a0b5564-9013-11e7-95d3-ef1eada63a80.jpg)

**Comment by Vultraz** [comment]
*screams into pillow*

**Comment by Vultraz** [comment]
Please see if that fixes it ^

**Comment by Kwandulin** [comment]
The proposed fix doesn't change the behavior

**Comment by Vultraz** [comment]
God DAMMIT.

**Comment by Vultraz** [comment]
I just checked again, the behavior seems correct after my commit. The sprite is no longer initially cropped.
