### ISSUE TITLE
messages, which have their portrait on the right, are not centered

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1938]
![shaman](https://user-images.githubusercontent.com/21158813/30005813-10cc9ba4-90eb-11e7-8f12-8468c997444a.png)
While most other messages have their message centered.

**Comment by CelticMinstrel** [comment]
I'm not sure this should be considered a bug...

**Comment by sevu** [comment]
It just doesn't look good if all other messages are centered, and the shamans one in between not.

**Comment by CelticMinstrel** [comment]
I'm not even sure what you mean by centred. Aren't all messages left-aligned?

**Comment by doofus-01** [comment]
I see what sevu is saying, although CelticMinstrel may be correct, strictly speaking.
  
1.  Most portraits have some dead-space/padding; you don't see the left-justified text  huddled up next to the portrait subject's face.  But there is (apparently) no such intrinsic padding for the left edge of the screen.  
2.  The word-wrap or newline also does not extend to the right side of the visual bounding box, for some common resolutions at least.  When the portrait is on the right, the newline coordinate is shifted to the left, so this extra right-hand padding is added to whatever intrinsic padding of the portrait (and that the left screen edge does not have).  

Net effect is that the portrait-left/portrait-right dialogues aren't at all symmetric, beyond what can be attributed to the left-justified text.

**Comment by Vultraz** [comment]
I honestly think this provides nice visual variation for portraits on the right.

**Comment by sevu** [comment]
I see why you think so. On the resolution of the example above (1440x752), the messages with the image on the left look like being the opposite of the one shown above.

But if you have the window on 1920x1080 it is different, because then the text from the messages with the image on the left looks clearly centred, while messages where the image is on the right have the text still on the very left.
(the text itself is left-aligned , as pointed out earlier)
![archer](https://user-images.githubusercontent.com/21158813/30027446-51c0fbaa-9181-11e7-826e-61702cfaaf6e.png)

![shaman2](https://user-images.githubusercontent.com/21158813/30027725-6c763cc0-9182-11e7-8134-b5ae401d5660.png)

**Comment by CelticMinstrel** [comment]
We can certainly add some padding on the left for right-portrait messages.

**Comment by jostephd** [comment]
#3529
