### ISSUE TITLE
1.12 terrain code parser quits to main menu if terrain code is longer than 4 characters

### ISSUE THREAD

**Issue by Shrieker1** [wesnoth/wesnoth#1949]
wesnoth 1.12.6

I had a minor mistake in thinking how many times my variables would get evaluated so I escaped them when I shouldn't. That resulted to filter with terrain attribute pointing to a long string instead of valid terrain code in the variable. It would be nice if this error would just result to WML error message without cancelling the scenario.

If the error would keep me in scenario I could just fix the lua code and reload it.

wesnoth log
~~~~
20170906 21:02:49 error general: An error due to possibly invalid WML occurred
The error message is :
A terrain with a string with more than 4 characters has been found, the affected terrain is :$NS_system.$player[$side_number].race|.village_type_terrain
 
When reporting the bug please include the following error message :
Condition 'str.size() <= 4' failed at /build/wesnoth-1.12-BSOVkQ/wesnoth-1.12-1.12.6/src/terrain_translation.cpp:713 in function 'string_to_layer_'.
~~~~

**Comment by Wedge009** [comment]
Closing in favour of #8777.
