### ISSUE TITLE
1.13.8 (Ubuntu 16.10): 50% zoom strange behavior 

### ISSUE THREAD

**Issue by GuidoBartoli** [wesnoth/wesnoth#1951]
Hi,
As already reported for the iOS version here --> [https://github.com/singalen/wesnoth/issues/47](url), when toggling the 50% zoom, the view jump across the map instead of remaining centered on the current point. Teoretically, going 100% --> 50% --> 100% should remain on the same point, except when the view is near the map edges.

**Comment by Vultraz** [comment]
I think this might have been fixed with #1845 ? Or did your testing build already have that commit.

**Comment by GuidoBartoli** [comment]
I did not compile it from sources, I installed the 1.13.8 development version on Ubuntu 16.10 using these packages: [http://apt.ubuntu.com/p/wesnoth](url)

**Comment by Vultraz** [comment]
Ok, the commit in question (29519406beed) is only on master. Could you test again once 1.13.9 is released later this month?

**Comment by Wedge009** [comment]
I remember this behaviour in the past, but it seems okay to me. I'm sure 1.13.9 will be fine but happy to wait for confirmation.

**Comment by Wedge009** [comment]
Closing since there's no further feedback and a quick check on 1.14.0 shows this doesn't happen (as best as I can tell).

**Comment by jostephd** [comment]
I think it happens only if zooming out runs into two opposing map edges (east and west, or north and south).

**Comment by jostephd** [comment]
PR #4442
