### ISSUE TITLE
engine bug with (nested) turn end event

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1952]
Take https://github.com/wesnoth/wesnoth/commit/3ca1150cbc1662153a95cbfff33680ac8c992e3e as an example:

It is a nested event inside a capture event, and fires after the player ended his turn. It has `side 1 turn end` as condition. The player is side 1. (and it's working)
If you instead use `turn end` or `turn 1 end` as condition the text is still displayed during the enemies turn, and cleared when it's your next turn. So, it seems it's fired at the end of the enemies turn.

:inspect shows the `turn end` event at the bottom of the event list after the capture event. (same for `side 1 turn end`)

**Comment by gfgtdf** [comment]
> If you instead use turn end or turn 1 end as condition the text is still displayed during the enemies turn, and cleared when it's your next turn. So, it seems it's fired at the end of the enemies turn.

This is the expected behaviour of turn end events.

**Comment by sevu** [comment]
Indeed, I thought it would fire after the end of each players turn.

**Comment by gfgtdf** [comment]
> Indeed, I thought it would fire after the end of each players turn.

We have the `side turn end` event for that.

**Comment by sevu** [comment]
I think many campaigns just work because` turn x` and `side 1 turn x` isn't much different. Didn't notice that until now.
