### ISSUE TITLE
The South Guard

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1954]
Necrosporus mentioned in the IRC that it may be possible to play on _easiest difficulty_ without recruiting. Sounded interesting, I try it, seems possible so far.
Here some feedback about things I though which could be improved.

I like this campaign, I hope I don't create another impression because I only list things which could be improved.

----- Scenario 3 ------
- [x] When killing the bandit leader in the end of scenario 3, he says sth. like : _Not even with the power of the undead ..._  Which makes me wonder, would he have recruited undeads too if I would have killed him later? There was nothing with undead in this scenario, thought he knew about the earlier ones.
Edit: The cause is, on easy they don't recruit undead. we need a different message.

- [x] In the end of scenario 3, the elvish shyde says sth. about the undead, although nobody has mentioned them. She may know sth. about them, but it sounds strange how she brings that up, because Deoran didn't say he has a problem with the undead.

As a side note, this one is too easy or rather boring. Could be the same without bandits. But I don't have suggestions. Or, maybe even on easy, more gold or rather a short gold boost after a 1 round recruiting break for the Bandits? Or, some tomato surprise like an ruffian/footpad hiding in a captured village? maybe in a random, non-elvish village.
-----Scenario 4 -------
- [x] In the beginning of scenario 4, Deoran calls the old wise by name. Nobody told him how he's called yet, it's unlikely that he got told it at the travel between scenario 3 and 4, because in the dialog the shyde just explained him who that man is. He can't know that. He also called the shyde by name - this he probably knows - thought as player it was a bit strange to hear that name out of the nothing the first time. Though I could have seen it in the sidebar during her dialogs before. [Edit, and in the dialogs itself, so it is probably fine for Ethiliel]

-----Scenario 5 -------
- [x] It is told that never a elve crossed the black river or told from the other side. That's said in the prologue ans the beginning of scenario 5. However, when in the beginning the the Elvish Fighter and Shaman are explained (I guess as help for newbies) it's that Elvish fighters live in this forest. This text needs adjustment.
- [x] Scenario 5 uses fog. In the beginning you see only the leader's vision are, then the units are recalled. After all the dialog the vision are is widened because of the recalls. I suggest adding a [redraw] after each recall.
- [x] Looking at the map I find 3 keeps, so there are three leaders. The scenario overview shows that only thwo of them are in the same view. Also, it shows their starting money and basic income. Usually scenarios with fog don't display these stats, but I think that's fine here. [OK, I'm now at the first events, it's definitely fine. I would not hide that information, it's good that it is there.]
- [x] During or after said event, there is the _enemy sighted_ text shown. Maybe a {CLEAR_PRINT} (the macro from the tutorial) can remove this. Same when finding the end boss.
- [ ] I suppose there may be room for some bugs (didn't check the code) - what happens if the player triggers that event a few rounds later? will the leader already be dead?
- [ ] I would give even on the easiest difficulty more gold to the end boss - he just sends out ever now and then a unit. Or spawn a few additional units at the event in his base. Or give him a gold bonus in the event turn. Doesn't need to be much.

-----Scenario 6 ------- 
- [x] wonderful, that something like that even exists in mainline. I suggest lowering the gold to have it more RPG like. 100 is much, that's what you have for an MP game. I played without recruits/realls (wasn't easy, but that made it interesting), I guess 2 Fighters and a Shaman would be enough. ->43 Gold. It's on very easy. 75 Gold would be enough for 5 recruits, that should be fine for very easy. Although, having seven units for that level... no, too much. 60 gold?

-----Scenario 7 ------- (underground)
- [x] When you make the deal with the trolls, there is this event which blows up the wall. I needs a [redraw] to remove the shroud.
- [x] if the {CLEAR_PRINT} trick works, it could be applied on the lich sighting too

-----Scenario 8 ------- (the way home)
- [x] replacing Chw at 10,28 with Kme? (it's a standalone castle field)

-----Scenario 9 -------
- [x] The name of all the enemies units , "Deorans Schüler" (in German) is too long to be displayed in the side bar in 1.12. maybe dropping that? not tested in 1.13 yet.
[Edit: not a problem for me in 1.13]

**Please don't spoiler me about the alternative path.**
Feel free to edit my post to check the checkboxes (what's that the are for). If no change is needed, check them too.

**Comment by ln-zookeeper** [comment]
> In the end of scenario 3, the elvish shyde says sth. about the undead, although nobody has mentioned them. She may know sth. about them, but it sounds strange how she brings that up, because Deoran didn't say he has a problem with the undead.

Deoran does say so; _"Bandits and criminals in our land have summoned the dead to help them plunder our farms and villages"_.

> It is told that never a elve crossed the black river or told from the other side. That's said in the prologue ans the beginning of scenario 5. However, when in the beginning the the Elvish Fighter and Shaman are explained (I guess as help for newbies) it's that Elvish fighters live in this forest. This text needs adjustment.

The text says _"Elvish Fighters are at home in the thick forests"_ but the meaning is not that the forest you are in right now is their home:
> be/feel at home
> to feel as relaxed as one does in one's own home or in a place or situation one knows well.

The other issues seem legit.

**Comment by sevu** [comment]
> The text says "Elvish Fighters are at home in the thick forests" but the meaning is not that the forest you are in right now is their home
How about removing the article, I think it will be more clear.

**Comment by GregoryLundberg** [comment]
I agree "in the thick forests" --> "in thick forests" seems more clear

**Comment by sevu** [comment]
- [ ] On other difficulties, Ethiliel is not a shyde but a druid. But her portraits have wings. And there's no time to level her before.
- [ ] Scenario 8a: In the dialog in the beginning speak two units, but one of them is not visible. And this reveals on higher difficulties the keep, because there is played with shroud.

**Comment by Arcanister** [comment]
- [ ] Free Dragoon Jarek is not loyal. 
- [ ] Death dialog of him does mention Deoran unconditionally even though you have scenarios where he is not present on map
- [ ] If you don't uncover minister Hylas immediately, but kill bandit leader first, he won't summon any undead, but dialogue will assume, he did.
- [ ] In scenario 5 if you defeat Gruth the zombie leader, they will still talk about "Far darker master" even if you have already seen the lich. Not sure if it's a problem though.

**Comment by sevu** [comment]
Most things are changed. What could be an issue:
If the AI kills the bandits in S5, the story is messed up.
Currently that doesn't happen, as the Bandits barely manage to keep them off.

However, the Lich side should be strengthened in some way.
Doing it with more golds or at a fixed time will then screw things up.
Doing it after the player finds the bandits has an abuse potential / is bad design.

@Arcanister Btw, 1.14 has finally been released

**Comment by nemaara** [comment]
I think I've addressed the issues with S5 except for the enemy sighted text (the {CLEAR_PRINT} macro doesn't seem to do anything, no matter how I try to alter the text with the [print] tag, it doesn't do anything). See https://github.com/wesnoth/wesnoth/pull/3648.
