### ISSUE TITLE
CMake Deprecation warning

### ISSUE THREAD

**Issue by GregoryLundberg** [wesnoth/wesnoth#1956]
Noted with recent upgrade to CMake 3.9

> CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
> 
> The OLD behavior for policy CMP0005 will be removed from a future version of CMake.
> 
> The cmake-policies(7) manual explains that the OLD behaviors of all policies are deprecated and that a policy should be set to OLD only under specific short-term circumstances. Projects should be ported to the NEW behavior and not rely on setting a policy to OLD.

I am unsure how to handle this. The cmake_policy option was set many years ago for backward compatibility with even earlier versions of CMake. I presume the option was added as an hack to avoid having to make the changes to literals.

I am not quite sure what would need to be corrected to remove the need for the cmake_policy setting.

It also seems that, once corrected, the minimum CMake version should be updated; but I do not think we should force 3.9.2 (the current version). The CMake documents are unclear on what version introduced the changes necessitating the cmake_policy (it appears the policy-setting option was a later addition).

Luckily, this is the only use of cmake_policy.

Unluckily, CMake is warning us the time is approaching where we can no longer delay fixing the underlying issues in our CMake configuration.

**Comment by GregoryLundberg** [comment]
> $ cmake --help-policy CMP0005
> CMP0005
> -------
> 
> Preprocessor definition values are now escaped automatically.
> 
> This policy determines whether or not CMake should generate escaped
> preprocessor definition values added via add_definitions.  CMake
> versions 2.4 and below assumed that only trivial values would be given                                                                                                                                    
> for macros in add_definitions calls.  It did not attempt to escape                                                                                                                                        
> non-trivial values such as string literals in generated build rules.                                                                                                                                      
> CMake versions 2.6 and above support escaping of most values, but                                                                                                                                         
> cannot assume the user has not added escapes already in an attempt to                                                                                                                                     
> work around limitations in earlier versions.                                                                                                                                                              
>                                                                                                                                                                                                           
> The OLD behavior for this policy is to place definition values given                                                                                                                                      
> to add_definitions directly in the generated build rules without                                                                                                                                          
> attempting to escape anything.  The NEW behavior for this policy is to                                                                                                                                    
> generate correct escapes for all native build tools automatically.                                                                                                                                        
> See documentation of the COMPILE_DEFINITIONS target property for                                                                                                                                          
> limitations of the escaping implementation.
> 
> This policy was introduced in CMake version 2.6.0.  CMake version
> 3.9.2 warns when the policy is not set and uses OLD behavior.  Use
> the cmake_policy command to set it to OLD or NEW explicitly.
> 
> .. note::
>   The ``OLD`` behavior of a policy is
>   ``deprecated by definition``
>   and may be removed in a future version of CMake.

**Comment by Vultraz** [comment]
@aginor might you be willing to look at this?

**Comment by aginor** [comment]
@Vultraz no, I think it would be better if one of the active maintainers would look into it since this is unlikely to be the last issue related to Cmake.

**Comment by GregoryLundberg** [comment]
I was thinking of taking a look at it, myself. I'm assuming the policy was set to OLD when 2.6.0 came out to avoid having to make a bunch of changes, some of which probably required deep thought. I'll see what 3.6.2 does after removing the policy and, if needed, roll back to 2.6.0 and version-walk to take the problems as they appeared.

**Comment by singalen** [comment]
I've just googled it up. [CMP0005](https://cmake.org/cmake/help/v3.0/policy/CMP0005.html)
affects escaping - new behavior is to escape as described in [COMPILE_DEFINITIONS](https://cmake.org/cmake/help/v3.0/prop_tgt/COMPILE_DEFINITIONS.html).

There are some definitions that could be affected by this policy. Looks like this is the complete list:
* if(NOT MSVC) ... add_definitions(${SDL2_CFLAGS})
* if(NOT WIN32) ... add_definitions(-DWESNOTH_PATH=\\\"${DATADIR}\\\")
* add_definitions(-DLOCALEDIR=\\\"${LOCALEDIR}\\\")
* add_definitions(-DFIFODIR=\\\"${FIFO_DIR}\\\")
* if(PREFERENCES_DIR) ... add_definitions(-DPREFERENCES_DIR=\\\"${PREFERENCES_DIR}\\\")
* if(DEFAULT_PREFS_FILE) ... add_definitions(-DDEFAULT_PREFS_PATH=\\\"${DEFAULT_PREFS_FILE}\\\")


but nothing too 
Looks like we just need to drop the line and test CMake build, mostly on Windows.

**Comment by Vultraz** [comment]
Is any of this covered by #1725 ?

**Comment by singalen** [comment]
No, the paths escaping is not changed by 1725.

**Comment by Vultraz** [comment]
Have any of the CMake changes since then had any bearing on this?

**Comment by GregoryLundberg** [comment]
yes
