### ISSUE TITLE
Checks on whether a lexical_cast fits always return true (CID 1380192)

### ISSUE THREAD

**Issue by AI0867** [wesnoth/wesnoth#1966]
For both the generic unsigned caster and the generic signed integer caster, a comparison of the result is done with the numeric limits. However, the result is obtained using `std::stol` or `std::stoul`, and for both signed and unsigned `long` targets, this check will therefore always return true.

The only way to make this check valid is to use `std::stoll` or `std::stoull`, but this is intentionally not used except for signed and unsigned `long long` targets, for performance reasons.

**Comment by jyrkive** [comment]
I think it's best to just leave the Coverity warning there.

The check always returns true only if `To` is `long` (or `unsigned long` for the unsigned case). The check is valid **and** necessary in other cases, including `lexical_cast` to `int` which is by far the most common case. And when the check always returns true, an optimizing compiler will optimize it out.

"Fixing" this warning would only make the code harder to understand for the sake of reducing the Coverity warning count.
