### ISSUE TITLE
Editor: Empty undo stack in perform_partial_action()

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1967]
1) start the editor
2) perform a right click to place a terrain.
 -> you get said message and are toggled to the title screen.

This doesn't happen if you placed a terrain with left click before.

**Comment by Wedge009** [comment]
I can confirm this. I _think_ it wasn't there before. Feels like there might be some uninitialised variable until the first terrain is placed with a left-click.

**Comment by Vultraz** [comment]
Caused by c5dc04c9000.

**Comment by Wedge009** [comment]
Resolved, thanks. I was wondering if it might be related to #1908, but it doesn't seem to be.
