### ISSUE TITLE
Editor: Start Position Tool

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1970]
Talking about this tool, which was redesigned in 1.13.
When clicking the delete button, the test on the map remains until you click another button or field.
![position](https://user-images.githubusercontent.com/21158813/30242506-e461466c-9597-11e7-92c3-25544598df51.png)

**Comment by gfgtdf** [comment]
> the test on the map remains until 

i assume you meant 'text' ?

**Comment by sevu** [comment]
I did

**Comment by Vultraz** [comment]
There's been something wrong with map labels for a few weeks. The starting position tool and labels tool are both screwed up. Labels from the former get hidden when setting a letter, for example. All kinds of problems.

**Comment by sevu** [comment]
In this case it's probably just a redraw which is missing

**Comment by CelticMinstrel** [comment]
I seem to recall seeing some issues with this too awhile back, with respect to custom locations. When you load a map, the custom locations are shown on the map but do not appear in the list, meaning you can't delete or move them.

**Comment by gfgtdf** [comment]
There are some  fixes related to map  labels recently, could you please retest this?

**Comment by GregoryLundberg** [comment]
@gfgtdf I just did. Still does not remove text from map until you click another tool button as OP reported.
