### ISSUE TITLE
MP lobby : selecting a campaign with long description causes to the list to scroll up

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1979]
If you select a _SP_ campaign in the MP Lobby which has a long description, so long that the part of the UI which shows the description needs a scrollbar, then the part of the UI with the campaign list will be scrolled up.
Additionally, the slider of the campaign list stays where it was before.

feels similar to #1940, differences in 1940 are:
- there is no slider
- I don't see by what it is caused in 1940

Probably affects the MP campaign list too, I just don't have enough MP campaigns.
Doesn't happen with choosing a map. 

No hurries to fix it for 1.13.9, since there are just 2 MP campaigns on the 1.12 server, and SP Campaigns are only available in debug mode.
For reproducing, there's no case in mainline with English language, in German it happens with SotBE.. Screen size was 1440x752.

**Comment by gfgtdf** [comment]
I assume you mean mp create and not mp lobby? Also it's uncelar on which version you observed this, on 1.13.8 release or a specific commit?

**Comment by sevu** [comment]
Yes, that's what I mean.  The version I had at this time is 8a7aa49

**Comment by Vultraz** [comment]
Ah, well, do confirm this is fixed. I'm not 100% the fix above affects this.

**Comment by sevu** [comment]
This fixed it.
