### ISSUE TITLE
MP lobby: large sprites cause issues for the others

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1981]
I'm pretty sure I saw this on the forums or somewhere else before, but I can't find it, so:
![oversized](https://user-images.githubusercontent.com/21158813/30301816-4187baa8-975d-11e7-86d5-ae569d30eed4.png)
I think it happens if the sprite is > 72x72.
The fire dragon is not quadratic, but the issue exists as well if I cut him to 160x160

**Comment by CelticMinstrel** [comment]
Probably just need to disable scaling in the `[image]` element, or something similar.

**Comment by Kwandulin** [comment]
This is probably related to https://github.com/wesnoth/wesnoth/issues/1932
