### ISSUE TITLE
High DPI support for WML Tools GUI

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#1982]
The `GUI.py` app doesn't look good on High DPI screens. I did a quick google search, and it looks like it should be possible to add a scaling factor fairly easily (https://stackoverflow.com/a/34133102) but since I don't know any Python/tinkter I'm leaving this to someone who does.

EDIT: I have a vague memory of possibly asking E_H about this before... if I've done so and it was deemed undoable, apologies.

**Comment by Elvish-Hunter** [comment]
While it should be theoretically possible, I don't have a 3K or 4K screen to test a patch on it. So, I need a bit of help for this.

You have to open IDLE and then type the following commands:
```python
from tkinter import *
root = Tk()
print("Screen width:",  root.winfo_screenwidth())
print("Screen height:",  root.winfo_screenheight())
root.mainloop()
```
After that, you can close the window opened by Tkinter.
In IDLE, you should be able to read the outputs of the two print() commands. Can you please paste it here?

**Comment by Vultraz** [comment]
```>>> print("Screen width:", root.winfo_screenwidth())
Screen width: 1536
>>> print("Screen height:", root.winfo_screenheight())
Screen height: 864```

That's my resolution at 96 DPI. However, I have a 4k screen that's 240 DPI (IRC) 3840x2160.

**Comment by Vultraz** [comment]
According to @Elvish-Hunter, this is too difficult to fix using tkinter. It just doesn't have the mechanism needed. He also admitted it might be better to redo `GUI.pwy` at some point with a better UI toolkit. I intend to try to write a new version of it in Electron at some point if he doesn't get to doing it with QT (as he proposed) first, so closing this.
