### ISSUE TITLE
could not open image 'misc/laurel-gold.png'

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1985]
Since a few days the message `could not open image 'misc/laurel-gold.png'` appears in stderr.
In the misc directory are only laurel-bronze.png, laurel-silver.png and laurel.png
Strangely I get this message despite having any completed campaign.
I'm at 76c814d.
Besides that, when renaming, maybe a wmllint rule can be added to transform laurel.png to laurel-gold.png.

**Comment by sevu** [comment]
_If_ you have an campaign completed, then it shows the laurel in the campaign selection dialog, and tries to display it in the difficulty selection dialog of this campaign. The last thing doesn't work.

**Comment by Vultraz** [comment]
I reverted the change of the laurel image's name from `laurel-gold` to just `laurel` yesterday (just forgot to update the difficulty dialog), so no wmllint rule is needed.
