### ISSUE TITLE
bad names generated in default map generator

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#1986]
Testing with addon 'World conquest 2' (after replacing `map_generation` with `scenario_generation`) on latest master i found that

Observed behvaiour:
Stange names like `'s Forest` are generated

Expectd behaviour:

No names should be generated.

**Comment by CelticMinstrel** [comment]
Why do you expect no names to be generated?

**Comment by gfgtdf** [comment]
because there were no names generated in 1.12

**Comment by CelticMinstrel** [comment]
Well, from the minimal information you've given, I suppose it's probably the default secondary generators being used even though there's no primary generator. It should bail out if there's no primary generator in the `[naming]` tag.

**Comment by gfgtdf** [comment]
there is no maing [naming] tag and 1.12 would simply not generate names if ther eis no naming tag. 
https://github.com/wesnoth/wesnoth/blob/1.13.0/src/generators/default_map_generator_job.cpp#L785
this case seems be broken in 1.13
