### ISSUE TITLE
help entries of the new gates

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#1990]
The new gate terrains are listed 4 times in the help - for the three directions, with picture, and a forth one.
The rails and bridge terrains are just listed once, with the `^foo|` terrain. The open gate terrains are not listed (which I think is good).
`^Pw\ ^Pw| ^Pw/` are shown with their picture, I don't know what `^Pwd` is.

![helpgate](https://user-images.githubusercontent.com/21158813/30400770-45d5f260-98d8-11e7-9798-77d804e38a0b.png)

When opening the help page of an _open_ gate on the map, it opens the flatland category in the help browser and displays the help entry for the terrain, though not being listed in flatland.

And what I suspect is` ^Pw\o` on the map is listed with `^Pwo` in the help, while `^Pw/o` shows as `^Pw/o`.

**Comment by sevu** [comment]
Other thing, when starting with an new userdir, some terrains are listed from the beginning in the help, e.g. bridges and forests, other need to be discovered, e.g. flatland and castles.

I think terrains it hides base terrains, and lists terrains which extend a base terrain. I'm not sure if that is good.

**Comment by doofus-01** [comment]
I believe the multiple gate entries in the help menu is solved.  I haven't tested the issue of overlays not needing to be discovered is true, and #2036 would do nothing to address that.  @sevu - if you still find that (the overlays thing) to be true, please open another issue.
