### ISSUE TITLE
Show credits screen after finishing a MP campaign

### ISSUE THREAD

**Issue by Kwandulin** [wesnoth/wesnoth#1996]
When finishing a SP campaign, the credits screen is shown. When finishing an MP campaign however, the main menu shows.

I'd suggest to also show the credits screen in the second case.

**Comment by Wedge009** [comment]
https://irclogs.wesnoth.org/2022/06/%23wesnoth-dev.2022-06-29.log
> 20220629 15:31:04<+wdiscord> [Lord-Knightmare] Should <https://github.com/wesnoth/wesnoth/issues/1996> be closed?
> 20220629 15:31:14<+wdiscord> [Lord-Knightmare] credit screen does show for MP campaigns
> 20220629 15:47:58<+wdiscord> [Pentarctagon] yep
