### ISSUE TITLE
Inconsistency in wording in Damage Calculations dialog

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#2002]
While in left half it is written something like "Defender resistance vs blade x0.6",
in right half it is written "Attacker vulnerability vs blade x0.6";
even though the coefficient is decreasing the damage and it is "resistance" in both cases.

In other hand when the coefficient is above 1 (so it's actual vulnerability), the dialog will still say "resistance" in left half and "vulnerability" in right half.

**Comment by Vultraz** [comment]
It's meant to be "how much resistance does the defender have against your attack" and "how vulnerable your are to the defender's counterattack".

**Comment by Arcanister** [comment]
In this interpretation it sounds right, but if you assume that these worlds mean part if game mechanic, then selection of "resistance" vs "vulnerability" should be consistent with resistance being positive (e.g. 60%) or negative (e.g. -20% which is also called vulnerability) in help, or be called resistance in both cases? 

Or, since in attack calculation resistances are written in their true form instead of percents, they could be called "vulnerability" in both case since unit is more vulnerable when coefficient is bigger.

Also, in same dialog, ToD adjustment are written as +25% or -25%, not as x1.25 or x0.75 which is again not consistent with notation for resistance/vulnerability calculation.
