### ISSUE TITLE
Under the Burning Sun - Troll Tunnel Lua Crash (1.13.8)

### ISSUE THREAD

**Issue by jjStinger72** [wesnoth/wesnoth#2003]
OS: Linux Mint 18 (Sarah)
built wesnoth from source
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Wesnoth Version:  1.13.8
UtBS-In the Tunnels of the Trolls Turn 3

save file:
[UtBS-In_the_Tunnels_of_the_Trolls-Auto-Save3.gz](https://github.com/wesnoth/wesnoth/files/1304401/UtBS-In_the_Tunnels_of_the_Trolls-Auto-Save3.gz)

... attempting to end turn with a unit (any unit, any unit count, any turn) at the eastern wall to trigger the "explosion" causes the following error / crash.

Setting mode to 1024x774
Checking lua scripts... ok
20170914 15:52:19 error scripting/lua: lua/wml-tags.lua:742: bad argument #2 to 'scroll' (number expected, got nil)
stack traceback:
	[C]: in field 'scroll'
	lua/wml-tags.lua:742: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>

**Comment by gfgtdf** [comment]
This points to [scoll] which was recently ported to lua by @CelticMinstrel

**Comment by gfgtdf** [comment]
In fact it seems like he already fixed that one in https://github.com/wesnoth/wesnoth/commit/7c4e3c62f5346287f00c6023d4dc727bda96c7b4

**Comment by gfgtdf** [comment]
We can probably close this.
