### ISSUE TITLE
1.13 from master fails to report deprecation of description WML for multiplayer_side and set_menu_item

### ISSUE THREAD

**Issue by Shrieker1** [wesnoth/wesnoth#2004]
wesnoth 1.13.8 from master commit 8de5a2e786

I made following minimal test case to show what happens

~~~~
#ifdef MULTIPLAYER
[era]
    id=Foo_Bar
    name=_"A minimal bug test"
    description=_"Just for testing"
    require_era=no

    [multiplayer_side]
        id=bug_elves
        name="&units/elves-wood/fighter.png="+_"Elves"
        type=Elvish Fighter
        leader=Elvish Fighter
    [/multiplayer_side]
[/era]

[multiplayer]
    id=Buggy_Scenario
    name=_"Bug infestation"
    description=_"Just a mini scenario for bug testing"
    experienced_modefier=70
    victory_when_enemies_defeated=no
    map_data="border_size=1
usage=map

Gg, Gg, Gg, Gg, Gg
Gg, 1 Kh, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, 2 Kh, Gg
Gg, Gg, Gg, Gg, Gg"

    {DEFAULT_MUSIC_PLAYLIST}
    {DEFAULT_SCHEDULE}

    [side]
        side=1
        user_team_name=_"Side 1"
        team_name=side1
        canrecruit=yes
        controller=human
        gold=200
        income=0
    [/side]
    [side]
        side=2
        user_team_name=_"Side 2"
        team_name=side2
        canrecruit=yes
        controller=human
        gold=200
        income=0
    [/side]
    [event]
        name=start

        [set_menu_item]
            id=no_deprecation_message_for_old_style_formatting
            description="~supposed bold text=&units/elves-wood/fighter.png~SCALE(25,25)"
            image="units/elves-wood/archer.png~SCALE(25,25)"
        [/set_menu_item]
    [/event]
[/multiplayer]
#endif
~~~~

That shows old 1.12 accepted style to add images and format text in a description attribute. To help UMC porting from 1.12 to 1.14 it would be nice if these cases would be detected like [message] and [option] telling this syntax is deprecated.

multiplayer_side produces following warning and shows faction name with verbatim text
~~~~
warning gui/layout: pango_text::set_markup_helper text '<span color='#a69275'>&units/elves-wood/fighter.png=Elves</span>' has unescaped ampersands '&', escaped them.
~~~~

set_menu_item generates very similar warning

~~~~
warning gui/layout: pango_text::set_markup_helper text '~supposed bold text=&units/elves-wood/fighter.png~SCALE(25,25)' has unescaped ampersands '&', escaped them.
~~~~

**Comment by gfgtdf** [comment]
Note that the wiki page says: `Any image in this description will not use the team color.`, which make me wonder why woudl any 1.12 addon use decriptionwml over the immage attribute there at all ?

Anways, assigning to @Vultraz

**Comment by Vultraz** [comment]
*sigh* Alright, I'll deal with this crap.

**Comment by Shrieker1** [comment]
There is TC and RC image path function. I forgot to use it in my example. But it would allow changing the magenta to a team colour. For set_menu_item you can use TC($side_number,magenta) and it will use the colour for current side. An advantage of using description wml was that it allowed images to be placed in any column. But I don't haven't seen anyone using it. Neither I see any pressing need to use it.

**Comment by CelticMinstrel** [comment]
By the way, if anyone discovers stuff documented to be deprecated that does not yield a deprecated message, please report. Note though that some deprecated messages appear conditionally based on debug mode and the current log level. (Some even appear only on "info" log level, if I recall correctly, so you'd need `--log-info=scripting/lua` or some such to see them.)

**Comment by Vultraz** [comment]
Thinking about this more, I'll add a warning for `[multiplayer_side]` since the wiki advertised it could use the old DescriptionWML, but not `[set_menu_item]`, since that's never been a  thing.

**Comment by Vultraz** [comment]
@CelticMinstrel Quite hard, at least given OP's example, since they decided to throw the *ancient* legacy GUI1 formatting in there too O_O

**Comment by CelticMinstrel** [comment]
I implemented a check for DescriptionWML in `[set_menu_item]`. It handles the typical case of an image in the first column, but doesn't know anything about the other old markup such as `~`, and will just output the image path if you attempted an image in column 2 like in the example. Still, either way it _will_ print the deprecation message, so I'm closing this.
