### ISSUE TITLE
Horizontal scroll appears in file loading dialog

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#2006]
Wesnoth 1.13.8+dev master, GNU/Linux

When you open Load Game dialog from main screen or from within a scenario, horizontal scroll-bar appears and buttons "Cancel" and "Delete" do not fit completely, even if there is enough space in the window to fit them.

Expected behavior:
Loading dialog takes as much horizontal space as it needs, if there is enough space on left and right.

**Comment by Wedge009** [comment]
What language do you use? I haven't seen this, at least not for a while, and certainly not on current master (98c0443d). I just wonder if it's related to #1665.

**Comment by Arcanister** [comment]
I have built my version with DISABLE_NLS, thus it is probably en_US . Try setting resolution to 1024x768, though it happens with higher resolutions as well. But perhaps you have something like 1920x1080 where different interface theme is used?

**Comment by Wedge009** [comment]
I use the default theme and 1920x1200 as that's the largest I can comfortably go in windowed mode. But even going to the minimum 800x600 doesn't show anything unusual for me, in US English, in Windows or Linux. Perhaps you could share a screenshot of this issue?

**Comment by sevu** [comment]
Is there a super long filename (which doesn't have enough place on the right side),
or, does is happen if a specific, maybe even the first, has been selected once (so, that sth. would be to long for the left side).

**Comment by Arcanister** [comment]
It does apparently have something to do with my configuration, since starting with clean profile (and playing some tutorial to get some saves), makes the problem disappear, but tracking it down further goes for no avail so far.

**Comment by sevu** [comment]
I imagine it may have sth. to do with the saves listed

**Comment by Arcanister** [comment]
I think it's not save filename, but something like "Wednesday, 12:34" in data column

**Comment by Wedge009** [comment]
That sounds possible. Related, but perhaps not relevant, is #1709. The changing nature of the dates and the conditions on which days are printed may make this difficult to track down, but I think this is a likely culprit.

**Comment by Arcanister** [comment]
The full name of scenario is displayed in format like "TSG-Born to the Banner" in the left pane. It seems that in order to get scroll-bar I need to have all of:
a) save which has date transforming into a day of week
b) scenario which has long full name in some save
c) vertical scroll-bar in save list

**Comment by sevu** [comment]
basically you have this bug if you have to less place, a), b)  and c) are all different reasons which go for that.
b) can cause this even alone: long save names are shortened, but it's not for all the same. "MMMM..." as scenario name would case the bug, while "IIII..." wouldn't.

**Comment by Wedge009** [comment]
Does this still occur with 1.14.9 release?

**Comment by jostephd** [comment]
I created a situation in which a) b) c) all held and don't see the bug:

![2019-10-09-215419_555x45_scrot](https://user-images.githubusercontent.com/24784687/66523398-697e4400-eadf-11e9-9ba5-5e9aace6a587.png)

Please show a screenshot.

**Comment by sevu** [comment]
I think this was connected to the Boost Locale issue. However, 
![new](https://user-images.githubusercontent.com/21158813/66524746-90df0c00-eaf3-11e9-8f5d-0c8ce4f114a2.png)

Originally there is no scrollbar. My observation is:
The horizontal scrollbar comes into existence when the vertical one is created.
(you may not immediately see the vertical one, because you need to scroll left then)
- Having no saves from last week leaves more space, enough for all
- The scrollbar come into play when clicking a mid-scenario save, because then the left part needs also more space

(I think half of the above I read somewhere else before)

**Comment by jostephd** [comment]
Does this patch help?

```
diff --git a/po/wesnoth-lib/de.po b/po/wesnoth-lib/de.po
index bf44c61a7bf..34118197441 100644
--- a/po/wesnoth-lib/de.po
+++ b/po/wesnoth-lib/de.po
@@ -6112,7 +6112,7 @@ msgstr "Szenariostart"
 
 #: src/gui/dialogs/game_load.cpp:412
 msgid "Difficulty: "
-msgstr "Schwierigkeitsgrad: "
+msgstr "Schwierigkeitsgrad\n: "
 
 #: src/gui/dialogs/game_load.cpp:416
 msgid "Version: "
```

**Comment by Wedge009** [comment]
I wonder if there's another factor involved. I still can't find any horizontal scroll when a, b, and c apply - and I've checked with English, French, and German.

**Comment by jostephd** [comment]
I can reproduce it if I make the `Gold Left:` string longer.

**Comment by Wedge009** [comment]
With 1.15.17+dev (1.16 beta), I notice in situations where files produce wide text in the map preview section on the left, the dividing line between that and the list of files will automatically adjust to accommodate. For especially long strings, such as with German, I notice the horizontal scroll is now limited to the map preview section, not the whole load dialogue.

The only way I'm able to replicate this now is if I reduce to the minimum 800x600 window size. In such a constrained situation, I don't think a scroll bar is unreasonable. I think this can be closed now, but please re-open if you find a similar situation at the recommended 1024x768 or above.
