### ISSUE TITLE
occassional lua error at scenario start

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2010]
Occasionally this appears at scenario begin. It's not reproducible, just happens sometimes when you start a scenario, and mostly not. Once a day.
```
20170915 17:03:31 error scripting/lua: lua/wml-tags.lua:291: Error: Attempted to access an invalid music track.

stack traceback:
	[C]: in metamethod '__newindex'
	lua/wml-tags.lua:291: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
```

It would be great if this could be fixed for 1.13.9.

**Comment by Pentarctagon** [comment]
Perhaps related to #1861 ?

**Comment by sevu** [comment]
Maybe. The scenarios use the SCENARIO_MUSIC macro, which has immediate=yes in it.

**Comment by Arcanister** [comment]
I got this in Wesnoth Tutorial part II two times, but I didn't find exact conditions when it happens.

**Comment by Vultraz** [comment]
Someone fix this ASAP before the release.

**Comment by CelticMinstrel** [comment]
What makes you think it's simple enough to be fixed in (eg) twenty-four hours?

**Comment by gfgtdf** [comment]
was this fixed by d063aa077a481000192fbff9c5d1fa7c47962ba7 ?

Also i think it'd be better if all othse functions returned the lua nil value instead of an 'invalid misuc track'

**Comment by sevu** [comment]
This may be, maybe even earlier.
I haven't seen this for a while, but I wasn't doing much with wesnoth recently.

**Comment by CelticMinstrel** [comment]
Yeah, I think this is probably the same issue as #1861.
