### ISSUE TITLE
Have lobby play a sound when someone creates a game

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#2016]
Whenever a new game is created on the mp server, the lobby should make a sound for it, so people running wesnoth in the background can be notified.

Suggested on 2017-09-17 irc logs for ##wesnoth
20170916 21:13:26< Marcgal> Lobby plays a sound whenever some1 joins lobby or leaves
20170916 21:13:34< Marcgal> I'm disintrested with this
20170916 21:13:58< Marcgal> But Lobby doesn't play any sound when some1 creates a new joinable game
20170916 21:14:05< Marcgal> Too bad :(
20170916 21:14:37< Marcgal> This makes it impossible for me to have Wesnoth with Lobby in the background and do sth else while I wait for an interesting game to appear

**Comment by Wedge009** [comment]
Covered in #4259.
