### ISSUE TITLE
Wesnoth 1.12.6 ignores screen resolution settings at the start if window doesn't fit on screen.

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#2017]
GNU/Linux, X11. Problem seem to be specific to 1.12. Wesnoth 1.13 behaves as expected.

When Wesnoth 1.12 starts, while resolution is explicitly set as 1024x768, either in Wesnoth preference setting or -r 1024x768 key in command line, or both, the window of Wesnoth doesn't start with specified size, but get resized to fit in screen together with window borders and task-bar.

The window is nevertheless rendered as 1024x768, which means, that half of tool-tip string and whole version string get clipped.
When I move Wesnoth window, though, the resolution changes to accommodate window size.

Expected behavior:
When resolution is set explicitly, Wesnoth won't attempt to do anything with it and just set its window to desired size, even if it doesn't fit to screen, so I can later remove window decorations to use screen height more efficiently. Window should get automatically resized to fit the screen only if resolution is not specified and when it is, then resize event should be sent to rendering engine so it will work correctly from the start and not only after window was moved.

**Comment by Vultraz** [comment]
Since this is a 1.12 (and 1.14 is imminent) issue and the fix is likely part of the SDL2 refactoring in 1.13, I'm closing this.
