### ISSUE TITLE
Full Deprecation & Removal of Cmake Building

### ISSUE THREAD

**Issue by jcdenton2k** [wesnoth/wesnoth#2022]
Are there any explicit reasons for keeping cmake builds updated with each Wesnoth version?  Scons works just fine and has much better sanity-checking than cmake (from my personal experience) and it avoids certain issues from forgetting to read build documentation in-depth to enable a specific flag.

Cmake will be deprecating in some ways seen [here](https://github.com/wesnoth/wesnoth/issues/1956).  So why is so much development time & effort devoted to keeping it around?  Why not just keep scons and let that be it?

Not a feature 'request' (more like removal of an existing build tool setup) so I didn't believe forums would be appropriate for this.

**Comment by Arcanister** [comment]
Removing cmake support will break build scripts in many package managers which rely on cmake being present. It will also require some people building Wesnoth from source to learn about new build system. I do not know how to build Wesnoth with scons and never tried it.

**Comment by GregoryLundberg** [comment]
It will require some of us to have to abandon our IDE to use SCons by hand since many tools seem to support CMake and few support SCons.

**Comment by jcdenton2k** [comment]
Understood.  @GregoryLundberg thank you for the response.  I'll go ahead and close out this issue.
I had tried posting on the forums but my old account didn't exist anymore or something.  I'll just make a new one and post there.
