### ISSUE TITLE
Race icon "Image not found" for non-core races

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#2030]
I think that if race icon is not available, which is the case for most add-on races, then some generic icon should be used rather than image-not-found yellow hexagon.
Also it seems that race icon location is hard-coded, instead of being configurable in [race] tag

**Comment by sevu** [comment]
It's possible to specify add icons in images/icons/unit-groups/ with naming the images
race_qwertz_30.png and race_qwertz_30-pressed.png. I also saw WoL using twice as big images named
race_qwertz_30@2x.png and race_qwertz_30-pressed@2x.png, thought I don't know if they are used.

I see it as the Era maintainers responsibility to support this.
If none are used, no image will be displayed, if you use debug mode you will find out that there belongs an image.

**Comment by Arcanister** [comment]
What "pressed" icon is for? You can't press race icon, can you?

**Comment by sevu** [comment]
These images were originally used in the  map editor.

When creating a new image, it's best to keep the borders free, so they fit fine with the button from the editor UI, and the editor is more restrictive about which colors you can use for this images.

With [some](https://github.com/sevu/EoM/tree/master/images/icons/unit-groups/race_EOM_celestial_30.png) [image](https://github.com/sevu/EoM/tree/master/images/icons/unit-groups/race_EOM_celestial_30-pressed.png), during whose creation I used an antialiasing algorithm while downscaling, I'm having an issue, while it's fine in the recruit / debug placement dialog.

**Comment by Arcanister** [comment]
So custom race icons are possible, but their location is hardcoded.  I think that their location should be settable in [race] tag like images which are used for units and other things

**Comment by gfgtdf** [comment]
@Arcanister this is possible but, i don't really see the advantages. But we shodul fix the 'image-not-found' issue and use another default race image image.

**Comment by Arcanister** [comment]
In either case it should be documented in [wiki](https://wiki.wesnoth.org/UnitsWML#.5Brace.5D), so UMC authors can find it.

If it won't be configurable in [race], then image-not-found error/warning still should be spit to console, so UMC author can figure out where to put race icon.

**Comment by CelticMinstrel** [comment]
I agree with @Arcanister here - the race image should be specified in the `[race]` tag.

**Comment by Arcanister** [comment]
There are also ToD icons and Alignment icons. Is it possible to make custom alignment?
Custom ToDs should be definitely possible.

**Comment by CelticMinstrel** [comment]
Custom times of day are possible. Where are these ToD icons used though?

As far as I know, custom alignments are not possible.

**Comment by Arcanister** [comment]
I can't find any ToD icons except editor's "switch time" icon. So probably problem is only with race icons at the moment. Though if we introduce custom alignment we will also need ability to specify new alignment icons.

**Comment by Vultraz** [comment]
Looking at the code, it turns out there is actually a key to specify an icon in `[race]`: `editor_icon=`. However, this key is undocumented on the wiki, and uses a non-standard syntax. Instead of specifying the path of an image, it takes an image stem. For example: `editor_icon="icons/unit-groups/race_custom"`. I'll need to ponder how to improve the design, and whether to change the key name.

**Comment by Vultraz** [comment]
I'll deal with possibly renaming `editor_icon=` and the path it expects at a later date.
