### ISSUE TITLE
Joining and leaving an MP game leaves it in weird state

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#2040]
Behavior noticed with current master. Steps to reproduce:
- have somebody else create normal 2-player MP game.
- Join this game
- Leave game
- Join again, as observer (normal join won't work)

Problems arising from that:
- ~~You are still listed as player, while you are observer~~
- ~~Teamname for your former team becomes untranslated and is displayed as "teamname^South"~~
- ~~Esc key drops game to main screen instead of just leaving the game~~
- ~~Random gender icon now displays "null" tool-tip, if you hover mouse over it. Normally it doesn't display any tooltips (probably should display "random"), unlike explicitly selected genders icons.~~

**Comment by gfgtdf** [comment]
This could happen if you connect to a server that was build before https://github.com/wesnoth/wesnoth/commit/8abb21e7074765842f37186cc9086e3b8abd177b

**Comment by gfgtdf** [comment]
the server  was rebuild so the main isue is fixed, mp ui issues are still there.

**Comment by Vultraz** [comment]
Remaining items fixed by the commits above.
