### ISSUE TITLE
Maximizing window makes Wesnoth render content in incorrect resolution in certain conditions

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#2041]
Problems appear when I use 1280x800 screen. In Wesnoth drop-down list I can select 800x600, 1024x768 and 1280x800.

- If I select 800x600, then press maximize button, I get window correctly maximized and resolution 1280x755 appearing in drop-down list and currently selected, as expected.

- However, if I select 1024x768 and press maximize, window gets resized to 1280x768 and cannot be moved (due to maximized state). In this state low-most part of window is inaccessible.

- If I select 1280x800, and press maximize, windows is resized to 1280x755 correctly most of time.

Note: I usually use 1024x768, because it's "standard" resolution, I would like it remain accessible, even if window doesn't fit in screen initially, since it could be made to fit by removing decorations or hiding taskbar.

**Comment by Wedge009** [comment]
I'll grant that sometimes things don't quite work the way you might expect when changing things like resolution, but on a Linux platform with a 1280x800 screen, I couldn't replicate the second point. Maximising the window resized the dimensions to 1280x741 (which is what Wesnoth comes to when taking my desktop taskbar into account).

**Comment by Arcanister** [comment]
My research shows that the problem is somewhere between window manager and SDL, since debug log of window manager shows correct ConfigureNotify being sent ( could be obtained starting WM from command line with --debug option).
Meanwhile debug log of SDL/Wesnoth (could be obtained [here](https://hg.libsdl.org/SDL/file/007dfe83abf8/src/video/x11/SDL_x11events.c#l44)) shows that ConfigureNotify had incorrect dimensions.
Though that was preliminary check, need verifications.

**Comment by CelticMinstrel** [comment]
I get the distinct impression that this, #2035, and #2050 are likely the same issue... if so, two of them should be marked as duplicates and closed.

**Comment by Wedge009** [comment]
I agree, but didn't want to take any unilateral action. Doing so now, with your second opinion.
