### ISSUE TITLE
Improve error message when an add-on contains a bad file/folder name

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#2043]
Currently when the add-ons server rejects an add-on due to having an invalid character in a folder or file name, all it returns is:
`Add-on rejected: The add-on contains an illegal file or directory name. File or directory names may not contain whitespace or any of the following characters: '/ \ : ~'`

Since it knows that the file name has one of those invalid characters, the error message should also tell what those files are, rather than just leaving the user to hunt them down themselves.  As an example, fmac's add-on Era of Second Chances encountered this issue, and as a result it was required to search though all 801 files to find only a few that had a whitespace in the file name([download](http://www.mediafire.com/file/sa20v0m49j9s39k/Era_of_Second_Chances.tar.gz)).

**Comment by Arcanister** [comment]
Server implementation doesn't have to hunt all filenames down though, it could reject the add-on after finding first nonconforming file name.

Does the server message mean that all other characters such as control's \1 to \039 are allowed in filenames?

A side not: It's not that hard to search for filenames, anyway. In GNU/Linux or MacOS X environment, user can use a command such as:
 `find Addon_Name -name '*[!A-Za-z0-9_.+@-]*'` 

 A Windows user can install cygwin or apply CMD or PowerShell and type something like:
`dir /a /s /b | findstr /i /r /c:"[^a-z0-9_.+@\\:-]"`
Though it is more tricky to construct a proper command there.

A file manager with search capabilities can also be used.

**Comment by jyrkive** [comment]
@Arcanister I bet there are many UMC authors who don't have the first idea about how to find files with command line.

**Comment by Arcanister** [comment]
Even if they are Windows users they can use Explorer and type `"*~*.*" "* *.*"` in search string including quotes. Colons and slashes are prohibited by OS itself anyway, so there is should be no need to check for them.

**Comment by jyrkive** [comment]
My point was that they have no idea *what* they need to write to the search box.

**Comment by Arcanister** [comment]
Even if Windows user can't use powershell, it can be done with cmd:
```
 dir /a /s /b "C:\Users\Your Login Name\My Games\Wesnoth1.13\data" | findstr /e /r /c:"[\\][^\\]*[^\\A-Za-z0-9_.+@-][^\\]*"
```
This command will scan all installed add-ons for incorrect filenames. It will also notice names having unicode characters outside of ASCII. It could be done to report only characters which Wesnoth addon server actually rejects, if necessary, but it is good practice to avoid special characters in resource names.

**Comment by sevu** [comment]
Windows users don't use any shell. But you can add it somewhere in the wiki.

**Comment by Pentarctagon** [comment]
@Arcanister Not to say that those commands aren't useful, but I think you are vastly overestimating the number of people who know `cmd.exe` or powershell even exist.

**Comment by gfgtdf** [comment]
is this fixed?

**Comment by Pentarctagon** [comment]
Looks like it: https://i.imgur.com/FkKTnHQ.png

**Comment by GregoryLundberg** [comment]
I can see it now:

`What is the ''' character? Does the list include ' and .`

While technically correct, a quoted list and terminating period are visually confusing. I'd suggest a line-break and showing only the characters and no punctuation.

**Comment by CelticMinstrel** [comment]
Agreed,
