### ISSUE TITLE
fake map border broken with sdl 2.0.6+

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2061]
![bildschirmfoto der karte_003](https://user-images.githubusercontent.com/21158813/31051439-ba3a1ecc-a668-11e7-8c91-656c9c1c9d90.png)
The offmap terrain is as well affected.
I assume the reason is the switch to sdl2.0.6, since this changed recently.

Tested with current master and dbd6695. The recent commits by Doofus are not related.
Can someone confirm this not happening with sdl 2.0.5? I uploaded the map [here](https://pastebin.ubuntu.com/25650938/).

**Comment by Pentarctagon** [comment]
This [does not happen](https://i.imgur.com/IxHrh50.jpg) for me in the map editor with SDL 2.0.5, on Mint 18.2.

I also tried loading this through Multiplayer > Local Game > User Maps, and it was... strange.  I've opened another issue for that though.

**Comment by Arcanister** [comment]
I can confirm that Wesnoth with SDL 2.0.6 has this problem, and 2.0.5 has not. OS is GNU/Linux (X11), wesnoth binary same.

**Comment by zonkmachine** [comment]
Yo!

You could test and see if this is fixed in the [SDL 2.0.7 prerelease](https://discourse.libsdl.org/t/sdl-2-0-7-prerelease/23232).

**Comment by Wedge009** [comment]
As noted in #2131 this seems to occur in Aethermaw as well.

**Comment by Wedge009** [comment]
@Vultraz Seems to do the trick. Funny thing about the alpha layer.
