### ISSUE TITLE
"Instruct Ally" menu layering incorrectly on iOS version

### ISSUE THREAD

**Issue by justinmcdavid** [wesnoth/wesnoth#2065]
I'm using version 1.0.6 for iOS (iphone), and noticed this issue LOW-Elves' Last Stand campaign/scenario.

When I attempt to instruct an ally by setting an objective or setting behavior, the choice menu appears behind the game layer (see attached screenshots).

![img_8040](https://user-images.githubusercontent.com/12969375/31059415-a37e5376-a6b6-11e7-808e-4741ddeb9709.PNG)
![img_8041](https://user-images.githubusercontent.com/12969375/31059417-a862b3fa-a6b6-11e7-8d7a-86c7e254798b.PNG)
![img_8042](https://user-images.githubusercontent.com/12969375/31059418-aadfbc90-a6b6-11e7-887a-f7c2106cef2c.PNG)

**Comment by soliton-** [comment]
Doesn't happen anymore in the current version. Even when iphone support is back it's unlikely to have this bug.
