### ISSUE TITLE
Scrolling position in Lua console is reset constantly

### ISSUE THREAD

**Issue by Arcanister** [wesnoth/wesnoth#2067]
GNU/Linux, X11, Wesnoth master.

Steps to reproduce:
1) Start a scenario in debug mode ( e.g. start as `wesnoth -dt` )
2) Press [~] key to invoke Lua console
3) Enter some commands, so window content becomes long enough, for example, a, b, abc, abcd

Actual result:
After enough commands are entered, pressing Enter makes scrolling position jump on top of console text output.

Expected result:
Scroll position should show result of last entered command.

Seems to be unrelated to GNU history support, since reproduces both on builds with and without it.

**Comment by sevu** [comment]
Can confirm this.
It happens (only) with long commands, so that the line with the error message has a line break.

**Comment by gfgtdf** [comment]
from looking at the code it seems like it shoudl scroll to the bottom when a new input is executed see this line https://github.com/wesnoth/wesnoth/blob/1.13.9/src/gui/dialogs/lua_interpreter.cpp#L103 which shoudl do that. No idea why it doesn't work.

**Comment by Arcanister** [comment]
It seems that when I input correct commands such as `2+2` or simply `543315`, scroll works like expected, but once I type a command resulting as error such as any random word, console starts to jump to top every time, even if I start entering "correct" commands again.

**Comment by Vultraz** [comment]
Known issue. Something triggers a relayout in the scroll label.

**Comment by CelticMinstrel** [comment]
This is an issue with long text fields in general, not just the Lua console (you can also trigger it in lobby chat if I recall correctly).

**Comment by Arcanister** [comment]
Is it hard to fix line counting, taking line wrapping into account and invalidating it on window side change?

**Comment by CelticMinstrel** [comment]
I think accounting for line wrapping is (was?) the hard part.

**Comment by GregoryLundberg** [comment]
Best advice: when you're about to press Enter on a Lua command, close your eyes for a second. That way you won't be annoyed at the scroll-top-scroll-bottom flicker.
