### ISSUE TITLE
Wesnothd crashes on startup if it cannot bind to port

### ISSUE THREAD

**Issue by AI0867** [wesnoth/wesnoth#2073]
> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51                                                                                 
> #1  0x00007fafccf443fa in __GI_abort () at abort.c:89                                                                                                              
> #2  0x00007fafcd85b0ad in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6                                           
> #3  0x00007fafcd859066 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6                                                                                     
> #4  0x00007fafcd8590b1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6                                                                     
> #5  0x00007fafcd8592c9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6                                                                    
> #6  0x0000562ce84c65e2 in boost::throw_exception<boost::system::system_error> (e=...) at /usr/include/boost/throw_exception.hpp:69                          
> #7  0x0000562ce84c090b in boost::asio::detail::do_throw_error (err=..., location=0x562ce8686596 "bind") at /usr/include/boost/asio/detail/impl/throw_error.ipp:38
> #8  0x0000562ce84c0868 in boost::asio::detail::throw_error (err=..., location=0x562ce8686596 "bind") at /usr/include/boost/asio/detail/throw_error.hpp:42        
> #9  0x0000562ce8500ea1 in boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> >::bind (     
>     this=0x7ffed8e59fe0, endpoint=...) at /usr/include/boost/asio/basic_socket_acceptor.hpp:377                                                               
> #10 0x0000562ce84f8e38 in server_base::start_server (this=0x7ffed8e59fc0) at src/server/server_base.cpp:52                               
> #11 0x0000562ce84a707d in wesnothd::server::server (this=0x7ffed8e59fc0, port=12345, keep_alive=false, config_file=...) at src/server/server.cpp:261
> #12 0x0000562ce84bfa59 in main (argc=5, argv=0x7ffed8e5a898) at src/server/server.cpp:2814

**Comment by sevu** [comment]
other report for this: #1757

**Comment by CelticMinstrel** [comment]
If it's a duplicate, you should close it.
