### ISSUE TITLE
Objective for "Hills of the Shorbear Clan" scenario is unclear

### ISSUE THREAD

**Issue by adam4235** [wesnoth/wesnoth#2080]
In the "Hills of the Shorbear Clan" scenario (Sceptre of Fire campaign) the objective says to kill the leader, then have all your heroes in the caves with no enemies in the caves.  I assumed that "caves" meant the caves surrounding the starting position in the top-left of the map.  Only by reading the code (data/campaigns/Sceptre_of_Fire/scenarios/5_Hills_of_the_Shorbear_Clan.cfg file) for the scenario did I discover it actually meant the caves in the centre of the map.  Could the dialogue be changed to make this clearer?  Other people have had the same confusion, for example in this thread:

https://forums.wesnoth.org/viewtopic.php?f=22&t=20347

I have version 1.12.5.

**Comment by adam4235** [comment]
Perhaps better yet: add a label on the map saying "Shorbear caves", to more clearly show the caves that you're supposed to put everybody in.

**Comment by ln-zookeeper** [comment]
> Have all heroes in the Shorbear caves while no enemies are in the caves

Isn't that pretty unambiguous? If really necessary, then I guess it could be changed to something like this to make sure someone can't think the latter "caves" includes the starting caves too:

> Have all heroes, and no enemies, in the Shorbear caves

**Comment by adam4235** [comment]
The wording of the objective itself is fine.  The confusion comes from not knowing what the Shorbear caves are - I didn't know they were the caves in the middle of the map.  Again a label would fix this.  Also, the dialogue gave me the impression that my units were killing the leader, stealing his tools, and then retreating back to our caves due to overwhelming enemies.
