### ISSUE TITLE
help text of "Starting Tool": incomplete sentence

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#2085]
https://github.com/wesnoth/wesnoth/blob/94f3a4c2de23aec2e7f6deadd0b08a0215f44d90/data/core/editor/help.cfg#L70

There appears to be a missing word after "certain".

**Comment by GregoryLundberg** [comment]
The missing word is "whatever". No, I'm serious, that's what was accidentally deleted from there. The commit comment which added it stated, "Still contains a lot non-sense and stubs."

This tool adds numeric stating locations as well as marks special named locations.
