### ISSUE TITLE
Remove Lit Stone Wall terrain in favor of a Torches overlay

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2087]
Even with the introduction of all these wall variants, only the Stone Wall has a lit variant. It'd be stupid to create Lit variants for every single wall, so I propose making the torches an overlay so they can be used with any wall.

**Comment by doofus-01** [comment]
That's not a bad idea.  It will require starting from scratch though, so it won't get done tonight.  A general "torch/sconce image-set" would be useful in all sorts of instances.

**Comment by Vultraz** [comment]
On second thought, the Lit Stone Walls terrain should probably be kept around for legacy purposes.

**Comment by Vultraz** [comment]
BTW, if you're redrawing the torches from scratch, might I suggest you make them larger than the current ones? Right now they're rather small.

**Comment by doofus-01** [comment]
General FYI that I'm working on this in PR #2103

**Comment by doofus-01** [comment]
Commit 2a79475 addresses this, correct?
