### ISSUE TITLE
wmlindent crashes in case of invalid encoding

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2091]
```
Traceback (most recent call last):
  File "/usr/bin/wmlindent", line 260, in convertor
    linefilter(filename, infp, outfp)
  File "/usr/bin/wmlindent", line 322, in <lambda>
    convertor(lambda n, f1, f2: reindent(n, f1, f2),
  File "/usr/bin/wmlindent", line 118, in reindent
    for line in infp:
  File "/usr/lib/python3.6/codecs.py", line 711, in __next__
    return next(self.reader)
  File "/usr/lib/python3.6/codecs.py", line 642, in __next__
    line = self.readline()
  File "/usr/lib/python3.6/codecs.py", line 555, in readline
    data = self.read(readsize, firstline=True)
  File "/usr/lib/python3.6/codecs.py", line 501, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wmlindent", line 323, in <module>
    arguments, "|".join(exclude))
  File "/usr/bin/wmlindent", line 261, in convertor
    except bailout as e:
TypeError: catching classes that do not inherit from BaseException is not allowed

```

**Comment by AI0867** [comment]
What should wmllint do in this case? Skip the file and note that it has an illegal encoding?

**Comment by GregoryLundberg** [comment]
Yes

**Comment by Arcanister** [comment]
I also think that wmllint should do dry-run by default and perform any actions involving modifying files only if requested with a command-line option, not vice versa.

**Comment by CelticMinstrel** [comment]
I would agree about dry-run being on by default.

**Comment by sevu** [comment]
I disagree about dry-running. There's no need, keep it simple.
Currently users don't need to have any knowledge about about the tool, besides finding out that they have to give the files as argument.
Since wmlindent is only indenting, there's nothing which breaks or which is controversial.
Not even wmllint does dry-run by default (though I think it should).

I must say, I often check in git what did change with wmlindent, but that's only out of curiosity.

To the question what wmlindent should do if it encounters an illegal character:
Crash peacefully down and print a message about the file and line. That makes it more obvious that it's not the tools fault. I liked how wmlxgettext (the new one) prints error messages.

I would stop when encountering such a file and not continued with other ones, because then you are more likely to fix the problem. Though, it's an option.

I could as well think that wmlindent could be written in a way that it can process files with illegal characters, after all it doesn't has to process the directly. But I  think it's connected to additional pain, and it's not having a payoff, since the illegal characters must be fixed anyways.

**Comment by AI0867** [comment]
Failed bailout fixed by c5b19ed66d.

**Comment by CelticMinstrel** [comment]
Ohh somehow I got my tools mixed up. Yeah, wmlindent should not dry-run by default, but wmllint should.

**Comment by Elvish-Hunter** [comment]
Instead of having a `bailout` catch-all exception class, wouldn't it be better if we replace it with `except UnicodeDecodeError as e:`? This way, `bailout` won't catch every possible exception (potentially hiding possible bugs while doing so), and we could implement a more specific error message for non UTF-8 files.
As for wmllint, sounds good to replace the `--dryrun` switch with a `--perform-changes` switch? However, there might be some kind of backward compatibility issue if someone's using wmllint inside a script (although I'm not aware of any instance of this, beside GUI.pyw, which can be easily updated anyway).

**Comment by cooljeanius** [comment]
@virtualghetto says BOMs (Byte-Order Marks) can cause this, too
