### ISSUE TITLE
SCons no longer works

### ISSUE THREAD

**Issue by GregoryLundberg** [wesnoth/wesnoth#2093]
Building with SCons is no longer working.

The errors start with ~/SConstruct line 20, the file() function has been removed from Python, and cascade thereafter.

This appears to be an issue with SCons 3.0.0 temporarily downgrading to SCons 2.5.1 works around the issue,

**Comment by Pentarctagon** [comment]
If you change
`optfile = file(GetOption("option_cache"))`
to
`optfile = open(GetOption("option_cache"))`
does it work with scons 3.0.0?

That is what's recommended [here](https://docs.python.org/release/3.0/whatsnew/3.0.html#builtins).

**Comment by GregoryLundberg** [comment]
That is the first of several errors.

The next on can be fixed by using open().readlines() and string.join()

But then you get an error in the PO scons and I'm not up to tracking it down further tonight. So I'm hoping someone with more Python experience will fix it.

**Comment by Wedge009** [comment]
Aye, SCons 2.5.1 build still works for me.

**Comment by GregoryLundberg** [comment]
Confirming works for both 2.5.1 and 3.0.0
