### ISSUE TITLE
Crash on iOS and MacOS (?) in case-insensitive sorting

### ISSUE THREAD

**Issue by singalen** [wesnoth/wesnoth#2094]
Extracted from #1759 as a different problem.

Discussion from development Discord channel:
[19:53] sinda: Have exactly this problem on iOS: https://stackoverflow.com/questions/39809811/boost-locale-compare-throws-exc-bad-access
Strange, all the objects involved are non-null.

My stack is:
```

#0	0x0000000000000000 in 0x00000000 ()
#1	0x00000001014ed7f8 in boost::locale::collator<char>::compare(boost::locale::collator_base::level_type, char const*, char const*, char const*, char const*) const at /Users/vic/src/wesnoth/wesnoth/projectfiles/Xcode-iOS/battleforwesnoth/../lib/iOS_boost_1_60/libs/boost/include/boost/locale/collator.hpp:81
#2	0x00000001014ed788 in translation::icompare(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /Users/vic/src/wesnoth/wesnoth/src/gettext_boost.cpp:429
#3	0x00000001013830c4 in gui2::dialogs::campaign_selection::sort_campaigns(gui2::window&, gui2::dialogs::campaign_selection::CAMPAIGN_ORDER, bool)::$_1::operator()(std::__1::shared_ptr<ng::level> const&, std::__1::shared_ptr<ng::level> const&) const at /Users/vic/src/wesnoth/wesnoth/src/gui/dialogs/campaign_selection.cpp:149
```

@CelticMinstrel:
> The trace from @singalen sounds like the same crash that I've gotten for awhile on the Mac when opening the file dialog (for example, go to map editor and click Load Map). Not sure if it's the same as that described in the opening post, but I recall @ancestral investigating a little and finding evidence of some binary compatibility issues between Boost and its dependencies (libiconv if I recall correctly) as the cause.

@singalen:
> Might be the case. iOS version has access to two `iconv`s: Apple's version and GNU version. Sadly, glib and friends doesn't build on Apple `iconv`.

@CelticMinstrel:
> If it is binary incompatibilities, it just means that the libraries @ancestral builds with need to be carefully tuned to require the correct version of the dependencies... which is easier said than done, mind you.

It doesn't crash for me on MacOS, only on iOS. I have Boost as a pre-built shared library in MacPorts.
Applying [this workaround](https://stackoverflow.com/a/27957170/207791) didn't help.

**Comment by mattsc** [comment]
Confirming that this is happening for me (both the Campaigns -> Name and the Editor -> Load Game crashes) in macos 10.12 with both the 1.13.10 package and my own build of current master.
Marking as blocker.

**Comment by mattsc** [comment]
Extracted from [here](https://forums.wesnoth.org/viewtopic.php?f=5&t=47054&start=15#p620122):
> I've done some more digging and found that the crash originates in https://github.com/wesnoth/wesnoth/blob/master/src/gui/dialogs/file_dialog.cpp#L96 when called from https://github.com/wesnoth/wesnoth/blob/master/src/gui/dialogs/file_dialog.cpp#L493.

That's for the edior crash.  But I don't know what that means, what to do about it or even whether this is useful additional information here.

**Comment by singalen** [comment]
Worked around. Probably it's something about [static variables in statically linked libraries](https://stackoverflow.com/questions/26990412/c-boost-crashes-while-using-locale) between gettext and boost::locale.

**Comment by CelticMinstrel** [comment]
Really not happy that the workaround is to sort case-sensitively, though.

**Comment by singalen** [comment]
For me, it was a quick fix that's definitely better than a crash in the field.

It should be doable to link Boost dynamically on MacOS. On iOS, it took me a royal pain to find a semi-working version and have it build and run. On top of that, can we enforce Boost::locale to be linked only as a shared library?

As for the other fix at SO... I think I might not have dug deep enough and gone through ALL the binaries that access `Boost::locale`. There should be a way to instantiate that singleton.

**Comment by CelticMinstrel** [comment]
I'm pretty sure Xcode _is_ dynamically linking Boost though? And I know the error occurred in the Xcode build.

Now that it's at least not crashing, the priority has dropped, but we still need to fix this somehow. I guess it could wait until after 1.14 though.

**Comment by singalen** [comment]
Looks like that, but the crash is happening. Maybe on XCode it is DIFFERENT statically linked library, say, `gettext`? I don't build on Mac with XCode, so cannot tell.

My suggestion is to reopen the issue, and leave the workaround in.

**Comment by CelticMinstrel** [comment]
Alright, will do.

I thought everything was dynamically linked in the Xcode build, but it's been quite awhile since I looked at it, so I could be remembering wrong.

**Comment by cooljeanius** [comment]
> Alright, will do.
> 
> I thought everything was dynamically linked in the Xcode build, but it's been quite awhile since I looked at it, so I could be remembering wrong.

Is this still the case?

**Comment by Pentarctagon** [comment]
Is this issue still happening?

**Comment by CelticMinstrel** [comment]
I don't recall seeing this crash recently. I'm not confident it's definitely gone though, as opening the file dialog isn't the most common action when I'm working on Wesnoth.

**Comment by singalen** [comment]
The issue is probably with the sort on iOS being `#ifdef`-ed to be case-sensitive.

**Comment by cooljeanius** [comment]
See some in-depth discussion about iOS case-sensitivity in iains/gcc-darwin-arm64#101 and the mailing list threads linked to from within it.

**Comment by Wedge009** [comment]
Closing on basis of https://github.com/wesnoth/wesnoth/issues/4786#issuecomment-2091829550. Can always re-open if this proves to be an issue for current macOS builds.

**Comment by CelticMinstrel** [comment]
I haven't seen it since migrating my Wesnoth development back to Mac.
