### ISSUE TITLE
wesnoth: SDL_ConvertSurface_REAL(): wesnoth killed by SIGSEGV

### ISSUE THREAD

**Issue by jorti** [wesnoth/wesnoth#2098]
The game crashes before showing any window. More info in the Fedora bug report:

https://bugzilla.redhat.com/show_bug.cgi?id=1501244

All packages are the provided by Fedora 27:

wesnoth-data-1.13.8-4.fc27.noarch
wesnoth-1.13.8-4.fc27.x86_64
SDL2_image-2.0.1-8.fc27.x86_64
SDL2_mixer-2.0.1-5.fc27.x86_64
SDL2_ttf-2.0.14-5.fc27.x86_64
SDL2-2.0.6-2.fc27.x86_64

```
Truncated backtrace:
Thread no. 1 (5 frames)
 #0 SDL_ConvertSurface_REAL at /usr/src/debug/SDL2-2.0.6-2.fc27.x86_64/src/video/SDL_surface.c:937
 #1 SDL_ConvertSurfaceFormat_REAL at /usr/src/debug/SDL2-2.0.6-2.fc27.x86_64/src/video/SDL_surface.c:1051
 #2 SDL_SetWindowIcon_REAL at /usr/src/debug/SDL2-2.0.6-2.fc27.x86_64/src/video/SDL_video.c:1704
 #3 game_launcher::init_video() at src/game_launcher.cpp:362
 #4 do_gameloop at src/wesnoth.cpp:608
```

**Comment by Vultraz** [comment]
Actually, can you test again with 1.13.10? I think we fixed this.

**Comment by jorti** [comment]
1.13.10 works fine. Thank you.
