### ISSUE TITLE
Add ActionWML tag for storing unit terrain defense

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2107]
It is already possible (and unofficially implemented) with Lua, but tag version is frequently requested.  

References:
https://forums.wesnoth.org/viewtopic.php?f=21&t=44946  
https://forums.wesnoth.org/viewtopic.php?f=21&t=45553  
https://forums.wesnoth.org/viewtopic.php?f=21&t=45564

**Comment by ProditorMagnus** [comment]
Seems it is implemented already, but documentation is missing https://github.com/wesnoth/wesnoth/commit/e4552c7a758b8cef7b794773df08762becdc904c#diff-d471df014b92a45ed106cf664118b43c https://wiki.wesnoth.org/Referencewml

**Comment by CelticMinstrel** [comment]
Feel free to copy the documentation from the commit message to the wiki.

**Comment by ProditorMagnus** [comment]
Done.
