### ISSUE TITLE
Traits in the help

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2108]
1) Showing traits which have no description in the help doesn't look good, it shows only a page with the name, nothing else.

2) Traits without name are listed in the help too (in the way you would imagine it).

In the 2nd case they may have been used to add secretly some effect, I think that they should remain hidden.

**Comment by jostephd** [comment]
> In the 2nd case they may have been used to add secretly some effect, I think that they should remain hidden.

They're already hidden in the unit preview pane.

Submitted #2163.
