### ISSUE TITLE
high dpi icon

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2109]
If wesnoth has an icon of size 128x128 or higher, it's beneficial in the gnome-software store.
Currently there is a 64x64 icon included, but the logo on wesnoth.org uses a higher resolution.
Could we include a better set of icons?

**Comment by Vultraz** [comment]
https://www.dropbox.com/sh/lncz6sp106f3fyn/AADApxh8acnBZ29F6b4G2zzIa?dl=0

**Comment by CelticMinstrel** [comment]
I think OSX also supports 256x256 icons.

**Comment by Vultraz** [comment]
That size is packaged with the Windows version. Is it not with the macOS one?

**Comment by CelticMinstrel** [comment]
I have no idea!

**Comment by sevu** [comment]
Thanks for the images @Vultraz. PR #2113 wires them in.
There are a few other sizes where we could add images for (such as 72x72, 96x96 and a few more), but I'm not sure if this improves anything, since they would just downscale an image anyway.
