### ISSUE TITLE
high contrast icon

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2110]
similar to #2109, if someone would create a high contrast icon it would be beneficial too.

**Comment by Vultraz** [comment]
High contrast?

**Comment by sevu** [comment]
![bildschirmfoto von 2017-10-21 16-24-29](https://user-images.githubusercontent.com/21158813/31856438-7548220a-b6c1-11e7-8a1b-50f6e266e7ed.png)
Icons like that, meant for visually impaired people.

**Comment by CelticMinstrel** [comment]
It would be good, yeah, but I wonder how playable Wesnoth is for people who would need that...

**Comment by sevu** [comment]
Trying to collect the technical requirements:

- Either a svg, _or_ a set of pngs in the sizes 16x16, 22x22, 24x24, 32x32, 48x48 and 256x256
- It might be helpful to look on a Linux system in the /usr/share/icons/HighContrast/ folder, and the apps subfolder. Alternatively one can look [here][a] or [here][b]. Probably easiest to take the colors from there.

Some Links:
- How it looks in general [1]
- Gnome calls these symbolic icons [2]
- An very old and outdated document, only linking for Table 9-3 [3]
- When scrolling down to basics, there are a few words about 16x16, 22x22 icons. [4] Though the page is not about high contrast icons.

[a]:http://ftp.tu-chemnitz.de/pub/linux/debian/debian/pool/main/g/gnome-themes-extra/gnome-accessibility-themes_3.28-1_all.deb
[b]:https://www.archlinux.org/packages/extra/x86_64/gnome-themes-extra/download/
[1]:https://wiki.gnome.org/Initiatives/GnomeGoals/HighContrastAppIcons
[2]:https://developer.gnome.org/hig/stable/icons-and-artwork.html#custom-symbolic-icons
[3]:https://developer.gnome.org/hig-book/unstable/icons-design-accessible.html.en
[4]:https://community.kde.org/KDE_Visual_Design_Group/HIG/IconDesign
[5]:https://community.kde.org/File:Breeze-icon-design-1.png

**Comment by sevu** [comment]
@Vultraz I recall there being a svg-logo added to one of the other repos recently, I can probably be reused here. Can you link to it.

**Comment by Vultraz** [comment]
Here ya go! https://github.com/wesnoth/resources/blob/master/images/wesnoth-logo-simple.svg Should be perfect. Credit to Leonard03.

**Comment by Wedge009** [comment]
I think other OSs are moving towards this flat, monochrome icon style too.

**Comment by GregoryLundberg** [comment]
I'd do fill:black instread of grey, but otherwise, rendering this SVC as and ICO in various resolutions should close this issue.

**Comment by Vultraz** [comment]
We can't use the svg directly?

**Comment by sevu** [comment]
In the cases that the icon is used, it will be together with the other ones here. They should be the reference. In particular, due to the white frame they are usable if the background is dark (like in the screenshot) or white (like mostly) ![theme-arc-dark](https://user-images.githubusercontent.com/21158813/64480858-63d7ca80-d1d0-11e9-905c-0a2cf72c948f.png)

Right wesnoth icon is the one Vultraz linked, left one with some edits, in particular an option which add's a frame over the object — but the problem is, that the frame does not only expand outwards the object, but also towards the interior, so it "eats" the image if it's to wide, and has an free space between sword and shield.

**Comment by sevu** [comment]
Added with https://github.com/wesnoth/wesnoth/commit/fda90a1896f67a46cadfce3484f1ad9d380f26cf
Source files at https://github.com/wesnoth/resources/commit/9433a8b8fb8ea30f5bf5c12b8db36182676c1477

Similar to the image below, but with bigger frame:
![in-use](https://user-images.githubusercontent.com/21158813/64928574-74182700-d81a-11e9-9bc3-00fd737f8079.png)

**Comment by Wedge009** [comment]
I like that the outlines of the Wesnoth logo shield was kept. Thanks.
