### ISSUE TITLE
Assertion Failure for AI with two leaders - src/attack_prediction.cpp:1763

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#2117]
On v1.13.10+dev (f6c4f3d214), the program aborts with assertion failure:
`wesnoth: src/attack_prediction.cpp:1763: double {anonymous}::calculate_probability_of_debuff(double, bool, double, double, bool, double): Assertion 'prob_touched >= 0.0 && prob_touched <= 1.0' failed.
Aborted (core dumped)
` 
when the AI has control of a side with two leaders, each with their own 'extra_recruit' lists, but the side recruit list is empty.  

Such a situation used to work just fine, I'm not sure when this first became a problem - I think it was OK in 1.13.8, but I'm not sure.

I'm attaching a demonstration scenario.  If you modify the map to remove the secondary keeps (the encampments), the game does not abort.  Campaign is found in list with name "Empty Recruit List".
[Demo_Camp_D.zip](https://github.com/wesnoth/wesnoth/files/1405777/Demo_Camp_D.zip)

**Comment by doofus-01** [comment]
@jyrkive  - Well, it _is_ fixed, but your description seems unrelated to the situation I described.  If the recruit lists and keeps business (no enemy required, within range at least) makes sense to you, it's all good.  Just bringing it up in case this is suppressing a symptom of something that will flare up again later.

**Comment by jyrkive** [comment]
My description is about the actual cause of the bug, which I found out by debugging in your test scenario. Your guess about two leaders was incorrect. (Indeed, attack prediction code doesn't even know how many leaders you have.)

**Comment by doofus-01** [comment]
Well, I only know when it showed up, and your description still doesn't apply to what I saw (who was dying? -> no one.  Why do the secondary keeps matter?  Why does changing the recruit list matter?)
But I'm not a programmer, so I wouldn't understand.

**Comment by jyrkive** [comment]
It was in attack prediction. It predicted that one combatant was 100% guaranteed to die in a future fight if it were to occur.

**Comment by doofus-01** [comment]
Hence my incredulity...  Please explain how that applies to these: 
1.  Using that same test add-on, just change the side 1 recruit list from `recruit=""` to `recruit="Bowman"` and the crash goes away (using f6c4f3d again).  Move the Bowman to the `extra_recruit="Spearman"` list, and it crashes again.
2.  Remove the two `Ke` terrain from the map, or make the map bigger and start the Spearman somewhere where it can't reach the `Ke` hex, and the crash does not happen.
