### ISSUE TITLE
Multiplayer lobby "join" and "observe" buttons enter the wrong game

### ISSUE THREAD

**Issue by Samonella7** [wesnoth/wesnoth#2121]
For wesnoth 1.13.10:

In the multiplayer lobby, I can only enter the currently highlighted game. Clicking on different games changes which is highlighted, of course, but the "join" and "observe" for different games will enter the currently selected one.
![lobby](https://user-images.githubusercontent.com/21229771/32022380-716284a8-b993-11e7-99db-45a86ab25ade.png)

**Comment by Vultraz** [comment]
Oh dear.
