### ISSUE TITLE
Multiplayer: game freeze in specific circumstances

### ISSUE THREAD

**Issue by Samonella7** [wesnoth/wesnoth#2122]
For wesnoth 1.13.10:

If it is the host's turn and the host has a dialogue box with [option]s, the client's game will freeze until the host's player closes the message. The client can't scroll around the map, select units or anything.

If it is the client's turn when this happens, I get the expected behavior (client can still scroll around etc, and there is a message saying "Waiting for input from side(s)<side>"). If the client gets the message instead of the host, the host has expected behavior regardless of whose turn it is.

I haven't tested with more than 2 players.

**Comment by gfgtdf** [comment]
i wasn't able to reproduce this.

**Comment by Samonella7** [comment]
Here is a simple mod and save that you should be able to easily reproduce it with. It displays a message any time a unit dies (the message is for the side of the victorious unit). I can reliable reproduce it, using two windows 10 computers (regardless of which one is the host).

To load the save file you might need to use the nicknames "Samonella2" and "Samonella3" since that's what I used when creating the game. If I understand it right you should be able to use any nick, but i had trouble with that. It might be another bug, I'm not sure.

[simple_mod_and_save.zip](https://github.com/wesnoth/wesnoth/files/1488883/simple_mod_and_save.zip)

**Comment by gfgtdf** [comment]
i tested with your save with a 1.13.10+dev version from november, while i was able to reproduce the 'unable to load it with a different nick' issue, i am still not able to repdoduce the freeze

**Comment by gfgtdf** [comment]
makring as 1.14, for the 'To load the save file you might need to use the nicknames ' oart not for the 'game freeze in specific circumstances ' part

**Comment by Vultraz** [comment]
Confirmed the the freeze doesn't happen with 1.13.11+dev. I don't really see the "might need to use the nicknames" issue. When I load the save, it initially sets the side controllers to those nicks, and if I try to join, I become an observer (found a different issue here, but that's another problem). However, I could (as the host) set the controller to Network Player to allow my other client to join normally (without the special nick).
