### ISSUE TITLE
Windows: minimizing from full-screen mode bug

### ISSUE THREAD

**Issue by Samonella7** [wesnoth/wesnoth#2123]
For wesnoth 1.13.10:

In full-screen mode, keyboard shortcuts win+d and alt+tab don't minimize the game like they should. 

Alt+tab should minimize the game so that the desktop is behind whatever other program is switched to, but it leaves Wesnoth open behind the other program.

Win+d does nothing at first. If I press it several times in succession it will usually minimize the game, but when I open some other program, Wesnoth re-opens behind the new one (so it ends up in the same state as alt+tab).

**Comment by CelticMinstrel** [comment]
Why should alt-tab minimize the game? I wouldn't expect that.

**Comment by GregoryLundberg** [comment]
Not on Windows or my Linux Display Manager.  Alt-Tab simply cycles the focus and pops the newly-focused window to the top of the Z-order.

**Comment by CelticMinstrel** [comment]
I think I've seen fullscreen games that minimize when you alt-tab out of them, but I've never _expected_ that behaviour.

**Comment by Wedge009** [comment]
I'm inclined to agree that this isn't a valid bug - my personal experience of desktop convention (and I recognise everyone will have different experiences) is that switching windows from a full-screen application (usually) does not minimise that full-screen application. As CelMin said, _some_ applications may choose to minimise themselves, but I find this is an exception not the norm.

If minimising happened in previous Wesnoth versions, I have a feeling that may be more related to your window manager rather than Wesnoth itself.

**Comment by Samonella7** [comment]
Huh, well you're all the boss. Win+d should definitely minimize it though, yes? Am I the only one that's misbehaving for?

**Comment by GregoryLundberg** [comment]
I checked 1.12.5 and 1.13.10+dev and cannot see any issues with task switching or minimizing on my Arch box. Yes, Win+D clears the desktop by minimizing all windows, including Wesnoth.

**Comment by jyrkive** [comment]
The reason why this behavior is new in Wesnoth 1.13.10 is that it was requested in #1606.

**Comment by GregoryLundberg** [comment]
On both Linux and Windows 10:

First open a small window: the filesystem browser.
Next open Chromium and pressed F11 to put it into full-screen mode
Then open Wesnoth and go to Preferences to set it to full-screen mode.

Testing Alt-Tab shows the small window and menu bar atop the full-screen window: works the same for Chromium and Wesenoth on both Window 10 and Linux.

Testing Alt-D minimizes all windows to a blank desktop with menu bar works the same for all, as well.

I cannot find any combination where Westnoth does not behave the same as Chromium on either Windows 10, or my Arch Linux (using LxQT and Openbox).

Marking this invalid and closing it. If additional follow-up shows there actually is an error, this issue can be re-opened.
