### ISSUE TITLE
Planning mode sprite missing

### ISSUE THREAD

**Issue by inky17** [wesnoth/wesnoth#2124]
When planning a move using planning mode, there is supposed to be a grey sprite left at the destination indicating where you planned to move a unit, but nothing shows up.

Noticed this on a previous 1.13 version though it still happens in 1.13.10. Works in 1.12. OS: windows 10

**Comment by Wedge009** [comment]
I vaguely recall this used to be the case (I only ever used planning mode in testing). If it's a deliberate design decision to remove it, I think this is fair too. But it may well be unintentional.

**Comment by Wedge009** [comment]
The future sprite is in full colour rather than being greyed out as it used to be. Otherwise, at least there's a unit there now.

**Comment by gfgtdf** [comment]
did you test that 1.12 has it greyed out?

**Comment by Wedge009** [comment]
I don't have working 1.12 or 1.13 builds any more, but I do know that it was previously grey when I worked with planning mode in the past.

**Comment by CelticMinstrel** [comment]
Needs either an image mod suffix or to use one of the internal whiteboard animations.

**Comment by gfgtdf** [comment]
> I don't have working 1.12 or 1.13 builds any more, but I do know that it was previously grey when I worked with planning mode in the past.

hmm my memory tell me the opposite unless you tested it i will assume 1.12 behaved just like 1.14.1 in that regard.

**Comment by CelticMinstrel** [comment]
It would be extremely weird in my view if the planning mode sprite were indistinguishable from a regular sprite.

**Comment by gfgtdf** [comment]
well you still have the red arrow pointing to that unit with the 'ghosted' unit in the orgin place, so it's not that hard to distinguish them.

**Comment by Wedge009** [comment]
Is 'ghosted' supposed to mean translucent? It looks like normal unit transparency to me.

Anyway, I suppose you were right after all - it's the planned origin that's greyed out, not the the planned destination.

http://www.tuxarena.com/wp-content/uploads/2012/02/planning_mode.png
