### ISSUE TITLE
Lobby private message characters limit in UI too small

### ISSUE THREAD

**Issue by JasonSpine** [wesnoth/wesnoth#2126]
When I double click a player in lobby I can type only 18 characters for private message. I think it's too short. As for public chat there is much more characters to type. Sometimes I need to write longer private messages and I'd like to use gui rather than using whisper command. Please, rise the limitation. Thanks!

**Comment by Vultraz** [comment]
I can't reproduce this. What version are you using?

**Comment by Vultraz** [comment]
Related: #1255. But again, I cannot repro this.

**Comment by Vultraz** [comment]
Are you seeing this dialog?
![dlg](https://user-images.githubusercontent.com/3558659/32082386-f136fabe-bb06-11e7-86dc-a844629b3599.PNG)

**Comment by Wedge009** [comment]
I have a feeling that might be what he's referring to. Could be an improvement, but I don't really think it's a bug.

**Comment by Vultraz** [comment]
That dialog isn't used anymore, which is why I think he might be looking at 1.12...

**Comment by Wedge009** [comment]
(checks MP)

Why, so it is. Yeah, 1.12 is limited, your redesign for 1.13 is not.

**Comment by JasonSpine** [comment]
Sorry, I was sleeping ;)

I'm using stable Wesnoth 1.12.6 on Mac OS.

I made a video to show the limit:
https://www.youtube.com/watch?v=JjankgTKdwQ

When I reach it I cannot type more characters.

**Comment by Vultraz** [comment]
Ah, I see. This is no longer an issue in 1.13, where the Lobby has been redesigned. Thanks for reporting, though. 🙂
