### ISSUE TITLE
"Enemy unit sighted" text does not appear

### ISSUE THREAD

**Issue by inky17** [wesnoth/wesnoth#2130]
When your unit's move is interrupted due to sighting an enemy unit, the only text that pops up is "press t to keep moving."

Wesnoth ver. 1.13.10; windows 10

**Comment by Wedge009** [comment]
Yes, it's gone.

**Comment by Vultraz** [comment]
No idea what could have caused this :(

**Comment by Pentarctagon** [comment]
I believe #2097 supposed to fix this.

**Comment by galegosimpatico** [comment]
@Pentarctagon thank you! 😓

**Comment by Vultraz** [comment]
That was merged earlier, can someone confirm if this is fixed?

**Comment by Wedge009** [comment]
The message as a whole only hangs around for a second or two, which might not be long enough for the player to read - but that might be a separate change and possibly one to deal with an old bug report about messages overlapping each other.

Anyway, yes, this particular issue seems to be fixed now. Thanks.
