### ISSUE TITLE
Bad transparency in some transitions

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#2131]
I haven't tested much for a while so I'm not sure when this started, but I noticed in master (tested at 0cb203e9) that Aethermaw has some bad transparency in the water transitions. This happened for me in both Windows and Linux, and I'm not sure where else this kind of issue happens (I know Aethermaw already has some strange transparency issues in #1406).

![aethermaw](https://user-images.githubusercontent.com/13679322/32089026-489f0fea-bb33-11e7-9447-0c9a09b8463e.png)

**Comment by Pentarctagon** [comment]
Looks related to #2061

**Comment by Wedge009** [comment]
Aye, I must have missed that one. I did test with 2.0.6 and 2.0.7.

**Comment by Wedge009** [comment]
Closing in favour of #2061.
