### ISSUE TITLE
Random hexes get highlighted when setting a path for a unit with no moves left

### ISSUE THREAD

**Issue by inky17** [wesnoth/wesnoth#2132]
When you select a unit that has no moves left, and then click somewhere else on the map, a bunch of hexes (the southern half of the map it seems like) will suddenly become highlighted.

Wesnoth ver. 1.13.10; windows 10

**Comment by GregoryLundberg** [comment]
Confirming on 1.13.10+dev(d98d7aa80c-Clean) on Arch Linux. For me, the random highlighting was originally a bit random but on mouse release it followed the mouse cursor as I waved it around.

**Comment by Wedge009** [comment]
Ooh, that is bizarre indeed. For me, yet more highlighted hexes follow my mouse cursor as I move it around. The effect stops when I highlight the selected unit again.

**Comment by GregoryLundberg** [comment]
Dunno. Just someone asked about it a few days ago and it released and updated on Arch in the part day or two.

**Comment by Vultraz** [comment]
@jyrkive is it possible this has to do with your optimization changes, specifically the the draw-once-not-twice bit?

**Comment by jyrkive** [comment]
It's possible, but my guess would be rather #2055.

**Comment by jostephd** [comment]
Bisected to 8e388c1b3557f436cd524fb35572e40c739043ba, the fix for #1908.  Submitted PR #2148.

**Comment by Vultraz** [comment]
If that didn't fix this, let me know and I'll reopen.
