### ISSUE TITLE
One test fails with scons3

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2137]
This test fails in scons:
`Checking for Ogg Vorbis support in SDL... no`

The result of this test is cached, all will work fine until you build with --config=force
I first assumed it's the sdl2.0.7 update, but I still have this problem after a downgrade.
There's no problem with playing .ogg files in the cmake build.

This affects the 1.13.10 version too, we need a patch file for it.

**Comment by GregoryLundberg** [comment]
Confirmed

**Comment by loonycyborg** [comment]
I can't reproduce this. Can you paste build/config.log?

**Comment by GregoryLundberg** [comment]
@loonycyborg Sure but all you'll see is warning about unused variable argc and argv .. no errors or other warnings. Compiles, links, runs, no output to stderr/stdout. Returns EXIT_FAILURE and that's it.

**Comment by GregoryLundberg** [comment]
Reverted to sdl2-2.0.6-2-x86_64.pkg and scons-2.5.1-1-any.pkg and still failing. There is a -l library (sdl_mixer) commented out in the Pyhton; add it back in didn't help.

Checking my logs I see sdl_mixer updated to 2.0.2 on 26OCT so checking that ...

**Comment by GregoryLundberg** [comment]
I'm thinking this is the reason. I don't do SDL so I'll leave it to someone who knows more to see what to do about this.

> Mercurial > SDL_mixer / changeset
summary | shortlog | changelog | graph | tags | bookmarks | branches | files | changeset | raw | bz2 | zip | gz | help 
Only load music interfaces that are explicitly initialized or needed for audio content
author	Sam Lantinga <slouken@libsdl.org>
Tue, 24 Oct 2017 21:41:50 -0700 (3 days ago)
changeset 839	7fa15b556953
parent 838	7d6df0a13bd0
child 840	90e3ffcfea04
Only load music interfaces that are explicitly initialized or needed for audio content

**Comment by GregoryLundberg** [comment]
Added print for Mix_GetError().

Message reads "Unrecognized audio format"

**Comment by GregoryLundberg** [comment]
Added Mix_Init (MIX_INIT_OGG) and printed error: "OGG support not available"

**Comment by loonycyborg** [comment]
According to doc Mix_Init() should be enough. I'll look into it more once this version of sdl-mixer makes it to my distro.

**Comment by GregoryLundberg** [comment]
Methinks I'll pull down the source kit and build it myself. Most likely it's a bad build upstream. As I read the docs, Ogg is supposed to be enabled by default for all SDL builds. Or maybe there's an incompatibility with the Ogg Vorbis libraries. The crap is the reason I switched to Arch from Ubuntu .. I got tired of waiting for Cannonical to get around to it.

**Comment by Pentarctagon** [comment]
The 2.0.2 changelog also states as having
> Updated external libraries flac-1.3.2, libmodplug-0.8.9.0, libogg-1.3.2 and libvorbis-1.3.5

so that might be it.

**Comment by GregoryLundberg** [comment]
Don't think that's it. Those are the same libs used by 2.0.1 and have not updated for quite some time. The only replacement needed is to revert to 2.0.1 and scons --config=force works.

As a next test I told scons' sdl.py feature-test to always succeed and built Wesnoth. The Wesnoth executable has no problems playing OGG music files using 2.0.2.

So, I'm thinking it's just that the sdl.py is too simplistic.  I don't see why, tho. As said earlier, it looks like all one need do is Mix_Init(...) and Mix_LoadMUS(...) but Mix_Init is saying OGG isn't available .. so what is Wesnoth doing which sdl.py isn't?

**Comment by GregoryLundberg** [comment]
scons sdl.py tests Mix_LoadMUS() which instantiates a Mix_Music class/struct with an OGG file pathname. It simply tests whether it got a Mix_Music struct or a NULL pointer back.

wesnoth sound.cpp uses Mix_FadeInMusic() with a Mix_Music class/struct built with Mix_LoadMUSType_RW which uses filesystem::make_read_RWops given an OGG file name. The music plays, so I'm assuming the Mix_Music struct was non-NULL.

I'm getting far out of my ken here but it seems to me that either both constructors should fail or both should succeed, given a specific file.

**Comment by GregoryLundberg** [comment]
The following code works when compiled from the command-line. I took it from a sample found by Google and stripped it down until removing any more causes an error.

```
#include <stdlib.h>
#include <stdio.h>

#include <SDL2/SDL.h>
#include <SDL2/SDL_mixer.h>

int main(int argc, char ** argv)
{
    if (Mix_OpenAudio( 44100, MIX_DEFAULT_FORMAT, 2, 1024 ) == -1) {
        fprintf(stdout, "Cannot initialize SDL Mixer: %s\n", Mix_GetError());
        return (EXIT_FAILURE);
    }

    Mix_Music* music = Mix_LoadMUS("/home/lundberg/wesnoth/data/core/music/main_menu.ogg");
    if (music == NULL) {
        fprintf(stdout, "Cannot load music file: %s\n", Mix_GetError());
        Mix_CloseAudio();
        return (EXIT_FAILURE);
    }

    fprintf(stdout, "Success\n");
    Mix_FreeMusic(music);
    Mix_CloseAudio();
    return (EXIT_SUCCESS);
}

```

I compile and run it, by hand, with the following commands:

```
[lundberg@lundberg-arch sdltest]$ cc main.c -o main -lSDL2 -lSDL2_mixer
[lundberg@lundberg-arch sdltest]$ ./main
Success
[lundberg@lundberg-arch sdltest]$
```

So, I copied the file into sdl.py and adjust it for the $TESTFILE and backslash escapes. But when I run it there I get an error on stderr:

`ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to open slave
`

And stdout (configure26.out) shows this happens during Mix_OpenAudio:

`Cannot initialize SDL Mixer: ALSA: Couldn't open audio device: Device or resource busy
`

At this point I'm lost in what the Python scripts are doing which differs from what I did by hand, but I'm fairly confident that, with my corrected C program, the error is somewhere on the Scons Pyhton scripts.

**Comment by loonycyborg** [comment]
Seems it can't access sound device. I'd prefer if it didn't try to access sound device since it's not part of test's purpose. I don't see a way for Mix_OpenAudio to run without opening sound device unfortunately. Also doc says it requires SDL_Init(SDL_INIT_AUDIO), yet it somehow works for you without using it.

**Comment by loonycyborg** [comment]
This PR makes sdl-mixer 2.0.2 work for me. I suspect it might fail on other systems due to some sound subsystems being dependent on environment variables. Does running "scons OS_ENV=true" fix this for you?

**Comment by GregoryLundberg** [comment]
OK. I pulled the PR with your latest, @loonycyborg, and it's working fine without the OS_ENV=true bit.

@sevu can you pull test  PR #2151 and verify it solves the problem for you, as well?
