### ISSUE TITLE
In Dark Forecast, it's impossible to choose a faction/leader/color.

### ISSUE THREAD

**Issue by singalen** [wesnoth/wesnoth#2147]
Dark Forecast has `force_lock_settings=yes`.
Currently `force_lock_settings` completely locks faction selection.

Added in 0c92fbd10ba627c05edf401532dc5e9005192ff8 on 7/4/17,
> "Added force_lock_settings=yes to "A New Land" and "Dark Forecast" 
> Without it, it was possible to uncheck "Use Map Settings" and make choices (such as factions, teams, turn limits) which can break the scenarios."

I don't think this was the author's intention. I believe, faction, leader, position and color selections should be allowed. The factions are balanced to be more or less equal in strength, in the end.

[Reported by user](https://forums.wesnoth.org/viewtopic.php?f=67&t=46963#p618538).

**Comment by gfgtdf** [comment]
In the bugreport in the forums he said that the faction in 'Dark Forecast' is not only locked (to random) but also that no recuits are aded to the side at all which would make that scenario completely unplayable. So i'm amrking this blocker

**Comment by CelticMinstrel** [comment]
Uh, why did you mark this as "MP Lobby"? It doesn't sound like it has anything to do with the lobby UI.

**Comment by gfgtdf** [comment]
i use the mp lobby label for the whole gui2 mp setup dialogs (mp lobby, mp create, mp staging) not just the lobby, that's also how it's done in multiple other reports.

**Comment by CelticMinstrel** [comment]
Even considering that, I don't see how this has anything to do with the lobby. It sounds more like a report about a specific MP scenario.

**Comment by gfgtdf** [comment]
I thought the problem here was that 'force_lock_settings=yes' is not suposed to lock the faction too (just those entried in the create game dialog) , but i'm not sure on this one.

**Comment by Vultraz** [comment]
With `force_lock_settings` a proper faction list isn't even generated in the FLG dialog. It just get a "Custom" entry.

**Comment by gfgtdf** [comment]
i think this this is caused by the gui2 port of that dialog, it's mosrelikeley to be casued by https://github.com/wesnoth/wesnoth/commit/0c92fbd10ba627c05edf401532dc5e9005192ff8 and the spmp patch in 1.13.0

So we basicially have 2 ways of fixing that:
1) add leader_lock/faction_lock=no so the [side]s in that scenario
2) Dont use force_lock_settings as a default value for leader_lock/faction_lock

**Comment by ln-zookeeper** [comment]
Sorry, it was silly oversight on my part. I don't think there's a need for force_lock_settings to behave differently.
