### ISSUE TITLE
friend list: buggy when same username added twice

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2156]
Battle for Wesnoth v1.13.10+dev (61bbd51-Clean)

Preferences -> Multiplayer -> Friends
add "a" two times
you will have two "a"s
select one and click "remove"
one "a" will disappear but one will remain
select remaining "a" and click "Remove"
=> "No username specified"

Easy fix might be to not allow having same name in the list multiple times

**Comment by ProditorMagnus** [comment]
That would happen when updating note of friend, it should overwrite previous case of that name.
