### ISSUE TITLE
false positive invalid nick name: "-_-"

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2157]
![foo](https://user-images.githubusercontent.com/476013/32293786-89fb8350-bf44-11e7-8015-d013c27c0c39.png)

nick only consists of hypens and underscores, game still didn't like it

**Comment by Wedge009** [comment]
Weird one, but technically inconsistent with the dialogue text. Maybe there's an assumption that at least one alpha-numeric character is needed? '-_-t' worked for me.

**Comment by soliton-** [comment]
Indeed the issue is the error description. utils::isvalid_username() is the function that checks the nick and it checks for at least one alpha-numeric character.

**Comment by Vultraz** [comment]
> Only alpha-numeric character (one at minimum), underscores and hyphens are allowed.

How's this sound?

**Comment by matthiaskrgr** [comment]
Yes, sounds good to me, thanks. :)
