### ISSUE TITLE
Broken Default era, usage of string `"null"` instead of empty list

### ISSUE THREAD

**Issue by vn971** [wesnoth/wesnoth#2158]
"Deathblade" unit type has its "advances_to" field set to string "null". In Lua:
`wesnoth.unit_types["Deathblade"].__cfg.advances_to`

It should be an empty list(string) "". Otherwise it's broken. Without a fix Lua scripts will have to consider "null" to be a special case string.

Other units in default Era that have a "null" string: "Halberdier", "Javelineer", "Gryphon Master", "Soothsayer". Maybe some others, too. Most units are OK.

**Comment by sigurdfdragon** [comment]
Note that it appears to be the current convention in mainline, as there are 116 occurrences of advances_to=null in unit.cfg files in /core/units

**Comment by vn971** [comment]
@sigurdfdragon hmm, indeed you're right.

There probably was some other mistake with my Lua code that made me think Deathblade special.

Since this is standardized across Default era, I think we should accept it as-is. Closing issue. Thanks for the remark!

**Comment by gfgtdf** [comment]
yes advances_to=null is supported and removing suport for it would possibel break addons for no gain. What you coudl do however is fiel a feature request for <unit_type>.advances_to (just like units,  without going through '__cfg') which woudl then now only return a lua vector/table but also strip those null entries.

**Comment by vn971** [comment]
@gfgtdf that's a nice suggestion.
