### ISSUE TITLE
Dialog fails to repaint, and window switch is not Esc!

### ISSUE THREAD

**Issue by GregoryLundberg** [wesnoth/wesnoth#2159]
All my windows are maximized. I'm in AToTB in debug mode checkout out the statistics dialog and using Alt-Tab to switch to the shell, or VSCode, then flip back to Wesnoth and don't see the statistics dialog. I wave the mouse around and most of the elements appear, like the data lines and the Close button, but nothing brings back the background/border or static labels. Click Close when I can see it and press 's' again and the dialog looks normal until I do it again.

So I decide to see if it's just that one dialog and start afresh. No problems until I get to the intro to AToTB and the Alt-Tab'ing cancels the intro, and then cancels the [start] conversations .. as if I was pressing Esc. Anyway I'm finally back to the S01 map and it's my first turn.

Bring up the Objectives and Alt-Tab and they disappear.
Same for Unit List.

So instead of Alt-Tab I restore (out of maximize to normal window) and the dialogs disappear.

IT looks like we're handling repaid find for the main window but if dialogs are up we're not repainting them.

**Comment by GregoryLundberg** [comment]
If I resize by dragging an edge or corner, I can sometimes see the dialog appear and disappear. If I'm really careful and stop the resize when it's there, it usually stays visible.

**Comment by matthiaskrgr** [comment]
I noticed that dialogs failed to redraw after changing window resolution, maybe this is the same issue.
![wesbug](https://user-images.githubusercontent.com/476013/32319636-8d361f22-bfbb-11e7-9ff6-c7ad1482d108.jpg)

**Comment by sevu** [comment]
Is it since c6d8692 (followed up e5fb29d) or already older?

**Comment by jostephd** [comment]
I see this with e5fb29dba666a5dfc30a7fddbae3ccd4218b8696: if I Alt-Tab away from wesnoth while the Objectives or "Do you really want to quit? [yes][no]" dialog is displayed, the dialog is not repainted when I Alt-Tab back, instead I get the main map.  Any labels in the main map are hidden, and if I mouseover a dialog button it appears.  If I press Esc to dismiss the (invisible) dialog everything continues normally.
