### ISSUE TITLE
Assertion Failure

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#2178]
BfW 1.13.10+dev; Win 7 x64 mingw w64 5.3.0 build

Assertion Failed
src/gui/widgets/generator_private.hpp, Line 688
Expression: index < items_.size()

Introduced in: https://github.com/wesnoth/wesnoth/commit/9902b07519ca023b6d141bb80529ee1e15ccb99c

Occurs when I use add-on GUI Debug Tools.
To reproduce:
Install GUI Debug Tools Add-on
Launch AToTB S01
Have on or activate debug mode
Right-click on a side 1 unit and select 'Side Debug' OR right-click on on a side 2 unit and select 'Unit Debug'. (but the opposite, unit debug on a side 1 unit or side debug on a side 2 unit doesn't trigger it.)

**Comment by sigurdfdragon** [comment]
@GregoryLundberg I assume you made that with GDT 0.9.6? I don't get that last line in my log with my latest dev version (soon to be 0.9.7)

**Comment by GregoryLundberg** [comment]
Whatever was on the addons server at 11:13 CST. I'd never installed it before so had to snag a copy. This was second run. First just verified the message. Second I stepped carefully to be sure all this appeared specifically on the menu item and not earlier. Also, by doing a second run I didn't show the addon server messages from bad or missing components for other addons.

**Comment by GregoryLundberg** [comment]
OK. Updated your addon and all those gui/parse warnings are gone. All that's left on my console, now, is the assertion failure.

**Comment by sigurdfdragon** [comment]
thanks
