### ISSUE TITLE
Multiplayer > Local game function activates "Server" dialog

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2179]
Steps to repro:
* start wesnoth-1.13
* click Multiplayer Game > Connect to Server
* enter address `server.wesnoth.org:14997`, click connect
* log out
* exit wesnoth and start it again
* click Multiplayer Game > Local Game

Expected at this point:
* starting a local game

Observing:
* the `Connect to Server` dialog which asks for server address.

**Comment by jyrkive** [comment]
Fixed in commit a324534a6a0e38f65570c7e8093d48703ffb1223.

**Comment by vgaming** [comment]
@jyrkive thank you!
