### ISSUE TITLE
Opacity IPF ignores hundreds place

### ISSUE THREAD

**Issue by matsjoyce** [wesnoth/wesnoth#2185]
- Wesnoth version: master 192fbdc17355d6a26e5c4b966190cf8f18dda57e
 - Build env:
    - G++ 7.2.0
    - CMake 3.9.4
    - SDL 2.0.7
 - OS: Arch Linux 4.12.13
 - Repro: Put the following in `data/tests/scenarios`, execute `wesnoth -t optest` and move a unit:
    ```
    {GENERIC_UNIT_TEST "optest" (
        [event]
            name=moveto
            {VARIABLE i 0}
            [while]
                [variable]
                    name=i
                    less_than=40
                [/variable]
                [do]
                    [remove_item]
                        x,y=4,4
                    [/remove_item]
                    {VARIABLE_OP i add 1}
                    [item]
                        x,y=4,4
                        halo="halo/fire-aura.png~O($i|0%)"
                    [/item]
                    [label]
                        x,y=4,4
                        text="halo/fire-aura.png~O($i|0%)"
                    [/label]
                    [delay]
                        time=100
                    [/delay]
                [/do]
            [/while]
        [/event]
    )}
    ```
 - Expected result: Fire halo gets increasingly brighter
 - Actual result: Halo opacity resets to 0 when a multiple of 100 is reached.

**Comment by Vultraz** [comment]
I think this is a case of It's Not a Bug It's A Feature.

**Comment by matsjoyce** [comment]
:confused: The [wiki says](https://wiki.wesnoth.org/ImagePathFunctionWML#O:_Opacity_modifying_function) "an image will be displayed at its native opacity with ~O(100%)", while currently the image vanishes.

**Comment by Vultraz** [comment]
Oh, you mean it has 0% opacity when set to 100%? That is indeed a bug.

**Comment by matsjoyce** [comment]
Yeah, it's like it just takes the last two digits of the percentage. It's workaroundable, but not consistent with 1.12.

**Comment by Vultraz** [comment]
I assume you don't expect any change past 100%?

**Comment by matsjoyce** [comment]
It would be nice if it continued increasing alpha on the partially transparent pixels (I think that's what 1.12 does) but clamping it at 100% wouldn't cause any problems either.

**Comment by Vultraz** [comment]
Above commit restores the described 1.12 behavior ^ :) Thanks for pointing this out.
