### ISSUE TITLE
Cannot save game from within a replay

### ISSUE THREAD

**Issue by mattsc** [wesnoth/wesnoth#2186]
It is not possible any more (1.13.10+dev) to save the game from within a replay.  The 'save game' menu option is not there, and the keyboard shortcut does not work either.

Reproducing this is super simple: just open any replay and try to save the game.

I have tried this with both SP and MP replays, and I have deleted both cache and preferences to make sure nothing was corrupted.  The bug was confirmed by vn971 on irc.

**Comment by Vultraz** [comment]
This check is the issue: https://github.com/wesnoth/wesnoth/blob/master/src/hotkey/hotkey_handler.cpp#L328

`replay_controller` has a `comand_disabler` member which causes that item to vanish. If I change that to `return true`, the Save Game entry appears, but I'm not sure if I should do that. @gfgtdf any thoughts?

**Comment by gfgtdf** [comment]
we could proabably replace that `!events::commands_disabled` with a !events::commands_disabled || (is_replay() && events::commands_disabled <= 1).

the reason for that `!events::commands_disabled` is that we don't want people to save during an action si the 'execution state' of that action woudl not be saved, for exampl if you coudl save the game after the firt hit of an attack, the attack would be aborted when that savegame is loaded or when you save during an umc actionwml animation that temporarily removes a unit to animate it, that unit would be lost when that file is loaded.

What woudl be even better is, if we could make the 'save' button always available but make the engine delay the actual saving unit th current action/wml etc is finished, This woudl alos make it a lot easier to save during the ais turn.

**Comment by CelticMinstrel** [comment]
Agreed on making the save action always available but delaying it to the next safe point.

**Comment by gfgtdf** [comment]
i committed `!events::commands_disabled || (is_replay() && events::commands_disabled <= 1).` for now @mattsc please test whether it works now.

**Comment by mattsc** [comment]
Confirmed, works for me now.  Thanks.

**Comment by CelticMinstrel** [comment]
...wait, `commands_disabled` isn't a boolean? o.O
