### ISSUE TITLE
Item rendering is buggy

### ISSUE THREAD

**Issue by matsjoyce** [wesnoth/wesnoth#2187]
- Wesnoth version: 1.13.10-retag-239-g21395a7925
 - Build env:
    - G++ 7.2.0
    - CMake 3.9.4
    - SDL 2.0.7
 - OS: Arch Linux 4.12.13

When a halo is placed such as 
```
[item]
    x,y=12,6
    halo=halo/fire-aura.png
[/item]
```
The item seems to be initially placed twice:
![image](https://user-images.githubusercontent.com/6631310/32612156-7622f22a-c55f-11e7-8736-9d1dadeff21c.png)
As can be seen when you mouse over it:
![image](https://user-images.githubusercontent.com/6631310/32612188-8cc697a2-c55f-11e7-87d3-52555c5ef109.png)

When using it to animate:
```
    [event]
        name=moveto
        {GENERIC_UNIT 1 "Elvish Shyde" 4 4}
        {VARIABLE i 0}
        [while]
            [variable]
                name=i
                less_than=100
            [/variable]
            [do]
                [remove_item]
                    x,y=4,4
                    image="halo/fire-aura.png~O($i|%)"
                [/remove_item]
                {VARIABLE_OP i add 2}
                [item]
                    halo="halo/fire-aura.png~O($i|%)"
                    x,y=4,4
                [/item]
#                 [redraw][/redraw]
                [delay]
                    time=100
                [/delay]
            [/do]
        [/while]
        {CLEAR_VARIABLE i}
    [/event]
```
It leads to either artifacts:
![a2](https://user-images.githubusercontent.com/6631310/32612812-1f1713ec-c561-11e7-9f3b-55e3dd1a0e35.gif)

Or flashing when redraw is used:
![b](https://user-images.githubusercontent.com/6631310/32612941-74f323c8-c561-11e7-8a08-e62b9fb25c21.gif)

**Comment by Vultraz** [comment]
I can't repro the double-place, but I do see artifacts when mousing over the layer of alpha-adjusted `[item]`s.

**Comment by jyrkive** [comment]
Fixed.

As a hint, I recommend adding `redraw=no` to `[item]` at least in the animation case. `[item]` implicitly redraws the entire screen, which has a big performance impact in animations.

**Comment by matsjoyce** [comment]
Thanks, works great now.
