### ISSUE TITLE
mp mod selection broken

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2194]
the mod selection menu in the mp create game dialog is just borken: The mods that are checked on the mod menubutton don't match the mos that are active in the game. The mods that are shown in the options menu doesn't match the ones that are activated in the that menu. The mods that are shown in the options menu doesn't match the ones that are active in game.  It even happened to be that a mod was activated 'twice' (and yes, this did copy all event of my modification twice in the actual scenario, and i don't have 2 mods with the same name)

![grafik](https://user-images.githubusercontent.com/4893136/32780447-83bbe2d0-c941-11e7-8f7a-650d361299b5.png)

**Comment by gfgtdf** [comment]
ok seems liek this happend becasue the time i opened wesnoth before i tested this i had 2 modificatiosn with the same id but difffent names installed, and the value was still saved 'twice' in the preferences file when i tested this one.

**Comment by Vultraz** [comment]
Does 138faa9 fix this, then?

**Comment by gfgtdf** [comment]
It shoud, didn't test it yet though.

**Comment by gfgtdf** [comment]
removign blocker since it likeley ons breaks things if a borken addon is installed.

**Comment by gfgtdf** [comment]
hmm yes unable to reproduce assuming to be fixed
