### ISSUE TITLE
"Delay Shroud Updates" should apply to recalls

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#2196]
Hi,

Recalling a unit unveils the shroud, and hence is not undoable, even while "Delay Shroud Updates" is enabled.

To reproduce, enable "Delay Shroud Updates" and recall any dwarf onto (8,16) at the very start of HttT Hasty Alliance.  The recall will unveil (4,13) and be non-undoable.  I expect the recall not to unveil any hexes and to be undoable, until "Update Shroud Now" is invoked.

**Comment by jostephd** [comment]
I've tried to implement this by making place_recruit return early if team::auto_shroud_updates() is false, but then I ran into the undo list handling: actions::undo::recall_action unconditionally clears the shroud.  I'm not sure how to proceed.

**Comment by AI0867** [comment]
This appears to be due to the initiative special, and its associated events. It triggers on all prerecruit and prerecall events, breaking undo for recall and traitless recruit.

**Comment by jostephd** [comment]
@AI0867 Thanks but I can still reproduce the original problem with current master (b4c08f462c0f8a373fa67aac3bd5f7629ae72cd3).  Could you double check please?

**Comment by AI0867** [comment]
After my fix, recalls did appear to honor "delay shroud updates" in the tests I did in Hasty Alliance.

**Comment by jostephd** [comment]
With current master, if I start HttT anew, :create a dwarvish unit, :change_level to Hasty Alliance, enable Delay Shroud Updates and recall the unit onto (8,16), then shroud is removed from some hexes and the recall is not undoable.  So it seems it's fixed for you but not for me..?
