### ISSUE TITLE
dead condition

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2198]
found by cppcheck.
````
[src/scripting/lua_fileops.cpp:95] -> [src/scripting/lua_fileops.cpp:99]: (warning) Identical condition 'pos==std::string::npos', second condition is always false
````

This code is from src/scripting/lua_fileops.cpp:99
````cpp
	//resolve /../
	while(true) {
		size_t pos = filename.find("/..");
		if(pos == std::string::npos) {
			break;
		}
		size_t pos2 = filename.find_last_of('/', pos - 1);
		if(pos == std::string::npos || pos2 >= pos) {
			return false;
		}
		filename = filename.replace(pos2, pos- pos2 + 3, "");
	}
````

if the first ````(pos == std::string::npos)```` is true, then we break and the second one will never fire. Maybe this is a typo and supposed to be ````pos2 == std::string::npo```` in the second if condition?

**Comment by gfgtdf** [comment]
hmm yes it shodul likeley be `pos2 == std::string::npos` although it likeley won't change the code in parctice since `pos2 < pos` imples `pos2 != std::string::npos` if std::string::npos is defined as the biggest possible size_t value.

**Comment by GregoryLundberg** [comment]
Gotta love it when mistakes cancel out.

As written, pos==npos is always false. But pos2>=pos will only be true when pos2==npos

Correcting to pos2==npos means both terms are the same. (pos2==npos)==(pos2>=pos).

I would correct line 99 to simply `if (pos2 == std::string::npos) { // else assert(pos2<pos)`

**Comment by gfgtdf** [comment]
> Gotta love it when mistakes cancel out.

Then you might also like LoW mp campaign on 1.12

> I would correct line 99 to simply if (pos2 == std::string::npos) { // else assert(pos2<pos)

`pos2 != std::string::npos` doesn't  imply `pos2<pos` so this won't work .., anyway i fixes this in https://github.com/wesnoth/wesnoth/commit/320255868d4eb6fe583cd2afcfedd136a97ad3e6, wonder why it oesnt close this one.

**Comment by Vultraz** [comment]
Fixed in 320255868d4e.

**Comment by GregoryLundberg** [comment]
pos2 is in [0 .. pos-1, npos] due to line 98

**Comment by gfgtdf** [comment]
hmm yes but only if you assume that string::find_last_of does what the c++ ducmentation says it does...  i think that code was just written extra defensiveley for the case that the c++ documentation was interpreted incorrecty.
