### ISSUE TITLE
"Show Enemy Moves" highlights hexes that are only reachable through shroud

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#2199]
Suppose that shroud is on and that some enemy unit can move from its current position A, through some shrouded hexes, to another hex B that's not shrouded.  If you mouseover the enemy unit, hex B is highlighted, which leaks information about what lies under the shroud.  I would expect B not to be highlighted since the player doesn't know the enemy unit can reach it.  (This also happens with the "Show Enemy Moves" menu item.)

Example: play [this MP map (test-shroud-crossing.txt)](https://github.com/wesnoth/wesnoth/files/1472844/test-shroud-crossing.txt) with fog and shroud enabled, as team 1, set your leader to a Dwarvish Steelclad.  (It doesn't matter what faction team 2 uses.)  When you mouseover the enemy leader, hexes (14,9) through (14,11) will be highlighted, even though the player doesn't know that the enemy leader can reach them.

1.12.6 & 1.13.10+dev (138faa9464-Clean)

**Comment by AI0867** [comment]
Without looking at the code, I suspect that the game treats shroud as having a movement cost of 1, so it will be used in pathfinding.

Unless the path-through-shroud actually leaks information about the underlying terrain (if say, a shrouded impassable mountain doesn't actually show up as a possible move), this is probably working as intended.

**Comment by GregoryLundberg** [comment]
I always assumed it was intended.

But I assumed it simply leaks the condition "Yes, you can get there  from here!"

Which may or may not tell me which unit can get there and usually does not tell me the path to take; so I smile and move on.

**Comment by jostephd** [comment]
@AI0867 yes, it leaks information.  If you take the map I posted and extend the impassable mountains further south, (14,11) won't be highlighted as reachable.

@GregoryLundberg Since this happens when mouseover'ing an enemy unit, "which (enemy) unit can get there" is obvious.

**Comment by jostephd** [comment]
Something like this?  https://github.com/jostephd/wesnoth/commit/7f59e2bfc2e231f173d82e96e75ba251dd4e5ca7

**Comment by AI0867** [comment]
I think that could fix it, by displaying shroud as impassable. The question is whether we want to treat it as impassable or as minimal-cost.
