### ISSUE TITLE
addon screen shading broken sometimes when hovering addon

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2202]
addons -> connect 
game resolution was   1307x861
when hovering an addon, the screen went crazy, see screenshot
![bug](https://user-images.githubusercontent.com/476013/32867673-cf318b2e-ca6e-11e7-8b2b-128cd7b5f4c9.png)

**Comment by Vultraz** [comment]
Known for awhile, has to do with the fact that there's a scrollbar. No idea how to fix.

**Comment by Wedge009** [comment]
Pretty sure this is the same as #1583.

**Comment by matthiaskrgr** [comment]
Hmm, it is possible to trigger this weird behaviour in a couple of places. So all of these boil down to the same bug essentially?

**Comment by Vultraz** [comment]
Yes

**Comment by Vultraz** [comment]
I *think* this is fixed on accelerated_rendering, but that doesn't exactly help us right now :P

**Comment by jyrkive** [comment]
Fixed in commit 01a81c2c6dfa67f0e34c3f78b994fc5e114dd7f5.
