### ISSUE TITLE
wesnoth.exe doesn't have proper icon

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#2204]
When I build master on Win 7 x64, the .exe no longer has a proper icon (swords and shield). Instead it has the windows default icon for apps. It is possible this could affect future windows releases.

This started somewhere between: https://github.com/wesnoth/wesnoth/commit/608de6a42df8ead850248e35f4b3990489d04523
and
https://github.com/wesnoth/wesnoth/commit/f759e4ecd10cfbf2d4077e69ed4811bf2c7c3c79

It might be the SConscript changes. Any ideas @jyrkive @Pentarctagon ?

**Comment by Vultraz** [comment]
Three commits touched the SConsscript config between those two commits:
* 52f84df4b5593e7edf2223f52da6e5fe158bfaa0
* fd00a4be81be0d0525b6784f30489d3c06f686a5
* 3b81f06953265b993bdb16c0e47e70614757c94a

**Comment by GregoryLundberg** [comment]
My vote would be for 5287df .. "wesnoth_res" from the environment sounds like a reference to the resources (.res) which is where the icon is set (along with the Properties stuff like name, version, copyright, etc.

**Comment by jyrkive** [comment]
Are you compiling with SCons on Windows?

**Comment by Pentarctagon** [comment]
If removing `wesnoth_res` is what caused this, I'd be really curious what populates that value.  There's nothing that refers to `wesnoth_res` in the entire git repo after removing that line, or even anything that matches just "_res" is Sconstruct or src/SConscript.

**Comment by Pentarctagon** [comment]
Looks like it's from [here](https://github.com/wesnoth/wesnoth/blob/master/packaging/windows/SConscript#L11-L16).

**Comment by Wedge009** [comment]
Might it be SCons-specific? I use MSVC and I can't reproduce this at f7f2da45, although I only did an incremental rebuild. There was an issue quite some time ago when repeated start and exits of the same build would intermittently show or not show the Wesnoth icon but I'm guessing that's something else entirely.

**Comment by loonycyborg** [comment]
wesnoth_res is added by packaging/windows/SConscript
