### ISSUE TITLE
cannot rejoin game that has 'registerd users only'

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2206]
as the tilte said i cannot rejoin game that has 'registerd user only' if i am not a registered user even if i'm the original host of this game.  While this is somehat expected i still think you should always be able to enter a game in case that you had a disconnect. So wenshoudl eigher make it impossible to unregisted user to open 'registerd user only' games or add a an exception for the original host (i'd vote for the first).

**Comment by gfgtdf** [comment]
assgning to vultraz who merged #666

**Comment by sevu** [comment]
666 - that's a problematic number, no surprise...
