### ISSUE TITLE
leader crown not shown in attack dialogue for leader sprites smaller than 72x72

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2225]
I do have this message in stderr
```
20171121 13:26:29 error config: Failed to apply a modification to an image:
Image: elementals/water-ice-hardshell.png.
Modifications: ~RC(magenta>red)~BLIT(misc/leader-crown.png)~SCALE_INTO_SHARP(144,144).
Error: ~BLIT(): offset and width '72' larger than destination image's width '70' no blitting performed.
```
This only affects the attack dialogue, works fine on the map. The sprite is 70x70.

Current version: b1c9cb4 (1.13.10+dev)

**Comment by CelticMinstrel** [comment]
It seems silly that blitting onto a too-small canvas is an error when we could easily just a) expand the canvas to match the size of the blitted image or b) clip the blitted image to fit in the canvas.

(Personally I think b makes more sense.)

**Comment by Vultraz** [comment]
You'd think this would be a simple issue to solve, but it isn't...

Though I do suggest you resize your sprite to 72x72 :P
