### ISSUE TITLE
`wesnoth.clear_shroud` doesn't seem to exist

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2226]
Cannot invoke this method from wesnoth-1.13.10: https://wiki.wesnoth.org/LuaWML:Sides#wesnoth.clear_shroud

It seems not to exist at all (no auto-completion for it, on such field inside `wesnoth`).

**Comment by GregoryLundberg** [comment]
try wesnoth.remove_shoud
for an example see ~wesnoth/data/lua/wml/modify_side.lua around lines 62-67

Leaving this open because the wiki appears wrong

**Comment by Vultraz** [comment]
indeed, the action is `wesnoth.remove_shroud`. I've updated the wiki.

**Comment by vgaming** [comment]
Needs to be fixed on LuaWML page, too (done):
https://wiki.wesnoth.org/index.php?title=LuaWML&diff=59022&oldid=58997

**Comment by Vultraz** [comment]
Ah thanks.
