### ISSUE TITLE
is `wesnoth.remove_fog` working?

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2227]
I invoke this lua code on wesnoth-1.13.10: `wesnoth.remove_fog(1,{})`  but it doesn't seem to change fog of war for side 1 at all. Any hints on how to invoke the method so it'll change the fog?

**Comment by GregoryLundberg** [comment]
Take a look in data/lua/wml-tags.lua around line 906 to 926. Or use the wml_actions.

ISTM you need to force a re-paint to force the shroud/fog changes to the screen. It's been a while.

**Comment by vgaming** [comment]
@GregoryLundberg , I tried all kind of inputs already, I don't understand how it's supposed to work. This doesn't work:

```
wesnoth.remove_fog(1, {})
wesnoth.remove_fog(1, {x=10, y=10})
wesnoth.remove_fog(1, "10,10")
wesnoth.remove_fog(1, {"10,10"})
wesnoth.remove_fog(1, {terrain = Qxua^Xo})
wesnoth.remove_fog(1, {10,10})
wesnoth.remove_fog(1, {"filter_location", {}})
etc etc etc
```

Can you please help and give an example of what works?

**Comment by GregoryLundberg** [comment]
Off the top of my head, I'd try `{filter_location = {x=10, y=10}}` to lift the fog at (10,10)

**Comment by Vultraz** [comment]
Need improvement, this does...

**Comment by vgaming** [comment]
@GregoryLundberg  This doesn't seem to work:
```lua
wesnoth.remove_fog(1, {filter_location = {x=10, y=10}})
wesnoth.redraw{side=1}
wesnoth.redraw{}
wesnoth.fire("redraw")
```

**Comment by GregoryLundberg** [comment]
Ah. Parameter 1 is a side object, not a side number

`wml_actions.lift_fog` is the implementation of `[lift_fog]`. It uses `wesnoth.remove_fog` internally. For parameter 1, side 1, it uses `sides[1].side`. It sets sides using `wesnoth.get_sides`

Please refer to `~wesnoth/data/lua/wml-tags.lua` lines 906 through 927

**Comment by vgaming** [comment]
@GregoryLundberg but... `sides[1].side` is a number. I don't know why the code used `sides[1].side`, but it should be a number, shouldn't it?

You're writing the second time to refer to Lua source code. I know that, I've read it multiple times! But I can't get through it even though I've read it this many times, and I ask for help..

**Comment by vgaming** [comment]
From weshoth-1.13 Lua console:
```
$ wesnoth.sides[1].side
1
```

**Comment by GregoryLundberg** [comment]
OK. So the userdata has a tostring showing the side number. 
does not mean its a Lua number.

**Comment by vgaming** [comment]
@GregoryLundberg I tried `wesnoth.sides[1].side`, it didn't work, too:
```lua
wesnoth.remove_fog(wesnoth.sides[1].side, {filter_location = {x=10, y=10}})
wesnoth.fire("redraw")
wesnoth.redraw{}
wesnoth.redraw{side=1}
```

**Comment by vgaming** [comment]
* EDIT ^^^  (see above)

**Comment by GregoryLundberg** [comment]
Grrr ... PLEASE READ the wml-tags.lua section ...

local sides = wesnoth.get_sides{} -- {} is a side filter, empty is 'all sides'
wesnoth.remove_fog(sides[1].side ....

**Comment by vgaming** [comment]
(To get a side object, you need `wesnoth.sides[1]`, not `wesnoth.sides[1].side`.)

**Comment by GregoryLundberg** [comment]
/me mutters something about horses and water.

Please take a look at how Lua implements [lift_fog] and preset_fog] in ~wesnoth/data/lua/wml-tags.lua lines 906 through 927

**Comment by vgaming** [comment]
@GregoryLundberg 
```lua
$ type(wesnoth.get_sides{}[1].side)
'number'
$ wesnoth.get_sides{}[1].side
1
```

Also, I'm not lazy, I tried this, too:
```lua
sides=wesnoth.get_sides{}
wesnoth.remove_fog(sides[1], {filter_location = {x=10, y=10}})
wesnoth.fire("redraw")
wesnoth.redraw{}
```
It doesn't work, too.

**Comment by GregoryLundberg** [comment]
sides[1].side

**Comment by vgaming** [comment]
@GregoryLundberg WTF???!! I ask 5 or 6 times TO GIVE A WORKING EXAMPLE!
PLEASE!
Don't just link me to the code, please help!
Did you try your solutions? I try to reproduce them, and none work. The fact that they do not work may be an indication of something broken inside wesnoth development version, not that I'm stupid and should be sent away.

**Comment by GregoryLundberg** [comment]
I'm sorry. I'm not having a good morning between this issue and the 5yo ... the WML tags work so the Lua source for them obviously does. Do what the Lua source does.

**Comment by vgaming** [comment]
@GregoryLundberg 
> `sides[1].side`
doesn't work either. Tried just now. Also, it's type is "number" and it's value is printed as `1`.

**Comment by GregoryLundberg** [comment]
OK. your code
`wesnoth.remove_fog(sides[1], {filter_location = {x=10, y=10}})`
should read
`wesnoth.remove_fog(sides[1].side, {filter_location = {x=10, y=10}})`

**Comment by vgaming** [comment]
@GregoryLundberg I'm trying, and I need help. Also, I have no strong belief that those WML tags work, because they simply might be broken in the dev version.

**Comment by GregoryLundberg** [comment]
So try giving a full filter_side to the wesnoth.get_sides.

**Comment by vgaming** [comment]
> `wesnoth.remove_fog(sides[1].side, {filter_location = {x=10, y=10}})`

Yes, I understood that. I tried it and it didn't work.

**Comment by GregoryLundberg** [comment]
DM HttT and TSG all use [lift_fog] and if were broken there's be a fix lickety-quick because the other dev's would be screaming bloody hell about it breaking mainline. I do most of my testing in HttT and I'd be tapping my foot until it was fixed.

**Comment by GregoryLundberg** [comment]
OK, I'm not reading the code either:
```
local sides = wesnoth.get_sides{side=1}
local locs = wesnoth.get_locations{x=1, y=1}
wesnoth.remove_fog(sides[1].side, locs, true)
```

**Comment by GregoryLundberg** [comment]
And ISTR the need to [redraw] was removed sometime in the past year or two on the 1.13 tree

**Comment by GregoryLundberg** [comment]
We're talking about [lift_fog] and some think there may be a problem with the multi-turn option but I just tested in TSG and it certainly lifts the fog in S05 when meeting the bandit leader.

**Comment by vgaming** [comment]
@GregoryLundberg it seems that it's really working. I tried a code like this and it works: `wesnoth.remove_fog(1, {{4,16}}, true)`
Vultraz said something else might be broken though (the last parameter), this I don't know yet. Trying to figure out now..

**Comment by GregoryLundberg** [comment]
He's concerned about [list_fog] and omitting multturn=yes if you specific true or false you're not going to trigger the bug. I'm still trying to figure out is there is a problem with the `not cfg.multiturn` which he's referring to

**Comment by GregoryLundberg** [comment]
I've been code-reading the C++ source.
Parameter 1 can be a Lua number (integer) or a table of numbers (ie {1,3,5})
Parameter 2 must be a table of locations.
Parameter 3 must be a boolean.

The boolean has a lot of not-ing going on between the Lua and the C++ and I'll be doing some testing on it in a while. Code-read looks good but I'll be adding some debugging checks to ensure it's working as documented in [lift_fog]. If I find anything I'll push a fix and let you know

**Comment by vgaming** [comment]
I used this line:
`wesnoth.remove_fog(1, {{4,16}})`
and this:
`wesnoth.remove_fog(1, {{4,16}}, false)`
with the stock Lua version. In both cases, `lift_fog` behaved wrong in that it preserved fog for multiple turns. I will now try the solution @Vultraz proposed.

**Comment by GregoryLundberg** [comment]
thank you. RL is beating me up.

**Comment by GregoryLundberg** [comment]
Your two tests should be the same. Also cehck `, true)` which I was intending to do when I can clearn RL time and my servers free up

**Comment by vgaming** [comment]
@GregoryLundberg no problem.
Thanks for your help, the solution of creating locations (`wesnoth.get_locations{x=10, y=10}`) was the thing that finally saved me. I will now document it on the wiki of course.

**Comment by GregoryLundberg** [comment]
note also vultraz and I are talking about wml-tag [lift_fog] not wesnoth.remove_fog

**Comment by vgaming** [comment]
@GregoryLundberg that's funny.) Following my programming instincts, I tried to do the same (setting `true`), but I probably had some mistake and didn't got anything interesting.
Following your comment, I did a clean test now, and indeed `true` fixes the problem. So currently the rule is inverted.

**Comment by vgaming** [comment]
@GregoryLundberg wait. So `wesnoth.remove_fog` expects an inverted boolean as last parameter? Actually, looking at the code, it seems so. So the last parameter in `remove_fog` means "temporary?", but the last parameter in `clear_fog` means "permament?"...

**Comment by vgaming** [comment]
I guess I wrote _too_ many messages lately, and actually made a number of mistakes. Just write me what to do and I'll do it (if anything at all). Currently I didn't touch the wiki part that explains `permament`, but I can, if you (or anybody) confirms that `wesnoth.remove_fog` should indeed behave differently than `[clear_fog]`.

**Comment by GregoryLundberg** [comment]
Reading the C++ comments:
```
 * Keeping affect_normal_fog as false causes only the fog override to be affected.
 * Otherwise, fog lifting will be implemented similar to normal sight (cannot be
 * individually reset and ends at the end of the turn), and fog resetting will, in
 * addition to removing overrides, extend the specified teams' normal fog to all
 * hexes.
 *
 * Arg 1: (optional) Side number, or list of side numbers
 * Arg 2: List of locations; each is a two-element array or a table with x and y keys
 * Arg 3: (optional) boolean
```
The use of optional arguments explains why the last parameter is indexed from the top of the stack (-1) instead of by its parameter number (2 or 3).

At least one Lua table must be passed. This must be a table of tables of x and y values.

So:

* `wesnoth.remove_fog{{10,10},{3,15}}` should effect all sides and permanently remove fog from (10,10) and (3,15)

* `wesnoth.remove_fog({{10,10},{3,15}}, false)` should be identical to the above

* `wesnoth.remove_fog({{10,10},{3,15}}, true)` should only remove the fog until the end of the turn

* `wesnoth.remove_fog(1, {{10,10},{3,15}})` should effect only side 1 and permanently remove from from (10,10) and (3,15)

* `wesnoth.remove_fog(1, {{10,10},{3,15}}, false)` should be identical to the above

* `wesnoth.remove_fog(1, {{10,10},{3,15}}, true)` should only remove the fog for side 1 until the end of the turn.

* `wesnoth.remove_fog({3,5,6}, {{10,10},{3,15}})` should effect only sides 3 5 and 6 and permanently remove from from (10,10) and (3,15)

* `wesnoth.remove_fog({3,5,6}, {{10,10},{3,15}}, false)` should be identical to the above

* `wesnoth.remove_fog({3,5,6}, {{10,10},{3,15}}, true)` should only remove the fog for sides 3 5 and 6 until the end of the turn.

This code is extremely fragile. Any other form may result in undefined behavior.

* wesnoth.lift_fog takes a single parameter, a Lua table created from the contents of the [lift_fog] WML tag.

* The [lift_fog] WML tag **should** have only side-filter and location-filter attributes and tags, and **may** also have a `multiturn` boolean (true/false or yes/no) attribute.

* `multiturn=true` is the same as specifying `false` as the last parameter to `wesnoth.remove_fog`; the fog should permanently lift

* `multiturn=false` is the same as specifying `true` as the last parameter to `wesnoth.remove_fog`; the fog should lift until the end of the turn

* omitting `multiturn` is the same as specifying `multiturn=false`

The behavior described in the Wiki for [lift_fog] appears correct. So my only real note is that the C++ code is very fragile.

**Comment by vgaming** [comment]
@GregoryLundberg well, there are 2 questions regarding this:

1. should we fix the multiturn/multiturn mismatch until it's too late? I think this is very surprising to see such mismatch for addon developers.
2. Currently, wesnoth wiki describes the last parameter of `remove_fog` as "permanent". This currently mismatches the real logic. Since the wiki says as it is now, I think this is our chance to fix things.

What do you think about it?

**Comment by GregoryLundberg** [comment]
I don't care what it's called. I do like 'permanent' better, but whatever.

I don't see any issue with the remove_fog description at https://wiki.wesnoth.org/LuaWML/Tiles#wesnoth.remove_fog

And I don't see anything wrong with the lift_fog description at https://wiki.wesnoth.org/DirectActionsWML#.5Blift_fog.5D
