### ISSUE TITLE
addons manager gui stack slightly buggy/confusing

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2243]
wesnoth Battle for Wesnoth v1.13.10+dev 537f530

add-ons -> connect
select addon
click button "addon details" (lower left corner)
click "+" icon  (install addon)
=> game will return to addon list and download addon
==> the button in lower left corner still says "back to list" but clicking it goes back to the fullscreen-view of the addon details. Clicking it again will reset it properly to "back to list"

Maybe we are supposed to return to addon details automatically after downloading the addon?

**Comment by GregoryLundberg** [comment]
Linking to #2203 

Sounds like something which would get fixed in the normal course of working on #2203

**Comment by Vultraz** [comment]
No, it's an issue already reported in #2023 that I haven't gotten around to. Nothing to do with #2203.

**Comment by GregoryLundberg** [comment]
OK. So closing as duplicate
