### ISSUE TITLE
Username field in multiplayer dialog doesn't except all alphanum characters

### ISSUE THREAD

**Issue by kallaballa** [wesnoth/wesnoth#2245]
The username field doesn't accept a lot of characters. e.g the character 't' or 'e'.
My System is OpenSuse 42.3 with Awesome WM.

![screen](https://user-images.githubusercontent.com/287266/33242337-7a18cee6-d2d3-11e7-8f7e-9ddc85709727.jpg)

**Comment by GregoryLundberg** [comment]
Also in the Connect To Server dialog

**Comment by Pentarctagon** [comment]
Confirmed as happening on latest master on Mint 18.2.  The login name will auto-fill with those characters if they are in your username, but 't' or 'e' do not appear in the textbox when typed.

**Comment by Vultraz** [comment]
Found cause (8bf95ce69a9bd59d98d14653cc727368d23f75c0) and I'll fix soon.
