### ISSUE TITLE
Unexpected behavior of `wesnoth.unit_types["Mage"].attacks[0]`

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2254]
Type this in Lua console:
```lua
attacks = wesnoth.unit_types["Mage"].attacks
attacks[0].name
```

Expected: error, because `attacks[0]` should resolve to `nil`, and `nil.name` is not possible.

Actually: wesnoth prints "Mage".

UPD: `attacks[0].advances_to` prints `{"White Mage", "Red Mage"}`, which is a clear sign that `attacks[0]` is the mage type itself somehow.

**Comment by vgaming** [comment]
Might be related to https://github.com/wesnoth/wesnoth/issues/2253  (and might not)

**Comment by jyrkive** [comment]
This is kind of intentional...

https://github.com/wesnoth/wesnoth/blob/master/src/scripting/lua_unit_attacks.cpp#L45-L46

**Comment by vgaming** [comment]
@jyrkive maybe it made some sense before, but doesn't now? Why would this be needed?
Theoretically, some AI parts could maybe use that at some point? But it's doubtful it's still used now. And shouldn't anyway, don't you think?

Anyway, if you're sure it's a good choice, you can close the issue..

**Comment by AI0867** [comment]
It was originally introduced here: https://github.com/wesnoth/wesnoth/commit/43c10ec0ccc88c6deeed85c96646a9c0782502df

**Comment by jyrkive** [comment]
@vgaming The implementation of the indexing operator **itself** uses it.

Closing the issue. I consider that this isn't a bug, it's an undocumented feature.

**Comment by vgaming** [comment]
A bit of a leaky abstraction/implementation, but OK, I don't mind too much.
Thanks for the explanations.
