### ISSUE TITLE
Lua API: make `wesnoth.unit_types[].__cfg.advances_to` always exist

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2262]
Currently, it is possible to create units which have the `advances_to` field be `nil`.
Would it make sense to make this field always present (even if `""`) ?

Feel free to close the issue if it's considered OK as is (I'm not 100% sure).

**Comment by GregoryLundberg** [comment]
If you're talking about Lua only, is there some reason to switch one false-y value for another? Simply guard with an `if`.

```
if advances_to then -- any advances at all
  -- do things with advances_to[n]
end
```

Or does the lack of a value propagate to the C++/WML side and cause problems? If so, it may be more appropriate to swat down those bugs.

**Comment by vgaming** [comment]
@GregoryLundberg I'm indeed talking about Lua API only. I just thought uniformity would be good here. If not, feel free to close the issue. No problems were encountered outside of just the nil field.

**Comment by AI0867** [comment]
I believe `__cfg` is intended to directly represent the WML. `nil` would represent the absence of a setting, which may in some cases is semantically different from an empty value or the like.

**Comment by gfgtdf** [comment]
If no advancemets exist it should return an empty array, is this really not the case?

**Comment by gfgtdf** [comment]
Edit: i am not talking about unit.__cfg.advances_to

**Comment by AI0867** [comment]
`wesnoth.unit_types[].__cfg` represents a `[unit_type]` tag. It still represents WML doesn't it?

**Comment by vgaming** [comment]
@gfgtdf currently, there is `wesnoth.unit_types[name].advances_to` which is nice&correct (always exists, never has `"null"`/`nil` entries).
It's a pity though that `__cfg.advances_to` can not exist at all. Maybe it's OK if we just recommend to always use the new version.

**Comment by gfgtdf** [comment]
As ai said, _cfg represents just the wml table that was used to construct the unit. I personally see little use in adding code to modify  the __cfg field

**Comment by vgaming** [comment]
OK guys, I feel that I was wrong raising this issue. Closing.

**Comment by vgaming** [comment]
Thanks for the explanations (I wasn't sure what exactly `__cfg` means).

**Comment by CelticMinstrel** [comment]
I just want to point out that an empty table is a truthy value in Lua; it seemed like Gregory's comment suggested that it's not.

**Comment by gfgtdf** [comment]
'Lua api' seens tthe obvious label for it, in particular since the title of the report begins with that word.

**Comment by vgaming** [comment]
@CelticMinstrel well, that particular field is a _string_, not array. And currently, it can be set to: `nil`, `""`, `"null"` and any other arbitrary thing, it seems. I thought that `nil` is a bit too much, at least could be made a `""`. But it seems that we just don't touch that part. And very luckily, a `wesnoth.unit_types[].advances_to` exists which fixes the problems above.

**Comment by gfgtdf** [comment]
when accessing the filed you can also easily work around this just write `cfg.advances_to or ""`

**Comment by CelticMinstrel** [comment]
Yeah, `__cfg` is just unparsed WML of the unit, so you should probably only use it when there's no alternative.
