### ISSUE TITLE
Removing an event causes assertion failure

### ISSUE THREAD

**Issue by beetlenaut** [wesnoth/wesnoth#2265]
Using [remove_event] seems to work at first, but when you end the turn, the game closes.
```
wesnoth: /home/dan/wesnoth/wesnoth/src/game_events/manager.cpp:148: game_events::handler_ptr game_events::lock_ptr(const handler_list&, std::list<std::weak_ptr<game_events::event_handler> >::iterator): Assertion `false && "Found null handler in handler list!"' failed.                                                                                                                                  
Aborted (core dumped)   
```

**Comment by GregoryLundberg** [comment]
Current master src/game_events/manager.cpp line 148 is in the midst of a comment block below the function lock_ptr(). The function lock_ptr() has no such assertion.

Can you retest against current master and provide steps to reproduce if the problem recurs.

**Comment by Vultraz** [comment]
I removed this assertion already. Please update your clone.

**Comment by beetlenaut** [comment]
Okay, it is fixed. I didn't realize I hadn't updated it in a couple days.
