### ISSUE TITLE
Cutscene themes should not show map borders

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2272]
Need to add a `show_border` key to `[them]` in some form.

**Comment by CelticMinstrel** [comment]
Why shouldn't they show map borders?

**Comment by Vultraz** [comment]
This is why:
![thisiswhy](https://user-images.githubusercontent.com/3558659/33793568-7b644412-dd0d-11e7-95aa-74ff906c32a5.PNG)

**Comment by CelticMinstrel** [comment]
Okay, now can you add a few more words of explanation? I'm not clear on why that image is bad.

**Comment by Vultraz** [comment]
The cutscene theme doesn’t have a bar or the regular map background, so it looks really bad to have these gray bars cutting across the screen.

**Comment by CelticMinstrel** [comment]
What do you mean by "doesn't have a bar"? If you mean the sidebar, then obviously that space shouldn't be reserved in the cutscene screen; the map border should be at the edge of the window.

**Comment by Vultraz** [comment]
Map borders are drawn at map edges and are no longer handled by the theme system. Look at this, it looks horrible.
![lookatthiscrap](https://user-images.githubusercontent.com/3558659/33799092-dfee327e-dd78-11e7-9dc2-9a130621d6e1.JPG)

**Comment by CelticMinstrel** [comment]
I feel like it'd look just fine if those black edges were filled in with the brownish border colour.

**Comment by GregoryLundberg** [comment]
It's present a number of places. But when I looked it didn't look bad because the map went to the edges.

The complaint, here, appears to be that the points where the map "is not" like the black areas above that it looks bad.
