### ISSUE TITLE
room members bug (disconnected clients remain visible)

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2287]
Steps to reproduce:
* open wesnoth-1.13.10 (168d86c9-Clean)
* enter multiplayer official server, create any game room (waiting for others to join)
* start wesnoth-1.13 separately, join the server via different nickname
* click "Observe" with the second client to observe the game/room
* close your second wesnoth client

Expected at this point: the first client says he's the only one in the room.

Actually: the first client tells the second client is still connected. This doesn't change with time (waited 5+ minutes).

**Comment by Vultraz** [comment]
I cannot reproduce this :( The first client displays removes the second client's nick from the list.

**Comment by vgaming** [comment]
@Vultraz strange, I observed 2 times before raising the issue (first time initially, and one separate to confirm it's reproducable with the exact steps).

You entered game, not just the lobby, right?

**Comment by Vultraz** [comment]
Yes. :/ What OS are you testing on?

**Comment by vgaming** [comment]
@Vultraz Linux amd64 (ArchLinux). I'll re-build the latest wesnoth master to re-test.

**Comment by Vultraz** [comment]
I’m on WIndows 10. There have actually been bugs with the user list before that I could not reproduce, but @wedge009 could.

**Comment by jyrkive** [comment]
I observed this a couple of times (on Windows 10) while testing #2153. Most of the time it didn't happen, though.

**Comment by vgaming** [comment]
@Vultraz @jyrkive damn! My mistake. I forgot an important detail. I click _observe_, not _join_ game. On my system, it only reproduces on _observe_. Please re-test..

**Comment by Wedge009** [comment]
Confirmed on Observe, _not_ Join.

Regarding the issues @Vultraz mentioned, I think that was on gui1 - I would get duplicated 'connected players' entries. With gui2 lobby, I don't have that any more, so the mystery wasn't solved, just no longer relevant.

**Comment by Vultraz** [comment]
Iiiiiiinteresting... I'll look into this.

**Comment by Vultraz** [comment]
Fixed. Thanks for finding this!

**Comment by Wedge009** [comment]
Looks good to me. Thanks.

**Comment by vgaming** [comment]
Glad to help!
Really cool to see good commit messages btw.
