### ISSUE TITLE
MP client: Not possible to set multiline motd

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2288]
MP server accepts command /query motd \<message\>. That works for setting single-line message, but both 1.12 and 1.13 servers use message of multiple lines, which cannot be written in wesnoth client. That means it is not possible to change their message without scripts.

I suggest allowing \n to mark line breaks.

**Comment by CelticMinstrel** [comment]
An alternative suggestion would be allowing something like Shift+Enter to insert literal line breaks into the chat field.

**Comment by ProditorMagnus** [comment]
That would also work, though allowing literal line breaks would be much more useful in Lua console.

**Comment by CelticMinstrel** [comment]
Ooh, yes, that would be great to have.

**Comment by ProditorMagnus** [comment]
Since this works now, closing issue.
