### ISSUE TITLE
not float_label in heal-unit.lua

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#2295]
heal_unit.lua have not float label to value of heal_amount when animate=yes

**Comment by sigurdfdragon** [comment]
@CelticMinstrel https://github.com/wesnoth/wesnoth/commit/0c4b05ee2a61650c8ab0a6553ba7f06963f7996c
Was it working at that point? I checked the 1.13.8 release and this bug present there as well.

I used UtbS 06a_In_the_Tunnels_of_Trolls scenario at hex 22,26 (pool of water) where there is a healing event to test this.
