### ISSUE TITLE
[harm_unit] bug and feature request

### ISSUE THREAD

**Issue by Samonella7** [wesnoth/wesnoth#2298]
Using 1.13.10

A common thing in campaigns is for a unit's last breath event to show some last words, animate his death with [kill], and then have some more dialogue. However, if the unit was killed by a [harm_unit] with `fire_event=yes` that results in this lua error:

```
20171217 11:32:22 error scripting/lua: lua/wml/kill.lua:67: bad argument #1 to 'add' (unit not found)
stack traceback:
	[C]: in method 'add'
	lua/wml/kill.lua:67: in field 'kill'
	lua/wml/harm_unit.lua:179: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
```

Also, it seems that if the [harm_unit] has a second_unit, it does not get passed on to the kill/last breath event, which would be a good thing to add.

I attached a simple mod that should be useful to see what I mean.
[TestMod.zip](https://github.com/wesnoth/wesnoth/files/1565936/TestMod.zip)

**Comment by GregoryLundberg** [comment]
Can you provide an example causing the error you're seeing?

I think I can see the cause, as well as where to pass the second unit you're requesting, but without test cases I'm not sure what I'm doing will work.

**Comment by jostephd** [comment]
@GregoryLundberg I can reproduce the traceback using the TestMod provided by the OP.  (Enable the mod, then in any MP scenario, recruit a unit as side 2 and move a unit as side 1.)

**Comment by Samonella7** [comment]
> Can you provide an example causing the error you're seeing?
Yep, I attached a zipped mod for it. Here are the events in it:
```
[event]
	name=moveto
	first_time_only=no
	[filter]
		side=1
	[/filter]
	[harm_unit]
		[filter]
			side=2
			canrecruit=no
		[/filter]
		[filter_second]
			x,y=$x1,$y1
		[/filter_second]
		amount=100
		kill=yes
		fire_event=yes
		animate=yes
	[/harm_unit]
[/event]

[event]
	name=last breath
	first_time_only=no
	[message]
		speaker=unit
		message=_"Augh! Poignant last words!"
	[/message]
	[kill]
		x,y=$x1,$y1
		animate=yes
	[/kill]
	[message]
		speaker=second_unit
		message=_"Insulting catch-phrase!"
	[/message]
[/event]

````

**Comment by GregoryLundberg** [comment]
I saw the zip. It didn't work when I tried it as a mod. So I edited AToTB S01, copied it in by hand, and it's working. I get the Lua error and I don't get the insulting catch-phrase.
