### ISSUE TITLE
Incorrect font

### ISSUE THREAD

**Issue by michal-stankie** [wesnoth/wesnoth#2299]
Text is showing up incorrectly.

![screen shot 2017-12-17 at 4 25 08 pm](https://user-images.githubusercontent.com/32530393/34083962-dfb80586-e346-11e7-9a04-eca392d6e97d.png)

Wesnoth: Version 1.12.6 (1.12.6)
MacOS 10.13.2

EDIT: Language set to English (Or at least, I didn't change it.)

**Comment by CelticMinstrel** [comment]
Is this in English or some other language?

**Comment by GregoryLundberg** [comment]
@singalen probably wants to see this

**Comment by michal-stankie** [comment]
English.

**Comment by Vultraz** [comment]
Looks like some GUI2 font loading issue in 1.12. Do you get this with 1.13?

**Comment by michal-stankie** [comment]
I download v1.13 from the website (https://sourceforge.net/projects/wesnoth/files/wesnoth-1.12/wesnoth-1.12.6/Wesnoth_1.12.6.dmg/download), mounted the disk image, but copying the app into Applications folder doesn't work. I get an error, shown below. Plus, is it strange that the disk image is named '1.12.6'?

Am I downloading the wrong file?
![screen shot 2017-12-18 at 12 17 35 am](https://user-images.githubusercontent.com/32530393/34091044-23178af8-e389-11e7-9a66-7770824c94c1.png)

**Comment by Vultraz** [comment]
That's the download link for 1.12.6. 1.13.10b is here: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.13.10/Wesnoth_1.13.10b.dmg/download

**Comment by michal-stankie** [comment]
Strange, the link on wesnoth.org redirected me to that one. 

The font works.
![screen shot 2017-12-18 at 1 03 18 am](https://user-images.githubusercontent.com/32530393/34092072-82ae4f50-e38f-11e7-8f09-cb4fb4d0f9b8.png)

**Comment by Vultraz** [comment]
Just tested, the macOS link under the Development tab redirects to 1.13.10b as expected. You must have chosen the Stable (1.12) link.

Anyway, since this seems a 1.12 problem and there isn't going to be another 1.12 release, and it's fixed in 1.13, I'm marking Won't Fix.
