### ISSUE TITLE
SIGABRT when editing "None" scenario time schedule

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2301]
Steps:
* open wesnoth v1.13.10+dev (19c08e77-Clean)
* open map editor
* click Menu > New Scenario
* click "Time schedule" (upper-right button that looks like a sun)
* choose "Assign Time Schedule" > "None"
* clicke "Time schedule" > "Time schedule editor"

At this point, wesnoth will crash.

Additional comment: it would be good if wesnoth would have full support for the absence of a time schedule (which the "None" schedule button does). Wesnoth just shouldn't crash if there is no `[time]`.

**Comment by vgaming** [comment]
( This issue might be relevant  https://github.com/wesnoth/wesnoth/issues/2302 )

**Comment by GregoryLundberg** [comment]
```
wesnoth: /home/lundberg/wesnoth/src/gui/dialogs/editor/custom_tod.cpp:115: gui2::dialogs::custom_tod::custom_tod(const std::vector<time_of_day>&, int): Assertion `!times_.empty()' failed.
Aborted (core dumped)
```

**Comment by vgaming** [comment]
@GregoryLundberg oh right, forgot to attach the backtrace and stuff. Thanks.

**Comment by Wedge009** [comment]
It looks like the 'None' time schedule is a problem because any access to the times vector will fail, since it's now empty. This is even before getting to the schedule editor, I get this debug-mode exception (looks like it's not caught or is ignored in release-mode) just setting the 'None' schedule:

```
wesnoth.exe!tod_manager::replace_schedule(const std::vector<time_of_day,std::allocator<time_of_day> > & schedule) Line 293	C++	Symbols loaded.
wesnoth.exe!editor::map_context::replace_schedule(const std::vector<time_of_day,std::allocator<time_of_day> > & schedule) Line 303	C++	Symbols loaded.
wesnoth.exe!editor::editor_controller::execute_command(const hotkey::hotkey_command & cmd, int index, bool press) Line 662	C++	Symbols loaded.
wesnoth.exe!hotkey::execute_command(const hotkey::hotkey_command & command, hotkey::command_executor * executor, int index, bool press) Line 533	C++	Symbols loaded.
wesnoth.exe!hotkey::command_executor::show_menu(const std::vector<config,std::allocator<config> > & items_arg, int xloc, int yloc, bool __formal, display & gui) Line 386	C++	Symbols loaded.
wesnoth.exe!editor::editor_controller::show_menu(const std::vector<config,std::allocator<config> > & items_arg, int xloc, int yloc, bool context_menu, display & disp) Line 1094	C++	Symbols loaded.
wesnoth.exe!hotkey::command_executor::show_menu(const std::vector<config,std::allocator<config> > & items_arg, int xloc, int yloc, bool __formal, display & gui) Line 383	C++	Symbols loaded.
wesnoth.exe!editor::editor_controller::show_menu(const std::vector<config,std::allocator<config> > & items_arg, int xloc, int yloc, bool context_menu, display & disp) Line 1094	C++	Symbols loaded.
wesnoth.exe!controller_base::play_slice(bool is_delay_enabled) Line 249	C++	Symbols loaded.
wesnoth.exe!editor::editor_controller::main_loop() Line 174	C++	Symbols loaded.
wesnoth.exe!editor::start(const config & game_conf, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & filename, bool take_screenshot, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & screenshot_filename) Line 52	C++	Symbols loaded.
wesnoth.exe!game_launcher::start_editor(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & filename) Line 1002	C++	Symbols loaded.
wesnoth.exe!game_launcher::start_editor() Line 93	C++	Symbols loaded.
wesnoth.exe!do_gameloop(const std::vector<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > & args) Line 897	C++	Symbols loaded.
wesnoth.exe!SDL_main(int argc, char * * argv) Line 1151	C++	Symbols loaded.
wesnoth.exe!main_getcmdline(...) Line 161	C	Symbols loaded.
wesnoth.exe!WinMain(HINSTANCE__ * hInst, HINSTANCE__ * hPrev, char * szCmdLine, int sw) Line 203	C	Symbols loaded.
```

As a work-around, I wonder if the schedule editor should just be disabled for the 'None' case. Doesn't make sense to allow editing of something that doesn't exist.

**Comment by CelticMinstrel** [comment]
Yeah, I'd say it should be disabled if there's no schedule.

**Comment by vgaming** [comment]
I'm OK with that solution, too.
// It's only important (for me) to support the absense of [time], so that wesnoth won't fail or insert wrong [time] in this case.

**Comment by gfgtdf** [comment]
> It's only important (for me) to support the absense of [time], so that wesnoth won't fail or insert 

Yes I fully agree here

**Comment by Wedge009** [comment]
@jyrkive I suppose that works. There's a 'Stub Time of Day' that's created as a result, so the 'None' schedule is no longer really 'None', but I suppose it doesn't make sense to have a completely empty schedule - a scenario will always have at least one time of day. Thanks.
