### ISSUE TITLE
Recalls are not undoable after toggling planning mode

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#2303]
To reproduce:

1. Recall a unit
2. Press 'p' twice to enable and disable planning mode
3. Press 'u' to undo.

The recall does not get undone.

The map has fog and shroud disabled.

**Comment by jostephd** [comment]
Clearing the undo stack is hardcoded into the whiteboard manager:

https://github.com/wesnoth/wesnoth/blob/7be364f3b5985979a6647cda13cc2ad00b948261/src/hotkey/hotkey_handler_sp.cpp#L136-L137

https://github.com/wesnoth/wesnoth/blob/7be364f3b5985979a6647cda13cc2ad00b948261/src/whiteboard/manager.cpp#L184-L185

https://github.com/wesnoth/wesnoth/blob/7be364f3b5985979a6647cda13cc2ad00b948261/src/whiteboard/manager.hpp#L183-L185

**Comment by jostephd** [comment]
Submitted #2309.

**Comment by Wedge009** [comment]
Should have refreshed the page earlier, I was starting my own investigation when I find you've already found the cause. I was going to say that it's probably a function of the switching to and from planning mode.
