### ISSUE TITLE
[insert_tag]name=event does not create an event

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#2314]
The following code should display a message with the text "hi", but instead no message is displayed:
```
[event]
  name="start"
  
  [set_variables]
    name=test
    
    [value]
      name="turn 1"
      
      [message]
        message="hi"
      [/message]
    [/value]
  [/set_variables]
[/event]

[insert_tag]
  name=event
  variable=test
[/insert_tag]
```

**Comment by gfgtdf** [comment]
> The following code should display a message with the text "hi", but instead no message is displayed:

no thi is not how it works, insert_tag is a tag that inserts that tag when the containing tag is parsed, but [scenario] does't support varible subsutution, also even it it woudl allow variable subsutution it wouldn't create an event since the scenario parsing woudl happen before that start event is executed.

**Comment by GregoryLundberg** [comment]
Move the [insert_tag] inside the [event]name=start

Also, try naming the [value] as "myEvent" and doing a [fire_event] on it.

What I'm getting at is (1) you have to insert the tag properly and (2

**Comment by GregoryLundberg** [comment]
Sorry. my system is acting up and I didn't mean to click anything.

**Comment by gfgtdf** [comment]
i'm courious, are you just testing stuff or do you really have a usecase for such thing ?

**Comment by GregoryLundberg** [comment]
Move the [insert_tag] inside the start [event]

Works for me. 

Now I am intentionally closing this as "invalid"
