### ISSUE TITLE
Non-graceful migration procedure for `[side].share_view`

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2316]
Steps:
* open wesnoth 1.13
* open Map Editor on a map that has the following tag:
```
[side]
    share_view=yes
    ...
```
* save the map (make any changes for it to be save-able)

Now, how should wesnoth-1.13 save the map?

I think the answer is -- it should save in a format compatible to both wesnoth-1.13 and wesnoth-1.12, when possible and easy to maintain.
So I would expect the following tag to be used:
```
[side]
    share_vision="all"
    share_view=yes
```
The `share_vision` should be dominant, and `share_view` should be used as a fallback (actually, this is already the case when reading the data). If we insert both tags when writing, we can use Map Editor from 1.13 and still have limited support for opening the resulting map on 1.12.

**Comment by Vultraz** [comment]
Sorry, no. `share_vision` should overwrite it. I don't think deliberately adding fallback keys for old versions makes sense at all.

**Comment by CelticMinstrel** [comment]
It kinda does make sense actually, though there are other things about the map format that differ between 1.12 and 1.13 so I'm not sure if it would actually help that much.

**Comment by vgaming** [comment]
Will, pity it won't be handled.

But better not keep stale issues that will never be fixed. Closing.

**Comment by vgaming** [comment]
(EDIT: typo)
