### ISSUE TITLE
Map Editor does not preserve unknown properties

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2318]
Map Editor does not preserve unknown properties.
This means when working with a MapEditor on any kind of unsupported keys, those keys get erased, not left out as-is. For example:

* create a new scenario
* create a side
* in your text editor, add the properties `team_lock` and `gold_lock` to the side
* try to open this scenario in Map Editor and save it back.

You'll see that those unknown properties got erased, simply because Map Editor didn't knew about them.

What I propose is to store all unknown properties into an untyped attribute map and write it back without changes upon save.

**Comment by Wedge009** [comment]
@vgaming Is #1380 similar/related?

**Comment by vgaming** [comment]
Indeed. I think either one can be marked as duplicate. I tend to think that my version is a bit better documented, but the other has more comments. OK, let's close this one.
