### ISSUE TITLE
MP moderation not implemented

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2327]
The MP moderation functions were never implemented. So far the following action items have been identified:

 - [x] Implement /q ban as documented
 - [x] Implement /q kick as documented
 - [ ] Implement /q kickban (/q kban) as documented
 - [ ] Check the ip is not banned during login and kick the client if it is
 - [x] Expire the ban
 - [ ] Persist the bans across server crashes, cold- and warm-restarts
 - [ ] Gracefully close the client when rejected by the server for any reason

**Comment by GregoryLundberg** [comment]
Here is what I see on the wesnothd console when I "Kick + Ban" my Windows user 'lundberg55' from my Linux wesnothd for reason 'Plugh' and time 30:

```
20171226 20:48:59 info server: Admin Command: type: kbanlundberg55 30 Plugh     IP: 127.0.0.1   nick: lundberg3
20171226 20:48:59 info server: Command 'kbanlundberg55' is not recognized.
Available commands are: adminmsg <msg>, ban <mask> <time> <reason>, bans [deleted] [<ipmask>], clones, dul|deny_unregistered_login [yes|no], kick <mask> [<reason>], k[ick]ban <mask> <time> <reason>, help, games, metrics, netstats [all], [lobby]msg <message>, motd [<message>], pm|privatemsg <nickname> <message>, requests, sample, searchlog <mask>, signout, stats, status [<mask>], unban <ipmask>
Specific strings (those not inbetween <> like the command names) are case insensitive.
```

**Comment by ProditorMagnus** [comment]
Use space between kban and target.

**Comment by GregoryLundberg** [comment]
Did that. No joy.

**Comment by GregoryLundberg** [comment]
I can't seem to get the commands to work from the chat line. And the GUI is buggy, missing "Ban" and not putting a space between kban and the nick

**Comment by ProditorMagnus** [comment]
For chat line it works like /q ban Name 30s reason

**Comment by GregoryLundberg** [comment]
Ah. So the /help command is completely wrong. As is /help ban and /help kick.

**Comment by ProditorMagnus** [comment]
There is https://wiki.wesnoth.org/ServerAdministration

**Comment by GregoryLundberg** [comment]
OK. I glanced at that to remember how to authenticate as an admin but never read it in depth and rarely play network against myself. Silly me thinking that the in-game help would be updated.

**Comment by ProditorMagnus** [comment]
Additional hints to replicate:
Server password goes to passwd attribute in lan_server.cfg in same folder as preferences file.
Authentication using that password is done with /q admin password
User can be banned with /q ban Name 30s reason

**Comment by GregoryLundberg** [comment]
It appears the only place a ban is automatically lifted by program-code is in a commented-out block of code. This appears to have been from 1 to 9 years ago.

I'm still looking but I don't see anywhere that bans are persisted across server crash-restarts. A quick test indicates they are preserved (in memory) across warn-restart (SIGHUP).

The place to expire a ban is when you're looking for it .. during a login attempt. I can handle that. I don't think I'll try to do a crash-proof persistence.

**Comment by soliton-** [comment]
Bans are saved to the file set under the ban_save_file key from the server configuration.

**Comment by GregoryLundberg** [comment]
I'm closing this in favor of my PR. Too much hassle having two issues open for it.
