### ISSUE TITLE
Make the Lua state persistent 

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2328]
not my own idea, migrated form notsoeasycoding page

> Wesnoth is designed to make all data files as simple and human-readable as possible, including savefiles. WML is designed so that it is always very easy to write the entire WML state as plaintext and reload it correctly. There are many benefits of this, but especially 
> 
> 1) It makes it easy for beginners / students to read the files and see what's going on
> 2) It makes it easy for us to debug problems without needing special tools to read the savefiles
> 3) It makes it easy to edit save files to work around any possible bugs. Users have even reported opening savefiles from version 1.10 in microsoft word (!) to correct minor bugs in mp and resaving them, as a policy for tournament games.
>
>If you use lua in your scenarios, things become more complicated because we can't save the lua state at all. If you rely on lua variables to save information, then when your scenario is saved and reloaded those variables will get wiped. The wesnoth engine provides places for lua to hook into "onsave" and "onload" so that the scenario developer can write their own serialization routines, but this is just punting the problem to scenario developers.
>
>A nice solution to this would be if we properly serialized the lua state alongside the WML in a savefile. The most suitable solution is probably this library: https://github.com/fnuecke/eris
It would require significant additional work as well to find a good way to serialize the C functions that we expose to lua, and the userdata like units held by lua.
>
>More info here: http://lua-users.org/wiki/PlutoLibrary

I moved it from the notsoeasycoding page to here since it's not so obviousl why this woudl be good idea.  in particular it's unclear how making the lua state presistent would improve the siatuation of the 1,2,3 mentioned above. I don't know the details of the lua prestient state format, but i'd guess that it is not easiyl readable for user and would probably add many useless information to the savefile (in the worst case it'd probably add the whole content of the data/lua directory in each savefile)

**Comment by GregoryLundberg** [comment]
Pluto was abandoned in 2008.  TamedPluto was a Lua 5.2 implementation but all links I found to it were dead (404, etc). There is an archived version of Pluto 2.4 from 2008 available.

The Eris github fork still exists but has not been updated for 2 years. It is deeply coupled with Lua 5.2.4 so someone would need to upgrade the Lua engine, fix the merge conflicts, and understand both Eris and Lua well enough to determine what needs to be dropped and what needs to be added, when upgrading to Lua 5.3.4 (a non-trivial task).

Assuming someone did undertake the project, the result, from reading the Eris documentation, would be quite fragile. It would be a simply matter, for example, for a UMC author to create an infinite loop. And, if the need to save state occurs when we're inside C++ code, Eris does not save sufficient call-stack information to restore to the C++ code and return back to the Lua.

This certainly is __*not*__ a Good First Issue. In fact, it's probably too much even for those of us who are not afraid of diving into the guts of the Lua engine. I'd recommend closing this as a Good Idea but Probably Impossible to Implement.

**Comment by CelticMinstrel** [comment]
Personally I don't think the effort required for this is worthwhile, particularly considering how functions and data are mixed together in the Lua state. (It's extremely difficult, possibly impossible, to persist functions.)

Considering how we already offer Lua hooks into the SaveWML where addon authors can store any kind of WML data they want, I don't think this sort of persistence is needed.

**Comment by vgaming** [comment]
I think this will add too much complexity to the game, too (even though I am an addon writer).

**Comment by gfgtdf** [comment]
since we all agree that this should not be implemented i'm closing this.
