### ISSUE TITLE
Document `use_markup` widget property

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2336]
Please document this widget property?

It should probably belong somewhere here: https://wiki.wesnoth.org/GUIWidgetInstanceWML#Widget
Or maybe here (if it's Label-specific): https://wiki.wesnoth.org/GUIWidgetInstanceWML#Label

I could document that myself if I'd knew how it works (and knew how to actually document it, since that wiki part is auto-generated).

**Comment by jyrkive** [comment]
That documentation would belong here: https://github.com/wesnoth/wesnoth/blob/1c2968c632bc9ca3cf62c6d0f864d01afdcbc496/src/gui/widgets/styled_widget.cpp#L569

I see `use_markup` is indeed undocumented.

**Comment by vgaming** [comment]
closed via https://github.com/wesnoth/wesnoth/commit/d21a79b0117c7b6bbeeba73da8551132ad751753
