### ISSUE TITLE
Impossible to load a multiplayer game

### ISSUE THREAD

**Issue by singalen** [wesnoth/wesnoth#2340]
> It's impossible to load a saved multiplayer game. 
> When I press the "Load" button in multiplayer "Create game" mode, I‘m thrown back to the lobby.

Reported on iOS version: https://forums.wesnoth.org/viewtopic.php?f=67&t=47697
Confirmed by @Pentarctagon on Discord:
> [10:31] Pentarctagon: I reproduced it locally just now
> [10:32] Pentarctagon: I don't think it was previously known, though
> [10:33] Pentarctagon: IMO that would be another blocker if it was.
> [10:34] Tad Carlucci: Any console messages when you reproduce it? Or does it just silently crash back to the lobby?
> [10:34] Pentarctagon: Nothing.  It just kicks me back to the main menu.
> [10:35] Pentarctagon: like I had clicked Cancel, basically.

**Comment by ProditorMagnus** [comment]
Check if loading from main menu works.

**Comment by Pentarctagon** [comment]
Loading from the main menu works.

**Comment by Pentarctagon** [comment]
Which, to clarify - for local games it's still possible to load them from the main menu, but it is currently not possible to load a networked multiplayer game on master.  As such, I would consider this to be a blocker, though I can't add tags myself.
