### ISSUE TITLE
AI: convert E_NOT_REACHED_DESTINATION from an error to a warning

### ISSUE THREAD

**Issue by mattsc** [wesnoth/wesnoth#2344]
Migrated from the EasyCoding wiki page:

This happens, for example, when a unit runs into an ambush, which is not an error.

**Comment by Wedge009** [comment]
What other conditions constitute an error? Without knowing much about the AI, it seems sensible that this be treated as a warning than an error.

**Comment by mattsc** [comment]
Other error conditions are things like "tried to move a unit that is not on AI side" or "tried to move incapacitated (petrified) unit."  Those are clearly errors.

A different way I have come to think about this in the meantime is: when this condition happens, it could be the indication of a real problem, or it might be something "legal", just unexpected.  So I think this is exactly what warnings should be about.  So yes, I agree that it should be a warning.  I will take care of this together with the other remaining tasks of #3450 sometime over the next few weeks.

**Comment by mattsc** [comment]
Done in #4588.
