### ISSUE TITLE
AI: add Lua function ai.get_individual_attacks()

### ISSUE THREAD

**Issue by mattsc** [wesnoth/wesnoth#2348]
Migrated from the EasyCoding wiki page:

Add a Lua function ai.get_individual_attacks() that returns all the single attacks the side can do (as opposed to attack combinations).  This needs to include an option to recalculate and take the current situation on the map into account (making the function believe that the game state has changed).

**Comment by CelticMinstrel** [comment]
I thought this was satisfied by `ai.aspects.attacks`?

**Comment by mattsc** [comment]
Indeed.  With the slight correction that it is `ai.get_attacks` which provides this information, it's all there. Not sure for how long this has been hanging around on the EasyCoding page ...

In any case, closing this issue.

**Comment by CelticMinstrel** [comment]
Huh, okay. I'd assumed it was asking for something different from the full analysis of possibly attacks returned by `ai.get_attacks()`, but if I was wrong, then great?

**Comment by mattsc** [comment]
It probably did, but it's been so long that I don't remember.  I think the original request was for something like WFL's `my_attacks`, but since this information is all contained in `ai.get_attacks()` this _should_ be good.  If anybody disagrees, feel free to reopen this.
