### ISSUE TITLE
AI: add [filter_own] to all candidate actions

### ISSUE THREAD

**Issue by mattsc** [wesnoth/wesnoth#2349]
Migrated from the EasyCoding wiki page:

Set up an option the allows us to exclude units from the move-to-targets phase similar to [filter_own] for the combat phase (other than setting ai_special=guardian, which has a number of other side effects). Actually, having this option for all CA's would be nice.

**Comment by mattsc** [comment]
I've started thinking about how to do the WML syntax for this. I don't want something like the attacks aspect, as that does too many things with the same mechanics.  In fact, I think this shouldn't be an AI aspect at all.  Instead, how about having a (non-aspect) tag like this
```
[ai]
    [filter_ca]
        ca_id=move_to_targets
        # Insert SUF content here
    [/filter_ca]
[/ai]
```
This would be implemented similar to `[ai][goal]`, specifically also in that there can be several (one for each default AI candidate action).

**Comment by CelticMinstrel** [comment]
Another possibility would be accepting filters in the `[candidate_action]` tag. (Actually, this is already supported in FormulaAI CAs, right? And for a Lua CA you can probably somehow manage it in the evaluation function...) More specifically, in `[candidate_action]engine=cpp`, I guess?

**Comment by mattsc** [comment]
I thought of adding it to the `[candidate_action]` tag also. The "problem" (more an inconvenience, really) is that you then have to change the AI setup itself, rather than adding an instruction to it.  I'm not sure whether that's a real argument against it though.

**Comment by mattsc** [comment]
I just added PR #4581 as a first step toward resolving this issue.  I decided to go with @CelticMinstrel's suggestion for the syntax, as this has the added advantage that it is then possible to add several instances of the same default CA in order to force the order in which units are moved (or one could even change the behavior for different units by changing aspects or goals in between the two instances).

The syntax with the `[filter_own`] tag looks like this:
```
	[candidate_action]
		id=move_to_targets
		engine=cpp
		name=ai_default_rca::move_to_targets_phase
		max_score=20000
		score=20000
		[filter_own]
			type=Orcish Grunt
		[/filter_own]
	[/candidate_action]
```

**Comment by mattsc** [comment]
Some more thoughts on syntax:  There is also a Lua CA in the default AI (there are more in mainline, but only one is currently part of the default AI).  There is already a mechanism for passing arguments to Lua CAs, via `[candidate_action][args]`, but I strongly believe that we should have the same syntax for C++ and Lua CAs.  Among other things, there is really no need for the non-AI-expert content creator to even know how a CA is implemented.

So there are two possibilities:
1. Also add '[candidate_action][filter_own]` as an allowed tag for Lua CAs.
2. Change the syntax for C++ from that shown above to '[candidate_action][args][filter_own]`

I'd be in favor of the latter, given that it builds on existing syntax, and that it is easily expandable if we ever want to allow other arguments to be passed in the future.

Comments?  Objections?

**Comment by CelticMinstrel** [comment]
From my point of view, `[args]` is unspecified, unformatted data passed verbatim to the Lua engine. It doesn't make sense to me to use it for a non-Lua engine or for data that is not dependent on the engine being used, and adding known structure to it goes against its use as unspecified data (this is similar to my objection to gfgtdf's idea for an `[effect]apply_to=variable`).

**Comment by mattsc** [comment]
Okay, that's fine.  I'll go with Option 1. then.  Since I managed to figure out how to do it for the C++ engine, it can't be that much harder for a Lua CA.  😉

**Comment by CelticMinstrel** [comment]
It would probably need to be part of the whole system of how a Lua CA is called, I guess? Or, maybe it could be something in the `ai` table, not sure if that would work…

**Comment by mattsc** [comment]
@CelticMinstrel I went with the former approach from your last message.  This adds another parameter to the call to eval/exec functions.  I tested that I can read the `[filter_own]` tag in the Lua CA, but have not made any changes yet to the CA itself.  I want to see what objections people have to this first.  ;-P  Let me know if you have comments.

**Comment by mattsc** [comment]
Taken care of in #4581
