### ISSUE TITLE
 Northern Rebirth/Infested Caves: primary scenario end event won't trigger

### ISSUE THREAD

**Issue by singalen** [wesnoth/wesnoth#2352]
Victory condition of talking to Hamel w/ Tallin doesn't trigger.
See attachments: https://github.com/singalen/wesnoth/issues/79

@GregoryLundberg: 
> @singalen Open master issue. Label: Bug, Confirmed, WML and Assign to Zookeeper. The issue is that ONLY your leader can explore and discover the  Drawven leader. If any other of your units discovers him, the sighted  event never re-fires when your leader eventually comes into range.

**Comment by GregoryLundberg** [comment]
The issue is that the sighted even fires only once. If you're exploring with your leader, you're fine. Otherwise it will never re-fire when the leader comes into range.
