### ISSUE TITLE
Crash on empty campaignd

### ISSUE THREAD

**Issue by GregoryLundberg** [wesnoth/wesnoth#2355]
First test before adding content.

After entering localhost as the server I get an on-screen message that there is no content, as expected.

When I click to dismiss that message, the game crashes to desktop with the following message:
```
wesnoth: /home/lundberg/wesnoth/src/gui/widgets/window.cpp:513: int gui2::window::show(bool, unsigned int): Assertion `status_ == NEW' failed.
```

**Comment by jyrkive** [comment]
Likely a regression from commit e0abb211760f41bde6f1806c5de25989b968dea8.

**Comment by GregoryLundberg** [comment]
I removed the assert() and don't see any problems. I was going to see "any issues" but that's wrong because the UI should disable the `Addon Details` button if there is not an addon selected; instead is shows some funky, default, non-existent addon's details.

I'll retry with the assert() and without that commit to see if that us the "cause".
