### ISSUE TITLE
Split add-ons into logically independent "Eras", "Modifications", "Scenarios" etc

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2359]
This is a re-design proposal on how Eras, Modifications, Scenarios, etc, are defined in wesnoth.

Currently, wesnoth loads all addons it has when starting a game. This leads to easy mistakes in add-on code that will cause OOS.

If, however, add-ons were defined strictly and were divisible, the host-s client could only load the add-ons it really needs for that particular game, avoiding thes kind of OOS altogether.

----
As a temp work-around, could wesnoth remember which directory all Eras / Scenarios / Mods came from? If wesnoth does it, it would have ways of detecting that a particular add-on is not in use for a particular game (e.g. if it only defines an Era that is not in use).

----
Solving this problem might also help in another aspect of the game: start-up times. If wesnoth (hypothetically) knew what's inside an add-on, it could not load e.g. an Era until you really need it in a particular game. This could help with e.g. Ageless Era, which takes considerable amount of time to load, yet should not be needed in other Era games.

**Comment by vgaming** [comment]
As a temp work-around, could wesnoth remember which addon all Eras / Scenarios / Mods came from? If wesnoth does it, it would have ways of detecting that a particular add-on is not in use for a particular game (e.g. if it only defines an Era that is not in use).

**Comment by jyrkive** [comment]
This is also related to the long-term goal of live reloading, i.e. having Wesnoth automatically reload stuff that has changed on disk. If things are separated in the in-memory representation, then live reloading would only need to reload some of the WML rather than all of it, which would be crucial for acceptable performance.

**Comment by ProditorMagnus** [comment]
This has been considered, but I think never implemented. https://forums.wesnoth.org/viewtopic.php?p=588083#p588083

**Comment by vgaming** [comment]
@ProditorMagnus is it indeed the same issue and problem that are being addressed (on the linked forum topic)? From what I gather, the link above discusses add-on conflicts, whereas my proposal is add-on elimination (for particular games).

**Comment by stevecotton** [comment]
The goal that's marked "temp workaround" in the original message was completed in 1.15.4 - add-ons are only active if something from that add-on is in use.

I think that's as far as this one should go - using `[load_resource]` to ensure that the full era is active is actually useful, for example ProditorMagnus/Ageless-for-1-14#27. So I think this issue can be closed as done.

**Comment by knyghtmare** [comment]
>  I think this issue can be closed as done.
