### ISSUE TITLE
Auto-save shows Errors for Scenarios with newline (each turn)

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2366]
Steps to reproduce:
* create or use a filesystem that cannot save newlines (for example, create FAT partition on an USB stick)
* start wesnoth-1.13 with `--userdata-dir /path/to/your/filesystem/directory` (the dir that cannot have files with newlines). If your FS already doesn't support newlines, start wesnoth normally
* start a Scenario those name contains a newline.

What you get at this point:
```
20180112 14:32:55 error engine: Could not auto save the game. Please save the game manually.save_game_failed: failed opening file: Invalid argument: iostream error
```
![autosave-bug](https://user-images.githubusercontent.com/33452702/34873318-b09b670c-f7a5-11e7-8a61-508374815790.png)

**Comment by vgaming** [comment]
Implementation-wise, I think it makes sense to just sanitise autosave (and normal save) names to those allowed on all filesystems.

**Comment by Wedge009** [comment]
I wonder if this could be bundled with any work done for #1567.

**Comment by vgaming** [comment]
@Wedge009 Well IDK, I would generally prefer the contrary: self-contained simple changes, each fixing it's own problem.

Then again, if #1567 would clash into a conflict with a patch that fixes this problem, it'd be bad, so those issues could be _dependent_. Again, my personal opinion.

**Comment by Wedge009** [comment]
My point was that any work to filter out spaces in file names could equally apply to filtering for new-line characters. I believe these are related, but I could be wrong. Sounds like you believe they are separate issues.

**Comment by vgaming** [comment]
Ah sorry, I think I got what you mean now, @Wedge009 . You're probably right.

**Comment by vgaming** [comment]
@jyrkive thanks a lot !
