### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by GregoryLundberg** [wesnoth/wesnoth#2367]
I am checking out out a new analytical tool, Codacy. It includes cppcheck static analysis, which indicates the following three memory leaks:

> src/scripting/game_lua_kernel.cpp
> Memory leak: lua_engine
> 3509 }

> src/serialization/preprocessor.cpp
> Memory leak: buffer
> 1506 }
> Memory leak: buffer
> 1548 } else if(parent_.depth() < 40) {

I have not chased down all the places these pointers are passed, in case they're deleted elsewhere. But a local code-read confirms they appear to leak.

**Comment by Vultraz** [comment]
It's rather confusing (and probably should be changed), but the two `buffer` pointers are forwarded to the `preprocessor_data` ctor and used to initialize a `unique_ptr`. Therefor, the `preprocessor_data` objects takes ownership and deletes the ptr when necessary, meaning it's not a leak. But I agree it's definitely confusing the way the code is now >_<

**Comment by GregoryLundberg** [comment]
Yeah, it was pointed out elsewhere that it's not really a leak. It's just coded to make it look like one.

I have several thousand examples of "false positives" which would be "true positives" if the message simply read "Your code is too confusing to analyze: consider rewriting more clearly."

**Comment by AI0867** [comment]
Clarified in 65dd884b50e1 and f453f1422b37.

**Comment by AI0867** [comment]
I haven't looked at the game_lua_kernel leak, so that might still be a problem. Reopening.

**Comment by GregoryLundberg** [comment]
I appreciate you taking the time to work on this.

If you've not figured it out, the tool I'm testing is Codacy https://www.codecy.com/ which appears to be a web site which integrates a number of static analysis tools. For C++, it's using cppcheck. I'm seeing a lot of very good comments, and a lot of false positives due to poor writing style. The best feature appears to be automatic code-quality review of Pull Requests.

Set up as I have it, it takes a while for master push commits like you just did to process (I've seen it take an hour, and I've seen it take six). If you were to set it up, as a project owner, there is an option you can set which makes it much faster re-analyzing master pushes.

Anyway, as of your two commits, it still shows the warning for line 1509 in the preprocessor and, of course, 3509 for Lua.

**Comment by jyrkive** [comment]
I pushed code that should fix the Lua issue *to my own fork*: https://github.com/jyrkive/wesnoth/commit/f02e89396a8ddb2b80b935a798371e44c90c938d

It requires significant refactoring, and an extremely ugly hack. If you ask me, the cure is worse than the disease.

The approach I recommend is suppressing the warning in Codacy.

**Comment by GregoryLundberg** [comment]
I agree, your 'fix' is ugly.

I am not opposed to suppressing the warning; just so everyone recognized this is just holding your nose to avoid the stench. Messages like this appear for a reason.

**Comment by AI0867** [comment]
Well, all remaining (and new) "issues" in preprocessor.cpp are now false positives. (it now wants me to pass a unique_ptr by reference, when I'm taking the argument like this to clarify that it's a sink)

As the fix for the lua issue is worse than the problem, I think we should now close this issue.

It might be interesting to look at redesigning the lua code to make the pointer ownership more natural, but this isn't the time to do that.
