### ISSUE TITLE
Variable `damage_inflicted` is not exposed in Lua API wesnoth.current.event_context

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2368]
I think it makes sense to add `damage_inflicted` as a field in `wesnoth.current.event_context` during the `attacker hits` event.

**Comment by CelticMinstrel** [comment]
Is that not available already? Admittedly not under such a nice name, probably `data1` or `value1` or something like that.

**Comment by vgaming** [comment]
@CelticMinstrel I can't find it at least. Here is a dump of `wesnoth.current.event_context`, formatted as JSON:
```json
{
  "1": {
    "1": "weapon",
    "2": {
      "1": {
        "1": "specials",
        "2": {}
      },
      "min_range": 1,
      "defense_weight": 1,
      "icon": "attacks/bow.png",
      "type": "pierce",
      "max_range": 1,
      "description": "bow",
      "parry": 0,
      "name": "bow",
      "attack_weight": 1,
      "number": 4,
      "movement_used": 100000,
      "range": "ranged",
      "accuracy": 0,
      "damage": 6
    }
  },
  "2": {
    "1": "second_weapon",
    "2": {
      "1": {
        "1": "specials",
        "2": {}
      },
      "min_range": 1,
      "defense_weight": 1,
      "icon": "attacks/javelin-human.png",
      "type": "pierce",
      "max_range": 1,
      "description": "javelin",
      "parry": 0,
      "name": "javelin",
      "attack_weight": 1,
      "number": 1,
      "movement_used": 100000,
      "range": "ranged",
      "accuracy": 0,
      "damage": 8
    }
  },
  "unit_x": 5,
  "name": "attacker_hits",
  "y1": 16,
  "y2": 16,
  "x2": 4,
  "unit_y": 16,
  "id": "",
  "x1": 5
}
```

**Comment by Vultraz** [comment]
From looking at the code:
```
	int damage = 0;
	if(hits) {
		damage = attacker.damage_;
		resources::gamedata->get_variable("damage_inflicted") = damage;
	}
```
Since this is an `attacker_hits` event, `damage_inflicted` should equal `weapon.damage`. Though this does raise the question of whether the `damage_inflicted` variable was supposed to take resistance into account...

**Comment by CelticMinstrel** [comment]
I think it's supposed to be the _actual final damage dealt_, so accounting for everything.

**Comment by Vultraz** [comment]
Right, but I'm not sure if `attacker.damage_` already has those calculations applied, or not... I guess one would have to test?

**Comment by Vultraz** [comment]
Ok, I can confirm that indeed `damage_inflicted` has the actual total damage and that `weapon.damage` only has the configured damage, not the actual.

**Comment by vgaming** [comment]
`damage_inflicted` variable shows the damage that was actually inflicted to a unit, accounting all possible effects on attacker side, defending side etc etc.

@Vultraz thanks!
