### ISSUE TITLE
wesnoth.cbp in CodeBlock not updated and files changes for compile with MINGW(by nuwen.net)64 bits

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#2377]
The wesnoth project with mingw is not updated, 3 or 4 files are not find. wesnoth_connection.cpp and hpp (std:mutex convert to boost:mutex)and server.cpp are not adapt to Mingw and only for tdm-gcc who will be abort.
I will post an
 zip with files when i could

**Comment by GregoryLundberg** [comment]
Please, just do it as a PR so you're not left hanging hoping someone will take the time to download, unzip, apply the patches, and create a PR on your behalf.

**Comment by Vultraz** [comment]
The CodeBlocks project is unmaintained. As @GregoryLundberg said, any changes need to be submitted via PR. I might remove the CB files soon anyway, though.

**Comment by newfrenchy83** [comment]
i willl post PR january 20. the zip is fir wesnoth_connection and mutex fix

**Comment by newfrenchy83** [comment]
i convert std::mutex to boost::mutex in wesnothd_connection for compile with MinGW(nuwen.net).
mingw64 don't function but this project could be  mainained. Cb include libraries and dll must be replace by 64 bits version but wesnoth start also in 34 bits without problems. Please, don't abort the codeblock project immediately, i haven't Visual studio and mingw is the only free compiler what i can download.
I don't know if i am the only in the case, but tkink.MinGW can replace TDM-GCC  in the project.

**Comment by Vultraz** [comment]
For the record, Visual Studio is free to download.

As for switching to a 64-bit Windows build, a lot of libraries would need to be recompiled.

**Comment by newfrenchy83** [comment]
Really? for 64 bit i recompiled the libraries and i will post the cb64.zip with the PR saturday. It will had more files what necessary, but it do function. For VS, the installer is on or offline, if it's online, i cannot download(smart

**Comment by newfrenchy83** [comment]
(smartphone or cybercoffe only), i am not high debit.

**Comment by newfrenchy83** [comment]
smartphone and cybercoffee only, not high debit in my village(80km to Paris only!). and i don't know for using license. I am probably the only develloper in that case, i concede

**Comment by GregoryLundberg** [comment]
What is the point of 'cb64.zip'?

If it's pre-compiled libraries, please, don't. They won't get added to the master tree.

If there are special steps you think are needed to get a CodeBlocks/MinGW64 build system up, like making 64-bit libraries, it would be best to provide a Markdown file with clear instructions, or add the work to the project file.

For Visual Studio,the libraries are available as binaries from a separate GitHub project. At present, they are 32-bit only.

**Comment by newfrenchy83** [comment]
all my excuses! I finally managed to compile with mingw64_posix 32bits version. Copy/paste the dll from mingw to wenoth location is sufficient. Tomorrow, i post the update Codeblock project, with wesnoth.cbp, wesnoth.cbp and README.md updated. Replace TDM_GCC by MINGW64 32 bits posix version could permit to prolonge the CodeBlock project without recompile all libraries. Thank you for Visual Studio, i will see this.
