### ISSUE TITLE
cmake flag to prevent installation of game assets

### ISSUE THREAD

**Issue by arunisaac** [wesnoth/wesnoth#2392]
I am building only the wesnoth daemon for installation on a headless server. I am using the cmake-flag "-DENABLE_GAME=OFF" to achieve this. However, during installation with `make install', various game assets such as images, fonts, music, etc. get installed into share/wesnoth. If I understand correctly, the wesnoth daemon does not need these assets. It would be nice to have a cmake flag that can prevent those assets from being installed.

I am using wesnoth 1.12.6 on GNU Guix SD.

**Comment by GregoryLundberg** [comment]
I can't assign @Pentarctagon but he's probably best for this having spent so much time on this recently.

Don't forget to check SCons while working on the CMake side.

**Comment by Pentarctagon** [comment]
I can take a look, though I've only made changes to the build flags and variables.  I've never done the `install` command with either scons or cmake.

**Comment by Pentarctagon** [comment]
Speaking of which, what all *shouldn't* be done for server-only installations?  Just from a quick read through, it looks like lines [542](https://github.com/wesnoth/wesnoth/blob/master/CMakeLists.txt#L542) and maybe [580](https://github.com/wesnoth/wesnoth/blob/master/CMakeLists.txt#L580) would need to be changed, but I don't actually know what requirements the MP server/add-ons server have.

**Comment by GregoryLundberg** [comment]
Some config files, maybe some folders. They're both basically standalone.

@shikadilord will know more.

The campaignd side of things needs some art assets for the web but I don't think it even verifies them on upload.

Basically, to start, just install the executable and, if there is one, the man page. We can find out if any directories need to be pre-created during testing.

**Comment by Pentarctagon** [comment]
I'll wait for him to reply then.  Changing the cmake script looks like it'd just be a matter of only copying over any needed sub-directories rather than everything, but I've never done any of this before and I don't want to just start poking at it blindly.

**Comment by shikadilord** [comment]
Neither campaignd and wesnothd require game assets for anything (`data/lan_server.cfg` doesn't count since it's only used for wesnothd instances launched through the game client, and IIRC it's copied to the preferences dir anyway).

addons.wesnoth.org has nothing to do with campaignd.

**Comment by shikadilord** [comment]
Actually, correction, campaignd does require *one* asset to operate correctly, and it's `data/COPYING.txt`. But honestly, people should have no business installing campaignd in the first place.

**Comment by GregoryLundberg** [comment]
@arunisaac Can you pull the PR and confirm it works as you expect?

**Comment by Pentarctagon** [comment]
He's using 1.12.6, so it would have to backported to 1.12 if there are no issues with the PR.  That doesn't look like it'd be too difficult though.

**Comment by GregoryLundberg** [comment]
He's building from source. I was hoping he would fast-forward to your PR. He'd just have to be sure the match client and server versions for any testing.

I was thinking I'd put up a VM to check it but that's a lot of work for such a small change.

**Comment by arunisaac** [comment]
No need to backport. I will directly clone Pentarctagon/wesnoth and build the relevant branch. Give me a while. I'll get back to you when I'm done.

**Comment by arunisaac** [comment]
I have verified the pull request. A large number of translations have been installed to `share/wesnoth/translations`. I'm assuming wesnothd requires them. If so, then everything works as I expected.

**Comment by GregoryLundberg** [comment]
Nope. That's an escape. Only the game client (wesnoth) needs translations.

**Comment by arunisaac** [comment]
In that case, please remove the translations as well.

**Comment by GregoryLundberg** [comment]
Patience. I'm sure he'll jump on it once he wakes and has some coffee :P

**Comment by Pentarctagon** [comment]
You can already use `ENABLE_NLS` to enable/disable translations.

**Comment by GregoryLundberg** [comment]
damn I need to take my finger off the mouse when I fall asleep at the keyboard.

**Comment by arunisaac** [comment]
Yes, `ENABLE_NLS=OFF` does the job. But, is it somehow possible to make `ENABLE_GAME=OFF` imply `ENABLE_NLS=OFF`? Is that a good idea? What do you think?

**Comment by Pentarctagon** [comment]
I [changed that](https://github.com/wesnoth/wesnoth/pull/2393/files#diff-af3b638bc2a3e6c650974192a53c7291R57) in the last push yesterday as well.

**Comment by arunisaac** [comment]
Thanks! Everything is working exactly as I expected.
