### ISSUE TITLE
Titlescreen flash when starting game

### ISSUE THREAD

**Issue by GregoryLundberg** [wesnoth/wesnoth#2395]
When testing #2372 I notice a flash of the titlescreen after 'Reading unit tiles ...' and before 'Building terrain rules ...'

This only occurs on a cold start of the wesnoth client. If I quit back to the titlescreen and reload the replay without quitting to the desktop, I do not see the flash.

**Comment by Vultraz** [comment]
Been an issue for years. Probably has to do with the loading screen object being created twice or something? Or destroyed and recreated?

**Comment by CelticMinstrel** [comment]
I think there are indeed some circumstances where the loading screen is effectively shown twice consecutively. It was more obvious on the old loading screen, which had an actual progress bar (which I am still mildly annoyed about it being removed).

**Comment by Wedge009** [comment]
Why was it removed, anyway? Inaccurate representation? gui2 conversion?

**Comment by Vultraz** [comment]
I didn’t like it.

**Comment by Vultraz** [comment]
Well, to be more specific, it was too large and in-your-face before. I dropped it with the conversion to GUI2 since I thought we could get away with an icon only, but @CelticMinstrel insisted we have some animated part, so that’s what we have the dots. I suppose a smal progress bar could be added back, maybe, but how to determine how much to fill up at any given time I’d have to find.

**Comment by Wedge009** [comment]
Even a smaller one would still be nice, but not high priority obviously. The dots at least indicate that something is busy working, I suppose.

Sorry, back to the actual issue discussion...

**Comment by Wedge009** [comment]
I'm not seeing any flash in 1.14.0 (Windows or Linux). Is this still happening? It may just be that I've been running Wesnoth a lot in the past few hours so a lot of resources could still be in OS memory.

**Comment by Vultraz** [comment]
The underlying issue wasn’t solved, no.

**Comment by CelticMinstrel** [comment]
Pretty sure I've seen it as recently as the last release candidate.

**Comment by Wedge009** [comment]
1.14.9

**Comment by Wedge009** [comment]
Closed in #2395, back-ported to 1.16 in 9be14b46030ca8edaa7a2be67ec111e00c5b5537.

**Comment by CelticMinstrel** [comment]
@Wedge009 That referenced issue number is wrong (it's this PR) – do you know the correct one?

**Comment by Wedge009** [comment]
Sorry, fixed. Must have copied the wrong number...
