### ISSUE TITLE
Linux: quit titlescreen with  ctrl (+ shift?) + q

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2397]
This has been reported in the 1.13.6 feedback thread: (r.wesnoth.org/t44809)
On Linux you can quit most Applications with ctrl + q.
For 1.12 this was the case for wesnoth too, it has been changed to ctrl+shift+q nowadays.

While this change was intentional, it seems it was rather a side effect.
I recall that we had way bigger issues with hotkeys, and I think some bugs are still unsolved.
(Things into one doesn't stumble if one uses US layout)

**Comment by Wedge009** [comment]
> While this change was intentional, it seems it was rather a side effect.
I understand English might not be your first language but I don't understand this sentence - I suppose it connects with why you call it a regression?

It looks like @CelticMinstrel's change in c3538798, making the quit-to-desktop command apply to both title-screen and editor might be related, as opposed to the quit command (which only quits to title-screen).

I suppose Ctrl+Q might be convention for Linux, as Alt+F4 is for Windows. Should the default quit (to title-screen) command be changed to Ctrl+W and the quit-to-desktop command be changed to Ctrl+Q?

**Comment by CelticMinstrel** [comment]
I think it was changed to Ctrl+Shift+Q as a protection against accidentally hitting the key and losing your game. As I recall, that's no longer an issue (hitting the key now produces the regular confirmation box). Assuming I do recall correctly, I wouldn't mind it being changed to Ctrl+Q (and Cmd+Q on Mac).

**Comment by Wedge009** [comment]
Actually, now that you mention it, that's probably what happened. I do remember there was previously no confirmation dialogue and, in fact, 1.12 does quit immediately when using those hot-keys.

Should we change the defaults from Ctrl+Q and Ctrl+Shift+Q to Ctrl+W and Ctrl+Q respectively, then?

**Comment by CelticMinstrel** [comment]
Provided Ctrl+W / Cmd+W aren't used for anything else, that could make sense, but I think they might actually be used for "close map" in the editor...

**Comment by GregoryLundberg** [comment]
https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

**Comment by Wedge009** [comment]
When I checked yesterday I didn't see Ctrl+W used for anything, but I'll check again.

**Comment by Wedge009** [comment]
Default quit (to title-screen) command is set to Cmd+W in OSX but Ctrl+Q for everything else.
