### ISSUE TITLE
AI not working

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#2398]
As of master 182b4bb1e5f227ba1eaea397781fe8e5e3b00bb8
To reproduce, start any scenario with a computer side. It will not recruit any units.

@Vultraz:
Probably something to do with
c8b0833b1a9293fc9b7b56ff362bc4aad49a54ad
or
3dc8617ec9396d5d0612ef9fda626d45d12e54dc

**Comment by Vultraz** [comment]
Latter is the cause.
