### ISSUE TITLE
OptionWML: [checkbox] (at least) doesn't set variables

### ISSUE THREAD

**Issue by Elvish-Hunter** [wesnoth/wesnoth#2401]
While trying to port one of my campaigns to 1.14, and at the same time trying to implement a feature, I decided to use OptionWML's `[checkbox]` tag. It turns out that, on 1.13.10+dev, at least `[checkbox]` doesn't set any variable - it's possible that the other available controls might suffer of the same issue.
So I created a test case, using Two Brothers as base.
In the attached diff, you can see that I added (in the `[campaign]` tag, exactly as the wiki says) a checkbox which should set a variable that transforms Arvith from a Knight to a Dragoon: the dialog is correctly shown, but the variable `arvith_dragoon` is never set, no matter what the value of the checkbox is, and this can be easily verified by issuing the `:debug :inspect` commands after the scenario starts.

This is the diff, renamed as .txt to allow its upload: [checkbox.txt](https://github.com/wesnoth/wesnoth/files/1670521/checkbox.txt)

**Comment by sigurdfdragon** [comment]
I haven't tested your diff yet, but I tested the [checkboxes] I have in Random Campaign 1.3.2 (an MP campaign) on the latest master (24e40cc0b18a9167f1a910b946cc64586450a77b), and they work. So maybe this is just a SP thing?

**Comment by ProditorMagnus** [comment]
>Please note that the option variables are initialized in a prestart event, therefore they can't be used before the first prestart event.
