### ISSUE TITLE
Improve "silent quit" when running wesnothd from wesnoth

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2403]
Steps:
* make `/var/run/wesnothd` not writeable by any user. (`chmod -w /var/run/wesnothd` on Linux.)
* start wesnoth client, start hosting networked game.

Expected at this point: wesnoth gives an explanation on the reason of failure, or at least shows an "error" pop-up.

Actually: wesnoth silently quits to main (starting) screen.

**Comment by jostephd** [comment]
> Actually: wesnoth silently quits to main (starting) screen.

How do you get this behavior? As far back as 1.10, if wesnothd is not executable I get a dialog asking me where the wesnothd binary is. That's not as good as showing the error message from trying to execute wesnothd but it's better than silent quit.

**Comment by vgaming** [comment]
@jostephd wait, the "steps" explicitly states on how to reproduce the issue. Did you try to make /var/run/wesnothd not writeable?

**Comment by jostephd** [comment]
@vgaming No. The steps say "make wesnothd error-quit in any way" so I made wesnothd fail to start by `chmod -x` or by symlinking it to /bin/false.

**Comment by jostephd** [comment]
I can host MP games on localhost even though /var/run/wesnothd/ is not writable by me. It gives an error message but I can host, join, and start a match.

20180920 19:34:03 error server: could not make fifo at '/var/run/wesnothd/socket' (Permission denied)
20180920 19:34:05 warning network: Failed to connect to ::1: Connection refused

**Comment by sevu** [comment]
(/var)/run/wesnothd/socket (actually a pipe) can be used to send there administrative commands, but to my knowledge it's not required to have this file.
A typical situation is to start wesnothd from within the wesnoth UI as user
In that case the `-d` option is used, it's not going to main screen because of a failure but because it forked it off.

**Comment by jostephd** [comment]
@vgaming Can you reproduce the error?

**Comment by vgaming** [comment]
@jostephd I guess I no longer can. I do not even see the /var/run/wesnothd dir anymore. It's not there, and everything works smooth without it.
Thanks for bringing this up, closing issue.
