### ISSUE TITLE
Feature request: improve faction/leader display?

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2405]
Current view, no faction selected, no leader selected:
![rand_fact_rand_lead](https://user-images.githubusercontent.com/33452702/35481326-8866c2ec-0432-11e8-88f8-63838087f3c3.png)

Current view, faction selected, leader not selected (random):
![rand_fact](https://user-images.githubusercontent.com/33452702/35481330-925873f4-0432-11e8-8d73-18e8005840ea.png)

Within all of the pictures above, only the `>>` is clickable. Can we improve the situation?
1. can we make ALL area click-able, not just the `>>` symbol (IDK what it means by the way)
2. can we remove `>>` altogether? I'm not sure what it does exactly.
3. If a specific faction was chosen by a side, can we NOT show the dice image anymore?
4. can we make a meaningful picture for a situation where faction is chosen, but leader is not? It's not a very common situation -- people often chose leader, too. So maybe a blank space would be good enough. But are there alternatives? Maybe we can tile all races that a faction contains?
5. also, I would personally avoid showing a yet another dice for "Gender". If it's unspecified, I'd rather hide it.

Here is an example for 4. that I tried to create using GIMP:
drakes:
![faction_drakes](https://user-images.githubusercontent.com/33452702/35481469-349e0fbe-0435-11e8-8591-6491d1d1a965.png)
northeners:
![faction_northeners](https://user-images.githubusercontent.com/33452702/35481472-3bb98120-0435-11e8-9128-956584245be4.png)
honestly, I'm not sure it's any good. Added just to see how it looks. Can be disregarded if it looks bad. Other proposals still hold.

**Comment by vgaming** [comment]
@Wedge009 regarding the "Enchancement" label. I think that the strange `>>` icon and non-clickable dice/labels section is more a bug. I mean, it's totally counter-intuitive, to me. I have no idea what would `>>` mean at all. So I'd personally split the 1. and 2. points in this issue and view them as **bugs**. Other proposals are not that important and I'd view them as Enchancement, too.

**Comment by Vultraz** [comment]
I used >> as an icon because I couldn't think of a better "Select" icon to use here.

**Comment by Pentarctagon** [comment]
FWIW, this confused me as well the first time.  I was expecting to click the leader sprite, since that's what the `>>` was pointing to.  It took me a minute or two of random clicking before I got the `>>` and realized what it was meant to do.

**Comment by knowak** [comment]
">>" was fixed with https://github.com/wesnoth/wesnoth/commit/d4ee030b59b8d13e33741ffe2af93188446c0b44 

As far as I'm concerned the only remaining part of this UI that confuses me is that dash that changes into "Random" or leader unit type name...

**Comment by Vultraz** [comment]
The dash simply means nothing is set.

**Comment by CelticMinstrel** [comment]
Perhaps for 1.14.1, replace the dash with the string "Not chosen"?

**Comment by vgaming** [comment]
@CelticMinstrel IDK, wouldn't the hyphen sign `--` be more visually distinguishing?

**Comment by CelticMinstrel** [comment]
What, are you suggesting using a double hyphen instead of an M dash? That doesn't make any sense to me.

**Comment by vgaming** [comment]
@CelticMinstrel OK maybe I didn't really understand something, because IDK what you mean by M dash. I'll retreat from discussion for a while until I at least compile everything and see it in more detail.

**Comment by CelticMinstrel** [comment]
Hyphen: -
N/en dash: –
M/em dash: —

**Comment by vgaming** [comment]
@CelticMinstrel understood now. Double hyphen was a mistake, I just tried to type the longer em dash this way. What I wanted to say is that the long dash may be more visually distinguishing than text "Not chosen".

**Comment by knowak** [comment]
Any opinions on adding a "Leader:" label as showed on my screenshots?

**Comment by Vultraz** [comment]
Hmmm... that is perhaps acceptable, yes.

**Comment by Wedge009** [comment]
Checking 1.15.17+dev...
1. Could be nice to have but possibly somewhat mitigated by the next point...
2. As mentioned, '>>' has been for a while now been replaced with a rather obvious button which I think works sufficiently.
3. With leader: chosen leader replaces the die image.
4. Without leader: Generic die image remains because leader is 'random'
5. I don't see any issue with another die for random leader gender, nor a suitable alternative.

As best as I can tell, the most worthwhile outstanding issue here is the addition of 'Leader:' label ahead of the 'Faction:' and 'Gender:' labels. Looks like that never happened?

**Comment by Vultraz** [comment]
I don't think adding the "Leader" label is necessary.

**Comment by CelticMinstrel** [comment]
Suggestion for 1.16.1: change the string "random" for a random leader to "Random Leader".

**Comment by Wedge009** [comment]
At this point I'm not sure what would be acceptable though that sounds reasonable to me. You could make that suggestion in #2955 or even just make the change in master and make the note to back-port it.
