### ISSUE TITLE
wesnoth.set_variable regression

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2418]
steps:
```lua
wesnoth.set_variable("_a", 1)
print(wesnoth.get_variable("_a"))
```

Expected: same behavior as on 1.12, the variable is successfully written and read.

Actually:
* on 1.13, first line returns successfully. But savegame won't have that variable.
* second line returns without Lua errors, and prints nothing. Not even `nil`, really nothing. If you write `type(wesnoth.get_variable("_a"))`, you'll get a Lua error.

**Comment by vgaming** [comment]
zookeper reports that behavior was correct in a build "about two months old".

**Comment by GregoryLundberg** [comment]
Once, again, I cannot reproduce the issue when I add the lua to AToTB S01 start event. The save file for the start of turn 2 does, indeed, have the variable set to the value I chose.

I checked the source code and no changes have been made for about two years, which does not fit with Zookeeper's observation.

I note that, as last time, the issue appears when using debug.

I am beginning to think that the issue is not with the various problems but that they should all be closed and an omnibus issue opened for debug console, hand-entered lua not working.

**Comment by GregoryLundberg** [comment]
OK. Please re-test using "a_" instead of "_a" and if that works, the issue is with the recent changes to what is a valid name.

Marking this Confirmed .. it's just not the bug you thought it was.

**Comment by GregoryLundberg** [comment]
Added to S01
```
[lua]
code=<<
wesnoth.set_variable("_greg", 314)
print(wesnoth.get_variable("greg"))
>>
[/lua]
```

On console:
```
Battle for Wesnoth v1.13.10+dev (7a6c39380e-Clean)
Started on Tue Jan 30 13:15:55 2018

Automatically found a possible data directory at /home/lundberg/wesnoth

Data directory:               /home/lundberg/wesnoth
User configuration directory: /home/lundberg/.config/wesnoth
User data directory:          /home/lundberg/.local/share/wesnoth/1.13
Cache directory:              /home/lundberg/.cache/wesnoth

Setting mode to 1360x713
Checking lua scripts... ok
20180130 13:16:06 warning scripting/lua: Cannot resolve variable '_greg' for writing. when attempting to write a 'number'
```

**Comment by Vultraz** [comment]
Indeed, the problem is that `_greg` (or any variable with a leading `_`) fails this check: https://github.com/wesnoth/wesnoth/blob/master/src/variable_info_private.hpp#L131, probably as a result of fbb0e0229cf4c870fef69e0b6729e9a1ea69b6fe.

Not sure what we should do about this.

**Comment by Vultraz** [comment]
Ya know what, I'll do that. It makes sense, since it restores the old behavior.

**Comment by CelticMinstrel** [comment]
The only problem is, this could potentially bring back #2375 if I understand correctly...

**Comment by Vultraz** [comment]
I don't see why. That's related to WML tags, this is variable names.

**Comment by CelticMinstrel** [comment]
WML variables are stored _as WML_. Every variable is either a WML tag or a WML attribute.

**Comment by tsaiwangchang** [comment]
I'm sorry! I'm out.

**Comment by jyrkive** [comment]
Well, there is the additional safeguard that Wesnoth refuses to save now if the save file can't be loaded afterwards. If underscores in variable names result in unloadable saves, at least players won't accidentally overwrite their working saves with broken ones.
