### ISSUE TITLE
CMake: is it possible to change the configuration directory?

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2419]
I am usually building with scons, and set many variables to have it work in parallel with the 1.12 installation. E.g. `mandir`, `docdir`, `fifodir`, ...
AFAIK there does not exist an equivalent for `prefsdir` in cmake - or I have missed it.
Which means one cannot install multiple version in parallel using cmake.

**Comment by jyrkive** [comment]
PREFERENCES_DIR=\<anything you like\>
