### ISSUE TITLE
Menu -> Back to... in MP local game is broken

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#2422]
Using the command: Menu -> Back to... to select a previous turn to return the game state to in at least an MP local game no longer works. It does nothing when selected. It still works in SP though.

Not certain, but I think this appeared sometime in the last week or two.\

On current master: 5bc09da48d659c9c66a19458c6de6fba3da5abc5

**Comment by Vultraz** [comment]
Is this... *supposed* to work in MP?

**Comment by GregoryLundberg** [comment]
Sorta, yes.

On 1.12 it puts up warning that it's a SP option and MP should use Load Game instead. The game for that player then goes back. Tested with 2P Aethermaw and I'm amazed the game survived but maybe it was because I was only setting back one turn and not two or more.

**Comment by sigurdfdragon** [comment]
fixed, thanks.
Though there's a regression:
In SP campaigns, Back to... no longer includes 'Back to Start' for all campaign scenarios (it's present in 1.13.10 & 1.12.6. Interestingly, this appears to only be an SP campaign issue.
As 'Back to Start' is an option in MP campaign scenarios after the first scenario (Don't know if it was ever supposed to work for the first scenario in MP)

**Comment by Vultraz** [comment]
@sigurdfdragon cannot reproduce. Back to Start is included in SP scenarios beyond the first for me.

**Comment by sigurdfdragon** [comment]
What is was is that I was using start of scenario saves made before the fix. those ones don't have the 'Back to Start' option on 'Back to...'
When I make a fresh start of scenario save, I get the same as what you got.

**Comment by Vultraz** [comment]
Odd. I'd have not expected those saves to be affected by the original regression. *shrug*
