### ISSUE TITLE
32-bit warning when launching Wesnoth on macOS 10.13.4 and later

### ISSUE THREAD

**Issue by Thunderforge** [wesnoth/wesnoth#2427]
When launching _The Battle for Wesnoth_ on macOS 10.13.4 and later, the user sees the following warning:

![image](https://user-images.githubusercontent.com/2218817/35726269-97a62c72-0804-11e8-8a14-e1f743cf2947.png)

This is due to Apple phasing out support for 32-bit apps on macOS, [much like they did for iOS](http://www.idownloadblog.com/2017/06/06/ios-11-no-32-bit-app-support/) last year. [From Apple's website](https://developer.apple.com/news/?id=12012017a):

> If you distribute your apps outside the Mac App Store, we highly recommend distributing 64-bit binaries to make sure your users can continue to run your apps on future versions of macOS. The last macOS release to support 32-bit apps without compromise is macOS High Sierra.

macOS High Sierra (a.k.a. 10.13) is the latest version of macOS, so we can expect that macOS 10.14, probably available in Q3 2018, will be unable to run 32-bit apps (or will run them "with compromise"). If Apple follows the same pattern that they did with iOS, we can expect that in the coming months the operating system will start showing more aggressive messages encouraging developers to update their app to 64-bit.

As the guidelines above say, the only solution to ensure compatibility with future versions of macOS is to distribute the Mac binary as a 64-bit app. The last Mac sold with a 32-bit CPU [was in 2006](https://apple.stackexchange.com/a/99644/64937), so any Mac sold in the last 12 years will be able to run a 64-bit version of _The Battle for Wesnoth_.

What will it take to convert the Mac version of Wesnoth to 64-bit before the next version of macOS comes out?

**Comment by GregoryLundberg** [comment]
As I understand it, there is no reason that the macOS version cannot be a 64-bit build.

I am on Arch Linux and it's already 64-bit for me and I didn't do anything special.
```
$ file wesnoth
wesnoth: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=a931c22f2fb6f3ed36f1d142bb10ec4a403b56ce, not stripped
```

The only 32-bit only build I know of is for Windows using Visual Studio and that is only because the external modules are usually downloaded from Github and only 32-bit versions are there. And there's recent talk about when to upgrade to 64-bit and abandon any players remaining on 32-bit only versions of Windows.

I'm going to mark this as a Feature Request, but I think it's just an issue for whoever does the "official" macOS build.

**Comment by hrubymar10** [comment]
It is true but not fully. This warning is shown only for 1.12.6 which was build in 2016. Newest dev versions have both slices (64-bit and 32-bit) or even only 64-bit I am not sure. This will be fixed by next major release of Wesnoth 1.14 which will be released soon.

**Comment by Thunderforge** [comment]
Looking at the macOS System Information report, it does say that the latest development version is indeed 64-bit.

<img width="668" alt="wesnoth system information" src="https://user-images.githubusercontent.com/6200170/35762877-3c760b22-0865-11e8-8088-147922a19cc4.png">

Should we close this issue then as already resolved?

**Comment by Vultraz** [comment]
Indeed. 1.14 is planned for April, and there definitely won't be another 1.12 release.
