### ISSUE TITLE
HttT S04: "Or" at the start of a sentence

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#2435]
In HttT S04, Delfador says:

> You must lead your men to the city and help defend it. Or recapture it if it falls before you arrive.

The punctuation here is wrong: "Or" shouldn't be the first word of a sentence.

**Comment by CelticMinstrel** [comment]
While I don't really have a problem with sentences beginning with "or", in this case it does make more sense to just merge the two sentences together.
