### ISSUE TITLE
MP: 6p_Team_Survival

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2440]
6p Team Survival is a map where borders are drawn to separate non allied but adjacent players. By default all players are allied.
In 1.13 there was some refactoring, and and a few hexes are now broken when playing with default settings.
![team_survival](https://user-images.githubusercontent.com/21158813/35782171-a91f9078-09f4-11e8-830a-371d87a326ec.png)

I looked a bit through the changes in 1.13 and didn't find the issue yet, eventually I have a look at this another day.
The bug must be in the scenario file, the map file is fine.

**Comment by CelticMinstrel** [comment]
Perhaps an off-by-one caused by the removal of the map border setting? If so, the fix might be very simple.
