### ISSUE TITLE
Uploading an addon without passphrase is not forbidden

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2444]
Uploading an addon without passphrase is not forbidden.

If you upload such add-on to the server, the password is assumed to be equal to `""`.

I'd say this is a bit counter-intuitive. Would it make sense to forbid uploading such add-ons?

**Comment by Vultraz** [comment]
A empty password is supposed to cause one to be generated and written back to the pbl.

**Comment by Vultraz** [comment]
Which I can confirm happens.

**Comment by vgaming** [comment]
@Vultraz on the other hand, if you use wesnoth_addon_manager, then nothing is written to _server.pbl, and the real value for your passphrase would indeed be "".
We discussed this with @soliton- a while ago.

I wonder who generates the password BTW: wesnoth client or the server. I would expect the client to do that because of the info above. Still, the issue is not as important if the default wesnoth client fixes those problems by default.

**Comment by Vultraz** [comment]
The client does it: https://github.com/wesnoth/wesnoth/blob/master/src/addon/client.cpp#L134-L143

**Comment by Vultraz** [comment]
Anyway, sounds like this is an issue with the wesnoth_addon_manager.

**Comment by vgaming** [comment]
@Vultraz well if server accept the wrong stuff, then it's server-side validation problem, isn't it?

**Comment by CelticMinstrel** [comment]
Sounds like a problem with _both_.

**Comment by shikadilord** [comment]
It seems to me like wesnoth_addon_manager lacking the ability to do as the mainline client and generate a random passphrase in lieu of an empty one ought to be reported and fixed as a separate issue.

**Comment by soliton-** [comment]
Yes, it‘d certainly be best if wesnoth_addon_manager had feature parity there. Thanks for fixing the server side!

**Comment by vgaming** [comment]
@shikadilord thanks for the (server-side) fix!

I see a mental mismatch of passwords been written in _server.pbl and they way CLI world usually works. Let me explain.

In CLI world, you would automate things. You would also put things in a VCS (git). Currently though, _server.pbl contains stuff that is both private (pass) and stuff that should otherwise be shared for everyone, stored in VCS (icon, title, type, dependencies, translate, maybe email and feedback).

That leads to problems. You want to put _server.pbl in git, yet you cannot, because of the password. There are two possible work-arounds I see:
1. Introduce a separate file, like _credentials.pbl, that would store developer-specific information. Entries could, for example, be "concatenated" - but one of the files could be commited to git while the other would be private. This is not easy, it's a whole new concept that should be understood by standard wesnoth client etc.
2. Use wesnoth_addon_manager. Improve it a bit, allow specifying password from CLI. This way, you can keep the passwords anywhere you like, just make sure you specify it in CLI if you decide not to use standard _server.pbl.

As a reference, here is a repo where I really do make _server.pbl public: https://github.com/vgaming/afterlife/blob/master/_server.pbl
And here is the hellish script that supports doing that: https://github.com/vgaming/afterlife/blob/master/.build/tools-backup/wesnoth_addon_publish.sh
As you see, I specify _server.pbl version here: https://github.com/vgaming/afterlife/blob/master/.build/tools-backup/wesnoth_addon_publish.sh#L20
And I specify description and passphrase in the next two lines.

_This_ is how I think it should look like for a good CLI tool, only supported by upstream.

So, instead of generating passwords and writing them to _server.pbl file, I believe we should re-think a bit how CLI should work for it to be very effective. This would probably lead to the result "don't generate passwords", let the developer deal with it in a more intelligent way.

**Comment by vgaming** [comment]
Instead of reading the very long comment above, maybe this issue will clarify things best: https://github.com/wesnoth/wesnoth/issues/2485

**Comment by CelticMinstrel** [comment]
@vgaming Relevant forum thread: https://forums.wesnoth.org/viewtopic.php?f=2&t=42966

Note that, as far as I know, shadowm is no longer interested in actually implementing this.
