### ISSUE TITLE
Graphical artifacts when zooming out

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#2458]
I haven't noticed any pattern to this yet, but one way in which I can produce this is as follows:

- Start the test scenario (`wesnoth -t`)
- Zoom out so that the map area is smaller than the window (default hot-key is -)
- Toggle normal zoom (default hot-key is 0 or magnifying glass icon in side-bar, bottom-left of mini-map)
- Observe graphical artefacts outside the map area
- Switching windows to force a redraw resolves the artefacts but toggling the zoom brings them back

Discovered this while looking at #1636. Currently compiled at 118eb94b. I could only get it to happen on in Windows, but I think it's more to do with the window resolution as the window has to be quite large for this to happen (I run at 1920x1200 window in Windows, and 1280x800 full-screen in Linux).

**Comment by Wedge009** [comment]
![zoom](https://user-images.githubusercontent.com/13679322/35955341-eb88e4f0-0ce2-11e8-993c-2ad60a23daed.png)

**Comment by Vultraz** [comment]
Noticed this too the other day.

**Comment by cooljeanius** [comment]
It'd be nice if there were GUI menu options for zooming in and out; the hotkeys aren't too discoverable as-is...

**Comment by Vultraz** [comment]
There are 🤔 
![image](https://user-images.githubusercontent.com/3558659/126880843-ad8cf553-0086-447e-a6d6-6f70c046f551.png)

**Comment by cooljeanius** [comment]
oh derp; guess I was looking in the wrong place

**Comment by Wedge009** [comment]
I remember another issue discussing that this isn't easy to find...

**Comment by cooljeanius** [comment]
> I remember another issue discussing that this isn't easy to find...

#1636?

**Comment by Wedge009** [comment]
Specifically #1213, which I mentioned in #4423 (which I forgot about), which itself refers to #1636. So yes, indirectly. (:

**Comment by Wedge009** [comment]
Coming back to the original issue (I suggest discussion regarding the zoom be redirected to the aforementioned issues), I reconfirm this in 1.16 branch as well as master. I also confirm it's not OS-specific but seems related to relatively large resolutions (confirmed on 2560x1440).

**Comment by Wedge009** [comment]
While it doesn't happen for me in the test scenario at the moment, I can still find this occurring in other scenarios - the specific one I checked just now was UtBS S11.

Found this while attempting to replicate #6415.

**Comment by mesilliac** [comment]
This is likely related to halo rendering. The extra blob of rendered map to the bottom right of the actual map is centered on the unit with a halo.

There are also some occasional problems with halo rendering when zoomed in. I'm planning on looking at it, but wanted to leave this note here in case i don't get to it.

**Comment by Wedge009** [comment]
The halo explanation seems right. The unit concerned in UtBS is the Quenoth Sun Sylph which has a halo similar to the Mage of Light's. I could replicate the issue on 1.16.5 release but not with 1.17.5+dev after your #6855 merge. So I suppose this is resolved? Unless someone else finds a similar edge case.

**Comment by mesilliac** [comment]
Yes, i overhauled how halos render so this should be completely resolved.
