### ISSUE TITLE
FR: Menu could use one entry less

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2460]
There is an entry for "Pause Menu Game" and "Continue Network Game" while observing a game. I didn't use these yet, but I looks like only one of them is needed each time.

![menu](https://user-images.githubusercontent.com/21158813/35956036-7619049c-0c93-11e8-9334-6c8f1eeb5302.png)

**Comment by ProditorMagnus** [comment]
Would be better yes, then same hotkey could be assigned to both.
