### ISSUE TITLE
addons: when downloading addon list, cancel button does nothing

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2462]
When the addon manager downloads the list of available addons, hammering the "cancel" button does not affect anything, it just ignores it and loads the addon list as if nothing happened.

Battle for Wesnoth v1.13.11 (52db950e94-Modified)

**Comment by jyrkive** [comment]
How do you get the transfer dialog to show long enough to be able to hit the cancel button?

**Comment by matthiaskrgr** [comment]
:D
Well, my connection is not that fast...
Alternatively maybe you can do smartphone 2G tethering or something like that to throttle it down.
Or try to download a lot of things in the background on the machine.

**Comment by jyrkive** [comment]
Yeah... I live in Finland and have a 100 Mbps connection. I'm not able to press the cancel button fast enough.

https://en.wikipedia.org/wiki/List_of_countries_by_Internet_connection_speeds

**Comment by Wedge009** [comment]
You're still doing better than I am in Australia... but I was able to cancel the dialogue so I'm not sure what's happening for you.

**Comment by matthiaskrgr** [comment]
Hm,I build the game with asan/ubsan instrumentation and without optimizations so it is running very slowly, my clicks are not registered in time?

**Comment by jyrkive** [comment]
Indeed, it's possible that the game simply doesn't even process the click before the download has already finished.

In fact, that sounds more believable to me. I wrote the cancel code that's currently being used, and attempting to cancel downloading the add-on list should create a second network transmission dialog.

**Comment by Wedge009** [comment]
So... does it still happen with a standard optimised release build?

I tried it with MSVC debug-mode compilation (without debugging) and it registers my cancellation okay as well.

Well, if @jyrkive thinks there could be an issue, I'll let you work together on it. :)

**Comment by jyrkive** [comment]
I do **not** think there could be an issue. Matthias's original report doesn't sound believable to me.

Most likely the download just finishes before the game processes the click.

**Comment by matthiaskrgr** [comment]
Well ok then...

**Comment by Wedge009** [comment]
Sorry, mis-read your comment.

I did try some more and with the debug-compiled version it got to something like 80% when I tried to click cancel. It looked like nothing happened but in the background it was (very slowly, due to the debug-mode compilation) processing the add-ons list.

Maybe my Internet is so slow that I was able to cancel before the download completes.
