### ISSUE TITLE
Lobby Bugs - alphabetic sorting

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2475]
There is a button for alphabetic sorting - setting it changes the sorting to alphabetic
unsetting it... does nothing, leaves the sorting in the current state (alphabetic). It's changed when a new user joins.

**Comment by sevu** [comment]
Similar issues for the other button next to it, for sorting friends first, and ignored last.
I don't have and friends or ignored users, but setting that button changes the sorting.

**Comment by Wedge009** [comment]
Testing in 1.14.0 (which has plenty of people now that it's been released) seems to work okay. Are you still having this issue?

**Comment by Wedge009** [comment]
Closing this, then. For the friends-first/ignored-last one, your own name is treated as a 'friend' so it seems to behave as expected (I also have empty friend/ignore list). Thanks for your confirmation.
