### ISSUE TITLE
Map border draws under fog

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2479]
Presumably applies to shroud too, but that's really not noticeable. Almost certainly a regression from @ln-zookeeper making the map border draw with the terrain graphics engine.

**Comment by Wedge009** [comment]
What's meant by 'map border'? Is it the dark shading at the edges of the main game screen? Or an actual map border from an earlier version? I'm looking at 1.14.9 release.

**Comment by Wedge009** [comment]
#wesnoth-dev discussion:
> 07:34:06 - wesdiscordbot: <Vultraz> yeah, I meant thedark thing on the edge of the map
07:35:56 - wedge009: Vultraz: for #2479? Is it so bad for it to be under the fog? I thought it looks right as it is.
07:36:31 - wesdiscordbot: <Vultraz> not really
07:36:35 - wesdiscordbot: <Vultraz> it used to be over
07:36:40 - wesdiscordbot: <Vultraz> bit i guess it doesn't really matter
