### ISSUE TITLE
Lobby Bugs - missing markup

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2483]
An image says more than words:
![markup](https://user-images.githubusercontent.com/21158813/36069090-5d0199cc-0ee3-11e8-8b27-90ad20009d69.png)
Are there other places which could have the same issue?

On another note, is it correct to use 'They', while 'The host' is singular?

**Comment by CelticMinstrel** [comment]
Singular "they" is fairly widely accepted (though also widely disputed). I think it's fine.

**Comment by ProditorMagnus** [comment]
I guess I can remove explicit version check code from ageless after 1.13 then.
