### ISSUE TITLE
allow overriding _server.pbl entries via CLI

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2485]
This is a feature request for `wesnoth_addon_manager` to support overriding _server.pbl entries from CLI.

Example entries that developers may wish to override:
* `version`. Instead of in-lining in _server.pbl, calculate it at upload time, e.g. by using last git tag (`git describe --tags`).
* `passphrase`. A must-have key if you want to put `_server.pbl` in git (or any other VCS).
* `description`, if you want to avoid copy-pasting description between WML and _server.pbl.

The feature request is to support keys like this:
`--upload_pbl_override version "0.1.0"`

**Comment by CelticMinstrel** [comment]
Relevant forum thread: https://forums.wesnoth.org/viewtopic.php?f=2&t=42966

Note that, as far as I know, shadowm is no longer interested in actually implementing this.
