### ISSUE TITLE
movetype::terrain_info's fallback & cascade looks fragile

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2486]
This might be the cause of the "13.10-dev hex fields movement" bug, https://forums.wesnoth.org/viewtopic.php?f=4&t=47782 .

IIUC instances of terrain_info are linked so that:
X is a terrain, Y can have X as its fallback. Then X.cascade_ points to Y, so that X.clear_cache() calls X.data_.clear_cache() which calls Y.clear_cache().

But if Z is copy-constructed from Y, then X.clear_cache() will only notify Y and won't update Z. The default copy constructor is not deleted, so will cause this broken chain, and the default copy constructor is used by movetype's hand-written copy constructor.

At the moment this is just a partial code review, I don't have the spare time to go further with it.

**Comment by stevecotton** [comment]
I prototyped some changes, but they didn't fix the "13.10-dex hex fields movement" bug, so I no longer suspect that this is a cause of that.

**Comment by CelticMinstrel** [comment]
So, should this be marked as invalid and closed? Or should it be renamed?

**Comment by stevecotton** [comment]
I've changed "broken" to "fragile", I intend to open a PR eventually but if you wish to please feel free to close the issue.

**Comment by stevecotton** [comment]
Refactored code is now merged to both 1.14 and master, found and fixed some potentially dangling pointers as part of that.
