### ISSUE TITLE
MP chat command /ping 

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2487]
Among the commands available in Chat is /ping.
What does it do? A secret hidden somewhere in the source code
/help ping should give information about it
... or, eventually this can be removed.

(marking for the next release since it's a string change)

**Comment by Vultraz** [comment]
Looks like the code to handle pings is commented out server-side...

**Comment by Vultraz** [comment]
Ok, so it seems right now `/ping` doesn't do anything, I *think* because of protocol changes to wesnothd in 1.13 (the switch to `boost::asio`). It could be reimplemented to give network ping, but @GregoryLundberg says ping isn't really useful for TBS games...

Anyway, dropping this from the 1.13.11 milestone.

**Comment by soliton-** [comment]
The ping command just sends a message to the server so that you notice when you've lost connection. It's mildly useful in situations where you do not want to send some other message/command to notice disconnects.

It could perhaps be extended to display the round trip time or so.

**Comment by GregoryLundberg** [comment]
I did not say it's not useful. What I said is I know a number of real-time games which include it.

The person who would find /ping most useful would be the server manager. The shell ping command only verifies the system is up an reachable. A Python script, for example, could be written which sends an ICMP ping followed by /ping and compares the results. This would not only establish reachability, but ensure that wesnothd is also up and running and give remote ability to notice when the wesnothd is significantly slowed (as with high system loads or other causes).

Not all commands need be useful to the players.

**Comment by sevu** [comment]
> so that you notice when you've lost connection
That doesn't seem to work on 1.12 (didn't test 1.13)

**Comment by soliton-** [comment]
How did you test that?

**Comment by sevu** [comment]
- I started an networked game with somebody, turned off my wifi, sent /ping in the normal chat, and turned wifi on again.. Nothing happened.
- Had a game with only me vs an AI on the server, turned wifi off, sent /ping, waited very long. Nothing happened. When turing wifi on and ending my turn the AI made a move, then the game stuck, though I could see it still being listed in the games list with another instance of wesnoth, and it disappeared in the moment I left the game.
- Spectate a game, turn wifi off, sent /ping
- Just sent /ping with working network in the game / a spectated one / the lobby / mp staging

**Comment by soliton-** [comment]
Well, if you cannot provoke a disconnect at all then /ping will not either. No idea what's happening there though, certainly seems odd.

Don't know what your last test should show.

**Comment by jostephd** [comment]
So, if I understand correctly, what we need to do here is:

- [ ] Make `/help ping` work
- [ ] Make the server respond `pong` to a `ping` command

Right?

**Comment by soliton-** [comment]
The server response is only needed if we want to show the round trip time.

The help could say: "Sends some data to the server. Can be used to manually verify the network connection and notice disconnects."

**Comment by ProditorMagnus** [comment]
MultiplayerServerWML does not have API for ping. So if implementing ping command, client should also be changed to send something.

If ping does not show time, it does not need to be separate command, for example alias to "q version" would work as check if there is connection.

**Comment by jostephd** [comment]
I agree with @ProditorMagnus: ping doesn't _have_ to show round-trip time. Just showing a "pong" is enough to test connectivity.

**Comment by soliton-** [comment]
The ping command already exists and does send something. So far no server side API is needed.

I don't see why we should rewrite it to show the server version instead. We could as well remove it then. Would be less confusing.

**Comment by jostephd** [comment]
@soliton- The point is that the ping command doesn't have to show the round-trip time, or the server version, or anything else. It just has to say "Yes, a round trip was successfully completed". Forget about how to implement that for a moment, do you agree that would be reasonable behavior?

**Comment by soliton-** [comment]
That's fine sure. Only sending data like it does now is fine as well IMO. I would only make it a round trip if some interesting info is sent back otherwise I don't really see the point.

**Comment by jostephd** [comment]
> I would only make it a round trip if some interesting info is sent back otherwise I don't really see the point.

To check that round trips work, of course. If some router along the way starts to drop packets, you won't get an error from the TCP stack.

**Comment by jostephd** [comment]
That depends on what exactly the router does. If the router sends a RST packet, that would kill the TCP session immediately. If the router just ignores the packet entirely, the TCP session would remain active for a few minutes (performing retransmissions) until the timeout is reached.
