### ISSUE TITLE
Compiler warning in buffered_istream

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2492]
I'm getting the following warning in MSVC 2013:

```
buffered_istream.hpp(50): warning C4351: new behavior: elements of array 'buffered_istream::buffer_' will be default initialized
```

Not entirely sure what it means, so I thought it was best posted here.

**Comment by CelticMinstrel** [comment]
Still getting this... guessing the ignore just needs to be added to the other projects too?

**Comment by jyrkive** [comment]
Commit 77edec6048e78234d0e4f92114dd0139f5a53d09 should take care of it.
