### ISSUE TITLE
Lobby chat not reaching #wesnoth-mp-lobby-dev

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2497]
1.12 equivalent #wesnoth-mp-lobby-stable includes lobby chat. It is important for mp moderation.

Special messages like from /q lobbymsg still reach the channel.

**Comment by soliton-** [comment]
Fixed with 7ca7ed0e4f1bc3fe9aeaabc01a3a17ac4a89b8a8.
