### ISSUE TITLE
Crash from N4gui231layout_exception_width_modifiedE

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2498]
Testing with "/q adminmsg nope" once caused crash with this log. Not reproducible.

Battle for Wesnoth v1.13.10
Setting mode to 1048x775
..
Caught general 'N4gui231layout_exception_width_modifiedE' exception:
std::exception

**Comment by CelticMinstrel** [comment]
If I understand correctly, this would imply a missing catch somewhere (as this exception is used to quickly jump out of nested function calls if I understand correctly).

Perhaps @jyrkive knows more?

**Comment by ProditorMagnus** [comment]
Today N4gui236layout_exception_width_resize_failedE happened while I was not looking. Resolution is around 1099x829.

`20180505 19:59:37 error gui/layout: grid [_content_grid] place: Failed to place a grid, we have 935,3034 space but we need 773,3116 space. This happened at a grid with the id '_content_grid' in a 'N4gui27listboxE' with the id 'game_list' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'mp_lobby'.
20180505 19:59:42 error gui/layout: grid [_content_grid] place: Failed to place a grid, we have 935,3034 space but we need 773,3116 space. This happened at a grid with the id '_content_grid' in a 'N4gui27listboxE' with the id 'game_list' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'mp_lobby'.
20180505 20:00:06 error gui/layout: grid [_content_grid] place: Failed to place a grid, we have 935,3034 space but we need 773,3116 space. This happened at a grid with the id '_content_grid' in a 'N4gui27listboxE' with the id 'game_list' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'mp_lobby'.
20180505 20:00:14 error gui/layout: grid [_content_grid] place: Failed to place a grid, we have 935,2952 space but we need 773,3034 space. This happened at a grid with the id '_content_grid' in a 'N4gui27listboxE' with the id 'game_list' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'mp_lobby'.
20180505 20:00:40 warning engine: User mimloopen has unknown game_id: 308
20180505 20:00:41 error gui/layout: grid [_content_grid] place: Failed to place a grid, we have 935,3034 space but we need 773,3116 space. This happened at a grid with the id '_content_grid' in a 'N4gui27listboxE' with the id 'game_list' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'mp_lobby'.
20180505 20:00:42 error gui/layout: grid [_content_grid] place: Failed to place a grid, we have 935,2952 space but we need 773,3034 space. This happened at a grid with the id '_content_grid' in a 'N4gui27listboxE' with the id 'game_list' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'mp_lobby'.
20180505 20:00:45 warning engine: User blumenkranz has unknown game_id: 309
20180505 20:00:46 error config: illegal map: Illegal tile in map: (Xv^Yyyy) 'Xv^Yyyy'
20180505 20:00:46 error config: illegal map: Illegal tile in map: (Xv^Yyyy) 'Xv^Yyyy'
20180505 20:00:47 error gui/layout: grid [_content_grid] place: Failed to place a grid, we have 935,3034 space but we need 773,3116 space. This happened at a grid with the id '_content_grid' in a 'N4gui27listboxE' with the id 'game_list' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'mp_lobby'.
20180505 20:00:51 error config: error writing to credentials file 'C:\Users\Ravana\Documents\My Games\Wesnoth1.14/credentials'
Caught general 'N4gui236layout_exception_width_resize_failedE' exception:
std::exception
`

**Comment by Wedge009** [comment]
The N4gui... naming doesn't really mean much, except maybe to those who know what it's about already. For the last couple of days or so, when I've been testing/checking the add-ons manager, I get this error messages like this for 1.15.17+dev in 1.16 branch, but not master:

`error gui/layout: grid [] place: Failed to place a grid, we have 1603,119 space but we need 364,123 space. This happened at a grid with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui25panelE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'addon_manager'.`

Maybe doesn't have much to do with your original issue, but the IDs looked similar.

**Comment by AI0867** [comment]
> The N4gui... naming doesn't really mean much, except maybe to those who know what it's about already. For the last couple of days or so, when I've been testing/checking the add-ons manager, I get this error messages like this for 1.15.17+dev in 1.16 branch, but not master (currently 1.17.0+dev):

It's just a `gui2::layout_exception_width_resize_failed` after C++ name mangling.

> `error gui/layout: grid [] place: Failed to place a grid, we have 1603,119 space but we need 364,123 space. This happened at a grid with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui25panelE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'addon_manager'.`

Again, these are `gui2::grid`, `gui2::panel`, `gui2::scrollbar_panel` and `gui2::window`.

**Comment by ProditorMagnus** [comment]
Hard to reproduce/not worth the effort.
