### ISSUE TITLE
Wesnoth commands report

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2500]
I marked with box those that I think need action.

Missing help entry
- [x] 	benchmark
- [x] 	theme

Incomplete help
- 	friend accepts note after name
- 	report alias is query adminmsg, in addition to just adminmsg

Unneeded
- 	controller - Lua and WML have access to it
- [x] 	details
- [x] 	drop
- [x] 	register
- [x] 	set

Room commands do nothing on 1.13, regression - though they have extremely limited use even in 1.12
- [x] 	join
- [x] 	names
- [x] 	part
- [x] 	room
- [x] 	room_query - topic at least doesnt work on 1.12 either
- [x] 	rooms

Untested
- [x] 	create - alternate for create unit menu?
- [x] 	throw - I guess same as fire_event as called from lua

Misc
- [ ] 	control/give_control - needs GUI access as well for 1.14
- 	"q" does not give help message that it is supposed to - when writing out query, or "q ", then that works
- 	log - unsure what domains and levels exist
- 	refresh - not sure what it does
- 	whiteboard, whiteboard_options - I guess first one is same as planning mode, second one if it still works should be reachable from same menu
- 	alias does not work when used with /
- [x] 	benchmark and fps are duplicates

**Comment by stevecotton** [comment]
Half of those can't be fixed during a string freeze. :(

**Comment by ProditorMagnus** [comment]
Only give_control GUI access is such that would be needed for 1.14.

**Comment by soliton-** [comment]
Perhaps not so great to have that many different issues in one report. Thanks for the overview nevertheless.

**Comment by CelticMinstrel** [comment]
If the GUI access can be done using only existing strings, sure?

**Comment by doofus-01** [comment]
I think "refresh" regenerates the image cache.  It's useful for drawing/testing terrain or sprite images, not sure a regular player would have reason to use it though.  

I think there used to be a command "sunset" that could have gone in the same category, but it doesn't seem to work anymore.  Maybe I'm miss-remembering the name.

**Comment by ProditorMagnus** [comment]
Sunset I reported long time ago, gna 22979.

Follow-up Comment #2:

Sunset was removed in 1.13.7.

Follow-up Comment #1:

I'm not convinced this is actually a bug.

This appears to be an extremely old debugging aid for developers, the purpose
is to help visualize what pixels are being redrawn during screen refresh
events. It might also be useful to see this during the main menu and such,
it's hard to say. I don't think it is intended to be used ever by users or
even WML developers.

Regardless I am downgrading the importance of this.

**Comment by doofus-01** [comment]
Those links must be unintentional?  I recall finding sunset useful once or twice, so I don't think it was a completely useless relic from early development, but I'm not arguing that it should be brought back.

"Refresh" certainly isn't useless, even if players and WML/Lua developers have no use for it.  Please don't remove it.  (Not that anyone said they were going to, but just in case anyone was getting that idea from the "sunset" stuff.)

**Comment by Vultraz** [comment]
`refresh` is very useful. It does as @doofus-01 says and purges the image cache.

**Comment by Vultraz** [comment]
References to #2049.

**Comment by Pentarctagon** [comment]
give_control has a GUI now.

**Comment by Pentarctagon** [comment]
details, drop, register, and set are resolved, as they no longer exist as of #4247

**Comment by Pentarctagon** [comment]
As for the room commands, what exactly was their purpose?  If they aren't currently functional and aren't especially useful anyway, perhaps they could simply be removed as well.

**Comment by ProditorMagnus** [comment]
It was equivalent of irc channels.

**Comment by jostephd** [comment]
Added theme, create, throw in 90f69b0494c30ea346fb7ef4f102c40c0303a65b.

**Comment by jostephd** [comment]
>  [ ] benchmark and fps are duplicates

They aren't, actually - :fps toggles the preferences, :benchmark is a one-off, toggles a few things that :fps doesn't (see display.cpp) - but yes, it's confusing. There's already a checkbox for documenting benchmark so I'll mark this duplication as done.

**Comment by ProditorMagnus** [comment]
> give_control has a GUI now.

I mean GUI to open the GUI it has, so something in menu or actions.

**Comment by Pentarctagon** [comment]
> I'll probably be removing what remains of the room commands once 1.16 is close to release, unless anyone would still prefer to keep that around.

So coming back to this, given no one has said anything in the mean time, I'll be doing that in the next few days probably.

**Comment by Wedge009** [comment]
I'm not really sure what's going on here, but 1.16 is pretty close - maybe it's too late to do that now?

**Comment by ProditorMagnus** [comment]
At this stage it is outdated enough that better to close it and potentially plan to review situation again.

**Comment by Wedge009** [comment]
Thanks for the feedback.
