### ISSUE TITLE
1.13.11  saved games contain "space" in the name , instead of underscore => duplicate saved games

### ISSUE THREAD

**Issue by alain-bkr** [wesnoth/wesnoth#2503]
I updated wesnoth from git, and found duplicated saved games, except  contain underscore and the other spaces

-rw-rw-r-- 1 alain alain  486647 févr. 10 15:29 LotI1-Achilles'_Revenge_Tour_1.gz
-rw-rw-r-- 1 alain alain  487599 févr. 13 23:43 LotI1-Achilles' Revenge Tour 1.gz

It was nice to have underscore in names, please put this back  (dash ,  simple quote are allowed , but please no space !)

$ git log | head
commit 0bc03e14c749699b7dfee5e8921b8ac34cf49d58
Author: Charles Dang <mail@mail.mail>
Date:   Tue Feb 13 16:19:22 2018 +1100

**Comment by jyrkive** [comment]
I changed the underscores to spaces (commit d2748dc4259fa6f493c5d08ec71c3140565231d4). What's the problem with using spaces?

**Comment by alain-bkr** [comment]
'space' in filenames is  mess under unix , it is a separator (i believe it should be forbidden in filenames even on windows)

What was the problem with underscore ?

**Comment by jyrkive** [comment]
As the commit message mentions, attempting to show the underscores as spaces required the code to convert underscores to spaces and back all over the place. It was just a mess, and sometimes it failed, see #1567.

The fact that space is a separator character only matters in the command line, when trying to e.g. delete files with rm. Players aren't supposed to be messing with save files in terminal, so it's a moot point.

Closing.

**Comment by alain-bkr** [comment]
Maybe just let underscore, and don't try t hide them by wrongly pretending they are spaces ?

And, btw, players do what they want with their saved games  :-)

**Comment by jyrkive** [comment]
Yeah, you can mess with saves however you like. But we aren't going to make decisions from the POV of making it easy to manipulate the saves manually.

**Comment by GregoryLundberg** [comment]
Enclose the filename in quotes to handle spaces.

**Comment by CelticMinstrel** [comment]
You can also deal with spaces on the command-line by preceding them with a backslash.
