### ISSUE TITLE
Possible to be thrown back to lobby when loading MP game

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2509]
Again, using Oath of Allegiance, when I lost I would quickly leave the game, return to lobby, click Load Game, and double click an autosave. Often I would then be thrown back to the lobby. If I waited a few seconds, I could do it with no problem.

**Comment by Vultraz** [comment]
Also possible when creating a game quickly.

**Comment by Wedge009** [comment]
I'm not sure what you're doing here. I thought Oath of Allegiance was a SP campaign. The MP Lobby doesn't allow loading of SP games (though maybe it did when you recorded this?).

**Comment by Vultraz** [comment]
It does.

**Comment by Wedge009** [comment]
It does...? What does? MP Lobby loads SP games? I couldn't get it to do so in 1.14.9 release, instead get an error message that it's not a MP save file.

**Comment by Vultraz** [comment]
I think you need to start the SP game though MP 🤔

**Comment by Wedge009** [comment]
Oh right. Yes, that seems to work.

Well, once I got to the auto-save of the second scenario (first play scenario) I kept re-loading that... nothing seems to be amiss. I used double-click on the load file dialogue - maybe when you tried it the second click somehow registered against the lobby? Either way, I can't replicate this one in 1.14.9.

**Comment by jostephd** [comment]
It's a wild guess, but maybe the problem here occurs if one manages to click `Load Game` and double-click a savegame _before_ wesnothd sends the updated game list? Then the updated game list says "Vultraz's game has ended", so he's thrown back to the lobby? Is this plausible? I don't really know how this part of the code works, but I'm not sure what else could explain the time dependence in the report.

**Comment by Wedge009** [comment]
Oh, I was testing on local MP... does this only work with networked MP? I didn't know the server kept save games (I don't really play MP).

**Comment by jostephd** [comment]
Vultraz said "lobby" so I assumed he was playing on the server. The lobby screen isn't used in "Local MP" mode.

**Comment by jostephd** [comment]
When starting an MP game one can load a (local) savefile. (There's also https://replays.wesnoth.org/ but it's unrelated)

**Comment by Wedge009** [comment]
Doesn't make sense to me to connect to the network just to reload a local MP game (which is what I was testing before). Anyway, not sure if Vultraz is still getting this particular issue.

**Comment by Wedge009** [comment]
May not be relevant, but I was using a mouse with a left-click that's starting to bounce (double-clicks when only a single-click was made) when starting a campaign and got thrown back to the main menu. Might be that the second click is still registering on the main menu screen, so similarly your second click here took you back to the MP lobby.

**Comment by Wedge009** [comment]
Is this still an issue in 1.18?

**Comment by Wedge009** [comment]
Closing due to age and lack of response.
