### ISSUE TITLE
1.13.11 : error messages about advancement

### ISSUE THREAD

**Issue by alain-bkr** [wesnoth/wesnoth#2514]
Hi

with Loti extension, I encoutered  a bug while upgrading wesnoth from git v1.13.10+dev a4e7cb0  (2018 Jan 6) to git wesnoth v1.13.11+dev (0bc03e1-Clean)  (2018 fev 13 )
 
i reported this in https://github.com/Dugy/Legend_of_the_Invincibles/issues/77 , but it seems related to wesnoth engine.

At least one functionality does not work anymore : 
* alter avancement

--------- 
The easiest way i found to reproduce the bug : 

using debug commands 
* select one unit
* :unit advances=1
The unit do level up (the dialog box appears ...) , but the i cannot "alter advancement)

-----------
This give lots of error messages on the screen (ctrl X to clear) and in th logs : 

Invalid WML found: Attempt to store nonexistent unit type 'Advancing Efraim_lich'.
Invalid WML found: Attempt to store nonexistent unit type 'Advancing Lethalia_lich'.
Invalid WML found: Attempt to store nonexistent unit type 'Advancing Dwarvish Hero'.
Invalid WML found: Attempt to store nonexistent unit type 'Advancing Delly_lich'.

or this kind  when one unit should have levelup during opponent's turn between turn 14 and 15 .

[LotI1-Chasing Dragons-Sauvegarde automatique15.gz](https://github.com/wesnoth/wesnoth/files/1734534/LotI1-Chasing.Dragons-Sauvegarde.automatique15.gz)
[LotI1-Chasing Dragons-Sauvegarde automatique14.gz](https://github.com/wesnoth/wesnoth/files/1734535/LotI1-Chasing.Dragons-Sauvegarde.automatique14.gz)

20180215 17:47:41 error scripting/lua: game_error: unknown unit type: Advancing Elvish Juggernaut
stack traceback:
[C]: in local 'cmd'
lua/wml-utils.lua:145: in field 'handle_event_commands'
lua/wml-flow.lua:52: in local 'cmd'
lua/wml-utils.lua:145: in field 'handle_event_commands'
lua/wml-flow.lua:38: in local 'cmd'
lua/wml-utils.lua:145: in field 'handle_event_commands'
lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
[C]: in field 'fire_event'
lua/wml-tags.lua:164: in local 'cmd'
lua/wml-utils.lua:145: in field 'handle_event_commands'
lua/wml-flow.lua:52: in local 'cmd'
lua/wml-utils.lua:145: in field 'handle_event_commands'
lua/wml-flow.lua:20: in local 'cmd'
lua/wml-utils.lua:145: in field 'handle_event_commands'
lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>

I can provides logs or saved games if needed.

**Comment by gfgtdf** [comment]
this was likely broken by https://github.com/wesnoth/wesnoth/commit/13a4822d77d8cb32b219b7c647fc9710309a2735

**Comment by Vultraz** [comment]
Indeed, this is an addon-side issue.
