### ISSUE TITLE
Help browser markup is included in certain translatable strings

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2516]
For example: `_("<header>text='Units with this ability'</header>"`. We can't fix this right now since we're in a string freeze, but it should be fixed for 1.15.

**Comment by soliton-** [comment]
This can be fixed with the help of pofix.

Note that markup in translatable strings is not an issue per se. In the shown case it certainly looks useless though.

**Comment by jyrkive** [comment]
Would pofix really help? If we remove the markup from the English string with pofix, won't it still remain in all other languages?

**Comment by soliton-** [comment]
Indeed we would also need to adjust the translations. That's probably not something pofix can do yet. So the point is rather that it can be done mechanically without translator help. You're right that it's a bit more involved.

**Comment by Vultraz** [comment]
Fixed as of 23e78ab. Since I went through the entirety of the code, I'm pretty certain I caught all cases.
