### ISSUE TITLE
need a way to identify/get missing Era from MP Lobby

### ISSUE THREAD

**Issue by sapientN3T** [wesnoth/wesnoth#2518]
I'm checking out the 1.13.11 Multiplayer Lobby and when I check the (i)nfo for Rear's game, it says Era: (missing). Join and observe are disabled. So, in other words, there's no way for me to know what era I am missing or get its required add-on.

![2018-02-19 15_48_19-the battle for wesnoth - 1 13 11](https://user-images.githubusercontent.com/19386345/36367199-921db94c-158c-11e8-97c0-ed279af181e6.png)

Additional Info:
Version= 1.13.11 (downloaded from Sourceforge)
OS= Windows 7
Log contents=
```
Battle for Wesnoth v1.13.11
Started on Mon Feb 19 15:24:06 2018

Automatically found a possible data directory at C:\Users\Parker\Documents\My Games\Wesnoth1.13

Data directory:               C:\Users\Parker\Documents\My Games\Wesnoth1.13
User configuration directory: C:\Users\Parker\Documents\My Games\Wesnoth1.13
User data directory:          C:\Users\Parker\Documents\My Games\Wesnoth1.13
Cache directory:              C:\Users\Parker\Documents\My Games\Wesnoth1.13\cache

Setting mode to 1024x768
Checking lua scripts... ok
20180219 15:26:46 error addons-client: add-on 'Gweddyn_the_Ruler' has an icon which cannot be found: 'units/player/rulerking.png~RC(magenta>green)'
20180219 15:26:46 error addons-client: add-on 'Water_Era' has an icon which cannot be found: 'projectiles/nagas_merman.png'
20180219 15:28:01 error display: ~BLIT(): image not found: 'units/khalifate/jundi.png'
20180219 15:28:01 error display: ~BLIT(): image not found: 'hits/blade-3.png'
20180219 15:28:02 error display: ~BLIT(): image not found: 'units/undead-skeletal/revenant-dying-7.png'
20180219 15:28:02 error display: unknown image function in path: DARKEN
20180219 15:28:02 error display: could not open image 'projectiles/nagas_merman.png'
20180219 15:28:02 error gui/draw: Image: 'projectiles/nagas_merman.png' not found and won't be drawn.
20180219 15:28:32 error addons-client: add-on 'Gweddyn_the_Ruler' has an icon which cannot be found: 'units/player/rulerking.png~RC(magenta>green)'
20180219 15:28:32 error addons-client: add-on 'Water_Era' has an icon which cannot be found: 'projectiles/nagas_merman.png'
20180219 15:28:36 error addons-client: add-on 'Gweddyn_the_Ruler' has an icon which cannot be found: 'units/player/rulerking.png~RC(magenta>green)'
20180219 15:28:36 error addons-client: add-on 'Water_Era' has an icon which cannot be found: 'projectiles/nagas_merman.png'
20180219 15:28:56 error addons-client: add-on 'Gweddyn_the_Ruler' has an icon which cannot be found: 'units/player/rulerking.png~RC(magenta>green)'
20180219 15:28:56 error addons-client: add-on 'Water_Era' has an icon which cannot be found: 'projectiles/nagas_merman.png'
20180219 15:29:42 error addons-client: add-on 'Gweddyn_the_Ruler' has an icon which cannot be found: 'units/player/rulerking.png~RC(magenta>green)'
20180219 15:29:43 error addons-client: add-on 'Water_Era' has an icon which cannot be found: 'projectiles/nagas_merman.png'
20180219 15:29:49 error addons-client: add-on 'Gweddyn_the_Ruler' has an icon which cannot be found: 'units/player/rulerking.png~RC(magenta>green)'
20180219 15:29:49 error addons-client: add-on 'Water_Era' has an icon which cannot be found: 'projectiles/nagas_merman.png'
20180219 15:41:20 warning engine: User Bonobo has unknown game_id: 72
20180219 15:41:31 error lobby: Room window not open in add_room_window_message for lobby
20180219 15:41:32 error lobby: Room window not open in add_room_window_message for lobby
20180219 15:44:12 warning engine: User Rears has unknown game_id: 73
```

**Comment by sapientN3T** [comment]
Ok, not sure what's going on, but now it shows the Era name... in Russian. I do not speak Russian. So that doesn't really help me. Join and Observe are still disabled.

![2018-02-19 16_09_47-the battle for wesnoth - 1 13 11](https://user-images.githubusercontent.com/19386345/36367892-b62f2cc8-158f-11e8-819d-57ab7f5dff58.png)

**Comment by gfgtdf** [comment]
> So, in other words, there's no way for me to know what era I am missing or get its required add-on.

> Join and Observe are still disabled.

hmm this shouldn't happen, even if you don't have the era installed it should still be possible and give you an option to autmaticially download all required addons from the addon server.

**Comment by sevu** [comment]
> hmm this shouldn't happen, even if you don't have the era installed it should still be possible and give you an option to autmaticially download all required addons from the addon server.

works currently only with doubleclick on the game afaik

**Comment by Vultraz** [comment]
I've seen this before, but I can't repro it anymore on master.

**Comment by Vultraz** [comment]
Observe being grayed out fixed in a86bd3149fb1.

**Comment by sevu** [comment]
I think I saw this too short before 1.13.11, once there being (missing) shown for the Era, and at some later time, while testing something else, there suddenly was the name of the missing era. (With no new compiles in between)

**Comment by Vultraz** [comment]
Do you still see it on current master?

**Comment by Vultraz** [comment]
Closing since @ProditorMagnus reported correctly seeing the name of a missing era using 1.13.12.
