### ISSUE TITLE
[heal_unit], amount=0, animate=yes shows floating zero

### ISSUE THREAD

**Issue by Kwandulin** [wesnoth/wesnoth#2530]
Using [heal_unit] with amount=0 and animate=yes, shows a green zero that is floating upwards. I suggest to change it so, that no floating text is shown, when amount=0, just like it was in previous versions.

**Comment by Vultraz** [comment]
Can go into 1.14.0, I think.

**Comment by Vultraz** [comment]
Should we disable animations completely if there's no healing (amount is 0)?

**Comment by Kwandulin** [comment]
I use it as a shortcut for the blink and sound effect. Is there an alternate way to do that?

**Comment by jyrkive** [comment]
The blink and sound effect are a part of the animation. Disabling the animation would also disable them.

I think you can trigger the other effects but not the text with this Lua code:

```lua
local animator = wesnoth.create_animator()
animator:add(u, 'healed', 'hit', {})
animator:run()
```

**Comment by CelticMinstrel** [comment]
I think if there's no damage healed, the _logical_ outcome would be to get a healing animation (assuming you have a healer) but no healed animation?

**Comment by Vultraz** [comment]
@CelticMinstrel I'll leave it to you to decide.

**Comment by CelticMinstrel** [comment]
So, in this case, there are several possible behaviours I can think of:

1. Do nothing. No healer animation, no healed animation.
2. Play the healer animation but not the healed animation.
3. Play both animations, but without the floating text.
4. The current behaviour.

The fourth option is the only one that doesn't make sense, in my opinion. The second kinda doesn't make much sense either, and in any case it can easily be done with an `[animate_unit]` tag instead, if desired. The third option is also possible with an `[animate_unit]` tag, actually.

So I guess the answer really comes down to... what's the _purpose_ of the tag? Is the purpose to _heal units_, or is the purpose to _show an animation_? According to the wiki, it's the latter. So, given that options 2 and 3 (and even 4!) are possible with a different tag, I think it actually makes the most sense to take option 1.

Any other opinions?

**Comment by jyrkive** [comment]
My preference out of those options is option 4. It makes it clear that there was an attempt to heal the unit, but it didn't do anything because the unit was already at maximum HP.

**Comment by soliton-** [comment]
I'd restore 1.12 behaviour (option 2 or 3?) since there does not seem to be consensus on another option being strictly better/more sensible. Less work for add-on authors.

If we do want to change then I agree that option 1 would be preferable if the other options can be done anyway if the author wants.

**Comment by Vultraz** [comment]
My commit above implements option 2.

**Comment by Vultraz** [comment]
Closing since we've gotten no additional feedback.

**Comment by CelticMinstrel** [comment]
...I really hate the idea of closing an issue simply because there has been no feedback for some period of time. I've seen Epic doing it numerous times, and it really just gives an illusion that you have fewer issues than you really have.

**Comment by Vultraz** [comment]
Except this is not a case of closing an issue because we didn't receive feedback and couldn't fix the bug. It's a case of we fixed the bug, and received no further feedback on the fix.

**Comment by CelticMinstrel** [comment]
I guess that's true, sure.
