### ISSUE TITLE
Reloaded MP games aren't renameable

### ISSUE THREAD

**Issue by wesnothmint** [wesnoth/wesnoth#2534]
It's no longer possible to set a new game title when reloading mp saves. This used to be possible in Wesnoth 1.10.x but as of 1.12.x every reloaded game gets named <player's> game. It'd be handy to get this back for reloading tournament games and a few other things.

**Comment by Vultraz** [comment]
The above commit doesn't allow setting a *new* title when reloading a game, but it does preserve the original one. I think that's sufficient. If you really think setting a new title is important, I'll reopen and do some more work. But the immediate issue is fixed.

**Comment by ProditorMagnus** [comment]
Maybe have this issue open (and remove assignment) so it is more visible. However, original title is very good default, so it is low priority and solution would just allow changing original title, while still keeping it as default.

**Comment by Vultraz** [comment]
I don't think it's worth making them renamable. Given the current workflow such a thing would be non trivial. Won't fix.

**Comment by CelticMinstrel** [comment]
I think making them renamable would be nice to have but is low priority.
