### ISSUE TITLE
In-game chat not displayed for player 2

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2546]
Seen with local builds from both the tagged 1.13.11, and on a local branch based on bf8c1b90bf2099bf6df0cc01290d893951c451fb. This was on the official server, testing with multiple instances of the same build.

2 players in a game, both of them writing chat messages:

* At the top-left of the screen, player 1 sees all the conversation
* At the top-left of the screen, player 2 sees only what they say themselves
* For both players, opening the chat log window shows all messages, including the ones that didn't appear at the top-left of the screen

4 players and one spectator, p1 allied with p4, p2 allied with p3, all of them writing chat messages (tested with the tagged 1.13.11 only):

* At the top-left of the screen, p1, p3 and the spectator see all messages
* At the top-left of the screen, p2 sees only the messages from themselves
* At the top-left of the screen, p4 sees only the messages from themselves
* For all players, opening the chat log window shows all messages, including the ones that didn't appear at the top-left of the screen
* p2 and p4 quit, rejoin and are given back control of their original sides. Now they see all messages at the top-left.

**Comment by gfgtdf** [comment]
couldn't reproduce using 1.13.11 official windows build windows using local wesnothd.exe also from official 1.13.11 windows release

**Comment by stevecotton** [comment]
The bug only happens if you have quick replays enabled, and joined the game when it was still being created, and aren't the host. With that combination, the chat message reaches do_replay_handle() and gets as far as the line below, where `is_skipping_replay()` returns true.

    replay.cpp:732    if (!resources::controller->is_skipping_replay() || is_whisper)

It seems the 4 player game in the original bug report was misleading - p3 was another player, I guess they had quick replays disabled. The spectator might have joined after the game started.

**Comment by gfgtdf** [comment]
hm ok thne the bug here is that is_skipping_replay() returns true when it shouldn't . It will the probably also casue other bugs like animations not beeing shown.

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/commit/289ec41e86a30da61d908a558fad10ee1a512a88

**Comment by stevecotton** [comment]
@gfgtdf 's fix looks good to me.
