### ISSUE TITLE
Update the manual

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2551]
@shikadiqueen just pointed out that the manual hasn't been updated for any of the new 1.13.x UI changes. This _should_ have been done before the string freeze, but apparently it slipped everyone's minds.

I hate to break the string freeze, but this is actually very important, in my opinion. I propose that we prioritize it right away so that it can be ready well before 1.13.12 is released. That way, translators can be told that the string freeze applies to everything _except_ the manual, and the freeze for the manual will start in 1.13.12.

The alternative is shipping 1.14 with an out-of-date manual. I personally don't consider this an acceptable option, but perhaps someone might disagree.

**Comment by jyrkive** [comment]
I granted a string freeze exception and sent an email about it to the i18n mailing list.

(For some reason, it doesn't show up in the archives, but @AI0867 confirmed in IRC that he received it.)

**Comment by jyrkive** [comment]
Done as of commit 8f8a7b7585e287ad3cf8322351bca3015b4010a5.
