### ISSUE TITLE
DescriptionWML used to be accepted in [multiplayer_side]name

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2554]
According to the wiki, the `name` attribute in `[multiplayer_side]` used to accept the old-markup DescriptionWML, which allows specifying an image and a second column of text in the dropdown menu in MP Staging. While the image part is useless (it wouldn't be team-coloured and there was an alternate way to specify an image), the second column is still useful.

It wouldn't necessarily need to use the new DescriptionWML format. Merely adding a `description` attribute is probably sufficient. Since the dropdown menu no longer exists, it could be displayed in the FLG dialog. While the original implementation would've added a column, we need not even mimick that; it could instead be displayed under the name in a smaller font, for example. Compatibility support for the old DescriptionWML would also be needed.

I'm posting this because it's a regression, but I don't consider it a blocker or high priority. I'd be open to closing this if there's a consensus that the regression isn't important, but I'm also willing to do the implementation myself, so please don't make arguments based on "that's too much work" or anything like that. Even if we decide to close this, we must at least parse DescriptionWML if it's found in the `name` key.

**Comment by Vultraz** [comment]
Stating for the record that I am absolutely opposed to adding another column or row to the Faction Select dialog (the only place where the `[multiplayer_side]` (ie, faction) selection now appears. The dropdown displayed for the host in 1.12 is no longer present.

**Comment by Vultraz** [comment]
Also, relevant: #2004

**Comment by gfgtdf** [comment]
afaik `[multiplayer_side]` does alreaedy support `description` which contains the helpwml for that faction. I'm also opposed to addding a second column.

**Comment by CelticMinstrel** [comment]
If @gfgtdf is correct and it was only ever used for the image, that's certainly relevant to the importance of this issue. We could grep the addons server to see whether it's ever used for a second column.
