### ISSUE TITLE
Credits no longer show up in the help

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2555]
One of the entries in the help window is the credits. However, they no longer work. Either that should be fixed, or the entry should be removed.

While this is a regression, it doesn't strike me as important since the credits screen is actually better for viewing the credits than the help screen.

**Comment by shikadiqueen** [comment]
Appears to have been introduced by commit 476027f239f2c86169ad088bbfe6024c0ad2d1f6.

**Comment by Vultraz** [comment]
I removed it in help since I couldn't figure out how to get it displaying again. But then I never went back to it. And now if I try to remove its `[topic]` from help.cfg nothing displays in help at all.
