### ISSUE TITLE
OOS in multiplayer when [modify_side] changes a controller during "side_turn_end" event.

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2563]
if a code like 
```
[modify_side]
  side = $($current_side + 1)
  controller=human
[/modify_side]
```
is executed during an "side_turn_end" OOS can happen (assumng that side was previously null-controlled)
What happens is that the [end_turn] command is sended to the server before that event is executed and the server updates the current_player_ field when it recieves [end_turn]. So what happens on the server is that a the time when current_player_ filed is updated the next side is skipped becasue it is empty, on the clients however current_side_ is updated after the 'side_turn_end' event has finished so the next side will not be skipped since modify_side activated it.

**Comment by soliton-** [comment]
Is this likely to happen/be wanted? Perhaps it‘d be enough to document the issue on the wiki.

**Comment by gfgtdf** [comment]
well before 1.13.2 (2d80c97b1359ba893e04c646cbad73894a6d055f) we lived fine without support for [modify_side] controller= in mp at all unrelated to in which event it happens, so this is clearly not a blocker. I still think it'd be nice to have it since there is no reason why using it in turn end event would not make less sense than in any otzher events.


I also didn't fiund any cases in mainline campaign that ere effected by it (i did find a possible invalid [filter] in https://github.com/wesnoth/wesnoth/blob/1.13.11/data/campaigns/Two_Brothers/scenarios/02_The_Chase.cfg#L423)

**Comment by Vultraz** [comment]
@gfgtdf that filter seems to work fine... odd... the wiki doesn't say `[filter]` is accepted under `[modify_side]`.

**Comment by CelticMinstrel** [comment]
The filter tag is used to match which sides to modify. Without it it would be impossible to distinguish the filter keys from the change keys.

**Comment by CelticMinstrel** [comment]
(But if there's no filter tag the side key is supposed to be used instead.)
