### ISSUE TITLE
Take campaign abrev into account for searches in the add-on manager.

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2565]
It would be neat if besides the title, description and dependencies (not sure if this really already happens) the campaign abrev also would be matched against the keyword. Sometimes you have old savefiles and wonder what add-on you need to download to load them again.

However, I guess it's not so easy, since the information so far is from the _server.pbls, while the campaign abrev is just in the add-in files.

**Comment by shikadiqueen** [comment]
Would allowing add-on authors to specify the add-on's abbreviation -- regardless of the add-on type -- be an acceptable solution?

**Comment by CelticMinstrel** [comment]
Another possibility is supporting a `keywords` attribute in the pbl.

**Comment by shikadiqueen** [comment]
The answer on Discord was positive, so I'm closing this issue.
