### ISSUE TITLE
Login with registered nick is broken on trunk

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2568]
Login with current master onto dev MP server works.

**Comment by jyrkive** [comment]
Can you elaborate? Is there a difference between "trunk" and "dev"?

**Comment by sevu** [comment]
The dev server is for clients with 1.13.x and runs on port 14997, clients with 1.13.x-dev connect to a separate trunk server. (I think it runs on port 15000, but redirects other clients to other ports)

The bcrcpt branch has been merged recently.
It surprises me that I can still login on port 14997 with both current master and 1.13.11

**Comment by jyrkive** [comment]
@loonycyborg You implemented bcrypt support. Can you investigate?

**Comment by ProditorMagnus** [comment]
For me login with remembered password has been broken for dev for both 1.13.10 and 1.13.11 - autofilled password is not accepted, but after deleting credentials file and doing full reload, I can get in. Havent tried any +dev versions after 1.13.8+.

**Comment by jyrkive** [comment]
@ProditorMagnus Sounds like a separate bug. Please file a new bug report.

**Comment by jyrkive** [comment]
From IRC:

> [16:19:34] \<loonycyborg\> JyrkiVesterinen: Soliton: this issue seems to have disappeared after I restarted it
> [16:19:59] \<Soliton\> ah, maybe because of the db container upgrade.
> [16:20:25] <loonycyborg> maybe, it could have moved connection to invalid state

@sevu Please test if you can connect to the trunk server now.

**Comment by GregoryLundberg** [comment]
Please do __*NOT*__ make *any* changes to the MD5 or Bcrypt functions, or anything having to do with passwords in wesnothd, campaignd or the wesnoth client.

I am in the process of auditing the code and collecting needed repairs.

I have been extensively testing with a local server. If there are issues with logging into the official servers, a restart will likely solve it.

At present, there is *no* way to test bcrypt password hashing on the official server without updating your password on the Forums and, thus, losing all multi-player access to any version of Wesnoth prior to 1.13.11 on the official servers.

**Comment by sevu** [comment]
Works now.

**Comment by shikadiqueen** [comment]
In case anyone is confused by @GregoryLundberg's statement at the end of his post above, it is safe to update your password in the forums right now. He means a different thing entirely that is not enabled in production.

**Comment by GregoryLundberg** [comment]
I said, "no way to test" meaning just that .. not enabled.

Which is why I'm running a local copy to test password handling: since it's mine, I can set up users with each form of MD5 and Bcrypt password hashing, including forms we don't support, but which might appear if one uses PHP (or phpMyAdmin or MySQL Workbench) to replace, supplement, or bypass, phpBB user authentication.
