### ISSUE TITLE
Some hexes can incorrectly act as impassable

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#2571]
Reported in the forums:
https://forums.wesnoth.org/viewtopic.php?f=4&t=47782
https://forums.wesnoth.org/viewtopic.php?p=624042#p624042

**Comment by sigurdfdragon** [comment]
Maybe this is some sort of cache corruption issue?

**Comment by gfgtdf** [comment]
ok i was somehow able to create a testign scenario
```
[multiplayer]
	id=multiplayer_test
	name=multiplayer_test
	map_data = "Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg
Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg
Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg
Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg, Ch, Ch, Gg, Ch, Ch, Gg, Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg
Rr^Vhc, Rr^Vhc, Rr^Vhc, 1 Kh, Ch, Gg, Gg, Gg, Ch, 2 Kh, Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg
Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg, Gg, Ch, Gg, Ch, Gg, Gg, Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg
Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg
Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg
Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Rr^Vhc, Rr^Vhc, Rr^Vhc, Gg"

    {DEFAULT_SCHEDULE}
	{DEFAULT_MUSIC_PLAYLIST}
	
	
	
    [side]
        side=1
        controller=human
    [/side]
    [side]
        side=2
        controller=human
    [/side]
	[event]
		name = "start"
		[lua]
		code = <<
			u = wesnoth.get_units({ side = 1})[1]
			print(u:movement("Hh^Kov"))
			wesnoth.set_terrain(2, 2, "Hh^Kov")
		>>
		[/lua]
	[/event]
[/multiplayer]
```

Note that this testing scenario might not work if you have addons installed, it's quite what happens the the case of that testing scenario, not sure yet how it happens in Liberty or other maps.

**Comment by gfgtdf** [comment]
ok i think there are 2 probably bugs involved here, on is the one from the example above (basicially terrain_type_data::underlying_mvt_terrain not calculating the result if it is not cached), but i'd rather liek to actually see the other one fixed first (probably something like someone calling mevement_costs with uninitialized parameters).

**Comment by gfgtdf** [comment]
ok problem solved, the 'bad' commit is https://github.com/wesnoth/wesnoth/commit/a2be9c8f86690974d98f7a34c85c54496097185c and just fixing what i said above shodul solve it
