### ISSUE TITLE
Macro definitions for cores

### ISSUE THREAD

**Issue by adramolokh** [wesnoth/wesnoth#2580]
Running Wesnoth 1.13.11, 4c8b3ed-Clean, Arch Linux x86_64 with Linux 4.15.6-1.

[Core wiki-page](https://wiki.wesnoth.org/CoreWML), [core thread](https://forums.wesnoth.org/viewtopic.php?f=6&t=40415).

Unlike eras, multiplayer scenarios and campaigns, cores appear to lack a specific macro defined only when they're currently being used as the main core. This means that a core's files are always loaded: in my core, this causes there to be two copies of every campaign in my core, two copies of every advanced preference used in my core (which I need to include at least one of to prevent crashes), and likely two copies of several other things that I've yet to find out about.

**Comment by CelticMinstrel** [comment]
A few comments...

* It's my understanding that _core.cfg_ is loaded first, which then sets the path to be loaded for the main game config.
* Some of the things in the main game config shouldn't really be customizable, mainly the advanced preferences; possibly also the default hotkeys. In my opinion, these should always be loaded no matter which core you're on.

Look in _game_config_manager.cpp_ for how core loading works.

**Comment by sevu** [comment]
I updated the wiki page on how to load cores, I assume you did something different. IIRC I had as well redefinition warnings while I tried to figure out how to load a custom core.

- Have the [core] in cores.cfg, this file be called like that. Don't source that file from a _main.cfg or somewhere (cores are loaded earlier and different than other UMC)
- specify a path to a file or directory, using `/_main.cfg` (that's the _main.cfg in /data) is the same what the default core does.
- Best copy that file and adjust it to your needs. Note that the paths used in that file are absolute, so they load mainline stuff even when you copied it to your add-on. One can as well use relative paths with `{./blah}` though you will still want a lot of things from mainline (e.g. the AI).

**Comment by CelticMinstrel** [comment]
Linking this to #3702.

**Comment by sevu** [comment]
This quote from the linked thread seems to describe what happened:
> Wesnoth looks in every add-on's toplevel directory and reads the _main.cfg from there.
If this file includes your whole core then it is loaded every time.
Make sure your toplevel _main.cfg does not do that.
