### ISSUE TITLE
Units hidden with [hide_unit] on scenario end will be hidden in the next scenario

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2590]
Regression from 298b4486cd55b799c301461ed8e0e2da0858726c. This didn't happen before since the `hidden=` attribute wasn't serialized. Since I made the above commit to address hidden units becoming visible on save reload, I see two possible solutions:

- Revert the above commit and let UMC authors continue to use the set-hidden-in-an-on-load-hook-if-they-need-it hack.
- Reset all units' `hidden` status when transitioning to the next scenario.

Not sure which is better.

**Comment by gfgtdf** [comment]
i think both are accepotable and rather easy to implement. The advantage of (2) is that hidden status would still be preserved during saveload, one advantage of (1) might be that it also applies to umc-implemented recall list (store all units at end of scenario and unstore them in some later scenario).


That said, as noted in https://github.com/wesnoth/wesnoth/issues/1357#issuecomment-299798847 hidden was originaly not meant ot be a 'persistent status' just a tool for mid event animations, that's probably also it was not presistent in savefiles before.

**Comment by Vultraz** [comment]
Where would one look to implement 2?

**Comment by gfgtdf** [comment]
one option would be https://github.com/wesnoth/wesnoth/blob/master/src/carryover.cpp#L35 which happens quite late the other option would be https://github.com/wesnoth/wesnoth/blob/master/src/playsingle_controller.cpp#L301 which happens before linger mode iirc.

**Comment by Vultraz** [comment]
I went with option 2. Thanks!
