### ISSUE TITLE
Map editor icons problem

### ISSUE THREAD

**Issue by dust5114** [wesnoth/wesnoth#2598]
If font scaling is set to more than 110 %, then  tool icons disappear  in windowed mode. In fullscreen problems start at 145% of font scaling, but at 115% some map "toggle view" controls disappear. 
Version 1.13.11, Win 8.1, installed from prebuild installer.

**Comment by dust5114** [comment]
Version  1.13.11

**Comment by CelticMinstrel** [comment]
This can probably be counted as affecting the game too? Though it may not be as bad there.

**Comment by dust5114** [comment]
@CelticMinstrel  Yes,  i looked at the game, same thing  with  map toggle icons if  using default theme.

**Comment by Vultraz** [comment]
This has something to do with how GUI1 widgets calculate their sizes with zoom on, which then affects the size of the overlay image they try to load.

**Comment by CelticMinstrel** [comment]
I wouldn't expect GUI1 to take font scaling into account when loading images, so if that's the cause, maybe that should be changed.

**Comment by Wedge009** [comment]
This seems to be duplicate of #1604, albeit for editor buttons instead of the mini-map.

**Comment by Wedge009** [comment]
No further input, closing in favour of #1604, this discussion can apply there too.
