### ISSUE TITLE
Entering tile bug

### ISSUE THREAD

**Issue by dust5114** [wesnoth/wesnoth#2599]
Sometimes  some units can't enter  in  villages  or grassland tiles. Restarting application solves this issue, simple reload doesn't.  It's hard to reproduce, so may be  there are some logs that i can send  of current map state when this happens?
Version 1.13.11, Win 8.1,  prebuild installer.
![cant enter](https://user-images.githubusercontent.com/37002913/36988225-0d122672-20a7-11e8-8a4c-1a0e59601cc6.png)

**Comment by stevecotton** [comment]
This sounds like #2571, already fixed by #2577.
