### ISSUE TITLE
Add-ons client: UI element for displaying add-on tags

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#2601]
#2592 adds the `tags=` attribute to add-ons server entries and .pbl WML. While this is used by the Filter textbox without any additional changes right now, it could be useful for people to be able to directly see the tags on the Add-ons Manager.

This is not doable at the moment because of the string freeze, but it's a trivial addition that could be considered for version 1.14.1.

**Comment by stevecotton** [comment]
While tags can be free text, I think we should define a "standard" set of tags that get translated in one of core's textdomains.

**Comment by stevecotton** [comment]
Done in #5774.
