### ISSUE TITLE
Crash in 1.13.11 when opening Preferences

### ISSUE THREAD

**Issue by dleducq** [wesnoth/wesnoth#2612]
Hi,
I've got a (systematic) crash in BfW 1.13.11 (already in 1.13.10, did'nt try previous dev versions), when accessing the Preferences in main menu screen.
After investigation, this is due to the line :
`compress_saves=no`
in the preferences file (inherited from  

1.12), replacing it with 
`compress_saves="none"`
solved the problem...

I tried (and again) to join my preferences file and a backtrace, after compressing them with gzip, but it doesn't work : 
"Something went really wrong, and we cant process that file. Try again."

`The Battle for Wesnoth version 1.13.11
Running on Fedora release 27 (Twenty Seven)

Game paths
==========

Data dir:        /usr/share/wesnoth
User config dir: /home/dleducq/.config/wesnoth
User data dir:   /home/dleducq/.local/share/wesnoth/1.13
Saves dir:       /home/dleducq/.local/share/wesnoth/1.13/saves
Add-ons dir:     /home/dleducq/.local/share/wesnoth/1.13/data/add-ons
Cache dir:       /home/dleducq/.cache/wesnoth

Libraries
=========

Boost:             1.64
OpenSSL/libcrypto: 1.1.0g  (runtime 1.1.0g)
Cairo:             1.15.10 (runtime 1.15.10)
Pango:             1.40.13 (runtime 1.40.13)
SDL:               2.0.7   (runtime 2.0.7)
SDL_image:         2.0.2   (runtime 2.0.2)
SDL_mixer:         2.0.2   (runtime 2.0.2)
SDL_ttf:           2.0.14  (runtime 2.0.14)
libpng:            1.6.31  (runtime 1.6.31)

Features
========

Experimental OpenMP support:    no
PNG screenshots:                yes
Lua console completion:         no
Legacy bidirectional rendering: yes
D-Bus notifications back end:   no
`

**Comment by dleducq** [comment]
OK, got it, it was a script blocking problem...


[backtrace.gz](https://github.com/wesnoth/wesnoth/files/1792833/backtrace.gz)
[preferences.gz](https://github.com/wesnoth/wesnoth/files/1792835/preferences.gz)

**Comment by Vultraz** [comment]
`gui/dialogs/preferences_dialog:691`. It attempts to match the field with value "no" for an initial selection and can't find it. Not sure how to alias the IDs...

**Comment by gfgtdf** [comment]
> Not sure how to alias the IDs...


i don't think we need to, just make sure it falls back to it's default value instead of crashing should be good enough.
