### ISSUE TITLE
Appdata file: New screenshots before 1.14.0 is tagged

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2614]
Unlike the steam page or the forum announcement, the appdata file belongs to the tagged stuff.
The links to the screenshots must be updated before the final 1.14.0 tag.
_The images can be uploaded later if the link name is known (and updated) in advance._

Technical stuff:
- 16:9 format (unlike the ones currently used. Screenshots in a different format lower the score in the software centre)
- minimum width: 620 px
- png or jpg, preferably png
- not all images must have the same size, software centres can adjust
- Should be 5 or more images. At least that looks good in Gnome's software centre
- In Gnome's software centre the images are listed the same order as in the file (Unless using `<caption>`, then they are ordered alphabetically, and depending on the language that may be different. We don't use that currently.)
- The `with=` and `height=`attributes are optional

Edit: one can run `appstreamppstream-util validate-strict *.appdata.xml` and see if there are lines like
aspect-ratio-invalid  : <screenshot> aspect ratio not 16:9 [https://www.wesnoth.org/images/sshots/wesnoth-1.13.7-2.jpg]

**Comment by Vultraz** [comment]
Placeholder links added in 8044bb512eb3cb1bcc992fc17263f0175a5d828f.
