### ISSUE TITLE
UI : size of component in list has changed;

### ISSUE THREAD

**Issue by alain-bkr** [wesnoth/wesnoth#2628]
I upgraded wesnoth engine (from 0bc03e14c749699b7dfee mid-february) to current ( 11d48f16390266 ,march 9th)

In LotI extension, lists are used ,and now they have a very odd looking : 
* all lines have the same height (the size of the biggest element in the list) 

I eported this in https://github.com/Dugy/Legend_of_the_Invincibles/issues/79
 

![](https://user-images.githubusercontent.com/31039036/37243572-020fa988-247c-11e8-9c0e-c03bf1a194ba.png)

**Comment by CelticMinstrel** [comment]
@Vultraz - Here's a good reason _not_ to do that, eh?

**Comment by Vultraz** [comment]
Leave it to LotI to do something ridiculous like using an image that huge...

**Comment by stevecotton** [comment]
Here's an (IMHO) more reasonable example from SXC's shop.
![wesnoth_lists_2628](https://user-images.githubusercontent.com/101462/37249026-41d928d8-24df-11e8-9e73-3e792adabeda.png)
