### ISSUE TITLE
segfault during opponent's turn

### ISSUE THREAD

**Issue by alain-bkr** [wesnoth/wesnoth#2629]
I upgraded wesnoth engine (from 0bc03e14c749699b7dfee mid-february) to current ( 11d48f16390266 , march 9th)

With Loti extension (i have not tested other games) , there is a segfault very quickly, during opponents trun (while ttacking one of my units).
This happens very often at the first turn.

I attached the backtrace in gdb.
https://github.com/Dugy/Legend_of_the_Invincibles/files/1799487/20180309.segfault.txt

I reported this in https://github.com/Dugy/Legend_of_the_Invincibles/issues/80 

[LotI1-Revolution Begins-Sauvegarde automatique16.gz](https://github.com/wesnoth/wesnoth/files/1799852/LotI1-Revolution.Begins-Sauvegarde.automatique16.gz)

**Comment by gfgtdf** [comment]
conidering the date, it's probably a dublicate of #2615

**Comment by gfgtdf** [comment]
fixed
