### ISSUE TITLE
LoW persistent data not being saved at the end of chapter 2

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2637]
In multiplayer mode, the LoW campaign has multiple start points, and some persistent storage that stores the characters at the end of a chapter, so that a new game starting from the next chapter starts with those stats. Testing on trunk (ab354737ef6bea42d439671752435f0166f0e004) it seems that the persistent storage at the end of chapter 2 isn't created.

Starting chapter 2 and using ":n" to complete each scenario until reaching chapter 3 doesn't create a file in the persistent saves directory (on Linux, it's a directory called "persist").

Doing the equivalent steps on chapter 1 works on trunk, and doing the same steps on 1.12.6's chapter 2 works.

**Comment by gfgtdf** [comment]
> Doing the equivalent steps on chapter 1 works on trunk, and doing the same steps on 1.12.6's chapter 2 works.

this suprised me , did you also check that the fiel actuall contains the correct contents (that is, kalenz and landars side)?

**Comment by stevecotton** [comment]
> > Doing the equivalent steps on chapter 1 works on trunk, and doing the same steps on 1.12.6's chapter 2 works.

> this suprised me , did you also check that the fiel actuall contains the correct contents (that is, kalenz and landars side)?

The 1.12.6 chapter 2 file contains only Kalenz (but debugging I hadn't recruited), it does not contain Landar. I didn't check that earlier, does it fit what you expected?

**Comment by gfgtdf** [comment]
> The 1.12.6 chapter 2 file contains only Kalenz (but debugging I hadn't recruited), it does not contain Landar. I didn't check that earlier, does it fit what you expected?

Yes, in particular it means that it didn't really work on 1.12 eigher. If you want to try to fix it: here https://github.com/wesnoth/wesnoth/blob/1.13.11/data/campaigns/Legend_of_Wesmere/scenarios/chapter2/08_Council_of_Hard_Choices.cfg#L144 it tries to sotr all persitent sides, but that scenario does not ahve any persistent sides (probably since its just a cutscene scenairo)

**Comment by stevecotton** [comment]
Now you've written it like that, it's quite easy to fix the main bug - just do the save at the end of the previous scenario (PR will be opened in soon).

However, this leaves some smaller details which have already been split in to a separate bug, #2638.
