### ISSUE TITLE
LoW incomplete persistent data at the end of chapter 3

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2638]
The l3_store_kalenz and l3_store_landar variables aren't part of the sides (see the description of the save mechanism in #2637). These variables aren't stored at the end of chapter 3, which means all non-loyal level 3 elves from chapter 2 don't turn up in chapter 4.

**Comment by gfgtdf** [comment]
it's quite unclear to me how it is supposed to work, are those l3_store_kalenz/l3_store_landar varaibles actualyl created anywhere (in sp or mp), and where exactly are those non-loyal level 3 units removed?

**Comment by stevecotton** [comment]
They're created at the start of chapter 3, in a macro which means that you'll find it by grepping for "l3_store_" but not if you grep for either of the complete variable names.

https://github.com/wesnoth/wesnoth/blob/ab354737ef6bea42d439671752435f0166f0e004/data/campaigns/Legend_of_Wesmere/scenarios/chapter3/09_Bounty_Hunters.cfg#L238

**Comment by gfgtdf** [comment]
so this only appears when using the 'start from chapter' feature right? the proper fix wouidl probably just to store a copy of that variable that variable along with the sides units.


afaik another issue with the 'start from chapter' feature is that olurfs units are not preserved, in scenario 2 you play with an allied olurf whose units gets carried over to the next map where you ahve him as ally and finally to a later scenario when you can ocnotrl him, with probably down't work when startiong from later chapter too.

**Comment by stevecotton** [comment]
Please would someone with labelling permissions add the "low-priority" label?

I separated from the other two LoW issues so that those other ones could be closed; and now I see that I rushed yesterday and didn't put that in the original description. It only appears when using the "start from chapter" feature.

**Comment by singalen** [comment]
Is this something related? https://github.com/singalen/wesnoth/issues/90
If so, makes it pretty high priority.

**Comment by gfgtdf** [comment]
This is about the mp version of LoW

**Comment by singalen** [comment]
@gfgtdf thanks. So I should report it as a new one?

**Comment by stevecotton** [comment]
I don't know what caused it, nor what fixed it, but something similar to singalen#90 has already been fixed in the 1.14 branch.

See https://forums.wesnoth.org/viewtopic.php?f=51&t=31592&start=15#p628469

Steve (octalot)


-------- Original Message --------

**Comment by nemaara** [comment]
See https://github.com/wesnoth/wesnoth/commit/e7947e348b62ea84b69ace20d90ee5cd108a137e, this should fix this issue.
