### ISSUE TITLE
loading game causes exception if in `--multiplayer` mode

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2648]
Steps to repro:

* Start a scenario from command line:
`wesnoth --multiplayer --era=era_default --scenario="multiplayer_Aethermaw"`
* Press Menu > Back to... > Turn 1

Expected: wesnoth loads game at turn 1

Actually: game silently closes itself, with underlying reason (visible in console):
```
Caught general 'N8savegame19load_game_exceptionE' exception:
std::exception
[Inferior 1 (process 4173) exited with code 01]
```

**Comment by GregoryLundberg** [comment]
`wesnoth --multiplayer` is both necessary and sufficient. The crash does not occur of you start a Local Game from the main menu.

**Comment by sevu** [comment]
Can confirm it too

**Comment by GomesGoncalo** [comment]
Hi all, I was able to reproduce this with the command line multiplayer and opened a pull request that fixes it!
Let me know if anything needs changing in the PR.

**Comment by Zireael07** [comment]
I don't think you opened a PR yet, or at least I can't see anything in my feed - just a single commit on your repo.

**Comment by soliton-** [comment]
It's PR #7904 and it looks good to me.
