### ISSUE TITLE
Lag and stuttering

### ISSUE THREAD

**Issue by TehPlayer14** [wesnoth/wesnoth#2654]
So since I've played Wesnoth back in 2009 not much has changed besides that the game really lags now on greater hardware...

**Comment by gfgtdf** [comment]
> greater hardware

i assume you mean older hardware?

**Comment by jyrkive** [comment]
Which version of Wesnoth are you using?

**Comment by Michal1324** [comment]
@jyrkive  Lastest stable verison 
PC specs:
Win 7 x64
CPU XEON E5-1620 V3 3.5GHz
GPU GTX 980

@gfgtdf I mean newer

**Comment by jyrkive** [comment]
Try Wesnoth 1.13.11 (development release). I have made significant performance improvements in 1.13. This issue may be already fixed. :)
