### ISSUE TITLE
diagonal scrolling with keyboard doesn't work

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2657]
until very recently you could press up+right and the map would scroll up and right at the same time. this doesn't work in latest master, in latest master it will just scroll eigher right or up.

**Comment by Vultraz** [comment]
Blocker?

**Comment by CelticMinstrel** [comment]
Seems like a blocker to me too.

**Comment by jyrkive** [comment]
Commit ecc0dca665737bcb411fbd355edd37df8a9038b8 *shouldn't* have caused it, but it's the most obvious possible culprit.

**Comment by galegosimpatico** [comment]
<sub>Related to this: both horizontal and vertical keyboard scrolling on macOS `1.13.11` have an imperfection by which it _bumps_ forward in the direction you are scrolling to, slightly but noticeably. I don't have a guide to reproduce, but it's quite common, so it is going to be in a matter of time.</sub>

**Comment by Vultraz** [comment]
Hm, yes, I've noticed some regressions related to scrolling too...
