### ISSUE TITLE
filter_self function is invoked twice -- bug?

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2665]
Steps to repro:
* start wesnoth from terminal, so that you see both the terminal and wesnoth window.
* start a new game as side 1 (tested on 1vs1 human-vs-computer random map, no shuffling)
* open Lua console
* type this in:
```
	temp_func = function(unit)
		print("temp_func calculation")
		return true
	end
	unit = wesnoth.get_units {side = 1}[1]
	wesnoth.add_modification(unit, "object", {
		T.effect { apply_to = "remove_ability", T.abilities { T.leadership { id = "science_mod" } } },
		T.effect {
			apply_to = "new_ability", T.abilities {
				T.leadership {
					id = "science_mod",
					cumulative = true,
					name = "s" .. unit.side,
					value = 100,
					affect_allies = false,
					affect_self = true,
					T.filter_self { lua_function = "temp_func" },
				}
			}
		}
```

Now select your leader and hover different tiles. You'll see that for each hovered hex **two** function invocations are being made and logged to console.

Expected: one function invocation for each hovered hex.

Thoughts?

**Comment by jyrkive** [comment]
We aren't giving any guarantees about how often filter functions are called.

**Comment by vgaming** [comment]
@jyrkive wait please. There might be some underlying bug that this test accidentally reveals.

**Comment by vgaming** [comment]
I ask to re-consider and at least see if there's any plausible idea where this might have come from (except underlying logic bugs).

**Comment by Vultraz** [comment]
I agree with @jyrkive here.

**Comment by vgaming** [comment]
From the API perspective, I agree totally. The API works like it says.

The reason I raised the issue is to see whether there might be underlying error that this test accidentally reveals. Well, if developers of the engine do not think it's suspicious I would refrain from pushing it further of course, though that was unexpected.

**Comment by CelticMinstrel** [comment]
I don't think you had a bad idea here; if you can find an actual underlying bug that this is a symptom of, feel free to report that.
