### ISSUE TITLE
Display max_attacks in the unit sidebar

### ISSUE THREAD

**Issue by Kwandulin** [wesnoth/wesnoth#2667]
Since 1.13 we have the option to set max_attacks via [effect]. Unfortunately, it is not displayed, if the unit has more than one attack per turn. It might be reasonable to display the number of attacks per turn in the unit sidebar. 

Maybe we can get something like "Attacks (2)"
![attacks](https://user-images.githubusercontent.com/19636085/37520495-9b096796-291d-11e8-99d5-0eb5f691e5f4.png)

**Comment by CelticMinstrel** [comment]
Also, the movement_used for an attack might be good to show (if different from the default).

**Comment by gfgtdf** [comment]
if this doesn'go into 1.14 coud can also do this in an addon by using luas theme_items hook.

**Comment by CelticMinstrel** [comment]
I think this actually _can't_ go into 1.14 solely _because_ of the `theme_items` hook; there might be a way around that, but it's probably easier to just save it for 1.15.

**Comment by jostephd** [comment]
Added:

![2019-10-18-020135_173x132_scrot](https://user-images.githubusercontent.com/24784687/67060143-3b39dd80-f14b-11e9-83da-3632f7cdf200.png)

<details>

<summary>
test case
</summary>

```
diff --git a/data/scenario-test.cfg b/data/scenario-test.cfg
index 69185e223c9..7531835e766 100644
--- a/data/scenario-test.cfg
+++ b/data/scenario-test.cfg
@@ -253,27 +253,16 @@ Xu, Xu, Qxu, Qxu, Ql, Ql, Ql, Xu, Xu, Xu, Xu, Xu, Xu, Xu, Xu, Gg, Gg, Gg, Gg, Gg
             generate_name=yes
             [modifications]
                 [trait]
-                    id=feral
-                    availability="musthave"
-                    male_name="feral"
-                    female_name="female^feral"
-                    description="Receive at most 40% defense in villages"
-                    [effect]
-                        apply_to=defense
-                        replace=yes
-                        [defense]
-                            village=-60
-                        [/defense]
-                    [/effect]
-                [/trait]
-                [trait]
                     id=overpowered
                     name="overpowered"
                     availability=musthave
                     [effect]
                         apply_to=attack
-                        increase_attacks=1
-                        increase_damage=1
+                        set_movement_used=2
+                    [/effect]
+                    [effect]
+                        apply_to=max_attacks
+                        increase=1
                     [/effect]
                 [/trait]
             [/modifications]
@@ -1565,6 +1554,7 @@ My best advancement costs $next_cost gold and I’m $experience|% there."
     [event]
         name=start
 
+        {UNIT 2 (Orcish Grunt) 14 7 ()}
         [gold]
             side=1
             amount=1000
```

</details>

@CelticMinstrel Could you explain why you think this isn't backportable? If someone replaces or wraps wesnoth.theme_items.unit_weapons, then...what?

**Comment by CelticMinstrel** [comment]
I think it's not backportable because I expected it would be adding a new element to `wesnoth.theme_items`... if that's somehow not the case, then maybe it _can_ be backported?

**Comment by jostephd** [comment]
It just adds another line to the existing `unit_weapons` report: f973919fdcc97d27e669a8e2b5659c1df2913e3f

**Comment by CelticMinstrel** [comment]
Yeah okay... in that case, I'd say it's backportable.

**Comment by jostephd** [comment]
Need to backport ad0867fa4206b237b45d4059ac9a74a034859719 too for the `#include`.

**Comment by stevecotton** [comment]
Will probably need work for the sidebar changes being discussed in https://www.wesnoth.org/irclogs/2021/03/%23wesnoth-dev.2021-03-18.log

**Comment by Wedge009** [comment]
Where does this stand? Probably too late for 1.16.0, but I understand there are no further planned releases for 1.14 so back-porting isn't a concern there.

None of the standard campaigns have units with more than one attack per turn, do they? This is mainly for UMC, right?

**Comment by CelticMinstrel** [comment]
What? Isn't it already done? The commit jostephd linked appears to be on master, at least.

**Comment by Wedge009** [comment]
Sorry, yeah, it does seem to be - I was just focused on all the discussion about back-porting to 1.14 which is no longer relevant. In that case, closing.
