### ISSUE TITLE
Use enter as hotkey for "I'm Ready" button (for small resolution windows)

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2674]
After selecting map where enter works, user can see teams setup screen. That is not possible to skip without using mouse currently, and since map selection and that screen confirm buttons have different locations, mouse is not effective there.

Considering nonlocal mp it might be needed to use ctrl/shift + enter instead.

This is regression from 1.12 where all 3 setup screens have confirm button in same location.

**Comment by ProditorMagnus** [comment]
re #2538

**Comment by Vultraz** [comment]
I deliberately disabled Enter in MP Staging and MP Join Game. I suppose I could re-enable them...

I have no idea what you're saying about non-local MP.

Also, what do the buttons being in different locations have to do with anything? You'd still need to use the mouse to click them. >_<

**Comment by ProditorMagnus** [comment]
It makes sense to not use enter in context where chat is allowed - it would be too easy to accidentally start game there. That is why I mentioned having ctrl or shift with enter to start.

Local mp is when selecting last option after pressing m in main menu, nonlocal is when using any kind of server, no matter if official or localhost. Local mp has no chat, so enter would not have special meaning, so it is free to use for starting there.

Different locations mean that between each click there is need to locate next button, instead of locating button once and then clicking until game has started.

**Comment by CelticMinstrel** [comment]
Yeah, the different button location is quite annoying.

**Comment by Vultraz** [comment]
They are very, very close to each other if you’re in standard resolution and not a lower resolution layout.

**Comment by ProditorMagnus** [comment]
With full screen that is indeed the case, but I prefer to have wesnoth in size that fits 2-3 of those on screen.

**Comment by Vultraz** [comment]
2-3 of what?

**Comment by ProditorMagnus** [comment]
Wesnoth windows.

**Comment by Vultraz** [comment]
You must have a huge monitor O_O

**Comment by ProditorMagnus** [comment]
I keep game size lowest it can be without switching to small UI.

**Comment by Vultraz** [comment]
Well, that's a very unusual usecase. I can move the buttons around on lower resolutions, though.

**Comment by CelticMinstrel** [comment]
There's such limited room in the lower resolutions that it's quite difficult to get the button in the same location in both windows. :(

**Comment by ProditorMagnus** [comment]
Dont see the value to keep this issue open anymore.
