### ISSUE TITLE
support redraw=false for remove_item action

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2675]
The action of adding an item supports a useful key, "redraw":
https://wiki.wesnoth.org/InterfaceActionsWML#.5Bitem.5D

Can we add support for such key in "remove_item", too? Currently it's not being listed as supported on the wiki: https://wiki.wesnoth.org/InterfaceActionsWML#.5Bremove_item.5D

The use case is the same as for the already-existing "item" tag: make many graphics operations in batch and only issue a redrawal after you've done all changes.

**Comment by CelticMinstrel** [comment]
I'd say there's no reason to add the key if its default value is no, because you can always force a redraw whenever you want with the redraw tag.

**Comment by jostephd** [comment]
Yeah, fair enough. I reckon this issue can be closed then?

**Comment by vgaming** [comment]
Please don't close the issue until somebody confirms that [remove_item] does NOT cause redraw.
My issue clearly states that it does, so at some point (17 Mar 2018) I thought that's the current behavior.

Currently I can't test myself at all. If anybody confirms, please close the issue. Otherwise I have this mail "unread" and will return to it later.

**Comment by jostephd** [comment]
I hoped to hear from you. I tested this yesterday by doing a sequence of [item], [remove_item], [delay], [message]. During the delay, both the added item and the removed item were visible. The removal was only drawn after the delay ended when message showed.

**Comment by vgaming** [comment]
Thanks, I see. I'll test this scenario.

**Comment by vgaming** [comment]
Indeed this is fixed (or was never the case if I was mistaken in the first place). Anyway, all good now.

I tested with this code now:
```
on_event("start", function()

	wesnoth.wml_actions.item {
		x = 15, y = 21,
		image = "misc/blank-hex.png~BLIT(lobby/status-lobby-s.png~SCALE(36,36),0,36)~BLIT(units/elves-wood/avenger.png~CROP(20,12,47,47)~SCALE(36,36),36,0)~BLIT(units/elves-wood/marksman.png~CROP(16,12,47,47)~SCALE(36,36),36,36)"
	}
	for i=1, 1000000 do
		wesnoth.wml_actions.remove_item {
			x = 15, y = 21,
		}
	end

end)
```
The last loop is relatively slow (because of the number of repetitions), yet the item remains visible until you exit out of the loop. This means that `remove_item` does not cause an immediate redraw.

**Comment by vgaming** [comment]
(And sorry for the late reply.)
