### ISSUE TITLE
Mismatching ToD images in {SUMMER_SCHEDULE} and {WINTER_SCHEDULE}

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2677]
Either revert 443339d8a066c33927b7123fd13d9720ff91974e or update the 24-hour schedule images to match.

**Comment by Vultraz** [comment]
Don't use Urgent for something like this.

**Comment by CelticMinstrel** [comment]
It's totally urgent, but whatever.

**Comment by doofus-01** [comment]
The good news is we can swap out images even in stable branch.  The image change may have been premature, but if it spurs some action, it's not all bad.  If this is a mistake, we won't be stuck with it for the next four years, or whenever 1.16 comes out.
Adding graphics tag so I might find it some day later.

**Comment by CelticMinstrel** [comment]
I'll add that a third option would be to simply not use 24-hour schedule images for `{MIDDAY}` and `{MIDNIGHT}` and instead use images that better match the new ToD images.

Still, the best option would be to update _all_ built-in schedules (including the two-suns schedule!).

**Comment by CelticMinstrel** [comment]
It's been nearly a year. Any update on this?

**Comment by jostephd** [comment]
There are already resources for a 24-hour version of the new ToD images:

https://github.com/wesnoth/wesnoth/blob/3ba0bbb3438b3b8612d34b4eddf81cdf1e1ed1da/data/core/images/unit_env/schedule/tod-schedule-24hrs.png

How difficult would it be to compile new actual tod graphics  from them?

https://github.com/wesnoth/wesnoth/blob/3ba0bbb3438b3b8612d34b4eddf81cdf1e1ed1da/data/core/images/misc/time-schedules/tod-schedule-24hrs.png

**Comment by CelticMinstrel** [comment]
I'm not sure... I don't think they quite match the default schedule's graphics, though? So while that approach should work for an updated 24-hour schedule, I'm not sure it'll work for midnight and midday.

**Comment by Vultraz** [comment]
I created the new default schedule images by taking one of the base sky images, cropping it to the right size, and adding some of the cloud overlays manually.

But honestly, this is still an incredibly minor issue. I think we should just forget it.

**Comment by CelticMinstrel** [comment]
No, it's not an "incredibly minor" issue. It's not a _major_ issue either, but it's not at the level of being unworthy of attention.

Anyway, from what you said it sounds like we can pretty easily make at least midday and midnight images using the same process you used for the other times of day.

**Comment by jostephd** [comment]
There are already midday/midnight images in WoV:
https://github.com/sigurdfdragon/Wings_of_Victory/blob/master/images/misc/schedule-midday.png
https://github.com/sigurdfdragon/Wings_of_Victory/blob/master/images/misc/schedule-midnight.png
They're also being added as part of #3977. However, since that PR is for master only, I suggest to cherry-pick those two images to master+1.14 in order to make the winter/summer schedules internally consistent.

@sigurdfdragon @CelticMinstrel okay?

**Comment by CelticMinstrel** [comment]
Sounds good! I assume they do fit with the rest of the schedules, right?

**Comment by jostephd** [comment]
I'd say so, yes. See for yourself:

WoV:

![2019-03-22-001119_1920x1080_scrot](https://user-images.githubusercontent.com/24784687/54792707-1f16a200-4c37-11e9-8851-b03bd8a4fa01.png)

mainline SUMMER_SCHEDULE:

![2019-03-22-001232_1920x1080_scrot](https://user-images.githubusercontent.com/24784687/54792743-56854e80-4c37-11e9-9b24-01e18e7af0b3.png)

**Comment by CelticMinstrel** [comment]
The midnight one really stands out, but I suppose that's because I'm looking at summer schedule, not winter schedule...

**Comment by jostephd** [comment]
Here's the winter schedule.

![2019-03-22-115740_1920x1080_scrot](https://user-images.githubusercontent.com/24784687/54821381-e0fe9a00-4c99-11e9-84e6-c4f38a75665c.png)

**Comment by CelticMinstrel** [comment]
Okay yeah, looks good. (I think the mainline summer/winter schedules only contain one each of midday/midnight though, don't they?)

**Comment by jostephd** [comment]
The schedules are exactly as shown in the screenshots:

https://github.com/wesnoth/wesnoth/blob/a65fb92d82571eddb463e9c9302750b6bf1d822f/data/core/macros/schedules.cfg#L139-L155

**Comment by CelticMinstrel** [comment]
Oh, okay. In any case, they're fine, so please go ahead and commit them.

Now all we need is updated 24-hour schedule images and updated 2-suns schedule images... but those are less important since they're at least internally consistent. Oh, and maybe updated images for the special schedules (indoors, underground, etc).

**Comment by sigurdfdragon** [comment]
FTR, the midday & midnight images are from https://forums.wesnoth.org/viewtopic.php?p=633042#p633042

**Comment by jostephd** [comment]
Okay, committed and backported. @beetlenaut, thanks for making those images. @CelticMinstrel, I agree, the other schedules are internally consistent, we can have a new issue for them.
