### ISSUE TITLE
Debug notifications are just visible for a short period of time

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#2683]
In 1.13 certain debug commands are now synced so they cause no out-of-sync errors. The issue is that they only get announced by a transient message and it's not logged anywhere either so there is barely any chance for a player to notice cheating via debug mode.

I suggest turning the notification into a dialog (similar to the OOS dialog) that needs to be dismissed so there is no chance the player misses it.

**Comment by gfgtdf** [comment]
just liek the OOS dialog this should also have a 'don't show this again' checkbox.

**Comment by CelticMinstrel** [comment]
Also please don't show it when there's no network connection.

**Comment by gfgtdf** [comment]
> Also please don't show it when there's no network connection.

no, it should also be shown in replays; you want to know whether someone cheatet if you are anylyzing a replay.



Actually i think to implement this we could just reuse the current oos dialog asis since afaik all it's text is configurable. It would probably offer you a "do you want to save the game" button but that doesn't do any harm, in fact beeing able to save the game before the cheat happens might be a useful feature.

**Comment by CelticMinstrel** [comment]
Um, if it's going to be a proper dialog, it _absolutely_ must never be shown when you're playing a campaign or a local MP game. Otherwise it would totally defeat the convenience of the debug commands.

Maybe only show it if debug mode is _not_ enabled? That could work.

**Comment by gfgtdf** [comment]
> Maybe only show it if debug mode is not enabled? That could work for your replay case.

hmm but it would hide the message form people who use debug mode in normal mp games (afaik there are such people who _alyways_ have debug mode on).

i think the beast check would be somehting like `current_player.is_local() && !is_replay()`.

**Comment by CelticMinstrel** [comment]
Sure, as long as that makes it not show up in campaigns or local MP games when I have debug mode enabled, that would be fine.
