### ISSUE TITLE
GUI2 rich text label widget for the help browser

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2687]
We need a rich-text widget using probably an extension to Pango markup (with additional tags) in order to fully port the help browser to GUI2.

The widget has the following requirements:

* Inline images, which can be shown centred between paragraphs of text.
* Floating images, which align to left or right and which text will wrap around. I believe Pango supports this in the form of 'wrap shapes' or something similar.
* Clickable links that trigger a callback, allowing them to link to other pages within the help browser.
* Ability to set tab stops, or some other means of creating tables.

In my opinion the tag names for these should be unchanged, which means `img`, `ref`, `jump` respectively. In particular, don't use `a` for links; it doesn't make sense anyway.

**Comment by jostephd** [comment]
In unit type help topics, the resistances and terrain defense columns, which contain percentages, are left aligned. It'd be nice to have them right aligned, so all the `%` signs are above each other even when some values are 0% and some not.

**Comment by CelticMinstrel** [comment]
I wonder if it's okay to mark this high (or at least medium) priority? It's basically the blocker for #3653 which I think would be really nice to get ready for 1.16, if possible. It's not the end of the world if not, mind you, as the GUI1 help still functions pretty well, and there are other blockers preventing the full removal of GUI1...

**Comment by Pentarctagon** [comment]
Either priority is fine I suppose; the main question is if anyone (@Vultraz maybe?) will work on it.

**Comment by CelticMinstrel** [comment]
I did get started on it ages ago, though I think I didn't make any actual material progress (as I recall I simply copied a class and started altering it a little). I don't currently have plans to continue working on it though.

**Comment by babaissarkar** [comment]
@CelticMinstrel 
Seems like pango can't wrap text around an image :
https://stackoverflow.com/questions/41845831/pango-layout-flow-around-container-image

**Comment by babaissarkar** [comment]
Current Plan : I've currently decided to use `set_cfg` to dynamically update the canvas based on the contents parsed from marked up text using `help:topic_text's` parse_text method (`help/help_impl.cpp`)

**Comment by babaissarkar** [comment]
Seems the text wrapping around floating images need to be done manually.

**Comment by Pentarctagon** [comment]
Does wrapping text around an image refer to the portraits on the unit help pages? Or are there other places that's done?

**Comment by CelticMinstrel** [comment]
I concluded it was probably possible after scanning the pango documentation and seeing some functions that looked like they might be able to make it happen (I think the functions contained one or both of the words "wrap" and "shape" in them). I didn't get as far as confirming whether or not those functions actually _could_ do it.

The accepted answer on that question you linked has a link to another answer that seems to imply it's possible to do but quite difficult. Please note that we don't need anything as elaborate as the sample image that was posted in the question you linked – wrapping around the rectangular area occupied by the image should be sufficient, and if pango shape functions can't make it happen, perhaps it could be done manually by splitting the text into up to three rectangles. I'm pretty sure there should be a way to tell, given a specific rendering width and height, which word is the first one that falls out of bounds.

Take a look at the actual in-game help to see where it's used. I don't think there are a lot of uses of it, so depending on the context where it appears, it might also be an option to stick to solely centered images.

-----

Note that the main issue with the whole rich text widget is that it probably _can't_ just use Pango's built-in markup parser. The intent is to extend Pango's markup with some custom tags, but as far as I know, Pango doesn't provide any extension hooks for their markup. So it's quite possible a whole custom markup parser is required, and then manually apply attributes such as bold or whatever to the string. (We do have the existing help markup parser which would probably satisfy the parsing half of that tho.)

**Comment by Pentarctagon** [comment]
Yeah, where I was going with my question was essentially that this doesn't need to be a general solution - it can be tailored specifically for what we need, and we completely control the in-game help so we can adjust how that's laid out as well if necessary.

**Comment by CelticMinstrel** [comment]
In particular, point one (supporting inline images at all) is more important than point two (allowing them to be floated off to the right with text wrapped around them). Points three and four are also important though – we need a way to make links that trigger a callback, and we need a way to align text in columns. (Pango does have some facility for links already, but I don't know anything about how that works. We probably use it in one or two places.)
