### ISSUE TITLE
text_box: deleted text is restored during input method is activated

### ISSUE THREAD

**Issue by fujimo-t** [wesnoth/wesnoth#2694]
Reproduce method and behavior of this bug:
1. Push 'Multiplayer' in title screen
1. Type 'wesnoth' in 'Login:' text box
1. Activate input method
1. Type any character
1. Delete all characters by pushing Backscape key repeatedly
1. Type any character
1. Then, displayed text is 'wesnoth' + typed character

Environment:
* OS: Linux (openSUSE Tumbleweed)
* Version: 1.13.12+dev (7ca7ed0e4f)
* Input method framework: Fcitx
* Input mehtod engine: mozc

If you want to know or install input method in linux environment to test, URLs below are maybe useful:
* https://wiki.archlinux.org/index.php/Fcitx
* https://wiki.archlinux.org/index.php/mozc

**Comment by fujimo-t** [comment]
I think cause of this bug is that toggle of `text_box_base::ime_in_progress_` is not done in right timing.
I'm trying to fix this.

**Comment by jyrkive** [comment]
Fixed by merging #2697.
