### ISSUE TITLE
[for] loop partially broken on master

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#2699]
For the following code:
```
[for]
  start=0
  step=1
  end=30
  variable=i
  [do]
    {VARIABLE counter "$counter $i
"}
    [message]
      message="$i"
    [/message]
  [/do]
[/for]

[message]
  message="$counter"
[/message]
```

`$counter` works as expected, and displays 1-30.  Displaying the individual `$i` however does not, with the values being variously incorrect.

An example of what this looks like in my add-on:
https://cdn.discordapp.com/attachments/259976436490829825/425015673186418699/Screenshot_from_2018-03-18_14-34-05.png

(the visual glitch in the screenshot is distro-related, not wesnoth-related)

**Comment by gfgtdf** [comment]
so is this known to be master-only or did you just not test on 1.14 ?

**Comment by Pentarctagon** [comment]
This does not happen on 1.14.

**Comment by gfgtdf** [comment]
it's somwhat hard to see how that screenshot relates to the code you posted.

**Comment by Pentarctagon** [comment]
The [option]'s label field is being populated by the [for] loop's `$i`.

**Comment by Pentarctagon** [comment]
Maybe a better screenshot+example:
```
{VARIABLE counter ""}

[for]
  start=0
  end=30
  step=1
  [do]
    
    {VARIABLE counter "$counter $i
"}
    [set_variables]
      name=option_test
      mode=append
      [value]
        label=$i
      [/value]
    [/set_variables]
    
  [/do]
[/for]

[message]
  message="$counter"
  [insert_tag]
    name=option
    variable=option_test
  [/insert_tag]
[/message]
```
on master then results in:
https://i.imgur.com/kTKyi7c.png

**Comment by gfgtdf** [comment]
> on master then results in:

hmm, i thought master doesnt even start scenarios peoperly? Also this could also be a bug in the [message] implementation bringing the entries in unorder (whihc seems somwhow more likeley since master as  huge gui changes and nearly zero changes to the wml api iirc.)

**Comment by CelticMinstrel** [comment]
This is quite a strange issue, as the value of `$i` is being correctly substituted in one place but incorrectly substituted in another...

**Comment by gfgtdf** [comment]
Is this issue still present in current master?

**Comment by Pentarctagon** [comment]
It isn't.

**Comment by CelticMinstrel** [comment]
Kinda wonder what it was that ended up fixing it… I guess it's not too important though.
