### ISSUE TITLE
Raise minimum MSVC version to 2017

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2702]
according to http://en.cppreference.com/w/cpp/compiler_support vs2015 does not support the following c++14 features:

* Extended constexpr ( N3652 )
* Member initializers and aggregates (NSDMI) ( N3653 )

so we have to require vs2017 to get full  c++14 support.

**Comment by Vultraz** [comment]
@jyrkive what are your thoughts on this?

**Comment by gfgtdf** [comment]
irclogs:

> 20180319 12:24:21< JyrkiVesterinen> Fine. If VS2015 is the only reason why we don't have full C++14 support, I'm okay with dropping it.

**Comment by Vultraz** [comment]
Oh. Ok. Nevermind then. I can commit my own VS 2017 projectfile, then.

**Comment by gfgtdf** [comment]
> I can commit my own VS 2017 projectfile, then.

i'll assign it to you then

**Comment by gfgtdf** [comment]
> Current master and 1.14 VC project files both contain VC16, corresponding to VS 2019. (In fact, I remember this because their introduction to the code repository overwrote my own project files...)

This issue was iirc not only about adding them.but also.about raising the mimum msvc requirement to 2017.

**Comment by Wedge009** [comment]
Okay.

**Comment by Vultraz** [comment]
I really cannot think of anything that needs to be done for this besides what has already been done - namely, to add the new VS projectfiles and remove any old ones.

**Comment by stevecotton** [comment]
I think this one's not only been done (0c3cdd3a8663f4b3d9d5cc3e0959350d44995873), but also its replacement has since removed for being obsolete (b95d72f9c15a2a540103ba158e2008d1cc85b518).

@Wedge009 are you happy with closing this again?

**Comment by Wedge009** [comment]
I wasn't really the one concerned about keeping it open, but yes, the project files aren't explicitly kept any more. I'm assuming VS 2017 is now the minimum version.
