### ISSUE TITLE
In-game help: Add-ons section is outdated

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#2703]
The Add-ons → Using Add-ons topic in the in-game help was not updated in time for 1.14.x to document changes or additions like the one introduced in commit a09e2bb8583c6125f8c4e3157d6eba8bbd800b62 (renaming MP Modifications to simply Modifications), or Cores.

The Installing Add-ons topic in the same section might also not accurately reflect the changes made to the Add-ons Manager since 1.12 (which was more or less replaced wholesale, really), so that might also need some double-checking.

This needs to be addressed in 1.14 after the string freeze is lifted following the 1.14.0 gold release.

**Comment by jyrkive** [comment]
Done with commits 51d86c93febf180aa988fe44c07d2c2904c658f4 and e1adb8f29c0cd301c71346804b30900ae46ea6ef.
