### ISSUE TITLE
Map Editor: "toggle minimap village drawing" not working

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2707]
Steps:
* open any map with Map Editor
* add villages (I used grassland Gs^Vh)
* check out buttons at the bottom of minimap, try to toggle the "village" one

IDK what this button should do to be honest, but it doesn't do anything at all anyway.
It should do something right?

**Comment by jyrkive** [comment]
Which version of Wesnoth did you test?

**Comment by vgaming** [comment]
@jyrkive  v1.13.11+dev (8309ba63c1-Modified)

**Comment by jyrkive** [comment]
Could you test latest 1.13.12+dev (in the 1.14 branch)? This may be a duplicate of #2681.

**Comment by vgaming** [comment]
Ah, didn't notice the branch. Sure, will do.

**Comment by vgaming** [comment]
@jyrkive I re-tested on 1.14, getting the same behavior. When you press this toggle button on minimap, nothing changes.

**Comment by vgaming** [comment]
Possibly related bug: https://github.com/wesnoth/wesnoth/issues/2706

**Comment by vgaming** [comment]
@jyrkive sorry, I cannot reproduce anymore, too. Maybe there was something wrong with the test after all.
Sorry for the confusion, closing for now.
