### ISSUE TITLE
Update All addons fails with Access is denied

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2712]
Happened on 1.13.12 when trying to update pick_advance from 0.5.6 to 0.5.8

Screenshot https://i.imgur.com/lmbUame.jpg

Log
```
20180322 18:46:03 error filesystem: Failed to create directory C:\Users\Ravana\Documents\My Games\Wesnoth1.13/data/add-ons/pick_advance: Access is denied
20180322 18:46:03 error filesystem: Failed to create directory C:\Users\Ravana\Documents\My Games\Wesnoth1.13/data/add-ons/pick_advance/doc: Access is denied
20180322 18:46:03 error filesystem: filesystem::io_exception thrown while installing an addon; "failed opening file: Access is denied.

: iostream error"
20180322 18:46:03 error general: A problem occurred when trying to create the files necessary to install this add-on.
```

On filesystem I see that pick_advance folder is now gone.

**Comment by Wedge009** [comment]
Maybe an issue in accessing your file system? Was it temporary or permanent?

**Comment by ProditorMagnus** [comment]
Temporary I believe.

**Comment by ProditorMagnus** [comment]
Doesnt seem so. However, update all does not seem to work when addon has dependency and both have update, it asks to download dependencies multiple times.

**Comment by Wedge009** [comment]
Sounds like a different issue, though. I see a few references to dependencies while scanning through the bug list.

**Comment by UnwiseOwl** [comment]
User Kmaz also seems to have had this problem. Reported via steam:
https://steamcommunity.com/app/599390/discussions/0/1696046342863589530/

>Hi there, when trying to download certain add-ons (Era of Magic - Resources, To Lands Unknown, To Lands Unknown - Resources Pt. 1, To Lands Unknown - Resources PT 2) and some others I get this weird error. https://i.imgur.com/Xd3Ra9J.jpg 
> Any ideas or help would be awesome.

**Comment by ProditorMagnus** [comment]
It has not happened since then, so not enough information to be able to do anything with this issue.
