### ISSUE TITLE
Revert to Boost 1.50 as minimum required version on 1.14

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#2715]
This is a reminder for @CelticMinstrel mainly, stemming from an extensive IRC discussion spanning two days which I probably don't need to repaste here.

**Comment by shikadiqueen** [comment]
Commit 6265181b579230b5764b8d29afe099b1185d5617 reverts the build-time config checks for 1.56 to 1.50, but the code that mandates 1.56 is still around so there will be FTBFS for people using 1.50 until this bug is properly fixed. We just want to be able to build the server software on wesnoth.org again.

**Comment by Vultraz** [comment]
667b2b7bd3425516bd084eb9bc036dafd3ecf584 changes the code to use something other than `boost::optional`.

**Comment by CelticMinstrel** [comment]
You mean something other than `boost::optional::emplace`. It's still using `boost::optional`.

**Comment by Vultraz** [comment]
Ah. Ok. Well, same difference.
