### ISSUE TITLE
make wesnoth.format a tstring metatable function

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2722]
i just updated my addons for 1.14 and i noticed that i often had to replace  codes like 
```("%s's %s"):format(name1, name2)```
 with 
```wesnoth.format(_$name1|s's $name2|", { name1 = name1, name2 = name2} )``` 
it might be nicer to be able to just wrtite  
```_("$name1|s's $name2|"):format { name1 = name1, name2 = name2}```

just a random idea though, bu it'D be nice to have some opinions.

**Comment by CelticMinstrel** [comment]
Note that the first argument to `wesnoth.format` can be either type of string.

**Comment by gfgtdf** [comment]
hmm ye but we are not going to remoe the wesnoth.format name so that shoudn't be  problem.

**Comment by CelticMinstrel** [comment]
Well, I'm not opposed to duplicating the function in the t_string metatable.

**Comment by CelticMinstrel** [comment]
Done in 7ee7d6d47c7d6cb861a6c5989584d3e5fc8eeed9
