### ISSUE TITLE
Can't disable mods for campaigns after they have been used

### ISSUE THREAD

**Issue by Samonella7** [wesnoth/wesnoth#2727]
Using 1.13.12

If I start a campaign with a mod active, then quit and restart the campaign after unchecking the mod's box, the mod is still active in the new game. Also, if I uncheck the mod's box, click 'cancel' to escape back to the main menu, then open the campaign chooser again, the mod's box is checked again.

Uninstalling the mod, restarting the game / pressing F5, and reinstalling it is the only way I have found to start a campaign without including it.

As far as I can see, multiplayer is unaffected by this.

Here is a mod that you can easily test with; all it does is display a message at the start of each scenario:
[TestMod.zip](https://github.com/wesnoth/wesnoth/files/1843905/TestMod.zip)

**Comment by Vultraz** [comment]
@gfgtdf you might have broken this when you fixed the "mod selection in SP cause dependency prompt" message.

**Comment by gfgtdf** [comment]
fixed in 74ca37f97bba4d
