### ISSUE TITLE
Replay unit selection issue

### ISSUE THREAD

**Issue by EoZ8** [wesnoth/wesnoth#2739]
Wesnoth 1.13.12

When moving cursor over some of the units in the replay some of them are not selected
only some of them, most are. The units that can not be selected seem to change when continuing the replay, they appear to be random.
![image](https://user-images.githubusercontent.com/37751563/37868408-bc8e0c4c-2f9d-11e8-87b5-17b5d0b7d506.png)

**Comment by Wedge009** [comment]
I don't really understand this one. What does 'selected' mean. A quick replay check and I can hover and click on all the units present. Random doesn't really help - without a reliable way to reproduce the issue I doubt there's much we can do.

Tested in 1.14.0.

**Comment by jostephd** [comment]
It's a version of #3687. I can reproduce it by loading a replay of an SP game with fog enabled, changing view to "Show all units", and doing mouseover on a fogged unit _after_ starting the scenario.

**Comment by jostephd** [comment]
I can no longer reproduce this. I assume it was fixed by #4119 which has been merged after my last comment.

@EoZ8 Can you reproduce this in 1.15.1/1.14.9?

**Comment by Wedge009** [comment]
It does indeed sound like #3687. I also confirm it's no longer an issue. Not sure if EoZ8 is that active, will give him/her a few days to respond otherwise we should close this as resolved.
