### ISSUE TITLE
Replay buttons issue

### ISSUE THREAD

**Issue by EoZ8** [wesnoth/wesnoth#2740]
Wesnoth 1.13.12

When i move my mouse over the buttons to control the replay none of the buttons lit up except the start from the beginning button.
Only after clicking on them and moving the mouse during playing of the replay they lit up.
![image](https://user-images.githubusercontent.com/37751563/37868439-2dd8a060-2f9e-11e8-963b-ac82c0cc1438.png)

**Comment by Wedge009** [comment]
Button highlights do seem inconsistent. A quick check on 1.14.0 shows only the stop icon (square) being highlighted on mouse hover.

**Comment by stevecotton** [comment]
PR #4156 fixes this, the underlying issue is two different bits of code having different ideas of which buttons should be enabled.

**Comment by Wedge009** [comment]
#4156 was merged, please re-open if this is still an issue (although I suppose there hasn't been a new 1.14 release since that commit).
