### ISSUE TITLE
Speed preferences are weird

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2741]
In the preferences dialog, the speed setting is not saved if the accelerated speed checkbox is unchecked when you close the dialog. This means that checking it, setting the speed, and unchecking it again does not work.

Furthermore, it does not make sense for the slider to be disabled when accelerated speed is. The accelerated speed has a quick-toggle hotkey, so the speed setting is relevant even if accelerated speed is not currently enabled.

This presumably affects both master and 1.14.

**Comment by Wedge009** [comment]
I agree with this. I've always had to work around it by enabling the permanent-acceleration toggle, adjusting the speed, then disabling the toggle again.

**Comment by jostephd** [comment]
#3258
