### ISSUE TITLE
Mini-map's white rectangle is too big if the map fits horizontally on screen

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2742]
When a narrow map fits horizontally in the main window, the white rectangle on the mini-map overlaps the main window.

This is in 1.13.12, and is also visible in a pre-1.13.9 screenshot attached to #1563, although that issue is about a different bug.

**Comment by Wedge009** [comment]
I find this doesn't happen in 1.14.0. Can you confirm, please?

**Comment by stevecotton** [comment]
Seems fixed in 1.14.0, thanks.

**Comment by Wedge009** [comment]
I'm re-opening this as I'm starting to see it a lot now (1.14.9 was just released). Specifically, An Orcish Incursion S1 with 1920x1200 window exhibits this.

It looks like it might be related to how we use SDL as 1.14.9 release doesn't have it but it's using 2.0.8, I have 2.0.10 (and we now know some changes in default render behaviour caused #4237/#4245).

**Comment by Wedge009** [comment]
SDL 2.0.9 also doesn't have this issue.

**Comment by Wedge009** [comment]
Resolved via work on #4510.
