### ISSUE TITLE
Certain units flash black instead of white on advancement

### ISSUE THREAD

**Issue by EoZ8** [wesnoth/wesnoth#2743]
Wesnoth 1.13.12

When loading a replay from 1.13.12 game, when a unit advances its color when advancing goes black and not white. Did not happen when I was loading 1.13.12+dev
![image](https://user-images.githubusercontent.com/37751563/37868752-7c10661e-2fa3-11e8-8359-3d82702c8c99.png)

**Comment by gfgtdf** [comment]
maybe you could test with 1.13.13 release, if it did not happen witrh 1.12.12+dev its probably fixed but it coudl alos be that it happened becasue you used differnt library versions for those two builds.

**Comment by Wedge009** [comment]
I'm guessing you mean the unit sprite flashes black during advancement. Is this still happening in 1.14.0? Would help if you had a save game for us to test.

**Comment by Wedge009** [comment]
Okay, I can confirm this one - tested today on 1.14.1. I confirm bats flash black, spearmen flash white, and an interesting case of a horseman flashing black on advancement to knight, but white on advancement to lancer.

**Comment by newfrenchy83** [comment]
in fact this black unit have standing or levlout levelin animations. wjen i clan them thie advancement flash white.

**Comment by newfrenchy83** [comment]
someone find the origin of the problems? i tried but i cannot.

**Comment by jostephd** [comment]
I can't reproduce Horseman flashing black on advancement to Knight. I tried all 4 time of day values on the first scenario of AToTB on Linux on 1.14 from git.

**Comment by Wedge009** [comment]
Confirmed: 1.14.1 release seems to have the problem, build on e54b28a5 seems to be okay. Please re-open if this is still a problem.

**Comment by Vultraz** [comment]
Fixed by 60c93cf47b19f8c1da6f6ee78d346feddebfcc07
