### ISSUE TITLE
In mp games, rename "Quit to Titlescreen" to "Quit to Lobby"

### ISSUE THREAD

**Issue by blarum** [wesnoth/wesnoth#2744]
From a mp game, "Quit to Titlescreen" from the "Menu" menu in the top left, quits to lobby instead, so it should be renamed to "Quit to Lobby". In local games, "Quit to Titlescreen" does what it says.

**Comment by Vultraz** [comment]
Unfortunately, it seems the hotkey system doesn't currently support this. Will need to make some changes.

**Comment by CelticMinstrel** [comment]
Or you could hard-code a special case. >_>

**Comment by gfgtdf** [comment]
> Or you could hard-code a special case. >_>

for 1.14 this is probably the best option.
