### ISSUE TITLE
MP password save broken

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2745]
1. Login and save password
2. Exit wesnoth
3. Login again
Result: Incorrect password, when deleting last symbol, then correct.

Tested on 1.13.11 and 1.13.12.

**Comment by sevu** [comment]
I'm not asked for the password in step 3 and are directly logged in - this may mean it's an windows specific bug. (tested only on linux)

**Comment by Vultraz** [comment]
I've been consistently able to log in here on Windows, though I seem to remember running into this once. Not sure what the issue is.

**Comment by vgaming** [comment]
> though I seem to remember running into this once
I also think I've run into this once too, but I'm unsure as well.

Could it be that the _first_ attempt to save a password fails (if it did not exist before)? Wild guess...

**Comment by vgaming** [comment]
EDIT ^

**Comment by Pentarctagon** [comment]
@jyrkive My password is 64 characters, so that is a possibility.

**Comment by ProditorMagnus** [comment]
Problem remains with 1.13.13.

**Comment by ProditorMagnus** [comment]
More specifically, 1.13.13 does not accept even correct password after it has been saved once.

**Comment by ProditorMagnus** [comment]
Might be related
`20180403 16:59:17 error general: Invalid UTF-8 string.
20180403 16:59:18 error general: Invalid UTF-8 string.
20180403 16:59:18 error general: Invalid UTF-8 string.
20180403 16:59:18 error general: Invalid UTF-8 string.
20180403 16:59:19 error general: Invalid UTF-8 string.
20180403 16:59:19 error general: Invalid UTF-8 string.
20180403 16:59:20 error general: Invalid UTF-8 string.
20180403 16:59:21 error general: Invalid UTF-8 string.
20180403 16:59:21 error general: Invalid UTF-8 string.
20180403 16:59:21 error general: Invalid UTF-8 string.
20180403 16:59:23 error general: Invalid UTF-8 string.
20180403 16:59:23 error general: Invalid UTF-8 string.
20180403 16:59:23 error general: Invalid UTF-8 string.
20180403 16:59:23 error general: Invalid UTF-8 string.
20180403 16:59:23 error general: Invalid UTF-8 string.
20180403 16:59:23 error general: Invalid UTF-8 string.
20180403 16:59:23 error general: Invalid UTF-8 string.
20180403 16:59:23 error general: Invalid UTF-8 string.
20180403 16:59:23 error general: Invalid UTF-8 string.
20180403 16:59:23 error general: Invalid UTF-8 string.
20180403 16:59:24 error general: Invalid UTF-8 string.
20180403 16:59:24 error general: Invalid UTF-8 string.
20180403 16:59:24 error general: Invalid UTF-8 string.
20180403 16:59:24 error general: Invalid UTF-8 string.
20180403 16:59:24 error general: Invalid UTF-8 string.
20180403 16:59:24 error general: Invalid UTF-8 string.
20180403 16:59:24 error general: Invalid UTF-8 string.
20180403 16:59:24 error general: Invalid UTF-8 string.
20180403 16:59:28 error general: Invalid UTF-8 string.
20180403 16:59:31 error general: Invalid UTF-8 string.
20180403 16:59:31 error general: Invalid UTF-8 string.
20180403 16:59:31 error general: Invalid UTF-8 string.
20180403 16:59:31 error general: Invalid UTF-8 string.
20180403 16:59:35 error general: Invalid UTF-8 string.
20180403 17:00:50 error general: Invalid UTF-8 string.
20180403 17:00:53 error general: Invalid UTF-8 string.
20180403 17:02:01 error general: Invalid UTF-8 string.
20180403 17:03:12 error general: Invalid UTF-8 string.
20180403 17:03:18 error general: Invalid UTF-8 string.
20180403 17:03:18 error general: Invalid UTF-8 string.
20180403 17:03:19 error general: Invalid UTF-8 string.
`

**Comment by ProditorMagnus** [comment]
Some time after having credentials file, \F is appended to it. When removing \F, then it is back in the form of delete one to get in.

**Comment by ProditorMagnus** [comment]
After one more exit of wesnoth, Ì is appended.

**Comment by ProditorMagnus** [comment]
And after that, \. This happens just when opening wesnoth to title screen, and then using exit - nothing that should change credentials.

**Comment by ProditorMagnus** [comment]
After some cycles of that, appended part based on xxd output consists of hex 5c46 4043 f780 9c2c 8e91 0c24 e557 8544

**Comment by ProditorMagnus** [comment]
At that point, credentials file is 48 bytes.

**Comment by ProditorMagnus** [comment]
Testing shows that credentials file size must be 30 bytes. Solved it by changing credentials file to read-only.

**Comment by CelticMinstrel** [comment]
The 30 bytes presumably assumes you only have one login.

**Comment by ProditorMagnus** [comment]
Yes.

**Comment by CelticMinstrel** [comment]
Based on this thread, I'd hypothesize that there's something wrong with the code that reads the credentials file from disk.

**Comment by ProditorMagnus** [comment]
> This happens just when opening wesnoth to title screen, and then using exit - nothing that should change credentials.

That suggests credentials update is called when there is no need to change them.

**Comment by Pentarctagon** [comment]
So does password saving not work *at all*?  If yes, this definitely would be something to get fixed before 1.14.

**Comment by ProditorMagnus** [comment]
I would say yes, normal user is not expected to go change permissions on credentials file to get it work correctly.

There is one problem of credentials file corrupting on wesnoth exit, and another problem of loaded credentials preventing login with manually entered password.

**Comment by Vultraz** [comment]
Actually, out of curiosity, could you see if you still get this problem on master?

**Comment by ProditorMagnus** [comment]
Not in reliable test form, I can only compile wesnoth on another OS.

**Comment by Pentarctagon** [comment]
@Vultraz I can confirm that this happens on master as well.

**Comment by CelticMinstrel** [comment]
That commit fixes it for me, please confirm?

**Comment by ProditorMagnus** [comment]
Curiously this is indeed fixed, even though newly credentials file is 1 byte longer now. Both 30 and 31 byte versions allow logging in.
