### ISSUE TITLE
Allow attempting to observe game even with missing addons

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2747]
With 1.12, I can attempt to observe game with unknown era - and if they have missing unit type, I get error message containing their id, and can create placeholders needed to join.

Example placeholder
```
[unit_type]
	id={}
	name={}
	hitpoints=1
	movement=1
	experience=1
	level=1
	alignment=neutral
	cost=1
[/unit_type]
```

After some iterations it is possible to locate all necessary unit types, and observe game.

1.13.12 instead shows https://i.imgur.com/9JHiwha.png - and as such would be reported here anyways.

**Comment by ProditorMagnus** [comment]
re #2538

**Comment by stevecotton** [comment]
It seems the behaviour depends on whether the era is required or not. Testing with games that are still waiting for players to join before starting:

Using Ageless Era, mousing over the information (i) symbol shows that the era is missing, and the "One or more items need to be installed to join this game" message.

SXCollection has the SXC Default Low-Level Era, which isn't required to be installed on all players' PCs (it's just a subset of Default Era), and is in the SXCollection add-on (an mp map_pack add-on). That gets the "Something is wrong with the add-on version check" error reported in this issue.

**Comment by Vultraz** [comment]
Indeed, it depends if the era is required or not. Sounds like there's some issue with non-required eras, though...

**Comment by Vultraz** [comment]
Confirmed fix.
