### ISSUE TITLE
MP login password reminder

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2748]
When logging into the MP Server and being asked for the password, press the password reminder button twice.
You end up in an endless loop.

**Comment by shikadiqueen** [comment]
Since the function doesn't do anything other than tell you to use the forums, I feel like it'd be better to drop it entirely.

**Comment by soliton-** [comment]
The question is if we want to support other user_handler implementations that would want to use the password reminder functionality.

**Comment by GregoryLundberg** [comment]
What we had was wrong/lame and needed to go.

Yes, we should support it with other password protocols which offer it. But we don't support any, so it may be a while before we need to revisit the idea.

**Comment by soliton-** [comment]
I have trouble understanding what the motivation is. If the idea is to remove everything we do not currently use from the user_handler then there is some more stuff to clean up.

**Comment by Vultraz** [comment]
The motivation was all it did was tell people to go use the forums. @shikadiqueen said it better to just remove it, and that saved me the trouble of fixing this bug here.
