### ISSUE TITLE
assertion failure "eh->disabled()" during OOS dialog

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2750]
the OOS dialog can give you the option to save the dialog during an event, which casues the above assertion failure

**Comment by Vultraz** [comment]
*sigh* Looks like we may just have to get rid of that assertion entirely.

**Comment by gfgtdf** [comment]
just observed the same asertion during the "players X left what do you want to do" -> "save game and abort" dialog

**Comment by gfgtdf** [comment]
It's important to know that the saves generated there are somehow 'corrupt' in a sense that you _should not_ continue playing with those sicne you risk into gettings bugs. So fixing that assertion is probalby not enough to be called a good fix, we have basicially have  options:

1) Just save a replay if an efect is currently excuting, then people can play a replay and generate a usable save that way.
2) Delay the save until the current action is finished, not that we probabl don't want this in for the 'debug command delteced' saves.
3) Leave the logic as is but add a fat warning about this issue, when the save is loaded.

**Comment by Vultraz** [comment]
@gfgtdf commit above skips the disabled event, which would be the current one in case of an OOS. Is that acceptable?

**Comment by gfgtdf** [comment]
well it fixes the assertiion failure so it clearly an impovement. with this we are problably at 1.12 behviour. still, the resultng savegame might be bad since that even was not exactuted complely in that savegame, we need way to flag these saves, and tell the user how to saveley load these saves when they try to load them in the usual way.
