### ISSUE TITLE
TRoW in debug mode: S07 fails because of missing lady_store

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2752]
If you jump through TRoW using :debug :n, there's a WML error in S07 Return To The Oldwood, because lady_store hasn't been set. You have to go back to S02 and play it to set that variable (admittedly that doesn't take long in debug mode).

Please take this as minor, it's just logged because it slows debugging of another issue.

**Comment by sevu** [comment]
Depending on the decision one has to play S05 too.
Things can be simplified a bit by moving things into `victory` events (they are fired when using :n).
Then one doesn't need to 'play' the scenario, but skipping it entirely by using :cl will still have the issue.
