### ISSUE TITLE
pkg-config required for building

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2755]
To build with scons I needed to have pkg-config installed, otherwise I get
`/bin/sh: pkg-config: Kommando nicht gefunden.`, and a bit later a compiling error.

This should be documented in the INSTALL.md
Is this scons specific? Is this required on windows too? what about mac_os?

**Comment by GregoryLundberg** [comment]
My Arch Linux has pkg-config 0.29 installed. It's a dependency for a LOT of other packages. I've not checked which ones installed it on my system.

There is no need to document every dependency for every package Wesnoth depends upon.

**Comment by sevu** [comment]
I had it apparently installed all the time I was around here.... until yesterday (I did some -Rss)
It's installed because it's part of the base-devel group, it's only as required as makedependency for a lot of packages.
But I think it's fine as is, we're not soting minimum versions of cmake and scons either. The tricky part was that on first sight it looked like a compile error.
