### ISSUE TITLE
Promoting Wesnoth to Facebook

### ISSUE THREAD

**Issue by anaufalm** [wesnoth/wesnoth#2769]
Wow, I've seen trailer of this game, and this is a really cool strategy game, very interesting I really like it. And that's evident from the many stars in this game.

May I share this preject? So that people (gamers) know more about this cool game. I will promote it on facebook possible. ;)

**Comment by singalen** [comment]
Battle for Wesnoth does have a Facebook page: https://www.facebook.com/Battle-for-Wesnoth-1671354243186470/

**Comment by anaufalm** [comment]
Yes I know that, I just want to promote this Game through my page on Facebook personally. Just asking permission from PO that my actions are allowed.

**Comment by Pentarctagon** [comment]
I don't believe there's any restrictions or similar on promoting Wesnoth - quite the opposite in fact, promoting Wesnoth and getting attention for it is something that has generally not been done very effectively.  So yeah, go for it.
