### ISSUE TITLE
trow buf

### ISSUE THREAD

**Issue by unijonsson** [wesnoth/wesnoth#2770]
on TROW easy mermen cannot access villages, either on land or sea

![screen shot 2018-03-28 at 1 52 31 pm](https://user-images.githubusercontent.com/37883564/38055991-06ca86ba-3290-11e8-927c-39d66a581b97.png)
![screen shot 2018-03-28 at 1 52 18 pm](https://user-images.githubusercontent.com/37883564/38055995-0949e1f6-3290-11e8-9f73-41accd39df30.png)

**Comment by sevu** [comment]
Thank you for the report.
This issue has been fixed with 1.13.12, though, if you just want to continue it should be enough to restart wesnoth.
