### ISSUE TITLE
wesnoth.wml_actions.message.side_for not working?

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2776]
Steps:
* start game with 2 humans players
* end turn with first side so side2 will be in control
* open Lua console
* execute
```lua
wesnoth.wml_actions.message {message="test", side_for=1}
wesnoth.wml_actions.message {message="test", side_for=2}
````

Expected: first command doesn't generate a message, second command does generate a message

Actually: the inverse happens.

Wesnoth version v1.13.12+dev (6265181b57-Clean)

**Comment by gfgtdf** [comment]
iirc 'side_for' actually means 'show the message for the client that controls that side', unrelated to whether it is that sides turn or not. But yes there seems to be a bug there becuase even then both messages should be shown (how can you even tell which message is shown when both hav the same message?)

**Comment by ProditorMagnus** [comment]
On 1.13.12 it works as expected.

**Comment by gfgtdf** [comment]
> On 1.13.12 it works as expected.

that's somewhat surpsing since i thought i alaredy found the cause for that bug (this line https://github.com/wesnoth/wesnoth/blob/1.13.12/data/lua/wml/message.lua#L345 using `side < #wesnoth.sides` instead of `side <= #wesnoth.sides`) :/

**Comment by ProditorMagnus** [comment]
Not completely same test conditions, scenario had 4 sides in total.

**Comment by vgaming** [comment]
Oh, that simple?
Thanks for the fix.
I tend to write side-specific functions in pure Lua code now though. Cross-compatible between 1.12 and 1.13:
```lua
if side == 1 or side == 2 then
  wesnoth.wml_actions.message { ...
```
Allows you to additionally distinguish observers, etc etc.

**Comment by gfgtdf** [comment]
> Oh, that simple?

well yes, becasue we just fixed the bug in the code that and not changed the bahviour to what you expceted in your first comment.

**Comment by vgaming** [comment]
@gfgtdf yeah I'm OK with how it is now. Just thought it's somewhere deep in C++, not in Lua that I could fix even myself.
OK, glad the issue is resolved now.
