### ISSUE TITLE
floating_label duration is specified in frames, not seconds or milliseconds

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2787]
Given that `[delay]` uses milliseconds, for consistency that's probably the best alternative. This bug also applies to `[message]`, if the duration even works at all there (I haven't tested yet).

**Comment by vgaming** [comment]
Implementation proposals include:
1. add a `time_unit` field which should be either `frames` or `millis`, with "frames" being default
2. add another field `time` or `millis` (exactly one, we have to choose) that would take preference over the existing "duration".

**Comment by CelticMinstrel** [comment]
For the record, it actually doesn't work in `[message]` (and likely hasn't for a very long time), so this only affects `[print]` as far as I know.

**Comment by Vultraz** [comment]
We don't need a brand new key. Just replace the backend so the existing `duration` key counts ms, not frames.

**Comment by gfgtdf** [comment]
> We don't need a brand new key

the idea was to keep compability with code that assumes the old behviour.

**Comment by CelticMinstrel** [comment]
I think there's also worth in changing the key for consistency with `[delay]`, which uses time.

**Comment by gfgtdf** [comment]
i am not a native english speaker, but i think `duration` is more accurate than just `time`, `time` could also mean things like 'when does this message start to show' for example.

**Comment by Vultraz** [comment]
As a native English speaker, I agree with gfgtdf.

**Comment by CelticMinstrel** [comment]
You're both entirely correct, but by that token, `[delay]` should be changed to use `duration` too... although it's not actually a problem in that context since the tag name makes it clear what sort of time is being considered.

**Comment by vgaming** [comment]
Wouldn't `millis` or `seconds` be the best? I mean, we already had "duration". Old WML developers might not even spot the difference fast enough. If, however, we say "seconds", then it's clear we're talking about wall clock time instead of frames.

**Comment by vgaming** [comment]
EDIT ^

**Comment by CelticMinstrel** [comment]
I have no idea what you're talking about? You just need to store the start time and the duration, or perhaps the start time and the end time. If you need fade-ins and fade-outs and movement, those can all be calculated from start/end or start/duration. It makes it a little harder too, but still not all that difficult. Just a little math.

**Comment by vgaming** [comment]
I think there are two basic possible implementations for that. One is simple: check out _current_ frames per second, calculate desired "frames" from "time" and use the calculated "frames".
It'll be incorrect if user changes speed while the [print] is active, but well, it'll work just fine on most cases TBH.

Another solution is to check remaining time per each tick, as you already discussed.

**Comment by CelticMinstrel** [comment]
Framerate isn't up to the user, it's dependent on things like background processes and stuff (unless we have a framerate limiter in place, but I think Jyrki removed it). So really the only solution is to check each tick if the required time has elapsed.

**Comment by stevecotton** [comment]
I believe this was fixed by @gfgtdf in a9d9e48c72e70fd41ae9759e3894752eb9708596.

@CelticMinstrel, as you recently touched this in 1141e976209e8905f3e8f9a446e5cafd17a69cb5, please would you confirm that the issue is fixed?

**Comment by CelticMinstrel** [comment]
Yeah, you are correct.
