### ISSUE TITLE
MP lobby chat scrolling to top on new message if not focused at bottom

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2789]
When chat is scrolled to bottom, then on new message it scrolls as expected.

However, if current focus is in the middle, like https://i.imgur.com/kWFPZ2k.png, then new messages makes it scroll to top https://i.imgur.com/DhdtreQ.png. Expected behaviour would be not scrolling on new message then, and alternative behavior scrolling one line for each new line.

![image](https://i.imgur.com/kWFPZ2k.png)
![image](https://i.imgur.com/DhdtreQ.png)

**Comment by ProditorMagnus** [comment]
This is still happening, so milestone is not correct.

**Comment by Landiss** [comment]
> Expected behaviour would be not scrolling on new message then, and alternative behavior scrolling one line for each new line.

Surely expected behaviour is not to scroll at all in this case? If I'm reading something from the middle of the chat history I don't want to be interrupted by new messages at all.

**Comment by CelticMinstrel** [comment]
Uhh, read again. You said the same thing as him.

**Comment by Landiss** [comment]
Ah, I see. Sorry. That "alternative behavior" part misled me a bit
