### ISSUE TITLE
[filter_wml][or] is broken

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2791]
This is fixed on master, but for 1.14, we need to decide whether to revert 82fd82d53403b8173d234b8a3abef6a1e3ef39c9 or cherry-pick b483d96f500827ccacc78f3c2e89fc6690a3d2df.

**Comment by CelticMinstrel** [comment]
@Vultraz Please specify which.

**Comment by Vultraz** [comment]
Latter would probably be better i think.

**Comment by Vultraz** [comment]
Oops.
\

**Comment by CelticMinstrel** [comment]
I ended up reverting the commit that introduced it for 1.14; meanwhile it's fixed on master (or if not on master, at least on the schema branch, though I'm pretty sure I did cherry-pick it), so this can be closed.
