### ISSUE TITLE
Buggy font characters when font scaling enabling in Windows and Wesnoth.

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#2792]
Wesnoth 1.13.12 with **140% font scaling**
Windows 7 Pro x64 with **125% font scaling**
Monitor 1920x1080

See screenshot:
![wesnoth_and_windows_font_scaling_buggy](https://user-images.githubusercontent.com/10855248/38157229-9d8887a6-348d-11e8-8200-86d3ecd8c1cf.jpg)

Some characters could be visible only for half. And it didn't depend is there full screen for game or not.

**Comment by CelticMinstrel** [comment]
Known issue, probably a duplicate of #1624?

**Comment by Vultraz** [comment]
Font scaling has been disabled for 1.14.

**Comment by amokmen** [comment]
Probably bad decision. New monitors with high resolution would make text smaller and hard to read.

**Comment by Wedge009** [comment]
Font scaling is back in 1.15. I tested 1.15.1+dev with Windows 7 scaling of 114% and Wesnoth scaling of 140%.

**Comment by amokmen** [comment]
Let's close it.
