### ISSUE TITLE
Private chats get lost when joining or leaving a game

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2802]
Subj. Private chats get permanently lost, along with all their contents, if you join or leave any game (possibly observe too).
The chat tabs just disappear, and everything written in them too.

**Comment by vgaming** [comment]
I personally think it's a Breaker, can't release 1.14 with that.

**Comment by ProditorMagnus** [comment]
Public chats as well.

**Comment by ProditorMagnus** [comment]
re #2538, especially #1194

**Comment by gfgtdf** [comment]
is this this behaiopur different from 1.12

**Comment by vgaming** [comment]
@gfgtdf yes, because on 1.12 there were on real "private chat" tabs, so all was written in lobby. Lobby was retained (not sure if it's retained now, gotta check).

**Comment by ProditorMagnus** [comment]
With 1.12 you only lose private messages sent to you while you were in game.

**Comment by vgaming** [comment]
EDIT ^

**Comment by vgaming** [comment]
UPD: currently, the public chat is lost as well. I think we need to retain all of it: the public chat, the private chats.
Adding blocker label since I think this is a blocker.

**Comment by jyrkive** [comment]
Unassigning due to lack of progress.

**Comment by jyrkive** [comment]
I implemented saving and restoring public and private chats in commit 8a0027691363c05fa06657f8c4e466054a530fda.

**Comment by ProditorMagnus** [comment]
Staging chat, "this game" is not saved/restored currently.

**Comment by Vultraz** [comment]
Intended and expected.
