### ISSUE TITLE
chatcolors in wrong color after unasigning side

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2813]
yes, as title says. related to #2357

borken in https://github.com/wesnoth/wesnoth/commit/36e92900c374b801df133b7221a04014b3b20b84, i decided to make a seperate bugreport for this since it seems that in #2357 are multiple bugs involved.

**Comment by ProditorMagnus** [comment]
This also means that when someone becomes observer, he will keep red color and will not be included in observers list.

**Comment by jyrkive** [comment]
Unassigning from loonycyborg due to lack of progress. I'll try to reproduce this and give gfgtdf's proposed fix a go.

**Comment by jyrkive** [comment]
Fixed. The updated server still needs to be deployed, though.

**Comment by gfgtdf** [comment]
i'd still e happy if somone took a deep look at https://github.com/wesnoth/wesnoth/commit/36e92900c374b801df133b7221a04014b3b20b84 and checked whether it may have caused other similar issues.
