### ISSUE TITLE
game crashes if help accessed from main menu

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2814]
repo @ 3f67c2fbf051aa9e322defb66c782477cd53b8bd
I launch the game and click on the "help" button in main menu:
````
Setting mode to 956x1041
Checking lua scripts... ok
WML exception:
User message: Mandatory widget '+introduction' hasn't been defined.
Dev message: Condition '!must_exist || result' failed at ../src/gui/auxiliary/find_widget.hpp:74 in function 'find_widget'.
````

**Comment by Vultraz** [comment]
Working on help refactors. Though not sure why this specifically is happening, I'm not getting it locally, so it should be fixed soon.

**Comment by Vultraz** [comment]
Should be fixed now. Can confirm?

**Comment by matthiaskrgr** [comment]
Confirmed, thanks!
