### ISSUE TITLE
assertion failure: 'gamestate().board_.has_team(current_side())'

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2818]
> 20180401 18:07:17< grzywacz> And finally on OOS: https://gist.github.com/knowak/c97a3484d0dda5fe6261a3ab6aebd57a
> 20180401 18:07:22< grzywacz> (game crashed)

While it's omplteley unclear why it happened in the case observed above, it's not too hard to come up with a way to invoke this assertion failure, We shoudl fix this, the easiest way is probably to make that throw a custom exception (like for example  `invalid_side_numer_exception`) instead of assertion and and catch that appropriately.

**Comment by Vultraz** [comment]
That's an odd assertion... it mean the current side doesn't exist.
```
team& play_controller::current_team()
{
	assert(gamestate().board_.has_team(current_side()));
	return gamestate().board_.get_team(current_side());
}
```

As for exceptions, `get_team` already throws `std::out_of_range` if you want to catch that.

**Comment by gfgtdf** [comment]
> That's an odd assertion... it mean the current side doesn't exist.

Yes it can for example fail if the current scenairo has no sides and the game (or umc  during prestart) does something that acts on the the currentyl active side. Although i don't think that's what happened in the case reported by grzywacz above.

**Comment by Vultraz** [comment]
Perhaps we should track down the issue, then, instead of ignoring it.

**Comment by gfgtdf** [comment]
> Perhaps we should track down the issue, then, instead of ignoring it.

the problem is the information given in th first ps is really not much, so the oynl tihgn we can do there is fixing the cases that i mentioned above.

**Comment by gfgtdf** [comment]
fixed the two possible cases i mentioned above. Since we ahve no information on the original report im closing this.

**Comment by AI0867** [comment]
If referencing the current side during prestart would trigger this, and this can be done through WML, an error message specific for that case would be appropriate.

**Comment by gfgtdf** [comment]
> If referencing the current side during prestart would trigger this.

I think in theory referencing the current side during prestart would trigger this _during a scenario that has no [side]s_ ( a story only scenario) can cause this. In usual scenarios it's just side 1 during prestart events.

**Comment by AI0867** [comment]
That's fine then. I interpreted an earlier message to mean that during prestart, sides haven't been initialized yet, and referencing would cause this, but it appears I was mistaken.
