### ISSUE TITLE
Music playing on lobby UI

### ISSUE THREAD

**Issue by AncientLich** [wesnoth/wesnoth#2824]
I noticed that, unlike wesnoth 1.12, the music theme continue playing when you are connected to lobby.
I don't know if it is intentional or not, but this new behaviour could be considered either positive or negative for user experience, so I am not sure it is a good thing.
Could be an idea to open a poll and see what other users may think about this to understand if this new feature is good or bad?

**Comment by Vultraz** [comment]
Caused by the same underlying issue as #2602.

**Comment by AncientLich** [comment]
I didn't notice that connection. Thank for pointing it.

**Comment by Wedge009** [comment]
Closing this as duplicated of #2602. As I mentioned there, I see this as a good thing but others may disagree.
