### ISSUE TITLE
Allow translating ‘Friends’ differently

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2836]
The word ‘Friends’ appears in two different contexts in the game:
- As the title of a preferences tab (data/gui/window/preferences/05_multiplayer.cfg:415).
- As the label of a checkbox (data/gui/window/lobby_main.cfg:420).

Please, allow translating these strings differently (e.g. ‘Amigos’ / ‘Amigos.’).

Supplied paths and line numbers are for commit 32178aab8197272aed862d83207935c8201534b3 of branch 1.14.

**Edit:** Additional strings in a similar situation:
- Shroud

**Comment by shikadiqueen** [comment]
Why, exactly? Across all of our UI we generally do not use terminating punctuation for tooltips and labels for checkboxes and buttons.

**Comment by Gallaecio** [comment]
I’m not asking to change the English text, but to make whatever changes allow translation to be different for each. In Galician, we do use periods for the checkboxes on top of the multiplayer lobby (but not for tab titles).

**Comment by shikadiqueen** [comment]
Is it **necessary**, or is it just a style choice your team made independently from the dev team?

**Comment by Vultraz** [comment]
I really don't think this is necessary, especially if only a stylistic choice.

**Comment by dagnelies** [comment]
Well, perhaps many prefer "without a dot"? (Including the few Galician users perhaps?)

As a latin-based language speaker (french), this choice seem silly to me. IMHO duplicating translations strings just adds more work and the danger of mismatched strings.

**Comment by Vultraz** [comment]
I don't really feel it's worth splitting the strings just for that. If I'm being honest, I find it slightly silly, but regardless, it also means extra work for translators of other languages who would now need to re-translated this (albeit short) string and any others.

So, yes, we would probably reject a PR for this if you submitted one.

Closing.
