### ISSUE TITLE
Map labels disappear when using dropdowns in dialogs

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#2839]
On latest git from the 1.14 branch, when in any dialog(ex: preferences, unit statistics) and a dropdown is used, all map labels disappear until the dialog is closed.

For example, [before](https://i.imgur.com/f8Imw4r.jpg), then [after selected Random map from the dropdown](https://i.imgur.com/M2llKYB.jpg).

**Comment by Vultraz** [comment]
Known. The best has been done to mitigate it, but it will have to remain this way until 1.15.

**Comment by Vultraz** [comment]
Though technically, I might just close this since I'm sure it's fixed on master already.

**Comment by Vultraz** [comment]
Yeah, just gonna close this. Not going to fix it on 1.14.
