### ISSUE TITLE
The team color → The side’s color

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2842]
When you are setting up a multiplayer game, there is a drop-down control with colors to choose a color for each side. However, the tooltip states that the color is for the team. But when you have two sides on the same team, there is still one color selector per side within the team.

**Comment by CelticMinstrel** [comment]
This is a result of the source code and the WML/UI disagreeing on what a "team" is. In the source code, "team" refers to a single side; in the WML/UI, "team" refers to a sort of grouping of sides.

**Comment by AI0867** [comment]
Extra fun facts: teams are 0-indexed (mostly), sides are 1-indexed, and the WML key grouping of sides into alliances is called `team_name`

**Comment by CelticMinstrel** [comment]
I think we were trying to move towards teams being 1-indexed though. Not sure if it's completed.

**Comment by jostephd** [comment]
Fixed... only a little over a year after the report.
