### ISSUE TITLE
[SotA] Gwyllin vs Gwillyn

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2844]
Translating the campaign, I noticed that there is a unit called Gwillyn, (first i, the y), and there is a dialog message that mentions a unit by name, calling that unit Gwyllin (first y, then i).

I suspect they are meant to be one and the same, and that one of the two forms of the name should be chosen and applied in both cases.

**Comment by CelticMinstrel** [comment]
I like "Gwyllin" better, but I'm not sure if it's the more Welsh-like of the two. (I say Welsh-like because the Wesnoth names are at least partly Welsh-based.)

**Comment by Gallaecio** [comment]
@Vultraz On the 1.14 branch? Doesn’t this break string freeze?

**Comment by Vultraz** [comment]
I added a pofix rule... though I didn't run pofix.
