### ISSUE TITLE
[Help] "affected unit of poison" → "unit affected of poison" or "poisoned unit"

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2849]
Seen at `data/core/macros/abilities.cfg:12` and `data/core/macros/abilities.cfg:30` on commit 32178aab8197272aed862d83207935c8201534b3:

> This ability will not cure an **affected unit of poison**, however, only delay its effect.

Besides the change proposed in the menu title, consider whether that "however" should be moved to the beginning of the sentence ("However, this […], only […].").

**Comment by CelticMinstrel** [comment]
In my opinion this phrasing is fine; "unit affected of poison" is not good grammar, and I kinda don't like "poisoned unit", though I think I could get on board with "unit afflicted by poison".

The movement of "however" doesn't really matter in my opinion; it would work just about as well in either location.

**Comment by Vultraz** [comment]
I think the phrasing is fine as it is.

**Comment by Gallaecio** [comment]
What I found weird is having the object of the affection, "of poison", before the subject, "unit". But it might be just the influence of latin-based languages. Is that phrasing common in English? Can you provide some online examples? I could not find any, but not necessarily because there aren’t — I’m not sure how to search for them.

Also, I did not notice when I reported this, but searching for examples of the current phrasing, I found out that both affected and afflicted seem to require ‘by’ to indicate the object of the affliction, as opposed to ‘of’. Although, if the current construction is correct English, maybe ‘of’ is valid when the object is after the subject.
