### ISSUE TITLE
share_vision (and legacy equivalents) doesn't seem to work in [modify_side]

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2850]
If you reload a save from after the `[modify_side]`, then it works correctly, which makes me think this is probably an engine bug and not a bug in my code. Basically, the vision is not shared at all, even several turns later.

In my opinion this should be a blocker, as it represents a regression (this worked in 1.12) and a totally broken feature. If others disagree they can feel free to remove the label.

The issue cropped up in [this scenario](https://github.com/CelticMinstrel/BlackCrossOfAleron/blob/master/scenarios/05-reinforcements.cfg).

**Comment by gfgtdf** [comment]
Adding some calls to `team::clear_caches` could fix it cannot treat it from my mobile tough
