### ISSUE TITLE
Kills/losses in replays are counted again after starting the replay from the beginning.

### ISSUE THREAD

**Issue by EoZ8** [wesnoth/wesnoth#2852]
Wesnoth 1.13.13

1. Run any replay
2. Wait for it to finish
3. Click start replay from the beginning and wait for it to finish again, the kills/losses in the statistics will be counted again and added to the real kills/losses after the first run of the replay, possible to be repeated indefinitely.

**Comment by Vultraz** [comment]
Maybe @gfgtdf knows where to look for this? Sounds like it just needs a `statistics::fresh_stats()` call somewhere.

**Comment by jostephd** [comment]
#3997
