### ISSUE TITLE
Forward-port #2384

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#2853]
Rather than just cherry-picking #2834, I think it would be better to add an extension to `[set_variables][join]` for this purpose.

**Comment by Vultraz** [comment]
What would the syntax look like?

**Comment by CelticMinstrel** [comment]
Not sure. I'd like to use `separator=and` and `separator=or` as magic values, but not sure if that's an acceptable way.

**Comment by CelticMinstrel** [comment]
Does anyone think that _wouldn't_ be an acceptable way?

**Comment by stevecotton** [comment]
It sounds good to me, but maybe the magical values should be `grammatical_and` and `grammatical_or` - something that would never be used except when wanting the magic behaviour. I can see UMC writers who know that a variable contains exactly two values using [join] with "and" or "or", and it would be surprising if that became "et" or "und" in the middle of an untranslated sentence.

**Comment by CelticMinstrel** [comment]
> I can see UMC writers who know that a variable contains exactly two values using [join] with "and" or "or", and it would be surprising if that became "et" or "und" in the middle of an untranslated sentence.

Exactly what situation could there be where you need to join an untranslated sentence with untranslated "and" or "or"? Even if it's two numbers for example, I'd expect the joiner to be translated.

**Comment by stevecotton** [comment]
I retract my previous comment, the situation that I was thinking about wouldn't happen.

I imagined a WML author who knew that there's exactly two values and hadn't yet implemented translation in their add-on, but in that situation they're unlikely to use `[set_variable][join]` anyway.

**Comment by CelticMinstrel** [comment]
…is it just me or was this never done? Seems kinda important? It would be a regression from 1.14, wouldn't it?

**Comment by stevecotton** [comment]
> …is it just me or was this never done?

By "this" do you mean the fwdport of the fix, or do you mean the `[set_variable][join]` feature?

The fix seems to have been ported in 6150db6b1a835cfa930e7324468bc24b087de53b.

**Comment by CelticMinstrel** [comment]
Okay, since it _was_ forward-ported, I'll close this.

If the join feature wasn't done though, I may still do it later.
