### ISSUE TITLE
[UtBS] References to "horses"

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#2854]
The displayed messages, at least in the first scenario, have some references to "horses", but with the new quenoth elf line-up, this needs to be changed.  I'm not sure where other horse-related references, or other relics of the old elf units, may show up, but I will update this issue if I find more. 
EDIT: "hunters" is another reference which should be changed.

**Comment by ln-zookeeper** [comment]
There's a few still marked with "TODO:" notes in the .cfg files, so there's at least: horses, hunters, blond hair, bow and sword.

As for horses, we haven't even started thinking about what those animals should be called.

**Comment by shikadiqueen** [comment]
I'm rather concerned that this wasn't addressed before the string freeze.

**Comment by CelticMinstrel** [comment]
For the names of the animals we should probably just name them after similar real animals (possibly with an adjective).

**Comment by CelticMinstrel** [comment]
It's too late for anything for 1.14, so we might as well be creative if we can come up with something. We should probably also consider adding `#po:` comments explaining the origin of whatever name we come up with.

**Comment by beetlenaut** [comment]
I know there is a string freeze in effect, but we could still change a spelling mistake couldn't we? Likewise, I think we could change a word that was just wrong as well.

**Comment by CelticMinstrel** [comment]
Spelling mistakes can be fixed, yes.

**Comment by shikadiqueen** [comment]
This kind of thing goes far beyond the scope of spelling mistakes (which are normally handled with `pofix` to not disrupt the translators' workflow) and ventures into the dreaded territory of grammar and semantics, so it absolutely cannot be handled during a string freeze. The next release is slated to be 1.14.0 gold, so we're not lifting the string freeze even temporarily until 1.14.0 is announced either unless it's to introduce strings required to fix an unprecedented critical bug. The UtBS maintainers' lack of planning in this regard (and choice to stay completely silent on the matter even during the string-thawing rampage between RC 1 and RC 2) doesn't qualify as one such situation.

**Comment by doofus-01** [comment]
Just want to drop a link to the forums, where we are trying to come up with a new name for the "horses":
https://forums.wesnoth.org/viewtopic.php?f=32&t=48117
