### ISSUE TITLE
Manual image localization instructions do not match the latest screenshots

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2856]
The last update of manual images, done at fe9729e8c6f9838c59648d1d02f8a3211014d373, does not seem to follow the image-capturing instructions provided in the README file where the images are, which translators use to reproduce the manual images as accurately as possible with their own locale.

Specifically, some images are in PNG format instead of JPEG (which is lighter and I think makes more sense for the manual), and two images are not taken following the instructions depicted on the README (`doc/manual/images/game-screen-1.13.11+dev.jpg` and `doc/manual/images/recruit-1.13.11+dev.png`).

Please, either repeat the screenshots following your own instructions on the README file, or modify the README file accordingly.

**Comment by jyrkive** [comment]
Argh. I completely missed that there was a README for manual images when I updated them.

It's not important that the images in different locales are as similar as possible, the manual text doesn't talk about the details in images anyway. I plan to change the wording in the README accordingly.
