### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [wesnoth/wesnoth#2858]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by GregoryLundberg** [comment]
We have a logo.

**Comment by soliton-** [comment]
To find something to contribute graphics-wise it's better to ask in the art contributions section of our forum: https://forums.wesnoth.org/viewforum.php?f=9

**Comment by GregoryLundberg** [comment]
Not sure: The account on GitHub is 21 day old and has been going around with the same proposal elsewhere (like 17 or 18 elsewheres, so far).
