### ISSUE TITLE
[macOS] Thin unreadable font issue with new versions of pango

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#2859]
I just tested that this font problem is reproducible with every version of pango after `1.40.1`:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/2218817/38524235-365bd6aa-3c4e-11e8-8656-a590898d1ff5.png">
<img width="675" alt="image" src="https://user-images.githubusercontent.com/2218817/38524244-3f567850-3c4e-11e8-9f2b-cc90060c38b1.png">

This issue is **NOT** blocker, because macOS packages use my new MacCompileStuff, which contain latest working pango `1.40.1`.

* It is reproducible in every language, not Czech specific.
* This issue exists since @Vultraz added new thin fonts in (I believe) this commit: https://github.com/wesnoth/wesnoth/commit/2e81aed96d9d524ead5efc01900bae317901107d

**Comment by sevu** [comment]
On Archlinux with pango 1.42.1 are no issues.

**Comment by hrubymar10** [comment]
Yes, we already know that it is macOS specific.

**Comment by GregoryLundberg** [comment]
Confirming. Downgraded Arch to Pango 1.40.1 to match macOS and the font remains visible. I do see the issue on my macOS VM.

**Comment by Vultraz** [comment]
If this is upstream we should report this to the Pango team.

**Comment by hrubymar10** [comment]
Yes we can, but I think that they won't care.

I want compare 1.40.1 and 1.40.2 and find the bug myself. If I'll find it, then I'll be able to report it to pango with more details so they will have bigger motivation to fix it.

**Comment by hrubymar10** [comment]
Update:

It looks that it is caused by this commit: https://github.com/GNOME/pango/commit/fcec6f721d5254b9010814023f98f541ca798b02

I openned issue: https://bugzilla.gnome.org/show_bug.cgi?id=795188

**Comment by hrubymar10** [comment]
**Update:**
It is better with latest version of Pango 1.42.3 but issue is still here:
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/2218817/43927981-922d1e26-9c2f-11e8-97d7-f6833bf2938a.png">

**Comment by hrubymar10** [comment]
## Update:
Latest version Pango 1.45.3 seems to work without problems with at least `master` branch

**Comment by hrubymar10** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2218817/88565621-291f9080-d035-11ea-988f-61618c7fb461.png">

**Comment by hrubymar10** [comment]
Pango 1.45.3 works in both `master` and `1.14` branch.

Pango 1.45.3 is now included in [MacCompileStuff](https://github.com/hrubymar10/MacCompileStuff) since [this commit](https://github.com/hrubymar10/MacCompileStuff/commit/3fb550e0f25fb14bfcac7142221f05151a5bc5d3).

Closing
