### ISSUE TITLE
Commits to backport for 1.14.1

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2866]
- [x] Commit a4dd74c32afb2f6c37453eafb60f60b8b215df01 needs backporting for 1.14.1.

**Comment by sevu** [comment]
Let's collect all commits in ine issue instead of opening a new one for each:
- [ ] f0f664b needs to be backported too

**Comment by Vultraz** [comment]
- [ ] 1942627

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/commit/d31e74aee0028bdb0c7d7dbc74d4ec05389a9298

**Comment by Vultraz** [comment]
All the above backported.
