### ISSUE TITLE
The Galician translation freezes the game when opening the ‘Recruiting and Recalling’ page of the help

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2874]
Tested on branch 1.14, commit 0854bf8fe3. Reproducible using the Galician (gl) translation, but not the source language (en_US) or the Spanish (es) translation.

Steps:
1. Run the game in Galician (e.g. `LC_ALL=gl wesnoth`).
2. Select ‘Help → Gameplay → Recruiting and Recalling’ (‘Axuda → Manual → Recrutar e reincorporar’).

Expected result: The help page opens.
Actual result: The game freezes.

I believe there are two issues to fix there:
- Whatever I did on the Galician translation that triggers the issue. I’ve been unable to see anything wrong with the translations of that page at a first glance, so I would appreciate any help on finding out the underlying cause.
- Whatever a translation does, the game should probably not freeze.

**Comment by Gallaecio** [comment]
Issue found, the usage of `<b></b>` on a string that does not has such syntax in English.

I’ll soon send a fix for the translation. I think the issue should remain, with the goal to prevent manual page translations from freezing the game, but I would consider it a low-priority issue,

**Comment by shikadiqueen** [comment]
It appears that the game tries to display an error message using GUI2 stating that invalid markup was found in the help text, but somehow the UI hangs up instead.

(An easier way to reproduce without using translations is to replace `is` with `<b>is</b>` in the first `[topic] text=` attribute around `data/core/help.cfg` line 98, by the way.)

Backtrace using 1.14 at commit 719ee4f5cdc61bba7d200a2d9f46abe80c0cc5dc:
```
#0  0x00007ffff70612e0 in __GI___nanosleep (requested_time=0x7fffffff9ef0, remaining=0x7fffffff9ee0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007ffff4527915 in  () at /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#2  0x0000555555933ecd in gui2::window::show(bool, unsigned int) (this=0x55555a911a90, restore=false, auto_close_timeout=0) at src/gui/widgets/window.cpp:572
#3  0x0000555555b1a4b5 in gui2::dialogs::modal_dialog::show(unsigned int) (this=0x7fffffffa310, auto_close_time=0) at src/gui/dialogs/modal_dialog.cpp:89
#4  0x0000555555b5f4bb in gui2::show_transient_message(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool) (title="", message="Parse error when parsing help text: 'Error when parsing help markup as WML: 'Unexpected characters after variable name (expected , or =)\nat <unknown>:2''", image="", message_use_markup=false, title_use_markup=false, restore_background=false) at src/gui/dialogs/transient_message.cpp:70
#5  0x0000555555c6f338 in help::show_help(help::section const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) (toplevel_sec=..., show_topic="", xloc=40, yloc=75) at src/help/help.cpp:240
#6  0x0000555555c6e6d5 in help::show_help(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) (show_topic="", xloc=-1, yloc=-1) at src/help/help.cpp:118
#7  0x0000555555b52bb3 in gui2::dialogs::title_screen::<lambda()>::operator()(void) const (__closure=0x5555588f2620) at src/gui/dialogs/title_screen.cpp:292
```

**Comment by Vultraz** [comment]
There's an issue with that in 1.14. A GUI2 dialog cannot properly display over the GUI1 Help, but the game thinks its open, so there's nothing one can do. I could have sworn I disabled the code that shows the message...

**Comment by Vultraz** [comment]
ah, no, I see, I disabled a separate popup.

**Comment by Gallaecio** [comment]
Tested, this is the current behavior after your changes:
- If the help is opened from the title screen, the help window closes when trying to open the problematic page.
- If you try to open the page from a recruiting dialog, nothing happens.

Definitely a better experience than a crash.

**Comment by Vultraz** [comment]
Good enough. I can add a cerr message or such later.

**Comment by CelticMinstrel** [comment]
Another possibility might be to insert the error text as the help topic.
