### ISSUE TITLE
Allow a gender-specifc translation of a certain tutorial message

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2875]
At some point during the tutorial, Galdrad says to either Konrad or Li’sar the following:

> Hang on! You need to gather your forces. Or do you intend to fight the orcs single-handedly?

In Galician (gl), I need to translate this string differently depending on whether the message is for Konrad (single-handedly → soíño) or for Li’sar (single-handedly → soíña).

**Comment by CelticMinstrel** [comment]
I was just recently thinking that `[message]` could use a way to distinguish the addressed person's gender (and number!), and here's an example already.

I think there's a macro in the tutorial for this very purpose though, so we'll have to make do with that.
