### ISSUE TITLE
Outdated button label reference in a message tutorial (and similar issues)

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2882]
(all referred to commit 6a085e490f1798ec931b5c4a13266b6663c38869 of branch 1.14)

At some point, the **OK** button in the attack dialog became **Attack**, which I believe is great.

However, now there is an outdated message at `data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg:340` and `data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg:347`:

> To attack the quintain, first select the attacker (Li’sar), then the target (the quintain). You will see an attack description. When you click &lt;b>**OK**</ b>, Li’sar will attack.

I took the chance to see if I could find some other similar issues in the code with a simple `grep "\bOK\b" * -EIR --exclude-dir po`, and I found these issues:

Issue regarding the **OK** button on the recruitment dialog, which now reads **Recruit** instead:
**data/core/help.cfg:**`        text="<img>src=help/recruit.png align=left float=yes</img>" + _ "Each side begins with one leader in their keep. At the start of any battle, and at times during it, you will need to recruit <ref>dst='..units' text='units'</ref> into your army. To recruit, you must have your leader (for instance, Konrad in the <italic>text='Heir to the Throne'</italic> campaign) on the keep hex of a <ref>dst='terrain_castle' text='castle'</ref>. Then you may recruit by either choosing <bold>text='Recruit'</bold> from the menu or right-clicking on a hex and selecting <bold>text='Recruit'</bold>. This brings up the recruit menu, which lists units available for recruitment, along with their gold cost. Click on a unit to see its statistics, then press the `**OK**` button to recruit it." + _ "`

Issues regarding the **OK** button to install add-ons from the add-on manager, which is now a **plus sign button** instead:
**data/core/help.cfg:**`To install an add-on, select it from the list and click <bold>text='`**OK**`'</bold>, or simply double-click on the add-on’s title. The <bold>text='Description'</bold> button provides you with additional details about the add-on, such as its full description, installation status, and available languages."`
**data/tools/addon_manager/html.py:**`    <p>To install add-ons using the in-game client, choose “Add-ons” from the main menu, and click “Connect” to connect to the add-ons server. Pick the add-on you want to install from the list and click “`**OK**`” — the download will commence immediately and the add-on will be automatically installed once finished. Bear in mind that not all add-ons are singleplayer campaigns!</p>`

I am not sure if the following message has an issue or not. On campaign scenarios there is no OK button, you have to press Space (or click or something, I’m unsure) to close that dialog and Finish to finish the scenario.
**doc/man/wesnoth.6:**`exits once the scenario is over, without displaying victory/defeat dialog which requires the user to click `**OK**`.`

And finally a message where the OK is not the issue:
**utils/umc_dev/manual/dev_manual.tex:**`\item Press Finish and OK until you `**exist**` all windows.`

**Comment by Wedge009** [comment]
Click Attack was corrected in 8b492a3a (master and 1.14). The rest I've updated in PRs #3001 and #3002.
