### ISSUE TITLE
The toggle buttons under the minimap have recently stopped working

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2884]
They stopped working in 64ef0eb1e6830fc61a617a094b6f0cbb6cf97dfc. They were working on the commit right before that one, 0854bf8fe3c594ce4fc0e670574e80090a1865e6.

**Comment by Gallaecio** [comment]
@jyrkive You might want to look into it.

**Comment by Vultraz** [comment]
Also affects toolkit buttons in the editor.

**Comment by jyrkive** [comment]
Fixed in commit a0b54b1513e840498e90572e0e4b9687df36a9cd.
