### ISSUE TITLE
On the Statistics, move "Campaign" into the drop-down list and remove the tabs

### ISSUE THREAD

**Issue by Gallaecio** [wesnoth/wesnoth#2886]
This is an enhancement suggestion, feel free to close it if you believe the current UI is better.

It is about the Statistics dialog that you open during a scenario of a campaign. This is in short what I mean (made with KolourPaint, do not judge me):

![add-campaign-to-drop-down-list-and-remove-tab-bar](https://user-images.githubusercontent.com/705211/38766062-bb7c65da-3fcc-11e8-95f8-468f6e8cd7f1.png)

Currently, it has a drop-down list where you can select a specific scenario to see the data specific of that scenario, and it has a tab bar with two tabs, Scenario (to show the data of the scenario from the drop-down list) and Campaign (to show the data of the whole campaign, regardless of the scenario selected on the drop-down list).

I think that we should move "Campaign" into the drop-down list (e.g. as "All Scenarios"), add a "Scenario" label to the drop-down list to make it more clear that the drop-down list allows to choose a scenario (currently it has no label), and remove the tab bar, which after these changes becomes unnecessary.

**Comment by Vultraz** [comment]
This is not a bad idea.
