### ISSUE TITLE
add a lua gamemap object

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2891]
just a random idea but i think it might be useful to ahve a gamemap lua object that can be used both in the game_lua_kernel and the mapgen_lua_kernel, it would have functions like for example:
```
create_gamamap(number width, number height, string defautterrain)
create_gamamap(string mapdata)
map:get_locations(SLF)
map:set_terrain(x,y, terrain)
map:get_terrain(x,y)
map:tostring()
map:adjacent_tiles(x,y)
map:terrain_overlay(... (like [terrain_overlay]))

--@returns a gamemap opbject
map:submap(x,y, width, height)
map:blit(other_map, x,y, width, height)
...
flip. rotate, etc.
```

In particular i think that using standard location filter in the lua map generator could be useful, since i have seen some wml map generation that coudl easily be moved to a lua map generator if we have slf support there.

**Comment by CelticMinstrel** [comment]
Full standard location filter support is impossible in the Lua map generator. I guess the things that would work are location, terrain properties, and special locations, and obviously adjacency filters with the same. Probably not much else. I think supporting a subset of SLF might actually be more confusing than not supporting it at all.

**Comment by gfgtdf** [comment]
hmm i think i might aswell use a completreley new and more lua friendly filter syntax then, that's probabl easier to implement anyways.

**Comment by gfgtdf** [comment]
this was implemented, even though it doesn't yet contain all of the suggested methods
