### ISSUE TITLE
load map dialog is slow

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2892]
i thought this was already reported but i couldn't find a report so i'll just report it:

On windows the load/save map dialogs open with a ~5 seconds delay. My suspect is enumerate_storage_devices but i did no testing.

**Comment by gfgtdf** [comment]
do you mean saved game or maps? Since this is the load map editor te number of saved games shouldn't matter. i have two maps created.

**Comment by Vultraz** [comment]
Oh sorry, misunderstood what dialog you were talking about.

**Comment by shikadiqueen** [comment]
If my memory serves (I wrote the code about two years ago after all), the Windows version `desktop::enumerate_storage_devices()` *can* stall for I/O during some `GetVolumeInformation()` calls if one or more volumes with an assigned drive letter are slow removable drives (e.g. optical discs and floppy disks) that Windows can't trust to not have been swapped in the meantime.

**Comment by gfgtdf** [comment]
I don't really know how to find you whether that's the case, but it's quite possible that my system is misconfigured

**Comment by gfgtdf** [comment]
> @gfgtdf Do you still have this? If so, what's your map load configuration?

No, but I have a 'new' pc now so that's kinda expected

**Comment by Wedge009** [comment]
Thanks, re-open if you find this is still a problem.
