### ISSUE TITLE
Internationalize Turn Limit - none

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2894]
![none](https://user-images.githubusercontent.com/21158813/38771931-40da6cd6-402c-11e8-9190-9e3a56fd7bb7.png)

The translation of 'none' in this context depends in German on the word before it, depending if it is female or male it woule be _Keine_ or _Keiner_.

(and what one sees as well on the screenshot, the 'None' for modifications is not the same as the 'none' for the time limit)

**Comment by CelticMinstrel** [comment]
I guess the only solution here would be to have separate translatable strings for each usage of "None".

**Comment by stevecotton** [comment]
@CelticMinstrel lobby_data.cpp line 464

    time_limit = _("none");

**Comment by CelticMinstrel** [comment]
Ahh I missed it because it wasn't capitalized. Alright then!
