### ISSUE TITLE
[UtBS] Wrong help page shown

### ISSUE THREAD

**Issue by beetlenaut** [wesnoth/wesnoth#2902]
Clicking on Nym shows a help page that describes Kaleh's personality, family, and upbringing. (There _is_ a female version of the "Quenoth Youth" type that describes Nym. It's just not showing up.)

**Comment by ln-zookeeper** [comment]
Yeah, possibly Nym should be a variation instead of only a female variation, since AFAICT the help pages do work correctly for variations (WC's, for example). However, what I can do is make the unit type description feature both the Kaleh and Nym texts, and give the single units only their own respective half. I think I somewhat prefer that solution.

**Comment by nemaara** [comment]
@ln-zookeeper since it looks like you fixed this, can we close this issue?

**Comment by ln-zookeeper** [comment]
Right, looks like I completely forgot. Anyway, you're right that the unit type descriptions are now combined, but the single unit descriptions for Kaleh and Nym could still be made to feature only their own personal text. That requires some slight reorganizing of those macros, it seems.

**Comment by nemaara** [comment]
Not sure I'm understanding what you mean by "the single unit descriptions for Kaleh and Nym could still be made to feature only their own personal text". Are you saying that it's better to split them into two unit types (or different variations) after all? Or are you saying that when hovering over their unit type on the side bar, it only should show one of the two descriptions?

**Comment by ln-zookeeper** [comment]
The latter. It's a minor detail, but it'd make sense to do.

**Comment by nemaara** [comment]
Alright, I'll make a commit that fixes this and close this issue when I do so.

**Comment by nemaara** [comment]
See https://github.com/wesnoth/wesnoth/commit/f38fa3d607ac49a6f4bbbb368155ec661ee76c57.
