### ISSUE TITLE
Menu scroll bar bug

### ISSUE THREAD

**Issue by EoZ8** [wesnoth/wesnoth#2904]
Wesnoth 1.13.13

Right click menu scroll bar is bugged.

![image](https://user-images.githubusercontent.com/37751563/38790969-40266462-4134-11e8-83c8-4ecf19a99b18.png)

**Comment by shikadiqueen** [comment]
Like I said on Discord the other day, odds are that the positioning code is not correctly accounting for the 1 pixel-wide frame around the menu since I'm having trouble trying to reproduce it with my regular mouse precision (which doesn't really let me move the pointer in 1 pixel increments).

**Comment by Wedge009** [comment]
Checking in 1.14.9 I can't replicate this. But I may not be getting the exact 1-pixel alignment to trigger it. @EoZ8 is it still an issue for you?

**Comment by Wedge009** [comment]
@jostephd Were you able to replicate this?

**Comment by jostephd** [comment]
No, but a scrollbar that pops up only if you right-click on a particular 1-pixel-high row across the screen isn't high priority.

**Comment by Wedge009** [comment]
Oh I agree with the low priority, I was just wondering if your tagging implied that you could replicate it. I still can't at the moment but maybe I'm not getting that 1-pixel precision needed to trigger it.

**Comment by jostephd** [comment]
It'll probably be a lot easier to replicate this if you temporarily change the source to make the 1-pixel frame a lot wider. I don't know how to do this, though.

**Comment by Wedge009** [comment]
I don't know either. But I gave it a good hard try and found that the context menu is exactly aligned with the bottom of the game window, and carefully shifting the mouse one pixel down and trying again moves the context menu to be above the mouse. Given this, I'm pretty sure this is resolved. If @EoZ8 find it's still an issue, we can always re-open and investigate further.
