### ISSUE TITLE
[UtBS] Help file shows incorrect abilities

### ISSUE THREAD

**Issue by beetlenaut** [wesnoth/wesnoth#2907]
The Quenoth Youth help file shows all the abilities the unit could potentially gain after leveling up, none of which the level-1 unit actually has. Apparently, this bug affects any unit using [advancement] tags with abilities, because it can be seen in UMC as well.

**Comment by Vultraz** [comment]
Pretty sure this is deliberate.

**Comment by beetlenaut** [comment]
Help doesn't show weapon specials, attacks, moves, HP, etc. that it doesn't have but could get by leveling up. Why would it show abilities? Also, it _doesn't_ happen anywhere else. Mages are not shown as having illuminate and teleport for example. That would be confusing.

**Comment by Vultraz** [comment]
It’s possible I misunderstood the code when I was refactoring it....

**Comment by CelticMinstrel** [comment]
I think the ideal outcome isn't very attainable in the current help system; a "close enough for now" solution might be to add those possible abilities to the list of known abilities but not mention them on the unit's page.

**Comment by soliton-** [comment]
It seemed intentional to me as well since there is no way to figure out what those abilities do unless there is some actual unit type with them available in help. Perhaps it can be made clearer what info only pertains to future advancements though.

**Comment by beetlenaut** [comment]
You can't figure out what _any_ ability does until a unit that has it is available in help. That's the normal behavior. You don't even know that an ability exists until you encounter a unit that has it. (The same with weapon specials, uncommon traits, and the units themselves.)

**Comment by beetlenaut** [comment]
Do you mean you that can't get to the help screen? Because you can. Both of these buttons work, so you can look up the abilities just like for any other unit. Did I misunderstand?

![advance](https://user-images.githubusercontent.com/4147859/39113040-30ca6e04-468f-11e8-91be-e33a916d1aec.png)

**Comment by soliton-** [comment]
If that shows you the new ability descriptions then I‘m misremembering and then it certainly looks like a bug. I‘m currently playing a different campaign with similar advancement options were I‘m fairly sure that you can‘t see these things. I‘ll have to explicitely check utbs again...

**Comment by soliton-** [comment]
The issue is that help pages are for unit types not for specific units. Thus you can only show their potential (stuff in [advancement] tags) or not show any of it.

Since I‘m not aware of a better fix until we get help pages for single units I think showing the description for potential abilities/weapon specials is better than not showing them.

**Comment by soliton-** [comment]
There’s #2582 and #1091 related to this. Probably not useful to keep all of them open but I‘ll let others decide that.

**Comment by beetlenaut** [comment]
I filed a bug report with a UMC author because a listed ability wasn't working. (It was actually available at the third level-up.) If I was confused, a lot of other people are going to be confused. For that reason, I strongly disagree that we should list abilities that the units don't have--listing nothing would be a lot better. When the unit levels, the potential abilities [i]are[/i] shown as options on [i]that[/i] screen. The player can look them up in the abilities section in help at that point to find out what they do, so @CelticMinstrel's suggestion would be fine for now.
