### ISSUE TITLE
editor shows no gui

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#2908]
wesnoth @ 7821f470c2c70eb0865f27b3baece9d0ce91afbc

Theres no gui in the editor.
Is there already a ticket for that?
![editor_nogui](https://user-images.githubusercontent.com/476013/38792956-9457f292-414f-11e8-8be9-bf781e7af2eb.jpg)

**Comment by Vultraz** [comment]
I mean, it's pretty obvious. Didn't think we needed a ticket :P

**Comment by Wedge009** [comment]
master in general is still unstable at the moment, isn't it? If I was to report every single bug I found in master currently I think I'd be here all year!

**Comment by CelticMinstrel** [comment]
@Vultraz, I really think this should be the 1.15.0 milestone, not 1.16.0.

**Comment by matthiaskrgr** [comment]
Game is still unusable @ de99a381723dad41153917696e5468b5e0a99894 
![wesnoth_gui](https://user-images.githubusercontent.com/476013/43885919-9018b818-9bba-11e8-9d34-180dbedfa790.jpg)

**Comment by gfgtdf** [comment]
i assume this is fixed with ar revert?

**Comment by Wedge009** [comment]
Yes, this is resolved in 'new' master.
