### ISSUE TITLE
Wesnoth won't run in High Sierra's 64-bit-only test environment.

### ISSUE THREAD

**Issue by beeflin** [wesnoth/wesnoth#2916]
Apologies if this is already in progress, but I have searched and couldn't find a reference to this problem.

In macOS 10.13.4, users are warned that 32-bit apps will be unsupported in future releases of macOS, and according to Apple's publicity the change will come this year. Wesnoth 1.12.6 invokes this warning, and doesn't run in the 64-bit-only environment set by the boot argument _boot-arg: -no32exec_. So I hope a 64-bit version is in development.

Again, apologies if this is well known and I am merely incompetent in finding a reference.

**Comment by hrubymar10** [comment]
It is already solved. Upcomming wesnoth 1.14 will be 64-bit only, so no more warnings and problems.

Thank you for reporting anyway.

**Comment by beeflin** [comment]
Thank you :-) Good to hear!
