### ISSUE TITLE
tutorial string changes for 1.14.1

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2917]
> To attack the quintain, first select the attacker (Konrad), then the target (the quintain). You will see an attack description. When you click <b>OK</b>, Konrad will attack.

This button was renamed to <b>Attack</b>.
There are two strings, for Konrad and Li´sar

**Comment by sevu** [comment]
Not exactly sure how to word it, just changing the bold part sounds stupid, must be a bigger change.

**Comment by CelticMinstrel** [comment]
"Click Attack when you're ready."?

**Comment by sevu** [comment]
Sounds good!

**Comment by sevu** [comment]
Included in master with 8b492a3, I close this and add the commit to the backport issue.
