### ISSUE TITLE
Does not build with boost 1.67

### ISSUE THREAD

**Issue by t-zuehlsdorff** [wesnoth/wesnoth#2923]
When trying to compile Wesnoth 1.12.6 on FreeBSD 10.4 with boost-libs-1.67.0 it does not work. Here an log: https://ptpb.pw/DVLR

On FreeBSD 11.1 it works. Can you please help figure out what needs to be patched / changed in order to get it compiled?

**Comment by Vultraz** [comment]
I suggest you build the 1.14 branch as opposed to 1.12. We aren't really supporting 1.12 anymore as 1.14 is about to become the new stable series. 1.12 doesn't even use C++11 and as far as I know, no one on the dev team has built it in a long time.

**Comment by t-zuehlsdorff** [comment]
This wouldn't make any sense. 1.12 is the official release. Since i'm maintainer of the wesnoth package for FreeBSD i will need 1.12 to build ;)
The only other option is to remove Wesnoth from every FreeBSD 10.x build, which would be very sad.

**Comment by Vultraz** [comment]
We're tagging 1.14.0 in 5 days and plan to announce it on May 1st. So it'd be best to get a 1.14 build working in any case :P

**Comment by t-zuehlsdorff** [comment]
Ok, i'm fine with this ;)
I have a 1.13 build, but its not fully tested. Looking forward the release :)
