### ISSUE TITLE
Logging in with an unregistered, then changing it to a registered nick does not work

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#2925]
Related to forum accounts now being [required](https://forums.wesnoth.org/viewtopic.php?f=6&t=48014) to log into the 1.14 MP server, it is not currently possible to attempt to log in with an unregistered nick, then change it to a registered nick and finish logging in.  Instead, this results in Wesnoth getting stuck on the "Logging in..." screen and never getting to the MP lobby.

**Comment by Vultraz** [comment]
Confirmed fixed.
