### ISSUE TITLE
Horizontal scroll bar in Load dialog

### ISSUE THREAD

**Issue by beetlenaut** [wesnoth/wesnoth#2930]
The layout in the Load dialog sometimes breaks down and a horizontal scroll bar gets inserted. I couldn't figure out what triggers it exactly, but I can tell that it depends on what the filenames are. You do need to have at least 18 files so that a vertical scroll bar is necessary, and you need to have a long file name that requires an ellipsis somewhere in the list. There is at least one more condition that might have something to do with a day name in the date, but I couldn't pin this one down.

![load_dialog](https://user-images.githubusercontent.com/4147859/39081404-9487124e-44f5-11e8-9f47-6b30de564494.png)

**Comment by Wedge009** [comment]
I'm pretty sure this is a duplicate of #2006.

**Comment by beetlenaut** [comment]
It seems to be. I remember searching for it before creating the issue, but I must have done something wrong. Sorry.

**Comment by Wedge009** [comment]
No worries. I'll close this one because the other has more info, plus this one has been linked to it anyway. Thanks for the confirmation.
