### ISSUE TITLE
MP Lobby chat: Link with line break is not displayed as link

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2934]
![image](https://user-images.githubusercontent.com/7848963/39087046-3d1f00f8-45a3-11e8-8795-1aaae710b333.png)
Second message has link that is still clickable, but is not yellow with underline.

**Comment by stevecotton** [comment]
I think the bug report is inaccurate - the bug is that only the first instance of a given URL will be highlighted, and word-wrap doesn't matter.
