### ISSUE TITLE
initial lobby scroll position

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2935]
When you first join MP server and the lobby, your previous chat gets loaded into "chat" text area. The questionable thing about it is scroll position. Currently it's "top", whereas I think it should be "bottom".

Steps to repro:
* start v1.13.14+dev (75828004ff-Clean)
* join multiplayer server
* check the scrollbar on the right of the textarea. If it's not present, write a number of messages and re-join MP server
* upon joining MP server with scrollbar you'll see that text is scrolled to "top". Expected behavior is to scroll it to "bottom".

**Comment by vgaming** [comment]
// On a separate note: big thanks for implementing chat persistence! It's awesome, I totally love it.:heart:

**Comment by vgaming** [comment]
I found out that chat history is not preserved between program restarts.
This makes this issue very low-priority. I'll close issue if it doesn't get any positive reaction in 24h.

**Comment by CelticMinstrel** [comment]
I think this is probably very easy to do, though.
