### ISSUE TITLE
Prose for the Storm Trident [low priority]

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2936]
The description of the Storm Trident is

    msgid "This trident allows a merman to shoot electric bolts at his enemies!"

> The English original isn't Wesnoth's style. Lightning involves electrical energy, but the word "electrical" was unknown during the middle-ages, the word's origins can be traced to 1601. And a trident being a SHOOTING weapon seems unusual to me...
>
> Improvements:
> This trident gives a merman the power to hurl (elemental) bolts of lightning at his enemies.
> This trident gives a merman the power to throw lightning at the enemies.

The storm trident seems to use the same animation as Delfador's lightning, calling lightning down from the sky rather than shooting it from the weapon, and all of this sounds better prose than the current text. Also, #722 points out that the current text isn't gender-neutral.

> The quoted parts are comments from the German translation by Christoph Berg in 162fbdd19f759d8aa9f51708f05dad83e0da929a

**Comment by sevu** [comment]
Looks like I forgot to close this.
