### ISSUE TITLE
Status Table Dialogue uses strange line formatting

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2941]
Both the msgids and msgstrs do not use any linebreaks, it's _the engine_ which does that.

German version
![linebreaks](https://user-images.githubusercontent.com/21158813/39089972-b03a8894-45d2-11e8-871b-331b16255720.png)
English version (image upscaled by github)
![eng](https://user-images.githubusercontent.com/21158813/39090009-786ae3c2-45d3-11e8-9470-047d16d10696.png)

- The issue appears in the columns where the engine places in English linebreaks
- In cases where linebreaks could be usesd in German that's not happening, since it starts in the 2nd line
- German uses longer words

(The German translation for this window is currently being reworked)

**Comment by gfgtdf** [comment]
> Both the msgids and msgstrs do not use any linebreaks

a quick look at the source says otherwise: https://github.com/wesnoth/wesnoth/blob/1.13.14/data/gui/window/game_stats.cfg#L311

**Comment by sevu** [comment]
Another possible outcome:
![threeliner](https://user-images.githubusercontent.com/21158813/39556835-98673af0-4e83-11e8-95e1-8668b9d6a337.png)

I found a way to translate it in German without running in this (already in the repo)

**Comment by jostephd** [comment]
@sevu So can this be closed? Looks like the original problem is solved.

**Comment by Wedge009** [comment]
Closing for @sevu. (: Re-open if needed.
