### ISSUE TITLE
Tutorial: text clarifications

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2950]
Texts from the Tutorial which could need fine tuning. I currently don't have an idea from them in mind. Maybe someone else has?

- [x] marksmanship explanation:
> Advancing a level has fully healed me! I always have a 60% chance of hitting with my <i>Marksman</i> ability, and I deal 9 damage each for 4 attacks. Use me to dislodge hard-to-hit units.

It doesn't mention that (in contrast to magical) it can be more than 60%, and also not that it only works offensively. Eventually it could be mentioned that it works only with the bow.

- [x] time of day explanation
> During a scenario, the time of day will shift as turns pass. There are four <i>alignments</i> a unit may be: Lawful, Neutral, Chaotic, or Liminal. Each alignment gets a different bonus or handicap depending on the time of day. You can mouse over the landscape image below the minimap on the right to see the current time of day and who has the advantage.

It's no longer a landscape image since we have the new pictures.

- [x] first thing taught to the player:
> When you select a unit, in this case Konrad, the places he can move to are highlighted.....To move, simply click on your destination.

The fields are also highlighted when being on mouse over, but not clicking the unit. To move, one must then first click. The description could be more accurate here.

- [x] S2, fight in the east:
> You could. However, elves (and orcs) have bad <i>defense</i> in water. You’ll be more vulnerable as you try to wade slowly across the ford; the enemy will have an 80% chance to hit you. Since elves have good defense in the forest, I would advise you keep to the trees and attack the orcs from there; you’ll only have a 40% chance of being hit in return.

40% is true for Elvish Fighters, but Shamans and Archers have 30% - best to come up with a new phrasing.

########################################################
- [x] wesnoth-help:
> Each side begins with one leader in their keep. At the start of any battle, and at times during it, you will need to recruit <ref>dst='..units' text='units'</ref> into your army. To recruit, you must have your leader (for instance, Konrad in the <italic>text='Heir to the Throne'</italic> campaign) on the keep hex of a <ref>dst='terrain_castle' text='castle'</ref>. Then you may recruit by either choosing <bold>text='Recruit'</bold> from the menu or right-clicking on a hex and selecting <bold>text='Recruit'</bold>. This brings up the recruit menu, which lists units available for recruitment, along with their gold cost. Click on a unit to see its statistics, then press the OK button to recruit it.

Likewise the button was renamed from OK to recruit.

- [x] wesnoth-help2:
> Modifications are optional scenario- and era-independent scripts for <italic>text='Multiplayer'</italic> games that can alter the default ruleset in various ways. You can choose and configure modifications when creating a new game.

Singeplayermodifications exist now too

**Comment by Wedge009** [comment]
I've done my best to accommodate these in PRs #3001 and #3002.
