### ISSUE TITLE
MP Create: untranslatable string for 'random' leader

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2954]
![dewfew](https://user-images.githubusercontent.com/21158813/39134049-fd555106-4715-11e8-95b0-72679520a045.png)

I didn't find where and how this 'random' is defined in the code.
Eventually the _random_ (Zufall) which is used for the faction can be reused in 1.14.0.
In the long run I think it's a bit confusing to have so many ways to display randomness, eventually it should be a separate string later.
Or should there just be a – instead of _random_.

**Comment by Vultraz** [comment]
Unrelated, but why is there a space before "Faction"?

**Comment by gfgtdf** [comment]
My first guess would be that that label is center aligned

**Comment by CelticMinstrel** [comment]
The label should be right aligned in my opinion, so that the colons line up.

**Comment by Vultraz** [comment]
I’m pomdeeing removing the labels altogether.

**Comment by CelticMinstrel** [comment]
I think that could be quite confusing if some parts are random and others aren't.

**Comment by gfgtdf** [comment]
well youd just show a dice only for the random parts, clearly we cannot remember the label without adding another way (images) to show that information

**Comment by Wedge009** [comment]
So my attempt to fix this caused #4472 - it seems to me that this plain string "random" is being used both as a leader type name as well as a string for display. Need to separate those meanings somehow - plain strings aren't good for indicating type.
