### ISSUE TITLE
Wesnoth crashes if password is empty

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#2959]
Version: 1.13.13
OS: Windows 10
Steps to reproduce:
1. Connect to the official server using random login
![1](https://user-images.githubusercontent.com/3605541/39211218-44f81ec6-480b-11e8-819d-2ba4e9ba944c.PNG)
2.  Leave password empty, click OK button
![2](https://user-images.githubusercontent.com/3605541/39211219-45162556-480b-11e8-91bb-a7b48a44200f.PNG)
Result:
![3](https://user-images.githubusercontent.com/3605541/39211220-45356628-480b-11e8-963d-f86624b0f45b.PNG)

**Comment by sevu** [comment]
Thanks for the Report. I could reproduce it with 1.13.14. This doesn't happen with the version in the 1.14 branch, in that case there happens just nothing if you click OK.

**Comment by sevu** [comment]
The commit message states it fixes an regression introduced in 1.13.14, but this report from 1.13.13

**Comment by shikadiqueen** [comment]
Do you have any idea then where it might've come from or whether it's actually not fixed?
