### ISSUE TITLE
Surrendering with Shuffle Sides on does not work correctly

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#2960]
I found that using the Surrender option in a 1v1 game with Shuffle Sides enabled, at the very beginning, when you are the host and it's not your turn, causes an issue where the host's client displays an error message from the server, while the other client doesn't and only sees the surrender notification:

![1](https://user-images.githubusercontent.com/489895/39220791-c1efbf9e-4809-11e8-938a-642bd4a950e8.png)

Furthermore, after the other player ends their turn, the host is still able to play as if they hadn't surrendered in the first place. The other player is able to surrender themselves and then control of their side is transferred to the host as well.

I started a new 1v1 game with Shuffle Sides disabled and surrendered immediately at the start during my turn as the host and it worked as expected, so I suspect this has something to do with Shuffle Sides specifically.

**Comment by shikadiqueen** [comment]
(As an aside, it's not obvious how surrendering is supposed to work when it's not a 1v1 game.)

**Comment by Pentarctagon** [comment]
Currently it seems like it just gives control of the surrendered side to the host.

**Comment by Wedge009** [comment]
Is this still an issue? I did the following on 1.15.1+dev (I know 1.15.2 release is pending but I haven't recompiled yet):
- Two instances.
- Create 2p game with shuffle sides active.
- While one player is having their turn I surrender on the other player.
- Both instances show the following messages:
> <server> [side2] becomes an observer.
> <server> [side1] takes control of side 2.
> <server> [side2] has surrendered.

Is this expected behaviour? Am I missing something to replicate the original issue (assuming it's still present)?

**Comment by soliton-** [comment]
Did the two sides actually switch? I assume it works fine if the shuffling, by chance, does not actually do anything.

**Comment by Wedge009** [comment]
I think so, because my [side2] was the host, while [side1], the starting player, was the guest. Isn't it the case that the host would normally play first without shuffle active?

**Comment by soliton-** [comment]
If you did no further side configuration before game start that sounds correct.

**Comment by Wedge009** [comment]
No other configuration changes, thanks for confirmation. @shikadiqueen Can re-open if it's still an issue.
