### ISSUE TITLE
1.14.1 quenoth unit descriptions

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2961]
Look if we can include new descriptions before the 1.14.1 string freeze from here:
https://r.wesnoth.org/t47996

There is also mentioned that the higher level Quenoths have no custom costs yet.

**Comment by CelticMinstrel** [comment]
I'd say we probably don't need to worry about the unit costs for 1.14.

**Comment by sevu** [comment]
We don't need to worry, it's only a help/statistics thing, there this entry in the statistics which compares you kills and losses by gold. 

And it makes things easier if someone things the Elves are so great that he/she wants to use them somewhere else.
(For the record, mattsc said in the chat it's not used for the AI currently)

**Comment by CelticMinstrel** [comment]
Oh, it's used by statistics? I suppose for that it might be worth putting the altered costs in 1.14, though still not a priority.

**Comment by mattsc** [comment]
> (For the record, mattsc said in the chat it's not used for the AI currently)
I mis-remembered:
https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/attack.cpp#L67
The attack target evaluation _is_ based on the unit cost.

**Comment by nemaara** [comment]
I'm going to try to get this in for 1.14.7.

**Comment by nemaara** [comment]
#3958 merged, so this probably can be closed.
