### ISSUE TITLE
New "dead" Kaleh sprite needed

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2962]
In UtBS S12 there's a brief sequence where Kaleh is unconscious on the ground. Its image (`UtBS/images/items/kaleh-dead.png`) is based on his own sprite and needs an update to match his new one.

Assigning to @doofus-01 since he did the new sprite.

**Comment by doofus-01** [comment]
I've answered this on the forums:
https://forums.wesnoth.org/viewtopic.php?f=9&t=43345&p=626706#p626706

**Comment by doofus-01** [comment]
I believe this has been addressed in 93f8645
