### ISSUE TITLE
'todo:' notes in help pages for Scenario Editor

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#2964]
some help pages, in particular those about the editor contain are incomplete and contain 'todo:' comments.

**Comment by stevecotton** [comment]
I'd like to re-enable the editor help pages for the 1.15 branch, with the idea that they'll either be improved or hidden again before 1.16.0.

**Comment by stevecotton** [comment]
The remaining todos in the help are only about the scenario editor - retitling the issue to match that.

**Comment by jostephd** [comment]
Marked blocker for the same reason as #4280: We shouldn't release 1.16.0 with todos in the help.

Current list:

```
git grep -ni todo data/core/editor/
data/core/editor/help.cfg:133:    text= "<img>src=icons/action/editor-tool-label_60.png align=left box=yes</img>" + _"TODO"
data/core/editor/help.cfg:141:    text= "<img>src=icons/action/editor-tool-item_60.png align=left box=yes</img>" + _"TODO"
data/core/editor/help.cfg:159:    text= "<img>src=icons/action/editor-tool-village_60.png align=left box=yes</img>" + _"TODO"
data/core/editor/help.cfg:167:    text= "<img>src=icons/action/editor-tool-unit_60.png align=left box=yes</img>" + _"TODO"
data/core/editor/help.cfg:299:    text= _ "TODO"
data/core/editor/help.cfg:349:TODO.>>
data/core/editor/terrain-groups.cfg:8:#TODO
```

**Comment by stevecotton** [comment]
@fendrin what's to be done in the TODO in terrain-groups.cfg, please?

It was added in 169c74ba55048f12731b86b0a537a99f649af3c5, which also adds `[terrain-group]id=autumn` to that file. My guess is that the TODO was just a reminder to add that terrain-group, and you forgot to remove the TODO comment.

Re: jostephd's list:
* for four of them, the subject is obvious
* line 299 is the Time Schedule Editor
* line 349 is about the file format that the Scenario Editor mode uses - should probably include the hints in https://github.com/wesnoth/wesnoth/issues/1380#issuecomment-528818324

**Comment by jostephd** [comment]
If we don't hear otherwise, I suggest to just remove the TODO in terrain-groups.cfg.

@stevecotton Do you plan to work on this further before string freeze? I assume these todos were made user-visible again by your PR, #4414.

**Comment by stevecotton** [comment]
I'm hoping that someone who uses the scenario editor will take over and write the documentation.  Without the knowledge of someone who uses the editor, the only option is to leave a gap in the documentation.

If no-one else does it, then I'll do a clean-up that hides those pages while keeping the terrain-editor's pages visible.

**Comment by stevecotton** [comment]
@Pentarctagon this issue corresponds to the roadmap item "Improve the documentation for the editor, following from the discussion in PR #4999".

**Comment by stevecotton** [comment]
@Pentarctagon although I'd put this in the roadmap for 1.15.5, I think it's going to come much later, possibly as late as 1.15.11 (the milestone for finishing the scenario editor's feature removal).

**Comment by Pentarctagon** [comment]
Alright, I've updated to roadmap to reflect that.

**Comment by stevecotton** [comment]
Note when fixing this - check for dead links by running in `--debug` mode.

**Comment by stevecotton** [comment]
For 1.16, this issue can close now (although I'll leave it open until #5399 merges).

A ping to everyone who commented on this - once #5399 is merged, my plan is to re-enable the editor documentation in 1.14, overwriting the hidden documentation that's currently in 1.14 with the updated data/core/editor/help.cfg from master.

**Comment by stevecotton** [comment]
Closing as fixed in master.
