### ISSUE TITLE
Clean up PO files that include the "prefix^" in the msgstr

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2965]
This is wrong but seems to work:

    msgid "filesystem_path_system^Root"
    msgstr "filesystem_path_system^Root"

For strings that have no translation, the part before the "^" will be removed. The example above shows "Root" because that no-translation handling is also done when the PO's msgstr is exactly the same as the msgid.

But this will later break if someone makes any change to the text, so it seems a good idea to clean it up. For example, this shows as "filesystem_path_system^Wurzel":

    msgid "filesystem_path_system^Root"
    msgstr "filesystem_path_system^Wurzel"

**Comment by Wedge009** [comment]
I suppose this happens when translators don't realise that they're supposed to remove the 'prefix^' part.
