### ISSUE TITLE
Help: Lit stone Wall misses image

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2966]
Terrains > Impassable > Lit Stone Wall is displayed without image in the help, unlike in 1.12.

**Comment by Vultraz** [comment]
@CelticMinstrel what do you think of automatically converting deprecated terrains to a given new equivalent so we can avoid having these old terrains stick around hidden? Or, barring that, some way to actually inform people the terrain is deprecated? We used to have that back in 1.9, dunno what happened...

**Comment by sevu** [comment]
Even if it's deprecated and hidden, the image should be shown too if it still exists in core.

**Comment by Vultraz** [comment]
@CelticMinstrel probably should have specified I meant when they open such a map in the editor.

**Comment by CelticMinstrel** [comment]
Oh, yeah, that's doable. Then you at least don't have to take the trouble of replacing the deprecated terrains yourself. Still needs a deprecated message though, for usage in things like `[terrain]` ActionWML.

**Comment by Vultraz** [comment]
Yeah... wish I knew how it was done in 1.9. I clearly remember being informed about deprecated terrains when I switched from 1.8...
