### ISSUE TITLE
untranslatable overlays in advanced preferences

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#2968]
- [x] In Preferences > Advanced > Logging:
The overlays for the 4 logging levels aren't translatable

- [ ] In Preferences > Advanced > Graphic scaling options:
The Overlays aren't translatable
The settings themself neither
In case the settings aren't removed completely (heard that was an idea) translations hints are needed too, since the casual translator doesn't know _nearest neighbour_ 

Edit: First part is a duplicate of #2837

**Comment by Vultraz** [comment]
The scaling options would only need translating for 1.14 since they'll be dropped in master.

**Comment by sevu** [comment]
They were translatable - just not translated.
