### ISSUE TITLE
Load dialog's sorting by time seems to treat times in the same second as the same

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#2981]
Although the load-game dialog sorts by file time, it seems to fall back to sorting based on the filename for files that are saved at approximately the same time.

For example, when playing a campaign there will be pairs of (replay of scenario X) (start of scenario X+1) that are saved at almost the same time. Those pairs seem to get sorted by filename, even though an "ls -l --full-time --sort=time" sorts them correctly, and shows that the times differ slightly.

If the pair is split in different seconds, then it's sorted as expected.

OS: Linux
Wesnoth: 1.14.0

**Comment by Wedge009** [comment]
Is this still an issue? Testing 1.14.9 release (albeit in Windows), I saved two files in quick succession - both were at 23:07 AEDT but they are sorted in correct chronological order in both Windows Explorer and Wesnoth load dialogue. I haven't checked Linux at this time but can do so if you confirm it's still an issue for you.

**Comment by Wedge009** [comment]
Oh, sorry, I just noticed you specified same second, not same minute.

**Comment by jostephd** [comment]
Something has already been done about it. Here's the code as it was in 1.14.0:

https://github.com/wesnoth/wesnoth/blob/f5fd48dafd78afa710afb8758547f8e4f6ce0bcd/src/save_index.cpp#L236-L251

@stevecotton Is there any chance that you were using a translation at the time? There was another bug here, generating the savefiles used `_("replay")` and this function used `_(" replay")` and some po files translated the two strings differently. I fixed that in https://github.com/wesnoth/wesnoth/commit/5bbc7a6c7c1fe1f8744d96112d420fe1151911d3.

**Comment by stevecotton** [comment]
Thanks for the hint about translations - yes, I was swapping between de, en_US and en_GB. I confirm that I can't reproduce the bug with the currently-selected language, so the fix looks good to me.

**Comment by Wedge009** [comment]
Thanks for confirming.

**Comment by jostephd** [comment]
And I confirm that de is one of the languages affected:

```
$ egrep '" ?replay"' -A 1 po/*/de.po
po/wesnoth/de.po:msgid " replay"
po/wesnoth/de.po-msgstr " Spielverlauf"
--
po/wesnoth/de.po:msgid "replay"
po/wesnoth/de.po-msgstr "Aufzeichnung abspielen"
```
