### ISSUE TITLE
Base prerequisites are not met 1.14

### ISSUE THREAD

**Issue by zor1984qq** [wesnoth/wesnoth#2983]
Hi
I am using Ubuntu 18.04 bionic
Checking for Boost random library version >= 1.50.0... (cached) no
apt search libboost-random
Сортировка… Готово
Полнотекстовый поиск… Готово
libboost-random-dev/bionic,now 1.65.1.0ubuntu1 amd64 [installed]
  Boost Random Number Library (default version)

libboost-random1.62-dev/bionic 1.62.0+dfsg-5 amd64
  Boost Random Number Library

libboost-random1.62.0/bionic 1.62.0+dfsg-5 amd64
  Boost Random Number Library

libboost-random1.65-dev/bionic,now 1.65.1+dfsg-0ubuntu5 amd64 [installed, automatically]
  Boost Random Number Library

libboost-random1.65.1/bionic,now 1.65.1+dfsg-0ubuntu5 amd64 [installed, automatically]

I cant install 1.62 its bugged on installation and quit with errors. I upgrade my 16.04.4 LTS to 18.04 using sudo do-release-upgrade -d so thats currently strange cause 18.04 LTS is out in release state but I am forced to use -d key so that is considered as developer version, but others prerequisites are met fully and completely.

No matter what build system I use cmake or scons the results are same.

I dont think its useful to show all other outputs of my building endevour cause other things are ok on my newly upgraded system.

**Comment by jyrkive** [comment]
Try passing `--config=force` to SCons so that it rechecks if the dependencies are installed.

**Comment by sevu** [comment]
Closin, as I think this has been resolved.
