### ISSUE TITLE
[TRoW] New Ka'lian Elvish Champion sprite

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#2985]
This guy: https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/The_Rise_Of_Wesnoth/images/units/kalian-elvish-champion.png

He's just used in a cutscene, so he doesn't need animations, but god DAMN this sprite looks horribly out of date. It's pillow-shaded, has hardcoded red team coloring, and doesn't use our current Elf palette.

**Comment by CelticMinstrel** [comment]
The hard-coded team colouring _really_ isn't important (though I suppose it would be a bonus if it had team colouring).

This sprite isn't new, either, it's just that whoever added it didn't wire it in properly.

**Comment by Vultraz** [comment]
I...never said it was new? I don't understand what you're getting at. It's been in the repo, unchanged, since b56fe58eb01ad61c49faae3223dc17642fc8b0de in August 2006.

**Comment by CelticMinstrel** [comment]
Did you not read the issue title?

**Comment by doofus-01** [comment]
Is this guy's attempt good enough?  https://forums.wesnoth.org/viewtopic.php?f=9&t=43345&start=375#p621882

**Comment by doofus-01** [comment]
I took Kasdel's last version and tried to make the fist a bit more clear.  I'm not sure I actually improved it much, but I did at least fix the shadow.  I did not check the magenta TC.
![kalian-elvish-champion](https://user-images.githubusercontent.com/13510196/39412664-dfd3d314-4bd4-11e8-9484-a76a4a471d61.png)

**Comment by Vultraz** [comment]
Ahhhh niiiiice 👍

**Comment by CelticMinstrel** [comment]
Um, I hate to burst your bubble, but I'm pretty sure that's the wrong sprite. Lord Logalmier is the grey-haired elf.

**Comment by CelticMinstrel** [comment]
Okay, I scrolled a bit further in that thread and realized that this is technically not the case. I still prefer the grey-haired version as it seems more distinctive, but that's not really the point of this issue, I guess.
