### ISSUE TITLE
Wesnothd keeps same user in lobby multiple times.

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#2989]
This happened after kicking ghost session with new connection https://i.imgur.com/xwrT3Z9.png

Observing received network traffic proves that this is server-side issue:
```
[gamelist]
[/gamelist]
[user]
available="yes"
game_id="0"
location=""
name="vasya"
registered="yes"
status="lobby"
[/user]
[user]
available="yes"
game_id="0"
location=""
name="Ravana"
registered="yes"
status="lobby"
[/user]
[user]
available="yes"
game_id="0"
location=""
name="Ravana"
registered="yes"
status="lobby"
[/user]
[user]
available="yes"
game_id="0"
location=""
name="bot_Laela"
registered="yes"
status="lobby"
[/user]
```

**Comment by ProditorMagnus** [comment]
Since server crashed today, it is not listed twice there anymore.

**Comment by shikadiqueen** [comment]
Naturally, since a new server instance is started without any knowledge of the runtime state of the previous one.

**Comment by ProditorMagnus** [comment]
Happening today as well https://i.imgur.com/6K0wFd6.png.

**Comment by ProditorMagnus** [comment]
Currently there are at least 7 such ghosts in lobby.

**Comment by ProditorMagnus** [comment]
Now it has increased to 13.

**Comment by vgaming** [comment]
Still happening: https://pointsgame.net/vn971/temp/2018.05.25_23:59:24_1be4c3a.png

**Comment by ProditorMagnus** [comment]
I have not noticed it happening after this commit.
