### ISSUE TITLE
Add a Register button to the MP server log-in dialogue

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#2991]
With forum accounts being enforced for MP games as of 1.14, a request to add a 'Register' button to link to the forum site was made in #wesnoth-dev.

> Urist: Do I need a forum account for multiplayer?
> jyrkive: Yes, you do.
> Urist: I think the game should have a "register" button somewhere
> Urist: justo to open the browser
> jyrkive: Hmm. As little as opening the web browser would work reliably and be easy to implement.
> jyrkive: We'll consider it.
> Urist; thanks 😃

**Comment by CelticMinstrel** [comment]
I'm not sure if I like the idea…

**Comment by Wedge009** [comment]
Just submitting as per @jyrkive's recommendation in chat.

**Comment by ProditorMagnus** [comment]
Showing this button in mp lobby would be too late, then account either exists or is irrelevant.

**Comment by Wedge009** [comment]
I think the request was for the log-in screen, not the lobby itself.

**Comment by Vultraz** [comment]
Implemented in 851b28e (master) and 9d8d8af (1.14).

**Comment by Wedge009** [comment]
Looks good to me. Thanks.
