### ISSUE TITLE
"lobby" chat tab has a "close" button (X)

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#2992]
See screenshot:
![wesnoth-chat-tab-lobby](https://user-images.githubusercontent.com/33452702/39535686-3c4d3332-4e3d-11e8-824a-83191719aa3d.png)

Steps to repro:
* start wesnoth  v1.13.14+dev (75828004ff-Clean)
* join MP lobby
* start creating a new game, wait till you get your own room and a chat belonging to room

It's not important, but I think it's a bug nevertheless.

**Comment by Wedge009** [comment]
Agreed it's trivial but still worth reporting - I'd expect Lobby isn't meant to be ever closed so it shouldn't have a close button even if that button doesn't do anything (and the fact it doesn't do anything can be confusing).

**Comment by Vultraz** [comment]
The lobby tab in staging is hidden in 1.14.0 and later, so this isn't really relevant. But, indeed, you should never be able to close the lobby tab...

**Comment by vgaming** [comment]
@Vultraz oh, indeed.
I really don't understand why "lobby" tab was removed though. Why was it? Considering we have tabs, it makes all the sense to me to have a "lobby" tab too. Doesn't eat too much space/attention in the chat tab bar, does it?

**Comment by vgaming** [comment]
@Wedge009 but it is removed!
![no-lobby-tab](https://user-images.githubusercontent.com/33452702/39565044-28634622-4ebf-11e8-9dda-04fee33e9296.png)
No lobby tab that I could see.

**Comment by Wedge009** [comment]
Hmm, playing 1.14.0 in Steam and 1.14.0+dev (aa772cbe), the tab is still there for me. This is when in the lobby, immediately upon logging into the official server. I haven't joined any room/game yet - I notice your message says 'this game' joined. Are you saying this only happens when you join a game?

If so, that's a different issue - I agree you might want to keep the lobby open in this case, but it's different from the lobby tab having a non-functional X button on it.

**Comment by vgaming** [comment]
@Wedge009 yes, that is indeed a separate question.

> Are you saying this only happens when you join a game?

Yes, "lobby" is hidden when I join any game. As far as I understood, it was done intentionally. OK, I guess I'll have to ask or raise any issues/questions about it separately. Not in this issue.

**Comment by sevu** [comment]
The X should be hidden in the main Lobby UI too.
![x](https://user-images.githubusercontent.com/21158813/39602433-6f8f615a-4f25-11e8-9f73-ecf84c9a1a17.png)
(newest 1.14 build from the repo)

**Comment by vgaming** [comment]
@sevu yes indeed, wonder why I missed it myself when re-checking. So, still needs to be fixed.

**Comment by sevu** [comment]
It's not always shown. My theory is it's not shown the first time you launch the game and enter the lobby, but after joining a game room and returning. Plus, when leaving the MP Server and rejoining afterwards it is directly there.

**Comment by Wedge009** [comment]
It wasn't being shown in the main lobby. But if it was re-appearing after returning from a game room, then I wouldn't have seen that anyway.
