### ISSUE TITLE
Game not responding after connecting to mp lobby

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3004]
It handles events eventually though - logs show that
20180503 22:45:54 error network: caught network error: You have been kicked. Reason: autokick by registered user
happens 7 min after the kick happened
20180503 22:38:56 warning engine: User Wushrogg has unknown game_id: 113

However, it is too unresponsive to actually do anything. https://i.imgur.com/JKDOsWS.png shows that it seems to happen before MOTD.

**Comment by ProditorMagnus** [comment]
It shows notifications, no idea when the message was actually sent though https://i.imgur.com/w0k135c.png.

**Comment by ProditorMagnus** [comment]
Shows notifications happen 70min after the event https://i.imgur.com/ctX7eMh.png.

**Comment by ProditorMagnus** [comment]
Same happens on linux (#3017 setup) too, 100% cpu from wesnoth. Log only has unknown game_id messages (which get updated even though wesnoth is not responsive).

**Comment by ProditorMagnus** [comment]
This is likely caused by users list. When I use default userlist and hide all 3 groups, lobby stays responsive.

**Comment by ProditorMagnus** [comment]
Underlying problem seems to be that list is cleared and refilled every time something changes.

**Comment by ProditorMagnus** [comment]
Today happened even with users grouping.

**Comment by Choicerer** [comment]
Same here, the lobby only works decently if I hide the users list and I seem to be constantly getting messages about an unknown user id in my terminal (like for every user that logs in).

**Comment by ProditorMagnus** [comment]
Today happened with 1.14.2. It stayed in unresponsive state for 2.5h, then it crashed with "Ran out of memory. Aborted.".

Notable error message types:
```
844 times: 20180602 18:21:45 error lobby: Error while applying the gamelist diff: 'illegal index to add child at' Getting a new gamelist.
949 times: 20180602 18:21:45 error lobby: process_gamelist_diff failed!
2123 times: 20180602 18:21:45 error lobby: Ran out of listbox items -- triggering a full refresh
8519 times: 20180602 18:56:21 warning engine: User Satelizer has unknown game_id: 4291
5 times: 20180602 18:56:23 error gui/layout: grid [_content_grid] place: Failed to place a grid, we have 1027,2460 space but we need 759,2542 space. This happened at a grid with the id '_content_grid' in a 'N4gui27listboxE' with the id 'game_list' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui26windowE' with the id 'mp_lobby'.
```

**Comment by gfgtdf** [comment]
just happend to me too 1.14.3 the error log just ontained a lot of there 
```
20180711 20:54:57 warning engine: User Dart_Bob has unknown game_id: 24764
20180711 20:54:59 error gui/layout: Failed to fit vertical list to requested rect; expected bottom edge was 44120180711 20:54:59 error gui/layout: , actual bottom edge was 35920180711 20:54:59 error gui/layout:  (top edge is 113)
20180711 20:55:00 error gui/layout: Failed to fit vertical list to requested rect; expected bottom edge was 35920180711 20:55:00 error gui/layout: , actual bottom edge was 27720180711 20:55:00 error gui/layout:  (top edge is 113)
20180711 20:55:04 warning engine: User echo00 has unknown game_id: 24765
20180711 20:55:04 warning engine: User echo00 has unknown game_id: 24765
20180711 20:55:06 error gui/layout: Failed to fit vertical list to requested rect; expected bottom edge was 44120180711 20:55:06 error gui/layout: , actual bottom edge was 27720180711 20:55:06 error gui/layout:  (top edge is 113)
20180711 20:55:28 warning engine: User Dart_Bob has unknown game_id: 24766
20180711 20:55:30 error gui/layout: Failed to fit vertical list to requested rect; expected bottom edge was 35920180711 20:55:30 error gui/layout: , actual bottom edge was 27720180711 20:55:30 error gui/layout:  (top edge is 113
```

**Comment by gfgtdf** [comment]
confirmed with 1.14.4+dev (appveyour build) aswell

**Comment by gfgtdf** [comment]
ok it happend to me again and it seems to happen when i hover over the 'i' smbol of vertain games. Currently there is a game 'Jeu de Welendas' that casues this.

**Comment by ProditorMagnus** [comment]
That game entry for the record https://pastebin.com/ffmZgzZy

**Comment by gfgtdf** [comment]
ok was able to 'fix' this by replacing the condition in https://github.com/wesnoth/wesnoth/blob/1.14/data/gui/window/tooltip_floating.cfg#L97 with just 0, i ahve no idea why that code exists in the first place though, so i'd prefer to have some other opinions bewfore changing it.

**Comment by ProditorMagnus** [comment]
Opening user list does not cause notable issues anymore.
