### ISSUE TITLE
UI hidden - A group in a war

### ISSUE THREAD

**Issue by FractalWire** [wesnoth/wesnoth#3006]
Hi,

After the end of the first scenario in this campaign (outpost), I've got a weird UI appareance

![image](https://user-images.githubusercontent.com/16882885/39605030-f4dbd132-4f2e-11e8-8827-71edf0df10c2.png)

Everything went black except for a thin line the moment I went on an event leading to the next scenario (Campaign map). I saw things moving on that thin line when i used the arrow to move around, but, all the rest was black.
At this point I could not really interact with wesnoth, so I restarted the game.

Unfortunately, I was unable to reproduce this again by doing the same procedure.

Edit : 
Wesnoth 1.14
Windows 10
Resolution 1280x800

**Comment by sigurdfdragon** [comment]
Could you be more specific as to what campaign & scenario this occurred in? Is a mainline campaign or an add-on?

**Comment by FractalWire** [comment]
It happened with the add-on campaign "A group in a war", at the end of the first scenario where you spend time recruiting and training your army.

**Comment by jostephd** [comment]
I saw the same behavior as the OP when I started `wesnoth --debug` and pressed `t` to enter the tutorial, but I can't reproduce it. I had the unit markers add-on installed at the time.
