### ISSUE TITLE
1.14: tutorial: "unknown unit" if Li'sar looked up in the help

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#3012]
not sure why but I can't look up Li'sar in the wesnoth unit help in the tutorial

**Comment by shikadiqueen** [comment]
Loading a save with her in it will add her to the `encountered_units` list, but starting the tutorial for the first time won't. I *suspect* this has something to do with the fact that she's added to the gamemap using `wesnoth.put_unit` in Lua.

**Comment by sevu** [comment]
It would be a workaround for the time being though.

**Comment by shikadiqueen** [comment]
I'd personally prefer if the underlying bug was fixed though. It's probably not that complicated to solve.

**Comment by sevu** [comment]
With 1.14.2 being close - will one of the two go in?

**Comment by jostephd** [comment]
@CelticMinstrel Right now, units are added to encountered_units even if they are fogged/shrouded and never actually seen by players (like the Giant Spider in HttT). Maybe units should only be "encountered" when the player _sees_ them.

**Comment by sevu** [comment]
Closing this, as the original issue has been addressed, there are two new issues for related things mentioned here.
