### ISSUE TITLE
1.14: planning mode: whiteboard warnings on every gui update

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#3014]
if I enter planning mode and plan moves over several turns, the game will spam
````
20180504 16:16:19 warning whiteboard: Move defined with insufficient movement left.
````
into stdout on every gui update (such as moving the cursor).

Maybe this was supposed to go into debug output?

**Comment by gfgtdf** [comment]
Are planned recruits involved?

**Comment by gfgtdf** [comment]
Are you using log-debug=whiteboard?

**Comment by matthiaskrgr** [comment]
Yeah, planned recruits are involved.
No I don't use  log-debug.

**Comment by gfgtdf** [comment]
i tried but i could not reproduce this.

**Comment by matthiaskrgr** [comment]
Hm, right now, if I enter planning mode, plan a recruit, and already plan moves of the recruit, the further plans get removed as soon as the unit is recruited in the next turn. Is that intended?
Maybe that's preventing the bug somehow...

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/commit/06118bbac8f6fe5fae7b16e9e87bae61ca0a19f5

**Comment by gfgtdf** [comment]
ok i investigates this and it's still not fixed, the problem is that this line https://github.com/wesnoth/wesnoth/blob/1.14/src/whiteboard/mapbuilder.cpp#L127 wrongly resets the units moves to 'full'

**Comment by matthiaskrgr** [comment]
It might be required that one unit reveals an enemy units while executing a planned move, to repro the bug

**Comment by matthiaskrgr** [comment]
for the record:
I was able to reproduce
20180505 15:43:20 warning whiteboard: Unable to build future map to determine whether leader's allowed to move.
 by:
1) enter planning mode 
2) plan recruits
3) plan movement of leader over multiple turns
=>
then in the next turn where things are executed, the warning will show up

**Comment by gfgtdf** [comment]
this 54e5c54c796c3740c7f0e9a59e470e679a8d0da9 shodul fix the issue in case of an interrupted movement.

**Comment by matthiaskrgr** [comment]
Ok, I think it is good now :)
Thank you!

**Comment by matthiaskrgr** [comment]
Actually its seems there are still ways to trigger this :(
start wesnoth -t
enter planning mode
make plans as shown in the screenshot
![planning](https://user-images.githubusercontent.com/476013/39671315-011f305e-5116-11e8-9769-2497b5e7f413.png)
````
20180506 10:12:52 warning whiteboard: Move for unit UI testing Outrider called Isor [Elvish Outrider-2] from (15,8) to (12,14) defined with insufficient movement left.
````
