### ISSUE TITLE
game selection is lost as time passes

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#3020]
Steps to repro:
* join MP lobby (1.14)
* select any already-started game at the bottom of the list
* wait. (You can switch to other apps, e.g. return 5 minutes later.)

Expected: game focus never changes until the (selected) game is not finished.

Actually: selection "shifts away", resulting in different game being selected. Player list "Selected Game" changes too.

From my observations, selection does not change when new rooms are created. Probably it changes when the old ones are closed (higher than your entry in list).

**Comment by Wedge009** [comment]
I wonder if this is somewhat similar to #1197. In that one, the game list seems to refresh itself (and throw the selected game back to the top). For this one, the game list seems to refresh itself periodically (as games start/stop, etc) and the selected game may change as a result.

**Comment by Wedge009** [comment]
Took over half an hour of observation but eventually I did notice this still happening in 1.14.7.

**Comment by Wedge009** [comment]
Did not observe this in 1.18.0 release but #1197 is still an issue.

Please re-open if this is still an issue.
