### ISSUE TITLE
UtBS: Garak is not actually berserk

### ISSUE THREAD

**Issue by beetlenaut** [wesnoth/wesnoth#3023]
In A Stirring in the Night, Garak seems to gain the berserk weapon special. It shows up on the sidebar, and is attached to his weapon when he attacks, but it's not true. He fights normally. I thought this was a bug, but you can see in the WML that it's intentional: He is only berserk when fighting two, specific enemy units! In that case, it should definitely not say that he is berserk in all his other fights. (That is why I marked this as a bug.) Actually, it probably shouldn't make him berserk in some rare cases in the first place because that would be bizarre and unexpected no matter what it said on the side bar.

IMO, the best solution would just be to make Garak actually berserk all the time--at least on HARD. On EASY, the opposite would be better. But, the most important thing is that the information in the side bar is true.

**Comment by CelticMinstrel** [comment]
I think @shikadiqueen is working on a fix for specials showing in the attack dialog when they shouldn't be.

**Comment by newfrenchy83** [comment]
the special berserk. don't function for all berserker in orher campaign not just garak in utbs. round= get_special("berserk").hihgedt("value",1).first in attacl.cpp equals 1 same if value=30 in [berserk].

**Comment by Vultraz** [comment]
This can be closed?

**Comment by CelticMinstrel** [comment]
I think @sevu might've done something about this? Fairly sure _someone_ did at least.
