### ISSUE TITLE
UtBS: Constant Lua errors about "on_redo"

### ISSUE THREAD

**Issue by beetlenaut** [wesnoth/wesnoth#3024]
If you choose to use the support ability for one of the heroes, a Lua error appears saying that "on_redo" is not supported every time the hero moves, and the move cannot be undone.

While UtBS is the only mainline campaign affected and could be fixed easily enough, it might also be a good idea to change the handling of the tag. The changelog says that on_redo is deprecated and has no effect, so it seems like it should raise a warning on the console instead of breaking the game event.

**Comment by Vultraz** [comment]
But all the cases of `[on_redo]` have been removed...

**Comment by Vultraz** [comment]
Hm. Was this from before 1.14.0 was tagged? https://github.com/wesnoth/wesnoth/commit/b8bf9b380634449e66a1f469b2b889d975211123

**Comment by Vultraz** [comment]
Perhaps you're using a savefile?

**Comment by CelticMinstrel** [comment]
`[on_redo]` was never in a stable version, so it's not subject to the deprecation system.

**Comment by beetlenaut** [comment]
Oh, rats. I was using a corrupted abilities file. I was chasing down a more serious bug (that does really exist), and I got the files mixed up.

**Comment by CelticMinstrel** [comment]
So we can mark this invalid?

**Comment by Wedge009** [comment]
I'd say so. @beetlenaut can make another issue for the 'more serious bug'.
