### ISSUE TITLE
Esc does not exit status table sometimes

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3028]
As seen from https://i.imgur.com/1WVpzGS.jpg, quit game popup is open over status table. I have not found any way to get back into game other than using quit->yes and rejoining.

Pressing No leads to stuck state: quit game popup is still visible with noninteractive buttons, and there is little that can be done - pressing esc again allows using yes to quit; menu can be used to open help (and not close it, by closing it remains in noninteractive form until redraw).

Game thinks the window is no longer there - it is possible to trigger redraw by rightclicking where map would be if windows was not open https://i.imgur.com/zWeTIXi.jpg.

It is also possible to open another status table, enter chat and chat commands without seeing them until manual redraw and so on https://i.imgur.com/JLO8eLI.jpg.

This can be replicated after several times of opening status and pressing esc.

I observed similar bug when implementing query_location, and it was one of the reasons I stopped with it.

**Comment by Wedge009** [comment]
I wasn't able to replicate this under Windows, but I wonder if there's any relation to #1601 (on assumption you are using Linux).

**Comment by ProditorMagnus** [comment]
This happened on windows, can try if happens on linux too.

**Comment by Wedge009** [comment]
Then it's probably a separate issue, maybe timing related (which always makes it difficult to replicate).

**Comment by ProditorMagnus** [comment]
Cant replicate on linux at Battle for Wesnoth v1.14.0+dev (5fd833a-Modified).

**Comment by Wedge009** [comment]
I'm just not able to get the exit dialogue over the statistics/status dialogue.

**Comment by ProditorMagnus** [comment]
It happened once today with chat log, but cant intentionally cause this yet.

**Comment by ProditorMagnus** [comment]
It hasnt happened recently, so closing this unless it happens again.
