### ISSUE TITLE
Lack of Dialogue in The South Guard 'Into the Depths'

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3030]
The Dialogue between Mal M'Brin and Ethiliel doesn't happen if my trollish allies are the first to discover Mal M'Brin.

[TSG-Into the Depths-Auto-Save26.gz](https://github.com/wesnoth/wesnoth/files/1977144/TSG-Into.the.Depths-Auto-Save26.gz) (End the turn, see the trolls discovering him, and notice the lack of dialogue.)

**Comment by sevu** [comment]
But it happens when you move to him later, or? I.e. when you are in range.

**Comment by Konrad22** [comment]
Nope. Never. I guess it might trigger if I lose vision of him and then I am the one to spot him again instead of the trolls.
I have a replay here.
https://forums.wesnoth.org/viewtopic.php?f=42&t=10286&sid=35cbe8871ede333c8848b4d482ba82b1&start=60
