### ISSUE TITLE
Horizontal scrollbar appears in Addons window

### ISSUE THREAD

**Issue by ancestral** [wesnoth/wesnoth#3037]
If you toggle “Unknown” in the “Type” drop down, on and then off, you will get a horizontal scroll bar in the window.

**Comment by Wedge009** [comment]
I didn't get this with either French or English, but I wonder if it's dependent on resolution size. It may also be another symptom similar to #1665 (and the related issues linked there).

**Comment by ancestral** [comment]
I’m having difficulty reproducing this behavior again.

**Comment by Wedge009** [comment]
@ancestral Could be specific to the add-ons list you had at the time and/or changes to the add-ons manager since you reported this. Do you still want to keep-it open?

**Comment by ancestral** [comment]
If it’s not reproducible, then presumably it’s fixed.

OK to close.

**Comment by Wedge009** [comment]
Thanks for confirmation. Can always re-open if you find it again.
