### ISSUE TITLE
TSG - Return to Kerlath, Lot's of [detoff_...] not supported

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3040]
This happens in this scenario whenever anyone fights. ._.
![tsgbug](https://user-images.githubusercontent.com/39015360/39671414-4ab3c35e-5118-11e8-9b90-8b9dd107c490.png)
[TSG-Return to Kerlath-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/1977458/TSG-Return.to.Kerlath-Auto-Save1.gz)
I was also able to reliable replicate it with the save file. But I can't replicate it after restarting the scenario. So I'd guess something is wrong with the save file instead of the scenario.

**Comment by Vultraz** [comment]
Are you sure you didn't have a modification active when you started the campaign or something? There is no code in the campaign related to any `[detoff...]` tags.

**Comment by Konrad22** [comment]
Yeah, you are right. I had installed the 'Deterministic Offense Mod' to test it, and I started the scenario while it was turned off. Then I deinstalled it and now, after reloading it, this happened. My bad, sorry. ^^
