### ISSUE TITLE
[Campaign] Issues with new Northern Rebirth Mission 5 The Pursuit

### ISSUE THREAD

**Issue by Nelson951223** [wesnoth/wesnoth#3043]
On the left bottom side of the map, AI spawn at a position with an one-hex entry. On Hard+ difficulty, with the initial income and villages AI has, it produces units faster than you can kill each turn, resulting into some necessity of RNG luck burst to kill 2 enemies in 1 round by 1 unit (one by offense and one by defence) to move into AI's base and take over. 

This map's questionable design probably need some modifications. It is adviseable to make the entry having at least 2 hexes instead of 1, so the progress of this campaign can be less inhuman.

**Comment by UnwiseOwl** [comment]
Closed. Solved by #3094 above.
