### ISSUE TITLE
Wesnothd sends [gamelist_diff] to client that is in game

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3045]
While observing game I noticed from console that based on timestamp I have received [gamelist_diff] while in game. I have been observing that game since at least 19:45.

```
20180506 20:20:02 error network: found unknown command:
[gamelist_diff]
	[change_child]
		index = 0
		[gamelist]
			[delete_child]
				index = 7
				[game]
				[/game]
			[/delete_child]
		[/gamelist]
	[/change_child]
[/gamelist_diff]

20180506 20:21:32 error network: found unknown command:
[gamelist_diff]
	[change_child]
		index = 0
		[gamelist]
			[delete_child]
				index = 7
				[game]
				[/game]
			[/delete_child]
		[/gamelist]
	[/change_child]
[/gamelist_diff]
```

**Comment by ProditorMagnus** [comment]
Part of the issue might be that when observed game ends, server decides that the observer is no longer in game, while observer does not accept lobby changes yet.

**Comment by gfgtdf** [comment]
a possible fix is to process lobby updates during the game aswell.

**Comment by ProditorMagnus** [comment]
Hard to reproduce/not worth the effort.
