### ISSUE TITLE
Non-standard teleport still counts friendly villages

### ISSUE THREAD

**Issue by ArcDeSeel** [wesnoth/wesnoth#3047]
Wesnoth 1.14.0
compiled source code; same bug in Steam version
Linux Mint 18.3

Unit has the following ability:
`[teleport]
    id=teleport_0
    name="teleport"
    [tunnel]
        id=village_teleport
        [source]
            [not]
                owner_side=0,1
            [/not]
        [/source]
        [target]
            [not]
                owner_side=0,1
            [/not]
        [target]
        [filter]
            ability=teleport_0
        [/filter]
    [/tunnel]
[teleport]`

When the unit is part of any side but side 1, the ability works as expected. If the unit is on side 1, it can teleport through villages owned by side 1.

(Also, the filter shouldn't be necessary, but it is or it crashes.)

**Comment by ArcDeSeel** [comment]
I'm noticing this does not happen if the source and target are "owner_side=2,3,4" without a not.

**Comment by ArcDeSeel** [comment]
Actually, the owner_side is just taking the first number. That's all.

**Comment by CelticMinstrel** [comment]
Looks like you want `[filter_owner]` instead of `owner_side`.
