### ISSUE TITLE
Crash with 'St8bad_cast' when opening Preferences

### ISSUE THREAD

**Issue by arunisaac** [wesnoth/wesnoth#3050]
I am using Wesnoth 1.14.0, built with boost 1.66.0. When I try to open the in-game Preferences dialog box, either from the title screen, or from the menu while playing, Wesnoth crashes with the following error.

```
Caught general 'St8bad_cast' exception:
std::bad_cast
```
What more information can I provide to help debug this?

**Comment by shikadiqueen** [comment]
Is this Windows? Could you try these instructions?

https://forums.wesnoth.org/viewtopic.php?p=627523#p627523

**Comment by arunisaac** [comment]
No, this is GuixSD, a GNU/Linux distribution. So, I can't use the wesnoth executable from that forum thread. But, I'll try applying commit 18e5ea50a7136cb3686c5a7c51c111ccce73dc54.

It's also possible that there is a issue with locale configuration specifically on my system or generally in GuixSD.

**Comment by arunisaac** [comment]
With commit 18e5ea50a7136cb3686c5a7c51c111ccce73dc54 applied, opening
Preferences does not crash Wesnoth. I just get the following error. I
believe this is what was expected.

```
20180507 19:29:42 error general: locale set-up for icompare() is broken, falling back to std::string::compare()
```

**Comment by shikadiqueen** [comment]
Removing the Linux label because this is neither a Linux-specific nor a Windows-specific issue, as it turns out.

**Comment by sevu** [comment]
Can this be closed?

**Comment by Wedge009** [comment]
It looks like @arunisaac worked around the issue. Will close in a few days if there's no further feedback.

**Comment by arunisaac** [comment]
Sorry for keeping you waiting so long. I missed the message somehow.

Now, I'm running wesnoth 1.14.9 with boost 1.70.0, and I encounter no
crash.  So, this issue is fixed.

**Comment by Wedge009** [comment]
No worries, always nice to have confirmation of a resolution.
