### ISSUE TITLE
HttT Sc17 map is missing in the maps folder. And the Sc17 scenario file has a typo.

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3052]
17 **Scepter** of Fire should be 17 **Sceptre** of Fire.
The code in Sc16 specifies 17 **Sceptre** of Fire as the next scenario, which means you get stuck at Sc16 because you only have 17 **Scepter** of Fire in the scenario folder.

**Comment by ln-zookeeper** [comment]
That's... not true. If the game claims the scenario is missing, you must have messed with the files yourself somehow.

**Comment by ln-zookeeper** [comment]
Closing this, since apparently there is no problem. And there is no map file because, as you can see by peeking into the cfg file, the scenario uses the random map generator.
