### ISSUE TITLE
The South Guard - The Tides of War: hint explaining campfires

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3056]
Just like the titel says. Apparently campfires in this scenario have their own time zone. 
[TSG-The Tides of War-Auto-Save5.gz](https://github.com/wesnoth/wesnoth/files/1981664/TSG-The.Tides.of.War-Auto-Save5.gz)

**Comment by sevu** [comment]
That's very likely intended.

**Comment by Konrad22** [comment]
Huh. I always thought that campfires work like illuminating (underground they do, but those are apparently the only ones working like that). I still think that illuminating campfires make more sense than time changing campfires.
Example for an illuminating campfire:
[UtBS-A Subterranean Struggle Turn 1.gz](https://github.com/wesnoth/wesnoth/files/1982581/UtBS-A.Subterranean.Struggle.Turn.1.gz)

**Comment by CelticMinstrel** [comment]
So I'm slightly confused, are they using a light level in the terrain like `^Ii` or are they using a `[time_area]`?

**Comment by Konrad22** [comment]
Most campfires (at the very least those in TSG-Sc9a and UtBS-Sc3) seem to use `[time_area]`, while campfires that are underground use a light level(?) (UtBS-A Subterranean Struggle). I'm just judging by their effects.
And what I'm saying is, that `[time_area]` makes less sense than using the light level, because Campfires provide light, instead of being a time portal. ._. It's also less confusing.

**Comment by Wedge009** [comment]
I don't know about the underlying time stuff, but I recall camp fires in Under the Burning Suns providing some illumination against the night as well (the scenario where you have to defend against two opposing undead leaders, and one of the elves gets possessed by them).

**Comment by CelticMinstrel** [comment]
Eh? It's always dusk on a campfire? That's actually really weird.

The campfire terrain does have a light level, right? Is there some reason not to just use that and drop the time area?

**Comment by gfgtdf** [comment]
> The campfire terrain does have a light level, right

That'd probably only work for the fire tile itself but not for adjacent tiles

**Comment by Konrad22** [comment]
@CelticMinstrel No, the campfire shifts the time zone around them one up on the brithness lvl (night -> dusk and dusk -> day). In that UtBS scenario it's night the whole time, which is why there is dusk around the campfires for the whole time.

@gfgtdf Wouldn't it be possible to modifify 'illuminating' (Like, from Mages of Light) and apply it to the campfire?

**Comment by CelticMinstrel** [comment]
@Konrad22 There's a facility for exactly that already in terrains, the `^Ii` terrain (which is a beam of light shining down from the ceiling, intended for cave usage) makes use of it. I haven't checked whether the new campfire terrain also uses it, though. And even if it did, that would only apply if you step _on_ the campfire.

...okay so I kinda just talked myself out of my former position. I think what should be done here isn't shifting the time zone but rather blitting the illumination image over it, much like what I did [here](https://github.com/CelticMinstrel/BlackCrossOfAleron/blob/master/utils/time.cfg#L5). With that it'll look exactly as if the illumination ability is in effect.

**Comment by Konrad22** [comment]
That makes a lot more sense then the timeshifting campfires. 👍 I'll try to add any mainline scenarios I can find that use campfires. :)

**Comment by CelticMinstrel** [comment]
For the record the only difference between what I described and what's currently done is the visual display.

**Comment by sevu** [comment]
@CelticMinstrel the red,green,blue values have been changed during 1.13, probably you want to update your macros too. Was it intentional that these values are the same than the non illuminated area?

List of affected scenarios:
- [x] UtBS S3 (WIP)
- [ ] TSG S8b
- [ ] DiD Parthyn (S6 and S1?) #3161
- [ ] DiD Tath #3161

**Comment by sevu** [comment]
The coding part is done, what is left is a hint.

**Comment by Konrad22** [comment]
The Checkboxes for the DiD maps have not been ticked off yet, so I don't know for sure.

**Comment by Konrad22** [comment]
Hey, that's mine too. xD
In that case I guess closing this one will be fine.
