### ISSUE TITLE
Halo bug after canceling recalling

### ISSUE THREAD

**Issue by AncientGeneral** [wesnoth/wesnoth#3065]
I found a bug with displaying some halo effects. In HttT campaing I started recalling my veterans. I recalled some units and loyal mage of light(3 level). Then I pressed "Undo", mage returned into recall list, however halo effect remain on map. I can reproduce this after loading previous save. It has no affect on gameplay.
![_2018-05-09_22-53-44](https://user-images.githubusercontent.com/20964929/39837148-4235251a-53de-11e8-951e-30e6860c9021.png)
![_2018-05-09_22-59-41](https://user-images.githubusercontent.com/20964929/39837149-425df526-53de-11e8-9ec6-d0941adf4ff9.png)

Steam version
The Battle for Wesnoth version 1.14.1 (918cdfc-Modified)
Running on Ubuntu 16.04.4 LTS

Game paths
==========

Data dir:        /home/USER/.steam/steam/steamapps/common/wesnoth
User config dir: /home/USER/.config/wesnoth
User data dir:   /home/USER/.local/share/wesnoth/1.14
Saves dir:       /home/USER/.local/share/wesnoth/1.14/saves
Add-ons dir:     /home/USER/.local/share/wesnoth/1.14/data/add-ons
Cache dir:       /home/USER/.cache/wesnoth

Libraries
=========

Boost:             1.66
OpenSSL/libcrypto: 1.0.1  (runtime 1.0.2g)
Cairo:             1.10.2 (runtime 1.14.6)
Pango:             1.30.0 (runtime 1.38.1)
SDL:               2.0.4  (runtime 2.0.5)
SDL_image:         2.0.1  (runtime 2.0.1)
SDL_mixer:         2.0.1  (runtime 2.0.1)
SDL_ttf:           2.0.14 (runtime 2.0.14)

Features
========
Experimental OpenMP support:    no
JPG screenshots:                no
Lua console completion:         yes
Legacy bidirectional rendering: no
D-Bus notifications back end:   yes

**Comment by sevu** [comment]
@jyrkive, pinging you as you worked on that
