### ISSUE TITLE
Pressing up or down while in an intro text for a scenario makes most of the 'text part' transparent (confirmed for windows 7 and 10)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3068]
I'm talking about this:
![transparent](https://user-images.githubusercontent.com/39015360/39844802-4b48e27c-53f2-11e8-9185-71efa014eef5.png)

EDIT: Tabbing out and back in to wesnoth or just going forward or backwards in the text returns it to normal.

**Comment by ProditorMagnus** [comment]
Looks like #2988.

**Comment by Wedge009** [comment]
I notice that even using the left and right arrow keys to navigate the story text results in a momentary flash of maximum transparency through to the background. Using the mouse to click the arrow keys does not have this, so it may be a case of the text box reading the key input as a cursor movement or something like that.

**Comment by Vultraz** [comment]
I can't reproduce this.

**Comment by Wedge009** [comment]
I can confirm it happens on both Windows 7 and 10, 1.14.1 release.

**Comment by Vultraz** [comment]
Still cannot confirm.

**Comment by Konrad22** [comment]
I'm unable to confirm it for 1.14.2.

**Comment by Wedge009** [comment]
It's still there in 1.14 branch as of ee638bc8 (1.14.2+dev).

1. Start a campaign (I just went with A Tale of Two Brothers).
2. Click the story text area (I don't remember having to do this previously but maybe I just missed that last time).
3. Press up/down to produce the transparency. Left/right flickers.

Repeating the above while skipping step 2 does not produce the issue. I confirm the above for Windows 7 and Linux.

**Comment by Vultraz** [comment]
Ok, NOW I can repro it with step 2. This is... *weird*.

**Comment by Konrad22** [comment]
@Wedge009 
Thanks for providing that missing step.
I can confirm it now once more for Windows 10.

**Comment by Vultraz** [comment]
This is not an issue on master, so I might just leave it unfixed in 1.14.

**Comment by Wedge009** [comment]
Is it because master is using a different rendering now?

I suppose that's fair - it's a fairly contrived situation to use both mouse and keys on the story screen.

**Comment by Vultraz** [comment]
Yes, master's UI rendering has been quite changed. This kind of issue is a symptom of the "dirty widget" drawing paradigm, while master uses a "always redraw everything" method that does away with stuff like this.

So... yeah, actually, I'm closing this. Fixed on master.
