### ISSUE TITLE
replays.wesnoth.org/1.12 takes a long time to load

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3069]
https://replays.wesnoth.org/1.12/ takes just forever to load (unlike https://replays.wesnoth.org/1.14/), the first possible reason that comes into my mind is that maybe https://replays.wesnoth.org/1.12/ simply has too many subfolders? Sooner or later this will probably apply to the unlike https://replays.wesnoth.org/1.14/ aswell.

**Comment by soliton-** [comment]
We should make year/month subdirs sometime and add redirects to not break the old URLs.

**Comment by stevecotton** [comment]
Ready to close? The year/month subdirs change has been done.

**Comment by soliton-** [comment]
Indeed, thanks for the heads-up.
