### ISSUE TITLE
Rise of wesnoth, A new land - It's possible to indefinitely "avoid deaths for as long as possible"

### ISSUE THREAD

**Issue by alexisnaveros** [wesnoth/wesnoth#3072]
In the campaign "The Rise of Wesnoth", in the scenario "A new land", the objectives are:
"Avoid death for as long as possible (the scenario ends when any unit perishes)"

Unfortunately, it's actually possible to avoid deaths indefinitely, meaning the scenario never ends. And so, the player can accumulate any desired massive amount of gold for the next scenario.

Screenshots:
http://www.rayforce.net/wesnoth000.png
http://www.rayforce.net/wesnoth001.png

Proposed solution: End the scenario after a given count of turns, even if no deaths have occured. Maybe 30 turns?

**Comment by Wedge009** [comment]
As discussed in #wesnoth-dev, it's an oversight in the campaign design. I agree, there should be a maximum limit as an alternative trigger to end the scenario even if that limit is hidden from the player. It should be low enough to ensure that the player doesn't end up with the ridiculous scenario posted here. (Seriously 231 turns is dedication, but ultimately wasted!)

**Comment by alexisnaveros** [comment]
For the record, I lasted that long to see if the attacking units could get troublesome after reaching level 3 (slowly gaining experience for each attack...) and finally put an end to the scenario.

Unfortunately, by that time, there are so many units piled up that it's impossible for these attacking wounded level 3 units to move aside, heal, and let other units attack. So they wait, healing just 2 HP per turn, until they can attack again.

And the scenario really never ends.

**Comment by mattsc** [comment]
I think putting a turn limit on this scenario is a good idea.

In addition, I'll have a look at the AI.  There's a custom AI in the scenario that is meant to prevent units from suiciding themselves and retreat instead.  However, if retreat is not possible, such as in the screenshot, they should probably attack no matter the consequences.  I'm not sure if that's enough though.  It would be nice to figure out how to avoid getting into this situation in the first place, so @alexisnaveros, if you could post your replay here, that would be very helpful.

**Comment by alexisnaveros** [comment]
Sure, here's the replay:
http://www.rayforce.net/TRoW-A%20New%20Land%20replay.gz

Note that I didn't even recall the best units for the job... I had too many melee units, so even wounded ranged attackers would keep pummelling them, and I had to rotate them constantly. With ranged units, I think I would have had nothing to do except press "end turn".

**Comment by alexisnaveros** [comment]
I have play tested zookeeper's proposed changes:
https://gist.github.com/ln-zookeeper/bee5b37da80869d9fd1351c352ab52c9

Even with good starting gold and tactics, it becomes hard to hold at turn 16 (running out of units to rotate), and to go beyond the turn 25 requires abundant luck. That seems appropriate.

But most importantly, I also like what the changes mean lore-wise. You have just set foot on this new land and the locals are immediately throwing a torrent of sorceresses, elvish marksmen and other upgraded units at you. The impression you now get is "Okay, these guys are mighty, this is their land, and they don't mess around! I must establish friendly relations just to survive..."

**Comment by sevu** [comment]
@ln-zookeeper, I see a fix has been included in the repository.
Please reopen if there is more to it.

**Comment by CelticMinstrel** [comment]
@sevu Can you please link to the commit as well.

**Comment by sevu** [comment]
It's this one: 0de4a4c
