### ISSUE TITLE
Northern Rebirth - Infested Caves, Undead side 8 behaves very brainless (which affects the difficulty of the scenario)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3073]
This undead side with 500 gold decided to go to a keep with one castle hex attached to it. And it apparently doesn't want to leave. It's stuck there with over 300 gold and it's income almost equals the amount of gold it can spend per turn. (It's not even chosing to take the keep with four castle hexes attached next to it.)
[NR-Infested Caves-Auto-Save6.gz](https://github.com/wesnoth/wesnoth/files/1991061/NR-Infested.Caves-Auto-Save6.gz)

EDIT: The bat at the beginning that is side 9 is now using the color of side 5. Why?

**Comment by mattsc** [comment]
I looked into what's happening here and it's kind of funny.  The side leader starts on hex 23,4 (see the screenshot below) and on turn 1 grabs one of the southern villages.  On turn 2, he moves south to the keep on 23,11 and then is stuck there (the default AI doesn't really analyze which castle is best, and it does not switch castles on its own; the experimental AI does, but that includes a bunch of other changes that would alter the balance of the scenario). So I think it is save to say that this is not intended and counts as a bug.

I have this fixed locally by keeping the leader on his keep for the first two turns.  That way, his skeletons will have grabbed the villages and he doesn't do that, but it is still possible to lure him off the keep later.

If there are no objections, I'll commit that later.

Don't know about the bat, but the color for this side is set specifically to black in this commit:
https://github.com/wesnoth/wesnoth/commit/0771fddf812e403d528721dfd6885dfb5f16074b#diff-59e6276c7405c448a887effae8630934R189
So you'd have to ask @Vultraz.

![screen shot 2018-05-10 at 13 28 06](https://user-images.githubusercontent.com/2106424/39893889-12395e9a-545a-11e8-9415-fd079b1fb94a.png)

**Comment by Konrad22** [comment]
Would it maybe be possible to cap his movement speed at 3 or 4 for the first two turns? That way he can still grab a village (23,7) in the 1st turn and he will have only the original keep as choice in the 2nd turn.

**Comment by mattsc** [comment]
It's possible.  But would having one village more for one turn make any difference?  And it's all under shroud anyway, so nobody would be surprised by the slightly unusual behavior.

**Comment by mattsc** [comment]
It's still "artificial", just not as much.  ;-)  What should really be done is to design the map so that this is not possible in the first place, but I am not going to touch that, esp. in Northern Rebirth.  Anyways, I've already changed it to limit moves to 4 on the first two turns.

**Comment by Vultraz** [comment]
Couldn't we just use the proper AI :|
