### ISSUE TITLE
UtBS - daze special says that only magical attacks do not suffer from it, but marksman isn't affected as well

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3076]
As the title says.
(I messed around a bit because I wanted to see the new great tree.)
[UtBS-The Morning After Turn 1.gz](https://github.com/wesnoth/wesnoth/files/1991492/UtBS-The.Morning.After.Turn.1.gz)

**Comment by ln-zookeeper** [comment]
I think it makes more sense for marksman to be unaffected (just like magical is), and that only the description needs to be updated to match that.

**Comment by ln-zookeeper** [comment]
Will have to think about how to phrase the change, though. One can't simply say "except for magical and marksman attacks", because marksman attacks are still affected in some cases, so the wording needs to change overall.

**Comment by Konrad22** [comment]
In what cases would marksman attacks be affected and why?

**Comment by ln-zookeeper** [comment]
If the marksman would otherwise have a 70% (or higher) CtH against an enemy, then daze would/should still cause a -10% to CtH. If the enemy would have 40% or higher defense, then daze would have no effect.

**Comment by Konrad22** [comment]
So we are looking for a wording that makes clear that those two 'abilities' are not affected, while the attacks itself are affected.

**Comment by sevu** [comment]
Btw, are there cases where one has enemies with marksman?

**Comment by Konrad22** [comment]
Orcish Assasin or Slayer in Sc4.

**Comment by nemaara** [comment]
How about this description? 

        description= _ "When hit with this attack, an enemy suffers a 10% penalty both to their defense and chance to hit for one turn. Other specials that affect chance to hit (e.g. magical and marksman) take precedence over this special*.

*Magical attacks will still have a 70% chance to hit.
*Marksman attacks are only affected if the chance to hit is greater than 60%."

Konrad22 already said he liked it, so I'll probably commit this sometime over the weekend unless there are any concerns.

**Comment by nemaara** [comment]
See https://github.com/wesnoth/wesnoth/commit/b02652fa0c753750f474807b290bd9e2106c54ad, this issue should be fixed now.
