### ISSUE TITLE
Deprecated keys inserted into saves

### ISSUE THREAD

**Issue by mattsc** [wesnoth/wesnoth#3081]
The keys `needs_select` and `previous_recruits` have been deprecated/removed, but still get inserted into saves.  Sometimes this produces warning messages in stderr.  I have not figured out exactly when the warnings are displayed, but here is a simple way to reproduce this anyway.

Start mainline campaign Secrets of the Ancients.  Move to the second scenario using `:cl`.  `previous_recruits` will be in the start-of-scenario save (but not in the turn saves), and `needs_select` will be in the turn saves (but not start-of-scenario save, because the menu only gets inserted during the scenario).

**Comment by gfgtdf** [comment]
`previous_recruits` is not deprecated, (in fact it was never a supported attribute) it's just an attribute that the game uses internally during carryover, we should just add it to whitelist.

**Comment by sapientN3T** [comment]
if needs_select has been deprecated but not removed, then you could just print a message when it’s set to Yes.

**Comment by CelticMinstrel** [comment]
If it doesn't already call the `deprecated_message()` function then a call should be added when the key is present (even if it's set to no).

**Comment by Vultraz** [comment]
I wonder, can needs_select handling just be removed? Ie, does it do anything useful?

**Comment by CelticMinstrel** [comment]
I'm not entirely sure (maybe @gfgtdf knows more) but my impression was that it's basically become irrelevant somehow, so it no longer does anything. But I could be wrong.

**Comment by Vultraz** [comment]
There's some handling of it left over.... but maybe that could be removed?

**Comment by CelticMinstrel** [comment]
Depends whether it actually does something. If it doesn't do anything, deprecate it at level 4. Otherwise, leave it in and deprecate at level 3.

**Comment by sapientN3T** [comment]
As far as I am aware, needs_select does synchronize the previous select event over the network and into the replay. It works in most cases. It only had to be deprecated because it can't handle some edge cases. So I would not advise removing the code that maintains the functionality... or at least not until the full deprecation cycle has completed. It was deprecated in version 1.13.7

**Comment by CelticMinstrel** [comment]
Okay, then the only thing to do is make sure that it's deprecated with the new deprecation functionality. I did go through and replace a lot of old messages with the new functionality, but I might've missed some.

**Comment by gfgtdf** [comment]
So the need_select part was fixed in https://github.com/wesnoth/wesnoth/commit/49f4656c085c1f9eab0f3c917aaba38a82fc23e7
