### ISSUE TITLE
wrong directory paths displayed (on linux at least)?

### ISSUE THREAD

**Issue by matthiaskrgr** [wesnoth/wesnoth#3082]
linux, manjaro, Battle for Wesnoth v1.14.1+dev (0d4bfce2b7-Clean)

Wesnoth stdout's
````
Automatically found a possible data directory at /home/USER/vcs/github/wesnoth/build/..
Data directory:               /home/USER/vcs/github/wesnoth/build/..
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.14
Cache directory:              /home/USER/.cache/wesnoth
````
but I'm wonder if that is correct, there is obviously no ````/home/USER/```` directory.

Maybe this us supposed to say ````/home/$USER/```` on linux ````$USER```` (or even better; ````${USER}````) would be substituted for ````matthias```` in my case.

Or we could probably just grab the $USER env var and insert it print ````/home/matthias/....````

**Comment by shikadiqueen** [comment]
This is an intentional feature someone introduced at some point to minimize the amount of personal information provided by Wesnoth logs when they are posted publicly. The design is a bit flimsy but it works in the average case.

**Comment by matthiaskrgr** [comment]
Oh ok.
Well but if we used literal ${USER}, it would still be anonym but also actually be a valid path in most cases. :)

**Comment by CelticMinstrel** [comment]
I did consider doing that but ended up deciding to imitate Apple's crash reports.

**Comment by matthiaskrgr** [comment]
Ok, it turns out the code already tried to get the $USER env but fails for some reason.

````cpp
std::string sanitize_path(const std::string& path)
{
#ifdef _WIN32
	const char* user_name = getenv("USERNAME");
#else
	const char* user_name = getenv("USER");
#endif

	std::string canonicalized = filesystem::normalize_path(path, true, false);
	if(user_name != nullptr) {
		boost::replace_all(canonicalized, user_name, "USER");
	}

	return canonicalized;
}
````

**Comment by matthiaskrgr** [comment]
Ah, this should obviously be
````cpp
	if(user_name != nullptr) {
		boost::replace_all(canonicalized, user_name, "USER");
	}
````
