### ISSUE TITLE
require_scenario does not work with random maps

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3105]
as said in the title, i ust noticed that i was able to join a map that had require_scenarnio=yes even though i didn't have that addon installed. Im quite sure that that hapened becasue that scenario uses random map generation.

**Comment by CelticMinstrel** [comment]
Does it use the scenario generator it the map generator?

**Comment by gfgtdf** [comment]
No, but the create_engine still has a different path for maps that use map_generation

**Comment by CelticMinstrel** [comment]
That didn't answer my question.
