### ISSUE TITLE
NR S5 - (southern) secret door to Malifors Study can't be opened from his study

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3116]
[NR-The Pursuit-Auto-Save65.gz](https://github.com/wesnoth/wesnoth/files/2005496/NR-The.Pursuit-Auto-Save65.gz)
It's obviously a door, but I can't open it from malifors study. :(

**Comment by UnwiseOwl** [comment]
This applies to each entrance to the study: the main door, the spider entrance and the sunken tunnel, none of which can be opened from the inside.
It would be easily possible to make them fire from the inside, but the events don't make sense going backwards. My inclination is to leave them blocked from the study and let folks explore the level from the South if they really want to. Happy to write "There seems to be a door here, but I can't seem to open it from this side." messages if people think they'd add anything, but personally, meh.

**Comment by Konrad22** [comment]
I think it would add something. ^^ It just feels wrong to look at a door and tobe unable to open it while your units don't care about it.
