### ISSUE TITLE
NR S5 - Malifors Death dialogue somewhat bugged

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3117]
There is a dialogue that fires (no matter what) when I 'kill' Malifor with any unit of mine. It fires as well, if I kill him with my Mages of Light (who can kill him for good). (Therefor it's not exactly bugged, it's just missing a necessary check.)
[NR-The Pursuit-Auto-Save66.gz](https://github.com/wesnoth/wesnoth/files/2005554/NR-The.Pursuit-Auto-Save66.gz)
(Yes, I did cheat so I'd get Abhai. I might have maybe reached him if I fight the green undead long enough, but being unable to wipe them out after 60 turns is just unreasonable. I'm glad about the fix.)

**Comment by Byteron** [comment]
You mean that these events should only be fired once?

**Comment by Konrad22** [comment]
I mean that they shouldn't comment on Malifor being unable to be killed by normal means (and that only the Mages of Light can kill him) if they have already killed him for real on the first try.

**Comment by UnwiseOwl** [comment]
You're right that there's no check, but I also don't think that it's possible to reach this state by normal means. How did you do the damage to Malifor in the first place? As I understand it he can't be hurt at all by anything other than white mages and that event should fire the first time that they attack him.

**Comment by Konrad22** [comment]
So...
Let's list the events first.
Event 1: Dialogue that Malifor is unkillable except by the White Mages (told in a way like 'oops, we can't kill him like that, let's do it like this instead)
Event 2: Dialogue when Malifor was killed for real

Event 1 fires when Malifor is 'killed' for the first time
Event 2 fires when Malifor is killed by the White Mages

My situation: Malifor is being killed for the first time and I used the White Mages to kill him
Now: Event 1 fires. Event 1 ends. Event 2 fires.
My 'problem' is, Event 1 contains information you should have only found out by failing to kill him for real (by the way it's worded) and it sounds quite redundant when the two Events fire directly after another.

**Comment by UnwiseOwl** [comment]
I'm assuming that your Event 1 is the dialogue that begins "I see now. It is impossible to destroy him by ordinary means." that triggers when Malifor is first attacked by Morvin or Thera. If other units attack him, they cannot kill him as they cannot do damage. If you were able to damage him using other means then that is a bug, which is why I asked about how you damaged him.

Since 1 white mage cannot kill Malifor, event 1 should never fire once Malifor is dead.

**Comment by UnwiseOwl** [comment]
That'll do it.

changing:
`    [event]
        name=attack end
        [filter]
            id=Father Morvin,Sister Thera
        [/filter]
        [filter_second]
            id=Malifor
        [/filter_second]`
to:

`    [event]
        name=attack end
        [filter]
            id=Father Morvin,Sister Thera, Malifor
        [/filter]
        [filter_second]
            id=Malifor,Father Morvin,Sister Thera
        [/filter_second]`
should do the job.

**Comment by Konrad22** [comment]
Thanks for your attention.
