### ISSUE TITLE
Team chat is not marked as such on remote clients

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3119]
From https://www.wesnoth.org/irclogs/2018/05/%23wesnoth-mp-lobby-stable.2018-05-15.log

20180515 23:43:11< lobby>         <Hugh_Jascock> lol also did you notice
20180515 23:43:21< lobby>         <Hugh_Jascock> when you're in a game and you're using allied chat
20180515 23:43:28< lobby>         <Hugh_Jascock> your partner doesnt see it as allied
20180515 23:43:37< lobby>         <Hugh_Jascock> he sees your name in <> like regular chat
20180515 23:43:41< lobby>         <Hugh_Jascock> even when you use allied

**Comment by CelticMinstrel** [comment]
Tagging @gfgtdf since that's his commit.

**Comment by gfgtdf** [comment]
i don't remember that commit very well but it looks like the easiet fix is just to make the code in replay.cpp just check for to_sides instead of team_name. I don't know how whispters are handled though, do they also use [speak] or do they have a seperate command ?

**Comment by ProditorMagnus** [comment]
https://forums.wesnoth.org/viewtopic.php?p=630613#p630613 seems it only fixes it for chat log, not in normal chat area.

**Comment by Choicerer** [comment]
I've submitted a pull request fixing the second part of the bug.
https://github.com/wesnoth/wesnoth/pull/3313/files
The problem resides in replay.cpp as well, under do_replay_handle. 
The "team_chat" index in speak should actually be "to_sides"
this commit:
https://github.com/wesnoth/wesnoth/commit/6aa3b3bc9a920638b68e6ceebd96a23822767c8d
didn't change it.
