### ISSUE TITLE
Drake Enforcer Weapon 'Trident'

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3129]
I'd say something is missing.
![trident](https://user-images.githubusercontent.com/39015360/40236536-35f9f34e-5aae-11e8-9b89-6a56a386184d.png)

**Comment by Vultraz** [comment]
Well, that's weird... the icon path is correctly set...

**Comment by ln-zookeeper** [comment]
Someone also made a similar report (only in IRC, IIRC) about some merman's trident. I couldn't reproduce or see anything wrong with the WML and image file, so if this is actually a thing, perhaps it might be a packaging issue?

**Comment by sevu** [comment]
Do you have Ageless installed and use Windows or Mac?
Ageless has the file attacks/Trident.png - I always wondered what that could cause...

**Comment by Konrad22** [comment]
@sevu Yes. I'll deinstall it now and check what happens.

![trident2](https://user-images.githubusercontent.com/39015360/40254659-a1e3faba-5ae4-11e8-9aa3-e9f5cc2504e8.png)
Looks like it happens because of Ageless.
