### ISSUE TITLE
NR Sc13 Nightmare - Ai Ally dies at turn 12/13 (causing you to lose the scenario)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3133]
[NR-Showdown-Auto-Save12.gz](https://github.com/wesnoth/wesnoth/files/2018405/NR-Showdown-Auto-Save12.gz)
I don't think the plan was to have my north and south groups rush to his defense to save his life. I'll try that in my next run though. (Additionally Hamel wasted some turns on attacking enemies instead of recruiting)

**Comment by Konrad22** [comment]
[NR-Showdown-Auto-Save17.gz](https://github.com/wesnoth/wesnoth/files/2026256/NR-Showdown-Auto-Save17.gz)
I'm adding this to show how...infuriating this ai can be, because Hamel as unit is too aggressive. (

**Comment by soliton-** [comment]
Sounds more like a bug to me if the scenario becomes unwinnable.

**Comment by sevu** [comment]
@DisherProject I bumped gold for the lich brothers (in case they come even into action) and set passive_leader=yes for the leaders who aren't allowed to die.

**Comment by GregoryLundberg** [comment]
I really am not sure about "fixes" like this. They may make it extremely unlikely for the issue to crop up, but they don't make it impossible. Not sure how I'd handle this issue, but in other places I'd done things like use alternates to replace the unlikely/unexpected death just in case it ever occurs.

**Comment by Konrad22** [comment]
So, since I've finished NR once more, I can say with certainty that the issue of Hamel dying is still there (at least in 1.15). I think, unless you just want to bump the amount of gold he has, you'd have to change the map, so there is more space between Hamel and the orcish fortress (so he doesn't draw the lvl 3 guards), and so he has some hills to rely on for defense. The dwarves just get slaughtered on the flat in front of the fortress.
