### ISSUE TITLE
NR Sc11 Nightmare - a bit step up in difficulty without Drake allies

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3134]
Krash is allowed to die, but losing him has severe repercussions in Sc10 and 11 and 12. You wouldn't even know what you did wrong if you've never had him survive that far... I'm pretty sure that could cause quite some frustration and going back far enough to save him isn't that nice either.
So, my ideas:
a) Make his death a lose condition.
b) Do it just the way it is done in Sc13. Let Ro'Arthian/'Sothian cover for him. (Like 'I found some orgres here, I'm now an allied leader')

(You could also use them to make Sc12 possible even without the elves.)

EDIT:
(Changed the name of the issue, because I finally noticed that only because I can't beat it anymore, doesn't mean that noone can.)

**Comment by nemaara** [comment]
See https://github.com/wesnoth/wesnoth/commit/455fbb207a3e467743434a66c96cf833474c19e2.
