### ISSUE TITLE
No effects and bell sound in ubuntu - music and interface sound are ok

### ISSUE THREAD

**Issue by badpenguin** [wesnoth/wesnoth#3138]
I dunno what has happened but suddenly when playing some sound stopped working.
I rebooted the machine, reinstalled wesnoth, resetted the cache and the config files, nothing.
While music and interface sounds are ok i cannot hear anymore the ring/bell of the start of the turn and the combat sound (effetct) are not heard or they have a strange very low volume that cannot be heard.
I'm using latest Ubuntu and latest version from flatpak: org.wesnoth.Wesnoth/x86_64/stable system,current

Any idea or settings i can try to change?

**Comment by badpenguin** [comment]
I think my soundcard has problem, since other apps are not working good, strange things this happened while playing.

**Comment by sevu** [comment]
You could test these things, eventually they have a positive effect:
==> If you experience sound problems try setting your SDL_AUDIODRIVER environment variable to "dma"
==> eg. export SDL_AUDIODRIVER="dma" ; wesnoth-1.14
==> If "dma" doesn't work,other options are: dsp,alsa,artsc,esd,nas try to find the right output.

If one of them work it would be interesting to know more about it.

**Comment by badpenguin** [comment]
@sevu nope, it was some problem with my machine while playing wesnoth i was upgrading the distro and pulseaudio messed up :)
