### ISSUE TITLE
[color_adjust] no longer allows setting the screen to a single colour with ToD

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#3144]
In 1.14, the RGB values passed to the `[color_adjust]` tag are clamped in the [-255, 255] range by the `tod_color` class constructor (`wesnoth.color_adjust` calls `display::adjust_color_overlay()`, which sets `display::color_adjust_` to a new `tod_color` value). While this "makes sense", it unfortunately breaks edge cases from 1.12 and 1.10 where it was possible to use `[color_adjust]` with excessively large or small values (e.g. 500 or -500) to completely negate the effects of the existing time schedule colour shift (see the `[time]` tag) in case it would interfere in some way since the `[color_adjust]` shift is **added** to the base ToD shift.

For example, if the ToD shift is 100,100,100, using `[color_adjust]` with -255,-255-255 will leave the effective shift at -155,-155,-155, which is not 100% black, so we'd use -500,-500,-500 in 1.12 and 1.10 instead.

This regression affects a huge number of cutscenes in my campaigns and I'd greatly prefer to see it fixed in the engine without having to resort to the alternative of manipulating the ToD schedule of the scenario every single time I need to have the screen painted a full solid colour.

It could be considered for 1.16 to leave it to the author to specify whether the `[color_adjust]` shift should be added to the ToD shift or override it entirely.

**Comment by Vultraz** [comment]
Introduced by c77faf2223b535badbe56fdd30bc404e283e7c29

**Comment by CelticMinstrel** [comment]
I thought this should've stayed open as a reminder to add something like `override_tod` to `[color_adjust]`...
