### ISSUE TITLE
1.14.3 backports

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3147]
- [ ] fd8473e translation prefix
- [ ] 36026a5 manpage

**Comment by CelticMinstrel** [comment]
691435ed4c5d2a7cb386971288a117e1e94ac569

**Comment by gfgtdf** [comment]
* [ ] https://github.com/wesnoth/wesnoth/commit/acf9a9874c6d51ca205de6fb8cebb35f91c3fec0

**Comment by CelticMinstrel** [comment]
* [ ] 1413dfd4f387f589d59545f0a4cde665d0d1aac2

**Comment by Vultraz** [comment]
Done.
