### ISSUE TITLE
1.14 terrain generator blocks terrain changes

### ISSUE THREAD

**Issue by Choicerer** [wesnoth/wesnoth#3151]
wesnoth.set_terrain has no effect in 1.14 when using the vanilla terrain generator.
https://forums.wesnoth.org/viewtopic.php?f=21&p=628566#p628566

**Comment by gfgtdf** [comment]
by "1.14 terrain generator" you mean the random generator that is shiiped with wesnoth that can be acceses using multiplayer->random maps ?

Do you get any erros in stderr.txt ?

**Comment by ProditorMagnus** [comment]
Yes, no errors.

**Comment by gfgtdf** [comment]
i ust tested exatly that has no problems. maybe you just forgot to [redraw] ?

**Comment by ProditorMagnus** [comment]
Seems so indeed.

**Comment by CelticMinstrel** [comment]
Shouldn't need to redraw, mind you, but I guess if there's a workaround then maybe we can close this for now? We do want to eliminate the need for explicit redraws in the future, but that's a separate (and more general) issue.

**Comment by Choicerer** [comment]
Hm, there never had been any need for [redraw] before 1.14 in my add-on, I never even realised such a tag existed and was needed for anything. But very well, I can just include it for now. Thanks!

**Comment by Choicerer** [comment]
I can confirm this issue doesn't exist... No need for any redraw calls, the problem was completely different. Kind of embarrassing... The new version of my add-on doesn't randomise the tiles that have no symmetry if mirror is switched on. Well, the randomly generated maps have no symmetry... Closing.
