### ISSUE TITLE
Ignorring illegal whiteboard data...

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3153]
All players were running 1.14.1 (praise steam autoupdate)
At some point in this ANL match this two lines appeared, noticed by multiple people, no farther issues:
Ignoring illegal whiteboard data, sent from user ... which had an invalid side of '4'
Ignoring illegal whiteboard data, sent from user ... which had an invalid side of '4'

The users were from side 2 & 3, I myself did observe the game.

I have an observer save of the game - a replay will probably be available in a few hours on the replays server - would any of these help?

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/commit/619704923ca692705607cc4820e50d4e6665990c might have fixed this.
