### ISSUE TITLE
DiD - Parthyn Map

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3161]
There is a campfire on 28,12 that does not provide any light.

**Comment by Konrad22** [comment]
(Same for Tath map)

**Comment by sevu** [comment]
There exist campfires which only illuminate the current hex, and some which illuminate a 2 hex radius.
When placed on these maps there were no tactical considerations involved, if they should illuminate area of the map where they are should be reconsidered.

**Comment by sevu** [comment]
This could be a good element to better balance S1 #3310

**Comment by Konrad22** [comment]
This specific campfire doesn't even illuminate the current hex. :/

**Comment by CelticMinstrel** [comment]
I'm guessing it uses the old campfire macro rather than the new campfire terrain?

**Comment by sevu** [comment]
Both don't illuminate any hex (sth. that could be changed in master though)

**Comment by nemaara** [comment]
Fixed by #3841, there aren't any more campfire hexes in the Parthyn or Tath maps.
