### ISSUE TITLE
DiD Sc7 Raiding Tath?

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3162]
I kinda destroyed Tath, but noone noticed. Is that really okay?
[DiD-A Small Favor replay.gz](https://github.com/wesnoth/wesnoth/files/2034263/DiD-A.Small.Favor.replay.gz)

**Comment by Konrad22** [comment]
In that case, please increase the support villages give by 1.

**Comment by sevu** [comment]
Good idea!
