### ISSUE TITLE
DiD - Alone at last

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3164]
He says that his Sister won't dare to lead her soldiers too far from Parthyn, but looking at the map she already did lead them across half Wesnoth. ._. Maybe we can find a good/better explanation for this and include it in the campaign?
![map](https://user-images.githubusercontent.com/39015360/40478123-838a4610-5f48-11e8-837f-44287ad6d6af.png)

**Comment by Konrad22** [comment]
This will be fixed by the DiD revision.

**Comment by nemaara** [comment]
#3878 merged, so this issue should be able to be closed now.
