### ISSUE TITLE
DiD Sc11 - Necromancers can't become Lichs

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3165]
I do know that this is not a bug, but with Secrets of the Ancients (as origin for the book Mal Keshar has) being part of the mainline campaigns, it is an inconsistency.
In SotA you can turn your Necromancers into Lichs and all of your lichs can advances to Ancient Lichs (Sc18). All thanks to the same book that Mal Keshar has now. ^^

**Comment by stevecotton** [comment]
Mal Keshar has just the book, but the necromancers of SotA are learning directly from the genius who wrote the book.

**Comment by sevu** [comment]
It could be changed in the last scenario though, eventually in a later playthrough... as Malin did figured it out, and _eventually did not forget_ how this works when he abandoned his human life.

(Though - if enabling it in a later playthrough that would give hope to the player that there is more to reach in the 2638 playthrough)

**Comment by sevu** [comment]
.... this is already done like that.

**Comment by sevu** [comment]
Your units can advance to Liches in Scenario 11 & 12. Advancing to Ancient Liches is not possible.

Guess it would be cool... On the other hand, it worsens the situation with playing scenario 12 forever :(

**Comment by Konrad22** [comment]
That's why I specified Necromancers instead of just units. :/ In SotA it is possible to 'turn' the lvl 3 unit Necromancer into the lvl 3 unit Lich, which can advance to the lvl 4 unit Ancient Lich.
This is what I was talking about. :c
