### ISSUE TITLE
DiD Sc12 - It's kinda boring after the 3rd-5th Night...

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3167]
How about instead letting the player chose if they want to continue and ending the campaign without Mal Keshar dying but instead make him 'forgotten', like, he is still alive, but people don't find his home anymore.
End it with a 'While it is believed that he was vanquished at some point of history, noone ever managed to find proof of it'.

**Comment by Konrad22** [comment]
I'm in 1.14.1 and I decided to suicide in Endless Night 7.
[DiD-Endless Night-Auto-Save7.gz](https://github.com/wesnoth/wesnoth/files/2035608/DiD-Endless.Night-Auto-Save7.gz)

**Comment by Konrad22** [comment]
Two things:
Why would that be a problem?
And if the player didn't understand at that point that Keshars choices were not exactly the best, then this ending won't help making that point either. He went down fighting, doing what he wanted for decades, maybe centuries. In a way, he died a glorious death. The only thing dying did to him, was stopping him.
Showing his death seems to only make a point of demonstrating his resolve.

**Comment by stevecotton** [comment]
Based on the epilogue of SotA, maybe Mal Keshar should read a bit more of the book at the start of each playthrough:

In the intro for the 1st night, he reads enough for level 3 necromancers to safely be converted to liches.

In the intro for the 2nd night, he reads the epilogue of SotA, and ponders in-universe about the future.

Between the 2nd and 3rd nights, he's realised that the mages of Tath couldn't destroy the book, and the idea that the book will itself lead to another lich rising and trying to persuade the world that necromancers are nice people. So he makes a copy of the book for himself, and plans to let the foolish hero to take the original back to Tath.

On the 3rd and subsequent nights, there's an alternative victory condition of "let an enemy unit take the book".

**Comment by Wedge009** [comment]
As others have already noted, the original ending was that the final scenario keeps repeating until the player gives up. I suppose this isn't that much different in the current 1.14 release but at least it's now a little clearer that the repetition is intentional and the only way to break out of it (that I can recall) is to lose.
