### ISSUE TITLE
The game assume the uniqueness of "canrecruit=yes" in each side.

### ISSUE THREAD

**Issue by yifan92** [wesnoth/wesnoth#3168]
If a second unit with "canrecruit=yes" is deployed with [unit] tag, it would simply fail. Examples include the 1st scenario of UMC campaign The Final Exam, and Lethalia in LotI.

**Comment by ProditorMagnus** [comment]
Creating multiple units with canrecruit=yes works for me.

**Comment by yifan92** [comment]
The bug occurs when you create a unit at the start of a scenario with WML.

**Comment by gfgtdf** [comment]
this still sounds very unlikely and we will not debug The Final Exam or LotI. Maybe you could post a a minimal test case for reproducing?

**Comment by yifan92** [comment]
The Final Exam example is a simple test case. By default, you should start the 1st scenario with a Bowman named Johnny but you don't. And if you go to the code and comment out the "canrecruit=yes" line in the prestart event, he appears.

**Comment by yifan92** [comment]
Seems that it's caused by conflict with UMC mod.
