### ISSUE TITLE
Row - 'distract' doesn't seem to work?

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3171]
[TRoW-A Harrowing Escape Turn 23.gz](https://github.com/wesnoth/wesnoth/files/2037219/TRoW-A.Harrowing.Escape.Turn.23.gz)
Doesn't look like she is negating the ZoC of that wolf rider.

**Comment by ln-zookeeper** [comment]
Looks like she is. Nothing suggests otherwise to me.

**Comment by Konrad22** [comment]
You are right, that was just me misunderstanding the ability.

**Comment by stevecotton** [comment]
Added the "Invalid" label, but confess I almost logged the same bug.
