### ISSUE TITLE
Factions are forced into sorted order

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3177]
Issue discussed before, starting from https://forums.wesnoth.org/viewtopic.php?p=628111#p628111

Testing suggests adding `​` (zero-width space) is good as workaround.

**Comment by Vultraz** [comment]
Feature, not a bug.

**Comment by ProditorMagnus** [comment]
Documented this behavior then.

**Comment by gfgtdf** [comment]
> Documented this behavior then

Maybe you should also add a mention your workaround then since there are probably many add-ons that suffer from this.

**Comment by ProditorMagnus** [comment]
Yes, I linked this issue.
