### ISSUE TITLE
Conditional weapon special is always marked inactive

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3178]
https://i.imgur.com/vUbcrwm.png charge is active and doubles damage, but says inactive. Out of core specials this also includes marksman, backstab.

Problem exists with both active_on= filter and with [filter_self]formula= filter.

This works correctly in 1.12.

I remember inactive specials being gray, but that might be from 1.10. If anyone knows how to do it now, would be appreciated.

**Comment by Vultraz** [comment]
She fixed the attack dialog showing inactive specials. This is an issue with specials' tooltips showing them inactive incorrectly.

**Comment by jostephd** [comment]
Fixed on master by 826a76a939149409d5e98d9fc36664a92efc6438. That hasn't been backported to 1.14 yet.

**Comment by Wedge009** [comment]
Back-ported 826a76a9 as abf8eba6, confirmed it did the job in 1.14 before pushing. Let me know if I did anything wrong.

**Comment by jostephd** [comment]
> Let me know if I did anything wrong.

Looks quite correct to me, especially the use of `git cherry-pick -x` to reference the commit in master. Thanks! :-)
