### ISSUE TITLE
Experimental AI can't recruit units in Dark Forecast map

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#3182]
Experimental AI can't recruit units in Dark Forecast map. Wesnoth 1.14.1

![lua](https://user-images.githubusercontent.com/3605541/40586557-e209992a-61c3-11e8-931d-90289acd42a7.PNG)

**Comment by Alarantalara** [comment]
This should be fixed by https://github.com/wesnoth/wesnoth/pull/3130

**Comment by mattsc** [comment]
Thanks for reporting.  This is [fixed](https://github.com/wesnoth/wesnoth/commit/09fe71911f6577311baa6dad497775f176c90646) in 1.14.2 which was released yesterday.
