### ISSUE TITLE
Add an asset credits file specifying the copyright for each asset

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3186]
We need some way for people to learn what the copyright is on any individual image, sound, or music track. It would also be very beneficial to have an easy way for people to learn who the author of an asset is.

In addition, it would be ideal to have it in a machine-readable format so that Travis can alert us to any missing or out-of-date entries.

In that vein, I suggest adding a csv (comma-separated-values) file with columns for date added, author, path, and license. Or possibly three files, one for each asset type. I believe csv allows extraneous spaces, so it could be kept human-readable by judicious use of extra whitespace (and keeping the path, which would be the most variable in length, as the last column). Even if csv doesn't natively do this, it's easy for a Python tool to strip extra whitespace.

Of course, I'm open to other ways of doing this too.

**Comment by stevecotton** [comment]
Seems like something that's already been invented elsewhere, with every invention having a slightly different feature-set. I suggest taking something that's already in use elsewhere, even if that means it has features that Wesnoth doesn't use.

Possible option (but even within Debian this is optional to use):
https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#example-files-paragraph

**Comment by CelticMinstrel** [comment]
Yeah, I'd be fine with that too.

**Comment by Pentarctagon** [comment]
I'll see if I can get to it this weekend, probably using the csv method.  Nothing against any other formats, but csv is dead simple, and the part that would take the most time would be actually looking through Wesnoth's 12k+ image/sound files and documenting what is licensed under what.

**Comment by Pentarctagon** [comment]
A question: how would I go about determining authorship for things whose commit message doesn't explicitly say who the author is?  The creator and the committer obviously can be different people.

**Comment by CelticMinstrel** [comment]
Well, if they're still around, I'd start by asking the committer. You could also try searching the forums to see if it was posted there by the actual artist.

**Comment by Pentarctagon** [comment]
Yeah, good idea.  Looks like there's also the (not up to date) [ARTISTS](https://github.com/blackberry/Wesnoth/blob/master/data/core/images/portraits/ARTISTS) file at least for portraits, and of course [about.cfg](https://github.com/wesnoth/wesnoth/blob/master/data/core/about.cfg).

I'll probably also upload it as a google doc or something at some point soon, in case anyone else wants to help out or just knows a bunch off the top of their head.  Otherwise, me alone going through all 14,738 files will take quite a bit of time.

**Comment by eltiare** [comment]
I did a few music pieces under the handle jeremy2. When I contributed it was understood that any music submitted was under the license of the game itself.

**Comment by CelticMinstrel** [comment]
@Pentarctagon - Did you ever finish this list?

**Comment by Pentarctagon** [comment]
Vultraz at one point told me I shouldn't bother, so I stopped.

**Comment by CelticMinstrel** [comment]
In my opinion it's absolutely necessary to have some way to determine whether the copyright on an asset is GPL or CC, though. So while it may be unnecessary to go through all old assets to figure out the source, we do need this for any assets added after CC licensing became an option.

That said, it would still be really nice to have a way to know the source of any individual asset, including older ones.

(Pinging @Vultraz too since he clearly has opinions on this.

**Comment by Pentarctagon** [comment]
I don't disagree, and I do still have the spreadsheet up on google docs, though I don't know when I'll really be able to devote time to it other than May/June at the latest.

**Comment by eltiare** [comment]
If any of my stuff is still in there, you can count it as GPL.

**Comment by jostephd** [comment]
Another case where this will be useful: https://github.com/wesnoth/wesnoth/issues/4345#issuecomment-534103569 wanted to consult the artist who had originally created a portrait:

> Is there an inconsistency to how Delfador's portraits are oriented throughout the campaigns? ... Do we have the artist available to consult on this?

**Comment by Pentarctagon** [comment]
Yep.
