### ISSUE TITLE
[Campaign tag] Chronological ordering does not work properly for BW tag.

### ISSUE THREAD

**Issue by nemaara** [wesnoth/wesnoth#3187]
When using the year and start_year keys under the [campaign] tag, if "BW" is used, the date in front of the BW acronym does not seem to affect the campaign's order position in the menu when ordered by date. For example:

Using "10 BW" or "100 BW" or "1 BW" will not affect a campaign's position relative to TRoW (which has a start_year of 2 BW), it will always either appear in the same spot (before or after) TRoW, depending on its rank. The rank value will affect this position, e.g.:

TRoW has a rank of 230, and giving a campaign a rank lower than 230 (e.g. 229) will put that campaign before TRoW, and giving a value of 231 will put that campaign after TRoW, regardless of the BW date.

**Comment by jostephd** [comment]
Fixed on 1.14 and added to the fwdport queue.
