### ISSUE TITLE
SUF formula side returns wrong value

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3189]
```
$ wesnoth.get_units({formula="side=1"})[1].side
2
```
Seems to be caused by https://github.com/wesnoth/wesnoth/commit/d41f4934d52f770143236fac7c761e3543c814a9.

**Comment by Vultraz** [comment]
Confirmed the removal of the -1 there results in the correct value. I'm assuming here it treated the side number as a 0-based array index, but I don't see how that -1 made it so... Anyway, this is a bug fix not a feature so it should go into 1.14.

**Comment by CelticMinstrel** [comment]
No, it should not. Fixing this will break FormulaAI code.

**Comment by Vultraz** [comment]
But it's a bug.

**Comment by CelticMinstrel** [comment]
It's a bug that probably doesn't even affect anyone; but I'm pretty sure that fixing it would break FormulaAI stuff that's included with the core game, not to mention potentially breaking FormulaAI stuff coded by other people.

**Comment by stevecotton** [comment]
Deprecated in 4c8167c4e7b2144f4e484dfbbb0aca1e6fe4dbf6, which will recommend using `formula="side_number=1"` instead.

@CelticMinstrel, I'm assuming it's good to close this now. If you want to keep it as a reminder to remove the deprecated code in 1.17, please reopen it (but please don't make master diverge from 1.16 immediately).
