### ISSUE TITLE
[SotA] S9 loss condition doesn't work

### ISSUE THREAD

**Issue by beetlenaut** [wesnoth/wesnoth#3192]
In 09_Training_Session, you are supposed to lose if all your new Dark Adepts die, so they are counted in a die event. The condition upkeep=full filters out potential loyal adepts and the leader. However, leaders now _have_ upkeep set to full, so that doesn't work. The game always counts one too many adepts (because it counts the leader), and you don't lose if they all die.

So, the leader, Ras-Tabahn has to be made loyal at some point before that scenario starts, or another condition has to be added to the die event in that scenario to filter him out, or the engine has to go back to making leaders loyal by default. I'm not sure which would be better.

**Comment by sigurdfdragon** [comment]
The fix I'll do sometime in the next week will be to adjust the wml filter conditions.

**Comment by gfgtdf** [comment]
>  I think making leaders have upkeep=loyal by default would be best. Not sure if that's easy though.

this  would then again compablity issue for no reson in the next release, also it might give problems when a leader is converted into a non-leader and it keeop or doesnt keeo it's loyal upkeep..

**Comment by CelticMinstrel** [comment]
> this would then again compablity issue for no reson in the next release, also it might give problems when a leader is converted into a non-leader and it keeop or doesnt keeo it's loyal upkeep..

Well, the compatibility argument is moot if this is a bugfix (that is, we're changing it back to how it worked in 1.12). As for the second thing, the easiest way to get around that would probably be for the upkeep getter to also check whether the unit can recruit; then setting the upkeep of a leader unit would have no effect, but if the unit is no longer a leader, whatever upkeep was set suddenly takes effect again.

**Comment by gfgtdf** [comment]
> Well, the compatibility argument is moot if this is a bugfix

it's not, people that write addons for 1.14 will expect the new behviour, changing it will break their addons.

> that is, we're changing it back to how it worked in 1.12)

noone showed yet that it behaved differntly on 1.12

> As for the second thing, the easiest way to get around that would probably be for the upkeep getter to also check whether the unit can recruit; then setting the upkeep of a leader unit would have no effect, but if the unit is no longer a leader, whatever upkeep was set suddenly takes effect again.

that is exactly the current beviour.
