### ISSUE TITLE
upgrade to luajit

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3195]
we should upgrade to luajit at some point, the current lua intepreter is just too slow, the concrete example why i want this is that i tried to port the mainline mapgen to lua. it gave the same result as the cpp mapgen but was just way to slow to actually use it . the critucal part is the generate_heightmap function:

```
local width=213
local height=213 
local iterations=52489 
local hill_size=8 
local island_size=0

function create_array(n, a)
	a = a or 0
	local r={}
	for i=1, n do
		r[i] = a
	end
	return r
end

function generate_height_map(width, height, iterations, hill_size, island_size, island_off_center)
	
	local math_max = math.max
	local math_min = math.min
	local math_floor = math.floor
	local math_sqrt = math.sqrt
	local math_random = math.random -- use wesnoth.random in the actual mapgen code.
	local res = create_array(width * height)
	local center_x = math_floor((width + 2) / 2)
	local center_y = math_floor((height + 2) / 2)
	for i=1, iterations do
		local is_valley = false

		local x1 = island_size > 0 and (center_x - island_size + math_random(island_size*2) - 1) or (math.random(width))
		local y1 = island_size > 0 and (center_y - island_size + math_random(island_size*2) - 1) or (math.random(height))
		local radius = math_random(hill_size)

		if island_size ~= 0 then
			local diffx = x1 - center_x
			local diffy = y1 - center_y
			local dist = math_floor(math_sqrt(diffx*diffx + diffy*diffy))
			is_valley = dist > island_size			
		end
		-- std_print("placing hill at " .. x1 .. "," .. y1 .. " radius=" .. radius .. " is_valley=" .. tostring(is_valley))
		local min_x = math_max(1, x1 - radius)
		local max_x = math_min(width + 1, x1 + radius)
		local min_y = math_max(1, y1 - radius)
		local max_y = math_min(height + 1, y1 + radius)
		for x2 = min_x, max_x - 1 do
			for y2 = min_y, max_y - 1 do
				local xdiff = (x2-x1)
				local ydiff = (y2-y1)
				local hill_height = radius - math_floor(math_sqrt(xdiff*xdiff + ydiff*ydiff))
				if hill_height > 0 then
					local old_h = res[width * (y2 - 1) + x2]
					if is_valley then
						res[width * (y2 - 1) + x2] = math_max(0, old_h - hill_height)
					else
						res[width * (y2 - 1) + x2] = old_h + hill_height
					end
				end
			end
		end
	end

	--normalize to 0-max_wanted
	local max_wanted = 1000
	local h_max = res[1]
	local h_min = res[1]
	for i, h in ipairs(res) do
		if h > h_max then
			h_max = h
		end
		if h < h_min then
			h_min = h
		end
	end

	print("h_max=" .. h_max .. " h_min=" .. h_min)
	local norm_factor = max_wanted / (h_max - h_min)
	for i= 1, #res  do
		res[i] = math_floor((res[i] - h_min) * norm_factor)
	end

	return res
end

generate_height_map(width, height, iterations, hill_size, island_size, island_off_center)
```

where the parameters in the code above are taken form the last scenario of the popular addon 'world conquest 2'.

benchmarking gives that the corresponding c++ code runs in ~0.2 second while the wesnoth lua interpreter takes ~3.5 second to execute the code above. benchmarking with a standalone luajit.exe also gives a speed similar to the c++ code. (actually the luajit doesn't have a precise clock function to timestamp, but commandline returned instantly with the correct result when i ran this code).

So using luajit ofc not only allow use to port the mainline mapgen to lua but it would also allow umc author to implement more custom mapgens in lua (bases on the default mapgen or not).

I also think that other codes in paerticular the ai code would also profit from it.

it's no easy though, the obviousl issues are:
1) it's unclear whether your c++/lua exception workaround woudl still work as-is and how difuculat it's be to adapt it.
2) luajit is basd on lua 5.1/5.2 (but it has some of the 5.3 function aswell), some lua code that use lua 5.3 feature might give compiler erros.

**Comment by jyrkive** [comment]
LuaJIT would open up possibilities for [JIT spraying](https://en.wikipedia.org/wiki/JIT_spraying) attacks. Also, it can't be used on iOS.

**Comment by gfgtdf** [comment]
> Also, it can't be used on iOS.

hmm ye this is a problem

> LuaJIT would open up possibilities for JIT spraying attacks

the page says that jit prorgamms are usually except from dep, i dont' so how it cannot work with dep to prevent execution of you non-executable data. It just has to mark every block of compiled block as executable and unmark it when its freed, on windows you use VirtualProtect for hat iirc, quite possible that luajit does that.

**Comment by gfgtdf** [comment]
> Also, it can't be used on iOS.

actually, wher did you see that? the officl page luajit.org/install.html says luajit works on iOS 3.0+

**Comment by jyrkive** [comment]
The wording in Wikipedia is a bit misleading. JIT compilers don't disable DEP, they just allocate executable memory for the machine code.

The problem on iOS is simply that iOS doesn't allow programs to allocate executable memory. JavaScriptCore (Apple's JavaScript interpreter) is exempt, but nothing else can use JIT on iOS.

**Comment by gfgtdf** [comment]
> The wording in Wikipedia is a bit misleading. JIT compilers don't disable DEP, they just allocate executable memory for the machine code.

hmm i see, but i wonder how other interperters handle it then? I mean these days a lot of stuff, in particular javascript, is jitted.

> The problem on iOS is simply that iOS doesn't allow programs to allocate executable memory. JavaScriptCore (Apple's JavaScript interpreter) is exempt, but nothing else can use JIT on iOS.

the luajit page says that it falls back to an interpreter in that case, which is obviously slower than the riginal original luajit but still faster than the original lua interpreter.

**Comment by jyrkive** [comment]
> hmm i see, but i wonder how other interperters handle it then? I mean these days a lot of stuff, in particular javascript, is jitted.

JIT compilers are either designed to be safe against untrusted input (and updated whenever a vulnerability is found), or to only be used with trusted input. I don't know in which category LuaJIT is.

**Comment by gfgtdf** [comment]
hmm as understood it it does aim to be of the first category, but afiak its a one-man team that maintains luait so it's somwhat questionable whetehr he is able to fix everything asap.

**Comment by singalen** [comment]
[LuaJIT work on iOS, it will just do no JITting](https://news.ycombinator.com/item?id=9877311).

**Comment by GregoryLundberg** [comment]
I looked at LuaJIT, and rejected it because it's running so far behind on fixing bugs and implementing the Lua language. In fact, it appeared that the one-man-team was, effectively, a zero-man-team.

Yes, he's still making some changes. But, officially, [he's leaving the project and moving on to something else and looking for someone to hand it off to](https://www.freelists.org/post/luajit/Looking-for-new-LuaJIT-maintainers).

**Comment by Pentarctagon** [comment]
There also haven't been any versions released, stable or development, for over a year: http://luajit.org/download.html

**Comment by gfgtdf** [comment]
> I looked at LuaJIT, and rejected it because it's running so far behind on fixing bugs

hmm i didnt went though to issue tracker of that yet, maybe you could link me one or two unfixed luajit bugs that are really important in your opinion.

> implementing the Lua language.

i think that the perfoamnce gain does outweight possible features that lua has that luajit doesn't becasue  as i said in my first post the new parformance does really allow you to do things in luajit that you wouldn't do in default lua.

> In fact, it appeared that the one-man-team was, effectively, a zero-man-team. Yes, he's still making some changes. But, officially, he's leaving the project and moving on to something else and looking for someone to hand it off to.

hmm well in that case it's probalby better just to wait to see how it evolves, i know that that post is from 2015 but this issue doesnt have any hurry eigher.

> There also haven't been any versions released, stable or development, for over a year: http://luajit.org/download.html

The last few releases there also has about a year gap bweteen them so this doesn't really mean anything.

**Comment by GregoryLundberg** [comment]
Yes, I would love to see the performance gains.

My main issue with LuaJIT is that it is no longer "Lua" and is not documented. Yes, at one time, it was sufficiently Lua-like that the difference did not matter. But, today, a programmer cannot pick up a Lua manual and expected everything to "just work". What won't work? Well, you can make a reasonable guess if you're willing to compare your current Lua manual to an archived copy of the Lua 5.1 manual.

Don't put the question to me. But it to all UMC authors: What Lua language features do you use which you will need to rewrite so that me can switch to LuaJIT?

**Comment by CelticMinstrel** [comment]
Here's one thing: https://www.lua.org/manual/5.1/manual.html#pdf-ipairs

Compare to 5.2: https://www.lua.org/manual/5.2/manual.html#pdf-ipairs

The `__ipairs` metamethod is used by the `vconfig` metatable. Even if that was changed, it's only because 5.3 no longer requires the metamethod and manages to give the expected behaviour without it, which would not be the case if falling back to 5.1.

**Comment by gfgtdf** [comment]
> The __ipairs metamethod is used by the vconfig metatable

even though luajit is based on 5.1 it has quite some of the 5.2 and 5.3 features, in particular it's quire likely that it supports this one since it seems rather easy to implement.

**Comment by CelticMinstrel** [comment]
I think that kinda makes it a lot worse, to be honest. It's not like using Lua 5.1. It's not like using Lua 5.2. It's not like using Lua 5.3.

I don't think a performance boost is worth confusing people.

**Comment by singalen** [comment]
I think, if Wesnoth switches to LuaJIT, one of the two is eventually inevitable:
* Lua will eventually catch up with performance, like Javascript and PHP caught up with V8/Hiphop, and LuaJIT becomes obsolete,
* or Wesnoth will become reliant on LuaJIT speed (like in mapgen), and iOS version will become dog slow.

**Comment by GregoryLundberg** [comment]
The second option seems more likely.

Lua's specification is to use only fully-compliant ISO Standard C so it's unlikely to gain a huge speed-up. To get really fast you need to compile to native code, not byte-code, so iOS is unlikely to ever see the speed-up. In fact, it's possible other systems will begin to more strongly enforce restrictions against data execution, so Windows, Andriod or Linux may eventually suffer the same as iOS.

We could obtain some of the speed improvement for LuaJIT by caching Lua byte-code to disk and pre-fetching some features.

I suggest it would be better to change from a monolithic build to a modular build and add support for plug-in libraries (as well as the ability to swap out some of our standard libraries, such as the C++ map generator). Lua could be moved to one and, then, for those who care to, the Lua module could be swapped out for a LuaJIT module.

**Comment by CelticMinstrel** [comment]
That would certainly be great for those rare people who want to try writing Wesnoth AI code in C++, as it would mean they don't need to rebuild the entire engine to do so and can distribute their AI as a dynamic library.

**Comment by gfgtdf** [comment]
> I think that kinda makes it a lot worse, to be honest. It's not like using Lua 5.1. It's not like using Lua 5.2. It's not like using Lua 5.3.

It's not bad, you have a clear list of what is suppoered and whats not, unlike lua 5.3 and lua 5.2 luajit is fully compatible with lua 5.1, it also has every feature of lua 5.2 that des not break compability with lua 5.1

> Lua will eventually catch up with performance, like Javascript and PHP caught up with V8/Hiphop, and LuaJIT becomes obsolete,

An interpreted lua will nevery reach the full speed of jitted lua.

> Wesnoth will become reliant on LuaJIT speed (like in mapgen), and iOS version will become dog slow.

as i said above even on ios the luajit is quit a bit faster than original lua. also for things liek mpagenerated thy luckily only need to be run on the hosts client so for those maps you could just yout teammates to host the game.


> We could obtain some of the speed improvement for LuaJIT by caching Lua byte-code to disk and pre-fetching some features.

the 'compilation' time is really not an issue in lua our code, so this would not give us much, also we probably should disallow reading lua byte code anyways for security issues in particular as lua 5.2 no longer checks the lua bytecode for validity.

> I suggest it would be better to change from a monolithic build to a modular build and add support for plug-in libraries (as well as the ability to swap out some of our standard libraries, such as the C++ map generator). 

First of, having some clients with luajit and some with lua would really make it hard to wmlauthors to write eite code compatible to both, second we don't want umc to contain binary code for security reasons, (also this requires umc to compile for each plattform etc)

**Comment by CelticMinstrel** [comment]
I don't see Lua 5.1 compatibility as a good or desirable thing.

**Comment by ExtReMLapin** [comment]
> 
> 
> LuaJIT would open up possibilities for [JIT spraying](https://en.wikipedia.org/wiki/JIT_spraying) attacks. Also, it can't be used on iOS.

Stop spreading this kind of wrong informations : 

https://github.com/LuaJIT/LuaJIT/blob/1e66d0f9e6698fdee672c40a9a5b4159c9254091/src/lj_mcode.c#L130
https://github.com/LuaJIT/LuaJIT/blob/1e66d0f9e6698fdee672c40a9a5b4159c9254091/src/lj_ccallback.c#L288

**Comment by ExtReMLapin** [comment]
Adding more information about what exactly luajit is doing.
It's an reimplementation of Lua, the interpreter itself is coded in Assembly, which makes it ~4 times faster than Lua PUC (Official implementation).

**Comment by Pentarctagon** [comment]
Given luajit is still only compatible with lua 5.1/5.2 whereas Wesnoth has updated to 5.4, is there any chance of luajit being used at this point (any other issues aside)?
