### ISSUE TITLE
wesnothd: Remove netstats from /q help

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3200]
Its command handler has been commented out, https://github.com/wesnoth/wesnoth/blob/1.14/src/server/server.cpp#L2132. Currently /q netstats results in empty message from server, so should be removed from https://github.com/wesnoth/wesnoth/blob/1.14/src/server/server.cpp#L362 too.

Help message text: https://github.com/wesnoth/wesnoth/blob/1.14/src/server/server.cpp#L1068

Re #2500

**Comment by loonycyborg** [comment]
Perhaps I'll implement it instead.

**Comment by ProditorMagnus** [comment]
When editing something there, would be nice to add /q version to help message.

**Comment by Pentarctagon** [comment]
Closing as this command no longer exists.
