### ISSUE TITLE
MP game statistics broken when room created by 1.14.2 user

### ISSUE THREAD

**Issue by tamanegi-jp** [wesnoth/wesnoth#3201]
If a game is created by 1.14.2 user, game statistics of both of players seem to be merged.
Kills and losses show the same value, and the same happens for damage inflicted and taken.

When the room is created by 1.14.1 user, this does not happen.
So this depends on the BfW version of room host.
BfW version of room guest is not related to this issue.
Pls fix!

Relating forum thread:
https://forums.wesnoth.org/viewtopic.php?f=4&t=48272&p=629291#p629291

**Comment by tamanegi-jp** [comment]
In addition, recruited unit list in statistics is also mixed.
So players can know enemy's recruit (and faction) even when fog exists.
This bug is terribly serious in 1vs1 matches.

**Comment by vgaming** [comment]
Confirming. // I didn't test 1.14.2 specifics, but confirm the stats being wrong sometimes.

**Comment by tamanegi-jp** [comment]
To reproduce:
1. 1.14.2 player makes a new room at the lobby (any map/scenario OK, AFAIK)
2. begins game with AI (or some other players)
    (first player = human, second = AI)
3. first player ends first turn
4. AI does something
5. in the second turn of first (human) player, statistics show the AI's recruit 

There maybe many other ways to confirm.

**Comment by ProditorMagnus** [comment]
Caused by https://github.com/wesnoth/wesnoth/commit/ee50171d13c7f20a3c8147201c2b78ab54fafae3

**Comment by CelticMinstrel** [comment]
Tagging @gfgtdf since that's his commit.

**Comment by ProditorMagnus** [comment]
69f026fd656a7f15070e544390a6ae7565fe7d39 has some improvements, but 1.14.2 clients still see other recruits even when hosted with this commit.

**Comment by gfgtdf** [comment]
hmm 1.14.3 was just tagged so we cannot put a fix for that case in 1.14.3 anymore, what we could do if we really wanted is to to put some hack in the server code to inject save ids into the scenario for the other players, this won't work for the host though, also it might casue OOS if the other players use the save_id of that side. Other than that i think you best option is to force your other players to use the latest wesnoth version (you can use /q version), in particular for ladder games.
