### ISSUE TITLE
add a /clear command to mp lobby chat

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3202]
as said in the title. It'd be nice to have a /clear command in the chat window in the mp lobby to get rid of older chats and messages in that window

**Comment by sevu** [comment]
Chat can be cleared with `ctrl+x` (pressed outside the chat window). But it's nowhere mentioned that this exists.

**Comment by ProditorMagnus** [comment]
Issue is about lobby chat.

**Comment by sevu** [comment]
Then this does make sense...

**Comment by macabeus** [comment]
@sevu the `ctrl+x` command is mentioned here: https://wiki.wesnoth.org/HotKeysSystem#Multiplayer_.28chat.29

Anyway, it looks like a quick win. I can add this command

**Comment by stevecotton** [comment]
At least two people have been confused, so I'm adding a picture for clarity. The issue is to add a `/clear` command to this chatbox:
![mp_lobby](https://user-images.githubusercontent.com/101462/150715826-fa63f3d7-6e04-4543-ab6c-852ea208c8f2.png)

**Comment by stevecotton** [comment]
Resolved in #6457 and #6476.
