### ISSUE TITLE
Terrain Avoidance in SotA - The Mage

### ISSUE THREAD

**Issue by dsime42** [wesnoth/wesnoth#3204]
What version of the game are you running?
-       Wesnoth V 1.13.10

Have you built (from sources) the game by yourself? gcc/g++ version? SDL library versions?
-       No. Got it with Fedora distribution

What operating system are you using? What version/release of that operating system?
-       Linux
-       Fedora release 26 (Twenty Six)
-       4.16.7-100.fc26.x86_64 #1 SMP Wed May 2 21:45:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Can you reproduce the problem? If you can please provide steps to do it.
-       Yes
SotA-The Mage
I have a Shadow in the village at 28.2 which I move closer to the Mage's keep, but not close enough to be attacked
When Crelanu leaves his keep to attack my bat in the village at 21.12 the mages in the castle have been able to kill my shadow

Rinconan or Issa both have MP=5 and Forest requires 2 MP per hex but they are able to move through four (4) hexs of Forest/Flat to kill my Shadow
and Ginmera, also MP=5, was able to traverse 1 castle hex, 1 mountain hex,and 3 hill hexes to attack

They seem to not have any terrain issues at all
[SotA-The_Mage_bug.gz](https://github.com/wesnoth/wesnoth/files/2065425/SotA-The_Mage_bug.gz)

**Comment by dsime42** [comment]
Ginmera was also able to able to move to 17.7 to kill a Spectre that I had moved into the lake

**Comment by dsime42** [comment]
I guess I need to update to FC27 :-(

**Comment by sevu** [comment]
Could you post the replay

**Comment by dsime42** [comment]
I don't know that it will help you because after I had the problem I did some testing and then loaded to just before the incorrect movement and didn't move to within a range of movement with terrain cost = 1 to finish the scenario

[SotA-The_Mage_replay.gz](https://github.com/wesnoth/wesnoth/files/2066068/SotA-The_Mage_replay.gz)

**Comment by sigurdfdragon** [comment]
This issue was fixed by
https://github.com/wesnoth/wesnoth/commit/64d3aa1ab69cf5269b19d2c695a659a3bfc3efd9
which first appeared in 1.13.11
