### ISSUE TITLE
helper.set_wml_tag_metatable has been deprecated

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#3208]
Version 1.14.2 gives this warning:
`warning deprecation: helper.set_wml_tag_metatable has been deprecated and may be removed at any time.
   (Note: You should use wml.tag instead in new code)`

But this is not documented anywhere, as far as I can tell.
https://wiki.wesnoth.org/LuaWML:Misc#helper.set_wml_tag_metatable

wesnoth.deprecate_api returns the old element, not the replacement, so I guess we shouldn't assume simply renaming deprecated things to their undocumented replacements will work?

**Comment by Vultraz** [comment]
@CelticMinstrel has started updating the wiki with regards to this.

**Comment by CelticMinstrel** [comment]
I recently created https://wiki.wesnoth.org/LuaAPI/wml

**Comment by doofus-01** [comment]
Great, thanks.  I suppose you'll link that in the LuaWML section visible from the ReferenceWML page once it's ready.
I will test the substitution later and close this issue, if no one else does first.

**Comment by shikadiqueen** [comment]
I'd like to point out that it's actually not a 1:1 replacement for `helper.set_wml_tag_metatable`.

Doing a simple substitution like this:
https://github.com/project-ethea/Naia/commit/cfc67c2f294371d64756354bb88b2e3e32809e7f

Resulted in errors like this:
```
20180605 04:48:12 error scripting/lua: In function lua_kernel::run(): Lua Error:
  When executing, Lua runtime error: ~add-ons/Naia/lua/spawner.lua:10: attempt to call a table value (field 'tag')
stack traceback:
        ~add-ons/Naia/lua/spawner.lua:10: in main chunk
        [C]: in field 'dofile'
        [string "..."]:27: in main chunk
```

Which I had to fix with this:
https://github.com/project-ethea/Naia/commit/855c41210a2c39715bd651d6dc11541a213f7b21

**Comment by CelticMinstrel** [comment]
Yeah, that's what I said in my comment too.

**Comment by CelticMinstrel** [comment]
The threats in the deprecation warning won't be carried out until 1.15 at the earliest; and probably much later.
