### ISSUE TITLE
Feature request: Add Steam Workshop support.

### ISSUE THREAD

**Issue by stavrossk** [wesnoth/wesnoth#3214]
Since Wesnoth have a map editor, I think it would be nice to add support for a Steam Workshop to the Steam version of the game so people could upload their maps and also download maps made by other people.

**Comment by CelticMinstrel** [comment]
You can do that without Steam Workshop. Though you need to make it an addon which is a bit of extra work…

**Comment by gfgtdf** [comment]
It was decied against steam worksshops, the main reason is that we dont want to split the comunity. To updad/download user made content (often abriviated a UMC in the wiki) like for example maps you use the addon manager, the addon mnager can be accesesed by clicking the buton 'add-ons' on the main screen. See also this wiki page https://wiki.wesnoth.org/PBLWML on more information on how to upload an addons via the addon server.

**Comment by CelticMinstrel** [comment]
I mean you can't just upload the maps to the addons server, as far as I know. You need to bundle the map into a scenario, even if it's a trivial scenario with nothing but the map and the side definitions.

For example, if you have one two-player map, you could create a "_main.cfg" in the data/addons/your_addon_name folder with the following content:

```
#ifdef MULTIPLAYER
[multiplayer]
    map_data={~addons/your_addon_name/maps/your_map.map}
    [side]
        side=1
    [/side]
    [side]
        side=2
    [/side]
[/multiplayer]
#endif
```

Then you add a "_server.pbl" file in the same folder as described in gfgtdf's link, add the maps folder containing the actual map, and you can upload that from within the game by clicking on "Addons" at the main menu.

**Comment by stavrossk** [comment]
@gfgtdf @CelticMinstrel Thanks a lot guys, it all makes sense now. Not really need a Steam Workshop if I can add addons/mods from the in-game menu. Please bear with me, I'm new to this game.
