### ISSUE TITLE
undead bats - sound issue with se/s/sw defense animation

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3215]
Reported by @shikadiqueen, I'm mostly opening this issue to sort out the possible reasons.

Problem: 
The hitsound is played correctly for all directions. However:
* In case it is defended against se/s/sw the sound of the {DEFENSE_ANIM ...} of the base unit is played as well - one can always hear it when the bat is not being hit. 
* When the bat is hit one can hear it sometimes as well and sometimes not, the variation's hit sound can always be heard. I suspect that both sounds are played the same time then, and the engine handles this situation not the same.

(I used different sounds for testing to hear the difference)

The Soulless bat inherits the {DEFENSE_ANIM ...} from the base unit, _this code is intended to be overwritten_ later. The relevant code looks like this:
```
    [defend]
        start_time=-126
        [frame]
            image={BASE_IMAGE}:1,{REACTION_IMAGE}:250,{BASE_IMAGE}:1
        [/frame]
        # Do not change to SOUND:HIT, this has to remain a hit_sound_frame
        [if]
            hit_sound_start_time=-25
            hits=hit
            [hit_sound_frame]
                sound={HIT_SOUND}
            [/hit_sound_frame]
        [/if]
    [/defend]
```
The bat has the following code. It uses the SOUND_HIT macro, below I replaced the macro by the code it inserts. As of my understanding, the first [defense] block below should _fullly_ replace the [defend] block above - might be I am wrong in this interpretation.
```
    [defend]
        direction=s,sw,se
        [if]
            hits=miss
            offset=0.0~-0.15,-0.15~0.0
        [/if]
        start_time=-126
        [frame]
            image="units/undead/soulless-bat-se-[3,4,3].png:[1,250,1]"
        [/frame]
        [if]
            hits=yes
            attack_sound_start_time=-25
            [attack_sound_frame]
                sound={HITSOUND}
            [/attack_sound_frame]
        [/if]
    [/defend]
    [defend]
        direction=n,nw,ne
        [if]
            hits=miss
            offset=0.0~-0.15,-0.15~0.0
        [/if]
        start_time=-126
        [frame]
            image="units/undead/soulless-bat-ne-[3,4,3].png:[1,250,1]"
        [/frame]
        [if]
            hits=yes
            attack_sound_start_time=-25
            [attack_sound_frame]
                sound={HITSOUND}
            [/attack_sound_frame]
        [/if]
    [/defend]
```
Now I would like to specifically ask, how would you _expect_ the inheriting to happen (one can't look it up with :inspect as it doesn't show animations)
(simply using hit_sound_frames instead of attack_sound_frames was not a quick fix)

**Comment by ln-zookeeper** [comment]
The [variation] was set to inherit=yes, so the first [defend] block was getting merged with the one from the base WC/Soulless, resulting in an unintended mess. But then there was also the other problem mentioned in the above commit messages.
