### ISSUE TITLE
[WML] changing unit type in a prestart event causes the unit to disappear

### ISSUE THREAD

**Issue by Dugy** [wesnoth/wesnoth#3225]
I have found that if [modify_unit] is used to change a unit's type in a prestart event, the unit disappears. If it is in a start event or some other event, everything goes fine.

This problem happens in 1.14, but didn't happen in 1.12.

**Comment by gfgtdf** [comment]
this sounds really unlikely, does the unit disaapear completely or is it just now drawn on the map ? (can you still access it with wesnoth.get_unit(x,y)) ?

**Comment by Dugy** [comment]
Their dialogue lines are skipped, so they are not there. I may try wesnoth.get_unit(x, y), but I don't have time for that right now, maybe today afternoon.

**Comment by gfgtdf** [comment]
hmm we just had this commit whihc appeartly fixed a bug that might be related to using modfy_unit in mainline https://github.com/wesnoth/wesnoth/commit/354a6709f947e12d24c5b4cb864ccd09357540b0 . maybe it helps in this case aswell.

**Comment by Dugy** [comment]
Sounds like it, but there is a key difference: one of the units in my case is a leader who came from the previous scenario, others were recalled using the [recall] tag. Maybe recalling doesn't remove the units from the recall list until prestart ends?

**Comment by gfgtdf** [comment]
> Maybe recalling doesn't remove the units from the recall list until prestart ends?

hmm considering that in that commit the bug was fixed by using [recall] this is also somewhat unlikely, lo note that that scenario also uses modify_unit in a prestart event so there is clearly more onvolved than just modify_unit during a prestart event.

**Comment by Dugy** [comment]
Looks like that. In my case, modify_unit is used to change the unit's type, which includes recalculating all the units' properties from type and modifications unlike those in that scenario.

**Comment by gfgtdf** [comment]
> Looks like that. In my case, modify_unit is used to change the unit's type, which includes recalculating all the units' properties from type and modifications unlike those in that scenario.

modify_unit uses unstore_unit under the hood since it is more or less a lua implementation of the old MODIFY_UNIT macro so it _always_ includes recalculating the units stats (and overwritiing it then later moving the whole calculations to absurdum, (which i also why i never use [modify_unit] in my addons.))

**Comment by Dugy** [comment]
[unstore_unit] _doesn't_ recalculate the unit stats if the type is not changed. This is essential in many use cases, because recalculating stats includes fully healing it and the advancing animation, which is unwanted in most mid-scenario application.

**Comment by gfgtdf** [comment]
> [unstore_unit] doesn't recalculate the unit stats if the type is not changed

it does, the point is just that its getting overwritten with the content of that variable that contians basicially all information like hp attaks etc except animiations. Basicially all functions that create units from wml tables work the same way unrelated to whether it's [unit], [unstore_unit], wesnoth.create_unit(), or loading a savefile: first read the type= and variation= attributes and create a unit of that type, second apply all modifications, third overwrite unit stats with the rest of the content of the wml table.

**Comment by Dugy** [comment]
Ah, yes, really, some little details like modified animations are lost. Some of them are kept when creating the unit with [unit]. But in any case, it's a different kind of unstoring when the type is changed.

**Comment by gfgtdf** [comment]
ok now i tested it myself:
```
[modification]
	id="gfg_test"
	name="test"
	[event]
		name = "prestart"
		[modify_unit]
			[filter]
			[/filter]
			type="Knight"
		[/modify_unit]
	[/event]
[/modification]
```
on a 2p standard mp map. transforms both leaders to knighs as it should

**Comment by Dugy** [comment]
The conditions don't seem to be so easy. Please try it in the context, campaign _Kill the King,_ scenario 1 (intro can be skipped by hitting escape). The scenario code contains three advance_unit macro calls, if they are moved from the start of start event into the end of prestart event, the units will disappear.

**Comment by gfgtdf** [comment]
well, i won't debug umc code in particular if its rather complicated like loti, so unless you can give me simple case where it happens i'll assume its a bug in your addon.

**Comment by Dugy** [comment]
So if I comment out the complicated code (that shouldn't have any effect there), will you have a look at it?

**Comment by gfgtdf** [comment]
> So if I comment out the complicated code (that shouldn't have any effect there), will you have a look at it?


well actually already tried and it worked after i commented the lines at the bottom of that file global_events etc.

**Comment by Dugy** [comment]
So some WML code started working differently on 1.14 compared to 1.12. Debugging this won't be easy. Anyway, it's not a bug. I'll close it and reopen it if I find some unusual cause.
