### ISSUE TITLE
[help] dead links

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3228]
The section gameplay -> healing contains many death links.

**Comment by Vultraz** [comment]
Caused by my fix to that bug where abilities with the same name but different IDs weren't separated.

**Comment by sevu** [comment]
Could you link to the change, and eventually the issue if one exists?
 
A nice thing I found out a few weeks ago – if two traits have a different name but same id they get only one entry in the help, e.g. one can make a reworded elemental ability without cluttering up the help.

**Comment by jostephd** [comment]
#3355 is also about "Abilities with the same id".

**Comment by Wedge009** [comment]
@sevu These are dead links in addition to the ones we discussed in #2963?

**Comment by jostephd** [comment]
Fixed, probably by 5e92b8e80d846cb130db1d3c58543a25fa8507fe. Opening that section in wesnoth --debug shows no dead links.
