### ISSUE TITLE
EI - 11. Captured, missing prisoners from the recall list

### ISSUE THREAD

**Issue by Landiss** [wesnoth/wesnoth#3237]
In this scenario the player starts with his leaders and most of his units imprisoned, not under his control. He has to free them first. 

What I think is intended is that the prisoners are formed from the recall list of the player. However, what happens is the game generates new lvl1 recruits to be prisoners. Furthermore, the first prison cell is empty, the second one is half empty and only the third one is full. They should be all filled up with recall list units, right?

See the screenshot:
![captured](https://user-images.githubusercontent.com/20052491/41243646-f89be6d0-6da2-11e8-8f22-906ed7320a24.PNG)

**Comment by ln-zookeeper** [comment]
Version? Platform? Have any savefiles? Any error/warning messages whatsoever?

**Comment by Landiss** [comment]
Ah, yes. 1.14.3, Steam, Windows 10. I haven't noticed any error messages. Here's save file:
[EI-Captured Turn 11.gz](https://github.com/wesnoth/wesnoth/files/2092874/EI-Captured.Turn.11.gz)

**Comment by Landiss** [comment]
And here's the save from the beginning, as requested on discord:
[EI-Captured.gz](https://github.com/wesnoth/wesnoth/files/2093655/EI-Captured.gz)
