### ISSUE TITLE
ctrl+X (cut) does not work in chat line

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3245]
as said in the title, ctrl+X (cut) does not work in the (ingame) chat textbox.

**Comment by ProditorMagnus** [comment]
ctrl+A is another one that has nonintuitive behavior.

**Comment by sevu** [comment]
Can be closed?

**Comment by gfgtdf** [comment]
ye I don't think it applies to master as master has given 1 mostly removed.

**Comment by sevu** [comment]
:+1:
