### ISSUE TITLE
Conditional jump or move depends on uninitialised value

### ISSUE THREAD

**Issue by bckpkol** [wesnoth/wesnoth#3249]
Version: 1.15.0-dev
SDL built from source trunk with clang
Wesnoth built from source trunk with clang, too
Clang version 6.0
OS - Ubuntu 18.04
Linux bckpkol-HP-Notebook 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I've found a bug using Valgrind. It's in src/gui/core/event/handler.cpp.
```
void init_mouse_location()
{
        point mouse = get_mouse_position();

-        SDL_Event event;
+        SDL_Event event={};
        event.type = SDL_MOUSEMOTION;
        event.motion.type = SDL_MOUSEMOTION;
        event.motion.x = mouse.x;
        event.motion.y = mouse.y;

        SDL_PushEvent(&event);

```

**Comment by Pentarctagon** [comment]
Do you mean the Wesnoth version you built is 1.5.0-dev?

**Comment by bckpkol** [comment]
No, sorry. v1.15.0-dev

**Comment by Wedge009** [comment]
What specifically is Valgrind complaining about, the uninitialised `event`? Some members are defined after the creation, but I agree that any newly created object should be initialised before use. Where does the conditional jump instruction come in, is that from its analysis of the compiled code?

**Comment by Wedge009** [comment]
Looks like `init_mouse_location()` has already been updated. Please re-open if Valgrind is still flagging this as an issue.
https://github.com/wesnoth/wesnoth/blob/ea90383f1de6ee14f6eedc4f78c9de5f5303a46b/src/gui/core/event/handler.cpp#L913-L924
