### ISSUE TITLE
Support vertical mousewheel scrolling in [menu_button]

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3251]
The [menu_button] widget is used in mp_create_game screen and in the statistics dialog. It would be convenient if "mouse wheel up" and "mouse wheel down" over the drop down, when the drop down is closed, selected the previous/next option.

**Comment by CelticMinstrel** [comment]
I think currently they scroll the menu view itself (if it's overflowing and has a scroll bar), so doing this would mean losing that. (But maybe that's okay.)

**Comment by CelticMinstrel** [comment]
Apparently I missed the "when the drop down is closed" part.

I guess this doesn't make sense to add to the [multimenu_button], either, so Vultraz's commit seems good.
