### ISSUE TITLE
Core dumps on OpenBSD when connecting to add-ons server

### ISSUE THREAD

**Issue by yason** [wesnoth/wesnoth#3261]
Hi!
Wesnoth 1.14.x dumps core when trying to connect to add-ons server on OpenBSD-amd64. 1.12.x is working fine.
Backtrace is attached. What other information would be helpful?
[wesnoth.gdb.txt](https://github.com/wesnoth/wesnoth/files/2108436/wesnoth.gdb.txt)

**Comment by yason** [comment]
Thanks for the hint. I will check that and report back.

**Comment by yason** [comment]
Wesnoth built against boost with icu support connects to add-ons server as expected. Thanks!

**Comment by sevu** [comment]
Added it to the list at https://wiki.wesnoth.org/Compilingwesnoth#Prerequisites, please have a look if the wording is accurate.

**Comment by yason** [comment]
Looks good for me.
