### ISSUE TITLE
[turn][command][attack] is not validated

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3262]
Attack has keys max_range and min_range, which mostly do not work. However, even when those have default value 1, game allows sending [turn][command][attack] to attack unit that is not in the allowed range of 1. It is also possible to attack more times per turn than max_attacks allows.

Some other [command]s that are not considered allowed for normal game result in OOS, which is the expected result here too.

http://replays.wesnoth.org/1.14/20180616/2p__Clearing_Gushes_Turn_1_(11099).bz2 shows two longrange attacks without OOS, and then some further testing which does have OOS.

http://replays.wesnoth.org/1.14/20180616/2p__Clearing_Gushes_Turn_1_(11157).bz2 is clean example, it only has one longrange attack.

**Comment by ProditorMagnus** [comment]
It is quite minor issue, since when player can send arbitrary wml to server, he can use normal actionWML to do everything anyways.

**Comment by gfgtdf** [comment]
> It is quite minor issue, since when player can send arbitrary wml to server, he can use normal actionWML to do everything anyways.

people, (except the host whoe sends the scenario content)cannot send arbitrary wml (actionwml) to server

**Comment by ProditorMagnus** [comment]
99ddf3bce8f3e162dc59fcd73103e3a90b0944bb
