### ISSUE TITLE
Unit overlays added by [effect] cumulate

### ISSUE THREAD

**Issue by ln-zookeeper** [wesnoth/wesnoth#3264]
Easy steps to reproduce: start Eastern Invasion, :cl to scenario 9, and pick up the holy amulet at 10,2. The unit receives the ankh overlay via an [effect], and for example whenever progressing to the next scenario or the unit advances, it gets re-added to the unit's overlays= list on top of the existing ones.

Presumably, while the overlays= list is already specifically retained across unit rebuilds, the overlay-adding effect keeps being re-applied.

**Comment by CelticMinstrel** [comment]
I guess the effect should basically be changed to "add if not already present" then? Perhaps even use `std::set` for the overlays list.

**Comment by ln-zookeeper** [comment]
Hard to say whether there are legitimate usecases for having the same overlay appear in the list several times, but at least the order should be retained (which, presumably, is that the overlays are drawn in the same order as they've been added).

**Comment by gfgtdf** [comment]
This is the same as https://github.com/wesnoth/wesnoth/issues/3220, having an object effect that changes an attribute that is retained across unit rebuilds just didn't really make sense, even if we used one of the fixes proposed here #3220 would still be there so it would not be a complete fix, we should either make image_mod not retained across unit rebuilds which is not really an option for 1.14 or use direct unit modifications actionwml to get that effect ([then] in [object])

**Comment by CelticMinstrel** [comment]
Yeah retaining the order would be good so I guess `std::set` won't work. Still, we could implement either "add only if not already present" (ie search first) or "remove before adding".

I think not retaining image_mod is the best choice really, but as you say that's not really an option for 1.14. 

Unless… what if we had the `unit_creator` (ie the `[unit]` tag) automatically convert these keys to an `[object]` when encountered?

**Comment by gfgtdf** [comment]
> Unless… what if we had the unit_creator (ie the [unit] tag) automatically convert these keys to an [object] when encountered?

hmm possible but i's quite likely that there are some corner cases that we might miss when we do that. also there is afaik no way to distinguish between a untore_unit that explicitly sets a  overlay= via set_varible before and a unstore_unit that jut has overla= set because the previousl store unit had it set.
