### ISSUE TITLE
Crash after loading save-game (memory access error)

### ISSUE THREAD

**Issue by ePaul** [wesnoth/wesnoth#3266]
When loading this start-of-scenario save from To Lands Unknown 3.0.1, [TLU-Defense of Saffaros.gz](https://github.com/wesnoth/wesnoth/files/2109224/TLU-Defense.of.Saffaros.gz), in Wesnoth 1.14.3+dev on Ubuntu 17.10, I can click through the story screen sequence (or skip it), and then Wesnoth crashes with a "Speicherzugriffsfehler" (which is likely my german Ubuntu's translation for "memory access error").

Reproduced several times. Clearing the cache didn't change anything.

```
Battle for Wesnoth v1.14.3+dev (67076d376ae-Clean)
Started on Sun Jun 17 19:36:18 2018

Automatically found a possible data directory at /home/USER/projektoj/wesnoth

Data directory:               /home/USER/projektoj/wesnoth
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.14
Cache directory:              /home/USER/.cache/wesnoth

Setting mode to 1920x1026
Checking lua scripts... ok
20180617 19:36:34 warning engine: Invalid anchor!
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

I'm running a freshly built (locally) wesnoth from the 1.14 branch of today (67076d376ae). (It happened previously with a two weeks older version f1bf186c872 too.)

**Comment by ePaul** [comment]
Might be, how do I find this out? (I think I have a 64-bit Linux ... I'm not at home at the moment to check.)

I just did `scons` in the source directory, and then started the resulting `wesnoth` binary.

**Comment by ePaul** [comment]
```ShellSession
0 paulo@kato[0] 2018-06-18 20:43 ~/projektoj/wesnoth [1.14] 
$ ./wesnoth --version
Battle for Wesnoth v1.14.3+dev (67076d376ae-Clean)
Started on Mon Jun 18 21:27:41 2018

Automatically found a possible data directory at /home/USER/projektoj/wesnoth
Battle for Wesnoth 1.14.3+dev

Library versions:
Boost:             1.62
OpenSSL/libcrypto: 1.0.2g  (runtime 1.0.2g)
Cairo:             1.14.10 (runtime 1.14.10)
Pango:             1.40.12 (runtime 1.40.12)
SDL:               2.0.6   (runtime 2.0.6)
SDL_image:         2.0.1   (runtime 2.0.1)
SDL_mixer:         2.0.1   (runtime 2.0.1)
SDL_ttf:           2.0.14  (runtime 2.0.14)

Optional features:
Experimental OpenMP support:    no
JPG screenshots:                no
Lua console completion:         no
Legacy bidirectional rendering: yes
D-Bus notifications back end:   yes

0 paulo@kato[0] 2018-06-18 21:27 ~/projektoj/wesnoth [1.14] 
$ uname -a
Linux kato 4.13.0-45-generic #50-Ubuntu SMP Wed May 30 08:23:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

0 paulo@kato[0] 2018-06-18 21:29 ~/projektoj/wesnoth [1.14] 
$ file wesnoth
wesnoth: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=5ca123e1e4c2ba5eac4b725370273a6ca4605a21, not stripped
```
So yes, it looks like 64-bit executable on a 64-bit system.

**Comment by jostephd** [comment]
@inferno8 Do you know how to reproduce this crash?

**Comment by ePaul** [comment]
I'm still there, but only get the Github notifications at work, while all my Wesnoth related stuff is at home. I'll try to remember to check if this still happens with current Wesnoth, and if so, will do the debug build to get more info.

**Comment by Wedge009** [comment]
How's work going, @ePaul? (:

**Comment by ePaul** [comment]
So, I just tried it with an older build of the stable branch (v1.14.9+dev (ec3b2fb381d-Clean)), and could not reproduce it anymore. Same for a fresh build with v1.14.9+dev (43dd7e289f7-Clean).

So I guess I'll close this issue now. Thanks for reminding me to check this again.

**Comment by Wedge009** [comment]
Thanks for your confirmation!
