### ISSUE TITLE
GUI tooltip cover some content > should be displayed below and to the right

### ISSUE THREAD

**Issue by Landiss** [wesnoth/wesnoth#3274]
This was shortly discussed on Discord a couple days ago. GUI tooltips are by default displayed above and centered. This is not the usual way of displaying tooltips and they can cover content that should not be covered, for example in preferences:

![tooltip](https://user-images.githubusercontent.com/20052491/41619153-78793912-7405-11e8-90d6-16f88427ee98.png)

**Comment by Landiss** [comment]
I have checked the settings for this and I propose several changes that result in this:

1. Tooltips are displayed in relation to the mouse cursor, not the object containing the tooltip (but they are still fixed once generated). I admit I really don't understand why it was done differently.
2. Tooltip y position: if there is space, tooltips are displayed below the cursor. If there is no space below, they will display above. If there is also no space to fit the whole tooltip above, instead it is displayed as low as possible.
3. X position: by default they are displayed a bit to the right. If there is not enough space, they are displayed as to the right as possible (same as it was). I'm not sure if that's fine or perhaps it would be better to display them in such cases to the left of the cursor, if there is enough space.

Here's the changed cfg file with the above changes, hope someone can check it:

[tooltip_floating.zip](https://github.com/wesnoth/wesnoth/files/2118086/tooltip_floating.zip)

Some screenshots showing how it looks like:

![tooltip1](https://user-images.githubusercontent.com/20052491/41640920-c98fb53e-7463-11e8-867b-5f30f96e63e0.PNG)
![tooltip2](https://user-images.githubusercontent.com/20052491/41640923-cb135578-7463-11e8-910a-170001990b6a.PNG)
![tooltip3](https://user-images.githubusercontent.com/20052491/41640924-cd3e33ea-7463-11e8-9761-868555b54845.PNG)

**Comment by CelticMinstrel** [comment]
Here's the diff for those uninterested in downloading a zip:

```diff
27,30c27,30
< 		, 'V'
< 		, if(m.y >= w.y
< 			, if(m.x >= w.x, 'I', 'III')
< 			, if(m.x >= w.x, 'II', 'IV')
---
> 		, 'TooBig'
> 		, if(m.y + 25 + w.y >= s.y
> 			, 'Above'
> 			, 'Below'
44,48c44,47
< 		, 'I'   , m.x - (w.x / 2)
< 		, 'II'	, m.x -  w.x
< 		# extra offset to avoid being obscured by the mouse. #
< 		, 'IV'  , m.x + 15
< 		, 'V'   , 5
---
> # extra offset to avoid being obscured by the mouse. #
> 		, 'Above' , m.x + 20
> 		, 'Below'  , m.x + 20
> 		, 'TooBig'   , 5
64c63,67
< 	switch(
---
> 	if(preferred_y < 0
> 		, s.y - w.y
> 		, preferred_y)
> where
> 	preferred_y = switch(
66,70c69,71
< 		, 'I'   , m.y - (w.y + 5)
< 		, 'II'  , m.y
< 		, 'III' , m.y -  w.y
< 		, 'IV'  , m.y + 25
< 		, 'V'   , 5
---
> 		, 'Above' , m.y - (w.y + 15)
> 		, 'Below'  , m.y + 25
> 		, 'TooBig'   , 5
112c113
< 			  loc(source_x + (source_w / 2), source_y + (source_h / 2))
---
> 			  loc(mouse_x, mouse_y)
121c122
< 			  loc(source_x, source_y)
---
> 			  loc(mouse_x, mouse_y)
```

I don't see any particular issues with it, though I'm wondering a little at the change on line 112 (but I have no particular reason to reject the change).

**Comment by Landiss** [comment]
Thanks for checking this, @CelticMinstrel. 

As for the 112 and 121 lines - as I said, I don't understand why it was source and not mouse in the beginning. Maybe there was some reason for this, but I tested this quite a lot and it works fine everywhere. Having it in relation to mouse and not the object below it really makes more sense, especially as the objects vary a lot in size which could result in the tooltip to be displayed far from the cursor or be partially covered by it in some cases. 
It would be best to have the tooltip move with the cursor, as that is the typical way and it would make sure cursor does never cover the tooltip - but I don't know how to do that.

**Comment by Wedge009** [comment]
Is there a problem with @Landiss' contribution? Perhaps it should be submitted as a PR so it is more likely to be reviewed?
