### ISSUE TITLE
Legend of the invincibles crashes on iOS

### ISSUE THREAD

**Issue by kernowboy** [wesnoth/wesnoth#3276]
Legend of the invincibles crashes on iOS.

I am playing into the light on version 1.14.2 (up to this point it was excellent).
The game crashes and will further fail to load previous saves, so means the campaign is unplayable from this point, It has now happened to me twice.

Once it happened when I ended a scenario, and once at the end of a turn.

The following add-on had errors and could not be loaded:
    /private/var/mobile/Containers/Data/Application/235F83BD-513E-413C-996C-91564162FE79/Library/Application Support/wesnoth.org/iWesnoth/.wesnoth1.14/data/add-ons/Legend_of_the_Invincibles/_main.cfg

Please report this to the author or maintainer of this add-on.

Details:

    Macro/file 'FLAG' is missing
    at languages/da_DK.cfg:2170
        included from languages/da_DK.cfg:14
        included from <unknown>:18
        included from ~add-ons/Legend_of_the_Invincibles/terrain.cfg:18
        included from ~add-ons/Legend_of_the_Invincibles/_main.cfg:173

**Comment by singalen** [comment]
No promises yet, but if it's a problem I'm thinking about, the there is a workaround: install and/or uninstall any OTHER add-on.

**Comment by kernowboy** [comment]
Thank you , this seems to have worked, Greatly appreciated
