### ISSUE TITLE
Addon version is taken from _info.cfg when _server.pbl exists

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3278]
Issue for https://forums.wesnoth.org/viewtopic.php?f=4&t=48236

**Comment by shikadiqueen** [comment]
Assigning to @Vultraz since he did almost all of the changes in the 1.14 add-ons client.

**Comment by Vultraz** [comment]
I can't really figure out a good way to test this, but it *should* be fixed...

**Comment by ProditorMagnus** [comment]
Create addon consisting of _main.cfg that requires download and create _server.pbl and upload it. Download and host it with another client. Try join with original client.

**Comment by ProditorMagnus** [comment]
It is fixed.
