### ISSUE TITLE
boost unit tests segfault with LTO

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#3279]
I'm not sure if this is a problem with wesnoth or not, but I'm creating this issue so that if it is, it's documented somewhere besides the Discord/IRC logs.

---

Currently, compiling the `boost_unit_tests` on master with LTO enabled (mostly) results in a segfault when using [GCC 7](https://travis-ci.org/Pentarctagon/wesnoth/builds/394877532), but does not segfault when I use GCC 5.4, [nor with Clang 6](https://travis-ci.org/Pentarctagon/wesnoth/builds/395346390).  The command I used when running docker locally is:
`scons all --option-cache="" --debug=time ctool=gcc cxxtool=g++ ccache=yes build=release opt="-O3" enable_lto=yes arch=native nls=no jobs=14`

Valgrind then gives the [following results](https://pastebin.com/r4S3d9r4) when run as:
`valgrind --tool=memcheck --log-file=valgrind.log --track-origins=yes --leak-check=no --num-callers=500 ./boost_unit_tests`
as well as printing the following error to the terminal:
> unknown location(0): fatal error: in "Test setup": memory access violation at address: 0x00000008: no mapping at fault address

---

When doing a debug build using the command:
`scons all --option-cache="" --debug=time ctool=gcc cxxtool=g++ ccache=yes build=debug nls=no jobs=14`
and running valgrind as:
`valgrind --tool=memcheck --log-file=valgrind.log --track-origins=yes --leak-check=no --num-callers=500 --read-var-info=yes ./boost_unit_tests-debug`

the boost unit tests give a successful result(though even [currently](https://travis-ci.org/wesnoth/wesnoth/jobs/395473865#L1137) it has thousands upon thousands of of "image not found" errors), with valgrind then giving the [following results](https://pastebin.com/mQBUBFmG).

---

So, while on one hand it seems somewhat likely that this is a bug with GCC 7+LTO given that it works with GCC 5.4 and Clang 6 as well as for GCC 7 only for the `-O1` optimization level, valgrind also looks like it's finding something wrong, in which case it could instead mean that there is an actual issue and it's only causing problems due to however GCC 7 is trying to optimize.

**Comment by Pentarctagon** [comment]
Also, FTR, all those `image not found` errors seem to be due to image.cpp's `create_texture_from_file` method, at which point the line `SDL_Renderer* renderer = CVideo::get_singleton().get_renderer();` returns a null pointer.

**Comment by Pentarctagon** [comment]
Some additional info:
- This issue also occurs with GCC 8
- When build with `-Og`, LTO, and ubsan enabled, it gives the following output:
```
src/video.hpp:50: runtime error: reference binding to null pointer of type 'struct CVideo'
src/gui/dialogs/loading_screen.cpp:216: runtime error: member call on null pointer of type 'struct CVideo'
src/video.hpp:67: runtime error: member access within null pointer of type 'const struct CVideo'
unknown location(0): fatal error: in "Test setup": memory access violation at address: 0x00000008: no mapping at fault address
```

**Comment by Pentarctagon** [comment]
This is still happening, though with slightly different line numbers:
```
./boost_unit_tests
src/video.hpp:45: runtime error: reference binding to null pointer of type 'struct CVideo'
src/gui/dialogs/loading_screen.cpp:220: runtime error: member call on null pointer of type 'struct CVideo'
src/video.hpp:62: runtime error: member access within null pointer of type 'const struct CVideo'
unknown location(0): fatal error: in "Test setup": memory access violation at address: 0x00000008: no mapping at fault address
```

Additionally, I looked into if any specific flag were causing the issue, and the flags:
```
-Og -flto -fno-combine-stack-adjustments -fno-compare-elim -fno-cprop-registers -fno-defer-pop -fno-forward-propagate -fno-guess-branch-probability -fno-ipa-profile -fno-ipa-pure-const -fno-ipa-reference -fno-omit-frame-pointer -fno-reorder-blocks -fno-shrink-wrap -fno-split-wide-types -fno-tree-builtin-call-dce -fno-tree-ccp -fno-tree-ch -fno-tree-coalesce-vars -fno-tree-copy-prop -fno-tree-dce -fno-tree-dominator-opts -fno-tree-dse -fno-tree-fre -fno-tree-sink -fno-tree-slsr -fno-tree-ter -fno-merge-constants
```
give identical output as `-O0 -flto` for `g++-8 -Q --help=`
- optimizers
- target
- params
- c++
- c
- common

However, that `-Og` mess of flags still results in the same error as above.  So whatever is causing the problem is something internal to GCC that's different between `-O0` and `-Og`.

**Comment by Pentarctagon** [comment]
On GCC 8, now for me `-O3` doesn't work, but `-O3 -fsanitize=undefined` does work.  So at this point, I'm just going to call this an upstream issue.

**Comment by Pentarctagon** [comment]
More specifically, the segfault happens on [this line](https://github.com/wesnoth/wesnoth/blob/e3cffa8b8e50e2859b3291ff630c578baa6c223e/src/gui/dialogs/loading_screen.cpp#L207), when calling the `faked()` method on `CVideo::get_singleton()`.

**Comment by Wedge009** [comment]
Sounds like this still an ongoing problem. It's not easy to isolate it to Wesnoth specifically is it?

**Comment by Pentarctagon** [comment]
I haven't looked too deeply at any of the actual code, and at this point my hope is pretty much just that it'll be fixed in the newer GCC in Ubuntu 20.04.

**Comment by Wedge009** [comment]
Are we sticking to LTS? I just noted 19.10 is already on GCC 9 but sticking to LTS seems sensible to me.

**Comment by Pentarctagon** [comment]
Historically, Wesnoth has kept support for the current and previous LTS release.  Also, just speaking for myself, I use Mint which is based only on the LTS releases.

**Comment by Pentarctagon** [comment]
Confirmed the segfault no longer happens with GCC 9.
