### ISSUE TITLE
In game chat messages are randomly cleared

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3282]
Observed with 1.14.3 and 1.14.4. Happens for wesnoth.message() and usercreated messages and invalid wml messages.

Usually they are cleared when new message is inserted, leaving that message visible, but sometimes it ends up with no visible messages.

I might eventually try it out with earlier 1.14, but compiling takes long time. This issue is currently mostly placeholder until it is further investigated.

**Comment by soliton-** [comment]
Perhaps you‘re talking about the advanced preference `chat message aging`?

**Comment by ProditorMagnus** [comment]
No, happens both with 0 and nonzero.

**Comment by ProditorMagnus** [comment]
Happens with 1.14.5 as well.

**Comment by gfgtdf** [comment]
do they disappear one after another or all at once, also what if your value of the chat message aging preference.

**Comment by gfgtdf** [comment]
> Usually they are cleared when new message is inserted, leaving that message visible, but sometimes it ends up with no visible messages.

this actualyl also sounds uninteded to me, i'd expect thatwhen a new message is added when there is no space, that then only the oldest message is deleted.

**Comment by ProditorMagnus** [comment]
All at once. Today I had chat message aging 0.

**Comment by gfgtdf** [comment]
and you are sure that it also happens with chat message aging nonzero?

**Comment by ProditorMagnus** [comment]
With 1.14.4 yes, havent tried today.

**Comment by gfgtdf** [comment]
> With 1.14.4 yes

So did you mean that you just observed that all these messages disappear together, or that they really  disappear before the specified time.

**Comment by gfgtdf** [comment]
i made a commit to master https://github.com/wesnoth/wesnoth/commit/2f54ecbc53abe69a294b5384b974537d84efa80d it is untested though.

**Comment by ProditorMagnus** [comment]
All always disappeared together.

**Comment by gfgtdf** [comment]
ok the ci also passes for the commit mentione above, please test it, there are not many changes to 1.14 so it should be appliable asis to 1.14

**Comment by ProditorMagnus** [comment]
Compiling. https://github.com/wesnoth/wesnoth/compare/1.14...ProditorMagnus:1.14-3282?expand=1

**Comment by gfgtdf** [comment]
ok please report whether it worked or not.

**Comment by ProditorMagnus** [comment]
Yes. Havent found games where I would expect issue happen so far.

**Comment by ProditorMagnus** [comment]
At this point it is sufficiently likely that fix helped.

**Comment by ProditorMagnus** [comment]
This has not been committed yet.
