### ISSUE TITLE
SotA - Against the World, Nagas say Saurians line of text

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3294]
The Nagas say that they are mad at me for killing their males. But. Every single enemy Naga is male, instead of, let's say, female. Which would mage more sense, story wise.

**Comment by CelticMinstrel** [comment]
Just checking, but how do you know they're male? (I know the nagas don't have differing male/female sprites, though I think there _is_ some way to distinguish.)

**Comment by Konrad22** [comment]
The name of the unit.
Male ones are called 'Naga ...' and female ones are 'Nagini ...'.

**Comment by CelticMinstrel** [comment]
Well, in any case it seems like it should be relatively easy to make them all female.

**Comment by sigurdfdragon** [comment]
Noted. No ideas at the moment for what, if anything, to do.

**Comment by Konrad22** [comment]
Ohhh, right, I remember.
Uh. So, change it, so the saurians says it and randomize the gender of the Naga? ^^ There still is no reason why all of their warriors should be the same gender. :D

**Comment by Konrad22** [comment]
@sigurdfdragon Would you mind reopening the issue? After all, you apparently fixed something that wasn't wrong, because I misunderstood the issue and managed to convince everyone. xD
The actual issue now still exists, right?

**Comment by sigurdfdragon** [comment]
@Konrad22 @beetlenaut 

All Saurian units are not specified/male gender. (can't see a difference like one can for the nagas via name) Do we think that would play well enough with having them say the dialog? If so, I'll reopen this and do something about it.

**Comment by Konrad22** [comment]
@sigurdfdragon 
Well, we certainly are sure, that the Nagas are saying a line that actually belongs to the saurians (and that does partially make no sense for the Nagas)...but if we take that line from them, then the Nagas just arrive on the battlefield, saying nothing. That's kinda random too.
So I actually hope for more information. I do think that maybe the Saurians were actually meant to arrive on turn 1, with the Nagas arriving on turn 2. The Saurians saying their actual line and the Nagas saying the line the Saurians are saying presently. That way it makes the most sense to me.
If the others agree, then I'd like you to change it in this way. :)

**Comment by beetlenaut** [comment]
@sigurdfdragon @Konrad22 Don't take the whole line from the nagas, just "they killed our males". That's the part I messed up. The saurian should have said that. Everything else was correct.

Saurians [definitely have males and females](http://wiki.wesnoth.org/Saurians). The females do most of the fighting, and the males work magic. You fight only augurs and their advancements in the swamp because the superstitious females (the skirmishers) have left. And, you kill almost all of them. That's what the line is supposed to refer to.

**Comment by CelticMinstrel** [comment]
If that's the lore, I wonder if we should add the `gender` key to all the Saurian unit type definitions? I mean add `gender=male` to the augur line units and `gender=female` to the skirmisher line units, so that the sidebar text will also support the campaign's assertion that all the augurs are male (if you're playing in another language, at least).

**Comment by Konrad22** [comment]
That would be neat.

**Comment by Konrad22** [comment]
It would be also very good, if you'd removed the saurian mages from the recruit list, after all all their males (the mages) are supposed to be dead. While there is no gender tag for saurians yet, the wiki does have a nice description of saurians, saying the the mages are male and the skirmishers are female.
This is not part of the ingame help description, but the scenario 'Battleground' (which is the reason the saurians are attacking you now) does seem to have had this wiki in mind, because you fight only against saurian mages there.

**Comment by sigurdfdragon** [comment]
Ok, so it seems like a proper fix would be the following:
Dialog changes for S21

        [message]
            speaker=Taxtrimon
            message= _ "We have found them! These magi destroyed a profitable business venture. We will take vengeance. You horse humans can assist us."
        [/message]
   
        [message]
            speaker=Fizztsars
            message= _ "We have arrived, Taxsstrimon. We will fight bessside you. They will pay for killing our malesss!"  # no spellcheck
        [/message]
(This next line is same as before)
        [message]
            speaker=Taxtrimon
            message= _ "Well met Fizztsars. Now these creatures will certainly fall."
        [/message]


Have Saurians only recruit skirmishers & ambushers in S21

Undo the naga gender change commits in S11 & S21
add a mix of genders in the placed nagas in S21

@beetlenaut @CelticMinstrel @Konrad22 Sound good?

**Comment by beetlenaut** [comment]
Yes, that sounds good.

**Comment by CelticMinstrel** [comment]
Not sure why you're asking me or Konrad, but I have no problem with it.
