### ISSUE TITLE
wesnoth can't be closed if being caught in an [end_turn] loop

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3296]
When trying to close wesnoth the map becomes grey, but the game still continues increasing the turns.
One has to kill it.
Of cause no campaign should have an event like that.
```
	[event]
		name=side turn
		first_time_only=no
		
		[end_turn][/end_turn]
	[/event]
```

**Comment by Vultraz** [comment]
Really not sure what we can do about this....

**Comment by ProditorMagnus** [comment]
It is general problem seen when addon code never yields, no matter if through recursive events, loops, or something else.

**Comment by soliton-** [comment]
It‘s not sensible to try to prevent infinite loops but perhaps it‘s feasible to allow the user to forcefully abort a scenario.

**Comment by CelticMinstrel** [comment]
I don't think it's feasible to allow the user to forcefully abort a scenario if caught in a Lua-internal loop (unless Lua somehow supports an "abort" key or something), but for this end turn loop it might be possible.

**Comment by soliton-** [comment]
So if it's not easy to prevent in the general case I'd say we should not do it at all (unless it's such a common error that every new umc author falls in that trap or something).

**Comment by sevu** [comment]
So I close this as won't fix. After all the OS will report wesnoth as unresponsive and offer to terminate it.
