### ISSUE TITLE
Map editor crashes during editing in canvas.cpp:1074

### ISSUE THREAD

**Issue by SirDifferential** [wesnoth/wesnoth#3298]
Game version: 1.14.3, downloaded from Wesnoth website, Windows 10 64-bit

![](http://plantmonster.net/pics/wesnoth/wesnoth_crash_0001.png)

While editing a map, the map editor started glitching with the map editor view being filled with all kinds of rubbish. It kind of looked like the screen wasn't cleared between frames and simply rendered everything over the old frame. I saved the map under a new filename, the glitching stopped, then the editor crashed with the above error.

Here's the map in case it's useful: http://plantmonster.net/wesnoth/africa_2v2_2.map

**Comment by Wedge009** [comment]
Can you still replicate this in 1.14.9 release? I've noticed the Editor crashing on me lately as well, but only after using it for a while, eg switching between playing and editing, usually from checking various issue reports. A fresh instance of Wesnoth doesn't crash straight away - eg I loaded your map without issue in 1.14.9.

**Comment by SirDifferential** [comment]
I only ever had this happen once and could never reproduce it. If the map editor crashes now, I doubt it would be the same crash - the version I used earlier is 1.5 years old and I bet a lot has changed since then.

**Comment by Wedge009** [comment]
Thanks for the quick response. I will close this, then. If it happens again, please re-open with the new information.
