### ISSUE TITLE
The unit name tooltip is broken 

### ISSUE THREAD

**Issue by Choicerer** [wesnoth/wesnoth#3306]
Mousing over a unit name doesn't bring the tooltip up as it did in 1.12

**Comment by Landiss** [comment]
Can you be more specific? It works for me in 1.14.3.

**Comment by Landiss** [comment]
Ok, after further testing I confirmed the bug and found out what is causing it. The bug only happens with long unit names, when the name is long enough to be covered by the rectangle of the movement points (unit_moves). Shortening the height of that rectangle (from 16 to 14) fixes the issue.

By the way, the same unit_moves rectangle is covering the unit_side flag, also breaking its tooltip.

**Comment by Choicerer** [comment]
Thanks! I've submitted a patch for this.
