### ISSUE TITLE
DiD - Saving Parthyn (1.14.3) unclear objectives/defeat conditions

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3308]
Even under torture I wouldn't be able to tell anyone what exactly the 'river fort defences' are. Or where they end. Please add something that makes is clear, maybe lables or a better explanation. (It really makes a difference when you are being hard pressed by the orcs.)
![rfd](https://user-images.githubusercontent.com/39015360/42215221-100959d4-7ebe-11e8-8474-2297cb0bc801.png)

**Comment by nemaara** [comment]
Fixed by #3841.
