### ISSUE TITLE
DiD - Saving Parthyn, triggering defeat condition

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3310]
Maybe the defeat condition could need adjustments.
![defeat](https://user-images.githubusercontent.com/21158813/42223318-cbcf7dce-7ed7-11e8-9d45-b54373a72a3b.png)
Formerly the castle was on the left and reached to the water – in practice one did ZoC that part.

I don't know what's the best way to balance this scenario, after all, it should not be to easy without using Walking Corpses.... no need to encourage just sitting in the forest. Maybe one could lower the defeat area, but set the AI to move towards it instead of focusing the main fight. [goal] or [micro_ai]s controlling the wolf riders maybe.
Or/and an map adjustment to have no consistent forest to defend, forcing the player to rely more on recruiting Walking Corpses for ZoCing. So far it is no problem to play without WCs at all.

**Comment by nemaara** [comment]
Fixed by #3841, if you think that it wasn't addressed adequately, we can reopen this issue.
