### ISSUE TITLE
NR S9: avoid the term princess

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3322]
> 09a_Introductions.cfg:                    message= _ "Not at all, Princess. I am no more than a humble peasant trying to free my people from enslavement."

(Partially) quoting from https://wiki.wesnoth.org/Etiquette:
> Addressing a princess as 'Princess' is an egregious, tin-eared piece of George Lucas-level modern phrasing. It's not even correct in the real world. ...

**Comment by Vultraz** [comment]
I wonder if we should come up with an Elvish word for "princess"...

**Comment by Vultraz** [comment]
I mean, sure, but having an Elvish word is worldbuilding.

**Comment by CelticMinstrel** [comment]
But what you want then isn't an Elvish word for "princess", it's an Elvish word for addressing a princess. These are two very different things.

**Comment by sevu** [comment]
The word »Princess« is quite used a lot in HttT. Seems like a leftover from the anime style times.

**Comment by nemaara** [comment]
I'll look at this for 1.14.8.

**Comment by nemaara** [comment]
See #4023.
