### ISSUE TITLE
[disable] affects attacks that it shouldnt when human player is involved

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3324]
Create unit that has 2 attacks.
lua wesnoth.get_units()[1].attacks[1].specials={[1]={'disable',{active_on='defense'}}}
lua wesnoth.get_units()[1].attacks[2].specials={[1]={'disable',{active_on='offense'}}}
Try attack with that unit. Results in no available attacks.
Droid that unit. Results in unit attacking.

**Comment by ProditorMagnus** [comment]
Actual attacks where it was observed https://gist.github.com/ProditorMagnus/d8cd93e9da62fc3589d4e99f5f918156

**Comment by Vultraz** [comment]
Seems the issue is not that the player can't use the attack, but that the AI can.

**Comment by ProditorMagnus** [comment]
One attack is for attack only, and other is for defend only. And player is supposed to be able to attack with attack that has attack only.

**Comment by ProditorMagnus** [comment]
Both of these specials work correctly when they are not on same unit.

**Comment by ProditorMagnus** [comment]
https://forums.wesnoth.org/viewtopic.php?p=631107#p631107 should also be caused by [disable].

**Comment by gfgtdf** [comment]
could be this issue https://github.com/wesnoth/wesnoth/blob/1.14.3/src/mouse_events.cpp#L993 , coudl you please check whether it works if you disable that (replace with `const bool all_disabled = false;`)

**Comment by ProditorMagnus** [comment]
It works correctly for me, so I dont have anything to test against.

**Comment by gfgtdf** [comment]
ao this issue can be closed ?

**Comment by ProditorMagnus** [comment]
No, I thought you meant about todays comment.

**Comment by ProditorMagnus** [comment]
With the change, original issue is fixed.
