### ISSUE TITLE
Undoing a recall only partially undraws the unit

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3325]
In The Siege of Elensefar, I recalled a Horseman and pressed undo. The tip of the Horseman's lance was left behind:

![screenshot_2018-07-06_10-11-48](https://user-images.githubusercontent.com/24784687/42373797-84b18718-8105-11e8-9740-1af279f0d13e.png)

I ran into a similar issue a few days ago, I don't know if it's the same: https://forums.wesnoth.org/viewtopic.php?f=21&t=39771&start=30#p630763

**Comment by Wedge009** [comment]
As in #3026, happens in undoing planned moves too.

**Comment by jostephd** [comment]
Fixed in the case of undoing recalls. Filed https://github.com/wesnoth/wesnoth/issues/3950 for undonig planned moves. Are there any other variants?
