### ISSUE TITLE
[1.15] allow filtering for upkeep in SUFs

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3333]
Celmin mentioned that it was probably an oversight that `upkeep` is not a valid thing to filter for in Standard Unit Filters.
(One can filter for it with [filter_wml] inside an SUF if neccessary, it will be slower though, as using [filter_wml] slows filtering down. In 1.13 many such cases were made availaible in the SUF.)

**Comment by gfgtdf** [comment]
how exactly shoudl ie behave? it coudl either work on the original upkeep (which is usllay either 'full' or 'free') or on the evaluated upkeep which is just a number.

> One can filter for it with [filter_wml] inside an SUF if neccessary, it will be slower though

for 1.13 a faster alterntive might be formula, which will be faster

**Comment by sevu** [comment]
I thought it should behave like when using it with `[filter_wml]`.
`[filter_wml] upkeep=loyal` works,
`[filter_wml] upkeep=free` works surprisingly not,
`[filter_wml]upkeep=0` works not.

If more can be made working that's good, but if there is some restriction, loyal is enough.

**Comment by ProditorMagnus** [comment]
I consider number more useful, but that should be available from formula anyways.

**Comment by CelticMinstrel** [comment]
Um, `upkeep=loyal`, `upkeep=free`, and `upkeep=0` should be synonymous in SUF.

It's possible I already implemented this on the schema branch, I can't remember though.
