### ISSUE TITLE
c18537e needs an equivalent on master

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#3343]
Commit c18537e needs forward-porting.

**Comment by hrubymar10** [comment]
Done - #3349

**Comment by jostephd** [comment]
Unfortunately this needs to be redone after #3603 :(

@hrubymar10 Feel free to unassign yourself if you don't have time or anything.

**Comment by jyrkive** [comment]
Rather than "forward-porting", it would be better to recreate the whole change from scratch.

Also, we don't "need" to do the same thing in the master branch. It's optional.

**Comment by jostephd** [comment]
Yes, we'd forward port the change by re-doing it, not by using `git cherry-pick`. But it's still a forward port. :)

Agreed that it's optional, labeled accordingly.

**Comment by Wedge009** [comment]
Just wondering: why does this need to be re-done? I see links in master as HTTPS rather than HTTP - am I missing something?

**Comment by jostephd** [comment]
Spot checking some the changes from the #3349, they _are_ present in master, so I guess we can close this. There _are_ some more instnaces of `http://` in master, but they're beyond the scope of this issue.
