### ISSUE TITLE
sidebar shows max_moves instead of moves for units of other sides

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3344]
If one modifies the moves of a unit belonging to another side, be it with lua, modify_unit or by storing/unstoring it, the changed moves are shown in the sidebar during the event, e.g. when that unit speaks.

After the event, it shows the unit as having as many moves as max_moves. Same for highlighting the movement range of that unit.
Inspect shows that the changes did persist and that it is an issue with displaying it.

In an following event the correct moves are shown again, for the duration of the event.

Where would it be useful to have this working? In the tutorial, PR #3297.

**Comment by gfgtdf** [comment]
this is probably caused by the whiteboard.

**Comment by sevu** [comment]
It happened without planning mode.
With planning mode it happens as well during the event.
If disabling planning mode after the 1st event, it happens in the 2nd too though.

**Comment by jostephd** [comment]
Removing the wb::future_map object in game_display::draw_sidebar() "fixes" the problem. I have no idea whether that's a sensible change, I am just confirming @gfgtdf guess that the whiteboard is involved. I did not enter planning mode.

**Comment by soliton-** [comment]
It seems sensible to expect another side's unit to have max_moves once it's their turn again and to show that in the side bar.

**Comment by stevecotton** [comment]
Implementing this would be bug #6716, that's to say the requested behavior is a bug. I accidentally implemented it for a while, which is why that bug got logged.
