### ISSUE TITLE
backport e4589e2 to 1.14

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3347]
> IRC: <celticminstrel> @sevu I think e4589e2 can probably be cherry-picked to 1.14, the other commit in that PR shouldn't be though.

Probably best do to this for 1.14.5, with the next release being close.

**Comment by CelticMinstrel** [comment]
I'm not sure if commits from closed pull requests hang around indefinitely, but 45674a is the same commit as merged to master.
