### ISSUE TITLE
Unit placed events don't work for units placed by [unstore_unit] in start events

### ISSUE THREAD

**Issue by Samonella7** [wesnoth/wesnoth#3348]
Using 1.14.3 from steam, on windows 10

[TestCampaign.zip](https://github.com/wesnoth/wesnoth/files/2195883/TestCampaign.zip)

Steps to reproduce using the attached campaign:

1) Start the campaign. In the first scenario, no units are poisoned. 
2) Move to the labeled tile to start scenario 2
3) In this scenario, a unit placed event should make all units poisoned. The enemy leader is, but your leader is not because he was stored in the previous scenario's victory event, and unstored in this one's start event.
4) You can use debug mode to create more units and see that they are also poisoned to verify that the unit placed event was made correctly

**Comment by jostephd** [comment]
Using the attachment, `unit placed` does fire if `fire_event=yes` is added to the `[unstore_unit]`.

**Comment by Samonella7** [comment]
Hm, I guess I can see reasons for it to work either way (requiring fire_event=yes or working even with =no). 

If this is the intended behavior, then the wiki needs to be updated for [unit placed](https://wiki.wesnoth.org/EventWML#unit_placed_.28Version_1.13.3_and_later_only.29) and [[unstore_unit].](https://wiki.wesnoth.org/DirectActionsWML#.5Bunstore_unit.5D)

**Comment by CelticMinstrel** [comment]
It should certainly not fire the event if you have `fire_event=no`. Which one should be the default, I don't know; but probably best not to suddenly change it.

**Comment by sevu** [comment]
Wiki is updated.
