### ISSUE TITLE
wmlindent crashes when sending SIGINT

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3352]
Aborting the program with `ctrl+c` shuts it down with a crash.
$ wmlindent 
```
^CTraceback (most recent call last):
  File "/home/space/git/wesnoth/data/tools/wmlindent", line 323, in <module>
    arguments, "|".join(exclude))
  File "/home/space/git/wesnoth/data/tools/wmlindent", line 249, in convertor
    linefilter("standard input", sys.stdin, sys.stdout)
  File "/home/space/git/wesnoth/data/tools/wmlindent", line 322, in <lambda>
    convertor(lambda n, f1, f2: reindent(n, f1, f2),
  File "/home/space/git/wesnoth/data/tools/wmlindent", line 118, in reindent
    for line in infp:
KeyboardInterrupt
```

**Comment by ProditorMagnus** [comment]
I would say that is expected.

**Comment by sevu** [comment]
I would say it should exit without Traceback.

**Comment by GregoryLundberg** [comment]
SIGINT is the interrupt signal. The terminal sends it to the foreground process when the user presses ctrl-c. The default behavior is to terminate the process, but it can be caught or ignored. The intention is to provide a mechanism for an orderly, graceful shutdown.

SIGQUIT is the dump core signal. The terminal sends it to the foreground process when the user presses ctrl-\. The default behavior is to terminate the process and dump core, but it can be caught or ignored. The intention is to provide a mechanism for the user to abort the process. You can look at SIGINT as "user-initiated happy termination" and SIGQUIT as "user-initiated unhappy termination."

SIGTERM is the termination signal. The default behavior is to terminate the process, but it also can be caught or ignored. The intention is to kill the process, gracefully or not, but to first allow it a chance to cleanup.

SIGKILL is the kill signal. The only behavior is to kill the process, immediately. As the process cannot catch the signal, it cannot cleanup, and thus this is a signal of last resort.

**Comment by soliton-** [comment]
This is the standard behaviour of python scripts.

**Comment by CelticMinstrel** [comment]
This is normal, but I think it might be good for the program to catch this exception and terminate silently (or with a simple one-line message) rather than with a traceback. It probably applies to the other Python tools too (wmllint, wmlscope, wmlxgettext).
