### ISSUE TITLE
Allow specifying map data by file path in addition to string

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3357]
Currently most maps are {} included to cfg file.

Using map file would have same effects as with using Lua file - immediately visible changes and possibility that different clients use different content.

**Comment by gfgtdf** [comment]
this is afaik possible https://github.com/wesnoth/wesnoth/blob/1.14.3/src/saved_game.cpp#L438

**Comment by ProditorMagnus** [comment]
Linking it to #2653 then.

**Comment by Vultraz** [comment]
Yes, it is possible with `map_file=`.
