### ISSUE TITLE
Move Campaign 'Save random seed' into Modifications enablement list

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3359]
~~(When you start a campaign, you can choose 'Save random seed'. I think this could or should be the default choice, which you have to disable if you don't want it, as 'savescumming' is almost encouraged very enticing if you are stuck and you can change outcomes by reloading.) <- this is just why i personally like to take that option. So not really relevant at all.
Adding a preference to tick in the preferences (maybe in 'Advanced' or 'General'), so you don't have to think of ticking the box every single time you start a campaign would be nice.
(I couldn't find such a preference, so if it exists, please make it easier to find.)~~
This is pretty much obsolete, because celmin had a better idea, so yeah.

**Comment by CelticMinstrel** [comment]
I'm tempted to close this as WontFix, but I'll wait to see what others think first.

**Comment by gfgtdf** [comment]
'Save random seed' also has disadvatages, in particular it cannot be used in mp (as it can be used to 'see the future' cheats) so the games created with it can maybe not be reloaded in mp.

When i implemented this, it was one the one hand assumed to be useful for debugging but also to fix the following issue:

> i dont like the non deterministicness: when i forgot something during my last move i reload the game and the result is eigher that i get worse random result making me fell betrayed by the game or getting better random results making me fell like i cheated.

I currently have no strong opinion on this simply becasue i don't play much singleplayer games these these days.

**Comment by CelticMinstrel** [comment]
Not sure if you changed the title before or after I made my alternate proposal, but maybe we should change it to that instead?

Something like "Save last state of the 'Save random seed' checkbox"?

**Comment by Konrad22** [comment]
After our first part of the talk, before the conclusion.

**Comment by jostephd** [comment]
> > i dont like the non deterministicness: when i forgot something during my last move i reload the game and the result is eigher that i get worse random result making me fell betrayed by the game or getting better random results making me fell like i cheated.

Nowadays one can save the game, replay it with the new `Play Single Move` button until the right point, and hit `Continue Play`, to get save-loading that uses the original dice. It's a bit tedious though.

**Comment by Wedge009** [comment]
Even I could probably do this, but I'm inclined to think that the default behaviour should have this disabled (which it currently is).

**Comment by jostephd** [comment]
Referencing #4448 

I don't feel strongly about this, but I think Save Random Seed is basically a built-in mod, and for mods we do remember which ones are activated. In fact, if we can fold Save Random Seed into the "Mods to enable" drop-down, that might be a good idea

**Comment by gfgtdf** [comment]
> In fact, if we can fold Save Random Seed into the "Mods to enable" drop-down, that might be a good idea

I had the same idea some time ago, so.i'd support this.

**Comment by Wedge009** [comment]
Noting that modifications selection doesn't appear to be working completely correctly: #3470.

**Comment by Wedge009** [comment]
Is this issue obsolete with 1.15.17+dev (1.16 beta)? I've notice there are now two pull-down menus in addition to the difficulty selection: modifications and combat, with the latter containing RNG-related options. If I understand correctly, this basically takes over from where 'save random seed' was in 1.14, right?

**Comment by Wedge009** [comment]
I think this is specific to 1.14, so closing as such.
