### ISSUE TITLE
Filtering for 'first uploaded' (date) in add-ons manager

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3360]
It would be nice to easily see what add-ons are 'new' on the server, e.g. when you open wesnoth or the add-ons manager after being absent from it for a long time. You can indirectly do that by filtering for least amount of downloads, but it's not foolproof.

**Comment by jostephd** [comment]
It's already possible in 1.14, just pick "First uploaded" from the "Order" dropdown.

**Comment by CelticMinstrel** [comment]
What should we label this if it's already possible? Invalid? WontFix? Something else?

**Comment by Konrad22** [comment]
I'm guessing 'Invalid'.
