### ISSUE TITLE
[terrain_mask] placing starting locations wrongly. 

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3364]
this code
```
wesnoth.wml_actions.terrain_mask { x = 2, y = 2, mask = "2 Ww", border = false }
```
will change the tile at (2,2) to water but will place the starting locations at (1,2).

Also the default behaviour of [terrain_mask] border=no is somehow bad since code like

```
wesnoth.wml_actions.terrain_mask { x = 2, y = 2, mask = "2 Ww"}
```
will change the tile at (1,2) instead of (2,2) which is totally unexpected.

**Comment by gfgtdf** [comment]
also terrain_mask doesn'T seem to be able to handle loosing the villages properly

**Comment by CelticMinstrel** [comment]
What do you mean? If the mask unmakes a village it's still somehow considered for upkeep?

**Comment by gfgtdf** [comment]
at least it still appears in the counter in the top bar.

**Comment by gfgtdf** [comment]
fixed in master
