### ISSUE TITLE
Adding info for Saurians in the Help

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3372]
There is more info avaible in the [wesnoth wiki](https://wiki.wesnoth.org/Category:Races) than in the ingame Help regarding the [Saurians](https://wiki.wesnoth.org/Saurians)~, [Drakes](https://wiki.wesnoth.org/Drakes_(race)), [Elves](https://wiki.wesnoth.org/Elves), [Dwarves](https://wiki.wesnoth.org/Dwarves) and [Monsters](https://wiki.wesnoth.org/Races#Monsters)~. 
It would be really nice to add those informations to the ingame Help. :)
(I do not know if/which parts of the wiki are intentionally not in the game help.)

~EDIT: While I'm at it, could we maybe add an 'Outlaw' section to the 'Humans'? I feel that they are very much missing in the description.~
(Moved to a new issue.)

**Comment by sigurdfdragon** [comment]
There's also this recent thread that has some attempts to come up with a race description for the Saurians.
https://forums.wesnoth.org/viewtopic.php?f=32&t=44441

**Comment by CelticMinstrel** [comment]
I'm pretty sure there's already info on drakes in the help, but it's commented out for some reason.

**Comment by Konrad22** [comment]
@sigurdfdragon So we have basically too many descriptions and no consens yet? xD

@CelticMinstrel The info in help is the info in help, just a bit more polished and minus the biology section. That's why I'm saying that there is 'more' info avaible in the wiki. :)

**Comment by sigurdfdragon** [comment]
@Konrad22 I think there's enough there to come up with a useable description, based on the wiki and refined by some things in that thread.

@beetlenaut @CelticMinstrel Any major reason to object to using the wiki description?

Also, going foward, it might be helpful to keep this issue limited the Saurian race description.
Haven't really looked over the rest of them, but at a glance, adding the Drake biology section is something worth considering.
