### ISSUE TITLE
SoF - Sc3, a Gryphon Rider just comes flying at me for no reason

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3379]
In this scenario I can start recruiting Gryphon Riders, after I somehow trigger the appearance of a Gryphon. Great. But, three things. (I might split them up into multiple issues later on, depends on how many of those three are valid.)
1) A Gryphon **Rider** (instead of a plain Gryphon) comes flying to my keep and is now part of my troops. Who is riding that Gryphon? Where did he come from? I mean, I though I'd be the first one riding them, so who is that guy?
2) Let's say the animation is a mistake and it should have been a Gryphon that turns into a Gryphon Rider after arriving at my keep. The dwarves are a bit too stoic about this. Like, no 'Maybe try riding the Gryphon?' or 'Huh, I think he wants me to ride on his back!' and 'Wow, it works. But this is a bit high up...'. Instead they just accept it without blinking, like they'd been riding Gryphons for ages.
3) There is no message like 'You can now recuirt Gryphon Riders.', they just appear on your recruit list. Please add such a message, it is useful and it is the standard. :)

~(While I'm at it, why would there be Woses attacking me in this scneario? Any idea? ..maybe add a line for the dwarves, they should be surprised about the Woses attacking, right now they act like it's completly normal for them.)~ Moved to another issue.

**Comment by CelticMinstrel** [comment]
Agreed on all three points, but I suggest you move the Woses to a separate issue.
