### ISSUE TITLE
NR - Epilogue, ambiguous wording

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3386]
There is a line:
“If a chieftain refused to co-operate with the Alliance, he was forcibly removed from his post and another more favourably **disposed** put in his place.”
When I read this the first time I thought there is a word missing, because disposed doesn't just mean 'inclined', but also 'getting rid of'. So I tought it was supposed to say:
'..another more favourably one than the disposed one put in his place...' or '..another more favourably candidate/orc put in his place...'
I hope that in this case 'disposed' can be changed to 'inclined' or another clear (not ambigous) synonym.

**Comment by Wedge009** [comment]
Just wondering: what is your native language? As a native English speaker this reads sensibly to me - 'favourably inclined' actually sounds more awkward than 'favourably disposed'.

If you really want an alternative, I am thinking something along the lines of

> If a chieftain refused to co-operate with the Alliance, he was forcibly removed from his post and a more favourably-disposed leader put in his place.

**Comment by Konrad22** [comment]
German. While it does read sensibly to me, once I got the right idea, I'm just trying to say that this can trip the player up when he thinks of the other meaning of disposed (because that meaning can fit, as long as there are minor adjustments). And I don't think that it has to be this way.

And I'm definntely happy with your suggestion, because this way the 'remove' meaning of disposed would not make sense at all. So it's not ambigous. :)
