### ISSUE TITLE
add warning for players that connect to wesnothd using older versions than 1.14.4

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3387]
i suggested on irc before to just block users using versions older than 1.14.4 from our server for their own good since those players could easily get hacked using the lua loadstring issue, but got no positive feeback on this.

But what we at least should do is to add a wanring for them when they login to tell them aout thesecutiry issue and to tell them to update immidiateley. Not all players check the forum regularely and not all players get updated automaticially via steam.

**Comment by soliton-** [comment]
This is implemented on 1.14 with 02804c1 now, right?

**Comment by gfgtdf** [comment]
yes
