### ISSUE TITLE
Suggestions for ATotB - Sc4

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3388]
https://forums.wesnoth.org/viewtopic.php?p=626970#p626970

**Comment by nemaara** [comment]
1. After watching your replay, I don't think forcing the player to keep Reeve Hoban alive is a good idea. This is the easiest, novice level campaign (which I guess most players will play after the tutorial), and having a rush to save ai scenario is too complicated gameplay-wise for this campaign. 

2. I can add a couple lines of text for when Baran attacks the warlord.

**Comment by nemaara** [comment]
See #3968.
