### ISSUE TITLE
ATotB - Sc3, the sun is shining underground/indoors?

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3389]
Basically there is this castle and the ToD is effective indoors. I think it would make more sense if it was either (regarding lighting enviroment):
a) lit floor(or however this might be called :D)
b) underground.

**Comment by CelticMinstrel** [comment]
There is an indoor "schedule" built-in, which if I recall correctly acts as a neutral (or possibly lawful?) time of day. I think it would be reasonable to apply that (or some variant thereof - obviously you shouldn't change to a lawful schedule when fighting chaotic units in their own home) with a `[time_area]` to the castle.

**Comment by Konrad22** [comment]
That would be neat. :)

**Comment by CelticMinstrel** [comment]
For the record, I don't like using the cave schedule for a castle, but maybe an "indoor darkened" schedule which is mechanically equivalent but uses a modification of the indoor image?

**Comment by stevecotton** [comment]
Comment from @Vultraz in #3457 - the lit stone wall terrains are deprecated, and should be replaced by a sconce on the terrain south of them. So for 1.15/1.16 the extra time zones that I've added in the commit auto-linked above should be done by (updating the map + merging #3457) instead.

**Comment by nemaara** [comment]
Fixed by #3882.

**Comment by AI0867** [comment]
I'm late to the party, but if we're adding an EASY explanation for the dark indoor ToD, we should probably also have an explanation for the sconces.

**Comment by jostephd** [comment]
@AI0867 I agree, [the tip](https://github.com/wesnoth/wesnoth/blob/aa901478c22be3dc0c32cdcf4c4807f19af2f428/data/campaigns/Two_Brothers/scenarios/03_Guarded_Castle.cfg#L770) should say something about the sconces hexes being neutral ToD. File a new issue?

**Comment by jostephd** [comment]
Reopening and assigning @nemaara at her request.

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/371a1bacd06dfdcf7b2d8a5d781dac5d6ea0c842 should be good now.
