### ISSUE TITLE
Tutorial suggestions/'bugs'

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3390]
I'm posting a bunch of things in this issue, because I'm not sure how much of it is still valid (I wrote them in the feedback threads of the forum 3 months (1.14.0) ago but no one seems to have reacted). So please do point out things to me that got already fixed and I'll cross them out.

I've had an idea! (no idea if it is any good)
How about making one more tutorial, one for Li'sar. As it is now, the tutorial is 'historically accurate' for Konrad, but absolutly not for Li'sar.

New tutorial scenario(tree)
Intro (choosing leader)
1a (Konrads training)
1b (Li'sars training)
2a
2b

Li'sars tutorial would be like a training session in the palace, under the care of Asheviere or her generals? ^^

Why give Konrad and Li'sar not the chance to level up? Is there any specific reason for that?
And how about making the units they recruit, recalls in HttT (or reinforcements at some point)? :D That would be awesome.

After your leader recruits (for the first time), ordering him to move to the village to heal, if he has enough moves left, would make sense.

Leveling up a unit in the first turtorial part makes me miss out on the explanation of it.
https://forums.wesnoth.org/download/file.php?id=80530

There is also a lack of explanations about units that advance further than lvl2. I mean, sure, it's not very likely to happen, but still...

I've noticed something about the warning regarding standing in shallow water. It is only triggered by 9 hexes. As long as I avoid those 9 hexes and instead only move in the other shallow water hexes, I won't be warned at all. 
https://forums.wesnoth.org/download/file.php?id=80532
There is also no warning about moving into swamps. (which should be added, right?)

**Comment by sevu** [comment]
>  How about making one more tutorial, one for Li'sar. As it is now, the tutorial is 'historically accurate' for Konrad, but absolutly not for Li'sar.

That's true. But the Tutorial scenario is taking care of many things, having two for female/male would just end up with having more bugs. If Li'sar's appearance is a problem, then it would be better to have some other female character take her place, maybe an elf. But that would probably mean that there would be need for new graphics, and the current ones are fine. I think there is no way to have both, history accurate and Li'sar without duplication of effort.

> Why give Konrad and Li'sar not the chance to level up

Keep it simple. There are enough other shiny things to the new players.

> And how about making the units they recruit, recalls in HttT (or reinforcements at some point)? :D That would be awesome.

Technically possible, but … how exactly?And wahat about Li'sar's units? you will fight against them? And at a point when you will have already really strong units, while she has the lv0 with maybe a few lvl1 from the turorial.
And, as for gameplay, level 1 units are generally not worth it.

> After your leader recruits (for the first time), ordering him to move to the village to heal, if he has enough moves left, would make sense.

Sounds valid, on the other hand he has been taught that part directly before recruiting, let's don't annoy the player with even more babbling…

> Levelling up a unit in the first tutorial part makes me miss out on the explanation of it.

Could you explain that happens, or what you miss out?

> There is also a lack of explanations about units that advance further than lvl2. I mean, sure, it's not very likely to happen, but still...

That's fine.

> I've noticed something about the warning regarding standing in shallow water. It is only triggered by 9 hexes. As long as I avoid those 9 hexes and instead only move in the other shallow water hexes, I won't be warned at all.

Should be changed… could you link to the code about which you talk?

**Comment by Konrad22** [comment]
In that case I'd prefer removing Li'sar as a choice. I like continuity. :)

With Li'sar removed, you could give the option of having those units either as your escort (in exchange for you having 0 gold and them having no mp in the first turn) or adding them to your recall list in Sc2 (and having normal gold in Sc1).
And I'm not really advocating this for gameplay reasons, but because I think that would be a neat and cool addition. ^^

When you advance a unit to lvl 2 in the 2nd part of the tutorial, it talka to you and gives you an explanation about advancement (and the unit in specific). If you advance a unit in the 1st part of the tutorial, there is no such explanation. If you recall this unit in the 2nd part, there won't be an explanation for this unit either. -> You miss out on the explanation.

https://github.com/wesnoth/wesnoth/blob/74d8cfa98e0f61ee22a536fc06c2019c9c89aede/data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg#L607 (I think that's the right one.)

**Comment by CelticMinstrel** [comment]
>I've had an idea! (no idea if it is any good)
> How about making one more tutorial, one for Li'sar. As it is now, the tutorial is 'historically accurate' for Konrad, but absolutly not for Li'sar.
> 
> New tutorial scenario(tree)
> Intro (choosing leader)
> 1a (Konrads training)
> 1b (Li'sars training)
> 2a
> 2b
> 
> Li'sars tutorial would be like a training session in the palace, under the care of Asheviere or her generals? ^^
> 
> Why give Konrad and Li'sar not the chance to level up? Is there any specific reason for that?
And how about making the units they recruit, recalls in HttT (or reinforcements at some point)? :D That would be awesome.

I don't think any of this has any merit, to be honest. The tutorial is absolutely not canon, and changing things to maintain continuity with HttT isn't a concern at all. If the continuity thing bugs you so much, it would be better to instead replace Konrad and Li'sar with more generic units.

> After your leader recruits (for the first time), ordering him to move to the village to heal, if he has enough moves left, would make sense.

Uh. Wasn't the leader ordered to the village _before_ recruiting?

> There is also a lack of explanations about units that advance further than lvl2. I mean, sure, it's not very likely to happen, but still...

I think this is so unlikely that it's not worth the effort.

> I've noticed something about the warning regarding standing in shallow water. It is only triggered by 9 hexes. As long as I avoid those 9 hexes and instead only move in the other shallow water hexes, I won't be warned at all.
https://forums.wesnoth.org/download/file.php?id=80532
There is also no warning about moving into swamps. (which should be added, right?)

It would be really easy to make the shallow water warning trigger the first time you move into _any_ shallow water hex, so I think that would be fine. I'm not sure if the swamp warning is worth it but I'm not opposed to it.

**Comment by Konrad22** [comment]
I think that the swamp warning would be worth it, because there is a swamp hex at the elvish side of the rivershore.

**Comment by Wedge009** [comment]
Personally I don't see a problem with having Li'sar as an option for the Tutorial. As celmin mentioned, the Tutorial isn't meant to be part of the 'real' story and having a male/female option - each being significant characters - is a nice introduction for new players, I feel. That said, I'm not against complementing or adding to the Tutorial a separate scenario for Li'sar that fits the 'real story' better but it doesn't seem necessary.

With respect to Konrad/Li'sar not getting enough experience for their next level - is this not possible in the second Tutorial scenario? As sevu mentioned, Tutorials are supposed to be simple to ease newcomers into the game-play mechanics. As long as regular units have a chance to gain a level, I think that suffices for teaching players the experience mechanics.

Regarding the terrain warning, I presume the trigger is on the presumed most obvious route to the enemy. As celmin mentioned it sounds like the trigger could be on specific terrain rather than specific hexes so this would be a fair improvement.

**Comment by nemaara** [comment]
I'm going to take care of this for 1.14.7. I'll do 3 things:

Allow Konrad and Li'sar to level up, I agree with wedge here in that there's no real reason not to (they're not really that different than other units). 

Fix the warning about water, remove swamp tiles from the map. 

Change the quintains in part 1 to level 0 so that it's impossible for your units to level up (fixes the what happens if you level up in part 1 thing). 

The others, I agree with what others have said and don't really think the suggested changes are desirable.

**Comment by CelticMinstrel** [comment]
I have no objections to Li'sar/Konrad being able to level up, but note that you're kinda encouraged not to take them to the battle, so I don't know how likely it is that you'd actually see them level up.

**Comment by Wedge009** [comment]
Thanks for the PR, nemaara. Looking over it I don't see anything out of place.

With respect to Konrad/Li'sar in the tutorials, if I recall correctly, the guide encourages the player to look after the leader - after all, dead leader almost always means game over - but also notes that during campaigns the leader is expected to gain experience too, so those objectives needs to be balanced against each other. I think it's fair to add them to the tutorial even if it's unlikely that a new player would managed to gain levels for them - the dialogue and unit descriptions (in nemaara's PR) look very similar to existing units.

**Comment by nemaara** [comment]
Yes, it's unlikely that the player would have leveled Konrad or Li'sar, but this is just in the case that they do put exp on them. The strategy discussion in the tutorial could be updated a little bit, my PR probably won't change anything about what currently exists regarding that.

**Comment by nemaara** [comment]
Closing since #3963 was merged.
