### ISSUE TITLE
SoF - Sc4, starting in a closed off cave

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3393]
So, I'm 'advancing' into troll territory, so I'd guess I'm walking though some tunnels to get there.
Alas, it's not true. I must have teleported with my dwarvish made castle and I landed in a cave with no access to any other cave. (No part of the map suggests that how I arrived there or that I can leave after mining. It's cutoff from everything.)
Maybe change it so it is more obvious how the dwarves arrived there?

**Comment by CelticMinstrel** [comment]
Like rough cave leading off the edge of the map, right?

**Comment by Konrad22** [comment]
Exactly. :)
