### ISSUE TITLE
SoF - Sc6, flimsy explanation for going into the cave

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3402]
Looking at the map, the way I came from is even worse guarded than the cave I'm trying to escape to. Maybe add a couple of elvish heroes at the tunnel I arrived from?

**Comment by stevecotton** [comment]
There's a large dialogue rewrite for the whole campaign, discussed in https://r.wesnoth.org/t36050 . But that ended with the person who was doing it having Real Life take over, and no-one taking up the task.

Konrad, you've logged many bugs, please would you consider taking over the task?

**Comment by Konrad22** [comment]
I'm sure that, if I even tried to, my real life would suffer a lot. And I wouldn't even do a good job at it.
I'll keep it in mind and hopefully come back to this task once I believe I can complete it.
