### ISSUE TITLE
SoF - Sc7, killing all Outriders chasing me doesn't mean I win

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3403]
Why not? Getting rid of them means I escaped, right? (You could add it as alternative scenario objective if there is no reason for this.)

**Comment by stevecotton** [comment]
A new set of riders (reinforcements) could spawn at the north edge of the map if more than a set number of riders are killed. They wouldn't catch up, but they're mean you'd have to keep riding south.

**Comment by Konrad22** [comment]
That would be a nice solution. :) Maybe when 4 have been killed? That way the reinforcements shouldn't be able to spawn more than once.
