### ISSUE TITLE
TSG - Sc8b, anticlimatic boss death

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3412]
Mal M'Brin is an ancient lich of great power who rose to get revenge on the humans. It doesn't sit well with me that he is dying so quietly...

**Comment by stevecotton** [comment]
He's only been a lich for a year.
https://github.com/wesnoth/wesnoth/blob/c2064827e4d65d819ee258ec40ef54b0c8875590/data/campaigns/The_South_Guard/scenarios/05_Choice_In_The_Fog.cfg#L510-L511

**Comment by Konrad22** [comment]
I was refering to his unit type though. :C

**Comment by Wedge009** [comment]
I think you're making too much of a link between lore and game-play again. While your attention to detail is admirable, I'm not so sure it's necessary to open a new request for every single issue you spot. I think some of these may be better directed to the campaign designers and/or maintainers on the forums.

**Comment by Konrad22** [comment]
Quite some of my created issues I've took from my posts in the campaign review/feedback section on the forums. And I guess that I'll condense some issues to some more posts on the forums as well, so they will be both here and there.

In this case I'm using lore to add to my argument. It would trouble me much less, if it wasn't so normal for most enemy leaders to say something when they are defeated, making Mal M'Brin the odd one. (In the elvish Branch he didn't die without saying anything either.)

**Comment by CelticMinstrel** [comment]
I do think it's weird to use the Ancient Lich unit type for a character who only recently became a lich, though. What's wrong with the regular lich?

**Comment by Wedge009** [comment]
Author wanted a challenge? Given what I remember of the campaign, I wouldn't be against downgrading M'brin to a regular Level 3 Lich.

**Comment by CelticMinstrel** [comment]
If you want him to be a bit tougher there's also the option of giving him one or more `{AMLA_DEFAULT}` right from the beginning.

**Comment by Konrad22** [comment]
I'd like to point out that he is a lvl 3 lich in the elvish branch. (This could be explained by him having time to achieve a breakthrough because he had more time to prepare (because they couldn't invade his base) or something..?)

**Comment by CelticMinstrel** [comment]
Well, a _minimum_ change might be to just create a unit using the Ancient Lich as the base unit but with a different name; that would solve the narrative weirdness without touching the mechanical side of things.

**Comment by nemaara** [comment]
Do these changes address this issue?

https://github.com/wesnoth/wesnoth/commit/051cec2de44e788f6f99cc93d10ec85e4d2fa910

https://github.com/wesnoth/wesnoth/pull/3597

**Comment by GregoryLundberg** [comment]
As I said over on the PR, I'm still not sure of Mebrin's motivation for becoming a Lich. It seems implausible that the bandits would have been able to overcome and kidnap him if he had already become a Lich, and it seems unlikely he would have become one simply due to their treatment of him.

That said, yes, I would be very glad to see the OP's reaction (on this and the related issues) to the recent changes which will appear in 1.14.6.

Celtic Minstrel's suggestion might be the best. Change him from a Lich to an evil mage having been driven mad by the bandits (probably on the way to becoming a Lich, but not there yet).

**Comment by GregoryLundberg** [comment]
I agree, it's quite improved.
