### ISSUE TITLE
Toggling fullscreen in story screen shows the map

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3421]
Run `./wesnoth -cHeir_To_The_Throne --campaign-difficulty=2 --campaign-scenario=01_The_Elves_Besieged`, wait for the story text to show and music to start, and press `Ctrl+F`. The titlescreen map will disappear for a moment and the main map (playfield) will be visible.

**Comment by Wedge009** [comment]
There are a lot of issues with resizing windows, particularly during a story page, I think this is another example of this.

**Comment by Wedge009** [comment]
With respect to the flickering/flashing aspect, I wonder if it's related to #2395.

**Comment by Wedge009** [comment]
Still present in 1.17.0+dev.

**Comment by Wedge009** [comment]
I just tested by starting HttT from in the game, no need to deal with command line arguments. It still occurs with 1.17.5+dev even after #6855, but the difference with the new draw implementation is that the game map is not rendered yet (since we are still in the story), just the UI elements such as the mini-map are visible.

**Comment by mesilliac** [comment]
Well there are still some issues with resizing, but at least this particular issue should be fixed by the referenced commit.

**Comment by CelticMinstrel** [comment]
Does that also prevent the map from drawing if the story screen is launched in the middle of a scenario?

**Comment by mesilliac** [comment]
Hmm, no. I assumed it has to be at the start, as it's hardcoded so in `playsingle_controller::play_scenario()`.

Is there a good example of a mid-scenario story screen i can test?

**Comment by CelticMinstrel** [comment]
Just in mainline, I see one is used in the final scenario of Descent into Darkness. That might be a touch difficult to trigger, but I imagine some debug commands can get you there, just not sure what they'd be.

That's the only instance I can find in mainline.

**Comment by mesilliac** [comment]
I managed to trigger it. It was broken in a different way, as buttons were showing on top of it. I'll add this fix to the story viewer so it works every time.

It might also be a good place to trigger screen fading, if i can get it to also fade the UI.
