### ISSUE TITLE
Show messages with options even during a replay

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3423]
I was just watching one of my replays and noticed that `[message]` tags that offer options seem to be skipped entirely. It would be better to either:

* Show them normally but disable changing the selection
* Concatenate the message text and the selected option text (as separate paragraphs), probably with some special styling on the latter, and show that as a regular message.

I don't know about others, but I include parts of the dialogue in these messages, both in the main text and in the option text, so without them the dialogue no longer makes sense.

**Comment by shikadiqueen** [comment]
I didn't even know there were situations where messages would be skipped in replays. Displaying them with the selection clearly locked in some way seems like the most intuitive option to me.

**Comment by CelticMinstrel** [comment]
I didn't know either, but for example, the message asking if I want to take the storm trident was very clearly missing - it skipped straight to the storm trident popup box.

**Comment by jostephd** [comment]
Dup of #1834?

**Comment by ProditorMagnus** [comment]
Similar #3253

**Comment by CelticMinstrel** [comment]
Ooh, you're right, this is a duplicate of #1834 - thanks for spotting that!
