### ISSUE TITLE
Assertion failure when attacking

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3424]
If you attempt to attack with a unit whose attacks all have `attack_weight=0`, there is an assertion failure in the GUI2 listbox. I haven't tested but it might also apply if the unit's attacks all have an active `[disabled]` weapon special.

**Comment by jostephd** [comment]
#3424

**Comment by vgaming** [comment]
@jostephd you're referencing the very same issue we're now in.

**Comment by jostephd** [comment]
Whoops. Fixed.

**Comment by CelticMinstrel** [comment]
Wow that was fast! \o/
