### ISSUE TITLE
Add-on manager closes and error message is displayed

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3426]
While having opened the description of an add-on, I used 'update all' to, well, update some add-ons. (I'm pretty sure that it's possible to reproduce the bug this way.) Which led to the situation on the screenshot. (I somehow do remember this bug so this might be a duplicate issue.)
![addon](https://user-images.githubusercontent.com/39015360/43642909-94cd7744-9729-11e8-8511-99bafa97c8cc.png)

**Comment by Konrad22** [comment]
#3059 duplicating myself. xD

**Comment by CelticMinstrel** [comment]
Someone please mark this as duplicate, I can't right now.
