### ISSUE TITLE
Lua CVE tests break pot-update

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#3436]
$ git checkout --detach origin/1.14
HEAD is now at 7e8088f801 updated Chinese (Traditional) translation (changelog)
$ scons pot-update
...
error: data/test/scenarios/test_cve_2018_1999023_2.cfg:4: UTF-8 Format error.
Can't decode byte 0x93 (invalid start byte).

**Comment by CelticMinstrel** [comment]
Is that file perhaps using "UTF-8 with BOM"?

**Comment by CelticMinstrel** [comment]
A better fix is probably to change the file extension.

**Comment by jyrkive** [comment]
I also considered changing the extension. However, I found out that only files with the .cfg extension can be loaded as unit tests.
