### ISSUE TITLE
fatal error: boost/test/detail/unit_test_parameters.hpp: No such file or directory

### ISSUE THREAD

**Issue by kingbeowulf** [wesnoth/wesnoth#3442]
When compiling with 'scons all' the following error occurs: 

```
src/tests/main.cpp:31:54: fatal error: boost/test/detail/unit_test_parameters.hpp: No such file or directory
compilation terminated.
scons: *** [build/release/tests/main.o] Error 1
scons: building terminated because of errors.
```

The issue appears to be the src/tests/main.cpp selecting the wrong boost test subdirectory:

```
#if BOOST_VERSION >= 106000
#include <boost/test/unit_test_parameters.hpp>
#else
#include <boost/test/detail/unit_test_parameters.hpp>
#endif
```

Slackware64 14.2
boost-1.59.0
wesnoth-1.14.4

**Comment by Wedge009** [comment]
I don't know the history behind this but it looks like boost/test/unit_test_parameters.hpp is available from boost 1.59 onwards, rather than 1.60+ as implied by the preprocessor if statement.

**Comment by kingbeowulf** [comment]
Well, boost-1.59 doesn't have a "boost/test/detail/" so the issue is with wesnoth using the wrong condition statement, not boost.  The workaround was to omit the tests.  

I maintain the wesnoth buildscript on Slackbuilds.org and, per SBo policy, can't required newer libs of those included in the stable release of Slackware 14.2.

**Comment by jostephd** [comment]
Does it build if you change the condition to `#if BOOST_VERSION >= 105900`?

**Comment by kingbeowulf** [comment]
Yes, 'scons all' builds fine with the attached patch, and 'scons wesnoth wesnothd campaignd' isn't effected by this issue.

`--- wesnoth-1.14.4/src/tests/main.cpp.old	2018-07-22 04:40:33.000000000 -0700
+++ wesnoth-1.14.4/src/tests/main.cpp	2018-08-11 19:43:27.688965301 -0700
@@ -25,7 +25,7 @@
 
 #include <boost/test/unit_test.hpp>
 #include <boost/test/unit_test_monitor.hpp>
-#if BOOST_VERSION >= 106000
+#if BOOST_VERSION >= 105900
 #include <boost/test/unit_test_parameters.hpp>
 #else
 #include <boost/test/detail/unit_test_parameters.hpp>`
