### ISSUE TITLE
Redundant duplicated strings in top bar (ingame)

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#3445]
Example:
Here is string `gold` with down-case **g**
https://github.com/wesnoth/wesnoth/blob/f12835140421a64a559b1f7beced5fc13aea325c/data/themes/default.cfg#L177

And here is same word with same meaning for tooltip for same object defined uppercase:
https://github.com/wesnoth/wesnoth/blob/f12835140421a64a559b1f7beced5fc13aea325c/src/reports.cpp#L1264

## Solution:
Make affected strings in theme cfg files uppercased

**Comment by jyrkive** [comment]
I think it's better to keep them separate. Keeping the casing consistent would also force the game to display both strings with the same casing.
