### ISSUE TITLE
game gets stuck at 'getting game' when observing certain games.

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3454]
as said in the title i often get stuck at 'gettign game' in the loadingscreen when observing certain games. 
It clearly effect some maps (for example 'Isars cross', 'Colloseum 3p', "Orcia") more often than others ( for example 'world conquest 2', 'Afterlife') but i was not able to reprpduce this with a game that i sated by myself with a secodn client. shadowm also reproduced this and got this serversides errorlog:

```
20180811 21:13:38 info server: xxx.xxx.xxx.xxx  ShikadiQueen    joined game:    "Isar" (567) as an observer. (socket: 0x55adb79e5620)
20180811 21:13:38 error config: attributes: 'user_team
faction_name' < 'fog'
20180811 21:13:38 error config: ERROR: 'attributes not in order'
20180811 21:13:38 warning config: async_send_doc: simple_wml error: attributes not in order
 
[...]
 
20180811 21:14:10 info server: xxx.xxx.xxx.xxx  ShikadiQueen    joined game:    "Isar" (567) as an observer. (socket: 0x55adb70e05b0)
20180811 21:14:10 error config: attributes: 'user_team
faction_name' < 'fog'
20180811 21:14:10 error config: ERROR: 'attributes not in order'
20180811 21:14:10 warning config: async_send_doc: simple_wml error: attributes not in order
```

when observing game, the node ctor (where that erro comes from) in in particular called by simepl_wml::document::clone() which is used when resending the game wml to the observer (see this strachtrace of an older bug that is already fixed https://pastebin.com/DkkawKhe ). I suspect that this is caused by my recent 'make simple_wml handle translatable strings' commit, so we will have to revert that if we cannot fix it soon, still even with it reverted i'd be of course nice to have this one fixed properly so that we can reapply it (to make the simple_wml be able to handle translatable strings again)

This comment saiy it happens when observering but that does nto mean that it does not happen when joining i just currently oserver more than i play so i probably wouldnt have noticed if it also happens when joining.

**Comment by gfgtdf** [comment]
ok it seems like it also effects players that try to join the game:

![grafik](https://user-images.githubusercontent.com/4893136/43996638-48ba7312-9dc7-11e8-89a2-1d2abaf95ff0.png)

**Comment by gfgtdf** [comment]
ok i after reverting the other commit this is no longer 'urgent'

**Comment by Pentarctagon** [comment]
Closing since, well, it no longer happens since the commit that caused it was reverted.
