### ISSUE TITLE
--skip-story option

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3472]
When debugging a scenario I launch it directly using `wesnoth --campaign-scenario`. I'd like to be able to run `wesnoth --campaign-scenario=foo --skip-story` to not show the `[story]` screens and skip directly to the scenario.

If possible, also skip non-interactive parts of prestart and start events, for example, the starting dialog and "move screen to signpost" in HttT S1.

**Comment by jostephd** [comment]
#3528

**Comment by loonycyborg** [comment]
Above-mentioned PR merged in https://github.com/wesnoth/wesnoth/commit/faf167a253db9a1e7f8eadc1bc8c1bcb928789ce
