### ISSUE TITLE
GUI.pyw directory selector starts in the Wesnoth data directory instead of the userdata directory

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3480]
It would be a lot easier to find my add-on if the initially-chosen directory was the userdata directory.

**Comment by Elvish-Hunter** [comment]
This is indeed the supposed behaviour. What OS are you on? Are you using a custom userdata directory?

**Comment by CelticMinstrel** [comment]
I'm on Windows, using a non-Steam build. I'm not using a custom userdata directory.

**Comment by Elvish-Hunter** [comment]
On Windows, the script builds the userdata path with this block (WESNOTH_SERIES is a string constant defined at the start of the script and for the current stable series is equal to 1.14):

        userdata=os.path.join(os.path.expanduser("~"),
                              "Documents",
                              "My Games",
                              "Wesnoth"+WESNOTH_SERIES,
                              "data",
                              "add-ons")

Can you send me (even through a forum PM or on IRC) the path of your userdata directory?

**Comment by CelticMinstrel** [comment]
I just checked what Python returns from `os.path.expanduser("~")` and discovered that it's not the correct prefix for my userdata directory (it returns a C drive path but my data is on D drive). So I guess this isn't a problem with wmlxgettext after all.

**Comment by jostephd** [comment]
For that it just needs to run `wesnoth --userdata-path`.
