### ISSUE TITLE
Regression: can't undo two moves in a row

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3486]
Start HttT. Move Delfador. Move Konrad. Press 'u' twice. The second press does nothing. Bisected to f0ffb458f2ee516b5c73bb44935df459aa02dfe7.

**Comment by gfgtdf** [comment]
fixed

**Comment by CelticMinstrel** [comment]
Uhhh, if it's fixed, close it?

**Comment by gfgtdf** [comment]
fix isn't on master yet.

**Comment by sevu** [comment]
It's on master by now
