### ISSUE TITLE
update pofix

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3487]
Some changes of #3377 may deserve a pofix entry.

**Comment by jostephd** [comment]
Here you go - https://github.com/wesnoth/wesnoth/pull/3490

**Comment by sevu** [comment]
I didn't expect that!
But more of them would fit there – basically anything which does not change the sense.
The ones form AOI, maybe the one from Kalenz where the sentence is split, but not the other one of the person speaking to him, …

Pinging @shikadiqueen as I didn't work with pofix before.

**Comment by jostephd** [comment]
Glad to have been a surprise :) Added one from AOI and Li'sar's description. Any others?

**Comment by jyrkive** [comment]
#3490 merged, resolving this issue.
