### ISSUE TITLE
Add-on manager: first scale icons (down), then blit

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3488]
Currently it's the other way round.
![png](https://user-images.githubusercontent.com/21158813/44469085-fe498800-a626-11e8-9325-3f81b28ce39e.png)

**Comment by Wedge009** [comment]
Is the symptom that the green + signs are different sizes?

Also what version is this? I don't see green + signs at all, or is that a view only publishers see?

**Comment by sevu** [comment]
Thanks for digging this out. It's working like you say, and it's fixed.
