### ISSUE TITLE
reconsider naming scheme of the nightblade image files

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3498]
Orcish nightblades have been mainlined in 1.13.
The assassins in UtBS use the same images, but by having a copy of them in the campaign, with the same path but a slightly different naming scheme.

E.g.:
Core:  nightblade-attack-se1.png
UtBS: nightblade-attack-se-1.png

Giving them the same scheme allows to remove the copies of the files in 1.15.

Edit: Depending on the final scheme, the WML could already in 1.14 be changed to point to the core files.

**Comment by nemaara** [comment]
See https://github.com/wesnoth/wesnoth/compare/141469deec4a...49eab2867d50.
