### ISSUE TITLE
Proposed text improvements for The South Guard

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3499]
Document from German translator for TSG, Chewan:
[TSG.pdf](https://github.com/wesnoth/wesnoth/files/2322246/TSG.pdf)

Needs to be committed and reviewed by a native speaker.

(submerging rangers & missing female strings have already been changed)

**Comment by nemaara** [comment]
Should be taken care of by this:

https://github.com/wesnoth/wesnoth/commit/051cec2de44e788f6f99cc93d10ec85e4d2fa910

**Comment by Pentarctagon** [comment]
https://github.com/wesnoth/wesnoth/pull/3597
