### ISSUE TITLE
Units' haloes are not removed on death after an animation is played

### ISSUE THREAD

**Issue by DisherProject** [wesnoth/wesnoth#3509]
I'm playing Wesnoth 1.14.4 on Windows 10

To reproduce:
1) Start "The hammer of Thursagan"
2) Jump to the 9th scenario "Forbidden Forest" by typing `:debug` and `:choose_level`
3) Create a Mage of Light (`shift + C`) next to the temple in the middle of the map
4) Move him on it to let him take the staff
5) Kill the mage (`shift + K`)

The mage's halo will remain where it is. Reloading the map will remove it.

Another way to reproduce this bug is the one that follows:
1) Download this version of the Caves of the Basilisk and replace it with the original one (i've added some events at the end of the file)
[2p_Caves_of_the_Basilisk.zip](https://github.com/wesnoth/wesnoth/files/2333536/2p_Caves_of_the_Basilisk.zip)
2) Start the Caves of the Basilisk
3) Move your Mage of Light on the signpost
4) Do whatever you want with him (attack someone, move him...) then kill him

His halo won't be undrawn. You can try with other units with haloes, like Elvish Shydes: the result will be the same

**Comment by newfrenchy83** [comment]
I am post an PR for tesolve this.
