### ISSUE TITLE
Random start time option does not work

### ISSUE THREAD

**Issue by betrok** [wesnoth/wesnoth#3515]
MP scenarios seem to always start at dawn regardless this setting.

**Comment by gfgtdf** [comment]
hm yes known issue, seems like we forgot it


> heh turned out this happens really randomly, random gnerator has some high chance to produce an invalid number in which case the code jsut set it to the first start time.

**Comment by vgaming** [comment]
@jyrkive thanks! Is the fix OOS-safe? Can I re-compile and start playing online with the newer version?
