### ISSUE TITLE
move wmlxgettext to data/tools

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3517]
There was a consensus of moving it there, part of the reason being that GUI.pyw has an UI for it, but the utils directory is not shipped on comparison to the data/tools directory

**Comment by CelticMinstrel** [comment]
Do you mean move to data/tools?

**Comment by sevu** [comment]
…yes :(

**Comment by CelticMinstrel** [comment]
Done in 1f4f1a366f4 and 59e78e55659. Let me know if I missed something.
