### ISSUE TITLE
backport wmlxgettext pr

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3539]
#3481 (the fix for #3469) has only been merged into master

**Comment by CelticMinstrel** [comment]
Oh, is it possible to do that before the next release, at least? I'm not sure if that would violate the string freeze.

**Comment by sevu** [comment]
It doesn't contain translatable strings.

I saw this while I cleaned up my stash and was surprised that I had not gotten a merge conflict earlier.

Now looking at the PR, I should have just cherry-picked it directly instead to open an issue ^^

**Comment by CelticMinstrel** [comment]
Well, I think it could only violate the string freeze if we needed to do another pot-update for some reason... which is pretty unlikely anyway, so it's probably fine.
