### ISSUE TITLE
TSG S2: players should not be able to ignore objectives

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3540]
It is possible to ignore the objectives telling that Deoran should go to the town centre and take his post of command. Instead one can go after the bandit leader and kill him.
This is actually easier, because the bandits gain the ability to recruit undead when Deoran arrives in the city.

A commander who fights bandits in the forests while they burn down the town (-> story text) would not stay a commander for long.

Different approaches are possible to change this, be it by forcing the player to send Deoran to the town or to make the events not depend on Deoran arriving there.

**Comment by GregoryLundberg** [comment]
I thought I tested it and had Hylas come out, talk, but avoid mentioning undead. My main concern, though was NPC consistency from scene to scene and dialog consistency with what was seen (or not seen). I didn't really care that the Player ignored directions, only that you didn't have situations where a critical NPC was not present, either crashing a future scene or rendering it unplayable.

**Comment by sevu** [comment]
It works flawless, I also added a bit additional handling for this situation.
I saw a lot of your changes, sounds like TSG was somewhat broken before.

Someone told me that it is easier, so… hmm I thought maybe to do something about it.
What came to mind so far was about using [fire_event], and having an alternative trigger for switching to undead recruits, like … turn 12 or 15. On the other hand, it also looks good with just defeating bandits.

The other thing about this scenario was that it should maybe have 1 or 2 burned houses, as the text mentions something about the burning town.

**Comment by GregoryLundberg** [comment]
Ping to @nemaara concerning the burned houses comment since he's presently reworking the maps.

**Comment by nemaara** [comment]
Westin does now have some "ruined" city houses, if that's sufficient.

**Comment by nemaara** [comment]
My new TSG PR (https://github.com/wesnoth/wesnoth/pull/3648) should now address this. It's no longer possible to win without moving Deoran to the keep.
