### ISSUE TITLE
comparing tstring to a string crashes the game.

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3541]
reproduced on 1.14.4, comparing tstring lua userdata to a lua string crashes the game. `_("a") < "a"`

**Comment by gfgtdf** [comment]
fixed by https://github.com/wesnoth/wesnoth/commit/71a6f62e5615cd272fc89373d0452b3b069efd0a seems liek i forgot the `#` in the commit message

**Comment by CelticMinstrel** [comment]
I closed this since gfgtdf said it was fixed, but then noticed it was only fixed on 1.14, so reopening until it's forward-ported.

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/commit/69cdbe8da76e37d4bb827dad97ce99d4ef16cde2
