### ISSUE TITLE
observer icon at wrong location

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3543]
As seen in the screenshot the observer icon (the eye) is too much towards the right and hidden behind the minimap. Reproduced on 1.14.4+dev

![grafik](https://user-images.githubusercontent.com/4893136/45423326-47738180-b693-11e8-8b27-1c407aebee10.png)

**Comment by jostephd** [comment]
Fixed on 1.14. The battery code hasn't been backported to master yet.
