### ISSUE TITLE
Load Game Dialogue: Difficulty may take up too much space

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3548]
I think there was in the recent time a PR which changed sth.
The campaign difficulty is shown twice, once with the version for the campaign, and once with a general wording.
![difficulty](https://user-images.githubusercontent.com/21158813/45488261-211c1780-b761-11e8-879b-6fb9d07427a5.png)

**Comment by jyrkive** [comment]
@jostephd Do you have ideas about what to do here?

**Comment by jyrkive** [comment]
Hmm... thinking about it, I think the current situation isn't _bad_. The mere existence of a scrollbar isn't really a big problem. I think we could just leave it there.

**Comment by jostephd** [comment]
The label _does_ to have a capped width:
![screenshot_2018-09-14_16-27-17](https://user-images.githubusercontent.com/24784687/45562872-29488580-b83b-11e8-8864-65f2dc3001af.png)

I think the scrollbar is just a coincidence because the German line happens to be just under the maximum width for the label - close enough that it exceeds the width when padding is added or something.

**Comment by Wedge009** [comment]
This looks very similar to #1665, which itself is related to a lot of other similar 'scroll bar' issues (like #2006).

**Comment by CelticMinstrel** [comment]
I don't think it makes sense to move "Difficulty" to a tooltip.

**Comment by Wedge009** [comment]
The situation has improved to the point where I closed #2006, but I do notice the scroll bar in the map preview section when using German. Back to the original report, sevu mentions difficulty is displayed twice... but I don't actually see it twice (I'm not a German speaker).

**Comment by Wedge009** [comment]
@Vultraz has updated the Load Game dialogue in master (I tested at 1.17.2+dev 65d8c201a5d). Unfortunately, testing German, the scroll bar still appears on the map preview panel. Presumably there was no change to the panel itself, just that it was moved to the right side of the dialogue along with the other revisions made to it.

**Comment by Wedge009** [comment]
I can't replicate this in master (1.19) after 5e3a86f7abbfcb48d4c55f4e275fe81fc4a0372a.
