### ISSUE TITLE
object is applied to unit twice (same id)

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#3549]
Steps to repro:

* start a new game
* enter debug mode (:debug), enter Lua console (`)
* execute this:
```
unit = wesnoth.get_units {side = 1}[1]
wesnoth.add_modification(unit, "object", {
	id = "test",
	T.effect {
		apply_to = "movement",
		increase = "1",
	},
})
wesnoth.add_modification(unit, "object", {
	id = "test",
	T.effect {
		apply_to = "movement",
		increase = "1",
	},
})
```
As you can see, the same unit is given an object with the same id twice.

Expected: As per documentation, object should be applied exactly once.

Actually observed: The object is applied twice.

**Comment by jyrkive** [comment]
Where is it documented that there can't be multiple modifications with the same ID? I didn't find anything in https://wiki.wesnoth.org/LuaWML/Units#wesnoth.add_modification or https://wiki.wesnoth.org/EffectWML

**Comment by jyrkive** [comment]
Yeah, this isn't a bug. `[object]` in WML can only be picked up once per ID, but `wesnoth.add_modification()` doesn't have the same restriction.

**Comment by vgaming** [comment]
@jyrkive how is it possible to guess that `wesnoth.add_modification` DOES apply the "object" twice? After all, it says "object", not something else! And "object"-s documentation regarding id-s is pretty clear.

**Comment by vgaming** [comment]
@jyrkive note theat the "effect" WML is irrelevant since it's only a subtag. The main tag is, as most readers will I think assume, "object" (thus [object]).

**Comment by vgaming** [comment]
Also, since you say neither of the behaviors is documented explicitly by now, should we change the behavior to only allowing one "object" with the same id be applied to a unit?

**Comment by jyrkive** [comment]
The "once per ID" restriction is a part of the implementation of the `[object]` tag. You are *not* using the `[object]` tag directly, but the underlying lower-level function.

https://github.com/wesnoth/wesnoth/blob/8dc604d4c8a2e7c58cce92cbffbacca2d7a04d15/data/lua/wml/object.lua#L11-L15

**Comment by jyrkive** [comment]
Also, in this case `[effect]` is the subtag you're using. Note that your code says `T.effect`.

**Comment by vgaming** [comment]
@jyrkive the effect is a subtag simply because I can use many of them with one unit modification, so clearly it's not the wrapper thing. The constraint I would like to have is at "object" level, not per-effect.

**Comment by vgaming** [comment]
@jyrkive I am well aware that I'm not using [object] directly. I ask, however, if we should change `wesnoth.add_modification` behavior to match this of [object].
Breaking user expectations so hard was the reason I marked this issue as "bug", but to stay productive, let's put the "bug or not bug" question aside and focus one one question. Should "add_modification" functionality match this of [object] ?

**Comment by jyrkive** [comment]
Changing the behavior of `wesnoth.add_modification()` would be a backwards-incompatible change. In addition, it needs an override; even with `[object]` you can set `take_only_once=no`.

It might be done for 1.15 if the UMC community at large believes that it would be an improvement.

**Comment by CelticMinstrel** [comment]
Note that any changes to `add_modification` could also affect traits and AMLAs; that would need to be taken into account before changing anything.

I'm not sure whether it _should_ check for an ID. An alternative might be adding some way for the Lua code to explicitly test if an object with the ID already exists before adding the duplicate. (Actually that way probably already exists, but maybe an easier way could be added.)

**Comment by vgaming** [comment]
@CelticMinstrel such an API would definitely be useful for me personally at least. Currently I work-around the problem by just setting a specific variable of a unit, e.g.  `unit.variables.creepwars_has_abc = true`

**Comment by gfgtdf** [comment]
@vgaming : note that the cfg.take_only_once =yes function just prevents the object to applies twice withon one scenario. unrelated to the unit. So two differnt unit cannot get the same object in one scenario scenario but in the next scenario that id is 'free' again.

**Comment by vgaming** [comment]
@gfgtdf ah you're right, not the best example. Let's skip this "work-around" then, because it's for a different goal.
