### ISSUE TITLE
CMake doesn't correctly find libcrypto

### ISSUE THREAD

**Issue by timothyqiu** [wesnoth/wesnoth#3557]
When building `b8d8be3` with CMake 3.12.2 on macOS, I got the following error:

> [  0%] Building CXX object src/CMakeFiles/wesnoth-core.dir/hash.cpp.o
> /path/to/wesnoth/root/src/hash.cpp:25:10: fatal error: 'openssl/sha.h' file not found
> #include <openssl/sha.h>
>          ^~~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [src/CMakeFiles/wesnoth-core.dir/hash.cpp.o] Error 1
> make[1]: *** [src/CMakeFiles/wesnoth-core.dir/all] Error 2
> make: *** [all] Error 2

---

The OpenSSL library is installed via Homebrew. Because “Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries”, the homebrewed OpenSSL is not symlinked to `/usr/local`, resulting a non-standard prefix `/usr/local/Cellar/openssl/1.0.2p`. Thus, vanilla `cmake /path/to/wesnoth/root` produces the following error:

> CMake Error at cmake/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find Crypto (missing: CRYPTO_INCLUDE_DIR) (Required is at least
>   version "1.0")
> Call Stack (most recent call first):
>   cmake/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   cmake/FindCrypto.cmake:9 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:71 (find_package)

So I followed the message and set `CRYPTO_INCLUDE_DIR`.

> cmake /path/to/wesnoth/root -DCRYPTO_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2p/include

This successfully generates Makefile, but `make` will produce the “`openssl/sha.h` not found” error shown in the beginning.  Running `make VERBOSE=1` shows that the custom OpenSSL include directory is not honored:

> [  0%] Building CXX object src/CMakeFiles/wesnoth-core.dir/hash.cpp.o
> cd /tmp/wesnoth-build/src && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DFIFODIR=\"/var/run/wesnothd\" -DHAS_RELATIVE_LOCALEDIR=1 -DHAVE_CONFIG_H -DHAVE_FRIBIDI -DLOCALEDIR=\"translations\" -DLUA_USE_POSIX -DWESNOTH_PATH=\"/usr/local/share/wesnoth\" -I/path/to/wesnoth/root/src -I/tmp/wesnoth-build/src -isystem /usr/local/Cellar/fontconfig/2.13.1/include -isystem /usr/local/opt/freetype/include/freetype2 -isystem /usr/local/Cellar/pango/1.42.4/include/pango-1.0 -isystem /usr/local/Cellar/harfbuzz/1.9.0/include/harfbuzz -isystem /usr/local/Cellar/graphite2/1.3.12/include -isystem /usr/local/Cellar/fribidi/1.0.5/include/fribidi -isystem /usr/local/Cellar/cairo/1.14.12/include/cairo -isystem /usr/local/Cellar/glib/2.58.0_1/include/glib-2.0 -isystem /usr/local/Cellar/glib/2.58.0_1/lib/glib-2.0/include -isystem /usr/local/opt/gettext/include -isystem /usr/local/Cellar/pcre/8.42/include -isystem /usr/local/Cellar/pixman/0.34.0_1/include/pixman-1 -isystem /usr/local/Cellar/libpng/1.6.35/include/libpng16 -isystem /usr/local/include -isystem /usr/local/include/SDL2  -std=c++14 -Wall -Wextra -Werror=non-virtual-dtor -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wold-style-cast -Wtrampolines -Qunused-arguments -Wno-unknown-warning-option -Wmismatched-tags -Wno-conditional-uninitialized  -fPIE -fstack-protector-strong -O3     -I/usr/local/include/SDL2 -D_THREAD_SAFE -o CMakeFiles/wesnoth-core.dir/hash.cpp.o -c /path/to/wesnoth/root/src/hash.cpp

---

https://github.com/wesnoth/wesnoth/blob/b8d8be3436dc415a5f8ad924599bfa67bbd51743/cmake/FindCrypto.cmake#L3-L5

I read the `FindCrypto.cmake` script and find that

1. `CRYPTO_INCLUDE_DIR` seems not used anywhere else in the project.
2. `CRYPTO_INCLUDE_DIR` and `CRYPTO_LIBRARY` are not related. Which, in my case, results in pointing to two different libraries. (`CRYPTO_INCLUDE_DIR` points to the homebrewed OpenSSL include directory I specified on the command line; `CRYPTO_LIBRARY` points to the shared library `/usr/lib/libcrypto.dylib` provided by macOS itself.)

The Travis build “cheated” by setting the flags manually in the script:

https://github.com/wesnoth/wesnoth/blob/b8d8be3436dc415a5f8ad924599bfa67bbd51743/utils/travis/steps/install.sh#L21-L31

The `/usr/local/opt/openssl` in the script is a symlink to `/usr/local/Cellar/openssl/VERSION` above.

**Comment by singalen** [comment]
@timothyqiu, can you please try adding this:

```
if(CRYPTO_INCLUDE_DIR)
	include_directories(SYSTEM ${CRYPTO_INCLUDE_DIR} )
endif()
```
to `src/CMakeLists.txt`, in line 43, right after `if(ZLIB_INCLUDE_DIR) ... endif()`?

**Comment by timothyqiu** [comment]
@singalen, it compiles successfully after adding those lines.

But the shared library is still the system one instead of the Homebrew one. (With `-DCRYPTO_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2p/include` the correct shared library should be `/usr/local/Cellar/openssl/1.0.2p/lib/libcrypto.dylib`, but `/usr/lib/libcrypto.dylib` was chosen.)

**Comment by singalen** [comment]
OK, one part done.

Second part will require packaging the dynamic library with Wesnoth.

It doesn't look like Wesnoth CMake build copies dynamic libraries over at all, and frankly, it shouldn't, but OpenSSL is a special case. We'll have to, and to use `install_name_tool` to [edit the library paths afterwards](https://stackoverflow.com/questions/13656033/how-do-you-add-an-rpath-to-an-executable-in-cmake-on-build-not-install-on-osx)... let me figure this out. I'm also affected by OpenSSL 1.1 migration.

**Comment by GregoryLundberg** [comment]
Have you considered using the new Apple replacement for OpenSSL and providing Apple-only shims (if needed) to marshal the two or three functions we use over to their stock library?

**Comment by singalen** [comment]
In fact, I have already done it for iOS version.

Porting it to Mac version should probably be easier than maintaining two different solutions.

**Comment by singalen** [comment]
...done.
@timothyqiu, can yo please try it?

**Comment by timothyqiu** [comment]
@singalen, it compiles and links to the Security framework 😄
