### ISSUE TITLE
discrepancy with error messages from addons.wesnoth.org between 1.12.x and 1.14.x

### ISSUE THREAD

**Issue by Can-nedFood** [wesnoth/wesnoth#3567]
The trouble was caused by some filenames in which I forgot to change the 0x20s to something else.  Making those changes allowed me to upload successfully.

However, I noticed that the server only returned a complaint when I attempted to upload to `--port '1.12.x'` — see below:

Here, I am attempting to upload to `--port 1.14.x`

    ?  ./Proto_1-15-0-“dev”_src/data/tools/wesnoth_addon_manager --upload Proto\ add-ons\ /skirmishes_XVIIthCenturyEEAW_many --address addons.wesnoth.org --port '1.14.x' --verbose
    Opening socket to addons.wesnoth.org:15014 for 1.14.x
    Connected as 42.
    Adding directory Proto add-ons /skirmishes_XVIIthCenturyEEAW_many as skirmishes_XVIIthCenturyEEAW_many.
    ('Ignored dir', 'private')
    ('Ignored file', '_server.ign')
    ('Ignored file', 'server-pbl_nugget')
    ('Ignored file', '_server.pbl')
    Closing socket.

Here, I am attempting to upload to `--port 1.12.x`

    ?  ./Proto_1-15-0-“dev”_src/data/tools/wesnoth_addon_manager --upload Proto\ add-ons\ /skirmishes_XVIIthCenturyEEAW_many --address addons.wesnoth.org --port '1.12.x' --verbose
    Opening socket to addons.wesnoth.org:15007 for 1.12.x
    Connected as 904.
    Adding directory Proto add-ons /skirmishes_XVIIthCenturyEEAW_many as skirmishes_XVIIthCenturyEEAW_many.
    ('Ignored dir', 'private')
    ('Ignored file', '_server.ign')
    ('Ignored file', 'server-pbl_nugget')
    ('Ignored file', '_server.pbl')
    Receiving 159 bytes.
    Received 159 bytes.
    159/159
    Add-on rejected: The add-on contains an illegal file or directory name. File or directory names may not contain whitespace or any of the following characters: '/ \ : ~'
    Closing socket.

**Comment by soliton-** [comment]
What is not mentioned is that the upload still failed for 1.14 but the error was not displayed.

The log file contains this:
> 20180918 21:01:24 error config: ERROR: 'did not find newline after end of attribute'
> 20180918 21:01:24 warning config: async_send_doc: simple_wml error: did not find newline after end of attribute

Seems like the error was not sent out because of this.
