### ISSUE TITLE
Error when try to compile Wesnoth in Xcode

### ISSUE THREAD

**Issue by macabeus** [wesnoth/wesnoth#3574]
I'm trying to compile using Xcode in a macOS High Sierra, using Xcode 9 or 10. I already installed some dependencies, like `boost` and `sdl2`, and I can compile `liblua`, but when I try to compile `Wesnoth`, I receive many errors messages like:

```
No member named 'memcpy' in namespace 'std::__1'; did you mean simply 'memcpy'?
```

![image](https://user-images.githubusercontent.com/9501115/45931787-39eab100-bf49-11e8-8a33-296900b2c5a7.png)

How to fix it?

**Comment by Pentarctagon** [comment]
Did you follow the instructions [here](https://github.com/wesnoth/wesnoth/tree/master/projectfiles/Xcode#step-by-step-building)?  Particularly step 3?

**Comment by GregoryLundberg** [comment]
My macOS box is down awaiting an upgrade so I can't test right now. But the documented procedures worked for me when I followed them on a freshly installled macOS when last I checked, several months ago. And, yes, I checked skipping steps and failing to follow the procedures produced messages such as your reported.

I'm going to close this as 'Works for Me'. If you still have an issue and can provide a bit more information, feel free to Reopen it with a followup.
