### ISSUE TITLE
Mission "Ur-Thorodor" shows unintuitive black screen at the end

### ISSUE THREAD

**Issue by fancywriter** [wesnoth/wesnoth#3575]
The mission of campaign "Delfador's Memoirs" just hangs after I try to finish it... Delfador goes to the meditation and I see black screen instead of game map.
Version 1.14.5
See nothing useful in stdout/stderr. :-(

Attaching savefile, just move Delfador to the "castle" to reproduce.
[МД-Ур-Фородор-Автосохр7.gz](https://github.com/wesnoth/wesnoth/files/2409077/-.-.-.7.gz)
![screenshot_20180923_204904](https://user-images.githubusercontent.com/1200256/45932330-5f3fe500-bf72-11e8-909a-a7b04f4fe8a7.png)

**Comment by DisherProject** [comment]
Did you try pressing the "End Scenario"/"End turn" button on the bottom of the side panel? Afaik, this behaviour is expected.
Anyway, we could set `linger_mode` to `no` in order to avoid any doubt.

**Comment by fancywriter** [comment]
@DisherProject - oh, right - this makes sense 🤦‍♂️ I see this button on the screenshot now - didn't notice it yesterday.
I would just expect to see something else, not black screen - some sort of text message at the centre with the meaning of "scenario is finished", like in other scenarios...

Will try to finish it manually today and will close this issue if everything is fine.

**Comment by DisherProject** [comment]
> oh, right - this makes sense 🤦‍♂️ I see this button on the screenshot now - didn't notice it yesterday. I would just expect to see something else, not black screen

Don't worry xD thank you for your feedback anyway: as you say, this scenario ends in an unexpected way, so it should be improved.

**Comment by GregoryLundberg** [comment]
Hey, I spent a couple hours figuring out why there were stray pixels and ghosts on that screen and getting it totally black. Used to be it looked sorta like the game just froze unless you noticed that the End Scenario button was now enabled.

I s'pose we could say "This screen intentionally left black." :P

Prolly be best, though, the have it was a few seconds (long enough to cause a panic but not long enough to decide it's dead and reboot) and automagically press the button for you .. if we can.

**Comment by sigurdfdragon** [comment]
I should have this done in a couple of days.
