### ISSUE TITLE
Countdown position is hardcoded as relative to battery

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3582]
In the default theme, the countdown (clock) widget and battery status are adjacent. This is hardcoded in the engine:

https://github.com/wesnoth/wesnoth/blob/db40dcafc8d2f4d5ce75fdb83cbe5491c736e357/src/theme.cpp#L463-L471

The engine shouldn't hardcode any particular relationship between these two elements.

Labeling 1.14 because themes were removed on master.

**Comment by jostephd** [comment]
Themes were re-added to master as a byproduct of the reshuffle, #3603.

**Comment by gfgtdf** [comment]
The theme wml is to some extent able to change like it's done in the replay viewer which is added dynamically on the theme by theme wml. I dunt remember how it worked exactly so I dunt know whether that can be applied here.

Iirc the main reason why we didn't fix this one was that we wanted to remove theme wml at some point. And it's currently unclear wheyy that'll still happen.

**Comment by jostephd** [comment]
Thanks!
