### ISSUE TITLE
game is unresponsive while connection to add-ons server is pending

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3592]
Currently two things happen for me at the same time – bad wifi connection and the server troubles.

Sometimes I do not get an immediate error message while connecting. The loading bar stays then empty, and some time passes until I get the error message (I assume it's the wifi causing the delay)

If I press during that time either the cancel button, or try to quit wesnoth with the window manager's X button, no action is executed. (in case of the cancel button, it remains highlighted after pressing)

However, the action is executed after some time.
That sound like wesnoth is blocked until it get's an answer from the network.

Edit: the dialogue box showed all the time "connecting to add-ons.wesnoth.org", it didn't go to the next step (which it couldn't to begin with due to the server trouble)

**Comment by GregoryLundberg** [comment]
Adding the wesnoth.org servers to my etc/hosts file allowed me to work around the DNS failure. Most likely, that failure will clear in a few more hours. Once the DNS issues resolve, testing this issue should be possible by purposefully sending wesnoth.org to a non-existent IP address by using entries in etc/hosts.

**Comment by fcbond** [comment]
I can't connect to the add-ons server or even wesnoth.org.

**Comment by mesilliac** [comment]
This appears fixed. I can both cancel and close the game while waiting for the addon server connection, which takes a second or two in my region. I confirmed that in 1.16 exiting wesnoth does wait for the connection before quitting (although canceling works), so this appears to have been fixed sometime in 1.17.
