### ISSUE TITLE
May I contribute russian translation?

### ISSUE THREAD

**Issue by devovercome** [wesnoth/wesnoth#3593]
Hi! Just opened the game on steam, and found that languages are mixed. This isn't playable, really.

The good news - I am working on filling up localizations. Currently I have done po/Wesgoth folder, as you can see in [my fork](https://github.com/devovercome/wesnoth/tree/1.14)

And since the Wesgoth website is down, and only lead to correct move is Steam thread (something like 'Dont push code directly to github - email the localization Lead' - so here I am, asking for that email.

**Comment by jostephd** [comment]
Thanks! The website should be up now can you open https://wiki.wesnoth.org/WesnothTranslationsHowTo#How_to_submit_your_translations ?

**Comment by devovercome** [comment]
Great! That page contains all I need! I will proceed further li'l bit later, next weekend.
