### ISSUE TITLE
assertion failue in attack.cpp

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3594]
![grafik](https://user-images.githubusercontent.com/4893136/46431559-63c38500-c74c-11e8-9f2e-eb6ced1c2553.png)

See screenshot, it happens during the campaign "The Atlaz Mariners" I have autosaves disabled so i cannot give you a recent save. It might or it might not be relevent that
1) I hit the enemy in tmy turn before with the "disarm" special which disables ranged attacks, and that unit only had disarmed attacks.
2) My unit was only 1 exp from advancing.

It probably reproducable by having an ai controlled unit that has only one attack and which is [disabled]

happend on 1.14.5 official windows release

EDIT2: there seemed to be no problems after i hit "Ignore"

**Comment by jyrkive** [comment]
Was this during your own turn, or an AI turn?

**Comment by gfgtdf** [comment]
during the ai turn. (also updated my first post, assumiong form how fast your answered that you migth still have read the old version)

**Comment by gfgtdf** [comment]
ok after loooking at the code it very liek that its this path https://github.com/wesnoth/wesnoth/blob/1.14.5/src/actions/attack.cpp#L567 (attacker_stats_ is set and then it returned casues the assertion)

**Comment by gfgtdf** [comment]
ok i tested and it can be reproduces with wesnoth.simulate_combat, when the attacker as exactly one weapon and that weapon is disabled and the defender has multiple nondisabled weapoions (all of the same range)

**Comment by jyrkive** [comment]
Note that the reset call in question was necessary to *fix* a crash elsewhere. See commit 95953079895cf5c1cff89b0f7103ac850a3847db.

**Comment by gfgtdf** [comment]
Thinking about it, I'm unsure how disable is supposed to work on detail, In particular: when a unit has an attack with a disable special that is only active for certain opponents attacks ( which makes a lot sense in the defensive case but I want to talk about the Offensive case ), should the attack then be disabled if the unit has _any_

**Comment by jostephd** [comment]
If unit A has an attack with a disable special that's active for attack X but not for attack Y, then the attack should be disabled if unit B attacks A with X but not if unit B attack A with Y... Right?

One could still define an attack that's disabled whenever the enemy unit has, say, "a ranged impact attack" even if the enemy unit isn't using that attack in this combat, of course.

**Comment by gfgtdf** [comment]
> unit B attacks A with X but not if unit B attack A 

That was not the question we are talking about the case where the attacker has the disable special

**Comment by jostephd** [comment]
Can you give a complete example? (The definition of the special)

**Comment by gfgtdf** [comment]
The special has a filter that is only active for some of the defenders weapon, cannot type code on my phone.

**Comment by jostephd** [comment]
Sorry, I see what you mean now. Unit A has an `affect_self` disable special that kicks in depending on the attack of the other unit, and the question is, can unit A attack a unit that has one attack that matches the filter and one attack that doesn't.

We could say that A can't attack. The alternative interpretation is that A can attack and the defender is forced to choose an attack that doesn't satisfy the disable special's condition, but that interpretation can be achieve by other means, can't it?

**Comment by gfgtdf** [comment]
hmm yes i also came to the conclusion that "A can't attack" is the most logical conclusion.

**Comment by gfgtdf** [comment]
madea pr for the fix https://github.com/wesnoth/wesnoth/pull/3602

**Comment by jostephd** [comment]
@gfgtdf Can we add a regression test, maybe based on the wesnoth.simulate_combat reproduction recipe you had?
