### ISSUE TITLE
Scrolling in game / editor is erratic to the point of being annoying

### ISSUE THREAD

**Issue by wlinna** [wesnoth/wesnoth#3607]
Since 1.14.0, scrolling in game and in editor has been erratic. 

Steps to reproduce:
1. Open Map Editor
2. Create an empty map.
   - Size doesn't seem to matter, but let's go with 100x100
3. (Optional) Set scrolling speed to low for easier observation
4. Move the camera around the map with either mouse or arrow keys

What should happen:
The same as in 1.12: the actual scrolling speed is constant. 

What actually happens
The speed of scrolling usually follows this pattern: fast, slow, fast.

I've tested this with both Steam version and with compiled version. My system information:

- Wesnoth version: 1.14.5 from source (or 48bd45d-Modified from Steam).
- SDL2: 2.0.8
- SDL2_image: 2.0.3
- g++: 7.3.0
- OS: Kubuntu 18.04
- GPU: Intel(R) HD Graphics 520 (max core profile is 4.5 and compat profile 3.0)

I noticed that while compiling 1.14.5 from source,  the Steam build of Wesnoth didn't exhibit this behavior as strongly.

I will test this on Windows 10 soon.

As I said, this problem has been present since 1.14.0. Sorry for not reporting about this earlier!

**Comment by gfgtdf** [comment]
hmm its very likeley that this happens becasue some parts of the programm are just too slow, to excule the most common sources of slowness you should try the following things:
1) disable minimal terrain drawing (there is a button below the minimap for that)
2) disable map animations and water animations, in the preferences menu

**Comment by wlinna** [comment]
I tried the things you suggested, but neither produced the desired result. But could they? The map was already as plain as possible. Just grassland, and the size of the map didn't seem to matter. I've tried this on 50x50, 100x100, 200x200, and in the first scenario of the campaign Under the Burning Suns. It doesn't seem to make any difference.

On default scrolling speed, the problem is actually that the scrolling gets suddenly **too fast**. It's almost like the scrolling doesn't take FPS into account or something. Scrolling was much more tolerable (<- constant) **during heavy load** (when I was compiling Wesnoth at the background).

I just tested this on Windows on Steam on the same machine, and the same problem occurs.

**Comment by gfgtdf** [comment]
> But how could they? 

the minimal drawwing is independent of what the map actually contains, it just uses a really slow scaling algorithm with no animations. 

but wrong what you describe it indeed doesn't seem like this was the problem here.

**Comment by Wedge009** [comment]
I could only really observe this very slightly, barely noticeable let alone bothersome (for me). It could be that we are hitting the limits of the engine, particularly on older processors (rendering is all done in software so GPU is, I believe, irrelevant). Another reason for the push for Wesnoth 2.0, I suppose.

**Comment by gfgtdf** [comment]
ok i was also able to reproduce with on 1.15-dev. It tatally unrelated to the actual shown terrain or the minimap: when you press the arrow button it starts scrolling at normal speed fast(rather fast) but slows down aftter a few tiles. I think this is totally unrelated to the drawing code and more relatedto wesnoth handles input.

**Comment by gfgtdf** [comment]
> ok i was also able to reproduce with on 1.15-dev. It tatally unrelated to the actual shown terrain or the minimap: when you press the arrow button it starts scrolling at normal speed fast(rather fast) but slows down aftter a few tiles

I assume (not 100% sure though) that i tested this with an all-grass 200x200 map. and still got uneven scrolling. On my current pc don't have his problem anymore. So yes it's likeley that this is effecty by computer speed.

> Only when I generate a map do I observe some slight inconsistencies in the scroll speed

this could be because  scolling over water is somewhat slow, which is indeed a a graphics issue.
