### ISSUE TITLE
Allow referencing locations by x and y

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3617]
A number of Wesnoth APIs return locations in a simple `{x, y}` array format, but this is unintuitive since you need to reference the coordinates as `loc[1]` and `loc[2]`. It would be nicer if they could be referenced as `loc.x` and `loc.y`.

This should not be difficult to do, as sometime during 1.13 a centralized C++ function was created for placing locations onto the stack, so all you'd need to do is double-store the coordinates in both keys. In other words, instead of pushing `{3, 4}` for example, it would push `{3, 4, x = 3, y = 4}`.

It might also be nice to add a metatable with a `__tostring` that collapses out the redundant information (for example, returning `"(3,4)"`), but not really necessary...

**Comment by stevecotton** [comment]
@CelticMinstrel have you already done this in 1.16?

**Comment by CelticMinstrel** [comment]
This is covered by d04bd2bf5d2ad932ca9bb3203f4ff9f91411e261; however, that won't be backported. It was a little trickier to make it work than I thought, though.
