### ISSUE TITLE
Disconnecting from MP server crashes master

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#3625]
Post-October 2018 re-based master is in a much better state overall but I found that it crashes upon disconnecting from an MP server (the official one, at least).

Issue appears to be caused by 519447b0, inside the destructor for wesnothd_connection(). (Testing at 2dd7e870 was okay.) Maybe there some other commits from 1.14 that needs to go together with this one?

Confirmed in both Windows and Linux.

**Comment by jyrkive** [comment]
The automated MP test in Travis CI was passing until commit 519447b0cb049e5e9ec7dfb8a06a3af7c6c60f44, so this bug may be a regression from that commit.

Commit f6933b98f8b582e89981f89c0c9206daf5f9163b attempts to fix the test and may also fix this bug.

**Comment by Wedge009** [comment]
Seems to work, and despite the 'shot in the dark', it makes sense to me. Sorry for submitting this too soon.
