### ISSUE TITLE
SCATTER_UNITS macro places twice the units it's supposed to

### ISSUE THREAD

**Issue by mattsc** [wesnoth/wesnoth#3663]
When using the SCATTER_UNITS macro, double the units set in the arguments are placed on the map.  After looking into this, this is caused by the `[random_placement]` code.  The `[command]` tag in the macro is executed twice, first [here](https://github.com/wesnoth/wesnoth/blob/master/data/lua/wml/random_placement.lua#L83) then [here](https://github.com/wesnoth/wesnoth/blob/master/data/lua/wml/random_placement.lua#L95).

I suspect that this affects other code using `[random_placement]` as well.

Assigning to @CelticMinstrel since he added that code block in ab36d7b60

An easy way to test this is to put a moveto event like that below into any scenario.  Moving any unit will then trigger the macro.
```
[event]
    name=moveto
    first_time_only=no

    {SCATTER_UNITS 1 "Ghost" 1 (x,y=1-10,1-11) (side=1)}
[/event]
```

**Comment by CelticMinstrel** [comment]
Thanks for spotting that.
