### ISSUE TITLE
After killing a unit, adjacent friendly units don't change orb color from yellow to red

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3664]
1. Move unit A next to enemy unit X
2. Kill X with a unit other than A
3. A's orb should change color to red, but it remains orange until A is moused over.

**Comment by jostephd** [comment]
Reminds me of https://github.com/wesnoth/wesnoth/issues/3629

**Comment by Konrad22** [comment]
Doesn't something like this happen as well when you win a scenario? (All of your orbs turn green and then they do not turn red.)

**Comment by jostephd** [comment]
In 1.14 the orbs stay red. I wouldn't mind if they stayed all green, either, but they shouldn't _wait to be moused over_ to change color.

**Comment by stevecotton** [comment]
> Doesn't something like this happen as well when you win a scenario? (All of your orbs turn green and then they do not turn red.)

That's been logged (on 1.15) as #5187, with PR #5205 fixing it. Should it be backported?

**Comment by Wedge009** [comment]
I suppose no point in back-porting to 1.14 any more.

_This_ particular issue is still present for 1.15.17+dev (1.16 beta).

**Comment by Wedge009** [comment]
Orbs seem to be changing to red correctly, for 1.16.8 release.
