### ISSUE TITLE
Vision retained to droided side

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#3665]
When playing an MP game with multiple human sides, such as Auction X:
- A player surrenders
- The host is given control of the side
- The host droids the side via the `:droid <side> on` command

At this point, the host is still able to see as if playing the droided side.  This is particularly annoying since it *only* gives vision to the most recently droided side, so as the host I can't see what's going on with my units until it's my turn again.  For example, [here](https://i.imgur.com/saYr5jZ.jpg) green is the side that I droided, which I get vision to as soon as it's the green AI's turn to move, and I can't see my side(red) which is on the part of the X to the right until after the center AI finishes moving.  Additionally, if I type in chat while I have vision on green, my player name is also green rather than red.

This occurs using the Steam release on Mint 19.

**Comment by gfgtdf** [comment]
> At this point, the host is still able to see as if playing the droided side

yes this is intentional, in 1.14 :droid means letting the ai play/help 'for you' (instead of  giving up control over that side)

**Comment by Pentarctagon** [comment]
How do I give up control of the side, in that case.  It's very irritating to not be able to see my own units.

**Comment by gfgtdf** [comment]
hmm ye i agree that the current situation is not optimal, and that an easy way to do that should be added. afaik its currently only doable via wml [modify_side]controller=ai.

**Comment by Pentarctagon** [comment]
What about a `:droid_full` command that uses the same syntax as the `:droid` command but also gives the AI control of the side.

**Comment by jostephd** [comment]
Or adding an "AI" side to the `:give_control` dialog.

**Comment by gfgtdf** [comment]
hmm the problem is that changing the actual controller might casue OOS if its done out of turn, so such a command woudl then probably only work during your 'own' turn (the turn of any side you control inclusing the side you just took over)

**Comment by Pentarctagon** [comment]
@gfgtdf It is currently possible to give control of your own side to another player during someone else's turn, and for the host to reassign sides during anyone's turn, so I don't think OOS is a concern, unless there's something uniquely OOS inducing about making the AI a controller.

For example, with the following setup:
* side 1 - Pentarctagon
* side 2 - Pentarctagon1
* side 3 - Pentarctagon1
* side 4 - Pentarctagon1

during side 1's turn with `:give_control`:
* Pentarctagon was able to assign side 3 to Pentarctagon2
* Pentarctagon2 was then able to assign side 3 to Pentarctagon
* Pentarctagon1 was then able to assign side 2 to Pentarctagon2

The end result being:
* side 1 - Pentarctagon
* side 2 - Pentarctagon2
* side 3 - Pentarctagon
* side 4 - Pentarctagon1

**Comment by gfgtdf** [comment]
> unless there's something uniquely OOS inducing about making the AI a controller.

Afaik there are two cases where chaging controller can cause OOS:
1) wml that uses code like `if side.controller == 'ai' then --do stuff...`

2) the code that checks whether you got a victory or a loss uses the side controller so changin controller in a mp campaign in the wrong moment could make the game fire different events (victory or defeat) on the differnt sides

**Comment by CelticMinstrel** [comment]
> Or adding an "AI" side to the `:give_control` dialog.

I think this is probably the best option.

**Comment by Pentarctagon** [comment]
@gfgtdf The [wiki](https://wiki.wesnoth.org/InternalActionsWML#.5Bstore_side.5D) for the controller value already says though that:

> In networked multiplayer, the controller attribute may not be the same on all clients. Be very careful or you have OOS errors.

So the examples you gave are problematic currently anyway, it looks like.

**Comment by jostephd** [comment]
> > Or adding an "AI" side to the `:give_control` dialog.
> 
> I think this is probably the best option.

Looking at the code, this looks fairly fairly straightforward to implement, so I'm labeling this a good first issue. However, this will require patching the srever as well, so I'm not sure if that's backportable to 1.14?

**Comment by gfgtdf** [comment]
> @gfgtdf The wiki for the controller value already says though that:

That comment was mainly about 1.12 when 'network_ai' and 'network' were also possible values currently it shodul be _mostly_ safe, i currently don't remember the details though.

**Comment by Pentarctagon** [comment]
So more specifically it looks like the change would be to:
* gui/dialogs/multiplayer/mp_change_control.cpp, to add the "AI" option(s) to the selectable list.
* server/game.cpp's transfer_side_control method to handle the "player" value being "AI".

The first is easy enough, but the second I'm not really sure how to do myself.  [:droid](https://github.com/wesnoth/wesnoth/blob/master/src/menu_events.cpp#L1190) ends up just [calling team.hpp's toggle_droid method](https://github.com/wesnoth/wesnoth/blob/master/src/menu_events.cpp#L1446-L1451), [:control](https://github.com/wesnoth/wesnoth/blob/master/src/menu_events.cpp#L1195) goes through the [same code](https://github.com/wesnoth/wesnoth/blob/master/src/menu_events.cpp#L1563) path as [:give_control](https://github.com/wesnoth/wesnoth/blob/master/src/menu_events.cpp#L1233), and [modify_side] ends up calling [team.cpp's change_controller_by_wml](https://github.com/wesnoth/wesnoth/blob/master/src/team.cpp#L583) method(which I guess wouldn't be safe to call directly?).

**Comment by CelticMinstrel** [comment]
I still think an added option in `:give_control` would've been preferable...

**Comment by Wedge009** [comment]
Re-opening due to @Konrad22's reports in #3374.

**Comment by Pentarctagon** [comment]
Given gfgtdf's first comment, I think this behavior is expected now for "on", which is why I added the "full" option.

**Comment by Wedge009** [comment]
@Konrad22 Sounds like this is new behaviour - does that work for you?

**Comment by Wedge009** [comment]
No response from @Konrad22 yet, but from what I saw in #wesnoth-dev he seems to be okay with the new behaviour.
