### ISSUE TITLE
Deprecate the AI controller for removal

### ISSUE THREAD

**Issue by mattsc** [wesnoth/wesnoth#3668]
The [AI controller](https://github.com/wesnoth/wesnoth/blob/master/data/core/macros/ai_controller.cfg) is used in roughly 2 dozen mainline scenarios.  It certainly has its uses, but it has a whole bunch of issues too.

Arguably its biggest problem is that, unless you're quite familiar with both the AI and what the AI controller does internally, it is not at all obvious what it does.  Settings like "Be more defensive" or "Focus on protecting..." do not necessarily do what one would intuitively expect.  As a result, it is not always obvious what the controller is doing, often leading players to conclude that it simply isn't working.

It is also possible to choose options that actively contradict each other.  See, for example, #3066.

And, in general, because it has to work within the limitations of the default AI, a lot of the effects are rather subtle in the first place, and it is questionable whether they really make a noticeable difference.

So what should we do about this?  Possibilities include:

1. Leave it as is (easiest solution, of course)
2. Remove it altogether (almost as simple)
3. Add more instructions/explanations, so that it is more obvious what the AI controller does
4. Add conditions so that contradictory instructions cannot be chosen
5. Add additional behavior (for example, in one of my campaigns I have "make allied leader go here" and "release allied leader from going here" context menu options to keep said leader from committing suicide)
6. Customize the options per scenario
7. ...

... or combinations thereof.

Speaking from a practical perspective, I'd just remove the thing altogether, because I don't think it is all that useful in its current stage and improving it is more effort than it's worth.  Idealistically speaking, I would of course like to turn it into something more useful, along the lines of options 5 or 6.  Or we could just leave it as is ...

So I guess I am asking for two things: for people's opinions on the topic and for volunteers to help with ideas, customizations by scenario, writing of more intuitive instructions etc.  I'd be happy to help with whatever AI work might be needed, but in practice there's no way I am going to go through 20+ scenarios to customize this.

**Comment by gfgtdf** [comment]
A way to control the ai is clearly useful if done properly, It is still annyoing when you for example play a scenario with an ai ally and you see the ai going siuicidal towardes the enemy area instead of just staying in the castle, and wait for me to do a joined forces attack.

From what you said though it seems like the current ai controller is neither easy to understand/maintain nor is really capable to fix these things, so ye i'd also go with removing it, at least the current code, from talking a briref look at you link it seems like its actually 90% hard-to-understand wml dialog code that would nowdays be done via wesnoth.show_dialgo anyways and 10%ai code that as you said doesnt really work the expected way.

**Comment by GregoryLundberg** [comment]
I'm going to miss it but it sounds like it needs far too much work, so I won't oppose removing it.

Truthfully, I never really understood it, and I do remember giving exactly those orders which you said were contradictory.

If it stays, it needs "all, or some combination, of the above": better descriptive terms on-screen, better documentation, checks to prevent illogical or impossible conditions, and strengthening so the effects are more noticeable.

**Comment by GregoryLundberg** [comment]
So just make the options say what they mean:

"Be a bit more cautious in your hopeless, suicidal charges."

"Pay minimal lip service to protecting <unit> during your hopeless, suicidal charges."

/s

**Comment by CelticMinstrel** [comment]
Additional options:

- Change the behaviour of each command to be closer to what the player would expect, for example using MicroAIs.
- Deprecate it, write something new from scratch to take its place.

**Comment by mattsc** [comment]
Agreed that those would be good/preferable options.  The problem is that I do not know how to do either one of those in a way that would work well enough in a (somewhat) general setting.

**Comment by Vultraz** [comment]
Remove it is!

**Comment by CelticMinstrel** [comment]
And @Vultraz instantly picks the absolute worst of the options. Thanks!

**Comment by CelticMinstrel** [comment]
After some discussion with Vultraz on IRC/Discord, we decided to reopen this as a reminder to actually do it.

The goal then is:

* [ ] Mark the AI Controller macro(s) for level 3 deprecation, to be removed in 1.17.
* [ ] Start removing any usage of them from mainline scenarios.

Personally I think it'd be preferable if an alternative were produced before we remove it, but apparently no-one really knows how to do that, so it seems likely that it won't happen, I guess. If I find time (which is unlikely), I may try my hand at it, but...

**Comment by mattsc** [comment]
Just adding a cross-link to #3450, where this is also mentioned as an action item.

**Comment by CelticMinstrel** [comment]
Thinking of ideas for a Lua-based replacement, maybe with custom WML tags. Not sure yet if I'll actually do it, though.

**Comment by mattsc** [comment]
Ticked off both tasks.
