### ISSUE TITLE
Loading screen animation rate limiter temporarily disabled

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3679]
dbbd153d3f6f835fe9c7f8543358b3ac6b475f2e disabled the loading screen animation rate limiter. According to the commit message, that was done "temporarily", which means we should to enable it again before the next release. So here's a reminder issue.

**Comment by jostephd** [comment]
@Vultraz The log message of dbbd153 speaks of "a weird issue where the animation sometime wouldn't show up on game launch". Does that issue exist on current master? I understand that the issue wouldn't be _visible_ since the rate limiter is disabled, but could it affect other parts of the UI?

**Comment by CelticMinstrel** [comment]
I disagree about it looking better without the rate limiter... it still looks okay on my machine, but not _better_.

**Comment by jostephd** [comment]
I checked how long it takes `wesnoth ./t` from start to turn dialog. Reverting e761acbaa428ad350b3a0d9b386f11b191c127ea e868c7e890ad4e56dd8074f12ffd76dada0987f0 dbbd153d3f6f835fe9c7f8543358b3ac6b475f2e increases the speed by 5% (2.0s to 1.9s) but causes the turn dialog sound to stop playing. So I guess there are three separate questions here:

1. Playing the turn dialog sound
2. Make the loading screen fast
3. Make the loading screen look good

In master, 1) is done, and unless there are particular complaints about 2) and 3), we can just close this as won't fix.
