### ISSUE TITLE
Removing illegal command 'init_side'

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#3685]
During an MP match on Auction X, I had the following happen:
- Player 3 disconnected
- I replaced them with an observer via the popup dialog that appears automatically, not with :give_control or :control
- In the chat it printed "Removing illegal command 'init_side' from: Pentarctagon. Current player is: zill (1/5)." - https://i.imgur.com/dpcqFB3.png
- This also seems to have ended up breaking the ability to reassign control altogether - the only way I could do so later was to kick him.

**Comment by gfgtdf** [comment]
who was the host of this game? When did the 'Removing illegal command ' appear? (directly after reassigning the side or later). Whose turn was it when the player 3 disconnected ?

**Comment by Pentarctagon** [comment]
I was the host.

It happened immediately after I gave control to the observer.

It was player 3's turn - they had started the game as the player "mill", then left soon after "zill" joined(who had the same IP address as "mill").

It happened on the 1.14.5 Steam release.

**Comment by gfgtdf** [comment]
hmm i looked at the code that generates he erromessage and it seems like it contains wrong information: the (`1/5`) part should give information about the current side number but actually it uses the turn_end_ variable which is never set.


Does the errolopg contain any useful information ?

**Comment by Pentarctagon** [comment]
The Steam release [doesn't keep any logs](https://forums.wesnoth.org/viewtopic.php?f=4&t=46166#w0steamunix), unfortunately, so I don't have any log output.

**Comment by gfgtdf** [comment]
hmm ok i think the most intuitive fix is to add a check for 'not idle' at `play_controller::maybe_do_init_side`, (https://github.com/wesnoth/wesnoth/blob/20b76b32c0101cee202ba6946eaa1f2e23b094c8/src/play_controller.cpp#L440)have to think about whether that might break other things.

**Comment by gfgtdf** [comment]
general note: after getting a "Removing illegal command" error it is reccomended to save&load the game to prevent later OOS. Its also possible if just the side the was mentioned just leaves an rejoins but in this case this case that was the host, so yet save&reload is the reccomneded action is that situation.

**Comment by sevu** [comment]
Can this go to 1.14 too?
