### ISSUE TITLE
When "Point of view" is "Full map", can't view descriptions of would-be shrouded enemy units

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3687]
During replay of a scenario that has an enemy unit under shroud, change "Point of view" to "Full map". The enemy unit is then shown, but the `d` hotkey ("Unit Description") does not work on it. This is because https://github.com/wesnoth/wesnoth/blob/64cb83d4579f7ba7cbfd9832ce1c511e2c02ea0d/src/hotkey/hotkey_handler.cpp#L360-L361 calls https://github.com/wesnoth/wesnoth/blob/64cb83d4579f7ba7cbfd9832ce1c511e2c02ea0d/src/menu_events.cpp#L635-L645 which does not pass `see_all=true`.

**Comment by jostephd** [comment]
I think this might also affect the time of day graphic, when the mouse is over a hex that has a custom tod schedule.

**Comment by sevu** [comment]
Just for information, there are two more places not involved with replays, where one "can't view descriptions of would-be shrouded enemy units":
- you played an MP game, the game is over and the map uncovered – you see now all units, but hotkeys don't work on previously shrouded ones
- you host a game networked game with shroud,  but don't play yourself. As host you can see the whole map, but not the description of all units.

**Comment by jostephd** [comment]
> you played an MP game, the game is over and the map uncovered – you see now all units, but hotkeys don't work on previously shrouded ones

Didn't test this one.

> you host a game networked game with shroud, but don't play yourself. As host you can see the whole map, but not the description of all units.

#4119 doesn't fix this, but I'd still like to merge it since it fixes another form of the bug.

**Comment by jostephd** [comment]
> you played an MP game, the game is over and the map uncovered – you see now all units, but hotkeys don't work on previously shrouded ones

https://github.com/wesnoth/wesnoth/pull/4119/commits/37b813bec4aa81cd86fa7ea154c51f45c7d2ffbc should fix this. I don't know if it fixes the issue with a non-playing host in MP games.

**Comment by sevu** [comment]
It does!

**Comment by Wedge009** [comment]
I also confirm this is present in 1.14.7 and resolved in 1.14.8+dev.
