### ISSUE TITLE
Fix mingw cross-compile on master

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3690]
Fwdport 698d233ee6549740c45aef55fed1012749ab9463 from 1.14 to new master.

That probably means changing "Windows" to "windows" on this line:

https://github.com/wesnoth/wesnoth/blob/a26dcf8577691e5074776765416e30e7a36a61e9/src/desktop/windows_battery_info.cpp#L17

but if someone could actually do a cross build and run it, obviously that'd be better.

**Comment by loonycyborg** [comment]
Porting case fix is fine. I'll do a cross build later, when I'll have cross-toolchain working again. If there will be any issues I'll fix.

**Comment by jostephd** [comment]
@loonycyborg Thanks. In the meantime I'll close this issue since #3691 has been merged (unless you prefer to leave it open as a reminder).
