### ISSUE TITLE
add a wesnoth.set_dialog_tooltip function

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3692]
as the tilte says, It'd be nie to hve a unction to set  a wigets tooltip.

**Comment by edwardspec** [comment]
Is there a chance it can be backported to 1.14?
This is too cool to wait for 1.15.

Check out what I can use it for:
![tooltip-item](https://user-images.githubusercontent.com/1163218/50553073-a136a080-0cb0-11e9-8494-c5aa91f77e2c.jpg)

**Comment by jyrkive** [comment]
@edwardspec No, this can't be backported to 1.14. API changes are not allowed in bugfix releases.
