### ISSUE TITLE
Sidebar terrain defense modifier truncated

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3693]
The terrain defense modifier is truncated. This happens on master but not on 1.14. Probably need to fwdport 47bd5ade3726675c0d6e4e68af82004a01ddb63d (one of the two remaining commits on #3614).

![screenshot_2018-11-06_23-54-18](https://user-images.githubusercontent.com/24784687/48101660-b8609100-e21f-11e8-863a-3ac16e382157.png)

**Comment by Wedge009** [comment]
Anyone willing to check #4315?
