### ISSUE TITLE
Default AI TODOs cleanup

### ISSUE THREAD

**Issue by mattsc** [wesnoth/wesnoth#3695]
Issue #3450 has a single bullet on cleaning up the TODOs in the C++ AI code. There are 50 such TODOs, so I figured it would be useful to have a separate issue to discuss what should be done with them.

**Updated 14 Dec 2018**

<details><summary>Don't do anything, just remove the comment (done in b62f2d3f33)</summary>

- [x] [actions.cpp#L384](https://github.com/wesnoth/wesnoth/blob/master/src/ai/actions.cpp#L384):	`///@todo 1.9: see_all -> false`
    AI has full knowledge of map (but not of invisble units on map). This is not going to change.
- [x] [actions.hpp#L451](https://github.com/wesnoth/wesnoth/blob/master/src/ai/actions.hpp#L451): `///@todo 1.7.11 important! Add an ai action (and fai function) to set a goto on a unit`
    Can already be done with `wesnoth.custom_synced_commands`
- [x] [actions.hpp#L452](https://github.com/wesnoth/wesnoth/blob/master/src/ai/actions.hpp#L452): `///@todo 1.7.11 important! Add an ai action (and fai function) to send a chat message to a player`
    Don't see a need for this
- [x] [contexts.cpp#L657](https://github.com/wesnoth/wesnoth/blob/master/src/ai/contexts.cpp#L657):	`//TODO: fix, removing some code duplication`
    This looks like an acceptable level of code duplication to me
- [x] [manager.cpp#L608](https://github.com/wesnoth/wesnoth/blob/master/src/ai/manager.cpp#L608): `///@todo 1.9 add error reporting`
    Don't think it's needed
- [x] [manager.cpp#L634](https://github.com/wesnoth/wesnoth/blob/master/src/ai/manager.cpp#L634): `///@todo 1.9 add error reporting`
    Don't think it's needed
- [x] [testing.cpp#L97](https://github.com/wesnoth/wesnoth/blob/master/src/ai/testing.cpp#L97): `///@todo 1.9: add information about ai_config`
    Already done [here](https://github.com/wesnoth/wesnoth/blob/master/src/ai/configuration.cpp#L250) and available with `--log-debug=ai/config`
- [x] [composite/ai.cpp#L177](https://github.com/wesnoth/wesnoth/blob/master/src/ai/composite/ai.cpp#L177): `//@todo 1.9 : consider allowing other engines to evaluate`
    No need for this
- [x] [composite/aspect.cpp#L60](https://github.com/wesnoth/wesnoth/blob/master/src/ai/composite/aspect.cpp#L60):			`///@todo 1.9 add `minor_gamestate_change_observer
- [x] [composite/aspect.cpp#L88](https://github.com/wesnoth/wesnoth/blob/master/src/ai/composite/aspect.cpp#L88):		`///@todo 1.9 add minor_gamestate_change_observer`
- [x] [composite/aspect.cpp#L114](https://github.com/wesnoth/wesnoth/blob/master/src/ai/composite/aspect.cpp#L114):		`///@todo 1.9 add `minor_gamestate_change_observer
    Don't see a need for the previous three.  What would we use them for?
- [x] [composite/component.hpp#L33](https://github.com/wesnoth/wesnoth/blob/master/src/ai/composite/component.hpp#L33): `//TODO: find a good place for this`
    This place is as good as any?
- [x] [composite/aspect.hpp#L302](https://github.com/wesnoth/wesnoth/blob/master/src/ai/composite/aspect.hpp#L302):		`///@todo 1.9 optimize in case of an aspect which returns variant`
    Good enough as is?  This is not done very often.
- [x] [default/ca.cpp#L84](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/ca.cpp#L84):			`//@todo: only bail out if goto is on keep`
    The behavior is good as is.
- [x] [default/ca.cpp#L571](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/ca.cpp#L571): `///@todo 1.7 check if this an improvement`
    Don't see a need to do this
- [x] [default/attack.cpp#L159](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/attack.cpp#L159):		`/** @todo 1.9 add combatant.prob_killed */`
- [x] [default/attack.cpp#L232](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/attack.cpp#L232):		 `* @todo 1.9: attack_prediction.cpp should understand advancement`
- [x] [default/contexts.hpp#L47](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/contexts.hpp#L47):	`///@todo 1.7: ai goals: this is a 'target' marker class which should be expanded with additional information which is generic enough to apply to all targets.`
    Good enough as is?
- [x] [formula/ai.cpp#L194](https://github.com/wesnoth/wesnoth/blob/master/src/ai/formula/ai.cpp#L194):	`///@todo 1.9 add formula_debugger`
- [x] [formula/stage_side_formulas.cpp#L75](https://github.com/wesnoth/wesnoth/blob/master/src/ai/formula/stage_side_formulas.cpp#L75):	`///@todo 1.7: serialize to config`
- [x] [formula/function_table.cpp#L695](https://github.com/wesnoth/wesnoth/blob/master/src/ai/formula/function_table.cpp#L695): `/* // TODO: Not really sure what this was meant to do or if there's any reason left to keep it...`
- [x] [formula/engine_fai.cpp#L40](https://github.com/wesnoth/wesnoth/blob/master/src/ai/formula/engine_fai.cpp#L40):		`///@todo 1.7: implement fai_ca->to_config()`
- [x] [lua/core.cpp#L222](https://github.com/wesnoth/wesnoth/blob/master/src/ai/lua/core.cpp#L222):	`//TODO: Right now, aggression is used by the attack execution functions to determine the weapon to be used.`
    This is not really a todo. We should either delete it or change it to a note.
- [x] [lua/core.cpp#L283](https://github.com/wesnoth/wesnoth/blob/master/src/ai/lua/core.cpp#L283):	`//TODO fendrin: talk to Crab about the from argument.`
- [x] [lua/core.cpp#L308](https://github.com/wesnoth/wesnoth/blob/master/src/ai/lua/core.cpp#L308):	`//TODO fendrin: talk to Crab about the from argument.`
- [x] [actions.cpp#L309](https://github.com/wesnoth/wesnoth/blob/master/src/ai/actions.cpp#L309):	`//start of ugly hack. @todo 1.9 rework that via extended event system`
- [x] [game_info.hpp#L114](https://github.com/wesnoth/wesnoth/blob/master/src/ai/game_info.hpp#L114):	`/** hack. @todo 1.9 rework that via extended event system, or at least ensure it hurts no one */`
- [x] [manager.cpp#L743](https://github.com/wesnoth/wesnoth/blob/master/src/ai/manager.cpp#L743):	`/*hack. @todo 1.9 rework via extended event system*/`
- [x] [composite/ai.cpp#L189](https://github.com/wesnoth/wesnoth/blob/master/src/ai/composite/ai.cpp#L189):	`///@todo 1.9 replace with event system`
- [x] [contexts.cpp#L581](https://github.com/wesnoth/wesnoth/blob/master/src/ai/contexts.cpp#L581):	`///@todo 1.9: replace with variant::null_variant;`
</details>

<details><summary>Changes done</summary>

- [x] [contexts.cpp#L777](https://github.com/wesnoth/wesnoth/blob/master/src/ai/contexts.cpp#L777):	~`///@todo 1.9: check for (level_["disallow_recall"]))`~ Not relevant any more, this was removed in f8871d9ad8
- [x] [composite/goal.cpp#L266](https://github.com/wesnoth/wesnoth/blob/master/src/ai/composite/goal.cpp#L266):			`//TODO: we will protect hidden units, by not testing for invisibility to current side`
    Done in d0f1b27dee
- [x] [default/ca.cpp#L1684](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/ca.cpp#L1684):					`//TODO: maybe we should we fix the entry in possible_moves for this move to avoid getting the 'Unit vanished' warning above.`
    Yep.  See #3240
    Done in 37cf4d0e279
- [x] [contexts.cpp#L778](https://github.com/wesnoth/wesnoth/blob/master/src/ai/contexts.cpp#L778):	`return current_team().recall_list().recall_list_; //TODO: Refactor ai so that friend of ai context is not required of recall_list_manager at this line`  -- taken care of in f8871d9
</details>

<details><summary>Won't do: remove todo (done in ba4202caf8b)</summary>

- [x] [manager.hpp#L51](https://github.com/wesnoth/wesnoth/blob/master/src/ai/manager.hpp#L51): `* @todo 1.9 move it out of public view`
    celmin: I guess this could be satisfied by moving the class to the cpp file; might be worth trying it and seeing if it breaks anything, but... if it breaks anything not easily changed, I'd say just remove
    mattsc: tested it: it is used in other places -> don't change, just remove todo
- [x] [default/ca_move_to_targets.cpp#L405](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/ca_move_to_targets.cpp#L405):			`///@todo 1.9: lower this value for perf,`
    Addressed in 6c14b66161
- [x] [contexts.cpp#L548](https://github.com/wesnoth/wesnoth/blob/master/src/ai/contexts.cpp#L548): `///@todo 1.9: add validators, such as minmax filters to aspects`
    Not really all that useful.  (The comment this refers to was removed already when the attack_depth aspect was removeds.)
- [x] [contexts.cpp#L1167](https://github.com/wesnoth/wesnoth/blob/master/src/ai/contexts.cpp#L1167):		`///@todo: shall possible moves be modified as well ?`
    ~I had a first look into this and the answer is yes, it should probably be done for consistency. Need to do some tests though.~  Nope.  Should not be done.  Just remove the TODO.  See my comments in #3764.
- [x] [actions.cpp#L422](https://github.com/wesnoth/wesnoth/blob/master/src/ai/actions.cpp#L422):	`///@todo 1.9 add 'new units spotted' failure mode`
    This is not useful without a significant reworking of the AI itself. If that ever happens, it will be obvious that this is needed. Don't need the TODO.
- [x] [actions.cpp#L476](https://github.com/wesnoth/wesnoth/blob/master/src/ai/actions.cpp#L476):	`///@todo 1.9 set to false after implementing interrupt awareness`
    Related to previous
- [x] [actions.cpp#L804](https://github.com/wesnoth/wesnoth/blob/master/src/ai/actions.cpp#L804):	`//TODO: should we do something to pass use_undo = false in replays and ai moves ?`
    celmin: This sounds like something that probably should be done if it's not already.
    mattsc: isn't that what the `false` in the line above does?
</details>

<details><summary>Won't do for now: change 'todo 1.9' etc. to 'TODO' (done in 49e216bba3)</summary>

**History related TODOs:** this refers the WFL command window history (accessible with the 'f' hotkey). It used to be mixed in with Formula AI, that's why it is part of the AI code. As Formula AI will likely be deprecated and/or removed at some point, we will not do anything about these:
- [x] [manager.hpp#L18](https://github.com/wesnoth/wesnoth/blob/master/src/ai/manager.hpp#L18): `* @todo 1.9 Refactor history handling and internal commands.`
- [x] [manager.hpp#L19](https://github.com/wesnoth/wesnoth/blob/master/src/ai/manager.hpp#L19): `* @todo 1.9 AI Interface command to clear the history.`
- [x] [manager.hpp#L95](https://github.com/wesnoth/wesnoth/blob/master/src/ai/manager.hpp#L95): `* AI Command History Item. It is an implementation detail`
- [x] [manager.cpp#L493](https://github.com/wesnoth/wesnoth/blob/master/src/ai/manager.cpp#L493): `///@todo 1.9 extract to separate class which will use fai or lua parser`
- [x] [manager.hpp#L488](https://github.com/wesnoth/wesnoth/blob/master/src/ai/manager.hpp#L488):	 `* @todo 1.9 rewrite this function to use a fai or lua parser.`

**Other FAI and Lua AI related TODOs:** to be left as they are for now:
- [x] [formula/function_table.cpp#L283](https://github.com/wesnoth/wesnoth/blob/master/src/ai/formula/function_table.cpp#L283):	`/* // TODO: Do we need this?`
    celmin: My suggestion is that, unless you know the answer, just ignore it; FAI is in limbo
- [x] [lua/engine_lua.cpp#L380](https://github.com/wesnoth/wesnoth/blob/master/src/ai/lua/engine_lua.cpp#L380):	`///@todo this is not mandatory, but if we want to allow lua to evaluate`
    celmin: I wonder, under what circumstances is this function even called? I think the equivalent function in engine_fai is called when issuing commands through the 'f' console, but does the Lua version ever get called? I think there definitely should be some path to that, especially if we plan to deprecate/remove FAI.
    mattsc: I don't think this is used at the moment. Keep as a hook in case we ever want to.

**Speculative unit map:** While this would be nice, it is too much to be done at this point. Leaving the TODOs in case somebody wants to pick it up in the future:
- [x] [contexts.cpp#L387](https://github.com/wesnoth/wesnoth/blob/master/src/ai/contexts.cpp#L387):		 `* @todo This is where support for a speculative unit map is incomplete.`
- [x] [contexts.hpp#L1263](https://github.com/wesnoth/wesnoth/blob/master/src/ai/contexts.hpp#L1263) `*       (See the todo in the implementation.)`

- [x] [default/contexts.hpp#L289](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/contexts.hpp#L289):	`///@todo 1.9 refactor this`
    celmin: I'd hazard a guess that this todo is about removing the "mutable" annotation.
</details>

**Comment by mattsc** [comment]
Looking into the two TODOs in [ai/contexts.cpp: get_recall_list()](https://github.com/wesnoth/wesnoth/blob/master/src/ai/contexts.cpp#L775), it appears that this function is actually not used anywhere anymore.  I went as far as removing the definition from ai/contexts[ch]pp as well as the include for recall_list_manager.hpp in contexts.cpp, and the AI certainly still recalls units.

Am I missing something?  Assuming I'm not, I'll remove this function and the corresponding TODOs.

**Comment by jyrkive** [comment]
> * [ ]  [default/attack.cpp#L159](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/attack.cpp#L159):		`/** @todo 1.9 add combatant.prob_killed */`
>   What am I missing? This looks like it's exactly what's done below it.
> * [ ]  [default/attack.cpp#L232](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/attack.cpp#L232):		 `* @todo 1.9: attack_prediction.cpp should understand advancement`
>   Again, looks like this is done in the following.

These look like requests to move the functionality from AI to attack prediction, which isn't a bad idea per se. However, I think it's unnecessary to have TODOs in code comments for suggested improvements.

**Comment by mattsc** [comment]
Moved some items into different categories and added comments based on input from @jyrkive and @CelticMinstrel

**Comment by mattsc** [comment]
I updated the lists in the first comment to reflect what has to be done, and my opinion on what should still be done (and specifically also what will not be done at this time or at all).  There are really only 2 (or maybe 3) items left to take care of.

Let me know if you disagree with any of that.

**Comment by mattsc** [comment]
This is now all taken care of in #3764.  Closing.
