### ISSUE TITLE
Add Lua API to parse a WML file (or string?)

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3696]
This probably wouldn't be too difficult to add, allowing Lua scripts to load arbitrary files (which is already possible) and parse them as WML. It would need to offer some options, such as predefined preprocessor macros (similar to the `--preprocessor-defines` flag), whether to preprocess at all, whether to validate, the schema to use for validation, and perhaps more. It would also make `wml.tostring` a reversible operation.

**Comment by ProditorMagnus** [comment]
I tried to do this few days ago, to see if this way could be used to get instant reload benefit for actionWML.

**Comment by GregoryLundberg** [comment]
# Use Case: Lazy loading WML #

In traditional, monolithic design, certain events may give rise to a cascade of other events but, if the triggering event never occurs, we need none of the supporting WML. When starting the scenario, we must load and parse all of the WML potentially needed for all possible cases.

The proposed change should allow us to only load the conditional WML only when actually needed.

This could result in a significant reduction in the size, loading and parsing time of the base scenario.

## Issues ##
The triggering event may occur several times. Care must be taken to recognize the WML has already  been loaded and avoid re-loading.

The WML might change between loads. While this is most likely during development and debugging, future features might allow the modification of the WML file (say, by (re-)writing from a Lua script). Traditionally, in this case, the scene must be re-started for the changes to take effect. Facilities could be provided to allow discarding the older version and replacing it with the newer. An option should be provided to allow the designer to choose the desired behavior such as ignore the changes, overwrite the changes, or create a new WML block alongside the elder block.

The WML may not exist as an actual file. The Lua script might build the file on-the-fly as a text string. Note this increases the probability that the WML might change (see above).

The WML might no longer be required. If the block is an [event] take we can already remove it. But we need to consider the implications of loading other higher-level tags such as [side] or maps.

**Comment by CelticMinstrel** [comment]
Commit 20e85aa417e implements this, adding `wml.load(file, defines, schema)` and `wml.parse(string)`. There are still two more things that could be done, though:

* `wml.tostring(cfg)` does not output a lossless representation of the config. Specifically, strings are not properly quoted and translatability is lost. This is probably because the function was originally intended for debugging, not serialization, but I think it might be a good idea to change that. (Could involve an optional boolean parameter if the slightly simpler format is still desirable for debugging.)
* `wml.parse()` could take a schema argument in addition to the WML string. It might be nice if it could even run the preprocessor, but that looks like it'll be pretty difficult, so just schema is sufficient in my opinion.
