### ISSUE TITLE
Error in the test scenario

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3697]
Split from https://github.com/wesnoth/wesnoth/pull/3669#issuecomment-436823248 since i can't reopen that one. The change in that issue introduced a logged error in the test scenario.

@newfrenchy83 How would you like to proceed? Fix the scenario, fix the C++, revert the scenario change?

**Comment by jostephd** [comment]
While we're revisiting this, perhaps we should add a WML test for the original bug? @newfrenchy83 I mean something like 36c796852b65b4fb8704054cd769ca94ad7c64fd.

**Comment by newfrenchy83** [comment]
I preger revert the change in test scenario.

**Comment by newfrenchy83** [comment]
I work on force cth macro, and to use object and cth abilities lity instead of weapon special. The remove_object could be used in victory and unit placed for remove modification in blink case.

**Comment by newfrenchy83** [comment]
yes for wml test but i could not test myself before put an PR.

**Comment by jostephd** [comment]
> I preger revert the change in test scenario.

I see you've done that in #3698. Thanks for that. I'll close this issue now as it's done. In the future when you create a PR that's related to an issue please cross-reference the two.

> yes for wml test but i could not test myself before put an PR.

Why is that? If you need help getting the WML tests to run, join the `development` channel on discord (https://discord.gg/battleforwesnoth) and someone will help you set it up. There's also a French-speaking channel but I don't know how many developers are on it.

> I work on force cth macro, and to use object and cth abilities lity instead of weapon special. The remove_object could be used in victory and unit placed for remove modification in blink case.

Okay. Please open a new issue or PR about that. (This issue was resolved by merging #3698.)
