### ISSUE TITLE
A way to get RGB values from color id

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3706]
In the add-on world conquest II, i often want to have text in a specific sides color, unfortunately there is currently afaik no way to convert a specific sides color like 'Red' into a RGB hex string that can be passed to pango. So what I currently do it to have a hard coded map from the standard 9 team colors to RGB values,. This is suboptimal thought since it means that the add-on will not be compatible with custom colors.

So is needed it a way to get RGB values from color id.

**Comment by jostephd** [comment]
The engine could predefine macros or variables that expand to the configured side 1 color.

**Comment by GregoryLundberg** [comment]
ISTR we used to use macros and took them out because of some issue or other.

**Comment by gfgtdf** [comment]
>I think the most intuitive change (which is also probably the hardest to do) would be to integrate team colour names into the Pango markup, so you could do something like <span color='teal'> and it would automatically look up the hex value from the colour range.

Hmm a goodidea but i don't think there is a api in pango to add colors though, so if i'd iplement this i'd probbly just add something like a wesnoth.colors table that can be used like color = wesnoth.colors["teal"], where color would either contain a the full color range data (the4 rgb values) or just the 'average color'.


Another possile issue is that pango also definedits own colors (which i think are the standard html colors) so we could have name id clashes with those colors if we wanted to support our own colors there. (i didn't think this is  a serious issue but something that should be kept in mind)

**Comment by gfgtdf** [comment]
> I'm not sure if Pango has any options for directly extending its markup

I mean, this is not really extending the markup, just adding more colors/overwriting colors, pango _does_ support for example `color='teal'` already it basicially supports all the standard web colors (here as link to the supported colors: https://github.com/GNOME/pango/blob/master/tools/rgb.txt). the point is really that first these colors might not might wesnoths definitions for those colors and that second it will not support fancy umc custom colors. Note that the first might actualyl be a problem: if we overwrite standard colors with wesnoth color it could happen that code that assumes standard colors will be broken.

**Comment by gfgtdf** [comment]
Also this does not only effect my addon in fact it effects mainline in eras.lua to display the timeover advantage.

**Comment by CelticMinstrel** [comment]
I mean, by extending the markup (or at least Pango's colour dictionary) you could write something like `color='team teal'` to get what you want. So I'd say it's still the best option if that can be figured out.

**Comment by cooljeanius** [comment]
document this somewhere please?

**Comment by CelticMinstrel** [comment]
[Way ahead of you there](https://wiki.wesnoth.org/LuaAPI/wesnoth#wesnoth.colors).
