### ISSUE TITLE
Run WML schema validation on Travis

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3709]
Now that we have a schema validator capable of validating looser WML than the GUI2 configs, we should consider running it on Travis to auto-detect mistakes. Note that this also means the schema needs to be properly kept up-to-date as new features are added. Currently, it has yet to be updated for some of the new 1.15.x features.

Summary of relevant options:

* `--validate-schema` _schema-path_ : Validates a WML schema file against _data/schema/schema.cfg_ and additionally checks that cross-references to tags and types within the schema are valid.
* `--validate` _file-path_ : Validates a WML file against a schema, by default _data/schema/game_config.cfg_. For Travis, the file to validate would be _data/_main.cfg_.
* `--use-schema` _schema-path_ : Specifies the schema to use for `--validate`. Does not validate the schema.
* `--preprocess-defines` _list,of,defines_ : When used with `--validate`, the specified defines are set for the preprocessor. Special values like `SKIP_CORE` have no effect when used with `--validate`. For Travis validation, this would be needed in order to set various campaign defines, difficulty level defines, the `MULTIPLAYER` define, scenario-specific defines (eg for A New Land), and the `EDITOR` define.

Depends on #3708.

**Comment by Pentarctagon** [comment]
Trying this locally on master, `data/_main.cfg` succeeds validation.

Trying `./wesnoth --validate data/campaigns/An_Orcish_Incursion/_main.cfg` then gives:
`error preprocessor: Macro/file 'CAMPAIGN_DIFFICULTY' is missing` as expected.

However,
```
./wesnoth --validate data/campaigns/An_Orcish_Incursion/_main.cfg --preprocess-defines CAMPAIGN_DIFFICULTY
```
results in:
```
Validating data/campaigns/An_Orcish_Incursion/_main.cfg against schema /home/derpy/Desktop/wesnoth-dev/data/schema/game_config.cfg
/usr/include/c++/8/bits/stl_vector.h:950: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >; std::vector<_Tp, _Alloc>::const_reference = const std::__cxx11::basic_string<char>&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
fish: “./wesnoth --validate data/campa…” terminated by signal SIGABRT (Abort)
```
(`fish` being the shell I use)

**Comment by CelticMinstrel** [comment]
I'll look into the crash, which shouldn't be happening, but... I _think_ you should be validating `data/_main.cfg` even for the campaigns. Otherwise, it won't include things like the core macros.

This is assuming that `{campaigns/}` in `data/_main.cfg` results in including all the campaigns' WML at that location though, which I'm not 100% confident of...

**Comment by CelticMinstrel** [comment]
Just checked, and found that this seems to work:

```
wesnoth --data-dir=. --validate=data/_main.cfg --preprocess-defines=CAMPAIGN_AN_ORCISH_INCURSION
```

**Comment by jostephd** [comment]
Don't you need to add one of EASY/MEDIUM/HARD to that command line?

**Comment by mattsc** [comment]
Hmm ...  I kind of got it to work by copying the `[micro_ai]` tag into the first scenario of AOI and running with the options as given above by @CelticMinstrel.  Kind of, because I do get an error message when I remove the `ai_type=` line, or when I add a key that does not exist.  But when I remove one of the stationed_guardian specific required keys, such as the `station_x,station_y` line, there is no error.  Am I doing something wrong or is this a problem in the schema code?

```
        [micro_ai]
            side=2
            ai_type=stationed_guardian
            action=add

            [filter]
                id=stationed1
            [/filter]
            distance=4
            station_x,station_y=2,14
            guard_x,guard_y=3,13
        [/micro_ai]
```

**Comment by Pentarctagon** [comment]
@jostephd It should, yes.  It just happened that not doing so didn't result in any additional AOI validation errors.

**Comment by CelticMinstrel** [comment]
> Don't you need to add one of EASY/MEDIUM/HARD to that command line?

Or NIGHTMARE, yes.

@mattsc I don't think there's a way to validate an individual test scenario. Using `--preprocess-defines=TEST` will validate _all_ the test scenarios.

As for your other comment, the relevant part of the schema is here:

https://github.com/wesnoth/wesnoth/blob/master/data/schema/core/actionwml.cfg#L1329

The schema marks the `guard_x` and `guard_y` keys as required, so it _should_ produce an error if they're not present (though that's reliant on `ai_type` having the correct value and `action` not being set to `delete`). Note that _any_ error in the `ai_type` value causes the schema to give up and accept everything (due to the `[else]` tag further down in the file). That said, your example looks like it should trigger the proper conditions to get validated, so I'm not sure where it's going wrong...

**Comment by mattsc** [comment]
@CelticMinstrel Yeah, that's all how I expected it to be.  FTR, I don't care whether I validate test scenarios individually or all together, as long as I get an error message when something's wrong, which does not seem to be so in all cases.  Anyway, I really don't have time to look into this further right now, maybe in a few days, but it looks like something else needs to be done in addition to just adding the new keys.

**Comment by Pentarctagon** [comment]
@CelticMinstrel What's the difference between the various data types?  For example, `grep -Iirn " x "` returns that as being variously `int`, `s_int`, `s_coordinates`, `unsigned`, `range_list`, and `s_range_list`.

**Comment by CelticMinstrel** [comment]
You can look in the types definition file for the answer, I think, but...

* `int` should be used if it can be negative, `unsigned` if it must be a natural number. (I thought that would be obvious? Maybe not to a non-programmer though...)
* `range_list` should be used where ranges are supporter, eg `1-2,4-7,9`.
* Types prefixed with `s_` should be used in contexts that support variable substitution (however, there is no `s_string` because it is indistinguishable from `string` at the schema level).
* Types prefixed with `f_` should be used in contexts where you can substitute a WFL formula enclosed in parentheses (_without_ the use of `$(...)`). There aren't many of these.

**Comment by Pentarctagon** [comment]
Alright, good to know about `schema/types/` (I didn't even think to look there).

**Comment by CelticMinstrel** [comment]
Or `int` and `natural`, even. I don't really care if someone wants to rename schema types, for the record.
