### ISSUE TITLE
DiD S6: victory conditions are inconsistent

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3710]
- [ ] After killing Drogan, the objectives are "Victory: make it to the signpost; Bonus: kill the orc leader", but if you complete the bonus objective (kill the orc leader), the scenario ends without requiring Malin to make it to the sign post (the stated primary objective). I'm not sure if the [objectives] should be changed to match the events, or the other way around. https://github.com/wesnoth/wesnoth/blob/20e85aa417ee993e5d7b00a67295cdd994f486a1/data/campaigns/Descent_Into_Darkness/scenarios/06_Return_to_Parthyn.cfg#L161-L170 https://github.com/wesnoth/wesnoth/blob/20e85aa417ee993e5d7b00a67295cdd994f486a1/data/campaigns/Descent_Into_Darkness/scenarios/06_Return_to_Parthyn.cfg#L451-L456 When I played this, in the last turn I used Malin to kill the orc leader. If I'd had to wait one more turn I'd probably have lost a lvl2 or lvl3 unit.
- [x] ~If you kill Drogan and then the orc leader, you win; if you kill the orc leader and then Drogan, you lose. The order shouldn't matter.~

**Comment by jostephd** [comment]
I just tested again and you _don't_ lose if you kill the orc leader and then Drogan. If you do that the objectives change to "Escape to the north-west" (to the signpost behind the orcs' keep). I edited the first post.

**Comment by nemaara** [comment]
Now fixed by #3857.
