### ISSUE TITLE
1.14.5 MP Lobby text input loses focus when new message arrives

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#3715]
Wesnoth v1.14.5 (MP at Official server)
Windows 7 x64

Join to any hosted game. When you write something and server message comes (for example - "Someone joined game") command line loses focus. So you need to click on it to continue writing.  
Very annoying.

**Comment by Wedge009** [comment]
Not sure if 'command line' is supposed to mean chat box. Seems related to #2817 although that one is for MP staging rather than the lobby.

**Comment by amokmen** [comment]
You could say "command line" - because you could input commands here, or you could say "chat input" - because you could input chat text here...

**Comment by Wedge009** [comment]
Command line usually refers to the OS command prompt where one can execute Wesnoth, not something within Wesnoth itself, hence my confusion.
