### ISSUE TITLE
1.14.5 MP game with ally and my planning mode - OOS errors

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#3717]
Wesnoth v1.14.5 (MP at Official server)
Windows 7 x64

When I played MP games **with ally** (Isar) there was OOS errors in ~50% times. Usually from 1 turn. I am always using planning mode.
![oos_error_planning](https://user-images.githubusercontent.com/10855248/48432999-0d078d00-e787-11e8-8a26-30071b6e96e9.png)

P. S.

There are problems with planning mode from 1.12 at least. Now we have 1.14.5 and problems become more frequent. What's wrong to simple remove mechanism to show ally your planning - I bet that evil is there. **Simple let player do his planning locally w/o any netcode involved!**

I simply could not play w/o planning mode. And I could not understand how other are playing.
It greatly saves time!

**Comment by gfgtdf** [comment]
there were known oos problems with wesnoth versions older than 1.14.5 could you please check what versions to other players in your game use (use the :q version <playername> command)?

**Comment by gfgtdf** [comment]
Also please tell when exactly the post error happens, ( during which players turn, during what action), and attach a replay of the game where the oos occurred

**Comment by amokmen** [comment]
As for me, it happens when my ally taken control.

[4g — Krzyż Isar-Auto-Save2.gz](https://github.com/wesnoth/wesnoth/files/2577584/4g.Krzyz.Isar-Auto-Save2.gz)

**Comment by gfgtdf** [comment]
hmm maybe this is related to using planning mode during your allies turn, did it also happen if you user planning mode only during your own turn?

**Comment by amokmen** [comment]
Probably yes: I usually plan buying units on turn 1. And it could not be my turn, but turn of my ally when OOS errors starts.

**Comment by gfgtdf** [comment]
Hmm ok what i currently think wht happens is that this code https://github.com/wesnoth/wesnoth/blob/1.14.5/src/whiteboard/recruit.cpp#L190 is somehow exceuted in the other client in a synced context so that generates an id which causes oos.

Currently the two ways this could happen the first is that it is exceuted while waiting for a synced choice (here: server random seed). The other is this line https://github.com/wesnoth/wesnoth/blob/1.14.5/src/playmp_controller.cpp#L453 .

**Comment by gfgtdf** [comment]
ok i made a pr for a serversided fix #3720 a clientsided patch should also be done though.

**Comment by amokmen** [comment]
Now again got same errors.

Game starts. Map is Isar. My mate is #1, I am #4. He started buying units and I started "buy" in planning mode. All was OK. But immediatly after he End turn, I get screen with error!

**Comment by amokmen** [comment]
It happens again at Isar. My mate 1.14.5 was side 2, immediately after he end turn, was screen with error.

[Replay](https://replays.wesnoth.org/1.14/20181117/4p__Isars_Cross_Turn_1_(28594).bz2)

**Comment by gfgtdf** [comment]
> It happens again at Isar. My mate 1.14.5 was side 2, immediately after he end turn, was screen with error.

I pushed a comit 1.14 to fix this: https://github.com/wesnoth/wesnoth/commit/c445828e62067749149cc410a7da6c914a714d44 . lt takes effect as soon as the server is restarted, currently waiting for @soliton- to restart it.

**Comment by amokmen** [comment]
Just writing to you more info, if it could help.

How I would know that server is restarted to check it out?

**Comment by gfgtdf** [comment]
> How I would know that server is restarted to check it out?

Hmm i don't think there is a way unfortunteley, but i can repost it here when @soliton-  or @shikadiqueen say they have rebuild it.

**Comment by gfgtdf** [comment]
> Just writing to you more info, if it could help.
> How I would know that server is restarted to check it out?

THe serve was relasted please check whether it still happens.

**Comment by amokmen** [comment]
I played **a few** games today with no errors.

**Comment by gfgtdf** [comment]
@amokmen did you pass more games or do you want to say something else? Otherwise I'd close this now.

**Comment by amokmen** [comment]
Yeap, I played a lot of games, and no more errors.
