### ISSUE TITLE
[message] reveals position of hidden units

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3724]
There was a commit fixing the revealing of units hidden by shroud / fog.

It's also revealed if the unit is hidden due to abilities.

![secret_reveal](https://user-images.githubusercontent.com/21158813/48594012-6a4e3a80-e94f-11e8-91bc-07e7e63cba66.png)
(The map being black is part of some effect)

**Comment by jostephd** [comment]
Works for me in this test case https://gist.github.com/jostephd/ec2a8c24ff68331b1412231e4be74936. Furthermore, even for visible units I never get a _yellow_ hex; I get a green/blue/red hex for own units, ally units, and enemy units respectively.

**Comment by GregoryLundberg** [comment]
https://wiki.wesnoth.org/InterfaceActionsWML#.5Bmessage.5D

Need to use `[show_if]` or `highlight` for these cases

If this is in mainline, please report the error
