### ISSUE TITLE
Check documentation for [core] tag

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3728]
The [[core]](https://wiki.wesnoth.org/CoreWML) page lists among other

`icon: the image displayed in the core selection menu`
`image: the image shown in the information pane when this core is selected in the core selection menu (typically a transparent, 350×350 pixels portrait)`

To my knowledge _icon_ is not used anymore, and _image_ is for providing an icon, i.e. the default core uses a 64x64 one. Can someone verify in the C++ wether this is accurate.

**Comment by jostephd** [comment]
Yes, it's accurate. Cores are parsed here:

https://github.com/wesnoth/wesnoth/blob/4be068696b93b7bcb1df1f9258463a150a2e407a/src/game_config_manager.cpp#L193-L238

and used here:

https://github.com/wesnoth/wesnoth/blob/4be068696b93b7bcb1df1f9258463a150a2e407a/src/gui/dialogs/core_selection.cpp#L94-L118

And as you can see, `"image"` is accessed but `"icon"` is not.

**Comment by sevu** [comment]
Thanks, I updated the documentation.
