### ISSUE TITLE
Make sure schema is up-to-date on any new WML features in master

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3730]
Off the top of my head, the new *_loc options in the MicroAIs come to mind, but it's likely there's a bunch more too.

**Comment by mattsc** [comment]
The new AI features have been added in #3756.

**Comment by CelticMinstrel** [comment]
Probably all that's left then (if anything) is features I added while working on the schema (like new options in `[move_unit]` for example)... so in other words I need to go through all my commits or something.

**Comment by jostephd** [comment]
In general, what's the failure mode if we add a WML feature without adding it to the schema? The feature works but anything that uses it would fail schema validation? Nothing else, right?

**Comment by CelticMinstrel** [comment]
That's correct.

And since the game config is not automatically validated as the GUI config is, that would mean nothing changes unless someone specifically wants to validate it.

**Comment by CelticMinstrel** [comment]
#3920 and #3776 need to be documented in the schema.

I may add others as I think of them or as they pop up.

**Comment by CelticMinstrel** [comment]
Note: I tried to document 3920 and #3776 but might have missed something. If anyone else knows of other new features that aren't accepted by the schema, please add them. Otherwise, this can now be closed.

**Comment by CelticMinstrel** [comment]
I think this might be finished? I'm not quite sure though...

**Comment by stevecotton** [comment]
> And since the game config is not automatically validated as the GUI config is, that would mean nothing changes unless someone specifically wants to validate it.

I think it now is tested (implemented in #3709), so can we close this #3730?
