### ISSUE TITLE
Document new unit ability options

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3735]
A number of new possibilities for unit abilities were recently added by @newfrenchy83, but they haven't yet been documented on the wiki.

**Comment by newfrenchy83** [comment]
I don't see left out except recommandation perhaps, when you use chance_to_hit damage drains etc.. abilities, the developper must think to exclude specials who don't must afected like when you use chance_to_hit value=60 cumulative=no but what you don't want magic specials was affected but else all is here.

**Comment by CelticMinstrel** [comment]
In that case, I guess this can be closed.

**Comment by newfrenchy83** [comment]
i forget to said what backstab option is necessary in abilities because other_unit don't design opponent like in weapon_specials

**Comment by CelticMinstrel** [comment]
I have no idea what you're talking about...

**Comment by newfrenchy83** [comment]
Im wikia the backstab option is said deprecated after 1.13.4 but for weapon like abilities, this option can't be replaced by filter_opponent like in Weapon specials. In specials formula unit point the owner of attack and other his opponent, but in abilities other point unit adjacent to owner and not opponent. It must specifie what backstab option not deprecated for weapon like abilities.

**Comment by CelticMinstrel** [comment]
Okay, I understand what you mean here, but I think it's better to somehow change the mechanics rather than having to update the documentation.

Besides `[filter_opponent]`, is there anything else in [this section](https://wiki.wesnoth.org/AbilitiesWML#Common_keys_and_tags_for_every_weapon_special) that these new abilities do not support? (Or only partially support?)

**Comment by newfrenchy83** [comment]
i don't think but i hope what backstab option don't suppress to c++ if i can't modify the code in formula

**Comment by newfrenchy83** [comment]
[filter_attacker] and [filter_defender] don't supported in new abilities

**Comment by CelticMinstrel** [comment]
So everything other than the four filters is supported?

I'll look into adding support for them in these abilities.

**Comment by newfrenchy83** [comment]
i added https://github.com/wesnoth/wesnoth/pull/3743/files

**Comment by newfrenchy83** [comment]
i added https://github.com/wesnoth/wesnoth/pull/3743

**Comment by newfrenchy83** [comment]
@CelticMinstrel the four filter and option are supported with https://github.com/wesnoth/wesnoth/commit/16927f9508115614fab4fe46f28649982bf49d4b and the fix by @jyrkive  you can close this issue backstab is deprecated for all( i must resign to this).
