### ISSUE TITLE
Scenario leaders incorrectly named as "name"

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#3736]
When starting a campaign, the name of each side's leader is simply "name".  Tested as happening in AToTB and LoW, but I assume it happens on all campaigns.

**Comment by DisherProject** [comment]
@Pentarctagon does the objectives panel show the default win only? ("Defeat all enemy leader(s)")

**Comment by gfgtdf** [comment]
will fix this weekend.
