### ISSUE TITLE
side variabels clashes with leader variables

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3742]
as the title say, in [side] the [variables] tag is interpreted as the sides variables aswell as the leaders [variables] which might casue issues, actually i didn't find any serious problems with that yet though.

**Comment by CelticMinstrel** [comment]
My suggestion is to deprecate the use of unit keys in the `[side]` tag - so, in particular, if a `type` key is found. I think we should instead be putting the leader's details in a `[leader]` tag (which is already supported).

But in addition we should probably just remove `[variables]` from the config before passing it to the unit creator.

**Comment by gfgtdf** [comment]
> so, in particular, if a type key is found. I think we should instead be putting the leader's details in a [leader] tag (which is already supported).

The way it currently works though is to not put a type key on side and put it in leader instead and I think this makes more sense that your suggestion of having type=  in side and ask other leader attributes in [leader].


I wonder whether we should make the sides save_id also default to [leader]id= just like we do currently for id= in [side]

**Comment by CelticMinstrel** [comment]
Um, what? I never suggested putting `type` in `[side]` and everything else about the leader in `[leader]`. I suggested deprecating the use of unit keys in `[side]` and in particular printing a deprecation warning if `type` is found, encouraging the use of `[leader]` instead to specify the side leader.

**Comment by gfgtdf** [comment]
hmm misssread your comment then.

I think currently one of the advantges of pussting everything in [side] is that you don't have to explciitly write save_id (since it defaults to 'id'), any oppinion on adding the same bviousto leader (making side]save_id also defaut to [leader]id= if given) ?

**Comment by CelticMinstrel** [comment]
Hmm, not sure. What if there are multiple `[leader]` tags? I'm not strongly opposed to it though...

**Comment by gfgtdf** [comment]
> Hmm, not sure. What if there are multiple [leader] tags? 

just use the first one i'd say.

**Comment by gfgtdf** [comment]
also i think its likeley that the mp settupcode currentlyhandled leader differntly that inline leader data that also need to be fixed.

**Comment by gfgtdf** [comment]
With https://github.com/wesnoth/wesnoth/issues/7985 [side][variables] it no longer interpreted as the leaders variables,
