### ISSUE TITLE
Submerge problem when zooming

### ISSUE THREAD

**Issue by beetlenaut** [wesnoth/wesnoth#3746]
The part of a unit that is under water is mostly invisible at high zoom levels. There do seem to be a couple pixels of transparency at the border, so maybe the submerge value is not being scaled or is being scaled in reverse.
![submerge_problem](https://user-images.githubusercontent.com/4147859/49075018-d00db280-f1ea-11e8-99cc-5289365001ac.png)

**Comment by Wedge009** [comment]
I remember #1146 as well since it's loosely related to this. Both are related to how units are displayed when in water.

**Comment by Wedge009** [comment]
I wonder if opacity is incorrectly being adjusted by zoom factor (though I can't imagine why this would be done even accidentally). I resolved #5974 by removing multiplication by zoom factor when it wasn't necessary.

**Comment by mesilliac** [comment]
I recently rewrote the submerge code (unrelated to this). I don't see the problem right now, so it's probably fixed. Can anyone confirm?

**Comment by Wedge009** [comment]
I observe the issue in current 1.16.3 release and also confirm it appears resolved in current master (tested at 557738dd495)
