### ISSUE TITLE
Dark Forecast default difficulty is too high

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#3753]
It's just not something the average Wesnoth player can be at all expected to be able to beat.

The randomness of the waves/wave spawn points, the number of units involved, and the types of units that can spawn(particularly the sea serpent and the griffon wave) make it difficult to come up with any sort of plan that won't get thrown out the window more than a couple turns in the future.  The waves at times end up feeling like one long string of "tomato surprises" - griffon riders flying out of the fog and across half the map to kill a level 2 unit in one turn with no warning, enemy waves spawning and completely surrounding a unit that had just claimed a village, etc.

It's one thing for a scenario to be a challenge, but this just isn't fun.

**Comment by gfgtdf** [comment]
There is a difficulty slider though changing the strength of the enemies.

**Comment by Pentarctagon** [comment]
There is, but by default it's exceptionally difficult.  The scenario's mechanics for generating spawns are also just generally not very good.

**Comment by Pentarctagon** [comment]
Closing in favor of #5651 since that one has more details.
