### ISSUE TITLE
Weapon special abilities need to pass other_unit to the filters

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3771]
Currently, the weapon special abilities added by newfrenchy do not pass `$other_unit` to the filters, which means that backstab-style specials do not work in ability form. It should be ensured that the `$other_unit` is the same as it would be if the special were used normally as a weapon special, in order to allow the same macros to be reused in both ways.

The test-case I used to verify that this does not currently work is given below. The general idea is that the shaman confers the backstab ability on adjacent units, so if the fighter attacks the bat, his damage should be doubled. (I tested by adding the code to the tutorial, though I imagine it would work in any scenario.) I'm not quite certain the test is correct, though; it might need a little tweaking.

```
[unit]
    type=Elvish Shaman
    side=1
    x,y=9,7
    [modifications]
        [object]
            apply_to=new_ability
            {WEAPON_SPECIAL_BACKSTAB}
            [+damage]
                affect_self=no
                affect_allies=yes
                [affect_adjacent]
                    race=elf
                [/affect_adjacent]
            [/damage]
        [/object]
    [/modifications]
[/unit]
[unit]
    type=Elvish Fighter
    side=1
    x,y=10,6
[/unit]
[unit]
    type=Elvish Archer
    side=1
    x,y=10,8
[/unit]
[unit]
    type=Vampire Bat
    side=2
    x,y=10,7
[/unit]
```

**Comment by newfrenchy83** [comment]
fixed in https://github.com/wesnoth/wesnoth/pull/3776
