### ISSUE TITLE
EI S02 The Escape Tunnel is too hard on first playthrough

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3782]
The second scenario of _Eastern Invasion_ is very difficult for players who haven't played it before ([FTPR](http://catb.org/~esr/wesnoth/campaign-design-howto.html#_balancing_scenarios)).

For one, the walkthrough and the replays on the forums recommend to _take the southern path_ at the crossroads, even though the map dimensions and Dacyn's dialog imply the player should go east; the winning strategy is a non-FTPR strategy. For two, it's not possible to distinguish between the troll treasure room and the escape tunnel, and with the mass of undead the player sometimes just has to guess which exit to take.

I haven't yet played S3, but for starters I would like to suggest lifting the shroud when the player meets the dwarves. That's a sensible change from a lore point of view since the dwarves are allies in this scenario, and it also addresses another issue about removing the need for the player to scout the amulet's chamber for possible enemies.

@Konrad22 points out that Dacyn should know about the tunnel so the "correct" / "main" path could be shown unshrouded (but ~possibly~ fogged) even in turn 1 and the ~fog~ shroud removed from the dwarves' chamber when they're sighted. The amulet chamber and treasure chamber would remain ~fogged~ shrouded.

edit: Fixed what Konrad said

**Comment by cooljeanius** [comment]
Even with this change I still found it too hard; the main change I made that was the most helpful in helping me beat it was to move Mal-Bakral's arrival from turn 6 to turn 7: https://github.com/cooljeanius/wesnoth_mods/blob/master/campaigns/Eastern_Invasion/02_The_Escape_Tunnel.diff#L66
