### ISSUE TITLE
Lua: set_dialog_callback(): changing callback from A to B within A() causes B() to be called immediately

### ISSUE THREAD

**Issue by edwardspec** [wesnoth/wesnoth#3794]
It may not be a bug, but it's an unexpected behavior:

1. player clicks the button. The button has callback A().
2. A() changes the callback of this button to B() via `wesnoth.set_dialog_callback()`.

Expected result: B() will be used in the future - starting with the next click.
Actual result: B() gets called immediately.

The following testcase demonstrates:
```lua
function reproduce_issue()
	local dialog = { wml.tag.tooltip { id = "tooltip_large" }, wml.tag.helptip { id = "tooltip_large" },
		wml.tag.grid { wml.tag.row { wml.tag.column {
			wml.tag.button {
				id = "bugfinder",
				label = _"Click causes infinite loop"
			}
		} } }
	}

	function callback1()
		wesnoth.log("error", "In first callback")

		-- Expected: next click should be handled by callback2().
		-- Actual: callback2() gets called immediately.
		wesnoth.set_dialog_callback(callback2, "bugfinder")
	end

	function callback2()
		wesnoth.log("error", "In second callback")
		wesnoth.set_dialog_callback(callback1, "bugfinder")
	end


	function preshow()
		wesnoth.set_dialog_callback(callback1, "bugfinder")
	end

	wesnoth.show_dialog(dialog, preshow)
end
```

**Comment by gfgtdf** [comment]
is this master or 1.14 ?

**Comment by gfgtdf** [comment]
does set_dialog_callback actuall remvoe the old callback at all? meaning if you write `wesnoth.set_dialog_callback(callback1, "bugfinder");wesnoth.set_dialog_callback(callback1, "bugfinder")` will callback1 be exceuted once or twice ?

**Comment by edwardspec** [comment]
> is this master or 1.14 ?

master

> does set_dialog_callback actually remove the old callback at all?

No, it doesn't remove it. (just checked)
Callback is called twice.
