### ISSUE TITLE
Unit ellipse displayed at the wrong place while 'Attack Unit dialogue' open

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3795]
This happens when I open and then close a 'window' without closing the Unit Attack dialogue (e.g. Damage Calculation or the Help after viewing a Profile of the units).
It happens exactly after closing said 'window'.

![inkedellipse_li](https://user-images.githubusercontent.com/39015360/50369613-c7658d80-0598-11e9-9f57-6d8fd669c375.jpg)

shadowms guess about the cause:
> So basically I guess the ellipse somehow gets relocated to the attack source location before the Attack Unit dialog is displayed but done so without redrawing the gamemap
> And when another dialog is dismissed while Attack Unit is running the gamemap gets refreshed while in that weird limbo state causing the ellipse to be displayed there
> (Either that or it's the ellipse of a fake unit used for damage calculation -- as in the damage calculation performed during the initialization of the attack data)

**Comment by Wedge009** [comment]
Does this still happen? I couldn't replicate the symptom exactly as described here. What I find is that the ellipse disappears from the source unit, but doesn't appear to be shown at the attacking position any more.

Tested 1.16.9 release and 1.17.18+dev.

**Comment by Konrad22** [comment]
> Does this still happen? I couldn't replicate the symptom exactly as described here. What I find is that the ellipse disappears from the source unit, but doesn't appear to be shown at the attacking position any more.
> 
> Tested 1.16.9 release and 1.17.18+dev.

...sort of? (1.17.18)

![grafik](https://github.com/wesnoth/wesnoth/assets/39015360/1e127744-1e0b-4685-80ce-375ed518077b)
case 1
![grafik](https://github.com/wesnoth/wesnoth/assets/39015360/7e30995b-0a5f-4496-b144-7e8a4a192931)
case 2 (original case)

I can reproduce this for seemingly any unit, I'm just not sure for what units which case happens.

I also remember seeing both the unit and its aftereimage in some cases (1.16), but I don't have an example handy.

**Comment by Wedge009** [comment]
Is this any different to #6960? That one was partly resolved, although there's still #8728 as a side-effect.

ie Is this still an issue in 1.18?

**Comment by Wedge009** [comment]
I rechecked 1.18.0. No ellipse is displayed at all now. I think that's okay, but I can also see a case for restoring it. I'll roll that into #8728.
