### ISSUE TITLE
lua gui2 dialog: hovering mouse over button with tooltip or opening wesnoth.confirm() causes map [label] below the dialog to be drawn on top of it

### ISSUE THREAD

**Issue by edwardspec** [wesnoth/wesnoth#3798]
1) The map has some `[label]` tags (text on several hexes).
2) Player opens a dialog based on `wesnoth.show_dialog()`.
3) This dialog has a button with callback A().
4) Callback A() calls `wesnoth.confirm()` to ask "Are you sure?" question.

Actual result: map labels are drawn on top of the dialog.
Expected: labels should be covered by the dialog.

Screenshot (labels "Weapons trader" and "Jewelry trader" are showing through the dialog):
![lua-gui2-dialog-and-labels](https://user-images.githubusercontent.com/1163218/50407566-739eb280-07eb-11e9-935c-56aa7d4bcd7d.jpg)

The labels are hidden before opening and after closing wesnoth.confirm().
There is another label below wesnoth.confirm(), it is correctly hidden.

**Comment by edwardspec** [comment]
The labels are hidden before opening and after closing `wesnoth.confirm()`.
There is another label below `wesnoth.confirm()`, it is correctly hidden.

**Comment by edwardspec** [comment]
Update: `[label]`s also appear when hovering mouse over buttons with tooltips.
![tooltip-label-bug](https://user-images.githubusercontent.com/1163218/50426689-7cec5580-08a5-11e9-8204-58d27b2f09c2.jpg)

**Comment by gfgtdf** [comment]
> Update: [label]s also appear when hovering mouse over buttons with tooltips.

This is a known issue, but actually I thought this was fixed, maybe the fixed was reverted   as part of the ar-reverting?

**Comment by Wedge009** [comment]
I think I know the issue you're talking about, but I couldn't find it. It may well have been closed previously - I'm pretty sure it's been resolved. I don't have the scenario from the images but the way I tested this for both master and 1.14 is to use the test scenario `wesnoth -t` and open dialogues as available. I didn't find a recurrence of the overlapping label issue, but that's not to say there could be other situations where this is still happening.

**Comment by CelticMinstrel** [comment]
Does anyone remember who fixed it originally? It might've been @jyrkive but I can't remember...

**Comment by gfgtdf** [comment]
hmm the only Realtors issue I could find in the tracker is this one https://github.com/wesnoth/wesnoth/issues/2839

**Comment by Wedge009** [comment]
Hmm, that's not the one I was thinking of. I thought this was one shikadi had taken care of, but I'm probably wrong.

**Comment by Wedge009** [comment]
Seeing this again with 1.14.17, specifically on Ka'lian Under Attack, third scenario of Legend of Wesmere (labels aplenty).

**Comment by mesilliac** [comment]
I believe this should be completely fixed by #6855, can anyone confirm, or is there an easy test case i can try?

**Comment by Wedge009** [comment]
As mentioned above, Legend of Wesmere S3 has labels and I think I confirmed it in the GUI Debug Tools (add-on). Strangely, I don't observe it with 1.16.5 so maybe it was already fixed a while back.
