### ISSUE TITLE
TRoW - Sc5, empty space in dialogue isn't shown

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3799]
![grafik](https://user-images.githubusercontent.com/39015360/50408664-b90faf80-07ec-11e9-9e0a-88f347515977.png)
An empty space seems to be missing there, but looking at the code, there is one, but apparently it is being disregarded. 
https://github.com/wesnoth/wesnoth/blob/a44617c408b335a83e34dff8c289b46e523188f3/data/campaigns/The_Rise_Of_Wesnoth/scenarios/05_The_Oldwood.cfg#L237

**Comment by nemaara** [comment]
![image](https://user-images.githubusercontent.com/13598479/50419771-84a5ee80-0800-11e9-820e-ea22f8a1fb2c.png)

Works fine for me, hmm.

**Comment by Konrad22** [comment]
I got someone else to test this and it works for them as well, so it's apparently not a general wesnoth problem.
I'm playing Wesnoth on Windows 10, downloaded from Steam. The code on my pc for this sentence is the same as it is for @nemaara.

**Comment by Wedge009** [comment]
I observe this with French and English GB but not English US, which is Wesnoth's default, so I suspect it's related the translation string handling. It occurs in both master and 1.14.

**Comment by jostephd** [comment]
It's not about translated strings in general, it's this one string that's wrong. Look:

```
$ grep 'We will help' po/wesnoth-trow/en_GB.po
msgid "We will help. "
msgstr "We will help."
```

The en_GB and fr translations omit the trailing space. We could just re-add the space to the translations, but it's probably better to change the scenario to have no trailing spaces in strings marked for translation. Maybe we should even get pofix to warn if any msgid has leading or trailing spaces.

**Comment by Wedge009** [comment]
Ah, well-spotted. I don't touch the French translations but for en_GB I think my po editor automatically strips trailing spaces. So this is potentially an issue in other translations too, but as you say it's better to solve the root cause, which is the trailing space in the source text.
