### ISSUE TITLE
TRoW - Sc7, allied leader you are talking with belongs to an enemy side (cutscene)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3806]
It's just a cutscene so it's no big deal, but it would be cool if it made more sense.
(The other wose units on the map seem to belong to an enemy side as well.)

**Comment by Konrad22** [comment]
In case someone wants to do something about it, a workaround would be to add another enemy side and place a wose somewhere in the forest, so he'd be invisible for the whole cutscene while allowing for different sides.

**Comment by Wedge009** [comment]
I believe that would still show in the team table, which is what I thought was what you were complaining about in the first place.

**Comment by Konrad22** [comment]
My 'complaint' is about seeing the units on the map and seeing that they are enemy units. ^^

**Comment by Wedge009** [comment]
The side bar isn't active during this story scene so unless you force open the team table how can you even tell they are 'enemies'?

**Comment by Konrad22** [comment]
The lack of the blue 'circle' next to their health bar. :D

**Comment by sevu** [comment]
@Konrad22 Isn't it nicer to have less elements around in a cutscene?

**Comment by sevu** [comment]
(A better <s>workaround</s> way would be to set [scenario]victory_when_enemies_defeted=no) But do we really want them to show the orb?

**Comment by Konrad22** [comment]
It is, but I prefer a ugly workaround instead of an elegant 'wrong' situation.
Yes, why not? It makes more sense that way.
