### ISSUE TITLE
hide revision with scons

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3809]
Scons has no option equivalent to -DENABLE_DISPLAY_REVISION.

The code is [there](https://github.com/wesnoth/wesnoth/blob/1.14/SConstruct#L628), it just misses an option to turn it off.

**Comment by loonycyborg** [comment]
Are there particular use cases to have it as a command line option? By default it does autodetection anyway.

**Comment by sevu** [comment]
The case where I used it with cmake:

When you build a release it shows normally the version number without commit.
If your (distributions) build script lies in a git repository, and you thus build in another non-wesnoth git repository, it picks up this for the commit ID.

On the other hand, other packagers don't get too deep into the options and don't find this one.
