### ISSUE TITLE
When a new unit disembarked,its description didn't appear in "units" of "help".

### ISSUE THREAD

**Issue by gaojicainiao** [wesnoth/wesnoth#3813]
When a new unit disembarked,its description didn't appear in "units" of "help".It shows"Unknown Unit",just likes that I didn't discover it.
I don't know if this is a bug.But I would like to report it.
I'm a Chinese and I'm not good at programming and written English,so maybe I won't relpy.I'm sorry about it.

**Comment by Wedge009** [comment]
First, thanks for your report.

I understand writing in another language is hard. There is an English saying that '1 picture is worth a 1000 words' - do you have a screenshot or image to help explain what you mean? 'Disembark' is usually related to ships - but there are few Wesnoth scenarios involving ships. I just wonder if you are referring to unit recruitment or something else.

**Comment by gaojicainiao** [comment]
I recoeded a video to show the problem.
I uninstalled the game and deleted all data of the game except the saved game.Then reinstalled it.Then I changed Chinese to English and load the saved game to record.
In the video,the disembarked units that I did't discover before has no description in "units" of "help".
So it should be a small problem.Less players will meet it because less boats to bring new units.
Don't worry about the names of the units which show incorrectly,bacause I changed Chinese to English,so the Chinese name can't show correctly,that's not a bug.
Thanks for your working on this game!
[video.zip](https://github.com/wesnoth/wesnoth/files/2712451/video.zip)

**Comment by sevu** [comment]
Which campaign and scenario is this? And are there more scenarios where this occurs?

**Comment by gaojicainiao** [comment]
Black Flag of Son of the Black-Eye.
I don't know if there's more.

**Comment by sevu** [comment]
Thank you. If you want you can the file and add the two lines.

**Comment by jostephd** [comment]
@sevu I think you meant to say that @gaojicainiao can **modify** the file (in his wesnoth data directory) and add the two lines. (You missed a word)

Should a new issue be opened for making units placed via lua (also unit:to_map, etc) add themselves to known units?

**Comment by sevu** [comment]
Ah…indeed.

A new issue would be good, it was the 1st time discussed several month ago in regard to the same case in the tutorial, which is closed now.
