### ISSUE TITLE
TRoW - Sc9, Yetis as allies of undead

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3815]
In this scenario two yetis appear and they are on the same team as the undead (who they are very unlikely to ever get close to). Is there a reason for that?

**Comment by GregoryLundberg** [comment]
Probably easier than setting up a hidden side and making it an ally so they don't immediately attack each other.

**Comment by DisherProject** [comment]
You may be using an old wesnoth version. I fixed this bug [here](https://github.com/wesnoth/wesnoth/commit/8a0490b11124e0b6f57f571db715531a1551d038#diff-3447e6f1f57f2471472b31342cf613a3)

I noticed you have opened some other issues about TRoW: could you please check if they persist on a newer version?

**Comment by Konrad22** [comment]
I'm played TRoW (after Swamp of Esten) on 1.14.5. :/

**Comment by sevu** [comment]
Thanks @DisherProject. A few comments to the commit:

- I think the Yeti side could be hidden until they come into action.
- I don't know the other scenarios, it may or may not be fitting to unhide the side when some units come into action. (with [modify_side] IIRC)
- It's good practice to always add a user_team_name. If the side is always hidden it's still used in debug mode (e.g. with :inspect), and it helps if someone decides to unhide the side.
- In case you load the scenario, feel free to change the color too.

**Comment by GregoryLundberg** [comment]
@sevu You probably want to re-open this or create an Issue for your comments since it's unlikely anyone will search for a closed issue for 1.14.6

**Comment by nemaara** [comment]
@sevu Correct me if I'm wrong, but I think all of your comments have been addressed now? If so, could we maybe close this issue?
