### ISSUE TITLE
TRoW - Sc14, apparently Sea Serpent event isn't working properly

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3818]
I'm going entirely by memory and my recent WoV playthrough regarding the way the event is 'supposed' to happen.
Only two out of three Sea Serpents 'appear', only one of them really appearing, the other one is apparently being recalled instead.
(The first Sea Serpent 'appears' in turn 10.)
[TRoW-Rough Landing replay.gz](https://github.com/wesnoth/wesnoth/files/2716833/TRoW-Rough.Landing.replay.gz)

A possibility:
There was 'place' were the blue and the green Sea Serpent could be placed, so instead it was placed in the recall list of the side. And since the blue leader had already been dead, the blue Sea Serpent never appeared. (I ran into something similiar [here](https://forums.wesnoth.org/viewtopic.php?p=635855#p635855).)

Note: As WoV lifted this event, any fix for this should be applied to WoV as well.

**Comment by nemaara** [comment]
It seems like @DisherProject fixed this a while ago with commit 5e2ccd911b46872c7cbaa33e26311b754075f5d2. What was happening was that borders were being included in the location filter, so sea serpents could spawn in the border (where they could not move) and were being automatically placed in the recall list. New filter doesn't include borders, so now that can never happen.
