### ISSUE TITLE
TRoW - Sc15, full end of scenario dialog happens when one of your leaders dies

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3819]
The scneario 'ends' once the first unit dies. This could be one of your leaders, triggering the (lengthy) end of scenario dialog, only afterwards resulting in you losing the scenario. If found out by having Haldric die and I'm just assuming that the same is true for Jessenes or Typhons death.
[TRoW-A New Land Turn 10.gz](https://github.com/wesnoth/wesnoth/files/2716835/TRoW-A.New.Land.Turn.10.gz)

**Comment by Wedge009** [comment]
True, the losing condition should take priority over the end of scenario dialogue. Depending on how you play it seems unlikely this should happen (clearly no-one really noticed this in play-testing - but this also reminds me of a rather amusing scenario: #3072) but obviously it's still possible and ideally should be resolved.

**Comment by nemaara** [comment]
Addressed by b222c33.
