### ISSUE TITLE
Маркеры карты (метки)

### ISSUE THREAD

**Issue by ak72ti** [wesnoth/wesnoth#3820]
solluxander#6501 - says, "i can translate issue for you"
Метки карты неудобны, словно сломаны, ими невозможно активно пользоваться, хотя они в принципе куда более перспективны чем стандартный чат, если речь заходит о ролевой игре.

1.Поле ввода представляет из себя одну мизерную строчку на 20 символов, чего не хватает для нормальных меток, а так же чтения длинных меток, уходящих за грань видимой зоны на карте. Прошу, сделайте зону ввода нормального размера с переносом на следующую строку.

2.Метка представляет из себя крайне не стабильную надпись на карте, пожалуйста, сделайте так, что бы игроки могли удалять метки только у себя, либо только свои, оставляя остальные, поскольку иначе во первых, игрок не может отредактировать свою метку, если написал её в то время как другой нажал на кнопку УДАЛИТЬ ВСЕ МЕТКИ, а так же игрок не может просто прочитать метки которые адресованы ему от других игроков на больших картах, из-за случайных удаления других игроков, нажавших не на ту кнопку, либо намеренно желающих удалить метки у себя с экрана. 

3.Пожелание так же, сделайте метки привязанными к единицам, если это возможно, или нормальные облачки для ответов, это помогло бы куда интереснее сделать диалоги не убивая ход в мультиплеерных компаниях, где кто то отошел, а в это время закончился таймер. Но это уже пожелание а не issue, первые два пункта действительно мешают играть мне и моим друзьям, если вы не в состоянии их починить в ближайшее время, дайте хотя бы подсказку как сделать это самостоятельно. Спасибо за внимание и перевод. 

Мы используем метки для удобной ролевой игры в рамках Battle For Wesnoth, мы уже сейчас пользуемся метками для этого, очень часто, тысячи и тысячи символов улетают в трубу из-за неосторожных действий игроков, которые случайно удаляют все метки на карте для всех остальных и для себя в том числе. Пожалуйста, почините это.

**Comment by CelticMinstrel** [comment]
Duplicate of #3821 for the record.
