### ISSUE TITLE
wesnoth hangs on start when built with homebrew

### ISSUE THREAD

**Issue by equal-l2** [wesnoth/wesnoth#3823]
When I build wesnoth from source with cmake, it builds successfully, but when I run `wesnoth`, it doesn't open a window or emit any message.
FYI it builds and runs successfully if I use Xcode project.

Environment:
Wesnoth master
macOS 10.14.2
Boost 1.68.0
Cairo 1.16.0
Pango 1.42.4
SDL 2.0.8
SDL_image 2.0.4
SDL_mixer 2.0.4
SDL_ttf 2.0.14
(All dependencies are from Homebrew)

**Comment by GregoryLundberg** [comment]
Not sure we actually support SCons and/or CMake on macOS.

XCode works so I'd say this is very low priority.

I'd take a quick look at it, but my macOS VM is down waiting for me to get around to wiping and upgrading to the latest and greatest. IIRC, however (it's been a year or two), there are a few dependencies which cannot use Homebrew and must is the official Apple libraries.

**Comment by jyrkive** [comment]
We have automated SCons builds on macOS, see https://travis-ci.org/wesnoth/wesnoth/builds/473368418 However, the build merely tests that the game builds; it doesn't run any unit tests.

**Comment by EricFromCanada** [comment]
Homebrew maintainer here, attempting to update the [`wesnoth` formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wesnoth.rb) to the latest version. While it builds fine using CMake, it still hangs when running the binary, even with what should be a simple command like `wesnoth --help`. This is what I have so far:

```
class Wesnoth < Formula
  desc "Single- and multi-player turn-based strategy game"
  homepage "https://www.wesnoth.org/"
  url "https://downloads.sourceforge.net/project/wesnoth/wesnoth-1.14/wesnoth-1.14.7/wesnoth-1.14.7.tar.bz2"
  sha256 "475e6ce3720edf76cfc3a9b9ac015067d473a46d164dcc4406b3c8f7d8dc5e48"
  head "https://github.com/wesnoth/wesnoth.git"

  bottle do
    sha256 "2edf0d0aefea381bb679a1530ad07029ba01c0fbf28ac61ca84e229b07263c64" => :mojave
    sha256 "13978002d0394113986b5afd21a521dbbe20dde151c43cff0765b3513e9238ec" => :high_sierra
    sha256 "48457b031fc7b69e86ac34f912031957cf53f76f1b6767f3a22f0b4f1071c3f5" => :sierra
  end

  depends_on "cmake" => :build
  depends_on "gettext" => :build
  depends_on "pkg-config" => :build
  depends_on "boost@1.60" # Next release should support latest version
  depends_on "cairo"
  depends_on "fontconfig"
  depends_on "freetype"
  depends_on "fribidi"
  depends_on "gettext"
  depends_on "glib"
  depends_on "libffi"
  depends_on "libvorbis"
  depends_on "pango"
  depends_on "readline"
  depends_on "sdl2"
  depends_on "sdl2_image" # Must have png support
  depends_on "sdl2_mixer" # The music is in .ogg format
  depends_on "sdl2_ttf"

  def install
    args = std_cmake_args + %W[
      -DENABLE_GAME=ON
      -DENABLE_SERVER=ON
      -DFIFO_DIR=#{var}/run/wesnothd
      -DCMAKE_CXX_STANDARD=14
      -DEXTRA_FLAGS_CONFIG="-pipe"
    ]

    mkdir "build" do
      system "cmake", "..", *args
      system "make", "install"
    end
  end

  test do
    system bin/"wesnoth", "-p", pkgshare/"data/campaigns/tutorial/", testpath
  end
end
```

**Comment by soliton-** [comment]
Perhaps you can get a backtrace when it hangs.

Since not even `wesnoth --help` outputs anything(?) I can only imagine some issue with SDL and its business of replacing `main()` or some other early initialisation.

If you can't get a backtrace you could add some debug printf's around here:
https://github.com/wesnoth/wesnoth/blob/23f74d97815eb4690fceb729a76a2aff32015a70/src/wesnoth.cpp#L1017-L1045

**Comment by Pentarctagon** [comment]
Given this is only an issue when using homebrew, and not when using xcode+macOS or on Windows/Linux, this seems like it's an upstream issue?

**Comment by equal-l2** [comment]
According to printf debug, the app hangs before getting to main application code.
It hangs at L.120 of the following code:

https://github.com/wesnoth/wesnoth/blob/ff18f2aecf39221fca62c4719ba54ed0acb310cc/src/macosx/SDLMain.mm#L116-L122

**Comment by soliton-** [comment]
Since it appears to also be an issue for openttd which seems to use SDL as well I'm going to guess it's an issue with how SDL is built in homebrew or how the SDLMain business works there. Either way it indeed sounds quite like an upstream issue that we cannot fix in our codebase.

**Comment by EricFromCanada** [comment]
Doubtful, since OpenTTD was updated in a [later pull request](https://github.com/Homebrew/homebrew-core/pull/50063) and Homebrew has several SDL-based apps that don't exhibit this issue. But, the `wesnoth` formula having since been [removed](https://github.com/Homebrew/homebrew-core/pull/48158) from homebrew/core makes this issue irrelevant.

**Comment by Pentarctagon** [comment]
Closing, in that case.
