### ISSUE TITLE
Missing tooltip for 'vision' in sidebar

### ISSUE THREAD

**Issue by Samonella7** [wesnoth/wesnoth#3824]
When a unit's vision is different than its max moves (which is very rare) an entry for 'vision' appears in the sidebar, next to its XP. On low resolution, most of the entry is truncated. Most entries in the sidebar have hover-over tool tips, but there isn't one for 'vision' so there's no way for players to see what the unusual entry means (or what the unit's value for vision is).

![vision](https://user-images.githubusercontent.com/21229771/50553946-21d8ab00-0c77-11e9-93e4-9c0035eaffb6.png)

**Comment by jostephd** [comment]
Already fixed for 1.14.6: efba33410ea6c683422bd2f6bd25505cce18644b.
