### ISSUE TITLE
[unit_type][variation][event] not working if [modifications] is used

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3827]
Based on UnitTypeWML, [variation] supports "All keys and tags of [unit_type], except [advancefrom], [base_unit], [female], [male], and [variation]."

However, adding [event] under [variation] does not usually register that event.

Testing done for https://github.com/inferno8/wesnoth-Era_of_Magic/issues/16#issuecomment-407919971 suggests that adding extra [modifications] to unit is what breaks adding events - creating [unit] with variation=name works, but adding object to change variation does not. Even empty [modifications][/modifications] inside [unit] is enough to break registering event.

**Comment by ProditorMagnus** [comment]
https://github.com/ProditorMagnus/Ageless-for-1-14/issues/1

**Comment by gfgtdf** [comment]
In the an advantage of putting the [event] inside variation instead of putting it into the parent unit_type? Otherwise I'd support not fixing this (at least for 1.14) and just update the wiki to make users put their events into [unit_type] to prevent oos with older 1.14 versions.

**Comment by ProditorMagnus** [comment]
In current case the advantage would be not adding abilities and specials to parent type, which can sometimes appear without variation.
Which is why I created dummy unit type to hold the abilities and specials.

**Comment by ProditorMagnus** [comment]
Then I would need more code duplication, events are in ability macro with +tag.

**Comment by ProditorMagnus** [comment]
Most likely caused by WML merge logic between tags of regular unit and tags of variation.

**Comment by ProditorMagnus** [comment]
Closing in favor of #7486.
