### ISSUE TITLE
Units movement animation is broken

### ISSUE THREAD

**Issue by slavrenyuk** [wesnoth/wesnoth#3831]
I found a bug, at least related to several units. When unit moves, some sprites are skipped. But if I undo the movement action, all sprites are shown when unit goes back.

Game version 1.14.5
OS Microsoft Windows 10 (10.0.17134)

Confirmed by @jostephd on 1.14.5 and master on Linux.
Topic on the forum https://forums.wesnoth.org/viewtopic.php?f=4&t=49180

**Steps to reproduce**
- In general preferences set acceleration factor = 0.25 (the bug is not related to acceleration, but it would be easier to detect).
- In the main menu choose "Multiplayer".
- Select "Local Game".
- Create a map without fog and shroud (to be able to undo your actions).
- Take Drakes faction (it is easier to observe the bug because of their large wings).
- Create a flying drake, move it to some distant hex.
- While it flies, pay attention to its wings. The cycle of movement is not full.
- Undo the action and compare the animation (I observed correct animation during undo).

**Comment by jostephd** [comment]
Fixed by #3919 #3921 by @madmax28 and @gfgtdf.
