### ISSUE TITLE
FR: allow [modify_side] to change village_gold

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3833]
According to the [documentation](https://wiki.wesnoth.org/DirectActionsWML#.5Bmodify_side.5D) [modify_side] can't change _village_gold_, though it can change _village_support_.
 I guess there's no reason why it shouldn't be able to set both.

**Comment by ProditorMagnus** [comment]
https://github.com/wesnoth/wesnoth/blob/1.14/data/lua/wml/modify_side.lua#L39

**Comment by ProditorMagnus** [comment]
And documentation has both village_gold and village_support.

**Comment by sevu** [comment]
…

**Comment by CelticMinstrel** [comment]
(For the record, the cited line alone is not enough to prove that it's possible in the engine; you'd also need to check in the C++ source whether the side metatable accepts that key as valid. But I'm guessing it does in this case.)
