### ISSUE TITLE
TRoW - Sc17c, Burin describes trolls as green

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3836]
https://github.com/wesnoth/wesnoth/blob/f34f0c1006f8c586b922f9c9470fe13fe1f8e0be/data/campaigns/The_Rise_Of_Wesnoth/scenarios/17c_Troll_Hole.cfg#L268
Probably a relic from a time long past.

http://zapicm.freeshell.org/1_02/tree_troll.html

**Comment by Konrad22** [comment]
Btw, why are there so many sides in this scenario? 3 would have been enough, right?

**Comment by nemaara** [comment]
Fixed by https://github.com/wesnoth/wesnoth/commit/afad68aebc8c3996ed1b529787b2134fbc51bf7d. The sides are to randomize where the trolls spawn and to turn the remaining two into spiders.
