### ISSUE TITLE
Crash or Lua error after 'breaking' progress tracker 

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3838]
Break the journey tracker(?) as described in #3837 and press Esc before the journey tracker has reached the final destination. Now, either the Lua error turns up or the game crashes.
![lua2](https://user-images.githubusercontent.com/39015360/50719144-4cbc6800-1098-11e9-8494-6c2be017bb7f.png)

**Comment by gfgtdf** [comment]
this is actually UB, as std::string is not guaranteed to throw an exception in that case.

**Comment by Wedge009** [comment]
I wonder if this has already been resolved. I could only replicate this issue on the 1.14.5 release - at least the '48bd45d-Modified' that's in Steam and seems to be the same as what Konrad is using. Current 1.14 branch (as at 31c3e6a8) as well as master don't appear to be affected.

**Comment by Konrad22** [comment]
Do you mind if I confirm it for 1.15.1 instead?
![grafik](https://user-images.githubusercontent.com/39015360/64843600-cfbd9700-d605-11e9-94d1-fad185404700.png)

**Comment by Wedge009** [comment]
Whatever works for you. ~~Are you saying it's happening on 1.15.1?~~ Only just saw the screen shot - huge images are slow for me, sometimes cropping or using JPEGs when details aren't needed helps.

What did you do to get this error?

**Comment by Konrad22** [comment]
I followed the steps described in my first post.

![grafik](https://user-images.githubusercontent.com/39015360/64843897-989bb580-d606-11e9-85d3-b114fd66a21b.png)
And that's 1.14.7 for the same scenario.

**Comment by Wedge009** [comment]
I meant the details - like which scenario. I tried do the same for myself and don't get any problems, otherwise I wouldn't have asked you to reconfirm the issue.

**Comment by Konrad22** [comment]
The first post is HttT 5b, the recent reconfirmation is SotBE S3, both from the scenario start file.

**Comment by Wedge009** [comment]
I couldn't replicate this for HttT Isle of the Damned, it looks like it's changed a lot since when you first reported it.

I also couldn't replicate this for SotBE Towards Mountains of Haag.

I tested both 1.14.7 release and 1.15.1+dev. I wonder: do you still get this problem if you clear your data cache?

**Comment by Konrad22** [comment]
I do get this problem after clearing the data cache. Both 1.14.7 and 1.15.1. Steam version.

1.14.7 for SotBE 3: I used debug mode to 'choose level'
1.15.1 for SotBE 3: I've  loaded a file from 02.09.2019

**Comment by gfgtdf** [comment]
i also get this problem on 1.15.1+dev

**Comment by Wedge009** [comment]
What am I missing? How do I replicate this? I did include the 'use left to restart the tracking animation' in my testing.

**Comment by gfgtdf** [comment]
what i did:

1) Start Sotbe
2) :debug, :cl to scenario 3
3) pres sleft arrow to restart.
3) press esc.
4) crash.


But as noted before, this is UB, not an exception to the behviour is undefined and might also show in a different form to you.

**Comment by gfgtdf** [comment]
I think you can increase the chance of crash by pressing the left arrow multiple times.

**Comment by Wedge009** [comment]
That's pretty much what I did last time, including the 'multiple left arrows'. I just retried it again, on 1.15.1+dev, still nothing unusual...

**Comment by gfgtdf** [comment]
as i said it's UB, it might crash or it might not crash, maybe your compiler arragens the cod in a way that makes it less likely to crash.

@matthiaskrgr  maybe you could run an UB check on this one?

**Comment by Wedge009** [comment]
Okay, I can replicate this fairly reliably against SotBE S3 now, but _only_ in my Linux builds and _only_ if I select skip (or press Esc) after doing the 'multiple left arrows' thing. But I don't get the Lua error, I only get the crash with the message `LLVM ERROR: out of memory Aborted`. This happens on both 1.15.1+dev and 1.14.8+dev.

**Comment by gfgtdf** [comment]
> But I don't get the Lua error, I only get

Yesi also get a randomly selected mesage everytime, sometimes its a segfault, sometime a lua error, sometimes out of memory. As i said its ub.

**Comment by Wedge009** [comment]
For me it's pretty consistent, though. Weird.

**Comment by Wedge009** [comment]
Not that I was able to replicate the issue reliably previously, but it seems to be resolved. That was awfully quick, thanks.
