### ISSUE TITLE
TRoW - Sc17d, Undead do not fade away after killing Midnight Queen

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3839]
Haldric says that the Undead fade away after her death. It would be nice if this was backed up by an event.

**Comment by Konrad22** [comment]
That does make me wonder about the Bats. Why do they disappear as well?

**Comment by DisherProject** [comment]
One could imagine they are fleeing because nobody is controlling them anymore (even though Haldric doesn't say it).
Otherwise, adding a filter to that [kill] tag should be quite easy.

**Comment by Wedge009** [comment]
b911e9a1 was accepted - does this mean this is resolved? Or do you want to keep this open till the bats question is dealt with?

**Comment by Konrad22** [comment]
Keeping it open till the bats question is dealt with.
I'm rooting for a filter.

**Comment by nemaara** [comment]
Addressed by c5fbea5.
