### ISSUE TITLE
EI S2 The Escape Tunnel: Doesn't Dacyn know where the tunnel leads?

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3848]
From https://github.com/wesnoth/wesnoth/pull/3797#discussion_r243845070

In EI S2, when the undead arrive, Dacyn says:

https://github.com/wesnoth/wesnoth/blob/649f2b8a3a0e29c496fec73c421d77e520ae7199/data/campaigns/Eastern_Invasion/scenarios/02_The_Escape_Tunnel.cfg#L427-L430

but part of the in-world rationale for the changes in #3797 is that Dacyn knows where the tunnel leads, and he does say earlier "these caves are currently inhabited by trolls" before the party sights the trolls, so shouldn't he be more confident as to where the tunnel's exit will be?

**Comment by nemaara** [comment]
How about this edit?

`        [message]
            speaker=Dacyn
            message= _ "They follow us... we must travel east to escape through this tunnel. That is unfortunate, for it will take us into the Estmark hills, beyond the borders of Wesnoth. But it is our only option."
        [/message]`

**Comment by jostephd** [comment]
I like how in the revision Dacyn knows that the tunnel's exit will be to the east, but "travel east to escape through this tunnel" doesn't sound quite right to me. Once they've entered the tunnel, the possible directions they could take are no longer given by a compass rose (as on the surface) but by the topology of the cave system, notwithstanding that Dacyn will bring them back to the surface at a location to the east of the outpost.

**Comment by nemaara** [comment]
Changed to `message= _ "They follow us... we must escape through this tunnel. That is unfortunate, for it will take us into the Estmark hills, beyond the borders of Wesnoth. But it is our only option."` with josteph's approval. Closing this issue since it should be resolved (see https://github.com/wesnoth/wesnoth/commit/6a7ad942596438c3d6e23b2eb8aaa99d99600b64).
