### ISSUE TITLE
Crash when assigning side to additional team

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#3849]
Steps to reproduce:
1) Go to any scenario with more sides than teams.
2) Uncheck "Use Map Settings".
3) Assign a side to a team not initially listed in the Game Lobby screen.

For example, in Bath of Glory, assign side 4 to Team 4.

Backtrace:
https://pastebin.com/xHdReEDu

Reported for 1.14 [here](https://forums.wesnoth.org/viewtopic.php?f=4&t=49239), and I can reproduce on master as well.

**Comment by jyrkive** [comment]
The crash occurs in this line: https://github.com/wesnoth/wesnoth/blob/c157fc8a9990e887066596c62d405871c88230ce/src/gui/dialogs/multiplayer/mp_staging.cpp#L414

`team_tree_map_[side->team_name()]` returns a null pointer.

I think that the team is not present in `team_tree_map_`. Thus, the indexing operator creates a new entry in the map with the default value, which is null pointer for pointer types.

**Comment by jyrkive** [comment]
I believe this crash is a regression caused by commit 1b4cd8195b063f89fcce73620c12bb007f116eb6 from @Vultraz .

**Comment by jostephd** [comment]
@jyrkive For me it segfaults on 1.14 even if I revert that commit locally.

**Comment by jostephd** [comment]
I opened #3853 to fix this, could I have a second pair of eyes over it before I merge?

> I think that the team is not present in `team_tree_map_`. Thus, the indexing operator creates a new entry in the map with the default value, which is null pointer for pointer types.

Exactly.

**Comment by Vultraz** [comment]
There must have been something missed in the backport. I'm almost certain it worked when I made that commit.

**Comment by jostephd** [comment]
I compared the old master, new master and 1.14 commits and they were identical.
