### ISSUE TITLE
Backport ThemeWML changes

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3852]
#3731 made several changes to the sidebar.

Two of them have been backported: 

- [x] 02a43389249 Sidebar: Reformat trait tooltip
- [x] 8cbe2a28593 Default theme: Make alignment and abilities wider.

Four have not:

- [ ] 4aebb78d744 ThemeWML: Update unit_defense and selected_unit_defense
- [ ] f4efc7ba3f2 ThemeWML: Make highlighted_unit_weapons fall back to unit_weapons rather than to nothing.
- [x] c8162964c65 ThemeWML: Add selected_tod_stats and selected_time_of_day reports.
- [x] e9373c8a6d5 ThemeWML: Implement tod_stats more similarly to other reports.

I'm not certain whether these four changes should be backported. Should they?

edit: Not a ThemeWML change, but:
- [ ] 999e42e524a Help: Show XP for units with modification advancements only (including max-level units with AMLAs)

edit: Another one:
- [ ] 7622dc33587 unit_moves: Show the predicted unit moves, not the current ones

**Comment by CelticMinstrel** [comment]
I have no particular objection to backporting them. I guess maybe c816296 is new API and thus shouldn't be backported, but I imagine there's still a possibility that ThemeWML may get removed on master, so I wouldn't mind backporting it anyway.

**Comment by CelticMinstrel** [comment]
So you decided not to do the unticked ones? Or did you do them but not tick them?

**Comment by jostephd** [comment]
I backported only the first two.

**Comment by CelticMinstrel** [comment]
Wait, did you not backport c816296 and e9373c8 then? I thought the tick meant they were backported...

**Comment by jostephd** [comment]
No, I didn't. I've cleared the tick marks.
