### ISSUE TITLE
TRoW - Sc22, Lua error at start of turn 19 (Cuttle Fish failed to destroy bridge)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3855]
Nothing happened, but I guess something was supposed to happen. I'm playing on hard.
![](https://cdn.discordapp.com/attachments/259976436490829825/532167325143793675/lua_e.png)

**Comment by Konrad22** [comment]
Weirdly enough, on turn 24 a fourth Cuttle fish appeared and destroyed the bridge. He had the same name as the third one. ._.

**Comment by nemaara** [comment]
There is a unit at 42,21 that blocks the cuttlefish from spawning there, so it spawns at 41,31 instead. However, the animation expects the cuttlefish to be at 42,31 (or at least somewhere adjacent to 41,31), so it fails if something is blocking the cuttlefish from spawning there. 

Does https://github.com/wesnoth/wesnoth/pull/3894 address this suitably to you? What it does is it removes the facing filter for cuttlefish that attack from the se (so they face the nw, the default direction when they attack) and adds the ne direction for the other one. If they do spawn anywhere besides the specified location, they won't appear to attack the bridge, but at least it's better than having an error pop up.

**Comment by Konrad22** [comment]
It's certainly good enough, but it would be probably better if there was some event that fires if you block the cuttlefish, like Mal Jevyan being mad at me for foiling the destruction of the bridge. But I think that's something for a later version.

**Comment by nemaara** [comment]
I merged #3894, so closing this issue now.
