### ISSUE TITLE
TRoW - Sc22, missing defeat condition which is handled badly

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3856]
The whole plan would fail if I killed Jevyan before he kills Commander Aethyr. There is no defeat condition that covers this case.
Also, if you actually do that and there is only one orc leader left, he will say 'the elfses have the ruby' and flee.

**Comment by DisherProject** [comment]
I tried fixing this [here](https://github.com/wesnoth/wesnoth/commit/dd24dd6b6e2a3a7837bff6da548d6d2b26ee92a5#diff-258ed147403dbd1e8dca5df04f639d24). Could you please check whether the error persists despite these changes?

**Comment by Konrad22** [comment]
I have really no idea how to do so. :/

**Comment by Konrad22** [comment]
The fix works for me.
