### ISSUE TITLE
Game crash in multiplayer lobby

### ISSUE THREAD

**Issue by FranPrin** [wesnoth/wesnoth#3859]
I'm getting an odd problem and was wondering if anyone else has?

In the multiplayer lobby if I join a game that has add-ons that I don't have then it says "connnecting to add-on server" and attempts to connect.

If, however, I press 'cancel' while it is connecting to the server the entire game dies instantly. This happened twice yesterday and the log files say "Caught unspecified general exception. Terminating."

I don't know if this error has already been reported but it is pretty severe to have the entire game die.

I am using the latest wesnoth 1.14.5 btw

**Comment by jostephd** [comment]
Confirmed on latest 1.14 from git.

**Comment by gfgtdf** [comment]
This means someone forgot to make their exception derive from std::exception

**Comment by jostephd** [comment]
It's throwing addon_client::user_disconnect, but if I make it derive from std::exception it's still only caught in main(). Haven't looked further yet.

**Comment by gfgtdf** [comment]
yes, the actual bug I'd not catching it should also be fixed, but all classes that are thrown should derive from std::exception to make debugging easier.

**Comment by hrubymar10** [comment]
I **can** reproduce on `origin/1.14`: 6c128f30e27  :

```
The Battle for Wesnoth version 1.14.5+dev (6c128f30e27-Modified)
Running on Apple macOS 10.14.4 (18E194d)

Game paths
==========

Data dir:        /Users/USER/xcode/wesnoth_1.14/projectfiles/Xcode/Build/Products/Debug/The Battle for Wesnoth.app/Contents/Resources
User config dir: /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14
User data dir:   /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14
Saves dir:       /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/saves
Add-ons dir:     /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/data/add-ons
Cache dir:       /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/cache

Libraries
=========

Boost:     1.69
Cairo:     1.16.0 (runtime 1.16.0)
Pango:     1.40.1 (runtime 1.40.1)
SDL:       2.0.9  (runtime 2.0.9)
SDL_image: 2.0.4  (runtime 2.0.4)
SDL_mixer: 2.0.4  (runtime 2.0.4)
SDL_ttf:   2.0.15 (runtime 2.0.15)

Features
========

Experimental OpenMP support:    no
JPG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: no
Cocoa notifications back end:   yes
```

**Comment by hrubymar10** [comment]
Closing by 856183067f0999e228338c4ebf402165b198fbf6
