### ISSUE TITLE
wmlparser3 creates separate AttributeNode after textdomain change

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#3862]
Given unit_type fragment of
```
    description= {AE_ARC_UNIT_NOTICE}+_ "

"+{SPECIAL_NOTES}+{SPECIAL_NOTES_POISON}+{SPECIAL_NOTES_SUBMERGE}
```
expanded and wrapped with [units][unit_type] as
```
[units]
[unit_type]
    [resistance]
    [/resistance]
#textdomain wesnoth-Ageless_Era
		description=_"This unit is from the Archaic Era. Its coding and art were done by doofus-01.

" +
#textdomain wesnoth-Archaic_Era
			_"

" +
#textdomain wesnoth-help
			_"

Special Notes:" +
			_" The victims of this unit’s poison will continually take damage until they can be cured in town or by a unit which cures." +
			_" This unit can move unseen in deep water, requiring no air from the surface."
[/unit_type]
[/units]
```
Gives 3 AttributeNode-s: "description", "\_" and "\_". Image after adding \_\_str\_\_() to some wmlparser3 classes: https://vgy.me/c55sZD.png

This means that the other fragments of description are not recognized as description. Evaluating "n.get_text_val("description")" from previous image returns 
```
This unit is from the Archaic Era. Its coding and art were done by doofus-01.

#textdomain wesnoth-Archaic_Era
```
The other fragments can be queried with "\_" key, but there is no indication from which key they actually are.

**Comment by LovCAPONE** [comment]
A [pull request](https://github.com/wesnoth/wesnoth/pull/3902) fixing this issue was submitted.

**Comment by LovCAPONE** [comment]
> With the pull request, result is much better. Though "_" are still part of description.
> 
> ```
> This unit is from the Archaic Era. Its coding and art were done by doofus-01.
> 
> _
> 
> _
> 
> Special Notes:_ The victims of this unit’s poison will continually take damage until they can be cured in town or by a unit which cures._ This unit can move unseen in deep water, requiring no air from the surface.
> ```

Ok I'm on it.

**Comment by ProditorMagnus** [comment]
Remember that this one was not merged.

**Comment by LovCAPONE** [comment]
> Remember that this one was not merged.

Yeah I was waiting for a team member to give it the green light.

So I can go ahead and merge it?

**Comment by ProditorMagnus** [comment]
This pull request has 5 commits, so I would create different one to make sure its clean.

**Comment by LovCAPONE** [comment]
@ProditorMagnus Oh by the way I made a new [pull request](https://github.com/wesnoth/wesnoth/pull/3910) for this issue. So I think the new one is proper and we can close this pull request.

**Comment by ProditorMagnus** [comment]
Yes, that one looks good.
