### ISSUE TITLE
Document gettext/boost::locale mutex

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3868]
src/gettext.cpp uses a mutex to protect various function calls:

https://github.com/wesnoth/wesnoth/blob/8cbc3a4477d34fbb414877d84d59e805055d832c/src/gettext.cpp#L47

We should document in source code comments why the mutex is needed and which functions should call it. Some info is here:
https://github.com/wesnoth/wesnoth/pull/3847#discussion_r247317865

**Comment by cooljeanius** [comment]
`git blame` says that @gfgtdf added it in b780da4 in order to fix #2013

**Comment by cooljeanius** [comment]
PR #7207 will close this
