### ISSUE TITLE
unable to save game

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3877]
after running `wesnoth.set_variable("_a.a", true)` saving the game fails with 'Game state is corrupted'. This si becasue the accepted tagnames are stricter than the accepted variablenames (dont allow underscores as first chracter) and wesnoth.set_variable uses always the name check for attributes.

See also https://github.com/wesnoth/wesnoth/commit/3bc36efa5898a95ce793195e24b4dee1b546c222 where that check was added and the referenced issue.

**Comment by jyrkive** [comment]
I'm glad to see that the protection from saving invalid WML is working as intended. This is much better than agreeing to save the game but failing to load it afterwards.

`wesnoth.set_variable()` should just reject variable names which aren't valid WML tag names.

**Comment by gfgtdf** [comment]
> wesnoth.set_variable() should just reject variable names which aren't valid WML tag names

yes I agree. But it already had such a check but that check assumes valid tag names are the same as valid attribute names. ( which it isn't valid tag names are not allowed to start with _). I think it'd be both easier to implent and also easier to understand for users if they were the same. Do you remember why you disallowed _ as the first character in tag names. In the commit linked above?

**Comment by jyrkive** [comment]
The WML parser can't parse tags which begin with underscores. It's discussed in #2375, especially https://github.com/wesnoth/wesnoth/issues/2375#issuecomment-359039543

Here are some unit tests about the tag names the Lua API accepts (targeting full parity with the WML parser): https://github.com/wesnoth/wesnoth/blob/master/data/test/scenarios/test_lua_wml_tagnames.cfg

**Comment by gfgtdf** [comment]
you said that you only tested with `[_]` but a look at the code makes it likely that it will behave differently depneding on _ is followed by and aphanumerical chracter or not. See

https://github.com/wesnoth/wesnoth/blob/674fda85b7d74ea45d7db4ef842616097b58f0a1/src/serialization/tokenizer.cpp#L131

For the `[_]` case i think we can just replace that isalnum with a isalnum || peek_char() == '_' in the same line.

**Comment by jyrkive** [comment]
Ah, you're right. It looks like the WML parser can indeed parse tags which begin with underscores, and only `[_]` (underscore _by itself_) is an invalid tag.

Well, inability to create WML tags which begin with an underscore **with Lua** is already a part of the API. But I can relax the safeguard that's executed on saving so that the game state can be saved if there is such a WML tag somewhere.
