### ISSUE TITLE
set_variable("_", 0) creates invalid savefiles

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3879]
just like for tagnames, using a single `_` as an attributename will create invalid savegames that cannot be read by the parser.

testing code: `lua wesnoth.set_variable("_", 0)` in debug line.

Since we already disallowed `_` as tagnames for the vers same reason it woudl oynl be onsitent if we also disallowed `_` as an attributename for that reason.

**Comment by gfgtdf** [comment]
those checks assume that _ is a valid attributename since the check for _ was only added for tagnames.

**Comment by jyrkive** [comment]
All right, I found the problem with the first layer.

https://github.com/wesnoth/wesnoth/blob/81d0d2214a857a7987afa7d51cd431eaddc19e9d/src/variable_info_private.hpp#L131

This line should be using `config::valid_tag()` instead.

The second and final layer is over here: https://github.com/wesnoth/wesnoth/blob/81d0d2214a857a7987afa7d51cd431eaddc19e9d/src/savegame.cpp#L638-L640

Will need to investigate why it's letting the invalid WML through.

**Comment by gfgtdf** [comment]
> This line should be using config::valid_tag() instead.

no, config::valid_tag() and config::valid_attribute() shodul jsut be realyl the same function everywhere since the rules which names are accepted for atributes and tags are just the same.

> Will need to investigate why it's letting the invalid WML through.

becasue it is only ehcking tag not attributes.

**Comment by jyrkive** [comment]
Yeah, you're right. Variables are saved as attributes, not tags. And a lone underscore isn't valid as an attribute name, either.

I'll make `config::validate_wml()` check attributes as well and make `valid_attribute()` just call `valid_tag()`.

**Comment by gfgtdf** [comment]
then you can also revert https://github.com/wesnoth/wesnoth/commit/736f217793368fa27d180ed4dc5818072319d528 because the the line you linked above then already checks for that.


> I'll make config::validate_wml() check attributes as well and make valid_attribute() just call valid_tag().

I would probably have changed valid_attribute() and make it the other way around was since the chracter comparision based function is probably about 50 times faster than the std::isalnum based function butr that'd work too.

**Comment by jyrkive** [comment]
> I would probably have changed valid_attribute() and make it the other way around was since the chracter comparision based function is probably about 50 times faster than the std::isalnum based function

I'm not really convinced that `std::isalnum()` would be slow. Compilers aren't stupid and they can inline functions.

**Comment by gfgtdf** [comment]
>I'm not really convinced that std::isalnum() would be slow. Compilers aren't stupid and they can inline functions.

but it cannot line what it does not know, and as std::isalnum depends on the given locale, it'll probably just contain a virtualcall to use_facet<whtaever>(locale).isalnum()

**Comment by jyrkive** [comment]
Fixed in commit ccedb51101a695b776a38c61e672a2506a6f5bc3.

**Comment by gfgtdf** [comment]
> We're passing the "classic" locale as an argument.

Still, i just made a test https://pastebin.com/7xM3gCyQ, ran on http://cpp.sh/ and depending on exact impleemntation and optimisation level the chracter based solution was a factor between 3 and 30 faster than isalnum. In particular the isalnum baed implementation was realy similar on all optimsation levels so i don't think the compiler is able predict that one.

**Comment by jyrkive** [comment]
> Still, i just made a test https://pastebin.com/7xM3gCyQ, ran on http://cpp.sh/ and depending on exact impleemntation and optimisation level the chracter based solution was a factor between 3 and 30 faster than isalnum.

I see. Thanks for testing. Do you think I should change `config::valid_tag()` from `isalnum()` to a manual check?

**Comment by gfgtdf** [comment]
I personlly think chracter based is not only faster but also easier to understand it does not require you to understand how locales work etc. . So i would support that.

Also while it is of course not as timecritical as for example the drawing code (which would im partiuclar result in lags if it was to slow), it's still a function that is called rather often so i'd say its good to make it faster.

**Comment by jyrkive** [comment]
Done in commit b879702545273a04f35ebfcaa82a3cd21ba4ad6b.
