### ISSUE TITLE
Dark Forecast, enemies spawning on your villages don't remove that village from your control

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3890]
As the title says.

**Comment by soliton-** [comment]
Perhaps a nice way to fix this is to just prevent spawning on villages.

**Comment by jostephd** [comment]
It's easy enough to fix it directly:

```
diff --git a/data/multiplayer/scenarios/2p_Dark_Forecast.lua b/data/multiplayer/scenarios/2p_Dark_Forecast.lua
index 966ac9b9ed9..c0622885f24 100644
--- a/data/multiplayer/scenarios/2p_Dark_Forecast.lua
+++ b/data/multiplayer/scenarios/2p_Dark_Forecast.lua
@@ -239,6 +239,7 @@ local function place_units(unittypes, x, y)
 		})
 		local dst_x, dst_y = wesnoth.find_vacant_tile(x, y, u)
 		u:to_map(dst_x, dst_y)
+		wesnoth.set_village_owner(dst_x, dst_y, 1)
 	end
 end
 
```

**Comment by gfgtdf** [comment]
as i noted on the other simlar issue, fixing it in 2p_Dark_Forecast.lua directly, will casue OOS if people with two differnt versions of that (that ship with wesnoth version) play together. If you want to do this you probably have to copy the whole file, (lets call the copy 2p_Dark_Forecast_new.lua) and then include the new file in 2p_Dark_Forecast.cfg via preproceccor inclusion (instead of dofile)

**Comment by jostephd** [comment]
Could we prevent 1.14.5 Dark Forecast from joining and 1.14.6 Dark Forecast games? Maybe by creating a [[resource] require_modification=yes](https://wiki.wesnoth.org/ModificationWML) resource as part of the scenario or something?

Is the change acceptable for master?

**Comment by gfgtdf** [comment]
> Could we prevent 1.14.5 Dark Forecast from joining and 1.14.6 Dark Forecast games?

Hmm not sure.

> Maybe by creating a [resource] require_modification=yes resource as part of the scenario or something?

I think this only works for addon versions.

> Is the change acceptable for master?

Yes.

**Comment by jostephd** [comment]
> Yes.

Okay, fixed on master. If preventing units from spawning on villages (as @soliton- suggested) is better, we can change to that instead.

**Comment by jostephd** [comment]
Reopening since it still affects 1.14.

**Comment by jostephd** [comment]
The backport will conflict (in a trivial way) due to 04e840b0254458e5e117e5b175542820985abf64.
