### ISSUE TITLE
Block users from joining based on the host's blacklist

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#3892]
As per https://forums.wesnoth.org/viewtopic.php?f=6&t=49313, the "Block" button in the Multiplayer preferences doesn't actually block anything - it simply adds an indicator next to the username, which is misleading at the very least, and therefore rather misnamed.

Ideally though, I think it would be useful to prevent users from joining a game, either as a player or an observer, if the host has blacklisted them.

**Comment by ProditorMagnus** [comment]
It might block messages.

**Comment by soliton-** [comment]
Yes, it should ignore messages from users on the list otherwise that is a bug.

The button was renamed in commit d9b6bd7fa162.

**Comment by Pentarctagon** [comment]
eb37602656e19ac9f47429a2aede0d00404543e9 should make this more useful/doable as well.
