### ISSUE TITLE
Error when side 1 of a multiplayer game is empty

### ISSUE THREAD

**Issue by DenBeke** [wesnoth/wesnoth#3899]
Sometimes I got `Removing illegal command 'init_side'` when starting a multiplayer game with a friend. (Using the official lobby to host the game).
If I reboot my computer this problem usually goes away. But today I can't seem to solve it. Tried rebooting, tried different maps, ... still get the error once the game is loaded.

Running Wesnoth 1.14.5 on MacOS 10.14.2

What can I do to solve this?

**Comment by ProditorMagnus** [comment]
This message says someone tried to start turn, but it was not their turn. It is warning message, not something that needs solving by itself.

**Comment by DenBeke** [comment]
Most times it's followed by an out of sync error.

**Comment by ProditorMagnus** [comment]
I would like to see the type of game where it happens. I am online now (Ravana).

**Comment by DenBeke** [comment]
Thanks for debugging this with me, @ProditorMagnus !
For others stumbling upon this issue: SXC doesn't allow the first side to be empty and this happend to us because we only played with only 2 out of 5 players and with 'shuffle sides' enabled.

**Comment by gfgtdf** [comment]
@ProditorMagnus did you investigate this? Is this really only an issue of bad umc code in sxc? I mean if course that possible but sounds rather unlikely to me to give such an error message.

**Comment by ProditorMagnus** [comment]
The full error message said that the side whose command was dropped was undefined. And empty sides breaking scenarios is nothing new, I remember that from 2012.

**Comment by soliton-** [comment]
I suppose the client should not send [init_side] for empty sides to fix this. Doesn't seem useful in the first place.

**Comment by gfgtdf** [comment]
> I suppose the client should not send [init_side

If it does then it's a bug, actually, empty sides should just be skipped over.

**Comment by soliton-** [comment]
I can only say that from the server log shuffle sides was on and the server complained about illegal [init_side]+[checkup] messages. For player1/host it complained about side_number=2 and for player2 about side_number=2,3,4.

**Comment by soliton-** [comment]
Oh wait, it was not side_number=3 but [end_turn] next_player_number=3

**Comment by gfgtdf** [comment]
hmm I'll report this for now even though we still cannot exclude the possibility that this is just a bug in that add-ons wml code.

**Comment by Wedge009** [comment]
Looks to me like we don't know if this lies in the add-on or within Wesnoth. It also looks like the only ones directly working on this were Ravana and DenBeke, and Den himself closed this. I also can't see how to replicate this issue, so I'm inclined to close this again. If @gfgtdf really thinks this needs to be kept open, then re-open.

**Comment by gfgtdf** [comment]
No this is still not fixed in fact you can easily reprocue it in any moap my assigning the first aidey to "empty"

**Comment by gfgtdf** [comment]
After thinking about this, this seems nontrivial to fix because it is possible that wml.code might change the controller of the first side in a prestart event, so if we just add the" skip empty sides" code at game start serverside we might skip over sides that are reactivated by wml in a prestart event.
