### ISSUE TITLE
EI - Sc1, early finish bonus for 'fleeing' makes no sense

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3900]
If you are running away, how do you get gold from those villages? (Unlike TRoW Sc8 Clearwater Port noone is staying behind and might be giving you funds.)
So, I propose adding an alternative win condition (Defeating all enemy leaders) that rewards you with the early finish bonus, but denying it otherwise.

@nemaara

**Comment by nemaara** [comment]
Fixed by 6ee3c16.

**Comment by AI0867** [comment]
I suspect this is more of a game-design thing: Not having the bonus rewards players for sticking around as long as their income remains positive.
