### ISSUE TITLE
Possibly invalid WML, 'Image doesn't fit on canvas' 

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3905]
Sadly I have no idea how to reproduce this or what I might have done.
![](https://cdn.discordapp.com/attachments/259976436490829825/540666132181417994/wait.png)
Exited to Main Menu afterwards.

**Comment by Konrad22** [comment]
Resolution is 1280x657.

**Comment by jostephd** [comment]
@Konrad22 [new-battle.png](https://github.com/wesnoth/wesnoth/blob/1.14/data/core/images/misc/new-battle.png) is the red crossed swords image that's usually shown on the story screen after the journey dots. I think the `x=-15` means that image would have been drawn beyond the left (west) edge of the window. So, I'm just guessing, but maybe you started wesnoth in a maximized window and then unmaximized it at some point during the story screen, or something like that?

**Comment by Konrad22** [comment]
_Probably_ not, but I really don't know. Testing your suggestions didn't yield the bug though.
