### ISSUE TITLE
[TSG] Typo log

### ISSUE THREAD

**Issue by nemaara** [wesnoth/wesnoth#3906]
Putting this here so I don't forget anything that needs to be fixed for 1.14.7. Right now there is one small typo reported, but more may come later.  

1. These forts **and** ill-equipped for holding back so many undead. — from The South Guard (Pebbles in the Flood)

2. ...but we are still human and we still know loyalty and gratitude, **sir knights**. (same scenario as 1)

**Comment by nemaara** [comment]
Okay, I think it might still be better to have this issue here because I'm much less likely to forget about this though.

**Comment by soliton-** [comment]
Sure, you can use whatever you like best. Just saying that generally people will probably report typos on that page so it would be a good idea to at least check there even if you don't want to use it.

**Comment by Wedge009** [comment]
@jostephd just made a spelling/grammar-related PR #3939. Might be worth including these (and the ones on the web-site wiki) in there. With 1.14.6 nearing release I think the string freeze should be over soon if not already.

**Comment by nemaara** [comment]
I'm not entirely sure which ones @jostephd took care of already, but it seems like he hasn't fixed the TSG or TRoW ones, so I'll do that right now. I don't have a wiki account, so could someone remove the typos under TSG and TRoW for me? :)

**Comment by Wedge009** [comment]
Looks good to me. Thanks.
