### ISSUE TITLE
Eastern Invasion (Captured): cannot move freed prisoners - instant campaign end

### ISSUE THREAD

**Issue by SwissGuy19** [wesnoth/wesnoth#3908]
Version: IoS 1.14.4
Campaign: Eastern Invasion, scenario "Captured"  (it's a mainline campaign, so far as I know)

Issue: when my disguised Escapee opens a prison cell to make my other units available, they become "my" units, but they are all shown with a Red dot above (as in, their turn has ended and they cannot do any further actions). The same thing happens to Dacyn, Gweddry and Owaec.   Therefore, I cannot move the heroes out of harm's way, nor can I use the freed prisoners to attack, and the only possible action is "end turn" once I have moved the three escapees.

Since the heroes are all in open space with several nearby Orc Warriors and Level 2 trolls, once they became "my" units, the monsters turn hostile and attack them. Dacyn promptly gets slaughtered and the scenario ends. Hence it is impossible to progress further.

I have read elsewhere that this is a bug, and that the intent is that I should get one turn to try to move the heroes to safety by moving and sacrificing some of the freed prisoners.

I would be grateful if you would fix this!  I believe it has been an issue for some time now based on some comments on forums, but I cannot find any evidence that this has been entered here as a bug report.

I assume that you can contact me using my username here in GitHub and did not want to post my email address publicly. In case that is not the case, please post any follow up questions for me here, and I will check back. I believe that I should receive notifications of any replies that you may post.

**Comment by Konrad22** [comment]
Can't confirm this for 1.14.5 (Windows 10).

**Comment by Konrad22** [comment]
Apparently this is an iOS port problem, not a wesnoth problem. So, this is in a way the wrong place to report it and/or hope for a fix. :/

**Comment by soliton-** [comment]
Indeed it might be better to report at https://github.com/singalen/wesnoth/issues because the fix can likely not be done in vanilla wesnoth.

**Comment by SwissGuy19** [comment]
Thank you, I will try that. I am totally new to GitHub so would not have a clue where to report things. I found the link to this location here https://wiki.wesnoth.org/Reportingbugs and did not have another idea where to look.

**Comment by soliton-** [comment]
You did perfectly fine. It's not obvious that this is exclusive to ios or where to find the ios-specific issue tracker.

**Comment by soliton-** [comment]
Yes, no use to keep this open.

**Comment by SwissGuy19** [comment]
Thanks, hopefully this will get sorted soon on IoS.
