### ISSUE TITLE
Allow observers while meeting the MP CoC's behavior exception

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#3909]
The [MP CoC](coc.wesnoth.org) currently says:

> If "observers" is unchecked, then the game is considered private, and no public replay is saved.

It would be useful to separate the "observers"/"no observers" functionality from the "public replay"/"no public replay" functionality, as well as to allow enforcing the game password for observers.  This would then allow changing the [exception](https://wiki.wesnoth.org/MP_CodeOfConduct#Exception) to state that it applies to password protected games that don't create a public replay - currently the only way to satisfy the exception is to password protect the game and disable observers, which doesn't allow for the case of a private game where a couple friends are playing while a couple friends just observe and chat.

So, specifically, the proposed changes are:
- [x] Add an option to also force (non-moderator) observers to enter a password before joining a game.  Currently only players need to enter the password specified during game creation.
- [x] Add a separate option for making the replay private, rather than doing this implicitly when not allowing observers.

**Comment by ProditorMagnus** [comment]
The use case could be solved by #1057 as well.

**Comment by soliton-** [comment]
If we add a separate checkbox for replay saving I see no reason to couple it with anything. Though IMO it makes a lot of sense the way it is right now.

I'm not sure about the reasoning here. Password protection does not restrict observers. Perhaps you can restate the goal?

**Comment by Pentarctagon** [comment]
Maybe I'm misremembering, but I thought that observers had to enter the password as well?

In any case, the worry I have about not coupling the option with anything would be that people could use it to host otherwise public games but prevent a replay from being recorded, which would prevent use from having something to go back and look at later if necessary.

**Comment by ProditorMagnus** [comment]
No password needed for observing.

It is about public replay. When we need, we can ask for it still.

**Comment by GregoryLundberg** [comment]
Could make it a coupled option:

* Save replays and allow observers
* Save replays and do not allow observers
* Do not save replays and do not allow observers

If Allow Observers is checked, Save Replays is checked and disabled.

**Comment by soliton-** [comment]
Right if the issue is about moderation then that is no issue because moderators can request to see specific private replays. They are saved as well just not made publicly available.

**Comment by Pentarctagon** [comment]
Alright, good to know - I've removed the part about tying it to either unchecking Observers or setting a password.

**Comment by soliton-** [comment]
Ok, so since I still have trouble understanding the goal I'll try to state it:

You want to change password protection to also require the password from observers. Since the password will not be required to see the replay you then want a separate option for saving replays so that people can set up games that only a restricted group of people can see.

Correct? If so then I would suggest to just not publish replays of password protected games.

**Comment by Pentarctagon** [comment]
Observers not needing to provide the password kind of throws a wrench into how I was thinking about this.  What I was originally thinking was:

The current state is:
- A password can be set.
- Observing can be prevented via a checkbox.  This also prevents the saving of a public replay.

The proposed state:
- A password can be set.
- Observing can be prevented via a checkbox.
- A public replay can be prevented from being available via a separate checkbox.  This new checkbox can be used independently of the above two options.

---

The goal was to be able to have games where a password prevented random people from being able to join/observe a match and a replay was publicly available afterwards, thus satisfying the MP CoC's exception while still allowing there to be private games with observers.  If observers don't need the password though, then that doesn't really work, since a passworded game that saves no public replay still allows anyone to observe it.

**Comment by Pentarctagon** [comment]
Updated the first post to accurately specify what is needed.
