### ISSUE TITLE
Eastern Invasion, Bone Knights can't earn xp

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3913]
He is probably just missing the Standard AMLA macro.
![xp](https://user-images.githubusercontent.com/39015360/52479033-8b69a480-2ba7-11e9-92f9-f8b01aff55b1.png)

**Comment by ProditorMagnus** [comment]
With 1.12 it showed actual xp amount instead of "-", so I would say it is separate issue. Though the unit indeed does not have any advancements, Liberty version too.

**Comment by nemaara** [comment]
Fixed by 3b32cec.
