### ISSUE TITLE
Check whether special is active by tag name or by id

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3915]
Currently, checking whether a weapon special is active is done by looking for a weapon special whose tag name _or_ id match the specified value:

https://github.com/wesnoth/wesnoth/blob/80b00fc38b66273fd87ede407eef626eafcca26b/src/units/abilities.cpp#L607-L614

For example, the `initiative` special in HttT would be matched by _either_ `special_active=initiative` or `special_active=firststrike`:

https://github.com/wesnoth/wesnoth/blob/80b00fc38b66273fd87ede407eef626eafcca26b/data/campaigns/Heir_To_The_Throne/utils/abilities.cfg#L4-L14

Which can be confusing, because some tag names are also used as ids:

https://github.com/wesnoth/wesnoth/blob/80b00fc38b66273fd87ede407eef626eafcca26b/data/core/macros/abilities.cfg#L402-L406

It would be good to separate "search by tag name" and "search by id" and expose that in [StandardWeaponFilter](https://wiki.wesnoth.org/FilterWML#Filtering_Weapons), as @gfgtdf said in https://github.com/wesnoth/wesnoth/pull/3800#issuecomment-452714256.

Labeling "Good first issue" since this isn't a difficult change, but it will require some work on the C++ side.

**Comment by newfrenchy83** [comment]
resolve in https://github.com/wesnoth/wesnoth/pull/3920

**Comment by newfrenchy83** [comment]
@jostephd, please lookk also https://github.com/wesnoth/wesnoth/pull/4424, what this issue was reolved(or ot) BEFORE beta version

**Comment by jostephd** [comment]
Thanks for the reminder. Milestoned as requested.

**Comment by jostephd** [comment]
Reopening until documentation is updated, see https://github.com/wesnoth/wesnoth/pull/4424#pullrequestreview-301086942
