### ISSUE TITLE
attack_weight does not function as advertised

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#3923]
[Reported on the forums](https://forums.wesnoth.org/viewtopic.php?p=638187#p638187)

Attack and defense weight are treated as a boolean setting rather than a true weighting.

**Comment by CelticMinstrel** [comment]
Perusal of the code suggests that only `attack_weight` is broken and `defense_weight` actually is used as a weighting.

**Comment by cooljeanius** [comment]
> Perusal of the code suggests that only `attack_weight` is broken and `defense_weight` actually is used as a weighting.

The documentation on the wiki is worded kind of confusingly in this regards; it makes it sound like they're both broken...

**Comment by CelticMinstrel** [comment]
By the way, does nonzero _defense_ weight work as advertised?

**Comment by ProditorMagnus** [comment]
From code review it was used for something at least.
