### ISSUE TITLE
patch for wesnoth 1.14.5, scons/boost.py support for gcc8 c++ with -Werror=return-type

### ISSUE THREAD

**Issue by viy2** [wesnoth/wesnoth#3926]
It applies to wesnoth 1.14.5, can be true for unstable too.

from https://gcc.gnu.org/gcc-8/changes.html:
"Flowing off the end of a non-void function is considered unreachable and may be subject to optimization on that basis. As a result of this change, -Wreturn-type warnings are enabled by default for C++."
In other words, before, in gcc7-c++ and less we could write a function without return, like,
int  hello { cout << "Hello!" } and call it hello()
and it would work as long as we do not try to check int return value.
However, In gcc8 gcc8-c++ will optimize this code and this hello function will not return.
Thus -Wreturn-type is a must and -Werror=return-type is highly recommended.
However, scons/boost.py generates code that fails under -Werror=return-type
(code has no return).

patch is available from
http://git.altlinux.org/people/viy/packages/?p=wesnoth.git;a=blob_plain;f=wesnoth-1.15.5-alt-gcc8.patch;h=fec2538f3267b17bce5b5641792f217103ba3560;hb=05babbf23eec025831699374243182556cb23b07

The following patch fixes the issue
```diff
diff --git a/wesnoth/scons/boost.py b/wesnoth/scons/boost.py
index c828005..30676e4 100644
--- a/wesnoth/scons/boost.py
+++ b/wesnoth/scons/boost.py
@@ -102,6 +102,7 @@ def CheckBoost(context, boost_lib, require_version = None, header_only = False):
         test_program += """
         boost::unit_test::test_suite* init_unit_test_suite ( int, char**)
         {
+            return NULL;
         }
         \n"""
 
@@ -112,6 +113,7 @@ def CheckBoost(context, boost_lib, require_version = None, header_only = False):
         #endif
         int main()
         {
+            return 0;
         }
         \n"""
     if context.TryLink(test_program, ".cpp"):
@@ -135,6 +137,7 @@ def CheckBoostIostreamsGZip(context):
         {
             boost::iostreams::filtering_stream<boost::iostreams::output> filter;
             filter.push(boost::iostreams::gzip_compressor(boost::iostreams::gzip_params()));
+            return 0;
         }
         \n"""
 
@@ -165,6 +168,7 @@ def CheckBoostIostreamsBZip2(context):
         {
             boost::iostreams::filtering_stream<boost::iostreams::output> filter;
             filter.push(boost::iostreams::bzip2_compressor(boost::iostreams::bzip2_params()));
+            return 0;
         }
         \n"""
 
@@ -203,6 +207,7 @@ def CheckBoostLocaleBackends(context, backends):
             for(auto backend : backends) {
                 std::cout << backend << std::endl;
             }
+            return 0;
         }
         \n"""
 ```

**Comment by jyrkive** [comment]
Thanks for the patch. I applied with a minor change (`NULL` -> `nullptr`; we ensure that build-time tests are compiled with at least C++11).

Would you like to have yourself added to the game credits? If yes, please tell what name/nickname you'd prefer us to use.

**Comment by viy2** [comment]
> Would you like to have yourself added to the game credits? 
> If yes, please tell what name/nickname you'd prefer us to use.
viy@altlinux.org, thanks.

**Comment by jostephd** [comment]
Done (see 2396e0e734a7d4b6213655e85cc5458538ab6b7d).
