### ISSUE TITLE
[Fwd-port] Do we need to apply #3932 to master?

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#3933]
Is issue #3859 reproducible at `master` branch?

**Comment by Wedge009** [comment]
From what I can see, #3932 silently ignores any exceptions which presumably caused the ungraceful exits of #3859. If there's no harm in silently ignoring them, then I would expect it could/should go in master as well.

**Comment by Wedge009** [comment]
Given that it was accepted for 1.14 I think it should go to master as well, if only for consistency - even if it is a 'wide net' as jyrkive put it. And since hrubymar10 doesn't appear active at the moment I did this with 1b24c3ab.

**Comment by hrubymar10** [comment]
@Wedge009 Thank you for closing it. Indeed that I am rather busy these days.
