### ISSUE TITLE
Add message boxes for rest of exceptions from #3859

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#3934]
There are 2 more `addons_client` exceptions, which could happen in multiplayer lobby. They were removed from this commit: https://github.com/wesnoth/wesnoth/pull/3932/commits/0df243e46c320cacc1dfe6eda3afc14704969250

**TODO:**
- [ ] Add message box for `addons_client::invalid_server_address` catch
- [ ] Add message box for `addons_client::not_connected_to_server` catch

**Comment by stevecotton** [comment]
The string freeze for 1.14.10 has started, should we create a 1.14.11 milestone?

**Comment by stevecotton** [comment]
What is the difference between user_exit and user_disconnect? They both seem to mean "user has used a GUI button/hotkey to cancel", is it useful to know exactly how far the connection had got before the user cancelled?

**Comment by Wedge009** [comment]
https://github.com/wesnoth/wesnoth/blob/e235d9a64e50a1af0a228292849d9a054dae76e5/src/addon/manager_ui.cpp#L105-L107
https://github.com/wesnoth/wesnoth/blob/e235d9a64e50a1af0a228292849d9a054dae76e5/src/addon/manager_ui.cpp#L323-L325

Does this mean the first one is done?

I couldn't find any mention of `addons_client::not_connected_to_server`, at least in master - does that mean it's no longer valid?

If yes to both, I think this should be closed.

**Comment by Wedge009** [comment]
Re-open if still valid.
