### ISSUE TITLE
Use damage type and range icons in units database

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3949]
Like #3732 #3740 #3940, but for [the units database](https://units.wesnoth.org/trunk/mainline/en_US/mainline.html) for 1.15+

**Comment by edwin7878** [comment]
3740

**Comment by jostephd** [comment]
Fixed in #4016 

@drzaal Thanks for fixing this! Next time, please include `Fixes #3949` somewhere in the commit message so github will auto-close the issue as well.

**Comment by soliton-** [comment]
That was my fault. I squashed the commits and wrote the commit message missing the proper format.

**Comment by jostephd** [comment]
Ah, sorry.
