### ISSUE TITLE
internal error in unit database

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3965]
Thanks for getting the unit database running again.

There's still a bug left, in the Build Report are two internal errors listed.
https://units.wesnoth.org/1.14/overview.html

`please report as bug`
`unorderable types: NoneType() < str()`

**Comment by soliton-** [comment]
Complete backtrace:

> campaign Mountain_Witch Mountain_Witch en_US
> Traceback (most recent call last):
>   File "/usr/src/wesnoth/master/data/tools/wmlunits", line 480, in batch_process
>     n = process_campaign_or_era(name, cid, campaign["define"], batchlist)
>   File "/usr/src/wesnoth/master/data/tools/wmlunits", line 425, in process_campaign_or_era
>     n = html_output.generate_campaign_report(addon, isocode, campaign, wesnoth)
>   File "/usr/src/wesnoth/master/data/tools/unit_tree/html_output.py", line 1362, in generate_campaign_report
>     n = html.write_units_tree(grouper, title, True)
>   File "/usr/src/wesnoth/master/data/tools/unit_tree/html_output.py", line 953, in write_units_tree
>     self.write_navbar("units_tree")
>   File "/usr/src/wesnoth/master/data/tools/unit_tree/html_output.py", line 599, in write_navbar
>     racenames = sorted(r[0].items())
> TypeError: unorderable types: NoneType() < str()
>     Mountain_Witch failed

Same thing with "Castle_of_evil_spirit".
