### ISSUE TITLE
Segfault when hotkey filter has no matches

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3970]
This is basically #3969 for #3759: if you open the "Hotkeys" tab of the preferences dialog, enter a filter that has no matches, and press "Clear Hotkey", wesnoth will segfault. @rocketBANG @addaleax 

Several dialogs have very similar search functionalities:
- hotkeys #3759 
- recruit list #3787 
- recall list
- campaign list (#3829)
and it's been requested for the faction list (#3826).

The state of this particular bug for each of these is:
- hotkeys: this issue
- recruit list: fixed in #3969 
- recall list: fixed in #3476 
- campaign list: doesn't crash, just starts AToTB. This is a minor bug but there's no issue for it.

**Comment by jostephd** [comment]
This is probably a regression from 1.14.5, the hotkey filter was added in 1.14.6.

**Comment by jostephd** [comment]
@rocketBANG Would you be able to look into this for 1.14.9?

**Comment by rocketBANG** [comment]
will do

**Comment by jostephd** [comment]
Thank you :+1:
