### ISSUE TITLE
pbl syntax error prevent startup

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3971]
When an installed addon has an invalid `_server.pbl` file, wesnoth fails to start, it dies immediately with `Caught unspecified general exception. Terminating.`

Two changes are needed.

- [x] Make `invalid_pbl_exception` inherit from std::exception

- [x] Catch `invalid_pbl_exception`, probably here:

https://github.com/wesnoth/wesnoth/blob/9e6d033efbe997745adfe544832d00e9835e1eaa/src/game_config_manager.cpp#L401

https://github.com/wesnoth/wesnoth/blob/9e6d033efbe997745adfe544832d00e9835e1eaa/src/addon/manager.hpp#L63-L71

**Comment by ProditorMagnus** [comment]
Isnt it impossible for installed addon to have pbl files?

**Comment by jostephd** [comment]
It's an addon I maintain so it does have the pbl file in the addons directory.

**Comment by Pentarctagon** [comment]
Closed by #4017.
