### ISSUE TITLE
static build?

### ISSUE THREAD

**Issue by vans163** [wesnoth/wesnoth#3973]
Is there a statically linked build available?  The compiled binary is not portable at all, and not all systems have the exact required libraries. Also not all systems have flatpak.

**Comment by Vultraz** [comment]
For what OS?

**Comment by vans163** [comment]
Linux

**Comment by GregoryLundberg** [comment]
IIRC we already link statically. The issue is that some of libraries we statically link to dynamically link to others. Attempting to statically link those, as well, is on the highway down the Rabbit Hole, if it's even possible.

**Comment by vans163** [comment]
Right thanks. Il have to figure something out for my portability usecase.
