### ISSUE TITLE
Dark Forecast (2p Survival) - Bosses Not Spawning

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#3981]
> I used to play the map Dark Forecast (Co-op Survival) quite a bit a few years ago, but upon coming back and checking it out I noticed that the final bosses that used to spawn weren't spawning (yeti, dragon, elf). Is there a way to fix this or has the map simply been made easier since then?

https://forums.wesnoth.org/viewtopic.php?t=49382

**Comment by nemaara** [comment]
See https://github.com/wesnoth/wesnoth/compare/ff9fef962d35...524692e016f6.

**Comment by gfgtdf** [comment]
if you change the Lua file it causes out of sync errors when two player with different version play together. For 1.14 please use the wml patch I mentioned in the thread,for 1.15 the Lua patch is the correct way.

**Comment by nemaara** [comment]
Okay, see https://github.com/wesnoth/wesnoth/compare/524692e016f6...6bb78d4f6552.
