### ISSUE TITLE
Playing a campaign on hardest difficulty does not always award a gold wreath/laurel (probably caused by old 'difficulties' syntax)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#3983]
(Add-on) Campaigns where I've noticed this:
Lich Terror
Panther Lord
To Lands Unknown
Epical
A Vision Blinded
Heroes: The Iron Bulwark
Inky's Quest
(And some more.)

Every mainline campaign (I've played so far (10)) awards the gold laurel for the hardest difficulty and multiple add-on campaigns do as well.

So, maybe this might be caused by some schema the add-ons did not adhere to, which messed with the completion marker? I'm guessing very much.

EDIT:
FTR, there is a single difficulty campaign that properly awards the gold laurel, but there are other single difficulty campaigns that wrongly awarded a silver laurel.

**Comment by soliton-** [comment]
Seems to me like all the campaigns you mentioned use the old difficulties syntax while mainline has been converted to [difficulty] which is also what the code checks:

https://github.com/wesnoth/wesnoth/blob/073081ef89218edf743d642a28f61f6eaf7f5e96/src/gui/dialogs/campaign_selection.cpp#L337-L363

So I'm guessing there is perhaps an issue with backwards-compatibility code that converts to the new syntax.

**Comment by Konrad22** [comment]
Thanks. I'll try spreading the word. :D

**Comment by slavrenyuk** [comment]
I have verified that with the old difficulties syntax the completion laurel is always silver instead of gold or bronze. The correct laurel is shown after the difficulties syntax has been updated.

**Comment by CelticMinstrel** [comment]
Ideally I'd say it should work for both syntaxes, but... I don't know if it's worth the effort to do this? I think the old syntax was already removed in master.

**Comment by Konrad22** [comment]
It's not really a bug, it's at most a badly communicated behavior change/feature implementation.

**Comment by jostephd** [comment]
@Konrad22 That depends on how 1.12 behaved. If it's simply a difference between the old and new syntaxes, then yes, it's a behavior change. However, if in 1.12 the (now) old syntax gave gold wreaths, then this behavior change is a bug in 1.14's support for the deprecated syntax, in which case this bug would be fair game to be fixed, though admittedly it's low priority as it's about a deprecated feature.

**Comment by CelticMinstrel** [comment]
I agree, it's definitely a bug. We may choose not to fix it since it only affects a deprecated feature, but it's still a bug, not a communication error.

**Comment by Konrad22** [comment]
To avoid someone opening a new issue about this, Or maybe actually fixes it.

**Comment by gfgtdf** [comment]
> I think the old syntax was already removed in master.

If this is true and this report oynl effects 1.14. please add a the 1.14 label to this issue.

**Comment by jostephd** [comment]
In master the old syntax is deprecated but hasn't yet been removed:

https://github.com/wesnoth/wesnoth/blob/e4c4ca7572b2986790f40ee20b1ccb2e6e85252a/src/gui/dialogs/campaign_difficulty.cpp#L77-L85

**Comment by Wedge009** [comment]
Seems to still be accommodated as we head towards 1.16 release as well (I suppose that's okay, just pointing it out):
https://github.com/wesnoth/wesnoth/blob/e235d9a64e50a1af0a228292849d9a054dae76e5/src/gui/dialogs/campaign_difficulty.cpp#L43-L52

**Comment by Pentarctagon** [comment]
Should this be closed?

**Comment by Wedge009** [comment]
@Konrad22, original reporter, seemed to think so back in March 2019. I note the old difficulty deprecation message is still in place in master as at 0945c30efd2cafff9f36ca328bcd5ffc591e6be9.

**Comment by Konrad22** [comment]
Ftr, I agree with closing he issue. New campaigns are very unlikely to be using the old format (and running into the issue), and old campaigns that haven't updated it yet, probably won't.
