### ISSUE TITLE
Better "Help" Menu for ANL

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#3987]
The »4p - A New Land« Scenario has explanations about how the game works in form [messages] called from a menu _item.

It has limitations which some UMC did overcome:
* It's only available while it's you turn, and not to observers
* It's synced, other players must wait while you read

AFAIK Ageless Era addressed these two points.

**Comment by gfgtdf** [comment]
It's very easy to overcome: check that it does not change the gamestate in any way and then add synced=no to the menu item.

I actually think we should port the whole scenario to Lua btw.

**Comment by sevu** [comment]
Thanks, that's really easy to change.
(needs new string in the objectives, so pointing to 1.14.8)

Porting to Lua... hmm. May be nice, but is it worthy it?

In case this becomes a thing, it would be nice to think of it more like an engine and a scenario, or to have it extendable in some way (like adding transformation actions).
That's more or less what ANLEra does (in WML), though it can't use code from mainline anl directly, had to be duplicated, and the code of ANLera has the same problem that nobody could extend it.
On the other hand, I never really found sth. which would be worthy to port back to mainline anl.
(though that's partly a chicken-egg problem, because there is just one scenario...)

To put a start on this, rewriting the leader_options is one thing where wanted to look into using Lua - mainly because you can't know in WML how many sides the game has. (Not anytime soon though)

Though, again, maybe the next time worthy rewriting is haldric. The code so far works, rewriting is just investment of work.

**Comment by sevu** [comment]
merged
