### ISSUE TITLE
wmllint's warnings for core

### ISSUE THREAD

**Issue by konecnyjakub** [wesnoth/wesnoth#3993]
On 1.14.6, wmllint prints quite a lot of warnings for core. Most/all of them are false positives for misspelling. Full list is here: https://gist.github.com/konecnyjakub/2314fdf9bd5054821e59b9a8a2bc03a5. Some of them appear since 1.13.6: https://forums.wesnoth.org/viewtopic.php?f=5&t=44809&start=105#p607519. False positives can be filtered out with magical comments in form
`# wmllint: [global|directory|local] spellings word1 word2 ...`

**Comment by stevecotton** [comment]
#4494 is a duplicate of this, but as #4494's description says how to run the lint tool I suggest closing this earlier bug as a duplicate of the later-filed one.

**Comment by soliton-** [comment]
Duplicate of #4494
