### ISSUE TITLE
Win10 bad fonts render

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#3994]
## Environment
Windows 10 x64
Wesnoth 1.14.6

2 monitors configuration: 2560x1440 with Windows scale 150% and 1920x1080 with Windows scale 100%.

## Problem
It's simply disgusting font rendering. Even hard to read words.

I've tried to turn off/on ClearType... I've tried to do Windows scale 100/150%... I've tried to fullscreen/windowned... I've tried on both monitors...  

[Screenshots here, ZIP-archive](https://github.com/wesnoth/wesnoth/files/2979984/screens.zip)

Always there is bad font rendering. And only difference is between 2 monitors: on 2560x1440 monitor with 150% scale - font symbols seems like anti-aliased/blurred (but this not helps).

**Comment by Wedge009** [comment]
FYI, you can crop images and drop them directly into the issues here, for your convenience.

I think there have been issues with Windows font rendering in the past but I find it hard to replicate and diagnose. I also don't test much on Windows 10, still being primarily on 7, but I note these similar (but probably not related) issues in #1568 and #1921.

I don't know what differences there could be between Windows 7 and 10 in terms of text rendering but I can't replicate this in Windows 7.

**Comment by Wedge009** [comment]
Just tested in Windows 10, albeit on a small screen, and couldn't replicate this either. Need to wait for other Windows 10 users to give their input, or check for other OS-level specifics on your system.

In both cases I was also using the 1.14.6 release, from Steam.

**Comment by amokmen** [comment]
I have another system with Windows 7 - there is acceptable font rendering.

But I have no second Win 10 to make double testing...

**Comment by Wedge009** [comment]
Has anyone else seen anything remotely resembling this? Even on something other than Windows 10?

**Comment by amokmen** [comment]
Some summarize and additions.

I have 2 systems:
* Win 10 with 4K monitor (3840x2160) and currently installed Wesnoth 1.14.6 and Wesnoth 1.15.1.
* Ubuntu 18 with same model of monitor and Wesnoth 1.14.7, 1.15.1.

On Windows there are 2 ways to run Wesnoth - with checked option "Disable display scaling on high DPI" for application (Right-click the application name, select Properties, select the Compatibility tab, and then select the Disable display scaling on high DPI settings check box) or with unchecked.

Difference is - Wesnoth would run in native resolution (desktop resolution) with native small fonts - which hard to read OR Wesnoth would run, for example in 1920x1080 resolution, with absolutely bad font rendering.

So, all are very simply: there is no way to play Wesnoth normally. Small native hard reading text or big bad rendered text.

All the same for Ubuntu, but there is one more problem - you must manually (or by script) switch desktop resolution from native 4K to FullHD before running game for big fonts and switch back again after playing.

So, my sum is: **on 4K monitor you could not play Wesnoth with comfort at all (Windows or Ubuntu)**.
My only option now - at system with Ubuntu I have 2 monitors config, and second monitor have **native FullHD - only here fonts could be acceptable for playing**.

So, one more time: **now you could play Wesnoth only at FullHD monitor**.

**Comment by Wedge009** [comment]
@Vultraz Given that you use a UHD monitor and also Windows 10 (IIRC), do you have any comments relating to this?

**Comment by amokmen** [comment]
And "Font scaling" option in 1.15.1 seems good at 150% (but need it to be up to 200%).
There are buggy UI of course, but with some changes probably this is could be solution.

**Comment by Wedge009** [comment]
Font scaling issues are already tracked in items such as #1604 and #2792. High DPI support is also already requested in issues like #1588 and #2219. If that's all you're concerned about, then you should close this as duplicate.

However, it seems to me that there is specific concern about how Windows 10 renders Wesnoth fonts with certain OS (ie not Wesnoth-based) settings, which I can't replicate and therefore cannot confirm this issue.

**Comment by amokmen** [comment]
Actually I think there is no sense to understand if there is exactly smth wrong in details becouse all should be changed.

Closing issue then.
