### ISSUE TITLE
Add liberapay links to the websites / discord / etc

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3995]
The liberapay link https://en.liberapay.com/Battle_for_Wesnoth/ should be published on places such as www.wesnoth.org, the wiki, discord, MP server MOTD. I don't know what places exactly and how visible the link should be, but right now it's only mentioned in a [single forum post](https://forums.wesnoth.org/viewtopic.php?p=639892#p639892), unless I've missed something.

**Comment by soliton-** [comment]
If we can come up with specific wording I'm happy to add that to the MOTD on the mp servers.

**Comment by Pentarctagon** [comment]
I brought it up in the admin chat about getting it added to wesnoth.org's home page.  Once that's there I'm planning to sticky it to the wesnoth/steam forums.

**Comment by shikadiqueen** [comment]
Home page end done in wesnoth/wesmere v1.1.7 (already deployed).

**Comment by Pentarctagon** [comment]
I've added announcements to the Wesnoth and Steam forums.  The wiki probably isn't necessary though, which leaves Discord and the MP MOTD.

**Comment by shikadiqueen** [comment]
Personally I don't think adding this to the MOTD is useful. People barely bother with reading the CoC in there as it is, and people who actually want to donate will check the website anyway.

**Comment by Pentarctagon** [comment]
It's less about that, and more about just letting people know that it's available.  There are people who are on the MP server frequently, but visit the website only rarely.

**Comment by sevu** [comment]
Can this be closed, or is there sth. outstanding?

@shikadiqueen, unrelated, just see that the twitter button on wesnoth.org went missing.

**Comment by shikadiqueen** [comment]
@sevu It hasn't for me. Check if disabling adblock makes a difference perhaps?

**Comment by sevu** [comment]
Indeed.
