### ISSUE TITLE
Drake Flare not undrawn when playing leadership animation over water

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#3996]
Drake Flares are a flying unit that has leadership. When a Flare is on a water hex and a friendly unit next to it is attacking, the Flare isn't completely undrawn before it's drawn playing its leadership animation submerged (because of the water):

![2019-03-22-124730_1920x1080_scrot](https://user-images.githubusercontent.com/24784687/54823837-f7f4ba80-4ca0-11e9-9cc7-3d80cb945a74.png)

Similar to #3325

<details>

<summary>
test case
</summary>

```
diff --git a/data/scenario-test.cfg b/data/scenario-test.cfg
index 784f11193a6..294dad69407 100644
--- a/data/scenario-test.cfg
+++ b/data/scenario-test.cfg
@@ -76,7 +76,9 @@ Xu, Xu, Qxu, Qxu, Ql, Ql, Ql, Xu, Xu, Xu, Xu, Xu, Xu, Xu, Xu, Gg, Gg, Gg, Gg, Gg
         gold=2000
         village_support=5
         team_name="1"
-        shroud=yes
+        shroud=no
+        {UNIT 1 (Drake Flameheart) 28 14 ()}
+        {UNIT 1 (Red Mage) 29 15 ()}
         recall_cost=42
         [village]
             x,y=9,7
```

</details>

**Comment by jostephd** [comment]
I took a shot in the dark:

```
diff --git a/src/units/animation.cpp b/src/units/animation.cpp
index 30d6be32c68..3f39c4c9277 100644
--- a/src/units/animation.cpp
+++ b/src/units/animation.cpp
@@ -1127,7 +1127,7 @@ bool unit_animation::invalidate(frame_parameters& value)
 
 	if(complete_redraw) {
 		if( need_update()) {
-			disp->invalidate(overlaped_hex_);
+			disp->invalidate_all();;
 			invalidated_ = true;
 			return true;
 		} else {
@@ -1136,7 +1136,7 @@ bool unit_animation::invalidate(frame_parameters& value)
 		}
 	} else {
 		if(need_minimal_update()) {
-			disp->invalidate(overlaped_hex_);
+			disp->invalidate_all();;
 			invalidated_ = true;
 			return true;
 		} else {
```

It seems to help, but I don't know if it's correct. I didn't examine the function or its callers to know if `invalidate_all()` will be called under the right conditions.

**Comment by AI0867** [comment]
That will work, but it will also destroy performance, as you rerender the entire screen for every frame. You instead want to figure out which hexes are overlapped and only invalidate those. I am unsure what `overlaped_hex_` means here, but it looks like a good start. Check what the parameters are and what unit_frame::get_overlaped_hex() then does with them.

**Comment by jostephd** [comment]
Thanks for the review. `src_` and `dst_` are the Flare's and Spearman's hexes respectively for the leading animation, and the Spearman's and Orcish Warlord's hexes respectively for the attack animation, but I haven't been able to get to the bottom of get_overlaped_hex(). However, in second thought, I wonder if this is even the right area of the code to be looking at? Maybe the `"leading"` animation is played correctly, but nothing invalidates the hexes the standing/idle animation was playing over?

https://github.com/wesnoth/wesnoth/blob/74c1f204e554ea6dad8879eec2bf42e880a00255/src/units/udisplay.cpp#L649-L651

**Comment by jostephd** [comment]
Is this better?

```
diff --git a/src/units/udisplay.cpp b/src/units/udisplay.cpp
index fd9b780adba..139e7fba63f 100644
--- a/src/units/udisplay.cpp
+++ b/src/units/udisplay.cpp
@@ -658,6 +658,7 @@ void unit_attack(display * disp, game_board & board,
                unit_map::const_iterator leader = board.units().find(ability.second);
                assert(leader.valid());
                leader->set_facing(ability.second.get_relative_dir(a));
+               leader->anim_comp().invalidate(*disp);
                animator.add_animation(&*leader, "leading", ability.second,
                        att->get_location(), damage, true,  "", {0,0,0},
                        hit_type, attack.shared_from_this(), secondary_attack, swing);
```

I added a test case to the first post.

**Comment by mesilliac** [comment]
Just a note that i confirmed this is still a problem. It is a separate issue from both #6118 and #6589. I'm guessing however the leadership frame is done doesn't clear the animation frame correctly.

**Comment by mesilliac** [comment]
The fix posted above worked and looks correct. Thanks @jostephd

**Comment by Wedge009** [comment]
Back-ported to 1.16 in e5c2a13468d
