### ISSUE TITLE
LoW MP - S4, Cleodil can't be freed by allied units from side 3

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4000]
At the start of the scenario you get a unit for side 3 (Cleodils side) which runs to the cage with Cleodil. The problem is, that unit is not able to actually free her. 
My best guess is, someone forgot to account for side 3 when checking who can trigger that event.

**Comment by gfgtdf** [comment]
I always assumed this was intentional that the other players have to free her before side 3 gets to do something. But thinking about it that's probably not the case.

**Comment by nemaara** [comment]
See https://github.com/wesnoth/wesnoth/commit/3907a978cad5693ac88e8bdca56da2012fe4ec72.
