### ISSUE TITLE
'Lit' (as in 'lit underground hex') and 'illuminating' stack (unlike the way it is in reality)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4002]
As the title says.
There is a chance that I've misunderstood the physics regarding this, but if I didn't, the stacking makes little sense.

Looking at it from the gameplay point of view it makes it possible to play as if it's daylight, but underground.

**Comment by Konrad22** [comment]
I'm closing that at least until I figure out how this stuff actually works.

**Comment by jostephd** [comment]
For comparison, the terrain bonus of lava stacks with illuminates, so it's possible to get +25% lawful bonus during night:

![2019-03-26-161750_358x229_scrot](https://user-images.githubusercontent.com/24784687/55014353-bb97c600-4fe2-11e9-91fd-508dd529c3c0.png)

**Comment by CelticMinstrel** [comment]
@jostephd I'm not sure if that actually counts as stacking?

**Comment by jostephd** [comment]
@CelticMinstrel At night the lawful bonus is -25% with neither illuminates nor lava, 0% with one of them but not the other, +25% with both.

**Comment by CelticMinstrel** [comment]
Hmm. Maybe that could be read as the lava providing dim illumination and the holy light is bright illumination?

(But I guess it does stack then, huh...)
