### ISSUE TITLE
Legend of Wesmere (MP) - S3, vision according to story mismatches with actual vision for the ai enemy

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4005]
> the north wind blew, and the fog lifted to reveal a grim sight...

Except, it apparently only blows for the Elves. The map remains fogged for the AI (Orcs).

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/bd56f4312c425399e91c7635a8ae4f6c82c497a7
