### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [wesnoth/wesnoth#4008]
Would you like to wrap any more pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [run()](https://github.com/wesnoth/wesnoth/blob/bad9e86d717a0b784bae12c73a6ee8652cf68255/src/attack_prediction.cpp#L2641)
- [text_surface::bidi_cvt()](https://github.com/wesnoth/wesnoth/blob/60fd504caf46bbb1648de369303b76225d805e5d/src/font/text_surface.cpp#L40)

**Comment by jyrkive** [comment]
For the record, `run()` is test code, and `text_surface` is only used by legacy text rendering. Neither of them are a priority in any way.
