### ISSUE TITLE
Tutorial: Force bad luck to teach about save/load

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4010]
https://forums.wesnoth.org/viewtopic.php?p=640618#p640618, suggestions by @beetlenaut and me:

> Maybe add a scene to the tutorial where we have the player do an attack, force that attack to miss 4/4, and then the narrator explains that that happens sometimes and campaigns generally don't expect you to save/load when it happens 

> This message is a really good idea. However, I bet it's rare that someone saveloads when a fighter or archer misses 4 out of 4 times. More often it seems to be when an important unit dies. Maybe we should do it the first time a unit dies in the tutorial. We could even force that if it hasn't happened yet and the enemy is down to just a couple units. (The player would be winning handily in that case.)

**Comment by jyrkive** [comment]
BTW, it's trivial to force attacks to miss: just give the target unit the `invulnerable` status. It's not shown to the player, so it's perfect for that.

**Comment by jostephd** [comment]
Or use [FORCE_CHANCE_TO_HIT](https://github.com/wesnoth/wesnoth/blob/97b1f7630cadbb58710dc492a6ae65d8fe513e84/data/core/macros/utils.cfg#L496-L516).

**Comment by jyrkive** [comment]
Hmm... on second thought invunerability isn't such a good idea after all because attack prediction is aware of it, and thus the attack dialog would show in advance that the attack cannot hit.

**Comment by jostephd** [comment]
So we might be able to assign the `invulnerable` status in an `attack` event, or just use FORCE_CHANCE_TO_HIT. At any rate, this is solvable.

Let's try to figure out the gameplay we're after. @beetlenaut How can we force a unit to die? A good player can win the tutorial with no losses, I think, so I don't think we can force a unit to die. Maybe we can combine the ideas: show the message in S2 upon the first player unit dying, _and_ force the first attack on the enemy leader to miss entirely if no player unit had died by that point.

**Comment by beetlenaut** [comment]
It's not *that* unlikely for four hits to miss the leader--he's in a castle after all--and I can't imagine anyone savescumming just for that. Missing 7 out of 8 on the first two attacks would be a lot more aggravating, so maybe we could do that. I would say that only the sixth out of the first 8 strikes hits, so two shamans would miss entirely, and two archers would only get one hit between them. ("Wow, you've had some really bad luck so far this turn!")

However, we could check each turn to see if there was a unit the leader could rush out and kill with some "luck". If he was quick and fearless, that would be most of them. Even a good player is almost certainly going to approach the leader with a unit that has 30 hitpoints or less. So, *forcing* the loss of a unit would be technically impossible, but making it really likely wouldn't be that hard.

**Comment by CelticMinstrel** [comment]
What exactly are we trying to solve with this? I don't think the existence of save/load really needs to be covered in the tutorial...

**Comment by beetlenaut** [comment]
Apparently, some players seem to think that save/loading is normal and expected, and, by design, it's the only way to make it through the mainline content. Maybe we should just do a tip of the day though.

**Comment by Arcanister** [comment]
I think forcing a player unit to die or to miss is a bad idea, it will be viewed as unfair by the player.
And as far as I understand, it's impossible to detect savescumming from wml/lua code?
Otherwise I would suggest this dialogue after player loads a game from same not-first turn several times in row.

**Comment by jostephd** [comment]
> I think forcing a player unit to die or to miss is a bad idea, it will be viewed as unfair by the player.

Okay, how about this: we don't load the dice, but if the player gets many misses by chance, then the advisor elf (side 3) remarks about that?

>  And as far as I understand, it's impossible to detect savescumming from wml/lua code?
> Otherwise I would suggest this dialogue after player loads a game from same not-first turn several times in row.

It might be possible to engineer something with https://wiki.wesnoth.org/PersistenceWML.

**Comment by stevecotton** [comment]
Maybe this would be better to add in a third scenario to the tutorial campaign, along with a narrator's comment that after two scenarios the player already knows enough to play other of the other campaigns instead?

**Comment by stevecotton** [comment]
Save-loading is a part of the UI interface, with the "Menu > Back to ..." menu. Instead of adding the comment to the tutorial, how about adding it to the "Back to ..." menu?

**Comment by beetlenaut** [comment]
> Save-loading is a part of the UI interface
That's a good point. We do seem to be encouraging save/loading there. Maybe that menu option should be less obvious or harder to get to. It could be disabled by default and added by an advanced option for example. (Which could have a note.) Or, it could just be removed entirely. Nothing would really change because you could still load an autosave manually, but you wouldn't be encouraged to do so.

**Comment by stevecotton** [comment]
I've added a help link to the "Back to" menu in 862e482895c405808b8ab9f77e6a2509c57948c7 (for 1.15). I don't feel it necessary to make it harder to go back to a previous turn, because a player either uses it or forgets about it.

On the tutorial, in PR #4205 I've had a go at adding a third scenario which includes an attack by an Elvish Enchantress (you're playing as orcs), with the tutor saying:

> The magical attack of an Elvish Enchantress is very strong, and if she doesn’t manage to kill an orc herself then another elf is likely to try and finish the already-weakened orc, so assume that we will lose some orcs in this battle.
> 
> In the previous lesson you learnt to decide which units should get the best chances to gain experience. You should decide which units will be shielded using other units’ <i>Zone of Control</i>.

A forced chance to hit could be added to that, if needed.

**Comment by nemaara** [comment]
Given that we already have something about strategy in help and I've reduced the difficulty of a lot of campaigns for newer players, this issue seems to be indirectly resolved.
