### ISSUE TITLE
UtBS - Out of the Frying Pan: Set Water Rise to a Global Timer

### ISSUE THREAD

**Issue by Sorenroy** [wesnoth/wesnoth#4019]
I try to play through all the campaigns blind and Ironman. I love the feeling of always being unsure of what is coming next and knowing it could end your whole career if you make a wrong move.  I was playing through Under the Burning Suns (great work by the way, best campaign IMO) this way and was upset when I ended up losing after struggling with the scenario "Out of the Frying Pan". After losing, I went back and confirmed my suspicion that the water rise was linked to certain map triggers and not on a global timer. This was upsetting as it punished me for using the extremely fast level three magic units to scout ahead as I was inadvertently setting off those triggers and dooming my slower walking units to a watery grave. I have no problem with a challenge or even with my slow units dying because of my bad decision to recall them in such a scenario, but being punished for the logical decision of scouting ahead was extremely unfun, especially as a first time player of the scenario.

My recommendation would be to have all the triggers that would normally cause water rise be removed and in their place, have longer tunnels with the water starting further back that would fill up at the expected rate of the player naturally moving through*.

*With the exception of the water that comes from flipping the secret switch for the exit tunnel. This could still have the water rise as soon as it was opened with some sort of explainer like *magic slows the floods coming into the sanctum*.

Also, while I've got you thinking about this particular scenario, here are a few other minor things that bothered me playing through:

1. Units trapped in the area near the containment circle should still drown. They shouldn't miraculously cling on against the far wall and then teleport out at the end of the scenario. It also meant maintaining expensive units in the hope that those units would escape to be recalled later.

2. There is some reason to split the scenario into two separate ones. The only carryovers between the caves and emerging from them is the river that forms once the caves finish flooding and the number of turns you have left upon cave exit. Even your gold is reset once you reach the cave exit.

[UtBS-Out of the Frying Pan replay.gz](https://github.com/wesnoth/wesnoth/files/3056627/UtBS-Out.of.the.Frying.Pan.replay.gz)

**Comment by nemaara** [comment]
Fixed by #4022.
