### ISSUE TITLE
Potential Portrait Candidates

### ISSUE THREAD

**Issue by MetaKnight** [wesnoth/wesnoth#4020]
I noticed there are several sprites lacking portraits, and many well-done portraits have been made for these units. However, they have not been mainlined.
There is also plenty of Wesnoth Fanart, which seems realistic based on standards set by Jetryl, Lord Bob, Kitty and others.
I know not all may be acceptable, but please consider some of them, since I don't think we'll be getting many portraits anytime soon. At the very least, these could be placeholders for the time being.

**Units Lacking Portraits**
Royal Warrior
https://forums.wesnoth.org/download/file.php?id=43501
Made by LordBob. Used to be used for Eldaric from 'The Rise of Wesnoth'.

Cuttlefish
https://forums.wesnoth.org/download/file.php?id=75827
Made by doofus-01. Looks pretty good but not mainlined for some reason.

Fire Dragon
https://ibb.co/37Y8mpq
Used in 'The Sceptre of Fire'. Could be used for the default portrait as very few of this unit are encountered in the first place.

Fire Guardian
https://forums.wesnoth.org/download/file.php?id=50119
I know LordBob had some issues with this one, but it doesn't seem totally unacceptable, more so as we don''t seem to be getting many contributions as of late.

Water Serpent
https://ibb.co/ScYWYZr
A great portrait. I know there were some issues, but I think it's better than having no portrait.

Wolf
https://wesnoth.org/forum/download/file.php?id=51877
Made by doofus-01.

Great Wolf
https://raw.githubusercontent.com/doofus-01/wesnoth-Archaic_Era/master/images/portraits/timber-wolf.png
Found this from the 1.12 UMC 'Swamplings'. We could ask the artist for their permission.

Direwolf
https://ibb.co/qyvsBD1
A photoshop of the wolf from the Direwolf Rider.

**Replacements for Repeat Portraits**
Elder Mage
https://ibb.co/nwrxwqF
This is the portrait of Master Perrin from 'The Hammer of Thursagan', who speaks only in one scenario, and doesn't even cause defeat when he dies. He seems to look viable for the aforementioned unit's portrait.

Elvish Marshal
https://ibb.co/99Z0R41
This was used in 'The Sceptre of Fire' and was given the file name 'elvish_marshal', suggesting it was a generic portrait for the Elvish Marshal in the campaign. Could we not port this to core?

Elvish Rider
https://forums.wesnoth.org/download/file.php?id=83483
Lomarfel, the loyal Rider from 'An Orcish Incursion', who speaks only twice in the whole campaign, has his own portrait. Couldn't this be used for the Elvish Rider mainline portrait instead?

Elvish Outrider
https://ibb.co/vqCbWsN (Less evil version of Elurin)
In 'The Hammer of Thursagan', there is an enemy Rider who speaks only one line in a single scenario and does nothing more; he has his own portrait. It looks like one for a strong Rider, so we could use that for the Outrider mainline portrait. This portrait looks kinda evil, so maybe the expression could be slightly altered. Might be a controversial one, but I think it might work out.

Orcish Leader and Orcish Ruler
I think we could use one of the alternates for the former and the other for the latter. We also have a ton of promising alternate Orcish Grunt portraits that could be considered for this purpose. Perhaps we could discuss what to do in this regard.

Great Troll and Troll Hero
https://ibb.co/YDTW4V7 (Proposed Great Troll)
https://forums.wesnoth.org/download/file.php?id=57422 (Proposed Troll Hero)
Can we not use the Troll Hero Alternate for the Level 2 and the Default for the Level 3, since the latter looks stronger than the former (and so more fitting to be a Great Troll portrait), instead of merely keeping it an alternate and repeating the same portrait for the two units?

Bat Line
https://ibb.co/nw4kWX8 (Vampire Bat)
https://ibb.co/S5LfsYJ (Blood Bat)
https://ibb.co/p3h824Q (Dread Bat, Existing Portrait)
Since the sprites for the Blood Bat and Vampire Bat are identical, I did a quick hue filter and made a blood bat portrait from the original, as well as a lighter version of the existing one to look more like the Level 0 Bat. The current Bat portrait could be used solely for the Dread Bat, as its colours better match the sprite.

**Comment by MetaKnight** [comment]
I added a new Outrider portrait that looks nicer than that of Elurin from THoT.

**Comment by gfgtdf** [comment]
The following units also miss poertraits (at least they did last time i checked) 'Walking Corpse,Soulless,Chocobone'  and of course the whole dunefolk.

**Comment by MetaKnight** [comment]
Could we have an official response on this? It would be great to know if there is any point in putting any further time an effort on this.

**Comment by MetaKnight** [comment]
@gfgtdf = The soulless and wc now have portraits

**Comment by MetaKnight** [comment]
How about the Orcish Ruler and Orcish Leader, they have an alternate (helm-less) portrait which could be the base for the leader, and the current Orcish Leader portrait which is used for both could be only for the Orcish Ruler.
I think many of them (Water Serpent, Fire Guardian etc.) were made by their respective artists for mainline, but the thread died out and so the art was forgotten. They aren't active anymore, but since their intent was for mainline, I believe we can safely consider to have their permission.

**Comment by nemaara** [comment]
Elvish Marshal has the same problem as the other proposed portraits: it doesn't match stylistically with what we have in mainline right now. Your proposal for the leader/ruler is okay to me, but I'll wait to change those around until I ask LordBob about his opinion.

**Comment by nemaara** [comment]
I've implemented the discussed changes in #4047. See also #4041 for the portraits doofus-01 added. Feel free to reopen or make another issue if there are more potential portraits that weren't addressed here.
