### ISSUE TITLE
Improve UI for enabling experimental PRNG combat

### ISSUE THREAD

**Issue by slavrenyuk** [wesnoth/wesnoth#4021]
Experimental PRNG combat presented in this thread https://forums.wesnoth.org/viewtopic.php?f=6&t=48160 looks very promising. However, it is hard to find that option (it is the last item in the advanced preferences) and it is not user friendly to enable it (both checkboxes "Use experimental PRNG combat" in advanced preferences and "Save random seed" in the campaign selection menu must be enabled).

The feature is currently available only for singleplayer campaigns. In order to promote it to more players I propose to:
1) Move the "Use experimental PRNG combat" checkbox from the advanced preferences to the campaign selection menu.
2) Once the "Use experimental PRNG combat" checkbox in the campaign selection menu is selected, "Save random seed" checkbox is also automatically selected and becomes non-editable.
3) Rename the "Use experimental PRNG combat" to something more specific and user friendly. For example, "Use more predictable random generator for combat" or "Reduce random deviations in combat"

**Comment by slavrenyuk** [comment]
That's probably too early to talk about that, but since I already spent some time thinking about this "Experimental PRNG combat" I would like to share my thought with developers. In my opinion this feature is too deterministic. What if the experimental RNG falls back to the default RNG in, for example, 5% of battles? Once again - just wanted to share this thought, no need to discuss it now.

**Comment by stevecotton** [comment]
Both the PRNG and "save random seed" could be presented to the user as if they were `[modification]`s, so in the bottom-left of the campaign menu.

**Comment by Vultraz** [comment]
Closing since this is addressed with @shikadiqueen's recent Campaign screen work.
