### ISSUE TITLE
Ubuntu 19.04 cursor theme broken in Flatpak version on Flathub

### ISSUE THREAD

**Issue by FurtiveDolus** [wesnoth/wesnoth#4024]
Title basically says it all. A lot of Flatpak'd games with custom cursor themes seem to have this problem all of a sudden. 0AD and OpenMW are two I've also seen this happen in. 
![Screenshot from 2019-04-14 20-49-06](https://user-images.githubusercontent.com/49626275/56103136-c87b4b80-5ef6-11e9-97b8-b9a9e9165366.png)

**Comment by loonycyborg** [comment]
If it's lots of games then consider making issue here: https://github.com/flatpak/flatpak/issues
Since I updated it to newer version of freedesktop runtime flatpak version supports wayland and will use it by default. What does it use for you? x11 fallback or wayland?

**Comment by FurtiveDolus** [comment]
Ubuntu doesn't use Wayland yet by default, so I have not tested it outside of X11 yet.

**Comment by loonycyborg** [comment]
If I try it on fedora it has broken cursor like in screenshot if I force it to use x11. It works fine via wayland.

**Comment by sevu** [comment]
@loonycyborg Closing as won't fix?

**Comment by loonycyborg** [comment]
Upstream issue flatpak/flatpak#2868 already exists so closing
