### ISSUE TITLE
UtBS - S2 Across the Harsh Sands, units suffer from poison during day despite +4 healer next to them

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4031]
[UtBS-Across the Harsh Sands Turn 4^.gz](https://github.com/wesnoth/wesnoth/files/3094209/UtBS-Across.the.Harsh.Sands.Turn.4.gz)
End the turn, Garak will be poisoned and lose hp due to being poisoned next turn despite being next to a +4 heal unit.
(Probably because of the dehydration thing. Units with the 'cure' ability cure properly.)

**Comment by Konrad22** [comment]
Actually, healing doesn't work during the day either. It's the same kind of problem.

**Comment by nemaara** [comment]
Behavior is intended, but I added an explanation to the player in objective notes. See e0cbfb6.
