### ISSUE TITLE
UtBS - S2 Across the Harsh Sands, scenario objectives do not update after defeating the outlaw leader

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4035]
That means both that no updated scenario objectives are actively shown and that looking at the scenario objectives after defeating said enemy leader still shows the old objectives (which include defeating the outlaw leader).
[UtBS-Across the Harsh Sands-Auto-Save51.gz](https://github.com/wesnoth/wesnoth/files/3096466/UtBS-Across.the.Harsh.Sands-Auto-Save51.gz)

**Comment by nemaara** [comment]
9f1fa79
