### ISSUE TITLE
'formation' (UtBS) works not exactly as described/description is misleading

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4036]
(There is [this](http://forums.wesnoth.org/viewtopic.php?f=38&t=4439&p=641375#p641375)
> Is it intended that the formation ability only works on offense? If so, I think that should be stated in the ability's description.

)
EDIT:
It does, but for some reason it doesn't work against/with units created by debug mode.

(And there is also the fact that it doesn't work on offense if the enemy unit has 'formation' as well.
[UtBS-Descending into Darkness Turn 8.gz](https://github.com/wesnoth/wesnoth/files/3097811/UtBS-Descending.into.Darkness.Turn.8.gz))
EDIT:
I'll need to test that in MP I guess?

(The first one is certainly important to know because assuming that it works on defense as well leads the player to build defensive formations based on that.)

**Comment by ProditorMagnus** [comment]
It takes 5 allies with formation to lower 80% cth to 70%. And 1 ally to lower 40% to 30%. Nothing about offense only.

**Comment by Konrad22** [comment]
Offense only -> You have to be the one attacking so that the lowering of cth is applied. If the enemy is the one attacking instead, it is not applied.

**Comment by Konrad22** [comment]
![formation](https://user-images.githubusercontent.com/39015360/56421047-f79c0f00-62a0-11e9-894a-d1d0de907a53.png)
CTH should be only 50% for the Flanker.

**Comment by ProditorMagnus** [comment]
No, it takes 3 allies with formation to reduce 60 to 50.

**Comment by ProditorMagnus** [comment]
Also, on master it will not work against ranged attacks because of 7f7217cf157393fc5fe3526a81181d95aa7fcbe9.

**Comment by Konrad22** [comment]
The issue is not relevant anymore, see discord dev from 'So, who had the idea to create the 'formation' ability? Is that person still around?'.

**Comment by CelticMinstrel** [comment]
[Direct link](https://www.wesnoth.org/irclogs/2019/04/%23wesnoth-dev.2019-04-19.log)
