### ISSUE TITLE
UtBS - S5 A Subterranean Struggle, inconsistent vision sharing with allies

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4037]
If you ally with the trolls: The cave system around the blue troll leader (side 2) is revealed and your vision is shared with his side. Nothing like that happens for your other ally, side 3.

If you ally with the dwarves: No new part of the map is revealed and there is no vision sharing.

That's
a) inconsistent and
b) it was different in older versions of the scenario, where the map was revealed around your allies and you shared vision with them.

**Comment by Wedge009** [comment]
It's been a long time since I played UtBS, but I recall allying with either side sharing vision and that's probably the intentions. At a guess something broke with the WML for allying with the dwarves.

**Comment by Konrad22** [comment]
Probably for the trolls too, since you don't get the shared vision with the side 3 trolls.

**Comment by DisherProject** [comment]
> If you ally with the trolls: The cave system around the blue troll leader (side 2) is revealed and your vision is shared with his side. Nothing like that happens for your other ally, side 3.
If you ally with the dwarves: No new part of the map is revealed and there is no vision sharing.

Can you please attach a game save? I can't reproduce this in master.

> b) it was different in older versions of the scenario, where the map was revealed around your allies and you shared vision with them.

Shared vision has been removed on purpose. As a matter of fact there are specific events when you sight the ally leaders.

**Comment by Konrad22** [comment]
Before finding the war
[UtBS-A Subterranean Struggle-Auto-Save9.gz](https://github.com/wesnoth/wesnoth/files/3100358/UtBS-A.Subterranean.Struggle-Auto-Save9.gz)

After finding the war
[UtBS-A Subterranean Struggle Turn 9.gz](https://github.com/wesnoth/wesnoth/files/3100361/UtBS-A.Subterranean.Struggle.Turn.9.gz)
End turn to update vision. Or look at the status table.

**Comment by nemaara** [comment]
af92c85
