### ISSUE TITLE
UtBS - S6b In the Domain of the Dwarves, dwarvish guards stay quiet after I blow the first wall up

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4038]
The dwarves are supposed to cry out https://github.com/wesnoth/wesnoth/blob/b023b818c742cee0bc75460235c9d1088c0b495d/data/campaigns/Under_the_Burning_Suns/scenarios/06b_In_the_Domain_of_Dwarves.cfg#L564, but the don't.

[UtBS-In the Domain of the Dwarves-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/3100373/UtBS-In.the.Domain.of.the.Dwarves-Auto-Save1.gz)
Give the signal to blow up the wall, end the turn.

**Comment by nemaara** [comment]
5c8152d
