### ISSUE TITLE
UtBS - S6b In the Domain of the Dwarves, Tentacles of the Depth are not spawned the first time

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4039]
Kaleh crys out about them, but none of them actually spawn. Next turn he says his next line about them, with them actually appearing.

[UtBS-In the Domain of the Dwarves Turn 21.gz](https://github.com/wesnoth/wesnoth/files/3100379/UtBS-In.the.Domain.of.the.Dwarves.Turn.21.gz)
End turn.

**Comment by nemaara** [comment]
b45ff18
