### ISSUE TITLE
LoW - S23, Landar's hero death event still fires when he is defeated

### ISSUE THREAD

**Issue by ever-3W** [wesnoth/wesnoth#4046]
![bug_landar](https://user-images.githubusercontent.com/42660111/56527162-d9d5e080-6512-11e9-8f39-84bb8ff6b3d2.png)

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/dcf6095966af3dd812cfd037e6b415a124de5e6a
