### ISSUE TITLE
Illuminating Campfires shifts schedule

### ISSUE THREAD

**Issue by Blackheart595** [wesnoth/wesnoth#4048]
In campaign The South Guard, scenario 8b The Tides of War uses the default schedule beginning with the second watch. If the map contains Illuminating Campfires due to surviving long enough in the preceding scenario, the area around the campfires that gets illuminated uses a default schedule starting with dawn. This means that time of day around the campfire is always one phase ahead of the rest of the map. This is different from the actual illumination effect of the campfire that changes the attack modifier for lawful units.

The following table shows which time of days are in effect simultaneously:

Map phase|Map time of day|Campfire phase|Campfire time of day
-|-|-|-
1/6|Dawn|2/6|Morning
2/6|Morning|3/6|Afternoon
3/6|Afternoon|4/6|Dusk
4/6|Dusk|5/6|First Watch
5/6|First Watch|6/6|Second Watch
6/6|Second Watch|1/6|Dawn

This e.g. means that by maneuvering in- and outside of the campfire area, one can abuse this mechanic to fight with only a single night phase and three day phases in a single day-night-cycle.

This behavior has been observed on version 1.14.6.

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/e2585a7fdf6361ffd4d3f4d6fbd402a6c13205e2
