### ISSUE TITLE
Classic theme bug: coordinates are not showing. 

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#4053]
On 1.14.7 in classical theme there are no coordinates and terrain movement costs anywhere in the GUI, they are gone from the place they were in previously (top right corner next to the clock).

Differences between versions:
1.14.4
![unknown (1)](https://user-images.githubusercontent.com/41817546/56870097-69dfc280-6a0a-11e9-8fc1-32e6794edb7a.png)

1.14.7
![unknown (2)](https://user-images.githubusercontent.com/41817546/56870101-6f3d0d00-6a0a-11e9-8a14-2bd9b365b79d.png)

**Comment by Wedge009** [comment]
I don't know that this is theme-specific - I note the co-ordinates are also missing in the default theme for 1.14.7... but I don't remember there being co-ordinates in older 1.14 releases either (though there may well have been for the classic 1.12 theme).

**Comment by jostephd** [comment]
> I don't know that this is theme-specific - I note the co-ordinates are also missing in the default theme for 1.14.7...

In the default theme the coordinates are shown under the minimap, above the time-of-day graphic.

@Hejnewar Can you bisect this?

**Comment by Wedge009** [comment]
Right - I don't remember all the details of the theme changes between versions...

**Comment by sevu** [comment]
It's probably has something to do with the battery icon fix, 1.14.5:
![1 14 4-271-6772682](https://user-images.githubusercontent.com/21158813/57420191-c4490200-7206-11e9-8ffd-55723639fb45.png)

**Comment by sevu** [comment]
conmpiled at 1.14.5-159-ddb3927, battery fixed, clock and coordinates gone.
![1 14 5-259-ddb3927](https://user-images.githubusercontent.com/21158813/57421426-088ad100-720c-11e9-9139-091086f3cc49.png)

**Comment by edwin7878** [comment]
1.13.4-158ddb3727

**Comment by jostephd** [comment]
@sevu What's 1.14.5-159-ddb3927? I don't have that.

@edwin7878 What are you saying? 1.13.4 is no longer supported.

**Comment by Wedge009** [comment]
Marking as confirmed with multiple reports.

**Comment by Lucibuki** [comment]
Does that say we just have to wait until they fix it?
Thanks for the response anyways ;)

**Comment by jostephd** [comment]
I've milestoned this for the next release so we don't forget it, but we still need someone to actually work on the issue.

**Comment by Wedge009** [comment]
I tried bisecting between 1.14.5 and 1.14.6, but even that proved to be too much - there are far too many compilation errors with things like boost (the `tribool` change I could resolve myself but not the executor == operator error - can't find which commit resolved that) and specialisation of `std` namespace in `synced_commands.hpp`.

**Comment by jostephd** [comment]
Made some progress. If I apply this diff:

```
diff --git a/data/themes/classic.cfg b/data/themes/classic.cfg
index dfc13215ce0..c25e79ee0a3 100644
--- a/data/themes/classic.cfg
+++ b/data/themes/classic.cfg
@@ -359,6 +359,7 @@
             # so that the long strings don't get cut off as easily.
             [panel]
                 id=terrain-panel
+                ref=status-income
                 rect="+0,=,1024,="
                 xanchor=left
                 yanchor=fixed
```

then, **when does_device_have_battery return true**, I get the x,y and terrain descriptions strings on top of the battery and clock information:

![2019-10-24-062837_223x29_scrot](https://user-images.githubusercontent.com/24784687/67459220-8f4f3100-f627-11e9-9e9e-6e74b11bd81c.png)

So we "just" need to find out what the correct `ref` is. And to make sure the [no_battery] case is correct as well.

**Comment by Wedge009** [comment]
I had a quick look at the classic theme configuration as well. If you make further progress I can test both desktop and laptop (no-battery and battery) cases.

**Comment by ProditorMagnus** [comment]
Is this the thing vultraz removed?

**Comment by Wedge009** [comment]
I don't know, but perhaps not - as I mentioned in #4515, the most recent committers to `classic.cfg` were jyrki and hrubymar (and this was at the time the theme started breaking).

**Comment by Pentarctagon** [comment]
It was removed from master in e718d1e472e870f68e945485e688764531790c90.

**Comment by Vultraz** [comment]
Classic theme removed from 1.14 in 7be4237.
