### ISSUE TITLE
[Question] Backport Damage type and range icons from master?

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#4062]
## Brief
I recently noticed that there is new **Damage type and range icons** feature in master branch.

This feature is from @jostephd and I like it. So as 1.15 and 1.16 don't seems to be released anytime soon I want to discuss if we could backport this feature to 1.14 .

Project for that feature: https://github.com/wesnoth/wesnoth/projects/4

### 1.15 from 4d168369e29
<img width="177" alt="image" src="https://user-images.githubusercontent.com/2218817/57227676-42908300-7012-11e9-93e2-d7a8fd82c9e4.png">

### 1.14 from 4ce5b52c4e821e5d20b82f83e519e6402547df92
<img width="178" alt="image" src="https://user-images.githubusercontent.com/2218817/57225589-26d6ae00-700d-11e9-9c91-8a9562c29261.png">

## Things which I have to mention
* (@jostephd ) If a unit has two attacks, one of the attacks has mainline ranges/types and one attack has custom ranges/types, then it'd look a bit funny... That's the only downside to backporting that I can think of.
* (@hrubymar10 ) Icons makes the space for text smaller. It could be problem for some longer texts
* (@hrubymar10 ) There are some icons missing (for example in case of lightning (magic attack))

## Ping
@jostephd , @Vultraz , @jyrkive and anyone else who has opinion

**Comment by jostephd** [comment]
> (@hrubymar10 ) There are some icons missing (for example in case of lightning (magic attack))

There are icons for the standard ranges (melee/ranged) and damage types (arcane/cold/fire/blade/impact/pierce). Your screenshot shows a unit that uses a custom range, "electrical", which doesn't have an image, so the code falls back to the texty display. That is important for compatibility with existing UMC that uses custom ranges or damage types (like Era of Magic).

**Comment by hrubymar10** [comment]
Also this feature will be real advantage for iOS version, especially the iPhone version. This feature makes height of attack smaller so attack informations could fit even in smaller displays.

@singalen ^^

**Comment by jyrkive** [comment]
I don't really have an opinion about backporting the icons.

**Comment by stevecotton** [comment]
Closing because the passage of time has made "should we backport to 1.14" an obsolete question.
