### ISSUE TITLE
Remove "Stable 1.14" label from issues that affect 1.15

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4065]
Some of the issues on https://github.com/wesnoth/wesnoth/labels/Stable%201.14 affect master (1.15) as well. We should remove the label from those issues, that label makes them seem like lower priority than they really are.

**Comment by ProditorMagnus** [comment]
So by default, without labels, issue is expected to target all versions?

**Comment by jostephd** [comment]
Most issues are about master and 1.14, yes. We don't have a separate label for "affects master only".

The "Stable 1.14" label basically means "this issue doesn't apply to master".

**Comment by Wedge009** [comment]
I removed a few - I agree that the 1.14 tag should only be used on 1.14-specific issues. I suspect many others could be removed as well, but I don't know how to or couldn't replicate them.

**Comment by sevu** [comment]
Removed from the open issues. It were mostly issues from the time around the 1.14 release.
