### ISSUE TITLE
wesnoth crash during AI turn

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#4068]
This was in the console:

```
wesnoth: /build/wesnoth/src/wesnoth/src/attack_prediction.cpp:1668: static void {anonymous}::monte_carlo_combat_matrix::scale_probabilities(const std::vector<double>&, std::vector<double>&, double, unsigned int): Assertion `std::abs(std::accumulate(target.begin(), target.end(), 0.0) - 1.0) < 0.001' failed.
```

wesnoth version 1.14.7

CC @jyrkive 

It happen in CreepWars, leaders had about 200-300 HP at that moment and about 30-10 damage-strikes.

**Comment by jyrkive** [comment]
I'm afraid that's not enough data for me to really figure out anything. I'd need a save file as near as possible before the crash.

**Comment by vgaming** [comment]
I wasn't sure it'll be needed so didn't attach from the beginning. Fixing the mistake, here's the savegame:

[Creep Wars snow 1.5.1-Auto-Save36.zip](https://github.com/wesnoth/wesnoth/files/3165251/Creep.Wars.snow.1.5.1-Auto-Save36.zip)

Crash happens if you load the savegame and end the turn.

**Comment by jyrkive** [comment]
Thanks. I plan to investigate the issue tomorrow.

**Comment by vgaming** [comment]
For possible future reference: to repro you must also have Ageless installed, and Monte Carlo AI algorithm enabled in Preferences.

**Comment by vgaming** [comment]
Thanks!
