### ISSUE TITLE
Sidebar selected_unit_weapons report doesn't determine which weapon specials are active correctly

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4071]
When a unit with drains and backstab attacks an Orcish Grunt, the damage calculations dialog looks like this:

![2019-05-11-132246_1920x1049_scrot](https://user-images.githubusercontent.com/24784687/57570301-ebaef300-73ef-11e9-854b-7f39ff2053dc.png)

Note how the words "backstab" and "drains" are shown in different colors, because drains is active (Orcs aren't immune to drains) but backstab is not (there isn't an ally of the Thief behind the orc).

I use a [custom theme](https://forums.wesnoth.org/viewtopic.php?f=6&t=41065&hilit=asymmetric&start=15#p633615) that displays `selected_unit_weapons` in the sidebar. That report shows the same information as the Damage Calculations dialog:

![2019-05-11-132014_1920x1080_scrot](https://user-images.githubusercontent.com/24784687/57570267-a094e000-73ef-11e9-8f6d-cb5a05d30a6a.png)

The word "drains" and "backstab" are shown in different colors depending on whether the weapon special is active or not, but the determination of "is active?" is wrong. For example, when backstabbing a Soulless, "backstab" is shown as inactive and "drains" as active, even though it should be the other way around:

![2019-05-11-135716_1920x1049_scrot](https://user-images.githubusercontent.com/24784687/57570747-e86a3600-73f4-11e9-9827-728eaf757168.png)

The weapon specials are added to the report here: https://github.com/wesnoth/wesnoth/blob/08979a6736b3fc778cc40022714076c5ccdc8e2b/src/reports.cpp#L874-L896

**Comment by gfgtdf** [comment]
Not 100% sure whether it's related but the was iirc a controversial change in 1.12 that made all weapon specials filters default to true on the sidebar. This was iirc in particular controversial because it made units that appear in loti that had two attack specials "x2 damage against elves" and "x2 damage against orcs" show the x4 damage even though the unit would obviously never get x4 damage against any unit.

**Comment by jostephd** [comment]
> Not 100% sure whether it's related but the was iirc a controversial change in 1.12 that made all weapon specials filters default to true on the sidebar.

I don't see that. I had the code print "active" or "inactive" and it looks like this:

![2019-05-15-110941_1920x1080_scrot](https://user-images.githubusercontent.com/24784687/57771365-08a23980-7702-11e9-8edc-82faa51a36e3.png)

**Comment by gfgtdf** [comment]
I mistyped I meant that all filters filtering the enemy like [filter_opponent] iirc now default to true.

**Comment by jostephd** [comment]
Ah, thanks for clarifying that. The change in 1.12 was to the regular `unit_weapons` report, right? In that context we don't have an enemy to work with, so maybe we can't be right in _every_ case, for exapmle, some other addon could have "x2 damage against all but orcs" and "x2 damage against all but elves" specials... but in the `highlighted_unit_weapons`/`selected_unit_weapons` report we deal with _two_ units, the selected unit and the mouseover unit, so the problem won't arise: we should be able to run the filters on the actual enemy unit.

I think it's just a matter of replacing the call to `specials_context_for_listing` by a call to one of the other specials_context getters..

**Comment by Leonard03** [comment]
Can't seem to be able to reproduce this issue. The code from reports.cpp above is different than what's currently in the master branch, perhaps it's a bug in the custom theme?

**Comment by jostephd** [comment]
@Leonard03 Good catch. I was trying with 1.14 so I linked the 1.14 source code. I have now re-tested in master and there all specials show as active. This is likely due to the change @gfgtdf remembered.

So yes, the situation in master and 1.14 is different, but I stand by my opinion that when the report [simulates a concrete battle between two specific units](https://forums.wesnoth.org/download/file.php?id=83887&t=1), it should display the enabled/disable values for that particular battle, not just "enabled" across the board. What do you think?

**Comment by Leonard03** [comment]
@jostephd That makes sense to me, but at that point it is it perhaps more of a "feature" that would be nice rather than a bug?

**Comment by jostephd** [comment]
@Leonard03 Yes. Labels changed. Thanks. Are you interesting in writing a patch for this issue, by the way? Happy to help if so.

**Comment by Leonard03** [comment]
@jostephd I'm down to give it a shot, yes.

**Comment by jostephd** [comment]
Fixed in #4107
