### ISSUE TITLE
Sand Scuttler and Giant Scorpion

### ISSUE THREAD

**Issue by Gweddeoran** [wesnoth/wesnoth#4076]
I remember there being an old Giant Scorpion portrait that was removed not because of quality but rather as the old sprite didn't seem menacing enough to match the portrait. With the introduction of the Giant Scorpling though, I think the new Giant Scorpion portrait could be used for the Level 0 and the old portrait for the Level 1 Giant Scorpion.
Further, akin to the Dread Bat, which uses a recolour of the Blood Bat (hardcoded in the .cfg file), the Scorpion portraits could be tweaked to match the Sand Scuttler by making the hue more brown.

Thanks in advance 😃

**Comment by Wedge009** [comment]
Has this suggestion been put forward in the forums? Seems like artistic decisions like this are more enthusiastically discussed there.
