### ISSUE TITLE
Status icons not showing in sidebar in Dead Water

### ISSUE THREAD

**Issue by sigurdfdragon** [wesnoth/wesnoth#4079]
When a unit is poisoned or slowed in 1.15.0-dev, the status icons don't show for the unit in the sidebar.

**Comment by jostephd** [comment]
To anyone fixing this, please also test that when a unit is _both_ poisoned and slowed, both icons show, or at least one icon with an ellipsis indicating there are more statuses.

**Comment by DisherProject** [comment]
@sigurdfdragon i've just built wesnoth (at https://github.com/wesnoth/wesnoth/commit/4830028142dfdd5fc14a0609510f59f8ed277b9e) and the status icons are shown

![Screenshot (5)](https://user-images.githubusercontent.com/29802612/59878419-87952c80-93a8-11e9-85e6-a5012e706b9d.png)

Or perhaps i have misunderstood the issue

**Comment by jostephd** [comment]
@DisherProject Your screenshot shows the right outcome: it shows the snail for slowed and the ellipsis for poisoned. I just tested myself and I get the same behavior as you in AToTB S4, however, if I create a slowed/poisoned unit in the test scenario (`wesnoth -t` then `:unit status=poisoned` and `:unit status=slowed`) then I don't see either status icon. Any idea why the status icons don't show in the test scenario?

**Comment by sigurdfdragon** [comment]
@DisherProject Still getting the issue
I'm running a 64-bit build of master branch
The Battle for Wesnoth version 1.15.0-dev (4830028142d-Modified)
Running on Microsoft Windows 7 Service Pack 1 (6.1.7601)

Libraries
=========

Boost:             1.70
OpenSSL/libcrypto: 1.1.1b (runtime 1.1.1b)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.43.0 (runtime 1.43.0)
SDL:               2.0.9  (runtime 2.0.9)
SDL_image:         2.0.4  (runtime 2.0.4)
SDL_mixer:         2.0.4  (runtime 2.0.4)
SDL_ttf:           2.0.15 (runtime 2.0.15)

Features
========

JPG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: yes
Win32 notifications back end:   yes

**Comment by jostephd** [comment]
@sigurdfdragon What scenario do you get that behavior in? As I said, for me it works in some scenarios but not others. I tested the same commit hash as both of you.

**Comment by sigurdfdragon** [comment]
@jostephd I tested it in AOI S01 and MP Den of Onis. Originally saw it during an SP campaign, not sure which one

**Comment by jostephd** [comment]
@sigurdfdragon Works for me in AOI S01:

![2019-06-25-102738_413x295_scrot](https://user-images.githubusercontent.com/24784687/60091350-e73a6180-9733-11e9-8bb4-1291127f1e30.png)

I use the default theme, I tested both 800x600 and 1920x1080.

**Comment by jostephd** [comment]
And see #3197

**Comment by sigurdfdragon** [comment]
Not sure why it's not working for me.

**Comment by Wedge009** [comment]
@sigurdfdragon Is this still a problem for you? I just tried with 1.14 and master with no apparent issue.

**Comment by sigurdfdragon** [comment]
@Wedge009  Yes, still occurring in my build of master

**Comment by jostephd** [comment]
In master, I see the "petrified" icon for the Elvish Avenger at 4,8 if I apply the following patch, but not otherwise:

```
--- a/data/scenario-test.cfg
+++ b/data/scenario-test.cfg
@@ -1207,19 +1208,6 @@ end
                 function has_teleport(u)
                     return wesnoth.unit_ability(u, "teleport")
                 end
-                local old_unit_status = wesnoth.theme_items.unit_status
-                function wesnoth.theme_items.unit_status()
-                    local u = wesnoth.get_displayed_unit()
-                    if not u then return {} end
-                    local s = old_unit_status()
-                    if u.status.entangled then
-                        table.insert(s, { "element", {
-                            image = "misc/key.png",
-                            tooltip = "entangled: This unit is entangled. It cannot move but it can still attack."
-                        } })
-                    end
-                    return s
-                end
             >>
         [/lua]
     [/event]
```

@sigurdfdragon Do you use any mods that overwrite wesnoth.theme_itemes.unit_status?

**Comment by sigurdfdragon** [comment]
Yes, one. Will post test results as soon as I can get my master branch to work again.

**Comment by sigurdfdragon** [comment]
Yes, that was it. I had code just like that for stun effect lifted from Dead Water. Removing my mod fixed it.
However, said code is still in DW, and still causing this bug there.

**Comment by jostephd** [comment]
I put a debug printf in reports::generate_report:

https://github.com/wesnoth/wesnoth/blob/dbe9d60c1f174d911fb70a1f9f8af46133affc9b/src/reports.cpp#L1739-L1750

and what's happening is that the returned config object is empty. With the patch in my previous comment, the returned object is this:

```
[element]
	image = misc/petrified.png
	tooltip = petrified: This unit has been petrified. It may not move or attack.
[/element]
```

**Comment by jostephd** [comment]
So, here:

https://github.com/wesnoth/wesnoth/blob/dbe9d60c1f174d911fb70a1f9f8af46133affc9b/src/scripting/game_lua_kernel.cpp#L3816-L3826

`luaW_getglobal(L, "wesnoth", "theme_items", "unit_status")` returns false. Stepping into it, it seems to think wesnoth.theme_items.unit_status is nil. However, if I select (click) the Elvish Avenger and execute `wesnoth.theme_items.unit_status()` in the lua console, it works and returns the same config object as in my last comment. Also, `nil == wesnoth.theme_items.unit_status` evaluates to `false`. What's missing here, then? Maybe something wrong in the __newindex?

https://github.com/wesnoth/wesnoth/blob/dbe9d60c1f174d911fb70a1f9f8af46133affc9b/src/scripting/game_lua_kernel.cpp#L3853-L3864

**Comment by jostephd** [comment]
Actually, on a closer look, even this reproduces the problem:

<details>

<summary>
patch that reproduces the problem
</summary>

```
--- a/data/scenario-test.cfg
+++ b/data/scenario-test.cfg
@@ -1207,19 +1207,8 @@ end
                 function has_teleport(u)
                     return wesnoth.unit_ability(u, "teleport")
                 end
-                local old_unit_status = wesnoth.theme_items.unit_status
-                function wesnoth.theme_items.unit_status()
-                    local u = wesnoth.get_displayed_unit()
-                    if not u then return {} end
-                    local s = old_unit_status()
-                    if u.status.entangled then
-                        table.insert(s, { "element", {
-                            image = "misc/key.png",
-                            tooltip = "entangled: This unit is entangled. It cannot move but it can still attack."
-                        } })
-                    end
-                    return s
-                end
+                local s = wesnoth.theme_items.unit_status
+                s = nil
             >>
         [/lua]
     [/event]
```

</details>

And this fixes it:

<details>

<summary>
patch that fixes the problem
</summary>

```
--- a/data/lua/core.lua
+++ b/data/lua/core.lua
@@ -598,7 +598,6 @@ if wesnoth.kernel_type() == "Game Lua Kernel" then
        wesnoth.skip_messages = wesnoth.deprecate_api('wesnoth.skip_messages', 'wesnoth.interface.skip_messages', 1, nil, wesnoth.interface.skip_messages)
        wesnoth.add_tile_overlay = wesnoth.deprecate_api('wesnoth.add_tile_overlay', 'wesnoth.interface.add_hex_overlay', 1, nil, wesnoth.interface.add_hex_overlay)
        wesnoth.remove_tile_overlay = wesnoth.deprecate_api('wesnoth.remove_tile_overlay', 'wesnoth.interface.remove_hex_overlay', 1, nil, wesnoth.interface.remove_hex_overlay)
-       wesnoth.theme_items = wesnoth.deprecate_api('wesnoth.theme_items', 'wesnoth.interface.game_display', 1, nil, wesnoth.interface.game_display)
        wesnoth.get_displayed_unit = wesnoth.deprecate_api('wesnoth.get_displayed_unit', 'wesnoth.interface.get_displayed_unit', 1, nil, wesnoth.interface.get_displayed_unit)
        wesnoth.gamestate_inspector = wesnoth.deprecate_api('wesnoth.gamestate_inspector', 'gui.show_inspector', 1, nil, gui.show_inspector)
        -- Units module
```

</details>

The line being removed by that patch doesn't exist in 1.14, so that's why that branch works.

As to that patch, I think I see why it works.

First things first, [the documentation of wesnoth.deprecate_api](https://github.com/wesnoth/wesnoth/blob/dbe9d60c1f174d911fb70a1f9f8af46133affc9b/data/lua/core.lua#L173-L182) says the fifth parameter should be `wesnoth.interface.game_display`, not `wesnoth.theme_items`, but that doesn't matter in this case, because [they're equivalent](https://github.com/wesnoth/wesnoth/blob/dbe9d60c1f174d911fb70a1f9f8af46133affc9b/data/lua/core.lua#L466). (Also, I tried correcting the fifth argument and that didn't fix the bug.)

What does happen here is that `wesnoth.theme_items` starts out as a table, so we fall into this block:

https://github.com/wesnoth/wesnoth/blob/dbe9d60c1f174d911fb70a1f9f8af46133affc9b/data/lua/core.lua#L204-L226

and `wesnoth.theme_items` starts out with a metatable, too, so line 224 is executed... and _sets the metatable of the the new table's metatable_ to the original `wesnoth.theme_items`' metatable. That's a bug, isn't it?

**Comment by jostephd** [comment]
PR #4376
