### ISSUE TITLE
wmllint: "speaks in die event" may read the id from the wrong filter

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4085]
The following code example triggers a false-positive warning that Ras-Tabahn speaks in his "die" event rather than "last breath". Seen with the wmllint from 1.14.7, it seems wmllint assumes that the first `[filter]` tag with an `id=` is the event's filter.

```
    [event]
        name=die
        [filter]
            type="DoE Mortuary Caravan"
        [/filter]
        [lift_fog]
            [filter]
                id=Ras-Tabahn
            [/filter]
        [/lift_fog]
        [message]
            id=Ras-Tabahn
            message= _ "You left the caravans unprotected? I expected you to at least hide them in the castle."
        [/message]
        [endlevel]
            result=defeat
        [/endlevel]
    [/event]
```

**Comment by jostephd** [comment]
I assume the error is this one:

https://github.com/wesnoth/wesnoth/blob/d513c0db60dc82fc65810d40cf6104644791e001/data/tools/wmllint#L1453-L1493

I guess the error is on line 1468: it shouldn't recurse upward past the [lift_fog] tag.

**Comment by stevecotton** [comment]
Line 1463 looks as if it wouldn't handle nested events.

**Comment by stevecotton** [comment]
@soliton- thanks, but please would you merge to master too?

**Comment by soliton-** [comment]
Good point, I‘m rarely in a proper dev environment though so it’d help if you can make PR for that as well.

**Comment by stevecotton** [comment]
It'll probably be another week before I have time to make the PR for master. Possibly quicker, because it mainly needs the computer's time for building and running the tool, and less of my time for sanity-checking the results.
