### ISSUE TITLE
helper.shuffle: potential DoS attack

### ISSUE THREAD

**Issue by spixi** [wesnoth/wesnoth#4100]
helper.shuffle takes an arbitrary function as a parameter. If used with a large table and a compute-intensive function, this may allow a DoS attack.

helper.shuffle should use a whitelist for allowed functions.

**Comment by gfgtdf** [comment]
being able to freeze the client is not a bug, in fact it is as easy as writing `while True do end` in Lua.

**Comment by spixi** [comment]
Isn’t the helper.shuffle command passed to the remote clients, when you are in debug mode?

**Comment by gfgtdf** [comment]
no, you can lookup the definition in https://github.com/wesnoth/wesnoth/blob/0bf377ab9fe5f4fd44a62d4ff4117a1f133fffc0/data/lua/helper.lua#L201

**Comment by spixi** [comment]
Ok, then this can be closed. Sorry.
