### ISSUE TITLE
confirm to observe game using moderator rights

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#4101]
Please add confirmation before force-observing games using Moderator rights.

This can happen accidentally because observing happens by simply clicking the Observe button for a Moderator, with currently no prompt whatsoever. It is relatively easy to miss the "no observers allowed" icon in the game list: it's on the right, far away from map icon and description.
Moderator observation is only meant to fight spam / abuse (see GH-2851). Players also get distracted because they see "*** joined the game" chat notification. A confirmation could help preventing that.

### Current behavior:
you can join a private game with just a double click

### Expected behavior:
show a confirmation dialog asking if you really want to use moderator rights to observe a game

**Comment by ProditorMagnus** [comment]
It is issue new to 1.14 since those games are no longer red.
