### ISSUE TITLE
ubuntu 18 flatpak wesnoth 1.14.7: Color mouse cursor seems to be missing its icon

### ISSUE THREAD

**Issue by lawkaita** [wesnoth/wesnoth#4104]
Did clean install of ubuntu 18.04.
Installed flatpak.
Installed wesnoth 1.14.7 from flathub.

Color mouse cursor seems to be missing its icon:

[Screenshot: Menu (google drive)](https://drive.google.com/open?id=1JOcn22CdqA3RWi2yeWzOEBqEmrz2tPxX)
[Screenshot: In-Game (google drive)](https://drive.google.com/open?id=1OXtrCjzG26YiHIngbhEBdd4MdebmUBKo)

This effect happens also in fullscreen.

Installed wesnoth 1.12.6 from apt.
Problem is not present in this version & install method.

**Comment by Pentarctagon** [comment]
Sounds like a duplicate of #4024 ?

**Comment by GregoryLundberg** [comment]
I was thinking the same thing. That issue was closed as an upstream issue. I was about to search for it, thanks.

**Comment by lawkaita** [comment]
Seems exactly the same as #4024 to me also.
As said there, flatpak issue exists:

> Upstream issue flatpak/flatpak#2868 already exists so closing

Closing.
