### ISSUE TITLE
Dark Adept does not lose traits when advancing to Lich

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#4108]
Steps to reproduce:
* start any game as UD faction (Default Era)
* buy Dark Adept
* advance it twice in battles, or quicker, enable debug menu `:debug`, hover the unit and type in `unit advances=2`

Expected at this point: Adept advances to Lich, their only trait being "undead"

Actually: Lich has 3 traits. E.g. "resilient", "quick", "undead".

**Comment by ProditorMagnus** [comment]
Why should it lose traits?

**Comment by vgaming** [comment]
@ProditorMagnus it was the behavior in 1.12 IIRC, and even previous versions of wesnoth in 1.14 line.

**Comment by ProditorMagnus** [comment]
So it is oos issue?

**Comment by vgaming** [comment]
indeed it could be I think.. IF indeed 1.14.0 had different behavior.

**Comment by vgaming** [comment]
it's very weird that it went unnoticed for so long though, need to double-check if indeed 1.14.0 had the behavior I'm expecting.

**Comment by vgaming** [comment]
I'll try to compile `1.14.0` to test now...

**Comment by vgaming** [comment]
Konrad2 says that behavior on 1.12 is the same. So probably it's not a bug at all.

**Comment by Konrad22** [comment]
It matches with 1.14.0 behavior as well.

**Comment by sevu** [comment]
One _could_ change it for 1.15 though…

**Comment by Konrad22** [comment]
But based on what reasoning?
You could also change it so that created/recruited Lichs have traits.
