### ISSUE TITLE
Translation oversight: Recommended setting of gold per village

### ISSUE THREAD

**Issue by spixi** [wesnoth/wesnoth#4110]
For 5p The Wilderlands and 6p Crusaders Field, the German translation is wrong. The English text says "Recommended setting of 1 gold per village." but the German one says  "Recommended setting of 2 gold per village."

I don’t know how many further languages are affected.

https://github.com/wesnoth/wesnoth/blob/master/po/wesnoth-multiplayer/de.po#L2376

**Comment by sevu** [comment]
Thanks. Changed it on the 1.14 branch.
Btw, would you have interest in updating the German translation?

**Comment by spixi** [comment]
I know, such stuff can happen, when you work with tools like Poedit, which suggest you a 99 % match and you just click "Apply". If I had more time, I could help you with translation ...
