### ISSUE TITLE
Duplicate entries for current scenarios in replay statistics

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4111]
When you load a replay savefile (it must be a replay savefile, not a regular savefile with "Show replay" checked) and open the statistics dialog, there are two entries for the current scenario. The first entry shows the end-of-scenario stats, like for all previous scenarios. The second entry shows the statistics through the current point in the replay:

![2019-06-11-100421_247x237_scrot](https://user-images.githubusercontent.com/24784687/59263295-4d04f480-8c30-11e9-8716-65791fc4829a.png)

The two entries have the same name. One or the other should be renamed or removed.

**Comment by jostephd** [comment]
The error propagates to the "All Scenarios" view. For example, if you play a replay to the end and open the All Scenarios view, it will count the events of the current scenario twice.

**Comment by Wedge009** [comment]
Confirmed on 1.14.17 - I don't have any replays for versions beyond that at present.

**Comment by CelticMinstrel** [comment]
Apparently fixed in #7585 / 01f28b1.

**Comment by Wedge009** [comment]
Comparing master and 1.16.9 release, it seems so.
