### ISSUE TITLE
Considering using new terrains in campaigns

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4121]
1.13 added new castles for meerfolk (also possibly usable for nagas), Trolls, an destroyed elven variation and an undead variation for Encampments. Also gates, though these have already been handled. Best to check all campaigns if there is some use for them. This has partly be done, let's make a list to keep track:
- [x] ATotB
- [x] TSG
- [x] AOI
- [x] HttT
- [x] L
- [x] EI
- [x] DiD
- [x] THoT
- [x] DW
- [x] DM
- [x] TRoW
- [x] SoF
- [x] LoW
- [x] SotA
- [x] SotBE
- [x] UtBS
- [x] NR
- [x] WoV
- [x] Maybe MP maps?

I checked the ones I know about, please check if you know that have been dealt with.

**Comment by CelticMinstrel** [comment]
I'm pretty late to this party, maybe too late, but I don't think the merfolk castles really suit nagas. I think if naga built castles I'd expect them to be on land, not in the water (or at least partially on land). Perhaps something a little like the swamp villages?

**Comment by nemaara** [comment]
WoV can handle itself when the revision comes in and we review it then. The rest have been taken care of now.
