### ISSUE TITLE
wmlunits: three issues

### ISSUE THREAD

**Issue by spixi** [wesnoth/wesnoth#4124]
wmlunits has several issues which can be seen on the page of my [honeycomb faction](https://units.wesnoth.org/1.14/Honeycomb/en_US/honeycomb.html).

1. When an add-on depends on another (for example the Ageless resource pack), images are not shown correctly
2. Custom `[drains]` specials are not displayed (see unit Gnat, which has a 1-1 drains attack which heals 100 % of the damage done)
3. If a unit only has 1 MP, movement costs are not shown (the units Bug and Isopod can move on flat and catle, though)

**Comment by Slayer95** [comment]
> When an add-on depends on another (for example the Ageless resource pack), images are not shown correctly

Still a bug.

> Custom [drains] specials are not displayed (see unit Gnat, which has a 1-1 drains attack which heals 100 % of the damage done)

This is just an add-on bug. That special is missing a ``name`` attribute.

> If a unit only has 1 MP, movement costs are not shown (the units Bug and Isopod can move on flat and catle, though)

Fixed in 8a2faf24e3

**Comment by Slayer95** [comment]
> Seems to work with https://units.wesnoth.org/1.14/Honeycomb/en_US/honeycomb.html including ../../pics/add-ons%24Ageless_Resources%24general%24images%24units%24hive%24ant.png

https://units.wesnoth.org/1.16/To_Lands_Unknown/en_US/To_Lands_Unknown.html doesn't show Era of Magic images, however.

Maybe an addon issue, too?
