### ISSUE TITLE
Deleting a save can select an entry not in the (visible) list when using the search function

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4125]
Since illustrating the issue is probably the best way to explain it:
![filter1](https://user-images.githubusercontent.com/39015360/59702857-f92e7880-91f8-11e9-85aa-9c636e539bbd.png)
Deleting the selected savefile...
![filter2](https://user-images.githubusercontent.com/39015360/59702865-fc296900-91f8-11e9-8b93-5d6b06b19936.png)
The now selected savefile does not match the search criteria and is hidden. It was created in the time between the autosave 11 and 12.

**Comment by soliton-** [comment]
https://github.com/wesnoth/wesnoth/blob/7a96934c714dd3a390ae95848323ddad55abdcd1/src/gui/widgets/generator.cpp#L68

Seems like there is already a todo note for the issue.
