### ISSUE TITLE
Changing the sound played for the undead summoning in DM, S7

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4127]
This scenario revolves about undead summoning stones. Right now it plays the 'healing' sound and I propose changing said sound to the sound which is played when a necromancer recruits undead units, because I think that would be more fitting.
I heard somewhere that bothering @sigurdfdragon about this is my best bet to get it implented. :D

**Comment by sigurdfdragon** [comment]
> Right now it plays the 'healing' sound and I propose changing said sound to the sound which is played when a necromancer recruits undead units, because I think that would be more fitting.
Yes indeed

**Comment by sigurdfdragon** [comment]
@Konrad22 Thanks for pointing it out. Please let me know if you see anything else odd like that with DM.
Saw the discussion about the S08 ending on discord, thinking about how to handle that.
