### ISSUE TITLE
HttT: moving armor icon to core

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4128]
The file [data/campaigns/Heir_To_The_Throne/images/icon_armor.png](https://github.com/wesnoth/wesnoth/blob/1.14/data/campaigns/Heir_To_The_Throne/images/icon_armor.png) could be moved to core, being available for shop systems. What I'm still missing for that is a new name.

**Comment by Wedge009** [comment]
Oh, this is for the scenarios where you can pick up bonus items for a small boost? What kind of new name is needed?

**Comment by sevu** [comment]
Yes. Current name is icon_armor.png – The ones in https://github.com/wesnoth/wesnoth/tree/1.14/data/core/images/icons are more descriptive.

Maybe breastplate2.png ?

**Comment by Wedge009** [comment]
Perhaps, it looks similar to [breastplate.png](https://github.com/wesnoth/wesnoth/blob/master/data/core/images/icons/breastplate.png)

**Comment by sevu** [comment]
One more issue closes, moved it in 116a667
