### ISSUE TITLE
MP Lobby: keeps cache of old games

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4148]
1) Join the Lobby – if there are currently not many games it's easier to see. Remember how the state is, e.g. how many green games.
2) open the create game screen… abort after a while
3) For a moment the lobby shows the gamelist like it was when you joined the lobby originally. After half a second it's updated.

Also, if you repeat step 2, still the original gamelist from first joining is shown.

**Comment by Pentarctagon** [comment]
I think it's less that it keeps a cache, and more that the half second it what it takes to update the game list in the lobby.

**Comment by sevu** [comment]
Not exactly – the game list shown for half the second is not the one which was actual at the point I switched to game creation.

**Comment by stevecotton** [comment]
> Not exactly – the game list shown for half the second is not the one which was actual at the point I switched to game creation.

PR #4192 opened for this.

**Comment by Vultraz** [comment]
@stevecotton @sevu ^ should address this, but I'd like additional confirmation (it's on 1.15 only).

**Comment by Vultraz** [comment]
Closing this. Please re-open if this becomes an issue again (though it should not).
