### ISSUE TITLE
An android game using wesnoth's sprites

### ISSUE THREAD

**Issue by druskus20** [wesnoth/wesnoth#4149]
Ive been a long time wesnoth player since I was a child. Today, I saw an androdi game on the google play store using your unit sprites.
The game is called Everybody's RPG. By NomadGames.
I dont know if you are aware of it, neither if they have permission, just thought It would be fair to let you know

**Comment by Pentarctagon** [comment]
It's been brought up a couple times, yeah.  The main problem being that, even if they are inappropriately using Wesnoth's/GPL licensed art, it simply isn't practical for us to go after these sorts of people or groups who may or may not be violating the GPL.
