### ISSUE TITLE
Spider Walking Corpse can cause OOS in 1.14

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4150]
Commits afd5a2db and 7a103d17 add spider variations of the walking corpse to the 1.14 branch, both of these commits are after 1.14.7. This can cause OOS, the example that I'm aware of is plaguing a spider, doing 18-24 hp of damage to the WC (enough to kill a normal WC, but not a spider WC), and then doing anything that depends on the unit still existing.

Replay showing the OOS (to see the OOS, view it with a plain 1.14.7 build):
https://replays.wesnoth.org/1.14/20190702/spiders_vs_zombies_Turn_1_(54093).bz2

**Comment by Pentarctagon** [comment]
Those commits should be reverted on 1.14 then, I assume?  The different movetype could also probably an OOS.

**Comment by gfgtdf** [comment]
Yes I agree

**Comment by Pentarctagon** [comment]
Closing as those commits have been reverted on 1.14.
