### ISSUE TITLE
Command line --preprocess misses data/core/units.cfg (LESS_NIMBLE_ELF, etc)

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4152]
The logic in wesnoth.cpp's handle_preprocess_command assumes that all of the core WML #defines will be in data/core/macros or data/core/terrain-graphics. The assumption isn't quite true, which means it fails to process add-ons that use `{LESS_NIMBLE_ELF}` (a common define for elvish fighter units).

Of the files that aren't included, only data/core/units.cfg looks likely to be necessary.

```
data/core/hotkeys.cfg:#define IF_APPLE_CMD_ELSE_CTRL
data/core/units.cfg:#define LESS_NIMBLE_ELF
data/core/units.cfg:#define RACIAL_NOTES_ORCS_AND_GOBLINS
data/core/units.cfg:#define WOODLAND_RESISTANCE
data/core/units.cfg:#define FLY_MOVE
data/core/units.cfg:#define FLY_DEFENSE DEFENSE_NUMBER
data/core/units.cfg:#define FLY_RESISTANCE
data/core/units.cfg:#define MOUNTAIN_MOVE
data/core/units.cfg:#define MOUNTAIN_DEFENSE
data/core/units.cfg:#define DRAKEFLY_MOVE
data/core/units.cfg:#define DRAKEFLY_RESISTANCE
data/core/units/humans/Mage_Elder.cfg:#define ELDER_MAGE_LIGHTNING DIRECTION_NUMBER
data/core/units/undead/Corpse_Soulless.cfg:#define UNIT_BODY_SOULLESS_STATS MOVETYPE_ID MOVES_NUMBER HP_AMOUNT
data/core/units/undead/Corpse_Soulless.cfg:#define UNIT_BODY_SOULLESS_GRAPHICS BASE_NAME
data/core/units/undead/Corpse_Walking.cfg:#define UNIT_BODY_WALKING_CORPSE_STATS MOVTYPE_NAME MOVES_NUMBER HP_AMOUNT
data/core/units/undead/Corpse_Walking.cfg:#define UNIT_BODY_WALKING_CORPSE_GRAPHICS BASE_NAME
```

**Comment by ProditorMagnus** [comment]
I wonder if that is why I had to collect core macros in separate step https://github.com/ProditorMagnus/WML_tree_tools/blob/master/py_files/preprocess_addon.py#L45

**Comment by stevecotton** [comment]
Including data/core/units.cfg would bring in all of the data/core/units/... subdirectories. So if we want to fix this, I think the solution would be to move the macros from data/core/units.cfg to a new data/core/macros/movetypes.cfg.

**Comment by CelticMinstrel** [comment]
I was thinking that too - simply moving the macros seems easier than dragging in another directory. (And yeah the walking corpse / soulless stuff isn't necessary. It's the sort of thing you should `#undef` at the end of the file.)

**Comment by sevu** [comment]
The WC and hotkeys macro have an #undef at the end of the file. If this is as well done for ELDER_MAGE_LIGHTNING (which includes the image of the unit, and is thus not reusable) and RACIAL_NOTES_ORCS_AND_GOBLINS then all macros are addressed.
