### ISSUE TITLE
Lua error in ca_grab_villages.lua

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#4157]
Hi,
I always see this error at the second turn when I'm playing with AI.  In this case, it happened on Aliork Marsh
![lua_error](https://user-images.githubusercontent.com/3605541/60834820-da048480-a1c1-11e9-86ba-8034ac7a810f.png)

version: 1.15.0-dev 6e27bc7
OS: Linux
Installation method: Flatpak

**Comment by jostephd** [comment]
Confirmed, happens with the experimental AI only.

**Comment by mattsc** [comment]
I was not able to reproduce this: Alirok Marsh giving sides 2 and 3 to the Experimental AI in a local game.  This is with the last version of 1.15 that I just compiled a few minutes ago, v1.15.0-dev (1c19e8ce299-Clean).  Do you have any more details on how I could reproduce this?

**Comment by grz0** [comment]
@mattsc I can reproduce on the latest Flatpak build(1c19e8c-Clean). I use default settings and assign experimental AI to sides 2 and 3.
![game_settings](https://user-images.githubusercontent.com/3605541/60839825-6452e580-a1ce-11e9-8472-b3466189a396.png)

**Comment by mattsc** [comment]
Hmm, I can reproduce it now. I didn't have fog on previously, maybe that's the difference as it crashes in function `find_path_with_shroud()`.  I'll look into it.  Thanks for reporting.

**Comment by mattsc** [comment]
So it was because of the fog, but not for the reason I expected. This is due to changes that are in master only, so it does not need to be backported.
