### ISSUE TITLE
Add log directory infomation to main menu info popup.

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#4168]
On the 1.14 main menu, there's an "i" button in the lower left corner of the screen.  Currently this displays and allows directly opening various folders such as the directory where add-ons are saved.  At least for Windows(I don't know if Wesnoth saves log files automatically on macOS, though it doesn't on Linux), it would be useful if this dialog also provided this information/functionality for the logging directory.

**Comment by jostephd** [comment]
This was closed since the information is already available on windows.
