### ISSUE TITLE
Document preprocessor macro scoping rules

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4172]
See https://forums.wesnoth.org/viewtopic.php?p=644839#p644838 and the following post by @ProditorMagnus. The rules should be documented on https://wiki.wesnoth.org/PreprocessorRef

**Comment by cooljeanius** [comment]
ok done in: https://wiki.wesnoth.org/index.php?title=PreprocessorRef&curid=1480&diff=70236&oldid=70229
