### ISSUE TITLE
[1.15] po-merge

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4173]
The last po-update for master has been a long time ago. Thus, while translation have been included (via msgmerge) into the po-files of both 1.14 and master, strings (msgid's) not know in the master pot files were not included in master. E.g. if someone translated the reworked TSG or DiD, it's translations aren't in master.

Thatfor, all 1.14 po-files need to be be merged (via msgmerge) into their master-counterpart after the pot-update.

**Comment by loonycyborg** [comment]
Is pot-update enough to resolve this or there are other aspects yet?

**Comment by sevu** [comment]
The pot-update did bring the WML-files and the po-files of master in sync.

The second aspect is that translations for new msgids, which had been merged before the pot-update, are not yet in master's po-files. For that, merged the po-files of 1.14 again into master.

##########################
That's actually an issue in our workflow. WML changes are usually commited to both branches at the same time. po(t)-updates are done at differing times, usually before a release. The 1.14 po files submitted by the translators are merged at the same time into 1.14 and master.

One way to deal with it would be to also make a pot-update on 1.14 when 1.15.0 is released, and vice versa when 1.14.9 is released to also make one for master. Side effect is that one can't push a "translations only" update anymore to steam once one does that.
