### ISSUE TITLE
The 'hexes' count returned by [find_path] isn't the number of steps if the path isn't straight

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4177]
The results of `find_path` are quite surprising when the path has to go round an obstacle. I'm logging the issue to ask whether the behaviour should change for 1.15. The description below is for 1.15's ae2d89b132, and has matching behaviour on 1.14.

An extreme example, but consider the map below, travelling from the player start to destination. For both players, path.step.length will be 8, which is expected when you know that the path includes the starting hex.
![test_movetype](https://user-images.githubusercontent.com/101462/61396437-0c039e00-a8c8-11e9-9ef7-98f4b679ce3b.png)

Surprise 1: Although there are (7+1) steps in the path, path.hexes will be 4 for player 1, and 5 for player 2. This is because path.hexes is the result of distance_between(), or the distance as the crow flies, rather than being based on the path that the unit found.

Surprise 2: Suppose we want to move a unit to a (keep or cave) hex, `find_path` takes an SLF which can be expected to do this. However, if you do this path-finding from player 1's start then it will return a path that goes through the cave hex and continues on to the keep.

I think surprise 1 should be changed, and surprise 2 could be an option but shouldn't be the default. Looking at the implementation there's a third surprise - it already works out the paths to all hexes that match the SLF, and afterwards discards any that have a distance_between that's greater than a currently-found route. I'd expected fixing surprise 2 would require removing an optimization, but it turns out that optimization wasn't done.

**Comment by gfgtdf** [comment]
Hmm i Wonder whats the point of having .hexes in the first place when one could also step.length ?

Also I don't understand what you mean in (2)

**Comment by ProditorMagnus** [comment]
If there is .hexes and .length, I would say it is intentional that they work differently.

**Comment by stevecotton** [comment]
> Also I don't understand what you mean in (2)

Suppose we want to move a (keep or castle) hex on the map below. If you use `find_path` with a unit that's on player 2's starting point, it returns a path that moves the unit to the closest (rightmost) of the three hexes. However, if you do this path-finding with a unit on player 1's start then it will return a path that goes to the leftmost (closest as the crow flies, but furthest as the unit walks) of the three hexes.

![test_movetype_2](https://user-images.githubusercontent.com/101462/61406164-930e4180-a8db-11e9-9264-954f5cbaeb32.png)

**Comment by gfgtdf** [comment]
> Suppose we want to move a (keep or castle) hex on the map below

I assume you mean you want to move a unit onto a keep tile and not to move the keep tile itself?

**Comment by stevecotton** [comment]
Oops, thanks. Cut & pasted that part, and edited without seeing it. :(

**Comment by gfgtdf** [comment]
I didn't look at the code but I think it's possible that (2) is actually a consequence of (1) because the implementation might try to return the path that minimizes 'hexes'

**Comment by stevecotton** [comment]
Have's the code. Given two paths where one is better in terms of distance and one is better in terms of movement cost, it will choose the one that it calculated first:

https://github.com/wesnoth/wesnoth/blob/95286cb49f0cdd2b329e57a5ee76f6357e43bfc8/data/lua/wml/find_path.lua#L50-L53

The comment there would make more sense if it was above the if statement.

**Comment by stevecotton** [comment]
Closing, as:
Issue 1 is now fixed by adding more documentation to the Wiki
Issue 2 should not be changed for 1.14, and will be handled by the PR for 1.15
