### ISSUE TITLE
Removing this bug report for ethical reasons. Reasons enclosed. Feel free to delete.

### ISSUE THREAD

**Issue by MalcolmRose** [wesnoth/wesnoth#4178]
Editing this comment to remove my bug report. I was just banned from the Discord by Iris whilst trying to contribute. I don't feel comfortable contributing anything to a project where mod abuse is allowed/encouraged and there's no recourse to complain or appeal. Please consider changing this.

**Comment by soliton-** [comment]
A failed assertion after you disregard the warning and OOS errors doesn't sound that bad but maybe it'd be easy to show a nicer error message and return to the main menu or so.
