### ISSUE TITLE
vision, [store_reachable_locations] and units with vision different to movement

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4179]
`[store_reachable_locations]` supports storing `range=vision`, which as implement and documented on the Wiki stores "the vision range (movement range ignoring Zone of Control + 1 hex)."

That assumption is broken by the feature that units can have [vision_costs] separate to their [movement_costs] or vision_points different to their max movement points. There isn't currently a WML function for storing the vision of such units.

**Comment by CelticMinstrel** [comment]
Suggestion: Add support for `range=movement` and `range=jamming` to use movement and jamming costs+points respectively. Then make `range=vision` use the vision costs+points.

That might be a slight compatibility break, mind you... maybe leave `range=vision` as-is for 1.14 and also add `range=sight` for actual vision points?

Maybe also a mode that uses vision but also accounts for enemy jamming.

**Comment by stevecotton** [comment]
The existing `viewing_side` key could also trigger accounting for enemy jamming (I haven't checked if it already does).

I don't understand jamming yet, but I think it's more than a list of locations. IIUC it's also the number of jamming points that are left over when that hex is reached, with the left-over points being the penalty that's applied to enemy vision.

**Comment by stevecotton** [comment]
Added to the roadmap for 1.15.9.
