### ISSUE TITLE
old replays can cause wesnoth to fail an assertion check

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#4180]
An old/corrupt replay can cause wesnoth to assert in this code:

https://github.com/wesnoth/wesnoth/blob/95286cb49f0cdd2b329e57a5ee76f6357e43bfc8/src/play_controller.cpp#L712-L722

It would be nicer to be able to show an error message and return to the main menu or so.

I think switching to throwing an exception may already do most of that and it seems to fit better for something that apparently may actually "normally" occur.

Unfortunately I don't have a replay at hand to test this but maybe @jostephd can provide a link?

**Comment by gfgtdf** [comment]
Related issue: https://github.com/wesnoth/wesnoth/issues/2818

**Comment by jostephd** [comment]
> Unfortunately I don't have a replay at hand to test this but maybe @jostephd can provide a link?

Looks like pretty much any replay will do this, here's one. Just load it and skip past the OOS errors and it asserts.

[Wesnoth_Tutorial_Part_I_replay.gz](https://github.com/wesnoth/wesnoth/files/3406780/Wesnoth_Tutorial_Part_I_replay.gz)
