### ISSUE TITLE
Add the asymmetric theme?

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4184]
Since gloccusv posted his [asymmetric theme](https://forums.wesnoth.org/viewtopic.php?f=6&t=41065&start=15), I've been using a modified version of it ([code](http://sprunge.us/uLV6Pj), [screenshot](https://forums.wesnoth.org/download/file.php?id=83887&mode=view)). My version works best on master (because it uses some of the features from #3852). I've considered packaging it [as an add-on](https://forums.wesnoth.org/viewtopic.php?f=21&t=50213) but I wonder if it'll be easier to just add it to mainline?

*edit* That code patch is just what I'm using right now in my personal branch. I am **not** proposing to just apply that to master as-is; if the concept is acceptable, I'll clean the patch up before merging it.

- [ ] On 2560x1440 the left bar is 1106 pixels high, not full length.

**Comment by Vultraz** [comment]
Noooo. Too cluttered.

**Comment by jostephd** [comment]
I wouldn't make it the default.

**Comment by Pentarctagon** [comment]
I like it, FWIW.  It makes it much faster to see expected outcomes compared to having to additionally click on the enemy unit, select the attack I want, and then clicking to view the damage calculations.  Even more so if I want to compare expected outcomes against multiple enemy units.

**Comment by jostephd** [comment]
The asymmetric theme is also useful for:

- Having the sidebar show enabled/disabled status of weapon specials correctly (#4071)
- Previewing enemy attacks (if #3956 is merged)

**Comment by soliton-** [comment]
Looks quite interesting indeed. I suppose continued maintenance is an issue otherwise I see no reason why it couldn’t be added.

**Comment by Vultraz** [comment]
*No*. This is absolutely horrible UI design and makes it look like we're some MMORPG from 2005. Nothing is condensed, you need to keep glancing from one side of the screen to the other. The margins around text are almost non-existent. Copious numbers and icons and arrows and colors are thrown around haphazardly with no explanation as to what they mean. Our current in-game UI design is bad enough, but this just turns it into a cluttered mess.

**Comment by jostephd** [comment]
@Vultraz Thanks for the review. Let me try to address your points:

> Nothing is condensed, you need to keep glancing from one side of the screen to the other.

Well, to start with, if _that's_ the only problem, we can just put both sidebars next to each other.

Moreover, I have played with this theme for months and found it convenient and much better than the default theme. Have you tried playing with this theme (an actual scenario, more than one turn), or did you just look at the screenshot?

And lastly, even if this isn't the best imaginable UI design, then so what? The question isn't whether this theme is the best (it isn't; I'm not vain enough to claim otherwise, and I can even think of ways to improve this theme), but whether this theme is worth including. About that, this theme is useful because it makes the battle results simulation histogram available with two fewer clicks, and doesn't impose any maintenance costs on any other part of the code. I'm sure there are even better ways to present the information, but that's neither here nor there. Don't let the perfect be the enemy of the good.

> The margins around text are almost non-existent.

I assume you mean the margin above the red/black icons. That's not an issue with the asymmetric theme but with one of the helper functions in reports.cpp that's used by the default theme too. I have already changed reports.cpp on master to add some more padding there. (I did that several weeks ago, actually; it's just that I created this issue I forgot to re-take the screenshot with a current wesnoth build. Sorry.)

> Copious numbers and icons and arrows and colors are thrown around haphazardly
> with no explanation as to what they mean.

Icons and arrows are identical to those in the default theme. (The arrow isn't even part of the theme system. The icons are, but they are hardcoded into the reports; a theme can't control the icons short of omitting the battle results report entirely.)

Good point about lack of explanations. I think we have two options:

- We could decide that this theme should be newbie-friendly. Then we should add some text labels such as "Baseline damage", "Battle results", and so on. It would be little effort to do so.

- We could decide that this theme doesn't attempt to be newbie-friendly. We'll recommend new players to use the existing default theme and open the damage calculations dialog, just like now. This theme will be marketed as a theme that targets experienced players and presents information more densely. That _is_ a thing, you know: many programs have a "friendly" output mode for beginners and a "dense" output mode for experts. Here's one example:

        sqlite> select * from t;
        word        number
        ----------  ----------
        hello       5         
        world       6         

    (and again, after changing a few settings:)

        sqlite> select * from t;
        hello|5
        world|6

Colors: Well spotted: the color gradient used by the sidebars' histograms, `game_config::blue_to_white`, isn't used anywhere else in master. It would be trivial to change reports.cpp to use another gradient (I assume `game_config::red_to_green` would be suitable).

> Our current in-game UI design is bad enough, but this just turns it into a cluttered mess.

If you don't like this theme, no one will force you to use it. However, plenty of other people do like it. Are you going to prevent people from using a theme _they_ find useful because _you_ don't like it?

**Comment by Vultraz** [comment]
> If you don't like this theme, no one will force you to use it. However, plenty of other people do like it. Are you going to prevent people from using a theme they find useful because you don't like it?

I would like to maintain a certain level of quality for what we add to the game. There have already been cases in the past (see the infamous Reverse Time Graphics option) wherein people *like* options, but having them is not necessarily consistent with good design. I don't deny this theme might be useful to some or that some might prefer it. But there are many things you could add just because someone finds it useful, and I do not think that this theme is good enough to be included.

If you'd like, you could help with designing the in-game UI for version 2.0. Currently it looks like this. It's far from finished, but if we want to have proper support for 1v1 unit comparisons in the UI, this would be the best venue.

![haldricHUD](https://user-images.githubusercontent.com/3558659/62001327-a4581900-b139-11e9-9982-11d5696a6a91.jpg)

**Comment by soliton-** [comment]
I think it'd be more useful to add support for addons installing themes. So people can install usermade themes and use them like the default ones not just when scenarios specifically reference them.

Not sure what exactly would be necessary for that. Probably best to open a new issue for that.

**Comment by jostephd** [comment]
Sorry for the late answer, I've been away the past two weeks.

@Vultraz Thanks for the explanation. I'd be happy to help with the Haldric UI. Should I just clone and build https://github.com/wesnoth/haldric, or should I read some threads first, or what?

I've been thinking about how to distribute the theme. Creating an addon with `[theme]..[/theme]` in its `_main.cfg` actually works (as I mentioned in the first post) so I think I'll do that; I just need #4209 to be merged first. I'll put `type=other` in _server.pbl.

**Comment by jostephd** [comment]
For anyone interested in the theme, I've uploaded it to the 1.15 addon server under the name **Combat Information Theme** (thanks Lucipurr for the name). Bug reports to https://github.com/jostephd/combat-info-theme/issues please or on the forums.
