### ISSUE TITLE
Consider switching bundled font Dejavu to Bitstream Vera

### ISSUE THREAD

**Issue by travankor** [wesnoth/wesnoth#4202]
On Linux, the dejavu font has a tendency to override color emojis with it's own black and white version. To many users this is undesirable behaviour when we want to install our own color emojis. Bitstream Vera is a drop in replacement for Dejavu without the B/W emojis. I don't think Wesnoth uses Dejavu's emojis, so I think it would be safe to switch to Bitstream Vera.

### Why Bitstream Vera
The default serif, sans-serif and monospace font for most Linux distributions is DejaVu. DejaVu includes a wide range of symbols which override the Twitter Color Emoji characters. The previous solution was to make Twitter Color Emoji the default system font, but that causes a number of issues. A better solution is a different font that doesn't override any emoji characters such as Bitstream Vera. Bitstream Vera is the source of the glyphs used in DejaVu, so it's not very different. 99%+ of people will not notice the difference.
https://github.com/eosrei/twemoji-color-font#why-bitstream-vera

**Comment by Vultraz** [comment]
When are you seeing DVS? We use Lato. DVS Mono is mostly only used for the Lua console.

**Comment by GregoryLundberg** [comment]
The only reasons I can see for making the OP would be that an attempt to use a Twitter Emoji character in in-game chat failed, or a message somewhere in a UMC under development.

If the above is just a comment about Linux systems, in general, without an example of where an issue occurs in Wesnoth, this PR should simply be closed.

**Comment by travankor** [comment]
Sorry for the noise, Linux fontconfig doesn't seem to natively support the font format upon further research. So you can't use it in any other application other than a browser it seems.
