### ISSUE TITLE
UtBS S2 - Across the Harsh Sands, remove 'thirst' mechanic for enemy units

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4206]
There is no given story for any of the living units to suffer from thirst, since they are all camping/living on top of a water source (except the scouting ogres, but they surely have packed enough water).
The explantion for the elves is basically that the had to leave in a hurry, which does not match with the situation of the living beings 'native' to this part of the desert.
~zookeeper conceded that, if it works balance-wise, having the outlaws/ogres/scorpions camp at their oasis instead of rushing out to attack during the day sounds good to him.~

**Comment by soliton-** [comment]
You really think it's more intuitive if the rules are based on how much water a unit can carry around?

Can you suggest how to adjust the text explaining the mechanic?

Or is the suggestion to adjust the AI of the enemy units in some way? (Which way exactly?) Since then presumably the thirst mechanic should stay as is.

**Comment by Konrad22** [comment]
I really think it's more intuitive if the mechanic is applied in a way that matches the story explanation for said mechanic.

"During the daytime (Dawn, Morning, Midday, Afternoon, and Dusk) at the beginning of each your turns, every **of your units** unit in a sand, road, rubble or sand dune hex will suffer from thirst. Each turn of thirst reduces a unit’s attack damage and causes $dehydration_loss hitpoints of damage. Healers can prevent dehydration from becoming worse, but cannot heal it. Only by refreshing at an oasis (any water hex) at the start of your turn will your units regain full attack strength."

Having reread the [story explanation](https://github.com/wesnoth/wesnoth/blob/2d3c26b560cc81087b1d9ad95b5ab0165a8b83b1/data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg#L334) now, I don't suggest adjusting the AI of the enemy units, at least not due to the 'thirst' mechanic.

**Comment by stevecotton** [comment]
Just found that a Sun Sylphs's illuminate ability makes her thirsty at night.

**Comment by Wedge009** [comment]
That sounds unintentional. Presumably would need to separate light from time-of-day from light from illumination. Similar to other scenarios like camp fires and such.

**Comment by nemaara** [comment]
I haven't encountered it, but that's probably because I deliberately avoid getting lvl 3s on this scenario. I don't know if there's a way to separate the filter based on illumination or the map's base ToD. The filter just uses time_of_day=, which doesn't do that.

**Comment by nemaara** [comment]
Fixed by #4770.
