### ISSUE TITLE
Usability enhancement: give players the option to disable certain effects, such as weather effects

### ISSUE THREAD

**Issue by rubyFeedback** [wesnoth/wesnoth#4208]
I am playing a campaign right now which has rain.

I remember another campaign where we could disable rain.

The rain causes lag-issues; movement is slower and sluggish of units.

I propose to make it possible in general to disable such effects, rather than on a per-campaign issue, in general. As a user I am fine with rain per se but not if this slows down how quickly I can move the units (right now this is unfortunately slowing units down).

In the long run perhaps the weather effects can be fixed, but in the short term I propose ad-hoc ways to disable this.

perhaps as an additional entry in the preferences, or in the right-mouse click context menu during the scenario.

**Comment by jostephd** [comment]
Going with your idea, we could make, say, the `Animate water` and `Animate terrain` preferences' values accessible to Lua and then UMC authors could default rain to enabled/disabled depending on the value of those preferences... but I'm not convinced we need to do this. Isn't this just a bug in the addon that doesn't give a way to disable rain?

Could you link to the addon please?

**Comment by AI0867** [comment]
I've seen toggleable rain in UMC before, but I don't believe there is any in mainline.

Rain is probably about as expensive as having the screen full of animated terrain (think looking at an ocean), so there might be a case to be made about disabling water animation.

**Comment by GregoryLundberg** [comment]
One similar effect which is in mainline, for example, is the earthquake during Delfador's Memories. I never really was happy with it but didn't feel it should be removed. A main option to disable such things, perhaps with a short narator message "An earthquake occurs ...", sounds like a good idea.

**Comment by Wedge009** [comment]
The only thing I could find resembling an earthquake in Delfador's Memoirs was S10 The Gate Between Worlds, where Iliah-Malal opens the portal in the north-west. It's only a relatively few hexes - does it really cause that much CPU strain on lower-power processors? In contrast with the full-map effects like rain and large ocean animations, I mean.

https://github.com/wesnoth/wesnoth/blob/ae73e5cd1546997b59e1156d8be3a7a9c0dbf79e/data/campaigns/Delfadors_Memoirs/scenarios/10_The_Gate_Between_Worlds.cfg#L129-L152

(BTW, the animation worked well enough for me, glad it was left in.)

**Comment by GregoryLundberg** [comment]
Yeah I didn't 0work so well imo so I spent a few hours plating around with it. I'm not totally happy with it but its better than it was. The point is not CPU load so much as its just a bit annoying and an option to bypass this sort of thing sounds like a good idea.

**Comment by Wedge009** [comment]
I'm not sure we're still seeking more information on this one.

**Comment by soliton-** [comment]
So what is this issue about? Providing a way for UMC to query preferences?

**Comment by Wedge009** [comment]
Seems like ruby is just really keen to have an option to disable certain animations. I only just noticed a few days ago that they submitted the request twice.

**Comment by soliton-** [comment]
But the mentioned animations/effects are not implemented by mainline wesnoth but some addon. Unless the goal is to disable all (map/terrain?) animations this is something to implement in those addons not in wesnoth itself.

**Comment by Wedge009** [comment]
I don't know if the intention is to blanket enable/disable all animation effects - water, non-standard rain, etc - or do it on a per-effect basis. The latter would certainly need to be handled by the add-on implementing non-standard effects.

If it's not up to Wesnoth to do this, should it be closed then?

**Comment by soliton-** [comment]
Yes, that's why I'm asking. If an addon should change how it implements an animation/effect then that needs to be requested from the addon's author/maintainer.

**Comment by Wedge009** [comment]
Aside from the earthquake effect in Delfador's Memoirs, earlier conversation seemed to affirm this is a shortcoming of the add-on, not Wesnoth. All right, closing then.
