### ISSUE TITLE
Area not used by theme not redrawn

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4210]
In current master, with #4209, when I change the optional argument's value to 400 and use the _default_ theme, if I open and close the preferences screen, it's not completely undrawn:

![Screenshot_2019-08-10_14-18-50](https://user-images.githubusercontent.com/24784687/62822918-cd38cf00-bb79-11e9-8fbf-cc4ac99e4787.png)

**Comment by mesilliac** [comment]
I added a fix for this because it was trivial in the new rendering system.
