### ISSUE TITLE
Create mushroom mixed terrains

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4213]
In 1.14, the `^Uf` terrain was visually an overlay but behaved as a non-mixed-terrain mushrooms; see https://github.com/wesnoth/wesnoth/pull/4185#issuecomment-513620750.

#4185 changed the graphics to match the data. This issue is about creating a _new_ terrain code that uses the old graphics and behaves as a mixed terrain (flat/fungus, for example).

**Comment by stevecotton** [comment]
If it's going to have a new letter, the available ones are L, N, O, P and T. Current list is at https://wiki.wesnoth.org/TerrainCodesWML#Decoding_the_Terrain_Codes

Toadstool?

**Comment by slavrenyuk** [comment]
@jostephd @stevecotton
Consider adding mushroom defense cap to horseman, cavalryman and their advancements similar to the forest cap which they already have.

**Comment by jostephd** [comment]
@slavrenyuk I'm not an authority on balancing maps so I'll leave this decision to others. Thanks for suggesting that.

**Comment by stevecotton** [comment]
Created a new issue for the remaining task in this one.
