### ISSUE TITLE
Forward port mushroom visual-only change 

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4214]
Forward port #4185 to make the `^Uf` code's graphics match its behavior. For adding a new terrain code for true mixed terrain fungus, see #4213.

**Comment by doofus-01** [comment]
The old behavior is pretty much a mistake, don't we just want to clean it up in 1.15, rather than forward-porting the band-aid?  Or is that breaking a deprecation cycle?  We can make a dummy terrain ^Uf so that old maps can still be opened.

**Comment by soliton-** [comment]
The current mushroom terrain is not a mistake regarding map balance. It was visually misleading though.

**Comment by slavrenyuk** [comment]
Port this PR as well https://github.com/wesnoth/wesnoth/pull/4216 please.

**Comment by jostephd** [comment]
@doofus-01 The `^Uf` code should be preserved for compatibility, but right now on master it still suffers from the problem you described in https://github.com/wesnoth/wesnoth/pull/4185#issuecomment-513620750. See also #4213 if you haven't already. I think we're saying the same thing, aren't we? Or am I misunderstanding you?

@slavrenyuk We only create "forward port" issues for things that have already been merged to 1.14. You don't need to separately ask for PRs to be merged to master unless they have been merged to 1.14 or have the green "Stable 1.14" label.

**Comment by slavrenyuk** [comment]
> @slavrenyuk We only create "forward port" issues for things that have already been merged to 1.14. You don't need to separately ask for PRs to be merged to master unless they have been merged to 1.14 or have the green "Stable 1.14" label.

Ok, thanks for the information.

**Comment by doofus-01** [comment]
@jostephd - I think we may have been saying the same thing.  My point was that the (now reverted) PR was an attempt at fixing the issue in a way that didn't change the actual behavior, but it wasn't the best way to deal with things going forward:
 - The existing graphics and terrain codes said it was an overlay (implying mixed terrain), the actual terrain wasn't mixed terrain.
 - 1.15 allows new terrain codes, so there is a new mushroom terrain that really is an overlay/mixed terrain (*^To, or whatever), and a new one that is a base terrain (both graphics and terrain code, Tb or whatever), maintaining the old behavior but with a more sensible terrain code -> 1:1 replacement in updating maps.  Also, as a base terrain, "Tb" could have other overlays.
 - there is no reason to maintain ^Uf in 1.15, except as a deprecated old code to keep maps from crashing.  The new terrains should not be ^Uf.

That may have been hashed out in the other issues and PRs, I was out of the loop for a bit.  I read enough in the discord logs to not want to touch this (or anything) anymore for now, but if you need help later on in 1.15 with the terrain graphics, I can pitch in when the mechanics are settled.

**Comment by slavrenyuk** [comment]
This issue is not trivial, it requires attention of many people. Especially those who did not participate in the discussion from the beginning, namely @nemaara @shikadiqueen and @Vultraz. IMO it doesn't make sense to work on implementation, until there is a plan that satisfies all parties. In any case, thanks to @doofus-01 we already have new graphics, which is usually hard to get. If it will be decided to keep status quo, I would ask to add this information to list of proposed and rejected ideas (on the forums).

**Comment by CelticMinstrel** [comment]
Is there really a need to have these two separate issues on this subject? In any case, what doofus-01 says is pretty much correct - there's no need to change `^Uf` (apart from marking it hidden or deprecated or whatever), just add a new base terrain using the new graphics and a new overlay terrain using the old graphics.

My suggestions for new terrain codes:

* `Tt` - mushroom archetype, to provide the icon for the sidebar and be used as an alias for all other mushroom terrains. Like all the other archetypes, a hidden terrain that cannot be placed in the editor.
* `Tb` - mushroom base terrain. I don't really like the choice of `b` here but can't think of anything better.
* `^Tf` - mushroom grove overlay with mixed properties. (`f` for "forest")

**Comment by jgizis** [comment]
On 1.15.2 (Mac) in Merkwuerdigliebe map, the mushroom terrain does not blend at the hex edges properly with land type terrain. (The water sides are fine.) Example:
 
<img width="563" alt="ScreenShotWesnothMushrooms" src="https://user-images.githubusercontent.com/3182540/68731523-6377f900-059e-11ea-9572-86764109ee3c.png">

**Comment by doofus-01** [comment]
I believe that's #4453, should be already fixed in master.

**Comment by Pentarctagon** [comment]
Is there anything left to do for this issue?
