### ISSUE TITLE
Map editor unusable

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#4215]
If you want to draw mountains on grass, you can do that.  But you can't select any other terrains.  The terrain palette, where you select the specific terrain, is unresponsive though the other things above it work (fill tool, radius, etc.) 

My info:

The Battle for Wesnoth version 1.14.8+dev (aa34fcccf0d-Modified)
Running on openSUSE Leap 15.0

Libraries
=========

Boost:             1.66
OpenSSL/libcrypto: 1.1.0i  (runtime 1.1.0i)
Cairo:             1.15.10 (runtime 1.15.10)
Pango:             1.40.13 (runtime 1.40.13)
SDL:               2.0.8   (runtime 2.0.8)
SDL_image:         2.0.4   (runtime 2.0.4)
SDL_mixer:         2.0.2   (runtime 2.0.2)
SDL_ttf:           2.0.14  (runtime 2.0.14)

Features
========

JPG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: yes
D-Bus notifications back end:   yes

**Comment by Vultraz** [comment]
Can confirm, Windows 10....

**Comment by Pentarctagon** [comment]
Bad commit is https://github.com/wesnoth/wesnoth/commit/4139b43cc900b72756f07267dbb887c469d6f4c2, which is also in master.

**Comment by Pentarctagon** [comment]
@loonycyborg btw

**Comment by stevecotton** [comment]
GCC9 gives a -Wdeprecated-copy for widget's copy-assignment, which will similarly copy-assign the sdl_handler.

About to push a branch fixing Rule of Five for sdl_handler instead.
