### ISSUE TITLE
DM - S20 Prince of Wesnoth, add note to explain 0 XP

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4219]
~In this scenario you play as Kalenz and you can recall your his elvish veterans. But for some reason every unit (including Kalenz and Chantal) has had their XP set to 0.
I don't see how this makes sense, so I'm asking to undo this.~
[DM-Prince of Wesnoth-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/3500606/DM-Prince.of.Wesnoth-Auto-Save1.gz)
Apparently every unit was advanced once. I suggest adding a note to explain that. And preferably make the advancement random (right now the 'first' advancement choice is taking exclusively).

**Comment by GregoryLundberg** [comment]
Remember, a lot of years passed. Actually I considered randomly deleting some units from the recall list, and randomly adding a few as well. I didn't consider randomly choosing an advancement path. I remember thinking about it and deciding the default choice was "good enough" and probably would have decided randomizing was too much work at the time.

**Comment by stevecotton** [comment]
Maybe add a random amount of XP on top of the advancement?

**Comment by Konrad22** [comment]
> 
> 
> Remember, a lot of years passed. Actually I considered randomly deleting some units from the recall list, and randomly adding a few as well. I didn't consider randomly choosing an advancement path. I remember thinking about it and deciding the default choice was "good enough" and probably would have decided randomizing was too much work at the time.

I do remember, which is why I'm not wondering (anymore) what the heck happened. I'm just saying that there is no need to keep the 'wait what' moment. (This 'mechanic' is unique and therefor not unexpected by the player.)
