### ISSUE TITLE
DM - S21 Clash at the Manor, inconsistency in the story

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4220]
In the story text Delfador is granted an audience with the king and 'expressed his concerns about the missing book', but so far there has been no mention that the book is misssing.
https://github.com/wesnoth/wesnoth/blob/d69b5c8804608142ad291ed0d789cb50086b32f4/data/campaigns/Delfadors_Memoirs/scenarios/20_Prince_of_Wesnoth.cfg#L206
https://github.com/wesnoth/wesnoth/blob/d69b5c8804608142ad291ed0d789cb50086b32f4/data/campaigns/Delfadors_Memoirs/scenarios/21_Clash_at_the_Manor.cfg#L25

**Comment by sigurdfdragon** [comment]
@Konrad22 
Not sure what needs to be done about that. I did add the word 'missing' to the line of '...concerns about the missing book..." to make it more clear what's going on, as lines afterward refer to it being missing & needing to be retrieved.

Do mean something like adding "Delfador checked where he had kept the book and found it missing" a line or two before the audience with the king part?

**Comment by Konrad22** [comment]
Yes, something like that. Because up to that point the player is not aware that the book is missing or whether Delfador checked. At worst it sounds like he drew conclusions without backing them up with facts.

**Comment by stevecotton** [comment]
Add something about a magic alarm on the safe where the book is normally kept?

According to AToTB, even apprentice mages are able to make such a plot widget:
https://github.com/wesnoth/wesnoth/blob/02da0c43a7a75a0839c124ccdc21c186bcd38ebf/data/campaigns/Two_Brothers/scenarios/01_Rooting_Out_a_Mage.cfg#L62
