### ISSUE TITLE
game crashes after using "Back to..." if you are defeated, only in multiplayer mode. 

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#4236]
1.15 game crashes after using "Back to..." if you are defeated, only in multiplayer mode.

**Comment by jostephd** [comment]
It's an uncaught `reset_gamestate_exception`. Only happens when playing via wesnothd, not in local games.

**Comment by jostephd** [comment]
I had this happen both when I won and when I lost. In both cases I was the host against AI players, I don't know if that matters.

**Comment by gfgtdf** [comment]
Does this also happen in 1.14?

**Comment by Wedge009** [comment]
I vaguely recall a request or issue relating to disabling the 'back to' function for MP games.

**Comment by gfgtdf** [comment]
> I vaguely recall a request or issue relating to disabling the 'back to' function for MP games.

Hmm no, for this issue it should not be needed we could just disable it after the game ended.

In fact 'back to' does something complteley differnt in mp: it resets the gamestate to that save for your client only and switches to replaymode until the current turn is reached. to review previous turns. I am not sure how well tested it is but there are no tracked bugs to it except for this one.

**Comment by jostephd** [comment]
> Does this also happen in 1.14?

Yes.

> Also does this only happen if the game is ended or also if just your side is defeates but the game has not ended yet (which could for example happen in a 1vs1vs1 match)

If I'm defeated but the game hasn't ended, it doesn't crash.

**Comment by gfgtdf** [comment]
Ok, so if we don't come up with a better fix we should just disable those buttons when the game has ended in mp.

**Comment by Wedge009** [comment]
I found the issue: #2508. They look to be the same issue to me.

**Comment by gfgtdf** [comment]
This will be fixed in 1.17.15 adn 1.16.9

**Comment by gfgtdf** [comment]
I tested it in master, for 1.16 we will just disable it, since the fix from master is too complicated for 1.16

**Comment by Wedge009** [comment]
If it works for you, that's good enough I suppose. Can always re-open if someone else still encounters it.
