### ISSUE TITLE
Mini-map elements are displayed in non-game screens

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4237]
![colorpoints](https://user-images.githubusercontent.com/39015360/63128125-79344d00-bfb4-11e9-8293-81745ed42089.png)
![colorpoints2](https://user-images.githubusercontent.com/39015360/63128131-7b96a700-bfb4-11e9-9e98-7ecf3ba95eec.png)
![grafik](https://user-images.githubusercontent.com/39015360/63128527-6d955600-bfb5-11e9-8ba0-6d37e7dadadb.png)
I just tried starting HttT and THoT. No idea what this is, what's causing it. And it doesn't happen every time (e.g. nothing happened when going from HttT S3 to S4).
Windows 10, 1.15.0

EDIT:
Tabbing out 'fixed' the black background in the last picture.

**Comment by jostephd** [comment]
Looks like the minimap. Probably another regression from #4188? There's also #4230 which is already open.

**Comment by Konrad22** [comment]
I can confirm that this is the minimap. It matches the units present at the time of scenario start.

**Comment by Konrad22** [comment]
I'd like to point out that this does not account for the 'black background'.

**Comment by jostephd** [comment]
I can't reproduce this.

At this point, as I said on #3120, I think it would be best if someone reviewed #4188. It's known to have introduced two regressions and I imagine it may have introduced more.

**Comment by jostephd** [comment]
#4188 has been reverted (#4238). @Konrad22 Would you test this again in 1.15.1 when it's released?

**Comment by Konrad22** [comment]
Of course. Maybe it will also fix this:
![grafik](https://user-images.githubusercontent.com/39015360/63187157-7d1ca980-c05e-11e9-921b-f8a2050a347a.png)

**Comment by Konrad22** [comment]
This bug is still present in 1.15.1.
![grafik](https://user-images.githubusercontent.com/39015360/63386780-24be1280-c3a4-11e9-9cee-a75072719140.png)

**Comment by Konrad22** [comment]
I have exactly the same issues on a different pc of mine. @Wedge009 remembered encountering something like this with a bad graphics driver bug.
I have Intel(R) HD Graphics 520 on one and NVIDIA GeForce 9600 GT on the other.

**Comment by Konrad22** [comment]
For some reason I do not encounter this bug when playing 1.15 on steam. But I am guaranteed to encounter it when using the sourceforge version.

**Comment by Konrad22** [comment]
Refering #4309 because this looks very similiar even though the steps are not the same.

**Comment by Wedge009** [comment]
Do we have two separate issues here? Mini-map and black screens? When I started working again on Wesnoth a few weeks ago I noted that MSVC projects had switched to 64-bit compilation. I don't know if I've mucked something up there or if I've stuffed something up in terms of libraries/dependencies but I had also noticed problems with the mini-map - but only on my own Windows builds, not in my Linux builds (which were already 64-bit), nor the official 1.14.7 Windows build.

I actually first noticed it from the Editor, not the story screens but have since confirmed it on the story screens too (so I'm inclined to label it Confirmed but jostephd has already said Works for me) - I hadn't reported it yet because I'm still reviewing the issue back-log and didn't want to make new issues until I've done that (which may take some time).

I can't speak for the black screen though.

**Comment by soliton-** [comment]
I think any confirmation overrides an earlier "works for me". It probably just means the steps to reproduce were perhaps missing something or some other relevant context is/was not clear yet.

**Comment by jostephd** [comment]
@Wedge009 I agree with @soliton-, if you can reproduce this issue please label it Confirmed and remove Works for me. I did the same for #4196 when I managed to reproduce it.

**Comment by Wedge009** [comment]
Plan to do so when I investigate further.

**Comment by Wedge009** [comment]
Related to the mini-map elements being shown in story scenes, I also have something similar with the editor:
- Start Wesnoth
- Start Editor
- Mini-map does not draw/update until I scroll the main map.
- Exit Editor
- Mini-map white rectangle showing the view of the main map is still showing in the top-right corner of the title main menu screen until I force a redraw by passing the mouse cursor over the menu buttons.

On top of that, I also have a repeat of #2742 which, back then, I didn't have an issue with.

The only similarity I have with #4245 is where it does and does not happen. Copying the report from there...

---

Git code repository pulled as at 2019-09-13 ~09:00 UTC (but problem appears to be have started well before this time)

Where I find the problem **does** occur:
- Windows 1.14.8+dev
- Windows 1.15.1+dev

Where I find the problem **does not** occur:
- Windows 1.14.7 release
- Linux 1.14.8+dev
- Linux 1.15.1+dev

**Comment by Wedge009** [comment]
I have a couple of other graphical artefacts with the same replication pattern, which makes me wonder if something broke in terms of graphics. Not sure if it's worth reporting them yet, as compared with this and #4245 they're relatively minor.

**Comment by Wedge009** [comment]
@Konrad22 From what I read in #wesnoth-dev, 1.15.1 release is 32-bit on Steam and 64-bit as stand-alone build (what you called 'sourceforge version'). Can you verify if you have different results with respect to 32-bit vs 64-bit, please?

**Comment by Konrad22** [comment]
Yes, I can. And I do have the expected different results.

**Comment by Wedge009** [comment]
Expected different results meaning the issue is specfic to the 64-bit Windows build?

**Comment by Konrad22** [comment]
Yes.

**Comment by sevu** [comment]
![AOI](https://user-images.githubusercontent.com/21158813/65442118-e8128a80-de2b-11e9-828a-944b9d946f4e.png)

Not 1.15. exclusive. Not Windows exclusive. Not happening 100% – although I can currently reproduce it always for this scenario, and on another one not.
```
Library versions:
Boost:             1.69
OpenSSL/libcrypto: 1.1.1d (runtime 1.1.1d)
Cairo:             1.17.3 (runtime 1.17.3)
Pango:             1.44.6 (runtime 1.44.6)
SDL:               2.0.10 (runtime 2.0.10)
SDL_image:         2.0.5  (runtime 2.0.5)
SDL_mixer:         2.0.4  (runtime 2.0.4)
SDL_ttf:           2.0.15 (runtime 2.0.15)

For testing:
LC_ALL=C ./wesnoth-1.14 --nocache --campaign=An_Orcish_Incursion --campaign-difficulty=2
```

**Comment by Wedge009** [comment]
Need to establish that your case is the same as this case. This case is 100%, plus seems tied with #4245. If you're not getting that one at the same time I suspect it may be a separate incident. We've had this problem before, for different reasons.

**Comment by sevu** [comment]
I got it always when I was specifically testing, using `--nocache` to rule out possible caching issues. Maybe I just didn't notice it before. Might or might nor be the same. From further testing :

I tried all the 1st scenarios of campaigns:
- happened on all except DM. DM S1 uses the cutscene theme, which is the reason this issue doesn't appear there, but I also get the problem from the 2nd screenshot in #4242 
Without the cutscene theme DM S1 behaves like the others – drawing the mini-map elements on the story screen and having no issues when the main map appears after the story part.
- Using the cutscene theme in AOI S1 (also always):
![cutscene-theme](https://user-images.githubusercontent.com/21158813/65447067-0e3d2800-de36-11e9-8543-5b4eb0937991.png)
This confirms that the cutscene theme behaves differently.

What I did not see:
- The third screenshot from the opening post above..
- The black screenshots in #4242 , but I also haven't specially looked for them yet. (no confirm, nor denial)

Second thing I figured out, quoting Konrad from 1st post:
> I just tried starting HttT and THoT. No idea what this is, what's causing it. And it doesn't happen every time (e.g. nothing happened when going from HttT S3 to S4).

The story screen of this HttT S4 draws red markers on the map (the ones which show that there is a fight). Thus one doesn't notice the issue, but if one looks very carefully: The issue still applies there, for a very short moment one can see it, but it's "fixed" as the red drawing starts.

**Comment by Wedge009** [comment]
Just wondering: do you observe any change if trying SDL 2.0.9?

**Comment by Wedge009** [comment]
Confirming SDL 2.0.10 x64 is responsible. SDL 2.0.9 is fine (though @stevecotton notes there are security issues in the older versions).

**Comment by Wedge009** [comment]
Disabling the batched renders feature that's default in SDL 2.0.10 seems to resolve this.

**Comment by jostephd** [comment]
So to be clear, this _isn't_ a bug in SDL's batched renders feature, it's just that the way Wesnoth uses SDL isn't compatible with batched renders in the first place? If so, is that something we should look into changing (in the long term)?

**Comment by Wedge009** [comment]
I believe that's the case, and yes, I think it should be resolved for the long term but I honestly don't know where to begin. On the other hand, it might just be resolved as part of the GPU-rendering work... if it happens. (:

**Comment by jostephd** [comment]
@Wedge009 Thanks for confirming that. So, we don't need to send a bug report to SDL about the batched renders feature, nor to create another issue about changing our rendering code. Let's move on then, cheers :)
