### ISSUE TITLE
1.15, units being advanced for story reasons {ADVANCE_UNIT} skip the 'advancing animation'

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4243]
At the end of turn 3 of side 3 the map focuses on the Orc Archer on 16,18. On 1.14.7 the orc 'advances' to 'Sea Orc', but on 1.15.0 it looks like he gets replaced.
Just end the turn.

1.14.7
[HttT-The Bay of Pearls-Auto-Save3.gz](https://github.com/wesnoth/wesnoth/files/3511263/HttT-The.Bay.of.Pearls-Auto-Save3.gz)
1.15.0
[HttT-The Bay of Pearls-Auto-Save3.gz](https://github.com/wesnoth/wesnoth/files/3511260/HttT-The.Bay.of.Pearls-Auto-Save3.gz)

**Comment by Konrad22** [comment]
This affects LoW S16 and probably SotA S17 (I can't check that one because it's broken).
And probably any scenario that advances a unit for story reasons. So if this change has not been documented yet, please document it. In bold letters.

**Comment by sevu** [comment]
The WML didn't change…

**Comment by gfgtdf** [comment]
this was probably caused by my changes to the [modify_unit] tag, should we try to change [modify_unit] back to animating the advancement? Alternatively we could also just change ADVANCE_UNIT to animate the advancement.

**Comment by GregoryLundberg** [comment]
In [modify_unit] I would expect it to be optional, defaultint to no animation. Given the name, I would expect ADVANCE_UNIT to do the animation (possible with an option to suprpess it).

**Comment by sevu** [comment]
> (possibly with an option to suprpess it).

advancing without animation can already be done by TRANSFORM_UNIT / [transform_unit]

**Comment by Wedge009** [comment]
I didn't see what the lack-of-animation looked like in 1.15.0, but checking this in 1.16.8 release (HttT S4, after turn 3), the unit advancement seems to be as normal.
