### ISSUE TITLE
Story scenes do not render properly (black screen)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4245]
I'm stuck with a black screen. The window still reacts, I get my nice cursor. I just can't do anything with wesnoth except close it (which works as if everything else was fine as well).
![](https://cdn.discordapp.com/attachments/259976436490829825/612046914837414107/unknown.png)
Windows 10, 1.15.0
To reproduce: Load the savefile and try to proceed without using 'esc'.
https://cdn.discordapp.com/attachments/259976436490829825/612047813915705405/SotA-Mortality.gz
If you skip the talking by pressing esc when Ras-Tabahn speaks (for the first time, which is also the last things thats said) or earlier, then everthing works fine.

**Comment by sigurdfdragon** [comment]
Can't reproduce with the attached save or my own using either esc or not.
I get the game moving on as expected tested against current master

**Comment by Konrad22** [comment]
As you can see, this bug is still present in 1.15.1 and is not just about SotA. (E.g. HttT, Elvish Council)
![grafik](https://user-images.githubusercontent.com/39015360/63386874-51722a00-c3a4-11e9-9783-6aea9c615e77.png)
![grafik](https://user-images.githubusercontent.com/39015360/63386882-56cf7480-c3a4-11e9-89e0-128ac3cef1e9.png)

![grafik](https://user-images.githubusercontent.com/39015360/63386976-926a3e80-c3a4-11e9-84d2-f757cc973186.png)

**Comment by Konrad22** [comment]
There is also this, which might be related.
![grafik](https://user-images.githubusercontent.com/39015360/63388166-c85cf200-c3a7-11e9-9d33-756ed310411e.png)
Mousing over hexes or tabbing out 'fixes' it though.

**Comment by Konrad22** [comment]
I have exactly the same issues on a different pc of mine. @Wedge009 remembered encountering something like the last screenshot with a bad graphics driver bug.
I have Intel(R) HD Graphics 520 on one and NVIDIA GeForce 9600 GT on the other.

**Comment by grz0** [comment]
I have an issue on Linux which may be related to this one
https://github.com/wesnoth/wesnoth/issues/4196

**Comment by Wedge009** [comment]
Haven't yet had time to test my various platforms but would be interesting to see if there are any common patterns here in terms of graphics hardware, drivers, operating systems, SDL libraries, or even something else entirely.

**Comment by Konrad22** [comment]
For some reason I do not encounter this bug when playing 1.15 on steam. But I am guaranteed to encounter it when using the sourceforge version.

**Comment by Wedge009** [comment]
I didn't realise 1.15 is on Steam already - do you need to opt-in to beta releases?

Would have to confirm with the packagers but I would expect that the Steam version should match the binaries distributed on Sourceforge.

**Comment by jostephd** [comment]
> For some reason I do not encounter this bug when playing 1.15 on steam. But I am guaranteed to encounter it when using the sourceforge version.

That's just what you said on #4237. Did you mean to post this to both issues? If so, it's possible they have a common cause.

**Comment by Konrad22** [comment]
Yes, I did mean to do that.

**Comment by Konrad22** [comment]
Referencing #4309 because this looks very similiar even though the steps are not the same.

**Comment by Wedge009** [comment]
I got this on Windows, confirmed with the save file attached in the original report but also - surprisingly - just by starting Secret of the Ancients and using debug->choose_level to skip to the Mortality scenario.

**Comment by Wedge009** [comment]
Consolidated report. Tested:
- Secret of the Ancients: Mortality (it looks like the screen is being redrawn prematurely, hence everything not being animated going to black)
- Heir to the Throne: Elven Council (story scene only - I didn't get the black screen problem on the game map)
- Git code repository pulled as at 2019-09-13 ~09:00 UTC (but problem appears to be have started well before this time)

Where I find the problem **does** occur:
- Windows 1.14.8+dev
- Windows 1.15.1+dev

Where I find the problem **does not** occur:
- Windows 1.14.7 release
- Linux 1.14.8+dev
- Linux 1.15.1+dev

**Comment by Wedge009** [comment]
Another place where this occurs: Opening story scene of Delfador's Memoirs. The common thread seems to be that these are all story scenes. I wonder if there's something specific done (or not done) in terms of graphics for story scenes only.

**Comment by Wedge009** [comment]
@Konrad22 From what I read in #wesnoth-dev, 1.15.1 release is 32-bit on Steam and 64-bit as stand-alone build (what you called 'sourceforge version'). Can you verify if you have different results with respect to 32-bit vs 64-bit, please?

**Comment by Konrad22** [comment]
Yes. Steam one works fine, SF displays this bug.
(Loading the very same savefile.)

**Comment by Wedge009** [comment]
So it appears 64-bit builds on Windows (or perhaps one or more of the dependencies) have something to do with this...

**Comment by Pentarctagon** [comment]
1.14 still isn't 64-bit though, I believe, just 1.15+.  @loonycyborg is this correct?

**Comment by Wedge009** [comment]
1.14.7 release is 32-bit on Windows, so everything is fine there from what I can tell. But my 1.14.8+dev compilations are 64-bit on Windows. Will check the refresh command soon.

**Comment by Wedge009** [comment]
It's a story-only scenario where this happens - I don't think I can enter the `:refresh` command when a unit is 'speaking'... I had a moment where there was animations happening in SotA Mortality and I snuck in a `:refresh` then, but the screen kinda flickered between correct drawing and the black screen before the story scenario ended.

**Comment by soliton-** [comment]
Perhaps check if https://github.com/wesnoth/wesnoth/commit/fb1e62c09ab30361a286b7458a1c56dac66f63d8 and https://github.com/wesnoth/wesnoth/commit/ee35f6ac9adf7285fed9219a4801602a5955869f have any effect on this.

**Comment by Wedge009** [comment]
Thanks for that, but doesn't appear to be a direct cause in this case. I took 1.14, reverted fb1e62c0, and fixed the conflicts as best as I could but I still get the issue afterwards.

**Comment by Wedge009** [comment]
Just reporting that my brother downloaded the stand-alone 1.15.1 release and also gets this issue as well as #4237. I suspect not many people download the development build (if they do, they probably do it via Steam) so it hasn't had much exposure.

**Comment by Wedge009** [comment]
Confirming SDL 2.0.10 x64 is responsible. SDL 2.0.9 is fine (though @stevecotton notes there are security issues in the older versions).

**Comment by Wedge009** [comment]
Disabling the batched renders feature that's default in SDL 2.0.10 seems to resolve this.

**Comment by bckpkol** [comment]
On Windows (AMD Mullins+Hainan dual), everything works fine for me.
On two machines, with Arch Linux (Intel HD integrated) and its stable spin Manjaro (AMD Mullins+Hainan dual), 1.12 works fine. But not 1.14. I can confirm that in SotA black screen happens at the Meeting of the Minds, and in Hammer of Thursagan it happens in the scenario when Angarthing is introduced. But the Bad Moon Rising UMC fails right after the words "I - I have the rock.", which is the first speech ever. Just start the first chapter, skip "Lethal fatique", and it will fire.

**Comment by Wedge009** [comment]
1.14.9 release does not have the work-around to disable the batched rendering that's set by default in SDL 2.0.10. This issue is related to story scenes - if you are finding rendering problems specific to input, that is, the issue does _not_ occur in a story scene where dialogue is not skipped, that may be an issue which you should probably report separately. One way to confirm this is if neither downgrading to SDL 2.0.9 nor setting an environment variable to disable batched renders `SDL_HINT_RENDER_BATCHING=0` resolves it.

**Comment by bckpkol** [comment]
SDL_HINT_RENDER_BATCHING=0 does not solve this. But after downgrading to 2.0.9-1, the problem is gone.

**Comment by Wedge009** [comment]
How are you running the hint? At least two of us confirmed that switching batched renders via environment variables resolved this issue for SDL 2.0.10.

Yes, we know moving the mouse in this case is enough to trigger a redraw. If you really think your issue is not batched renders related, please submit a new issue instead of reporting on this old one.

**Comment by bckpkol** [comment]
Aha! Found. Edit 02_Reclaiming_The_Past.cfg, remove the line
`theme=Cutscene_Minimal`
and the bug vanishes!

**Comment by bckpkol** [comment]
`[stuntj@bckpkol-silvermont ~]$ SDL_HINT_RENDER_BATCHING=0 wesnoth`
Is that okay?

**Comment by bckpkol** [comment]
Imagine this:

- in 1.14.x that works neither way.
- in 1.15.x somebody notices the bug. He thinks that bug only affects non-batch render, so he leaves the old code, and adds a switch to his workaround when batch rendering is disabled.

The result? In 1.15.x disabling batch render works, in 1.14.x not.
You simply say batch render doesn't work anymore, instead of fixing.

**Comment by bckpkol** [comment]
Checked. I have no problems in the latest dev 1.15.x version, even without that variable, but 1.14.x are broken, even with that variable. However, how can I re-enable batch render in 1.15.x, to debug it?

**Comment by Pentarctagon** [comment]
You'd need to comment out the line in 6436f902498f4a910df2c34601a2871ac6c55e57 and rebuild wesnoth, I assume.

**Comment by bckpkol** [comment]
Thanks. I don't have a time for this right now. Maybe I'll respond after a two weeks.

**Comment by bckpkol** [comment]
Gonna do. I have a complete repo clone.
