### ISSUE TITLE
1.15, HttT, Konrad's portrait is not used after he is lvl 2

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4248]
Windows 10, 1.15.0
[HttT-Muff Malal’s Peninsula.gz](https://github.com/wesnoth/wesnoth/files/3512470/HttT-Muff.Malal.s.Peninsula.gz)
![grafik](https://user-images.githubusercontent.com/39015360/63217775-98fe7900-c14c-11e9-92cf-c42f27dfe38f.png)

**Comment by gfgtdf** [comment]
there is no reason to undo the whole thing just because it does not work for the profile attribute, just remove the corresponding conditional for that attribute in in unit::write (and for small_profile_ aswell for that matter)
