### ISSUE TITLE
HttT S5b Isle of the Damned, Ship at the end of the scenario should be visible 

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4251]
Due to the map being under the cover of fog, the arriving ship is sometimes not visible (when you have no unit close by), resulting in a disembodied voice that _somehow_ appeared (or rather did not appear) and spots Konrad.
I suggest lifting the fog around the arriving ship. Maybe even an exchange of words between the people on the ship and Konrad to confirm for them that he is actually there?

**Comment by GregoryLundberg** [comment]
Both sound good to me.

What do you propose for the conversation?

It took me a while to get it so it was a (known) unit doing the talking, but a ship on the map. At that point I just wanted to move on, so I'm not surprised if I missed some edge conditions.

**Comment by Konrad22** [comment]
Something like 
My Lord, are you here?
Over here! Let's finally leave this dreadful place.

I'm no writer though.

**Comment by GregoryLundberg** [comment]
I'm marking this Saved for Later. I might be able to get it done in a few days. I've not been keeping up with the development status; I believe there's a string freeze in effect for 1.15, so this would have to wait a bit, anyway.

This is a drop-dead easy change, though. So I'm marking this Good First Issue in the hopes someone will take care of it before I can get to it.

**Comment by jostephd** [comment]
There's no string freeze on 1.15.

**Comment by stevecotton** [comment]
@GregoryLundberg I'm looking at the current comments and wondering if there's a much easier way to do it. Re the paragraph below, AFAICS when the ship arrives the player is going to be in a scripted event which will end with moving to the next scenario - they won't know if the WML restores their recall list before the ship animation happens. Am I missing something?
https://github.com/wesnoth/wesnoth/blob/495f60dfbf57e7280fbc1d7fbef7a6189e642d45/data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg#L41-L44

I haven't tried yet, but it seems the sequence could be:
* Restore recall list
* Recall real unit
* `[object]duration=scenario [effect]copy the disguise code from EI S11`

**Comment by GregoryLundberg** [comment]
I don't really care how it's done. I remember I was trying a lot of different ways to get the ship, the highlited hex, on the map, and the Advisor's image on the dialogs. I remember looking but don't remember finding the "disguise code" in EI. What I wanted was to see the ship arriving through the fog, the Advisor from the previous scenario speaking as if in/on the ship. I think I settled on this because it was the first which worked and I was taking too long on this scene and felt the project was stalled because of it.

**Comment by jostephd** [comment]
Added the lift_fog. Could someone retitle the issue please?

**Comment by GregoryLundberg** [comment]
Title seems fine. To my mind, lifting the fog around the ship is enough and this can be closed. But someone might want to consider the dialog changes @Konrad22 suggests.

**Comment by jostephd** [comment]
Fair enough. Let's close this, then. We can open a new issue for any further dialog or WML improvements.
