### ISSUE TITLE
Dwarvish Berserker has irregularities in Team Colours

### ISSUE THREAD

**Issue by Earth-Cake** [wesnoth/wesnoth#4252]
Dwarvish berserker has irregularities in TC, which can be seen in this topic: https://forums.wesnoth.org/viewtopic.php?f=9&t=49319

**Comment by sevu** [comment]
Also affects the Masked Berserker in ThoT. (not surprising)

**Comment by jostephd** [comment]
This is easy to see on a Berserker that belongs to side 2 (blue), the color of the trousers changes:

![2019-09-09-062731_72x218_scrot](https://user-images.githubusercontent.com/24784687/64507740-0eccaf00-d2cb-11e9-97e7-898b72bbac88.png) ![2019-09-09-062725_69x211_scrot](https://user-images.githubusercontent.com/24784687/64507741-0eccaf00-d2cb-11e9-8924-f11c7230e591.png)

This is not as easy to see in Berserkers that belong to other sides.

**Comment by Earth-Cake** [comment]
I usually zoom in when I check TC.
