### ISSUE TITLE
Ranges like 1-99999, {EVERYWHERE} and {INFINITY} are bugs waiting to happen

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4253]
I don't like "amount=1...99999" even though we see it in existing code, because it's a bug laying in wait. "amount=1..." seems harder to parse and error prone (too visually similar to "amount=1").

_Originally posted by @GregoryLundberg in https://github.com/wesnoth/wesnoth/pull/4233#issuecomment-522594643_

**Comment by ProditorMagnus** [comment]
Such constants have been defined as 99 and 999 depending on context.

**Comment by stevecotton** [comment]
A suggestion of adding allowing `amount=1-infinity`, along with the necessary changes to the validation schema, are in the originally-referenced bug.
