### ISSUE TITLE
wesnoth.require Currently if you require a file by different (relative) paths, each will be a different copy.

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4256]
see the comment in 
https://github.com/wesnoth/wesnoth/blob/60fd504caf46bbb1648de369303b76225d805e5d/data/lua/package.lua#L39

To solve this problem we probably need an api function to resolve relative filenames, what im currently wondering is whether we should add a new one, or make wesnoth.have_file return the resolved filename in case it exists.

**Comment by gfgtdf** [comment]
any opinion on whether we shoudl make wesnoth.have_file return the real path or adda  new function to do this?

**Comment by soliton-** [comment]
Can you give an example of different paths resolving to the same file? Are you talking about preprocessor stuff like `{./path}`?

**Comment by gfgtdf** [comment]
this is lua i currently dont remember how it work in wml, but in lua you can do stuff like `wesnoth.dofile("./a.lua") from b/a2.lua or `wesnoth.dofile("./b/a.lua") from a3.lua or `dofile("./../a.lua") from b/c/a4.lua and they will all open the same file.

**Comment by CelticMinstrel** [comment]
Pretty sure WML and Lua use the same C++ functions for this?

Anyway, I think logic of this sort belongs in the `resolve_package` function, particularly the `if` on line 21, so I think a separate function from `have_file` would make sense. I'm quite not sure what to call it though... the idea is to get a unique canonical name that identifies the file, so maybe `canonical_file`?

**Comment by soliton-** [comment]
I agree that canonical should be in the name, perhaps `canonical_path`.

**Comment by gfgtdf** [comment]
> Pretty sure WML and Lua use the same C++ functions for this?

Actually no, iirc wml inclusion does not support going 'upwards', its a lua-only feature build on top of the original get_wml_location function, the main problem is that in lua we only want to allow loading data from save locations (the addon directly or the wesnoth data directory) while in wml we also sometimes want to load from other sources (like for example loading scenario for the map editor which iirc allows loading scenarios from any directory). So in lua we were able to implement this easily by simply not allowing to load stuff outside these directories, while in wml a general solution its somehow nontrivial because allowing going upwards ("../") might be a a security problem. and the solution we have in the lua code (always work with 'safe' poaths . etc "~add-ons/" or "/data") does not work in the wml case becasue it'd break for exampel the ability to load scenarios from any directory in the map editor.

**Comment by CelticMinstrel** [comment]
> Actually no, iirc wml inclusion does not support going 'upwards'

That said, it _should_ support that, treating the "data" folder as the root directory. I did implement it, but then people said I should take a different approach...
