### ISSUE TITLE
HttT S19b Swamp of Dread, scenario objectives do not update

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4262]
There as a Bonus objective (Defeat all Death Knights first). After fulfilling said objective and opening the Scenario objectives, it still lists the Bonus objective.
Please have it be updated instead.

**Comment by Wedge009** [comment]
Not sure I understand this. What sort of mid-game update in the objectives are you expecting?

**Comment by Konrad22** [comment]
Before beating all Death Knights
![before](https://user-images.githubusercontent.com/39015360/63499547-57f9c200-c4c8-11e9-9f6a-f92afde6b4ec.png)
After beating all Death Knights
![after](https://user-images.githubusercontent.com/39015360/63499564-5d570c80-c4c8-11e9-94e1-05a050063454.png)

**Comment by Wedge009** [comment]
It's been a while since I've played properly (ie not for debugging purposes). Is it normal for objectives to be updated mid-game? I have a vague recollection of it but can't be sure.

**Comment by Konrad22** [comment]
E.g. UtBS.

**Comment by Konrad22** [comment]
Oops.

**Comment by Wedge009** [comment]
Fair enough. But any in the more 'conventional' campaigns?

**Comment by GregoryLundberg** [comment]
Actually, it's fairly common to update the objectives as things move along. Can't believe I missed this one. *sigh*
