### ISSUE TITLE
Create new game_info entry for when an MP campaign advances to the next scenario

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#4281]
From Discord/IRC:
```
<Soliton> i meant to mention that mp campaigns are handled poorly so far.
<Soliton> as in advancing to the next scenario.
<Soliton> that should create a new entry.
```

**Comment by ProditorMagnus** [comment]
How is their replay handled?

**Comment by soliton-** [comment]
You can detect advancing if an already started game is started again.
Since the DB code is only in server.cpp so far you may want to add a `game::is_started()` or so function.

**Comment by gfgtdf** [comment]
> How is their replay handled?

iirc not at all onyl the replay of the last game is saved, iirc there is also a seperate bug entry for that

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/issues/1492

**Comment by soliton-** [comment]
Good point about the replay. A separate issue but sure would be great to fix that as well.

Probably just needs a `save_replay()` call at the right spot...

**Comment by Pentarctagon** [comment]
Unassigned myself from this and #4341 since I'm really not sure how to solve the problem.
