### ISSUE TITLE
Additional game/player information to store?

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#4284]
Now that Wesnoth 1.14+ is storing some information about games played and the players, as documented in [table_definitions.sql](https://github.com/wesnoth/wesnoth/blob/master/utils/mp-server/table_definitions.sql), there's also the question of what other information would be useful to store.

This issue then is for discussing that, and for anything agreed upon a task item can be added to this issue.

- [x] Store the version used by each player in `game_player_info`.
- [x] Store the source the client was downloaded from.
- [x] Store whether the game is reloaded.
- [ ] Associate a reloaded game to its previous row in `game_info` (unsure if this is practical).
- [x] Store the versions of add-ons used.
- [ ] Store which side(s) won/lost (the easiest implementation being to just check for leaders being alive/dead, or a surrender).
- [x] Store whether observers are allowed.
- [x] Store whether a password is set.
- [x] Store whether the game should have a publicly available replay (currently identical to whether observers are allowed, pending the second item of #3909).
- [x] Store the player name as well as their ID, due to [this](https://github.com/wesnoth/wesnoth/issues/4463#issuecomment-542937081).
- [ ] Provide an API to allow add-ons to store information in the database?

**Comment by gfgtdf** [comment]
for game_player_info we could also store the version used, during that game, similary for users maybe the last game version used.

for game_info, if #4282 goes in we might want to store the game of the the previous scenario of the campaign or have another way to group games from one campaign together.

And finally it'd be really nice to be able to identify reloaded games, meaning when a game was loaded somehow point to the 'old' gameid, but i currently don't know how to do that. In the end we might even support some 'load from server' function where saves can be stored at the server, the cient has a 'resume server game' button that'd allow to load any game stored the the db associated with that user that is not marked as 'ended by victoy/defeat'.

The main problem with a reload form server function i see is that the server only stores replays and not actualy savegames, and having the users replay the whole previous scenario on reloading woudl probably be annyoing.

**Comment by soliton-** [comment]
All good ideas.

The server has some code to identify save games/reloads:
https://github.com/wesnoth/wesnoth/blob/ff772b1be828e93e788a8dd4103a692150728116/src/server/game.cpp#L308
https://github.com/wesnoth/wesnoth/blob/ff772b1be828e93e788a8dd4103a692150728116/src/server/game.cpp#L357-L362
Not sure there is really a way to figure out the old game id currently. The server would presumably have to send the clients the game id or similar so they can put it in save games and it's available on reload.

**Comment by Pentarctagon** [comment]
Two other ideas that came up during the initial PR as well:
* Also storing add-on version numbers.
* Storing victory/defeat for sides.

**Comment by gfgtdf** [comment]
> Also storing add-on version numbers.

Sounds like an easy to implement and useful feature to me.

> Storing victory/defeat for sides.

I also really support this one, although i am not sure that it's doable with the I formation that is currently send to the server.

**Comment by Pentarctagon** [comment]
Closing as most suggestions have been implemented, and the remaining are questionably possible/useful.
