### ISSUE TITLE
Recent regression affecting unitmarker mod

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4288]
I've noticed two regressions using the Unitmarker mod.

1. Install Unitmarker mod
2. Start Liberty S1
3. Right-click a unit and choose "Flag this unit"

In `1.15.0-23-g612a9132305`, I get the correct behavior:

![2019-08-27-224403_331x102_scrot](https://user-images.githubusercontent.com/24784687/63813145-39f2ee00-c91c-11e9-9715-1202fd0cd81c.png)

(Note that even slightly older master might still have the bug; @stevecotton fixed it not long ago, in... #4211, I think?)

In `1.15.1-64-g4830c76f45c` (current master), I get:

![2019-08-27-224636_479x95_scrot](https://user-images.githubusercontent.com/24784687/63813264-93f3b380-c91c-11e9-8bfa-db294c2a05d0.png)

There's also a bunch of `warning gui/layout: pango_text::validate_markup text '&misc/red-x.png=Revert all changes' has unescaped ampersands '&', escaped them.` warnings that weren't there before.

This looks like a regression. Even if it's intentional it should at least be added to changelog, which hasn't happened yet.

Related to #4058. Sorry for not having done more research or provided a minimal example but I don't have time right now.

**Comment by gfgtdf** [comment]
does that mod have a github repo so that we an look at its code?

**Comment by jostephd** [comment]
https://files.wesnoth.org/addons/1.14/Unitmarker.tar.bz2

**Comment by stevecotton** [comment]
I suspect the cause of `&misc/hearticon.png~CROP(9,0,19,14)=With a Heart!` is 93dff47a75c9fe32692e63aa189d14d5317c201c. I haven't tested that, but that string is the old deprecated-style way of adding icons to `[option]`s.

@jostephd what's the other regression? I only see one of them in this bug report.

**Comment by gfgtdf** [comment]
yes, @Pentarctagon what was teh reason for this change? were you aware of this comatability break when you did it?

**Comment by jostephd** [comment]
> @jostephd what's the other regression? I only see one of them in this bug report.

1. Requiring the ampersand to be escaped
2. The image not showing

It sounds like these might be two effects of a single change, though. And it sounds like the change was intentional, so we just need to document it, and I should send a bug report to the Unitmarker addon author?

Thanks for the quick answers, everyone.

**Comment by stevecotton** [comment]
> Separately though, is there a way we would want to indicate in the changelog changes that break backwards compatibility? Maybe just make them bold, or something like that?

I think UMC authors should probably read all of the changelog's "WML Engine" sections, and the "AI" and "Lua API" if they're using those features. Ensuring that breaking changes are listed in one of those is probably good, and it means other readers are distracted by bold formatting.

**Comment by gfgtdf** [comment]
We used to have a separate section for breaking changes in The forum announcement. And I think we still do

**Comment by jostephd** [comment]
Put it first in the "WML Engine" section and start the line with "incompatible change:"? I don't think the entire line needs to be bold, maybe just the part before the colon. And please update the wiki https://wiki.wesnoth.org/InterfaceActionsWML#.5Bmessage.5D

**Comment by Pentarctagon** [comment]
@stevecotton and @gfgtdf - We do, and I assume will (once 1.15.1 is finally formally announced), but then we also tend to end up separately creating a single list of changes for users anyway ([1.8 to 1.10](https://forums.wesnoth.org/viewtopic.php?f=21&t=33321), [1.10 to 1.12](https://forums.wesnoth.org/viewtopic.php?f=21&t=36057), and [1.12 to 1.14](https://forums.wesnoth.org/viewtopic.php?f=21&t=47614)).

@jostephd Do you mean beyond what's already on the wiki?

**Comment by jostephd** [comment]
@Pentarctagon The description of `[option]message` implies that it behaves the same in 1.14 and 1.15, which is no longer the case, is it?

**Comment by Pentarctagon** [comment]
So the correct place to mention this would be [here](https://wiki.wesnoth.org/DescriptionWML#Description_texts), I would think.

**Comment by jostephd** [comment]
I guess we can close this, then?
