### ISSUE TITLE
TRoW / Green Isle geography: should Oldwood be the forest south of the Swamp of Esten?

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4289]
Is the wrong Green Isle forest labelled as the Oldwood?
![Green Isle map](https://raw.githubusercontent.com/wesnoth/wesnoth/master/data/campaigns/The_Rise_Of_Wesnoth/images/maps/green_isle.png)

The scenario before Oldwood is either 04a in the Swamp of Esten, or 04b which is south-west of the Swamp. The scenario after Oldwood is Clearwater Port, which means the forest labelled Oldwood is the north edge of a plain which still has to be crossed from north to south after Oldwood.

At the end of 03, Haldric is aiming to get to Southbay rather than Clearwater Port; in 04b he gets warned that the road to Southbay is full of orcs, and goes in to Oldwood on the way to Clearwater. If it's the labelled forest then he goes around the south and east of the Swamp, and in to a forest far north of the straight line from where he was to Clearwater.

The Oldwood scenario itself has Haldric starting at the north-west corner.

There's a signpost in south of the Swamp that says "SW - Oldwood":
https://github.com/wesnoth/wesnoth/blob/4830c76f45c5f5d6cc299dd850d468aee2c46b60/data/campaigns/The_Rise_Of_Wesnoth/scenarios/04a_The_Swamp_of_Esten.cfg#L481-L482

**Comment by stevecotton** [comment]
An alternative idea: maybe 04b should be followed by 04a, so the player always goes through the Swamp (and has the opportunity to collect the loyal auto-recalled white mage). Choosing to go to 04b would become an optional detour, granting some XP but also meaning the Swamp has to be played with a tighter time limit.

**Comment by sevu** [comment]
linking https://r.wesnoth.org/p647341

**Comment by stevecotton** [comment]
Resolved:
* the Oldwood is east of the Swamp of Esten
* the Midlands scenario is going to be removed, as discussed in PR #4377
* the signpost and dialogue in the Swamp is fixed by a5bfb20f599800159014d0e8cfd4de2211994844
