### ISSUE TITLE
1.15.1 THoT - S4 High Pass, enemies don't move

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4290]
I can basically just walk over the map without fighting once as long as I move around my enemies.
[THoT-High Pass replay.gz](https://github.com/wesnoth/wesnoth/files/3549600/THoT-High.Pass.replay.gz)

**Comment by stevecotton** [comment]
Although the mage was removed, the AI is now trying to avoid `x,y=undefined,undefined`:
```
 [avoid]
     x,y=$magehut.x,$magehut.y
 [/avoid]
 ```

Comparing the file to the 1.14 version, I prefer the old dialogue, "Something frightened those orcs we fought among the bandit villages ... I’ve a grim feeling we might be going to discover that in person" to the new war-mongering from Movrur.

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/af2aaf4ba6cf8bf5cc5c3cf682460a836f5c6c27
