### ISSUE TITLE
1.15.1 THoT, wrong advancement for Dwarvish Masked Ulfserker

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4294]
Said unit advances to 'Dwarvish Berserker' instead of 'Dwarvish Masked Berserker'.
![grafik](https://user-images.githubusercontent.com/39015360/63968857-da721b00-caa0-11e9-8ecc-fb1786d61761.png)

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/f5f5da0828d9388a8c7c07299f908f8c5796c175
