### ISSUE TITLE
UMC .po translations are not shown in the add-ons manager

### ISSUE THREAD

**Issue by slavrenyuk** [wesnoth/wesnoth#4296]
My campaign was recently translated to Simplified and Traditional Chinese languages. Only .po files were added according to this documentation 
> If an add-on contains only .po files instead of .mo files, then Wesnoth (since 1.14) will read the .po files directly. This means that you can check it in-game without needing to compile a .mo file. 

https://wiki.wesnoth.org/GettextForTranslators

The languages are available in the game, but they are not shown in the add-on manager.

![addon_folder_structure](https://user-images.githubusercontent.com/5528718/64027376-3a240100-cb49-11e9-8406-962759c11d3e.jpg)
![translation_available](https://user-images.githubusercontent.com/5528718/64027377-3a240100-cb49-11e9-88df-4e1a84b1ca4a.jpg)
![translation_not_shown](https://user-images.githubusercontent.com/5528718/64027378-3abc9780-cb49-11e9-8d0d-e786cc3add96.jpg)

**Comment by soliton-** [comment]
The addon server expects a LC_MESSAGES directory with the parent dir being the locale.

**Comment by soliton-** [comment]
Well, actually it was already updated to consider .po files as well: https://github.com/wesnoth/wesnoth/commit/1db6fb3

Are you sure you uploaded the .po files?

**Comment by soliton-** [comment]
Ok, looks like the addon server was not rebuilt since that commit. Rebuilding now...

**Comment by soliton-** [comment]
@slavrenyuk Please upload your campaign again.

**Comment by slavrenyuk** [comment]
@soliton- Reuploaded, translations are shown now, thanks.

![translations_present](https://user-images.githubusercontent.com/5528718/64048521-9eab8400-cb7a-11e9-9870-9837975d644a.jpg)
