### ISSUE TITLE
TSG S04: No sign of a struggle at Mebrin's home

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4301]
In S04, a hint about the identity of the Big Bad is that Mebrin left his home without a struggle:
https://github.com/wesnoth/wesnoth/blob/18b4477e62c367be56cc7e7e0278cd5065d43590/data/campaigns/The_South_Guard/scenarios/04_Vale_of_Tears.cfg#L670

However, the backstory revealed in S06a is that he didn't turn to the dark arts until the bandits had captured and tortured him.

**Comment by nemaara** [comment]
I guess I was thinking that the bandits would've ambushed him and taken him by surprise (along with the other elves), otherwise they would've sent for help. It's not really a big plot point now, though, so I can change it if you like.

**Comment by GregoryLundberg** [comment]
"there is no sign" --> "there is so little sign"

**Comment by stevecotton** [comment]
Reading the context again, I was misreading "footprints" as "one set of footprints".

I'd replace the "no sign of a battle" line with one of the bodyguards saying "I can see footprints from more than a dozen pairs of boots, and no skeletal feet among them." That has the problem that the bodyguards might not have appeared by this point.
