### ISSUE TITLE
Lua sanitation of game_config can be bypassed

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4302]
`wml.parse("game_config.cfg")` works and returns the contents of [game_config.cfg](https://github.com/wesnoth/wesnoth/blob/master/data/game_config.cfg).

This is unexpected, since the Lua API `wesnoth.game_config` is sanitized:

https://github.com/wesnoth/wesnoth/blob/8bdd2e6764fd0315e556b7b5577fe19243a30f2e/src/scripting/lua_kernel_base.cpp#L988-L1004
https://github.com/wesnoth/wesnoth/blob/8bdd2e6764fd0315e556b7b5577fe19243a30f2e/src/scripting/lua_kernel_base.cpp#L713-L724

What's more, game_config.cfg may contain addresses of private MP servers, or presentation layer UI customizations (custom audio files / colors) - Lua addons don't need to be able to access this sort of info.

I suppose we should split game_config to separate engine-related information (such as MP server addresses) from gameplay-related information (such as `recall_cost`)?

**Comment by jyrkive** [comment]
> I suppose we should split game_config to separate engine-related information (such as MP server addresses) from gameplay-related information (such as `recall_cost`)?

I think it would be better to just block game_config.cfg from being read directly. Add-ons can use `wesnoth.game_config` to read the parts they need.

**Comment by CelticMinstrel** [comment]
Why is this marked low-priority? If it's a potential privacy issue, shouldn't it be high-priority?

**Comment by jostephd** [comment]
> Why is this marked low-priority? If it's a potential privacy issue, shouldn't it be high-priority?

I had asked about this before creating the issue and was advised to treat it as a public, low-priority issue. I hadn't been sure either, and given your comment, I'll remove the label (for now, anyway).

> Maybe it's simplest just to block _any_ toplevel file?

Shouldn't we be doing a whitelist rather than a blacklist? Addons shouldn't have any reason to load any file not in the add-ons directory, right?

**Comment by CelticMinstrel** [comment]
Well, yeah, we could just go ahead and blacklist the entire main data directory, sure. I imagine some people could come up with niche reasons for loading files there, but...

**Comment by shikadiqueen** [comment]
I'm just going to leave this here:
```
[set_variables]
    name=test1
    mode=replace
    [literal]
        {_main.cfg}
    [/literal]
[/set_variables]

[set_variables]
    name=test2
    mode=replace
    [literal]
        {game_config.cfg}
    [/literal]
[/set_variables]
```
Etcetera.

> If private information exists within the core dir then there's something horribly wrong with whoever added such private information
