### ISSUE TITLE
build failure on 1.15.1 complaining about  env["have_fortify"]

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#4306]
I'm trying to build wesnoth, tag `1.15.1` with scons, but it fails.

`git status` says:
```
HEAD detached at 1.15.1
nothing to commit, working tree clean
```

I'm building with this command:
```
scons prefsdir=.local/share/wesnoth/"$branch" --config=force ccache=yes prefix="$prefix" destdir="$destdir" build=debug extra_flags_debug=-Og
```

and I'm getting this error:
```
...
Checking for dbus-1... (cached) yes
Checking for fribidi >= 0.10.9... (cached) yes
Checking for C library history... yes
Checking for Boost unit_test_framework library... yes
  If any config checks fail, look in build/config.log for details
  If a check fails spuriously due to caching, use --config=force to force its rerun
---[applying configuration]---
KeyError: 'have_fortify':
  File "/home/vasya/data/dev/games/wesnoth/wesnoth/code.cache/SConstruct", line 525:
    if not env["have_fortify"] and "-O0" not in env["opt"]:
  File "/usr/lib/python3.7/site-packages/SCons/Environment.py", line 410:
    return self._dict[key]
```
(the exit code is `2`)

The contents of `.scons-option-cache` file are:
```
default_targets = 'wesnoth,wesnothd'
build = 'debug'
extra_flags_debug = '-Og'
prefix = '/'
prefsdir = '.local/share/wesnoth/1.15.1'
destdir = '/home/vasya/data/dev/games/wesnoth/wesnoth/target.cache/1.15.1'
ccache = True
```

Operating system is ArchLinux, `scons-3.1.1-2`.

Am I doing something wrong? What could be the reason of the failure?

**Comment by vgaming** [comment]
Note that in SConstruct line 525, changing `env["have_fortify"]` to `env.get("have_fortify")` fixes the problem.

**Comment by vgaming** [comment]
I'm closing this issue since the commit already landed in `master`.

**Comment by jostephd** [comment]
Doesn't this need to be backported?

https://github.com/wesnoth/wesnoth/blob/1.14/SConstruct#L509

**Comment by vgaming** [comment]
@jostephd it probably should indeed.

Though we never fully understood the reason of this bug to ever occur. The last hypothesis was python version (which doesn't feel like it's explaining everything though).

I've created a PR:
https://github.com/wesnoth/wesnoth/pull/4332

**Comment by jostephd** [comment]
> Though we never fully understood the reason of this bug to ever occur. The last hypothesis was python version (which doesn't feel like it's explaining everything though).

Well, there's this:

https://github.com/wesnoth/wesnoth/blob/90f69b0494c30ea346fb7ef4f102c40c0303a65b/SConstruct#L379-L380

So the obvious suspect is that env['harden'] is false for some reason...

**Comment by vgaming** [comment]
@jostephd could it be some trick with `if false` and `if null` having the same effect and happily "compiling" in dynamic languages? IDK though, I don't see it in the quoted code, to it's just a random guess..

**Comment by jostephd** [comment]
@vgaming That's basically what the fix does (it causes the expression to evaluate to `None`, rather than throw a KeyError), but this doesn't explain what the original problem was. Maybe if you put a `print(repr(env['harden']))` right above the line I linked we'll get a hint?

**Comment by vgaming** [comment]
I did use `env.Dump()` when we discussed it in IRC. Results were (master branch):
env: https://gist.github.com/vgaming/6673e41fcecfd9b26d7b44cf1bbc22cb
client_env: https://gist.github.com/vgaming/f20e36fdc068fc618ae8e8142f161d6c
test_env: https://gist.github.com/vgaming/18e157cd2776553c981bd644974e8936

**Comment by jostephd** [comment]
Thanks. I don't see the problem, `harden` and the outer condition's `prereqs` are both true, so `have_fortify` should've been set. At what point did you do the dump? The assignment I linked above might be overwritten by https://github.com/wesnoth/wesnoth/blob/0cf8da9357285941980b804ce1dd871eede9c8b7/SConstruct#L386, for all I know...

**Comment by vgaming** [comment]
I'm a bit busy ATM, so just answering the question: the Dump() was suggested to be done (and was done) right before the loop on env types. Manually for the 3 types of env-s, e.g. `env_test.Dump()`.
