### ISSUE TITLE
1.15.1 game crash with calculate_probability_of_debuff assertion failure

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#4307]
This was the message in the terminal after the crash:
```
wesnoth: src/attack_prediction.cpp:1772: double {anonymous}::calculate_probability_of_debuff(double, bool, double, double, bool, double): Assertion `initial_prob >= 0.0 && initial_prob <= 1.0' failed.
```

The crash appeared when I've let wesnoth play an AI-vs-AI game. To be specific, I've let computer play on Creep Wars (3p) map. At the end of this game, most AI units had objects that give them lots of MP and strikes.

Unfortunately, I don't have a savegame as it was a pure-AI game.

**Comment by vgaming** [comment]
CC @jyrkive

**Comment by jyrkive** [comment]
Okay... this is pretty much impossible to investigate without a save file. :(

**Comment by vgaming** [comment]
I will try to repro, if I figure out a way for wesnoth to make those goddamn savefiles.

**Comment by Vultraz** [comment]
You can still manually save (ctrl+s), can't you? Or does that not work in pure AI games.

**Comment by vgaming** [comment]
@Vultraz Saving (Ctrl+S) probably does work in AI games. But -- it crashed!

BTW, unrelated possible room for improvement: take a savegame before dying in case of exceptions like that.

**Comment by vgaming** [comment]
It crashes quite often actually, given a specific map. Here's an example savegame:
[Creep Wars 3team 1.5.2 Turn 76b.gz](https://github.com/wesnoth/wesnoth/files/3568834/Creep.Wars.3team.1.5.2.Turn.76b.gz)

If you load this savegame and press "End Turn", the game will crash in about 1 game out of 2-3.

**Comment by jyrkive** [comment]
`initial_prob` is passed in at 1.0000052293729125. Looks like a rounding error at this point.

**Comment by vgaming** [comment]
I wonder if we may want an additional check like `v < 1.000001` here. Possibly in debug build only(?). Just an idea though, I think you can decide better (jyrkive).

**Comment by vgaming** [comment]
Thanks for fixing!
