### ISSUE TITLE
1.15.1 possibly broken `droid` command

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#4308]
Steps to reproduce:
* start any game
* type in user command `droid`
* ~~observe the response "Invalid action provided for side '1'. Valid actions are: on, off, full" (this is good)~~
* ~~type in `droid on`~~

Expected at this point:
* current side (1) gets droided

Actually:
* "Error: can't droid invalid side: '0'.

**Comment by soliton-** [comment]
The syntax is: `droid [<side> [on/off/full]]`

Just `droid` should work. `droid on` is not valid.

**Comment by soliton-** [comment]
Looks like there is no default anymore for the last argument. Default should be to toggle. I.e. if the side is AI controlled switch away from it and if not switch it to AI.

**Comment by vgaming** [comment]
@soliton- you're right indeed. I've edited the description a bit if you don't mind as well.

**Comment by Pentarctagon** [comment]
Do you get the same invalid side error on 1.14? on/off/full not being optional was probably caused by me when I added the "full" option, but the logic determining the side when not provided hasn't changed between [1.14](https://github.com/wesnoth/wesnoth/blob/99953ef9573d8630886d934f25f57152fce1ca96/src/menu_events.cpp#L1427) and [master](https://github.com/wesnoth/wesnoth/blob/0f5b6848304c8b76509dd2f9ff8624aff783d075/src/menu_events.cpp#L1434).

**Comment by vgaming** [comment]
@Pentarctagon when I enter `droid` when playing side 1 on wesnoth-1.14, I get it toggled (as expected). The "synopsis" that you see by entering command `help droid` also suggests that droid should do _something_ without arguments.

**Comment by vgaming** [comment]
I checked that yesterday on ArchLinux-s system wesnoth-1.14.7-1.

**Comment by vgaming** [comment]
@Pentarctagon code-wise, I think the problem is with parsing "action" (`on`/`off`/`full`) instead of parsing side, as already noted by @soliton- .

**Comment by soliton-** [comment]
There's no default handling for action here:

https://github.com/wesnoth/wesnoth/blob/efd808ea842ff88174cc2e953c8b871b8c41dae0/src/menu_events.cpp#L1442-L1471

If action is empty it should call `toggle_droid()`.

**Comment by Pentarctagon** [comment]
@vgaming The check for whether "side" is valid comes first though, so if the error "Error: can't droid invalid side: '0'." happens after just typing `:droid`, then that seems to indicate that the line I linked is also giving different results in 1.14 vs master.

@soliton- If side 1 called `:droid 1 full` and then `:droid`, that would leave them with a controller of AI but a proxy controller of PROXY_HUMAN for example, which doesn't sound right.

**Comment by soliton-** [comment]
The side is no issue except that if the last optional parameter doesn't work properly it doesn't matter how earlier parameters are handled.

I just mentioned `toggle_droid()` as what was done before. I have not looked closely how the new `full` action changes that. That needs to be considered certainly.

**Comment by vgaming** [comment]
Thanks for fixing! Code-wise, seems to be good. I'll check in-game if another RC release will be made.
