### ISSUE TITLE
1.15.1 Switching virtual desktops with full-screen wesnoth causes graphics issues

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#4309]
Steps to reproduce:
* start wesnoth
* open preferences > Display > enable "full-screen" checkbox
* start any game
* switch to another application
* switch back to wesnoth

Expected at this point:
* battlefield is shown normally

Actually:
![2019 09 02_22:35:19](https://user-images.githubusercontent.com/33452702/64150848-667d9d00-ce29-11e9-9dcf-ca6baa04d0aa.png)

**Comment by jyrkive** [comment]
Which operating system do you use? This may well be OS specific (and even depend on your window manager if you use GNU/Linux).

**Comment by vgaming** [comment]
@jyrkive I'm using ArchLinux, XFCE desktop environment, but no compositor (window manager) at all. (To be clear: yes, really, no compositor. Neither xfwm4 nor compton.)

**Comment by vgaming** [comment]
When I hover the tiles, they get back to normal.

**Comment by jyrkive** [comment]
All right, I added the Linux label for now.

**Comment by Pentarctagon** [comment]
I'm not able to reproduce this on Linux Mint 19.2.

**Comment by vgaming** [comment]
I tried to reproduce locally again, but on the first attempt, I couldn't (read further).

The problem apparently only appears if you have "Preferences -> Didsplay -> Full screen" checkbox enabled. In non-fullscreen mode, there's no such bug for me as well.

Can anybody please confirm the existence or not existence of this bug if said checkbox is enabled? (BTW, it is the default preference when people install wesnoth anew.)

**Comment by dvladf** [comment]
I couldn't reproduce this problem (with fullscreen mode) on Kubuntu 18.04. Probably, this is specific for xfce.

**Comment by vgaming** [comment]
Very interesting. My system is XFCE indeed, but there's no window manager, so it should be identical to any other DE with no compositor. I'll check this bug with a compositor enabled in the evening.

**Comment by Pentarctagon** [comment]
I'm still not able to reproduce the issue when switching between Wesnoth and TF2, whether either or both are fullscreen.

Does anything change if you do `:refresh`?

**Comment by jostephd** [comment]
The minimap part looks similar to @Konrad22's screenshots on #4237/#4245.

And there's also #4196.

I use openbox on Debian, in case it matters.

**Comment by Wedge009** [comment]
I think this is a separate issue from Konrad22's reports. If I understand vgaming's original post correctly, this one happens generally, not in specific circumstances.

**Comment by vgaming** [comment]
@Pentarctagon yes, if I enter :refresh, everything goes back to normal. Note that just "fullscreen" of the window manager is not enough. It's only the wesnoth-s built-in "refresh" checkbox that makes the graphics buggy for me.

**Comment by vgaming** [comment]
EDIT ^

**Comment by vgaming** [comment]
If it's desired, I can try to bisect the commit from which it started to behave this way.

**Comment by Pentarctagon** [comment]
Refresh checkbox?

**Comment by vgaming** [comment]
@Pentarctagon sorry, typo. "Full-screen" checkbox.

**Comment by Pentarctagon** [comment]
Ah, right, that makes more sense :P

And yeah, a bisect would help, unless anyone has an idea where a redraw call would need to be added to fix this issue.

**Comment by Wedge009** [comment]
I re-tested with full-screen (technically borderless window) option in both Windows and Linux, 1.14.7, 1.14.8+dev, and 1.15.1+dev, and couldn't replicate this, unfortunately.

Yes please, it would be helpful if you can find the commit that broke this for you since it looks like no-one else has been able to replicate the symptoms yet.

**Comment by vgaming** [comment]
Ah, nevermind about bisecting I guess.. It behaves this way in 1.14.7 already. IDK how far away should I dig to find it.. I'll try 1.14.0 or something like that out of curiosity though.

**Comment by Wedge009** [comment]
Was it a long time since you last played successfully? It really does sound like it's peculiar to your system. BTW, what graphics drivers are you using? The driver issue I saw before some time ago, which had this very same symptom (and all the time, just like this issue) was with proprietary NVIDIA drivers (nouveau was fine, I think).

**Comment by vgaming** [comment]
@Wedge009 the bug apparently only happens when using wesnoth-s built-in "fullscreen" mode. So I normally never observe it as I don't play wesnoth fullscreened. And even if I'do, it'd be the WM-s fullscreen mode, which doesn't have the bug.

The reason I saw the bug now is that I tested on a "clean" configuration, where fullscreen is enabled by default.

**Comment by Wedge009** [comment]
Then it may well go back as far as 1.12 or even earlier.

**Comment by vgaming** [comment]
(Oh sorry, forgot to add: I have an Intel graphics card. So that's one exact possible driver.)

**Comment by Wedge009** [comment]
Hmm, I just tried it on a Skylake-based laptop (Linux) and couldn't encounter this issue. :/

**Comment by jostephd** [comment]
> * switch to another application
> 
> * switch back to wesnoth

How exactly do you switch to another application? There are bugs (such as #3255) that only happen when I switch virtual desktop but not when I Alt+Tab staying within the virtual desktop.

**Comment by vgaming** [comment]
Oh indeed! I never thought it's important, but apparently it is.

I _do_ switch to a different virtual desktop and back.

Just checked: if I switch within same virtual desktop, the bug doesn't appear.

**Comment by vgaming** [comment]
Furthermore, if I press the key combination to switch between windows within same virtual desktop (like Alt+Tab, but Super+Tab on my system), the screen is refreshed and the bug disappears. Otherwise, I had to hover all tiles with my mouse until they all refresh.

**Comment by Wedge009** [comment]
Interesting, that helps explain why I couldn't see anything wrong, I don't appear to have issues with virtual desktop switching, at least not with Wesnoth. There is #2880 but that report is a full crash rather than just graphical problems.

**Comment by stevecotton** [comment]
I can reproduce both this and the command-is-too-dark issues on Debian unstable.
Downgrading libsdl2 from `2.0.10+dfsg1-1` to `2.0.9+dfsg1-1` fixes both issues for me (without recompiling), however there's known security bugs in the older version.

**Comment by Wedge009** [comment]
Thanks, @stevecotton! That was the key - I only have SDL 2.0.9 on Linux so didn't have the issue there. I can't replicate this particular issue (with the virtual desktop switching) but it does affect my other issues relating to 64-bit compilation.

**Comment by Wedge009** [comment]
@stevecotton If you can, please check if 6436f90 helps with the virtual desktop switching (on SDL 2.0.10).

**Comment by stevecotton** [comment]
Yes - this fixes it for me (Debian with Mate desktop environment, Marco window manager)

**Comment by Wedge009** [comment]
Thank you. I assume this is resolved then, unless @vgaming indicates otherwise.

**Comment by vgaming** [comment]
// I've already built `master`, will test in a few hours from home if I won't forget. Yes it's fine to close, I'll re-open if anything.

**Comment by vgaming** [comment]
Confirming that the bug is fixed in `d5e58ed64dd`. Thanks for fixing!

**Comment by Wedge009** [comment]
Thanks for confirming!
