### ISSUE TITLE
SotBE S3, Special notes talk about a function I don't have

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4311]
![grafik](https://user-images.githubusercontent.com/39015360/64231619-714f3500-cef0-11e9-9add-98b8d8c1deb4.png)
![grafik](https://user-images.githubusercontent.com/39015360/64231626-757b5280-cef0-11e9-95b6-d63bcd9b36c0.png)

I guess that funtion was removed at some point?
I do not know if this is for 1.14 and 1.15 or just 1.15.

**Comment by stevecotton** [comment]
The removal was in #3668 's 23d313949d4ed9c13dcf7e5afe7a6296bce0580e, so 1.15 only.

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/03cd1a6e0aaa0fc164481f98dd20795b391af927
