### ISSUE TITLE
Factual inconsistencies in LoW and SoF

### ISSUE THREAD

**Issue by clockback** [wesnoth/wesnoth#4314]
The _main.cfg file for LoW says it starts in 20YW. The scenario "The Treaty", however, takes place in 15YW. Also, in SoF's "A Bargain is Struck", Haldric II speaks about meeting the elves in Weldyn, when he actually met them in Tath.

**Comment by clockback** [comment]
[https://forums.wesnoth.org/viewtopic.php?f=8&t=50702&p=646986#p646986](url)

**Comment by clockback** [comment]
Pull request to solve first part of problem is here:
https://github.com/wesnoth/wesnoth/pull/4319

**Comment by nemaara** [comment]
PR merged, seems to solve both.
