### ISSUE TITLE
Date of The South Guard

### ISSUE THREAD

**Issue by TomOfWesnoth** [wesnoth/wesnoth#4321]
As of now, The South Guard starts eighty-nine years after the end of Heir to the Throne. The protagonist of The South Guard, Deoran, is the grandson of Haldiel from Heir to the Throne. This is _just about_ possible, but a bit of a stretch. I'd suggest moving The South Guard to take place around ten years earlier.

In combination with Issue #4320, this should reduce the eighty-nine year gap to a more plausible seventy-four year gap.

**Comment by jostephd** [comment]
Or we could change "grandson" to "great-grandson". (This has the advantage of not creating problems for UMC that takes place during those years)
