### ISSUE TITLE
1.15 [modify_unit] not able to disable canrecruit

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#4325]
`wesnoth.wml_actions.modify_unit{{"filter", {}}, canrecruit=false}` has no effect.

Confirmed as regression compared to 1.14.7.

**Comment by gfgtdf** [comment]
please test after https://github.com/wesnoth/wesnoth/commit/7621b9b63ec47893a254ad7c54f686f7c71e225b

**Comment by ProditorMagnus** [comment]
Fix helps
