### ISSUE TITLE
Mousing over a village should show the owner side in the UI

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4344]
When you mouse over a village, the caption under the minimap says "Enemy village" or "Allied village", but nowhere does the UI say which side owns the village; you're supposed to infer that from the flag's color and shape, but that's not always easy (see #2682). So this is a suggestion to add to the UI somewhere an identification of which side controls the village: their leader's name, if known (as in the Game Status dialog), or else their side number.

**Comment by Wedge009** [comment]
Looks like relevant part is in terrain code:
https://github.com/wesnoth/wesnoth/blob/d52783a7eaf9e254b7f552c54228d007c7f5af8f/src/terrain/terrain.cpp#L183-L204
I'm not sure if team information is available there as it currently stands. There may also need to be consideration of side/team names for translations (as this has been a lingering issue in the past).

**Comment by jostephd** [comment]
> I'm not sure if team information is available there as it currently stands.

Team information is _definitely_ available at the point that decides which of those strings to show, and in any case, so long as we know the x,y of the village we can use the singletons in resources.hpp to determine any info we need (controlling team, viewing team, village owner, fog, etc).

> There may also need to be consideration of side/team names for translations (as this has been a lingering issue in the past).

[side]team_name is the translatable team name. There is a member function in team.hpp that returns that value too. I don't see a problem here.

**Comment by stevecotton** [comment]
I wonder if there's any UMC that defines custom values for `income_description`, `income_description_ally`, etc. The current version of #6458 would remove support for those by replacing the text with the owner's name; I'm wondering if deprecating the old feature is actually the right choice.

**Comment by CelticMinstrel** [comment]
I think it's not great that there are four different income description fields, but I don't think there's any other way to make it work with localization. You can't just substitute the main income description into a string like `_"Allied $name"`, because there's no way to inflect that correctly for an arbitrary `$name` in languages that require adjective-noun agreement.

**Comment by Pentarctagon** [comment]
Resolved by #7920
