### ISSUE TITLE
[floating_text] is too fast

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#4347]
The WML tag [floating_text] is too fast, as the title says.  It's not that recent an issue, but I'm not sure when it started.
https://wiki.wesnoth.org/InterfaceActionsWML#.5Bfloating_text.5D

Put this event in HttT scenario 01_The_Elves_Besieged.cfg and move Konrad a step (this avoids complications like dialogs popping up).  
>`[event]`
        `name=moveto`
        `[filter]`
            `id=Konrad`
        `[/filter]`
        `[floating_text]`
           `x,y=19,23`
           `text="<span color='#cccc33'>" + _ "Your text here" + "</span>"`
        `[/floating_text]`
`[/event]`

If there is a key to specify the speed, it's not documented on the wiki, and it's not 'time'. 
EDIT:  This is BfW 1.14, I have no idea about 1.15.

**Comment by stevecotton** [comment]
The speed is hardcoded in game_display::float_label(), so no way for WML to override it. It is affected by the game acceleration speed, so if you're playing at 16x speed there's no chance to read it.

**Comment by doofus-01** [comment]
Also too fast to read at 1x speed.

**Comment by gfgtdf** [comment]
> Also too fast to read at 1x speed.

It it really specific to floating_text? That is is it rally faster than for example the green numbers when a unit is healed at the start of a turn?

**Comment by doofus-01** [comment]
Seems so, yes.

**Comment by gfgtdf** [comment]
I'm quite sure that both harm_unit and floating_text are implemented in lua and call the same lua function to display the text

**Comment by doofus-01** [comment]
Ah, yes, I assumed for some reason harm_unit worked, but it is also too fast if it is by itself.

**Comment by jostephd** [comment]
Is this just a matter of changing the magic numbers in the function @stevecotton identified, or is there more to it than that?

<details>

<summary>
proposed values
</summary>

```
--- a/src/game_display.cpp
+++ b/src/game_display.cpp
@@ -616,8 +616,8 @@ void game_display::float_label(const map_location& loc, const std::string& text,
 	flabel.set_font_size(font::SIZE_XLARGE);
 	flabel.set_color(color);
 	flabel.set_position(get_location_x(loc)+zoom_/2, get_location_y(loc));
-	flabel.set_move(0, -2 * turbo_speed());
-	flabel.set_lifetime(60/turbo_speed());
+	flabel.set_move(0, -1 * turbo_speed());
+	flabel.set_lifetime(225/turbo_speed());
 	flabel.set_scroll_mode(font::ANCHOR_LABEL_MAP);
 
 	font::add_floating_label(flabel);
```

</details>

@doofus-01 When posting code segments please use multiline text areas, delimited by ` ``` ` on a line by itself, that will preserve indentation.

**Comment by gfgtdf** [comment]
> Is this just a matter of changing the magic numbers in the function @stevecotton identified, or is there more to it than that?

Doofus said it onle effected the last loationg message shown, so I'd say no.

**Comment by jostephd** [comment]
@gfgtdf Ah! I had tested with two [floating_text] and didn't see the problem, but when I test the example from https://github.com/wesnoth/wesnoth/issues/4347#issuecomment-531521894 I do see the problem. So it's not what I thought it was.

**Comment by gfgtdf** [comment]
adding a `[delay]` after the `[floating_text]` also seems to workaround this issue.

**Comment by gfgtdf** [comment]
the set_lifetime function

https://github.com/wesnoth/wesnoth/blob/60fd504caf46bbb1648de369303b76225d805e5d/src/floating_label.hpp#L52-L53

says its measured in 'frames' so maybe during event excution there are just less frames per second?

**Comment by gfgtdf** [comment]
thinking about it didn't @jyrkive recently removed the fps cap by default? That could have caused the bug.

**Comment by jostephd** [comment]
While testing this with one floating_text and with different magic numbers in game_display::float_label, I noticed that the speed at which the text moved varied. When the text appeared it moved up about a hex's height very quickly, and then it moved the rest of the way more slowly.

**Comment by jyrkive** [comment]
@gfgtdf The FPS cap is still enabled by default.

**Comment by jostephd** [comment]
Similar: https://github.com/wesnoth/wesnoth/issues/3607#issuecomment-428100147
