### ISSUE TITLE
Make tooltips use brighter green

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4348]
Some tooltips, at least the time of day and traits tooltips, use a dark green color. @ProditorMagnus reports this is platform specific.

See https://forums.wesnoth.org/viewtopic.php?p=647304#p642778 and following posts (including the spoiler)

The dark green should be made brighter, probably #00ff00 which is what windows already uses. Also make sure the red is legible.

**Comment by ProditorMagnus** [comment]
`<span foreground='green'>` is also affected.

**Comment by gfgtdf** [comment]
At some point pango changes it's definition of 'green', I don't know in which version exactly though.

**Comment by sevu** [comment]
Does that mean that windows just used outdated Pango libs, and the 1.15.1 exe from SourceForge (not the Steam one) has the same green like linux?

**Comment by gfgtdf** [comment]
> Does that mean that windows just used outdated Pango libs, and the 1.15.1 exe from SourceForge (not the Steam one) has the same green like linux?

Quite likely, i noticed the color change when i updated pango on my local windows build.

**Comment by jostephd** [comment]
> At some point pango changed it's definition of 'green', I don't know in which version exactly though.
> 
> [GNOME/pango@d2c319b#diff-86329ef9c3175a3504b08a9a0b7b069eL77](https://github.com/GNOME/pango/commit/d2c319b9ded8cce864914d9f1fd704a7aff3112f#diff-86329ef9c3175a3504b08a9a0b7b069eL77)

Thanks for finding that!

According to your link, they changed #00FF00 to #008000 in version 1.32.2. I have version 1.40.5 and I see #008000, so that checks out. In the current version of rgb.txt, #00FF00 is available as `green1`, so maybe we can use that?

https://github.com/GNOME/pango/blob/7dfa511509fcf34f6756963eddc4babf0da933e1/tools/rgb.txt#L277-L280

**Comment by Wedge009** [comment]
Confirmed, Windows 1.14.7 release is using pango 1.30.1 - currently using pango 1.40.11 in my own Windows builds.

green1 looks like the way to go - but that will mean the newer pango should be included for the next releases. Is green1 what you used in your proposed change in the forums?

**Comment by jostephd** [comment]
Thanks for confirming

> green1 looks like the way to go - but that will mean the newer pango should be included for the next releases.

`green1` was added to rgb.txt in pango 1.31.1. It's seven years old so there shouldn't be a problem requiring that as the minimum version, and we can check that (`#if PANGO_VERSION_ENCODE(1,31,1) >= PANGO_VERSION`). What does green1 do on older pango, though? (Easiest way to test this is to parrot hex in the test scenario and write `<span color='green1'>foo</span>` when prompted)

> Is green1 what you used in your proposed change in the forums?

I hardcoded `#00ff00`, which is equivalent to green1.

**Comment by jostephd** [comment]
> What does green1 do on older pango, though?

I don't have an old pango to test with, but with current pango using an unknown color name is treated as a markup syntax error, so wesnoth displays the pango source text (with `<` and everything) literally.

The color names `red` and `red1` have both been `#ff0000` as far back as I've checked, so we're safe there. So it seems we just have to use `green1` instead of `green`.

**Comment by Wedge009** [comment]
@Pentarctagon asked a reasonable question in #wesnoth-dev as to whether or not the 'too dark' command-line/message text issue (which I've yet to formally record here) could possibly be related to the pango change. However, I don't think this is the case as Linux builds still work fine for me and I have 1.42.3 there and it's still reading fine.

**Comment by Wedge009** [comment]
I wasn't expecting anyone to, just noting the similarities that Pent pointed out. I haven't yet made a proper report (with expected screen shots) because at this point I think it's tied in with the other two issues.

**Comment by jostephd** [comment]
> The color names `red` and `red1` have both been `#ff0000` as far back as I've checked, so we're safe there. So it seems we just have to use `green1` instead of `green`.

Discussion on IRC recommends to avoid relying on pango color names, i.e., hardcode the hex color or use our own `color_t` constants.

**Comment by Wedge009** [comment]
Confirming the 'too dark' command/message text is completely separate to this pango issue.

**Comment by Wedge009** [comment]
I didn't look in detail but #3706 appears to be wrestling with the question of how to map RGB values with colour IDs, so possibly related.

**Comment by jostephd** [comment]
#3706 is about letting WML access the RGB values of team colors. This issue is about having consistent colors in the UI regardless of Pango version.

**Comment by CelticMinstrel** [comment]
(Why the heck is Pango redefining core colours!?)

In general I'd agree on avoiding the named colours here.

**Comment by hexagonrecursion** [comment]
Is this simply a matter of running `sed -i s/green/#00ff00/ **/*` and manually reviewing the diff? If so I'll do it.

**Comment by Wedge009** [comment]
Thanks for looking into this. It does sound as though we should perhaps use hard-coded colour values to keep things consistent, instead of the named colours which - as we've seen - can change.

If you're be willing to see where instances of green are used it might be useful. I'd be curious to see if any potential conflicts with the functions that perform a 'red to green' gradation for unit terrain defence probabilities and unit resistance ratings (I think they use different colour gradients).

Also, for the record, the original issue is still present: green is still the dark version for unit tool-tips for 1.14.15 release running with Pango 1.44.7 (although the title screen details says it was compiled under Pango 1.30).

**Comment by Wedge009** [comment]
> (Why the heck is Pango redefining core colours!?)
> 
> In general I'd agree on avoiding the named colours here.

I just noticed that in the commit gfgtdf mentioned, the message states:
> Colors that were defined to different values in Pango than they were in
the CSS specification have been updated to conform to the CSS specs.
See http://dev.w3.org/csswg/css3-color/#svg-color for the color values.

So it seems the colours are unlikely to change again without good reason like a change in specifications. Without noticing this I was thinking to go with hard-coded colour definitions instead. But if it's based on specifications, it may be okay to continue using the named colours and adjust our use of green accordingly... unless we still have to negotiate the possibility of differing pango versions before and after change, in which case, yeah, probably still have to go with hard-coded colours just to be safe.

(Sorry, thinking out loud - or in writing - there.)

**Comment by cooljeanius** [comment]
some documentation of this issue on the wiki or somewhere would be helpful

**Comment by Wedge009** [comment]
...why? Isn't it already documented here? Why duplicate the effort?

But by nature of what wikis are, you can do so if you think it will be helpful.

**Comment by cooljeanius** [comment]
> ...why? Isn't it already documented here? Why duplicate the effort?
> 
> But by nature of what wikis are, you can do so if you think it will be helpful.

In the "Formatting" section of InterfaceActionsWML it mentions you can use a color name such as 'red', but it doesn't specify the full list of color names available, or what they correspond to: https://wiki.wesnoth.org/InterfaceActionsWML#Formatting

**Comment by Wedge009** [comment]
Okay. With this issue, though, it seems ideally we want to avoid named colours in the future.
