### ISSUE TITLE
name_inactive key of [specials] tag is ignored in attack dialog

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#4352]
Concerning the weapon specials
https://wiki.wesnoth.org/AbilitiesWML#The_.5Bspecials.5D_tag

The inactive name works for the side panel, but the attack dialog just uses the (active) name with gray font.

This is for BfW 1.14

**Comment by jostephd** [comment]
Sidebar:

https://github.com/wesnoth/wesnoth/blob/8d576ddc523d1909a6595184f9cce07b781b127b/src/reports.cpp#L943-L953

Attack Enemy dialog:

https://github.com/wesnoth/wesnoth/blob/8d576ddc523d1909a6595184f9cce07b781b127b/src/units/abilities.cpp#L747-L773

Proposed fix:

```
diff --git a/src/units/abilities.cpp b/src/units/abilities.cpp
index 049c23f8575..c28749a9082 100644
--- a/src/units/abilities.cpp
+++ b/src/units/abilities.cpp
@@ -760,7 +760,10 @@ std::string attack_type::weapon_specials(bool only_active, bool is_backstab) con
 	{
 		const bool active = special_active(sp.cfg, AFFECT_EITHER, sp.key, is_backstab);
 
-		const std::string& name = sp.cfg["name"].str();
+		const std::string& name =
+			active
+			? sp.cfg["name"].str()
+			: default_value(sp.cfg, "name_inactive", "name").str();
 		if (!name.empty()) {
 			if (!res.empty()) res += ", ";
 			if (only_active && !active) res += font::span_color(font::inactive_details_color);
```

@doofus-01 This works in my testing; can you test it too?

**Comment by jostephd** [comment]
Linking #3686 which introduced the gray.

**Comment by doofus-01** [comment]
@jostephd - I will test this this weekend, if no one else gets to it first.  Thanks.

**Comment by doofus-01** [comment]
@jostephd - I tested your proposed fix and it works.  Thank you.  I'll leave this issue open for your fix to get committed.

**Comment by jostephd** [comment]
Thanks for testing!
