### ISSUE TITLE
Backports to 1.14.10

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4356]
- [x] 0a6ed0ae4f25509d53fa6d22eba5439f79100111
- [x] d26c2a2290a8f4e06f296043c11076d7db51ab51
- [x] b4e977555b15cef6e781107fbb8cf5400123730c
- [x] 90f69b0494c30ea346fb7ef4f102c40c0303a65b
- [x] 4c0a012b5b54fff6474c9232ccdc75eab2de65df
- [x] ~~8867aab43fb89d720aca1629ae7c26967cb2b0a6~~

Postponed until ~~end of 1.14.9 string freeze~~ after 1.14.9 is released.

**Comment by sevu** [comment]
Hold back because of string changes:
- [ ] f32fda8
- [ ] 5cfe19e
- [ ] b73435f
