### ISSUE TITLE
SotBE S7, Scenario objectives refer to an unknown name

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4369]
That's the objectives once you spot side 2.
![grafik](https://user-images.githubusercontent.com/39015360/65312732-6dc7d900-db93-11e9-8980-0039af814fb0.png)
The problem is, I have no idea who that Ar-Dant is supposed to be. Noone told me or Kapou'e.
I suggest changing it to 'defeat all units from side 2' or something like that.

**Comment by Wedge009** [comment]
I'm guessing that Ar-Dant is the leader of the enemy team and this is only revealed upon discovering units of that team. So the leader Ar-Dant would most likely be still on his keep and invisible to the player at this point.

I'm pretty sure this isn't the only place where we have this kind of situation, objective to kill team leader only revealed upon discovering the enemy team. How do those scenarios handle this?

**Comment by Konrad22** [comment]
Enemy leaders are usually not named in the scenario objectives, especially not if you only meet them once and never again.

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/de0fda74d0209f614c03e46ff23c820c5e87377f
