### ISSUE TITLE
[1.15] wmllint: issue with defense cap

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4379]
Wmllint reports correctly if a unit reqired the defense cap.
However, after adding it, it reports:
```
"data/campaigns/Liberty/units/Bone_Knight.cfg", line 3: unit Bone Knight is missing traits forest=-70
"data/campaigns/Liberty/units/Skeleton_Rider.cfg", line 3: unit Skeleton Rider is missing traits forest=-70
```
The units have forest-70 due to the mounted movetype.

Aside from that, it's unclear where the complains about `forest=-70` come from, grepping for it doesn't find anything within wmllint. Strictly speaking, the defense cap note should also be used if another terrain is negative.

**Comment by newfrenchy83** [comment]
Normally, defense in terrain 0<=def_cap<=100, 0 was invulnerability and 100 is 100% to be hit, forest=70 instead for me, the negative value must be to origin of bugs.

**Comment by soliton-** [comment]
Please check the documentation before declaring something a bug: ["If the defense value is negative, then the unit will be hit as though the value were positive with one difference: the number is also the best defense that the unit may have if there is more than one terrain type for the terrain the unit is on."](https://wiki.wesnoth.org/UnitsWML#.5Bmovetype.5D)

**Comment by stevecotton** [comment]
The association between `NOTE_DEFENSE_CAP` and `forest=-70` comes from this line (changing the text here changes the error message when checking Liberty):
https://github.com/wesnoth/wesnoth/blob/ca71057e7fde459941cb825a920b23cd093e7adf/data/core/units/undead/Skele_Chocobone.cfg#L12-L15

@CelticMinstrel this seems like it will break for any unit that uses `NOTE_DEFENSE_CAP` for a non-forest terrain (and it's broken for units that get their defense stats from `movetype`).

**Comment by newfrenchy83** [comment]
It must erase wmllint of this file, then?

**Comment by stevecotton** [comment]
Hmm - now that special notes are known to the engine via the `[special_note]` WML tag, should the equivalent of NOTE_DEFENSE_CAP be automatically added by the engine when it shows units with defense caps, without needing to be in the WML? The engine already needs to have a special case for it in the help browser, to show the extra column of statistics.

**Comment by CelticMinstrel** [comment]
How exactly can the engine automatically detect a defense cap? It doesn't sound possible to me. Maybe I'm missing something.

**Comment by stevecotton** [comment]
I don't understand your question - or at least if I do understand it, then the answer is "by calling movetype::has_terrain_defense_caps, which the help browser already does to determine whether to show the extra column with the defense caps in".

**Comment by CelticMinstrel** [comment]
I guess the question amounts to what that function's actually doing...

**Comment by stevecotton** [comment]
Class `movetype` is where the calculations for mixed terrains are done, it's calculating based on the numbers in the unit's `[defense]` or `movement_type=` config.

**Comment by jostephd** [comment]
@CelticMinstrel, I think @stevecotton is asking whether the unit type topic generator should call movetype::has_terrain_defense_caps on the unit type and if that function returns true, automatically add {NOTE_DEFENSE_CAP} to the unit type before processing it.

That `match forest=-70 with {NOTE_DEFENSE_CAP}` is really not a permanent fix. We should figure out some design that doesn't require a separate match statement for every terrain type and every terrain defense value. @stevecotton's suggestion does that (at least for the default core), or we could try to make wmllint look for "any terrain type has a negative value in the [defense] section". I already mentioned wmllint should use wmlparser3 once today so I won't do that again...

**Comment by CelticMinstrel** [comment]
Wait, so you're saying any negative defense value counts as a defense cap?

**Comment by soliton-** [comment]
The documentation is quoted and linked above https://github.com/wesnoth/wesnoth/issues/4379#issuecomment-534604268

**Comment by CelticMinstrel** [comment]
Oh, I see, so the minus sign is not a minus sign but rather a magic marker... I feel like that could cause some problems with stuff like movetype patching. That aside, yeah, I guess the help (or perhaps even the unit build process) could automatically insert this special note if relevant.

**Comment by jostephd** [comment]
"movetype patching"? Do you mean, for example, EffectWML with apply_to=movement `increase=-50`?

Putting it in the unit build process sounds good.

**Comment by CelticMinstrel** [comment]
No, it's something for people who add custom damage or terrain types to patch values for them back into the core movetypes - documentation [here](https://wiki.wesnoth.org/UnitsWML#.5Bresistance_defaults.5D) (both the `_defaults` tags).

**Comment by jostephd** [comment]
Thanks for the reference. Yes, it's a gotcha, people writing formulas will have to be careful about negative values in their inputs.

**Comment by CelticMinstrel** [comment]
That said, you have a point about EffectWML – we might also want to look at tweaking it to transparently handle this case... if someone tries to add 10 to a capped defense, will it actually reduce it by 10 instead? The correct formula is probably `sgn(original) * (abs(original) + increase)`. Also maybe it should offer a simple way to cap or uncap a terrain. In fact, it might be nice for it to support formulas...

**Comment by jostephd** [comment]
Not sure if it'd be easier to add handling of negatives to everywhere that handles terrain defense values, or to just invent a new view of terrain defense values as a map of base terrain type to cth plus a list of base terrains that have caps. It'd be just a new view; the underlying C++ unit_type object would store the movetype data just once, both the current view and the new view would read/update the same data in the backend, and the old view would be deprecated, I guess.

**Comment by CelticMinstrel** [comment]
Indeed, adding a key to the movetype that lists capped terrains would be preferable to using a minus sign as a magic marker. When reading movetypes from the `[movetype]` tag, you could have the presence of that key mark the choice of the new view, so that negative values either produce an error/warning or are made positive. On the other hand, in `[unit_type]` and EffectWML this wouldn't be so easily-detected... for the latter, maybe you'd have to go all out and deprecate `apply_to=movement_costs` in favour of something else? For example, `apply_to=movetype` (which would also deprecate several other `apply_to` values though). But that still leaves the case of `[unit_type]`...

**Comment by jostephd** [comment]
Created https://github.com/wesnoth/wesnoth/issues/4413 for that.
