### ISSUE TITLE
[1.15] running wmllint on mainline campaigns

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4381]
For many campaigns wmllint complains or changes a file.
Appeasing wmllint will uncover the one or other minor issue.

For the biggest part it misses magic comments to associate speakers of [message]s with the speaker. Not sure which comment it needs there, either `who` or another one.

Campaigns:
- [x] tutorial
- [x] tb 
- [x] ~aoi~ (removed with PR #4592)
- [x] tsg (except #4379)
- [ ] httt
- [x] l (except #4379)
- [x] ei (except #4379)
- [ ] did
- [x] thot
- [ ] dw
- [ ] dm
- [x] wov
- [x] trow
- [x] sof
- [ ] low
- [ ] sota
- [x] sotbe
- [x] utbs (except #4379)
- [ ] nr

One way to run wmllint is:
`wmllint --nospellcheck data/core data/campaign/foo`

**Comment by Pentarctagon** [comment]
Would this be something that could be added to the travis builds?

**Comment by sevu** [comment]
Yes, I had that in mind too.

**Comment by stevecotton** [comment]
If it's added to Travis, please ensure there's a way to add new warnings without immediately having to fix old code. As in, if someone writes a new test such as the "speaks in die event" one, they should be able to merge the new version of wmllint before updating all of the existing campaigns.

My concern is that any changes to wmllint would get stuck in unmerged PRs, and other developers wouldn't check their code again not-yet-merged PRs, so the goalposts for merging the PRs would keep moving.

**Comment by Pentarctagon** [comment]
Though the problem would become that very few people likely actually look at the output on builds that travis calls successful, so warnings with nothing else might simply go unnoticed.  C++ warnings and WML schema validation problems are also currently treated as build failures, so I don't think it'd be a huge problem to have a wmllint check follow the same route.

**Comment by cooljeanius** [comment]
There are other bugs open on this topic; see #4494 and #5799

**Comment by Wedge009** [comment]
I suggest this may be closed in favour of #5799. Unless this gets turned into a task to add the checks to Travis.

**Comment by Wedge009** [comment]
Replaced with #7082.
