### ISSUE TITLE
MP: Warn player when hosting a game with outdated add-ons

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4388]
When a player creates a game on the official MP server and one of the enabled addons is not at the latest version available for download, show a warning to that player that he should upgrade. Reason is because other players are unlikely to join a game that uses old versions of addons.

(Probably makes sense to do this not only on the hosting player's side but also in the MP Lobby too, whenever one mouses over a game to see what add-ons it uses.)

**Comment by Wedge009** [comment]
Similar to #3482 though I understand that one to be concerned with the base game while this one is focused on add-ons.

**Comment by Wedge009** [comment]
Actually, it seems #3482 is about add-ons too, so it seems this one is a duplicate. (Base game is covered in #4825)
