### ISSUE TITLE
Fix [filter_weapon] don't match in [filter_student/opponent/defender/attacker] in weapon like abilities

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#4389]
excuse me, but i forget what for the big mofifications, i must post issue before to put a PR with the solution. When i created weapon like abilities for emulate the specials weapons, i used [filter_weapon/filter_second_weapon] already used in leadership and resistance abilities and i forgeted to  create a filter_weapon child o filter_(student/opponent etc..). For emulation will be perfect, it must change that.

**Comment by newfrenchy83** [comment]
solution here https://github.com/wesnoth/wesnoth/pull/4373/files#diff-42ba1d994f4fa8c6ad17a7efae7936cc

**Comment by newfrenchy83** [comment]
@CelticMinstrel ,@gfgtdf or @jostephd please look this issue and the PR https://github.com/wesnoth/wesnoth/pull/4435, what it could be merged BEFORE béta version.

**Comment by jostephd** [comment]
@newfrenchy83 Does the wiki correctly document the behavior of master as it is today, before #4435?

**Comment by newfrenchy83** [comment]
@jostephd [filter_(second)_weapon] in https://github.com/wesnoth/wesnoth/pull/4435 are inactive if a weapon tags[filter_student/opponent/attacker/defender] is put in abilitie like weapon. It must mark that like deprecated in wiki.

**Comment by jostephd** [comment]
@newfrenchy83 I know that the wiki would need to be updated when #4435 or its replacement #4481 are merged, but **that is not what I am asking about**. I was asking you whether the wiki **as it is today** accurately documents the behavior of master **as it is today**. Does it?

**Comment by newfrenchy83** [comment]
i think what yes, except what [filter_student] not documented, else yes

**Comment by jostephd** [comment]
Let's document [filter_student], then. Would it go in [this section](https://wiki.wesnoth.org/AbilitiesWML#Extra_tags_and_keys_used_by_weapon_special_abilities) or in [this one](https://wiki.wesnoth.org/AbilitiesWML#Common_keys_and_tags_for_every_weapon_special)? What version was it first released in?

**Comment by newfrenchy83** [comment]
It go in https://wiki.wesnoth.org/AbilitiesWML#Extra_tags_and_keys_used_by_weapon_special_abilities because don't exsit in true weapon special but replace abilitie filter_self.
this filter has be commited 15 dec 2018 in https://github.com/wesnoth/wesnoth/commit/ae4af3010c5b0678a69db472c7c93907d8ecfdc1

**Comment by newfrenchy83** [comment]
https://github.com/wesnoth/wesnoth/pull/4481 is complete now

**Comment by CelticMinstrel** [comment]
I can't quite remember, but I think `[filter_student]` might've been in already by 1.15.0? Probably need to check logs to be certain though…

**Comment by CelticMinstrel** [comment]
Also, please confirm - `[filter_student]` should also work in regular `[leadership]` and `[resistance]` abilities, right?

If not, we can remove them from that section in the wiki for now, though the preferred route would be enabling them there.

Incidentally… logically, `[leadership]` should be identical to `[damage]` as an ability, right?  Should we deprecate `[leadership]` in favour of `[damage]`?

**Comment by newfrenchy83** [comment]
Filter_student don't match in regular leadership and resistance, because enemy units can't be filtzred like in damage abilities. I don't like idea to deprecate leadership abilities because calculations rule more compatible with per level effect what [damage], and coloration of damage value in report bar is specific to [leadership].deprecate [filter_(second)weapon] in [resistance], yes, but max_value can't be used in damage.

**Comment by newfrenchy83** [comment]
> 
> 
> Filter_student don't match in regular leadership and resistance, because enemy units can't be filtzred like in damage abilities. I don't like idea to deprecate leadership abilities because calculations rule more compatible with per level effect what [damage], and coloration of damage value in report bar is specific to [leadership].deprecate [filter_(second)weapon] in [resistance], yes, but max_value can't be used in damage.

If i can doing what abilitie damage can work like regular leadership( color of damage in report bar) then yes leadership could be deprecated but i not certain.

**Comment by newfrenchy83** [comment]
> 
> 
> Incidentally… logically, `[leadership]` should be identical to `[damage]` as an ability, right? Should we deprecate `[leadership]` in favour of `[damage]`?

NO, damage not identicall to regular leadership, because https://github.com/wesnoth/wesnoth/pull/3642 don't work in abiliies used like specials, an d who used const unit_map in attack_type instead of const unit.

If damage used instead of leadership, then "multiply" used instead of #value" and two damage abilities cumul effect same if not wanted.

**Comment by newfrenchy83** [comment]
> 
> 
> Also, please confirm - `[filter_student]` should also work in regular `[leadership]` and `[resistance]` abilities, right?
> 
> If not, we can remove them from that section in the wiki for now, though the preferred route would be enabling them there.

i add [filter_student] in leadership and resistance abilities in https://github.com/wesnoth/wesnoth/pull/4481 PR and now i can confirm

**Comment by newfrenchy83** [comment]
someone could add tihsi issue to https://github.com/wesnoth/wesnoth/milestone/20 please?

**Comment by newfrenchy83** [comment]
someone could add the pre 1.16 string milestone to https://github.com/wesnoth/wesnoth/pull/4593 and labelled this, please?
