### ISSUE TITLE
unit preview pane backports

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4394]
Following these two backports:

0db0b8dd3185164a63cd630c7cfddd314bd014cc
26a30fc341df00f40a0d263d23bc4c35cbd29b62

We also need to:

- [x] copy blades.png to blade.png - as done in master as part of 08c469561ca8b9dc90307fd97f32bfad599eec29 - so that blade attacks show the red icon in unit_preview_pane, like all standard attack types do
- [ ] maybe remove blades.png. Whether we can do this depends on whether blades.png is an API that UMC has been allowed to use. If it's an API, we can't remove it in a patch release. If it isn't, we can.
- [ ] document on the wiki whether images/ is a public API or not. There was some disagreement about this on discord
- [ ] consider backporting 08c469561ca8b9dc90307fd97f32bfad599eec29
- [ ] check whether any other related commits also need to be backported. For example, master also uses the damage types in the unit type help pages, if we backported those two commits we might as well backport that one too.
- [ ] document in the release notes that UMC that uses custom damage types or ranges should add images. The code fails gracefully when there are no images, so it's just a UX question.

**Comment by jostephd** [comment]
The "show damage type and range icons" issues have been collected here: https://github.com/wesnoth/wesnoth/projects/4

Here are the commit messages of some relevant commits. I believe the first ten are from master. I am not sure about the last five: I think they too are from master, but it's possible some of them are commits that were pushed to one of the PRs on https://github.com/wesnoth/wesnoth/projects/4 and were subsequently history rewritten before merge.

I don't have the hashes immediately available.

- Help: Reorder columns in unit help page
- Help: Put the icons in the same column as the text that describes them
- Help: Support optional image in push_tab_pair
- Help: Use a typedef instead of hardcoding the concrete type
- Help: Show damage type and range icons in unit help pages
- unit_preview_pane: Add tooltips to the damage type and range icons
- unit_preview_pane: Move the icons to before the damage and strikes, as in the sidebar.
- Break long lines.
- unit_preview_pane: Add attack icons
- Sidebar: Add some vertical padding after attacks that have specials.

- Sidebar: Fix 'damage versus' tooltip not visible
- Sidebar: If the range icon or damage type icon isn't found, fall back to text.
- Sidebar: Make the attack icons the same size as the range and damage type icons
- Sidebar: Show attack, attack range, and damage type icons in the unit_weapons report.

- Just drop the attack icon for now

**Comment by Pentarctagon** [comment]
I'm guessing it would be easier to revert what was already added to 1.14 rather than continue backporting all of this?

**Comment by jostephd** [comment]
> I'm guessing it would be easier to revert what was already added to 1.14 rather than continue backporting all of this?

Not quite.

What happened here is that 5aaf179728d193fa0cdbfd016d54c605c487695b was committed to master and then backported. The backport conflicted so @Vultraz backported [two](0db0b8dd3185164a63cd630c7cfddd314bd014cc) [commits](26a30fc341df00f40a0d263d23bc4c35cbd29b62) that were necessary to fix the conflicts. However, those two commits were part of a larger feature, so either all of the feature should be backported (the blade.png thing because otherwise the UI looks broken, and the rest because there'll be no reason _not_ to backport it once we've backported the first part), or those two commits should be reverted.

I agree with you that it would be easier/better to revert those two commits than to backport the rest of the feature.

Nonetheless, is no particular reason to revert the backport of 5aaf179728d193fa0cdbfd016d54c605c487695b (ec3b2fb381d17a9297ae5f9a2c1ff9fa16649b75). That commit simply changed the whitespace in the unit preview pane (see screenshots in the spoiler). That change is reasonable (which is not the same as saying I agree with it aesthetically - I don't - but that's neither here nor there), and could make sense for 1.14 independently of the damage type and range icons.

However, because Vultraz's change and the damage type and range icon changes conflict with each other, **what I recommend to do** is two steps:

1. Revert ec3b2fb381d17a9297ae5f9a2c1ff9fa16649b75, 26a30fc341df00f40a0d263d23bc4c35cbd29b62, and 0db0b8dd3185164a63cd630c7cfddd314bd014cc (in this order, so there'll be no conflicts).
2. Re-backport 5aaf179728d193fa0cdbfd016d54c605c487695b.

This way, Vultraz's change stays in but the other two commits stay out. (It bears mentioning that when those two commits were added to master, they were _intentionally_ not backported, but nobody told Vultraz that was the case.)

<details>

<summary>
screenshots of Vultraz's change on master
</summary>

![2019-09-29-121342_1920x1080_scrot](https://user-images.githubusercontent.com/24784687/65832421-e4ab5300-e2b2-11e9-9377-956c1d70af4d.png) ![2019-09-29-121323_1920x1080_scrot](https://user-images.githubusercontent.com/24784687/65832422-e5dc8000-e2b2-11e9-9b7d-eb356a547974.png)

</details>

**Comment by jostephd** [comment]
@Vultraz Looking at the screenshots in my last post, does the vertical placement of the red/black icons look right to you? Previously the layout had the red/black icons vertically aligned with a letter that had both an ascender and a descender, but now, the bottom of the icon is aligned with the baseline of the text (the horizontal stroke of the `2` in the first attack), so the top of the icon is much higher than the top end of letters with ascenders.

**Comment by Pentarctagon** [comment]
Added as a Blocker at @jostephd's request.

**Comment by jostephd** [comment]
(That was a misunderstanding.)
