### ISSUE TITLE
Use map_file in MP scenarios in mainline

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4397]
Despite `map_data` exists also `map_file`, which has been undocumented so far. Example:
`map_data={multiplayer/maps/2p_Arcanclave_Citadel.map}`
`map_file= multiplayer/maps/2p_Arcanclave_Citadel.map`

`map_data` parses the map at preprocessor time.
`map_file` does so when loading the scenario – meaning there is less to preprocess, and no need to recreate the cache if the map file has been edited.
The disadvantage however is that it doesn't display a map preview in the MP lobby.

Should we switch to map_file? 
For now, I added the recommendation to the wiki, to use map_file for SP and map_data for MP.

**Comment by Pentarctagon** [comment]
Not showing the map preview sounds like it'd be a problem.

**Comment by sevu** [comment]
That's why I bring this up here – My thoughts so far were:
SP scenarios or rather campaigns in general (SP & MP) have never a map preview — no issue for them, we could use map_file for the campaigns.
MP – can it be changed to work with map_file ? Maybe no good idea, as it would need to read the data in some way, and do it again at scenario start.

If that's the way to go, maybe we can teach wmllint to transform the trival cases of map_data, but only if we're in a [scenario] tag. I'd like to deprecate map_data on level 1, but not remove it, as it _has_ an legitimate use case left (having the scenario data not in an external file). In short, I want to deprecate the use of [scenario]map_data + preprocessor inclusion.

**Comment by gfgtdf** [comment]
> The disadvantage however is that it doesn't display a map preview in the MP lobby.

This sounds like a bug to me that should just be fixed.

**Comment by Pentarctagon** [comment]
What about fixing the bug of the preview not working for `map_file`, and then deprecate `map_data` everywhere?

**Comment by gfgtdf** [comment]
> and then deprecate map_data everywhere?

i disagree here, there are cases where one wants inline data like  `map_data="Gg, ..."` mostly because one for example wants to have it in one file for example when uploading a testcase scenario for bugreports (there are also other usecases for that).

**Comment by jostephd** [comment]
>  SP scenarios or rather campaigns in general (SP & MP) have never a map preview

Even in the Game Load dialog?

**Comment by CelticMinstrel** [comment]
Okay, maybe don't deprecate `map_data`, but I'd suggest at least moving all the campaigns and (once the missing preview bug is fixed) the MP scenarios over to `map_file`.

**Comment by Pentarctagon** [comment]
So it sounds like:
* Don't deprecate anything, given gfgtdf's example.
* The MP map preview not working for `map_file` is a bug that should be fixed.
* Have all of the mainline campaigns and MP scenarios (once the above bug is fixed) use `map_file` instead of `map_data`.

**Comment by jostephd** [comment]
> The MP map preview not working for `map_file` is a bug that should be fixed.

#4407

**Comment by jostephd** [comment]
> * The MP map preview not working for `map_file` is a bug that should be fixed.

Done, #4407 has been merged

> * Have all of the mainline campaigns and MP scenarios (once the above bug is fixed) use `map_file` instead of `map_data`.

This is the only remaining work here, MP scenarios only (@sevu did the SP ones in 6da85e9042014ec0595f9448937c472be9aa8d9c). Retitled/Relabeled accordingly.

**Comment by Pentarctagon** [comment]
So everything in `data/multiplayer/scenarios/`?

**Comment by sevu** [comment]
Feature implemented =)
