### ISSUE TITLE
HttT S16/S17: Li'sar's forces desert her without explanation

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4401]
Li'sar's forces desert her between S16 and S17. There could be some dialog about this, perhaps between Li'sar and one of her units (a General, maybe?) at the end of S16, when the trolls are dead and there's time for the General to persuade Li'sar to renege the hasty alliance. That can set up [the dialog at the start of S22](https://github.com/wesnoth/wesnoth/blob/4f667254c9af792147fa0740e5944d21b7e79095/data/campaigns/Heir_To_The_Throne/scenarios/22_Return_to_Wesnoth.cfg#L237-L256) where Li'sar is called a traitor.

**Comment by Wedge009** [comment]
I've wondered about this too. She has her own troops in S16 but then Li'sar joins Konrad's party and she no longer has the ability to recruit Loyalists (that I can recall, anyway).

**Comment by GregoryLundberg** [comment]
How about a cut scene between S16 and S17 where her troops react to her having cooperated with Konrad, starting by suggesting she turn on him and arrest him while his guard is down, and finally deserting her when she refuses.

This would finally put her in direct conflict with the Queen, leading the the penultimate battle at the end of the campaign. We might want to adjust the later campaigns to add more story about her treason, which would tend to push her and Konrad closer together as the end-game unfolds.

It also could serve as a reason Konrad grows even more opposed to turning on her, as well.

**Comment by jostephd** [comment]
Sounds good to be, but it's not really my area. @nemaara might be able to help here.

**Comment by knyghtmare** [comment]
Was there ever any follow-up to this?

**Comment by knyghtmare** [comment]
Closed in favour of #7501
