### ISSUE TITLE
[1.15] Campaign extra_defines can drop out in some circumstances

### ISSUE THREAD

**Issue by zepko1** [wesnoth/wesnoth#4402]
A message said that I could turn a Necromancer to a Lich, and that I could then advance a Lich to Ancient Lich.
My Liches cannot advance to Ancient Lich when they level up, they just get the normal AMLA.
Only Ardyn-Na could advance.

**Comment by sigurdfdragon** [comment]
@zepko1 I assume you are onS18 Abandoned Outpost
I'm getting this bug, but only for start of scenario saves. If I quit and load an auto-save or do the same thing with a manual save, the level adavancement is available. Does the same happen for you?

Also, in this campaign, leveling a unit to death knight should be an option. I'm finding it is buggy, the same as the ancient lich bug/band-aid fix listed above. Are you getting the same with that as well?

**Comment by sigurdfdragon** [comment]
Also, if I add a space after the comma for the extra_defines in SotA's _main.cfg, they both work for Start of Scenario saves as well.

**Comment by zepko1** [comment]
@sigurdfdragon Yes, I'm talking about S18, but also the next scenarios.
I made some more tests. I have to say that it further confused me, since I cannot reliably reproduce the issue. 
The problem arises some times if I load the start of scenario save, but sometimes it does not. I didn't observe the problem if I load an autosave instead.

Regarding the death knight advancement, during the campaign I was able to do it without problems, so I didn't find any issues there.

**Comment by gfgtdf** [comment]
do you ahv debug mode enabled? if yes do you also get this problem when you don't have debug mode enabled when the game is loaded?

**Comment by zepko1** [comment]
When I first encountered the problem I was playing the campaign normally, so debug mode disabled. In that case: Lich->Ancient Lich: no, Revenant->Death knight: yes.

Then when I made a few tests in debug mode to put my lich close to advancement, then I tried to have them advance both with debug mode enabled and disabled. I still can't figure out a pattern about when the problem happens.

**Comment by sigurdfdragon** [comment]
When starting a fresh campaign with a cleared cache, using debug to jump from S1 to S17, I get the bug on both  Lich->Ancient Lich (with Ras-Tabin character) & Revenant->Death Knight. (with a recruited one) Also, the level paths are missing from help: unit descriptions.

When I save that game, quit Wesnoth, and then restart and load that save (either without debug, or having debug on when launching Wesnoth), Ras-Tabin now has the ability to level to Ancient Lich, but the previously recruited Skeleton/Revenant does not, but new skeleton/revenants & Liches do. Also, both level paths show up in the help: unit descriptions.

**Comment by zepko1** [comment]
@sigurdfdragon I can confirm this behavior.

**Comment by sigurdfdragon** [comment]
If I start SotA and use debug to go S17, then transition normally to S18 , I get the error.
If I start SotA and use debug to go straight to S18, I don't.
Haven't been able to figure out what the difference is yet.

@gfgtdf @Pentarctagon : Anything that you've seen in fix/modify_unit_type changes that might be involved in this?

**Comment by Pentarctagon** [comment]
I just renamed the tag, so if it's not related to that, there's not much I can really add.

**Comment by sigurdfdragon** [comment]
I can reproduce this with LoW & SoF with their extra_define for the Dwarvish Runesmith. For LoW, the runesmith advancement is available in the first scenario, but when jumping with debug to the second scenario, the advancement drops out.
For SoF, it's the third scenario
With SotA the drop out doesn't occur until the 3rd scenario with debug switching.

The pattern that causes the extra_defines to drop appears to be **not having unit manipulation involving a filter in the scenario prestart.** For SotA S02, [hide_unit] seems sufficient to allow the define to continue. in S03 there is none, and the define is dropped.  If you skip S03 and go straight to S04, the freeze_unit object keeps the define working. Also dropped when going through S06 (recall insufficient) S17 (prestart only has unit placement.)

Also note there is no prestart unit manipulation in LoW S02

Once the extra_define is dropped, it does not come back unless you save the game, quit to desktop, then reloading it brings it back. Passing through another scenario without prestart unit manipulation causes it to drop again.

**Comment by ProditorMagnus** [comment]
1.15 should use modify_unit_type/unit_type_fix instead.

**Comment by sigurdfdragon** [comment]
> 1.15 should use modify_unit_type/unit_type_fix instead.

Do you mean that the extra defines are deprecated?

**Comment by ProditorMagnus** [comment]
I think they should be before 1.16 at least. #3955

**Comment by sigurdfdragon** [comment]
Tested today on current master with a clear cache. The Enables for SotA (Death Knight, Ancient Lich) & SoF (Dwarvish Runesmith) are not working in the opening scenarios for each campaign. Tested by creating units in debug.

**Comment by gfgtdf** [comment]
> Tested today on current master with a clear cache. The Enables for SotA (Death Knight, Ancient Lich) & SoF (Dwarvish Runesmith) are not working in the opening scenarios for each campaign. Tested by creating units in debug.

did you reload an old savefile?

**Comment by sigurdfdragon** [comment]
No, my recent tests were just with starting the campaign from scratch.
Just tried opening a SotA S21 start of scenario save as well made back in Feburary and the Ancient Lich advancement was lost there as well, with a lich on the recall with no advancement and 163/150 xp

**Comment by Wedge009** [comment]
I recently - in 1.16.1 release - played SotA normally with no debug mode and by the end of the campaign I had several Ancient Liches, both main characters as well as generic units. I also tested 1.17.0+dev (02cdde963b0) with a new campaign, debug-switch to S17 and proceed to S18 normally, and didn't find this issue with Lich->Ancient Lich advancement.

Given the age of the report, I think it's safe to close, but please re-open if anyone else finds it's still a problem.
