### ISSUE TITLE
[1.15] Secrets of the Ancients - Cutscenes behave incorrectly

### ISSUE THREAD

**Issue by zepko1** [wesnoth/wesnoth#4403]
Cutscenes in SotA behave weirdly. I just see the starting of the scene, then everything goes dark and I can only advance through dialogues by pressing the right arrow to show the dialogue, then space or enter to dismiss it, then right arrow to show the next one...

I attach the starting save for the first cutscene "Meeting of the Minds".
[SotA-Meeting of the Minds.gz](https://github.com/wesnoth/wesnoth/files/3667386/SotA-Meeting.of.the.Minds.gz)

**Comment by sigurdfdragon** [comment]
@zepko1 For this and 4402, you are using the 1.15.1 release? Also, where did you get it from? steam or sourceforge? (yes, there's a difference depending on where, & this issue might be related to https://github.com/wesnoth/wesnoth/issues/4245)

**Comment by zepko1** [comment]
@sigurdfdragon Yes, I'm using 1.15.1. Got it form sourceforge.
Indeed, #4245 looks like the same issue I am experiencing here.

I'm on macOS Mojave 10.14.6, if this matters.

**Comment by Wedge009** [comment]
It sounds like you're using SDL 2.0.10 (you can check via the i icon in the bottom-left of the title screen). This was resolved just after 1.15.1 was built. Please confirm which SDL version you're using.

**Comment by zepko1** [comment]
I can confirm I am using SDL 2.0.10.

**Comment by Wedge009** [comment]
Thanks, this has been resolved already. You have a number of options to work around this for 1.15 release:
- Use SDL older than 2.0.10 (that's still 2.0.x, obviously).
- Recompile the game yourself, if you know how to.
- Use the beta version distributed from Steam (which I understand uses older SDL for all OS including macOS)
- Or if none of those are possible for you, you'll just have to wait till the next 1.15 release or revert to 1.14. Sorry for the inconvenience.

**Comment by zepko1** [comment]
Perfect, thanks. Good to know it has already been solved.
