### ISSUE TITLE
Damage calculations dialog should show "×2 (charge)" for the defender too

### ISSUE THREAD

**Issue by YellowKingValley** [wesnoth/wesnoth#4408]
The Rise of Wesnoth. Horseman has -30% impact resistance instead of +30%. Occurs in other campaigns as well.

The Battle for Wesnoth version 1.14.9 (9eba78f-Modified)
Running on Microsoft Windows 10 (10.0.18362)

**Comment by soliton-** [comment]
Can you show what modifications you have applied to 1.14.9?

**Comment by YellowKingValley** [comment]
I just installed the game through Steam recently. Happened even before I installed any addons. I am not sure where I can find the modifications I have applied. Hope these info helps. Should I uninstall all addons and try again?

The Battle for Wesnoth version 1.14.9 (9eba78f-Modified)
Running on Microsoft Windows 10 (10.0.18362)

Game paths
==========

Data dir:        D:\Program Files (x86)\Steam\steamapps\common\wesnoth
User config dir: C:\Users\USER\Documents\My Games\Wesnoth1.14
User data dir:   C:\Users\USER\Documents\My Games\Wesnoth1.14
Saves dir:       C:\Users\USER\Documents\My Games\Wesnoth1.14\saves
Add-ons dir:     C:\Users\USER\Documents\My Games\Wesnoth1.14\data\add-ons
Cache dir:       C:\Users\USER\Documents\My Games\Wesnoth1.14\cache

Libraries
=========

Boost:             1.66
OpenSSL/libcrypto: 1.1.0f (runtime 1.1.0f)
Cairo:             1.10.2 (runtime 1.10.2)
Pango:             1.30.1 (runtime 1.30.1)
SDL:               2.0.8  (runtime 2.0.8)
SDL_image:         2.0.3  (runtime 2.0.3)
SDL_mixer:         2.0.2  (runtime 2.0.2)
SDL_ttf:           2.0.14 (runtime 2.0.14)

Features
========

JPG screenshots:                yes
Lua console completion:         yes
Legacy bidirectional rendering: no
Win32 notifications back end:   yes

**Comment by YellowKingValley** [comment]
![Capture](https://user-images.githubusercontent.com/55989520/65960124-54256c00-e486-11e9-809d-429226e7fc4d.PNG)

**Comment by Wedge009** [comment]
I did a quick check of an Iron Mauler (impact) against Horseman and the damage is reduced from 25 to 18, which is 30% impact resistance after rounding.

**Comment by soliton-** [comment]
Ah, a vulnerability of 0.7 means it's actually a 30% resistance.

**Comment by Wedge009** [comment]
That Damage Calculations image above shows the defender with 30% resistance.

**Comment by YellowKingValley** [comment]
6 x 0.7 x 1.25 = 5.25

6 / 0.7 x 1.25 = 10.71 ~ 11

**Comment by Wedge009** [comment]
Hmm, so the Total Damage figure appears incorrect.

**Comment by YellowKingValley** [comment]
Ugh my bad. False alarm then. Sorry and thanks.

**Comment by Wedge009** [comment]
No worries. I was thinking maybe the Charge modifier should be on the Defender side as well, to make this clear.

**Comment by jostephd** [comment]
@YellowKingValley, in the future, please share not only your conclusions but also the observations you based those conclusions on.

I will add that there _is_ a bug in that dialog: "×2 (charge)" should be shown in the defender side of the dialog as well. However, that bug is already fixed in master:

![2019-10-01-122002_1920x1080_scrot](https://user-images.githubusercontent.com/24784687/65961342-e2c5c900-e445-11e9-89ca-bf4e14d360e2.png)

And for reference, that screenshot is Horseman v. strong Thug at night.

**Comment by Wedge009** [comment]
Didn't know it was added in master. Good that it's already done. (:

**Comment by jostephd** [comment]
It should be done in 1.14 too, though.

**Comment by jostephd** [comment]
I think it might have been fixed here, as part of a larger patch:

https://github.com/wesnoth/wesnoth/commit/ebb980a45e7cc94376a7d008038a465627983f66#diff-95ed73f0bfc3aa6b8db7c0e357cca851

This change is similar:

https://github.com/wesnoth/wesnoth/commit/47dd4eb3771598646f8c0ece4fc11c3b11bd22d1#diff-95ed73f0bfc3aa6b8db7c0e357cca851

**Comment by Wedge009** [comment]
I was looking for that... how to only pull out the Charge addition?

**Comment by jostephd** [comment]
I think what's needed here is basically to port the changes to attack_predictions::set_data, and then to port those "add a parameter" changes until it compiles. It might be easier to do it the other way, to backport the entire patch _except_ for the changelog and unit::ability_affects_weapon changes.

**Comment by Wedge009** [comment]
Maybe @newfrenchy83 and/or @CelticMinstrel can comment on what they feel is the best approach for this one.

**Comment by CelticMinstrel** [comment]
Not 100% sure, but my initial suspicion would be that the key lies in the addition of `opp_ctx`. I'm not sure whether the added parameters to `damage_from` and `under_leadership` are required; they might be?

**Comment by Wedge009** [comment]
I had a go at trying to merge those filter changes into 1.14 but ran into conflicts and didn't really understand what the changes are doing so I've left this for now.

**Comment by Wedge009** [comment]
No more releases are planned for 1.14 and 1.16 release is imminent.
