### ISSUE TITLE
Backport: fix [modify_side] controller=ai for the current side

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4430]
@gfgtdf Took the liberty of creating this for you :)

873752943f6a43b9a675404c689169e3407ef162

**Comment by gfgtdf** [comment]
if we are already at it i should consider backporting 

https://github.com/wesnoth/wesnoth/commit/cad013c4dec7f93359785638ec55da95a4808f0c

and


https://github.com/wesnoth/wesnoth/commit/c4ffade49aa4efc2a410e031539a791c005c3b30

**Comment by soliton-** [comment]
Would be nice if you can backport the server change soon since a restart for other fixes is planned.

**Comment by gfgtdf** [comment]
done
