### ISSUE TITLE
Expand [special_note] support

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#4434]
Currently, the `[special_note]` tag is only supported in units and unit types. However, the vast majority of special notes relate to specific abilities or weapon specials, so it would be useful to support placing the special note in the actual definition of the abilities and specials.

Special notes should ideally be supported in the following places:

* [ ] In unit ability tags (any tag nested in `[abilities]`).
* [ ] In weapon special ability tags (any tag nested in `[specials]`).
* [ ] In movement type definitions (the `[movetype]` tag).

**Comment by CelticMinstrel** [comment]
Side note - the standard heals ability is currently a direct combination of two other abilities (cures and extra heals), so that might require some special preprocessor work in order to have two special notes for the individual abilities but a different one for the combination.

**Comment by stevecotton** [comment]
Implemented in #5811.
