### ISSUE TITLE
Statistics dialog shows end scenario stats

### ISSUE THREAD

**Issue by slavrenyuk** [wesnoth/wesnoth#4441]
I found this multiplayer replay that shows end scenario statistics at the beginning of the replay. The workaround is to press "reset to beginning" button. Unfortunately I don't know the OS of the user. Replay is shown to be recorder on Wesnoth 1.14.9

Replay file:
[stats_bug.gz](https://github.com/wesnoth/wesnoth/files/3709008/stats_bug.gz)

**Comment by soliton-** [comment]
Is it perhaps the same as https://github.com/wesnoth/wesnoth/issues/4133?

**Comment by slavrenyuk** [comment]
@soliton- it looks similar. @jostephd please take a look. By the way, I noticed that stats at the beginning are not actually the same as at the end. Also there were several server messages about the new host. Perhaps the initial host has disconnected at some point and that is what messed up the stats.

**Comment by slavrenyuk** [comment]
It looks like a different use case comparing to #4133 , because the replay file was saved after the leader was killed (which is `mid_scenario=no` I suppose)

**Comment by jostephd** [comment]
@slavrenyuk Your replay has `mid_scenario=yes`, and if I change that to `no`, the replay starts out with all-zero statistics and two entries, just as in #4133. Looks like a duplicate to me.

I assume leader death and even linger mode are still mid_scenario=no, and only "move to the next scenario" (as in a campaign) creates mid_scenario=yes.

**Comment by gfgtdf** [comment]
i think only start-of-scenario saves are supposed to have `mid_scenario=no` that 'end of scenario replays' have `mid_scenario=no` is a bug,

**Comment by CelticMinstrel** [comment]
Apparently fixed in #7585 / 01f28b1.
