### ISSUE TITLE
Issues in TSG Into the Depths

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4452]
(scenario 6a in 1.15, 7a in 1.14)

- [x] Overlays:
To my knowledge, the convention is:
 - yellow crown for leaders
 - silver crown for (loyal?) units who cause you to lose the scenario
 - bronze marker for loyal units

 Hylas + Gerrick should lose the silver crown then, likewise Afalas in 7b
 (Maybe it even worked like that and I just broke it – in any case, the code needs changes to not directly edit the `overlay=` key)

- [x] Recruit:
Troll Leader can recruit Bowmen. This can be solved by switching from [side]recruit to [unit]extra_recruit. Maybe it's best to use that for the whole campaign

- [ ] Something goes wrong here:
![glitch](https://user-images.githubusercontent.com/21158813/66703049-92d0e700-ed0e-11e9-9a76-70f188a8d9aa.png)

**Comment by nemaara** [comment]
Troll leader isn't supposed to be able to recruit. I forgot to fix that before. Also fixed the overlays. See https://github.com/wesnoth/wesnoth/compare/fdf1785bf56e...1f4e18548130.

I don't encounter anything that goes wrong during that event, can you explain it more?
