### ISSUE TITLE
Regression with terrain graphics

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4453]
That's hex 2,14 in the last scenario of The South Guard path A.
Terrain transitions exist in 1.14, are missing in master. Terrain overlay is `^Uf` in both.
![y](https://user-images.githubusercontent.com/21158813/66703455-1ab8f000-ed13-11e9-8768-46bc62ce90c5.png)

**Comment by jostephd** [comment]
Bisected to d9cebd634e80a877db366645ea8094535588360b. @CelticMinstrel that's your commit.

**Comment by CelticMinstrel** [comment]
That was obvious to me without a bisect... though I might not have noticed this issue with out it.

Guessing it has something to do with the `{NEW:DISABLE_TRANSITION` lines added in the commit, but I'm not sure what exactly those do or how to fix it...

**Comment by jostephd** [comment]
I don't know either, I'm afraid, but as it's your commit, please do look into it. Ask if you need help.

**Comment by CelticMinstrel** [comment]
I have a feeling that the second parameter of the `DISABLE_TRANSITION` should be `Tb` rather than the overlay terrains... are there issues placing `Tb` next to road or hills or cave?

**Comment by jostephd** [comment]
Does this look right?

![2019-10-16-021452_320x378_scrot](https://user-images.githubusercontent.com/24784687/66882640-c0da5380-efba-11e9-997e-e92cacc8d835.png)

If you ask me, the transition to flat/hills is a bit sharp, but I don't know if that's an issue with the assets or with the cfg.

**Comment by jostephd** [comment]
Let's do that, but in any case, I think the Uf issues, where it actually shows a hexagon with no transition whatsoever, are the more pressing concern here.

**Comment by doofus-01** [comment]
I recall there could be issues with three-terrain corners, though I don't quite remember details off the top of my head.  I think it's because none of them are using two-sided transitions (-s-sw.png), just one-sided (-s.png or -sw.png).
Or maybe it's something else.  I should be able to look at it more this weekend, if it's still an issue.

**Comment by jostephd** [comment]
@CelticMinstrel Any progress on the issue in the OP?

**Comment by CelticMinstrel** [comment]
I really don't know. I may have been the one who committed the mushroom terrain, but @doofus-01 did most of the work, I mostly just modified it to the new terrain codes. Does removing the `DISABLE_TRANSITION` lines fix it while not introducing other issues? If not, I think I'd recommend talking to someone who knows the terrain system better…

**Comment by doofus-01** [comment]
I'll look at it, once I get on the 1.15 wagon.  It's probably trivial once you figure it out.  Give me a few weeks to get up to speed.
