### ISSUE TITLE
Defense caps and unit balancing for new mushroom terrains

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4454]
Consider adding mushroom defense cap to horseman, cavalryman and their advancements similar to the forest cap which they already have.

_Originally posted by @slavrenyuk in https://github.com/wesnoth/wesnoth/issues/4213#issuecomment-520257354_

Discussion thread in the forums:
https://r.wesnoth.org/t50936

**Comment by cooljeanius** [comment]
Whether or not this happens could change the calculus of the ongoing debate over if/how we want `wmllint` to handle changes to the mushroom terrain
