### ISSUE TITLE
Add a help page for gold/silver crowns and loyal marker

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4455]
To my knowledge, the convention is: 
* yellow crown for leaders 
* silver crown for (loyal?) units who cause you to lose the scenario
* bronze marker for loyal units

__the above originally posted by @sevu in #4452__

We shouldn't need to say "to an experienced dev's knowledge", we should have a page in the help's Gameplay section, as we do with "Orbs" and the hp/experience colouring.

**Comment by jostephd** [comment]
What about ellipses? What does it means when a unit has the seven-pointed star ellipse? And what's the distinction between the two kinds of seven-pointed star ellipses?

![2019-10-12-213248_130x124_scrot](https://user-images.githubusercontent.com/24784687/66707919-d9870700-ed37-11e9-82d7-774eb83f831c.png)

(That's _Blackwater Port_ after `:unit type=Fog Clearer` on Konrad and Delfador. Ignore the orb colors.)

**Comment by stevecotton** [comment]
Added to the roadmap for 1.15.6.

**Comment by stevecotton** [comment]
Currently blocked by PR #5180. I want to add this to the same help page as the orbs, and am waiting for that PR's revision of the orbs page to merge.

**Comment by CelticMinstrel** [comment]
This can be closed, right?
