### ISSUE TITLE
Music fade-in/fade-out blocks the UI

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesnoth#4460]
Any instance of background music fade-in or fade-out across the board blocks the game UI. This is because we use SDL_mixer's functions for fading music in or out, and they are designed to not return until the fade-in/fade-out is complete.

This is very much a non-trivial issue to fix at the moment. Even if we were to use a separate thread for controlling the music volume on our own, I don't think calling SDL_mixer's functions from a thread other than the main thread is a safe operation. SDL_mixer was intended as a tech demo first and foremost, and its documentation doesn't state anything about thread safety guarantees so presumably there are none (although admittedly they probably depend **mostly** on any guarantees made by the SDL functions they wrap).

One way to go about it would be to implement music fade-in/fade-out at our end by making event loops aware of the music engine's need to perform such operations. This would allow us to keep using SDL_mixer in a perfectly thread-safe fashion.

Another way would be to use a different solution for audio than SDL_mixer that does provide the ability to perform non-blocking fade-in/fade-out, but if that were to be considered then hopefully it would be one that would also provide us with additional benefits like sound filters to make up for the time invested into that solution.

**Comment by mesilliac** [comment]
Well, i fixed this as it was destroying the new visual fade effect i implemented... fixed in #6855 .

SDL_Mixer isn't following what its API docs say, but i got it to do everything without blocking.
