### ISSUE TITLE
End Unit Turn (spacebar) can jam the tutorial before the user makes a move

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4466]
### Game and System Information
1.14 and master (latest from Git in each branch), on Debian Linux

### Bug and reproduction:

1. Start the tutorial, which suggests using the spacebar to dismiss messages
2. Get to the "Click on Konrad" step, and click on him
3. Press the spacebar one time too many (so dismissing the message and then doing an End Unit Turn)

At this point, the game map and units are unresponsive to the left mouse button. It seems the only way to make the next move is either:
* a right-mouse click
* space, n

**Comment by Wedge009** [comment]
I only confirmed this by pressing space slowly - if I press repeatedly it just alternates between move ended and move available. I suppose it's possible for a new player to use space mistakenly and then not realise what button he/she pressed and so get stuck like this. I suppose would have to disable end moves in the Tutorial at least for the first scenario (if that's possible in the WML).

**Comment by stevecotton** [comment]
Pressing space another time toggles the orb back to green, but it's still in a state where the left mouse button doesn't make a move - it still needs the user to either press 'n' or right-click.

**Comment by jostephd** [comment]
The `End Turn` button is clickable, but when you click it, it just says you haven't finished the tutorial on movement. It would be nice if it repeated the last instruction for you.

Though that doesn't address preventing the user from doing 'End Unit Turn' on Konrad. :thinking: Could the `select` event help here?

**Comment by Wedge009** [comment]
Oh right, yes, cannot move again until `n`.
