### ISSUE TITLE
Backport #4444

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4469]
Backport #4444, commits: 

$ git log --oneline 6b77280c28f4993d2c7c04cbc1250d6f6c5804ac..70a2046f8f7f4c60e96245319d03b9aad4a40ec5
70a2046f8f7 Add #4444 to changelog
129e53b660f unit_recruit: Pass the error strings as t_string
69f7ba660c1 unit_recruit: Edit comments
9fdeebfa0e9 unit_recruit: Rename variable
c7adc3ad9f6 unit_recruit: Move the planning mode gold computation out of the dialog
1fbf9d93561 unit_recruit: Gray out units that would not be able to be recruited
b3e04ba54de unit_recruit: Minor refactoring
eaf67247400 recruit: Add menu_handler::can_recruit that returns a reason
534549daa37 recruit: Show a transient message if repeating a recruit failed

**Comment by jostephd** [comment]
cb07373251484289fcc5a4ded634275a5535ddc2 c9ba3ee18f4415ee4cab3e49baa4d37fc58755e7 need to be backported first to prevent conflicts. And then #4362 might as well be backported too...

**Comment by Wedge009** [comment]
Shall I have a go at this or do you think it will be significantly harder to resolve conflicts than for #4492?

**Comment by jostephd** [comment]
Thanks for looking into this. I _think_ it will merge without conflicts once the right set of commits to backport is found. That'll require something like `git log --reverse --oneline 1.13.12..origin/master .../unit_recruit.cpp .../unit_recall.cpp` (and add to the command line any other files that commit series modified). Maybe it's just necessary to backport all of #4362 and all of #4444? I haven't tried that yet.

**Comment by Wedge009** [comment]
Closed via #4563.
