### ISSUE TITLE
1.14 cve test is failing on Windows

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4471]
AppVeyor builds on 1.14 are failing like this:
`WML_tests.cmd : error WML1: Test 'cve_2018_1999023' returned 1, expected 0 [C:\projects\wesnoth\projectfiles\VC12\wesnoth.vcxproj]`.
This is happening since #4449's 94698fb4eb4083d4ef6e68b4cbf742102ec3b2b7, although it's not obvious how that is related to the error.

A separate error, `Error sending Webhook notification: Error calling webhook http://ai0867.net:6661/wesnoth: An error occurred while sending the request.` doesn't make the build count as failed, it was already happening on the preceding AppVeyor build.

**Comment by jyrkive** [comment]
WML tests have strict logging enabled, i.e. they fail if they log a warning or error to the console.

Thus, the most likely possibility is that the test calls a deprecated API somewhere.

**Comment by stevecotton** [comment]
Ah, a793bce disabled it for non-Windows builds. Windows builds have their own run_wml_tests:
https://github.com/wesnoth/wesnoth/blob/1.14/projectfiles/VC12/WML_tests.cmd
https://github.com/wesnoth/wesnoth/blob/1.14/projectfiles/VC16/WML_tests.cmd

My preference would be to backport #4599, and have this test return the new status instead of needing to disable strict mode.

This also connects with https://github.com/wesnoth/wesnoth/issues/4646#issuecomment-566147399 - one of my two hesitations for backporting the Python3 version of run_wml_tests was that it would need this special handling for the cve test. The other reason is that it would add a build-dep on Python3, but that seems a trivial issue.

**Comment by Pentarctagon** [comment]
On (most) linux distros it'd be a non-issue since python3 comes installed by default, and on macOS I think(?) it does as well.  For Windows it would mean people need to install python3, though my guess would be that very few people on Windows run the WML unit tests locally anyway.

A bunch of the other tools also already depend on python3, so it wouldn't really be an entirely brand new dependency either.

**Comment by stevecotton** [comment]
Fixed by #4666.
