### ISSUE TITLE
poedit warnings for translatable strings "HINT^ line starting with space"

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4480]
Poedit does some sanity checks, and warns in the UI if the original and translation differ in:
* starting with whitespace
* ending with whitespace
* ending with a `.`

The new special notes all trigger warnings, because `SPECIAL_NOTE^ This unit is able to move through solid stone walls.`, etc should be translated starting with a space. Poedit doesn't know about Wesnoth's hinting method.

**Comment by jostephd** [comment]
We should change the special note strings so they don't start with spaces.

We should also not use leading spaces in translated strings. Some translations didn't keep the leading space where the English string had one.

**Comment by stevecotton** [comment]
What about strings that start with newlines? If it needs a change, I'd like to update #4414's new documentation before the translators work on it.

**Comment by jostephd** [comment]
I think the best form would be to have neither leading whitespace nor trailing whitespace (where by "whitespace" I mean spaces, tabs, newlines, etc) in translated strings. Making the change only for strings that haven't been processed by a pot-update sounds like a good idea.

**Comment by stevecotton** [comment]
Logged #4484, "pot-update broken by #4414's editor documentation", although I'm hoping @AncientLich will take it as a feature-request for wmlxgettext.

**Comment by Wedge009** [comment]
With respect to poedit's checks, they are useful, but Wesnoth's conventions do indeed often cause false alerts on these.

#4305 predates this report and seems to resolve the issues around those checks - is there still more work to do on this, for Special Notes or other things?

**Comment by stevecotton** [comment]
There's exactly two left, according to a search of the .pot files for anything that has a caret followed by whitespace. It's just a co-incidence that both are special notes.

* UtBS's `SPECIAL_NOTE^ Unlike normal Shadows, Ethereal Shadows cannot hide at night.`
* The Silver Mage's special note, which is already fixed on master and in the list for backporting (#5979)

Expect a new PR to referencing this issue soon.

**Comment by Wedge009** [comment]
Hooray, thanks.
