### ISSUE TITLE
Backport #4477 - custom special notes for some units

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4488]
### Describe the bug
Backport #4477 to 1.14

### Additional context
The [special_note] tag does not exist in 1.14. Instead, the special notes should be appended to the `description` string. They should probably be added _as a new string_, using `_"foo" + _"bar"`, for translators' benefit.

**Comment by Wedge009** [comment]
Closed with 12ddac89. I checked each one thoroughly but please let me know if I made a mistake. I kept the leading spaces out of the translation strings because we definitely don't want those in there.

**Comment by jostephd** [comment]
Looks good to me, thanks!

By the way, I'm not sure if there are other units that would benefit from such changes. I wrote #4477 from memory; I didn't audit the entire mainline unit set for any unit that has a different movetype than a unit it advances from.

**Comment by Wedge009** [comment]
That may be a separate task to review the unit descriptions at a global level.
