### ISSUE TITLE
update-po4a broken

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4490]
Running `scons update-po4a` stops with an error because of malformed xml in the pt_BR manual, which is missing the `>` on the end of `</emphasis>`:
https://github.com/wesnoth/wesnoth/blob/8becb29fad074908efdeaec34af768096cd139c2/po/wesnoth-manual/pt_BR.po#L4786-L4787

**Comment by jostephd** [comment]
Fixed that instance in 6b15d6847a0294216cba299442b18f2d8ae99dfa.

**Comment by jostephd** [comment]
Marking blocker since this step is in https://wiki.wesnoth.org/ReleasingWesnoth#General_maintenance

**Comment by Wedge009** [comment]
If the syntax is resolved, what's left to do? Re-run update-po4a?

**Comment by jostephd** [comment]
Yes. I ran it myself to check but it failed with unrelated errors, so I left the issue open.
