### ISSUE TITLE
Backports to 1.14.10

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4492]
- [ ] d1a72cafffa EI: Fix the "Northlands" fix
- [ ] 437ff89ab18 HttT S18: Fix "noble merfolk".
- [ ] 4a1d71b5ec5 EI: Typo fix
- [ ] 1017018e442 fixup! Fixes from SpellingMistakes
- [ ] 87e3e8f9cf2 HttT: Typo fixes
- [ ] 74589a642c1 Fixes from SpellingMistakes

**Comment by Wedge009** [comment]
Is this delayed because of a string freeze?

**Comment by jostephd** [comment]
No, there's no string freeze in place, they just conflict and I didn't have time to sort that out yesterday.

**Comment by Wedge009** [comment]
I did these with 74562e29..8c5f187b. Re-open if I got anything wrong.

**Comment by jostephd** [comment]
Thanks! Reviewed, looks good.
