### ISSUE TITLE
Reinstate deprecated macros at level 4

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4493]
The following commits removed macros deprecated at level 3. Those macros should be restored as no-op macros deprecated at level 4 (see https://wiki.wesnoth.org/CompatibilityStandards#Post-removal):

- [ ] 871e857771ed08abafa78be9072656444cf24876
- [ ] 92c7d2fed0bebed20855e4ad3bdaf911521cd8d7
- [ ] a766d2d93a57ca99cc582935b9b325a01648dffb
- [ ] 021339bcc58a347f28607315d9d5fe94546dcba8

**Comment by CelticMinstrel** [comment]
Oh, I thought this would be a blocker for the current release, but I guess not, huh?

**Comment by jostephd** [comment]
They were deprecated at level 2 or 3 for removal in 1.15, and it's a development release anyway so I figured we'd just fix it in 1.15.3.

**Comment by jostephd** [comment]
See IRC just now

**Comment by CelticMinstrel** [comment]
So um, what's going on here then? I missed the IRC and don't want to hunt for it...

**Comment by Vultraz** [comment]
>>> They were already removed and were slated for removal in 1.15.x so there's no point in restoring them
Instead of worrying about API stuff it would be great if people invested that energy into things that concern actual players
e.g. #2710
