### ISSUE TITLE
add [filter] to [advancement]

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4495]
I think it might be useful to have a [filter] tag in [advancement], so that the [advancement] is only available if the unit matches the [filter], this is effectively more flexible than the current require_amla/exclude_amla: one could just have other advancements keep track of them via varibale-set effect, and then us the filter to have for example a 'available of the unit has already exactly two of the following advancements' filter.

Of course this can already be implemented via pre_advance events and setting the list fo possible amlas in pre_advance events, so not sure whether its really needed, still it think it might be a good idea

**Comment by stevecotton** [comment]
Reminder: this needs documentation in the Wiki.

(I'm doing some housekeeping on changelog.md, seeing which Git commits need documentation)
