### ISSUE TITLE
AoH Northerners can't recruit. 

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#4501]
### Game and System Information
 - 1.15.2
 - Steam
 - Windows 10

### Describe the bug
AoH Northerners can't recruit. 

### Expected behavior
Menu with units should show up.

### Additional context
I already checked unit ids I might missed something but I think they are fine.

**Comment by Wedge009** [comment]
What's AoH? Maybe I'm being forgetful but that doesn't sound like a main-line campaign.

**Comment by Wedge009** [comment]
Okay, I think AoH is supposed to mean Age of Heroes, which is something to do with MP, not main-line campaigns.

**Comment by CelticMinstrel** [comment]
Yes, AoH is the Age of Heroes era.

**Comment by Pentarctagon** [comment]
It works as expected for me on linux.

@Hejnewar Could you check if there's anything in Wesnoth's error log?

**Comment by Wedge009** [comment]
Closing due to lack of information. Re-open if it comes.
