### ISSUE TITLE
Secret of the Ancients S1: Gaining Human Corpses on Ardonna's Death

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#4503]
### Game and System Information
 - 1.15.2+dev Windows

### Describe the bug
Only occurs on master, presumably this will occur any time until Ardonna properly gains the ability to recruit human corpses, but it's easiest just to replicate this on S1.

### To reproduce
1. Start Secret of the Ancients, any difficulty.
2. Debug-kill Ardonna (or play normally and let her die).
3. She will give her death cry, and then the message 'You can now raise human corpses!' appears. Presumably because she is human and she died...

### Expected behaviour
In contrast, doing this on 1.14 branch gives the expected behaviour of death cry then game over.

### Additional context
It appears this is introduced with:
https://github.com/wesnoth/wesnoth/blob/81fcc2ef301750124d0c1c51cf4cdad65f8e8a78/data/campaigns/Secrets_of_the_Ancients/scenarios/01_Slipping_Away.cfg#L112

...which calls:
https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Secrets_of_the_Ancients/utils/zombie-utils.cfg

**Comment by Wedge009** [comment]
@sigurdfdragon Are you maintaining SotA, or do you know who is?

**Comment by Wedge009** [comment]
I should add that this bug is present in 1.15.1 release.

**Comment by sigurdfdragon** [comment]
@Wedge009 Yes

**Comment by sigurdfdragon** [comment]
@Wedge009 Thanks for the report

**Comment by Wedge009** [comment]
Works for me, thank you!
