### ISSUE TITLE
Legend of Wesmere: Missing Help entry for Aged trait

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#4506]
### Game and System Information
1.14.9 release and 1.15.1 release (on Windows 7, but not OS-specific)

### Describe the bug
I'm sure I've seen Aged trait in more than one place but looking at Legend of Wesmere specifically for the purposes of the instructions below.

### To reproduce
1. Start Legend of Wesmere campaign
2. Click the ally leader to the west (Velon at 5,15)
3. Note his traits in the side-bar: aged and intelligent
4. Clicking intelligent goes to the Intelligent Help entry
5. Clicking aged opens Help but only at an empty page

### Expected behaviour
Either clicking aged opens the Aged trait Help page or does not do anything.

**Comment by UnwiseOwl** [comment]
Works fine for me on both 14.9 and 15.2 on windows 10.

**Comment by Wedge009** [comment]
Thanks for taking the time to check this. I just had a look at the 1.14.11 release and it's still missing. Have you run your installation for very long? I'm wondering if there's an aged entry from another campaign, perhaps.

What does the Aged entry say? I just don't see one at all.

**Comment by UnwiseOwl** [comment]
I have a relatively fresh install on this machine since the last one died. 

"Units with the _aged_ trait have 8 fewer hit points and suffer from a 1 point decrease in movement and melee damage"

**Comment by Wedge009** [comment]
Hmm, I see `TRAIT_AGED` declared in `traits.cfg`
https://github.com/wesnoth/wesnoth/blob/2f22de2636755e22c12edeb90f987114922a90e7/data/core/macros/traits.cfg#L355-L376

It is used for unit Velon in the first Legend of Wesmere scenario, as well as for Methor, Delfador's mentor, in the opening scenarios of Delfador's Memoirs. In all cases I get a blank Help page, and I tested different languages too, including the default en_US. I note the following message in stderr:

> Help browser tried to show topic with id 'traits_aged' but that topic could not be found.

This comes from `help_browser::show_topic()`:
https://github.com/wesnoth/wesnoth/blob/2f22de2636755e22c12edeb90f987114922a90e7/src/help/help_browser.cpp#L207-L219

So apparently `find_topic()` isn't working for my particular set-up (whether 1.14.11 release or 1.14/master development build), but at this point I can't see why it doesn't work for me yet it seems to work for you.

**Comment by stevecotton** [comment]
Fixed for 1.15 in #5123, and the explanation of why aged works sometimes is in https://github.com/wesnoth/wesnoth/issues/1935#issuecomment-327988495 .

Maybe it should be backported, at the moment I'm not backporting simply being I think it's low priority.

**Comment by Wedge009** [comment]
Thank you @stevecotton. I confirm the work-around functions as expected and resolves this issue.

I also back-ported it to 1.14 branch since I think it's reasonable enough to include it there.
