### ISSUE TITLE
SDL 2.0.9 breaks title-screen full-screen toggle

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#4508]
### Game and System Information
master and 1.14 on Windows 7

### Describe the bug
Toggling between full-screen and window is broken with SDL 2.0.9 and 2.0.10, but seems okay with SDL 2.0.8.

### To Reproduce
1. Run Wesnoth with SDL 2.0.9 or 2.0.10 (current at time of writing)
2. Press Ctrl+F, default hot-key for toggling between full-screen and window display
3. Title screen does not re-size properly with the window.

### Expected behaviour
Same behaviour as for SDL 2.0.8

### Screenshots
After switching from full-screen (2560x1440) to window:
![broken](https://user-images.githubusercontent.com/13679322/67304555-be8a7300-f53f-11e9-875e-d98c68201264.jpg)

**Comment by sevu** [comment]
Works for me with Archlinux

**Comment by Wedge009** [comment]
Aye, works on Linux for me too.

**Comment by Wedge009** [comment]
Issue is still present with SDL 2.0.14 on 1.15.14+dev (1.16 branch). I should re-check this when 1.16 is released, but for the time being looks like Windows releases are still using SDL 2.0.8.

**Comment by Pentarctagon** [comment]
It would also be interesting to know if this is specific to Windows 7 or if it also happens on Windows 10.  I don't know why it would be, but it's strange that this behavior is happening in the first place.

**Comment by Wedge009** [comment]
I wondered about that too, but I only have Win 10 on a laptop (OS monopoly) and don't have Wesnoth build set-up there (official release only uses SDL 2.0.8). The problem may 'go away' if we just declare Wesnoth to be only supported on 10 onwards for Windows, but would be nice if someone else with Windows 7 can confirm or refute this, since it could also be a peculiarity with my particular build.

Retesting with the just released SDL 2.0.16 still has the issue - both 1.15.15+dev and 1.17.0+dev. What I observe is that while Wesnoth remembers the window resolution it was using previously when reverting from full-screen mode, internally it still tries to render its display at the resolution it had available when in full-screen mode. Upon exiting and restarting Wesnoth, it is displayed in windowed mode but at the same resolution as full-screen (minus space taken up by window decorations). So I wondered if there was something wrong with the way Wesnoth was recording resolutions or some such, but if that was the case one would expect this to be a problem with Linux builds as well... unless there's something OS-specific in the way SDL is handling things?

**Comment by Wedge009** [comment]
I just did a copy-paste of my Win 7 build to the Win 10 laptop and confirm the issue is present there. I also dropped the SDL2.dll binary for SDL 2.0.16 to the Steam release and can replicate the issue there as well, so it's not just an issue with my build. Seems worthwhile reporting to SDL team, perhaps.

**Comment by Wedge009** [comment]
The same issue is observed when toggling full-screen via the preferences dialogue - ie via mouse instead of keyboard short-cut or 'hot-keys'. Except that when the preference dialogue is closed the display is redrawn at the correct resolution.

I recall Wesnoth is using SDL in perhaps not-quite-standard ways, but I did find https://github.com/libsdl-org/SDL/issues/3363 in SDL's issue tracker. However, it predates the libsdl 2.0.9 release by a few months and doesn't seem exactly what I'm experiencing here.

**Comment by Wedge009** [comment]
I just noticed the 1.15.17 stand-alone Windows release (1.16 beta) includes SDL 2.0.12, so I imagine this is likely to become an issue for the new release.

**Comment by Wedge009** [comment]
Response from a SDL developer suggests that things are working as expected from their perspective. So perhaps this is an issue with how Wesnoth is using the resizing? BTW, would be good if someone else can confirm this, though I have confirmed this on both Windows 7 and 10, with the official Windows 1.16.0 release.

**Comment by Wedge009** [comment]
SDL dev has closed https://github.com/libsdl-org/SDL/issues/4637, effectively dismissing it as a Wesnoth-specific problem.

**Comment by Wedge009** [comment]
Just noting it's still an issue in Windows, tested 1.16.2+dev with SDL 2.0.22.

**Comment by mesilliac** [comment]
It's possible this was fixed by one of the recent changes. Does it still happen in current master?

**Comment by Wedge009** [comment]
I already retested this one, it still occurs. Very easy to test for yourself at the title screen, assuming you're in Windows. It seems Wesnoth isn't using SDL according to specifications, given the SDL developers closed my report.

**Comment by mesilliac** [comment]
I don't see the same problem on Linux, resizing and fullscreening update correctly in all cases. But yes the related video code is somewhat iffy, and is probably doing something wrong.

**Comment by Wedge009** [comment]
Yes, I already made it clear it's a Windows-specific issue. I also don't observe the issue in Linux.

**Comment by Wedge009** [comment]
Wow, really strange. This seems to be resolved from SDL 2.24.0 onwards (current at time of writing is 2.24.2).

I reconfirmed the problem on the previous release of SDL 2.0.22 for _both_ master and 1.16. Without recompiling, but just dropping the newer `SDL2.dll` into the directory, the issue is resolved.

So this can be closed if/when SDL 2.24.0 or newer is packaged with Windows releases (Steam 1.16 release currently uses SDL 2.0.22).

**Comment by Pentarctagon** [comment]
For Steam it's up to Valve, though they have updated SDL2 to in the past so it'll probably happen eventually. vcpkg seems to have SDL 2.24 available, so it'd be a matter of updating the baseline Visual Studio is using to something more recent.

@loonycyborg would the standalone Windows version be able to use SDL 2.24?

**Comment by Pentarctagon** [comment]
Looks like SDL 2.24 is actually already available for Steam-Linux, we just need to use a newer Sniper image for our builds.

**Comment by loonycyborg** [comment]
Seems msys2 has 2.24.1, so just would need to rebuild images.

**Comment by Pentarctagon** [comment]
Cool, would you be able to do this for 1.17.10?

**Comment by loonycyborg** [comment]
Docker images are updated now.

**Comment by Pentarctagon** [comment]
Great, thanks.

@Wedge009 So with 1.17.10, please confirm whether this is resolved or not.

**Comment by Wedge009** [comment]
Pretty sure I rebuilt everything but 4c61f0781 still shows as using 2.0.22 for me. cmake build.

BTW, anyone on Windows can easily check this.

**Comment by loonycyborg** [comment]
If you're doing local build then you'll have whatever you have installed. If you're using vcpkg you should get update from here. But @Pentarctagon was actually referring to next release, not your local build. When it's actually released.

**Comment by Pentarctagon** [comment]
@Wedge009 try your local build with https://github.com/wesnoth/wesnoth/commit/0ac49cf1261c94cfe57955a45a6c065a3e37180a

**Comment by Wedge009** [comment]
For Windows I use MSVC with cmake as per recommendations and I thought the cmake configurations applies specific SDL versions, among other things from vcpkg, etc.

But I also misunderstood that 1.17.10 hasn't been released yet.

At any rate, I did a complete update and rebuild of vcpkg and wesnoth master and it pulls in SDL 2.42.2 now, thereby resolving this issue. Does it make sense to leave this open till 1.18 is released, or just till 1.17.10?

**Comment by Pentarctagon** [comment]
I'd say 1.17.10.

**Comment by Wedge009** [comment]
Marking as resolved since official 1.17.10 release downloaded from sourceforge.net is packaged with SDL 2.24.1 and no longer exhibits this strange behaviour.
