### ISSUE TITLE
Draug characters should have another portrait for campaigns prior to the Sceptre of Fire

### ISSUE THREAD

**Issue by slavrenyuk** [wesnoth/wesnoth#4518]
While playing "The Rise of Wesnoth" I noticed that there are two Draug enemies which have dialogues:
[Draug in "The Vanguard" scenario](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/The_Rise_Of_Wesnoth/scenarios/19_The_Vanguard.cfg#L542)
[Draug in "Return of the Fleet" scenario](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/The_Rise_Of_Wesnoth/scenarios/20_Return_of_the_Fleet.cfg#L38)

Those Draugs use default portrait and there is Scepter of Fire depicted on the shield.
[draug.png](https://github.com/wesnoth/wesnoth/blob/master/data/core/images/portraits/undead/draug.png)
[original shield with Scepter of Fire](https://forums.wesnoth.org/download/file.php?id=52217&t=1)

However, Scepter of Fire was created later than "The Rise of Wesnoth" campaign (as well as "An Orcish Incursion", "The Legend of Wesmere" and "Secrets of the Ancients" according to the [Timeline of Wesnoth](https://wiki.wesnoth.org/Timeline_of_Wesnoth), though I haven't checked if those campaigns have the same issue)

Possible solution is to use either [draug-2.png](https://github.com/wesnoth/wesnoth/blob/master/data/core/images/portraits/undead/draug-2.png) or [revenant.png](https://github.com/wesnoth/wesnoth/blob/master/data/core/images/portraits/undead/revenant.png)

**Comment by Wedge009** [comment]
I don't think we know for certain that the image on the shield is supposed to depict the Sceptre of Fire. Still, that's a good observation, and maybe the question should be put forward to artist/s as to what it's supposed to represent and what the intention was behind it. If a lore inconsistency is really there I suppose it's just a matter for an artist (original or otherwise) to update the image on the shield, but I'd say it's pretty low-priority. (Not meaning that it shouldn't be resolved, though.)

**Comment by Wedge009** [comment]
Nit-pick: official spelling is Sceptre of Fire.

**Comment by slavrenyuk** [comment]
@Wedge009 

> Nit-pick: official spelling is Sceptre of Fire.

I updated the wiki page https://wiki.wesnoth.org/index.php?title=Timeline_of_Wesnoth&type=revision&diff=65021&oldid=64374

> I don't think we know for certain that the image on the shield is supposed to depict the Sceptre of Fire.

Have you looked at the both images that I linked?

https://github.com/wesnoth/wesnoth/blob/master/data/core/images/portraits/undead/draug.png
https://forums.wesnoth.org/download/file.php?id=52217&t=1

Meaning of Wesnoth logo is described here in this topic https://forums.wesnoth.org/viewtopic.php?t=24484 (shield with the Sceptre of Fire). I can clearly see that Draug's shield has corrupted image of the Sceptre of Fire. Few posts below @shikadiqueen says:
> It's been in the logo of the titlescreen all the time, just difficult to notice.


... after half of an hour of searching ...

Here is the thread where that Draug portrait was created. https://forums.wesnoth.org/viewtopic.php?f=9&t=26022&start=285#p433436 and below. There are no explicit mentions that the Sceptre of Fire is on the shield (probably because it is obvious), here are a few quotes:

> I absolutely love the shield emblem!

> Shouldn't only the black paint be "dripping" from the emblem? I guess the sceptre has been originally there so it was probably painted proffessionaly and just the black paintover has been done by the skeleton or his necromancer...

**Comment by slavrenyuk** [comment]
> If a lore inconsistency is really there I suppose it's just a matter for an artist (original or otherwise) to update the image on the shield, but I'd say it's pretty low-priority.

Of course it doesn't affect the gameplay. It is like an actor with a wristwatch in a Roman Empire movie. Important part of the Rise of Wesnoth story is the Ruby of Fire. Sceptre of Fire is created from the Ruby of Fire and is used as the shield emblem by some of Wesnoth warriors. But that will happen several decades later after TRoW is finished.

**Comment by Wedge009** [comment]
> Have you looked at the both images that I linked?

Yes, I did.

I'm not saying it's _not_ the Sceptre of Fire, just that nowhere it explicitly says that it is.

> Of course it doesn't affect the gameplay. It is like an actor with a wristwatch in a Roman Empire movie.

I admire your attention to detail, but I wouldn't call it an anachronism on that level. There could be any number of reasons one has a shield with a sceptre on it. If the sceptre image is indeed supposed to be Sceptre of Fire, then yes, I agree, it ought to be changed. But it can easily be explained away that it is _not_ the Sceptre of Fire. Thus it is not a high priority. It is not as though the Draug is armed with an automatic rifle - now _that_ would be an anachronism.

**Comment by Wedge009** [comment]
Sorry, I have no idea how I wound up editing your comment instead of adding my own...

**Comment by slavrenyuk** [comment]
@Wedge009 

> I admire your attention to detail, but I wouldn't call it an anachronism on that level. There could be any number of reasons one has a shield with a sceptre on it. If the sceptre image is indeed supposed to be Sceptre of Fire, then yes, I agree, it ought to be changed. But it can easily be explained away that it is not the Sceptre of Fire. Thus it is not a high priority. It is not as though the Draug is armed with an automatic rifle - now that would be an anachronism.

Ok, I agree with you. Just in case I created a PR for changing the portraits.

**Comment by slavrenyuk** [comment]
Just in case - I checked that there is no Draug characters in "An Orcish Incursion", "The Legend of Wesmere" and "Secrets of the Ancients" campaigns.
