### ISSUE TITLE
Map size displayed as 0x0.

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#4519]
### Game and System Information
 - 1.15.2
 -Steam
 - Windows 10

### Describe the bug
Map size is displayed as 0x0.

### To Reproduce
Try to create game on Steam version of wesnoth. 

### Screenshots
![bug](https://user-images.githubusercontent.com/41817546/67593816-4d2b0a00-f763-11e9-896a-a7568f5a0eec.PNG)

@sevu

**Comment by ProditorMagnus** [comment]
Scope not limited to steam.

**Comment by Pentarctagon** [comment]
I can confirm that this happens to me for Steam and non-Steam on linux.

**Comment by jostephd** [comment]
Why is @Vultraz assigned? I suspect this was caused by the combination of #4407 and e29287eeee2f5a306f09d3712efcb31b4504d7ed, but haven't confirmed.

**Comment by Vultraz** [comment]
Yeah, looks like #4407 just sets the map data directly, but this requires some deeper tinkering besides just reverting. So I'll look into it since that code is my area.

**Comment by jostephd** [comment]
Thanks.

**Comment by Pentarctagon** [comment]
@jostephd vultraz also asked to be assigned this on Discord, which is why I went ahead and did that.

**Comment by Wedge009** [comment]
Yes, issue in master, but not in 1.14.

**Comment by jostephd** [comment]
Set milestone, feel free to change it though.

**Comment by Pentarctagon** [comment]
Adding the Blocker label if for no other reason than this would be an absurd thing *not* to fix by 1.16.

**Comment by Pentarctagon** [comment]
Fixed in #4652
