### ISSUE TITLE
:inspect crashes with uncaught std::bad_cast when clicking on "events"

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4540]
### Game and System Information
Linux built from Git 14e650819d69354612cdd1c34262b08370d9057d

### Describe the bug
1. Start a game (can be the tutorial)
2. `:debug`
3. `:inspect`
4. Click on "events"
Crashes with an uncaught std::bad_cast:
```
Thread 1 "wesnoth" hit Catchpoint 1 (exception thrown), 0x00007ffff743925e in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) up
#1  0x00007ffff742d148 in __cxa_bad_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) up
#2  0x0000555555fe0e75 in gui2::dialogs::gamestate_inspector::controller::handle_stuff_list_item_clicked (this=0x55555bc55240, tree=...)
    at src/gui/dialogs/gamestate_inspector.cpp:324
324			tree_view_node* selected = dynamic_cast<tree_view&>(tree).selected_item();
(gdb) p tree
$1 = (gui2::widget &) @0x55555bcc0cc0: {<gui2::event_executor> = {_vptr.event_executor = 0x555557288160 <vtable for gui2::tree_view_node+16>, wants_mouse_hover_ = false, 
```

### Additional context
Reverting commit 2adac53461b62d3f1aa30b496759451555c5361e solves the problem. Don't be confused by the 2018 author date on that commit, it was one of the batch that was merged less than 24 hours before 1.15.2 was tagged.

**Comment by Pentarctagon** [comment]
@Vultraz
