### ISSUE TITLE
TRoW Haldric with the Ruby of Fire uses bow animation on defense

### ISSUE THREAD

**Issue by slavrenyuk** [wesnoth/wesnoth#4541]
Haldric with bow defense animation is shown when he uses Ruby of Fire attack. Animation filters should be used to fix this https://wiki.wesnoth.org/AnimationWML#Generic_animation_filters_available_for_all_animations

**Comment by Wedge009** [comment]
Not sure if I understand you correctly - I realise timing might be tricky but if you can get an image of the problem it would help, I think.

**Comment by slavrenyuk** [comment]
@Wedge009 

This defense animation [link](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/The_Rise_Of_Wesnoth/units/Noble_Lord.cfg#L25) is used for this attack [link](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/The_Rise_Of_Wesnoth/scenarios/12_A_Final_Spring.cfg#L240-L276)

**Comment by Wedge009** [comment]
I don't know WML that well but I would guess that the Ruby of Fire is an addition to the unit for ranged attacks, and his normal ranged attacks are still used for defence. The question is what's the behaviour for other units which have more than one attack/defence option and how should that convention apply to Haldric in this situation? One example I recall from memory is the Elvish Sylph line.

**Comment by slavrenyuk** [comment]
@Wedge009 it's not actually defending with the bow, it's just showing bow in his hands when he is hit with ranged attack. And yes, the Ruby of Fire is his additional ranged attack. I know how to fix this, I will try to make PR today.

Btw I update bug description, initial version was not quite correct, sorry if that confused you.
