### ISSUE TITLE
selecting »Custom Maps« in MP Lobby crashes if having an invalid map

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4545]
Try to create a new MP game and select custom maps from the drop-down menu
(This entry is only available if one created maps with the editor):
>
wesnoth: /usr/include/boost/dynamic_bitset/dynamic_bitset.hpp:701: boost::dynamic_bitset<Block, Allocator>::~dynamic_bitset() [with Block = long unsigned int; Allocator = std::allocator<long unsigned int>]: Assertion `m_check_invariants()' failed.

Program terminated with signal SIGABRT
current 1.14 git branch, boost 1.71
special note: the editor directory in my userdata directory is a symlink to the 1.12 one (though that's the case for 2 years)

It's apparently related to having a map in that directory with this content:
```
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Dd, Gg, Gg, Gg^Dc, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg, Gg
```
Gg^Dc is an invalid terrain code. ( ^Dc is not an overlay and Dd^Dc is a single terrain)

It does crash  as described above if having this and at least another map.
With only this one map it doesn't crash as above with SIGABRT, thugh one is likely to encounter an SIGSEGV when clicking around afterwards, maybe because the map is not shown in the list.

**Comment by gfgtdf** [comment]
See also https://github.com/wesnoth/wesnoth/issues/4395
