### ISSUE TITLE
Use of $unit.overlays in ANL, DiD and SotA

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4550]
As of PR #4211, setting [unit]overlays= works, but the [unit]overlays attribute will always be empty if WML tries to read it. This means the following three uses are now broken:
- [x] SotA's lichify macro `overlays=$stored_necromancer.overlays`
- [x] DiD's copy of that lichify macro (@nemaara, is this going to be removed anyway?)
- [x] ANL's clearing of critter's overlays:
https://github.com/wesnoth/wesnoth/blob/a075a2971c192aec381fa31311953fef4c11a456/data/multiplayer/scenarios/ANL_utils/ANL_special_macros.cfg#L218-L220

**Comment by nemaara** [comment]
I already removed that here https://github.com/wesnoth/wesnoth/commit/79d97a11898d15c314b1f8cb7b127c473898bc33.

**Comment by stevecotton** [comment]
Removed the leftover DiD code in 80b03f1a05e86bfe794a4482b4ab2ce23ae6b219

**Comment by sevu** [comment]
Will change the ANL code

**Comment by sigurdfdragon** [comment]
Removed from SotA in f55704cff8753bb771e06d2fce6286dddc825883

**Comment by sevu** [comment]
5ee5920 changes the ANL part.
