### ISSUE TITLE
Backport type+variation modification fix

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#4558]
217992a843f1ca9fc62eda02d0e376619ab786f7

**Comment by CelticMinstrel** [comment]
Oh right, forgot to mention - I'm pretty sure this is a regression in 1.14, so that's why I consider it backport-worthy.

**Comment by gfgtdf** [comment]
>  I'm pretty sure this is a regression in 1.14, 

Why is that? I currently see no reason to believe that

**Comment by CelticMinstrel** [comment]
Hmm, checked the code, not so sure now, but still suspect it might be, but you could be right and it's not.

Regardless, it's a bugfix, not an API change (other than the added heal_full for apply_to=variation).

**Comment by Wedge009** [comment]
3d373329
