### ISSUE TITLE
Clean up WML/Lua deprecation warnings in mainline content

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#4561]
Even from just opening the tutorial, there are a _lot_ of deprecation warnings that pop up in chat. (This assumes running with debug mode enabled one way or another.) We should try to avoid using anything deprecated in mainline WML and Lua, which means all these warnings should be cleaned up before 1.16. Most of them are straight substitutions, so it might not even be difficult.

**Comment by gfgtdf** [comment]
We really must have a rule that when people deprecate something they _must_ also check/update all mainline content that uses it (in fact I thought we had such a rule)

**Comment by CelticMinstrel** [comment]
I probably forgot or something? Or they were deprecated at level 1 so I couldn't be bothered? I can't remember.

**Comment by mattsc** [comment]
FTR, I took care of deprecation warnings in the Lua AIs in 55478e20ad2 (and then fixed the things I had messed up in 68bb48ddf1).

**Comment by stevecotton** [comment]
I think this issue should be closed, and separate issues opened if any more warnings remain.

I don't see any Lua warnings remaining when opening the tutorial. However, as currently written the bugreport would need someone to play through all of the campaigns to confirm that it's been fixed everywhere. I think it would be better to open new reports when finding any warnings.

**Comment by mattsc** [comment]
From the Lua AI side, that's fine.  I think most everything is fixed there.  I am already planning to run all the Micro AI test scenarios again for other reasons, and I'll fix any remaining deprecation warnings I'll come across in the process, independent of this issue.  I've just been waiting for the Lua gamemap PR to be merged (and now I need to wait for the crash that caused to be fixed).

**Comment by CelticMinstrel** [comment]
I did do a pass of World Conquest and replaced quite a lot of deprecated stuff, but it's possible I missed something.

**Comment by mattsc** [comment]
I did my pass of the AI code, and found a few instances in non-AI Lua code in the process.  All of that is updated now.

Can we close this issue at this time?

**Comment by Pentarctagon** [comment]
Is there any way to proactively find deprecated usages?  I doubt many people play with debug mode enabled in the first place (or even know it exists), much less while playing through campaigns.

Would it make sense to have lua deprecation warnings show up without needing to use debug mode?

**Comment by CelticMinstrel** [comment]
I didn't actually try without debug mode, but showing them in the Lua console probably ignores debug mode (though you need to enter debug mode to view the console). Additionally, there's the new --strict-lua command-line flag which instructs the kernel to remove the deprecated functions entirely, so they raise an error instead of just being a warning. (There's probably a few deprecated functions that this misses, so if you try it and find one, let me know.)

**Comment by Pentarctagon** [comment]
What I'm thinking though is that "people can open a new bug if they find more usage of deprecated functions" is essentially not going to happen in the first place - unless you're already a developer, there's already a very low chance that you know that enabling debug mode will make lua deprecation messages be printed, and even more so if someone would need to be playing through the mainline campaigns with debug mode enabled.  So I think it would make sense to not hide the lua deprecation warnings behind enabling debug mode and instead show them all the time - there are already few enough people who look at the logs, and those exist *without* needing to take an extra step to enable.

**Comment by CelticMinstrel** [comment]
I suppose you're also going to argue that people aren't that likely to open the Lua console where they can then see the deprecation warnings. (And in fact there's no way to do so if it's a map generation script - I had to add a `gui.open_lua_console` call to WC's map generation script to find the deprecated usages in there.)

What about making deprecated messages visible in chat and logs without debug, but _only_ in dev releases? IOW, if the minor revision of the version is odd.

**Comment by Pentarctagon** [comment]
I think that'd make sense.

**Comment by Pentarctagon** [comment]
So I think that'd just be changing https://github.com/wesnoth/wesnoth/blob/41fa00de2aa3e008f598d2022c88eb99dffb1bf3/src/deprecation.cpp#L82 to be:
`if(preferences::get("show_deprecation", false) || game_config::wesnoth_version.minor_version() % 2 == 1)`
?

**Comment by CelticMinstrel** [comment]
I think there's a `utils::is_odd` function which might be a little clearer, but other than that, yes, it seems correct.

**Comment by Pentarctagon** [comment]
Rather strangely, the warning displayed ingame has its line displayed in reverse order.  The warning logged is:
```
unpack has been deprecated and will be removed in version 1.17.0.
   (Note: You should use table.unpack instead in new code)
```
while the warning displayed ingame is:
```
Invalid WML found:    (Note: You should use table.unpack instead in new code)
Invalid WML found: unpack has been deprecated and will be removed in version 1.17.0.
```

**Comment by Pentarctagon** [comment]
Added in 7050eaf03e4a1045f569c1f21def1f816550344e
