### ISSUE TITLE
AppVeyor WebHook fails

### ISSUE THREAD

**Issue by GregoryLundberg** [wesnoth/wesnoth#4567]
Examining recent AppVeyor runs I note we are consistently seeing an error reporting results via the web hook. I looked back a week or so and it's been there at least that long, but have no idea how long this has been going on.

Specifically, AppVeyor reports the following message on all runs:
```
Error sending Webhook notification: Error calling webhook http://ai0867.net:6661/wesnoth: An error occurred while sending the request.
```

A quick test on my computer indicates that while http://ai0867.net is up (it shows the default Apache "It Works" page), the server is not accepting connections on port 6661,

**Comment by AI0867** [comment]
That's the irker appveyor message collector. It's now back up (a dependency broke somewhere, causing it to not come back up after reboot).

If this causes actual failures in the build, that needs to be fixed in the appveyor script.

**Comment by GregoryLundberg** [comment]
The builds appeared to succeed or fail on their own merits. This was just an error message appearing at the end of every one.

**Comment by soliton-** [comment]
@AI0867 Would be nice to get this setup on wesnoth.org at some point so more people are able to fix things.

**Comment by GregoryLundberg** [comment]
More importantly, so we're not dependent upon one programmer remaining active with the project.

**Comment by AI0867** [comment]
True.

This is a fairly simple setup of the following pieces of software:

- [irkerd](https://gitlab.com/esr/irker) (no configuration)
- [irker-appveyor-collector](https://github.com/AI0867/irker-appveyor-collector) (configuration described in README, with example in repository)

Other sources may require other software:

- github: [irker-github-webhook](https://github.com/AI0867/irker-github-webhook)
- sourceforge: [sf-git-irker-pipeline](https://github.com/AI0867/sf-git-irker-pipeline)
- irkerhook from other servers: [irker-filter](https://github.com/AI0867/irker-filter)
