### ISSUE TITLE
The Fog/Shroud in campaigns after using Debug

### ISSUE THREAD

**Issue by NobracNoj** [wesnoth/wesnoth#4586]
I downloaded the game via steam and it's always updated.

It was working fine until yesterday I tried out debug and typed in shroud and fog to reveal the map

After using cheats to reveal map in campaigns i'm unable to ever undo it again. 
Uninstalling and Re-installing the game didn't do as the Shroud and Fog cheat are still there.
Quiting or restarting the game did not remove the cheat. I even turned off all the cheat in a campaign before advancing to the next level but it just comes back after loading the map.

This ruins the game as the secrets of the map is always revealed and I can always see the enemies

because of this the map is always revealed at the start of the game and the encounter dialogue for some of the Ai are always triggered. 

What can I do to undone this?

**Comment by Pentarctagon** [comment]
What operating system are you on and what version of Wesnoth are you using?  Also, which campaign/scenarios did this happen on?

**Comment by NobracNoj** [comment]
Windows 7 Ultimate 
1.14.9(9eba78f-Modified)
Running on Microsoft 7 Service Pack 1(6.1.7.601) is what i read

I'm currently playing the first four of the campaigns and both of them are without shroud or fog in every beginning of the games.

tho the scenarios with the cave are exempted as they start with the shroud on but the fog isn't there.

the multiplayer games seem fine as the fog is on when playing them

**Comment by NobracNoj** [comment]
The scenario in Heir to the Throne: Isle of Damned, The Dwarven Doors, Plunging into Darkness, The Lost General, Hasty Alliance, The Scepter of Fire, are the only maps i saw that started without revealing the whole map. The Isle one had fog on, and the Cave scenarios had shroud so the map wasnt revealed in the start of the game.

Ever since enabling debug and typing fog/shroud the cheat has stayed in the game and i cannot disable it in campaigns... not even when i reinstall the game
