### ISSUE TITLE
Using new Naga units in campaigns

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4591]
With the Dunefolk new Naga units were added to mainline.
Instead of 1 Lv1 Naga exist now 2, and for the higher levels there are three times as much possible Nagas to chose from.

Existing campaigns could make use of them, and should at the one or other place.

**Comment by CelticMinstrel** [comment]
Note that using them in northern campaigns would be contrary to the lore that these are southern nagas.

But they could still be used in some campaigns, I'm sure.

**Comment by sevu** [comment]
So I read through their descriptions and they are pretty good, also putting in some effort into Dunefolk worldbuilding.

But it's not smart to limit them to only the southern map by prose.
These units will get good sprites, animations, portraits and even got their values properly balanced.
Nagas have been a 1 line race, adding the second line could be used to add more depth to them.

The new ones are coupled to the Dunefolk and thus the south because of the MP faction, but they don't have to be there exclusive. Keeping them exclusive makes it harder to wire them in, to find a place for them in Wesnoth's lore (which is already hard enough for the Dunefolk).
Aside from that, where is "the south"? Dunefolk are in the south because the real live Khalifate was in the south from the perspective of the dark age knights. And the wesnoth map has some unspecified desert in the south. Where does "the south" start, is "The South Guard" south enough? It had a scenario with the normal Nagas until it was removed recently, would that have been to south for the northern Nagas as of today?

I see the Naga (and Saurians) as a race which lives here and there, where they haven't been ~~killed~~ pushed back by the major races.
References to the Dunefolk in their descriptions are fine and helpful for the lore, we should keep them less strict and more as optional (i.e. they are often seen dwelling with the Dunefolk instead of "the southern Naga").

**Comment by GregoryLundberg** [comment]
Also, I'm thinking the existing Naga appear in more temperate climates, usually along waterways and in marshes, which does not seem to fit well with them being mainly in the deserts of the south.

**Comment by CelticMinstrel** [comment]
I think the area of the South Guard about as far north as the dunefolk have ever ventured, but more west (based on the giant map that's floating around somewhere). So perhaps southern nagas could fit there, I guess, though it'd maybe be a stretch. The southern naga don't live in the deserts of the south. They live _south_ of the deserts.

**Comment by sigurdfdragon** [comment]
I'm thinking about using the new nagas in WoV S05 Islands (located between the Green Isle and the Great Continent) They'd provide needed ranged damage & variety for the enemy side.

>But it's not smart to limit them to only the southern map by prose.
These units will get good sprites, animations, portraits and even got their values properly balanced.
Nagas have been a 1 line race, adding the second line could be used to add more depth to them.

I agree with this. If lore limits them to south of the desert, it puts obstacles in the way of justifying their addition.

**Comment by UnwiseOwl** [comment]
Checklist of current places where mainline campaigns encounter naga units. I am happy to work through these and add a mix of the new guys into them if it's decided to go ahead and do so.

- [ ] Descent_Into_Darkness\03_A_Haunting_in_Winter.cfg 
- [ ] Heir_To_The_Throne\04_The_Bay_of_Pearls.cfg
- [ ] Legend_of_Wesmere\07_Elves_Last_Stand.cfg
- [ ] Northern_Rebirth\05a_01_The_Pursuit.cfg
- [ ] Secrets_of_the_Ancients\11_Battleground.cfg 
- [ ] Secrets_of_the_Ancients\21_Against_the_World.cfg
- [ ] The_Rise_Of_Wesnoth\08_Clearwater_Port.cfg
- [ ] The_Rise_Of_Wesnoth\12_A_Final_Spring.cfg
- [ ] The_Rise_Of_Wesnoth\14_Rough_Landing.cfg
- [ ] The_Rise_Of_Wesnoth\17b_Lizard_Beach.cfg
- [ ] The_Rise_Of_Wesnoth\22_The_Rise_of_Wesnoth.cfg

UtBS has its own custom nagas.

**Comment by CelticMinstrel** [comment]
I don't know _where_ all of those take place, but it feels like most of them are too far north for a native appearance of the new nagas. That doesn't meant their presence can't be justified, I guess…

**Comment by ghype** [comment]
> Keeping them exclusive makes it harder to wire them in, to find a place for them in Wesnoth's lore (which is already hard enough for the Dunefolk).
> Aside from that, where is "the south"? Dunefolk are in the south because the real live Khalifate was in the south from the perspective of the dark age knights. And the wesnoth map has some unspecified desert in the south. Where does "the south" start, is "The South Guard" south enough? It had a scenario with the normal Nagas until it was removed recently, would that have been to south for the northern Nagas as of today?

For answering the question where "south" might be, this is a map we are currently developing with the goal to canonise it. Everything north/west from the white line is considered canon. Everything else is part of the southern expansions.

The beginning of the Sandy Wastes then indeed could be considered the border between north and south. The living space of the southern nagas however currently are reduced to the Bay Of Clouds, the area between Palmiya and the Sleepless Sea and the riverlands in the south.

As far my understanding goes, undead were rumouring the black forest (Mal M'Brin) so I doubt the nagas would move along that coast a lot and if they were weary about the undead. 
This thread explains the lore being developed behind the south and the nagas a bit better:
https://forums.wesnoth.org/viewtopic.php?p=654722#p654722

Quenoths are a product of the Fall but it doesn't mean that UtbS nagas are. Why can't they used as variation for naga fighters considering that they look more similar to them as the new ones (as the new ones are intended to look differently).


![New Irdya-18](https://user-images.githubusercontent.com/38769187/80374047-57ef6480-8896-11ea-8ce2-1399517a006a.png)

**Comment by Wedge009** [comment]
Regarding question of 'north' vs 'south' - I was considering that whatever the Northlands comprise of, 'south' could be south of that. But it all seems pretty vague and relative to me anyway.

I haven't seen what the distinguishing features of these 'new' nagas are, but if it fits a given scenario and associated lore I suppose there could be potential for introducing them there. On the other hand, I understand @nemaara is doing a lot of work the over-arching lore in the background and may have an opinion on this one way or another.

**Comment by nemaara** [comment]
I was thinking you might start to see them south of Wesmere, maybe around the Bay of Pearls area. Further inland, you'd encounter them south of Weldyn perhaps.

**Comment by sevu** [comment]
There was also a third line of Nagas – with mace –  added since this issue was opened.

**Comment by Gothyoba** [comment]
Naga Dirkfangs are now used in WoF. Naga Guards and Shield Guards are now used in EI.

**Comment by Pentarctagon** [comment]
Just to confirm before closing - these are now used in WoF?

**Comment by Jonathan-Kelly** [comment]
They are used WoF, specifically scenarios 4 and 11.

**Comment by Gothyoba** [comment]
The otehr bew line with maces is used in EI. So all are used now,
