### ISSUE TITLE
Migrate 'irker' (and ilk) to project hosts

### ISSUE THREAD

**Issue by GregoryLundberg** [wesnoth/wesnoth#4602]
We use a few Continuous Integration platforms. When they complete a test run, we can receive notification of the results.

The 'irker' programs were written to receive these notifications and forward them to IRC.

At present, AI0867 runs these on his personal domain.

We should move these programs to a machine in the project domain so we are not dependent upon one programmer remaining active on the project and so others can correct issues (such as recently experienced), and add or remove services as our needs evolve.

Links to the repositories for these programs are at the end of [Issue 4567](https://github.com/wesnoth/wesnoth/issues/4567#issuecomment-558626519).

**Comment by Pentarctagon** [comment]
Closing as the alerts are only sent to Discord ever since the migration to github actions.

**Comment by CelticMinstrel** [comment]
What? There are alerts sent to IRC too, via "wesbot". I have no idea if this is still hosted by @AI0867 though.

**Comment by Pentarctagon** [comment]
I assume they are sent over via the regular bridgebot, not directly from github actions, since the github actions setup does nothing related to IRC.

**Comment by CelticMinstrel** [comment]
They're not send from the IRC bridge bot. It's a separate bot in IRC. I don't know the details, however.

**Comment by soliton-** [comment]
There are webhooks enabled for wesbot. It is running on wesnoth.org though so this is obsolete anyway.
