### ISSUE TITLE
Ai advancement aspect not come considered for umc invoicked advancements

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4605]
When and advancent of an ai controlled is caused by umc code for example [unstore_unit] the unit will be advanced randomly and the ai code for choosing an advancement will not be used.

**Comment by gfgtdf** [comment]
to be clear, the main challenge here is to firegure out how to get  the  `ai::unit_advancements_aspect` from outside the ai code, since i dont have an overview of teh code structure of the code inside ai:: it'd be nice if someone else could do this.

**Comment by CelticMinstrel** [comment]
@gfgtdf - I suspect two good places to look with regards to this would be:

* The `wesnoth.debug_ai` function, defined at game_lua_kernel.cpp:3617
* The `wesnoth.add_ai_component` function (and its related delete/change functions), defined at game_lua_kernel:3087

(Probably the first is more relevant, but the second may help a little too.)
