### ISSUE TITLE
Goto Micro AI broken "attempt to call a nil value (method 'movement')"

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4608]
### Game and System Information
Local builds from master, building with GCC9 on Linux (Debian Unstable).
Bisecting shows the first bad commit as 153680400d, and I can still reproduce it with branches based on 1c6d1ddfa.

### Describe the bug
Using the Goto Micro AI throws many Lua errors:
```
20191129 05:12:21 error scripting/lua: ai/micro_ais/cas/ca_goto.lua:11: attempt to call a nil value (method 'movement')
stack traceback:
	ai/micro_ais/cas/ca_goto.lua:11: in function <ai/micro_ais/cas/ca_goto.lua:9>
	(...tail calls...)
	[C]: in field 'find_path'
	ai/micro_ais/cas/ca_goto.lua:153: in field 'execution'
	[string "local self, params, data, filter_own = ......"]:2: in main chunk
```

Other Micro AIs seem okay (checked the Animals and Bottleneck Defense ones).

### To Reproduce

1. Run `wesnoth -t goto` from the command line
2. End turn
3. Press spacebar twice to dismiss the `[message]`s
4. A load of Lua errors occur

**Comment by CelticMinstrel** [comment]
Seems like this is a result of my Lua reorganization work. The name of that function was changed to `movement_on`, but I messed up the old-name stub.

**Comment by stevecotton** [comment]
Thanks for the very quick response.
