### ISSUE TITLE
IDs for Experimental AI CAs

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4611]
Having IDs would allow to remove CAs.
Particular use case: removing retreat_injured on a map where the AI should be recklessly aggressive or cannot heal anyways.

I also wonder if it's helpful to define the CAs in their own macros, which allows to add them later. Tough – no use case currently.

**Comment by CelticMinstrel** [comment]
I suspect @mattsc is already working on this with #4598?

**Comment by sevu** [comment]
Found it on the list, it's even already checked.

**Comment by mattsc** [comment]
I'm a little late to this but, yes, that was the very first commit of PR #4600.  You posting this brought it to my attention though that this is one (of a few) commits of that PR that should be backported.  The others being whatever bug fixes I stumble across along the way.  I added a task for this to #4598.

**Comment by mattsc** [comment]
Well, actually ...  This cannot be done for 1.14 as the Experimental AI was only split up into separate CAs in 1.15.  I have backported the other bug fixes though.

**Comment by CelticMinstrel** [comment]
Wait, what?

**Comment by mattsc** [comment]
Just checking whether anybody is paying attention.  😉  Not even going to try to explain/justify where that came from...

It's now taken care of in b0a79e6e9fd for 1.14 (and for the record, the 1.15 commit was 3bd6613dda).
