### ISSUE TITLE
Mouse cursor is hourglass when dialog opens during AI turn

### ISSUE THREAD

**Issue by jostephd** [wesnoth/wesnoth#4618]
### Game and System Information
v1.15.2+dev (3ea5ee5f709-Clean)
self built
Linux

### Describe the bug
When a dialog opens during the AI's turn, the mouse cursor is an hourglass rather than a pointer.

### To Reproduce

1. Start `wesnoth -t`
2. End turn
3. Click through the [message], get the advancement choice dialog
4. In the advancement choice dialog, the mouse cursor is an hourglass

### Expected behavior
The mouse cursor should be a pointer, not an hourglass.

### Screenshots
![Screenshot_2019-12-03_09-15-17](https://user-images.githubusercontent.com/24784687/70037022-bfd2a500-15ad-11ea-9c4d-a7a7e500105f.png)

### Additional context
This also happens if I click through the advancement choice, let the AI play on, and press Ctrl+P to open the preferences dialog during the AI's turn. The preferences dialog opens and can be used but the mouse cursor is hourglass.

Regression from 1.14 and from earlier 1.15.

**Comment by jostephd** [comment]
I didn't test 1.14. If you think this should block 1.16 please milestone accordingly, I don't have an opinion.

**Comment by shikadiqueen** [comment]
I have observed this in the MP login dialog when it shows up during the loading screen sequence. My gut feeling is that it's an unexpected ramification of 47ddf8877f5bb481b933b2a3dbc012d4c156d69a.
