### ISSUE TITLE
items.lua bugs when loading scenario 1 of Htt

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#4621]
### Game and System Information
 - What version of the game are you running? master branch
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) built from source
 - If you're using a custom build, what compiler did you use, and what commit did you build at? Mingw and commit is https://github.com/wesnoth/wesnoth/commit/74e004c265dcd2c64d6ca9c554515f9eb9cbbec9#diff-be09c6b9e36e83e10415b68b58339693
 - What OS are you running? Windows 7

### Describe the bug
When start scenario highlight signpost then lua return an error message

### To Reproduce

1. Start game
2. Load Htt campaing(not a savegame)
3. Let scenario load and look.

### Screenshots
the message don't appear in screenshot

**Comment by GregoryLundberg** [comment]
Tested on Linux with 1.15.2+dev current master

$ git log -1
commit 0b89c6e4c97b0dd11ebe69c1f8000ef929e42344 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: nemaara <nemaara@gmail.com>
Date:   Fri Dec 6 22:10:39 2019 -0500

    DiD: decrease difficulty ratings
$ ./wesnoth
Battle for Wesnoth v1.15.2+dev
Started on Sat Dec  7 08:07:52 2019

Automatically found a possible data directory at /home/USER/wesnoth

Data directory:               /home/USER/wesnoth
User configuration directory: /home/USER/.config/wesnoth
User data directory:          /home/USER/.local/share/wesnoth/1.15
Cache directory:              /home/USER/.cache/wesnoth

Setting mode to 1920x1061
Checking lua scripts... ok
20191207 08:08:19 error scripting/lua: bad argument #2 to '?' (number expected, got table)
        [C]: in ?
        [C]: in function 'string.format'
        lua/wml/objectives.lua:119: in upvalue 'generate_objectives'
        lua/wml/objectives.lua:191: in local 'cmd'
        lua/wml-utils.lua:144: in field 'handle_event_commands'
        lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
20191207 08:11:05 error scripting/lua: lua/wml/items.lua:12: bad argument #1 to 'insert' (table expected, got boolean)
stack traceback:
        [C]: in function 'table.insert'
        lua/wml/items.lua:12: in upvalue 'add_overlay'
        lua/wml/items.lua:74: in local 'cmd'
        lua/wml-utils.lua:144: in field 'handle_event_commands'
        lua/wml-flow.lua:160: in local 'cmd'
        lua/wml-utils.lua:144: in field 'handle_event_commands'
        lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
20191207 08:11:06 error scripting/lua: attempt to index a boolean value
stack traceback:
        [C]: in for iterator 'for iterator'
        lua/wml/items.lua:45: in field 'write'
        lua/core.lua:534: in function <lua/core.lua:527>

**Comment by Pentarctagon** [comment]
@CelticMinstrel - this seems to have been caused by 30240aa7cda41bd5c1a660f17c67e76a9b9ab2cd.

**Comment by CelticMinstrel** [comment]
Actually it's caused by 74e004c265dcd2c64d6ca9c554515f9eb9cbbec9 - the commit you link also causes an issue that appears in the log from @GregoryLundberg but the issue from the original post is caused by this commit.

**Comment by CelticMinstrel** [comment]
GitHub didn't link it for some reason, so the commit fixing the other issue is e009989ec3d46b0be51d16f5116919c7142a82ca

**Comment by GregoryLundberg** [comment]
confirming appears fixed here
