### ISSUE TITLE
Now when i load scenario, prestart and start event don't played

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#4625]
### Game and System Information
 - What version of the game are you running?1.15
 - Where did you download it from? , built from source
 - If you're using a custom build, what compiler did you use, and what commit did you build at?Mingw
 - What OS are you running?windows 7

### Describe the bug
When i load a new scenario, i start event not played

### To Reproduce

1. Start wesnoth
2. choose scenario(not savefile)
3. Load and wait

### Expected behavior
Normally, start and prestart event must be played

### Screenshots
![Capture d'écran_003](https://user-images.githubusercontent.com/31768074/70389842-25b39800-19c5-11ea-855b-243a6c682318.png)

**Comment by GregoryLundberg** [comment]
Try clearing your cache files and re-testing?

**Comment by newfrenchy83** [comment]
oops, i haven't updated lua_common.cpp and lua_kenel_base in engine, sorry for that false alert
