### ISSUE TITLE
wesnoth compilation on mac fail in travis validation

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#4632]
### Describe the bug
the xcode validation failed because of https://travis-ci.com/wesnoth/wesnoth/jobs/265767039#L4904 

### To Reproduce

1. Pull a PR
2. wait to travis to finish
3. look the reason of fail...

### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

**Comment by Pentarctagon** [comment]
It's a result of [these two files](https://github.com/wesnoth/wesnoth/commit/1323e75ee2e076e610b33fae2ca41f09b18506d1#diff-341fce8450d8d3653ac91a70dd64adaf) being added.  Someone with macOS - @mattsc or @hrubymar10 - will need to update the xcode configuration.

**Comment by CelticMinstrel** [comment]
Was it really necessary to open an issue for this...?

**Comment by mattsc** [comment]
Fixed in f1f7bd4f6f
