### ISSUE TITLE
LoW - S3 'Ka'lian under Attack' Lua error

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4638]
### Game and System Information
 - What version of the game are you running?
1.15.2

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Steam

 - What OS are you running?
Windows 10

### Describe the bug
The Lua error seen in the image below is present once the scenario starts.
I have no idea what the error means.

### To Reproduce

1. Load the save file below.
2. Go past the story text and the map.

### Expected behavior
No Lua error.

### Screenshots
![grafik](https://user-images.githubusercontent.com/39015360/70852820-30c76600-1ea6-11ea-8a1b-19b201c1bf86.png)

### Savefiles
[LoW-Ka’lian under Attack.gz](https://github.com/wesnoth/wesnoth/files/3964174/LoW-Ka.lian.under.Attack.gz)

### Additional context
[wesnoth-20191214-191749-3964.log](https://github.com/wesnoth/wesnoth/files/3964175/wesnoth-20191214-191749-3964.log)

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/commit/6da85e9042014ec0595f9448937c472be9aa8d9c

@sevu
