### ISSUE TITLE
Backport the unit-test speedups from master?

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4646]
Do we want to backport #4535's optimisations of run_wml_tests to 1.14? The main reason to do so is to make the tests run quickly enough that developers might run them more often.

**Comment by soliton-** [comment]
Are that many developers still working on 1.14? Are there serious bugs left?

To me it seems like it's not worth the effort unless it's perhaps a really simple straightforward change.

**Comment by sevu** [comment]
Do other people run `run_wml_tests` by themselves?

I think it's in practice only used by travis.

**Comment by GregoryLundberg** [comment]
When there's a problem, it's often best to run the WML tests locally and save the intermidable wait for Travis.

For 1.14, the question is not "are there serious bugs" ... of course, there are none THAT WE KNOW OF! The question is how long until 1.16 comes out. If it's going to be years than we can be pretty safe in assuming something major is going to come down the road. But even if not, there will certainly be a long series of minor bugs and having a faster Travis (or local) test run could save a pile of time.

**Comment by stevecotton** [comment]
Hmm - not quite as straightforward as I though. The 1.14 handling of loadstring() shows a deprecation message, and so the cve_2018_1999023 test is run without strict mode; this feature isn't used on 1.15 (the test uses pcall, so it passes as long as strict mode doesn't complain). I have a WIP that would add a specific return code for Wesnoth when a test breaks strict mode (and would otherwise pass), but it's not even got a PR for 1.15 yet.

I'd hope more people would run the wml tests as part of their local build process, but I recall (for a different project) that it's hard to integrate build-and-run-test-script into IDEs.

**Comment by shikadiqueen** [comment]
It was already decided that we need to release 1.14.10 because of bugs affecting Wesnoth 1.14.x on SDL 2.0.10.

**Comment by stevecotton** [comment]
Done in #4666
