### ISSUE TITLE
wesnoth_addon_manager dumps cleartext passphrase

### ISSUE THREAD

**Issue by Chergnobarp** [wesnoth/wesnoth#4651]
### Game and System Information
Running wesnoth 1.14.9 from debian unstable.

### Describe the bug
wesnoth_addon_manager generates a file called packet.dump when it runs. If you're uploading an add-on, packet.dump contains the passphrase from _server.pbl in cleartext. With the default OS settings, packet.dump is world-readable.

Seems to be campaignserver_client.py that actually generates packet.dump, but I don't know python, so I can't say more than that.

**Comment by soliton-** [comment]
I think this is just a debugging aid and can simply be commented out/removed.
