### ISSUE TITLE
[Documentation, tiny change] Could the link on the main README.md towards INSTALL.md be made clickable?

### ISSUE THREAD

**Issue by rubyFeedback** [wesnoth/wesnoth#4655]
Installation instructions are available at:

https://github.com/wesnoth/wesnoth/blob/master/INSTALL.md

If you look at the main README, though, at:

https://github.com/wesnoth/wesnoth

Lots of links work, but this part:

"See INSTALL.md for instructions on how to build the game from source cod"

Does not have a clickable link.

I propose to change the README.md to make INSTALL.md directly
clickable - this is mostly a small convenience change and hopefully
not too difficult to do. Thanks!

**Comment by gfgtdf** [comment]
im not sure, there files are not only for the github webpage, but also for people who download the game, so if we made install.md a link to https://github.com/wesnoth/wesnoth/blob/master/INSTALL.md , that'd probably be for disadvantage for those, if github somehow supports relative  links that could  work though.
