### ISSUE TITLE
Dune Piercer is missing

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#4658]
https://forums.wesnoth.org/viewtopic.php?p=650058#p650058

At some point, Khaiyal was renamed to Dune Piercer https://github.com/wesnoth/wesnoth/blob/master/data/tools/wmllint#L923. However, as of 1.15.2 Dune Piercer does not work either.

**Comment by Earth-Cake** [comment]
Dune Piercer as unit was removed in PR[#4195](url=https://github.com/wesnoth/wesnoth/pull/4195)

**Comment by gfgtdf** [comment]
It woudl make sense that removals also have an entry in  wmlint, enven if you probably cannot fix it automaticially you should make sense to teall addon authors if their code is broken and whta is the suggested fix,
