### ISSUE TITLE
Attempting to start a campaign with no id starts a different campaign instead

### ISSUE THREAD

**Issue by Chergnobarp** [wesnoth/wesnoth#4664]
### Game and System Information
wesnoth 1.14.9 from debian unstable

### Describe the bug
If there's no id in the `[campaign]` tag, the campaign will still show up in the menu, but it will load whatever campaign was previously selected in the campaign menu. It will also retain the description and image of the previously selected campaign. Only the icon and name are displayed correctly.

wesnoth -c errors out properly, thankfully, but that was a very confusing issue.

### To Reproduce
1. Make a copy of a campaign, or create a new one
1. Delete the id from the campaign tag
1. Run wesnoth, try to select and play the campaign.

### Expected behavior
Ideally, the faulty campaign should display an error instead of loading, as it does with preprocessor errors. It also shouldn't display the image and description of another campaign. Alternatively, I could live with the campaign not showing up in the menu, so long as wesnoth --log-debug engine shows something useful.

**Comment by stevecotton** [comment]
> I could live with the campaign not showing up in the menu, so long as wesnoth --log-debug engine shows something useful.

That's easier to implement than a message in the UI. As it's only expected to happen on the campaign-author's PC, I think it can go at log-level "error" so that the message is shown without needing any --log options.

```
20191229 18:22:08 error config: Found a [campaign] with neither a name nor an id attribute, ignoring it
20191229 18:25:18 error config: Ignoring a [campaign] with no id attribute, but name 'Tactics Puzzles'
```
