### ISSUE TITLE
DiD's color_range is unknown to the load save dialog

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#4670]
### Game and System Information
 - What version of the game are you running?
1.15.2
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Steam.
 - What OS are you running?
Windows 10

### Describe the bug
Malin has the wrong teamcolor (magenta?) in the loading save dialog.
(The screenshots and the saves are just examples. This bug seems to be in effect for every DiD save, but not for other saves.)
This issue disappears once you've loaded one of the DiD saves until you close Wesnoth.

### To Reproduce
1. Have a 1.15 save from DiD.
2. Start Wesnoth 1.15.
3. Open the loading saves dialog.
4. Select a 1.15 save from DiD.

### Expected behavior
Malin has the intended teamcolor (dark blue).

### Screenshots
![grafik](https://user-images.githubusercontent.com/39015360/71534752-3b034e80-2901-11ea-8861-805d06b610e9.png)
![grafik](https://user-images.githubusercontent.com/39015360/71534892-16f43d00-2902-11ea-8a15-27f1375b73b7.png)

### Savefiles
[DiD-A Small Favour — Part 3.gz](https://github.com/wesnoth/wesnoth/files/4006398/DiD-A.Small.Favour.Part.3.gz)

**Comment by Wedge009** [comment]
I'm not sure what I'm supposed to look for. I did a quick test with 1.14 release and 1.15.2+dev (with newly saved games for the first scenario) and neither show any indication of team colour for the leader image. For the map preview, the correct team colour for Malin's position is shown in 1.15.2+dev. I suppose it's possible whatever the issue, it was resolved in between 1.15.2 release and current master (c7900c3f).

**Comment by Konrad22** [comment]
This pops up when I open the loading save dialog:

> error display: caught config::error while processing color-range RC: Invalid colour in range: darkblue
> error display: bailing out from RC

Maybe this helps for figuring out whether it has been fixed?

**Comment by Wedge009** [comment]
I didn't see any such message... I will leave further confirmation to someone else who has access to 1.15.2 release, but I assume this means that this isn't a problem in current master.

**Comment by sevu** [comment]
This message is only shown in stderr.

Did uses a custom team color:
https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Descent_Into_Darkness/utils/team-colors.cfg

It's scenario specific stuff, about which the game doesn't know at load save time.
Easiest solution would be to move the color range definition to core.

Linking #4123 as it's also about what to do with the core colors.
