### ISSUE TITLE
EI - Captured - game plan is bypassable

### ISSUE THREAD

**Issue by rjframe** [wesnoth/wesnoth#4674]
### Game and System Information
 - What version of the game are you running? **1.14.9**
 - Where did you download it from? **Archlinux repository**
 - What OS are you running? **Archlinux on kernel 5.3.15**

### Describe the bug

When a guard sees one of the two units not disguised as an orc, it chases after the unit, but no other enemies are alerted.

The enemy leader ignores these units completely except to counterattack when being attacked directly.

This allows a player to pick off each enemy unit individually, then release the prisoners.

### To Reproduce

1. Step within range of a guard
2. Kill the guard.
3. Repeat 1 and 2 until all guards are dead.
4. Free the prisoners.
5. Escape easily, with 0 losses.

### Expected behavior

When one of the two units is seen, the enemy response to the intruders should begin, just as if the disguised unit had moved too close to one of them.

### Screenshots

![image](https://user-images.githubusercontent.com/1379218/71561928-3054d080-2a4b-11ea-9cd7-9eccae729f7b.png)

### Savefiles

[EI-Captured replay.gz](https://github.com/wesnoth/wesnoth/files/4008507/EI-Captured.replay.gz)

The relevant turns are 23 and 39 through 75.

**Comment by Wedge009** [comment]
Sounds like the opposite of what I had playing this scenario some years ago. I prematurely alerted everyone and wound up having my few starting units utterly crushed, it became impossible to complete without reverting to an earlier save file. Perhaps this is a case of the AI being restricted too much instead?

**Comment by stevecotton** [comment]
Can be fixed without any new strings, so valid for the string-freeze; fix will be pushed soon.

**Comment by stevecotton** [comment]
Fixed in #4713 on master, and 98fc1251e61c84c352864fd1d41f3fc36a32c05f on 1.14.
