### ISSUE TITLE
Should help be accessible by F1 in the MP Lobby?

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4685]
E.g. preferences are accessible there. Why not reading the help while lurking in the MP Lobby?

Right, because there is no button for it. Enabling the shortcut nevertheless?

**Comment by GregoryLundberg** [comment]
First reaction: "Yes"

Second reaction: [Betteridge's law of headlines](https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines)

**Comment by CelticMinstrel** [comment]
I think it should be. We could also add a button (if that's easy to do in an inobtrusive way).

**Comment by shikadiqueen** [comment]
I have a feeling the button is never gonna see enough use to justify its presence in a fullscreen UI that's a bit too cramped as it is, but F1 not doing anything sounds like a bug to me.
