### ISSUE TITLE
High CPU usage when playing or observing multiplayer game

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#4696]
### Game and System Information
Wesnoth 1.14.5 from Ubuntu repo.
Ubuntu 18.04.3
CPU Intel i7-3770 (4 cores, 8 threads)
Installed add-ons: `Color Changer`, `Ladder Era`, `Mini Isar`, `Plan Unit Advance`.

### Describe the bug
High CPU usage when playing or observing multiplayer game.

### To Reproduce
1. Open Wesnoth and connect to default Mplayer server.
2. According `htop` there is only 1 Wesnoth process and it's eating 1 CPU thread with ~67% usage.
3. Create map (MicroIsar for example) or join as observer to any running game.
4. According `htop` there are 8 Wesnoth process, and all 8 CPU threads now eating. There is still 1 main process with 50-70% and 7 other with ~50%.

### Expected behavior
Intel i7-3770 is a top desktop CPU for one of previous platforms. So, it's very strange behavior from 1 rather simple game to eat it so hard.

### Screenshots
![wesnoth_high_cpu_usage](https://user-images.githubusercontent.com/10855248/72088875-1b662000-331c-11ea-8116-4e7aa04b1295.png)

**Comment by gfgtdf** [comment]
1.14.5 is not the latest wesnoth version,  this means that if we fix this bug you will probably not benefit from it as if you didn't get the 3 latest versions you probably won't get that version either. It's is reccomended to get wesnoth via steam instead to stay up to date. You version 1.14.5 has also other known bugs such as a crash related to sutom themes that makes some campaigns like "bad moon rising" crash when you play them on 1.14.5

**Comment by gfgtdf** [comment]
Actually it's not unlikely that this was already fixed In a later version, so if you can please test whtger this still happens if you use 1.14.9 (via steam or some other source)

**Comment by soliton-** [comment]
Duplicate of #4130

**Comment by amokmen** [comment]
Could not confirm for 1.14.9 and 1.15.2.

**Comment by Wedge009** [comment]
There's been quite a few performance-related reports over the years, and I've found they're usually hard to track down (at least I couldn't replicate them, aside from maybe the water animation ones). Product of software rendering, I suppose.

At any rate, folks have pointed out there have been recent performance-related fixes and it sounds like you confirmed this with the current releases.

I suspect he dual monitor issue you're observing is related to GNOME rather than Wesnoth.

**Comment by amokmen** [comment]
okay, let's think that was old bug, closing.
