### ISSUE TITLE
pot-update fails on master (fix waiting for a decision about WoV)

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4699]
Trying to build `scons pot-update` fails because WoV has been only partially removed; `po/CMakeLists.txt` still lists WoV and the `po/wesnoth-wov/*.po` files still exist.

Fixing this needs a decision about whether to revert or to complete the partial removal.

@loonycyborg has already fixed the normal build scripts to gracefully recover in 0ab4ecbd8c1f97c0dad90a94a53db424c1a8ad54, but the current behavior of the pot-update script (to error out) is probably the correct behavior for pot-update.

**Comment by shikadiqueen** [comment]
Strictly speaking, fixing this does not necessitate such a decision since the removal of the translation catalogue can be reverted just as easily, and ensuring that our build toolchain is working properly takes priority.
