### ISSUE TITLE
l10n-track and binary path type "" triggers "Conflicting files in binary_path" warning

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4716]
Logging what I've found so far, however it's one where there's a question of which bit is the broken bit. There will be another bug logged after this, asking if l10n-track is used.

### Game and System Information
* Occurs on the current branch heads for both 1.14 and master.
* Does not occur when using language `en_US`. I'm reproducing it when using `de`, and it was originally reported by @Wedge009 who reproduces it with `fr` but not with `en_GB`.
* Seen on Linux, but expected to occur on all OSes.

### Describe the bug
This warning is printed to the console:
    warning filesystem: Conflicting files in binary_path: 'wesnoth_dir//l10n-track' and 'wesnoth_dir/l10n-track'

### To Reproduce

1. Start Wesnoth (it just needs to show the title screen)
2. Change language to something other than en_US

Step 2. is unnecessary if Wesnoth is already in a non-en_US language.

### Additional context
The warning itself was added in #4654 (master) and #4657 (1.14), I guess I only tested in en_US.

The l10n-track file is requested by picture.cpp. The first argument of the function call, `""`, is expected to be the name of a subdirectory such as `images`, `maps`, etc.
https://github.com/wesnoth/wesnoth/blob/3db2fa71e42714176113ff6ed93ce59dcbd14b09/src/picture.cpp#L464

The implementation of get_binary_file_location has a fallback of also considering the root of the user directory and root of the wesnoth data directory, omitting the subdirectory from the path. For example, calling `get_binary_file_location("maps", "filename")` looks for both `<each_binary_path>/maps/filename` and `wesnoth_dir/filename`.
https://github.com/wesnoth/wesnoth/blob/3db2fa71e42714176113ff6ed93ce59dcbd14b09/src/filesystem_boost.cpp#L1330-L1335

Thus passing `""` as the first argument looks for both `wesnoth_dir//filename` and `wesnoth_dir/filename`, triggering the warning.

**Comment by Wedge009** [comment]
Thanks for your efforts. Actually, I was using fr - I checked en_GB and the warning message doesn't appear.

I did, however, confirm both master and 1.14 previously, and I was also testing on Linux. I checked Windows just now and the result is the same (warning on fr but not en_GB) so it doesn't appear OS-dependent.

I haven't checked other languages besides those two.

**Comment by stevecotton** [comment]
Resolved in 1.15.4. The code for l10n-track has been removed in #4722, and all remaining callers of `get_binary_file_location` pass a non-empty string as the first argument.

**Comment by Wedge009** [comment]
Confirmed I didn't see the warning in 1.14 as of 926cae6fedf. Thanks.
