### ISSUE TITLE
Is l10n-track used, and should it be part of the release process?

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#4717]
Bug #4716 is a warning about the way that the l10n-track file is loaded. However, that file was last updated in 2015, although it seems as if it should have been updated for 2018's b24b127ad3f90ed657600ea4cc0e33c5cc814972 and c645a228bf2527c34d9603ac1e896c6eabda4c62.

According to https://wiki.wesnoth.org/ImageLocalization, "A tracker script is run periodically on the repository to indicate that localized images need updating when the original image has been changed or moved."

**Comment by shikadiqueen** [comment]
See <https://github.com/wesnoth/wesnoth/issues/2825#issuecomment-378871430> for more information.

**Comment by stevecotton** [comment]
ping: @Vultraz @ivanovic @loonycyborg 

Thanks for the info, but I can't see a scenario where this fuzziness mechanism would be useful, even when considering the previous times that it was used.

### A screenshot needs to be replaced

In this case the new images are going to be screenshots too. If the old images are out of date, better to just delete them instead of needing the fuzzy mechanism.

### A map is completely redrawn

I can't imagine this scenario happening, but in this case it's probably best to just delete the `--overlay.png` files. The translators are likely to work from the .xcf files anyway.

### A new feature is added to a map

Using the existing overlay file is still going to be good, as it means the rest of the map is shown translated. There's surely new dialogue in the WML files commenting on this new landmark, which would be a good place to say `# po: Lorem's Ipsum was added to the map on 24 Jan 2020, please add a label to your language's --overlay file`.

### An old feature is removed from the map

Using the existing overlay will have an out-of-date label, and the significance of that would depend on how it affects the storyline. This could be significant enough to make showing the English labels be a better option than showing the translated ones. However, the translated maps could be updated without knowledge of the language, so if it's such a significant change then the developer writing the new WML should probably do that.

### A feature moves slightly on the map

This is an example where the l10n-track file has been used, it happened with the Bitter Swamp on the bottom-right corner of the title screen. I think it would have been better to show the slightly-out-of-date overlay instead of showing the English.

**Comment by GregoryLundberg** [comment]
Some game maps have text on them which is localized. Rather than replace the entire map, each word has a small, localized, image which can overlay it. Perhaps that is what this is for.

**Comment by AI0867** [comment]
> It would be far better to eliminate all localization in images and overlay a localized text. This not only places the localization into the normal stream, but also reduces requirements and allows for consistent presentation.

Given that many images in the help are screenshots, and maps contain stylized text that may have to be carefully placed, this seems unfortunately impractical.

The point of the 'fuzzy' status is, I believe, less that the localizer can reuse his work (in some cases he can, but in many cases he cannot), but that the image is marked as no-longer-up-to-date automatically, without the editor of the original having to either delete the localized version or manually mark it as outdated in some way.

**Comment by shikadiqueen** [comment]
Game screenshots in the help could be dealt with using WML tstring localization, unique filenames for each new version of the screenshots, and simple instructions for game devs who decide to update the American English version of the screenshots.

Honestly I'm not keen on this whole business, especially when it comes to art (the world maps). It places an unnecessary burden on translation maintainers that to my knowledge is completely unique to Wesnoth. Not to mention that we still don't have an automated process to update the file in our build systems — clearly I forgot to do something with the information I dug up back then and I'm not sure I'm willing to deal with this business now.

**Comment by stevecotton** [comment]
> The point of the 'fuzzy' status is, I believe, less that the localizer can reuse his work (in some cases he can, but in many cases he cannot), but that the image is marked as no-longer-up-to-date automatically, without the editor of the original having to either delete the localized version or manually mark it as outdated in some way.

Okay, I should have added a conclusion to my scenarios: automatically marking the images as fuzzy is in general the wrong thing to do.
* Screenshot needs to be replaced - there's a slight gain from the feature, equal to deleting the translations
* Map completely redrawn - unlikely to happen, more likely that a separate new map would be added
* New landmark on map - auto-fuzziness is bad, the unrelated parts of the map revert to English
* Landmark removed from map - whether auto-fuzziness is good or bad depends on the details
* Landmark moved slightly - auto-fuzziness is bad

Conclusion: even if this feature worked perfectly, it would be worse than not having it.

**Comment by loonycyborg** [comment]
I'm of same opinion of this feature as @shikadiqueen . In fact I don't think that providing localized copies of entire images would ever be a good idea. I think it would be better to have any images with text in them in vector format such as .svg and feed them to existing po4a infrastructure.

**Comment by stevecotton** [comment]
I've created #4722 to remove this feature from the master branch, and #4721 to avoid the #4716 warning on 1.14. Please could I have review comments on those?

**Comment by Pentarctagon** [comment]
If you're looking for reviews from specific people, requesting a review over on the PR would be best, or perhaps pinging them on Discord.

**Comment by shikadiqueen** [comment]
The code in #4721 looks fine to me.

However, it only just dawned on me that the existence of the feature means that the game is looking up files in more directories than the first match. I'm fairly sure that is no cause of concern by itself, but then you realize that:

1. `stat()` operations are not guaranteed to be fast.
2. Wesnoth loads a huge number of resources in an as-needed fashion, in particular images.
3. There can be any number of binary paths registered at one particular time, especially in multiplayer.

Was it really necessary to make the warning not exclusive to debug mode in the first place?

**Comment by stevecotton** [comment]
While they're not guaranteed to be fast, it seems a reasonable expectation that the OS will cache directories that the application is using. Have you seen performance problems?

It's going to be OS-specific, but I tried running an Ageless SXC replay and according to strace the total time spent in stat was 0.4 seconds (with no time spend in readdir or getdents).

If code's enabled in debug mode then (except for the logging function's implementation itself) I prefer to have the same code path being used in non-debug mode, simply because debug mode should match what happens in non-debug mode.

**Comment by shikadiqueen** [comment]
> While they're not guaranteed to be fast, it seems a reasonable expectation that the OS will cache directories that the application is using. Have you seen performance problems?

Not as of late, although I used to observe I/O-bound frame drops during animations with too many cache misses back in the day.

> If code's enabled in debug mode then (except for the logging function's implementation itself) I prefer to have the same code path being used in non-debug mode, simply because debug mode should match what happens in non-debug mode.

That's your personal preference showing. Debug mode already results in different behaviour in several areas, including the default logging level for WML deprecation notices, and the image-not-found placeholder being retrieved by the image cache API instead of a null surface.

**Comment by stevecotton** [comment]
Done in #4722. There's still a question of whether #4654 should be made debug-only for performance.
