### ISSUE TITLE
Desktop notifications ignore current game filter

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#4723]
### Game and System Information
 - windows steam 1.14.9

### Describe the bug
After adding game filter by text, I still get notification about game I will not see after switching to wesnoth - example https://i.vgy.me/lbp2Hb.png

### To Reproduce
- Add game filter which would not match newly created game
- Switch to different program
- Create new game from different computer

### Expected behavior
No desktop notification since created game does not match filter

### Screenshots
https://i.vgy.me/lbp2Hb.png

**Comment by Pentarctagon** [comment]
Removed those tags since it happens on Linux as well.

**Comment by drewdaemon** [comment]
It looks like a PR got merged for this one: https://github.com/wesnoth/wesnoth/pull/5261. Does it make sense to close the issue?
