### ISSUE TITLE
Desktop notifications show literal markup

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#4724]
### Game and System Information
 - Same as #4723

### Describe the bug
Notifications show markup such as `<b>` https://i.vgy.me/bS2Ihp.png

### To Reproduce
Same as #4723

### Expected behavior
Notification does not contain `<b>`

### Screenshots
https://i.vgy.me/bS2Ihp.png

**Comment by Pentarctagon** [comment]
Removed those tags since it happens on Linux as well.
