### ISSUE TITLE
Using Travis' Windows support instead of AppVeyor

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#4727]
Since Travis has early support for running Windows builds (and the master branch currently makes use of this to run jobs with VS2017), I'm wondering what would be needed for Travis' Windows support to be considered equivalent to AppVeyor's.  At that point we could stop using AppVeyor, and have everything using Travis, instead of using both Travis and AppVeyor as currently is done.

Benefits I see from this:
* AppVeyor's web hook to Discord isn't set up (or is disabled?), so there isn't a notification if it fails, whereas Travis does have this notification.
* In Travis I was able to implement a fairly simple script to support partial builds, so the Travis Windows jobs complete much faster than the AppVeyor ones.
* We'd only have to rely on one CI provider rather than two.
* AppVeyor is much more aggressive than Travis in cancelling jobs, and when that happens it makes it look like the automated builds experienced a failure rather than it just being AppVeyor cancelling something (when looking at the commit history on Github).

**Comment by gfgtdf** [comment]
a disadvantage of this would be that the total time for everythign to pass wil be longer since appveyor and traivs can run at the same time while, the amount of parallel travis builds is limited.

Oh and more importantly, appveyor currentl does generate downloadable windows builds that i can give people to test if i really need to, afaik travis (at least in our current configuration does not do this)

**Comment by Pentarctagon** [comment]
For the majority of the time, partial builds due to caching makes the difference somewhat less.  For the most recent commit where both [Travis](https://travis-ci.com/wesnoth/wesnoth/builds/146312463) and [AppVeyor](https://ci.appveyor.com/project/wesnoth/wesnoth-7lnpw/builds/30392852) completed for example, Travis' total run time was ~47 minutes while AppVeyor doing a full rebuild of the Release configuration was was ~36 minutes.  Additionally, the xcode build runs last but also takes the longest (no idea why), so moving the macOS jobs to run earlier would probably make the difference even less.

By downloadable windows builds, do you mean an entire installer, or the executables?

**Comment by GregoryLundberg** [comment]
IIRC AppVeyor can build a Windows Installer, but not the one we use. WiX or something like that. It's been a while and didn't seem worth the bother.

**Comment by Pentarctagon** [comment]
From discussions on Discord, SourceForge would work as a place to upload executables to from travis.

**Comment by Pentarctagon** [comment]
Given [this commit](https://github.com/wesnoth/wesnoth/commit/656737e6c9c108c638fe30885c5c9ec5450eb618), is there anything else that would need to be covered?
