### ISSUE TITLE
[Feature request] Consider adding a way to show how far (and where) a single unit can move in general.

### ISSUE THREAD

**Issue by rubyFeedback** [wesnoth/wesnoth#4729]
Hello wesnoth team,

Right now if we click on on of our own units, a grid is shown where we can move that unit. This is good for planning ahead, e. g. position certain units at certain positions.

We currently do not have this functionality available for enemy units. I have to manually count e. g. if the unit can move 5 hex fields, then I position my own unit sometimes one extra field distance away from this.

This is a bit cumbersome, but not a big deal.

However had, just now when playing an unusual campaign, there was a new unit, and that unit had skirmisher ability, so it ran through my sparse defence, hitting a weak unit. This was evidently me miscalculating it. So I think that this feature suggestion may be useful for this scenario at the least.

Implementation:

I do NOT suggest to make this the default. The default may stay as it is. But I would like to add the FUNCTIONALITY. One way to add this is via the right mouse button click, when it shows that menu, to add a new entry, let's call it "show possible movements" or just "possible moves" or something along those lines.

The functionality is already existing somewhere as-is, as we see this for our own units, just not for enemy (or allied) units. So the code-requirement should not be too high (I am really bad with C++ so I am not sure where the functionality is, though). Thanks for considering! Please comment if you find this a good or bad suggestion too.

**Comment by Pentarctagon** [comment]
I'm fairly sure that hovering over a unit shows where it can move to.  Is this different from that?

**Comment by doofus-01** [comment]
There's also an option to see all enemy-reachable hexes, with a count of how many enemies on each hex.  Default is Ctrl+v, I think.

**Comment by Pentarctagon** [comment]
Closing due to lack of info on the feature.
