### ISSUE TITLE
Put the timestamp in save file names

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#4730]
From comments by specing a couple days ago:
```
<specing> "Save already exists. Do you want to overwrite it? Name ... replay"
<specing> played two MP games in a row
<specing> Can't you put the timestamp into the file name?!
```

The FR then is to make it so that save files have the date and time of the save in the file's name(ex: 01/01/20-00:00:00), so that replays don't always ask the user about whether or not they want to overwrite the replay file.

**Comment by shikadiqueen** [comment]
`YYYYMMDD-HHMMSS` would make more sense. In particular, colons are not allowed characters in filenames on Windows.

**Comment by Wedge009** [comment]
Definitely agree with that suggestion both for auto-sorting reasons, and also unambiguity with respect to regional conventions. I shudder whenever I see dates in file names as DDMMYYYY, or even worse, MMDDYYYY, but neither of those can be sorted easily by file name.

As for punctuation, well, that is dictated by what's permissible in file names, which differs between OSs. Best to keep it simple.

**Comment by GregoryLundberg** [comment]
I'd add preferences:

* Always overwrite save files
* Add timestamp to save file names

**Comment by AI0867** [comment]
Any particular reason to not always prefix the filename with a ISO8601/RFC3339 datetime stamp? Options Are Bad.

**Comment by Wedge009** [comment]
I am aware of ISO 8601 and am fine with the 'T' separator but I don't think many people are familiar with it so I think the suggestion to use a hyphen instead was a suitable compromise. I would also favour time-stamp as the suffix rather than a prefix.

Regardless, the primary principle of arranging the characters of a time-stamp from greatest to least significance is crucial in natural sorting.

**Comment by gfgtdf** [comment]
i don't think natural sorting is that big of an issue, iirc the wesnoth loadgame dialgo sorts by date already anyways and any manager can also sort by date. Furthermore we will probably add a filename to the end of the filename to enable sorting by campaign name for example.

**Comment by Wedge009** [comment]
Just because it can be done via file date sorting is no reason to regress to badly-formed file names. At any rate, I would think things like campaign names would take precedence over the time-stamp, hence why I thought the time-stamp should be a suffix rather than a prefix.

**Comment by Pentarctagon** [comment]
Given that the save files are already sortable by date, I don't think putting it on the front of the file name makes sense.  I agree with there not being a need to make this a preference though.

**Comment by gfgtdf** [comment]
Yes that's what I was typing to say, had a few wrong words in my text
