### ISSUE TITLE
Chat area scrolls to top

### ISSUE THREAD

**Issue by haytham-med** [wesnoth/wesnoth#4733]
### Game and System Information
 -  1.14.11
 - Where did you download it from?  Steam
 - What OS are you running? Ubuntu 18.04

### Describe the bug
Chat area in lobby scrolls from bottom to top in certain occasions.

### To Reproduce

1. First.. Create a game then chat till scroll bar appears
2. Then...New user joins / user changes leader [not sure exactly what triggers it]
3. Lastly...Chat area scrolls upwards to top.

### Expected behavior
Chat area keeps at bottom / last line written

### Screenshots
need a GIF, could make if no one experienced it.

**Comment by Wedge009** [comment]
I was sure this, or something like this, was reported before. But the closest I could find was #2789, which is already marked as closed. Is your experience anything like what's described there?

**Comment by sevu** [comment]
Seems it happens when a game is removed from the list of games in the lobby.

**Comment by Wedge009** [comment]
Sounds like a redraw of the whole lobby when an event like that happens (and the scroll to the top is part of the redraw).

**Comment by mesilliac** [comment]
I think this might be fixed in 1.17.6. Can anyone confirm one way or the other?

**Comment by Wedge009** [comment]
Observing for well over half an hour in release 1.18.0, I couldn't replicate this outside of things I did myself (such as resize the window). Other things, such as people joining the lobby, games added, etc, happened during this time. Replicating #1197 did not reset the chat.

Please re-open if anyone else still observes this happening.
