### ISSUE TITLE
Liberty story nitpicks

### ISSUE THREAD

**Issue by IskarJarak** [wesnoth/wesnoth#4747]
@nemaara 

Places for story improvements on current master.

### Scenarios 1 - 3
The orcs in scenario 3 are implied to belong to Asheviere and also to actively seek revenge for the orcs beaten in scenario 1. In the middle of both events, Wesnothian forces come to Dalben to collect the mayor. The narrative doesn't imply a relevant distance in time of these events, which makes it weird that they are not connected. If orcs paid to harrass the villagers are in the vicinity, I'd expect a little more coordination with such an official visit - maybe he should argue using the orc threat, maybe the orcs in scenario 3 are actually hired in retaliation for # 2 but are motivated by revenge for # 1? Anyway, a little more connective tissue (even just a narrator implying time passing bye - of which we have very little sense currently - would help).

### Scenario 7
Narrator:

> This sentinel of the western plains stood watch as Wesnoth prospered for many centuries under its protection. No war has overcome it, and its walls have never been overrun. The blood of invaders stains its parapets and the bones of the defeated crumble at the base of Halstead’s frozen waves of stone.

Helicrom:

> the mountain on which the fort was built is solid, but the castle on top has been built and rebuilt many times over the ages. It is not as indestructible as you might think.
> [...] Over time, after many wars, supports were required to hold up the middle.

- Raiders rarely attack a fortification, at least not one so big and mighty. They go for the vulnerable targets. The text implies that Halstead has seen quite a few actual invasions - west of the Wesnoth heartlands. That is like, the least likely place for any invasion to reach. This alone is still minor, however, Helicrom supplementing this ("many wars") doesn't help.
- In the same vein: why is there suddenly on orc raid _on friggin Halstead_ while the Wesnothians are busy with each other, the Hinterlands are mostly unprotected, and all orcs in the campaign beforehand where linked to Asheviere? I think we need either more explanatory work why Halstead, _despite_ all we know, would still be an attractive target or this needs to be toned down considerably. Either way, the orcs need better motivation than the one given (maybe not for _being there_, but certainly for engaging in battle instead of turning around). The orc army is even called "small" in scenario 8.
- Helicrom's text on the castle rebuild is also problematic. We have stone castles still standing after hundreds, sometimes thousands of years all over Europe (and in other parts of the world). They also usually do not get "a lot" of tearing down and rebuilding (in contrast to cities, even fortified ones) - especially mountain castles that never fell to outside invasion or natural catastrophe. We have less than 350 years between the building of the castle and the scenario. I'd suggest to change the dialogue here.
- Scenario 8:
> He [the Wesnothian army commander] quickly retreated to the traditional border and set up a strong defense against the west.

This line makes no sense whatsoever. Pretty much all the campaign played on Wesnoth's soil. North, west, south, all around Halstead is Wesnoth's domain until oceans / forests / great rivers, except for the _city state_ of Elensefar...

Edit: removed accidental linking of PR's 1 and 2...

**Comment by nemaara** [comment]
I've revised all the dialogue in Liberty. You can reopen if you decide to review it and find something then.
