### ISSUE TITLE
editor crashes when a scenario is loaded with [item]s but not [side]s

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4755]
as asid in the titel, when  try to load a scenario (that was created with the map editor) that contains itmes but no sides wesnoth crashes with a segfault. i don't really know hwo to debug on this linux computer so i cannot give a stacktrace yet.

happened on both 1.15 and 1.14

**Comment by UnwiseOwl** [comment]
This also occurs when placing items in a scenario with no sides. To reproduce:

1. Open any map.
2. Save as scenario.
3. Place item.

**Comment by gfgtdf** [comment]
> This also occurs when placing items in a scenario with no sides. To reproduce:

If you are on current master, could you check.whther it fails the the assertion expression that I added a month ago or with a different message?

**Comment by UnwiseOwl** [comment]
Sorry, I'm not. I'm on the current steam beta 1.15.3.

**Comment by gfgtdf** [comment]
this this was helpful
