### ISSUE TITLE
[Small feature request] Add a new (additional) entry in the add-ons listing, for "n scenarios" in a campaign

### ISSUE THREAD

**Issue by rubyFeedback** [wesnoth/wesnoth#4756]
Hello wesnoth team,

I have a small feature to suggest.

In the "Add-ons Manager", when you selected a campaign, on the bottom-right area,
I would love to see a new entry that displays how many scenarios are part of the campaign.

Example:

**"Campaign name: Big Girl"
"Scenarios: 13"**

Reasoning:

I prefer campaigns that take some time, say, +10 scenarios. Some campaigns from the
add-ons have fewer than that and I'd like to skip that or simply see how many 
scenarios there are.

**Some campaign-authors add this in the description of their campaign, on the top right side
in the add-ons manager widget, but this is optional, and some other campaign authors do not.**

I do not know where or how a campaign is described; probably in some XML file
or so, and this can be OPTIONAL, to achieve 100% backwards compatibility.

Active authors of an add-on campaign may add that entry, which could
then be displayed to the user, which I think would be nice.

That's the suggestion. :) It's really small - I guess perhaps you may want to
discuss whether this would be a good idea, but I think it is, since right now
we don't know how many scenarios are part of a campaign; at the least
not from within the add-ons manager. Thanks for reading.

**Comment by gfgtdf** [comment]
First, recall that not all addons are campaigns, some are also mp eras modifications or mappacks. But from now on lets talk about campaigns only.

The wesnoth game/server cannot easily tell how long a campaign is, it could _maybe_ (actually: probably not really) count the number of  [scenario] tags in your campaign but even that could also 
 be misleading: for example WC2 from the 1.14 addon server contains 15 [scenario] tags but actually the campaign is just 5 scenarios long and it has versions for 1,2 or 3 players. So the only way to do this would be to make the addon author tell us this (that is: adding a field scenario_count in _server.pbl) and  they could leave that one out if they wanted to.


So yes we could do this and i'm not against it, but just as right now it probably won't cover all campaigns.

**Comment by Pentarctagon** [comment]
Campaigns with multiple paths, where different paths have different numbers of scenarios, would be another case where it would be essentially impossible for the add-ons server to automatically figure out a scenario count.

**Comment by sevu** [comment]
… would be impossible to figure it out manually too, as the paths can have different lengths.

**Comment by Wedge009** [comment]
#3183 requests something similar but for the standard campaigns. Nonetheless, it also goes into some explanation why determining the number of scenarios isn't a straightforward calculation.

**Comment by cooljeanius** [comment]
> Campaigns with multiple paths, where different paths have different numbers of scenarios, would be another case where it would be essentially impossible for the add-ons server to automatically figure out a scenario count.

Yeah and some campaigns don't even use a consistent numbering scheme for when they do this; I'm thinking of "A New Order" in particular here... also "Saving Elensefar" probably, too...

**Comment by Pentarctagon** [comment]
It sounds like this can be closed as not being possible to implement?

**Comment by Wedge009** [comment]
I'm in favour of closing as many issues as is reasonable, I'm just wondering if 'not possible' is too strong a judgement here.

An alternative I just thought of is to institute a minimum and maximum number of scenarios. The main problem I see is ~forcing~ encouraging campaign maintainers to actually keep accurate counts in their campaign packages. We would need to do the same for official campaigns too, of course.

* If min_scenarios and max_scenarios present:
  * If min == max: display either as scenario count
  * Else (If max > min): display min-max scenarios
  * (What to do if min > max, which is obviously wrong? Perhaps step back to handling where they are not present...)
* If either min or max is missing, step back to an 'estimate' of some sort. Maybe raw count of scenario files? And display ~X scenarios in campaign.

I dunno, maybe too much effort to be really useful. In which case, go ahead and close as 'won't fix'.

**Comment by Pentarctagon** [comment]
It seems like there are two situations here:
* Programmatically determine how many scenarios a campaign has - this isn't possible to do reliably.
* Have the campaign author state explicitly how many scenarios are in a campaign - I'm not sure how likely this would be used or what the benefit would be compared to today where they can state the number of scenarios in the add-on's description.

**Comment by Wedge009** [comment]
I had a quick look through some add-on campaigns and it looks like many authors will but the number of scenarios in the description. Some will include dialogue-only scenarios in the count but also mention how many such scenarios are included. Others include mention of an epilogue (a special-case dialogue-only scenario). Some seem to implement some sort mechanic where number of scenarios vary widely (I saw one say 7 to 26 out of a total 144). Some are works-in-progress, with a set number planned but only some implemented.

So it just seems infeasible to accommodate every possible combination/possibility. For the amount of effort required, it doesn't seem very useful (to me) other than being able to sort by (approximate) scenario count. If someone were to make a case for a reasonable implementation, however, I'm sure we can re-open this.
