### ISSUE TITLE
[modify_unit_type] – usage and limitations?

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#4762]
Fro the documentation:
> Changes a unit type while this modification is active. This tag is also supported in [campaign] and [era].

However, placing that tag in [era] or [modification] or [campaign] throws the error message:
> not supported at scenario toplevel

https://github.com/wesnoth/wesnoth/blob/master/data/lua/core.lua#L506

The unit type being modified was a umc one.

Related: #4099
IIRC [unit_type_fix] was renamed to [modify_unit_type]. Using tag [unit_type_fix] does nothing, also not triggering an error.

**Comment by gfgtdf** [comment]
> However, placing that tag in [era] or [modification] or [campaign] throws the error message:

this sounds like a bug. the name is probabl just missing in this list https://github.com/wesnoth/wesnoth/blob/master/src/scripting/game_lua_kernel.cpp#L4515

**Comment by gfgtdf** [comment]
im unsure whether calling `error` is really the best way to handle bad usage of `wesnoth.persistent_tags`, since it means one addon misusing `wesnoth.persistent_tags` will also breask other addons code, maybe the author of that code @CelticMinstrel  has an opinion on this.

**Comment by gfgtdf** [comment]
that said, does it still work? mean even with that error message, does the unit type get updated  properly?

**Comment by gfgtdf** [comment]
okay pushed a commit that shodul fix this

**Comment by sevu** [comment]
Currently compiling
Line 4515 needs a change to, otherwise:
> src/scripting/game_lua_kernel.cpp:4540:2: Fehler: zu viele Initialisierer für »std::__array_traits<std::__cxx11::basic_string<char>, 23>::_Type« {aka »std::__cxx11::basic_string<char> [23]«}

**Comment by gfgtdf** [comment]
okay i pushed a fix for the compilation error

**Comment by sevu** [comment]
Tested it and it works as expected.

This opens up one new possibility:
Add-ons can define units which advance from or to units from elsewhere, while not messing with other add-ons.
How to tell that to people is another story though.

Can [advancefrom] be deprecated?

**Comment by ProditorMagnus** [comment]
#3955

**Comment by gfgtdf** [comment]
> Can [advancefrom] be deprecated?

hmm yes but we should remove all mainline usecases before we do this
