### ISSUE TITLE
[Feature Request] Make it possible for the player/user to disable certain add-on effects

### ISSUE THREAD

**Issue by rubyFeedback** [wesnoth/wesnoth#4766]
Hello wesnoth-folks,

Some add-ons add fancy effects. Many of which are cool; some are a bit annoying,
though - in particular rain.

Visually it is nice, but it lags a LOT. It slows down everything to the point of me
having to wait for units to move, even at maximum speed.

Some campaign authors provide means to disable this, via right click menu.
Other campaign authors do not.

I would thus like to propose to allow this to work for every add-on campaign,
so that we as users (as players) can toggle these effects. This could be an
extra widget, or it could be a right-click context menu action, I have no 
preferences here.

I do not know how the code would or should have to look for this,
but I guess we could simply take the code that already exists in some
campaigns (one I remember that has this functionality is the one where
you defend against some hydra-thingies and in the middle of the map
is a large castle-setup where you could use djinni to build it up too).

The add-on that I am currently playing does not allow for me to get
rid of the rain effect, so this is annoying. It sort of spoils that campaign.

Note that there could be other solutions, such as rain-effects becoming
much cheaper to calculate rather than incur this constant lag - but 
this may take more time to implement, so perhaps a faster ad-hoc 
fix could help here. I guess a simple context-menu action for us
to disable/enable this should be fine.

**Comment by ProditorMagnus** [comment]
There is no way for wesnoth to know if something is that kind of special effect. It can only be solved by communication.

**Comment by soliton-** [comment]
If you’re asking for a rain feature to be added to mainline and a preference to turn it on/off please clarify and change the issue title.

Otherwise there is no way for wesnoth to automatically discover/disable/transform arbitrary code portions of addons that constitute what you consider certain effects and as you note addon authors can already provide the options you want.

**Comment by Wedge009** [comment]
@rubyFeedback This looks very similar to #4208, which is also one of yours. If I'm wrong, please re-open and clarify what's different in this request.
