### ISSUE TITLE
Add "The Battle for Wesnoth" to the credits page

### ISSUE THREAD

**Issue by UnwiseOwl** [wesnoth/wesnoth#4767]
When the credits scroll following a campaign, the title of the campaign is shown followed by the campaign credits, then the normal game credits run, but they're easily confused as there is no differentiation between the two.

This could be easily fixed by adding a 'The Battle for Wesnoth' title header before the main title credits in the same typeface as the campaign title.

**Comment by stevecotton** [comment]
Resolved in #5186 - the outro screen now shows the credits for the campaign and then returns to the title screen without showing the main credits.
