### ISSUE TITLE
Remove new mushrooms terrain and remove composite terrain properties from the old mushrooms

### ISSUE THREAD

**Issue by ElderoZ** [wesnoth/wesnoth#4771]
Too long for github so I created a forum thread.

https://forums.wesnoth.org/viewtopic.php?f=15&t=52090

**Comment by stevecotton** [comment]
I've replied in the forum thread about the difference between `^Uf`,`^Tf` and `Tb`. Labelling 'more info', as I think the issue is waiting on @ElderoZ to update the description based on `^Uf` and `^Tf` being separate terrains.

**Comment by ElderoZ** [comment]
I clarified some things in the post, added some terrain markers and paragraphs, also clarified what I think about old deprecated ^Uf.

**Comment by Pentarctagon** [comment]
Closing, given the mushroom transition isn't getting reverted (again) at this point.
