### ISSUE TITLE
Stop using multiple AI [avoid] tags

### ISSUE THREAD

**Issue by UnwiseOwl** [wesnoth/wesnoth#4775]
AI sides can only have one instance of each aspect at once.
There are eight places in mainline where campaign scenarios attempt to use multiple concurrent [avoid] tags. In these situations, the AI will only obey the last tag. We should campaigns to use only one tag per side where possible.

These scenarios are:

- [x] 1. Delfadors_Memoirs\12_Terror_at_the_Ford_of_Parthyn
- [x] 2. Eastern_Invasion\17a_The_Duel
- [x] 3. Heir_To_The_Throne\07_Crossroads
- [x] 4. Heir_To_The_Throne\11_The_Ford_of_Abez
- [x] 5. Legend_of_Wesmere\09_Bounty_Hunters
- [x] 6. Son_Of_The_Black_Eye\14_Back_Home
- [x] 7. Under_the_Burning_Suns\06a_In_the_Tunnels_of_Trolls
- [x] 8. Under_the_Burning_Suns\06b_In_the_Domain_of_Dwarves

It's possible this problem is also affecting other ai aspects, though [avoid] seems to be the most commonly used.

Looks like this has been previously reported as #1271.

**Comment by Pentarctagon** [comment]
@CelticMinstrel Would this be something that could be added to the WML schema validation?

**Comment by Earth-Cake** [comment]
I did a quick check. `[avoid]` tag accepts form:
`[avoid]
    x=
    y=
[/avoid]`
in which you can list locations you want ai to avoid.

**Comment by UnwiseOwl** [comment]
Now that I have a better understanding of this I don't think it's very likely that any of the other aspects will have been accidentally called more than once. I suspect [avoid] is the only one we have to worry about.

**Comment by mattsc** [comment]
Yeah, I'd agree that that's unlikely.  It's pretty obvious that aspects like aggression cannot be simultaneously set to several different values.  It's just that `[avoid]` "feels" like it should stack.  It might be worth specifically stating this on the wiki for the avoid aspect.

**Comment by UnwiseOwl** [comment]
I'd added a note to the aspects section header already, but I've just duplicated it in the [avoid] bit. Can't say we haven't warned them now.

**Comment by UnwiseOwl** [comment]
The outstanding case in DM here is solved as part of #4774.

**Comment by CelticMinstrel** [comment]
@Pentarctagon - No, I don't think it could be encoded into the schema. First of all, multiple `[avoid]`s are perfectly valid. If you have more than one, they *are* all added to the AI, and while the AI will only use the last one, you could have an event that removes the last one, making it fallback to the previous one. So there are valid reasons to have multiple `[avoid]`s as long as you know what you're doing. Secondly, if you use the extended syntax (or multiple `[ai]` tags), you can have multiple `[avoid]`s for different turns or times of day, and the AI will automatically choose the last one that matches the current turn.

Besides `[avoid]`, the only aspects that someone might be likely to get wrong here are `[leader_goal]` (but I don't think that aspect sees much use) and `[attacks]` (though that doesn't have a simplified form). It's *technically* possible to make the error with any aspect, if you use extended syntax, for example:

```
[aggression]
    turns=2,5,7
    value=0.2
[/aggression]
```

(The full syntax, using an `[aspect]` tag, could also cause the issue. Note that the `[attacks]` aspect only exists as extended syntax, but is typically used without any conditions.)

However, if you're doing that, you probably understand how the conditions work, so… I think it's less likely you'd make the mistake.

**Comment by AI0867** [comment]
I think part of this issue is that `[avoid]` *predates* the RCA system. I don't know if multiple `[avoid]` tags worked before then, but they probably did.

**Comment by sigurdfdragon** [comment]
Final item fixed in 0e4a35da8c7951b8577b78690498e6b72ef2cfac
