### ISSUE TITLE
DiD, Descend into darkness, A Small Favor - Part Two, Lua error, no units available

### ISSUE THREAD

**Issue by pvanek** [wesnoth/wesnoth#4778]
### Game and System Information
```
Name        : wesnoth
Version     : 1.15.1
Release     : 1.3
Architecture: x86_64
Install Date: Sun 12 Jan 2020 05:02:54 PM CET
Group       : Amusements/Games/Strategy/Turn Based
Size        : 20438699
License     : GPL-2.0-or-later AND EPL-1.0
Signature   : RSA/SHA256, Sat 16 Nov 2019 06:27:16 AM CET, Key ID b88b2fd43dbdc284
Source RPM  : wesnoth-1.15.1-1.3.src.rpm
Build Date  : Sat 16 Nov 2019 06:13:35 AM CET
Build Host  : lamb11
Packager    : https://bugs.opensuse.org
Vendor      : openSUSE
```

### Describe the bug
Entering the manor in Part One without killing the general leads in the situation when there are no recruited units available in the manor itself.
Lua error stacktrace is printed into the screen.

### To Reproduce
Just end Part One scenario

### Expected behavior
My units are needed ;)

### Screenshots
![wesnoth_lua_error](https://user-images.githubusercontent.com/207237/75629999-4e73b400-5be7-11ea-939c-d5c796d84b23.png)

### Savefiles
[saves.zip](https://github.com/wesnoth/wesnoth/files/4272136/saves.zip)

### Additional context
n/a

**Comment by gfgtdf** [comment]
this is probably fixed already by https://github.com/wesnoth/wesnoth/commit/3772e633fae7e87146534eb781b2ab9dfec69486

**Comment by Wedge009** [comment]
Quite possibly, as I don't have this issue in master, 1.15.2+dev (f2324a2b).

**Comment by pvanek** [comment]
tested with d2bb3fb1033d456159ac680450f9efd9b3f635f1 and all works. Thanks and sorry for a false positive.

**Comment by Wedge009** [comment]
No worries, thank you for confirming the issue is no longer present.
