### ISSUE TITLE
Keeps crashing when menu items pressed twice

### ISSUE THREAD

**Issue by michio3483** [wesnoth/wesnoth#4786]
### Game and System Information
 - What version of the game are you running? -iPhone, HD
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) Mac App Store
 - If you're using a custom build, what compiler did you use, and what commit did you build at?n/a
 - What OS are you running? iOS 13.3.1

### Describe the bug
A clear and concise description of what the bug is.- the app keeps crashing when you tap a menu item multiple times.  When you tap item first time, it often does not respond.

### To Reproduce

1. First.. enter tutorial mode. When you try to recruit, it sometimes doesn’t respond.
2. Then... if you press recruit again, the system crashes
3. Lastly...when you open up again, program starts over from beginning.

(If you are in game mode and try to change preferences, it often does same thing).

### Expected behavior
A clear and concise description of what you expected to happen. Do action requested on first attempt.  Not crash

### Screenshots
If applicable, add screenshots to help explain your problem. NA

### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

**Comment by michio3483** [comment]
Do you know if the non-HD version of the game has less issues?  If so, would it be possible to switch without paying $3.99 again?

**Comment by cooljeanius** [comment]
> Do you know if the non-HD version of the game has less issues? If so, would it be possible to switch without paying $3.99 again?

The iOS app should be available to download for free now, since it's no longer being updated.

**Comment by Wedge009** [comment]
@Pentarctagon Given your remark about iOS in #8833 and cooljeanius' remark above, is this one still valid?

**Comment by Pentarctagon** [comment]
I'm not sure any iOS-specific issues make sense to keep open at this point. Any new iOS version would essentially be a fresh port unrelated to the "current" 1.14 ported version and there's essentially no chance any issues with the current port will ever be fixed.

**Comment by Wedge009** [comment]
That's what I understood on the basis of your other remarks.
