### ISSUE TITLE
Scenario editor can crash if units are placed on same hex

### ISSUE THREAD

**Issue by UnwiseOwl** [wesnoth/wesnoth#4789]
### Game and System Information
 - 1.15.2 and 1.14.9
 - Steam
 - Windows 10

### Describe the bug
Scenario editor crashes on opening a new scenario after trying to place units from different sides on the same hex.

### To Reproduce

1. In the map editor, open a new or existing scenario.
2. Place a unit on side 1.
3. Attempt to place a unit on side 2 on the same hex.
4. Open a new scenario.
5. Crash!

### Expected behavior
Open new scenario, keep old scenario open.

### Additional context
Log contents:
Setting mode to 1536x864
Checking lua scripts... ok
20200306 22:50:35 warning engine: Invalid anchor!
20200306 22:50:35 warning engine: Invalid anchor!

**Comment by UnwiseOwl** [comment]
Actually: expected behaviour would be that any new unit placed would replace the old one like new terrains do in the map editor, nicely skipping this issue.

**Comment by Pentarctagon** [comment]
Does this still happen with 1.14.11?

**Comment by UnwiseOwl** [comment]
Yes.
