### ISSUE TITLE
Error in get_selected_item in multiplayer lobby

### ISSUE THREAD

**Issue by capgelka** [wesnoth/wesnoth#4792]
### Game and System Information
 - Game version: 1.14.11
 - Downloaded from steam
 - OS: Manjaro Linux Release 19.0.2

### Describe the bug
I was online in the wesnoth multiplayer lobby. After a few hours AFK I saw an error message:
"Unconditional failure at src/gui/widgets/generator_private.hpp:681 in function get_selected_item".
Extra development information: selected_item_count_ was non-zero, yet no selected item was found.

After pressing "Enter" I got to the main menu.

I have no idea how to reproduce this. Probably there may be some connection issue, my internet access is not stable.

### Screenshots
![wesnoth-2020-03-08_02-52-35](https://user-images.githubusercontent.com/5390251/76154301-2f938700-60eb-11ea-91a8-1d57205ee7fc.png)

**Comment by Pentarctagon** [comment]
Did you mean 1.14.11?

**Comment by capgelka** [comment]
Of course, I have fixed the description.

**Comment by gfgtdf** [comment]
this was also reported in the forum in both cases the "vacant slots" checkbox was checked.

**Comment by Pentarctagon** [comment]
I haven't tried looking at the code, but would it make sense to set `selected_item_index_` to 0 in this case, rather than showing an error and kicking the user back to the main menu?  Or maybe there's a way to check if the previously selected item is still visible after the list of games is updated (whether from a filter being applied or any other reason).

**Comment by gfgtdf** [comment]
Well this error message indicates the but in the gui2 listbox code the situation here (selected item count > 0) but all items having the selected property set to false.

The way it's supposed to work: when the selected item disappeares (and it doesn't matter whether the game was ended it whether it just didn't match the filter) the next game should be selected

**Comment by gfgtdf** [comment]
This just happend to me  aswell i had wesnoth open in the background  and when i brough this window to the front i noticed that it was this error message
![Screenshot from 2020-08-10 02-34-43](https://user-images.githubusercontent.com/4893136/89745196-7d555680-dab2-11ea-9c49-3266c664008a.png)
