### ISSUE TITLE
[addon server] avoid sending restricted attributes when listing addons

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#4800]
When sending the list of addons currently attributes like `email` or `upload_ip` are sent as empty values. Ideally those attributes should not be included at all.

**Comment by soliton-** [comment]
Probably just need to fix these lines:

https://github.com/wesnoth/wesnoth/blob/d39fe3ad6db189705818eac92b8e496e2c58dcce/src/campaign_server/campaign_server.cpp#L644-L649

**Comment by ProditorMagnus** [comment]
Why is feedback_url restricted?

**Comment by gfgtdf** [comment]
> Why is feedback_url restricted?

its not really, the code 10 lines  below explains.
