### ISSUE TITLE
support scenario files in [scenario]map_file

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4803]
currently the scenarios generated by the scenario editor mare ment to be inclused ina  scenario via {./map/ediro_scenario.cfg}, i think it migth make sense to support them via [scenario]map_file, so if a .cfg file is given in  map_file, the code the currently reads map_file would just call scenario.appens(read_cfg(scenaro["map_file"])).

There are some things im unsure about yrt though:
1) shoudl we use map_file or a new key for things created by the scenario editor?
2) Assuming we used the same key, should we try to detect whther its a scenario or not by the extension or by content?

**Comment by CelticMinstrel** [comment]
I'd use extension rather than content to detect the format - if it's a .cfg, assume it's a scenario. If it's not a .cfg, assume it's a map.

Your existing implementation (searching for the string `map_data`) seems really inefficient, too.

**Comment by gfgtdf** [comment]
> Your existing implementation (searching for the string map_data) seems really inefficient, too.

Its efficient enough, its clearly not a botleneck here are both parsing the map and reading it from disk are much slower each.

Furthermore, this is also how the editor detects the type when a map is loaded. I think it totally makes sense that the the map_file implementation detects it in the same way as the editor.

**Comment by CelticMinstrel** [comment]
Well, okay. I don't think it's a good method, but it does make sense to have consistency.
