### ISSUE TITLE
create logfiles also on linux/mac

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4805]
On windows wesnoth creates logfiles that contain the output of stderr, on linux that does afaik not happen. I don't know whether its my lack of linux knowledge but when i recently started wesnoth normally (here this means: form the desktop launcher with no console attached) and got an error then i had no idea how to get the output that was written to stderr, a situation that can no happen on windows due to the logfiles.

Even if linux somehow does supports recovering the stderr output of a non-termianl programm that did already run, i really don't expect users from who i might want bug reports to be able to figure out how to do it if i am unable to do it myself.

So what i propose it: generate logfiles on linux just as we do on windows.

**Comment by shikadiqueen** [comment]
Whoever tackles this can reuse the code in `log_windows.cpp` but it's mandatory for them to:

1. Handle macOS and other Unices as well.
2. **Copy** rather than redirect Wesnoth's to a file, without eliminating terminal output, so that tools that expect to see its stderr through a pipe don't break horribly bad.

In the meantime, you can just make your launcher use a command like this:

`sh -c "wesnoth 2> ~/test.log"`

And to keep the terminal output when launching from a terminal:

`sh -c "wesnoth 2>&1 | tee ~/test.log"`

(If launching directly from a terminal then you can skip the `sh -c` and the double quotes around.)

**Comment by shikadiqueen** [comment]
It's also worth noting that the above isn't really new knowledge. See [How to locate the game logs](https://forums.wesnoth.org/viewtopic.php?t=46166) (linked from the [Technical Support instructions](https://forums.wesnoth.org/viewtopic.php?f=4&t=25660)).

**Comment by loonycyborg** [comment]
I think creating logfiles by default on unix-likes will be unexpected behaviour, so it probably should be only enabled by a command line option or preferences file

**Comment by loonycyborg** [comment]
Though it might be ok to enable by default if both stderr and logfile output are kept

**Comment by shikadiqueen** [comment]
> Though it might be ok to enable by default if both stderr and logfile output are kept

This should be the only option like I said above.

**Comment by gfgtdf** [comment]
> I think creating logfiles by default on unix-likes will be unexpected behaviour, so it probably should be only enabled by a command line option or preferences file

i think i said this already, but apparently not in this thread: 

We absolutely need to create logfiles on default, making in 'by default' is the main purpose of this feature-request. If i wanted to do it in another way, then i could just to shat iris said. The problem is:

Currently, when a Linux user encounters a bug/crash there is no way for him to recover the error log, meaning we might not be able to help him at all. The options iris mentioned can only enable logging for the next start, in the case that the user doesn't know how to reproduce the bug/crash this is worthless.

**Comment by Pentarctagon** [comment]
Oh, I didn't realize/forgot there was an issue open for this - I added this in d1833b5cf73bc2a642c106d6fec7d37e267fdfc4 already actually.
