### ISSUE TITLE
Mandatory widget 'addon' hasn't been defined

### ISSUE THREAD

**Issue by Xel** [wesnoth/wesnoth#4812]
### Game and System Information
 - Version 1.4.11
 - Downloaded via the Archlinux repo
 - Arch Linux x86_64 Linux 5.5.8-arch1-1

### Describe the bug
I tried updating an add-on (Strange Legacy - RPG to be specific). Update ran till the end and the error message popped up. 

### To Reproduce

There are no another updates available on the server at the moment, hence i'm unable to reproduce.

### Screenshots
![Screenshot from 2020-03-18 09-55-20](https://user-images.githubusercontent.com/886449/76949356-54b0a280-6900-11ea-8d0a-1ab1fe4f3c21.png)

**Comment by Pentarctagon** [comment]
I'm unable to reproduce this on Linux Mint with Wesnoth downloaded through Steam.

**Comment by soliton-** [comment]
Was this the first time it happened? Does it happen each update? Only on updates?

I've uploaded an add-on called "test" on the 1.14 server. It should get updated each hour so you can use it to test updates. Perhaps that helps reproducing the error.

**Comment by Xel** [comment]
First time I ever encountered it. 

I can see your upload on the server but clicking on the install button doesn’t reproduce it or provide any response. It simply doesn’t install.

**Comment by soliton-** [comment]
Right, I should have put something in the addon. It should install properly now.

**Comment by Xel** [comment]
@soliton- Great, installed successfully. Can you please make an update to it, so i try updating?

**Comment by soliton-** [comment]
Try again now. The addon gets updated every hour.

**Comment by Xel** [comment]
@soliton- Yes, reproduced while trying to update.

![Screenshot from 2020-03-20 09-31-16](https://user-images.githubusercontent.com/886449/77151556-147f2a80-6a8e-11ea-8bd5-bd8f78805f5c.png)

**Comment by soliton-** [comment]
Perhaps someone else on Arch can reproduce. I couldn't on iOS either.

Also weird that it only happens on updates since install and update really do that same thing.

**Comment by Xel** [comment]
I'll see whether i can convince the maintainer on Archlinux @svenstaro to try it out.

**Comment by Xel** [comment]
@Soliton Did another quick search through issues... Related to this #1993

**Comment by Xel** [comment]
Update: I've had success running 4 updates to add-ons without reproducing the bug. I still haven't figured what the issue may be, but i think i'll close it for now, since no one else has been able to reproduce it, even within the Archlinux community
