### ISSUE TITLE
1.14.9 MP Game lobby: observer icon doesn't change after side is given

### ISSUE THREAD

**Issue by PiotrMakarewicz** [wesnoth/wesnoth#4819]
BfW 1.14.9, SourceForge download for Windows 10

l-carnitine has joined the game as an observer. Then host gave him control over a side, replacing Coughart. As you may notice on the screenshot icons on the right bar didn't update: l-carnitine is still shown as an observer and Coughart as a player.
![image](https://user-images.githubusercontent.com/54529536/77257345-f70bb580-6c73-11ea-8fc6-d1be51f146d0.png)

**Comment by soliton-** [comment]
Duplicate of #2357
