### ISSUE TITLE
Add names of months and potentially days of the week to in-game encyclopedia

### ISSUE THREAD

**Issue by nemaara** [wesnoth/wesnoth#4822]
As the title says. This is a reminder to add this to the help at some point before 1.16, just so players have an easy reference to it should they want it.

Current naming scheme:

January - Whitefire
February - Bleeding Moon
March - Scatterseed
April - Deeproot
May - Scryer's Bloom 
June - Thorntress
July - Summit Star
August - Kindlefire
September - Stillseed
October - Reaper's Moon
November - Verglas Bloom
December - Blackfire

**Comment by Pentarctagon** [comment]
Is there background to these names?  They all sound pretty dramatic.

**Comment by Wedge009** [comment]
I also wonder where these names come from. Are they already present?

**Comment by nemaara** [comment]
They're not in yet. There'd be a greater backstory to them in SP rework, but for now you could imagine they have a lot of association with Elven magic.

**Comment by sevu** [comment]
Well, TBH, I think it's more confusing to swap out real world names by fantasy ones. And not just a few – will I ever memorize them and not mix them up either?

**Comment by shikadiqueen** [comment]
> Well, TBH, I think it's more confusing to swap out real world names by fantasy ones. And not just a few – will I ever memorize them and not mix them up either?

Except we never used any names in the first place (Wesnoth's calendar system has been the elephant in the room for ages) and they probably won't be too important for most people other than writers. And if you do mix them up, there's basically zero consequence for that.

**Comment by nemaara** [comment]
Actually I'm going to use these names for Liberty for now, and if someone wants to suggest alternative names I'll swap them out later.

**Comment by CelticMinstrel** [comment]
Just kinda wondering, was it intentional for Whitefire and Blackfire to be adjacent months?

(I asked this on the other thread too but then realized this is probably the more important thread on this topic.)

**Comment by nemaara** [comment]
Yes, that's intentional.

**Comment by nemaara** [comment]
> It's a question that I've asked before, but what's the lore around the calendar? It seemed to be added with no notes about where and when in the timeline it appears, nor even which races use it. Assuming it's used by humans, with a history that spans around 1000 years including a forced migration and meeting new cultures, a calendar that keeps the same names over the entire timespan breaks the worldbuilding for me. #4822 suggests it's a part of the Iryda Canon storyline, and given @nemaara's refusal to write story-bible for that world I think there's logic-errors that need to be checked before using this calendar.

It's intended to be used by humans, the background was supposed to be from Irdya Canon as you said, where some of the months associated with equinoxes or strong seasonal shifts also had effects on certain types of magic (hence some of the month names). I was thinking this was something that more educated people (e.g. Baldras or say Malin Keshar) would tend to use, while peasants probably have their own names for the months. Elves/dwarves/etc. probably also have their own names, but from a reader clarity standpoint it would probably be better to either not mention month names at all, just use numbers, or use this list.

**Comment by stevecotton** [comment]
I think it works for Liberty because that campaign takes place over little more than a month - all except S01 and the epilogue are in the month of Deeproot, with barely any time at all`*` between scenarios. Two Brothers could work similarly, as (excluding the epilogue) it all happens within a few weeks.

I think it wouldn't work with longer campaigns. SotA's S15 is the only scenario in month V, using month-names it would be easy to miss that the calendar advanced a whole month during the journey northwards.

The intro of S01 itself covers 3 months in 5 story screens. That wouldn't be apparent if it said Blackfire and Bleeding Moon instead of XII and II.

`*` It's probably a case of WINR, but on normal difficulty the turn limits for S02 onwards sum to 148 turns, all between 6 Deeproot and 3 Scryer's Bloom.

**Comment by nemaara** [comment]
Well I think we can try it out where it seems suitable. If it doesn't seem to work, like it doesn't feel right or something, it's an easy switch back. In the particular case for SotA, I agree with you that it doesn't seem to fit with Ardonna's style anyway.
