### ISSUE TITLE
Assign Recruit List in scenario editor does nothing

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#4824]
### Game and System Information
 - What version of the game are you running?
1.14.11

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Steam

 - If you're using a custom build, what compiler did you use, and what commit did you build at?
N/A

 - What OS are you running?
Linux Mint 19.3

### Describe the bug
Setting a side's recruitment list does not work.

### To Reproduce
1. Save a scenario.
2. Add a side.
3. Place a unit.
4. Set that unit as being able to recruit.
5. Select "Assign Recruit List".
6. Nothing happens.

### Expected behavior
Some window opens which allows setting the recruit list.

### Screenshots
N/A

### Savefiles
N/A

### Additional context
As per https://forums.wesnoth.org/viewtopic.php?f=4&t=52255 this functionality was apparently working at least somewhat with 1.14.7.

**Comment by gfgtdf** [comment]
es i agree that it totally unituitive, but iirc ou first have to select the units in the right side pabel (probay with rightlick on them), then clicking 'assign recruit list' on a unit on that map will set the set of selected unti on the right side panel as the recruitable units of that unit.

**Comment by Pentarctagon** [comment]
That sort of works, though there's no UI indication anything happened - no matter what unit is selected in the right panel, the leader unit in the scenario file gets line line added:
`extra_recruit="Ancient Lich"`

**Comment by gfgtdf** [comment]
> no matter what unit is selected in the right panel, the leader unit in the scenario file gets line line added:
extra_recruit="Ancient Lich"

You have to select the recruit list by right clicking in the right side panel. Ancient lich is selected by default so you have to deselect it by right clicking  on it first.

**Comment by Pentarctagon** [comment]
I have the vampire bat unit selected in the right side panel, but it gives the same result:

![editor](https://user-images.githubusercontent.com/3030250/77574288-c7d98c00-6e9f-11ea-9237-2c279a8d904f.png)

**Comment by gfgtdf** [comment]
> I have the vampire bat unit selected in the right side panel:

No you don't i said "right click", there are two types of selection the ones with blue borders which is sone with rightclick and one with blue borders which allow multiple units to be selected, this is done with right click, You need the 'blue' type  of selection here.

**Comment by Pentarctagon** [comment]
Alright, that did it.  Thanks.

**Comment by gfgtdf** [comment]
I think we should repoen this, even if it works 'as intended' its still quite counterintuitive in my opniion and should be improved .

**Comment by Pentarctagon** [comment]
I'll open another issue as an enhancement, since technically I suppose this is currently working as intended.
