### ISSUE TITLE
unit tooltip in editor doesnt show

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4826]
the editor has tooltip of the units that should appear when the mouse is over a unit showing certain information, It doesnt show in 1.15.3+dev

**Comment by Wedge009** [comment]
Confirmed behaviour in current master (a8bb275a) is not the same as 1.14.11 release. In my case I see the tool-tips flickering on mouse hover, as though the tool-tip is being shown then prematurely dismissed then shown again, in a repeating cycle. Must be a change somewhere recently that broke this.

**Comment by gfgtdf** [comment]
Yes thinking about it it's quite likely that it's unrelated to the editor and applies to all gui1 tooltips
