### ISSUE TITLE
Assigning a side's recruit list in the editor is unintuitive

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#4827]
There was a question asked on the forums today about how to add a certain unit the a side's recruit list in the scenario editor.  While trying to find the answer to that, the steps I had to take were in no way intuitive for someone to be able to figure out on their own:
* The text of the option, "Assign Recruit List", made me think that this would open up a window where I would be able to select the unit(s) to add to the side's recruit list - this didn't happen and in fact there seems to be no UI at all showing what the side's current recruit list is.
* Clicking the "Assign Recruit List" option without selecting a unit from the right panel defaults to making the Ancient Lich recruitable for that side, rather than showing the user an error saying that they need to choose a unit first.  This has also caused confusion for at least one other person:
![unwiseowl-ancientlich](https://user-images.githubusercontent.com/3030250/77579684-bb0d6600-6ea8-11ea-8c67-df477fa6ac6d.png)
* It isn't intuitive to know that I need to right click the unit in the right hand panel rather than left click in order for the unit to be added the the side's recruit list, and seems to be a general issue with the editor:
![unwiseowl-rightclick](https://user-images.githubusercontent.com/3030250/77579764-d7a99e00-6ea8-11ea-80ef-591c31338cf2.png)

**Comment by stevecotton** [comment]
"Fixed by" is the wrong phrase, but closed by removing the feature in c8666a8.
