### ISSUE TITLE
Disable unused addon during a game

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4832]
So currently it is possible that global [trait], [units], [lua] etc tagshave an effect on the current gamestate even if they are dfeined from in addons that are not active n the current game. This casues OOS and i'd be better of this was not possibel.

I think the enginr should bahve as if these addons wouldn't exist during a game unless a part of that addon is explicitly used in the current game:

When we start a game the engine should gather a list of all addon_id that contain the used [campaign], [multiplayer], [era], [modification], [resource], and hide all content from other addons. 

Clearly all addons shodul be active during the loadingscrren/multiplayer_create etc screens, to show all installed campaigns/eras etc.

The difficultiers when implementing this include:
1) when the config is loaded for a game one cannot say at that point what addons are involced since for example [scenario]s might contain [load_resource]
2) _A lot_ of places use the global config object, so an approach of replacing the global config with a a set of configs for one for each  addons, might require some refactoring

**Comment by Pentarctagon** [comment]
Using an external resource via [load_resource] would still require the add-on to list the other add-on in its [binary_path] though, right?

**Comment by gfgtdf** [comment]
> Using an external resource via [load_resource] would still require the add-on to list the other add-on in its [binary_path] though, right?

Hmm no it currently doesn't and I don't see why it should after this patch. Binary_paths are currently only used to.rrsolve file location but [load_reesource] uses the I'd from the [Ressource] tag

**Comment by Pentarctagon** [comment]
Can the resource ID be contained in a WML variable?

**Comment by Pentarctagon** [comment]
If yes, then there's no way to know which add-ons are used in 100% of cases until runtime.  Otherwise, there could be essentially a post-preprocessing step to search for these tags for their IDs, and then match them up to the add-on(s) using them.  I was already thinking such a thing might be needed as well in order to store add-on version in the MP database, since for that I would need to be able to match up a particular scenario ID, era ID, etc with the source add-on in order to be able to know that content's version.

**Comment by gfgtdf** [comment]
> Can the resource ID be contained in a WML variable?

No, [load_ressorce] is not an actionwml tag, its read at scenario initiliation. But its processed after the game config for the scenario is read. ( for example [load_resource] may be used from inside the campaigns #ifdef)

>  I was already thinking such a thing might be needed as well in order to store add-on version in the MP database

This already exists, and the clients do already send their used addon versiond for each addon involved (only for addons that require a download of this addon though) in a game to the mp server, this list is exactly the infotmation that onw  would use also here.

**Comment by gfgtdf** [comment]
>  I was already thinking such a thing might be needed as well in order to store add-on version in the MP database

look at the [multiplayer][addon] array.
