### ISSUE TITLE
Unit keeps attacking until it (or defender) dies.

### ISSUE THREAD

**Issue by MrWillow** [wesnoth/wesnoth#4836]
First remark: Thanks to all contributors! This is a great game!

### Game and System Information
 - What version of the game are you running?
Version 1.14.7
I upgraded just now to 1.14.11 and it has the same issue.

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
from github via the link provided on https://wesnoth.org/

 - If you're using a custom build, what compiler did you use, and what commit did you build at?
no custom build.

 - What OS are you running?
Windows10 Home, 64 bit, (fully patched / up-to-date).

### Describe the bug
Units keep fighting far longer than they should. It ends when the attacker or defender dies.
I have seen happening this before, but decided to report now I saw it happening again.

### To Reproduce
(I attached my safe game.) Just end the turn, and the enemy unit (dwarfish ulfserker) will start attacking endlessly on my white mage.
The unit is almost dead, so it can happen that the ulfserker dies before it reaches it max attacks. In that case, please retry.

### Expected behavior
Normal number of attacks, not endless.

### Screenshots
1) the ulfserker that starts attacking
2) the white mage that will be attacked endlessly.

![image](https://user-images.githubusercontent.com/3976559/78259667-4916cb80-74fd-11ea-8822-b9ff38340edf.png)

### Savefiles
[THoT-Fear Turn 4.gz](https://github.com/wesnoth/wesnoth/files/4421598/THoT-Fear.Turn.4.gz)

### Additional context
Nothing to add.

**Comment by soliton-** [comment]
If you look at the description of the Ulfserker unit you can find this note:

> Whenever its berserk attack is used, this unit continues to push the attack until either it or its enemy lies dead.

So it is normally that they attack this way.

Is that all this report is about?

**Comment by shikadiqueen** [comment]
The berserker weapon special used by the attacks of both the Ulfserker and Berserker allow them to keep fighting until either unit dies, for a maximum of 30 rounds. This is specified in its description.

**Comment by MrWillow** [comment]
@soliton- 

Erm.... yes. Ahum. You are right.
I am an idiot for missing that.
Excuse me for wasting your time!
(Please close, or better, delete this 'bug')

**Comment by soliton-** [comment]
No worries. It's good to report bugs. Just needs a little more care next time. :wink:

**Comment by UnwiseOwl** [comment]
Honestly disappointed this wasn't posted 24 hours earlier. Would have been a great April Fools issue.
