### ISSUE TITLE
(1.14.9) Main menu background didn't display, but interface did

### ISSUE THREAD

**Issue by ZombieEnderman5** [wesnoth/wesnoth#4839]
### Game and System Information
 - What version of the game are you running? 1.14.9.
 - Where did you download it from? The website.
 - What OS are you running? Windows 8.

For all I know this may have been fixed in 1.14.10 or 1.14.11; if that is the case, my apologies for creating an issue for an already-fixed bug.

### Describe the bug
Wesnoth was fullscreened. I had quit from a multiplayer server hosted by a friend (connected to using the connect option that requires you to give an IP address) and the main menu interface was laid on top of the multiplayer server interface, with the main menu background not displaying. I didn't check to see whether the multiplayer server interface could still be used (forgetfulness on my part), but it shouldn't have been usable.

### To Reproduce

1. Connect to a multiplayer server, using the connection option that requires an IP address.
2. Quit the server using the Log Out button.
  
Note: this only happened the *last* time I had quit that server, not any of the other times.

### Expected behavior
I expected the Wesnoth main menu to display as normal - that is, with the interface and background displayed, not just the interface.

### Screenshots
![Screenshot showing the issue.](https://cdn.discordapp.com/attachments/259976436490829825/696306031093088286/unknown.png)

### Additional context
"Interface" being the clickable buttons and whatnot of a menu. As seen in the screenshot, the main menu background does not appear, but all of the clickable buttons do.

**Comment by Pentarctagon** [comment]
I'm not able to reproduce this, at least on Linux Mint 19.3 with 1.14.11.  Ideally someone on Windows can check as well though.

**Comment by Wedge009** [comment]
The only time I have seen anything resembling this is when I was experimenting with DLLs on start-up and the JPEG library was missing - so of course the background wood texture failed to load.

The reporter notes it has only happened once so i wonder if it is a chance occurrence resulting from the perhaps-not-quite-proper way Wesnoth uses SDL for rendering.

**Comment by Wedge009** [comment]
If this issue recurs, please advise, but for the time being I don't think it's worth keeping something open that we don't know how to reliably replicate.
