### ISSUE TITLE
a way to query active specials for a weapon

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4840]
With the newly added weapon speciasl as abilities feature in 1.15, the special_tag_active attribute does not longer return the same value that is used in the actual attack calculation to check whether a weapon is really under the effect of an ability making it harder to implement weapon specials in wml properly, We should either
1) make the implementation of special_tag_active call the special bool function
Or
2) Add a new attribute that checks calls special_bool

Im currently unsure which of these is the best way though.

**Comment by newfrenchy83** [comment]
i already tried to resolve that but yes, only the true weapon_specials were identified by special_tag_active, probably because weapon-special must be implemented inside [specials] tag for that.

**Comment by gfgtdf** [comment]
Wee so what it your opinion on changing this line 

https://github.com/wesnoth/wesnoth/blob/e053566a15287d14b3ac8fb0ec05ddc2bfc7e910/src/units/attack_type.cpp#L207


to call attack->ability_bool() instead ?

**Comment by newfrenchy83** [comment]
i already try that, but if id or tag are not in [special] tags, it is undectectable. for filter_weapon or filter_attack, it is only the wml code wrting inside [attack] who can be filtered, the remain code inside unit_type can't be filtered.

I tried to emulate get_special_boll in ability_bool but without changes.

The ability like weapon_special can't be filtered like true weapon_specials, and i search an alternate to [filter_weapon] for resolve that but in best case, it will be partial.

**Comment by newfrenchy83** [comment]
i think what i did findest an solution but i must test before.

**Comment by newfrenchy83** [comment]
@gfgtdf i resoved this issue with add a new attribute that checks calls special_bool

**Comment by gfgtdf** [comment]
I worked on something that fits _my own_ usecase  better in https://github.com/wesnoth/wesnoth/pull/5016 basicialyl we add a lua api function that allows me to not only check whether any ability/special with a certain tagname is active but also to to query information about them. This only supports querying abilities by tagname (not by id) yet, but i don't think this is a problem.

**Comment by newfrenchy83** [comment]
> 
> 
> I worked on something that fits _my own_ usecase better in #5016 basicialyl we add a lua api function that allows me to not only check whether any ability/special with a certain tagname is active but also to to query information about them. This only supports querying abilities by tagname (not by id) yet, but i don't think this is a problem.

except what if [filter_student/opponent/eetc..], apply_to or active_on were used and condition not matches, weapon abilities will be seen like  active
