### ISSUE TITLE
In SotBE 15, level doesn't conclude despite conditions being met

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#4841]
### Game and System Information
 - Version 1.15.3
 - Downloaded binary from SourceForge
 - Windows 64

### Describe the bug + To Reproduce
In Son of the Black Eye scenario 15 "Civil war", you must:

1. Kill all enemy leaders
2. Move Kapoue to the signpost

Now, if you move Kapoue to the signpost first, you get some dialog on how he can't just leave with renegade tribes behind, and he supposedly needs to go back. This is fine - except that he doesn't need to go back _personally_. Now, if you kill the last leader while Kapoue is _at_ the signpost, the level doesn't conclude. You have to move Kapoue _away_ from the signpost. That's annoying, and - if you've just managed to get him to the signpost with the last of his movement, you've lost a whole turn needlessly. Not fair...

### Savefiles
[SotBE-Civil War-Auto-Save21.gz](https://github.com/wesnoth/wesnoth/files/4453080/SotBE-Civil.War-Auto-Save21.gz)

**Comment by nemaara** [comment]
Fixed by 3d6e03a.
