### ISSUE TITLE
Assert fail on Windows build

### ISSUE THREAD

**Issue by rebhuhn** [wesnoth/wesnoth#4844]
Hello,

While playing wesnoth on Windows, I encountered an assert fail (see my post Assert Fail in the technical support forum, started on April 6, 2020).  I'm reporting it here on the advice of gtgtdf.

As part of trying to track down this issue, I downloaded the code and built a version.

Code tar was wesnoth.1.14.11

I build using VC16.

I downloaded vcpkg and installed using:

git clone https://github.com/microsoft/vcpkg.git vcpkg
cd vcpkg
bootstrap-vcpkg.bat
vcpkg integrate install
vcpkg install sdl2:x64-windows sdl2-image:x64-windows sdl2-mixer:x64-windows sdl2-ttf:x64-windows bzip2:x64-windows zlib:x64-windows pango:x64-windows cairo:x64-windows fontconfig:x64-windows libvorbis:x64-windows libogg:x64-windows boost-filesystem:x64-windows boost-iostreams:x64-windows boost-locale:x64-windows boost-random:x64-windows boost-regex:x64-windows boost-asio:x64-windows boost-program-options:x64-windows boost-system:x64-windows boost-thread:x64-windows boost-bimap:x64-windows boost-multi-array:x64-windows boost-ptr-container:x64-windows boost-logic:x64-windows boost-format:x64-windows

I then built the system.  I copied necessary directories such as data and sounds to the build directory, projectfiles\VC16\Debug.

I attempted to run wesnoth and tripped the following assert fail:

static void check_fpu()
{
uint32_t f_control;

if(_controlfp_s(&f_control, 0, 0) == 0) {
uint32_t unused;
uint32_t rounding_mode = f_control & _MCW_RC;
uint32_t precision_mode = f_control & _MCW_PC;

if(rounding_mode != _RC_NEAR) {
std::cerr << "Floating point rounding mode is currently '"
<< ((rounding_mode == _RC_CHOP)
? "chop"
: (rounding_mode == _RC_UP)
? "up"
: (rounding_mode == _RC_DOWN)
? "down"
: (rounding_mode == _RC_NEAR) ? "near" : "unknown")
<< "' setting to 'near'\n";

if(_controlfp_s(&unused, _RC_NEAR, _MCW_RC)) {
std::cerr << "failed to set floating point rounding type to 'near'\n";
}
}
if(precision_mode != _PC_53) {
std::cerr << "Floating point precision mode is currently '"
<< ((precision_mode == _PC_53)
? "double"
: (precision_mode == _PC_24)
? "single"
: (precision_mode == _PC_64) ? "double extended" : "unknown")
<< "' setting to 'double'\n";

if(_controlfp_s(&unused, _PC_53, _MCW_PC)) <================== Assert failing on this line
std::cerr << "failed to set floating point precision type to 'double'\n";
}

Value of precision_mode is 0
Value of f_control is 524319
value of rounding_mode is 0

Assert pop up is attached. Text is:
File: minkernel\crts\ucrt\src\appcrt\tran\amd64\ieee.c line 106
Expression: (mask&~(_MCW_DNI_MCW_EMI_MCW_RC))==0

![AssertFail2](https://user-images.githubusercontent.com/12900614/78956716-206c7400-7ab1-11ea-94c1-b5844fdf603e.png)

There is no stderr output.

I commented out the 3 lines of the if that caused the assert fail and did a rebuild.

I now get another assert fail.  This one is in SDL_DestroyRenderer in SDL_render.c

void
SDL_DestroyRenderer(SDL_Renderer * renderer)
{
    SDL_RenderCommand *cmd;
    SDL_AllocVertGap *gap;
    SDL_AllocVertGap *nextgap;

    CHECK_RENDERER_MAGIC(renderer, );   <===== Fails here.

renderer is a null pointer.

The only other information I have to add is that I have several times had issues where the redrawing of the screen after unit moves was bugged.  Units would leave trails of themselves behind them rather than the background properly redrawing.

I'm happy to take any steps that might help uncover the problem, just send me an email and let me know what you'd like me to try.

**Comment by Pentarctagon** [comment]
Can you check if this is fixed with the latest 1.14 code?

**Comment by rebhuhn** [comment]
I applied the patch rather than redownloading.  It worked and I'm on to trying scenarios.
Wasn't sure if it was okay for _renderer to be null at that point.

    On Friday, April 10, 2020, 10:00:19 AM EDT, Pentarctagon <notifications@github.com> wrote:  
 
 


Can you check if this is fixed with the latest 1.14 code?

**Comment by Pentarctagon** [comment]
Alright, sounds good then.

**Comment by rebhuhn** [comment]
So, I tried to integrate the error check that gtgfdf committed along with some other error checking and when I go to build,I'm getting
wesnoth\wesnoth-1.14.11\src\boost-patched\bind\arg.hpp(3,10): fatal error C1083: Cannot open include file: 'boost/version.hpp':similar errors for lots of boost include files.

It's possible that visual studio updated itself since I last built.
I tried redoing the vcpkg install, it told me that everything was already installed.
Opening Visual Studio, if I try to add  #include <boost  nothing is found except the boost_patched directory under wesnoth/src.
I found the files under vcpkg\installed\x64-windows\include\boost, and can manually add the include path to the 
projects, but this seems a bit of a kludge.  Just wondering if you've seen anything like this before and if there'ssome solution to get things working the way they are supposed to?
Any help appreciated.
Thanks.

**Comment by gfgtdf** [comment]
Hmm really no idea maybe you accidentally tried to do a 32bit build or maybe you somehow manually removed that directly from your include path?

**Comment by rebhuhn** [comment]
Don't know.  I haven't had the debugger up for a while.  Just loaded the project, changed the file and tried to build.I manually put the directory into the additional includes and everything compiled, so I'm going forward.
Just another day working with Microsoft.   Which now reminds me of the probably cause.   Last week I made the mistake of installingtheir gflags utility and following their directions to try and debug some memory overwrite problems.  Thatled to the machine being unbootable and having to reinstall windows.  Probably lost something somewherethat sets up the include paths in the process.  I suggest that you never try the gflags utility!



On Monday, April 27, 2020, 8:46:52 PM EDT, gfgtdf <notifications@github.com> wrote: 
 
 


Hmm really no idea maybe you accidentally tried to do a 32bit build or maybe you somehow manually removed that directly from your include path?

**Comment by rebhuhn** [comment]
whoops, spoke to soon.  Patch failed compilation:
had to add 
#include <iostream>
hmm, looks like i'm going to need to manually add the lib directories too


    On Monday, April 27, 2020, 8:46:52 PM EDT, gfgtdf <notifications@github.com> wrote:  
 
 


Hmm really no idea maybe you accidentally tried to do a 32bit build or maybe you somehow manually removed that directly from your include path?

**Comment by rebhuhn** [comment]
aha!  reran vcpkg integrate install.   much better now

    On Monday, April 27, 2020, 8:46:57 PM EDT, gfgtdf <notifications@github.com> wrote:  
 
 


Reopened #4844.

**Comment by gfgtdf** [comment]
Hmm yes I made a follow-up commit https://github.com/wesnoth/wesnoth/commit/ce45540b81a601c6abd4b2ca301f915a0bf544bd fo fix that right after the original commit

**Comment by gfgtdf** [comment]
So i assume it works now for you? I'm looking forwards to seeing the errolog from next time you encounter this problem

**Comment by rebhuhn** [comment]
Build succeeded, could start it.  No time right now to play, but will let you know as soon as I get anything.

    On Tuesday, April 28, 2020, 8:05:31 AM EDT, gfgtdf <notifications@github.com> wrote:  
 
 


So i assume it works now for you? I'm looking forwards to seeing the errolog from next time you encounter this problem

**Comment by Wedge009** [comment]
Removing high priority label because it _looks_ like this is largely resolved, or at least is in progress of being resolved.

**Comment by gfgtdf** [comment]
Well not really what was fixed is the first bug report, which was more or less a failure to compile (okay crash on statdrup) on windows x64 but the 'new' and not yet fixed  issue is a random crash on theofficial 1.14 release that was reported my many used on the formal already

**Comment by Pentarctagon** [comment]
Closing again since the crash on start has been fixed, and the second issue was fixed by re-running `vcpkg integrate install`.

**Comment by gfgtdf** [comment]
To be clear the mort important problem and the reason why we are investigating all of this in the first place _not fixed yet_ as I said I. My previous post. But I agree that it better to open a new issue for it @rebhuhn

**Comment by Pentarctagon** [comment]
That issue already exists as #4855
