### ISSUE TITLE
On Windows, 64 bit Wesnoth installs by default to the 32 bit Program Files folder.

### ISSUE THREAD

**Issue by 123chess456** [wesnoth/wesnoth#4847]
### Game and System Information
Using Windows 10 64 bit.
Game version is 1.15.3, Windows 64 binary from wesnoth.org

### Describe the bug
When trying to install the game for everyone, the default path for Windows 10 is "C:\Program Files (x86)\Battle for Wesnoth 1.15.3", which is incorrect, as the game is not a 32 bit program in this context.

### To Reproduce

1. Download the 64 bit installer for Windows.
2. Open the installer.
3. Go through the steps of the installer, ensuring that "Install for anyone using this computer" is checked.

### Expected behavior
The default game path for the 64 bit version should be C:\Program Files\Battle for Wesnoth 1.15.3" as Program Files is where 64 bit programs go.

**Comment by loonycyborg** [comment]
This will come in effect only on next 1.15.x/1.16.0 release though
