### ISSUE TITLE
Northern Rebirth - The Pursuit: Naga triggers lever to Malifor's Study

### ISSUE THREAD

**Issue by PapaAlpaka** [wesnoth/wesnoth#4853]
### Game and System Information
 - 1.14
 - Steam

### Describe the bug

Following the flooded tunnel (south-east) to Malifor's study, you encounter a bunch of hostile Naga. When a Naga hits the tile triggering the "door" dialogue opening a back door, the dialogue is triggered.

### To Reproduce

Do not kill the Naga upon sight and have one of their units move onto the lever dialogue-triggering tile.

### Expected behavior

 I think it should only triggered by friendly/own units.

### Screenshots
![Wesnoth - Northern Rebirth - Pursuit - Malifor-Lever-Naga](https://user-images.githubusercontent.com/34440922/79620892-d0755900-8111-11ea-9768-e04a03cbbdee.png)

**Comment by Pentarctagon** [comment]
Closed in the above commit.
