### ISSUE TITLE
Something wrong in lobby

### ISSUE THREAD

**Issue by GliderMaster** [wesnoth/wesnoth#4858]
### Game and System Information
 - What version of the game are you running? 1.14.11
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) Website
 - If you're using a custom build, what compiler did you use, and what commit did you build at? I'm not
 - What OS are you running? Windows 10
### Describe the bug
I'm receiving the messare 
Error
Something is wrong with the addon version check database supporting the multiplayer lobby 

when I try to join some games.

**Comment by Pentarctagon** [comment]
Duplicate of #4055, it looks like.
