### ISSUE TITLE
Minimap broken on raspberry pi

### ISSUE THREAD

**Issue by garydwatson** [wesnoth/wesnoth#4861]
### Game and System Information
 - 1.14.11 and 1.14.5
 - first I tried raspbian (buster) package and then I built from source

### Describe the bug
The minimap does not display correctly.  This has been a bug for a really long time (several years at this point).  I thought it would get fixed, so I never reported it, however I'm starting to realize that this probably only shows up on the raspberry pi, (ie most builds probably don't exhibit this bug).  Here are some screen shots of the bug...

![Screenshot from 2020-04-20 06-53-57](https://user-images.githubusercontent.com/903200/79744795-0282e880-82d5-11ea-84b4-5651fb293653.png)

![Screenshot from 2020-04-20 06-54-37](https://user-images.githubusercontent.com/903200/79744810-07479c80-82d5-11ea-96d3-916ecc9f2e53.png)

### To Reproduce
1. Go get a raspberry pi
2. install wesnoth either from source or from the raspbian repos
3. run wesnoth
4. notice that the minimap never displays correctly, either when selecting levels or during gameplay

### Expected behavior
Minimap displays properly

### Screenshots
See above

**Comment by Wedge009** [comment]
It does sound like it might be Pi-specific. What SDL libraries does the Pi use?

**Comment by garydwatson** [comment]
What I'm about to paste in is a list of packages from raspbian that start with libsdl.  There's probably more information here than needed, but I think contained within it will be the relevant information...

libsdl-console/stable,now 2.1-6 armhf [installed,automatic]
  Console that can be added to any SDL application, libraries

libsdl-console-dev/stable,now 2.1-6 armhf [installed]
  Console that can be added to any SDL application, development files

libsdl-gfx1.2-5/stable,now 2.0.25-11 armhf [installed,automatic]
  drawing and graphical effects extension for SDL

libsdl-gfx1.2-dev/stable,now 2.0.25-11 armhf [installed]
  development files for SDL_gfx

libsdl-gfx1.2-doc/stable 2.0.25-11 all
  documentation files for SDL_gfx

libsdl-gst/stable 3.2.5-1.1+b1 armhf
  SDL bindings for GNU Smalltalk

libsdl-image-gst/stable 3.2.5-1.1 all
  SDL_image bindings for GNU Smalltalk

libsdl-image1.2/stable,now 1.2.12-10+deb10u1 armhf [installed,automatic]
  Image loading library for Simple DirectMedia Layer 1.2, libraries

libsdl-image1.2-dev/stable,now 1.2.12-10+deb10u1 armhf [installed]
  Image loading library for Simple DirectMedia Layer 1.2, development files

libsdl-kitchensink-dev/stable 1.0.7-1 armhf
  FFmpeg and SDL2 based library for audio and video playback - Development files

libsdl-kitchensink1/stable 1.0.7-1 armhf
  FFmpeg and SDL2 based library for audio and video playback

libsdl-mixer-gst/stable 3.2.5-1.1 all
  SDL_mixer bindings for GNU Smalltalk

libsdl-mixer1.2/stable,now 1.2.12-15 armhf [installed,automatic]
  Mixer library for Simple DirectMedia Layer 1.2, libraries

libsdl-mixer1.2-dev/stable,now 1.2.12-15 armhf [installed]
  Mixer library for Simple DirectMedia Layer 1.2, development files

libsdl-net1.2/stable,now 1.2.8-6 armhf [installed,automatic]
  Network library for Simple DirectMedia Layer 1.2, libraries

libsdl-net1.2-dev/stable,now 1.2.8-6 armhf [installed]
  Network library for Simple DirectMedia Layer 1.2, development files

libsdl-ocaml/stable 0.9.1-2+b3 armhf
  OCaml bindings for SDL - runtime files

libsdl-ocaml-dev/stable 0.9.1-2+b3 armhf
  OCaml bindings for SDL - development files

libsdl-pango-dev/stable 0.1.2-8 armhf
  text rendering with Pango in SDL applications (development)

libsdl-pango1/stable,now 0.1.2-8 armhf [installed,automatic]
  text rendering with Pango in SDL applications (shared library)

libsdl-perl/stable,now 2.548-1+b1 armhf [installed,automatic]
  SDL bindings for the Perl language

libsdl-sge/stable 030809dfsg-9 armhf
  extension of graphic functions for SDL multimedia libraries

libsdl-sge-dev/stable 030809dfsg-9 armhf
  extension of graphic functions for the SDL multimedia, development files

libsdl-sound-gst/stable 3.2.5-1.1 all
  SDL_sound bindings for GNU Smalltalk

libsdl-sound1.2/stable,now 1.0.3-9 armhf [installed,automatic]
  Sound library for Simple DirectMedia Layer 1.2, libraries

libsdl-sound1.2-dev/stable,now 1.0.3-9 armhf [installed]
  Sound library for Simple DirectMedia Layer 1.2, development files

libsdl-ttf-gst/stable 3.2.5-1.1 all
  SDL_ttf bindings for GNU Smalltalk

libsdl-ttf2.0-0/stable,now 2.0.11-6 armhf [installed,automatic]
  TrueType Font library for Simple DirectMedia Layer 1.2, libraries

libsdl-ttf2.0-dev/stable 2.0.11-6 armhf
  TrueType Font library for Simple DirectMedia Layer 1.2, development files

libsdl1.2-dev/testing,now 1.2.15+dfsg2-4+rpt2 armhf [installed]
  Simple DirectMedia Layer development files

libsdl1.2debian/testing,now 1.2.15+dfsg2-4+rpt2 armhf [installed,automatic]
  Simple DirectMedia Layer

libsdl1.2debian-dbgsym/testing 1.2.15+dfsg2-4+rpt2 armhf
  debug symbols for libsdl1.2debian

libsdl2-2.0-0/testing,now 2.0.9+dfsg1-1+rpt1 armhf [installed,automatic]
  Simple DirectMedia Layer

libsdl2-2.0-0-dbgsym/testing 2.0.9+dfsg1-1+rpt1 armhf
  debug symbols for libsdl2-2.0-0

libsdl2-dev/testing,now 2.0.9+dfsg1-1+rpt1 armhf [installed]
  Simple DirectMedia Layer development files

libsdl2-doc/testing 2.0.9+dfsg1-1+rpt1 all
  Reference manual for libsdl2

libsdl2-gfx-1.0-0/stable,now 1.0.4+dfsg-3 armhf [installed,automatic]
  drawing and graphical effects extension for SDL2

libsdl2-gfx-dev/stable,now 1.0.4+dfsg-3 armhf [installed]
  development files for SDL2_gfx

libsdl2-gfx-doc/stable 1.0.4+dfsg-3 all
  documentation files for SDL2_gfx

libsdl2-image-2.0-0/stable,now 2.0.4+dfsg1-1+deb10u1 armhf [installed,automatic]
  Image loading library for Simple DirectMedia Layer 2, libraries

libsdl2-image-dev/stable,now 2.0.4+dfsg1-1+deb10u1 armhf [installed]
  Image loading library for Simple DirectMedia Layer 2, development files

libsdl2-mixer-2.0-0/stable,now 2.0.4+dfsg1-1 armhf [installed,automatic]
  Mixer library for Simple DirectMedia Layer 2, libraries

libsdl2-mixer-dev/stable,now 2.0.4+dfsg1-1 armhf [installed]
  Mixer library for Simple DirectMedia Layer 2, development files

libsdl2-net-2.0-0/stable,now 2.0.1+dfsg1-4 armhf [installed,automatic]
  Network library for Simple DirectMedia Layer 2, libraries

libsdl2-net-dev/stable,now 2.0.1+dfsg1-4 armhf [installed]
  Network library for Simple DirectMedia Layer 2, development files

libsdl2-ttf-2.0-0/stable,now 2.0.15+dfsg1-1 armhf [installed,automatic]
  TrueType Font library for Simple DirectMedia Layer 2, libraries

libsdl2-ttf-dev/stable,now 2.0.15+dfsg1-1 armhf [installed]
  TrueType Font library for Simple DirectMedia Layer 2, development files

**Comment by Pentarctagon** [comment]
The second bullet from [here](https://forums.wesnoth.org/viewtopic.php?f=4&t=25660) will help with providing more specific information.

**Comment by garydwatson** [comment]
The Battle for Wesnoth version 1.14.11
Running on Raspbian GNU/Linux 10 (buster)
Distribution channel: Default

Game paths
==========

Data dir:        /usr/local/share/wesnoth
User config dir: /home/USER/.config/wesnoth
User data dir:   /home/USER/.local/share/wesnoth/1.14
Saves dir:       /home/USER/.local/share/wesnoth/1.14/saves
Add-ons dir:     /home/USER/.local/share/wesnoth/1.14/data/add-ons
Cache dir:       /home/USER/.cache/wesnoth

Libraries
=========

Boost:             1.67
OpenSSL/libcrypto: 1.1.1d (runtime 1.1.1d)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.42.3 (runtime 1.42.3)
SDL:               2.0.9  (runtime 2.0.9)
SDL_image:         2.0.4  (runtime 2.0.4)
SDL_mixer:         2.0.4  (runtime 2.0.4)
SDL_ttf:           2.0.15 (runtime 2.0.15)

Features
========

JPEG screenshots:               yes
Lua console completion:         yes
Legacy bidirectional rendering: yes
D-Bus notifications back end:   yes

**Comment by Wedge009** [comment]
SDL 2.0.9 should do fine. Is the mini-map the only place where it doesn't render well or are there other graphical issues? It does seem like it might be specific to Raspbian - I haven't heard or seen any other reports like this. You mentioned trying both the Raspbian packages and self-compiling, I assume the results are the same for both. I'm not sure what we can do to help, other than perhaps asking the Raspbian package maintainers about this.

**Comment by mesilliac** [comment]
In 1.17.4 the rendering system has been upgraded to use SDL's hardware rendering interface. From what i can tell... it might actually work on the Pi as it can use Mesa and openGL to satisfy the interface.

It might have even fixed this bug.

@garydwatson if you can test 1.17.6 with this i'd be curious to see if it (a) works? (b) fixes this issue.

**Comment by Wedge009** [comment]
Closing due to lack of response - re-open if still an issue.
