### ISSUE TITLE
Dark Assassin drawn with curved dagger, said to have a scythe

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#4875]
Wesnoth 1.15.3
Scenario 4: Descending into Darkness

In the scenario, Kaleh is attack by a "Dark Assassin". First I should say that dressing him up like an Orcish Assassin is somewhat unbecoming, but - that's a matter of taste I suppose.

The issue is that the assassin is drawn to be holding a curved dagger with a sort of a curved hook at its bottom - certainly not a scythe. But the combat dialogue suggest he has a scythe. Make it a dagger please, if there isn't something more fitting.

**Comment by Wedge009** [comment]
Perhaps a case of the unit attributes not being updated along with the sprite re-design. Compare the unit sprites between 1.10 and 1.12 (which is also used for 1.14):

https://units.wesnoth.org/1.10/mainline/en_US/Dark%20Assassin1.html
https://units.wesnoth.org/1.12/mainline/en_US/Dark%20Assassin1.html

**Comment by eyalroz** [comment]
Actually, examining the sprite again, I note that:

* Combat dialog - scythe
* Large illustration - dagger
* Sprite - a blade which could be interpreted in more than one way

**Comment by doofus-01** [comment]
> First I should say that dressing him up like an Orcish Assassin is somewhat unbecoming, but - that's a matter of taste I suppose.

I agree, the unit data is also in an `/orcs` directory, he's basically an orc copy.  I'll look into getting him a unique sprite.

**Comment by doofus-01** [comment]
This should no longer be an issue, after #4906
