### ISSUE TITLE
In UtBS, Wesnothpedia says Elves have pale skin

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#4876]
Wesnoth 1.15.3
Any scenario

The Wesnothpedia section on Elves discusses the regular elves, despite the individual unit links pointing to the Quenoth variants. The general text for elves should be altered as well - or there should be a split between Elves and Quenoth Elves (even better)

**Comment by Wedge009** [comment]
Is 'Wesnothpedia' the in-game help? I wonder if there's a mix-up in how the pages are generated - if you temporarily rename your preferences file (a lot of global state information, such as units you've encountered, is also stored here) so you are effectively starting with a 'blank slate', does the issue still occur?

**Comment by eyalroz** [comment]
> Is 'Wesnothpedia' the in-game help? 

Yes.

> if you temporarily rename your preferences file

Which preference file, exactly?

**Comment by Wedge009** [comment]
_The_ preferences file: https://wiki.wesnoth.org/Editingwesnoth

**Comment by eyalroz** [comment]
@Wedge009 : I my userdata direction (`wesnoth --config-path 2>&1 | tail -1`) there is no preferences file as described at the link.

**Comment by soliton-** [comment]
It’s --userconfig-path nowadays.

**Comment by stevecotton** [comment]
There's no `[race]` tag anywhere in data/campaigns/UtBS. The Quenoth units all have `race=elf`, which gets the `[race]id=elf` from data/core/units.cfg; and a `[hide_help]` is used to hide the pre-Fall elves.

I agree with the suggestion of making the Quenoth elves a separate race. This isn't an offer to do the work, however I am intending to play the campaign again soon with #4974, so might test.

**Comment by eyalroz** [comment]
> It’s --userconfig-path nowadays.

No preferences file there either (under `$HOME/local/share/wesnoth/1.15`).

**Comment by soliton-** [comment]
Sounds like you are using --userconfig-dir or --config-dir with a different path when you start wesnoth or your installation is broken.

Btw, it's odd that the path you report says `local` and not `.local`. Haven't seen that before.

**Comment by eyalroz** [comment]
> Sounds like you are using --userconfig-dir or --config-dir with a different path when you start wesnoth or your installation is broken.

I'm not, and - it isn't; at least, not that I know of...

Also - it's `.local`, I mis-copied.

**Comment by eyalroz** [comment]
>  I wonder if there's a mix-up in how the pages are generated - if you temporarily rename your preferences file (a lot of global state information, such as units you've encountered, is also stored here) so you are effectively starting with a 'blank slate', does the issue still occur?

Yes, it still occurs.

**Comment by stevecotton** [comment]
I haven't opened a PR because I feel it needs more testing, but there's a potential fix auto-linked above this comment.

**Comment by eyalroz** [comment]
@stevecotton : Looks reasonable.

**Comment by stevecotton** [comment]
Added to the roadmap for 1.15.5. I have a local version of the fix, but need to do some playtesting before opening a PR.

**Comment by CelticMinstrel** [comment]
> Should the Corrupted Elf be considered undead, and the Divine Avatar be
something else?

I have no idea about the Corrupted Elf; from the name it doesn't sound like it should be undead, but I don't know anything about what it actually does in the scenario. For the Divine Avatar I almost wonder if she should actually stay as `race-elf`… or something else is also an option. Again, I don't fully understand what she's supposed to be.

**Comment by stevecotton** [comment]
For the prose of the new race description, I'm planning to put in a brief placeholder text: "Compared to the elves of the Great Continent around the time of Wesnoth, the Quenoth Elves are far more suited to life in the desert.". That's minimal, but at the same time the story is going to be told by the campaign itself, and it allows the change to be done and tested in one PR, even if the text is then improved in another later PR.

@nemaara and @CelticMinstrel , does this sound OK to you (or at least, better than having the "pale skin" text)?

**Comment by Wedge009** [comment]
That sounds fine to me, at least.

**Comment by CelticMinstrel** [comment]
I don't have any real issues with that text.

**Comment by eyalroz** [comment]
> Compared to the elves of the Great Continent around the time of Wesnoth, the Quenoth Elves are far more suited to life in the desert.

This is slightly problematic. First, you don't describe a race merely via a comparison to another race. (Actually, that's an issue with the text for Elves). Second, there needs to be some description of their physical features, mentioning the effect of many years  in the desert; and of aspects of their culture, e.g. their taking to riding animals, their worship of the goddess, their use of sun magic. None of this spoils the campaign at all. Finally, a link, if possible, to the page on (regular) Elves would be a good idea too.

However - if this is supposed to be just a placeholder then it's certainly much better than the current state of affairs.

**Comment by CelticMinstrel** [comment]
> However - if this is supposed to be just a placeholder then it's certainly much better than the current state of affairs.

I was assuming it as only meant as a placeholder. I said I had no issues with that assumption in mind.
