### ISSUE TITLE
UtBS Dark Assassin declared an "Orc"

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#4879]
Wesnoth 1.15.3
Under the Burning Suns
Multiple scenarios, but specifically - Out of the Frying Pan

The Dark Assassin's race is shown as "Orc" - before and after he reveals himself. That doesn't make sense. Before, it should be unknown, and afterwards he should be an elf. (By "afterwards" I mean during dialogue, he's no longer active as a unit).

**Comment by doofus-01** [comment]
This should no longer be an issue, as of #4906
