### ISSUE TITLE
LoW S4: Avoid use of 'men' to refer to majority female groups

### ISSUE THREAD

**Issue by joeljpa** [wesnoth/wesnoth#4880]
* Is the text in English? If not, what language is it in? 
English.

* What campaign does the text appear in? If it's not in a campaign, say where it is: 
Legend of Wesmere: The Elvish Treasury

* Please quote the text verbatim. You can use `**bold**` to point out the mistaken part:
Cleodil: "We are free! My lord Kalenz, from this day forward I and my **men** are your sworn followers."

* _(optional)_ What do you propose to change the text to?
"Men"? Odd choice of a word from her, given that they're elves.  She's a druidic type with a following of mostly females - her main all-female druids in addition to neuter? gender Woses and okay, male elvish scouts. **"People"** sounds like a lazy but easy replacement.

**Comment by Wedge009** [comment]
I read the 'men' as the soldiers under her command. Not necessarily male, not necessarily human.

I haven't re-read the surrounding dialogue, but I imagine 'my guard' might be a suitable replacement.

**Comment by CelticMinstrel** [comment]
It's definitely a _little_ odd to use "men" to refer to a group that's majority-female and non-human. Probably not unprecedented, but a little odd.

**Comment by Wedge009** [comment]
Not unprecedented. Was just re-watching Star Wars: The Clone Wars (so not an insignificant piece of media), the episodes dealing with the liberation of Ryloth. In addressing his fellow natives, the leader of the resistance movement addresses his compatriots as '**Men** of Ryloth'. In one sense it might sound odd, but I understood what he meant in the same way as I understood the words of Cleodil (or at least the intent of the author).

**Comment by joeljpa** [comment]
I think one of the main reasons some of us find this odd at first glance is, this being high-fantasy, LOTR comes to our mind....where "men" is always used to denote just humans .

_Gandalf: It is in Men that we must place our hope.
Elrond: Men? Men are weak._

**Comment by Wedge009** [comment]
I was going through this recently with respect to Wesnoth races and humans as a race are generally referred to as humans, not men. There's also precedent for 'men' referring to non-humans in other places:
Konrad often refers to his followers as 'men' and many/most of them would have been elves.

Kalenz calls his fellow elves 'men:
https://github.com/wesnoth/wesnoth/blob/3fcba6aa1c3636e531a159bd5e55fd959f17232b/data/campaigns/Legend_of_Wesmere/scenarios/chapter1/03_Kalian_under_Attack.cfg#L1124-L1125

Olurf calls his fellow dwarves 'men':
https://github.com/wesnoth/wesnoth/blob/3fcba6aa1c3636e531a159bd5e55fd959f17232b/data/campaigns/Legend_of_Wesmere/scenarios/chapter2/07_Elves_Last_Stand.cfg#L502-L503

Likewise Hamel also calls his fellow dwarves 'men':
https://github.com/wesnoth/wesnoth/blob/3fcba6aa1c3636e531a159bd5e55fd959f17232b/data/campaigns/Northern_Rebirth/scenarios/02_01_Infested_Caves.cfg#L929-L930

Kapou'e calls his fellow orcs 'men':
https://github.com/wesnoth/wesnoth/blob/3fcba6aa1c3636e531a159bd5e55fd959f17232b/data/campaigns/Son_Of_The_Black_Eye/scenarios/12_Giving_Some_Back.cfg#L236-L237

Zhul of the Quenoth Elves refer to her kin as 'men':
https://github.com/wesnoth/wesnoth/blob/3fcba6aa1c3636e531a159bd5e55fd959f17232b/data/campaigns/Under_the_Burning_Suns/scenarios/01_The_Morning_After.cfg#L1377-L1378

So it's not just the Legend of Wesmere author that does this. In view of this I'll close this shortly unless there's strong objection.

**Comment by CelticMinstrel** [comment]
I also want to add that "people" probably isn't the correct replacement here, if we're going to replace it. I do think replacing it would be good in all four cases, but I don't think it's a priority either.

**Comment by Wedge009** [comment]
There's quite a few more instances of non-human 'men' than the examples I gave here, BTW. Which is my point about this already being an apparent convention in Wesnoth prose.

So do you want to keep this open as a reminder for such a possible future change, then?

**Comment by CelticMinstrel** [comment]
I think avoiding the use of "men" for a mixed-gender (and especially all/mostly female) group is objectively a good thing, yes. The titular example from Cleodil seems to be just one of the most extreme cases of it.

On the other hand, I don't think there's a problem using it for almost-humans. At least for orcs and elves, I think it's fine to use "men" for an all-male group. So your Kapou'e quote above is actually fine, in my opinion. (There's still merit to replacing it if we wanted to, but no strong reason to from my perspective.)

**Comment by Wedge009** [comment]
Do we know for certain that Cleodil is referring to her fellow shamans in that phrase? (I suppose there is a later scenario where Cleodil and shamans are absent from the recall list, when Landar insists on going to war against the saurians.) I was just thinking of The South Guard where Ethiliel is travelling in the company of her bodyguards which, I think, are male riders.

But I suppose the point stands. I'm comfortable with the term, given the archaic medieval tone I understand Wesnoth goes for, but I understand most people don't feel that way about things, especially in the current social climate. Anyway, given your points I'll let this remain open.

**Comment by CelticMinstrel** [comment]
I'm comfortable with it when it refers to an all-male group. It doesn't make any sense when it refers to an all-female group.

**Comment by Wedge009** [comment]
Fair enough. Renamed the issue to refocus on the gender inconsistency vs the racial meaning.

**Comment by Wedge009** [comment]
I re-reviewed all 265 or so instances of 'men' in the campaign prose and I think this is the only case where it could plausibly seem contradictory to use the term - taken out of context, 'men' could easily be appropriate as it is in so many other cases. The only reason I can see why it's not here is because when Cleodil is freed, a druid and sorceress are released along with her.

I considered substituting 'maids' or 'maid-servants', but I don't recall any indication that Cleodil is necessarily of high standing among the elves (other than being a major character within the story), and somehow I feel those terms are more appropriate for human culture rather than elven. Similarly for 'followers', as well as the word followers being used later in the same sentence. 'Sisters' might work, but perhaps too strong connotations of blood relations or association with human nuns. So in the end I settled on 'kin', which also could be used to refer to blood relations but sometimes - and this is my intention here - used for referring to kindred people, people of the same race, or otherwise those more distant than direct family.

I haven't seen anyone come up with a better option than this thus far. (:

**Comment by CelticMinstrel** [comment]
I was also considering "girls", but that also implies they're rather younger, so I dismissed it. I also dismissed "women" because it just doesn't work for me in that context.

I think "kin" works. It's probably not the exact same connotation as "men" but that probably doesn't matter.
