### ISSUE TITLE
Graphical glitches and failed assertion in the map editor on Windows 10

### ISSUE THREAD

**Issue by Equaraphanus** [wesnoth/wesnoth#4883]
### Game and System Information
 - Version 1.14.11
 - Downloaded from SourceForge, link from wesnoth.org
 - OS: Windows 10

### Describe the bug
In some time (40 to 50 minutes) after opening the editor the tiles stop redrawing properly when I move map around. Now they are updated only on mouse over. If you try to quit to main menu, the `assert(surf)` in function `blit_surface` in file `src/sdl/utils.cpp` on line 2012 fails.

### To Reproduce

1. Start Wesnoth
2. Open the map editor
3. Play around with it for about 50 minutes
4. *Graphical glitches appear*
5. Quit to main menu
6. Assertion failed: `surf` in function `blit_surface`

### Expected behavior
Graphical glitches do not appear and the editor works as intended

### Screenshots
![image](https://user-images.githubusercontent.com/53881077/80843763-c709e780-8c0d-11ea-861a-1661a46e22f1.png)
![image](https://user-images.githubusercontent.com/53881077/80839811-a0937e80-8c04-11ea-822a-bf4245f1abf3.png)

**Comment by Pentarctagon** [comment]
This is an instance of #4855
