### ISSUE TITLE
Units get healed on recall

### ISSUE THREAD

**Issue by virtualghetto** [wesnoth/wesnoth#4888]
### Game and System Information
Wesnoth 1.14.9
Debian sid

### Describe the bug
Injured units that are placed on the recall list with `[put_to_recall_list] heal=no` get fully healed once recalled.

Details are on this thread.
https://forums.wesnoth.org/viewtopic.php?f=21&t=52253

### Expected behavior
The unit to remain injured when recalled.

**Comment by gfgtdf** [comment]
fixed this for 1.15, for 1.14 this would be a compatability  break that could among other things also cause OOS, so i currently would just leave it as-is for wesnoth 1.14

**Comment by virtualghetto** [comment]
Thank you.
