### ISSUE TITLE
Mainline campaign uses Y UMC terrain code

### ISSUE THREAD

**Issue by virtualghetto** [wesnoth/wesnoth#4891]
### Game and System Information
Wesnoth 1.14.9
Debian sid

### Describe the bug
Under the burning sun campaign defines `^Yl` terrain code which is supposed to be reserved for third party UMC addons and not mainline campaigns.

https://wiki.wesnoth.org/TerrainCodesWML

**Comment by shikadiqueen** [comment]
Mainline campaigns are regarded as add-ons that ship with the game for this purpose. Updated the documentation accordingly.
