### ISSUE TITLE
Mainlining World Conquest II

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4895]
@soliton-  and Yumi have on discord suggested to mainline World conquest II which is the most popular mp campaign where players play in 5 scenarios against ai sides of increasing difficulty. Its highly randomized and has a high replay value. It very little story (people go on an island, people conquer island, people find random allies on island, people to and conquer next island).

At first i was hesitant because it had a few problem wrt to tranlsatability, but i now think these either gone now or actually bugs in the engine.  (wesnothd sometimes removing translation marks (`_` from the wml data is a known problem))

but now i think that both wesnoth would beneit from mainlining a campaign that is for good reason the most played mp campaign. And i also think that at the current point the campaign would benefit from mainlining it, in particular it would of course get translations and maybe someone would even add dunefolk faction to it.

The campaign contains quite a bit of (for newcomers probably rather complex) lua code, i am not saying this is like EraOfHighSorcery but its certainly on a different level than most Mainline campaigns/maps since its adds a few custom mechanics like droppable items, training bonuses for newly recruited units etc.

Mainlining is a little more work than just moving it over, we would need to:
1) think about what we do to its custom terrains in particular whether we mainline them aswell (remove the xyz characters), honestly i'm not really a fan because afaik most of these only exist because of https://github.com/wesnoth/wesnoth/issues/4894
2) I think a few parts of the lua helper function code can also be mainlined in particular the "drop pickup" event implementation that fires whena unit steps on an [item]

So i opened this topic to discuss this issue, and opinion on mainlining WorldConquestII and about (1) ?

**Comment by ghype** [comment]
This was my go to map for years before I started the Dunefolk Rework.

Would this be added as a campaign or just a mp scenario? 
It would feel out of place considering Yumi's rework on the mainline campaigns. Trying to add more story to this would be an attempt to make it more than it is. If it was mainlined, then as mp campaign yes, but one that does not appear in the Campaign Menu.

**Comment by gfgtdf** [comment]
> Would this be added as a campaign or just a mp scenario?

Depends on what you mean here.

> one that does not appear in the Campaign Menu.

Are you talking about the singeplayer campaign menu here (titlescreen -> Campaigns)? Then obviously not, For the mp menu  (titlescreen -> Multiplayer -> ... ->create game -> ) i'm not sure wehther it'd fit better in campaign  section or in the random maps section.

**Comment by Pentarctagon** [comment]
@nemaara is Yumi here btw.

**Comment by Pentarctagon** [comment]
@gfgtdf Out of curiosity, does WCII pass WML schema validation?

**Comment by gfgtdf** [comment]
>@gfgtdf Out of curiosity, does WCII pass WML schema validation?

I don't know, on the one hand it defines.quite.some custom actionwml tags which could make is less likely, on the other hand is uses very little wml in the first place and even those chus wml tags are usually called from lua or from lua generated wml code. So in conclusion my guess would be yes, simply because is contains so little wml, but I'm not sure

**Comment by Wedge009** [comment]
Just wondering: what was World Conquest I? I suppose it should be left named as World Conquest II if it is to be included in main Wesnoth but as a newcomer I would be curious to know what happened to World Conquest I.

**Comment by gfgtdf** [comment]
> Just wondering: what was World Conquest I? I

So there was first a similar add-on on that add-on server called world conquest, and then sometime modified it and uploaded his own version and called it world conquest II at some point.

**Comment by ghype** [comment]
> i'm not sure wehther it'd fit better in campaign section or in the random maps section.
intuitively I would say it would belong to random maps at it basically using the settings every players knows to create random maps. I never looked at WC as campaign just because it had multiple scenarios, a bit of dialogue and special events. It feels more like a sophisticated version of the "random maps" generator.

**Comment by gfgtdf** [comment]
So for the customs terrains, i for now decided just remove the custom terrain mod from the mainline version.

**Comment by Pentarctagon** [comment]
Closing as this has since been mainlined.
