### ISSUE TITLE
Game aborts when selecting Custom Maps drop down menu.

### ISSUE THREAD

**Issue by virtualghetto** [wesnoth/wesnoth#4897]
### Game and System Information
1.14.11
Compiled from source tag 1.14.11
Debian buster

### Describe the bug
Selecting the multiplayer 'Custom Maps' drop down menu will raise an assertion fail and abort immediately if the folder editor/maps includes a map that has custom UMC terrains.

Details are in this thread.
https://forums.wesnoth.org/viewtopic.php?f=4&t=52477

The error shown:

    Battle for Wesnoth v1.14.11
    Started on Sat May  9 12:23:54 2020
    
    MESA-LOADER: failed to retrieve device information
    
    Data directory:               /home/USER/local/games/wesnoth/1.14/share/wesnoth
    User configuration directory: /home/USER/.config/wesnoth/1.14
    User data directory:          /home/USER/.local/share/wesnoth/1.14
    Cache directory:              /home/USER/.cache/wesnoth
    
    Setting mode to 1024x768
    Checking lua scripts... ok
    20200509 12:24:00 error config: map could not be loaded: Unknown tile in map: (Yw) 'Yw'
    20200509 12:24:00 error config: map could not be loaded: Unknown tile in map: (Yw) 'Yw'
    wesnoth-1.14: /usr/include/boost/dynamic_bitset/dynamic_bitset.hpp:644: boost::dynamic_bitset<Block, Allocator>::~dynamic_bitset() [with Block = long unsigned int; Allocator = std::allocator<long unsigned int>]: Assertion `m_check_invariants()' failed.
    Aborted

**Comment by Pentarctagon** [comment]
I can reproduce this on 1.14.11, but not 1.14.11+dev.  If you're able to, can you try recompiling with the latest code from the 1.14.11 branch and let me know if it still happens?

**Comment by gfgtdf** [comment]
Afaik this is on the tracker already, but I cannot find it rn

**Comment by virtualghetto** [comment]
Compiled and tested it on 1.14.11+dev 1886fe0d9e9.
It did not abort or crash. In fact, it listed the file and showed a small error message about the terrain.

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/issues/4395
