### ISSUE TITLE
Boost unit tests logging changes when LTO is enabled

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#4898]
After adding the following code to the start of the function [here](https://github.com/wesnoth/wesnoth/blob/6eeab88c5e448051a60fd27ccd40a6e627274c6a/src/gui/auxiliary/iterator/policy_order.hpp#L79):
```
if(lg::debug().dont_log(gui2::log_gui_iterator))
{
    std::cout << "debug not enabled" << std::endl;
}
```

[This](https://github.com/wesnoth/wesnoth/files/4605285/noLTO.log) is the output of the non-LTO run, and [this](https://github.com/wesnoth/wesnoth/files/4605286/LTO.log) is the output for the LTO run.

Requires GCC 9, since with GCC 7 the boost unit tests segfault.

**Comment by Pentarctagon** [comment]
After some investigation, what seems to be happening is that LTO is re-ordering when [this line](https://github.com/wesnoth/wesnoth/blob/acd08fd0c51f9f5e71ac8d0c5d1679d1c8a4876e/src/tests/gui/iterator.cpp#L271) gets executed.  After adding `std::cout << "first logger set" << std::endl;` after that line, with a [debug build](https://pastebin.com/q5ANc6kG) it gets executed before the tests, but with an LTO build it gets executed [after the tests](https://pastebin.com/6SfnVRfu).

`gcc --version` reports "gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0"

**Comment by Pentarctagon** [comment]
Marking as an upstream issue, since I'm fairly sure code isn't supposed to be able to be reordered like that.

**Comment by gfgtdf** [comment]
If you are marking this as an upstream issue you should file a bugreport at boost and link it here.

**Comment by gfgtdf** [comment]
preferably you would also create a  minimalisitc test case. that runs independend of the wensoth code.

**Comment by Pentarctagon** [comment]
The problem is I don't know why LTO would think it's safe to reorder the code the way it appears to be doing, so I don't really have any idea how to create a minimalistic test case either.

**Comment by gfgtdf** [comment]
Is this the only test case that is effected by this, or are all the tests reordered?

**Comment by gfgtdf** [comment]
one arrpoach to creatinga  minimialitic test case is to remove stuff until the bug disappears.

**Comment by gfgtdf** [comment]
wait the part that is reordered seens unlreated to boost test suite? test_grid() is calle as a normal function that is called by te function in gui/iterator.cpp#L271

**Comment by gfgtdf** [comment]
tbh this seems to be unrelated? Do you know where the other lines  come from ?

**Comment by gfgtdf** [comment]
also, where are the `in constructor...` lines from ?

**Comment by Pentarctagon** [comment]
The `in constructor...` I actually should have removed - I added those as a regular `std::cout` statement after [this line](https://github.com/wesnoth/wesnoth/blob/96369589e60832e1515508a1ee72fe159b30f6b3/src/gui/auxiliary/iterator/policy_order.hpp#L48).

As a side note as well, clang does not change the logged output when LTO is enabled.

**Comment by gfgtdf** [comment]
> After some investigation, what seems to be happening is that LTO is re-ordering when this line

okay then what exactly does this output proof?  in both cases the `first logger set` lines is followed by 6 `in constructor...` lines. To most likely these 6 lines come form the inside if the gui iterator test. In one of them there are  a few more `in constructor...` lines but they most likely come form another test. I'd think its perfectly legal to reorder in which order the tests are exceuted.

**Comment by Pentarctagon** [comment]
The issue is that the `first logger set` line is where the logging level is set to debug.  In the debug build this happens prior to the tests being run, which is why there's additional log output, whereas is the LTO build this happens after the tests which is why there's less log output.

**Comment by gfgtdf** [comment]
Well yes but you have  to watch out what you mean by 'the test' here: there are many tests, and i see no reason why it should not be  totally legal to for example run the `test_gui2_visitor` before or after the `test_gui2_iterator`, the later one is the one that prints `first logger set` while the `in constructor...` might come form any test.

**Comment by gfgtdf** [comment]
what i'm saying is: i think if we change all tests to clean up their changes to the log settings we should be fine. probabl nough to call  `lg::set_log_domain_severity("all", lg::warn());` at the end of any test that changes the log settings.

**Comment by Pentarctagon** [comment]
To be completely clear then:
* The `in constructor...` text should just be ignored - I should have removed that before uploading the log.
* The [line](https://github.com/wesnoth/wesnoth/blob/96369589e60832e1515508a1ee72fe159b30f6b3/src/tests/gui/iterator.cpp#L271) setting the logging level to debug comes almost immediately before the call to [the method](https://github.com/wesnoth/wesnoth/blob/96369589e60832e1515508a1ee72fe159b30f6b3/src/tests/gui/iterator.cpp#L278) that creates the log statements that are missing for the LTO build.  Instead setting `lg::set_log_domain_severity("gui/iterator", lg::debug());` in the constructors in [policy_order.hpp](https://github.com/wesnoth/wesnoth/blob/master/src/gui/auxiliary/iterator/policy_order.hpp) fixes this.
* The LTO build also still has some extra `info engine` level logging that the non-LTO build doesn't have, which I don't think(?) would be related to any test.

**Comment by gfgtdf** [comment]
> before the call to the method that creates the log statements that are missing for the LTO build

im not sure to which lines you are referring to here.

> The LTO build also still has some extra info engine level logging that the non-LTO build doesn't have, which I don't think(?) would be related to any test.

the unit_map_test calls `lg::set_log_domain_severity("engine", lg::info());`

**Comment by Pentarctagon** [comment]
> im not sure to which lines you are referring to here.

The lines I linked to.

**Comment by gfgtdf** [comment]
> The lines I linked to.

can you cite them ? i see no lines in the debug log that looks like it would  be generated from the `test_grid()` call.

**Comment by Pentarctagon** [comment]
The while loops that have `/* DO NOTHING */` inside the loop body call the [next()](https://github.com/wesnoth/wesnoth/blob/96369589e60832e1515508a1ee72fe159b30f6b3/src/gui/auxiliary/iterator/policy_order.hpp#L79) method in `policy_order.hpp` place their output in `TST_GUI_I`.  That is used by the redirect_output_setter to check if the test passed or not, but is also output to the terminal when the logging level is set to debug.

**Comment by gfgtdf** [comment]
> The while loops that have /* DO NOTHING */ inside the loop body call the next() method in policy_order.hpp place their output in TST_GUI_I.


This doesn't answer any of my questions. To be clear: in the debug log file, i see nothing except the `first logger set` lines and the `in constructor...` that looks like  it belongs  to the `test_gui2_iterator` test.  The nest line is already `Down widget 'orb_unmoved_brightgreen'.` and since the `test_gui2_iterator` test at no place creates a widget with such an id, i'd assume this line already belongs to another test, which implies that all further lines also belong to different tests.

**Comment by Pentarctagon** [comment]
`Down widget 'orb_unmoved_brightgreen'` comes from `bottom_up_t_t_t_result()`, which is used in the test_grid() method to check that the redirected logged output matches the expected output.  So I'm not sure how that could be part of a different test.

**Comment by gfgtdf** [comment]
> Down widget 'orb_unmoved_brightgreen' comes from bottom_up_t_t_t_result(),

No it doesn't. Bottom_up_t_t_t_result returns a fixed static string that does not contain these lines. 

Also  what i said before still stands: it cannot come from that test because  that tests redirects all log output to local strings.

> So I'm not sure how that could be part of a different test

test_gui2_iterator is not the only test that uses the gui2 widget iterators. THere are multipel tests the test gui2 dialgos that will also call this code in one way or another.

**Comment by Pentarctagon** [comment]
Debugging with vscode, `select_orb_colors.cpp` is where those log statements are being output from, so I apparently got multiple things wrong about this.

As far as tests that change any logging levels, those are `src/tests/test_unit_map.cpp`, `src/tests/gui/iterator.cpp`, and `src/tests/test_formula_function.cpp`.  Adding your suggestion of `lg::set_log_domain_severity("all", lg::warn())` at the end of those tests results in both non-LTO and LTO builds outputting the same log statements, and as a bonus now outputs significantly less since it's no longer logging the orbs added in `select_orb_colors.cpp`.
