### ISSUE TITLE
Wrong chance to hit

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#4902]
### Game and System Information
 - What version of the game are you running?
1.14.11
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Steam
 - What OS are you running?
Windows

### Describe the bug
Attached is a save file at a turn where if you try to attack the shaman right beside the Player's leader, the chance to hit the defender is (100% - Attacker's Terrain Defense).

### To Reproduce
Ive tried repeatedly loading the save and trying to attack the shaman with the Player leader and it always shows the bug. Compare attacking the shaman from the forest and attacking from the flat ground to observe the "chance to hit the defender is (100% - Attacker's Terrain Defense)"

### Expected behavior
It should be chance to hit is the defender's terrain defense.

### Screenshots
![image](https://user-images.githubusercontent.com/41433185/81953149-ea835800-9639-11ea-914e-9ec26eb4e583.png)

Attached Save:
[bug.gz](https://github.com/wesnoth/wesnoth/files/4629342/bug.gz)

I do not know if this bug is scenario specific, I do not know what specific conditions produced a save file that had this bug.

**Comment by ProditorMagnus** [comment]
> chance to hit the defender is (100% - Attacker's Terrain Defense).
Attacker has 50% def.

**Comment by Pentarctagon** [comment]
I'm not sure what the problem is.  The shaman has 30% defense, so the orc has 70% chance to hit; the orc has 50% defense, so the shaman has 50% chance to hit.

**Comment by max-torch** [comment]
Oops, theres no problem... I just got confused... hehe lets just delete this issue.
