### ISSUE TITLE
Map not drawn on smaller resolutions

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4909]
When i try to start any game on a rather small resolution (which i mostly do to workaround #4908) the map is not drawn also the white border in the minimap only shows a very flat box.

![image](https://user-images.githubusercontent.com/4893136/82510411-b6f96f80-9b0a-11ea-9456-eb3b52ff3c5c.png)

**Comment by Pentarctagon** [comment]
This one I suspect may be caused by #4851.

**Comment by gfgtdf** [comment]
doing `git revert 43de778c6aad87^..f3a472ab963a5f` seems to fix this issue aswell.

**Comment by gwhitney** [comment]
Apologies to all -- investigating now -- please can you let me know what resolution this occurs at? And also what roughly your pixel pitch is?

**Comment by gwhitney** [comment]
Just posted PR #4910 to address this. gfgtdf if you could test whether that PR resolves this symptom I'd appreciate it. I may need more info to get at #4908, which I recognize is the more fundamental issue for you, but figured I should fix what I could do quickly first. Thanks!

**Comment by Pentarctagon** [comment]
Confirmed locally that I could reproduce the issue, and the related PR fixes the issue.
