### ISSUE TITLE
custom status breaks status icons in sidebar

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#4921]
### Game and System Information
 - What version of the game are you running?
1.15.3+dev
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
source
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
gcc 04a0fccd5a7 
- What OS are you running?
Linux

### Describe the bug
The status icons, such as the little green skull for poison, are not displayed in the sidebar.  The icons are displayed outside of the campaign, so it's probably not an engine bug.

### To Reproduce

Try to find entangled/poisoned unit in test scenario

**Comment by Pentarctagon** [comment]
When you say that the icons are displayed outside of the campaign, does that mean they display correctly in single player scenarios?

**Comment by doofus-01** [comment]
Yes, a default era MP game for example works fine.

Commenting out the call to theme.lua in the campaign's _main.cfg makes the poison status work again, so I guess that needs to be updated in some way.

**Comment by doofus-01** [comment]
The test scenario seems to have the same problem, and it also uses `wesnoth.interface.game_display.unit_status()`
to show a custom status icon.  I guess it's the LuaAPI that's bugged, though I don't know enough to pin it down any further.

**Comment by gfgtdf** [comment]
the only related recent commit i see is the renaming of wesnoth.theme_items to wensoth.interface.game_display.

@CelticMinstrel  maybe you could fix this?

**Comment by CelticMinstrel** [comment]
So, does the custom status show but not the built-in one?

As far as I know, `theme_items` and `game_display` should be the same Lua object; if not, maybe that's the issue?
