### ISSUE TITLE
Transition bugs with tall encampment and encampment keep & with dwarven castle ruins and dwarven castle keep

### ISSUE THREAD

**Issue by Earth-Cake** [wesnoth/wesnoth#4923]
### Game and System Information
 - Version 1.15.3
 - Steam version of Wesnoth
 - Linux Ubuntu

### Describe the bug
It looks like a bug with transition with tall encampment and encampment keep. I also saw this bug with dwarven castle ruins and dwarven castle keep.

### To Reproduce
Just place terrains like I did on screenshots. For tall encampment it works anywhere, and for dwarven castle ruins it works only when ruined dwarven castles are northeast or northwest.

### Screenshots
![transitionbug](https://user-images.githubusercontent.com/52823609/83079969-43f97700-a07d-11ea-9b0f-6e6b2013c21c.png)
![transitionbug1](https://user-images.githubusercontent.com/52823609/83079973-45c33a80-a07d-11ea-937f-346490b90cd3.png)

**Comment by doofus-01** [comment]
I'll look at it this weekend.
