### ISSUE TITLE
experimental_ai doesn't recruit from extra_recruit

### ISSUE THREAD

**Issue by virtualghetto** [wesnoth/wesnoth#4924]
### Game and System Information
1.14.12
Compiled from source tag 1.14.12
Debian buster

### Describe the bug
When `ai_algorithm=experimental_ai` is enabled for a side, it won't recruit from types given under `[unit] extra_recruit=`. It only recruits from types set with `[side] recruit=`

Details are in this thread.
https://forums.wesnoth.org/viewtopic.php?f=21&t=52539

**Comment by soliton-** [comment]
So you're saying the default AI does recruit those units?

**Comment by virtualghetto** [comment]
Hi,
I included a small demo in the thread, press End Turn to get it going.
If you run it without modifying anything in the demo, the Orcish Warrior will sit there doing nothing, not recruiting or whatever.

If you comment out the line `ai_algorithm=experimental_ai`, it will recruit from the extra_recuit= types which are Orcish Archer and Orcish Grunt. This answers the question above, I think.

If you keep expermiental_ai but uncomment recruit=Goblin Spearman, it will recruit only the Goblin Spearman and never the Archer or Grunt.
Thanks.

**Comment by cooljeanius** [comment]
This is one of the things blocking me from using the new parameter described in #6330 (since that's only available with the experimental AI)

**Comment by cooljeanius** [comment]
> I'm already in the progress of fixing some issues with the Experimental AI. This one is on the list, because it is probably pretty simple to do (whereas #4117 is not).

Oh yeah that one too

**Comment by mattsc** [comment]
While this issue is closed with c1d1ff517a, I want to point out one thing from the commit message:
`Note, however, that the recruit rushers CA is set up for single-leader sides and does not work with multiple leaders, so this is of limited use.`
