### ISSUE TITLE
httt, scenario 14, bats.

### ISSUE THREAD

**Issue by gaojicainiao** [wesnoth/wesnoth#4928]
1-3 bats will attack dwarves then die.
Should the bats and dwarves fight with each other ?

**Comment by Wedge009** [comment]
The dwarves are allied with Konrad's team, so the only enemies are the bats.

https://github.com/wesnoth/wesnoth/blob/3fcba6aa1c3636e531a159bd5e55fd959f17232b/data/campaigns/Heir_To_The_Throne/scenarios/14_Plunging_Into_the_Darkness.cfg#L75-L81

I think the 'guardian' specification is supposed to keep the bats in place until they spot an enemy - namely your approaching party - and they aren't intended to fight the dwarves. Do you have a save game from where you see the bats attacking the dwarves?

**Comment by Wedge009** [comment]
If anyone can replicate, please re-open.
