### ISSUE TITLE
Full attacks not totally displayed in right panel on fullscreen

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [wesnoth/wesnoth#4932]
### Game and System Information
I am running Wesnoth 1.14.2, on Archlinux using community package.
My display has a 1366x768 resolution.
### Describe the bug
If a unit has too many attacks, the whole list on the right panel cannot be displayed while fullscreen: there’s just not enough space for it.
![screenshot](https://user-images.githubusercontent.com/8524154/83531777-acb57900-a4ed-11ea-9306-5a56f1b7093d.png)
(This unit has a third attack called “vector”.)
### To Reproduce
Start a game, go fullscreen, find any unit with at least 3 attacks, hover it, see the problem on the right panel.
### Expected behavior
I would like to be able to read all attacks of a unit, either by descaling the text or scrolling it.

**Comment by Wedge009** [comment]
Thanks for the report. I'd say it's a duplicate, or at least strongly related to, #1994. In both cases we're dealing with units with more than the usual one or two attacks, plus a relatively low resolution screen. The UI isn't designed to scroll where the attacks text exceeds the available space.

**Comment by Wedge009** [comment]
With the introduction of the attack range and type icons, the text length is greatly reduced, plus I also couldn't replicate #1994 any more. Please re-open if you still find this to be an issue.
