### ISSUE TITLE
MinGW Runtime Assertion Failed

### ISSUE THREAD

**Issue by GaussLM** [wesnoth/wesnoth#4934]
### Game and System Information
 - Wesnoth 1.14.12
 - Downloaded from Steam
 - Windows 10 Pro, Version 1909 (OS Build 18363.836)

### Describe the bug
While playing, program crashed with an 'Assertion failed!' error (see screenshot below).

Second scenario of The South Guard.  At the beginning, after the player characters have some dialogue the screen scrolls to show the enemy Thief, then scrolls further to the enemy Outlaw, who has some dialogue.  Crash occurred after second scroll, before dialogue.

Problem does not occur again on reloading scenario.

I experienced a similar crash an hour or two prior on the Into the Depths scenario of The South Guard, but didn't think to screenshot or take notes so I can't say it was exactly the same error, and I continued without problems after reloading from the latest autosave.

### To Reproduce
Unable to reliably reproduce.  Happened twice so far on different scenarios but in both cases did not recur after loading from most recent autosave.

### Screenshots
![MinGW Runtime Assertion](https://user-images.githubusercontent.com/66341456/83584399-109f6800-a515-11ea-8913-5603edf96746.jpg)

### Savefiles
[TSG-Proven by the Sword.gz](https://github.com/wesnoth/wesnoth/files/4720473/TSG-Proven.by.the.Sword.gz)

**Comment by Pentarctagon** [comment]
This looks to be the same issue as #4855, so closing as duplicate.

Next time it happens though, it would be helpful if you can upload your logs to #4855.
