### ISSUE TITLE
A unit is broken in scenario three of Under the Burning Suns [spoilers]

### ISSUE THREAD

**Issue by 123chess456** [wesnoth/wesnoth#4945]
### Game and System Information
Version 1.15.3, Windows, downloaded from Wesnoth.org

### Describe the bug
In Scenario 3 of Under the Burning Suns, Garak, a Quenoth Champion, is given the "righteous rage" ability on both of his attacks. The ability is described as basically being the same as berserk from a Dwarf Berserker, yet Garak's attacks function normally and do not "berserk".

### To Reproduce

1. Play Under the Burning Suns
2. Get to Scenario 3
3. Attack a unit with Garak
4. Garak will oftentimes leave the enemy still alive

### Expected behavior
Garak should either kill the enemy or die doing so.

**Comment by soliton-** [comment]
`righteous rage` only works on the champions. Since presumably the description did not make that clear feel free to suggest an improved description.
