### ISSUE TITLE
OOS and bugs caued by select events during other events.

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#4946]
the following code 
:
```

	[event]
		name=enter_hex
		first_time_only=no
		[filter]

.....
		[/filter]
....
		{DELAY 1000}
		[/modify_unit]
			[filter]
				x,y=$x1,$y1
			[/filter]
....
		[modify_unit]
	[/event]
```

might fail randomly if the scenario uses custom menu items and causes OOS erros because if the user righclicks somewhere during the [delay] the code that evaluated the menu items filter will set the x1,y1 variables to the location that was righclicked on.

**Comment by Pentarctagon** [comment]
This is fixed, then?

**Comment by gfgtdf** [comment]
yes
