### ISSUE TITLE
Can not connect to Add-ons

### ISSUE THREAD

**Issue by rubyFeedback** [wesnoth/wesnoth#4957]
When I do, the window appears connecting to add-ons server
but nothing happens. Would it be possible to add some button
to show which command is used? Perhaps wesnoth is using
some external program that breaks; right now we don't see
what happens.

https://i.imgur.com/61XasKG.png
[image](https://i.imgur.com/61XasKG.png)
(I fail at embedding the image directly...)

It stays like this as-is forever.

Version 1.14.12, all compiled from source on linux (I compile
everything from source).

**Comment by Pentarctagon** [comment]
Can you try again now and confirm whether it still gets stuck?
