### ISSUE TITLE
Credits / about out of sync between 1.14 and git master

### ISSUE THREAD

**Issue by ivanovic** [wesnoth/wesnoth#4959]
### Game and System Information
 - irrelevant

### Describe the bug
The credits between 1.14 and master are significantly out of sync. Some data was added to the 1.14 credits only, other data was added to master only. For the information on the website we always use master assuming that changes to stable are forward ported to master as well.

### To Reproduce

1. get a checkout of 1.14 and master
2. copy data/core/about.cfg from 1.14 to master
3. run git diff on master, resulting diff: https://pastebin.com/2jR7rLRy

### Expected behavior
No extra credits added in diff in master, especially existing name entries are identical. Removals are expected though since master might contain more content than 1.14. But names should not be gone of the obviously updated name entries be reverted.

This might also be an issue for the about sections in the various campaigns _main.cfg files. This issue also affected the translation credits (especially German translation) and was fixed there in master.

### Screenshots
N/A

### Savefiles
N/A

### Additional context
resulting diff: https://pastebin.com/2jR7rLRy

**Comment by stevecotton** [comment]
The campaigns still need checking, but the main about.cfg file was already mostly in sync. After backporting two corrections to 1.14 (the number in newfrenchy83's name, and iKevinY changing to Kevin Yap), every entry in 1.14 lines up with one in master.

In master, "Astrid Halberkamp" should change to "Astrid Halberkamp (bumbadadabum)".

**Comment by stevecotton** [comment]
> In master, "Astrid Halberkamp" should change to "Astrid Halberkamp (bumbadadabum)".

@Asheviere, would you prefer it if the nickname was removed from your credits in 1.14? I was about to add it to master, but then saw that it had been deliberately removed in 287ec15c101b030af956d640f04328803c5360e1.

**Comment by stevecotton** [comment]
The campaigns are up to date, although if we backport removing Astrid's nickname then there's an instance in Eastern Invasion's _main.cfg too.

**Comment by stevecotton** [comment]
All done.
