### ISSUE TITLE
Hope Chinese folder path can be compatible.

### ISSUE THREAD

**Issue by gaojicainiao** [wesnoth/wesnoth#4965]
We are running wesnoth on Microsoft Windows 7 and 10.
The Version is 1.14.x.
The language is Simplified Chinese (SC).
We have some problems that wesnoth may exit suddenly before entering main menu at start up.

Here's the conditions I tested:
① Has SC characters in add-ons' path. (Usually Windows' user name)
② Has .po file will be read at start up. (Has .po file can be read for selected language)
③ Install wesnoth in a path which has SC characters.

-①+②=normal
①-②=normal
-①-②=normal
①+②=crash
③=crash
(Less Chinese players will do ③, and it's esay to solve, so it dosen't matter.)

Add a new user on Windows and name it with SC characters in order to create an add-ons' path can be tested. Such as “C:\Users\用户名\Documents\My Games\Wesnoth1.14\data\add-ons”
Use add-on “Captured by a nightmare” to test, it has .po files for Chinese. But it changed to use .mo files, so change to use .po files manually.

Don't worry too much about it. And thank you for all your work for wesnoth.

**Comment by gfgtdf** [comment]
Shouldn't be too hard to fix, we had the types of issues before with other parts code. and now the person to added the code to read po files probably just disntk ow that you cannot use the standard library for reading files.

**Comment by gfgtdf** [comment]
> The Version is 1.14.x.

did you download this via steam or via the wesnoth website ?

**Comment by gfgtdf** [comment]
So we fixed this in the 1.14 branch so the thext 1.14 release will no longer have this problem.

**Comment by gaojicainiao** [comment]
> > The Version is 1.14.x.
> 
> did you download this via steam or via the wesnoth website ?

The offline installer version and the steam version have the same problems.

**Comment by gaojicainiao** [comment]
> So we fixed this in the 1.14 branch so the thext 1.14 release will no longer have this problem.

Thank you!

**Comment by gfgtdf** [comment]
> The offline installer version and the steam version have the same problems.

well yes but for steam we might be able to  deploy an update quicker.

**Comment by gfgtdf** [comment]
this isnt on master yet afaik

**Comment by Pentarctagon** [comment]
Yep, that's why I added the Fwdport tag.

**Comment by gfgtdf** [comment]
yes i just  explained why i reoponed it.

**Comment by gaojicainiao** [comment]
Sorry for my mistake...
