### ISSUE TITLE
[macOS] Support new Apple Silicon

### ISSUE THREAD

**Issue by hrubymar10** [wesnoth/wesnoth#4967]
On WWDC 2020 Apple announced that they will move to the their new ARM64 CPUs.

I was able to compile wesnoth from `1.14.13` tag for that new `arm64` arch, but I wasn't of course able to link it against our [MacCompileStuff](https://github.com/hrubymar10/MacCompileStuff) which is `x86_64` only.

So far it looks that we (I) only have to rebuild all MacCompileStuff libs to be Mach-O fat libraries with both `x86_64` and `arm64` slices.

### MacCompileStuff status:
| Library          | MCS version | latest version | Status             | Note |
|------------------|:-----------:|:--------------:|:------------------:|------------------------|
| **Boost**        | 1.74.0      | 1.74.0         | :x:                | Build-time linking fails with unknown/unsupported architecture name for: -arch armv4t. [Logs](https://gist.github.com/claui/2115daa9fa1b6f6d976846c34894144d) |
| **Cairo**        | 1.16.0      | 1.16.0         | :white_check_mark: | works |
| **Fontconfig**   | 2.13.1      | 2.13.1         | :warning:          | works with [patch](https://github.com/Homebrew/homebrew-core/pull/57999) |
| **Freetype**     | 2.10.2      | 2.10.2         | :white_check_mark: | works |
| **Fribidi**      | 1.0.10      | 1.0.10         | :white_check_mark: | works |
| **Gettext**      | 0.21        | 0.21           | :white_check_mark: | works |
| **Glib**         | 2.64.5      | 2.64.5         | :white_check_mark: | works |
| **GNU Readline** | 8.0.4       | 8.0.4          | :white_check_mark: | works |
| **Graphite2**    | 1.3.14      | 1.3.14         | :white_check_mark: | works |
| **harfbuzz**     | 2.7.1       | 2.7.1          | :white_check_mark: | works |
| **libffi**       | 3.3         | 3.3            | :warning:          | works with [patch](https://github.com/Homebrew/homebrew-core/pull/58092) |
| **libogg**       | 1.3.4       | 1.3.4          | :white_check_mark: | works |
| **libpng**       | 1.6.37      | 1.6.37         | :white_check_mark: | works |
| **libvorbis**    | 1.3.7       | 1.3.7          | :white_check_mark: | works |
| **Pango**        | 1.46.1      | 1.46.1         | :x:                | [Logs](https://gist.github.com/mistydemeo/3fe2f77f927f1df8513197d7acff08cb) |
| **pcre**         | 8.44        | 8.44           | :warning:          | works without `--enable-jit` |
| **Pixman**       | 0.40.0      | 0.40.0         | :white_check_mark: | works |
| **SDL2**         | 2.0.12      | 2.0.12         | :grey_question:    | unknown |
| **SDL2_image**   | 2.0.5       | 2.0.5          | :grey_question:    | unknown |
| **SDL2_mixer**   | 2.0.4       | 2.0.4          | :grey_question:    | unknown |
| **SDL2_net**     | 2.0.1       | 2.0.1          | :grey_question:    | unknown |
| **SDL2_ttf**     | 2.0.15      | 2.0.15         | :grey_question:    | unknown |

> Source: [Homebrew's issue](https://github.com/Homebrew/brew/issues/7857)
> 
> Last updated 2020/08/23

### Notes:
* Apple said that they will soon start sending PRs to all major libs with their `arm64` support.
* ~~We will be probably able to use same libraries from MacCompileStuff also for iOS version @singalen .~~ This isn't true. For example SDL2 will even with `arm64` macOS use Cocoa backend instead of iOS' UIKit one.

**Comment by Vultraz** [comment]
Do we need one of the hardware devkits at all?

**Comment by hrubymar10** [comment]
I would like to have one, but you can't buy it. You can just "rent" it and return it to apple later.

We can cross-compile to ARM64 on Intel and when there will be official Mac with Apple Silicon we can test it on it. I expect that MacBook with ARM64 CPU will be available in October 2020 and I will probably buy one for myself at day one so I will be able to test Wesnoth on it.

**Comment by hrubymar10** [comment]
### Update 2020/07/31:
* Added table with Apple `ARM64` status of libs used in MacCompileStuff
* Added note that it isn't true that we will use same libs for macOS and iOS

**Comment by mistydemeo** [comment]
Pango will build with an upstream patch that will be in the next release; you can see it in Homebrew's package: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pango.rb#L10-L16

That patch also requires a glib patch to support it.

**Comment by ryandesign** [comment]
Wesnoth 1.14.13 appears to run great on Apple Silicon Mac DTK.

For SDL2 2.0.12 you'll need this patch:

https://github.com/macports/macports-ports/blob/253d4dcdf2bb4530caf7047b2055401e54c809fd/devel/libsdl2/files/arm.patch

For boost 1.71.0 we use this patch:

https://github.com/macports/macports-ports/blob/7bc2c0e6fa0dd7a5b331da8cf8eca4f8560772ac/devel/boost/files/patch-add-support-for-arm64.diff

Not sure if that patch will need changing for boost 1.74.0.

**Comment by hrubymar10** [comment]
@ryandesign Thank you for your informations.

I expect that you are talking about native arm64 build?

Can you verify Roseta 2 version too? Is it somehow usable? Also so far I expect that only version 1.15 and 1.16 will be the native one and then I will think about backporting 1.14 .

**Comment by ryandesign** [comment]
> I expect that you are talking about native arm64 build?

Right, compiled by MacPorts.

> Can you verify Roseta 2 version too? Is it somehow usable?

Your Intel binary of 1.14.13 seems to run fine too.

**Comment by sevu** [comment]
Wonder what part uses pcre. I recall that it has a bug with compiler optimisation, there's some patch floating around, but the other way is to just build it with `-O0`.
https://bugs.exim.org/show_bug.cgi?id=2173#c1

**Comment by hrubymar10** [comment]
All MacCompileStuff libs are now universal. Xcode project was update in 1d5448fb0c3038fb158fb3f90e936c84dea2abe1

Closing
