### ISSUE TITLE
[object] duration=turn does not work as specified in the wiki

### ISSUE THREAD

**Issue by nemaara** [wesnoth/wesnoth#4989]
### Game and System Information
 - What version of the game are you running?
This bug is present in 1.14.5, 1.14.13, 1.15.3, and master.

### Describe the bug
As the title states. Using duration=turn inside an [object] tag does not cause the object to be lost on turn refresh as stated in the wiki.

### Expected behavior
The object's effects should be lost on turn refresh, but they are not.

### Savefiles
The savefile has a mage in the upper left corner with the ability to reduce enemy resistance on hit. It should only last for 1 turn but it lasts much longer than it should.

[Gns-1-Siege of Fort Helemoor Turn 1.gz](https://github.com/wesnoth/wesnoth/files/4905837/Gns-1-Siege.of.Fort.Helemoor.Turn.1.gz)

**Comment by gfgtdf** [comment]
I'm quite sure it does work as expected can you be a bit more concrete about the example  that doesn't work for you ?

**Comment by gfgtdf** [comment]
loading the savefile faiels with `unknown terrain spay`

**Comment by gfgtdf** [comment]
my first guess (since i cannot load the savefile) is: your savefile says turn1, it is possible that object duration, (like healing) is not applied during the first turn. so if you give an enemy an object its oynl removed one the sceond turn or later

**Comment by nemaara** [comment]
Ah that's right. Sorry, false alarm. So it's only petrifies that's not removed since it's a bit of a special case.

**Comment by gfgtdf** [comment]
We can still change the 'don't remove objects on turn 1' behavior in master if we agree that it doesn't make sense.

**Comment by nemaara** [comment]
Doesn't really matter to me either way.
