### ISSUE TITLE
Addons iPad version

### ISSUE THREAD

**Issue by timediv** [wesnoth/wesnoth#4990]
### Game and System Information
 - What version of the game are you running? Latest from AppStore 
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) AppStore 
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - What OS are you running? Latest iPadOS 

### Describe the bug

Connection to Addons server gives
![IMG_0522](https://user-images.githubusercontent.com/5778449/87243774-ea84b600-c438-11ea-93a4-9f1e879c49c9.jpeg)

### Expected behavior
Opens list of addons

**Comment by Pentarctagon** [comment]
This looks like the same issue as #4903.  @timediv Would you be able to answer the questions soliton asked the other user on that issue?
