### ISSUE TITLE
The campaign outro's font doesn't render Cyrillic characters

### ISSUE THREAD

**Issue by kabachuha** [wesnoth/wesnoth#5007]
### Game and System Information
 - What version of the game are you running? 1.14.13 and 1.15.3+dev
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) 1.14.13 from the official site, 1.15.3+dev is custom
 - If you're using a custom build, what compiler did you use, and what commit did you build at? 1.15.3+dev was built from https://github.com/wesnoth/wesnoth/commit/a9a7b726e4593270f9010a8947c03a3a58548679 using MS Visual Studio 2019.
 - What OS are you running? Windows 10

### Describe the bug

The campaign outro's font doesn't render some characters (including Cyrillic) properly leaving them as squares with four numbers in the corners.

### To Reproduce

1. Change the language of the game to one that uses Cyrillic characters (e.g. Russian).
2. Finish a campaign to get the outro screen.
3. Look at what is supposed to be "The End" text.

### Expected behavior

I expected that the characters will render a localized variant of "The End".

### Screenshots

The bug on 1.14.13 with Russian language:
![1 14](https://user-images.githubusercontent.com/14872007/88484408-fdd66c00-cf76-11ea-9a26-cba2523d4bd7.png)

The bug on 1.15.3+dev with Russian language:
![1 15](https://user-images.githubusercontent.com/14872007/88484413-02028980-cf77-11ea-82d0-587a2f8c6ce6.png)

The English version works fine:
![1 14eng](https://user-images.githubusercontent.com/14872007/88484460-32e2be80-cf77-11ea-9264-ef0f0d65ad68.png)

### Additional context

I think the problem can be solved by changing the outro font to be more supportive of Unicode characters.

**Comment by Wedge009** [comment]
I think it's known that we have issues with fonts for Windows. Would you mind having a look through #1549 and seeing if any of that discussion is relevant to your report or do you think we should keep this report separate?

**Comment by kabachuha** [comment]
Hello, @Wedge009 ! Indeed, both issues are connected as we pointed it out in the dev channel. @loonycyborg made a fix for the problem yesterday by forcing Wesnoth to use the fontconfig at his branch https://github.com/wesnoth/wesnoth/tree/use_fontconfig (commit https://github.com/wesnoth/wesnoth/commit/ec67098fbf90eae09f686b2ee86dd8dc195289e6). However, for now it's unclear whether this fix can break something, but when I tested the fix on my Windows both the outro screen characters and the language screen ones were rendered correctly. So I think if it will be implemented, it will close both issues.

**Comment by Pentarctagon** [comment]
@Vultraz Do you know if there's another font that would fit here that has wider character support?

**Comment by Wedge009** [comment]
Any objection to closing this in favour of #1549?

**Comment by kabachuha** [comment]
Yeah, I think this specific issue can be closed now. (and we fixed the case with Russian by switching to another font)
