### ISSUE TITLE
Game lobby selectors broken after scrolling down

### ISSUE THREAD

**Issue by mwlon** [wesnoth/wesnoth#5009]
### Game and System Information
 - What version of the game are you running? 1.14.13
 - Where did you download it from? https://sourceforge.net/projects/wesnoth/
 - If you're using a custom build, what compiler did you use, and what commit did you build at? (no)
 - What OS are you running? MacOSX

### Describe the bug
The game lobby menu selectors are glitchy if you scroll down (see video link in screenshot)

### To Reproduce
1. start wesnoth > multiplayer > local game
2. pick any map with several players; e.g. Merkwuerdigliebe, create game
3. start setting everyone to Computer Player, optionally setting the AI
4. scroll down
5. try setting more players to Computer Player, and you will be unable to; it will open the wrong selector and not do what you want

### Expected behavior
Selectors to work clearly, rather than having other hidden selectors in front of them after scrolling down

### Screenshots
https://gfycat.com/welldocumentedmilkycranefly

**Comment by AI0867** [comment]
Looks like an instance of #2897 to me. Thanks for the video evidence!

**Comment by Wedge009** [comment]
It does sound like the same or at least similar issue to me as well.

**Comment by mwlon** [comment]
@AI0867 @Wedge009 Thanks. I notice the other issue is from 2 years ago though - is anyone working on this?

**Comment by Wedge009** [comment]
I don't think there's any active work at the moment. I think @Vultraz was primarily responsible for the redesign of the MP Lobby, but in #2897 notes that he could not replicate this issue.

**Comment by gfgtdf** [comment]
This is still an updateam bug right? Did you file an upstream bugreport ?

**Comment by Wedge009** [comment]
Any objections to closing this in favour of #2897?

**Comment by mwlon** [comment]
@Wedge009 go ahead, but please link the screen capture from this issue.
