### ISSUE TITLE
Add missing Naga portraits

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5044]
Add 1 new portrait and 3 level up variants for the nagas.

Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.4_.2808.2F22.2F2020.29).

**Comment by Pentarctagon** [comment]
Moving to the 1.17 milestone since I assume these won't be completed by 1.16.

**Comment by knyghtmare** [comment]
I have noticed that the most Naga units have individual portraits already.
Only exceptions:
- Naga Warrior
- Naga Sicarius
- Naga Zephyr
- Naga Hunter (UtBS)

Are these planned or can the issue be closed?

**Comment by Lordbob** [comment]
You may keep the issue open for now. Sicarius and Zephyr are due their own portraits, I need to finish them sometime. Warrior has one also, sitting on my hard drive but it seems I never committed it.
The hunter does have one ; there is a naga with bow portrait that I did previously for UtBS. It had been re-routed as a placeholder before the naga guard line got their portraits, but as far as I can tell it is still being used in UtBS.

[](https://www.wesnoth.org/units/1.16/mainline/en_US/Naga%20Hunter.html)
