### ISSUE TITLE
Create the queryd program

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5051]
Its purpose would be to execute SQL separate from wesnothd, so that queries that could potentially take several seconds or longer to complete won't block wesnothd from continuing to run until the query completes.

Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.6_.2810.2F17.2F2020.29).

**Comment by soliton-** [comment]
How will a separate binary make concurrent, async DB queries easier?

**Comment by Pentarctagon** [comment]
Trying to build a multithreaded query/db connection manager into wesnothd didn't feel like a great alternative.

**Comment by soliton-** [comment]
But that's what you'll still need to communicate with queryd then? Or how should this work?

**Comment by Pentarctagon** [comment]
I was thinking it would be client -> queryd, rather than client -> wesnothd -> queryd.

**Comment by Pentarctagon** [comment]
The idea being that something like retrieving the user's game history could take a fair amount of time (compared to the existing queries wesnothd runs), especially a few years or more down the road for players that play games online frequently, while also isn't required for any functionality within wesnothd itself.  So instead of having wesnothd take the time to execute the query, the client would send queryd something like:
```
[query]
    id=1
    username="user_A"
    password_hash="<hashed password>"
    [parameter]
        value="asdf"
    [/parameter]
    [parameter]
        value="1234"
    [/parameter]
... and so on ...
[/query]
```
and then queryd would send the result of the query back to the client to be displayed.

**Comment by soliton-** [comment]
Oh, I see. Completely unrelated to wesnothd.

I wonder if this would be an opportunity to use a different protocol like for example http/websocket so the same backend could be used to easily show the info on a website...

On the other hand not sure how wise the assumption is that this data will not be used by wesnothd at some point. Still with a separate service we're flexible and in the future the service could still be used by wesnothd or converted to a library to be integrated into wesnothd.

**Comment by Pentarctagon** [comment]
For the moment I was planning to base it on what's available in `server_base` plus the existing wesnothd/campaignd implementations, since those already exist and function, but once that's at least working I do think using something like http or websockets would be good to do.

**Comment by gfgtdf** [comment]
> Trying to build a multithreaded query/db connection manager into wesnothd didn't feel like a great alternative.

Why not? the server is already using boost::asio, which was written to do exactly that: asynchronous io.

**Comment by Pentarctagon** [comment]
From what I've been told previously, wesnothd only uses a single thread for executing the actual logic, so changing that to now also have background threads to handle other requests would, I assume, be a pretty significant design change, as well as potentially not a direction that might be accepted given that IIRC wesnothd did used to be multithreaded but was then changed to not be when it was overhauled to use boost::asio.

**Comment by gfgtdf** [comment]
> From what I've been told previously, wesnothd only uses a single thread for executing the actual logic, so changing that to now also have background threads to handle other requests would, I assume, be a pretty significant design change, as well as potentially not a direction that might be accepted given that IIRC wesnothd did used to be multithreaded but was then changed to not be when it was overhauled to use boost::asio.

two things, first, you can still do "the actual locic" in the single thread. Second i really see no reason so keep the worker single threaded (iirc there were some compiler  problem when trying to make it multithreaded maybe @loonycyborg  knows more.)

Related fun fact: Unlike  the server, the The client network code is multithreaded https://github.com/wesnoth/wesnoth/blob/1.15.3/src/wesnothd_connection.hpp#L124 so that a worker thread does the parsing (char[] data to config objects) and the main thread the rest.

**Comment by Pentarctagon** [comment]
> two things, first, you can still do "the actual locic" in the single thread.

That's one of the main things I was looking to avoid though, since I wouldn't want to block wesnothd's single worker thread for 10 seconds (arbitrary number as an example) every time a long time player wants to look at their game history.

> Second i really see no reason so keep the worker single threaded

Having something be multithreaded automatically makes it more complex and riskier, any other factors aside.  If that's the way it should be done for this, then I'm fine with that, but by default multithreading is something I try to avoid unless it's really needed.

**Comment by soliton-** [comment]
> by default multithreading is something I try to avoid unless it's really needed.

I think this is a good approach and as wesnothd currently shows multithreading is not always needed. I don't think it is needed here either. DB requests are not something that need to block the client. The work is done in the DB process anyway, the client is just waiting. This could be done with asio just as well without the need for threads.

It might be worth looking into https://github.com/anarthal/mysql for example. It says it's proposed for boost so that's a good sign. I'm not sure how it relates to the mariadb/mysql future direction but it's apparently tested with both at least.

That said I wouldn't say it was an issue when wesnothd used multiple threads for the networking part. It was certainly simpler and more robust than the loading screen threading we nowadays do on the client side. So I wouldn't be opposed to reintroducing some threading if it actually helps. mariadbpp seems to have concurrency support...

**Comment by Pentarctagon** [comment]
I'd be hesitant to use it before it formally becomes part of boost, both because it'd be another dependency we'd need to add to wesnoth's repository since it's also not available from any package manager and also because of the possibility of compatibility breaking changes that might be required before it could potentially be added to boost.

**Comment by gfgtdf** [comment]
> That's one of the main things I was looking to avoid though, since I wouldn't want to block wesnothd's single worker thread for 10 seconds (arbitrary number as an example) every time a long time player wants to look at their game history.

I didn't mean locking, you can with boost asio afaik do most part of async io in withotu worker threads, idk whether it used worker threads 'under the hood' i don't _think_ so at least with the current configguation.

In Async io often you call a function that takes a callback function to be called when the result is ready, and this function is not called in another thread, its just called by the main thread from the main "loop", that how we use boost::asio most of the times.

**Comment by Pentarctagon** [comment]
There doesn't seem to be any documentation or examples for mariadbpp's concurrency support, but it *looks* like it would be relatively straight forward to variants to a couple methods in `dbconn.*pp` to execute async queries instead of synchronous ones.  Then have another `boost::asio::steady_timer` (like `dump_stats_timer_`) which would then check for any completed queries every few seconds(?) and send results back to the wesnoth clients, if they're still connected.

**Comment by gfgtdf** [comment]
Hmm i just read the doumentation and (on first sight at least) it seems like the sql client we use cannot queue multiple queries at the same time withotu waiting for the previous ones to finish. I originally expected that is was possible to implement an (C-) api that can be used like  this:
```
...
handle1 = async_query("SELECT whatever from USERS")
handle2 = async_query("SELECT whatever from GAMES")


..
query1_ready= 0;
query2_ready= ß
... result;
while(...) {
..
  if(query1_ready= pull(handle1, &result)){
    //do sometihng with 'result'
  }

..
}
```

**Comment by soliton-** [comment]
> I'd be hesitant to use it before it formally becomes part of boost, both because it'd be another dependency we'd need to add to wesnoth's repository

I assume it'd replace mariadbpp. I don't think it'd make sense to keep both.

No clue on the status of their boost addition or the likelihood of breaking API changes. I just did a quick search for asio+mysql/mariadb.

**Comment by gfgtdf** [comment]
@Pentarctagon  can you reming me what was the reason for the switch to the mariadpp client? I it is that assume that the server is also using mariadb ?

**Comment by soliton-** [comment]
Our own DB functions were not enough for the new functionality.

**Comment by gfgtdf** [comment]
what do you mean by "Our own DB" i thought we were using  some type of mysql api? so the mariadpp offers more functions?

**Comment by Pentarctagon** [comment]
@gfgtdf The server is using mariadb, but mariadbpp also provided an easier way to handle more complex resultsets (and in my own local testing was better able to handle reconnecting in case something happened to the connection itself)  and is what's listed to use on the [mariadb site](https://mariadb.com/kb/en/c-client-library/) for C++.

> Hmm i just read the doumentation and (on first sight at least) it seems like the sql client we use cannot queue multiple queries at the same time withotu waiting for the previous ones to finish. I originally expected that is was possible to implement an (C-) api that can be used like this:

It looks like mariadbpp does essentially that - submitting an async query it returns a `mariadb::handle` (which is a typedef of `mariadb::u64` which is a typedef of `unsigned long long`).  You can then use the handle to check the status of the query and retrieve the resultset if applicable.

@soliton- 

> I assume it'd replace mariadbpp. I don't think it'd make sense to keep both.
> 
> No clue on the status of their boost addition or the likelihood of breaking API changes. I just did a quick search for asio+mysql/mariadb.

Alright, I misunderstood then.  I was able to find some comments on the boost mailing list from [March](https://lists.boost.org/Archives/boost/2020/03/index.php) and [April](https://lists.boost.org/Archives/boost/2020/04/index.php) discussing it, though nothing more recent or definitive.

**Comment by gfgtdf** [comment]
> It looks like mariadbpp does essentially that - submitting an async query it returns a mariadb::handle (which is a typedef of mariadb::u64 which is a typedef of unsigned long long). You can then use the handle to check the status of the query and retrieve the resultset if applicable.

Yes but this page  https://mariadb.com/kb/en/using-the-non-blocking-library/ sees to imply that you have to finish one operation before stating another, which at least partly defeats my suggestion (if i understood correctly, this imples that for example  when the server queries one "game log" then that "game log" has to finish before any other operations (like "check password") can be queued)

**Comment by gfgtdf** [comment]
i _think_ how it is meant to be used is probably for one program to have a "pool" of sql connection objects for one single sql server to exceute multiple operations.

**Comment by Pentarctagon** [comment]
At the moment, my thought was that implementing a connection pool would be overkill for this, but it would be trivial to just have a second connection.  So there'd be one connection for the current queries wesnothd does, and then a second connection that'd handle the async queries.

**Comment by loonycyborg** [comment]
Only reason I made wesnothd single-threaded is to make locking simple. It's still possible to make separate threads to handle db accesses, and they could dispatch their results to main thread. That could work as long as you control which data is shared between threads, e.g. don't touch global data. If mysql/mariadb don't have proper async/nonblocking interfaces already pretty sure it's possible to wrap asio over them anyway, with use of extra threads as above.

**Comment by loonycyborg** [comment]
Also, it's still possible to run asio event loop in multiple threads at the same time but that is really needed only if there is a lot work done in the threads while wesnothd's work is dominated by waiting for connections, so running only one thread saves on properly implementing synchronization or using asio strands. That is what I actually mean when I say that I made wesnothd single-threaded. Adding extra threads not related to asio isn't blocked by current design. Also running multiple event loops is still possible if proper work on synchronizing handlers is done.

**Comment by Pentarctagon** [comment]
Looking into it a bit more, it's not actually viable to have a single connection for the async queries, since even though mariadbpp executes all async queries in the order they were submitted in a single background thread ([[1]](https://github.com/viaduck/mariadbpp/blob/114d7ea8cc871252fd6609fd12522cdcfa632f79/src/concurrency.cpp#L39-L63)), it does not read out any resultsets at that time, which means running two such queries in a row still results in [this error](https://dev.mysql.com/doc/refman/8.0/en/commands-out-of-sync.html).  It also means that the number of connections being used for async queries is irrelevant - they'll all still be executed (asynchronously) one at a time in the order they were submitted.

The simplest solution would be to use [mariadb::concurrency::create_statement](https://github.com/viaduck/mariadbpp/blob/114d7ea8cc871252fd6609fd12522cdcfa632f79/src/concurrency.cpp#L165-L170), since that creates a connection per statement (and thus would never create a situation where multiple queries are trying to use the same connection), though that would of course also have the overhead of creating that connection each time.

---

For anarthal's Boost.Mysql, it does explicitly state that it's the user's responsibility to make sure a connection that's already in use isn't reused for a second query ([[2]](https://anarthal.github.io/boost-mysql/mysql/async.html#mysql.async.sequencing)).

It also has the ability to have callbacks, which would be a bit of a convenience over having a timer and checking each handle like mariadbpp would need, and it says it's fully compatible with Boost.Asio which for the moment I'm assuming means it could be added into the existing setup of wesnothd without too much additional effort.

There would need to be some sort of connection pooling, or a connection per query, same as mariadbpp.

And of course, having actual documentation and examples to refer to is beneficial.

**Comment by Pentarctagon** [comment]
So it looks to me like the best approach would be to use the Boost.Mysql candidate, and that would be done by:
* Submitting async queries with a callback to be executed once the query finishes.
* The callback would be for `boost::asio::post`.
* The function called by `boost::asio::post` would then be responsible for handling the resultset and sending data back to the client.

This would also then require connection pooling functionality, which I think(?) could be fairly simply implemented by claiming(or creating if needed) a connection prior to submitting the async query, and then releasing the connection in the function provided to `boost::asio::post`.

**Comment by gfgtdf** [comment]
> The callback would be for boost::asio::post.

If i understood that Boost.Mysql correctly it does that for you already, meaning you just pas it a callback as usual and it will then be called indirectly vai io_context::run() in the main thread.

**Comment by Pentarctagon** [comment]
It doesn't look like Boost.Mysql is going to be an option, at least for now.  It currently requires Boost 1.72, which isn't available in the Ubuntu or Debian repositories - those only have at most Boost 1.71.  I can go back several commits to where only Boost 1.70 was required, but at that point Boost.Mysql required C++17 (rather than C++11) which also can't be used since the Steam Runtime's gcc only supports up to C++14.

**Comment by Pentarctagon** [comment]
So I think the two remaining options are:
* Provide the async query logic to a packaged_task, provide the packaged_task to boost:asio::post, every few seconds check if any queries have finished, and for any that have send the results back to the client via async_send_doc.  This would be the simpler option, but has the downside that there will always be an addition delay between when the query completes and when its results are actually processed.
* Have the call to async_send_doc be done as part of the packaged_task provided to boost::asio::post.  This would avoid the delay between a query completing and its results being sent back to the client, but would then also need some additional handling to ensure that the async_write call doesn't end up getting made twice simultaneously to the same client.

**Comment by soliton-** [comment]
> ensure that the async_write call doesn't end up getting made twice simultaneously to the same client.

I don't quite understand that part. Is this about clients making another request before they get the reponse of the previous?

**Comment by Pentarctagon** [comment]
The [async_write](https://www.boost.org/doc/libs/1_74_0/doc/html/boost_asio/reference/async_write/overload1.html) documentation says:

> The program must ensure that the stream performs no other write operations (such as async_write, the stream's async_write_some function, or any other composed operations that perform writes) until this operation completes.

So for example, it wouldn't be valid to have the background thread executing the post start sending the query results to the client, and then in the middle of that have the main thread try to send an updated games/users list for the lobby.

Though in looking at it further, another option is to:
* Call `boost::asio::post(<lambda1>)` to execute the query asynchronously.
* Then from within lambda1, call `boost::asio::post(io_service_, <lambda2>)` to send the query result back to the client on the main thread of io_service_.

**Comment by soliton-** [comment]
To be clear the issue there is not concurrency as in multithreading (could be in addition of course) but interleaving data if multiple `async_write()`s are active at the same time. The data of each write is not going to be written at the same time but chunks can be  written in any order. The program logic needs to make sure that this does not happen.

Looking at current wesnothd code I'm not sure that is actually done...

One question is if async_write is even that useful. I would assume in most cases a write will be very quick and just copy the data to some OS buffer before it's sent out at some point. I'm guessing that is also why it's not an issue currently.

I suggest looking into just writing directly.

**Comment by Pentarctagon** [comment]
From the discussion on discord, it sounded like the concern with doing synced writes was if it could end up blocking for long periods of time (ie: if someone has a very slow connection or the connection ends up timing out).  Alternatively, it'd be necessary to make sure everything uses `send_to_player` since that would ensure the writes are queued rather than overlapping, though it looks like `send_to_player` is used pretty widely already.

**Comment by soliton-** [comment]
Yeah, I think `async_write()` is indeed useful and the queuing implemented in `send_to_player()` is simple enough that that can just be used everywhere necessary including the planned query stuff for this feature.

**Comment by Pentarctagon** [comment]
Closing as this was implemented with async query support.
