### ISSUE TITLE
Implement a game history viewer by utilizing queryd

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5052]
Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.6_.2810.2F17.2F2020.29).

**Comment by soliton-** [comment]
How will a separate binary make concurrent, async DB queries easier?

**Comment by Pentarctagon** [comment]
Reassigning the @Vultraz based on discussions on Discord.

**Comment by Pentarctagon** [comment]
Completed with #7416
