### ISSUE TITLE
Add Wose shaman portrait

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5053]
Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.6_.2810.2F17.2F2020.29).

**Comment by Pentarctagon** [comment]
@Lordbob Is this something you were thinking would be ready for 1.16, or should I move this to the 1.17 milestone?

**Comment by cooljeanius** [comment]
He posted a WIP version of a Wose shaman portrait to the forums on June 11th, but said he wasn't satisfied with it: https://forums.wesnoth.org/viewtopic.php?p=665659#p665659 
...so I dunno if you want to just use it anyways, as a placeholder for now, or continue to wait for it to be finished?
