### ISSUE TITLE
Implement an MP reporting dialog

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5056]
This would be a replacement for the `/query report <message>` command that's available now. This could include functionality such as searching for the username(s) to report, searching for a particular game to report (currently running or already ended, if already ended then automatically include a link to the game's replay), and inserting a PM to the MP Moderators group from the reporter (though I'm not sure if this part is actually possible).

Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.7_.2811.2F21.2F2020.29).

**Comment by soliton-** [comment]
Just noting that this does not need to be a replacement. At least I don't see the need to remove `/query report`.
