### ISSUE TITLE
Add missing Monsters & Creatures portraits

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5057]
This would be 5-8 portraits.

Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.7_.2811.2F21.2F2020.29).

**Comment by Pentarctagon** [comment]
Moving to the 1.17 milestone since I assume this won't be completed for 1.16.

**Comment by CelticMinstrel** [comment]
Isn't this completed rather than not planned? I thought doofus-01 added a bunch of monster portraits? Or am I just confused?

**Comment by Pentarctagon** [comment]
The roadmap item doesn't specify, but I assumed that the work doofus-01 did is unrelated to this issue.

**Comment by CelticMinstrel** [comment]
Well, I do know he added a lot of monster portraits, so that's why it seemed like this should be considered completed instead of not planned. The only thing I'm not sure of is whether those monster portraits were added before or after this issue was opened.

**Comment by Pentarctagon** [comment]
It would've been after. I don't think any of the portraits @doofus-01 did were because of this issue.

**Comment by doofus-01** [comment]
They weren't done because of this, but I could say that they were if it means we get bigger bonuses.
