### ISSUE TITLE
Mainline the Visual Map Pack

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5059]
Current feedback from @doofus-01 from Discord:

> Regarding Visual Map Pack (0.2.1a)- The Isar's Cross map is pretty nice, though I do think there should be a chance to revise it a bit before mainlining.  The Aethermaw is cool too, but I think it's better as UMC, at least in its current state.

Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.7_.2811.2F21.2F2020.29).

**Comment by sevu** [comment]
@doofus-01 Can you give more specific feedback about it graphic-wise?
For Isar's, there was also a revision since you looked at it.

Linking to https://r.wesnoth.org/t45058.

**Comment by doofus-01** [comment]
I'll look at the update, but my concern for Isar's was that some of the rock looked very quickly drawn.  Also, if we can get the clouds simple enough, we could have them drift laterally, faking parallax scrolling with terrain animation, without paralyzing lower-power systems.

The other map had standard terrain-to-off-map transitions, didn't look so great in places.  Maybe that's been updated.

**Comment by doofus-01** [comment]
@sevu - Isar's does look better now, I'd have no objections to it being included.  I think there's still some possibility for drifting clouds, but that shouldn't block it.

The other one is unfinished.  This is an example:
![Screenshot_20200912_a](https://user-images.githubusercontent.com/13510196/92994953-d0f10080-f4b3-11ea-9222-c4775446fcae.jpg)

**Comment by inferno8** [comment]
Hello, I am happy to hear that my Isar's map background has been approved. It would be good to have both maps, this one and the classic one, available in 1.16. That way players could be given a choice as I am sure there is a fair number of people who would still prefer the standard look of the original Isar's Cross map.

> if we can get the clouds simple enough, we could have them drift laterally, faking parallax scrolling with terrain animation, without paralyzing lower-power systems.

@doofus-01 It is doable, nevertheless I am afraid that such large moving areas could distract players a lot. AFAIK most (if not all) maps are static in appearance, so introducing parallax scrolling would be "too much" in my opinion. Still it is worth running some experiments in the future, though.

> The other map had standard terrain-to-off-map transitions, didn't look so great in places. Maybe that's been updated.

Speaking of Aethermaw, I have some ideas to fix these issues, but I need more time to improve the map. Until I manage to prepare it before 1.16 is out, I suggest skipping this one entirely for now.

**Comment by sevu** [comment]
> Hello, I am happy to hear that my Isar's map background has been approved. It would be good to have both maps, this one and the classic one, available in 1.16. That way players could be given a choice as I am sure there is a fair number of people who would still prefer the standard look of the original Isar's Cross map.

There's an option in the map preferences to revert to the old style.

> Speaking of Aethermaw, I have some ideas to fix these issues, but I need more time to improve the map. Until I manage to prepare it before 1.16 is out, I suggest skipping this one entirely for now.

Opened PR #5333 for Isar’s. The graphics are the same which @doofus-01 looked at in September.

**Comment by Pentarctagon** [comment]
Should this be closed now that #5333 has been merged, or left open for Aethermaw?

**Comment by doofus-01** [comment]
I would say yes, if we are going to include more maps like Isar's, we need to come up with some sort of method for it.

**Comment by Pentarctagon** [comment]
Closing then.
