### ISSUE TITLE
Add sprites and basic animations for any approved new animals

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5064]
Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.8_.2812.2F19.2F2020.29).

**Comment by Pentarctagon** [comment]
@doofus-01 is this complete?

**Comment by doofus-01** [comment]
Some animations more basic than others, but yes, this is complete.  I'll continue to chip away at animations, I believe that's OK in the beta freeze?

**Comment by Pentarctagon** [comment]
Yep, that's fine.  I'll close this then.
