### ISSUE TITLE
Remove/modify the scenario editor functionality

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5070]
Some discussion is in #4999, [this](https://github.com/wesnoth/wesnoth/pull/4999#issuecomment-662532891) in particular.

Essentially though the point is that while there is some useful functionality in the scenario editor that should be preserved, many of its features range from being intuitive to nearly impossible to actually use without already knowing how to use them, and there's little in the way of instructions for users to find out how.  Therefore it makes sense to trim down the features to things that are actually known to be useful and also not implemented with terrible UI/UX, and then make the way the editor writes out the scenario files be more useful as well.

Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.11_.2803.2F20.2F2021.29).

**Comment by CelticMinstrel** [comment]
I think I said this somewhere else, but… in my opinion, the best thing we could do with the scenario editor is dispense with the two modes system. The editor is _always_ in scenario editor mode, but when you save your map, you can choose to save as either a plain map or a scenario. Of course, if you use features that can't be saved as a plain map, it'll warn if you try to do that.

It could be either an option in the save dialog or just two separate save commands in the menu.

**Comment by gfgtdf** [comment]
> in my opinion, the best thing we could do with the scenario editor is dispense with the two modes system. The editor is always in scenario editor mode, ...

I agree with this plan.

**Comment by stevecotton** [comment]
There are several `todo` comments in the src/editor directory, and I'm looking at adding more in #5260 (a mass conversion of C++ from raw-pointers to std::unique_ptr).

Posting this as reminder to myself both myself and Pentarctagon to check them (and for Pentarctagon to bug me about any he feels I was lazy about).

**Comment by stevecotton** [comment]
Something that still needs to be treated as a "Blocker: New Stable" and handled before the string freeze: the current editor docs have the line "Warning: the Scenario Mode is buggy in 1.14. Improving it is one of the main blockers for the 1.16 release, however in 1.14 its quality is far below that of the game and the terrain mode."

I was expecting that to be handled as part of this issue, but with this issue postponed I'm unsure whether to create a new issue or whether to add comments to #5700.

**Comment by Pentarctagon** [comment]
I'd say to just remove that line then.

**Comment by stevecotton** [comment]
> I'd say to just remove that line then.

That's on my todo list, but I'm hoping to do some more documentation improvements at the same time.
