### ISSUE TITLE
Add Dunefolk portraits

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5073]
Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.14_.2806.2F19.2F2021.29_.28Beta_1.29).

**Comment by Pentarctagon** [comment]
Moving to the 1.17 since I assume this won't be completed in time for 1.16.

**Comment by CelticMinstrel** [comment]
This doesn't seem like the kind of thing that should be closed as "not planned", or even closed at all? It's something we probably intend to do at some point, isn't it?

**Comment by Pentarctagon** [comment]
It was added since it was an item on the 1.15 roadmap - otherwise we don't have issues opened for each thing we'd like a sprite or a portrait for.
