### ISSUE TITLE
UtBS dialogue touchup

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5074]
It's not certain whether this will be able to be finished in time for 1.15/1.16, but this is the issue to keep track of it.

Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.14_.2806.2F19.2F2021.29_.28Beta_1.29).

**Comment by Pentarctagon** [comment]
@nemaara Should I close this or move it to the 1.17 milestone?

**Comment by nemaara** [comment]
I'd say close, supposing I remain SP maintainer I think tackling DM/EI first is more pertinent and I'll try my hand at it before UtBS.

**Comment by Pentarctagon** [comment]
Alright, closing then.
