### ISSUE TITLE
Have the campaigns be more correctly ordered by difficulty

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5075]
This will involve either rebalancing them or simply changing their difficulty ratings, and applies especially to Eastern Invasion (EI).

Taken from the [1.15 Roadmap](https://wiki.wesnoth.org/1.15_Roadmap#1.15.14_.2806.2F19.2F2021.29_.28Beta_1.29).

**Comment by nemaara** [comment]
With the SotA rebalance here (https://github.com/wesnoth/wesnoth/commit/3e59f2ef5b031d49caa9c5982cfe56bf36d5f130), this is done. UtBS might get another patch later, but tentatively it's complete for 1.16 considering the prior balance patch I already did.
