### ISSUE TITLE
campaignd: Require version= increment on uploads

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#5079]
As pointed out in #5038, campaignd currently allows add-ons to be re-uploaded without bumping the version number. However, if the PR is merged this could introduce complications to the whole system.

In general, I feel it's fair to expect content creators to stick to the principle of least surprise and not change add-on contents or metadata without changing the version number as well. Not doing so can result in a number of complications when discussing a version of an add-on, and also bypasses the UI's checks for upgradable add-ons.

**Comment by CelticMinstrel** [comment]
I mostly don't mind the idea, but if I realize 5 seconds after uploading that I missed something, I'd rather not have to increment the version number. How hard would it be to institute a time limit on this requirement?

**Comment by soliton-** [comment]
Rather than a time limit I would suggest a download limit. So you can upload the same version if there are at most the limit number of downloads since the previous upload. The limit should probably be 0.

**Comment by Pentarctagon** [comment]
Is there really a need to add a special case for handling instances like that, rather than just incrementing the version number? IMO it isn't really a problem to do something like:
* Upload version 1.2
* "Oops, found a typo"
* Upload version 1.2.0.1

**Comment by CelticMinstrel** [comment]
> it isn't really a problem to do something like

It's a problem for me.

> Rather than a time limit I would suggest a download limit.

Yeah, that could work too, although it seems less reliable. If someone by pure chance happens to download it the instant you uploaded it, then too bad! I think I prefer the time limit, personally. That said, if the download limit was like, 1 or 2 or something it would probably be okay.

**Comment by shikadiqueen** [comment]
I'm against both, primarily because of the technical complications this would mean for e.g. the WIP diff packs system -- not to mention that `wesnoth_addon_manager` on wesnoth.org (which is the tool that generates the web indices) may run under the download/time limit.

This whole idea of allowing people to pull the rug from under players' feet hasn't ever sit well with me. If I find even the smallest mistake in my add-ons I just bump the version and upload again. `version_info` is flexible enough to allow you to add new version components so that `U.V.W.1 < X.Y.Z` continues to hold true for future uploads.

**Comment by CelticMinstrel** [comment]
If the diff packs system is the PR that brought his issue to me, then I'm pretty sure it already handles the case of uploading the same version number again, so I don't think that's really an argument against it; but `wesnoth_addon_manager` is definitely something that would need to be accounted for in a download limit.

If I found a mistake several days later, I'd probably go ahead and bump the version number, but if I find the mistake right away then I don't want to bother with incrementing the version again.

**Comment by shikadiqueen** [comment]
> If I found a mistake several days later, I'd probably go ahead and bump the version number, but if I find the mistake right away then I don't want to bother with incrementing the version again.

If "right away" is such a meaningless amount of time that the odds of people downloading a bogus version are impossibly low then that says more about your code or release practices than anything else.

**Comment by CelticMinstrel** [comment]
Even with the most "perfect" release practices, anyone can make a mistake.

**Comment by ProditorMagnus** [comment]
There is use case for upload of same version, but I think requiring version change would not be so bad.

However, what would happen if user first removes addon to then be able to upload it again to old version?

**Comment by Pentarctagon** [comment]
It doesn't seem like a good trade-off to increase code complexity in order to avoid having to very occasionally open the _server.pbl and add ".1" to the end of the version string.

**Comment by shikadiqueen** [comment]
> However, what would happen if user first removes addon to then be able to upload it again to old version?

Then the user deserves a slap in the face, which they will get courtesy of themselves if they care about their add-on's statistics on the server.

**Comment by shikadiqueen** [comment]
> Even with the most "perfect" release practices, anyone can make a mistake.

And in the real world that means bumping your version and releasing again instead of making it a nightmare for people who aren't "in" to follow what happened when stuff suddenly breaks.

(Speaking as a victim of this kind of thing myself.)

**Comment by CelticMinstrel** [comment]
Also, the problem of bypassing the UI's checks for upgradable add-ons would be better solved by checking upload date rather than version. I don't think it's a strong argument for requiring version increment.

**Comment by shikadiqueen** [comment]
> Also, the problem of bypassing the UI's checks for upgradable add-ons would be better solved by checking upload date rather than version.

So if for whatever reason the server clock ends up running backwards we break upgrades for all uploads that happen during that timeframe?

Like, I get it, you just want to be able to upload add-ons without raising the version number. But I don't want that.

**Comment by CelticMinstrel** [comment]
…the solution there is to just make sure the server clock never runs backwards. I'm pretty sure there are ways to do that.

**Comment by shikadiqueen** [comment]
But they are not fault-proof.

**Comment by CelticMinstrel** [comment]
Yeah, I don't know that much about them, so I can't say how reliable they are…

**Comment by Pentarctagon** [comment]
Also there's things like daylight savings time adjustments, depending on where things are located.

**Comment by stevecotton** [comment]
> > it isn't really a problem to do something like
> 
> It's a problem for me.

I'm curious - what problems would it cause in your workflow?

My perspective is that I'm wondering what could be done to make the workflows for source-control easier, because I think it would be good for our UMC author's employability to have source-controlled projects in their portfolio.

**Comment by soliton-** [comment]
> I'm against both, primarily because of the technical complications this would mean for e.g. the WIP diff packs system -- not to mention that `wesnoth_addon_manager` on wesnoth.org (which is the tool that generates the web indices) may run under the download/time limit.

What's running on wesnoth.org is already exempt from the download stats.

> This whole idea of allowing people to pull the rug from under players' feet hasn't ever sit well with me. If I find even the smallest mistake in my add-ons I just bump the version and upload again. `version_info` is flexible enough to allow you to add new version components so that `U.V.W.1 < X.Y.Z` continues to hold true for future uploads.

A download limit of 0 would mean there is no surprise for players since no player has the addon version yet. At least not from the addon server. The webinterface would not be included in this check though so that would be an issue.

I don't think it's necessary to allow same version uploads either. It's barely an inconvenience to increase the version number.
