### ISSUE TITLE
Question regarding kilo/kibi prefix from translators' point-of-view

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#5081]
1 kilobyte = 1000 bytes (base 10 convention - humans)
1 kibibyte = 1024 bytes (base 2 convention - binary-based classical computers)

Former is conventionally abbreviated (in English) as kB (or sometimes - admittedly not strictly correctly - KB). Latter is conventionally abbreviated as KiB.

I was a bit confused as a translator as to why, when I saw these entries in the po file, I still saw kibibyte rendered as KiB in Wesnoth itself despite the po file only registering 'K'. Just looking at the translation strings I was at first tempted to change 'K' to 'Ki' by virtue of the description 'prefix_kibi'. It was only after checking the code that I realised that the 'i' is entered separately.

https://github.com/wesnoth/wesnoth/blob/2be22c8030cdc68582c428741cc8484fcda71810/src/serialization/string_utils.cpp#L566-L579

https://github.com/wesnoth/wesnoth/blob/2be22c8030cdc68582c428741cc8484fcda71810/src/serialization/string_utils.cpp#L590-L593

I'm not sure if there's a better translation description for this special case. Kilo does appear to be a special case in that it's the only one out of the commonly-used prefixes (in computing contexts) that is lower-case (k vs M, G, T, P etc). I'm fine if this is closed without further changes, but I just thought I'd put the question out there.

**Comment by AI0867** [comment]
A note for translators could be added. I don't think adding a parallel "prefix_kibi^Ki", "prefix_mebi^Mi", .... series would be a good idea, though it is an option.

I originally implemented this despite being against the very concept of translating SI units, because someone insisted we have translations for them nonetheless.

**Comment by Wedge009** [comment]
Yeah, by very definition SI units are supposed to be international standard, though I'll grant not every language uses Latin alphabet. A note is an option... though I feel it's not worth bother given these prefixes are standardised. Same for adding a dedicated series for binary prefixes.

Oh well, thanks for taking the time to respond. I suppose it's only silly people like me who look into the minute details and get confused as a result. Happy to have this closed if no-one else has any input.

**Comment by stevecotton** [comment]
Maybe add a translator comment to `prefx_kibi^K` noting the existence of `infix_binary^i`?

**Comment by Wedge009** [comment]
Thanks everyone.
