### ISSUE TITLE
Units have no images in scenario editor. 

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5096]
### Game and System Information
-1.15.4
-Steam
-Windows 10

### Describe the bug
Units don't have images in scenario editor. After spawning one and mousing over "list" of units its image appears until next reload of the game. Might be related to the fact that for some reason units from add-ons can still be spawned after removal of said add-ons (units form removed add-ons have no sprites). 

### To Reproduce

1. Enter scenario editor.

### Expected behavior
Units have proper images.

### Screenshots
![Scenario editor has no images](https://user-images.githubusercontent.com/41817546/90981867-a5898e80-e563-11ea-96a7-5f6032ff3812.JPG)

**Comment by Pentarctagon** [comment]
A bisect points to commit 5cecb11652ba08d9eda9a52520d3f90f7a8e1083.

**Comment by Pentarctagon** [comment]
Fixed in 1423dfdba4d5269da062c9a4dc1999f6ea9b4eec:
![units](https://user-images.githubusercontent.com/3030250/91583027-3ff82200-e916-11ea-92a4-1331bb701c21.png)
