### ISSUE TITLE
Lua error in World Conquest, bad argument to 'set_terrain'

### ISSUE THREAD

**Issue by IceTyp** [wesnoth/wesnoth#5098]
### Game and System Information
-1.15.4
-Steam
-Ubuntu 20.04

### Describe the bug
In scenario 4 turn 2 of World Conquest 1p, a Lua error (bad argument to 'set_terrain') occurred. (see screenshot)

### To Reproduce

1. Open the save file.
2. End the turn.

A Lua error will occur at the end of my turn 2.

### Screenshots
![Screenshot from 2020-08-23 19-46-47](https://user-images.githubusercontent.com/70106364/90985069-a88f7980-e579-11ea-9e9c-7ab07e9e45ab.png)

### Savefiles
[WC II 1 Scenario4 - -Auto-Save2.gz](https://github.com/wesnoth/wesnoth/files/5114557/WC.II.1.Scenario4.-.-Auto-Save2.gz)

### Additional context
There are no villages on this map. I am not sure if this is intended. 
I reloaded the whole scenario (to generate another map). This time there where villages. But I got the same Lua error on turn 2.

[WC II 1 Scenario4 - .gz](https://github.com/wesnoth/wesnoth/files/5114587/WC.II.1.Scenario4.-.gz)

**Comment by gfgtdf** [comment]
> A Lua error will occur at the end of my turn 2.



This should be easy to fix.

> There are no villages on this map. I am not sure if this is intended.

No this is really strange 🤔

**Comment by IceTyp** [comment]
Furthermore, the same error happens twice in turn 2 of the last scenario (Final Battle).
It occurs at the beginning of the turn of side 8 and 9. (see replay)

[WC II 1 Final Battle -  replay 20200824-013537.gz](https://github.com/wesnoth/wesnoth/files/5116296/WC.II.1.Final.Battle.-.replay.20200824-013537.gz)

Another Lua error (Repeated [endlevel] execution. ignoring) happens immediately after the last enemy leader is killed (turn 33). (see screenshot and replay)

![image](https://user-images.githubusercontent.com/70106364/91014721-3145fe00-e5ea-11ea-9c17-82908b78644c.png)

**Comment by gfgtdf** [comment]
I'm really interested in the "no villages on the map" problem, do you know how to reproduce it?

**Comment by IceTyp** [comment]
Unfortunately, I have no idea how to reproduce it. I just loaded the whole scenario several times but each time the map had villages. 
I assume there is a problem with the map generator.

**Comment by IceTyp** [comment]
I have loaded Scenario4 again and again. Here are more such maps without villages.

[WC II 1 Scenario4 -  Turn 1 no villages.gz](https://github.com/wesnoth/wesnoth/files/5125436/WC.II.1.Scenario4.-.Turn.1.no.villages.gz)

[WC II 1 Scenario4 -  Turn 1 no villages again.gz](https://github.com/wesnoth/wesnoth/files/5125435/WC.II.1.Scenario4.-.Turn.1.no.villages.again.gz)

The problem seems to depend on the terrain types. All three cases have. (Forests, Mushroom Groves, Caves, Chasm with Lava, ...)

**Comment by IceTyp** [comment]
I have done some research. All three maps have terrain types Ms (Snowy Mountains), Xu (Natural Cave Wall), Ql (Lava Chasm) and others. The only generator that contains the strings "Ms", "Xu" and "Ql" is _industrial.lua_. Hence, I assume that this is the broken generator.

**Comment by gfgtdf** [comment]
reopening for the villages issue

**Comment by gfgtdf** [comment]
I looked into this an i'm quite sure thats is the wild.lua generator. will pusha  fix soon

**Comment by gfgtdf** [comment]
this is fixed now
