### ISSUE TITLE
Flatpak nigthly build doesn't work anymore

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5103]
### Game and System Information
 - What version of the game are you running?

Nigthly build
https://forums.wesnoth.org/viewtopic.php?f=5&t=47872

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Flatpak 

 - What OS are you running?
Fedora

### Describe the bug
Can't install or update, it used to work a week ago

$ flatpak install --from http://files.wesnoth.org/wesnoth-nightly.flatpakref
error: Unable to load summary from remote wesnoth-origin: While fetching http://baldras.wesnoth.org:8080/job/Wesnoth/branch=master,compiler=flatpak-builder,label=Fedora/ws/repo/summary.sig: [7] Couldn't connect to server

### To Reproduce

1. flatpak install --from http://files.wesnoth.org/wesnoth-nightly.flatpakref

**Comment by grz0** [comment]
OK, baldras.wesnoth.org:8080 is reachable again. I'm closing the issue.

**Comment by soliton-** [comment]
> OK, baldras.wesnoth.org:8080 is reachable again. I'm closing the issue.

Thanks to your report! :wink:
