### ISSUE TITLE
World Conquest: treasure unobtainable if bonus point is on the southern boundary

### ISSUE THREAD

**Issue by MarcusAichmayr** [wesnoth/wesnoth#5108]
### Game and System Information
 - 1.15.4
 - Steam
 - Ubuntu 20.04

### Describe the bug
If a bonus point is on the southern boundary of the map and you obtain a treasure there, then the treasure will be unreachable.
This is because the treasure is placed on the area directly south to the bonus point and this area is not reachable by any unit.

### To Reproduce
To reproduce this issue, the generated map must have a bonus point on the southern boundary of the map.
By visiting it, an event will be triggered. If this is a treasure event, then the treasure will be placed on an unreachable area as described above.
Note that randomly another event might be triggered instead. If this is the case, you can reload the corresponding save file to visit the bonus point again.

### Screenshots
![image](https://user-images.githubusercontent.com/70106364/91634168-933da380-e9ee-11ea-9295-c68401bf6879.png)

### Savefiles
The Footpad cannot reach the area of the treasure south of him.
[WC II 1 - Start Turn 2_treasure unobtainable.gz](https://github.com/wesnoth/wesnoth/files/5145051/WC.II.1.-.Start.Turn.2_treasure.unobtainable.gz)

This save file can be used to trigger the event by visiting the bonus point _Tarigolin's Route_. Note that another event might be triggered instead of the treasure event. In this case, you can reload the save file and try again to trigger the treasure event.
[WC II 1 - Start-Auto-Save2.gz](https://github.com/wesnoth/wesnoth/files/5145050/WC.II.1.-.Start-Auto-Save2.gz)

**Comment by gfgtdf** [comment]
Hmm okay then we have two obvious ways to fix it 
1) don't spawn bonus points near the southern border, 
2) find a free location when a bonus point is discovered.

**Comment by IceTyp** [comment]
I am not sure if this is already implemented, but we should also ensure that the location where the treasure is placed is not impassable, unwalkable, or Deep Water or something like that.

**Comment by Wedge009** [comment]
The use of hexes can make checking boundary conditions tricky. I recall a similar issue with villages, #1390.

**Comment by Pentarctagon** [comment]
Was this ever fixed?

**Comment by knyghtmare** [comment]
Still persists for Battle for Wesnoth v1.15.14+dev (8679f0573f8-Modified) x86_64
![image](https://user-images.githubusercontent.com/5283677/123485155-5e5ca600-d62b-11eb-88db-385de002d427.png)

**Comment by CelticMinstrel** [comment]
Does anyone know _where_ the code that controls this is? It should be quite an easy fix once the location is found.

**Comment by Wedge009** [comment]
I don't profess to know anything about the campaign but it looks like this might be related:
https://github.com/wesnoth/wesnoth/blob/31591337076fb45d29569b6c4af3e50577d14f77/data/campaigns/World_Conquest/lua/game_mechanics/bonus.lua#L8-L36

**Comment by CelticMinstrel** [comment]
Hmm… starting from there and investigating further, I think the _best_ fix would be to add `f.border` to the simple filter mechanism, but that's an API change… so we probably need to fix it some other way for 1.16?

---

Just for posterity, here's the chain of links I followed to decide this…
https://github.com/wesnoth/wesnoth/blob/31591337076fb45d29569b6c4af3e50577d14f77/data/campaigns/World_Conquest/lua/map/scenario_utils/bonus_points.lua#L404-L416
Line 413 adds a WML call to wc2_place_bonus, and the function doing that is passed as a callback to `random_placement`. So, I took a look at `random_placement` which is at the top of the file, but it didn't seem relevant, so I went back to this function and realized that `possible_locs` is the key. It's populated from the filter on line 404.
https://github.com/wesnoth/wesnoth/blob/31591337076fb45d29569b6c4af3e50577d14f77/data/campaigns/World_Conquest/lua/map/scenario_utils/bonus_points.lua#L67-L75
That's where the filter is built up. I missed this on the first look but it seems it's already trying to avoid borders… but apparently, that doesn't work? It wouldn't surprise me if `f.x` and `f.y` just don't support location ranges like that…

**Comment by CelticMinstrel** [comment]
Oh! Here's the final low-level implementation of `f.x()`:
https://github.com/wesnoth/wesnoth/blob/31591337076fb45d29569b6c4af3e50577d14f77/src/scripting/lua_terrainfilter.cpp#L335-L352
Is it just me or is it off-by-one? I think it should be using `l.wml_x()` rather than `l.x` on line 349?  If that's the case, presumably `y_filter` has the same problem.
