### ISSUE TITLE
Let Xcode build succeed when using source tarball

### ISSUE THREAD

**Issue by ryandesign** [wesnoth/wesnoth#5117]
### Game and System Information
 - What version of the game are you running? 1.14.13
 - Where did you download it from? built from source by MacPorts
 - If you're using a custom build, what compiler did you use, and what commit did you build at? Apple LLVM version 9.1.0 (clang-902.0.39.2), 1.14.13 tag
 - What OS are you running? macOS 10.13.6

### Describe the desired feature
Hi, I'm the maintainer of [Wesnoth in MacPorts](https://ports.macports.org/port/wesnoth), finally updating our port from 1.12.6 to 1.14.13. I ran into an issue that could possibly be avoided by changing how Wesnoth prepares its source code tarballs, specifically to include the src/revision.h file in the source tarball.

I see that the [official build instructions for macOS](https://github.com/wesnoth/wesnoth/blob/1.14/projectfiles/Xcode/README.md) instruct me to get the source from the git repo. For various reasons we don't want to do that in MacPorts; we want to use the wesnoth-1.14.13.tar.bz2 tarball that you've uploaded to [SourceForge](https://sourceforge.net/projects/wesnoth/files/wesnoth-1.14/wesnoth-1.14.13/). But when I build using that tarball, I get the error:

```
error: No repo or cache detected.
```

This is coming from the [autorevision.sh script ](https://github.com/wesnoth/wesnoth/blob/1.14/utils/autorevision.sh) which the Xcode project is running to generate the file src/revision.h.

Could you include that file in the source tarball in future versions of Wesnoth? Otherwise it is somewhat unclear why you produce source tarballs if they cannot be used to build the software.

I've worked around the issue by generating the file myself in a git clone of the 1.14.13 tag and shipping that file with MacPorts, but I would rather not have to do that every time I update our port.

**Comment by shikadiqueen** [comment]
That error should be harmless and the game should still build correctly, though. The only thing the file presence does (and only if `LOAD_REVISION` is defined) is to provide the game with VCS-specific information about the build. Are you seeing other errors?

**Comment by ryandesign** [comment]
Thanks for the quick reply. It's good to know that revision.h isn't essential. The build fails with:

```
error: No repo or cache detected.

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Update\ Revision.h build/The\ Battle\ for\ Wesnoth.build/Release/The\ Battle\ for\ Wesnoth.build/Script-46B626461D635BC900863502.sh
(1 failure)
```

I assumed the fact that this Update Revision.h step failed, and that that stopped the build, meant that the file that step generated was essential. But if I remove that step from the Xcode project then you're right, it does build, even without revision.h. I hadn't tried that before.

So then I guess what I would want is for a failure of this step not to stop the entire build. Maybe it's as simple as adding `|| true` to the end of the command.

**Comment by ryandesign** [comment]
> Maybe it's as simple as adding `|| true` to the end of the command.

Like this:

```
--- projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj.orig	2020-08-31 22:50:44.000000000 -0500
+++ projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj	2020-08-31 22:51:35.000000000 -0500
@@ -4828,7 +4828,7 @@
 			);
 			runOnlyForDeploymentPostprocessing = 0;
 			shellPath = /bin/sh;
-			shellScript = "cd \"$SOURCE_ROOT/../..\"\n./utils/autorevision.sh -t h > src/revision.h\n";
+			shellScript = "cd \"$SOURCE_ROOT/../..\"\n./utils/autorevision.sh -t h > src/revision.h || true\n";
 		};
 		91C2A6EB1B843AA900346948 /* Copy Translations (if present) */ = {
 			isa = PBXShellScriptBuildPhase;
```

With that change, that step outputs:

```
error: No repo or cache detected.
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
```

And then the build proceeds.

**Comment by Pentarctagon** [comment]
@hrubymar10 Thoughts?

**Comment by hrubymar10** [comment]
@Pentarctagon File `revision.h` is used just for parsing rev number, isn't it?

I'll add check for `.git` folder in root of project. That would be cleaner solution IMHO.

Also @ryandesign next stable release is scheduled to the 9th of September at 00:00 UTC. I believe, that fix will be included here.

**Comment by soliton-** [comment]
autorevision already checks for a git repo and you do need the revision.h file even if it's empty. Just ignoring the exit status of autorevision seems like the best thing to do. You can also redirect stderr if you don't like those messages.

**Comment by hrubymar10** [comment]
@ryandesign 's solution didn't work for me. I believe that this is the best solution (maybe just correct the warning message as I am non-native english speaker:

```bash
cd "$SOURCE_ROOT/../.."

if [ -d ".git" ]; then
  ./utils/autorevision.sh -t h > src/revision.h
else
  echo "warning: Project is not under source control. Skipping revision.h ..."
fi
```

**Comment by soliton-** [comment]
The solution simply adds `|| true` to the command exiting non-zero thus making sure the exit status will be zero. It seems very difficult to imagine how that can not work. How does it nor work?

It still looks to me like you do need revision.h. I can only see LOAD_REVISION being set in the project file and thus src/game_version.cpp includes that file and will not be happy if it's missing.

https://github.com/wesnoth/wesnoth/blob/cd34e2d8aedffc53851d13ec9083681e76ca8429/src/game_version.cpp#L21-L23

Not sure a warning is useful. Who is going to build from a tarball and expect version control info?

As an aside, .git can also be a file (which autorevision handles correctly).

**Comment by hrubymar10** [comment]
@soliton- it generated errors which failed build (Using Xcode 12)
![image](https://user-images.githubusercontent.com/2218817/92090897-4e3fb580-edd0-11ea-810c-48b6e397b201.png)

---

Yes, I need `revision.h`. My bad. I had empty `revision.h` created during my tests, that's why it worked for me.

---

I fixed it by suppressing errors (as you said before).

```bash
cd "${SOURCE_ROOT}/../.."

./utils/autorevision.sh -t h > src/revision.h 2>/dev/null || echo "warning: Project is probably not under source control. Revision number may be incorrect."
```

And the warning message could be helpful. At least for me. Also don't think that this is only warning message during build. In fact wesnoth currently produces 181 warnings...

**Comment by soliton-** [comment]
Ah, so it really did not like receiving stderr output or that the message contained "error" and didn't trust the exit code. Interesting, seems a little overzealous of Xcode. I guess they have their reasons.

Sure a warning is cool if it helps potential confusion. 181 warnings seem like a little much though... :worried:

**Comment by hrubymar10** [comment]
You can see all those warnings for example in currently running Travis CI job [#25269.3](https://travis-ci.com/github/wesnoth/wesnoth/jobs/380653597) in RAW log here: https://api.travis-ci.com/v3/job/380653597/log.txt by searching for `warning:`.

**Comment by Pentarctagon** [comment]
A lot of the warnings for macOS are the same type that got converted to errors for the linux clang jobs when the docker image was upgraded to use Ubuntu 20.04.  So I'd guess we'll start seeing some of the macOS warnings in the linux jobs as well once the upgrade to Ubuntu 22.04 happens.
