### ISSUE TITLE
DiD: OOS errors

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#5119]
codes like https://github.com/wesnoth/wesnoth/blob/166b982250b9e697ad62d908aa4aa135ad510b8d/data/campaigns/Descent_Into_Darkness/scenarios/06_Return_to_Parthyn.cfg#L557 cause OOS errors since malin.experience add 6} changes the gamestate but the event has allow_undo

**Comment by soliton-** [comment]
Does this produce an warning at runtime? I assume the engine does notice the gamestate change issue but assumes the author knows better. Which is fine though I think it should still print a warning.

**Comment by gfgtdf** [comment]
> Does this produce an warning at runtime?

No

> I assume the engine does notice the gamestate change issue

It doesn't

**Comment by soliton-** [comment]
Oh, I see. Would it be difficult to change that?

**Comment by gfgtdf** [comment]
i'm not sure there are a lot of function that might or might not change the gamestate, and keeping track of them just to notice a misuse of [allow_undo] .. probably not worth it, at least for me.

**Comment by soliton-** [comment]
Well, clearly we're already keeping track since we can undo at all and surely we could not warn if there is an [on_undo] involved...

Was just an idea anyway I thought we already do some checks when undoing.

**Comment by gfgtdf** [comment]
> Well, clearly we're already keeping track since we can undo at

Keeping track of what here ?

**Comment by soliton-** [comment]
We're keeping track of actions so they can be undone.

**Comment by gfgtdf** [comment]
> We're keeping track of actions so they can be undone

well yes player actions. (action invoked by players).-

But we don't keep track of things like changing  variables/unit etc which is what this is about.

**Comment by soliton-** [comment]
There is also the replay data which surely must contain everything or replays wouldn't work.

**Comment by gfgtdf** [comment]
> There is also the replay data which surely must contain everything or replays wouldn't work.

It contains the playr actions and everythign else it ten calculated by that, (the game executed events which then sets variables etc.)

**Comment by nemaara** [comment]
I removed them here (https://github.com/wesnoth/wesnoth/commit/0a3c09aa036cbebc45c660d335332014444463f6), if there is more code causing oos issues this can be reopened.
