### ISSUE TITLE
Compilation of mushroom terrain related graphical issues.

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5122]
Issue 1 - For most people new mushroom terrain simply looks worse than the previous one. I strongly encourage to look at them in game on MP maps and in campaigns.
Before:
![Before](https://user-images.githubusercontent.com/41817546/92088416-213dd380-edcd-11ea-8ed8-a8fc1e734d52.JPG)
After:
![After](https://user-images.githubusercontent.com/41817546/92088420-21d66a00-edcd-11ea-8852-a3f48e03321c.JPG)
It also starts to cover swamp terrain and this looks awful (I see potential in this one high grass terrain / ornament could look good):
![This](https://user-images.githubusercontent.com/41817546/92091844-9a3f2a00-edd1-11ea-85a7-efba8d6df49c.JPG)

Issue 2 - New mushroom terrain doesn't cover hill terrain that exists underneath it perfectly.
![Cover](https://user-images.githubusercontent.com/41817546/92089545-978f0580-edce-11ea-91a6-22473df8dde0.JPG) ![MushroomCover](https://user-images.githubusercontent.com/41817546/92088477-387cc100-edcd-11ea-9657-747efaf5bebe.JPG) 

Issue 3 -Transitions work weirdly. They sometimes apply and sometimes they don't.
![Shrooms in watter](https://user-images.githubusercontent.com/41817546/92088616-6235e800-edcd-11ea-8349-cd1df8336ec8.JPG) ![In viodd](https://user-images.githubusercontent.com/41817546/92090528-d3769a80-edcf-11ea-968b-e616a62cd65f.JPG) ![In water 3](https://user-images.githubusercontent.com/41817546/92089689-c7d6a400-edce-11ea-84ff-b1eb4fc3381f.JPG)   
In water but in line:
![In line](https://user-images.githubusercontent.com/41817546/92089007-eb4d1f00-edcd-11ea-8de5-465187c2be8f.JPG)

Issue 4 - This is also a problem in 1.14 but transitions don't work well with few other terrains.
With walls and with keeps (dune keep for reference):
![Keep transitions also 1 14](https://user-images.githubusercontent.com/41817546/92088883-c35dbb80-edcd-11ea-9fba-80210eab21fb.JPG) ![Shrooms and wall](https://user-images.githubusercontent.com/41817546/92088850-b9d45380-edcd-11ea-8ff1-1774c9cf4727.JPG)

**Comment by Pentarctagon** [comment]
The transition problems are definitely bugs.

For the appearance on maps, the reason the appearance changed was so that it would function the same as the previous mushroom terrain in terms of unit defense and movement.

@doofus-01 and @nemaara Any opinions on the Tb^Tf tile appearance on existing maps?

**Comment by doofus-01** [comment]
> @doofus-01 and @nemaara Any opinions on the Tb^Tf tile appearance on existing maps?

My opinion is that this has been brought up before by the same crew, I still don't see the problem, and I'd rather not get involved any further.  If someone has alternative graphics, we can certainly consider them.

The swamp/water thing in image 3 is possibly a filtering issue, if I understand the complaint correctly.

**Comment by Pentarctagon** [comment]
> Clarification - I think that should read:

I *think* my original post was correct - Tb^Tf replaced the old ^Uf terrains in the existing maps since they provide identical defense and movement penalties to units, whereas now ^Tf looks the same as the old ^Uf terrain but provides some different defenses and movement penalties.

> If the question was can we just leave the old terrain code and graphics, I'd think that would be pretty confusing.

I meant more whether Tb^Tf fits in aesthetically with the current maps or not.  A question to @Hejnewar as well would be whether changing Tb^Tf to be only the ^Tf overlay (which would restore the previous appearance) would make the maps unbalanced.

If the issue is that the mushroom base+overlay doesn't visually fit the current maps, and using just the mushroom overlay won't meaningfully affect balance, then IMO the simplest solution would be to change those maps to use the overlay instead of the base+overlay.

**Comment by gfgtdf** [comment]
> and using just the mushroom overlay won't meaningfully affect balance


I think this might actually depend on the concrete base terrain, since the formula is usually, 'best defense, worst movement'. I'm really not an expert at balancing but i'd guess that for flat+Fungus the effect might be rather small since the huge majority of the units has better movement of flat and better defense on Fungus anyways. For other combinations like for example swamp+Fungus that might not be the case since i'd guess that there are quite a few units that have better movement of Fungus than on swamp.

**Comment by ElderoZ** [comment]
Unpopular opinion: Forest properties should be changed, not mushroom properties.

Not that I myself believe this change is necessary or good for the gameplay but I think its an interesting take.

The reasoning is that the only analogue for mushroom terrain is forest, but forest unlike 1.14 mushrooms has composite properties. In the early versions of wesnoth forest did not have composite properties, for example I tested it in 0.8 and there forest/snow did not have composite properties. Drakes had forest defense and forest movement on forest/snow.

**Comment by ElderoZ** [comment]
Unpopular opinion: Forest properties should be changed, not mushroom properties.

Not that I myself believe this change is necessary or good for the gameplay but I think its an interesting take.

The reasoning is that the only analogue for mushroom terrain is forest, but forest unlike 1.14 mushrooms has composite properties. In the early versions of wesnoth forest did not have composite properties, for example I tested it in 0.8 and there forest/snow did not have composite properties. Drakes had forest defense and forest movement on forest/snow.

**Comment by Hejnewar** [comment]
> I meant more whether Tb^Tf fits in aesthetically with the current maps or not. A question to @Hejnewar as well would be whether changing Tb^Tf to be only the ^Tf overlay (which would restore the previous appearance) would make the maps unbalanced.

Yes it would, with my understaing of how this would work with only ^Tf terrains like Ss^Tf would give swimmers / flying units good dodge thus allowing for much easier crossing of natural barriers like the one on 3rd screenshot. This can change a lot depending on situation.

On a side note: Mycelium should not be visible at all on terrains like swamp, it doesn't grow on water itself nor attached to plants. If it exists it usually is attached to the bottom of lake / river and only water tile with transparent water is ford. So in theory ^Uf can look there like it did and still work like it did with ok explanation why.

**Comment by stevecotton** [comment]
> Tb^Tf replaced the old ^Uf terrains in the existing maps

Actually, the multiplayer maps are still using `^Uf`. The graphics have changed, but the files in data/multilplayer/maps haven't (except for ANL and Dark Forecast). Not disputing anything, just adding more clarification.

**Comment by Pentarctagon** [comment]
Huh, alright.  For some reason I was thinking all the uses of the deprecated ^Uf terrain had been removed already.

**Comment by gfgtdf** [comment]
WC2 also still uses it afaik

**Comment by Pentarctagon** [comment]
In any case, as far as the issue goes, given doofus-01 (art lead) doesn't see a problem with the look of the new mushroom terrain, it will remain as-is.

**Comment by doofus-01** [comment]
There are a few things that need cleaning up, like the spillover in the last image, but they can be fixed.

**Comment by CelticMinstrel** [comment]
@Hejnewar
> On a side note: Mycelium should not be visible at all on terrains like swamp, it doesn't grow on water itself nor attached to plants. If it exists it usually is attached to the bottom of lake / river and only water tile with transparent water is ford. So in theory ^Uf can look there like it did and still work like it did with ok explanation why.

To me this explanation is saying that we should use Ss^Tf instead… though I assume that's not your intent.

**Comment by stevecotton** [comment]
> Huh, alright. For some reason I was thinking all the uses of the deprecated ^Uf terrain had been removed already.

For the campaigns that I updated, it acts as a hidden marker of whether the map's balance has been checked.
* still using `^Uf` means the map hasn't been checked
* hex changed to `Tb^Tf` means that hex is either tactically important or I thought `Tb^Tf` looked best for it
* hex changed to `(not Tb)^Tf` means the hex is either just scenery or I checked the balance changes
