### ISSUE TITLE
[modify_unit]x,y=recall problby won't work

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#5133]
[modify_unit]x,y=recall problby won't work

During https://github.com/wesnoth/wesnoth/pull/5131 i noticed that wml does that sometimes.

Edit with explanation, now that another report of this has clarified it for me: trying to move a unit from the map to a side's recall list with `[modify_unit]x,y=recall,recall` or between sides' recall lists with `[modify_unit]side=2` will not work with the fast-path implementation. The old slow-path implementation would store and unstore the unit, using the fast path means we don't get any of the special-case handling that's in the unstore-unit code.

The effect of `[modify_unit]x,y=` to move a unit to an occupied map-hex is also likely to have changed. Tests are needed.

The `[modify_unit]side=` is reported in https://r.wesnoth.org/t54977
A more trivial effect of the fast-path, that the animation code isn't notified about the changes, is logged as #4978.

**Comment by stevecotton** [comment]
I searched but could only find one instance of this. It's a macro that happens at end-of-scenario, but if it doesn't work then the schema should be improved to catch it.

https://github.com/wesnoth/wesnoth/blob/54f86f0c9b1c53cb2d855c47deccd566dfb3f1bd/data/campaigns/Delfadors_Memoirs/utils/sides.cfg#L445-L448

**Comment by gfgtdf** [comment]
> , but if it doesn't work

The problem is that it did probably work in 1.14 but we changtes the [modify_unit] implementation in 1.15

**Comment by CelticMinstrel** [comment]
This sounds like it should be relatively simple to fix if true - just add a special case in `[modify_unit]` if x = "recall".

**Comment by cooljeanius** [comment]
Does this apply only to cases where the recall list is explicitly specified, or also to cases where the recall list just happens to get caught in the filter implicitly?

**Comment by stevecotton** [comment]
Fixed by removing the fast path in #6223.
