### ISSUE TITLE
wc:  deprecated fungus terrain

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#5135]
wc still uses the old fungus terrain

**Comment by Pentarctagon** [comment]
`grep -rl "\^Uf" | wc -l` gives 157 files as still using the old terrain, so it's looks like most of mainline still hasn't been updated to the new terrain, rather than just WC.

**Comment by stevecotton** [comment]
I think this transition is a low priority - even if all of mainline is updated, 1.16 and probably 1.18 have to keep support for `^Uf` for UMC.

**Comment by Pentarctagon** [comment]
I don't think there's really any reason/need to remove support for ^Uf entirely, but if something is deprecated then mainline shouldn't be using it.
