### ISSUE TITLE
Migrate Lua API documentation to the new wiki location

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#5141]
All new Lua API from the API reorganization is currently documented at [LuaAPI](https://wiki.wesnoth.org/LuaAPI) or one of its subpages. However, older API that has not been subjected to the reorganization is still documented on subpages of [LuaWML](https://wiki.wesnoth.org/LuaWML). It's confusing to have two locations for Lua API documentation, so everything from LuaWML should be migrated over to LuaAPI. The LuaWML page can remain as a documentation of the `[lua]` WML tag.

One of the reasons why some of the documentation hasn't been moved is that there were still remaining plans for reorganizing things. The original draft proposal is [here](https://wiki.wesnoth.org/LuaWML/Reorganization), and #4580 is a WIP on the "game" table of the proposal (although it doesn't contain everything from that proposal). Other than that, pretty much anything that doesn't have a new name/location can be moved to LuaAPI.

* [x] [Events and WML Actions](https://wiki.wesnoth.org/LuaWML:Events) - `wesnoth.fire` is deprecated, the helper functions and `wesnoth.tovconfig` are renamed, and `on_event` is experimental (instead of a function I'd like an interface similar to `wesnoth.wml_actions`). Everything else on this page can probably be moved over to LuaAPI.
* [x] [User Interface](https://wiki.wesnoth.org/LuaWML:Display) - I think all of this has been renamed/moved either to the `wesnoth.interface` module or to the `wesnoth.gui` module, other than `wesnoth.show_dialog` and related functions which I believe are deprecated since #5106? There are probably a few here that whose documentation does need to be moved to LuaAPI though.
* [x] [Maps and Terrains](https://wiki.wesnoth.org/LuaWML:Tiles) - Most of this would be moved to the map userdata, I believe, so they should be covered by #4580 and any followups. Since #4580 is not merged, however, their documentation could be moved to LuaAPI as-is for the time being. I think some of these (most notably the items functions) were also moved to `wesnoth.interface`, but I'm not sure...
* [x] [Time of Day Schedule](https://wiki.wesnoth.org/LuaWML:Time) - I didn't have any plans to move these, so their documentation could probably be directly moved to LuaAPI
* [x] [Units](https://wiki.wesnoth.org/LuaWML:Units) - I'm pretty sure all of this was moved to the new `wesnoth.units` module. If there's anything that wasn't, its documentation can be moved to LuaAPI.
* [x] [Sides](https://wiki.wesnoth.org/LuaWML:Sides) - I'm pretty sure all of this was moved to the new `wesnoth.sides` module. If there's anything that wasn't, its documentation can be moved to LuaAPI.
* [x] [Pathfinder](https://wiki.wesnoth.org/LuaWML:Pathfinder) - I don't think any of this was moved/renamed, so its documentation can probably be moved to LuaAPI.
* [x] [Lua Files](https://wiki.wesnoth.org/LuaWML:Files) - All of this was already moved to LuaAPI (although none of them were renamed). Thus it can just be deleted (though it might be good to leave it around until 1.16).
* [x] [Location Sets](https://wiki.wesnoth.org/LuaWML:Location_set) - This documentation was already moved to LuaAPI, so it can just be deleted (though it might be good to leave it around until 1.16).
* [x] [Miscellaneous](https://wiki.wesnoth.org/LuaWML:Misc) - I think most of these haven't been named or removed, so their documentation can probably just be directly moved to LuaAPI.
* [x] [Functions that should not be used](https://wiki.wesnoth.org/LuaWML#Functions_that_should_not_be_used) - This information should be moved to LuaAPI.
* [x] Once all the documentation is copied over, the WIP notice at the top of the LuaAPI pages should be removed, and a similar notice should be added to all the LuaWML pages to indicate that they covers only the 1.14 stable version (which also means any 1.15-specific stuff should be removed from those pages).

Moving the documentation is _not_ a simple copy-paste, unfortunately. The new [style guide](https://wiki.wesnoth.org/LuaAPI#Conventions_used_in_this_manual) will need to be applied to all entries. In some cases this will be easy; in other cases, it might be rather tricky. In addition, any example code will need to be checked to ensure it is not using deprecated, renamed, or moved functions.

While there are still some functions that I feel should be renamed or moved, that's outside the scope of this issue, which is specifically about the current split in documentation.

**Comment by cooljeanius** [comment]
Does this really need the 1.16.0 milestone, or can it be done separately? I thought the wiki could be updated separately from whatever releases get released...

**Comment by CelticMinstrel** [comment]
Actually, this is basically all done. There are about four functions that I still haven't documented, but they're low-priority and I'll make sure to get to them soon.
