### ISSUE TITLE
One missing unit in recruit list makes entire recruit list unavailable

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#5144]
### Game and System Information
 - 7036af787f9e4e871a0e5a1647670fa09535ea47 and later

### Describe the bug
When recruit list contains id which is not known unit, it is not possible to recruit other units either.

### To Reproduce
https://forums.wesnoth.org/viewtopic.php?p=658078#p658078

### Expected behavior
Being able to recruit the units which are known.

**Comment by gfgtdf** [comment]
why is this marked as a 'bug' how much recovery engine does in case a of a error in a umc code looks clearly like an enchantment to me.

**Comment by stevecotton** [comment]
> why is this marked as a 'bug'?

Although the steps to reproduce it mentioned UMC, I think it was reproducible without. It just needed a savegame with a character that could recruit Naga Slashers.
