### ISSUE TITLE
UTBS S02: The ghost-spawning code doesn't know about Ds (Beach Sands) terrain

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5149]
### Game and System Information
AFAICS the bug is also in 1.14.9, the scenario code wasn't updated for the map changes in 
efaff25ccdca3d1391b9859124f047218615645e and 99512957350cc731f1cbe8b50ee3713873ec3e6f.

Tested on:
1.15.4+dev based on 48279849d611d14c366edc03c59f62f6c07219a5
    + PR #5143 [race]help_taxonomy=
    + All elves have race=quenoth (WIP for #4876)
Local build with GCC-10 on Linux

#### Cosmetic bug: dialogue without enemies
At night, ghosts are supposed to spawn. On turn 20 there was dialogue about the ghosts, yet no ghosts had spawned on the map, which is a cosmetic bug. Investigating it led to:

#### Main bug of this issue: ghosts not spawning
The logic for spawning ghosts is broken. It's supposed to do this:
```
# spawn a number of ghosts each turn depending on how "exposed"
# the player units are. Only units in the middle of the desert attract
# ghosts.

# store "exposed" units - those surrounded by a lot of desert
[store_locations]
            variable=ghost_spawn_locs
            [filter]
                side=1
            [/filter]
            terrain=Hd, Dd, Rr
            [filter_adjacent_location]
                count="5,6"
                adjacent="n,ne,se,s,sw,nw"
                terrain=Hd, Dd, Rr
            [/filter_adjacent_location]
        [/store_locations]
```

### Savefiles
[UtBS S02 ghosts did not spawn.gz](https://github.com/wesnoth/wesnoth/files/5213613/UtBS.S02.ghosts.did.not.spawn.gz)

My troops are close to the oasis here, but the same issue would affect all of the `Ds` (Beach Sands) areas in the map.

### Additional info:
@nemaara Does this affect your rebalancing of the campaign?

**Comment by nemaara** [comment]
Yes, but I think it should be fine to make this fix. I'll playtest again after and adjust the difficulty accordingly.
