### ISSUE TITLE
An AI-controlled unit can escape the playable arena on Dark Forecast(Survival) map

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5152]
### Game and System Information
The Battle for Wesnoth version 1.15.4+dev (48279849-Clean)
Running on Linux 5.8.8-200.fc32.x86_64 #1 SMP Wed Sep 9 19:31:09 UTC 2020 x86_64

### Describe the bug
An AI-controlled unit can escape the playable arena on Dark Forecast(Survival) map.
Check the first screenshot, in turn 56 AI moved an Elf Champion on impassable mountains hex.
The unit did not appear again, and I lost a game in turn 59(the second screenshot)

### To Reproduce
Steps to reproduce the behaviour:
1. Play Dark Forecast(Survival), it happens pretty frequently

### Screenshots
![Screenshot_20200916_151916](https://user-images.githubusercontent.com/3605541/93348324-5834d000-f836-11ea-9b91-f45a863c1b40.png)
![Screenshot_20200916_153627](https://user-images.githubusercontent.com/3605541/93348516-96ca8a80-f836-11ea-9ff4-36d69e59d4dd.png)

**Comment by Pentarctagon** [comment]
It sounds like a worse variation of #3891?  I don't think I've ever seen a unit go through the cave walls before though.

**Comment by grz0** [comment]
Yes, this looks like the worst-case scenario of #3891, AI can't be defeated. I took a screenshot at turn 59 with disabled fog 
![Screenshot_20200916_173944](https://user-images.githubusercontent.com/3605541/93360888-7d303f80-f844-11ea-9420-f26c3feaf976.png)

**Comment by Pentarctagon** [comment]
Alright, I'm going to close this as a duplicate then, but I've changed #3891 to be tagged as a bug instead of an enhancement.

**Comment by gfgtdf** [comment]
I also think its strange that thsi scenario has a 'lost on turn over' in the first place, maybe we could remove it?

**Comment by Pentarctagon** [comment]
I'd be fine with that.

**Comment by ProditorMagnus** [comment]
Survival should be win on turn over.
