### ISSUE TITLE
Searching doesn't work correctly with long save file names

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5156]
### Game and System Information
The Battle for Wesnoth version 1.15.4+dev (48279849-Clean)
Running on Linux 5.8.9-200.fc32.x86_64 #1 SMP Mon Sep 14 18:28:45 UTC 2020 x86_64

### Describe the bug
Searching does not take into account whole filename, it uses only truncated string.

### To Reproduce
1. Open the "Load Game" dialog(you need to have a save file with long name)
2. Try to search using part of file name that is truncated
(check screenshots)

### Expected behavior
The whole file name should be used while searching

### Screenshots
I have save file named '2p — Dark Forecast (Survival)-Auto-Save55':
![Screenshot_20200918_113537](https://user-images.githubusercontent.com/3605541/93582674-1a08ef00-f9a3-11ea-9b13-a3cae74c6c79.png)
Let's try search 'Save55', it does not show any results:
![Screenshot_20200918_113621](https://user-images.githubusercontent.com/3605541/93582749-3311a000-f9a3-11ea-8eba-d46ce21e822b.png)

**Comment by Pentarctagon** [comment]
My guess is this is due to the save file name being truncated, which as far as I'm aware, seems to be to work around a UI bug.  So the fix for this would probably be to have the filter check a list of the full filenames rather than the text being displayed on the UI.
