### ISSUE TITLE
Wrong turn tooltip description.

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5168]
### Describe the bug
Description is wrong. Game ends when turn counter exceeds the number indicated by the second number.

### Screenshots
![Ehe](https://user-images.githubusercontent.com/41817546/94305961-62f80f00-ff72-11ea-8476-64f9809f62f7.JPG)
![hmm](https://user-images.githubusercontent.com/41817546/94305972-69868680-ff72-11ea-883e-352dacb5d3af.JPG)

**Comment by Pentarctagon** [comment]
The text is located [here](https://github.com/wesnoth/wesnoth/blob/ef888206dab2018267ef0634d6d9cdcf9a15f53e/src/reports.cpp#L1391).
