### ISSUE TITLE
SotA zombie messages are poorly implemented

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#5170]
The code is splitting a translatable string, which is just asking for problems. On top of that, it's repeating translatable strings that already exist in the game for no real reason. The zombie-utils file needs some major rework.

**Comment by stevecotton** [comment]
The "splitting translatable strings" part has been fixed in #5276 .

There's still some repetition of strings from core, but AFAICS it's now only two strings in the definition of the plague ability.

There's a should-never-be-shown error message which mentions Lua, which might not make sense to the user. However, the only thing that comes to mind for it would be to add a "please report this bug in the forums" to it.

**Comment by celerini** [comment]
The two strings mentioned above - the plague and its description - are untranslatable now.

They should land into wesnoth-units textdomain (as defined on the [first line of zombie-utils](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Secrets_of_the_Ancients/utils/zombie-utils.cfg)), but they don't.

If I manually add the two messages into wesnoth-units/cs.po with their translations, the game shows translated texts for plague in SotA.

The very same texts are in data/scenario-test.cfg (landing in the wesnoth domain) and in data/core/macros/abilities.cfg (landing in the wesnoth-help domain), but their translations are not used by SotA.

**Comment by CelticMinstrel** [comment]
So basically what that means is, the textdomain at the top of the file should be wesnoth-help, not wesnoth-units.

**Comment by Toranks** [comment]
I have seen this issue exploring bugs, and I think it is solved, one of the problems I already reported and it was fixed recently, so there are no more errors related to the translation in SoTA (I already played and reviewed it some weeks ago)

Solved in:
https://github.com/wesnoth/wesnoth/commit/8ce7578adfd4d460cb4c628fe829ded18b19e3ed
https://github.com/wesnoth/wesnoth/issues/7255
https://github.com/wesnoth/wesnoth/pull/5276
