### ISSUE TITLE
Crash when clicking dismiss when recall list is filtered and no units match the filter.

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5171]
The description and a simple test case to reproduce the issue is at https://forums.wesnoth.org/viewtopic.php?f=4&t=53284

The backtrace I got when reproducing the crash is at https://pastebin.com/QcUvRm56

**Comment by gfgtdf** [comment]
hmm ys the dismiss button shoudl be greyed out when there is no unit selected
