### ISSUE TITLE
Descent into Darkness: Malin's variation and advancements are not persisted

### ISSUE THREAD

**Issue by slavrenyuk** [wesnoth/wesnoth#5183]
Wesnoth version 1.15.4, downloaded from sourceforge.net
Windows 10

Savefile: [DiD-A Haunting in Winter.gz](https://github.com/wesnoth/wesnoth/files/5321910/DiD-A.Haunting.in.Winter.gz)

In the updated version of DiD Malin's advancements are based on variations https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Descent_Into_Darkness/units/Malin_Keshar.cfg#L615-L639

It doesn't work when a savefile is loaded (any savefile - start of a scenario, mid of a scenario, replay). 
Opening a savefile in a text editor shows that Malin's unit doesn't have neither variation nor advancements.
As a result, Malin doesn't have any advancements and his XP is shown as `-` instead of `current/maximum` (e.g. `4/80`)

Variations are not persisted for other units too (e.g. swimmer or goblin walking corpse). After a savefile is loaded those units are "reset" to their default variation. Though that is not so critical as for Malin.

**Comment by stevecotton** [comment]
This sounds similar to #5161, however the fix for that was to upgrade to 1.15.5 before the character took their variation.

**Comment by slavrenyuk** [comment]
I am going to check 1.15.5 now.

**Comment by slavrenyuk** [comment]
@stevecotton yes, there is no such problem in 1.15.5. Closing this issue. Thanks for your response! Looking forward to play the updated DiD 😄
