### ISSUE TITLE
Preferences window broken on high resolutions

### ISSUE THREAD

**Issue by imposeren** [wesnoth/wesnoth#5185]
Current master has a little bigger texts and buttons on high resolutions(bigger than 1200x900), so preferences do not fit in the 800x600 window anymore and needs at least 900x650 window.

Maybe insted of `GUI_WINDOW_FIXED_SIZE_CENTERED ` preferences window should use `GUI_WINDOW_PERC_FIXED_SIZE_CENTERED` ? For example:

```diff
#data/gui/window/preferences.cfg
[window]
	id = "preferences_dialog"
	description = "Main game preferences dialog."
	[resolution]
		definition = "default"

-		{GUI_WINDOW_FIXED_SIZE_CENTERED 800 600 }
+		{GUI_WINDOW_PERC_FIXED_SIZE_CENTERED 75 70 800 600 }
# Note: 75% of 1200 is 800. Height percent was chosen by checking  look ща preferences window on resolution of 1280x960
```

Resulting preferences window:
![image](https://user-images.githubusercontent.com/1067274/95008671-7cf5b980-0624-11eb-8b55-a16eb073ef5b.png)

_Originally posted by @vgaming in https://github.com/wesnoth/wesnoth/issues/2219#issuecomment-662097214_
> Today-s `master` branch with 4k  (note the unnecessary scroll bars)
> Could be unrelated from 4k.
> ![2020 07 21_22:14:02](https://user-images.githubusercontent.com/33452702/88105197-d6148c00-cba3-11ea-953e-66b270535454.png)
>

**Comment by imposeren** [comment]
The same issue applies to some other dialogs. For example `game_version.cfg`:

```diff
[window]
	id = "game_version"
	description = "List of paths used by the game to locate resource and configuration files."

	[resolution]
		definition = "default"

		click_dismiss = true
-		maximum_width = 650
-		maximum_height = 600
+		maximum_width = "(floor(max(650, min(screen_width  * 0.55, {GUI_SCALE_RESOLUTION 650 }))))"
+		maximum_height = "(floor(max(600, min(screen_height  * 0.667, {GUI_SCALE_RESOLUTION 600 }))))"
```

**Comment by Pentarctagon** [comment]
This sounds like potentially caused by another change to scale text size based on resolution.  The solution I'd guess would be to just slightly increase the size of the popups so that the scrollbars are avoided.

@Vultraz thoughts?

**Comment by imposeren** [comment]
> caused by another change to scale text size based on resolution

Yes, that's precisely what's happening. I think that button sizes are also scaled based on resolutions, and maybe some other elements too. So now some things do not fit in 800x600 preferences window and into some other windows.

If the scaling is "stepped" (like there are only 2 sizes possible) then simply increasing size will be enough.

If scaling is more dynamic (if there are more than 2 sizes if test/buttons is possible), then simple increase will be not enough

**Comment by stevecotton** [comment]
Rather than having to resize dialogs in a whack-a-mole fashion, I'd like to ask a general question: what do we want to constrain the dialog sizes for? If we want to communicate to the user that this dialog is the child of another dialog, then we possibly only need to ensure that child is thin enough for a wide parent to show beneath it, or short enough for a tall parent to show beneath it.

**Comment by Pentarctagon** [comment]
I'm not sure I understand what the suggestion is.  One problem though actually is that, for example, the preferences dialog dimensions use the entire space available at 800x600.

It'd also be good if @imposeren provided the information listed [here](https://forums.wesnoth.org/viewtopic.php?f=4&t=25660), since I'm not able to reproduce the screenshots he has here - going to the Advanced Preferences doesn't change the dialog's height for me, nor do I have the horizontal and vertical scrollbars on the sides of the dialog window in when General is selected.

**Comment by stevecotton** [comment]
> I'm not able to reproduce the screenshots he has here

These two images are the same instance of Wesnoth, the only difference is that I dragged the window between monitors and opened the preferences (the text size depends on which monitor the window is on at the point that the button is pressed).

HDPI monitor
----

SDL video drivers:       [x11] wayland KMSDRM KMSDRM_LEGACY dummy
Window size:             1973x1211
Screen refresh rate:     60
Screen dots per inch:    281.895966x282.804138
Screen dpi scale factor: 2.936416x2.945876


Normal monitor
----

SDL video drivers:       [x11] wayland KMSDRM KMSDRM_LEGACY dummy
Window size:             1973x1211
Screen refresh rate:     60
Screen dots per inch:    108.917923x108.857140
Screen dpi scale factor: 1.134562x1.133929

![wesnoth_hdpi_monitor](https://user-images.githubusercontent.com/101462/107071681-61bed480-67e5-11eb-8fc8-a5089dff8641.png)



The Battle for Wesnoth version 1.15.9+dev x86_64, commit c42bf114249dcef5241327ca92214cf155ff89e8
Running on Debian GNU/Linux bullseye/sid x86_64
Distribution channel: Default

Game paths
==========

Data dir:        /home/USER/development/wesnoth/quenoth
User config dir: /home/USER/.config/wesnoth1.15/
User data dir:   /home/USER/.local/share/wesnoth/1.15
Saves dir:       /home/USER/.local/share/wesnoth/1.15/saves
Add-ons dir:     /home/USER/.local/share/wesnoth/1.15/data/add-ons
Cache dir:       /home/USER/.cache/wesnoth

Libraries
=========

Boost:             1.74
OpenSSL/libcrypto: 1.1.1i (runtime 1.1.1i)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.46.2 (runtime 1.46.2)
SDL:               2.0.14 (runtime 2.0.14)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.4 (runtime 2.0.4)
SDL_ttf:           2.0.15 (runtime 2.0.15)

Features
========

Lua console completion:         yes
Legacy bidirectional rendering: yes
D-Bus notifications back end:   yes

Current audio settings
======================

SDL audio drivers:  [pulseaudio] alsa sndio dsp disk
Number of channels: 2
Output rate:        44100 Hz
Sample format:      signed 16 bit little-endian
Sample size:        1024 bytes

Installed add-ons
=================

After_the_Storm:           0.10.11
Ageless_Era:               4.27.0
Ageless_Resources:         4.23.0
An_Orcish_Incursion:       1.0.2
AtS_Music:                 0.3.2
Black_Cross_of_Aleron:     2.0.3
Color_Modification:        1.2.1
Era:                       1.0.3
Era_of_Magic_Resources:    1.2.0
Gui_Debug_Tools:           0.9.11
IftU_Music:                0.3.2
Invasion_from_the_Unknown: 2.1.9
Marbuss_Escape:            1.1.1
SXCollection:              0.0.0
Story_of_Wose:             0.9.0
Tactics_Puzzles:           0.3.5a
War_of_Legends:            1.2.5

**Comment by Pentarctagon** [comment]
This most likely would have to do with the font scaling being based on DPI now, so the solution here would be that the font size needs to be recalculated every time the window is dragged to a different monitor.

**Comment by soliton-** [comment]
I think the suggestion is to also scale the dimensions of the dialog not only the font sizes. Would be nice if someone can test the suggestions and commit them. They seem simple enough. Just the magic factors in them are not great or I don't understand how they're calculated.
