### ISSUE TITLE
When you change the language to Chinese, some words will disappear

### ISSUE THREAD

**Issue by lishaoxia1985** [wesnoth/wesnoth#5194]
<img width="1299" alt="YueR" src="https://user-images.githubusercontent.com/49801619/95154281-0d1e3500-07c4-11eb-8139-0349dba08ae4.png">

The bug is this:
 1. Open the app in English
 2. Change the language to Chinese, then some words will disappear
 3. If you reopen the app in Chinese, the game will show normally

I advise that all the language use the font "wqy-microhei", its license is under Apache2 and GPLv3. This is website: 
https://sourceforge.net/projects/wqy/files/wqy-microhei/0.2.0-beta/

**Comment by Pentarctagon** [comment]
A screenshot would be useful, as well as the information listed [here](https://forums.wesnoth.org/viewtopic.php?f=4&t=25660).

Beyond that, if the text displays correctly after restarting, it's unlikely to be an issue with the font itself.

**Comment by stevecotton** [comment]
Reproducible with 1.14.9, 1.14 (built from a recent Git commit) and current master:

The Battle for Wesnoth version 1.15.5+dev (at 87469933bc)
Running on Debian GNU/Linux bullseye/sid
Distribution channel: Default

Game paths
==========

Data dir:        /home/USER/development/other-source/wesnoth/main
User config dir: /home/USER/.config/wesnoth1.15/
User data dir:   /home/USER/.local/share/wesnoth/1.15
Saves dir:       /home/USER/.local/share/wesnoth/1.15/saves
Add-ons dir:     /home/USER/.local/share/wesnoth/1.15/data/add-ons
Cache dir:       /home/USER/.cache/wesnoth

Libraries
=========

Boost:             1.71
OpenSSL/libcrypto: 1.1.1g (runtime 1.1.1g)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.46.2 (runtime 1.46.2)
SDL:               2.0.12 (runtime 2.0.12)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.4 (runtime 2.0.4)
SDL_ttf:           2.0.15 (runtime 2.0.15)

Features
========

JPEG screenshots:               yes
Lua console completion:         yes
Legacy bidirectional rendering: yes
D-Bus notifications back end:   yes

Current video settings
======================

SDL video drivers:       [x11] wayland KMSDRM dummy
Window size:             1024x768
Screen refresh rate:     60
Screen dots per inch:    281.895966x282.804138
Screen dpi scale factor: 2.936416x2.945876

Installed add-ons
=================

After_the_Storm:        0.10.5
Ageless_Era:            4.27.0
Ageless_Resources:      4.23.0
An_Orcish_Incursion:    1.0.0
AtS_Music:              0.3.2
Black_Cross_of_Aleron:  2.0.3
Color_Modification:     1.2.1
Era_of_Magic_Resources: 1.1.1
Gui_Debug_Tools:        0.9.11
SXCollection:           0.0.0
Tactics_Puzzles:        0.3.5a

**Comment by stevecotton** [comment]
During the startup sequence, the fonts are loaded twice:
```
$ wesnoth --language en_US --log-debug font
debug font: Set the font list. The styled font families are:
debug font: [0]:		base:	'Lato-Regular.ttf'	bold:	'Lato-Bold.ttf'	italic:	'Lato-Italic.ttf'
debug font: [1]:		base:	'DejaVuSans.ttf'	bold:	'DejaVuSans-Bold.ttf'	italic:	'DejaVuSans-Oblique.ttf'
debug font: [2]:		base:	'Andagii.ttf'	bold:	''	italic:	''
debug font: [3]:		base:	'DroidSansJapanese.ttf'	bold:	''	italic:	''
debug font: [4]:		base:	'DroidSansFallbackFull.ttf'	bold:	''	italic:	''
...
The same set of fonts are then loaded again in the same order.
```

```
$ wesnoth --language zh_CN --log-debug font
The fonts are first loaded in the same order as en_US.
The fonts are then reloaded:
debug font: Set the font list. The styled font families are:
debug font: [0]:		base:	'Lato-Regular.ttf'	bold:	'Lato-Bold.ttf'	italic:	'Lato-Italic.ttf'
debug font: [1]:		base:	'DejaVuSans.ttf'	bold:	'DejaVuSans-Bold.ttf'	italic:	'DejaVuSans-Oblique.ttf'
debug font: [2]:		base:	'Andagii.ttf'	bold:	''	italic:	''
debug font: [3]:		base:	'DroidSansFallbackFull.ttf'	bold:	''	italic:	''
debug font: [4]:		base:	'DroidSansJapanese.ttf'	bold:	''	italic:	''
```

Changing the language in-game doesn't seem to reload the fonts, and it needs to swap over the order of DroidSansJapanese.ttf and DroidSansFallbackFull.ttf.

**Comment by stevecotton** [comment]
@ivanovic is there a reason why we have both DroidSansJapanese and DroidSansFallbackFull? I don't know if the symbols that are in both are the same in both, but when FallbackFull is loaded first there's only one extra symbol that would be loaded from Japanese. That symbol is U+12316 CUNEIFORM SIGN UD TIMES MI 𒌖.

**Comment by lishaoxia1985** [comment]
@stevecotton @Pentarctagon we can replace all the fonts with the font "wqy-microhei", the font "wqy-microhei" supports all the languages. Its size is also very small.

**Comment by stevecotton** [comment]
In the history there was a switch from wqy-zenhei to DroidSans. I don't know the history and will leave it to the folks involved to assess whether we should switch font again.

The bug seems to be a logic error in sdl_ttf.cpp (which is a Wesnoth file, not a LibSDL one)'s `char_block_map::insert` and `char_block_map::compress` functions. They cope with slightly-overlapping ranges, but they don't cope with one font having a lot of small ranges with gaps between them and the other font having a single range of everything from 20000-40000.

**Comment by ivanovic** [comment]
Honestly, I don't know. I neither speak Chinese nor Japanese and can't judge if the fonts make sense and can be used interchangeably. I gave the link to this thread to the current translation lead to provide some input (in case he is able to do so, since it can get very technical once you are down on font level).

**Comment by CelticMinstrel** [comment]
I know that Japanese and (simplified) Chinese use different simplified characters, but it wouldn't surprise me if a single font can provide both the simplified Chinese version of a character and the simplified Japanese version…

**Comment by oo13** [comment]
"wqy-microhei" is not a Japanese font.
Don't remove DroidSansJapanese and DroidSansFallbackFull, please.

Unicode doesn't support multi-language, intentionally. A plain text encoded Unicode-family cannot contain both Japanese "glyph" and Chinese.

**Comment by lishaoxia1985** [comment]
@oo13  "wqy-microhei" supports all the languages, it also contains a Japanese font.

**Comment by oo13** [comment]
@lishaoxia1985 Do you mean "wqy-microhei" has multiple glyphs in a single code point?
Does Wesnoth support the feature?

**Comment by stevecotton** [comment]
I'm looking at refactoring the code that's causing this bug, so could test other stuff at the same time, but don't know enough about font handling to know what to try.

Wesnoth passes UTF-8 to the FreeType library, so might be able to support whatever that library supports:
* Combining diacritical marks do work (tested with U+6f + U+0308)
* I think the U+FE00 CJK variant selector is getting passed to the library

Wesnoth definitely doesn't have any other support for multiple glyphs sharing a codepoint. It probably does have a bug similar to the one in this issue, if DroidSansJapanese is on the font list before DroidSansFallbackFull and a codepoint that's only in FallbackFull followed immediately by U+FE00 then it might split them and send the U+FE00 alone to be rendered with DroidSansJapanese.

**Comment by oo13** [comment]
U+FE00 is "VARIATION SELECTOR-1" and doesn't change the languages.

I suggest to wait the answer to my question "'wqy-microhei' has multiple glyphs in a single code point?"

**Comment by fujimo-t** [comment]
Different font should be used in each CJK languages.

CJK languages shares codepoints but some codepoints are displayed as different look on different CJK language.
For example:
 * DroidSansFallback (Suitable look for Chinese)
![On DroidSansFallback](https://user-images.githubusercontent.com/10286050/95647783-0d446a80-0b0d-11eb-94f1-24b59382652a.png)
* DroidSansJapanese (Suitable look for Japanese)
![On DroidSansJapanese](https://user-images.githubusercontent.com/10286050/95647817-5f858b80-0b0d-11eb-9f41-03c5ef966185.png)

I have never heard that a font has multiple glyph for a single code point.
At least, [Google Noto](https://www.google.com/get/noto/), which is newer international font set, also separate font file for each CJK language.

**Comment by fujimo-t** [comment]
So change of font file is not solution for this issue.
I think implement font reloading after the language selection is easy way to solve.

**Comment by stevecotton** [comment]
Thanks for the explanation. That means that PR #5200 isn't going to fix this issue, although I'll still merge it as a code improvement.

**Comment by lishaoxia1985** [comment]
@fujimo-t OK, I get your point, I'm sorry. 
You are very serious, If you want to show all the language by one font, 'wqy-microhei' may be a good choice.
Of cource, some Japanese word may show different, although it can be understood rightly.
about"今", you can look this:
![YueR](https://user-images.githubusercontent.com/49801619/95787766-c1601400-0d0c-11eb-9a5e-4dc5c3750367.jpg)
