### ISSUE TITLE
wesnothd: Removing the host of a game that hasn't started yet does not cancel it

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesnoth#5217]
(Wesnoth 1.14.13+dev, live wesnothd on server.wesnoth.org at 1.14.13-58-g40d12e79de3.)

Using mod commands to remove the host of a game that hasn't been started yet does not cancel the game, which results in the game sticking around until it no longer has any players in it. This can result in issues when trying to use `query stopgame` to cancel games with inappropriate titles, for example.

One particular side effect of this as well is that a pending game can end up in an inconsistent state where it's effectively unjoinable:

* Client 1 creates a 1v1 game with observers disabled, with password joins enabled.
* Client 2 joins the game before it starts.
* A moderator uses `query kick` to remove client 1 from the server.
* Client 2 remains in the game lobby, which is now listed as "Full" despite having only one player in it. Joining is impossible without mod access (which only serves to bypass the  no-observers requirement).
* Additionally, if a client with mod access attempts to observe the "Full" game, the game collapses without any error messages and both clients are sent back to the lobby.

**Comment by Pentarctagon** [comment]
I'm not able to reproduce this locally using the steps above on 1.15.15+dev - kicking the host of the not yet started game results in the non-host player being returned to the lobby and the host's game no longer appearing in the list of games.  @irydacea does this still happen for you?

**Comment by Wedge009** [comment]
Would be good to know if this occurs in 1.18, else I think this could be closed.
