### ISSUE TITLE
Unit Statuses not displayed in Wesnoth 1.15.6

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5225]
### Game and System Information
 - What version of the game are you running?
Wesnoth 1.15.6

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
www.wesnoth.org

 - If you're using a custom build, what compiler did you use, and what commit did you build at?
No, just the default installation the website provided me

 - What OS are you running?
Windows 10/Mac OS X, bug is present in both.

### Description of Bug:
Normally, when a unit is poisoned or slowed, a status icon is shown for the unit below the ToD (time of Day) when the mouse cursor is hovered over it. However, in 1.15.6, this seems to be either missing or absent.

### How To Reproduce

1. Launch any campaign, preferably UtBS (since this shows a guaranteed occurrence of the bug).
2. switch to debug mode and spawn 1x Assassin and 1x Elvish Shaman for side 1 and 1x Royal Warrior for side 2/3 (for test target, must belong to the enemy side).
3. Attack the Royal Warrior with the Assassin and Elvish Shaman and inflict the _slowed_ and _poisoned_ statuses.
Note: Royal Warrior was chosen since the unit has a 30% def on flat terrain so I could get the statuses on the unit easily without having to repeat.

### Expected behavior
There should be icons, a snail for slowed status and/or a green skull for poisoned status displayed below the ToD, when the cursor is hovered over the unit, or if the unit is selected.

### Screenshots
![Screenshot 2020-10-23 115049](https://user-images.githubusercontent.com/5283677/96997463-a5057800-1553-11eb-945b-60cfff6137f1.png)
Screenshot#1: First encountered the Bug. Campaign: SotBEE

![Screenshot 2020-10-23 171630](https://user-images.githubusercontent.com/5283677/96997537-c23a4680-1553-11eb-9bdf-a2fe2bfd57c1.png)
Screenshot#2: Reproduced in mainline campaign **Sceptre of Fire**, Wesnoth 1.15.6

<img width="487" alt="Screenshot 2020-10-23 at 17 00 09" src="https://user-images.githubusercontent.com/5283677/96997601-e0a04200-1553-11eb-8aa1-5349e896c3e2.png">
Screenshot#3: Comparison with Wesnoth 1.14.11, showing the existence of the feature. Apologies for the unintentional rotation of the image, but it still exhibits the existence of a bug.

![Screenshot 2020-10-23 174927](https://user-images.githubusercontent.com/5283677/97000186-3545bc00-1558-11eb-87be-7fd479712b2b.png)
Screenshot#4: Bug reproduced again on _Under the Burning Suns_ on Wesnoth 1.15.6.

### Savefiles
Not Required.

### Additional context
I probed further into this and noticed that this bug has a 100% chance to pop-up if the campaign is UtBS as shown in Screenshot#4. I wonder if I have managed to narrow it down.

**Comment by Pentarctagon** [comment]
I can reproduce this on Linux as well; I'll try to bisect this later today.

**Comment by Pentarctagon** [comment]
So it looks like I won't be able to bisect this:
* The bug happens even as early as 1.15.0, but not on 1.14 as far as I can tell.
* I can't build 1.14.5 and earlier due to a compilation error involving boost tribool.

**Comment by doofus-01** [comment]
I think this is same as #4921.  For what it's worth you can see it in the test scenario, and it was the custom "entangled" status that caused it there.
