### ISSUE TITLE
SotA - Zombie recruit dialog duplication

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#5237]
### Game and System Information
Battle for Wesnoth v1.15.6+dev (9e91ddb1fee-Modified)

### Describe the bug
Recruit dialog shows both the "all corpses" option, and the standard walking corpses in the recruit dialog.  It seemed to start in "Carcyn" scenario, but it might be that I used a start-of-scenario save from BfW 1.15.5+dev.  All options seemed to work.  See attached image.

It did make me realize that the zombie recruit dialog is not helpful, just adding the walking corpses to the recruit list would allow faster UI navigation.  It is nice to have a working Lua/GUI2 example though.

### To Reproduce
Use the attached save-file.

### Screenshots
![Screenshot_20201025_](https://user-images.githubusercontent.com/13510196/97133243-85fb1780-1706-11eb-8cc0-d0bab99831c4.jpg)

### Savefiles
[SotA-Carcyn.gz](https://github.com/wesnoth/wesnoth/files/5436744/SotA-Carcyn.gz)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

**Comment by stevecotton** [comment]
As noted in #6128, the bug is on the first scenario that the player controls Ras-Tabahn, who has a separate recruit list to Ardonna.

**Comment by stevecotton** [comment]
It needs testing (which I don't currently have time to do), but the fix is probably to `[disallow_recruit]type=SotA Walking Corpse_Dummy` in S07's event that does `{SAVE_ZOMBIE_LIST ardonna_zombies}`.

**Comment by max-torch** [comment]
> It did make me realize that the zombie recruit dialog is not helpful, just adding the walking corpses to the recruit list would allow faster UI navigation. It is nice to have a working Lua/GUI2 example though.

I would actually argue that the zombie recruit dialog is in fact helpful and makes it organized, especially as the list gets longer and longer. The walking corpse recruit list ends up becoming actually longer than the main recruit list.
See my zombie variants at the last scenario:
![image](https://user-images.githubusercontent.com/41433185/135073497-52858eb3-ec32-49df-9695-3727081e24d9.png)
![image](https://user-images.githubusercontent.com/41433185/135073537-537d334d-dd28-4d91-8518-9e6473f2bcfd.png)

**Comment by Wedge009** [comment]
> It needs testing (which I don't currently have time to do), but the fix is probably to `[disallow_recruit]type=SotA Walking Corpse_Dummy` in S07's event that does `{SAVE_ZOMBIE_LIST ardonna_zombies}`.

I'm probably not 'doing it right', but I changed S7's pre-start event to (addition at the end):
```
        # Prepare to switch leaders.
        {SAVE_ZOMBIE_LIST ardonna_zombies}
        # Clear Ardonna's recruitable zombie list so Ras-Tabahn doesn't start with them.
        [foreach]
            array=zombies
            [do]
                [set_variable]
                    name=this_item.allow_recruit
                    value=no
                [/set_variable]
            [/do]
        [/foreach]
        # Ras-Tabahn does start out with human walking corpses.
        [set_variable]
            name=zombies[3].allow_recruit
            value=yes
        [/set_variable]

        [disallow_recruit]
            type=SotA Walking Corpse_Dummy
        [/disallow_recruit]
```

I ran S7 and then straight into S8 I debug-killed a mage (human type already available) and a horseman (mounted type), with Ras-Tabahn still on the starting keep. Checking the recruit list I still see walking corpse entries for human and mounted units in both the main list and the All Corpses sub-list.

**Comment by CelticMinstrel** [comment]
> It is nice to have a working Lua/GUI2 example though.

I don't think that dialog should be implemented in Lua in the first place. Instead we should expose the actual recruit dialog to Lua as a simple API call, something like `gui.pick_recruit`. Some changes might need to be made to the dialog to support variations, but I doubt it would be that extensive.

That has nothing to do with this issue, though.

**Comment by Wedge009** [comment]
Testing in 1.18.0 release, I activated the human and mounted walking corpses type in S1 and the debug-moved to S8 (Carcyn). The walking corpses now only appear in the All Corpses sub-menu so I think this is resolved. Re-open if I'm mistaken.

**Comment by CelticMinstrel** [comment]
I opened #8829 to cover my earlier comment
