### ISSUE TITLE
SotA - Rastaban zombie recruit list overwrites Ardonna list

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#5256]
### Game and System Information
The Battle for Wesnoth version 1.15.6+dev (9e91ddb1fee-Modified)
### Describe the bug
Zombie recruit list for Ardonna in scenario "Battleground" is the list from Rastaban in previous scenario.  No wolves or rats, but there are swimmers.

### To Reproduce
Just playing through the campaign, I don't think I did anything special.  Start-of-scenario savefile for "Battleground" is attached.

### Expected behavior
Zombie recruit list would be the same as the last Ardonna scenario.

### Savefiles
[SotA-Battleground.gz](https://github.com/wesnoth/wesnoth/files/5472364/SotA-Battleground.gz)

**Comment by stevecotton** [comment]
ooooppss ...

I mentioned this bug in https://github.com/wesnoth/wesnoth/pull/5188#discussion_r503202622 - however, instead of fixing it, I pointed out to @CelticMinstrel that we could use it to simplify the translation of `swimming corpse (" + _ "translate this to an empty string^" + ")"` to `"swimming corpse (Merfolk)"`.

**Comment by CelticMinstrel** [comment]
I'm not sure I get how that comment is related to this bug; it seems to me that this is more likely caused by 24d8a249fa1fa4778c13caba7610f0bdbdfa5006 than f6dc83375c9cfcf2124f48146b926d08b60743bf.

**Comment by stevecotton** [comment]
Once this bug is fixed, then the first time Ardonna kills a **Naga** then she'll be able to recruit swimmers, and the player will see a message that says "You can now recruit **Merfolk** corpses".

**Comment by CelticMinstrel** [comment]
Honestly, I think the _proper_ fix for that is to add a new naga zombie variant.

**Comment by doofus-01** [comment]
I think the _proper_ fix would be to let Ardonna keep the old recruit list, with rats and wolves and bats.

As far as the swimmer corpse for the nagas, the current one is fine.  It's not perfect, but it is close enough.  The sprite isn't perfectly merfolk or naga.  The portrait is more merfolk, but the standard zombie has the same issue - it looks nothing like an orc or mage or etc.

**Comment by stevecotton** [comment]
> I think the *proper* fix would be to let Ardonna keep the old recruit list, with rats and wolves and bats.

We're all agreeing on that.

However, I was under the (incorrect) impression nagas are faster than merfolk on flat, and therefore that a naga zombie would have different movement costs to a merfolk zombie. Now that I see they're the same, adding a naga zombie variant no longer makes sense to me.

**Comment by stevecotton** [comment]
Underlying bug looks like a simple one, although I haven't tested yet. `{SAVE_ZOMBIE_LIST rastabahn_zombies}` ignores the argument and always stores the list to a variable called `ardonna_zombies`:
https://github.com/wesnoth/wesnoth/blob/2a96d87bf8b65564d964284c6a3ac3378975e66e/data/campaigns/Secrets_of_the_Ancients/utils/zombie-utils.cfg#L120-L131
