### ISSUE TITLE
TSG S6a, troll villages don't turn to my side

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5269]
### Game and System Information
 - 1.15.6
 - Steam
 - Windows 10

### Describe the bug
When you talk to the trolls they turn to your side but you don't get the ownership of villages that are occupied by a troll at that time.

### To Reproduce

1. Start the Scenario TSG 6a - Into the Depths/load the provided save.

2. Talk to the trolls.

### Expected behavior
You get the villages the trolls are occupying at that moment.

### Screenshots
![Troll village](https://user-images.githubusercontent.com/39015360/98510667-ca88c600-2263-11eb-9db7-55fc8f953b60.png)

### Savefiles
[TSG-Into the Depths.gz](https://github.com/wesnoth/wesnoth/files/5508658/TSG-Into.the.Depths.gz)
[TSG-Into the Depths Turn 2.gz](https://github.com/wesnoth/wesnoth/files/5508659/TSG-Into.the.Depths.Turn.2.gz)

**Comment by sevu** [comment]
That happens because side 5 has no leader anymore, and so it has no villages, and the code to move villages from side 5 to 1 has nothing to move.
