### ISSUE TITLE
Item placement bug in SoF S4, possibly because of [store_locations]

### ISSUE THREAD

**Issue by IskarJarak** [wesnoth/wesnoth#5278]
### Game and System Information
The bug was reported for Wesnoth 1.15.4 here https://forums.wesnoth.org/viewtopic.php?p=658095#p658095
I have confirmed the behavior on 1.15.6+dev and have confirmed that the behavior does not occur on 1.15.3 (IIRC, it also didn't occur for the version(s) of 1.15.3+dev I was working on at the time).

### Describe the bug
The placement of the coal and gold locations in SoF scenario 4 doesn't work as intended anymore. Coal always gets placed on the keeps of the respective sides leaders that serve as filter anchors, while gold never gets placed at all (presumably because no keep location is matching its distance filter). _This currently makes the scenario uncompleteable_ (without debug).

### To Reproduce
Load the attached save any number of times and remove shroud via debug.

### Expected behavior
Edit: important context: the scenario map is in part generated randomly, which leads to the issue at hand.
Until some point in the 1.15.4 development, the items were still placed correctly at a random location somewhere in the area specified by the respective filters (starting at ~ line 400 of the scenarios code). I have tested that reverting my changes to that filter (commit 7e00c45) does not impact the behavior on 1.15.6+dev.
I assume the bug lies in the behavior of the `[store_locations]` action or something related and not the scenario code.

### Savefiles
[SoF-Gathering Materials.gz](https://github.com/wesnoth/wesnoth/files/5527156/SoF-Gathering.Materials.gz)

### Additional context
I also took a look at the data state in some save files. For the one provided in the forum thread linked above (with the 2 coal deposits already picked up by the player), resource locations are saved as follows. Note the weird values for gold in the first case and the occurrence of Strings in both cases.

```
	[coal_1]
			x=0
			y=0
		[/coal_1]
		[coal_2]
			x=0
			y=0
		[/coal_2]
		[gold_1]
			x="-1].x"
			y="-1].y"
		[/gold_1]
```

In one of the scenario starts I created via the attached file, the locations for turn 1 are given as:

```
		[coal_1]
			x=32
			y=33
		[/coal_1]
		[coal_2]
			x=10
			y=8
		[/coal_2]
		[gold_1]
			x=""
			y=""
		[/gold_1]
```

**Comment by Pentarctagon** [comment]
Does the placement happen at the start of the scenario?

**Comment by IskarJarak** [comment]
As far as I can tell, the map is randomly generated at the start of the scenario, the placement happens as part of the prestart event.

**Comment by Pentarctagon** [comment]
git bisect does point to 7e00c45e665d9572eeaaa025c052594cf9dd05ed as the cause, and I've tested that the issue doesn't happen with the previous commit 7a16f30c6196e76efe104a0f2f422d0c97fe0054

**Comment by IskarJarak** [comment]
Oh, you are right - I think I didn't restart Wesnoth (enough) between tests. I've done additional testing and the bug does indeed come from my commit and I even understand why it happens now...

I'm currently working on a fix to retain the intended behavior of my original commit, and will do a PR with the fix later.
