### ISSUE TITLE
wesnoth package broken in Ubuntu 21.04 (Alpha)

### ISSUE THREAD

**Issue by bittin** [wesnoth/wesnoth#5291]
Hello!

Got this error when installing wesnoth via apt on the Daily Ubuntu Alphas: https://paste.ubuntu.com/p/rR4qm8pVHw/ v1.14.13
Version 1.14.14 from Steam works however 

Maybe someone wants to update the packages in the Ubuntu Repos ?

**Comment by soliton-** [comment]
The Ubuntu package is not maintained by a wesnoth dev. You need to report that to Ubuntu.

**Comment by stevecotton** [comment]
It's reported in the Debian BTS: https://bugs.debian.org/970520

**Comment by soliton-** [comment]
Good. Looks like a fix is incoming.

**Comment by bittin** [comment]
This is now fixed with 1.14.15
