### ISSUE TITLE
DiD S9 - Descent into Darkness, too long exploration

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5294]
### Game and System Information
 - 1.15.6
 - Steam
 - Windows

### Describe the desired feature
In this scenario have to walk all over the map, which is very timeconsuming. My idea would be to
a) let Mal Keshar have 1mp cost for cave during this scenario/until the boss fight
b) let Mal Keshar have unlimited moves as long as he can't see any enemy (with vision being his normal max mp points).
c) something else that makes the map easier to traverse.

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/f0df3378651d6cbcdd41c9ddd8ef3c05a4fd902d
