### ISSUE TITLE
DiD S9 - Descent into Darkness, Mal Keshar starts with too little health (exploration part)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5296]
### Game and System Information
 - 1.15.6
 - Steam
 - Windows 10

### Describe the desired feature
I wish for Mal Keshar to start with a bit more health, maybe 25 instead of 19. With 2 bats rushing at him soo, he can easily die in the first few turns with the player having little influence upon his survival. A few more hitpoints to start with should help with letting him survive. (FTR, I was playing on hard.)

**Comment by Wedge009** [comment]
Campaign balance may be dependent on the author/maintainer, but my recollection is that they're generally balanced for the middle difficulty. I would assume Hard is meant to be, well, hard...

**Comment by AI0867** [comment]
Sure, it's supposed to be hard, but that means hard to do correctly so you have a good chance of survival, not hard to pick the right lottery ticket so you can win.

I don't know what the scenario currently looks like, but if parking yourself on advantageous terrain and/or sniping the bats with your ranged attacks isn't enough to give you a reasonable chance of success, then maybe the scenario should be rebalanced a bit.

**Comment by Konrad22** [comment]
Just to break down the numbers further: Each bat can deal 6-3 damage. You can heal (sometimes less than) 3 hp for every hit you land on a bat. You can get up to 60% defense (mushrooms) if you position yourself well, but the bats have 60% as well.

Without going into detail, with average you will survive if you play well. But if you take two more hits beyond the average (with the average being like 3 hits), you die. If you take one hit, you will need more than average luck to survive the next few turns.

My complaint is basically that even if you play optimally (or what I think is optimal), you can still easily die. Where the goal should be that optimal play means you only die with very bad luck.
