### ISSUE TITLE
DiD S10 - Endless Night, raising nonexistent corpse

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5297]
### Game and System Information
 - 1.15.6
 - Steam
 - Windows

### Describe the bug
If you defeat Inky with a unit that has plague, you 'raise' Inky's corpse, even though Inky supposedly escaped.

### To Reproduce
1. Load the scenario.
2. Kill Inky with a unit that has plague (like Sushi).
3. Observe the raised corpse.

### Expected behavior
No corpse is being raised since Inky escaped instead of having died.

### Savefiles
[DiD-Endless Night replay 20201120-203307.gz](https://github.com/wesnoth/wesnoth/files/5575992/DiD-Endless.Night.replay.20201120-203307.gz)

**Comment by Pentarctagon** [comment]
I'd guess this should either be a `last breath` event or, if that's not early enough, maybe an `attacker hits` event that triggers when Inky's hp goes to 0.

**Comment by sevu** [comment]
Another possibility is to give her an object with the unplaguable status.
