### ISSUE TITLE
a plan to visit enemy hangs the game

### ISSUE THREAD

**Issue by celerini** [wesnoth/wesnoth#5302]
### Game and System Information
 - Battle for Wesnoth v1.15.6
 - Fedora 32 system repository

### Describe the bug
I made a wrong plan which touched enemy unit and caused my unit to finish its move in the next turn. After end of my turn this unit is attacked and after the enemy unit finishes its first strike the game hangs.

The mouse cursor stays as sandglass, I can select next **enemy** unit, menu is accessible, I can quit but not to save the game.

### To Reproduce

1. load SotBE-End_of_Peace-Turn_10.gz
2. activate planning mode
3. plan to move grunt from village to northwest (two hexes, two steps) - see a-plan_started.png
4. finish the plan to allow the particular enemy attack (b-plan_finished.png)
5. deactivate planning mode, execute the plan (c-plan-executed.png)
6. kill the cavalryman by archer (d-cavalryman_killed.png)
7. end turn and let the bowman attack the grunt (e-end_turn.png)

### Expected behavior
AI will finish its attacks.

### Screenshots
a-plan_started.png
![a-plan_started](https://user-images.githubusercontent.com/37598370/99919272-abd30680-2d1c-11eb-8c4f-efdf079a0824.png)
b-plan_finished.png
![b-plan_finished](https://user-images.githubusercontent.com/37598370/99919278-b2fa1480-2d1c-11eb-92b1-36365971eca1.png)
c-plan-executed.png
![c-plan_executed](https://user-images.githubusercontent.com/37598370/99919279-b55c6e80-2d1c-11eb-8b12-a2672c706e58.png)
d-cavalryman_killed.png
![d-cavalryman_killed](https://user-images.githubusercontent.com/37598370/99919284-b7bec880-2d1c-11eb-9e24-c9902e42df13.png)
e-end_turn.png
![e-end_turn](https://user-images.githubusercontent.com/37598370/99919285-ba212280-2d1c-11eb-808e-4d4b6ec3a5d1.png)

### Savefiles
[SotBE-End_of_Peace-Turn_10.gz](https://github.com/wesnoth/wesnoth/files/5580533/SotBE-End_of_Peace-Turn_10.gz)

**Comment by gfgtdf** [comment]
Hmm i just tried again with different settings (skip ai moves/no skip ai moves | executing the whiteboard actions individually or  pressed "execute all planned actions").. in no cae i was able to repdoduce it. I'm pretty sure that the screen looked exactly like your before/after i executed the actions.

Do you have any addons installed that could inerfere , for example addons that modify the ai? It'd be interersting to get a stacktrace of where it hangs exayctly but its hard to get witout building it yourself, maybe you can try to run the game with the --log-debug=ai flag (or enabling in the preferences), and post a logfile.

**Comment by gfgtdf** [comment]
Actually when it really gets stuck  "during" the attacks, there is probably no Ai code involved :/, it'D be really nice to know whether you have any addons installed that could interfere, ai related or not.

**Comment by Toranks** [comment]
Planning mode is not cleared when a unit dies, it seems. But there is no crash.
https://youtu.be/K4LwxTtEyF0

**Comment by gfgtdf** [comment]
This is also what i got:

[Screencast from 23.03.2023 04:02:31.webm](https://user-images.githubusercontent.com/4893136/227090068-0f57bb3e-beae-42af-bf92-b6e62541298d.webm)

**Comment by celerini** [comment]
Thank you for your interest.

I found that the bowman Meolloc freezes after his first shot when I have Preferences -> Display -> Show unit standing animations disabled. He and whole game immediately continues when I enable this option.

I can easily clear dead grunt by pressing y (execute action), so it is only cosmetics error.

I have no add-ons installed.

**Comment by gfgtdf** [comment]
So i used a debugger on this one and it seems like the  whiteboard wants to set the units animation to standing animation in the draw phase during the attack:
```
unit_animation_component::set_standing(unit_animation_component * const this, bool with_bars) 
wb::unghost_owner_unit(unit * unit) 
wb::manager::post_draw(wb::manager * const this) 
game_display::post_draw(game_display * const this)
display::draw(display * const this, bool update, bool force)
events::raise_draw_event() 
controller_base::play_slice(controller_base * const this, bool is_delay_enabled) 
unit_animator::wait_for_end(const unit_animator * const this) 
unit_display::unit_attack( ... ) 
attack::perform_hit( ... ) 
attack::perform( ... ) 
attack_unit( attacker,  defender, int attack_with, int defend_with, bool update_display)
```

**Comment by gfgtdf** [comment]
This will/should be fixed in the  next wesnoth version 1.16.9

**Comment by celerini** [comment]
I just tried it in 1.16.9 and 1.17.15 and the game in both versions no longer hangs with Show unit standing animations disabled.

Thanks a lot.

**Comment by gfgtdf** [comment]
Thx for the feedback, I'm not on my main of right now so i don't have access to discord right now so i forgot the 1.16.9 tag was today.

Let us know when there are still problems with planning mode.
