### ISSUE TITLE
Macro documentation for inline macros causes schema validation failures

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#5304]
The `wmlscope` macro documentation functionality requires documentation comments inside the macro definition. However, for macros intended to be used inline, these comments may not end up being parsed as comments after substitution - for example, if the macro is substituted inside a string, the comment character has no special meaning and the comments themselves will be included as part of the string.

Simply stripping out comments when parsing the macro definition does not appear to be an option, because there is no way for the parser to determine whether a comment is a WML comment (and thus terminated by an end of line) or a WFL comment (and thus terminated by another `#`).

This leaves two options that I can think of, although I'm option to other suggestions:

1. Change `wmlscope` to expect the documentation comments to precede the `#define` instead of following it. The preprocessor then needs no further changes.
2. Change `wmlscope` to require some sort of special syntax to mark the documentation comments. For example, `#doc This is a documentation string`, or even something as simple as `#. This is a documentation string`. The preprocessor could then strip out only those comments with the documentation syntax in them.

**Comment by Elvish-Hunter** [comment]
In ddc51d5 (master) and baa1456 (1.16), I implemented a `# wmlscope: docstring` directive, which allows defining documentation comments outside of macros (useful for inline macros, but it can be used for any macro - I also added a complete documentation inside wmlscope itself).  For this reason, I'm closing this issue.
