### ISSUE TITLE
NR S2, lack of dialogue for out of time defeat

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5314]
### Game and System Information
 - 1.15.7
 - Steam
 - Windows 10

### Describe the desired feature
NR S2 lacks any kind of dialogue to explain why you lose once turns run out. (The obvious choice would be food running out.)
I think it would be nice to add at least some explanation.

**Comment by stevecotton** [comment]
Could also be done with the undead reanimating

**Comment by fraaans** [comment]
i will give this issue a try
