### ISSUE TITLE
Lua Error in AToTB S2

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5316]
### Game and System Information

 - What version of the game are you running?
Wesnoth 1.15.7

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
SourceForge

 - What OS are you running?
Windows 10

### Describe the bug
Lua Error message that pops up when you prevent the Dark Adept from escaping to the sign post by blocking his movement with your units.

### To Reproduce

1. Load the save file of Turn 16. (I am using the experimental PRNG feature and save random seed BTW)
2. Play the turn, ensure you move your units to prevent the Dark Adept from moving.
3. End the Turn.

### Expected behavior
No Lua Error message pop-up

### Screenshots
![Screenshot 2020-11-26 165516](https://user-images.githubusercontent.com/5283677/100343206-46776200-3009-11eb-948c-2babf5cca8e0.png)
SS1: Error Message
![Screenshot 2020-11-26 165925](https://user-images.githubusercontent.com/5283677/100343214-48d9bc00-3009-11eb-9297-3fd479c18247.png)
SS2: What produced it. Prevented the DA from moving to the sign post.

### Savefiles
[AToTB-The Chase Turn 16.gz](https://github.com/wesnoth/wesnoth/files/5602464/AToTB-The.Chase.Turn.16.gz)
[AToTB-The Chase replay 20201126-165750.gz](https://github.com/wesnoth/wesnoth/files/5602478/AToTB-The.Chase.replay.20201126-165750.gz)
[AToTB-The Chase.gz](https://github.com/wesnoth/wesnoth/files/5602483/AToTB-The.Chase.gz)

**Comment by mattsc** [comment]
I've assigned this to myself.  I'm still away due to real-life issues, so if somebody else wants to take care of this, I won't complain.  Otherwise I'll get to it when I'm back.

**Comment by mattsc** [comment]
I had a quick look and the bug is due to a change in the return value of `ai_helper.find_best_move()` when no move is found.  The fix is simple, we need to change l.65 to
```
    if go_to and ((go_to[1] ~= muff_toras.x) or (go_to[2] ~= muff_toras.y)) then
```
I'm not able to do this from where I'm at right now, so if somebody else wants to commit it, please go ahead.  Otherwise I can probably do so in a couple days.
