### ISSUE TITLE
port to libretro?

### ISSUE THREAD

**Issue by DartPower** [wesnoth/wesnoth#5328]
Hi there, i have a idea, you want to port to libretro?
This is will be cool, really :)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by Vultraz** [comment]
What would this get us?

**Comment by sevu** [comment]
Please let us know more.
Wesnoth is a native Linux application ans should just run. It also doesn't care about library versions - if there's a version breaking sth., it will just be fixed. As for the opengl link, opengl is not used by wesnoth.

What is the part where libretro comes into play here?

**Comment by Pentarctagon** [comment]
Closing since this sounds like a lot of work for little benefit.
