### ISSUE TITLE
SotA: Zombie dialog interrupts replays

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5334]
### Game and System Information
 - Reported by @doofus-01 in https://r.wesnoth.org/p660620
 - Reproducible on 1.15.7+dev built from 7c4ce9dd0fb50e8b16876f27538322b242126747

### Describe the bug
When the player recruited a zombie in the replay, the zombie dialog pops up and asks the replay-viewer which zombie to recruit.

### To Reproduce
* Load the savefile attached to @doofus-01 's forum post
* Play the first turn

### Other stuff
As #5237 notes, this dialog isn't necessary for SotA but is a nice example of how to write a Lua/GUI2 dialog - no matter whether we fix it or remove it, we should ensure that there is a fully-working example to point UMC developers at. @Pentarctagon, I think this should be a blocker for a new release.

Time issues: I can't commit more time to Wesnoth this month, and assume neither @beetlenaut nor @gfgtdf can either.

**Comment by Pentarctagon** [comment]
Is this a problem with that particular dialog or with the `show_dialog` function?

**Comment by stevecotton** [comment]
It's a problem with the campaign code, not the core `show_dialog`. Just added the bold bits to show_dialog's docs:

This function should be called in conjunction with `#wesnoth.synchronize_choice`, in order to ensure that only one client displays the dialog and that the other ones recover the same input values from this single client. **Even in single-player campaigns, synchronization is necessary otherwise the replay will be broken.**

**Comment by Pentarctagon** [comment]
Based on https://github.com/wesnoth/wesnoth/blob/7bdd72886ddd27c431d94e342f95834a117513ec/data/campaigns/Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua#L152 this was apparently committed while known to not work, in fact.

From a quick look it doesn't seem as though the fix is especially difficult, at least.

**Comment by Pentarctagon** [comment]
@stevecotton Also the version should be 1.15.7+dev, seeing as 1.15.8 hasn't been release yet :P

**Comment by stevecotton** [comment]
@CelticMinstrel does 726b5458f961f7e2c02de91b66b90dbfed5ddcfd fix this?

I've taken a quick look at the code and think the issue is still open, but haven't spent time testing yet.

**Comment by CelticMinstrel** [comment]
That commit doesn't really change anything; it just moves the WML code out to a WML file for easier editing.

**Comment by stevecotton** [comment]
This one can (and should) still be fixed during the string freeze.

**Comment by stevecotton** [comment]
Fixed in PR #5994 and #5995.
