### ISSUE TITLE
_NOT_REACHED_DESTINATION

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#5345]
That's a typical warning to find in the logs, and some cases expected, like when being ambushed or with enter hex events.

Today I played DiD S1 in 1.14, and checked the log. There are many of these entries.
`Error #2007 (move_result::E_NOT_REACHED_DESTINATION) in full move by side 3 from location 4,17 to location 5,18`

In this case, it doesn't seem to be a false positive.
5,18 is the keep, where Drogan from side 3 is (and never leaves).
4,17 is Dela, who has also the leader status on side 3.

**Comment by mattsc** [comment]
Hmm, yeah, confirmed.  Unsurprisingly, it happens during the `move_leader_to_keep` candidate action:
```
20201207 16:25:52 debug ai/stage/rca: Executing best candidate action: candidate action with name [ai_default_rca::move_leader_to_keep_phase]
20201207 16:25:52 error ai/actions: Error #2007 (move_result::E_NOT_REACHED_DESTINATION) in full move by side 3 from location 4,17 to location 5,18
20201207 16:25:52 debug ai/stage/rca: Disabling candidate action because it failed to change the game state: candidate action with name [ai_default_rca::move_leader_to_keep_phase]
```
Apparently that stage does not check whether there is another leader on the keep.  This seems to be one of those left-over problem from the time when the AI could only handle a single leader per side (although it probably does not make any practical difference).  I'll have a look at sometime after I deal with more urgent AI problems.
