### ISSUE TITLE
Do a pass of macro documentation generate bugs in some macros

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#5346]
### Game and System Information
 - What version of the game are you running?master
 - Where did you download it from? (built from source,)
 - If you're using a custom build, what compiler did you use, and what commit did you build at?(gcc8.1.0 and https://github.com/wesnoth/wesnoth/commit/73b18717d3aa15ac71c5fa3fe302fa7f36c193f8(after https://github.com/wesnoth/wesnoth/commit/059dabcb6a015a13631dae3da6b079b8907ce657 and after fix indentation)
 - What OS are you running? windows 7

### Describe the bug
When I load a scenario in a campaign (Ats) with full_range,fade_range={INFINITY},{INFINITY}
I get this:
"error config: Unexpected characters after variable name (expected, ou =)
in core / macros / scenario-utils.cfg: 12
    included from core / _main.cfg: 18
    included from _main.cfg: 18
    included from ~ add-ons / After_the_Storm / Naia /./ macros / soundfx.cfg: 78
    included from ~ add-ons / After_the_Storm / Naia / loader.cfg: 39
    included from ~ add-ons / After_the_Storm / base-loader.cfg: 7
    included from ~ add-ons / After_the_Storm / _main.cfg: 196
    included from ~ add-ons / After_the_Storm / Naia /./ macros / soundfx.cfg: 84
    included from ~ add-ons / After_the_Storm / Naia / loader.cfg: 39
    included from ~ add-ons / After_the_Storm / base-loader.cfg: 7
    included from ~ add-ons / After_the_Storm / _main.cfg: 196
    included from ~ add-ons / After_the_Storm / episode3 / scenarios / 00_Opening.cfg: 73
    included from ~ add-ons / After_the_Storm / base-loader.cfg: 65
    included from ~ add-ons / After_the_Storm / _main.cfg: 196
    included from ~ add-ons / After_the_Storm / base-loader.cfg: 175
    included from ~ add-ons / After_the_Storm / _main.cfg: 196 "
but the problem disappears when I remove the documentation from the INFINITY macro

### To Reproduce

1. Install Ats in addon
2. Load a beginning scenario in Ats episode 3
3. look loading screen

### Expected behavior
The scenario will be load normally

**Comment by CelticMinstrel** [comment]
I don't know if that commit is on a branch or what, but it should probably be merged.

It would be great to find a more permanent solution to avoid needing to do that, mind you… but until then, things need to work.
