### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#5350]
I guess I'm the only one who gets them … (1.15)
```
In function 'createstrobj',
inlined from 'luaS_createlngstrobj' at src/lua/lstring.cpp:148:29,
inlined from 'luaS_newlstr' at src/lua/lstring.cpp:206:30:
src/lua/lstring.cpp:142:17: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
142 |   getstr(ts)[l] = '\0';  /* ending 0 */
|                 ^
src/lua/lstring.cpp: In function 'luaS_newlstr':
src/lua/lstate.h:213: note: at offset 0 to object 'ts' with size 24 declared here
213 |   struct TString ts;
|
In function 'createstrobj',
inlined from 'luaS_createlngstrobj' at src/lua/lstring.cpp:148:29,
inlined from 'luaS_newlstr' at src/lua/lstring.cpp:206:30,
inlined from 'luaX_newstring' at src/lua/llex.cpp:130:29:
src/lua/lstring.cpp:142:17: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
142 |   getstr(ts)[l] = '\0';  /* ending 0 */
|                 ^
src/lua/llex.cpp: In function 'luaX_newstring':
src/lua/lstate.h:213: note: at offset 0 to object 'ts' with size 24 declared here
213 |   struct TString ts;
|
In function 'createstrobj',
inlined from 'luaS_createlngstrobj' at src/lua/lstring.cpp:148:29,
inlined from 'luaS_newlstr' at src/lua/lstring.cpp:206:30,
inlined from 'pushstr' at src/lua/lobject.cpp:391:3,
inlined from 'luaO_pushvfstring' at src/lua/lobject.cpp:405:12:
src/lua/lstring.cpp:142:17: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
142 |   getstr(ts)[l] = '\0';  /* ending 0 */
|                 ^
src/lua/lobject.cpp: In function 'luaO_pushvfstring':
src/lua/lstate.h:213: note: at offset 0 to object 'ts' with size 24 declared here
213 |   struct TString ts;
|
```

**Comment by Pentarctagon** [comment]
How are you building wesnoth?  A fix for scons at least was added in d643edc9072ba870b0db9ea364c5c3d244915273

**Comment by shikadiqueen** [comment]
It would help a lot to know more about the particular compiler version and platform.

**Comment by sevu** [comment]
I built from a branch without this commit yet. But I tested again with today's master (63b16ad6e19), and it's the same, with the above remaining unchanged.

As compiler I used gcc 10.2.
build system was scons,
build host was Archlinux,
library versions … I think are not relevant, as it's about out packaged Lua and the compiler.

Fun fact: GCC doesn't print `inlined from …` lines when using the German localisation.

**Comment by Pentarctagon** [comment]
I guess this will have to wait until GCC 10 is more widely available.  I can't test this myself yet, and the commit linked above seems to have fixed this for loonycyborg.

**Comment by soliton-** [comment]
Are you saying you get stringop-overflow warnings even though it is turned off?

**Comment by sevu** [comment]
It happens during linking, scons doesn't pass -Wno-stringop-overflow to the linker.

When executing the linking command myself with the option it's turned off.

**Comment by soliton-** [comment]
Can you show the command? Really seems weird that option would do anything when linking.

**Comment by sevu** [comment]
> g++ -o wesnoth -pthread -fstack-protector-strong -fPIE -pie -Wl,-z,relro,-z,now -O3 -march=native -flto=4 -fuse-ld=gold -Wl,-O1,--sort-common,--as-needed -Wl,--whole-archive build/release/libwesnoth-widgets.a -Wl,--no-whole-archive build/release/wesnoth.o build/release/libwesnoth-client.a build/release/liblua.a build/release/libwesnoth-core.a build/release/libwesnoth-game.a build/release/libwesnoth-sdl.a build/release/libwesnoth-client.a -lboost_regex -lboost_filesystem -lboost_locale -lboost_thread -lboost_system -lboost_random -lboost_program_options -lboost_iostreams -lm -lpthread -licudata -licui18n -licuuc -lcrypto -lSDL2 -lSDL2_ttf -lSDL2_mixer -lSDL2_image -lvorbisfile -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0-lharfbuzz -lcairo -lfontconfig -lfreetype -lX11 -ldbus-1 -lfribidi -lhistory

I specified a few custom options:
extra_flags_config = '-pipe -Wno-stringop-overflow'
extra_flags_release = '-fno-plt -Wl,-O1,--sort-common,--as-needed'
enable_lto = True
arch = 'native'

I see in the command the `-Wl,-O1,--sort-common,--as-needed` was taken from extra_flags_release, but `-fno-plt` not, so scons filters them out somewhere.

**Comment by Pentarctagon** [comment]
Does it happen if you build without LTO enabled?

**Comment by sevu** [comment]
No, only with LTO.

**Comment by Pentarctagon** [comment]
I'm not sure if it's something really fixable by us then, since it feels like it would be incorrect to add that warning suppression to the entire linking step when we only want it to apply to particular source files.
