### ISSUE TITLE
WFL: segfault when accessing invalid list indexes

### ISSUE THREAD

**Issue by Elvish-Hunter** [wesnoth/wesnoth#5355]
### Game and System Information
 - What version of the game are you running?
v1.15.7+dev, although I'm fairly sure that this happen even on the latest stable release (1.14.14).
 - Where did you download it from?
Github repository.
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
gcc, with 1ed3edb as last commit.
 - What OS are you running?
Linux Xubuntu 20.04 on amd64, but it should happen on Windows and any other OS as well.

### Describe the bug
The bug was reported here: https://forums.wesnoth.org/viewtopic.php?f=21&t=53707. Although at first it looked like a bug caused by some sort of malformed WML, I was able to pinpoint it to a WFL issue: when splitting a string with `.item` and then trying to access a non-existing index of the resulting list, a segmentation fault is triggered.

### To Reproduce
Put this code in a prestart or start event into the test scenario:

        [set_variable]
            name=unit_to_spawn
            value=$('Elvish Fighter,Dwarvish Fighter,Spearman,Elvish Archer,Dwarvish Thunderer,Bowman'.item[6])
        [/set_variable]
        [message]
            speaker=narrator
            message= _ "Unit to spawn: $unit_to_spawn|."
        [/message]

Then just run `wesnoth --test`. Wesnoth freezes and then there's the segfault. If you replace `6` with `5`, the subsequent `[message]` tag correctly prints "Unit to spawn: Bowman."

### Expected behavior
I'd have expected the WFL command either to silently fail or print an error message.

### Additional context
This is the backtrace generated with `gdb` and a debug build.

[wfl-backtrace.txt](https://github.com/wesnoth/wesnoth/files/5684481/wfl-backtrace.txt)

**Comment by CelticMinstrel** [comment]
`.item` splits the string to a list and `[6]` then accesses an item in the list, so this is likely an issue with lists rather than string splitting.

**Comment by CelticMinstrel** [comment]
Confirmed - the formula `[1,2][2]` is sufficient to see the crash. Maps do not appear to share the problem - `['a' -> 'b']['b]` does not crash and correctly returns null.
