### ISSUE TITLE
Using config instead of simple_wml in wesnothd and campaignd

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5368]
Mostly I'm opening this as a more easily findable way to document what came up in Discord recently, that being, whether it would work and-or make sense for wesnothd and campaignd to drop simple_wml and instead use config like the client does.

Some background can be found [here](https://wiki.wesnoth.org/WesnothdDesign), but the short version is that simple_wml was created long ago as a stripped down, but much faster, way for the servers to process WML.  simple_wml does have its own issues, such as not quite identically parsing data (ie: #4427) as well as being a much more opaque and dangerous to modify implementation of WML parsing.

That said, simple_wml does generally accomplish its goal of being faster than config - simple_wml is reported as being 10x-30x faster than config when it was written, and in the worst case scenario (parsing a newly provided WML text) as of this writing remains ~6x faster than config.  In other situations though, it's not as clear cut.  config has a copy constructor whereas simple_wml does not - it has `clone()`, however this is effectively identical to reparsing the WML text from scratch - and config's copy constructor is only ~1.6x slower than simple_wml.  config also has a move constructor whereas simple_wml again does not, and the move constructor is ~2x **faster** than simple_wml.

---

The main question at this point then is: Is config now fast enough, especially since it has copy and move constructors, that simple_wml isn't needed?  And if not, how much faster would it need to be in order to be a viable replacement, given it's unlikely config can ever reach performance parity with simple_wml?

Additionally, is building wesnothd and campaignd with optimizations enabled an option to eliminate some of the performance difference?  Currently they are built with `-O0`, but doing a release build, which uses `-O3`, nearly eliminates the worst case performance difference (that is to say, simple_wml at `-O0` can parse WML text approximately as quickly as config can at `-O3`), but I'd expect that using `-Og` or `-O1` would be a significant improvement as well.

**Comment by loonycyborg** [comment]
Worst aspect of simple_wml is that it's tricky to use. Need to keep track of who is supposed to manage memory when you pass anything to it. This makes it significantly more error prone than config. Using config instead would increase maintainability and reduce likelihood that any new unsuspecting contributors add new segfault bugs. That said 6x performance gain is still nice so I'm not sure what is better atm.

**Comment by Pentarctagon** [comment]
> That said 6x performance gain is still nice so I'm not sure what is better atm.

Yeah, that's why I mentioned building with optimizations as well.  Using config and building with `-O3` sounds like it could be the best of both - equivalent performance to the current setup while using config instead of simple_wml - but I don't know why they're currently built without optimizations so that might not be an option.

**Comment by loonycyborg** [comment]
Currently built without optimization where?

**Comment by Pentarctagon** [comment]
According to Iris, the current official servers are compiled with `-O0`: https://discord.com/channels/231976805987385345/259976436490829825/730977983522668605 (07/09/2020 for anyone looking through the IRC logs).

**Comment by loonycyborg** [comment]
It was built in debug mode because at some point it had crash bugs after me porting it to asio so I needed to get a complete backtrace to fix them. It shouldn't be needed anymore.

**Comment by Pentarctagon** [comment]
@shikadiqueen or @soliton- is there a need to continue building the servers with `-O0`?

**Comment by soliton-** [comment]
I'm not aware of one.

**Comment by Pentarctagon** [comment]
Would switching from simple_wml to config and changing back to building with `-O3` be acceptable, then?

**Comment by soliton-** [comment]
I don't see the two related.

I would switch to config if we can make sure we get similar performance when comparing release builds.

**Comment by Pentarctagon** [comment]
Both get a similar speedup from a release build.  I doubt config is ever going to become ~6x faster than it currently is though.

**Comment by loonycyborg** [comment]
Official server isn't overloaded for now, but it's good to have potential for growth. It might be a good idea to look into making config parser faster by using boost.spirit, perhaps even matching simple_wml.

**Comment by Pentarctagon** [comment]
Wasn't the main reason for replacing simple_wml with config that config is less dangerous to use?

**Comment by loonycyborg** [comment]
Yes, but redoing that part is potentially disruptive too. At least we already put a lot of effort in maintaining it so we would be still a bit leery to give up the performance benefit it gives, even though it's just 6x now rather than 20x.

**Comment by Pentarctagon** [comment]
Boost Spirit I also somewhat recall as being said to increase compile times by a significant amount, and the current usecase for it (gettext) is also the file that takes the longest to compile out of the entire codebase.  I given how many places use config, that could mean a substantial increase to compile time (which I guess isn't *as* big of an issue given Github Actions has a timeout of 6 hours rather than 50 minutes, but still).

**Comment by shikadiqueen** [comment]
@loonycyborg is talking about the **parser**, not about config.

I'm not sure if the parser was specifically tested here or if it's a relevant bottleneck in practice in the first place*. Furthermore even if the parser will only exist in one translation unit like it does currently, I wouldn't trust template-based frameworks like that to emit code that reasonably fits in any kind of CPU cache at runtime.

* In theory the parser *should* be a hot codepath since incoming WML needs to be parsed... using simple_wml. But I have a feeling in practice most time is spent operating with WML objects rather than tokenizing and parsing the data stream into WML.

**Comment by loonycyborg** [comment]
>Furthermore even if the parser will only exist in one translation unit like it does currently, I wouldn't trust template-based frameworks like that to emit code that reasonably fits in any kind of CPU cache at runtime.

Most of complexity of template stuff is resolved at compile time. So at runtime code would be both small and fast. That's the nature of tradeoff they make. If they failed at this then nobody would use or develop them.

**Comment by loonycyborg** [comment]
Also, yes, I would expect use of boost.spirit for parsing WML to be confined to a single source file while it would expose `config` interface to the rest of wesnoth.

**Comment by Pentarctagon** [comment]
@shikadiqueen the test involved just starting the WML text and then ending with a config.  I'm not sure what the best way to test only the parser would be -  I guess the simplest might be to remove everything related to config and the schema validator, rerun the test, and then compare the difference?

**Comment by Pentarctagon** [comment]
Testing this, the result was that *just* the WML text parsing took 539 ms.  So given the original test gave 1619 ms for how long it took to do the parsing and assign the values to the config object, it means that the text parsing takes ~1/3 of the time and value assignment takes ~2/3 of the time.

**Comment by Pentarctagon** [comment]
As a semi-interesting side note, when running the same tests using a release build with PGO profiling data, config's speed improved by ~10% on the second run and simple_wml's improved by ~14%.

**Comment by Pentarctagon** [comment]
A profile of the config test I ran, using -O0:
![prof](https://user-images.githubusercontent.com/3030250/121466197-a073bf80-c97c-11eb-8d66-f37f00ed9025.gif)

**Comment by Pentarctagon** [comment]
Anyway, closing this as the odds of config being able to match simple_wml in terms of speed are essentially 0.
