### ISSUE TITLE
NR S12, inconsistent teamcolors for Krash and Eryssa

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5375]
### Game and System Information
 - 1.15.7
 - Steam
 - Windows 10

### Describe the bug
Literally the title.

### To Reproduce

1. Obtain Krash and Eryssa.
2. Skip to S12.
3. Observe their colors. (Purple and black.)
4. Skip to S13.
5. Compare the colors. (Orange and teal.)

### Expected behavior
I was expecting for them to have orange and teal in all the scenarios. (Especially Krash since he already had orange in S10 and S11.)

**Comment by Wedge009** [comment]
I'm not sure there's any rule that says team colours have to be consistent across scenarios though it is nice if they are. @sevu seemed to partially resolve this in 4846a08c5f8ef028b0e1e52b0a4baeb30033c1c0 by making Krash's team always be orange. Eryssa, however, remains unspecified, so her team is still black in S12 and teal in S13. There's also a _lot_ of sides in S13, as befits the final scenario of a campaign.

Not sure if sevu is still looking at this - I suppose it's just a matter of adding a consistent `color=` setting to scenarios where Eryssa leads a team... which is only for scenarios 12 and 13 (the final two). And if Eryssa is not alive for the final one, her team could be assigned to Sisal or Ro'Sothian, but then neither of them have any other opportunity to lead a team so them sharing Eryssa's team colour might not be consequential.
