### ISSUE TITLE
UtBS The Morning After says Early Finish Bonus

### ISSUE THREAD

**Issue by dsime42** [wesnoth/wesnoth#5381]
### Game and System Information
Version 1.15.7
Updated to FC32 and it was there
Linux  5.9.14-100.fc32.x86_64 
Fedora FC32 

### To Reproduce
Open UtBS campaign and note that the first scenario says 
Early Finish Bonus
40% carry over

Play the scenario at the end
(YMMV)
Finished 11 turns early
Bonus 0

### Expected behavior
Well,
I suppose it could total up a Bonus gold amount and carry over 40% of the remaining gold. :-)
Or
You could change the objective panel to say "No Early Finish Bonus"

### Screenshots
I can provide screen shots if they are needed but I suspect they are not.

**Comment by stevecotton** [comment]
@nemaara this comes from your ad9567392ffd - the scenario's text needs to be changed to tell the player that they have no income.

**Comment by nemaara** [comment]
https://github.com/wesnoth/wesnoth/commit/497d556d0552aadc2cd10540a6136af7ac97356f
