### ISSUE TITLE
Difficulty level change

### ISSUE THREAD

**Issue by rmj555** [wesnoth/wesnoth#5392]
1.15.8
Window 10

It takes four clicks to change the difficulty level (two clicks if game just turned on).

**Comment by Pentarctagon** [comment]
What is the bug?

**Comment by sevu** [comment]
One needs do choose the difficulty twice.

**Comment by Pentarctagon** [comment]
In what circumstances is it necessary to change the difficulty twice?

**Comment by doofus-01** [comment]
Load a start-of-scenario save and select the change difficulty checkbox.  The dialog for choosing the new difficulty doesn't seem to believe you, you have to go through the choice multiple times before you can get past the dialog.  

I'm not sure what determines the number of times, but it's not always twice.
![Screenshot_20201228](https://user-images.githubusercontent.com/13510196/103253250-379c0c00-4935-11eb-8df4-2feaacc2cc6a.jpg)

**Comment by sevu** [comment]
Can this be backported to stable? IIRC 1.14 is affected too.
