### ISSUE TITLE
SoF S2, inside the cave the day/night ToD is used

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5393]
### Game and System Information
 - 1.15.8
 - Steam
 - Windows 10

### Describe the bug
Literally the title.

### To Reproduce

1. First, start SoF.
2. Then, skip to S2.
3. Lastly, check the ToD inside the cave.

### Expected behavior
ToD 'Underground' instead of day/night circle.

### Savefiles
[SoF-Closing the Gates-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/5748113/SoF-Closing.the.Gates-Auto-Save1.gz)

**Comment by doofus-01** [comment]
All the action takes place near the outside, so it's not that broken-looking.  Should the trolls get a boost?

**Comment by Konrad22** [comment]
For me it's not as much about trolls getting a boost, but that a day/night circle inside a dark cave is a broken thing indeed. :(

**Comment by doofus-01** [comment]
Well, all the action takes place near the outside, so it's not that broken-looking.  Changing TOD is more than cosmetic, I guess it could be part of a scenario revision, but shouldn't be a standalone issue.  I'm inclined to close this.
