### ISSUE TITLE
SoF S1, please mark the Caravans attack as 'defense only'

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5395]
### Game and System Information
 - 1.15.8
 - Steam
 - Windows 10
 
### Describe the desired feature
In SoF S1 you control a couple of Caravans which have a melee attack. Which is why I was quite surprised to see the message 'no attack avaible' when I was trying to attack an enemy unit with a Caravan. I guess that the attack is defense only and ask for this to be made clear.

### Screenshots
![grafik](https://user-images.githubusercontent.com/39015360/103231760-ee4dbb80-4938-11eb-9050-20d543a6c114.png)
![grafik](https://user-images.githubusercontent.com/39015360/103231800-002f5e80-4939-11eb-962f-ee8cf89ff523.png)

**Comment by doofus-01** [comment]
I believe this is fixed now.
