### ISSUE TITLE
Add-on downloads not adding up

### ISSUE THREAD

**Issue by Helmet-BfW** [wesnoth/wesnoth#5411]
### Game and System Information
 - What version of the game are you running? **1.15.8**
 - Where did you download it from? **website**
 - Custom build? **no**
 - What OS are you running? Mac OS **10.12.6**

### Describe the bug
I recently uploaded my completed campaign "The Pool of Ek" to the add-on server. Although multiple people downloaded the add-on, the server reported only 1 download. It presently reports 2 downloads, still fewer than the actual number. I've received 4 communications from forum members who downloaded "The Pool of Ek." I'm wondering, How many people downloaded it but did not message me or make a post on the related thread?

It would be great if the problem was not only fixed, but my download counter was increased to display the correct figure. Thanks.

### To Reproduce

1. First..write a campaign
2. Then...upload the campaign to the add-on server
3. Lastly...look at the download number to see if it correlates with reality

### Expected behavior
When a download occurs, the download counter should add 1 to the prior number, increasing the total.

**Comment by shikadiqueen** [comment]
Thanks for the report. The fix is on the live server now.

> It would be great if the problem was not only fixed, but my download counter was increased to display the correct figure. Thanks.

Unfortunately this is harder than it sounds and also affects more than one single add-on over a pretty long period of time (nearly 2 months).
