### ISSUE TITLE
Dune Raider sprite facing the wrong direction after being attacked

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5412]
### Game and System Information
 - 1.15.8
 - Steam
 - Windows 10

### Describe the bug
When the Dune Raider faces SW when being attacked from S, the sprite faces to SE during the attack, but turns back to SW after the attack is over.

### To Reproduce

1. Create a Dune Raider and make it face SW.
2. Change the Dune Raiders side to an enemy side and create any unit.
3. Attack the Dune Raider with that unit from S.

You can also load the provided save file and end the players turn. The described bug happens during blacks turn.

### Expected behavior
The Dune Raider keeps facing SE after the attack is over.

### Savefiles
[RftA-Inglorious Campaign Turn 4.gz](https://github.com/wesnoth/wesnoth/files/5787794/RftA-Inglorious.Campaign.Turn.4.gz)

### Additional context
If you are testing on 1.15.8, you will likely see that the Dune Raider loses TC when moving or melee attacking. This has already been fixed by @Vultraz on master.

**Comment by doofus-01** [comment]
This has something to do with IPFs, or at least ~BLIT().  The south-facing sprite is usually SE default, but if the sprite has ~BLIT() in the standing animation, it is SW.  Just having a standing animation doesn't cause it.

It doesn't require any attack to test, just create a unit and move it south, see which way it ends up facing.
