### ISSUE TITLE
Terrain graphics background layer

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#5416]
Using images on the off-map regions, like the new Isar's-Cross-in-the-sky, is nice, but could be better if we could use a solid JPEG background.  The problem is, base terrains are drawn on the absolute lowest layer, so you can't put anything under them.  There are two ways to get around this (without changing anything in the engine):
1.  carefully replace the "*" in the [terrain-graphics] map with "." wherever a desired base terrain graphic should be.
2. move the base terrain layer up one, to -999, and reserve layer=-1000 for backgrounds.

I think option 2 is the better one, but I'll need some time to make sure it doesn't cause some issue somewhere.  There may also be some other problem I'm not thinking of.

I'll try to get this in to 1.15 some time, starting with Isar's Cross.

**Comment by soliton-** [comment]
Option 2 sounds better to me too.

**Comment by doofus-01** [comment]
Maybe with #6254, this is worth looking at again.  (Flagging this for my future self.)

**Comment by CelticMinstrel** [comment]
Why is -1000 the lowest layer exactly…?

**Comment by doofus-01** [comment]
It's not, I mixed something up.  There was some other issue, but I don't remember.  It'll come back when/if I or anyone else works on this.

**Comment by doofus-01** [comment]
The webp conversion makes whatever was valid here, if anything, very low priority.  If there is still anything to do around this, a fresh start wouldn't hurt.
