### ISSUE TITLE
Bugs when zooming in

### ISSUE THREAD

**Issue by renom** [wesnoth/wesnoth#5420]
Bugs when zooming in:
1. Lit cave becomes cyan
2. Some tiles have thin border around
<img src="https://user-images.githubusercontent.com/4979122/104452927-b8edd280-55b4-11eb-93d0-531a42c40bed.png" width="50%" height="50%" />
<img src="https://user-images.githubusercontent.com/4979122/104452938-be4b1d00-55b4-11eb-9f18-49938ce2e97d.png" width="50%" height="50%" />

**Comment by renom** [comment]
3. Team color circles are rendered with noise
<img src="https://user-images.githubusercontent.com/4979122/106353750-e305fb00-62fd-11eb-925d-d6bb64176192.png" width="50%" height="50%" />

**Comment by cooljeanius** [comment]
> Bugs when zooming in:
> 
>     1. Lit cave becomes cyan
> 
>     2. Some tiles have thin border around

Oh yeah I've noticed the second one, too; it was a precursor to the graphical artifacts that led to one of the crashes in #6030 for a bit...

**Comment by Wedge009** [comment]
> Team color circles are rendered with noise

I remember seeing that before but I think it only happens on certain types of interpolation methods and I believe choice of method is removed with 1.15.x so isn't really an issue any more - the default interpolation method doesn't exhibit this noise.

Regarding the other two cases - is there a specific scenario we can go to to check those cases?

**Comment by mesilliac** [comment]
This should be fixed by recent rendering engine changes, if it wasn't already fixed before that. Interpolation is now always done in hardware. If the seam artifacts show up again, it's a fresh bug.

I did try to reproduce all three issues earlier and verified no visible problem.
