### ISSUE TITLE
DiD S09 uses [modify_unit] to set vision without an [effect], and moves without max_moves

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5440]
### Game and System Information
Reviewing the WML in current master, f29ff0518034284610e057009aa380e6b6fe0da6

### Describe the bug
For #3356 I'm reviewing all the campaign WML that uses [effect]apply_to=vision. DiD S09 has a line that sets vision directly, although vision is one of the stats that may be overwritten whenever the unit is rebuilt.

Given that it's at the same time as a change to moves (not max_moves) and a lift_fog, I'm assuming that it's a leftover line from an older method of reducing his vision during the ritual. However, maybe the change to moves was intended to also be a change to max_moves?
https://github.com/wesnoth/wesnoth/blob/f29ff0518034284610e057009aa380e6b6fe0da6/data/campaigns/Descent_Into_Darkness/scenarios/09_Descent_into_Darkness.cfg#L3340-L3344

@nemaara, ping.

**Comment by nemaara** [comment]
I think what I was trying to do with that block was reset Mal Keshar's moves/attacks when you trigger the boss battle. Looking at it again, that vision line probably doesn't do anything, I probably want a [redraw] instead. Does that sound right?

**Comment by nemaara** [comment]
See here https://github.com/wesnoth/wesnoth/commit/8eb0bc3151325f6fd2a07c6172b18d9c3b4e4a4c, I think this behaves as I'd like using the right code now.
