### ISSUE TITLE
Dune Cataphract sprite being 'chonky' on the right

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5445]
### Game and System Information
 - 1.15.8
 - Steam
 - Windows 10
 
### Describe the bug
The Dune Cataphract is 'chonky' on the ride side of the screen. (Sorry, I have no idea what that thing is named. Feel free to rename the issue.)

### To Reproduce

1. First, create a Dune Cataphract.
2. Then, look at the unit.

### Expected behavior
The sprite not being chonky like that.

### Screenshots
![grafik](https://user-images.githubusercontent.com/39015360/104817735-4afb1280-5823-11eb-8cb9-c001666ebc1f.png)

### Savefiles
[Cataphract bug.gz](https://github.com/wesnoth/wesnoth/files/5824771/Cataphract.bug.gz)

**Comment by doofus-01** [comment]
It just needs an image_icon, like the loyalists knights.  The default scaling is weird.
(Chonky?)

**Comment by Konrad22** [comment]
(That's @Vultraz choice of words. And I really drew blank on how to describe it.)
