### ISSUE TITLE
Diversion tooltip useless (Dunefolk Sky Hunter/Falconer)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#5454]
### Game and System Information
 - 1.15.9
 - Steam
 - Windows 10

### Describe the bug
The tooltip for diversion will always say that the ability is inactive right now, so the tooltip is useless.

### To Reproduce

1. First, create a Sky Hunter/Falconer, and two more units.
2. Then, make it so that one of the random units is on an enemy side.
3. Lastly, place the units so that diversion is active and try to check the tooltip.

### Expected behavior
Sadly the expected behavior is the observed behavior, because by moving the mouse to the tooltip, the game is checking if the ability would be active if the unit was standing where the mouse is, which is never the case.

### Screenshots
![grafik](https://user-images.githubusercontent.com/39015360/104837209-4f6f0c00-58b3-11eb-80b8-443c2b0afa34.png)

### Additional context
I don't think that this is a bug (everything is behaving as expected and intented), but it is undesirable behavior in this case.

**Comment by doofus-01** [comment]
fixed in #5495
