### ISSUE TITLE
[CI] "boost_unit_test" received signal SIGSEGV 

### ISSUE THREAD

**Issue by hexagonrecursion** [wesnoth/wesnoth#5463]
### Game and System Information
 - What version of the game are you running?  master
 - Where did you download it from? git
 - If you're using a custom build, what compiler did you use, and what commit did you build at? clang 42d9047
 - What OS are you running? Ubuntu

### Describe the bug
I noticed that CI builds are failing https://github.com/wesnoth/wesnoth/pull/5462/checks?check_run_id=1720246030. I get "Error: Process completed with exit code 1".

### Expected behavior
All tests pass.

### Additional context
The logs are noisy with a bunch of warnings and errors that, apparently, do not cause a build failure (they probably should), but based on comparing [this](https://github.com/wesnoth/wesnoth/pull/5462/checks?check_run_id=1720246030) to [this](https://github.com/wesnoth/wesnoth/runs/1719715857) I think the error that causes the test failure is

https://github.com/wesnoth/wesnoth/pull/5462/checks?check_run_id=1720246030#step:3:1750
```
unknown location(0): fatal error: in "Test setup": CVideo::error: Video initialization failed

Thread 1 "boost_unit_test" received signal SIGSEGV, Segmentation fault.
```

**Comment by Pentarctagon** [comment]
This is a known quirk of the CI environment where rarely and at random SDL fails to initialize.  Unless it's something that happens on repeated CI runs, it's fine to ignore it.
