### ISSUE TITLE
Small textbug in the german version from "The South Guard"

### ISSUE THREAD

**Issue by Sonoar** [wesnoth/wesnoth#5464]
I found a small textbug in the german version from "The South Guard" in the first scenario.
I'm running BfW on Windows 10 over Steam, version 1.14.15

The bug occurs when you walk into the castle and is located in the dialogue between Gerrick and Deoran in Deorans 2nd part. It shows: "Der Text enhält ungültiges Pango Markup: <l> [monologue from Deoran] </l> [monologue from Deoran] [End]"

![wesnoth](https://user-images.githubusercontent.com/77623359/104921060-1f9a3400-5999-11eb-81d5-545b9633cd06.png)

**Comment by soliton-** [comment]
Thanks for the report! Fixed in 24d3872
