### ISSUE TITLE
Delf's Memoirs Sc.19-20

### ISSUE THREAD

**Issue by rmj555** [wesnoth/wesnoth#5472]
1.15.8 on Windows10
After victory in sc. 19 there was a lua error. 
Sc. 20 begins with abourt 27 elves in the forest; there are none for recall.

#

**Comment by Pentarctagon** [comment]
Can you provide a save file of just prior to the error as well as the text of the error itself?

**Comment by rmj555** [comment]
Sorry, but that autosave file is gone, and I can't figure out how to take a  screen shot.

**Comment by stevecotton** [comment]
While the Lua error must be a bug, the empty recall list isn't - the end of S19 is meant to put every elf except Kalenz into `delfador_elvish_veterans`, and they're meant to turn up again near the end of S20.

**Comment by rmj555** [comment]
Version 1.15.10

[DM-Prince of Wesnoth-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/6137025/DM-Prince.of.Wesnoth-Auto-Save1.gz)
[DM-Showdown in the Northern Swamp-Auto-Save20.gz](https://github.com/wesnoth/wesnoth/files/6137026/DM-Showdown.in.the.Northern.Swamp-Auto-Save20.gz)

**Comment by Wedge009** [comment]
I also checked instances of `[set_specials]` and didn't see anything in relation to `mode=`. Please re-open if you happen to find this is still a problem.
