### ISSUE TITLE
Links in mp games no longer work.

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5485]
### Game and System Information
 - 1,15,9
 - Steam
 - Windows 10

### Describe the bug
Links in mp games no longer work.

### To Reproduce

1. Send link in mp game's chat. 

### Expected behavior
Link should be highlited and work. 

### Screenshots
![bug](https://user-images.githubusercontent.com/41817546/105214925-ea384680-5b50-11eb-9eb3-91e3beb7f45c.JPG)

**Comment by Pentarctagon** [comment]
@Vultraz I'd guess that this is caused by 7188781f914f2d2dbcd3c269a03ca5337c19714a?
