### ISSUE TITLE
[random_placement] WFL num_items is broken

### ISSUE THREAD

**Issue by virtualghetto** [wesnoth/wesnoth#5489]
### Game and System Information
 - What version of the game are you running?
 - wesnoth 1.15.9
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - tag 1.15.9
 - What OS are you running?
 - linux

### Describe the bug
`[random_placement]` deprecated calculating `num_items` via lua in favor of wfl.
The number assigned to num_items using wfl does not match the number returned by lua.
wfl's wesnoth.eval_formula() seems to be returning 0 when the `size` variable is used.

**Comment by CelticMinstrel** [comment]
Hmm… the code for handling WFL looks correct to me (though I just noticed the code for percentages is broken). What WML are you using that doesn't work?

**Comment by virtualghetto** [comment]
For the WFL method, I used:
`num_items="(size * ({N} / 100))"`
{N} is an integer like 5 or 8.
I placed `std_print` after `wesnoth.eval_formula()` to see the value of `result` and I got 0 everytime.

The following using the Lua method didn't cause any issues.
`num_items="size * ({N} / 100)"`

I'm not sure where it's going wrong exactly either, sorry.

**Comment by virtualghetto** [comment]
I'm attaching a demo for testing,
Comment/Uncomment lines 90 and 93 to switch between wfl and lua.
[_main.cfg.txt](https://github.com/wesnoth/wesnoth/files/5861686/_main.cfg.txt)

**Comment by CelticMinstrel** [comment]
Just a thought, but what if you print out `num_items` rather than `result`? That can at least rule out a bad value for `{N}`.

**Comment by virtualghetto** [comment]
Forget I even mentioned {N}

The attached demo generates an empty map with Gg and 2 castles.
It then changes half of the grass into lava in prestart.

The WFL will change none.
The Lua will change half.

Please download it and test it. Let us know if the WFL on your end is changing half of the map into lava. I'd appreciated it if someone else tried it too to confirm.

```
    [event]
        name=prestart

        [random_placement]
            # WFL method
            num_items="(size * (50 / 100))"

            # Lua method
            #num_items="size * (50 / 100)"

            variable=random_placement_location
            allow_less=yes
            min_distance=0
            [filter_location]
                include_borders=no
                terrain=Gg
            [/filter_location]
            [command]
                [terrain]
                    x,y=$random_placement_location.x,$random_placement_location.y
                    terrain=Ql
                [/terrain]
            [/command]
        [/random_placement]
        {CLEAR_VARIABLE random_placement_location}
    [/event]
```

**Comment by CelticMinstrel** [comment]
Oh! What if you divide by 100.0 instead of 100?

**Comment by virtualghetto** [comment]
> Oh! What if you divide by 100.0 instead of 100?

Wow, excellent catch! Yes that fixes it.
The question now is, should there be a type cast somewhere?

Don't forget about ./Heir_To_The_Throne/scenarios/12_Northern_Winter.cfg:                num_items="(size / ($turn_limit - $turn_number))"
Thanks.

I'll leave this issue for you to close.

**Comment by CelticMinstrel** [comment]
Well, assuming we're sticking to integer division being truncated, the generic way to handle this would be to type-cast using the `as_decimal` function.

**Comment by virtualghetto** [comment]
data/core/macros/terrain-utils.cfg {SCATTER_EMBELLISHMENTS} is currently not functioning because of this.
num_items="(size * ({PERCENTAGE} / 100))"

**Comment by CelticMinstrel** [comment]
While changing those two known mainline cases is one option, I think it might be nicer to change WFL division to be be non-truncating. I'm a little worried that this might break some existing cases though, and @Pentarctagon also seems to be against it… does anyone else have thoughts on the matter?

**Comment by Pentarctagon** [comment]
Out of curiosity, what was the reason for deprecating the use of lua in favor of WFL?

Also, would the solution here simply be to add a note about this change in division to the deprecation message?

**Comment by virtualghetto** [comment]
Truncating the division is not intuitive. It wouldn't have taken us this long to identify the root cause of the issue if it was.

I lean towards making WFL division non-truncating to match Lua's division.
You could then enclose the formula with a `ceil()` or `floor()`, or use `[set_variable]`'s `ipart` or `round` when an integer is expected.

I see the cases that might break as the ones with the bug, not vice-versa.

**Comment by CelticMinstrel** [comment]
> what was the reason for deprecating the use of lua in favor of WFL?

I don't remember my exact reasoning from the time, but possibly something to do with how WFL can guarantee no side-effects (other than random generator state) while Lua cannot.

> Also, would the solution here simply be to add a note about this change in division to the deprecation message?

That would only help for people who were using Lua before and haven't updated it yet.

> You could then enclose the formula with a `ceil()` or `floor()`

Technically the correct answer would be `trunc()` (and add it if it doesn't exist) but yeah.

**Comment by Pentarctagon** [comment]
@virtualghetto It's very much a language-specific decision - some (like C++, Java, and apparently WFL) truncate integer division, whereas others (such as lua) don't truncate it.

Were WFL something new, then I'd say that WFL should definitely work the same way as lua and WML.  But given it's something that's been around a while and is pretty widely used, I think that changing how a basic math operation works for all UMC authors needs a better justification than to support the new way to calculate a single attribute of a single tag.

**Comment by CelticMinstrel** [comment]
I wouldn't say that my justification for the change is specifically this attribute of this tag… that's just the thing that brought it to my attention.

**Comment by Pentarctagon** [comment]
Regardless, the options available are:
* Fix this issue by making WFL division work the same way as lua division, which would also potentially cause issues anywhere else WFL division is used currently.
* Un-deprecate the lua version of the attribute.
* Leave the implementation as-is, instead adding the `num_items` compatibility change to the list of other changes that've happened between 1.14 and the eventual 1.16.

Ideally there'd be a way to do a grep to search for which add-ons use WFL for division, and if it's small then there wouldn't be much of a reason *not* to do the first option.  Would doing a grep for lines that contain an opening parenthesis, a slash, and then a closing parenthesis give too many false positives?

**Comment by Pentarctagon** [comment]
Even from a quick, simple grep though, it looks like there's a bunch of division done in the various `gui/` files in mainline for example.

**Comment by CelticMinstrel** [comment]
I think that method of grepping would give some false positives and also miss some in the case of multiline formulas (though that's mostly GUI2, probably). It seems like it would be a good starting point, though.

**Comment by Pentarctagon** [comment]
To be clear though, I'm not volunteering to do the actual search to try and determine the potential impact of changing how WFL division works or to fix the places where it would affect mainline.  So unless there is someone who will do that, I'll leaning towards closing this via the third option I mentioned above.

**Comment by AI0867** [comment]
> Even from a quick, simple grep though, it looks like there's a bunch of division done in the various `gui/` files in mainline for example.

Well, that definitely needs to be integer division in most if not all cases.

**Comment by CelticMinstrel** [comment]
> Well, that definitely needs to be integer division in most if not all cases.

I haven't looked at the specific cases, but a lot of them might be truncating the value after the division anyway. Any key with a type of f_int will already truncate the final value, at least.

Maybe if division is used in some intermediate stage though, it might not be truncated…

**Comment by CelticMinstrel** [comment]
I wonder if it makes sense to log a warning when encountering division that will truncate? Could that help us evaluate the impact of making division non-truncating?

**Comment by Pentarctagon** [comment]
I doubt it, since it's pretty unlikely that users would report seeing the message.

**Comment by CelticMinstrel** [comment]
Well, yeah, I guess it would require someone to actually dedicate the time to try out lots of add-ons, which seems… pretty unlikely…

Plus it would probably be spammed by GUI formulas anyway…

**Comment by CelticMinstrel** [comment]
I'll open a new issue to track the possibility of changing WFL division.
