### ISSUE TITLE
Wesnoth is greatly increasing GPU usage thru Client/Server Runtime Subsystem. 

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5494]
### Game and System Information
 - 1.14.15 / 1.15.9
 - Sourceforge / Steam
 - Windows 10
 - My GPU is GeForce GTX 1060 6GB

### Describe the bug
Wesnoth is greatly increasing GPU usage thru CSRSS. I did talk with others about this and this also happens for them. This issue also exists in 1.15.9 but at the same time it does not cause this big of an increase (up to 16% instead of 27% of 1.14.15).

### To Reproduce

1. Enter any any scenario / game / campaign.
2. Check how much of GPU is CSRSS using in for example task manager.

### Expected behavior
Wesnoth in my opinion should not cause indirect increase in workload of GPU by this much (it seriously made me worried that I either have some malware installed or that some part of my PC is failing, I didn't even expect that wesnoth could be the cause).

### Additional context
[Video of this happening.](https://www.youtube.com/watch?v=4k0BhTgKvk8&feature=youtu.be)

**Comment by Pentarctagon** [comment]
Does turning off water animations or lowering the fps affect the result?

**Comment by Pentarctagon** [comment]
There was a recently slowness report on macOS as well, which is perhaps related - https://forums.wesnoth.org/viewtopic.php?p=662167#p662167

**Comment by Hejnewar** [comment]
> Does turning off water animations or lowering the fps affect the result?

It makes things worse. After dissabling all possible animations it can jump up to above 50% for me... I can post video of this happening too if needed.

**Comment by Pentarctagon** [comment]
Does this happen with earlier versions?

**Comment by Hejnewar** [comment]
I tested 1.14.9 and 1.14.12 (I skipped other versions) it happens in both but they just dont increase workload as much 10% for 1.14.12 for example.

**Comment by Hejnewar** [comment]
I tested this issue a bit more today and I think that this is related to lack of things to do. For example side 2 without units nor leader animations will have GPU usage increased to around 49%, in the same game I spawned 80 gryphons for side 1, ending the turn can drop usage to as little as 5%, after they are revealed for side 2 it will also recive similar drop in usage. Also in replays where things are happening pretty much all the time usage can be as low as 1%. Even things like scrolling the map help with this by droping the usage by 4-6%.

I also tried to crash CSRSS / PC but I wasnt able to, it was always adjusting its own usage to not cross 90% of total usage. During this I didnt expirience too much lag in wesnoth, it was just unnecessarily stressing my GPU.

Also correction for 1.14.12, with the same testing conditions (no animations, no units) this version reached staggering 78% of GPU usage thru CSRSS.

1.14.0 is actually the least stressing version that I tested so far with reasults better than even 1.15.9.

**Comment by Wedge009** [comment]
As a wild guess, could be related to the unconventional way Wesnoth uses SDL? As far as I know Wesnoth still uses software rendering so there's no apparent reason that it should use the GPU in any significant way.

**Comment by Hejnewar** [comment]
Limiting / not limiting FPS seems to have little to no impact on this. There also is a ponit where there are too many animations quequed or something that actaully increases GPU usage iirc, I tested that long time ago by setting animation frequency to 3000 or maybe even higer.

**Comment by Wedge009** [comment]
Could you retest current master, there may be an improvement with #6855 merged.

**Comment by Wedge009** [comment]
Thanks.
