### ISSUE TITLE
animation frame keys x,y do not scale with zoom level

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#5508]
### Game and System Information
 - What version of the game are you running?
 The Battle for Wesnoth version 1.15.9+dev (63c71a010af-Modified) x86_64

#### Libraries
Boost:             1.66
OpenSSL/libcrypto: 1.1.1d (runtime 1.1.1d)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.44.7 (runtime 1.44.7)
SDL:               2.0.8 (runtime 2.0.8)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.2 (runtime 2.0.2)
SDL_ttf:           2.0.14 (runtime 2.0.14)

 - If you're using a custom build, what compiler did you use, and what commit did you build at?
gcc & scons
 - What OS are you running?
Linux

### Describe the bug
The x,y keys are ignored in animation frames.  It's easiest to see in the dunefolk raider, the torch flame is centered on the sprite image.  I believe many of the missile frames are also affected, for example the footpad's rock.

halo_x,halo_y do seem to still work.

I tried this on 1.15.8+dev, forgot to record which commit but from around New Year's, and it seemed to have the same issue.  I'll add the blocker label, but this seems like something that would have been noticed before so it may just be a quirk on my system.

EDIT:  It looks like x,y do still work outside the [frame] tags.
### Screenshots
![Screenshot_000](https://user-images.githubusercontent.com/13510196/106402647-52075080-63df-11eb-9c13-c925d5c75fc0.jpg)
The sidebar image shows where the flame is supposed to be.

**Comment by newfrenchy83** [comment]
Sorry but with me, this work normally. i use 1.15.9dev+  custom build mingw64-8.1.0, boost1-72, sdl-image2.0.5, gcc by codeblock on windows7

**Comment by Pentarctagon** [comment]
It behaves as expected on my system as well - Linux with lastest master:
![raider](https://user-images.githubusercontent.com/3030250/106830324-7bc8ad80-6653-11eb-8255-e60d77869efb.png)

**Comment by doofus-01** [comment]
Sucks for me, but good in general I guess.  It's still a bug, but not a blocker in that case.

**Comment by doofus-01** [comment]
I think I found the issue, @Pentarctagon @newfrenchy83 - does it still work if you zoom in?

**Comment by Pentarctagon** [comment]
Zooming in (or out) does indeed move the torch location for me.

**Comment by newfrenchy83** [comment]
> 
> 
> Zooming in (or out) does indeed move the torch location for me.

For me too.

**Comment by doofus-01** [comment]
Thanks for confirming, it looks like the keys do work, but just don't scale with zoom.  halo_x,halo_y do seem to scale, and I can't think of any reason why not scaling would be the desired behavior.  I'm not sure if this warrants a "blocker" tag, but it is pretty important.
