### ISSUE TITLE
Flatpak nigthly builds are broken

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5515]
### Game and System Information
Fedora 33, flatpak-1.10.1-1.fc33.x86_64

### Describe the bug
Can't install nightly builds from flatpak (https://forums.wesnoth.org/viewtopic.php?f=5&t=47872)

### To Reproduce

1. flatpak install --from http://files.wesnoth.org/wesnoth-nightly.flatpakref

The error message which I got when I tried for the first time:
```
Error: While pulling app/org.wesnoth.Wesnoth/x86_64/master from remote wesnoth-origin: While fetching http://chantal.wesnoth.org:8080/job/Wesnoth/branch=master,compiler=flatpak-builder,label=Fedora/ws/repo/deltas/Ba/X0DRehmstYVjrl+21QhU17zqvczqHwtFk4MnOCWnU/2: [18] Transferred a partial file
error: Failed to install org.wesnoth.Wesnoth: While pulling app/org.wesnoth.Wesnoth/x86_64/master from remote wesnoth-origin: While fetching http://chantal.wesnoth.org:8080/job/Wesnoth/branch=master,compiler=flatpak-builder,label=Fedora/ws/repo/deltas/Ba/X0DRehmstYVjrl+21QhU17zqvczqHwtFk4MnOCWnU/2: [18] Transferred a partial file
```
Error messages which I'm getting when I'm retrying:
```
Error: Failed to read commit 05a5f40d17a19acb58563ae5fb6d50854d7bceabdccea1f0b459383273825a75: No such metadata object 748ed52aaf82425429ed496996a79ff73b0b929e7149f1040ec1191e233ac361.dirtree
error: Failed to install org.wesnoth.Wesnoth: Failed to read commit 05a5f40d17a19acb58563ae5fb6d50854d7bceabdccea1f0b459383273825a75: No such metadata object 748ed52aaf82425429ed496996a79ff73b0b929e7149f1040ec1191e233ac361.dirtree
```

### Expected behavior
Installation of flatpak nightly builds should work

**Comment by soliton-** [comment]
Installation on Debian stable worked fine just now. Perhaps try again a bit later it sounds like there are connection issues to wesnoth.org for you.

**Comment by grz0** [comment]
I successfully installed the nightly build, but I had to execute `flatpak repair` first. This command removed downloaded files which probably were corrupted.
