### ISSUE TITLE
1.15 THoT Movrur should be created if he doesn't exist

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5520]
The usual pattern for not-leader-but-not-allowed-to-die characters in mainline campaigns is to use macros such as `CHARACTER_STATS_AIGLONDUR` or `NEED_DELFADOR` in utils/characters.cfg. This means that they'll automatically be created if the player has a start-of-scenario save from an old version, or when using `:choose_level`.

From IRC discussion about migrating user data from 1.14 to 1.16, we noticed that Movrur is only added if the player starts from scenario 1, the campaign doesn't use the standard pattern.

Seen in the WML as of c42bf114249dcef5241327ca92214cf155ff89e8.

**Comment by Wedge009** [comment]
I admit I don't know too much about WML but I notice that `CHARACTER_STATS_AIGLONDUR` is used regularly because Aiglondur is the leader character. `CHARACTER_STATS_ANGARTHING` is also there, but the macro is only used in one scenario despite Angarthing also being a mission-critical character.

**Comment by cooljeanius** [comment]
Is this something that changed in @nemaara's reworking of THoT?

**Comment by stevecotton** [comment]
Movrur is a new character added in @nemaara's reworking. He doesn't exist in Wesnoth 1.13.12 or earlier.
