### ISSUE TITLE
segfault when trying any MP mode after an attempt to connect alternate server2.wesnoth.org

### ISSUE THREAD

**Issue by celerini** [wesnoth/wesnoth#5528]
### Game and System Information
 - 1.15.9
 - Fedora 33 system repository

### To Reproduce

1. Multiplayer -> Connect to Server -> Alternate Wesnoth Server
2. Confirm the Error window (different versions)
3. Multiplayer -> Local Game (any mode segfaults)

### Additional context
20210208 23:52:58 error network: caught network error: The server accepts versions '1.12*,1.11.17*,1.11.18*,1.11.19*,test*', but you are using version '1.15.9'
20210208 23:52:58 error general: The server accepts versions '1.12*,1.11.17*,1.11.18*,1.11.19*,test*', but you are using version '1.15.9'
wesnoth: src/game_initialization/multiplayer.cpp:162: mp::{anonymous}::mp_manager::mp_manager(const string&): Assertion `!manager' failed.
Neúspěšně ukončen (SIGABRT) (core dumped [obraz paměti uložen])

**Comment by Pentarctagon** [comment]
I can reproduce this on 1.15.9, but not on current master, so it looks like this has already been fixed.

**Comment by Vultraz** [comment]
Should have been addressed in cd120f51186c61e80cb1d54aaaf5ce6ed79f9c8d
