### ISSUE TITLE
UtBS: Mounted Quenoth units don't have an undead variation set

### ISSUE THREAD

**Issue by shikadiqueen** [wesnoth/wesnoth#5529]
None of the units in the Scout and Tauroch Rider unit lines have an undead variation set in either Wesnoth 1.14 or master as of this writing, so they turn into regular walking corpses instead.

(Filing a bug because I don't know if this is somehow intentional, in particular for the Tauroch line.)

**Comment by knyghtmare** [comment]
I can work on this however, what undead variation would be best as a placeholder for a Tauroch (assuming we do an official undead variation for them in the possible future)? I know Dusboks (or whatever they are called) fit well with `mounted`

**Comment by doofus-01** [comment]
Seems like it should be possible to cram in a new WC variation from the campaigns without touching the core files, but I'm not sure how to do it.  I tried redefining WEAPON_SPECIAL_PLAGUE to a new unit
```
   id=Walking_Corpse_utbs
    [base_unit]
        id=Walking Corpse
    [/base_unit]
    name= _ "Walking Corpse UTBS"
    [variation]
        variation_id=dustbok_mounted
        ...
```
but that didn't seem to do anything, maybe because of order in which these things are read and expanded.

I guess something could be simulated with [campaign] level events, but that's a last resort.

**Comment by CelticMinstrel** [comment]
I think dustbok can just use the regular mounted variation. The tauroch could as well, but here a custom one might be better.

I think the way to cram in a custom variation would be to override all the units that have the plague ability to replace `{WEAPON_SPECIAL_PLAGUE}` with `{WEAPON_SPECIAL_PLAGUE_TYPE Walking_Corpse_utbs}`. Assuming the code you posted works to add a new variation:

```
   id=Walking_Corpse_utbs
    [base_unit]
        id=Walking Corpse
    [/base_unit]
    #textdomain wesnoth-units
    name= _ "Walking Corpse"
    [attack]
        [specials]
            {WEAPON_SPECIAL_PLAGUE_TYPE Walking_Corpse_utbs}
        [/specials]
    [/attack]
    [variation]
        variation_id=dustbok_mounted
        ...
```

That's assuming that the attack is the first attack on the unit (which I think it is for all of the relevant units). If it's not you'd need to add an empty `[attack]` tag above that one.

Don't forget to override the necromancer too, if that's used anywhere in UtBS.

**Comment by doofus-01** [comment]
> Don't forget to override the necromancer too, if that's used anywhere in UtBS.

That's actually what I was getting at, not the zombie attack.  It would be nice to have a way to do that without customizing every possible plague unit, could be useful for UMC and maybe SotA or DiD (I don't remember).

**Comment by CelticMinstrel** [comment]
Sure, but there are only three plague units to customize, right?

I think moving the quenoth to core is the best option, though.

**Comment by shikadiqueen** [comment]
If we really want Tauroch Riders to have their own variation (bearing in mind that invariably means new stats and art) I feel it would be best to make it generic enough that it can be used by anything vaguely resembling "guy riding big beefy beast", without necessarily enforcing the after-the-Fall ties.

**Comment by doofus-01** [comment]
> I think moving the quenoth to core is the best option, though.

That would solve some issues, and make it easier for UMC to include them.  I guess they should be hidden behind some preprocessor symbol like AFTER_THE_FALL_EPOCH

> If we really want Tauroch Riders to have their own variation (bearing in mind that invariably means new stats and art) I feel it would be best to make it generic enough that it can be used by anything vaguely resembling "guy riding big beefy beast", without necessarily enforcing the after-the-Fall ties.

A variation without new art would be a pretty crappy variation.  What other beefy beast-riders are there?  UMC counts, though if it's too different from a tauroch I probably can't take it into account (no giant frogs, for example)

**Comment by CelticMinstrel** [comment]
You can see prior discussion on this matter in #3414. It seems like more people are in support of moving the Naga Hunter line to core than the Naga Guardian line.

> I guess they should be hidden behind some preprocessor symbol like AFTER_THE_FALL_EPOCH

I don't think it's necessary to hide them; the extra units will only be visible to the Create Unit debug screen, and UMC would be able to use them without any special measures.

**Comment by shikadiqueen** [comment]
> I don't think it's necessary to hide them; the extra units will only be visible to the Create Unit debug screen, and UMC would be able to use them without any special measures.

Well, after being discovered they *would* remain listed on the help browser even when UtBS (or any other add-on that uses them) is not currently being played.

**Comment by doofus-01** [comment]
> You can see prior discussion on this matter in #3414. It seems like more people are in support of moving the Naga Hunter line to core than the Naga Guardian line.

That seems a bit outdated, since Lordbob has some concept sketches for the mace nagas and the newer dunefolk nagas are now a thing.  There might need to be some stats adjustments, but now would be the time to figure that out.

**Comment by CelticMinstrel** [comment]
Yeah, that _is_ indeed a fairly old PR, so current sentiment may differ.

**Comment by CelticMinstrel** [comment]
Also note that there was a previous PR about the Quenoth: #4687

**Comment by shikadiqueen** [comment]
> Are you saying this is a good thing or a bad thing?

I'm just pointing it out, really.

**Comment by doofus-01** [comment]
Moving the Quenoth to core is overkill for the reported issue.  I'm making a "beast rider" WC variation in #5551, which is a much simpler project.

There is #5532 that adds a new faction too, but is not aimed for 1.16.  Maybe the Quenoth move should be a thing for 1.17/1.18 as well.
