### ISSUE TITLE
UtBS: Hekuba attempts to play Jesus in Blood is Thicker than Water

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesnoth#5540]
Emphasis on "attempts".

In UtBS scenario 9 (Blood is Thicker than Water) if all enemy leaders are killed before all merfolk are sacrificed (turn 16) or rescued (before turn 16), one of the Council leaders — Hekuba — is spawned on deep water at 15, 28. He only exists for the duration of a short cutscene before being removed from the game and created again at the Iron Council island's keep during a much later event.

There's nothing technically wrong with this but the choice of terrain for his temporary location is rather immersion-breaking. It happens on both 1.14 and master.

**Comment by stevecotton** [comment]
Tempting to stick him on the mountains around 16,18, which would also act as a hint about where the player will need to move their forces for the third act of this scenario.
