### ISSUE TITLE
World Conquest is Unplayable beyond the first scenario

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5545]
### Game and System Information
 - What version of the game are you running?
 1.15.9 
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 SourceForge
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
N/A
 - What OS are you running?
  Windows 10

### Describe the bug
World Conquest seems unplayable after the first scenario. I either get a LUA error or a new faction-choice menu, which if tampered with completely crashes to the mainmenu

#### Screenshots
![Screenshot 2021-02-15 223600](https://user-images.githubusercontent.com/5283677/107974917-7cf9c300-6fe1-11eb-89db-8f295f1aa166.png)
![Screenshot 2021-02-15 225255](https://user-images.githubusercontent.com/5283677/107974926-7ff4b380-6fe1-11eb-9615-578f7498dc9e.png)

### To Reproduce
1. Play World Conquest 1p under Random Maps
2. Select any difficulty 
3. win 
4. and then click "end scenario"

[WC II 1 - Start replay 20210215-231927.gz](https://github.com/wesnoth/wesnoth/files/5983124/WC.II.1.-.Start.replay.20210215-231927.gz)
[WC II 1 - Start-Auto-Save12.gz](https://github.com/wesnoth/wesnoth/files/5983126/WC.II.1.-.Start-Auto-Save12.gz)

**Comment by shikadiqueen** [comment]
For me, the following happens as soon as you launch a newly created game using WC:

![image](https://user-images.githubusercontent.com/489895/108604381-601c1180-738c-11eb-9f23-87a4e825e4a4.png)
