### ISSUE TITLE
Plan Unit Advance modification doesn't work

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5546]
### Game and System Information
The Battle for Wesnoth version 1.15.9+dev (e28d0399-Clean) x86_64
Running on Linux 
Distribution channel: Flatpak nightly

### Describe the bug
Plan Unit Advance is not working, it throws LUA error in console.

### To Reproduce

1. Create a new local game
2. Enable Plan Unit Advance 
3. Recruit a unit which has multiple advancement options 
4. Click 'Pick Advance'

### Expected behavior
It should work.

### Screenshots
![Screenshot_20210215_182239](https://user-images.githubusercontent.com/3605541/107977063-cc78c880-6fba-11eb-826b-c6b23a7824ac.png)

**Comment by Pentarctagon** [comment]
It looks like this was caused by 561cc33dc41d5b1561934d5c9e184f1da8545195
