### ISSUE TITLE
Flatpak nightly builds require old freedesktop runtime

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5552]
### Describe the bug
Flatpak nightly builds require Freedesktop 19.08 runtime which is older than 20.08 used by Wesnoth installed from Flathub.

### To Reproduce

1. flatpak install --from http://files.wesnoth.org/wesnoth-nightly.flatpakref
2. flatpak list  --app --columns=application,runtime | grep wesnoth

### Expected behavior
Flatpak nightly builds should use Freedesktop runtime 20.08 or maybe even 21.08beta from freedesktop-sdk

**Comment by Pentarctagon** [comment]
@loonycyborg I'd guess it'd just be updating the last line of https://github.com/wesnoth/wesnoth/blob/master/utils/dockerbuilds/CI/Dockerfile-base-flatpak to 20.08?  I don't see a need to start using a beta runtime.
