### ISSUE TITLE
Offscreen video rendering of replays

### ISSUE THREAD

**Issue by kallaballa** [wesnoth/wesnoth#5553]
### Game and System Information
 - What version of the game are you running?
Stable

 - What OS are you running?
 Linux

### Describe the desired feature
I'd like to be able to render videos of replays offscreen and as fast as possible. I'm interested in implementing it myself. In the absence of better advice I'd probably use: https://github.com/kallaballa/SDLVideoCapture. The downside of that project is that it depends on ffmpeg. Would that be acceptable?

**Comment by Pentarctagon** [comment]
What's the use case for this?

**Comment by kallaballa** [comment]
I want to be able to create time-lapse videos and use them to analyze games in a visual manner. I can't even guarantee that the videos i want to generate will be of any significance. That said, if you want me to come up with ideas of how people might use it, i cculd :)

**Comment by Pentarctagon** [comment]
Features should always be added because they will be used, especially if they're going to introduce additional dependencies (even in this case where it would need to be an optional dependency).  So it would definitely be good to know what the goal is and why this helps with them.

**Comment by soliton-** [comment]
Not sure what the plan is but I would suggest to implement it as a standalone tool (which of course can share code with wesnoth). Then it could be integrated with replays.wesnoth.org for example...

**Comment by kallaballa** [comment]
The preliminary plan is to render specific matchups (e.g.: side1: drakes, side2: undead, on hamlets) of top ladder-games and blend them together into a timelapse video.

**Comment by kallaballa** [comment]
I'll start with a fork of wesnoth. let's see if i can make a separate tool.
https://github.com/kallaballa/wesnoth

**Comment by soliton-** [comment]
> The preliminary plan is to render specific matchups (e.g.: side1: drakes, side2: undead, on hamlets) of top ladder-games and blend them together into a timelapse video.

Just to be clear I would suggest that deciding on the matchup/replay is the job of the caller though. I imagine a tool that just takes a replay/save file as input and outputs a video. Something like: `wesnoth_replay_renderer -i myreplay.gz -o myreplay.mp4`

**Comment by kallaballa** [comment]
that makes sense. I'm on it, but i found something curious: in-game messages don't seem to be rendered using SDL (through canvas) as far as i can see. How are they being rendered?

**Comment by shikadiqueen** [comment]
> that makes sense. I'm on it, but i found something curious: in-game messages don't seem to be rendered using SDL (through canvas) as far as i can see. How are they being rendered?

What messages are we talking about? Ultimately everything in the game goes into the display framebuffer exposed by SDL without exception.

**Comment by kallaballa** [comment]
thx, but I gave up on that project.

**Comment by cooljeanius** [comment]
aw man, I thought it was a cool idea... oh well...
