### ISSUE TITLE
Desert mountains have pretty rough transition with any water terrain

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5554]
Desert mountains have pretty rough transition with any water terrain. I dont know if its an actual bug but in my opinion it doesnt look good.

@doofus-01 could you take a look at this? 

### Screenshots
![transition](https://user-images.githubusercontent.com/41817546/108130897-ab929f00-70b0-11eb-95d0-01783e98ad1f.JPG)

**Comment by doofus-01** [comment]
Hmm, the water transition looks OK to me, but the swamp does look a bit strange (though it's also a bit conceptually strange).  The cave wall transition might also deserve a look.  The good news is that this can be fixed at any time, no release deadline.

**Comment by doofus-01** [comment]
Feel free to reopen if there is anything more to add, but as it is, this is just keeping our bug count up.
