### ISSUE TITLE
Plan Unit Advancement  UI is not consistent with the rest of game UI

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5555]
### Game and System Information
The Battle for Wesnoth version 1.15.9+dev (a0ee38a4-Clean) x86_64

### Describe the bug
Plan Unit Advancement UI is not consistent with the rest of the game UI:
* the window's title has a different font style than other dialogues
* unit color doesn't match team color, it is always pink
* cancel button is missing
* IMHO 'Save(All)' button should be replaced with a checkbox

Current implementation:
![image](https://user-images.githubusercontent.com/3605541/108135744-f57f8300-70b8-11eb-9bc2-ea23cd9fe687.png)

vs my quick attempt to fix these issues:
![image](https://user-images.githubusercontent.com/3605541/108102451-d9fc8400-7088-11eb-8b9a-63d10316b720.png)

**Comment by CelticMinstrel** [comment]
Or maybe a radiobutton?

```
(*) Apply only to <unit name>
( ) Apply to all <unit type>s
```

**Comment by shikadiqueen** [comment]
All should be fixed now.
