### ISSUE TITLE
Where is Ratheln

### ISSUE THREAD

**Issue by dsime42** [wesnoth/wesnoth#5560]
### Game and System Information
 - What version of the game are you running?
1.15.8
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Fedora 32 repository
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
N/A
 - What OS are you running?
Linux 5.10.15-100.fc32.x86_64 
Fedora FC32 

### Describe the bug
I have been to 13 of the 13 villages and no mage

### To Reproduce
Visit every village

### Expected behavior
Isn't there supposed to be a Mage in one of the villages?

### Savefiles
file:///home/don/.local/share/wesnoth/1.15/saves/THoT-High%20Pass%20replay%2020210218-113255.gz

**Comment by dsime42** [comment]
Did that submission send the replay file or do I need to put it somewhere that it can be accessed?
It said drag 'n drop but I'm unsure that it worked

**Comment by Pentarctagon** [comment]
It didn't work.

**Comment by knyghtmare** [comment]
This campaign was recently reworked and as far as I know, there is no Rathelyn or the scenarios "Mages and Drakes" anymore.

**Comment by dsime42** [comment]
Well, ... "there is no Ratheln" ... could certainly be part of my problem.

Thanks
