### ISSUE TITLE
DiD S09: Effect of Zephryn’s laboratory on the story

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5572]
After the ritual has already finished and Malin is supposedly back from death, he finds a sign saying `<s><i>Welcome to Zephryn’s laboratory. Please be mindful of ongoing experiments during your visit.</i></s>
<big><i><b>This territory is the domain of the mighty Xanthric. All unwelcome intruders shall die.</b></i></big>` and he responds `That mage’s name is suspiciously... familiar`, pointing out that it's almost the name of the mage whose death caused Malin's expulsion from Alduin.

I think this sign makes everything after `Leave me while I prepare` a dream that happens as he succumbs to the poison, although I think that was unintentional given the lack of response to the translator's question in https://r.wesnoth.org/t53464 . @nemaara for both translation and for UMC authors that are trying to connect to the canon, we should have a clear explanation of what actually happens in S09.

**Comment by nemaara** [comment]
Yknow I rather like your interpretation, I think it fits rather well thematically.

Maybe I'm confused but exactly what are you asking for in this issue?

**Comment by stevecotton** [comment]
> Yknow I rather like your interpretation, I think it fits rather well thematically.

While it fits the logic of the story, it seems an unsatisfying fate for a player-character protagonist.
* The player wins the master vs apprentice battle, but then the character goes and suicides off-screen.
* The player amasses an awesome army with a dragon, but it was just a dream.

There's a loose end about what happens to the book. Another necromancer probably learns of it and does a quest to find it; however that would be a story that's already been told.

> Maybe I'm confused but exactly what are you asking for in this issue?

Mainly to add a note in the writer's bible (whereever that is, maybe Secret Lore) saying whether Malin managed to become a lich.

My preference for the storyline would be that he does manage it. Maybe move all the puzzles into a fourth stage of the ritual: "The final task of the ritual will be to reanimate my own corpse. However, it seems each of these puzzles is a memory of a lesson from Alduin that I didn't master back then; perhaps there is still time to learn from them."

After the ritual, instead of searching for rats he could wake already surrounded by hungry rats who have been doing the task of stripping the flesh from his skeleton for him.

**Comment by nemaara** [comment]
Sorry but I don't agree, a core element of almost all of my writing is leaving things open to interpretation.

**Comment by stevecotton** [comment]
IMO that doesn't fit with having translatable stories and a team-created world where UMC can fit with canon. But I'll close the issue.
