### ISSUE TITLE
HttT Isle of the Damned: temples look recently built

### ISSUE THREAD

**Issue by vasiousbloods** [wesnoth/wesnoth#5576]
Terrain description for the ancient temples is currently just "dirt flat". Konrad refers to them as "ancient temples".
They don't look ancient, though. Perhaps just **"temple"** would do?

**Comment by cooljeanius** [comment]
well the temples were also there in the scenario in The Rise of Wesnoth that also takes place there, and that was 517 years before HttT, so I'd say that qualifies as "ancient"

**Comment by vasiousbloods** [comment]
> well the temples were also there in the scenario in The Rise of Wesnoth that also takes place there, and that was 517 years before HttT, so I'd say that qualifies as "ancient"

ah well indeed they are, and so the art is what should really change. Some cracks and what not- im not so sure. They just look like new buildings and first time players i have seen have said it :p 

but i surgested a word change as its a lot less work!

**Comment by Wedge009** [comment]
From a purely game-play perspective, I find the clean temples stand out and draw attention that way - often scenarios will include bonuses (or surprise attacks) for sending units there. Sometimes there's a dissonance between story and visuals for the sake of game-play.

**Comment by Wedge009** [comment]
They look good, but I'm not sure how graphics are integrated into the file structure - eg campaign-specific resources vs core resources.
