### ISSUE TITLE
MP lobby - poor performance

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#5578]
While it's been a well known problem for a while, it's apparently never been explicitly documented: once the number of players on the official multiplayer server reaches 150+, the responsiveness of the lobby can degrade to the point where typing messages and clicking buttons is noticeably delayed.  This is a major problem if we want Wesnoth's popularity to increase - people won't keep playing the game if every time more people start playing the lobby starts badly lagging.

From what I understand the cause of the lagging is because the tree view containing the list of player names is very slow to update, and right now is being cleared and replaced entirely each time anyway.

Tagging @Vultraz and @shikadiqueen for additional information as well.

**Comment by Pentarctagon** [comment]
A suggestion brought up on Discord was to only update the UI on a timer (every 5 seconds?) instead of on every change like is currently done.  While it's of course better to keep the information displayed as up to date as possible, it becomes rather irrelevant if said UI can't actually handle updating that frequently.

**Comment by Pentarctagon** [comment]
As an update to the above comment - it was determined that the UI doesn't actually update more than once per second even if it receives updates more frequently than that.  So the issue is definitely the time it takes for the UI to update itself once there are a certain number of players online rather than it trying to update more frequently than it can handle.

Also, for trying to replicate the lagging encountered without needing to wait for a time when 150+ players are online, there's https://github.com/renom/fastbot that could probably be used to replicate that.  Also potentially an option could be to see if there's a way to pre-populate the player list with a set of dummy players, though I'm not sure yet whether that's actually possible or not.

**Comment by soliton-** [comment]
It might be easiest to use `utils/wesnothd.pl` to create a wesnothd test instance which produces whatever kind of player join/quit pattern and the according userlist update messages.

**Comment by soliton-** [comment]
It's a wesnothd implementation in perl. It's not ready to use for what I suggested. One would have to implement the user activity and possibly also update a thing or two since this is quite old and there probably were a couple protocol changes... Actually it seems this still uses binary WML so nevermind. Probably too much work to update then.

I thought it would be nice to have something in a scripting language so it's simpler to quickly code up different test scenarios. But it looks like hacking in a dummy/demo mode into wesnothd proper is easier.

Using a simple client/bot implementation is certainly also an option but might cost quite a bit of resources if you want to simulate 300 users or so. Would be very flexible as well though.

**Comment by Pentarctagon** [comment]
Is there any reason to keep wesnothd.pl around, in that case?

**Comment by Pentarctagon** [comment]
After modifying wesnothd to pre-populate its user list with 500 users and then adding or removing one every 30 seconds, the following profiling information was generated, as an image:
![prof](https://user-images.githubusercontent.com/3030250/121061774-e452a300-c789-11eb-9b4a-e408786ffbb7.gif)

And then also as text:
[prof.txt](https://github.com/wesnoth/wesnoth/files/6610888/prof.txt)

**Comment by soliton-** [comment]
Looks like either `tree_view` shouldn't be used for this or it needs a mode where it doesn't resize itself on each `tree_view_node::add_child` but where one could manually trigger a resize after doing a bunch of changes. I assume this would also help all tree_view uses where most items are added in one go initially. (Which I expect to be the most common use case.)

The other thing is that the lobby constantly clears the whole thing and adds everything again. Which seems in itself quite silly and just makes the issue much worse the more players there are...

**Comment by stevecotton** [comment]
The main issue is why it's getting resized so often (the issues @soliton- pointed out), but styled_widget::update_canvas looks far too expensive for its documented role of getting called every time the widget gets resized. Most of the profiled time is spent creating and copying WFL formulas, where the old and new copies are probably identical.

That would be faster in a non-debug build, but it's still a possible optimisation.

**Comment by Pentarctagon** [comment]
Release build (-O3) as well:
<details><summary>image</summary>![prof](https://user-images.githubusercontent.com/3030250/121260791-6a004c80-c877-11eb-8bc7-e0e90a6d2c58.gif)</details>

[prof.txt](https://github.com/wesnoth/wesnoth/files/6619725/prof.txt)

**Comment by Pentarctagon** [comment]
If I'm reading this right, it looks like the bottleneck is that:
* The tree gets cleared entirely each time.
* Each item in the tree is then re-added using the updated list.
* Each time an individual item is re-added, it calculates the dimensions needed for the UI element.

So it sounds like the fix would be to add a way for all the items to be re-added at once, and only then re-calculate the element's size, since for N players every size calculation from 1 through N-1 is wasted isn't it?

**Comment by soliton-** [comment]
Yes, that is similar to "manually trigger a resize after doing a bunch of changes." Since adding multiple items is presumably the most common use case that might be a nicer way to reach the same goal.

Since the updates are done by diffs it should also be fairly easy to just do the necessary changes instead of clearing and rebuilding. But if the above optimization is done that might not make much of a difference anymore.
