### ISSUE TITLE
Writing style for tips on the home screen

### ISSUE THREAD

**Issue by phineix** [wesnoth/wesnoth#5585]
on `Memoirs of Gweddy, 627YW` we see the word "Unfortunately" rather than something like "However". 
Whist sure, who ever Gweddy is might dislike skirmishers, from a game design perspective its a little odd to have biasness in the main menu. If perhaps all the menu texts like this have a balance of every characters' point of view in the wesnoth world and in time line, then nvm this. 

:D

**Comment by Wedge009** [comment]
On the contrary, I think it adds character if the tips have a little personality to them. As a native Anglophone, I don't necessarily ascribe bias to the use of 'unfortunately' either.

Still, I'm not sure who looks after the Help tips, maybe @nemaara might have an opinion on this.

**Comment by nemaara** [comment]
If it has an attribution to the character, it should match the character's voice. If it's from the Wesnoth encyclopedia, the tip should be written formally without bias. I do think most of the tips are written pretty decently as they are right now, so I'll close this for the time being.

**Comment by Wedge009** [comment]
Agreed, thank you.
