### ISSUE TITLE
Lua: some missing variable declarations

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#5586]
My Lua linter found a few references to undeclared variables that I'm not sure how to resolve:

```
data/ai/lua/ai_helper.lua:1385 - Undefined variable `attack_array`.
data/ai/lua/battle_calcs.lua:1234 - Undefined varaible `cfg`.
data/ai/lua/battle_calcs.lua:1237 - Undefined variable `cfg`.
data/ai/micro_ais/cas/ca_messenger_move.lua:50 - Assigning undeclared variable `nh_cost`
    I think maybe `optimum_cost` was intended but not sure
```

**Comment by CelticMinstrel** [comment]
Huh? I could've sworn I edited in one more issue... well, suffice to say I think there _is_ one missing from that list.

**Comment by mattsc** [comment]
Let me know what it is and I'll fix it along with the others once my build is not crashing any more.

**Comment by CelticMinstrel** [comment]
It _might_ have been data\ai\micro_ais\mai-defs\protect.lua:49? That ones fairly obvious though, I'm not sure why I didn't already fix it...
