### ISSUE TITLE
Could you tag the development branches as dev/beta prerelease on github?

### ISSUE THREAD

**Issue by romulasry** [wesnoth/wesnoth#5590]
Thanks in advance.

**Comment by Pentarctagon** [comment]
So just add "-dev" to the tag name?

**Comment by romulasry** [comment]
That would work.

**Comment by Pentarctagon** [comment]
I've added that to my notes for the future, so since I'm not going to go back and re-tag a bunch of releases I'll close this.

**Comment by romulasry** [comment]
Either that or check the box in github with "prerelease" on it.

**Comment by romulasry** [comment]
Doesn't seem to be working,, see: https://release-monitoring.org/project/8621/
