### ISSUE TITLE
Add support for parent `..` directory preprocessor access

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#5592]
When doing Preprocessor file/directory inclusions, allow using `..` to denote parent directory.

See here: https://wiki.wesnoth.org/Preprocessorref#File.2Fdirectory_inclusions

For example, allow writing
`{CURRENT_DIRECTORY}/../wml/my_other_file.wml`
or
`{CURRENT_DIRECTORY}/../lua/something.lua`

Having a way to access parent directory would improve the ability to structure files in wesnoth I believe, as opposed to dropping dozens of files all in the addon's root directory.

From a security perspective, we have to limit which files can wesnoth access. That is fairly easy to do with e.g. just collapsing `..` with previous segment of the path, and then use that path to resolve the file in a standard way

Thoughts?

**Comment by Pentarctagon** [comment]
There's #4953 to add this, as well as #1033 before it, however #4953 is in limbo at the moment since gfgtdf isn't around at the moment.

**Comment by vgaming** [comment]
@Pentarctagon Thanks! I thought I've seen this this before, but couldn't find it. Apparently it was a PR, not an issue.

As an issue, this issue will be the first one it seems, so it can stay?. (Correct me if I'm wrong)

**Comment by Pentarctagon** [comment]
It hasn't been implemented, so yeah, no reason to close it.

**Comment by Wedge009** [comment]
Doesn't this duplicate #2180? Also opened by @vgaming. Or is this something different?

**Comment by Pentarctagon** [comment]
These sounds identical, yeah.

**Comment by vgaming** [comment]
Oh wow.. I probably searched for keywords like `..` or `parent` before opening this issue.. But the old one didn't have the word "parent" in it. I've added it now.

Thanks for detecting this and closing.
