### ISSUE TITLE
CURRENT_FILE and CURRENT_DIRECTORY macros not working inside #define

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#5593]
Context/example, this DOES work:
```
# include something.cfg
{{CURRENT_DIRECTORY}/wml/something.cfg}
```

However, this fails:
```
#define ADDON_DIR
{CURRENT_DIRECTORY}#enddef
```

It would be nice if the latter example would work as well. Currently, {CURRENT_DIRECTORY} will expand to an empty string (or not expanded at all?), which I think is a bug. Thoughts?

**Comment by soliton-** [comment]
Perhaps you expect {CURRENT_DIRECTORY} to be expanded when ADDON_DIR is defined? But it is expanded where you expand {ADDON_DIR}.

You can test the same thing with
```
#define A 
a#enddef 
#define B 
{A}#enddef 
#define A
b#enddef
key={B}
```
`key` will be set to b not a.

Perhaps you're asking for a preprocessor symbol that expands to the base dir of the current addon?

Would be good to know the use case to decide what's needed.

**Comment by vgaming** [comment]
@soliton- Sorry, apparently I've missed the email notification. I think this bug can be closed: it's not actionable as I don't have any desires for macro expansion anymore (I'm using other techniques now).
