### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by acroobat** [wesnoth/wesnoth#5597]
### Game and System Information
 - version 1.14.15
 - downloaded from archlinux repo

### Describe the desired feature
Please add for gamers and fans **"Back"** button in Game lobby screen(players choose fraction, side etc)  which will return to Create game screen(player choose map, era etc)

When the game scenario is finished i mean map is over,  player also have to be returned to Create game screen instead of Main menu screen(player choose Tutorial, Campaings etc)

**Comment by shikadiqueen** [comment]
> When the game scenario is finished i mean map is over, player also have to be returned to Create game screen instead of Main menu screen(player choose Tutorial, Campaings etc)

Is this for local (not networked) MP specifically? Because it wouldn't be a good idea in networked multiplayer, where people would expect to be returned to the MP lobby instead of the Create Game flow.

**Comment by acroobat** [comment]
For both I guess. What is the reason to return into the network MP lobby instead of "Choose Map" title screen?

**Comment by shikadiqueen** [comment]
I can't speak for everyone else tbh, but I'm pretty sure people after a long match might not necessarily want to create another game right away.

**Comment by acroobat** [comment]
Maybe you are right or they wanna play more and more.

**Comment by acroobat** [comment]
> people after a long match might not necessarily want to create another game right away.

Btw, turn countdown timer works wrongly. Player can recruit even after timer is over. Unfortunately i can't check this in network game as it is development  version with no people on server.
