### ISSUE TITLE
tile connection errors on sunken castle

### ISSUE THREAD

**Issue by Violetnred2** [wesnoth/wesnoth#5611]
Sunken Human Ruin castle gets weird walls that are split in half if the castle has mixed surrounding of regular water titles and other tiles, even swamp tiles:
https://i.imgur.com/dR8iGQD.png
https://i.imgur.com/HFsacSi.png
https://i.imgur.com/AxsEBmZ.png

**Comment by doofus-01** [comment]
I'm not totally sure why the walls are split the way they are, but it's been like that for most of Wesnoth's existence.  Possibly there is a reason, possibly not.  Fortunately, there are the alternatives for any map maker.

**Comment by Violetnred2** [comment]
what do you mean by "alternatives", if i may ask?

**Comment by doofus-01** [comment]
The ruined and swamp-ruined.  It doesn't completely eliminate the split wall, but I'm pretty sure you need to look for it to see it and know what it is.
