### ISSUE TITLE
wrong backgronud tiles on some villages

### ISSUE THREAD

**Issue by Violetnred2** [wesnoth/wesnoth#5612]
1.14.15 game version
Cave Village and Log Cabin has one building variant each that ignore terrain underneath them and always overlay it with the green grass tile:
https://i.imgur.com/Lpp6nIT.png
https://i.imgur.com/jKMJRS5.png

**Comment by doofus-01** [comment]
I can't reproduce in 1.15, and don't see such a glitch in the 1.14 image files.  I'm also not sure why the cave village would have a grass hex.  Does anything special need to be done to recreate this?  Are you sure this isn't caused by an add-on?

**Comment by Violetnred2** [comment]
right, terribly sorry. failed to mention this:

hold SHIFT while placing a village to place it without the tile that comes with it.

**Comment by Violetnred2** [comment]
actually nevermind - this seems to be fixed on 1.15.10

**Comment by doofus-01** [comment]
I don't believe there was any fix to village images (none needed).  I think there was some image cache issue at some point, that caused odd graphics bugs, but I don't remember enough about it to link here.
