### ISSUE TITLE
Narrow game width breaks side menu

### ISSUE THREAD

**Issue by Violetnred2** [wesnoth/wesnoth#5620]
happens on 1.15.10, but not on 1.14.15. 

happens if a window is narrower than 800 pixels or so

side menu in map editor get buttons that are misaligned, "End Scenario" button after a game ends is misaligned as well and loses it's decoration.

![wesnoth_0rAncreZqG](https://user-images.githubusercontent.com/26041224/111482644-c3efeb00-873c-11eb-94cc-ffda3a5096b5.png)
![wesnoth_vU5fFltxYu](https://user-images.githubusercontent.com/26041224/111482649-c5211800-873c-11eb-8ba9-ac0a8c9a5f56.png)

**Comment by shikadiqueen** [comment]
For the record, it's intentional that on smaller sizes the End Turn button looks like a normal button instead of being the big decorated button you see at 1024x768 and larger. (Everything else is bugs, of course.)

**Comment by Pentarctagon** [comment]
The minimum requirements for the window size on the website homepage are listed as 800x600, so are windows smaller than 800 pixels meant to be supported?

**Comment by shikadiqueen** [comment]
No, but you can see in the screenshot that in reality the horizontal resolution is higher than 800 (and smaller than 1024).

**Comment by Violetnred2** [comment]
ok, i looked at my window width this time - it is 960. 

the exact width below which the side panel break is 1032.

**Comment by shikadiqueen** [comment]
Just found out this also affects the regular game theme **if** and only if the replay UI is active.

![image](https://user-images.githubusercontent.com/489895/111710979-8e74fb80-8829-11eb-86a9-11ec7530daa2.png)

**Comment by shikadiqueen** [comment]
Reverting the following three commits in order shows it's another side-effect of #4851.

* 2e6a043c1a40854a08704d3614502b5b07c84fd8
* 399fd8adf96ab2dbd40f2ac4fd5cc273e002e015
* 43de778c6aad8710707680a6b59ba0adbabbe565

**Comment by shikadiqueen** [comment]
For reference (I don't think I can look into this right now) the issue with the replay UI seems to stem from the aforementioned changes and related not taking into account the optional existence of the replay UI at all.

Not sure about the editor and the turn button.

**Comment by Wedge009** [comment]
Had a look at the End Turn button specifically. Don't think I found anything new that hasn't already been mentioned here.
https://github.com/wesnoth/wesnoth/issues/6544#issuecomment-1053715284

**Comment by mesilliac** [comment]
I fixed these all.

It was a mess.
