### ISSUE TITLE
Random wesnoth crashes during loading screen

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5629]
### Game and System Information
 - 1.15.11
 - Steam
 - Windows 10

### Describe the bug
Wesnoth is randomly crashing during loading of game / mp (trying to enter local or mp server) / campaigns (trying to enter campaign selection screen). Game is not stopped or without answer, it's process is ended completely and instantly.

### To Reproduce
I have no idea how to reproduce it. It just happens from time to time usually during first launch of wesnoth. After certain section loads properly it doesn't crash again unless I reset my PC.

**Comment by shikadiqueen** [comment]
Do you have any add-ons installed? Can you provide the report from the game version dialog's (main menu → "i" in the bottom left) copy-to-clipboard option?

**Comment by Hejnewar** [comment]
> The Battle for Wesnoth version 1.15.11 x86_64
Running on Microsoft Windows 10 2004 (10.0.19041) x86_64
Distribution channel: Steam

Game paths
==========

Data dir:        G:\Steam\steamapps\common\wesnoth
User config dir: C:\Users\USER\Documents\My Games\Wesnoth1.15
User data dir:   C:\Users\USER\Documents\My Games\Wesnoth1.15
Saves dir:       C:\Users\USER\Documents\My Games\Wesnoth1.15\saves
Add-ons dir:     C:\Users\USER\Documents\My Games\Wesnoth1.15\data\add-ons
Cache dir:       C:\Users\USER\Documents\My Games\Wesnoth1.15\cache

Libraries
=========

Boost:             1.74
OpenSSL/libcrypto: 1.1.1i (runtime 1.1.1i)
Cairo:             1.17.4 (runtime 1.17.4)
Pango:             1.48.0 (runtime 1.48.0)
SDL:               2.0.12 (runtime 2.0.12)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.4 (runtime 2.0.4)

Features
========

Lua console completion:       yes
Win32 notifications back-end: yes

Current video settings
======================

SDL video drivers:       [windows] dummy
Window size:             1920x1017
Screen refresh rate:     60
Screen dots per inch:    96.000000x96.000000
Screen dpi scale factor: 1.000000x1.000000

Current audio settings
======================

Audio not initialized.

Installed add-ons
=================

Era:                1.0.3
Knyght_MP_Campaign: 0.0.3
Mercenaries:        Unknown

**Comment by Pentarctagon** [comment]
Is there an add-on literally called just "Era"?

**Comment by Hejnewar** [comment]
Yes it's mine. Mercenaries is my unanounced project, it's a campaign (also used to test MAIs). I dont think that they can cause any problems, they didn't in the past and they don't modify core in any way (unless Knyght_MP_Campaign: 0.0.3 does but I don't think it does).

**Comment by Pentarctagon** [comment]
It would be interesting to see if it keeps happening even with no add-ons present.  About how often does it tend to crash?

**Comment by Hejnewar** [comment]
Will test that tomorrow. 0-3 times right after first launch, on average it would be like 1 every 2 days for me, only today I got 3.

**Comment by stevecotton** [comment]
> Is there an add-on literally called just "Era"?

It's the "Era of Creations", which as @Hejnewar has already said is his. @Hejnewar, if it had a forum topic then I'd have posted a bug report about its name in there...

**Comment by Hejnewar** [comment]
At this point I would just remove it form add-on server. :P I probably should do that anyway honestly. 

Today I got not a single crash with or without add-ons and I tried to get one.

**Comment by stevecotton** [comment]
I'm seeing intermittent crashes on the loading screen when starting Wesnoth, and I can see how the same bug could trigger on the loading screen when entering multiplayer mode. AFAICS:

The data thread is in game_config_manager::load_game_config(), using WFL for movetype patching
```
in (anonymous namespace)::patch_movetype(movetype&, std::string const&, std::string const&, std::string const&, int, bool)
in unit_type_data::set_config(game_config_view const&)
in game_config_manager::set_unit_data()
in game_config_manager::load_game_config(bool)
```

The GUI thread is using WFL for ThemeWML
```
in wfl::call_stack_manager::~call_stack_manager()
in wfl::formula_expression::evaluate(wfl::formula_callable const&, wfl::formula_debugger*) const
in wfl::formula::execute(wfl::formula_callable const&, wfl::formula_debugger*) const
in wfl::formula::evaluate(wfl::formula_callable const&, wfl::formula_debugger*) const
in gui2::typed_formula<unsigned int>::operator()(wfl::map_formula_callable const&, wfl::function_symbol_table*) const
in gui2::text_shape::draw(surface&, SDL_Renderer*, wfl::map_formula_callable&)
```

The call_stack_manager class is a wrapper for src/function/formula.cpp's `static std::deque<std::string> call_stack`, I think the problem is two threads accessing the static deque object simultaneously. The crash happens during call_stack_manager::~call_stack_manager()'s call to call_stack.pop_back(). The deque appears to be corrupt, and has -1 elements at the time of the crash.

Replicated on a local build (current master) on Debian Linux, built with GCC-10. I can't replicate the crash while running under the debugger, I'm having to use core dumps for analysis. The call_stack_manager class also has a rule-of-three violation, but adding `= delete;` statements to it doesn't avoid the crash.
