### ISSUE TITLE
[message][option]labels either don't wrap or are cut horizontally

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5633]
### Game and System Information
1.15.11+dev, 64b672f9ef4d07e143d884531493d6d6cab022c2
Local Linux build running on Debian with X11, build with GCC-10

### Describe the bug
The `[message]` in TSG S05 that selects the elven or bandit branches is shown with the main text word-wrapped to a narrow column. The `[option]` labels are given a single line each, and shown truncated.

### To Reproduce
On TSG S05, trigger Urza's dialogue and see the options presented to the player.

![wesnoth_urza_clipped](https://user-images.githubusercontent.com/101462/112073977-81337600-8b75-11eb-93f8-6d97bfb4f1ef.png)

**Comment by Pentarctagon** [comment]
Does this all [message][option]s or just this specific one?

**Comment by shikadiqueen** [comment]
There is a scrollbar. It's not ideal but it is a thing.

Also, this is what I get:

![image](https://user-images.githubusercontent.com/489895/112095860-0752bb00-8b7c-11eb-9056-7b14b3219f50.png)

**Comment by stevecotton** [comment]
Appears to affect all of them (tested on DW S03, grabbing the trident), and be reproducible at least as far back as 1.15.7. With DW on 1.15.7 I do at least get a scrollbar between the `[option]` and the OK button.

Please would you check if it's reproducible for you? As it hadn't been reported until now I guess this must be something local with my setup, but it's also happening with a fresh user config and user data dir, and is also reproducible on my non-HDPI monitor.

**Comment by stevecotton** [comment]
This isn't a regression, it's a duplicate of #1915.
