### ISSUE TITLE
Setting units movement points to 0 is no longer possible

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5638]
### Game and System Information
 - 1.15.11
 - Steam
 - Windows 10

### Describe the bug
In 1.15.10 it was possible to set units movement points to 0 using this code:
```
                [modify_unit]
                    [filter]
                        id = Yura
                    [/filter]
                    [effect]
                        apply_to = movement
                        set = 0
                    [/effect]
                [/modify_unit]
```
But in 1.15.11 that is no longer possible and units movement points will be set to 1 instead. It would be nice to be able to set them to 0 again.

**Comment by CelticMinstrel** [comment]
I don't think this was possible in 1.14.x was it?

**Comment by stevecotton** [comment]
@Hejnewar, I can't reproduce this, it works for me on both 1.14.16 and 1.15.11.

PR #5434 will add this to the unit tests - that PR has two commits, cherry-pick the first one to get a test that works on both 1.14 and 1.15.

**Comment by Hejnewar** [comment]
@stevecotton Actually, now that you mentioned it I went to check what is happening exactly. Here is video of this. It turns out to be much more complicated than I thought.

At least now I know why after setting it to -1 it still did change to 1 from time to time. 

[Reload bug - movement](https://www.youtube.com/watch?v=zRfeUVLc3IE)

**Comment by stevecotton** [comment]
Thanks for the details - looks like it's a typo in 66a282a96be288a284d12a71625868cee5b2dc6b, which changed this:
```
	max_hit_points_ = std::max(1, cfg["max_hitpoints"].to_int(max_hit_points_));
	max_movement_ = std::max(0, cfg["max_moves"].to_int(max_movement_));
	max_experience_ = std::max(1, cfg["max_experience"].to_int(max_experience_));
```
to this:
```
	if(const config::attribute_value* v = cfg.get("max_hitpoints")) {
		set_max_hitpoints(std::max(1, v->to_int(max_hit_points_)));
	}
	if(const config::attribute_value* v = cfg.get("max_moves")) {
		set_total_movement(std::max(1, v->to_int(max_movement_)));
	}
	if(const config::attribute_value* v = cfg.get("max_experience")) {
		set_max_experience(std::max(1, v->to_int(max_experience_)));
	}
```
