### ISSUE TITLE
Add a "Teleport Unit (Debug!)" option to debug menu

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#5649]
### Game and System Information
I'm on 1.14.16 downloaded from Steam for Mac.

### Describe the desired feature
Currently when enabling debug mode, it adds options to create units, kill units, and change unit side to the contextual menu (see screenshot below). It would be helpful if there were also an option to teleport an existing unit somewhere else to that menu in debug mode, to make it easier to test certain events that depend upon certain units triggering them. Using `unit moves=100` isn't as practical because there might be enemy units in the way, or impassable terrain. 

### Screenshots
<img width="259" alt="Screen Shot 2021-03-31 at 02 04 51" src="https://user-images.githubusercontent.com/1388660/113097943-c8e57d80-91c5-11eb-8c13-29e1b19e39b3.png">

**Comment by sevu** [comment]
Want to note that allowing to set x or y `unit x=10` might make sense, but it is not supported.

(The GUI Debug Tools Add-on allows something like that though)

**Comment by Wedge009** [comment]
I use that same GUI Debug Tools add-on to just increase the movement points to 100, which is more than enough for most scenarios. I haven't found any standard campaign scenario where impassable terrain is an issue - and if it was, I wonder how the player would be expected to complete such a scenario in the first place.

**Comment by cooljeanius** [comment]
> I use that same GUI Debug Tools add-on to just increase the movement points to 100, which is more than enough for most scenarios. I haven't found any standard campaign scenario where impassable terrain is an issue - and if it was, I wonder how the player would be expected to complete such a scenario in the first place.

OK I guess I should have said "and" instead of "or" between "enemy units in the way" and "impassable terrain". Usually when impassable terrain is an issue, it's because there's a bottleneck where enemy units are blocking it off, so the player is expected to complete the scenario by just defeating the enemy in normal gameplay, but sometimes I'm too lazy to do that and would prefer to teleport around the bottleneck.

**Comment by Wedge009** [comment]
I normally find if you're going through a debug run that you can traverse the scenario before enemies may take hold of a choke point, and even if they are already enemies around (eg in a shroud or fog situation), you can always debug-kill them. But yes, I'll grant that it's a lot quicker just to bypass them altogether. (:

**Comment by cooljeanius** [comment]
> > I use that same GUI Debug Tools add-on to just increase the movement points to 100, which is more than enough for most scenarios. I haven't found any standard campaign scenario where impassable terrain is an issue - and if it was, I wonder how the player would be expected to complete such a scenario in the first place.
> 
> OK I guess I should have said "and" instead of "or" between "enemy units in the way" and "impassable terrain". Usually when impassable terrain is an issue, it's because there's a bottleneck where enemy units are blocking it off, so the player is expected to complete the scenario by just defeating the enemy in normal gameplay, but sometimes I'm too lazy to do that and would prefer to teleport around the bottleneck.

Another example of impassable terrain being an issue: scenario 10 ("Subterranean Crossfire") of Dawn of Thunder, where you need to use the Dwarvish Miner's "dig" ability to create a path to your exit point.

**Comment by cooljeanius** [comment]
Hm I guess now that I know there's a `wesnoth.units.teleport` function in Lua (thanks to [e613010](https://github.com/wesnoth/wesnoth/commit/e613010b4b473b3ae81febc3f58257b9a16d077f)), I guess it should be pretty simple to just implement this as a wrapper around that...

**Comment by ProditorMagnus** [comment]
Teleport as API action has been available for many years, having new name for it in Lua should not affect whether it is considered good first issue.

**Comment by CelticMinstrel** [comment]
> Using `unit moves=100` isn't as practical because there might be enemy units in the way, or impassable terrain.

I think if there is impassable terrain you should in theory be able to get through it with something like `:unit move=10000`, though I haven't tried it.

That said, adding teleport as an available debug action would definitely be more convenient. It would also be rather complicated, which means it's probably easier to implement in the engine than as an add-on.

**Comment by ProditorMagnus** [comment]
Select event to know who to move. Menu location for where to move. That seems addon suitable implementation.

**Comment by CelticMinstrel** [comment]
Might not even need the select event, as long as right-clicking doesn't deselect the unit before calling the menu callback…

**Comment by TheHitsy** [comment]
Is the solution of using teleport_unit_between and a couple of help functions to simulate a teleport through move acceptable or should it be solved in any other way? And is there any good documentation if that is the case for how to solve the issue?

**Comment by soliton-** [comment]
There is not really going to be anyone that knows exactly how to do it or have documentation on it.
You'd have to implement it to know or write that documentation.

In the end the selected unit just needs to end up on some other hex that can be chosen some way.

**Comment by daniel-santos** [comment]
Ooh, I just saw this commit. Thank you!
