### ISSUE TITLE
WC: Error flood after being made playable after recent commits. (Feedback report)

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5650]
### Game and System Information
 - What version of the game are you running?
 - Battle for Wesnoth v1.15.11+dev (1af920669c6-Modified) x86_64

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 Github
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
Msys2   v1.15.11+dev (1af920669c6-Modified) x86_64
 - What OS are you running?
 Windows 10

### Describe the bug
After recent commits, World Conquest was made playable again, so I gave it a test run. I got a lot of deprecated Lua and WML messages most of the time and sometimes a few bugs popped up.
Additionally, when progressing from the first scenario, you are shown the faction/side/team selection interface (the one where you pick factions, color, team, gold and income, etc). This allows you to edit the gold and income, as well as the team of the enemy AI sides...and is...a mega cheat itself. I got through most scenarios just by setting the enemy gold and income to 0 and -2 respectively, and also putting them against each other for a FFA.

### Expected behavior
No "Invalid WML found" or "Lua Error" should be appearing

### Screenshots
![Screenshot 2021-03-31 203619](https://user-images.githubusercontent.com/5283677/113179871-e3753080-9271-11eb-94cc-e7daef871b09.png)
![Screenshot 2021-03-31 223055](https://user-images.githubusercontent.com/5283677/113179876-e53ef400-9271-11eb-8d9c-1d79cd2fc4e9.png)

### Additional context
```lua
20210331 21:50:38 info deprecation: wesnoth.extract_unit has been deprecated indefinitely.
   (Note: You should use wesnoth.units.extract instead in new code)
Invalid WML found:    (Note: You should use wesnoth.units.extract instead in new code)
Invalid WML found: wesnoth.extract_unit has been deprecated indefinitely.
libpng warning: iCCP: known incorrect sRGB profile
20210331 22:03:30 info deprecation: map:get_tiles_radius has been deprecated indefinitely.
  The filter is now the last parameter, instead of the radius (Note: You should use map:find_in_radius instead in new code)
20210331 22:03:30 info deprecation: map:get_locations has been deprecated indefinitely.
   (Note: You should use map:find instead in new code)
20210331 22:03:30 info deprecation: wml.parsed has been deprecated indefinitely.
  Since vconfigs are not supported outside of the game kernel, this function is redundant and will be removed from plugin and map generation contexts. It will continue to work in the game kernel. (Note: You should use (no replacement) instead in new code)
20210331 22:08:18 info deprecation: wesnoth.add_modification has been deprecated indefinitely.
   (Note: You should use wesnoth.units.add_modification instead in new code)
Invalid WML found:    (Note: You should use map:find instead in new code)
Invalid WML found:    (Note: You should use wesnoth.units.add_modification instead in new code)
Invalid WML found:   Since vconfigs are not supported outside of the game kernel, this function is redundant and will be removed from plugin and map generation contexts. It will continue to work in the game kernel. (Note: You should use (no replacement) instead in new code)
Invalid WML found:   The filter is now the last parameter, instead of the radius (Note: You should use map:find_in_radius instead in new code)
Invalid WML found: map:get_locations has been deprecated indefinitely.
Invalid WML found: map:get_tiles_radius has been deprecated indefinitely.
Invalid WML found: wesnoth.add_modification has been deprecated indefinitely.
Invalid WML found: wml.parsed has been deprecated indefinitely.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
20210331 22:10:33 info deprecation: helper.child_range has been deprecated indefinitely.
   (Note: You should use wml.child_range instead in new code)
Invalid WML found:    (Note: You should use wml.child_range instead in new code)
Invalid WML found: helper.child_range has been deprecated indefinitely.
campaigns/World_Conquest/lua/map/main.lua:43: bad argument #-1 to 'dofile' (file not found)	stack traceback:
	[string ""]:7: in function <[string ""]:7>
	[C]: in field 'dofile'
	campaigns/World_Conquest/lua/map/main.lua:43: in function '.wc_ii_generate_scenario'
	(...tail calls...)
	[C]: in function '.xpcall'
	[string ""]:7: in main chunk
nil
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
20210331 22:30:37 error general: Map generator error: Error when running lua_map_generator create_scenario.
The generator was: World Conquest 1p
bad return value:
  expected a config (table), found a nil
```

**Comment by Pentarctagon** [comment]
The warnings showing up in-game now is likely a result of 7050eaf03e4a1045f569c1f21def1f816550344e, for reference.

**Comment by CelticMinstrel** [comment]
Deprecations are minor, so I won't comment on them. Of course they do need to be fixed on master.

About the actual error, from a quick look at the code it would seem that it's a result of having an invalid player count or number of scenarios (WC can't handle more than 3 players or a sequence of more than 5 characters). How you'd end up with an invalid value there though, I'm not sure.

**Comment by knyghtmare** [comment]
![Screenshot 2021-04-02 062130](https://user-images.githubusercontent.com/5283677/113429964-29113500-93fb-11eb-978e-0716300ce2ec.png)

This side/team selection interface pops up after winning any scenario. As shown, the team aren't locked as well as the gold and income. This allows me to "cheat" my way through WC (even at the highest difficulty). I got passed it easily by setting my enemies against each other and minimizing their gold and income.
