### ISSUE TITLE
Dark Forecast Has Become Impossible on Default (1.15.11)

### ISSUE THREAD

**Issue by anakayub** [wesnoth/wesnoth#5651]
### Game and System Information
 - What version of the game are you running? 1.15.11
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) Website
 - If you're using a custom build, what compiler did you use, and what commit did you build at? Default compile
 - What OS are you running? MacOS Big Sur

### Describe the desired feature
In the current version, it seems that Dark Forecast has become impossible to beat in its default settings. The spawns are now too frequent; usually the next spawn occurs before finishing off the current one. Spawns are also too powerful (as they appear before any proper recovery/healing); their value usually approaches/equals the value of the players' units. To add insult to injury, they appear usually right before their optimal time of day, making their counterattacks devastating. I suggest some form of adjustment somewhere to make beating this mainline scenario...possible. I've tried over the past 3 weeks and this was the only time I reached turn 30 with this exact faction combo.

### Screenshots
If applicable, add screenshots or mockups to help explain your request.

<img width="1792" alt="Screenshot 2021-03-31 at 10 57 31 PM" src="https://user-images.githubusercontent.com/42091252/113183729-ecbcc800-9286-11eb-8d5d-1fc3404dc846.png">
The value of the spawn here probably even exceeds the units I have left

[https://replays.wesnoth.org/1.15/2021/03/31/2p__Dark_Forecast_(Survival)_Turn_30_(35).bz2](url)
My last attempt, played on the MP server.

**Comment by knyghtmare** [comment]
I didn't win but I didn't died either. It's rather...unwinnable.
[2p — Dark Forecast (Survival)-Auto-Save59.gz](https://github.com/wesnoth/wesnoth/files/6238747/2p.Dark.Forecast.Survival.-Auto-Save59.gz)
[2p — Dark Forecast (Survival)-Auto-Save58.gz](https://github.com/wesnoth/wesnoth/files/6238748/2p.Dark.Forecast.Survival.-Auto-Save58.gz)
![Screenshot 2021-04-01 002808](https://user-images.githubusercontent.com/5283677/113194199-acf3e180-9282-11eb-891c-dd6186467007.png)
![Screenshot 2021-04-01 002837](https://user-images.githubusercontent.com/5283677/113194205-afeed200-9282-11eb-8c96-88aca7a9c5f1.png)
![Screenshot 2021-04-01 003058](https://user-images.githubusercontent.com/5283677/113194211-b1b89580-9282-11eb-9704-ca7e808267c0.png)
![Screenshot 2021-04-01 003532](https://user-images.githubusercontent.com/5283677/113194214-b2512c00-9282-11eb-85f6-4098244ba71b.png)
![Screenshot 2021-04-01 003746](https://user-images.githubusercontent.com/5283677/113194216-b2e9c280-9282-11eb-81f0-9b153c3efe62.png)

**Comment by anakayub** [comment]
It seems to be beatable by others playing just 1 side instead of 2 sides. I think the combination of bigger spawns and greater economic impact from upkeep for 2 sides makes the difficulty not twice harder but more.

One can compare the difference in spawns here where I played mentally carefree yet reached further than I ever have playing 2 sides on the dev version
[2p — Dark Forecast (Survival)-Auto-Save39.gz](https://github.com/wesnoth/wesnoth/files/6240254/2p.Dark.Forecast.Survival.-Auto-Save39.gz)

Again one can reference my replay here on the stable version where I did win, where the difficulty seems easier:
https://youtu.be/W_IuYHTAaqs

**Comment by knyghtmare** [comment]
After checking the code, this scenario has a very....very abusable hack in the code.
Reproduce the hacked form:
1. Start game.
2. Set Side 3 to empty
3. Play as side 4.
4. **No weather change happens.** 
5. Enjoy without being impeded by unfavorable terrain.

**Comment by anakayub** [comment]
The drastic change in difficulty by playing 1 side only is apparent when I no longer try playing with 2 sides.

Now I can reach the final bosses at least. Maybe there's something wrong with how the scenario now handles 2 players in dev vs stable

Game originally played on the dev server

<img width="1792" alt="Screenshot 2021-04-02 at 1 16 14 AM" src="https://user-images.githubusercontent.com/42091252/113330842-c748c080-9351-11eb-8a00-45cc83ed8413.png">
[2p — Dark Forecast (Survival) Turn 48.gz](https://github.com/wesnoth/wesnoth/files/6245318/2p.Dark.Forecast.Survival.Turn.48.gz)

**Comment by sevu** [comment]
> It seems to be beatable by others playing just 1 side instead of 2 sides. I think the combination of bigger spawns and greater economic impact from upkeep for 2 sides makes the difficulty not twice harder but more.

- [ ] One could increase the village_gold and village_income by 1 to effectively double the villages, when 2 players are on the field.

Besides this issue, there's these two things:
- [ ] The final_spawn() function has no adjustments for one player mode. That's what will be spawned over the crouse of 4 turns (x,y-coordinates and units): https://github.com/wesnoth/wesnoth/blob/master/data/multiplayer/scenarios/2p_Dark_Forecast.lua#L362-L367
- [ ] The time over event should be removed
- One way would be to increase the turn limit, and let the players loose if he didn't kill all units until then. Maybe the preferable option.
- Or one could make it like one wins after killing the 4 bosses. But that includes situations where one barely killed them and would loose.
-  Or one could let the player win if he reaches the turn limit,  but that includes hiding with a unit somewhere.

**Comment by knyghtmare** [comment]
@sevu For my PR, I was doing the restoration of the GPV (_gold per village_) for the two player mode.
As in, for 1 player mode, it stays at 1 GPV (since it's manageable), while the two player mode will have 2 GPV, so that they can stand some chance at getting to the final wave at turn 41.
From my playtesting, the 2 player mode suffers from not having enough gold for loss recuperation. I lose an unit but no gold to replace him/her. This problem does not exist in 1 player mode. I think the first option would be best.
