### ISSUE TITLE
Lua API `wesnoth.set_terrain` is deprecated yet the replacement is not documented

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#5659]
For `master` branch of wesnoth, `wesnoth.get_terrain` is deprecated. Attempts to use it will cause a warning that suggests using `wesnoth.current.map[loc]` instead. However, this alternative does not seem to be documented: https://wiki.wesnoth.org/LuaAPI

Deprecation itself is defined in lua/core/map.lua:202
```
	wesnoth.get_terrain = wesnoth.deprecate_api('wesnoth.get_terrain', 'wesnoth.current.map[loc]', 1, nil, function(x, y)
		local loc = wesnoth.map.read_location(x, y)
		if loc == nil then error('get_terrain: expected location') end
		return wesnoth.current.map[loc]
	end)
```

Can somebody please confirm it's a bug? I'm a bit doubting here, but I think it is one, because the behavior is "unexpected" and an add-on developer wouldn't know what to do about it (especially if they're new to wesnoth).

**Comment by Pentarctagon** [comment]
IMO part of deprecating an API should be documenting its replacement.  Assigning @CelticMinstrel since he implemented the new API and deprecated the old one.

**Comment by vgaming** [comment]
@CelticMinstrel oh BTW, I noticed that the deprecation itself is kinda wrong, it ignores the optional `[layer]`, `[replace_if_failed]` parameters I think. Old code that used to work for wesnoth-1.14 `wesnoth.set_terrain(x, y, "H")` is not working on `master` and requires explicitly specifying `wesnoth.set_terrain(x, y, "H", "both")` I think

Can you please confirm? I tried to read the code but I'm not good at e.g. `local new_ter, mode, replace_if_failed = select(n + 1, ...)`

**Comment by CelticMinstrel** [comment]
There _is_ [a page](https://wiki.wesnoth.org/LuaAPI/wesnoth/map) documenting the map module. It's something of a work in progress, though, and it looks like it's not linked from the main LuaAPI page.

As for whether the setter deprecation is correct, I think I recall noticing an error and fixing it. Are you testing on master or latest release? The line you quote there (with `select()`) just means that those three arguments follow the location, which may be either the first argument or the first two arguments. In other words, it supports both `set_terrain({x, y}, new_ter, mode, replace_if_failed)` and `set_terrain(x, y, new_ter, mode, replace_if_failed)`.

**Comment by vgaming** [comment]
@CelticMinstrel thanks for your answer! WRT wesnoth version, I'm guilty here indeed, I'm not testing the latest. Will re-build and report later, assume it's fixed for now.

> and it looks like it's not linked from the main LuaAPI page

Oh, I indeed was searching everything from the LuaAPI "root page". Didn't find it from there. This is the thing left before closing the issue then?

**Comment by vgaming** [comment]
UPD: confirming that wesnoth.set_terrain works correctly on latest master -- thanks! (and sorry for testing on somewhat outdated `master` branch)

**Comment by CelticMinstrel** [comment]
Yeah, linking it from the main LuaAPI page and also from LuaAPI/wesnoth. I think there's some functions still not documented on LuaAPI/wesnoth/map as well, and it's possible the get/set terrain functionality is among those since it's not part of the `wesnoth.map` module but rather a feature of the `wesnoth.current.map` metatable… did you check if it's documented there?

**Comment by vgaming** [comment]
@CelticMinstrel I looked but I couldn't find `wesnoth.current` itself

**Comment by CelticMinstrel** [comment]
Well, `wesnoth.current` is documented somewhere under WML but hasn't been moved into LuaAPI yet; `wesnoth.current.map` is new though.

**Comment by CelticMinstrel** [comment]
It's now documented [here](https://wiki.wesnoth.org/LuaAPI/types/map#Terrain) so I'll close this. You can also find documentation of [wesnoth.current](https://wiki.wesnoth.org/LuaAPI/wesnoth#wesnoth.current) on the LuaAPI pages now, including the new `map` and `schedule` members.
