### ISSUE TITLE
[Units] Sand Scuttler (Giant Scorpion variation) has no variation name specified. Shows "empty" link in Help.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5676]
### Game and System Information
 - What version of the game are you running?
 - 1.15.11+dev
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 - Github
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - Battle for Wesnoth v1.15.11+dev (289ac354a07-Modified) x86_64
 - What OS are you running?
 - Windows 10

### Describe the bug
In the unit file, the variation "Sand Scuttler" has a name specified but the `variation_name=` is absent...this causes an empty/broken link in the Units help section.

### Screenshot of Bug
![Screenshot 2021-04-06 184749](https://user-images.githubusercontent.com/5283677/113713662-6c281c80-9709-11eb-83f8-33bede8e2324.png)

### Expected behavior
Should look like this:

![Screenshot 2021-04-06 185245](https://user-images.githubusercontent.com/5283677/113714173-eeb0dc00-9709-11eb-8ff3-df74fce7c1a4.png)
![Screenshot 2021-04-06 185221](https://user-images.githubusercontent.com/5283677/113714452-38012b80-970a-11eb-8cde-32360884b354.png)

**Comment by doofus-01** [comment]
What's a "scuttler" variation mean?  And "scuttler" under the name "Sand Scuttler" looks strange.  Making this a separate unit might be better.

**Comment by knyghtmare** [comment]
> What's a "scuttler" variation mean? And "scuttler" under the name "Sand Scuttler" looks strange. Making this a separate unit might be better.

I agree with you, given that #5691 suggests that the Sand Scuttler is supposed to be some sort of elemental type unit with the Burrows ability as stated by the current description. I mean the choice is either updating the descriptions or making it a separate unit.
