### ISSUE TITLE
UtBS: 'dehydrated' icon is displayed in the right panel even in the next scenario

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5687]
### Game and System Information
 - What version of the game are you running?
The Battle for Wesnoth version 1.15.11+dev (0575bde-Clean) x86_64
Running on Freedesktop.org 20.08.7 (Flatpak runtime) x86_64

### Describe the bug
'dehydrated' icon is incorrectly displayed in the right panel even if a unit is not dehydrated

### To Reproduce
1. Start UtBS campaign
2. Skip/win the first scenario
3. In the second scenario dehydrate one of the units then skip/win the scenario while the unit is dehydrated
4. In the third scenario check status of the unit in the right panel. The unit will remain marked as dehydrated during the whole campaign. 

### Expected behavior
'dehydrated' icon should not be displayed in the right panel if a unit is not dehydrated

### Screenshots
(Third scenario) In the right panel a unit is incorrectly marked as dehydrated:
![image](https://user-images.githubusercontent.com/3605541/113942951-07042200-9802-11eb-91b2-5e0a01c04f71.png)

**Comment by grz0** [comment]
The issue seems to be caused by dehydrated status, it is not cleared after the end of a scenario.
I added the below code to `utils/dehydration-utils.cfg` and it seems that it fixes the issue:
```
    [event]
        name="victory"
        
        [modify_unit]
            [filter]
                status=dehydrated
            [/filter]
                    
            [status]
                dehydrated=no
            [/status]
        [/modify_unit]
    [/event]
```
Probably the same should be done to `dehydration_slowed_by_healer` status.

A similar issue exist for units with dazed status, it is not cleared in a next scenario.

**Comment by Pentarctagon** [comment]
See also #6045 for another report of this.

**Comment by Wedge009** [comment]
If that code resolves the situation, can you submit it as a PR? Or are you concerned about the `dehydration_slowed_by_healer` status?
