### ISSUE TITLE
Plan Unit Advance modification causes incorrect XP colour in Advance Unit dialogue

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5707]
### Game and System Information
 - What version of the game are you running?
The Battle for Wesnoth version 1.15.11+dev (c72ea20c-Clean) x86_64
Running on Freedesktop.org 20.08.8 (Flatpak runtime) x86_64

### Describe the bug
XP colour for AMLA advancements is light blue, it should be purple as in other UI elements.

### Screenshots
![image](https://user-images.githubusercontent.com/3605541/114798700-3ed90f80-9d96-11eb-8269-f14068d66e4f.png)

**Comment by knyghtmare** [comment]
This does not appear in my case.

![Screenshot 2021-04-15 070509](https://user-images.githubusercontent.com/5283677/114799218-eff0a180-9db8-11eb-8fca-b97dfc1d7e11.png)

**Comment by grz0** [comment]
I found this issue while playing '6p - Team Survival' map, and I reproduced it on '2p - Weldyn Channel'. I was playing on the Default era and with the default map settings.

Full info:
The Battle for Wesnoth version 1.15.11+dev (c72ea20c-Clean) x86_64
Running on Freedesktop.org 20.08.8 (Flatpak runtime) x86_64
Distribution channel: Default

Game paths
==========

Data dir:        /app/share/wesnoth
User config dir: /home/USER/.var/app/org.wesnoth.Wesnoth/config/wesnoth
User data dir:   /home/USER/.var/app/org.wesnoth.Wesnoth/data/wesnoth/1.15
Saves dir:       /home/USER/.var/app/org.wesnoth.Wesnoth/data/wesnoth/1.15/saves
Add-ons dir:     /home/USER/.var/app/org.wesnoth.Wesnoth/data/wesnoth/1.15/data/add-ons
Cache dir:       /home/USER/.var/app/org.wesnoth.Wesnoth/cache/wesnoth

Libraries
=========

Boost:             1.66
Lua:               5.4.2
OpenSSL/libcrypto: 1.1.1g (runtime 1.1.1k)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.45.5 (runtime 1.45.5)
SDL:               2.0.12 (runtime 2.0.12)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.4 (runtime 2.0.4)

Features
========

Lua console completion:       yes
D-Bus notifications back end: yes

Current video settings
======================

SDL video drivers:       [x11] wayland dummy
Window size:             1920x1015
Screen refresh rate:     60
Screen dots per inch:    102.453781x102.741570
Screen dpi scale factor: 1.067227x1.070225

Current audio settings
======================

Audio not initialized.

Installed add-ons
=================

After_the_Storm:           0.10.12
AtS_Music:                 0.3.2
IftU_Music:                0.3.2
Invasion_from_the_Unknown: 2.1.10

**Comment by grz0** [comment]
I'm closing the issue because I can't it reproduce anymore. I retested on the latest master and it works as expected. In the meantime cleared wesnoth cache. I don't know what fixed this issue.

**Comment by grz0** [comment]
I'm reopening the issue because I noticed the same issue with the latest build
![image](https://user-images.githubusercontent.com/3605541/175752233-9ba45410-fff9-42c1-84b5-eacaabd9be39.png)

**Comment by knyghtmare** [comment]
I encountered it myself while playing Dark Forecast today. Latest build too.

**Comment by Wedge009** [comment]
Is it related to MP? I cannot see this in SP and I just tested 1.16.5 release and 1.17.6+dev (6eb2246eff4). I cannot confirm this.

**Comment by grz0** [comment]
> Is it related to MP? I cannot see this in SP and I just tested 1.16.5 release and 1.17.6+dev ([6eb2246](https://github.com/wesnoth/wesnoth/commit/6eb2246eff4afdcec538701e3cb73d281b550a4e)). I cannot confirm this.

I was playing with AI on '6p - Team Survival' and '2p - Weldyn Channel'.

**Comment by Wedge009** [comment]
I ran a local MP game with those two scenarios, still seeing XP rendered in purple to indicate no further advancement for those L3 units. There must be something else triggering it.

**Comment by grz0** [comment]
I spent some time debugging this issue, and I think I know what is causing it.
A new unit passed to GUI dialog has advances_to_ the same as the unit before advancing.

I checked what is happening in `advance_to()` funtion and  `advances_to_`  during `advance_to()` was empyt until call to `apply_modifications`
```
(gdb) bt
#0  unit::add_modification(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, config const&, bool)
    (this=this@entry=0x55920abe5540, mod_type="object", mod=..., no_add=no_add@entry=true) at src/units/unit.cpp:2326
#1  0x00005591f33abf3e in unit::apply_modifications() (this=this@entry=0x55920abe5540) at src/units/unit.cpp:2435
#2  0x00005591f33ac430 in unit::advance_to(unit_type const&, bool) (this=0x55920abe5540, u_type=..., use_traits=use_traits@entry=false)
    at src/units/unit.cpp:979
#3  0x00005591f3422916 in get_advanced_unit(unit const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    (u=..., advance_to="Lancer") at src/actions/advancement.cpp:323
```
`advances_to_`  was modified after this line in `add_modification()`:

`description_component = resources::lua_kernel->apply_effect(apply_to, *this, effect, true);`

```
(gdb) p mod.values_
$265 = std::map with 2 elements = {
  ["pickadvance"] = {
    value_ = std::variant<std::monostate, config_attribute_value::true_false, config_attribute_value::yes_no, int, unsigned long long, double, std::string, t_string> [index 2] = {{
        value_ = true
      }}
  },
  ["take_only_once"] = {
    value_ = std::variant<std::monostate, config_attribute_value::true_false, config_attribute_value::yes_no, int, unsigned long long, double, std::string, t_string> [index 2] = {{
        value_ = false
      }}
  }
}
(gdb) p effect.values_
$266 = std::map with 3 elements = {
  ["apply_to"] = {
    value_ = std::variant<std::monostate, config_attribute_value::true_false, config_attribute_value::yes_no, int, unsigned long long, double, std::string, t_string> [index 6] = {"new_advancement"}
  },
  ["replace"] = {
    value_ = std::variant<std::monostate, config_attribute_value::true_false, config_attribute_value::yes_no, int, unsigned long long, double, std::string, t_string> [index 2] = {{
        value_ = true
      }}
  },
  ["types"] = {
    value_ = std::variant<std::monostate, config_attribute_value::true_false, config_attribute_value::yes_no, int, unsigned long long, double, std::string, t_string> [index 6] = {"Knight,Lancer"}
  }
}
```
This comes from LUA function `set_advances` in build-in pick_advance addon.

**Comment by grz0** [comment]
I confirmed this by removing Plan Advance Unit LUA code from a save file on which I was reproducing this issue. Now XP has the correct color.

**Comment by Wedge009** [comment]
Who maintains the Plan Advance Unit add-on? Is it a case that the add-on is doing something incorrect from Wesnoth's perspective, or is the problem specifically with Wesnoth?

I don't see any Plan Advance Unit add-on (yet?) for 1.18. Is this still an issue?

**Comment by soliton-** [comment]
It's a modification in mainline.

**Comment by knyghtmare** [comment]
> Is this still an issue?

Yes.
