### ISSUE TITLE
Maintenance Tool GUI.pyw app freezes/becomes unresponsive after Python 3.9.2 update.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5719]
### Game and System Information
 - What version of the game are you running?
 - Battle for Wesnoth v1.15.11+dev (ad1c42ca8f0-Modified) x86_64
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 - Github
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - Battle for Wesnoth v1.15.11+dev (ad1c42ca8f0-Modified) x86_64
 - What OS are you running?
 - Windows 10

### Describe the bug
This GUI.pyw tool stops responding after producing the pot file.

### To Reproduce
Run wmlxgettext on an add-on, I guess?

### Expected behavior
No freezes and the app is responsive?

### Screenshots:
![Screenshot 2021-04-18 213209](https://user-images.githubusercontent.com/5283677/115151938-ebfea100-a090-11eb-8475-1409285c5cd3.png)

### Additional Context:
```swift
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\msys64\home\Asus\wesnoth\data\tools\GUI.pyw", line 1375, in on_run_wmlxgettext
    dialog=Popup(self.parent,"wmlxgettext",wmlxgettext_thread)
  File "C:\msys64\home\Asus\wesnoth\data\tools\GUI.pyw", line 299, in __init__
    self.check_thread_alive()
  File "C:\msys64\home\Asus\wesnoth\data\tools\GUI.pyw", line 305, in check_thread_alive
    if self.thread.isAlive():
AttributeError: 'ToolThread' object has no attribute 'isAlive'
```

When I used Python 3.8.8, I used to get a deprecation warning, but this is not there anymore, and I get this.

**Comment by Elvish-Hunter** [comment]
The fix here is simple: in Python 3.9, `Thread.isAlive()` has been renamed as `Thread.is_alive()`; now the real issue is keeping compatibility with Python <= 3.8 (there are a few ways to do so). Assigning to myself.
