### ISSUE TITLE
Multiplayer turns over advantage doesn't use team colors

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5722]
### Game and System Information
Local builds of 1.14.16 and 1.15.12

### Describe the bug
The multiplayer "turns over advantage" screen is supposed to team-color the sides' names. Instead it shows them all in white.

There's a hardcoded list of the RGB values for colors "1", "2", "3", ..., "9"; however the Lua code is receiving the RGB colors "red", "blue", etc.

### To Reproduce
1. Start a local multiplayer
2. In the create game screen, set the turn limit to 1 turn
3. Start the game
4. End turn for each side
5. A dialog pops up when the turns run out

### Screenshots
This is what it's meant to look like. If you try to reproduce it, you'll find that all the names are white instead.

The teams here are all using their default colors, which have names that are also recognised by Pango's rendering code. Notably Ravana's color-changer mod is not activated, which is why I'm creating a bug report instead of opening a PR with a simple fix.

![wesnoth_turns_over_with_color](https://user-images.githubusercontent.com/101462/115434279-ceecde00-a208-11eb-980c-9086ca86ddbb.png)

### Hardcoded list
https://github.com/wesnoth/wesnoth/blob/1b0d63f3057a268b94bfee0fb383a609a8e7a50b/data/multiplayer/eras.lua#L51-L60

**Comment by knyghtmare** [comment]
It must be mentioned that this issue has deeper things involved

https://github.com/wesnoth/wesnoth/blob/1b0d63f3057a268b94bfee0fb383a609a8e7a50b/data/core/team-colors.cfg#L240-L242

**Comment by CelticMinstrel** [comment]
Side note: we should use `gui.show_popup` for that summary instead of `gui.show_narration` / `[message]`.
