### ISSUE TITLE
Tag the prereleases as -dev

### ISSUE THREAD

**Issue by romulasry** [wesnoth/wesnoth#5724]
Or else this doesn't pick them up as prereleases: https://release-monitoring.org/project/8621/ thanks for your work

**Comment by romulasry** [comment]
It should be set as prerelease.

**Comment by Pentarctagon** [comment]
What does this mean specifically?

**Comment by romulasry** [comment]
https://www.reddit.com/r/github/comments/4mwwjp/what_qualifies_as_a_prerelease/

**Comment by Pentarctagon** [comment]
We don't put releases on github though.

**Comment by stevecotton** [comment]
https://en.wikipedia.org/wiki/Software_versioning#Odd-numbered_versions_for_development_releases

The version numbering scheme that we're using is probably getting less common, but it's a known one. GNOME have stopped using it for their headline version number, but applications within GNOME have used it, and many will still be using it. My feeling is that it's something for that release tracker (Anitya) to support, and that we should close the issue on Wesnoth.

Having looked for a feature-request on Anitya's bug database, I see you've already logged it, thanks.
https://github.com/fedora-infra/anitya/issues/1088
