### ISSUE TITLE
Bump the minimum SDL version for 1.15.x

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#5735]
As per discussion in #5734  - Wesnoth requires a pretty low version of SDL in comparison to required Boost and compilers versions.
Bumping the minimum SDL version would allow removing some workarounds for SDL bugs from the code.

**Comment by rubyFeedback** [comment]
One day I also hope to be able to use a modern version of boost,
rather than have to use an outdated backup copy to please
wesnoth. ;-)

**Comment by soliton-** [comment]
If there are issues with a modern boost version you should report them.

This is about the minimum version of a dependency which means the lowest supported version not the highest.
