### ISSUE TITLE
Unit checksum code needlessly checks weapon special names, which can cause OOS

### ISSUE THREAD

**Issue by ForestDragon-wesnoth** [wesnoth/wesnoth#5743]
### Game and System Information
 - Wesnoth 1.14.16, Steam, Windows 10

### Describe the bug
the unit checksum code, when calculating weapon specials, considers weapon special names part of the checksum. therefore, if the name is changed locally, it causes OOS

### Expected behavior
Since weapon special names are a text string that has no actual impact on gameplay, it should not be counted in the checksum in my opinion, as it causes problems for people using my macro-based translation

### Proposed fix:
replace the following code in units.cpp:
https://github.com/wesnoth/wesnoth/blob/fa720141587392938ce65fcaae1827b467bc397c/src/units/unit.cpp#L2678-L2682
with this:
```C++
		for(const config& spec : att.child_range("specials")) {
			config& child_spec = child.add_child("specials", spec);

			child_spec.recursive_clear_value("description");
			child_spec.recursive_clear_value("description_inactive");
			child_spec.recursive_clear_value("name");
			child_spec.recursive_clear_value("name_inactive");
		}
```

**Comment by soliton-** [comment]
Suggestion from ForestDragon-wesnoth to reproduce the issue:

1. install Great Steppe Era, and Great Steppe Era Russian Translation (the way the translation is done with macros can cause changed checksum)
2. play a match with GSE (specifics don't matter, as long as you have a save file with the translated macros) and save a replay
3. uninstall the translation add-on
4. reboot the game
5. load replay
