### ISSUE TITLE
Map editor categories

### ISSUE THREAD

**Issue by rmj555** [wesnoth/wesnoth#5750]
1.15.12

There is no category for castles/fortresses; one must go to All to locate them.

Why have a category Fall; there are only five? tiles.

**Comment by knyghtmare** [comment]
You don't really seem to explore the editor much.
![image](https://user-images.githubusercontent.com/5283677/116575032-1aea0200-a930-11eb-96cd-3d100b32db2a.png)

**Comment by CelticMinstrel** [comment]
There _are_ some terrains that aren't in a category, though. The one I remember is tracks but maybe there's more.

**Comment by rmj555** [comment]
![Wes_editor](https://user-images.githubusercontent.com/76490126/116720068-a1363080-a990-11eb-94a1-9fec7a60ecb1.png)

**Comment by CelticMinstrel** [comment]
Maybe the problem is that the categories aren't lexicographically ordered? Also, did you miss that you can scroll down?

**Comment by rmj555** [comment]
Thank you. My vision is not that good, and I didn't see the scroll.

To whosoever is in charge:  Increase the contrast!

**Comment by Pentarctagon** [comment]
It sounds like this can be closed?

**Comment by Wedge009** [comment]
It's an unfortunate choice of default colours that the scroll bar is a bit hard to see in this case. But on my large window I don't have a scroll bar anyway. Closing as resolved, no response since May anyway.
