### ISSUE TITLE
Units that are half covered in fog / shroud no longer trigger sighted events

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5758]
### Game and System Information
 - 1,15,12
 - Steam
 - Windows 10

### Describe the bug
Units that are half covered in fog / shroud no longer trigger _sighted_ events. 
![u1](https://user-images.githubusercontent.com/41817546/116894164-0c526200-ac32-11eb-8e13-d6dd73410ade.JPG)

### Expected behavior
Units half covered in fog / shroud should trigger _sighted_ events, there is even in game mention that unit has been sighted but event doesn't trigger until unit is fully seen.

**Comment by stevecotton** [comment]
Do you know when this was last working correctly, please? A known-working version would save debugging time.

**Comment by Hejnewar** [comment]
Sorry I dont know when was the last time it worked properly, but I know that in 1.15.9 it already didnt work.

**Comment by stevecotton** [comment]
I've done a major overhaul of the relevant unit test in PR #5760.

It seems to be working correctly - Alice on 7,3 with 6 vision points sees Bob when he moves to 14,3. The behavior is the same if I cherry-pick that test back to 1.14.

**Comment by Hejnewar** [comment]
So you are saying that it works for you? If so please download For the Lord! (avalivable on 1.15 add-on server) place any goblin on 29,28 and then move him to 9,38 wolf should be in sight but no event will trigger. There is one more thing, if you move any goblin on foot to 8,38 it will trigger sighted event despite the fact that no unit is in sight.

**Comment by stevecotton** [comment]
> if you move any goblin on foot to 8,38 it will trigger sighted event despite the fact that no unit is in sight.

That's correct, the sighted event with the wolves triggers when a wolf sees a goblin, not when a goblin sees a wolf.
The wolf on 3,41 can see 8,38. (Whether the wolf is quick on not doesn't affect this).

> place any goblin on 29,28 and then move him to 9,38 wolf should be in sight but no event will trigger

I'm assuming you meant starting at 9,28 and moving in a straight line to 9,38. During that journey, when should the sighting occur, and which pair of hexes would be involved? There doesn't seem to be any point where a wolf can see a goblin, much less a goblin see a wolf.

Moving by the least-mp path from 9,28 to 9,38 goes through 7,37, and the sighting occurs there.

**Comment by Hejnewar** [comment]
I guess I'm trully sorry then because its my mistake.
