### ISSUE TITLE
Conflicting zombie images between core and SotA

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5761]
Although the new walking corpse variations have been added to core, there are still similarly named images in SotA:

    data/core/images/units/undead/zombie-spider-die-3.png
    data/campaigns/Secrets_of_the_Ancients/images/units/undead/zombie-spider-die-3.png

Worse that that, those aren't the same image:

![core](https://github.com/wesnoth/wesnoth/raw/1.15.12/data/core/images/units/undead/zombie-spider-die-3.png)
![sota](https://github.com/wesnoth/wesnoth/raw/1.15.12/data/campaigns/Secrets_of_the_Ancients/images/units/undead/zombie-spider-die-3.png)

**Comment by Pentarctagon** [comment]
@nemaara and-or @doofus-01 which images should be kept?

**Comment by nemaara** [comment]
Definitely a question for doofus since he drew the core image.

**Comment by doofus-01** [comment]
The zombie spider images from SotA look like placeholders, they should have been removed, probably my fault.  I'll deal with this if no one else gets to it first.
