### ISSUE TITLE
Being able to use lawful_bonus in formulas

### ISSUE THREAD

**Issue by ForestDragon-wesnoth** [wesnoth/wesnoth#5776]
### Describe the desired feature
in filter/ability formulas, it would be nice to be able to use the lawful bonus of the tile the unit is standing on for calculations. This would allow much more customization with Tod based abilities, like a weapon having its own alignment, or a nightstalk ability that only triggers with -30% ToD

**Comment by CelticMinstrel** [comment]
With the above linked commit you will be able to use `tod_bonus(loc)` in a unit filter formula to get the current bonus applied to the unit's location. This accounts for inherent terrain lighting and illumination abilities in addition to the time of day. If you want to ignore illumination and only get the time of day bonus, there is also `base_tod_bonus(loc)`.

Does that satisfy your request?

**Comment by ForestDragon-wesnoth** [comment]
> Does that satisfy your request?
Yep, that's what I was looking for, thanks :)

**Comment by CelticMinstrel** [comment]
I want to support _actual_ custom alignments at some point in the future, too (like `alignment=some_custom_thing`), but that's probably going to be a lot more work.
