### ISSUE TITLE
Link to Freenode in the translatable strings

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5797]
I think there's only one, but if we change the IRC provider then there's an i18n'd string to update before the freeze:

https://github.com/wesnoth/wesnoth/blob/7e839a924ca9b798ed4deb92580c39e7febc06fe/doc/manual/manual.txt#L156-L159

There's a few other mentions of the IRC channel, but I think none of these are localised:

* CONTRIBUTING.md
* doc/doxygen/doxygen.cpp
* utils/travis-old/.travis.yml
* The comments at the start of many po/*/de.po files point to the German team's IRC channel

**Comment by Pentarctagon** [comment]
Also there's https://wiki.wesnoth.org/Support#IRC on the wiki.

**Comment by soliton-** [comment]
As much as possible should be updated to irc.wesnoth.org. Currently that still points to freenode but we can trivially change that.

**Comment by shikadiqueen** [comment]
I'm not closing this yet because it needs to be backported to 1.14. I'm also waiting on Libera.Chat's staff to sort out the lack of a webchat client to restore the webchat links.

**Comment by shikadiqueen** [comment]
Okay, turns out I missed @soliton-'s comment above about using the `irc.wesnoth.org` alias.

There's two problems with that idea however: one is the the webchat links (once it makes sense to have them back), and the other is the fact that it's usually more elegant to mention the network's name alongside the URL.

**Comment by soliton-** [comment]
Yes, it may not always be the best fit and I don't expect people to actually set that in their clients but it'd be a simple way to keep pointing to the right place where it makes sense.

It's not a big deal either way. Hopefully we're not going to be moving all the time...
