### ISSUE TITLE
Unmute doesn't work

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#5801]
### Game and System Information
 - 1.15.13 / 1.14.15
 - Steam / Source forge 
 - Windows 10

### Describe the bug
Unmute doesn't work.

### To Reproduce

1. Mute someone or everyone.
2. Try to unmute them.

### Expected behavior
Unmute unmutes chosen person or all observers. 

### Screenshots
![unmute](https://user-images.githubusercontent.com/41817546/119169434-4ad58280-ba62-11eb-91ce-e161b9eb4cc2.JPG)

**Comment by soliton-** [comment]
https://wiki.wesnoth.org/CommandMode

> unmute a specific observer. If no username is given everyone is unmuted. (**Doesn't effect the muteall setting.**)
