### ISSUE TITLE
Game sometimes crashes in add-ons with custom music

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#5807]
### Game and System Information
It's not determined which exact versions are affected, seems like any version. It's known for sure it affects 1.14.16 on Windows 10

### Describe the bug
The game crashes without any warning when the scenario with custom music started

Logs contain the only error message "warning engine: Invalid anchor!"

Observed in various addons like "A New Order" and supposedly several others

Example about "A New Order": https://forums.wesnoth.org/viewtopic.php?f=8&t=6486&start=525

**Comment by Discontinuum** [comment]
Another confirmed case: this save from the addon "Hordes of the Other World". It's the scenario where custom music appears. It crashes the game of those who experiences the same problem with "A New Order". For me personally "A New Order" as well as this save work fine 
[HotOW-Cave_of_the_Guardians.gz](https://github.com/wesnoth/wesnoth/files/6534411/HotOW-Cave_of_the_Guardians.gz)

**Comment by Wedge009** [comment]
The only instance of 'Invalid anchor!' that I can find is in the `terrain_builder` class. I assume there are no crashes when no custom music is included? Not saying I'm familiar with either the terrain or audio code, just trying to establish information for the others.

**Comment by Discontinuum** [comment]
Seems so, one of the scenarios susceptible to such a crash had an option to turn off custom music and without custom music no crashes observed

**Comment by Wedge009** [comment]
Unless there's something strange about the way Wesnoth handles custom music, it might be specific to the add-on.

**Comment by Discontinuum** [comment]
Was seen in many different addons

**Comment by Pentarctagon** [comment]
Unless a developer is able to reproduce it, this might need someone who is able to reproduce the issue to provide a backtrace.

**Comment by Wedge009** [comment]
For those able to replicate this, does it still happen in 1.18?

I'd be inclined to close this at some indeterminate time in the future, if there's no response or confirmation of this issue.
