### ISSUE TITLE
Add-ons manager: version selection drop down causes "Mandatory widget not defined" on small screens

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5810]
### Game and System Information
- 1.15.13 (both as-tagged and the latest 1.15.13+dev)
- Originally noticed by @Konrad22, I confirm that I can reproduce on a Local Linux build

### Describe the bug
If the add-ons manager is in small-screen mode, the `version_filter` drop-down's callback causes Wesnoth to return to the title screen, displaying a "Mandatory widget 'addons' hasn't been defined' error.

### To Reproduce

1. Start at the title screen
2. Make the window 800x600, so that the add-ons manager will use its small-screen layout
2. Open the add-ons manager
3. Click on the "Details" button at the bottom left. Which add-on is selected doesn't matter, even ones that only have one version can still trigger the bug.
4. Click on the version drop-down, and select a version.

**Comment by knyghtmare** [comment]
Connected to #3059 ?

**Comment by Konrad22** [comment]
Ohhhh. I didn't look far enough I guess. And yeah, that's the very same bug.
