### ISSUE TITLE
Created unit info causes crash

### ISSUE THREAD

**Issue by rmj555** [wesnoth/wesnoth#5813]
### Game and System Information
 - What version of the game are you running?
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - What OS are you running?

### To Reproduce

1. First..
2. Then...
3. Lastly...

### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

**Comment by Pentarctagon** [comment]
There's no information here?
