### ISSUE TITLE
ABILITY_TELEPORT causes lots of "terrain.owner is deprecated" warnings

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5816]
### Game and System Information
Current master, 1.15.13+dev 4ee5e41a2e5b454d718ffd4e666b3310fb049649

### Describe the bug
Units with {ABILITY_TELEPORT} cause lots of warnings about "terrain.owner" and "unit.side" being deprecated.

### To Reproduce
1. Have a Silver Mage on a map with villages
2. Get the game to calculate where they can move to

**Comment by stevecotton** [comment]
This triggers during the AI turn if the side's recruit list includes silver mages; they don't even need to be on the map.

**Comment by knyghtmare** [comment]
OH...this explains why I was bombarded by over 12k lines if "Invalid WML found" in WoF S5
[WoF-The Three Sisters.gz](https://github.com/wesnoth/wesnoth/files/6564584/WoF-The.Three.Sisters.gz)
![Screenshot 2021-05-29 000850](https://user-images.githubusercontent.com/5283677/120068584-36693980-c0a3-11eb-945d-dbc967c13cba.png)
[wesnoth-20210528-230410-16948.log](https://github.com/wesnoth/wesnoth/files/6564585/wesnoth-20210528-230410-16948.log)

**Comment by stevecotton** [comment]
The reproduction steps are short and quick. I'm disappointed that the issue was closed without checking that the issue was fixed, especially given how quick it was to test.

I think the only other cause is the other formula in `ABILITY_TELEPORT`, but the reason that I don't just change it and push the one-liner is that fixing an issue should include spending time testing.

**Comment by sigurdfdragon** [comment]
Can confirm that 04455c01b4649 didn't fix the issue

**Comment by newfrenchy83** [comment]
@CelticMinstrel has forget owner and side in [target]
