### ISSUE TITLE
Wesnoth 1.15.13 - can't pass tests and won't install due missing libwesnoth-widgets.so()(64bit)

### ISSUE THREAD

**Issue by AngryPenguinPL** [wesnoth/wesnoth#5817]
### Game and System Information
 - Wesnoth 1.15.13
 - Compiled from source
 - Compiled with LLVM/Clang 12
 - OS: OpenMandriva Cooker

### Describe the bug
As of Wesnoth 1.15.13, there is a problem. The game compiles correctly, but it does not pass the tests. Likewise, installation is impossible as RPM / DNF installer calls for missing component libwesnoth-widgets.so () (64bit) 

Full log from install:
```
Error: 
Problem: conflicting requests
- nothing provides libwesnoth-widgets.so()(64bit) needed by wesnoth-1.15.13-1.x86_64
```

Worth to add, previous version 1.15.12 still compiling and installing fine, without any issue. This install error is only on 1.15.13.

Full build log: https://file-store.openmandriva.org/api/v1/file_stores/f47febacdb7e3b056d1e1e20561a46fa7f35c3a6.log?show=true
Full testing log: https://file-store.openmandriva.org/api/v1/file_stores/fd3e4d9b07e4520902dc28b1318f048a1512ac27.log?show=true

### To Reproduce

1. Install OpenMandriva Cooker
2. Compile v1.15.13
3. Try install or run tests

**Comment by Pentarctagon** [comment]
The option was removed because it was no longer useful and, as the option itself stated, [installation using it is not supported](https://github.com/wesnoth/wesnoth/blob/7f1f1cecdfb11dba3bfddc07463f6fd7d1866e6e/CMakeLists.txt#L158).
