### ISSUE TITLE
AI lua [goal] syntax unclear

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#5832]
### Game and System Information
The Battle for Wesnoth version 1.15.13+dev (7e15e6d1f5b-Modified) x86_64
Running on openSUSE Leap 15.2 x86_64
Distribution channel: Default

### Describe the bug
use of [ai]...[goal]...code= << etc. causes validation errors
```
Validating data/_main.cfg against schema /home/wesnoth-CI/data/schema/game_config.cfg
Error (strict mode, strict_level = 0): wesnoth reported on channel error validation
20210601 03:09:12 error validation: Invalid key 'code=' in tag [goal]
at campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg:105
    included from campaigns/Sceptre_of_Fire/_main.cfg:125
    included from data/_main.cfg:38
validation failed
Skipping NORMAL validation
Skipping HARD validation
Sceptre_of_Fire validation complete!  Success: No
```
https://github.com/wesnoth/wesnoth/pull/5822#issuecomment-851790207

I think I followed what's in the wiki, but it's hard to tell if it is working as intended,  Something needs correction, maybe just the wiki, maybe just the schema, maybe something else.  

`src/ai/composite/goal.*pp` is over my head.

**Comment by CelticMinstrel** [comment]
Your goal usage appears to be correct, so this is most likely a schema bug.

**Comment by doofus-01** [comment]
This has been fixed
