### ISSUE TITLE
Lua mapgen uses wrong wesnoth.random / mathx.random

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5846]
### Game and System Information
Local builds of current 1.15.13+dev (957496560b4b9eb8fe7d5e41db334a9f3435e7ea)

### Describe the bug
The mapgen lua kernel provides a different implementation of `wesnoth.random` than the game lua kernel. I haven't looked into the history of why, but whatever it is was important enough that there's commit specifically to ensure the right one is used (52534550217947982249c3bf4dc42603266da658).

The Lua reorg has moved lua_kernel_base's `wesnoth.random` to `mathx.random`, without any changes to the mapgen lua kernel; including not updating the comments about mapgen needing to override the base function. In the reorg, `data/lua/cave_map_generator.lua` was changed to calling the non-mapgen version; I'm logging the bug because I think that was a search-and-replace unaware that there were two different functions called `wesnoth.random`.

### To Reproduce

1. Put breakpoints on both `intf_random` functions.
2. Load HttT's Sceptre of Fire scenario
3. Watch which function gets hit

### Expected behavior
I don't know what the behavior change is, would be interesting to know if it causes OOS in multiplayer.

**Comment by CelticMinstrel** [comment]
I think my expectation would be that the mapgen Lua kernel now replaces mathx.random with its custom function.

> I don't know what the behavior change is, would be interesting to know if it causes OOS in multiplayer.

I suspect it's not possible for this (or any mapgen code) to produce an out-of-sync error.
