### ISSUE TITLE
the arch package has still python2 as a dependecy

### ISSUE THREAD

**Issue by Axeltherabbit** [wesnoth/wesnoth#5850]
not much to say about it:
`:: removing python2 breaks dependency 'python2' required by wesnoth
`

**Comment by soliton-** [comment]
And what is requiring python2 according to the packaging?

**Comment by Axeltherabbit** [comment]
> And what is requiring python2 according to the packaging?

not sure, I found this thread https://www.spinics.net/lists/arch-general/msg47746.html

**Comment by soliton-** [comment]
What files are python2? Are you talking about version 1.14?

**Comment by Axeltherabbit** [comment]
```
axel@xyz [~] $ wesnoth --version
Battle for Wesnoth v1.14.16
Started on Wed Jun 16 14:28:36 2021

Battle for Wesnoth 1.14.16

Library versions:
Boost:             1.75
OpenSSL/libcrypto: 1.1.1j (runtime 1.1.1k)
Cairo:             1.17.4 (runtime 1.17.4)
Pango:             1.48.3 (runtime 1.48.5)
SDL:               2.0.14 (runtime 2.0.14)
SDL_image:         2.0.5  (runtime 2.0.5)
SDL_mixer:         2.0.4  (runtime 2.0.4)
SDL_ttf:           2.0.15 (runtime 2.0.15)

Optional features:
JPEG screenshots:               yes
Lua console completion:         yes
Legacy bidirectional rendering: yes
D-Bus notifications back end:   yes
axel@xyz [~] $ grep  "python2" /usr/share/wesnoth/data/tools/*.py
/usr/share/wesnoth/data/tools/expand-terrain-macros.py:1:#!/usr/bin/env python2
/usr/share/wesnoth/data/tools/scoutDefault.py:1:#!/usr/bin/env python2
```

**Comment by soliton-** [comment]
Ok, so wesnoth 1.14 tools still require python 2 and that's not going to change in a stable version. For the development version everything was already moved to python 3.

Maybe arch also has the dev version packaged? Otherwise it's presumably going to be this way until next stable (1.16).

Btw those python tools are not actually required to run wesnoth.

**Comment by Pentarctagon** [comment]
Is there anything that needs to be done here then?

**Comment by Axeltherabbit** [comment]
@soliton- ok, thanks
