### ISSUE TITLE
Frost stoat description is inaccurate

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#5853]
The frost stoat description says "Frost Stoats are a devious rodent" which is scientifically inaccurate. Stoats are mustelids, not rodents. If this were some completely made-up animal I wouldn't mind that much, but since stoats exist in the real world, too, I think it makes sense to keep facts about them as close to their real-world counterparts as possible, unless there is a good reason for diverging from reality. Like, if someone wants to say stoats in Wesnoth are actually rodents, then fine, just redo their artwork to make them look more rodent-like in that case. I think it would be easier just to change the text from "rodent" to "mustelid" though.

cc @doofus-01

**Comment by doofus-01** [comment]
That description can certainly be changed.  I'm not an expert on stoats and don't have any particular attachment to rodents, redoing the artwork for this would be silly.  But using the term 'mustelid' seems a bit too...  encyclopedic(?) - orcs etc. aren't referred to as 'hominids' for example.  Probably just rewording to avoid the subject is better.  Critters.

**Comment by CelticMinstrel** [comment]
Unfortunately there's no more-layman term that I can think of that applies here… so if you don't like "mustelid" I think the best option is to use something even more generic (which I think is what doofus suggested?) or rewrite it so that "devious" is a predicate adjective (eg, "Frost stoats are notoriously devious.")

**Comment by AI0867** [comment]
"Small carnivores"?

**Comment by cooljeanius** [comment]
yeah either "critters" or "carnivores" would be fine, IMO
