### ISSUE TITLE
Ophidian naga changes deadlines?

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#5854]
The ophidian branch of the dirkfang nagas currently use bows, but that is being changed and we need to get it all straightened out really soon.  This "bug report" is to keep that on the radar, and also make clear what needs to be done by when.

- sprites & animations -> placeholders by 6/20, final by 10/24
- portraits -> placeholders by 6/20, final by 10/24
- unit configuration -> basic agreement by 6/20, tweaks by 10/24
- descriptions -> by 6/20

Is that right, and am I forgetting something?
EDIT: #5855  is related to this

**Comment by Pentarctagon** [comment]
Descriptions and anything related to balancing definitely need to be settled by 6/20.  Portraits, sprites, and animations would probably be fine without needing to put placeholders in by 6/20 - "feature freeze" in my mind is more related to WML, lua, and anything else that would cause incompatibilities with previous versions of wesnoth if changed, whereas nothing is going to break if a portrait or an animation is added.

**Comment by doofus-01** [comment]
Thanks, I think I see now.

**Comment by Pentarctagon** [comment]
Also, to be clear as well, any new art will need to go only in the master branch starting with the RC1 release on 9/26, since release candidates are essentially "this is exactly what 1.16.0 will be unless we find a bug that needs to be fixed".

**Comment by doofus-01** [comment]
OK, thanks.  Not sure if LordBob knows that, I'll send him a reminder.
