### ISSUE TITLE
Black screen when viewing some cutscreens

### ISSUE THREAD

**Issue by roadrunner56** [wesnoth/wesnoth#5869]
### Game and System Information
 - v. 1.14.9
 - Downloaded from ubuntu packages (`sudo apt install wesnoth`)
 - Running on Kubuntu 20.04
 
### Describe the bug
Sometimes, when I play campaigns, the cutscenes will not fully show up. Instead, I get a portrait, some dialog, and a few sprites, as seen in the first picture. Then, when I click on anywhere on the screen, the screen turns completely black (second picture). I then have to wait a bit until the game moves on to the next scenario. I am unable to see most of the cutscenes, making it difficult to understand campaign stories. This has mostly happened on the THoT campaign.

### To Reproduce

1. First, start a new THoT campaign.
2. Then, finish the first scenario and go to the cutscene.
3. See the bug.

### Expected behavior
I expected the cutscene to display properly, with no blank spots.

### Screenshots
![Screenshot_20210618_123738](https://user-images.githubusercontent.com/65418682/122620253-b43fb580-d04f-11eb-94af-b8fc5480c05a.png)
Picture 1
![Screenshot_20210618_123746](https://user-images.githubusercontent.com/65418682/122620263-bace2d00-d04f-11eb-864d-a8245eb90389.png)
Picture 2

### Savefiles
[THoT-At the East Gate-Auto-Save16.gz](https://github.com/wesnoth/wesnoth/files/6679511/THoT-At.the.East.Gate-Auto-Save16.gz)

### Additional context
This game is fantastic, besides this bug. Apologies if this is a duplicate, but I was unable to find anything that was like my problem.

**Comment by Pentarctagon** [comment]
That is a known bug that is fixed in a later version of Wesnoth.  I would suggest using either Wesnoth's Flatpak, or downloading via Steam.
