### ISSUE TITLE
[campaign][world conquest][1.16/master] Enemy team is always one side and campaign runs on an infinite loop

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5896]
### Game and System Information
 - What version of the game are you running?
 - Battle for Wesnoth v1.15.14+dev (8679f0573f8-Modified) x86_64
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 - Github
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - msys2 Battle for Wesnoth v1.15.14+dev (8679f0573f8-Modified) x86_64
 - What OS are you running?
 - Windows 10

### Describe the bug
1. The same scenario repeats itself for an infinite loop.
2. It was always the WC start scenario and not the follow-ups

### To Reproduce
1. Enable WC and play it and win a few scenarios.
2. Notice the repeating start scenario.

### Expected behavior
Progression to scenarios with 1 more successive enemy side.

### Screenshots
![image](https://user-images.githubusercontent.com/5283677/123486745-741f9a80-d62e-11eb-8885-c30c4f8ecd89.png)

### Additional context
This might be a debug mode thing as I was playing for bug-tracking. Not sure though.

**Comment by CelticMinstrel** [comment]
I can't reproduce this because the game crashes when World Conquest advances to the next scenario… does anyone else get that?

**Comment by knyghtmare** [comment]
> I can't reproduce this because the game crashes when World Conquest advances to the next scenario… does anyone else get that?

instead of debug `:n`, you can debug `Shift+K` the leaders. I got advanced to like 8 scenarios that way.

**Comment by CelticMinstrel** [comment]
I tried that but it also crashed in the same way.

**Comment by knyghtmare** [comment]
This is the method I used:

1. Load WC campaign
2. Pick any faction
3. Start. `:debug` mode
4. debug kill  enemy leader and commanders if any.
5. get victory and end scenario
6. repeat

This went on for like 12 times or so when I noticed the loop and each scenario being the "starting" one.

**Comment by CelticMinstrel** [comment]
The only difference between that and what I did is that instead of using `:debug` I launched Wesnoth with the `--debug` command-line option. Also, you didn't mention your shroud/fog situation, but I had shroud enabled and just guessed where the enemies were (or maybe the debug menu gave away their locations).

**Comment by knyghtmare** [comment]
> but I had shroud enabled 

wait, how is this possible? world conquest has shroud disabled and fog enabled as default settings and this is locked. In my case, shroud is set to no and fog is set to yes.

**Comment by CelticMinstrel** [comment]
Sorry, you're right. It was fog, not shroud.

**Comment by knyghtmare** [comment]
Killing the leader and commander:
1. using the debug kill on the other keep hex
there is a follow up "rally to me" dialogue by the commander and gives away the location of the commander
2. using the debug kill on the commander's hex.

this was how I progressed while probing this bug.

**Comment by CelticMinstrel** [comment]
Yeah, that sounds about the same as what I did.

**Comment by knyghtmare** [comment]
Found it:
https://github.com/wesnoth/wesnoth/blob/80b3809b9b08d8e8a466b98bf15053af6965a4e9/data/campaigns/World_Conquest/lua/map/main.lua#L39

For some reason, this `scenario_num` is staying at `1` and this causes the infinite loop.

**Comment by CelticMinstrel** [comment]
This seems to suggest that `wml.variables` may be broken in the mapgen kernel? I'm not quite sure though…

**Comment by knyghtmare** [comment]
is there any reason(s) why the labels "Blocker: Point" and "Blocker: Stable" haven't been added to this issue? It's a dire issue, and renders WC non-advanceable after the first scenario.

**Comment by Pentarctagon** [comment]
It wouldn't be a point blocker given WC is currently disabled.

@knyghtmare what is the value of `settings.scenario_num` and `wml.variables.wc2_scenario`?

**Comment by knyghtmare** [comment]
> @knyghtmare what is the value of `settings.scenario_num` and `wml.variables.wc2_scenario`?

When i was debugging and playtesting through it, `scenario_num` stayed at `1`, while `wml.variables.wc2_scenario` incremented by 1 for each level.
`scenario_num` is supposed to take the value of `wml.variables.wc2_scenario` for each level after the first one, but for some reason it is not.

**Comment by Pentarctagon** [comment]
So for the first scenario:
* settings.scenario_num == 1
* wml.variables.wc2_scenario == 1

Then for the second scenario:
* settings.scenario_num == 1
* wml.variables.wc2_scenario == 2

?

**Comment by knyghtmare** [comment]
| Expected | Bugged | 
| ------------- | ------------- |
| Scenario 1 scenario_num == 1 &&  wml.variables.wc2_scenario == 1  |  Scenario 1 scenario_num == 1 &&  wml.variables.wc2_scenario == 1  |
|  Scenario 2 scenario_num == 2 &&  wml.variables.wc2_scenario == 2   |  Scenario 2 scenario_num == 1 &&  wml.variables.wc2_scenario == 2  |
|  Scenario 2 scenario_num == 3 &&  wml.variables.wc2_scenario == 3   |  Scenario 2 scenario_num == 1 &&  wml.variables.wc2_scenario == 3  |

**Comment by Pentarctagon** [comment]
Hm.  It looks like `settings.scenario_num` only comes from [settings_dialog.lua](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/World_Conquest/lua/map/settings/settings_dialog.lua), and that dialog (`wc2_debug_settings`) is only ever called from inside [this](https://github.com/wesnoth/wesnoth/blob/182c9119774895f3d4187043f06e1943959f7e46/data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg#L56-L72) `#ifdef EDITOR` block.

So the only time it would ever get set to something else that's *not* 1 would be when it's used to generate a random map in the map editor.  In which case the fact that it's not getting incremented when advancing to the next scenario is entirely expected.

So the correct code would probably be:
```
scenario_num = 1
if settings.scenario_num > 1 then
    scenario_num = settings.scenario_num
elseif wml.variables.wc2_scenario > 1
    scenario_num = wml.variables.wc2_scenario
end
```

**Comment by CelticMinstrel** [comment]
I think I would expect `settings.scenario_num` to be `nil` unless run in the map editor…

**Comment by Pentarctagon** [comment]
@knyghtmare Would you be able to check and see if the code I posted works?

**Comment by CelticMinstrel** [comment]
Wait, how exactly did you make that table? Did you use the gamestate inspector or add std_print calls to the map generator?

**Comment by knyghtmare** [comment]
> @knyghtmare Would you be able to check and see if the code I posted works?

![image](https://user-images.githubusercontent.com/5283677/124846796-67e6f600-dfbb-11eb-9c32-04ea9bb596c5.png)


> Wait, how exactly did you make that table? Did you use the gamestate inspector or did you add std_print calls to the map generator?

The gamestate inspector to check `scenario_num` and `wc2_scenario`

**Comment by CelticMinstrel** [comment]
The gamestate inspector may not be accurate in this case. The code that's broken runs in the map generation context, but the gamestate inspector runs in the game context. Even if the variable has the correct value in the latter, that doesn't mean it has the correct value in the former.

**Comment by Pentarctagon** [comment]
Using std_print(), both `settings.scenario_num` and `wml.variables.wc2_scenario` output nil.

**Comment by Pentarctagon** [comment]
@knyghtmare this is a relatively new bug, right?

**Comment by CelticMinstrel** [comment]
The obvious possible cause is when I enabled `wml.variables` for use in the mapgen kernel… reverting that might be a first try before doing a bisect. I don't see how it _could_ have caused it but maybe I missed something.

**Comment by knyghtmare** [comment]
> @knyghtmare this is a relatively new bug, right? Or at least I assume it hasn't been doing this the entire time it's been in mainline, in which case this is something that can be bisected.

Yes, this is the first time I am seeing the infinite loop in WC. In earlier versions like 1.15.13, it was fine.

**Comment by Pentarctagon** [comment]
Alright, should be pretty easy to bisect then, I'll try to get to it today sometime.

**Comment by Pentarctagon** [comment]
So yes, it broke between 1.15.12 and 1.15.13.  The code was changed between those releases from `wesnoth.get_variable("wc2_scenario")` to `wml.variables.wc2_scenario`.

**Comment by CelticMinstrel** [comment]
I meant reverting it as a test to see if the cause is _in_ that commit.

**Comment by Pentarctagon** [comment]
According to a full bisect, 1410b5cef9e3b7cc66a0e612fcf28ef736d17079 is the bad commit

**Comment by knyghtmare** [comment]
Battle for Wesnoth v1.15.14+dev (b05215d8aa6-Modified) x86_64

I am closing this since 35911a3 fixed it.

**Comment by CelticMinstrel** [comment]
Reopening because the fix hasn't been forward-ported to master yet.

**Comment by Pentarctagon** [comment]
It looks like this was forward ported, unless I'm mistaken?

**Comment by CelticMinstrel** [comment]
Looks like it.
