### ISSUE TITLE
Lua error in S3 of UtBS, Wesnoth version 1.15.14

### ISSUE THREAD

**Issue by ScarDre** [wesnoth/wesnoth#5897]
Wesnoth version: 1.15.14, Campaign version: mainline
Campaign: Under the Burning Suns
Scenario 3: A Stirring in the Night
Lua Error occurs at the start of turn 12, screenshot and replay attached
Scenario can still be finished, unsure if working as intended
![Screenshot_20](https://user-images.githubusercontent.com/57530238/123491780-d91bc600-d617-11eb-9f2f-b0d4f2cee3e4.png)
[UtBS-A Stirring in the Night replay 20210626-003958.gz](https://github.com/wesnoth/wesnoth/files/6719123/UtBS-A.Stirring.in.the.Night.replay.20210626-003958.gz)

**Comment by Pentarctagon** [comment]
@CelticMinstrel I'm guessing this is related to the lua API reorg?
