### ISSUE TITLE
SotA campaign, months in date as number...

### ISSUE THREAD

**Issue by arosella** [wesnoth/wesnoth#5898]
Since now we have names for all the months (wesnoth-help), we could use them, no ?

For examples, line 22 in wesnoth-sota/xxx.po state
**<i>From the Journal of Ardonna of Tarrynth</i>

9 XII, 22 YW:

**

could be rewritten as

9 Blackfire, 22 YW:

**Comment by Pentarctagon** [comment]
@nemaara Thoughts?

**Comment by nemaara** [comment]
Sure we can use them, but probably is a bit late to put them in 1.16.

**Comment by stevecotton** [comment]
It's a question that I've asked before, but what's the lore around the calendar? It seemed to be added with no notes about where and when in the timeline it appears, nor even which races use it. Assuming it's used by humans, with a history that spans around 1000 years including a forced migration and meeting new cultures, a calendar that keeps the same names over the entire timespan breaks the worldbuilding for me. #4822 suggests it's a part of the Iryda Canon storyline, and given @nemaara's refusal to write story-bible for that world I think there's logic-errors that need to be checked before using this calendar.

Specifically for Ardonna:

* She's got an unusual mindset, using a numerical style for her person journal feels right to me.
* The story is trying to tell the player how much time passed, and month numbers are easy to understand. How will a set of unfamiliar month names communicate that to the player?

**Comment by nemaara** [comment]
Well considering it more carefully I think you have a point, Ardonna's scientific style is better suited for numerical months rather than the stylized name months that Baldras uses. 

Your other points probably we can talk about elsewhere since it's not really related to this issue directly? Unless you want to discuss here.

**Comment by stevecotton** [comment]
> Your other points probably we can talk about elsewhere since it's not really related to this issue directly?

Very true, maybe in #4822?

**Comment by arosella** [comment]
Personally, agree about all. Steve, you scored a very good point, really appreciated. As per my concern i.e. italian translation, I'll keep the number in this campaign ... for the moment.

**Comment by Pentarctagon** [comment]
It sounds like this can be closed then?

**Comment by nemaara** [comment]
Closing for now, can be reopened later if needed.

**Comment by stevecotton** [comment]
At the moment Ras-Tabahn's solo scenarios don't include dates at all, they get straight into the action. Maybe the dialogue between the protagonists could gain months, with him or the kids using the months' names.
