### ISSUE TITLE
[world conquest] [feature request] [1.17+] Add [modification] for faction extra advancements

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5899]
### Describe the desired feature
Since WC is going to be using `[campaign]` from now, there should not be limitations to holding back advancements.

1. Drakes: Inferno Drake -> Armageddon Drake
2. Undead: Lich -> Ancient Lich and Revenant -> Death Knight
3. Knalgans: Dwarvish Fighter -> Dwarvish Runesmith and Dwarvish Runemaster -> Dwarvish Arcanister
4. Rebels: Wose -> Wose Shaman
5. Northerners: Troll Whelp -> Troll Shaman and Orcish Slayer -> Orcish Nightblade
6. Loyalists: N/A
7. Dunefolk: Dune Blademaster -> Dune Paragon

I am fine if they get added as "options"

**Comment by CelticMinstrel** [comment]
I don't think I'd recommend enabling the Ancient Lich but I have no objection to any of the others. However, I don't think there's a way to do it as an option. On the other hand, since this is probably for master only, perhaps such a way can be added.

Loyalists really don't have any? I thought the grand marshal was optional but I guess not.

**Comment by knyghtmare** [comment]
> I don't think I'd recommend enabling the Ancient Lich but I have no objection to any of the others. However, I don't think there's a way to do it as an option. On the other hand, since this is probably for master only, perhaps such a way can be added.

By "options" I meant as modification(s):
```
[modification]
   id=enable_armaggeddon_drake
   name= _ "Enable Armageddon Drake"
   type=mp # can be both
   require_modification=yes

  {ENABLE_ARMAGEDDON_DRAKE}
[/modification]
```

as for the Argument against Ancient Lich, a similar one can be added for Armageddon Drake and Dwarvish Arcanister. So,  not adding these 3 would be fine (but the modifications are optional...so maybe?)

> Loyalists really don't have any? I thought the grand marshal was optional but I guess not.

They already have Great Mage and Grand Marshal enabled by default.

**Comment by CelticMinstrel** [comment]
If that's what you want, then it's not specific to World Conquest. A modification can be used with any era, after all. Is that really what you're asking for though? You clearly tagged this as "[world conquest]" after all…

**Comment by knyghtmare** [comment]
> A modification can be used with any era, after all. Is that really what you're asking for though? You clearly tagged this as "[world conquest]" after all…

Might as well make it as a downloadable add-on that can enable the advancements for World Conquest then.

**Comment by CelticMinstrel** [comment]
In that case, I guess this should be closed?
