### ISSUE TITLE
[world conquest] [BUG] faction recruit list gets appended by recruits of another faction of the same era and Leader unit inherits heroic trait for each scenario and it stacks

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5900]
### Game and System Information
 - What version of the game are you running?
 - Battle for Wesnoth v1.15.14+dev (8679f0573f8-Modified) x86_64
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 - Github
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - Msys2
 - What OS are you running?
 - Windows 10

### Describe the bug
After each successive scenario, the recruit list is appended with the recruits of another faction of the same era. Additionally, the leader unit inherits "trait heroic" for every scenario, and the effects stack.

### Expected behavior
Recruit list stays the same. 

### Screenshots
Screenshot 1: My recruit list is of the Drakes faction from Default Era.
![SS1](https://user-images.githubusercontent.com/5283677/123548405-80b70680-d786-11eb-88b5-20f80482d013.png)
Screenshot 2: My recruit list is now Loyalists and Drakes.
![Screenshot 2021-06-27 202228](https://user-images.githubusercontent.com/5283677/123548402-7dbc1600-d786-11eb-9d7b-7d09ab48e190.png)
Screenshot 3: My recruit list has now Drakes, Northerners and Loyalists.
![SS3](https://user-images.githubusercontent.com/5283677/123548408-8280ca00-d786-11eb-9ebe-de9354b1f82f.png)
Screenshot 4: My recruit list has all factions except Knalgan Alliance.
![SS4](https://user-images.githubusercontent.com/5283677/123548719-d0e29880-d787-11eb-9a1c-97231702ea7e.png)
Screenshot 5: Leader unit inherits "heroic" trait for each scenario. It can be clearly seen how many times it has stacked.
![image](https://user-images.githubusercontent.com/5283677/123548749-f079c100-d787-11eb-9056-abe4ed93322d.png)

**Comment by CelticMinstrel** [comment]
Is this on master or on #5882?

**Comment by knyghtmare** [comment]
> Is this on master or on #5882? Does it happen if you select a specific faction in the setup screen or only if you select random faction?

I picked Drakes, not Random. It happens for #5882. It might also be related to #5896 (which seems to be present for both).

**Comment by knyghtmare** [comment]
can this be added to the https://github.com/wesnoth/wesnoth/projects/7 ?

**Comment by knyghtmare** [comment]
Battle for Wesnoth v1.15.14+dev (b05215d8aa6-Modified) x86_64

The "recruit list being appended..." part has been solved, however the leader being stacked on "heroic" trait still persists.
It's not a bad thing (but does make the player's leader Overpowered)

**Comment by knyghtmare** [comment]
Upon further investigation, this is happening because of the function `wc2_start` firing once every scenario (but it's supposed to fire only once for the first scenario). I noticed this since I kept getting 2 new heroes per scenario (I should be getting 2 first, and then 1 every follow-up)

**Comment by Pentarctagon** [comment]
It should be pretty easily fixable by checking against the scenario_num value, right?
