### ISSUE TITLE
[master/1.17/1.18] Please enable [micro_ai] support inside the [ai] tags.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#5910]
### Describe the desired feature
For smarter AI and more clean code, can the `[micro_ai]` tag be supported by the `[ai]` tags?

Here are some examples of what I mean:
```cs
[multiplayer_side]
    id=Rebels
    name= _"Rebels"
    image="units/elves-wood/captain.png"
    type=random
    leader=Elvish Captain,Elvish Hero,Elvish Ranger,Elvish Marksman,Elvish Druid,Elvish Sorceress,White Mage,Red Mage,Elder Wose
    random_leader=Elvish Captain,Elvish Hero,Elvish Ranger,Elvish Marksman,Elvish Druid,Elvish Sorceress,White Mage,Red Mage
    recruit=Elvish Fighter,Elvish Archer,Mage,Elvish Shaman,Elvish Scout,Wose,Merman Hunter
    terrain_liked=Ff, Fa, Ss, Ww

    [ai]
        recruitment_pattern=fighter,fighter,archer,archer,mixed fighter,healer,scout
       # Elvish Shaman can heal so this faction can benefit from this MAI
        [micro_ai]
            ai_type=healer_support
            action=add
            aggression=0.20
        [/micro_ai] 
    [/ai]
[/multiplayer_side]
```
```cs
[multiplayer_side]
    id=Dunefolk
    name= _"Dunefolk"
    image="units/dunefolk/rover/explorer.png"
    type=random
    leader=Dune Explorer,Dune Swordsman,Dune Spearguard,Dune Scorcher,Dune Apothecary
    random_leader=Dune Explorer,Dune Swordsman,Dune Spearguard,Dune Scorcher,Dune Apothecary
    recruit=Dune Rover,Dune Soldier,Dune Skirmisher,Dune Rider,Dune Herbalist,Dune Burner,Naga Dirkfang
    terrain_liked=Ss, Hh, Ha, Ww

    [ai]
        recruitment_pattern=fighter,fighter,mixed fighter,mixed fighter,archer,healer,scout
         [micro_ai]
            ai_type=healer_support
            action=add
            aggression=0.20
        [/micro_ai] 
        [micro_ai]
            ai_type=lurkers
            action=add

            [filter]
                type=Dune Skirmisher
            [/filter]
            [filter_location]
                terrain=D*
            [/filter_location]
            [filter_location_wander]
                terrain=D*,G*,H*,F*
            [/filter_location_wander]
        [/micro_ai]
    [/ai]
[/multiplayer_side]
```

**Comment by stevecotton** [comment]
Is the request to allow `[micro_ai]` inside `[side]` and `[multiplayer_side]`? What will take precedence in a scenario where the scenario author has also used Micro AIs?

I'm not seeing the connection to the `[ai]` tag, which according to the Wiki isn't supported in `[multiplayer_side]` either. (The Wiki says it is supported in `[era]` but then only refers to the AiWML page, and the latter doesn't say anything about `[era]`).

**Comment by knyghtmare** [comment]
> I'm not seeing the connection to the [ai] tag, which according to the Wiki isn't supported in [multiplayer_side]

If it's not supported, then why do the Default Era faction codes have it? Seems very confusing.

> Is the request to allow [micro_ai] inside [side] and [multiplayer_side]? 

More or less, yes. I want to add specific MAI behaviour for specific factions. Such as...Aragwaithi...They have a healer, so should get healer support MAI added to their `[multiplayer_side]` definition. They scouts which can use coward guardian MAI for disorientation. 

In campaigns, we UMC authors can select the factions for each side, and add MAI via ActionWML. However, in the case of MP eras/scenarios, this isn't possible unless with dirty hacks, so would be nice if a cleaner alternate was added in. Adding the `[micro_ai]` inside the faction/`[multiplayer_side]` would allow the MAI to be added in when the faction is played with/against. This is what I proposed in the code examples.

**Comment by CelticMinstrel** [comment]
> If it's not supported, then why do the Default Era faction codes have it? Seems very confusing.

It's either unsupported or undocumented, and I'm not quite sure which, but I _believe_ `[multiplayer_side]` is a special case of `[side]` and should thus support everything the latter does. The schema at least defines `[multiplayer_side]` as inheriting from a common abstract base with `[side]`.

**Comment by CelticMinstrel** [comment]
I've got this working in both `[side][ai]` and `[multiplayer_side][ai]`, and even in `[unit][ai]`. I don't plan to require an action key for these MicroAIs, since I think "add" would always be what you want. Does that sound reasonable?

**Comment by mattsc** [comment]
Sounds good to me.
