### ISSUE TITLE
Lua API deprecations

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#5919]
Using recent 1.16 beta 39401aca02a

Functioning code with `wesnoth.set_variable` and `wesnoth.get_variable` is broken with replacement `wml.variables`.

For whatever flaw is being fixed, the old method was readable.  If the new method is better, the deprecation warning should explain how to implement it.  This sort of thing is very discouraging for UMC authors.

**Comment by Pentarctagon** [comment]
For that example specifically, it should be equivalent:
* `wesnoth.get_variable(<var>)` -> `wml.variables[<var>]`
* `wesnoth.set_variable(<var>, <value>)` -> `wml.variables[<var>] = <value>`

@CelticMinstrel more generally I assume this mostly applies to your changes.

**Comment by CelticMinstrel** [comment]
So if I'm not mistaken, your complaint is that the deprecation message for get|set_variable doesn't sufficiently explain how to use `wml.variables`?

If there are any others where the deprecation message can be improved, please tell me.

**Comment by doofus-01** [comment]
Right.  Pentarctagon's explanation makes sense, I'll try it tomorrow and if there is anything else I'll mention it here.  Thanks.

**Comment by doofus-01** [comment]
It isn't clear how to deal with these gui deprecations  
 `info deprecation: wesnoth.set_dialog_active has been deprecated indefinitely.;  (Note: You should use <widget>.enabled instead in new code)`
Is this where the documentations is?  https://wiki.wesnoth.org/LuaAPI/gui

Some things like `wesnoth.set_dialog_markup` can be moved directly to the grid because you probably won't want to change it later.  But how does one reference the element you used to specify with `id`in `wesnoth.set_dialog_active(<val>, "id")`?

**Comment by CelticMinstrel** [comment]
That link is the documentation for the GUI module, but the documentation for the widget type is probably more useful to you here: https://wiki.wesnoth.org/LuaAPI/types/widget

That's linked from the page you posted, in the description of show_dialog.

Also relevant: https://wiki.wesnoth.org/LuaAPI/UpdatingFrom14#GUI2_API

To answer your specific question: pre_show and post_show now take a parameter, which is a widget representing the entire dialog. You can grab subwidgets from there by their ID. For example:

```lua
-- You can call the parameter whatever you want.
-- I called it self because it evokes the convention for member functions.
-- window and dialog are other popular names.
local function pre_show(self)
  self.id.enabled = false
end
gui.show_dialog(dialog_wml, pre_show)
```

**Comment by doofus-01** [comment]
Thanks, I think things are under control now.  The linked documentation and the error messages are clear as mud, but your explanation helps a lot and can be pasted on the wiki.

What also helped was ` lua/core/gui.lua`, where I see there is this `value_compat` which is the right answer for all things formerly `set/get_dialog_value`

**Comment by CelticMinstrel** [comment]
The `value_compat` key isn't intended to be used. You can feel free to use it anyway if you want, but it's possible it might be removed at some point in the future without warning. In other words, it's not documented for a reason. The `gui.widget.set_callback` function is also undocumented, for the same reason.

We can certainly mention `value_compat` on the wiki though, as long as it comes with some sort of "use at your own risk" disclaimer.

Do you have any suggestions for making the documentation and error messages less muddy?

**Comment by CelticMinstrel** [comment]
I also got started on an [example](https://wiki.wesnoth.org/LuaAPI/gui/example) for `gui.show_dialog`. It probably needs more work, but perhaps it's still helpful in its current form. It even works if you add the two files to the tutorial, load into it, and execute the following commands:

```
:lua wesnoth.dofile "character_select.lua"
:lua wesnoth.wml_actions.select_character{}
```

**Comment by doofus-01** [comment]
> Do you have any suggestions for making the documentation and error messages less muddy?

For things that aren't simple renaming, it might be too difficult to give a succinct, single line instruction.  Direction to the wiki or some README file could be an option.

> I also got started on an example for gui.show_dialog. It probably needs more work, but perhaps it's still helpful in its current form

Examples are great.  That one looks like it captures the key parts.

**Comment by CelticMinstrel** [comment]
> For things that aren't simple renaming, it might be too difficult to give a succinct, single line instruction.

You mean [here](https://wiki.wesnoth.org/LuaAPI/UpdatingFrom14)?

**Comment by doofus-01** [comment]
A link to that could help, yes, though the info on that page isn't that useful if you don't already know what needs to be done.  I added an example to the **wesnoth.set_dialog_active** entry, the sort of thing I would have found useful.

**Comment by CelticMinstrel** [comment]
Okay, I'll go ahead and add something like that for all the GUI stuff on that page, and maybe for a couple of others too.

**Comment by stevecotton** [comment]
> > I also got started on an example for gui.show_dialog. It probably needs more work, but perhaps it's still helpful in its current form
> 
> Examples are great. That one looks like it captures the key parts.

Sadly, that means you've just copied #5334 a.k.a. #5926 into your code.

**Comment by doofus-01** [comment]
I didn't copy anything.  But a small, non-trivial (meaning not foo.bar pseudo-code) example is still a good idea.  If the API is so unstable that there can't be any such thing, what hope is there for UMC or even mainline?

**Comment by CelticMinstrel** [comment]
The example could be updated to synchronize the result, yes. It certainly fits for what that example does; not all dialogs need to be synced, obviously.

**Comment by CelticMinstrel** [comment]
I updated the example to use sync.evaluate_single, and added a lot of examples to the update guide… is there anything else that needs work?

**Comment by doofus-01** [comment]
The update guide looks much better, thanks.  If there's something missing, it will just take time to find.

Maybe a link to it can be added in the release announcements for the 1.16 beta releases?  Or at least somewhere semi-prominent and outside of the wiki itself.

**Comment by CelticMinstrel** [comment]
Yeah, that sounds good. I think you'd have to bring it up with whoever posted the announcement though.

**Comment by Pentarctagon** [comment]
It's been my forum account posting all the announcements there, so no idea why there'd be any mystery about that.

**Comment by CelticMinstrel** [comment]
That's just a case of me not really paying attention to who the poster was.
