### ISSUE TITLE
Tutorial: replay shows character selection dialog

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#5926]
An issue similar to #5334 affects the tutorial (tested on the master branch's current commit). The character-selection dialog pops up during a replay, followed (if you select the other character) by an OOS.

From https://github.com/wesnoth/wesnoth/issues/5334#issuecomment-738131757 :

It's a problem with the campaign code, not the core `show_dialog`. Just added the bold bits to show_dialog's docs:

This function should be called in conjunction with `#wesnoth.synchronize_choice`, in order to ensure that only one client displays the dialog and that the other ones recover the same input values from this single client. **Even in single-player campaigns, synchronization is necessary otherwise the replay will be broken.**

**Comment by Pentarctagon** [comment]
Would it be possible/make sense to have this be synchronized by default?  It seems like a strange API that will by default break all replays that use it.

**Comment by CelticMinstrel** [comment]
There's no reason to synchronize a dialog that provides only information and no choice. Since `gui.show_dialog` can easily create either type of dialog, I think it makes sense to let the designer decide whether it needs to be synced. I don't think there's a way of automatically detecting whether a dialog offers a choice to the player.

**Comment by Pentarctagon** [comment]
Is there a downside to synchronizing by default?  Sure, synchronizing a dialog that has no choice on it does nothing, but it also prevents bugs like these from happening at all.

**Comment by stevecotton** [comment]
I'd be more tempted to write a nice wrapper than to try changing the behavior right now.

**Comment by stevecotton** [comment]
@CelticMinstrel as you've worked on the tutorial-based example, are you going to fix the tutorial and SotA too?

There are also dialogs that shouldn't be synchronized; admittedly these are likely to be rare enough that making them add a non-default option seems reasonable

 Ageless has a right-click option so that players can read the changelog when it's not their turn:
https://github.com/ProditorMagnus/Ageless-for-1-14/blob/master/data/era_events/unsynced_menu.cfg

I'm not planning much further development on SXC, but if I did then I'd be looking at making the initial turn's shopping event asynchronous, instead of needing each player to wait in turn.

**Comment by CelticMinstrel** [comment]
I can fix the tutorial. I'm not quite sure about SotA but I can look into that too.

**Comment by stevecotton** [comment]
> I can fix the tutorial. I'm not quite sure about SotA but I can look into that too.

Will you have time to do these, or should I take them?

**Comment by CelticMinstrel** [comment]
Alright, how about I take the tutorial and you look into SotA?

**Comment by stevecotton** [comment]
While I appreciate the tutorial being fixed, fixing the tutorial is an easy and quick-to-test preparation for fixing SotA. So if I have to take SotA, I may as well do the tutorial too.

**Comment by stevecotton** [comment]
> Would it be possible/make sense to have this be synchronized by default? It seems like a strange API that will by default break all replays that use it.

The answer turned out to be "only if it's a simple set of buttons, like the tutorial's dialog". The SotA fix is a counter-example.

**Comment by CelticMinstrel** [comment]
Yeah, basically as I said - only a simple choice dialog (buttons or listbox) could possibly be auto-synchronized without extra programmer input.

**Comment by stevecotton** [comment]
Fixed in PR #5994 and #5995.
