### ISSUE TITLE
HttT deprecation messages shown at the first scenario

### ISSUE THREAD

**Issue by PiotrMakarewicz** [wesnoth/wesnoth#5932]
### Game and System Information
1.15.14 on Windows 10

### Describe the bug
As soon as you begin the first scenario you see the errors shown at the screenshot

### To Reproduce
Start the HttT campaign

### Expected behavior
No error messages

### Screenshots
![image](https://user-images.githubusercontent.com/54529536/124653315-750dc300-de9d-11eb-9a3f-5beaf5d12439.png)

**Comment by knyghtmare** [comment]
@PiotrMakarewicz may I see your list of installed add-ons please? This is known issue I see as a discord moderator and it's caused one add-on that bleeds itself into mainline/other add-ons.

**Comment by PiotrMakarewicz** [comment]
Brave Wings, Eastern Europe at War, Invasion from the Unknown

**Comment by knyghtmare** [comment]
> Brave Wings, Eastern Europe at War, Invasion from the Unknown

uninstall Brave Wings or just deactivate it. That's the bleeder.

**Comment by PiotrMakarewicz** [comment]
Alright, so it has nothing to do with HttT. Still, is it a good idea that it shows errors unrelated to HttT within it?

**Comment by knyghtmare** [comment]
> Alright, so it has nothing to do with HttT. Still, is it a good idea that it shows errors unrelated to HttT within it?

It depends on the UMC campaign's _main.cfg file. If the add-on author does not include the campaign specify define, the scenario files, and stuff get loaded directly into mainline/core. So, it's not an issue with HttT.
