### ISSUE TITLE
Should Tips of the Day authors be only from mainline Wesnoth lore?

### ISSUE THREAD

**Issue by PiotrMakarewicz** [wesnoth/wesnoth#5933]
In 1.15 we have a Tip of the day by "Galun, the Flight Leader" - from Wings of Victory that has been added to mainline and then removed again and a tip by Turin from UMC Saving Elensefar.

Should we accept or remove these tips?

**Comment by nemaara** [comment]
These tips can be accepted. In Galun's case, the name should be updated if/when the new Winds of Fate is accepted.
