### ISSUE TITLE
my sound wont work

### ISSUE THREAD

**Issue by awesomecow329** [wesnoth/wesnoth#5934]
### Game and System Information
 - What version of the game are you running? most recent 1.15.14
 - Where did you download it from? Steam Mac
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - What OS are you running?

### Describe the bug
i had my sound off for a long time wanted to hear it again but my sound wont work
### To Reproduce

1. i turned off all my sounds
2. had them off for like 3 months
3. turned them back on and it wont work

### Expected behavior
 my sounds to turn on when i turned up the volume of it
### Screenshots
dont have screen shots and dont have a recording softwear that records sound
### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

**Comment by Pentarctagon** [comment]
I'm assuming that you're the same person as in https://forums.wesnoth.org/viewtopic.php?f=4&t=54566, however there you posted showing you're using Ubuntu, not macOS.  Which OS are you using?

**Comment by Wedge009** [comment]
Even if only as a starting point, can we confirm that audio is working for everything else on your system _except_ for Wesnoth? 'it wont work' isn't very descriptive...

**Comment by Wedge009** [comment]
No response, so closing.
