### ISSUE TITLE
[sound] reproduces twice unless repeat=0 is specified

### ISSUE THREAD

**Issue by Descacharrado** [wesnoth/wesnoth#5939]
### Game and System Information
 - What version of the game are you running? 1.15.14
 - Where did you download it from? Steam
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - What OS are you running? Windows 10 

### Describe the bug
I was coding in WML and found out that every sound was playing twice, so I had to add repeat=0 to all [sound] tags which should not happen according to https://wiki.wesnoth.org/InterfaceActionsWML#.5Bsound.5D

### To Reproduce

1. Code a simple map in wml and try adding a [sound]
2. Then, play the map.
3. Lastly I wanted to add that I am using git. Also, it is not a big deal to fix this problem (adding the repeat=0 solved the problem), but maybe the bug report helps?

### Expected behavior
I expected a [sound] tag only containing a name=sound.ogg to only be played once.

**Comment by Pentarctagon** [comment]
@CelticMinstrel This sounds familiar - has it already been fixed for 1.15.15/master?

**Comment by CelticMinstrel** [comment]
Fixed in 9f96c4662b5ebe4dd1471bbbec230fb863b2bc1b but it looks like I forgot to backport.

**Comment by Pentarctagon** [comment]
Fixed in c90f13cf77d79958e81530d821cc373717c13fad
