### ISSUE TITLE
wesnoth.scenario.mp_settings.active_mods returns nil in 1.15.14

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#5941]
### Game and System Information
 - 1.15.14

### Describe the bug
error scripting/lua: attempt to index a nil value (field 'active_mods')

### To Reproduce
Start multiplayer game and run wesnoth.scenario.mp_settings.active_mods:find("StealingWeaponsMode")

### Expected behavior
No error. Even if there are no modifications active.

**Comment by CelticMinstrel** [comment]
Looks like that was removed in 0efd35acbcba45724be4737073dc7f77480ec781. You can get the same info from `wesnoth.scenario.modifications` but maybe there should be some sort of fallback…

**Comment by ProditorMagnus** [comment]
I had actually created the functions needed for that already, `ORM.fun.table_contains(ORM.fun.map(function(mod) return mod.id end, wesnoth.scenario.modifications), "plan_unit_advance")`

**Comment by CelticMinstrel** [comment]
The map function already exists in Wesnoth by the way (`wesnoth.requre "functional"`).

**Comment by ProditorMagnus** [comment]
In that case map is not even needed, `f.find(wesnoth.scenario.modifications, function (e) return e.id=="plan_unit_advance" end)`
