### ISSUE TITLE
wesnoth.schedule.get_time_of_day fails

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#5944]
### Game and System Information
 - 1.15.14

### Describe the bug, To Reproduce
```
$ wesnoth.schedule.get_time_of_day(nil, 1)
Lua Error:
  When executing, Lua runtime error: [string "return wesnoth.schedule.get_time_of_day(nil, ..."]:1: bad argument #1 to 'get_time_of_day' (number expected, got nil)
stack traceback:
	[C]: in field 'get_time_of_day'
	[string "return wesnoth.schedule.get_time_of_day(nil, ..."]:1: in main chunk

```

### Expected behavior
> nil - returns the information for the global scenario schedule

### Additional context
Related to wesnoth.wml_actions.store_time_of_day

**Comment by CelticMinstrel** [comment]
I think I remember fixing this… let me see if I can find the commit.

**Comment by CelticMinstrel** [comment]
Looks like it was fixed in ca0534f150848dba44c3de391a3d78cd8fa82cad but I don't see a backport.

**Comment by ProditorMagnus** [comment]
I see, should be used as `wesnoth.schedule.get_time_of_day(nil, nil, 1)` instead.

**Comment by CelticMinstrel** [comment]
No, the usage is correct, but the implementation was wrong. Specifically, the implementation tried to load the turn number from the first argument instead of the second (but only after checking that the second argument was a number).

**Comment by ProditorMagnus** [comment]
Thanks for information. I updated workaround. My use cases do not need to explicitly pass current turn number.

**Comment by CelticMinstrel** [comment]
Yeah, that's one way. Of course, it's going to break any scenario that actually uses [store_time_of_day], isn't it?

**Comment by ProditorMagnus** [comment]
I got impression that no matter what, or if any, location you pass, turn number is ignored (but validated).

**Comment by CelticMinstrel** [comment]
No, the problem was that the turn number is validated but then it tried to use the location as the turn number, like (fake Lua code) `if type(turn) == 'number' then turn = location end`. It's a kind of bug that would be easy to spot in Lua (you used the wrong variable) but in C++ it's harder to spot (variables are represented as a numeric index).

**Comment by Pentarctagon** [comment]
Was this ever backported?

**Comment by CelticMinstrel** [comment]
Backported in b05215d8aa66b088b30f133ee341e0e76b42857e
