### ISSUE TITLE
wmlscope: ignore hidden files, e.g. git repository files

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#5949]
Running `wmlscope --collisions` on one of my addons results in messages like this:
```
%%
Possible duplicated files with MD5 hash 25231d1b1d78564a4affceec70297255
-> /Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/data/add-ons/A_New_Order/.git/logs/HEAD
-> /Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/data/add-ons/A_New_Order/.git/logs/refs/heads/master
%%
Possible duplicated files with MD5 hash 8b9e8221b2131ab39cfe3d910098e5c4
-> /Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/data/add-ons/A_New_Order/.git/refs/heads/master
-> /Users/ericgallager/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.14/data/add-ons/A_New_Order/.git/refs/remotes/origin/master
%%
```
This isn't very useful. On unix-like systems, files beginning with a dot are supposed to be hidden, and git repository files are controlled by git, and not something users are supposed to go mucking around with. IMO, `wmlscope` should be updated to ignore these.

**Comment by cooljeanius** [comment]
According to @Elvish-Hunter, `wmlscope` is already supposed to ignore .git directories, but for some reason it doesn't.

**Comment by soliton-** [comment]
Where is the code that should do that?

**Comment by cooljeanius** [comment]
Another example: those darn `.DS_Store` files on macOS.

> Where is the code that should do that?

I'm not sure exactly; just relaying what @Elvish-Hunter told me.
