### ISSUE TITLE
Game becomes unplayable when trying to view walking corpse description in SotA

### ISSUE THREAD

**Issue by Marken-Foo** [wesnoth/wesnoth#5953]
### Game and System Information
 - BfW 1.15.14, Steam
- Windows 10

### Describe the bug
When trying to view specific walking corpse type descriptions from the recruit menu, a lua error triggers and the game becomes unplayable thereafter, requiring BfW to restart.
By "unplayable" I mean units on the field cannot be selected, neither can units be recruited nor recalled. This persists through loading other turns, loading other scenarios, or trying to continue play from the middle of a replay; only restarting BfW fixes this.

### To Reproduce
1. Play Secrets of the Ancients to a point where you can recruit walking corpses (I was playing S3 Bandits; a scenario start is provided.)
2. Bring up the recruit menu (e.g. by ctrl-r)
3. Double click the "All Corpses" option to bring up the walking corpse recruit type menu.
4. Click the "i" button on the left pane to try and bring up the unit description.
5. A lua error triggers; when cleared the error log shows on the screen, and Wesnoth becomes unplayable until program restart.

### Expected behavior
The correct unit description should appear.

### Screenshots
![all-corpses](https://user-images.githubusercontent.com/41288521/125384074-f4822180-e3ca-11eb-86ba-07b3807b4eea.jpg)
![corpse-menu](https://user-images.githubusercontent.com/41288521/125384080-f5b34e80-e3ca-11eb-91be-f6f170e2e031.jpg)
![corpse-lua-error](https://user-images.githubusercontent.com/41288521/125384093-f946d580-e3ca-11eb-9ca6-e9d745d2dac1.jpg)
![corpse-lua-error-log](https://user-images.githubusercontent.com/41288521/125384097-fb109900-e3ca-11eb-9b22-00a19b751d9b.jpg)

### Savefiles
S3 Bandits start-of-save file for convenience:
[SotA-Bandits.gz](https://github.com/wesnoth/wesnoth/files/6805602/SotA-Bandits.gz)

### Additional context
Transcript of one ingame <Lua error> log for convenience (it's in the screenshot):
> lua/wml-tags.lua:756: attempt to call a nil value (field 'open_help')
> stack traceback:
>
>    lua/wml-tags.lua:756: in field '?'
>    lua/core/wml.lua:193: in function 'wml.fire'
>    lua/helper.lua:47: in field 'open_help'
>    .../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:36: in function <.../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:35>
>    [C]: in upvalue 'old_show_dialog'
>    lua/core/gui.lua:121: in function 'gui.show_dialog'
>    .../Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua:92: in main chunk
>    [C]: in field 'dofile'
>    [string "wesnoth.dofile 'campaigns/Secrets_of_the_Anci..."]:1: in local 'bytecode'
>    lua/wml-tags.lua:265: in local 'cmd'
>    lua/wml-utils.lua:144: in field 'handle_event_commands'
>    lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>

**Comment by Pentarctagon** [comment]
@CelticMinstrel were you still planning to look into this?

**Comment by CelticMinstrel** [comment]
Based on the stack trace, it's likely fixed by 02585e5aff61f4e78f72bc72a13bb3e2d9d3412b

**Comment by Pentarctagon** [comment]
Yep, this is fixed.
