### ISSUE TITLE
Wesnoth version components return wrong values

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#5955]
### Game and System Information
 - According to wesnoth.current_version, it is 2483150592.1.15

### Describe the bug, To Reproduce
```
$ wesnoth.current_version()[1]
2483150592
$ wesnoth.current_version()[2]
1
$ wesnoth.current_version()[3]
15
$ wesnoth.current_version()[4]

```

### Expected behavior
Return values 1, 15, 14.

**Comment by Pentarctagon** [comment]
@CelticMinstrel when you fix this, also add a unit test to check that `wesnoth.current_version()[1] == 1`.
