### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by arosella** [wesnoth/wesnoth#5962]
macchinista@htpc:**~**/wesnoth
$ lsb_release -ar
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
macchinista@htpc:**~**/wesnoth
$ uname -a
Linux htpc 5.10.0-5mx-amd64 #1 SMP Debian 5.10.26-1-mx19+1 (2021-04-01) x86_64 GNU/Linux
macchinista@htpc:**~**/wesnoth
$ git branch
_*_ 1.16
  master
macchinista@htpc:**~**/wesnoth
$ git pull
Already up to date.
macchinista@htpc:**~**/wesnoth
$ cd build
macchinista@htpc:**~**/wesnoth/build
$ cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=true
-- Found the following ICU libraries:
--   data (required)
--   i18n (required)
--   uc (required)
Removing -rdynamic flag from CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS
Removing -rdynamic flag from CMAKE_SHARED_LIBRARY_LINK_C_FLAGS
Removing -DNDEBUG flag from CMAKE_CXX_FLAGS_RELWITHDEBINFO
Removing -DNDEBUG flag from CMAKE_C_FLAGS_RELWITHDEBINFO
Removing -DNDEBUG flag from CMAKE_CXX_FLAGS_MINSIZEREL
Removing -DNDEBUG flag from CMAKE_C_FLAGS_MINSIZEREL
Replacing default flags used for Release build with   
added -flto=1 to Release build
Using GCC gold linker
Using gcc-ar and gcc-ranlib
Replacing flags used for Debug build  -DDEBUG -ggdb3  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/develop/wesnoth/build
macchinista@htpc:**~**/wesnoth/build
$ make
[  0%] mo-update: Done.
[ 72%] Built target mo-update
[ 72%] Built target wesnoth-revision_dummy
[ 72%] Built target wesnoth-revision
[ 73%] Built target wesnoth-common
[ 74%] Built target wesnothd
[ 76%] Built target wesnoth-widgets
[ 76%] Building CXX object src/CMakeFiles/wesnoth-client.dir/game_data.cpp.o
/home/macchinista/wesnoth/src/game_data.cpp: In constructor ‘game_data::game_data(const config&)’:
/home/macchinista/wesnoth/src/game_data.cpp:46:55: error: call of overloaded ‘t_string(const attribute_value&)’ is ambiguous
  , victory_music_(utils::split(level["victory_music"]))
                                                       ^
In file included from /home/macchinista/wesnoth/src/config_attribute_value.hpp:30,
                 from /home/macchinista/wesnoth/src/config.hpp:30,
                 from /home/macchinista/wesnoth/src/game_data.hpp:17,
                 from /home/macchinista/wesnoth/src/game_data.cpp:20:
/home/macchinista/wesnoth/src/tstring.hpp:147:2: note: candidate: ‘t_string::t_string(const string&)’
  t_string(const std::string &);
  ^~~~~~~~
/home/macchinista/wesnoth/src/tstring.hpp:140:2: note: candidate: ‘t_string::t_string(const t_string&)’
  t_string(const t_string&);
  ^~~~~~~~
make[2]: *** [src/CMakeFiles/wesnoth-client.dir/build.make:1597: src/CMakeFiles/wesnoth-client.dir/game_data.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:427: src/CMakeFiles/wesnoth-client.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

Same error with LTO not enabled...

**Comment by Pentarctagon** [comment]
Which version of gcc are you using?

**Comment by arosella** [comment]
$ gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Pentarctagon** [comment]
If you revert d7c148c3b4c1a9051daddc5294cd6f941940d512 does it work?

**Comment by arosella** [comment]
I'll try: at the moment, switched to clang & clang++ : it seems work like a charm. Just warnings about deprecated Boost.Coroutine, but game_data.cpp compiled with no problems..

**Comment by arosella** [comment]
$ git checkout d7c148c3b4c1a9051daddc5294cd6f941940d512
M	po/wesnoth-sof/it.po
M	src/game_data.cpp
M	src/modules/mariadbpp
Note: switching to 'd7c148c3b4c1a9051daddc5294cd6f941940d512'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at d7c148c3b4c Fix a missing detail in saved game serialization
$ mkdir build_gcc
$ cd build_gcc && cmake .. -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
[..snipped...]
-- Generating done
-- Build files have been written to: /home/macchinista/wesnoth/build_gcc
$ make -j2
[ .. compiling with a looot of warnings about Boost.Coroutine .. ]
[ 82%] Building CXX object src/CMakeFiles/wesnoth-client.dir/game_config_manager.cpp.o
[ 82%] Building CXX object src/CMakeFiles/wesnoth-client.dir/game_data.cpp.o
[ 82%] Building CXX object src/CMakeFiles/wesnoth-client.dir/game_display.cpp.o

It seems to work..

**Comment by Pentarctagon** [comment]
Can you try again now with the current 1.16 (65a951111c4a4e8ef0244199463639e469d7d14f specifically)?

**Comment by arosella** [comment]
Working!

$ git switch 1.16
$ git pull
$ cd build_cc
$ cmake .. -DCMAKE_BUILD_TYPE=Release
$ make -j2
[..]
Scanning dependencies of target wesnoth
[100%] Building CXX object src/CMakeFiles/wesnoth.dir/wesnoth.cpp.o
[100%] Linking CXX executable ../wesnoth
[100%] Built target wesnoth
$ sudo make install
