### ISSUE TITLE
[World Conquest] Issues on translatable strings

### ISSUE THREAD

**Issue by tamanegi-jp** [wesnoth/wesnoth#5975]
### Text Issues: Typos, grammar mistakes, suggested improvemetns

* Is the text in English? If not, what language is it in?
English.

* What campaign does the text appear in? If it's not in a campaign, say where it is:
World Conquest (BfW v1.15.15+dev (ec44c3be732-Modified))

Following strings are not marked as translatable, where leading/trailing spaces are omitted.
* lua/campaign/objectives.lua (texts in objectives window)
**difficulty = "Difficulty: ",**  (L8)
**version = "Version",** (L9; probably "Version" in objectives?)

* gui/help_dialog.cfg (wocopedia text and setting items)
**label = "<b>Recruits:</b>"** (L400)
**label = "<b>Deserters:</b>"** (L465)
**label = "<b>Commanders:</b>"** (L484)
**label = "<b>Heroes:</b>"** (L503)
**label = "<b>Random Leaders:</b>"** (L522)
**label = "Use WC2 PYA mod"** (L590)
**label = "Use WC2 Unitmarkers"** (L610)
**label = "Use WC2 experimental pickup"** (L630)
**label = "Show pickup confirmation"** (L650)
**label = "WC2 version"** (L691)

There are two problematic strings in help.lua.
* lua/game_mechanics/wocopedia/help.lua

The following string (at L41) seems to be incorrect; "2% to" should be removed.
```
      _ "At scenarios 1 to 3, for each training level players already own, trainers found have 2% to 4% chance to become advanced trainers (provide 2 levels). Becomes irrelevant from scenario 4 onwards because all trainers will always be advanced.\n\n" ..
```
In scenarios 1-3, there is 4 * (sum of training levels) % of chance to find advanced trainers according to "training.bonus_calculate_amount" function in lua/game_mechanics/training.lua.

In the feedback information (L43), I suppose gfgtdf's github page is no longer a suitable place for feedback.
```
                local str_cat_feedback, str_des_feedback = help_page_text( _ "Feedback", _ "For feedback please either post in the World Conquest II thread in the official Wesnoth forum &lt;https://r.wesnoth.org/t39651&gt; or file an issue at GitHub &lt;https://github.com/gfgtdf/World_Conquest_II/issues&gt;.")
```

**Comment by kabachuha** [comment]
> In the feedback information (L43), I suppose gfgtdf's github page is no longer a suitable place for feedback.
> 
>  local str_cat_feedback, str_des_feedback = help_page_text( _ "Feedback", _ "For feedback please either post in the World Conquest II thread in the official Wesnoth forum &lt;https://r.wesnoth.org/t39651&gt; or file an issue at GitHub &lt;https://github.com/gfgtdf/World_Conquest_II/issues&gt;.")

I fixed this part in  https://github.com/wesnoth/wesnoth/commit/3de79c15fbf7862f6fa2e69225cc30fcc67c6ba9 . It is coming in the 1.16.1 update. 

 P.S. Oops for the misclick.

**Comment by kabachuha** [comment]
Hmm, seems like @knyghtmare does the first part in https://github.com/wesnoth/wesnoth/pull/5948 .

**Comment by gfgtdf** [comment]
From looking at the code it seems like most of these are fixed, at least in master

**Comment by Wedge009** [comment]
Closing on basis of gfgtdf's last comment, cane be re-opened if anything besides the 'most of these' are explicitly listed.
