### ISSUE TITLE
LUA error in final mission of SOTBE

### ISSUE THREAD

**Issue by brirush84** [wesnoth/wesnoth#5992]
### Game and System Information
 - What version of the game are you running?
 1.15.14
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 Website
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
 - What OS are you running?
 Windows 10

### Describe the bug
I received a LUA error (bad argument to 'get time of day') after the opening cutscene of the final and every turn afterwards.

### To Reproduce

Start the Son of the Black Eye campaign, and then go to The Northern Alliance. A LUA bug will show up after the cut scene and every turn afterwards.

### Expected behavior
No LUA bug.

### Screenshots
![image](https://user-images.githubusercontent.com/28042598/127217450-0a674101-7c36-4cd2-8007-8d351e960af7.png)

### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

**Comment by ProditorMagnus** [comment]
Fixed with #5944

**Comment by CelticMinstrel** [comment]
Closing as duplicate.
