### ISSUE TITLE
Wesnoth can't be run as a command-line tool on MacOS

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#6003]
There are at least two different issues at play here.

* The hardened runtime setting prevents it from launching at all as a command-line tool. A possible solution here may be to bundle two separate versions of the Wesnoth executable – one to execute when running as an app, and a different one for running as a command-line tool. They'd have the same code but probably different build settings. There may be a better solution though, not sure.
* On MacOS, Wesnoth overrides the current working directory with the path to the package-internal Resources folder, which makes it impossible to pass relative paths on the command-line.

**Comment by Pentarctagon** [comment]
Has the first point been fixed now? Or is that separate from the signing issue?

**Comment by CelticMinstrel** [comment]
I believe this is fixed _for developers_ by the changes related to the addition of a SignedRelease target. However, the _released_ version of Wesnoth also needs to somehow work as a command-line tool. The main developer use-case is the WML unit tests, but there are a bunch of other options that are generally useful for addon developers, like schema validation, IPF rendering, preprocessing…

**Comment by mattsc** [comment]
Maybe I am missing something, but I just went into the 1.16.0 release's `The Battle for Wesnoth-1.16.0.app/Contents/MacOS` folder and ran
`./The\ Battle\ for\ Wesnoth --validate=data/ --preprocess-defineTEST`
and it ran just fine and told me that the validation succeeded.  Isn't that what you are talking about?

**Comment by CelticMinstrel** [comment]
Okay, if the release _does_ work, then this can be closed. That said, it should probably be tested on 1.17 rather than 1.16.

It's also possible that it works in the SourceForge and Steam downloads but not in the App Store download? If that's the case, then I don't really care. Don't use the App Store.

**Comment by mattsc** [comment]
Just to be sure, I downloaded 1.16.3 and 1.17.5 and tested it with those versions.  These are the SourceFourge downloads using the links in the release announcements forum posts.

It works for both versions.

**Comment by mattsc** [comment]
As a final remark, since I downloaded the AppStore version for testing #4795 anyway, I ran the CL validate command above with that version, and it works there as well.
