### ISSUE TITLE
Add snowy troll castle/keep terrain (to fix transition btwn snowy mountains & troll castle)

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#6016]
When updating one of my campaigns to use snowy mountains instead of regular ones (i.e. replacing `Mm` with `Ms`; see cooljeanius/Son_Of_The_Black_Eye_Easy_Edition#10), a transition between snow mountains and a troll encampment broke; note how the mountains are popping under the outer rim of the encampment:
<img width="275" alt="Screen Shot 2021-08-09 at 01 42 47" src="https://user-images.githubusercontent.com/1388660/129127559-348aed2e-7e23-458f-aae3-2ced7b646dd8.png">
A way to fix this could be to add snowy variations of the troll encampment and keep terrains; I'd recommend their codes be `Ctea` and `Ktea` (i.e., adding the `a` for `arctic` that other snowy terrains have to the existing `Cte` and `Kte` terrain codes)

**Comment by knyghtmare** [comment]
Just use terrain from Archaic Resources? (also, this FR maybe for 1.17+)

**Comment by stevecotton** [comment]
There's two different issues here, the more noticeable one of them could be fixed for 1.16.x:

* The transition graphics are broken when `Ms` is south of `Cte`, because the top of the mountain still appears inside the keep. For `Mm`, a shorter mountain graphic is used when south of castles.
* There should be a snowy troll castle/keep, with a little snow on the inside of the walls.

**Comment by doofus-01** [comment]
Yeah, the behaviour in the screenshot is a graphical glitch that can be fixed in 1.16 without making a new terrain.

**Comment by rubyFeedback** [comment]
The ice is invading the castle!!!

**Comment by cooljeanius** [comment]
I'd recommend checking the transitions for the snowy mountains terrain in general, to see if there's any other borders with it that experience the same issue, while you're at it

**Comment by doofus-01** [comment]
Right, thanks.

The chasm transitions still need work, but it doesn't need to impact this.
