### ISSUE TITLE
[Liberty][S06: The Hunters] target of "sighted" event incorrect

### ISSUE THREAD

**Issue by tamanegi-jp** [wesnoth/wesnoth#6019]
### Game and System Information
 - What version of the game are you running?
 1.15+dev (47c19ceff6f-Modified)

### Describe the bug
On Liberty scenario 06 (The Hunters), nothing happens when Helicrom side (side=2) unit is sighted by outpost guards (side=4).
 
### To Reproduce

1. Start scenario 6 (The Hunters) of Liberty
2. End turn of Baldras side and enter turn of Helicrom side
3. move Helicrom unit to the outpost and get sighted by guard unit
4. Nothing happens
(Outpost is located in upper left in the map; needs some turns to be sighted without debug mode)

### Expected behavior
Player should be defeated according to the lose condition `Any allied unit is sighted by the outpost guards`.

### Additional context
side=1 in this event should be modified to side=1,2 (scenarios/06_The_Hunters.cfg)?
```
    [event]
        name=sighted
        [filter]
            side=1
        [/filter]
        [filter_second]
            side=4
        [/filter_second]
    ....
```

**Comment by Wedge009** [comment]
Confirmed both the bug and that solution.

**Comment by Wedge009** [comment]
@nemaara Just notifying you in case you intended something different - appears this issue was introduced with your rewrite/merge of scenarios 6 and 7 in Liberty: https://github.com/wesnoth/wesnoth/commit/167de74242317a386e1555845388205e329b36d0

**Comment by nemaara** [comment]
Oops yea I gotta fix this.

**Comment by Wedge009** [comment]
Thanks, just review #6025 then.

**Comment by tamanegi-jp** [comment]
Thank you for the fix!

**Comment by Wedge009** [comment]
No worries, thanks for the report.
