### ISSUE TITLE
Allow assigning a single `[micro_ai]` to multiple sides at a time

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#6023]
I wrote a `[micro_ai]` like this:

```
        [micro_ai]
            side=4,5
            ai_type=wolves_multipacks
            action=add
            type=Wolf Rider

#ifdef DEBUG_MODE
            show_pack_number=yes
#endif
            pack_size={ON_DIFFICULTY 2 3 4}
        [/micro_ai]
```

Unfortunately when testing, the game displayed this message upon loading the scenario:
<img width="387" alt="Screen Shot 2021-08-15 at 00 42 07" src="https://user-images.githubusercontent.com/1388660/129467566-7362dafc-b2d8-4885-a8ad-60fdd322bce7.png">
Currently I am working around this by just copying and pasting the block of code twice, with different side entries each time, but it'd be a lot easier if I could consolidate them into a single block of code.

**Comment by doofus-01** [comment]
> Currently I am working around this by just copying and pasting the block of code twice, with different side entries each time, but it'd be a lot easier if I could consolidate them into a single block of code.

Copy-Paste for something like this can be avoided by using a macro.

**Comment by cooljeanius** [comment]
> > Currently I am working around this by just copying and pasting the block of code twice, with different side entries each time, but it'd be a lot easier if I could consolidate them into a single block of code.
> 
> 
> 
> Copy-Paste for something like this can be avoided by using a macro.

That just gave me the idea to re-implement the `{ATTACK_DEPTH}` macro in terms of this MAI, but that'd require #5910 being fixed first, for it to be usable as a drop-in replacement, without updating any usages of the macro...

**Comment by cooljeanius** [comment]
Thanks for fixing, @CelticMinstrel! IMO this should get a note on the wiki page for MAIs, too: https://wiki.wesnoth.org/Micro_AIs

**Comment by CelticMinstrel** [comment]
Yeah, I still need to document all the changes I just merged into master. I'll probably put it off until after 1.16 is released, though.

**Comment by sevu** [comment]
This is not yet documented in the wiki.

**Comment by cooljeanius** [comment]
> Yeah, I still need to document all the changes I just merged into master. I'll probably put it off until after 1.16 is released, though.

> This is not yet documented in the wiki.

Separate issue for the documentation, or re-open this one?

**Comment by CelticMinstrel** [comment]
What? It's documented and has been since around when Sevu posted. (Probably just after.)

**Comment by cooljeanius** [comment]
> What? It's documented and has been since around when Sevu posted. (Probably just after.)

OK, sorry, never mind, then.
