### ISSUE TITLE
utils::format_timespan() is too buggy to contact the translators about

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#6036]
`utils::format_timespan(std::time_t)` is a function for converting times into strings such as "3 months and 20 seconds".

Several things to note about this:

* It uses a hardcoded assumption of 30 days per month, despite being able to generate strings with years and seconds.
* It's only called from one place, which is to display ban durations to people banned from the multiplayer server.
* It doesn't use [gettext's pluralisation rules](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html), instead it hardcodes the bug described at the top of that page.
* A string such as "3 months and 20 seconds" lacks the concept of significant figures.

The Spanish and French translations omit the number from the translation of `timespan^$num years`, but given the problems in the C++ I think that's the least of the issues here.

**Comment by irydacea** [comment]
Hi, author of the function here. I wrote it as part of fixing #3766 in PR #3904.

Could you clarify what you mean by "lacks the concept of significant figures"?

> It uses a hardcoded assumption of 30 days per month

I thought about this part very hard and concluded that for the initial purpose of the function there was absolutely no need to get into calendar specifics, since most people tend to call 30 days a month anyway to keep things simple. Bear in mind that if you wanted to change this assumption, you would need a precise reference point as a new function argument in order to be able to tell what the individual lengths of the months encompassed by the specified period of time are (in the Gregorian calendar at least).

> It doesn't use gettext's pluralisation rules, instead it hardcodes the bug described at the top of that page.

This is intentional. In order to keep the code clean, a look-up table is used for the format strings, which means that they must not be **translated** strings, while `_n()` only ever returns translated strings. I did consider using gettext plurals but found that rearranging the code for that purpose would make it considerably worse for a fairly nonexistent benefit.

**Comment by stevecotton** [comment]
> Could you clarify what you mean by "lacks the concept of significant figures"?

I mean that it's usual to round numbers a few decimal places, and in a similar way I think that it's odd to include units much smaller than the largest one. "2 months and 10 seconds" is 2.0000039 months; when the largest unit is months then it feels odd to me to include any unit smaller than days. It also feels odd to go to a precision smaller than days when people expect "1 month" to vary by +/- a few days anyway.

Will think more about the code when I'm more awake tomorrow.

**Comment by irydacea** [comment]
> I mean that it's usual to round numbers a few decimal places, and in a similar way I think that it's odd to include units much smaller than the largest one. "2 months and 10 seconds" is 2.0000039 months; when the largest unit is months then it feels odd to me to include any unit smaller than days. It also feels odd to go to a precision smaller than days when people expect "1 month" to vary by +/- a few days anyway.

I guess. I don't think the people reading these really care that much about the exact length of time, to be honest (and if they do all the more reason to keep them banned).

**Comment by CelticMinstrel** [comment]
So basically, in order to solve point 3, we need a version of `_N()` for plural strings.

**Comment by Pentarctagon** [comment]
My own two cents:
* If it's shorter than 24 hours remaining, show hours/minutes/seconds.
* If it's longer than 24 hours, show just the days left rounded down.  If someone's ban has 97 days remaining and is frustrated that they don't know exactly how many months and days the equates to, then... I just don't care.  The solution there is they shouldn't do the thing that got them banned for multiple months.

**Comment by stevecotton** [comment]
Making "days" be the biggest unit simplifies things. I'd happily open a PR either for Pentarctagon's solution, or for the idea in the next paragraph.

I've been wondering about taking the biggest unit that there are at least three of, and then giving only that unit. So "5 days", "4 days", "3 days", "71 hours", ..., "50 hours", ..., "3 hours", "179 minutes", ..., "3 minutes", "179 seconds", ..., "2 seconds", "1 second", "expired".

**Comment by irydacea** [comment]
> I'd happily open a PR either for Pentarctagon's solution, or for the idea in the next paragraph.

I know you like writing code but I haven't exactly been hit by a bus yet.

> So "5 days", "4 days", "3 days", "71 hours", ..., "50 hours", ..., "3 hours", "179 minutes", ..., "3 minutes", "179 seconds", ..., "2 seconds", "1 second", "expired".

If we are using fuzzy times, how do you get from 3 minutes to 179 seconds? What about 120 seconds?

**Comment by stevecotton** [comment]
> I know you like writing code but I haven't exactly been hit by a bus yet.

Apologies, I've focused too much on coding and forgotten about politeness.

> > So "5 days", "4 days", "3 days", "71 hours", ..., "50 hours", ..., "3 hours", "179 minutes", ..., "3 minutes", "179 seconds", ..., "2 seconds", "1 second", "expired".
> 
> If we are using fuzzy times, how do you get from 3 minutes to 179 seconds? What about 120 seconds?

I was going to use "120 seconds" for simplicity of coding, thinking that "90 seconds" and "150 seconds" sound right; but now that you point it out it, it would be better to use "2 minutes". For the string "179 seconds" - yes it's strangely precise, but that also avoids adding code just to round it to something less precise.

**Comment by stevecotton** [comment]
Resolved in #6097 and #6105.
