### ISSUE TITLE
UtBS S2 'wrong' item description (Travellers Ring)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#6043]
### Text Issues: Typos, grammar mistakes, suggested improvements

* Is the text in English?
Yes.

* What campaign does the text appear in?
Under the Burning Suns S2

* Please quote the text verbatim. You can use `**bold**` to point out the mistaken part:
https://github.com/wesnoth/wesnoth/blob/6b6eb8a35b957f87606cf2678fd11e91bb12ab15/data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg#L514
At the **end** of each turn

https://github.com/wesnoth/wesnoth/blob/6b6eb8a35b957f87606cf2678fd11e91bb12ab15/data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg#L341
at the **beginning** of each your turns

* _(optional)_ What do you propose to change the text to?
I believe the explanation of the Travellers Ring should say 'At the **start* of each turn'

**Comment by stevecotton** [comment]
As the mechanics are already explained elsewhere, I suggest simply "The unit wearing this ring will not become dehydrated by the desert."
