### ISSUE TITLE
UtBS S3, Garaks blessing includes steadfast, which is useless for him

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#6046]
### Game and System Information
 - What version of the game are you running? 1.15.15
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.) Steam
 - What OS are you running? Windows 10

### Describe the 'bug'
Garak has -10% arcane and 0% for other resistances, which is why 'steadfast' is useless and serves only to confuse the player.

### To Reproduce

1. First load the save file, check his stats and abilities.

### Expected behavior
No steadfast, and/or maybe some ability that raises his resistances.

### Savefiles
[UtBS-A Stirring in the Night-Auto-Save4.gz](https://github.com/wesnoth/wesnoth/files/7038818/UtBS-A.Stirring.in.the.Night-Auto-Save4.gz)

**Comment by knyghtmare** [comment]
> No steadfast, and/or maybe some ability that raises his resistances.

Maybe some ability which gives +20% resistances on offence?
Or, some ability which gives +10% resistances on defence?

Actually, no. This would mean more strings...with string freeze in effect...so...no steadfast seems the best option.

**Comment by Discontinuum** [comment]
Add him some armour with the blessing xD and the steadfast will become useful

**Comment by Konrad22** [comment]
Reopening this, as the resistance ability special for Garak is just a useless as the steadfast was. The ability triggers only if Garak has more than 0% resistance, which he doesn't have vs any dmg type. Same problem as steadfast.

**Comment by soliton-** [comment]
The filter_base_value part seems like it should just be removed, `max_value` already caps it to 50% and I see no reason to special case vulnerabilites. Of course the description would need to be adjusted.

Btw, if you remove the C parts of your URL (`#L699C1` -> `#L699`) and just keep it to full lines then github will show the linked range itself.
