### ISSUE TITLE
Leaders sprite gets displaced when zoomed in on TRoW S8

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6068]
### Game and System Information
 - 1.15.17
 - Downloaded from Steam
 - Windows 10
 - Display Resolution is Fullscreen 1366x768

### Describe the bug
In the scenario Clearwater Port, when zooming in on any leader (you, allies, and enemies) while they are standing on their keep (the hex they can recruit from), the leader's sprite gets displaced upwards. The displacement gets worse the further in you zoom. If the leader is moved to other hexes the displacement does not occur. I have not observed the bug in other scenarios. The issue manifests consistently every time the scenario is reloaded, even after exiting and relaunching the game.

### To Reproduce

1. Load a scenario save of TRoW S8 Clearwater Port. Save file attached.
2. Zoom in on any of the leaders
3. Observe that the displacement gets worse the further the zoom level
4. Observe the behavior with all leaders
5. Move the leader out of the keep to observe that the behavior only occurs on a keep hex.

### Expected behavior
Leaders get displaced upwards when zooming, getting worse the further in you zoom.

### Screenshots
![image](https://user-images.githubusercontent.com/41433185/132472186-e29743d1-10df-47ec-acdc-cd415d8f7314.png)
![image](https://user-images.githubusercontent.com/41433185/132472283-32b4f35c-390a-4936-bb8e-15284a14b3b4.png)
![image](https://user-images.githubusercontent.com/41433185/132472380-117bd5d6-eed9-4cc6-9331-f6732895f5bf.png)

### Savefiles
[TRoW-Clearwater Port-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/7127123/TRoW-Clearwater.Port-Auto-Save1.gz)

### Additional context
Maybe check if the issue is consistent with any Human Frozen Keep Hex, or consistent only with S8 of TRoW.

**Comment by cooljeanius** [comment]
this is a dup of #5974

**Comment by Wedge009** [comment]
Thanks for both the report and the duplicate notification.
