### ISSUE TITLE
Issue in translating "kick" unit attack. New string required.

### ISSUE THREAD

**Issue by sheepo99** [wesnoth/wesnoth#6071]
### Situation

As of my knowledge, the string for the "kick" attack is present in the following units: **Horses** (bay, dark, white unit ranges) the **Wild Wyvern**, and the **Orcish Nightblade**. See screenshot below.

![image](https://user-images.githubusercontent.com/3621746/132769465-544f70c6-f6df-4e7f-95ec-ce50a70499f4.png)

### Issue

When translating the string "kick" to Portuguese (Portugal) a problem arises from the fact the language has separate words for "human kicks" and "animal kicks". A kick delivered by a human foot will always be called _pontapé_. A kick delivered by an animal is usually called _coice_. This means that picking either of the options for translation will always end up in at least one inadequate translation because there is only one string to cover all three attacks. There are also no "neutral" Portuguese words I can use in this circumstance (such as the Portuguese equivalent for the words "hit" or "slam"), because the attack icon for horses show a picture of a hoof, and the attack animation for the Nightblade displays a flying kick. Therefore a new string is necessary for the horse attacks in order to ensure a decent translation.

### Proposed solution

- Create a new dedicated string for the horse attack called "hooves", since it's in line with other animal attacks like "claw", "tusk", etc.
- Replace the Wyvern attack name with "slam", which is already used in Sky Drakes and currently uses the same icon as the Wyvern "kick". See picture below:

![image](https://user-images.githubusercontent.com/3621746/132769953-9008813f-c3a6-4e4a-9ed6-31fb6b6af5ec.png)

**Comment by Wedge009** [comment]
As I recall from the #wesnoth-dev discussion yesterday, we had a couple of different ideas:
* Use prefixes to distinguish between the animal/monster kick vs the humanoid/orcish kick.
* Rename the Nightblade's kick to something like 'flying kick' to distinguish its ninja-like attack from the animal attack: https://raw.githubusercontent.com/wesnoth/wesnoth/master/data/core/images/units/orcs/nightblade-kick-se-6.png

Any solution would need to wait until the 1.16.0 string freeze is over (#5973)

**Comment by sheepo99** [comment]
I personally think the best solution would be to create a new string to rename the horse attack to "hoof" or "hooves" since it's much more specific and prevents confusion and inquiries from other translators wondering why are there two prefixed strings for "kick". That also means the Nightblade attack can remain as is ("kick") and the Wild Wyvern attack can simply be matched to that of the Sky Drake.

**Comment by Wedge009** [comment]
Sure, at this point I think it might work nicely too.

@doofus-01, @Hejnewar, @Pentarctagon, @Turuk, any strong preferences on which way to go, as original authors or maintainers? (@CelticMinstrel too, from #wesnoth-dev discussion)

Otherwise I can make a PR for the suggested change in a short while.

**Comment by doofus-01** [comment]
No preferences.  Horses kick, and that makes more sense to me for the name of an attack, but they have hooves, so I guess it's the same as "sword" for a human instead of "slash".
