### ISSUE TITLE
"World Conquest 3p" option in map generator causes error

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#6077]
### Game and System Information
 - What version of the game are you running?
 -- Battle for Wesnoth v1.15.17+dev (9a36ff4d8c2-Modified) x86_64
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 -- Source, Linux

### Describe the bug
Try to generate a map in the map editor using the "World Conquest 3p" option of the Generate Map dialog.  It doesn't work.
```
campaigns/World_Conquest/lua/map/main.lua:42: bad argument #-1 to 'dofile' (file not found)     stack traceback:
        [string ""]:8: in function <[string ""]:8>
        [C]: in field 'dofile'
        campaigns/World_Conquest/lua/map/main.lua:42: in function '.wc_ii_generate_scenario'
        (...tail calls...)
        [C]: in function '.xpcall'
        [string ""]:8: in main chunk
nil
20210912 13:29:55 error mapgen: Error when running lua_map_generator create_scenario.
The generator was: World Conquest 3p
bad return value:
  expected a config (table), found a nil
```

**Comment by knyghtmare** [comment]
Not sure how you have gotten this one. I can generate maps using the WC 3p option just fine on Mac OS X

**Comment by stevecotton** [comment]
I can reproduce it, when doing this in the map editor instead of doing it in the create game screen.

It's trying to load a file from `data/campaigns/World_Conquest/lua/map/scenarios/`, but with `nplayers` set to `0`. Seems a bug in this line:
https://github.com/wesnoth/wesnoth/blob/e235d9a64e50a1af0a228292849d9a054dae76e5/data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg#L241-L245

**Comment by Pentarctagon** [comment]
Note that the #ifndef is a temporary fix for this issue (see #6059).

**Comment by stevecotton** [comment]
Would removing the whole `#ifdef EDITOR` section (except the `#else` block) be an acceptable fix?

**Comment by Pentarctagon** [comment]
I'd think so, given it was added relatively recently and while WC was disabled, so very few people would've had access to it.

Though I am also curious if this worked when @CelticMinstrel added it or not.

**Comment by CelticMinstrel** [comment]
That won't work – the editor _only_ reads multiplayer scenarios when looking for map generator engines. However, having three scenario definitions in the editor depending on the number of players is probably acceptable, although I think there's also a player slider once you click on one of them so it's not ideal.

**Comment by Pentarctagon** [comment]
If there's a player slider anyway, couldn't nplayers=0 just be changed to nplayers=1?

**Comment by CelticMinstrel** [comment]
It's worth a try.
