### ISSUE TITLE
Generate Chocolatey packages for releases

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#6099]
[Chocolatey](https://docs.chocolatey.org/en-us/faqs) is a popular fully-user-space package management system for Windows. It has over 10M users, maybe even over 50M. Many many applications are packaged for Chocolatey either by their developers or by third-party package maintainers. 

There [is currently a Wesnoth 1.14.16 package](https://community.chocolatey.org/packages/wesnoth/1.14.16) in the Chocolatey repository, but it doesn't seem that well-taken-care-of (e.g. its Changelog link is dead).

I was hoping the packaging/dissemination mechanism the project uses might also be made to include the generation and upload of a Chocolatey package for each release of the game - hopefully maintaining a most-current release version and most-current development/beta version.

**Comment by eyalroz** [comment]
@Pentarctagon : I see your point about the low number of downloads; although I would perhaps counter with the fact that Wesnoth has not been announced or promoted as a Chocolatey app. In fact, one could argue that typical Windows users would benefit from downloading Wesnoth via Chocolatey, since it would auto-update whenever they update the rest of their software.

Also, and perhaps more fundamentally - this is somewhat similar to how it is available as a package in all major Linux distributions.

**Comment by soliton-** [comment]
Is there any other indication that it's not taken care of besides the changelog link? (should be changelog.wesnoth.org)

It's marked as a trusted package. 1.15.17 is available as well. Releases seem to be around 2 days after upstream tagging.

Perhaps it'd be more useful to report the broken changelog link on that site.

**Comment by eyalroz** [comment]
> 1.15.17 is available as well

It is? ... I don't see it in the Chocolatey app.

**Comment by soliton-** [comment]
On the page you linked you can click on "Version History": https://community.chocolatey.org/packages/wesnoth/1.15.17-beta

**Comment by Pentarctagon** [comment]
@eyalroz Adding distribution methods is more work to maintain and keep updated.  itch.io was added as a distribution method because it was both trivial to do and provided a simple way for itch.io users to donate if they wished to.  Barring a specific benefit of a distribution method that would justify the effort, I don't think Wesnoth really needs to officially support Yet Another Distribution Method in this case for the same reason I don't think we need to officially have AppImage or Snap packages on Linux.

**Comment by eyalroz** [comment]
@Pentarctagon : Ok, I guess I'm convinced.
