### ISSUE TITLE
Replace informal/anachronistic language

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6107]
Noticed use of 'cool' and 'guys' while replaying Northern Rebirth S5. While I recognise this campaign - and scenario in particular - is more light-hearted and/or fourth-wall-breaking in some of its dialogue, the following phrases didn't read well to me. (I also searched all campaigns for other instances of these words.)

### Proposed Changes
https://github.com/wesnoth/wesnoth/blob/4c9e016fa319eea34d2aa60e02f666a354625b89/data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg#L1169-L1170
I had Tallin find this signpost, so it just sounded weird to me (even accepting that he's an uneducated, albeit brave and inspiring, fighter). I propose '**Great**, let's loot some booty!' Or since `en_US` is default, I suppose it's fine to leave it as 'let's go loot'.

https://github.com/wesnoth/wesnoth/blob/4c9e016fa319eea34d2aa60e02f666a354625b89/data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg#L804-L805
This is in the context of Morvin's and Thera's first death-respawn event. Propose '...kept you **two** in jail...'

https://github.com/wesnoth/wesnoth/blob/4c9e016fa319eea34d2aa60e02f666a354625b89/data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg#L1840-L1841
Finding the signpost to Malifor's study. Propose 'This way, **everyone**!'

https://github.com/wesnoth/wesnoth/blob/4c9e016fa319eea34d2aa60e02f666a354625b89/data/campaigns/Northern_Rebirth/scenarios/10a_Stolen_Gold.cfg#L1054-L1055
The lich is getting impatient at the lengthy introductions between Tallin, Eryssa, and Hidel. Propose 'if you **lot** are quite finished...'

https://github.com/wesnoth/wesnoth/blob/4c9e016fa319eea34d2aa60e02f666a354625b89/data/campaigns/Son_Of_The_Black_Eye/scenarios/08_Silent_Forest.cfg#L271-L272
Even accepting the orcs' general lack of literary sophistication, 'guys' still sounds too anachronistic to me. Propose to just skip the word 'guys' altogether, as it still reads fine to me, ie 'You already have...'

https://github.com/wesnoth/wesnoth/blob/4c9e016fa319eea34d2aa60e02f666a354625b89/data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg#L415-L416
Elyssa is the fire mage introduced in the prior scenario of Under the Burning Suns, and this is in the context of discussing the undead appearing during the 'long dark' night cycle. Propose 'why can't these **creeps** just stay dead?' (Elyssa also seems to be a less formal character, otherwise I'd consider 'ghosts' or similar.)

### Probably Justifiable
https://github.com/wesnoth/wesnoth/blob/4c9e016fa319eea34d2aa60e02f666a354625b89/data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg#L1037-L1038
Camerin's already a little crazy, so I suppose using 'cool' in his informal context is okay.

https://github.com/wesnoth/wesnoth/blob/4c9e016fa319eea34d2aa60e02f666a354625b89/data/campaigns/Northern_Rebirth/scenarios/07a_Settling_Disputes.cfg#L464-L465
https://github.com/wesnoth/wesnoth/blob/4c9e016fa319eea34d2aa60e02f666a354625b89/data/campaigns/Northern_Rebirth/scenarios/07a_Settling_Disputes.cfg#L832-L833
Four uses of 'guys' by Camerin in the one scenario. But I suppose if he's allowed to use 'cool' in his crazy informal dialogue, he can use 'guys' here, though I could probably rephrase this to avoid its use.

Every other use of 'cool' that I found relates to temperature rather than as a synonym for 'super', 'awesome', 'great', etc. Other uses of 'guys' are only internal (not player-visible from within the game itself), eg team: 'bad guys'.

@nemaara or anyone else, if this looks okay I'll submit a PR shortly. Or let me know of any suggestions of your own, for either the proposed changes or for Camerin, so they can be merged together.

**Comment by Asheviere** [comment]
I don't quite like "you guys" even in a modern setting for writing, and I think your changes are just an improvement overall. Idk how much my opinion matters though.

**Comment by nemaara** [comment]
NR is a tricky case because it's not really a serious campaign like the others. Although you raise a good point here, I think right now it would be better to keep the informal tone for most of the lines, even if they're anachronisms. The ones that would be easy to change right now are for Ro'Arthian (or Ro'Sothian), and Elyssa, who wouldn't feel as out of place speaking more formally. 

Other campaigns shouldn't use anachronisms yea.

**Comment by CelticMinstrel** [comment]
> Or since en_US is default, I suppose it's fine to leave it as 'let's go loot'.

I don't think "let's go loot" sounds good. Maybe something more like "let's get to looting" or similar? Though "let's loot some booty" doesn't sound too bad either, I suppose. Another possibility would be to completely rewrite it, maybe something like "let's clear it out" or similar.

Also, I have a feeling that "great" still has the same problem as "cool"… how about using "excellent" instead? Or does that seem _too_ formal?

**Comment by Wedge009** [comment]
I did recognise that NR appears to take a less formal tone in places for comic effect, but the 'cool' and 'guys' just stood out too much for me (and not in a good way). And of the four proposed changes for NR, two of them are not tied to specific characters so I'm still inclined to make those changes. I'm okay to leave the 'guys' for Camerin's lines, though (like Asheviere, I didn't really like it but can accept it's justifiable).

Regarding 'go', it might not specifically be American but in my personal experience I find it's often in casual American English where a superfluous 'go' is added before verbs. Celmin makes some good suggestions, I'll settle on one when submitting the PR.

'Excellent' can also qualify as informal to my mind - I have a manager who likes to say 'excellent' in the same vein as The Simpsons' Mr Burns, and I also think of Beast Wars Transformers' Megatron whose trademark vocal tic was 'excellent... yessss'.

**Comment by Wedge009** [comment]
I forgot to mention that I also left alone Thera's use of 'good guys' as it feels like a fourth-wall breaking moment relating to their immortality game-play mechanic:
https://github.com/wesnoth/wesnoth/blob/4c9e016fa319eea34d2aa60e02f666a354625b89/data/campaigns/Northern_Rebirth/utils/herodeaths.cfg#L486-L487

(It's about time some player characters have the same respawn magic that many opponents in the campaigns also have.)

**Comment by CelticMinstrel** [comment]
> Regarding 'go', it might not specifically be American but in my personal experience I find it's often in casual American English where a superfluous 'go' is added before verbs. Celmin makes some good suggestions, I'll settle on one when submitting the PR.

I think my objection isn't so much from the "go" but rather the fact that it feels like "loot" needs an object. Wiktionary does define it as a transitive word, so there's probably merit to my feeling. (Technically it does say there's an intransitive sense, but the example for that sense still has an object, so I'm not sure how to intepret that.)

**Comment by Wedge009** [comment]
No worries, I liked your rephrasing anyway.
