### ISSUE TITLE
TRoW Final Scenario Turns Run Out is a defeat condition but there is no Turn Limit

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6109]
The Final Scenario of The Rise of Wesnoth states in its Objectives "Turns Run Out" as a defeat condition even though there is no turn limit. This text should be removed from the objectives
![image](https://user-images.githubusercontent.com/41433185/133994882-58e5a7b7-7731-405a-8d1a-909f390ad62a.png)

**Comment by Wedge009** [comment]
Thanks for spotting and reporting this. Looks like the turn limit was removed in 1.15.10 (next time please don't forget to report the game version) but the lose conditions weren't updated.

I checked all scenarios with unlimited turns and this doesn't appear to be an issue anywhere else, except for Eastern Invasion S11, but turns are only limited once allies are rescued and objectives are appropriately updated at that point.

**Comment by max-torch** [comment]
> Thanks for spotting and reporting this. Looks like the turn limit was removed in 1.15.10 (next time please don't forget to report the game version) but the lose conditions weren't updated.
I was actually somewhat autopilot following the "guide template" that the textbox contains when you make a new issue, For other issues the template does include "specify game version", but if the chosen category is "typos" the "specify game version" is not part of the guide template. We could include the reminder to specify game version in that template.

**Comment by Wedge009** [comment]
Ah, this would really be a bug report than a text improvement - I suppose that explains the prose tag then. No worries, at least the issue was resolved.
