### ISSUE TITLE
LoW Sc.3 Kalian under attack

### ISSUE THREAD

**Issue by rmj555** [wesnoth/wesnoth#6112]
1.15.14
Windows 10
Sourceforge

Every turn of Sc. 3 of LoW gives five LUA errors relating to time of day is nil.

**Comment by Wedge009** [comment]
That's an old build. Please try the current 1.15.17 release.

**Comment by cooljeanius** [comment]
does 060ab19 fix this?

**Comment by Asheviere** [comment]
Different deprecated WML warning.

**Comment by Wedge009** [comment]
As mentioned above, there will be deprecation warnings in 1.15.17, but not related to time-of-day. Unless there's more info on this, I'll close it in a few days.

**Comment by CelticMinstrel** [comment]
It sounds like this could be #5944? I can't tell without further info though.

**Comment by Wedge009** [comment]
Same version, same description, could well be.

**Comment by rmj555** [comment]
No problem when I updated to 1.15.17.  Close this issue.

**Comment by Wedge009** [comment]
Thank you for confirming.
