### ISSUE TITLE
UtBS S2 Across the Harsh Sands: Add ring icon of Traveler's ring to the unit sprite

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6126]
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

### Describe the desired feature
Add an indicator icon on the sprite of the unit that takes the Traveler's Ring.
This feature is already implemented in Dead Water.
![image](https://user-images.githubusercontent.com/41433185/134915808-fc170dc4-4d4b-4bb2-a6f3-f93d3e5069dc.png)
We should also implement this here.

### Screenshots
The Traveler's Ring which I gave to the unit called Nisen. On some occasions I had to check the names of all the Quenoth scout units to find him:
![image](https://user-images.githubusercontent.com/41433185/134915209-a6309130-4bcc-48e6-83fb-88c07bd5c571.png)

There is nothing to indicate that he now possesses the ring:
![image](https://user-images.githubusercontent.com/41433185/134915383-56fdc3d6-ea6c-43d5-a80c-087748192414.png)

**Comment by Wedge009** [comment]
There are number of items that provide bonuses that units can pick up across several campaigns, including the storm trident (as you no doubt remember), holy water, etc. Some instances - but not all - have an associated icon attached to the unit. What bonus is the one attached to the Dead Water unit?

**Comment by max-torch** [comment]
> There are number of items that provide bonuses that units can pick up across several campaigns, including the storm trident (as you no doubt remember), holy water, etc. Some instances - but not all - have an associated icon attached to the unit. What bonus is the one attached to the Dead Water unit?

+3 HP
+1 damage of each attack

**Comment by Wedge009** [comment]
I meant, what is it called?

**Comment by knyghtmare** [comment]
It more of a question of user experience. The issue is about players finding it difficult to discern which unit inherits the traveler's ring. Thus, adding the icon on top of the unit as a halo via EffectWML is good solution to let players know which of their units has taken the item/artifact.

**Comment by Wedge009** [comment]
Yep, that's what I was looking for. I'm just wondering why it was only ever applied in some instances, not all or even most of them - maybe hard to find all the instances where this kind of thing happens (I'm thinking of the armour item bonus in HttT, for example.

**Comment by knyghtmare** [comment]
> Yep, that's what I was looking for. I'm just wondering why it was only ever applied in some instances, not all or even most of them - maybe hard to find all the instances where this kind of thing happens (I'm thinking of the armour item bonus in HttT, for example.

No overlay images for the items. We can make them via IPF.

In the case of DW, it has its own overlay icons for all artifacts inside its image directory.

**Comment by max-torch** [comment]
> I meant, what is it called?

ring of power

**Comment by Wedge009** [comment]
The ring image in UtBS just uses a generic ring image from the core data set:
https://github.com/wesnoth/wesnoth/blob/ca90694141d8e2c5d2d1ea8afcfb071e9a439f12/data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg#L510-L520

Comparing this image with the overlay used in Dead Water, it's clear the latter is offset to be suitable for use with units:
https://github.com/wesnoth/wesnoth/blob/master/data/core/images/items/ring-white.png
https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Dead_Water/images/overlays/silver-ring-icon.png

**Comment by max-torch** [comment]
This is a good candidate feature for fanning out.
