### ISSUE TITLE
DW S8: Add carryover gold note to the objectives

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6131]
### Text Issues: Typos, grammar mistakes, suggested improvements

* English
* Dead Water Scenario 8, Talking with Tyegea
* The objectives currently:
![image](https://user-images.githubusercontent.com/41433185/135268567-1cf4c925-c7e4-4467-90b1-d93170f9ae89.png)
* The proposed change:
![image](https://user-images.githubusercontent.com/41433185/135269375-8be551d7-f809-4bb0-aba3-3bc177e300bd.png)
* Rationale:
The narrator hint explains that you may recall or recruit a unit. It does not make it clear that doing this will impact your carryover gold for the next scenario. If this fact is made clear, the player may choose to give the holy water only to a unit that has already been auto-recalled at the start of the scenario.

**Comment by Wedge009** [comment]
I imagine it's trivial to do this, but I wonder if a better solution would be to transfer the carry-over gold amount from the previous scenario directly to the next instead.
