### ISSUE TITLE
TSG Scenario 5: Forest march too long

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#6132]
In Scenario 5 of the South Guard, in the introductory dialog before the actual scenario, it says:

> For **many weeks** they marched down nameless paths that no man had trod before.

Many weeks is too long. Now, it's true that it's a forest, but still - this is a party guided by Elves, so they didn't just get lost and go in circles. Plus, Deoran would not have agreed to leave the area he's supposed to protect and command, including the town of Westin, not just without his own presence, but without his Lieutenant Garrick and the Minister of Westin.

I believe this should be replaced with something like "many days" or "days and days" - which is pretty vague; or maybe "marched for days, which became weeks" - suggesting that it's several weeks.

**Comment by nemaara** [comment]
Yea you're right, I'll make it many days once string freeze is done.
