### ISSUE TITLE
TRoW S19 The Vanguard: Ensure the player receives the gold the orcs drop before ending the level

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6141]
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

### Describe the desired feature
In the beginning, the orcs' dialog talks about a chest of gold that they drop:
![image](https://user-images.githubusercontent.com/41433185/135708584-81f27e31-2dc3-49c0-9f47-f0453e7e868c.png)
Later, the player has to move a unit onto the hex containing the chest of gold to get it:
![image](https://user-images.githubusercontent.com/41433185/135708615-d299cd1c-e95b-484e-a085-edb37e571ba0.png)
**It is not 100% obvious** that this wooden box sprite is the aforementioned chest of gold, and **the player can finish the scenario by killing the leader without ever picking up the gold**. 

It seems that players are meant to get this chest as it's referenced in the dialog, and is placed right close to the leader, on the way to approaching the enemy leader, who you have to defeat to finish the scenario.

The desired feature is to make the player receive gold as an event triggered by killing the troll leader and remove the chest from the map. This is consistent with what occurs in other scenarios in the campaign, such as in the scenario Troll Hole, where the player finds gold after killing an enemy leader. Let the unit that delivers the killing blow say something like "I found the chest of gold the orcs dropped nearby somewhere on the battlefield. It seems the trolls were trying to retrieve it. Some _friends_ these orcs are."

**Comment by Wedge009** [comment]
Would have to ask the author what the intent of making it a separate chest rather than upon killing the leader, but an option could be just to label the tile on which the chest sits, right?

I've also run into a similar problem such as in the Captured scenario of Eastern Invasion - one of the bonus objectives is to retrieve your stolen gold but initially I had trouble finding where it was sitting.

**Comment by knyghtmare** [comment]
> Would have to ask the author what the intent of making it a separate chest rather than upon killing the leader, but an option could be just to label the tile on which the chest sits, right?

Is the author of TRoW still active? 

I think getting gold added into the warchest on leader kill is better than spending some MP and a unit to swipe the chest. However, having the chest there also allows grabbing the gold without killing that leader first.

**Comment by max-torch** [comment]
The forum feedback of the scenario actually has people finding the "drop the gold" dialog awkward and possibly misconstruing it's meaning. https://forums.wesnoth.org/viewtopic.php?p=472038#p472038

>having the chest there also allows grabbing the gold without killing that leader first.

Would having someone try to somehow grab the gold, so that you could recruit more before making your assault, be practical on any difficulty of the scenario?

**Comment by max-torch** [comment]
> Would have to ask the author what the intent of making it a separate chest rather than upon killing the leader, but an option could be just to label the tile on which the chest sits, right?

Chest location varies randomly each time, would this make it difficult to implement a label?
![image](https://user-images.githubusercontent.com/41433185/135715550-9b319177-9bbf-44f5-90d1-58c3b054a3ce.png)

**Comment by stevecotton** [comment]
Having a chest on the map to fit with the dialog seems a nice touch to me.

If the player doesn't pick it up first, maybe have Haldric pick it up in the `victory` event, along with a comment about it.

**Comment by max-torch** [comment]
> Having a chest on the map to fit with the dialog seems a nice touch to me.
> 
> If the player doesn't pick it up first, maybe have Haldric pick it up in the `victory` event, along with a comment about it.

Oh hey, this is perfect! Nice, I second this.
