### ISSUE TITLE
[SoF] S3 Searching for the Runecrafter: Add Narrator hint describing Thursagan's rune upgrade mechanic

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6153]
In the scenario Searching for the Runecraft of Sceptre of Fire. I propose adding a narrator hint after the following line:
https://github.com/wesnoth/wesnoth/blob/dd3baa488150bfc8d8cd0105da9083009cb29ca0/data/campaigns/Sceptre_of_Fire/scenarios/3_Searching_for_the_Runecrafter.cfg#L620
The issue is that the line can be construed as some sort of story dialog only, and even if understood as explaining a game mechanic, it is still unclear how exactly the interface for interacting with this mechanic works.
I also discussed this in the forums: https://forums.wesnoth.org/viewtopic.php?p=668143#p668143. Konrad2 had to explain to me how it works.
The narrator-hint should be a metatext that officially explains how to use the mechanic.

**Comment by doofus-01** [comment]
What sort of interface do you use?  Using a mouse, it seems pretty hard to miss, almost to the point of being a nuisance (hence the "reject" option), so I don't see how you can be so baffled.  But maybe it's different on a touch device or is there some common hot-key method of moving units around?  If that's the problem, it should probably be addressed in the mechanic, rather than a tutorial message.

**Comment by max-torch** [comment]
It's about not even knowing what I was supposed to and could do.

With a mouse. When I saw the glowing rune animation on the unit beside Thursagan, I had no idea what it meant. Then when I was told you could upgrade it, the first thing that comes to mind is to right-click the unit, and not to left-click the unit to bring up the upgrade menu.

**Comment by doofus-01** [comment]
> With a mouse. When I saw the glowing rune animation on the unit beside Thursagan, I had no idea what it meant. Then when I was told you could upgrade the unit, the first thing that comes to mind is to right-click the unit, and not to left-click the unit to bring up the upgrade menu. It would have never occurred to me that you would have to left-click the unit. Nowhere is it explained that left-clicking on the unit is how you bring up the upgrade menu. Why not just make it explicit for the player?

No offense intended, but your being paralyzed with confusion upon seeing the rune animation must be very unusual.  Select (left-click) is pretty much the default action, the bare minimum of exploration on the player's part.  The context menu (right-click) is a convention familiar to any veteran Wesnoth player, but it's also really easy to go through a mainline campaign without using it.

Maybe the mechanic needs revision or rethinking, but adding narrator noise disrupts the scene for little gain.  If a notice is really needed, updating the objectives would probably be more helpful.

**Comment by max-torch** [comment]
Well at least I shared my own personal experience with SoF. Thanks for taking the time to respond to it I do appreciate it.

**Comment by doofus-01** [comment]
A note in the objectives won't break immersion or create dialog noise, sounds harmless to me.  And if the player needs the help, they can consult it at any time.

**Comment by max-torch** [comment]
Before I make a PR for this, I'd like to get approval for the note text first.

Proposed Objective Note:
> While Thursagan is on a keep, left-clicking on adjacent dwarves opens Thursagan's Rune Shop. Purchased rune upgrades are not carried over to the next scenario.

Will make a PR when the text is approved.
