### ISSUE TITLE
[SoF] S7 Outriding the Outriders: Add map label for outpost

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6159]
version 1.15.18.

See below image:
![image](https://user-images.githubusercontent.com/41433185/136032210-e5c9cb29-5896-4825-9d0a-0394abb955bb.png)
The objective says to reach the outpost, but the outpost is not clearly marked with the term outpost and its terrain even says Encampment rather than Outpost. Most of us will get this, but it might not be clear for some as to what constitutes an "outpost". I propose adding a map label to mark the Outpost.
![image](https://user-images.githubusercontent.com/41433185/136033633-2836f44e-7793-48e7-a735-da95404d5842.png)

The first scenario of SotA also uses a map label, "Lorvin", to mark the town Lorvin, which the protagonist must reach to finish the scenario.

**Comment by max-torch** [comment]
> Seems like you already went to the effort of adding the label yourself, why not just submit it as a PR? (:

The image was just a mockup map label made using "Set Label" in the right click menu while playing. Hence, the player team color on the label. I hadn't yet looked at the code to see how to put a map label when I opened the issue.

**Comment by Wedge009** [comment]
No worries, I realised that afterwards when I saw the label colour was different from the standard blue.

**Comment by cooljeanius** [comment]
let's see what @max-torch thinks

**Comment by max-torch** [comment]
> so that players on harder difficulties are still a bit more confused?
The question is, would being confused, even slightly, be a pleasant experience for the player? For me, it's all about improving the player experience. I would disagree with varying the label, but I will also listen to any counterarguments.

**Comment by cooljeanius** [comment]
ok never mind then
