### ISSUE TITLE
[World Conquest] [1.17] Add one or two Dunefolk-X pair factions into WC era to complete it.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6175]
Currently Proposed/Discussed
 - [x] Dunefolk + Dwarves/KA (The Aristocrats)
 - [x] Duneolk + Northerners (name to be decided)

More proposals:
. - [ ] Dunefolk + Undead 
Note: I did see this suggestion but I do not find this immersive enough in accordance to the lore on the Dunefolk
 - Comment here if you want anymore added in or to be discussed.

**Comment by Wedge009** [comment]
I don't doubt it. I enjoy the lore too, but mainly for SP - I don't really know what the environment is like for MP.
