### ISSUE TITLE
DM S14 Shadows in the Dark: Improve spawning in of Draug and Spectre

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6176]
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

### The Issue
If the player moves a unit too close to the north east enemy leader before Delfador arrives, a Draug and Spectre suddenly spawn. The way they spawn in is sudden and not very graceful. It's awkward.

### To Reproduce
Move a unit to a hex in this range:
```
x=38-52
y=1-5
```

### Proposal
Add some kind of dialog to justify the event. Perhaps when they show up they say "Reinforcements are on the way". Anything to make it less plain.

### Screenshots
See how they suddenly spawn when my Rider moves to the village, and then attack and slaughter him on their turn:
![suddenspectre(4)](https://user-images.githubusercontent.com/41433185/136449176-67a53571-bfbd-4c41-a261-6d69809faff6.gif)
A static image:
![image](https://user-images.githubusercontent.com/41433185/136449485-1a7b1ddb-1f23-4fd2-a420-40c8cb153044.png)

### Savefiles
[DM-Shadows in the Dark replay 20211007-004057.gz](https://github.com/wesnoth/wesnoth/files/7306467/DM-Shadows.in.the.Dark.replay.20211007-004057.gz)

### Additional context
The WML code of the event that spawns the Draug and Spectre:
https://github.com/wesnoth/wesnoth/blob/59e23813d7e2fe24dcf7e1c993a90970768b92ab/data/campaigns/Delfadors_Memoirs/scenarios/14_Shadows.cfg#L316-L335

The purpose of making them spawn in is to (hopefully) prevent the player from accomplishing the scenario objective before Delfador arrives.

**Comment by Wedge009** [comment]
From what I remember in recently replaying the scenario, the expectation is that the player defeats the closer (and weaker) threats to the west first, before going back east by which time Delfador should (hopefully) arrive to lend assistance.
https://github.com/wesnoth/wesnoth/blob/59e23813d7e2fe24dcf7e1c993a90970768b92ab/data/campaigns/Delfadors_Memoirs/scenarios/14_Shadows.cfg#L181-L184

I suppose it can be hard to accommodate players who are exceptionally lucky, aggressive, or in your case, just wanting to capture villages while bypassing enemies. Seems you were ambushed on turn 6 while additional enemies are scripted to arrive on turn 8 and 11, and Delfador only arrives at turn 12.

Regardless, it does seem like a cheap and cumbersome way to block a lucky/aggressive player. I'm reminded of the Wolf Rider ambush when first fighting Rakshas in Northern Rebirth but at least there you had plenty of warning regarding his army's strength. So perhaps the allies somehow discouraging the player from heading to the north-east keep too soon without appearing prescient or, as you suggest, adding some dialogue on the sudden spawn would help.

**Comment by max-torch** [comment]
The bare minimum for a spawn in of units would be a dialog.
