### ISSUE TITLE
AToTB S2 The Chase: Appearance of loyal horseman at the end is abrupt

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6183]
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

### The Issue
When you kill the enemy adept, a loyal horseman suddenly spawns beside your leader and joins the dialog. There doesn't seem to be enough context for a horseman to appear.

### Describe the desired feature
Remove the spawning of the loyal horseman and transfer his dialog to an existing player-owned unit.
– OR –
Make the loyal horseman enter from the side of the map and move up to the player's leader, and tweak the dialog so that it makes sense why this happens.

### Screenshots
You can see the problem with this gif:
![abrupt](https://user-images.githubusercontent.com/41433185/136774508-5bdf2c40-ab13-4ebe-9481-db84035cab03.gif)

### Replay File
[AToTB-The Chase replay 20211009-223750.gz](https://github.com/wesnoth/wesnoth/files/7321672/AToTB-The.Chase.replay.20211009-223750.gz)

**Comment by stevecotton** [comment]
This is the `NEEDS_MERCENARY` macro. It would use a horseman who's already on the map if there was one (excluding Arvith), which is probably why this wasn't noticed before.

I agree that it's a bug.

There are two other places where this macro is used - once at the start of S02 (where it acts as a typical start-of-scenario auto-recall), and once on turn 10 of S01 (where it has the same bug as this).

**Comment by cooljeanius** [comment]
Hm, I guess this is something I'd want to change for [AToTBWaTD](https://github.com/cooljeanius/Two_Brothers_With_A_Third_Difficulty), too...
