### ISSUE TITLE
Problem downloading Wesnoth without enabling all scripts

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#6195]
I'm trying to download the source tarball for Wesnoth (1.15.18) from this URL:

https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.15.18/wesnoth-1.15.18.tar.bz2/download

using Firefox 93.0. The page keeps reloading every few seconds. Only if I disable my ad blocker (uBlock Origin) does the download actually begin. Now, if I then re-enable it, I can still download the file, but initially it fails.

I'm pretty certain his is an issue with SourceForge generally and not Wesnoth-specific.

**Comment by Pentarctagon** [comment]
Closing as invalid since this is an issue with SourceForge and-or Firefox, not with Wesnoth itself.
