### ISSUE TITLE
Issue with UtBS: A Stirring in the Night and the next scenario

### ISSUE THREAD

**Issue by joeljpa** [wesnoth/wesnoth#6199]
* Is the text in English? If not, what language is it in?
Yes.

* What campaign does the text appear in? If it's not in a campaign, say where it is:
UtBS: A Stirring in the Night and the next Descending into Darkness.

* Please quote the text verbatim. You can use `**bold**` to point out the mistaken part:
Per my post and the feedback I got here: https://r.wesnoth.org/t54989

* _(optional)_ What do you propose to change the text to?
I'm going to start with what max_torch said in my forum post: "Perhaps, we could add dialog to the next scenario saying 'oh hey all the terrain here matches the map we found from that orc leader(in the previous scenario)' to make it clearer what the actual benefit was.". 
Additionally, I felt the same thing when I played it for what they said about trying to sneak part. Perhaps after she says 
"Let's see if we can sneak past them", the Goblin rider saying "Intruders! Alert the others and attack" and she saying "I spoke too soon blah blah ". Something like this would remove any idea the player had about sneaking.

**Comment by max-torch** [comment]
> The second, "did not realize his berserk would take effect against enemy leaders!" It was unclear to me how that berserk even applied since the instructions were vague. I discovered by fluke that it triggered on one of the champions. Maybe clearer instructions or dialogue on how it works?

The description that appears when you mouse over 'righteous rage' in the sidebar is super duper clear and even gives the names of the enemy champions.
![image](https://user-images.githubusercontent.com/41433185/140616863-69e7371d-c829-4c9b-942f-6138044a9add.png)

**Comment by joeljpa** [comment]
I did read that as I played but we're talking about it working even against the enemy leaders ie the lich and the death knight, not just the champions. Or am I missing something in the screenshot of the description?

**Comment by max-torch** [comment]
> I did read that as I played but we're talking about it working even against the enemy leaders ie the lich and the death knight, not just the champions. Or am I missing something in the screenshot of the description?

I have a suspicion that maybe the walkthrough is outdated and maybe this has been fixed/changed. I havent confirmed this yet.

**Comment by max-torch** [comment]
@joeljpa If you are around, as the issue author do you have any thoughts on the solution implemented in #6963

**Comment by joeljpa** [comment]
Nice! This solves the map problem we discussed and now it'll be clearer about its use. And some more clarity on whether sneaking up is even an option.
