### ISSUE TITLE
[advancefrom] does nothing in 1.16

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesnoth#6204]
Affects 1.15.18+dev, has been around since before 1.16 beta 1.

`[unit_type] [advancefrom]` in legacy WML such as the following does nothing even though the game purportedly has a compatibility path to make it emit appropriate `[modify_unit_type]` WML during add-on initialization.

```
    [advancefrom]
        unit=Dwarvish Thunderer
    [/advancefrom]
```

The add-on campaign "Invasion from the Unknown" in particular has a Dwarvish Flamethrower unit type which uses `[advancefrom]` to make it a possible advancement from the mainline L1 Dwarvish Thunderer. This works in 1.14 but not 1.16.

(Yes, I realize `[advancefrom]` is deprecated. The point is that it was supposed to be removed in 1.17.x, not 1.15.x, since `[modify_unit_type]` was first introduced in the latter.)

**Comment by stevecotton** [comment]
> So, it looks like there's already some code to handle `[advancefrom]`, including a deprecation warning, but it sounds like it's never triggered or doesn't work?
> 
> https://github.com/wesnoth/wesnoth/blob/57ce449af83f2508f98c2414b1c611131dca5d5e/src/game_config_manager.cpp#L525

That looks for `[units][advancefrom]` rather than `[units][unit_type][advancefrom]`, and fixing it now would mean OOS between 1.16.1 and 1.16.x. Given that it's marked as for removal in 1.17.0 I think we should treat it as already-removed and just print a deprecation message if an `[advancefrom]` is found.

Note for testing: this code block only triggers for add-ons, it doesn't trigger for mainline campaigns; I spent a while trying and failing to trigger it by reverting Dead Water's Kraken.cfg to its 1.14 version.

**Comment by CelticMinstrel** [comment]
Yeah, pretty much.



> The `[modify_unit_type]` config that it generates is also backwards - for example it adds an advancement from L3 Kraken to L2 Cuttle Fish.

It shouldn't be added to either. It needs to be placed in the add-on tag (eg `[campaign`]).

> Given that it's marked as for removal in 1.17.0 I think we should treat it as already-removed and just print a deprecation message if an `[advancefrom]` is found.

I'm not sure. I kinda think that out-of-sync errors to fix a genuine bug may be an acceptable compromise, but this particular bug might just take too much effort to justify it...

**Comment by irydacea** [comment]
`[advancefrom]` by definition caused OOS, which is why this whole alternative system was invented. With that in mind, plus the fact that it's been completely nonfunctional for several versions including 2 maintenance releases, I will insist on my original suggestion (also from chat) to simply mark it as removed in 1.16.0.
