### ISSUE TITLE
UtBS: Keep race of Dark Assassin hidden from the player

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6213]
### Game and System Information
 - 1.15.18
 - Steam
 - Windows 10

### Describe the desired feature
Display the race of the Dark Assassin as ?????, at least until it is revealed that the assassin is an elf.

### Rationale
In the story, the characters (and supposed to be the player as well) get surprised when they discover that the assassin is an elf. However, the player can already know that the assassin is an elf from seeing the Race as Quenoth Elf in the sidebar and in the Help Encyclopedia Unit Description.

### Screenshots
This is supposed to be a surprise reveal:
![image](https://user-images.githubusercontent.com/41433185/138067768-f9de0675-2c96-4e53-b2e8-9595af694190.png)
But it's not because of this:
![image](https://user-images.githubusercontent.com/41433185/138067935-ccf225c7-c401-4fa4-862f-4c2277bcc982.png)
and this:
![image](https://user-images.githubusercontent.com/41433185/138068116-99d4577a-a89c-46f9-8518-36209144fdc1.png)

**Comment by stevecotton** [comment]
Thanks for logging this, I should have logged it when I opened #5151 (which changed every unit_type mentioned in this comment from `elf` to `quenoth`).

> For a few of these, I think another race might be better - they're converted to
> Quenoth here, as they were Elves before. The Corrupted Elf is should probably be
> considered undead, and the Divine Avatar should possibly be something else, more
> like an elemental than a living creature. That those two are currently included
> in the elves does have the side-effect of hiding a plot spoiler about the Dark
> Assassin who is also included in the elves (the spoiler being that this one is
> correct, he really is an elf).
