### ISSUE TITLE
[WC2] Potential bug in carryover mechanic

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#6216]
I came along this comment:
> NOTE: this is a bit fragile, in particualr it breaks if difficulty_selection happens before the prestart event above.
https://github.com/wesnoth/wesnoth/blob/1.16/data/campaigns/World_Conquest/lua/campaign/scenario.lua#L66

Since it is now a campaign, difficulty selection happens before the game starts. Unclear whether it currently works correctly.

**Comment by knyghtmare** [comment]
I was playing it earlier today and it was working fine for me

**Comment by Wedge009** [comment]
Just trying to understand: is the question resolved? If so, can it be closed? If not, should it be updated to an enhancement?
