### ISSUE TITLE
"Show joins of friends only" does nothing

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#6234]
### Game and System Information
 - 1.16
 - Steam
 
### Describe the bug
"Show joins of friends only" selected in Multiplayer settings does nothing and still shows all lobby joins.

### To Reproduce

1. Set "Show joins of friends only" selected in Multiplayer settings
2. Create a game lobby (do not start the game)
3. Watch lobby messages

### Expected behavior
I only get messages about friends joining.

**Comment by amokmen** [comment]
>shows all lobby joins

Very annoying, actually. This spam almost flooding useful messages.
