### ISSUE TITLE
How to use Preference -> Display -> Theme?

### ISSUE THREAD

**Issue by jurisbu** [wesnoth/wesnoth#6238]
### Game and System Information
- Version 1.16
- From Steam
- On Arch Linux

### Describe the desired feature
Absolutely new to this game, so pardon if this is obvious. I noticed there is a possibility to load Theme ... supposedly. Under Preferences -> Display -> Theme. But I cannot find any information on where and how would one get new themes. Is it even possible?

The main use case for me is that I hope that some themes would have larger text/fonts than default theme/looks. For me it is hard to read default fonts.

**Comment by Pentarctagon** [comment]
Closing as the question has been answered.
