### ISSUE TITLE
[World Conquest] [MP] [1.17] Feature Request: Monster units recruits as Enemies

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6243]
### Describe the desired feature
It has been brought to my attention that the world conquest [WC] player base would like to have monster units added into the enemy array. Thus, I am opening up discussions here. 

This can be done in one of two ways:
1. For the enemy data, add in Tamers (Ranger/Huntsmen/Dune Sky Hunter) and their level 2s as leaders and commanders while the recruitment lists would be consisting of Monster units.
2. An enemy array purely of monsters with "intelligent" monsters such as the Fire Dragon taking up the role of enemy leaders, and maybe some lesser monsters such as Wild Wyverns becoming commanders.

I am opening this Issue to start discussions and how this can be approached.

**Comment by knyghtmare** [comment]
No response for over a year. So, I infer that this is either not required or there is no demand for it.

**Comment by CelticMinstrel** [comment]
That said, if someone were to do the work to implement this, I believe it has a high chance of being merged, right?

**Comment by knyghtmare** [comment]
with all due respect, the monster unit faction would be a mismatched and hugely unbalanced mess. Also, some advancements need to be enabled by default like the wolves otherwise this faction is a freebie. There's also the case of some monster units of level 2 with level 3 stats. They have to be rectified/re-adjusted.

I dont really see this happening (I mean I have left it open for a year so zero responses proves it's not desired)
I even asked on the forum thread and nobody cared.  If someone else wants to do it, go right ahead.
