### ISSUE TITLE
1.16.0 wesnothd.exe can not run because could not find libboost_coroutine-mt.dll

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#6245]
### Game and System Information
1.16.0
Website
Win10

### Describe the bug
**wesnothd.exe** can not run because could not find **libboost_coroutine-mt.dll**.

**Comment by Wedge009** [comment]
I believe @loonycyborg already resolved this with 9a1b4caa5574a5f914dd1a8b16fd3d3ffef066d1 but I don't think it's been pushed to general public yet (eg I don't have the issue when building Wesnoth myself). It's also been reported elsewhere such as in `#wesnoth-dev` and the forums, but for some reason we didn't log an issue for it here.

I understand 1.16.1 is scheduled for release in about a week.

**Comment by Wedge009** [comment]
Here's the forum report, it includes a manual work-around: https://forums.wesnoth.org/viewtopic.php?t=55017

**Comment by Wedge009** [comment]
1.16.1 just released, no longer an issue.
