### ISSUE TITLE
Make it possible to see the real add-on ids in the Add-ons Manager

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesnoth#6255]
As the subject says, since right now it's pretty much impossible to find out the id of an add-on without downloading it, or changing log levels and then interacting with it in some specific way other than looking at its info on the UI.

(Perhaps hide them behind debug mode?)

**Comment by haytham-med** [comment]
Hi, what do you want id for?
it's usually used for porting

**Comment by soliton-** [comment]
You need the ID for lots of interactions with the addon. Finding it in the filesystem, most commands for campaignd, using data/tools/wesnoth_addon_manager, etc.

There is no real way to identify an addon if the author changes the title for example or should two addons have the same icon, title, version etc. (all properties that can be chosen freely and need not be unique)...

The ID doesn't need to be prominently visible but it should be accessible somewhere (not behind debug mode IMO).

**Comment by zishiwu123** [comment]
I'm not sure if this would be a good idea, but would it be possible to make a request to the add-on server for a list of all the add-on ids (and other info about the add-ons that might be needed)? Then store this in a add-ons.json file. When the game loads, it can check if this file exists already. If not make the request to get the data and create the file.

**Comment by Pentarctagon** [comment]
While that may be useful for something else to consume, the request here is simply to display the ID on the UI in the in-game add-ons manager.

As a side note as well, Wesnoth doesn't currently have any ability to write out in the JSON format - it uses WML (Wesnoth Markup Language), though the [wmlparser3](https://github.com/wesnoth/wesnoth/blob/master/data/tools/wesnoth/wmlparser3.py) script can convert to JSON (and XML).

**Comment by cooljeanius** [comment]
> (Perhaps hide them behind debug mode?)

Or an advanced preference?

**Comment by binarydigitz01** [comment]
I would like to work on this. Personally I feel that we can have the ID along with website, dependencies column.

**Comment by soliton-** [comment]
Feel free to make a pull request.
