### ISSUE TITLE
SotA S20: Teleporting Berserker in scripted event

### ISSUE THREAD

**Issue by dsime42** [wesnoth/wesnoth#6257]
SotA - S20 (North Knalga)
1.15.17 (Difficult)
Fedora release 33 
Linux 5.13.19-100.fc33.x86_64

So I'm playing this scenario and when I get to the Dwafish Throne room (or where ever that is) and Golbanduth says 
"The invaders approach! Fetch the last chest o' gold. We're equipin' more soldiers"
Then Trimalalfur jumps down runs over to a locked gate and retrieves a chest.
At this point the king starts, when it is his turn, to recall a bunch of troops.

So I loaded it up a few plays prior to entering the room and send three Spectres down the back route, West side, while the liches just hang out at the entrance killing any uppity  dwarves that drop by to do battle.

When the Spectres are at the back West entrance I move them along the wall to block the locked gate. With my Spectres in place at 15,33 16,33 and 17,33, I walk a lich into the room and yup Golbanduth makes his request and Trimalalfur complies.

I was fine with that because I thought my Spectres would be able to hold the Derserker out of the gold room and Golbanduth would have to make do with the troops he had. !!! :-)

Imagine my surprise when Trimalalfur stops on 15,32 and doesn't attack my Spectre but rather unlocks the gate, located at 16,34 - must have been a LONG key, and then walks right through my Spectre grabs the gold box and takes it back to Golbanduth!
Not so much as a by-your-leave to my line of malevolent, and very dangerous, UnDead.
Please also note that Trimalalfur has 5 movement points but manages to move 7 hexes to my Spectre where he unlocks the gate, 8 more to get the gold chest and exit the gold room and then another 6 to get back to Golbanduth.

and just in case you were wondering 7+8+6 <= 5 is not a True statement

**Comment by max-torch** [comment]
I would surmise that the author does not want, in any circumstance, for there to be a way to block the dwarves from getting their gold boost. I take it that's what the OP was trying to do.

What I can say at the moment is that if we resolve this issue we have to make sure it's in a way that dwarves still get their gold.

**Comment by knyghtmare** [comment]
>This event fires when the king sees a unit approaching the castle, and he
        is alerted that he needs more units. We want the player to be able to see
        the king while he talks about this, so that's what we're actually going to
        check: That a player's unit can see the side-2 leader. We can't use
         "sighted" for this because that only works when a unit is revealed for the
         first time, and the king may have already been revealed by a shadow or other
         hidden unit. (But, of course, the king wouldn't have been alerted in that
         case.) We fire a custom event to have the king open another chest of gold.

https://github.com/wesnoth/wesnoth/blob/ee233cead6e2335ea71d5bf6b03bc6de024a2bd7/data/campaigns/Secrets_of_the_Ancients/scenarios/21_Against_the_World.cfg#L3-L7

SotA has been infamous for having fail-safe code to prevent players from employing dirty tactics such as the ones mentioned in the previous comment. 
For this issue, an event can be scripted in for checking if the vault is locked, if it is...moving the chest-opener to another or a third fall-back chest location.

**Comment by dsime42** [comment]
code to prevent players from employing dirty tactics such as the ones mentioned in the previous comment.

Me using "dirty tactics?
I'm not the one who gives the opponent more troops than I have at a point in the scenario when I only have three turns to end it?
**That is the Drity Trick**

**Comment by max-torch** [comment]
> code to prevent players from employing dirty tactics such as the ones mentioned in the previous comment.
> 
> Me using "dirty tactics? I'm not the one who gives the opponent more troops than I have at a point in the scenario when I only have three turns to end it? **That is the Drity Trick**

Yes, it is a tomato surprise to see that the enemy will suddenly have more gold. Not the worst of tomato surprises mind you, but unforeseeable nonetheless. It's completely normal to feel that way and there is in fact a debate about whether any form of tomato surprise is allowed, or what degree of severity tomato surprises are allowed.

This is actually part of the inspiration of my plan for making a ["Before you Play" Series](https://forums.wesnoth.org/viewtopic.php?t=54890). To inform players of the design style and philosophy of a campaign, including severity of tomato surprise, so they know if its for them and what to expect.

**Comment by dsime42** [comment]
I figured it out
I just needed to type in these three lines before starting the scenario

VER="1.15"; DIR="${HOME}/.local/share/wesnoth/${VER}/saves/"

cd ${DIR}; mv SotA-North\ Knalga.gz SotA-North\ Knalga-saveme.gz

zcat SotA-North\ Knalga-saveme.gz |sed -e 's/gold=-/gold=20/' -e 's/previous_recruits="C/previous_recruits="Spectre,Nightgaunt,C/' |gzip > SotA-North\ Knalga.gz

Very helpful
Got down to the Keep with good rapidity and when Golbanduth got his gold I was able to put a Nightgaunt on every open recall spot. I was even able to finish 5 whole turns early!!!

There are some tricky triggers on the floor though where even hidden units are seen
I'm going to use this method a lot more now as it makes the whole scenario Much More FUN

**Comment by max-torch** [comment]
I move to just close this and mark this as a case of WINR (Wesnoth Is Not Realistic). Anyone in favor?

**Comment by Wedge009** [comment]
Yeah, let's close this. Scripted events to force certain things happen in all sorts of games, not just Wesnoth. Foreknowledge can sometimes help us stall things, but not always. Also, this is an old issue.
