### ISSUE TITLE
Add a composite hero/leader ellipse

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#6258]
If an add-on author tries to use `{IS_HERO}` or the ellipse `misc/ellipse-hero` for a unit with `canrecruit=yes`, they end up getting messages like `error display: could not open image 'misc/ellipse-hero-leader-top.png'`. (I have had this happen to me before myself.) Technically this is Wesnoth just doing what it's told, so there's no need to change any code here, but it *would* be useful to at least add a composite ellipse with that path for this particular case, at least IMO.

**Comment by knyghtmare** [comment]
> If an add-on author tries to use `{IS_HERO}` or the ellipse `misc/ellipse-hero` for a unit with `canrecruit=yes`, they end up getting messages like `error display: could not open image 'misc/ellipse-hero-leader-top.png'`. (I have had this happen to me before myself.) Technically this is Wesnoth just doing what it's told, so there's no need to change any code here, but it _would_ be useful to at least add a composite ellipse with that path for this particular case, at least IMO.

I have had this issue the most in my campaign for the first arc. Previously, in 1.10/1.12 series, it was possible to have both, with the hero icon being overlayed on top of the leader icon.

**Comment by cooljeanius** [comment]
> I have had this issue the most in my campaign for the first arc. Previously, in 1.10/1.12 series, it was possible to have both, with the hero icon being overlayed on top of the leader icon.

Hm, do you think you could bisect to find which commit changed this?

**Comment by doofus-01** [comment]
> I have had this issue the most in my campaign for the first arc. Previously, in 1.10/1.12 series, it was possible to have both, with the hero icon being overlayed on top of the leader icon.

I believe this is for the ellipse (side-colored things on the ground), not icons (the little floating gold/silver trinkets).  

Maybe a hack, but simply copying the leader ellipse images and calling them "ellipse-hero-leader" should work.  Any reason not to do that?

**Comment by cooljeanius** [comment]
> > I have had this issue the most in my campaign for the first arc. Previously, in 1.10/1.12 series, it was possible to have both, with the hero icon being overlayed on top of the leader icon.
> 
> I believe this is for the ellipse (side-colored things on the ground), not icons (the little floating gold/silver trinkets).
> 
> Maybe a hack, but simply copying the leader ellipse images and calling them "ellipse-hero-leader" should work. Any reason not to do that?

Let's ask @irydacea

**Comment by cooljeanius** [comment]
> > > I have had this issue the most in my campaign for the first arc. Previously, in 1.10/1.12 series, it was possible to have both, with the hero icon being overlayed on top of the leader icon.
> > 
> > 
> > I believe this is for the ellipse (side-colored things on the ground), not icons (the little floating gold/silver trinkets).
> > Maybe a hack, but simply copying the leader ellipse images and calling them "ellipse-hero-leader" should work. Any reason not to do that?
> 
> Let's ask @irydacea

(it works perfectly fine when doing so as part of an add-on, btw)

**Comment by CelticMinstrel** [comment]
I think it would also be perfectly acceptable to just duplicate the regular leader ellipse for this.
