### ISSUE TITLE
Nickname tab autocompletion of players' nicks in lobby chats doesn't work and causes crashes

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6263]
### Game and System Information
 - What version of the game are you running? Tried 1.16.0 and 1.17.0-dev from flatpak and 1.16.0 built from sources from 91d1296af933409c4abdaf423de885c4928b423c
 - What OS are you running? Ubuntu 20.04

### Describe the bug
When you press Tab to autocomplete a player's nickname in mp lobby chats:

if you do it in the main lobby chat, it does nothing

if you do it in a private chat with some player, it crashes with SEGFAULT

### To Reproduce

1. Enter the MP lobby
2. Start typing first letters of some nick who is online
3. Press Tab

**Comment by Wedge009** [comment]
The 'steps to reproduce' miss the aforementioned detail about doing this in a private chat, not the lobby. But otherwise confirmed.

Not sure if related to, or a super-set of, #3729.

**Comment by Discontinuum** [comment]
I wouldn't say they miss it, because if you do that in the lobby, it does nothing which is also incorrect behaviour (it should autocomplete, as it is in 1.14). But if you're talking about crash, then yeah, a private chat

**Comment by Wedge009** [comment]
Specifically referring to the crash.

https://github.com/wesnoth/wesnoth/blob/e4497ba160b35e9623b598455a0441f34c39e586/src/gui/widgets/chatbox.cpp#L177-L185
`t.name` is 'lobby' when in the lobby, but is the name of the recipient if in a private chat tab. When it is 'lobby' `get_room()` returns a valid `room_info` object so there is no crash (even if the functionality doesn't work as expected). However, if the `t.name` refers to an individual recipient as for private chats then `get_room()` returns `null` which results in the crash when entering the `for` loop.

@Vultraz This seems to have been introduced with your commit 6b21233c44a39b4bcd5bc1462e6e01394e79d6e4 which was included from 1.15.7 onwards. Do you have any advice, please?

**Comment by Wedge009** [comment]
Additionally, when `t.name` is 'lobby', it doesn't look like there is anything returned by `members()`, so there is nothing in `matches` and so auto-complete appears to 'doesn't work'.
