### ISSUE TITLE
UtBS S1 replay has OOS after accomplishing final objective

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6265]
### Game and System Information
 - Watching replay on 1.16.0, and replay is from 1.15.17
 - Steam
 - Windows 10

### Describe the bug
Out of Sync Error is thrown when watching the replay after the final objective is accomplished.

### To Reproduce

1. Watch a replay of UtBS S1 until the end

### Expected behavior
No OOS error.

### Screenshots
![image](https://user-images.githubusercontent.com/41433185/140616426-43416bb0-6ab9-41de-97ce-663da1fd26ec.png)

### Savefiles
[UtBS-The Morning After replay 20210926-171058.gz](https://github.com/wesnoth/wesnoth/files/7490838/UtBS-The.Morning.After.replay.20210926-171058.gz)

### Additional Context
I also tried this on 1.16 but using debug so that I go to the end right away. Here's the replay just skip through all the debug complaints.
[UtBS-The Morning After replay 20211107-002444.gz](https://github.com/wesnoth/wesnoth/files/7490854/UtBS-The.Morning.After.replay.20211107-002444.gz)

**Comment by gfgtdf** [comment]
This is probably fixed on master

**Comment by Descacharrado** [comment]
> This is probably fixed on master

Tested, it is. Thanks!
