### ISSUE TITLE
UTBS S4 Descending Into Darkness: Improve trigger of "how can he move fast" dialog

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6266]
### Game and System Information
 - Scenario was played in 1.15.18
 - Steam
 - Windows 10

### Describe the desired feature
Currently, when any of the player's units proceed to attack the enemy Direwolf Rider Leader, Kaleh says
https://github.com/wesnoth/wesnoth/blob/ee233cead6e2335ea71d5bf6b03bc6de024a2bd7/data/campaigns/Under_the_Burning_Suns/scenarios/04_Descending_into_Darkness.cfg#L605

The current timing looks like a delayed reaction. He has already seen the Rider move fast but is only commenting on it late. I think it would be an improvement if the dialog also triggers the first time the Direwolf Rider moves to attack one of the player's units.
It is explained later lorewise that the Rider was unnaturally fast because he had a ring that gave him an additional 1MP.

### Screenshots
The timing of the dialog is... unnatural
![image](https://user-images.githubusercontent.com/41433185/140617494-b63b1578-0063-437b-81f8-051cec8282f7.png)

### Replay
[UtBS-Descending into Darkness replay 20211005-023011.gz](https://github.com/wesnoth/wesnoth/files/7490889/UtBS-Descending.into.Darkness.replay.20211005-023011.gz)

**Comment by knyghtmare** [comment]
> him an additional 1MP

Hardly seems unnatural. Maybe the attack event can be changed for an "exit_hex" event with the starting co-ordinates of his keep?

**Comment by max-torch** [comment]
> > him an additional 1MP
> 
> Hardly seems unnatural. Maybe the attack event can be changed for an "exit_hex" event with the starting co-ordinates of his keep?

I think this will not do because there are times when the Direwolf Rider moves out of the keep to capture villages while he has not yet been discovered by the player.
![image](https://user-images.githubusercontent.com/41433185/140618631-5ee29378-d9e6-4dff-ab8c-88c614d04c28.png)

**Comment by knyghtmare** [comment]
> while he has not yet been discovered by the player.

Ah, right..I forgot to life the shroud from the surface region, I have to get that conditional to true in the previous scenario (that is, nab the map).

Perhaps switching on a conditional when he is sighted and then triggering event only when conditional holds true?

**Comment by max-torch** [comment]
> Perhaps switching on a conditional when he is sighted and then triggering event only when conditional holds true?

Could be... Anyhow, I'll help whatever PR gets made for this.

**Comment by knyghtmare** [comment]
> > Perhaps switching on a conditional when he is sighted and then triggering event only when conditional holds true?
> 
> Could be... Anyhow, I'll help test whatever PR gets made for this.

Upload the start of scenario save file here. Would be easier for me to make a patch if I had a testing save available.

**Comment by max-torch** [comment]
> Upload the start of scenario save file here. Would be easier for me to make a patch if I had a testing save available.

[UtBS-Descending into Darkness.gz](https://github.com/wesnoth/wesnoth/files/7491006/UtBS-Descending.into.Darkness.gz)

**Comment by Wedge009** [comment]
I also just noticed this issue while playing this scenario today (1.16.1 release). Looks like it was only introduced in 1.9.1, so it wasn't in 1.6 when I last played this campaign. I understood afterwards that it's meant to make it clear that the goblin leader is special, dropping the ring as a bonus. As it stands, it does feel like a clumsy way to point out the bonus so it'd be nice to present it in a better way but it's hardly a show-stopping issue.
