### ISSUE TITLE
Add-ons server keeps undefined properties at their previous value upon update

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#6284]
### Game and System Information
 - What version of the game are you running? wesnoth_addon_manager version 170ec9ba139e240ddbb445e102c6112a2ea6b6fd  2021-09-25
 - Where did you download it from? `git clone`
 - What OS are you running? ArchLinux

### Describe the bug
Context: I have an add-on (Creep_Wars_Dev) that I try to update. It previously had a dependency on `pick_advance`, and now I want to remove it as it's a built-in wesnoth dependency now.

The bug happens when I update the add-on using wesnoth_addon_manager. I'm using this _server.pbl: https://github.com/vgaming/CreepWars/blob/8a417ccf1ec12e589079845674490165d7ff82f3/Creep_War_Dev/_server.pbl  which has no `dependencies` defined.
When I update my addon, the add-on store says that my addon is accepted. The version is updated accordingly, as seen in the game client. **However, the dependency does not get removed and remains to be the old one**.

In other words, updating an addon with not-specified `dependencies` did not cause removal of the dependencies. The only thing that worked was to submit this update: https://github.com/vgaming/CreepWars/commit/1d2358c492052e3f3ab416e26fe23545dedc1719  after which everything worked as expected

### Steps To Reproduce

1. Create a new add-on with a dependency specified
2. Use wesnoth_addon_manager to publish the addon
3. Remove the dependency from the add-on
4. Update the addon
5. Observe from the game client that the add-on still requires the old dependency

### Expected behavior
After publishing an add-on that **does not specify** any dependencies, dependencies should be removed by the addons server

### Screenshots
![2021 11 11_18:35:46e](https://user-images.githubusercontent.com/33452702/141343518-ce960c89-1198-46a7-8c2d-c9b412ea6b91.png)

**Comment by soliton-** [comment]
Official add-on server instances have been restarted with the fix.
