### ISSUE TITLE
Multiplayer scenarios with custom terrains don't load for non-host players and observers

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6285]
### Game and System Information
 - What version of the game are you running? 1.16.0 on flatpak on Ubuntu 20.04, my friends used Steam on Windows

### Describe the bug
When you start a game in a multiplayer scenario with custom terrains, other players (not the host) see an error window "the map could not be loaded: Unknow tile in the map <some custom terrain id>" and fail. The host, on the other hand, works fine. The same error sees everyone trying to observe such a game. (NB: all the folks have the same version of the addon in question)

### To Reproduce

1. Install any addon with a multiplayer scenario with custom terrains
2. In the lobby Create Game > Scenarios, choose a scenario in question
3. Either start a game with several people or start the game alone and let other people try to observe this game

Addons and scenarios you can try (from the 1.16 addon server): Era of Magic and scenario EoMa 4p - Zombies Challenge; Legend of the Invincibles (beta) and scenario LotI - Gladiators

### Screenshots
![GladiatorsRIP](https://user-images.githubusercontent.com/68666085/141369460-cdcade8f-559f-4049-8536-6c7364f97c77.png)
What you see for non-host players/observer in LotI - Gladiators

![ZCbug](https://user-images.githubusercontent.com/68666085/141369515-a4f94cf5-11c2-4d41-85dc-f965a8c34ed1.png)

What you see in EoMa Zombies Challenge

### Additional context
Dunno if the bug is applicable to other things (campaigns, mp campaigns, etc), only tested for separate mp scenarios

**Comment by Wedge009** [comment]
Maybe not relevant, but I've seen unknown tile error messages even just from browsing the MP lobby (from testing work - I don't use MP). I just assumed someone has set-up a game with custom terrains that my client doesn't recognise when generating the previews in the lobby.

**Comment by Discontinuum** [comment]
Atlaz Mariners campaign is played a lot... It's an MP campaign, and I believe with custom terrains. So it seems campaigns unaffected, but single scenarios are

**Comment by knyghtmare** [comment]
Normally, this is avoided by having:
```
require_scenario=yes
```
In the add-on scenario file to ensure the terrain codes are installed for everyone.

**Comment by Discontinuum** [comment]
> Normally, this is avoided by having:
> 
> ```
> require_scenario=yes
> ```
> 
> In the add-on scenario file to ensure the terrain codes are installed for everyone.

It doesn't work even when the scenario and its dependencies installed for everyone, that's the problem

**Comment by Pentarctagon** [comment]
A simple add-on to allow reproducing the issue: [test.zip](https://github.com/wesnoth/wesnoth/files/7677961/test.zip)

Does anyone know when this started happening in 1.15?

**Comment by Pentarctagon** [comment]
Looks like the first bad commit is 5759404121215730cbd4ec899061317923e0ec6e

**Comment by CelticMinstrel** [comment]
I'm kinda confused… why is that the fix? Based on the commit message for 5759404, it seems like the `[terrain_type]` tags should be picked up as long as they are in the same add-on as the scenario being played. Or is one add-on using a terrain from another add-on?

**Comment by Pentarctagon** [comment]
It looks like `entry_tags` are the top-level tags that get used in a game for active add-ons, not just everything.

**Comment by ProditorMagnus** [comment]
Then shouldnt [language] for example also be in this list?

**Comment by Pentarctagon** [comment]
I'm not familiar with what [language] does.

**Comment by Pentarctagon** [comment]
Also to be honest, I'm not sure why [terrain_type] specifically is a problem. There are other top-level tags such as [units] that are clearly not affected by this issue.

**Comment by CelticMinstrel** [comment]
> It looks like `entry_tags` are the top-level tags that get used in a game for active add-ons, not just everything.

Is that what it was? I didn't look at the implementation, but from the set of tags that was in there before, it seemed like the logic was intended to be something like this:

1. For each tag on that list that's part of the active game, grab the add-on it's loaded from. So, this gives you a list of add-ons.
2. Copy _everything_ from each of those add-ons into the information that's sent from the host.

But again, I didn't even look at the code, so this is just my assumption… maybe I'm wrong? Still, it does seem like a logical way to do it…

**Comment by Pentarctagon** [comment]
It's quite possible I misunderstood the logic as well - I haven't spent much time reading the code there yet, I just confirmed that the change in the PR does fix the issue.

**Comment by ProditorMagnus** [comment]
[language] is used to define names to custom damage types and ranges.

**Comment by stevecotton** [comment]
@Discontinuum for EoMa 4p - Zombies Challenge, I can replicate this when using an era other than EoMa, but when I choose EoMa as the era then it works OK. Does that match what you're seeing?

More details about my testing: https://github.com/wesnoth/wesnoth/pull/6373#issuecomment-990784486

**Comment by Discontinuum** [comment]
@stevecotton Yes, with EoMa okay, with other eras doesn't work

**Comment by Pentarctagon** [comment]
After some investigating, it looks like the real root of the issue is that Wesnoth tries to enable content based on the scenario ID in https://github.com/wesnoth/wesnoth/blob/d9f6c3616b82023344c89e458a279d7c00a2304f/src/game_config_manager.cpp#L750
For the host this works fine because it already knows the scenario ID. However the client doesn't know the scenario ID when it joins and tries to enable the required content - it only gets told the scenario ID after the start button is pushed.

So when the client goes to get the scenario ID in https://github.com/wesnoth/wesnoth/blob/master/src/saved_game.cpp#L648-L664 on joining, it returns the value from line 655, which is just an empty string. When using the example test scenario I posted above, if I hard-code line 655 to the value of `"test"`, then I no longer get the unknown terrain error.

So it looks like in MP the server needs to tell the host what the scenario ID is when joining the game rather than when starting the game.

**Comment by stevecotton** [comment]
It sounds as if multiplayer has two different pieces of code handling the add-on list, and that they should be connected to each other:

* One that's used for starting the game
* One that's used in the lobby display
![image](https://user-images.githubusercontent.com/101462/146132957-1a5e7366-3f02-403c-a99d-fa67f259f981.png)

> So it looks like in MP the server needs to tell the host what the scenario ID is when joining the game rather than when starting the game.

I haven't tested, but will that work with `require_scenario=no`? I suspect the edge-case of SXC maps that want Ageless units will fail when the players choose an era other than Ageless (currently those maps just use `allow_era=` to force something compatible).

**Comment by Pentarctagon** [comment]
> I haven't tested, but will that work with require_scenario=no? I suspect the edge-case of SXC maps that want Ageless units will fail when the players choose an era other than Ageless (currently those maps just use allow_era= to force something compatible).

No idea - I don't have a fix for any case yet.

**Comment by Pentarctagon** [comment]
Also, I'm not clear on how that would work anyway? If a scenario tries to spawn Ageless Era units, and a player doesn't have Ageless Era installed, then it wouldn't have ever worked I would think?

**Comment by stevecotton** [comment]
The other players would need to have Ageless Era installed, but wouldn't need to have SXC installed.

**Comment by ProditorMagnus** [comment]
SXC is supposed to use [load_resource].

**Comment by Discontinuum** [comment]
> It sounds as if multiplayer has two different pieces of code handling the add-on list, and that they should be connected to each other:
> 
> * One that's used for starting the game
> * One that's used in the lobby display
>   ![image](https://user-images.githubusercontent.com/101462/146132957-1a5e7366-3f02-403c-a99d-fa67f259f981.png)

When hosting a game, there are two blocks which I have to fill: mods used and addons required to have downloaded. Here, Afterlife's mods don't require to be downloaded by the player, as they are inlined and don't have external resources like images

**Comment by stevecotton** [comment]
> SXC is supposed to use [load_resource]. ProditorMagnus/Ageless-for-1-14#27

Sorry, the example I used has accidentally brought a separate issue into the mix; it's true that I should do that to re-enable mixing eras. The point that I was trying to make was:

> So it looks like in MP the server needs to tell the host what the scenario ID is when joining the game rather than when starting the game.

At that stage, the other clients might not have the WML for the scenario. I haven't tested when it gets sent.

**Comment by Pentarctagon** [comment]
I don't believe that [terrain_type] gets sent by the server, since it's not part of any scenario. So I would think that add-ons that define their own custom terrain wouldn't work regardless if they set `require_scenario=no`? Any image files definitely don't get sent.

**Comment by Pentarctagon** [comment]
I've gotten side tracked by something else for a bit, but it sounds like there's essentially two related issues:
* When a player joins a game, their client hasn't been told of the scenario ID of the scenario that's going to be played. This results in their client not knowing that it needs to enable the add-on which that scenario is from, which results in the unknown terrain errors. The solution for this one is to add the scenario's ID to be part of the information sent by the server in https://github.com/wesnoth/wesnoth/blob/ed482c1feb2d9fcfd37cb3dcfee00da822f7c174/src/gui/dialogs/multiplayer/mp_join_game.cpp#L87 on joining. Then in `get_scenario_id()` use that value instead if `carryover_["next_scenario"].str()` is an empty string.
* The addon containing the era to be used is also not enabled.

**Comment by Discontinuum** [comment]
> I don't believe that [terrain_type] gets sent by the server, since it's not part of any scenario. So I would think that add-ons that define their own custom terrain wouldn't have worked previously if they set `require_scenario=no`? Any image files definitely don't get sent.

Legend of the Invincibles (beta) and LotI - Gladiators. The custom terrain and the scenario is in the same addon, still doesn't work. Added require_scenario, still doesn't work (although it required LotI even without require_scenario somehow)

**Comment by Pentarctagon** [comment]
It looks like actually all the required information is already sent, since it's what's used by the server to insert the add-on information for each game into the database.  So `level_` after https://github.com/wesnoth/wesnoth/blob/c21dfcaeb4a5cadf9bfa291353f474181bd15a4d/src/gui/dialogs/multiplayer/mp_join_game.cpp#L111 would contain ie:
```ini
[addon]
	id = mainline
	name = mainline
	require = no
	version = 1.17.0-dev
	[content]
		id = plan_unit_advance
		name = Plan Unit Advance
		type = modification
	[/content]
	[content]
		id = era_default
		name = Default
		type = era
	[/content]
[/addon]
[addon]
	id = test
	name = test
	require = no
	version = 0.0.0
	[content]
		id = test
		name = test
		type = scenario
	[/content]
[/addon]
```
So it should just be a matter of taking that information and using it/passing it along as needed.
