### ISSUE TITLE
Impossible to join games on server2.wesnoth.org due to registered user requirement

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesnoth#6287]
Creating games on `server2.wesnoth.org` (1.16 instance) seems to only create games that require players to be registered and identified, even though the server instance does not support player registration at all due to technical limitations. When attempting to join a newly created game, the server responds with "Only registered users are allowed to join this game". There isn't a visible option in the UI to toggle, so I'm not sure if the bug is on the client or the server side.

(Current as of 1.16.1.)

**Comment by soliton-** [comment]
Looks like the git checkout on server2 is messed up. git describe says it's current but it's really 1.15.5... I'll try to figure out what's going on and build a proper wesnothd.

**Comment by soliton-** [comment]
A properly uptodate wesnothd 1.16 instance is now running on server2.
