### ISSUE TITLE
Regex processing during MP server connection takes excessively long time with CJK languages

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6291]
Reporting on @fujimo-t's behalf (at least I think it is their report) from #wesnoth-dev discussion at 2021-11-14 ~02:30-03:00 UTC.

### Game and System Information
Official Windows 1.16.1 release

### Describe the bug
Connection to MP server appears to hang when Japanese or Chinese language is selected. (2021-11-21 update: it just takes an excessively long time.) Seems only applicable to Windows build, official Linux release does not exhibit this problem.

### To Reproduce
1. Start Wesnoth 1.16.1 on Windows
2. Select Japanese language
3. Log-in to official MP server
4. Observe the connection screen remains indefinitely (does not even reach the enter credentials stage).

### Expected behaviour
Successful log-in to MP server in a 'reasonable' time (eg within a minute).

### Additional context
I have confirmed this, though have not yet tested any versions besides official 1.16.1 releases, nor any other languages besides `en_GB`.

2021-11-21 update: appears to be an upstream bug in regex handling.

**Comment by fujimo-t** [comment]
Thank you for open this issue.

I can reproduce it by self-build according to the [make_mingw_build](https://github.com/wesnoth/wesnoth/blob/master/utils/dockerbuilds/make_mingw_build) script but can't by Visual Studio + vcpkg.
(Both source is same 1.16.1 tag.) 

I built by the mingw with debug option and confirmed "Invalid parameter" messages repeated many time while the hanging.
[invalid-parameter-messages.txt](https://github.com/wesnoth/wesnoth/files/7533178/invalid-parameter-messages.txt)

Then I set a breakpoint on _invalid_parameter, It seems the message is from std::regex constructor in src/utils/parse_network_address.cpp.
[backtrace.txt](https://github.com/wesnoth/wesnoth/files/7533183/backtrace.txt)

**Comment by Pentarctagon** [comment]
What's the value of the `address` argument when this is happening?

**Comment by fujimo-t** [comment]
From backtrace.txt:
> #26 0x000000000073abd5 in parse_network_address (address="add-ons.wesnoth.org", default_port="15016")
    at /wesnoth/src/utils/parse_network_address.cpp:24

It seems no problem.

**Comment by Wedge009** [comment]
I confirm 1.16.1+dev build compiled with MSVC does not exhibit the issue. I even tested both with and without generated `mo` translation files, both log-ins were successful.

It seems like the inverse of my issue in #6171 where access to Add-ons server works in official release but not with MSVC compilation.

**Comment by Pentarctagon** [comment]
In the backtrace is mentions
`'ｫ' <repeats 15 times>, "\376\356\376\356\376\356\376\356\376\356\376\356\376\356", <incomplete sequence \376>`

What is 'ｫ'?

**Comment by fujimo-t** [comment]
I'm wondering about it too.
Something wrong in parse of regular expression (address_re).

**Comment by Pentarctagon** [comment]
Hmmmm...

So, `address_re` is defined as a `const char*` aka a C-style string.  C-style-strings are supposed to be null terminated, which is also stated in the documentation of `std::regex` for the first argument:
> A pointer to the start of a C-style null-terminated string containing a regular expression.

However, `address_re` is not null terminated.  What happens if you add `\0` to the end of `address_re`?

**Comment by fujimo-t** [comment]
I think C-style string literal usually contains a null terminator if the capacity of destination is enough.
>  What happens if you add \0 to the end of address_re ?

I tried but difference was nothing.

**Comment by Pentarctagon** [comment]
Just to see what happens, does it change if you remove the '\0' and instead change `address_re` to an std::string?  From some googling the results seemed to indicate the "incomplete sequence" message happens for a C-style wasn't null terminated.

**Comment by fujimo-t** [comment]
I had already tried std:string but the backtrack inside std::regex hadn't been changed...

**Comment by fujimo-t** [comment]
It seems a known bug of mingw.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98723
At least, there are nothing wrong side of Wesnoth's code.

**Comment by fujimo-t** [comment]
Also I confirmed this on Chinese.

**Comment by Wedge009** [comment]
Impressive research. I'm surprised that regex is used in network connections, though. Did they quantify how slowly 'very slow' is? To me, trying to connect in Wesnoth wasn't so slow as to appear as though it hung (ie doesn't complete for at least 30 or so minutes).

**Comment by Pentarctagon** [comment]
I wonder if regex is really needed here?  The address validation regex didn't exist until Jan 2019, and it seems like it'd be equivalent to have non-regex checks for `address`:
* If there's no colon character, the format is `<IPv4/URL address>` and the default port is used.
* If there's a single colon character, the format is `<IPv4/URL address>:<port>`.
* If there's multiple colons, the address starts with a `[` character, and it ends with a `]` character, then the format is `[<IPv6 address>]` and the default port is used.
* If there's multiple colons and the address starts with a `[` character but doesn't end with a `]` character, then the format is `[<IPv6 address>]:<port>`.
* Else the address is invalid.

**Comment by fujimo-t** [comment]
> Impressive research. I'm surprised that regex is used in network connections, though. Did they quantify how slowly 'very slow' is? To me, trying to connect in Wesnoth wasn't so slow as to appear as though it hung (ie doesn't complete for at least 30 or so minutes).

It took 5 minutes in my env (Core i7-1065G7 + 16GB memory) and consumed 4GB memory at most.

> I wonder if regex is really needed here? The address validation regex didn't exist until Jan 2019, and it seems like it'd be equivalent to have non-regex checks for `address`:

I think it can be a workaround, too.

But I noticed std::regex is only used this place and boost::regex is used many place.
Simply replacing from former to latter can be another temporary workaround. 
I will try it.

**Comment by Pentarctagon** [comment]
Yeah, there was an attempt at one point to drop boost::regex in favor of std::regex to get rid of a dependency, only for it to be discovered that boost::regex has features we need but that std::regex doesn't support.  So there's some std::regex and some boost::regex in different places.

**Comment by Wedge009** [comment]
> It took 5 minutes in my env (Core i7-1065G7 + 16GB memory) and consumed 4GB memory at most.
Okay, I may have exaggerated previously. But I just tested again with Traditional Chinese on my best Windows machine which has Ivy Bridge E era Core i7 4930K with half the threads already occupied doing other processing work, and it was at least 20 minutes before I got past the connection screen using a bit more than one CPU core. Peak memory use was about 4.2 GiB before falling back to ~182 MiB at the lobby screen.

I'll update the original report with the new information.

**Comment by Pentarctagon** [comment]
To be honest I'd somewhat prefer using non-regex solutions where possible just because any non-simple regex looks like mostly gibberish to me.

**Comment by fujimo-t** [comment]
I found another usage of std::regex.
Long regex processing was happened too when I pushed "OK" in Editor->Starting Positions Tool->Add.
https://github.com/wesnoth/wesnoth/blob/376bb10cd4fef104fbae2836cb1542a00da20815/src/editor/palette/location_palette.cpp#L267

Both places become working correct by replace to boost::regex.

> To be honest I'd somewhat prefer using non-regex solutions where possible just because any non-simple regex looks like mostly gibberish to me.

Indeed.
But I will keep the implementation by regex because it works correctly on other environments...

**Comment by Wedge009** [comment]
> Yeah, there was an attempt at one point to drop boost::regex in favor of std::regex to get rid of a dependency, only for it to be discovered that boost::regex has features we need but that std::regex doesn't support. So there's some std::regex and some boost::regex in different places.

I see fujimo's PR replaces `std:regex` with boost, so everything is back to boost again. At least it's consistent that way.

**Comment by Wedge009** [comment]
Merged #6316 in master and 1.16.

**Comment by soliton-** [comment]
While regex probably have little place in network code this is hardly network code. It's validating user input and I think using a regex there is fine. There is no reason to suspect this can possibly be a performance issue to run a simple regex on a couple of bytes of user input. It is rather impressive that the mingw implementation manages to run this catastrophically bad...

It could be written as a raw string literal though to make it more readable.

**Comment by Pentarctagon** [comment]
I don't mean it as where the regex is being used or how it's being used. I mean that the regex string `\\[([[:xdigit:]:]*)\\](:([[:alnum:]]*))?|([[:alnum:]\\-_\\.]{1,253})(:([[:alnum:]]*))?` is not an obvious thing to read if you aren't already familiar with regex. Using that as an example, I didn't spend much time try to figure out what it did - it was much faster for me to read the git history for the file and look at the code below it to figure out what it was doing than it would've been for me to read up on regex grammar and (hopefully) come to the correct conclusion about what it was doing.

While it's not Perl in this case, this xkcd is nevertheless all to accurate: https://xkcd.com/1171/

**Comment by soliton-** [comment]
https://xkcd.com/208/

I think regex is a quite common concept in pretty much any language that you can expect familiarity with it. But sure as with anything else if you don't know it you won't be able to read code using it.
