### ISSUE TITLE
TRoW S8 inconsistency when trying to board a ship as a soldier

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#6298]
### Game and System Information
 - 1.16.x (the rest doesn't matter)

### Describe the bug
There are three places where the ships can arrive at. 
(29,16) = a, (32,14) = b, and (31,16) = c.
For a and b, the 'narrator' admonishes the unit. At c it's Aethyr instead.
And I don't how that makes sense. It should be either Aethyr only, or narrator only.

### To Reproduce

1. Load the provided save.
2. Move units to the provided coordinates.
3. Note that narrator and Aethyr say the same, but the one talking depends on the coordinates.

### Expected behavior
Either Aethyr only, or narrator only.

### Savefiles
[TRoW-Clearwater Port-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/7538782/TRoW-Clearwater.Port-Auto-Save1.gz)

### Additional context
c https://github.com/wesnoth/wesnoth/blob/60c6e72921fe91339014cd9cab49afde5affe2f7/data/campaigns/The_Rise_Of_Wesnoth/scenarios/08_Clearwater_Port.cfg#L778

b https://github.com/wesnoth/wesnoth/blob/60c6e72921fe91339014cd9cab49afde5affe2f7/data/campaigns/The_Rise_Of_Wesnoth/scenarios/08_Clearwater_Port.cfg#L832

a https://github.com/wesnoth/wesnoth/blob/60c6e72921fe91339014cd9cab49afde5affe2f7/data/campaigns/The_Rise_Of_Wesnoth/scenarios/08_Clearwater_Port.cfg#L887

**Comment by Descacharrado** [comment]
I suggest defining an in-scenario macro so code is not repeated (thus the problem is solved) and future changes are easier to do.

**Comment by Wedge009** [comment]
Indeed, the entire event is repeated thrice and I don't think the differences between them (aside from the co-ordinates and event names) are intentional. Commander Aethyr speaks at all three locations when it's Haldric who steps on them so I think it makes sense to replace the narrator with Aethyr.
