### ISSUE TITLE
Steam 'cloud' saves not working for Linux

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6303]
### Game and System Information
1.16.1 Steam

### Describe the bug
Steam Linux appears to be excluded for 'cloud' save games for Wesnoth 1.16.

### To Reproduce
Steps to reproduce the behaviour:

1. Open Wesnoth in Steam Linux, optionally save a game, close Wesnoth. Observe no `steam_autocloud.vdf` in 1.16 save directory.
2. Open Wesnoth in Steam Windows, optionally save a game, close Wesnoth. Observe `steam_autocloud.vdf` present in 1.16 save directory.
3. Additionally, save games will synchronise across Steam Windows instances, but not Steam Linux instances.

### Expected behaviour
Save games should synchronise across all Steam instances irrespective of OS, as 1.14 did before.

### Additional context
As discussed in #wesnoth-dev on 2021-11-16 UTC, Steam synchronisation was mistakenly not-yet-enabled for 1.16 but this had been rectified. Even so, I seem to only get save games on Windows hosts, not Linux ones.

I haven't explicitly tested, but I think 1.14 save game behaviour remains unchanged (it appears to get included in the file storage used for 'Steam Cloud'). It works for both Windows and Linux.

**Comment by Pentarctagon** [comment]
It looks like in the Steam cloud settings, there can be multiple Root paths (which are set to the Windows 1.14 and 1.16 save directories) but only one Root Override path per OS (used to provide cross platform syncing with Linux and macOS).  There also doesn't appear to be any way to link a particular Root Override to a Windows Root path, so as far as I can tell it's only possible to sync saves to **either** 1.14 or 1.16 for Linux and macOS.

Therefore I've deleted the 1.14 Root Override paths for Linux and macOS, and have confirmed that the `steam_autocloud.vdf` file now gets created in the 1.16 saves directory on Linux.  This does mean that 1.14's saves will no longer sync, but that seems to be a limitation of Steam's AutoCloud functionality, and if there needs to be a choice between syncing stable vs oldstable then I think the current stable version definitely takes precedence.

@Wedge009 If you can confirm that 1.16 syncing is working for you now, then I think this issue can be closed.

**Comment by Wedge009** [comment]
Thanks for that. I think it's acceptable to drop synchronisation for 1.14 especially if the current default distribution is 1.16.

I can see `steam_autocloud.vdf` being generated in Linux 1.16 save directory, but I haven't yet seen those saves transfer to my Windows installations (will test more soon). Steam is now reporting 2.75 MiB stored which matches my current Linux 1.16 directory, at least.

**Comment by Wedge009** [comment]
I confirm that Steam Linux installations have save game synchronisation working now, which is an improvement from before.

However, it looks like cross-OS synchronisation doesn't work, and it did before for 1.14. ie save games in Linux don't get copied to Windows, nor vice versa. I can open a new report for that issue if you want to close this one.

**Comment by Pentarctagon** [comment]
Does it not work at all, or do the 1.16 Linux saves end up in the 1.14 Windows directory?

**Comment by Wedge009** [comment]
Oh that's not good...

Yeah, 1.16 Linux saves are being copied to 1.14 Windows directory. At least the existing 1.14 saves don't appear to have been overwritten, on Linux or Windows.

**Comment by Pentarctagon** [comment]
Alright, how about now?

**Comment by Wedge009** [comment]
First I tidied the save games on my Windows installations. Then I started and stopped Wesnoth on my Linux instance where my save games are located. (I have not subscribed to any beta channels on Steam, only using the default 1.16.1 release.)

`steam_autocloud.vdf` is not getting updated again - neither 1.14 nor 1.16. I assume that means Linux is not being synchronised with Steam 'cloud' again.

Running Wesnoth on Windows, I observe `steam_autocloud.vdf` getting updated (just for 1.16) and new save files are being added but removed ones are not being deleted. That's probably a safe option but I was sure that removing files on one instance would propagate the deletions to other instances, previously.

**Comment by Pentarctagon** [comment]
Alright, how about now?  It looks like it didn't automatically update the override path replacement even when the root path it was supposed to be overriding no longer existed.

**Comment by Wedge009** [comment]
Testing, but I noticed some save files from Windows 1.16 going to Linux 1.16, so maybe that's a good sign.

**Comment by Wedge009** [comment]
Made some fresh test saves, on both Linux and Windows, and confirm the propagate to all other Steam instances, for both Linux and Windows. 1.16 only. Thank you for your perseverance.

**Comment by AI0867** [comment]
Seems to me that the only feasible solution would be to have all saves in the same directory tree: `some_path/saves/1.14` and `some_path/saves/1.16`. I doubt we want to reorganize our config directory tree that way though, so it would need to be through symlinks.
