### ISSUE TITLE
[foreach]array=this_item.something does not write back to the outer this_item

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#6305]
Low-priority because closing this as 'won't fix' seems a reasonable option. The Wiki has already been updated, logging an issue gives me a page to refer questions to.

The `[foreach]` loop makes the WML variables `this_item` and `i` locally scoped. If `readonly=no`, which is the default, then the code inside the loop can modify data through `this_item`.

The name of the `this_item` variable can be overridden, but in 1.14 it was possible to use nested loops with the default names, as in the code below. Since 1.15.10 and a0ee38a49ae0da7de6665f23a271a7a63b3c3ae7's change to data/lua/wml-flow.lua, that doesn't work, because the modified value is stored back to the current (inner) `this_item` before the inner `this_item` goes out of scope.
```
        # Store a unit to a variable
        {VARIABLE u.abilities[0].regenerate.value 4}
        {VARIABLE u.abilities[1].heals.value 4}

        [foreach]
            array=u.abilities
            [do]
                [foreach]
                    array=this_item.heals
                    [do]
                        [set_variable]
                            name=this_item.value
                            value=8
                        [/set_variable]
                    [/do]
                [/foreach]
            [/do]
        [/foreach]
```

While writing the test code, I found a separate issue with nesting using the default names: although `array=this_item.something` generally works for read-only data, using it with `array=this_item` triggers the sanity-check added in d895b1865978ef3144e650f57f3b520b271efae3. The sanity check will compare the outer `this_item.length` to the inner `this_item.length`.

Low priority because it seems there are only two add-ons that have a line matching `array=this_item.something`, and only one seems broken. The Wiki has already been updated to say this is to be avoided, which is the reverse of the old docs.
* SXCollection is the add-on that was broken, and will be fixed in that add-on.
* Era of Magic's doubleattack.cfg already uses `variable=this_item_attack` for its inner loop.

**Comment by stevecotton** [comment]
Given that 1.16.2 will have major fixes for multiplayer, I'm thinking it would be better to fix this than to leave it as "won't fix". Will open a PR for it soon.

**Comment by stevecotton** [comment]
@CelticMinstrel simply reverting the change would be one method, but fixing the bug while still using the new closure framework is giving me a steep learning curve - would you be able to take over the task and fix it in time for 1.16.2, please?

**Comment by CelticMinstrel** [comment]
I'm not sure… maybe I can take a look this weekend.

**Comment by stevecotton** [comment]
@CelticMinstrel, have you had time to work on this? I'm wondering what the best plan for 1.16.2 is, and whether to go for a revert to the 1.14 code.

**Comment by CelticMinstrel** [comment]
I haven't had a chance to look at this in any detail, but I did notice that the final line of the function changed scope in the linked commit – before the commit, it was executed _after_ the scoped variable was closed, while after the commit, it's executed _before_ the scoped variable is closed. Can that be the issue? (If so, all we'd need to do is add an extra scope around it, which is `do ... end` in Lua if I recall correctly.)

**Comment by stevecotton** [comment]
Part of the issue is copying back from the inner `this_item` to the outer `this_item`. When I tried to copy it though a temporary variable, the behaviour wasn't what I expected, however I didn't debug what the behavior actually was.
