### ISSUE TITLE
Button on load old version saves has a translation problem

### ISSUE THREAD

**Issue by MXB2001** [wesnoth/wesnoth#6307]
### Text Problems: Typos, grammar mistakes, suggested improvements

* Is the text in English? If not, what language is it in?
German

* What campaign does the text appear in? If it's not in a campaign, say where it is:
Load saved game screen button for loading older version saved games (like 1.14)

* Please quote the text verbatim. You can use `**bold**` to point out the mistaken part:
game_version^Derzeitige Version

* _(optional)_ What do you propose to change the text to?
Obviously the translation helper text should not be there

**Comment by stevecotton** [comment]
Thanks for reporting, and sorry about this. I have a fix sitting around locally, waiting for me to translate other stuff in the same .po file.

**Comment by Wedge009** [comment]
Is it this?
https://github.com/wesnoth/wesnoth/blob/1b0d245bafc256beb4674269b7417062df689f21/po/wesnoth-lib/de.po#L6395-L6397

I thought `gettext` knows to strip away the leading `XXX^` notation, or does it only do that if the 'translated' string matches the original?

**Comment by stevecotton** [comment]
Yes, it's that, and it only removes the caret-hint if the translated string exactly matches the original.

As for whose responsibility it is, while my language skills aren't enough to translate prose, I am using Wesnoth as a text to practice my German and doing simple cleanups.

**Comment by stevecotton** [comment]
Fixed in cc74772e26493dd9acc1cc4c7b6b99b80badc32f, although it will be a while before 1.16.2 releases.
