### ISSUE TITLE
[store_unit] doesn't replace x,y of units to "recall", "recall" when you store units from the recall list

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6315]
Most likely connected with #6295 

If you have units in the recall list with coords not equal to 0,0 (that happens if you just put units to the recall list with [put_to_recall_list] or if you saved units from the map to a variable and then unstored them into the recall list), [store_unit] doesn't replace their coords to "recall", "recall", as a result [unstore_unit] places them on the map. So the unit that had to be unstored back to the recall list appears on the map.

In 1.14 [store_unit] changed x,y to recall, recall if you stored units from the recall list, and after needed manipulations [unstore_unit] put it back to the recall list.

**Comment by stevecotton** [comment]
Thanks, focusing on `[store_unit]` has lead me to the first part of problem. The implementation created a temporary variable, changed it, and then used the values in the original. Fix part 1:

```
diff --git a/data/lua/wml-tags.lua b/data/lua/wml-tags.lua
index d62487da321..fca6d8425fb 100644
--- a/data/lua/wml-tags.lua
+++ b/data/lua/wml-tags.lua
@@ -401,11 +401,11 @@ function wml_actions.store_unit(cfg)
                local ucfg = u.__cfg
                if u.valid == 'recall' then
                        ucfg.x = 'recall'
                        ucfg.y = 'recall'
                end
-               utils.vwriter.write(writer, u.__cfg)
+               utils.vwriter.write(writer, ucfg.__cfg)
                if kill_units then u:erase() end
        end
 end
```

@CelticMinstrel with the change above, the test in #6296 now passes in non-strict mode, but is printing error messages. As you're much more familiar with this code than me, please would you debug it?
```
Error (strict mode, strict_level = 1): wesnoth reported on channel error config
20211121 03:29:32 error config: Error: attempting to delete non-existing child: LUA_modify_unit[0]
20211121 03:29:32 error config: Error: attempting to delete non-existing child: LUA_modify_unit[0]
BROKE STRICT (PASS): put_to_recall_and_modify
```

**Comment by CelticMinstrel** [comment]
Without further investigation, I would theorize that that's caused by the final line of `[modify_unit]` in a scenario where the modification variable somehow doesn't exist… but I'm not sure how that can happen.

If I can get my build working again, I can investigate further. Last I checked it was just a missing lib, so that _might_ be easy to fix…

**Comment by stevecotton** [comment]
@CelticMinstrel, are you able to fix this before 1.16.2 please? (There isn't a release date for that yet, but I'm guessing late January based on it needing a string-freeze.)

**Comment by CelticMinstrel** [comment]
I can probably take a look before the new year.

**Comment by stevecotton** [comment]
Fix part 2 is to change it to this instead:
```
utils.vwriter.write(writer, ucfg)
```
