### ISSUE TITLE
Allow the `{RANDOM}` macro to be used inline to set values

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#6319]
Currently, `{RANDOM}` expands to a call to `[set_variable]`, which means it can't be used in places where the `[set_variable]` tag can't be placed. I want to be able to do stuff like:
```
[ai]
    aggression={RANDOM 0.4..0.9}
[/ai]
```
and such. Currently I'd have to do an event like:
```
{RANDOM 0.4..0.9}
[modify_side]
    [ai]
        aggression=$random
    [/ai]
[/modify_side]
{CLEAR_VARIABLE random}
```
but that gets tedious when there are a bunch of different AI parameters I'd want to all set randomly. This would just be syntactic sugar to let it be done more easily. It doesn't necessarily have to replace the existing `{RANDOM}` macro; there could be a new macro instead if that makes things easier.

**Comment by cooljeanius** [comment]
(this is semi-related to #1211 but different because I'm proposing a specific way of allowing that to be fixed, and also in that I want this to be usable for more things besides just AI)

**Comment by Pentarctagon** [comment]
Note that there's no way to change the existing macro to do this without breaking every other place that's using this macro.

**Comment by cooljeanius** [comment]
so yeah make it a new macro instead then, I guess... call it `{RANDVAL}` or something instead? I dunno...

**Comment by ProditorMagnus** [comment]
Sounds like you want formula which returns random instead of macro.

**Comment by CelticMinstrel** [comment]
Dice operator possibly may be integers only, though.

**Comment by ProditorMagnus** [comment]
True, better as dedicated function. Still not supporting macro.

**Comment by cooljeanius** [comment]
Couldn't a macro wrap the formula/operator/function?

**Comment by ProditorMagnus** [comment]
Why would you prefer to use macro? Macro is sign that language syntax is not great. When asking for new feature it could be designed to be nice to use already.

**Comment by Pentarctagon** [comment]
Keep in mind that a macro does not return a value - it's just text replacement.  So for this to be a macro at all it would already need to be able to be done on a single line in order to be assignable like this.

**Comment by CelticMinstrel** [comment]
Note that the WFL solution won't even work in the example of `[side][ai]`, as variable substitutions aren't expanded there.

**Comment by cooljeanius** [comment]
> Why would you prefer to use macro? Macro is sign that language syntax is not great. When asking for new feature it could be designed to be nice to use already.

I find that macros are usually shorter and easier to remember

**Comment by ProditorMagnus** [comment]
> I find that macros are usually easier to remember and more readable

In that case why not just
```
#define ai name min max
{RANDOM {min}..{max}}
[modify_side]
    [ai]
        {name}=$random
    [/ai]
[/modify_side]
{CLEAR_VARIABLE random}
#enddef

{ai aggression 0.4 0.9}
#undef ai
```

**Comment by rubyFeedback** [comment]
> In that case why not just

But your example shows 11 lines. Isn't the one line suggestion by
cooljeanius simpler? I already know that I'd never use a +11 lines
expanded macro when a simpler one could be used instead. Not
just for that, but in general all custom macros that don't have a
unified base "upstream".

Actually personally I am in favour of having that macro be more
flexible, including backwards breaking problems (but preserve the
old behaviour for old games). Or, probably simpler, just give it
another name for now to solve that particular use case, and at
some point in the future decide whether it should be simplified
as a name.

**Comment by ProditorMagnus** [comment]
Macro is text replacement. It has no flexibility.

**Comment by Pentarctagon** [comment]
The best that can really be done with a generic macro would be something like:
```
{RANDOM 1..9 (
[modify_side]
    [ai]
        {name}=$random
    [/ai]
[/modify_side]
)}
```

**Comment by cooljeanius** [comment]
> > I find that macros are usually easier to remember and more readable
> 
> In that case why not just
> 
> ```
> #define ai name min max
> {RANDOM {min}..{max}}
> [modify_side]
>     [ai]
>         {name}=$random
>     [/ai]
> [/modify_side]
> {CLEAR_VARIABLE random}
> #enddef
> 
> {ai aggression 0.4 0.9}
> #undef ai
> ```

hm, I might give this a try, actually, although I'd want to give the macro a longer name to make it more explicit what it does, and reduce the chance of a name clash...

**Comment by ProditorMagnus** [comment]
Yes, if defining the macro somewhere else then should have better name. In my example it had immediate #undef so no danger of that.

**Comment by soliton-** [comment]
The request makes little sense. Usage of random values and macros have no relationship at all. It would be more useful to open a new request (or maybe completely rewriting this one) for something that in principle is possible. This is best done by not requiring specific implementation details (like asking for a macro here).
