### ISSUE TITLE
Sceptre of Fire final scenario: Handling the victory condition

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6332]
I originally played Sceptre of Fire all the way back in 1.4, though it looks to me like the campaign revision was only done quite recently in 1.15.x development cycle. In particular, the final scenario 'Caverns of Flame' was rewritten in #4681.

I recently replayed the campaign in 1.16.1 release but had particular trouble with the objectives for the final scenario. To release the seal on the volcano, three runic tablets need to be destroyed:
1. The first one is destroyed by the orc leader when enough of his team (or the leader himself) is killed. Thankfully the invading elves seem willing to help you complete this unless the player's side has not moved sufficiently far away enough.
https://github.com/wesnoth/wesnoth/blob/b8400b5b722a4fd022b6eabbcfb2f68bbfac7b28/data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg#L467-L471
2. The second is destroyed when defeating the Troll Hero, something that seems reasonable given this team is the weakest of all the enemies.
https://github.com/wesnoth/wesnoth/blob/b8400b5b722a4fd022b6eabbcfb2f68bbfac7b28/data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg#L571-L575
3. However, I had particular trouble with the final one as it requires Krawg - and only Krawg - to find the runic tablet.
https://github.com/wesnoth/wesnoth/blob/b8400b5b722a4fd022b6eabbcfb2f68bbfac7b28/data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg#L660-L663

The problem I had was that I used a generic Gryphon Rider to enter that hex, since my Krawg was severely wounded by the harassing Cave Wyrmlets near the start. Nothing happened upon reaching the tablet, so I assumed real tablet was somewhere else. Eventually I had to dig through the code to find out that the trigger for the final runic tablet was Krawg alone, Gryphon Riders are not considered.

I'm not sure how to handle this situation. If a non-Krawg Gryphon was to reach the tablet first - as in my situation above - I can't think of a plausible dialogue hint to say that Krawg should go to the tablet instead. (I think @doofus-01's intention here is to have Krawg destroy the tablet so that he can be ready to fly out when the volcano erupts - and have the main cast give their heroic sacrifice/farewell speeches.) One other option might be to have the victory event trigger irrespective of who reaches the runic tablet, but then the dialogue would have to be adjusted because the existing narration makes it explicit that Krawg is the one doing the breaking.

Looking at the [forum feedback](https://forums.wesnoth.org/viewtopic.php?t=20351), I see only @Konrad22 has given feedback after the rewritten scenario was introduced in 1.15.3 and apparently he found the objectives clear, so maybe I just got unlucky...

**Comment by max-torch** [comment]
Another detail to this, if you send Krawg to the third tablet before it's event has been "activated" something like this happens:
"Krawg looks at the tablet but is confused and has no idea." Then you have to wait until some trigger (maybe the destruction of the other two tablets) before you can then return Krawg to the final tablet and then Krawg knows now what to do and flies out with it.

My suggestion to resolve this issue would be to have a dialog whereby if a regular gryphon goes to the tablet, a message appears saying they are confused but Krawg is smarter and knows more lore so maybe he should check it, prompting the player to then send Krawg over instead.

**Comment by doofus-01** [comment]
> Krawg destroy the tablet so that he can be ready to fly out when the volcano erupts 

Yep.  A non-Krawg Gryphon just didn't occur to me, but adding a separate event and some text strings for that case shouldn't be too difficult.  Can something like that be back-ported, or would it be 1.17-only?

**Comment by Wedge009** [comment]
> Another detail to this: if you send Krawg to the third tablet before its event has been "activated" something like this happens: "Krawg looks at the tablet but is confused and has no idea." Then you have to wait until some trigger (maybe the destruction of the other two tablets) before you can then return Krawg to the final tablet and then Krawg knows now what to do and flies out with it.

Yes, I did consider the possibility that an adventurous player may find the tablet before the other two tablets are destroyed - I think the way the scenario is coded is that it expects the tablet to be found last which may not always be the case. Which is another situation that could be confusing.

> Yep. A non-Krawg Gryphon just didn't occur to me, but adding a separate event and some text strings for that case shouldn't be too difficult.

Thanks for confirming the intention. Implementing the separate event isn't necessarily difficult but writing appropriate lines (at least for me) is, otherwise I could have prepared a PR myself instead of logging this request.

> If possible I'd hope for the change to be backported, since 1.16 isn't going to go away anytime soon.

I would consider any solution for this as a 'fix' for game-play, not breaking anything at a code level, so should definitely be back-ported to 1.16 branch for a future point release.

So at least two additional possibilities to consider:
* A Gryphon besides Krawg could reach the third tablet.
* Krawg (or another Gryphon) could reach the third tablet before the other two are destroyed.

**Comment by max-torch** [comment]
>The situation where Krawg reaches the third tablet before the other two are destroyed
When I brought this up I meant to specify that this exists, not that it still had to be accounted for. Sorry if i wasnt clear about it.
Anyhow, the message for the regular gryphon encountering the tablet can just be similar to this. 

**Now as to why only Krawg has to be the one to be able to pick up the tablet.... well... we need to come up with some story logic for that.**

**Comment by Wedge009** [comment]
No worries, probably my fault, I realised that after the fact.

> Now as to why only Krawg has to be the one to be able to pick up the tablet.... well... we need to come up with some story logic for that.

_That's_ the bit I'm stuck on. ;)

**Comment by Wedge009** [comment]
Closed via #6628.

**Comment by max-torch** [comment]
Just saw this statement in the description of this issue:
>Looking at the [forum feedback](https://forums.wesnoth.org/viewtopic.php?t=20351), I see only @Konrad22 has given feedback after the rewritten scenario was introduced in 1.15.3 and apparently he found the objectives clear, so maybe I just got unlucky...

I looked at the forum thread and the post with Konrad doesn't say he found the objectives clear. He gave it a 4/10 for clarity.
>(3) How clear did you find the scenario objectives?
4, honestly. At least compared to the usual clarity.

It was the dialog and storyline that he found clear
>(4) How clear and interesting did you find the dialog and storyline of the scenario?
Clear.

Konrad's main gripe throughout his post is all about the tablets.
I hope the solution that closed this issue will improve the player experience.
