### ISSUE TITLE
UtBS S2: Final ogre killed re-appears and lingers during Dust Devil event

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6341]
### Game and System Information
1.16.1 release

### Describe the bug
In Under the Burning Suns S2 Across the Harsh Sands, there is a group of hunting ogres that ambush you near (17,49). A conversation event triggers (the one where Nym obtains the Dust Devil) when the last ogre is killed, but in 1.16 that ogre re-appears and lingers for the duration of the conversation.

### To Reproduce
Fortunately, the strange behaviour can be reproduced in debug-mode:

1. Start UtBS and use debug mode to go to the next scenario.
2. Move Kaleh and/or Nym to the area near (17,49) to trigger the appearance of the hunting ogres.
3. Debug-kill the ogres and notice that the final ogre re-appears to linger during the event where Nym obtains the Dust Devil.

### Expected behaviour
No ogres should be present (because they're all dead) during the event. This was the case for 1.14 so this seems to be a regression.

### Screenshots
![ogre](https://user-images.githubusercontent.com/13679322/143981783-433cadca-3b61-42ef-a844-08d703ed90cd.png)

[ogre.gz](https://github.com/wesnoth/wesnoth/files/7622777/ogre.gz)

**Comment by Wedge009** [comment]
Hmm, I did some more testing and it looks like it doesn't always happen (depending on the units present), but I'm pretty sure I did replicate it in debug mode at some point. At any rate I've updated the original report with the save game for the posted image. Not only does the ogre linger but the bottle for the Dust Devil doesn't even appear.

**Comment by Descacharrado** [comment]
Seems to be happening in normal 1.15.18 games too:
![Sin título](https://user-images.githubusercontent.com/30196839/144133998-a1071eff-01a2-4a92-8962-5964bd6426b8.png)
Also, looking at the code, seems like the creator knew the problem:
`During a die event, $unit is still blocking the hex, so Nym probably ends up running to the hex north-west of $x1,$y1.`

**Comment by Wedge009** [comment]
Thanks for confirming, though just wondering why you're playing on 1.15. Or is it a case of you checking an older save file and that's what was available at the time?

Regarding the code commentary, it seems to be discussing specifically the issue of what to do when Nym is adjacent to the last ogre killed and it's not really related to any potential display issues regarding the final ogre.
https://github.com/wesnoth/wesnoth/blob/01fa0c1e7cac460f5dff38f2abae9b8585366029/data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg#L725-L730

I couldn't replicate the situation in 1.14, so I wondered if there was possibly some change in the graphical side for 1.16, but then I found situations where I also couldn't replicate it in 1.16. Whenever it was introduced, it's a minor, inconsistent bug but still worth recording here.

**Comment by Descacharrado** [comment]
> Thanks for confirming, though just wondering why you're playing on 1.15. Or is it a case of you checking an older save file and that's what was available at the time?

Yeah, I had video proof recorded from 1.15.18, but I was able to replicate it in 1.16.1 with debug mode aswell. Already working on a possible solution.
