### ISSUE TITLE
wmltools: recognize the `--version` flag

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#6346]
This mostly applies to `wmllint` as it's the one whose behavior changes the most between versions, but ideally it should apply to all the [WML Maintenance tools](https://wiki.wesnoth.org/Maintenance_tools): users should be able to do `wmllint --version` (or `wmlindent --version` or `wmlscope --version`) to find out which version of BfW it comes from, to make sure their tools don't get out of sync with their game, if they've put them somewhere unusual or something. Currently the output when trying to use such a flag is:
```
$ ./wmllint --version
usage: wmllint [-h] [-c | -D | -d | -r] [-m] [-s] [-v] [-K] [-S] [-Z] [directories [directories ...]]
wmllint: error: unrecognized arguments: --version
$ ./wmlindent --version
usage: wmlindent [-h] [-?] [-d] [-v] [-e EXCLUDE] [-q] [files [files ...]]
wmlindent: error: unrecognized arguments: --version
$ ./wmlscope --version
usage: wmlscope [-h] [-c] [-C] [-d] [-e EXCLUDE] [-f FROM] [-l] [-r REFCOUNT] [-t TYPELIST] [-u] [-w WARNLEVEL] [-p] [--force-used FORCEUSED] [--extracthelp] [--unchecked] [directories [directories ...]]
wmlscope: error: unrecognized arguments: --version
```

See the GNU Coding Standards for more info about the `--version` flag:
https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html#Command_002dLine-Interfaces
https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html#g_t_002d_002dversion
(it's something that automake's `gnits` strictness level would also add checks for, btw, if the project were using automake)

**Comment by Elvish-Hunter** [comment]
Adding a `--version` command line flag isn't that hard; the real problem here is where to get the version number.
At the moment, three options come to my mind:

- Define a constant string somewhere in a Python module, which would have to be updated for every new release. This is probably the easiest solution, but who's going to update it every month if I forget or can't do it for a certain release?
- Attempt to run `wesnoth --version` as a subprocess. Not only we'd need to have different code for for different operating systems (different paths to the executable), but it isn't even guaranteed that the executable is actually there (for example, what if someone tries to run the wml tools without having compiled Wesnoth first?). This is the most complex option.
- Read the version number for an already existing file. After having looked at 237adec3, the only decent option to do so is the `changelog.md` file, because anything else isn't available in the Wesnoth installation package for Windows; obviously, it'd miserably fail if someone decides to delete the changelog from their own setup...

Have I missed some other, maybe more obvious, solutions?

**Comment by max-torch** [comment]
What do other software do, where do they read their version numbers?

**Comment by Elvish-Hunter** [comment]
> What do other software do, where do they read their version numbers? Maybe we can follow...?

@max-torch The other software are free to do whatever their authors want (hard-coding it, using an external file..). We, however, need to keep the version number of each WML tool in sync with the Wesnoth release number.
After thinking a bit more about it, probably updating the version number in the (upcoming?) Python module for every new release would be a task for the Project Manager. @Pentarctagon is this correct?

**Comment by Pentarctagon** [comment]
I think my question is in what scenario someone would have, for example, the wmllint script standalone. Or to put it another way, I understand why someone would want the `--version` flag, but in what situation would they both want the version of Wesnoth it came from while also having no way to find that out themselves?

**Comment by cooljeanius** [comment]
> I think my question is in what scenario someone would have, for example, the wmllint script standalone. Or to put it another way, I understand why someone would want the `--version` flag, but in what situation would they both want the version of Wesnoth it came from while also having no way to easily find that out themselves?

I have multiple installs of Wesnoth on my computer and sometimes forget which one's tools I'm using

**Comment by Pentarctagon** [comment]
Would that not be just as easily findable by looking at which directory the wmllint being used is in?

**Comment by cooljeanius** [comment]
Directory path doesn't contain the version string in it

**Comment by Pentarctagon** [comment]
What OS is this and how did you install these?

**Comment by cooljeanius** [comment]
> What OS is this and how did you install these?

I'm on macOS; I've got one from MacPorts, one from Steam, and one that I build myself from git, and I sometimes switch between branches with my git checkout, so it's not always the same version

**Comment by Pentarctagon** [comment]
So on all of these you should be able to check the version of the Wesnoth executable I would think.

**Comment by cooljeanius** [comment]
> So on all of those you should be able to check the version of the Wesnoth executable I would think.

I don't *want* to check the version of the Wesnoth executable, though, I want to just do it from the tools themselves

**Comment by Pentarctagon** [comment]
I don't want to have to now manually update a bunch of python scripts' hard-coded version number every release.

**Comment by cooljeanius** [comment]
Why not do one of the solutions that @Elvish-Hunter proposed previously instead?

> Adding a `--version` command line flag isn't that hard; the real problem here is where to get the version number. At the moment, three options come to my mind:
> 
> * Define a constant string somewhere in a Python module, which would have to be updated for every new release. This is probably the easiest solution, but who's going to update it every month if I forget or can't do it for a certain release?
> 
> * Attempt to run `wesnoth --version` as a subprocess. Not only we'd need to have different code for for different operating systems (different paths to the executable), but it isn't even guaranteed that the executable is actually there (for example, what if someone tries to run the wml tools without having compiled Wesnoth first?). This is the most complex option.
> 
> * Read the version number for an already existing file. After having looked at [237adec](https://github.com/wesnoth/wesnoth/commit/237adec3124345813445383f74ef35884d9c4069), the only decent option to do so is the `changelog.md` file, because anything else isn't available in the Wesnoth installation package for Windows; obviously, it'd miserably fail if someone decides to delete the changelog from their own setup...
> 
> 
> Have I missed some other, maybe more obvious, solutions?

**Comment by Pentarctagon** [comment]
The first is the thing I don't want to have to do every release. The second is more complex to implement and may not work anyway if it can't find the wesnoth executable. The third is essentially the same as the second, just using the changelog instead of the executable.

**Comment by Pentarctagon** [comment]
Also, to be blunt, I don't understand the motivation for wanting to being able to `wmllint --version` instead of `wesnoth --version`. It sounds more like wanting to follow the GNU conventions here rather than because it's actually difficult to find the version otherwise.

**Comment by cooljeanius** [comment]
Because the executable isn't named `wesnoth`, it's `The Battle for Wesnoth`, so I have to the escape the spaces in it, and it's also not in the same directory, so I have to remember how many directories above my current directory it's in, so after I've done all that, it becomes `../../../MacOS/The\ Battle\ for\ Wesnoth --version`, which is a lot longer than just `./wmllint --version` would be.

**Comment by Pentarctagon** [comment]
I'm not sure how macOS handles it, but can't you put double quotes around it rather than escaping the spaces?

**Comment by Elvish-Hunter** [comment]
> I don't want to have to now manually update a bunch of python scripts' hard-coded version number every release.

To be fair, you wouldn't have to do it for every script (that'd be absurd, pointless and I don't want to do it either).
To be more detailed, my first point proposed to create a `version.py` file in `data/tools/wesnoth`, which would contain a series of constants with the version number, like this for 1.16.2:

    major = 1
    minor = 16
    release = 2

Only this single file would need to be modified for every new release; then, every Python tool that needs to know the version number can just import the `wesnoth.version` module.
Hopefully this clarifies things a bit.

**Comment by Pentarctagon** [comment]
Ah, alright yeah, that sounds reasonable then.

**Comment by CelticMinstrel** [comment]
> I'm not sure how macOS handles it, but can't you put double quotes around it rather than escaping the spaces?

You can, but I don't think that really solves the underlying issue. Also, I think using quotes breaks tab-complete (if you use tab-complete you normally get escaped spaces).

**Comment by cooljeanius** [comment]
Thanks @Elvish-Hunter for the fix!
