### ISSUE TITLE
[history] section in preferences file

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6350]
Since 1.16 release, I've been noticing my preferences file fluctuating in size by a substantial amount. After some comparisons, I think it's in the `[history]` section, for example:
```
[history]
	[addon_connect_history]
		[line]
			message="add-ons.wesnoth.org"
		[/line]
	[/addon_connect_history]
	[mp_user_name_history]
		[line]
			message="Wedge009"
		[/line]
	[/mp_user_name_history]
	[other_abilities]
	[/other_abilities]
	[other_advancements]
	[/other_advancements]
	[other_attack]
	[/other_attack]
	[other_gotos]
	[/other_gotos]
	[other_ids]
	[/other_ids]
	[other_locations]
	[/other_locations]
	[other_names]
	[/other_names]
	[other_objects]
	[/other_objects]
	[other_overlays]
	[/other_overlays]
	[other_recruits]
	[/other_recruits]
	[other_roles]
	[/other_roles]
	[other_traits]
	[/other_traits]
	[other_types]
	[/other_types]
	[other_upkeeps]
	[/other_upkeeps]
	[other_variables]
	[/other_variables]
	[other_variations]
	[/other_variations]
[/history]
```

The `[other_xxx]` entries keep being sometimes added, sometimes removed, and I'm not sure why it's doing this or even why these entries are needed. Does anyone know what they're used for and whether the constant addition and removal from the preferences file is expected behaviour? There doesn't appear to be any correlation with MP lobby or Add-ons browser as I normally just play SP campaigns with no interaction with other segments of the game.

**Comment by soliton-** [comment]
In mainline I can only find:

> data/gui/window/mp_method_selection.cfg:91:                                                                     history = "mp_user_name_history"
> data/gui/window/addon_connect.cfg:104:                                                                  history = "addon_connect_history"
> data/gui/window/mp_login.cfg:106:                                                                       history = "mp_user_name_history"
> data/gui/window/mp_connect.cfg:116:                                                                     history = "mp_connect_history"
> data/gui/window/lua_interpreter.cfg:84:                                         history = "lua_text_entry"

Are those "other_" ones perhaps from some addon? On a quick look I cannot find anything about "other_" in the wesnoth sources at least.

**Comment by Wedge009** [comment]
Hmm, I did a search for 'other_' in my 1.16/data/add-ons/ directory and didn't find anything. The only add-ons I have installed are sigurdfd's GUI Debug Tools, An Orcish Incursion since that campaign was removed, and Winds of Fate for testing the PR.

As I was checking that, the preferences file had its references to the empty `[other_xxx]` entries removed again. Weird. It's not a big deal, but I am curious to see where this is coming from as I don't recall seeing it in 1.14.

**Comment by Pentarctagon** [comment]
Are add-ons able to add/remove/read things from the preferences? That sounds like it could be problematic.

**Comment by Wedge009** [comment]
I wasn't aware that they could, but looking through the code I couldn't see where 'other_xxx' could be coming from. Am I the only one finding these entries in the file? It's not a big deal, but it is strange that they keep being written, removed, written, removed, etc.

**Comment by Pentarctagon** [comment]
It looks like it's coming from GUI Debug Tools:
```
Gui_Debug_Tools> grep -Iirn 'other_'
lua/unit_debug.lua:35:									history = "other_names",
lua/unit_debug.lua:55:									history = "other_ids",
lua/unit_debug.lua:116:									history = "other_types",
lua/unit_debug.lua:136:									history = "other_variations",
lua/unit_debug.lua:156:									history = "other_locations",
lua/unit_debug.lua:176:									history = "other_gotos",
lua/unit_debug.lua:196:									history = "other_upkeeps",
lua/unit_debug.lua:815:								history = "other_recruits",
lua/unit_debug.lua:836:								history = "other_advancements",
lua/unit_debug.lua:857:								history = "other_roles",
lua/unit_debug.lua:878:								history = "other_attack",
lua/unit_debug.lua:899:								history = "other_abilities",
lua/unit_debug.lua:920:								history = "other_objects",
lua/unit_debug.lua:941:								history = "other_traits",
lua/unit_debug.lua:962:								history = "other_overlays",
lua/unit_debug.lua:983:								history = "other_variables",
lua/side_debug.lua:309:									history = "other_teleports",
lua/side_debug.lua:329:									history = "other_gotos",
lua/side_debug.lua:573:								history = "other_colors",
lua/side_debug.lua:593:								history = "other_flags",
lua/side_debug.lua:613:								history = "other_flag_icons",
lua/side_debug.lua:633:								history = "other_user_team_names",
lua/side_debug.lua:653:								history = "other_team_names",
lua/side_debug.lua:673:								history = "other_recruits",
lua/side_debug.lua:693:								history = "other_recall_units",
```

**Comment by Wedge009** [comment]
So it was in the lua code, that's why I couldn't find it. Thanks, that answers the core of my question even if it doesn't entirely explain why the behaviour wasn't present for 1.14 - or at least I didn't notice it...

**Comment by Pentarctagon** [comment]
@sigurdfdragon Any idea how/why these are getting into the preferences file by the way?

**Comment by Pentarctagon** [comment]
I'm thinking that if it's possible for an add-on to read or overwrite actual history entries, like a player's other usernames or other servers they've visited, then that'd be something we need to fix.

**Comment by Wedge009** [comment]
It could be. I don't know if it was necessarily introduced in 1.16, though.

**Comment by sigurdfdragon** [comment]
@Pentarctagon I can't find the wiki page for gui/wigets/dialog that mentioned the history field, (it's changed a bit) but from what i remember it might have been an unfinished feature. Wesnoth Lua Pack for 1.12/1.14 has these history lines in as well, I just carried it over from there.
I'm fairy sure it was listed in the wiki at some point.
As for the mechanics of how it gets in the preferences file, no clue.

**Comment by Pentarctagon** [comment]
@CelticMinstrel Any idea?

**Comment by soliton-** [comment]
https://github.com/wesnoth/wesnoth/blob/77eed10a098579ddb8ac20bbdadbf05b69541203/src/gui/widgets/text_box.cpp#L439
If two `text_box`es define the same history attribute they will overwrite each other.

**Comment by CelticMinstrel** [comment]
> Are add-ons able to add/remove/read things from the preferences? That sounds like it could be problematic.

There is a Lua preferences API, but it's only exposed in plugins, and you can't accidentally run a plugin (the plugin file needs to be loaded on the command-line), so that can't be the situation here.

I have no idea how the GUI2 history system works.
