### ISSUE TITLE
DiD, Alone At Last: Darken Volk can advance to Lich

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6351]
It happens implicitly when [remove_trait] is used to remove "loyal" (so his unit is reassembled from the template and the change to the "advances_to" preperty lost).

The easiet way to fix: not remove his loyal trait (its description seems fitting), or specify in the comments that enabling the lich advancement is intentional (if it would really be considered fitting)

**Comment by soliton-** [comment]
Single unit creation with different advances_to from the unit type:
https://github.com/wesnoth/wesnoth/blob/912625be842962704525f8fc8f9f39bbc7eb3a8e/data/campaigns/Descent_Into_Darkness/utils/characters.cfg#L38
Introduction of `[remove_trait]` which probably changed the behaviour: 26c2f941f2bcdd89528481e114c0375ad2a46271

**Comment by Descacharrado** [comment]
What about using something like this, but with the dark sorcerer, as far as I know there are no dark adepts in the new DiD. https://github.com/wesnoth/wesnoth/blob/912625be842962704525f8fc8f9f39bbc7eb3a8e/data/core/macros/optional_unit_advancements.cfg#L12-L19

**Comment by Wedge009** [comment]
@nemaara I suppose we can't apply this to 1.16 in case Volk has somehow advanced to Lich already?

**Comment by nemaara** [comment]
I'm not sure. It would only apply to S8 so I think it's minor enough that it should go in 1.16. If it were in an earlier scenario, then it probably couldn't.

**Comment by Wedge009** [comment]
I thought a similar thing. I only asked because of the commits you merged recently I think this one was master-only. I'll push it to 1.16 as well, if you haven't done it already.

**Comment by nemaara** [comment]
I think it's already in 1.16.

**Comment by Wedge009** [comment]
Yeah, it is. Sorry, for some reason I thought it was skipped.
