### ISSUE TITLE
UtBS: Kaleh vs Cloaked Figure

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6355]
In S8 Out of the Frying Pan, the Cloaked Figure is hard-coded to appear for the 'third' time:
https://github.com/wesnoth/wesnoth/blob/cf18e8d4e00c62eb741682f1860901a2da9388f9/data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg#L2355
https://github.com/wesnoth/wesnoth/blob/cf18e8d4e00c62eb741682f1860901a2da9388f9/data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg#L2395

The other two times are in S4 Descending into Darkness and S5 A Subterranean Struggle. The S4 encounter is guaranteed (Kaleh enters any hex that has an 'underground' time-of-day attribute, but the S5 encounter is randomised on certain turn number and it's possible to complete that scenario without meeting the Cloaked Figure again. So when I got to S8 and Kaleh complains of having to fight him a 'third time', I was thinking, 'wait, when was the second time?'

A trivial work-around might be just to have Kaleh say 'must I fight you again?' But I don't know if it's worth the effort of tracking the actual number of times that the Cloaked Figure is defeated and making his response based on that. Alternatively, there could be more done to make the encounter for S5 more reliable. Thoughts?

**Comment by stevecotton** [comment]
I'm sure I've seen this reported somewhere before, but can't find an original bug report.

**Comment by knyghtmare** [comment]
> but the S5 encounter is randomised on certain turn number and it's possible to complete that scenario without meeting the Cloaked Figure again.

It always triggered for me, but I took advantage of it and timed it right so that the Cloaked Figure became a meat shield vs Dwarves/Trolls and I didn't even bother fighting him XD

**Comment by Wedge009** [comment]
Heh, that's funny.

It's a minor quibble, but as I said, it was strange to be told third time when I missed the second (unintentionally).

**Comment by Wedge009** [comment]
> I'd go for the "must I fight you again" option.

I just noticed this will repeat 'again' in quick succession, which doesn't sound great. Wondering if there's a better way to phrase this...

'In Eloh’s name, not you **again**. Must I fight you **again**?'

I don't think 'yet again' would be appropriate if it's just the second encounter.

**Comment by max-torch** [comment]
I'd go for forcing the second encounter to occur. 
Reason:
- It affects scenario balance and difficulty in S5. Especially since it is not necessarily the easiest unit to take down without proper strategizing because of its poison. It is a welcome challenge.
- It seems like it affects the tone, mood, and development of the story. The dialog in each encounter is not generic verbatim complete copies of each other.
- The author has even made several versions of the dark assassin for the three different encounters, with the first one in S4 being the easiest and the last the hardest.

**Comment by Wedge009** [comment]
I agree that it makes more sense for the second encounter to occur. How to enforce that in a way that doesn't seem contrived, however, is beyond me at the moment.
