### ISSUE TITLE
Building fails on SunOS 5.11 (e.g. OpenIndiana) and fixes

### ISSUE THREAD

**Issue by larb0b** [wesnoth/wesnoth#6377]
### Game and System Information
 - What version of the game are you running?
    - Wesnoth 1.16.1
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
    - Built from source
 - If you're using a custom build, what compiler did you use, and what commit did you build at?
    - GCC 10.3.0, Wesnoth built from 1.16.1 release tarball
 - What OS are you running?
    - OpenIndiana 2021.10

### Describe the bug
Wesnoth does not build successfully out of the box on SunOS 5.11/Illumos platforms.

### To Reproduce

Attempt to compile on a SunOS 5.11/Illumos distribution e.g. OpenIndiana.

### Expected behavior
Wesnoth builds successfully.

### Issues and fixes
* Linking failure
  * On Solaris-based platforms, when doing things with sockets, you need to link against the socket library with `-lsocket`. If cmake or scons detect SunOS, add `-lsocket` to final linking of `wesnoth`, `wesnothd`, etc. executables.

* utsname difference
  * The declaration of `utsname u;` should be `struct utsname u;` on SunOS in `src/desktop/version.cpp`
e.g. change [this](https://github.com/wesnoth/wesnoth/blob/a202146b892249905d0306fe5777ff9802cb0bd9/src/desktop/version.cpp#L220) from
`utsname u;`
to

```
#if defined(__sun)
    struct utsname u;
#else
    utsname u;
#endif
```

### Screenshots
![image](https://user-images.githubusercontent.com/45925460/145645321-d86baf45-641c-45cf-9e4c-5b1ce87caa68.png)

After these adjustments, Wesnoth builds and runs perfectly. Tested on OpenIndiana 2021.10.

**Comment by Pentarctagon** [comment]
Can you open a PR with these changes? Nobody on the dev team uses this OS, so we can't test ourselves that the change we think is what you mean is actually correct and working.

**Comment by larb0b** [comment]
I would be willing to, but I'm not sure what the proper way to tell cmake and scons to add `-lsocket` for SunOS is.

**Comment by Pentarctagon** [comment]
For cmake you could add another elseif block at https://github.com/wesnoth/wesnoth/blob/a202146b892249905d0306fe5777ff9802cb0bd9/src/CMakeLists.txt#L41-L47 using it looks like [CMAKE_HOST_SYSTEM_NAME](https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_NAME.html).

For scons I'd say after https://github.com/wesnoth/wesnoth/blob/a202146b892249905d0306fe5777ff9802cb0bd9/SConstruct#L631-L638 add another check for SunOS using `env["platform"]` with `env.Append(LINKFLAGS = "-lsockets")`.

**Comment by larb0b** [comment]
Created a PR: #6379
