### ISSUE TITLE
[terrain graphics] - sconces can have odd rules

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#6381]
Sconces sometimes get drawn in an odd way.  In the editor, try drawing a wall running NE-SW, then overlay a sconce on the SW end.  Do the same for a wall running NW-SE.  I intend to fix this for 1.16.  I think there were some other glitches, I'll probably find them again when fixing this one.

I can't imagine anyone is relying on the asymmetric sconce behavior, but I'm posting a bug report to see if this is something that is frozen in stable.

**Comment by Pentarctagon** [comment]
Graphical display glitches aren't an API, so they can be fixed in stable.

**Comment by doofus-01** [comment]
Changing the behavior of a core macro could be seen as an API change.  Hopefully it isn't in this case, but it will make things look a little different, so best to ask.  I'll close this in a couple days, if there are no objections.

**Comment by Pentarctagon** [comment]
As long as people don't need to make changes in their own code for it, I'd say it's still fine.
