### ISSUE TITLE
Addons can't be updated from the multiplayer server menu

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#6383]
### Game and System Information
 - What version of the game are you running? Tried 1.16.0 and 1.16.1
 - Where did you download it from? flatpak and custom build from 1.16.0 tag
 - What OS are you running? Ubuntu 20

### Describe the bug
When someone is hosting a game which required some addon and you have an outdated version of this addon, the game proposes to update the addon (if you click OK). In 1.16 it does nothing. Only manual updating through Main Menu > Add-ons works.

### To Reproduce
1. Host a multiplayer game in one Wesnoth instance
2. Launch another one with an outdated version of the addon
3. Try to update the addon with this menu 
![изображение](https://user-images.githubusercontent.com/68666085/145713496-bd7abed1-e54d-4959-bda3-e9a43695129a.png)

Not all addons require all users to have the same latest version to play. Addons for which this behaviour was observed: Era of Magic, The Great Steppe Era
### Expected behavior
The addon updates successfully and you can join the game

**Comment by Pentarctagon** [comment]
If the add-on isn't installed at all, does that work?

**Comment by Discontinuum** [comment]
Afaik yes, if the addon isn't installed at all, it installs it

**Comment by Pentarctagon** [comment]
Also, is there any error that pops up, or what specifically is meant by "does nothing"?

**Comment by Discontinuum** [comment]
No error, it displays a window with some indicator, then Wesnoth logo and then again in the lobby. Simply say, exactly how it looks in 1.14, where it works, from a player's perspective at least. But when you scroll to the game, it still says you have an outdated addon version, the same as before. And I watched files in the addon directory - they don't change at all

**Comment by Pentarctagon** [comment]
> And I watched files in the addon directory - they don't change at all

Just to be sure - the version in the info.cfg doesn't change, right?

**Comment by Discontinuum** [comment]
Yeah, no changes in the dir at all in my experiment

**Comment by Discontinuum** [comment]
Well, here https://github.com/wesnoth/wesnoth/blob/e02cb3f8c2882c655859affd9620f31185d6c697/src/gui/dialogs/multiplayer/lobby.cpp#L177-190 I just don't see any downloading code under the if statement for this case. And in the else below, for a missing addon, there is downloading code

**Comment by stevecotton** [comment]
Re-opening as a reminder to backport.

**Comment by Pentarctagon** [comment]
Were you planning to do the backport, or should I?

**Comment by stevecotton** [comment]
Please do it.
