### ISSUE TITLE
Image Export for maps

### ISSUE THREAD

**Issue by JonathanLochridge** [wesnoth/wesnoth#6386]
### Game and System Information
1.14.15 version through steam
Windows

### Describe the desired feature
Be able to export high-resolution images from the map editor. As .Png or .Jpeg.

###Why:
Wesnoth currently has the best hex-map editing tool I know of anywhere. 
So, I would like to use it to make maps for my RPG sessions. 
However, taking screenshots results in super grainy images unless I zoom in a ton and stitch multiple screenshots together.

**Comment by Pentarctagon** [comment]
There's already Map Screenshot functionality actually, you just need to assign a hotkey to it in the preferences.

**Comment by soliton-** [comment]
I think we should add that item to the map menu so it's easier to discover.
