### ISSUE TITLE
Uncompiled .po translation files in add-ons are ignored by the game client

### ISSUE THREAD

**Issue by czyzby** [wesnoth/wesnoth#6391]
### Game and system Information
Wesnoth 1.16.1, Linux Pop!_OS, Flatpak installation.

### Describe the bug
`.po` files do not get picked up in a custom add-on. The associated modification is not translated with the provided `.po` file. `LC_MESSAGES/{file}.mo` has to be added in order for the game client to pick up the translation. Based on this [documentation page](https://wiki.wesnoth.org/GettextForWesnothDevelopers), this should not be necessary:

> ### Generating the .mo files for UMC
>
> For Wesnoth 1.14, it's generally not necessary to compile the .po files to .mo files. The mainline translations still use .mo files for better performance, but UMC authors can skip the .mo compilation stage.

### To reproduce

1. Install the `Saurian Pack` (v1.0.0 - v.3.0.0) from the add-on repository, or clone [this version of the add-on](https://github.com/czyzby/wesnoth-saurian-pack/tree/v3.0.0).
2. Change the game language to Polish.
3. Enter the multiplayer section and attempt to start a local game.

### Expected behavior
The add-on's modification is translated to Polish.

### Notes
[This commit](https://github.com/czyzby/wesnoth-saurian-pack/commit/c975201c8cd2fc14def6c29290b935afd7eb681a) fixed the issue locally. As you can see, the `.po` translation file was not moved or modified in any way - adding the `.mo` file in a nested folder alone was enough to add the translation. Moving `.po` file to the `LC_MESSAGES` folder had no effect.

**Comment by CelticMinstrel** [comment]
The location of your .po file is incorrect. It should be at translations/pl.po.

**Comment by czyzby** [comment]
I see. I'll try to rename the file and let you know if it gets picked up.

**Comment by czyzby** [comment]
`translations/pl.po` did not get picked up, but `translations/{TEXT_DOMAIN}/pl.po` did. So you need 1 more nested folder with the same name as your text domain, and `.mo` files are no longer necessary. Sorry for getting this mixed up.

**Comment by CelticMinstrel** [comment]
Right, I forgot that detail, sorry for giving incorrect information.

**Comment by stevecotton** [comment]
I had another look at the documentation page, and the example full-path-filename was word-wrapped as part of a paragraph of text. Have done a bit of editing to make it clearer.
