### ISSUE TITLE
1.16.1 stderr output has irrelevant data

### ISSUE THREAD

**Issue by MXB2001** [wesnoth/wesnoth#6409]
### Game and System Information
 - What version of the game are you running?
 1.16.1
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
flatpak 
 - What OS are you running?
Debian Linux
### Describe the bug
The error list includes a listing of units that have identical id's even if they are in different (and thus isolated in 1.16) add-ons. I've tested the identical id units and there is no conflict (each type is loaded by it's own add-on only) between them due to the id's being identical.

### To Reproduce
Download Era of Chaos and War of Legends to 1.16 and load a MP game with one of them. View the stderr output and see the multiple id error config lines.

### Expected behavior
No output for something that is not a problem under 1.16.

### Additional context
Battle for Wesnoth v1.16.1 x86_64
Started on Thu Dec 30 15:51:16 2021

Data directory:               /app/share/wesnoth
User configuration directory: /home/USER/.var/app/org.wesnoth.Wesnoth/config/wesnoth
User data directory:          /home/USER/.var/app/org.wesnoth.Wesnoth/data/wesnoth/1.16
Cache directory:              /home/USER/.var/app/org.wesnoth.Wesnoth/cache/wesnoth

20211230 15:51:16 warning general: setlocale() failed for 'de_DE'.
20211230 15:51:16 warning general: setlocale() failed for 'de_DE'.
Setting mode to 1280x1024
Checking lua scripts... ok
20211230 15:51:23 error config: Multiple [unit_type]s with id=Orcish Terror encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Brazier Imp encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Furnace Beast encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Kobold encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Nymph encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Stone Titan encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Sylph encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Thunderbird encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Undine encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Vine Beast encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Zephyr encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Quenoth Archer encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Quenoth Marksman encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Quenoth Mystic encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Quenoth Warrior encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Elvish Acolyte encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Elvish Ascetic encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Elvish Avatar encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Elvish Mystic encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Faerie Dryad encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Faerie Spirit encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Faerie Sprite encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Fire Faerie encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Hellwolf Rider encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Goblin Lancer encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Ancient Banner encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Archer encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Captain encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Eagle Master encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Eagle Rider encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Flagbearer encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Greatbow encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Guard encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Guardian encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Lancer encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Longswordsman encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Pikeman encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Scout encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Shield Guard encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Silver Shield encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Slayer encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Sorceress encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Spearman encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Strongbow encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Swordsman encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Aragwaith Swordsmaster encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Shadow Lord encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Shadow Mage encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Naga Guardian encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Naga Hunter encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Naga Marksman encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Naga Sentinel encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Naga Warden encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Orcish Shaman encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Orcish Sorcerer encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Orcish Warlock encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Bone Knight encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Dark Rider encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Death Baron encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Skeleton Rider encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Blood Apprentice encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Blood Hulk encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Blood Manipulator encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Bloodborn encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Day Hunter encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Duchess encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Vampire Duelist encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Fledgeling encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Flesh Artisan encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Malborn encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Methusalem encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Mistress encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Vampire Noble encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Sangel encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Sire encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Sword Dancer encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Twilight Walker encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=True Vampire Bat encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Vampiric Blood Bat encountered.
20211230 15:51:23 error config: Multiple [unit_type]s with id=Vampiric Dread Bat encountered.

**Comment by Pentarctagon** [comment]
This is, in fact, a problem (with the add-on). So I'm not sure what the issue is?

**Comment by MXB2001** [comment]
Yes the addon has the same unit id's but I thought that 1.16 ignores this. So why does it report something that has no bad effect. As stated both addons co-exist very comfortably under 1.16 so there is no problem with either add-on. The problem lies in 1.16 reporting something that doesn't matter anymore. Under 1.14 this was very important information indeed but under 1.16 it is completely irrelevant.

**Comment by stevecotton** [comment]
It's definitely a bug in the add-ons. The line that prints that message is the error-handling from trying to put both types into the single list of known unit ids, so if it's triggering then which definition gets into the list is implementation defined behavior, it might even be random:
https://github.com/wesnoth/wesnoth/blob/299550113af7ad3a7132d749c60838724f5da60a/src/units/types.cpp#L1221-L1225

**Comment by Pentarctagon** [comment]
Also there doesn't seem to be an Era of Chaos on the add-ons server?

**Comment by ProditorMagnus** [comment]
You have not considered that each of your independent addons can be loaded by third unknown addon.

**Comment by doofus-01** [comment]
This is probably similar to your #6410.  If this isn't just a bug in the add-ons, can you provide more details (the save-file, the way you tried to load it, etc.)?

**Comment by Pentarctagon** [comment]
It's actually impossible to reproduce with the steps provided since Era of Chaos isn't downloadable (unless I'm blind).

**Comment by knyghtmare** [comment]
**Oh god. Not this again.... (this was brought up in 2013)**
yes, both EoC and WoL share identical unit IDs and both authors were too proud to add a suffix to split them since one of the eras was heavily used in campaigns (still is).
I believe EoC is being ported to the latest 1.16.x and thus, these 1.12/1.10 issues are coming back...

Possible solution:
1. Add "EoC" suffix to each unit id of EoC

**Comment by stevecotton** [comment]
> both authors were too proud

Possible solution:

2. Both authors fix their stuff

I was fully agreeing with you saying "Oh god. Not this again..." until I realised that you were the other author, and WoL has ID clashes with Quenoth units that might move from UtBS into core.

**Comment by knyghtmare** [comment]
> WoL has ID clashes with Quenoth units that might move from UtBS into core.

If Quenoth Elves move to core, I will probably swap out that faction from WoL. I am aware of a PR in drafts about taking good units from mainline campaigns (3414), however that one seems to be lacking updates.

Also, adding suffix to WoL is kind of complicated as I would be breaking over 20 other add-ons with that action (can give name list)...

For EoC, it would be less complicated as it's not used in any 1.16.x server UMC campaigns.

**Comment by Pentarctagon** [comment]
To clarify, is the issue caused by duplicate unit types when two add-ons with the same unit type are directly depended on by another add-on, or is the issue that unit types can still collide even if only one of them is currently being used?  The former is expected and a problem with the add-ons, but the latter is unexpected to me and if true then we should document what WML remains un-isolated.

Unfortunately I can't which is the exact case described in the OP, since one of the add-ons is unpublished, so probably it'd be best to wait until it's published so the steps provided can actually be followed.

**Comment by CelticMinstrel** [comment]
> so probably it'd be best to wait until it's published so the steps provided can actually be followed.

On the contrary, I think this is something that should be resolved _before_ the second add-on is published.

**Comment by Pentarctagon** [comment]
The add-on author should update their unit types before publishing, yes. I simply can't try to reproduce an issue when the steps to do so require something I don't have access to though.

**Comment by ProditorMagnus** [comment]
So there is agreement that stderr output data is relevant.

**Comment by Pentarctagon** [comment]
Correct.

**Comment by stevecotton** [comment]
It can be reproduced by copying files between two `#ifdef MULTIPLAYER` add-ons. I tested with:
```
cp -a War_of_Legends/units/elves-quenoth* Era_of_Magic/units/
```


> To clarify, is the issue caused by duplicate unit types when two add-ons with the same unit type are directly depended on by another add-on, or is the issue that unit types can still collide even if only one of them is currently being used? The former is expected and a problem with the add-ons, but the latter is unexpected to me and if true then we should document what WML remains un-isolated.

Did some debugging, and the un-isolated data appears to only affect the multiplayer lobby and the "Create Game" screen. I put a breakpoint on `unit_type_data::set_config`, and it was hit once for each of these actions:

* Start Wesnoth, load config before the title screen.
* Enter multiplayer (any of "host network game", "connect to server" or "local game"). **This is the only one where these warnings are seen.**
* Creating the waiting-for-players lobby (after choosing the era on the "Create Game" screen, the host clicks that screen's "Create Game" button).
* Someone in the multiplayer lobby clicks "Join" or "Observe" (either during the waiting-for-players step or after the game has started).

The point where this debug is triggering is on the "enter multiplayer" step, so the WML isolation is working when it matters in the game itself. When in the waiting-for-players lobby, the correct data is already loaded before choosing factions and leaders.

Haven't thought this through, but it might suggest an optimisation of not loading unit data when entering the lobby. I think the unit data is only used if you enter the multiplayer lobby and then open the help browser by pressing F1 (there's no "Help" button other than the hotkey on that screen).

> You have not considered that each of your independent addons can be loaded by third unknown addon.

As @ProditorMagnus pointed out - even if the isolation code works perfectly, making all units have unique IDs is probably a good idea anyway.

**Comment by MXB2001** [comment]
Oh I'm so sorry guys, I posted this two days BEFORE the EoC was uploaded. I'm an idiot. It's been up since Jan. 1, 2022 though.

 As Tahsin said it's his lovely WoL and the freshly reborn EoC that give a lot of the errors. The fault is entirely the EoC's for not having unique ID's for the duplicate units.

 That said, I was under the impression that one of the great advances of 1.16 was that it isolated the addons so that it would not matter.

 As one commented the isolation DOES work in game. I'd tested that using the Bloodborn units from both factions. Same ID but different stats in the game.

 The only problem here is the output in the log. The log is making a false claim. That there is an error where there is none. Since the duplicate id's don't cause the wrong stats to be loaded for units in 1.16 it is crying wolf so to speak. :- )

**Comment by soliton-** [comment]
As mentioned above the error comes from the code that adds the unit types. If the error is printed the unit type was not inserted and is not available (in the help or wherever). It is definitely an error regardless if later in a game that only requires one of the units it will work fine (and the error is not printed then).
