### ISSUE TITLE
1.16.1 Ubuntu (Steam) game map is showing through very small rectangle "window"

### ISSUE THREAD

**Issue by amokmen** [wesnoth/wesnoth#6415]
### Game and System Information
1.16.1
Steam
Ubuntu

### Describe the bug
Game map is showing through a very small rectangle "window".

If I resize _game window_ - all are becoming okay.

### To Reproduce
Could not reproduce by my will.
Sometimes occurs immediately after **load replay** or **connect as observer to game**.

### Screenshots
![wesnoth_small_window](https://user-images.githubusercontent.com/10855248/147859485-1f9a2c41-6b7e-4357-b994-476ca8a11492.png)

### Additional context
Game resolution 3706x2105
Not full-screen.
I am using in-game scaling (by keys "-" & "+").

**Comment by Wedge009** [comment]
If it's intermittent, it's going to be very hard to debug. I haven't seen anything like this in recent (ie 1.16.x) play.

**Comment by doofus-01** [comment]
I commented on a similar report on the forums
https://forums.wesnoth.org/viewtopic.php?p=670503#p670503

It's seemingly random.  Restart Wesnoth and load the same file -> no issue.  Does it need to be loaded from a save-file?  Not sure, too difficult to reproduce.  Happens maybe 1-5% of the time.

**Comment by amokmen** [comment]
> I haven't seen anything like this in recent (ie 1.16.x) play.

I saw it 3-4 times. My bet for incorrect start to show map - because of enabled scaling.

**Comment by Wedge009** [comment]
Up to release 1.16.2 now. For those who experienced this, is it still happening?

**Comment by doofus-01** [comment]
This has been happening for me still, for 1.16 current at least as of last week or maybe week before.

**Comment by Wedge009** [comment]
But you're not able to quantify how it happens, how to replicate it, etc?

**Comment by Wedge009** [comment]
> Game resolution 3706x2105 Not full-screen. I am using in-game scaling (by keys "-" & "+").

For those who can replicate this - do they have large resolutions like the original report? While playing around with zooming, I replicated #2458 but wasn't able to get the narrow window that this issue specifically describes.

**Comment by doofus-01** [comment]
1920x1015 or similar.  Default zoom.

**Comment by Wedge009** [comment]
doofus or anyone else, still happening on 1.18?

**Comment by doofus-01** [comment]
No, I haven't seen it recently.

**Comment by Wedge009** [comment]
Re-open if anyone can replicate this.
