### ISSUE TITLE
Log Relocation on steam

### ISSUE THREAD

**Issue by geor999** [wesnoth/wesnoth#6418]
### Game and System Information
 - What version of the game are you running? last version on steam, more specific [1.16.1]
 - Where did you download it from? Steam
 - What OS are you running? Windows

### Describe the bug
When i tried to open it via steam i got an error about Log Relocation. 

### To Reproduce

1. First downloaded via steam and opened
2. Then got the error
3. Lastly did the whole process again but nothing happened

### Expected behavior
I expected it to launch properly but no matter how many times i tried to delete/restart it nothing actually happened.

![image](https://user-images.githubusercontent.com/72676920/147898642-30f77087-5e44-440a-b5c2-7097a96ba459.png)

**Comment by Pentarctagon** [comment]
This is a known issue (#2999). It's caused either by:
* Anti-virus blocking Wesnoth from creating files/folders in the My Games directory.
* OneDrive managing the directories Wesnoth tries to create in My Games.
