### ISSUE TITLE
Editor: add a way to hide or move the "Shift + left-click:"... text at the bottom of the screen

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#6422]
1.16.x and 1.17, on all platforms.

Commit 8b236620dd39123501403322f52870373536edcb changed the text at the bottom of the map-editor screen from
```
    	FG: Savannah/Forest (Forest,) | BG: Green Grass/Grassland (Flat)
```
to the much longer
```
    	Left-click: Savannah/Forest (Forest, ) | Right-click: Green Grass/Grassland (Flat)
    	Shift + left-click: paint overlay layer only | Ctrl + click: copy terrain
```
which can get in the way of editing. This issue is a reminder to myself that I've promised @irydacea that I'll fix it. I'm currently thinking of adding a new button next to the "draw terrain codes", "draw hex coordinates" and "draw grid" toggle buttons.

**Comment by FrostBlade5** [comment]
The text indeed can get in the way of editing, an extra button for terrain description sounds good, however if this is to much work i would aprecciate if the annoying text could simply be removed, anyways take your time it is not a game breaking thing, thank you in advance.

**Comment by CelticMinstrel** [comment]
Removing the text entirely is also game breaking, as it hides important information (the identity of the currently-selected terrain).

**Comment by cooljeanius** [comment]
yeah it's useful information that is only slightly annoying; adding a way to move it or hide it would be highly preferable to removing it entirely

**Comment by CelticMinstrel** [comment]
Of course, there's also the possibility to move it to someplace else.

**Comment by stevecotton** [comment]
Took a while looking through GUI layouts and themes trying to find out where the location of that widget is configured. Turns out that it's a special case that's hardcoded in the C++, and has over time been replaced with tooltips everywhere except in the editor.

Look at display.cpp/display.hpp in bb90f34fdd527aa67bfa93d231f2341c27ee3315 for what it is.
In 1.16 it's handled by the CVideo singleton.
In 1.17 it's moved to a global static in floating_label.cpp / floating_label.hpp.

It looks like the global variable might have been redundant in 1.16, as the value is also stored in editor_palettes.hpp's `help_handle_`. However, that has been removed from editor_palettes.hpp in 1.17.

**Comment by stevecotton** [comment]
For everyone subscribed to this, please comment on the pictures in #7362. Not a complete fix, but is it enough for the stable branch?

**Comment by cooljeanius** [comment]
> For everyone subscribed to this, please comment on the pictures in #7362. Not a complete fix, but is it enough for the stable branch?

yeah I agree with what @Pentarctagon said there

**Comment by stevecotton** [comment]
Once people have had time to try this out, I'm OK with reopening it if more is needed.
