### ISSUE TITLE
[LoW] [deprecated code] replace share_view=yes in favour of share_vision=all

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6496]
https://github.com/wesnoth/wesnoth/blob/f5ea3b0906ff5bb3f1282a33bc3419c11e1cb105/data/campaigns/Legend_of_Wesmere/utils/characters.cfg#L18

[Wiki](https://wiki.wesnoth.org/SideWML)
```
share_view: whether sides allied with this side see the units that this side sees, if they are on FoW (fog). ([Version 1.13.1 and later only](https://wiki.wesnoth.org/DevFeature)) This has been deprecated in favor of share_vision (see below).
```
Since it's been deprecated around 1.13.1, it should be updated to `share_vision=all`

Comment:
I am surprised this deprecated code has stuck so long and undetected.

**Comment by CelticMinstrel** [comment]
Is there perhaps no deprecation message? If that's the case we could also add one.

**Comment by stevecotton** [comment]
> Is there perhaps no deprecation message? If that's the case we could also add one.

WIP, will open a PR about it in the next couple of days.
