### ISSUE TITLE
Upgrade flatpak nightly builds to freedesktop runtime 21.08

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#6497]
### Game and System Information
Linux + flatpak

### Describe the desired feature
Wesnoth flatpak build uses 20.08 runtime, please upgrade to the latest 21.08

```
 # flatpak list --app --columns=application,runtime
 Application ID                                Runtime
 org.wesnoth.Wesnoth                           org.freedesktop.Platform/x86_64/20.08

```

**Comment by Pentarctagon** [comment]
Is 20.08 deprecated, or is there another reason to upgrade it?

**Comment by grz0** [comment]
It is not deprecated, but all flatpak apps that I use have updated to 21.08 runtime, and I keep 20.08 only for Wesnoth.
