### ISSUE TITLE
[Graphics] Drake Arbiter/Warden pop outside of map hex when attacking or defending.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6508]
## Wesnoth Version
1.17.0+dev

https://cdn.discordapp.com/attachments/259976436490829825/939623417882226748/IQ-Clash_of_the_Drakes_Turn_7.2.gz
(requires Inky's Quest to be installed)

Observed Here:
Video: https://www.twitch.tv/videos/1288191641
TimeStamp: 20:24

Reproduce:
1. Spawn Drake Arbiter on a ford/shallow water hex
2. Observe it being attacked and defending.
3. Observe it retaliate in attack
4. It can be seen he is levitating on water

(Not observed for Drake Clasher/Thrasher/Enforcer)

![image](https://user-images.githubusercontent.com/5283677/153634306-4943103d-bede-4343-b519-369591de1751.png)

Reported by @Konrad22

**Comment by doofus-01** [comment]
I can't view the video and am not seeing the issue when I test this in mainline 1.16.  Is this specific to 1.17?

**Comment by Konrad22** [comment]
> In 1.16.2, Arbiter pops out of the water, Warden looks good. ![Arbiter def](https://user-images.githubusercontent.com/30196839/153749398-6fc06fc0-af9b-46ae-b640-bc0ef62f9fe6.png)

If you compare the feet of the Wardens, you'll see that the idle ones feet are far deeper under water. It's not as obvious as the Arbiter, where the one defending is plainly above the water.

FTR, right now it doesn't trigger for me on shallow water, but it does trigger on Ford or Coastal Reef.

**Comment by Descacharrado** [comment]
> If you compare the feet of the Wardens, you'll see that the idle ones feet are far deeper under water. It's not as obvious as the Arbiter, where the one defending is plainly above the water.

I have looked at the files and it looks like that happens with every single image that is not 72x72 (the norm for wesnoth unit image sizes), will open a PR soon.
