### ISSUE TITLE
Great Troll (level 3) and Troll Warrior (level 3) should have different sprites.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6509]
This issue was brought up before but forgotten but it still persists to this very day, which is saddening.

Anyways, the confusion becomes apparent when both Troll Warrior and Great Troll are available to the player at the same time. Often players would confuse one with the other and this is not good.

Mainline example: SotBE (the troll hero, but he is given a different color hue via code)

References:
https://forums.wesnoth.org/viewtopic.php?t=47619
https://forums.wesnoth.org/viewtopic.php?t=47627

![image](https://user-images.githubusercontent.com/5283677/153636301-b107d36e-7625-4db1-816f-d9eb008c6f47.png)

![image](https://user-images.githubusercontent.com/5283677/153637254-f06885de-f9e7-4dc8-ba08-6a63951ab454.png)

Summary: 
Opening a ticket here so it's not neglected and eventually forgotten like it was before.

**Comment by Wedge009** [comment]
I don't recall this issue being logged before, either here or on Gna, so if it was just a forum discussion it would have easily been missed. Wonder if @doofus-01 has thoughts on the distinction.

**Comment by Wedge009** [comment]
> Not very likely. It's sort of attached to one campaign (SotBE), a boss in UtBS (In the Tunnels of the Trolls) and some LoW Scenarios.

Not too many locations so it's not beyond the realm of possibility, but I don't really think deleting the unit is the best option anyway.

> Ah, so it was neglected. Sad.

My point is that I don't recall it being logged in any bug/issue tracker (for as long as I've been monitoring them). Not that it was 'neglected'. Pretty hard to neglect something you don't know about (I know some devs keep a close eye on the forums but not everyone does). But anyway, you've recorded it here now, so at least it can be considered.

For whatever it's worth, I have the impression that the Great Troll is something perhaps a little more 'special' than just an experienced Troll Warrior. Perhaps akin to the difference between the Orcish Sovereign vs Orcish Warlord, aside from the leadership ability.

**Comment by doofus-01** [comment]
My thoughts at this moment are:
1.  I agree with the notion that these aren't the same unit and shouldn't be using the same sprites
2. This is something that should be fixed in 1.17, along with the fire dragon.  The sprite above might work, need to think about this more...

**Comment by cooljeanius** [comment]
> > Is deleting the "great troll" altogether a possibility? And distinguishing the greater trolls via WML enhancements?
> 
> Not very likely. It's sort of attached to one campaign (SotBE), a boss in UtBS (In the Tunnels of the Trolls) and some LoW Scenarios.
> 
> > I don't recall this issue being logged before, either here or on Gna,
> 
> Ah, so it was neglected. Sad.
> 
> Anyways, I am attaching the closest update which was made for the Great Troll here for viewing as well.
> 
> ![gargantuan_troll](https://user-images.githubusercontent.com/5283677/153691644-5b96b6c2-fdc7-402f-9a18-a9cc1926e454.png)

I've also seen that sprite used in UMC (such as Dawn of Thunder) for bosses that are supposed to be Level 5 units unrelated to the Great Troll... anyways, the point is that that sprite looks a bit too powerful for a Level 3 unit like the Great Troll

**Comment by cooljeanius** [comment]
I think that @doofus-01 fixed this sometime recently? Someone should be sure to track down the correct PR/commit before closing this, though...

**Comment by Wedge009** [comment]
#7844

**Comment by cooljeanius** [comment]
> #7844

ok so yeah, fixed by [20b0319](https://github.com/wesnoth/wesnoth/commit/20b031949faeaf0ce0795e875c766d09e135ddb3), then.
