### ISSUE TITLE
Northern Rebirth Prologue: Don't use "reckon" twice in succeeding sentences

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#6510]
English text, second "screen" of NR campaign prologue sequence:

> The dwarves of Knalga, cannily **reckoning** the gains from their trade ... The people... **reckoned** themselves well able to fight...

The use of "reckon" in succeeding sentences doesn't sound right. I suggest replacing one of them with something else - at the word or phrase level. The second use could be replaced with "considered". The first use might benefit from some expansion or clarification. It's not exactly clear why the "canny reckoning of gains" in itself leads to building fortifications, other than for the consideration in the second sentence.

**Comment by Descacharrado** [comment]
Permalink to the code (master): https://github.com/wesnoth/wesnoth/blob/933c273b997b61ebe4cf435c4e535154ba975abd/data/campaigns/Northern_Rebirth/scenarios/01_Breaking_the_Chains.cfg#L23

**Comment by Wedge009** [comment]
For a small change like this, I suggest making a PR. To me, the words are far enough apart that it doesn't sound too bad but if it's that important for you, you can submit your suggested change.

**Comment by cooljeanius** [comment]
I think the repetition might actually be an intentional form of wordplay, since each usage of "reckon" is in a different sense: the first one is more in an archaic sense of the word meaning "realizing" (in the sense of "making real") or "capitalizing upon" or "taking advantage of", while the second one is in the more modern/colloquial sense of "thinking"

**Comment by eyalroz** [comment]
@cooljeanius : That's a problem, because (1.) narration should not be jovial/humorous (2.) We shouldn't have sentences mixing modern and archaic language like that.

**Comment by cooljeanius** [comment]
> @cooljeanius : That's a problem, because (1.) narration should not be jovial/humorous (2.) We shouldn't have sentences mixing modern and archaic language like that.

OK well I added a commit (b3a3d4b) to PR #6057 that changes the second "reckoned" to "considered" at least

**Comment by cooljeanius** [comment]
So, #7454 recently updated some of the dialogue in this area, but after rechecking, it looks like it didn't address this particular nit, though...

**Comment by TheShadowOfHassen** [comment]
Sorry I didn't see this sooner I've been busy and github didn't notify me of references to my pull request.

I'm the person who did the rewrite of the first NR script. I want to do the rest of the campaign but I haven't had time.

So I left both reckoning to have parallel construction. I honestly think it's better with it, but if a lot of people don't like it...

**Comment by TheShadowOfHassen** [comment]
You sort of need the same words to have parallel construction...

**Comment by eyalroz** [comment]
@TheShadowOfHassen : I'm not sure I follow. Can you perhaps quote some literary source for an example perhaps?

**Comment by TheShadowOfHassen** [comment]
So it really isn't parallel construction in the dictionary definition. However while I don't know what it's actually called here's the quote:

  "The dwarves of Knalga, cannily reckoning the gains from trade, built strong fortifications around Dwarven Doors. The people who called it home, dwarven and human alike, knew that the wealth of their city might arouse envy from afar — hence they kept their weapons sharp, and reckoned themselves well able to fight off any bandit gang or petty warlord that could arise in the thinly-settled Northlands."

I thought the reckoned and reckoning would give it a sort of ironic twist and sort of tie it together. I know it's a me thing and people could think differently.

It occurred to me a way to make this paragraph even better though...

  "The dwarves of Knalga, cannily reckoning the gains from trade, built strong fortifications around Dwarven Doors.  The dwarves and humans who called it home knew that the wealth of the city might arose envy from afar --hence they kept their weapons sharp, and thought themselves able to fight off any bandit game or petty warlord."

I think that comma set whatever it called with dwarves and humans alike make it harder to follow the story.

On more looking at it I can see how the two "reckonings" can be confusing. I'll add this new paragraph into the latest pull request (if you don't see anything else wrong with it) Also, @eyalroz if you find any other issues in NR's dialog/narrator let me know and I'll try to fix them.

**Comment by Zireael07** [comment]
I like the rephrased paragraph more <3

**Comment by TheShadowOfHassen** [comment]
I don't understand <3 but I'm glad you like it. I'll put it in my next NR rewrite PR. Whenever I have time to do it.

**Comment by Wedge009** [comment]
> I don't understand <3

It's a 'smiley' for a heart symbol. Visualise it rotated 90 degrees anti-clockwise.

**Comment by eyalroz** [comment]
> might arose envy from afar

might arouse, I think you meant?

**Comment by TheShadowOfHassen** [comment]
Oh a heart. I should have seen that.

yes I meant arouse. I find it very ironic that even when I'm trying to edit stuff I still get typos.

**Comment by TheShadowOfHassen** [comment]
I made a pull request with the new paragraph. It's #7628.

**Comment by C0mpi11er** [comment]
what about using the word "Savor" to replace the first reckoning word

**Comment by eyalroz** [comment]
@C0mpi11er : Can you "cannily savor" something? I don't know...

**Comment by eyalroz** [comment]
ALso - I see references to a couple of MRs from May, but it doesn't look like they've gotten rid of the double-"reckon"ing.

**Comment by TheShadowOfHassen** [comment]
I was going to change it but the powers that would be thought it was ok. Honestly, though while it might not be proper for formal writing, I've read a lot of fiction with sentences with similar words that close together.

**Comment by eyalroz** [comment]
> but the powers that would be thought it was ok

Well, this bug has not been closed, so - I guess enough powers-that-be agree that it isn't ok. 

The point is not so much propriety, as user experience. When a user reads this, they think "Oh, someone was trying to sound erudite and eloquent using fancy vocabulary like 'reckon', but actually, that was just for show, since their vocabulary is too small to find anything other than 'reckon' to say later in that sentence." - it's annoying and distracting from the the narrative spirit.

**Comment by C0mpi11er** [comment]
so whats the best bet

**Comment by nemaara** [comment]
Closing via 6ae178d74d0.

**Comment by eyalroz** [comment]
I reckon this does the trick. So much discussion over a word tweak...

**Comment by Wedge009** [comment]
> For a small change like this, I suggest making a PR.
