### ISSUE TITLE
HttT S17: Uses deprecated wesnoth.special_locations table

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#6517]
Version: current master, c0d1293757cd2592558a5e3b78b5a09637bf9718.

Although `wesnoth.special_locations` is deprecated, it's still used in HttT S17's event where Delfador determines the location of the Sceptre. I haven't playtested, I'm just looking for examples of `wesnoth.deprecate_api` being used with a table:

```
data/campaigns/Heir_To_The_Throne/scenarios/17_Scepter_of_Fire.cfg:                local sceptre_loc= wesnoth.special_locations.sceptre
data/lua/core/map.lua:  wesnoth.special_locations = wesnoth.deprecate_api('wesnoth.special_locations', 'wesnoth.current.map.special_locations', 1, nil, setmetatable({}, {
```

**Comment by Wedge009** [comment]
Dummy's question: I'm not sure what `deprecate_api` is supposed to - is it to flag things that are considered deprecated? Maybe the wiki is not up-to-date because the only reference to `special_locations` I could find was https://wiki.wesnoth.org/LuaAPI/types/map, and I don't see any mention of deprecation there.

**Comment by stevecotton** [comment]
Before reading the exact answer, please would you review the updated docs for `deprecate_api` in @CelticMinstrel's #6483 ? It would be great to have a fresh pair of eyes check that over, and it's at the very top of the first file in the Github's diff.

<span title="it's used for renaming w.x to w.map.x like this: w.x=deprecate_api('w.x', 'w.map.x', ...)">Spoiler with exact answer (mouseover to see it)</span>

**Comment by knyghtmare** [comment]
> wesnoth.special_locations renamed to map.special_locations (note: the length operator is no longer supported)

https://wiki.wesnoth.org/LuaAPI/UpdatingFrom14

I think it's just renaming it to `map.special_locations` for a fix.

**Comment by stevecotton** [comment]
I think it's just that rename + retesting. Logged it as a bug because I was in the middle of the documentation review and didn't want to get sidetracked.

**Comment by Wedge009** [comment]
The UpdatingFrom14 wiki page was helpful, thanks. I looked at #6483 as well but I don't think I have anything constructive to add there.

I did a check and it looks like this is the only location where the deprecated call is still being used.
