### ISSUE TITLE
After latest flatpak update Wesnoth does not load

### ISSUE THREAD

**Issue by MXB2001** [wesnoth/wesnoth#6523]
### Game and System Information
 - What version of the game are you running?
1.16.2
 
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
flatpak 

 - What OS are you running?
Linux Debian 9

### Describe the bug
flatpak run org.wesnoth.Wesnoth
Battle for Wesnoth v1.16.2 x86_64
Started on Tue Feb 15 15:14:24 2022
$

is all I get

### To Reproduce
Probably only affects my setup

### Additional context
1.16.2 flatpak ran fine under 20.08 but now that it was "updated" to 21.08 it is broken

21.08 doesn't seem to work well on my computer, previously I only used it with Mozilla Firefox (latest version) and it crashed until I turned off hardware acceleration in Firefox

**Comment by Pentarctagon** [comment]
Cross-posting from https://forums.wesnoth.org/viewtopic.php?p=671609#p671609 - this issue doesn't happen for me.

**Comment by Wedge009** [comment]
Candidate for closing, given the age?

**Comment by Pentarctagon** [comment]
It's not reproducible for anyone else and the person reporting it found a work around, so I'd say closing is fine.
