### ISSUE TITLE
CI, Doxygen and Lua 5.4.4

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#6528]
Something about the Lua 5.4.4 changes is causing Doxygen to generate warnings in unrelated code. Looks like a Doxygen bug, but for the moment it breaks our CI builds:

```
Executing Doxygen check
Found doxygen errors or warnings!
/home/wesnoth-CI/src/actions/heal.cpp:45: warning: documented symbol 'heal_unit::heal_unit' was not declared or defined.
/home/wesnoth-CI/src/actions/heal.cpp:66: warning: documented symbol 'POISON_STATUS @8::poison_status' was not declared or defined.
/home/wesnoth-CI/src/actions/heal.cpp:83: warning: documented symbol 'POISON_STATUS @8::poison_progress' was not declared or defined.
/home/wesnoth-CI/src/actions/heal.cpp:159: warning: documented symbol 'bool @8::update_healing' was not declared or defined.
/home/wesnoth-CI/src/actions/heal.cpp:180: warning: documented symbol 'int @8::heal_amount' was not declared or defined.
/home/wesnoth-CI/src/actions/heal.cpp:234: warning: documented symbol 'void @8::do_heal' was not declared or defined.
/home/wesnoth-CI/src/actions/heal.cpp:250: warning: documented symbol 'void @8::animate_heals' was not declared or defined.
```

By brute-force reverting files, I found that the specific chunk of dd509518e09a0ac686ae129647d1d60f3d139285 that triggers the Doxygen bug is:
```
diff --git a/src/lua/lobject.h b/src/lua/lobject.h
index 1cc8e757bf1..abf5c2b1cca 100644
--- a/src/lua/lobject.h
+++ b/src/lua/lobject.h
@@ -140,6 +140,10 @@ typedef struct TValue {
 */
 typedef union StackValue {
   TValue val;
+  struct {
+    TValuefields;
+    unsigned short delta;
+  } tbclist;
 } StackValue;
```

**Comment by Wedge009** [comment]
That's an incredibly obscure issue - thanks for tracking this down and working around it so promptly.

**Comment by stevecotton** [comment]
> Should we attempt to report this to Doxygen? The project appears to be on GitHub also, so linking issues will be easy.

My feeling is no, at least not if the only way that we can reproduce it is with the full Wesnoth source code; there are other similar structures within Lua that aren't triggering the bug, so it seems unlikely that we could easily isolate a minimal test case based on Wesnoth. They have 1800 open issues, so I think there's more chance of them fixing this by fixing an existing issue that there is of them debugging it in our code.
