### ISSUE TITLE
Crash on Windows 11

### ISSUE THREAD

**Issue by moichia** [wesnoth/wesnoth#6530]
### Game and System Information
 - What version of the game are you running? 1.16.1
 - Where did you download it from? itch.io
 - If you're using a custom build, what compiler did you use, and what commit did you build at? No
 - What OS are you running? Windows 11

### To Reproduce

1. First..
2. Then...
3. Lastly...

### Savefiles
If applicable, attach savefiles to help explain your problem. (To find savefiles, start Wesnoth, click on the `i` button at the bottom left corner of the title screen, and open the `Saved games` directory.)

### Additional context
Add any other context (compiler logs, console output, etc) about the problem here.

**Comment by Pentarctagon** [comment]
To clarify, just saying "it crashed" essentially is not enough information for us to do anything useful with.
