### ISSUE TITLE
add-ons server not connecting other problem

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#6533]
### Game and System Information
 - What version of the game are you running?1.17(master)
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)built from source
 - If you're using a custom build, what compiler did you use, and what commit did you build at? gcc8, and problem begin in october 2021
 - What OS are you running? windows 7 

### Describe the bug
A clear and concise description of what the bug is. the bug is described in [add-ons server not connecting other problem](https://forums.wesnoth.org/viewtopic.php?p=671671#p671671) by arnaudlui but i can said what when i tried to acces toaddons.server, i have "distant server disconnected".

### To Reproduce

1. First.. start game
2. Then... click on addons button
3. Lastly... try to connect

### Expected behavior
game must be connect to addons server

**Comment by Pentarctagon** [comment]
Cross-posting fromhttps://forums.wesnoth.org/viewtopic.php?t=55426:

It looks like it isn't using the updated certificate to connect - the DST Root CA X3 certificate that the logs mention [has expired](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021). Windows 7 supposedly should work fine as per [this](https://letsencrypt.org/docs/certificate-compatibility/) which for Windows says
> Windows >= XP SP3 (assuming Automatic Root Certificate Update isn’t manually disabled)

**Comment by Pentarctagon** [comment]
Could you post what you did to install the new certificate in the forum thread, so the other person can do the same?

**Comment by newfrenchy83** [comment]
it done

**Comment by Pentarctagon** [comment]
Thanks!
