### ISSUE TITLE
a way to manually scale text and/or ui

### ISSUE THREAD

**Issue by dryluggage** [wesnoth/wesnoth#6547]
### Game and System Information
 game version: 1.16.2
Arch linux

### Describe the desired feature
i want a way to manually scale the text so i can see/read it better.
like a option in the optionmenu

i know there is this pullrequest https://github.com/wesnoth/wesnoth/pull/4860 but i dont see a way to scale the text in the options.

**Comment by Wedge009** [comment]
Scaling in general is pretty finicky and the results has been mixed. It was actually removed altogether in 1.14, if I recall correctly, and before being restored in 1.15 and ultimately made into an automatic process in that PR you mentioned. So it begs the question of what is wrong with that implementation that you're having difficulty with? Perhaps this should be a bug report instead, if you can post the results you're getting and what you would prefer instead for the UI scaling.

**Comment by dryluggage** [comment]
i cant see that well so the text especially the campaign  and unit text is hard to look at and i have to focus harder. i want maual text scaling to be able to make it easier on the eyes
![wes](https://user-images.githubusercontent.com/58333865/156919747-c546151f-354a-4055-8c1f-3cea67fe2c3d.png)

**Comment by CelticMinstrel** [comment]
This kind of reason was why I originally added the font scaling option to preferences. However, it caused issues on the right sidebar in particular, so the option was removed from preferences.

All the code for it still exists though, so you should be able to activate it by manually adding a `font_scale` option to the preferences file, which takes a percentage. However, it really does break the text in the sidebar, so I don't know if that trade-off is worthwhile.

**Comment by Wedge009** [comment]
The scaling looks okay to me, so this sounds like a case of the user wanting to go beyond what's intentional in the existing automated scaling. This is fine, just pointing out that it's not a case of the automated scaling doing something wrong.

As pointed out, the manual scaling can have unexpected effects on the rest of the interface and there were numerous bug reports pointing this out, so even if you re-enable the manual scaling in the `preferences` file, just be prepared that other things can be adversely affected.

**Comment by cooljeanius** [comment]
Maybe have separate scaling settings so there's one for the sidebar and another for all other text?

**Comment by CelticMinstrel** [comment]
GUI2 and GUI1 text _are_ handled separately by the scaling parameter, but GUI1 also includes the help, so I'm not sure how hard it would be to separate the help browser from the sidebar.

**Comment by cooljeanius** [comment]
> This kind of reason was why I originally added the font scaling option to preferences. However, it caused issues on the right sidebar in particular, so the option was removed from preferences.
> 
> All the code for it still exists though, so you should be able to activate it by manually adding a `font_scale` option to the preferences file, which takes a percentage. However, it really does break the text in the sidebar, so I don't know if that trade-off is worthwhile.

So this is what 2de3246 added back, right? (I know I asked that elsewhere, too, but I'm just [building the web](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Linking#General_principles) here so everyone in all relevant issues are on the same page)

**Comment by CelticMinstrel** [comment]
Yes, that just exposes the existing preference in the UI again (editing the preferences file manually has worked this whole time).

**Comment by ajay-anand** [comment]
> This kind of reason was why I originally added the font scaling option to preferences. However, it caused issues on the right sidebar in particular, so the option was removed from preferences.
> 
> All the code for it still exists though, so you should be able to activate it by manually adding a `font_scale` option to the preferences file, which takes a percentage. However, it really does break the text in the sidebar, so I don't know if that trade-off is worthwhile.

For such games, the instructions for beginners are important and the dialogues and story are 50% of the meat. I was about to ignore this game, but this comment saved the fun. I had already stumbled upon the preferences file. Now the game is learnable and playable. Thanks.

**Comment by Wedge009** [comment]
I feel like this can be closed since there is automated scaling as of 1.18 (with option to override) and I think this scaling is an improvement over what we had previously (what's discussed here). And #8608 covers the in-between cases.

**Comment by CelticMinstrel** [comment]
For what it's worth, I don't think the overall UI scaling negates any need for a separate font scaling. But it seems fine to close this since both preferences are now accessible.
