### ISSUE TITLE
background image don't appear in start menu

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#6564]
### Game and System Information
 - What version of the game are you running?
 
 master branch

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
 
built from source

 - If you're using a custom build, what compiler did you use, and what commit did you build at?

 gcc and support for webpp

 - What OS are you running?
 
windows

### Describe the bug

When i sart the game, background image no longer visible

### To Reproduce

1. First.. start game

### Expected behavior

image background must be visible, libwebpp present but includes not implemented in source code.

**Comment by Pentarctagon** [comment]
You need to have libwepb present and SDL2_image built with webp support enabled.

**Comment by newfrenchy83** [comment]
i have [SDL2_image-devel-2.0.5-mingw.tar.gz](https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-mingw.tar.gz) with libwebp external binarie updated, but don't change.

**Comment by newfrenchy83** [comment]
imust have convert each image in other format then.

**Comment by Pentarctagon** [comment]
The plan is to eventually start converting many other images to webp as well, since the file size is significantly smaller. We're not going to ship two versions of the same image.

**Comment by Pentarctagon** [comment]
Is there a reason you don't use Visual Studio?

**Comment by newfrenchy83** [comment]
issue solved, i forget to pull good sdl_image.dll in fold
