### ISSUE TITLE
Build of 1.17.2 fails

### ISSUE THREAD

**Issue by limburgher** [wesnoth/wesnoth#6566]
### Game and System Information

- 1.17.2
- wesnoth.org
- Scons
- Fedora 35, for RPM

### Description of the bug

I'm the Fedora wesnoth maintainer and 1.17.2 fails to build:

### Steps to reproduce the behavior

1. Unpack tarball
2. Install prerequisite RPMs
3.scons wesnoth wesnothd campaignd prefix=%{_prefix} \
          bindir=%{_bindir} \
          libdir=%{_libdir} \
          boostdir=%{_includedir} \
          boostlibdir=%{_libdir} \
          localedirname=locale \
          python_site_packages_dir=%{python3_sitelib}/wesnoth \
          extra_flags_release="$RPM_OPT_FLAGS $RPM_LD_FLAGS" \
          %{?_smp_mflags}

+ scons wesnoth wesnothd campaignd prefix=/usr bindir=/usr/bin libdir=/usr/lib64 boostdir=/usr/include boostlibdir=/usr/lib64 localedirname=locale python_site_packages_dir=/usr/lib/python3.10/site-packages/wesnoth 'extra_flags_release=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 ' luadir=/usr/include -j4
scons: Reading SConscript files ...
Building Wesnoth version 1.17.2
Mkdir("build")
---[checking prerequisites]---
Checking for C header file sys/sendfile.h... yes
Checking for C function sendfile()... yes
Checking whether C++ compiler works (g++ version >= 7 required)... yes
Checking for Boost iostreams library version >= 1.66... yes
Checking for gzip support in Boost Iostreams... yes
Checking for bzip2 support in Boost Iostreams... yes
Checking for Boost program_options library version >= 1.66... yes
Checking for Boost random library version >= 1.66... yes
Checking for Boost smart_ptr library... yes
Checking for C library pthread... yes
Checking for Boost system library... yes
Checking for Boost asio library... yes
Checking for Boost context library... yes
Checking for Boost coroutine library... yes
Checking for Boost thread library... yes
Checking for Boost locale library... yes
Checking for Boost filesystem library... yes
INFO: Base prerequisites are met
Checking for available Boost Locale backends... icu,posix,std
Checking whether compiler has built-in -D_FORTIFY_SOURCE... no
Checking for C library libcrypto... yes
Checking for C library ssl... yes
Checking for Simple DirectMedia Layer library version >= 2.0.8... yes
Checking for SDL2_mixer library... yes
Checking for SDL2_image library... yes
Checking for C library vorbisfile... yes
Checking for Ogg Vorbis support in SDL... yes
Checking for PNG support in SDL... yes
Checking for JPG support in SDL... no
Checking for WebP support in SDL... yes
Checking for Cairo... (cached) yes
Checking for Pango with cairo backend... (cached) yes
Checking for fontconfig... (cached) yes
Checking for Boost regex library... yes
WARNING: Lua submodule does not exist. You must run 'git submodule update --init --recursive' to initialize it.
WARNING: Client prerequisites are not met. wesnoth cannot be built.
WARNING: Unit tests are disabled because their prerequisites are not met
  If any config checks fail, look in build/config.log for details
  If a check fails spuriously due to caching, use --config=force to force its rerun
---[applying configuration]---
Unable to find source files for: mariadbpp
scons: done reading SConscript files.
scons: Building targets ...
error_action(["wesnoth"], [])
g++ -o build/release/server/common/dbconn.o -c -Werror=non-virtual-dtor -std=c++17 -Wold-style-cast -Wextra -pthread -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wtrampolines -fPIE -O3 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DHAVE_CONFIG_H -D_FORTIFY_SOURCE=2 -DLOAD_REVISION -DFIFODIR='"/var/run/wesnothd"' -DWESNOTH_PATH='"/usr/share/wesnoth"' -DLOCALEDIR='"locale"' -DHAS_RELATIVE_LOCALEDIR -Ibuild -Isrc src/server/common/dbconn.cpp
g++ -o build/release/server/common/forum_user_handler.o -c -Werror=non-virtual-dtor -std=c++17 -Wold-style-cast -Wextra -pthread -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wtrampolines -fPIE -O3 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DHAVE_CONFIG_H -D_FORTIFY_SOURCE=2 -DLOAD_REVISION -DFIFODIR='"/var/run/wesnothd"' -DWESNOTH_PATH='"/usr/share/wesnoth"' -DLOCALEDIR='"locale"' -DHAS_RELATIVE_LOCALEDIR -Ibuild -Isrc src/server/common/forum_user_handler.cpp
scons: *** [wesnoth] Target disabled because its prerequisites are not met
g++ -o build/release/server/common/resultsets/ban_check.o -c -Werror=non-virtual-dtor -std=c++17 -Wold-style-cast -Wextra -pthread -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wtrampolines -fPIE -O3 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -DHAVE_CONFIG_H -D_FORTIFY_SOURCE=2 -DLOAD_REVISION -DFIFODIR='"/var/run/wesnothd"' -DWESNOTH_PATH='"/usr/share/wesnoth"' -DLOCALEDIR='"locale"' -DHAS_RELATIVE_LOCALEDIR -Ibuild -Isrc src/server/common/resultsets/ban_check.cpp
scons: building terminated because of errors.
error: Bad exit status from /var/tmp/rpm-tmp.3bIZCM (%build)

### Expected behavior

Wesnoth builds from tarball without needing an additional git repo

**Comment by Pentarctagon** [comment]
According to the scons check: `Checking for JPG support in SDL... no`

Which would indicate that the SDL2_image being used wasn't built with JPG support enabled?

**Comment by loonycyborg** [comment]
Would need to see build/config.log if it's caused by something different than lacking JPG support

**Comment by loonycyborg** [comment]
Seems config check is trying to load image that doesn't exist. Something went horribly wrong when making tarball.
Commands I used to make it:
`git archive --format=tar --prefix="wesnoth-$VERSION/" $VERSION > "wesnoth-$VERSION.tar"`
`tar rf wesnoth-$VERSION.tar src/modules`
It didn't add submodules too

**Comment by limburgher** [comment]
That's what I thought but I wasn't sure what your release process is.

**Comment by loonycyborg** [comment]
I figured out how to add submodules to tarball properly, but JPG issue isn't caused by this. Instead it's caused by config check referencing image from attic/ dir that exists in git repo but not added to tarballs, it was different image in 1.17.1, not from attic.

**Comment by Pentarctagon** [comment]
Ah, that'd be my fault then. The jpg check was previously looking at the main menu background, which was changed to webp, so I had it check something in attic thinking "well, nothing in attic every gets deleted".

**Comment by loonycyborg** [comment]
Command to add submodules should be `tar --transform="s,^,wesnoth-$VERSION/," --append --file wesnoth-$VERSION.tar src/modules/` because git archive adds prefix.

**Comment by loonycyborg** [comment]
As far as 1.17.2 is concerned I can reupload the tarball with submodules and that one attic file added.

**Comment by Pentarctagon** [comment]
Just let me know when so I can updated the sha hash for that.

**Comment by Pentarctagon** [comment]
Also the CI artifact is generated using:
```
git archive --format=tar HEAD > wesnoth.tar
tar rf wesnoth.tar src/modules/
bzip2 -z wesnoth.tar
mv wesnoth.tar.bz2 ~/wesnoth-$version.tar.bz2
```
which does include the submodules correctly.

**Comment by loonycyborg** [comment]
It will be a "tar bomb" without path prefix though.

**Comment by loonycyborg** [comment]
Fixed tarball uploaded.

**Comment by Pentarctagon** [comment]
Updated the sha hashes as well.

**Comment by limburgher** [comment]
Works perfectly, thank you for the quick resolution!
