### ISSUE TITLE
Font error 

### ISSUE THREAD

**Issue by RichardsATcn** [wesnoth/wesnoth#6580]
### Game and System Information

- **Version:* 1.16.2*
- **Downloaded from:* steam and sourcefoge*
- **Build info:* *
- **OS:* windows 10 x64*
![1648188790(1)](https://user-images.githubusercontent.com/8119891/160065019-798c7f70-7d77-4e9f-aade-41e7ec0105d7.png)
![1648188816(1)](https://user-images.githubusercontent.com/8119891/160065026-db2d237c-53bf-4b10-b66f-67216687f30e.png)
![1648188790(1)](https://user-images.githubusercontent.com/8119891/160065131-f0ae3514-e2c1-4018-839c-930f6ea6c068.png)
![1648188941(1)](https://user-images.githubusercontent.com/8119891/160065145-ce0d1e51-6e6d-41b7-9c8b-64ae24fdd717.png)
![Uploading 1648188988(1).png…]()

### Description of the bug

any language  Display Error 

### Steps to reproduce the behavior

1.
2.
3.

**Comment by Wedge009** [comment]
The screens appear to be for Simplified Chinese. At first I thought it might be related to #1549 but it doesn't appear to be the case. We'll need more info, because testing 1.16.2 release I could not replicate this in Linux, Windows 10, or Windows 7.

**Comment by Wedge009** [comment]
Without further information I don't think anyone can help with this and the issue could be closed.
