### ISSUE TITLE
[Map Editor] "Time Schedule Menu" on top right toolbad does Nothing. At all.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6581]
### Game and System Information

1.17.2+dev
github
Latest
Windows 10 MingW 64Bit

### Description of the bug

This menu does nothing in Map Editor Mode but it's still there and accessible

### Steps to reproduce the behavior

1. Open map Editor
2. Select "Time Schedule Menu" and then "Time Schedule Editor"
3. Try setting some values there and click 

### Expected behavior

color is adjusted as stated by the RGB values in the menu GUI
OR,
It's grayed out and inactive as it's a Scenario Editor feature and not map editor.

### Additional context

![Uploading image.png…]()

Also, the image uploading of this template is broken

**Comment by knyghtmare** [comment]
![image](https://user-images.githubusercontent.com/5283677/160207569-2c140247-2a1c-41d1-9cbc-3bbc6ce676da.png)

**Comment by Wedge009** [comment]
This seems related to #5259 - as you note these features are only available in Scenario editing and not just a plain Map edit. Perhaps these functions should be greyed out when only in map-edit mode.

**Comment by knyghtmare** [comment]
> This seems related to #5259 - as you note these features are only available in Scenario editing and not just a plain Map edit. Perhaps these functions should be greyed out when only in map-edit mode.

Oh, thanks for pointing out that this is a duplicate issue. Maybe making this option inactive/grayed out when map editor is active? That seems to be the most optimal thing to do. Otherwise, it just misleads/disappoints map-makers.

(since this is a duplicate, it can also be closed as is)

**Comment by Wedge009** [comment]
Both are your issues, I thought you were best placed to make that judgement.
