### ISSUE TITLE
[SotA] [Campaign] Update Terrain Codes for this file.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6591]
https://github.com/wesnoth/wesnoth/blob/c1896bb79ed345219bc5435973623391aa219681/data/campaigns/Secrets_of_the_Ancients/utils/terrain-compat.cfg#L5

This was stated to be done and removed in 1.15.6 and it's now almost 1.17.3. When viewing these terrain from the editor, they are all deprecated.

**Comment by Wedge009** [comment]
Looks like @doofus-01 did this as part of #6751.
