### ISSUE TITLE
Unit can become co-located with wall in NR Pursuit

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#6607]
### Game and System Information

- **Version:** 1.17.2
- **Downloaded from:** Uh... sourceforge, I guess.
- **Build info:**  GCC 10.2
- **OS:** Devuan GNU/Linux Chimaera,

### Description of the bug

In NR scenario "The Pursuit", when you enter the Great Chamber - if another unit happens to be on one of the two hexes which are closed in to become a wall - those  units co-locate with the wall hex, and can move to either direction.

That's probably not what you wanted...

### Steps to reproduce the behavior

Just be careful not to trigger the Great Chamber before moving some units onto the cave tiles which become wall.

### Expected behavior

Good question. Either create a wall/door which doesn't take up a full hex, closing the back units off, or alternatively, nudge them southwards. A cruel option would be to kill them off.

**Comment by Wedge009** [comment]
Ignore the above links - referenced the wrong issue.

**Comment by Wedge009** [comment]
@Descacharrado I recall some unit-stuck-in-wall issues that you resolved for UtBS (eg #6369), similarly there's the avoiding-the-chasm changes that you made in #6357. If you have time, could you please have a look at this scenario and see if something similar would resolve this issue too?

**Comment by Descacharrado** [comment]
Sure, I just got back from my March wes-cation. The best fix I can think of is moving the unit back or forward from that "door". I'll comment further on the PR.
