### ISSUE TITLE
[MP] MP Server2 harshly rejects 1.17.2+dev client

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6613]
Screenshot says it all
![image](https://user-images.githubusercontent.com/5283677/162029503-c7c6e234-7f2c-4364-a9e8-b636ef7cdb70.png)

Apparently, it seems Wesnoth 1.17.2+dev cannot enter the server2 instance. Hence, I cannot play MP with my brother (who has a 1.17.1 client). :(

**Comment by Pentarctagon** [comment]
@soliton- or @loonycyborg

**Comment by Wedge009** [comment]
This is a standard message when the server doesn't accept the version, right? I was just wondering about the 'harshly'. I grant it's an issue, though.

**Comment by soliton-** [comment]
There is no dev server running on server2. I can allow dev clients on the stable server and leave it up to players to figure out any issues with incompatibilities between versions.

**Comment by Pentarctagon** [comment]
Taking a quick look at https://status.wesnoth.org/ confirms that, actually.

So is this invalid, or a feature request?

**Comment by soliton-** [comment]
I can do what I suggested. If there is no interest then there is nothing to be done unless someone else wants to maintain a dev server on server2.
