### ISSUE TITLE
[Terrain] [Editor] Properly assign Terrain types to appropriate terrain groups

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6643]
Some terrain types seem to be not properly assigned to their appropriate groups.

An example is the Elven Winter Castle. Which is supposed to be in both castle and frozen but is in castle group only. Thus, someone using a frozen terrain kit misses out on that terrain type's existence.

This is just one example. More might be present.

**Comment by Wedge009** [comment]
Are these terrain groups defined somewhere or are they calculated on-the-fly somehow?
