### ISSUE TITLE
[ThoT] Forbidden forest too hard relative to difficulty level

### ISSUE THREAD

**Issue by dukc** [wesnoth/wesnoth#6666]
### Game and System Information

- **Version:** 1.16.1
- **Downloaded from:** [nixpkgs](https://search.nixos.org/packages?channel=unstable&show=wesnoth&from=0&size=50&sort=relevance&type=packages&query=wesnoth)
- **OS:** NixOS 21.11

### Description of the bug

The scenario "Forbidden Forest" in "Hammer of Thursagan" is far more difficult on "challenging" than challenging scenarios usually are. I undestand that before the rework of ThoT one likely had mages to help fight in forest, and also the previous scenario was something that granted more carryover gold.

### Steps to reproduce the behavior

1. Give yourself little (under 40) to no carryover gold. That's what is realistic after "fear".
2. The gryphon rider is alive and level 2. I have 3 steelclads, 3 pathfiders, 3 thunderguards and a stalwart at the recall list. 2 of the stalwarts and one pathfinder are close to levelup. In my opinion, this is a reasonable recall list for "challeging".
3. Aiglondour and Movrur are both level 2 and close to levelup. Angarthing is level 3.
4. Try it. The scenario is maybe possible with these, but far more difficult than about anything else on "challeging".

**Comment by knyghtmare** [comment]
Save file?

**Comment by dukc** [comment]
[Tv-Kielletty metsä uusinta.gz](https://github.com/wesnoth/wesnoth/files/8599217/Tv-Kielletty.metsa.uusinta.gz)

This includes a replay of the scenario to tenth turn. While the replay ends before the result is clear it does give an idea how difficult the scenario is.

**Comment by knyghtmare** [comment]
[Tv-Kielletty metsä replay 20220501-222919.gz](https://github.com/wesnoth/wesnoth/files/8599304/Tv-Kielletty.metsa.replay.20220501-222919.gz)

Here you go. It's not _that_ difficult. You have to rely on the resistance of Dwarven units and maintaining a defensive tactic. Do not let units wander outside the formation and kill off elves as fast as possible to prevent encirclement.

**Comment by cooljeanius** [comment]
I wonder if this is something that changed with the changes made to THoT for 1.16? Like, previously in 1.14, you used to get Mages from Ratheln right before this scenario, didn't you?

**Comment by knyghtmare** [comment]
> I wonder if this is something that changed with the changes made to THoT for 1.16? Like, previously in 1.14, you used to get Mages from Ratheln right before this scenario, didn't you?

I checked what changed...seems it was made _easier_ on all difficulties on 1.16...so with that change..I think it being too hard now is more inline with skill issue or a misunderstanding of what knalgan alliance faction tactic to employ.

**Comment by cooljeanius** [comment]
> > I wonder if this is something that changed with the changes made to THoT for 1.16? Like, previously in 1.14, you used to get Mages from Ratheln right before this scenario, didn't you?
> 
> I checked what changed...seems it was made _easier_ on all difficulties on 1.16...so with that change..I think it being too hard now is more inline with skill issue or a misunderstanding of what knalgan alliance faction tactic to employ.

easier just to the point of compensating for no longer having access to Mages? Or beyond that?

**Comment by knyghtmare** [comment]
> easier just to the point of compensating for no longer having access to Mages? Or beyond that?

Entirely. Checking the rebalance commit, all difficulties have been made easier.

afbd7e0237cb762bd932dfde659efa8157f7169e

**Comment by cooljeanius** [comment]
Those are some really minor gold/income differences; I don't think it fully compensates for the loss of mages

**Comment by knyghtmare** [comment]
>  I don't think it fully compensates for the loss of mages

what do you think this "loss" is?
1. lost of a damage-tole unit (Red Mage/Arch Mage)
2. Lich counter unit (Silver Mage)
3. healer (White/MoL)

Currently THoT seems doable without mages, and given that XP-eating Mages are not in player army anymore, you can get more Steelclads and Lords which are pretty much what you need to pass the campaign with very little effort.

**Comment by dukc** [comment]
> Here you go. It's not that difficult. You have to rely on the resistance of Dwarven units and maintaining a defensive tactic. Do not let units wander outside the formation and kill off elves as fast as possible to prevent encirclement.

I'm not claiming it can't be done, nor that there would not be some issues in my tactics. My point is that the difficulty level is supposed to be challeging, not nightmare. No other "challenging" scenario I know of (not just in this campaign) requires finer play than what you see on the replay, unless one is seriously short on veterans and/or missed opportunity for carryover gold. 

> I wonder if this is something that changed with the changes made to THoT for 1.16? Like, previously in 1.14, you used to get Mages from Ratheln right before this scenario, didn't you?

I'm not sure if I have played this scenario then, but if I had mages they would definitely help a lot.

> what do you think this "loss" is?
Isn't it obvious? Mages benefit defensively from forest, unlike dwarves. And the their magical attack is more important than usual because elves enjoy from such high defence.
