### ISSUE TITLE
NR Showdown - Hamel should have leadership

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#6683]
### Game and System Information

**Version:** 1.17.3
**Downloaded from:**  Source, from here, I think.
- **Build info:** N/A
- **OS:** Devuan GNU/Linux Chimaera

### Description of the bug

Hamel, the Dwarf leader, is the one who trains Tallin in Leadership. Yet, when showing up in the final scenario - Showdown - he doesn't have the Leadership trait. That doesn't make sense IMHO.

### Steps to reproduce the behavior

N/A

### Expected behavior

Hamel should have Leadership. If you want to penalize the Dwarven faction to account for this, downgrade a unit to a lower level or reduce the Gold slightly etc.

**Comment by knyghtmare** [comment]
Given that he is AI controlled (last time I played NR) and hardly moves from Keep, is this really feasible?
It's no issue adding it if it's just for flavor.

Also, NR is being reworked so I will take your request for Hamel having leadership into consideration.

**Comment by eyalroz** [comment]
@knyghtmare : He's player-controlled right now.

**Comment by knyghtmare** [comment]
> He's player-controlled right now.

Ah, so it's worse than I remember.
