### ISSUE TITLE
Unit standing animations stopped working

### ISSUE THREAD

**Issue by Vultraz** [wesnoth/wesnoth#6692]
I just noticed recently that unit standing animations aren't on current master. working. Idle animations do play, but units with standing animations - like the Spearman - just stand still. I'm not sure when exactly this cropped up...

**Comment by Pentarctagon** [comment]
A bisect would be useful.

**Comment by knyghtmare** [comment]
```ini
 [standing_anim]
        start_time=0
        {WOUNDED_UNIT ()}
        [if]
            direction=s,se,sw
            [frame]
                image="units/human-loyalists/spearman.png:400"
            [/frame]
            [frame]
                image="units/human-loyalists/spearman-stand-s-[1~6].png:[150*2,300,100*3]"
            [/frame]
        [/if]
        [else]
            direction=n,ne,nw
            [frame]
                image="units/human-loyalists/spearman-n.png:400"
            [/frame]
            [frame]
                image="units/human-loyalists/spearman-stand-n-[1~3,2~1].png:[150*2,400,150*2]"
            [/frame]
        [/else]
    [/standing_anim]
```
Some only show if the unit is wounded (has 33% HP left)

**Comment by Vultraz** [comment]
Was that a recent change?

**Comment by knyghtmare** [comment]
> Was that a recent change?

https://github.com/wesnoth/wesnoth/pull/5388

**Comment by Pentarctagon** [comment]
Is this actually a bug then?

**Comment by knyghtmare** [comment]
More of a feature than a bug

**Comment by CelticMinstrel** [comment]
Having separate standing animations when wounded is definitely a feature.

Having no animation when healthy but a standing animation only when wounded though, that seems like a bug to me.

**Comment by Pentarctagon** [comment]
It sounds like that was the intention of the above linked PR though.

**Comment by CelticMinstrel** [comment]
I don't really get that impression? He didn't like how exaggerated the standing animations were when healthy. That doesn't necessarily mean he feels they shouldn't be animated at all.

**Comment by Pentarctagon** [comment]
If you prevent the current animations from being run, and don't add new animations, then the logical conclusion is that there won't be any animations run.

**Comment by doofus-01** [comment]
There will eventually be new standing animations for the few units that got their heaving animations filtered.

**Comment by doofus-01** [comment]
Animations are a work in progress
