### ISSUE TITLE
Several portraits not showing

### ISSUE THREAD

**Issue by mesilliac** [wesnoth/wesnoth#6696]
### Game and System Information

- **Version:** master
- **Downloaded from:** git
- **Build info:** Release
- **OS:** Linux

### Description of the bug

Several portraits seem to be missing. I noticed it trying to look up "delfador.png" and "kalenz.png".

All i found when searching briefly was "delfador.webp" and "kalenz.webp".

I saw other portraits not working as well.

### Steps to reproduce the behavior

Play one of the campaigns, i guess. The above was from Heir to the Throne, but i saw portraits missing in other campaigns too.

### Additional context

Portraits all seemed to be working not long ago, this seems to have been caused by a recent commit (sometime in the past couple weeks).

**Comment by Wedge009** [comment]
It seems likely from #6611. I couldn't find any references to `kalenz.png` or `delfador.png`, though - only their new `.webp` counterparts. Also I did a quick check of the starting scenario for HttT and didn't find anything amiss. Recompiled master just now as at 7e878263038.

**Comment by mesilliac** [comment]
Hmm, so the scenario i was on was "Crossroads". I also didn't find any reference to delfador.png (and am on 7e878263038976a85dc114c3ae0f8903a8b2decc ). Could it be automatically putting together the ".png" extension somewhere?

Delfador does show up correctly on the starting scenario.

Oh, or perhaps it's that it was a loaded game? I've been swapping around different save games for testing other things.

**Comment by mesilliac** [comment]
Right - the image filename for units seems to be encoded into the save game. Maybe it would be a good idea to automatically convert those somehow?

This is the save game with Kalenz and Delfador, who both speak at the start of the scenario.
[HttT-Crossroads.gz](https://github.com/wesnoth/wesnoth/files/8651169/HttT-Crossroads.gz)

**Comment by CelticMinstrel** [comment]
We should add a rule in the image loading code that if the file isn't found, it tries switching the extension to webp before giving up.

**Comment by Pentarctagon** [comment]
Is there a central place in the code where finding and loading images is handled?

**Comment by CelticMinstrel** [comment]
> Is there a central place in the code where finding and loading images is handled?

Yes – the image cache.
