### ISSUE TITLE
An option to disable texture filtering on unit sprites

### ISSUE THREAD

**Issue by iddq-tea** [wesnoth/wesnoth#6700]
### Describe the desired feature

I am not a fan of texture filtering in pixel art. If some people really like it, it should be a feature you can toggle, instead of one that's forced. Better yet, for those who like it, there could be numerous filtering options to pick form. I would personally like to retain the crisp pixel look.

![texture_filtering](https://user-images.githubusercontent.com/86078609/168081689-b9adcf92-4401-4f71-b8f9-a6ed436e404f.png)

Left: Scaled by 200%, uses a texture filtering algorithm | Right: Scaled by 200%; unfiltered

**Comment by Wedge009** [comment]
It's interesting that you request this because this used to be an option - both the method of filtering as well as whether or not to filter at all. At some point it was removed... I'm not sure if my preferences file has overridden something but when I zoom in my units are presented scaled up without filtering, maybe something else happens in a fresh installation without pre-existing preferences set-up.

**Comment by iddq-tea** [comment]
> It's interesting that you request this because this used to be an option - both the method of filtering as well as whether or not to filter at all. At some point it was removed... I'm not sure if my preferences file has overridden something but when I zoom in my units are presented scaled up without filtering, maybe something else happens in a fresh installation without pre-existing preferences set-up.

Well that's annoying. Why remove such a good feature?
Can you please share your preferences file with me?

**Comment by iddq-tea** [comment]
> The screenshot posted seems to be from one of the UI elements, which I am currently working to convert to NN (pixel/unfilterd) scaling only. The scaling options @Wedge009 is referring to only applied to the gamemap and it allowed different scaling algorithms to be used based on zoom level. I removed that and made all map zooming use NN scaling.

Wonderful, the screenshot I took was from the unit recruit screen, with the unfiltered sprite slapped next to it. Glad to hear it's being worked on!
