### ISSUE TITLE
[WoF] Scenario objectives dialog should be succinct and not replace narrative dialog

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#6706]
### Game and System Information

- **Version:** 1.17.3
- **Downloaded from:** N/A
- **Build info:**  N/A
- **OS:** N/A

### Description of the bug

A point regarding the Scenario objectives dialog: This campaign tends to put excessive amounts of text there. The Scenario objectives should be succinct and straightforward, not poetic and involving motivation and story narrative. For example, instead of saying "Capture all villages so that our flight may have provisions", it should be just "Capture all villages". The text belongs in dialog at the beginning of the scenario (or sometimes later on). This goes also for comments such as "Units from enemy faction X will not try to do thing Y" - doesn't belong in the scenario objectives dialog, at least if one follows the custom from other campaigns.

### Steps to reproduce the behavior

N/A

### Expected behavior

N/A

### Additional context

N/A

**Comment by max-torch** [comment]
> This goes also for comments such as "Units from enemy faction X will not try to do thing Y"
What's wrong with Scenario Notes like these? Sometimes it's helpful to have clear info to inform your strategy and just be plain about what the player can expect.

Completely agree with the OP about the way the Scenario Objectives  themselves should be stated.
However, I don't know what's wrong with Scenario Notes.

**Comment by eyalroz** [comment]
> What's wrong with Scenario Notes like these?

I wouldn't say it's wrong per se. But:

1. It goes against the convention in all other campaigns.
2. It selective. Why describe only this aspect of computer-controlled sides' behavior when one can describe others as well?
3. It usually - in WoD - mixes up application info for the player and narrated information for the character the player is playing (and thus also different writing styles).
4. It can, and does, easily result in scenario notes which are long enough to sound like a repeat of part of the opening dialog.

**Comment by max-torch** [comment]
@eyalroz Can you mention some specific scenarios?

**Comment by eyalroz** [comment]
@max-torch : I've only played up to scenario 5, but here are a couple of examples.

* In "The Contention", there are 6 different points in the "Notes" - the last of which is 3 lines long, and has nothing to do with this scenario: "Should Gorlack stand victorious, he will forevermore have loyal intendants etc. etc." 
* In "The Contention", one of the notes reads: "Through the ways of Morogor, veterans may not be recall during the contention" instead of "Unit recall is disabled in this scenario" - or better yet, _nothing_, because the initial dialog should mention that you'll be using fresh recruits, plus, when you try to recall, it already says "You are separated from your soldiers and may not recall them".
* In "Reclamation", one of the objectives is "Then destroy the intruders' skimmers (boats) so they can escape not the hunt". Seriously? Try "Then destroy all opponent boats"  (or "boat units") And in fact, using "then" here is probably not a good idea, it sounds awkward. It would probably have been fine without it, i.e. "Destroy all opponent boats". If you want more literary flare, then "Sink all opponent boats".


etc.

**Comment by knyghtmare** [comment]
I agree with the title. Objectives should be displaying what you have to do in general in few words as possible. Rest of the information can go in the objective notes. However, if the "rest" is way too much, I recommend some other way of relaying that information to the player. Maybe via some right-click menu item which shows a pop-up.

**Comment by max-torch** [comment]
This issue is only about the Winds of Fate Campaign? If so, may I edit the Issue title and add "[WoF]"

**Comment by eyalroz** [comment]
@max-torch : Done.

**Comment by knyghtmare** [comment]
Pinging the WoF's maintainer @Jonathan-Kelly here to clarify/comment.

**Comment by Jonathan-Kelly** [comment]
Alright, I will cut down and simplify the objectives text. If anyone would like assign this issue to me, feel free to (it does not look like I have the permissions necessary to self-assign.)

**Comment by eyalroz** [comment]
@Jonathan-Kelly : And please put the more narrative comments into the start or end dialog, or even into mid-scenario dialog if necessary.

**Comment by Jonathan-Kelly** [comment]
A fix is now [committed](https://github.com/wesnoth/wesnoth/commit/6a2d638c4f9be2b23aed4670471c782bf0334ccd) so this can be closed.

**Comment by knyghtmare** [comment]
https://github.com/wesnoth/wesnoth/issues/6706#issuecomment-1222567881 Okay
