### ISSUE TITLE
Tell user somehow where screenshots are saved

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#6708]
When you press the "Print Screen" button, a screenshot is saved. But - _where_? There's no message saying where the shot was saved, nor is there information about the output directory for screenshot, in the preferences.

This information should be made available _somehow_.

**Comment by knyghtmare** [comment]
![image](https://user-images.githubusercontent.com/5283677/168443793-155d4f94-e5d4-4686-bcad-a21bafc0b21a.png)
Seems your request is already available

**Comment by Pentarctagon** [comment]
Closing, given there's already a button to open the screenshots folder.

**Comment by eyalroz** [comment]
@Pentarctagon : Where is that from? When I press "Print Screen" I don't get a dialog. Or - is this very recent? I'm using 1.17.3

**Comment by knyghtmare** [comment]
In Preferences, go to Hotkeys,
search "screenshot" and assign a hotket (alt+x) in my case. 
and then use the hotkey.

**Comment by eyalroz** [comment]
@knyghtmare : I wouldn't have guessed it... I assumed the hotkey for screenshot is "Print Screen" and there isn't a second-behavior for the same functionality.

**Comment by Pentarctagon** [comment]
If you're using the print screen key on your keyboard, that seems like the OS's responsibility to deal with? Wesnoth doesn't have anything to do with that key being used.

**Comment by eyalroz** [comment]
> If you're using the print screen key on your keyboard, that seems like the OS's responsibility to deal with?

You are absolutely right, Print Screen actually uses my desktop environment's facility. Silly me. So, accepting the closure and all is well.
