### ISSUE TITLE
[MacOS] Mouse and Screen UI elements are not Mapped accurately...at all

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6715]
- **Version:**
- **Downloaded from:**
- **Build info:**
- **OS:**
- 1.17.4
- SourceForge
- Client Download
- MacOS Big Sur 11.6.3

**Description of Bug:**

Screen UI buttons/elements are not being accurately with the mouse and the deviations are rather significant.

<img width="768" alt="Screenshot 2022-05-17 at 12 39 15 PM" src="https://user-images.githubusercontent.com/5283677/168745411-db7f12f6-fdab-4253-86c1-da4c083a5a03.png">

<img width="815" alt="Screenshot 2022-05-17 at 12 37 58 PM" src="https://user-images.githubusercontent.com/5283677/168745216-ad02cb39-172e-4430-a6d6-4a0f6e69f217.png">

<img width="750" alt="Screenshot 2022-05-17 at 12 39 33 PM" src="https://user-images.githubusercontent.com/5283677/168745471-5fcaf906-9e93-4d31-8bf8-106d49bcabed.png">

I got curious and installed a fresh 1.17.4 client on my macbook Pro...and I got the same issue.
The mouse cursor is somewhere near the location of Knalga on the Main Menu's map screen but Multiplayer is highlighted/selected

<img width="1440" alt="Screenshot 2022-05-17 at 12 21 50 PM" src="https://user-images.githubusercontent.com/5283677/168745702-03391768-70b8-4a29-bd38-704179ac39c1.png">

Lastly, it's not just the main menu...it appears the entire Wesnoth app is affected by this.
I tried altering the display options and settings in SysPrefs but nothing restored it.

Wesnoth 1.16.2 client seems unaffected and is working as usual.

This is causing frustration and confusion from the MacOS player-base (including me), and if it's affecting _every_ Mac user, I think this is quite serious.

Note: my brother has a MacPro and he has the same issue with 1.17.4. So, 3 cases and counting...

(Is this High Priority? The app is almost unplayable on MacOS right now due to this)

**Comment by Pentarctagon** [comment]
Does this happen even if the scaling is set to 1x?

**Comment by Pentarctagon** [comment]
That'd make sense.

@CelticMinstrel does this also happen for you?

**Comment by Pentarctagon** [comment]
I wonder if this might be at all related to the Apple-specific adjustment that was added to get_dpi() previously?
https://github.com/wesnoth/wesnoth/blob/f7859ad104bd9658d57cda16630282c1839c84a1/src/video.cpp#L512-L534

Not that it's related to that specific method, but maybe something similar is needed.

**Comment by CelticMinstrel** [comment]
I do get this issue in the release in fullscreen mode. I was able to turn off automatic scaling in preferences, and then it worked… then it stopped working again when I disabled fullscreen. Eventually I managed to change the manual pixel scaling value. None of 2, 3, or 4 worked, but when I put it back on 1, it started working again. But then when I relaunched it didn't work anymore.

I'm not really sure what to make of this.

**Comment by mesilliac** [comment]
Can you post the output of running Wesnoth with the `--log-info=display` commandline argument? It's possible one of the assumptions about how highDPI support works on mac was incorrect.

**Comment by knyghtmare** [comment]
```
/Applications/Wesnoth.app/Contents/MacOS/The\ Battle\ for\ Wesnoth --log-info=display
Battle for Wesnoth v1.17.4 x86_64
Started on Thu May 19 08:04:41 2022

Automatically found a possible data directory at /Applications/Wesnoth.app/Contents/Resources

Data directory:               /Applications/Wesnoth.app/Contents/Resources
User configuration directory: /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.17
User data directory:          /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.17
Cache directory:              /Users/USER/Library/Containers/org.wesnoth.Wesnoth/Data/Library/Application Support/Wesnoth_1.17/cache

Setting mode to 1280x800
20220519 08:04:41 info display: pixel scale: 1
20220519 08:04:41 info display: overriding logical size
20220519 08:04:41 info display:   old lsize: 0,0
20220519 08:04:41 info display:   old wsize: 1280,800
20220519 08:04:41 info display:   old osize: 2560,1600
20220519 08:04:41 info display:   new lsize: 2560,1600
20220519 08:04:41 info display:   new wsize: 1280,800
20220519 08:04:41 info display:   new osize: 2560,1600
20220519 08:04:41 info display: creating 32bpp drawing surface with format SDL_PIXELFORMAT_ARGB8888
20220519 08:04:41 info display: creating drawing texture
Checking lua scripts... ok
```

**Comment by CelticMinstrel** [comment]
I think it must also be significant that it can be fixed by manually setting the scale factor (although only a factor of 1 works), but reverts to broken on next launch.

**Comment by knyghtmare** [comment]
> reverts to broken on next launch.

I dont think players would appreciate having to spend ~10-20 minutes of their limited game time fixing the client every time they opened it.

**Comment by mesilliac** [comment]
Well, it turns out on MacOS that can happen. The linked PR should fix it.

There was a reported crash when testing it, but that seems to be an unrelated issue of theme support at very high DPI.

**Comment by irydacea** [comment]
So is this why the game from Steam's beta branch is completely unusable on macOS at the moment? It would be nice if that were fixed for those who just want to check out the changes in 1.17.4 without having to wait a whole other month.
