### ISSUE TITLE
Movement range of units is not properly shown after the turn of the side owner ends 

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#6716]
### Game and System Information

- **Version: 1.16.2**
- **Downloaded from: Steam**
- **OS: Windows**

### Description of the bug

After the side owner ends the turn, instead of showing the movement range that unit would have next turn, what is shown is still the current movement range. In additional content, I showcase the issue, I mouse over the unit, then press 2, then release and then I can see movement range of the unit. In addition to that 1 no longer works probably because of this issue. 

### Steps to reproduce the behavior

1. Create 4 player game in local multiplayer.
2. Use all of the movement on one of the leaders.
3. Check thier movement range from alied side perspective.
Or
1. Create 4 player game on multiplayer server.
2. Play and end the turn.
3. Check movement ranges of units from perspective of side owner.
Or
1. Observe any 4 player game and check units of a side that just ended the turn. 

### Expected behavior

After the owner ends the turn, all movement ranges of units are instantly refreshed and show where units can move next turn. 

### Additional context

https://youtu.be/MO54GIzembY 

Usually I would upload directly but for some reason it didn't let me do that.

**Comment by mattsc** [comment]
Confirmed.  It's caused by af0968d9c.  @stevecotton
