### ISSUE TITLE
THoT S04 Unused code

### ISSUE THREAD

**Issue by Descacharrado** [wesnoth/wesnoth#6725]
I stumbled upon this piece of code while looking for victory events.

https://github.com/wesnoth/wesnoth/blob/7d2ee4ef72fb17b714290dbf576fc854a02a1382/data/campaigns/The_Hammer_of_Thursagan/scenarios/04_High_Pass.cfg#L297-L299

This is just a reminder for me (or whoever) to delete it as it does nothing. Its there in 1.16 too.

**Comment by knyghtmare** [comment]
> I stumbled upon this piece of code while looking for victory events.
> 
> https://github.com/wesnoth/wesnoth/blob/7d2ee4ef72fb17b714290dbf576fc854a02a1382/data/campaigns/The_Hammer_of_Thursagan/scenarios/04_High_Pass.cfg#L297-L299
> 
> This is just a reminder for me (or whoever) to delete it as it does nothing. Its there in 1.16 too.

that event code looks amusing...why is it even there?

**Comment by Descacharrado** [comment]
I would guess the event did something at some point but the code inside it was moved to other part... who knows.

**Comment by soliton-** [comment]
You can click on the link pick "View git blame" from the dot menu and see what commit it was added in.

**Comment by Descacharrado** [comment]
It happened on the rename 4d58ab8cf. Not that it matters much when, but it's good to know that tools exists, thanks!

**Comment by soliton-** [comment]
Well, you can see it was added without anything in the event. So it never did anything. Presumably just an artefact from developing the WML that slipped in since it produces no error.
