### ISSUE TITLE
Can't Interact with Units or use Hotkeys

### ISSUE THREAD

**Issue by Uleesees** [wesnoth/wesnoth#6759]
### Game and System Information

- **Version:** 1.16.3
- **Downloaded from:** Steam
- **Build info:** N/A
- **OS:** Windows 10

### Description of the bug

Can not interact with anything* on the map. Menus can be interacted with as normal but any attempt to click on units results in nothing. Hotkeys also do nothing. The only exception to this is, after selecting "next unit" from the menu, I can move a unit once, but only to its maximum move distance.

### Steps to reproduce the behavior

Occurs in every loaded mission. 

### Expected behavior

Watching videos of the game leads me to believe you should be able to interact with me map.

### Additional context

N/A

**Comment by Pentarctagon** [comment]
Can you provide the relevant information listed at https://forums.wesnoth.org/viewtopic.php?t=25660 ?

**Comment by Uleesees** [comment]
Steps to reproduce the behavior:

1) Load any mission.
2) Can't interact with anything other than the menus once opening dialogue ends.

Log:

Battle for Wesnoth v1.16.3 x86_64
Started on Wed Jun 08 19:50:08 2022

Automatically found a possible data directory at E:\Steam\steamapps\common\wesnoth

Data directory:               E:\Steam\steamapps\common\wesnoth
User configuration directory: C:\Users\USER\Documents\My Games\Wesnoth1.16
User data directory:          C:\Users\USER\Documents\My Games\Wesnoth1.16
Cache directory:              C:\Users\USER\Documents\My Games\Wesnoth1.16\cache

Setting mode to 1536x864
Checking lua scripts... ok

**Comment by Pentarctagon** [comment]
The build information too, please.

**Comment by Uleesees** [comment]
The Battle for Wesnoth version 1.16.3 x86_64
Running on Microsoft Windows 10 21H1 (10.0.19043) x86_64
Distribution channel: Steam

Game paths
==========

Data dir:        E:\Steam\steamapps\common\wesnoth
User config dir: C:\Users\USER\Documents\My Games\Wesnoth1.16
User data dir:   C:\Users\USER\Documents\My Games\Wesnoth1.16
Saves dir:       C:\Users\USER\Documents\My Games\Wesnoth1.16\saves
Add-ons dir:     C:\Users\USER\Documents\My Games\Wesnoth1.16\data\add-ons
Cache dir:       C:\Users\USER\Documents\My Games\Wesnoth1.16\cache

Libraries
=========

Boost:             1.78
Lua:               5.4.2
OpenSSL/libcrypto: 1.1.1n (runtime 1.1.1n)
Cairo:             1.17.6 (runtime 1.17.6)
Pango:             1.50.5 (runtime 1.50.5)
SDL:               2.0.20 (runtime 2.0.20)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.4 (runtime 2.0.4)

Features
========

Lua console completion:       yes
Win32 notifications back end: yes

Current video settings
======================

SDL video drivers:       [windows] dummy
Window size:             1536x864
Screen refresh rate:     60
Screen dots per inch:    96.000000x96.000000
Screen dpi scale factor: 1.000000x1.000000

Current audio settings
======================

SDL audio drivers:  [wasapi] directsound
Number of channels: 2
Output rate:        44100 Hz
Sample format:      signed 16 bit little-endian
Sample size:        4096 bytes

Installed add-ons
=================

No add-ons installed.

**Comment by soliton-** [comment]
Do other SDL apps work?

**Comment by knyghtmare** [comment]
![image](https://user-images.githubusercontent.com/5283677/173017083-42497cff-5d99-4dd3-8a3a-b767cf944830.png)
![image](https://user-images.githubusercontent.com/5283677/173017137-23cc05ff-bb26-49aa-8b66-544419efd63b.png)
![image](https://user-images.githubusercontent.com/5283677/173017185-41830f22-cf01-4109-ad48-4b24fa3aeedb.png)

Summary: 
This is a bug which occurs when Wesnoth client is launched from Steam.

**Comment by Hejnewar** [comment]
![mehhh](https://user-images.githubusercontent.com/41817546/173029628-0379cc47-c69d-43cd-b2a8-6516220110f1.JPG)

There is only one problem, it might not be. I'm honestly quite a bit annoyed by this.

**Comment by Uleesees** [comment]
I hate to be the bearer of bad news, but it still doesn't work after loading from the exe or the taskbar.

**Comment by Pentarctagon** [comment]
A [second person](https://steamcommunity.com/app/599390/eventcomments/3390660679622205663/#c3422186614294084192) has now also reported that basically just spamming the keyboard gets it working eventually.

**Comment by Uleesees** [comment]
I'm not sure what kind of spooky wizard shit this is, but it's worked for me. Put my hands over all of the main keys and pressed down. Now it works even after reloading the game and even through Steam. I have to imagine it's actually a key combo being hit.

**Comment by Pentarctagon** [comment]
Well, uh... if it happens again to you again, or for anyone else reading this at some point, try pressing the keys more slowly and see if you can find which key/key combo is responsible for fixing the issue.

**Comment by Uleesees** [comment]
I pressed each key in sequence, including the function keys, numpad, as well as every standard key with no effect. It has to be a combo.

**Comment by mesilliac** [comment]
Someone finally tracked down that this is the Scroll Lock key. Posting a fix now.
