### ISSUE TITLE
An option to organise addons regarding their start_year before downloading

### ISSUE THREAD

**Issue by hermestrismi** [wesnoth/wesnoth#6761]
### Describe the desired feature

It's not an urged thing but it will be funny if it become added: an option to organise addons regarding their start_year before downloading, why not?

**Comment by knyghtmare** [comment]
I dont think this is even feasible since not all addons are based in Wesnoth...or Irdya. Also, eras dont even use that parameter.

you can actually add dates within the `tags=` in PBL file. So, that pretty much covers the feature

**Comment by hermestrismi** [comment]
> I dont think this is even feasible since not all addons are based in Wesnoth...or Irdya. Also, eras dont even use that parameter.
> 
> you can actually add dates within the `tags=` in PBL file. So, that pretty much covers the feature
yes, I know. what I mean is the possibility to organise the addons just like 'date' or 'last update' before downloding and not just after (or at least showing those information on the details just languages and dependency )

**Comment by knyghtmare** [comment]
> what I mean is the possibility to organise the addons just like 'date' or 'last update' before downloding and not just after (or at least showing those information on the details just languages and dependency 

<img width="293" alt="Screenshot 2022-06-12 at 3 20 44 PM" src="https://user-images.githubusercontent.com/5283677/173226536-f5e325e7-7466-4008-8fef-41b1c5298a10.png">

Is this what you're looking for? It's in the "Order" drop down (last 4 options)

**Comment by soliton-** [comment]
Addons can contain 0, 1 or more campaigns. So finding a start_year for every addon is not possible. Please consider discussing ideas in the forum before filing a feature request here.
