### ISSUE TITLE
[Descent into Darkness] Update Walkthrough

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6767]
Just leaving a reminder here for me to update the walkthrough of the reworked DiD as it's outdated by like 2 years. I will probably add this as a fresh new wiki page since the current walkthrough is still relevant for 1.14.x

**Comment by cooljeanius** [comment]
link to the wiki page: https://wiki.wesnoth.org/DescentIntoDarkness

**Comment by cooljeanius** [comment]
Mal Shubertal has kinda been doing this lately: https://wiki.wesnoth.org/index.php?title=DescentIntoDarkness&type=revision&diff=70376&oldid=70036 
OK to close as fixed now?
