### ISSUE TITLE
Mainline replay OOSs

### ISSUE THREAD

**Issue by Descacharrado** [wesnoth/wesnoth#6832]
I have tested through every victory event in mainline SP as I said [here](https://github.com/wesnoth/wesnoth/pull/6438#issuecomment-1134328142).

~~Seems like most victory event OOSs are related to a unit being spawned, moved or stored/unstored* although #4667 has a very simple scenario that has an OOS with a [set_variable] tag.~~

This Issue is meant to track scenarios with OOSs in mainline in order to revert my (or whomever's) wml workarounds ~~when #4667 is solved.~~

Having #4667 solved, we may revert the PRs after retesting the following scenarios

### Singleplayer

- [x] TSG S04 #6859 
- [x] UtBS S01
- [x] UtBS S08 #6676 
- [x] DM S08
- [x] DM S14
- [x] EI S10
- [x] NR S01 #6438
- WoF Untested

**Comment by prrajput1199** [comment]
@Descacharrado can I work on this issue??

**Comment by Descacharrado** [comment]
Sure, go ahead!

**Comment by dharmik209** [comment]
Can I work on this issue!?

**Comment by gfgtdf** [comment]
What do you want to do? This issue is marked as fixed

**Comment by dharmik209** [comment]
Thank you for replying.
