### ISSUE TITLE
Gcc compilation fail for test when using codeblock projectfiles

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#6834]
### Game and System Information

- **Version:master
- **Downloaded from:here
- **Build info:[**]compiled with gcc-8.1.0  --threads=posix --exceptions=seh --arch=x86_64 after commit (https://github.com/wesnoth/wesnoth/commit/8ed261053ddbc34ae2760deaeca98b2c00133883)
- **OS:**windows 7

### Description of the bug

the compilation of src/test/main.cpp fail.

### Steps to reproduce the behavior

load codeblocks
2load codeblock workspace in projectfiles/codeblocks folder
3. compile src/tests/main.cpp file.

### Expected behavior

file compiled normally.

### Additional context

[log.txt](https://github.com/wesnoth/wesnoth/files/9034875/log.txt)

**Comment by CelticMinstrel** [comment]
This is probably not unique to CodeBlocks. I suspect it would happen in older Boost versions on any Windows computer.

**Comment by newfrenchy83** [comment]
> This is probably not unique to CodeBlocks. I suspect it would happen in older Boost versions on any Windows computer.

boost 1.78 is already too old?

**Comment by CelticMinstrel** [comment]
> boost 1.78 is already too old?

I really have no idea… I just vaguely recall this kind of issue arising in the past with Boost.Filesystem.
