### ISSUE TITLE
game crash when user clicks on license in encyclopedia

### ISSUE THREAD

**Issue by uneconomicalfairy14** [wesnoth/wesnoth#6845]
### Game and System Information

- **Version:**
- **Downloaded from:**
- **Build info:**
- **OS:**
1.16.3
portableapps
windows

### Description of the bug

the game crashes when user clicks on license tab in encyclopedia

**Comment by Pentarctagon** [comment]
What is 16.13.1? Also does this happen when downloaded from SourceForge?

**Comment by CelticMinstrel** [comment]
I would suspect this to be the same crash as the credits.

**Comment by uneconomicalfairy14** [comment]
> What is 16.13.1? Also does this happen when downloaded from SourceForge?

sorry for the mistake

**Comment by Pentarctagon** [comment]
Whatever exists on portableapps wasn't put there by the Wesnoth team. For Windows we make Wesnoth available on SourceForge, itch.io, and Steam. So unless this can be confirmed as happening when downloaded from one of those three places, this isn't our issue to solve - you'd need to contact whoever uploaded Wesnoth to portableapps.

**Comment by uneconomicalfairy14** [comment]
umm...ok i ll close this issue. still just check once if this is happening on other copies too

**Comment by mesilliac** [comment]
I did check this on the master branch recently and it's not crashing for me. It does however take several seconds to render that massive chunk of text. It should definitely be improved, along with credits.

**Comment by Wedge009** [comment]
I just checked 1.16.3 build from Steam for both Windows and Linux. Neither crashed but they both took a long time to render. Windows far longer than Linux, but that may just be because the Windows machine I tested on is a lot less powerful than the Linux machine.

**Comment by mesilliac** [comment]
> We can re-work this issue into an enhancement task to improve the rendering time for the licence.

I think that's a good idea. I suspect breaking the text up into smaller sections will solve both issues. And it also needs to be done with the credits screen, as that's definitely still crashing in new_rendering for likely the same reason.

**Comment by stevecotton** [comment]
The help browser still GUI1, porting it to something more recent is feature request #2687.

It does already break the text into chunks, and in this case the code doing the chunking looks like it's at least O(n^2), a.k.a. it slows down on big inputs. `help_text_area::add_text_item` splits the text into separate parts, each part being a line or smaller. It repeatedly calls `split_in_width`, which asks `pango_word_wrap` to word-wrap the entire remaining portion of the text, but then to return only the first line.

**Comment by Wedge009** [comment]
Reconfirming the issue for both 1.16.10 and 1.17.19+dev. On my relatively fast machine, it takes ~5 seconds to respond. Separate report suggests it can take over a minute (machine details not given).

**Comment by Wedge009** [comment]
With GUI2 Help introduced in 1.19, the licence page no longer renders at all because the resulting texture is too large:

`error SDL: When creating texture from surface: Texture dimensions are limited to 16384x16384`

**Comment by babaissarkar** [comment]
> With GUI2 Help introduced in 1.19, the licence page no longer renders at all because the resulting texture is too large:
> 
> `error SDL: When creating texture from surface: Texture dimensions are limited to 16384x16384`

<img width="1356" height="805" alt="Image" src="https://github.com/user-attachments/assets/fc7e03a5-0fda-4492-8a1a-ce3c10067cb8" />

I never faced this particular texture limitation, but did receive reports on it from Iris on Discord a few times.

**Comment by Wedge009** [comment]
Retesting at e151c4af2d4, I can replicate with pixel scale x2, but not x1. At x2 the Help window is there, but the Licence page is entirely blank.
