### ISSUE TITLE
Unit created in Ms^Xm terrain

### ISSUE THREAD

**Issue by l-alcom** [wesnoth/wesnoth#6847]
### Game and System Information

- **Version: 1.17.5**
- **Downloaded from: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.17.5/Wesnoth_1.17.5.dmg/download**
- **Build info: 18G9323**
- **OS:**

### Description of the bug

In WoF S09 Ancestor, a unit (Gryphon in hex 9.2 in my case) is created in the middle of a Ms^Xm terrain. This makes finishing the scenario impossible as it cannot move outside the terrain and it cannot be attacked.

### Steps to reproduce the behavior

As the distribution of enemy/monster units is unpredictable, one must probably enter the scenario several times until the bug appears. 

### Expected behavior

All enemy/monster units should be created on accessible terrain, or at least, on terrain which they can leave.

**Comment by soliton-** [comment]
@Jonathan-Kelly probably wants to look at this.

**Comment by knyghtmare** [comment]
Seems to need a follow up to #6537

**Comment by Jonathan-Kelly** [comment]
Oops, I probably should have foreseen this one. We can go ahead and assign the issue to me.

Thanks for reporting @l-alcom

**Comment by Jonathan-Kelly** [comment]
A fix is now [committed](https://github.com/wesnoth/wesnoth/commit/6a2d638c4f9be2b23aed4670471c782bf0334ccd) so this can be closed.

**Comment by knyghtmare** [comment]
https://github.com/wesnoth/wesnoth/issues/6847#issuecomment-1222568233 Okay
