### ISSUE TITLE
map diff tool fails on certain terrain and images are swapped

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#6862]
The map diff tool fails on maps with `_off^_usr` terrain as visible in this run:
https://github.com/wesnoth/wesnoth/runs/7301694657?check_suite_focus=true

It would be good if there would be an error message if it doesn't find an image for a terrain.

Currently the parser fails to remove comments from attribute values and the terrain.cfg entry in this case looks like `string=_off^_usr    # wmllint: ignore`. Since there are plenty moe entries with those wmllint comments it fails on all those terrains as well.

Easy test cases are lots of the mainline multiplayer maps like: `data/multiplayer/maps/2p_Aethermaw.map`

For maps where it works the images are swapped. I would expect the old map on the left and the new map on the right but it displays the other way around.
Example with the top left tile changed to a mountain: https://github.com/soliton-/wesnoth/pull/5

**Comment by soliton-** [comment]
@macabeus ^

**Comment by cooljeanius** [comment]
Another example of terrain where it fails: `^Xo`, as seen in #6057. I tried taking a look at it, but don't really grok the source yet, as I don't speak Typescript: https://github.com/cooljeanius/wesnoth/tree/egallager_wesnoth_map_diff_tinkering

**Comment by soliton-** [comment]
I think everything reported here is actually fixed.

For Xo there actually is no image. It's not a parsing issue. For that I would suggest to just use a fallback image as wesnoth does in debug mode IIRC.
