### ISSUE TITLE
[Editor] [1.17.5+dev] Editor Unable to show/load pre-saved maps

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6868]
### Game and System Information

- **Version:** Battle for Wesnoth v1.17.5+dev (e1f15234a40-Modified) x86_64
- **Downloaded from:** Github
- **Build info:** Msys2
- **OS:** Windows 10

### Description of the bug

Editor unable to load existing maps since files disappeared completely or are not shown anymore.

### Steps to reproduce the behavior

Open the map editor and load a map

### Expected behavior

I can load my pre-saved maps

### Additional context

See screenshot in next comment. Also, fix the template. Attachments dont work here anymore.

**Comment by knyghtmare** [comment]
![image](https://user-images.githubusercontent.com/5283677/178852863-d3726c5f-13f9-4128-80bf-a5259aaf556d.png)

**Comment by mesilliac** [comment]
Oh that's weird. Seems it works for navigating around until you actually go into one of the folders. I'll look into it

**Comment by mesilliac** [comment]
Should be fixed by 29204418db7ea3ea81710992d41789ef101444ac

**Comment by knyghtmare** [comment]
i finally got my optical fibre broadband cable repaired and was able to check this. Yes, seems fixed now.
