### ISSUE TITLE
In-Game Help text flickers

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6869]
### Game and System Information

- **Version:** 1.17.5+dev (e1f15234a40)
- **Downloaded from:** self-compiled
- **Build info:** SCons and MSVC/CMake
- **OS:** Linux/X11 and Windows

### Description of the bug

While in-game - not at the title screen - parts of the text in the Help dialogue will flicker. I found it was much more noticeable in Linux but I confirm it's there in Windows too.

### Steps to reproduce the behavior

1. Load/start a game.
2. Bring up the Help dialogue - I find it simplest to just hover over a unit and bring up its description (default hot-key: `d`)

### Expected behavior

Text shouldn't be flickering - it looks like it's being rendered several times a second but in a way which is definitely noticeable and off-putting.

### Additional context

It's not easy to see in a static image but here's an example:
![flicker](https://user-images.githubusercontent.com/13679322/178852989-1daff433-bd2b-45e1-9f70-fc654c5cf78b.png)

The 'non-bold' portion of the text in the red box flickered rapidly between 'bold' and 'non-bold' rendering. The 'non-bold' portion of the text in the purple box remained as-is.

**Comment by mesilliac** [comment]
I'm not sure why this could be happening, but it does look like a fix for #6870 should fix this as well.

**Comment by Wedge009** [comment]
Resolved together with #6870, thanks.
