### ISSUE TITLE
Poor text rendering for in-game Help

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6870]
### Game and System Information

- **Version:** 1.17.5+dev (e1f15234a40)
- **Downloaded from:** self-compiled
- **Build info:** SCons and MSVC/CMake
- **OS:** Linux/X11 and Windows

### Description of the bug

Seems related to #6869. The text is rendered quite badly for Help, but only while in-game, not from the title screen. It happens in both Linux and Windows. Possibly #6855 doesn't work well with GUI1 elements? (I recall Help being the last major piece still yet to migrate to GUI2 framework - #3653)

![1 17 5+dev](https://user-images.githubusercontent.com/13679322/178854308-60cc7668-65a2-4c64-b00c-900277232545.png)

### Steps to reproduce the behavior

1. Load/start a game.
2. Bring up the Help dialogue - I find it simplest to just hover over a unit and bring up its description (default hot-key: `d`)

### Expected behavior

Text rendered as in current 1.16.5 release.

![1 16 5](https://user-images.githubusercontent.com/13679322/178854349-e71562a0-9980-4acd-8d8b-0cb3447b7667.png)

### Additional context

Actually, now that I compare the images side-by-side, it's not just the text that's rendered badly - the 'sparkles' behind the sylph also look over-saturated.

**Comment by mesilliac** [comment]
I can't reproduce either of these text bugs on Linux/X11/Nvidia. The screen also appears to be flipping correctly and the text drawing only once when it should. I might have to add some detailed debugging output to find what's going wrong in this case.

**Comment by mesilliac** [comment]
Ahh i managed to reproduce it - it only happens if the map is animating. Shouldn't be too difficult to fix.

**Comment by mesilliac** [comment]
Both issues should be fixed by 5c3d959ae01f34090ff18ffea3775aaf98507f81

**Comment by Wedge009** [comment]
Yes, much better now - thank you!
