### ISSUE TITLE
Terrain defence label in side-bar is missing

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#6872]
### Game and System Information

- **Version:** 1.17.5+dev (bd05566de0e)
- **Downloaded from:** self-compiled
- **Build info:** SCons and MSVC/CMake
- **OS:** Linux/X11 and Windows

### Description of the bug

This report is not concerned with the short-comings of the side-bar design, just pointing out a minor regression with the defence label. It displays in current 1.16.5 release but not in 1.17.5+dev. Apparently it was still displayed in 1.17.3+dev as seen in the first image in #6663.

Fortunately the terrain defence value itself is still displayed.

### Steps to reproduce the behavior

Just load/start/join a game and observe the side-bar with a unit selected.

### Expected behavior

Defence label should be displayed next to movement points.

### Additional context

I tried tinkering with the WML but have little understanding of how it all works. For reference:

https://github.com/wesnoth/wesnoth/blob/29204418db7ea3ea81710992d41789ef101444ac/data/themes/default.cfg#L179-L186

https://wiki.wesnoth.org/ThemeWML

**Comment by Descacharrado** [comment]
If I change its position, the def label reappears, but only for anything larger than 1366x705
![image](https://user-images.githubusercontent.com/30196839/179020486-d026476d-6d0a-42cc-9ba3-28eb106f6bf4.png)
![def](https://user-images.githubusercontent.com/30196839/179019930-7d57cd2d-7ba3-4903-9168-0250de9c3535.png)

I'm not saying that changing its position is a good fix, I'm just nothing weird behaviour.

**Comment by mesilliac** [comment]
The current definition is completely broken, and should never have worked...

It says:
 * put the left edge of the def label 1 pixel to the right of the right edge of the MP label -- what?
 * put the top edge of the def label the same place as the top edge of the MP label -- okay sure
 * put the right edge of the def label the same place as the right edge of the MP label -- WTF?
 * put the bottom edge of the def label 14 pixels from the top edge of the def label -- okay fine

That point 3 is giving it a negative size which is causing it not to display.

I had to print out the final position using some debug code to figure out what was wrong.

**Comment by Wedge009** [comment]
Yes, fixed, thanks. No wonder I had no success with my own tinkering, if it was so broken to begin with - I was under the assumption that whatever was already there was basically right.

Also well done for fixing the reduced resolution configuration too.
