### ISSUE TITLE
Error out if data dir is not found automatically

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#6883]
### Describe the desired feature

Currently you get an assert that's not very clear about what the issue is: https://github.com/wesnoth/wesnoth/blob/bc94f37f767960f053ff5f77cc5cf3b5100042a1/src/filesystem.cpp#L1497

Better would be to error out if no data dir was found automatically and no `--data-dir` option was given.

**Comment by Wedge009** [comment]
Yeah, ran into that when starting to use CMake builds in MSVC, because by default the executables are not placed at the root of the source, where it can easily find the data directory.

**Comment by Wedge009** [comment]
Is the assertion necessary? I replaced it with an error log message and then saw that the log already records a message:
https://github.com/wesnoth/wesnoth/blob/157c8d066a61c89240c41c50014bb7b3f84bd900/src/wesnoth.cpp#L628-L630

On the one hand, the assertion error on its own isn't helpful, but on the other hand without the assertion it could be hard to know that the application has even started, let alone failed.

**Comment by SyedSaifuddin045** [comment]
Is this issue Open I would like to work on it?
If yes,I am a beginner,some guidance would be appreciated.

**Comment by Pentarctagon** [comment]
Yes, this issue is still open. It sounds like some clarification is needed on what the new behavior should be though.

**Comment by CelticMinstrel** [comment]
I think the relevant files for this would be wesnoth.cpp and _maybe_ commandline_options.cpp. See the log message linked by @Wedge009.

**Comment by soliton-** [comment]
The code that tries to find the data dir is above this line:

https://github.com/wesnoth/wesnoth/blob/bf5befcd5e8cb97fbbd35bbf598358b8a8816b47/src/wesnoth.cpp#L1177

The idea is that if the dir is _not_ automatically found and `--data-dir` is _not_ given then the game can give up (exit non-zero as celmin said) at this point. Continuing without a data dir just means it continues to run into errors until one is fatal which currently happens to be the mentioned assert. And doing that does not make the actual issue any clearer.

**Comment by tofilwiktor** [comment]
is this issue still open?

**Comment by soliton-** [comment]
Yes.
