### ISSUE TITLE
Undo command not working

### ISSUE THREAD

**Issue by mesilliac** [wesnoth/wesnoth#6898]
### Game and System Information

- **Version:** 1.17.6, master @ 720094361d446c9f05495906117dd2c773ce746f
- **Downloaded from:** git
- **OS:** Linux

### Description of the bug

The undo command no longer works. The "u" button has no apparent effect, and there's no "undo" option in the right click menu.

### Steps to reproduce the behavior

1. Start the tutorial
2. Move to the wrong place
3. Press "u"

### Expected behavior

The move undoes. I assume there should be a menu item in the right click popup menu as well, as that's what the tutorial message on the screen is saying.

### Additional context

I bisected this and it was introduced in the commit 7e234f8833282424b3535b9c334c751748f7222b

**Comment by Wedge009** [comment]
I confirm the symptom of undo not working as well as 7e234f8 appearing to be where the problem first appears in master. Whether it makes sense or not, when I compile current master (6ev2246eff) with 7e234f8 reverted 'undo' works again.

Note that with the recent merging of #3157, `z` is now the default hot-key for 'undo'.

**Comment by CelticMinstrel** [comment]
Come to think of it, we could just revert 7e234f8 for the next version until this gets a proper fix, couldn't we? It would mean there are deprecation warnings in master, but I don't think that's a _major_ issue.

**Comment by sevu** [comment]
Breaks the tutorial, when you can't undo but also aren't allowed to end the turn.

**Comment by sevu** [comment]
Every scenario includes this event … it is from diversion.lua, it does not need to be in every scenario.
![event](https://user-images.githubusercontent.com/21158813/194712111-28653c07-e06f-49a7-98d6-35487c0a1bb2.png)

**Comment by CelticMinstrel** [comment]
Yes, the issue is that non-WML events added through the new events API always disable undo with no way to opt out. The long-term fix is to add a way to do that; a short-term fix would be to either not use the new API for diversion.lua and feeding.lua (using the old `on_event` instead) _or_ to only register those events if an associated unit actually exists on the map.

**Comment by knyghtmare** [comment]
I am tempted to label this as high priority but I labelled it as medium for now. This is causing a really bad case of UX and playability. This is very inconvenient to players, umc authors and devs

**Comment by stevecotton** [comment]
I'd agree with labeling it high priority, as it's making people less likely to test the dev branch (see current discussion in Discord's `#general` channel).

@CelticMinstrel do you have an ETA for a proper fix, please?

**Comment by stevecotton** [comment]
> Come to think of it, we could just revert [7e234f8](https://github.com/wesnoth/wesnoth/commit/7e234f8833282424b3535b9c334c751748f7222b) for the next version until this gets a proper fix, couldn't we? It would mean there are deprecation warnings in master, but I don't think that's a _major_ issue.

Our unit tests treat unexpected warnings as build failures. I think that's correct - it's showing that we can't deprecate `on_event` until we have a complete replacement.
