### ISSUE TITLE
create a auto-update feature

### ISSUE THREAD

**Issue by uneconomicalfairy14** [wesnoth/wesnoth#6900]
### Describe the desired feature

it would be better if we could get a in-game check for updates feature

**Comment by Wedge009** [comment]
I thought this was a duplicate, but maybe I was thinking of the version check request for add-ons. At any rate, I think this is made redundant by the auto-update features in Steam, itch.io, and Flatpak distributions and would have similar issues in terms of 'stable' vs 'development' releases. I'd consider this low priority. And even if the game could internally find a newer release of itself, I do not see a straightforward way for it to update itself considering the myriad of configurations, platforms, permissions, etc, to be negotiated.

**Comment by max-torch** [comment]
If not fully auto-updating, could something in-between be feasible?

A message in-game saying "A new version is available". And then it provides a link to the place you got the game from: (steam, itch, flatpak, etc) to see if you can update it.

In LibreOffice when a new version is available it shows this message and a link, when you visit the link it shows you a download button for the new version so you can install it.

**Comment by uneconomicalfairy14** [comment]
Also could there be patches instead of replacing the entire game

this was what i had in mind when i opened this issue. A small update patch that would update the game to the next version

**Comment by Pentarctagon** [comment]
We're not building our own custom auto-update mechanism - the solution is to use the already existing Steam, itch.io, or Flatpak versions.

**Comment by grz0** [comment]
Similar feature request #1470

**Comment by Wedge009** [comment]
Thank you! I was sure I had seen this request before.
