### ISSUE TITLE
`FADE_TO_BLACK` macro should probably use the new `screen_fade` system

### ISSUE THREAD

**Issue by mesilliac** [wesnoth/wesnoth#6907]
I added a smooth screen fading tag in #6864 which should be used for screen fades over the previous method of animating the `color_adjust` tag. However i haven't yet converted the macros `FADE_TO_BLACK` etc that are usually used do screen fading.

There is a small question of whether to override the existing macro to use the new system, or whether to make a new macro for the new system and keep the old macro for the old behaviour (animating `color_adjust`).

There is a visible difference, in that the old behaviour did not fade units and halos, only terrain.

The new behaviour fades everything, and so better fits the name, but if there's any scenario relying on being able to see units after doing the fade, it will break.

I'm somewhat in favour of overriding the behaviour, as it more accurately does what it says on the tin (fades to black). Some sort of `FADE_TO_BLACK_LEGACY` or `FADE_TERRAIN_TO_BLACK` could replace the old macro. But i don't know how to notify anyone possibly relying on that functionality that it has changed.

**Comment by CelticMinstrel** [comment]
I'm a bit unsure about this too. First, I'm not sure whether or not it's okay to just change the behaviour of the macro. It's a relatively minor behaviour change, so it _might_ be okay, I'm just not really sure. Second, I'm not quite sure what's the best way to notify people of the change. The deprecation system is the obvious choice, but that would require deprecating the old macro (with no behaviour change presumably, since it's deprecated) and probably adding two replacement macros for the two variations in behaviour, which seems a bit less than ideal…

**Comment by mesilliac** [comment]
There's also a possible future distinction between fading just the game map portion of the screen and fading the UI as well. I had planned to add an option to the `screen_fade` tag but it was nontrivial.

Perhaps adding new explicit macros and deprecating the old one is the best choice. The old macro could later be repurposed to whichever is most useful, after it passes whatever length of time is appropriate for the deprecation.

**Comment by CelticMinstrel** [comment]
That's true – there's nothing preventing us from re-using a deprecated macro for some other (related) purpose instead of removing it outright.

**Comment by soliton-** [comment]
If there is a simple tag now I'd say there is no need for a macro at all. Leave FADE_TO_BLACK as it is. Deprecate it if the new tag can do that same. No need for a macro if all it hides is `[screen_fade] duration=100 [/screen_fade]` or whatever.

**Comment by mesilliac** [comment]
Yeah, and changing the `color_adjust` value is very very bad for performance. Every terrain image needs to be regenerated (and sliced up into sixths, and blended with the colour, and uploaded to the GPU) every frame of the change.

The macro name makes it seem like the preferred method of fading, which it definitely now is not. I suppose this is the biggest reason i want to change or deprecate the macro.

The `screen_fade` tag can't reproduce the behaviour of colouring only terrain and leaving units visible, and it was mentioned in #6745 that this can be desirable. So some method of keeping the old behaviour is still needed. But it should also be clear to a scenario designer somehow that using the old way is not recommended unless they need that specific effect. Both because of the performance concern, and because the new effect is more true to the name.

**Comment by mesilliac** [comment]
So after converting a few things to use `screen_fade` i found that the `FADE_TO_BLACK` macro is important in that you don't have to specify time. The duration is standard across scenarios and campaigns.

I tried some variations of naming for a simple properly-fade-out macro, but `FADE_OUT` was the only other one that felt reasonable... and `FADE_IN` already exists as the opposite of `FADE_TO_BLACK`

I did also find that convenience macros for `screen_fade` were useful, at least in changing the `FLASH_*` macro definitions. I used `{FADE r g b time}` and `{UNFADE time}`. So `FADE_OUT` and `UNFADE` would work. But then it really is not ideal that `FADE_IN` would not be the opposite of `FADE_OUT`.

**Comment by mesilliac** [comment]
The more i look at this the more it annoys me that the existing macro took both "fade to black" and "fade in". Either one or the other would be fine as i could use the non-taken one for the more proper fade.

**Comment by mesilliac** [comment]
Well, after converting everything in mainline that was using `FADE_TO_BLACK` i settled on: `SCREEN_FADE r g b t`, `SCREEN_UNFADE t`, `SCREEN_FADE_OUT` and `SCREEN_FADE_IN`. This makes it obvious they're fairly thin convenience wrappers around the `screen_fade` tag.

**Comment by mesilliac** [comment]
#6913 for the proposed replacement
