### ISSUE TITLE
Feature request: "Watery chasm" terrain

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#6919]
### Describe the desired feature

Right now there are 2 tiers of lava: lava chasms (`Ql`) and regular lava (`Qlf`). It would be nice if this distinction existed for water tiles, too, so campaign authors can have rivers running along the bottoms of gorges... maybe go with `Qw` for the terrain code?

**Comment by doofus-01** [comment]
I think this is addressed in d77a16f4153ed9441af93cfb8e5f50b9343a6470 and can be closed.  Do you agree, @cooljeanius ?

**Comment by cooljeanius** [comment]
um, hm... well, it wasn't quite what I was looking for originally, but yeah I can probably get that to work, so, ok, I'll close this...
