### ISSUE TITLE
Feature request: APFs (Audio Path Functions), to mimic IPFs for music/sounds

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#6932]
### Describe the desired feature

Another thing I remembered from an earlier Discord discussion with @CelticMinstrel: so, basically, Wesnoth has these Image Path Functions (IPFs) that are very nice for being able to modify images when an image is needed. It would be nice if similar functionality were available for audio files, too, in case a scenario designer needs to modify some audio for whatever reason. I'm thinking just some real basic stuff like "start at certain time" / "stop at certain time" or "volume up/down" would really just be all I'd want at first (for songs with long intros where I want to skip straight to the good part for an event or something), although they could eventually be extended to support fancier things, too.

**Comment by Pentarctagon** [comment]
There's already [volume] btw.

**Comment by cooljeanius** [comment]
> There's already [volume] btw.

Yeah but sometimes I might want to apply it just to a single sound, rather than globally

**Comment by CelticMinstrel** [comment]
Volume is far from the only potential use-case for this. Pitch-shifting, enveloping, attenuation, cutting, splicing, mixing, cross-fading, even fully procedural sounds… you could potentially do a _lot_ of things with APFs.

**Comment by cooljeanius** [comment]
oh wait never mind this is a duplicate of #1717
