### ISSUE TITLE
Boost unit tests are structurally broken

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#6937]
The current setup of the boost unit tests have a ton of cross-test pollution - changing a test or removing a test source file can cause entirely different tests to give different results, start or stop printing error logs, etc.

**Comment by Pentarctagon** [comment]
Just off the top of my head, a perhaps "less broken" way to do this would be to have a separate executable per test source file, so at least that way there would be no way for tests to pollute the execution of other tests.

**Comment by CelticMinstrel** [comment]
It should be possible to avoid cross-test pollution even in the current setup… the test fixture is essentially a class or something, right? So any common setup and teardown should be done there. Unfortunately that does mean an audit of every test would be necessary…

**Comment by Pentarctagon** [comment]
The problem is I don't think it'd even be possible to do such an audit with confidence, as well as making sure all the tests remain fully separate.

Just as an example though, there were four checks that were causing only the GCC+LTO build to fail on the new Ubuntu 22.04 based docker image in `test_gui2.cpp`. I disabled those, and now there's something getting thrown (which apparently **also** doesn't extend std::exception) in every single test in `test_mp_connect.cpp`, but only for the clang+debug build - the GCC+LTO build is fine.

I'm sure there's a reason, and it's probably Wesnoth's code's fault, but IMO it just doesn't seem like a good use of anyone's time to try and audit this mess vs refactoring it to make every test its own executable which automatically guarantees there's no cross-test pollution.

**Comment by CelticMinstrel** [comment]
Having a hundred different test executables also seems like a terrible idea though. Using the current executable and running one test at a time isn't quite so bad, but even that doesn't seem great.

**Comment by Pentarctagon** [comment]
If there's a way to tell the boost unit tests executable to only execute a single test or set of tests per execution, that would accomplish the same thing without needing separate executables I suppose.

**Comment by CelticMinstrel** [comment]
It's possible. I think you can figure out how with the test runner's own inline documentation (run it with `--help` or something like that) and/or with the official Boost documentation.

**Comment by CelticMinstrel** [comment]
I'm not sure why my comment isn't showing in the thread, but there's a typo in the command-line documentation.
