### ISSUE TITLE
Bots and How to Handle Them

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#6939]
### Describe the desired feature

In their current form bots are not at all problematic but as time goes on many more bots are planned to be added for longer events and it is my opinion that it does not create the best picture, having a lot of the lobby occupied with games that rarely start (for most of the day there is simply not enough players to fill them) might discourage others from playing and makes wesnoth seem like even more of a dead game, as well as possibly creating confusion among new players as some of them are planned to be accessible only after fulfilling certain conditions. 

In the past I know that there was an idea to create a separate tab in the multiplayer lobby for bots, and if that is possible I would support this idea. Another idea idea is to have a filter that filters out bots, but maybe there is a better idea. Also I don't know if these ideas are even possible to be done so that is also something to talk about.

**Comment by Pentarctagon** [comment]
@Vultraz in particular, since this is very much a UI question.

**Comment by Pentarctagon** [comment]
The first thought that comes to mind for this would be to have bots listed separately on the right side of the lobby separate from actual players, and then have a separate tab in the main lobby UI for bot host games vs human hosted games. Though the second part of that may be fairly difficult given how complex the MP lobby code already is.

**Comment by soliton-** [comment]
None of this is possible unless bots mark themselves as such. Currently there is no way to decide what a bot is.

**Comment by Pentarctagon** [comment]
Right, there would need to be some way to indicate to the server whether something is a bot. Could be a username prefix, an additional attribute sent when logging in, an additional database table that lists out which usernames are for bots, etc.

**Comment by Discontinuum** [comment]
Maybe mark individual games? Like there are flags for Private Replays, there was a flag for "registered only". So a hidden but documented in API flag for bot games?

**Comment by soliton-** [comment]
Unless you somehow want to host bot and non-bot games from the same client that doesn't make much sense to me. I think it's better to mark the client as a bot so it can also appear differently in the player list and then the server can mark each game created by that client as a bot game automatically.

**Comment by stevecotton** [comment]
> _ @Discontinuum in https://github.com/wesnoth/wesnoth/issues/7002#issuecomment-1240700145_ :
> * When the game started, with living people playing, it doesn't make sense to hide it after that. Abundance of open empty bot games may be not-good looking, but games with living people should be shown independently of how they started. The filter should hide only not yet started games

A bot-hosted game that's still waiting to start, but which has just had a player join, should probably be shown - all it would need is another player to join and it would be ready to go.

Instead of separating games hosted by bots, how about separating games based on how long it's expected to be before the next human interaction? In practise, that might be implemented as how long it's been since the last human interaction, with bots being able to set a flag saying "create this game with that timer already expired", or even have an account flag that messages from that account don't reset the timer.

**Comment by Pentarctagon** [comment]
What would be the benefit of this approach?

**Comment by CelticMinstrel** [comment]
> My proposal would be names like "General Lobby"/"Special events" (bots were made basically for events, so)

If this is the purpose of the feature, it doesn't really make sense for it to be a boolean flag…

**Comment by Pentarctagon** [comment]
Some of these events seem to be pretty long lasting though - [Afterlife](https://forums.wesnoth.org/viewtopic.php?t=55186) seems to be going for almost a year now for example.

**Comment by Discontinuum** [comment]
Afterlife started in August 2021 if we consider 1.14 version, so a bit more than a year. There were also a couple of temporary events, but Afterlife proved to be enough popular to be run on a nearly-permanent basis.

**Comment by Pentarctagon** [comment]
Right, so it's not really an event, it's a constant thing.
