### ISSUE TITLE
Cursor doesn't work correctly on Wayland

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#6949]
### Game and System Information

The Battle for Wesnoth version 1.17.6+dev (54fedb4d6a8-Clean) x86_64
Running on Fedora Linux 36 (Workstation Edition) x86_64
DE: KDE 5.25

### Description of the bug

The mouse cursor does not work correctly when wesnoth is running as native Wayland application, check screenshot:

![image](https://user-images.githubusercontent.com/3605541/183293475-e961cf1a-fcfc-4739-ad1b-9f85c50b95ec.png)

### Steps to reproduce the behavior

1. Run wesnoth
2. Change resolution to the lowest
3. Maximize window
4. Try to click a GUI element

**Comment by mesilliac** [comment]
I tried running under Wayland again and i can't reproduce this - although i did manage to trigger some strange behaviour and breakage after changing to random resolutions, maximizing, minimizing, and doing various things.

Is this a full-desktop window like you get when you click "fullscreen", or just a maximized window? What i mean is, are there any bars or docks reducing the screen area, or is it taking up the whole display?

I did sometimes manage to get it into a state where the wrong resolution was being used by the game, and the remainder of the space was black. However even in this case it was mapping the cursor correctly.

For reference i'm running SDL version 2.0.20. There were many Wayland-related changes in SDL recently, but as far as i'm aware it's still not considered stable on Wayland even in the latest version.

Graphics hardware may also be an important factor. Nvidia at least still don't fully support Wayland.

**Comment by grz0** [comment]
> Is this a full-desktop window like you get when you click "fullscreen", or just a maximized window?
Maximized desktop window, but I can reproduce the same issue when I switch from maximized window to fullscreen.

**Comment by Wedge009** [comment]
It's not clear to me what the image is supposed to be illustrating. Is it the case that a click at the position where the mouse cursor is registers as a click on the General tab?

**Comment by grz0** [comment]
> Is it the case that a click at the position where the mouse cursor is registers as a click on the General tab?
Yes

**Comment by Wedge009** [comment]
I suppose you don't get the mis-alignment on X11? At a glance this looks similar to what I reported in https://github.com/wesnoth/wesnoth/issues/5518#issuecomment-1183747885 except I don't use Wayland.

**Comment by grz0** [comment]
> I suppose you don't get the mis-alignment on X11?

No, it works fine on X11, on Wayland it broken.

**Comment by grz0** [comment]
I'm closing this bug. I retested on 314f6f7c78d and I cannot reproduce this issue. I think this could be caused by some KDE/Wayland.
