### ISSUE TITLE
Wesnoth loses custom cursor icon when running natively on wayland

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#6951]
### Game and System Information

The Battle for Wesnoth version 1.17.6+dev (54fedb4d6a8-Clean) x86_64
Running on Fedora Linux 36 (Workstation Edition) x86_64
Distribution channel: Default
DE: KDE 5.25

### Description of the bug

Wesnoth looses the custom mouse cursor icon while running as native wayland application.
The icon is restored when you click on some in-game GUI element.

### Steps to reproduce the behavior

1. Start wesnoth, it will start with the system's default cursor icon
2. Click some in-game GUI element, the cursor will switch to the wesnoth's custom cursor
3. Move the mouse outside the game window, then move back inside. The cursor will be set to the default system icon.

**Comment by mesilliac** [comment]
To add to this i also noticed problems with the cursor disappearing completely when running in fullscreen under Wayland. I couldn't find any solution to it, nor any reason for it.

I don't have the problem with the cursor disappearing after moving out and into the window. It's quite possible these are SDL bugs, or bugs in some other system out of our control.

**Comment by grz0** [comment]
`To add to this i also noticed problems with the cursor disappearing completely when running in fullscreen under Wayland.`

In my case, starting the game in fullscreen is the only scenario in which I have no issues with cursor.

**Comment by grz0** [comment]
The issue seems to be fixed. I'm not sure if this was KDE/SDL2/wesnoth bug.
Tested on:
- wesnoth b8adf0cd5e7
- SDL2-2.26.5
- KDE Plasma 5.27.9
