### ISSUE TITLE
Release 1.16.5

### ISSUE THREAD

**Issue by ryandesign** [wesnoth/wesnoth#6957]
### Game and System Information

- **Version:** 1.16.5
- **Downloaded from:** SourceForge
- **Build info:** N/A
- **OS:** N/A

### Description of the bug

Files for Wesnoth 1.16.5 were uploaded to SourceForge on 2022-07-15 and a Git tag was created but there is no GitHub release for this version; please create one.

**Comment by Pentarctagon** [comment]
This was intentional, since there was only a single change and the source code tarballs github generates are incomplete, so a release here serves no purpose.

**Comment by ryandesign** [comment]
The purpose would be to document what that change was, and to inform people of the availability of the release. As it stands, the front page of this GitHub repo states the latest version is 1.16.4 which is inaccurate.

**Comment by Pentarctagon** [comment]
To be honest I forget why I even started creating releases on github - they don't really serve any purpose for Wesnoth.
