### ISSUE TITLE
[wmllint] Quenoth elf units as well as new nagas are not known unit types in wmllint

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#6962]
### Game and System Information

The Battle for Wesnoth version 1.17.6+dev (4de78f406c6-Clean) x86_64
Running on Ubuntu 22.04.1 LTS x86_64
Distribution channel: Default

Game paths
==========

Data dir:        /home/USER/Documents/GitHub/wesnoth
User config dir: /home/USER/.config/wesnoth
User data dir:   /home/USER/.local/share/wesnoth/1.17
Saves dir:       /home/USER/.local/share/wesnoth/1.17/saves
Add-ons dir:     /home/USER/.local/share/wesnoth/1.17/data/add-ons
Cache dir:       /home/USER/.cache/wesnoth

Libraries
=========

Boost:             1.74
Lua:               5.4.4
OpenSSL/libcrypto: 3.0.0b-dev (runtime 3.0.0b-dev)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.50.6 (runtime 1.50.6)
SDL:               2.0.20 (runtime 2.0.20)
SDL_image:         2.0.5 (runtime 2.0.5)
SDL_mixer:         2.0.4 (runtime 2.0.4)

Features
========

Lua console completion:       yes
D-Bus notifications back end: yes

Current video settings
======================

SDL video drivers:        [x11] wayland KMSDRM dummy
Window size:              1920x1080
Game canvas size:         1920x1080
Final render target size: 1920x1080
Screen refresh rate:      75

Current audio settings
======================

SDL audio drivers:  [pulseaudio] alsa sndio pipewire
Number of channels: 2
Output rate:        44100 Hz
Sample format:      signed 16 bit little-endian
Sample size:        1024 bytes

Installed add-ons
=================

No add-ons installed.

### Description of the bug

As the title says: "Quenoth elf units as well as new nagas are not known unit types in wmllint"

### Steps to reproduce the behavior

Run wmllint on Under the Burning Suns files

### Expected behavior

No warning saying that these units are not known.

### Additional context

![Screenshot from 2022-08-14 05-33-16](https://user-images.githubusercontent.com/41433185/184511546-df4f4ff6-829e-4eba-aa19-13c00cf90d1f.png)

**Comment by soliton-** [comment]
How are you calling wmllint?

**Comment by max-torch** [comment]
> How are you calling wmllint?

`/usr/bin/python3 /home/alexander/Documents/GitHub/wesnoth/data/tools/wmllint --dryrun /home/alexander/Documents/GitHub/wesnoth/data/core /home/alexander/Documents/GitHub/wesnoth/data/campaigns/Under_the_Burning_Suns/scenarios`

**Comment by knyghtmare** [comment]
Try the same command mentioned in #4381 ?

**Comment by max-torch** [comment]
> Try the same command mentioned in #4381 ?

This is the command you are referring to?
> One way to run wmllint is:
`wmllint --nospellcheck data/core data/campaign/foo`

I ran it also except using absolute paths instead of relative:
`/usr/bin/python3 /home/alexander/Documents/GitHub/wesnoth/data/tools/wmllint --nospellcheck /home/alexander/Documents/GitHub/wesnoth/data/core /home/alexander/Documents/GitHub/wesnoth/data/campaigns/Under_the_Burning_Suns/scenarios`

As you can see im running wmllint with the 
- no spell check option
- core folder directory
- UtBS campaign scenarios directory

Still the same result.

**Comment by soliton-** [comment]
If you just give wmllint scenarios it won't find units. Those are under the units dir.

**Comment by max-torch** [comment]
> If you just give wmllint scenarios it won't find units. Those are under the units dir.

Thank you. This was the issue. It was a lack of understanding on my part of how wmllint works. closing this issue now.
