### ISSUE TITLE
Can't compile wesnoth

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#6964]
### Game and System Information

- **Version:**master after https://github.com/wesnoth/wesnoth/commit/3915ee812c27d88dee304a321e5dfa6ea33377f6
- **Downloaded from:**here
- **Build info:**gcc12.1.0 and pango and cairo librarie from wesnoth1.15 dependancie on sourceforge
- **OS:**windows10

### Description of the bug

when i compile wesnoth on gcc i have'wesnoth-master\src\font\text.cpp|100|error: 'pango_layout_set_line_spacing' was not declared in this scope; did you mean 'pango_layout_set_spacing'?|' message.

### Steps to reproduce the behavior

Compile game in using wesnoth1.15 dependance from sourceforge( not librarie for 1.17).

**Comment by Pentarctagon** [comment]
As of 3915ee812c27d88dee304a321e5dfa6ea33377f6 you need a pango version of at least 1.44.
