### ISSUE TITLE
Addon version check database issue

### ISSUE THREAD

**Issue by Bigsky22** [wesnoth/wesnoth#6970]
### Game and System Information

- **Version:**1.16.5
- **Downloaded from:** Steam
- **Build info:**
- **OS:** Win 10

### Description of the bug

Error
Something is Wrong with the addon version check database supporting the multiplayer lobby. Please report this at bugs.wesnoth.net

### Steps to reproduce the behavior

Trying to observe a ladder-era game

**Comment by Wedge009** [comment]
Seems to be a repeat of #4055. That one has more discussion.
