### ISSUE TITLE
1.17 Default hotkey "i" interference

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#6972]
### Game and System Information

- **Version:**
v1.17.6+dev (672ee6feec5)
- **Downloaded from:**
github
- **Build info:**
scons
- **OS:**
linux

### Description of the bug

In the editor, "i" used to toggle the terrain codes, and it still indicates this in the drop-down menu.  But now it opens the help dialog.  I did not assign any hotkeys, so this is a default behavior.

### Steps to reproduce the behavior

open map editor, hit "i" key.  Help dialog opens to describe Gg terrain

### Expected behavior

"Gg" labels pop on/off each hex.  This still happens if you use the menu instead of the "i" key

**Comment by knyghtmare** [comment]
Is this related to https://github.com/wesnoth/wesnoth/pull/3157?
Seems like it.

**Comment by Pentarctagon** [comment]
https://github.com/wesnoth/wesnoth/pull/3157/files#diff-f59ce21614fc0621f895ee9e1ccb6c96fe0db6cea68c90b44f4a6bbbea9c14e3R129-R132 I assume.
