### ISSUE TITLE
Pin comments in "this game" chat

### ISSUE THREAD

**Issue by xSkyEndx** [wesnoth/wesnoth#6974]
### description:
When you host a game it can sometime take a while till someone joins. You might go aft in the meanwhile, but want to let the player know, who joins your game, **that you're aft** for 10 min or something. Also it can be used to **share game informations** that you can't or don't want to put in the title. (explain what ladder is or what maps you have in your picker etc.)

### feature:
To pin comments in "this game" chat (that's the chat when you hosted a game and wait for the start)

**Comment by CelticMinstrel** [comment]
So basically, "pin" here means the comment is visible to players who weren't there when it was originally sent, right?

I think the second use-case (custom game information) is better served by a game description set in the game creation screen, but "pinned" comments also seem useful.

**Comment by xSkyEndx** [comment]
Yeah that what I mean. And your right that also can be an option.

**Comment by Kingofd** [comment]
I'll see to it

**Comment by stevecotton** [comment]
Instead of pinning, an alternative would be to for newly-joined clients to see all the chat that had happened before they joined. I'm wondering if that would do everything that pinning would, and be simpler than adding the pinning.

**Comment by soliton-** [comment]
Chat message replay has now been implemented.
