### ISSUE TITLE
1.17.7+dev Hotkey "s" not showing Statistics UI anymore.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#6982]
### Game and System Information

- **Version:** Battle for Wesnoth v1.17.7+dev (72a1c801c07-Modified) x86_64
- **Downloaded from:** Github
- **Build info:** Battle for Wesnoth v1.17.7+dev (72a1c801c07-Modified) x86_64
- **OS:** Windows 10 Msys2

### Description of the bug

On 1.16 and prior, the keyboard key "s" instantly showed the scenario/campaign "Statistics" UI and now it's mapped Status Table instead? Just why?

### Steps to reproduce the behavior

1. Load any campaign
2. Press "s"

### Expected behavior

Statistics is shown. and not the Status table

### Additional context

If you're going to suddenly change the entire assignment of ALL hotkeys, please dont....it's very confusing now...everything seems weird now

**Comment by soliton-** [comment]
It was done in https://github.com/wesnoth/wesnoth/pull/3157.

I agree that changes like the statistics and status table switch is pretty arbitrary and will just annoy players. Any default hotkey changes should have very strong reasoning and should at a minimum be mentioned in the changelog.

**Comment by knyghtmare** [comment]
#3157 has caused 2 issues so far. I am in favour in reverting it.
My wesnoth play experience is hampered greatly since my mental keymapping has been distorted by such a chaotic change.
