### ISSUE TITLE
"lua submodule does not exist" when cmake-configure'ing in the source tree

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#6986]
### Game and System Information

- **Version:** 1.17.7
- **Downloaded from:** github
- **Build info:** N/A
- **OS:** Devuan GNU/Linux Daedalus

Using 3.24.0-rc4 .

### Description of the bug

I'm trying to build Wesnoth after having download the tarball for 1.17.7 . When running `cmake` in the source dir, and if I don't specify a build directory, I am told:
```
CMake Error at CMakeLists.txt:33 (message):
  Lua submodule does not exist.  You must run 'git submodule update --init
  --recursive' to initialize it.
```
I did not use git to build, nor to download, so I can't be told to use git on what is not a repository...

If I use a separate build directory, this doesn't happen.

### Steps to reproduce the behavior

Try cmake-configure'ing within the source 

### Expected behavior

Either in-source build should work, or I should get a message saying "specify a different build directory".

**Comment by CelticMinstrel** [comment]
I wonder, is it possible to have cmake and scons automatically run the correct `git submodule` command if the files don't exist?

**Comment by eyalroz** [comment]
> run the correct git submodule command if the files don't exist?

I don't see how that would be possible without a git repository to begin with. You could theoretically clone from a remote source.

**Comment by Pentarctagon** [comment]
The github generated tarball doesn't include submodules, and we have no way of tell it to either include submodules or just not generate a tarball.

**Comment by soliton-** [comment]
Seems to me downloaded from github can only mean the github autogenerated tarball because we're not providing any tarball there. Bizarre that a separate build directory should change anything.

Can you provide the tarball that reproduces this?

**Comment by eyalroz** [comment]
@soliton- : It's the 1.17.7 release tarball... https://github.com/wesnoth/wesnoth/archive/refs/tags/1.17.7.tar.gz

**Comment by Pentarctagon** [comment]
I'm tempted to just delete all the existing "releases" on github and stop adding new ones. The only reason I started doing them was because it was what some release tracking tool used, but this isn't the first time the github-generated tarball has confused someone.

**Comment by CelticMinstrel** [comment]
Okay, so basically this is a GitHub bug, right?

**Comment by eyalroz** [comment]
@CelticMinstrel : Doesn't seem likely, because the tarball was not actually missing anything. If any of you guys can reproduce this - perhaps it can also be reproduced with tarballs from elsewhere?

**Comment by soliton-** [comment]
No idea how you think that tarball is not missing anything. `src/modules` has only empty subdirs. Also when trying to reproduce the issue with that tarball I get the exact same error with a separate build dir or not. No clue how it worked for you.

The actual release tarball is the one on sourceforge linked from the front page or http://files.wesnoth.org/wesnoth-1.17.7.tar.bz2

As Pentarctagon already mentioned there is no way for us to either fix the github generated tarball or disable it. If github allows us to disable their autogenerated tarball we can certainly do that. Until then there is nothing to do here.

**Comment by eyalroz** [comment]
@soliton- 

>  No clue how it worked for you.

Actually, it didn't quite. Things broke down later.

>  Until then there is nothing to do here

How about adding a note to the GitHub release page saying "Don't download the tarballs from here"?
