### ISSUE TITLE
Malin talks about people he doesn't know about / don't exist

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7005]
### Game and System Information

- **Version:** 1.17.4
- **Downloaded from:** wesnoth.org
- **Build info:** N/A
- **OS:** N/A

### Description of the bug

In DiD scenario "All alone", Malin still says, when leaving:

"The Terrain is hazardous in these mountains. Neither the paladins nor Dela will be able to pursue me."

even if Dela hasn't arrived and Cadeus' forces are gone

### Steps to reproduce the behavior

In "All alone", get the book and kill all of Cadeus' troops, bringing it to your camp by, say, turn 13.

### Expected behavior

Malin should not mention Dela at this point, and even mention of any Tath forces should refer to the possibility that _other_ parties might be searching for him.

**Comment by Wedge009** [comment]
Scenario 8: Alone at Last
