### ISSUE TITLE
[modify_unit_type] check if the advancement is already possible for the [unit_type]

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#7009]
### Describe the desired feature

`[modify_unit_type]add_advancement=` adds the advancement to the list.
If it was already in the list, it's added twice.
This happens for example when both a [modification] and an [era] include the macro to unlock an advancement.
It causes problems with the mod in mainline.

![double](https://user-images.githubusercontent.com/21158813/190189994-8242a342-aee6-4ec9-8d97-d538fca7c83f.png)

**Comment by the-nostromo-1** [comment]
Hi, is this issue still available to be worked on?

**Comment by gfgtdf** [comment]
I'd think so, at least I'm not aware of this being fixed.

**Comment by the-nostromo-1** [comment]
Awesome, thank you for the reply. I'm new to contributing to projects, do you have any advice where/what file to start with for this issue?

**Comment by gfgtdf** [comment]
This depends on your Preknowledge, if i were to to it it just do a text search for `modify_unit_type` or `add_advancement` in the .cpp files and then trying to understand these programmcodes and how they can be changed

**Comment by CelticMinstrel** [comment]
Before you get started on the issue I recommend building Wesnoth from source, if you haven't already.

My recommendation for finding where in the code this is handled would be to search the project (using your IDE of choice, or grep) for the string `"modify_unit_type"` (including the quotes), which will immediately show you where it's read from the config. From there you should be able to figure out where to go next.

**Comment by the-nostromo-1** [comment]
Ok, sounds good! Thank you guys for the advice, I really appreciate it!

**Comment by gfgtdf** [comment]
Fixed in #7743
