### ISSUE TITLE
Revert planning mode key associations

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7011]
### Game and System Information

- **Version:** 17.7
- **Downloaded from:** GitHub
- **Build info:** N/A
- **OS:** N/A

### Description of the bug

The keys associated by default with planning mode have changed to Alt+P to activate and backspace to undo a plan action. I find this less convenient than the earlier arrangement - I want one-key planning!

I realize the key bindings can be changed, but:

1. That argument goes both ways.
2. There's no single-button to bring back all planning mode keys, and the action names are not obvious, so it's tedious to change.

### Additional context

>By failing to prepare, you are preparing to fail.
>
> *― Benjamin Franklin*

**Comment by soliton-** [comment]
This was already done. See #6982.

**Comment by eyalroz** [comment]
> probably find the old key to be even more inconvenient

What's the basis for that assumption?

**Comment by CelticMinstrel** [comment]
I remember seeing complaints from people who were confused because they accidentally enabled planning mode and didn't know how to get out of it and thought the game was broken. It's less bad than it was, I believe (I think there's a big notification when you enable it), but I don't think the problem has gone away entirely.

**Comment by eyalroz** [comment]
@CelticMinstrel : Let me push back on that some...

* How does the current situation allay those complaints? One can still enable planning mode and theoretically be confused about it. It seems the way to address that confusion - if it needs addressing - is making it clearer that you're in planning mode and/or how to exit it.
* Statistics. Both my complaint and the other complaints you mentioned are anecdotal. Which of the "problems" are statistically significant?
* The confusion problem is supposedly already addressed by the large text indicating that you are in planning mode. Naturally, no solution is perfect, but what you're describing is a case of "I ignored what the program was clearly and explicitly telling me, and then X happened".

**Comment by CelticMinstrel** [comment]
> * How does the current situation allay those complaints? One can still enable planning mode and theoretically be confused about it. It seems the way to address that confusion - if it needs addressing - is making it clearer that you're in planning mode and/or how to exit it.

> * The confusion problem is supposedly already addressed by the large text indicating that you are in planning mode. Naturally, no solution is perfect, but what you're describing is a case of "I ignored what the program was clearly and explicitly telling me, and then X happened".

Your second point essentially answers your first point. I'm just not sure if the large text is the _best_ solution to the original issue, or if the problem can still occur despite the large text. In particular, was there a time limit set on the text? If there's a time limit, it could open the possibility of someone pressing it by accident while switching away from the game and missing the text entirely.

Even if it _does_ solve the problem 90% or 99% or whatever, I think adding a modifier key by default for something as drastic as enabling a completely separate command mode is still a better user experience. Sure, there are likely people who are used to just pressing P… but anyone is free to customize their keybindings however they please, so a single person's opinion on the best key combination to enable planning mode is essentially irrelevant.

As for statistics, I am unsure if we have statistics on this. I vaguely remember a forum poll related to planning mode but don't remember how relevant it was to this question. We would probably need to do some sort of survey.
