### ISSUE TITLE
AI behaviour is bad / any changes planned?

### ISSUE THREAD

**Issue by FrostBlade5** [wesnoth/wesnoth#7019]
### Describe the desired feature

Once again i have to comment on AI behaviour...
The Wesnoth AI is sort of agressive and in general it is a decent enemy, however there are some scenarios where the AI is honestly speaking, just dumb.
Yesterday i played a scenario, i had about 10 elven-horse-riders and i moved all of them to the edge of the map, then i went straight up to the enemys king and killed it, what's dumb about this? Well the enemy had more than enough units to prevent me from taking the king out but instead of blocking my units on the edge of the map, the AI only attacked like 2-3 of them and the rest passed through and reached the king. A real player would never allow this to happen.

Generally speaking the AI seems to lack a tactic/technique/strategy.

I complained about the AI of "Kings" before, when i started the match yesterday there was multiple AI enemys and one of them managed to get it's king killed right at the beginning of the game. A real player would protect his king at all costs and not send it to death. I can already smell to upcomming comments, get over it, blabla... Honestly it's just annoying that the AI sends their king to die and protect's it badly. Personally i would have programmed the AI to set a priority on protecting the king as soon as an enemy unit is in attack range to it. All in all, even tho this might never happen i will say it anyways because it has to be said, the king should have it's own AI and not use the same AI as all other units, the king should have a priority to stay alive as long as possible and not leave the castle to get killed straight away, period.

I would also like to ask, is it possible to collect anonymous statistic data from wesnoth games to improve AI?
Or, is it possible to let the wesnoth AI fight against it self over and over again to become smarter and smarter untill eventually it will outsmart the average player? Or atleast add difficultys such as easy / medium / hard for the AI to be selected at the start of the game? If you are familiar with alpha zero and alpha go, the AI that beat a human who once was world champion, basically that's what im asking if such a "self learning AI" would be possible for wesnoth aswell?
The current AI is not bad but it could be much better, and by better i mean more challenging which would make the game all in all more fun.

**Comment by max-torch** [comment]
> if such a "self learning AI" would be possible for wesnoth aswell

I doubt that this is impossible. However, if possible, i think it would be a lot of work. Right now, when we talk about AI we are talking about machine learning - algorithms that are developed from training a computer. The computer is given a lot of data to train on.

So the first ingredient is the training data. There are several obstacles to this:
- The maps change and unit stats change in different versions. This is also part of the reason why OpenAI five is not continuing to maintain their Dota 2 AI - they have to keep retraining it to account for the patch changes that keep releasing. In fact, they even had to do some "rough surgery" on it several times to make it still work properly without completely retraining it to make it keep working properly for a while longer.
- Another thing that the version changes introduce is changes to the structures of wesnoth game data. So you have all of these data, but you need multiple variations of the data parsing and data cleaning algorithms deal with all of the different changes to the data structure introduced.

After data is cleaned and parsed, you then have to decide the "architecture" of the training regimen. So is it gonna be one layer only? Is it gonna be a weighted ensemble? Is it going to be over/undersampled to reduce the bias during training? Are you going to use simple Machine Learning only or are you going to use Deep Learning?

You actually have to run different training regimens, like stated above, quantify the performance of each, and compare them. First, by just doing evaluation using training and validation data sets.

Then, you have to also compare performance on real-world data, unseen by the AI during training.

It's a lot of work, it's practically an academic thesis or something. There's a lot that I'm simplifying and not even mentioning. I'm  sure there's more I'm not even aware of, but at least I have this much to share.

**Comment by Wedge009** [comment]
A repeat of #6156, perhaps?

Max gives some good points, particularly around machine learning. AI is used a lot as a buzzword in recent years but it really is almost always in the context of machine learning from large data sets and I don't think that translates well to the Wesnoth engine.

> Personally i would have programmed the AI to set a priority on protecting the king as soon as an enemy unit is in attack range to it.

You are welcome to make your own contributions if you find something better! I'm pretty sure the current algorithms already consider things like protecting the leader, but obviously doesn't always get it right, as you often point out.

> ...the king should have it's [sic] own AI and not use the same AI as all other units, the king should have a priority to stay alive as long as possible and not leave the castle to get killed straight away...

I believe there is a parameter that can be set to discourage the leader from leaving the keep.

I admit I don't know too much about the AI rules within Wesnoth but I think there are different rule-sets available - not sure if it's easy to activate the 'experimental' AI to see if there's any significant difference in behaviour in the problem scenarios described.

**Comment by cooljeanius** [comment]
> A repeat of #6156, perhaps?

repeating my reply from there:

please look at the wiki pages about AI: 

- https://wiki.wesnoth.org/WhyWritingAWesnothAIIsHard 
- https://wiki.wesnoth.org/Creating_Custom_AIs
- https://wiki.wesnoth.org/Category:AI

**Comment by CelticMinstrel** [comment]
Although I wouldn't consider this issue to be a "real" issue in the game since the AI is highly customizable in ways that solve pretty much all the listed complaints, I _will_ note that there may be merit in adding additional built-in AI configurations that can be selected from the Create Game screen, beyond "default" and "experimental".

**Comment by FrostBlade5** [comment]
Thanks for the replys everyone, the response from max was very interesting. I am not into programming so my knownledge is limited.. I see that with new versions these updates might be a problem for AI learning. And deep learning is interesting but also complicated.. The records of all multiplayer games might be of use at some point.
I can imagine this is much work,

This: "I believe there is a parameter that can be set to discourage the leader from leaving the keep." sounds a little cheap as a solution but still better than the king going rogue and being killed, sadly i don't think the dev's will make that change but i honestly beleve it would be the best option as of now.

**Comment by Wedge009** [comment]
It's not quite what I was thinking of, but it appears a number of scenarios use the technique of restricting leaders' movement to prevent them from potentially committing suicide by charging into battle recklessly:
https://github.com/wesnoth/wesnoth/blob/d4ca8d3e4146f339969c3aab8e02aa886ee4d549/data/campaigns/Descent_Into_Darkness/scenarios/08_Alone_at_Last.cfg#L410-L432

https://github.com/wesnoth/wesnoth/blob/d4ca8d3e4146f339969c3aab8e02aa886ee4d549/data/campaigns/Son_Of_The_Black_Eye/scenarios/12_Giving_Some_Back.cfg#L178-L209

It seems to be a work-around for the limitations of the AI. Perhaps this could be done better so that it's not required everywhere, but it appears to work well enough for the campaigns.

As an aside, I think your interaction with everyone will be much improved if you stop thinking in terms like 'the devs' and using words like 'cheap' and 'sadly'. Wesnoth is a community project, everyone who plays is potentially a contributor. There is always room for improvement, sure, and constructive feedback is welcome but don't expect things to change especially when frequently making remarks with such a negative tone.

**Comment by eyalroz** [comment]
Shouldn't this issue be split into several ones? The general complaint/question, and the two points regarding kamikaze leaders and cavalier attitude towards attacks on leaders?

**Comment by cooljeanius** [comment]
> Shouldn't this issue be split into several ones? The general complaint/question, and the two points regarding kamikaze leaders and cavalier attitude towards attacks on leaders?

well I think at the very least a task list could be edited into the OP, to make this a multi-task issue...
