### ISSUE TITLE
Removal of the deprecated `[weapon ability]backstab=` attribute

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7032]
AbilitiesWML's common key `backstab` is deprecated, to be replaced with `[filter_opponent][filter_adjacent]`, with the core `WEAPON_SPECIAL_BACKSTAB` macro updated during 1.13.x's development cycle (see 12c96a94d24d9a353df82f342a695e6e6d5f8409).

Discussion has mainly been in the PR #6791. I'm creating an issue because it's turned out to be a non-trivial change, and it'll be annoying to search for the issue later and not find it because the discussion was in a PR.

I merged @newfrenchy83 's #7024 (changing it from `PREEMPTIVE` to `FOR_REMOVAL`), because I incorrectly thought it was a trivial change and that discussion had already finished. That was my error, not an error of the PR author.

The C++ code currently has special handling for the `backstab` attribute, which is unnecessary when using the WFL filter; PR #7031 shows how much simplification is possible by removing the old C++ code. Old UMC could be supported by a wrapper, as suggested in https://github.com/wesnoth/wesnoth/pull/6791#issuecomment-1175360252 .

**Comment by stevecotton** [comment]
Can we agree that filters don't change during combat? Examples of the rules that I'm proposing:
* Results can change, so an attack with a filter checking if the opponent is already poisoned might have the result change after the first hit, and that would still be allowed.
* The `[event]name=attack` happens before combat, so would still be able to change filters on abilities. (This currently works, see #7033).
* An `[event]name=attack_hits` wouldn't be allowed to add or remove filters; and we can have implementation-defined behavior if it tries (with no changes during a stable series, so no OOS).

When we do find the place to put [a wrapper](https://github.com/wesnoth/wesnoth/pull/6791#issuecomment-1175360252), I'm thinking that:
* An ability with `backstab=yes` and no filters gets converted to have a WFL filter instead.
* An ability with both `backstab=yes` and also with WML-supplied WFL-filters triggers a deprecation warning, and the implementation can ignore the `backstab=yes`.
* The replacement likely happens at most once per combat.
* It's okay for the replacement to be permanent; using `[store_unit]` afterwards could return WML with the WFL filter instead of `backstab=yes`.

**Comment by Pentarctagon** [comment]
I think I agree, though I'm not sure I follow how the first three points are related to the topic? To clarify though:
> An ability with both backstab=yes and also with WML-supplied WFL-filters triggers a deprecation warning, and the implementation can ignore the backstab=yes.

This would would occur only if there was another [filter_opponent] with a formula= attribute, correct? Otherwise the [filter_opponent] should be able to be added to a different existing filter, or the formula= attribute can be added to an already existing [filter_opponent]?
