### ISSUE TITLE
EI S11: Captured - Orcs or Trolls

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7040]
### Language

English, but really all of them?

### Source

EE Captured - opening dialog

### Original Text

> Gweddry and his men had been captured by northern orcs

### Proposed Change

Well, they were captured by _Trolls_, and if the Trolls serve the Orcs - that needs more explanation, either in the ending dialog of Lake Vrug, or in the opening dialog here.

And, by the way - since when do the Orcs have a king? Maybe "High Chieftain?"

**Comment by Wedge009** [comment]
At first glance, it does look inconsistent.

Ending of previous scenario:
https://github.com/wesnoth/wesnoth/blob/0712a94b11a0cb9c6da4c9b807e1f5c96fe23265/data/campaigns/Eastern_Invasion/scenarios/10_Lake_Vrug.cfg#L365-L407

Introduction of S11:
https://github.com/wesnoth/wesnoth/blob/0712a94b11a0cb9c6da4c9b807e1f5c96fe23265/data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg#L17-L22

Perhaps there is a historical reason for this or an underlying assumption that orcs and trolls are generally allied. At any rate, I imagine this will be resolved with the eventual revision of the campaign but of course any PR to update the introduction of S11 to resolve the inconsistencies mentioned would be welcome.

**Comment by knyghtmare** [comment]
@Wedge009 EI is a very old and outdated campaign

With that fact being stated, it assumes the captors are the Northerners factions which constitute Orcs, Trolls, Goblins (and their wolves), and Naga. Thus, replacing all those Trolls with Orcish Warlords seems more plausible than a textual change.

Note: There are talks going on a for a EI re-work (not the DM-EI merger) and this topic has been sent to its team for discussion. The rework aims to patch EI for the time being until the Project TDG is ready.

**Comment by Wedge009** [comment]
I was aware of some sort of revision in progress. As long as this is taken into account, which you said it is. I didn't try to 'fix' this because as you already alluded to there may be all sorts of ways to deal with the situation.

**Comment by knyghtmare** [comment]
the code name for one of the 4 reworks.

**Comment by eyalroz** [comment]
Please reopen; the change does not fully resolve the issue. There is no such thing as "trolls from the northern orcish tribes."

A change would need to include some dialog by the Trolls, explaining/stating they're acting on the Chieftain's behalf, and that  Gweddry & co. are to be brought before him. That would avoid the need to have the narration say that Gweddry & al. had been captured. Instead, the narration would only talk about how they were put in dungeons, separated etc., or that they were marched into caverns, something along those lines.

**Comment by cooljeanius** [comment]
> Please reopen; the change does not fully resolve the issue. There is no such thing as "trolls from the northern orcish tribes."
> 
> A change would need to include some dialog by the Trolls, explaining/stating they're acting on the Chieftain's behalf, and that Gweddry & co. are to be brought before him. That would avoid the need to have the narration say that Gweddry & al. had been captured. Instead, the narration would only talk about how they were put in dungeons, separated etc., or that they were marched into caverns, something along those lines.

OK, reopening.

**Comment by Jonathan-Kelly** [comment]
I think this can now be closed as completed, since the newly added total rewrite of EI more than covers the issue.

**Comment by knyghtmare** [comment]
> I think this can now be closed as completed, since the newly added total rewrite of EI more than covers the issue.

okay
