### ISSUE TITLE
gouts -> bouts of faerie fire

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7063]
### Language

English

### Source

Wesnothpedia for Elven Sorceress

### Original Text

This destructive nature commonly manifests itself as gouts of ‘faerie fire’ etc.

### Proposed Change

This destructive nature commonly manifests itself as bouts of ‘faerie fire’ etc.

(gouts -> bouts)

**Comment by Alarantalara** [comment]
'gouts' is fine.
To quote the nearest dictionary: "[literary] a drop or spot, especially of blood, smoke, or flame: gouts of flame and phlegm"

**Comment by eyalroz** [comment]
Ok, didn't realize that, I thought the word only related to the disease.
