### ISSUE TITLE
"Remote Host Disconected" from add-on server via client

### ISSUE THREAD

**Issue by ghype** [wesnoth/wesnoth#7066]
### Game and System Information

- **Version:** 1.16.6
- **Downloaded from:** webside
- **Build info:** none
- **OS:** maOS High Sierra 10.13.6

### Description of the bug

A connection to the add-on server via client is not possible via client. It also cannot auto pull missing add-ons when you want to join a game where I don't have all required add-ons installed. "Remote Host Disconnected" is error I receive after some delay. On some occasion it also crashes. 

### Steps to reproduce the behavior

not clear.

### Additional context

Connection to MP Servers works. No Firewall active. 
Tried different wi-fi connections in different locations, still doesn't work.
No Obvious Proxies activated. 
Note: I have this issues since two years for which I created this post: 
https://forums.wesnoth.org/viewtopic.php?p=660875&hilit=mac#p660875
Related to this issue was that I couldn't access the forum pages with this mac. The difference to two years ago is that for some reason Safari no longer has the connection issue, only chrome (no extensions, no proxies, updated versions.) doesn't want to tag along. Maybe it has something to do that I sent my mac into a workshop where they made a professional system optimisation and virus cleansing. At least I don't have to use TOR browser anymore to access the forum. 
Add-ons I can download manually through the web page which I finally can access through safari as well. But I am worried that my development process will be hell, if I cannot upload anything.

Any advice? 
My Last resort is factory reset with current version (which I have no problem with doing). 
If that won't work I' factory reset and install latest version. This however I really try to avoid as old mac books such as mine (Pro 2014) don't handle new updates well.

**Comment by soliton-** [comment]
Make sure that you're connecting to **add-ons.wesnoth.org** NOT addons.wesnoth.org.

**Comment by ghype** [comment]
It is connecting to exactly that "add-ons.wesnoth.org"

**Comment by soliton-** [comment]
What is the output of `nc -vz add-ons.wesnoth.org 15016`?

**Comment by ghype** [comment]
could you elaborate on the "nc-vc" and "15016"? I have no clue what it is or what I am supposed to do with it.
(my knoweledge of networks is limited, beyond knowing that VPN's and Proxies do exist)

**Comment by soliton-** [comment]
Open a terminal and copy&paste that command in exactly. Press enter and post what it printed.

The command nc is netcat which should connect to the addon server on the 1.16 port to see if that works outside of wesnoth.

**Comment by ghype** [comment]
nc: connectx to add-ons.wesnoth.org port 15016 (tcp) failed: Connection refused

**Comment by ghype** [comment]
and now it timed out

**Comment by soliton-** [comment]
So you cannot connect to add-ons.wesnoth.org:15016 at all. Nothing in wesnoth will change that. How are you connecting to the internet? Any firewalls involved?

You can try the nc command with the ports 80 and 443 instead to verify if you can connect to the webserver on wesnoth.org. If that is the case (as you were saying in your first post, I think) then it seems like something is blocking at least port 15016. If you have no control over the firewalls involved in your internet access then there is not a lot you can do about that unless you can change how you get internet access. A VPN for example should help.

**Comment by ghype** [comment]
u mean like this "nc -vz add-ons.wesnoth.org 80" and "nc -vz add-ons.wesnoth.org 443" ?
Both failed, it says network not reachable.

Firewalls are all off. It also is not the internet connection. I have this issues since two years and I changed internet connection and location doesn't of time. It got to do something either with my device or the network setting (I never touched them though). I am not blocking any adress nor do I have proxies set up. 

I could try a vpn. but my browsers (except chrome) can access the add-on server i don't know though if they are related.

I will get back to this when I have tried a vpn

**Comment by Pentarctagon** [comment]
If you can connect to MP and the forums, but not the add-ons server, that sounds like something is blocking the port. I know @Vultraz has the reverse problem where his school's internet blocks access to the MP server's port.

**Comment by soliton-** [comment]
If your browser can access add-ons.wesnoth.org on port 80 or 443 and nc cannot then it's hard to say what might be going on. That sounds like some odd configuration of your OS.

**Comment by Pentarctagon** [comment]
Closing, since this doesn't appear to be a wesnoth issue.
