### ISSUE TITLE
DM: Why does Delfador take a detour in Dark Sky over Weldyn?

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7067]
### Game and System Information

- **Version:** 1.17.7

### Description of the bug

In Delfador's Memoirs, "Dark Sky over Weldyn", the map route Delfador takes from the Great River to Weldyn goes _around_ Gryphon Mountain. Why does he not take the more direct route, between Gryphon Mountain and Glyn's Forest, through Tath?

**Comment by knyghtmare** [comment]
Picture for context
![image](https://user-images.githubusercontent.com/5283677/198818120-e4c9664a-aaba-467d-af90-a24f45d38433.png)

My remark is that the question is valid. There is nothing blocking that shorter path via Tath to Dan-Tonk and Weldyn. The bigmap should be changed. The story text offers no reason for the long path either.

**Comment by eyalroz** [comment]
Delfador even says he's in a hurry and everything.
