### ISSUE TITLE
DM Prince of Wesnoth - Black screen at scenario start

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7074]
### Game and System Information

- **Version:** 1.17.9 (also 1.17.7)
- **Downloaded from:** Sources from wesnoth.org
- **Build info:** GCC 11
- **OS:** Devuan GNU/Linux Daedalus

### Description of the bug

In DM: Prince of Wesnoth, after the initial dialog, the screen is black, or shows the main map, or shows junk, but I hear the game music. It's as though the first turn has started, but nothing is rendered.

### Additional context

![Screenshot from 2022-11-01 01-20-31](https://user-images.githubusercontent.com/8672255/199128082-ed95c487-40cb-421b-81af-5f18e4646365.png)

**Comment by Pentarctagon** [comment]
Does this happen in 1.17.9?

**Comment by eyalroz** [comment]
I'll need to download and build that... :-P

**Comment by eyalroz** [comment]
@Pentarctagon : Yes, it, does, editing the opening comment.

**Comment by Wedge009** [comment]
Any further information on this? I don't think anyone else has encountered this and such issues are closed after a prolonged period of no updates.

**Comment by Wedge009** [comment]
Closing due to age. Re-open if more information is provided.
