### ISSUE TITLE
bad hex in Test Elevated Terrain scenario

### ISSUE THREAD

**Issue by jgizis** [wesnoth/wesnoth#7080]
### Game and System Information

- **Version: 1.17.9

- **OS: macOS

### Description of the bug

In Wesnoth 1.17.9 scenario Wesnoth Test Elevated Terrain there is a bug for one spot:

The hex at 43,14 can't be entered. It has terrain type Road().

It looks like a road but no one can more there. Similar hexes that work say Road(Flat)  

### Steps to reproduce the behavior

Just check the scenario

### Expected behavior

The type should be Road (Flat)

### Additional context

Here is a screenshot

<img width="1052" alt="Screen Shot 2022-11-01 at 10 35 17 AM" src="https://user-images.githubusercontent.com/3182540/199259046-baab9cb7-7143-459c-a883-9956d92aa409.png">

**Comment by Wedge009** [comment]
If the map is opened in the editor, one can see markers - presumably this is how the various elevation levels are implemented. This also occurs at other places such as (4,18) or (11,4).

I'm not sure if the hex being impassable is a side-effect of these markers, or if this can be worked around. @doofus-01 - any ideas?

**Comment by doofus-01** [comment]
I accidentally created a new terrain type, it causes a couple bugs: 
- no unit has a movement cost assigned to it (this issue)
- help screen shows this new terrain type, and it is missing an icon

I'll fix it this weekend.

**Comment by Wedge009** [comment]
Works for me. Thanks.
