### ISSUE TITLE
Add additional test for [return]

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#7084]
Test that [return] in a nested event exits from the event that contains the [fire_event] too.

Creating as per review comment on #7076

**Comment by stevecotton** [comment]
Will rebase and open a PR after #7076 merges.

**Comment by CelticMinstrel** [comment]
Um, what? Why would this be expected behaviour? Wouldn't it be a bug instead?

**Comment by stevecotton** [comment]
It's the [documented behavior](https://wiki.wesnoth.org/InternalActionsWML#Flow_control_actions), and it's also the current behavior (only tested master at the moment).

**Comment by CelticMinstrel** [comment]
Hmm, okay, it is indeed the documented behaviour… by the way, can we add an equivalent test for `[break]`? It's documented to be equivalent when used outside of a loop or switch, though I think this would be a good opportunity to put an "exit only the current event" behaviour.

**Comment by stevecotton** [comment]
I'll add the new test, but I wouldn't want to change behavior in the same PR. For me, adding the tests is more of a 'document what the current behavior is' thing.

**Comment by CelticMinstrel** [comment]
Well, I wasn't suggesting doing those two things in one PR anyway.
