### ISSUE TITLE
"Chance to hit: " not translated on any language

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7088]
### Language

All

### Source

Mouse over weapon name on attack dialog

### Original Text

\src\gui\dialogs\unit_attack.cpp lines 174 and 185 has "Chance to hit: " but this isn't translated on any language

### Proposed Change

Add "Chance to hit: " to .po files on all languages.

Must be same translation as 
data/gui/window/attack_predictions.cfg:94
msgid "Chance to hit"

**Comment by Pentarctagon** [comment]
As a side note, you can link directly to the lines:
https://github.com/wesnoth/wesnoth/blob/master/src/gui/dialogs/unit_attack.cpp#L185
https://github.com/wesnoth/wesnoth/blob/master/data/gui/window/attack_predictions.cfg#L94

**Comment by stevecotton** [comment]
Oops, sorry that I missed this when merging #6462. The fix IIUC is to use the `N_` macro, but that needs some checks about which textdomain the strings end up in. Should probably also move the trailing whitespace out of the string.

This is only in 1.17, in a file which is currently being actively worked on (@newfrenchy83 has 3 or 4 PRs in progress), but this particular part of that file is probably stable.

**Comment by newfrenchy83** [comment]
> Oops, sorry that I missed this when merging #6462. The fix IIUC is to use the `N_` macro, but that needs some checks about which textdomain the strings end up in. Should probably also move the trailing whitespace out of the string.
> 
> This is only in 1.17, in a file which is currently being actively worked on (@newfrenchy83 has 3 or 4 PRs in progress), but this particular part of that file is probably stable.

resolved in https://github.com/wesnoth/wesnoth/pull/7091
