### ISSUE TITLE
Leadership does not seem to affect same-race second-faction

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7094]
### Game and System Information

- **Version:** 1.17.9
- **Build info:** GCC 12
- **OS:** Devuan GNU/Linux Daedalus

### Description of the bug

I'm playing the Legend of Wesmere, Scenario 3: The Ka'lian under attack.

In this scenario you control two Elvish factions. However, it seems the leadership of one faction (e.g. Kalenz) does not seem to affect troops of the other faction - even though you control them both and they're both of the same race. I'm pretty sure that's a bug... right?

**Comment by knyghtmare** [comment]
Not a bug. Read the leadership description again.

> All adjacent lower level units of the **same** side ...

**Comment by eyalroz** [comment]
@knyghtmare : But in that scenario, the two armies have explicitly joined and are the same side. They're not just allies.

**Comment by ProditorMagnus** [comment]
It is clear that core leadership not affecting allies is intentional. This issue could be considered as suggestion to use variation of leadership which affects allies for that scenario or campaign.

**Comment by Wedge009** [comment]
The question of leadership affecting allied sides seems to have been closed not too long ago: #4258

**Comment by Pentarctagon** [comment]
As a side note, leadership has nothing to do with whether the sides are the same race or not.

**Comment by knyghtmare** [comment]
From what I read, I think the terms faction, side, team and race have all been mixed up in a conundrum.

Kalenz and landar have the same team and are both controlled by the player. They belong to different sides. Thus, Kalenz's (as captain if picked) leadership will only be affecting level 1 units of his side. Landar's level 1 units are not meant to be affected by Kalenz's leadership or any Captain from side 1.

**Comment by eyalroz** [comment]
"they belong to different sides" - not sure how you can say that these two forces of Elves belong on different sides, when Kalenz has come to the Ka'lian seeking his leaders, to inform them and to be guided by them.

In other words: You're describing game mechanics, and I'm talking about the narrative here.

**Comment by Pentarctagon** [comment]
The effects of leadership are not based on the narrative. You have to move each side's units on separate turns too, for the same reason.
