### ISSUE TITLE
Cutscene Replays Don't Work

### ISSUE THREAD

**Issue by Ashmyr** [wesnoth/wesnoth#7099]
### Game and System Information

- **Version: 1.14**
- **Downloaded from: Appstore**
- **Build info:**
- **OS: Chromebook**

### Description of the bug

Octalot on Discord asked me to report this.

Whenever I load a replay from a cutscene, I can't view the units, the map or anything, which is honestly kind of infuriating. It just advances to the next scenario. A lot of the time I want to look at the various elements of the scenario, but the game prevents me from doing such.

### Steps to reproduce the behavior

1. Load cutscene scenario
2. Advance to next scenario
3. Load cutscene replay

### Expected behavior

I wanted to be able to load the replay interface, by looking at the map and units and only have the cutscene play when I start the scenario.

**Comment by Wedge009** [comment]
As discussed on #wesnoth-dev, this seems to be related to the unofficial Android port from Google Play, nothing to do with this project.
