### ISSUE TITLE
Debug text overlap

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7100]
### Game and System Information

The Battle for Wesnoth version 1.17.9 x86_64
Running on Microsoft Windows 7 Service Pack 1 (6.1.7601) x86_64
Distribution channel: Steam

Current video settings

SDL video drivers:        [windows] dummy
Window size:              1920x1080
Game canvas size:         1920x1080
Final render target size: 1920x1080
Screen refresh rate:      60

### Description of the bug

The debug console informational text (and any other text above) overlaps between different outputs (but not lines inside the same outputs), this was not the case in 1.16 with the same settings and resolution.
![Sin título](https://user-images.githubusercontent.com/40789364/200170191-5409ddc5-6cb7-4983-965f-e143b3ce3c5b.png)

### Steps to reproduce the behavior

1. Write :debug
2. Do different things or run different commands that output the text above.

### Expected behavior

The spacing between lines should be the same in one output as it is between different outputs.

### Additional context

Probably Windows-only

**Comment by Wedge009** [comment]
Doesn't appear to be OS-specific.

**Comment by Wedge009** [comment]
This appears to have been caused by a5b154088c3b786ed597060a93399efa53836dee (@Vultraz), just before 1.17.7 was tagged.

**Comment by Wedge009** [comment]
I'm trying to understand the details of what changed. At a guess, the previous surface-based implementation aligned nicely so that the text boxes did not overlap. But using textures to implement the text boxes, the alignment appears to only be done at the text level, ignoring the padding of the boxes surrounding the text, hence the overlap.

BTW, this issue applies to chat messages as well as debug output.

**Comment by Toranks** [comment]
I have noticed that the overlap depends on the zoom level, in case it helps you to find the problem. Text boxes should not be affected by zoom.

![Sin título](https://user-images.githubusercontent.com/40789364/204001503-b761d4c6-6ece-4031-86b7-ea2df21d5fa2.png)

![image](https://user-images.githubusercontent.com/40789364/204001419-c9ef4562-e334-4cad-b2d0-63262530cef4.png)
