### ISSUE TITLE
Players should be given the option to disable allied movement orbs.

### ISSUE THREAD

**Issue by Ashmyr** [wesnoth/wesnoth#7108]
### Describe the desired feature

I'm now playing on 1.16 on Windows.

I've talked about this on Discord.

I personally don't want to see the movements left on the allied units. It makes me think that I'm controlling the side before they start moving every single time. I can intuit how much movement they have left myself. I personally find the new feature rather confusing.

I tried going through preferences, but if I disable or change the allied orb color, no matter what, when it's the ally's turn, their units are shown with the green and red movement orbs, which I do not want to see because it's confusing to me. I also tried going through the code, but Knyghtmare has informed me this isn't in the game's code so I can't edit it.

Although I'm sure most people like the new feature, it's considerably confusing to me and I would honestly just prefer if there was an option to choose how it was before -- allied orbs have one color, and stay that way. I think that if such a big feature is introduced, players should generally have the option to go to the old version.

**Comment by cooljeanius** [comment]
Personally I think there should be a compromise option, too: something like a blue outline (for being allied) around a green/yellow/red inner core, or maybe reuse the new half-orbs added for #5155 where one half is blue and the other is green/yellow/red. Or something. I dunno.

**Comment by stevecotton** [comment]
Reusing the half-orbs is a lot easier than adding a new preference.

**Comment by stevecotton** [comment]
Have you tried out the new orbs on 1.17, or are you waiting until they're backported to 1.16? I'd like to check what the feedback is before backporting.

**Comment by cooljeanius** [comment]
> Have you tried out the new orbs on 1.17, or are you waiting until they're backported to 1.16? I'd like to check what the feedback is before backporting.

Uh, which of us are you asking, @Ashmyr or me?

**Comment by stevecotton** [comment]
Both :D

**Comment by knyghtmare** [comment]
Tested it on 1.17.12+dev. Seems enabling the option makes the allied side orbs behave the same as they did in 1.10.x-1.12.x

**Comment by stevecotton** [comment]
Erm, you do mean *disabling* the option, right?

Are you happy with the UI once you've configured it to your preferenceL

**Comment by knyghtmare** [comment]
> Erm, you do mean disabling the option, right?
> Are you happy with the UI once you've configured it to your preference?

Yes, and yes. Seems quite clear and understandable.

**Comment by cooljeanius** [comment]
So wait how exactly do I turn this on again? I tried switching to the 1.17 branch, but it doesn't look like the allied orbs have changed at all since 1.16...

**Comment by stevecotton** [comment]
> how exactly do I turn this on again?

In "preferences", "advanced", "customize orb colors", there should be a new "During ally turn" tickbox below "Show ally orb" and above the row of color buttons for the ally orb.

At the moment, you need to build from source - it'll be in 1.17.13 and 1.16.9.

**Comment by CelticMinstrel** [comment]
Come to think of it, "Customize orb colours" is no longer accurate, right? We should probably rename the setting.

**Comment by stevecotton** [comment]
It could be "Customize orbs", but OTOH the new settings are sort-of choosing which colors to put on a two-color orb - the new ones would be equivalent to coloring both halves of the orb the same color.

**Comment by CelticMinstrel** [comment]
It's customizing the orb colours, but also whether to show them at all. So it's definitely more than just colours.

**Comment by cooljeanius** [comment]
> > how exactly do I turn this on again?
> 
> In "preferences", "advanced", "customize orb colors", there should be a new "During ally turn" tickbox below "Show ally orb" and above the row of color buttons for the ally orb.
> 
> At the moment, you need to build from source - it'll be in 1.17.13 and probably 1.16.9 (assuming #7342 is merged).

ok well remind me once 1.17.13 is released

**Comment by stevecotton** [comment]
> ok well remind me once 1.17.13 is released

Orbs are done and in 1.16.9 too.
