### ISSUE TITLE
LoW: An Aquaintance in need "Big Fight"

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7110]
### Language

English

### Source

LoW: An Aquaintance in need

### Original Text

Kalenz says: "There will be a big fight with the Orcs at Wesmere"

### Proposed Change

"Big fight" sounds too low-brow for an Elf. 

How about: 

* "The Orcs are advancing on Wesmere, and a great battle will soon be upon us" 
* "A great battle will soon be fought at Wesmere against the Orcs" 
* "Wesmere will soon see a great battle with Orcs"

?

**Comment by Alex58516** [comment]
I have just found and replaced the string in the `.po` files. Is there anything else that is needed to resolve this issue?

**Comment by eyalroz** [comment]
@Alex58516 : Not sure whether you're asking me.

**Comment by cooljeanius** [comment]
> I have just found and replaced the string in the `.po` files. Is there anything else that is needed to resolve this issue?

Did you make a commit with this changes? Ideally issues should be fixed for everyone at the source.

**Comment by Alex58516** [comment]
@cooljeanius: This is a commmit in my own fork, I will open a draft PR once I believe that I have full understanding of the issue and I'm confident that I've solved it.

**Comment by predatorprasad** [comment]
is this issue open??

**Comment by Pentarctagon** [comment]
Yes.

**Comment by eyalroz** [comment]
Kalenz says: "Big issue no close."

**Comment by KaKashi1210** [comment]
@eyalroz i am new to open source and dunno where to track file in big repo can you help me , where should i make change ?

**Comment by eyalroz** [comment]
@eyalroz : I'm not really the person to ask since I'm not one of the developers. Generally, to propose a change to a GitHub repository, you fork it, make a change on a branch in your repository (typically via a local work copy on your own computer),, then finally create a "pull request" from your fork's branch against the development branch of the  original repository.

**Comment by KaKashi1210** [comment]
Well thanks for advice and your time :)

**Comment by VALiUMgithub** [comment]
Hey @eyalroz, can you assign this task to me. I'm just getting started with my open source contribution and this is a great opportunity to get involved in the community. 😀

**Comment by cooljeanius** [comment]
> @VALiUMgithub : I'd love to... but I can't :-P
> 
> I'm not a Wesnoth developer, just a game player like everybody else who is also good at complaining about stuff.
> 
> I do actually write a bunch of free software, but - not Wesnoth.
> 
> Maybe @Pentarctagon can help?

I assigned it

**Comment by Wedge009** [comment]
Closing as resolved with #7505.
