### ISSUE TITLE
Inconsistency of trait order w.r.t HP calculation

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7118]
### Game and System Information

- **Version:** 1.17.9
- **Build info:** GCC 12
- **OS:** Devuan GNU/Linux Daedalus

### Description of the bug

* When I recruit an Elvish Shaman with traits "Resilient, Quick" - it has 29 HP. 
* When I recruit an Elvish Shaman with traits "Quick, Resilient" - it has 30 HP.

I don't believe the order of traits should have this (or any) effect.

**Comment by Pentarctagon** [comment]
This has been discussed previously on multiple occasions, and this is the intended functionality.

**Comment by eyalroz** [comment]
@Pentarctagon : Link to previous discussion perhaps? That sounds rather... ridiculous.

**Comment by Pentarctagon** [comment]
https://forums.wesnoth.org/viewtopic.php?t=21754

**Comment by eyalroz** [comment]
> https://forums.wesnoth.org/viewtopic.php?t=21754

So, I read that, and nobody on the thread provides any justification for this behavior. Based merely on that thread, this bug should be reopened. i.e. the fact that an incorrect/inappropriate behavior was introduced intentionally does not in itself justify it.

Also, asked for elaboration on that thread.

**Comment by Pentarctagon** [comment]
> nobody on the thread provides any justification for this behavior

The second and third posts do exactly that.

**Comment by eyalroz** [comment]
> The second and third posts do exactly that.

The second post really doesn't.

The third post is said in jest - that's how I read it anyway. If it's not a joke, it is an ex-post-facto attempt at a rationalization which does not make sense: There is no inherent "diversification" of unit HP. If that were the intent, then HP would be drawn randomly from some range determined by the (unsorted) traits, not set by trait order.

**Comment by Toranks** [comment]
Maybe I'm wrong, but my intuition tells me that on quick, resilient, -5% is applied to HP BEFORE applying resilient, and on resilient, quick, -5% is applied to HP after applying resilient, thus the calculation is not the same. That should be the explanation at the programming level.

**Comment by eyalroz** [comment]
@Toranks : I understand _how_ this happens, what I'm asking an explanation of how is it justifiable for "quick" to mean something different depending it appears to the left or to the right of another trait. A "quick, dextrous" elf is the same as a "dextrous, quick" elf - reading-comprehension-wise.

**Comment by CelticMinstrel** [comment]
Mathematically, there's no difference between applying quick first or resilient first either, so this is clearly happening because of rounding error. I don't personally think it's a big deal (since it's only a difference of 1 HP) but I do think the argument for it being a bug makes sense.

**Comment by eyalroz** [comment]
@CelticMinstrel : I'm not sure it's that clear. It's `some_rounding(X * 0.95) + 4` vs `some_rounding((X + 4) * 0.95)` ; and that can be different without being an error.

**Comment by CelticMinstrel** [comment]
Ahh, one is additive and the other is multiplicative, huh? Well, still, I think it makes sense that they should be the same regardless of order but I also don't think it's a big deal if they're slightly different.
