### ISSUE TITLE
[Campaign][TRoW][UX] Patch Cutscenes to prevent generation of replay saves

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7123]
The following Cutscene scenarios of TRoW have to be patched with `replay_save=no` inside `[endlevel]`.

- [ ] Return to Oldwood
- [ ] Southbay in Winter
- [ ] The Kalian
- [ ] Spy in the Woods
- [ ] The Plan

### Context:

Replay Saves for cutscene are not required as the replay functionality is not usable in it, as cutscenes start and end with a start event.

**Comment by Wedge009** [comment]
It looks like disabling of replay saving isn't very common - this issue should not be flagged as specific to TRoW.

I'm assuming scenarios with `theme=Cutscene_Minimal` (I'm assuming these are story-based scenarios as this theme removes normal game controls like the side-bar). There are 29 scenarios of which 18 are missing `replay_save=no`:
* DW S11: Getting Help
* DM S1: Overture
* DM S5: Council in Weldyn
* EI S15: The Council
* HttT S21: The Elven Council
* LoW S13: News from the Front
* SoF S2t: In the Dwarven City
* SoF S3t: The Council Regathers
* SoF S4t: The Jeweller
* SotA S7: Meeting of the Minds
* SotA S13: Together Again
* SotA S17: Mortality
* TRoW S7: Return to Oldwood
* TRoW S11: Southbay in Winter
* TRoW S16: The Kalian
* TRoW S18: A Spy in the Woods
* TRoW S21: The Plan
* UtBS S10: Speaking With the Fishes

**Comment by knyghtmare** [comment]
I can confirm for TRoW, UtBS, SoF, HttT. Not sure about the remaining three cases as I haven't played them since they fell from grace, but the listed ones should be correct.

**Comment by Ashmyr** [comment]
I honestly wish that they had replays. It's good to go back and see the dialogue and context. I suppose closing the ability to make replays solves the bugs and stuff, but it's a rather disappointing outcome for me. The only other way to see the dialogue is if you reload the scenario or go to the campaign dialogue pages, which feels a little tedious...

**Comment by Wedge009** [comment]
The scenario can still be re-loaded. No different than re-loading the replay.

**Comment by Ashmyr** [comment]
I disagree but I won't argue any longer. I've let my position be known here and on the Discord/IRC, and if you make this choice, I disagree with it, but it's fine.
