### ISSUE TITLE
Character Traits are Inconsistent

### ISSUE THREAD

**Issue by Ashmyr** [wesnoth/wesnoth#7128]
### Describe the desired feature

- [x] #7141

- [x] #7148
 
- [x] #7139
There could be more, but these are ones I'm recalling off the top of my head.

**Comment by cooljeanius** [comment]
> ### Describe the desired feature
> 
>     * Kalenz in HttT has no traits, but in LoW he has Quick, Dextrous.
> 
>     * Delurin has random traits (I think) in Liberty, but in HttT he has random traits (I think?), when I last loaded the scenarios of both campaigns his traits were different.
> 
>     * Relgorn has Strong, Healthy in DM, but no traits in HttT
>       There could be more, but these are ones I'm recalling off the top of my head.

In the case of Kalenz it could just be due to age; he's lost his quickness and dextrousness over the years or something? Although in TEG he has Loyal and Dextrous, and that takes place at the same time as HttT, so... yeah I guess he should keep Dextrous at least... (also in TEG, Relgorn doesn't have any traits there either, but he just appears in cutscenes, so it doesn't really matter...)

**Comment by Wedge009** [comment]
Similar for the reasons I gave in #7126, I don't think it's unreasonable that the same unit in different campaigns behave slightly differently in terms of game-play. I think of the same characters across different games in commercial offerings, particularly in the RPG genre (being reset to low experience level, for example), this sort of thing happens very frequently.

Of course, if it can be justifiable to adjust some traits in terms of story and it doesn't break things in terms of game balance, I wouldn't necessarily object.

**Comment by knyghtmare** [comment]
> Delurin has random traits (I think) in Liberty, but in HttT he has random traits (I think?), when I last loaded the scenarios of both campaigns his traits were different.

In liberty, Delurin has random traits, so what traits should he have? the same as that of HttT?

**Comment by Ashmyr** [comment]
Does he have defined traits in HttT? If so, that's what I would go with.

**Comment by CelticMinstrel** [comment]
> In the case of Kalenz it could just be due to age; he's lost his quickness and dextrousness over the years or something?

If that were the intention, I'd say you should replace one of his traits with the aged traits for HttT.

**Comment by knyghtmare** [comment]
> Kalenz in HttT has no traits, but in LoW he has Quick, Dextrous.

> In the case of Kalenz it could just be due to age; he's lost his quickness and dextrousness over the years or something? Although in TEG he has Loyal and Dextrous, and that takes place at the same time as HttT, so... yeah I guess he should keep Dextrous at least... (also in TEG, Relgorn doesn't have any traits there either, but he just appears in cutscenes, so it doesn't really matter...)

LoW's code says he has quick and resilient, and not dexterous.  So, I will be assigning him loyal and resilient for HttT

**Comment by Ashmyr** [comment]
Idea for Delurin traits:
- Loyal
- Resilient
- Strong (Or, if illegal traits are allowed, Dextrous?)

**Comment by knyghtmare** [comment]
Closed by #7151's merger.
As all three cases were answered.
