### ISSUE TITLE
Thousands of lines with [special_note] appended to units with movement type spirit (ghosts) and mounted foot

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7132]
### Game and System Information

Battle for Wesnoth v1.16.6 x86_64
Steam
Windows 7

### Description of the bug

This line is added to every shadow unit (can be seen with inspect console) several times every turn, growing with each turn, until reaching thousands and saturating the savegame.

```
[special_note]
	note=_"Spirits have very unusual resistances to damage, and move quite slowly over open water."
[/special_note]
```

In addition, hundreds or thousands of lines like this appear in the log file

```20221116 05:04:29 error deprecation: SPECIAL_NOTES ha quedado obsoleto y eliminado.; Use [special_note]note= tags or special_note= in an ability or weapon special to apply special notes.```

### Steps to reproduce the behavior

Start a map with ghosts
Skip several turns
Use debug inspect console and go to any shadow, wraith or spectre unit

### Expected behavior

Only one [special_note] for every unit

### Additional context

No real effect on gameplay

**Comment by Pentarctagon** [comment]
Please provide a save file where this is happening.

**Comment by Toranks** [comment]
Here is a plain save zipped on a scenario with plenty of spirits:
[IdE-Los llanos hundidos Turno 11.zip](https://github.com/wesnoth/wesnoth/files/10018161/IdE-Los.llanos.hundidos.Turno.11.zip)

**Comment by Pentarctagon** [comment]
Also, does this use any add-ons?

**Comment by knyghtmare** [comment]
Not just ghosts, it seems. Cavalryman and Horseman's mountedfoot is also affected.

**Comment by Toranks** [comment]
> 

Only Advanced Wesnoth Wars, but it shouldn't be related, I maintain this addon and I know the code pretty well

**Comment by Pentarctagon** [comment]
I'm not able to reproduce this on 1.16.6 on Linux with any of those units. In fact, the save file has no [special_note] tags at all.
[2p — Hamlets-Auto-Save6.zip](https://github.com/wesnoth/wesnoth/files/10018251/2p.Hamlets-Auto-Save6.zip)

Please try to reproduce this when no add-ons are installed at all.

**Comment by Wedge009** [comment]
I also cannot replicate this - I was going to ask if this is really a valid issue if it's dependent on an add-on being present, but of course there may still be some unintended behaviour if it is indeed caused by a particular add-on.

**Comment by Pentarctagon** [comment]
Note also that the error message is regarding the presence of the deprecated SPECIAL_NOTES macro, which is no longer used in mainline.

**Comment by Toranks** [comment]
I've tested on a multiplayer map with and without addons and it does not happen in any case neither with ghosts nor with Cavalryman. It should only happen in campaign scenarios (which is the only thing I've played these weeks). 
[knyghtmare](https://github.com/knyghtmare) can you tell us in what kind of map did you happen with the Cavalryman?

**Comment by ProditorMagnus** [comment]
active_mods="advance_wesnoth_wars,Gui Debug Tools"

**Comment by Toranks** [comment]
It's possible that it's Gui debug tools, I'm closing the thread since I misunderstood Knightmare and thought it happened to him.
If no one can reproduce it, it must be interference. Sorry for the omission, I forgot about that addon.

**Comment by Wedge009** [comment]
I have GUI Debug Tools as my only add-on, and wasn't able to replicate the issue.

**Comment by stevecotton** [comment]
It appears that the detail missing from the reproduction steps (but present in the save-file) was that this occurred in EI S13, where the ambush-handling code uses `MODIFY_UNIT`.
