### ISSUE TITLE
LoW S9 and S10: Scenario designs are too similar

### ISSUE THREAD

**Issue by eyalroz** [wesnoth/wesnoth#7137]
### Game and System Information

- **Version:** 1.17.9

### Description of the bug

In LoW: Cliffs of Thoria, the bottom half of the map is an almost-exact copy of the map from the previous scenario, Bounty Hunters: Forest, villages, mountains - just like last level.

### Expected behavior

The Scenario 10 map should be significantly different from the scenario 9 map, so that it doesn't seem like part of it remained a copy-paste of the original.

**Comment by Pentarctagon** [comment]
And?

**Comment by eyalroz** [comment]
You guys should tweak the map to make it not look like a copy-paste job...

**Comment by Pentarctagon** [comment]
Then say that in the "Expected behavior" field. "Lame!" isn't a bug.

**Comment by eyalroz** [comment]
Ok.

**Comment by CelticMinstrel** [comment]
Fixed by #9128
