### ISSUE TITLE
Synchronize Character "Delurin" between HttT and Liberty.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7148]
This character is more or less the same person between the 2 campaigns so his traits should be consistent.

Proposed: 
Loyal + Intelligent + Resilient (HttT)
Intelligent + Resilient (Liberty)

He is not loyal in Liberty so just 2 traits there.

**Comment by Ashmyr** [comment]
What I suggested was Loyal, Resilient and Strong, or Dextrous if illegal traits are in consideration, though I suppose Intelligent might work.
