### ISSUE TITLE
[unstore_unit] causes duplicate [movetype][special_note]s

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7153]
### Game and System Information

- **Version:** 1.16.6+dev, 1.17.10+dev
- **Downloaded from:** Git
- **Build info:** 94d9cdb2db05ff99ed7ee7d579ec810a0d2c71b2
- **OS:** Linux

### Description of the bug

For movetypes that include `[special_note]`s, storing and unstoring a unit causes duplicates of the special note.

Originally reported by @Toranks in https://r.wesnoth.org/t56418

### Steps to reproduce the behavior

```
# wmllint: no translatables

#####
# API(s) being tested: [special_note], [unstore_unit]
##
# Actions:
# Alice is a Spectre, a unit which should have 1 special note from the 'undeadspirit' movetype.
# Store Alice
# Unstore Alice
# Store Alice
##
# Expected end state:
# Both stored copies of Alice have 1 special note.
#####
{GENERIC_UNIT_TEST "special_note_count" (
    [event]
        name=start

        # The copies are called alice1 and alice2 so it's easy to work out which assert failed.
        [store_unit]
            [filter]
                id=alice
            [/filter]
            variable=alice1
        [/store_unit]
        {ASSERT ({VARIABLE_CONDITIONAL alice1.special_note.length equals 1})}

        [unstore_unit]
            variable=alice1
        [/unstore_unit]

        [store_unit]
            [filter]
                id=alice
            [/filter]
            variable=alice2
        [/store_unit]
        {ASSERT ({VARIABLE_CONDITIONAL alice2.special_note.length equals 1})}
    [/event]
) SIDE1_LEADER="Spectre"}
```

**Comment by Toranks** [comment]
Reported and closed previously on ;
https://github.com/wesnoth/wesnoth/issues/7132

Other people couldn't replicate it, so I thought it was an addon and closed it.

**Comment by stevecotton** [comment]
Oops - I checked for open bugs, and forgot to search for closed ones.

**Comment by stevecotton** [comment]
There should be zero `[special_note]`s in the unit's WML, because the note should be coming from the movetype. So the bug is in `[store_unit]` and in the unit test code that I posted both asserts should be checking that it's zero rather than one.

The movetype's data in included in the unit because events may have modified it after the unit was built. However, the special notes for the movetype will be regenerated when the unit is rebuilt, there's no need to include them in the unit itself.
