### ISSUE TITLE
[Units][UI] XP/HP Bar get ridiculously long if Extended

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7171]
### Game and System Information

- **Version:** 1.17.10
- **Downloaded from:** SF
- **Build info:** Downloaded Client
- **OS:** Windows 10

### Description of the bug

XP/HP Bar of units if extended beyond normal values can get ridiculously long...(See screenshot)

### Steps to reproduce the behavior

1. Start UtBS
2. Get Garak
3. Fight with Garak
4. Observe his huge XP bar 

### Expected behavior

XP/HP bars stay the default length. 

### Additional context

![image](https://user-images.githubusercontent.com/5283677/204267864-8e0d78d6-856c-4848-94d5-7b149e5a7142.png)

**Comment by knyghtmare** [comment]
Also, do not throw in Campaign label, is this issue is general. As the MP scenario "The Kraken" got affected as well

**Comment by stevecotton** [comment]
Quicker reproduction steps:
1. Start the tutorial.
2. Attack the Quintain, giving it 1 XP.
3. Observe its huge XP bar.

**Comment by irydacea** [comment]
I feel like commit afd6baa7cf1685610c72305f5c9f989078462dff might be responsible for some loss of information in the routine that calculates final bar dimensions even before Vultraz's refactoring in c6932e813346cd0776096c2add47f6ea14d72af6. I've submitted a patch as that may address this in a way that I *believe* is similar to what Wesnoth 1.16 and earlier used to do here.
