### ISSUE TITLE
Update CI to use Node.js version 16

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7178]
At the bottom of the CI log pages, Github is now adding a deprecation note about Node.js 12, with an aim to move to Node.js 16 in summer 2023.

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: ...

Collated across the various annotations, the actions to upgrade are at least the following:
* actions/checkout@v2
* actions/upload-artifact@v2
* technote-space/workflow-conclusion-action@v2

**Comment by stevecotton** [comment]
Based on the `git blame` for actions/checkout's README.md, it seems checkout@v3 would be a drop-in replacement. Haven't looked at the other actions.

**Comment by soliton-** [comment]
Same with upload-artifact@v3 and workflow-conclusion-action@v3.
