### ISSUE TITLE
[Terrain][Graphics] Snow Mountain and Mountain have bad Transition

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7180]
### Game and System Information

- **Version:** 1.17.10
- **Downloaded from:** SourceForge
- **Build info:** Downloaded Client
- **OS:** Windows 10

### Description of the bug

![image](https://user-images.githubusercontent.com/5283677/204862839-abf49f22-4795-4b6c-8205-9dc5490f2173.png)

### Steps to reproduce the behavior

Open Editor.
Place Mountain and Snow Mountain in screenshot arrangement
Observe

### Expected behavior

Smooth transition of mountain-to-snowymountain

**Comment by cooljeanius** [comment]
oh yeah I've seen this one when trying to make the winter maps in SotBEEE more snowy; I wound up with some weird tile patterns trying to avoid it...
