### ISSUE TITLE
Inspect window can crash on HDPI displays (1.17 only)

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7201]
### Game and System Information

- **Version:** 1.17.10+dev
- **Downloaded from:** Built from Git
- **Build info:** GCC and b5ff5c3ddc706f1281bbbe2f235b16c4b00f92db
- **OS:** Linux

### Description of the bug

The inspect window paginates data so a maximum of 20000 characters appear in the right-hand window. On an HDPI display, 1.17's large fonts can make the 20000 characters larger than Pango's limits. An example of circa 14000 characters is already enough to need 2740x33009 pixels on my 3840x2160 screen, which allows the surface to be created in  pango_text::create_surface but then gets CAIRO_STATUS_INVALID_SIZE in pango_text::render.

Similar to #6952, there's no longer viewport code in canvas.cpp limiting the area to the drawn.

In #7194, I reduced the character limit while testing to trigger pagination, but didn't test with the full 20000 character limit.`

### Steps to reproduce the behavior

1. Start Under the Burning Suns, because the two starting units have lots of AMLA data stored in their `[unit]`
2. `:debug`
3. `:inspect`
4. Scroll down to the "units" section (this takes some time, the scrolling is slow and there are 1800 entries in the `outer villages` array)
5. Click on either unit (there are only two at the moment, Kaleh and Nym)
6. The game exits, `Caught general 'St12length_error' exception: Text is too long to render`.

**Comment by stevecotton** [comment]
That `outer_villages` array's size is #7202.

**Comment by Wedge009** [comment]
Admittedly I'm not on what would be considered a 'hidpi' monitor (2560x1440) but I didn't get a crash. Instead, I sometimes get a display, sometimes not, but I see the following in my stderr:
`20221208 08:53:37 error SDL: When creating texture from surface: Texture dimensions are limited to 16384x16384`

**Comment by stevecotton** [comment]
I think the same root cause has two different error messages, depending on the font size. If the height is 2^15 or more pixels then it hits the `Text is too long to render` sanity check, if it's between 2^14 and 2^15 then it passes that and runs into the `Texture dimensions are limited` check.

However, it's not worth making the `too long to render` check have the same behavior as the `texture dimensions are limited` check, IMO. Instead we should either fix canvas.cpp to not request such huge viewports, or we could work around it by limiting the amount of text per page to a smaller length.

**Comment by stevecotton** [comment]
@Vultraz please would you give an ETA for fixing the credits screen crash (#6952)? I'm assuming it's likely to fix this issue too.

**Comment by neoedmund** [comment]
Credits has 1500+ lines, and `cairo_image_surface_create_for_data` failed(why?) to create a image with (something like w=372  h=38087 strid=1488).
I suggest to use eg. `SDL_OpenURL` to open a credits web page instead, for a (temp) quick fix.

**Comment by Wedge009** [comment]
On 3840x2160 @ 27" ~= 163 ppi screen, I wasn't able to replicate the crash testing with 4a5ac6ed29e, just a repeat of the error message I stated on 2022-12-08. Not sure of the threshold to trigger the crash, but at least I was able to replicate #7093 on Linux.
