### ISSUE TITLE
SoF last scenario can't load

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7210]
### Game and System Information

1.17.10

### Description of the bug

![imagen](https://user-images.githubusercontent.com/40789364/207440493-ed2c917a-28f6-447c-805d-d2aeaf35a417.png)

### Steps to reproduce the behavior

- Play Sceptre of Fire to the last scenario or load 9_Caverns_of_Flame.map on map editor.

**Comment by Toranks** [comment]
Changing **Isay** with **Iasy** on all tiles affected, solves the problem

**Comment by knyghtmare** [comment]
Hehe.

**Comment by knyghtmare** [comment]
>  Seems to me that Isay is the intended code, not Iasy.

Are you suggesting that the map itself is correct but the terrain code `Isay` is not being recognised/loaded/showing up? Then the patch required is a different approach all together.

Does map editor show big "D" on top of `Iasy` or `Isay`?

**Comment by Wedge009** [comment]
I only inferred this from #7042 being later than #5397. And yes, in this case it would mean a different change to just renaming everything to `Iasy` (which is what it already was previously).

Probably best to wait for @doofus-01 to clarify what should be done here unless we are aiming for some sort of 'hot fix' release.

**Comment by doofus-01** [comment]
Bug came from a find-and-replace that either went too far or not far enough.  Propagating `Isay` to the terrain definition probably makes the most sense.
