### ISSUE TITLE
Legend of Wesmere S11 and S14 gold carry-over inconsistency

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7230]
### Language

All

### Source

Battle of the Book, Campaign Legends of Wesmere

### Original Text

40% carried gold

### Proposed Change

80% carried gold

Note: If it's not a typo, and it's an error in the mission objectives and it really should be 40%, then change the objectives

**Comment by Wedge009** [comment]
Confirmed. I believe 40% has been the standard for a long time now, but completing LoW S11 results in 80% carry-over. Trying to find where it's getting this figure from.

**Comment by Toranks** [comment]
Maybe this event is interfering? Upon killing Aquagar, this event takes precedence:

```
    [event]
        name=last breath
        [filter]
            id=Aquagar
        [/filter]
        [message]
            speaker=unit
            # wmllint: local spelling Morogoth
            message= _ "I die, but I will not go unavenged! Cursed will you be Kalenz! You will never find lasting peace in all your years. You will lose your dearest. And you, Crelanu, your book will bring woe on you and haunt all its future owners to their graves! This will be the price for slaying me, Aquagar, great drake wizard of Morogoth."
        [/message]

        [message]
            id=Olurf
            message= _ "Some scary fellow this Aquagar thinks he is! Come now, I think Crelanu owes us some drinks."
        [/message]

        [endlevel]
            result=victory
            save=no
#ifdef MULTIPLAYER
            bonus=0.3
#else
            bonus=yes
#endif
        [/endlevel]
    [/event]
```

**Comment by Wedge009** [comment]
I understand last breath is to trigger just before a unit is killed off - usually for a final line of some sort - so this triggers before the enemies defeated event and that seems valid to me. Plus I don't see any reference to gold there.

Probably needs someone more familiar with WML to look at this.

**Comment by knyghtmare** [comment]
> Probably needs someone more familiar with WML to look at this.

Let me see.

> **bonus**: whether the player should get bonus gold (maximum possible gold that could have been earned by waiting the level out). The default is bonus=yes. ([Version 1.13.2 and later only](https://wiki.wesnoth.org/DevFeature)) Alternatively, a number, defining the bonus multiple (1.0 meaning full).

> carryover_percentage: by default 80% of the gold is carried over to the next scenario, with this key the amount can be changed.

So, since the Aquagar death event plays first the enemies defeated event, and there is no percentage specified, it defaults to 80%, not 40%. I think the fix is adjusting the objectives to state 80% finishing gold (given what the next battle scenario is...you need every coin you can get)

I know LoW is incomplete, bugged in a few places and a prime victim of developer negligence (do not deny this), but this is just plain absurd.

### Summary:

Fix is adjust objectives to state 80% finishing gold will be carried over, not 40%.

**Comment by Wedge009** [comment]
I thought the default was changed to 40% some time ago. Well, assuming that it is still 80%, I also verified that the previous scenario, Cliffs of Thoria, has 40% gold carry-over. Looking over the WML, I don't see anything explicitly stating 40, other than the objectives and the `DEFAULT_VICTORY` macro. In that regard, it appears to the same to me as for Battle of the Book - so what's different that causes one to have 40% carry-over, and the other, 80%?

**Comment by Toranks** [comment]
10_Cliffs_of_Thoria.cfg
Lines 213-216
```
            [gold_carryover]
                bonus=yes
                carryover_percentage=40
            [/gold_carryover]
```

**Comment by Wedge009** [comment]
That's my point. The same thing is in S11 as well.

**Comment by Toranks** [comment]
S14 same typo

**Comment by Wedge009** [comment]
In English, typo is colloquial for a spelling error. This does not appear to be a spelling or typing error but a serious inconsistency in how gold carry-over is handled.

At any rate, I **cannot** confirm S14. 40% is listed in the objectives and 40% is what gets carried over in the victory summary.

**Comment by Toranks** [comment]
I started S15 scenario with 330, so Kalenz 80% is what is carried to next scenario.
![imagen](https://user-images.githubusercontent.com/40789364/210136466-ad56ac5b-e686-4e81-b1d4-104fff1d3018.png)
