### ISSUE TITLE
iron armor broken in world conquest

### ISSUE THREAD

**Issue by clmates** [wesnoth/wesnoth#7234]
### Game and System Information

- **Version:**1.6.1
- **Downloaded from:** web page
- **Build info:** 
- **OS:** windows

i

### Description of the bug

n World Conquest I have a leader thieve level 2, picked the iron armor that gives pierce and blade resistances, also drives al negative resistances to 0 and gives steadfast. it worked, but when we passed to map 2, only steadfast lasts, all the rest is gone

### Steps to reproduce the behavior

get faction alliance, leader thieve
get item iron armor
pass to map 2

### Expected behavior

should have no negative res, increased blade  impact and pierce rest + steadfast

### Additional context

we had the following add on active. Reign of the lords and color changer

**Comment by clmates** [comment]
saved and loaded the game and my resistances are back ....
strange

**Comment by Pentarctagon** [comment]
Version is 1.16.1 I assume, not 1.6.1?

**Comment by knyghtmare** [comment]
Encountered before but not reported
https://forums.wesnoth.org/viewtopic.php?p=672940#p672940
https://forums.wesnoth.org/viewtopic.php?p=672943#p672943

**Comment by clmates** [comment]
apologies, version 1.16.6

**Comment by gfgtdf** [comment]
Hi, long time no see (i have lost  (or at least cannot find right now) my discord login otherwise i'd have greeted there)

I took a look into this issue, and i think its because custom [effect]s don't work on units that are on the recall list at the start of a game, in particular here https://github.com/wesnoth/wesnoth/blob/7e67bc5d081ae4025bbe3cb49f810e84762d3f18/src/teambuilder.cpp#L178 those units are handled in  build_team_stage_one instead of  build_team_stage_two, and the custom effects are only available in build_team_stage_two since the lua kernel is initialized in between those ( https://github.com/wesnoth/wesnoth/blob/6ace55e0639bec72a46d96c5135ae1cfb7dd6442/src/game_state.cpp#L225 )

**Comment by cooljeanius** [comment]
> Hi, long time no see (i have lost (or at least cannot find right now) my discord login otherwise i'd have greeted there)

Welcome back! We all had missed you and were beginning to worry as to what might have happened to you!

**Comment by Pentarctagon** [comment]
Welcome back!

**Comment by gfgtdf** [comment]
I'm sorry for making you believe that, i have indeed struggeld with health issues , the last years (and still do somewhat) , but i have never died at least :D .

**Comment by Elvish-Hunter** [comment]
@gfgtdf Welcome back! I'm sorry about your Discord account (at least you can always create a new one), but if you have issues with your forum account just contact me or @Pentarctagon.

**Comment by gfgtdf** [comment]
@Elvish-Hunter thx, the forum account still works. And there is a small chance that i'll find the login to the discord account somewhere on an old windows 7 pc that i haven touched since anicent times.

**Comment by cooljeanius** [comment]
Also, if something happens to you in the future, could you arrange for someone to let us know, so that we don't worry again? You have a rather large [bus factor](https://en.wikipedia.org/wiki/Bus_factor) that it would be helpful to mitigate.

**Comment by irydacea** [comment]
@gfgtdf Welcome back! It's good to know you're at least alive :D

By the way, if at any point you want to recover access to your IRC account... don't. freenode suffered a hostile takeover by a lunatic in your absence and all old accounts were permanently lost as part of it. Most projects including Wesnoth moved away from the so-called "freenode" and now use other IRC networks instead. Wesnoth in particular moved to [Libera Chat](https://libera.chat) (the user and dev channels are still #wesnoth and #wesnoth-dev). If you decide to create an IRC account there and confirm your identity through forum PM we can give you a `wesnoth/developer/` cloak again.

**Comment by gfgtdf** [comment]
> Also, if something happens to you in the future, could you arrange for someone to let us know, so that we don't worry again

You mean another person? idk how could fit that role tbh. but i'll think about it.

> @gfgtdf Welcome back! It's good to know you're at least alive :D

Thank you.

> If you decide to create an IRC account there and confirm your identity through forum PM we can give you a wesnoth/developer/ cloak again.

Thx, i'll look into it eventually, but i feel like i forgot most things about irc it'll probably take a while. Also i found another discord account of which i thought was my normal developer discord account, but that seems not to be the case, so i wonder why i have it.  Maybe i intended to switch to that account anyways at some point, not sure though, maybe i should just use that one.

**Comment by gfgtdf** [comment]
Reopen for 1.16

**Comment by gfgtdf** [comment]
Fixed in 1.16
