### ISSUE TITLE
SOTA - Error on portrait folders on zombie-utils.cfg

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7254]
### Game and System Information

1.17.11

### Description of the bug

Fix is easy:
`{NEW_UNIT_TYPE_KILLED (type=Giant Rat) ("SotA Walking Corpse_Rat") "units/undead/zombie-rat.webp"}`
   
Must be:
`{NEW_UNIT_TYPE_KILLED (type=Giant Rat) ("SotA Walking Corpse_Rat") "portraits/undead/zombie-rat.webp"}`

Or when first rat is killed, doesn't appear his image.

Besides, spider portrait exist, but is the sprite, not the portrait. Must be changed for consistency, too:

`{NEW_UNIT_TYPE_KILLED (type=Giant Spider) ("SotA Walking Corpse_Spider") "units/undead/zombie-spider.png"}`
  to:
 `{NEW_UNIT_TYPE_KILLED (type=Giant Spider) ("SotA Walking Corpse_Spider") "portraits/undead/zombie-spider.webp"}`
            
Location:
https://github.com/wesnoth/wesnoth/blob/f579000862b7e0020388256574c49149c86e6553/data/campaigns/Secrets_of_the_Ancients/utils/zombie-utils.cfg#L497

**Comment by Wedge009** [comment]
I thought I fixed something like this not too long ago...

**Comment by Wedge009** [comment]
Similar to #7255, can you report the actual symptoms in the issue and your suggested changes as PRs? This way we can see what the actual problem is.

**Comment by knyghtmare** [comment]
```ini
{NEW_UNIT_TYPE_KILLED (type=Giant Spider) ("SotA Walking Corpse_Spider") "portraits/undead/zombie-spider.png"}
```
Pretty sure the portrait is a `.webp` file

**Comment by Wedge009** [comment]
Uh, this is already resolved.
