### ISSUE TITLE
SOTA - "plague" not translated because wrong textdomain

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7255]
### Language

All

### Source

SOTA

### Original Text
https://github.com/wesnoth/wesnoth/blob/f579000862b7e0020388256574c49149c86e6553/data/campaigns/Secrets_of_the_Ancients/utils/zombie-utils.cfg#L1

#textdomain wesnoth-units
#define WEAPON_SPECIAL_SOTA_PLAGUE
    # Written this way to allow overwriting the base Necromancer weapon in the SotA Necromancer implementation
    [plague]
        id=SotA_plague
        name= _ "plague"
        description= _ "When a unit is killed by a Plague attack, that unit is replaced with a Walking Corpse on the same side as the unit with the Plague attack. This doesn’t work on Undead or units in villages."
        type=null # prevents normal corpse, and allows SotA code to handle it
    [/plague]
#enddef

### Proposed Change

#textdomain wesnoth-help
#define WEAPON_SPECIAL_SOTA_PLAGUE
    # Written this way to allow overwriting the base Necromancer weapon in the SotA Necromancer implementation
    [plague]
        id=SotA_plague
        name= _ "plague"
        description= _ "When a unit is killed by a Plague attack, that unit is replaced with a Walking Corpse on the same side as the unit with the Plague attack. This doesn’t work on Undead or units in villages."
        type=null # prevents normal corpse, and allows SotA code to handle it
    [/plague]
#enddef

**Comment by Wedge009** [comment]
I think this kind of suggestion is better submitted as a PR rather than an issue.

Admittedly, I'm not terribly knowledgeable about the text domains - what difference does it make moving it from units to help? Perhaps it would be better to report the actual symptoms as an issue and your suggested change from units to help as a PR.

**Comment by Toranks** [comment]
I just looked up where the "plague" and "When a unit is killed by a Plague attack....etc" strings were and found them in wesnoth-help. I don't know well what is the logic using one textdomain and another (besides campaigns and addons), and why exist so many textdomains.

**Comment by Wedge009** [comment]
For future reference, adding 'resolves #(issue number)' to the commit message will auto-close issues when the PR is merged to master.

For the record, I verified the change against the undead bat in Ardonna's starting units. Plague is translated now.
