### ISSUE TITLE
[Units][Loyalists] Grand Knight base image does not fit into sidebar

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7257]
### Game and System Information

- **Version:** 1.17.11+dev
- **Downloaded from:** Github
- **Build info:** Msys2 (latest commit)
- **OS:** Windows 10

### Description of the bug

Grand Knight Unit image is moved rightwards and downloads in sidebar UI

### Steps to reproduce the behavior

Just hover over a GK to view its Side bar UI in any map.

### Expected behavior

GK unit image fits into the sidebar UI's 72x72 window like it used to.

### Additional context

![image](https://user-images.githubusercontent.com/5283677/210206792-a5b035b0-2bee-44e1-aea3-38da02ee9dc2.png)

introduced by #7208 possibly.

**Comment by Wedge009** [comment]
@doofus-01 Confirmed.

A quick scan of units, Grand Knight seems to be the only one affected.

**Comment by Wedge009** [comment]
Is it because #7208 changes the Grand Knight's image dimensions from 81x90 to 128x128?

**Comment by knyghtmare** [comment]
> Is it because #7208 changes the Grand Knight's image dimensions from 81x90 to 128x128?

Can you check the gamemap and see how far the HP and XP bar move from it?

**Comment by Wedge009** [comment]
Yeah, it doesn't look right:
![image](https://user-images.githubusercontent.com/13679322/210210283-54e88415-0111-4226-aa63-8af5a77f16dd.png)

**Comment by Wedge009** [comment]
https://github.com/wesnoth/wesnoth/blob/4a5d1932c7c07c23e3792ba1abe3b7cb7adcc030/data/core/units/humans/Horse_Grand_Knight.cfg#L7
I changed this to `~CROP(28,28,72,72)` and it seems to resolve the reported issue of the image not fitting.

![image](https://user-images.githubusercontent.com/13679322/210211572-e70bf732-7359-4cd1-a87f-ab18802a2b47.png)

I'm not sure if you want the HP/XP bars to be aligned to better match the previous presentation, though, and I'm not sure how to do that anyway.

**Comment by Pentarctagon** [comment]
Is the issue just that a bunch of transparent pixels were added to increase the image's dimensions?

**Comment by knyghtmare** [comment]
> Is the issue just that a bunch of transparent pixels were added to increase the image's dimensions?

the canvas size is simply too big now. The previous dimensions were fine

**Comment by Wedge009** [comment]
It's not clear to me if the larger dimensions from #7208 are intentional or not, @doofus-01 has yet to respond. The work-around I put above will crop the image but then it appears that the large dimensions will still cause the HP/XP bars to display further away from the unit.

**Comment by Pentarctagon** [comment]
If nothing else is said about it prior to the 1.18 betas starting, I'd say to just crop the sprite to remove the extra transparent pixels.

**Comment by Wedge009** [comment]
As highlighted by @Konrad22, another symptom of the additional padding is in the Grand Knight's use as a campaign difficulty icon. Without the completion laurel it's not as obvious, but the problem becomes apparent when it's there:
https://cdn.discordapp.com/attachments/259976436490829825/1088206414842966156/image.png

**Comment by Pentarctagon** [comment]
@doofus-01 would you be able to look into this?
