### ISSUE TITLE
[HttT] Achievements List (LK picked)

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7258]
# Heir to the Throne

Achievements List

Titles and Descriptions WIP. This is just listing the possible ones we can get.

1. S1: Defeated 2 enemy leaders (I know it's not possible to nab all three, but you can do 2 actually.)
  
2. S2: Defeated enemy leader (you are asked to resist, not defeat him, so easy achievement)
  
3. S2: Unlock Simran (a loyal knight attained if and only if the enemy leader is beaten on Challenging) [HIDDEN]
  
4. S3: Get Elrian. (you can technically skip him by not capturing that village...)
  
5. S4: Defeated both enemy leaders
6. S4: Beat up that Fool Sea Orc
  
7. S4: Free all the merfolk! (there's one faraway cage that players can skip, but yeah we throw an achievement there)
  
8. S5A: defeated Muff Malal (you can skip him, but you can also wreck him)
  
9. S5B: unlock that cool-White Mage dude (defeated all enemy leaders). You normally resist them but yeah [HIDDEN]
  
10. S6: Asked Theives to flank the rear of the orcs
  
11. S6: Asked Theives to help infiltrate Elensefar
  
12. S6: Liberator of Elensefar
  
13. S7: defeated both enemy leaders. I know this is joke achievement but I think players will feel good if they get one.
  
14. S8: Met your Mirror. (Defeat the Heiress to the Throne) actually, I might be spoilering the campaign with that achievement name..so will re-edit title.
  
15. S9: Purged the Undead (Really hard achievement actually) [HIDDEN]
  
16. S10: Rescued Gryphon Eggs
  
17. S10: Did Nothing to Gryphon (HIDDEN). I am sure you all know why this is a Hidden one. This is very hard to attain. Title can be "Pacifist Towards Avian-kind" or sth.
  
18. S11: defeated Orc leader. Normally, you win as soon as Konrad steps on a Gg hex on other side of river, so you dont normally know of this one [HIDDEN]

19. S11: Terror to the Seas (Purged the attacking sea monsters) (HIDDEN)

20. S11: Hey, Princess (Defeated Li'sar) at her Ford (HIDDEN). Not sure if this is possible.
  
21. S13: Liberator of Dwarven Doors. (Defeat all Orcs)
  
22. S13: Got Uncle Smr...(I forgot his name but Reglok's Uncle) [HIDDEN]
  
23. S13: Cuttle Fish annihilator (slay the Cuttlefish near Thundain's Keep) [HIDDEN]
  
24. S14: Got the treasure chest [HIDDEN]
  
25. S15: Dwarven Guardsman unlocked [HIDDEN]. Allied leader dies quick fast if an unaided so this achievement is good to have.
  
26. S15: Berserker (HIDDEN)
  
27. S17: Recall a Merfolk (special easter egg dialogue) (HIDDEN)
  
28. S17: Heir to the Throne (Konrad gets Scepter)
  
29. S17: Heiress to the Throne (Lisar gets Scepter)
  
30. S17: Elder Knowledge
  
31. S18: Took Hidden Path (19C) [HIDDEN]
  
32. S19A: Got flaming sword
  
33. S19B: Got void armour
  
34. S19C: Defeated Drake Armageddon (HIDDEN)
  
35. S19C: Rescued Warven (HIDDEN)
  
36. S20B: Got Wose Book [HIDDEN]
  
37. S22: Gryphons arrive to aid you. (HIDDEN). This is...the biggest easter egg of HttT and we should give a hidden achievement tied to it.
  
38. S23: Sir Alric of the Plains
  
39. S23: Sir Ruga of the Plains
  
40. S23: Sir Daryn of the Plains
  
41. S23: Lord Bayar of the Plains
  
42. S23: Conquerer of the Plains (HIDDEN)
  
43. S24: HttT Done
  
44. S24: killed Queen with Konrad (HIDDEN)
  
45. S24: killed Queen with Delfador (HIDDEN)
  
46. S24: killed Queen with Li-Sar (HIDDEN)
  
47. S24: HttT Done (Challenging). You earn a gold laurel, but I add something extra.

**Comment by knyghtmare** [comment]
@stevecotton @CelticMinstrel I think the flagship campaign should come with the full set so I listed as many as I could think of. there could possibly be more but I think `2*campaign_length` is good enough.

**Comment by kabachuha** [comment]
16. Did Nothing to Gryphon — I suggest "Leave the Bird Alone" (Konrad looks quite like Elon Musk, and that would be funny in the current situation)

**Comment by cooljeanius** [comment]
>     17. S11: defeated Orc leader. Normally, you win as soon as Konrad steps on a Gg hex on other side of river, so you dont normally know of this one [HIDDEN]

Additional ones for this scenario:
- Win after ignoring the warnings not to attack Li'sar
- Defeat the sea monsters

>     19. S13: Got Uncle Smr...(I forgot his name but Reglok's Uncle) [HIDDEN]

"Uncle Somf"

>     27. S17: Elder Knowledge

What does this one mean? Something about Delfador concentrating?

**Comment by knyghtmare** [comment]
> Win after ignoring the warnings not to attack Li'sar
> Defeat the sea monsters

Added them in. How come sea monsters come so far inland? Explain that...XD

> What does this one mean? Something about Delfador concentrating?

Yes and there's another reference with it too.

**Comment by cooljeanius** [comment]
>     19. S11: Hey, Princess (Defeated Li'sar) at her Ford (HIDDEN). Not sure if this is possible.

I was actually just thinking of triggering a few of the "more guards" events rather than fully defeating her... there are 4 "more guards" events; maybe just triggering 3 of them would be enough?

**Comment by knyghtmare** [comment]
> I was actually just thinking of triggering a few of the "more guards" events rather than fully defeating her... there are 4 "more guards" events; maybe just triggering 3 of them would be enough?

I know how hard the achievement must be so I think we leave it around for now but remove if it actually is too hard

**Comment by CelticMinstrel** [comment]
> I know how hard the achievement must be so I think we leave it around for now but remove if it actually is too hard

I think if it's something that's possible then we might as well keep it, but if it's too hard we can add an extra "halfway" achievement or something like that?

**Comment by knyghtmare** [comment]
> Obtain Great Mage
Obtain Elvish Sylph
Obtain a Grand Marshal (Warven) [HIDDEN] (Requested by Konrad2, so I will add it in for the grandest of Wesnoth players)
Obtain Grand Knight (why? Cause it's fav loyalist unit)
Commander of the Rebellion
Lord of the Rebellion
Battle Princess of Wesnoth
Legend of Wesmere


Moved to part 2 with some others

**Comment by cooljeanius** [comment]
Is it still possible to get these in for 1.18, or would that violate the string freeze? I think HttT having achievements would be a pretty important showcase for the new achievements feature...

**Comment by knyghtmare** [comment]
> Is it still possible to get these in for 1.18, or would that violate the string freeze? I think HttT having achievements would be a pretty important showcase for the new achievements feature...

Nobody helps me so it has to be only me doing it so 1.19 it is

**Comment by cooljeanius** [comment]
> > Is it still possible to get these in for 1.18, or would that violate the string freeze? I think HttT having achievements would be a pretty important showcase for the new achievements feature...
> 
> Nobody helps me so it has to be only me doing it so 1.19 it is

Sorry about that... I thought I'd given the linked PR (#7304) a look, but after re-checking, it looks like I didn't actually, so I guess I should do that...
