### ISSUE TITLE
Flatpak screenshots are still from 1.14

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7260]
The screenshots displayed on our [Flathub page](https://flathub.org/apps/details/org.wesnoth.Wesnoth) are from 1.14. I think it's low priority, because there are only small differences such as still showing a "Tutorial" button on the title screen.

These screenshots are (probably) configured in https://github.com/wesnoth/wesnoth/blob/9f780903abfa592752cb02c767a4ef5992f6f9c7/packaging/org.wesnoth.Wesnoth.appdata.xml#L65-L81

**Comment by soliton-** [comment]
@loonycyborg ^

**Comment by loonycyborg** [comment]
This should come in effect on next 1.16 update.

**Comment by Pentarctagon** [comment]
Does this need to be forward-ported to master?

**Comment by stevecotton** [comment]
It's been forwarded-ported to master in 91d4543a3b4edf37653cb6fb459ca20e94be086c (which will use the 1.16 screenshots for 1.17), although we should add a reminder somewhere to update that again once 1.18 releases.

@Pentarctagon please would you add that to the locked 1.17 Roadmap page on the wiki, and then close this?
