### ISSUE TITLE
game_config schema: the schema has keys for orb colors, but not the toggles

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7261]
### Game and System Information

- **Version:** 1.17.11+dev
- **Downloaded from:** built from source
- **Build info:** current master, with or without PR #7189

### Description of the bug

The validation in data/schema/core/config.cfg is aware of the `*_orb_color` preferences, and the `orb` and `orb_two_color` filenames, but it doesn't have entries for the 6 (+1 in PR #7189) settings below. Should it have?

```
//
// Orb display flags
//
bool show_ally_orb;
bool show_disengaged_orb;
bool show_enemy_orb;
bool show_moved_orb;
bool show_partial_orb;
bool show_status_on_ally_orb;
bool show_unmoved_orb;
```

**Comment by Pentarctagon** [comment]
Is there any reason to not have it?

**Comment by stevecotton** [comment]
I think it should probably be added, but thought I'd open the issue to see if anyone else knows of a reason not to.

Planning to get #7189 merged first, unless we decide that this should be included directly in that PR. I'm 50/50 on adding it to the PR anyway.

**Comment by stevecotton** [comment]
Ah, there are a couple of things to resolve first:

* `disengaged_orb_color` is a left-over from an older concept for #5523.
* `show_partly_orb` vs `show_partial_orb` (explanation below)

The game will read defaults from `game_config.cfg` if present, but will fall back to hardcoded defaults. The colors have been in `game_config.cfg` since 1e5d58af6a5143f37cd1768f4967bac5b075ccaa, but the booleans to enable and disable orbs haven't, it's always fallen back to the values in the C++.

Both the colors and the enabling/disabling have a corresponding key in the preferences file. For all except one, the names match up; even the `partial_orb_color`. However, the key in `game_config.cfg` for enabling/disabling that orb is `show_partly_orb`.

Looks like some trivial cleanup, but I'm in two minds about backporting the cleanup afterwards. I still intend to backport #7189 which adds a `show_status_on_ally_orb` to the `game_config.cfg`, so there's some logic to reconcile about whether it's right to backport or not. On that question, #7189 gets a bonus for being something that 1.16 players are asking for.

**Comment by CelticMinstrel** [comment]
If it's valid in the WML, then that should be encoded in the schema. Although the schema isn't a perfectly-accurate representation of what's permitted, and perhaps may never be 100% perfect, the goal should be to get it as close as possible.

**Comment by stevecotton** [comment]
The fix is currently in my `orb_cleanup` branch - I'll open the PR once #7189 is merged. Doing it in that order clears #7189 to be backported without getting entangled with this, so this can stay 1.17-only.

**Comment by cooljeanius** [comment]
> The fix is currently in my `orb_cleanup` branch - I'll open the PR once #7189 is merged. Doing it in that order clears #7189 to be backported without getting entangled with this, so this can stay 1.17-only.

ok, #7189 is merged now
