### ISSUE TITLE
Commanders in World Conquest work improperly

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#7264]
### Game and System Information

- **Version:** tested with 1.16.\*, I think 1.17.\* also affected

### Description of the bug

Commanders are supposed to become recruiting leaders if the current leader of the player's side dies. They become, but in the next scenario the player has Peasant as the leader of his side, which is clearly not supposed to be

### Steps to reproduce the behavior

1. Take a commander as a bonus in the start of a scenario
2. Get your current leader killed. The commander becomes a new leader
3. Proceed to the next scenario. The commander can still recruit but your leader is a peasant. Death of the peasant means defeat

### Expected behavior

The commander is your only leader

**Comment by knyghtmare** [comment]
Confirmed in 1.16.6 MacOS. So, 1.17.x presumably has it
