### ISSUE TITLE
Add leader type to Multiplayer Activity Report

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#7267]
### Describe the desired feature

Currently RPG maps set faction of side to Custom to be sure recruit list is empty, but that means report does not have faction information anymore.

Possible solution is additionally saving leader faction, maybe leader unit type too.

**Comment by Pentarctagon** [comment]
What would be a good example of a situation where this is happening?

**Comment by ProditorMagnus** [comment]
I believe creep war was one example which used Custom.

**Comment by Pentarctagon** [comment]
It doesn't look like creep wars does this - the faction is recorded the actual faction chosen, not Custom.

**Comment by Pentarctagon** [comment]
@inferno8 as well, if you have any suggestions.

**Comment by knyghtmare** [comment]
> What would be a good example of a situation where this is happening?

A New Land in Core MP Maps. The factions for all 4 human sides are set to Custom to force recruit list to "Peasant, Mage".
Also, it's not `faction="Custom"` on the file code, it's there as a default.

**Comment by Pentarctagon** [comment]
It looks like leader selection updates are handled through https://github.com/wesnoth/wesnoth/blob/master/src/server/wesnothd/server.cpp#L1781

So leader types chosen that way can be found by adding something like:
```
if(const simple_wml::node* a = scenario_diff->child("change_child")) {
	if(const simple_wml::node* b = a->child("scenario")) {
		if(const simple_wml::node* c = b->child("change_child")) {
			if(const simple_wml::node* d = c->child("side")) {
				if(const simple_wml::node* e = d->child("insert")) {
					PLAIN_LOG << e->attr("type");
				}
			}
		}
	}
}
```

I don't see any good way for the server to know the leader type if it's specified in the scenario cfg though.

**Comment by soliton-** [comment]
Note that if the faction is `Custom` then that is the faction. There is really nothing more to it. You can check the unit type of the leader but that is not related to the faction of the side. (Though you might be able to guess the faction from the unit type.)

What is the goal?

**Comment by ProditorMagnus** [comment]
EoMa leader types are not shared between factions, so unit uniquely identifies faction.

**Comment by soliton-** [comment]
So there are scenarios that specify faction Custom but then the leader is selected from another faction from the current era? And the goal is to guess that other faction from the leader type?

**Comment by Pentarctagon** [comment]
As a more general data point, it would also be possible to see how frequently different leaders are chosen.

**Comment by ProditorMagnus** [comment]
Custom is the value you need to disable recruitment. Then entire faction is leader.

**Comment by knyghtmare** [comment]
> As a more general data point, it would also be possible to see how frequently different leaders are chosen.

It can exhibit statistics which leaders are over-used and which ones are not even picked. This will help discerning if certain leaders are..."in need of tweaking". Not really my department but it till help the relevant staff.
