### ISSUE TITLE
[UI] Addon list box container does not resize to fit filtered addons

### ISSUE THREAD

**Issue by Kingofd** [wesnoth/wesnoth#7270]
### Game and System Information

- **Version: 1.17.10**
- **Downloaded from: Github**
- **Build info:**
- **OS: Manjaro Linux x86_64**

### Description of the bug

When filtering addons with the filter options the size of the GUI is not always updated to show all the newly filtered addons. This results in addons that are not shown in the addon list, since they are cut off there.

I used the resolution 1920x1080.

### Steps to reproduce the behavior

1. Start Add-ons Manager (version 16 (add-ons.wesnoth.org:15016))
2. Select language filter option: "Afrikaans"
3. Then, select language filter option "Bahasa Indonesia"
4. "An Orcish Incursion" is now cut off in the addon filter list

### Expected behavior

Any and all addons that are matching the filter arguments should be shown in the list

### Additional context
It is sometimes accompanied by the following error msg:

`20230110 17:27:22 error gui/layout: grid [] place: Failed to place a grid, we have (1015,59) space but we need (4653,62) space. This happened at a grid with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui25panelE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui27dialogs13addon_managerE' with the id 'addon_manager'.`

Only Afrikaans is selected.
![AddonListFilterErr](https://user-images.githubusercontent.com/26515148/212097791-bbb89db8-7505-4b1c-941e-b39175b2117b.jpeg)

After also selecting Bahasa Indonesia, "An Orcish Incursion" should still be shown on the list, and indeed is still on the list and can be selected (when navigating with the arrow keys), but it is not.
![AddonListFilterErr2](https://user-images.githubusercontent.com/26515148/212097798-8031b834-b264-454c-94e1-2396985356ea.jpeg)

**Comment by Wedge009** [comment]
Not sure what is meant by 'Add-ons Manager (version 16)'. But I could not replicate this in Linux, master @ e7e6649377b. An image demonstrating the issue might be helpful. Perhaps also the resolution you have Wesnoth set to, since the add-ons manager has different layouts depending on overall window size.

It wouldn't surprise me if this is a genuine problem - there are a few UI-related issues reported for Add-ons and similar dialogues.

**Comment by Kingofd** [comment]
Sure, I've updated the comment and added pictures, the resolution is 1920x1080.

**Comment by Wedge009** [comment]
A few things:
* I didn't know that connecting on port 15016 gives the add-ons for 1.16.
* The ordering is important to get this precise symptom - in this case, author descending.
* Selecting languages in the opposite order - Bahasa Indonesia first, then Afrikaans second - does not replicate the issue. So clearly something odd is going on with the filtering.

**Comment by Pentarctagon** [comment]
A simple way to reproduce this with current master:
* Choose Deutsch for the language
* For tags, click Terraforming then Difficulty

The add-on Merry Christmas isn't visible on the list but can be selected via the arrow keys:
![Screenshot from 2024-02-02 23-12-33](https://github.com/wesnoth/wesnoth/assets/3030250/2cab18fe-602d-43d6-89ab-e6ce37172109)

**Comment by Wedge009** [comment]
On UHD screen, I have no such issue with 1.16.11 (with 1.16 add-on list), but 1.17.25+dev @ 30139da16c3 (with 1.17 add-ons) I can replicate the issue as just described. For non-German speakers as myself the appropriate tag appears to be Schwierigkeitsgrad (difficulty level).

Looks like Pent has already prepared a work-around/solution so I won't bother to find what broke this.

**Comment by gfgtdf** [comment]
I can reproduce this, but even though they are not drawn, i can click on them (in the black area) to make them appear.
