### ISSUE TITLE
SotBE S14 Grüu dissapeared

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7280]
### Game and System Information

1.17.11

### Description of the bug

Grüu must be present, and he is mentioned, but he does not answer because he is not there. Looking in the code, he does indeed have several sentences and then he disappears when the conversations end. But he is already missing from the start. According to the code, Grüu is initially defined as the leader of **Side 4** and is killed with **[kill]** in a **prestart event**. Then in a **start event** he is recalled with **[recall]** but being dead he doesn't return. I don't understand the reason for that logic, but at least I understand that this is what is happening that prevents the appearance of Grüu.
![imagen](https://user-images.githubusercontent.com/40789364/212312574-6da29c28-912c-4faa-b41b-3daed243040f.png)

### Steps to reproduce the behavior

1. Start SotBE S14
2. Where is Grüu?

### Expected behavior

Grüu present on the starting castle, talking, and **THEN** dissapears.

**Comment by knyghtmare** [comment]
> According to the code, Grüu is initially defined as the leader of Side 4 and is killed with [kill] in a prestart event. Then in a start event he is recalled with [recall] but being dead he doesn't return. I don't understand the reason for that logic, but at least I understand that this is what is happening that prevents the appearance of Grüu

Something has definitely bugged out...

**Comment by cooljeanius** [comment]
related to #5983?

**Comment by cooljeanius** [comment]
> No, because the troll wipe is already fixed.

When did that happen?

**Comment by Toranks** [comment]
I didn't say it, they say it in the thread itself. The error is 1.15, not 1.16 or 1.17. I don't know why it happen in 1.15, but the code correctly changes all trolls to side 1 when all enemies are defeated.

**Comment by cooljeanius** [comment]
> I didn't say it, they say it in the thread itself. The error is 1.15, not 1.16 or 1.17. I don't know why it happen in 1.15, but the code correctly changes all trolls to side 1 when all enemies are defeated.

ok well I closed it now

**Comment by CelticMinstrel** [comment]
> According to the code, Grüu is initially defined as the leader of **Side 4** and is killed with **[kill]** in a **prestart event**. Then in a **start event** he is recalled with **[recall]** but being dead he doesn't return.

Sounds like those should have been `[store_unit]` and `[unstore_unit]` respectively?

**Comment by Toranks** [comment]
> > According to the code, Grüu is initially defined as the leader of **Side 4** and is killed with **[kill]** in a **prestart event**. Then in a **start event** he is recalled with **[recall]** but being dead he doesn't return.
> 
> Sounds like those should have been `[store_unit]` and `[unstore_unit]` respectively?

Yes, that already does it. Right when the conversation ends it is stored and then when it appears on turn 7 it is unstored. At the beginning of the scenario it is not necessary, since he only participates in the conversation.

**Comment by stevecotton** [comment]
Fixed for 1.17 in #7282. Looks like it should be backported - @Toranks, should it?

**Comment by Toranks** [comment]
> Fixed for 1.17 in #7282. Looks like it should be backported - @Toranks, should it?

They have the exact same code, so I'm assuming so.

**Comment by stevecotton** [comment]
Backport is in #7397.
