### ISSUE TITLE
[Help Menu] Race/unit description clipped off by scroll bar, unable to be read

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7300]
### Game and System Information

- **Version:** 1.17.12+dev (latest commit)
- **Downloaded from:**  Github
- **Build info:** Mys2 Windows 10
- **OS:** Windows 10

### Description of the bug

![image](https://user-images.githubusercontent.com/5283677/213861930-168bac39-f9be-4d1e-a6ac-eb103224a4c7.png)

Part of the race/unit description is not readable due to the scrollbar

### Steps to reproduce the behavior

Open client
Access help menu
Read elf description, on the rightmost part

### Expected behavior

Texts isn't placed behind the scrollbar

**Comment by Pentarctagon** [comment]
Does this still happen for you? I can't reproduce this.

**Comment by knyghtmare** [comment]
> Does this still happen for you? I can't reproduce this.

Not anymore, but got something new:

![image](https://github.com/wesnoth/wesnoth/assets/5283677/e8e87edd-b9d9-4e00-8033-d800301ae157)
