### ISSUE TITLE
[HttT] [Units] Injured Sergeant appearance

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7311]
### Game Information
Wesnoth 1.17.12+dev
Github Download
Windows 10 (Msys2 compiler)

### Bug Description
The Injured Sergeant unit looks strange now that Lieutenant unit was updated. (See Screenshot)
![image](https://user-images.githubusercontent.com/5283677/213984465-2d8004e7-7f32-490c-98c0-f2bd97a0eba0.png)

### Expected Behavior
Appearance should be further animation frame where it shows him lying near dead on the ground and not his helmet levitating

**Comment by Wedge009** [comment]
Oh, I see. The lieutenant sprites for 1.17 were updated in #6803, hence the change. For both 1.16 and 1.17 versions frame 9 (used in #7312) works because it's the last frame of the animation anyway.
