### ISSUE TITLE
WML variables in pl_PL strings that don't match the msgid

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7318]
Game information:
* Wesnoth 1.16.8

The tool in wesnoth/wesnoth#4436 searches for WML variables in translated strings, and checks whether they match the variables in the msgid. It found these issues in the Polish translation for 1.16.8, all relating to `po/wesnoth-multiplayer/pl.po`'s comparison dialog:

`msgid "<span strikethrough='true' foreground='$side_color'>Side $side_number</span>:  Has lost all units"`: `$side_number` has been translated, and `$side_color` should now be a WML-style variable instead of using printf-style `%02x`

`msgid "<span foreground='$side_color'>Side $side_number</span> has the advantage."`: '$side_color' should now be a WML-style variable instead of `%s`

`msgid 'Sides $side_number and $other_side_number are tied.'`: both of those variable names need correction

**Comment by cooljeanius** [comment]
@Hejnewar do you know if ForPeace is on GitHub?

**Comment by MrTitainin** [comment]
ForPeace has been inactive for a while. We might replace him when someone competent comes out. I've fixed variables (and the text as well while at it) and sent to Ivanovic. Please run the script again to make sure it's resolved after it's merged.

**Comment by stevecotton** [comment]
> Please run the script again to make sure it's resolved after it's merged.

There's still corrections left to do for `msgid "<span strikethrough='true' foreground='$side_color'>Side $side_number</span>:  Has lost all units"`. `#side_color` should have a `$` instead of `#`, and `$side_numer` needs to be `$side_number`.

**Comment by MrTitainin** [comment]
Both have been fixed and are already merged into master branch.

**Comment by stevecotton** [comment]
Checked, and confirmed that it's fixed.
