### ISSUE TITLE
Byte Complier Warnings for wesnoth-mode on GNU Emacs 27.1

### ISSUE THREAD

**Issue by Dyrcona** [wesnoth/wesnoth#7337]
### Game and System Information

- **Version:** Master
- **Downloaded from:** Github
- **Build info:** GNU Emacs 27.1
- **OS:** Ubuntu 22.04

### Description of the bug

When byte-compiling wesnoth-mode with Emacs 27.1, the following warnings are produced:

In wesnoth-jump-to-matching:
wesnoth-mode.el:1144:14:Warning: ‘interactive-p’ is an obsolete function (as
    of 23.2); use ‘called-interactively-p’ instead.

In wesnoth-check-element-type:
wesnoth-mode.el:1351:39:Warning: (lambda (x) ...) quoted with ' rather than
    with #'
wesnoth-mode.el:1352:30:Warning: (lambda (y) ...) quoted with ' rather than
    with #'

In wesnoth-check-wml:
wesnoth-mode.el:1756:10:Warning: ‘toggle-read-only’ is an obsolete function
    (as of 24.3); use ‘read-only-mode’ instead.

### Steps to reproduce the behavior

1. cd data/tool/emacs_mode
2. make

### Expected behavior

Instead of getting warnings about obsolete functions, the output should contain no warnings.

**Comment by CelticMinstrel** [comment]
Just noting that that commit was #7338.
