### ISSUE TITLE
A dedicated event that fires on any unit rebuild

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7353]
### Describe the desired feature

Some addons have problems when managing certain characteristics of the units because when commands like modify_unit, object, remove_object, unstore_unit, transform_unit, etc... are applied, some modifications, status or other values are lost or reset.
To help addons cover a wider range of possibilities, it would be very useful to have an event with filter that fires right after any of these commands, to perform a new check on the unit to make sure it preserves the modifications made due to modifications, addons, eras, campaigns, etc.

For example:
```
[event]
    name=unit_rebuild
    [filter]
    [/filter]
    [filter_condition]
    [/filter_condition]
```

**Comment by ProditorMagnus** [comment]
This is probably not possible to implement in a way which would help you.

**Comment by gfgtdf** [comment]
One of the main reasons why we don't have this is that the most common way to change units in wml is still [unstore_unit],  which would by itself rebuild the unit again, leading to either infinite recursion or or to very complicated code.

**Comment by Toranks** [comment]
Can I close this "as not planned"?

**Comment by gfgtdf** [comment]
sure
