### ISSUE TITLE
Unit idle animation frequency slider doesn't seem to work properly

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#7373]
There's no way to see what the current value is, and after closing and reopening the preferences, the value changes. It seems like a mismatch between how the value is "loaded" and how it is "stored", because just opening and closing preferences changes the value stored in the file (unless it's at the default value of 1).

I also find it confusing with respect to which direction increases the frequency and which direction decreases it.

**Comment by Wedge009** [comment]
I just noticed this seems to have been duplicated by #8613, which has since been resolved. On that basis, I'm closing this but please re-open if this is referring to something else.
