### ISSUE TITLE
wmlxgettext: add option to set style of paths placed in comments

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#7380]
### Describe the desired feature

If two developers are collaborating on an add-on, and one is on a system with Windows-style paths, and the other is on a system with Unix-style paths, and they both want to regenerate the potfile with `wmlxgettext` occasionally, each regeneration will introduce a huge amount of noise due to all the paths in comments in the potfile changing style. It would be nice to have an option to choose just 1 style to avoid this.
(prompted by inferno8/wesnoth-To_Lands_Unknown#11)

**Comment by stevecotton** [comment]
I'd suggest "no option, just force one style".

**Comment by Elvish-Hunter** [comment]
> I'd suggest "no option, just force one style".

And that style should be the Linux/Unix one, because Windows is perfectly capable of understanding it, while the reverse isn't true.

**Comment by CelticMinstrel** [comment]
Does wmlxgettext never, ever an absolute path? I think 59b6049 is technically incorrect and only manages to equal correct because all paths are relative… which might still be good enough though, as long as all paths _really are_ relative.

Otherwise I think pathlib.PurePath would be the answer, though I'm not completely confident on this.

**Comment by CelticMinstrel** [comment]
> Does wmlxgettext never, ever an absolute path? I think [59b6049](https://github.com/wesnoth/wesnoth/commit/59b6049f9fbaebb492069a32022d7a33241a20df) is technically incorrect and only manages to equal correct because all paths are relative (and because we don't support weird exotic OSes like OpenVM or MacOS 9)… which might still be good enough though, as long as all paths _really are_ relative.
> 
> Otherwise I think pathlib.PurePath would be the answer, though I'm not completely confident on this.

**Comment by Elvish-Hunter** [comment]
> Does wmlxgettext never, ever output an absolute path?

It shouldn't output absolute paths: the command line allows specifying a starting path (which defaults to the current working directory) and the `pywmlx.autof.autoscan` function looks for all interesting files inside of it (internally it uses `os.walk`), so all paths are relative to the starting directory (and are then normalized to the format used by the OS in the main script). Granted, there's the case where the `--recursive` flag isn't used and wmlxgettext has to parse only the files stated in the command line arguments, but that's a different issue and might require more testing.
Besides, using absolute paths might expose the directory structure of the user running the script, and we certainly don't want this: it'd be both a privacy issue and a bug (I remember finding some disasters made with the old trackplacer script, but I'm not sure if the damaged files were haphazardly modified by clueless users...).

> we don't support weird exotic OSes like OpenVM or MacOS 9

Supporting these would be another can of worms: the official Python releases don't support them either, so in theory we'd have to make our own libraries. I remember that, at some point, `os.path` used to support the MacOS classic separator (`:`), but this is no longer the case; `os.path` is internally composed of `os.ntpath` and `os.posixpath`, so it supports only Unix-based and Windows operating systems.

> Otherwise I think pathlib.PurePath would be the answer, though I'm not completely confident on this.

I have to admit that `pathlib` is a nice library and for new projects it's better than `os.path`, however it suffers from the same issues: internally it supports Unix (as `PurePosixPath` or `PosixPath`) or Windows (as `PureWindowsPath` or `WindowsPath`), so it won't solve the problem on non-Windows and non-Unix systems. Being so recent, it has never supported MacOS 9 either.
What I can actually do, in the same `autof.py` file I modified, is add a check that raises an error and exits if the value reported by `os.name` is neither `posix` or `nt` (which is in theory possible: the documentation says that it can also return `java`).

**Comment by CelticMinstrel** [comment]
Sounds like the issue I came up is basically imaginary. I just wanted to be sure.
