### ISSUE TITLE
Merge Treehouse villages from UMC Terrain Pack into mainline

### ISSUE THREAD

**Issue by ForestDragon-wesnoth** [wesnoth/wesnoth#7385]
### Describe the desired feature

Was scrolling through the UMC Terrain Pack, and noticed these extremely beautiful treehouse villages, in my opinion the best terrain in the entire add-on. I believe these villages deserve to be mainlined, as their quality and amount of variations is more than enough to be on par with existing village terrain. Plus it would make designing elf maps a lot more interesting, instead of having to use the same old elf villages that veteran players already seen hundreds of times.

![image](https://user-images.githubusercontent.com/34136200/219360570-22f72110-53b0-4e31-a44c-0d8904a040dd.png)

**Comment by knyghtmare** [comment]
I can pull request these in as early as tonight.
