### ISSUE TITLE
Improve UtBS gameplay experience

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#7391]
### Describe the desired feature

Long story short, during my talk with Yumi we came to the conclusion that it would be good to experiment a bit and in my opinion it is possibly the best time for that as the units were changed pretty drastically.

Proposed changes:
Difficulty XP modifier - basically on every difficulty units have their own xp modifier that increases the experience needed to level up, this is purely difficulty modifier.
 
Recall cost based on unit cost (can also be based on difficulty) - this solves one of my biggest problems with current wesnoth high levels, to play optimally you should only get the best of them because then all cost 20g anyway. Another problem is lack of scale depth, big units do more or less as well as small units and their power is not at all shown to be different, which in many cases isn't bad but here we have the tauroch problem. Aka. Big unit that should be better than small units but can't be because it would dominate everything. It also allows for more interesting and less limited strategies (mostly more spammy ones).

In addition both of those can generate quite a bit of content in the form of for example challenge campaigns where players intentionally set them to very high levels.

The reason behind this FR is gathering opinions and ideas from the community.

**Comment by Toranks** [comment]
This may help, for reference.
(Note that it overrides any custom recall costs the units might have)

https://github.com/Toranks/Advance_Wesnoth_Wars/commit/450c7bcfe02d9089f321707104e519197a0d2522#diff-faff7527bcabf3220903ef689f3744eff5c09b16e6b391ed59d3422be9e8c49bL1

**Comment by knyghtmare** [comment]
> Difficulty XP modifier - basically on every difficulty units have their own xp modifier that increases the experience needed to level up, this is purely difficulty modifier.

Why not just the `experience_modifier={ON_DIFFICULTY 100 150 200}` for each scenario of the campaign? Seems better than modifying each unit file.

> Recall cost based on unit cost (can also be based on difficulty)

Cannot comment on it until I have sampled some scenarios with this logic in placement.

**Comment by CelticMinstrel** [comment]
I agree that experience modifiers should be handled at the scenario level.

**Comment by Hejnewar** [comment]
> Why not just the experience_modifier={ON_DIFFICULTY 100 150 200} for each scenario of the campaign? Seems better than modifying each unit file.

Well we aren't doing that and I don't know how you came to this conclusion, actually it would probably be best if that was handled on the campaign level not even the scenario level. Same with recall costs.

**Comment by CelticMinstrel** [comment]
> actually it would probably be best if that was handled on the campaign level not even the scenario level.

Hmm, yeah, supporting some of these scenario keys in the campaign might be a nice idea…
