### ISSUE TITLE
UtBS S05: Difficulty is highly dependent on where Kaleh is when the main cavern event triggers

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7394]
### Game and System Information

- **Version:** 1.15.1+dev (but I've checked the scenario and this would still apply to 1.17.13+dev)

### Description of the bug

The difficulty in S05 is heavily influenced by how long it takes Kaleh to reach the keep after the main cavern is opened. That timing depends on whether Kaleh was (or was near) the explorer who triggered the moveto event, and how many movement points Kaleh has remaining at the time. Having someone scout forwards makes the scenario much harder; not impossibly harder, but "ohh, this must be intended to be an unusually hard scenario" harder.

A possible solution (particularly for players who are used to the tailwind ability) would be a narrator dialogue, "We assume all the Quenoth elves moved to the cavern mouth during that discussion. For this turn only, they have extra movement points so that you can move them into the cavern." along with extra MP based on how far away they were.

Originally reported, with replays, at https://r.wesnoth.org/p647258 . Just realised that I never logged an issue for it, so I'm logging it now as the Quenoth rework will mean a major retest of the balance.

**Comment by knyghtmare** [comment]
> The difficulty in S05 is heavily influenced by how long it takes Kaleh to reach the keep after the main cavern is opened. That timing depends on whether Kaleh was (or was near) the explorer who triggered the moveto event, and how many movement points Kaleh has remaining at the time. Having someone scout forwards makes the scenario much harder; not impossibly harder, but "ohh, this must be intended to be an unusually hard scenario" harder.

I think I remember just timing Kaleh's movement to ensure he is the one who triggers it, but foreknowledge is not a given for first time players. Thus, I think the event can be readjusted by a timer. As in, event triggers 1-2 turns later and not immediately, giving the player a chance to nab the keep.

Or, placing some hint in objectives with "Find a keep as soon as possible"

**Comment by stevecotton** [comment]
What would the player do during those extra turns though? If it's just "move east and end turn" then it would be better to do the one-off extra movement, IMO.
