### ISSUE TITLE
In PblWML's `version` attribute, should the third digit be mandatory?

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7396]
Version 1.17.13 added schema validation of the `_server.pbl` file. The schema rejects many of the examples from https://wiki.wesnoth.org/PblWML#Version_Key_Examples , because it makes the `.z` part of `x.y.z` mandatory, and all of them must be digits.

The question is, do we change the schema, or decide that the examples are now invalid?

Links to the discussion:
*  Discord `#modding`: https://discord.com/channels/231976805987385345/442775044590927873/1077168267455627315
* IRC (starting at 10:02:08): https://irclogs.wesnoth.org/2023/02/%23wesnoth-umc-dev.2023-02-20.log

**Comment by Pentarctagon** [comment]
Unless there's some sort of issue with supporting the examples, the schema should be changed to allow them.

**Comment by CelticMinstrel** [comment]
Change the schema. It's an error to force the third digit.
