### ISSUE TITLE
Crash on Attack with Planning Mode

### ISSUE THREAD

**Issue by Dyrcona** [wesnoth/wesnoth#7398]
### Game and System Information

- **Version:** 1.17.13
- **Downloaded from:** Built from source
- **Build info:** Commit 113056c9e199cec746f1e7a5c9be001dd55170f4
- cmake -B build; cd build; make; sudo make install (Not sure what you really want for build info)
- **OS:** Ubuntu 22.04

### Description of the bug

With planning mode activated, when I order a unit to attack the game crashes with the following error message:

wesnoth: /home/jason/Src/Wesnoth/wesnoth/src/whiteboard/attack.cpp:164: virtual void wb::attack::apply_temp_modifier(unit_map&): Assertion `unit.attacks_left() > attack_count_' failed.

### Steps to reproduce the behavior

1. Activate planning mode while playing
2. Order a unit to attack
3. Immediate crash on clicking the attack button

### Expected behavior

Expected behavior is for the attack to be queued and to happen when the queued actions are executed.

### Additional context

I can rebuild with debug options and produce a stack trace if you need it.

**Comment by Toranks** [comment]
I can confirm:
![imagen](https://user-images.githubusercontent.com/40789364/220183360-4f3b0f6b-81c4-4c21-8837-7ce1e1bab208.png)

**Comment by CelticMinstrel** [comment]
Hmm… could this be related to cbbd34a79e865f1d00edc9e5895809f1d0960bd3?

**Comment by Pentarctagon** [comment]
It should be easy to bisect, if so.

**Comment by Dyrcona** [comment]
I think I have a fix. The assert on line 164 of whiteboard.cpp should probably be >= rather than >. I made the change locally and it works for me. I can make a pull request unless you think a real fix is more complicated than that.

**Comment by Pentarctagon** [comment]
Actually I guess a bisect isn't needed - that assert was actually added in the commit CelticMinstrel linked.

**Comment by CelticMinstrel** [comment]
> Actually I guess a bisect isn't needed - that assert was in fact added in the commit CelticMinstrel linked.

This is incorrect. I didn't add that assert. I did edit it, however.
