### ISSUE TITLE
[object] [effect] [filter] status= doesn't work

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7400]
### Game and System Information

1.17.13
Windows 7

### Description of the bug

~~Apparently other status like poisoned are correctly detected~~, but this is not the case with uncovered, which prevents creating [effects] based on the uncovered status.
**NEW NOTE: Doesn't work with some non-persistent states, as status, HP, movement points, etc.**

### Steps to reproduce the behavior

Try adding this to any unit and do an attack, the unit never shows the icon.
```
			[modifications]
				[object]
					id=uncovered_icon
					[effect]
						add="misc/loyal-icon.png"
						apply_to=overlay
						[filter]
							status=uncovered
						[/filter]
					[/effect]
				[/object]
			[/modifications]
```

Change that with ~~status=poisoned on a poisoned unit~~ another StandardUnitFilter and see how the icon appears.

### Expected behavior

When the unit becomes uncovered, the icon should update

### Additional context

* status=uncovered as StandardUnitFilter works on [modify_unit] [filter], [event] [filter] and other places, the problem is only inside [effect]

* It is not a new bug. I remember having issues with the uncovered status and using objects in the past, but couldn't reproduce it correctly until now

**NEW NOTE: as said in the comments, this behavior is not expected, therefore I close the issue**

**Comment by Toranks** [comment]
To give uncovered automatically:
uncovered: if 'yes', the unit has performed an action (e.g. attacking) that causes it to no longer be hidden until the next turn.

**Comment by CelticMinstrel** [comment]
Your comparison to poison seems to be incorrect. You're adding the poison overlay modification to a poisoned unit, but you're adding the uncovered overlay modification to a non-uncovered unit, assuming I read your report properly.

If you add the modification after the unit attacks, does the overlay appear?

**Comment by Toranks** [comment]
No, what I said is a way to reproduce it, but the icon changes in real time after a unit that was not previously poisoned is poisoned. Any attack updates the status of this icon, checked with other status, and other different properties, and also with ability_type_active. I've been using this methods for a long time, and I've discovered that status=uncovered is the ONLY thing that doesn't wors, AFAIK.

So no to your first question, the overlay never appears, no matter what I do (attack, move, next turn, giving status manually, etc...). Yes to your second question, with not only poisoned, but many other examples, those mentioned above, other StandardUnitFilters, StandardTerrainFilters, and detection of adjacent enemies, with perfect behaviour since @stevecotton   fixed this crash:
https://github.com/wesnoth/wesnoth/issues/7238

**Comment by CelticMinstrel** [comment]
And generally speaking it is not expected to work. I don't even know what could be making it work, but it might even be a bug that it works for poison.

**Comment by gfgtdf** [comment]
> And this can do a potential OOS?

Like i said, if your effect only changes the overlay, it won't cause OOS. But when you for example have code like
```
[effect]
	apply_to=new_ability
	 .. some ability code
	[filter]
		status=poisoned
	[/filter]
[/effect]
```
The the unit might for example have the object when the object is applied for the first time. And then when the unit loses their poisoned state the unit still has the ability since the unit was not rebuilt (unless you rebuild it manually via wml). Then when the game is reloaded which automaticially rebuilds the unit it might lose the ability. (In reality  this only happens in rather rare cases, but its still possible afaik)

**Comment by CelticMinstrel** [comment]
I think `ability_type_active` and `ability_id_active` should be considered non-persistent, yes. I wouldn't expect them to work reliably on a modification.
