### ISSUE TITLE
Missing images are no longer logged in stderr

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#7403]
Previously, when an image was not found, it was logged to stderr. No longer the case.

This was useful, because one got a list of the not working file paths logged.

Build c9eae7c

**Comment by Wedge009** [comment]
I tested current master and 1.16 branch by renaming `data/core/images/maps/titlescreen.png` (or `.webp`).

In 1.16:
```
20230222 10:46:38 error display: could not open image 'maps/titlescreen.png'
20230222 10:46:38 error gui/draw: Image: 'maps/titlescreen.png' not found and won't be drawn.
```

In master:
```
20230222 10:47:37 error image: could not open image 'maps/titlescreen.webp'
```

So the draw error is no longer logged (maybe from the hardware acceleration overhaul?) but there is still an error logged. In what context do you find there is no logging?

**Comment by Wedge009** [comment]
Confirmed in #wesnoth-dev that missing images are still logged - was just an expectation that logs would be displayed at the terminal, but now they are logged in files by default.
