### ISSUE TITLE
WoF S03 lack of animation when any unit returns to recall list

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7410]
### Game and System Information

All

### Description of the problem

When a unit dies, it is sent to the recall list, but in an abrupt and ugly way. It suddenly disappears right on the last hit.

### Steps to reproduce the behavior

- WoF Scenario 3: The Contention
- Kill any unit

### Expected behavior

Some animation would be nice, I suggest this change just before this line:
https://github.com/wesnoth/wesnoth/blob/7b6027cdec232624a24a04895853684527278e54/data/campaigns/Winds_of_Fate/scenarios/03_The_Contention.cfg#L332
```
		[animate_unit]
			[filter]
				id=$unit.id
			[/filter]
			flag=pre_teleport
			with_bars=no
		[/animate_unit]
```
pre_teleport is the animation that best fits what is happening. Well configured, the movement animation could also work, but it would be a little more complicated to make it look good

**Comment by Wedge009** [comment]
I suggest it's more of an enhancement than a bug. The current state might not look nice (I haven't checked for myself yet), but it doesn't sound like something that would be considered erroneous.

**Comment by Toranks** [comment]
Right, I forgot to use the other tag

**Comment by Toranks** [comment]
> Tested your suggested change and the effect looks good.

I send a PR with the change?

**Comment by Jonathan-Kelly** [comment]
Yeah, send it as a PR so that you get the credit for your work (both with github and the wesnoth project).
