### ISSUE TITLE
Wesnoth Client Not Recognised/Loadable in OBS Studio for YT Streaming

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7417]
![image](https://user-images.githubusercontent.com/5283677/221356858-8b480b7d-1222-4e99-8c77-e260d1d06d03.png)

I have followed the steps as instructed but the client doesn't seem to be recognized by the streaming software so the YT stream appears with only sounds and black screen.

**Comment by Hejnewar** [comment]
I use OBS to record wesnoth. It works fine for me.

**Comment by knyghtmare** [comment]
I meant live streaming...not recording...well, tried that either but no works

**Comment by cooljeanius** [comment]
dup of #5814?

**Comment by knyghtmare** [comment]
How the heck is Discord being associated with OBS and Youtube? Of course, it's not a dup

**Comment by cooljeanius** [comment]
The bug is that Wesnoth doesn't make its video output recognizable as something that can be streamed by various streaming applications; it shouldn't matter which streaming applications those are specifically

**Comment by knyghtmare** [comment]
> The bug is that Wesnoth doesn't make its video output recognizable as something that can be streamed by various streaming applications; it shouldn't matter which streaming applications those are specifically

Then fit it maybe?

**Comment by Hejnewar** [comment]
Works for me on window capture / for you on display capture.

**Comment by ProditorMagnus** [comment]
Works with 1.16.0

**Comment by knyghtmare** [comment]
> for you on display capture.

apparently, Wesnoth is not an app...Oh well...I expected nothing less

**Comment by Toranks** [comment]
All my videos I sent here to show Wesnoth bugs are recorded with OBS on Windows 7 and works fine

**Comment by Toranks** [comment]
![imagen](https://user-images.githubusercontent.com/40789364/221368353-1b6cf312-2c62-4b52-9817-ebecc3e65d30.png)

**Comment by knyghtmare** [comment]
English. Please.
