### ISSUE TITLE
Incorrect version information applied to Windows releases

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#7441]
### Game and System Information

- **Version:** At least 1.16.x and 1.17.x
- **Downloaded from:** sourceforge.net and Steam
- **Build info:** official release builds
- **OS:** Windows

### Description of the bug

1.16.8 release downloaded via Steam:
![image](https://user-images.githubusercontent.com/13679322/223587096-b6894848-7e1e-4c59-bbfa-28f5f58fa235.png)

1.17.13 release downloaded from sourceforge.net:
![image](https://user-images.githubusercontent.com/13679322/223586997-25d17129-1446-49b6-9b71-4cfcb78085ed.png)

I suppose this is low priority, but it causes confusion when encountering problems like in #7438.

### Steps to reproduce the behavior

Check the version information in Properties -> Details (or simply wait for tool-tip pop-up with the same information in Windows Explorer).

### Expected behavior

Version information should match the actual release version.

**Comment by Wedge009** [comment]
1.17.14 Windows executables are showing the correct information in the version now. Thanks. Awaiting the next 1.16 release before closing.

**Comment by Wedge009** [comment]
1.16.9 release now reports 1.16.9.0 for file version, 1.16.8+dev for product version.

**Comment by Wedge009** [comment]
I'm re-opening this. 1.17.18 release, downloaded from sourceforge.net, has 'File version' reported as 1.17.15.0 and 'Product version' reported as 1.17.15. Why does this happen?

As an aside, the original report shows 'Copyright' as 2003-2018 and 1.17.18 release has 'Copyright' as 2003-2022. Still not quite right, although an improvement over the older releases.

**Comment by soliton-** [comment]
@loonycyborg looks like 9df0a5943fd8e5c7cc64d4747a578928a577ae07 was not enough.

The copyright can be adjusted in `packaging/windows/wesnoth.rc`.

**Comment by loonycyborg** [comment]
In fact it's all because of confusion caused by packaging/windows symlink, I need to think how to reorganize this build step to avoid this.

**Comment by Wedge009** [comment]
Windows 1.17.19 release:
* File version: 1.17.19.0
* Product version: 1.17.19
* Copyright: 2003-2023

Seems good for now, so closing. Thanks.

**Comment by Wedge009** [comment]
Because 1.17 was working (and I just confirmed 1.17.20 follows the same - correct - pattern as 1.17.19), I'd neglected to check 1.16 releases. I'm not sure if the change for master also need to be applied for 1.16.

Despite what the details say, this is the properties listing for Wesnoth 1.16.10 official Windows release (note the date modified), 1.16.9 was released in April 2023.

![image](https://github.com/wesnoth/wesnoth/assets/13679322/de189ae3-a6f1-4339-b806-70bc9c0d4ab9)

**Comment by soliton-** [comment]
Is this fixed now?

**Comment by Wedge009** [comment]
Need to wait for 1.6.11 release.

**Comment by Wedge009** [comment]
Looks good for at least the Steam release executable. Thanks.
