### ISSUE TITLE
Tauroch units can only use each attack once per scenario instead of once per turn

### ISSUE THREAD

**Issue by abepressman** [wesnoth/wesnoth#7446]
### Game and System Information

- **Version:** 1.17.13
- **Downloaded from:** Steam
- **Build info:** ?
- **OS:** Mac OSX

### Description of the bug

Decided to try out Under the Burning Suns to see how the new units work. Unfortunately, once my taurochs attack, they can't attack anymore. At all. This is not how the ability "once per turn" is described.

**Comment by abepressman** [comment]
Just updating to add: However the Quenoth fighter line was *supposed* to change, I don't think it quite worked right. The units now have extra attacks, but those attacks are completely useless.

**Comment by Toranks** [comment]
![imagen](https://user-images.githubusercontent.com/40789364/224479711-64166b39-746a-4613-b302-2c09f56443ab.png)
I just checked all the variations of the Tauroch and they work fine. Aren't you using a campaign already started when the changes were made? That can mess things.

**Comment by knyghtmare** [comment]
Works for me.

**Comment by abepressman** [comment]
<img width="1439" alt="Screen Shot 2023-03-11 at 6 46 35 AM" src="https://user-images.githubusercontent.com/26127550/224482511-f80bf038-dfb5-4f48-abdf-15a851f1a238.png">

Screenshot attached. Maybe it's a bug related to mac, or steam, or something to do with how they spawn in the first level?

I just started playing a new game from the beginning, yeah. None of my taurochs can attack more than once, period.

The Quenoth Fighter line also appears to be broken with respect to its attacks. (At higher levels, it gains multiple basically identical attacks, that don't seem to be usable in any circumstance.)

**Comment by knyghtmare** [comment]
WAIT

![image](https://user-images.githubusercontent.com/5283677/224482609-15f6a75f-c00c-4331-8a89-2b94e72a44d4.png)

**Comment by abepressman** [comment]
<img width="500" alt="Screen Shot 2023-03-11 at 6 49 41 AM" src="https://user-images.githubusercontent.com/26127550/224482635-4bf0c8aa-76db-47d8-bb7e-edb9908a14d6.png">
<img width="534" alt="Screen Shot 2023-03-11 at 6 49 36 AM" src="https://user-images.githubusercontent.com/26127550/224482636-8e8fbbed-c22d-4dba-9604-27b378315f8c.png">

Also (and I could put it in a different thread if that's better), the changes to the Quenoth fighters aren't working as intended either.

**Comment by knyghtmare** [comment]
@abepressman can you split the Quenoth fighter bug to another issue tracker?

**Comment by abepressman** [comment]
Of course! Will do.

**Comment by Toranks** [comment]
I confirm it too. It's reproducible by simply attacking with a Tauroch and skipping to the next turn.

**Comment by Hejnewar** [comment]
Its funny. I was waiting for someone to notice and it almost would make it till next patch without anyone noticing and at that point it would be already fixed.

**Comment by Toranks** [comment]
```
    [event]
        name = turn end
        first_time_only = no

        [modify_unit]
            [filter]
                [has_attack]
                    special_id = once_per_turn_$weapon.name
                [/has_attack]
            [/filter]

            [set_variable]
                name = $weapon.name|_used
                value = 0
            [/set_variable]
        [/modify_unit]
    [/event]
```

$weapon variable doesn't apply on turn events, only on events related to attacks. You have to delete the variables of all existing attacks, not just one, since the Tauroch have more than one attack

**Comment by Hejnewar** [comment]
Tbh I dont get this comment since this is fixed already... Just not commited cuz I still have more to do.

**Comment by Wedge009** [comment]
The heading and discussion was very misleading, till I realised the issue was to do with how the attacks are handled.

I only found this for master - I presume there was some sort of major revision for 1.17? 1.16 works fine.

**Comment by abepressman** [comment]
> The heading and discussion were very misleading, till I realised the issue was to do with how the attacks are handled.

So, it's a little more complicated than that. If they're attacked and counterattack, they also lose the ability to use that attack.

**Comment by Toranks** [comment]
> Tbh I dont get this comment since this is fixed already... Just not commited cuz I still have more to do.

I didn't understand that you had already fixed it. Also @knyghtmare messed me up on discord xD
