### ISSUE TITLE
Quenoth Fighter unit line multi-attack implementation needs improvement

### ISSUE THREAD

**Issue by abepressman** [wesnoth/wesnoth#7447]
### Game and System Information

- **Version:** 1.17.13
- **Downloaded from:** Steam
- **Build info:**
- **OS:** Mac OS

### Description of the bug

For some reason, the Quenoth Fighter line of units appear to have gained extra attacks that don't do anything. (I don't know what was _intended_, but at least on the version I'm running, they merely have copies of their attacks that deal less damage)
<img width="500" alt="Screen Shot 2023-03-11 at 6 49 41 AM" src="https://user-images.githubusercontent.com/26127550/224482758-16fd069e-f832-4344-98ea-0ac3bc2c5138.png">
<img width="534" alt="Screen Shot 2023-03-11 at 6 49 36 AM" src="https://user-images.githubusercontent.com/26127550/224482759-f9c6e47c-c41b-4670-9439-8576423abb00.png">

**Comment by knyghtmare** [comment]
Apparently, they use different number of "attacks" for each. Meaning, that 9-1 there can hit more than one opponent or the same opponent twice.
However, I see a very bad UX here since nothing of this note has been shown to the player (you).
I explained this before..nobody listened and now you have an open issue here. LOL

**Comment by Hejnewar** [comment]
Now Im waiting for bug report that states that Taurochs are useless and that Fighters are OP because both a bugged and it is really easily noticable after a while. Also the bug for UI and gameplay are already opened when it comes to attacks used.

**Comment by abepressman** [comment]
> Apparently, they use different number of "attacks" for each. Meaning, that 9-1 there can hit more than one opponent or the same opponent twice.

SO, this is not at all intuitive or explained. If they make the 9-2 attack, their turn ends. If they make the 9-1 attack first, they can follow it up with the 9-2 attack.

> Actually, it's here but not many would take time to read a unit text:

The unit text doesn't explain at all how the ability actually works, and if you're a normal player who always uses the better attack first, you'll likely never figure it out.

**Comment by Wedge009** [comment]
Again, the heading was misleading. As best as I can see there are two issues:
* The reason for the seemingly duplicated attack entries is not clear at first - I take it that either the level 1 fighter can expend both of its attacks on one target, as conventional for most other main-line units, or only attack once and then possibly use its other attack on another target.
* This brings up the other problem in that the fighter can target one opponent with the single attack and then on the subsequent attack choose the double attack option.

**Comment by abepressman** [comment]
> * This brings up the other problem in that the fighter can target one opponent with the single attack and then on the subsequent attack choose the double attack option.

I have no idea how it's *supposed* to be implemented. Since the order of attacks affects the number of attacks, which I assume wasn't intended.

**Comment by stevecotton** [comment]
> Also the bug for UI and gameplay are already opened when it comes to attacks used.

The UI bug is #7367, but I don't see a bug for the gameplay. Where's the bug for a unit with `attacks_left=1` still being able to use an attack with `attacks_used=2`?

**Comment by Toranks** [comment]
> > Also the bug for UI and gameplay are already opened when it comes to attacks used.
> 
Where's the bug for a unit with `attacks_left=1` still being able to use an attack with `attacks_used=2`?

This is intended? Should have an additional key to set that possibility to yes/no

**Comment by Hejnewar** [comment]
> > Also the bug for UI and gameplay are already opened when it comes to attacks used.
> 
> The UI bug is #7367, but I don't see a bug for the gameplay. Where's the bug for a unit with `attacks_left=1` still being able to use an attack with `attacks_used=2`?

#7406

**Comment by Wedge009** [comment]
So that's what those two reports are about, I didn't know they would impact main-line units. Could this be closed as duplicate then, or treated as a campaign-specific subset?

**Comment by CelticMinstrel** [comment]
I think I'd probably say this is something that depends on those but might not be equivalent to them…?
