### ISSUE TITLE
Nr: Some Problems with Northern Rebirth

### ISSUE THREAD

**Issue by TheShadowOfHassen** [wesnoth/wesnoth#7448]
So I was playing Northern rebirth and I have found a few bugs and have a few suggestions.

First I'm assuming you know this but the art for the portraits are drastically different from the rest of the game. They're not bad but the art style is different.

Another thing is it may be in other places but In scenario 10 Stolen Gold  Hamel refers the dwarves as men more than once.

The last problem is also mentioned in issue # 5374 If Eryssa dies after you rescue her you loose the game, I don't remember either the objectives saying that or there being a crown over her head.

Their not breaking issues or anything but they'd be nice to have fixes. Thanks for the great game.

**Comment by Wedge009** [comment]
Thanks for the feedback but I'm not sure I see anything new here. Art development is an ongoing effort and you're right, the art for NR is a bit inconsistent but I think it's one of the oldest in terms of introduction.

There is some discussion of 'men' to refer to non-human people in #4880.

If #5374 is already logged, then that covers the situation with Eryssa, doesn't it?

**Comment by TheShadowOfHassen** [comment]
#5374 does sort of log it except it's been assigned to someone two years ago and It wasn't done. I brought it up again because I wasn't sure if anyone was still doing it. It has not been a very fun experience to forget I have to keep her alive and when she dies I loose

Also I noticed looking through the campaign files that there is a hole bunch of dialog and stuff for a plot arc that needs edited out. You probably know that.

Another comment I have for the campaign is that the battles are so much bigger and it takes me days of playing to get through them. It gets kind of boring but that's just me.

I just wanted to bring these problems to attention. I'll close the issue when the issue for Eryssa is fixed. I could figure it out if everyone else is busy. I don't think it'd be too hard.

**Comment by Wedge009** [comment]
Keep in mind this is a volunteer, community project and a lot of issues are quite old but by the same token eventually many issues to get resolved at some point. You're welcome to have a go if you'd like to see something improved.

I understand there's an ongoing effort to thoroughly revise a bunch of official campaigns and I think NR is one of them. @nemaara may update you on that.

I believe NR is supposed to be at the harder end of the spectrum so larger battles are part of that. At the same time, a large battle that doesn't really have anything going for it beyond its scale is probably a candidate for improvement - I know there are plenty of other contributors far more critical in this aspect than I am who are actively working on game-play improvements.

**Comment by knyghtmare** [comment]
> First I'm assuming you know this but the art for the portraits are drastically different from the rest of the game. They're not bad but the art style is different.
> Thanks for the feedback but I'm not sure I see anything new here. Art development is an ongoing effort and you're right, the art for NR is a bit inconsistent but I think it's one of the oldest in terms of introduction.

NR has had a portrait set done. I dont see why they have not been committed.
https://forums.wesnoth.org/viewtopic.php?f=9&t=38969

I also brought up this topic in the discord channels but was ignored. So I throwing this comment with the link as I demand answers

**Comment by cooljeanius** [comment]
I'll see how many of these I can work into #6057 after @macabeus fixes the map-diff thing

**Comment by cooljeanius** [comment]
> > First I'm assuming you know this but the art for the portraits are drastically different from the rest of the game. They're not bad but the art style is different.
> > Thanks for the feedback but I'm not sure I see anything new here. Art development is an ongoing effort and you're right, the art for NR is a bit inconsistent but I think it's one of the oldest in terms of introduction.
> 
> NR has had a portrait set done. I dont see why they have not been committed. [forums.wesnoth.org/viewtopic.php?f=9&t=38969](https://forums.wesnoth.org/viewtopic.php?f=9&t=38969)

Do you know if Valkier is on GitHub?

**Comment by nemaara** [comment]
I think those portraits are not too bad but don't entirely fit the vibe of the current campaign as well, so personally I would stick with the current ones. It would very much be nice to get LordBob quality portraits, but those are hard to come by and it's not fair to ask him to work on them unless he's specifically interested.

As far as the dialogue you have a great point and I would go further and say not just this campaign but a lot of campaigns could use a bit of touchup on style, let alone story/plot/etc. We just have limited energy to work on all of them as a small team so these revisions will come slowly.

**Comment by TheShadowOfHassen** [comment]
Thanks for making the change! I can't wait until you push it to the steam version!

I can work on some of the dialog if you all like. Just point me where I need to edit the dialog so the translators can translate and I'll 

The images look good they need another draft I think. I don't know art so I can't say exactly what's wrong. I seem to remember that their was a Hamel in another campaign and they look sort of similar so maybe it could be used.

**Comment by nemaara** [comment]
You can go ahead and modify the dialogue in the scenario files or you can send me a script instead and I will put it in for you.

**Comment by Wedge009** [comment]
> ...scenario files...

https://github.com/wesnoth/wesnoth/tree/master/data/campaigns/Northern_Rebirth/scenarios

**Comment by TheShadowOfHassen** [comment]
Thanks!

**Comment by TheShadowOfHassen** [comment]
I might have done a bit more than dialog in pull request #7454. I didn't even get to the dwarf part. I looked over the scenario and found a few things I thought might be good to change. I'll get to the said dwarf dialog once I get to the scenario.

I hope that was ok.
