### ISSUE TITLE
Add-on ID not shown below Translations field

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7455]
The comment https://github.com/wesnoth/wesnoth/pull/7442#issuecomment-1459640492 in #7442 states that it should be below "Translations", but it clearly is not.

![image](https://user-images.githubusercontent.com/5283677/225237662-d736c306-51b9-4e39-a90a-cd78fe5ac2e1.png)

### Build Info

1. Wesnoth 1.17.13+dev (latest commit) as of 15/3/23, 3:30 PM HK Standard Time
2. Windows 10
3. Msys2 Compiled Build
4. Github download

### Expected Behaviour
1. ID filed below "translations" field

**Comment by soliton-** [comment]
No idea how this is considered a bug. Clearly the linked suggestion wasn't implemented before the PR was merged.

**Comment by knyghtmare** [comment]
> Clearly the linked suggestion wasn't implemented before the PR was merged

I viewed the last part of the PR. seems to be the case.

**Comment by Vultraz** [comment]
As of 78620c7d6171345691586fdc3183656738f1f4aa the addon id has been moved to a different place.
