### ISSUE TITLE
[Windows] woptipng.py Does not work

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7457]
the command:
```java
py woptipng.py C:\Users\Cheese\Documents\My Games\Wesnoth1.17\data\add-ons\War_of_Legends\images
```
The output:
```java
Traceback (most recent call last):
  File "C:\msys64\home\Cheese\wesnoth\utils\woptipng.py", line 53, in <module>
    os.nice(args.nice) # set niceness
AttributeError: module 'os' has no attribute 'nice'
```

I use Python 3.10.7

**Comment by knyghtmare** [comment]
> Niceness should only be set on supported platforms.

I checked with:
```py
import os
print(os.nice(5))
```
And it seems it's non-existent in Windows
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'nice'
```

**Comment by knyghtmare** [comment]
> Note that matthiaskrgr has a separate repo for woptipng here: https://github.com/matthiaskrgr/woptipng
(I'm still not entirely clear on whether woptipng bug reports should go there, here, or both places...)

Cross-issue report if you have to, all I want is my add-on development to proceed without hindrance.

**Comment by Elvish-Hunter** [comment]
> And it seems it's non-existent in Windows

@knyghtmare It doesn't exist and it's even officially documented at https://docs.python.org/3.10/library/os.html.

> Availability: Unix.

I think I can fix it.

**Comment by knyghtmare** [comment]
I am not done haunting you yet... :p

```
Collecting files...  done
WARNING: can't handle following files:'
C:/Users/Cheese/Documents/My, Games/Wesnoth1.17/data/add-ons/War_of_Legends

Compressing 0 pngs...
ERROR: advdef binary not found!
ERROR: optipng not found!

```

**Comment by Elvish-Hunter** [comment]
This is an issue I kind of expected. woptipng internally uses ImageMagick, advdef (which is part of the AdvanceCOMP package) and optipng. All three of them must be installed and their directories must be added to the `PATH` environment variable (otherwise Windows would require the full paths to their executables; perhaps three command line switches can be added to do so).
Have you installed them and added them to PATH?

**Comment by knyghtmare** [comment]
why is this so complicated for Windows and just one click for MacOS?
Argh...
I am just gonna ignore the `libpng warning: iCCP: known incorrect sRGB profile` for now
until I do the tasks with macOS...
