### ISSUE TITLE
Incompatible passphrase and forum_auth keys in PBL files

### ISSUE THREAD

**Issue by Elvish-Hunter** [wesnoth/wesnoth#7468]
### Game and System Information

Version 1.17.14+dev (f0413a11729), self-compiled, running on Xubuntu 22.04 LTS (x86-64).

### Description of the bug

I was doing some experiments with the add-ons server (to improve the addon_manager script) and I tried to upload an add-on which has both a passphrase and `forum_auth=true`.

Despite being registered on the forums, I got this error message:

![add-ons authentication error](https://user-images.githubusercontent.com/4049668/226768368-ac2b8665-74dc-4718-b3da-3620b513b8c0.png)

### Steps to reproduce the behavior

Try to upload an add-on on the 1.17.x server that has both the `passphrase=` and `forum_auth=true` keys in the PBL file.
For reference here's the content of my PBL file (with e-mail and passphrase removed):
```
author="Elvish_Hunter"
description="test123"
email="<removed>"
icon="items/rock.png"
passphrase="<removed>"
title="test123"
type="campaign"
version="0.0.7"
forum_auth=true
```

### Expected behavior

Even if forum_auth should override passphrase, perhaps a warning message if both keys are present will be useful. Certainly the game shouldn't tell me that I'm not registered.

### Additional context

From the stderr log:
> 20230322 00:41:17 error addons-client: server error: extra_data = 
> message = Add-on rejected: Forum authentication was requested for a user that is not registered on the forums.
> status_code = 3
>
> 20230322 00:41:17 error general: The add-on was rejected by the server:
>
> Forum authentication was requested for a user that is not registered on the forums.

**Comment by Toranks** [comment]
This happens to me some days ago, and I mentioned that on #modding. Currently I only use forum_auth=true and it works fine for me in both 1.16 and 1.17

**Comment by CelticMinstrel** [comment]
Um… shouldn't that have failed the schema validation step?

**Comment by Elvish-Hunter** [comment]
> Um… shouldn't that have failed the schema validation step?

I didn't get any validation errors.

**Comment by CelticMinstrel** [comment]
Hmm, I might have figured out why. What happens if you change it to `forum_auth=yes` (but everything else the same)?

**Comment by Elvish-Hunter** [comment]
> What happens if you change it to `forum_auth=yes` (but everything else the same)?

It returns the same error message.

**Comment by Pentarctagon** [comment]
> This happens to me some days ago, and I mentioned that on #modding. Currently I only use forum_auth=true and it works fine for me in both 1.16 and 1.17

What? forum_auth doesn't exist for 1.16.

**Comment by Toranks** [comment]
> > This happens to me some days ago, and I mentioned that on #modding. Currently I only use forum_auth=true and it works fine for me in both 1.16 and 1.17
> 
> What? forum_auth doesn't exist for 1.16.
```

I have this on 1.16 and 1.17 and works fine since a few weeks. Before I had to use passphrase in 1.16, but not anymore. I don't know what has changed in the addons server.

author=Toranks
icon="units/human-loyalists/duelist-die5.png"
version="3.3.5"
title="Non-Fatal Wounds Extended"
type="mod_mp"
email="my@email.com"
forum_auth=true
description="blablabla"
```

**Comment by CelticMinstrel** [comment]
> It returns the same error message.

Huh… I thought the issue could be that the schema's `forum_auth=yes` test wasn't matching if it's set to `true`, but maybe there's another issue here…
