### ISSUE TITLE
Reworking suggestions about the stance of saurian race regarding cannibalism as not a taboo

### ISSUE THREAD

**Issue by demario-w** [wesnoth/wesnoth#7469]
### Describe the desired feature

Since version 1.14 of Battle for Wesnoth, one section of the saurian race description states that:

"""
Because of their rapid population growth, frequent splits in clans, *and the fact that cannibalism is not taboo*, violence is one of the defining features of Saurian life. This limits the growth of the Saurian culture to fits and starts, as much of their knowledge is passed by oral tradition and their possessions must be mobile.
"""

The highlighted part is the sole instance where saurians are linked to cannibalism. No other mention to this fact is present in existing mainline campaigns. The very subtle reference to possible cannibalism would naturally lead people to think that this is not a regular practice. It could be part of some saurian rituals, some shamanic practices or rites of passage, in other words, very specific circumstances. The meaning might be highly symbolic ("I annihilate you", "I adopt you", "Those who followed you will now follow me"...). As such, the cannibalism is likely to be limited to very specific parts of the victim's body (heart, brains...). It is utterly unlikely that the aim of the cannibalism is to feed oneself or that the full body is eaten.

Unfortunately, this short sentence is repeatedly understood (eg. [here](https://github.com/wesnoth/wesnoth/issues/7361#issuecomment-1418670313) and [there](https://github.com/wesnoth/wesnoth/issues/7361#issuecomment-1423081467) )  as meaning that active cannibalism is common practice in saurian society as a way to feed the population.

The acceptance of cannibalism is an open door for other deviant behaviors. Given that eating a sapient creatures is the worst that can be done, it is likely that it opens the door for the presence of slavery, torture and rape in wesnoth.

It is necessary that the nature of what "cannibalism is not taboo" encompasses is clearly stated so that it is not misunderstood by wesnoth content creators.

As it is hard to make it clear within the saurian race description without having this problematic to standout from the general race information, **I suggest that this part of the sentence is removed** and it is left to a future campaign or other lore defining piece to settle and explain the extend of the practice of cannibalism in the saurian society.

Without the highlighted part, the sentence keeps its original meaning and does not require further change.

**Comment by nemaara** [comment]
Actually, my takeaway from the other issue is that a majority including myself don't view the drake diet as a problem (leaving that issue open for one other reason right now). I'll leave this open for a few days, but if there's no additional response or discussion on this issue I will close it as something we won't fix.

**Comment by CelticMinstrel** [comment]
I don't think I have a problem with this vague reference, at least.

**Comment by demario-w** [comment]
> Actually, my takeaway from the other issue is that a majority including myself don't view the drake diet as a problem (leaving that issue open for one other reason right now). I'll leave this open for a few days, but if there's no additional response or discussion on this issue I will close it as something we won't fix.

Just putting the record straight, this issue is about saurian and *not* drakes. These are 2 different races and saurians do not practice any flesh eating in the campaign the other thread is about. I am not sure where the confusion is coming from.

Lastly let's remember the time where [such an argument](url=https://forums.wesnoth.org/viewtopic.php?p=650518#p650518) would be receivable by the development team:
> Well, do drake females serve any useful or interesting purpose in WoV? If not, then what's the point of arguing about political correctness and so on? If they can be deleted entirely without any further changes being needed because their presence or lack thereof has no impact at all on the story, then **it's just poor writing to put something like that in there and then do nothing with it**.

It was in 2020. How time flies.

**Comment by Pentarctagon** [comment]
I don't really see the connection between that topic and this one? There's a significant difference between "all Drake females are non-sentient breeders" vs "cannibalism occurs sometimes in Saurian society".

**Comment by nemaara** [comment]
I actually forgot to close this so I'm going to do so now. Another dev may feel free to reopen for more questions or if something else changes of course.
