### ISSUE TITLE
Dead Water difficulty selection, sprite missing

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#7474]
### Game and System Information

- **Version:** 1.17.14
- **Downloaded from:** Steam
- **OS:** Windows 10

### Description of the bug

As you can see, the sprite for the 'citizien' difficulty is missing.
![grafik](https://user-images.githubusercontent.com/39015360/227056805-617af30c-5b8e-49cd-8eaa-180b1a35bedb.png)

### Steps to reproduce the behavior

Click on 'campaigns'
Select Dead Water
Click on the difficulty selection

### Expected behavior

The citizien sprite being next to the citizien difficulty.

**Comment by Wedge009** [comment]
Regression from 1.16.

**Comment by Wedge009** [comment]
Seems to be because of the Citizen unit being moved to core in #7323.
