### ISSUE TITLE
Game quits at scenario end when loading a mp campaign game in singleplayer in debug mode 

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#7478]
### Game and System Information

- **Version:** 1.16.8+dev

### Description of the bug

When a multiplayer Campaign game is resumed via the normal "Load Game" button from Titlescreen, the game ends at the end of the scenario in debug mode.

### Steps to reproduce the behavior

1. Start A game of world Conquest and Save it.
2. Exit game and reload it via the normal Load game Menu
3. Use :debug and :n to advance to the next level

### Expected behavior

The next scenario should start

### Additional context

It quits here https://github.com/wesnoth/wesnoth/blob/a5825a58c70351404e09ea131c259e8d471157de/src/game_initialization/playcampaign.cpp#L393 And i suspect this or a related commit:

https://github.com/wesnoth/wesnoth/commit/2cf8ec63a9633a29cc14fe0efcaf5368b4e1b5f4

Maybe  @Vultraz knows more.

**Comment by Wedge009** [comment]
Confirmed on both master and 1.16.

**Comment by Pentarctagon** [comment]
This only happens with :debug, not when playing normally, right?

**Comment by Wedge009** [comment]
I think I would have only tested in debug-mode. I wouldn't have attempted to complete a WC game normally.

**Comment by sigurdfdragon** [comment]
Yes, only seems to happen when debug mode is active at end of scenario.
Tested on Win Steam BfW 1.17.22 via 
1. loading a scenario of World conquest 1p via titlescreen menu with debug off.
2. turned on debug to set up a quick win of scenario then turned off debug.
3. quickly won scenario. it advanced properly to the next one.
4. turned debug back on, left it on, and quickly won that scenario. It then went to load screen & then ended to titlescreen.

**Comment by Discontinuum** [comment]
Any progress on this?

**Comment by ProditorMagnus** [comment]
Isnt the issue that that wc doesnt have next scenario, all of them are generated only on demand?

**Comment by Discontinuum** [comment]
No because this bug affects any MP campaign, not only WC.

**Comment by gfgtdf** [comment]
I mean we coudl easiyl push a temporary fix for this case i dont rememebr why we didn't.

**Comment by gfgtdf** [comment]
made a pr for a fix in #8907

**Comment by gfgtdf** [comment]
This is fixed, the commit message says its not an optiomal fix but after looking at the code it seems like in non-networked games connect_engine.can_start_game() always returns true since it can assign human sides automaticially to the player.
