### ISSUE TITLE
[BUG][Descent into Darkness][S8 - Alone at Last] Walking Corpse (Bat) can take book item

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7485]
### Game and System Information

- **Version:** 1.17.14+dev
- **Downloaded from:** Github
- **Build info:** Msys2 Compiler with Scons cmd
- **OS:** windows 10

### Description of the bug

Scenario instructions state that the Bats and Ghosts cannot carry the book. This is true..
BUT..a walking corpse of a bat can carry the book.

### Steps to reproduce the behavior

1. Take the book with a Walking Corpse of Bat variant

### Expected behavior

Bat Corpses cannot carry the book of the Dead.

### Additional context

![image](https://user-images.githubusercontent.com/5283677/227766128-896f5d66-4525-4282-a543-ee798d5d8186.png)

**Comment by knyghtmare** [comment]
Since this is 1.17, I can only presume, 1.16 has it as well.

**Comment by Wedge009** [comment]
This sounds similar to #6576. Any other units should be barred from taking the book?

**Comment by knyghtmare** [comment]
> Any other units should be barred from taking the book?

Soulless/WC Bat variant might be the only missing entry.
