### ISSUE TITLE
MP Lobby: Assertion error in Match History tabs

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#7489]
### Describe the desired feature

I understand Match History was only implemented in 1.17 so this isn't applicable for 1.16. Since I don't play MP, I assume this is why have no history. However, attempting to use the history function results in an unresponsive UI while the client attempts to find data that isn't there. This is confirmed by log messages:

> error network: Timed out waiting for history data, returning nothing

Time-out is supposed to be only 5 seconds, but it still feels strange to have the UI do nothing (and block redraws). Perhaps attempt the network transfer asynchronously - maybe 5 seconds is too short an interval to bother with showing a progress bar or any such feedback.

Additionally, the history dialogue should probably not be shown at all if no history data is found - display some text to the user instead, something simple like 'no history found'.

**Comment by Pentarctagon** [comment]
Can you try this with debug network logging enabled and post the results of that?

**Comment by Wedge009** [comment]
That's bizarre. With debugging on, apparently I do have one game saved on the server (obviously I must have been testing something):

```
20230327 18:05:07 debug network: Received no data
20230327 18:05:07 debug network: In wesnothd_connection::send_data::lambda
20230327 18:05:07 debug network: Written 85 bytes.
20230327 18:05:08 debug network: Received no data
20230327 18:05:08 debug network: Received no data
20230327 18:05:08 debug network: Received no data
20230327 18:05:08 debug network: Received no data
20230327 18:05:09 debug network: Received no data
20230327 18:05:09 debug network: Received no data
20230327 18:05:09 debug network: Received no data
20230327 18:05:09 debug network: Received no data
20230327 18:05:10 debug network: Received no data
20230327 18:05:10 debug network: Received no data
20230327 18:05:10 debug network: Received no data
20230327 18:05:10 debug network: Received no data
20230327 18:05:11 debug network: Received no data
20230327 18:05:11 debug network: Read 274 bytes.
20230327 18:05:11 debug network: Received:
[game_history_result]
        era_name = Default
        game_name = Wedge009’s test
        game_start = 2021-09-15 15:11:17
        replay_url = https://replays.wesnoth.org/trunk/2021/09/15/4p__Blue_Water_Province_Turn_1_(9).bz2
        scenario_name = 4p — Blue Water Province
        version = trunk
        [player]
                faction = Rebels
                name = Wedge009
        [/player]
        [player]
                faction = Loyalists
                name = Wedge009
        [/player]
        [player]
                faction = Loyalists
                name = Wedge009
        [/player]
        [player]
                faction = Undead
                name = Wedge009
        [/player]
[/game_history_result]

20230327 18:05:11 debug network: Received history data: [game_history_result]
        era_name = Default
        game_name = Wedge009’s test
        game_start = 2021-09-15 15:11:17
        replay_url = https://replays.wesnoth.org/trunk/2021/09/15/4p__Blue_Water_Province_Turn_1_(9).bz2
        scenario_name = 4p — Blue Water Province
        version = trunk
        [player]
                faction = Rebels
                name = Wedge009
        [/player]
        [player]
                faction = Loyalists
                name = Wedge009
        [/player]
        [player]
                faction = Loyalists
                name = Wedge009
        [/player]
        [player]
                faction = Undead
                name = Wedge009
        [/player]
[/game_history_result]
```

And then if I try the Players or Modifications tab I get a complete application crash - that'd be a bug not an enhancement issue.

```
wesnoth: src/gui/widgets/generator_private.hpp:691: gui2::grid& gui2::generator<minimum_selection, maximum_selection, my_placement, select_action>::item(unsigned int) [with minimum_selection = gui2::policy::minimum_selection::one_item; maximum_selection = gui2::policy::maximum_selection::one_item; my_placement = gui2::policy::placement::vertical_list; select_action = gui2::policy::select_action::selection]: Assertion `index < items_.size()' failed.
Aborted
```

**Comment by Pentarctagon** [comment]
Huh... well that's not good. I'll try and reproduce that myself, but if I can't I might need you to be logged into the lobby while I debug it so I can view your match history results from my local debug build.

**Comment by soliton-** [comment]
An automatic timeout is a bad idea. It wastes server resource doing work that is just thrown away. Aborting waiting for the data should only be done on user request.

**Comment by Pentarctagon** [comment]
I'm not sure what the connection there is? It will waste server resources if the user cancels out of the dialog too.

**Comment by Wedge009** [comment]
> Huh... well that's not good. I'll try and reproduce that myself, but if I can't I might need you to be logged into the lobby while I debug it so I can view your match history results from my local debug build.

Be glad to help, but we'll need to co-ordinate a time when you're ready to do this. I fly out on volunteer work in a couple of days and won't be back till the Easter weekend.

The crash is on the client side, though, looks like out-of-bounds access.

**Comment by soliton-** [comment]
> I'm not sure what the connection there is? It will waste server resources if the user cancels out of the dialog too.

Yes, on explicit user request. Not automatically which in its current form will probably just confuse the user and make them request again wasting even more resources. It's just really bad UX IMO.

**Comment by Pentarctagon** [comment]
GUI2 updates can only be done in the main thread, correct? So this would involve using std::async to run it in the background and then a timer of some sort to periodically check whether it completed. However my understanding is also that there's apparently no safe way to terminate a thread/std::async task in C++, so if the user clicks the cancel button before it returns data then it would just continue on running in the background anyway until it completed?

**Comment by Wedge009** [comment]
To answer @Pentarctagon from #7510, I couldn't get a stack trace. In a release build I get to this point:
![image](https://user-images.githubusercontent.com/13679322/230761134-fa2ffbda-54a3-4c30-b913-d3229950d522.png)

Clicking Players or Modifications tab results in a crash to desktop:
```
wesnoth: src/gui/widgets/generator_private.hpp:691: gui2::grid& gui2::generator<minimum_selection, maximum_selection, my_placement, select_action>::item(unsigned int) [with minimum_selection = gui2::policy::minimum_selection::one_item; maximum_selection = gui2::policy::maximum_selection::one_item; my_placement = gui2::policy::placement::vertical_list; select_action = gui2::policy::select_action::selection]: Assertion `index < items_.size()' failed.
```

But in a debug build I just get the `error network: Timed out waiting for history data, returning nothing` issue.

**Comment by Wedge009** [comment]
So Pent's change adds a message indicating if a time-out was encountered. But an empty dialogue is still shown afterwards. Might be trivial, but I think it works better if no dialogue was shown at all in the case of network time-out.

Also, when that single test game shows in my history, I still get the crash if I try to click on Players or Modifications:
```
wesnoth: src/gui/widgets/generator_private.hpp:691: gui2::grid& gui2::generator<minimum_selection, maximum_selection, my_placement, select_action>::item(unsigned int) [with minimum_selection = gui2::policy::minimum_selection::one_item; maximum_selection = gui2::policy::maximum_selection::one_item; my_placement = gui2::policy::placement::vertical_list; select_action = gui2::policy::select_action::selection]: Assertion `index < items_.size()' failed.
```

While this is different from my original issue of not appearing to have any history, I'll re-open and rename.

**Comment by Wedge009** [comment]
> Might be trivial, but I think it works better if no dialogue was shown at all in the case of network time-out.

It seems like the code should return without attempting to show the match history dialogue, but it did in my case. Unfortunately, I can't replicate the time-out again right now so I can't check this.
https://github.com/wesnoth/wesnoth/blob/61b37a746fb7c1c97f49859fe2f6ffe53484e26c/src/gui/dialogs/multiplayer/match_history.cpp#L205-L211

**Comment by Pentarctagon** [comment]
For the crash, I can't reproduce it on my end, so I'm not sure what else would be causing the issue. Could you try enabling debug symbols and getting a stack trace on the release build?

---

That code is called from the pre_show, so the dialog showing up after that is expected. The question is whether there's a way to cancel out of showing the dialog during the pre_show method.
