### ISSUE TITLE
AMLAs of Kaleh and Nym

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#7504]
### Describe the desired feature

The amlas of Kaleh and Nym are currently bad, not very interesting and unbalanced. Some combinations are clearly better than the others and over all for me the trees lack depth as well as they do not allow the characters to actually keep up with regular units early on but fully leveled heroes are also not by any means powerhouses.

While possessing 9 amlas in total they can only pick 6 of them which can be argued to be enough but players can still max them out relatively easily.

Example of my idea for Nym tree: 
![Nym_1](https://user-images.githubusercontent.com/41817546/229240606-cdf20079-3ddd-4139-b1ba-b3ef7b160764.jpg)

IMO it clearly is too big, some skills could be merged into one and there might not be enough specialisation over cool combination skills in the endgame. Even with these changes I dont think this tree would be particularly great for her, maybe some of the skills would make it out but over all most of them won't be able to. Well at least that adds replay value.  

With Kaleh situation is even more complicated as I don't have any clear idea about what to do with him. My "best" idea for him is literally something akin to policies that for example make units cost nothing but increase / double upkeep and you lose if you don't have any gold left. The clear goal of such amla will clearly be replayability but it also is a ton of work ensuring that it is an appropriate change to the campaign itself.

Or an aura that double movement points of all units / units next to him but after going below your standard max mp unit cant attack or defend at all. 

But this doesn't seem like a proper amla for a character, even in support role. In the end I end up in an inspirational dead end and with the amlas still clearly needing a lot of work. And thus as Im clearly unhappy with my ideas and work, this FR begins its existence.

**Comment by knyghtmare** [comment]
Can you provide some clarification comments on some AMLA here? Like Sword Dance and Arrow Dance?
Another suggestion is marking where the trees start from with different coloring. It took me a while to figure how it starts with Swords(wo)manship, Bow(wo)manship, Nimble, Pathfinder.

Also, it does look an improvement over the current existing one.

**Comment by Hejnewar** [comment]
Okay so I tried to improve the tree for Nym and make if it the campaign better. It still requires to level up more than once per scenario iin order to unlock everything but 17 is better than 26.

![Kopia Nym](https://user-images.githubusercontent.com/41817546/229814079-985d5da0-34ed-4823-85a2-00a33a518937.jpg)

Offsetting Rythm - Each strike lowers enemy dodge against future attacks. 
Sword Dance - damages enemeise around you. 
Hit and Run - gain mp after attacking with sword.
KoE - better mc and dodge on terains. 
Arrow Rain - damages enemies ahead of you.
Self Made Arrows - choose what special arrows you want. 

I think others are self explainatory. 

> Swords(wo)manship, Bow(wo)manship

lol xd
