### ISSUE TITLE
Game don't create autosave for turn one

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#7508]
### Game and System Information

- **Version:**master commit https://github.com/wesnoth/wesnoth/commit/ca013eaff32dd9096e2597d0330092401930caf7
- **Downloaded from:**git(source code)
- **Build info:**mingw64
- **OS:**windows10

### Description of the bug

Remove autosave from first turn affects [event] when wanting to replay the turn

When I start Httt in debug mode and trigger a non-repeatable event on the first round createdafter last autosave, then replay that round with the "back to turn" command, when I try to re-trigger the event, nothing happens because using old autosave and not new generated for turn 1.

On the other hand, if I do it from an autosave on turn 2 or more, everything works normally

### Steps to reproduce the behavior

Load game.
Load Httt(or other campaign) in campaign menu.
In the first turn, trigger an executable event once createdafter creation of last autisave turn 1, use "back to turn" to replay this turn then restart the maneuver of the first turn.

### Expected behavior

Once the turn has been reloaded, the event should be able to re-trigger

**Comment by newfrenchy83** [comment]
bug caused by old autosave when tring to re-trigger event impemented later, whenautosave deleted, impossible to replay turn 1

**Comment by gfgtdf** [comment]
> In the first turn, trigger an executable event once (create enemy in debug mode and attack it with Delfador or Konrad), use "load turn" to replay this turn then restart the maneuver of the first turn.

The game doesn't create an autosave for the first turn, so this was to reprouce doesnt work (for me at least).

**Comment by newfrenchy83** [comment]
description of bug updated

**Comment by gfgtdf** [comment]
It still doesn' work, the game simply doesn't  create an autosave for turn one.

**Comment by gfgtdf** [comment]
Also the title is very unclear to me, How do you remove an autosafe? Do you mean the  "Delete" button in the load game menu?

**Comment by newfrenchy83** [comment]
> It still doesn' work, the game simply doesn't create an autosave for turn one.

this is the problem, the game don't createautosave for turn one and if an old autosave remain, it will e used instead of new auatosave who don't create anymore.

**Comment by gfgtdf** [comment]
And the "Not creating an autosafe" part is new in master right? So 1.16 does create an autosave on turn 1?

Then i think two unrelated things needs to be done here:
1) Stricter checking whether the original game actually matches the reloaded game, it already does that by comparing the [replay] but for the first turn autosafe ther will probably no replay to compare.
2) Create an autosave on turn 1 again.

**Comment by newfrenchy83** [comment]
> And the "Not creating an autosafe" part is new in master right? So 1.16 does create an autosave on turn 1?
> 
> Then i think two unrelated things needs to be done here:
> 
>     1. Stricter checking whether the original game actually matches the reloaded game, it already does that by comparing the [replay] but for the first turn autosafe ther will probably no replay to compare.
> 
>     2. Create an autosave on turn 1 again.

yes it's new. And it should create autosave turn 1 again

**Comment by gfgtdf** [comment]
I made opened  #7511, so this report is now only about the autosave on turn 1 not being created.

**Comment by gfgtdf** [comment]
Fixed in: https://github.com/wesnoth/wesnoth/commit/3bba135510f0b72e9748880c0546f40049796876

(please reopen if it still happens, for you)
