### ISSUE TITLE
Nibbler (unit) with odd resistances

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#7516]
### Game and System Information

- **Version:** 1.17.14

### Description of the bug

The Nibbler has weirldy different impact/pierce resistances compared to its advancements.
I'd get it if only pierce res was improved, but why is impact res reduced for advancements? Which is why I think it might be just an oversight.

[Nibbler](https://units.wesnoth.org/1.17/mainline/en_US/Nibbler.html)
![grafik](https://user-images.githubusercontent.com/39015360/230771130-7676c65c-b53f-4dae-991e-d1e3b1647b14.png)

[Caribe](https://units.wesnoth.org/1.17/mainline/en_US/Caribe.html)
![grafik](https://user-images.githubusercontent.com/39015360/230771154-30309031-ccb6-4fe5-9fa1-3d6572e201d4.png)

### Steps to reproduce the behavior

1. Open https://units.wesnoth.org/1.17/mainline/en_US/Nibbler.html
2. Open https://units.wesnoth.org/1.17/mainline/en_US/Caribe.html
3. Compare.

**Comment by knyghtmare** [comment]
Classic Dev Oversight XD
