### ISSUE TITLE
Restore Windows checks when vcpkg issues resolved

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#7523]
### Describe the desired feature

Regular false alerts on the CI made it necessary to merge #7521 lest we become complacent about CI failures. At some point that PR should be reverted, restoring Windows checks.

The linked vcpkg issues are https://github.com/microsoft/vcpkg/issues/28722 and https://github.com/microsoft/vcpkg/issues/26601.

**Comment by stevecotton** [comment]
The fix is now in vcpkg, so it's time to update our version of vcpkg and restore the CI checks.

I intend to do that once the flatpak-related build failures are fixed (so that we don't have two overlapping changes that can cause failures). Also happy if someone else does it first.

**Comment by Wedge009** [comment]
Assuming #7809 does the trick, can close this one. Re-open if it needs to be disabled again.

**Comment by Wedge009** [comment]
Re-opening due to #8704/#8703.

**Comment by stevecotton** [comment]
Unassigning myself because anyone can do the revert when the problems with xz are resolved, although it will probably require upgrading to a new version of vcpkg too.

**Comment by stevecotton** [comment]
They ought to work again: `https://github.com/microsoft/vcpkg/pull/37957#issuecomment-2046017114`

However, following the link from that it might be nice to wait for xz 5.8.0 to be tagged, and the upgrade to a version of vcpkg that pulls the new version in.

**Comment by Wedge009** [comment]
I'll keep a watch for new xz releases on GitHub, but I hope I wouldn't be the only one.

**Comment by Pentarctagon** [comment]
Is there a reason to wait for a new xz release? We don't create any artifacts or distribute anything based on vcpkg to players, so there shouldn't be any risk of letting the CI run.

**Comment by Wedge009** [comment]
I wouldn't have thought so.

**Comment by Wedge009** [comment]
In case it's still relevant, xz 5.6.2 just released.

**Comment by Wedge009** [comment]
vcpkg is still using liblzma 5.4.4 for the time being.
