### ISSUE TITLE
Can't finish the fourth game in SoF

### ISSUE THREAD

**Issue by gth-other** [wesnoth/wesnoth#7527]
### Game and System Information

- **Version:** 1.16.8
- **Downloaded from:**  Steam
- **OS:** Ubuntu 22.04

### Description of the bug

Game does not finish after moving main character to the pointer.
![Снимок экрана от 2023-04-12 11-21-44](https://user-images.githubusercontent.com/81192470/231398582-b06612c1-37ec-4518-a9c3-12fef6ee5515.png)

**Comment by gth-other** [comment]
If I put every main character to the northest path of the map, game finishs. I think game was translated to Russian incorrectly, because translation says "Достигните верхней границы карты Ругнуром, Баглуром или Аланином", that means "Put Rugrun, Balglur OR Alanin to the northest part of the map".

**Comment by Wedge009** [comment]
Looks like the Russian translation wasn't quite right, then, since it looks like the objective has been for Rugnur, Baglur, _and_ Alanin since the scenarios introduction in #4609.
