### ISSUE TITLE
[progress_achievement] does not decrease achievement progress

### ISSUE THREAD

**Issue by Dalas121** [wesnoth/wesnoth#7529]
### Game and System Information

- **Version:** 1.17.14
- **Downloaded from:** Steam
- **OS:** Windows 10

### Description of the bug

The documentation for [progress_achievement] states that "If the achievement's current progress is already higher than the limit, its current progress will be decreased", but doing so has no effect on the achievement's current progress.

### Steps to reproduce the behavior

1. Progress, but do not complete, an achievement.
2. Restart your game, so progress is updated.
3. Use [progress_achievement] with limit=0.
4. Restart your game, so progress is updated.
5. Progress has not been reduced.

### Expected behavior

Achievement progress should be reduced to the [progress_achievement] limit.

**Comment by Wedge009** [comment]
While this certainly sounds contrary to the documentation, as a player I would very much prefer progress not to regress.

**Comment by Dalas121** [comment]
I agree!  I don't think achievements should ever be revoked, but I do think it's important to be able to accurately show partial progress.

In my use-case, I have an achievement for ironman-ing a campaign (no loading a previous turn).  I'd like to show the player's current progress as they complete each mission, so that they can be confident they're still on-track to get the achievement.  The progress needs to reset to 0 if they load a previous save, otherwise the tracker is no longer accurate.

Or another example, maybe you have an achievement for killing 3 enemy leaders in some particular scenario.  You want to show 1/3, 2/3, 3/3 for each leader who's killed, but that progress needs to reset to 0 if they restart the scenario from the beginning.

**Comment by CelticMinstrel** [comment]
I also agree that I'd prefer progress not to regress.

With your use-case (and mine), we're essentially abusing the progress metre to sort of give an idea of how much progress has been made. It's an approximation.

I do think there might be an argument for a different type of achievement that has not a 1/n counter but instead something like

`[x][x][x][ ][ ][ ][x][x][ ][x][ ][x][ ][ ][x][x][x] 1/17`

Though exactly what that would end up looking like is still not well-defined. But I don't think regressing an achievement is a good idea.

Assuming for a moment that the above idea is not implemented, you and I have totally different concepts of the best way to approximate a "collect all N" achievement within the format of a counter.

You want to show them "the progress of the current play-through". But that doesn't even make sense. What is a play-through? What if they start the campaign from the beginning, play through four scenarios, start again from the beginning, play through three scenarios, give up half-way through the third one, then reload the old scenario four save, play through two more scenarios, then go back to the new scenario save and play through to the end? What's the current playthrough? There's no such thing. They could play in any order and hit the sub-achievements in any order. Are you going to save their current progress at the start of every scenario? In that example, supposing one item can be found in every scenario, starting from the beginning resets to 0, right? But then when you reload scenario 4, it suddenly resets to 3? Just loading a scenario updates your progress? That doesn't even make any sense?

I think the best reasonable approximation that can be made is "the maximum number you managed to collect in any given playthrough". Say there are 5 things, A through E. In your first playthrough, you find B and E, so your progress goes up to 2. Then in your second playthrough, you find A, C, and F, so now your progress is 3. Later you play through and find A, B, E, and F, so now your progress is 4. In this case, the "playthrough" is tracked by WML variables stored in the scenario, but they're separate from the actual progress counter. They're just a set of boolean variables for each item that can be found, recording whether it has been found. Exactly like the "third acheivement type" idea above. The exact representation of your progress in a single playthrough.

So the progress bar is nothing more than an approximation. It can never be more than an approximation for this kind of achievement. But I'd rather see a counter that can only go up than a bar that leaps around like a crazed doll.

**Comment by Dalas121** [comment]
> You want to show them "the progress of the current play-through". But that doesn't even make sense. What is a play-through? 

Hmm, that's a really good point.  In my specific case it's not an issue, because restarting (or reloading) resets progress back to 0.  But it wouldn't make any sense for a situation where you can jump between "almost finished", "just starting", and back again by just loading a new game.

In that case, can we just update the wiki so it's accurate about "limit"?  I'll figure out another way to show the player their ironman progress.

**Comment by CelticMinstrel** [comment]
I would note that if it's something that's entirely contained within one scenario, the `[objectives]` may be a good place to show it.

**Comment by Pentarctagon** [comment]
It looks like I was misremembering and did actually add in a check to prevent achievement progress from decreasing. I've updated the wiki to match this.
