### ISSUE TITLE
Using "Back to"/"Load Turn" Menu options perfectly erases/resets Statistics

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7548]
Wesnoth 1.17.15+dev
Windows 10 / msys2 / Github download

Start of turn 16/24
![image](https://user-images.githubusercontent.com/5283677/232761148-f499dc74-cb4e-4c38-bd14-854de7bbe8e0.png)

After using back to on turn16:
![image](https://user-images.githubusercontent.com/5283677/232761235-8df86d4b-c623-4562-a85f-911fdb384a37.png)

**Comment by Toranks** [comment]
I can confirm it, and several people on discord too.

**Comment by Pentarctagon** [comment]
@gfgtdf I would guess that this is related to your "back to turn" changes?

**Comment by gfgtdf** [comment]
Yes

**Comment by gfgtdf** [comment]
I mean in theory this should also effect 1.16 when "back to turn" is used in mp. I'm not sure whether a fix for this is worth backporting though.

**Comment by Pentarctagon** [comment]
If this bug was introduced to 1.16, then the fix needs to be backported to 1.16 as well.

**Comment by gfgtdf** [comment]
I mean in mp this bug probably effects all versions starting  from 1.15.x . But wasn't reported yet.

**Comment by Pentarctagon** [comment]
This is for SP though I believe.

**Comment by knyghtmare** [comment]
> In mp this bug probably effects all versions starting from 1.15.x . But wasn't reported yet.

For MP, if you mean online, then there's no option to "reload" during a live game...for obvious reasons.
For local MP, I would assume people load saves with "Control+O -> Enter" and this skipped detection

And you're also correct. This is present in both SP and MP.

> This is for SP though I believe.

Both now.

**Comment by gfgtdf** [comment]
> For MP, if you mean online, then there's no option to "reload" during a live game.

In online games the "back to turn" does does the same in 1.16.0 as in 1.17.15 . My commit 'just' enabled it in sp too for 1.17.15. hence my wondering whether this is some5worth backporting for mp.

**Comment by knyghtmare** [comment]
> hence my wondering whether this is some5worth backporting for mp

if bug, then backport fix
if bug but might possibly cause MP issues, consult Hejnewar, and then decide if backporting should be done

**Comment by gfgtdf** [comment]
@Pentarctagon is there already a schedule for the next 1.17 release?

**Comment by Pentarctagon** [comment]
https://wiki.wesnoth.org/1.17_Roadmap

The things listed under each release aren't really relevant anymore, but the dates are still the current plan.

**Comment by gfgtdf** [comment]
Okay, I was just asking to be sure there was not another emergency release planned, (in which case i would have suggested to disable this feature until the next release)

**Comment by Pentarctagon** [comment]
Emergency releases are made as needed - they don't show up on that schedule at all aside from a version number being skipped.

**Comment by gfgtdf** [comment]
Well yes, that's why I asked you.

**Comment by Pentarctagon** [comment]
I mean that then I didn't really answer your question by providing your the 1.17 roadmap link. The correct answer would be that there are no further emergency releases planned before the next scheduled 1.17 release, particularly given that even if there was one by the time it was tagged and available for all platforms it'd only be about a week until the next scheduled release anyway.

**Comment by gfgtdf** [comment]
Fixed in https://github.com/wesnoth/wesnoth/commit/01f28b12aea57c969e0331eb38af5dde1bac9cfa
