### ISSUE TITLE
[Campaigns][Bug] WoF unplayable after Scenario 2

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7550]
Something causes the client to assert to desktop after loading the third scenario

![image](https://user-images.githubusercontent.com/5283677/233073085-b0732148-79a0-4e31-98ad-232469867127.png)

Wesnoth 1.17.15+dev
Github
Windows 10 (msys 2)

### More Context:

https://forums.wesnoth.org/viewtopic.php?p=681121#p681121

### Extra Remarks:

before adding new features. playtest your code...
Sincerely, LK

**Comment by soliton-** [comment]
While there may be a workaround possible from the campaign this is pretty surely an engine bug.

**Comment by knyghtmare** [comment]
> While there may be a workaround possible from the campaign this is pretty surely an engine bug.

Not sure what happened exactly, but cannot really play pass S2 at this current state.

**Comment by knyghtmare** [comment]
> the 3rd scenario is 02x_Victory_Feast, right? In this case, maybe the game can no longer manage scenarios without camps or without a map? The files calling the functions containing mod > 0 are playcontroller.cpp among others, and there have been many commits on these files since the last release, but I can't precisely locate the error.

You have a sharp eye, friend. The cutscene scenario seems to be missing side definitions `[side][/side]` so maybe absence of that caused an assertion.

**Comment by newfrenchy83** [comment]
But to locate engine error, i fear to can't be help.

**Comment by knyghtmare** [comment]
> it's missing side definition
> 
> > > the 3rd scenario is 02x_Victory_Feast, right? In this case, maybe the game can no longer manage scenarios without camps or without a map? The files calling the functions containing mod > 0 are playcontroller.cpp among others, and there have been many commits on these files since the last release, but I can't precisely locate the error.
> > 
> > 
> > You have a sharp eye, friend. The cutscene scenario seems to be missing side definitions `[side][/side]` so maybe absence of that caused an assertion.
> 
> i's missing side definition, when i load with side efied, no crash. But why wesnoth don't tolerate missing side anymore?

40fbf95b804ae1d680d44571dff6caa5d69f5438 Maybe. I dont read C++ code but this seems to be the one which relates to the empty side thing

**Comment by newfrenchy83** [comment]
> [40fbf95](https://github.com/wesnoth/wesnoth/commit/40fbf95b804ae1d680d44571dff6caa5d69f5438) Maybe. I dont read C++ code but this seems to be the one which relates to the empty side thing

exact, when i try without this commit, scenarion load normaly

**Comment by Pentarctagon** [comment]
@gfgtdf ^

**Comment by Pentarctagon** [comment]
Addressed in #7555
