### ISSUE TITLE
[BUG][Units] Great SeaHorse Standing Animation prevents Poison Status effect Green Hue from being Shown

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7551]
![image](https://user-images.githubusercontent.com/5283677/233074707-3c8a5d90-ca4b-4fa3-8213-cd328053537e.png)

Screenshot clarifies what I mean

**Comment by doofus-01** [comment]
This probably isn't the only unit with this issue, I'll try to fix it this weekend.
