### ISSUE TITLE
[Campaigns][DM] Assertion after story-sequence in S16

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#7553]
Same as #7550 but for DM this time. Same cause:  [40fbf95](https://github.com/wesnoth/wesnoth/commit/40fbf95b804ae1d680d44571dff6caa5d69f5438)

Not one but two breakages in 1.17.15...Guys, come on...Why you do this?

**Comment by Pentarctagon** [comment]
Addressed in #7555
