### ISSUE TITLE
Liberty S7 Paladin quote grammatical mistakes?

### ISSUE THREAD

**Issue by Crissium** [wesnoth/wesnoth#7556]
### Language

English

### Source

Liberty S7 Glory

### Original Text

        [message]
            speaker=Sir Gwydion
            message= _ "Ready thine lances, mine brethren. Let us charge down the armies of Weldyn!"
        [/message]

### Proposed Change

Ready your lances, ~~my~~ brethren. Let us charge down the army of Weldyn!

Reasons:
(1) thine -> your, since ‘brethren’ is in the plural.
(2) ~~mine -> my, ‘brethren’ does not begin with a vowel.~~ On second thoughts, I believe dropping the possessive determiner would be a more natural way to address fellow members of an order.
(3) armies -> army, well, I think when talking about the opposing force, you should use the singular form. In addition, if ‘army’ means a kind of military unit here, there should be one army manning a fortress at most.

And a paladin would not talk in a deliberately pseudo-archaic way like ‘Thou knoweth too much!’.

**Comment by Crissium** [comment]
> it fits with a common portrayal of paladins.

In fact, I haven't seen much of paladins in the campaigns. I only remember three scenarios which feature paladins who have actually got a few lines ([here](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Secrets_of_the_Ancients/scenarios/21_Against_the_World.cfg), [here](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Eastern_Invasion/scenarios/04c_Mal-Ravanals_Capital.cfg) (not necessarily the loyal paladin, though) and [here](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Descent_Into_Darkness/scenarios/08_Alone_at_Last.cfg)), and they seem like normal speech to me.

> Pseudo-archaicisms are common throughout Wesnoth.

This is the very first instance of pseudo-archaism I’ve ever noticed. But I have never been a careful reader.

**Comment by nemaara** [comment]
I'd like to not make it a habit for people to nitpick at grammar because writers often have their reasons for writing things a certain way, and yes, this means not every sentence has perfect grammar or diction. That being said, I wasn't super happy with this line when I wrote it so I changed it.
