### ISSUE TITLE
Rashy Era does not show up in 1.16 database

### ISSUE THREAD

**Issue by Vyncyn** [wesnoth/wesnoth#7578]
### Game and System Information

- **Version: 1.16.1**
- **Downloaded from: Wesnoth homepage**
- **Build info:**
- **OS: Windows**

### Description of the bug

Rashy Era was released on 1.16 for a while and visible in https://units.wesnoth.org/1.16/mainline/en_US/mainline.html
After an update of the UMC, the era disappeared from the database and following text can be seen in the database build report (https://units.wesnoth.org/1.16/Rashy_Era/error.html):

> 
> Warning: No race "None" found (None).
> Error: Era 'era_R_aoh' faction 'Chevalier' references non-existant unit id 'VRCe Holy Knight'!
> Warning: Unit id=null not found as advancement of 'VRHR White Mage'
> 
> please report as bug
> can only concatenate str (not "NoneType") to str

A new update has already been done, which should fix the Holy Knight and White Mage errors. Not sure if the era will be visible in the database when it's refreshed

### Steps to reproduce the behavior

Unlear what caused this error. It can still be seen at https://units.wesnoth.org/1.16/Rashy_Era/error.html (status 30.4.2023)

### Expected behavior

Era from the UMC shoud be visible in the wesnoth 1.16 unit database

**Comment by Pentarctagon** [comment]
That seems normal? There was an error with the era, so it showed an error.

**Comment by ProditorMagnus** [comment]
Just like wesnoth should not crash, wmlunits should not crash. In case of `<WML ERROR>` it is addon author responsibility, in case of `<INTERNAL ERROR>` it is wmlunits responsibility.

**Comment by Pentarctagon** [comment]
Ah, alright. So the error is not so much that the era isn't showing up, it's that wmlunits shouldn't crash when this issue happens?

If so, then it would be useful to know what the fix made in the era was as well.

**Comment by ProditorMagnus** [comment]
Fix wont happen except accidentally until this issue has progress.

**Comment by Pentarctagon** [comment]
The report says:
> A new update has already been done, which should fix the Holy Knight and White Mage errors.

**Comment by ProditorMagnus** [comment]
Since publicly available error message doesnt tell anything about crash reason, if it is also fixed that was accident.

**Comment by Pentarctagon** [comment]
Oh, I see - the:
> please report as bug
> can only concatenate str (not "NoneType") to str

is entirely unrelated (probably) to the:
> Warning: No race "None" found (None).
> Error: Era 'era_R_aoh' faction 'Chevalier' references non-existant unit id 'VRCe Holy Knight'!
> Warning: Unit id=null not found as advancement of 'VRHR White Mage'

**Comment by Slayer95** [comment]
Rashy Era is now visible in the database. The underlying crash has also likely been fixed by https://github.com/wesnoth/wesnoth/pull/7580 .

**Comment by Slayer95** [comment]
Yes. If a similar issue arises in the future, then it should be reported - the error log will then include a couple of stack frames for better debugging.
