### ISSUE TITLE
Secrets of the Ancients: 4. Becalmed (intro text) Just who are "the living ones" needing food?

### ISSUE THREAD

**Issue by joeljpa** [wesnoth/wesnoth#7611]
### Language

English but I'm guessing all of them

### Source

Secrets of the Ancients: 4. Becalmed (intro)

### Original Text

The journey started well enough, but on the dawn following our departure, the wind died completely, and we were stranded. There was enough food for the paying passengers for a couple days of this, but none for my companions, **and the living ones soon got hungry.** When one of the crew disappeared on the second evening, I suspected the cause. I was not wrong.

### Proposed Change

It's not clear to the player just who exactly are the living ones with her. It might be obvious to some that it's her bats? But if that's the case, it's awkward narration to refer to just her tiny bats as the living ones as if that's a big diverse group. Might as well mention them explicitly. 

I think it was intended to refer to her ghouls as well, that makes sense -- but they aren't living so that's the problem here. I don't know if this game's lore consider Walking Corpses as needing food ("brainssssss")?

Maybe change to something like "and the ones who needed sustenance grew restless"?

**Comment by stevecotton** [comment]
The ghouls are living, that's what the "one of them didn't survive" in the previous message means. All the bandits except that one did unfortunately "survive".

**Comment by Wedge009** [comment]
It reads clearly to me, but then English is my first language.

@nemaara Comments?

**Comment by nemaara** [comment]
For me it's not the most clear (I mean I can understand it but have to read twice) but that's a byproduct of English grammar rather than bad wording I guess?

**Comment by nemaara** [comment]
SotA kind of implies that they are halfway between living and undead, which matches their in game stats as well. "One of them didn't survive" I read as meaning she failed to make the ghoul properly, so she turned the corpse into a skeleton instead.

**Comment by Wedge009** [comment]
I'm not sure of the classification of all units, but would predecessors to liches (dark mages, etc) also be considered part of the 'undead' faction? Practitioners of dark arts may still be living but are conveniently classified as undead.

Even the Help description of undead seems to express a degree of ambiguity with respect to classification:
> Undead are not really a single race of creatures, although often treated as such.

Hmm... after all that, it seems there's a distinction between race and faction. Dark Adept/Sorcerer would be in the undead _faction_, but they are still of the human race until they advance to Lich when they become classed as undead _race_.

**Comment by joeljpa** [comment]
> Hmm... after all that, it seems there's a distinction between race and faction. Dark Adept/Sorcerer would be in the undead _faction_, but they are still of the human race until they advance to Lich when they become classed as undead _race_.

Exactly. By _race_, a ghoul, necrophage or ghast is undead along with skeletons etc. They aren't living while sorcerers and bats of the Undead _faction_ are.

> "One of them didn't survive" I read as meaning she failed to make the ghoul properly, so she turned the corpse into a skeleton instead.

Yes, no ambiguity here. Reads quite clearly. Just that I kept wondering just who were these "living ones" aboard when I read the latter part while playing.

> SotA kind of implies that they are halfway between living and undead, which matches their in game stats as well.

Then by this, I leave it to you to close this. If no one seems to have felt what I did, then I guess it's trivial compared to this narrative that SotA carries.

**Comment by nemaara** [comment]
I'll leave it open a couple more days but if there's no other comments I think this can be closed.

**Comment by nemaara** [comment]
I'll leave it open a couple more days but if there's no other comments I think this can be closed.

**Comment by Wedge009** [comment]
Closing as per last remark.
