### ISSUE TITLE
Some strings not translated on attack dialog

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7612]
### Game and System Information

All

### Description of the bug

These string does not exist in any of the po files

![imagen](https://user-images.githubusercontent.com/40789364/236917418-9a027d0d-9509-4d9c-965b-8a3d5859c80e.png)

https://github.com/wesnoth/wesnoth/blob/a9ed25e694d1d06116df91bbdeb235218ac6f1ed/src/gui/dialogs/unit_attack.cpp#L145
https://github.com/wesnoth/wesnoth/blob/a9ed25e694d1d06116df91bbdeb235218ac6f1ed/src/gui/dialogs/unit_attack.cpp#L160
https://github.com/wesnoth/wesnoth/blob/594f5b3d8911fb387a13fd4728451a857ecae2b8/src/units/abilities.cpp#L915
https://github.com/wesnoth/wesnoth/blob/594f5b3d8911fb387a13fd4728451a857ecae2b8/src/units/abilities.cpp#L918
https://github.com/wesnoth/wesnoth/blob/594f5b3d8911fb387a13fd4728451a857ecae2b8/src/units/abilities.cpp#L921

**Comment by Wedge009** [comment]
These are not the only places where `dsgettext` is used. As mentioned in #7618, the `po` files should be including this string but it's not, at least for the moment. I don't know why this would happen.

**Comment by Toranks** [comment]
Same problem with 
"Owned: "
"Taught: "
"Taught: (by an enemy): "

The first can be seen on the same screenshot, above.
All of them from the attack dialogue.

**Comment by CelticMinstrel** [comment]
> These are not the only places where `dsgettext` is used. As mentioned in #7618, the `po` files should be including this string but it's not, at least for the moment. I don't know why this would happen.

Maybe that file isn't parsed by xgettext? Or `dsgettext` isn't recognized as a translatable string?

The three extras that Toranks posted are a completely different problem, as they're not even marked as translatable at all.
