### ISSUE TITLE
Graphical glitches with custom lua dialogs

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7617]
### Game and System Information

The Battle for Wesnoth version 1.17.16 x86_64
Running on Microsoft Windows 7 Service Pack 1 (6.1.7601) x86_64
Distribution channel: Steam

Libraries
=========

Boost:             1.81
Lua:               5.4.4
OpenSSL/libcrypto: 3.0.0h-dev (runtime 3.0.0h-dev)
Cairo:             1.17.8 (runtime 1.17.8)
Pango:             1.50.14 (runtime 1.50.14)
SDL:               2.26.3 (runtime 2.26.3)
SDL_image:         2.6.3 (runtime 2.6.3)
SDL_mixer:         2.6.3 (runtime 2.6.3)

Features
========

Lua console completion:       yes
Win32 notifications back end: yes

Current video settings
======================

SDL video drivers:        [windows] offscreen dummy
Window size:              1920x1080
Game canvas size:         1920x1080
Final render target size: 1920x1080
Screen refresh rate:      60
Screen dpi:               96.00x96.00
Renderer:                 direct3d (hw)
Maximum texture size:     16384x16384
VSync:                    on

Current audio settings
======================

SDL audio drivers:  [wasapi] directsound winmm
Number of channels: 2
Output rate:        44100 Hz
Sample format:      signed 16 bit little-endian
Sample size:        4096 bytes

Installed add-ons
=================

A_New_Order:                  1.5.0
Advance_Wesnoth_Wars_fork:    1.17.16
Akladian_Music:               1.0.1
An_Orcish_Incursion:          1.0.3
Dead_Bodies:                  1.3.3
Dead_Bodies_terrain:          1.0.2
Eastern_Invasion_Dalas:       2.3.18
Era_of_Magic:                 4.0.3
Era_of_Magic_Resources:       2.0.0
Gui_Debug_Tools:              0.10.3
Knyght_RotD:                  1.0.4.1
Legend_of_the_Invincibles:    Unknown
Non_Fatal_Wounds_Extended:    3.3.5
Reflection:                   1.2.4
Spartan:                      0.0.0
To_Lands_Unknown:             3.7.0
To_Lands_Unknown_Resources_1: 2.1.0
To_Lands_Unknown_Resources_2: 2.0.0
Unitmarker:                   1.0.6
combat-info-theme:            0.0.7

### Description of the bug

When a menu window is generated with lua immediately after another, these graphical glitches occur. Since I don't know if it has a generic cause or not, or it's related with any other issue, I'll leave it here with a video for the record of exactly how it happens.
It doesn't seem to happen with windows generated by wesnoth himself, like in preferences.

### Steps to reproduce the behavior

See the video. I'm usign Legend of the Invincibles, but happens with any addon with lua custom menus.

https://github.com/wesnoth/wesnoth/assets/40789364/67fbcf74-24b5-428d-98cc-0ecb8851bfa8

**Comment by Wedge009** [comment]
Does this happen at all with 1.16? Looks like a redraw problem to me.

**Comment by Wedge009** [comment]
So perhaps a product of the graphics overhaul introduced (I think) in 1.17.6.

**Comment by Toranks** [comment]
Something similar happens with normal dialogs too. It's rare to see, but for example you can see it in the new achievement dialog:

![imagen](https://github.com/wesnoth/wesnoth/assets/40789364/2bfec86e-7a34-4729-97b9-7f393f47491d)

**Comment by Wedge009** [comment]
The specific issue you noted with normal dialogues on 24th May 2023, I think that's already reported in #3942.

It may be that the redraw issues you're observing here are related, though.

**Comment by mesilliac** [comment]
I don't know anything about how these windows draw, but as a suggestion probably whatever is drawing them simply needs to mark its area of screen for redraw when it closes or resizes the dialog, and isn't doing so.

**Comment by gfgtdf** [comment]
Is this actually reroducable ?

**Comment by gfgtdf** [comment]
> See the video. I'm usign Legend of the Invincibles, but happens with any addon with lua custom menus.

The loti dialog code is really complicated, it'd be better if we had a simpler example.

**Comment by gfgtdf** [comment]
I didnt dig super deep into the loti gui2 code, but it looks a bit like what seems to be two dialogs in the video of the first post, is actually one big shapeshfting dialog.

**Comment by gfgtdf** [comment]
> Something similar happens with normal dialogs too. It's rare to see, but for example you can see it in the new achievement dialog:

Imo even with this fixed this is still bad design of the achievement dialog, it shouldn't change its size, when another   campaign is selected.

**Comment by Pentarctagon** [comment]
It's not just the achievements dialog - it's just the easiest way to reproduce it. See #3942 for that issue. I wasn't able to find any way to prevent a window from shrinking in size.
