### ISSUE TITLE
Latest version for windows marked as 1.16.8 on sourceforge

### ISSUE THREAD

**Issue by superusercode** [wesnoth/wesnoth#7630]
### Game and System Information

n/a

### Description of the bug

![image](https://github.com/wesnoth/wesnoth/assets/60588434/ccb899a9-356d-4ee7-bf8e-508742347599)
The latest version indicated by sourceforge is 1.16.8 despite 1.16.9 being present. Having the latest version mislabeled prevents community package managers like scoop, winget, and chocolatey from grabbing an up to date version.

### Steps to reproduce the behavior

n/a visit https://sourceforge.net/projects/wesnoth/files/wesnoth-1.16/

### Expected behavior

"Latest version 1.16.9"

### Additional context

Actual behavior: "Latest version 1.16.8"

**Comment by Pentarctagon** [comment]
I don't think we control that latest version button?

**Comment by Pentarctagon** [comment]
The "Download Now" button on https://www.wesnoth.org/ does, since that's something I update with each release.

**Comment by Pentarctagon** [comment]
What are you writing the regex for?

**Comment by Pentarctagon** [comment]
Ah, alright. It sounds like this can be closed then? The html for https://www.wesnoth.org/ of course isn't guaranteed to stay identical forever, but nevertheless it's probably the best option available.
