### ISSUE TITLE
Consistency between `priority` attributes (int vs double) (positive vs negative as higher)

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7631]
We currently have open PRs that add new `priority` attributes, as well as some existing things that are a similar concept. I'm not sure the stuff below is an exhaustive list, however I want to ask what our standard should be. We seem to already have a consistent rule for high numbers going first, with only some open PRs going the other way. I think integers vs floating-point is an open question, but I might already be on the losing side (I'd prefer signed ints, even if that means add-ons that want to allow other add-ons to interoperate will use numbers in the same range as the Micro AIs).

The RCA AI and Micro AI's [`ca_score`](https://wiki.wesnoth.org/RCA_AI#The_Candidate_Actions_.28CAs.29_of_the_main_loop_Stage_in_the_RCA_AI) is "higher goes first", using ints in an unbounded range, with common well-defined actions in the range 1000-200000. These might be signed.

The Lua `on_event` implementation already in 1.16 is "higher goes first", seems to accept anything that the Lua `<` operator recognises (so would accept doubles), however the only values used by callers of that function are `-1`, `0`, and `1`.

PR #7582 is "higher goes first" and allows negative numbers. Currently using doubles.

PR #7003 and PR #7484 have to change. Not the author's fault, as he's had a committee asking for changes, but it's ended up with lower numbers generally being higher priority, however zero being lower priority than any positive number.

Feature request #3136 will be affected, but can just follow what's decided here.

FormulaAI's `priority` is documented as "higher goes first", without documenting details. It's deprecated anyway.

Ping @CelticMinstrel @gfgtdf @Slayer95 @newfrenchy83.

**Comment by gfgtdf** [comment]
When i added it to on_event, i originally wanted to name `order` but i renamed it to `proirity` because priority for me implies that the higher number goes first, while `order` doesn't give any hint about whether higher or lower number goes first, so i thought priority was more self explaining. (When though higher priority doesn't mean here it's more important, just that it's execute first)

> PR #7003 ..

Here the situation is different, it's not really about an order of execution of things, but rather about which thing is active, i dont see how any thoughts regarding "order of things" apply here. The thing with the highest priority should be active and all the others are not.

**Comment by newfrenchy83** [comment]
if existent priority attribute and other PR use "higher goes first", then i must change that in my PR

**Comment by CelticMinstrel** [comment]
For people porting older scenarios, FormulaAI's priority would map to ca_score, for what it's worth.

**Comment by stevecotton** [comment]
The int vs float question looks like it will get more discussion in #7583, and there seems to be consensus on the higher vs lower question, so I'm closing this.

**Comment by CelticMinstrel** [comment]
> The RCA AI and Micro AI's [`ca_score`](https://wiki.wesnoth.org/RCA_AI#The_Candidate_Actions_.28CAs.29_of_the_main_loop_Stage_in_the_RCA_AI) is "higher goes first", using ints in an unbounded range, with common well-defined actions in the range 1000-200000. These might be signed.

I just noticed that you appear to have a misconception here. Candidate action scores, despite the large values, are also floating-points numbers, though I believe negative numbers are not allowed as zero indicates the CA is disabled.

**Comment by stevecotton** [comment]
Candidate action scores are validated to be `s_unsigned` by the schema, and I've just checked that.
```
error validation: Invalid value '210001.4' in key 'ca_score=' in tag [micro_ai]
```

While the Lua treats them as `number`, that seems to be integer when (as is the case) every value is an integer. There's also only one place where they're tested for equality, in a loop inside ca_high_xp_attack.lua (where it can only be integer).

**Comment by soliton-** [comment]
Seems like that shows using floating point adds nothing useful in practice.
