### ISSUE TITLE
[1.17] if side 1 is empty, side 2 will start with 2 turns

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#7633]
1) Create a MP game
2) Set side 1 to nobody
3) Make your turn with side 2
4) After ending your turn, you can end it again. Your units won't have their moves replenished, but side turn events happen. E.g. with ANL things can be done twice.

In later turns, this will not happen.
If you set instead side 2 to nobody, it will also not happen.

1.17.16+dev 594f5b3d891

**Comment by Pentarctagon** [comment]
Does this happen with earlier versions? Like 1.17.12 or .10?

**Comment by sevu** [comment]
It is something new, maybe dd9fccc

**Comment by Pentarctagon** [comment]
@gfgtdf

**Comment by sevu** [comment]
It's not that, 3fa5fde is the oldest I tested and it also happens there.

I used 1.17.13+dev for quite some time, there I did not notice that.

**Comment by gfgtdf** [comment]
I cannot test it right now since I'm not on my computer but  i think what happens is that, `next_player_number_` stil points to player 2 because it was set to `current_player +1` before current_player was corrected to 2 because side 1 is empty.

**Comment by gfgtdf** [comment]
Could you test whether it still happens if you insert a `gamestate_->next_player_number_ = gamestate_->player_number_ + 1;` at the beginning of `play_controller::do_init_side()` ?

**Comment by sevu** [comment]
This does the trick

**Comment by gfgtdf** [comment]
Ok thx i'll commit that as soon as I can can u less someone else wants to do it. (I tried on my phone but u think the autocorrection prevents me from editing code)

**Comment by sevu** [comment]
I committed it, but please have a look at it again. I don't know if it interacts with the line above it.

I'm also not sure if there is still a corner case.

**Comment by gfgtdf** [comment]
> I committed it, but please have a look at it again. I don't know if it interacts with the line above it.

Thx, Looks good to me,  the line above also just sets a simple variable  so the order doesn't matter here. The change also makes sense to me (determine the next playing side in the current turn not in the previous turn) even if it wouldn't fix something, we should probably remove the old `gamestate_->next_player_number_ = gamestate_->player_number_ + 1;` line in  finish_turn as it's no longer needed (although it won't do any harm either so not urgent, i can do it when I'm back on my pc)

> Not that i can think of rn 🤔, do_init_side is always called  before a turn can be ended. Of course it is not called when we reload a mid-turn savegame, but in that case we also want to use whatever next_sude_turn was in the same game since mid-turn saves should always have that written.
