### ISSUE TITLE
UtBS S03: Were Garak's dreams a long-standing prophecy?

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7634]
### Language

English

### Source

UtBS S03 Stirring in the Night

### Original Text

"I had dreams **of** this night Kaleh, full of gloom and darkness, my journey will end here one way or another."

### Proposed Change

This is a suggestion to revert 4248738a3894df4a551debd4ff6afff4e68ffe49, which added "of" to that sentence; although that commit is titled "minor correction", it significantly changes the meaning. The scenario starts at `LONGDARK4`, with the moon on the schedule picture about to make way for dawn; Garak says the line on turn 2, at which point the player knows that dawn hasn't come yet, but doesn't know that it won't come at turn 12.

"I had dreams this night" means that Garak has had the visions while they were camped here, but he hasn't known about this in advance.

"I had dreams of this night" implies multiple visions long before this. Given that it's not the only place with ruined castles in the desert it's understandable that he didn't warn Kaleh against camping here, but it opens the question of why he doesn't warn about the schedule change at turn 12.

**Comment by Wedge009** [comment]
I honestly don't remember why I added that. I can only think that, at the time, reading it as it was didn't make sense to me. But yes, you are right, they are quite different meanings.

I'm happy for you to revert the change for master and 1.16.

**Comment by Zireael07** [comment]
I had dreams this night (or tonight) doesn't make sense to me. Why is him having dreams so important to be mentioned in this dialogue? I would keep the "of' which clearly implies visions/prophecy, and add some line about their vagueness to explain why no warning about the schedule change

**Comment by stevecotton** [comment]
Because the dreams lead him to ask (and get) a cursed buff from Zhul: enchant his weapon with fire and with a `berserk` special that's only active when fighting against the enemy sides' champions. Also, for plot reasons he dies in combat this scenario, even if the player manages to win the scenario before turn 12 while keeping him alive.

**Comment by stevecotton** [comment]
> 'I had dreams this night' still reads awkwardly to me. The original text was committed 15 years ago... I'm not sure what to do about this. Would 'I had dreams tonight' still carry the intended meaning or does it sound too casual/modern?

It doesn't sound right. I'm wondering about other wordings, and whether it would be better to add some detail about the vision. Maybe even a foreshadowing with a description of Eloh that's slightly different to the portrait that appears in S08 - not majorly, just enough for a player replaying the campaign to notice.

Time to ping @nemaara.

**Comment by nemaara** [comment]
If I had to guess, the original text from long ago probably meant for Garak to have the "multiple visions" about the night but I kind of agree that it doesn't seem fitting (especially since Garak isn't a mystic or anything) and is an oft used cliche.

One way is to make the line "I had a dream this night, Kaleh, full of gloom and darkness. My journey will end here one way or another." This implies that he just had said dream which the player probably can guess was a byproduct of the undead lords literally being on their doorstep so of course his dream was gloomy like that.

**Comment by knyghtmare** [comment]
Am I the only person not bothered by this? 

"I had dreams of this night Kaleh, full of gloom and darkness, my journey will end here one way or another."

I mean there's really nothing wrong with it. Like, to an ESL it's interpreted as:

"He had nightmares about instances he is seeing now and in these nightmares he dies. He had these recurrent nightmares many times and the result was the same each time."

Reverting this just sounds like promoting bad English.

**Comment by stevecotton** [comment]
@knyghtmare that's the correct interpretation of the "of" version, but the question is whether it makes sense for him to have had these dreams before.

I like @nemaara's version. It does seem a bit archaic, which doesn't fit with Garak's other dialog; but having it be a ceremonial phrase fits with the way that Zhul checks if he's sure, but doesn't check whether she's correctly understood the request.

**Comment by Wedge009** [comment]
Making a singular 'had a dream this night' instead of the original 'had dreams this night', sounds like it conveys the original meaning better while avoiding implications of Garak being some sort of mystic.

**Comment by Wedge009** [comment]
So the po comments were added but we're leaving the statement-in-question alone? Is it unreasonable to change it to 'had a dream this night' now, as previously suggested, as the po comment states it will be addressed for 1.18?

**Comment by nemaara** [comment]
Any objections to changing it to my version for 1.18?
