### ISSUE TITLE
Improve vision and jamming tooltip

### ISSUE THREAD

**Issue by Toranks** [wesnoth/wesnoth#7636]
### Describe the desired feature

If a unit vision is different from movement points or have jamming points, apparently this appears in the UI (vis...) Hovering the mouse over shows nothing.

![imagen](https://github.com/wesnoth/wesnoth/assets/40789364/c8d1589a-1e5a-4128-b8e8-896278eef8f6)

Replacing "Vision:" with a empty space on my language translation, shows a number.

![imagen](https://github.com/wesnoth/wesnoth/assets/40789364/f8a35730-15dc-4cc4-963c-60e83a34fdcc)

So it looks like it uses the status UI to put
`Vision: X`
Or
`Jamming: X`

https://github.com/wesnoth/wesnoth/blob/454d816c86e1669cfcacb56a744aae9f2f37321e/src/reports.cpp#L643

But there is no space for it.
It must be some old code from a different UI than the current one.
I suggest doing something like (JP VP =Jamming or Vision points)
```
VP/JP
X/X
```
It should be a very simple change to the code, and it improves an unusable part of the current UI.

**Comment by Wedge009** [comment]
#6021 seems related.
