### ISSUE TITLE
xgettext warnings

### ISSUE THREAD

**Issue by Slayer95** [wesnoth/wesnoth#7667]
### Game and System Information

- **Version:**
Master

### Description of the bug

``translations`` CI workflow produces several warnings when running ``xgettext`` over C++ files.

### Additional context

> src/ai/composite/component.cpp:137: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/editor/map/map_context.cpp:159: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/editor/map/map_context.cpp:175: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/editor/map/map_context.cpp:181: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/editor/map/map_context.cpp:645: warning: a double-quote in the delimiter of a raw string literal is unsupported
/usr/bin/xgettext: warning: msgid 'The following add-on appears to have publishing or version control information stored locally, and will not be removed:' is used without plural and with plural.
                            src/gui/dialogs/addon/manager.cpp:856: Here is the occurrence without plural.
                            src/addon/manager_ui.cpp:192: Here is the occurrence with plural.
                            Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
/usr/bin/xgettext: warning: msgid 'The following add-on could not be deleted properly:' is used without plural and with plural.
                            src/gui/dialogs/addon/manager.cpp:864: Here is the occurrence without plural.
                            src/addon/manager_ui.cpp:202: Here is the occurrence with plural.
                            Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
src/server/campaignd/server.cpp:104: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/server/campaignd/server.cpp:104: warning: unterminated string literal
src/server/campaignd/server.cpp:120: warning: unterminated string literal
src/tests/gui/test_gui2.cpp:736: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/tests/gui/test_gui2.cpp:736: warning: unterminated string literal
src/tests/gui/test_gui2.cpp:738: warning: unterminated string literal

**Comment by Pentarctagon** [comment]
Locally I get the warnings:
```
src/tests/gui/test_gui2.cpp:736: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/tests/gui/test_gui2.cpp:736: warning: unterminated string literal
src/tests/gui/test_gui2.cpp:738: warning: unterminated string literal
src/ai/composite/component.cpp:137: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/server/campaignd/server.cpp:104: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/server/campaignd/server.cpp:104: warning: unterminated string literal
src/server/campaignd/server.cpp:120: warning: unterminated string literal
src/editor/map/map_context.cpp:159: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/editor/map/map_context.cpp:175: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/editor/map/map_context.cpp:181: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/editor/map/map_context.cpp:645: warning: a double-quote in the delimiter of a raw string literal is unsupported
```
which generally seem to be due to it incorrectly handling string literals. ie: the ones in `src/editor/map/map_context.cpp` and `src/ai/composite/component.cpp` are regular expressions.
