### ISSUE TITLE
Allow an event definition to filter scenario/campaign id

### ISSUE THREAD

**Issue by demario-w** [wesnoth/wesnoth#7668]
### Describe the desired feature

Allow a modification to define an event where the campaign id and scenario id can be used to filter when the event should be executed (besides all the [filter]s and first_time_only).

The use cases are:
- allow a modification to modify the difficulty of a certain scenario on the fly
- allow a modification to fix an existing event to behave more purposefully/correctly
- allow these changes to be optional based on whether the modification is enabled or disabled

**Comment by ProditorMagnus** [comment]
It is already possible.

**Comment by stevecotton** [comment]
Example code from Non Fatal Wounds: https://github.com/stevecotton/Non_Fatal_Wounds/blob/master/utils/campaigns.cfg

**Comment by stevecotton** [comment]
@demario-w is there anything more required here?

**Comment by demario-w** [comment]
> Example code from Non Fatal Wounds: https://github.com/stevecotton/Non_Fatal_Wounds/blob/master/utils/campaigns.cfg

This one looks very hack-y and it is surprising that we are told to spread that code across addons.

The code:
```ini
# From https://github.com/stevecotton/Non_Fatal_Wounds/blob/master/utils/campaigns.cfg

#define SCENARIO_ADDITIONAL_EVENT EVENT_NAME SCENARIO_ID WML_ACTION
[event]
    name={EVENT_NAME}
    [lua]
        # This seems to be readable only via Lua
        code=<<
            wml.variables["nfw_current_scenario_id"] = wesnoth.scenario.id
        >>
    [/lua]
    [if]
        variable=nfw_current_scenario_id
        equals={SCENARIO_ID}
        [then]
            {WML_ACTION}
        [/then]
    [/if]
    {CLEAR_VARIABLE nfw_current_scenario_id}
[/event]
#enddef

{SCENARIO_ADDITIONAL_EVENT ("side 1 turn 1 end") ("02_escape") (
[move_unit]
    id=Malica
    to_x,to_y=10,10
[/move_unit]
)}
```
gets executed during scenario with id=01_death

> @demario-w is there anything more required here?

I was looking for a one-liner setting.

**Comment by demario-w** [comment]
> > Example code from Non Fatal Wounds: https://github.com/stevecotton/Non_Fatal_Wounds/blob/master/utils/campaigns.cfg
> 
> This one looks very hack-y and it is surprising that we are told to spread that code across addons.
> 
@stevecotton could it be that the different #ifdef you're using in that code make it looks like it is working better than it is?

**Comment by ProditorMagnus** [comment]
Store the variable in prestart and rest of addon just use [filter_condition][variable]

**Comment by demario-w** [comment]
> Store the variable in prestart and rest of addon just use [filter_condition][variable]

Thanks, the new code seems to be working fine:
```ini
# Inspired from https://github.com/stevecotton/Non_Fatal_Wounds/blob/master/utils/campaigns.cfg

#define SCENARIO_ADDITIONAL_EVENT_PREPARATION
[event]
    name=prestart
    [lua]
        # This seems to be readable only via Lua
        code=<<
            wml.variables["nfw_current_scenario_id"] = wesnoth.scenario.id
        >>
    [/lua]
[/event]
#enddef

#define SCENARIO_ADDITIONAL_EVENT EVENT_NAME SCENARIO_ID WML_ACTION
[event]
    name={EVENT_NAME}
    [filter_condition]
        [variable]
            name=nfw_current_scenario_id
            equals={SCENARIO_ID}
        [/variable]
    [/filter_condition]

    {WML_ACTION}
[/event]
#enddef
```

**Comment by stevecotton** [comment]
Hmm - now that I look at it, it could be reduced further using `[filter_condition][lua]`.

**Comment by ProditorMagnus** [comment]
[lua] is documented to not be designed for that. https://github.com/ProditorMagnus/Ageless-for-1-14/blob/master/lua/preload.lua#L38C1-L46C4

**Comment by stevecotton** [comment]
Thanks.

If I'm reading that doc right, then it sounds like `[lua]` would be okay for NFW's intended purpose of checking only infrequent events (`die`, `local_victory`, `capture` but maybe not the `moveto` used for LoW S19). However, as NFW is also being used as the example to copy, I guess ought to do it like AE_is_rpg instead.

**Comment by CelticMinstrel** [comment]
It's fine to use `[lua]` in a `[filter_condition]`, but I wouldn't recommend doing it unless it's a condition that you only need exactly once. Defining a custom conditional, or putting it into a variable, are both probably better approaches than that for something that will be needed in many places.
