### ISSUE TITLE
Using Elevation in existing maps

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#7691]
It would look good to make use of the new Lowered/Elevated Terrain feature in existing campaigns.

- An explanation of the new feature is in the in-game help in the section for the Map and Scenario Editor (in the Terrain Editor subgroup)
- An example map is in multiplayer: "3p - Elevation Test"
- Screenshots are in #6975 and #6927

Generally, campaign maps can be updated for new graphics or even bigger changes.

**Comment by doofus-01** [comment]
I should mention that #7669 might be relevant, if it gets completed in time.  If there are specific use-cases in mainline maps, that would be helpful to know.
