### ISSUE TITLE
UtBS S08, S09: Zhul and Kaleh refer to the merfolk's "master"

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7695]
### Language

English

### Source

UtBS S08 and S09

### Original Text

08_Out_of_the_Frying_Pan.cfg:

* "You don’t know where to find your master?"

09_Blood_is_Thicker_Than_Water.cfg:

* "No, too many merfolk have died! There are not enough of them left to divine the location of their master. We should have protected the merfolk more carefully. Now our search is hopeless."
* "Too many merfolk have died! Even if we save the rest, there will not be enough for them to divine the location of their master. We should have protected the merfolk more carefully. Now our search is hopeless."

### Proposed Change

Should change to "leader" to match Esanoo's dialogue; in 1.15.4 the merman's dialogue changed "master" to "leader" or "wise leader". See f405b916a1141c2a4bc3bda3f88bbe0a8b8fe91b and https://github.com/wesnoth/wesnoth/pull/4950#issuecomment-647060510 .

I'm logging this as a reminder to myself - I'm currently writing a lot of `# po:` comment improvements which I intend to merge to 1.16, but this change shouldn't be included with those.

**Comment by Wedge009** [comment]
Similar to #7634, any reason why we can't make these changes in 1.17 now?

**Comment by stevecotton** [comment]
No reason to wait. I was confused and waiting for my `# po` adding PRs to merge, but have just realised that the UtBS PRs have already merged - I was confused and waiting for the WC PRs.

If you want to take over then that's good too, I'll take a few days before I have time.
