### ISSUE TITLE
Editor should recognise map_file in scenario files

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7699]
### Describe the desired feature

The editor has some support for opening a scenario file, if it uses the old-style map_data attribute. If the file uses `map_data={FILENAME_OF_MAP}`, then the editor will automatically redirect itself to opening the map file instead.

However, the editor does not recognise `map_file=FILENAME_OF_MAP`, and it will instead produce some cryptic error message as it tries to interpret WML as terrain codes.

**Comment by Pentarctagon** [comment]
I'm actually working on some changes to the editor at the moment, and this is something that will be fixed with that. Because yeah it's a bit odd that Wesnoth's own editor can't understand the mainline scenario cfg files.

**Comment by Pentarctagon** [comment]
Yeah, locally I have the editor regex warnings from xgettext fixed by just not using regex there anymore.

**Comment by Pentarctagon** [comment]
Addressed by #7719
