### ISSUE TITLE
[1.17] A status change is not immediately visible in the sprite

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#7709]
Changing a unit's status often comes with a graphical change. Currently on 1.17:
1) Change a unit's status with `:unit status=petrified` (or poisoned).
2) _Unit sprite is not yet gray_, standing animations still play (e.g. for the Jinn unit)
3) Click the unit. Then the graphics are updated.

**Comment by ProditorMagnus** [comment]
Debug-only or normal status change too?

**Comment by gfgtdf** [comment]
Is this new in 1.17?

**Comment by sevu** [comment]
Debug-only.
New in 1.17 because there was the switch to hardware acceleration.

**Comment by Wedge009** [comment]
I could not replicate this in current master, 9e61449562a. I also had no such issue with 1.16.9 release, 1.17.6 tag, 1.17.7 tag. Tested on Linux/X11. Tested units with standing animations and those without.

Was there a specific unit you encountered this with?

**Comment by Wedge009** [comment]
Okay, here is what I can confirm: the unit shading changes from neutral to green for poisoned or grey for petrified immediately upon the debug-command. But for petrified only, the only issue I see is the unit animations still playing, which obviously doesn't make sense for a petrified unit. The issue subject implied that the unit colour shading was not showing, but it seems like that's not the actual issue - is that a correct assessment?

**Comment by Wedge009** [comment]
Clarifying the animations, some units like the loyalist halberdier and orc archer, have standing animations that show intermittently. Introduced in 1.17 were 'breeze' animations, showing small things like the tail on the orcish grunt's helmet moving in the breeze. The latter, I observe still playing after debug-petrification. The former, I have not.

**Comment by doofus-01** [comment]
Some of this might be related to #7551.  I'll look into it.

**Comment by doofus-01** [comment]
Looked into it with recent master, and:
 - The Jinn was an oversight on my part, easy to fix, need to check if there is anything else where it matters more (i.e. can be poisoned)
 - The idle animations (belching ogre, for example) don't play when the units are petrified.
 - The standing animations (bobbing skeleton, for example) play for a petrified unit that was made that way via debug, then get no interaction to refresh, and it stops eventually.  That seems pretty niche and low priority, does it happen in a real use case, like a `[petrify]` direct action?

**Comment by Wedge009** [comment]
@sevu Can you review master now that #7725 has been merged?

**Comment by doofus-01** [comment]
#7725 wouldn't solve the artificially petrified unit standing animations issue, just whether the sprites turned gray or not.

**Comment by Wedge009** [comment]
Yes, but I think that is sufficient for 'normal' use.

**Comment by sevu** [comment]
It's fixed, the way doofus describes it.
The issue was less the original report by me but the Jinn.

**Comment by Wedge009** [comment]
So if this is issue is specifically about the Jinn being missed I think it can be closed.

I think the issue about animations not ceasing for debug status changes is fine as-is - if others object that should probably be a separate report.
