### ISSUE TITLE
map editor--forest on hills

### ISSUE THREAD

**Issue by rmj555** [wesnoth/wesnoth#7714]
### Game and System Information

- 1.16.8
- Windows 10

### Description of the bug

When a forest is put on a hill, the hill is gone and one gets forest on flat surface.  This was not the case long ago.

**Comment by soliton-** [comment]
Make sure to use shift to place overlays. Give specific steps to reproduce what you think goes wrong.

**Comment by knyghtmare** [comment]
Try `shift+click` and then you get your desired result.

**Comment by rmj555** [comment]
Shift+click accomplishes what I want, but this brings up two issues.

First:  I can put desert plants on hills without shift+click, so why not forests.

Second:  I do not see instructions that say shift+click is the way to do this, unless it is the "paint base layer only."  "Paint base layer only" may mean something to someone into tech, but to a layman its confusing.

**Comment by soliton-** [comment]
Wesnoth terrains consist of two layers a base and an overlay. "paint base layer only" means only replace the base layer on the map and "paint overlay layer only" means only replace the overlay layer.

Some terrains just define an overlay or base. Using shift or not makes no difference then.
