### ISSUE TITLE
GUI.pyw should have a "cancel" button before running wmllint on the core directory

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7728]
### Describe the desired feature

Start GUI.pyw and press the "run" button (with the wmllint tab open). It will show the message
```
You didn't select a directory.

wmllint will be run only on the Wesnoth core directory
```

Feature request: that dialog should have a cancel button. See also #5799 for the changes that the tool is about to create (yes, you can cancel it after it starts, but it's still a cleanup job afterwards).

**Comment by tymnec** [comment]
Hey, @stevecotton I would like to try and add this feature.

**Comment by stevecotton** [comment]
Welcome to the project, @tymnec. For the Python tools, @Elvish-Hunter is the main maintainer, and @Slayer95 is currently the most active developer on them; I'm pinging them to let them know that you're looking at this feature.

Generally we don't assign tickets in this project, we just check comments to see if someone's working on it.

**Comment by Elvish-Hunter** [comment]
This one should be pretty easy to implement.
The warning message quoted by @stevecotton is displayed using the `showwarning()` function in the `tkinter.messagebox` module; the same module contains several other functions and `askokcancel()` looks like the best option. In this last case, I also suggest to set the dialog's icon to `icon=WARNING`.
@tymnec Would you still like to try implementing this feature?

**Comment by tymnec** [comment]
@Elvish-Hunter Yup I will implement it by today 😃
