### ISSUE TITLE
--screenshot doesn't work

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#7747]
From bisecting, this stopped working as of cdfadff142b706a8bb177ec1ca8ea088bcec9dc8, now giving the error:
`Failed to create a SDL_Renderer object. Error »Couldn't find matching render driver«.`

**Comment by mesilliac** [comment]
I actually meant to fix this but completely forgot about it. It does require a renderer now. Should be fixed by #8004

**Comment by Pentarctagon** [comment]
Thanks!
