### ISSUE TITLE
Liberty, S4 Unlawful Orders, nameless enemies have names

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#7748]
### Game and System Information

- **Version:** 1.17.18

### Description of the bug

When the enemies transform from undead to humans, they are assigned a name. The intention of this scenario is that they all are nameless. (I believe it's an oversight.)
![name(less)](https://github.com/wesnoth/wesnoth/assets/39015360/6dd9253f-a242-41ad-89af-f8b912984219)

### Steps to reproduce the behavior

Start S4 of Liberty, wait a day/night circle, and notice that 'old' units now have names.

### Expected behavior

The units are supposed to stay nameless, even when transforming back into humans.
[Liberty-Unlawful Orders replay 20230630-193748.gz](https://github.com/wesnoth/wesnoth/files/11919664/Liberty-Unlawful.Orders.replay.20230630-193748.gz)

**Comment by Toranks** [comment]
04_Unlawful_Orders, line 759:

`generate_name=yes`

Maybe changing this to `=no`

**Comment by Konrad22** [comment]
> 04_Unlawful_Orders, line 759:
> 
> `generate_name=yes`
> 
> Maybe changing this to `=no` solves the problem

That's seems likely, I think it's just a leftover from 1.16, when the units had names.

**Comment by Wedge009** [comment]
So this is specific to 1.17? I don't recall enemy transformation in 1.16 and earlier.

**Comment by Wedge009** [comment]
Confirmed, yes, it seems to be something introduced for 1.17 that the enemies - including the leader - have no names but names are given when returning to human form.

**Comment by Wedge009** [comment]
> `generate_name=yes`
> 
> Maybe changing this to `=no` solves the problem

This turned out to be insufficient. I tried to find out why names are still being generated and how to stop that from happening, but it seems I'm not understanding the WML fully.

**Comment by Wedge009** [comment]
A-ha, `generate=no` needs to be applied to all cases. Submitting a PR shortly.
