### ISSUE TITLE
Liberty, S6 The Hunters, typo in unit move animation

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#7751]
### Game and System Information

- **Version:** 1.17.18

### Description of the bug

The move animation of the Shadow Mage is off by one hex.

### Steps to reproduce the behavior

Load the scenario, skip the talk, and watch the Shadow Mage move into position. He moves to the hex of the Rogue Mage, instead of his own.

### Expected behavior

Shadow Mage moves to 32,9 instead of 31,9.

### Additional context

https://github.com/wesnoth/wesnoth/blob/db239ecf16bb7c2eb51545ce732c67bf08abf2fb/data/campaigns/Liberty/scenarios/06_The_Hunters.cfg#L468C1-L472C1

**Comment by Wedge009** [comment]
Yeah, looks like a copy-paste issue. Fortunate that Wesnoth can handle hex collisions already, but best to not rely on that and fix it in the code.
