### ISSUE TITLE
DiD, S3, map is shrouded anew after Malins relflecting

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#7758]
### Game and System Information

- **Version:** 1.17.18

### Description of the bug

After you reach the end of the map, Malin has to confront himself, and summons a ghost. After that, he returns to the 'normal' map, which is now mostly shrouded, including Darken Volk.

### Steps to reproduce the behavior

Load the save, get through the introspection, check how Darken Volk is no longer visible.
[DiD-A Haunting in Winter-Auto-Save141.gz](https://github.com/wesnoth/wesnoth/files/11929464/DiD-A.Haunting.in.Winter-Auto-Save141.gz)

### Expected behavior

Either the map not being shrouded anew, or shared vision with Darken Volk, so he isn't speaking from the dark.

**Comment by Konrad22** [comment]
(Technically this also applies to S10 Descent into Darkness, but it's not (as much of) a problem, as Malin is alone in that scenario, so no weird voice from nowhere.)

**Comment by Wedge009** [comment]
This seems to have been caused by 4a5f38c5755da9e4ab3511f1daf2e3987e33d9f7 by @nemaara as part of #7515. Even if I added the redraw of side 3, because Darken Volk is assigned 0 MP for the duration of the scenario, the redraw doesn't do anything for him because he has no MP to 'see' with.

**Comment by Wedge009** [comment]
> ...this also applies to S10 Descent into Darkness...

I was confused again - Descent into Darkness is S9. Can you describe which part of the scenario your shroud issue applies?

**Comment by Konrad22** [comment]
> I was confused again - Descent into Darkness is S9. Can you describe which part of the scenario your shroud issue applies?

Sorry, I keep mixing up the numbers and names. I do mean S9, Descent into Darkness.
There is a reflection pool at 29,33, which triggers a reflection scene like in S3.

**Comment by Wedge009** [comment]
Ah yes, I see. This one is mid-scenario so potentially you could have a lot of viewed hexes 're-shrouded'. But I agree it's not a major issue.
