### ISSUE TITLE
DiD, typo AMLA Mal Keshar

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#7767]
### Game and System Information

- **Version:** 1.17.18

### Description of the bug

+1 dmg shadow wave AMLA grants +2 damage

### Expected behavior

AMLA grants as much dmg as the description says, and very likely the intention is only +1 dmg.

### Additional context

https://github.com/wesnoth/wesnoth/blob/b86b6efd0e55451bd08760dc02343aaf729ddce4/data/campaigns/Descent_Into_Darkness/utils/amlas.cfg#L300C1-L308C18

**Comment by Wedge009** [comment]
Agreed, introduced by @nemaara in #4479. Maybe a mistake that just got missed in the large scale of the change.
