### ISSUE TITLE
Heroes disappear between scenarios

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#7769]
### Game and System Information

- **Version:*1.17-1.17.18*
- **OS:*Windows*

### Description of the bug

Heroes disappear between levels

### Steps to reproduce the behavior

Play / debug thru level 1. At the start of level 2 only 0/1/2 heroes spawn. It is random, depends on really anything even on map changes, in the current build most common is only 1 spawning. 

First sightings: 
After 404th line in wml-tags.lua change: 

-        utils.vwriter.write(writer, u.__cfg)
+        utils.vwriter.write(writer, ucfg)

But even reverting that stopped working for me at some point. 

### Expected behavior

Heroes spawn without losing levels. 

### Additional context

https://github.com/wesnoth/wesnoth/assets/41817546/8c4cc5d5-83f9-4e97-9375-922152ebc36c

(The [unstore_unit] warrining doesnt matter here.) 

Test version with 2 scenarios:
[Mercenaries.zip](https://github.com/wesnoth/wesnoth/files/11952582/Mercenaries.zip)

**Comment by gfgtdf** [comment]
I tested this in 1.16 and 1.17 the way its is shown in the video and saw no difference in behavior, so its not clear to me what the bug is

**Comment by Hejnewar** [comment]
At the start of scenario 2, both heroes should appear, not just one. The bug was introduced / backported back in 1.16 so there is no way there would be a difference between these two.

**Comment by gfgtdf** [comment]
Okay, i think i know what happens, but next time please upload a minimal testcase rather than a addons that contains many files. . You can debug by gradually removing parts of your code/addon until the bug disappears, then we know at least somewhat where the bug is since usually debugging code that we didn't wrote ourselves its quite hard for us.

In this specific case the bug should disappear once you remove the merc_no_upkeep "unit placed" event. And the commit that changed the behaviour is probably https://github.com/wesnoth/wesnoth/commit/13c5d8a96ead8d2a7f0435f60b8ec7f7e0af0972 .

**Comment by Wedge009** [comment]
Switching labels, because I understand Campaign refers to official campaigns not add-ons.

**Comment by Pentarctagon** [comment]
A clearer description would also help. When I saw

> Heroes disappear between levels

my first though was "what levels? are World Conquest heroes disappearing between scenarios now?"

**Comment by Wedge009** [comment]
Yeah, I was trying to work out which campaign it was, at first.

**Comment by Hejnewar** [comment]
>  but next time please upload a minimal testcase

Problem with this was that minimal test cases worked fine for me everytime and this consistently worked not fine with very high rate of reproduction of the bug.  

> In this specific case the bug should disappear once you remove the merc_no_upkeep "unit placed" event.

Honestly I would have never guessed, we actually tried doing that but we limited ourselves to events that actually spawn them and the behviour was very inconsistent with pretty much any change creating different behaviour. 

> You can debug by gradually removing parts of your code/addon until the bug disappears, then we know at least somewhat where the bug is since usually debugging code that we didn't wrote ourselves its quite hard for us.

I understand that and thank you for your work, I guess our approach was wrong form the beginning then.

**Comment by gfgtdf** [comment]
pushed a commit that should fix it (its 1.17 only though, so for 1.16 you probably have to modify your wml)

**Comment by Hejnewar** [comment]
Works! Thanks.
