### ISSUE TITLE
UtBS S2: Missed XP from Lost Souls event when killing multiple units

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#7771]
### Game and System Information

- **Version:** 1.17.18

### Description of the bug

This scenario has a night event, where 'Lost Souls' spawn. If you destroy number of them during a night, all of them will disappear until the next night.
Now, if, 
by using an aoe attack (in my case the Sun Singer ray attack), 
I kill multiple Ghosts with the same hit of the attack, 
pushing me over the limit of Ghosts I have to kill that night,
then I only get xp for having attacked a Ghost, not for killing said Ghost.

TL, DR:
Edge case of scenario mechanics and aoe attacks can lead to losing out on xp.

### Steps to reproduce the behavior

1. Go to S2 of UtBS, get a Sun Singer/Sylph, and line up two Ghosts. (possibly by using the provided save)
2. Make sure that you are 1 Ghost away from scaring the Ghosts away.
3. Kill both Ghosts with the Ray attack of the Sun Singer, at the same time, with the same hit.
[UtBS-Across the Harsh Sands Turn 6.gz](https://github.com/wesnoth/wesnoth/files/11957829/UtBS-Across.the.Harsh.Sands.Turn.6.gz)

### Expected behavior

Expected behavior depends a bit on how the aoe mechanics will be nailed down, but base line is, that xp for the kill on the primary target is awarded.

(I'm unclear if kill xp is to be given when a secondary target is killed, or xp at all for hitting the secondary target.)

### Additional context

No idea what kind of title would be helpful for this.

**Comment by Wedge009** [comment]
The problem of the Lost Souls event aside, I wonder also about the implementation of attacks that can target more than one hex/unit. I tested in another UtBS scenario and if a ray attack kills one L1 enemy the unit is given the standard 8 XP. If the ray attack kills two L1 enemies, then the unit is still only given the standard 8 XP for killing one L1 unit. It's a separate issue to what's described here, but I would expect that the unit would be granted 2 x 8 XP.

@Hejnewar This seems to have been introduced by you in #7349, included from 1.17.13. Any thoughts on this specific issue and/or the general XP loss?

**Comment by Konrad22** [comment]
> The problem of the Lost Souls event aside, I wonder also about the implementation of attacks that can target more than one hex/unit. I tested in another UtBS scenario and if a ray attack kills one L1 enemy the unit is given the standard 8 XP. If the ray attack kills two L1 enemies, then the unit is still only given the standard 8 XP for killing one L1 unit. It's a separate issue to what's described here, but I would expect that the unit would be granted 2 x 8 XP.
> 
> @Hejnewar This seems to have been introduced by you in #7349, included from 1.17.13. Any thoughts on this specific issue and/or the general XP loss?

(That's not necessarily the full or right answer, but for some context.)
I asked some questions about that, starting here: https://discord.com/channels/231976805987385345/259976436490829825/1126117511780372571

> Konrad
did I verify correctly that the aoe dmg is not supposed to grant xp, or is this an oversight for now?

> Hejne
It is supposed to give you xp (for secondary targets hit/killed)

> Konrad
should secondary targets get xp for having been hit?

> Hejne
no idea and I'm actually fine with both ways.

> Konrad
What kind of xp should be granted in aoe attacks?

> Hejne
Unit gets normal XP for the first target and XP for secondary target if it is killed.
Getting XP for every target attacked* with nova would be broken

**Comment by Wedge009** [comment]
So it would appear that the current implementation of these multi-target attacks is not working as intended with respect to XP.

**Comment by Hejnewar** [comment]
I think Im going to download first wesnoth version that had new quenoth added after fixes just to see if it worked there because I remember being very happy about getting multikill xp and I believe I tested this quiet a bit cuz I did find some bugs after release, it would be weird if I didnt notice this. Still possible tho.

**Comment by Hejnewar** [comment]
Even in current version xp works correctly except for enemies that disappear during being killed.

**Comment by Wedge009** [comment]
What is your 'current' version? When I tested in 1.17.18+dev XP wasn't being awarded correctly (separate from the Lost Souls event).

**Comment by Wedge009** [comment]
Reported the general XP problem in #7776.

**Comment by Hejnewar** [comment]
Works correctly now
