### ISSUE TITLE
In-game fonts render absolutely massively in fullscreen (Pop!_OS)

### ISSUE THREAD

**Issue by Ophiolith** [wesnoth/wesnoth#7773]
### Game and System Information

- **Version:** 1.16.9
- **Downloaded from:** Steam, Flathub, Ubuntu repo
- **OS:** Pop!_OS 22.04 LTS

### Description of the bug

Fairly self-explanatory, when in full-screen, the in-game font approximately triples in size to the point where it is borderline obstructive to playing. The font size returns to normal when the game is windowed. The game also crashes when switching to windowed from full-screen but not vice-versa.

### Steps to reproduce the behavior

1. Install Wesnoth through any supported method on Pop!_OS
2. Run game
3. Toggle full-screen on and off

### Expected behavior

Full-screen font size
![image](https://github.com/wesnoth/wesnoth/assets/24281932/dcf43e77-bbb2-443a-9a9e-eb532683ff36)
Windowed font size, intended
![image](https://github.com/wesnoth/wesnoth/assets/24281932/b278d684-48f6-45e2-9461-39c256c75203)

**Comment by Wedge009** [comment]
At first I thought this was to do with the auto-scaling, but that was (re-)introduced in 1.17 and this is referring to 1.16. Do you find the same thing if trying 1.17? Any chance you know or could find out if this happens for you on other distributions? Is this a fresh installation - eg do you happen to have a pre-existing Wesnoth `preferences` file? (On my system it's in `~/.config/wesnoth/preferences`)

**Comment by Wedge009** [comment]
That crash on switching to full-screen suggests something odd/wrong with Pop!_OS. I certainly don't have that on Kubuntu or Windows. Looks like Pop! uses GNOME by default?

**Comment by Wedge009** [comment]
Can you also post your log file from when this occurs? The language button in the bottom-right should be showing the currently selected language - I assume 'Language' is a default fall-back.

**Comment by Ophiolith** [comment]
> At first I thought this was to do with the auto-scaling, but that was (re-)introduced in 1.17 and this is referring to 1.16. Do you find the same thing if trying 1.17? Any chance you know or could find out if this happens for you on other distributions? Is this a fresh installation - eg do you happen to have a pre-existing Wesnoth `preferences` file? (On my system it's in `~/.config/wesnoth/preferences`)

I've not tried 1.17 yet - I need to sleep just now but I'll report back when I've had a chance to install and test.

I've also tested 1.16.9 on Debian 12 stable via a VM and the issue is not present there, neither is it if I run the Windows build via Proton / Steam. I tried deleting my configuration file and it made no difference - it seems to be something that's automatically triggering when the game detects I've entered full-screen, as it stays with the correctly scaled font for just a second before switching after I toggle full-screen on.

wesnoth.log does not contain any particularly useful info
[wesnoth.log](https://github.com/wesnoth/wesnoth/files/11962755/wesnoth.log)

I'm afraid I'm not able to find any reasonably simple way to view stderr, as it's not logged to a file on Linux best I can tell, and running the game via Steam obfuscates any terminal output, sorry.

**Comment by irydacea** [comment]
It would be highly useful to see the clipboard report from the version info dialog (from the main menu, click on the i button on the bottom left, then click on the copy button in the bottom left of the resulting dialog).

As for stderr, please see this forum thread for info about obtaining logs on Linux with the Steam version: https://forums.wesnoth.org/viewtopic.php?t=46166

**Comment by Wedge009** [comment]
No worries, there's no rush as it appears no-one else has reported this issue (that I'm aware of).

It does sound like it's something specific to the Pop!_OS environment then. If only for the sake of ruling out variables, can you report what you're running by clicking the 'i' icon in the bottom-left corner of the main menu and switching to the 'Libraries' tab (there's a copy function button in the bottom-left corner of the dialogue)?

Oh, so you were able to get a log file anyway. Looks like there's nothing odd being reported there.

**Comment by irydacea** [comment]
The log file looks like it was taken in the Debian VM because it doesn't match the screen resolution seen in the pictures.

**Comment by Ophiolith** [comment]
> It would be highly useful to see the clipboard report from the version info dialog (from the main menu, click on the i button on the bottom left, then click on the copy button in the bottom left of the resulting dialog).

Please see below, noticed the scaling proportions seem a bit odd, could potentially be a lead? @Wedge009 Library info is in there too :)
[wesnoth popos system info.txt](https://github.com/wesnoth/wesnoth/files/11965814/wesnoth.popos.system.info.txt)

> The log file looks like it was taken in the Debian VM because it doesn't match the screen resolution seen in the pictures.

The pictures I uploaded were cropped, so don't represent my desktop / window resolution

**Comment by Ophiolith** [comment]
I've now tested in Flatpak 1.17 nightly, and the issue does not reproduce there. Given this is the case, if you're happy to list this as 'will be fixed in 1.17', then I'm fine to close this and use either 1.17 unstable builds or Proton in the meantime :)

**Comment by soliton-** [comment]
> Screen dots per inch:    94.146721x857.250000
Screen dpi scale factor: 0.980695x8.929688

The second numbers look quite odd there.

**Comment by Ophiolith** [comment]
> > Screen dots per inch:    94.146721x857.250000
> > Screen dpi scale factor: 0.980695x8.929688
> 
> The second numbers look quite odd there.

Yeah, on re-testing on 1.17, the comparable info dialog differs:

> Screen dpi:               94.15x857.25

A scale factor isn't defined in this one. Seems like there could be something wonky in how 1.16 is determining scaling.

**Comment by irydacea** [comment]
1.17 just rounds up the numbers for display but internally they're still the same. The core issue here is that the vertical dpi is abnormally large (857 vertical vs 94 horizontal).

Could you try checking and copying in a terminal emulator the output of `xdpyinfo`? (If it says command not found, first use `sudo apt install x11-utils` to install the file providing it)

**Comment by Ophiolith** [comment]
@irydacea Sure, here you go
[xdpyinfo.txt](https://github.com/wesnoth/wesnoth/files/11966689/xdpyinfo.txt)

**Comment by Wedge009** [comment]
While 1.17 includes major graphics revisions, both it and 1.16 still rely on `SDL_GetDisplayDPI` for screen DPI information. Which is part of why I wanted to double-check the library dependencies - for what it's worth, what was listed matches the 1.16.9 release I have installed.

Indeed, it appears the problem is caused by the bizarre DPI reported under Pop!. The [SDL documentation](https://wiki.libsdl.org/SDL2/SDL_GetDisplayDPI) includes this note:
> **WARNING:** This reports the DPI that the hardware reports, and it is not always reliable! It is almost always better to use [SDL_GetWindowSize](https://wiki.libsdl.org/SDL2/SDL_GetWindowSize)() to find the window size, which might be in logical points instead of pixels, and then [SDL_GL_GetDrawableSize](https://wiki.libsdl.org/SDL2/SDL_GL_GetDrawableSize)(), [SDL_Vulkan_GetDrawableSize](https://wiki.libsdl.org/SDL2/SDL_Vulkan_GetDrawableSize)(), [SDL_Metal_GetDrawableSize](https://wiki.libsdl.org/SDL2/SDL_Metal_GetDrawableSize)(), or [SDL_GetRendererOutputSize](https://wiki.libsdl.org/SDL2/SDL_GetRendererOutputSize)(), and compare the two values to get an actual scaling value between the two. We will be rethinking how high-dpi details should be managed in SDL3 to make things more consistent, reliable, and clear.

It might be worth reporting this issue to libsdl maintainers for the Pop! project, but otherwise this problem seems external to Wesnoth. Even the `xdpyinfo` report seems to show more sensible DPI information. Vertical DPI is multiplied by an order of 10 for some reason?

**Comment by Ophiolith** [comment]
> While 1.17 includes major graphics revisions, both it and 1.16 still rely on `SDL_GetDisplayDPI` for screen DPI information. Which is part of why I wanted to double-check the library dependencies - for what it's worth, what was listed matches the 1.16.9 release I have installed.
> 
> Indeed, it appears the problem is caused by the bizarre DPI reported under Pop!.

> It might be worth reporting this issue to libsdl maintainers for the Pop! project, but otherwise this problem seems external to Wesnoth. Even the `xdpyinfo` report seems to show more sensible DPI information. Vertical DPI is multiplied by an order of 10 for some reason?

Oh wow, that's... hmmmm. Yeah, tbh I'm not altogether surprised but thank you for looking into this! I will close this off just now as this is clearly a Pop! issue. Thank you for all the help, folks!

**Comment by irydacea** [comment]
I'd be careful about blaming Pop OS. Odds are that it's the driver (or the monitor's EDID) that's reporting numbers incorrectly. The fact that it doesn't happen in a VM doesn't mean anything because VMs emulate their own GPU and monitors independently of the host's.

It's tempting to consider SDL's advice here though.

**Comment by Wedge009** [comment]
> I'd be careful about blaming Pop OS.

What have you actually tested, @Ophiolith, in terms of 'bare metal' installation? Perhaps I mis-read/mis-understood what you're actually testing. Do you have another monitor to test with, perhaps? Would it be too much of a burden to try another OS on another partition or a separate drive on the same machine? All I can see, based on what I understand of your experience, is that SDL is incorrectly reporting DPI under your particular set-up.

**Comment by Ophiolith** [comment]
> What have you actually tested, @Ophiolith, in terms of 'bare metal' installation? Perhaps I mis-read/mis-understood what you're actually testing. Do you have another monitor to test with, perhaps? Would it be too much of a burden to try another OS on another partition or a separate drive on the same machine? All I can see, based on what I understand of your experience, is that SDL is incorrectly reporting DPI under your particular set-up.

I borrowed another monitor and tested on that, and I can't reproduce the issue. You're almost certainly right that it's SDL or, potentially Xorg, misreporting my monitor's resolution. I'm pretty convinced now that this is a real corner case, as I've re-tested since on other computers I have kicking about, and no other configuration I've tried has exhibited this.

**Comment by Wedge009** [comment]
Good to know. So it sounds like we can conclude it's an oddity with SDL reporting DPI on that particular monitor.
