### ISSUE TITLE
Artefact from recolored Wood Elves Quenoth, incomplete blessing of Glaive (UtBS S3)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#7774]
### Game and System Information

- **Version:** 1.17.18

### Description of the bug

When Garak decides to duke it out with the Undead Champions, Zhul blesses his weapon, turning his damage type to fire...on the attack that dealt blade damage previously.

It seems to be a leftover from 1.14, when Garak only had bladed melee attacks, so that filter would work for 100% of his attacks. (Refer to the additional context, the intention was to avoid overwriting possible arcane dmg.)
SInce 1.15 Garak has had pierce damage as well, which stays pierce even after the blessing, as the filter only works on blade attacks.
A piece of code that was overlooked, when the Quenoth had their first rework.

### Steps to reproduce the behavior

1. Get to UtBS S3.
2. Wait a turn.
3. Check Garaks damage types.

### Expected behavior

All attacks deal fire damage. (+, he only has that one weapon xD)

### Additional context

```
            [effect]
                apply_to=attack
                range=melee
                # the type=blade is needed in case Garak picked up the holy
                # water in the second scenario - in that case he gets to keep it
                type=blade
                set_type=fire
            [/effect]
```
https://github.com/wesnoth/wesnoth/blob/80b26dbb431e0fa0996bffdec55a2f5909753b2d/data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg#L710C1-L717C22
[UtBS-A Stirring in the Night-Auto-Save2.gz](https://github.com/wesnoth/wesnoth/files/11971778/UtBS-A.Stirring.in.the.Night-Auto-Save2.gz)

**Comment by Wedge009** [comment]
I'm guessing that's version 1.17.18 not .8. I last played UtBS on 1.16 - has there been a lot of changes to it for 1.17?

Just so I understand properly (the title isn't quite clear on this), your concern is that the change to fire damage should be for all of Garak's melee attacks?

**Comment by Konrad22** [comment]
> I'm guessing that's version 1.17.18 not .8. I last played UtBS on 1.16 - has there been a lot of changes to it for 1.17?
> 
> Just so I understand properly (the title isn't quite clear on this), your concern is that the change to fire damage should be for all of Garak's melee attacks?

Yes, it is. Also, the artefact has is from 1.14, the bug has been present since 1.15.

**Comment by Wedge009** [comment]
> ...the code that changed the damage type worked for 1.14, the bug has been present since 1.15.

I haven't tested 1.14, but I observe Garak changed from Desert Captain (blade melee + pierce ranged) to Quenoth Champion (blade melee) in #810 (included in 1.13.6), with the addition of pierce melee in f8f091cc2ece331f01411301b3f58121717ae175 (1.13.7). So I imagine 1.14 would also exhibit this oversight.

**Comment by Konrad22** [comment]
> > ...the code that changed the damage type worked for 1.14, the bug has been present since 1.15.
> 
> I haven't tested 1.14, but I observe Garak changed from Desert Captain (blade melee + pierce ranged) to Quenoth Champion (blade melee) in #810 (included in 1.13.6), with the addition of pierce melee in [f8f091c](https://github.com/wesnoth/wesnoth/commit/f8f091cc2ece331f01411301b3f58121717ae175) (1.13.7). So I imagine 1.14 would also exhibit this oversight.

Yes, you are correct. It seems I made a wrong assumption there, the bug is older than expected.

**Comment by stevecotton** [comment]
Reopening as a reminder about the backport.

**Comment by Wedge009** [comment]
672519726dc7c43f7a79bf504eaf309bd8a345a7
