### ISSUE TITLE
UtBS: Attacks killing multiple enemies only awards XP for the first kill

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#7776]
### Game and System Information

- **Version:** 1.17.18+dev (at ae76ddff686)
- **Downloaded from:** GitHub
- **Build info:** SCons
- **OS:** Linux but presumably all

### Description of the bug

General case for, and related to, #7771.

#7349 introduced attacks targeting multiple enemies in 1.17.13 for the Quenoth Sun Singer/Sylph units. They may have worked at some point between 1.17.13 and 1.17.18, but as of 1.17.18+dev XP for enemies killed doesn't appear to be working correctly. The Sun Singer has a 'ray' attack that can hit a unit behind a target, while the Sun Sylph also has a 'nova' attack that can hit units adjacent to a target. An attack that kills more than one unit is supposed to award XP for all units killed but currently only XP from the first unit killed is gained.

### Steps to reproduce the behavior

The whole 'first/second/third verse' mechanic isn't explained at all. Eventually I worked out from the unit definitions that it seems to be related to how many attacks the Sun Singer/Sylph has made before it is allowed access to the subsequent 'verse' attacks, they are not available immediately from the start. So to simplify things I've prepared an XP test scenario: 
[xp-test.gz](https://github.com/wesnoth/wesnoth/files/11988805/xp-test.gz) (I'm guessing GUI Debug Tools may need to be installed.)

The Sun Singer at 13,24 is already primed for her 'ray' attack. Use it against the mudcrawlers - compare killing one at a time and killing both together. Observe her XP before and after the attacks and observe that killing two mudcrawlers together only counts the XP from the first mudcrawler killed.

### Expected behavior

In this particular set-up, the Sun Singer's XP should increase by 12: 8 from the Giant Mudcrawler, 4 from the Small Mudcrawler.

### Additional context

From the log:
```
ERROR: TYPE ERROR: expected string but found null (null())
  unit_at
  direction_from

formula type error: TYPE ERROR: expected string but found null (null())
```

Looks like something might have broken?

**Comment by Wedge009** [comment]
I checked out and compiled tag 1.17.13 and the behaviour appears to be the same. So it seems unlikely XP was working correctly for this new multi-target mechanic.

**Comment by Hejnewar** [comment]
Yeah, I see it doesnt I see (I tested on fog cleaners and was thinking they are lvl 0). But for tests I would just make a unit with just the specials without verse special.

**Comment by stevecotton** [comment]
[direction_from](https://wiki.wesnoth.org/Wesnoth_Formula_Language#direction_from) takes a third argument, which is the distance in that direction. So instead of a complicated filter using `[filter_adjacent]`, it could be filtering for `unit_at(self.loc, self.facing, 2)`.

`[harm_unit]experience=yes`'s documentation says "if there is a harmer". The `[harm_unit]` call in question doesn't have a `[filter_second]`, so it doesn't know which unit is attacking.
