### ISSUE TITLE
Trigger unit_hits, unit_misses events

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#7782]
### Describe the desired feature

Purpose of new events is to cover use case where same functionality should be done in attacker_hits and defender_hits, but only difference is whether to use unit/second_unit related attributes and filters. With unit_hits primary unit is always the one doing current strike.

I got this idea from petrified event.

**Comment by ProditorMagnus** [comment]
Underlying issue is that defender_hits primary and secondary units are swapped, if event is called defender hit then defender should be the primary unit. But should not change API needlessly, so better as new event.

**Comment by CelticMinstrel** [comment]
I'm a bit confused at what you're saying. Aren't the units opposite in attacker_hits vs defender_hits?

**Comment by ProditorMagnus** [comment]
attacker hits: unit=the one who hits
defender hits: unit=the one who doesnt hit

**Comment by soliton-** [comment]
I think the idea is that usually what you want to implement has the same logic for the unit hitting and not for the unit that initiated the attack. So you have to write the logic twice once for unit and once for second_unit. If the primary unit was always the one hitting then you would just need to write it once.

**Comment by ProditorMagnus** [comment]
Yes. One example https://github.com/ProditorMagnus/Ageless-for-1-14/blob/master/data/ME_data/weapon_specials/triplestrike.cfg

**Comment by stevecotton** [comment]
Seems a good idea, a little invasive to implement into the current code in src/actions/attack.cpp but it's better to do it in one place in the engine than many places in UMC.

I think another alternative would be to leave the events for `attacker_hits` and `attacker_misses` as-is, but add `defender_hits_reversed`, and `defender_misses_reversed`, with the two units swapped. That would make `[event]name=attacker_hits, defender_hits_reversed` effectively the same as `[event]name=unit_hits`. Which method is better could be left as an implementation detail for now, to be decided when it gets implemented.

**Comment by CelticMinstrel** [comment]
I don't think I like the alternative proposal. Actually, if we're doing this at all, I think we might as well deprecated the attacker/defender events. The unit hit/miss event can just have an auto-stored variable that specifies whether the unit striking is the attacker or the defender; so an `attacker_hits` event would become a `unit_hits` event with `[filter_condition]is_attacker=yes`, and a `defender_hits` event would become a `unit_hits` event with `[filter_condition]is_attacker=no`.

You could even go a step further and make hit/miss an auto-stored variable too, so you have only one event, maybe something like `unit_strike`. I'm not sure if this step further is a good idea though.

**Comment by ProditorMagnus** [comment]
I disagree with deprecation.

**Comment by CelticMinstrel** [comment]
Why? A deprecation doesn't affect anyone. That's the entire point of doing it, so that no-one is affected. And it doesn't make sense to have two completely different ways of doing the same thing.

**Comment by soliton-** [comment]
I think the event names are fine. Just unfortunate that the defender events are not from the perspective of the defender.

Perhaps we could add an attribute to change that? Not sure how best to word it. Maybe `primary_unit=defender` with `primary_unit=attacker` being the default.

**Comment by CelticMinstrel** [comment]
> If you mean `[event]primary_unit=defender`, then I think it's more confusing than using a new event name.

It wouldn't be great if intended as an API. It could be fine though if intended as a transitional period to deprecate the original form of the event.

1.18: add `primary_unit=defender|attacker`, defaults to attacker, warns if missing
1.20: now defaults to defender, error if missing
1.22: `primary_unit=attacker` is now ignored and generates a warning; `primary_unit=defender` generates a different warning

**Comment by ProditorMagnus** [comment]
Main problem with primary_unit is that it can be included in event with multiple names. I asked for new event instead of changing defender_hits exactly to avoid the transitions and deprecations.

**Comment by stevecotton** [comment]
Where would the mechanism for implementing `primary_unit=defender` go? This seems to be heading in the direction of either "hardcode it in the wrong layer" or feature-creep to "let the caller of `fire()` provide an additional filter", both of which seem more complex than "add another event".

src/actions/attack.cpp would be a logical place to switch the data, but it is just calling `game_events->pump().fire(...)`. It doesn't know how many `[event]name=defender_hits` events have been registered, and even if it did, the existing `fire` function doesn't let it choose to only trigger the subset with the right value of `primary_unit=`.

The game_events framework would be able to check for `primary_unit=`, and `wml_event_pump::process_events` could be a logical place for "swap the units before filling in the `x1,x2,y1,y2,first,second,first,second_weapon`". However, I'd prefer to keep that layer as free as possible from logic such as "if the event is called `defender_hits` and `primary_unit=defender` then do something special".

**Comment by soliton-** [comment]
Right, looks like an event specific attribute is not great. And making more variables available to those events is probably not useful either?

Seems like event name is the only thing to adjust... but `defender_hits_primary` sounds like the defender hits the primary unit, i.e. the attacker, which sounds like how it works now. Can't really imagine we can find a good name so then making a complete alternative with unit_hits/misses as CelticMinstrel described seems like the only way to a nicer API. Not sure that's worth it.

**Comment by soliton-** [comment]
Well, making more variables available should be possible but it means making alternative variables with good names for: x1, y1, x2, y2, unit, second_unit, weapon, second_weapon

**Comment by CelticMinstrel** [comment]
> Well, making more variables available should be possible but it means making alternative variables with good names for: x1, y1, x2, y2, unit, second_unit, weapon, second_weapon

Ah, are you suggesting just keeping the current events but adding more auto-stored variables? That doesn't seem like it works for the purpose of the event filters though…

**Comment by soliton-** [comment]
Right, would also require corresponding alternative filter tags.

**Comment by ProditorMagnus** [comment]
Solved with https://github.com/wesnoth/wesnoth/commit/081866af7b5d52394ad5eaadedc19a364e0b8b35
