### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [wesnoth/wesnoth#7802]
### Game and System Information

Is it possible next time on release new version make the github release to have entry on https://github.com/wesnoth/wesnoth/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by Wedge009** [comment]
#7803
