### ISSUE TITLE
New Editor (#7719) breaks quick reload (F5)

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#7810]
### Game and System Information

- **Version:**
- Battle for Wesnoth v1.17.19+dev (c2ad332b21d-Modified) x86_64 (includes staged `src/modules/lua (new commits)` somehow?  I didn't touch those...  EDIT: I see it's a link to a different source tree)
- **Downloaded from:**
- here
- **Build info:**
- scons
- **OS:**
Linux

### Description of the bug

Multiple bugs, some are minor, at least one is not: 
 1.  When starting map editor, the new menu "Add-on Selection" menu pops up.  Click "show all" check-box, and any folder in the add-ons folder becomes an option, including temporary or "attic" folders that you could formerly use to disable or hide data.
 2.  It does not seem to matter what you choose, for the map editor - select "Mainline", and UMC terrain shows up just like before.  UMC terrain being available is actually good, so you can still load more than one dependency if you want, but then why did we have to deal with the new menu?
 3.  From the plain grass map, hit F5 to reload.  Or draw something before F5, it doesn't matter.  This leads to two issues:  (A) instead of quickly being brought back to the loaded map(s), you get the "Add-on Selection" menu again; (B) after the menu, the game exits with 
 ```
error editor: Editor exception in editor::start: File does not have .map or .cfg extension
Game error: File does not have .map or .cfg extension
```

### Steps to reproduce the behavior

See above

### Expected behavior

1.  Only show add-ons (folder contains `_main.cfg`?)
2.  Don't make the new menu pop up for the map editor?  Or make the menu do something, but if you do that, allow multiple selections and let it remember previous selections
3. Reloading a map with F5 shouldn't bring up the new menu and it shouldn't cause the game to exit

### Additional context

Rapidly reloading with F5 is a must-have for terrain development/tinkering, placing menus and speed-bumps in there should be avoided.  From what I see, the new feature is getting loaded too soon, it should only be for the scenario editor and should not be involved with the map editor.

**Comment by doofus-01** [comment]
@Pentarctagon  - I'd say this is high priority, even if it doesn't break things for most players.

**Comment by CelticMinstrel** [comment]
I think I'd also say that the optimal solution might be to scrap the in-editor F5 system and re-implement it from scratch. It's architected wrong in the first place, and there are other issues with it as well. Especially given the new form of the editor that requires selecting an add-on, maybe it shouldn't fully reload the editor but instead just reinitialize everything with updated data, or something.

**Comment by Pentarctagon** [comment]
> It does not seem to matter what you choose, for the map editor - select "Mainline", and UMC terrain shows up just like before. UMC terrain being available is actually good, so you can still load more than one dependency if you want, but then why did we have to deal with the new menu?

I'm not sure I understand the question? This isn't for loading dependencies, it's for determining which _server.pbl to look at for the pbl editor dialog and setting the default directory when first saving a map or a scenario (and potentially more things in the future). How the editor is made aware of UMC content hasn't changed.

**Comment by Pentarctagon** [comment]
> includes staged src/modules/lua (new commits) somehow? I didn't touch those... EDIT: I see it's a link to a different source tree

Lua was updated, so you need to update the submodule with `git submodule update --init --recursive`.

**Comment by CelticMinstrel** [comment]
> This isn't for loading dependencies

The dependency comment is an aside and not related to the actual issue here. I think he's saying it makes sense for _all_ content to _always_ be loaded in the editor, as you may want to add a dependency to your add-on… though with the new editor it actually makes some sense to change that so only the declared dependencies are loaded. However that might be quite a huge change.

**Comment by Pentarctagon** [comment]
At the very least it would make sense to warn about it in some way. It never made much sense to me that you could create a scenario in the editor only to get missing terrain, unknown unit, etc errors when you go to actually play it. IMO that'd be a separate issue though.

**Comment by doofus-01** [comment]
> I'm not sure I understand the issue? This isn't for loading dependencies, it's for determining which _server.pbl to look at for the pbl editor dialog and setting the default directory when first saving a map or a scenario (and potentially more things in the future). It's essentially just choosing the add-on you're currently working on or to initialize a new one. How the editor is made aware of UMC content hasn't changed.

You start up the map editor, you are confronted with a menu that asks you to select an add-on (or start a new one, or mainline).  What is the point of that?  I would have thought it determines what is available in the map editor.  But it does not.  Thankfully, it does nothing.

**Comment by Pentarctagon** [comment]
I mean, I explained what it currently does in the comment you quoted.

**Comment by doofus-01** [comment]
Right, so why are you making us go through that useless menu?

**Comment by doofus-01** [comment]
> At the very least it would make sense to warn about it in some way. It never made much sense to me that you could create a scenario in the editor only to get missing terrain, 

That's what the red text was for in the tooltips

**Comment by Pentarctagon** [comment]
> Right, so why are you making us go through that useless menu?

I don't know what you're looking for me to say that I haven't already said:

> it's for determining which _server.pbl to look at for the pbl editor dialog and setting the default directory when first saving a map or a scenario (and potentially more things in the future). It's essentially just choosing the add-on you're currently working on or to initialize a new one.

**Comment by doofus-01** [comment]
And I don't know how to make it any clearer either.  I don't know how anyone is supposed to guess what your intentions are, all I know is what I said above:

> You start up the map editor, you are confronted with a menu that asks you to select an add-on (or start a new one, or mainline). What is the point of that? I would have thought it determines what is available in the map editor. But it does not. Thankfully, it does nothing.

If there was some other conclusion/point someone starting the map editor is supposed to draw (that it would influence what is available in the editor), it's not obvious, to me at least.  The only other thing I could think of is that it just wasn't working as intended, and going forward the editor would be limited to one add-on.

**Comment by Pentarctagon** [comment]
I can add some text to the dialog explaining what it's for, then.

**Comment by doofus-01** [comment]
Or you could move it to somewhere where it matters.

**Comment by Pentarctagon** [comment]
I think it does matter there, especially since the goal is to add more add-on functionality in the future.

**Comment by doofus-01** [comment]
Well, maybe we're confronting a bigger design issue or disagreement.  Right now the menu does nothing for the map editor, aside from a few seconds of confusion the first time and an annoying pop-up every time afterwards.  If it's a placeholder for things to come, I'm not comforted.

Rather than cluttering up the map editor, how about moving the scenario editor out of it?  Then your new menu would make a lot more sense.  The current method of accessing the scenario editor doesn't seem great:
 - click "map editor"
 - ignore new map
 - open "new scenario"

In the meantime, maybe your new menu could open after "new scenario" is selected?

**Comment by Pentarctagon** [comment]
It doesn't do nothing - when opening or saving a map, the file dialog starts in the selected add-on's `maps/` folder.

**Comment by Pentarctagon** [comment]
Also if it's hidden behind New Scenario then it'll just be yet another piece of functionality that most people don't know how to use because the editor opens with the Add-on dropdown disabled and no obvious explanation for how to enable it.

**Comment by doofus-01** [comment]
I understand now, but that's really not worth the pop-up.  Something in the File drop-down would be less intrusive, it could have history like the "> Load Recent" or look for .pbl files or start a new add-on.

> Also if it's hidden behind New Scenario then it'll just be yet another piece of functionality that most people don't know how to use because the editor would open with the Add-on dropdown disabled and no obvious explanation for how to enable it.

This does not seem like the right way to fix that.

**Comment by Pentarctagon** [comment]
Well, the first and third issues should be easy fixes. I'll need to think more about the second one.

**Comment by CelticMinstrel** [comment]
The how is one thing, but as for the intended result, that should be obvious: if you press F5, you don't need to select an add-on, just stay in the same one.

**Comment by Pentarctagon** [comment]
What's `_initial.cfg` and `_final.cfg`?

**Comment by CelticMinstrel** [comment]
[The other special filenames.](https://wiki.wesnoth.org/PreprocessorRef#File.2Fdirectory_inclusions)

**Comment by doofus-01** [comment]
If someone is using `_initial.cfg` or similar, what they are doing is probably outside the scope of the scenario editor?

**Comment by CelticMinstrel** [comment]
I'm not really sure if that's the case. I just think it should work… but that doesn't really have anything to do with the editor. Right now it doesn't appear to work even outside of the editor.

**Comment by Pentarctagon** [comment]
Two options I've thought of for addressing this:
* Have it remember the add-on selected, so that you can just hit Enter rather than needing to find and click the add-on each time.
* Have the dialog be shown the first time the user clicks any of: New Scenario, Save Scenario As..., Add-on Publishing Editor, or Change Add-on ID. The Add-on dropdown on the editor's top bar would remain enabled in Terrain Mode.

**Comment by CelticMinstrel** [comment]
> Have it remember the add-on selected

This is probably good irrespective of this issue; however, it still shouldn't show at all on F5 in my opinion.

> Have the dialog be shown the first time the user clicks any of: New Scenario, Save Scenario As..., Add-on Publishing Editor, or Change Add-on ID. The Add-on dropdown on the editor's top bar would remain enabled in Terrain Mode.

I also have no objection to this approach.

In summary: I think there's an argument for doing _both_ of those things. If you only take the first option though, I think there still needs to be logic to automatically skip through the dialog when you use F5.
