### ISSUE TITLE
EffectWML for removing weapon special by tag name

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#7812]
### Describe the desired feature

Current remove_specials supports removing only by id. But when id composed of macro argument, in order to remove all variations there is need to remove_specials=AE_ele_fallen_drain0.17,AE_ele_fallen_drain0.125,AE_ele_fallen_drain0.20,AE_ele_fallen_drain0.193.... and there is high risk to miss some, especially if adjusting the multiplier in the future. Unique id is needed to decide which event to fire.

Possible solution is defining special as
```
    [AE_ele_fallen_drain]
        id=AE_ele_fallen_drain{VALUE}
        name= _ "consume"+" +"+"{VALUE}"
        description= _ "Weapons with this ancient ability drains hp from any kind of individual. No matter if living, undead, demon, machine, elemental, etc..."
    [/AE_ele_fallen_drain]
```
so that removing by tag name AE_ele_fallen_drain would solve use case.

**Comment by gfgtdf** [comment]
At least for now it should be possible for umc tto implement this in lua with a custom effect that writes to `attack.specials` (although i feel a  bit bad for suggesting this since i'd still like to change how attack.specials works.)


Untested luacode:
```
function wesnoth.effects.remove_AE_ele_fallen_drain(u, cfg)
	for i = 1, #u.attacks do
		local attack = u.attacks[i]
		if attack:matches(wml.get_child(cfg, "filter_attack")) then
			local specials = attack.specials
			for i = #specials, 1, -1 do
				if specials[i][1] == "AE_ele_fallen_drain" then
					table.remove(specials, i)
				end
			end
			attack.specials = specials
		end
	end
end
```

**Comment by ProditorMagnus** [comment]
If implementing custom effect I could also remove where id starts with AE_ele_fallen_drain.

I would like to let sxrpg remove the weapon special, so not my own addon.

**Comment by newfrenchy83** [comment]
i pull a request for resolve issue in source code because you shouldn't only to have thisproblems with remove_special effect
