### ISSUE TITLE
AI recruitment doesn't cache the combat simulations

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7821]
### Game and System Information

- **Version:** 1.17.19+dev

### Description of the bug

I haven't profiled this to see if the optimisation is required, however the AI does combat analysis before recruiting, so it makes sense that a cache would be required for good performance. According to the documentation it's cached:

```
/**
 * For Combat Analysis.
 * Calculates how good unit-type a is against unit type b.
 * If the value is bigger then 0, a is better then b.
 * If the value is 2.0 then unit-type a is twice as good as unit-type b.
 * Since this function is called very often it uses a cache.
 */
double recruitment::compare_unit_types(const std::string& a, const std::string& b) {
```

However, looking further down the function, it only caches the result if one of the units involved has no attacks, such as the 1.14 (or older) version of the Elvish Lady. If both units do damage to each other, then we reach one of these statements and skip inserting the result into the cache.

```
		// Normal case
		double value_of_a = damage_to_b / (b_max_hp * a_cost);
		double value_of_b = damage_to_a / (a_max_hp * b_cost);

		if (value_of_a > value_of_b) {
			return value_of_a / value_of_b;
		} else if (value_of_a < value_of_b) {
			return -value_of_b / value_of_a;
		} else {
			return 0.;
		}
```

### Steps to reproduce the behavior

1. Put a breakpoint or debug statement on the `return *cache_value;` line
2. Make the AI play a match
3. Notice that the breakpoint is never hit

### Additional context

It looks like the bug has been there since dc72d7b67e60, almost 10 years ago.

**Comment by Pentarctagon** [comment]
Would this affect #7644 at all?

**Comment by stevecotton** [comment]
Seems to be a different issue. In this one, the AI makes a list of units that are on the map, but does the calculation with default units of the same type (which is reasonable assuming the enemy would recruit more units of the same types), so it shouldn't be affected by modifications made to those units that aren't part of the basic unit type.

**Comment by GomesGoncalo** [comment]
Hi all, I used optimer to get how much time this function takes to execute and separated it into different cases into a json, then ran this `./wesnoth 2>&1 | grep "cached" | grep "time" | cut -d ' ' -f 5,6,7,8,9 | tee playthrough.set` to get those values into a file.
Then ran this:
```
import pandas
set_table = pandas.read_json("playthrough.set", lines=True)
set_table['struct type'] = "set"
unset_table = pandas.read_json("playthrough.unordered_set", lines=True)
unset_table['struct type'] = "unordered_set/unordered_map"
dataframe = pandas.concat([set_table, unset_table])
dataframe['time (ms)'] = dataframe['time']/1000
print(dataframe.groupby(["cached", "struct type"])['time (ms)'].describe())
```
(dumped two runs, one using the original set structure and I was curious if using unordered_set/unordered_map would make it a bit faster)

So here are the results (time in ms, measured in nanoseconds):
![image](https://github.com/wesnoth/wesnoth/assets/1236555/57fefec8-ac56-48ee-af94-dc419ea969fa)

(Cached=False includes inserting into the cache structure)

I think the unordered_set/unordered_map is better for big sets of data but not sure if the benefits would be seen over a game.
It does seem like there's a big difference between cached and not cached.

**Comment by GomesGoncalo** [comment]
Pushed a PR to fix the cache (https://github.com/wesnoth/wesnoth/pull/7905)

**Comment by soliton-** [comment]
Thanks for the detailed analysis and the PR!
