### ISSUE TITLE
Labeling 

### ISSUE THREAD

**Issue by Ress03** [wesnoth/wesnoth#7833]
### Language

english 

### Source

in the code 

### Original Text

H

### Proposed Change

check some errors in spelling in codes.

**Comment by Pentarctagon** [comment]
I haven't the slightest idea what this means.

**Comment by knyghtmare** [comment]
> I haven't the slightest idea what this means.

they mean the typos which are present in the source code files like comments in .lua/.cfg files
Example: `borken`

**Comment by Pentarctagon** [comment]
Just "fix typos" isn't a valid issue though - you need to point to the typos that you found.
