### ISSUE TITLE
wmlscope appears broken after 2413e2f

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#7841]
### Game and System Information

- **Version:** 1.17.19-78-g2a4a073da49
- **OS:** debian 12

### Description of the bug

`cd data/tools && ./wmlscope --definitions ../themes` should output some macros but outputs only the header.
With 2413e2f reverted it outputs the same as 1.16.

**Comment by Pentarctagon** [comment]
@Slayer95 are you still around?
