### ISSUE TITLE
1.17 Add-on manager displays auto-generated local add-ons

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#7846]
### Game and System Information

- **Version:**
- The Battle for Wesnoth version 1.17.19+dev (b4dd689f945-Modified) x86_64
Running on openSUSE Leap 15.4 x86_64
Distribution channel: Default

Game paths
==========

Data dir:        /home/USER/West/dev/wesnoth
User config dir: /home/USER/.wesnoth1_17
User data dir:   /home/USER/.wesnoth1_17
Saves dir:       /home/USER/.wesnoth1_17/saves
Add-ons dir:     /home/USER/.wesnoth1_17/data/add-ons
Cache dir:       /home/USER/.wesnoth1_17/cache
Logs dir:        /home/USER/.wesnoth1_17/logs

Libraries
=========

Boost:             1.75
Lua:               5.4.4
OpenSSL/libcrypto: 3.0.0h-dev (runtime 3.0.0h-dev)
libcurl:           8.0.1 (runtime 8.0.1)
Cairo:             1.16.0 (runtime 1.16.0)
Pango:             1.50.4 (runtime 1.50.4)
SDL:               2.26.4 (runtime 2.26.4)
SDL_image:         2.6.3 (runtime 2.6.3)
SDL_mixer:         2.6.3 (runtime 2.6.3)

Features
========

Lua console completion:       no
D-Bus notifications back end: no

Current video settings
======================

SDL video drivers:        [x11] offscreen dummy evdev
Window size:              2300x1628
Game canvas size:         1150x814
Final render target size: 2300x1628
Screen refresh rate:      60
Screen dpi:               162.02x160.89
Renderer:                 opengl (hw)
Maximum texture size:     32768x32768
VSync:                    on

Current audio settings
======================

Audio not initialized.

Installed add-ons
=================

Archaic_Era:                  1.17.1
Archaic_Resources:            1.17.1
Archaic_Sounds:               1.17.0
Bad_Moon_Rising:              1.17.0
MyAwesomeAddon-1690739649819: 
Reading_Elevation:            0.1.2

- **Downloaded from:**
here
- **Build info:**
- scons
- **OS:**
linux

### Description of the bug

1.  There is an error message: `error gui/draw: Image: '~SCALE(72,72)~BLIT(icons/icon-addon-publish.png,8,8)' not found and won't be drawn.`  It gets repeated every second the add-on dialog is open.

2.  It looks like auto-generated add-ons get auto-uploaded to the server?  Since I don't see a lot of those things on the server, it's probably not true, but it doesn't look good.  See attached image.
![Screenshot_20230813_addons](https://github.com/wesnoth/wesnoth/assets/13510196/399b121c-5940-4fa9-ae83-51cb92433228)

### Steps to reproduce the behavior

open the add-on dialog

### Expected behavior

1.  no GUI errors

2.  Auto-generated add-ons require manual upload

**Comment by Pentarctagon** [comment]
> It looks like auto-generated add-ons get auto-uploaded to the server? Since I don't see a lot of those things on the server, it's probably not true, but it doesn't look good. See attached image.

It very definitely does not get automatically uploaded.

**Comment by soliton-** [comment]
https://github.com/wesnoth/wesnoth/commit/187731c made local addons with version 0.0.0 display as published.

**Comment by CelticMinstrel** [comment]
> [187731c](https://github.com/wesnoth/wesnoth/commit/187731c) made local addons with version 0.0.0 display as published.

@Vultraz

**Comment by Wedge009** [comment]
Only confirming the auto-generated add-on aspect, which I observed after experimenting with the add-on aspect introduced in the editor.

**Comment by Pentarctagon** [comment]
For fixing this, would it be preferable to have the add-ons manager not display add-ons with version 0.0.0 (missing version info, I'm assuming) not display as published, or should the editor just create a default `_server.pbl` with the version set to 0.0.1?

**Comment by soliton-** [comment]
The simplest thing would be to just fix the logic in `get_addon_tracking_info`.  This is not particularly related to the editor and the addons should definitely not be hidden.

**Comment by Wedge009** [comment]
master @ 81bbcabe13b, I'm still seeing 'MyAwesomeAddon-1692253630517' with version 0.0.0 listed in the Add-ons menu. Is it because that add-on got generated with an older version of Wesnoth?

**Comment by Pentarctagon** [comment]
The issue here wasn't that it was shown at all, it's that it was listed as being already published when it wasn't.

**Comment by Wedge009** [comment]
Ah, okay. The icons now say it's to 'publish', so I suppose that's what changed.
