### ISSUE TITLE
Legend of Wesmere carryover

### ISSUE THREAD

**Issue by jamberine** [wesnoth/wesnoth#7862]
### Game and System Information

- Version: 1.17.19
- Downloaded from: Steam
- OS: Windows

### Description of the bug

In Scenario 9 Bounty Hunters, the objectives say 40% carryover, but the scenario actually awards 80% carryover in the old style (greater of 80% or the minimum starting gold)

In Scenario 11 Battle of the Book, the objectives say 40% carryover, and the scenario awards 40% carryover in the old style. (I assume this is unintended, since I haven't seen another campaign do this, and it is virtually impossible to beat the minimum starting gold of the next scenario)

In Scenario 14 Human Alliance, the objectives say 40% carryover, and the scenario awards 40% carryover in the old style.

### Steps to reproduce the behavior

1.  Complete Scenario 9.
2.  Complete Scenario 11. (maybe without killing the troll leader?)
3.  Complete Scenario 14 by surviving until the end of turns.

### Expected behavior

All scenarios should add 40% of any remaining gold to the next (playable) scenario.

### Additional context

This came up before in https://github.com/wesnoth/wesnoth/issues/7230 . I don't know much about WML, but I think all that's missing is carryover_add=yes for scenarios 11 and 14. Wedge notes that DEFAULT_VICTORY should have given the correct carryover. I suspect the reason is that DEFAULT_VICTORY triggers on all enemy sides being defeated, and scenarios 11 and 14 do not (ordinarily) end that way, since the troll leader is out of the way in S11 and S14 is a survival scenario. This is consistent with Wedge's observation that killing all leaders in S14 gives 40% carryover.

**Comment by Wedge009** [comment]
> In Scenario 11 Battle of the Book, the objectives say 40% carryover, and the scenario awards 40% carryover in the old style...
> 
> In Scenario 14 Human Alliance, the objectives say 40% carryover, and the scenario awards 40% carryover in the old style.

Did these mean to say '80% carry-over in the old style'?

**Comment by Wedge009** [comment]
Confirmed on all three scenarios, with the only caveat that S14 is incorrect via end-of-turn survival.
