### ISSUE TITLE
Graphical glitches with SDL 2.27+

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#7864]
As of https://github.com/libsdl-org/SDL/commit/00f05dcf49602889733262fc810386592ff51736 (which was made to fix https://github.com/libsdl-org/SDL/issues/6896), Wesnoth will frequently crash when performing simple operations (ie: opening the preferences dialog) and has a variety of graphical glitches:
![image](https://github.com/wesnoth/wesnoth/assets/3030250/78328da1-2258-4ad4-94a1-f4852b13feb0)

This is on Linux - I don't know if it does the same thing on Windows or macOS, but I would assume that it does.

**Comment by Wedge009** [comment]
I'm not familiar with overriding system packages in Linux so I did a quick investigation on Windows using official Wesnoth and libsdl releases.

It does appear this is related to the major graphics overhaul as this issue starts from 1.17.6. 1.16 is not affected and neither is 1.17.5.

SDL 2.26.5 is the last stable release that does not cause this trouble - I observe this issue from 2.28.0 onwards.

**Comment by Wedge009** [comment]
I recognise Wesnoth doesn't operate with reference to any specific distribution, but I notice the current development snapshot for Ubuntu has already packaged libsdl 2.28.2 and the next LTS release is due just over half a year from time of writing. Well, at least this is only an issue for 1.17.

**Comment by Pentarctagon** [comment]
The upstream issue that led to this problem in Wesnoth has been re-opened and the fix is pretty simple (as far as I can tell), so hopefully it's resolved prior to the next Ubuntu LTS.

**Comment by Wedge009** [comment]
Using the official Windows release for 1.17.21, I confirmed no issue with the bundled SDL 2.26.3, reconfirmed the issue with SDL 2.28.3, and then confirmed no issue with SDL 2.28.4. The [release notes for 2.28.4](https://github.com/libsdl-org/SDL/releases/tag/release-2.28.4) states:

> Enable clipping for zero sized rectangles in the SDL renderer
