### ISSUE TITLE
Wesnoth does not start after compiling with boost1.83

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#7866]
### Game and System Information

- **Version:**1.17
- **Downloaded from:**built from source
- **Build info:**gcc-12.2.0(mingw64 called with codeblock editor)
- **OS:**windows10
libraries
Lua:               5.4.4
OpenSSL/libcrypto: 1.1.1o (runtime 1.1.1o)
libcurl:           8.0.1 (runtime 8.0.1)
Cairo:             1.16.0 (runtime 1.17.6)
Pango:             1.50.7 (runtime 1.50.7)
SDL:               2.0.20 (runtime 2.0.20)
SDL_image:         2.0.3 (runtime 2.0.5)
SDL_mixer:         2.0.2 (runtime 2.0.2)

### Description of the bug

when after having compiled with the library boost1.81 or later, I try to start the game, the cursor is displayed briefly and then nothing

### Expected behavior

the game must be loaded normally

**Comment by Pentarctagon** [comment]
Can you get a stack trace?

**Comment by newfrenchy83** [comment]
when i compile with boost1.79 it's okay, but with 1.80 the icons of windows and cursor showed briefly, and nothing like if program closed before have loaded.

**Comment by Pentarctagon** [comment]
Does reverting 182d0ff548b0149a17a6fefcf061074db05c82de make any difference?

**Comment by Wedge009** [comment]
Any chance of running the compiler directly instead of through CodeBlocks?

**Comment by newfrenchy83** [comment]
> Does reverting [182d0ff](https://github.com/wesnoth/wesnoth/commit/182d0ff548b0149a17a6fefcf061074db05c82de) make any difference?

No, the issue was present good before that

**Comment by newfrenchy83** [comment]
i have "Process terminated with status 1" when i try to load withcodeblock command

**Comment by newfrenchy83** [comment]
wesot load with 1.80, thisshould be with 1.81 what issue should appear.

**Comment by newfrenchy83** [comment]
it's diffficult to find version of boost here problem appear, 1.81 work, it remain 1.82 to verify

**Comment by newfrenchy83** [comment]
> Does reverting [182d0ff](https://github.com/wesnoth/wesnoth/commit/182d0ff548b0149a17a6fefcf061074db05c82de) make any difference?

i try with commit reversed but compilation fail

**Comment by newfrenchy83** [comment]
@Wedge009  the issue is limited to boost1.83 and perhaps it is connected to https://github.com/wesnoth/wesnoth/commit/182d0ff548b0149a17a6fefcf061074db05c82de then.

**Comment by gfgtdf** [comment]
Can you run wesnoth with --log-debug=all and upload the output?

**Comment by gfgtdf** [comment]
you dont need to compile in debug mode for that

**Comment by newfrenchy83** [comment]
[gmon.out.txt](https://github.com/wesnoth/wesnoth/files/12421983/gmon.out.txt)

this is the one file generated

**Comment by gfgtdf** [comment]
That doesn't seem to be a text file this is the instruction on how to find the log files https://forums.wesnoth.org/viewtopic.php?t=46166 , if that doesn't work then show the console output of wesnoth.

**Comment by newfrenchy83** [comment]
[wesnoth-20230823-200416-3923198859.log](https://github.com/wesnoth/wesnoth/files/12422059/wesnoth-20230823-200416-3923198859.log)
[wesnoth-20230823-195530-706066555.log](https://github.com/wesnoth/wesnoth/files/12422060/wesnoth-20230823-195530-706066555.log)

this must be this.

**Comment by Pentarctagon** [comment]
Not sure how it'd be related to boost, but both end with:
```
WML exception:
User message: Window not defined in WML: 'faction_select'.Perhaps a mismatch between data and source versions. Try --data-dir <trunk-dir>
Dev message: Condition 'window_types.find(window_type) != window_types.end()' failed at D:\D\Nouveaudossier\Nouveau dossier (2)\wesnoth-master\src\gui\core\gui_definition.cpp:111 in function 'gui_definition'.
```

**Comment by newfrenchy83** [comment]
[wesnoth-20230823-202742-3936814691.log](https://github.com/wesnoth/wesnoth/files/12422230/wesnoth-20230823-202742-3936814691.log)
and when wesnoth loaded normally with boost1.79

**Comment by gfgtdf** [comment]
Hmm, earlier in the log it says `20230823 20:04:19 info filesystem: Failed to get file status of D:\D\Nouveaudossier\Nouveau dossier (2)\wesnoth-master\data\gui/window/mp_create_game.cfg: Le fichier spécifié est introuvable` I don't really know what it means though.

**Comment by gfgtdf** [comment]
Looking at https://github.com/boostorg/filesystem/commits/develop there seem to be multiple commits related to iterating directories on windows, so I'd guess at least that this is a windows specific bug

**Comment by gfgtdf** [comment]
It's not yet clear though why it only happens at the "window" directly, do you have an idea why? Did you do something with the directory?

**Comment by newfrenchy83** [comment]
> It's not yet clear though why it only happens at the "window" directly, do you have an idea why? Did you do something with the directory?

No, i don't touch directoire, m'y expertise was weapon,abilities and halo overlay only

**Comment by Wedge009** [comment]
I just compiled master on Windows with MSVC and vcpkg and no apparent issue with Windows 10, although vcpkg is still using boost 1.62. If/when it's bumped to 1.63 I can retry.

Probably isn't related, but for a while now I've noticed the MSVC compilation on Windows 7 doesn't start for me either - log file is created on start but it's completely empty. Trouble is, with a debug compilation there's no apparent issue starting Wesnoth. Again, probably isn't related to this particular report.

**Comment by newfrenchy83** [comment]
I recompiled with boost1.83 in the master branch to see if my modifications would have an impact but it's still the same problem

**Comment by newfrenchy83** [comment]
> I just compiled master on Windows with MSVC and vcpkg and no apparent issue with Windows 10, although vcpkg is still using boost 1.62. If/when it's bumped to 1.63 I can retry.
> 
> Probably isn't related, but for a while now I've noticed the MSVC compilation on Windows 7 doesn't start for me either - log file is created on start but it's completely empty. Trouble is, with a debug compilation there's no apparent issue starting Wesnoth. Again, probably isn't related to this particular report.

And with gcc?

**Comment by gfgtdf** [comment]
> > It's not yet clear though why it only happens at the "window" directly, do you have an idea why? Did you do something with the directory?
> 
> No, i don't touch directoire, m'y expertise was weapon,abilities and halo overlay only

The next step is to figure out why it happens in the `window` directory only, it is really hard to tell via remote, maybe some other programm is accessing it? Maybe some properties of the directory are different? Maybe for some reason it doesn't like the name `window` anymore,


Another approach might be to bisect boost/filesystem to find the commit that has changed the behavior, but that's also rather difficult

**Comment by gfgtdf** [comment]
> I just compiled master on Windows with MSVC and vcpkg and no apparent issue with Windows 10, although vcpkg is still using boost 1.62. If/when it's bumped to 1.63 I can retry.
> 
> Probably isn't related, but for a while now I've noticed the MSVC compilation on Windows 7 doesn't start for me either - log file is created on start but it's completely empty. Trouble is, with a debug compilation there's no apparent issue starting Wesnoth. Again, probably isn't related to this particular report.

Do you mean 1.82 here?

**Comment by Wedge009** [comment]
Sorry, yes. 1.82 and 1.83, not 1.62 and 1.63.

**Comment by newfrenchy83** [comment]
i compile version https://github.com/wesnoth/wesnoth/commit/48a10d9f7fbea97aaa4fa803137cd82599b75bea with boost1.83 but it is same problem, i don't know what update in boost can cause that.

**Comment by newfrenchy83** [comment]
i find thatin debug log:
"20230826 10:42:58 info filesystem: Failed to get file status of D:\D\Nouveaudossier\Nouveau dossier (2)\wesnoth-master\data\gui/window/mp_create_game.cfg: Le fichier spécifié est introuvable
20230826 10:42:58 info filesystem: Failed to get file status of D:\D\Nouveaudossier\Nouveau dossier (2)\wesnoth-master\data\gui/window/mp_faction_select.cfg: Le fichier spécifié est introuvable
20230826 10:42:58 info filesystem: Failed to get file status of D:\D\Nouveaudossier\Nouveau dossier (2)\wesnoth-master\data\gui/window/mp_host_game_prompt.cfg: Le fichier spécifié est introuvable
20230826 10:42:58 info filesystem: Failed to get file status of D:\D\Nouveaudossier\Nouveau dossier (2)\wesnoth-master\data\gui/window/mp_join_game.cfg: Le fichier spécifié est introuvable
20230826 10:42:58 info filesystem: Failed to get file status of D:\D\Nouveaudossier\Nouveau dossier (2)\wesnoth-master\data\gui/window/mp_join_game_password_prompt.cfg: Le fichier spécifié est introuvable"

this is only for window folfder

**Comment by Wedge009** [comment]
Is that actually where the files are located?

**Comment by newfrenchy83** [comment]
> Is that actually where the files are located?

yes, but paert of the file in data/gui/window/ not find then what other files in same folder find

**Comment by gfgtdf** [comment]
It's also worth noticing that the first ~60 files in the `window` directory are read correctly, so maybe it's related to the size of the folder.

**Comment by newfrenchy83** [comment]
> It's also worth noticing that the first ~60 files in the `window` directory are read correctly, so maybe it's related to the size of the folder.

i already try to use two folder instead of one for windows and to specify to default.cfg but not change

**Comment by gfgtdf** [comment]
> i already try to use two folder instead of one for windows and to specify to default.cfg but not change

Could you say what exactly happens if you do?  In particular, does the debug output change? like when you move all the windows wml files that start with `m` or a later latter in an alphabet into a different folder (let call it `window2`) 
.


Also i think at this point it makes more sense to create output with `--log-debug=filesystem` (intead of all)

**Comment by newfrenchy83** [comment]
> > i already try to use two folder instead of one for windows and to specify to default.cfg but not change
> 
> Could you say what exactly happens if you do? In particular, does the debug output change? like when you move all the windows wml files that start with `m` or a later latter in an alphabet into a different folder (let call it `window2`) .
> 
> Also i think at this point it makes more sense to create output with `--log-debug=filesystem` (intead of all)

I have to start over because I just found out that I had introduced bug locally that I forgot to undo in hardcoding, maybe the two folder strategy can still work, boost1.83 cause problem in loading and maybe because folder too high but i must reverify

**Comment by newfrenchy83** [comment]
I tried again with two window folders instead of one and even read mp_create_game.cfg and others first but the same problem persists and it's always the same files that are not read independently of the folders or the reading order (I placed window2 before window in default.cfg without results) the problem seems to be related to the source files corresponding to these .cfg files in src/gui/ and not to the size

**Comment by newfrenchy83** [comment]
[wesnoth-20230827-171903-2157528101.log](https://github.com/wesnoth/wesnoth/files/12448305/wesnoth-20230827-171903-2157528101.log) i forget log file

**Comment by gfgtdf** [comment]
Thx for providing this, So it seems indeed to be unrelated to the directory.

Another thing i noticed: The first file that fails be be read (`mp_create_game.cfg`) was just modified a few days before this started to happen (modified by https://github.com/wesnoth/wesnoth/commit/234060e08e988c5f412b24451ed5dc443943724b ), maybe that triggered your virusscanner or something that it now tries to access it and blocks it? Or maybe something went wrong when you pulled that commit from git? Can you open that file normally (with an editor)?



Alternatively if we want to gather more information on why it happens with boost 1.83 only it woudl be nice if we could check whether it's triggered by any of the codes added in boost 1.83, for example by setting a debug breakpoint here  https://github.com/boostorg/filesystem/blob/boost-1.83.0/src/operations.cpp#L1535

**Comment by newfrenchy83** [comment]
except that I tried with versions older than a year (updating gettext.cpp to finish compiling) and it's still the same

**Comment by newfrenchy83** [comment]
this is https://github.com/boostorg/filesystem/commit/d508d4950f7b51c84d2819a5b643b9406523027c who cause bug in loading

**Comment by gfgtdf** [comment]
Hmm, did you figure this out by bisecting?

The mentioned commit says it changes behavior in boost filesystem v4, but i think we are still using boost filesystem v3, but it's also a big commit that might have changed something else. I think it'd be important to know whether we using boost fileystem 4 or 3 though does anyone know?

**Comment by gfgtdf** [comment]
Okay i think i have an idea what might be the cause, the folder contains a directory `mp_create_game` it probably fails after trying to a read a directory it starts to fail with `mp_create_game.cfg

**Comment by gfgtdf** [comment]
Could you try whether https://github.com/wesnoth/wesnoth/pull/7880 fixes the issue?

**Comment by newfrenchy83** [comment]
> Could you try whether #7880 fixes the issue?

yes, it's work now!

**Comment by Zireael07** [comment]
I can't believe this whole issue was a naming collision - btw weird that a filesystem lib can't handle identically named files and folders, this is a common situation after all.

**Comment by newfrenchy83** [comment]
> > Hmm, did you figure this out by bisecting?
I had to test each commit from the beginning of 1.83 until I found the one that triggered the bug but I too had stuck with the idea that v3 was still used by default (and nothing indicates a change in the history from boost filesystem)
