### ISSUE TITLE
controller=null sides in campaigns work inconsistently if you add canrecruit=yes unit

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#7886]
### Game and System Information

- **Version:** 1.16.5, also on 1.16.1
- **Downloaded from:** 1.16.5 Flatpak. 1.16.1 built from source
- **OS:** Ubuntu 20.04

### Description of the bug

Wiki says that "null: the side doesn't get a turn to move and doesn't have a leader generated from the contents of the [side] tag. (It still can get units from [unit] tags in the [side] tag.)" Let's suppose you have the following code

```
	[side]
		side=2
		controller=null
		user_team_name= _ "Good Guys"
		team_name=we
		[unit]
			type=Footpad
			x, y=6, 4
			id=alright
			name = "Non recruiting"
		[/unit]
		[unit]
			type=General
			id=bugged
			x, y=5, 9
			canrecruit=yes
			name = "Recruiting"
		[/unit]
	[/side]
```

You'd expect that side=2 receives two units, a General with canrecruit=yes and an ordinary Footpad. But in fact the outcome depends on whether you proceed to the scenario from the previous scenario of the campaign or you load it from a start-of-scenario save.

If you load it from a start-of-scenario save, it works

If you proceed from the previous scenario, logs say
> error engine/team_construction: game_error: unknown unit type: null

and General doesn't appear on the board.

I made a short demo campaign for this bug 
[Null_Controller_Bug.zip](https://github.com/wesnoth/wesnoth/files/12478624/Null_Controller_Bug.zip)

### Steps to reproduce the behavior

1. Download and install the demo campaign
2. Start it. Win the first scenario (it's enough to end turn and it will claim victory)
3. Go next scenario. You will see that you have only the leader of side 1 and the Footpad on the board, no General.
4. Now return to the main menu, click Load and choose the start-of-scenario save for the second scenario (for me it's called "controllernullBUG-Big Bug.gz")
5. Notice that now the General appears and speaks his line of text

### Expected behavior

General appears in both cases

### Additional context

One could argue that `controller=null` sides shouldn't have leaders anyway. I still think there are two reasons it's a bug
1. Wiki only says the side doesn't get a leader generated from `[side]` tag and says units with `[unit]` tags can be added, without any explicit restriction on them

And most importantly

2. There is inconsistent behaviour here, when proceeding from the previous scenario and loading from a start-of-scenario save produced different outcomes. 

I think it shouldn't be like that, and although this particular bug itself shoots only in a fairly limited amount of cases, it may highlight some deeper pitfalls with Wesnoth campaigns' code

**Comment by gfgtdf** [comment]
I was able to reproduce this with 1.17.14

**Comment by gfgtdf** [comment]
It might be this code 
https://github.com/wesnoth/wesnoth/blob/9d3b8241fa3887c0f03ba30278fa9ef28bf31de3/src/game_initialization/connect_engine.cpp#L1080

I don't really understand why its there in the first place, but it should probably just be removed.

**Comment by gfgtdf** [comment]
It seems its there to remove leaders in case that the user disabled a side (by setting its controller to empty) in the mp staging dialog.

**Comment by gfgtdf** [comment]
It seems like the problem here (besides all the other problems that mp flg_manager code has) is that the game cannot differenciate between "controller=null" for helper sides (does anyone know a better word?) and for "disabled human sides"

**Comment by Discontinuum** [comment]
Btw, it turns pretty weird if I manually add a unit with id "null" to the campaign. It still works as it should when I load the start of scenario save, but I proceed from the previous scenario, the General now appears, but its unit type is "null" (and as "null" id is now valid, the recruiting unit is placed on the map in this case)
[Null_Controller_Bug2.zip](https://github.com/wesnoth/wesnoth/files/12479590/Null_Controller_Bug2.zip)

**Comment by gfgtdf** [comment]
Made a pr with a proposed fix.
