### ISSUE TITLE
`wmlunits` should recognize accuracy and parry

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#7895]
### Describe the desired feature

Some of @Hejnewar's balance changes for 1.18 are going to include changes to accuracy and parry values. `u.w.o` currently doesn't show these. @soliton- brought this up on Discord/IRC. See also discussion in #7766

**Comment by cooljeanius** [comment]
I think that this should be considered a blocker for 1.18, if the rebalancing changes are going to continue to use these values.

**Comment by cooljeanius** [comment]
Related: #2517 (for the in-game component)

**Comment by cooljeanius** [comment]
> Related: #2517 (for the in-game component)

...and then there's also #5860 for the in-game component, too, although I suppose it could be about either of these...

**Comment by CelticMinstrel** [comment]
Some runic enchants in SoF, some Quenoth Youth advancements and "sword dance" weapon special in UtBS, Elvish Champion, and a forced 100% hit chance in EI. That's all I can find.
