### ISSUE TITLE
Support [else] under [elseif]

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#7898]
Commit https://github.com/wesnoth/wesnoth/commit/aad6ce6 broke the story part of NR by replacing `[else][if]` with `[elseif]`. Since `[else]` is not supported under `[elseif]`:
https://github.com/wesnoth/wesnoth/blob/e7252b212e4a1b6f92b9cbe8be67eef7295f112b/src/storyscreen/parser.cpp#L53

It's simple to revert the replacement but it's also surprising that this is not supported so it'd be nice if it was...

I think the same holds true for https://wiki.wesnoth.org/ConditionalActionsWML#.5Bif.5D but I didn't check the code.

**Comment by ProditorMagnus** [comment]
```
[if]
	[false]
	[/false]
	[then]
		{1}
	[/then]
	[elseif]
		[false]
		[/false]
		[then]
			{2}
		[/then]
		[else]
			{3}
		[/else]
	[/elseif]
	[elseif]
		[true]
		[/true]
		[then]
			{4}
		[/then]
		[else]
			{5}
		[/else]
	[/elseif]
	[else]
		{6}
	[/else]
[/if]
```
After change, execution will reach {3} and {4}. Currently execution reaches only {4}.

I think it makes more sense as is now.

**Comment by CelticMinstrel** [comment]
I think the intended use of `[elseif]` is like so:

```
[if]
  # some condition
  [then]
    # code
  [/then]
  [elseif]
    # another condition
    [then]
      # more code
    [/then]
    # [else]
    #   # more code, but this isn't supported.
    # [/else]
  [/elseif]
  [elseif]
    # another condition
    [then]
      # more code
    [/then]
  [/elseif]
  [else]
    # this code runs if neither of the above conditions are true
  [/else]
[/if]
```

Semantically, I think an `[else]` inside the `[elseif]` would be different. As an example, suppose you commented out the nested `[else]` in the above example. When is is executed? Logically, I think you would expect it to be executed even when the 3rd condition is true, whereas the `[else]` at the end only executes if all 3 conditions are false.

**Comment by soliton-** [comment]
Ok, didn't expect that interpretation but there is certainly precedence in other languages and re-reading the conditional actions description it says exactly that.

Let's just fix the WML in NR then.
