### ISSUE TITLE
Duration of object: if set to 'turn_end' nothing happens, 'turn end' works fine 

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#7912]
### Game and System Information

- **Version:**1.17.21

### Description of the bug

Duration of object: if set to 'turn_end' nothing happens, 'turn end' works fine, according to wiki both are correct.

**Comment by ProditorMagnus** [comment]
Probably solved by adding extra line after expire_modifications("turn end");.

**Comment by soliton-** [comment]
It was removed in ad424f8c0342dfaf59f59c3adc0127ecc6da06d0 but wiki was not updated.

**Comment by soliton-** [comment]
Yeah.
