### ISSUE TITLE
[🗺️ World Conquest⚔️] Random training per scenario bug?

### ISSUE THREAD

**Issue by ArturBloch** [wesnoth/wesnoth#7921]
https://github.com/wesnoth/wesnoth/blob/e2bde1bb2c4838636b9dc97d631482343746cd44/data/campaigns/World_Conquest/lua/campaign/scenario.lua#L66C1-L89C1

This method looks to be called once at the start of every scenario and for difficulties lieutenant and below adds 1 random training PER SCENARIO for each player in World Conquest (so 5 in total for each player in a campaign) instead of 1 additonal training only in the first scenario.

On the main forum (I realize it might be outdated) https://forums.wesnoth.org/viewtopic.php?t=39651 it says players get one random training bonus but I think it refers to the whole campaign not one scenario. 

I think at some point the method has been changed from being called once at the start of the campaign to once per scenario but the code for rolling additional random trainings stayed the same (and should be only for first scenario).

I found this to be true on the current version of World Conquest (2 players)

**Comment by gfgtdf** [comment]
Yes this looks like a bug. we'll fix it for 1.18, thx for bringing it to our attention.
