### ISSUE TITLE
config_filter.cpp functions assume the default value is always zero

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#7923]
### Game and System Information

- **Version:**1.17
- **Downloaded from:**source
- **Build info:**gcc
- **OS:**windows10

### Description of the bug

when I use the filter [filter_ability] to only detect abilities with a value between 0 and 20, the linked event is triggered by uints with abilities not having the 'value' attribute but corresponding to the other criteria because the filter assigns the value 0 by default to 'value', 'add' and 'sub' and the value 1 to 'multiply' and 'divide'.

### Steps to reproduce the behavior

implement an event with [filter][filter_ability]value=0-20
2 try to trigger the event with an ability that does not have the 'value' attribute

The event should not be triggered, which is not the case because the system understand what value=0 then what this attribute is absent.

### Expected behavior

theevent should be trigered what if unit own abilité wit attribute 'value' and value between 0 and 20.

**Comment by newfrenchy83** [comment]
I just realized I made an interpretation error, in fact it is because the code attributes a default value to the value type attributes that the bug appears since the bu seems to be limited to the test of https://github .com/wesnoth/wesnoth/pull/7746 when I try to test using the filter[filter_specials][not]value=0-20 so that [damage]value=5 is not overwritten but then[damage] add=11 is not either but everything works again if I use an interval 1-20

**Comment by soliton-** [comment]
It's very difficult to figure out what issue is described here. Please provide a complete example that reproduces the issue.

**Comment by newfrenchy83** [comment]
> It's very difficult to figure out what issue is described here. Please provide a complete example that reproduces the issue.

i updated description and linked a PR for fix this issue.

**Comment by soliton-** [comment]
So the issue is filtering for abilities with `value=0`. Your expectation is that this will not match any abilities that do not use the `value` key at all and it will not match abilities that do use the `value` key but where `value=0` was _not_ explicitely specified but is merely the default.

Is that understanding correct?

**Comment by soliton-** [comment]
From https://wiki.wesnoth.org/AbilitiesWML it does not look like there are any abilities where `value` has a default though.

**Comment by newfrenchy83** [comment]
> So the issue is filtering for abilities with `value=0`. Your expectation is that this will not match any abilities that do not use the `value` key at all and it will not match abilities that do use the `value` key but where `value=0` was _not_ explicitely specified but is merely the default.
> 
> Is that understanding correct?

yes, not key not value is not explicitely specified.

**Comment by newfrenchy83** [comment]
> From https://wiki.wesnoth.org/AbilitiesWML it does not look like there are any abilities where `value` has a default though.

exactly, it why value=0 detected in abilities whodo not use this key is a bug.
