### ISSUE TITLE
Improve design of [filter_ability] and [filter_ability_active]

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#7926]
### Describe the desired feature

Instead of having two tags this should be one tag that supports filtering on active status and type.

So something like

```
[filter_ability]
  active = yes | no
  tag_name = heals | regenerate | ...
  [filter_wml]
    id = foo  # example
  [/filter_wml]
  affect_self = yes | no
  ...
[/filter_ability]
```

~~This makes it clear which part is meta data regarding the ability and what is the actual ability data being filtered and avoids attribute name conflicts.~~

~~Different suggestions for the `ability` sub tag name welcome.~~

Since there is only `active` and `tag_name` left and people seem to be allergic to a structured design all attributes are now in the same tag and we'll hope there'll be no name clashes in the future. Should probably come up with a different name for `active` since that is already very near `active_on`.

PS: Apparently there is already undocumented support for filtering the type via tag_name mixed in to the ability attributes currently. The documentation needs to be improved anyway. It currently looks like any ability tag/attribute is supported but that is not the case.

PPS: Documentation is now at https://wiki.wesnoth.org/StandardAbilityFilter.

**Comment by CelticMinstrel** [comment]
> Different suggestions for the `ability` sub tag name welcome.

Why does it need to be a subtag at all?

**Comment by soliton-** [comment]
> Why does it need to be a subtag at all?

How else would you do it?

**Comment by CelticMinstrel** [comment]
What advantage does it provide over putting all attributes directly in `[filter_ability]`?

**Comment by soliton-** [comment]
> This makes it clear which part is meta data regarding the ability and what is the actual ability data being filtered and avoids attribute name conflicts.

**Comment by gfgtdf** [comment]
I don't think the separation  between metadata and  the ability is that clear, usually i'd say the type is also part of the ability, also we don't have such separation in other filter tags. I think it'd make more sense if we have one tag `[filter_ability]` that supports whatever we implement into it and maybe support `[filter_wml]` (that works like filterwml for units)

(also it makes sense if we later also support ability formula objects and a formula= key in ability filters.)

**Comment by soliton-** [comment]
> I don't think the separation between metadata and the ability is that clear, usually i'd say the type is also part of the ability, also we don't have such separation in other filter tags.

Anything that is inside the ability tag is the ability data. Anything else is metadata. When using a subtag we could also make the name of that subtag be the tag name to filter for. Since we support a list of tag names that doesn't work though.

The important part is that the filter would work similar to the ability. Anything you write inside the ability tag you would write the same in the filter. I think that is very clear and would make the current description of "unit has an ability with the given attribute" actually be accurate (well, not quite accurate since we don't support all attributes...) and easy to understand.

We can continue the habit of for example mixing a unit filter inline in other tags. But it's not like the continued confusion there is a sign of good design. We repeatedly need to remind UMC authors where attributes are mixed in inline and where not, how name conflicts are handled or hope that any new developer will realize this mixing when they might add new attributes.

This is certainly no new issue. This comment on name conflicts in the recall tag for example is 16 years old.
https://github.com/wesnoth/wesnoth/blob/ed3ef8c84441de6222819456b7236b807722ea81/src/game_events/action_wml.cpp#L466-L468

While this case (filter_ability) is not the most egregious I simply see no reason to not do the separation properly anyway even if there is a low chance that we get conflicts in the future. It makes it clearer for developers and UMC authors.

> I think it'd make more sense if we have one tag `[filter_ability]` that supports whatever we implement into it and maybe support `[filter_wml]` (that works like filterwml for units)
> 
> (also it makes sense if we later also support ability formula objects and a formula= key in ability filters.)

I'm not proposing more than one tag. The current implementation uses two tags. I don't really know what the filterwml comment means.

**Comment by CelticMinstrel** [comment]
`[filter_wml]` would be something like a fallback in case you wanted to match something that the filter doesn't directly support. It just checks if the WML representation has the same keys with the same values, more or less.

**Comment by soliton-** [comment]
I've updated the description with the current status.

**Comment by newfrenchy83** [comment]
active=no could would said what one ability inactive were checked and no what abilties checked regardless of actvity or not. For me your suggestion don't simplify filter_ability
