### ISSUE TITLE
Provide an easy way to re-run the migrator

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#7936]
### Describe the desired feature

Split off from #2710. Sometimes the migrator messes up. Or sometimes I'd like to migrate from a different branch than I originally migrated from. Or sometimes I'm still using the branch I migrated from, and just need to migrate from it again. In such cases, it would be helpful to have an easy way to re-run the migrator in-game, to pick up any user data that might have been missed previously.

**Comment by cooljeanius** [comment]
User in this thread could have benefitted from such a feature: https://forums.wesnoth.org/viewtopic.php?t=57847

**Comment by Pentarctagon** [comment]
I was sort of hoping that someone would pick this up as a good first issue, but yeah maybe it should be a higher priority than that.

**Comment by Wedge009** [comment]
How does Wesnoth detect when to run the migrator? Investigating another issue, I experimented with deleting the standard logs directory and this seemed to trigger the migrator dialogue at start-up for me.

**Comment by Pentarctagon** [comment]
It runs it when the logs folder is not present.

**Comment by Wedge009** [comment]
So whatever in-game trigger we introduce for this would be separate to that. Okay.

**Comment by cooljeanius** [comment]
For anyone digging this issue back up due to wondering where the button added by #8791 got put, here's a marked-up screenshot:
<img width="652" alt="Screen Shot 2024-08-26 at 06 35 10" src="https://github.com/user-attachments/assets/94421819-efe8-4ac6-87c3-bd3a9ac21bda">
