### ISSUE TITLE
Wesnoth 1.16.10 x86_64 has Unreadable Fonts on MacOS 10.14.6

### ISSUE THREAD

**Issue by GittyGharial** [wesnoth/wesnoth#7939]
### Game and System Information

- **Version: 1.16.10 x86_64 for Mac**
- **Downloaded from: Wesnoth.org (direct sourceforge link: https://sourceforge.net/projects/wesnoth/files/wesnoth-1.16/wesnoth-1.16.10/Wesnoth_1.16.10.dmg/download)**
- **Build info:The Battle for Wesnoth version 1.16.10 x86_64
Running on Apple macOS 10.14.6 x86_64
Distribution channel: SourceForge

Game paths
==========

Data dir:        /Applications/The Battle for Wesnoth.app/Contents/Resources
User config dir: /Users/USER/Library/Containers/org.wesnoth.Wesnoth/USERata/Library/Application Support/Wesnoth_1.16
User data dir:   /Users/USER/Library/Containers/org.wesnoth.Wesnoth/USERata/Library/Application Support/Wesnoth_1.16
Saves dir:       /Users/USER/Library/Containers/org.wesnoth.Wesnoth/USERata/Library/Application Support/Wesnoth_1.16/saves
Add-ons dir:     /Users/USER/Library/Containers/org.wesnoth.Wesnoth/USERata/Library/Application Support/Wesnoth_1.16/data/add-ons
Cache dir:       /Users/USER/Library/Containers/org.wesnoth.Wesnoth/USERata/Library/Application Support/Wesnoth_1.16/cache

Libraries
=========

Boost:     1.76
Lua:       5.4.2
Cairo:     1.16.0 (runtime 1.16.0)
Pango:     1.48.7 (runtime 1.48.7)
SDL:       2.0.14 (runtime 2.0.14)
SDL_image: 2.0.5 (runtime 2.0.5)
SDL_mixer: 2.0.4 (runtime 2.0.4)

Features
========

Lua console completion:       yes
Cocoa notifications back end: yes

Current video settings
======================

SDL video drivers:       [cocoa] dummy
Window size:             1440x900
Screen refresh rate:     60
Screen dots per inch:    111.000000x110.000000
Screen dpi scale factor: 1.156250x1.145833

Current audio settings
======================

Audio not initialized.

Installed add-ons
=================

Ageless_Resources: 4.28.0
Xalzar_Quest:      2.0.4

**
- **OS: MacOS 10.14.6**

### Description of the bug

The font is very messed up (see attached screenshots)
![Screen Shot 2023-10-03 at 5 15 49 PM](https://github.com/wesnoth/wesnoth/assets/139590362/8121110e-1b1c-431e-aea9-00a10cdc8a1b)
![Screen Shot 2023-10-03 at 5 15 43 PM](https://github.com/wesnoth/wesnoth/assets/139590362/16ec3fe4-83cb-4b78-a397-061f9f9e91a4)
![Screen Shot 2023-10-03 at 5 10 46 PM](https://github.com/wesnoth/wesnoth/assets/139590362/7e3d3a57-a95a-457b-b638-f08e00ffeb40)

### Steps to reproduce the behavior

Open game.  The font issues are visible immediately.  Language is set to English (US)

### Expected behavior

I distinctly recall playing this game years ago with clearer fonts, on an older version of Mac OS X

**Comment by Pentarctagon** [comment]
@hrubymar10 looks like a re-occurrence of #5099?

**Comment by hrubymar10** [comment]
@Pentarctagon seems like it, but it’s weird. Nothing changed for long time in libs.

@GittyGharial Did it work in previous version 1.16.9 ? Can you please check? Thank you

**Comment by hrubymar10** [comment]
@GittyGharial Alright. Thank you. I’ll try to reproduce it in VM with macOS 10.14.6 but so far I was never able to reproduce that issue. I don’t understand why it happens. On works on all of my computers without any issue.

One more thing, do you know what mac computer do you have? Does it have retina display, or non-retina one?

**Comment by GittyGharial** [comment]
@hrubymar10 , it's the non-retina mid-2012 macbook pro (9,1).  However I also have a spare MBP 9,2 (still non-retina) currently running MacOS 12 as well; I just tried it on the 9,2 and don't see the font issue.  It might be OS-specific

**Comment by Wedge009** [comment]
Is this still an issue on 1.18?

**Comment by GittyGharial** [comment]
> Is this still an issue on 1.18?

I just checked, and the issue is fixed in 1.18.0 !  Thank you, developers!
