### ISSUE TITLE
UtBS's tailwind buff prevents rest-healing, and causes orange orb

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7966]
### Game and System Information

- **Version:** 1.17.22+dev 0945c30efd2cafff9f36ca328bcd5ffc591e6be9
- **Downloaded from:** built from Git

### Description of the bug

In UtBS, at the start of the player's turn any units that are next to a Quenoth Shaman get +1 move (or +2 for some of the L2/L3 shamans). The buffed units have an orange orb instead of the green unmoved orb. They also can't get the +2 hp bonus on the following turn for rest-healing.

If I didn't know what was causing it, I'd instead describe the bug like this: in UtBS S01, any unit that starts on the Great Tree's island gets an orange orb.

### Steps to reproduce the behavior

1. Play UtBS
2. In S01, get to the island or just debug-spawn a shaman
3. End turn

### Expected behavior

@Hejnewar Should they be able to rest-heal?

**Comment by Hejnewar** [comment]
We have two ways here, either, fix it and units with max or above mp rest (and when that is the case you can still move whatever mp you have above the max ans still rest), or we dont rest if mp is not exactly at the max. The same goes for attacks. Neither is perfect.

The orb is the same thing really, It also just checks if its equal, we could discuss if it should stay green or not.

**Comment by stevecotton** [comment]
The main question is whether the campaign wants to block rest-healing. This close to release, I feel we shouldn't change the engine.
