### ISSUE TITLE
Foreground terrain no longer draws over units

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#7976]
Idk, this might be intentional. As the title says, Foreground terrain no longer draws over units
See how the tree draws below Deflador in 1.17: :
1.17.22:
![image](https://github.com/wesnoth/wesnoth/assets/4893136/e2a43d40-0052-4cd2-8a67-f3f54bcfe779)

1.16:
![image](https://github.com/wesnoth/wesnoth/assets/4893136/18cebbdd-8e44-4648-ae78-d746b08ca888)

**Comment by gfgtdf** [comment]
Also see the Castle over the bridge in the  upper right corner of the image

**Comment by Pentarctagon** [comment]
This isn't intentional.

**Comment by doofus-01** [comment]
https://wiki.wesnoth.org/AnimationWML#Layering makes it sound like sprites were expected to be drawn on layer 40 by default, but that didn't used to be true, or at least there was a long period when it wasn't.  I guess that's something to test: a unit with standing anim specifically set to layer=0, see if it works like 1.16.  I can look into it next weekend, if no one gets to it first.

The bridge isn't necessarily related.

**Comment by Wedge009** [comment]
Assuming I didn't mess up, bisect suggests this was introduced in c6932e813346cd0776096c2add47f6ea14d72af6 by @Vultraz. First release 1.17.9.

I used the same example as the original report: opening scenario of HttT.

**Comment by Wedge009** [comment]
Oh, so that's all it was. Yeah, that's a really subtle copy-paste bug. Confirmed resolved, thanks.

**Comment by doofus-01** [comment]
That's good, I was worried I'd bumped the house of cards that is terrain-graphics.
