### ISSUE TITLE
EI S04b: Scenario ID has en_GB spelling

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#7994]
### Game and System Information

- **Version:** 1.17.22+dev 1c51bd33885c6870cba276c34a19d14cd8df6eaf

### Description of the bug

EI S04b, "Ill Humours", is spelt in `en_GB`, and so is its scenario ID. As it's a scenario ID, it'll need more testing than a simple typo fix.

Within the file itself, both "humour" and "vapours" are spelt in en_GB.

**Comment by knyghtmare** [comment]
isn't the fix as simple as correcting the British English words to American English words?

then again, it would mean save file breakage

**Comment by stevecotton** [comment]
Yes the fix is simple, but the testing will be time-consuming.

**Comment by fluidvanadium** [comment]
> isn't the fix as simple as correcting the British English words to American English words?
> 
> then again, it would mean save file breakage

maybe the remedy is worse than the disease?

**Comment by stevecotton** [comment]
The save file breakage would only be for mid-scenario S03 and start-scenario S04b saves created on 1.17.21 or later.

Saves from before then will be broken by the campaign rewrite anyway.
