### ISSUE TITLE
Outstanding typography issues

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#8000]
### Language

Source text

### Source

Various

### Original Text

Reviewed as at 1c51bd33885c6870cba276c34a19d14cd8df6eaf
Updated at fb42d4b5ac18ffcd3bf1f2e35ce859e0f8925deb

### Straight quotes/apostrophes
- [ ] EI Abilities
https://github.com/wesnoth/wesnoth/blob/fb42d4b5ac18ffcd3bf1f2e35ce859e0f8925deb/data/campaigns/Eastern_Invasion/utils/abilities.cfg#L536

- [ ] EI Abilities
https://github.com/wesnoth/wesnoth/blob/fb42d4b5ac18ffcd3bf1f2e35ce859e0f8925deb/data/campaigns/Eastern_Invasion/utils/abilities.cfg#L548

- [ ] NR S2 Part 1
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/campaigns/Northern_Rebirth/scenarios/02_01_Infested_Caves.cfg#L303

- [ ] SoF S9
https://github.com/wesnoth/wesnoth/blob/fb42d4b5ac18ffcd3bf1f2e35ce859e0f8925deb/data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg#L116

- [ ] SotBE S14
https://github.com/wesnoth/wesnoth/blob/fb42d4b5ac18ffcd3bf1f2e35ce859e0f8925deb/data/campaigns/Son_Of_The_Black_Eye/scenarios/14_Back_Home.cfg#L767

- [ ] TSG S6b
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/campaigns/The_South_Guard/scenarios/06b_The_Long_March.cfg#L545

- [ ] UtBS Abilities
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg#L1514

- [ ] UtBS Abilities
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg#L1517

- [ ] Dunefolk Names
https://github.com/wesnoth/wesnoth/blob/fb42d4b5ac18ffcd3bf1f2e35ce859e0f8925deb/data/core/macros/names.cfg#L145

- [ ] Units: Saurians
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/core/units.cfg#L252

- [ ] Naga Zephyr
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/core/units/nagas/Zephyr.cfg#L33

- [ ]  Rock Scorpion
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/core/units/monsters/Rock_Scorpion.cfg#L47

- [ ] Editor Help
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/core/editor/help.cfg#L199

- [ ] Editor Help
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/core/editor/help.cfg#L406

- [ ] GUI File Dialog
https://github.com/wesnoth/wesnoth/blob/fb42d4b5ac18ffcd3bf1f2e35ce859e0f8925deb/data/gui/themes/default/window/file_dialog.cfg#L321

- [ ] Micro AIs: Guardians
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/ai/micro_ais/scenarios/guardians.cfg#L401

- [ ] Micro AIs: Go To
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/ai/micro_ais/scenarios/goto.cfg#L473

- [ ] Micro AIs: Go To
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/ai/micro_ais/scenarios/goto.cfg#L556

- [ ] Terrain
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/core/terrain.cfg#L1072
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/core/terrain.cfg#L1092

### Straight double-quotes
- [ ] Drake Clasher
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/core/units/drakes/Clasher.cfg#L20

- [ ] Micro AIs
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/ai/micro_ais/scenarios/scenario_micro_ai.cfg#L150

- [ ] Micro AIs
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/ai/micro_ais/scenarios/scenario_micro_ai.cfg#L227

### Dashes vs hyphen/minus
- [ ] EI S10
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg#L1673

- [ ] EI S10
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg#L1679

- [ ] EI S10
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg#L1703

### Ellipsis character instead of three regular full-stops
- [ ] SoF S7
https://github.com/wesnoth/wesnoth/blob/1c51bd33885c6870cba276c34a19d14cd8df6eaf/data/campaigns/Sceptre_of_Fire/scenarios/7_Outriding_the_Outriders.cfg#L278

### Proposed Change

The last paragraph in the template for this issue is interesting:
> Note that the mainline campaigns are now using correct typography, including sexed quotes and en and em dashes.

Clearly not all text follows 'correct typography'.

Corrections may become automated through #7967.

**Comment by Pentarctagon** [comment]
My feeling on this topic generally is that at this point it'd probably be better to avoid changing already translated strings for typography issues until we have a script to validate them en-masse. Otherwise it does feel like there's always another batch of issues that's going to be found in a week, a month, etc.

**Comment by CelticMinstrel** [comment]
I don't think there's any good reason to hold off on fixing issues as they are found, unless there's a string freeze. Sure, it might seem pointless because you will often miss some and have to keep fixing them, but isn't it still better to keep approaching correct rather than wait around hoping for a script that may never exist?

**Comment by stevecotton** [comment]
Two have got swapped - "Ellipsis character instead of three regular full-stops" should be referring to SoF S7 instead.

> at this point it'd probably be better to avoid changing already translated strings

This. I feel the two in TSG and SoF ought to be left as-is, because [those campaigns are almost already translated](https://r.wesnoth.org/p684283). OTOH, anything in EI is worth changing now, because `en_GB` is the only language where it's more than 50% translated.

The editor mushroom terrains' strings probably aren't worth changing for 1.18. When it starts to generate noise in a checking script, that's a reminder to check whether the transition to the new terrains has finished yet.

**Comment by Pentarctagon** [comment]
@CelticMinstrel it's something that's caused complains from translators before already, so I think we need to be able to say essentially "here's one final mass fixup, and it won't keep happening (or will at least happen a lot less) because we have validation in place to catch it now".

**Comment by Wedge009** [comment]
> Two have got swapped - "Ellipsis character instead of three regular full-stops" should be referring to SoF S7 instead.

Thanks, late night review, I think I've fixed this.

> My feeling on this topic generally is that at this point it'd probably be better to avoid changing already translated strings for typography issues until we have a script to validate them en-masse.

I understand, and this is precisely why I just catalogued what I found was remaining instead of trying to do one (final for now?) pass. I made an attempt at automation that didn't work out, but since I noticed another pot update I recorded the remaining issues that I'm aware of for now.

**Comment by Wedge009** [comment]
> Two have got swapped - "Ellipsis character instead of three regular full-stops" should be referring to SoF S7 instead.

Thanks, late night review, I think I've fixed this.

> My feeling on this topic generally is that at this point it'd probably be better to avoid changing already translated strings for typography issues until we have a script to validate them en-masse.

I understand, and this is precisely why I just catalogued what I found was remaining instead of trying to do one (final for now?) pass. I made an attempt at automation that didn't work out, but since I noticed another pot update I recorded the remaining issues that I'm aware of for now.

> OTOH, anything in EI is worth changing now, because `en_GB` is the only language where it's more than 50% translated.

So it's worth it to change things like that now instead of later?

**Comment by CelticMinstrel** [comment]
If translators are translating when we're not in string freeze, it's their fault if the strings keep changing, isn't it?

Except when we're in string freeze (which I think we are now, or was it delayed?), I think it's better to fix any errors as soon as they're found.

You could maybe argue that keeping a list of the errors for later would be good enough, but I don't think that's true. Without string or feature freeze, the list could get out-of-date without even realizing, even from a PR that technically doesn't touch any strings.

So, unless someone is actively working on the tool you describe, I don't think there's a good reason to wait. That is also assuming we're not under string freeze, of course – _that_ is certainly a good reason to wait.

**Comment by Pentarctagon** [comment]
I mean, the string freeze was delayed in part because a bunch of other typography issues were found.

**Comment by CelticMinstrel** [comment]
And I'd also say that just before a string freeze is probably the best time for this kind of last-minute corrections.

**Comment by stevecotton** [comment]
I feel the choice should either be "fix now" or "postpone until 1.19", but that these should be chosen individually for each error.

**Comment by Wedge009** [comment]
WoF S9 being addressed in #9349.

**Comment by Wedge009** [comment]
Update: removed resolved instances and added some new ones, including a couple introduced in #8747.

**Comment by Wedge009** [comment]
I'm fine to do that if there's a consensus to proceed as such.

**Comment by stevecotton** [comment]
Sounds good to me - 1.18 has been out long enough that we've hopefully found and fixed most of the bugs where it would be helpful to keep exactly the same files for 118 as for 1.19.

@Dalas121 ?

**Comment by Dalas121** [comment]
Fixing these issues now seems sensible to me.
