### ISSUE TITLE
[Terrain] Cave wall to Cave chasm transitions show "black objects"

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#8001]
- Wesnoth 1.17.22+dev
- Msys2 Windows 10
- Github Downloaded

Screenshot says it all
![image](https://github.com/wesnoth/wesnoth/assets/5283677/3b207c7f-092b-4e0f-b1dc-0082adc0db18)

**Comment by cooljeanius** [comment]
Uh... I'm not sure if I'm seeing it properly... do you mean just where your cursor is hovering, or...?

**Comment by knyghtmare** [comment]
> Uh... I'm not sure if I'm seeing it properly... do you mean just where your cursor is hovering, or...?

Look at the cave wall hex and a chasm right below it (south of it).  You should be able to see black sharp edges

**Comment by cooljeanius** [comment]
> > Uh... I'm not sure if I'm seeing it properly... do you mean just where your cursor is hovering, or...?
> 
> Look at the cave wall hex and a chasm right below it (south of it). You should be able to see black sharp edges

Eh... kinda... it's pretty minor, though...

**Comment by Wedge009** [comment]
![image](https://github.com/wesnoth/wesnoth/assets/13679322/2ba44299-b0ea-4ebd-8688-83be5dc8f551)

b4471f3a116486897535d81385bc538633f542b0 1.17.17 @doofus-01

![image](https://github.com/wesnoth/wesnoth/assets/13679322/0840ac58-dbea-41c9-9a5e-a2dd84c4a7a1)
