### ISSUE TITLE
WoF: No documentation about the recall costs

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8008]
### Game and System Information

- **Version:** 1.17.23

### Description of the bug

As pointed out by @max-torch on Discord, there's no documentation that WoF has customised the recall costs.
![screenshot](https://cdn.discordapp.com/attachments/231976805987385345/1168606745787113533/image.png)

### Expected behavior

Probably should be stated plainly in the campaign description or in the campaign starting text, since it contradicts the in game help.

**Comment by knyghtmare** [comment]
I use this on the second scenario of my campaigns
```ini
        # update player on mechanic changes
        [alert] # custom lua tag, but core-equivalent can be [object]
            title= _ "Recall Cost Adjustment"
            message= _ "In this campaign, recall costs will be 25%/50%/75% of the unit cost based on the difficulty level picked."
        [/alert]
```
Perhaps it can be added in?

**Comment by Jonathan-Kelly** [comment]
> the campaign description or in the campaign starting text

Do you have a preference for which one of these it should be? The former approach will inform players up front before they choose which campaign to play. While the latter is more consistent with how other campaigns (UtBS and EI) do it but gives players no clear or immediate way to back out of the campaign once they see the warning message.
