### ISSUE TITLE
UtBS: No documentation about the recall costs

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8009]
### Describe the desired feature

UtBS's equivalent of WoF's #8008

**Comment by knyghtmare** [comment]
Nope. It was mentioned. Check:

https://github.com/wesnoth/wesnoth/blob/50a21a2c6c648b4ebcc2ab9fbfaed9b03f5d7f0f/data/campaigns/Under_the_Burning_Suns/utils/storytxt.cfg#L7C73-L7C73

```ini
            story= _ "Note: This campaign is probably not appropriate for beginners. It changes certain Wesnoth standards, such as the elves’ stats, the day/night cycle, recall costs and general approach to the difficulty levels. This campaign emphasizes role-playing elements and tends to have longer scenarios with objectives that change in the middle. For these reasons, we strongly suggest that you occasionally save your game mid-scenario, so you won’t lose all your progress if you get stuck and have to start over."
```

```txt
 cycle, recall costs and general
```

**Comment by Hejnewar** [comment]
Turns out I just forgot i updated it. But yeah I kinda agree that this might not be visible enough but at least it is there.

**Comment by Jonathan-Kelly** [comment]
It is a bit comical to only give players this information after they start the campaign and have no clear or quick way to return to the main or campaign selection menus. While not a new issue for UtBS, if now EI and WoF are adding similar warning messages then it might be worth considering whether to move this to the campaign description string instead.

**Comment by doofus-01** [comment]
> It is a bit comical to only give players this information after they start the campaign and have no clear or quick way to return to the main or campaign selection menus. While not a new issue for UtBS, if now EI and WoF are adding similar warning messages then it might be worth considering whether to move this to the campaign description string instead.

I largely agree with this, but would go even further.  How many people play this, are experienced enough with Wesnoth to have certain expectations and not just roll with whatever, and will remember some message in passing or think to go back to campaign description?

If a campaign has non-standard mechanics, it should have a help dialog like World Conquest has.  This might be a larger issue (I'm thinking it might also apply to SoF runes?), and doesn't preclude updating the campaign descriptions, but it would help if there was a standard way to add custom help info.
