### ISSUE TITLE
vision break link (cannot prevent quick trait from changing vision)

### ISSUE THREAD

**Issue by fluidvanadium** [wesnoth/wesnoth#8015]
### Describe the desired feature

as explained here https://wiki.wesnoth.org/Effectwml#Movement_and_Vision
it is no longer possible to break the link between vision and movement

im creating a mod here https://gitlab.com/gisadirsadrl/SSLM/
that specifically calculates vision and sets it to be the number i want it
problem is, then the era realized the leader is slow and adds a movement point and the vision is no longer constant for all units

the solution is, apply_to = vision increase does not break the link
but apply_to = vision set does 'break the link'
this is a blocker for my project so im gonna go fix it

**Comment by Pentarctagon** [comment]
#3356/#5434 for reference.

@stevecotton as well.

**Comment by fluidvanadium** [comment]
another solution is if i could guarantee my effect goes last in the queue

**Comment by fluidvanadium** [comment]
oh, i see there is a vision mod in 1.16. ill check it out

**Comment by fluidvanadium** [comment]
i think its possible that events always fire in alphabetical order of id? big if true and should be documented

**Comment by CelticMinstrel** [comment]
Did you read that wiki link carefully? It explicitly says that the link _can_ be broken:

```
[effect]
    apply_to=movement
    increase=50%
    apply_to_vision=no
[/effect]
```

**Comment by fluidvanadium** [comment]
> Did you read that wiki link carefully? It explicitly says that the link _can_ be broken:
> 
> ```
> [effect]
>     apply_to=movement
>     increase=50%
>     apply_to_vision=no
> [/effect]
> ```

edited issue for clarity. the default quick trait changes vision, even though am trying to create an environment where vision is decoupled from movement

**Comment by fluidvanadium** [comment]
oh, theres a simple workaround. i can set my vision on start instead of prestart

**Comment by fluidvanadium** [comment]
thanks all for the support

**Comment by Pentarctagon** [comment]
Given that, does this issue need to stay open?
