### ISSUE TITLE
[World Conquest][Artifact][Bug] Picking up Artifact throws Lua Error

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#8018]
- Wesnoth 1.17.22+dev
- GitHub Download
- Windows 10 Msys2 

### Bug Description
![image](https://github.com/wesnoth/wesnoth/assets/5283677/378c18cd-27e7-4bcd-872c-7c5f7e25bab0)

### How?
- Spawned an artifact on my turn
- Picked up Artifact
- Saw Lua Error
- Can also be produced by artifact spawned by bonus point

**Comment by gfgtdf** [comment]
These call `wesnoth.allow_undo(false)` to prevent undoing .

I assume this is caused by @CelticMinstrel s recent or.

**Comment by bjornlinder** [comment]
Same, have noticed this issue on a number of actions in 1.17 WC with the Magic Conquest mod. The error is also produced by applying the unit marker.

**Comment by CelticMinstrel** [comment]
Although `wesnoth.allow_undo` was on the list of functions that should explicitly not be used, it's trivial to make it continue working, so I went ahead and did that.
