### ISSUE TITLE
Text in the gamestate inspector should be selectable and copyable

### ISSUE THREAD

**Issue by cooljeanius** [wesnoth/wesnoth#8032]
### Describe the desired feature

When I type `:inspect` to open the inspection console, it's often because I'm collaboratively debugging something with someone online, who would like to know a particular element of my gamestate. In such a case, it would be a lot easier to be able to simply copy and paste the text out from the inspector, instead of my current method where I have to take screenshots of it. I thought to file this during the most recent look I've been taking at cooljeanius/The_Earths_Gut#27 btw.

**Comment by Pentarctagon** [comment]
There's a button to copy it on the lower right of the dialog.

**Comment by cooljeanius** [comment]
> There's a button to copy it on the lower right of the dialog.

That copies the whole thing, though. Sometimes I just want to select a portion to copy.

**Comment by Pentarctagon** [comment]
I think that's the best you're going to get for a while. Wesnoth doesn't have a multiline textbox UI element.

**Comment by CelticMinstrel** [comment]
Still reasonable to keep this open though.

**Comment by Wedge009** [comment]
Sounds like this is an extension of, or at least related to, #1206.

**Comment by cooljeanius** [comment]
> Sounds like this is an extension of, or at least related to, #1206. Assuming both are limitations of gui2.

not sure if they're both gui2 or not, but yeah, the more places that text can be made selectable, the better

**Comment by CelticMinstrel** [comment]
This is easily done ever since @babaissarkar made a proper multiline textbox.

**Comment by Wedge009** [comment]
Behaviour feels a bit sporadic with single-clicks, but it's certainly an improvement over what was there before.
