### ISSUE TITLE
Statistics window not fully cleared when resized

### ISSUE THREAD

**Issue by dbrozovic** [wesnoth/wesnoth#8036]
### Game and System Information

- 1.17.22
- aur wesnoth-devel package
- archlinux

### Description of the bug

When the statistics menu is open, changing from a larger to a smaller section will leave some uncleared remnants of the previous window on the screen.

Ex:
Kills screen open
![Screenshot_20231107_140932](https://github.com/wesnoth/wesnoth/assets/111772599/a933b8d1-082c-4fac-8bbe-2a07b7a6b15a)
Switched to losses screen, previous window is not fully cleared
![Screenshot_20231107_140937](https://github.com/wesnoth/wesnoth/assets/111772599/69657159-92d6-447a-8864-8d4ec75220be)

### Steps to reproduce the behavior

1. Download Wesnoth 1.17.22
2. Begin a campaign
3. Recruit, lose, and kill some units
4. Open the statistics menu
5. Select "Kills"
6. Select "Losses"
7. Remnants of previous window are still on screen

### Expected behavior

7. Previous menu should be fully cleared.

**Comment by Wedge009** [comment]
This, along with #7617, is already resolved after #7974. Unfortunately that's after 1.17.22 release, so just have to wait till the next release.
