### ISSUE TITLE
UtBS: Mystic line doesnt always heal in S2 

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#8037]
### Game and System Information

- **Version: 1.17.22**
- **Downloaded from: Steam**

### Description of the bug

Mystic line unit (or any unit with UtBS heal) start to randomly heal or not heal after you have units with the debuff. 

### Steps to reproduce the behavior

1. Start UtBS S2
2. Play it
3. As you get units with the debuff (scenario specific one) your units without it also stop being healed seemingly at random, it seems the more debuffs you have the worse it is for units without it.

**Comment by stevecotton** [comment]
I don't see a bug there - what prevents healing isn't dehydration itself, it's the /preventation/ of dehydration.

Looking at that photo, if the shaman wasn't there, Garak would become dehydrated. So the shaman prevents his dehydration instead of healing him.

**Comment by Hejnewar** [comment]
So wait, the bug is actually that they heal when they shouldnt? 

![11111](https://github.com/wesnoth/wesnoth/assets/41817546/7cb5e4bf-8681-4d94-9469-483eb57ad0f9)
![2222222](https://github.com/wesnoth/wesnoth/assets/41817546/97ecbeb1-e387-43c9-a4d5-6e33c779024a)

**Comment by stevecotton** [comment]
Hex 13,54 is terrain type `Ds`, "Beach Sands". That reminds me of #5149, which implies the bug has been in UtBS since 1.14.9.

Looks like the bug is https://github.com/wesnoth/wesnoth/blob/bf6b64be78550a6803c8f54eaa0b8e67f21c5429/data/campaigns/Under_the_Burning_Suns/utils/dehydration-utils.cfg#L6-L7

**Comment by stevecotton** [comment]
Fixed (to make it heal on less terrains) in #8047.
