### ISSUE TITLE
Screen redraw stops after Windows lock screen

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#8038]
### Game and System Information

- **Version: 1.17.22**
- **Downloaded from: Steam**
- **OS: Windows**

### Description of the bug

After afking with the game in the background its screen turns to black (which i believe is a known bug) after which it quickly gets updated as i move it around / animations play but one part of it no longer gets updated. 

![hhhhuh](https://github.com/wesnoth/wesnoth/assets/41817546/b8f0f1ca-71c3-4fca-96ce-ed604828ecf8)

### Steps to reproduce the behavior

1. Wait till game screen turns black in the background
2. Mouse over unit descriptions

**Comment by Pentarctagon** [comment]
How long does it take for this to happen?

**Comment by Hejnewar** [comment]
Honestly I dont know, I often have wesnoth launched in the background doing something else / getting distracted from playing by something else, for me black screen is common sight tbh.

**Comment by Wedge009** [comment]
Both this and #8037 seem to be non-deterministic events. I haven't seen either of them occur. Is there any chance of trying both on a different machine?

**Comment by Wedge009** [comment]
Does your screen 'lock' after your idle time? I can reliably replicate this on Windows 7 and Windows 10 (but not KDE/X11) by locking the screen (Windows + L) and then logging back in. The screen does not refresh properly after that. If this is the same issue we should rename it.

**Comment by Wedge009** [comment]
Present since 1.17.5 (not in 1.17.4).

**Comment by Pentarctagon** [comment]
Are there any errors in the log?

**Comment by Wedge009** [comment]
None. Noting it doesn't need to be the game screen - this issue happens at the title screen too.

I had a look at https://wiki.libsdl.org/SDL2/SDL_WindowEventID and it looks like Wesnoth is already covering all the appropriate events. For example, in `events.cpp`:
https://github.com/wesnoth/wesnoth/blob/2630b5bb630fd20cdc3f9fe98292781381798178/src/events.cpp#L626-L629

I just wonder if there needs to be some sort of unlock screen event that can trigger a redraw in this specific situation. (I don't know much about graphics, I could be on a completely irrelevant track.)

Is @mesilliac still around to give a pointer in the right direction?

**Comment by Pentarctagon** [comment]
From a quick google search, I did find one result that seems to describe the exact same issue as we're having: https://stackoverflow.com/questions/50301271/sdl2-texture-cleared-if-i-go-to-windows-lock-screen-and-come-back-or-resize-wind

From that it sounds like the two options would be:
* Tell SDL2 to use OpenGL (or Vulkan) on Windows instead of DirectX.
* Add handling for `SDL_RENDER_TARGETS_RESET` to have it redraw everything.

**Comment by Pentarctagon** [comment]
@Wedge009 if you add
`case SDL_RENDER_TARGETS_RESET:`
after `SDL_WINDOWEVENT_EXPOSED` does it still happen?

**Comment by Wedge009** [comment]
I was focusing on the Window Events. Didn't know there are SDL_RENDER_xxx events too.

I tried adding both `SDL_RENDER_TARGETS_RESET` and `SDL_RENDER_DEVICE_RESET` to the events handler as you suggested but it didn't appear to make a difference. However, adding `SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengl")` to `window::window()` in `window.cpp` 'fixed' it - but only so far as not using the renderer that has this problem.

Maybe it's worth going with OpenGL if only to be consistent with Linux? But I suppose DirectX drivers get a lot more support/testing on Windows systems. Of course, if someone works out how to handle the event properly, that would be the preferable solution for this specific issue, I think.

**Comment by mesilliac** [comment]
If it's actually destroying the render textures there will probably need to be special handling to regenerate them. Or at least mark that they need redrawing.

`display::update_render_textures()` will be assuming that the textures are fine as the sizes haven't changed. But it sounds like this is causing all internal render textures to be blanked?

`draw_manager.invalidate_all()` will handle updating the main display, but there needs to be extra handling to update the game map display. Probably `display::queue_rerender()` would work.

But then if it's doing it to all render textures, there will be other things that need rerendering. Like, blur textures will now probably be blank etc.

One way of handling it would be to add a new call to `draw_manager` to force a rerender on everything. `invalidate_all()` redraws everything to the screen, but it doesn't regenerate their internal render buffers. There would need to be another method there if that's something it should manage.

Probably everything that overrides `top_level_drawable::render()` needs to be clued in that its state has been voided...

**Comment by Wedge009** [comment]
I'm not sure if this will help:

Title screen after unlocking is completely black. Moving the mouse around over buttons so that their highlighted version triggers redraws results in this:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/327a6727-98f4-43c5-9317-f3668d1b4065)
Switching to another window and back redraws everything presumably due to the `SDL_WINDOWEVENT_EXPOSE` event.

Game screen after unlocking is not completely black because of unit animations:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/32b42abb-9df7-48ca-9478-2a0002d05191)
Switching to another window and back doesn't redraw everything but moving the game map around eventually brings most things back. The only issue is if the window area is larger than the game map boundaries then those areas outside the game map will not redraw properly, leading to the symptom that Hejnewar reported in the original post.
![image](https://github.com/wesnoth/wesnoth/assets/13679322/81974a0f-2807-4e6a-bebb-859efccfbf0d)

It sounds very complicated to work-around something specific to DirectX. Maybe we are better of using the SDL hint to favour OpenGL on Windows?

**Comment by mesilliac** [comment]
Hmm so it does look a lot like the render texture was filled with black, but was reinitialized so it can still be rendered to. It's just updating the areas as they change, and ignoring the areas it knows it's already rendered.

A quick grep shows that the only things using render textures are the game display (`display.ccp` / `game_display.cpp`) and gui2 windows (`gui/widgets/window.cpp`). The title screen is technically a window. I'm not sure why switching to another OS-level window and back would work when coming awake from the lock screen didn't. Surely there was already an expose event when it came back from the lock screen?

The game map background it knows it's already rendered it so it doesn't do it again, i assume.


The simplest way of accommodating directX here would be to augment the `top_level_drawable` interface with an ability to force things to fully rerender. It's a bit ugly, but wouldn't be much code. Tell `draw_manager` it needs to do that when that SDL event triggers, then it tells everything they need to rerender as part of the `render()` stage, via that interface. Probably just a "force" flag on `top_level_drawable::render()` or something like that.

Then when calling `render(force=true)` they just `queue_rerender()` and proceed as normal.


That said there's nothing nonstandard Wesnoth is doing graphically, i wouldn't expect any problem with just using openGL.

**Comment by Wedge009** [comment]
> Surely there was already an expose event when it came back from the lock screen?

Yes, I observe `events/EXPOSE` messages in the log, as mentioned above. I can only guess the title screen is much simpler than the game screen.

**Comment by Pentarctagon** [comment]
@Wedge009 can you do a quick check of the fps and CPU usage when using opengl vs directx? Doesn't need to be anything too complex - just open a map with some water somewhere on it. If their performance is close enough, then just using opengl would be the simpler approach.

**Comment by Wedge009** [comment]
Using the opening scenario for Dead Water as the test I notice comparable FPS numbers between DirectX and OpenGL on both of my Windows machines. It's probably not statistically significant, but on Windows 7 it even appeared marginally better.

But I'm dubious as to how accurate these numbers are. On both Windows and Linux, the numbers reported are substantially lower than the software rendering in 1.16.10 which doesn't make sense to me. Then again, they could have different implementations, so they may not be comparable between the different rendering methods. Also, none of my machines are slow enough to report anything lower than 100 fps average in 1.16 and 60 fps average in 1.17. (I don't normally use FPS indicator in Wesnoth.)

**Comment by Pentarctagon** [comment]
For 1.17, is the FPS limiter or the vsync option enabled?

**Comment by Wedge009** [comment]
Don't know, I'm just using default settings. Will be away for several hours.

**Comment by Pentarctagon** [comment]
Alright - both would result in the fps being limited to your screen's refresh rate, and 60 is the most common screen refresh rate, so seeing it be 60 fps seems suspicious.

**Comment by Wedge009** [comment]
Testing 1.16.10 official release against 1.17.22+dev @ ec0f8f9942f27c08dfc2005e67ab1607da53d39a

Windows 7 desktop with 60 Hz screen:
Software:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/a77e1d81-9356-4f3a-8d55-d0d439b74186)

Default DirectX:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/efd186d7-ad25-4dda-a053-33d683907fa2)

OpenGL hint:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/93034c01-1302-4936-91ec-36d213006f9f)

Windows 10 laptop with 144 Hz screen:
Software:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/7c44b57f-55b8-4530-aee2-1f18fbcf7474)

Default DirectX:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/58eb42ee-0dc3-4428-9c06-de17584991c6)

OpenGL hint:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/b0460a86-ce95-4c44-ba1a-385e41fad5ed)

KDE/X11 desktop with 60 Hz screen
Software:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/9802bdd6-d8ad-4b84-9dd8-01ee66dd49e2)

Default OpenGL:
![image](https://github.com/wesnoth/wesnoth/assets/13679322/f3b04a81-24a8-423a-8b73-2d1e8c561b28)

So it may just be that the hardware rendering follows the refresh rate more closely. Anyway, the point is there's no discernible difference (with sufficiently powered hardware) between DX and OGL. Would need someone with really low-end hardware to test any differences, I think.

As an aside, I notice Steam web view on Windows - after exiting the lock screen - also exhibits a momentary black screen before its rendering is refreshed. So whatever Steam's rendering framework is, it already knows how to accommodate this 'device loss' under DirectX.

**Comment by Wedge009** [comment]
Just noting that Direct3D version 11+ also does not exhibit this issue.
