### ISSUE TITLE
Update Flatpak freedesktop runntime to 23.08

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#8040]
### Describe the desired feature

Currently, Flatpak build uses 22.08 runtime. The latest is 23.08.

**Comment by Pentarctagon** [comment]
@soliton- @loonycyborg is there anything left to do for this?

**Comment by loonycyborg** [comment]
flathub uses 22.08 still

**Comment by Pentarctagon** [comment]
Oh, right, that's for 1.16.

**Comment by grz0** [comment]
@Pentarctagon @loonycyborg `SDL_image` in freedesktop 23.08 runtime seems to be compiled without webp support.
I can't see the change in freedesktop repo which disabled webp support, so maybe this is a bug. 

gdb session from inside flatpak shell:
```
(gdb) break IMG_isWEBP
Breakpoint 1 at 0x7ffff7dd0570: file /usr/lib/debug/source/components/sdl2-image.bst/IMG_webp.c, line 285.
(gdb) run Downloads/test.webp 
Starting program: /home/xx/a.out Downloads/test.webp
[Thread debugging using libthread_db enabled]                                                                       
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, IMG_isWEBP (src=0x555555559480) at /usr/lib/debug/source/components/sdl2-image.bst/IMG_webp.c:285
285     {
(gdb) list
280     {
281     }
282
283     /* See if an image is contained in a data source */
284     int IMG_isWEBP(SDL_RWops *src)
285     {
286         return(0);
287     }
288
289     /* Load a WEBP type image from an SDL datasource */
```

**Comment by Pentarctagon** [comment]
Where would we report that issue?

**Comment by loonycyborg** [comment]
Here's my test case:
```
//Compile with
// gcc `pkg-config --libs --cflags SDL2_image` -o test-webp test-webp.c

#include <SDL2/SDL_image.h>
#include <stdlib.h>

int main(int, char** argv)
{
    SDL_RWops *src = SDL_RWFromFile("end-n.webp", "rb");
    if (src == NULL) {
        exit(2);
    }
    if(IMG_isWEBP(src)) {
	    printf("WEBP load successfull\n");
    } else {
	    printf("WEBP load failed\n");
    }
    exit(!IMG_isWEBP(src));
}
```
Tried to run it from `flatpak run --filesystem=home --command=bash org.freedesktop.Sdk` with wesnoth's test webp image there too. Succeeds with 22.08, fails with 23.08. This should be probably reported to freedesktop runtime maintainers.

**Comment by grz0** [comment]
> Where would we report that issue?

Probably here:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues

**Comment by Pentarctagon** [comment]
Reported at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1675

**Comment by Pentarctagon** [comment]
Alright, looks like the fix has been made upstream. I don't suppose anyone knows when that'll make it into the distributed SDK?

**Comment by soliton-** [comment]
You could ask in the issue when they plan the next release. Last release was 3 weeks ago (https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases) so might be soon but it doesn't look like they have some strict schedule.

**Comment by Pentarctagon** [comment]
Reverted to 22.08 in 3b2266d and ed358bd until the webp fix is released.

**Comment by cooljeanius** [comment]
> Reverted to 22.08 in [3b2266d](https://github.com/wesnoth/wesnoth/commit/3b2266d9fc2bca62b3dff2b571eeca42dbf42a07) and [ed358bd](https://github.com/wesnoth/wesnoth/commit/ed358bdfe6b06ec218066b75446ae0d9c8d81d90) until the webp fix is released.

Thanks, I cherry-picked these to my personal branches that needed them, and can confirm that they work there, too

**Comment by grz0** [comment]
New version of 23.08 is avaiable
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases/freedesktop-sdk-23.08.7
