### ISSUE TITLE
Windmills confuse players / Map makers dont want to use windmills because they confuse players 

### ISSUE THREAD

**Issue by Hejnewar** [wesnoth/wesnoth#8064]
Windmills look like a villages, but arent villages in general, while being villages sometimes (because they look like villages and people give them village status). This is a problem because it often confuses players if they dont look at the tooltip and because they mostly dont look there (me included) map makers abstain from using that terrain on their maps thus making this terrain less useful than it could be.

**Comment by cooljeanius** [comment]
This is something I've run into occasionally; see project-ethea/After_the_Storm#101 where I proposed adding some dialogue to address this: https://github.com/project-ethea/After_the_Storm/pull/101/files#diff-3dff020db156cc01822629c89e3b1d54f0d1883fcf7cb521de724b8b01774769R232-R241
Also in nemaara/A_New_Order@2e798f1, I took advantage of this confusion specifically to make things more difficult for `NIGHTMARE`-difficulty players:
https://github.com/nemaara/A_New_Order/commit/2e798f1a75eaf58e59f796f5a402ecf0cee73ca8#diff-baa2e58132f9a9e316dd224f43264c3ca8ca8692bbff5235929b88c156707183R480-R485

**Comment by Hejnewar** [comment]
Actually I checked with 1.17 and it is already a village. Soo I guess I can close this. xd

**Comment by Discontinuum** [comment]
There are two terrain types: actual Windmill Village and a Windmill embellishment overlay. And they look almost identical if not exactly. And confuse a lot, even I get unsure when see a windmill during the map, even playing the game for several years. So may be nice to think about ways to possibly fix this

**Comment by Pentarctagon** [comment]
*has also been confused by them*

**Comment by mesilliac** [comment]
What horrified me the most about that empty maps complaint was the thought that someone might decide to put windmills on them.

**Comment by Hejnewar** [comment]
>What horrified me the most about that empty maps complaint was the thought that someone might decide to put windmills on them.

Well thats not even very terrifying, I could make a map with both ornamental and regular windmills and additionally to make minimap less useful I could place village overlays on flat near ornamental windmills. Oh yeah now that would be nice, but it is not even over, the windmills would randomly turn from and into ornamental or regular depending on what they were before. I hope thats terrifying enough, no need to thank me.  :P

Btw. there are no villages now, only windmills, have fun. 

Making that scenario would open this issue for me. 

>For the Windmill Village the current tile is okay, I think it's the Windmill embellishment to change. 

Any examples like from real world?

**Comment by doofus-01** [comment]
> Any examples like from real world?

https://upload.wikimedia.org/wikipedia/commons/e/eb/Wind-powered-agricultural-pump-1.jpg

**Comment by Jonathan-Kelly** [comment]
I guess I only ever use the windmill villages on maps. A grain mill looks like something worth capturing, so always seemed it should be a capture-able asset.

The way most mainline campaign stories go, what appears on the interface as "gold" would actually be "food" because most protagonists are armies of freedom fighters or refugees foraging in the wilds to survive (with only limited support coming from sympathizers). So a large structure containing sacks of grain and flour would be of strategic value to them.

**Comment by usernameStraffisnotavailable** [comment]
I hate the embellishment windmills, they are confusing me too,  I vote for removing the embellishment windmills. A windmill should always give income.

**Comment by stevecotton** [comment]
For the ones that really are villages, scenario authors could have them start owned by a hidden team, so there there's a flag flying on them. I agree that the non-village ones' appearance should change.

**Comment by MXB2001** [comment]
Here's an idea. How about make the embellishment a non building type of windmill. See link.

[https://m.media-amazon.com/images/I/419wQvLSpoL.jpg](url)
