### ISSUE TITLE
I dont know what is wrong this happens when i try to join a multiplayer game

### ISSUE THREAD

**Issue by Hjaltee** [wesnoth/wesnoth#8070]
### Game and System Information

1.16.6
SourceForge
dont know what this means
Windows 

### Description of the bug

When I try to Join a multiplayer game that requires some mods this happens. This is the first time i have tried this bug and other mods work fine
the mod it requires is Ageless RPG Era

### Steps to reproduce the behavior

Join multiplayer server
join the game 

### Expected behavior

![image](https://github.com/wesnoth/wesnoth/assets/88845624/52b2dbaa-7016-4b62-b8ac-7747c3dfd421)

**Comment by soliton-** [comment]
Duplicate of #4055.

If you have detailed instructions to reproduce which presumably includes creating the game that you got the error from when joining then please add a comment to the above issue.
