### ISSUE TITLE
Wesnothd - Cannot Connect Multiplayer LAN

### ISSUE THREAD

**Issue by Quin5** [wesnoth/wesnoth#8072]
### Game and System Information

- **Version:**    1.16.2
- **Downloaded from:**    Synaptic Package Manager
- **Build info:**     n/a
- **OS:**     LinuxMint 21.2

### Description of the bug

I launch Wesnoth from my GUI menu, select "Multiplayer", "Host Networked Game", and click "Ok".  I receive a message about Wesnoth server running in the background and click "Yes".  From a separate computer, attempting to connect using the host IP address and port 15000 gives the message, "connection failed operation timed out".

Upon investigation, I found the following error when wesnothd is ran:

```
Started wesnothd as a daemon with process id 7051
20231126 10:43:13 info server: Server configuration from file: '/home/me/.config/wesnoth-1.16/lan_server.cfg' read.
20231126 10:43:13 error server: could not make fifo at '/var/run/wesnothd/socket' (No such file or directory)
20231126 10:43:14 info server: 127.0.0.1	player joined using accepted version 1.16.2:	telling them to log in.
```

There is no '/var/run/wesnothd' directory.  The GUI appears to make a networked host, but is using localhost instead, which naturally does not allow LAN users to connect.

### Steps to reproduce the behavior

1. Run Wesnoth
2. Host networked game
3. Connect to host IP from separate computer on same LAN

### Expected behavior

Users on my LAN being able to connect to my host.

### Additional context

The computer I'm using to connect to my host is running Mac OSX 14.12.

**Comment by loonycyborg** [comment]
Indeed if we listen on loopback interface you could only connect more clients on same pc. I'm not sure what's the best way to figure out the ip you should listen on for LAN case.

**Comment by loonycyborg** [comment]
In general each host can have multiple network interfaces each on different networks, so would need to add an extra text field to input pc's ip address on desired network, unless there's some shortcut.

**Comment by loonycyborg** [comment]
Could make it listen on 0.0.0.0 but in general it's considered insecure. Would it be acceptable for LAN server?

**Comment by soliton-** [comment]
The fifo error is not an issue. It's not needed.

Is there a firewall running on the host running wesnothd? Then you need to allow connecting to port 15000.

**Comment by loonycyborg** [comment]
Double check that wesnothd it starts actually listens on all interfaces with something like `netstat -plant`. For me it listens on :: and 0.0.0.0 so should already work on LAN.

**Comment by Quin5** [comment]
> The fifo error is not an issue. It's not needed.
> 
> Is there a firewall running on the host running wesnothd? Then you need to allow connecting to port 15000.

I have been able to ping the host ip address from the client machine.  I added a rule in my firewall to allow in/out on port 15000, but I still get a connection to 127.0.0.1 after the FIFO/socket error when wesnothd is launched.

**Comment by Quin5** [comment]
> Double check that wesnothd it starts actually listens on all interfaces with something like `netstat -plant`. For me it listens on :: and 0.0.0.0 so should already work on LAN.

After wesnothd is launched, I typed 'netstat -plant' and saw:

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:15000           0.0.0.0:*               LISTEN      36036/wesnothd-1.16

**Comment by loonycyborg** [comment]
> > Double check that wesnothd it starts actually listens on all interfaces with something like `netstat -plant`. For me it listens on :: and 0.0.0.0 so should already work on LAN.
> 
> After wesnothd is launched, I typed 'netstat -plant' and saw:
> 
> Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name tcp 0 0 0.0.0.0:15000 0.0.0.0:* LISTEN 36036/wesnothd-1.16

This shows it's listening on all interfaces for you too, so I'd expect LAN connections to work unless firewall interferes.
