### ISSUE TITLE
Unclear objectives in the first scenario of SoF

### ISSUE THREAD

**Issue by usernameStraffisnotavailable** [wesnoth/wesnoth#8083]
### Game and System Information

BfW 1.16

Check [forums thread](https://forums.wesnoth.org/viewtopic.php?t=57387) for more information

### Description of the bug

The objectives say you have to move Alanin and the caravans to the dwarvish citatel, like it was in older versions, but now you have to move them to the go-here-icon at the top of the map.

### Additional context

Proposal to fix the issue:
Change the objectives, or label the go-here-icon as dwarvish citatel

**Comment by usernameStraffisnotavailable** [comment]
Quote: "Is it that the victory trigger hexes need adjustment, extended a bit further east?"
No that is not the problem.

Quote: "Is it that moving to Rugnur's castle isn't victory? "
Yes that is the problem.

The objectives suggests to the player that he has to move to the dwarvish castle. If I remember correctly, that was the goal in earlier versions. But now moving to the dwarvish castle is no longer victory, instead the player has to move to the go-here-icon on the top of the map.

Possible solutions:

- Rewrite the objectives (needs to be translated in all languages)
- Add a note to the objectives, to make them more clearly. (needs also to be translated)
- Place a label to the go-here-icon, name the label Dwarvish Citatel, or entry to the Dwarvish Citatel (needs translation too)
- At the end of the starting dialogue add a [scroll_to] with highlight=yes and a delay the go-here-icon

Maybe combine the last two proposals.

**Comment by doofus-01** [comment]
OK.  This is simple to address once we're allowed to change strings again.

**Comment by Pentarctagon** [comment]
IMO fixing the objective of the first scenario of a campaign is worth it to fix anyway.

**Comment by stevecotton** [comment]
@doofus-01 are you going to open a PR, or should someone else do it?

**Comment by doofus-01** [comment]
I can do it, just didn't get to it last week.
