### ISSUE TITLE
WoF macros: BOOK_LEARNING puts a macro in a translatable string

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8084]
### Game and System Information

- **Version:** 1.17.23

### Description of the bug

This translatable string has a macro argument in it, which [makes the translation fail](https://wiki.wesnoth.org/GettextForWesnothDevelopers#Things_to_avoid):

```
#. [floating_text]
#: data/campaigns/Winds_of_Fate/utils/macros.cfg:164
msgid "+{AMOUNT} experience"
```

**Comment by CelticMinstrel** [comment]
It's a bit of an ugly solution, but I think the this can be solved by creating subsidiary macros called `BOOK_LEARNING_40`, `BOOK_LEARNING_32`, `BOOK_LEARNING_40`, `BOOK_LEARNING_24`, `BOOK_LEARNING_16`, and `BOOK_LEARNING_8`. Then substitute the offending translatable string in the macro with `{BOOK_LEARNING_{AMOUNT}}`. Each of those subsidiary macros will then expand to the same string with the appropriate number substituted.

The other possibility is to use Lua and a proper plural string, sort of like what's done in HttT's Test of the Clans.

**Comment by stevecotton** [comment]
Using Lua is my preference, no reason to have multiple strings.

**Comment by Jonathan-Kelly** [comment]
There is a similar macro [in DiD](https://github.com/wesnoth/wesnoth/blob/85a3f8a2df0ebdd42f692c2cc9242ea64982049d/data/campaigns/Descent_Into_Darkness/utils/macros.cfg#L3-L24) which simply loads the macro argument into a variable before using it in a translatable string. Could that be the solution for this as well?

**Comment by stevecotton** [comment]
The macro is DiD would work here too, but if we want the mainline campaigns to be good examples then it should use the proper pluralisation, IMO.

**Comment by gfgtdf** [comment]
I don't think lua is needed here, since all use cases of it are plural, just `"+$amount experience"` and setting a variable should be enough.

**Comment by gfgtdf** [comment]
a quick look gives multiple cases the could use proper pluraliastion though, unless i missed soemthing):
* `message=_"Greetings, strangers! This swamp is dangerous... You wanna cross it, you’ll need protection — cost you only $fee gold!"`
* `text= _ "$(16 - $turn_number) turns remain to free $number_merfolk_caged| merfolk"`
* `text= _ "$kill_total of 20 prey harvested"`
* `_ "To travel east, collect {COUNT} alswdan herbs and pay Hahid al-Ali $gold_cost gold. <i>(challenging)</i>"`
* `_ "And look, our captured equipment and provisions are here too! I’ve recovered supplies worth $gold_amount_S11 gold."`

**Comment by stevecotton** [comment]
> `text= _ "$(16 - $turn_number) turns remain to free $number_merfolk_caged| merfolk"`

Issue #6080 has been logged for that, but the discussion here will help.

**Comment by CelticMinstrel** [comment]
>* `message=_"Greetings, strangers! This swamp is dangerous... You wanna cross it, you’ll need protection — cost you only $fee gold!"`
>* `_ "And look, our captured equipment and provisions are here too! I’ve recovered supplies worth $gold_amount_S11 gold."`



I don't think money requires pluralization, does it?

>* `text= _ "$(16 - $turn_number) turns remain to free $number_merfolk_caged| merfolk"`

Definitely needs a fix. This can literally use the exact same solution as HttT's Test of the Clans, can't it?

>* `text= _ "$kill_total of 20 prey harvested"`

I suspect this wouldn't need a plural form, as it's always "20 prey"… or are there languages that modify the form of the noun based on the numerator of a fraction?

>* `_ "To travel east, collect {COUNT} alswdan herbs and pay Hahid al-Ali $gold_cost gold. <i>(challenging)</i>"`

Wait, this one also has a macro in it!
