### ISSUE TITLE
Unit sprites half displayed on n-s bridge over chasm

### ISSUE THREAD

**Issue by MXB2001** [wesnoth/wesnoth#8111]
### Game and System Information

- **Version:**
- 1.17.23
- **Downloaded from:**
- flatpak
- **Build info:**
- **OS:**
- linux

### Description of the bug

Best explained by this screenshot:

![submerged](https://github.com/wesnoth/wesnoth/assets/65250870/263fa607-936d-4003-8f3e-7b18eae714de)

Note the two units (whelp/archer) on bridge are "submerged" seemingly. Observed also that in combat full sprite re appears for duration.

### Steps to reproduce the behavior

place unit on a n-s bridge over chasm

### Expected behavior

should look same as units on diagonal bridges

**Comment by doofus-01** [comment]
This must be related to #7976, will look into it
