### ISSUE TITLE
Official Wesnoth 1.17.24 Windows package missing libssp-0.dll

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#8132]
### Game and System Information

- **Version:** 1.17.24
- **Downloaded from:** sourceforge.net
- **Build info:** Official
- **OS:** Windows

### Description of the bug

> The code execution cannot proceed because libssp-0.dll was not found. Reinstalling the program may fix this problem.

### Steps to reproduce the behavior

1. Download and install official 1.17.24 release for Windows.
2. Attempt to start Wesnoth.

### Expected behavior

Wesnoth runs as normal.

**Comment by ProditorMagnus** [comment]
I followed same steps and libssp-0.dll was provided, game worked. It was put to wrong folder though so I had to move it, but that was just from installer differences between itch and sourceforge.

**Comment by Pentarctagon** [comment]
@ProditorMagnus so itch.io had the dll and SourceForge didn't?

@loonycyborg FYI btw.

**Comment by ProditorMagnus** [comment]
1.17.23 itch had ddl
1.17.24 sourceforge had ddl

I have not tested oppositite.

**Comment by Wedge009** [comment]
I downloaded from sourceforge.net.

**Comment by Wedge009** [comment]
For the Windows installation executables from sourceforge.net, `libssp-0.dll` is present for 1.17.23 but not 1.17.24.

For the 'beta' zip from itch.io, `'libssp-0.dll` is present for 1.17.24 but it is smaller and newer than the one from 1.17.23 sourceforge package. However, both of these - when dropped into the installation for 1.17.24 - allow the game to run again.

**Comment by Pentarctagon** [comment]
I believe loonycyborg has since uploaded versions with the dll?

**Comment by Wedge009** [comment]
I was using the package I downloaded earlier. If it's been resolved on-line, then this can be closed.

**Comment by Pentarctagon** [comment]
@loonycyborg just to confirm - the 1.17.24 package has been updated everywhere, correct?

**Comment by loonycyborg** [comment]
Yes. I uploaded them everywhere.
