### ISSUE TITLE
Skeleton Rider and Bone Knight have an inconsistency

### ISSUE THREAD

**Issue by MXB2001** [wesnoth/wesnoth#8138]
### Game and System Information

- **Version:**
1.17.24

### Description of the bug

The title units have movetype mounted plus the submerge ability. They can't use the ability normally as they can't enter deep water.

### Additional context

Thread discussion: https://forums.wesnoth.org/viewtopic.php?p=685387#p685387

**Comment by Wedge009** [comment]
Curious. These units were added to 1.17 from Liberty campaign in #6088. The submerge ability was added to the Skeleton Rider as part of synchronising its version in Liberty with the unit in UtBS (cba698cfc52cb444138477e386ea7731fb9d4e09). And then Bone Knight had it added in #7513 seemingly for the sake of consistency, without considering that the `mounted` movement type does not include deep water.

My last play-through of both Liberty and UtBS was in 1.16 and I don't have notes for either of these units so I suppose I did not encounter them in the campaigns. Perhaps it's only that these units are now part of the core that they are more visible to players and so this inconsistency is pointed out in the forum thread.

It seems the reporter has already started using the submerge ability so I don't know if we can just revoke the submerge ability on the units. Another solution is to make an mounted-undead movement type that includes deep water movement.

**Comment by Wedge009** [comment]
Further complicating this is the Chocobone - visually it is also a mounted unit, but its movement type is `undeadfoot`. It also has the submerged ability.

**Comment by knyghtmare** [comment]
> Further complicating this is the Chocobone - visually it is also a mounted unit, but its movement type is undeadfoot. It also has the submerged ability.

My assumption is that the Chocobone is not a horse and may differ in movement patterns. Thus, the `undeadfoot` type fits. The Skeleton Rider-line used to have its own "undeadmountedfoot", from UMC but seems these variants missed them.

There's 2 other cases which I want to mention:
- Barrow Wight 
- Pyre Wight

They are custom units in Eastern Invasion so should they get submerge and deep water movement too?
Actually for Pyre Wight, Maybe a no since that unit has a flaming sword and it would be odd if that still kept its blaze after staying in deep water. Maybe they these 2 units do not need the adjustment as much as the core ones.

**Comment by doofus-01** [comment]
I was wondering about the name "Barrow Wight", and from "internet research" it seems to be a JRR Tolkien wraith-like thing.  If you run it through translations, it needn't be tied to the Tolkien estate, but is that specific name OK to use?

I know it's pedantic, but I remember some Wizards of the Coast lawsuit that was over similarly dubious merit.  Having a hard time finding it with all the lawsuit news those folks generate (and it doesn't look like they are always the bad-guys).

**Comment by knyghtmare** [comment]
Barrow Wight and Pyre Wight are not the scope of either #8138 or #8142
Thus, I suggest moving these two particular mentions to a new discussional issue.

**Comment by soliton-** [comment]
I suggest adding a mounted-undead movetype and use that consistently.
