### ISSUE TITLE
Wings of Fate scenario 08

### ISSUE THREAD

**Issue by Argesilao2** [wesnoth/wesnoth#8140]
### Game and System Information

- **Version:1.17.23
- **Downloaded from:download page
- **Build info:**
- **OS:windows 11

### Description of the bug

scenario 08 Overlook of Wings of Fate
Reshan, Gorlack's intendant, becomes Resha, without the final n, in the whole scenario.

**Comment by soliton-** [comment]
Reshan was renamed to Resha in ffb45122d4128eb4c015400908ab2934ee8d5b24. I cannot find mention of Reshan in the campaign now.

**Comment by Argesilao2** [comment]
I started the campaign about two months ago, I don't remember which version 1.17 issue, and I didn't play it again for some time after completing the first seven scenarios.and Gorlack's helper was called Reshan.
Today I resumed the campaign, I finished scenario 7, in which the helper was still called Reshan, and at the beginning of the new scenario I found Resha, and Reshan is present in the recall list.
So the name was changed in one of the latest versions.

    Il giovedì 21 dicembre 2023 alle ore 11:45:26 CET, Gunter Labes ***@***.***> ha scritto:  
 
 


Reshan was renamed to Resha in ffb4512. I cannot find mention of Reshan in the campaign now.

**Comment by Wedge009** [comment]
This is the risk with playing the development releases, I think, that breaking changes like this can happen. If you wish to try continuing your original play-through, you can extract the text file from the save (assuming default compressed save games) and manually change the `id` and `name` field from `Reshan` to `Resha`.

Really not sure if that would work, however. You might be better off just starting the campaign from scratch - or revert to a 1.17 release before the change to Resha was made (looks like 1.17.21).

At any rate, this is an expected consequence of breaking changes during development so I don't think it's warranted to keep the issue open.

**Comment by Argesilao2** [comment]
Understood.
Thank you.
    Il giovedì 21 dicembre 2023 alle ore 21:49:20 CET, Wedge009 ***@***.***> ha scritto:  
 
 


This is the risk with playing the development releases, I think, that breaking changes like this can happen. If you wish to try continuing your original play-through, you can extract the text file from the save (assuming default compressed save games) and manually change the id and name field from Reshan to Resha.

Really not sure if that would work, however. You might be better off just starting the campaign from scratch - or revert to a 1.17 release before the change to Resha was made (looks like 1.17.21).

At any rate, this is an expected consequence of breaking changes during development so I don't think it's warranted to keep the issue open.
