### ISSUE TITLE
No laurel Crown in Delfador Memoirs

### ISSUE THREAD

**Issue by Argesilao2** [wesnoth/wesnoth#8141]
### Game and System Information

- **Version:1.17.23
- **Downloaded from:download page
- **Build info:**
- **OS:windows 11

### Description of the bug

Played and completed Delfador Memoirs, difficulty Great Mage (difficult), but tyhe laurel crown doesn't appears in the campaign list.

**Comment by Wedge009** [comment]
Can you find your `preferences` file (reference: https://wiki.wesnoth.org/EditingWesnoth) and see what's listed for the campaign completion section?

**Comment by Argesilao2** [comment]
This is what is present in the preferences file regarding completed campaigns
(ROH is an addon of mine that I'm testing)
[completed_campaigns] [campaign] difficulty_levels="HARD" name="Dead_Water" [/campaign] [campaign] difficulty_levels="HARD" name="Descent_into_Darkness" [/campaign] [campaign] difficulty_levels="HARD" name="Heir_To_The_Throne" [/campaign] [campaign] difficulty_levels="HARD" name="Liberty" [/campaign] [campaign] difficulty_levels="NORMAL" name="Northern_Rebirth" [/campaign] [campaign] difficulty_levels="NORMAL" name="ROH" [/campaign] [campaign] difficulty_levels="NORMAL" name="Secrets of the Ancients" [/campaign] [campaign] difficulty_levels="NORMAL" name="Son_of_the_Black-Eye" [/campaign] [campaign] difficulty_levels="HARD" name="The_Hammer_of_Thursagan" [/campaign] [campaign] difficulty_levels="NORMAL" name="The_Rise_of_Wesnoth" [/campaign] [campaign] difficulty_levels="NORMAL" name="The_South_Guard" [/campaign] [campaign] difficulty_levels="HARD" name="Two_Brothers" [/campaign][/completed_campaigns]
    Il giovedì 21 dicembre 2023 alle ore 21:53:45 CET, Wedge009 ***@***.***> ha scritto:  
 
 


Can you find your preferences file (reference: https://wiki.wesnoth.org/EditingWesnoth) and see what's listed for the campaign completion section?

**Comment by Wedge009** [comment]
If it's feasible, can you reply on GitHub directly when posting formatted text? E-mail replies lose the formatting.

(I tried to show the formatted text here but I'm getting a 'There was a problem saving your comment.' message from GitHub...)

Presumably the laurel is appearing for these campaigns you've listed. So the question is what's going on when Delfador's Memoirs completes. I'm not at my PC at the moment but I'll try to test it myself, later. Others are free to do so first, of course.

**Comment by Pentarctagon** [comment]
Reformatted:
```
[completed_campaigns]
    [campaign]
		difficulty_levels="HARD"
        name="Dead_Water"
    [/campaign]
    [campaign]
		difficulty_levels="HARD"
        name="Descent_into_Darkness"
    [/campaign]
    [campaign]
		difficulty_levels="HARD"
        name="Heir_To_The_Throne"
    [/campaign]
    [campaign]
		difficulty_levels="HARD"
        name="Liberty"
    [/campaign]
    [campaign]
		difficulty_levels="NORMAL"
        name="Northern_Rebirth"
    [/campaign]
    [campaign]
		difficulty_levels="NORMAL"
        name="ROH"
    [/campaign]
    [campaign]
		difficulty_levels="NORMAL"
        name="Secrets of the Ancients"
    [/campaign]
    [campaign]
		difficulty_levels="NORMAL"
        name="Son_of_the_Black-Eye"
    [/campaign]
    [campaign]
		difficulty_levels="HARD"
        name="The_Hammer_of_Thursagan"
    [/campaign]
    [campaign]
		difficulty_levels="NORMAL"
        name="The_Rise_of_Wesnoth"
    [/campaign]
    [campaign]
		difficulty_levels="NORMAL"
        name="The_South_Guard"
    [/campaign]
    [campaign]
		difficulty_levels="HARD"
        name="Two_Brothers"
    [/campaign]
[/completed_campaigns]
```

**Comment by gfgtdf** [comment]
https://github.com/wesnoth/wesnoth/issues/8090

**Comment by Wedge009** [comment]
I was wondering if that might have been related. Did you confirm it's the same issue?

@Argesilao2 Can you replay your final DM scenario or otherwise complete the campaign on 1.17.24 and see if that resolves it for you?

**Comment by Argesilao2** [comment]
I'll try.    Il venerdì 22 dicembre 2023 alle ore 03:23:48 CET, Wedge009 ***@***.***> ha scritto:  
 
 


I was wondering if that might have been related. Did you confirm it's the same issue?

@Argesilao2 Can you replay your final DM scenario or otherwise complete the campaign on 1.17.24 and see if that resolves it for you?

**Comment by Argesilao2** [comment]
With BfW 1.17.24 the laurel crown appeared.
    Il venerdì 22 dicembre 2023 alle ore 08:29:31 CET, Argesilao Argesilao ***@***.***> ha scritto:  
 
  
I'll try.    Il venerdì 22 dicembre 2023 alle ore 03:23:48 CET, Wedge009 ***@***.***> ha scritto:  
 
 


I was wondering if that might have been related. Did you confirm it's the same issue?

@Argesilao2 Can you replay your final DM scenario or otherwise complete the campaign on 1.17.24 and see if that resolves it for you?

**Comment by CelticMinstrel** [comment]
Alright, then we can close this.
