### ISSUE TITLE
[Utbs]Is it normal that Kaleh or Nym's level never changes?

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#8149]
### Game and System Information

- **Version:**1.17.24
- **Downloaded from:**build from source
- **Build info:**
- **OS:**widows7

### Description of the bug

When I try to evolve Kaleh, his stas increases (xp and hp) as well as his skills, but the level displayed remains 1, is this intended or not?

### Steps to reproduce the behavior

1Load game
2choose Utbs campaign or load savegame without external resource
3.evolve Kaleh several times with debug mode

### Expected behavior

We should expect the level to increase with each amla (every two amla) but this is no longer the case

**Comment by Hejnewar** [comment]
It is not but it is on my todo list for when I finally have time and will to finish balancing UtBS (probably January).

**Comment by newfrenchy83** [comment]
> It is not but it is on my todo list for when I finally have time and will to finish balancing UtBS (probably January).

[Youth.cfg.txt](https://github.com/wesnoth/wesnoth/files/13767075/Youth.cfg.txt)

this file contain an strategy for esolve that if it can help.
