### ISSUE TITLE
Events can be fired twice in a row

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#8157]
### Game and System Information

- **Version:** v1.17.24+dev (5be939a304b-Clean) x86_64
- **Downloaded from:** built locally
- **OS:** ArchLinux

### Description of the bug

Preload events can get executed twice, under specific conditions. This can be triggered when new event handlers are registered from a running event, as shown below.

### Steps to reproduce the behavior

1. Install this add-on: https://github.com/vgaming/_example_wesnoth/tree/main/example (the "example" directory of the repo)
2. Start Wesnoth-1.17 (development version)
3. Start a game with this example modification enabled

### Expected behavior

The message `loading main.lua` from `main.lua` should be shown exactly once.

Actual behavior: the message is shown multiple times.

*Importantly*, if you alter the Lua file `secondary.lua` and remove [lines 11-12](https://github.com/vgaming/_example_wesnoth/blob/main/example/lua/secondary.lua#L11-L12), then the double-execution bug disappears and the message from main.lua will only be shown once, as expected.

### Additional context

The fact that removing two lines from second file changes whether the first file is re-read is especially an indicator (to me) that the observed behavior is a bug. Note that it happens specifically with code that adds new events -- not just any code. Adding arbitrary random code to the second file does not trigger the behavior of executing main.lua twice.

**Comment by gfgtdf** [comment]
This is a bug in the event `execute_on_events` implementation, it only used an index in he event handlers list to make sure events are not fired twice, but adding an events with a priority might reorder the events list so that no longer works.

**Comment by gfgtdf** [comment]
here a simpler code to reproduce
```

	[event]
		name=recruit
		first_time_only=no
		[message]
			message = "recruit event"
		[/message]
		[event]
			name=moveto
			priority=1
			{VARIABLE moved yes}
		[/event]
		[event]
			name=moveto
			priority=1
			{VARIABLE moved yes}
		[/event]
	[/event]
```

**Comment by CelticMinstrel** [comment]
As @gfgtdf stated, and as I mentioned on IRC, this is not related to Lua at all. It's a bug in the even system.

**Comment by CelticMinstrel** [comment]
I think making a copy of the queue instead would fix the issue. It's just copying pointers so I doubt it would be a major performance impact.

**Comment by Pentarctagon** [comment]
IIRC on Discord gfgtdf said the issue with that approach was that events could alter the contents of the queue as they're being handled?

> if i for examepl make a copy of the  handler list matching the name, to loop over it, i not have to check that its okay when auch a variabels changes whiel fireing another event.

(on 12/28)

**Comment by gfgtdf** [comment]
That comment was about making a copy with all names whose names matches, instead of copying the whole list. Also i don't think thats that big of an issue, (it' won't break anything  in practice), my point was more that delayed name subsitition in event names makes the code more complicated and harder to maintain.
