### ISSUE TITLE
Linux packages totally out of date in Ubuntu APT and KDE Discover

### ISSUE THREAD

**Issue by stepo2** [wesnoth/wesnoth#8170]
### Game and System Information

Tuxedo OS (based on Ubuntu 22.04 "jammy") using KDE Plasma with default repos (Ubuntu APT and Flathub), assuming the behaviour is true for all recent Ubuntu+KDE-based distros.

### Description of the bug

Using KDE Plasma "Discover" (integrated GUI for installing programs) I get 1.16.2 (_not_ 1.16.11) from APT (official Ubuntu jammy release channel) and I get 1.14.17 using the Flatpak source. Using the command `flatpak install org.wesnoth.Wesnoth` I get a selection between "1.14.17" and "stable" (which actually is latest 1.16.11).

So, the only way to get the latest release on KDE Plasma is to use the command line flatpak command. This seems a bit user unfriendly and un-intended. Flatpak should give "stable" as default. And Ubuntu APT is on Wesnoth 1.16, so it should always have the latest minor releases as well.

### Steps to reproduce the behavior

1. have a recent Ubuntu-based distro with KDE Plasma
2. Try to install Wesnoth 1.16.11

### Expected behavior

Getting Wesnoth latest 1.16.xx per default using APT or Flathub.

**Comment by loonycyborg** [comment]
That's probably should be filed to KDE Discover's tracker. I'm not even sure how it determines which version to show. Maybe some stale cache somewhere. I'm using gnome here and gnome software not only shows latest version but also automatically updates it.

**Comment by Pentarctagon** [comment]
We have no control over how any software center handles Wesnoth nor over what version Ubuntu packages with a particular OS version. Notably, https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/2033222 is also an issue as well, which we can't fix for the same reasons. You would need to file issues with Ubuntu and KDE to address this issue.

**Comment by loonycyborg** [comment]
1.14 being available too is intended. Save compatibility isn't maintained for major version bumps like 1.14->1.16->1.18 so people should be able to install old version to finish their campaigns. APT and flathub are totally different things that don't know much about each other and it's distro's and Discover's/gnome-software's job to present this to users. We have very little influence besides calling one of our versions "stable" in flathub to show that's what we want most people to install. Maintaining APT is entirely in distro's purview.

**Comment by Pentarctagon** [comment]
Wesnoth is packaged by a variety of Linux distros which often have their own way of doing things, so there being differences between them is unavoidable. I can't explain why KDE Discover is handling Wesnoth differently (apparently worse) than Gnome's software center does, for example. As another example, Ubuntu not having the most recent version available is a packaging decision on their part - you can only get updated Wesnoth versions by upgrading the whole OS and never related to when we released a new version. As another example - Fedora had their own independent Flatpak repository which they build Wesnoth for which is entirely separate from Flathub.

We have basically no control over how any of that works or is decided. If you want to have the latest version available, then your best bet is to use one of:
* Steam
* Flathub (via https://flathub.org/apps/org.wesnoth.Wesnoth)
* A rolling release distro (ie: Arch)

**Comment by sevu** [comment]
The reason why they are shown separately might be because one has the id _org.wesnoth.Wesnoth_ and the other _org.wesnoth.Wesnoth-1.16_

**Comment by pehjota** [comment]
Ubuntu LTS being outdated is a regular problem.  Ubuntu has only 6,090 packages [1] in jammy/main that are officially maintained, and wesnoth-1.16 is not one of them.  All of the other 58,923 packages [2] in jammy/universe are maintained by [a relatively small team of 122 people](https://launchpad.net/~motu).  Of those 58,923 packages, only 89 [3] have been backported.  It might help if it were easier for the thousands of Debian contributors to help maintain their own packages in Ubuntu...

Debian bullseye (current oldstable, more comparable in age to Ubuntu jammy than current Debian stable) on the other hand has 3,200 [4] of its 58,612 [5] packages backported, including wesnoth-1.16.  And I'm hoping to soon help get the new Wesnoth 1.16.11 into Debian (which currently has 1.16.10 in testing and unstable), which will then go into Ubuntu noble 24.04 LTS (and then likely stagnate as usual, unfortunately).

References:
1: `wget -q -O - http://archive.ubuntu.com/ubuntu/dists/jammy/main/binary-amd64/Packages.xz | unxz -c | grep '^Package:' | wc -l`
2: `wget -q -O - http://archive.ubuntu.com/ubuntu/dists/jammy/universe/binary-amd64/Packages.xz | unxz -c | grep '^Package:' | wc -l`
3: `wget -q -O - http://archive.ubuntu.com/ubuntu/dists/jammy-backports/universe/binary-amd64/Packages.xz | unxz -c | grep '^Package:' | wc -l`
4: `wget -q -O - http://deb.debian.org/debian/dists/bullseye-backports/main/binary-amd64/Packages.xz | unxz -c | grep '^Package:' | wc -l`
5: `wget -q -O - http://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages.xz | unxz -c | grep '^Package:' | wc -l`

**Comment by pehjota** [comment]
I just remembered seeing ppa [branches](https://salsa.debian.org/games-team/wesnoth/-/branches/all) in Debian's wesnoth packaging Git repository.  The Debian Games Team has [a PPA with Wesnoth](https://launchpad.net/~pkg-games/+archive/ubuntu/wesnoth-devel) 1.16.10 (which may soon become 1.16.11) for jammy and other Ubuntu releases.  Hope this helps!
