### ISSUE TITLE
teleport.cpp uses assertions to validate WML

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#8175]
The code at https://github.com/wesnoth/wesnoth/blob/963029dd7cec3958f37e006b6a7cd1438b2d37bc/src/pathfind/teleport.cpp#L44-L66

should use the VALIDATE macro instead of asserts to check for WML attributes and tags.

**Comment by stevecotton** [comment]
Fixed in #8223, thanks to @dsfb.
