### ISSUE TITLE
Better way to determine the number of custom AMLAs a unit has received

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#8179]
#8152 uses max_experience to determine when to increment the unit's level so that it doesn't stay as level 1 forever. However that's a fragile approach, so it would make sense for there to be a more reliable way to get that information.

**Comment by CelticMinstrel** [comment]
A simple approach is to simply expose the modifications array to Lua and WFL. Then you could use `#unit.modifications.advancement` to get the number of AMLAs that have been applied. As a bonus you can also detect the number of traits or objects with this method, and even inspect the modifications to determine their effects or filter data.

**Comment by gfgtdf** [comment]
you can already use __cfg for such a approach (and i explained in that other pr why i think it is at least in the  current form not a very good approach). unrelated to that it might be nice to have `unit.modifications` though to allow writing unit modifications.
