### ISSUE TITLE
Recall costs in UtBS

### ISSUE THREAD

**Issue by Argesilao2** [wesnoth/wesnoth#8183]
### Describe the desired feature

The idea of the new recall cost system is interesting, but it absolutely requires adjustments; or in the definition of the difficulty of the campaign (i.e. difficult becomes nightmare, challenging becomes difficult and so on), or in the assignment of economic resources.
In fact, with the new recall method, the human player's old gold resources are absolutely inadequate.
In the last scenarios of the campaign, when it is absolutely necessary to have units of a level higher than 1, the only way to have them is to recall them from the recall list; with the old method the player could also recruit three level 3 and 4 units with 60 gold pieces, with the new method he can only recruit 1.
It is true that the human player can call up many more level 1 units, but he can only do this if he has recruited several of them in previous scenarios and if he has not lost them; not to mention that the recruit cost of Quenoth's level 1 units is quite high compared to their real combat value.
Finally, level 1 Quenoth units are practically useless when facing level 2 or higher enemy units.

**Comment by Hejnewar** [comment]
What difficulty did you play on?

**Comment by Argesilao2** [comment]
I'm playing in difficult.But the real problem is that for the same amount of gold available for both human player and enemies in the version with normal recall and the current one, the current one is more disadvantageous than the normal one; the campaign it isn't impossible, but more difficult.

    Il lunedì 1 gennaio 2024 alle ore 09:36:38 CET, Hejnewar ***@***.***> ha scritto:  
 
 


What difficulty did you play on?

**Comment by Hejnewar** [comment]
I understand that I was just curious. Honestly its pretty nice achievement to reach that far before the rebalance (which im hoping I will finish soon). What almas did you go for?

**Comment by Argesilao2** [comment]
To tell the truth, I'm stuck at the penultimate combat scenario (Blood is Thicker than water), and I'm still trying to understand how to overcome it in a short time (to have more gold available for the last one) and with few losses, without resorting to compulsive, and annoying, reloading.I noticed the balance issue I reported when playing the previous scenario (Out of the Frying pan) while in the previous scenarios the problem is much less noticeable, because three or four high-level units are enough, as the heroes are already in a state of considerable advancement.
Regarding the amlas, I tried to make both Nym and Kaleh have bolas, because being forced to use low level units, or very few high level units, I needed to reduce the damage that high level enemy units could inflict.
The Rain of arrow is interesting, but it deals too little damage to enemy units to be truly useful.For the rest I was rather conservative, not having fully understood what some advancements are for.

    Il lunedì 1 gennaio 2024 alle ore 13:36:35 CET, Hejnewar ***@***.***> ha scritto:  
 
 


I understand that I was just curious. Honestly its pretty nice achievement to reach that far before the rebalance (which im hoping I will finish soon). What almas did you go for?

**Comment by Hejnewar** [comment]
That's interesting to hear, it will certainly be an achievement if you manage to win it. 

When it comes to AMLAs I already buffed rain of arrows upgrade to deal iirc 10-2 instead (toxic rain was also buffed while I was at it). There are still few underpowered AMLAs like Opportunist for Kaleh that are still severely underpowered (that's completely my mistake for designing very cool AMLAs that works great... In MP) fortunately there aren't very many of them. Bolas are generally pretty strong but in my experience I often find myself lacking a reliable melee damage source so I usually level at least one of them as melee fighter. 

Can you give an example of not fully well understood AMLA?

**Comment by Argesilao2** [comment]
I have to admit that I didn't fully understand the usefulness of the taunt ability; to be clearer: I understand that forcing an opposing unit to attack Kaleh can be a good way to be reasonably certain of eliminating it; however I believe that the cases in which such a skill is useful are rather limited, and I wonder if it is worth sacrificing another advancement to acquire such a skill.Then there is an advancement, I do not remember the name, with the symbols of a foot, but it doesn't seem to increase the unit's movement points.
    Il lunedì 1 gennaio 2024 alle ore 17:52:44 CET, Hejnewar ***@***.***> ha scritto:  
 
 


That's interesting to hear, it will certainly be an achievement if you manage to win it.

When it comes to AMLAs I already buffed rain of arrows upgrade to deal iirc 10-2 instead (toxic rain was also buffed while I was at it). There are still few underpowered AMLAs like Opportunist for Kaleh that are still severely underpowered (that's completely my mistake for designing very cool AMLAs that works great... In MP) fortunately there aren't very many of them. Bolas are generally pretty strong but in my experience I often find myself lacking a reliable melee damage source so I usually level at least one of them as melee fighter.

Can you give an example of not fully well understood AMLA?

**Comment by Hejnewar** [comment]
Let me explain then Run By (Taunting Strike) is an AMLA that makes taunting strike cost 0 mp, usually attacking takes away all your mp, but with Run By you can still move after using that attack. Taunted enemies not only attack Kaleh, they also should chase him and if they dont catch him nor have any other target their turn is basically wasted. 

Im already buffing Taunting Strike to also have 30% parry because I felt like Kaleh was taking too much damage while taunting enemies I will probably also buff Run By because right now the game doesnt show anything in the unit changing... So yeah no surprise you didnt know what it did.

**Comment by FyiurAmron** [comment]
I second that the later AMLAs are poorly documented and need to be verified by trial-and-error. (the +10% to defense one e.g.) - in general, an AMLA of this kind should add an ability, and that ability should have the usual tooltip and help. If it doesn't, then it's obscure.

**Comment by Argesilao2** [comment]
Thank you for the explanation.
    Il lunedì 1 gennaio 2024 alle ore 21:18:05 CET, Hejnewar ***@***.***> ha scritto:  
 
 


Let me explain then Run By (Taunting Strike) is an AMLA that makes taunting strike cost 0 mp, usually attacking takes away all your mp, but with Run By you can still move after using that attack. Taunted enemies not only attack Kaleh, they also should chase him and if they dont catch him nor have any other target their turn is basically wasted.

Im already buffing Taunting Strike to also have 30% parry because I felt like Kaleh was taking too much damage while taunting enemies I will probably also buff Run By because right now the game doesnt show anything in the unit changing... So yeah no surprise you didnt know what it did.
