### ISSUE TITLE
Error message when Nym using the Rain of arrow attack

### ISSUE THREAD

**Issue by Argesilao2** [wesnoth/wesnoth#8184]
### Game and System Information

- **Version: 1.17.24
- **Downloaded from:download page
- **Build info:**
- **OS:windws 11

### Description of the bug

When Nym uses the Rain of arrow attack appears this:

[store_unit_defense] has been deprecated and will be removed in version 1.17.0; This functions returns the chance to be hit, high values represent bad defenses.
Using [store_unit_defense_on] is recommended instead. (2)

**Comment by Hejnewar** [comment]
It seems like someone forgot to remove it in 1.17.0 since we are in 1.17.24 but yeah fixed already actually, just not commited.
