### ISSUE TITLE
[UtBS] Descending into Darkness Event 7: End of the River text doesn't make sense for flying units

### ISSUE THREAD

**Issue by FyiurAmron** [wesnoth/wesnoth#8188]
### Game and System Information

- **Version:** 1.17.24
- **Downloaded from:** itch.io
- **Build info:** N/A
- **OS:** any

### Description of the bug

The text says "This is the end of the line. The water is too deep for me to continue any further. I’m freezing cold, wet, and I can’t see a thing. (...)" - this doesn't make any sense when triggered by a flying unit, especially taking into account that flying units can easily continue further along the river. Also, it's really easy to miss this at all with a flying unit, because the event trigger is `moveto` and not `exit_hex` nor `enter_hex`.

### Steps to reproduce the behavior

* go to x=3 y=10 with a flying unit, get the text that makes no sense in the context since unit can continue further anyway
* skip x=3 y=10 and just go further north with a flying unit, don't get the text at all

### Expected behavior

Either no trigger at all for flying units, or a reasonable text that would interrupt the movement of flying units and that couldn't be missed then, or make the rest of the river inaccessible to flying units.

### Additional context

The "flying unit" will usually be Quenoth Shyde at this point.

**Comment by stevecotton** [comment]
I'd like to have terrain graphics for the cave ceiling coming down to the water level; I thought there was already an issue for that, but can't find it.
