### ISSUE TITLE
[UtBS] Dust Devil speaking although mute

### ISSUE THREAD

**Issue by FyiurAmron** [wesnoth/wesnoth#8192]
### Game and System Information

- **Version:** 1.17.24
- **Downloaded from:** itch.io
- **Build info:** N/A
- **OS:** any

### Description of the bug

E.g. in In the Tunnels of Trolls, Dust Devil can "bury the bones", and the dialogue will be attributed to him. However, "Descending into Darkness" clearly states: `# Dust devil is supposed to be mute` - although it mentions "[in] the other cases, [N]ym could plausibly speak the line", the campaign doesn't actually do this. I recall the probably were other similar cases scattered throughout UtBS TBH.

### Steps to reproduce the behavior

1. go to "In the Tunnels of Trolls"
2. use Dust Devil to bury the bones of the dead dwarf

### Expected behavior

Dust Devil should stay mute 100% of the time.

**Comment by Wedge009** [comment]
Not the first time Dust Devil is treated as a normal speaking unit by mistake, eg #4892.
