### ISSUE TITLE
UtBS S01: Events trigger on wrong hexes when going clockwise (east from start)

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8201]
### Game and System Information

- **Version:** 1.17.24+dev (13d568248733f2598b37076860625144bdb05c3e)
- **Downloaded from:** Git

### Description of the bug

The first half of S01, exploring the village, can be done either clockwise (going east at the start), or counterclockwise (south at the start) around the lake. The opening dialog suggests south or east, alternatively ignoring the dialog and instinctively capturing the village triggers the first event, and leads to continuing in a counterclockwise direction.

https://github.com/wesnoth/wesnoth/blob/3e41aa0dc56fcf32e1bece97af156c357718d9c0/data/campaigns/Under_the_Burning_Suns/scenarios/01_The_Morning_After.cfg#L261-L267

However, following Kaleh's suggestion and going clockwise leads to the Dustboks (the events here feel correct), meeting Garak (also feels correct).

However, the next event has broken shroud when approached clockwise:

![image](https://github.com/wesnoth/wesnoth/assets/101462/28cb2bcb-bcb4-4a98-ad50-4289f1459a90)

And the area that would be the first event let Nym walk between the spawn points of the mudcrawlers without triggering; the difference between these two images is just moving the Quenoth Scout a couple of hexes to capture the village:
![image](https://github.com/wesnoth/wesnoth/assets/101462/d532a4ea-100d-46c2-9d68-09ec42dae335) ![image](https://github.com/wesnoth/wesnoth/assets/101462/8b8e47cb-6161-4841-9b6b-7a69f4e7e6a7)

### Expected behavior

Either make the triggers work correctly when going clockwise, or make the first counterclockwise event trigger automatically if the player starts by going clockwise. Triggering that event at the start of turn 2 seems reasonable, Vecnu's shout of "Kaleh, Nym, help us" fits naturally no matter which direction they're going.

**Comment by Wedge009** [comment]
Funny, I had no idea either option was meant to be valid - I've always gone south, or anti-clockwise, every time I've played this. Certainly if the intention is to treat either direction as valid then the events should work as such.

**Comment by Konrad22** [comment]
Btw, I feel like the events were designed under the assumption of splitting Kaleh and Nym, one going east, one going south. For example, lamenting over the destroyed keep, the lack of survivors and the lack of a leader feels weird when 1) you have already explored the whole village and 2) you have both Zhul and Garak, who are pretty decent candidates for leadership.
