### ISSUE TITLE
Wesnoth 1.16.11: macOS installation disk image is corrupted and checksum does not match

### ISSUE THREAD

**Issue by JD-Veiga** [wesnoth/wesnoth#8208]
### Game and System Information

- Wesnoth 1.16.11
- Website (sourceforge)
- Stable
- macOS 10.15 (Catalina)

### Description of the bug

The macOS installation disk image `Wesnoth_1.16.11.dmg` is corrupted (it raises a warning about opening it). 

Additionally, its checksum (8cd4af79e180ae90fbdbf740d63f26b0ac05826230eddd96b88c895f59a6525f) does not match the expected sum provided in the website (e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855).

### Steps to reproduce the behavior

1. Open `Wesnoth_1.16.11.dmg` with `DiskImageMounter.app`.
2. During verification of the disk image, a message pops out "There may be a problem with this disk image. Are you sure you want to open it?"
3. `shasum -a 256 Wesnoth_1.16.11.dmg` outputs `8cd4af79e180ae90fbdbf740d63f26b0ac05826230eddd96b88c895f59a6525f`.

### Expected behavior

- Disk image must be verified without failure.
- Checksum must be correct.

### Additional context

Maybe the disk image is bad (not the application itself).

Thank you.

**Comment by Pentarctagon** [comment]
Corrected the checksum.

**Comment by hrubymar10** [comment]
I can confirm that the `Wesnoth_1.16.11.dmg` diskimage should have the checksum that @JD-Veiga mentioned:
```
$ shasum -a 256 Wesnoth_1.16.11.dmg
8cd4af79e180ae90fbdbf740d63f26b0ac05826230eddd96b88c895f59a6525f  Wesnoth_1.16.11.dmg
```

I can also confirm that this diskimage is THE diskimage which I created and pushed for notarization:
```
$ spctl -a -t open --context context:primary-signature -v Wesnoth_1.16.11.dmg
Wesnoth_1.16.11.dmg: accepted
source=Notarized Developer ID
```

So no problems with this here.

Now to the topic that macOS 10.15.x (Catalina) shows the problem popup - To be honest I don't know. It's not the first time that happened. For some reason Apple likes to change (maybe harden) their signing/notarizing algorithms and as the result older systems stops reading those signatures correctly 😔 🤦 .

Thank you for noticing the incorrect sha256 published on website. The one published alongside the .dmg archive on SF was correct, but regarding the latter I would suggest either ignore the error (yeah, I know how it sounds) or use different distribution. For stable 1.16.x cycle there is also [Mac AppStore](https://apps.apple.com/cz/app/the-battle-for-wesnoth/id1450738104?mt=12) app available which should work just fine. Other options are [ich.io](https://wesnoth.itch.io/battle-for-wesnoth) or [Steam](https://store.steampowered.com/app/599390/Battle_for_Wesnoth/).

I believe that this issue can be closed? @JD-Veiga

**Comment by JD-Veiga** [comment]
I think that @hrubymar10 is right about the disk image.

I have tried to mount the disk images of versions 1.16.10 and 1.16.11 from terminal with: `hdiutil attach Wesnoth_1.16.10.dmg` and `hdiutil attach Wesnoth_1.16.11.dmg` and have got the same warning in both cases: "There may be a problem with this disk image. Are you sure you want to open it?" (although only 1.16.11 shows the GUI message when mounting via `DiskImageMounter`).

So I think that it fine though weird.

Thank you, @hrubymar10.
