### ISSUE TITLE
upgrade optional unit advancement macros

### ISSUE THREAD

**Issue by MXB2001** [wesnoth/wesnoth#8219]
### Describe the desired feature

Currently they're simply a modify unit type tag. Unfortunately they can be double or even triple loaded if more than one mod is active and uses them. If the tags were wrapped in a ifndef enable_advance_whatever and then after that it is defined it would prevent loading them more than once.
There is no conceivable use for loading these canned advancements more than once, it just adds a duplicate entry (and forces user interaction to choose one of the identical choices).

Example: era has enable_wolf_advancement included in its era tag and if you activate a modification that also includes it then it gets loaded twice and the level 1 wolf now has 2 identical advancements to greater wolf

I know of 3 eras that use it and 2 modifications that do.

**Comment by gfgtdf** [comment]
> . If the tags were wrapped in a ifndef enable_advance_whatever and then after that it is defined it would prevent loading them more than once.

I don't see how that could solve the problem, but i agree that the current solutions has its problems.

We could for example simply make the game discard duplicates in the advancement list, or we could give those tags an id and prevent those tags to be executed twice it they have the same id, or we make those macros expand to [load_resource], and add a bunch of [resource]s to mainline that contain the [modify_unit_type] as [load_resource] already has checks to make sure things are only loaded once.

Not sure yet what the best fix would be.

**Comment by gfgtdf** [comment]
wait, it seems like this is already implemented https://github.com/wesnoth/wesnoth/pull/7743
