### ISSUE TITLE
Show death and level-up animations while replaying saves with "Skip animation"

### ISSUE THREAD

**Issue by demario-w** [wesnoth/wesnoth#8227]
### Game and System Information

- **Version: The Battle for Wesnoth version 1.17.23+dev x86_64**
- **Downloaded from: Default**
- **OS: Running on Debian GNU/Linux**

### Description of the bug

When checking the "Skip animation" toggle when replaying a save, the animations for death and level-up are still played at nominal speed.

### Steps to reproduce the behavior

- Load a save.
- Enable the "skip animation" toggle.
- Replay until one unit dies or levels up
- Watch animations

### Expected behavior

These animations are skipped when enabling the "skip animation" toggle.

**Comment by Pentarctagon** [comment]
Does this happen with 1.16?

**Comment by Discontinuum** [comment]
No. On 1.16 it skips all animations.

**Comment by gfgtdf** [comment]
My bet would be that it is because this line

https://github.com/wesnoth/wesnoth/blob/a5825a58c70351404e09ea131c259e8d471157de/src/replay.cpp#L689

was removed in

https://github.com/wesnoth/wesnoth/commit/99be6c52a44ea4321109080da87fbe5fb5391500

**Comment by Pentarctagon** [comment]
Looks like not just that line probably? The whole update_locker was removed.

**Comment by Pentarctagon** [comment]
Tested and confirmed that https://github.com/wesnoth/wesnoth/commit/99be6c52a44ea4321109080da87fbe5fb5391500 caused the issue.
