### ISSUE TITLE
Can't proceed to the next level in MP campaign if the save loaded from the mainmenu

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#8230]
### Game and System Information

- **Version:** 1.16.*

### Description of the bug

If you load a save from an MP campaign (like World Conquest) from the main menu (through Load button), it loads and plays fine till the end, but when you finish and proceed to the next level, it returns you back to the main menu instead

### Steps to reproduce the behavior

1. Start some MP campaign
2. Start Wesnoth, click Load, load an MP campaign save
3. Finish the scenario and proceed to the next (debug next_level will reproduce as well as intended scenario finish)

### Additional context

You can still play MP campaign saves locally if you load then with Multiplayer > Local Game > Load Game, this way everything works

**Comment by gfgtdf** [comment]
I assume you are using debug mode, this is a known issue https://github.com/wesnoth/wesnoth/issues/7478

**Comment by Discontinuum** [comment]
Oops, indeed
