### ISSUE TITLE
[EI] Safyam in 04b is male but is mentioned as female

### ISSUE THREAD

**Issue by tamanegi-jp** [wesnoth/wesnoth#8233]
### Game and System Information

- **Version: 1.17.24+dev**
- **Downloaded from: github**
- **Build info: none**
- **OS: common**

### Description of the bug

In scenario 04b, Safyam is mentioned as female in the following message (speaker=Hahid al-Ali; in Eastern_Invasion/scenarios/04b_Ill_Humors.cfg ), while Safyam is male according to the unit definition.

"Thanks to my cure made from this marvelous herb, **she** is now immune to the swamp’s ill humours! With more, I can make an antitoxin strong enough to cure the draught of death itself!"

Safyam definition (also in 04b_Ill_Humors.cfg):
```
        [unit]
            side=4
            x,y=17,21
            name= _ "Safyam"
            id="Safyam"
            type=Dune Burner
            [modifications]
                {TRAIT_MERCENARY}
                {TRAIT_QUICK}
            [/modifications]
            facing=se
            [status]
                poisoned=yes
            [/status]
        [/unit]
```

Some fix may be necessary.

**Comment by soliton-** [comment]
@Dalas121 was the unit meant to be female or is the text wrong?

**Comment by CelticMinstrel** [comment]
According to the Dunefolk name generator, "Safyam" is a female name.

**Comment by Dalas121** [comment]
Intended to be female, not male.

**Comment by TheFlamelet** [comment]
what does Safyam mean?

**Comment by CelticMinstrel** [comment]
It probably doesn't have a meaning. I don't know exactly how @Dalas121 came up with it, but I would guess he ran Wesnoth's random name generator somehow until he found one that sounded good – the name is composed of the elements "saf" and "yam", which are chosen to give a vaguely Arabic or Persian flair, but I don't think they have any inherent meaning.

@Dalas121 is welcome to correct me if I'm wrong on any detail there.

**Comment by Dalas121** [comment]
Yep, @CelticMinstrel is correct here.  No inherent meaning; I created random female burners until I found one with a name that I liked.
