### ISSUE TITLE
[EI] Scenario 12: last breath for non-existent unit id=Ran-Lar

### ISSUE THREAD

**Issue by tamanegi-jp** [wesnoth/wesnoth#8242]
### Game and System Information

- **Version: 1.17.24+dev**
- **Downloaded from: github**
- **Build info: none**
- **OS: common**

### Description of the bug

In the scenario 12 "Evacuation" of EI, there is a last breath event for id=Ran-Lar.
But id=Ran-Lar does not exist in the campaign, only appears in this last breath event.
There are no comments in the scenario file; this may not be a some kind of Easter egg.
(The last breath event is defined in "Eastern_Invasion/scenarios/12_Evacuation.cfg" file.)

Most probably, this last breath event is for id=Rakkha who is one of the enemy leaders in this scenario.
Rakkha does not have last breath event while other enemy leaders do.

**Comment by Wedge009** [comment]
It looks like this was introduced in #7815. Before that, Ran-Lar was the leader of side 4, but as you observed this was changed to Rakkha. Perhaps @Dalas121 can confirm whether or not Ran-Lar was indeed meant to become Rakkha.
