### ISSUE TITLE
Feature request: add "Start Game" shortcut / hotkey

### ISSUE THREAD

**Issue by vgaming** [wesnoth/wesnoth#8250]
Is it possible to add a shortcut for this?:
![2024-01-16_09 07 39ed](https://github.com/wesnoth/wesnoth/assets/33452702/2243a8af-1ff7-4947-9f9c-49a0bebc9938)

Currently, it is possible to:
* (start the game)
* use the `m` shortcut to open the multiplayer menu
* use `⬆️` `⬇️` to navigate to a local game (for example)
* press `Enter` to enter map selection mode
* use `⬆️` `⬇️` to select the desired map
* use `Enter` to start the map

There's just one piece missing from being able to start the game -- that is a shortcut to actually start the game, triggering the same action as on the screenshot above.

Proposed changes are:
* Add a shortcut for this button, such as `Ctrl K` or `Ctrl G` (for "go") or `Ctrl Enter` if nobody objects.
* (Optional) Make the shortcut discoverable by hovering the button.

Thoughts? Thanks! :heart:

**Comment by vgaming** [comment]
Note that there is an older issue with a similar context, here: https://github.com/wesnoth/wesnoth/issues/2674
However, the older one was focused on screen resolutions, whereas I think this feature is useful universally by players, for any screen resolution or button layout.

**Comment by babaissarkar** [comment]
Should be resolved by 1c50ed525b9d9e3956964d68cf5fe292f353bbf7.
Used Ctrl+G as shortcut as Enter or any combination of it is disabled for dialog already.
