### ISSUE TITLE
Assertion when logging large essages on windows

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#8255]
Version: 1.17.23
OS: windows

It was observed here https://forums.wesnoth.org/viewtopic.php?p=685869#p685869 that an assertion inside  boost/iostreams/tee.hpp can fail under specific circumstances 
![image](https://github.com/wesnoth/wesnoth/assets/4893136/7d4b447f-a185-426d-a920-02b57eb19506)

Since the only code that uses iostreams/tee.hpp is the logging code and since  i got a very long error message when trying it, i i'm pretty sure that that is is cause. 

It would be nice if someone using windows could try to reproduce (just dump a big wml object into the logger)

**Comment by Pentarctagon** [comment]
@loonycyborg FYI

**Comment by Wedge009** [comment]
This is exactly the same bug I encountered in #8024 albeit at start-up and it crashed silently, ie didn't even get to the initial Wesnoth loading screen so it appeared as though the application didn't even run.

**Comment by Wedge009** [comment]
With my situation it only happened on start-up, no assertion messages. With this report it appears to be during a scenario during use. I was only reporting for my situation, I didn't encounter the issue with official builds so I assumed it was the fault of my compilation.

My expectation is the Steam release build is the same as what's offered on sourceforge/itch, but I could be wrong.
