### ISSUE TITLE
Image scaling regression

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#8275]
### Game and System Information

- **Version:**
- v1.17.24+dev (d9aa71ac867)
- **Downloaded from:**
- here
- **Build info:**
- scons
- **OS:**
Linux

### Description of the bug

Something has gone wrong with the scaling recently (maybe last couple weeks?)  It's more noticeable in sloppier portrait images, but it shows on mainline too.  I compare it to 1.16 here (need to click the image, don't just glance at the preview)
![Screenshot_20240121_scaling](https://github.com/wesnoth/wesnoth/assets/13510196/e15dcec7-07b1-4bd7-bf03-4bcdc308d615)

### Steps to reproduce the behavior

start wesnoth, go to help browser and look up units with both M/F versions

### Additional context

I'm going to call this a blocker because it looks worse than the current stable version, and lot of work went into the graphics/display for upcoming version.  This would undercut that rollout.

**Comment by gfgtdf** [comment]
> Something has gone wrong with the scaling recently (maybe last couple weeks?) It's more noticeable in sloppier portrait images, but it shows on mainline too. I compare it to 1.16 here (need to click the image, don't just glance at the preview)

I think 1.16 doesn't scaled the images at all. So i kinda doubt that this is related to recent changes, maybe someone can test 1.17.10 or something like that? Note that wesnoth only starts to scale after a certain windows size.

**Comment by Wedge009** [comment]
I can't see/read the image that the image links points to.

https://private-user-images.githubusercontent.com/13510196/298423994-e15dcec7-07b1-4bd7-bf03-4bcdc308d615.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDYwNzAsIm5iZiI6MTcwNjA0NTc3MCwicGF0aCI6Ii8xMzUxMDE5Ni8yOTg0MjM5OTQtZTE1ZGNlYzctMDdiMS00YmQ3LWJmMDMtNGJjZGMzMDhkNjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIxMzYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDIwOTUxOWYwYzMzMmI4NjJlNTA1MzkyNWJkN2RjMTQ1ZGY3MTRlYzhjOGFkNGRjNWE3NTBhNmE5YTYxZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hYVXqu-Bp0m0GAMDbmlzjbK0AblpgJjb1vJ30tw5T_4

**Comment by Wedge009** [comment]
Aforementioned change was ca366554a0a3fe762c92a1210cc00df4ff3b9cf9.

**Comment by Wedge009** [comment]
BTW, not saying it's not a real issue, but AFAIK confirmed label shouldn't be used till it's actually confirmed.

**Comment by Pentarctagon** [comment]
So it'd just be changing `return resize_mode::scale_sharp;` to `return resize_mode::scale;` then?

**Comment by CelticMinstrel** [comment]
It would be nice if that were the case, but that commit is touching GUI2 while the screenshots appear to be from in-game help.

@doofus-01 Do you see this issue anywhere other than in the help?

**Comment by doofus-01** [comment]
I'd noticed the issue in [message], but it was with an old UMC portrait, I don't have proof that it impacts mainline outside the help browser.

**Comment by Pentarctagon** [comment]
What resolution are you using? I can't reproduce this on Linux at 2560x1440.

**Comment by gfgtdf** [comment]
On thing still confuses me about this bugreport:

When i tested it, the  images on 1.17 were simply 2x the size as on 1.16 (if the window is big enough)
In the first post of this report all the protraits have the same size though. @doofus-01 did you scale the images for the sake of this report to make them comparable, or do the images show in the same size for you in 1.16 and 1.17?

**Comment by Wedge009** [comment]
I'm not sure what to look for. But I'm comparing 1.16.11 Steam release with 1.17.25+dev (4c87a4be74f) self-compiled, both on Linux/X11, Wesnoth showing as a maximised window on a UHD screen. Any difference is subtle and most noticeable in the sprites rather than the portraits.

1.16.11
![image](https://github.com/wesnoth/wesnoth/assets/13679322/6b9dd0ee-afb6-4321-8c20-a0bec8d44318)

1.17.25
![image](https://github.com/wesnoth/wesnoth/assets/13679322/6dbfbb33-c745-48c1-86e0-278fbf4e9ddb)

**Comment by gfgtdf** [comment]
> Any difference is subtle and most noticeable in the sprites rather than the portraits.

i think The sprites are a different  issue, maybe the removal of xbrz

**Comment by Wedge009** [comment]
Yes, I expect so, since it looks related to sprite-level interpolation rather than image scaling.

**Comment by doofus-01** [comment]
> When i tested it, the images on 1.17 were simply 2x the size as on 1.16 (if the window is big enough)

Making images bigger isn't usually an issue, as far as I noticed, it's the down scaling that happens with M/F portraits in the help browser (for many resolutions) that is simplest to reproduce.

>  @doofus-01 did you scale the images for the sake of this report to make them comparable, or do the images show in the same size for you in 1.16 and 1.17?

Of course not, that would be a pretty strange thing to do.

> What resolution are you using? I can't reproduce this on Linux at 2560x1440.

2457x1243 and similar show this for me.  It seems pretty noticeable on the female Mage of Light face, it affects some images more than others.

**Comment by Wedge009** [comment]
I compiled at commit d9aa71ac867d0fd41db9d509d413c4c7eced2797 and set window size to QHD but still can't replicate this. Zooming in via image editor, I can't see any discernible difference in scaling between this commit, current master, or 1.16.11 release. All on Linux/X11.

For those who can see this issue, what are your graphics hardware/drivers?

**Comment by Pentarctagon** [comment]
Out of curiosity, does it also happen with the flatpak or steam versions?

**Comment by Pentarctagon** [comment]
@doofus-01 the two options (nearest, which is the current default being used, or linear) for scaling are below. These are the only two options available: https://wiki.libsdl.org/SDL2/SDL_HINT_RENDER_SCALE_QUALITY

Nearest:
![Screenshot from 2024-02-07 14-08-33](https://github.com/wesnoth/wesnoth/assets/3030250/de2b5e74-25c3-4c58-a28a-e3294df8c903)

Linear:
![Screenshot from 2024-02-07 13-25-54](https://github.com/wesnoth/wesnoth/assets/3030250/7a9e24b0-3f7e-480b-b49c-42e5ff8da0b8)

**Comment by Wedge009** [comment]
That would explain why I don't see any scaling because I disable the auto-scale and leave it at 1x, since I find 2x too big.

Nonetheless, manually setting to 2x scaling doesn't look like either of those examples, neither excessively blurry (linear) nor pixelated (nearest).
![image](https://github.com/wesnoth/wesnoth/assets/13679322/6b53a36a-032d-4eff-b4a5-cb287a8a155d)
(this is from 1f1a68e94e0)

**Comment by Pentarctagon** [comment]
What's your screen resolution? Setting the pixel scale multiplier to 2x or higher doesn't do anything if your monitor is 1080p or smaller, for example.

**Comment by Wedge009** [comment]
UHD, as above.

It definitely made a difference in the size of the Help window.

**Comment by Pentarctagon** [comment]
I don't have any explanation for that. We're both using Linux too.

**Comment by Pentarctagon** [comment]
For reference, in case anyone wants to try it out themselves, just change line
https://github.com/wesnoth/wesnoth/blob/73824b95cc838d988065e08dcea8081f8db8925d/src/help/help_text_area.cpp#L390
to instead be
`texture tex(image::get_texture(path, image::scale_quality::linear));`

**Comment by Wedge009** [comment]
Okay, I can see a difference with the change you suggested. The image I posted above is without linear interpolation, yet it doesn't look anywhere near as bad as the original image doofus posted. If I had to guess, it's as though the artefacts there are a result of the image being scaled up with nearest neighbour, and then scaled back down again.

**Comment by doofus-01** [comment]
Pixel scale multiplier (PSM) wasn't on my radar as something to care about, I don't remember touching it, it was at Auto.  That explains the UI elements resizing when I resize the window.  Unfortunately, the help browser doesn't resize on the fly, so testing involves closing-opening-navigating.

But it does seem to be key to this, I don't see the issue with PSM set to 1 (Auto unchecked).  Same window, just changing PSM.
![Screenshot_20240210_PSM](https://github.com/wesnoth/wesnoth/assets/13510196/c521430d-f7ff-4e00-8587-6076a5165bf9)

Down scaling plays a role, the issue is worse when the window is something like 2125x1250 (PSM > 1) than when it is 3580x1970 (PSM > 1).  

Two possibilities to deal with it:
1. Is there some way to exclude certain elements from scaling?  This might not work well in [message] image display, but looks like it could work for help browser.
2. Should the thresholds for PSM auto-adjust be changed, so the window has to be bigger before it increases?

**Comment by Wedge009** [comment]
That's the key: _automatic_ multiplier. When I switched to automatic multiplier, I could replicate (with some fiddling with the window size) the grainy downscaling seen in the image from the original report.

I think this is one of those areas where fractional scaling would really help.

**Comment by Pentarctagon** [comment]
My understanding is that the scaling (via `SDL_RenderSetLogicalSize`) is applied globally. The thresholds can certainly be changed though.

**Comment by doofus-01** [comment]
In discord, there was a short discussion of what scaling options are better.  I don't think the issue is "2X scaling uses nearest neighbor scaling to scale 2X, and we need a better algorithm for portraits" - and sorry if I'm misunderstanding what @Pentarctagon is saying.

The image below shows scaling with a window size just before re-scale (1), just after rescale (2), and dragged even larger (3).  "Re-scale" here meaning the jump in UI elements, not sure if that's really the same threshold.  (1) and (2) are almost the same size, but (2) is clearly hurt by nearest neighbor.  (3) must also be hurt, but it's a bigger image and doesn't look as bad as (2).

So, whatever is going on, it's not just the limited choice of scaling methods.
![Screenshot_20240224_tripple](https://github.com/wesnoth/wesnoth/assets/13510196/fd463c8b-f4d3-4cae-9aab-d16a1e3af9df)

**Comment by Pentarctagon** [comment]
Unfortunately my monitor is only 1440p, so I can reproduce (1) and (2) but not (3). It looks like there is actually double scaling going on though, from https://github.com/wesnoth/wesnoth/blob/651e2866baaa36404249a0db15973da6c1789ac1/src/help/help_topic_generators.cpp#L328-L335

If I delete the SCALE_INTO IPF from those lines, then at 2x scale they're shown as:
![Screenshot from 2024-02-24 15-18-27](https://github.com/wesnoth/wesnoth/assets/3030250/69c1a7ee-672f-4797-9261-e0ba9b983c75)
![Screenshot from 2024-02-24 15-18-49](https://github.com/wesnoth/wesnoth/assets/3030250/1a15f12c-c653-40b7-add4-5094480a51df)

So perhaps `sz` there needs to be adjusted based on the pixel multiplier?

**Comment by doofus-01** [comment]
I'm not sure, maybe.  I do know that just trying to recreate the bad scaling with GIMP, I can do it by shrinking a 400px portrait to 200px, then rescaling it back up to 400.  Scaling 400 to a random size, or to 800 then a random size, doesn't get messed up much, as expected.  So probably figuring out the final dimensions before actually scaling anything would fix it.  (And maybe that's essentially what you are saying?)

**Comment by CelticMinstrel** [comment]
Hardware acceleration of the IPF chain would presumably be able to fix this, as (I think) it would be able to combine scaling multipliers to come up with a single final scale that's then applied to the image. (Technically speaking that's not how rendering works at all, but I think the effect ends up the same.)

I _thought_ the current rendering pipeline already did that as long as the scaling IPF was at the end of the chain, though. Is there _any_ possibility that it was implemented for some IPFs but not others? Does changing to `~SCALE()` or `~SCALE_INTO_SHARP()` make any difference?

Do we know the commit where this issue started, by the way?

**Comment by Pentarctagon** [comment]
SCALE and SCALE_INTO_SHARP don't improve the appearance. I don't know what I'd be looking for if some IPFs are implemented differently than others for this. I don't know which commit this started with, but presumably the one adding the scaling in the first place.
