### ISSUE TITLE
QUAKE macro doesn't shake the screen anymore

### ISSUE THREAD

**Issue by AnekronCZ** [wesnoth/wesnoth#8276]
### Game and System Information

- **Version:** 1.17.24
- **Downloaded from:** AUR
- **Build info:** 80da6fd
- **OS:** Manjaro Linux
- Tested on two separate computers with different resolution displays

### Description of the bug

QUAKE macro still plays the assigned sound, but it's scrolling feature simulating shaking doesn't seem to be working anymore, at least on Linux using X.org. 

### Steps to reproduce the behavior

1. Launch the final scenario of The Sceptre of Fire, Caverns of Flame
2. Kill Toomak, the troll hero leader to trigger the QUAKE macro
3. The screen doesn't shake

### Expected behavior

1. Launch the final scenario of The Sceptre of Fire, Caverns of Flame
2. Kill Toomak, the troll hero leader to trigger the QUAKE macro
3. The screen shakes

**Comment by Wedge009** [comment]
The regression starts at 06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4.

I recall there was some work in migrating events like thunder flashes and fade to/from black transitions to the new draw manager, but I can't recall if there was anything for the 'screen shake' animation.

**Comment by Wedge009** [comment]
The issue is with any `QUAKE` macro. There is a combination white flash and quake animation triggered on turn 4 of the MP scenario Aethermaw.

Just citing as a complementary example, this one including a white flash.

**Comment by Wedge009** [comment]
`QUAKE` macro is defined in `interface-utils.cfg`:
https://github.com/wesnoth/wesnoth/blob/56cc959d936eee7b5f0bd39af58cae9329fd8d35/data/core/macros/interface-utils.cfg#L146-L171

Is it the case that with the new draw manager the `[scroll]` blocks are not being drawn for some reason? I think `SCROLL` macros, which depend on `[scroll]` are still working correctly.

**Comment by Wedge009** [comment]
As an example, the introduction of SotA S20 North Knalga has a custom `SHAKE` macro using `[scroll]`s which plays when a dwarf raises a heavy gate. It is similar to the `QUAKE` macro but has smaller co-ordinate offsets and introduces a delay in between the `[scroll]`s.

I tried doing something similar in the `QUAKE` macro but it doesn't appear to make any difference. Maybe I'm missing something.

**Comment by Wedge009** [comment]
Oh silly me, I realised why I didn't get it working, yesterday or just now. I was editing the `QUAKE` macro directly, but reloading the same save file which didn't have the macro changes. As I suspected yesterday, the new draw manager was indeed doing the `[scroll]` but it now animates too quickly to be noticed. Introducing the `[delay]` seems to help.

I'll make a PR shortly.

**Comment by Wedge009** [comment]
As a counter-example, DM S10 introduction works as master currently stands because it uses a custom `MEMOIRS_TREMOR` macro that already has a delay built in.

**Comment by Wedge009** [comment]
`UTBS_SHAKE_SCREEN` is a similar macro to `QUAKE` that also doesn't show in current master.

**Comment by Wedge009** [comment]
There are a series of `[scroll]`s in UtBS S12, but they don't appear to show even in 1.16.11, so I'm leaving them alone.
