### ISSUE TITLE
Recalling CERTAIN units crash the game (dev version)

### ISSUE THREAD

**Issue by TheFlamelet** [wesnoth/wesnoth#8279]
### Game and System Information

- **Version:** 1.1724
- **Downloaded from:** Real Version itch.io
- **Build info:** NA
- **OS:** Win10x64

### Description of the bug

I noticed this mostly on Rise of Wesnoth Campaign.

Had AMLA+ mod enabled among others. Provided logs, and I have some saves if needed. Not sure why loading game sometimes fixes the problem, so the crash is not guaranteed. I have some more logs if needed.

### Steps to reproduce the behavior

crash was caused not only by units that trigger Amla+ event. iirc even units which did not trigger the event could cause the crash. If I am wrong then maybe I have selected loyal when AMLA+ triggered, thats why I thought the unit wasnt improved.

### Additional context

enabled mods included AMLA+, AWW among others.

[wesnoth-20240109-154638-2578151741.log](https://github.com/wesnoth/wesnoth/files/14013702/wesnoth-20240109-154638-2578151741.log)
[wesnoth-20240109-143002-3781818761.log](https://github.com/wesnoth/wesnoth/files/14013704/wesnoth-20240109-143002-3781818761.log)
[wesnoth-20240109-142632-3405682472.log](https://github.com/wesnoth/wesnoth/files/14013705/wesnoth-20240109-142632-3405682472.log)
[wesnoth-20240109-122138-3383926257.log](https://github.com/wesnoth/wesnoth/files/14013706/wesnoth-20240109-122138-3383926257.log)

**Comment by knyghtmare** [comment]
Your Log files only give deprecation warnings, no assertion message. (I checked the last 2 recent ones)

If it's a bug with `AMLA+` add-on, you should report it to its author.

**Comment by gfgtdf** [comment]
The reason why it shows no assertion messages  is probably https://github.com/wesnoth/wesnoth/issues/8108

**Comment by gfgtdf** [comment]
So first, how exactly does it crash the game? Do you get some kind of error message? If : yes what does it say can you maybe give a screenshot?

If not it's maybe better to wait until https://github.com/wesnoth/wesnoth/issues/8108 is fixed, and then try to debug this issue.

In any case a more minimlisic case would be nice, if you can figure  out whether  it only happens in a  certain scenario or with certain mods.

I took a short look at the AMLA+ addon and it seems rather harmless, just a few checks then an [object] call. So i guess it something else, not sure though.

**Comment by Wedge009** [comment]
Doesn't look like this is confirmed. I note #8108 is resolved now, plus 1.18.0 has since been released.
