### ISSUE TITLE
Sand (Sand) tiles are bugged in UtBS 2 (Across the Harsh Sands)

### ISSUE THREAD

**Issue by PointMeAtTheDawn** [wesnoth/wesnoth#8284]
### Game and System Information

- **Version:** 1.16.11
- **Downloaded from:** Steam
- **OS:** Windows

### Description of the bug

Desert(Sand) tiles work correctly for dehydration purposes. Sand(Sand), such as the tile at 20,52, does not. Units are healed/cured and do not suffer thirst, as they would on a grass tile.

**Comment by Wedge009** [comment]
I remember a number of issues reported (and fixed?) for this scenario in the 1.17 series, though I can't find them right now. It's possible this issue may already be resolved for the 1.18 release candidates.

**Comment by PointMeAtTheDawn** [comment]
Looks like this was fixed in 1.17.23!
