### ISSUE TITLE
what does this phrase mean?

### ISSUE THREAD

**Issue by TheFlamelet** [wesnoth/wesnoth#8288]
### Language

English

### Source

Legend of Wesmere, 24_Epilogue.cfg

### Original Text

he left his home and wandered for **many a year** across the Great Continent.

### Proposed Change

he left his home and wandered **for a year** across the Great Continent.
he left his home and wandered **many times a year** across the Great Continent.
he left his home and wandered **much** across the Great Continent.

**Comment by TheFlamelet** [comment]
is the word [times] implied?

**Comment by Zireael07** [comment]
This is an archaic way to say "many years"

**Comment by TheFlamelet** [comment]
> This is an archaic way to say "many years"

maybe it should be added to the not broken list then https://wiki.wesnoth.org/NotSpellingMistakes

**Comment by stevecotton** [comment]
I'm not sure about adding a po hint or wiki hint in this case; I'm not against doing so, just not sufficiently in favor to do it myself. The next line to translate says that he's still during Asheviere's reign, indicating that he lives at least 500 years.

**Comment by TheFlamelet** [comment]
I guess next time I will have to check the web in addition to the don't fix it list.
https://www.britannica.com/dictionary/eb/qa/the-difference-between-many-and-many-a#:~:text=Like%20the%20adjective%20and%20pronoun,%5B%3Dfor%20many%20years%5D
