### ISSUE TITLE
The add_source_file script conflicts about how .hpp files should be added

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8291]
Version 1.17.25+dev (56cc959d936eee7b5f0bd39af58cae9329fd8d35)

When adding files via add_source_file, the .hpp must and must not be given on the command line.

* For Xcode, the `.hpp` file needs to be given to the script on the command line.
* For CodeBlocks, if a `.cpp` is added then the corresponding `.hpp` is automatically also added.
    * If the user tries to add the `.hpp` manually afterwards, the script will print an error (but will continue).

For CMake and SCons, filenames not ending `.cpp` will be silently ignored, but this doesn't resolve what the correct usage is.

Note: it's not the issue that I'm raising here, but the script currently has some obnoxious behavior:
* `add_source_file --help` treats the argument as a filename.
* `add_source_file src/foo.cpp src/foo.hpp` treats foo.hpp as a target name, so to add two files you have to run it twice.

Steps to reproduce
===

1. Create src/foo.hpp (if you test with a completely fake filename, the CodeBlocks code won't automatically add it)
2. `add_source_file src/foo.cpp` (at this stage Xcode doesn't have all the files it needs)
3. `add_source_file src/foo.hpp` (gets an error from the CodeBlocks handling)

**Comment by Pentarctagon** [comment]
> For CMake and SCons, filenames not ending .cpp will be silently ignored, but this doesn't resolve what the correct usage is.

Honestly I'd be fine with it just not handling cmake and scons. Adding files to the source lists is trivial, and the only reason this script exists at all is for other build systems that use a project file that's not easy to hand edit.

**Comment by CelticMinstrel** [comment]
Especially Xcode. I have no idea where that hash comes from.

**Comment by stevecotton** [comment]
CMake and SCons is the easy bit, the only problem with them is that they don't give a hint which of Xcode or CodeBlocks is the correct behavior.

Based on the conversation so for, I'll merge #8292 because I've got a WIP on top of it that will fix this bug.
