### ISSUE TITLE
Corrupted 1.17.25 Windows release on sourceforge

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#8296]
### Game and System Information

- **Version:** 1.17.25
- **Downloaded from:** sourceforge.net
- **Build info:** N/A
- **OS:** Windows

### Description of the bug

The download from sourceforge.net for Windows 1.17.25 release appears to be incomplete. 1.17.24 release was 411 MiB, 1.17.25 release as downloaded from sourceforge.net is only 228 MiB.

![image](https://github.com/wesnoth/wesnoth/assets/13679322/095cf3c4-e55b-42c6-9913-bb888d0fc295)

### Steps to reproduce the behavior

1. Download Windows 1.17.25 release from sourceforge.net (my download was at 2024-01-26 ~03:00 UTC).
2. Attempt to run the installer.

**Comment by loonycyborg** [comment]
I've repeated the step that uploads windows installers. Size seems to check out now.

**Comment by Wedge009** [comment]
Looks okay now, thanks for the quick resolution.
