### ISSUE TITLE
Status icons are rendered deformed (poisoned, slowed, petrified)

### ISSUE THREAD

**Issue by AnekronCZ** [wesnoth/wesnoth#8303]
### Game and System Information

- **Version:** 1.17.24
- **Downloaded from:**AUR
- **Build info:** 80da6fd
- **OS:** Manjaro Linux under X11
- Also appears on Windows 10

### Description of the bug

![bug](https://github.com/wesnoth/wesnoth/assets/149104469/3e96691c-fd73-4846-ad72-fca0d2b33303)
As the upscaled image shows, status icons are shown squashed in-game. That goes both for mainline ones _and_ for UMC created art.

I've added the proper visual of the icon under the rendered one with added border for clarity.

### Steps to reproduce the behavior

1. Start any scenario
2. Apply any status to any unit
3. The icon(s) is/are deformed

### Expected behavior

3. The icons is shown in its proper aspect ratio

**Comment by Wedge009** [comment]
Like #7472, this started with e379aeefe4b91f9bc4b0d254ecc20e13766caa25 (1.17.5). I suspect any image that gets displayed in the side-bar, if it has padding, will need to have padding removed because the new display code includes the padding whereas the old one did not.

https://github.com/wesnoth/wesnoth/blob/master/images/misc/poisoned.png
https://github.com/wesnoth/wesnoth/blob/master/images/misc/petrified.png
https://github.com/wesnoth/wesnoth/blob/master/images/misc/slowed.png

**Comment by Wedge009** [comment]
Invisibility (Elvish Avenger in forest, undead in deep water, etc) is also affected.

https://github.com/wesnoth/wesnoth/blob/master/images/misc/invisible.png

I haven't confirmed these, but they may be affected too:

https://github.com/wesnoth/wesnoth/blob/master/images/misc/invulnerable.png
https://github.com/wesnoth/wesnoth/blob/master/images/misc/unhealable.png

**Comment by mesilliac** [comment]
There was previously some code that removed all bordering transparency from any image displayed in a "report" context. I disabled it in that commit because it wasn't clear what (if anything) was relying on it or why. If these images rely on not having transparent edging for correct display, shouldn't they just not have transparent edging in them to begin with?

**Comment by CelticMinstrel** [comment]
So basically the two options to fix it are:

1. Put that function back.
2. Remove the transparency.

Does removing the transparency cause problems? Certainly it's a compatibility issue - any number of images that we don't even know about could be affected. Are the mainline status icons used in any other locations? If not, I think perhaps the best approach is to put the function back, but add a deprecation warning whenever it decides to correct for transparency. Then we remove the function entirely in a later release.

**Comment by mesilliac** [comment]
The problem with replacing the function is that it can't be reproduced as part of the hardware rendering - it was done as a software operation at draw time as part of the draw operation.

If it's desirable to restore that behaviour, it would probably be best to reimplement it as an IPF function and apply it when loading those images.

**Comment by CelticMinstrel** [comment]
That's if we want to keep the behaviour indefinitely, rather than only temporarily to give addon authors a chance to update their images.

I guess I wouldn't mind having an IPF that clips off transparency though. It could be called something like `~CROP_TO_FIT()`.

So that makes a 3rd option for fixing this. Add that IPF and hard-code its use in the one place that used to call that function.

**Comment by Pentarctagon** [comment]
Unless someone is volunteering to implement that IPF, given there are only a small number of status images, I'd say just cropping the image files makes the most sense.

**Comment by Wedge009** [comment]
> There was previously some code that removed all bordering transparency from any image displayed in a "report" context. I disabled it in that commit because it wasn't clear what (if anything) was relying on it or why.

I think the 'report' context is anything that's shown in the side-bar, which explains the symptoms observed.

**Comment by CelticMinstrel** [comment]
> Unless someone is volunteering to implement that IPF, given there are only a small number of status images, I'd say just cropping the image files makes the most sense.

1. The implementation of the IPF is probably fairly similar to the commented-out function.
2. I think that, if we just crop the mainline image files, we should still have a deprecation cycle like mentioned earlier.

> I think the 'report' context is anything that's shown in the side-bar, which explains the symptoms observed.

The icons along the top bar as well. Not sure if those are affected though, maybe they don't _have_ any transparency.

**Comment by mesilliac** [comment]
It's not actually possible to reinstate the function as it was - the only place this type of read + write operation can be done now is when loading the image. But it should be almost a straight copy/paste to an IPF.

It was `display::draw_image_for_report()`, which appears to be gone now, i probably removed it in a later tidy up as i never found the noticable effect of removing it. It used a `get_non_transparent_portion()` helper fuction which did most of the work.

**Comment by CelticMinstrel** [comment]
I guess that rules out option 1 for fixing it. Probably the best answer then is, indeed, to implement a new IPF. Then the places that used to call that function can automatically append it to the image path.

**Comment by Pentarctagon** [comment]
If an IPF is made to address it, then there isn't really a point to having any sort of deprecation involved. Append the IPF, put a code comment in explaining why it's there, and then just leave it there.

**Comment by CelticMinstrel** [comment]
That's true, no need to deprecate it in that case. We could still deprecate it if we want to, though.

**Comment by doofus-01** [comment]
> I think that, if we just crop the mainline image files, we should still have a deprecation cycle like mentioned earlier.

Why is a deprecation cycle needed to crop empty padding from images?

**Comment by CelticMinstrel** [comment]
If we're going to change the behaviour of the game from cropping padding to not cropping padding, then there needs to be _some_ indication to an addon dev that they need to update their images.
