### ISSUE TITLE
SoF S6 - opening dialog

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#8311]
### Language

English (USA)

### Source

SoF S6

### Original Text

       [message]
            speaker=Rugnur
            message= _"The country between here and Knalga will be swarming with elves. We had better head back to the abandoned mines north of the Arkan-thoria, where we gathered our gold and coal. At least there Alanin will have some hope of finding us."
        [/message]

### Proposed Change

       [message]
            speaker=Rugnur
            message= _"The country between here and Knalga will be swarming with elves. We had better head back to the abandoned mines north of the Arkan-thoria, where we gathered our gold and coal."
        [/message]

**Comment by doofus-01** [comment]
Basically, the comment about Alanin in the opening dialog seems a little bizarre, not sure what happened.  I know we're not supposed to be changing strings now, but simply moving the string lower also sounds odd.  So some review is warranted when it's possible to change strings again.

**Comment by stevecotton** [comment]
The issue being that Alanin is still with them, and has dialogue lines in this conversation. It's also a very old bug - this mistake has been in the dialogue for 15 years, since 21c95e1353c70d52eaf8f6a4158a8065e9a8b547, and is already translated in 29 languages.

**Comment by Wedge009** [comment]
Should be appropriate to revisit this now, since 1.18.0 is released,
