### ISSUE TITLE
Visual Bug: some cured units look poisoned until mouse hover over them

### ISSUE THREAD

**Issue by TheFlamelet** [wesnoth/wesnoth#8312]
### Game and System Information

- **Version:** 1724
- **Downloaded from:** Real Version: itch.io
- **Build info:** NA
- **OS:** Win 10

### Description of the bug

unit is cured but looks green. hover over the cured unit and it will look normal again.

### Steps to reproduce the behavior

1. have multiple curers next to each other
2. have multiple poisoned units around 
3. one of the poisoned units will still look green
4. it is probably the last cured unit
5. hover over the unit, or alt+tab and come back to wesnoth,
6. the unit will look normal again.

### Expected behavior

all cured units look normal

### Additional context

![image](https://github.com/wesnoth/wesnoth/assets/155806857/fc169726-781f-46fb-a99f-272a824c3e08)
![image](https://github.com/wesnoth/wesnoth/assets/155806857/84d43636-813b-42ee-a3ff-f37a4c4e9356)

**Comment by Wedge009** [comment]
I'm not able to replicate this in 1.17.24 release for Windows, just going by the description. I had two poisoned units both adjacent to two white mages. Do you happen to have a saved game demonstrating this?

The Lua(?) error message is also a concern - is this from an official campaign?

**Comment by soliton-** [comment]
This is from Delfador's Memoirs. The poisoned unit is probably Delfador.

**Comment by Wedge009** [comment]
Was anyone able to replicate this?

**Comment by Wedge009** [comment]
Noting that Needs Info and Unconfirmed issues are likely to be closed when there is no further information.
