### ISSUE TITLE
[Units] `movement_type=lightfly` in Raven unit tree does not recognize assigned `[defense]` tag.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#8318]
### Game and System Information

- **Version:** 1.17.25+dev
- **Downloaded from:** GitHub
- **Build info:** Msys2
- **OS:** Windows 10

### Description of the bug

In each of the Raven units there is this: 
```ini
    [defense]
        village=60
        forest=70
    [/defense]
```

Which means these units will be getting 40% dodge in village and 30% in forest.
However, in the game, the dodge for village and forest is 60%. This implies that there is something wrong here.

### Steps to reproduce the behavior

1. Start any campaign (HttT is good as both forest and village in S1)
2. DEBUG MODE
3. Spawn Raven/Dark Omen/War Harbinger unit (any)
4. Observe dodge values for village and forest. Both show 60%.

![image](https://github.com/wesnoth/wesnoth/assets/5283677/58115c4a-1923-4e18-ae77-eb4a2b53ac09)

![image](https://github.com/wesnoth/wesnoth/assets/5283677/43e5eef3-7f90-4708-9776-840c16188df7)

### Expected behavior

Raven units: dodge 30% in forest and 40% in villages as per their unit type code? (Please see Additional Context section)

### Additional context

**Here is the confusing part:** 
I am very skeptical of these adjusted dodge values being given to the Raven unit tree myself. 

- Falcon/Elder Falcon get 60% in forest and 50% in village (enforced by feral trait). 
- So, why should Raven units get 30% in forest and 40% in village? Seems absurd.

**Comment by ProditorMagnus** [comment]
It recognizes. You tested mixed terrain, so higher defense applies.

**Comment by knyghtmare** [comment]
> It recognizes. You tested mixed terrain, so higher defense applies.

Oh

**Comment by CelticMinstrel** [comment]
I think there's definitely a bug here though. It shouldn't be specifying a `forest=70` that has no effect (since forest is _always_ mixed terrain). We should remove it or change it to something that _does_ have an effect.

**Comment by soliton-** [comment]
Not that forest or village must be an overlay but for mainline the stats do indeed look weird.
