### ISSUE TITLE
Nym, Kaleh, and Zhul have odd interactions with poison and deydration in UtBS

### ISSUE THREAD

**Issue by PointMeAtTheDawn** [wesnoth/wesnoth#8324]
### Game and System Information

- **Version:** 1.17 (I believe 1.16 as well, but my recent testing has been on 1.17).
- **Downloaded from:** Steam
- **OS:** Windows

### Description of the bug

Context:
- During the day on sand/desert hexes in mission 2, units should be unable to be healed or cured/delayed of poison. If they are not adjacent to a healer, they additionally suffer dehydration penalties.

Kaleh and Nym simply have broken interactions with poison. In any scenario, inconsistently (i.e,. consistently once it is happening, but I do not know the conditions required to start this process) they will automagically shed themselves of poison, slow, and presumably other negative conditions. I've seen this happen on turn start and turn end (or enemy turn start, perhaps). I've had it happen to one and not the other, then both.

Separately, Zhul's interactions with dehydration specifically are broken. Mystics follow the above context, but Zhul's healing aura ignores dehydration and heals/cures surrounding units, whether hero or not.

**Comment by stevecotton** [comment]
Fixed in #8147.
