### ISSUE TITLE
During enemy turns on Android, the main game map interface shakes or jitters when enemy characters move.

### ISSUE THREAD

**Issue by xingwozhonghua126** [wesnoth/wesnoth#8328]
### Game and System Information

- **Version:**TBD
- **Downloaded from:**TBD 
- **Build info:**Custom build or official build
- **OS:**Android 

### Description of the bug

During enemy turns on Android, the main game map interface shakes or jitters when enemy characters move.

### Steps to reproduce the behavior

1.Start a game on the Android version of the app.
2.Proceed to the enemy’s turn.
3.Observe the main game map interface as the enemy characters move.

### Expected behavior

I expected the game map to remain stable and not shake or jitter when enemy characters move. This issue can be quite jarring and negatively affects the gameplay experience.

**Comment by soliton-** [comment]
What does "Custom build or official build" mean? Did you build it yourself? What version? There is no official android build. There is a thirdparty app that is on 1.14 while current is 1.16 (and soon 1.18).

Anyway, in Preferences under Advanced you can disable the "Follow unit actions" option. That may be what you'e talking about.

**Comment by xingwozhonghua126** [comment]
1.14.17, i wiil try disable the "Follow unit actions", my english is poor ,ai tell me how to write issue.

**Comment by Pentarctagon** [comment]
Closing and the Android version is no longer available.
