### ISSUE TITLE
GCC-13's -Wdangling-reference

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8334]
GCC-13 brings a new `-Wdangling-reference`, which due to false positives had to be moved from `-Wall` to `-Wextra`. [link to GCC commit](https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=6b927b1297e66e26e62e722bf15c921dcbbd25b9)

For the CI, we want to build with `-Werror -Wextra`, and we'll eventually want to build with GCC-13 (it'll be the default in Debian Trixie).

- [ ] Assess all reports to see if they are false or correct.
- [ ] Add `-Wno-dangling-reference` for GCC-13 but not for GCC-14.

**Comment by CelticMinstrel** [comment]
> For the CI, we want to build with `-Werror -Wextra`,

Honestly, this sounds like it could be an _extremely_ bad idea. Feel free to give it a try, but if it produces a billion Meyers warnings, then let's not.

**Comment by stevecotton** [comment]
> Honestly, this sounds like it could be an _extremely_ bad idea.

I'm not suggesting changes, I should have said that AFAIK some of the CI build are already doing that.
