### ISSUE TITLE
[NR][HttT][other?] capitalization of artifact names (Sceptre of Fire, Rod of Justice etc.)

### ISSUE THREAD

**Issue by FyiurAmron** [wesnoth/wesnoth#8338]
### Game and System Information

- **Version:** 1.17.24 & bleeding edge
- **Downloaded from:** official (SourceForce)
- **Build info:** N/A
- **OS:** any

### Description of the bug

_Rod of Justice_ is commonly spelled just like that. Same with Sceptre of Fire etc. However, description per https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg#L1411 provides "rod of justice", and it shows just like that in the unit's attacks:

![image](https://github.com/wesnoth/wesnoth/assets/11016998/5e55cde7-ae15-4eb7-8b68-bff18dcd5435)

Same with SoF. I do recall that there probably was some reason for this in the days of yore (`description` didn't exist in ancient WML AFAIR, so maybe autogeneration of description from name? it does look like that in the historic commits, e.g. https://github.com/wesnoth/wesnoth/commit/0f41271a752f0e6fcc7cceaacd4d4568608c4a8b ), but frankly, it sticks like a sore thumb nowadays.

It's not in https://wiki.wesnoth.org/NotSpellingMistakes , I couldn't find any actual reason explaining the current state of things in the WML docs either.

### Steps to reproduce the behavior

1. have any unit with an artifact spelled capitalized in the story text equipped,
2. look at the unit and wonder at the capitalization of the name shown.

### Expected behavior

Artifact names should follow _Official Pattern of Artifact Naming_ from this day on everywhere.

### Additional context

This is not an issue of e.g. "flaming sword", which is referred to as either "Flaming Sword of XYZ" or just "flaming sword", and other minor stuff the player can get. It only covers the *Big Artifacts of Obvious Renown*, which look just strange when called just _big artifacts of obvious renown_ for no reason.

**Comment by Wedge009** [comment]
I could be wrong, but I think the convention for unit weapons is supposed to be lower-case. It's not as though the item in question is being stated as a generic 'rod of justice' in prose - at least in the way I read it.

**Comment by FyiurAmron** [comment]
@Wedge009 

> I could be wrong, but I think the convention for unit weapons is supposed to be lower-case.

My point is, what would be the sense/rationale of such convention, and, if it exists, how/where is it documented and why should we keep it at all?

Even if it would exist, then maintaining a sparingly-used but completely astonishing 20-years-old convention would IMVHO require an extraordinary rationale.

Like I said - I digged through the commits, and couldn't find none other than we had a convention to use lowercase for _names_ (i.e. IDs), and that descriptions were based on copy-pasting names initially. I do recall standardizing the _names/IDs_ to lowercase, though, but it doesn't apply here, for obvious reasons.

>It's not as though the item in question is being stated as a generic 'rod of justice' in prose - at least in the way I read it.

It's not. It's capitalized basically everywhere else. Same with Sceptre of Fire.

**Comment by Wedge009** [comment]
That's my point. It's capitalised in prose, but not in the side-bar entry. It reads fine to me, but if a decision is made to change that, then that's okay too.

**Comment by demario-w** [comment]
> > I could be wrong, but I think the convention for unit weapons is supposed to be lower-case.
> 
> My point is, what would be the sense/rationale of such a convention, and - if it indeed exists - how/where is it documented and why should we keep it at all?
> 
There is no need for a rationale. It is coming from the history of BfW and "fixing" it would breaks tens of translation.
The convention you are looking for is certainly: "don't fix what is not broken".

**Comment by knyghtmare** [comment]
> That's my point. They are capitalised in prose, as they should be, but not in the side-bar entry. It reads fine to me, but if a decision is made to change that, then that's okay too.

> There is no need for a rationale. It is coming from the history of BfW and "fixing it" would break tens of translation.
The convention you are looking for is certainly: "don't fix what is not broken".

I vote for keeping it the way it is. Prose: Capitalised, side-bar: lower-case

**Comment by demario-w** [comment]
@FyiurAmron 

You might not like the feedback, but you have to understand this: _you sit in a very privileged position as a native English speaker_ for which any change in a sentence that crosses your mind leads to an improvement to your experience in the game. But every translatable string that changes will show up in English for all international players unless the corresponding translation team does the work to resolve the conflict. So this is a **very expensive** process.
Not even mentioning the languages where the translation is inactive and the string will show in English for the rest of BfW life.

I hope you will be able to see how the privilege you enjoy doesn't allow you to be overly sensitive about this. This realization will really drive how much positive contribution you can make to this game.
