### ISSUE TITLE
Cancel a move after a special event can cause the unit to pass through a wall

### ISSUE THREAD

**Issue by alberic89** [wesnoth/wesnoth#8343]
### Game and System Information

- **Version:** 1.16.9 and nightly build
- **Downloaded from:** Debian package, Flatpak
- **Build info:** no
- **OS:** Debian 12

### Description of the bug

A special event can change the terrain after a unit move. But, you can cancel the move after the terrain change. This can lead to some pretty incoherent situations.

For example, in the 2^th^ scenario of the campaign The Scepter of Fire, activate a glyph summon walls. If you cancel the move, the wall keeps in place.

### Steps to reproduce the behavior

1. Go to the 2^th^ scenario of the campaign The Scepter of Fire,
2. Place unit to remove the fog,
3. Place a unit at the outside of the cave, near to a glyph,
4. Move the unit to the glyph,
5. Cancel the move : the unit pass through the new wall.

### Expected behavior

Cancellation should not be allowed after a dialogue or special event.

### Additional context

A video of the glitch, and the save I had used.
[Capture vidéo du 2024-02-03 10-20-04.webm](https://github.com/wesnoth/wesnoth/assets/90179203/dbbd247c-8c55-4aeb-86fb-fbb8c57e5716)
[SdF-Fermeture des portes Tour 1.zip](https://github.com/wesnoth/wesnoth/files/14150882/SdF-Fermeture.des.portes.Tour.1.zip)

**Comment by knyghtmare** [comment]
Confirmed. Also pressing Undo left the "glyph" ON so broke the scenario code by violating the mechanics "each glyph must have a unit on it to close the gate". So, labelled as blocker.

**Comment by gfgtdf** [comment]
> For example, in the 2^th^ scenario of the campaign The Scepter of Fire, activate a glyph summon walls. If you cancel the move, the wall keeps in place.

You say "for Example" but this seems to be concrete bug in that scenarios wml code. Are there other places where you noticed similar bugs?

**Comment by stevecotton** [comment]
@alberic89, please would you confirm that you've only seen this on SoF S02?

This specific event's code in SoF S02 has an `[allow_undo]`, which is causing the bug. If that wasn't there (and generally events don't include it), then the move wouldn't be undoable.

**Comment by alberic89** [comment]
Yes, I confirm it is the only place I found this bug.
