### ISSUE TITLE
[mainline] Weird faction turn sequence

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8356]
### Game and System Information

- **Version: 1.16.11**
- **Downloaded from: Steam**
- **Build info: not custom**
- **OS: Windows 10 I think?**

### Description of the bug

I have been playing LoW on easy mode in 1.16.11.

In LoW (S14, Human Alliance), the green (enemy) faction gets their turn before the purple (friendly) faction does. This splits up the friendly factions and ends the turn with purple, whereas it traditionally ends with the enemy factions. In theory, this changes little about the gameplay, but I found it somewhat disorienting.

PS: I love the game, thanks so much to the wonderful devs to make this possible! <3

### Steps to reproduce the behavior

1. simply start the scenario

### Expected behavior

I included the savefile, but I don't think it's really useful given that the issue is quite simple.

[Bugsave4.gz](https://github.com/wesnoth/wesnoth/files/14183847/Bugsave4.gz)

**Comment by Wedge009** [comment]
I think the turn order follows the arrangement of the sides, which may have been by design:

![image](https://github.com/wesnoth/wesnoth/assets/13679322/8db77ee0-de14-4ff7-b84d-603d165bf4fc)

**Comment by OrangePumpking** [comment]
I'm sure it is indeed due to the arrangement of the sides. If it is by design, I would recommend moving the purple faction up above the green faction in the sequence. I don't immediately see a reason to have the friendly purple faction go last and I felt it was somewhat confusing during gameplay.

**Comment by knyghtmare** [comment]
Actually this is intentional. Remember, LoW is not purely SP for now, but MP/SP.
In MP, allied team sequence for 2v2 is 14 and 23. Thus, it's like this. 
Think of the SP one like this your ally is playing his turn before you.

**Comment by OrangePumpking** [comment]
Ooooh ok that makes a heck of a lot more sense now. I didn't realize it was adpated for MP but in hindsight that makes a lot more sense. In that case I'd like to withdraw the issue :)

**Comment by Wedge009** [comment]
I take that to mean close. If not, can always re-open.
