### ISSUE TITLE
[mainline] Oddly easy 'survival' scenario LoW

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8357]
### Game and System Information

- **Version: 1.16.11**
- **Downloaded from: Steam**
- **Build info: not custom**
- **OS: Windows 10 I think?**

### Description of the bug

I have been playing LoW on easy mode in 1.16.11.

I played S14 (Human Alliance) on easy mode and it seemed unbalanced. The scenario is supposed to be a survival situation where you hold out for 18 turns. However, the orcish leaders recruit relatively little and not even all lvl2 units (the troll leader seemed to give the right amount of challenge). Given that the player controls 3 factions of their own, including a human faction which can recruit lvl 2 and even lvl3 and has an incredible amount of income, the orcs don't but up much of a fight. I managed to kill 2 enemy leaders and could've killed the troll with a bit more time (if not for the fact that he now gets the income that was meant for 3 leaders), while still sitting on 200+ gold for each of my factions that i didn't even bother spending. The favorable terrain of an easily defensible river is only relevant for the troll side because the orcs in the north barely put up a fight. I would recommend giving the orcs a LOT more starting gold, and/or giving the player significantly less gold.

PS: I love the game, thanks so much to the wonderful devs to make this possible! <3

### Steps to reproduce the behavior

I don't think any steps are required, it seems like an issue with the starting settings of the scenario.

### Expected behavior

The savefile shows turn 18, demonstrating the situation.

[Bugsave5.gz](https://github.com/wesnoth/wesnoth/files/14184101/Bugsave5.gz)

**Comment by Wedge009** [comment]
Not sure how this is an issue given you're playing on easy difficulty. I don't usually play high difficulty either, but would your assessment differ if you were to try replaying it on a higher difficulty, even experimentally (via debug-mode)? You can change the difficulty when loading the start-of-scenario file.

**Comment by OrangePumpking** [comment]
I've done some thinking on this and come to the conclusion that I was probably wrong.

Short answer: I think the scenario is fine, we can close this topic.

Long answer:
Easy mode was definitely far too easy for me (it had been a long time since I played Wesnoth so I went in too careful), which is fine, that's obv what easy mode is for, so I didn't have a hard time with previous scenarios. What stuck out to me is that this scenario felt far easier than other scenarios. However, I now realize that this may not be a balance issue at all. I think most scenarios (where you kill the enemy leaders) feel like the appropriate level of 'easy' even if you can kill them much faster than you usually would. However, when playing a difficulty mode far too easy for you (as I was doing), and faced with a scenario that is supposed to be impossible (survival scenario), you can suddenly kill the enemy leaders rather than just doing a better job of surviving. This feels problematic because there is a big difference in how the player experiences being able to kill the enemy faster or being able to kill an unkillable enemy. Hence, the scenario would actually feel perfectly balanced to anyone who was playing on an appropriate difficulty setting and only seems strikingly easy to someone who was not playing an appropriate difficulty setting like I was. At least I think this is the reason why the scenario stuck out to me the way that it did. In summary, I think the balancing of the scenario is probably fine and this bug report can be closed.
