### ISSUE TITLE
LoW: Clarify player's veterans joining Landar

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8359]
### Game and System Information

- **Version: 1.16.11**
- **Downloaded from: Steam**
- **Build info: not custom**
- **OS: Windows 10 I think?**

### Description of the bug

I have been playing LoW on easy mode in 1.16.11.

In LoW S22 (Northern Battle), the player can only recall shamans. The dialogue explains that your other units have already joined Uradredia (your ally) and will fight under his command. However, Landar ends up being the one that recalls your old units. Uradredia does not seem to have access to you old units, but does seem to recall units from a different list (he recuits/recalls some lvl1 units with experience and some lvl2 units without experience). Thematically it would actually make sense if Landar had convinced many of your old units to fight for him, but this does not match the dialogue.

PS: I love the game, thanks so much to the wonderful devs to make this possible! <3

### Steps to reproduce the behavior

I don't think any steps are required, it seems like an issue with the starting settings of the scenario

### Expected behavior

In the savefile you can see that Landar has recalled my old units.

[Bugsave7.gz](https://github.com/wesnoth/wesnoth/files/14184282/Bugsave7.gz)

**Comment by stevecotton** [comment]
It's meant to divide with 1/3 going to Uradredia and 2/3 going to Landar, and that does look similar to what's happened - there's around 25 units on Uradredia's recall list. However, Uradredia seems to have recalled two and recruited four completely new ones.

I think the previous scenario has most of the dialogue about veterans joining Landar.

**Comment by OrangePumpking** [comment]
Oh cool, in that case everything seems to go as intended. I had a look and the previous scenario does seem to have dialogue in that direction. Woops

**Comment by Wedge009** [comment]
So... can close as not-an-issue?

**Comment by gfgtdf** [comment]
note sure, mabye we could change the text like for example putting "those that didn't join landar joined Uradredia" somwhere instead of just saying that they joined Uradredia somwhere, but it depends on the exaxt text wheterh that'd make sense.

**Comment by OrangePumpking** [comment]
There is a message from the narrator at the start of this scenario:

    [event]
        name=start
        [message]
            speaker=narrator
            message= _ "Kalenz can only recall shamans and their advancements from his former army; the rest of his men joined Uradredia before he arrived."
            image=wesnoth-icon.png
        [/message]
    [/event]


Perhaps this informative message could just be adapted a little bit to avoid confusion?

**Comment by stevecotton** [comment]
Uradredia doesn't have any dialogue in the scenario. Maybe replace one of the narrator messages with him saying

`#po: exposition that two-thirds of the player's recall list are now on the enemy side`
"Many of these elves remember defending the Ka’lian alongside you, but it’s been a bitter split. For every elf who came back from Saurgrath wanting to stow their weapons and who now stands with us, two came back pledging their blade to Landar’s call."

**Comment by CelticMinstrel** [comment]
Fixed by #9128
