### ISSUE TITLE
LoW S22: Enemy camp starts too close to friendly camp

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8360]
### Game and System Information

- **Version: 1.16.11**
- **Downloaded from: Steam**
- **Build info: not custom**
- **OS: Windows 10 I think?**

### Description of the bug

I have been playing LoW on easy mode in 1.16.11.

In S22 (Northern Battle), the enemy purple faction starts off so close to the player, that one of the loyal elvish horsemen can run all the way into his camp and next to the enemy leader on turn 1, before they even have the chance to recruit. By sending other high lvl units, particularly the loyal units that spawn at the start without having to be recruited, the enemy leader can be killed before they even managed to spend all their money recruiting. I suggest either moving the enemy camp, or making the map bigger.

PS: I love the game, thanks so much to the wonderful devs to make this possible! <3

### Steps to reproduce the behavior

1. The player gets two loyal elvish scouts at some point in the campaign. By leveling them up to lvl3, they wil start at any scenario with tremendous movement range before recruitment has even begun.
2.  In S22, use these units, as well as other loyal units and a first round of recalled veterans to rush the enemy leader before they even finish recruiting.

### Expected behavior

[Bugsave7.gz](https://github.com/wesnoth/wesnoth/files/14184339/Bugsave7.gz)

**Comment by Wedge009** [comment]
I don't recall if there was a particular story reason for the placement of the enemy camp, but I'd say if you have an opportunity to attack the leader on the first turn then take it as an advantage.

**Comment by CelticMinstrel** [comment]
Fixed by #9128
