### ISSUE TITLE
[mainline] (SotA) AI doesn't understand protective circle

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8361]
### Game and System Information

- **Version: 1.16.11**
- **Downloaded from: Steam**
- **Build info: not custom**
- **OS: Windows 10 I think?**

### Description of the bug

I have been playing SotA on challenging mode in 1.16.11.

In S16 (The Mage), Crelanu is potected by a circle of holy water and 2 white mages. This is a really cool mechanic, but when a unit enters Crealnu's movement range, he will leave his keep to attack, thereby leaving behind his defences. The scenario ends when you kill Crelanu, so I didn't even interact with the holy water, sadly. I would recommend tweaking the ai so that the leader will not move from his keep and only attack enemy units standing right next to him.

PS: I love the game, thanks so much to the wonderful devs to make this possible! <3

### Steps to reproduce the behavior

1. send some dark sorcerers up front to lure out crelanu, unlike your undead units they will likely survive his attack.
2. Move in for the kill with melee units
3. By killing Crelanu, the scenario is won before you even interact with the holy water 😢

### Expected behavior

In the savefile, simply end the turn and Crelanu come out.

[Bugsave8.gz](https://github.com/wesnoth/wesnoth/files/14184575/Bugsave8.gz)

**Comment by Wedge009** [comment]
May just be a matter of fixing Crelanu to his keep.

**Comment by cooljeanius** [comment]
> May just be a matter of fixing Crelanu to his keep.

Many options for doing this:
- `passive_leader=yes`
- removing his movement points every turn (see examples in various other campaigns)
- goto MAI targeting the tile he's already on
- some others I'm probably forgetting

**Comment by Wedge009** [comment]
>     passive_leader=yes

Thank you, that's what I was thinking of. I also confirmed the issue, looking at my previous play-through in 1.16.

**Comment by cooljeanius** [comment]
@OrangePumpking could you take a look at #8521 please?
