### ISSUE TITLE
Make a tip genderneutral

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#8365]
### Source

Tips

### Original Text

https://github.com/wesnoth/wesnoth/blob/60ae0db6118bdcda29ccf7f091084dc3a8afaeb9/po/wesnoth/es_419.po#L3733

### Proposed Change

if you coddle **them** too much **they** may be

I'm not aware of any reason why it needs to be genderspecific, and it feels weird to read it while considering that there are female leader units (starting with the Battle Training).

**Comment by knyghtmare** [comment]
It was taken from HttT and it was implied that Delfador had Konrad in mind.

**Comment by Konrad22** [comment]
That would make sense. Can we change the date of the quote then? It's dated in 516YW, while HttT starts 517YW.
