### ISSUE TITLE
[EI] Paladin's standing animation is mixed in Terraent's one

### ISSUE THREAD

**Issue by tamanegi-jp** [wesnoth/wesnoth#8371]
### Game and System Information

- **Version: 1.17.25+dev**
- **Downloaded from: github**
- **Build info: built with SCons**
- **OS: debian testing**

### Description of the bug

![terraent-paladin](https://github.com/wesnoth/wesnoth/assets/29303968/d46ff717-a27b-4dc5-8cac-4763b806d7b1)
![terraent-terraent](https://github.com/wesnoth/wesnoth/assets/29303968/6a5293fa-b9b8-4689-97c0-5a1753f402ec)
(these images appear alternately.)

When "Unit standing animations" setting is enabled, Paladin images in core are mixed into Terraent's standing animation (see images above). Paladin is the base unit of Terraent (display name is also Paladin) and the normal Paladin's standing animation is longer than that of Terraent.

In my brief test, this can be fixed by making Terraent's standing animation longer. (I don't know how the standing animation is overridden, though.)

### Steps to reproduce the behavior

1. enable "Unit standing animation" setting
2. begin EI and enter scenario 04c Mal-Ravanal’s Capital
3. see Terraent (x,y=36,15 in the beginning)

### Expected behavior

core paladin images should not be mixed in

**Comment by Dalas121** [comment]
Ah, looks like the paladin didn't have a standing animation when I created Terraent, but when that got added in it also affected Terraent (since he inherits from Paladin as base unit).  Thanks for the report, should be fixed in #8381

**Comment by stevecotton** [comment]
Fixed in #8381.
