### ISSUE TITLE
Experience bug

### ISSUE THREAD

**Issue by hladkyjakub** [wesnoth/wesnoth#8374]
### Game and System Information

- **Version: 1.16.3**
- **Downloaded from: flatpack**
- **Build info: "Please respond with information, what should be there"**
- **OS:Linux, Kubuntu**

### Description of the bug

This effect (in [modify_unit]) gives unit, that has 0XP -> 1XP.
```
[effect]
      apply_to=experience
      increase=-40%
[/effect]
```

Didn't tested on other variables, may also occur.

### Steps to reproduce the behavior

1. apply:

```
[effect]
      apply_to=experience
      increase=-40%
[/effect]
```
to 0XP unit in [modify_unit]

2. That's probably all

### Expected behavior

0XP -> 0XP after 40% decrease

**Comment by hladkyjakub** [comment]
The lover part of the report is broken for some reason.

**Comment by hladkyjakub** [comment]
ALSO DOESNT WORK FOR +40% INCREASE!

**Comment by ProditorMagnus** [comment]
Probably similar bug which makes weapon special change 0 to 1.

**Comment by newfrenchy83** [comment]
The immense room resonates with sounds of pleasure; Kasumi and Ayane were plunged into ecstasy at the mercy of at least a dozen men.

I never doubted that something like this would happen if I was captured... but, to be honest, I imagined it would be much worse... and there's a good chance it would have been worse.
However, despite my regrets and sorrows, Ayane-chan's presence by my side every day and night makes the punishment for betrayal much more tolerable than if I were alone.

Are you sure you are not confusing experience and max_experience?

**Comment by newfrenchy83** [comment]
Are you sure you are not confusing experience and max_experience?

**Comment by hladkyjakub** [comment]
No, as sad generic unit with 0XP gets one when used modify_unit with [effect] up there.
I don't modify units max_experience, if that was the question.

**Comment by newfrenchy83** [comment]
> No, as sad generic unit with 0XP gets one when used modify_unit with [effect] up there. I don't modify units max_experience, if that was the question.

when i look the code i see what apply_mofofier finction has a minimum value who for increase experience is 1, valueto 0 to 1 or négative value dosn't valid probably dor what experience added was a iint value no null. i don't think what it is a bug.

what evalue of xp have you when you apply +40%?

**Comment by hladkyjakub** [comment]
Not sure what you ask, but decreasing works properly, when unit has more than 0 xp (1 or more).

**Comment by hladkyjakub** [comment]
evalue?

**Comment by newfrenchy83** [comment]
> evalue?

It is value not evalue

**Comment by newfrenchy83** [comment]
I just added a PR that might solve this problem

**Comment by stevecotton** [comment]
Looks like the bug was introduced all the way back in #618, which would mean this is in 1.14 and 1.16 too; I agree it's a bug, I'm just not sure about whether we rush the fix into 1.18 or whether we assume that UMC authors have already done their testing and we should postpone until 1.20.

Slightly in favor of fixing for 1.18.

**Comment by gfgtdf** [comment]
> Looks like the bug was introduced all the way back in https://github.com/wesnoth/wesnoth/pull/618, which

as i see it, the code also called `utils::apply_modifier` before that one.


I am not sure whether a unit with 0 max_experience is something that we actually actually support.

**Comment by gfgtdf** [comment]
Oh wait this commen was suppodef to be about that pr

**Comment by ProditorMagnus** [comment]
0 max_experience should be the intended way for units without amla.

**Comment by stevecotton** [comment]
max_experience has a lower limit of 1 enforced in various places in src/units/unit.cpp, and tested in data/test/scenarios/wml_tests/UnitsWML/zero_experience.cfg.

> as i see it, the code also called `utils::apply_modifier` before that one.

For current experience, that seems to have been introduced (with min 1) in f619b413e8f064584b60662153f932feec97c619, and the commit message suggests it was copied from hitpoints, where 0 hp is significantly different than 1 hp. I think the 1 minimum for current xp is a bug.

**Comment by newfrenchy83** [comment]
i see what utils::apply_modifier() with 1by default is used in attack_type.cpp(attack_type::apply_modification(), it is intended or some modification should be to zero?

**Comment by ProditorMagnus** [comment]
I think it should be 0, but this is not for 1.18.

**Comment by stevecotton** [comment]
By "this is not for 1.18", do you mean the current PR about experience, or the question about movement costs?

**Comment by ProditorMagnus** [comment]
It was about `attack_type::apply_modification()`. I dont have strong opinion about this pr target.
