### ISSUE TITLE
[EI 06a] enemy spawning event at the final turn not triggered

### ISSUE THREAD

**Issue by tamanegi-jp** [wesnoth/wesnoth#8376]
### Game and System Information

- **Version: 1.17.25+dev**
- **Downloaded from: github**
- **Build info: built with SCons**
- **OS: debian testing**

### Description of the bug

In the scenario 06a "Undead Crossing" of EI, enemy spawning event at turn 20 is not triggered.

The event name (at line 629 of scenarios/06a_Undead_Crossing.cfg) may be the problem.
`        name=side 1 turn {SCENARIO_TURN_LIMIT} END`
The event name seems to be case-sensitive. The event is triggered as expected when I modify "END" to "end".

The "defeat" event of {FOREIGN_DEFEAT} macro is correctly triggered (probably from "time over" event?).

### Steps to reproduce the behavior

1. begin Easter Invasion campaign with debug mode (or enable debugging in-game)
2. :cl  (choose level debug command)
3. (choose scenario 06a Undead Crossing)
4. :turn 20  (debug command)
5. end turn
6. enemy spawning event does not happen (and then you lost)

### Expected behavior

Enemy spawning event is triggered when I finish turn 20.

**Comment by Dalas121** [comment]
PR created, thanks for the report.  #8379
