### ISSUE TITLE
EI conflicting genders for Gaennell

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8389]
### Game and System Information

- **Version:** 1.17.25+dev

### Description of the bug

Eastern Invasion has a character called Gaennell, who's something of a easter egg - they're a minor enemy with a custom portrait who via an obscure path (requiring you to obtain another hard-to-get character first) can be turned into a loyal ally who advances to a custom class based on the Shadow Mages from Liberty.

Bug: their gender is inconsistent.

Note: getting the right gender is important. In the same way that the English UI shows whether an L2 unit is a Dark Sorcerer or a Dark Sorceress, some languages split the L1 unit names into Dark Adapt / Dark Adaptess.

* S01 and S13 both create the character as a male Dark Adept
* S13 has some dialogue involving them, but no pronouns are used
* S01 has a WML comment (not a po hint) that Gaennell is female
* Issue [#8380](https://github.com/wesnoth/wesnoth/issues/8380) gives Gaennell the po hint "this guy"
* If Gaennell becomes an ally, they can level up into the female-only L2 `female^Shadow Mage` unit type
* The character has a [custom portrait](https://raw.githubusercontent.com/wesnoth/wesnoth/master/data/campaigns/Eastern_Invasion/images/portraits/gaennell-adept.webp?raw=true)

@Dalas121, @tamanegi-jp and @hermestrismi what are your opinions?

**Comment by hermestrismi** [comment]
if I understand well, then the character must be "neutral" in first (like not using neither him nor her. just impersonal phrases like 'those people') then he turned into female in personal sentences. do this need many changes in the script?

**Comment by tamanegi-jp** [comment]
There is also a comment in last breath event (utils/deaths.cfg) "# if she gets executed while a prisoner, don't trigger her death line".  The custom portrait is also based on female adept. So I always think Gaennell is a woman.

BTW, in S01 Gaennell is male, but in S13 Gaennell's gender is random. This is due to the difference between NAMED_LOYAL_UNIT (S01; no gender specification) and NAMED_NOTRAIT_UNIT (S13; random_gender=yes) macros. I don't know why there is a difference in these macros...

**Comment by Dalas121** [comment]
Yes, intended to be a female character - S01/S13 gender issues is unintentional.  Unit should always be female.

**Comment by Wedge009** [comment]
> ...some languages split the L1 unit names into Dark Adapt / Dark Adaptess.

Dark Adept?
