### ISSUE TITLE
UtBS S1: Shaman/Cuttlefish event triggers 'inconsistent'

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#8397]
### Game and System Information

- **Version:** 1.17.25

### Description of the bug

Sort of two bugs, but I believe they form one issue.

Some context first:
Before the map was reworked (and much improved), the island with the shamans used to be reachable **only through the bridge**.
![old map](https://github.com/wesnoth/wesnoth/assets/39015360/c19b288e-9842-45c4-b8a7-7eed3b4f6609)

Since 1.16 (and probably 1.15), that's no longer the case, you can also reach it by wading through some shallow water to the north.
![new map](https://github.com/wesnoth/wesnoth/assets/39015360/efadac10-e248-466f-b666-c0c24ea36110)

Which brings me to the bugs.
1) You can't find the Shamans by reaching the island from the north.
![noshamans](https://github.com/wesnoth/wesnoth/assets/39015360/6e3e2a76-e9d0-420f-a7c7-2bccf8b0684d)
To find the shamans, you first need to spot the bridge leading to the island. Likely, because before 1.16 that was the only way to reach the island.
So, lets spot the bridge while on the island. And lets talk about it leading to the island and that one should be careful. Weird, but not a problem.
![bridge](https://github.com/wesnoth/wesnoth/assets/39015360/dfe32129-36ad-4523-baf8-3e59b45348fe)
![shamans](https://github.com/wesnoth/wesnoth/assets/39015360/68e17cae-7f72-4c50-92f4-20873833c7c3)

Bug number 2) The cuttlefish only appears if you move to the southern edge of the island or somewhere in the water south of the island. Before 1.16 that was the only way to leave the island. Now on the other hand, you can just leave to the north. No cuttlefish.
![no cuttlefish](https://github.com/wesnoth/wesnoth/assets/39015360/f81b7b20-fd52-406e-9ee1-d094d11e5ace)

### Steps to reproduce the behavior

Approach the island from the north, without spotting the bridge beforehand.
Spot the bridge.
Leave with the Shamans to the north.

### Expected behavior

Since there is this way to the island, I'd expect it to trigger an event about me going to the island, which would enable me to meet the shamans. (Maybe also decouple the two events, to make it more debug proof.)

The cuttlefish situation...I expected it to trigger when going north as well. @Hejnewar pointed out that by going north your shaman loses out on Garaks teaching xp, and that you can't immediatly send your druid to heal your units, so it's not just upsides without downsides.
So it could stay like this, with no cuttlefish to the north, but I'd suggest that Zhul tells you about the possibility of the monster to the south when you find Zhul, so you get to decide if you want to fight it, or if you want to skip it, both which comes with up- and downsides.
(Either that, or just trigger the cuttlefish always.)

Hope that made sense.

**Comment by stevecotton** [comment]
Finding the druids was fixed in #8281.

The cuttlefish spawn became an intended feature in #8281, with an improved comment about it being added to the code in the currently open #8423 (although that's mostly a code change to S05).
