### ISSUE TITLE
Text looking weird when a unit is selected while you don't hover above said unit

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#8398]
### Game and System Information

- **Version:** 1.17.25
- **Downloaded from:** Steam
- **OS:** Windows 7

### Description of the bug

See title
![grafik](https://github.com/wesnoth/wesnoth/assets/39015360/d6250daf-f133-4523-b044-24b19e579f3f)
As you can see it's most obvious in dialogue text, it's like the text gains a black edging? It's also a bit noticeable on HP, XP, MP numbers, the alignment, and the traits of the selected unit.

### Steps to reproduce the behavior

Select a unit. Move the cursor away

### Expected behavior

This not happening.

**Comment by Wedge009** [comment]
Just looking at the image I'm not quite sure what the 'weirdness' is supposed to be. I had a look at master @ 029da006818, selected a unit and hovered on and off the selected unit and (only at pixel scale multiplier x1) I do notice a slight difference in the intensity of the colours - as though the text might be rendered twice when hovering over the unit - but it's very subtle and I wouldn't describe it as 'weird' at all. Am I missing something?

**Comment by Vultraz** [comment]
This is the result of `pango_text::add_font_outline`...
