### ISSUE TITLE
Checkmark for 'skip animation' durings replays disappears (1.17)

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#8399]
### Game and System Information

- **Version:** 1.17.25
- **Downloaded from:** Steam
- **OS:** Windows 7

### Description of the bug

When you load a replay, you can check the box for 'skip animation'. This checkmark turns invisible when you interact with the replay buttons. (Any of the buttons. I tried. :D (Even just changing the point of view.)
When 'unchecking' the box after the checkmark disappeared you briefly see the checkmark again. (This behaviour differs from 1.16 where clicking on the box without releasing previews the checkmark being gone. Unchecking the box when the checkmark is visible has the same behavior as in 1.16.) 
It's odd. Can confirm that this behaviour does not happen on 1.16.11.
![this stuff](https://github.com/wesnoth/wesnoth/assets/39015360/dfeb9bdc-fb7a-4c38-aebb-0413105444d4)
(For reference.)

### Steps to reproduce the behavior

1. Load a replay.
2. Check the box.
3. Interact with the replay buttons.

### Expected behavior

This not happening. :D

### Additional context

[UtBS-The Morning After Turn 11.gz](https://github.com/wesnoth/wesnoth/files/14259054/UtBS-The.Morning.After.Turn.11.gz)
Just in case you don't have a 1.17 replay or save.

**Comment by Wedge009** [comment]
This seems to have started in 2f3927733d0c41fde4fe16427d96d67314c97269 by @Vultraz, present since 1.17.3. Hard to see what might be responsible, though - there's a lot of noise from the clean-up (which is why I try to keep such changes in separate commits).

**Comment by Wedge009** [comment]
Thanks for the quick resolution.
