### ISSUE TITLE
UtBS Tauroch unit sprites squished in the unit information

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#8401]
### Game and System Information

- **Version:** 1.17.25
- **Downloaded from:** Steam

- **OS:** Windows 7

### Description of the bug

![squish](https://github.com/wesnoth/wesnoth/assets/39015360/c8943059-7ba7-488a-a961-28294c008c7e)

### Steps to reproduce the behavior

Check the unit information of the tauroch units

**Comment by Wedge009** [comment]
At first I thought this might have been related to #7472 or #8303. But this appears to have been introduced with d4b7064904c86ec87a1bdf4744379078dbd0cc38 by @Vultraz for removing xbrz use, not yet released. It looks like the `SCALE_SHARP` macro requires dimensions as parameters and it looks like it's assumed that all unit sprites are 1:1 aspect ratio - but clearly this is not the case.

**Comment by Wedge009** [comment]
It looks like `unit_type::image()` just returns a string representing the image location. Is it possible to find the image dimensions in this context?

https://github.com/wesnoth/wesnoth/blob/600c88c2913e0139d418418468e90d279b590dde/src/help/help_topic_generators.cpp#L300-L310

**Comment by Vultraz** [comment]
I can either revert the commit in question or we can just merge the relative scaling for SCALE pr (#8217)

**Comment by Wedge009** [comment]
Would that mean xbrz  needs to hang around? I don't really know what's going on there, but I was under the impression its use was being removed.

I don't know the implications in terms of deprecation (discussed in the PR), but overall having a scaling-by-percentage option seems the best solution to me.

**Comment by Vultraz** [comment]
We're going to keep XBRZ around after all, so that's not an issue. But I'd still like to keep it NN there, I think. @Pentarctagon what say you? Merge 8217 or no to address this?

**Comment by Pentarctagon** [comment]
Was there a reason for replacing xBRZ with NN besides trying to remove usage of xBRZ?

**Comment by Vultraz** [comment]
Visual consistency with the rest of the UI. Basically every equivalent UI element (the unit preview pane in Attack, Create Unit, etc) uses NN.

**Comment by Pentarctagon** [comment]
Given it was using xBRZ for ~7 years before that, I think for now just reverting to xBRZ is fine.

**Comment by Vultraz** [comment]
Still needs mitigation on 1.18, BTW

**Comment by Wedge009** [comment]
Any reason for not back-porting to 1.18? Is it because #8217 needs to be back-ported as well?

Re-opening as specific to 1.18 until it's resolved.

**Comment by CelticMinstrel** [comment]
Could change it to `~XBRZ(2)` on 1.18 – if I recall correctly, that should still work, right?

**Comment by Wedge009** [comment]
That's what it was before d4b7064904c86ec87a1bdf4744379078dbd0cc38. So revert the change on 1.18 and continue with the removal of xBRZ in 1.19?

**Comment by CelticMinstrel** [comment]
That seems reasonable, yes.

I'm not sure if we're going to remove xBRZ as an available algorithm for scaling. I do think removing the `XBRZ()` IPF might not be a bad idea, however. It's not very flexible, which makes it poor as an API in my opinion. The various `SCALE*` IPFs are much better in that respect. So I think I'd prefer to see it integrated into those in some way, either as an option, or under certain circumstances, or something.

But that's not really a question for right now.

**Comment by Vultraz** [comment]
I'm fine with the revert for 1.18, though IMHO it would be nice if useful things like the SCALE enhancements made it into a point release for 1.18 rather than having to wait years until 1.20.

**Comment by Wedge009** [comment]
I don't see why what was done for master can't be repeated for 1.18, but the decision for this and discussion surrounding whatever resolution is why I felt this issue should be left open.
