### ISSUE TITLE
wmlxgettext: [message]speaker is incorrectly attributed to a previous message

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8411]
### Game and System Information

- **Version:** 1.17.25+dev (4567d56e226fde63ecec760887f49bb371517dcd)
- **Downloaded from:** Git
- **OS:** Debian Trixie (Linux)

### Description of the bug

This WML
```
        [message]
            speaker=Dacyn
            message= _ "Quiet, someone approaches..."
        [/message]
        [message]
            caption= _ "Unknown"
            image=units/unknown-unit1.png
            message= _ "..."
        [/message]
```

Will turn up in the .pot file as if Dacyn said "Unknown" (filenames omitted):
```
#. [message]: speaker=Dacyn
msgid "Unknown"
```

**Comment by CelticMinstrel** [comment]
The example doesn't seem to support the phrasing of the title. Isn't it more like the speaker is being inherited from one message to the next? Does the speaker hint also get applied to the correct message?

**Comment by stevecotton** [comment]
Thanks for catching the error in the title, and making me look at this again.

I've just found that it's not a bug in wmlxgettext - in EI S16 there's a message with both `speaker=Dacyn` and `caption=_ "Unknown"`, so the po hint is picking up `speaker=Dacyn` from that one.
