### ISSUE TITLE
EI S12 vs S18: Different uses of `dra_nak_dead`

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8414]
### Game and System Information

- **Version:** 1.17.25 (checked in the tagged version, as I'm doing unrelated changes around these files)

### Description of the bug

Two bugs so closely related that they belong in the same bug report:

S18 conditionally forwards the player to the bonus scenario, S99. One of the required conditions is that `dra_nak_dead` is not `yes`. The victory event of S12 unconditionally clears `dra_nak_dead`, meaning that that test in S18 will always pass.

S12 tests `dra_nak_dead` to see if he was killed in S11, and if he wasn't then it renames "Varrak-Klar" to "Chief Dra-Nak", as if Dra-Nak was pursuing the heroes. However, S12 doesn't set the `dra_nak_dead` variable if the renamed Varrak-Klar dies.

**Comment by stevecotton** [comment]
BTW, in S12 when Owaec destroys the bridge, it'll kill any flying zombies created by the plague staff. Is that an oversight? (It doesn't seem serious enough to make a bug report for.)

**Comment by Dalas121** [comment]
Ah, yes that's an oversight.  Will fix in the same PR.
