### ISSUE TITLE
EI S13: Gaolers don't show their movement when hovered over

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8420]
### Game and System Information

- **Version:** 1.17.25+dev (8d3a52eb3fb4e32c5e013eac0bf0a5d7c63839ec)

### Description of the bug

In S13, the gaolers have `max_moves=0`, because they only move via scripting. A side-effect of that is that the player can't see their movement range by hovering the mouse over them during the player's turn.

**Comment by Dalas121** [comment]
Is this an issue that needs to be fixed?  Showing their movement range wouldn't very useful to the player either, since they don't use all of it.

**Comment by stevecotton** [comment]
It probably doesn't need to be fixed, maybe review it again before closing though.

**Comment by Dalas121** [comment]
Yes, intent was to sound "medieval-esque."  I'm open to changing it if it sounds odd.

**Comment by CelticMinstrel** [comment]
Well, "sounds" isn't the right term, since "gaol" and "jail" are pronounced the same… in any case, I don't have a strong opinion on this matter, but I suppose I would mildly prefer not seeing a bizarre rule-breaking spelling like "gaol".
