### ISSUE TITLE
Translatable string cleanup (text widgets and WoF's advantage dialog)

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8430]
Some new strings got in.

A couple of these have merely moved up in their po file because they got copied to an alphabetically earlier file:
* wesnoth-lib "Missing required state for editable text box"
* wesnoth-units "Paladin", and the description of that unit

From here onwards are new strings:

+#: src/gui/widgets/scroll_text.cpp:233 src/gui/widgets/scroll_text.cpp:234
+msgid "Missing required state for scroll text control"

+#: src/gui/widgets/scroll_text.cpp:236
+msgid "No grid defined for scroll text control"

+#: src/gui/widgets/spinner.cpp:143 src/gui/widgets/spinner.cpp:144
+msgid "Missing required state for spinner control"

+#: src/gui/widgets/spinner.cpp:146
+msgid "No grid defined for spinner control"
 
+#. [args]
+#: data/campaigns/Winds_of_Fate/scenarios/03_The_Contention.cfg:371
+msgid "dialog^Advantage"

**Comment by stevecotton** [comment]
The WoF one comes from #8384, but it's a missing string rather than a new one. The old code was trying (and failing) to include it in `wesnoth-multiplayer`, which is why it didn't get caught during the code review. It will be player-visible, so my feeling on this one is to accept that it should be in the .po file.

The ones in the new widgets are all in `VALIDATE_WML_CHILD` calls, so it's no big issue for them to be untranslatable.

**Comment by stevecotton** [comment]
@babaissarkar sorry, but we need to clear up those four strings somehow.

**Comment by babaissarkar** [comment]
I wonder if it will be possible to change those strings to something like "Missing required state for $type control", in that way we won't need more strings if new widgets are added in the future.

**Comment by CelticMinstrel** [comment]
> I wonder if it will be possible to change those strings to something like "Missing required state for $type control", in that way we won't need more strings if new widgets are added in the future.

This isn't possible because of case systems, arbitrary gender, and similar grammatical constructs. Some languages would need to alter various words in that sentence differently depending on the value of `$type`.

**Comment by stevecotton** [comment]
These are ones where the error message is going to be along the lines of "Error. *bunch of technobabble*. Please report this to the respective authors or maintainers of these add-ons.". The technobabble doesn't really need to be translatable.

**Comment by CelticMinstrel** [comment]
I guess if `$type` references the actual name of the tag in code, then that format is fine – any reference to actual code should not be translated for sure.

**Comment by stevecotton** [comment]
Fixed by accepting the WoF string as new, and by #8433 for the other strings.
