### ISSUE TITLE
Missing/moved loyalist and undead unit images in MP Aethermaw

### ISSUE THREAD

**Issue by pehjota** [wesnoth/wesnoth#8432]
### Game and System Information

- **Version:** 1.17.25

### Description of the bug

While testing multiplayer on the "2p — Aethermaw" scenario as Loyalists vs. Undead, I noticed some `error image: could not open image` messages on the console:

    20240219 06:50:21 error image: could not open image 'units/undead/shadow-s-attack-1.png'
    20240219 06:50:21 error image: could not open image 'units/undead/shadow-s-attack-4.png'
    20240219 06:50:21 error image: could not open image 'units/undead/shadow-n-3.png'
    20240219 06:50:22 error image: could not open image 'units/undead/shadow-n-attack-2.png'
    20240219 06:50:26 error image: could not open image 'units/human-loyalists/spearman-attack-se-9.png'
    20240219 06:50:26 error image: could not open image 'units/human-loyalists/spearman-attack-se-10.png'
    20240219 06:50:26 error image: could not open image 'units/human-loyalists/spearman-attack-s-6.png'
    20240219 06:50:26 error image: could not open image 'units/human-loyalists/general-idle-5.png'

Indeed, those images don't exist under `data/core/images/`.  But files of the same name may exist elsewhere (e.g. `units/undead-spirit/shadow-s-attack-1.png`).  [It looks like at least some of this is known.](https://forums.wesnoth.org/viewtopic.php?p=684291&hilit=units%2Fundead-spirit%2F#p684291)

### Additional context

EDIT (from [below](https://github.com/wesnoth/wesnoth/issues/8432#issuecomment-1953374250)): The campaigns were false positives.  wmllint will fix the moved `units/undead/*` images.  But those `units/human-loyalists/*` images are actually missing. They were removed in commit 8e38cfd01ad, specifically "spearman image cleanup" commit 775e7f85c0b and "remove left-over old general frames" commit e07d554c524 in #7208.

Following is a generated list of:

    missing-image  wml-file-that-references-it:line-number

The first one (`data/core/images/misc/blank-hex.png`) exists and is probably a false positive (or does `data/core/images/` need removed?).

    $ git grep -EIn -- '^[^#]*[{]PLACE_IMAGE[^ ]* +[(]?"?[^{}$ ~")]+[ ~")].*$' data/ | while IFS=':' read -r wml ln img; do img="$(printf '%s' "${img}" | sed -En 's|^.*[{]PLACE_IMAGE[^ ]* +[(]?"?([^{}$ ~")]+)[ ~")].*$|\1|p')"; [ -e "data/core/images/${img}" ] && continue; case "${wml}" in data/campaigns/*) sfx="${wml#data/campaigns/*/}"; [ -e "${wml%/${sfx}}/images/${img}" ] && continue;; esac; printf '%s  %s:%d\n' "${img}" "${wml}" "${ln}"; done | sort -k 2,2 | sort -k 1,1 -s
    data/core/images/misc/blank-hex.png  data/campaigns/Eastern_Invasion/scenarios/14_The_Drowned_Plains.cfg:757
    units/human-loyalists/general-idle-5.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:203
    units/human-loyalists/spearman-attack-s-6.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:197
    units/human-loyalists/spearman-attack-se-10.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:196
    units/human-loyalists/spearman-attack-se-9.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:198
    units/undead/shadow-n-3.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:147
    units/undead/shadow-n-attack-2.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:135
    units/undead/shadow-s-attack-1.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:134
    units/undead/shadow-s-attack-4.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:149

**Comment by knyghtmare** [comment]
Seems like an oversight from when the image paths were changed. Careful checks should have been done...Oh well.

**Comment by pehjota** [comment]
It looks like it affects both multiplayer and campaigns, though multiplayer is where I noticed it.  I haven't played through the campaigns to encounter the issue.

**Comment by sevu** [comment]
running wmllint should fix these

**Comment by pehjota** [comment]
> running wmllint should fix these

It'll fix some of these, e.g.:
https://github.com/wesnoth/wesnoth/blob/10733b1071bd99191b1adfd6717919e0cb111f62/data/tools/wmllint#L1300

But not all, e.g. `items/*`, `scenery/`, `units/human-loyalists/*` and `units/monsters/flesh-golem.png`.

**Comment by pehjota** [comment]
Sorry, it looks like the campaigns were false positives, e.g. `scenery/blood-*` exist under `data/campaigns/Eastern_Invasion/images/`.

Assuming the `data/core/images/` path prefix in EI S14 is OK, only one multiplayer scenario is affected:

    $ git grep -EIn -- '^[^#]*[{]PLACE_IMAGE[^ ]* +[(]?"?[^{}$ ~")]+[ ~")].*$' data/ | while IFS=':' read -r wml ln img; do img="$(printf '%s' "${img}" | sed -En 's|^.*[{]PLACE_IMAGE[^ ]* +[(]?"?([^{}$ ~")]+)[ ~")].*$|\1|p')"; [ -e "data/core/images/${img}" ] && continue; case "${wml}" in data/campaigns/*) sfx="${wml#data/campaigns/*/}"; [ -e "${wml%/${sfx}}/images/${img}" ] && continue;; esac; printf '%s  %s:%d\n' "${img}" "${wml}" "${ln}"; done | sort -k 2,2 | sort -k 1,1 -s
    data/core/images/misc/blank-hex.png  data/campaigns/Eastern_Invasion/scenarios/14_The_Drowned_Plains.cfg:757
    units/human-loyalists/general-idle-5.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:203
    units/human-loyalists/spearman-attack-s-6.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:197
    units/human-loyalists/spearman-attack-se-10.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:196
    units/human-loyalists/spearman-attack-se-9.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:198
    units/undead/shadow-n-3.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:147
    units/undead/shadow-n-attack-2.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:135
    units/undead/shadow-s-attack-1.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:134
    units/undead/shadow-s-attack-4.png  data/multiplayer/scenarios/2p_Aethermaw.cfg:149

**Comment by pehjota** [comment]
Thanks for the label and milestone updates, although "Campaigns EI" can also be removed and "Units" didn't have to be.

wmllint does a lot more than just renaming the undead images, including adding and removing translation marks.  Some are newly translatable strings, so wmllint output shouldn't go in 1.17/1.18.  And some of wmllint's new translations look questionable, like "<span color='#ff7722'>" shouldn't be translated.

I'll send a PR to fix just this without everything else wmllint does, along with a CI check to prevent it in the future.

**Comment by CelticMinstrel** [comment]
> But not all, i.e. `units/human-loyalists/*` are missing (see below).

Those should be added to wmllint, then.

**Comment by pehjota** [comment]
> > But not all, i.e. `units/human-loyalists/*` are missing (see below).
> 
> Those should be added to wmllint, then.

If they're changed to different images as suggested in #8435/#8436, then yes, they should be added to `linechanges` in wmllint.  Or are you suggesting that wmllint should (but doesn't) look for missing images?  Not being very strong in Python or familiar with all of wmllint's code, I probably wouldn't be the one to make such a change.

**Comment by CelticMinstrel** [comment]
I was assuming each of them have reasonable replacements, yes. Even if it's not a straight move of the file, even if the number of frames in the animation was changed, I'd think there's at least one image among the new ones that could be thought of as "pretty close" to each of the old ones.

I wasn't suggesting that wmllint should warn about deleted images, but that wouldn't be a bad thing to do either.

**Comment by pehjota** [comment]
Yeah, in the PRs we're awaiting a review from doofus-01 to say whether there are suitable replacements for the Loyalist images.

**Comment by Wedge009** [comment]
Closing due to lack of response. If there's anything still outstanding it can still be re-opened, of course.
