### ISSUE TITLE
Being able to filter campaigns for completion status

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#8441]
### Describe the desired feature

My idea would to add the kind of filter that's used in the add-on manager for 'Type', 'Tags', 'Language'.
![add-on filter](https://github.com/wesnoth/wesnoth/assets/39015360/0a204078-371c-4cd4-9541-b471538c0845)

That way you can select multiple kinds of completion status, like 'No completion', 'Gold/Silver/Bronze Laurel'.
Why? Because that makes it easier to spot/find campaigns you haven't completed yet without having to know what all those campaigns are called.
![spotting campaign](https://github.com/wesnoth/wesnoth/assets/39015360/b6a13ef8-2728-49dc-a79e-e5f8d2ae662a)
Spot the campaign. D:

To provide another usecase:
There are 200ish user made campaigns on the 1.16 server, and I very much hope that a significant number of then will be ported to 1.18+.
(Btw, hey, thanks to everyone for implementing the search functionality in the campaign dialog when I requested it. It was very very helpful. :D)

**Comment by Konrad22** [comment]
I would say that's an improvement, but a _lesser_ improvement, as I can't combine that with sorting by name or timeline when I want to look for a specific campaign I haven't played yet.

**Comment by Konrad22** [comment]
> If the sort isn't stable, then that's a bug. You should be able to sort by year, then completion status, and see campaigns you haven't completed in chronological order.

Huh. Yeah, that would work. I had only considered it in the way we have timeline and alphabetical, which don't mesh that well together. It should work with completion, since there are only 4 possible options.

**Comment by babaissarkar** [comment]
#8451 adds toggle buttons for filtering.
The more complex task would be figure out how many scenarios the user has completed out of the total number of them. I haven't figured out if the game keeps track of that.

**Comment by CelticMinstrel** [comment]
What haven't you figured out, exactly…?

**Comment by babaissarkar** [comment]
> What haven't you figured out, exactly…?

1. Exact number of scenarios that a player has completed in a campaign
2. Total number of scenarios in a campaign

I can divide these two to get the user's progress (maybe as a percentage).

**Comment by CelticMinstrel** [comment]
I'm pretty sure the game only tracks whether or not the campaign was defeated, and on what difficulty level. So the data you're looking for doesn't exist.

The "total number of scenarios in a campaign" isn't even a thing that's defined. A campaign might have a different number of scenarios depending on the playthrough. It could require you to play the same scenario multiple times. There isn't even any requirement that campaigns are linear or even a DAG. You could make a campaign where you travel back and forth between various scenarios, the objectives slowly being modified each time depending on what you did elsewhere.

**Comment by Konrad22** [comment]
> #8451 adds toggle buttons for filtering. The more complex task would be figure out how many scenarios the user has completed out of the total number of them. I haven't figured out if the game keeps track of that.

I think you are trying to overengineer a solution for this request that's beyond what is needed and beyond what could work. Sorting by 'best laurel' status is exactly what's needed, and much easier to do.
(Thank you for trying to make a solution, I just don't want you to take on more work than is actually necessary.)

**Comment by CelticMinstrel** [comment]
Even if tracking completion status of a campaign is desirable, I think it would be best for each campaign to just implement it as an achievement for that campaign. What "completion" means probably varies depending on the campaign. And even if we preferred to integrate such a completion tracker into the engine somehow, I think it would still need to be left up to each campaign how it's actually done.

Regardless, completion status beyond "what difficulty did I beat this on, if any" is beyond the scope of this issue, I believe.

**Comment by babaissarkar** [comment]
@Konrad22 So what #8451 already does is enough for what you were asking?

@CelticMinstrel  Yes, I think I almost forgot about nonlinear camapaigns. In that case it's not possible to get it's partial progress unless the campaign defines it in some way.

**Comment by Konrad22** [comment]
> @Konrad22 So what #8451 already does is enough for what you were asking?

This on the other hand is actually a bare minimum, as my idea was to filter for laurel status as well. :D Like, yes, that absolutely works too, and I'm all for it if that makes the most sense, but it is less than requested. :D

**Comment by babaissarkar** [comment]
> > @Konrad22 So what #8451 already does is enough for what you were asking?
> 
> This on the other hand is actually a bare minimum, as my idea was to filter for laurel status as well. :D Like, yes, that absolutely works too, and I'm all for it if that makes the most sense, but it is less than requested. :D

Just trying to understand what's actually needed.

![Screenshot from 2024-02-24 16-08-23](https://github.com/wesnoth/wesnoth/assets/8469888/47905110-a748-420e-b805-d4c085c581bd)

This should fulfil the criteria you mention, right?

**Comment by Konrad22** [comment]
> Just trying to understand what's actually needed.
> 
> 
> This should fulfil the criteria you mentioned, right?

Yes, albeit I'm not sure how useful 'Completed : All' actually is. But just because I wouldn't use it, doesn't mean noone would.

**Comment by babaissarkar** [comment]
#8451 has been merged, so I'm closing this.
