### ISSUE TITLE
Polish Translations for Campain

### ISSUE THREAD

**Issue by Rakid1** [wesnoth/wesnoth#8444]
### Game and System Information

- **Version: Windows**
- **Downloaded from: Steam**
- **Build info:**
- **OS:**

### Description of the bug

There is a lot text in english and, some text have bug that the file isn't correct. I could help with the translate ; ) Just please repair that

### Steps to reproduce the behavior

1. Aswer me
2. I can help

**Comment by Rakid1** [comment]
> We usually gather on dicord now for translations. If you can please join there.

Can you get me link please? I can't find it

**Comment by Hejnewar** [comment]
https://discord.gg/G3d9VKyq

**Comment by Wedge009** [comment]
This seems more like a communication piece than an actual bug report. Hence, closing (though that doesn't mean the conversation can't continue).

I also note on the [wiki](https://wiki.wesnoth.org/WesnothTranslations) that the Polish translation folks use a [forum thread](https://forums.wesnoth.org/viewtopic.php?f=7&t=3796). If that's no longer accurate, could you update it?
