### ISSUE TITLE
Highlight Add-ons in the Campaign Menu

### ISSUE THREAD

**Issue by Dalas121** [wesnoth/wesnoth#8478]
### Describe the desired feature

Wesnoth has a huge amount of high-quality user-made campaigns, but it's not immediately apparent that clicking the "add-ons" button gives you access to these.

I suggest adding a note at the bottom of the mainline campaigns list, explaining that many high-quality, non-canon campaigns are available through the add-on server, and including a button to reach the add-on server.

**Comment by Wedge009** [comment]
Sort of, very loosely, related was the problem of handling the case where there were no official campaigns listed: #7875. If I recall correctly, the resolution in #8041 was to have a 'missing campaign' message at the bottom of the list. Not sure if something similar to advise of add-on campaigns should be done but I suppose that's an option.

**Comment by CelticMinstrel** [comment]
Also, I think that button should open the add-on manager with the filter settings prefilled to single-player campaigns.

**Comment by babaissarkar** [comment]
UI mockup:
![Screenshot from 2024-10-12 23-09-26](https://github.com/user-attachments/assets/86ff568e-37e9-4f62-a289-d795a7f6b04d)
