### ISSUE TITLE
Horseman unit damage is misrepresented in unit card

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8486]
### Game and System Information

- **Version: 1.17.26**
- **Downloaded from: Steam**
- **Build info: /**
- **OS: Windows 10 Home**

### Description of the bug

The Horseman unit shows a damage value for its melee attack on its unit card that is already doubled, which doesn't seem right because the charge effect shouldn't be applied unless they are in combat as the attacker. When recruiting the unit or when viewing the unit information it does not show this damage doubled. When attacking it does show the damage doubled, but that makes sense because the charge effect is being applied in this moment. 

I first noticed this issue when playing the second scenario in an HttT campaign, but I have checked in a multiplayer scenario against the ai and the issue shows itself here as well so it seems to be a thing for this unit anywhere in the game.

### Steps to reproduce the behavior

There are no steps required to reproduce the issue. Combat did not happen yet so it's not like it doubled in combat and then didn't change back.

### Expected behavior

The unit card should show the same damage value as the unit information view (9x2). I have added screenshots to show the isse. Note that the screenshot is taken in twilight (+0%) and the shown unit has the 'Strong' trait, so his unit card should show 10x2 but shows 20x2 instead.

![Screenshot (9)](https://github.com/wesnoth/wesnoth/assets/157546742/972fc3b7-224a-4ca7-8dae-60975c034173)
![Screenshot (58)](https://github.com/wesnoth/wesnoth/assets/157546742/dd577946-186b-49e6-8283-6e3ebe2d8dbf)
![Screenshot (56)](https://github.com/wesnoth/wesnoth/assets/157546742/e8b1e630-9370-4ed1-998c-3b71bcd85eda)
![Screenshot (57)](https://github.com/wesnoth/wesnoth/assets/157546742/7ac37048-7f1c-4652-8fef-f39b8189d0b8)

**Comment by knyghtmare** [comment]
This is not a bug. 

It shows the damage that can be dealt during the player's turn (in which the unit is attacking where charge is ON). During the night the number will change back to 7 - 2 (for non-strong horseman with -25% ToD)

During the day, the value of 22 - 2 is expected. 9 * 1.25 (ToD) = 11 * 2 (Charge is ON) = 22
So, sidebare shows as 22 - 2

**Comment by OrangePumpking** [comment]
Ah I see. I personally find that a tad confusing but I can see the logic behind it. Thanks for your response!

**Comment by gfgtdf** [comment]
Yes this was iirc an intentional change at some point, (i'd stil disagree with it though)
