### ISSUE TITLE
WoF: Village in map border in scenario 9

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesnoth#8494]
### Game and System Information

- **Version:** 1.18 branch from Git

### Description of the bug

WoF scenario 9 includes a village stuck in the map border at 39,23. In the past we've avoided having these in maps because they can cause confusion for players due to them being visible but impossible to capture.

Bear in mind that the map in question is shared with scenarios 10 and 11, as well as the extra `HM_Master.map` file. In particular, in scenario 11 the village in question *is* within the playable region and *can* be captured.

One way this could be fixed is by making scenario 9's map smaller so as to not contain the village in question. Another way could be by doing the opposite and adding 1 or 2 extra columns to the right of the village. Removing the village seems like a more annoying alternative as it would require a change to the scenario 11 map for consistency.

**Comment by knyghtmare** [comment]
@Jonathan-Kelly

**Comment by Jonathan-Kelly** [comment]
Good catch. I suspect moving the village itself in by one tile (so that it can be captured) may be the safest fix for 1.18 (opened a PR with this solution).

**Comment by cooljeanius** [comment]
Just from looking at the map diff images in #8495, it looks like it should fix this, but I haven't tested myself, though
