### ISSUE TITLE
Story screen button layout perhaps could be improved for non-default text layout configurations

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesnoth#8508]
`[story] [part]` takes a configuration value `text_layout=` (one of `top`, `middle`, and `bottom`, the latter being the default) defining the vertical segment of the screen where the main story text should be shown. The problem is that currently, the pagination buttons are arranged exactly the same way for all three configurations, even though the layout only really fully makes sense for the `bottom` configuration:

### `text_layout=top`
<img width="1392" alt="Screenshot 2024-03-06 at 03 29 14" src="https://github.com/wesnoth/wesnoth/assets/489895/aeda9c79-805c-49c3-ada5-2ca8343d360c">

### `text_layout=middle`
<img width="1392" alt="Screenshot 2024-03-06 at 03 27 46" src="https://github.com/wesnoth/wesnoth/assets/489895/b11a17ea-718e-4693-9374-06dc0e0fd33b">

### `text_layout=bottom` (default)
<img width="1392" alt="Screenshot 2024-03-06 at 03 27 15" src="https://github.com/wesnoth/wesnoth/assets/489895/cf12e1f7-8075-4641-9b04-d4e4f5ae3862">

It feels like the top and middle configuration could be improved by placing the buttons in different positions. In particular, it's been suggested by [LuminousE on Discord](https://discord.com/channels/231976805987385345/442775044590927873/1214815715220267050) that the middle configuration could use having the buttons centred under the text block.

![Screenshot_from_2024-03-06_11-32-29](https://github.com/wesnoth/wesnoth/assets/489895/94364157-a947-4327-94d8-473a6b22359c)

**Comment by babaissarkar** [comment]
Possibly requires adjustments for `text_alignment` as well. (Imagine RTL text in the story. Many things in GUI2 require adjustments for RTL text.)

**Comment by babaissarkar** [comment]
Another idea : 
![Screenshot from 2024-03-06 12-16-36](https://github.com/wesnoth/wesnoth/assets/8469888/76525ef0-5e6e-4ecd-920b-229ad3d8ca0d)

![Screenshot from 2024-03-06 12-31-18](https://github.com/wesnoth/wesnoth/assets/8469888/ebf5d99e-4674-4eaf-8403-09d3305db720)


The button grid (left, right and skip) button are vertically centered.

**Comment by babaissarkar** [comment]
Another approach is presented in PR #8510

**Comment by babaissarkar** [comment]
The new layout implemented in #8510 makes the adjustment unnecessary, so closing this. Could be reopened later if necessary.
