### ISSUE TITLE
[BUG] Ambush Ability Does not Work in Bluff/Glutch Forest Terrain

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#8512]
### Game and System Information

- **Version:** 1.17.26+dev
- **Downloaded from:** GitHub
- **Build info:** Msys2 Compiler - latest commit (1.18 branch)
- **OS:** Windows (10)

### Description of the bug

Ambush ability is supposed to let the unit hide in all forest terrain, but these forested terrain: bluffed forest and glutched forest seem not be taken into consideration for this. Thus, ambush is broken in this case.

### Expected behavior

Ambush is working and the Elven Ranger is "hidden".

### Additional context

<img width="683" alt="Screenshot 2024-03-07 at 12 09 41 PM" src="https://github.com/wesnoth/wesnoth/assets/5283677/c76fc7f3-b4a6-4bbd-9690-8e64eb100c69">

**Comment by newfrenchy83** [comment]
fixed with https://github.com/wesnoth/wesnoth/pull/8518

**Comment by ProditorMagnus** [comment]
Root cause of the issue is that there is no way for filter for terrain group such as forest.

**Comment by soliton-** [comment]
It would be nice to be able to filter for terrain aliases instead of having to maintain matching patterns.
