### ISSUE TITLE
Add --no-log-to-file option to preferences

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesnoth#8527]
### Describe the desired feature

At some point relatively recently, wesnoth has started logging to a file instead of console or standard error.  At least for Linux CLI.

That's probably an improvement for some people, but I find it very unhelpful and wish there was some option to make the `--no-log-to-file` option persistent, without layering on some alias or launch script.  There is already a "logging" section in advanced preferences, it could go there.

**Comment by irydacea** [comment]
Because Wesnoth needs to log stuff to the console before it can even open and parse the preferences file, I'm tempted to say this would sense as an environment variable rather than a preferences setting.

**Comment by Pentarctagon** [comment]
Caused by #8391 for reference.

**Comment by Wedge009** [comment]
I thought the default logging to file was introduced well before that. Some time around the teens of 1.17.x. My recollection is #8391 was just an update/enhancement to it.

**Comment by Pentarctagon** [comment]
The default was to log to file for a while, but then eventually boost::tee was added to it would go **both** to file and to terminal. #8391 then removed use of boost::tee, since redirecting the underlying C stdout/stderr isn't compatible with it. So now it's back to only going to one or the other.

**Comment by Wedge009** [comment]
For myself, I just learned to use `--no-log-to-file` when running development builds from command-line. It's not too hard to get into the habit, though understand that it might seem an inconvenience at first.

**Comment by doofus-01** [comment]
> Perhaps you can describe your use case in more detail. As Iris says technically this can't really be done in preferences. Perhaps there can be workarounds for your case though. For example we could default to --no-log-to-file if stdout/stderr is a terminal if that helps. Or as suggested an env variable could be used instead.

Preferences would have been higher-visibility for the broader public, but an environment variable or "default if started from terminal" would be just as good for my case.  My use case is that I want to see the errors/notifications in real time, so I can correlate them with what happened in the game.  I'd imagine the log files are pretty useful for getting bug report info from players who weren't looking for that stuff, but I doubt I'd ever use the log files.

**Comment by Pentarctagon** [comment]
Yeah, logging to file is the default so the log files are already there for regular players without having to do anything. Checking an environment variable is definitely easier than checking if Wesnoth was started from a terminal though.

**Comment by soliton-** [comment]
Checking for a terminal is just an `isatty` call on POSIX. Not sure on windows though.
