### ISSUE TITLE
[units.wesnoth.org] Caribe and Hunter Caribe unit images are not shown.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#8538]
## Bug Screenshot

![image](https://github.com/wesnoth/wesnoth/assets/5283677/e424784d-61c5-43ff-94a5-7e5fc17669da)

## Expected Behaviour
I can see what the Caribe and the Hunter Caribe looks like from the UWO and not just their shadows.

- https://units.wesnoth.org/1.17/mainline/en_US/mainline.html#Monsters

**Comment by ProditorMagnus** [comment]
Then unit file should have image instead of shadow.

**Comment by soliton-** [comment]
Duplicate of #7052.
