### ISSUE TITLE
Eastern Invasion: incorrect bigmap localization text position

### ISSUE THREAD

**Issue by Dalas121** [wesnoth/wesnoth#8543]
The 1.17 version of EI moved the "southern outpost" location further south on the bigmap.  The english-text label is also moved, but other languages still use the old, incorrect label position.

I took a look at the localization.xcf file for the campaign, but don't understand it well enough to make the changes on my own.  What's the correct way to modify localization.xcf so it matches the ei.webp bigmap image?  Will that fix existing bigmap translations, or will those need to be edited manually?

**Comment by nemaara** [comment]
Oh oops. I might need help on this too lol, not sure how to fix it.

**Comment by Pentarctagon** [comment]
In the layers, it has:
![Screenshot from 2024-03-12 16-55-02](https://github.com/wesnoth/wesnoth/assets/3030250/b41599ad-5fc6-4d6d-9262-c4cc1c8ee641)

So presumably you'd need to move the label in the specific layer it's in?

**Comment by Pentarctagon** [comment]
Could you provide the updated xcf?

**Comment by Dalas121** [comment]
> based on what I understood from image map localization, we should
Gotchya, thanks.  I think I've made the necessary changes to the localization.xcf file - can you give this a try and make sure everything looks correct?

Can't attack the file to this comment, so you can grab my current version from the PR: https://github.com/wesnoth/resources/pull/5

**Comment by arosella** [comment]
It works, with issue... It seems that for some reason is not "correctly copying" the black labels
![ei--overlay](https://github.com/wesnoth/wesnoth/assets/4649401/82042e1e-eadb-48f2-a482-70b7c3f69356)

**Comment by Dalas121** [comment]
> P.S: the same issue happens using the original .xcf file ( the one with the misplaced outpost labels), so, my guess is that something is not working as expected in the script itself.

Hmm well that's really weird.  I don't suppose you know who's in charge of the tool?

**Comment by Pentarctagon** [comment]
Nobody at the moment.

**Comment by arosella** [comment]
Resuming my elder lisp knowledge ( more than 30 years ago...), I found that the issue seems to be located in the initial function, "pencil-effect". So, I remove it from the workflow, commenting out line 195 of wesnoth-map-localization.scm script, obtaining this: 
![Screenshot-1](https://github.com/wesnoth/wesnoth/assets/4649401/12a9c35b-f85f-451a-bcf1-b7ac172c4ec5)
![ei--overlay](https://github.com/wesnoth/wesnoth/assets/4649401/99da49c8-ce84-43a0-9a92-1b0ccce1b076)

**Comment by arosella** [comment]
Second attempt, re-enabled pencil-effect function and changed "radius" parameter at line 194 of the script
        ; (set! blacklabels1 (car (pencil-effect img blacklabels1 1 20) ) )
        (set! blacklabels1 (car (pencil-effect img blacklabels1 **3** 20) ) )
![Screenshot-2](https://github.com/wesnoth/wesnoth/assets/4649401/4cc927ff-522e-4f13-904f-d6a2ce11aa53)
![ei--overlay](https://github.com/wesnoth/wesnoth/assets/4649401/c467daf3-50bd-4821-a370-855b0284e5fa)

It works also with "2" as parameter, it can be evaluated which is the best value to be used

**Comment by arosella** [comment]
OK, to summarize actions to be done before closing the issue:

1.  update wesnoth-map-localization.scm, changing radius parameter of pencit-effect call at line 194 from 1 to 2 or 3, according to the artistic preferences ( here below the final italian customization with radius "2" and curved labels, both full map and overlay);
2. remove the gimp 2.8 warning from map localization wiki page, the script works with latest 2.10.34 release;
3. commit the ei_localization.xcf updated by Dalas121
![Screenshot-Final](https://github.com/wesnoth/wesnoth/assets/4649401/34e0cdce-b876-4607-b805-5a8a6a95d5b9)
![ei--overlay](https://github.com/wesnoth/wesnoth/assets/4649401/55864f0a-12fe-46c5-8a16-358ef529f1e7)

**Comment by Pentarctagon** [comment]
The updated `wesnoth-map-localization.scm` should also be committed I assume.

**Comment by arosella** [comment]
> The updated `wesnoth-map-localization.scm` should also be committed I assume.

Correct. My last map was created with a radius "2" in the script. Feel free to test different values and evaluate which is the best value...

**Comment by Pentarctagon** [comment]
Can you upload the working version you have somewhere?

**Comment by arosella** [comment]
$ diff wesnoth-map-localization.scm wesnoth-map-localization-2.scm 
50c50
< (define (wesnoth-localize-map orig_img)
---
> (define (wesnoth-localize-map-2 orig_img)
193c193
<         (set! blacklabels1 (car (pencil-effect img blacklabels1 1 20) ) )
---
>         (set! blacklabels1 (car (pencil-effect img blacklabels1 2 20) ) )
279,280c279,280
<     "wesnoth-localize-map"
<     "Map Localization"
---
>     "wesnoth-localize-map-2"
>     "Map Localization - v2"
282c282
<     "zookeeper"
---
>     "zookeeper & Antro"
289c289
< (script-fu-menu-register "wesnoth-localize-map" "<Image>/Filters/Wesnoth")
---
> (script-fu-menu-register "wesnoth-localize-map-2" "<Image>/Filters/Wesnoth")

**Comment by arosella** [comment]
`$ diff wesnoth-map-localization.scm wesnoth-map-localization-2.scm 
50c50
< (define (wesnoth-localize-map orig_img)
---
> (define (wesnoth-localize-map-2 orig_img)
193c193
<         (set! blacklabels1 (car (pencil-effect img blacklabels1 1 20) ) )
---
>         (set! blacklabels1 (car (pencil-effect img blacklabels1 2 20) ) )
279,280c279,280
<     "wesnoth-localize-map"
<     "Map Localization"
---
>     "wesnoth-localize-map-2"
>     "Map Localization - v2"
282c282
<     "zookeeper"
---
>     "zookeeper & Antro"
289c289
< (script-fu-menu-register "wesnoth-localize-map" "<Image>/Filters/Wesnoth")
---
> (script-fu-menu-register "wesnoth-localize-map-2" "<Image>/Filters/Wesnoth")
`

**Comment by arosella** [comment]
```
$ diff wesnoth-map-localization.scm wesnoth-map-localization-2.scm 
50c50
< (define (wesnoth-localize-map orig_img)
---
> (define (wesnoth-localize-map-2 orig_img)
193c193
<         (set! blacklabels1 (car (pencil-effect img blacklabels1 1 20) ) )
---
>         (set! blacklabels1 (car (pencil-effect img blacklabels1 2 20) ) )
279,280c279,280
<     "wesnoth-localize-map"
<     "Map Localization"
---
>     "wesnoth-localize-map-2"
>     "Map Localization - v2"
282c282
<     "zookeeper"
---
>     "zookeeper & Antro"
289c289
< (script-fu-menu-register "wesnoth-localize-map" "<Image>/Filters/Wesnoth")
---
> (script-fu-menu-register "wesnoth-localize-map-2" "<Image>/Filters/Wesnoth")

```

**Comment by Pentarctagon** [comment]
I mean can you upload just the entire scm file?

**Comment by arosella** [comment]
``
[wesnoth-map-localization-2.scm.gz](https://github.com/wesnoth/wesnoth/files/14626937/wesnoth-map-localization-2.scm.gz)

**Comment by Pentarctagon** [comment]
Thanks!

@Dalas121 can you add that to https://github.com/wesnoth/resources/pull/5 ?

**Comment by Dalas121** [comment]
Done!

**Comment by Pentarctagon** [comment]
No worries.
