### ISSUE TITLE
DiD: Malin Keshar's (Ancient Lich) AMLA "+1 Shadow Wave Damage" Increases Shadow Wave Damage by 2

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8549]
### Game and System Information

- **Version:**1.16.11
- **Downloaded from:**Flatpak
- **Build info:**
- **OS:**ChromeOS / Debian

### Description of the bug

The Shadow Wave AMLA description says it increases damage by 1 point but the actual damage increase is 2 points. 

![Screenshot 2024-03-14 01 49 20](https://github.com/wesnoth/wesnoth/assets/81496259/502aa8d4-ef1c-492e-984e-d38fa04b800b)
![Screenshot 2024-03-14 01 48 52](https://github.com/wesnoth/wesnoth/assets/81496259/ba410c47-09e6-40a6-8053-41afa22d767e) 

### Additional context

The actual increase may be intended to be 2 points to provide more of a reason to use the Shadow Wave attack.

**Comment by IskarJarak01** [comment]
I didn't realise how recent the Campaign specific labels are or how close Wesnoth is to a new mainline release (inside the month) and this is a fairly trivial issue so it should just be closed.

**Comment by soliton-** [comment]
If you look at the menu or the tooltip you see duplicate in there.

**Comment by CelticMinstrel** [comment]
Sure, it makes sense to close duplicates as "not planned" when the issue it's a duplicate of is still open; but in this case it's already been done, so that's weird.
