### ISSUE TITLE
Liberty S04 "Unlawful Orders" freezes when transforming units

### ISSUE THREAD

**Issue by Dalas121** [wesnoth/wesnoth#8550]
### Game and System Information

- **Version:** 1.17.26
- **Downloaded from:** Steam
- **OS:** Windows

### Description of the bug

When playing Liberty's 4th scenario, on turn 3 your human opponents are scripted to transform into undead versions of themselves.  While this transformation is taking place (after the flash but before units transform), Wesnoth freezes indefinitely.

Is this just on my PC, or does it happen for everyone?

### Steps to reproduce the behavior

Play Liberty's scenario 4, get to turn 3, then click "end turn".

**Comment by Pentarctagon** [comment]
I can't reproduce this. Using self-built Wesnoth on Linux.

**Comment by Dalas121** [comment]
Thanks for testing.  I've uninstalled and reinstalled, and the bug no longer happens for me - I must've messed something up in my installation that caused the crash.  Closing this issue.
