### ISSUE TITLE
Invalid tag in [abilities] is partially succesful

### ISSUE THREAD

**Issue by white-haired-uncle** [wesnoth/wesnoth#8582]
### Game and System Information

- **Version:**  v1.19.0-dev (94b71ac95b2-Clean) x86_64
- **Downloaded from:** git
- **Build info:** g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- **OS:** `Linux spartan 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`  

### Description of the bug

I replaced [heals] with [harm_unit] inside [abilities], which I now understand to be wrong.  [heals] was being used with a negative value to inflict damage, but this worked strangely against poisoned units and a damage_type was requested.

According to https://wiki.wesnoth.org/AbilitiesWML#The_.5Babilities.5D_tag, this should have done nothing.  It actually mostly worked, but the damage_type was ignored.

### Steps to reproduce the behavior

See forum thread link below.

### Expected behavior

Going by the wiki, it should do nothing at all.  But if it's the wiki that's wrong, it should honor damage_type ([harm_unit] does honor damage type when called from turn refresh BTW)

### Additional context

https://forums.wesnoth.org/viewtopic.php?t=57835

I'd actually prefer if [harm_unit] was an acceptable and fully functional tag inside [abilities] than to have it not work at all, but IMO the current state is just not right.

**Comment by soliton-** [comment]
Please provide complete code and reproduction steps. As far as I can tell the forum thread just shows some excerpts.

**Comment by white-haired-uncle** [comment]
Oops.  My bad.

I changed the definition of the ability, but the unit I was testing already had the ability.  It worked because it was still using heals.

Sorry about that.
