### ISSUE TITLE
Elvish Sylph/Enchantress/Sorceress attacks inconsistent with updated description

### ISSUE THREAD

**Issue by babaissarkar** [wesnoth/wesnoth#8583]
### Language

English

### Source

Elvish Sylph/Enchantress/Sorceress' attack `entangle`/`gossamer`.

### Original Text

The new lore for Elvish Sylph added in 1.16 (d4144068fadd48a8a5e4fdb24e8930f8d19e12b4) explains that their ability stems from finding `reflection pools`, points where the corporeal and incorporeal/faerie realms are closer than usual, which they use to draw energy. However, their current attack, `gossamer` does not explicitly utilize this fact and don't show any relation to these pools whatsoever.
Gossamer also mean something very light and weak (https://dictionary.cambridge.org/dictionary/english/gossamer), so how is such an attack able to slow down enemies unless it has some kind of magical/otherworldly properties?

Another point : Since Sorceress lines' ability is connected to the incorporeal/faerie world instead of the physical world (Druid/Shyde line), perhaps the `entangle` needs to be changed too, since commanding vines/creepers requires mastery of the physical line.

### Proposed Change

Rename `gossamer` (Sylph) and `entangle` (Enchantress) to `ethereal web` (or something similar).
This will be able to show that they are becoming more strongly attached to their faerie side, so they use `ethereal web` instead of the physical based `entangle`. Plus `ethereal` also suggests that the power originates outside the corporeal/human world, thus making it more consistent with the lore.
Any name is fine as long as it is consistent.

**Comment by CelticMinstrel** [comment]
> Gossamer also mean something very light and weak (https://dictionary.cambridge.org/dictionary/english/gossamer), so how is such an attack able to slow down enemies unless it has some kind of magical/otherworldly properties?

It's because of the association with spiders, who trap insects in their **gossamer** webbing. Thus in this context I don't think it's correct to interpret it as something delicate (though it's certainly light).

**Comment by babaissarkar** [comment]
> It's because of the association with spiders, who trap insects in their **gossamer** webbing. Thus in this context I don't think it's correct to interpret it as something delicate (though it's certainly light).
That's a valid point, but even if it is very strong, still wouldn't something like *ethereal web* would be more consistent with the new lore? I still have trouble relating it with `reflection pool` (aka something like a magical portal or conjunction).

**Comment by CelticMinstrel** [comment]
I'm not sure what (if anything) reflection pools have to do with her slow ability…

**Comment by babaissarkar** [comment]
> I'm not sure what (if anything) reflection pools have to do with her slow ability…

The point of this issue is to try to connect those two, so that all of the attacks are explained by the lore.
For example, here's the description for the cavalaryman :

> "The more talented cavalrymen in the armies of Wesnoth are trained in the use of the crossbow, and matched with much more powerful steeds. Well-armored, and skilled in the use of their swords, these soldiers can drive forward and hold the ground they take. Their mobility and resilience make them of great value on the battlefield."

It's not very big, but we immediately understand that they can use Crossbow now, and there movement speed and terrain defense/resistance have increased.

If we change the `gossamer` to `ethereal web`, players automatically understand that the origin of their power is outside the real world, as mentioned in the lore. It also clearly distinguishes that there are two paths, Physical (Shyde line) and Faerie (Sorceress line), and they use different magic styles, so naturally their abilities should differ from each other. From this POV, a sorceress using vines to entangle is very weird, she should use a magical net instead. However there are no problems if a Druid/Shyde uses vines to capture the enemy.
(None of these problems arose with the pre 1.16 version, since they never mentioned the specifics of elven magic in such detail.)

**Comment by babaissarkar** [comment]
By contrast, Sorceress' lore clearly explains the Faerie Fire's origin :

> "Elven magic most commonly diverges among two paths — manipulation of the natural, or corporeal world, and divination into the arcane plane. The latter, as a power that is difficult to control and ill-understood even by most of its practitioners, is not often sought after by the Elves. Wielders of the arcane face significant risk in studying the volatile nature of their discipline and quickly learn to respect the disruptive power of their craft. This destructive nature most commonly manifests itself as gouts of ‘faerie fire’, which is among the most readily mastered skills for an Elvish sorceress. While a rather superficial application of this art, the Elves nonetheless hold the arcane flame in high regard and are careful to utilize it with judicious caution."

I originally also wanted this to be changed, at least for the Sylph, but since this already explains the origin of the faerie fire, I had to remove that from this issue.

**Comment by babaissarkar** [comment]
By the same logic, we might also need a new unit for Sorceress line :)
But that would be asking for too much.

**Comment by CelticMinstrel** [comment]
> From this POV, a sorceress using vines to entangle is very weird

Not when you consider that she used to be a shaman – it makes a certain kind of sense for her to retain the shaman's ability when she's transitioning to the path of the Faerie. But if you wanted to rename the attack for the enchantress, then that makes more sense.

**Comment by babaissarkar** [comment]
> Not when you consider that she used to be a shaman – it makes a certain kind of sense for her to retain the shaman's ability when she's transitioning to the path of the Faerie. But if you wanted to rename the attack for the enchantress, then that makes more sense.

Agreed. Changing the Enchantress' and Sylph's attack names would be enough.

**Comment by babaissarkar** [comment]
> It's not clear to me that the "gossamer" is intended to have such an origin. The "faerie fire" clearly is meant to have such an origin, yes; but whether or not the "gossamer" is intended to share the same origin is not clear from the unit description.

Yes, I want to completely clear this confusion. Either by updating the lore, or changing the attack name. The original lore from wesnoth 1.0 mentioned them to be creatures of both world, so in that it would have been fine.

https://github.com/wesnoth/wesnoth/blob/a8045ff78d6be5efae6ca1b46084684f7398a3d1/data/units/Elvish_Sylph.cfg#L21

**Comment by nemaara** [comment]
I like ethereal web or something to that effect more too, but that may break code in addons so I'm not sure it's worth it. Reflection pools is a line that will be useful for mainline campaigns, it doesn't present itself in the actual unit's stats or abilities.

**Comment by CelticMinstrel** [comment]
> that may break code in addons

Should be fine if you only change the `description` key… though that does create a slightly unfortunate situation where the description and name are completely different.

Maybe this is another place where we need to come up with a deprecation strategy…

**Comment by babaissarkar** [comment]
> I like ethereal web or something to that effect more too, but that may break code in addons so I'm not sure it's worth it. 
I agree with @CelticMinstrel here, just changing the description shouldn't break anything. (except for translations, but small change so they should be able to deal with it pretty fast.)

**Comment by CelticMinstrel** [comment]
My campaign definitely adjusts gossamer though, so it's not unheard of.

**Comment by nemaara** [comment]
Addressed by #8737.
