### ISSUE TITLE
(SoF) Outriding the Outriders: problematic difficulty level

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8589]
### Describe the desired feature

I don't like complaining about a scenario being too hard, because I could just play easy mode and some people like more of a challenge than others. That being said: some scenarios work very differently than an average scenario and this is one of them. You start with only 1 unit and only get few, weak units throughout the scenario to buy you time. I put the meatshields in places where they would block the elves yet where they would still have decent terrain defense and that's just about everything you can do in regards to strategy. I found the only way to get through this scenario was by savescumming. This is the kind of scenario where it being more difficult can't really be compensated for with better / creative strategy. I recommend making it a bit easier. If others managed this scenario without savescumming, please do let me know. It's always possible that I just missed a crucial tactical component to this scenario but I can't imagine it.

PS: from what I can tell from the script, this scenario isn't affected by the difficulty setting

As always, love to the team who make this game possible!

**Comment by OrangePumpking** [comment]
Cool, that one point explains everything hahaha

**Comment by Wedge009** [comment]
> ...it was added in [9721ae4](https://github.com/wesnoth/wesnoth/commit/9721ae4d237931c512f5bcdda3923b825a053b78).

I'm not sure I understand the 1.18 label - the cited commit appears to be included in master since at least release 1.17.20, so it would have been included in the current 1.18 branch as well, wouldn't it? ie This is an issue for both master and 1.18 branches, so I don't think the label should apply here.

**Comment by stevecotton** [comment]
Sorry if I've misunderstood how we're handling bugs for the stable branch - I added the label thinking it was highlighting that this needs fixing on master and backporting.

**Comment by cooljeanius** [comment]
> Labelling as a bug because SoF S07 wasn't updated to account for 1.18's Outriders having an extra movement point; it was added in [9721ae4](https://github.com/wesnoth/wesnoth/commit/9721ae4d237931c512f5bcdda3923b825a053b78).

I swear this scenario was a point that came up during the review of @Hejnewar's proposed stat changes; dunno how it managed to slip past without being addressed...

**Comment by Wedge009** [comment]
> Sorry if I've misunderstood how we're handling bugs for the stable branch - I added the label thinking it was highlighting that this needs fixing on master and backporting.

No worries, but AFAIK, things haven't changed - stable labels state they are intended to highlight issues specific to stable branches (ie not present on master). eg I created the 1.18 label when #8401 was resolved for master but not 1.18.

**Comment by Jonathan-Kelly** [comment]
> Labelling as a bug because SoF S07 wasn't updated to account for 1.18's Outriders having an extra movement point; it was added in [9721ae4](https://github.com/wesnoth/wesnoth/commit/9721ae4d237931c512f5bcdda3923b825a053b78).

From testing the scenario side by side in 1.16 and 1.17, I remember the extra movement point made little difference compared to the increased damage power of the new Outrider units. They more often cut down too many of the meat shield units you throw in front of them, which is the main thing stopping them from pinning Alanin.

I suspect deleting one of the initial Outriders and/or removing all of their traits should bring the difficulty level back to where it was in 1.16. If there's no objections I can put this in a PR after a bit more testing.

Also... wow, does this scenario have no difficulty variations or did I miss something in its code?

**Comment by cooljeanius** [comment]
> > Labelling as a bug because SoF S07 wasn't updated to account for 1.18's Outriders having an extra movement point; it was added in [9721ae4](https://github.com/wesnoth/wesnoth/commit/9721ae4d237931c512f5bcdda3923b825a053b78).
> 
> I swear this scenario was a point that came up during the review of @Hejnewar's proposed stat changes; dunno how it managed to slip past without being addressed...

Update: found it: it was something noticed in #7766
