### ISSUE TITLE
(HttT) S02 Isle of the Damned: Delurin has the loyal trait twice

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8592]
### Game and System Information

- **Version: 1.17.26**
- **Downloaded from: Steam**
- **Build info:**
- **OS: Windows 10**

### Description of the bug

The topic title kinda sums it up. In SO2 you encounter a loyal character called Delurin. He has the trait listed twice. No biggie.

**Comment by knyghtmare** [comment]
Seems patched by #8448
