### ISSUE TITLE
Steam version doesn't run on Ubuntu 22.04: missing libraries

### ISSUE THREAD

**Issue by AncientGeneral** [wesnoth/wesnoth#8597]
### Game and System Information

- **Version:** 1.18.0
- **Downloaded from:** Steam
- **Build info:** ?
- **OS:** Ubuntu 22.04

### Description of the bug

Game doesn't start:

```
$ ./start.sh 
./wesnoth: error while loading shared libraries: libicui18n.so.67: cannot open shared object file: No such file or directory
```

There are missing libraries:

```
$ ldd wesnoth | grep not
	libicui18n.so.67 => not found
	libicuuc.so.67 => not found
	libcrypto.so.1.1 => not found
	libssl.so.1.1 => not found
```

In `1.16` steam distribution, there is a directory `lib64` which contains all required libraries, and switching to beta branch `1.16` will run the game. However, in `1.18` steam distribution, directory `lib64` is not exists and required libraries are nowhere to get.

### Steps to reproduce the behavior

1. Install game through Steam on Ubuntu 22.04
2. Try to run it
3. Game doesn't run

### Expected behavior

Game runs

**Comment by loonycyborg** [comment]
1.18 is supposed to be run via steam sniper runtime that provides that icu file.
Does small "i" button in lower left corner of screen show something like this to you?
![изображение](https://github.com/wesnoth/wesnoth/assets/862623/99daa1b7-55bd-4be1-abde-9729817f926c)

Also are you running wesnoth via steam client or directly?

**Comment by AncientGeneral** [comment]
Before update, I used to run game via `start.sh` without enabling a steam client, after update it isn't working. Now I have tried to run game via steam client and it works. So running in a standalone mode is not supported any more?

**Comment by loonycyborg** [comment]
Not sure if it was ever formally supported. Whether it runs is just a matter of how close are your system libs to what steam runtime is using. Newer versions of steam have better support for providing own libraries instead of system's which may be incompatible, so we don't have to provide custom build of icu anymore because it's in steam runtime. Maybe steam has own way of making shortcuts that runs game with correct runtime. If not you can just locate that icu lib and add its dir to LD_LIBRARY_PATH.

**Comment by AncientGeneral** [comment]
I have added `.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-MYRVK2/usr/lib/x86_64-linux-gnu/` and `.local/share/Steam/ubuntu12_64/steam-runtime-sniper/var/tmp-MYRVK2/usr/lib/x86_64-linux-gnu/pulseaudio` to `LD_LIBRARY_PATH` and now game runs even without steam client enabled.
