### ISSUE TITLE
[Units] Giant Ant Egg/Fire Ant Egg: Document behavior that eggs hatch if adjacent eggs die.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#8604]
### Describe the desired feature

Currently, when you kill a Giant Ant Egg/Fire Ant Egg, the adjacent egg react by hatching (advancing) to Giant/Fire Ants. This is NOT communicated to the player in any way. This should be communicated via a special note or dummy ability. If it's not communicated, it's a nasty tomato surprise.

**Comment by knyghtmare** [comment]
I am not saying it's a bad thing. I find the hatching kind of cool. It's just it should be communicated to the player in some way.

**Comment by knyghtmare** [comment]
Nvm, It was there...just as a very tiny obscure bit at the end of the unit description.

**Comment by CelticMinstrel** [comment]
What about adding a reaction whenever you attack an ant/egg adjacent to an egg? Like…

"This egg looks like it's starting to hatch!"

**Comment by knyghtmare** [comment]
> What about adding a reaction whenever you attack an ant/egg adjacent to an egg? Like…
> 
> "This egg looks like it's starting to hatch!"

For one, it's fine but for 4 nearby ones? seeing that message so many times might get a bit annoying. The current thing works, so adding the "starting to hatch" message should be added on the scenario designer's end.

**Comment by CelticMinstrel** [comment]
Maybe only the first time it happens?

**Comment by knyghtmare** [comment]
> Aside from that, a sound effect and/or particle animation every time it happens might be good.

The current animation is advancing. So it's good enough, I guess.
