### ISSUE TITLE
Minimap escapes listbox in multiplayer lobby game list

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#8607]
When scrolling up and down, the minimap displayed in the multiplayer lobby game list will escape the listbox borders and continue being drawn when it shouldn't be:
![image](https://github.com/wesnoth/wesnoth/assets/3030250/9eb353be-014d-4a0a-bd31-3e2a2ccf8d51)

* 0f6da374e06fa50e02d43bb3e06d25b9cfad7e26 is the last good commit.
* For 8efd9d43f2d9ec80c2b0f8040f0656a892f57577 and 9222a11f61165a7658ac373776e24932e70d6589 the minimap isn't showing up at all, so it's not possible to tell if the root cause was introduced in either of these commits.
* 14dbe3143d60b30824cbbb90f475309d8462cb22 is the first commit where this issue can be reproduced.

**Comment by Wedge009** [comment]
Looks like something that was missed for #7657.

**Comment by Wedge009** [comment]
Different context, but looks similar to #7087.

**Comment by Vultraz** [comment]
^ Might fix this, but I need someone to confirm.
