### ISSUE TITLE
The frequency slider for idle animations isn't disabled when the dialog is reopened

### ISSUE THREAD

**Issue by fujimo-t** [wesnoth/wesnoth#8612]
### Game and System Information

- **Version:** 1.18
- **OS:** Fedora Linux 39

### Description of the bug

`Frequency:` slider bottom of `Unit idle animations` toggle button isn't disabled when `Preferences` dialog is opened even if the idle animations was disabled.

### Steps to reproduce the behavior

1. Open `Preferences` from the title screen and go to `Display` tab.
2. Toggle off `Unit idle animations`
3. Close and reopen the dialog and go to the tab.
![idle_animation_slider_not_disabled](https://github.com/wesnoth/wesnoth/assets/10286050/f6a0bcff-531a-44bb-aba9-e1ee544dfb7e)

### Expected behavior

The slider is disabled when the dialog is reopened.

**Comment by Wedge009** [comment]
This is something that was present in 1.16 as well. Contrasting the options where a slider bar is linked to a toggle option:

Unit idle animations:
https://github.com/wesnoth/wesnoth/blob/62ac421cf4363495a60c79028f3b98cc5a3ac664/src/gui/dialogs/preferences_dialog.cpp#L500-L505

Automatic pixel scaling works albeit with the inverted form - the slider is active only when the option is disabled.
https://github.com/wesnoth/wesnoth/blob/62ac421cf4363495a60c79028f3b98cc5a3ac664/src/gui/dialogs/preferences_dialog.cpp#L466-L474

Sound volume is factored into an `initialize_sound_option_group()` function.
https://github.com/wesnoth/wesnoth/blob/62ac421cf4363495a60c79028f3b98cc5a3ac664/src/gui/dialogs/preferences_dialog.cpp#L531-L532
