### ISSUE TITLE
The frequency slider for idle animations loads wrong value when the preferences dialog is opened

### ISSUE THREAD

**Issue by fujimo-t** [wesnoth/wesnoth#8613]
### Game and System Information

- **Version:** 1.18
- **OS:** Fedora Linux 39

### Description of the bug

`Frequency:` slider bottom of `Unit idle animations` can't reflect current value when `Preferences` dialog is opened.

The slider's [value range is `-40` to `30`](https://github.com/wesnoth/wesnoth/blob/2beda25526c01d81b7ce3f88645ea19594c65273/data/gui/window/preferences/03_display.cfg#L349) and it will [convert to double value](https://github.com/wesnoth/wesnoth/blob/2beda25526c01d81b7ce3f88645ea19594c65273/src/preferences/general.cpp#L530) for using.
It seems to load the double value to the slider without reverse conversion when the dialog is opened.

### Steps to reproduce the behavior

1. Open `Preferences` from the title screen and go to `Display` tab.
2. Move `Frequency:` slider for `Unit idle animations` to maximum value. 
3. Close and reopen the dialog and go to the tab.

### Expected behavior

The frequency value is preserved and correctly reflected to the slider when the dialog is opened.

**Comment by kurnevsky** [comment]
After I changed this slider I don't have animations at all - looks like it's broken :)

**Comment by Wedge009** [comment]
This is a regression from 1.16, which stored the frequency value in the `preferences` file as an integer, so there was no conversion. Haven't seen why/where the change to storing as floats was done for 1.17/1.18.

**Comment by Wedge009** [comment]
It appears this was introduced with 1.17.3 in 098c3342d5d10fc881171c509fd71ee0334c0dc5. @Vultraz, your commit message explicitly states idle animation rates use doubles now instead of ints, but it doesn't say why that change was necessary. Can you look into this issue, please?

**Comment by CelticMinstrel** [comment]
I think the problem stems from the fact that both the old and new `set_idle_anim_rate` functions use the formula of 2^(-rate/10) when setting the animation rate. This was correct in the old one but wrong in the new one – what Vultraz missed is that the old `set_idle_anim_rate` function that was using the formula is the function that _loads the value from the prefs_. Thus, the calculation that was supposed to be done to convert the int from the preferences into a double for internal use is now being done when you change your preferences, which is all sorts of wrong.

I think making it a double was a mistake. The integer form means you get a graduated scale of powers of 2, which I think is pretty sufficient for most purposes.

**Comment by Wedge009** [comment]
@Vultraz Back-port to 1.18?

**Comment by Wedge009** [comment]
Back-ported, including the subsequent commentary removal.
