### ISSUE TITLE
Did Acheivement "spoiler" ?

### ISSUE THREAD

**Issue by arosella** [wesnoth/wesnoth#8614]
### Game and System Information

- **1.18**
- **OS: Ininfluent**

### Description of the bug

In the Achievements screen for campaing Did, at the beginning only 4 achievements are present, but the counter at bottom say "0/7" ... spoiler ?
![image](https://github.com/wesnoth/wesnoth/assets/4649401/82aabb7e-4c90-48a8-bcea-5526afb46bbc)
 Should the number at the bottom and items in the list be aligned ?

**Comment by knyghtmare** [comment]
That is intentional. It indicates that there are three more "hidden" achievements you have to look out.

**Comment by arosella** [comment]
Reasonable, but in "Invasion fron East" it is the opposite: all the 22 achievements are available...
![image](https://github.com/wesnoth/wesnoth/assets/4649401/18521db0-164c-47bc-8905-7502c20e0fdb)
Maybe it is presented in such a configuration because each achievement is related to a specific scenario, but it is evident also the presence of an "secret bonus scenario", not really a secret...

![image](https://github.com/wesnoth/wesnoth/assets/4649401/cfa5852e-43e9-42ff-af82-c89a1728bb5f)

**Comment by CelticMinstrel** [comment]
Maybe that last one _should_ have been marked secret and @Dalas121 forgot to? Or maybe he just decided it wasn't worth it.

**Comment by Dalas121** [comment]
No, it's deliberately left unhidden as a hint for players. There's no other indication the hidden scenario exists, so I created that achievement as a tease.

**Comment by arosella** [comment]
Good, so everything is fine. We can safely close the "bug". Thanks for all the clarifications
