### ISSUE TITLE
minor typo - append s

### ISSUE THREAD

**Issue by realsobek** [wesnoth/wesnoth#8615]
### Language

english

### Source

po/wesnoth-help/wesnoth-help.pot#L801

### Original Text

"**This tool create** sets of tiles that can be used in WML scripts’ Standard "

### Proposed Change

"This tool create**s** sets of tiles that can be used in WML scripts’ Standard "

**Comment by Wedge009** [comment]
Source:
https://github.com/wesnoth/wesnoth/blob/2beda25526c01d81b7ce3f88645ea19594c65273/data/core/editor/help.cfg#L286

**Comment by Wedge009** [comment]
Agreed with the change, I take it the string freeze should be over soon-ish. How to update this without triggering complaints?
