### ISSUE TITLE
minor typo - add comma

### ISSUE THREAD

**Issue by realsobek** [wesnoth/wesnoth#8616]
### Language

english

### Source

po/wesnoth-manpages/wesnoth-manpages.pot#L1480

### Original Text

"sets the maximum number of worker threads that will be created.  **If set to "
"B<0> there** will be no limit (default: B<0>)."

### Proposed Change

"sets the maximum number of worker threads that will be created.  If set to "
"B<0>**,** there will be no limit (default: B<0>)."

**Comment by Wedge009** [comment]
Source seems to be here:
https://github.com/wesnoth/wesnoth/blob/2beda25526c01d81b7ce3f88645ea19594c65273/doc/man/wesnothd.6#L82-L88

I agree with the proposition, but I wonder if this is the sort of thing that is going to trigger complaints from certain individuals.
