### ISSUE TITLE
Problem in MatchHistory if side number differs from number of map starting positions

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#8619]
This is displayed in the match history about a 3p - Colosseum game.
The map file has starting positions for 8 sides. However, in the [side] tag starting positions are overridden by explicitly giving `x,y=`, and the scenario defines only 5 [side]s.
Sides 2-4 are for players, one side was left empty which is excluded form the list below.

The Problem here is that the sides are listed twice.
Maybe Computer 1+5 should be excluded too.
![bug](https://github.com/wesnoth/wesnoth/assets/21158813/38dc5120-f256-428d-82ba-d6ac3d68189a)

**Comment by Pentarctagon** [comment]
Can you link to the public replay of the game? That has the game ID in the file name so I can take a look if it's a data issue or a query issue.

**Comment by sevu** [comment]
This one:
https://replays.wesnoth.org/1.18/2024/03/24/3p__Colosseum_Turn_14_(1508).bz2
