### ISSUE TITLE
EI S10: "ghasts in cages"

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8620]
### Language

en_US

### Source

EI S10

### Original Text

"Look, a key! But it’s guarded by all those goblins... and there are ghasts in cages!"

There aren't any L3 ghasts, just L1 ghouls and L2 necrophages; 6 in total, with 0-2 of them being necrophages depending on difficulty. However, I think "ghouls" would fit better even if some of them were ghasts - the speaker is looking through a door to see what's in the room, and as a non-necromancer probably doesn't want to know the difference between ghouls and ghasts.

### Proposed Change

"ghouls in cages"

**Comment by Dalas121** [comment]
Works for me.  They used to be ghasts in an earlier iteration, but got nerfed down to their current form.

#8645
