### ISSUE TITLE
Wesnoth 1.16.12 release fails to start

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#8626]
### Game and System Information

- **Version:** 1.16.12 (official Windows release)
- **OS:** Windows 7/10

### Description of the bug

Wesnoth 1.16.12 fails to start, with the following message in the logs:
```
WML exception:
User message: Window not defined in WML: 'faction_select'.Perhaps a mismatch between data and source versions. Try --data-dir <trunk-dir>
Dev message: Condition 'window_types.find(window_type) != window_types.end()' failed at /wesnoth/src/gui/core/gui_definition.cpp:113 in function 'gui_definition'.
```

Confirming 1.16.11 release starts as normal.

### Steps to reproduce the behavior

Run Wesnoth 1.16.12

### Expected behavior

Wesnoth reaches main menu screen as normal.

### Additional context

Only reason I was checking 1.16 release was to see if some bug reports exist in 1.16 or are regressions from it.

**Comment by Wedge009** [comment]
Is it worth expending effort to resolve this? On the one hand, 1.18.0 has just been released, but on the other, it seems a bit sad that the final point release for 1.16 is broken.

Assuming, of course, this is an actual problem and not something specific to my set-up.

**Comment by Discontinuum** [comment]
I noticed 1.16.12 is in macOS App Store, if it won't start it would be very sad

**Comment by Pentarctagon** [comment]
Is this on Steam or elsewhere?

**Comment by Wedge009** [comment]
So far, only found it with SourceForge Windows release for 1.16.12. Yes, I just checked self-compiled 1.16 branch on Linux and it works.

**Comment by Wedge009** [comment]
Occurs with same SourceForge Windows release on Windows 10 as well.

**Comment by Wedge009** [comment]
`faction_select` is defined for tag 1.16.12:
https://github.com/wesnoth/wesnoth/blob/38dd04639887c1dc50429423c800177c92ce7d21/data/gui/window/mp_faction_select.cfg#L242-L394

I checked the corresponding file in the Windows installation and it is present there too...

**Comment by Pentarctagon** [comment]
If you download the Source-And-Windows-Installer from https://github.com/wesnoth/wesnoth/actions/runs/8320075439 and install that, does the same issue happen?

**Comment by Wedge009** [comment]
That took a while to download... I checked the SHA-256 hash and it differs from what's downloaded from SourceForge. It still results in the same error, however.

I'm still waiting for 1.16 branch to compile on Windows - as usual, vcpkg takes a long time to rebuild everything... even if it's been built before.

**Comment by Wedge009** [comment]
Self-compiled 1.16 branch on Windows works fine as well. So at this point I can only conclude there's an issue with the official Windows build for some reason.

**Comment by loonycyborg** [comment]
Installer with checksum b32fc7ac4a6be8cd69a649b5ee80e98f237f56e3 seems to be working fine for me locally

**Comment by Wedge009** [comment]
Which one is that?

**Comment by loonycyborg** [comment]
1.16.12 installer uploaded to sourceforge.

**Comment by loonycyborg** [comment]
hmm seems it works only under wine, and not in my win10 vm

**Comment by Wedge009** [comment]
The one I downloaded from SourceForge previously is time-stamped 2024-03-18 02:31 UTC. Its file size is 432 MiB (slightly smaller than 1.16.11 release) and SHA-256 hash is c2d70704d16a6e5d053ea6a788ee821dd1ae700cd09d84039d27204499d9a12d.

Looking at SourceForge again at time of writing I see a new installer updated '< 30 minutes ago'. It has a file size of 438 MiB (same as 1.16.11 release) and its SHA-256 hash is 6e465b86fb59089170f68cb9ba8dbc4fd6b72d3e677c3fb0be28b5f7e7442e47.

Installing this new upload, it seems to work. I'm guessing 'not in my win10 vm' must be some other issue.

**Comment by loonycyborg** [comment]
ye I rebuilt and reuploaded it. Was trying it in my win10 vm but you beat me to it. That vm is slooooooow.

**Comment by loonycyborg** [comment]
No idea why corrupted one worked in wine.
