### ISSUE TITLE
EI: Barrow Wight Resistance to Arcane On Defence Ability Doesn't Work Against Mixed Damage Type Weapons

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8631]
### Game and System Information

- **Version:** 1.18
- **OS:** ChromeOS/Debian

### Description of the bug

The Barrow Wight has the Shroud Ability: "When defending, this unit has 50% Fire and Arcane resistance." This ability works under normal circumstances.

The EI campaign provides some items that give units the Arcane damage type in addition to their original damage type e.g. Pierce, Arcane. 

If the attack's original damage type isn't Fire or Arcane, the Shroud Ability fails to trigger. The Barrow Wight takes massive Arcane damage (50% weakness) when defending against such attacks.

### Steps to reproduce the behavior

Give a unit with non-Fire and non-Arcane attacks a Holy Amulet item.
Unit deals high Arcane damage to the Barrow Wight when attacking because the Shroud Ability doesn't trigger.

### Additional context

The Barrow Wight appears in 14_The_Drowned_Plains.

**Comment by newfrenchy83** [comment]
is it really the arcane type that inflicts the damage or the associated type that is not halved?

**Comment by IskarJarak01** [comment]
![image](https://github.com/wesnoth/wesnoth/assets/81496259/a8967c1e-126d-41f2-8126-db95a37618e7)
It's definitely the Arcane. (The Barrow Wight has a 20% resistance to pierce.)

**Comment by newfrenchy83** [comment]
> ![image](https://private-user-images.githubusercontent.com/81496259/316974393-a8967c1e-126d-41f2-8126-db95a37618e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NzQ0MDEsIm5iZiI6MTcxMTQ3NDEwMSwicGF0aCI6Ii84MTQ5NjI1OS8zMTY5NzQzOTMtYTg5NjdjMWUtMTI2ZC00MWYyLTgxMjYtZGI5NWEzNzYxOGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE3MjgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYjkxZDNhMzBhZjc0ZDdmNGU2YThkYzUwNjBlM2MxNDU1OThiZjZjMjEyZTJhNmJiZmJjZDM2NjU0OWZhNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.01WUnRD1-SCUy5sYlhWhiSMQzDvY6NTiP5BST8aeuOI) It's definitely the Arcane. (The Barrow Wight has a 20% resistance to pierce.)

i work on the bug

**Comment by newfrenchy83** [comment]
added a PR for fix this.

**Comment by stevecotton** [comment]
While this is a single-player bug, I'm also wondering about the effect on multiplayer.

For 1.18.x, I think we should say that mixed-damage type weapons aren't supported in multiplayer, because they're likely to change a bit and therefore cause OOS between different versions of 1.18.

**Comment by stevecotton** [comment]
There will be different fixes for the stable and development branches. The stable fix is in #8640.
