### ISSUE TITLE
EI: Units With the Survivor Trait Take 1 Damage When an Undead Attack is Redirected to the Shield of the Sentinel Bearer

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8632]
### Game and System Information

- **Version:** 1.18
- **OS:** Debian/ChromeOS

### Description of the bug

The Shield of the Sentinel item has the effect: "Whenever an adjacent ally is hit by an attack, this shield's bearer is hit instead."

The Survivor trait reduces damage recieved from undead, bats and necromancers by 1.

When the Survivor trait would trigger and reduce damage, it instead causes the unit to take 1 damage and the full attack is redirected to the Shield of the Sentinel bearer.

If the trait isn't active/applied, the unit takes 0 damage.

### Steps to reproduce the behavior

Give a unit the Shield of the Sentinel (item is in 08_Xenophobia, trait is "TRAIT_sentinel").
Hit a Survivor unit protected by the Shield of the Sentinel with an Undead unit.

**Comment by Dalas121** [comment]
Most likely related to #8633, and I propose the same solution.

**Comment by Dalas121** [comment]
Bugfix PR opened: #8667
