### ISSUE TITLE
Wrong trait page opened for units with nameless traits

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#8635]
### Game and System Information

**Version 1.18.0**

### Description of the bug

If the 1st trait of a unit has no name, then clicking on the units (other) trait in the sidebar opens the wrong page in the help

### Steps to reproduce the behavior

```
[unit]
    type=General
    x,y=11,8
    side=5
    [modifications]
        {TRAIT_STRONG}
        [+trait]
            male_name=""
        [/trait]
    [/modifications]
[/unit]
```

### Expected behavior

The trait without name is not displayed, but clicking on the units other, displayed trait in the sidebar will open the correct page in the help.

**Comment by stevecotton** [comment]
Reproducible on the tutorial's Delfador :grimacing:
