### ISSUE TITLE
Update OpenSSL for Linux releases

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#8641]
### Describe the desired feature

Per notes from [OpenSSL site](https://openssl.org/source/):
> All older versions (including 1.1.1, 1.1.0, 1.0.2, 1.0.0 and 0.9.8) are now out of support and **should not be used**. Users of these older versions are encouraged to upgrade to 3.2 or 3.0 as soon as possible.

Windows (Steam) release for 1.18.0 (current stable at time of writing), I observe the packaged OpenSSL is 3.1. Similarly MSVC-compilation using `vcpkg` uses OpenSSL 3.1 (and `vcpkg` has OpenSSL 3.2 available). Ubuntu-based distributions (which I use) have OpenSSL 3.0 available, and self-compiled Wesnoth uses that. However, the Linux Steam release for 1.18.0 is still using Open SSL 1.1.1 (is this related to #8578? are we limited to what is available via Steam run-time?).

I don't know what Flatpak-packaged Wesnoth uses (would it be dependent on what OpenSSL the host OS has available?), nor the macOS release.

**Comment by Pentarctagon** [comment]
It's what the steam runtime comes with. You can check the version of `libssl` `manifest.dpkg` of the sniper runtimes at https://repo.steampowered.com/steamrt-images-sniper/snapshots/, for example https://repo.steampowered.com/steamrt-images-sniper/snapshots/0.20240307.80401/com.valvesoftware.SteamRuntime.Platform-amd64%2Ci386-sniper.manifest.dpkg

**Comment by Wedge009** [comment]
Oh right. So it's out of our hands, then? To this day, I still have no idea of the meaning behind the (Team Fortress based) names for the Steam run-times, ie which one is supposed to be newer/older, or if one is supposed to be used in one scenario over another...

Regardless, looking through the 'latest' package lists for each of the four characters, it looks like nothing is available later than 1.1.1. I had a quick look through the Steam run-time issues but there doesn't appear to be anything related to OpenSSL so maybe people aren't that concerned.

I presume this is a limitation of the Steam release and so Flatpak releases aren't affected? If so, we can probably close/leave this as something beyond our control.

**Comment by Pentarctagon** [comment]
Yeah, it's beyond our control.
