### ISSUE TITLE
Cannot pass SDL2_WEBP_SUPPORT

### ISSUE THREAD

**Issue by iFoundSilentHouse** [wesnoth/wesnoth#8642]
Architecture: x86_64/i686 & -musl/no musl
Hi. I'm porting wesnoth to Void linux. Build is fine and every test passed except the one for webp support. I'm building with xbps-src with last version of sdl2_image built with default options (https://github.com/void-linux/void-packages/blob/78806724a79bf2bc6b8fba399da0b6bdabe9e9d7/srcpkgs/SDL2_image/template#L4).
Maybe my patch destroys everything but my knowledge of C++ says that it doesn't https://github.com/wesnoth/wesnoth/pull/8628
I did a lot work updating our lovely game for Void and now I do need your advice.

**Comment by Pentarctagon** [comment]
It could be that sdl2_image was compiled without webp support? It happened by accident to Flatpak at one point: #8040

**Comment by iFoundSilentHouse** [comment]
> It could be that sdl2_image wasn't compiled without webp support? It happened by accident to Flatpak at one point: #8040

https://gitlab.com/search?search=Webp&nav_source=navbar&project_id=4339844&group_id=2054538&search_code=true&repository_ref=2c61f4cbb865b868c5db67787935525f82eaabbf
It doesn't look like that. Libwebp is fresh and it was built with flags from commit ^ 
https://github.com/void-linux/void-packages/blob/78806724a79bf2bc6b8fba399da0b6bdabe9e9d7/srcpkgs/libwebp/template#L6

**Comment by iFoundSilentHouse** [comment]
But it looks like custom sdl2_image should be built with this flags: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commit/2cf3b3c62d8b85cbe57ccd3569b3daa516eff68a 
```
    -DSDL2IMAGE_DEPS_SHARED:BOOL=OFF
    -DSDL2IMAGE_TIF:BOOL=ON
    -DSDL2IMAGE_WEBP:BOOL=ON
```
I'll give it a try

**Comment by iFoundSilentHouse** [comment]
Didn't work. It was already building ```CMakeFiles/SDL2_image.dir/src/IMG_webp.c.o```

**Comment by soliton-** [comment]
I can't really tell what build command you're running and what exactly the output is.

**Comment by iFoundSilentHouse** [comment]
@Wedge009 it's not an actual bug. Just a building complications. What I was able to find out:
1) I see no way to enable webp support keeping dynamic linking except patching CMakeLists.txt file directly. More precisely, line
```option(SDL2IMAGE_WEBP "Support loading WEBP images" OFF)```
2) You should really think well about last test - audio support. I had to build it within virtual environment and, obviously, it has no audio cards. Maybe adding virtual audio loop device would be a nice option. As for me, I just had to disable it.

**Comment by Wedge009** [comment]
No worries, issues are generally categorised as bugs or enhancements. Bugs can be considered unexpected behaviour and I don't think this could be considered an enhancement request. Unless you want to phrase it as a request to adapt the build configurations for something beyond Wesnoth's conventions.
