### ISSUE TITLE
Messages in moveto events sometimes get cleared immediately

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8644]
### Game and System Information

- **Version:** 1.18.0+dev (built from 72a102ccd427caede35038bed4cd6ebebc23b29a)
- **OS:** Linux

### Description of the bug

When moving by clicking on a unit and then clicking on a target hex which triggers a `moveto` event with `message`s, the first message sometimes flashes on screen and disappears without time to read it.

### Steps to reproduce the behavior

1. Start the tutorial
2. Select your character
3. Click on your character
4. Click on a hex next to Delfador
5. See that the displayed message is Delfador's "Um, well..." instead of the player character's "Good morning, Delfador! Is it time to attack things?"

### Additional context

If you're wondering "how else can a unit move?", the answer is that you can drag-and-drop them.

**Comment by gfgtdf** [comment]
im pretty sure that this has happend to me too (and im surprised that there was no report for this before), probably easier to reproduce with a high "accelerate moves" factor. My guess is that the moveup event from the mouse action that  triggers the move then discard the [message]

**Comment by Pentarctagon** [comment]
I saw it mentioned a couple times, but never with much information. Glad to see there's steps for reproduction now.

**Comment by stevecotton** [comment]
I'm trying to bisect, but I can't get it to happen consistently. I think 1.17.20 is good, but even that might need a retest.

**Comment by Wedge009** [comment]
Is the key word 'sometimes'? I just tried this (it seems like standard player actions to me) and Konrad/Lisar's greeting showed as normal.

**Comment by knyghtmare** [comment]
This happens to me a lot. 
This happens cause I click really fast so sometimes two clicks pop for 1. so first click initiates the moveto and the second one passes the first message dialogue since I did click it.

**Comment by stevecotton** [comment]
Went through a phase of it happening every time, but the more effort I make to try and work out the right timing, the more intermittent it seems to become. I'm sure I'm only clicking once on the end hex though.

**Comment by Pentarctagon** [comment]
I've tried reproducing multiple times with the steps above, but haven't been able to so far. Using the Steam Linux release of 1.18.0.

**Comment by stevecotton** [comment]
I saw it less than 10% of the time when trying to trigger it, even on a debug build (where there's probably a longer time to trigger it). #8717 explains where the race condition is.

**Comment by Wedge009** [comment]
Oh, but it sounds like you found it, at least.
