### ISSUE TITLE
Some icons load earlier than the rest of the interface

### ISSUE THREAD

**Issue by amakriLexa04** [wesnoth/wesnoth#8648]
### Game and System Information

- **Version:** 1.18
- **OS:** Windows 10

### Description of the bug

the bug is demonstrated in this video
https://github.com/wesnoth/wesnoth/assets/165188749/dccf3644-3570-4412-9127-08366cf4cb49

### Steps to reproduce the behavior

1. Just load turn

**Comment by Wedge009** [comment]
Looks like a recurrence of #6922. Odd.

**Comment by Wedge009** [comment]
#7997 (which closed #6922) was included from 1.17.23.

It looks like this regression was re-introduced with f79b38a1af0f317a4b5882f7c66f9e3bef6927bf, from 1.17.26. @Vultraz?

**Comment by Wedge009** [comment]
Assuming 4472867992e9ebe664b71d0d700a9df30f4431da actually resolves the issue, it needs to be back-ported because this affects 1.18 as well. I'll try to test this when I'm home.

**Comment by Wedge009** [comment]
Back-ported in 28310a40061d2c6a7066c01219617ae8a146c135. As a player-visible issue, I think this is worth recording in the change log.
