### ISSUE TITLE
Strange messages in The Rise of Wesnoth

### ISSUE THREAD

**Issue by amakriLexa04** [wesnoth/wesnoth#8661]
### Game and System Information

- **Version:** 1.18
- **OS:** Windows 10

### Description of the bug

Dialog boxes appear on the screen with text that is not in the .po translation files and that clearly contains technical information that should not be available to the player
![Знімок екрана (149)](https://github.com/wesnoth/wesnoth/assets/165188749/2b9d1df4-0e3b-40f7-b685-aa31150d6a7b)
![Знімок екрана (150)](https://github.com/wesnoth/wesnoth/assets/165188749/86b9e40a-2695-4fda-8065-1892e6725fc1)
![Знімок екрана (151)](https://github.com/wesnoth/wesnoth/assets/165188749/a4b3b52a-3306-4454-86c6-8a5cef7b1eec)
![Знімок екрана (152)](https://github.com/wesnoth/wesnoth/assets/165188749/a63d4319-e46c-4fb0-8708-257138e54550)

### Steps to reproduce the behavior

1. Load 19_The_Vanguard
2. Kill the enemy leader
and
1. Load 22_The_Rise_of_Wesnoth
2. Wait a few turns

**Comment by amakriLexa04** [comment]
> They are not available for players indeed. You asked for them by enabling debug.

Oh, thank you for the explanation, I was already thinking that something was wrong or that I would need to revise my translation

**Comment by stevecotton** [comment]
Looks like a bug IMO.

Although this says that it's meant to be be overridden in production, I don't see any other definition of `DEBUG_MSG`. And I've just tested (by adding a DEBUG_MSG to the tutorial), and the message shows up in a release build (of a +dev version), without enabling `:debug` first.
https://github.com/wesnoth/wesnoth/blob/b313270261dc75a1ed9ec14032b3b8dff068e3b2/data/core/macros/debug-utils.cfg#L4-L12
