### ISSUE TITLE
Way too many guards

### ISSUE THREAD

**Issue by RogueKorin** [wesnoth/wesnoth#8663]
### Game and System Information

- **Version:**1.18.0
- **OS:**Windows 10

### Description of the bug

Basically when a unit gets too close to the guards they spawn reinforcements, although if something like let's say a bat comes from above and attacks a guard it can trigger two guards, therefore spawning way too many guards,
![image](https://github.com/wesnoth/wesnoth/assets/165406159/04795493-88c8-4e44-bcf2-91105ff7d5ac)

### Steps to reproduce the behavior

1- Debug.
2 - Spawn a unit next to two guards, then attacking one.

### Expected behavior

Average amount of units, no double triggering.

**Comment by RogueKorin** [comment]
note: the bat attacked on 6.24, and it was actually 3 guards.

**Comment by knyghtmare** [comment]
This is intended. Like you are **not** supposed to attack Li'sar in this scenario. 
The guards spawn even more guards so that you can get that detail in that you are not meant to attack this side.
