### ISSUE TITLE
EI: Dacyn's Illuminate Visual Is Not Hidden at the Start of S12_Evacuation

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8675]
### Game and System Information

- **Version:**1.18
- **OS:**ChromeOS/Debian

### Description of the bug

Dialogue implies that Dacyn's illuminate effect should be hidden.
![Screenshot 2024-04-02 00 56 45](https://github.com/wesnoth/wesnoth/assets/81496259/df4489c1-fca0-4e8c-94bd-4aa7e1af958d)

### Additional context

Youtube [video](https://youtu.be/j0mxZrPBUFM?feature=shared&t=2966) of an older version where the illuminate effects is hidden as per the dialogue.

The Illuminate Halo's flickering effect plays correctly.

**Comment by Wedge009** [comment]
Is there a flickering effect intended? Reading the dialogue previously (I've yet to play the revised campaign), I thought it was more a reference to the morally-questionable path Dacyn appears to be taking rather than something necessarily directly connected to game-play.

@Dalas121?

**Comment by Dalas121** [comment]
#8676

**Comment by Wedge009** [comment]
Oops, okay, I see you're already on it!

**Comment by Dalas121** [comment]
Just barely! You commented at almost the exact moment I created the PR.
