### ISSUE TITLE
Review the translatable strings in the unit editor

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#8677]
This is logged as a reminder to do it before 1.19's eventual string freeze, probably 18-30 months from now; however I'm assuming there may be other changes before then.

Many of the strings in `editor_edit_unit.cfg` are only understandable in context, and so need PO hints.

Some of them might be mergeable with text from other areas, for example from the help brower's strings.

Some filenames have been marked translatable, for example
```
[widget]
	id = "tab_image"
	label = _ "/data/core/images/attacks/rectangular-shield.png"
[/widget]
```

**Comment by Wedge009** [comment]
I did wonder about some of the strings, but once I realised they were from a new Unit Editor feature it made sense. 

The only one that stuck out to me was move type rendered as 'Movetype', but I assumed it was 'acceptable' in en_US.

For reference this is the file concerned: https://github.com/wesnoth/wesnoth/blob/master/data/gui/window/editor_edit_unit.cfg

**Comment by CelticMinstrel** [comment]
> The only one that stuck out to me was move type rendered as 'Movetype', but I assumed it was 'acceptable' in en_US.

Rather than "acceptable", I'd say that's just a peculiar Wesnoth idiom?
