### ISSUE TITLE
Add official support for Ukrainian language inside the game

### ISSUE THREAD

**Issue by amakriLexa04** [wesnoth/wesnoth#8685]
### Describe the desired feature

There is no Ukrainian language in the selection menu, although translation exists. It is only possible to choose, when Ukrainian language is set as the system language. Could you please make it so that it appears alongside all other languages, regardless of the system language?

**Comment by stevecotton** [comment]
It's automatically set by translation percentage, languages show up if they have 80% of the strings in from the "core" textdomains listed below. As Ukrainian is already on 75%, I'm guessing you may have already sent Ivanovic the files that will get it to 80%.

* wesnoth
* -lib
* -editor
* -help
* -units
* -multiplayer
* -tutorial

wesnoth-anl isn't in that set, even though gettext.wesnoth.org says that it is
