### ISSUE TITLE
A name for the new +10% ability of the elvish champion

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8706]
### Describe the desired feature

The Elvish Champion unit recently (I think in 1.17 onwards, maybe earlier?) got an ability that allows it to always have 10% more chance to hit the opponent than the terrain defense would indicate. Similar abilities that affect the chance (%) that a unit will hit on an attack (such as magical or marksman) have a name, so just having the +10% chance to hit feels a bit unpolished.

Here are some simple suggestions: Martial Skill, Honed Blade, True Strike, Focus Slash, Quick Draw

**Comment by Hejnewar** [comment]
That is not an ability, it is a base statistic that every unit has just usually set to 0 and only appears if set to higher or lower than 0. In game it is called accuracy.

**Comment by OrangePumpking** [comment]
Then perhaps it could be shifted into an ability instead? I just feel like it being the only unit in the game (to my knowledge) to have this base statistic changed feels a bit ... offkey?

**Comment by ProditorMagnus** [comment]
@Hejnewar you can add it to Elvish Champion special notes.

**Comment by knyghtmare** [comment]
> No. Because that would cause people to be dont do anything about it again instead fixing it.

I agree. The Sidebar UI has to be enhance to communicate the Accuracy and parry values better.

**Comment by Wedge009** [comment]
#2517
#5860

**Comment by cooljeanius** [comment]
#9557 would "fix" this by just removing the accuracy bonus.
