### ISSUE TITLE
There is a problem with the verification of extension versions in the multiplayer lobby

### ISSUE THREAD

**Issue by alauzon** [wesnoth/wesnoth#8710]
### Game and System Information

- **Version:1.18
- **OS:Ubuntu 24.04

### Description of the bug

When I try to join a Dimaga Beach game having some extensions like Reign of the Lords and ageless eras. Translated from french, the message says "There is a problem with the verification of extension versions in the multiplayer lobby".
The user that started the game is Linux and he is using Fedora 39. host

### Steps to reproduce the behavior

1. Click on join the Dimaga Beach game then the error message appears,

### Expected behavior

No error message, game starts.

### Additional context

I am using Steam and the host not.

**Comment by guoshimin57** [comment]
I am the host player. I comiple wesnoth 1.18 with cmake natively.

**Comment by ProditorMagnus** [comment]
It would help to locate which of the 3 addons causes issue, or if it needs specific combination of them.

**Comment by Pentarctagon** [comment]
Logs would also potentially help.

**Comment by alauzon** [comment]
> Logs would also potentially help.

How can I extract the logs? I went to the logs directory but the last logs file dates March 23.

**Comment by Pentarctagon** [comment]
It sounds like you're probably looking at the 1.16 logs directory rather than the 1.18 logs directory.

**Comment by alauzon** [comment]
> It sounds like you're probably looking at the 1.16 logs directory rather than the 1.18 logs directory.

Nope: /home/user/.var/app/com.valvesoftware.Steam/.local/share/wesnoth/1.18/logs

**Comment by Pentarctagon** [comment]
And that's the logs folder pointed to by the build info dialog (little "i" button on the lower left corner of the main menu)?

**Comment by alauzon** [comment]
> And that's the logs folder pointed to by the build info dialog (little "i" button on the lower left corner of the main menu)?

I will check after this game.

**Comment by alauzon** [comment]
Do you also need the host logs?

**Comment by Pentarctagon** [comment]
It can't hurt, but those probably won't have anything useful in them.

**Comment by alauzon** [comment]
Ok, it's under /home/alain/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/599390/pfx/drive_c/users/steamuser/Documents/My Games/Wesnoth1.18/logs

**Comment by alauzon** [comment]
Battle for Wesnoth v1.18.0 x86_64
Started on Sun Apr 07 16:03:32 2024

Automatically found a possible data directory at: Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth

Data directory:               Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth
User configuration directory: C:\users\USER\Documents\My Games\Wesnoth1.18
User data directory:          C:\users\USER\Documents\My Games\Wesnoth1.18
Cache directory:              C:\users\USER\Documents\My Games\Wesnoth1.18\cache


Setting mode to 2522x1043
Checking lua scripts... ok
20240407 16:03:53 error general: Il y a un problème avec la vérification des versions d'extension au niveau du vestibule multijoueur. Merci de le signaler sur https://bugs.wesnoth.org.
20240407 16:04:59 error general: Il y a un problème avec la vérification des versions d'extension au niveau du vestibule multijoueur. Merci de le signaler sur https://bugs.wesnoth.org.
20240407 16:07:51 error gui/layout: grid [] place: Failed to place a grid, we have (0,853) space but we need (305,30) space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui210addon_listE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui25panelE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui27dialogs13addon_managerE' with the id 'addon_manager'.
20240407 16:07:52 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Reign_of_the_Lords/images/attacks/ink.png' and 'Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth/data/core/images/attacks/ink.png'
20240407 16:07:52 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Reign_of_the_Lords/images/projectiles/fire-burst-small-4.png' and 'Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth/data/core/images/projectiles/fire-burst-small-4.png'
20240407 16:07:52 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Reign_of_the_Lords/images/projectiles/whitemissile-impact-2.png' and 'Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth/data/core/images/projectiles/whitemissile-impact-2.png'
20240407 16:07:52 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/War_of_Legends/images/icons/amla-default.png' and 'Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth/data/core/images/icons/amla-default.png'
20240407 16:07:52 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Eternal_Era/images/attacks/staff-ruby.png' and 'Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth/data/core/images/attacks/staff-ruby.png'
20240407 16:07:52 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Reign_of_the_Lords/images/attacks/magic-missile.png' and 'Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth/data/core/images/attacks/magic-missile.png'
20240407 16:07:53 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Reign_of_the_Lords/images/attacks/lightning.png' and 'Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth/data/core/images/attacks/lightning.png'
20240407 16:07:53 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Reign_of_the_Lords/images/attacks/greatsword-human.png' and 'Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth/data/core/images/attacks/greatsword-human.png'
20240407 16:07:53 error addons-client: add-on 'combat-info-theme' doesn't have an icon path set
20240407 16:07:53 error addons-client: add-on 'pay_to_restart' doesn't have an icon path set
20240407 16:07:53 error gui/general: vertical_scrollbar [_vertical_scrollbar] recalculate: Can't recalculate size, force a window layout phase.
20240407 16:07:53 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Reign_of_the_Lords/images/attacks/greatsword-human.png' and 'Z:\home\alain\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\wesnoth/data/core/images/attacks/greatsword-human.png'
libpng warning: iCCP: known incorrect sRGB profile
20240407 16:10:27 error general: Il y a un problème avec la vérification des versions d'extension au niveau du vestibule multijoueur. Merci de le signaler sur https://bugs.wesnoth.org.
20240407 16:12:57 error general: Il y a un problème avec la vérification des versions d'extension au niveau du vestibule multijoueur. Merci de le signaler sur https://bugs.wesnoth.org.
20240407 16:13:52 error general: Il y a un problème avec la vérification des versions d'extension au niveau du vestibule multijoueur. Merci de le signaler sur https://bugs.wesnoth.org.
20240407 16:22:32 error general: Il y a un problème avec la vérification des versions d'extension au niveau du vestibule multijoueur. Merci de le signaler sur https://bugs.wesnoth.org.
20240407 16:24:18 error gui/layout: grid [] place: Failed to place a grid, we have (0,853) space but we need (305,30) space. This happened at a grid with the id '' in a 'N4gui27listboxE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui210addon_listE' with the id 'addons' in a 'N4gui24gridE' with the id '' in a 'N4gui25panelE' with the id '' in a 'N4gui24gridE' with the id '_window_content_grid' in a 'N4gui24gridE' with the id '_content_grid' in a 'N4gui215scrollbar_panelE' with the id '' in a 'N4gui24gridE' with the id '' in a 'N4gui27dialogs13addon_managerE' with the id 'addon_manager'.
20240407 16:24:20 error addons-client: add-on 'combat-info-theme' doesn't have an icon path set
20240407 16:24:20 error addons-client: add-on 'pay_to_restart' doesn't have an icon path set
20240407 16:24:21 error gui/general: vertical_scrollbar [_vertical_scrollbar] recalculate: Can't recalculate size, force a window layout phase.
20240407 16:24:41 error addons-client: add-on 'combat-info-theme' doesn't have an icon path set
20240407 16:24:41 error addons-client: add-on 'pay_to_restart' doesn't have an icon path set
20240407 16:24:46 error deprecation: SPECIAL_NOTES a été déprécié et supprimé.; Use [special_note]note= tags and special_note= attributes instead.
20240407 16:24:46 error deprecation: SPECIAL_NOTES a été déprécié et supprimé.; Use [special_note]note= tags and special_note= attributes instead.
20240407 16:24:46 error deprecation: SPECIAL_NOTES a été déprécié et supprimé.; Use [special_note]note= tags and special_note= attributes instead.
20240407 16:24:46 error deprecation: SPECIAL_NOTES a été déprécié et supprimé.; Use [special_note]note= tags and special_note= attributes instead.
20240407 16:24:51 warning preprocessor: Redefining macro AURA_HALO without explicit #undef at ~add-ons/Ageless_Era/data/EoC_data/animation_utils.cfg:196
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:9
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/anim_macros/anim_macros-EoS.cfg:170
    included from ~add-ons/Ageless_Era/_main.cfg:87
20240407 16:24:51 warning preprocessor: Redefining macro HALF-ANIMATED_BOW_ANIMATION without explicit #undef at ~add-ons/Ageless_Era/data/EoC_data/animation_utils.cfg:243
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:9
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/anim_macros/anim_macros-EoS.cfg:294
    included from ~add-ons/Ageless_Era/_main.cfg:87
20240407 16:24:51 warning preprocessor: Redefining macro MISSILE_FRAME_RAVAGE without explicit #undef at ~add-ons/Ageless_Era/data/EoC_data/animation_utils.cfg:363
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:9
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/anim_macros/anim_macros.cfg:5
    included from ~add-ons/Ageless_Era/_main.cfg:87
20240407 16:24:51 warning preprocessor: Redefining macro MISSILE_FRAME_WATER_SPRAY without explicit #undef at ~add-ons/Ageless_Era/data/EoC_data/animation_utils.cfg:435
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:9
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/anim_macros/anim_macros-EoS.cfg:51
    included from ~add-ons/Ageless_Era/_main.cfg:87
20240407 16:24:51 warning preprocessor: Redefining macro ABILITY_AE_MAG_CAVEAMBUSH without explicit #undef at ~add-ons/Ageless_Era/data/general_data/abilities/cave_ambush.cfg:30
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/general_data/_data.cfg:3
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:17
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/data/EoMa_data/ambush.cfg:51
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:11
    included from ~add-ons/Ageless_Era/_main.cfg:89
20240407 16:24:51 warning preprocessor: Redefining macro ABILITY_AE_MAG_MOUNTAINAMBUSH without explicit #undef at ~add-ons/Ageless_Era/data/general_data/abilities/mountain_ambush.cfg:5
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/general_data/_data.cfg:3
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:17
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/data/EoMa_data/ambush.cfg:2
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:11
    included from ~add-ons/Ageless_Era/_main.cfg:89
20240407 16:24:51 warning preprocessor: Redefining macro ABILITY_AE_MAG_SWAMPAMBUSH without explicit #undef at ~add-ons/Ageless_Era/data/general_data/abilities/swamp_ambush.cfg:26
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/general_data/_data.cfg:3
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:17
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/data/EoMa_data/ambush.cfg:18
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:11
    included from ~add-ons/Ageless_Era/_main.cfg:89
20240407 16:24:51 warning preprocessor: Redefining macro ABILITY_AE_MAG_WATERAMBUSH without explicit #undef at ~add-ons/Ageless_Era/data/general_data/abilities/water_ambush.cfg:25
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/general_data/_data.cfg:3
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:17
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/data/EoMa_data/ambush.cfg:35
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:11
    included from ~add-ons/Ageless_Era/_main.cfg:89
20240407 16:24:51 warning preprocessor: Redefining macro WEAPON_SPECIAL_AE_MAG_ATTACK_ONLY without explicit #undef at ~add-ons/Ageless_Era/data/general_data/weapon_specials/attack_only.cfg:15
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/general_data/_data.cfg:4
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:17
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/data/EoMa_data/abilities.cfg:3
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:11
    included from ~add-ons/Ageless_Era/_main.cfg:89
20240407 16:24:51 warning preprocessor: Redefining macro AE_RHY_SPECIAL_NOTES_MASSIVE without explicit #undef at ~add-ons/Ageless_Era/data/RE_data/special-notes.cfg:3
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:21
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/text/special-notes-RE.cfg:3
    included from ~add-ons/Ageless_Era/_main.cfg:88
20240407 16:24:51 warning preprocessor: Redefining macro AE_RHY_SPECIAL_NOTES_NIGHTSNEAK without explicit #undef at ~add-ons/Ageless_Era/data/RE_data/special-notes.cfg:9
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:21
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/text/special-notes-RE.cfg:21
    included from ~add-ons/Ageless_Era/_main.cfg:88
20240407 16:24:51 warning preprocessor: Redefining macro AE_RHY_SPECIAL_NOTES_SHIELDDEFENSE without explicit #undef at ~add-ons/Ageless_Era/data/RE_data/special-notes.cfg:21
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:21
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/text/special-notes-RE.cfg:24
    included from ~add-ons/Ageless_Era/_main.cfg:88
20240407 16:24:51 warning preprocessor: Redefining macro AE_RHY_SPECIAL_NOTES_RECRUIT without explicit #undef at ~add-ons/Ageless_Era/data/RE_data/special-notes.cfg:45
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:21
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/data/RE_data/abilities_recruit_black_lich.cfg:4
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:21
    included from ~add-ons/Ageless_Era/_main.cfg:89
20240407 16:24:51 warning preprocessor: Redefining macro AE_RHY_SPECIAL_NOTES_NIGHTEYE without explicit #undef at ~add-ons/Ageless_Era/data/RE_data/special-notes.cfg:69
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:21
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/text/special-notes-RE.cfg:30
    included from ~add-ons/Ageless_Era/_main.cfg:88
20240407 16:24:51 warning preprocessor: Redefining macro AE_RHY_SPECIAL_NOTES_DEATHSTRIKE without explicit #undef at ~add-ons/Ageless_Era/data/RE_data/special-notes.cfg:81
    included from ~add-ons/Ageless_Era/_main.cfg:65
    included from ~add-ons/Ageless_Era/data/_main.cfg:21
    included from ~add-ons/Ageless_Era/_main.cfg:89
previously defined at ~add-ons/Ageless_Era/text/special-notes-RE.cfg:45
    included from ~add-ons/Ageless_Era/_main.cfg:88
20240407 16:24:54 warning preprocessor: Redefining macro VAMPIRE_NAMES without explicit #undef at ~add-ons/Ageless_Era/units/MiE_units/./vampires.cfg:3
    included from ~add-ons/Ageless_Era/units/MiE_units/_main.cfg:9
    included from ~add-ons/Ageless_Era/_main.cfg:61
    included from ~add-ons/Ageless_Era/units/_main.cfg:99
    included from ~add-ons/Ageless_Era/_main.cfg:92
previously defined at ~add-ons/Ageless_Era/text/names-EoM.cfg:3
    included from ~add-ons/Ageless_Era/_main.cfg:88
20240407 16:24:56 error deprecation: SPECIAL_NOTES a été déprécié et supprimé.; Use [special_note]note= tags and special_note= attributes instead.
20240407 16:24:56 error deprecation: SPECIAL_NOTES a été déprécié et supprimé.; Use [special_note]note= tags and special_note= attributes instead.
20240407 16:24:56 error deprecation: SPECIAL_NOTES a été déprécié et supprimé.; Use [special_note]note= tags and special_note= attributes instead.
20240407 16:24:56 error deprecation: SPECIAL_NOTES a été déprécié et supprimé.; Use [special_note]note= tags and special_note= attributes instead.
20240407 16:25:05 error general: Il y a un problème avec la vérification des versions d'extension au niveau du vestibule multijoueur. Merci de le signaler sur https://bugs.wesnoth.org.
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/dwarves/ballista.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/dwarves/ballista.png'
20240407 16:29:12 error image: could not open image 'units/dunefolk/wayfarer.png'
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/human-chevalier/general.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/human-chevalier/general.png'
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/human-dardo/captain.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/human-dardo/captain.png'
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/elyser/high-lord.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/elyser/high-lord.png'
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/human-forest/druid.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/human-forest/druid.png'
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/human-luz/bishop.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/human-luz/bishop.png'
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/marashy/shadow-mage.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/marashy/shadow-mage.png'
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/human-mountains/birdman.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/human-mountains/birdman.png'
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/human-regis/noble-lord.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/human-regis/noble-lord.png'
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/trarashy/sentinel.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/trarashy/sentinel.png'
20240407 16:29:12 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/Rashy_Era/images/units/vixens/queen.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Ageless_Resources/general/images/units/vixens/queen.png'
20240407 16:29:39 error lobby: Room window not open in add_room_window_message for Linux
20240407 16:31:17 error deprecation: helper.lua a été déprécié et sera supprimé à la version 1.19.0.; Everything in this module has been moved into the core modules
20240407 16:31:56 warning filesystem: Conflicting files in binary_path: 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/Era_of_Magic_Resources/images/icons/profiles/secret.png' and 'C:\users\USER\Documents\My Games\Wesnoth1.18/data/add-ons/QQ_Ultimate_Wesnoth_Survival/images/icons/profiles/secret.png'

**Comment by alauzon** [comment]
Many errors

**Comment by Pentarctagon** [comment]
Does the error happen if you have only Dimaga Beach installed?

**Comment by Wedge009** [comment]
> Ok, it's under /home/alain/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/599390/pfx/drive_c/users/steamuser/Documents/My Games/Wesnoth1.18/logs

Maybe not relevant to the actual issue... but I am wondering why are you using what looks like the Windows version of Wesnoth via Steam Proton when there's a native Linux version available?

**Comment by soliton-** [comment]
Closing in favor of #8805.
