### ISSUE TITLE
Document unit vision

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#8719]
### Describe the desired feature

Maybe I'm missing something but the in-game help has a section on movement and shroud/fog but it doesn't really explain how vision works.

It should at least mention that the default is unit movement + 1 hex and ideally also explain that some units can have vision cost independent of movement cost.

**Comment by stevecotton** [comment]
There's a similar feature request for documenting jamming (#5325), but I think it makes sense to have this issue too. Getting the docs for basic vision without considering jamming would be a good thing.
