### ISSUE TITLE
Add a script to delete source files

### ISSUE THREAD

**Issue by gfgtdf** [wesnoth/wesnoth#8733]
### Describe the desired feature

We have a script to add source files to the various projectfiles, but we are currently lacking a script to delete them from the projectfles.

Not sure whether a separate script or  a `-d` option to the existing script would be better

**Comment by soliton-** [comment]
I think a new option for the existing script makes the most sense even if it doesn't quite fit the name. Knowledge about the existing project files is in there and shouldn't be unnecessarily duplicated.
