### ISSUE TITLE
CI failures on forks of Wesnoth?

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#8736]
I regularly get CI failures on my fork (master and 1.16/1.18 branches, no modifications) even when CI passes on the main repository. It's been going on for several months, if not years, I don't actually pay attention to them any more (which is obviously bad in the case of genuine failures). Am I the only one who has this?

Looking at the most recent CI runs, it seems to be failures in the 'flatpak' and 'notification' jobs. My most recent (at time of writing) runs failures:
* Flatpak: https://github.com/Wedge009/wesnoth/actions/runs/8530958666/job/23369704764
* Notification: https://github.com/Wedge009/wesnoth/actions/runs/8530958666/job/23371726618

For the latter, at least, it seems to be disallowing commit notifications on Discord, which makes sense. But is there a way to stop this action on forks?

**Comment by soliton-** [comment]
https://github.com/wesnoth/wesnoth/commit/020c848c84458b37d50369b14cd1c53411a9d8d9 should fix the flatpak issue. Notification only happens on failure so one more failure doesn't do much but we could add a check to skip anyway.

**Comment by Wedge009** [comment]
It looks like CI on my fork is working again. Thanks.
