### ISSUE TITLE
EI: Likely Typos in Unit Names for Dacyn and Mel Guthrak

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8744]
### Language

English

### Source

EI S1, S2, S16, S17a, S17b

### Original Text

In EI S1 Eastern Invasion, S2 The Escape Tunnel and S16 Eleventh Hour an undead leader is named "Mel Guthrak" which is inconsistent with other Necromancers/Liches naming conventions in the campaign. 
Probably should be "Mal-Guthrak".

(Spoilers?) In the cutscene after winning S17a and S17b, Dacyn's unit name briefly changes to "Mak-Dak'an" when Dacyn considers becoming a lich.
This is probably intended to be "Mal-Dak'an."

**Comment by Dalas121** [comment]
"Mel Guthrak" is a holdover from the original EI - that's what he was called there, so I left it as-is.  I don't care much either way, but as the campaign is already being translated I feel it's probably not worth fixing it.

"Mak-Dak'an" is a typo; I'll make a PR.
