### ISSUE TITLE
EI: Plague Staff Doesn't Gain Arcane Damage When Equipped After Holy Amulet

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8745]
### Game and System Information

- **Version:**1.18
- **OS:**ChromeOS/Debian

### Description of the bug

Very minor bug where the Plague Staff's melee attack doesn't gain the Arcane damage type when equipped after a Holy Amulet is equipped. Equipping the Plague Staff first and the amulet second works correctly.

### Steps to reproduce the behavior

1. Have a unit equip a Holy Amulet (arcane damage on all attacks)
2. Have that unit equip the Plague Staff (gives a new attack)
3. Plague Staff's attack doesn't benefit from the Holy Amulet's arcane damage

**Comment by CelticMinstrel** [comment]
This doesn't make any sense, as "equip" is not a concept that exists in mainline Wesnoth as far as I know. Did you submit this issue to the wrong repository? Or if it is indeed mainline, which campaign does this occur in?

**Comment by IskarJarak01** [comment]
This is in the new Eastern Invasion, which has items.

**Comment by newfrenchy83** [comment]
Apparently Holy_amulet give arcane damage to melle attack if already present before but effect don't repeated when another attack is added. Perhaps reinitialise all effect when a new is added is necessary.

**Comment by stevecotton** [comment]
Should be fixable in the campaign, by making picking up the plague staff remove and then re-add the amulet's `[object]`, so that the modifications are applied in a different order.

I feel it'd be fitting to have some dialogue about being unable to use the plague staff together with the amulet, but then again I share Owaec's reservations about the heroes of EI using the staff at all.

**Comment by newfrenchy83** [comment]
> Should be fixable in the campaign, by making picking up the plague staff remove and then re-add the amulet's `[object]`, so that the modifications are applied in a different order.
> 
> I feel it'd be fitting to have some dialogue about being unable to use the plague staff together with the amulet, but then again I share Owaec's reservations about the heroes of EI using the staff at all.

either we prohibit the player from using the two objects on the same unit or we transfer damage_type to the [abilities] tag given that we have in EI either arcane applied to thrown weapons and the stick is melee or an application to all weapons and there we can use an ability instead

**Comment by newfrenchy83** [comment]
@IskarJarak01 i added a PR for fix this issue
