### ISSUE TITLE
WoF: In S08 Overlook, Objectives Hidden For Story Reasons Can Result in Ending Scenario Earlier Than the Player Expects and Killing Veterans

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8751]
### Describe the desired feature

In WoF S08 Overlook the objectives window states: "Victory: Gorlack, Resha, Arinexis and Zedrix reach the cave exit."

An objective note reads: "When the heroes exit, anyone left on the map will die."

However, Resha refuses to leave the cave, so the actual objective is to move Gorlack, Arinexis and Zedrix to the exit. Once those 3 heroes exit the cave, Resha sacrifices herself and the scenario ends, killing any of your units remaining on the map. 

The objective is misleading on purpose so that Resha's death won't be spoiled. However, Resha's death doesn't work narratively anyway if you just watched Resha heroically kill 200G worth of your veterans.

Possible Solution
Currently, Resha insists on leaving last, so only trigger the scenario end when Resha is the last hero to move to the cave exit. At this point, Gorlack can return to the cave for their final conversation to play out. This preserves the surprise of Resha's death without surprising the player with the death of their veterans.

Alternately, units in a radius of 1-2 moves from the exit could automatically escape the map when the scenario ends.

**Comment by Jonathan-Kelly** [comment]
How would you feel about a change of the objective notes from:

`"When the heroes exit, anyone left on the map will die"`
`"Anyone that exits before the heroes do will survive"`
`"Unrecalled veterans will survive"`

To something more specific like:

`"When Gorlack exits, any recruits or recalled veterans left on the map will die"`
`"Recruits and recalled veterans which exit before Gorlack does will survive"`
`"Unrecalled veterans will survive"`

?

**Comment by CelticMinstrel** [comment]
Glancing at the scenario file, it seems the logic behind this setup is that the cave will collapse after the three heroes exit. If that's the case, it seems totally logical for the units closest to the exit to also escape.

**Comment by IskarJarak01** [comment]
Making the objective notes more specific would also solve the problem. I didn't suggest modifying objective notes here because of the knock-on effects on translation, but it isn't my decision anyway.

**Comment by Jonathan-Kelly** [comment]
> I didn't suggest modifying objective notes here because of the knock-on effects on translation, but it isn't my decision anyway.

That would be true for bug fixes that will be ported back to stable. But since this is an enhancement, my understanding is changes to translatable strings are alright in this case.

> If that's the case, it seems totally logical for the units closest to the exit to also escape.

It is logical, but unfortunately there is no way of knowing that the player will have all the units they plan to save close enough to the exit when Gorlack goes through.

**Comment by Jonathan-Kelly** [comment]
If objective notes are not clear enough, then a lot of players will still have units two or three moves away, perhaps even further away on the lower difficulties where enemy pressure is much weaker and beginner players' ideas of unit formations and defensive lines are eccentric.

**Comment by CelticMinstrel** [comment]
You could give everyone a movement buff on that final turn. Being in immediate danger, they could be capable of putting on an extra burst of speed.

It also doesn't have to be one turn. You could give them two or three turns to get units out after the event triggers. Or one turn on hard, two turns on medium, three turns on easy.

There's also the option of _not_ killing everyone off if they don't manage to get through. You can sacrifice a little realism for a) clarity of objectives and b) not needing to carefully tiptoe around spoilers. Just say "Actually, everyone made it through".
