### ISSUE TITLE
Oasis should have a (shallow water / sand) dual typing

### ISSUE THREAD

**Issue by OrangePumpking** [wesnoth/wesnoth#8753]
### Describe the desired feature

It would make sense for an oasis tile to have a dual typing that hints at the water. E.g. when moving a mermen unit through sandy terrain, a player would instinctively try to land them on an oasis, assuming they'd be in their element there.

As far as I understand Wesnoth terrain rules, units tend to get the terrain defense of the half that is most beneficial to them. So giving the oasis dual typing shouldn't mess anything up for sand-favoring units.

**Comment by CelticMinstrel** [comment]
Precedented with ford, so I tentatively agree.
