### ISSUE TITLE
Create a GitHub Code of Conduct

### ISSUE THREAD

**Issue by CoxAsh** [wesnoth/wesnoth#8756]
### Describe the desired feature

With currently ongoing events in mind I think it would be good to create a GitHub code of conduct because it is clear that disruptive behaviour seems to be rampant whenever there is any bigger issue in this community.

**Comment by kabachuha** [comment]
![b911f8329c0db87a](https://github.com/wesnoth/wesnoth/assets/14872007/5fd787c4-1fc2-4c08-ab14-1ab5748c8111)

Of course we'll trust a literally day-ago signup on a global Wesnoth community issue

**(no)**

Hejne, do you know it's prohibited to create alt accounts by Github TOS? **Your** behavior is unacceptable here

**Comment by kabachuha** [comment]
Need to add context for newcomers to this issue: this is not an abstract Wesnoth community issue, it's related to #8740 #8741 and #8749 —who have ruined Wesnoth balance and discuss how to fix it — directly

**Comment by DuncanusDillius** [comment]
> So I learned about this issue from YouTube, made an account just to share my opinion and this is what others (a developer nonetheless!) think? If this is how newcomers are treated by developement team just because they are new, there is no wonder why this game is dying. An impostor just because I dare to disagree.

What video, as a matter of curiosity? I can't find any on the matter...

**Comment by Mirion147** [comment]
> So I learned about this issue from YouTube, made an account just to share my opinion and this is what others (a developer nonetheless!) think? If this is how newcomers are treated by developement team just because they are new, there is no wonder why this game is dying. An impostor just because I dare to disagree. 

I just want to point out that this post here is right in line with what you spoke out against in the other thread. You posted something, a developer disagreed with you, and you're not happy about it.

**Comment by Pentarctagon** [comment]
The expectation is that the [Community Guidelines](https://forums.wesnoth.org/viewtopic.php?t=24277) apply here as well, so there's no reason to create a code of conduct just for Github. However people are not immediately and permanently banned after their first offense unless it's very severe.

**Comment by CelticMinstrel** [comment]
> Of course we'll trust a literally day-ago signup on a global Wesnoth community issue
> 
> **(no)**
> 
> Hejne, do you know it's prohibited to create alt accounts by Github TOS? **Your** behavior is unacceptable here

This is _entirely_ uncalled for. There's literally no reason why a newly-created account should not be trusted.

Also, while I obviously can't be certain, the creation of an issue like this doesn't seem at all in-character for Hejnewar, so I'm inclined to believe that CoxAsh is, in fact, a separate person.

**Comment by CelticMinstrel** [comment]
> I just want to point out that this post here is right in line with what you spoke out against in the other thread. You posted something, a developer disagreed with you, and you're not happy about it.

What on earth are you talking about? What just happened in this thread is not "CoxAsh posted something; a dev disagreed; CoxAsh is not happy". It's much more severe than that: "CoxAsh posted something; a dev outright insulted and slandered him; CoxAsh is not happy".

I'd say CoxAsh has every right to be annoyed. The one in the wrong here is _clearly_ kabachuha.

Even if by some chance kabachuha happened to be _right_ that CoxAsh is a Hejnewar alt (as unlikely as I think that seems), that doesn't give him the right to openly attack him like that.

**Comment by Mirion147** [comment]
> > I just want to point out that this post here is right in line with what you spoke out against in the other thread. You posted something, a developer disagreed with you, and you're not happy about it.
> 
> What on earth are you talking about? What just happened in this thread is not "CoxAsh posted something; a dev disagreed; CoxAsh is not happy". It's much more severe than that: "CoxAsh posted something; a dev outright insulted and slandered him; CoxAsh is not happy".
> 
> I'd say CoxAsh has every right to be annoyed. The one in the wrong here is _clearly_ kabachuha.
> 
> Even if by some chance kabachuha happened to be _right_ that CoxAsh is a Hejnewar alt (as unlikely as I think that seems), that doesn't give him the right to openly attack him like that.

I'm not saying kabachuha was right or wrong. Just noting the similarities. I agree it's more severe than my words can be perceived to indicate, but I do think it's fairly common for devs to respond a bit harshly to differing opinions, and especially to new opinions. In the topic this stemmed from Hej's first response is to call someone a liar, and second response talks about how he's not going to care about what people are saying at this point. So I think the insults are in both topics and therefore my statement is valid. But you are right, it is definitely a bigger affront than just disagreeing.

**Comment by Mirion147** [comment]
I could also note that I don't have any personal issue with you, CelticMinstrel. I have noticed several times in the past that your comments can very easily read as having strong tones of aggression which can likely discourage members from making suggestions or asking questions. I also will note that I've always tried to take this as simply your style of writing and that you don't actually mean to sound as aggressive as you can. It's very difficult to understand the tone of a written message and I think all of us, myself included, could spend a few extra minutes ensuring that we're not coming across differently than we intend. 

Again, I'm not trying to insult anyone, just voicing my perceptions.

**Comment by soliton-** [comment]
We already have a code of conduct set on github, btw. See https://github.com/wesnoth/wesnoth?tab=coc-ov-file or the `CODE_OF_CONDUCT.md` file.
