### ISSUE TITLE
Turns Over does not enter Linger Mode

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#8779]
### Game and System Information

1.18.0

### Description of the bug

After the message of winning/losing the game immediately exists the scenario.

### Steps to reproduce the behavior

Set a turn limit on a MP map via the settings. Tested in local MP.

### Expected behavior

For people to chat and arrange a new game it should enter Linger Mode. Works like that in 1.16.

### Additional context

[fire_event]name=time over does not trigger this.

**Comment by gfgtdf** [comment]
I did quite a few changes to related code in 1.19, could you test whether it also affects 1.19 ?

**Comment by sevu** [comment]
1.19 is not affected. Can it be backported?

**Comment by gfgtdf** [comment]
If its fixed by teh commit i meantione above, then yes

**Comment by sevu** [comment]
It is

**Comment by gfgtdf** [comment]
i can backport it when im home tomorrow or in a few days, or you could also do it yourself if you want.

**Comment by sevu** [comment]
Backported
