### ISSUE TITLE
HttT: Li'sar (a Hero Unit) can be Renamed.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#8781]
### Game and System Information

- **Version:** 1.18.0+dev
- **OS:** Windows 10

### Description of the bug

![image](https://github.com/wesnoth/wesnoth/assets/5283677/38f514a4-19c8-4890-86e8-91a610cba479)
- You can rename a hero unit "Li'sar"

### Steps to reproduce the behavior

[HttT-The Sceptre of Fire.gz](https://github.com/wesnoth/wesnoth/files/15048403/HttT-The.Sceptre.of.Fire.gz)
- Download Save File
- Launch Client
- Load Save File
- Right-Click on Li'sar and see "Rename Unit"

### Expected behavior

- Li'sar can NOT be renamed.

**Comment by AnekronCZ** [comment]
The bug is in the Hasty Alliance scenario. Unrenamable=yes is missing there and should be added around the line 90. If you convert Li'sar to side=1 via debug or take control of her side, you can rename her there as well.
