### ISSUE TITLE
Animation glitch introduced with hardware submerge

### ISSUE THREAD

**Issue by grz0** [wesnoth/wesnoth#8789]
### Game and System Information

The Battle for Wesnoth version 1.19.0-dev (https://github.com/wesnoth/wesnoth/commit/39987cd1ca4c09ea2f5d9de08ecfa3c6b029fe5d-Clean) Nieznana
Running on Freedesktop SDK 23.08 (Flatpak runtime) x86_64
Distribution channel: Flatpak

### Description of the bug

After destruction of the bridge, the unit standing in water is glitched. Check video:
[Screencast_20240421_002149.webm](https://github.com/wesnoth/wesnoth/assets/3605541/ed4364b5-dce4-4be3-8f7f-f5efd2cb315e)

### Steps to reproduce the behavior

1. Destroy the bridge

**Comment by Wedge009** [comment]
I don't think this is specific to EI but I found another occurrence in S6a Undead Crossing.
![image](https://github.com/wesnoth/wesnoth/assets/13679322/0b05c4eb-49b2-4c18-972b-96e684e69dea)

I confirmed it doesn't occur in 1.18.0 and after bisecting against master I confirmed my suspicion that it was the hardware submerge change that introduced this. #8687 by @Pentarctagon and @mesilliac.

**Comment by Pentarctagon** [comment]
Water animations strike again...

**Comment by Wedge009** [comment]
Guessing that's a reference to #8845.

**Comment by Pentarctagon** [comment]
Also for example the flickering sprite at the start of the video in https://github.com/wesnoth/wesnoth/issues/6960#issuecomment-1407075408

**Comment by Wedge009** [comment]
@Vultraz I'm not in a position to test right now, but does 26b467e3901c16e0acdc81fb01a46b4731109896 resolve this issue as well?

**Comment by Vultraz** [comment]
I can't reproduce this exact issue, but I do observe a weird flickering with the submerged part during some parts of the animation. It looks like it's using the wrong texture on random frames. Still investigating.

**Comment by Wedge009** [comment]
At 0fbf0688241396529869d6ca3312e9c6a403d162, I cannot replicate the submerged glitch as shown in my image from 22 May. So I think this is resolved as well.
