### ISSUE TITLE
DiD - A Haunting Winter: Ending the Grind

### ISSUE THREAD

**Issue by Sorenroy** [wesnoth/wesnoth#8809]
### Describe the desired feature

The writing and believable struggle of Malin Keshar, along with the limited resources of the early portion of the campaign, pair to make Decent into Darkness my favorite mainline campaign and the one I was most excited to come back and play following the 1.18 update. However, the new "A Haunting Winter" level removes that second strength of the campaign by creating respawning enemies in a level without a timer, allowing for endless, penalty-free grinding. This aspect not only undermines the challenge of the later scenarios, but also Malin's progression as a young necromancer apprenticing to Darken Volk. The optimal strategy is now to leave the cave a Dark Mage followed by a horde of ghasts, banebows, draugs, and dread bats with as much XP as you can bear to grind through.

There are multiple ways to solve this: removing XP granted from killing the respawning enemies (rather than setting it to 1), adding a generous level timer, and/or capping the number of creatures that can spawn in total. Personally, I think the best solution would be to take away the experience gain and add a tag to the respawning rats so that they no longer can be used to boost necrophage/ghast HP. There are multiple story-related reasons to justify these ideas (the rats being so thin as to not proc. the feeding perk, the magic of the cave making the rats inedible, etc.), but it would leave intact the absence of needing to rush through the level, allow for the player to still find and solve the two puzzles to grant Malin Keshar some bonus XP, and still allow for an achievement to sit there eating rats, even if there isn't a tangible benefit to the units themselves.

**Comment by nemaara** [comment]
Addressed in https://github.com/wesnoth/wesnoth/commit/ff040853c288f083c6881fc128eae2bcd3c01bd7. Still allowing HP grinding if you really like, but grinding necrophages/ghasts is much less powerful than stacking exp, as they simply don't have the damage to let you push in some scenarios.

**Comment by Sorenroy** [comment]
Thank you! The power of grinding necrophages/ghasts to high HP - to me - is more about establishing zones of control for weaker units with their walls of health and allowing other units to push towards scenario objectives. But this fix makes it much easier to avoid grinding on the player side by just not moving those units into combat range. I think an increase to the XP gained for solving the puzzles is an excellent counterbalance, but I wonder how it will work in playing the campaign. 80 XP for burning the glyph and poisoning rats is more XP for Malin than fighting and killing three level three units, which puts your hero unit at substantially more risk. It certainly makes Malin play like a more experienced necromancer upon leaving the cave gameplay-wise though.
