### ISSUE TITLE
Change Mudcrawlers' defense in the swamp to 60%

### ISSUE THREAD

**Issue by amakriLexa04** [wesnoth/wesnoth#8823]
### Describe the desired feature

Mudcrawlers, as the name suggests, are made of mud. Where else is there mud? That's right, in the swamp! 
But Mudcrawlers in swamp have only 40%, just like on the plain, which is a bit strange. Therefore I suggest increasing their defense in swamp to 60-70%, so that they have a place where they feel good. And also reduce protection in the castle. 
You can do this by adding this to Giant_Mudcrawler.cfg and Mudcrawler.cfg:
```
[defense]
        swamp_water=40
	castle=60
[/defense]
```

**Comment by Jonathan-Kelly** [comment]
It might make sense to reduce their movement penalty in swamp too, especially given how slow mudcrawlers are in general.

Is there any reason you want to reduce their castle defense in particular or is that just to compensate the game balance?

**Comment by amakriLexa04** [comment]
I agree on this, they are extremely slow

Yes, generally for balance. If you improve one thing, you have to worsen another. But also this makes sense from a logical point of view, here in fact we have analogy with the feral trait, but in terms of castles. Mudcrawlers have such a low intelligence that they don't know how to defend themselves effectively in the artificial environment.

**Comment by amakriLexa04** [comment]
I don't think that MP cost 2 for unit which has 3 MP(Mudcrawler, the Giant one has 4) is the best idea. As for your suggestion of the defense, it's not bad, because 60 in the castle and 40 in the swamp was really strange, although I would suggest anyway making the swamp 60, because it's a swamp and mudcrawlers are supposed to live there, probably.

**Comment by Jonathan-Kelly** [comment]
> Mudcrawlers have such a low intelligence that they don't know how to defend themselves effectively in the artificial environment.

That logic seems to fit well with many of the other monster units, as long as village defense is kept at the same (reduced) level as castle. So altogether this change might look something like:

```
[movement_costs]
    swamp_water=1
[/movement_costs]
[defense]
    swamp_water=40
    castle=50
    village=50
[/defense]
```

**Comment by CelticMinstrel** [comment]
Is mudcrawlers having low intelligence canon?

**Comment by amakriLexa04** [comment]
This is not stated directly, but it can be understood from the description:

> **Simple beings conjured up from soil and water**, Mudcrawlers fend for themselves by spitting globs of mud with surprising force. Even though they are slow, fragile, and vulnerable to fire, **their quick and easy creation**, along with their resistance to a common citizen’s improvised blunt weaponry, makes them the tool of choice for ambitious but **inexperienced** summoners.

I doubt that creatures that consists of soil and water, easily made and created by inexperienced summoners, can be any more intelligent than mud they are made of

**Comment by CelticMinstrel** [comment]
I think that's a slight exaggeration, seems like they'd _have_ to be at least _slightly_ more intelligent than inanimate mud.

**Comment by amakriLexa04** [comment]
Yes, perhaps this is an exaggeration, but anyway it is obvious that they are not the most intelligent creatures

**Comment by PointMeAtTheDawn** [comment]
> Yes, generally for balance. If you improve one thing, you have to worsen another. But also this makes sense from a logical point of view, here in fact we have analogy with the feral trait, but in terms of castles. Mudcrawlers have such a low intelligence that they don't know how to defend themselves effectively in the artificial environment.
I don't think this is a generally true statement. For the record, I have no strong opinions on this change (with or without the castle change included), but wanted to weigh in on design philosophy. Feel free to skip the rest of this post as it's just my opinion on this.

Balance is a lens that can be used to analyze various domains, and has different implications in each.
1. There's competitive multiplayer balance, where certain scopes (in Wesnoth's case, faction vs faction) MUST be balanced as finely as possible. If a faction is too strong, it MUST be nerfed. Sometimes compensating buffs to increase the magnitude of the nerf can be warranted, but it's usually cleaner to do a straight nerf on its own. (If a faction is too weak, it COULD be buffed, but that's a far less grave sin than being too strong). Sub-faction balance is largely irrelevant - it doesn't matter if the dwarven fighter is a better unit than the heavy infantryman in almost every single way, so long as Knalgans vs Loyalists (et al.) are in harmony.
2. There's competitive singleplayer balance, which varies much more widely. (Is money/pay2win involved? Can an element that's 'harder' to execute be allowed to be stronger than one that's more straightforward? How does RNG play into the options available to a player? What type(s) is it - Input/output, variable/uniform?) As such, not going to pretend I can make sweeping generalizations here except that 'it depends'.

In this case, changes here affect all mainline/UMC content, depending on the mudcrawler's criticality in it. Usually I see them as an enemy, but I believe they can be summoned by Delfador somewhere. How common are swamps/castles in those scenarios? How much does this increase/decrease the difficulty? E.g. in UtBS S1, I definitely have to play around not letting the mudcrawlers get on the southern castle hexes around Garak's stand. This eliminates that consideration from play. How bad is that? Not very. How about the survival scenarios? Will the waves need to be rebalanced for this? Probably not lol.

TL;DR: If we're making balance changes for thematic reasons (and for the mudcrawler, I think that is reasonable), I think we're safely in a position that we don't need to worry about balance of any sort. If you want to just buff it in swamps, go for it. If you want to nerf it in castles too, cool. It's not in competitive multiplayer, so the only limits are how many UMC authors you want complaining that you upset their carefully crafted scenario.

**Comment by amakriLexa04** [comment]
Hello, thanks for such a detailed text

I know for a fact that Mudcrawlers are found as enemies in utbs and did. In utbs there are no swamps, but there are castles. In did(03_A_Haunting_in_Winter), they can be found in a cave where they spawn endlessly, and there is a lot of swamp nearby, but as I've seen, it's pretty easy to kill them now. You can't control Mudcrawlers anywhere, except in UMC and tdg.

I completely agree with you that these changes can and will negatively affect the balance of add-ons. That's why we need to test these changes to see how they feel (they shouldn't affect standard multiplayer btw, because no faction has Mudcrawlers as an available unit)

**Comment by CelticMinstrel** [comment]
> (they shouldn't affect standard multiplayer btw, because no faction has Mudcrawlers as an available unit)

Not entirely true. At least one of the existing survival scenarios spawns mudcrawlers in its waves of enemies, I'm pretty sure. I think they may also exist in that wilderness scenario (the one with the yeti and the skeletal dragon).

**Comment by spixi** [comment]
A quick resilent Mudcrawler is part of the default roster in Hornshark Island (which is for factions like Dunefolk). However, as this unit is more a joke and not very useful, except against Undead.

**Comment by HolyPaladin1** [comment]
> A quick resilent Mudcrawler is part of the default roster in Hornshark Island (which is for factions like Dunefolk). However, as this unit is more a joke and not very useful, except against Undead.

I would not say it's that useless, look on mudcrawlers fighting against units with impact attack just like trolls

**Comment by spixi** [comment]
Note that this makes it more difficult for player 2 playing Dunefolk to defend the village at 19,25 with a Mudcrawler. They can use their Sand Scuttler, but that one is usually used to capture the village at 18,21 and save the keep at 22,20.

**Comment by CelticMinstrel** [comment]
That could be solved with an `[object]` on that specific Mudcrawler.

**Comment by spixi** [comment]
> That could be solved with an `[object]` on that specific Mudcrawler.

I added PR #8933 to solve this issue
