### ISSUE TITLE
Add hooks into the GUI2 theming system

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#8825]
GUI2 has a built-in theming system that can in principle be used to reskin the entire game, but at present there's a number of obstacles to actually using it.

First of all, custom themes can only be added by editing the game data right now. There should be some way of loading themes from addons.

Secondly, while there is a preference to change the preferred theme (I'm not sure if it's an advanced preference or a hidden preference), there's no way for a scenario to request switching to a particular theme.

There's likely other issues as well that make the system unusable for anything beyond making a mobile theme for the iOS/Android versions.

**Comment by ProditorMagnus** [comment]
Is that different from https://wiki.wesnoth.org/InterfaceActionsWML#.5Bchange_theme.5D?

**Comment by CelticMinstrel** [comment]
Not even slightly related. That's the in-game theme (ThemeWML), while this is GUI2.

**Comment by babaissarkar** [comment]
Would be good to have a list of specifications here, that is, the things that people would like to be customizable.
Things that I can remember :
1. The titlescreen appearance and layout
2. Appearance of in game UI controls
3. Any kind of color/position variables that are currently hardcoded. (I saw quite a few of them in [here](https://github.com/wesnoth/wesnoth/blob/master/data/gui/macros/_initial.cfg))

@CelticMinstrel Can this be related to porting ThemeWML to GUI2?

**Comment by CelticMinstrel** [comment]
> Can this be related to porting ThemeWML to GUI2?

I wouldn't say it's related.

> The titlescreen appearance and layout along with the background image

Though this could be a possibility, it might be worth limiting custom themes to be used only in-game (ie, dialogs that are shown during the course of a scenario). Otherwise, someone could install a broken theme that renders the game completely unplayable.

Another thing: if I recall correctly, I _think_ switching the GUI2 theme requires restarting Wesnoth at the moment, which is obviously a problem if we want to be able to use custom themes in scenarios.

**Comment by hladkyjakub** [comment]
> Would be good to have a list of specifications here, that is, the things that people would like to be customizable.
Things that I can remember :
I was thinking about option to use custom
> Though this could be a possibility, it might be worth limiting custom themes to be used only in-game (ie, dialogs that are shown during the course of a scenario). Otherwise, someone could install a broken theme that renders the game completely unplayable.
I do partly agree.
You should be able to edit any dialog while your add-on is active (in-game wiki, preferences, dialogs ...)
(As long as it's only while add-on is active, it shouldn't be able to break the game.

I'm not developer but I thought it could be done using cpp equivalent of 
`Theme = CustomTheme or DefaultTheme` ... maybe?

**Comment by Vultraz** [comment]
I really don’t think this is worth it for anything beyond the in-game UI. Besides the amount of work required to support it, it doesn’t really make sense to allow people to skin the whole UI.

**Comment by CelticMinstrel** [comment]
> it doesn’t really make sense to allow people to skin the whole UI

Though I kind of agree on this, it _does_ make sense to allow people to skin such dialogs as the story screen or the narration dialog.

> I really don’t think this is worth it for anything beyond the in-game UI.

The in-game UI is (probably) a completely separate situation, as it must be built to tie into the reports system.

**Comment by babaissarkar** [comment]
Preference for switching themes: #8953 
Loading gui2 themes from addons: #9057

**Comment by CelticMinstrel** [comment]
I think those two together cover the "firstly" portion of this issue.

**Comment by babaissarkar** [comment]
> I think those two together cover the "firstly" portion of this issue.

Will a Lua function to switch to a particular theme be enough for the second portion, or something else is needed?

**Comment by CelticMinstrel** [comment]
I guess it would make sense to be able to specify the starting theme in an addon tag (eg `[campaign]use_theme=modern`, but… a Lua function would be the absolute minimum requirement. Putting a `[lua]` tag that calls said function in the addon tag would ultimately have the same effect as the aforementioned key, I think. (You'd have to verify that that _works_ though – that you can switch the theme even before prestart.)

Also, the system would need to revert to the default theme (specified in preferences) when you exit the scenario. Naturally, a Lua-set theme should also not be saved in preferences.

**Comment by babaissarkar** [comment]
@CelticMinstrel I think this should be closed since #9057 is merged.
