### ISSUE TITLE
Expose unit pick dialog to Lua as a simple API call

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#8829]
This refers to the recruit, recall, and debug unit create dialogs – I believe it would make sense to merge them into single dialog that supports various options to tweak it into being identical to any of the current dialogs. If it turns out I'm wrong, however, the main thing would be to expose the recruit dialog, so that SotA can handle its corpse recruits in a more reasonable manner (and automatically get all the features of the recruit dialog, like filtering).

**Comment by babaissarkar** [comment]
If we're consolidating those dialogs, I'd suggest the following two things :
1. It should deal with #1059
2. Putting something as important as Recruit/Recall into a right click context menu doesn't feel good. One idea would be to show the recruit/recall when mouse hovers on top of a castle tile while the leader is in the keep. Haven't thought this in detail, but it'd atleast save a lot of clicks and make it obvious. (I've even thought of a design, might post that later.)

**Comment by CelticMinstrel** [comment]
> One idea would be to show the recruit/recall when mouse hovers on top of a castle tile while the leader is in the keep.

I'm not entirely sure what you mean by this, but I think it should be obvious that opening a modal dialog in response to a mouse hover is a very bad idea. Maybe that's not what you meant though.

**Comment by gfgtdf** [comment]
> the main thing would be to expose the recruit dialog, so that SotA can handle its corpse recruits in a more reasonable manner 

If thats what you want to do, you'd need to first add a way for lua to hook in before the original dialog is shown (to be replaced with your custom one), which is imo the more complicated part

**Comment by CelticMinstrel** [comment]
> which is imo the more complicated part

What's complicated about that, exactly…? Just find the place that currently calls the dialog and do something else instead, right?

Not entirely sure that's actually necessary though.

**Comment by CelticMinstrel** [comment]
> Is it possible with a modeless dialog (assuming we can get it working)?

Maybe, but that sounds like a strange way to do it…
