### ISSUE TITLE
Wesnoth Map Editor refuses to edit .mask files

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#8831]
### Game and System Information

- **Version:** 1.18

### Description of the bug

Terrain masks in Wesnoth are often saved with the .mask extension, which is used in mainline as well as in addons. For some reason in 1.18 the map editor refuses to open them, saying that only .map or .cfg files are allowed. Seems that's a recent change and .mask files were just forgotten when it was done
![изображение](https://github.com/wesnoth/wesnoth/assets/68666085/ebc159b3-88a3-4acc-856e-42fdaee7e361)

### Expected behavior

Allow to open .mask files in addition to .map and .cfg

### Additional context

In 1.16 the editor opened .mask files just fine

**Comment by Wedge009** [comment]
Introduced by Pent in 10997c39a3d559d699143f67e9ede7947e2193b3 (#7719)... but looks like it's already being taken care of.

**Comment by soliton-** [comment]
Yes, in 5491e48.
