### ISSUE TITLE
EI - 10. Dark Sanctuary - Owaec can go into the sanctuary

### ISSUE THREAD

**Issue by Earth-Cake** [wesnoth/wesnoth#8843]
### Game and System Information

- **Version:**1.18
- **OS:**Windows 11

### Description of the bug

When reaching the gate hexes, Owaec should always turn back after saying his line.
However, if Owaec crosses through a unit that is on a hex next to the gate hex, he will not go back to $x2, $y2 because that location is occupied by the unit, resulting in him staying inside of the gate and being able to move into the Sanctuary afterwards.

The replay of me reproducing the bug:
[EI-Dark Sanctuary replay Owaec bug.gz](https://github.com/wesnoth/wesnoth/files/15205168/EI-Dark.Sanctuary.replay.Owaec.bug.gz)
(A small note: in the replay, I was the one who moved Owaec outside towards the starting location in order to provide more examples of the bug occuring, but in every situation I was able to move him towards the Sanctuary. You can stop the replay to test it yourself.)

### Steps to reproduce the behavior

Place a unit next to the gates in 10. Dark Sanctuary after the gates have opened (it is easier to reproduce with 2 units next to one gate hex though).
Try to move Owaec towards the Sanctuary (into the area reserved for the eight units), but make sure that Owaec crosses through the hex with the unit.
Owaec will stay inside the hex and be able to move into the Reserved Area.

### Additional context

The issue is on this line:
https://github.com/wesnoth/wesnoth/blob/011e831171df64556645bf45905ef2ad5f3c9e8c/data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg#L941

**Comment by Wedge009** [comment]
@Dalas121

**Comment by Earth-Cake** [comment]
As far as I can see, there is no pretty solution to this issue, as the player can always crowd the space around with enough units to force Owaec to go into the Sanctuary.
My suggestions would either be to move Owaec to a fixed coordinate such as 42,21 (any hex far away from the gate area would work); or to later, before firing the `enter_dungeon` event, check for Owaec in this area and move him again.

**Comment by CelticMinstrel** [comment]
> My suggestions would either be to move Owaec to a fixed coordinate such as 42,21 (any hex far away from the gate area would work); or to later, before firing the `enter_dungeon` event, check for Owaec in this area and move him again.

Looks like it's already fixed, but my suggestion would've been to just swap Owaec with the unit he passed over.
