### ISSUE TITLE
In-game chat doesn't redraw over water when help is open

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#8845]
![water](https://github.com/wesnoth/wesnoth/assets/3030250/41996396-a445-4445-a152-c1ca62ed4493)

**Comment by Wedge009** [comment]
In 1.16.12 the chat text is wiped before the Help dialogue is displayed. I suspect the rendering overhaul leaves the chat text under the dialogue but the water animation (and presumably any animated hex) gets drawn over the chat text.

**Comment by Wedge009** [comment]
Confirming the aforementioned behaviour changes at 06254e5581cbb79b5eaf72bec0dbb3fc1566b7a4, the start of the rendering overhaul. It's not exactly a regression because the chat text simply wasn't shown previously.

**Comment by Wedge009** [comment]
@Vultraz I'm not in a position to test right now, but does 26b467e3901c16e0acdc81fb01a46b4731109896 resolve this issue as well?

**Comment by Vultraz** [comment]
No, this is unrelated.

**Comment by Wedge009** [comment]
Any resolution for this also needs to be back-ported.

**Comment by Wedge009** [comment]
It might be 'hacky', but it solves the immediate issue with messages being displayed under the Help dialogue and also seems to help with a bit of flickering I observed with water animations. So back-ported in 2f06922052126f040972dfea69d726bdac2d6b09.
