### ISSUE TITLE
apply_to=status add=unplagueable => status=not_living

### ISSUE THREAD

**Issue by white-haired-uncle** [wesnoth/wesnoth#8870]
### Game and System Information

- **Version:**
` v1.19.0-dev (ebf93c02bb4-Modified) `
- **OS:**
`Linux spartan 5.15.0-97-generic #107-Ubuntu`

### Description of the bug

Inside [unit][effect]apply_to=status, if you set add=unplagueable it will set status=not_living,unpoisonable,undrainable,unplagueable

I can set undrainable or unpoisonable or undrainable,unpoisonable but not unplagueable by itself or with one other, once you add unplagueable you get all of them plus not_living.  (actually I suspect unplagueable just causes not_living which causes the rest).

### Steps to reproduce the behavior

```
    [unit]
        side=3
        x,y={X},{Y}
        type={TYPE}
        generate_name=yes
        random_traits=yes
        gender={GENDER}
        [modifications]
            [object]
                [effect]
                    apply_to=image_mod
                    add="GS()"
                [/effect]
                [effect]
                    apply_to=resistance
                    replace=false
                    [resistance]
                        cold=-20
                        fire=-30
                        arcane=-10
                        blade=-30
                        pierce=-40
                        impact=-20
                    [/resistance]
                [/effect]
                [effect]
                    apply_to=status
                    add=unplagueable  # causes not_living and friends
                    #add=unpoisonable,undrainable,unplagueable
                [/effect]
            [/object]
        [/modifications]
    [/unit]

```

### Expected behavior

You should be able to set just unplagueable, I assume.

**Comment by ProditorMagnus** [comment]
`{TYPE}` is not defined, reproduction steps give error. We can assume this type by default has `unpoisonable,undrainable` status, so by adding third it is intended to get `not_living`.

**Comment by white-haired-uncle** [comment]
Strange, I tried building a simple example and it works okay.  However, in the original if I only set, for example, undrainable I would only get undrainable, or if I didn't set anything the unit wouldn't have any statuses so I know the type didn't have them.  Must be something else happening in that addon.
