### ISSUE TITLE
After sorting by level in the recall window recall or cancel leads to a crash

### ISSUE THREAD

**Issue by l-alcom** [wesnoth/wesnoth#8876]
### Game and System Information

- 1.18.0
- Mac OS 10.14.6 (Mojave)

### Description of the bug

After opening the recall dialog, here in the Two_Brothers campaign, and then sorting by level of the units recalling a unit or cancelling the recall leads to a crash. This happened also in at least one other campaign.

### Steps to reproduce the behavior

1. Open the game using the attached savefile
2. Open the recall window
3. Sort by level
4. Recall the first unit or cancel the recall

### Expected behavior

Expected the recall of the selected unit, not a crash.
[HdDF-La Poursuite-Sauvegarde automatique1.gz](https://github.com/wesnoth/wesnoth/files/15337522/HdDF-La.Poursuite-Sauvegarde.automatique1.gz)

**Comment by soliton-** [comment]
Already fixed in https://github.com/wesnoth/wesnoth/commit/39cc21db8eec293b2a7d07f861302b612691718a. Will be solved with 1.18.1.

Thanks for the report anyway!
