### ISSUE TITLE
EI: Dacyn Disappears Forever After Scripted Advancements If He Has Plague Staff Item Equipped

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8885]
### Game and System Information

- **Version:**1.18
- **OS:**ChromeOS/Debian

### Description of the bug

In Eastern Invasion, S14 The Drowned Plains and S16 Eleventh Hour, Dacyn switches unit type.

When he switches unit type with the Plague Staff item equipped, he disappears (doesn't trigger a loss).

Dacyn is an essential unit for the whole campaign.

### Steps to reproduce the behavior

1. Give Dacyn the Plague Staff Item
2.  Trigger either scripted advancement

### Additional context

Doesn't occur with the Baneblade Item, so it appears to be specific to the Plague Staff's unique effects.

Dacyn using the Plague Staff is also severely bugged in S17a: Dacyn becomes the player's leader (normally) but can't recall non-Undead units and loses the ability to recruit/recall if he drops the Staff.

It's a really terrible item to give Dacyn (Chaotic Mage of Light) anyway so he can just be disallowed from picking it up like the other Hero units. 

Picking up the Plague Staff doesn't trigger Dacyn's disappearance. 

Reported on Discord by MrPringles.

**Comment by Wedge009** [comment]
@Dalas121 FYI.

**Comment by Dalas121** [comment]
Yikes, that's a really serious bug. I'm guessing giving Dacyn the plague staff messes with upkeep too, though that's obviously not as major.

Dacyn has no in-game reason to ignore the plague staff so I would prefer to properly fix this, but given the complexity of the issue I think it's safest to just prevent Dacyn from picking it up in the first place.  PR created.

**Comment by Wedge009** [comment]
Regarding a story reason for Dacyn's refusal to use the plague staff - from what I've seen so far (yet to play the campaign properly), his alignment is ambiguous. While he's on a quest to obtain something dark, his remark about the plague staff could be interpreted as he's not fallen so far as to command necromantic forces. That is, his refusal could just add to the ambiguous nature of his plans.

Anyway, thanks for resolving so fast.

**Comment by IskarJarak01** [comment]
I had forgotten how specific the rejection message is: "I will not wield such a dark magical artifact, though I shall not begrudge its use by my companions." It really isn't ideal.

Dacyn's excuse for not picking it up could be that he'll need all of his strength and focus for the trials ahead / to wield the amulet. After Dacyn becomes a Fallen Mage, he could dismiss it as useless. This might require up to 3 lines: pre-finding the amulet, post-finding the amulet (unless there's a good line for both) and as a Fallen Mage. 

The other option is to allow Dacyn to wield the staff with some extremely hacky "fixes".
Just picking up the staff doesn't trigger the bug so for both advancements maybe check for the staff's presence, drop it, switch Dacyn's unit then automatically re-equip it. It's even worse for the Duel though: delete it before Dacyn becomes leader and place a copy on the ground?

(Upkeep doesn't seem to be bugged: I don't think the increased upkeep is applied because Dacyn is loyal.)

(I was poking around with the items a little more and Owaec can pick up the Baneblade (after Dark Sanctuary), but there's a comment in Dark Sanctuary that suggests he shouldn't be able to: "this is good for flavor, but also helps with balance. Vanguard + Baneblade would be way too strong".)

**Comment by Dalas121** [comment]
Perhaps a more generic rejection message?  The current item system doesn't support different rejection messages per-unit, and I think it's too risky to try and add that functionality at this point, since changes will be going straight into 1.18.1.

I'd considered using hacky "fixes", but am worried those would introduce additional bugs.  Hacky fixes unfortunately also wouldn't resolve the upkeep issue that I expect also happens.

I'm not seeing the baneblade message in the current version - where exactly is that?  That used to be an issue back in an older add-on version, but the baneblade got nerfed as part of the same add-on update that made items droppable so that comment (if it's still in the current version) is now obsolete.

**Comment by IskarJarak01** [comment]
A more generic rejection message would probably require dropping the reasoning ("I will not wield this artifact, though I shall not begrudge its use by my companions."). Most players obviously didn't give Dacyn the staff or the campaign would have broken. I'm not sure whether its better to keep the flavour and accept that it doesn't make sense for Daycn, but most players won't see it.

Disabling the item for Dacyn is definitely the right solution for 1.18x, though I can't reproduce / trigger an upkeep bug: the staff correctly doesn't increase upkeep when given to Dacyn or other loyal units. 

The comment is (or was) in 1.18's scenarios\10_Dark_Sanctuary.cfg, line 926.

**Comment by Dalas121** [comment]
`though I can't reproduce / trigger an upkeep bug: the staff correctly doesn't increase upkeep when given to Dacyn or other loyal units.`
Good to know, thanks.  There must be a check in there for loyal.

Looks like the comment is gone in master, so it must have been removed sometime since 1.18.0.
