### ISSUE TITLE
EI: In S16 Eleventh Hour, Decorative Allied Units (Civilians) Can Block Recruitment

### ISSUE THREAD

**Issue by IskarJarak01** [wesnoth/wesnoth#8886]
### Game and System Information

- **Version:**1.18
- **OS:**ChromeOS/Debian

### Description of the bug

Eastern Invasion S16 Eleventh features a number of allied civilian units that disappear during the AI's Turn 3. 
They move randomly and can move onto and block a castle hex belonging to one of the secondary keeps dotted around the map. 
The civilian units shouldn't be able to interfere with recruitment.
Anti-life civilians in the top-left and bottom right:
![Screenshot 2024-05-14 02 33 04](https://github.com/wesnoth/wesnoth/assets/81496259/9ea7b94e-e47f-4284-98e6-228ab198c020)

### Steps to reproduce the behavior

1. Start S16 Eleventh Hour and end turn
2. Civilians may move onto castle hexes
3. Reload the scenario save file and repeat until civilians block castle hexes

### Expected behavior

Civilians probably shouldn't be able to block castle hexes at all and definitely shouldn't block castle hexes at random.

**Comment by Wedge009** [comment]
I haven't replayed this campaign yet - is there something unique about the scenario that lends itself to this happening more than usual? I imagine this is something that could potentially occur in any scenario where there are allied units near the player's own keep. I don't know if the AI understands it should try to avoid allies' keep hexes - perhaps it is simply seeking hexes with desirable defence ratings?

**Comment by IskarJarak01** [comment]
It's specific to the scenario.

The Townsfolk units are controlled by a micro AI and are only present briefly for flavour. 

The randomness is due to whether the Townsfolk have the Quick trait or not. The problem Townsfolk seem to only be (29, 31) and (21, 20) if they spawn without the the Quick trait.
