### ISSUE TITLE
MP Campaigns: ``leader_lock=yes`` when no ``type=`` defined

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#8909]
### Game and System Information

- **Version:** 1.18

### Description of the bug

In MP campaigns by default you have ``faction_lock`` and ``leader_lock`` being yes. Let's suppose you want your MP campaign to be playable with any era, if you only add ``faction_lock=yes``. then the starting screen will be in a strange state where you can choose your faction but can't choose your leader, and when start the game, no leader is spawned and you lose. 

### Steps to reproduce the behavior

[Sample_MP_Campaign.zip](https://github.com/wesnoth/wesnoth/files/15414560/Sample_MP_Campaign.zip)

Can be reproduced in this example MP campaign

### Expected behavior

Either document it, or disable ``leader_lock`` if ``faction_lock`` is ``no``, or making it spawn the first leader of a chosen faction (it's usually Random for most eras)

**Comment by Discontinuum** [comment]
I think, maybe it's even not ``faction_lock`` but just ``leader_lock=yes`` without a predefined leader

**Comment by gfgtdf** [comment]
This is afaik intentional, by default campaign authors don't want the mp stuff to renadomly add a leader for a side, even if it doesn't have a leader defined, to change this behavior this `leader_lock` must be set to `no`.

We could disable `leader_lock` if `faction_lock` is `no`, but i'm not sure wheterh it would really make things to understand if the atttributes default values depend on each other

**Comment by gfgtdf** [comment]
i am also not sure whetehr the situation inthe first is that useless als it seems to be, umc authors wanting player only be able to change the recuitlist but not the leader unit could be useful in some situations.

**Comment by Discontinuum** [comment]
> i am also not sure whetehr the situation inthe first is that useless als it seems to be, umc authors wanting player only be able to change the recuitlist but not the leader unit could be useful in some situations.

I would certainly want to let this possibility be

**Comment by gfgtdf** [comment]
hmm yes then i think we should just document the current behavior better, that leader_lock really means "leader always as specified in the scenario wml, even if that means no leader"

**Comment by Discontinuum** [comment]
https://wiki.wesnoth.org/index.php?title=SideWML&type=revision&diff=73054&oldid=72396
