### ISSUE TITLE
editor: Save into addon when saving a scenario

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#8910]
### Describe the desired feature

When creating a scenario in the editor it asks for an addon but when then saving the scenario the save dialog starts out at editor/scenarios in userdata and not in the chosen addon.

**Comment by babaissarkar** [comment]
See if commit 64f136c02fbf310522df66bea983f19192f16ef4 in #8903 solves this.

**Comment by soliton-** [comment]
I can't test right now but that looks good.

**Comment by babaissarkar** [comment]
> I also noticed that even when you save the scenario in editor/scenarios the map file is saved in the addon and the editor can find it again when opening. However that is pretty confusing and the game does not expect that when checking custom scenarios under editor/scenarios. So you can't play the scenario then.

I'll check that.


> We should probably deprecate editor/scenarios since it's easy now to just make an addon, so it just adds confusion.

I agree.

**Comment by soliton-** [comment]
It's actually a bit odd that Save Scenario As saves the map as well.

I think it would make more sense if Save Map (just a button, ctrl+s) gets renamed to Save All or Save Scenario+Map or so and saves both. And then Save Map/Scenario As just save the map and scenario respectively.

**Comment by babaissarkar** [comment]
> I think it would make more sense if Save Map (just a button, ctrl+s) gets renamed to Save All or Save Scenario+Map or so and saves both. And then Save Map/Scenario As just save the map and scenario respectively.

Did that (Renamed to `Save`). Also, Save Scenario As is now only visible when the user is in Scenario editing mode.

**Comment by soliton-** [comment]
Would be good if this can be backported since the current behavior is very confusing.
