### ISSUE TITLE
editor: Pick proper dir and filename in Save Map/Scenario As dialog

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#8911]
### Describe the desired feature

1) Enter editor
2) New Scenario
3) Save Scenario As
4) Type in some name and save
5) Save Map As
Now you get the previous scenario filename in the dialog and if you do save you overwrite your scenario.

Similarly you get the map file name if you save as map first.

This is confusing and can lead to data loss if the user is not careful. Even if you change the filename you're saving to the wrong dir.

The save dialog should pick the proper dir to start with and even then it might be good to give an explicit warning if someone saves a map as .cfg or a scenario as .map and/or when they save them in the wrong dir (as much as the editor can tell, so just if the dir is named maps/scenarios). The wrong extension could perhaps even be completely forbidden.

**Comment by Wedge009** [comment]
On the directory aspect, #2807 seems related.

**Comment by babaissarkar** [comment]
@soliton- Please check if the latest commit in #8903 alleviates this somewhat?

> The save dialog should pick the proper dir to start with and even then it might be good to give an explicit warning if someone saves a map as .cfg or a scenario as .map and/or when they save them in the wrong dir (as much as the editor can tell, so just if the dir is named maps/scenarios). The wrong extension could perhaps even be completely forbidden.

Working on this part. Forbidding the extension completely should be much easier. Plus I can use my validation textbox idea (a textbox which shows check/cross marks based on whether the input is valid or not).

**Comment by babaissarkar** [comment]
@soliton-  Is b1d0a535a59e5059b34927ac9460dab12471a9f0 in #8903 enough to resolve this?

**Comment by babaissarkar** [comment]
> Is `input_name` the whole path? I think safer would be to just check the directory that is saved into. Not that we get confused by a user with "map" somewhere in their name or something.

`input_name` is the absolute, username-santized, cached path to the savefile.
Example : `/home/USER/.local/share/wesnoth/1.19/data/add-ons/TestAddon/scenarios/test_scenario.cfg`

I'll check the last directory.

> Does the user see some feedback on what is wrong? Can they override it?

No. What the code does is check the (cached) path and if it is empty or has 'maps'/'scenarios', it opens the file dialog into the default directory (which is the addon's scenario/map directory) with a blank filename.

> Using the correct starting dir to save to is also important. I forgot if you already added that in a different commit.

`Save Map As` opens into the addon's map directory (addon's scenarios directory for `Save Scenario As`) unless the user has already saved it somewhere else, in which case that directory is opened.

**Comment by babaissarkar** [comment]
> Ok, to pick the proper dir to start with I was just thinking to use `<addon dir>/maps` for `Save Map As` and `<addon dir>/scenarios` for `Save Scenario As`.

This already exists.
 
> The other logic would be to warn the user when they pick something that seems to make no sense. Like when they navigate to the scenarios dir from the Save Map As dialog, type in the file name and click `Save`. Or when they try to save a scenario in any dir with a `.map` extension. At that point there could be a warning dialog where they can save anyway though if they want.

Okay, will work on this one.

**Comment by CelticMinstrel** [comment]
Saving in the wrong directory should be allowed. Saving with the wrong extension should be forbidden.

**Comment by babaissarkar** [comment]
This is what I add in 9c65d1e0254077014d0ccb807cd7360fc0283258 :
![Screenshot from 2024-05-31 11-44-16](https://github.com/wesnoth/wesnoth/assets/8469888/77c25aed-1bbe-4cc5-b3a0-1c4193bb1815)

The example is from `Save Map As`, but it also appears for `Save Scenario As` with the corresponding extension.

**Comment by babaissarkar** [comment]
692924b31dbd9dd58ad4c4e0ba24d225935ac26f gives the user a warning the first they try to save a scenario in maps folder or vice versa. Pressing "Yes" saves anyway, "No" closes dialog.
![Screenshot from 2024-06-19 18-05-48](https://github.com/wesnoth/wesnoth/assets/8469888/f4c043bd-6f48-4802-9891-d3dc11774f59)

**Comment by soliton-** [comment]
Disabling saving until a name is given sounds good to me. I don't see a reason to auto generate a name.

**Comment by babaissarkar** [comment]
> Disabling saving until a name is given sounds good to me. I don't see a reason to auto generate a name.

I'm thinking about making the filename textbox something like this: ![validation_textbox](https://designmodo.com/wp-content/uploads/2021/03/image4.png)

**Comment by babaissarkar** [comment]
Commits 8eac37876f75fff2de7ab07abe6414b609d4653c and da83c9ae6a7cd18973742888ae99a424499b52db :

![Screenshot from 2024-06-20 18-57-03](https://github.com/wesnoth/wesnoth/assets/8469888/44511d7c-5820-486e-86fe-8b3a712fde8d)
![Screenshot from 2024-06-20 18-26-01](https://github.com/wesnoth/wesnoth/assets/8469888/f657d5a7-eb8c-4b4d-9d7b-4567a57050e2)

Extension checking is now file dialog's responsibility (since it already had extension info), so I'll remove that from the editor. Editor will now only be responsible for checking map/scenario folders.

**Comment by babaissarkar** [comment]
Anything else needs to be done as part of this issue?

**Comment by soliton-** [comment]
The extension is enforced now or can be overridden by the user? I think besides `.map` also `.mask` should be allowed.

Otherwise I think this looks to be resolved if the code gets merged.

**Comment by babaissarkar** [comment]
> The extension is enforced now or can be overridden by the user?
Cannot be overridden, so file cannot be save without correct extension.

> I think besides `.map` also `.mask` should be allowed.
For which dialog? `Save Map As` only, or somewhere else?

**Comment by soliton-** [comment]
Yes, when saving maps `.mask` would be same as `.map`.

**Comment by babaissarkar** [comment]
> Yes, when saving maps `.mask` would be same as `.map`.

Implemented in b3128ff3347d6a36497d52812bca1cf53dded68f. File Dialog now has support for multiple extensions (previous commit). Extension validation only done when saving files.
