### ISSUE TITLE
Make elevation terrain invisible on the minimap

### ISSUE THREAD

**Issue by amakriLexa04** [wesnoth/wesnoth#8924]
### Describe the desired feature

The new elevation tool looks very nice, but there can be problems with its implementation, which leads to a lot of elevated terrain. In the game itself, everything will look good, but on the minimap it will be a real nightmare. In addition, since the elevation is a purely visual feature, the player does not need to know where it's placed. Therefore, I suggest making it invisible on the minimap. I think this can be done by doing some manipulations with wesnoth/src/minimap.cpp
![Screenshot_1069](https://github.com/wesnoth/wesnoth/assets/165188749/b64860ee-a739-42e3-b174-c4679a162ff9)

**Comment by doofus-01** [comment]
I think this is fixed with [414e8ea](https://github.com/wesnoth/wesnoth/pull/9400/commits/414e8eae08b64b0cca691e009ac3651c27f94450)

**Comment by amakriLexa04** [comment]
Good to know, thank you for your work
