### ISSUE TITLE
Dialogs disappear instantly fairly frequently with 1.18

### ISSUE THREAD

**Issue by arobinson** [wesnoth/wesnoth#9001]
### Game and System Information

- **Version:** 1.18.0 (via steam)
- **OS:** Mac OSX 14.5 (23F79)

### Description of the bug

New to 1.18 (did not occur in 1.16), character messages, game messages and such disappear as soon as they appear, making it impossible for the user to read them. No events take place (extra key presses, mouse clicks etc), yet they go away.

I'd say anywhere from 25%-75% of the time I experience this

### Steps to reproduce the behavior

Just play the game. I am playing with the LotI mod, so not sure if that could be related. That author has items you can pick up. When you pick them up, he displays a description. That description often goes away instantly. I have seen it with normal character dialog too though.

### Expected behavior

Dialogs should be shown until dismissed

### Additional context

Origin bug reported on the LotI mod with a save game to reproduce:
https://github.com/Dugy/Legend_of_the_Invincibles/issues/820

**Comment by Pentarctagon** [comment]
Sounds like an instance of #8644, which should be fixed once the macOS package for 1.18.1 is uploaded (hopefully in the next couple days).

**Comment by arobinson** [comment]
I can't seem to produce it in 1.18.1, so yes I think that was the issue. I'm closing it as fixed. Thank you
