### ISSUE TITLE
THoT S05: Enemy leader (Masked Dwarf) portrait is shown cut off by the vertical crop

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#9008]
### Game and System Information

- **Version:** 1.18.1+dev (d5b726df6ecd107b8923e6a9a8bbc3785bf3a20a)

### Description of the bug

In the intro of S05 Fear, the portrait of the enemy leader is shown on the left side of the screen, facing left, but the image is obviously cropped assuming that it will be shown touching the right side of the screen.

### Steps to reproduce the behavior

1. Start S05 Fear. No need to play through to that point, can just start the campaign and then use debug to just directly to S05.
2. Move any unit east. No need to recruit, can just move the leader in turn 1.
3. Dialogue happens, including the portrait.

### Additional context

All of the enemy portraits in this campaign are drawn facing left, including Karrag and Elurin; they're all cropped assuming they'll be shown at the right hand side of the screen.

**Comment by HolyPaladin1** [comment]
Since 1.16 someone made some changes into THoT, I cannot remember any masked dwarf enemy leader in Fear in 1.18 version...

**Comment by stevecotton** [comment]
Current 1.18:

https://github.com/wesnoth/wesnoth/blob/d5b726df6ecd107b8923e6a9a8bbc3785bf3a20a/data/campaigns/The_Hammer_of_Thursagan/scenarios/05_Fear.cfg#L60-L62

**Comment by sevu** [comment]
```
[message]
    image_pos=right
    …
```
Using that in all places would work.

Another way would be to use the `~RIGHT()` IPF and maybe ~FL() though for some reason it is recommended to not use it anymore.

**Comment by Wedge009** [comment]
I think usually when speakers are alternating like that, the second speaker's portrait - in this case the masked dwarf - is placed on the right. I suppose no-one really thought the omission in this case looked bad enough to warrant reporting until now.

Looking through the portraits for this campaign, there's a mix of left- and right-facing portraits but in most cases the image is displayed appropriately, with the exception of the masked dwarf in this scenario as well as the first. The appearances of masked dwarves in scenario 9 (The Underlevels), as well as Karrag generally, are already aligned right with `~RIGHT()`.
