### ISSUE TITLE
config's automatic conversion of an attribute to bool gives unexpected behavior

### ISSUE THREAD

**Issue by Pentarctagon** [wesnoth/wesnoth#9009]
When using the automatic conversion of a config attribute to a bool, such as with:
```
bool b = cfg["some_attribute"]
```
The variable `b` will always be false regardless of the attribute's actual value. This is due to calling `operator int()` in `config_attribute_value.hpp` instead of `explicit operator bool()`, which results in using the `attribute_numeric_visitor` which uses the default value of 0 for bool values instead of its actual value.

Potential solutions mentioned by celticminstrel from IRC:
* Remove the explicit annotation on operator bool().
* Remove operator bool() entirely, and also remove operator int().
* Remove operator bool() and replace operator int() with a custom function using a different visitor that returns 0 or 1 if the value is a bool.

Any fix for this issue should also include test cases added to the boost unit tests for this behavior as well.

**Comment by gfgtdf** [comment]
instead of removing both operators we could probably also make the operator int explicit too,
