### ISSUE TITLE
Whirlpools are submerged in deep water

### ISSUE THREAD

**Issue by stevecotton** [wesnoth/wesnoth#9014]
### Game and System Information

- **Version:** 1.19.1+dev (no relevant commits since the 1.19.1 tag)
- Does not affect 1.18 (checked with a build that has no relevant commits since the 1.18.1 tag)

### Description of the bug

Part of a whirlpool is underwater. What's wrong with that is easier to explain with an image:
![image](https://github.com/wesnoth/wesnoth/assets/101462/5d92495d-f477-498d-91ae-95a28bdaab27)

It's visible in shallow water, and very obvious in deep water. These whirlpools are a scenery item rather than a terrain, and they're shown submerged.

### Steps to reproduce the behavior

2p Elensefar Courtyard has two whirlpools in the center, in shallow water.

HttT S15 Lost General has them in deep water.

### Additional context

The attached image shows a modified version of the you-can't-go-here overlay on the cave hexes, but that's not relevant to this bug.

**Comment by stevecotton** [comment]
Appears to be a general problem with `PLACE_IMAGE` looking the same as `PLACE_IMAGE_SUBMERGED`. The ship on HttT S04 Bay of Pearls is shown with water up to the masts.

**Comment by gfgtdf** [comment]
probably https://github.com/wesnoth/wesnoth/commit/9548f4c7b5c95acaa802457420afb8ab6207fe3b

**Comment by Wedge009** [comment]
#8789 is another issue caused by the hardware submerge.

I was playing 1.18.2 recently and whirlpools still show as intended.

**Comment by Wedge009** [comment]
Confirmed resolved. Thanks.
