### ISSUE TITLE
Plan Mode Enable/Disable Bug

### ISSUE THREAD

**Issue by MechanicalDragon963** [wesnoth/wesnoth#9018]
### Game and System Information

- **Version:** 1.18.0
- **OS:** Windows 10

### Description of the bug

After enabling plan mode 1 time, it becomes enabled by default even if I try do disable it. 

### Steps to reproduce the behavior

1. Enable plan mode.
2. Disable plan mode.
3. Restart Wesnoth and host the local mp game.

### Expected behavior

Plan mode should be disabled, but instead this, it becomes enabled by default.

**Comment by gfgtdf** [comment]
there is an option in the preferences to enable planning mode by default, but it shouldn't set itself, also iirc there were changed related to this in 1.18, So maybe you just accidentally enabled this in your preferences.

**Comment by MechanicalDragon963** [comment]
> there is an option in the preferences to enable planning mode by default, but it shouldn't set itself, also iirc there were changed related to this in 1.18, So maybe you just accidentally enabled this in your preferences.

You are right, that's my bad. I missed the preference. Thank you for answer!
