### ISSUE TITLE
Display multiple damage types

### ISSUE THREAD

**Issue by 2Redbeard** [wesnoth/wesnoth#9022]
### Game and System Information

- **Version:**
- **OS:**

### Description of the bug

In the new Eastern Invasion for item amulet, after you get captured and have to reclaim them didn’t seem to actually make damage into arcane, same if I dropped it and someone else picked it up.  Anyone else notice this?

### Expected behavior

Should continue to turn damage into arcane after your guys are capitonees and lose it temporarily

**Comment by newfrenchy83** [comment]
i no issue with it, unit retake item normally.

**Comment by newfrenchy83** [comment]
with what version of wesnoth you play

**Comment by newfrenchy83** [comment]
I think I understand what's wrong, one of these objects (Crystal Quiver) confers the arcane type to bows but not to other ranged attacks, if you try to take it back with a spear holder, it will only recover the ability illumination but not the arcane type because it is not an archer while Holy Amulet gives the arcane type to all the possessor's attacks. have you paid attention to the type of item collected and with which unit you take it?

**Comment by 2Redbeard** [comment]
Wesnoth is 1.18.1
Windows 11

I guess what I'm seeing is that the sign isn't changing, I am including some screenshots, it doesn't clearly label itself as changing on the main view, though if you go to the combat window, it shows the original damage type AS WELL AS arcane, and the damage amount reflects as arcane, which I don't think is supposed to happen.  So it works in a way, but doesn't display as I think it should, I"m pretty sure when I put it on the original owner earlier in the game (a Duellist), the damage insignia was arcane, as it should be and behaved as arcane damage
<img width="288" alt="amulet1" src="https://github.com/wesnoth/wesnoth/assets/163490140/e48188cb-0c1d-4284-8e34-2a1ea18a3378">
.  


<img width="140" alt="amulet4" src="https://github.com/wesnoth/wesnoth/assets/163490140/a7166dd8-72ad-4324-bb52-38a3d64c4719">
<img width="322" alt="amulet5" src="https://github.com/wesnoth/wesnoth/assets/163490140/278c183e-ff60-4e28-8de1-26e98a95dfa9">
<img width="312" alt="amulet6" src="https://github.com/wesnoth/wesnoth/assets/163490140/df864718-e89f-4472-9271-ef0914c00b9b">

**Comment by 2Redbeard** [comment]
aren't 2 damage types like that not supposed to be possible?

**Comment by knyghtmare** [comment]
dual damage type attacks are now a thing in 1.18.0

**Comment by 2Redbeard** [comment]
Interesting, didn't know that, so it just chooses what damage type is stronger in that fight?

**Comment by knyghtmare** [comment]
> Interesting, didn't know that, so it just chooses what damage type is stronger in that fight?

Yes

**Comment by newfrenchy83** [comment]
you said what amulet don't work, if you have speak of dual type showed i will explain it immediately, yes in 1.18 it is like this with [damage_type]alternative_type= and in 1.19.1 and beyond 'arcane' icon showed in sidebar along with other type.

**Comment by 2Redbeard** [comment]
So if you shoot a skeleton or a horseman with the dual damage bow, it'll do arcane to the skeleton and pierce to the horseman (the opposite would be dreadful).  That's okay, but there should be both icons for both damage types on the main display, not just one, otherwise it looks like it's dealing only one kind of damage.

**Comment by newfrenchy83** [comment]
> So if you shoot a skeleton or a horseman with the dual damage bow, it'll do arcane to the skeleton and pierce to the horseman (the opposite would be dreadful). That's okay, but there should be both icons for both damage types on the main display, not just one, otherwise it looks like it's dealing only one kind of damage.

this is fixed in 1.19.1 and later but can't be fixed in stable veersion because change of behavior. Try with 1.19.1.

**Comment by Wedge009** [comment]
If I understand correctly, the original report was a misunderstanding about whether or not the arcane damage type is applied when picking up the amulet (specific to EI campaign) and the discussion has now extended into how damage types are displayed to the player if there is more than one.

1.18
![image](https://github.com/wesnoth/wesnoth/assets/13679322/64080cb2-ceb8-435e-8728-1aa6a086ddea)

1.19
![image](https://github.com/wesnoth/wesnoth/assets/13679322/f96afe86-bd4c-45c3-a50a-71c8b52cdc62)

Given that this is resolved in master, the issue can be closed but I think this is something worth applying to stable as well so marking this specific to 1.18.

@newfrenchy83 It looks like the update was from your #8765 change. Is there anything really blocking this from being back-ported? CC: @soliton-

**Comment by 2Redbeard** [comment]
Yeah, looks like it has already been worked in, so can be closed

**Comment by soliton-** [comment]
> Given that this is resolved in master, the issue can be closed but I think this is something worth applying to stable as well so marking this specific to 1.18.

We could certainly show all alternative damage types in 1.18 as well if we consider that a bug fix. Changing what is displayed in the GUI is not going to cause OOS.

**Comment by newfrenchy83** [comment]
> > Given that this is resolved in master, the issue can be closed but I think this is something worth applying to stable as well so marking this specific to 1.18.
> 
> We could certainly show all alternative damage types in 1.18 as well if we consider that a bug fix. Changing what is displayed in the GUI is not going to cause OOS.

https://github.com/wesnoth/wesnoth/commit/57c8e0cce02bfd5849f67a4ba7576a41c14ed4dd is not only for GUI it's  why i can't backport to 1.18 because i push that too late

**Comment by soliton-** [comment]
Sure, it's not just picking a commit from master.
