### ISSUE TITLE
Character missing from font

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#9055]
https://github.com/wesnoth/wesnoth/blob/6812eac403982f82bdc4be0a4cf6c6b8cf235484/data/gui/widget/button_success.cfg#L250

The character ✔ is not in the used font. It's in all Dejavu Sans variants we ship though.

**Comment by Wedge009** [comment]
What is the used font? I'm guessing this is 'copy a full report here' button, but it seems to work fine for me on Linux.

**Comment by babaissarkar** [comment]
> What is the used font?

Wesnoth's default English font is Lato
> I'm guessing this is 'copy a full report here' button

Yes.
> but it seems to work fine for me on Linux.

In majority of cases, the platform's fontconfig (or its equivalent) should substitute that character from a font installed on the system that has the check character. However, PR #9056 safeguards against the edge cases where it doesn't.
