### ISSUE TITLE
[i] button in the leaderchoosing window only works correct when a unit's name is the same as its id.

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#9102]
### Game and System Information

- **Version:** 1.18

### Description of the bug

![изображение](https://github.com/user-attachments/assets/9a2081c8-387b-481c-b24a-fa9acb509abc)
This button, highlighted in red, works correctly only when a unit's name is the same as its id. When the unit's name is different from any id, the button is gray and inactive. If the name of the name is the same as the id of some other unit, it shows the help entry for this other unit.

### Steps to reproduce the behavior

[Leaderhelp_bug_Era.zip](https://github.com/user-attachments/files/16257568/Leaderhelp_bug_Era.zip) sample era to see the bug

The era contains five units, all of whom are custom liminal Naga Dirkfang:
the first one's id is "Naga DirkfangVS1", the name is "Peasant"
the second one's id is "Naga DirkfangVS2", the name is "Naga Dirkfang"
the third one's id is "Naga DirkfangVS3", the name is "Naga DirkfangVS3", also it has 111 hp
the fourth one's id is "Naga DirkfangVS4", the name is "Naga DirkfangVS1"
the fifth one's id is "Naga DirkfangVS5", the name is "Name Differs From Id"

1. install the era, go to Multiplayer > Local Game > choose this era with any multiplayer scenario
2. try to choose leader and click [i] for different leaders
3. for the first leader it will open the help entry for the human loyalist peasant
4. for the second one it will open the entry for the default neutral "Naga Dirkfang"
5. for the third one it will open the correct entry, with 111 hp
6. for the fourth one it will open the entry for our peasant naga, that has ``id=Naga DirkfangVS1``
7. for the fifth one the [i] button is inactive

### Expected behavior

The button is always active and shows the help entry for the corresponding unit

### Additional context

It seems the button's logic confuses names and ids and uses the unit's name as id to query the help entry

**Comment by Discontinuum** [comment]
When I switch to another non-English language, [i] is inactive for any unit, whose name was translated, even in the Default era.

**Comment by Pentarctagon** [comment]
Relevant line is https://github.com/wesnoth/wesnoth/blob/0f188acc9f2b4f6e36e9dfbcbe22db677cae8e9f/src/gui/dialogs/multiplayer/faction_select.cpp#L186
