### ISSUE TITLE
Provide valid WML in wesnoth -p output

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#9115]
### Describe the desired feature

Currently output has all keys quoted with usual `"`, which is not enough when text content contains `{}`, for example in mainline earliest failure is around line 30 with
```
[naming]
	bridge_name_generator=_"
		bridge_type=Bridge|Crossing
		main=$base {bridge_type}|$base{!}’s {bridge_type}
	"
```
where bridge_type define does not exist.

I think wesnoth -p should recognize that `{}` cause problems, and wrap those fragments in `<< >>`.

**Comment by soliton-** [comment]
See https://github.com/wesnoth/wesnoth/issues/7702

**Comment by soliton-** [comment]
As a note: the .plain output file contains the "raw" output of the preprocessor without any WML parsing. This means 1) it may or may not be valid WML (though on invalid WML it probably errors out before writing this file) 2) it may or may not be valid to preprocess it again. (In the case of the name generator example the input uses strong quotes so it can be preprocessed again.)
