### ISSUE TITLE
tree_view_node un/folding loses sync

### ISSUE THREAD

**Issue by white-haired-uncle** [wesnoth/wesnoth#9146]
### Game and System Information

- **Version:**
`Battle for Wesnoth v1.19.1+dev (e67a91caf22-Modified) x86_64`
- **OS:**
`Linux spartan 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Description of the bug

I have a modeless dialog with a tree_view.  Here the attacks (axe, shield) are the top level nodes, and the weapon specials are their children.  The shield is unfolded and will not (intentionally) change.  The label "Battle Axe" has a callback attached which toggles the folded/unfolded state.

This is the initial state.  The axe is folded.  
![01_folded](https://github.com/user-attachments/assets/90128eb9-5825-42e7-9007-08693d42f9fc)

I click on Battle Axe, and the node is unfolded.  Looks good so far.
![02_unfolded](https://github.com/user-attachments/assets/608a4e40-68f5-457c-baf5-059e68024fdc)

I click on Battle Axe again, and the node is folded.  I believe this is the step where things fall out of sync.  The specials disappear, but the node doesn't seem to "collapse".
![03_folded](https://github.com/user-attachments/assets/09af876f-7009-4095-aafd-25e9559baba2)

I click on Battle Axe again, and the node is unfolded.  Now the specials are displayed, but the node also collapses, so the axe specials and shield label/specials are written over each other.
![04_unfolded](https://github.com/user-attachments/assets/ae8cf79a-c7b7-48ed-84a8-3a9784af56ba)

I click on Battle Axe again, and the node is folded.  Again the specials disappear, but the node is expanded when it is supposed to be collapsed.
![05_folded](https://github.com/user-attachments/assets/91a316b8-72f3-4776-9981-8b05b799ff25)

I click on Battle Axe again, and the node is unfolded.  As you can see, the last two states repeat indefinitely.
![06_unfolded](https://github.com/user-attachments/assets/2152777b-79b9-49fb-bc97-7cdec30b69c8)

So it seems to me the first time I fold the node, the "collapse" action fails, leaving it in the wrong state.  After that, the collapse state toggles correctly, and therefore always remains inverted.

### Steps to reproduce the behavior

I'll need some advice on how to provide a proper test case.  While playing with this, I've just hijacked the debug clock with my own dialog.  Honestly, I have pretty much no idea what I'm doing, this is my first dialog/tree_view in cpp.

But for now...

My callback:
```
void sidebar::toggle_fold(tree_view_node& node)
{
        LOG_DP << "You touched my axe!";
        if(node.is_folded()) {
                LOG_DP << "   The axe node was folded.";
                node.unfold(false);
        } else {
                node.fold(false);
                LOG_DP << "   The axe node was unfolded.";
        }
        std::string s = node.is_folded() ? "folded." : "unfolded.";
        LOG_DP << "    Now it is " << s;
}
```

And a snip of the log just to show that the un/fold process seems to be correct:
```
20240730 01:15:15 info display: You touched my axe!
20240730 01:15:15 info display:    The axe node was folded.
20240730 01:15:15 info display:     Now it is unfolded.
20240730 01:15:24 info display: You touched my axe!
20240730 01:15:24 info display:    The axe node was unfolded.
20240730 01:15:24 info display:     Now it is folded.
20240730 01:15:33 info display: You touched my axe!
20240730 01:15:33 info display:    The axe node was folded.
20240730 01:15:33 info display:     Now it is unfolded.
20240730 01:15:46 info display: You touched my axe!
20240730 01:15:46 info display:    The axe node was unfolded.
20240730 01:15:46 info display:     Now it is folded.
```

### Additional context

This might be related to another issue I raised with the lua API.  I need to investigate.

**Comment by white-haired-uncle** [comment]
#8689 was the one I was thinking of.  Doesn't look quite the same, but it rhymes.

**Comment by white-haired-uncle** [comment]
On a lark, I tried it and... the problem goes away if I use fold(true) and unfold(true).  

In my case, the children don't un/fold, so I don't think it should make a difference whether I pass true or false.  Seems like a useful clue though.

**Comment by white-haired-uncle** [comment]
Updated wesnoth `Battle for Wesnoth v1.19.2+dev (64caa4acda3-Modified) x86_64` and copied my tree_view into gui_test_dialog.  Now it acts like #8689.

![gtd1](https://github.com/user-attachments/assets/466f3035-767d-4f15-963e-d148c101ed54)
![gtd2](https://github.com/user-attachments/assets/217d1e2f-3899-4a5b-a8c5-fb08a2140de0)

I wonder if they are the same issue, just manifesting differently (perhaps because this time I'm using modal -- like I was in lua???).

[gtd_modal.tar.gz](https://github.com/user-attachments/files/16434797/gtd_modal.tar.gz)

**Comment by Wedge009** [comment]
If both issues are using the tree-view mechanism, then it sounds to me like it's another case of #8689.
