### ISSUE TITLE
SotA: Bat can overwrite units in S2

### ISSUE THREAD

**Issue by Gothyoba** [wesnoth/wesnoth#9150]
### Game and System Information

- **Version:** 1.19.2, also reproduced in 1.14.13

### Description of the bug

In SoTA S2 (Dark Business) you can find a bat in the central village (not the guardhouse). This bat will initially appear on the coordinates 16,7 before escaping. If another unit is stationed on the coordinates 16,7 the bat will completely and permanently delete it. It is possible to lose the scenario by accident if you move Ardonna to 16,7 and then move one of your undead units to the village.

### Steps to reproduce the behavior

- Move a unit to coordinates 16,7 on SoTA S2. Alternatively, you can try your best to lure one of the guards there.
- Move another unit to the village. This has to be the first time the village is entered, otherwise the bat won’t appear.
- The unit on coordinates 16,7 will be deleted.

### Expected behavior

The bat should probably move to another spot where no unit is present.

**Comment by Wedge009** [comment]
Looks like this was added to 1.15 in #3869 and 1.14 in 3a9f8153bacda22574a3ea4edd514ff97c97d040.

The specific code is:
https://github.com/wesnoth/wesnoth/blame/1ba0168eb3e3a74a0505416d6b53072cbd4c90dd/data/campaigns/Secrets_of_the_Ancients/scenarios/02_Dark_Business.cfg#L373-L382

The way the scenario is set-up, I think most players would move Ardonna directly to the village on 15,7 first. It's unlikely - but obviously not impossible - to encounter the situation you describe. This is not a unique problem, however - I'm not sure how this is solved in other instances... though I can't recall other instances of this issue in other scenarios...

**Comment by soliton-** [comment]
Simplest would be to specify `find_vacant` presumably with `check_passabilty` (even if it won't do much for a bat).

Nicer would be to look for a vacant hex first so the `[move_unit_fake]` goes to the right destination.

**Comment by Wedge009** [comment]
I didn't even know those were options for `[unstore_unit]`. https://wiki.wesnoth.org/DirectActionsWML

Doesn't look like there's an existing function to provide vacant co-ordinates, though.
