### ISSUE TITLE
Weapon object missing properties

### ISSUE THREAD

**Issue by hladkyjakub** [wesnoth/wesnoth#9169]
### Game and System Information

- **Version:** 1.18.0

### Description of the bug

Lua and WFL weapon objects do not contain all the properties of a weapon.

### Steps to reproduce the behavior

In Lua console

```
function _G.f()
	unit = wesnoth.units.get("unit") or wesnoth.units.create{ type = "Dwarvish Fighter", side=1, id="unit" }:to_map(10,10)
	unit = wesnoth.units.get("unit")
        print(unit.attacks[1].__cfg.max_range)
        print(unit.attacks[1].max_range)
end
f()
```

In Formula command line: `unit_at(loc(10,10)).attacks[0].max_range`

### Expected behavior

Lua and WFL weapon objects should contain all properties, accessible in the config of the weapon.

**Comment by hladkyjakub** [comment]
Solved :D

**Comment by CelticMinstrel** [comment]
So those were the _only_ missing properties?

**Comment by hladkyjakub** [comment]
Probably not, but I'm unsure about it.

**Comment by hladkyjakub** [comment]
> So those were the _only_ missing properties?

...
Do you have some particular on your mind?

**Comment by CelticMinstrel** [comment]
No, I don't have anything in mind.

**Comment by hladkyjakub** [comment]
So...
If no-one knows what's missing, if something...
What do you expect me to do?

**Comment by CelticMinstrel** [comment]
I was only asking if those were the only missing things that you noticed. If there's something missing that you don't know about, we'll deal with it when we think of it, but if you _noticed_ something else then we might as well deal with it sooner rather than later.
