### ISSUE TITLE
Start game hotkey ctrl+g is missing from preferences

### ISSUE THREAD

**Issue by ProditorMagnus** [wesnoth/wesnoth#9175]
### Game and System Information

- **Version:** 1.18.2
- **OS:** windows

### Description of the bug

![image](https://github.com/user-attachments/assets/4d404231-e038-4acc-ad03-cd42c446f33f)

![image](https://github.com/user-attachments/assets/68fa7b24-c785-4b7f-99b6-5035eed9f5e7)

**Comment by babaissarkar** [comment]
This happened because I bypassed the Hotkey system altogether when adding that hotkey, so naturally it's not visible in the preferences.

**Comment by babaissarkar** [comment]
You can notice the same behavior with the Load Unit Type button in the Unit Type Editor.
