### ISSUE TITLE
World Conquest fails to start

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#9190]
### Game and System Information

- **Version:** Battle for Wesnoth v1.19.2+dev (31658e2587d-Modified) arm64 (Modified is a lie, it's added because of untracked files for some reason)
- **OS:** macOS

### Description of the bug

> Setting mode to 1399x943
Checking lua scripts... ok
test_nplayers	nil
...s/World_Conquest/lua/map/scenario_utils/bonus_points.lua:389: bad argument #-1 to 'filter' (string expected, got nil)	stack traceback:
	[string "..."]:8: in function <[string "..."]:8>
	[C]: in field 'filter'
	...s/World_Conquest/lua/map/scenario_utils/bonus_points.lua:389: in function '.world_conquest_tek_bonus_points'
	...aigns/World_Conquest/lua/map/postgeneration/1A_Start.lua:150: in local 'fun'
	campaigns/World_Conquest/lua/map/wct_map_generator.lua:56: in upvalue 'run_postgeneration'
	campaigns/World_Conquest/lua/map/wct_map_generator.lua:73: in local 'mapgen_func'
	campaigns/World_Conquest/lua/map/main.lua:122: in function '.wc_ii_generate_scenario'
	(...tail calls...)
	[C]: in function '.xpcall'
	[string "..."]:8: in main chunk
nil
20240810 20:28:14 error mapgen: Error when running lua_map_generator create_scenario.
The generator was: World Conquest 1p
bad return value:
  expected a config (table), found a nil
20240810 20:28:14 error general: Map generator error: Error when running lua_map_generator create_scenario.
The generator was: World Conquest 1p
bad return value:
  expected a config (table), found a nil

### Steps to reproduce the behavior

Select Multiplayer -> Local Game -> Multiplayer Campaigns -> World Conquest

### Expected behavior

World Conquest starts without error.

**Comment by CelticMinstrel** [comment]
Sounds like it's probably related to #8366

**Comment by gfgtdf** [comment]
The referenced line is 
https://github.com/wesnoth/wesnoth/blob/31658e2587d1a0ba230d2dcf562c5369ffb5b045/data/campaigns/World_Conquest/lua/map/scenario_utils/bonus_points.lua#L389

it creates a filter that uses f.find_in()

**Comment by gfgtdf** [comment]
This line 

https://github.com/wesnoth/wesnoth/blob/31658e2587d1a0ba230d2dcf562c5369ffb5b045/src/scripting/lua_terrainfilter.cpp#L481

also pushes nil on the lua stack, when its only supposed to check in that case.

**Comment by gfgtdf** [comment]
I'm curious where the `[string "..."]:8: in function <[string "..."]:8>` in the stacktrace comes from, does anyone know ?

**Comment by CelticMinstrel** [comment]
Could it be referring to [here](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg#L210)?

**Comment by gfgtdf** [comment]
Quite likely, but then why is its twice in the stack, once at the top and once at the bottom?

**Comment by CelticMinstrel** [comment]
> This line [...] also pushes nil on the lua stack, when its only supposed to check in that case.

So could the fix be to add a pop here?

https://github.com/wesnoth/wesnoth/blob/31658e2587d1a0ba230d2dcf562c5369ffb5b045/src/scripting/lua_terrainfilter.cpp#L484

> Quite likely, but then why is its twice in the stack, once at the top and once at the bottom?

That… I can't explain…

**Comment by gfgtdf** [comment]
> So could the fix be to add a pop here?

That could work, changing the `-1` to a `-2` in the next line might also work.

**Comment by Wedge009** [comment]
>     (Modified is a lie, it's added because of untracked files for some reason)

Not necessarily a lie - try making sure the sub-modules are up-to-date as well.

**Comment by Wedge009** [comment]
> Sounds like it's probably related to #8366

Confirmed it's 19f3682bdf0962af0a5afdb1a53ab9d49b345b9c that causes this.

**Comment by Pentarctagon** [comment]
@CelticMinstrel can you look into fixing this then?

**Comment by CelticMinstrel** [comment]
Probably, unless @gfgtdf wants to do it?

**Comment by soliton-** [comment]
Would be good to get this fixed or revert 19f3682 for 1.19.4.

**Comment by gfgtdf** [comment]
Do we have a plan on when 1.19.4 happens?

**Comment by gfgtdf** [comment]
Anyways I committed the suggested change via my phone, so it's not really tested, I don't really have doubts that my change fixes a bug in the code, but still it would be nice if someone could verify whether it actually fixes the given case in this report.

**Comment by Wedge009** [comment]
I'm not sure what that change is supposed to do but at 3af690331a5, I can start a 1-player WC game without apparent issue.

**Comment by gfgtdf** [comment]
Very good, thank you
