### ISSUE TITLE
Inconsistent volume handling after #9151

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#9199]
### Game and System Information

- **Version:** `master` (1.19.2+dev) after 9821e2037b5500314233fbd0bc662420a33f3655
- **OS:** Linux/X11, but I expect this to be cross-platform.

### Description of the bug

After #9151 was merged, the volume handling seems inconsistent. My `preferences` file for 1.18 and 1.19 has the following volume settings:
```
sound_volume=4
music_volume=4
bell_volume=2
UI_volume=4
```
In 1.18 and 1.19 up until before #9151 was merged, I have the following:
![image](https://github.com/user-attachments/assets/0071a162-4079-4b77-aebe-a2f98e67a2e5)

From #9151 onwards, I have:
![image](https://github.com/user-attachments/assets/ee2630f5-4338-4b66-808b-56855256898d)

It's not just a visual difference, the interface sounds (notably the 'click' sound effect on buttons) are awfully loud.

### Steps to reproduce the behavior

Without changing the volume settings in `preferences`, try a build before #9151 (eg `1.19.2` tag) and observe a difference in volume in current `master` build.

### Expected behavior

Volume handling to remain unchanged.

### Additional context

#9151 was by @Pentarctagon, with @CelticMinstrel, @gfgtdf, and @Vultraz as reviewers. I'm not sure what's gone wrong here, so I've reported it - hopefully it's straightforward to fix.

**Comment by Pentarctagon** [comment]
That's weird, since there was no change at all to the code for that preference in #9151.

**Comment by Wedge009** [comment]
Pretty sure I bisected correctly, so maybe there's some unintended side-effect?

**Comment by Pentarctagon** [comment]
Are you sure it's not caused by cce8c7a41062171c4d63334e4342f1bc5922460a?

**Comment by Pentarctagon** [comment]
Given the position of the slider, it looks like maybe it's not that it got louder but it reset to the default volume?

**Comment by gfgtdf** [comment]
My  guess is that here

https://github.com/wesnoth/wesnoth/pull/9151/files#diff-e992183c5db3874dd8255531f6d516b600c3f9d5fa969de178d53b3c81664fbaR266

 "UI_volume" was changed to "ui_volume"

i'd will probably work again once you set the slider to the desired value.

**Comment by Wedge009** [comment]
I did wonder about cce8c7a41062171c4d63334e4342f1bc5922460a but it was definitely 9821e2037b5500314233fbd0bc662420a33f3655 that I found. I suppose it's possible that it's showing as the default volume - changing `UI_volume` to `ui_volume` seemed to restore my volume preferences.

I wonder if there's some way to read both `UI_volume` and `ui_volume` but only write to `ui_volume`?

**Comment by Pentarctagon** [comment]
Ah, yeah, that makes sense actually. I do also see both the uppercase and lowercase attributes in my preferences file.

It would certainly be possible to add compatibility code for the old preference name, but I'm not sure if it's really worth it for this particular preference.

**Comment by Pentarctagon** [comment]
That'd be one option, yeah.

**Comment by Wedge009** [comment]
> It would certainly be possible to add compatibility code for the old preference name, but I'm not sure if it's really worth it for this particular preference.

It might not be, but consider how the eventual migration from 1.18 to 1.20 might be received by users. Notwithstanding that the `preferences` file is changing location anyway.

**Comment by Wedge009** [comment]
> My guess is that here
> 
> https://github.com/wesnoth/wesnoth/pull/9151/files#diff-e992183c5db3874dd8255531f6d516b600c3f9d5fa969de178d53b3c81664fbaR266
> 
> "UI_volume" was changed to "ui_volume"

I was looking for the change - it was in the not-rendered-by-default-because-too-large difference of `preferences_list.hpp`. I notice the other breaking change is `UI_sound` -> `ui_sound`, which I expect is the toggle switch for interface sounds.
