### ISSUE TITLE
[drawing] with empty [draw] causes assertion failure

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesnoth#9214]
### Game and System Information

- **Version:** 1.18.2+dev
- **OS:** macOS Sonoma

### Description of the bug

It is possible for Wesnoth to crash to desktop due to an assertion failure that can be easily triggered via the Lua API by using `gui.show_dialog` with a dialog definition that contains a `[drawing]` with an empty `[draw]` child. Note that there **must** be a `[draw]` child, otherwise the game will instead crash to the main menu since it explicitly checks for one.

```
Assertion failed: (!draw.empty()), function builder_drawing, file drawing.cpp, line 115.
```

### Steps to reproduce the behavior

1. Edit `data/campaigns/tutorial/gui/character_selection.cfg` such that under the Select Character heading there is a row with the following contents:
```
        [row]
            [column]
                [drawing]
                    [draw][/draw]
                [/drawing]
            [/column]
        [/row]
```
2. Start the game and launch the Tutorial campaign.
3. Click past the Welcome message in order to proceed to the character selection screen.
4. Kaboom.

### Expected behavior

1. How about not crashing.

**Comment by Vultraz** [comment]
Fixed in c5e0b3eefb8a4193e052ac70650be381cc6ed679, if someone wants to backport.
