### ISSUE TITLE
Liberty S1, dialogue item

### ISSUE THREAD

**Issue by Konrad22** [wesnoth/wesnoth#9241]
### Describe the desired feature

When Harper picks up the pack/bag item, she says 'I could use it to carry _more_ rocks.', and her ranged _damage_ increases by one. I'd say the wording suggest that the amount of hits would increase. So my suggestion is to change the wording to 'I could use it to carry _heavier_ rocks.', which is more in line with the gameplay.
[Liberty-The Raid-Auto-Save5.gz](https://github.com/user-attachments/files/16730097/Liberty-The.Raid-Auto-Save5.gz)
(Save file to check the dialogue, version 1.18.2)

**Comment by Wedge009** [comment]
https://github.com/wesnoth/wesnoth/blob/d4b2d151ce3413f8765530c1de0a3a8109dda534/data/campaigns/Liberty/scenarios/01_The_Raid.cfg#L414-L417

I'm fine with game-play and lore/wording not always aligning perfectly, but it doesn't take a lot of effort make it align better in this case.
