### ISSUE TITLE
Multiplayer Random Maps Crash the Game

### ISSUE THREAD

**Issue by Gothyoba** [wesnoth/wesnoth#9275]
### Game and System Information

- **Version:** 1.19.3, **not** replicated in 1.18.2 or 1.14.13
- **OS:** Windows

### Description of the bug

When opening a random map in the local multiplayer menu, the game gets stuck on Starting game... for a few seconds before crashing. This happens consistently every single time I do this.

### Steps to reproduce the behavior

1. Click Multiplayer and then Local Game from the main menu and select a random map (all random maps crash)
2. Create a game on whichever random map you chose.
3. The game will most likely crash.

### Expected behavior

It should not crash and allow you to play the map.

### Additional context

This seems to be something with 1.19, as the feature works fine on 1.18.2 for me.

**Comment by soliton-** [comment]
Already fixed with cff5630.

**Comment by gfgtdf** [comment]
i'm suprised that this fixes the issue, i thought most random mp maps don't use lua.

**Comment by CelticMinstrel** [comment]
All content uses Lua, since most of the WML tags are implemented in Lua. In this case, using `[set_variable]formula=` would probably have triggered the issue, for example.

**Comment by gfgtdf** [comment]
> All content uses Lua, since most of the WML tags are implemented in Lua. In this case, using [set_variable]formula= would probably have triggered the issue, for example.


but then its still complteley unrelated to random maps, especialy since our random maps https://github.com/wesnoth/wesnoth/blob/a8d68165ec0e5ab79f884c0b070dfe2a5eb8a076/data/multiplayer/scenarios/Random_Scenario.cfg#L8 dont use any event code at all.

**Comment by CelticMinstrel** [comment]
Yeah, I don't know how exactly it gets to this point in the random map.
