### ISSUE TITLE
add_item/add_item_of_type issues

### ISSUE THREAD

**Issue by white-haired-uncle** [wesnoth/wesnoth#9283]
### Game and System Information

- **Version:**
1.19 at least
- **OS:**
Linux

### Description of the bug

optional position argument is 0 based (at least for multipage), should be 1 based

add_item_of_type (at least) returns position -1 always

I don't think add_item returns anything for position, or uses optional position argument (untested)

### Additional context

I want to add lua support for menu_button (to start), but there are issues with add_item*.  Opening this ticket to track them.  I know I discussed some of these with @gfgtdf and @CelticMinstrel, probably on the forums, but I can't find the conversation. 

In addition to the above, some questions to start:

1) From the comments, it appears specifying position = 0 will prepend.  I'm not sure if this is because it's currently 0 based or not.  If it was 1 based (which I think it should be to be consistent with how things like selected_index, and more importantly accessing items by index), then specifying position = 0 == specifying position = 1.  Not really an issue, but interesting.

2) It looks like position = -1 means append, so I assume -2 means 'before the last item'

3) I'm not sure bounds checking exists.  Per @CelticMinstrel, trying to write out of the valid range (where valid includes append/prepend) should raise an error, not simply append/prepend.  Currently, it blows up.

4) I'm not sure any error checking exists in the underlying members (not necessarily a problem, basically a reminder to myself to check)

5) Is it safe to return the expected position?  By this I mean, if the user does not provide a position argument to add_item, and therefore it is supposed to append, is it okay to just return the (new) number of items?  I don't like this, but it's better  than what currently exists.  Likewise, if user says 'insert at position 2', and 2 is valid, is it okay to expect that the item really is now position 2, or does this need to be checked? 

6) At a minimum, we could easily check the number of children and ensure it increase by 1 after adding the item.  Can't imaging why it wouldn't, but...

more to follow, I'm sure

**Comment by Vultraz** [comment]
#8516 addresses this, I think?

**Comment by CelticMinstrel** [comment]
> 5\. Is it safe to return the expected position?  By this I mean, if the user does not provide a position argument to add_item, and therefore it is supposed to append, is it okay to just return the (new) number of items?

Pretty sure there's no other valid answer? If you appended, the new index is the new length of the list.

> 3\. Per @CelticMinstrel, trying to write out of the valid range (where valid includes append/prepend) should raise an error, not simply append/prepend.  Currently, it blows up.

The valid range from the C++ perspective is (0, list.size()). That means it's (1, list.size()+1) in Lua, and it means that the index you pass becomes the new index of the item. In other words, when you specify an index explicitly, you should get that same index back from the return value.

**Comment by white-haired-uncle** [comment]
> #8516 addresses this, I think?

Yeah, looks like it hits one of the issues.  I searched issues, didn't think to search PRs.

> Pretty sure there's no other valid answer? If you appended, the new index is the new length of the list.

Yes, if you appended, which is what all the underlying add functions do today when not given a position (or -1).  Since they don't return a position, we can either trust that they continue to append in the future, or find a way to check for ourselves (maybe?) if we want to be really paranoid.  I'm just checking that "trust it" is acceptable.

> In other words, when you specify an index explicitly, you should get that same index back from the return value.

But if you specify list.size()+13...  currently, it hangs for a minute or so and then bombs.  While just appending would be an alternative (and returning the actual new position), for no particular reason I prefer to catch it an throw an error.

**Comment by white-haired-uncle** [comment]
Note to self (mostly):  This is not the first time I've wanted to get a count of container.items in lua.  Maybe there's another way I'm missing, but I don't see why having an item_count attribute (or item/page/node_count depending on object) wouldn't be a bad idea.

For example, I'm currently testing adding items using various positions.  I scroll through them using a slider.  Be nice to be able to set slider.max_value = mp.page_count.

**Comment by gfgtdf** [comment]
> but I don't see why having an item_count attribute (or item/page/node_count depending on object) wouldn't be a bad idea.

Some widgets have that

https://github.com/wesnoth/wesnoth/blob/8fc55ee10609aad799dda3d4543bdcb10630b3aa/src/scripting/lua_widget_attributes.cpp#L379

> https://github.com/wesnoth/wesnoth/pull/8516 addresses this, I think?

Iirc (i know i coudl just look at it :/) the last state was:
- positive indicies shoudl behave just as table.insert
- we  are unusure whether we still want to suopport the "negative indicies count form the end" logic.

**Comment by white-haired-uncle** [comment]
I wonder how hard it would be to support `#my_container` vs `my_container.item_count`.  I don't really care that much, but I'm curious.  I can add item_count where it's missing easy enough.

FWIW, I have negative indices working for mp/tv/tvn.  The one I'm not sure about is 0, which is currently append, though I think either prepend or error makes more sense.

**Comment by CelticMinstrel** [comment]
> I wonder how hard it would be to support `#my_container` vs `my_container.item_count`.

This is pretty easy to do, I think. I'd say it's preferred, but existing cases of `item_count` also shouldn't be removed.

**Comment by Vultraz** [comment]
Since #8516 has been merged, can we close this?

**Comment by white-haired-uncle** [comment]
I think so.  I still want to add item_count, but the `#syntax` is going to take me a while to figure out, and really isn't that important anyway.
