### ISSUE TITLE
Holy potion items are invisible

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#9305]
### Game and System Information

- **Version:** 1.19.3+dev (adef779e-Clean)
- **OS:** linux

### Description of the bug

Holy potion items are not visible in campaigns. A simple test case of
```
[item]
    x,y=2,2
    image=items/holy-water.png
    submerge=1
[/item]
```
works though so it seems related to the `OBJ_POTION_HOLY_ALT` or probably the `PICKUPPABLE_ITEM` macro.

### Steps to reproduce the behavior

1. Start the campaign Heir to the Throne
1. Go to scenario 09_The_Valley_of_Death
1. Observe no item visible on 5,23 for example

### Expected behavior

A holy potion icon (items/holy-water.png) should be visible on the map.

**Comment by newfrenchy83** [comment]
it's related to submerge=1 attribute, if a remove this Hoy potion is anew visible

**Comment by newfrenchy83** [comment]
i don't know why submerge=1 hidden item on ground, then what its must be in water only.

**Comment by newfrenchy83** [comment]
@Vultraz @soliton- tihsis the https://github.com/wesnoth/wesnoth/commit/26b467e3901c16e0acdc81fb01a46b4731109896 commit who is origin of this issue,when i revert potion is visible

**Comment by newfrenchy83** [comment]
in https://github.com/wesnoth/wesnoth/commit/26b467e3901c16e0acdc81fb01a46b4731109896#diff-c69d99f823238fb59e4c6efdf3a9b5563ad606396fb51bb644871ba129454fa5R2873 ovr_sub > 0.0, it is the good value because submerge=1 not ignored?

**Comment by soliton-** [comment]
Ok, I did suspect the submerge part but it did work properly in the simple test I mentioned. Though my test was on top of water which might be relevant.

**Comment by newfrenchy83** [comment]
> Ok, I did suspect the submerge part but it did work properly in the simple test I mentioned. Though my test was on top of water which might be relevant.

i tested in water and is visible but not in the ground, the code don't make diffrence in terrains.

**Comment by newfrenchy83** [comment]
i find ter_sub not specified in conidtions, i will fix that.
