### ISSUE TITLE
"Load turn" menu option is available in network multiplayer, the player who chooses it disconnected immediately

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#9308]
### Game and System Information

- **Version:** 1.18.2

### Description of the bug

In MP you can choose "Load turn" and load some turn as you can in SP. If you do this, you are immediately disconnected from the MP server and continue the game locally
![изображение](https://github.com/user-attachments/assets/978b1e60-ae4a-4441-bec3-047200b3d143)
![изображение](https://github.com/user-attachments/assets/6f80fcd3-3005-4aa1-905a-0d17c9306670)

### Steps to reproduce the behavior

1. Open two windows of BfW and log in to the MP server (either local or official)
2. Start some game
3. At some point click Menu > Load Turn > Load Turn N
4. The loader continues the game locally, other people see he's disconnected

### Expected behavior

I think in 1.16 this option didn't show up when you were connected to the MP server, however it should be available if you play MP locally (Multiplayer > Local Game

**Comment by knyghtmare** [comment]
@gfgtdf

**Comment by gfgtdf** [comment]
hmm yeah kinda likely to be my fault will look at t when I back home

**Comment by gfgtdf** [comment]
Iirc In 1.16 the load tun button in networked multiplayer had the same effect as the" replay turn" has button in 1.18. I think in 1.18 we split these I to two different button

**Comment by Discontinuum** [comment]
Indeed in 1.16 load turn showed replay and then returned to the game. The client didn't get disconnected after it
