### ISSUE TITLE
`https://addons.wesnoth.org/1.19/` webpage does not load images in core.

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#9310]
See Screenshot:
<img width="608" alt="Screenshot 2024-09-07 at 2 02 36 PM" src="https://github.com/user-attachments/assets/8c40daa6-09be-4a1c-8004-f7d541ede9b3">

It seems only URI images are loaded.

**Comment by Pentarctagon** [comment]
@soliton- could you look into this?

**Comment by soliton-** [comment]
Fixed with 8122924.
