### ISSUE TITLE
Rebuid unit function

### ISSUE THREAD

**Issue by hladkyjakub** [wesnoth/wesnoth#9314]
### Describe the desired feature

Get function to rebuild an unit, replacing current best option, which consists of giving unit an object, and removing it immediatly.
```
wesnoth.wml_actions.object({id="rebuid_help",take_only_once=false,{"filter",{id=u.id}}})
wesnoth.wml_actions.remove_object({object_id="rebuid_help",id=u.id})

**Comment by CelticMinstrel** [comment]
I believe this will do the trick:
```lua
function wesnoth.units.rebuild(self)
    self:transform(self.type)
end
```
Or possibly this:
```lua
function wesnoth.units.rebuild(self)
    self:advance(false, false)
end
```
Feel free to open a pull request to add one of those to `data/lua/core/units.lua`. I would merge it immediately (assuming whitespace check passed).

**Comment by hladkyjakub** [comment]
> ```lua
> function wesnoth.units.rebuild(unit)
>     wesnoth.units.to_map(unit.__cfg, unit.x, unit.y)
> end
> ```

This one doesn't rebuild the unit, not allways at least, that's why this FR was created.

> Feel free to open a pull request to add one of those to `data/lua/core/units.lua` (with a documentation comment above it). I would merge it immediately (assuming whitespace check passed).

I wouldn't require something, I can simply code for my add-on. That's afterall what I do now. I thought of cpp way, as those two options, you've listed both have units rebuild only as a side effect.

(But thanks for those, seems better than rebuild I use now)

**Comment by CelticMinstrel** [comment]
> This one doesn't rebuild the unit, not allways at least, that's why this FR was created.

When does it not rebuild?

**Comment by hladkyjakub** [comment]
> When does it not rebuild?
I have a guide to reproduce, I can break it down, but it's better for demonstration imho.
(Unit has 10 bonus max HP, should have 99 bonus max HP)
1. Into Lua console:
```
wesnoth.wml_actions.object({id="hitpoints_bonus",{"effect",{apply_to="hitpoints",increase_total=10}},{"filter",{}}})
local u=wesnoth.units.find_on_map({})[1]
cfg=u.__cfg
wml.find_child(wml.find_child(wml.get_child(cfg,"modifications"),"object",{id="hitpoints_bonus"}),"effect",{apply_to="hitpoints"}).increase_total = 99
wesnoth.units.to_map(cfg)
local mu=wesnoth.units.find_on_map({})[1]
print("current unit should have hitpoints increased: "..wml.find_child(wml.find_child(wml.get_child(mu.__cfg,"modifications"),"object",{id="hitpoints_bonus"}),"effect",{apply_to="hitpoints"}).increase_total)

**Comment by gfgtdf** [comment]
The first one of celmins suggestion would work though, I think world conquest also used that to rebuild units

**Comment by hladkyjakub** [comment]
That's nice workaround, ngl :D
But bad mainline code.

**Comment by CelticMinstrel** [comment]
It's not a workaround. I'm pretty sure we explicitly document somewhere that it's expected.

**Comment by hladkyjakub** [comment]
> It's not a workaround. I'm pretty sure we explicitly document somewhere that it's expected.

You do something extra this way, all I ask for is to not even attend to do something extra. I see no reason why this approach would be any better than creating new method for unit in cpp, based on existing cpp code.

**Comment by CelticMinstrel** [comment]
What extra?

**Comment by hladkyjakub** [comment]
> What extra?

Transforming the unit, obviously.
:/
Theres no point in continuing this argument, clearly, you don't will to change your mind.

**Comment by CelticMinstrel** [comment]
> Transforming the unit, obviously.

The process of transforming the unit to a new type is _precisely_ the process of rebuilding the unit. Transforming it to its current type is _exactly_ rebuilding it with no changes. It's not doing something extra. That's what rebuilding _is_.

**Comment by hladkyjakub** [comment]
Okay...
Does to_map use transform?

**Comment by CelticMinstrel** [comment]
No. If you pass a WML table to `to_map`, it creates an _entirely new_ unit. If you pass a _unit_ to `to_map`, it won't rebuild the unit at all.

**Comment by hladkyjakub** [comment]
> No. If you pass a WML table to `to_map`, it creates an _entirely new_ unit. If you pass a _unit_ to `to_map`, it won't rebuild the unit at all.

You've tryied the code, I've sent?
I create entitely new unit there from WML table , and object take no effect.

**Comment by CelticMinstrel** [comment]
I'm saying that `to_map` does not rebuild the unit. It creates a new unit. I don't know if serializing and recreating the unit is _supposed_ to be equivalent to rebuilding it, so I have no idea if that's a bug.

**Comment by hladkyjakub** [comment]
Jup.
I was just curious.
