### ISSUE TITLE
multi_page::remove_page doesn't appear to account for page

### ISSUE THREAD

**Issue by white-haired-uncle** [wesnoth/wesnoth#9323]
I haven't tested this yet, working on something else and don't want to get distracted but also don't want to forget to check this, and perhaps generator_->delete_item(page) will just ignore this, but...

Setting/reducing the count to get_page_count() doesn't take into account page > 0.

https://github.com/wesnoth/wesnoth/blob/5c9065eb7eb92950ccdf7234aa86c7220fbf75e1/src/gui/widgets/multi_page.cpp#L75-L90

**Comment by Vultraz** [comment]
I'm not sure I understand the issue here. What is the expected behavior?

**Comment by white-haired-uncle** [comment]
```
 	if(!count || count > get_page_count()) { 
 		count = get_page_count(); 
```

If count==0, remove all pages to the end.  If the user wants to remove more pages than there are, reduce the count to the number of pages.

Seems fine when we're starting the remove at index 0.  But at any other position there won't be enough pages to remove.

It's possible that generator_->delete_item won't have a problem with that, but then why did we reduce the number of pages to begin with?  I'd expect to see something more like:

```
if(!count || (page + count) > get_page_count()) { 
    count = get_page_count - page;
```

**Comment by white-haired-uncle** [comment]
yeah, it fails

`wesnoth: src/gui/widgets/generator_private.hpp:587: void gui2::generator<minimum_selection, maximum_selection, my_placement, select_action>::delete_item(unsigned int) [with minimum_selection = gui2::policy::minimum_selection::one_item; maximum_selection = gui2::policy::maximum_selection::one_item; my_placement = gui2::policy::placement::independent; select_action = gui2::policy::select_action::show]: Assertion `index < items_.size()' failed.`
