### ISSUE TITLE
Search filter is case-insensitive only for ASCII characters

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#9328]
### Game and System Information

- **Version:** 1.18.2
- **OS:** Ubuntu 20.04

### Description of the bug

When you search for a save by its name, in English it's case-insensitive. Which is very logical. But for some reason in Russian it requires a verbatim inclusion, strictly case-sensitive

### Steps to reproduce the behavior

![image](https://github.com/user-attachments/assets/b031fcc2-0ac6-4ea6-8b94-19ac1d2c3fa8)
Here I search for Spartan with a different case of English letters and for Ход (it means "Turn" in Russian). It finds it when verbatim
![image](https://github.com/user-attachments/assets/78377030-51f8-4187-ab74-0c418088dde1)
now for ход (the first letter not capitalized) it finds nothing

### Expected behavior

Search is case-insensitive for all languages that have a notion of a letter case

**Comment by gfgtdf** [comment]
We should also review all other usescases of utils::chars_equal_insensitive, for our code it should probably never be used

**Comment by Wedge009** [comment]
Would the general summary 'Search filter is case-insensitive for ASCII characters only' be more appropriate?

https://github.com/wesnoth/wesnoth/blob/47642719bf4e5519945f99d579c926d43725a04d/src/utils/general.hpp#L23
It looks like [tolower](https://en.cppreference.com/w/cpp/string/byte/tolower) only uses whatever the 'C locale' is, as defined on the system.

**Comment by Pentarctagon** [comment]
Would `utf8::lowercase()` be more appropriate? (in unicode.cpp)

**Comment by Wedge009** [comment]
I had just noticed soliton's remark and was trying to find what `utf8::lowercase()` was. If it's something we already have in Wesnoth code it seems a straight forward implementation is to switch to that instead.

**Comment by Wedge009** [comment]
Ah, found it:
https://github.com/wesnoth/wesnoth/blob/47642719bf4e5519945f99d579c926d43725a04d/src/serialization/unicode.cpp#L50-L68

Curiously, there's also this in `gettext.cpp`:
https://github.com/wesnoth/wesnoth/blob/47642719bf4e5519945f99d579c926d43725a04d/src/gettext.cpp#L409-L419
It's not clear to me what - if anything - it's doing beyond `tolower()` already does.

**Comment by Wedge009** [comment]
Looks like `std::search` requires the predicate to accept individual elements which, in this case, are the individual characters of the string. `utf8::lowercase` accepts an entire string. Would it make sense to replace `tolower` with `utf8::lowercase`? I'm just wondering about the overhead of creating a new string object for every character comparison - it might not be much in the overall processing of Wesnoth but I also note some users play on very low-power machines (judging by past issues reported with CPU usage).

**Comment by soliton-** [comment]
Just lowercase the strings first.

**Comment by Wedge009** [comment]
I feel silly for not thinking of that. So in the context of the game load dialogue's use, it would be a matter of running `utf8::lowercase()` on `games_[i].name()` and `word` before running the `str::search`? And removing the reference to `utils::chars_equal_insensitive`?

**Comment by soliton-** [comment]
Not sure if it's really useful to use std::search. I'd just use string's find.

**Comment by CelticMinstrel** [comment]
> Looks like `std::search` requires the predicate to accept individual elements which, in this case, are the individual characters of the string.

Note: We use UTF-8, so elements are not necessarily characters. They could be part of a character. For the purposes of search, this mostly doesn't matter, but I think it does mean you can't solve things with a case-insensitive comparator – if it's comparing half of an upper-case Cyrillic character, how can it transform it to lowercase without knowing the other half? You would need to use UTF-32 for this to work.

So I guess the options are "lowercase first" or "convert to UTF-32 first", and the former seems easier.

> Not sure if it's really useful to use std::search. I'd just use string's find.

I think the two are almost exactly equivalent, aren't they? And we're not searching long documents here so the efficiency boost of using a better searcher is probably negligible.

**Comment by Wedge009** [comment]
I'm not sure if `utf8::lowercase()` is doing what it's supposed to do (or maybe I'm using it wrong). I applied the following to `menu_items.cpp` for the unit/label search.

```
diff --git a/src/menu_events.cpp b/src/menu_events.cpp
index 056cabf01db..dc80ebbb9b5 100644
--- a/src/menu_events.cpp
+++ b/src/menu_events.cpp
@@ -72,6 +72,7 @@
 #include "savegame.hpp"
 #include "scripting/game_lua_kernel.hpp"
 #include "scripting/plugins/manager.hpp"
+#include "serialization/unicode.hpp"
 #include "synced_context.hpp"
 #include "units/unit.hpp"
 #include "units/types.hpp"
@@ -1386,25 +1387,23 @@ void menu_handler::do_search(const std::string& new_search)
                        loc.y = (loc.y + 1) % pc_.get_map().h();
 
                // Search label
+               const std::string& last_search_text = utf8::lowercase(last_search_);
                if(!gui_->shrouded(loc)) {
                        const terrain_label* label = gui_->labels().get_label(loc);
                        if(label) {
-                               std::string label_text = label->text().str();
-                               if(std::search(label_text.begin(), label_text.end(), last_search_.begin(), last_search_.end(),
-                                                  utils::chars_equal_insensitive)
-                                               != label_text.end()) {
+                               const std::string& label_text = utf8::lowercase(label->text().str());
+                               if(label_text.find(last_search_text) != std::string::npos) {
                                        found = true;
                                }
                        }
                }
+
                // Search unit name
                if(!gui_->fogged(loc)) {
                        unit_map::const_iterator ui = pc_.get_units().find(loc);
                        if(ui != pc_.get_units().end()) {
-                               const std::string name = ui->name();
-                               if(std::search(
-                                                  name.begin(), name.end(), last_search_.begin(), last_search_.end(), utils::chars_equal_insensitive)
-                                               != name.end()) {
+                               const std::string& name = utf8::lowercase(ui->name());
+                               if(name.find(last_search_text) != std::string::npos) {
                                        if(!gui_->viewing_team().is_enemy(ui->side())
                                                        || !ui->invisible(ui->get_location())) {
                                                found = true;
```

Case-insensitivity still applies to plain Latin characters. But creating labels for `Ö`/`ö` and `É`/`é`, the search appears to remain case-sensitive. I confirm the output of, for example, `utf8::lowercase("É")` is still `É`.

**Comment by soliton-** [comment]
I suppose locale is not properly taken into account. Since `translation::ci_search` exists might as well use that.

**Comment by Wedge009** [comment]
I only just worked out `ci` means case-insensitive...
