### ISSUE TITLE
[BUG] Micro AI `recruit_random` Does not work anymore

### ISSUE THREAD

**Issue by knyghtmare** [wesnoth/wesnoth#9345]
### Game and System Information

- **Version:** 1.19.3+dev
- **OS:** Windows 10 (msys2 compiler)

### Description of the bug

![image](https://github.com/user-attachments/assets/2189ac06-898c-4c13-a849-f5df8443199e)

### Steps to reproduce the behavior

```
[micro_ai]
            side=2
            ai_type=recruit_random
            action=add
            skip_low_gold_recruiting=no
        [/micro_ai]
        [micro_ai]
            side=3
            ai_type=recruit_random
            action=add
            skip_low_gold_recruiting=no
        [/micro_ai]
```

### Expected behavior

There are no Lua Errors and the MAI works as intended.

### Additional context

Seems it broken when a lot of Lua changes happened...

**Comment by CelticMinstrel** [comment]
I can see what the issue is. The `location_set` code does something a little bit stupid. Shouldn't be hard to fix, once I figure out how…

**Comment by stevecotton** [comment]
Does this affect 1.18? I don't see any relevant changes to location_set since 1.19 branched...

**Comment by CelticMinstrel** [comment]
The cause of this would've been a change to the recruit AI, not to location_set – probably my big Lua PR that addressed deprecated things project-wide.
