### ISSUE TITLE
SoF S7 Outriding the Outriders: Lua error at start

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#9360]
### Game and System Information

- **Version:** 1.19.4
- **OS:** Linux/X11, though I don't expect this to be relevant.

### Description of the bug

Starting Sceptre of Fire S7 results in the following error:

```
error scripting/lua: lua/wml-tags.lua:194: bad argument #3 to 'newindex' (Table expected)
stack traceback:
        [C]: in metamethod 'newindex'
        lua/wml-tags.lua:194: in local 'cmd'
        lua/wml-utils.lua:145: in field 'handle_event_commands'
        lua/wml-flow.lua:5: in function <lua/wml-flow.lua:4>
        [C]: in ?
```

### Steps to reproduce the behavior

Debug-choose-level will result in an instant game over because there's no 'alanin' unit to unstore, but the Lua error may still be there. Alternatively just go to the previous scenario and complete it.

### Expected behavior

No Lua error.

### Additional context

The error seems to be introduced in cb1853b4bc1c754841bb17efe16e7c1706ddc164 (#9340) by @CelticMinstrel.

@Pentarctagon Not sure if this warrants postponing 1.19.4 release.

**Comment by CelticMinstrel** [comment]
Looks like there are two possible fixes.

1. Logically speaking, I don't think it makes sense for recruit to me nil? It's a list, so having nothing to recruit should be an empty list, shouldn't it? Therefore, change line 194 to `team.recruit = nil`.
2. If we think it's that important to accept nil, change line 334 and 335 of lua_team.cpp to use a `utils::optional`.

It would be nice if we can get an overview of how many people actually assign nil in add-ons, but I'm not sure how easy that is to track down. Maybe a search for `recruit\s*=\s*nil` won't have that many false positives…? But also note that the documentation never states it can take nil.

**Comment by soliton-** [comment]
> Maybe a search for `recruit\s*=\s*nil` won't have that many false positives…?

No relevant hits in 1.16/1.18 or 1.19 addons.


> Therefore, change line 194 to `team.recruit = nil`.

data/lua/wml-tags.lua:194 already assigns nil. Perhaps you meant assigning `{}`.

**Comment by Wedge009** [comment]
So is the issue something affecting this scenario because of its design? I only reported this one because this is the one I encountered. It's possible there are other official campaigns also affected - right now, thinking of towards the end of Descent into Darkness where Malin becomes a lich... but then he might be able to recruit later in the same scenario, I can't remember. Similarly, I recall Delfador journeying through a couple of scenarios solo in Delfador's Memoirs.

**Comment by CelticMinstrel** [comment]
Presumably the scenario is affected because the recruit list is cleared, and the implementation of `[disallow_recruit]` was doing something that wasn't officially supported.

**Comment by white-haired-uncle** [comment]
I see this also trying to start WC with any (I tried 3) scenario

```
20240930 12:22:53 error scripting/lua: lua/wml-tags.lua:194: bad argument #3 to 'newindex' (Table expected)
stack traceback:
    [C]: in metamethod 'newindex'
    lua/wml-tags.lua:194: in field 'disallow_recruit'
    campaigns/World_Conquest/lua/era/era.lua:71: in upvalue 'init_side'
    campaigns/World_Conquest/lua/era/era.lua:300: in upvalue 'fcn'
    lua/on_event.lua:36: in function <lua/on_event.lua:33>
```
