### ISSUE TITLE
Add a link to the game manual in-game

### ISSUE THREAD

**Issue by CelticMinstrel** [wesnoth/wesnoth#9369]
The game manual isn't currently very discoverable. I think there should be a button in-game that opens it, maybe in Help or the About dialog.

I'm not sure if the manual is installed in all distributions. The link could optionally link to an online copy of the manual if a local copy can't be found.

**Comment by stevecotton** [comment]
Why would a user want to read the manual instead of reading the same information in the in-game help?

The in-game help should be improved too, but that doesn't seem a reason to link to the external manual.

**Comment by CelticMinstrel** [comment]
Maybe they'd prefer to read it in a browser. Maybe they'd even like to print it out as an external reference. (I don't think that's very likely, but you never know.) The manual exists, so it should be exposed… unless we want to actually delete the entire manual, but I don't think it's bad to have documentation in another format.
