### ISSUE TITLE
Better error message for ActionWML [unit] with invalid type 

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#9382]
![unknown-lua](https://github.com/user-attachments/assets/a283596c-e93c-4ae0-8d0a-8331f2a0a19c)

Needs a clear error message instead. It is triggered by:
```
[unit]
    type=nonexistant_unit
```

Tested in 1.18 and master.

**Comment by Wedge009** [comment]
It wasn't clear to me at first, but presumably the 'non-existent unit' type just needs to be anything that's not a valid, recognised type. Similarly for #9383.

**Comment by CelticMinstrel** [comment]
Is this using system Lua or submodule Lua? I seem to recall something similar to this being a downside of the system Lua PR.

**Comment by Wedge009** [comment]
I wasn't aware it was possible to choose - wouldn't Wesnoth use what it was built with?

**Comment by sevu** [comment]
It uses system Lua.

With scons, it is possible to use it by setting `system_lua=True`

**Comment by CelticMinstrel** [comment]
> I wasn't aware it was possible to choose - wouldn't Wesnoth use what it was built with?

Yes, it's chosen at build time.

**Comment by soliton-** [comment]
This does not happen with lua as a submodule.

**Comment by soliton-** [comment]
Actually this is a duplicate of #8847.

**Comment by Wedge009** [comment]
Well spotted.
