### ISSUE TITLE
Better error message for ActionWML [allow_recruit] with invalid type

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#9383]
![allow_recruit](https://github.com/user-attachments/assets/f66ce224-661f-4935-9039-18b48b90a407)

triggered by
```
[allow_recruit]
    type=nonexistant_unit
```

This is an internal error message of the [allow_recruit] tag. It does not the give information that this occurred in the [allow_recruit] tag.

**Comment by CelticMinstrel** [comment]
At least it gives you enough information to figure out that's where it came from, unlike #9382.

**Comment by soliton-** [comment]
> I would like to take this issue.

Feel free to just work on it and open a pull request once you have something.

**Comment by dnew0101** [comment]
Submitting a PR right now!

**Comment by Wedge009** [comment]
This may be connected with #8847 as well.

**Comment by soliton-** [comment]
No, this is just about the lua code not augmenting the error with something about `[allow_recruit]`. Which as celmin said is not that difficult to figure out if you look at the line number the stack trace shows. Perhaps we could also improve the stack trace itself by mentioning in what function the mentioned lines are.

**Comment by CelticMinstrel** [comment]
Well, since it's an error in a WML tag, it should print a WML error, not a Lua error. The implementation of `[allow_recruit]` probably needs to call `wml.error` under some condition. Might even need a pcall.
