### ISSUE TITLE
I cannot connect to extension servor

### ISSUE THREAD

**Issue by newfrenchy83** [wesnoth/wesnoth#9388]
### Game and System Information

- **Version:**master
- **OS:**windows10

### Description of the bug

when i try to connect to addon servor i had the error message below:

"error general: An error due to possibly invalid WML occurred
The error message is :
Mandatory widget 'main_stack' hasn't been defined.
 
When reporting the bug please include the following error message :
Condition '!must_exist || result' failed at ..\..\src/gui/widgets/widget.hpp:742 in function 'find_widget'."

### Steps to reproduce the behavior

Load wesnoth,
clik on add_on button.

### Expected behavior

the game must connect to servor.

**Comment by newfrenchy83** [comment]
> What version of Wesnoth? At what commit (if you built it yourself)? What's the wesnoth window size?

the last commit in master branch build with mingw, window size greater what 1280*1024, else the game froze.

**Comment by Pentarctagon** [comment]
@Vultraz @babaissarkar I can reproduce this, any idea what might have caused it?

**Comment by babaissarkar** [comment]
> @Vultraz @babaissarkar I can reproduce this, any idea what might have caused it?

once again, the find_widget refactor

**Comment by Pentarctagon** [comment]
Sorry if it's been brought up already, I must have missed it.

**Comment by babaissarkar** [comment]
> Sorry if it's been brought up already, I must have missed it.

Not directly related, but my guess is that it's caused by the same PR that caused https://github.com/wesnoth/wesnoth/pull/9390.

**Comment by newfrenchy83** [comment]
Iretry with https://github.com/wesnoth/wesnoth/commits/master/ but without changes
