### ISSUE TITLE
World Conquest: in eras with summon-like abilities (recruiting outside of keep), summoning happens twice

### ISSUE THREAD

**Issue by Discontinuum** [wesnoth/wesnoth#9441]
### Game and System Information

- **Version:** 1.18.*

### Description of the bug

Some popular eras like the Era of Magic or the Great Steppe Era have units that can recruit out of keep, on an adjacent hex. In EoMa it's the "summons" ability some units have, in GSE it's units of the Northern Triumvirate faction that can build constructions on adjacent hexes.

In 1.18 what happens is that if you try summon a unit/construct a building, it does so twice. And gold is deducted two times.
![image](https://github.com/user-attachments/assets/d3b7dddc-7dbd-4bd6-940d-7260d2702c2c)
on the image I summoned only one water elemental, but the second one appeared as well. Also a warning about "last_selected_unit" appeared after the second summoning occured

### Steps to reproduce the behavior

1. Start a WC game with either EoMa or GSE
2. In EoMa use debug to get EoMa_Summons_Master or EoMa_Infernal_Vortex. In GSE pick the Northern Triumvirate faction, almost any their unit can build
3. Click on an adjacent hex near the summoner/builder and try to summon/build something
4. It will happen twice

### Expected behavior

Summoning/building should occur only once

### Additional context

In 1.16 it worked fine without any bugs
If you try to build/summon on the very first turn, it will summon a unit, open the WC Invest windows (just like it should when you recruit/recall for the first time), and after you pick your bonuses the second summoning happens

**Comment by ProditorMagnus** [comment]
If you use debug you accept to get unintended behaviour.

With non-debug verification of getting grand summoner legally, summon works as intended.

**Comment by Discontinuum** [comment]
Hm, sorry, indeed I confused things, I tested with my fork, hands just automatically picked it. WC with EoMa it works fine. With GSE it throws an error and building just doesn't work. In my fork I got the same error, kinda fixed it by returning on nil (https://github.com/Discontinuum/Invincibles_Conquest/commit/dbe1a4cbe7a9a32397731897f75013da909db006 ) but got doubled building instead
![image](https://github.com/user-attachments/assets/f9225a46-e133-4b17-94ea-68aa0bfc0cbe)

**Comment by ProditorMagnus** [comment]
Sounds like https://github.com/wesnoth/wesnoth/pull/9231

**Comment by gfgtdf** [comment]
yes that seems likely, if someone has the time, it woudl be nice if anyone could checke whether it still hppens with latest 1.18 for example https://github.com/wesnoth/wesnoth/actions/runs/11193473424/artifacts/2019152310

**Comment by gfgtdf** [comment]
@Discontinuum can you test whether  it still happens with wesnoth Wesnoth 1.18.3 ?

**Comment by Discontinuum** [comment]
Sure, I'll test it when I get some free time

**Comment by Discontinuum** [comment]
@gfgtdf I've tested on Wesnoth 1.18.3, seems it's been fixed, thanks a lot!
