### ISSUE TITLE
WML \n support

### ISSUE THREAD

**Issue by hladkyjakub** [wesnoth/wesnoth#9491]
### Describe the desired feature

In WML strings I really lack the option to create new lines, like Lua allows you, with \n instead of "
".

**Comment by CelticMinstrel** [comment]
…well, I really don't see much point in this, but I guess there's no reason to close it either.

**Comment by soliton-** [comment]
We're not going to change WML syntax when it worked fine for decades to be able to write a character two ways... As you already said you can use Lua if for whatever reason it is important to you to write a newline as `\n`.

**Comment by hladkyjakub** [comment]
Bruh

**Comment by CelticMinstrel** [comment]
You can also define a macro if you don't like putting literal newlines in:
```
#define NL

#endif
```

And use it like this: `some_key = "Long Text{NL}More Long Text"`

Note that this macro can only be used in _quoted_ text.

**Comment by hladkyjakub** [comment]
But if WML can support pango markup, what's the deal with propper \ support?
That's something that is supported by every language I know. (Console, Lua,c++)

**Comment by soliton-** [comment]
I'm not sure what you mean by WML supporting pango markup. You can put a string of pango markup in certain attributes in the WML document and the engine will treat it as pango markup just like you can put WFL or Lua or a myriad of mini languages in the right attribute in the right tag and the engine will treat it as documented. You can also put syntax errors (not WML syntax errors of course but WFL/Lua/whatever) in all those places and the WML will be parsed just fine and you'll only get an error once the specific attribute is actually processed in the engine.

Unsurprisingly all those things did not even exist when WML was designed and none of them needed changes in WML syntax. Also WML is clearly not similar to other general purpose programming languages like Lua and even then requiring support for backslash escapes to be a proper language or something is a weird metric.

**Comment by CelticMinstrel** [comment]
There are plenty of languages that don't use `\n` as a newline. Certainly there are a lot of languages that _do_, but that alone is not a reason for all languages to do the same thing.
