### ISSUE TITLE
gettext domains: wesnoth-editor vs wesnoth-lib

### ISSUE THREAD

**Issue by Wedge009** [wesnoth/wesnoth#9492]
The editor source files seem to use a mix of `wesnoth-editor` and `wesnoth-lib` domains. I suppose it's not a big deal, but I noticed at least one duplicated string (I was thinking that 'dirs' should be explicitly spelled out as 'directories' for clarity).

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/gui/dialogs/editor/custom_tod.cpp#L178

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/gui/dialogs/editor/edit_unit.cpp#L320

Looking at master at e6d5100924a6a568776943727b97cdb70b2bb73e, I see the following apparently editor-related files using the `wesnoth-lib` domain:

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/editor/palette/tristate_button.cpp#L16

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/gui/dialogs/editor/edit_label.cpp#L16

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/gui/dialogs/editor/edit_pbl.cpp#L15

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/gui/dialogs/editor/edit_pbl_translation.cpp#L15

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/gui/dialogs/editor/edit_scenario.cpp#L16

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/gui/dialogs/editor/edit_side.cpp#L16

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/gui/dialogs/editor/edit_unit.cpp#L18

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/gui/dialogs/editor/generator_settings.cpp#L15

https://github.com/wesnoth/wesnoth/blob/e6d5100924a6a568776943727b97cdb70b2bb73e/src/gui/dialogs/editor/tod_new_schedule.cpp#L18

Should any/all of these be switched to `wesnoth-editor`? I don't know how, if at all, any changes here might be impacted by #9299 or vice-versa.

**Comment by babaissarkar** [comment]
Relevant but not exactly related: https://github.com/wesnoth/wesnoth/pull/8731#issuecomment-2329015122

**Comment by Wedge009** [comment]
Thanks. I'm guessing that's what #9299 is referring to.

**Comment by CelticMinstrel** [comment]
This is a ridiculous mess… if there's a "wesnoth-editor" textdomain, you'd think it should include the editor strings, which would mean that this change should've been the opposite. But on the other hand we seem to have a convention that ll the GUI2 dialogs use "wesnoth-lib".

**Comment by Vultraz** [comment]
That’s not from any established convention, as far as I know. It just happened from people copy-pasting existing dialog files.

**Comment by Wedge009** [comment]
> This is a ridiculous mess… if there's a "wesnoth-editor" textdomain, you'd think it should include the editor strings, which would mean that this change should've been the opposite.

That was my question/concern as well. The only reason I made the contrary change was because those four strings were already in `wesnoth-lib`, so they were being replicated in `wesnoth-editor` unnecessarily.

> That’s not from any established convention, as far as I know. It just happened from people copy-pasting existing dialog files.

Without knowing exactly what's going on with the domains, that's the impression I had as well.

**Comment by CelticMinstrel** [comment]
Yeah, which is why I said it's a mess…

**Comment by Wedge009** [comment]
I also put this issue as a question to ask if anything could/should be done about it. I suppose it can be revisited if anything changes with #9299.

**Comment by soliton-** [comment]
`wesnoth-lib` exists because wesnoth and the editor share strings and the editor was a separate program at some point. When merging textdomains we should probably also dissolve `wesnoth-editor`.
