### ISSUE TITLE
Exception when opening MP a second time at low resolution

### ISSUE THREAD

**Issue by white-haired-uncle** [wesnoth/wesnoth#9528]
### Game and System Information

- **Version:**
`Battle for Wesnoth v1.19.5+dev (3b7798b60d5-Modified) x86_64`
- **OS:**
`Linux spartan 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Description of the bug

```
Setting mode to 800x600
20241029 23:43:52 warning config: add-on 'GUI_Tutorial' has no _info.cfg; cannot read version info
Checking lua scripts... ok
Caught general 'N4gui236layout_exception_width_resize_failedE' exception:
std::exception
spartan$ echo $?
1
```

### Steps to reproduce the behavior

1. Change resolution to 800x600
2. Titlescreen->MP->Official server
3. If this is your first time connecting to the server (or any MP???) since you started wesnoth, it should work fine
4. Log out of MP
5. Attempt to return to official MP server
6. Wesnoth terminates

### Additional context

Same thing happens if you start wesnoth with res already set to 800x600, it will abort on second attempt to enter official MP server.

**Comment by Wedge009** [comment]
I recall 1280 width seems to be a threshold for a change in layout - I can confirm this at 1280x1024 at most, but larger than that is okay.

```
Caught general 'N4gui236layout_exception_width_resize_failedE' exception:
std::exception
```

**Comment by Wedge009** [comment]
This appears to have been introduced by @babaissarkar in 6023eb338ca1e2270243e2f1be452195cf298a30 as part of #9356. I wasn't able to replicate the problem in 1.18.3 nor 1.19.4.
