### ISSUE TITLE
Buff DF Warmaster

### ISSUE THREAD

**Issue by DuncanusDillius** [wesnoth/wesnoth#9533]
### Describe the desired feature

Currently, the DF Warmaster is very underpowered, with only a 9-4 melee attack. This is the same as the general, but the general has a ranged attack, more hitpoints and an extra movement point. The only thing that the Warmaster has that is better is that is it 9g cheaper. I personally would buff the Warmaster by changing the hitpoints to 61 and the attack to 10-4, which makes it a stronger unit within the rest of the dunefolk faction. 

@Hejnewar

**Comment by ForestDragon-wesnoth** [comment]
Good idea. Right now even luminaries can comfortably beat up warmasters under normal conditions with their 9-4 attack, liminal alignment and regen

**Comment by Gothyoba** [comment]
Completely agreed. It might even be possible to buff it more than this. I have made a PR implementing your suggested buff.
