### ISSUE TITLE
OOS when undoing in MP

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#9561]
Start a mp game, disable fog for easier testing

1. move one field
2. move again one field
3. undo 
4. undo again

> Client versions were 1.19.4 & 1.19.4+dev (45662a2f833)

**Comment by gfgtdf** [comment]
what exactly happens when you do that?

**Comment by sevu** [comment]
Everything works normal … when the unit does to comes back to the place where it started, in that moment the sync happens – but step 3 will be synced to the other client,

**Comment by sevu** [comment]
When pressing redo as a fifth step, this occurs:
![error](https://github.com/user-attachments/assets/bc48e6e8-fd86-4822-8a4b-0701069d7502)

**Comment by gfgtdf** [comment]
so just to make sure i understood it correctly, after step 4, the unit suddenly moves from its starting position to the adjacent tile on the other client?

**Comment by gfgtdf** [comment]
ithink what could have hepend is that here 

https://github.com/wesnoth/wesnoth/blob/master/src/actions/undo.cpp#L338-L355

in `undoable_action->undo(side_) ` the undo stack is not in sync with the relpay stack becasue the code calls `undos_.pop_back();` before that and `resources::recorder->undo_cut` after that, this could confuse the code which sends replay commands to the other clients.

**Comment by sevu** [comment]
> so just to make sure i understood it correctly, after step 4, the unit suddenly moves from its starting position to the adjacent tile on the other client?

yes
I also see in the log that it prints then:

> error replay: trying to undo a command that was already sent.

I you have a patch I can test it tomorrow.

**Comment by gfgtdf** [comment]
i made a pr that could fix this one https://github.com/wesnoth/wesnoth/pull/9566
