### ISSUE TITLE
Lobby: faulty <span>

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#9568]
![map](https://github.com/user-attachments/assets/dfbcadb4-253f-42e3-b5ad-1499f6258501)

Games, for which one doe snot have the scenario files, are normally displayed with a red [S]. Doesn't work in 1.19.5+dev.

**Comment by Pentarctagon** [comment]
@Vultraz or @babaissarkar any idea what would've caused this?

**Comment by babaissarkar** [comment]
Quite possibly the Markup refactor PR. I'd give this a look. Notice the second span start tag is getting it's quotes escaped.
