### ISSUE TITLE
assign loyal to unit in the editor causes an error

### ISSUE THREAD

**Issue by hermestrismi** [wesnoth/wesnoth#9580]
### Game and System Information

- **Version: BfW 1.19.5**
- **OS: Windows 10**

### Description of the bug

When you select **loyal** for a unit in the **scenario editor**, you will cause a scenario inable to be load ( missing macro **OVERLAY**)

### Steps to reproduce the behavior

1. open **editor** -> **new scenario** -> add a **unit** -> click right-> select **loyal**
2. **save** the scenario then **quit** 
3. **load** the scenario again
4. an error is shown and the scenario will be load as a **map** only 
![20241113_115240](https://github.com/user-attachments/assets/a0383915-d1d2-4a00-9397-02a819199a8a)
![20241113_115307_mfnr](https://github.com/user-attachments/assets/3b467fe5-7d90-4c08-91c2-c69d9b74920a)
![20241113_115329_mfnr](https://github.com/user-attachments/assets/f363a040-b71d-4607-bbb0-c13ed768cca8)
![20241113_115334](https://github.com/user-attachments/assets/e2f90856-eed2-477c-a8a7-ad27de439a93)
![20241113_115340](https://github.com/user-attachments/assets/6afb7ba0-cf74-4fce-b3bc-41d153115d16)
![20241113_115507](https://github.com/user-attachments/assets/319cac10-332d-4dbe-993c-8a85a2996391)
![20241113_115543](https://github.com/user-attachments/assets/d484e742-3dc4-40db-ac87-c2bc2991e85d)

### Expected behavior

**_effect / apply to_**  should be assigned by an image path instead of a macro

### Additional context

the log error is about a missing macro

**Comment by Wedge009** [comment]
I strongly suggest using screenshots from the PC instead of what looks like photos from a phone. Especially with respect to sharing text, sharing the text itself would be better.

That aside, I can confirm this in master but not 1.18.

**Comment by Wedge009** [comment]
> I can confirm this in master but not 1.18.

On closer inspection, this is partly because 1.18 doesn't save the loyal flag for the unit.

```
				id="loyal"
				male_name=_"loyal"
				[effect]
					apply_to="loyal"
				[/effect]
				[effect]
					add="{OVERLAY}"
					apply_to="overlay"
				[/effect]
```

If I remove the overlay section, the file loads okay - but the loyal flag isn't set in the Editor UI.

**Comment by soliton-** [comment]
@babaissarkar ^

This seems to be an artifact of copying from the `TRAIT_LOYAL` macro where `OVERLAY` is an optional argument that defaults to `"misc/loyal-icon.png"`.
