### ISSUE TITLE
Formatting Tags

### ISSUE THREAD

**Issue by sevu** [wesnoth/wesnoth#9583]
Another instance. This has already the patches since my last report. Built with #9575, but rebased onto master.
Also notice the empty `<i>` tags and the space in the 2nd last line.
![markup](https://github.com/user-attachments/assets/72d91267-9993-4153-bfa4-37426e9781f4)

**Comment by babaissarkar** [comment]
Does this happen when you set language to English?

**Comment by babaissarkar** [comment]
I just merged #9574, does it happen with that patch? (with no translations active)

**Comment by babaissarkar** [comment]
> > Also notice the empty `<i>` tags and the space in the 2nd last line.
> 
> Still wondering about that.

Which tooltip is it?

**Comment by babaissarkar** [comment]
That space seems to be intentional, best not to change it.

**Comment by babaissarkar** [comment]
The empty tag issue should be fixed by https://github.com/wesnoth/wesnoth/commit/e64765da2a4c328d80664ec9f01eb23ee0e4bf0b.
