### ISSUE TITLE
Incorrect screen refresh rate reported on macOS

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesnoth#9594]
### Game and System Information

- **Version:** development branch
- **OS:** macOS Sonoma 14.7.1

### Description of the bug

The screen refresh rate reported by the About dialog report function is wholly incorrect on macOS for a 2021 16" MacBook Pro with a high refresh rate (ProMotion) screen without powersave enabled. This only happens in the development branch and not in stable.

### Steps to reproduce the behavior

1. Open the About dialog from the main menu
2. Copy the report to clipboard with the relevant button

### Expected behavior

The correct refresh rate is reported in 1.18:
```
SDL:       2.28.5 (runtime 2.28.5)

[...]

SDL video drivers:        [cocoa] offscreen dummy
Window size:              1728x971
Game canvas size:         1728x971
Final render target size: 3456x1942
Screen refresh rate:      120
Screen dpi:               127.50x127.50
Renderer:                 metal (hw)
Maximum texture size:     16384x16384
VSync:                    on
```
Instead, development reports -1:
```
SDL:       2.28.5 (runtime 2.28.5)

[...]

SDL video drivers:        [cocoa] offscreen dummy
Window size:              1728x971
Game canvas size:         1728x971
Final render target size: 3456x1942
Screen refresh rate:      -1
Screen dpi:               127.50x127.50
Renderer:                 metal (hw)
Maximum texture size:     16384x16384
VSync:                    on
```

Notice that both builds were made against SDL 2.28.5.

### Additional context

These are development builds made using the provided dependencies from `Fix_Xcode_Dependencies`, with no additional changes to the Xcode project on either branch. The operating environment is exactly the same for both builds as well.

I ignore if this has any functional implications for the game. Back in the day when I added this functionality, it was used only for diagnostic logs and had no bearing on the rendering system, which was locked to a certain framerate on any hardware configuration by default without checking for the actual display refresh rate.

**Comment by Vultraz** [comment]
Is this with b859060627968b34ed0ea3bb1ee85bbae27120e6?

**Comment by irydacea** [comment]
> Is this with [b859060](https://github.com/wesnoth/wesnoth/commit/b859060627968b34ed0ea3bb1ee85bbae27120e6)?

It's the current tip of the dev branch, yes. Reverting the commit fixes the issue.

> If, so, could you test changing video::current_refresh_rate

With this change it correctly reports 120. However, I can't help but notice that this means the hardware refresh rate may always be reported here.

**Comment by Vultraz** [comment]
Indeed. I figured it made sense to report the actual rate at which the draw manager was attempting to draw the screen. It would only be different if someone uses the --max-fps option, since the idea is to set the ceiling of that value to the monitor refresh rate. But I can add to the report so it notes if the refresh rate had been artificially lowered.

**Comment by Vultraz** [comment]
Alright, I'll address it once I get home.
