### ISSUE TITLE
I can make campaign character dubbing for you

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [wesnoth/wesnoth#9601]
### Describe the desired feature

Hi,

I just have [finished](https://github.com/vcmi-mods/french-translation/pull/15#event-15361711136) to dub the Complete Edition of [_Heroes of Might and Magic III_](https://github.com/vcmi) in French. I can dub the speech of the characters speaking in the campaigns, first in English and then in other languages. The [generation](https://huggingface.co/spaces/Fabrice-TIERCELIN/Multi-language_Text-to-Speech) is pretty realistic. Just create a mute audio file that is played ingame and I will be able to generate the speech in a _Pull Request_.

PS: I can also generate music with [Udio](https://www.udio.com/).

**Comment by Pentarctagon** [comment]
Wesnoth is not accepting AI generated contributions until, at minimum, the legal questions around its use are definitively resolved.

**Comment by Fabrice-TIERCELIN** [comment]
OK
