### ISSUE TITLE
Segfault in scenario 16 of DM (Dark Sky Over Weldyn)

### ISSUE THREAD

**Issue by soliton-** [wesnoth/wesnoth#9609]
### Game and System Information

- **Version:** Battle for Wesnoth v1.19.6+dev (b8747c37-Clean) x86_64

### Description of the bug

The game segfaults at the start of scenario 16 of DM.
https://forums.wesnoth.org/viewtopic.php?t=58911

The scenario is story only ([story] followed by [endlevel] in a prestart event).

### Steps to reproduce the behavior

1. Start Delfador's Memoirs
2. :debug
3. :cl
4. Pick scenario 16

### Expected behavior

No segfault.

### Additional context

The crash happens in `report_report_countdown(reports::context const&)`
https://github.com/wesnoth/wesnoth/blob/b8747c37b06dca7399e33199a21cccd2638f5761/src/reports.cpp#L1777-L1820

**Comment by Wedge009** [comment]
Adding blocker label since this will block anyone trying to play through DM campaign on 1.19.
