### ISSUE TITLE
EI S04c: event giving the enemy a ton of money doesn't fire

### ISSUE THREAD

**Issue by Thewodoros** [wesnoth/wesnoth#9623]
This scenario has 2 events which are supposed to manipulate Mal-Ravanal's side money:
```
    [event] # manually set gold to 0
        name=side 7 turn refresh
        first_time_only=no

        [filter_condition]
            {VARIABLE_CONDITIONAL ravanal_no_income equals yes}
        [/filter_condition]

        [modify_side]
            side=7
            gold=0
        [/modify_side]
    [/event]
    [event] # manually set gold to 1000
        name=side 1
        first_time_only=no

        [filter_condition]
            {VARIABLE_CONDITIONAL ravanal_no_income not_equals yes}
        [/filter_condition]

        [modify_side]
            side=7
            gold=9999
        [/modify_side]
    [/event]
```
The variable `ravanal_no_income` is set to `yes` in `prestart` event and cleared in `ravanal_gets_serious` event, which fires on turn 10 or after killing one of enemy leaders.

# Current behavior
The first event prevents Ravanal (side 7) from recruiting before `ravanal_gets_serious` event happens.

But the second event is named incorrectly (`side 1` instead of something like `side 1 turn`), so it doesn't work at all. So after `ravanal_gets_serious` event, side 7 starts receiving income normally, but often (in my experience) goes into negative gold because of the upkeep from multiple non-loyal units spawned during `ravanal_gets_serious` event.

This code was like this since the current version of the campaign was added in #7815. So I assume all the play-testing for difficulty back then was done with this event not working.

# Solutions
I see two possible solutions:
1. If we fix the second event by renaming it, then Mal-Ravanal will recruit 4 Spectres or Wraiths each turn (limited by castle size). But that will make the scenario significantly harder, so it may need additional play-testing.
2. Alternatively, we can just delete the second event. That will not change any behavior.

I want to ask for the opinion of @Dalas121 before making a pull request.

**Comment by Dalas121** [comment]
Huh, well would you look at that. Thanks for finding this.

I agree that we shouldn't just restore the event. I don't think scenario difficulty is an issue - the player isn't intended to fight Mal-Ravanal - but spawning a gazillion units every turn will needlessly clog up the map.

Rather, I'd suggest giving Mal-Ravanal gold only if he's running low on units, and leaving it at 0 otherwise. That way we avoid affecting balance for a normal playthrough, but Mal-Ravanal's still able to fight if the player somehow defeats the rest of his forces. I haven't tested this WML, but something along these lines:

```
    [event] # if ravanal's low on units and ravanal_no_income is cleared, give him gold
        name=side 7 turn refresh
        first_time_only=no
        [filter_condition]
            {VARIABLE_CONDITIONAL ravanal_no_income not_equals yes}
            [have_unit]
                side=7
                count=0-10
            [/have_unit]
        [/filter_condition]
        [modify_side]
            side=7
            gold=500
        [/modify_side]
    [/event]
    [event] # at the end of each side 7 turn, clear Mal-Ravanal's gold so we don't go positive nor negative (looks ugly)
        name=side 7 turn end
        first_time_only=no
        [modify_side]
            side=7
            gold=0
        [/modify_side]
    [/event]
```
