### ISSUE TITLE
EI: Dunefolk and the Plague Staff

### ISSUE THREAD

**Issue by Thewodoros** [wesnoth/wesnoth#9627]
I noticed that S18 (final cutscene) contains dialogue for the case where Hahid wields the Plague Staff:
```
                [if]
                    {VARIABLE_CONDITIONAL plague_staff_wielder_id equals "Hahid al-Ali"}
                    [then]
                        [message]
                            speaker=Konrad
                            image=portraits/konrad_II.webp
                            #po: the player chose to give Hahid the plague staff
                            message= _ "Southerner, <i>necromancer</i>, know that Wesnoth will never tolerate your kind. You shall surrender that accursed stave to be destroyed, you shall foreswear the practice of all magic on penalty of death, and you are hereby exiled back to the desert wastes. Be grateful for Our mercy."
                        [/message]
                        [message]
                            speaker=Hahid al-Ali
                            message= _ "Bah, I save you barbarians from an invasion, and this is the thanks I get! What happened to being paid thrice what I’m owed? So much for northerner generosity!"
                        [/message]
                        {CLEAR_VARIABLE plague_staff_wielder_id}
                    [/then]
```
But in `utils/items.cfg`, Hahid is excluded from wearing the staff:
```
        [not]
            type_adv_tree=White Mage,Paladin
            [not]
                id=Dacyn
            [/not]
        [/not]
        [not]
            id=Owaec,Gweddry,Dacyn,Hahid al-Ali,Terraent,Konrad
        [/not]
        # messes with existing recruiting, and messes with the S18 cutscene
        # if Dacyn gets this, it also breaks his scripted advancements (and his S17a recruitment)
```
So that dialogue in the final cutscene is currently unreachable.

As Hahid can't recruit, I guess he is excluded for lore reasons. Indeed, in S10 he says
> Ugh, spellcasting always gives me the shivers. There’s a reason the more civilized people of my homeland don’t trifle with magic!

and Dunefolk's race description in `data/core/units.cfg` says
> At the same time, this analytical mindset has distanced them from magical arts; to the rational mind, magic is uncontrollable, unpredictable, and hence unreliable. For this reason, the Dunefolk especially loathe the perversions of necromancy and the dark arts, even more so than other races.
# Problems with current behavior
However, other Dunefolk who join in S04b can take the Plague staff. Also, in that case the king should use the same words as for Hahid (see code above): call them "southerner" and exile them from the kingdom, rather than the generic message (without exiling).
# Solutions
I can think of 3 possible solutions:
1. Disallow all Dunefolk from wielding the staff, and remove the unreachable dialogue for Hahid in the final cutscene. 
2. Allow Hahid (and all other dunefolk) to wield it, and add the dialogue for other Dunefolk wielders to the final cutscene. Probably also remove Hahid's anti-magic message in S10. That essentially ignores the race description.
3. Remove the unreachable dialogue for Hahid in the final cutscene without changing the current behavior.

I prefer the first one because it's more in line with the lore. @Dalas121 , what do you think?

**Comment by mytbk** [comment]
I noticed some time ago that Dolburras cannot get the plague staff (because to get Dolburras the player must go to S06a, but to get the staff the player must go to S06b) but S18 has the condition that Dolburras has the plague staff. The player can use debug command to make this happen though.

**Comment by Dalas121** [comment]
> Dolburras cannot get the plague staff (because to get Dolburras the player must go to S06a, but to get the staff the player must go to S06b)

True, thanks.

> Disallow all Dunefolk from wielding the staff, and remove the unreachable dialogue for Hahid in the final cutscene.

This is probably the best solution - but if so, we really need customizable "rejection" messages. Right now there's only 1 message for all units, which doesn't do a great job of explaining why any particular unit can't wield the staff.

If adding a customizable rejection message is challenging (last time I checked I think it was), option #3 is probably the simplest.
