### ISSUE TITLE
Planning mode keeps turning on

### ISSUE THREAD

**Issue by arobinson** [wesnoth/wesnoth#9644]
### Game and System Information

- **Version:** 1.18.3
- **OS:** Mac OSX 15.1.1 (24B91)

### Description of the bug

As of yesterday, every time I load a save game or restart wesnoth, the planning mode keeps getting turned back on. I've rebooted the app, my computer, nothing helps. I have turned it off, saved then reloaded, and yet it still gets turned back on.

I've tried turning off the hotkey, but still has the isssue.

I've been playing this game for years, I've never seen this

### Steps to reproduce the behavior

Load a save game

### Expected behavior

Planning mode should never be on once turned off.

### Additional context

I'm using the `Legend_of_the_Invincibles` add on, latest git version, not sure if that could be related

I use a Dvorak keyboard layout, but that doesn't seem to matter (tried QWERTY, same behavior).

**Comment by gfgtdf** [comment]
Sounds like you enabled the "enable planning mode on start" option in the prefrences.

**Comment by arobinson** [comment]
Thank you, it has been driving me nuts. Must have mis-clicked or something
