### ISSUE TITLE
Crash to desktop after clicking on the "view game manual" button (when no language is set)

### ISSUE THREAD

**Issue by max-torch** [wesnoth/wesnoth#9661]
### Game and System Information

The Battle for Wesnoth version 1.19.7 x86_64
Running on Microsoft Windows 11 24H2 (10.0.26100) x86_64
Distribution channel: Steam

Game paths
==========

Data dir:      C:\Program Files (x86)\Steam\steamapps\common\wesnoth
User data dir: C:\Users\USER\OneDrive\Documents\My Games\Wesnoth1.19
Saves dir:     C:\Users\USER\OneDrive\Documents\My Games\Wesnoth1.19\sync\saves
Add-ons dir:   C:\Users\USER\OneDrive\Documents\My Games\Wesnoth1.19\data\add-ons
Cache dir:     C:\Users\USER\OneDrive\Documents\My Games\Wesnoth1.19\cache
Logs dir:      C:\Users\USER\OneDrive\Documents\My Games\Wesnoth1.19\logs

Libraries
=========

Boost:             1.83
Lua:               5.4.7
OpenSSL/libcrypto: 3.1.0d-dev (runtime 3.1.0d-dev)
libcurl:           8.4.0 (runtime 8.4.0)
Cairo:             1.18.0 (runtime 1.18.0)
Pango:             1.50.14 (runtime 1.50.14)
SDL:               2.28.4 (runtime 2.28.4)
SDL_image:         2.6.3 (runtime 2.6.3)
SDL_mixer:         2.6.3 (runtime 2.6.3)

Features
========

Lua console completion:       yes
Win32 notifications back end: yes

Current video settings
======================

SDL video drivers:        [windows] offscreen dummy
Window size:              1920x1080
Game canvas size:         1920x1080
Final render target size: 1920x1080
Render refresh rate:      75
Screen refresh rate:      75
Screen dpi:               96.00x96.00
Renderer:                 direct3d11 (hw)
Maximum texture size:     16384x16384
VSync:                    on

Current audio settings
======================

SDL audio drivers:  [wasapi] directsound winmm
Number of channels: 2
Output rate:        44100 Hz
Sample format:      signed 16 bit little-endian
Sample size:        4096 bytes

Installed add-ons
=================

No add-ons installed.

### Description of the bug

When the "View Game Manual" button is clicked, the game freezes for a few seconds while the animation when the button is released is not played. Doesn't redraw after resizing the window. Then eventually a crash to desktop (about 5-20 seconds till crash depending on the machine).

### Steps to reproduce the behavior

https://github.com/user-attachments/assets/91d964ea-b252-443d-b75f-604d17193372

### Expected behavior

Game does not crash. The browser opens and becomes the active window. The game manual opens on a new tab or window in the browser.

### Additional context

Segmentation fault error log found by Sevu from discord
https://bpa.st/KQ2Q

**Comment by Vultraz** [comment]
Has something to do with the `get_language().localename` handling. If set to System Default Language, this will be empty. If you select, say, `English (US)`, it won't be, and the function will work as expected (albeit take an incredibly long time to work...)

**Comment by Wedge009** [comment]
I can confirm only when System Language is set.
