### ISSUE TITLE
Customizable highlighting for reachable/other important hexes

### ISSUE THREAD

**Issue by ForestDragon-wesnoth** [wesnoth/wesnoth#9680]
### Describe the desired feature

Decided to check 1.19 today, and saw this change:
> Hovering over units and selecting units now highlights reachable hexes instead of obscuring unreachable ones.

![image](https://github.com/user-attachments/assets/01437a7e-03e0-4eb3-ad00-d3eca106c5eb)

After some more digging, I discovered the PR that implemented this change, and that this change was done at C++ level

https://github.com/wesnoth/wesnoth/pull/9292

I believe that the new UI looks too sci-fi for wesnoth, while the older unit movement UI was nicer. 

I can understand experimenting with it exclusively in the Modern theme, but I believe that forcing this change on every single UI theme by making it hardcoded at C++ level is not a good idea, and it just doesn't fit the default theme whatsoever in my opinion.

Proposed Solution:

I believe the best way to address this issue would be to re-add support of the old "darken unreachable hexes" code, and add a new "unit_reach_mode=" parameter 
inside [gui][settings] for 1.19's GUI2 themes, with acceptable values being "darken" (the old reach UI) and "highlight", being the the UI made in PR #9292, and the C++ code will have if statements to decide which to use.

the default theme would have the value set to "darken", and modern theme would have the value set to "highlight", custom themes can be set to either value, up to the mod author's preference

This approach would also allow for additional customization in custom themes in the future, like a "highlight_reach_images" or "darken_image" parameters inside GUI2 settings, while satisfying both people who like and dislike the highlight-based method.

**Comment by babaissarkar** [comment]
> I can understand experimenting with it exclusively in the Modern theme, but I believe that forcing this change on every single UI theme by making it hardcoded at C++ level is not a good idea, and it just doesn't fit the default theme whatsoever in my opinion.

Really sorry, but it's not possible to change the hex highlighting mechanism at the WML level.
Regardless, I think it should be possible and better to do it after the in-game UI gets moved to GUI2, which should hopefully bring the problem down to the WML level instead of hardcoding it.

**Comment by Refumee** [comment]
Can this be done optional, like the new main menu?

Personally I do not like the look of it, but I feel it can be improved on, if we are allowed to modify it.
We could also add ZoC or MP-cost. It would be really nice for new players to make this more visible, as long as it is optional.

**Comment by Dalas121** [comment]
Personally, I think the older movement UI was horrifically outdated - I can't think of a single present-day game that does something similar.

But if possible I do think it would be best to make this change as part of the modern theme, so that players can choose which option they prefer. I don't know how difficult that would be to implement.

**Comment by AnekronCZ** [comment]
I tend to agree with Dalas that we can do better than darkening everything that isn't a movable hex. Clicking the unit now basically prevents you from seeing anything else, which is suboptimal in a strategy game.

But while I understand the bright colour is a boon for accessibility, I'd like a setting to make it a bit more transparent, to make the edge less pronounced.

**Comment by CelticMinstrel** [comment]
No. This can't be done with ThemeWML. It's fundamentally a different beast.

**Comment by Roge-Tebnelok** [comment]
> Clicking the unit now basically prevents you from seeing anything else, which is suboptimal in a strategy game.

It's not that bad, unless it's a map with lot of dark hexes and contrasts, and even if that's the case it depends on composition. Also, if this exact color is going to be used, we'll probably get similar issue with water, snow and mountain hexes, and they are more prevalent and benefit more from darkening, not to mention that it's just not as visually pleasing. Besides, isn't knowing what you can't do more important and optimal than what you can, as boundries of possible are more clear?

> I don't see much merit in making it customizable, either. It does its job, and it does it well.

It did before as well, if it doesn't really change anything, what's the point of this change then, and if it's possible to make it castomizable by any means, why shouldn't it be? I can't test how it affects gameplay, for some reason download page on sourceforge doesn't work for me, but from the screenshot I get the impression that it's not really convenient.

> For those who just want to change the colour or make it more transparent, you can always just edit the images, I think?

Not everyone is an artist, and even less are willing to edit gamefiles. This won't make any difference for new players, but why should veterans be forced to use something they won't necessarily like?

**Comment by Pentarctagon** [comment]
We can't add options for every small change that a particular group of players don't like. That's a very slippery slope.

**Comment by Zireael07** [comment]
The previous behavior (darken everything) made some maps nearly unplayable for me as a glasses user.

If people do not like the color used here, I think introducing an in-game option to change the RGB color tint would be a good compromise?

**Comment by ForestDragon-wesnoth** [comment]
> We can't add options for every small change that a particular group of players don't like. That's a very slippery slope towards poorly maintained code from dozens and dozens of more options.

Significantly changing the UI on such a fundamental mechanic as moving units is hardly a small change, and many even smaller UI elements (like story next/prev/skip buttons) are already configurable and moddable in 1.19. Making unit reach UI moddable too would make it consistent, give UI mods more freedom to keep a consistent style across all UI elements, and allow for modifications that faithfully recreate UIs of various different versions of the game.

**Comment by Vultraz** [comment]
Unfortunately, this is fundamentally not part of the UI itself, and adding options to change it is decidedly not trivial. I recognize that it's a somewhat controversial change, but we won't be adding further customization options for this. There's a limited amount time we all have to contribute to this game. Besides the time and effort required to implement them, they also add a maintenance burden as well.

Also note that this isn't meant to be the final design. #9542 is still pending, which should improve the look. Any other PRs that refine the new design will also be welcome!

**Comment by Jonathan-Kelly** [comment]
The original version is much nicer looking and rather cinematic. The new version is a big color clash between it and the team coloring, and it is partly filling in all the action space with a single color, thereby muting and discoloring the game's beautiful terrain and sprite art.

> I can't think of a single present-day game that does something similar.

That may just be a fashion trend. The turn based strategy genre has been around forever, so there likely is not much unexplored territory left for actual "user experience" improvements to be discovered.

**Comment by kameramen0106** [comment]
I too think the original version is much better, and as ForestDragon already pointed out, the new UI is overly sci-fi and too flashy looking. In my opinion, this does not fit the high-fantasy theme of Wesnoth. However, I am not sure if new players will necessarily feel the same as I do. Ultimately, I think the two very much need to be optional.

> That may just be a fashion trend. The turn based strategy genre has been around forever, so there likely is not much unexplored territory left for actual "user experience" improvements to be discovered.

I think this is spot on. I agree with your opinion.

**Comment by Dalas121** [comment]
> That may just be a fashion trend. The turn based strategy genre has been around forever, so there likely is not much unexplored territory left for actual "user experience" improvements to be discovered.

Sure, in the same way that "red means stop" and "green means go" is a fashion trend in traffic signaling.

I support rolling movement highlighting UI into the theme selection, if possible. But if the engine only supports a single option, I think it's hard to justify greying out unreachable hexes instead of highlighting reachable hexes (although I agree there's room for improvements like #9542 and more).`

**Comment by ForestDragon-wesnoth** [comment]
wesnoth's code passes various data between C++, WML and Lua all the time. While a good long-term solution would be to rewrite unit movement code to rely on GUI2 rather than being hardcoded at C++ level, as babaissarkar/LuminousE suggested, a medium-term solution can be to just set a new C++ variable to the value of the "unit_reach_mode" theme variable proposed earlier whenever the game is booted up and whenever the theme is switched. Then the unit reach code is triggered based on the value of the C++ variable.

**Comment by Refumee** [comment]
> We can't add options for every small change that a particular group of players don't like. That's a very slippery slope towards poorly maintained code from dozens and dozens of more options.

I fully understand that we can't make every change a option. That will be a lot of work.


> Unfortunately, this is fundamentally not part of the UI itself, and adding options to change it is decidedly not trivial. I recognize that it's a somewhat controversial change, but we won't be adding further customization options for this. There's a limited amount time we all have to contribute to this game. Besides the time and effort required to implement them, they also add a maintenance burden as well.

But I don't understand why this isn't moddable?
Sure this will be a lot of work, but we players, modders and addon creators will appreciate this approach. Isn't that what makes Wesnoth great, to give a player the freedom to modify this game and then offer others in form of an addon the creation?

We all also understand the maintance burden a new Wesnoth version brings we face that every new version. If you mean that.

**Comment by Descacharrado** [comment]
Because of my involvement in the issue at hand, I feel obliged to answer.

I strongly believe the changes I have made to the reachmap are a step towards progress and development of the game, as I saw the previous behaviour strongly outdated and far from the industry standard (if not, I would not have put the effort into #9292).

I do also think, on the other hand, that there is still room for making the reachmap better (#9542) but I think the following efforts should involve enhancing, updating or making more visually fitting the .pngs I drafted up in an afternoon, but not adding a bunch of stuff on top of the existing behaviour.

That being said, there is a clear concern about accessibility (#6133) and I'm not against adding _**some**_ options (similar to the orb coloring options) such as "reachmap color" to change it from teal and "reachmap opacity".

**Comment by eyalroz** [comment]
I just tried a 1.19.x build for the first time, and my opinion is even more negative than @ForestDragon-wesnoth . The reachable hexes tint is distracting, "busy", and annoying. I doubt new users would like it either. Please make this optional (vs. the darkening/desturation of unreachable hexes), with the default off.

I will say, though, that having the boundary indicated somehow may be an interesting third option. But, please - not with thick Cyan [frickin' laser beams](https://ih1.redbubble.net/image.149481954.5149/tst,small,845x845-pad,1000x1000,f8f8f8.u2.jpg)... that's too much.

**Comment by Dalas121** [comment]
> Wesnoth is a 20-year-old game, inspired by a 36-year-old game. Now, sure, it doesn't mean we should not modernize things, but, you know, our sprite style is "horrifically outdated", and we certainly aren't getting rid of them, right? We love it!

We already did, many times over. This is what Wesnoth used to look like:

![ancient-01](https://github.com/user-attachments/assets/62622086-a085-475c-91a7-dfe7f0f0211c)

If you mean the more general sprite style of "pixel art", a quick look through steam will show that pixel graphics are still an extremely common, modern art-style for game.

**Comment by eyalroz** [comment]
> To you the new version is distracting and annoying, to me the old version resulted in some tiles being totally unreadable as a glasses user. ... This is something that badly needs a toggle.

Fair point. (I mean, I'm not sure what you mean by a glasses user because there are all sorts of glasses and I use glasses too, but I can understand that it may have been more difficult form some than what we have now.)

@Vultraz : Please reconsider the closure of this bug... pretty please with sugar on top.
